### ISSUE TITLE
Icon Request: fa-drafting-compass

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#10001]
Drafting Compass to depict the drafting of new courses or drawing of new guidelines 
![drafting-compass](https://cloud.githubusercontent.com/assets/539719/18966674/1d4ad220-8650-11e6-931e-fd212649bb3a.png)
for use wihin a healthcare data app

**Comment by tagliala** [comment]
Duplicate of #1378, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
