### ISSUE TITLE
Icon Request: fa-etsy / fa-ebay

### ISSUE THREAD

**Issue by misspato** [FortAwesome/Font-Awesome#10009]
Hi there,

I just realized that Etsy and Ebay aren't represented on FontAwesome and it would be great to use those icons to link to these profiles as well.

Thanks!

— Patricia

**Comment by tagliala** [comment]
Duplicate of #1962 and #1783 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
