### ISSUE TITLE
Icon request: save-as

### ISSUE THREAD

**Issue by ehelkur** [FortAwesome/Font-Awesome#10014]
An icon save as: the floppy with a pencil.

Used in combination with save. Save is for saving actual document, and save-as to save the document with a new name.

regards,

**Comment by tagliala** [comment]
Duplicate of #512, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
