### ISSUE TITLE
Icon request: icon-animals

### ISSUE THREAD

**Issue by ewefunny** [FortAwesome/Font-Awesome#10010]
I'm looking at implementing some new icons for a pet site.

I've included a few examples, and really love the dog icon, sadly the rest of the icons don't follow suit, but any help would really be appreciated. Even more animals would be superb :-)

![icons](https://cloud.githubusercontent.com/assets/22580203/19023790/e21871b6-88ee-11e6-880a-2b41b0f4fad9.jpg)

**Comment by ewefunny** [comment]
I think ideally, without the boxes around them, that was just me treading carefully on a new platform :-)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by drzraf** [comment]
we all know computing is by human for human, but I'm worried that something so basic like "the other animals" is totally absent from the set. Actually there is almost nothing aside from post-1900 antrocentric concepts (except tree, paw, sun and moon). Please merge a set of animals.
