### ISSUE TITLE
Add CSS file to main attribute in bower.json

### ISSUE THREAD

**Issue by davidbayo10** [FortAwesome/Font-Awesome#10011]
Bower.json has this attrubite:

```"main": [
    "less/font-awesome.less",
    "scss/font-awesome.scss"
  ]```

Why is dont like this?
```"main": [
    "less/font-awesome.less",
    "scss/font-awesome.scss",
    "css/font-awesome.min.css"
  ]```

This CSS file is a main file. I need there for using wiredep for minifying

**Comment by tagliala** [comment]
Sorry, we are following bower specs. Please use `overrides`

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#bowerjson-not-including-css-file-in-main

**Comment by alexjose** [comment]
I don't understand why it is avoided from adding in main. [wiredep](https://github.com/taptapship/wiredep) is using main attribute for injecting the files to the html files.

**Comment by tagliala** [comment]
@alexjose because of bower specs: https://github.com/bower/spec/blob/master/json.md#main

**Comment by alexjose** [comment]
@tagliala  I read the specs, but i couldn't figure out which spec if restricting you from including the css file. 

I am just wondering how bootstrap is working fine with grunt wiredep. It would be nice if you could make it work like that.
