### ISSUE TITLE
Can we have icons for the following 

### ISSUE THREAD

**Issue by stirumala76** [FortAwesome/Font-Awesome#10013]
Can you please create icons for 

1) Evacuate
2) Receive
3) Repatriate/admit
4) SIP, shelter in place
5) register

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
