### ISSUE TITLE
Icon request: stacked charts

### ISSUE THREAD

**Issue by m1gu3l** [FortAwesome/Font-Awesome#10024]
It would be great if there were more icons for charts (f. e. horizontal bars, stacked etc). I've created some additional with FontForge.

![capture](https://cloud.githubusercontent.com/assets/140639/19116562/46891d20-8b16-11e6-9656-857745e548a9.PNG)

[FontForge project](https://github.com/FortAwesome/Font-Awesome/files/511379/fa.zip)

**Comment by blimusiek** [comment]
It look amazing.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
