### ISSUE TITLE
fa-youtube new icon

### ISSUE THREAD

**Issue by Nic787** [FortAwesome/Font-Awesome#10021]
Hi,

What about re-designing the youtube icon for the new logo?
Like 
![image](https://cloud.githubusercontent.com/assets/11185348/19086139/fa235166-8a3a-11e6-805a-a343891253e6.png)

Thank you :)

**Comment by tagliala** [comment]
@davegandy could you please take a look at this, too?

I don't know if the actual icon should exactly match youtube's logo or it is rather a youtube-like play

**Comment by Nic787** [comment]
Yeah, maybe you are right.

**Comment by Studio384** [comment]
This is the same as the fa-youtube-play icon.

**Comment by tagliala** [comment]
@Studio384 they are not perfectly the same (different border shaping, different play size, play is rounded in FA). 

Brand icons are imported as they are, without any modification, so this request is legit

**Comment by davegandy** [comment]
Updated with the latest Youtube social logo. Kept it as `youtube-play`, which I think is appropriate. This is still the secondary logo, so we'll leave `youtube` it as-is.
