### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by luchopb** [FortAwesome/Font-Awesome#10026]
Hi, I hosted myself the font and I'm trying to cache the files via AppCache API. When I go offline I get this error:

```
> Failed to decode downloaded font: https://sistemaelvis.com/ardemo2/m5/fonts/fontawesome-webfont.woff2?v=4.6.3
> OTS parsing error: invalid version tag
> 
> Failed to decode downloaded font: https://sistemaelvis.com/ardemo2/m5/fonts/fontawesome-webfont.woff?v=4.6.3
> OTS parsing error: invalid version tag
> 
> Failed to decode downloaded font: https://sistemaelvis.com/ardemo2/m5/fonts/fontawesome-webfont.ttf?v=4.6.3
> OTS parsing error: invalid version tag
> 
```

And the icons are not shown.

Someone can help me please?
Thanks

**Comment by tagliala** [comment]
try to remove the query string `?v=4.6.3` in the css

**Comment by tagliala** [comment]
ref: #3823

**Comment by luchopb** [comment]
It seems to be working now. I'm gonna give it a try and debugg in all the devices to confirm. Working with Appcache is a little tricky sometimes. I woll give you more feedback and confirm. Thank you tagliala!

**Comment by gptA** [comment]
是删除css文件中URL后边的?v=4.6.3吗？我删了也显示不出来图标

**Comment by Arunkumar-Vasudevan** [comment]
The .css file is under the Node_Modules folder and im not able to change it in git since the file gets created during NPM install. Where did you exactly delete the "?v=4.6.3" from?

**Comment by tagliala** [comment]
Hi @Arunkumar-Vasudevan this is an old issue related to FA4 and at the time we didn't had official npm packages.

> Where did you exactly delete the "?v=4.6.3" from?

This is something from the past

Please read our docs: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
