### ISSUE TITLE
Icon Request: fa-hand-shake

### ISSUE THREAD

**Issue by pedramsaleh** [FortAwesome/Font-Awesome#10035]
Hi, I'd like to request an icon of a handshake. I want to use it to represent a partnership or partners.

Something like this.

![image](https://cloud.githubusercontent.com/assets/12803855/19195777/ecae225c-8c80-11e6-8bf8-90802900b366.png)

Thanks!

**Comment by tagliala** [comment]
Already in the upcoming 4.7.0 version. Stay tuned
