### ISSUE TITLE
Icon request: Fullscreen, lowerscreen

### ISSUE THREAD

**Issue by sjiamnocna** [FortAwesome/Font-Awesome#10038]
Hi!
I'd like to see fullscreen and lowerscreen icon in the set. I use FA in my project. Im hiding sidebar by button and offer "bigger" space for editing.

I have found something like http://www.flaticon.com/free-icon/expand_126570
And also I'd apreciate reversed arrow for lowerscreen.

Thanks

**Comment by ryankane** [comment]
Why not just use [`fa-external-link `](http://fontawesome.io/icon/external-link/)

**Comment by SuperPat45** [comment]
Or something like:

![fullscreen 2x](https://user-images.githubusercontent.com/7791600/52623895-bf95db80-2ead-11e9-8e0d-e90fca5abfcd.png)

I need this one for a map component

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/expand?f=classic&s=solid
https://fontawesome.com/icons/compress?f=classic&s=solid
