### ISSUE TITLE
Icon request: rainbow

### ISSUE THREAD

**Issue by vertein** [FortAwesome/Font-Awesome#10044]
Using it as a symbol of inclusion
Using it as a symbol of good times ahead.
Using it as a symbol of fortune.
Using it as a symbol of good weather.

![image](https://cloud.githubusercontent.com/assets/5521429/19246995/a879f924-8eee-11e6-9a3d-c7d7962acc0d.png)

Thanks,

**Comment by OptikWebCreative** [comment]
i'd prefer to see this without the clouds

**Comment by Crissov** [comment]
* [🌈 U+1F308 Rainbow](http://emojipedia.org/rainbow/) – Unicode emoji

**Comment by sensibleworld** [comment]
We added a couple of rainbow icons to the latest release: https://fontawesome.com/icons?d=gallery&q=rainbow

**Comment by vertein** [comment]
Thanks!
