### ISSUE TITLE
Allow some gradual degradation if font file is not loaded

### ISSUE THREAD

**Issue by dwt** [FortAwesome/Font-Awesome#10046]
Hi there,

during a deploy of a new customer page we noticed that all their windows PCs couldn't show font-awesome icons (and our own icon fonts) in all versions of IE. After much debugging, we noticed that this was because windows has a setting that disallows downloading of font files from the internet as a security measure - which is exactly what their admins have used to impose better 'security' on all of their workspace computers.

Now, this let to the unique situation that all the font css  files where loaded, but none of the actual fonts where. Which completely broke our application. 😠

Our workaround was, to redefine our own icon font to use unicode code points that at least have a sensible fallback on windows (to my knowledge the only platform with such a setting). (But ideally all platforms should be able to provide fallbacks).

So here is what I propose: change the unicode code points of FontAwesome to use code points that have at least a semantically identical meaning, so that some fallback is possible.

The reason being: I would much rather have a not so great looking website that is still usable by clients, where I can tell them that they can change this setting and make it look great again instead of a completely unusable site where I have to solve the problem of not running with web fonts, as the client is not accepting the broken page.

**Comment by tagliala** [comment]
> So here is what I propose: change the unicode code points of FontAwesome to use code points that have at least a semantically identical meaning, so that some fallback is possible.

This is discussed here: #222, please post there your thoughts
