### ISSUE TITLE
[CDN] 504 error for stats and edit

### ISSUE THREAD

**Issue by neyp** [FortAwesome/Font-Awesome#10056]
Getting "504 Gateway Time-out" when trying to edit an embed code or access its stats.

**Comment by robmadole** [comment]
@neyp is this a consistent error?

**Comment by neyp** [comment]
Yes, it is.

**Comment by robmadole** [comment]
@neyp I'm just not seeing this yet. If you create a new embed code do you have trouble? Can you even create a new embed code?

**Comment by neyp** [comment]
I created another one with stats disabled and editing works.
