### ISSUE TITLE
Corcle Social Fonts

### ISSUE THREAD

**Issue by JuanCarlos707** [FortAwesome/Font-Awesome#10057]
What about that guys, I know u have G+, but for example, when I try to find facebook, twitter, or insta... there´s no a circle icon, so I have to call for a external resource.

What I´m tryn´to say is http://drinchev.github.io/monosocialiconsfont/

See u then guys.

**Comment by tagliala** [comment]
Thanks for sharing this. Please post your commente here, it would be very helpful and easy to find: #4167

**Comment by aethior** [comment]
@tagliala I think you can close here.
