### ISSUE TITLE
Icon Request: fa-shopping-cart-empty (fa-shopping-cart-o)

### ISSUE THREAD

**Issue by Eusebiogm87** [FortAwesome/Font-Awesome#10051]
Hello guys, i need an icon like the fa-shopping-cart but with the cart open, the icon can be exactly the same as the fa-shopping-cart but with the cart not filled.

Some use cases for this icon:

1- Indicate that the shopping cart has items or its empty (fa-shopping-cart and fa-shopping-cart-o).
2- Put the number of items in the cart inside the shopping cart icon (actually, the icon is filled if it is empty is visually better)
3- When showing the "Add to cart" button of a product, an open icon (fa-shopping-cart-o) indicate that the product is not in shopping cart and a filled icon (fa-shopping-cart) will indicate that the product is already in the shopping cart (this is exactly my use case).

Please sorry for the uggly example image, i take your icon and remove the fill part with Paint.

Thanks in advance.....

![fa-shopping-cart-o](https://cloud.githubusercontent.com/assets/12664476/19286308/c9940166-8fc2-11e6-9f13-31c9e6b583b2.png)

**Comment by OptikWebCreative** [comment]
+1

**Comment by gquipster** [comment]
+1

**Comment by sajera** [comment]
+1

**Comment by jackk100** [comment]
+1, any hollow ( -o) cart would be nice, thanks

**Comment by WebVeteran** [comment]
Same here. But I think the top of the cart should show. EX:
![shopping-cart-o](https://user-images.githubusercontent.com/40175/27610583-ee0714aa-5b5c-11e7-99b7-de3e60f1b216.png)

**Comment by d1heller** [comment]
+1

**Comment by zhublik** [comment]
+1

**Comment by PWParsons** [comment]
+1

**Comment by tagliala** [comment]
This icon is available in FA5 Pro

https://fontawesome.com/icons/shopping-cart?style=regular

**Comment by sixpeteunder** [comment]
+1
