### ISSUE TITLE
Icon Request: fa-halloween-pumpkin

### ISSUE THREAD

**Issue by Daryan997** [FortAwesome/Font-Awesome#10055]
**Requested icon:** halloween-pumpkin
**how do i use this?** I will be using this for halloween and if it's possible to add it for this year's halloween, would be glad.
**color i will be using:** #EE7906

**Comment by ryankane** [comment]
Well, I doubt it will "make it" :neutral_face: 

See: [Contributing Guidelines](../blob/master/CONTRIBUTING.md)

**Comment by AshboDev** [comment]
I can see it will have its uses but like @ryankane said, I doubt it will be fulfilled. Not enough people will use it to justify the time to design it and add it into the repo.

**Comment by Daryan997** [comment]
@AshboDev well, hope he will.

**Comment by franciscojuan1974** [comment]
Like this https://images-na.ssl-images-amazon.com/images/I/416JYZHFgrL.jpg, or not? :-D

**Comment by Crissov** [comment]
[🎃 U+1F383 Jack-o-Lantern](http://emojipedia.org/jack-o-lantern/)

**Comment by Daryan997** [comment]
@franciscojuan1974 , yeah like that and @Crissov this could help me too.. thank you

**Comment by DigitalManDan** [comment]
Was looking for something like this as well. My use case is a calendar where I have holidays listed with a preceding icon. Am using fa-tree for Christmas. Would be nice to cover the other holidays.

**Comment by Wingo5315** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks! This was added to FA Pro when 5.0 was released. Check it out here: https://fontawesome.com/icons/jack-o-lantern?style=solid
