### ISSUE TITLE
Font shorthand doesn't support rem unit | IE10 Bug

### ISSUE THREAD

**Issue by artursopelnik** [FortAwesome/Font-Awesome#10052]
The rem unit is not supported in IE10 for the font shorthand.

**Bug report:**
https://connect.microsoft.com/IE/feedback/details/772679/ie10-not-recognizing-font-decloration-when-rem-is-used-as-font-size-unit-of-measure

**Code Snippet:**
`font: normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base} FontAwesome; // shortening font declaration`
(scss/_mixins.scss) Line: 6

**Solution:**
The only work-around is to specify the font-size again after the font property, or not use the shorthand when using rem.

**Comment by tagliala** [comment]
There is another issue coming from this shorthand: #5128.

At this point, I hope Dave will go back to the old font declaration

Assigning this to 5.0.0

**Comment by artursopelnik** [comment]
@tagliala I hope so ...

Otherwise we could use the sass function [unit ](http://sass-lang.com/documentation/Sass/Script/Functions.html#unit-instance_method ) to check **$fa-font-size-base** for rem and (inform the client with @warn / or do a workaround).

**Comment by tagliala** [comment]
@artursopelnik could you please check if this is an issue?

I don't have an IE10 machine

**Comment by artursopelnik** [comment]
Has been fixed ~ Font-Shorthand removed. 👍
