### ISSUE TITLE
Podcast host logos (acast, stitcher, tunein etc)

### ISSUE THREAD

**Issue by tomking89** [FortAwesome/Font-Awesome#10053]
Hello

I run a podcast service and use FA on our website but would love to be able to use the iTunes, acast, stitcher & TuneIn logos as icons on buttons instead of having written links.

Is there any plans to add logos like these to the existing list? Surely we cant be the only people out there that would find this selection (and any other providers people use) useful?

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
