### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by fredroo** [FortAwesome/Font-Awesome#10069]
please include

payments from brazil

pagseguro
https://stc.pagseguro.uol.com.br/pagseguro/i/logos/logo_pagseguro200x41.147653728.png

and mercado pago
https://mercadopago.mlstatic.com/static/dZRhk1pgIWyEHU5A1SalB1LzXeCFPERXMSuAdjLtTHv.png

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by fredroo** [comment]
![logo_pagseguro200x41 147653728](https://cloud.githubusercontent.com/assets/6863089/19411216/a008766a-92d3-11e6-9c4c-0c04a037ccf7.png)
![dzrhk1pgiwyehu5a1salb1lzxecfperxmsuadjltthv](https://cloud.githubusercontent.com/assets/6863089/19411217/a382b3b4-92d3-11e6-8c9b-7cfc38b87917.png)

**Comment by fredroo** [comment]
@tagliala please include this payments type from brazil
