### ISSUE TITLE
Font awesome not working on my Mac OS Sierra

### ISSUE THREAD

**Issue by pkonotop** [FortAwesome/Font-Awesome#10068]
Hello,

Font Awesome isn't working for me on my Mac.

I've just upgraded my Mac OS to Sierra, and it looks like the fonts aren't working in my font book, all I get is squares with question marks inside.

Thanks,

<img width="471" alt="screen shot 2016-10-14 at 16 36 50" src="https://cloud.githubusercontent.com/assets/22840813/19393377/6df8d02c-922c-11e6-9469-0aece07ef369.png">

**Comment by tagliala** [comment]
Hi,

question marks are ok there. If you have troubles in finding the font inside Pages, please use this workaround. https://github.com/FortAwesome/Font-Awesome/issues/7056#issuecomment-154527566

Just tested FA 4.6.3 under macOS Sierra 10.12.0 and everything is fine 👍 

![image](https://cloud.githubusercontent.com/assets/556268/19399131/3895dc62-9250-11e6-9c1b-83f562bd753c.png)

Copy & Paste icons from the cheatsheet http://fontawesome.io/cheatsheet/

I will also update the troubleshooting guide

**Comment by jholt1** [comment]
I am on macOS Sierra 10.12.0, downloaded font awesome from fontawesome.io and have got the same issue

![screenshot 2016-10-17 09 55 16](https://cloud.githubusercontent.com/assets/7101754/19431295/d9930fc6-944f-11e6-96fb-80548a478e9d.png)

Here is what happens when I copy and paste from the cheatsheet

![cheatsheet](https://cloud.githubusercontent.com/assets/7101754/19431481/8a2fa344-9450-11e6-91fc-f9e46f5bce54.gif)

**Comment by tagliala** [comment]
@jholt1 #7056 (comment)

**Comment by jholt1** [comment]
@tagliala Im not sure what you are wanting me to check? In Pages it is there, but just as text? But on a different note, I am not trying to do anything in Pages? The above image is the font book.

**Comment by tagliala** [comment]
You should select icons from the [Font Awesome cheatsheet](http://fontawesome.io/cheatsheet/) and select Font Awesome as your font in your application before pasting icons

**Comment by cressie176** [comment]
I'm having similar problems to @jholt1. After installing Font Awesome the font still isn't listed pages or keynote (other manually installed fonts show up fine). Had this working with El Capitan, so not sure if the problem is specific to Sierra.

**Comment by cressie176** [comment]
Found it (cmd+t -> All Fonts)

**Comment by tagliala** [comment]
> Had this working with El Capitan

This was reported also on older versions of OSX: https://github.com/FortAwesome/Font-Awesome/issues/7056#issuecomment-154527566

**Comment by cool4zbl** [comment]
Same problem here.
![image](https://cloud.githubusercontent.com/assets/4531922/19846912/032de354-9f7e-11e6-89bd-fbbbb1c2d5cc.png)
![image](https://cloud.githubusercontent.com/assets/4531922/19846929/1326ff8e-9f7e-11e6-88b9-177bcbfebe77.png)

**Comment by mickeycoke** [comment]
1. download fontawesome.
2. unzip
3. double click fontawesome-webfont.ttf
4. font fails when installed.  All I see is ????????

https://www.evernote.com/l/AFEApdw-iN5G4I7P_ciOc0BJxshIFyZeW3c

**Comment by pkonotop** [comment]
OK so it is working for me - But you need to use the fonts library as the fonts don't show up. Use the cheat sheet (http://fontawesome.io/cheatsheet/). Copy any icon you need and paste it, it won't work/appear in some places - don't worry that's normal, because the styling/formatting for font awesome doesn't work there. But in things like pages, word, prototyping tools etc. it will work!

**Comment by tagliala** [comment]
For comparison: 

![image](https://cloud.githubusercontent.com/assets/556268/19962807/a985b262-a1b9-11e6-8021-9b8b470ae9a6.png)

![image](https://cloud.githubusercontent.com/assets/556268/19962825/c67383cc-a1b9-11e6-830e-d9338e83f83b.png)

**Comment by Crissov** [comment]
This is still a result of #222.
@mickeycoke is right, though, and `⌘2` also works.

**Comment by doostinharrell** [comment]
I was able to install the font by dropping the TTF file directly inside the fonts folder (Library/Fonts/Font Awesome.ttf) for macOS High Sierra.

**Comment by edglazer** [comment]
> Check you have your font style set to "solid". Regular wouldn't work for me, but solid made everything work.
"Solid" did the trick for me as well.

**Comment by dandouglas** [comment]
Regular worked for me and for solid I just had to choose bold.
