### ISSUE TITLE
Icon Request: fa-trending

### ISSUE THREAD

**Issue by yuzemre** [FortAwesome/Font-Awesome#10063]
![5460-200](https://cloud.githubusercontent.com/assets/17101582/19345449/f0cba416-9146-11e6-8fee-f7410ad65410.png)
Hi, I wonder if you could just add this icon. Thanks.

[http://i.imgur.com/ly5KrWL.png](http://i.imgur.com/ly5KrWL.png)

**Comment by Roumed** [comment]
+1

**Comment by tagliala** [comment]
Can I consider this a duplicate of #4397?

**Comment by Roumed** [comment]
Disagree, it would be better to have a curve without an arrow

**Comment by kreatiflog** [comment]
So will it be added?

**Comment by tagliala** [comment]
I think that the Pro icon [chart-mixed](https://fontawesome.com/v6.0/icons/chart-mixed) and the free icon [chart-line](https://fontawesome.com/v6.0/icons/chart-line) may fit this use case

Feel free to comment if this request is about a line without chart axes
