### ISSUE TITLE
Icon request: icon-pan (pot / food)

### ISSUE THREAD

**Issue by fredroo** [FortAwesome/Font-Awesome#10076]
[pan.pdf](https://github.com/FortAwesome/Font-Awesome/files/532143/pan.pdf)

Icon Food (PAN)

**Comment by tagliala** [comment]
This *could* be a duplicate.

I'm not an English Native speaker, please [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) for synonyms to confirm it isn't

**Comment by fredroo** [comment]
@tagliala 

is pan to cook food

not duplicate

not find in issues list

not exist now

please add in new versions

**Comment by fredroo** [comment]
@tagliala why you not add adsense to earn more money with this project in main page

**Comment by tagliala** [comment]
@fredroo thanks for checking that there aren't duplicates

> please add in new versions

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> @tagliala why you not add adsense to earn more money with this project in main page

There are some adv on the home page of FA but I'm not in charge of this. Feel free to open a new issue as suggestion

**Comment by Crissov** [comment]
- 🍳 U+1F373 and
- 🥘 U+1F958 in Unicode #222

**Comment by sensibleworld** [comment]
We now have:

-  a `pan-food` icon: https://fontawesome.com/v6.0/icons/pan-food?s=solid
- a `pan-frying` icon: https://fontawesome.com/v6.0/icons/pan-frying?s=solid
