### ISSUE TITLE
Icon request: icon-telegram

### ISSUE THREAD

**Issue by riobahtiar** [FortAwesome/Font-Awesome#10070]
## About Telegram
Telegram is a messaging app with a focus on speed and security, it’s super-fast, simple and free. You can use Telegram on all your devices at the same time — your messages sync seamlessly across any number of your phones, tablets or computers.
**More Info:** [Official Website Telegram](https://telegram.org/faq)
##  Use Cases
- Link to telegram channel
- Link to telegram user profile

##  Img Assets

* ![telegram 2](https://cloud.githubusercontent.com/assets/2656058/19410753/e7a627b6-931d-11e6-8c66-b5a315479acd.png)
* ![telegram 3](https://cloud.githubusercontent.com/assets/2656058/19410754/e7b19f1a-931d-11e6-8fec-36a7ce832c00.png)
* ![telegram_logo svg](https://cloud.githubusercontent.com/assets/2656058/19410755/e7bcff40-931d-11e6-86ab-cea916a6cc41.png)
* ![telegram-logo](https://cloud.githubusercontent.com/assets/2656058/19410756/e7cb7232-931d-11e6-9436-71bfebb64c7b.png)

**Comment by tagliala** [comment]
Added to the upcoming 4.7.0 version.

Please stay tuned

Ref: #3034
