### ISSUE TITLE
icon-edit is not using the entire vertical space

### ISSUE THREAD

**Issue by jbranc** [FortAwesome/Font-Awesome#1007]
when icon-edit is sitting next to other icons of the same size, it appears to be shorter than the rest.  it seems the bottom of the square doesn't go all the way to the bottom of the icon, so as a result it can look 'off' while in a line.  Its especially noticeable when you stick icon-edit next to icon-trash.

**Comment by tagliala** [comment]
Assigned to @davegandy 

More info here: #5882

**Comment by luisrudge** [comment]
Here are the pics:

![](https://cloud.githubusercontent.com/assets/941075/6544486/fe76034c-c530-11e4-8c38-594d2c90dec7.png)

![](https://cloud.githubusercontent.com/assets/941075/6561688/f2b0c79e-c671-11e4-86ab-b6bf3109d7e0.png)

**Comment by tagliala** [comment]
Seems fixed to me https://jsfiddle.net/tagliala/qq2eLxo1/18/
