### ISSUE TITLE
Spock hand glyph is backward

### ISSUE THREAD

**Issue by EricR-FW** [FortAwesome/Font-Awesome#10082]
Spock is right handed. If you are giving the Vulcan greeting and are right handed the thumb should be on the right of the image, not the left. Note the official Emoji char for Vulcan/Spock does have the thumb on the right. http://unicode.org/emoji/charts/full-emoji-list.html#1f596

**Comment by tagliala** [comment]
Thanks. Adding to 4.7.0 so Dave will eventually take a look

**Comment by tagliala** [comment]
Refs:
http://emojipedia.org/raised-hand-with-part-between-middle-and-ring-fingers/
http://fontawesome.io/icon/hand-spock-o/

**Comment by davegandy** [comment]
Oh, wow! Excellent find! We'll get this in 4.7!

**Comment by davegandy** [comment]
Added to 4.7.0 branch. Closing.

**Comment by EricR-FW** [comment]
Live long and prosper. And thanks!
