### ISSUE TITLE
Icon Request: icon-line-app

### ISSUE THREAD

**Issue by maxjame5432** [FortAwesome/Font-Awesome#10088]
This icon for LINE Messenger

Use cases:
- Share button
- Add account button (Account on LINE App)

![line-icon](https://cloud.githubusercontent.com/assets/2587798/19530475/3d8002ea-965e-11e6-802b-950f16172fcf.png)

**Comment by timtjtim** [comment]
This is a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/2631
