### ISSUE TITLE
Font not loading on Chrome for Android

### ISSUE THREAD

**Issue by LeoMeshoes** [FortAwesome/Font-Awesome#10084]
I have a website in wordpress and sources do not load in chrome, they are replaced by letters and numbers.
I tried all alternatives before opening this topic but found no solution.

Does anyone know how I can solve?

**Comment by tagliala** [comment]
Maybe there is some conflict with a plugin/javascript/css you are using. Please check them one by one

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

> 5. You are not using plugins/extensions which are loading older/modified versions of Font Awesome (ref: #1546);
6. You are not using any JavaScript or CSS libraries that reset/change/override css properties on the icon tags;

If you think there is an issue related to Font Awesome, please provide a [reduced test case](https://css-tricks.com/reduced-test-cases/)

Meanwhile, closing here.
