### ISSUE TITLE
Snapchat icon not displaying

### ISSUE THREAD

**Issue by bellaluluink** [FortAwesome/Font-Awesome#10080]
I have troubles with the snapchat icon often. Sometimes it works, but most of the time nothing appears. I use a lot of your other icons and never have trouble with them. Might there be something going on with it? 

Thanks so much in advance!

**Comment by tagliala** [comment]
Please make sure you are using FA >= 4.6

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
