### ISSUE TITLE
New icon request

### ISSUE THREAD

**Issue by OS-2017** [FortAwesome/Font-Awesome#10094]
Hi, 
I'm looking for the Instagram icon that is available in Axure. I've included it in a prototype that was approved but now I can't find the same icon - the one that is available is different. Would you please help me!

![instagram](https://cloud.githubusercontent.com/assets/22962938/19567823/3a74c27a-96bd-11e6-96cf-501fedf20369.JPG)

Thank you very much!

**Comment by tagliala** [comment]
Hi,

we are using the official instagram icon

https://www.instagram-brand.com/

**Comment by OS-2017** [comment]
The white house site displays slightly different icon and this one I used for my site, but have no idea how they got it - code is the same
https://www.whitehouse.gov/
![image](https://cloud.githubusercontent.com/assets/22962938/19571218/3a295fb6-96cb-11e6-94ae-90920cb08362.png)

**Comment by tagliala** [comment]
They are using an older version of FA (< 4.6.3)
