### ISSUE TITLE
Icon request: fa-rotation-icon

### ISSUE THREAD

**Issue by martypowell** [FortAwesome/Font-Awesome#10095]
Would be nice to have this icon, wasn't sure what the intended class name would be though.

![rotate](https://cloud.githubusercontent.com/assets/1933400/19571270/7de044fe-96cb-11e6-9d0a-52aca1ef990d.png)

**Comment by tagliala** [comment]
Do
* http://fontawesome.io/icon/repeat/
* http://fontawesome.io/icon/undo/
* http://fontawesome.io/icon/refresh/

do the job?

Or maybe a duplicate of #772

**Comment by martypowell** [comment]
@tagliala definitely a duplicate of #7729

**Comment by tagliala** [comment]
@martypowell please +1 #772, thanks
