### ISSUE TITLE
Icon Request: fa-thin-plus, fa-thin-times, fa-thin-minus

### ISSUE THREAD

**Issue by kbnuy16** [FortAwesome/Font-Awesome#10098]
Needed for more Sleek Material Page Layout.

_Can provide `.ai` and `.svg` of requested icons if necessary._

![thin-minus](https://cloud.githubusercontent.com/assets/13635472/19591123/ff44b44e-97a7-11e6-85dd-18528ec557d5.png)
![thin-plus](https://cloud.githubusercontent.com/assets/13635472/19591124/ff48ccd2-97a7-11e6-8966-78b9280d4242.png)
![thin-times](https://cloud.githubusercontent.com/assets/13635472/19591125/ff499d7e-97a7-11e6-862f-af4fbf86eeb2.png)

**Comment by Roumed** [comment]
+1

**Comment by tagliala** [comment]
Hi,

I'm going to close this one.

Ref: #1540 #2161 #1733 and [thin icons](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22thin+icon%22)

If FA doesn't fit your application layout, consider another set of thin icons

Please also consider Black Tie Light (commercial): http://blacktie.io/products/light

**Comment by kbnuy16** [comment]
@tagliala thanks for the response Sir, though I just used my SVGs and made my own Webfonts.

**Comment by bastianwegge** [comment]
Seriously what kind of answer is this? There are clearly more than 30 people publicly requesting a thinner plus button and you're telling them "go use another set of icons!".

**Comment by giandv** [comment]
I also expecting this new font-awesome :)

**Comment by fadykstas** [comment]
you can make thin signs using -webkit-text-stroke: 4px whitesmoke;

**Comment by fadykstas** [comment]
you can make thin signs using -webkit-text-stroke: 4px whitesmoke;
