### ISSUE TITLE
Icon Request: icon-faucet (water tap)

### ISSUE THREAD

**Issue by CoreyT355** [FortAwesome/Font-Awesome#10092]
Hopefully this isn't too specific to the site I work with, but an icon for a faucet would be useful I think. I have a specific use case for myself, maybe others could use it as well.
![image](https://cloud.githubusercontent.com/assets/2046973/19560556/fad0aea0-96a2-11e6-96dd-758bca0b1924.png)

**Comment by Crissov** [comment]
## Related Unicode characters (emojis)

* [🚰 U+1F6B0 Potable Water Symbol](http://emojipedia.org/potable-water-symbol/)
* [🚱 U+1F6B1 Non-Potable Water Symbol](http://emojipedia.org/non-potable-water-symbol/)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/faucet?style=solid
https://fontawesome.com/icons/faucet-drip?style=solid
