### ISSUE TITLE
Icon Request: Credit Cards (PayPal, Google Wallet, Visa, Master Card, Discover Card, Amex)

### ISSUE THREAD

**Issue by tsquez** [FortAwesome/Font-Awesome#1009]
I'd like to see some specific credit card icons.Possibly for PayPal, Google Checkout, Visa, Master Card, Discover Card, Amex. I have been searching and there really isn't anything like them out there. There are a few but they aren't very good.

**Comment by assortex** [comment]
suddenly I just found out that PayPal just released their new logo. https://www.paypal-media.com/multimedia

**Comment by htmgarcia** [comment]
@assortex good catch! An update for this icon would be nice :)

**Comment by assortex** [comment]
@htmgarcia thanks.
@tagliala will i open a new request for this or let this stay here?

**Comment by tagliala** [comment]
@assortex a new request, thanks

no need to mention me, I will find it :)
