### ISSUE TITLE
Icon request: fa-snowflake, fa-fire, fa-tools

### ISSUE THREAD

**Issue by yaldaomm** [FortAwesome/Font-Awesome#10107]
need these  for my heating and cooling business
![cooling](https://cloud.githubusercontent.com/assets/23001080/19620756/a3456940-9851-11e6-82ee-4b07d2082ea8.gif)
![heating](https://cloud.githubusercontent.com/assets/23001080/19620758/a7922088-9851-11e6-8f17-f5dd6e1e7581.gif)
![waterheaters](https://cloud.githubusercontent.com/assets/23001080/19620760/ad612bf8-9851-11e6-96ea-622b59abb275.gif)
![maintenance](https://cloud.githubusercontent.com/assets/23001080/19620761/b2b8bb7a-9851-11e6-8182-d5e2abdc1b75.gif)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by yaldaomm** [comment]
Can i request just a snowflake
