### ISSUE TITLE
Workaround Ad Block Plus

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#10109]
Workaround Ad Block Plus's blocking of certain brand icons.

**Comment by tagliala** [comment]
Ref: #1799

**Comment by tagliala** [comment]
M: Remove font-awesome generic filters

https://hg.adblockplus.org/easylist/rev/3164f12b604f

**Comment by tagliala** [comment]
Hi Dave, I will close here and a `wontfix` label for the moment

/cc @robmadole
