### ISSUE TITLE
Icon Request: fa-iota

### ISSUE THREAD

**Issue by pinpong** [FortAwesome/Font-Awesome#10106]
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="850px" height="800px" viewBox="0 0 850 800" enable-background="new 0 0 850 800" xml:space="preserve">
<g>
	<polygon fill="#FFFFFF" points="509.854,431.008 509.855,431.023 509.855,431.008 	"/>
	<polygon fill="#FFFFFF" points="405.306,407.811 405.306,407.826 405.308,407.811 	"/>
	<polygon fill="#FFFFFF" points="367.482,447.24 367.482,447.25 367.483,447.24 	"/>
	<polygon fill="#FFFFFF" points="387.161,431.303 387.161,431.311 387.161,431.303 	"/>
	<polygon fill="#FFFFFF" points="486.201,421.994 486.203,422.002 486.203,421.994 	"/>
	<path fill="#FFFFFF" d="M448.029,345.007c1.066,1.536,3.09,2.241,4.92,1.7c0.459-0.135,0.893-0.345,1.291-0.62
		c1.996-1.41,2.49-4.184,1.098-6.178c-0.824-1.188-2.209-1.897-3.707-1.897c-0.912,0-1.779,0.27-2.508,0.776
		C447.111,340.195,446.619,342.985,448.029,345.007z"/>
	<path fill="#FFFFFF" d="M436.639,333.872c0.074,1.388,0.68,2.646,1.699,3.539c1.342,1.227,3.211,1.649,4.936,1.144
		c0.928-0.276,1.756-0.803,2.391-1.52c0.93-1.03,1.396-2.354,1.322-3.735c-0.076-1.382-0.684-2.653-1.715-3.582
		c-0.904-0.811-2.119-1.259-3.418-1.259c-1.521,0-2.938,0.61-3.885,1.675C437.035,331.155,436.566,332.479,436.639,333.872z"/>
	<path fill="#FFFFFF" d="M425.257,331.311c0.899,0.496,1.911,0.759,2.921,0.759c0.576,0,1.152-0.083,1.711-0.249
		c1.533-0.451,2.797-1.466,3.555-2.858c0.787-1.411,0.975-3.035,0.533-4.582c-0.443-1.553-1.463-2.834-2.871-3.607
		c-0.83-0.454-1.795-0.695-2.791-0.695c-2.259,0-4.385,1.198-5.418,3.053C421.313,326.031,422.368,329.704,425.257,331.311z"/>
	<path fill="#FFFFFF" d="M408.661,327.793c1.227,0.34,2.598,0.333,3.863-0.035c2.333-0.691,4.127-2.493,4.793-4.82
		c0.511-1.797,0.291-3.694-0.619-5.343c-0.911-1.64-2.406-2.83-4.212-3.351c-0.571-0.161-1.174-0.244-1.784-0.244
		c-3.146,0-6.058,2.142-6.918,5.093C402.75,322.796,404.936,326.704,408.661,327.793z"/>
	<path fill="#FFFFFF" d="M388.587,328.082c0.944,0.052,1.859-0.063,2.752-0.324c3.333-0.984,5.691-3.972,5.864-7.434
		c0.116-2.203-0.638-4.317-2.124-5.954c-1.468-1.62-3.468-2.566-5.633-2.666l-0.403-0.011c-4.299,0-7.991,3.499-8.23,7.801
		C380.597,324.005,384.085,327.861,388.587,328.082z"/>
	<path fill="#FFFFFF" d="M354.589,325.993c0.815,4.586,4.791,7.914,9.453,7.915c0,0,0,0,0.001,0c0.557,0,1.119-0.05,1.674-0.147
		c0.351-0.06,0.698-0.142,1.035-0.239c4.678-1.382,7.574-6.053,6.729-10.864c-0.832-4.573-4.807-7.898-9.448-7.898
		c-0.556,0-1.116,0.05-1.667,0.146C357.165,315.879,353.672,320.854,354.589,325.993z"/>
	<path fill="#FFFFFF" d="M449.67,362.017c0.924-1.026,1.391-2.354,1.314-3.74c-0.076-1.383-0.686-2.646-1.717-3.558
		c-0.914-0.832-2.133-1.286-3.439-1.286c-1.508,0-2.908,0.603-3.836,1.651c-0.934,1.025-1.404,2.349-1.334,3.737
		c0.063,1.376,0.662,2.644,1.689,3.575c0.961,0.854,2.195,1.33,3.471,1.331c0.5,0,1-0.073,1.484-0.217
		C448.215,363.243,449.031,362.727,449.67,362.017z"/>
	<path fill="#FFFFFF" d="M437.979,349.351c-0.453-1.55-1.482-2.839-2.893-3.618c-0.836-0.458-1.803-0.702-2.797-0.702
		c-2.26,0-4.334,1.182-5.412,3.083c-1.568,2.918-0.495,6.595,2.402,8.176c0.898,0.493,1.9,0.753,2.898,0.753
		c0.574,0,1.148-0.082,1.707-0.247c1.539-0.456,2.799-1.474,3.545-2.867C438.225,352.516,438.414,350.898,437.979,349.351z"/>
	<path fill="#FFFFFF" d="M421.318,347.891c0.502-1.793,0.278-3.694-0.633-5.346c-0.915-1.633-2.41-2.814-4.204-3.324
		c-0.582-0.167-1.187-0.25-1.799-0.25c-3.148,0-6.045,2.134-6.886,5.076c-1.063,3.72,1.103,7.615,4.825,8.686
		c1.276,0.356,2.645,0.354,3.916-0.021C418.853,352.025,420.64,350.224,421.318,347.891z"/>
	<path fill="#FFFFFF" d="M401.198,345.287c0.118-2.193-0.63-4.3-2.107-5.929c-1.47-1.622-3.473-2.572-5.644-2.675
		c-0.146-0.009-0.287-0.013-0.425-0.013c-4.221,0-7.975,3.559-8.199,7.771c-0.231,4.508,3.254,8.369,7.77,8.604
		c0.159,0.009,0.315,0.014,0.469,0.014c0.773,0,1.542-0.112,2.289-0.331C398.658,351.75,401.009,348.76,401.198,345.287z"/>
	<path fill="#FFFFFF" d="M368.006,339.713c-0.552,0-1.108,0.049-1.656,0.146c-5.189,0.897-8.675,5.879-7.773,11.103
		c0.447,2.524,1.852,4.725,3.956,6.19c2.082,1.454,4.651,2.021,7.158,1.57c0.374-0.064,0.726-0.149,1.076-0.251
		c4.655-1.375,7.539-6.041,6.707-10.852C376.639,343.042,372.657,339.713,368.006,339.713z"/>
	<path fill="#FFFFFF" d="M330.243,365.362c1.763,4.151,5.801,6.835,10.286,6.835c1.061,0,2.117-0.152,3.142-0.455
		c0.424-0.124,0.853-0.28,1.273-0.458c2.776-1.188,4.919-3.372,6.029-6.152c1.111-2.765,1.075-5.794-0.1-8.533
		c-1.762-4.146-5.81-6.821-10.316-6.821c-1.505,0-2.978,0.302-4.381,0.897C330.499,353.093,327.836,359.682,330.243,365.362z"/>
	<path fill="#FFFFFF" d="M446.295,373.309c-0.842-0.467-1.816-0.713-2.822-0.713c-2.254,0-4.359,1.196-5.367,3.046
		c-1.609,2.911-0.557,6.578,2.344,8.183c1.418,0.802,3.08,0.988,4.627,0.531c1.523-0.45,2.803-1.476,3.602-2.888
		C450.26,378.574,449.193,374.907,446.295,373.309z"/>
	<path fill="#FFFFFF" d="M419.594,376.974c0.908,1.633,2.401,2.817,4.202,3.337c0.625,0.173,1.276,0.262,1.929,0.262
		c0.68,0,1.354-0.097,2-0.287c2.33-0.687,4.117-2.488,4.779-4.82c1.043-3.732-1.121-7.628-4.822-8.676
		c-0.59-0.171-1.2-0.256-1.819-0.256c-3.128,0-6.021,2.13-6.877,5.065C418.463,373.406,418.68,375.316,419.594,376.974z"/>
	<path fill="#FFFFFF" d="M412.409,372.843c0.222-4.513-3.272-8.377-7.791-8.607l-0.387-0.01c-4.238,0-7.999,3.558-8.211,7.77
		c-0.241,4.513,3.241,8.382,7.762,8.626l0.402,0.009c0.8,0,1.587-0.112,2.34-0.335C409.845,379.313,412.21,376.319,412.409,372.843z
		"/>
	<path fill="#FFFFFF" d="M379.226,386.446c0.552,0,1.11-0.05,1.658-0.146c0.359-0.063,0.705-0.146,1.045-0.247
		c4.689-1.382,7.578-6.052,6.723-10.863c-0.82-4.591-4.793-7.925-9.445-7.925c-0.556,0-1.117,0.049-1.669,0.146
		c-5.19,0.924-8.668,5.92-7.751,11.138C370.605,383.123,374.575,386.446,379.226,386.446z"/>
	<path fill="#FFFFFF" d="M362.155,392.74c1.125-2.79,1.098-5.835-0.077-8.575c-1.746-4.069-5.927-6.804-10.404-6.804
		c-1.492,0-2.938,0.298-4.298,0.885c-2.766,1.161-4.901,3.321-6.023,6.085c-1.132,2.782-1.103,5.84,0.083,8.611
		c1.77,4.145,5.815,6.822,10.31,6.822h0.001c1.068,0,2.134-0.154,3.167-0.459c0.416-0.123,0.822-0.269,1.229-0.442
		C358.899,397.696,361.035,395.521,362.155,392.74z"/>
	<path fill="#FFFFFF" d="M333.968,401.501c-2.47-3.386-6.445-5.407-10.635-5.407c-1.254,0-2.498,0.182-3.7,0.537
		c-1.434,0.422-2.785,1.09-4.017,1.986c-2.825,2.057-4.681,5.098-5.224,8.564c-0.544,3.467,0.29,6.932,2.349,9.76
		c2.462,3.389,6.441,5.414,10.644,5.414c1.252,0,2.495-0.18,3.696-0.533c1.431-0.42,2.778-1.086,4.006-1.977
		C336.932,415.568,338.226,407.338,333.968,401.501z"/>
	<path fill="#FFFFFF" d="M475.154,447.473c-0.195-2.283-2.154-4.074-4.453-4.074c-0.129,0-0.258,0.006-0.387,0.016
		c-1.898,0.16-3.479,1.531-3.932,3.412c-0.111,0.467-0.146,0.936-0.107,1.434c0.209,2.266,2.148,4.047,4.42,4.047l0,0
		c0.127,0,0.254-0.006,0.383-0.016c1.15-0.094,2.248-0.672,3.02-1.586C474.879,449.783,475.254,448.635,475.154,447.473z"/>
	<path fill="#FFFFFF" d="M478.285,442.52c-0.225,0.943-0.186,1.924,0.117,2.84c0.861,2.652,3.844,4.188,6.533,3.314
		c1.242-0.406,2.316-1.359,2.947-2.607c0.631-1.252,0.756-2.682,0.344-3.926c-0.418-1.324-1.33-2.391-2.57-3.018
		c-0.727-0.371-1.527-0.566-2.32-0.566c-0.543,0-1.08,0.09-1.598,0.266C479.99,439.375,478.707,440.754,478.285,442.52z"/>
	<path fill="#FFFFFF" d="M490.809,434.299c-0.379,1.553-0.131,3.15,0.697,4.508c0.83,1.389,2.141,2.361,3.701,2.75
		c0.486,0.123,0.986,0.186,1.479,0.186c0.002,0,0.002,0,0.002,0c1.08,0,2.143-0.301,3.076-0.867
		c2.746-1.664,3.713-5.535,2.066-8.283c-1.09-1.785-3.078-2.898-5.188-2.898c-1.084,0-2.148,0.293-3.078,0.848
		C492.168,431.385,491.188,432.719,490.809,434.299z"/>
	<path fill="#FFFFFF" d="M509.855,429.988c1.822,0,3.553-0.701,4.873-1.973c2.67-2.594,2.742-7.25,0.152-9.961
		c-1.322-1.35-3.115-2.098-5.039-2.098c-1.85,0-3.602,0.701-4.936,1.973c-0.926,0.908-1.586,2.074-1.898,3.361
		c-0.57,2.369,0.094,4.822,1.775,6.561c1.305,1.344,3.059,2.102,4.938,2.135l0.133,1.021h0.002V429.988z"/>
	<path fill="#FFFFFF" d="M528.449,409.334c2.416-3.727,1.301-8.933-2.43-11.371c-1.324-0.852-2.859-1.303-4.434-1.303
		c-2.807,0-5.383,1.398-6.893,3.743c-0.506,0.781-0.875,1.636-1.096,2.544c-0.814,3.377,0.596,6.912,3.508,8.793
		c1.336,0.869,2.877,1.328,4.455,1.328c0.586,0,1.18-0.063,1.764-0.188C525.457,412.418,527.279,411.156,528.449,409.334z"/>
	<path fill="#FFFFFF" d="M533.504,372.002c-1.053-0.382-2.148-0.575-3.258-0.575c-4.023,0-7.656,2.543-9.035,6.327
		c-0.125,0.336-0.225,0.678-0.311,1.02c-1.143,4.741,1.455,9.584,6.045,11.257c1.039,0.372,2.127,0.562,3.229,0.562
		c4.037,0,7.67-2.537,9.041-6.312C540.973,379.29,538.412,373.778,533.504,372.002z"/>
	<path fill="#FFFFFF" d="M454.656,433.537c-0.225,0.922-0.188,1.889,0.109,2.795c0.426,1.316,1.344,2.381,2.58,3.006
		c0.732,0.371,1.512,0.561,2.32,0.561c0.547,0,1.094-0.09,1.625-0.266c1.258-0.402,2.338-1.35,2.971-2.6
		c0.631-1.24,0.756-2.658,0.348-3.885c-0.424-1.318-1.334-2.389-2.572-3.025c-0.738-0.381-1.527-0.576-2.348-0.576
		c-0.535,0-1.07,0.086-1.594,0.254C456.371,430.375,455.078,431.775,454.656,433.537z"/>
	<path fill="#FFFFFF" d="M471.58,432.541c1.535,0.373,3.215,0.127,4.578-0.697c2.764-1.68,3.701-5.48,2.043-8.301
		c-1.109-1.791-3.053-2.873-5.188-2.873c-1.094,0-2.164,0.301-3.096,0.867c-1.387,0.842-2.357,2.166-2.736,3.736
		c-0.375,1.561-0.125,3.162,0.709,4.504C468.713,431.168,470.02,432.143,471.58,432.541z"/>
	<path fill="#FFFFFF" d="M486.203,420.967c1.846,0,3.586-0.703,4.896-1.98c1.281-1.234,2.033-3.027,2.066-4.922
		c0.033-1.9-0.66-3.729-1.902-5.012c-1.33-1.375-3.123-2.133-5.047-2.133c-1.836,0-3.57,0.699-4.889,1.969
		c-0.955,0.936-1.627,2.115-1.939,3.402c-0.563,2.346,0.104,4.795,1.785,6.553c1.305,1.332,3.063,2.09,4.945,2.123l0.082,1.027
		h0.002V420.967z"/>
	<path fill="#FFFFFF" d="M504.816,400.31c1.162-1.783,1.549-3.961,1.088-6.139c-0.455-2.161-1.729-4.061-3.494-5.209
		c-1.326-0.858-2.861-1.313-4.439-1.313c-2.801,0-5.381,1.398-6.898,3.738c-0.512,0.779-0.881,1.635-1.104,2.547
		c-0.809,3.355,0.607,6.886,3.52,8.787c1.336,0.867,2.873,1.326,4.443,1.326c0.58,0,1.168-0.063,1.744-0.186
		C501.816,403.396,503.641,402.135,504.816,400.31z"/>
	<path fill="#FFFFFF" d="M503.334,381.007c1.033,0.37,2.121,0.56,3.223,0.56c4.041,0,7.68-2.537,9.059-6.313
		c1.816-4.943-0.756-10.453-5.73-12.284c-1.059-0.386-2.164-0.58-3.279-0.58c-1.404,0-2.77,0.306-4.057,0.909
		c-2.318,1.085-4.072,3.009-4.941,5.416c-0.131,0.357-0.234,0.707-0.322,1.062C496.15,374.49,498.75,379.321,503.334,381.007z"/>
	<path fill="#FFFFFF" d="M508.855,353.482c0.459,0.057,0.914,0.084,1.365,0.084l0,0c5.645,0,10.422-4.235,11.113-9.853
		c0.744-6.125-3.631-11.726-9.756-12.482c-0.461-0.057-0.924-0.084-1.381-0.084c-5.182,0-9.645,3.505-10.855,8.524
		c-0.105,0.43-0.184,0.879-0.24,1.333c-0.361,2.994,0.461,5.944,2.314,8.298C503.252,351.644,505.895,353.129,508.855,353.482z"/>
	<path fill="#FFFFFF" d="M449.375,423.998c0.385-1.574,0.156-3.211-0.629-4.494c-1.086-1.803-3.064-2.92-5.172-2.92
		c-1.086,0-2.154,0.297-3.088,0.861c-1.41,0.834-2.391,2.16-2.77,3.738c-0.373,1.545-0.125,3.166,0.697,4.563
		c1.096,1.799,3.027,2.881,5.16,2.881c1.092,0,2.164-0.299,3.1-0.863C447.998,426.969,448.982,425.596,449.375,423.998z"/>
	<path fill="#FFFFFF" d="M456.762,416.865h0.002c1.834,0,3.561-0.697,4.861-1.963c2.693-2.588,2.777-7.227,0.184-9.934
		c-1.307-1.355-3.066-2.127-4.961-2.164h-0.002c-1.928,0-3.664,0.699-4.99,1.973c-0.951,0.938-1.627,2.125-1.941,3.416
		c-0.568,2.359,0.1,4.811,1.787,6.553C453.039,416.111,454.838,416.865,456.762,416.865z"/>
	<path fill="#FFFFFF" d="M464.021,398.65c1.322,0.854,2.859,1.308,4.438,1.308c2.807,0,5.391-1.403,6.91-3.751
		c2.371-3.666,1.24-8.959-2.42-11.326c-1.33-0.866-2.869-1.323-4.451-1.323c-2.797,0-5.377,1.396-6.9,3.733
		c-0.508,0.787-0.875,1.644-1.09,2.538C459.697,393.194,461.107,396.739,464.021,398.65z"/>
	<path fill="#FFFFFF" d="M480.389,358.884c-1.043-0.377-2.133-0.568-3.238-0.568c-4.02,0-7.646,2.534-9.023,6.305
		c-0.125,0.34-0.227,0.678-0.307,1.022c-1.148,4.756,1.451,9.594,6.045,11.261c1.051,0.38,2.148,0.572,3.258,0.572
		c4.031,0,7.662-2.536,9.035-6.312C487.953,366.208,485.365,360.698,480.389,358.884z"/>
	<path fill="#FFFFFF" d="M482.1,327.136c-0.457-0.056-0.912-0.082-1.359-0.082c-5.195,0-9.672,3.525-10.891,8.573
		c-0.102,0.422-0.18,0.843-0.23,1.277c-0.367,2.98,0.449,5.916,2.297,8.273c1.852,2.37,4.504,3.87,7.467,4.224
		c0.434,0.053,0.869,0.078,1.301,0.078l0,0c5.623,0,10.529-4.326,11.172-9.85c0.377-2.979-0.426-5.908-2.258-8.261
		C487.758,328.999,485.094,327.496,482.1,327.136z"/>
	<path fill="#FFFFFF" d="M477.02,316.463c0.463,0,0.932-0.024,1.402-0.075c5.516-0.592,10.092-4.601,11.385-9.977
		c0.352-1.454,0.447-2.96,0.289-4.473c-0.711-6.685-6.316-11.728-13.039-11.728c-0.461,0-0.924,0.024-1.393,0.074
		c-5.518,0.578-10.098,4.589-11.4,9.979c-0.35,1.463-0.445,2.964-0.287,4.458C464.699,311.414,470.307,316.463,477.02,316.463z"/>
	<path fill="#FFFFFF" d="M372.96,408.4c-0.348-0.33-0.736-0.594-1.186-0.809c-0.578-0.266-1.205-0.404-1.854-0.404
		c-1.732,0-3.32,1-4.043,2.547c-0.492,1.043-0.541,2.285-0.136,3.41c0.409,1.135,1.217,2.035,2.273,2.531
		c0.591,0.275,1.221,0.416,1.871,0.416c0.001,0,0.001,0,0.001,0c1.733,0,3.327-1.012,4.061-2.578
		C374.76,411.789,374.362,409.734,372.96,408.4z"/>
	<path fill="#FFFFFF" d="M368.229,419.549c-0.368-0.078-0.731-0.117-1.093-0.117c-2.419,0-4.543,1.729-5.051,4.113
		c-0.269,1.279,0.019,2.689,0.787,3.861c0.769,1.17,1.942,1.992,3.225,2.254c1.383,0.309,2.74,0.039,3.902-0.715
		c1.163-0.76,1.95-1.912,2.216-3.246c0.395-1.787-0.159-3.59-1.478-4.844C370.03,420.191,369.16,419.736,368.229,419.549z"/>
	<path fill="#FFFFFF" d="M367.567,446.215c3.304-0.076,5.957-2.828,5.906-6.133c-0.032-1.631-0.698-3.148-1.875-4.266
		c-1.116-1.063-2.57-1.648-4.094-1.648c-1.775,0.023-3.276,0.672-4.396,1.826c-1.121,1.162-1.721,2.688-1.688,4.289
		c0.07,3.16,2.901,5.932,6.062,5.932l-0.001,1.025c0,0,0,0,0.001,0L367.567,446.215z"/>
	<path fill="#FFFFFF" d="M372.056,464.975c0.532,0,1.063-0.064,1.572-0.189c3.725-0.955,6.018-4.803,5.099-8.572
		c-0.326-1.256-1.007-2.412-1.964-3.328c-1.327-1.256-3.054-1.951-4.857-1.951c-0.575,0-1.152,0.07-1.715,0.211
		c-1.812,0.455-3.347,1.596-4.319,3.211c-0.963,1.604-1.245,3.494-0.793,5.314C365.842,462.691,368.841,464.973,372.056,464.975z"/>
	<path fill="#FFFFFF" d="M385.459,484.479c4.018-2.068,5.613-7.014,3.551-11.023c-0.424-0.832-0.979-1.58-1.654-2.221
		c-1.529-1.459-3.542-2.26-5.662-2.26c-1.287,0-2.569,0.309-3.71,0.893c-1.963,1.004-3.418,2.717-4.095,4.82
		c-0.668,2.08-0.487,4.287,0.51,6.213c1.376,2.695,4.295,4.434,7.436,4.434C383.12,485.334,384.34,485.047,385.459,484.479z"/>
	<path fill="#FFFFFF" d="M405.365,490.42c-0.229-0.277-0.476-0.535-0.731-0.783c-1.785-1.695-4.133-2.635-6.602-2.635
		c-2.248,0-4.438,0.799-6.166,2.246c-4.022,3.412-4.542,9.469-1.154,13.504c1.855,2.162,4.551,3.408,7.39,3.408
		c2.234,0,4.399-0.787,6.1-2.221C408.241,500.539,408.764,494.473,405.365,490.42z"/>
	<path fill="#FFFFFF" d="M387.857,403.584c-0.354-0.076-0.717-0.111-1.075-0.111c-0.995,0-1.971,0.291-2.823,0.844
		c-1.155,0.756-1.944,1.916-2.22,3.27c-0.281,1.293-0.003,2.701,0.762,3.875c0.76,1.166,1.923,1.984,3.191,2.242
		c1.381,0.301,2.742,0.033,3.906-0.715c1.158-0.742,1.957-1.896,2.253-3.25c0.365-1.781-0.201-3.598-1.517-4.85
		C389.646,404.234,388.79,403.783,387.857,403.584z"/>
	<path fill="#FFFFFF" d="M387.213,430.275c3.312-0.1,5.96-2.869,5.88-6.172c-0.034-1.619-0.697-3.121-1.865-4.234
		c-1.113-1.057-2.555-1.641-4.063-1.641l-0.215,0.004c-1.595,0.018-3.091,0.66-4.215,1.811c-1.116,1.168-1.718,2.703-1.687,4.318
		c0.069,3.205,2.869,5.914,6.113,5.914l-0.001,1.027l0,0L387.213,430.275z"/>
	<path fill="#FFFFFF" d="M385.487,438.422c-0.955,1.611-1.233,3.496-0.777,5.301c0.754,3.027,3.738,5.307,6.943,5.307
		c0.536,0,1.067-0.064,1.58-0.193c3.751-0.941,6.043-4.766,5.107-8.521c-0.33-1.295-1.013-2.465-1.976-3.381
		c-1.316-1.25-3.04-1.939-4.852-1.939c-0.574,0-1.149,0.07-1.712,0.209C387.997,435.664,386.461,436.807,385.487,438.422z"/>
	<path fill="#FFFFFF" d="M393.525,458.719c-0.669,2.084-0.49,4.295,0.504,6.223c1.367,2.701,4.284,4.441,7.435,4.441h0.001
		c1.261,0,2.505-0.293,3.595-0.848c4.021-2.055,5.622-7.006,3.568-11.033c-0.421-0.832-0.978-1.582-1.657-2.232
		c-1.516-1.439-3.518-2.234-5.635-2.234c-1.29,0-2.58,0.309-3.729,0.891C395.646,454.922,394.197,456.625,393.525,458.719z"/>
	<path fill="#FFFFFF" d="M424.993,474.498c-0.244-0.295-0.498-0.559-0.762-0.816c-1.771-1.682-4.107-2.615-6.568-2.615
		c-2.248,0-4.441,0.797-6.176,2.242c-4.016,3.412-4.538,9.479-1.158,13.514c1.818,2.18,4.483,3.428,7.313,3.428
		c2.251,0,4.448-0.797,6.188-2.244c1.964-1.652,3.168-3.971,3.386-6.523C427.436,478.936,426.646,476.457,424.993,474.498z"/>
	<path fill="#FFFFFF" d="M449.281,490.52c-0.318-0.301-0.668-0.596-1.035-0.873c-1.973-1.479-4.303-2.262-6.732-2.262
		c-0.535,0-1.072,0.039-1.611,0.117c-2.945,0.42-5.551,1.967-7.34,4.354c-1.789,2.377-2.549,5.314-2.141,8.27
		c0.41,2.975,1.959,5.607,4.361,7.416c1.953,1.471,4.279,2.248,6.725,2.248c3.561,0,6.828-1.623,8.963-4.449
		C453.895,500.795,453.383,494.424,449.281,490.52z"/>
	<path fill="#FFFFFF" d="M405.44,406.789c3.325-0.063,5.977-2.807,5.914-6.123c-0.016-1.636-0.675-3.15-1.853-4.269
		c-1.14-1.083-2.646-1.679-4.246-1.679c-3.353,0.077-5.995,2.834-5.932,6.144c0.057,3.159,2.852,5.929,5.981,5.929v1.02
		c0,0,0.001,0,0.002,0L405.44,406.789z"/>
	<path fill="#FFFFFF" d="M402.985,420.242c0.748,3.031,3.734,5.313,6.948,5.313c0.53,0,1.057-0.063,1.563-0.186
		c1.829-0.453,3.376-1.594,4.352-3.211c0.959-1.604,1.24-3.49,0.79-5.313c-0.336-1.295-1.024-2.471-1.988-3.389
		c-1.315-1.256-3.035-1.945-4.838-1.945c-0.579,0-1.159,0.072-1.726,0.215C404.333,412.693,402.041,416.516,402.985,420.242z"/>
	<path fill="#FFFFFF" d="M412.307,441.494c1.372,2.682,4.286,4.414,7.424,4.414h0.001c1.264,0,2.506-0.293,3.595-0.85
		c4.027-2.047,5.635-6.994,3.587-11.033c-0.429-0.832-0.986-1.578-1.654-2.215c-1.528-1.453-3.541-2.254-5.668-2.254
		c-1.288,0-2.576,0.309-3.726,0.889C411.843,432.506,410.244,437.465,412.307,441.494z"/>
	<path fill="#FFFFFF" d="M428.598,463.357c1.824,2.166,4.488,3.412,7.311,3.412l0,0c2.262,0,4.467-0.805,6.211-2.266
		c4.025-3.396,4.549-9.447,1.164-13.49c-0.23-0.271-0.475-0.531-0.732-0.773c-1.797-1.713-4.143-2.652-6.607-2.652
		c-2.25,0-4.441,0.801-6.17,2.254C425.732,453.254,425.204,459.316,428.598,463.357z"/>
	<path fill="#FFFFFF" d="M468.758,481.859c3.416-4.557,2.887-10.943-1.229-14.855c-0.314-0.299-0.639-0.578-0.992-0.84
		c-1.963-1.48-4.285-2.264-6.719-2.264c-0.529,0-1.063,0.039-1.596,0.113c-2.977,0.418-5.6,1.967-7.389,4.357
		c-1.783,2.387-2.523,5.359-2.086,8.371c0.434,2.975,1.965,5.574,4.313,7.318c1.969,1.494,4.293,2.281,6.729,2.281
		c0.516,0,1.033-0.035,1.553-0.107C464.314,485.826,466.947,484.271,468.758,481.859z"/>
	<path fill="#FFFFFF" d="M500.947,479.85c-1.086-1.031-2.336-1.867-3.719-2.486c-1.682-0.742-3.465-1.117-5.295-1.117
		c-5.207,0-9.928,3.061-12.029,7.797c-2.246,5.076-1.061,11.045,2.947,14.852c1.078,1.023,2.334,1.859,3.732,2.488
		c1.68,0.744,3.461,1.125,5.291,1.125l0,0c5.195,0,9.91-3.063,12.016-7.801C506.148,489.641,504.967,483.67,500.947,479.85z"/>
</g>
</svg>

**Comment by pinpong** [comment]
![logo](https://cloud.githubusercontent.com/assets/1012532/19620060/d06fb6aa-9874-11e6-89fe-ff58745fa9d9.png)

and here with inverted colors

**Comment by tagliala** [comment]
Could you please provide more details?

Is this a brand?

**Comment by pinpong** [comment]
Hy, iota is a foundation. iotatoken.com

Its a new cryptocurrency.

**Comment by pinpong** [comment]
Whats up? A donation ist required?

**Comment by tagliala** [comment]
@pinpong nope, donations are not required

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

There is also a kickstarter campaign at the moment: https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by pinpong** [comment]
added new svg

**Comment by William2030** [comment]
+1

**Comment by carpenterdev** [comment]
pinpong - hanks for getting this added!

Bob
