### ISSUE TITLE
Icon request: icon-fence icon-pole

### ISSUE THREAD

**Issue by francoisdug** [FortAwesome/Font-Awesome#10108]
Hi,

I was astonished to see that there is no pole/stick icon or even a fence icon.
Here the 3 icons, that can be very usefull I guess :)
![fence2](https://cloud.githubusercontent.com/assets/7413084/19622845/4fbdfe28-98b4-11e6-8117-4ecad2f0fa1f.jpg)
![fences-icon-614x460](https://cloud.githubusercontent.com/assets/7413084/19622846/4fc3718c-98b4-11e6-9201-903ced604668.png)
![pole](https://cloud.githubusercontent.com/assets/7413084/19622847/4fcad0b2-98b4-11e6-826b-44a7c1d14a06.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
