### ISSUE TITLE
Icon request : All Mobile brands 

### ISSUE THREAD

**Issue by mujeebdgk** [FortAwesome/Font-Awesome#10105]
Companies like 
Qmobile 
lenovo
Sony
Samsung
Huawei 
LG
Micromax
HP
Dell
Alcatel ETC

All of the mobiles icon should be in Font Awesom :)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
