### ISSUE TITLE
Icon Color not changing in Samsung Galaxy Note 4

### ISSUE THREAD

**Issue by adisofttech** [FortAwesome/Font-Awesome#10113]
hello ,
I am changing icon color at Runtime . its working good in other device but not in 
Samsung Galaxy Note 4 android 6.0.1 (marshmallow) 
please provide solution for me.

**Comment by tagliala** [comment]
Please provide more details or better a [fiddle](https://jsfiddle.net/tagliala/4Lcpvhoo/) showing the issue

**Comment by adisofttech** [comment]
I am using below button in xml 
  <Button
            android:id="@+id/btn1"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_margin="5dp"
            android:textSize="20dp"
            android:text="@string/fa_android"
            android:background="@android:color/transparent"/> 

and set font like 

Typeface font = Typeface.createFromAsset(getAssets(), "fontawesome-webfont.ttf");
btn1.setTypeface(font);
 btn1.setTextColor(Color.parseColor("#FF0000"));

Its working in other devices but not in Samsung Galaxy Note 4

**Comment by tagliala** [comment]
Closing here because of inactivity

If this is still an issue, feel free to fill out a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
