### ISSUE TITLE
Icon request: fa-pie-chart-100, fa-pie-chart-75, fa-pie-chart-75-25, fa-pie-chart-50, fa-pie-chart-50-50, fa-pie-chart-25, fa-pie-chart-25-75 (set)

### ISSUE THREAD

**Issue by kheldorn** [FortAwesome/Font-Awesome#10116]
I'd like to request a number of pie-chart icons representing different combinations of 25% chunks of the total pie.

I'm currently using image icons for this, e.g. to represent the user's progress of collecting a set of items and whether they are still actively collecting based on their last update.
For example:
- The 100% pie-chart represents that they completed their collection.
- The 75% pie-chart represents that they collected more than 50% of the collection but haven't updated their list in the last 3 months.
- The 75%+25% pie-chart represents that they collected more than 50% of the collection and are actively collecting.
- ... and so on

What I'm looking for:

fa-pie-chart-100:
![pie-chart-100](https://cloud.githubusercontent.com/assets/13883080/19703946/199d37ec-9b06-11e6-8c55-fff0871c9496.png)

fa-pie-chart-75:
![pie-chart-75](https://cloud.githubusercontent.com/assets/13883080/19703955/1fe74052-9b06-11e6-843b-3a567037b788.png)

fa-pie-chart-75-25:
![pie-chart-75-25](https://cloud.githubusercontent.com/assets/13883080/19703968/301c1c68-9b06-11e6-8e4a-8ffbcff092f4.png)

fa-pie-chart-50:
![pie-chart-50](https://cloud.githubusercontent.com/assets/13883080/19703979/38d40460-9b06-11e6-8199-5d5debf1b33d.png)

fa-pie-chart-50-50:
![pie-chart-50-50](https://cloud.githubusercontent.com/assets/13883080/19703983/3d6366b0-9b06-11e6-8d5a-89bdf26c709b.png)

fa-pie-chart-25:
![pie-chart-25](https://cloud.githubusercontent.com/assets/13883080/19703996/48c5ce12-9b06-11e6-8cea-b09b98f98142.png)

fa-pie-chart-25-75:
![pie-chart-25-75](https://cloud.githubusercontent.com/assets/13883080/19704010/527dc4b4-9b06-11e6-83ad-0d0747edd0eb.png)

I don't have any real experience creating svg graphics, but I'll supply them on short notice if this will get these icons implemented sooner.

**Comment by timmyrs** [comment]
I feel like all of these would be better flipped horizontally.

**Comment by narutards** [comment]
Flipped or otherwise rotated doesn't help me.

**Comment by fsailer** [comment]
+1 but would prefer to come in line with the circle-o icons

**Comment by shenghou** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by sensibleworld** [comment]
We a few options for these now:

https://fontawesome.com/icons/circle-three-quarters?f=classic&s=solid
https://fontawesome.com/icons/circle-quarter?s=solid&f=classic
https://fontawesome.com/icons/circle-half?s=solid&f=classic
https://fontawesome.com/icons/circle-half-stroke?s=solid&f=classic

https://fontawesome.com/icons/chart-pie?s=solid&f=classic
https://fontawesome.com/icons/chart-pie-simple?s=solid&f=classic
