### ISSUE TITLE
Add "speed" filter to "tachometer"

### ISSUE THREAD

**Issue by nighto** [FortAwesome/Font-Awesome#10115]

**Comment by tagliala** [comment]
I'm adding filters tho the docs when I see alias requests.

The difference is that you can search by filters in the docs but you can't use `fa-speed` in your css.

I prefer filters because:

1. Aliases bloat the CSS
2. you can add aliases via custom css, if you really need `fa-speed`.

**Comment by nighto** [comment]
That's fine by me. It's just because I thought there was no speedometer, but then searching visually through all icons I found the tachometer. :smiley:

**Comment by tagliala** [comment]
Hmmm... just noticed that there is a bug in the docs for gavel and tachometer icon, I need to check with Dave

**Comment by tagliala** [comment]
@nighto thanks, there was a bug in the docs. When they will be refreshed, you should be able to search for speed. I will take a look in the next days

**Comment by nighto** [comment]
Thanks!
