### ISSUE TITLE
Request for new icon

### ISSUE THREAD

**Issue by quaisar** [FortAwesome/Font-Awesome#10117]
Hello sir can you please add a new icon in Font-Awesome 
That is "Blog" icon see the link below
http://www.logospike.com/wp-content/uploads/2014/11/Blogger_logo-4.png

**Comment by tagliala** [comment]
Duplicate of #1088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
