### ISSUE TITLE
stats.js in FontAwesome CDN script includes babel-polyfill

### ISSUE THREAD

**Issue by SethTompkins** [FortAwesome/Font-Awesome#10120]
Hello, the stats.js script that is included with the FontAwesome CDN by default includes babel-polyfill. This will break sites that use babel-polyfill as only one instance of the polyfill can exist in any given context.

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by robmadole** [comment]
I probably need to switch to a different polyfill since Babel's doesn't behave well in this scenario. I'll see what I can find.

**Comment by SethTompkins** [comment]
@robmadole, you might look into https://babeljs.io/docs/plugins/transform-runtime/. It polyfills new globals inline in your code rather than globally. This would prevent clashes with userland polyfills like babel-polyfill.

If you are using new instance methods such as `Array.prototype.includes`, you will need to find additional polyfills for those.

**Comment by robmadole** [comment]
Ah perfect. I didn't know about that. Thanks @SethTompkins I'll get this integrated.

**Comment by robmadole** [comment]
I have a candidate fix for this going through our build process. I'll let you know when this is up and you can give it a try @SethTompkins.

**Comment by robmadole** [comment]
@SethTompkins this has been deployed now. When you get a chance can you give this a try?

**Comment by SethTompkins** [comment]
Looks good on my end, thanks for the quick response :)

**Comment by robmadole** [comment]
Thanks for the help!
