### ISSUE TITLE
Icon request:  icon-toilet

### ISSUE THREAD

**Issue by erikaursi** [FortAwesome/Font-Awesome#10126]
Hi!
I'm a designer who creates layouts for websites. I currently work for a website that sells real estate and vehicles that uses FontAwesome icons by default.
I'd like an icon for a half bath and it would be a toilet icon. The “fa-bath” and “fa-shower” icons already available at FontAwesome are more suitable for bathrooms with bath/shower options and are not suited for half baths and restaurant restrooms.
I believe it will be very useful for the FontAwesome community and I'd appreciate it if made available.
Here are some images for reference.
![icons_toilet](https://cloud.githubusercontent.com/assets/23098388/19765830/4807ecca-9c29-11e6-808f-a840b83bdd82.jpg)

**Comment by tagliala** [comment]
IIRC this is a duplicate.

We are using #2670 for this sign, could you please provide synonyms which actually represent the above object?

**Comment by erikaursi** [comment]
Hi, I don’t know how else we can call this icon. It will be used in websites selling real estate properties that have bathrooms AND half baths, meaning a room with a toilet and a sink only. The icon will indicate such room. And it’s for residential properties, so #2670 is not suitable as it is for public restrooms. In sum, what we need is an icon representing a room with a toilet and a sink (no shower/no bathtub) in houses/condos.
Examples...
![lavabo1](https://cloud.githubusercontent.com/assets/23098388/19768487/684c040a-9c36-11e6-8956-e9a092f4e558.jpg)
![lavabo2](https://cloud.githubusercontent.com/assets/23098388/19768490/684dee00-9c36-11e6-923d-6cf18fde4429.jpg)
![lavabo3](https://cloud.githubusercontent.com/assets/23098388/19768488/684c9d34-9c36-11e6-94b2-7d38f4d21234.jpg)
![lavabo4](https://cloud.githubusercontent.com/assets/23098388/19768489/684ced0c-9c36-11e6-8c83-b621b764dfaf.jpg)

**Comment by tagliala** [comment]
I'm leaving this open as `icon-toilet`, opposed to #2670 which is `toilet-sign`

**Comment by erikaursi** [comment]
Thanks! :)

**Comment by Crissov** [comment]
* [🚽 U+1F6BD Toilet](http://emojipedia.org/toilet/)

## Related Unicode characters (emojis)

* [🚿 U+1F6BF Shower](http://emojipedia.org/shower/)
* [🛁 U+1F6C1 Bathtub](http://emojipedia.org/bathtub/)
* [🛀 U+1F6C0 Bath](http://emojipedia.org/bath/)
* [🚾 U+1F6BE Water Closet (WC)](http://emojipedia.org/water-closet/) #2670
* [🚹 U+1F6B9 Mens Symbol](http://emojipedia.org/mens-symbol/) #2670
* [🚺 U+1F6BA Womens Symbol](http://emojipedia.org/womens-symbol/) #2670
* [🚻 U+1F6BB Restroom](http://emojipedia.org/restroom/) #2670 
* [🚼 U+1F6BC Baby Symbol](http://emojipedia.org/baby-symbol/)
* [♿ U+267F Wheelchair Symbol](http://emojipedia.org/wheelchair-symbol/)
* [🚰 U+1F6B0 Potable Water Symbol](http://emojipedia.org/potable-water-symbol/)
* [🚱 U+1F6B1 Non-Potable Water Symbol](http://emojipedia.org/non-potable-water-symbol/)

**Comment by You85** [comment]
+1

**Comment by FranciscoHanna** [comment]
+1

**Comment by MatthieuArzel** [comment]
+1
Now we have a scalpel icon in 5.2.
This one would be way more useful to me  👍

**Comment by MatthieuArzel** [comment]
Hey guys ? Still nothing here ?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=toilet
