### ISSUE TITLE
Icon request: fa-issuu

### ISSUE THREAD

**Issue by tercic** [FortAwesome/Font-Awesome#10123]
Quisiera que exista el ícono para issuu.com
Así como está Facebook, Twiter, etc. Issuu es una plataforma que muchos utilizados para la publicación de revistas.
![issuu](https://cloud.githubusercontent.com/assets/23087705/19748514/9e2f2800-9bb8-11e6-98ae-941068fbbbd7.png)
Lo utilizaría en mis web www.quehay.com.ar , www.guiavoy.com.ar y www.bluegrass.com.ar
Debería ser el logo de Issuu, el cual es muy simple.
GRACIAS!

**Comment by tagliala** [comment]
Duplicate of #1993, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
