### ISSUE TITLE
Builder for Custom Download of Icons in Use

### ISSUE THREAD

**Issue by bphilipnyc** [FortAwesome/Font-Awesome#10133]
Having used FontAwesome for over 2 years, I have to say that I love it.  The [Kickstarter](https://www.kickstarter.com/projects/232193852/font-awesome-5) campaign reflects the enormous contributions given to us over the years and I was happy to contribute.

One area that I feel could be improved is the generation of CSS for icons that are actually in use by our application.  For example:

1) The developer creates a list of icon names by grepping the application for "fa-"
2) The developer uploads the list, calls an API, or simply uses copy and paste on fontawesome.com
3) FontAwesome generates custom files containing only those icons needed for download

The thought is that this would decrease files sizes across millions of devices.  It's especially important for the upcoming Pro users who will now have over 1,000 additional icons.  There's the Icon Subsetter as the stretch goal, but this is a little different.

**Comment by tagliala** [comment]
Ref: #6398, #1322, #162

IIRC this a duplicate, but I'm unable to find the original request.

**Comment by bphilipnyc** [comment]
Thanks - closing in light of prior issues
