### ISSUE TITLE
Icon request: cc-sagepay

### ISSUE THREAD

**Issue by LiamMcArthur** [FortAwesome/Font-Awesome#10132]
I really like the cc card set that currently exists in FontAwesome. It would be awesome if we also had the availability of <strike>Maestro</strike> and SagePay.

I very quickly mocked these up as an idea of what I mean.

![_sagepay](https://cloud.githubusercontent.com/assets/7083125/19771493/fead68c0-9c5a-11e6-857c-b70353576678.png)

**Comment by tagliala** [comment]
Maestro is a duplicate of #4266, leaving this open as sagepay
