### ISSUE TITLE
Icon request: fa-victorops

### ISSUE THREAD

**Issue by zihaoyu** [FortAwesome/Font-Awesome#10134]
VictorOps is a popular incident management app, and brand in general. We plan to use it in Grafana which sends alerts to VictorOps. The icon will help identify the incident system.

VO already has a one-color icon here: ![VOIcon](https://victorops.com/wp-content/themes/vowp/images/victorops_color_ko.png)

**Comment by aethior** [comment]
VictorOps was adquired by Splunk.

>VictorOps is now Splunk On-Call — new name, updated product. With Splunk On-Call, developers, devops and operations teams make on-call suck less while reducing mean time to acknowledge and restore outages. ([more info](https://www.splunk.com/en_us/investor-relations/acquisitions/splunk-on-call.html))

cc/ @tagliala

**Comment by tagliala** [comment]
Let's use #16726
