### ISSUE TITLE
Icon request: fa-sisglass

### ISSUE THREAD

**Issue by NPC-Glasss** [FortAwesome/Font-Awesome#10136]
Hi!
I'm a designer who creates layouts for websites. Currently I am working on a site that sells glass, which uses the FontAwesome icons by default. 
I need a icon company logo.
I think this will be very useful for the community FontAwesome and I would be grateful, if available.
Here are the images for reference.

Thank you!

**Comment by tagliala** [comment]
Could you please provide a website for this brand?

**Comment by NPC-Glasss** [comment]
The old site _npc-steklo.ru
New website _steklo.info
