### ISSUE TITLE
Icon request: icon-paint-can

### ISSUE THREAD

**Issue by erikaursi** [FortAwesome/Font-Awesome#10131]
Hi!
I'm a designer who creates layouts for websites. I currently work for a website that sells real estate and vehicles that uses FontAwesome icons by default.
I'd like a paint can icon.
It'’d be very useful for FontAwesome as it can be used in several ways.
Here are some images for reference:
![icons_ink](https://cloud.githubusercontent.com/assets/23098388/19766003/35463974-9c2a-11e6-8e31-9d26020f6348.jpg)

**Comment by tagliala** [comment]
Duplicate of #3270, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
