### ISSUE TITLE
Icon request: icon-donut

### ISSUE THREAD

**Issue by bachoy** [FortAwesome/Font-Awesome#10148]
Hello!

I am looking for more food icons, specifically one with a donut shape, maybe with a bite taken out of it. Some examples:

![053_donut-512](https://cloud.githubusercontent.com/assets/10900367/19867386/a4d95862-9f71-11e6-80dd-4bfc6d024f8f.png) ![4119-200](https://cloud.githubusercontent.com/assets/10900367/19867385/a4d92b08-9f71-11e6-9d31-8f25ace3d4e2.png) ![thin-0919_donut_doughnut_cookie_desert_sweets-512](https://cloud.githubusercontent.com/assets/10900367/19867384/a4d9128a-9f71-11e6-8d5c-bd88c12027af.png)

Thank you!

**Comment by Crissov** [comment]
🍩 U+1F369 in Unicode #222

**Comment by adhoc-jan** [comment]
+1

**Comment by KristopherWagner** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a donut! https://fontawesome.com/v6.0/icons?q=donut&c=food-beverage
