### ISSUE TITLE
Icon request: fa-teamspeak

### ISSUE THREAD

**Issue by Nik99** [FortAwesome/Font-Awesome#10142]
It would be nice to see a Teamspeak 3 Icon (http://teamspeak.com/)

It's very very popoular and using a microphone icon it's kinda bad.

**Comment by tagliala** [comment]
Duplicate of #1474 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
