### ISSUE TITLE
Icon Request: fa-issuu

### ISSUE THREAD

**Issue by ITSecMedia** [FortAwesome/Font-Awesome#10144]
Dear Font-Awesome Team,

Please consider adding a simple brand icon for Issuu => ( https://issuu.com/ )
It would be a great addition to social icons for websites.

Best,
Norman

**Comment by tagliala** [comment]
Duplicate of #1993 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
