### ISSUE TITLE
Icon Request: fa-education-category

### ISSUE THREAD

**Issue by csuebws** [FortAwesome/Font-Awesome#10140]
Hello,

I was wondering if it would be possible to create a series of icons for the **_education_** category:

(I know _fa-university_ and _fa-graduation-cap_, exist and I believe those are the only one ones)

Here is a list of related icons I thought may come handy for any educational institution:

- Lecturer: fa-lecturer
- lynda.com: fa-lynda (A lot of universities, including ours use it for their employees for professional development)
- BlackBoard: fa-bb
- Studying: fa-study (see attached)
- Webinars: fa-webinar
- Exam/Test: fa-test (or fa-exam)
- Education: fa-education

Use case, would be used on University website, and web applications.

Thank you for your consideration are you guys are (no pun intended) Awesome! :)

![education](https://cloud.githubusercontent.com/assets/12142613/19833310/7f13527a-9df2-11e6-8381-60760f6efc1d.png)

**Comment by csuebws** [comment]
![091-512](https://cloud.githubusercontent.com/assets/12142613/19833338/169ce520-9df3-11e6-9a27-1503d61bfc7e.png)
![648ab86ed4c957868bf6c2a2a12c7de5](https://cloud.githubusercontent.com/assets/12142613/19833340/1a792438-9df3-11e6-8947-f4ec64b30df1.png)
![44224-200](https://cloud.githubusercontent.com/assets/12142613/19833341/1d4b9dd0-9df3-11e6-881b-8370fe8ced77.png)
![reader-512](https://cloud.githubusercontent.com/assets/12142613/19833343/207f529e-9df3-11e6-8d97-58bdeb405706.png)
![rulers-512](https://cloud.githubusercontent.com/assets/12142613/19833344/22753028-9df3-11e6-9f61-05fd14c071ef.png)
![webinaricon1](https://cloud.githubusercontent.com/assets/12142613/19833345/2475a66e-9df3-11e6-9f6e-1c26dd35dbdf.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
