### ISSUE TITLE
Icon request: van

### ISSUE THREAD

**Issue by olematon** [FortAwesome/Font-Awesome#10152]
I need icons for different vehicle types. Most of them do have their own icon, but vans don´t. Van icon should have a united driving compartment and cargo space - truck has a separate cargo space.
Thank you.

**Comment by tagliala** [comment]
Duplicate of #3260, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by olematon** [comment]
Ok thanks. I did search for word "van" but didn´t get any results.


1.11.2016, 15:09, Geremia Taglialatela kirjoitti:

**Comment by tagliala** [comment]
@olematon no problem, it happens sometimes
