### ISSUE TITLE
New Embed Code has been "publishing" for days

### ISSUE THREAD

**Issue by fatheaddesign** [FortAwesome/Font-Awesome#10155]
I've got a new embed code that's been "publishing" for days now, but never finishes so I can actually use it. Is there something I can do to get this to publish correctly, or just delete the code and start again? Browser refreshes, different browsers, restarting, nothing helps - as soon as i log back into my FA account, this code shows as "publishing" and is not accessible.

<img width="880" alt="screen shot 2016-11-01 at 11 33 43 am" src="https://cloud.githubusercontent.com/assets/93338/19897737/43234e0a-a027-11e6-8049-c3bbd4316e26.png">

**Comment by tagliala** [comment]
@robmadole could you please check?

**Comment by robmadole** [comment]
@fatheaddesign we are having some service interruption and I'm investigating it right now

**Comment by robmadole** [comment]
@fatheaddesign give it another try please. I think I have this sucker all fixed up.

**Comment by fatheaddesign** [comment]
Looks like that did the trick, thank you!

**Comment by knicpfost** [comment]
i'm having the same problem :/

also, every time i try to add my last name to my details, or really do much of anything, cdn.fontawesome.com eventually just returns a timeout. this has been happening for two days now.

**Comment by robmadole** [comment]
Sorry about this @knicpfost. Can you give it another try? I've restarted the app servers and load balancer. We've got a ghost in the machine somewhere that I'm having trouble tracking down. Let me know your results if you don't mind.

**Comment by knicpfost** [comment]
Well whatever you did worked! Publishing works quickly and I was able to
update name details and everything. No more timeouts or 404s. Thanks!

**Comment by Sara-n** [comment]
Same problem here. 
I tried to create the embed code and it's stuck on publishing since then (20 hours right now).

**Comment by robmadole** [comment]
@Sara-n I fixed this shortly after you commented on March 18th but forgot to reply to this ticket! My bad. If you are still having any issues let me know but I'm going to close this ticket now.

**Comment by Johnefsh** [comment]
Same here 2022 and still the bug the same!

**Comment by tagliala** [comment]
Hi, this is an old, beta service

Can you switch to the new Font Awesome Kits? https://fontawesome.com/start

**Comment by mwarren2** [comment]
Same here July 2023

**Comment by tagliala** [comment]
Hello, `cdn.fontawesome.com` is an old beta service

Please switch to kits: https://fontawesome.com/start

**Comment by mwarren2** [comment]
I'm a new user - I got an account today.
So I must have got there from somewhere on the site.

Anyway as soon as I sign in it goes right there to that page so I cannot do anything at all on the site.

**Comment by mwarren2** [comment]
I have just signed up today and the email contains a link to cdn.fontawesome.com

This link in the email:
<img width="533" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/10817233/68ce5e67-6f6a-4883-95ee-17a64d8c3ddf">

Takes you straight here:
<img width="848" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/10817233/3e287bca-41bf-4878-8550-bb911a154a77">

**Comment by tagliala** [comment]
> I have just signed up today

Where exactly?

**Comment by mwarren2** [comment]
The link took me to cdn.fontawesome.com  and I signed up there.

**Comment by mwarren2** [comment]
I would like to start again at https://fontawesome.com/start but it tells me my email is already taken

**Comment by tagliala** [comment]
Please try to login at https://fontawesome.com/sessions/sign-in?next=%2Fstart

If you don't have a password, try "forgot your password"

**Comment by mwarren2** [comment]
Thanks, that worked! You have gone beyond the call of duty, thank you again

**Comment by neron397** [comment]
Same problem here ( July 2023 )
