### ISSUE TITLE
Is icons.yml not updated?

### ISSUE THREAD

**Issue by mbaas2** [FortAwesome/Font-Awesome#10154]
I just detected this file and it seems to be a good resource to get the category-info and aliases of the icons. But I wonder if it is still maintained or perhaps has been abandoned (*for something better that I haven't yet discovered*)? 
The reason I'm doubting is because the file I was using ( [https://github.com/FortAwesome/Font-Awesome/blob/6b4fd47b620aec8978b8486a8eed7ab4039d4c80/src/icons.yml](https://github.com/FortAwesome/Font-Awesome/blob/6b4fd47b620aec8978b8486a8eed7ab4039d4c80/src/icons.yml) ) has the last entry for "created" as 3.2 and it has 360 entries whereas the official count is not at 675 (and the 4.7-Icons are missing indeed...)

**Comment by tagliala** [comment]
Hi, 

please check the `icons.yml` on the master branch at https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml

Hope it helps

**Comment by mbaas2** [comment]
Oh stupid me - I got that old version... 
That certainly helped - thanks! :-)
