### ISSUE TITLE
Fa fa-instagram error???¡¡¡

### ISSUE THREAD

**Issue by goia** [FortAwesome/Font-Awesome#10160]
The good co font awesome fa fa-instagram I have in the web http://tiendadeluca.es/index.php icon, sign me instagram icon and then shows me http://tiendadeluca.es/la-tienda a different being the same icon <i class = "fa fa fa-instagram-2x" aria-hidden = "true"> </ i> Any idea that can be

**Comment by tagliala** [comment]
Hi,

those pages are using a different version of FA.

`index.php` is using 4.5.0, `la-tienda` is using 4.7.0

The new instagram icon was introduced in 4.6.3.

Please take a look at your source code:

```html
<link rel='stylesheet' id='font-awesome-css'  href='http://tiendadeluca.es/wp-content/plugins/js_composer/assets/lib/bower/font-awesome/css/font-awesome.min.css?ver=4.12.1' type='text/css' media='all' />
<!-- ... -->
<link rel='stylesheet' property='stylesheet' id='rs-icon-set-fa-icon-css'  href='http://tiendadeluca.es/wp-content/plugins/revslider/public/assets/fonts/font-awesome/css/font-awesome.css' type='text/css' media='all' />	
```

Revslider plugin is loading an older version of FA, as per [Troubleshooting Guidelines](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up)

Hope it helps

**Comment by goia** [comment]
Thanks for all tagliala
