### ISSUE TITLE
Icon request: fa-caret-square-o-down - revision or new icon

### ISSUE THREAD

**Issue by MK1518** [FortAwesome/Font-Awesome#10167]
I'm using this icon to indicate a more actions menu inside a grid and I find the borders to be too thick. I am hoping it could be redesigned or a new icon created with thinner border for an elegant approach. See an example of the current icon and below an example of what I'm suggesting.

![icon_example1](https://cloud.githubusercontent.com/assets/20860448/20015797/3dd7bb20-a293-11e6-9a54-740f1777092c.png)

![icon_example2](https://cloud.githubusercontent.com/assets/20860448/20015802/43e0587e-a293-11e6-8a91-da888e9d6bde.png)

**Comment by sensibleworld** [comment]
We have a few options for this now: https://fontawesome.com/search?q=square-caret-down&o=r
