### ISSUE TITLE
.otf file missing fa-handshake-o

### ISSUE THREAD

**Issue by asp55** [FortAwesome/Font-Awesome#10171]

**Comment by tagliala** [comment]
Hi, please make sure you are using FA 4.7

![image](https://cloud.githubusercontent.com/assets/556268/20030933/7e7f6f38-a36f-11e6-83e6-7366cdc9c632.png)

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here
