### ISSUE TITLE
Icon Request: fa-anime, fa-manga

### ISSUE THREAD

**Issue by 0Bloom0** [FortAwesome/Font-Awesome#10173]
An Anime and Manga Icon! Would be vvveeerrrryyyy helpful for Anime Websites!

- Thanks for reading this. #fontawsomeISBEST

**Comment by tagliala** [comment]
Could you please provide examples?

Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment]
@tazMeah feel free to start a new request with a single example and a proper name

E.g: if you are requesting for Goku, please title the issue as `fa-goku` instead of `fa-anime`

**Comment by tagliala** [comment]
New icon request template: https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md

PS: no feedback, closing here

**Comment by Amermob** [comment]
is there any update on this?
looking to work for an anime website

**Comment by chanadmins** [comment]
Yeah, would love that too
