### ISSUE TITLE
Icon request: icon-telegram

### ISSUE THREAD

**Issue by gadfly1977** [FortAwesome/Font-Awesome#10172]
hi font-awesome team

you guys are doing great ,

just ask to see if there is any plan to have telegram icon in your awesome font ? 

i am using it via Instagram and you tube and other social community app as icon for contact us page and i missed this several time ( so every time i used image instead of icon )
thumbs up , great job

**Comment by tagliala** [comment]
telegram is already here: http://fontawesome.io/icon/telegram/

Please make sure you are using version 4.7.0

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here
