### ISSUE TITLE
Icon request: Feminism, Weed, Against, …

### ISSUE THREAD

**Issue by IconArchiv** [FortAwesome/Font-Awesome#10181]
Hi,

I'm a designer and working for a young party from Germany. They use the FontAwesome for their communication on the web. We would really appreciate if you could add the attached Icons to the font.
Thanks for your feedback.
![aigainst](https://cloud.githubusercontent.com/assets/23314573/20060954/f10c6f12-a4fd-11e6-8b3c-c5f87f58d986.png)
![feminism](https://cloud.githubusercontent.com/assets/23314573/20060956/f1312622-a4fd-11e6-9eda-5480acb2ad89.png)
![nothing to add 1](https://cloud.githubusercontent.com/assets/23314573/20060958/f135b944-a4fd-11e6-9c2c-2af939130e50.png)
![nothing to add 2](https://cloud.githubusercontent.com/assets/23314573/20060957/f134aa7c-a4fd-11e6-8e06-d9b9dca796c4.png)
![weed](https://cloud.githubusercontent.com/assets/23314573/20060959/f1362776-a4fd-11e6-9c31-9421f4001122.png)
![workers fist 1](https://cloud.githubusercontent.com/assets/23314573/20060960/f1385d8e-a4fd-11e6-8d0e-1a6adcebdf08.png)
![workers fist 2](https://cloud.githubusercontent.com/assets/23314573/20060955/f1255ce8-a4fd-11e6-9e98-48b59100281f.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
