### ISSUE TITLE
.ttf & .otf is not recognised

### ISSUE THREAD

**Issue by anfisign** [FortAwesome/Font-Awesome#10180]
I tried to search for this problem, but seems like I'm the only one who's experiencing next issue.
The font itself is not recognised. It connected to all types of glyph fonts. (I tried fonello and material icon fonts as well). 
What could prevent recognising those fonts?
<img width="1440" alt="2016-11-07 9 31 10" src="https://cloud.githubusercontent.com/assets/22645943/20043793/57f53afa-a4cd-11e6-93f0-77c8c22b2c7c.png">

Thank you a lt in advance

**Comment by tagliala** [comment]
Hi, 

apparently, this is normal for icon fonts, glyphicons do the same.

You can use the font without issues, using the cheatsheet http://fontawesome.io/cheatsheet/

Ref: #10068 

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#fonts-not-showing-up-in-apple-pages-for-mac
