### ISSUE TITLE
Icon request: male-o and female-o

### ISSUE THREAD

**Issue by boilerjt** [FortAwesome/Font-Awesome#10188]
Hello,

I am currently working on a project that uses a male and female icon.  An outline around the existing fa male and female icons would greatly help for color blind users.  I am requesting a black outline around the existing male and female icons with a white interior, similar to other fa icons with an outline.

Thanks,
John

**Comment by sensibleworld** [comment]
Hi there! There are outline version of both the male and female icons available in Font Awesome Pro.

https://fontawesome.com/icons/female?style=regular
https://fontawesome.com/icons/male?style=regular
