### ISSUE TITLE
New icons issue

### ISSUE THREAD

**Issue by dflorin** [FortAwesome/Font-Awesome#10187]
I downloaded the latest update, with the lastest added icons, I added it to my website but I still can't use the new icons, like: fa-user-circle, fa-user-user-circle-o, and many others.

I checked all loaded files by my website, in console, the new css file is correctly loaded, it has the new icon classes but when I use the class in any page, no icon is displayed.

I use laravel, i cleaned all caches, still nothing.

**Comment by tagliala** [comment]
could you please provide a link to your website?

**Comment by dflorin** [comment]
i work on localhost now, it's now live for the moment.

**Comment by tagliala** [comment]
Sorry, I can't help in that case

Please take another look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

I can just suppose that a plugin/extension you are using are loading an older version of FA

**Comment by dflorin** [comment]
I made it work, It seems i've missed a font file to update. Thanks!
