### ISSUE TITLE
Icon Request: fa-toilet-facilities

### ISSUE THREAD

**Issue by PlacesForPeopleWebTeam** [FortAwesome/Font-Awesome#10182]
It would be great to have an icon that showed if toilet facilities were available at our drop-in offices. My company has many offices and deals in the social sector. To many of our customers, this kind of availability info is very important.

Many thanks in advance.

**Comment by tagliala** [comment]
is this a duplicate of #2670 ?

**Comment by PlacesForPeopleWebTeam** [comment]
Yes it is. Thankyou. Does the icon already exist? Can't seem to find it.

**Comment by tagliala** [comment]
Nope, it is a request.

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
