### ISSUE TITLE
Problem with the icons in the font-awesome  

### ISSUE THREAD

**Issue by furabio** [FortAwesome/Font-Awesome#10197]
Why is this happening with the icons ?

![error](https://cloud.githubusercontent.com/assets/21022468/20196154/90b0d83a-a780-11e6-9e3f-32ce1465afb5.jpg)

**Comment by MuTLY** [comment]
Check that your page has the correct encoding. UTF-8 should be the default, IMHO.

Note you need to SAVE your file in UTF-8 enconding and also make sure that your `<meta>` encoding tag reflects that.

**Comment by tagliala** [comment]
Not enough details to debug this issue, if you think there is an issue with font awesome please provide an actual website or, much better, a reduced test case

Closing here
