### ISSUE TITLE
login and logout icon

### ISSUE THREAD

**Issue by myusufe** [FortAwesome/Font-Awesome#10208]
Please add login and logout icon

**Comment by tagliala** [comment]
Hi,

we already have `fa-sign-in` http://fontawesome.io/icon/sign-in/ and `fa-sign-out` http://fontawesome.io/icon/sign-out/

If you have something different in mind, please provide examples and a title following our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by myusufe** [comment]
Sorry, you are right.

Thanks,
