### ISSUE TITLE
Icon Request:支付宝 

### ISSUE THREAD

**Issue by ouyangnengjun** [FortAwesome/Font-Awesome#10206]
我找到了微信，QQ，就是没有找到支付宝。我想在我的网页提供用户快捷扫码支付功能，需要用到微信支付，支付宝支付，还有qQ,  可喜没有找到支付宝的

**Comment by tagliala** [comment]
Duplicate of #3854 / #4597, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by Gipors** [comment]
No alipay, such a shame!
