### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by praful-dhabekar** [FortAwesome/Font-Awesome#10213]
I created website using github and I used font awesome and when I open website in Google Chrome some icons doesn't show up. And when I open in Mozilla Firefox my website works properly, every icons shows up. Please Help me. I've to submit this to recruiter 
if you want see my code just go on to [https://github.com/praful-dhabekar/praful-dhabekar.github.io/blob/master/index.html](url)
My website : [https://praful-dhabekar.github.io/](url)

**Comment by tagliala** [comment]
Looks good to me

Please take a look at our [troubleshooting guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up) if you are experiencing issues

Please also consider to take advantage of cdn without hosting bootstrap and font awesome on your website
