### ISSUE TITLE
fa-user-circle-o not working

### ISSUE THREAD

**Issue by dontforgetmario** [FortAwesome/Font-Awesome#10219]
JFYI Is not working on Adobe Muse 2017 version (I don't think it is a Adobe Muse related issue anyway)

**Comment by tagliala** [comment]
Please make sure you are using 4.7.0

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

> You don't have an old version of Font Awesome installed on your system
