### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by oil4lessllc** [FortAwesome/Font-Awesome#10214]
plese tell me why this is missing

**Comment by tagliala** [comment]
Duplicate of #2499, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by oil4lessllc** [comment]
Please be advised that we searched for fa-bing and did not find it;
that is why we requested it.
  Thanks for the update; we will try it later.
