### ISSUE TITLE
Icon request: icon-catalog

### ISSUE THREAD

**Issue by steevegldev** [FortAwesome/Font-Awesome#10217]
Need opened book icon. Showing picture on pages would be great too.

Like this icons in the center: 
http://image.shutterstock.com/z/stock-vector-set-of-icons-for-book-list-and-information-in-flat-style-227859337.jpg
![image](https://cloud.githubusercontent.com/assets/6455947/20247998/e2f4ec56-a9a8-11e6-8151-44f60273a090.png)

**Comment by tagliala** [comment]
maybe a duplicate of #176 ?

**Comment by steevegldev** [comment]
It's would do the job basically, but with more details, it's not the same thing. 

I was thinking more like a magazine.

**Comment by tagliala** [comment]
duplicate of #2503 ?

**Comment by steevegldev** [comment]
Yep, my search didn't point this out. I'll close this one.
