### ISSUE TITLE
Icon Request: fa-pendrive (usb-dongle)

### ISSUE THREAD

**Issue by melanochaita** [FortAwesome/Font-Awesome#10216]
Basic pen drive, usually rotated at 45 degree to represent the use of a portable storage device.

**Comment by aethior** [comment]
Hi @melanochaita,

This icon was added in v5.11.0.
Check https://fontawesome.com/icons/usb-drive

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Also a duplicate of #7532
