### ISSUE TITLE
Icon request: icon-group

### ISSUE THREAD

**Issue by peeech** [FortAwesome/Font-Awesome#10221]
Hey, first of all thank you for an incredible set of icons we've been using in our project. I am really looking forward to the 5.0 version.

My request is for a fa-group icon. There is already: fa-users, fa-share and fa-share-alt, but none of them is reflecting an idea of a collaboration group (think of a shared folder in dropbox). Below are a few examples of what I am referring to:

<img width="80" alt="1" src="https://cloud.githubusercontent.com/assets/13788111/20268665/1c74ebb6-aa4e-11e6-949f-a6021fc6f39b.png">

<img width="100" alt="2" src="https://cloud.githubusercontent.com/assets/13788111/20268694/397049ea-aa4e-11e6-9c71-8927032740da.png">

<img width="36" alt="3" src="https://cloud.githubusercontent.com/assets/13788111/20268673/248307f2-aa4e-11e6-937b-4a73b0543175.png">

Please let me know if I can help somehow,

Thank you!
PJ

**Comment by tagliala** [comment]
Google drive uses 
![image](https://cloud.githubusercontent.com/assets/556268/20275694/dc340392-aa99-11e6-9259-a5ade008f9eb.png) this icon  to represents shared contents. It's requested at #2883 

I'm not convinced of the title, I would like something actually representing the icon you are requesting (group is too generic), as per our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by sensibleworld** [comment]
Here are a couple related icons:
- https://fontawesome.com/icons/user-friends?style=solid
- https://fontawesome.com/icons/users?style=solid
