### ISSUE TITLE
Icon Request: fa-number-format

### ISSUE THREAD

**Issue by phila213** [FortAwesome/Font-Awesome#10227]
To be used beside a number field as a button to format the number to 0.00 or 0,000.00.  Can also be used against numeric input fields to indicate numbers fields to indicate numbers only.

![number_format](https://cloud.githubusercontent.com/assets/23469044/20293537/7d5481c8-ab4b-11e6-9c8c-effdad4fc9fb.png)

**Comment by mbaas2** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by tagliala** [comment]
I'm going to consider this closed by https://fontawesome.com/icons/input-numeric?s=solid&f=classic

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) if the above icons does not fit this use case.

Please also clarify why the actual icon does not fit the use case, why a different design is needed, and provide an example
