### ISSUE TITLE
Icon Request: fa-web

### ISSUE THREAD

**Issue by omer-sds** [FortAwesome/Font-Awesome#10230]
**My Use Case** 
I will use it in admin/backend section, i have a menu link where i am showing icons before the labels and when creating a link for the front-end application labeled as "_**Front-end Application**_" i need one icon that could look like Web / Globe if possible, as i could not find any of the existing icons that could be used in place.

There are certain section where we need to show a list of external link , having a web icon along with a "_**visit here**_" text would also look nice.

**Comment by tagliala** [comment]
Globe: http://fontawesome.io/icon/globe/
External link: http://fontawesome.io/icon/external-link/

Request for a wireframe globe: #2655

Closing here

**Comment by omer-sds** [comment]
sorry how stupid of me that i could not find it ...
