### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by Natleen** [FortAwesome/Font-Awesome#10233]
Hey all,

i am new to build a homepage, however as a social worker and soon to be called as a therapist I want to be more into building a homepage and so I know now I need icons.
I use perth pro from aThemes

Now I have wishes :) that somehow I get icons for / with / ...

- a genogram ( family tree likewise) maybe you have some ideas
- two books on top of each other
- two little speak bubbles ( they have to look like two persons speak together)
- something which stays for action ( maybe some ideas?) with kids / pupils and grown ups
- a side shot from two chairs which fronts facing each other 
- a tree like an oak
- a forest

I would be glad if my wishes were fulfilled.

If you have questions email me. 

*Natalie

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Please provide individual requests, providing a proper title, a use case and an example

maybe genogram: http://fontawesome.io/icon/sitemap/
