### ISSUE TITLE
Icon Request: icon-profile

### ISSUE THREAD

**Issue by balangi** [FortAwesome/Font-Awesome#10239]
hi,
there is not any icon for discount and profile
![profile](https://cloud.githubusercontent.com/assets/14180653/20392248/3749907c-acec-11e6-891e-7bdbb017d76f.jpg)

![discount](https://cloud.githubusercontent.com/assets/14180653/20391809/34aaacf4-acea-11e6-9c6a-faf30df27747.jpg)

**Comment by tagliala** [comment]
User profile: http://fontawesome.io/icon/user/ http://fontawesome.io/icon/id-card/ http://fontawesome.io/icon/id-card-o/

Your example is similar to: http://fontawesome.io/icon/list-alt/, http://fontawesome.io/icon/list-ul/, http://fontawesome.io/icon/th-list/

**Comment by sensibleworld** [comment]
Here are a couple other options: https://fontawesome.com/icons/badge-percent?style=solid, https://fontawesome.com/icons/clipboard-list?style=solid, and https://fontawesome.com/icons/user-circle?style=solid
