### ISSUE TITLE
Icon request: icon-map

### ISSUE THREAD

**Issue by beneggett** [FortAwesome/Font-Awesome#1023]
For cases where icon-map-marker is not universally recognized as a symbol for map, I propose a new icon, icon-map.

![icon-map](https://f.cloud.github.com/assets/347537/489075/adc2869a-b98f-11e2-811d-6a3ecdc17b3d.png)

Here is an AI file for reference: https://dl.dropboxusercontent.com/u/7069732/icon-map.ai

**Comment by bgrayburn** [comment]
+1

**Comment by JulianKingman** [comment]
+1
I was wishing I had something a bit more treasure-map looking, kind of like this: https://cdn0.iconfinder.com/data/icons/travel-set-2/100/icon_Travel-05-512.png

**Comment by rosieks** [comment]
+1

**Comment by cvsguimaraes** [comment]
+1

**Comment by m0nzderr** [comment]
+1
yep, icon with a map of any kind would be very useful. Please!

**Comment by G-Driver** [comment]
+1

**Comment by jdandrea-nycgo** [comment]
+1

**Comment by scottrouse** [comment]
+1

**Comment by petterhj** [comment]
+1

**Comment by AlexErmer** [comment]
+1

**Comment by vlipman** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by G-Driver** [comment]
Seer also icon request for Open Street Map https://github.com/FortAwesome/Font-Awesome/issues/4317

**Comment by w3bninja** [comment]
A use case I recently ran into is:

I needed an icon to toggle between a list view and a map view and within the map view I needed to toggle pins on and off.

**Comment by JLundqvist** [comment]
+1

**Comment by Gzerox** [comment]
+1

**Comment by jamhall** [comment]
+1

**Comment by HalloTobi** [comment]
+1

**Comment by vlsoprun** [comment]
+1

**Comment by groupnet** [comment]
+1

**Comment by welligton1993** [comment]
+1

**Comment by madonion** [comment]
+1

**Comment by ParthasarathyRaja** [comment]
Can I use this for commercial purpose?

**Comment by tagliala** [comment]
@ParthasarathyRaja this icon or Font Awesome in general?

**Comment by wjgilmore** [comment]
+1

**Comment by beneggett** [comment]
@ParthasarathyRaja feel free

**Comment by davidpiesse** [comment]
+1

**Comment by ParthasarathyRaja** [comment]
This icon alone.

**Comment by SmugWimp** [comment]
+1

**Comment by NicoTexas** [comment]
+1 would be a great addition

**Comment by tagliala** [comment]
Added in 4.4.0

closing here

**Comment by djmj** [comment]
Where is the version with map+marker?

I find map+marker much more suitable for a specific address then just map or marker alone.

like: http://simpleicon.com/wp-content/uploads/map-4.png

**Comment by tagliala** [comment]
@djmj please open a new request

**Comment by dpfem** [comment]
+1

**Comment by tagliala** [comment]
@dpfem http://fontawesome.io/icon/map/, available in 4.4.0

locking here 🔒
