### ISSUE TITLE
Icon Request: fa-icon-car

### ISSUE THREAD

**Issue by PMistry123** [FortAwesome/Font-Awesome#10235]
![specials](https://cloud.githubusercontent.com/assets/23506151/20357907/cba1b42a-abf7-11e6-836e-ee1f885096ee.png)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/magic/ ?

**Comment by tagliala** [comment]
Please take a look at contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md
