### ISSUE TITLE
Feature Request: Provide SOURCE_URL value in API data accessible from the amp-ad tag

### ISSUE THREAD

**Issue by jlucero-contentad** [FortAwesome/Font-Awesome#10240]
Please provide the SOURCE_URL value in AMP API response available to amp-ad iframes. This value will make it easier to validate that the requesting page is the same as the publisher we currently have on file for our 3rd party ad serving service.

Best case scenario, the current page's query string parameters would be appended to the SOURCE_URL value to improve ad serving, but not required for basic validation.

**Comment by tagliala** [comment]
Sorry, I didn't get this request, I don't know what to do exactly

**Comment by jlucero-contentad** [comment]
Sorry about that. I clicked on the wrong tab. Please disregard this request.

**Comment by tagliala** [comment]
no problem
