### ISSUE TITLE
Icon request: fa-rectangle

### ISSUE THREAD

**Issue by iamandrewluca** [FortAwesome/Font-Awesome#10253]
Why `fa-square` and `fa-square-o` are not real squares?
First thought about requesting `fa-true-square` and `fa-true-square-o`  
But `fa-rectangle` and `fa-rectangle-o` would be better!
Thanks! :smiley:

**Comment by tagliala** [comment]
> Why fa-square and fa-square-o are not real squares?

you mean the border radius?

**Comment by iamandrewluca** [comment]
Yes, about border radius! :)

**Comment by g76r** [comment]
@iamandrewluca meanwhile you can use http://fontawesome.io/icon/stop/ since it's _almost_ square

**Comment by iamandrewluca** [comment]
@g76r Actually I needed an outline one to make acheckbox like, here I have `fa-check` and custom styled square

![avatar](http://i.imgur.com/TCWtx3L.png)

**Comment by g76r** [comment]
@iamandrewluca http://fontawesome.io/icon/check-square-o/ http://fontawesome.io/icon/check/  http://fontawesome.io/icon/square-o/ but yes, the corners are rounded
