### ISSUE TITLE
Icon request: fa-current-location

### ISSUE THREAD

**Issue by wencywww** [FortAwesome/Font-Awesome#10254]
Useful icon for many cases when current user locations should be retrieved. Used in Google Maps, for example

![image](https://cloud.githubusercontent.com/assets/4987356/20482203/0f515c52-aff4-11e6-9f5b-442bd3e2d07b.png)

**Comment by tagliala** [comment]
Duplicate of #10082 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by avdept** [comment]
@tagliala Sorry, but either link to issue is wrong, or you understood this request wrong.

**Comment by tagliala** [comment]
@avdept sorry and thanks for reporting this

The duplicate issue is #560
