### ISSUE TITLE
icon request: social site Branded.me

### ISSUE THREAD

**Issue by ire4444** [FortAwesome/Font-Awesome#10251]
Can you add the icon for the social site "[Branded.me](https://branded.me/)"?  Thanks in advance!

**Comment by ire4444** [comment]
Thanks for adding these tags. I hope this helps move up the resolution.  Thanks again!

Brian T.

**Comment by ire4444** [comment]
Just checking in here.  Anybody can build this one?  I appreciate the help.   :)

**Comment by ire4444** [comment]
Here is the logo for reference.
![branded me logo](https://cloud.githubusercontent.com/assets/23622437/20653762/e2611df2-b4d7-11e6-8f93-ede8e00fcc02.png)

**Comment by ire4444** [comment]
Anybody have any suggestions on who might be able to develop this?

**Comment by ire4444** [comment]
*bump*

**Comment by tagliala** [comment]
@ire4444 please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by ire4444** [comment]
Thanks @tagliala I'll see if I can get this to work.

**Comment by aethior** [comment]
>Branded.me was acquired in November 2016 by Outsource.com and was integrated into another business. We are proud to have served over 2 million members and look forward to delivering world class products in the future. ([source](https://www.branded.me/))

cc/ @tagliala

**Comment by ire4444** [comment]
Thanks for looking into this ticket – 5 years later.
