### ISSUE TITLE
Snapchat Icons Not Working

### ISSUE THREAD

**Issue by mc4rdle** [FortAwesome/Font-Awesome#10250]
None of the snapchat icons will work for me

**Comment by tagliala** [comment]
please make sure you are using Font Awesome >= 4.6

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by mc4rdle** [comment]
I have 4.7, where can I get an older version?

**Comment by tagliala** [comment]
4.7 is fine for snapchat

**Comment by russinating** [comment]
Same problem for me, just installed the latest 4.7 and just getting a crossed-through box in Photoshop

**Comment by tagliala** [comment]
please make sure you have installed the latest 4.7.0 version on your system

**Comment by tagliala** [comment]
Pages on macOS 10.12.1

![image](https://cloud.githubusercontent.com/assets/556268/20524774/5e499e3c-b0bc-11e6-98da-833cb627f7e5.png)
