### ISSUE TITLE
Icon Request: fa-desktop

### ISSUE THREAD

**Issue by m1rr0r1ng** [FortAwesome/Font-Awesome#10262]
• icon for desktop computer/non-mobile device

![ic-computer](https://cloud.githubusercontent.com/assets/15794399/20495708/d3f031bc-afe7-11e6-8275-11898ef73449.png)

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/desktop/ http://fontawesome.io/icon/television/
