### ISSUE TITLE
Icon request: fa-aboutme (brand icon)

### ISSUE THREAD

**Issue by ChiscoLeiton** [FortAwesome/Font-Awesome#10264]
Hi, thanks for all, you can create the "about me" icon?

https://about.me/

**Comment by tagliala** [comment]
Duplicate of #447 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by ChiscoLeiton** [comment]
Thanks...
