### ISSUE TITLE
Icon Request: Icon-aparat

### ISSUE THREAD

**Issue by ata24** [FortAwesome/Font-Awesome#10267]
Hello
[aparat.com](http://www.aparat.com) is the most famous video sharing platform in Iran. I was wondering if you could add its official icon to your library. 
Thank you.

**Comment by tagliala** [comment]
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
