### ISSUE TITLE
Icon Request: fa-musical.ly

### ISSUE THREAD

**Issue by Davidek577** [FortAwesome/Font-Awesome#10275]
Musical.ly, a video social network app icon :)
![musical ly_logotype](https://cloud.githubusercontent.com/assets/7951394/20609547/75af7d16-b28e-11e6-80d7-a811336ce5d3.jpg)

**Comment by WillJW** [comment]
+1

**Comment by Avery246813579** [comment]
+1

**Comment by p4rnicke** [comment]
+1

**Comment by aethior** [comment]
>ByteDance Ltd. acquired Musical.ly Inc. on November 10, 2017, and merged it into TikTok on August 2, 2018. At the same time, Musical.ly Inc. changed its name to TikTok Inc. ([more info](https://en.wikipedia.org/wiki/Musical.ly))

Regards.

cc/ @tagliala
