### ISSUE TITLE
Sport Icon

### ISSUE THREAD

**Issue by Bolli1957** [FortAwesome/Font-Awesome#10274]
Please could you create fonts that are sport related. Like this
Thank you
[http://www.thc-westerkappeln.de/IconsFreebie_Joomlarts.psd]

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by Bolli1957** [comment]
Excuse me, the picture has been inserted.
Hope it goes now.
