### ISSUE TITLE
Icon Request: fa-energy-bus, fa-can-open, fa-can

### ISSUE THREAD

**Issue by cawena** [FortAwesome/Font-Awesome#10272]
Requesting an icon for the bus systems, such as energyBus.

The icon is used to identify a bus system.
[EnergyBus](http://www.sycube.at/tl_files/upload/News/EnergyBus-logo-klein.gif):  Without the Text "EnergyBus"
[CANopen](https://de.wikipedia.org/wiki/CANopen#/media/File:Canopen_logo.svg)
[CAN](https://upload.wikimedia.org/wikipedia/de/e/ed/Cialogo_web.svg)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
