### ISSUE TITLE
Change icon-names - specifically, file-icons

### ISSUE THREAD

**Issue by langbakk** [FortAwesome/Font-Awesome#10271]
Currently, there is a bit of a naming inconsistency with the icon-files for documents / files. Since these might often be used in automatic processing, perhaps based on file-names, it would be simpler if they were named with the file-ending (extension), instead of what program/type they are. Let me exemplify:

The current name for the Excel file-icon is **file-excel-o** (for the white version).
A better name would perhaps be **file-xls-o**, with an alias **file-xlsx-o** - this way, it would be very simple to build up an automatic file-type assignment for listing directories and file-repositories. I do understand that not every icon would benefit from this, but for most of the specific icons in this part of the FontAwesome library, I think it would help. If only, add aliases for the already existing names, perhaps?

**Comment by tagliala** [comment]
Please consider using custom css to add those aliases.

**Comment by tagliala** [comment]
Hi, I'm shutting down some old requests

Since aliases have been removed in FA5, this does not apply anymore.

Closing here
