### ISSUE TITLE
Sport Icon

### ISSUE THREAD

**Issue by Bolli1957** [FortAwesome/Font-Awesome#10276]
Please could you create fonts that are sport related. Like this
Thank you
![iconsfreebie_joomlarts](https://cloud.githubusercontent.com/assets/23727088/20609612/35fcdb2c-b28f-11e6-98e3-77aae6e0f85b.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

@Bolli1957 there are several duplicates, and you should request individual icons
