### ISSUE TITLE
Icon Request: fa-sport

### ISSUE THREAD

**Issue by Bolli1957** [FortAwesome/Font-Awesome#10281]
Hello, can you create the following icons?
![selbstverteidigung](https://cloud.githubusercontent.com/assets/23727088/20636584/90b38c88-b36f-11e6-9bbe-8d7161bbfce8.jpg)
Selbstverteidigung
![zumba](https://cloud.githubusercontent.com/assets/23727088/20636596/c6a5e75a-b36f-11e6-859a-aaac4d3356f9.jpg)
Zumba
![gesundheitssport](https://cloud.githubusercontent.com/assets/23727088/20636618/44cde59c-b370-11e6-82a0-b77428e65aa2.jpg)
Gesundheitssport
![kinderturnen](https://cloud.githubusercontent.com/assets/23727088/20636624/8ca33732-b370-11e6-81ea-060b7eecef51.jpg)
Kinderturnen
![gymnastik](https://cloud.githubusercontent.com/assets/23727088/20636628/af69185e-b370-11e6-8933-44d8f1d656bf.jpg)
Gymnastik
![judo](https://cloud.githubusercontent.com/assets/23727088/20636648/06553616-b371-11e6-8e7c-73743220dbec.jpg)
Judo

Thank you

**Comment by tagliala** [comment]
@Bolli1957 please follow our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

You have to

1. search for existing issues before
If an icon is found (eg: judo #5661), add a 👍 reaction to that request

2. Open new individual requests with proper names
Eg: Title: `Icon Request: fa-zumba` and comment with an example

Hope it is clearer now

Closing here
