### ISSUE TITLE
Icon request : pending, draft

### ISSUE THREAD

**Issue by skygallery** [FortAwesome/Font-Awesome#10285]
I think Font Awesome needs to make a twice icon such as pending & draft. What do you think?

**Comment by tagliala** [comment]
could you please provide examples and fix the title?

[Contributing Guidelines - Requesting new icons](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by skygallery** [comment]
Please take a look the attachments for example

![draft](https://cloud.githubusercontent.com/assets/4106438/20659031/3ca11144-b56b-11e6-843d-a9126a425f7d.jpg)
![pending](https://cloud.githubusercontent.com/assets/4106438/20659032/3cca5a0e-b56b-11e6-94e2-b2e971828804.png)

**Comment by tagliala** [comment]
under construction: #5653 
notepad: #3449

all duplicates, closing here

**Comment by skygallery** [comment]
Great. Thank you
