### ISSUE TITLE
Blurry icon

### ISSUE THREAD

**Issue by dflorin** [FortAwesome/Font-Awesome#10286]
Hi! On my website I use a 13px font-size and some of the icons are a little blurry.
My font-family is: "open sans", sans-serif

I don't want to change the font-size of my entire website, because this will need too many modifications of many elements.
Is there a solution to get rid of this blurry effect?

For example, in the attached screen, the fa-home icon it's ok, but fa-bars not.
![untitled](https://cloud.githubusercontent.com/assets/15003839/20649914/ce5d6f04-b4d2-11e6-93f1-924fb3ccf56e.png)

**Comment by tagliala** [comment]
> I use a 13px font-size

Sorry, pixel perfection is based on font size. You should use 14px and multiples
