### ISSUE TITLE
Multiple icons Request

### ISSUE THREAD

**Issue by WHK102** [FortAwesome/Font-Awesome#10283]
1: Please add a translator icon like https://thumbs.dreamstime.com/z/translation-dictionary-icons-set-official-documents-legal-equivalence-online-english-black-collection-abstract-isolated-47195696.jpg from top to bottom, left to right the icon number 15.

2: And please, add a skull icon like: ` 💀 ( &#128128; )`

3: Please add a button icon in two states: normal and pressed, like this: https://thumb9.shutterstock.com/display_pic_with_logo/51559/193734752/stock-vector-white-arcade-button-with-player-one-two-three-and-four-icon-also-includes-on-off-button-state-193734752.jpg

4: Please add smiles :) like this: https://s-media-cache-ak0.pinimg.com/236x/0c/0d/08/0c0d0886a35956b9c3733f734679d88e.jpg

Thanks.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
