### ISSUE TITLE
Religion icons?? fa-islam fa-christian fa-jewish

### ISSUE THREAD

**Issue by saeed319** [FortAwesome/Font-Awesome#10290]
Can you please add Religion icons for the major religions?

fa-islam 
fa-christian 
fa-jewish
fa-hinduism
fa-athiest
fa-sikhism
etc

**Comment by tagliala** [comment]
We are discussing about religion icons here: #2088 .

Sorry but I can't leave this open, it doesn't meet our contributing guidelines https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
 * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
