### ISSUE TITLE
Icon request: fa-services

### ISSUE THREAD

**Issue by arexgill** [FortAwesome/Font-Awesome#10293]
Icon that describes a collection of services that can be provided. Right now we are using **fa-list** but it is too common.

**Comment by g76r** [comment]
hi, what about http://fontawesome.io/icon/cogs/ ?

**Comment by tagliala** [comment]
Please provide an example, as per [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by saqueib** [comment]
I also want something generic which represent service, here are some image I found which can help
![image](https://user-images.githubusercontent.com/6937224/31542618-5999de8c-b030-11e7-9a0e-880ce9bbbc37.png)
![image](https://user-images.githubusercontent.com/6937224/31542627-64510de6-b030-11e7-9826-a7c7b5fa45d6.png)

**Comment by vnextcoder** [comment]
pretty much needed.. I also need it for my Services site.

**Comment by tagliala** [comment]
I'm going to close this request because it doesn't meet our contributing guidelines. Also, I've asked for a feedback and I didn't got it.

There could be other requests to represent "services"

User with Headset: #5586 
Tools: #736

**Comment by MariaCrucin** [comment]
> hi, what about http://fontawesome.io/icon/cogs/ ?

Thanks

**Comment by lowpixel** [comment]
I think this will suit: https://fontawesome.com/v6/icons/hand-holding-heart
