### ISSUE TITLE
Some glyphs appear incorrectly

### ISSUE THREAD

**Issue by helix42** [FortAwesome/Font-Awesome#10301]
Hi there,

I've installed FontAwesome because I want to use icons in my i3bar on my personal desktop.

The problem is, that more than half of the glyphs are replaced by Korean letters, and they don't appear as icons.

If I copy and paste the cheatsheet into gedit, this is what happens:

![fa-notworking](https://cloud.githubusercontent.com/assets/7419656/20755417/366e0660-b70f-11e6-9a43-1fe5d881f9c3.png)

And this issue exists in the bar as well, even though I added the font to load itself, and even if I use the code and not just the copy-paste of the icon.

What could be done to solve this issue?

**Comment by tagliala** [comment]
Please post here: #10102

**Comment by helix42** [comment]
@tagliala that is not at all my problem.

The font can be rendered, but some glyphs are replaced.

For instance, if I want to use the 500px icon, it would show properly on the i3bar as well. But the Android icon would be replaced with the Korean character.

**Comment by tagliala** [comment]
@helix42 please post there your comment. Apparently there are some issue with this software but I cannot help, I hope that someone using it could investigate
