### ISSUE TITLE
bug: new fa-window-* icons unproportional big

### ISSUE THREAD

**Issue by tx4x** [FortAwesome/Font-Awesome#10306]
Hi,
there are new fa-window-* icons in town but unfortunately they look absolutely horrible and don't go well with the rest of the club: 

![image](https://cloud.githubusercontent.com/assets/1205100/20795365/17f06ff8-b7d1-11e6-8249-0c220960e03f.png)

I commented in the [original request](https://github.com/FortAwesome/Font-Awesome/issues/1582) already.

Is there some guidance to fix this myself ? 
thanks a lot.

**Comment by sajidali** [comment]
heavy thickness thick

**Comment by gbaumgart** [comment]
thanks for looking at this. i actually wanted to migrate the icons from glyph icons. here you can see that their icons do that right : http://jspanel.de/

**Comment by tagliala** [comment]
Fixed!

https://jsfiddle.net/tgzouajm/46/
