### ISSUE TITLE
Flip Horizontal + Passing Not work correctly

### ISSUE THREAD

**Issue by japita-se** [FortAwesome/Font-Awesome#10300]
This line
`<i class='fa fa-truck faa-passing faa-horizontal animated fa-4x'></i>`
doesn't behave as supposed to.

**Comment by tagliala** [comment]
what is faa-passing?

Please provide a fiddle showing the issue, you can start with this one:  https://jsfiddle.net/tagliala/s3msxtbe/

**Comment by tagliala** [comment]
No feedback, closing here
