### ISSUE TITLE
Icon request: fa-coin

### ISSUE THREAD

**Issue by Mar-k** [FortAwesome/Font-Awesome#10309]
See this issue 

https://github.com/FortAwesome/Font-Awesome/issues/1400

**Comment by tagliala** [comment]
@Mar-k https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by Mar-k** [comment]
@tagliala didn't read that sorry.

**Comment by tagliala** [comment]
@Mar-k no problem 👍
