### ISSUE TITLE
Icon Request: fa-radio

### ISSUE THREAD

**Issue by raRaRa** [FortAwesome/Font-Awesome#10317]
Image of radio tower or signal.

http://l7.alamy.com/zooms/fbb07a6582ec41c9a3e9da108d48cfe9/icons-radio-tower-frajye.jpg

Few use cases:
Remote control (icon of radio)
Broadcast message (icon of radio)
Tune in to our radio show (icon of radio)

**Comment by tagliala** [comment]
Duplicate of #2581, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
