### ISSUE TITLE
Use OTF instead of TTF to get smaller font files

### ISSUE THREAD

**Issue by RoelN** [FortAwesome/Font-Awesome#10319]
Currently Font Awesome offers an OTF file (presumably for "desktop use") and TTF-based webfonts (TTF, WOFF and WOFF2). TrueType fonts are generally larger than OpenType/CFF fonts, so why not use the OTF file? [More about difference between TT and OT/CFF](http://blog.typekit.com/2010/12/02/the-benefits-of-opentypecff-over-truetype/)

(Maybe related: a quick inspection of differences between the OTF and TTF is that the **OTF is outdated and misses icons**, is that possible?)

Edit: I have some more suggestions for [optimising Font Awesome's font files](https://pixelambacht.nl/2016/font-awesome-fixed/), so if you have any questions or need any help, ping me!

**Comment by tagliala** [comment]
From the author of IcoMoon: 

> I added OTF support (CFF outlines, to be more precise) to IcoMoon in early 2014. Later that year, we received complaints from Windows users that their glyphs no longer looked crisp on IE and Firefox (which used DirectWrite). It turned out that DirectWrite on Windows did not render CFF glyphs properly. I resisted to change anything at first, but then Chrome 37 switched to using DirectWrite. I had to disable CFF and revert back to TTF.

Source: http://disq.us/p/1ec9228

**Comment by RoelN** [comment]
We checked, but this only seems to apply to Windows 7, and for a specific build of that Icomoon set. There's no reason OTF (CFF) should look bad in Windows — thousands of OTF fonts are in use on Windows without any problems.

Depending on your tools and your build process, it's very well possible to generate a nice and clean OTF font.

**Comment by tagliala** [comment]
@RoelN sorry, just saw your tweet

I cannot confirm that the `.otf` is outdated

![image](https://cloud.githubusercontent.com/assets/556268/21118100/b6c88df6-c0bc-11e6-8572-427cf1683950.png)

Since .woff/.woff2/.svg/.ttf are generated via [Font Squirrel](https://www.fontsquirrel.com/tools/webfont-generator) at the moment (maybe things will change in FA 5.0), optimization of the other formats could be done in a separate project (eg: input .otf => output optimized .woff/.woff2/.otf/.ttf/.svg)

**Comment by RoelN** [comment]
@tagliala I didn't actually look at the icons, but saw the OTF wasn't updated in commit 1645c765d4b20c8e23b247f8a9ea5ba7da7b4627 and that it had 694 glyphs instead of the TTF's 707 (which is still more than the 675 icons claimed, by the way). Maybe some default glyphs (like `.notdef`) get added in the conversion process?

I'd be more than happy to discuss a pre/post-process setup to convert the source files to nice and clean font files!

**Comment by tagliala** [comment]
@talbs since FA7 will drop TTF and we provide an [OTF](https://github.com/FortAwesome/Font-Awesome/tree/6.x/otfs) for the Desktop, I would close this

Feel free to reopen
