### ISSUE TITLE
Icon Request: Drill 

### ISSUE THREAD

**Issue by tenznhok** [FortAwesome/Font-Awesome#10310]
![drill_icon](https://cloud.githubusercontent.com/assets/6728831/20848498/602b46ec-b8a0-11e6-852f-55efefe84bcd.png)

**Comment by tagliala** [comment]
Duplicate of #3139, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
