### ISSUE TITLE
Icon request: fa-sensor

### ISSUE THREAD

**Issue by dluc** [FortAwesome/Font-Awesome#10311]
Icon for a sensor device (e.g. IoT sensor). Something less generic than `fa-chip` and less specific than `fa-thermometer`, for instance a combination of `fa-rss` + `fa-line-chart`
![sensor](http://dev.ai/font-awesome/sensoricon.png)

**Comment by tagliala** [comment]
Duplicate of #7416, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
