### ISSUE TITLE
Icon Request: fa-php ; Icon Request: fa-javascript

### ISSUE THREAD

**Issue by lau29** [FortAwesome/Font-Awesome#10318]
Icon Request: fa-php
Icon Request: fa-javascript

I would use to be able to show the abilities that I have and that I use them for confection of sites.

I thank the attention.

**Comment by tagliala** [comment]
Duplicate of #1420 and #1711 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
