### ISSUE TITLE
Icon request: Need new icon fa fa-cart-arrow-up

### ISSUE THREAD

**Issue by peon501** [FortAwesome/Font-Awesome#10329]
Need icon for throwing out item of cart
something like 
fa fa-cart-arrow-down but to other side
fa fa-cart-arrow-up
or something  like
fa fa-cart-arrow-out
#10094

**Comment by tagliala** [comment]
Duplicate of #6941, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
