### ISSUE TITLE
Bangladesh Map Icon

### ISSUE THREAD

**Issue by MTelot** [FortAwesome/Font-Awesome#10323]
Hello, I'm using Font Awesome for quite a long time and loving it day by day. 👍 
Can you please add a Bangladesh map icon? Here's the png file that can help! 
![map-bangladesh](https://cloud.githubusercontent.com/assets/14920417/20931447/4a55a854-bbfb-11e6-856a-799003b23ac5.png)

**Comment by tagliala** [comment]
Sorry, maps are out of scope

Ref: #3992
