### ISSUE TITLE
Icon Request: fa-shopping-bag-o

### ISSUE THREAD

**Issue by amoola009** [FortAwesome/Font-Awesome#10321]
Hello 

I'm using font awesome in my online shopping site and i really liked it, it's amazing.

Now, i'm looking to change the whole site design and i think this icon 'fa-shopping-bag' is too old style, So i would like to suggest to add another trendy shopping bag (most of trendy online shopping site use it) Ex: [Asos](http://m.asos.com) and [Forever21](http://forever21.com).

Suggested Icon :
![image](https://cloud.githubusercontent.com/assets/24410866/20926360/fb9859b0-bbcc-11e6-81f6-8af578933dfc.png)

Thanks so much for your hard work.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/shopping-bag?style=regular
