### ISSUE TITLE
icon request : smartphone

### ISSUE THREAD

**Issue by fanle325** [FortAwesome/Font-Awesome#10335]
would you please release a set of smartphone-using icons such as call-in ,call-out, call-missed, call-failed, receiving msg, sending msg an so on which are just like what in your iPhones call history list items before the phone number. THANK YOU !

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by fanle325** [comment]
why?

**Comment by tagliala** [comment]
As per our contributing guidelines: 
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.

> * Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
Include a few use cases for your requested icon. How do you plan on using it?

> * Attach a single color image or two that represent the idea you're going for.

> * Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
