### ISSUE TITLE
fa-spin with fa-flip-horizontal on fa-history

### ISSUE THREAD

**Issue by MonteShaffer** [FortAwesome/Font-Awesome#10333]
It appears fa-flip-horizontal doesn't "take" with fa-spin...

**Comment by jtho** [comment]
Yes, I found this issue as well. spin works, but it ignores the fa-flip style

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is not a duplicate but it is related to #10336.

We probably need to clarify that you cannot apply multiple transformations to icons in the docs.

Let's use #10336 as a reference issue

Workaround: https://jsfiddle.net/tagliala/s3msxtbe/8/

Closing here
