### ISSUE TITLE
Icon Request: icon-aperture

### ISSUE THREAD

**Issue by Atomox** [FortAwesome/Font-Awesome#1033]
Hi guys,

I'd love to see more Photography-oriented icons. In this case, aperture, which would be used  when displaying exif data from an image. You commonly see this on Flickr, 500px, and other photography sites, when listing details of a photo. This could also double for fans of Portal (The Aperture Science logo is essentially a standard aperture icon).

See example:
http://3.bp.blogspot.com/_gGeQAkbhLG8/S96-a8ef7aI/AAAAAAAAAKw/qZkd7n_UXZU/s1600/aperture.png

**Comment by resonancedesign** [comment]
+1

**Comment by hhiru** [comment]
+1

**Comment by titenis** [comment]
+1

**Comment by metinsenturk** [comment]
+!

**Comment by Sirikon** [comment]
+1

**Comment by lucaskatayama** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by warandpeace** [comment]
+1

**Comment by quinen** [comment]
you can simulate one with this [code ](https://jsfiddle.net/uL6gexrs/):
```
// css
.text-white {color:white;}
// html
<span class="fa-stack fa-lg">
  <i class="fa fa-chrome fa-stack-2x"></i>
  <i class="fa fa-circle fa-stack-1x text-white"></i>
</span>
```

**Comment by nioc** [comment]
+1

**Comment by williwkl** [comment]
+1
![logo_aperture](https://cloud.githubusercontent.com/assets/25594099/22663395/b9db4076-ecac-11e6-8e3e-277c3f99b552.png)

**Comment by Schweinepriester** [comment]
+1

**Comment by amitbeck** [comment]
+1

**Comment by Pronink** [comment]
+1

**Comment by pinkeen** [comment]
Seconded

**Comment by sensibleworld** [comment]
It only took us 8 years. https://fontawesome.com/v6.0/icons/aperture?s=solid

<img width="989" alt="Screen Shot 2021-05-27 at 2 14 55 PM" src="https://user-images.githubusercontent.com/529604/119876462-ea2cc680-bef5-11eb-8b7f-dcc6f04c0984.png">

**Comment by hexandcube** [comment]
Why is this icon pro only? What happened to "Always free" for the basic set of icons? I'm not a company, I'm a hobbyist. I can't afford to pay $99 for icons for my personal website.

**Comment by sensibleworld** [comment]
@hexandcube The simple answer is that we'll always have and always support a free version of Font Awesome. As of this writing, Font Awesome Free includes over 2,000 icons. There's no grand plan of excluding icons from the Free set, only that we have to draw the line somewhere, and there will always be some tension there. (Version 6 already includes over twice the number of free icons than version 4 did.) We've written a bit more about that here: https://fontawesome.com/support#why-do-i-have-to-pay-for-font-awesome-icons-now.
