### ISSUE TITLE
Icon Request: icon-hair

### ISSUE THREAD

**Issue by modul3** [FortAwesome/Font-Awesome#10342]
Thanks!
![42055](https://cloud.githubusercontent.com/assets/15873580/21056809/db629776-be3f-11e6-8497-43904f45ba98.png)

**Comment by aethior** [comment]
Duplicate of #15344.

cc/ @tagliala

**Comment by tagliala** [comment]
https://fontawesome.com/icons/user-hair?s=solid

more at #15344
