### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by suraj1kc** [FortAwesome/Font-Awesome#10346]
I think there should be an icon name Inventory as in WordPress Woocommerce ==> Add Product page

**Comment by tagliala** [comment]
Could you please post here that example?

**Comment by tagliala** [comment]
No feedback, closing here.

Maybe one of these can cover this use case: https://fontawesome.com/icons?d=gallery&q=warehouse

**Comment by tagliala** [comment]
Actually, an inventory icon is present in FA Pro
