### ISSUE TITLE
Icon Request: fa-wallet

### ISSUE THREAD

**Issue by UXDesignerNL** [FortAwesome/Font-Awesome#10341]
I would like an wallet icon, something similar to this:
https://thenounproject.com/search/?q=wallet&i=587870

Btw, I ❤️  FontAwesome 😄

**Comment by Crissov** [comment]
Related Unicode emoji: 👛 [U+1F45B Purse](http://emojipedia.org/purse/) #222

**Comment by tagliala** [comment]
Duplicate of #2317, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
