### ISSUE TITLE
Copy to clipboard on icon pages.

### ISSUE THREAD

**Issue by GeorgeErickson** [FortAwesome/Font-Awesome#1034]
Possibly use https://github.com/jonrohan/ZeroClipboard.

**Comment by DA-Bryan** [comment]
Let's not give flash anymore ground to stay alive...
[https://clipboardjs.com/](https://clipboardjs.com/)

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-feedly was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by grokky1** [comment]
Also needed is ability to select and copy to clipboard. Right now the text is selectable but the icon is not. I often need to copy-paste into a word file or something like that when doing mockups, but I can't select the icons.

**Comment by PeterShaggyNoble** [comment]
@grokky1, use [the "cheatsheet"](http://fontawesome.io/cheatsheet/) instead.

**Comment by grokky1** [comment]
@PeterShaggyNoble That's a good idea. However it doesn't have the very useful search feature of the main icons page :(

**Comment by PeterShaggyNoble** [comment]
@grokky1 ... Ctrl+F!

**Comment by grokky1** [comment]
@PeterShaggyNoble It's not the same. That will search for a specific icon. The icons page I refer to filters all icons against multiple search terms.

Come to think of it, my original idea is the best solution. That icons page needs to allow selection. It's just a css tweak.

**Comment by sensibleworld** [comment]
Closing this issue, as you can copy the icon-name, unicode glyph, and HTML code from the icons preview pages (just hover over the info at the top).
