### ISSUE TITLE
Provide SVG icon to be used in SVG element as an alternative of Font Icon

### ISSUE THREAD

**Issue by SuperPat45** [FortAwesome/Font-Awesome#10352]
Hi,

I found two interesting blog posts:
https://cloudfour.com/thinks/seriously-dont-use-icon-fonts/
https://css-tricks.com/icon-fonts-vs-svg/

It may be wonderful if fontawesome has ability to provide SVG icons to be used in SVG element as an alternative of the classic Font Icon.
Example:
`<svg class="icon"><use xlink:href="path/to/icons.svg#search"/></svg>`

**Comment by tagliala** [comment]
Take a look at this repo: https://github.com/encharm/Font-Awesome-SVG-PNG

**Comment by SuperPat45** [comment]
> Take a look at this repo: https://github.com/encharm/Font-Awesome-SVG-PNG
This project is a good start but it seem to generate individual SVG files only... and I prefer my page does not download multiple files for icons.

**Comment by Crissov** [comment]
It’s quite trivial to convert `fonts/fontawesome-webfont.svg` to a proper (non-font) SVG file. SVG Fonts have been dropped from SVG 2.0 anyway.

**Comment by tagliala** [comment]
@SuperPat45 

there should be an .svg sprite on that repo: https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/sprites.svg

Unfortunately the repo is out of date, and I cannot submit a PR there at the moment

@dominykas @Rush could you please help us?

**Comment by Crissov** [comment]
Single-file SVGs are now available in [/sprites/](https://github.com/FortAwesome/Font-Awesome/tree/master/sprites), so this issue should be closed. @tagliala

**Comment by tagliala** [comment]
@Crissov thanks for the heads up
