### ISSUE TITLE
Icon request: icon-dress

### ISSUE THREAD

**Issue by lgmabugay37** [FortAwesome/Font-Awesome#10359]
I would like to request for dress icon package. 

I will be using it as subcategory for types of dresses. Basically the user can select a major dress category, followed by subcategories.

Ex of parent dress category:
icon-formal-attire
icon-casual-attire

Ex. of subcategory
icon-business-suit
icon-black-pants

Other requests that is related to dress.
icon-polo
icon-shorts
icon-tshirt
icon-sando
icon-underwear

Thank you so much for the great work. I am hoping to hear from the team soon.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by lgmabugay37** [comment]
Sorry, wasn't able to read this part.

"Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down)."

But thank you will submit new request based on the guideline. 

Thank you for quick response.

**Comment by tagliala** [comment]
@lgmabugay37 don't worry

I've also [searched for dress]`https://github.com/FortAwesome/Font-Awesome/search?q=dress&type=Issues&utf8=%E2%9C%93`, there could be duplicates
