### ISSUE TITLE
icon-request: icon-steam and icon-steam-sign

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1035]
A Steam icon would be useful for gaming websites (teams, communities, e-sports, ...). 
http://www.steampowered.com

**Comment by Woensdag** [comment]
+1

**Comment by paulocrash** [comment]
+1

**Comment by South-Paw** [comment]
Hi, @paulocrash

This issue is old and has already been closed. If you're not aware, both these icons have already been added to Font-Awesome

* http://fontawesome.io/icon/steam/
* http://fontawesome.io/icon/steam-square/
