### ISSUE TITLE
I need a half checked checkbox,thank you!

### ISSUE THREAD

**Issue by tiantian010110** [FortAwesome/Font-Awesome#10355]
I need a half checked checkbox,thank you!
waiting for your feedback.
![image](https://cloud.githubusercontent.com/assets/8926499/21126685/b7de99d0-c128-11e6-9e11-757a3bf93f9e.png)

**Comment by tagliala** [comment]
Duplicate of #6840, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment]
Nope, duplicate of #2055
