### ISSUE TITLE
Icon Request: fa-flags

### ISSUE THREAD

**Issue by BGamboa13** [FortAwesome/Font-Awesome#10367]
I would like to add country flags

**Comment by tagliala** [comment]
Sorry but flags are out of scope at the moment

Please consider an .svg based solution

Ref: #4735

**Comment by bengalamx** [comment]
@tagliala again, sorry to disagree, but if there's one flag (flag-usa) right now and is very unfair for the rest of the world. Pretty sure you can handle all countries flags, also it would be fun to make!
