### ISSUE TITLE
Icon request: icon-phpbb

### ISSUE THREAD

**Issue by rmcgirr83** [FortAwesome/Font-Awesome#10366]
I see there is an icon for wordpress.  How about one for phpBB?

**Comment by tagliala** [comment]
Duplicate of #1883, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by rmcgirr83** [comment]
Apparently it takes longer than 4 years to get icons included?  Not sure why people waste their time in making requests if they are never fulfilled.
