### ISSUE TITLE
Wrong unicode mappings on cheatsheet

### ISSUE THREAD

**Issue by krishnagupta21** [FortAwesome/Font-Awesome#10375]
Following mappings are wrong on http://fontawesome.io/cheatsheet/

fa-cogs -> should be f086 instead was f085
fa-key -> should be f085 instead was f084
fa-comments -> should be f087 instead was f086
fa-cameraRetro -> should be f084 instead was f083
fa-thumbs-up-open -> should be f088 instead was f087
fa-thumbs-down-open -> should be f089 instead was f088

**Comment by tagliala** [comment]
Sorry but I cannot confirm.

Why `cogs` should be f086? 

The unicode point in the .yml file is [f085](https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L1383)

It is also present [in the .css](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L571)

and it works via cut & paste in Apple Pages

![image](https://cloud.githubusercontent.com/assets/556268/21244104/483a764e-c31c-11e6-9621-d5745e7c8b3b.png)

**Comment by krishnagupta21** [comment]
Sorry I realized the issue is with https://icomoon.io/app/#/select/font, in here if you do this-
 select `key` icon from fontAwesome 4.7 library and try to use it-
```
.icon-key:before
    content "\f084"
```
It displays `cogs` instead of `key`. But changing it to `f085` fixes it.

**Comment by tagliala** [comment]
@krishnagupta21 don't worry, glad you solved 👍
