### ISSUE TITLE
wrong icon for version 4.7, details as below

### ISSUE THREAD

**Issue by bililovy** [FortAwesome/Font-Awesome#10371]
I found a bug in the version 4.7 , fa-plus displays the icon of  fa-close , fa-close displays the icon of fa-plus.

**Comment by tagliala** [comment]
Hi, could you be more specific?

Where does this happen?

http://fontawesome.io/icon/plus/
http://fontawesome.io/icon/times/

https://jsfiddle.net/tagliala/s3msxtbe/2/
