### ISSUE TITLE
Icon Request: fa-floor

### ISSUE THREAD

**Issue by vgjuvsland** [FortAwesome/Font-Awesome#10387]
An icon for a floor in a building

**Comment by tagliala** [comment]
please provide an example

**Comment by nut707** [comment]
![image](https://user-images.githubusercontent.com/3348847/35777790-afd6b94a-09ff-11e8-80f8-71bbc7610bb8.png)

**Comment by tagliala** [comment]
It looks like a translated version of `fa-th`: https://fontawesome.com/icons/th?style=solid
we also have a chess board: https://fontawesome.com/icons/chess-board?style=solid

**Comment by vgjuvsland** [comment]
I haven't found a good example yet, but i was thinking of an icon indicating a floor in a building. Maybe you could do it by combining some icons. Icon for building with left and right angles on each side.
