### ISSUE TITLE
Icon request: icon-embed

### ISSUE THREAD

**Issue by Rabia-Ahmed92** [FortAwesome/Font-Awesome#10381]

**Comment by Rabia-Ahmed92** [comment]
i want this icon for my video based application 
https://www.google.com/imgres?imgurl=http%3A%2F%2Fsimpleicon.com%2Fwp-content%2Fuploads%2Fembeb.png&imgrefurl=http%3A%2F%2Fsimpleicon.com%2Fembed.html&docid=cwIqOWjNC5Q7YM&tbnid=Ktnuhz2WQVG5mM%3A&vet=1&w=512&h=512&bih=765&biw=1600&q=embed%20icon&ved=0ahUKEwim0MrzhvjQAhUDtBQKHVBECQgQMwgqKAAwAA&iact=mrc&uact=8``

**Comment by tagliala** [comment]
Voilà: http://fontawesome.io/icon/code/
