### ISSUE TITLE
Icon request: icon-customercare

### ISSUE THREAD

**Issue by Rabia-Ahmed92** [FortAwesome/Font-Awesome#10380]

**Comment by Rabia-Ahmed92** [comment]
i want this icon for my video based application
https://thenounproject.com/term/customer-service/6704/

**Comment by tagliala** [comment]
Duplicate of #5586, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
