### ISSUE TITLE
Icon request: fa-hot-tub

### ISSUE THREAD

**Issue by limitstudios** [FortAwesome/Font-Awesome#10385]
Icon request for a hot tub

![icon_hottub](https://cloud.githubusercontent.com/assets/8024370/21258185/bedfba8c-c373-11e6-9566-9901d379f2d2.png)

**Comment by tagliala** [comment]
Does http://fontawesome.io/icon/bath/ fill your use case?

**Comment by limitstudios** [comment]
Nope our use case is a property search we've got most the icons covered but are currently using a non-fontawesome icon for filtering properties without hot tubs

**Comment by barabadam** [comment]
same for me as @limitstudios. hoping for more than a steaming cube, although that seems to be the standard. suggestion: avoid something that looks like a [user icon being boiled](https://developer.valvesoftware.com/wiki/File:Drownicon.png). cool for testing, but people don't need to be reminded that they're actually taking a chemical bath.
![image](https://cloud.githubusercontent.com/assets/10417265/25806748/40a279fa-33d2-11e7-90fe-46dc784a9406.png)

**Comment by tagliala** [comment]
This icon is available in FA 5.1 as `fa-hot-tub`

https://fontawesome.com/icons/hot-tub?style=solid
