### ISSUE TITLE
Icon request: fa-snooker-balls

### ISSUE THREAD

**Issue by millnut** [FortAwesome/Font-Awesome#10384]
Icon request for games

![icon_games](https://cloud.githubusercontent.com/assets/8024370/21258117/7ed52b84-c373-11e6-847e-a10fb8722b46.png)

**Comment by tagliala** [comment]
Maybe we need a better title for this one, I dont' see games. What does this icon exactly represent? a pile of balls?

**Comment by limitstudios** [comment]
Yeah basically pool/snooker balls we currently use it to reference games rooms for example

**Comment by Crissov** [comment]
Related Unicode emoji: [🎱 U+1F3B1 Billiards](http://emojipedia.org/billiards/)

**Comment by shoulders** [comment]
i would definitely think snooker if i saw this icon

**Comment by OptikWebCreative** [comment]
+1 for the icon being snooker - correct number of balls.  Pool and billiards have less 

Most varieties of Pool balls have either numbers in the middle of a solid ball, or a number in a stripe (would be great to have one of each to layer with a number)

Can't comment for Billiards as never actually played it

**Comment by zippy6** [comment]
or 2 snooker cues for any of the 3 sports

**Comment by Fatbat** [comment]
+1 for snooker/pool table games.
