### ISSUE TITLE
Icon Request : Icon-Medicine/Pharmacy

### ISSUE THREAD

**Issue by UmerFarooqOfficial** [FortAwesome/Font-Awesome#10399]
Hi,
I need icon of medicine for my **Hospital Management System** Project.

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by UmerFarooqOfficial** [comment]
![o_2514102887fb4cdb-0](https://cloud.githubusercontent.com/assets/14872186/21388739/6b8b12ac-c79f-11e6-9a56-37a292f2d7c0.png)

**Comment by UmerFarooqOfficial** [comment]
@tagliala It is not a Brand. I want to use it for my software. It is a New Icon Request.

**Comment by UmerFarooqOfficial** [comment]
![pill-512](https://cloud.githubusercontent.com/assets/14872186/21388831/f5d905b8-c79f-11e6-95f9-1cdf54607c24.png)

**Comment by tagliala** [comment]
let's use #15045, it has more +1s and a better title
