### ISSUE TITLE
Slack icon is displaed as a Note

### ISSUE THREAD

**Issue by notaduck** [FortAwesome/Font-Awesome#10394]
Hi. I'm having a hard time here with Font Awesome. I use it together with i3wm, but the Slack icon is displayed as a Note for some reason?

**Comment by tagliala** [comment]
Apparently, there are some issue with this i3

Please use this issue for reporting i3-related issues: #10102

Unfortunately I cannot help

**Comment by notaduck** [comment]
I will do that. Thanks
