### ISSUE TITLE
Please add to your front page instructions on how to browse all the icons in FA.

### ISSUE THREAD

**Issue by azav** [FortAwesome/Font-Awesome#10391]
I just cloned and installed the TTF and nowhere on the GitHub page for the project do I see any instructions for, "you've installed the font, here's how you can browse all the icons within the font."

Once people install the thing, they want to get going.  No one wants to hunt for instructions.  Please do not make them.  Supply "getting started" and "how to browse Font Awesome's icons" links in the main project page on GitHub.

**Comment by tagliala** [comment]
Taken from the homepage:

![image](https://cloud.githubusercontent.com/assets/556268/21286786/bcf973da-c45d-11e6-80be-fa24395f57f2.png)

http://fontawesome.io/cheatsheet/
