### ISSUE TITLE
Cheatsheet print problem

### ISSUE THREAD

**Issue by aromot** [FortAwesome/Font-Awesome#10395]
When trying to print in PDF the cheatsheet at the following address :

http://fontawesome.io/cheatsheet/

I only get the 3 first pages instead of the full list of icons (tested in Chrome 55 & Opera 42).

**Comment by tagliala** [comment]
I can confirm. I will try to fix this

**Comment by tagliala** [comment]
@armot I've prepared a fix at #10396. Meanwhile, I've attached there a proper PDF with all icons

**Comment by tagliala** [comment]
Thanks. The fix was committed to master, it will be live when the docs will be rebuild
