### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by emristan** [FortAwesome/Font-Awesome#10401]
[icomoon_6_icons.zip](https://github.com/FortAwesome/Font-Awesome/files/663785/icomoon_6_icons.zip)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
