### ISSUE TITLE
Icon Request: fa-cafeandbar

### ISSUE THREAD

**Issue by nlwt** [FortAwesome/Font-Awesome#10403]
This icon would show that you can find a cafe and bar area

**Comment by tagliala** [comment]
any example?

**Comment by nlwt** [comment]
An icon that shows that you will be able to find a café/bar at eg. The hotel.

Med venlig hilsen
ARP-HANSEN HOTEL GROUP

Nadia Tetens
Web-koordinator

Nybrovej 75
DK-2820 Gentofte

Tlf         +45 4597 0529
Mail       nat@arp-hansen.dk
Web      www.arp-hansen.dk
[cid:image001.jpg@01D25AD1.ABB694E0]<https://www.arp-hansen.dk/hoteltilbud/julekalender/>
Fra: Geremia Taglialatela [mailto:notifications@github.com]
Sendt: 20. december 2016 14:58
Til: FortAwesome/Font-Awesome
Cc: Nadia Tetens - Arp-Hansen Hotel Group; Author
Emne: Re: [FortAwesome/Font-Awesome] Icon Request: fa-cafeandbar (#10403)


any example?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
