### ISSUE TITLE
Icon Request: fa-common area

### ISSUE THREAD

**Issue by nlwt** [FortAwesome/Font-Awesome#10402]
This icon would have to symbolize that this is an area (eg. on a hotel) where you can hang out with the other people that stay at the hotel.

**Comment by tagliala** [comment]
any example?

**Comment by nlwt** [comment]
We are building a new hostel, and at the hostel there will be an area where you can hang out. An area where, everybody that stay at the hostel have the opportunity to read books,, charge their phone, study and so on. A common7public area, for everybody to chill ☺

Med venlig hilsen
ARP-HANSEN HOTEL GROUP

Nadia Tetens
Web-koordinator

Nybrovej 75
DK-2820 Gentofte

Tlf         +45 4597 0529
Mail       nat@arp-hansen.dk
Web      www.arp-hansen.dk
[cid:image001.jpg@01D25AD1.8C0AFA00]<https://www.arp-hansen.dk/hoteltilbud/julekalender/>
Fra: Geremia Taglialatela [mailto:notifications@github.com]
Sendt: 20. december 2016 14:54
Til: FortAwesome/Font-Awesome
Cc: Nadia Tetens - Arp-Hansen Hotel Group; Author
Emne: Re: [FortAwesome/Font-Awesome] Icon Request: fa-common area (#10402)


any example?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
