### ISSUE TITLE
Icon request: Computer maintenance

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10419]
![1420410486](https://cloud.githubusercontent.com/assets/24714037/21422958/af4194f8-c83a-11e6-9ac6-3edd2268edc9.png)

**Comment by tagliala** [comment]
Duplicate of #736 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
