### ISSUE TITLE
Sports icons not included

### ISSUE THREAD

**Issue by Buceador** [FortAwesome/Font-Awesome#10411]
Hello,

I was making a research of all issues requests for sports icons and I realize that there are several ones that asked for this, but there are no sports icons (only soccer balls - and yes, football is for american football and futbol is for soccer all around the world).

Some of this issues are from more than 2 years ago.

Are you going to include this sports icons or are you discarting this requests?

Please let me know if you need help.... I can help you with this... I think that this will bring a lot of sports website to FA.

Thank you in advance.

Regards,

Javier L'Episcopo

**Comment by tagliala** [comment]
They could land in FA 5.0.0
Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> Please let me know if you need help.... I can help you with this... I think that this will bring a lot of sports website to FA.

At the moment we are not accepting PR requests containing icons.

You can make a fork of font awesome or an extension with sport icons and share in every sports-related request on this tracker

Hope it helps

Please use #714

**Comment by Buceador** [comment]
Hi,


Thanks for your quick reply.


I was telling you that I can help you to collect the icons if you need human resources... not a PR request.


I read you case #714 and that is why I ask this.


I would like to wait for your FA 5.0.0 and see this new icons.


I was asking yu directly because my WP theme use your icons.


Regards,


Javier.


________________________________
