### ISSUE TITLE
Firefox problem with wide icons

### ISSUE THREAD

**Issue by PayteR** [FortAwesome/Font-Awesome#10413]
Hi, i have problem to manage this icon to work well in firefox

[isitalogo.zip](https://github.com/FortAwesome/Font-Awesome/files/667165/isitalogo.zip)

in selection screen is everything fine

![2016-12-21_2023](https://cloud.githubusercontent.com/assets/1248565/21403131/d0920ebe-c7bb-11e6-8573-6175c1c3e7a5.png)

but in download section is cutted off

![2016-12-21_2023_001](https://cloud.githubusercontent.com/assets/1248565/21403160/e7f02c08-c7bb-11e6-84ec-e6cc1b17a028.png)

i noticed this bug just in firefox, other browsers are fine

**Comment by tagliala** [comment]
Is this related to fontawesome cdn?

**Comment by PayteR** [comment]
no
