### ISSUE TITLE
fontawesome在ios上时有时无

### ISSUE THREAD

**Issue by dujiajiyi163** [FortAwesome/Font-Awesome#10415]
同为10.1的系统，有的iOS上从未丢失，有的就显示不出来，影响使用

**Comment by tagliala** [comment]
Could you please translate in English?

**Comment by vincent7128** [comment]
@dujiajiyi163 say some icon lose not show on the iOS 10.

**Comment by vincent7128** [comment]
I try font awesome 5 free icons only show the black square in to iOS 9, 10 system font, but font awesome 4 works fine.
