### ISSUE TITLE
Icon request: Warehouse

### ISSUE THREAD

**Issue by Minikibber** [FortAwesome/Font-Awesome#10418]
![warehouse_with_boxes-512](https://cloud.githubusercontent.com/assets/24714037/21422426/da1cbe62-c837-11e6-9c8b-1921bb3dc58f.png)

**Comment by tagliala** [comment]
Duplicate of #4560, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
