### ISSUE TITLE
Font Awesome Issue

### ISSUE THREAD

**Issue by abelvf** [FortAwesome/Font-Awesome#10429]
I'm trying to use:

```
<i class="fa fa-bath" aria-hidden="true"></i>
<i class="fa fa-shower" aria-hidden="true"></i>
```

And those are the only icons that does not work for me.

Appear in black, no errors, no nothing.

Any advice? Any suggestion?

Regards

Abel.

**Comment by tagliala** [comment]
Hi, you are probably using (maybe in an indirect unwanted way) an older version of font awesome. Please make sure you are on 4.7.0: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
