### ISSUE TITLE
Icon Request: fa-vtt

### ISSUE THREAD

**Issue by Georgespirit** [FortAwesome/Font-Awesome#10425]
Hello!  looking to have an icon for a vtt (atv, ssv, utv), could you help me out with this please?

[VTT.docx](https://github.com/FortAwesome/Font-Awesome/files/671049/VTT.docx)

thanks, have a great day! :)

**Comment by tagliala** [comment]
= mountain bike?

**Comment by Georgespirit** [comment]
an ATV or SSV, a four-wheeler

**Comment by lademone** [comment]
Good idea!

**Comment by sensibleworld** [comment]
Closing in favor of: https://github.com/FortAwesome/Font-Awesome/issues/19873
