### ISSUE TITLE
Why fa-lg is different from fa-2x, fa-3x etc.?

### ISSUE THREAD

**Issue by 40rn05lyv** [FortAwesome/Font-Awesome#10421]
Hi, I noticed that fa-lg is different from fa-2x etc classes:

```
.fa-lg {
  font-size: 1.33333333em;
  line-height: 0.75em;
  vertical-align: -15%;
}
.fa-2x {
  font-size: 2em;
}
.fa-3x {
  font-size: 3em;
}
````

Why do we need `line-height` and `vertical-align` for `fa-lg`, but don't need them in `fa-2x`?
Also, even visually `fa-lg` is different from others. You can see it in this example: http://www.w3schools.com/icons/fontawesome_icons_intro.asp

**Comment by tagliala** [comment]
Hi,

good point.

IIRC, the `fa-lg` was used to have larger icons in bootstrap buttons: https://jsfiddle.net/tagliala/hu6qksdb/1/

As you can see, it is supposed to vertical align the larger icon with the text
