### ISSUE TITLE
Icon Request: fa-shirt, fa-pants, fa-tie, fa-laundry-bag, fa-shoes

### ISSUE THREAD

**Issue by yonatancohen** [FortAwesome/Font-Awesome#10430]
Thank you!

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

e.g.: shirt: #715
