### ISSUE TITLE
Change request: swap `fa-transgender` and `fa-transgender-alt`

### ISSUE THREAD

**Issue by naeomees** [FortAwesome/Font-Awesome#10432]
I'd like to suggest switching round 'transgender' and 'transgender-alt', as the icon associated with 'transgender-alt' is the most commonly used version, not an alternative version - it can be a little misleading and confusing as it is currently.

**Comment by tagliala** [comment]
Hi,

there was a discussion about this in #5776 and #6664

This was my previous response: https://github.com/FortAwesome/Font-Awesome/issues/6664#issuecomment-109728531

I'm still seeing that both icons are accepted on wikipedia at https://en.wikipedia.org/wiki/Gender_symbol

> Anyway if you think that transgender must not be used for ⚥, please discuss this issue on wikipedia and then let me know if they fix their pages

**Comment by CydnieNaomi** [comment]
Correct, they are both accepted.  My point was the 'default', most widely used is what's been tagged as 'transgender-alt'.  I'm suggesting to change them round, since the one currently tagged as 'transgender' is the alternative, not the other way round.  A simple Google of 'transgender symbol' will show as much.

**Comment by tagliala** [comment]
@CydnieNaomi this change is a breaking change, and AFAIK Font Awesome 5.0.0 will keep backward compatibility.

The best thing I can do, is to assign @davegandy to this issue, so he will eventually take a look and decide what it is the best approach. Maybe the fix will be postponed to 6.0.0

**Comment by tagliala** [comment]
@sensibleworld is it possible to swap these icons for the upcoming FA6?

PS: please also take a look at the existing `transgender` icon, they look off-center in 6.x branch in the build system

**Comment by sensibleworld** [comment]
We've got this updated in version 6! https://fontawesome.com/v6.0/icons/transgender?s=solid
