### ISSUE TITLE
Icon Request: fa-envelope

### ISSUE THREAD

**Issue by bbuldrini** [FortAwesome/Font-Awesome#10435]
Hi,

it will be nice to have an icon of envelope.
thank you for your work !

Best regards,
Barbara

**Comment by ryankane** [comment]
There are already 5 envelope variants available.

* envelope-open-o
* envelope-open
* envelope-o
* envelope-square
* envelope

Do you mean something like this?

![letter](https://cloud.githubusercontent.com/assets/1094151/21499835/50ad5096-cc07-11e6-9681-c39dcf376865.png)

**Comment by tagliala** [comment]
@ryankane thanks

I'm closing here but if @bbuldrini has some different in mind I could consider reopening (with a different name)
