### ISSUE TITLE
Icon Request: icon-reading-glasses

### ISSUE THREAD

**Issue by unluckytoe** [FortAwesome/Font-Awesome#1043]
icon-reading-glasses

This would be a great icon. Front view of just the glasses.

**Comment by stepev** [comment]
:+1:

**Comment by stevenspiel** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by ellaestigoy** [comment]
+1

**Comment by erhhung** [comment]
+1
A version with one eye dark(er) would be nice for "view 3D anaglyph".

**Comment by madebygift** [comment]
+1 on this.

**Comment by 4bdulll4** [comment]
+1

**Comment by jcolvin1** [comment]
+1

**Comment by jononomo** [comment]
+1

**Comment by cthans** [comment]
+1

**Comment by dorothyjane** [comment]
+1

**Comment by bryananthonylewis** [comment]
+1

**Comment by tvirelli** [comment]
+1

**Comment by vimamica** [comment]
+1

Something like this:

![59c13bf4-3b6a-11e5-940d-48c8517b6478](https://cloud.githubusercontent.com/assets/13658140/9104655/840cc4fa-3c0f-11e5-9928-af69aa879334.png)
![59dc88a0-3b6a-11e5-985f-74eac6d01f7e](https://cloud.githubusercontent.com/assets/13658140/9104656/842bbd06-3c0f-11e5-9ee4-555cfbdc653d.jpg)
![a4e9d5aa-3b6a-11e5-91ea-62a8a26ae587](https://cloud.githubusercontent.com/assets/13658140/9104657/842cc5ac-3c0f-11e5-8786-5ecc1f45f4e5.png)

**Comment by TCattd** [comment]
+1, please.

**Comment by Chapullin** [comment]
+1

**Comment by okaufmann** [comment]
+1

**Comment by andersonkruger** [comment]
+1

**Comment by SamiTriki** [comment]
+1

**Comment by TareqMasri** [comment]
+1

**Comment by xtianus** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by hacksalot** [comment]
+1

**Comment by mike-stumpf** [comment]
+1

**Comment by irthos** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by mminute** [comment]
+1

**Comment by gjavi1** [comment]
:+1:

**Comment by peterfotinis** [comment]
+1

**Comment by kolbebe** [comment]
+ 1

**Comment by scasic** [comment]
+1

**Comment by mrvautin** [comment]
+1

**Comment by billstrahlend** [comment]
+1 for this version mentioned above:

https://cloud.githubusercontent.com/assets/13658140/9104657/842cc5ac-3c0f-11e5-8786-5ecc1f45f4e5.png

**Comment by hpvd** [comment]
+1

**Comment by dr4g0n** [comment]
+1

**Comment by Spark3000** [comment]
3 years and counting... 🙁

**Comment by KeizerDev** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-glass was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by cfaria** [comment]
+1

**Comment by jonathanstokes** [comment]
+1

**Comment by MichaelSamteladze** [comment]
+1

**Comment by ppdeassis** [comment]
+1

**Comment by Pantos** [comment]
+1

**Comment by SimonFricker** [comment]
How is this still not implemented?

**Comment by irthos** [comment]
Maybe without glasses they have trouble seeing this request :P

**Comment by mrzacarias** [comment]
+1

**Comment by tkh** [comment]
+1

**Comment by nelsondesign** [comment]
+1

**Comment by mykolat** [comment]
+1

**Comment by djoq** [comment]
+1

**Comment by janfreyberg** [comment]
+1

**Comment by kimehrenpohl** [comment]
+1

**Comment by npotier** [comment]
+1

**Comment by LesDrones** [comment]
+1, need this !

**Comment by pRob3** [comment]
1+

**Comment by gleamgraphics** [comment]
Definitely need this icon

**Comment by shaedrich** [comment]
+1

**Comment by shellfly** [comment]
+1

**Comment by LuisSanchez** [comment]
+1

**Comment by schowes** [comment]
+1 and +1 for binoculars as well.

**Comment by SimonFricker** [comment]
+1

**Comment by finbarr** [comment]
+1

**Comment by pingunaut** [comment]
+1

**Comment by jculverwell** [comment]
+ 1

**Comment by Jacobvdb** [comment]
+1
https://goo.gl/photos/K3R3sJM5KwTdMNAB9
![reading-glasses](https://cloud.githubusercontent.com/assets/2821547/24570360/6fce3e5c-1641-11e7-9f5b-31b2117de834.png)
 Use it on google docs reader add-on!

**Comment by focbenz** [comment]
+1

**Comment by gleamgraphics** [comment]
Awesome thank you

**Comment by smwbis** [comment]
+1
would love this for "display" vs "edit" (glasses and pencil)

this seems like a fairly basic and very useful icon. how did we get fa-hand-lizard-o before this...can't imagine that one is used very much

**Comment by trexanhvn** [comment]
+1

**Comment by Esty12** [comment]
+1

**Comment by agurz** [comment]
+1

**Comment by irthos** [comment]
+1 again since it's been a year+ since my last +1 :D

**Comment by eyot08** [comment]
We need this!! +1

**Comment by shababhsiddique** [comment]
Yep We do

**Comment by Spark3000** [comment]
Years go by. Still no reading glasses.

**Comment by transparentech** [comment]
👍 Something like the simple-line-icons' .icon-eyeglass would be awesome!

**Comment by daniel-g** [comment]
tons of new icons, still no glasses :( ... even emoji has glasses 👓

**Comment by Spark3000** [comment]
It's because the Font Awesome maintainers have a phobia of bad eyesight.

**Comment by sensibleworld** [comment]
We've just updated our prescriptions. This icon is in the design queue!

**Comment by daniel-g** [comment]
After years of waiting, I’m happy to see it coming :D , I will even make a cake to celebrate 🎉 

Enviado desde mi iPhone

**Comment by Spark3000** [comment]
LOL to the April Fools comment (now deleted)

**Comment by sagearslan** [comment]
@daniel-g If your cake does not look like this, I'm going to be disappointed.

![screen shot 2018-04-06 at 11 11 19 am](https://user-images.githubusercontent.com/2191083/38434393-620406f8-398b-11e8-8fcd-8ce40936d827.png)

**Comment by daniel-g** [comment]
@sagearslan it's going to be an Awesome cake

**Comment by faquino** [comment]
+1

**Comment by Vasimovic** [comment]
+1

**Comment by IgorceJovanoski** [comment]
+1

**Comment by sensibleworld** [comment]
Things just got a lot more clear: https://fontawesome.com/icons/glasses?style=solid

**Comment by daniel-g** [comment]
💥
