### ISSUE TITLE
bower.json is wrong

### ISSUE THREAD

**Issue by patrikx3** [FortAwesome/Font-Awesome#10449]
bower.json: the **main** directive is not usable. like grunt wiredep is not using the right injecting the files. bower main should use the css, bower only uses css and js!!! why we need less and scss???

**Comment by tagliala** [comment]
Because of bower specs, sorry

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#bowerjson-not-including-css-file-in-main
