### ISSUE TITLE
website - Page Get Started, support valid email

### ISSUE THREAD

**Issue by dhoko** [FortAwesome/Font-Awesome#10444]
Hi, 

You cannot use an email with a `+` :/  You get an error when you try to get the embed code

![screenshot at 2016-12-29 14-25-46](https://cloud.githubusercontent.com/assets/713283/21544822/c19f16dc-cdd2-11e6-89f1-c2d72c64e1f1.png)

Ex: `reobert+test@foo.bar`.

**Comment by tagliala** [comment]
Confirm.

@robmadole @talbs I don't know who is the right person to manage this, I've assigned @robmadole 

Could you please take a look?

**Comment by robmadole** [comment]
Yep, I'll grab this one.

**Comment by robmadole** [comment]
@dhoko we've got this fixed now :) can you give it a go?

**Comment by dhoko** [comment]
It works 👍 thx
