### ISSUE TITLE
Icon Request: Programming languages - fa-python, fa-csharp, fa-java, fa-javascript, fa-ruby (and a few others)

### ISSUE THREAD

**Issue by prahladyeri** [FortAwesome/Font-Awesome#10442]
I came across [this](https://github.com/FortAwesome/Font-Awesome/issues/10318) and [this](https://github.com/FortAwesome/Font-Awesome/issues/1420) while searching for a python icon in the fa library.  However, I now realize that a whole lot more icons are required for my web development, not just python :-).

Rather than opening separate requests for each language, consider this as a bundled request for the mentioned programming languages.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
