### ISSUE TITLE
'use.fontawesome.com' are pending a ICANN verification

### ISSUE THREAD

**Issue by MemorialVeraCruz** [FortAwesome/Font-Awesome#10454]
Hello, i'm from brazil and today when i tried to use your fonts i received an error, telling me that the domain use.fontawesome.com was returning a connection time out, so i go to the domain and the message here was that this domain have a ICANN verification pending.

**Comment by tagliala** [comment]
Let's use #10453

**Comment by probc** [comment]
Why is this issue marked closed when the problem is still happening?

**Comment by probc** [comment]
My aplogies, it is now working here in Canada for me.

**Comment by robmadole** [comment]
This is going to be a DNS propagation issue. So everyone's mileage may vary :)

**Comment by tagliala** [comment]
@probc it was closed just because it is a duplicate of #10453, as per https://github.com/FortAwesome/Font-Awesome/issues/10454#issuecomment-269969319
