### ISSUE TITLE
Icon request: git-logo

### ISSUE THREAD

**Issue by thomaskuntzz** [FortAwesome/Font-Awesome#10457]
Hi,
I think [the icons here](https://git-scm.com/downloads/logos) would be useful, especially the one without text. We already have [this one](http://fontawesome.io/icon/git/), so if we have the other (the one below) we can use both to create [this one](https://git-scm.com/images/logos/downloads/Git-Logo-2Color.png) and we would even have the ability to use two colors as on the image because it would be made of two icons.

What do you think of it? :smiley: 

https://git-scm.com/downloads/logos

![git logo](https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png)

**Comment by tagliala** [comment]
I'm pretty confident this is a duplicate but since I can't find the original post, I'm leaving this open

**Comment by tagliala** [comment]
This has been introduced in FA 5.8.2

https://fontawesome.com/icons/git-alt?style=brands
