### ISSUE TITLE
Your server down?

### ISSUE THREAD

**Issue by landrovernl** [FortAwesome/Font-Awesome#10458]
When I enter my email-address on this page http://fontawesome.io/get-started/ and click on "Send my Font Awesome embed code", it says your server is down. I've tried it on different computers and with different email-adresses.

**Comment by probc** [comment]
Somebody within Font Awesome must have dropped the ball and forgot to verify their domain properly, and now it was shut down by ICANN by the looks of it.  I would imagine some hands were slapped over this mishap!  Hopefully they can resolve it quickly though.

**Comment by probc** [comment]
After a few hours of outage for me, it has now started to work again.  All is good here in Canada.

**Comment by landrovernl** [comment]
That's good news. But I already had an embed code, and now it is'nt working anymore :-(

**Comment by RumbleFrog** [comment]
Still down for me :P

**Comment by Masa331** [comment]
for me in Czech Republic also :P

**Comment by SvenWesterlaken** [comment]
CDN will need to be updated around the globe (as it is cached on different places). So probably will take a while for other countries including mine.

**Comment by landrovernl** [comment]
It's OK here now (Netherlands) ;-)

**Comment by tagliala** [comment]
Thanks for reporting this. 

Please use #10453 to provide feedback
