### ISSUE TITLE
Icon request: icon-opensuse

### ISSUE THREAD

**Issue by souldanger** [FortAwesome/Font-Awesome#10468]
it would be fantastic if you add an icon for OpenSUSE as below.
Thanks

![opensuse-icon](https://cloud.githubusercontent.com/assets/10036776/21675227/51c9bccc-d331-11e6-8333-6a88d7957774.png)

**Comment by tagliala** [comment]
Is suse the same as opensuse?

**Comment by souldanger** [comment]
yes sir

**Comment by tagliala** [comment]
@souldanger thanks
