### ISSUE TITLE
fa-imdb

### ISSUE THREAD

**Issue by breitengrat** [FortAwesome/Font-Awesome#10462]
I'm sorry but the icon fa-imdb still does not work ;-( There is only an empty space. Can you solve it? Thank you

**Comment by tagliala** [comment]
Please make sure you are using the last version of fontawesome.

Take a look at our troubleshooting guidelines: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps
