### ISSUE TITLE
Icon Request: icon-miiverse

### ISSUE THREAD

**Issue by PaperYoshi** [FortAwesome/Font-Awesome#10460]
A Miiverse icon would be nice, it can be used like other social media icons.
![miiverse](https://cloud.githubusercontent.com/assets/24899636/21617937/d892ab3c-d1e8-11e6-9b7f-d56d8e19ff7d.png)

**Comment by aethior** [comment]
>On August 29, 2017, Nintendo of America announced that Miiverse would be permanently discontinued on November 7, 2017. Users could request to be sent a copy of all posts and screenshots they had made while using the service, however, replies to said posts would not be included. The service was shut down on November 7, 2017, at 10:00 pm PT, the same date that Wii U Chat was discontinued. ([more info](https://en.wikipedia.org/wiki/Miiverse#Shutdown))

cc/ @tagliala

**Comment by tagliala** [comment]
Oh, if this brand is related to Nintendo we can't implement it
