### ISSUE TITLE
Icon request: fa-iot (internet of things)

### ISSUE THREAD

**Issue by petrk94** [FortAwesome/Font-Awesome#10463]
Hello,

Im using a wordpress theme what need fa icon codes, and so I would like to use a IoT icon, but can not integrate it, because its not in FA, are there any plans to integrate it or how I can do it by my own?
I have seen it how to customize, but its works only if its the FA files.
Please help

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by petrk94** [comment]
Hello,
sorry to late you wait so long ;) 
I have thought about this icon for fa for IoT
https://thenounproject.com/term/internet-of-things/358752/

**Comment by petrk94** [comment]
@tagliala, how long it regularly takes until it will be inside?

**Comment by tagliala** [comment]
@petrk94 please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by hrcdigital** [comment]
Hi, 

I also like to see at least one iot icon.

Regards,
Raymond

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by hrcdigital** [comment]
Hello sensibleworld,

If you call Internet Of Things a niche, than everything is a niche.
iOT is a part of life and one of the biggest markets today.
So I strongly disagree with your personal view which is not based on facts.

Here you can see it yourself.
https://www.fortunebusinessinsights.com/industry-reports/internet-of-things-iot-market-100307

**Comment by sensibleworld** [comment]
Hi there! Thanks so much for the feedback. In terms of the wording of the above message, it was a boilerplate response... so please don't put too much weight on the word choice. (We're currently doing a long-overdue full review of ALL open icon requests.)

If this is an icon you'd still like to see, please open a new request (we have a new template that makes it easier to track things).
