### ISSUE TITLE
Icon request: OS: Debian, Ubuntu, OpenSUSE

### ISSUE THREAD

**Issue by souldanger** [FortAwesome/Font-Awesome#10466]
Please add icons for Linux OS
- Debian
- Ubuntu
- OpenSUSE

THANKS!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
