### ISSUE TITLE
new icons: icon-cross and/or icon-christianchurch

### ISSUE THREAD

**Issue by mjopepper** [FortAwesome/Font-Awesome#10461]
![cross-64](https://cloud.githubusercontent.com/assets/24903415/21625322/559d3afa-d1c8-11e6-941d-c17dce17553a.png)

![church_icon](https://cloud.githubusercontent.com/assets/24903415/21625360/8ab76936-d1c8-11e6-86dc-90c2190ee3ba.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1611 #2088 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by mjopepper** [comment]
----- Message from Geremia Taglialatela <notifications@github.com> ---------
    Date: Tue, 03 Jan 2017 15:23:14 -0800
