### ISSUE TITLE
Icon Request: fa-pokerchip

### ISSUE THREAD

**Issue by cozy2963** [FortAwesome/Font-Awesome#10477]
I searched for a poker chip or anything else related to playing poker like maybe playing cards and I didn't find anything. Would there be any way to get some related to this topic added?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1004, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
