### ISSUE TITLE
Icon Request: fa-groovemusic

### ISSUE THREAD

**Issue by rollo1002** [FortAwesome/Font-Awesome#10479]
It would be nice to have the Groove Music icon in font awesome. I have done a few sites for musicians and this icon would be a great addition.

**Comment by aethior** [comment]
>Groove Music (formerly Xbox Music or Zune Music Pass) is a discontinued audio player software application included with Windows 8, Windows 8.1 and Windows 10. (...) Groove Music has been replaced by Media Player in Windows 11. ([more info](https://en.wikipedia.org/wiki/Groove_Music))

cc/ @tagliala
