### ISSUE TITLE
CDN wrong Content-Type //use.fontawesome.com/.../fontawesome-webfont.woff2

### ISSUE THREAD

**Issue by dlmiles** [FortAwesome/Font-Awesome#10475]
https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.woff2

This does not return expected Content-Type header.  I see:

Accept-Ranges: bytes
Access-Control-Allow-Methods: GET
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3000
Cache-Control: max-age=31556926
Content-Length: 77160
**Content-Type: application/octet-stream**
Date: Thu, 05 Jan 2017 17:50:20 GMT
Etag: "af7ae505a9eed503f8b8e6982036873e"
Last-Modified: Tue, 25 Oct 2016 17:21:58 GMT
Server: NetDNA-cache/2.2
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method, Accept-Encoding
X-Cache: HIT
X-Firefox-Spdy: h2

Am expecting the current standard MIME type ?

**Content-Type: font/woff2**

**Comment by dlmiles** [comment]
FWIW the WOFF v1 URL also does not return expected Content-Type

https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.woff

**Comment by dlmiles** [comment]
Maybe check all expected files have correct Content-Type.

https//use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.eot

**Comment by tagliala** [comment]
@dlmiles thanks for reporting this, I can confirm.

AFAIK, "application/font-woff2" is the current standard MIME. Am I wrong?

Mime type is also wrong for .eot and .woff:

- [ ] `.eot` (expected: "[application/vnd.ms-fontobject](https://github.com/rack/rack/blob/2577f0bb09ff85fe6b07d290f708028aebf640ee/lib/rack/mime.rb#L180)", is: "application/octet-stream")
- [ ] `.woff2` (expected: "[application/font-woff2](https://github.com/rack/rack/blob/2577f0bb09ff85fe6b07d290f708028aebf640ee/lib/rack/mime.rb#L624)", is: "application/octet-stream")
- [ ] `.woff` (expected: "[application/font-woff](https://github.com/rack/rack/blob/2577f0bb09ff85fe6b07d290f708028aebf640ee/lib/rack/mime.rb#L623)", is: "application/octet-stream")
- [x] `.ttf` (expected: "[application/octet-stream](https://github.com/rack/rack/blob/2577f0bb09ff85fe6b07d290f708028aebf640ee/lib/rack/mime.rb#L580)", is: "application/octet-stream")
- [x] `.svg` (expected: "[image/svg+xml](https://github.com/rack/rack/blob/2577f0bb09ff85fe6b07d290f708028aebf640ee/lib/rack/mime.rb#L556)", is: "image/svg+xml")

```sh
>curl -k -I https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.eot
HTTP/1.1 200 OK
Content-Type: application/octet-stream

>curl -k -I https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.woff2
HTTP/1.1 200 OK
Content-Type: application/octet-stream

>curl -k -I https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.woff
HTTP/1.1 200 OK
Content-Type: application/octet-stream

>curl -k -I https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.ttf
HTTP/1.1 200 OK
Content-Type: application/octet-stream

>curl -k -I https://use.fontawesome.com/releases/v4.7.0/fonts/fontawesome-webfont.svg
HTTP/1.1 200 OK
Content-Type: image/svg+xml
```

**Comment by tagliala** [comment]
Hmm... there should be an issue for the `ttf` mime type in rack, too 😐 

I'm confused 😕 .

maxcdn uses `application/x-font-ttf` but it doesn't seem a registered iana mimetype.

The proper one should be: `application/font-sfnt`: https://www.iana.org/assignments/media-types/application/font-sfnt

**Comment by robmadole** [comment]
@dlmiles are you having issues related to this?

**Comment by tagliala** [comment]
@robmadole there could be different issues about mime types, we have also a wiki explaining that they should be properly configured. Personally, IIRC, I've experienced some `woff2` related issues when the format was just released

Ref: https://github.com/FortAwesome/Font-Awesome/issues/5559#issuecomment-74622760, #5372, [troubleshooting](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up)

**Comment by robmadole** [comment]
Alright. I'll work on this today and see if we can't get things fixed up. I can set the proper Content-Type and you guys can tell me if it's alleviating whatever issues you are having.

**Comment by tagliala** [comment]
@robmadole maxcdn uses `application/x-font-ttf` for `.ttf` format

```sh
>curl -k -I https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.ttf
HTTP/1.1 200 OK
Date: Fri, 13 Jan 2017 14:59:14 GMT
Content-Type: application/x-font-ttf
```

**Comment by robmadole** [comment]
This is still on my todo list. I didn't get to this last Friday so I'll try to attack it this week.

**Comment by Alex360hd** [comment]
Any update on this ? I'm using an online tool that give me a note on my website depending on the quality of the code, and it reports this a a problem that low the note...

**Comment by robmadole** [comment]
@dlmiles @Alex360hd this should be resolved now
