### ISSUE TITLE
Icon request: icon-discord

### ISSUE THREAD

**Issue by MickyPrice** [FortAwesome/Font-Awesome#10481]
Hey, I love font-awesome, It's awesome! I use it A LOT.
I was wondering if ya'll could add a discord icon, discord is a chat thing for gamers. It's like a better version or skype. 

Here's a picture of their logo https://discordapp.com/assets/07dca80a102d4149e9736d4b162cff6f.ico

I would be using this for contact pages and stuff like that!

Thanks for taking the time to read this, I really appreciate what you guys do there! Keep up the great work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
