### ISSUE TITLE
Icon Request: fa-Teeth

### ISSUE THREAD

**Issue by CharlestonPetResort** [FortAwesome/Font-Awesome#10485]
![dental_icons-04-512](https://cloud.githubusercontent.com/assets/24966728/21734310/c465ddd8-d430-11e6-957c-763c5d735ce6.png)

We would love to see teeth, or toothbrush to use for those clients who always get their teeth brushed!

**Comment by caduvieira** [comment]
Dupe of #1289?

**Comment by tagliala** [comment]
This looks like a shining tooth :\

**Comment by sensibleworld** [comment]
We now have a few tooth-related icons: https://fontawesome.com/icons?d=gallery&q=teeth
