### ISSUE TITLE
Icon request: magaphone

### ISSUE THREAD

**Issue by deleawo** [FortAwesome/Font-Awesome#10484]
I am planning on using the icon to symbolise speaking on our website. Will appreciate it if there is a wave in front of the magaphone symbolising sound
![th 2](https://cloud.githubusercontent.com/assets/24961192/21722638/776a0186-d425-11e6-97f9-5a267ce20b1b.jpg)

**Comment by tagliala** [comment]
@deleawo megaphone is already here! 🎆 

http://fontawesome.io/icon/bullhorn/
