### ISSUE TITLE
Icon Request: gab.ai social media icon

### ISSUE THREAD

**Issue by rexarcana** [FortAwesome/Font-Awesome#10482]
Would like to have gab.ai's frog icon added.

![gab.ai logo](https://gab.ai/logo.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10304, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
