### ISSUE TITLE
Icon Request: fa-cdbaby

### ISSUE THREAD

**Issue by rollo1002** [FortAwesome/Font-Awesome#10480]
Another music site and it would be nice to have an icon to represent this company.

Icon example: http://tinyurl.com/zhluz4r

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5424, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
