### ISSUE TITLE
Update Visa Logo per Brand Specifications

### ISSUE THREAD

**Issue by bepursuant** [FortAwesome/Font-Awesome#10492]
Simple update - Visa changed their brand specifications in 2016 and removed the 'flag' portion of the "V" in their logo. The flag distinction (line that goes through the V) in the Visa logo should be removed as they now use just a plain V as shown below.

![image](https://cloud.githubusercontent.com/assets/10257655/21746809/d0f53340-d517-11e6-9289-f1e1dbef45aa.png)

Thanks for the great project!

**Comment by tagliala** [comment]
thanks, added to 5.0.0 milestone

**Comment by tagliala** [comment]
https://fontawesome.com/icons/cc-visa?style=brands
