### ISSUE TITLE
Ballons icons

### ISSUE THREAD

**Issue by luisbatista000** [FortAwesome/Font-Awesome#10491]
I need some icons for my web.Is like a forum where posts receive scores from user.And i need some icons ballons for others plans in the same site.
![sin titulo](https://cloud.githubusercontent.com/assets/11902662/21746368/abf30684-d518-11e6-94c9-f5f850839fad.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? We already have a globe: http://fontawesome.io/icon/globe/ but I suppose you need another type of globe.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
Closing here because of #10494
