### ISSUE TITLE
Font Awesome and input buttons?

### ISSUE THREAD

**Issue by GiacomoLaw** [FortAwesome/Font-Awesome#10493]
Trying to add an icon to my input button, but it's not working.

https://github.com/GiacomoLaw/giacomolaw.github.io/blob/master/index.html

I have this: `<input class="fa-file-text-o" type="submit" value="My blog" />` as you can't add `<i>` tags to input buttons from what I have seen.

The stylesheet link in my header is `<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>`.

Any help?

Thanks in advance! 😄

**Comment by tagliala** [comment]
Hi, could you please provide a fiddle showing the issue? 

Maybe you are developing your files locally (`file:///` protocol) and the protocol-relative URL is causing issues.

Please consider using

```css
https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
```

**Comment by GiacomoLaw** [comment]
Managed to sort it out, error on my part.

Sorry about that!

**Comment by tagliala** [comment]
No problem, glad you solved 👍
