### ISSUE TITLE
I think you could add the Home icons category

### ISSUE THREAD

**Issue by mandoolabs** [FortAwesome/Font-Awesome#10506]
And add icons like 
- living room
- balcony
- terrace
- wardrove
- fridge
- lamp
- furniture
- armchair
- sofa
- window
- door
- microwave
- Hot water
- pool
- table
- chair
- desk
- ...

And move some icons to this category, like bath or shower

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
