### ISSUE TITLE
Icon Request: icon-beats1

### ISSUE THREAD

**Issue by adhesiv** [FortAwesome/Font-Awesome#10501]
Requesting icon for Beats 1 Radio.

This would be used to link out to radio shows/streams, playslits, added to footers, product pages etc.

**Comment by agerberi** [comment]
+1 for beats 1 radio icon

**Comment by aethior** [comment]
>Apple Music 1, previously branded as Beats 1, is a 24/7 music radio station owned and operated by Apple Inc. It is accessible through iTunes or the Apple Music app on a computer, smartphone or tablet, smart speaker (such as the Apple HomePod), and through the Apple Music web browser app. ([more info](https://en.wikipedia.org/wiki/Apple_Music_1))

cc/ @tagliala

**Comment by tagliala** [comment]
I'm confused by this. It does not look like a request for Apple Music as in #10500, and may be a request for "Apple Music 1"

I'm going to close this request. If anyone is interested in Apple Music 1, feel free to open a new request (and please clarify what is the brand to implement and the official website of the brand)
