### ISSUE TITLE
Icon Request: fa-park

### ISSUE THREAD

**Issue by ydelgado** [FortAwesome/Font-Awesome#10512]
Icon to be used as information in a hotel, to meake to know to clients that the hotel have parking as included service

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1559 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
