### ISSUE TITLE
Icon request: scatter-plot

### ISSUE THREAD

**Issue by deandevl** [FortAwesome/Font-Awesome#10517]
This would be a simple icon with an 'L' shaped x-y axis' and dots scattered and enclosed within the 'L'.  I create all types of bar, line charts including scatter plots for scientific applications and your icons have been helpful in differentiating the offerings.
Thanks for your work

**Comment by tagliala** [comment]
Duplicate of #4240?

**Comment by sensibleworld** [comment]
Playing some catch-up on older icon requests. We now have an icon that should fit this use case: https://fontawesome.com/icons/chart-scatter?style=solid
