### ISSUE TITLE
Icon Request: fa-beach

### ISSUE THREAD

**Issue by ydelgado** [FortAwesome/Font-Awesome#10510]
Icon to be used as information in a hotel, to meake to know to clients that the hotel have beach as included service.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is probably a duplicate of #3787, #1145 or #6936 please add a 👍  reaction to the proper one.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

If you have something different in mind, please leave a comment and I will consider reopening

Closing here
