### ISSUE TITLE
read and unread

### ISSUE THREAD

**Issue by rahmatullah** [FortAwesome/Font-Awesome#10520]
Hi,
Please design read and unread icons. When we read the message the is read when we did not read the message the sign is unread.

**Comment by ryankane** [comment]
They already exist.

![read-unread](https://cloud.githubusercontent.com/assets/1094151/21960615/42a67b8c-dabf-11e6-83b8-ef96fe0ff3dd.png)


* [`fa-envelope-o`](http://fontawesome.io/icon/envelope-o/)
* [`fa-envelope-open-o`](http://fontawesome.io/icon/envelope-open-o/)
* [`fa-envelope`](http://fontawesome.io/icon/envelope/)
* [`fa-envelope-open`](http://fontawesome.io/icon/envelope-open/)
