### ISSUE TITLE
Icon request icon 

### ISSUE THREAD

**Issue by irafairafa** [FortAwesome/Font-Awesome#10525]
Hi I like to ask to upload this icon

I put in the name for ech icon:
Icon request: icon-car  --->   Icon request icon-NAME

![icon request icon-barbell](https://cloud.githubusercontent.com/assets/25151596/21983731/7d6fe2b8-dbd1-11e6-80c5-f6506fb54bdb.png)
![icon request icon-capsules](https://cloud.githubusercontent.com/assets/25151596/21983732/7d7aa50e-dbd1-11e6-9231-d13d5beb9f96.png)
![icon request icon-centimeter](https://cloud.githubusercontent.com/assets/25151596/21983733/7d7a7692-dbd1-11e6-8906-ed40028319bd.png)
![icon request icon-climbing](https://cloud.githubusercontent.com/assets/25151596/21983734/7d7f7ca0-dbd1-11e6-989f-d7fbb87138ff.png)
![icon request icon-dumbbell](https://cloud.githubusercontent.com/assets/25151596/21983735/7d83cb98-dbd1-11e6-83d5-f3770811a8ca.png)
![icon request icon-dumbbell-white](https://cloud.githubusercontent.com/assets/25151596/21983736/7d877572-dbd1-11e6-9871-1f35c72dcd8a.png)
![icon request icon-floating_guru](https://cloud.githubusercontent.com/assets/25151596/21983737/7d95a070-dbd1-11e6-99f2-2fcbe4212c09.png)
![icon request icon-guru](https://cloud.githubusercontent.com/assets/25151596/21983738/7d9dcade-dbd1-11e6-99f4-03ca1903ed4a.png)
![icon request icon-jump](https://cloud.githubusercontent.com/assets/25151596/21983739/7da3fe04-dbd1-11e6-8fff-be6af7eb0ab4.png)
![icon request icon-medal](https://cloud.githubusercontent.com/assets/25151596/21983740/7da90674-dbd1-11e6-8273-f16c576a92ad.png)
![icon request icon-meditation_guru](https://cloud.githubusercontent.com/assets/25151596/21983741/7dca438e-dbd1-11e6-9fc0-65229db01d94.png)
![icon request icon-mountainbike](https://cloud.githubusercontent.com/assets/25151596/21983744/7dce4bbe-dbd1-11e6-967f-d819ca4217bc.png)
![icon request icon-regular_biking](https://cloud.githubusercontent.com/assets/25151596/21983743/7dcdbb4a-dbd1-11e6-9d46-3e80f6eb8ea6.png)
![icon request icon-run](https://cloud.githubusercontent.com/assets/25151596/21983745/7dceb11c-dbd1-11e6-8490-644760afaf29.png)
![icon request icon-runfast](https://cloud.githubusercontent.com/assets/25151596/21983742/7dcd9aac-dbd1-11e6-9e54-b4c6afb6babd.png)
![icon request icon-scale](https://cloud.githubusercontent.com/assets/25151596/21983746/7dd44ea6-dbd1-11e6-99b4-745bd6d5b90f.png)
![icon request icon-skiing](https://cloud.githubusercontent.com/assets/25151596/21983748/7deda216-dbd1-11e6-9230-5cfe8ae9902b.png)
![icon request icon-stepyoga](https://cloud.githubusercontent.com/assets/25151596/21983749/7df57720-dbd1-11e6-9e7d-d6aa812b5274.png)
![icon request icon-swimg](https://cloud.githubusercontent.com/assets/25151596/21983750/7dfaea3e-dbd1-11e6-9af8-3c1cf105b1d8.png)
![icon request icon-trekking](https://cloud.githubusercontent.com/assets/25151596/21983751/7e00e0c4-dbd1-11e6-9253-638b7ef6a7e6.png)
![icon request icon-trophy](https://cloud.githubusercontent.com/assets/25151596/21983753/7e01dbe6-dbd1-11e6-82be-9f92e359ad75.png)
![icon request icon-walk](https://cloud.githubusercontent.com/assets/25151596/21983752/7e015482-dbd1-11e6-8615-22e38b6084cf.png)
![icon request icon-weightlift](https://cloud.githubusercontent.com/assets/25151596/21983754/7e13cacc-dbd1-11e6-85e2-c6788cfccc05.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
