### ISSUE TITLE
Icon Request: fa-angies-list

### ISSUE THREAD

**Issue by tp546** [FortAwesome/Font-Awesome#10527]
Could you create an icon for Angie's List so I can use it to link to my company page there from my website?

Here is an example image:
http://durhamdds.com/wp-content/uploads/2013/06/Angies-List-App-Logo.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6716, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
