### ISSUE TITLE
Icon request: A simpler pencil

### ISSUE THREAD

**Issue by contentfree** [FortAwesome/Font-Awesome#10532]
The current pencil icon is a bit busy, especially at small sizes. Could we add an additional pencil (`pencil-2`?)

Something like: 
![image](https://cloud.githubusercontent.com/assets/10958/22046051/09bb5fc0-dcd3-11e6-9433-bba6d42b9262.png)

**Comment by schowes** [comment]
+1

**Comment by xXXIMMATTHEWXXx** [comment]
+1 I love the idea

**Comment by DUO-1080** [comment]
+1

**Comment by MrStevenHill** [comment]
I think this request has been resolved by the pen icon: https://fontawesome.com/icons/pen?style=regular

**Comment by sensibleworld** [comment]
As noted above, we now have a simpler version! https://fontawesome.com/icons/pen?style=regular
