### ISSUE TITLE
Icon request: icon-issuu

### ISSUE THREAD

**Issue by duikb00t** [FortAwesome/Font-Awesome#10539]
I plan to use it in footer bars of websites. Currently there are already icons like Twitter, Facebook, Linkedin,... Issuu would be nice as well.

http://rs1366.pbsrc.com/albums/r773/wearecorinneand/issuu_zpsb28882f8.png~c200

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1993 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
