### ISSUE TITLE
icon request: copyleft

### ISSUE THREAD

**Issue by mlibre** [FortAwesome/Font-Awesome#10548]
hi. you have copyright icon. this is copyleft.
https://en.wikipedia.org/wiki/Copyleft

**Comment by AntonRand** [comment]
Would flipping the Copyright horizontally give you what you want?

`<i class="fa fa-copyright fa-6 fa-flip-horizontal" aria-hidden="true"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2934, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by mlibre** [comment]
Ah. yes. sr.
