### ISSUE TITLE
ICON DO NOT SHOW UP 

### ISSUE THREAD

**Issue by Gyinka** [FortAwesome/Font-Awesome#10547]
The icons display on my local server but don't after I published it on my host. I'll appreciate a response real soon. Thanks in advance

**Comment by tagliala** [comment]
Please check our troubleshooting guide

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up
