### ISSUE TITLE
Design request: fontawesome.io/icons/  page

### ISSUE THREAD

**Issue by eldiyar7** [FortAwesome/Font-Awesome#10543]
Hi, the email input on the subscription section is always confusing. It would be better if you put there search input and move subscription section to bottom. I always end up typing my searches on email address input. Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10543, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
