### ISSUE TITLE
Icon request: flag-usa

### ISSUE THREAD

**Issue by nodesocket** [FortAwesome/Font-Awesome#10544]
Don't need every country, and I know it's being American biased, but having the US flag would be super useful for lots of cases.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1336, which is labeled as wontfix

Please note that the Font Awesome team could decide to implement the USA flag or other flags.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
