### ISSUE TITLE
Icon request: Icon-square-compass

### ISSUE THREAD

**Issue by ogre14t** [FortAwesome/Font-Awesome#10555]
I am working on a couple different masonic projects and it would be awesome to have a g-square-compass icon. something similar to: http://www.masonicexchange.com/assets/images/TME-EMB-D-01049.jpg

**Comment by tagliala** [comment]
Is this a duplicate of #6264?

**Comment by ogre14t** [comment]
No

**Comment by tagliala** [comment]
@ogre14t could upu please elaborate why?

The other issue says: "I'd like to suggest that we create an icon for the masonic symbol of the square and compasses.", this one has `Icon request: Icon-square-compass` title.

I would like to understand why they are different and the different use cases, so I can properly manage this request

Thanks

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by T3chnician** [comment]
It is the same @tagliala
