### ISSUE TITLE
Icon Request: fa-slash

### ISSUE THREAD

**Issue by trackor** [FortAwesome/Font-Awesome#10553]
Create a slash icon that can also be stacked on top of any other icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3691, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
