### ISSUE TITLE
Icon request: astronomy and space related icons

### ISSUE THREAD

**Issue by rodleiva** [FortAwesome/Font-Awesome#1055]
Would be great to have some astronomy and space-related icons in FontAwesome
examples:
a spiral galaxy
a ring planet
a comet
a telescope
a radio antenna
a dome

**Comment by jabarihunt** [comment]
I second these!

**Comment by tagliala** [comment]
sorry but I can't keep this open, if you are interested, please split this request in individual requests, having care of searching before
