### ISSUE TITLE
Icon request: fa-check-with-small-slash

### ISSUE THREAD

**Issue by gsvimieiro** [FortAwesome/Font-Awesome#10559]
Hi
Work in company which has an educational system.

We need two new icones : Question Correct (fa-correct) and question half Correct (fa-half-correct).

Follow an idea 
![half](https://cloud.githubusercontent.com/assets/25323854/22249783/7dfb99ba-e22b-11e6-8cf3-13b76a61b8e1.png)

![correct](https://cloud.githubusercontent.com/assets/25323854/22249796/93a1300e-e22b-11e6-9264-c1d9877df3b0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are those standard symbols?

**Comment by gsvimieiro** [comment]
Hi!

My company has a correction correction system and we use some icons that you do not have.
These icons are black with transparent background

Thanks

Giuliano

**Comment by mrtobar** [comment]
Hi!
Help me please I need icon alfresco please

Thanks
Milton
![logo](https://cloud.githubusercontent.com/assets/9864116/22254797/951187f2-e223-11e6-8434-0083e130b3cf.png)

**Comment by tagliala** [comment]
@mrtobar please take a look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons) and then to #6508

**Comment by mrtobar** [comment]
Hi!
![alfresco_logonegro](https://cloud.githubusercontent.com/assets/9864116/22255522/9c934400-e225-11e6-9592-7ee92ea784ef.png)
icon-alfresco

Alfresco is a company that helps us save documents in the cloud.
The logo is next and the name can be put icon-alfresco or another name no matter how important the logo

**Comment by mrtobar** [comment]
Sorry this is the icon 
![alfresco_logonegro](https://cloud.githubusercontent.com/assets/9864116/22256044/74c70f22-e227-11e6-976a-0e1681dd50df.png)

**Comment by tagliala** [comment]
@mrtobar please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

In other words: please add a 👍  reaction to #6508 if you want to request `alfresco`

I will delete off topic messages in this request in a short while

**Comment by mrtobar** [comment]
![alfresco_logonegro](https://cloud.githubusercontent.com/assets/9864116/22256812/f4405f68-e229-11e6-9cc1-1ed8df8695a5.png)

**Comment by gsvimieiro** [comment]
Found other icon that you do not have.
It is the indication icon (arrow).
Basically the teacher indicates that the issue has some problem.

These icons are black with transparent background

Thanks

Giuliano
![arrow](https://cloud.githubusercontent.com/assets/25323854/22292429/4e594af0-e2f2-11e6-816f-33d6f77e7762.png)

**Comment by tagliala** [comment]
Hi,

please do not request unrelated icons in a single request

If you need pointing arrows, you have a lot of options in this category: http://fontawesome.io/icons/#directional and also a [mouse-pointer](http://fontawesome.io/icon/mouse-pointer/)

Going back to the original request, I still didn't get if those are universal standard symbols for correct and non/correct questions. If they are standardizes, please provide me a link which explains those symbols.

**Comment by zoharshavit** [comment]
I think what gsvimieiro ment is that in adition to the fa-check and fa-times symbols he needs some kind of a hybrid of the two. like a check with a cross line to suggest that the answer is only half right. see https://www.onlinewebfonts.com/icon/185460 for a reference

**Comment by tagliala** [comment]
@zoharshavit thanks for the clarification

I will rename to `Icon request: fa-check-with-small-slash`

**Comment by zoharshavit** [comment]
Is there a due date for this?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
