### ISSUE TITLE
Icon Request: fa-Weight

### ISSUE THREAD

**Issue by chandnan** [FortAwesome/Font-Awesome#10557]
Hi, 
Can you please add icons related to healthcare domain? 

Weight, BMI, 
Icon for different specialties
Icon for - test, radiology, x-ray, labs etc 
Icon for - history, medication, allergies, procedures etc.

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
