### ISSUE TITLE
Icon Broken: fa-handshake-o

### ISSUE THREAD

**Issue by simonverzelen** [FortAwesome/Font-Awesome#10556]
Icon not visible when using this classname in latest version.

**Comment by vattenapa** [comment]
I'm facing the same issue. Did you find a fix @simonverzelen?

**Comment by simonverzelen** [comment]
I'm using the latest version of Font Awesome in the CMS platform 'SiteManager' and I still can't see it.
When I publish my website in SiteManager and I take a look on the live website, I suddenly see the icon.

My problem isn't fixed 100%..

**Comment by vattenapa** [comment]
I found a workaround by changing the `$fa-font-path` variable and using a CDN provided version of the FontAwesome font. Could there be some missing glyph in the node packaged font?

`$fa-font-path: "//netdna.bootstrapcdn.com/font-awesome/4.7.0/fonts";`

For reference I'm running font-awesome 4.7.0 downloaded from npmjs using npm version 4.1.1 and this glyph, specifically, doesn't work while others do.

This issue should probably be re-opened

**Comment by tagliala** [comment]
@vattenapa please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by vattenapa** [comment]
@tagliala D'oh. Had missed a gulp task to copy the assets! Thank you
