### ISSUE TITLE
Icon request: fa-chair

### ISSUE THREAD

**Issue by viewpoint** [FortAwesome/Font-Awesome#10567]
Can you add a sofa icon to represent a reception room for estate agent websites.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1998 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
