### ISSUE TITLE
Icon Request: fa-teamviewer

### ISSUE THREAD

**Issue by elfujiyama69** [FortAwesome/Font-Awesome#10566]
Just the brand icon of teamviewer. We have helpdesk and would like to offer a service which include the use of teamviewer and will be really nice to have the icon.

Thank u!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5383, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
