### ISSUE TITLE
Yelp Icon

### ISSUE THREAD

**Issue by drodda1** [FortAwesome/Font-Awesome#10572]
Can I please get a yelp icon or square.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yelp: http://fontawesome.io/icon/yelp/

Yelp square: #7843, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
