### ISSUE TITLE
Icon Request: fa-maths , Icon Request: fa-science

### ISSUE THREAD

**Issue by AsHeKEgYpT** [FortAwesome/Font-Awesome#10579]
Icon request: icon-maths , Icon request: icon-science

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
