### ISSUE TITLE
Issue with the thermometer icons in mobile browsers

### ISSUE THREAD

**Issue by SimplySynced** [FortAwesome/Font-Awesome#10571]
I just installed the most recent 4.7.0 font set on my site. I've uploaded all the font files and the css sheet.  I've added the fa-thermometer to a page and it works fine when viewing on a normal browser.  When I try to view the page on a mobile browser it does not show.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are too few details to understand this issue and I'm pretty confident that this is not related to Font Awesome.

If you think there is an issue with Font Awesome, please create a reduced test case. You can use this fiddle https://jsfiddle.net/tagliala/s3msxtbe/7

I think that you are (directly or indirectly) loading multiple versions of font awesome: your desktop browser loads the proper version, your mobile browser doesn't. Please check https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues

> Create an isolated and reproducible test case. Be sure the problem exists in Font Awesome's code with a [reduced test case](https://css-tricks.com/reduced-test-cases/) that should be included in each bug report.
