### ISSUE TITLE
Icon request: fa-ict

### ISSUE THREAD

**Issue by smita153** [FortAwesome/Font-Awesome#10576]
Requesting icon for information and communications technology as category listing icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by smita153** [comment]
Something like this.
![it_services](https://cloud.githubusercontent.com/assets/25382804/22366612/9c3f7db8-e4a3-11e6-8f63-49b527eb574c.png)

**Comment by tagliala** [comment]
What is the use case?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
