### ISSUE TITLE
fa-snapchat

### ISSUE THREAD

**Issue by andrei-acm** [FortAwesome/Font-Awesome#10577]
Hello. I have tried to implement that icon but is not working. I tried all 3 versions but the same result. With other icons it works. What could be the problem?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at our troubleshooting guide https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
