### ISSUE TITLE
Icon Request: fa-experience

### ISSUE THREAD

**Issue by sochychoeun** [FortAwesome/Font-Awesome#10574]
Dear team,

I would like to request new icon fa-experience to use for represent the experience of people.

Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

Quoting from [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by gopal1035** [comment]
I suggest _fa-black-tie_ or _fa-briefcase_ could serve the same purpose.

**Comment by Elizanel** [comment]
can you do something more gender neutral/ non binary. 

Thanks :)

**Comment by gopal1035** [comment]
Please do not promote androgny on your platform. 

I urge you to think how would a sex-neutral icon benefit, except for promoting weaker men, and non-feminine women?

Questions to ask:
1. Who are we trying to placate with this request? 

2. What tangible benefit will any demographic receive if this request were to go through? 

Kindly see 

https://therationalmale.com/2014/08/24/back-to-basics/

and

https://therationalmale.com/2015/10/30/complementarity/

for details and rationale.

**Comment by Elizanel** [comment]
Respectfully,

I do not mean to threaten your masculinity by suggesting the fact that
women are actually part of the workforce. I would advise you to plan for
the changing work dynamic that accompanies the growing rate that women are
achieving college degrees at a higher rate than men at every level
including PhDs. Now, unfortunately people such as yourself may feel
emasculated by the notion that women and men could work together in an
egalitarian even when you base your opinions on pseudo science. Please
understand that including icons that are either gender neutral and/or
equally gender specific can only help society by confronting gender
inequality in the workplace, which actually creates an economic
disadvantage to our economy and society.

Best regards,

Elizanel Martinez.

**Comment by gopal1035** [comment]
Thank you for the feedback. 

I agree that women indeed are becoming part of (physically non-dangerous) jobs.

Still, there seems no need to downplay the role of men by requesting a neutral design of the icon.

That said, this being a technical forum, I conclude my discussion on the topic.

**Comment by rulatir** [comment]
@Elizanel, when the first thing you have to say is the sneery "I do not mean to threaten your masculinity" then at least have the decency not to lead with "Respecfully" because there is nothing respectful about that.

Yes, more women than men graduate. If you were truly about equality, you would see this as a problem and not something to gloat about.

**Comment by tagliala** [comment]
Hi,

I'm going to close and lock this discussion.

If you are interested in an icon representing "experience", please open a new request following our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

PS: we prefer gender-neutral/language-neutral/culture-independent icons
