### ISSUE TITLE
Icon Request: icon-rewind-circle / icon-fast-forward-circle

### ISSUE THREAD

**Issue by kshahkshah** [FortAwesome/Font-Awesome#10573]
A few streaming services have icons which are a circle with an arrow pointing anti-clockwise for rewind with "10" for example, indicating the number of seconds the content being played will be rewound if pressed. The same for fast forward with the arrow of course then pointing clock wise.

See attached.

![10sec_backward-512](https://cloud.githubusercontent.com/assets/14322/22308539/68689f4a-e315-11e6-9fce-e76a64d17778.png)

**Comment by whistlerbrk** [comment]
The attached was just an example, I don't think the dashing is necessary, also I think the arrow should be centered at -45 degrees and 45 degrees from top dead center, respectively for rewind and fast forward as it helps further to indicate going backwards/forwards.

**Comment by fdambrosio** [comment]
I agree with this request

**Comment by sensibleworld** [comment]
Closing in favor of a similar request: https://github.com/FortAwesome/Font-Awesome/issues/16232
