### ISSUE TITLE
Icon Request: fa-duolingo

### ISSUE THREAD

**Issue by matmcal** [FortAwesome/Font-Awesome#10589]
Duolingo has 120 million users worldwide and is growing annually. Its Alexa ranking is 884.  I believe it is popular enough to deserve an icon from the best icon set on the internet.

http://duolingo.com

**Comment by matmcal** [comment]
Upon further investigation, this issue has already been opened by the community.

**Comment by aureliojargas** [comment]
Link to the original request: https://github.com/FortAwesome/Font-Awesome/issues/1906
