### ISSUE TITLE
a icon fa authorization (under user can see accepted,blocked,rejected,....)

### ISSUE THREAD

**Issue by publicocean0** [FortAwesome/Font-Awesome#10583]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example and set a proper title?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by publicocean0** [comment]
in my case (but there are many similar cases) you have a list of users in a table
for every user you have a status (related to authorization for a specific rule)
in the header of this list , in the column related to the status ... we can put a icon giving a idea about authorization status or permissions

**Comment by tagliala** [comment]
> A idea about a list under and a hand checking a single element could give a idea more properly

Could you please look for a single color, suitable for 16px icon size example on google images of what are you thinking about?

**Comment by publicocean0** [comment]
uhmmm 
maybe
https://cdn4.iconfinder.com/data/icons/REALVISTA/mail_icons/png/400/confirmation.png
or
https://thenounproject.com/term/invitation/697688/

**Comment by tagliala** [comment]
It's similar to http://fontawesome.io/icon/calendar-check-o/

I'm wondering if something simpler, like:

- http://fontawesome.io/icon/check-circle-o/
- http://fontawesome.io/icon/check/
- http://fontawesome.io/icon/check-circle/
- http://fontawesome.io/icon/check-square-o/
- http://fontawesome.io/icon/check-square/

fit your needs.

If it doesn't, is there any icon in Font Awesome which, combined with fa-check, will fit your needs?

**Comment by publicocean0** [comment]
i put it, but for me it can create a little confusion with a checkbox. It is too much similar , so probably it is better used when you need to create a custom checkbox. 

For my opinion adding a hand over showing the attempt to check is give better the idea that the concept is not a checkbox but is the action to make it.

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/user-check?s=solid
https://fontawesome.com/icons/user-xmark?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
