### ISSUE TITLE
icon request: dog

### ISSUE THREAD

**Issue by labrsq** [FortAwesome/Font-Awesome#10591]
![image](https://cloud.githubusercontent.com/assets/25471296/22493131/e31aaa5e-e7e2-11e6-8222-7c5323f0cb52.png)
[](url)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1317, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
