### ISSUE TITLE
icon request:  cat

### ISSUE THREAD

**Issue by labrsq** [FortAwesome/Font-Awesome#10592]
[](url)
![image](https://cloud.githubusercontent.com/assets/25471296/22493163/2e171ac4-e7e3-11e6-8005-b94921fc7e15.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2226, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
