### ISSUE TITLE
Icon request: icon-monitor (heartrate, cardiogram line)

### ISSUE THREAD

**Issue by KimPrince** [FortAwesome/Font-Awesome#1059]
Monitor, as in the verb form of the word, e.g. 'let us monitor the situation'.  (Not the noun form, as in monitor = screen).  This could also be called icon-channel, as in 'channel to market'.

I imagine it would look a bit like the line you see on a heart-beat monitor.  I am attaching an image of such now.
![apps-scan-monitor-icon](https://f.cloud.github.com/assets/1072441/493749/57e48478-bb68-11e2-9a88-765a78ad0a36.png)

**Comment by vlipman** [comment]
+1

**Comment by firdausramlan** [comment]
+1

**Comment by jbteague** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by Heinerion** [comment]
+1

**Comment by d3cline** [comment]
+1

**Comment by Arjunpxl** [comment]
+1

**Comment by andreschabur** [comment]
+1
