### ISSUE TITLE
Icon request: fa-universe

### ISSUE THREAD

**Issue by tracysmith10** [FortAwesome/Font-Awesome#10606]
An icon to depict the universe or space would be great for a project I am currently working on.  

![science-512](https://cloud.githubusercontent.com/assets/25510714/22558923/5c51f564-e967-11e6-891d-733857eddfda.png)

**Comment by tagliala** [comment]
Looks like an atom. Duplicate of #664?

**Comment by sensibleworld** [comment]
We have both `atom` and `atom-simple`, as well as `galaxy` and `solar-system`. Let me know if those don't work.
