### ISSUE TITLE
Icon request: tickets

### ISSUE THREAD

**Issue by Sn3b** [FortAwesome/Font-Awesome#10607]
Hi,

I'm using the ticket icon for a page where I create a new ticket, but I'd love to see the same icon in the plural form (bit like user vs users or tag vs tags) that I'd use for my tickets history page :)

That'd be awesome ;)

Thanks!

Seb :)

**Comment by douloh** [comment]
👍🏻

**Comment by subprime** [comment]
+1

**Comment by berzley** [comment]
+1

**Comment by AFlorencia** [comment]
+1

**Comment by leovogel** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/tickets?f=classic&s=solid

**Comment by Sn3b** [comment]
🎉🥳🍾
