### ISSUE TITLE
Icon request: Apple share

### ISSUE THREAD

**Issue by ekkis** [FortAwesome/Font-Awesome#10619]
on a great many occasions now I've needed to include a share button on my apps.  the most iconic form of it looks somewhat like this:

https://fthmb.tqn.com/4_jxGEPZnHWTJZKh3tl7SGVb74Q=/768x0/filters:no_upscale()/about/share_button2-57f7d54e3df78c690f643260.png

which comes from the Apple iPhone but may be seen everywhere.  would it be possible to have that? I know there are various Share icons in the library already but they don't convey sharing like does the image above

**Comment by brackendev** [comment]
I second this.

**Comment by ibushong** [comment]
A million times this! The current "share" icons are literally the same as the "forward" icons, and that's, IMO, generally what they convey.

Here is an example of what I think is a better share icon:

![ios_share](https://cloud.githubusercontent.com/assets/9298422/23722034/aae8e43e-03f8-11e7-81be-44ed07ba9fc6.png)

**Comment by ekkis** [comment]
@ibushong, I agree, the current icon speaks of a forward, but I would prefer the version I suggested.  it comes from Apple and hundreds of millions of people have iPhones and will instantly recognize it.

the hallmark of good iconography is recognition.  to me your icon suggestion seems like an upload

**Comment by ibushong** [comment]
I assume you mean a fontawesome-style version of the icon you linked (rather than that exact icon)? Yes I think that'd be good too.

The main point here is that the current selection of icons does not have a good, IMO, "share" icon, and something closer to a "box with a vertical arrow" would allow devs/designers more choices/flexibility.

**Comment by clarkbaker** [comment]
Here's an imperfect workaround for web.  Unfortunately this only works with FA4.  To create this with FA5 you need to pay for PRO since the arrows are only available in solid (Both icons need to be of the same type using this technique in FA5). You'll need to update the unicode as well as they're different in FA5.

https://jsfiddle.net/clarkbaker/Lq8u9bt6/

**Comment by fmp777** [comment]
I agree, was surprised to find out its not already there.  I am FA5 Pro user.

**Comment by darkmantle** [comment]
Agreed. Just looking for this now.

**Comment by drbarnard** [comment]
+1

**Comment by corwinlw** [comment]
👍

**Comment by gezamiklo** [comment]
👍

**Comment by hoektoe** [comment]
+1 Fa Pro user needs it

**Comment by biteater** [comment]
+1 another Fa Pro user wait's for it here.

**Comment by Krystian95** [comment]
+1 absolutly yes! Like this: 
![share_ios-512](https://user-images.githubusercontent.com/24765669/66438400-d71d6800-ea2c-11e9-9de3-f9096c793f1b.png)

**Comment by lucianholt97** [comment]
+1

**Comment by josh-m-sharpe** [comment]
+1 pro user here.

**Comment by akr4** [comment]
I want this too. As a workaround for now, I use sign-out icon with rotate-270.

**Comment by ebaynaud** [comment]
Only ios share is missing: https://www.pinclipart.com/maxpin/iioTTim/

**Comment by HalitTalha** [comment]
+1

**Comment by ste8** [comment]
+1

**Comment by matmasoni** [comment]
How is this still not a thing?! +1

**Comment by uxchameleon** [comment]
+1

**Comment by SebScoFr** [comment]
+1

**Comment by jdcookie** [comment]
+1 - really need this one please

**Comment by tockv** [comment]
+1

**Comment by mattcrowder** [comment]
+1

**Comment by Cy0u** [comment]
+1

**Comment by lukasz-revolve** [comment]
+1

**Comment by mrlife** [comment]
@tagliala Possible for FA6 launch?

**Comment by laurensnl** [comment]
➕1️⃣

**Comment by JuanDavidLopez95** [comment]
I too second this!🤣

**Comment by sensibleworld** [comment]
Hey folks! We have a couple of options for this available now as part of the v6 alpha release: http://fontawesome.com/download

Icons are `arrow-up-from-square` and `arrow-up-from-bracket`

**Comment by laurensnl** [comment]
Awesome!
