### ISSUE TITLE
Icon Request: icon-beauty

### ISSUE THREAD

**Issue by debby1** [FortAwesome/Font-Awesome#1061]
Hi! Thank you for your work, I use often icon fonts on my forum.

My forum is about beauty (beauty products, parfums, beauty creams, make-up etc). So, you could to add also icons about this things?

For example: http://www.endlessicons.com/category/free-icons/cosmetic-icons/

http://www.behance.net/gallery/Beauty-Products-Icons/7400333

http://images.teamsugar.com/files/upl1/2/20652/32_2008/SherylCrow.jpg

http://www.123rf.com/photo_5041919_cosmetic-icons.html

Lipstick: https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSSaUWyhV_1rbdzDCTbPEMo74SyQ_odA4U6pQTX6Hcvf_7XhTfnFQ

Products: http://4.bp.blogspot.com/-tag2icEFGbQ/TqbNmI-zxgI/AAAAAAAAFFs/Mx1oWA2HbVw/s1600/vs-pink-body-products.jpg
http://4.bp.blogspot.com/-o7rGZShMO9Y/UBVpXjmQt4I/AAAAAAAAAvY/_wgShJ8BV8s/s1600/champneys-spa-oriental-opul.jpg

Mascara: http://www.endlessicons.com/wp-content/uploads/2013/03/mascara-icon-614x460.png
http://cdni.condenast.co.uk/426x639/a_c/Clinique-Bottom-Lash-Mascara-Icon_gl_4mar11_PR_426x639.jpg

Parfums: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSUgjTdFNeEHlLdjelGUCsPDUGPEQZxglFUKZWbAjqhjlFCNXNu
https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQrwA2ZBO1X8m4f7P_xK_PANwOjkkGYuUVJTE78pqVRcMQJNdQ7

Thank you in advance

**Comment by nepa** [comment]
+1 for perfume bottle icon

**Comment by Xgamefactory** [comment]
for perfume there is spray can icon you can use for now. new icons request approving tooks so long.

**Comment by Xgamefactory** [comment]
+1 for beauty icon

**Comment by kubaizi** [comment]
+1 for beauty icon
