### ISSUE TITLE
Interval between lines of the list

### ISSUE THREAD

**Issue by MisterFoto** [FortAwesome/Font-Awesome#10616]
Hello.
Thanks for an excellent product!
Help me please.
I created the list by your example:
http://joxi.ru/12MWJ61SM87gpr 
I need to increase an interval between lines of the list.
http://joxi.ru/MAj38q0i4Y8Yvr
I have a list:
http://joxi.ru/8239DoOcJwXwBr 
And I need to set (assign) h1 and h2
http://joxi.ru/5mddXqkskJKJOm
How to make it? 
Help me please.

**Comment by tagliala** [comment]
Hi,

Font Awesome use plain css.

Feel free to add another class to your `.fa-ul` element and add the style you need

https://jsfiddle.net/tagliala/s3msxtbe/10/

Hope it helps

**Comment by MisterFoto** [comment]
Thank you so much!
