### ISSUE TITLE
Icons duplicate them-selves on CDN.

### ISSUE THREAD

**Issue by gabrielelia** [FortAwesome/Font-Awesome#10625]
I created a xml document and everything was ok, when I convert it in HTML some icons were duplicated, here there is a screen, the red part was the original one:
https://1.bp.blogspot.com/--zQ3pTUjHR4/WJi8gj1HCHI/AAAAAAAAAh0/9obr96Y4txYXzZTRLq-88OEmfLAE0kTMgCLcB/s1600/gggggggggggg.JPG

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We need more information

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by gabrielelia** [comment]
Hi! I give you an example of code:
https://jsbin.com/xawerajaji/edit?html,output
there is only an icon in the header.

**Comment by tagliala** [comment]
```html
<a class="fa fa-search" style="font-size:20px; line-height: 90px;" aria-hidden="true" />
```

This is not valid HTML.

![image](https://cloud.githubusercontent.com/assets/556268/22704208/2bfe28e8-ed67-11e6-9c7a-7745fa9cd791.png)

Also, this is not the way you are supposed to use Font Awesome

```rb
<a style="font-size:20px; line-height: 90px;">
  <span class="fa fa-search" aria-hidden="true"></span>
  <span class="sr-only">Search</span>
</a>
```

Hope it helps, closing here
