### ISSUE TITLE
Icon Request: fa-stockupdate

### ISSUE THREAD

**Issue by jganga1841** [FortAwesome/Font-Awesome#10628]
Icon for represent the Stock update.
![stockupdate](https://cloud.githubusercontent.com/assets/25383824/22685937/4ad626c2-ed48-11e6-92aa-1d82ed46e7a6.png)

**Comment by tagliala** [comment]
Is "stock update" a brand or a standard action in some field?

If it isn't we should 

Does one of the following fit your needs?
http://fontawesome.io/icon/reply/
http://fontawesome.io/icon/retweet/

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
