### ISSUE TITLE
Icon Request: fa-user-slash

### ISSUE THREAD

**Issue by rarangels** [FortAwesome/Font-Awesome#10636]
I think that, it's very important to have these icons:

user-circle-block
user-circle-o-block
user-block
user-o-block

![Example](https://cloud.githubusercontent.com/assets/17284005/22714973/f5105608-ed5c-11e6-9ae2-0876913e2009.png)

**Comment by tagliala** [comment]
Related to #1181, you will find a solution there

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-slash?style=solid

**Comment by ligne13** [comment]
Looks like the guy/girl is being beheaded by a guillotine. I 'm french so I maybe the only one to see that :-)

**Comment by rarangels** [comment]
@ligne13 jajajajajaja
