### ISSUE TITLE
Icon Request: fa-mole

### ISSUE THREAD

**Issue by rizzoait** [FortAwesome/Font-Awesome#10632]
This is the main monument of Turin ( Italy )
![icon-mole](https://cloud.githubusercontent.com/assets/16926864/22691001/aba3df04-ed38-11e6-8f3c-30cfdd68c6fb.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I need to close this request, since landmarks are out of scope at the moment

Ref: #2661 #6815
