### ISSUE TITLE
Icon Request: Beauty tools

### ISSUE THREAD

**Issue by kozanno** [FortAwesome/Font-Awesome#10639]
Would love to see beauty related icons
makeup brushes
hair dryers
combs
hair brush
scissors
lips / kiss

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
