### ISSUE TITLE
Icon request: icon-payroll; 

### ISSUE THREAD

**Issue by HeroRender** [FortAwesome/Font-Awesome#10637]
Hi Awesome :)
may I request these icons please? pretty please?
Icon request: icon-payroll-history
Icon request: icon-attendance-history
Icon request: icon-apply-leave
Icon request: icon-overtime
Icon request: icon-time-logs
Icon request: icon-loan-history

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by HeroRender** [comment]
awwww. why? but is the request possible?
