### ISSUE TITLE
Icon Request: fa-paid

### ISSUE THREAD

**Issue by markmeikle** [FortAwesome/Font-Awesome#10634]
Mark an order as paid, such as on a receipt or invoice.
![paid](https://cloud.githubusercontent.com/assets/20950563/22710950/f5755e26-ed44-11e6-91f7-1053807a7707.gif)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is language dependent and we are trying to avoid this kind of glyphs, so I'm going to close this one. Also, putting 4 letters in a 16px icon size is not the best choice

Please consider plain text, stacking feature or a simple `fa-check`.

If you have something better in mind, feel free to open a new request
