### ISSUE TITLE
Embed Code giving 403 (Forbidden) Error

### ISSUE THREAD

**Issue by mparker11** [FortAwesome/Font-Awesome#10648]
I signed up for the cdn service and was given a url with my embed code, something like **https://use.fontawesome.com/embedcode.js**.

When I run my app I get a Forbidden error saying it can't retrieve the CSS file associated. Has anyone had this problem?

**Comment by tagliala** [comment]
AFAIK, fortawesome was getting some errors.

https://twitter.com/getfortawesome/status/830182301032185856

Is it ok now?

**Comment by mparker11** [comment]
![shot_170210_203425](https://cloud.githubusercontent.com/assets/825507/22851236/6683cd54-efd0-11e6-97a8-4596dd7f9d9d.jpg)

Still having the problem

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by robmadole** [comment]
@mparker11 sorry, this issue fell through the cracks. I've got this resolved now.
