### ISSUE TITLE
Dependencies error with new Laravel webpack

### ISSUE THREAD

**Issue by IkRookG** [FortAwesome/Font-Awesome#10644]
**Information**

With the release of the new laravel (5.4) and the default usage of the new webpack instead of gulp to compile all resources using `npm run dev` also came a new way to load url's in sass. Instead of paths like; `../fonts` there now a need to have the paths look like this: `~/fonts/font.eot`.

I'm not really sure how non-laravel projects react to this change thus why I am making this issue.

**The changes that need to be made are as follows:**

1. Go to `node_modules/font-awesome/scss/_variables.scss:4`.
2. Change `"../fonts/"` to `"~/../fonts"`.

**How to duplicate this error**

1. Setup a (fresh) laravel 5.4 environment using the new webpack and npm.
2. Add the font-awesome module and run the `npm install` command.
3. After the install is done, run `npm run dev`.

**Exact error relevant for the font-awesome module:**
```
These dependencies were not found in node_modules:

* ../fonts/fontawesome-webfont.eot?v=4.7.0
* ../fonts/fontawesome-webfont.eot
* ../fonts/fontawesome-webfont.woff2?v=4.7.0
* ../fonts/fontawesome-webfont.woff?v=4.7.0
* ../fonts/fontawesome-webfont.ttf?v=4.7.0
* ../fonts/fontawesome-webfont.svg?v=4.7.0
```

**Comment by brunowerneck** [comment]
Adding

```javascript
    .copy('node_modules/font-awesome/fonts', 'resources/assets/fonts')
    .copy('node_modules/font-awesome/fonts', 'public/fonts')
```

to `webpack.js` solves this problem

**Comment by henriquebremenkanp** [comment]
@IkRookG update your package.json to get the latest version of laravel mix and it will work.

https://github.com/laravel/laravel/commit/e8b4f0e6ce5299972b656a562742c928b72f4d9d

**Comment by IkRookG** [comment]
This issue has been fixed for a while with the newer laravel-mix versions.
