### ISSUE TITLE
Camping Icons

### ISSUE THREAD

**Issue by sepub** [FortAwesome/Font-Awesome#10646]
Hello, it would be great to have some camping and outdoor icons in here.

https://static.vecteezy.com/system/resources/previews/000/082/671/non_2x/camping-camp-food-vector-icons.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
