### ISSUE TITLE
Icon Request: Flipboard

### ISSUE THREAD

**Issue by beethedude** [FortAwesome/Font-Awesome#10647]
Please add Flipboard to your icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1382, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by beethedude** [comment]
That looks like a 3+ year old request. Do you anticipate that this will be added at all?
