### ISSUE TITLE
Icon request: fa-handshake-times

### ISSUE THREAD

**Issue by publicocean0** [FortAwesome/Font-Awesome#10653]
hi i found a icon for  (fa-join)
https://d30y9cdsu7xlg0.cloudfront.net/png/24572-200.png
the fa-disjoin is the same icon with a X over

It want show the concept a user  is joint  to a group or agreed with another

the opposite concept is disjoint

**Comment by publicocean0** [comment]
i correct the post, the first one is present. 
just the disjoint icon so

**Comment by publicocean0** [comment]
i want emproving soon also bindep tool so it is possible directly by compiling&assembling tool to build css tailored on the specific project using preprocessor.

**Comment by tagliala** [comment]
Refers to #1181, you will find a solution there

**Comment by aethior** [comment]
Hi @publicocean0,

Maybe can you use [fa-handshake-slash](https://fontawesome.com/icons/handshake-slash) icon?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, I think it fits the use case

Otherwise please comment and I will reopen
