### ISSUE TITLE
Buffer 

### ISSUE THREAD

**Issue by suraj1kc** [FortAwesome/Font-Awesome#10661]
Can you add Buffer icons :)
![buffer](https://cloud.githubusercontent.com/assets/6723482/22916197/21390a34-f2a5-11e6-93c5-a2b81b3c1455.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2110, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
