### ISSUE TITLE
Icon Request: Essential Travel

### ISSUE THREAD

**Issue by zakst** [FortAwesome/Font-Awesome#10666]
A travel icon set.

Hotel
Island
Mountain
Sea
Chilled man
Chilled woman

and i trust your imagination

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
