### ISSUE TITLE
Icon Request: fa-file-csv

### ISSUE THREAD

**Issue by xuancanpro** [FortAwesome/Font-Awesome#10678]
I need file type *.csv

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5015, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by xuancanpro** [comment]
why i can't display it in my website
