### ISSUE TITLE
Icons request: Blizzard games - Diablo 3 and World of Warcraft

### ISSUE THREAD

**Issue by PekaFat** [FortAwesome/Font-Awesome#10688]
It can be used on personal pages for link up profiles in these games.

![d3](https://cloud.githubusercontent.com/assets/13280748/23125113/a9d245ac-f789-11e6-92ab-8eb08ded6a40.png)
<img width="512" alt="d33" src="https://cloud.githubusercontent.com/assets/13280748/23125114/a9d2704a-f789-11e6-9345-04a37f5fe0b0.png">
![wow](https://cloud.githubusercontent.com/assets/13280748/23125112/a9d1bea2-f789-11e6-95c8-e4a62cc289d2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
