### ISSUE TITLE
Provide JSON of all icon class names.

### ISSUE THREAD

**Issue by tempusrname** [FortAwesome/Font-Awesome#10682]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3366, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tempusrname** [comment]
Any news on this considering it was requested in 2014?
