### ISSUE TITLE
Icon Request: file-media, file-download, fa-library

### ISSUE THREAD

**Issue by vichiodo** [FortAwesome/Font-Awesome#10681]
Hii,
I making this app and every single icon is font-awesome but I need this three icons and them doesn't exist! So please, please add this three svg so I can't complete my project!!
Thank you soo much.. love font-awesome.

![icon-csv](https://cloud.githubusercontent.com/assets/8626734/23078586/783adf8c-f530-11e6-8002-e33d511af7b7.png)
![icon-kml](https://cloud.githubusercontent.com/assets/8626734/23078585/783a33ac-f530-11e6-9211-f8a8e5778878.png)
![libary](https://cloud.githubusercontent.com/assets/8626734/23078588/785701e4-f530-11e6-80be-b0ba3a4f34c0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
