### ISSUE TITLE
Icons not visible

### ISSUE THREAD

**Issue by rockchalkwushock** [FortAwesome/Font-Awesome#10684]
I've been searching through the issues but haven't found anything that was the same. I believe this could possibly be a webpack issue since I've never had an issue using Font Awesome before. Haven't put my finger on it just yet.

**Font Awesome** (_yarn add font-awesome_)
^4.7.0
**Webpack**
^2.2.1
**React**
^15.4.2
**OS X**
10.12.3

I imported the Font Awesome CSS library as I always do in my entry file:

```javascript
import 'font-awesome/css/font-awesome.css';
```

and I have several icons being used (here is one instance):

```javascript
      <a
        className='icon'
        target='_blank'
        rel='noreferrer noopener'
        href='https://www.facebook.com/'
        title='facebook'
      >
          <i className="fa fa-facebook-square fa-2x"></i>
      </a>
```

_webpack_
```javascript
const webpack = require('webpack');
const { join } = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const VENDOR_LIBS = [
  'react', 'react-dom', 'react-router',
  'react-redux', 'react-router-redux', 'redux',
  'styled-components'
];

module.exports = {
  devtool: 'eval',
  target: 'web',
  entry: {
    bundle: [
      'babel-polyfill',
      'react-hot-loader/patch',
      'webpack-dev-server/client?http://localhost:9000',
      'webpack/hot/only-dev-server',
      './client/index.js'
    ],
    vendor: VENDOR_LIBS
  },
  output: {
    path: join(__dirname, 'dist'),
    filename: '[name].js',
    publicPath: '/'
  },
  module: {
    rules: [
      {
        use: 'babel-loader',
        test: /\.js$/,
        exclude: /node_modules/
      },
      {
        loader: ExtractTextPlugin.extract({
          loader: 'css-loader'
        }),
        test: /\.css$/
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        use: [
          {
            loader: 'url-loader',
            options: { limit: 40000 }
          },
          'image-webpack-loader'
        ]
      },
      {
        test: /fonts\/.*\.(woff|woff2|eot|ttf|svg)$/,
        loader: 'file-loader?name="[name]-[hash].[ext]"',
      }
    ]
  },
  devServer: {
    contentBase: join(__dirname, './dist'),
    port: 9000,
    hot: true,
    historyApiFallback: true,
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new HtmlWebpackPlugin({
      template: 'client/index.html'
    }),
    new ExtractTextPlugin('style.css'),
  ]
};
```

The result I am getting in the DOM is:

![screen shot 2017-02-18 at 9 14 26 am](https://cloud.githubusercontent.com/assets/19720404/23094338/9200dc78-f5bc-11e6-85ec-21198f8f09cc.png)

I'm noticing two things in my `dist/`. 

1. There is no _font-awesome.css_ compiled into the `dist/`.
2. I am questioning _hashing_ the other font-awesome files.

![screen shot 2017-02-18 at 9 31 22 am](https://cloud.githubusercontent.com/assets/19720404/23094368/2f2ad35a-f5bd-11e6-840f-c34229528546.png)

**Comment by Aladdin-ADD** [comment]
can you post how did you solve it?

**Comment by rockchalkwushock** [comment]
@Aladdin-ADD 

I used [`react-fontawesome`](https://github.com/danawoodman/react-fontawesome) instead. 

1. `yarn add react-fontawesome`
2. [Insert stylesheet for font-awesome](https://github.com/rockchalkwushock/photography-frontend/blob/master/client/index.html#L7)
3. [Use package where you want](https://github.com/rockchalkwushock/photography-frontend/blob/master/client/commons/MailIcon.js#L2)

Hope that helps 😃
