### ISSUE TITLE
Icon Request: Various Weapons

### ISSUE THREAD

**Issue by jay2001** [FortAwesome/Font-Awesome#10690]
I currently have a project where I refer to weapons. In this case it is all rifles but I am using the pistol emoji...

🔫  http://emojipedia.org/pistol/

The problem is it isn't the same on all platforms. Any chance of a rifle icon? You could add pistol, throwing star, swords etc... at the same time if you fancied I'm sure someone would use them and it would make a nice set.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
