### ISSUE TITLE
Icon-Request: vinyl and turntable

### ISSUE THREAD

**Issue by antoniu86** [FortAwesome/Font-Awesome#10693]
Hi,

It would be awesome if you could add these 2 icons like fa-vinyl and fa-turntable. 

Thanks,
Tony

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5737 and #2406 , please add a 👍  reaction to those requests.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
