### ISSUE TITLE
Icon request: icon-airbnb

### ISSUE THREAD

**Issue by parce141** [FortAwesome/Font-Awesome#10697]
I would like to use it on my new page to redirect to "airbnb" just like a link but I want to use  this icon

![airbnb](https://cloud.githubusercontent.com/assets/17696209/23246257/df791648-f957-11e6-84cd-622e0b1cd676.png)

**Comment by parce141** [comment]
please

**Comment by parce141** [comment]
i need it or how can I change it, some help please

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7650, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment]
@parce141 please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by mircsicz** [comment]
+1
