### ISSUE TITLE
Icon request: fa-scatterplot

### ISSUE THREAD

**Issue by andreaphsz** [FortAwesome/Font-Awesome#10694]
Would be nice to have an icon for a (2d) [Scatter_plot](https://en.wikipedia.org/wiki/Scatter_plot).

**Comment by aethior** [comment]
Hi @andreaphsz,

This icon was added in v5.7.0.
Check https://fontawesome.com/icons/chart-scatter

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Duplicate of #4240
