### ISSUE TITLE
I cannot paste FA icon from the cheatsheet to my Adobe PS CC2017 canvas. Please help.

### ISSUE THREAD

**Issue by myboo** [FortAwesome/Font-Awesome#10706]
Today, I upgrade my OS to sierra and also update to Adobe Photoshop CC 2017. I try to use fontawesome. As usually I copy the icon from FA cheatsheet and paste into my PS canvas, but I cannot paste all icons since I upgrade to macOS and CC2017. Please help.

thank you :)

**Comment by tagliala** [comment]
> but I cannot paste all icons since I upgrade to macOS and CC2017. Please help.

Do you mean that you can paste some icons?
