### ISSUE TITLE
Icon request: Money-Bag

### ISSUE THREAD

**Issue by lkatme** [FortAwesome/Font-Awesome#10709]
![moneybag](https://cloud.githubusercontent.com/assets/26064912/23366277/c986c340-fccb-11e6-8b09-ea084ed94318.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
