### ISSUE TITLE
Need up and down arrow together 

### ISSUE THREAD

**Issue by RatanPaul** [FortAwesome/Font-Awesome#10700]
hey guys is this icon is available?

I need for sorting. 

<a href="http://tinypic.com?ref=2rhntjm" target="_blank"><img src="http://i64.tinypic.com/2rhntjm.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by tagliala** [comment]
Hi,

Please check if 

http://fontawesome.io/icon/sort/
http://fontawesome.io/icon/sort-asc/
http://fontawesome.io/icon/sort-desc/

fit your needs

**Comment by tagliala** [comment]
No, they aren't.

But you can use the above icons and +1 request #8144 which is asking for the same thing

Closing here
