### ISSUE TITLE
Icon request: icon-Boss

### ISSUE THREAD

**Issue by Christiannn** [FortAwesome/Font-Awesome#10717]
Hi,
we need a Boss/Leader/Approver Icon... 
you can't get around those kind of people anymore :)

maybe like this? 
https://www.screencast.com/t/KEDOHpJVDzN
(i cant upload to this site for some reason, therefore the link)

**Comment by tagliala** [comment]
Please fix the example

**Comment by tagliala** [comment]
Maybe this is a duplicate of #3397

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
