### ISSUE TITLE
Icon request: icon-network

### ISSUE THREAD

**Issue by sunil1293** [FortAwesome/Font-Awesome#10713]
![network_icon](https://cloud.githubusercontent.com/assets/5036347/23403555/9c1ca31e-fdd6-11e6-9aca-109c4f23f0fa.png)

Please add this icon to display the network towers available / signals and it will be helpful to show two way sound.

**Comment by tagliala** [comment]
Maybe http://fontawesome.io/icon/rss/ fits your needs

**Comment by schowes** [comment]
+1

**Comment by schowes** [comment]
@tagliala the RSS icon is too closely identified with RSS to be usable in the way a signal or network icon would be needed. Would love to have both.

**Comment by sunil1293** [comment]
@tagliala : we can rotate rss icon to some angle and use one way sound signals, but it doesn't fits for two way around.
It is good to have this two way signal icon as well. Thanks in advance. 👍

**Comment by sensibleworld** [comment]
Playing some catch-up on older icon requests. We now have an icon that should fit this use case: https://fontawesome.com/icons/signal-stream?style=solid
