### ISSUE TITLE
Icon request: icon-book

### ISSUE THREAD

**Issue by gerald2799** [FortAwesome/Font-Awesome#10716]
i plan to use it like img for button( it could have only shape, so you suruly know that is a book). or i also would be happy to see a simple rectangle =)
![book-icon-vector-1918631](https://cloud.githubusercontent.com/assets/24938726/23408857/389c8326-fdd2-11e6-8cc1-d80760903217.jpg)

**Comment by tagliala** [comment]
Already here: http://fontawesome.io/icon/book/

**Comment by gerald2799** [comment]
not what i looking for
