### ISSUE TITLE
Icon Request: fa-8-ball, fa-9-ball, fa-10-ball

### ISSUE THREAD

**Issue by thalueng** [FortAwesome/Font-Awesome#10714]
I'm running several pool league websites, icons for 8, 9 and 10-ball games would be greatly appreciated. It's a circle with the number inside.

**Comment by tagliala** [comment]
Hi,

Please consider using stacking feature: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/ or go with plain css

Ref: #6099
