### ISSUE TITLE
Fontawesome Selector

### ISSUE THREAD

**Issue by robert02** [FortAwesome/Font-Awesome#10711]
Hi all,
i have written a PC (Win) Application, the user can easy select visual a icon. and as result comes a final html, css content , UBB and more code. one click to clipboard and paste into your code editor.
add function fix width spin dont-size and pull-left right.
If the master of fontawesome gave some interesting, please contact me.
Best regards Robert

**Comment by saitho** [comment]
How is that different from the icon search FontAwesome already has? http://fontawesome.io/icons/

**Comment by robert02** [comment]
Its a PC Application, you can select visualy the required Icon and becames the as result 
HTML-code UBB-Code ,.........  you select Large in the html code is automatocally insert fa-lg and any more additional features, for ex. rotate flip.
you becames the Icon code for CSS content:"\f002";
Is a single EXE and no internet connection ist required.

**Comment by tagliala** [comment]
Hi,

> Is a single EXE and no internet connection is required.

You could open a new github repo and put there your application together with source code, then feel free share here your work, it may be useful for someone
