### ISSUE TITLE
Icon request: icon-designer

### ISSUE THREAD

**Issue by ekkis** [FortAwesome/Font-Awesome#10722]
I need an icon to indicate the user can open a designer i.e. a tool for designing something.  I'm not quite sure what it could look like (and I'm open to suggestions if some existing icon could fit the bill) but I think it's an important part of the software development process... we always have designers to do stuff

as for imagery, I'm thinking something like the tools architects use, like the images below, which can be fairly iconic:

https://thumbs.dreamstime.com/z/designer-tools-black-icons-graphic-studio-creative-process-set-isolated-vector-illustration-40838260.jpg

the third image on the top row, or maybe the first on the fourth row would be great.  a palette, or easel might also be good images for this

https://designmodo.com/wp-content/uploads/2015/11/9-Icons-Responsive-Material-Design-Palette.jpg

third icon, third row

http://squaregate.co.uk/assets/minimal-icon-set-design-1.jpg

real pretty, 2nd and 3rd icons on top row

**Comment by schowes** [comment]
+1

**Comment by DSwissK** [comment]
+1 easel

**Comment by aethior** [comment]
Hi @ekkis,

Currently there is a [**design category**](https://fontawesome.com/search?c=design) with many of the proposed icons.
(There are also other posible icons in other categories)

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Closing here

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
