### ISSUE TITLE
Icon Request: icon-pipe (vertical line)

### ISSUE THREAD

**Issue by ColinLondon** [FortAwesome/Font-Awesome#1072]
I say "icon-pip" but it could be "icon-vertical-bar".

In any event, I mean the keystroke that inserts a vertical line, often used between links in the footer (attached an image showing the bar in the middle of two links).

Would be good to have two versions of this: a solid bar; or as vertical row of dots.

Thanks,
Colin

![pipe](https://f.cloud.github.com/assets/4428323/501792/0c014724-bca0-11e2-8842-7db5defeca30.png)

**Comment by crhallberg** [comment]
+1

**Comment by dclaybrook** [comment]
+1

**Comment by HarryStevens** [comment]
+1

**Comment by M-Shahbaz** [comment]
+1

**Comment by c27cochran** [comment]
+1

**Comment by leblangi** [comment]
+1

**Comment by jtashley** [comment]
+1

**Comment by Greatshock** [comment]
+1

**Comment by ivhysenbelli** [comment]
+1

**Comment by jlawton2** [comment]
Similar problem; read this thread and solved simply using `fa-layers`:

```
<span class="fa-layers fa-fw fa-2x">
  <i class="fas fa-lock" data-fa-transform="shrink-4 up-7 left-7"></i>
  <i class="fas fa-shield-alt" data-fa-transform="shrink-4 down-7 right-7"></i>
  <span class="fa-layers-text" data-fa-transform="grow-10 rotate-45">|</span>
</span>
```

Ideally, a simple line icon would be fantastic, but a pipe as text works pretty good good.

**Comment by woloched** [comment]
+1

**Comment by alandarr** [comment]
One more vote for this one...

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of version 6: http://fontawesome.com/download
