### ISSUE TITLE
Icon request: sass & jquery icons (logo)

### ISSUE THREAD

**Issue by lffg** [FortAwesome/Font-Awesome#10725]
Icon request: sass & jquery icons (logo)

=)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2894 and #1665 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
