### ISSUE TITLE
VPN use causes use.fontawesome.com to take 20 seconds to load

### ISSUE THREAD

**Issue by Canadaboy** [FortAwesome/Font-Awesome#10720]
Use of a VPN appears to slow page load, with the wait being exclusively for the call to use.fontawesome.com. 

VPN in test is provided by Private Internet Access. 

Additional time to load use.fontawesome.com is in the range of 15-20 seconds. Everything else loads as expected for speed/timing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Take a look at fort awesome's twitter account for status updates

https://twitter.com/getfortawesome/status/836659550723821568

**Comment by Canadaboy** [comment]
LOL - ok, this was a timing issue! I've retested now that AWS is running correctly, and it all appears to have been that (didn't know it was going down when I posted this). Must have also been related to the VPN routing and AWS. Everything seems good now. Will post new if VPN issue is realized during non-AWS chaos day!
