### ISSUE TITLE
Icons not showing in Firefox 51.0.1 from local install

### ISSUE THREAD

**Issue by bethal** [FortAwesome/Font-Awesome#10726]
I have followed the the below Wiki & ensured all things in place:
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

I have added meta as mentioned here:
http://stackoverflow.com/questions/41471117/font-awesome-icons-not-showing-on-ie-and-firefox/41472520#41472520

Still icons are not showing up; if I load icons from CDN it is working fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide as many information as you can and check your development console for errors.

If you think there is an issue with Font Awesome, please provide a jsfiddle showing the issue.

If you are serving icons from your own server, please double check that everything is fine (from paths to mime types)

I was able to load font awesome even from the `file:///` protocol without any issue

![image](https://cloud.githubusercontent.com/assets/556268/23471387/64b0e894-fea9-11e6-974d-d6746ee35c5d.png)

Meanwhile, closing here

**Comment by bethal** [comment]
Although from `file:///` it is not working; it is working on `localhost:8383`.
