### ISSUE TITLE
FreeCodeCamp icon issue

### ISSUE THREAD

**Issue by JohnMica** [FortAwesome/Font-Awesome#10735]
![captura de ecran din 2017 03 02 la 23 42 04](https://cloud.githubusercontent.com/assets/7076631/23532145/e48da040-ffa1-11e6-881b-81e1430aa7f4.png)
As per the image attached, the FCC icon is a bit different then the other.
It has more width then height which will result in the improper display of the icon with a background.

Not sure how this is going on, but with a fixed height and width and border-radius 50%, the icon stays a circle otherwise it becomes an ellipsis.

**Comment by tagliala** [comment]
Please add `fa-fw` class, then let me know

**Comment by JohnMica** [comment]
by adding the fa-fw the images become 1.238 wide (as per the class) and thus the result is even worse. I'm going to try and find a different solution

**Comment by tagliala** [comment]
you should adjust your background circle accordingly

**Comment by JohnMica** [comment]
thanks for the suggestions - I was aiming for a "universal" size icons but I have to individually play with them. I know - different icons means different sizes, but was hoping 👍
