### ISSUE TITLE
Icon Request: fa-angle-right-thin

### ISSUE THREAD

**Issue by Romain-cotton** [FortAwesome/Font-Awesome#10732]
Hi! Requesting for 4 icons which looks like an arrow end (already existing like : fa-angle-right) but thinner.
May look like this one (https://www.iconfinder.com/icons/296832/arrow_right_icon#size=512).
Thanks ! :)
![image](https://cloud.githubusercontent.com/assets/25501635/23502623/be569954-ff38-11e6-8386-4f1e1f6cb45c.png)

**Comment by tagliala** [comment]
I'm going to close this because it is a subset of #5912
