### ISSUE TITLE
Icon Request: fa-speaker

### ISSUE THREAD

**Issue by brystfire08** [FortAwesome/Font-Awesome#10731]
Hi! Requesting for an icon which looks like a speaker  for web development purposes
May look like this one:
![2000px-speaker_icon svg](https://cloud.githubusercontent.com/assets/21236039/23501590/6752f684-ff6f-11e6-9379-e4265db70522.png)

TIA :)

**Comment by mschnack** [comment]
Take a look at [http://fontawesome.io/icon/volume-up/](volume-up)

**Comment by tagliala** [comment]
@mschnack thanks

closing here

**Comment by brystfire08** [comment]
Silly me didnt see that one thanks :)
