### ISSUE TITLE
Pls fix this issue - high risk

### ISSUE THREAD

**Issue by esmatptr** [FortAwesome/Font-Awesome#10742]
![image](https://cloud.githubusercontent.com/assets/10085853/23590782/f75c641e-01ee-11e7-84a7-bdca58649d94.png)

**Comment by tagliala** [comment]
Cannot replicate

OSX 0.12.3 / Chrome 56, Firefox 51, Safari 10.0.3

**Comment by esmatptr** [comment]
goto http://fontawesome.io
click on download, it is causing the problem

**Comment by esmatptr** [comment]
the jquery library causing the issue as I can see, maybe someone edited something there

**Comment by tagliala** [comment]
I cannot replicate, could you please clear your browser cache and retry?

**Comment by tagliala** [comment]
Everything is fine on my Windows machine, too

**Comment by tagliala** [comment]
btw here it is the direct link to download: http://fontawesome.io/assets/font-awesome-4.7.0.zip
