### ISSUE TITLE
Icon Request: fa-water-bottle

### ISSUE THREAD

**Issue by makaronnik** [FortAwesome/Font-Awesome#10741]
Icon for water delivery. Exaples:
http://www.clipartkid.com/images/475/water-bottle-5-gallon-water-bottle-bq-01a-1-sAVjoC-clipart.jpg
https://cdn.vectorstock.com/i/composite/14,08/water-cooler-bottle-vector-61408.jpg
Thank you!

**Comment by shemake** [comment]
+1 for this if it looks like a regular drinking bottle

**Comment by makaronnik** [comment]
Closed after a long period of time with no response
