### ISSUE TITLE
Icon Request: fa-check-circle-o

### ISSUE THREAD

**Issue by pekpyt1** [FortAwesome/Font-Awesome#10744]
![1](https://cloud.githubusercontent.com/assets/26226305/23615423/0a94cbd4-028f-11e7-8607-4c868bf5b84a.png)

**Comment by pekpyt1** [comment]
![2](https://cloud.githubusercontent.com/assets/26226305/23615528/6cecbd00-028f-11e7-9dfb-bc836d2589f8.png)

**Comment by sensibleworld** [comment]
Does this cover it? https://fontawesome.com/icons/check-circle?style=regular

**Comment by aethior** [comment]
> Does this cover it? https://fontawesome.com/icons/check-circle?style=regular

I think so.
