### ISSUE TITLE
Icon Request: ResearchGate

### ISSUE THREAD

**Issue by kronflux** [FortAwesome/Font-Awesome#10758]
I'd like the logo for ResearchGate(https://www.researchgate.net/) to be added to Font-Awesome as it ties nicely with Linkedin and is used by many universities for research papers and publishings.

Their logo is extremely basic, but I'm not sure what font they used, and the current image is non-transparent.

**Comment by kronflux** [comment]
![apple-touch-icon-180x180](https://cloud.githubusercontent.com/assets/834451/23693105/f44e9808-038f-11e7-9efe-792b6176b0a3.png)
The only available logo I could find

**Comment by juliohm** [comment]
Not only you, many people are waiting: https://github.com/FortAwesome/Font-Awesome/issues/3634

Please consider closing this issue. Also use the search bar in the issues page to avoid duplicates.

**Comment by kronflux** [comment]
oops! sorry about that. :) Thanks.
