### ISSUE TITLE
Icon Request: fa-package

### ISSUE THREAD

**Issue by rickdepeer** [FortAwesome/Font-Awesome#10754]
An icon that represents mail delivery for packages
![shipping-box](https://cloud.githubusercontent.com/assets/12747977/23650674/37f58b9c-0323-11e7-8004-08793a42709b.png)

**Comment by allor** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #908, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
