### ISSUE TITLE
拜托了，感谢！

### ISSUE THREAD

**Issue by BastardZhnSo** [FortAwesome/Font-Awesome#10752]
![z3](https://cloud.githubusercontent.com/assets/21953800/23639051/368bb63a-0320-11e7-9330-5960f95ffcee.png)
![z4](https://cloud.githubusercontent.com/assets/21953800/23639052/368d3442-0320-11e7-9fd7-15ca0a61f766.png)
![z5](https://cloud.githubusercontent.com/assets/21953800/23639053/36917f5c-0320-11e7-918b-7c4aa7b7340c.png)
![z7](https://cloud.githubusercontent.com/assets/21953800/23639054/36c05746-0320-11e7-8c8a-4842e2af481d.png)
![z8](https://cloud.githubusercontent.com/assets/21953800/23639055/36c20690-0320-11e7-9599-abb5f825025d.png)
![z10](https://cloud.githubusercontent.com/assets/21953800/23639056/36f415e0-0320-11e7-930b-bce0f2664780.png)
![z11](https://cloud.githubusercontent.com/assets/21953800/23639057/36f6fc06-0320-11e7-92f4-207ac81c7d48.png)
![z12](https://cloud.githubusercontent.com/assets/21953800/23639058/372831ea-0320-11e7-8359-c859d3c17a05.png)
![z13](https://cloud.githubusercontent.com/assets/21953800/23639059/3728f6b6-0320-11e7-8d5c-d98fde5c2e16.png)
![z14](https://cloud.githubusercontent.com/assets/21953800/23639061/3a189aa2-0320-11e7-870a-8419dec345a3.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
