### ISSUE TITLE
Icon request : discord

### ISSUE THREAD

**Issue by Ruther104** [FortAwesome/Font-Awesome#10778]
Could be nice to have a Discord Icon like that
![discord_logo1600](https://cloud.githubusercontent.com/assets/13911429/23825101/cd255fea-0683-11e7-922f-510a86537b8a.png)

**Comment by hydrabolt** [comment]
An issue already exists here https://github.com/FortAwesome/Font-Awesome/issues/7574

**Comment by tagliala** [comment]
@hydrabolt thanks
