### ISSUE TITLE
Icon Request: fa-material

### ISSUE THREAD

**Issue by AjithLalps** [FortAwesome/Font-Awesome#10774]
i cant find a useful icon for materials, shopping bags are there. but i think it is not suitable for the label material like raw materials . so need a good icon for material.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
