### ISSUE TITLE
Icon request: shopping-cart-o

### ISSUE THREAD

**Issue by gerald2799** [FortAwesome/Font-Awesome#10770]
as one as you already have, but empty inside.

**Comment by PeterShaggyNoble** [comment]
See #10051.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10051, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
