### ISSUE TITLE
Icon Request : Icon-faucet; Icon-woodworking; Icon-Painter; 

### ISSUE THREAD

**Issue by irilind** [FortAwesome/Font-Awesome#10777]
Hello Font-Awesome
I'm building a directory site for services and I need some icons mentioned in the title
Any simple icon that represents the requests in the title would work.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
