### ISSUE TITLE
Icon Request: ORCHID ID

### ISSUE THREAD

**Issue by DrMJEG** [FortAwesome/Font-Awesome#10779]
It would be nice to have an icon for ORCHID ID for researchers.
This would be great to supplement a Research Gate icon for which there is a separate request.

https://orcid.org/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4401, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
