### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by eroskamp33** [FortAwesome/Font-Awesome#10782]
Hi,

Can i request the following icons

- clown
- theatre
- dance
- bouncy-castle
- face-painter
- playground
- stiltwalker
- 

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
