### ISSUE TITLE
Icon Request: cart-icon

### ISSUE THREAD

**Issue by giannisgiat** [FortAwesome/Font-Awesome#10789]
![continuous-line-house](https://cloud.githubusercontent.com/assets/26403346/23891578/c3c7d590-089f-11e7-983d-c312dce3f110.png)
![continuous-line-envelope](https://cloud.githubusercontent.com/assets/26403346/23891574/c3c448b2-089f-11e7-9e9e-8e6aed4835cb.png)
![continuous-line-padlock](https://cloud.githubusercontent.com/assets/26403346/23891575/c3c47f26-089f-11e7-9543-8b6063bd8d17.png)
![continuous-line-calendar](https://cloud.githubusercontent.com/assets/26403346/23891577/c3c5f3b0-089f-11e7-92bb-a46fb525f71b.png)
![basic-magnifying-glass](https://cloud.githubusercontent.com/assets/26403346/23891576/c3c5b6b6-089f-11e7-9604-75b80862039d.png)
![basic-shopping-cart](https://cloud.githubusercontent.com/assets/26403346/23891579/c3c904f6-089f-11e7-8f28-e2fa1fc252ba.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

If you are looking for a shopping cart, here it is: http://fontawesome.io/icon/shopping-cart/

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
