### ISSUE TITLE
Category request - People

### ISSUE THREAD

**Issue by Ryzza5** [FortAwesome/Font-Awesome#10787]
Could you please add a new category called 'People' which would show any icon that looked like a person or user?
example:

add user
bed?
blind
child
female
male
remove user
street view
universal access
user
user secret
users
wheelchair
wheelchair-alt
user-md

Thanks

**Comment by sensibleworld** [comment]
We have this now in both v6: https://fontawesome.com/v6.0/icons?c=users-people&s=solid and v5: https://fontawesome.com/v5.15/icons?d=gallery&p=1&c=users-people
