### ISSUE TITLE
Add message filter to fa-envelope

### ISSUE THREAD

**Issue by calidion** [FortAwesome/Font-Awesome#10788]
fa-message is current unavailable, where fa-envelope is exactly for the same meaning.
hope fa-message will be added as an alias to fa-envelope.

**Comment by tiesont** [comment]
You can do this yourself, too:
```
.fa-messsage:before {
  content: "\f0e0";
}
```
and
```
.fa-message-o:before {
  content: "\f003";
}
```
All the aliases do is add additional selectors to the original selector.

**Comment by tagliala** [comment]
I agree with @tiesont 

I could add a `message` filter, so envelope will show up in docs while searching for `message`.

Also, extra classes will impact css size

**Comment by calidion** [comment]
@tiesont 
thanks.

it would be very nice, @tagliala

**Comment by tagliala** [comment]
Done, it will be live when someone will rebuild the docs
