### ISSUE TITLE
Icon Customer and Others

### ISSUE THREAD

**Issue by gegonzalez1** [FortAwesome/Font-Awesome#10780]
I need the icon list : 
Customer, Crops, Warehouse, Harvest, Pallet, Box, Order Purchase, Budget, Payroll, Assets, Inventory, Encrypted, Survey, Data Entry, worked, Labor, Variety, State, Phase, Seed, Program, Issue, population, Rank, Measuring Unit, age, Weight, Soil, Data type, Color palette, Tractor, Spray boom, airplane, track down, Packing, Groups, Research, Fumigate, Apply, Farm, Material, Catalogue, SKU, Kit, ribbon, active ingredient, equipment, Dangerous, Class, Type, Method, brand, model, weather, Kpi, Sales, report, query, consumption, invoiced, port, cold room, holiday, Crew, Active, Inactive, workday, Rejection, Approve, Process, Volume, Indicator, Production, Estimated, variation, Exchange rate, Account, Close process, Open process, prices, Chain value, performance evaluations, employee, Supervisor, Manager, Monitoring, Instructor, Payroll, agreement, mechanical workshop, mechanical, workshop, Repair and Maintenance, Failures, list of materials, check, Sac's, normative.
Note: Please, this list is for an agricultural software
Regards !

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
