### ISSUE TITLE
Informatic security

### ISSUE THREAD

**Issue by DragonMX** [FortAwesome/Font-Awesome#10791]
I work as a graphic designer with Computer Security and I need related icons.

I've raised many and I've come up with a good idea. I can contribute, under your supervision, but if you can create them quickly that better.

: Barents to choose:

-Fingerprint
-Facial recognition
-Eye with retina
-Security code

I need "shields", "keys" (example: shield with user) with:
-people
-folders
-leaves
-books
-paper bin
-save
-magnifying glass (inspections)
-cpu
-cloud
-display
-TV
-phone
-tablet
-video camera
-Surveillance Camera
-mail
-HDD / SSD
-safe
-wall
-net
-thief
-usb
-disquet
-discharge
-load
-Web
-website
-http
-open / sawing
-blade open
-password
-purchases
-links
-world
-security code
-House, bake
-building
-contruction
-hand
-...

**Comment by tiesont** [comment]
I would suggest reading the [Contributing](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) guidelines - you need to structure icon requests a specific way. A lot of what you're asking for can be accomplished using [stacked icons](http://fontawesome.io/examples/#stacked).

That being said, I would doubt any new icons are being added to the 4.x branch, as they are actively working on the 5.0 version.

**Comment by DragonMX** [comment]
Excuse my bad English, maybe you will not explain me correctly. Here are
some examples.

I take as an example with special interest with the plugins that are being
used as "Font Icons".


​

2017-03-14 16:01 GMT-06:00 Tieson Trowbridge <notifications@github.com>:

**Comment by tiesont** [comment]
I don't know if you added some HTML to your comment that wasn't escaped, but no, I don't get what you're asking for. When you say this:

> I need "shields", "keys" (example: shield with user) with:

you're basically making an icon request (in this case, many requests). Icon requests must follow a specific format, as noted in Contributing. If you don't follow those guidelines, your issue is much more likely to be closed.

**Comment by DragonMX** [comment]
I get it, no problem. 

An image that was not added:
http://subefotos.com/ver/?c013150a7a81f062112bfed88c0b070ao.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
