### ISSUE TITLE
Text-overflow: ellipsis issue on IE9 + workaround

### ISSUE THREAD

**Issue by Ninir** [FortAwesome/Font-Awesome#1079]
Hi,

After using FontAwesome for a moment I discovered that using an icon followed by a text, the whole thing wrapped into a tag with an `ellipsis` behavior is causing an encoding issue. Here is the html used:

``` html
<div class="btn btn-primary btn-large" style="white-space: nowrap; text-overflow: ellipsis; overflow-hidden; max-width: 300px;">
    <i class="icon-download-alt"></i>
    ALongTextBeinEllipsed AndATextAfter
</div>
```

There is no issue on IE8 and IE10.
Here is the render on IE9 for this HTML, made on the FontAwesome showcase:

![capture decran 2013-05-15 a 10 16 18](https://f.cloud.github.com/assets/855022/505801/ffa5b36e-bd37-11e2-84c0-cdbcccb1e5fc.png)

@davegandy Do you have any hints to provide on this please?

**Comment by leechansook** [comment]
@myange Thanks for your Code :D

**Comment by leechansook** [comment]
@myange Thanks for your Code :D

**Comment by leechansook** [comment]
@myange Thanks for your Code :D

**Comment by Ninir** [comment]
Hey guys, never took the time to thank you all soooo.... thank you! :-)
