### ISSUE TITLE
Icon request: Merge Icon

### ISSUE THREAD

**Issue by RogerVaughn** [FortAwesome/Font-Awesome#10790]
Something like 

![](https://cdn4.iconfinder.com/data/icons/glyphlibrary-one/100/merge2-512.png)

![](https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/arrow_merge.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1089, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
