### ISSUE TITLE
Icon Request: fa- customization

### ISSUE THREAD

**Issue by Pankajkumarbehera** [FortAwesome/Font-Awesome#10796]
Hi Support,

Please create a new icon class for customization. So that it will be helpful to us.

Thanks & Regards
Pankaj
![customiazation](https://cloud.githubusercontent.com/assets/26458854/23993784/f5b6d960-0a67-11e7-8948-786249ac319c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #736 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
