### ISSUE TITLE
Category Request - Automotive Icons (Engine, Transmission, Brakes, etc)

### ISSUE THREAD

**Issue by scottrizz** [FortAwesome/Font-Awesome#10799]
I would like to see a category for automotive icons added.
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
