### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by mohanprajapati** [FortAwesome/Font-Awesome#10797]
PayG Icon for Australia Pay as you Go (Text).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
