### ISSUE TITLE
Icon Request: icon-dj

### ISSUE THREAD

**Issue by JuanObiJuan** [FortAwesome/Font-Awesome#1080]
Hi. First of all congrats!
I would like to have an icon with a dj.
It could represent a proper dj in some cases or it could represent the meaning of performance.

I imagine something like this http://darkhavenradio.com/wp-content/uploads/2013/01/DJ-Icon.jpg
or maybe only the vinyl rith the hand
like here http://clipartstockphoto.com/images/dj-icons.jpg

Thankyou folks!

**Comment by ncnlinh** [comment]
+1

**Comment by ncnlinh** [comment]
volume control icon is the most important one in this set

**Comment by neerajgdtpl** [comment]
Hi @davegandy,

I have a kind request with you for the following request of mine #5519

Could you please review the same and let me know if its possible?

Kind regards,
Neeraj

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-sound wave was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by sensibleworld** [comment]
We've added a bunch of new music icons, including these vinyl related ones: https://fontawesome.com/icons?d=gallery&q=vinyl

https://fontawesome.com/icons?d=gallery&s=solid&c=music
