### ISSUE TITLE
Icon request: icon-instagram

### ISSUE THREAD

**Issue by ganjelija** [FortAwesome/Font-Awesome#10814]
Icon request: icon-car

**Comment by PeterShaggyNoble** [comment]
Don't know which you're requesting here but [`fa-instagram`](http://fontawesome.io/icon/instagram/) and [`fa-car`](http://fontawesome.io/icon/car/) both exist already.

**Comment by ganjelija** [comment]
thanks

**Comment by ryankane** [comment]
@tagliala Eh... close?

**Comment by tagliala** [comment]
@ryankane thanks, closing here

**Comment by ifarshgar** [comment]
Instagram icon is not showing very well on a dark background. can you suggest a quick fix?

This is my code:
<span class="fa-layers fa-fw" style="background:#27292E">
	<i class="fas fa-square" style="color:white"></i>
	<i class="fab fa-instagram" style="color:#E24057"></i>
</span>

![capture](https://user-images.githubusercontent.com/13864337/36308493-33c4526e-1336-11e8-96c7-1520fba6e1ac.PNG)

**Comment by tagliala** [comment]
@ifarshgar sorry, can't see your code

Please check that you didn't add a white background to your icon

Example: https://jsfiddle.net/tagliala/vLae8ted/14/

**Comment by ifarshgar** [comment]
I edited the code again and removed the white layer but this time the Instagram icon is all dark! 

My code:
```
<span class="fa-layers fa-fw" style="background:#27292E">
	<!-- (I only removed this) <i class="fas fa-square" style="color:white"></i> -->
	<i class="fab fa-instagram" style="color:#E24057"></i>
</span>
```

Result snapshot:
![capture](https://user-images.githubusercontent.com/13864337/36343689-8998133a-1424-11e8-8b08-5aee5114c41c.PNG)



A picture of what I exactly want on a dark background specifically in the footer (something that I can't make it work): 
![capture2](https://user-images.githubusercontent.com/13864337/36343713-e2218e5a-1424-11e8-9ff7-9a08ef6363c6.PNG)

**Comment by tagliala** [comment]
@ifarshgar Sorry but I still didn't get what you are trying to achieve

All icons in the Font Awesome set are monochromatic

If you need a filled-in version of the instagram loco with a red border, you should go for a different solution (multicolor svg) or ugly css hacks, like this: https://jsfiddle.net/tagliala/vLae8ted/29/

Please note that I do not recommend this solution.

You may be interested in an alternative, like #9223 or a proper transformation with masking: https://jsfiddle.net/tagliala/vLae8ted/36/

**Comment by ifarshgar** [comment]
Thank you so much. Your css hack is good enough for me. 
I appreciate your time and attention. 
Cheers...
