### ISSUE TITLE
Missing Icon

### ISSUE THREAD

**Issue by wasim8989** [FortAwesome/Font-Awesome#10815]
Greeting of the day
I want This Icon in my Project but its not Available in Font-Awesome

With this Mail i have Attached Image of that Icon which I needed.Please Suggest me.

Thank You

![capture](https://cloud.githubusercontent.com/assets/23648677/24138273/9fe4818e-0e3d-11e7-93b8-75fa58128507.JPG)

**Comment by PeterShaggyNoble** [comment]
It's called [`fa-files-o`](http://fontawesome.io/icon/files-o/).
