### ISSUE TITLE
Icon Request: fa-tpms

### ISSUE THREAD

**Issue by ACImaging** [FortAwesome/Font-Awesome#10828]
Please look into including more icons related to the automotive industry. Specifically, one for Tire Pressure Monitoring System (TPMS).

This could be easily used by the automotive advertising, sales, and service industries.  I have included a graphic of what this icon looks like.
![tpms icon](https://cloud.githubusercontent.com/assets/26609628/24219238/7d6db14a-0f1c-11e7-9be8-8cb4172c528a.jpg)

**Comment by hosein** [comment]
+1

**Comment by hosein** [comment]
There is a $50 bounty on this issue:
https://www.bountysource.com/issues/43334724-icon-request-fa-tpms

**Comment by CodeFetch** [comment]
@hosein See the contributing guidelines: "At the moment we are not accepting pull requests containing icons".

**Comment by xmuskrat** [comment]
I think this is already available in latest set.

https://fontawesome.com/icons/tire-pressure-warning?style=solid

**Comment by tagliala** [comment]
@xmuskrat thanks for the heads-up!

Available in FA Pro 5.2.0 and newer
