### ISSUE TITLE
Icon request: facebook-rounded

### ISSUE THREAD

**Issue by marquispalmer** [FortAwesome/Font-Awesome#10829]
New here. How can I get this icon and add it to my social icons menu? 
I would love to add it to the menu. see attached screenshot.
Thanks anyone.

<img width="288" alt="screen shot 2017-03-22 at 10 41 11 pm" src="https://cloud.githubusercontent.com/assets/26609281/24221974/cf2d5d6c-0f50-11e7-8beb-7d1203d604e6.png">

**Comment by sensibleworld** [comment]
Hi there! What plugin is this you're referencing?
