### ISSUE TITLE
Font awesome Tree Icon not showing up

### ISSUE THREAD

**Issue by amitg1204** [FortAwesome/Font-Awesome#10830]
I have been using the CDN link mentioned in below for font-awesome icons

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.css

Till yesterday it seemed to be working fine until today it shows up no more. Kindly Please fix this issue if there is really a problem.

**Comment by tagliala** [comment]
Cannot confirm: https://jsfiddle.net/tagliala/6bw1z3vn/

Please also notice that we do not directly manage CDNs, so we cannot control assets on cloudflare if something is going wrong

Closing here
