### ISSUE TITLE
Icon request: ingoing and outgoing

### ISSUE THREAD

**Issue by vskwirblies** [FortAwesome/Font-Awesome#10832]
Hello!
I'm new to Font awesome. I would like to use it for an existing project. But there is one Button which I cannot find a decent font-awesome-icon for. It looks like this:
![buttonassign](https://cloud.githubusercontent.com/assets/26623941/24245100/ccee6e1c-0fc1-11e7-94ee-0d11a736c741.png)
I know this is two-colored, but I think using it as an icon with one color would be sufficent.
Could be usefull for synchronization, for example in email-clients or such.
Thanks!

**Comment by PeterShaggyNoble** [comment]
It's called `fa-exchange`: http://fontawesome.io/icon/exchange/
