### ISSUE TITLE
bs4alpah6 list-group et al fa-ul bug?

### ISSUE THREAD

**Issue by mcleangm** [FortAwesome/Font-Awesome#10843]
Here is a try editor list that shows bs4alpha6 list-group et al not working with fa-ul et al...
https://www.w3schools.com/code/tryit.asp?filename=FDYSXQZTGDCZ

Any way to get the icons and list items to work so long list items are indented together?

**Comment by tagliala** [comment]
Hi,

> bs4alpha6 list-group

I'm seeing 3.3.5 loaded in the html file:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
```

By the way, font awesome was [originally designed for Bootstrap](http://fontawesome.io/#why), is still Bootstrap compatible but it doesn't mean that everything will work fine without custom css rules.

In your use case, `fa-ul` does not play well with `list-group` and it seems legit to me.

According to what you are trying to achieve, if you don't want to use custom css rules, this could be a way to go:

```html
<ul class="list-group" style="width: 150px">
  <li class="list-group-item">
    <ul class="fa-ul">
  	  <li><i class="fa fa-li fa-pencil"></i> Applications and more stuff</li>
    </ul>
  </li>
  <li class="list-group-item">
    <ul class="fa-ul">
      <li><i class="fa fa-li fa-cog"></i> Settings</li>
    </ul>
  </li>
</ul>
```

Hope it helps

**Comment by PeterShaggyNoble** [comment]
There's probably not much point trying to debug something in a third party alpha release as a lot will change between now and the final release.

**Comment by mcleangm** [comment]
Hi Peter,

Really appreciate that you took time to look at my list-group/fa-ul case and reply so fast.

Your nested div workaround helps and seems to work on first try. Much appreciated thank you kindly as I am still learning...

Note I did learn that fontawesome was developed to work with bootstrap why is why when I discovered on w3schools fa-ul/fa-li working an earlier version of bootstrap I figured my question was legit.

Like to see a less nested solution as I see this causing issues for others. Should I post this kind of issue to the bootstrap4 alpha github or is it best left to your fontawesome dev team to directly raise the the issue as a (nice to do) with the bootstrap dev team?

Have a great day.

Regards, Gord

**Comment by tagliala** [comment]
> Should I post this kind of issue to the bootstrap4 alpha github or is it best left to your fontawesome dev team to directly raise the the issue as a (nice to do) with the bootstrap dev team?

IMHO this is not an issue.

I mean, `fa-ul` and `list-group` do use `<ul>` and `<li>` tags, but they serve different purposes.

IMHO the best thing to do is go for a custom css class, because otherwise we should also deal with [pagination](http://getbootstrap.com/components/#pagination), and all other bootstrap component using `<ul>` and `<li>` tags

**Comment by mcleangm** [comment]
Hi Peter,

I see your point that pagination is also affected…

Playing further fount it a challenge to make badges and fa-ul/fa-li work as well.. default behavior seemed to contain the width of the li to the size of text…

Here was my workaround… seems like fair bit of work when the default bs4alpha 6 and fa-ul should play nice together...

<div class="list-group-wrapper list-group-flush">
	<ul class="list-group display-3">
											
		<li class="list-group-item">
			<ul class="fa-ul d-flex w-100 flex-column">
				<li><i class="fa fa-li fa-ticket fa-fw"></i>Children 3 years old and under</li>
				<li><span class="badge badge-pill badge-primary pull-right">FREE</span></li>
			</ul>
		</li>
	</ul>
</div>

Have great Saturday Nite.

Regards, Gord

**Comment by tagliala** [comment]
@mcleangm I was thinking something about this:

https://jsfiddle.net/tagliala/hu6qksdb/3/

without the extra markup, but it depends on use case

**Comment by mcleangm** [comment]
HI Peter/Geremia,

Thanks for sharing the custom fiddle.

Not an expert here… but it seems you are doing a calculation to adjust for line height? Default line height if I recall for browsers use to be 14px and now is 16px…

If it is not too much trouble can you expand on the calc trick used for width and margin-left…

Here were a few links on the workarounds I googled…  I tried writing a custom class I called hanging indent but it did not work to indent the list-group/list-group-item or a-ul/fa-li as I thought on first attempt...
How to Create Hanging Indents in HTML and CSS (thesitewizard.com) <https://www.thesitewizard.com/css/hanging-indents.shtml>

My newbie thinking is may fontawesome need a new custom set of classes for bootstrap that now uses flexbox… fa-ul-flex/fa-li-flex… so that bs4 and fa can work with components such as list-group, paginagation, badges… again too new at this flexbox coding...

Regards, Gord
