### ISSUE TITLE
Icon Request: icon-circle-loop (circle recycle)

### ISSUE THREAD

**Issue by GNSubrahmanyam** [FortAwesome/Font-Awesome#10848]
Icon for play audio/video in a loop

Sample loop icon from [iconfinder](https://www.iconfinder.com/icons/234124/arrow_line_loop_icon)

![image](https://cloud.githubusercontent.com/assets/18217008/24341228/e28fc920-12d5-11e7-9464-f8097880d12e.png)

**Comment by PeterShaggyNoble** [comment]
Possible dupe of #33.

**Comment by tagliala** [comment]
[`fa-retweet`](http://fontawesome.io/icon/retweet/) should be good to represent a loop

**Comment by GNSubrahmanyam** [comment]
@tagliala In Future, If i will use the fa-retweet in the same application. Then both icons will end up with a mess.

**Comment by tagliala** [comment]
Available in 6.1 thanks to [UNOCHA](https://www.unocha.org/)

https://fontawesome.com/icons/arrows-spin?s=solid
