### ISSUE TITLE
About fa-handshake-o icon. 

### ISSUE THREAD

**Issue by mitumelu** [FortAwesome/Font-Awesome#10846]
Hello.
 fa-handshake-o icon is not display. url(http://fontawesome.io/icon/handshake-o/)
But other icon is display.
fa-wrench,fa-smile-o,fa-line-chart are NO Problem it's ok.

**Comment by mitumelu** [comment]
When using Version 4.7.0, the Problem was solved :D

**Comment by mitumelu** [comment]
Thanks for this. Very nice!

**Comment by tagliala** [comment]
👍  glad you solved

closing here

**Comment by murphyjohn** [comment]
I have the same issue, but using 4.7.0 which came in my wordpress theme (Cryptic). Any ideas anyone?

**Comment by ikunyemingor** [comment]
Contents of this link [https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css](url) downloaded and used locally seems to be working for me
