### ISSUE TITLE
Icon Request: Handicapped symbol

### ISSUE THREAD

**Issue by kencoxdesign** [FortAwesome/Font-Awesome#10850]
I'm surprised the set doesn't include the standard "person in wheelchair" icon. Seems like a useful symbol for any site with an accessibility page.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You have probably missed
* http://fontawesome.io/icon/wheelchair/
* http://fontawesome.io/icon/wheelchair-alt/
