### ISSUE TITLE
Please promote awesome password standards by creating fa-secure-passwd

### ISSUE THREAD

**Issue by mustmodify** [FortAwesome/Font-Awesome#10854]
(cross-posted from the [FAPro ticket](https://github.com/FortAwesome/Font-Awesome-Pro/issues/334).)

The developer community needs a push toward doing a better job with passwords.

We can't go more than a few months without hearing about a huge [data breach](https://www.troyhunt.com/observations-and-thoughts-on-the-linkedin-data-breach/) where unsalted password hashes are sold.

More troubling, I recently clicked "forgot password" on a website. The company sent my password to me via email. Plaintext. Thus, they are storing plaintext passwords in their database, begging to be hacked. I still don't know what to think about companies that won't accept special characters. For instance, my bank won't let me use my "tier 1" password. They say: "You can't use $ in a password." What are they doing to cause that constraint? Doesn't seem good.

So my suggestion / plea to @FortAwesome is to come up with a symbol that means "we promise not to store plaintext passwords. In fact we use one of the Fort-Awesome-password-committee-approved one-directional salted hash methods." People could use that icon as a symbol to be trusted where they collected passwords. Then I would know when I could trust a site with one of the passwords I use broadly.

Something like:

![image](https://cloud.githubusercontent.com/assets/32432/24373210/4297f6e2-12f6-11e7-81e4-e5b26c441128.png)

maybe a salt bottle with a padlock or ... you're designers, come up with something. :)

Even if you had some "false-positives"*, you would still be doing a great service to the dev community by promoting high standards and best practices. 

I suspect that, given your license, you would have to work some serious magic to get this to be at all viable. Still, it's a noble goal. Go forth and awesome, please.

* where false-positives is a euphemism for people using it even though they hadn't implemented those standards...

**Comment by tagliala** [comment]
Hi,

thanks for sharing your thoughts

All I can only assign @robmadole and @davegandy to this issue because there should be no password in the open source version of font awesome

**Comment by Willardgmoore** [comment]
@mustmodify I like the concept. I'm curious how it would be enforced and ensure consistency. I was in DC last month and overheard talk of creating regulation on things like this in the internet because of the lack of consistency in security. I agree people should know how and who to trust more easily.

**Comment by mustmodify** [comment]
@Willardgmoore I hope Washington stays out of it. Things change so fast in this industry we could end up being legally required to store things in a way we knew to be unsafe.

As for enforcement, I kind of mentioned that above -- I'm not sure it's completely viable, unless there was some kind of code review process in place. And even then, there's bait-and-switch. So largely the icon would more mean "I'm the developer and I'm aware that this standard is important." But some effort toward getting a commitment from developers would be appreciated... asking them to put their own reputation on the line that a site was secure.

**Comment by SausageParty69** [comment]
Thank me later

http://fontawesome.io/icon/lock/

**Comment by jamesjenner** [comment]
As I mentioned in the other post, I don't feel this is the right place to be designing a logo for a campaign to recognise safe storage of passwords. You need a campaign and you need buy-in by others in the industry. I admire what your trying to achieve, but it will mean naught without sponsorship by big players (e.g. google, firefox, apache, etc). Once a campaign has been launched and it gains even a little bit of momentum then I think it would be time to ask FontAwesome to add the logo.

**Comment by mustmodify** [comment]
@jamesjenner I appreciate your zest in making sure to reply on both tickets.

I see your point and I don't disagree that a push from every tech company united against password stupidity would be fabulous. I don't think that's the only option. I will simply disagree that this is a non-starter. I think it would take a bit of promotional text and a list of approved storage methods from a well-recognized team like FA and we could get started that way. Having a logo is a powerful start to a project. Having an organization like FA, which has a great deal of credibility in our industry, would be a great starting place. I can see Google et al considering joining the bandwagon once it gets started.

**Comment by kgcreative** [comment]
A team like FA ha their hands full creating the thousands of icons hey promised us for Fa5, I doubt managing and enforcing standards is something they want to add to their already busy plates

**Comment by robmadole** [comment]
Hey, all. We love the energy behind this and if it ever becomes something that we can get involved with and it makes sense for us we'd love to help. However, security best-practices are something that we follow; we don't create them :D. Our focus is on Font Awesome for now.

If some security folks decided to create something like @mustmodify describes we'd be happy to throw our name into the hat as implementers of the standard / best practices. If they need an icon I bet I could even talk @davegandy into making a special one-off one. But for now this doesn't make sense for us.

Thanks, @mustmodify, for the time you spent on this. The idea is great I just don't think we're the ones to spear-head it.

**Comment by mustmodify** [comment]
@robmadole thanks for your consideration.
