### ISSUE TITLE
Icon Request - Equalizer

### ISSUE THREAD

**Issue by Shyamalangan** [FortAwesome/Font-Awesome#10852]
Hi,

I'm writing to request for Equalizer icon.

- Simple equalizer 
- Equalizer with fader stubs

PS: The USER icon is there, but not as cool as the glyphicon. Can you give a chubby user?

Thanks,
Sri

**Comment by GNSubrahmanyam** [comment]
@Shyamalangan Could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment]
I think [fa-sliders](http://fontawesome.io/icon/sliders/) do the job
