### ISSUE TITLE
IMDb Icon

### ISSUE THREAD

**Issue by richkelly1381** [FortAwesome/Font-Awesome#10857]
Hi, I am having trouble getting the IMDb icon to work on my website. Is there an issue with this icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Nope, there should be no issues.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
