### ISSUE TITLE
Font-Awesome Kakaotalk please... 

### ISSUE THREAD

**Issue by Jerfri6** [FortAwesome/Font-Awesome#10856]
dave, please help me to make the font "**fa fa-kakaotalk**"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3688 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
