### ISSUE TITLE
Icon Request: fa fa-twitter

### ISSUE THREAD

**Issue by silverster21** [FortAwesome/Font-Awesome#10868]
add to wordpress menu color white

**Comment by PeterShaggyNoble** [comment]
[fa-twitter](http://fontawesome.io/icon/twitter/) and [fa-twitter-square](http://fontawesome.io/icon/twitter-square/) both exist already.

**Comment by GNSubrahmanyam** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate 
[http://fontawesome.io/icon/twitter-square/](http://fontawesome.io/icon/twitter-square/)
[http://fontawesome.io/icon/twitter/](http://fontawesome.io/icon/twitter/)

Please make sure you search before opening new requests

Thanks
