### ISSUE TITLE
Icon Request: fa-facebook-square

### ISSUE THREAD

**Issue by marquispalmer** [FortAwesome/Font-Awesome#10869]
Hi

I would love to have the facebook-square icon. At the moment i only have the basic "social icons" in my wp menu.

See site nav bar: dev.maartenvanderschaaf.nl

Thanks,
Marquis

**Comment by GNSubrahmanyam** [comment]
Hi, @marquispalmer 

Thanks for being part of the Font Awesome Community.

This request is a duplicate
http://fontawesome.io/icon/facebook-square/

Please make sure you search before opening new requests

Thanks,
