### ISSUE TITLE
Icon request: fa-users-o

### ISSUE THREAD

**Issue by AdrienTorris** [FortAwesome/Font-Awesome#10864]
I would like to know if it's possible to add to this package of icons the same icon like the [users icon](http://fontawesome.io/icon/users/), but not filled. I need it to display it in the main menu of a mobile application, use the empty icon for the menu item is not the one displayed and the filled icon when the menu item is displayed.

The idea is to have the same set for the users than [user](http://fontawesome.io/icon/user/) and [user-o](http://fontawesome.io/icon/user-o/), [star](http://fontawesome.io/icon/star/) and [star-o](http://fontawesome.io/icon/star-o/), ...

**Comment by igoekten** [comment]
👍

**Comment by azekt** [comment]
+1
