### ISSUE TITLE
Icon Request: Status

### ISSUE THREAD

**Issue by MsDacia** [FortAwesome/Font-Awesome#10866]
It would be cool to have different status icons for Draft, Approved, Accepted, Pending, etc

**Comment by GNSubrahmanyam** [comment]
@MsDacia Could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by GNSubrahmanyam** [comment]
duplicate of #8816 , #10583

**Comment by MsDacia** [comment]
Yes, sorry, I am not much of a designer, but I was looking at the example that you have for credit cards. You have the name: Visa, MasterCard, Discover, etc, so I am looking for something similar to that, but with: Draft, Pending, Approved, Canceled, Paid, Final, Past Due, etc. A use-case for this would be if I want to send a client a design, I can use the draft icon to indicate this is not the final version, and as we move through the process, the status icon can change to match.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

If I got this request, you need to overlay credit card icons with some status icon, so you could be interested in taking a look to #1181

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet:

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
