### ISSUE TITLE
Icon Request: fa-arduino

### ISSUE THREAD

**Issue by danilopinotti** [FortAwesome/Font-Awesome#10861]
It would be interesting if the Font Awesome had the Arduino icon ...

**Comment by danilopinotti** [comment]
[Arduino logo](http://www.arduino.org/images/arduino_official_Logo__.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2530 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
