### ISSUE TITLE
icon request: height  and icon request: weight

### ISSUE THREAD

**Issue by zmancrow** [FortAwesome/Font-Awesome#10871]
Hi. Was looking for these two this morning but didn't find anything that might work. Perhaps a ruler and a weigh scale would do it. 

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1096 and #2735 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
