### ISSUE TITLE
Icon Request: fa-cpu

### ISSUE THREAD

**Issue by webdes03** [FortAwesome/Font-Awesome#10873]
Computer CPU icon

**Comment by GNSubrahmanyam** [comment]
@webdes03  Could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by GNSubrahmanyam** [comment]
Hi,  @webdes03

Thanks for being part of the Font Awesome Community.

This request is a duplicate #1840, #8630, #7534
Please make sure you search before opening new requests

Thanks

**Comment by tagliala** [comment]
IMHO, the mirochip icon included in the set does not represent a CPU.

Problem is that old cpu requests were closed.

I'm going to reopen #8630, please +1 that request
