### ISSUE TITLE
Icon Request: fa-money-bag

### ISSUE THREAD

**Issue by DmStepanov** [FortAwesome/Font-Awesome#10870]
Hello there!
Please, give me a money bag!
Like this: https://goo.gl/YDEsPE
Thanks, Dmitry.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1414 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by DmStepanov** [comment]
Ok, thanks!
