### ISSUE TITLE
UC browser and other browser icons

### ISSUE THREAD

**Issue by Sedoworld** [FortAwesome/Font-Awesome#10887]
Hi font-awesome.. it's nice how all the major browsers have been represented in your list of icons but I'll like it if you could come up with an icon for uc browser and other browsers that are also becoming the number 1 choice for many users

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
