### ISSUE TITLE
Icons do not show up in IE (Specific version)

### ISSUE THREAD

**Issue by H3ll0W0rld** [FortAwesome/Font-Awesome#10888]
Hello, 

None of the icons show up in Internet Explorer. It's very specific version of it I guess because I tested on different version of IE and do work. 

**IE Version: 11.633.10586.0**

See attached image for confirmation. Keep up the good work guys and thanks for this amazing library.

Cheers,

![font-awesome-ie-bug](https://cloud.githubusercontent.com/assets/5383861/24654986/96a93fc6-1912-11e7-8fb4-c0e4dd37a730.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot confirm.

Please make sure you are running the latest IE11 version available

![image](https://cloud.githubusercontent.com/assets/556268/24655213/9f234de2-193d-11e7-8679-11b8c856ae57.png)

**Comment by H3ll0W0rld** [comment]
As I said it only happens in very specific version of the IE. Here is the confirmation. 

![font-awesome-ie-bug](https://cloud.githubusercontent.com/assets/5383861/24657410/7bffd1e4-191c-11e7-934a-60ee85780697.png)

**Comment by ashast1** [comment]
My Problem solved with adding that website to Trusted Site list in Internet Explorer Security Options

**Comment by TomThak** [comment]
How to notify user to change the settings of the page?
