### ISSUE TITLE
Icon request: fa-*-slash (whole new set)

### ISSUE THREAD

**Issue by malothnaresh** [FortAwesome/Font-Awesome#10885]
Hi,
This might not be interesting case : 
But, I found it as : 
If I have ng-repeat over fa-icons, and I would want some of them to be shown as disabled [Instead of hiding the icon completely or reducing the opacity].

In this case, if every icon has disabled state also [I mean cross line over the icon], would work.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This should be nice to have but it requires every single icon to be redesigned with a slash.

Please take a look at this comment: https://github.com/FortAwesome/Font-Awesome/issues/1181#issuecomment-80275327

Refers to: #1181 (you will find a solution there), #3691

Closing here and labeling as wontfix right now

**Comment by malothnaresh** [comment]
Thanks Tagliala.

Request #3691 is the one I was requesting for.

Though, I have created fa-disabled class in my project for my use-case with less opacity.
