### ISSUE TITLE
Cedi sign icon -  ¢

### ISSUE THREAD

**Issue by Sedoworld** [FortAwesome/Font-Awesome#10889]
Hi font-awesome, the cedi sign icon is not part of your list of icons.. please come up with a cedi sign (¢)  icon. Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7287, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
