### ISSUE TITLE
Icon Request: icon-merge

### ISSUE THREAD

**Issue by allenan** [FortAwesome/Font-Awesome#1089]
Looking for an icon the represents merging two or more records in a web application. My main use case is for merging contacts in a contact manager, but I could imagine other situations where a need for this icon could occur.

The 'merge' street sign might be a good inspiration:

![image](https://f.cloud.github.com/assets/792845/508707/75ec0f12-bd8f-11e2-881a-9aa54ed11133.png)

**Comment by neil-119** [comment]
+1

We have fa-code-fork but not fa-code-merge?

**Comment by bradjc** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by breynolds** [comment]
+1

**Comment by guseng** [comment]
+1

**Comment by tduchateau** [comment]
+1

**Comment by Thinkscape** [comment]
YES!

**Comment by terraelise** [comment]
+1

**Comment by leetncamp** [comment]
+1 for merge and split icons.

**Comment by michaellewiswilson** [comment]
+1

**Comment by cubesun** [comment]
+1

**Comment by br1ckb0t** [comment]
+1

**Comment by michaellewiswilson** [comment]
+1

**Comment by gdsjassal** [comment]
would love to have this icon

**Comment by baalthazaar1** [comment]
+1 for arrow set

**Comment by nurikabe** [comment]
+1

**Comment by frejnorling** [comment]
+1

**Comment by flound1129** [comment]
+1

**Comment by maartenmensink** [comment]
+1

**Comment by skywlkr** [comment]
+1

**Comment by maxmueller89** [comment]
+1

**Comment by nimrod-cohen** [comment]
+1

**Comment by rajush** [comment]
+1

**Comment by vperlerin** [comment]
+1

**Comment by axwax** [comment]
+1

**Comment by smallreflection** [comment]
+1

**Comment by jaybny** [comment]
+1

**Comment by romelusw** [comment]
+1

**Comment by zsolt-racz** [comment]
+1

**Comment by acewert** [comment]
+1

**Comment by estevens99** [comment]
+1 for sodman's example

**Comment by drewsmith** [comment]
+1 although I'm using fa-compress in lieu of

**Comment by RogerVaughn** [comment]
+1 for Sodman; user can easily rotate so I'd vote for pointing up by default, as not all languages read right-to-left but all read top down.

**Comment by alexandrule** [comment]
+1

**Comment by cyberoblivion** [comment]
+1

**Comment by gdemartini** [comment]
+1 for something where the two paths being merged seem a little more equal in size

**Comment by johanelm** [comment]
+1 
Two paths merging to the right into one would be awesome :)
Also an inverted one; a split would be perfect.

**Comment by RogerVaughn** [comment]
Right-left flip and invert are built into font-awesome, so we just need 1
icon.

That said, I agree they should ideally be 2 paths of equal weight.

What would make this super easy to integrate? I've never made a font before
- .AI illustrator vector? SVG?

**Comment by stuartsharpe11** [comment]
+1 for merge. Something that would indicate that two contacts within a data base are being merged would be ideal: 

See: https://github.com/FortAwesome/Font-Awesome/issues/1089#issuecomment-31167682

**Comment by hmdhasani** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/1089#issuecomment-52668291 is much better.
only programmers would realize code-merge.

**Comment by tagliala** [comment]
Hi, feel free to open a new request and clarify the use case

This icon uses the same glyph as octicons' merge that you can also see on GitHub

![image](https://user-images.githubusercontent.com/556268/101918284-7a39b680-3bc9-11eb-9cee-5939c96ff7f3.png)
