### ISSUE TITLE
License for individual SVGs

### ISSUE THREAD

**Issue by tech4him1** [FortAwesome/Font-Awesome#10899]
Are individual SVGs covered under the SIL OFL, MIT, or CC BY 3.0?

**Comment by tech4him1** [comment]
Is there anyone that I can email or otherwise contact directly on this?

**Comment by tagliala** [comment]
> Are individual SVGs covered under the SIL OFL, MIT, or CC BY 3.0?

There are no individual SVGs, you mean the individual pictograms in the .svg font file? 

The should be licensed under the SIL OFL 1.1

From: http://fontawesome.io/license/

> Applies to all desktop and webfont files in the following directory: font-awesome/fonts/.
> License: SIL OFL 1.1

Hope it helps

**Comment by tech4him1** [comment]
Thank you.
