### ISSUE TITLE
Icon Request: fa-mastodon

### ISSUE THREAD

**Issue by xuv** [FortAwesome/Font-Awesome#10897]
Since the [Mastodon](https://mastodon.social) [Fediverse](https://instances.mastodon.xyz) [is gaining traction](https://motherboard.vice.com/en_us/article/mastodon-is-like-twitter-without-nazis-so-why-are-we-not-using-it) [at the moment](http://mashable.com/2017/04/04/mastodon-twitter-social-network/#CpSSOtiQDiqZ), there will soon be a need to update all the social profiles with a new icon.

The [Mastodon logo](https://github.com/tootsuite/mastodon/blob/master/app/assets/images/logo.png)

![Mastodon logo](https://raw.githubusercontent.com/tootsuite/mastodon/master/app/assets/images/logo.png)

**Comment by chrisheninger** [comment]
Digging around for an SVG so I can add Mastodon to my Franz app (meetfranz!), this is the best I could find from a few minutes of searching: http://svgur.com/s/Jh

**Comment by chrisheninger** [comment]
GitHub won't let me upload an SVG, so here's the code for a cleaned up version of the above URL to match the PNG.

```
<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000" viewBox="0 0 1000 1000">
  <path d="M527.194 543.7a28.362 28.362 0 0 0-56.723 0 25.73 25.73 0 0 0 2.67 11.674 26.42 26.42 0 0 0 5.672 8.34 28.2 28.2 0 0 0 40.04 0 31.87 31.87 0 0 0 6.006-8.34 28.8 28.8 0 0 0 2.336-11.674m-48.382-113.413a28.308 28.308 0 1 0 40.04 40.027 37.2 37.2 0 0 0 4.67-5.67 28.092 28.092 0 0 0 3.67-14.343 27.29 27.29 0 0 0-8.34-20.012 28.24 28.24 0 0 0-5.006-4 26.958 26.958 0 0 0-15.015-4.336 27.31 27.31 0 0 0-20.02 8.34m20.02-101.735a28.476 28.476 0 1 0 20.02 8.34 27.31 27.31 0 0 0-20.02-8.34M231.9 573.717a28.18 28.18 0 1 0 8.342 20.012 27.308 27.308 0 0 0-8.342-20.014m-40.04-93.4a28.352 28.352 0 0 0 20.02 48.366 26.958 26.958 0 0 0 15.015-4.336 28.255 28.255 0 0 0 5.005-4 27.29 27.29 0 0 0 8.342-20.013 28.09 28.09 0 0 0-3.67-14.343 37.21 37.21 0 0 0-4.67-5.67 28.2 28.2 0 0 0-40.04 0m40.04-93.4a28.2 28.2 0 0 0-40.04 0 26.425 26.425 0 0 0-5.673 8.34 25.73 25.73 0 0 0-2.67 11.673 28.315 28.315 0 0 0 48.38 20.018 27.29 27.29 0 0 0 8.342-20.012 28.8 28.8 0 0 0-2.336-11.674 31.87 31.87 0 0 0-6.006-8.34m550.55 178.453a28.476 28.476 0 1 0 20.02 8.34 27.31 27.31 0 0 0-20.02-8.34m20.02-85.057a28.2 28.2 0 0 0-40.04 0 37.2 37.2 0 0 0-4.672 5.67 28.092 28.092 0 0 0-3.67 14.343 27.29 27.29 0 0 0 8.342 20.013 28.248 28.248 0 0 0 5.005 4 26.96 26.96 0 0 0 15.015 4.336 28.3 28.3 0 0 0 20.02-48.366m-46.046-85.057a28.8 28.8 0 0 0-2.336 11.673 28.362 28.362 0 0 0 56.723 0 25.73 25.73 0 0 0-2.668-11.674 26.427 26.427 0 0 0-5.672-8.34 28.2 28.2 0 0 0-40.04 0 31.86 31.86 0 0 0-6.007 8.343z" fill="#2b90d9"/>
  <path d="M853.52 146.764Q707.04 0 499.833 0 292.96 0 146.48 146.764 0 293.2 0 500q0 207.138 146.48 353.57T499.833 1000q207.207 0 353.687-146.43T1000 500q0-206.8-146.48-353.236zM213.547 708.806h-3.337q-43.043 0-73.407-30.02-30.03-30.354-30.03-73.382V395.93v-.666q1.335-41.027 30.03-69.713 30.364-30.35 73.407-30.35t73.073 30.354q29.363 29.02 30.364 70.38V615.41q2.336 55.037 46.713 93.4zM600.6 554.7q-1 41.36-30.364 70.38-30.03 30.353-73.073 30.354t-73.407-30.354q-28.7-28.686-30.03-69.713V345.23q0-43.03 30.03-73.382 30.364-30.02 73.407-30.02h150.15q-44.378 38.36-46.713 93.4zm286.954 50.7q0 43.03-30.03 73.382-30.364 30.02-73.407 30.02h-150.15q44.378-38.36 46.713-93.4v-219.47q1-41.362 30.364-70.38 30.03-30.355 73.073-30.355t73.407 30.354q28.7 28.687 30.03 69.714V605.4z" fill="#2b90d9"/>
</svg>
```

**Comment by xuv** [comment]
Thanks @chrisheninger. Looks like a redraw by someone but thanks :)

**Comment by TraumaD** [comment]
there is an svg version of the logo on the mastodon github here: https://github.com/tootsuite/mastodon/blob/master/app/assets/images/logo.svg

**Comment by xuv** [comment]
@TraumaD Yes. Hopefully updated soon with the most recent colors and shapes. https://github.com/tootsuite/mastodon/pull/1362

**Comment by nIQnutn** [comment]
+1

**Comment by dersch81** [comment]
+1

**Comment by TraumaD** [comment]
The svg (and png) of the logo on the projects official GitHub was recently updated to be better pixel fitted, optimized, and to make the two the same size shape and colour.

**Comment by stephenstewart-ca** [comment]
I ran your svg through affinity and donatello and hand edited the html and css:
[mastodon-icon-font.zip](https://github.com/FortAwesome/Font-Awesome/files/1055672/mastodon-icon-font.zip)

**Comment by ROYALBEFF** [comment]
+1

**Comment by Gargron** [comment]
Hello! Finally we have a new logo for Mastodon. I was hesitating to respond in this thread because I knew a new one was coming (I didn't like the old one), I just didn't know when. Now it's here. The SVG can be found here: <https://github.com/tootsuite/mastodon/blob/master/app/javascript/images/logo.svg>

**Comment by stephenstewart-ca** [comment]
I scaled your Simplify & Favicon SVG files to a nominal 1000 x 1000 px in Affinity Designer.
The EOF, SVG, TTF, & WOFF fonts were generated by Fontello; the OTF font by Font2Web.
The #3088d4 hex color value is embedded with a style tag in the html.
[new-mastodon-icon-font.zip](https://github.com/FortAwesome/Font-Awesome/files/1185459/new-mastodon-icon-font.zip)

**Comment by Gargron** [comment]
@stephenstewart-ca Fantastic, thank you!

Now how/when can this land in font-awesome?

**Comment by stephenstewart-ca** [comment]
There two ways: a short term fix and a long term solution.
The short term solution is to add fa-mastodon (\e8a1) and fa-mastodon-alt (\e8a2) 
to a custom font-awesome with all the other  icons (see: custom-font-awesome.zip).
[custom-font-awesome.zip](https://github.com/FortAwesome/Font-Awesome/files/1209175/custom-font-awesome.zip)
In the long term, submit mastodon.svg and mastodon-alt.svg (see: mastodon-svg4font.zip)
to the Font Awesome community (https://github.com/FortAwesome/Font-Awesome/issues).
See guidelines (https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md).
[mastodon-svg4font.zip](https://github.com/FortAwesome/Font-Awesome/files/1209219/mastodon-svg4font.zip)

**Comment by Gargron** [comment]
From reading the contribution document, seems like this issue already fulfills all points from "Requesting new icons" - so a matter of waiting now?

**Comment by stephenstewart-ca** [comment]
Hi @tagliala 
This file mastodon-svg4font.zip contains mastodon.svg and mastodon-alt.svg for use by the
mastodon project, GNU Social-compatible microblogging server hosted here on GiHub:
https://github.com/tootsuite/mastodon
Can you help us add these to icons to Font Awesome?
[mastodon-svg4font.zip](https://github.com/FortAwesome/Font-Awesome/files/1209498/mastodon-svg4font.zip)

**Comment by iamcryptoki** [comment]
+1 Definitely needed!

**Comment by DeadSuperHero** [comment]
Any word on this? Would love to see support for the network in this icon set.

**Comment by cerisara** [comment]
Please add the Mastodon icon to font-awsome !

**Comment by jaketothepast** [comment]
+1 would like this icon pls

**Comment by remram44** [comment]
There is a lot of interest in this. I think they get it. Please use the 👍 button up top to vote this issue up, and *do not reply "+1"* as that will just alienate maintainers and *spam all of us* who subscribe to this issue. You are not helping.

**Comment by DansLeRuSH** [comment]
+1

**Comment by Sciss** [comment]
Hey; what's the status? It would be great if this was added!

**Comment by thomasbnt** [comment]
Yeah, please +1 .

**Comment by Drulac** [comment]
Please add it :-) !

**Comment by remram44** [comment]
You can use the SVG above in the interim; that's what I did. I agree that this is a useful icon, and since we have the glyph I'm not sure what's the holdup (or timetable).

**Comment by KindlyFire** [comment]
+1 👍

**Comment by kasramp** [comment]
+1

**Comment by jelv** [comment]
138 thumbs up emoji. Please add it :) Hope this request gets picket up before it's 1 year anniversary coming april.

**Comment by byronalley** [comment]
+1 👍

**Comment by Clarkinia** [comment]
+1

**Comment by Gargron** [comment]
This is the second most upvoted issue on this repository. What is holding it back for over 10 months?

**Comment by xuv** [comment]
@Gargron I've started tackling this issue. But it would be my first PR to this project. I think the main problem is that there hasn't been a PR from a community member in years (for adding icons that is, there has been PR for other issues). The code base is quite complicated to understand. There is multiple versions of the font in it and I'm still not sure if I added the icons to the right font file. Also, I still haven't figured out the full tool stack to get everything set up. Hoping to make more progress soon.

**Comment by Yeru-314** [comment]
+1

**Comment by xuv** [comment]
@Gargron As expected, the PR #12238 has been closed and not merged. The reason is they don't accept PR with icons at the moment. The last icon commit was [Oct 22, 2016](3f5146adb324b8d7c3013e4f180e6d5c5446dfa5). 

If people really want to grab temporary FontAwesome files with the Mastodon icons in it, they are welcome to snag it from my fork https://github.com/xuv/Font-Awesome until a more sustainable solution is found.

**Comment by tyrosinase** [comment]
I'm not above abusing other people's trademarks (ostensibly as temporary placeholders): is it possible to convince FA to display RTL so I could mirror the DeskPro icon as a workaround?

**Comment by trwnh** [comment]
@tyrosinase you can already mirror icons. either apply `data-fa-transform="flip-h"` in FA5, or use CSS3 transforms like `transform: scaleX(-1)`. Or you can use xuv's fork of FA4 in the comment immediately above yours.

**Comment by Sciss** [comment]
You can use https://github.com/ForkAwesome/Fork-Awesome/ - it includes Mastodon, Diaspora etc.

**Comment by kaushalmodi** [comment]
Thank you @stephenstewart-ca! Using your svg icons, I devised a [hack][1] to use those (for the lack of Fontawesome support) for Mastodon icon on my Hugo [site][2] (site footer).

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/commit/c491e6bfc257b1c8c58b39878b9117d1c086c31b
[2]: https://scripter.co

**Comment by stephenstewart-ca** [comment]
An SVG for fonts, including icon fonts, must be a monochrome single layer, by default black, so the new multicolour multilayer SVG submitted to Font-Awesome by Mastodon doesn’t work.

A better choice may be the Material Design Icons font maintained by Austin Andrews which includes all of Google’s Material icons as well as a large number of icons submitted by other contributors:
https://materialdesignicons.com/

The easiest way to use the Material Design Icons font is from a CDN:
https://cdnjs.com/libraries/MaterialDesign-Webfont

The Material Design Icons font is on GitHub:
https://github.com/Templarian/MaterialDesign

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mastodon

**Comment by realityfabric** [comment]
When I download the SVG it appears to be entirely transparent, and when I link to the icon with 
``` html
<i class="fab fa-mastodon"></i>
```
 the icon does not show up.

**Comment by remram44** [comment]
The SVG is NOT entirely transparent. If you want to use the SVG directly, then you should use an `<img>` tag.

**Comment by realityfabric** [comment]
Ah, you're right. My image viewer showed nothing when I opened the file, but opening the file with Firefox does show it. Not sure why Ubuntu would just... not show it.

**Comment by realityfabric** [comment]
It still doesn't show up when you use that HTML code, though, which was the reason I downloaded the SVG in the first place.

**Comment by robmadole** [comment]
@realityfabric can you open a new issue if you are having trouble?
