### ISSUE TITLE
Icon Request: fa-sprout

### ISSUE THREAD

**Issue by nstanard** [FortAwesome/Font-Awesome#10904]
Right now I'm using fa-leaf but it would be more appropriate if I could use a seed/sprout instead.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide examples (and split the request, if these icons are not strictly related)? 

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by nstanard** [comment]
Hey @tagliala, I am imagining using the seed icon to indicate something has been initiated. Then I want to use a seed sprouting into a leaf to indicate that same process has gone to the next phase and indicate progress is being made. I would then use the existing fa-leaf to indicate that something has come to completion or fruition. I thought of these as a set because of the way I imagine using them.

**Comment by nstanard** [comment]
![image](https://cloud.githubusercontent.com/assets/4204806/24800527/12498262-1b66-11e7-82ad-b75982bc6ed6.png)

Type of icons in the same style as the existing fa-leaf.

BTW. Font-awesome rocks! ^^
