### ISSUE TITLE
Icon request: icon-sc-sub-initiatives

### ISSUE THREAD

**Issue by SC-Robert** [FortAwesome/Font-Awesome#10902]
Hello team Awesomeness

The company that I work for, Scientrix, requires some font-icons for the development of their program platform. It has been running for over ten years with the development team in Argentina. The team has requested that any icons that we use in the program (it is a web-based program) be a font for re-scaling similar to which you supply.

Could you please assist us in creating two icons (a separate issue will be made for the other icon) to be used in the platform as per the development teams request. These icons will also be used in a section of our website.

![sc-sub-initiatives](https://cloud.githubusercontent.com/assets/26964697/24753502/adb6d950-1ad2-11e7-900a-843c3df52317.jpg)

If you want we have designed these in a vector format, you can e-mail me for the files, I will just need to know what format you would like them in.

Thanks for all your help Awesomeness!

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/arrow-down-wide-short?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
> Something like https://fontawesome.com/icons/arrow-down-wide-short?

Pretty confident that `arrow-down-wide-short` was already present at the moment of this request

I'm going to close here, feel free to open a new request if this icon is still needed. Please also provide a use case and clarify why the existing icon cannot be used
