### ISSUE TITLE
Site not reachable

### ISSUE THREAD

**Issue by meetwithchuks** [FortAwesome/Font-Awesome#10900]
http://fontawesome.io/icons/ not reachable for days now.

**Comment by tagliala** [comment]
Hi,

I'm not having issues. Where are you from? Which provider?

**Comment by vivaciouschuks** [comment]
Am from Nigeria. All other pages loads perfectly except for http://fontawesome.io/icons/

**Comment by PeterShaggyNoble** [comment]
When you say that page isn't reachable / doesn't load, what do you mean? Are you getting a 404, network error, blank page or something else?

Have a look in your browser's console, it may well shed some light on the problem.

**Comment by tagliala** [comment]
It could be possible that the content is blocket at provider level?

Also: https://twitter.com/fontawesome/status/850006162246430721

**Comment by vivaciouschuks** [comment]
![fontawesome icon page not reachable](https://cloud.githubusercontent.com/assets/4760135/24778918/184e02a0-1b25-11e7-838b-b510f39c663b.PNG)

This (http://fontawesome.io/icons/)doesn't load on browser 

![image](https://cloud.githubusercontent.com/assets/4760135/24778903/007b27e8-1b25-11e7-98de-69b763ebe294.png)
but every other page does.

But then i tried opening it as well i.e http://fontawesome.io/icons/ on the mobile phone and it does load properly.

**Comment by wdda** [comment]
Hello! 
That's another problem: http://fontawesome.io/icons//
Maybe It is also not good.

**Comment by PeterShaggyNoble** [comment]
That's not the same issue, @wdda. The URL you posted is not valid; you have an extra `/` on the end of it.

@vivaciouschuks, when you load the page on your phone, are you using the same network connection?

**Comment by vivaciouschuks** [comment]
@PeterShaggyNoble same network connection.
