### ISSUE TITLE
Icon request: flag-triangle

### ISSUE THREAD

**Issue by nclm** [FortAwesome/Font-Awesome#10911]
Hi!

This is a request for a triangle flag icon, which would supplements the already existing rectangle-with-wind one. The use for it would be to “flag” an item in an interface, or to display next to “flagged” item. Think Minesweeper flag. The rectangle one don’t convey this meaning and seems to be mainly referring to country’s flags.

Thank you.

**Comment by tagliala** [comment]
cold you please provide an example?

**Comment by nclm** [comment]
Sure:
* In social software Mastodon, [an icon is needed](https://github.com/tootsuite/mastodon/issues/1249) for a button to add a warning to a content.
* In any app, you could need an icon for an action starting by « Flag as… ». The rectangle flag could work, but the triangle one seems to work better as a signifier of being marked for what it is. The triangle put the emphasis on the item it’s applied on, while the rectangle seem to be a symbol for itself, possibly meaning Language or Country or Internationalisation.
* As an icon added on a map, a triangle flag would mean something different than a rectangle one. “I’ve been there”, “Here is burried the treasure”, anything that wants to mark the place and not the flag as important.
* A “Report” feature on social or comment software may benefit to this kind of flag too.
* A golf app would need a triangle flat. A minesweeper game clone would need it too. (Those are not serious examples)

**Comment by tagliala** [comment]
Sorry, I mean a single color example of the icon you are requesting

**Comment by PeterShaggyNoble** [comment]
@tagliala, it sounds like [this](https://icons8.com/icons/592/flag-filled) is what @nclm is looking for.

**Comment by nclm** [comment]
Yes, exactly, thanks! I was going to draw one, but as an example, this is close enough.

**Comment by ryankane** [comment]
High-resolution image.

![flag](https://cloud.githubusercontent.com/assets/1094151/24872805/aa51157e-1dec-11e7-8ed6-7b647f81b4fc.png)

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="34.7222in" height="34.7222in"
     viewBox="0 0 2500 2500">
  <path id="flag" fill="#000000" stroke="none"
        d="M 744.51,1573.31
           C 741.05,1578.67 741.67,2361.11 741.67,2361.11
             741.64,2378.61 733.33,2459.34 652.29,2458.33
             571.26,2457.32 558.38,2393.11 558.33,2361.11
             558.33,2361.11 558.33,122.22 558.33,122.22
             558.33,122.22 567.42,36.62 650.00,35.35
             732.58,34.09 741.67,121.46 741.67,121.46
             741.67,121.46 741.67,180.21 741.67,180.21
             741.67,180.21 2265.45,876.39 2265.45,876.39
             2265.45,876.39 748.74,1566.74 744.51,1573.31 Z" />
</svg>
```

**Comment by tagliala** [comment]
thanks

**Comment by sensibleworld** [comment]
Thanks for the request! This icon now exists. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=penant&s=solid

<img width="1005" alt="Screen Shot 2021-05-27 at 1 53 19 PM" src="https://user-images.githubusercontent.com/529604/119873787-e5b2de80-bef2-11eb-9d37-462d71f19194.png">
