### ISSUE TITLE
Conflicting with Wine/PlayOnLinux

### ISSUE THREAD

**Issue by fastenedrex** [FortAwesome/Font-Awesome#10915]
Running Ubuntu 16.04LTS and i3, I'm able to have everything working until I install Wine with PlayOnLinux. Then the icons act like they're not even installed. A few icons still work, but most are the cryptic symbols that are shown before installing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

i3 related issues: #10102, please post there

Closing here
