### ISSUE TITLE
Icon Request: fa-istagram

### ISSUE THREAD

**Issue by Renz84** [FortAwesome/Font-Awesome#10916]
![images](https://cloud.githubusercontent.com/assets/27204427/24857355/4474f850-1de8-11e7-8dc5-fdc4a1f914ff.png)

**Comment by Renz84** [comment]
istagram

**Comment by ryankane** [comment]
Pretty sure it's Instagram (with an 'n')

There is already a [fa-instagram](http://fontawesome.io/icon/instagram/), you will need to put in a support ticket.

**Comment by Renz84** [comment]
sorry for my big error.
thank you

**Comment by tagliala** [comment]
Closing here
