### ISSUE TITLE
Icon Request: fa-cartrdge

### ISSUE THREAD

**Issue by Dawnblairr** [FortAwesome/Font-Awesome#10910]
[Cartrdge](https://cartrdge.com/) is a relatively new community that connects game developers and artists and allows them to share their work. I'd love to see their logo added! I currently substitute fa-gamepad for my cartrdge social link on my porfolio site, but it would be great to have the actual logo.

![image](https://cloud.githubusercontent.com/assets/857345/24823642/e9286f10-1bce-11e7-82c3-bacc6e03db34.png)

**Comment by aethior** [comment]
Cartrdge was closed in 2018. ([more info](https://twitter.com/cartrdge/status/1022132070162878464))

Regards.

cc/ @tagliala
