### ISSUE TITLE
Icon Request: fa-carbon-footprint

### ISSUE THREAD

**Issue by granlund-alk** [FortAwesome/Font-Awesome#10914]
icon representing carbon dioxide released. Usually marked as footprint

**Comment by PeterShaggyNoble** [comment]
Possible dupe of #2140.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single-color, 16px icon size suitable example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by granlund-alk** [comment]
#2140
