### ISSUE TITLE
Icon Request: fa-rugby-ball

### ISSUE THREAD

**Issue by crojasf** [FortAwesome/Font-Awesome#10913]
Hello, Please I would like sports icons, especially the Rugby ball.
Thanks

**Comment by lickmydesign** [comment]
+1

**Comment by dwhaas82** [comment]
+1

**Comment by negoxp** [comment]
+1

**Comment by negoxp** [comment]
I am using the lemon! LOL

**Comment by Fatbat** [comment]
+1 for rugby represented in the sports category.

**Comment by mshovelt** [comment]
+1

**Comment by ybonillo** [comment]
+1

**Comment by comboostion** [comment]
+1

**Comment by bitedgecom** [comment]
We need a rugby ball icon. We could also use the upright (rugby goal posts). I only pay for font awesome pro for the sport icons so its very disappointing you are missing an icon for one of the top 5 sports in the world!

**Comment by Fatbat** [comment]
I see rugby ball has been added, but a modern rugby ball does not typically have laces and is more oval shaped the current icon. They are made up of 4 quarters invisibly stitched. A much more accurate image has been shared in another post here on this subject.

![image](https://user-images.githubusercontent.com/650859/119690618-21de3480-be4a-11eb-9b5f-e56dc1000406.png)

**Comment by ghost** [comment]
> I see rugby ball has been added

Where do you see that? In FA 5 or in 6 beta?

Oh I see what they are calling a Rugby ball in V 6

https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=rugby&s=solid

That's rubbish, it looks like an American Football or maybe a Rugby ball from 80 years ago...

**Comment by aethior** [comment]
Hi @crojasf,

This icon has been added in v6.0.0-BETA1
Check https://fontawesome.com/icons/rugby-ball

Regards.

cc/ @tagliala

**Comment by ghost** [comment]
> Hi @crojasf,
> 
> This icon has been added in v6.0.0-BETA1 Check https://fontawesome.com/icons/rugby-ball
> 
> Regards.
> 
> cc/ @tagliala

Unfortunately it does not represent a rugby ball...

**Comment by tagliala** [comment]
@bitedgecom is the example in this comment https://github.com/FortAwesome/Font-Awesome/issues/10913#issuecomment-848887069 a better suit?

**Comment by ghost** [comment]
Yes it is :) you can see it being used here FWIW https://bitodds.com/

**Comment by OscarBeiro** [comment]
+4

**Comment by sensibleworld** [comment]
This has been enhanced in 6.4.0: https://fontawesome.com/icons/rugby-ball?f=classic&s=light
