### ISSUE TITLE
Icon request: fa-key-ctrl, fa-key-enter, etc... (key illustrations)

### ISSUE THREAD

**Issue by Alberthaff** [FortAwesome/Font-Awesome#10925]
Icons like `fa-key-ctrl`, `fa-key-enter` or `fa-key-cmd` would be great for illustrating hotkeys to the user. 

Use case:
![untitled-2 fw](https://cloud.githubusercontent.com/assets/3864165/24917087/57ce9a06-1edc-11e7-84e3-171a377ce90f.png)

This will of cause add a lot of extra icons, since we will need icons representing each key, but it would make it a lot easier to instruct the user.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Ref: #10867

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
