### ISSUE TITLE
Icon request: haluansen

### ISSUE THREAD

**Issue by Markosaar** [FortAwesome/Font-Awesome#10928]
Brand icon for use in connection with haluansen.com

![placeholder](https://cloud.githubusercontent.com/assets/27331701/24943053/57cf13ba-1f5d-11e7-8e48-38df8e597398.png)

**Comment by james-lane** [comment]
You can get your logo added to font awesome pro and free here as part of backerkit:
https://font-awesome-5.backerkit.com/hosted_preorders

**Comment by aethior** [comment]
The domain ([link](https://www.haluansen.com/en/)) is currently down and the social networks are inactive since 2020 ([twitter](https://twitter.com/haluansencom) and [instagram](https://www.instagram.com/haluansencom/)).

cc/ @tagliala
