### ISSUE TITLE
Icon Request: fa-towel

### ISSUE THREAD

**Issue by nicrose91** [FortAwesome/Font-Awesome#10922]
icon representing towels and linens for a hotel site

**Comment by ScottAgirs** [comment]
Is this coming anytime soon? ### +

**Comment by CLSixteen** [comment]
Need this!

**Comment by bc-devle** [comment]
fa-blanket should be tagged in "towel" and "bath"

**Comment by tagliala** [comment]
@bc-devle thanks for the suggestion

Closing here because this available in FA Pro starting from version 5.0.9, ref #12383

https://fontawesome.com/icons/blanket?s=solid&f=classic

@talbs any chance to add a couple of search terms?
