### ISSUE TITLE
Icon Request: fa-wikia

### ISSUE THREAD

**Issue by barbarafux** [FortAwesome/Font-Awesome#10921]
Thanks for Font-Awesome! I am working on a project where I would need link to a Wikia wiki therefore I kindly ask for an icon for it.

Here's a link of the logo from the wikia page: http://www.wikia.com/File:Wikia_Main_Logo-Black.png
Since this is very complex here is the smaller form on their G+ Page: https://lh3.googleusercontent.com/-p0G0VNOUVw0/AAAAAAAAAAI/AAAAAAAACe8/N1d6KxUm-ig/s60-p-rw-no/photo.jpg

thanks

**Comment by aethior** [comment]
Wikia is now Fandom.

>Fandom (also known as Wikia before October 2016) is a wiki hosting service which hosts wikis mainly on entertainment (i.e. video games, movies, and entertainers). (...) Fandom wikis are hosted under the domain fandom.com, but some, especially those that focus on subjects other than media franchises, were hosted under wikia.org until November 2021. ([more info](https://en.wikipedia.org/wiki/Fandom_(website)))

cc/ @tagliala

**Comment by tagliala** [comment]
Let's use #12585
