### ISSUE TITLE
Icon Request: star-trek

### ISSUE THREAD

**Issue by Makreig** [FortAwesome/Font-Awesome#10929]
I think most people should get what i'm after here, we got a couple from star wars.
![f23f4e6e825a7c0d5c746ef4efaf13ed](https://cloud.githubusercontent.com/assets/6011781/24963689/31dcbd08-1f97-11e7-9f08-1d67751bd228.jpg)
![11a4d55fc1658d696a33d6c785abcc56_trek-arrowheads-font-star-trek-symbol-clipart_813-393](https://cloud.githubusercontent.com/assets/6011781/24963700/37e7c3dc-1f97-11e7-9d7e-dd6abc7d83e5.jpeg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet:
> Please do not request comprehensive sets of icons related to a very specific field.

**Comment by MTyson** [comment]
But... there are Star Wars icons... what gives?
