### ISSUE TITLE
polish letters

### ISSUE THREAD

**Issue by fisher006** [FortAwesome/Font-Awesome#10931]
Hi, it is possible add polish letters to awresome fonts like ę, ż ź etc?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please use standard unicode points.

Eg: https://jsfiddle.net/tagliala/s3msxtbe/14/

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet:

> Please do not request comprehensive sets of icons related to a very specific field.
