### ISSUE TITLE
fa-mobile too small, fa-envelope too big

### ISSUE THREAD

**Issue by chrispink** [FortAwesome/Font-Awesome#10934]
Especially when viewed together, this screenshot is 16px
and yes, I can cheat it in the CSS, but it would be good if it got addressed at source.

Also applies to fa-envelope-o and fa-tablet

![screen shot 2017-04-13 at 09 21 52](https://cloud.githubusercontent.com/assets/9802285/24996405/a7b65c08-202a-11e7-8c72-09a243eca57f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This should be fixed in FA 5, all icons will be redesigned from scratch.

fa-mobile issue: #928
