### ISSUE TITLE
Icon Request: fa-star-gate

### ISSUE THREAD

**Issue by Makreig** [FortAwesome/Font-Awesome#10930]
pretty self explanatory, i loved this show and the co-ordinates are meant to be words
![1acc78816d154e7921a10e3b6e8541c0](https://cloud.githubusercontent.com/assets/6011781/24963751/65e758d8-1f97-11e7-8cb4-aca7a7afcc38.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet:

> Please do not request comprehensive sets of icons related to a very specific field.
