### ISSUE TITLE
Icon Request: icon-file-pile

### ISSUE THREAD

**Issue by MaximeDawn** [FortAwesome/Font-Awesome#10937]
Hi,

It would be super nice to have **fa-file-pile-1** & **fa-file-pile-2** with the following style :

![image](https://cloud.githubusercontent.com/assets/20993007/25000271/f74da382-2040-11e7-8021-e788e550cab2.png)

To be able to do things like this in  a dashboard :

![image](https://cloud.githubusercontent.com/assets/20993007/25000368/55de73ae-2041-11e7-9986-7e591e16ec19.png)

PS :  Font Awesome is Awesome 😄 🍿

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that your icons look better, but it is a design choice rather than a request for a new icon

For your use case, you could use: http://fontawesome.io/icon/file-o/ and http://fontawesome.io/icon/files-o/

**Comment by MaximeDawn** [comment]
@tagliala OH ! Thanks for the fa-fileS-o, I didn't knew about this one. So i change my request, can you add the keyword "Pile" to files-o. I think many people like me search for "Pile" and don't find this icon :)
