### ISSUE TITLE
Icon request: periscope

### ISSUE THREAD

**Issue by arvinpoole** [FortAwesome/Font-Awesome#10943]
This is a special request. Surprised it is not already included in the social media pack. 

Thanks for your attention. 

Arvin

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6463 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
