### ISSUE TITLE
Icon request: icon-realm

### ISSUE THREAD

**Issue by mgohin** [FortAwesome/Font-Awesome#10940]
Hi there,

would be nice to have the https://realm.io/ icon to integrate in our apps the icon, better than text is our most cases.

![realm_logo](https://cloud.githubusercontent.com/assets/3430304/25016051/c5fbf502-207e-11e7-83bf-ea0726364e5e.png)

**Comment by PeterShaggyNoble** [comment]
If you convert that to a single colour icon, it's just going to be a solid circle.

**Comment by mgohin** [comment]
You are right, I updated it with the mono-color logo from their landing page. Not smooth because of the small size and I'm not a graphist ;)
