### ISSUE TITLE
Icon Request: fa-shred

### ISSUE THREAD

**Issue by gccumber** [FortAwesome/Font-Awesome#10948]
Currently FA offers a trash can and a recycle icon but nothing to represent shred. I made this for a mockup a long time ago (just thought I'd share)

<img width="37" alt="shred" src="https://cloud.githubusercontent.com/assets/6003048/25048475/47521e6e-2102-11e7-87fe-d51d1c1a6fc7.png">

**Comment by JordanReiter** [comment]
👍

**Comment by ryankane** [comment]
Personally, I like simple but bold icons like so:

![shred](https://cloud.githubusercontent.com/assets/1094151/25051471/d5b820f0-211a-11e7-937f-6a8c6e947a2e.png)

**Source:** [Shredder](https://thenounproject.com/term/shred/445532/) by Scott Lewis, US

**Licence:** [Creative Commons v3.0](https://creativecommons.org/licenses/by/3.0/us/) &mdash;  Copy and redistribute the material in any medium or format with appropriate attribution to the author.

## Source

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    xml:space="preserve"
    viewBox="0 0 32 32"
    enable-background="new 0 0 32 32"
    fill="#000000"
    x="0px" y="0px">
  <g>
    <path d="M27,10V4c0-1.105-0.895-2-2-2H7C5.895,2,5,2.895,5,4v6H2v12h3v6h3v-8h16v8h3v-6h3V10H27z M24,15H8V5h16V15z"/>
    <rect x="11" y="11" width="10" height="2"/>
    <rect x="11" y="7" width="10" height="2"/>
    <rect x="11" y="22" width="2" height="8"/>
    <rect x="15" y="22" width="2" height="6"/>
    <rect x="19" y="22" width="2" height="8"/>
  </g>
</svg>
```

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/shredder?style=solid
