### ISSUE TITLE
Icon Request: fa-lotion

### ISSUE THREAD

**Issue by jiwon1105** [FortAwesome/Font-Awesome#10953]
Lotion

http://www.freepik.com/free-icon/lotion_809538.htm

![lotion](https://cloud.githubusercontent.com/assets/27586528/25067300/db2f3914-2279-11e7-96ed-6fe02fbb9fcd.png)

**Comment by tahsinamio** [comment]
+1 this would come in handy

**Comment by aethior** [comment]
Hi @jiwon1105,

This icon was added in v5.13.0.
Check https://fontawesome.com/icons/pump-soap

Regards.

cc/ @tagliala
