### ISSUE TITLE
issue on installing from npm registery

### ISSUE THREAD

**Issue by mehranhadidi** [FortAwesome/Font-Awesome#10957]
i followed the docs on (https://www.npmjs.com/package/font-awesome).

i also added
![image](https://cloud.githubusercontent.com/assets/897774/25082143/f69f6a80-2363-11e7-9aa7-22a3d1e92506.png)

but when i trying to to run npm install i get an error

![image](https://cloud.githubusercontent.com/assets/897774/25082163/11a6a226-2364-11e7-9ebe-283701478f35.png)

what the hell is going on!?

**Comment by tagliala** [comment]
@juliankrispel could you please take a look here?

**Comment by SivanMehta** [comment]
It's under npm as just `font-awesome`:

```
$ npm install font-awesome
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.10.1
npm info attempt registry request try #1 at 8:04:03 PM
npm http request GET https://registry.npmjs.org/font-awesome
npm http 304 https://registry.npmjs.org/font-awesome
npm info addNameTag [ 'font-awesome', 'latest' ]
npm info lifecycle font-awesome@4.7.0~preinstall: font-awesome@4.7.0
npm info linkStuff font-awesome@4.7.0
npm info lifecycle font-awesome@4.7.0~install: font-awesome@4.7.0
npm info lifecycle font-awesome@4.7.0~postinstall: font-awesome@4.7.0
/Users/admin/Desktop
└── font-awesome@4.7.0

npm WARN enoent ENOENT: no such file or directory, open '/Users/admin/Desktop/package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
npm info ok
```

**Comment by juliankrispel** [comment]
@mehranhadidi those are the docs for installing via `component.json` not `package.json` - you can install by going `npm install font-awesome --save`...

**Comment by juliankrispel** [comment]
@tagliala can close

**Comment by tagliala** [comment]
@juliankrispel thanks 👍
