### ISSUE TITLE
Icon Request: icon-ruler

### ISSUE THREAD

**Issue by pinolito** [FortAwesome/Font-Awesome#1096]
Something like this http://www.iconarchive.com/show/icons8-metro-style-icons-by-visualpharm/Very-Basic-Ruler-icon.html or this http://www.iconpng.com/icon/18480

**Comment by aeksco** [comment]
:+1:

**Comment by erhhung** [comment]
+1

**Comment by pmadden** [comment]
+1

**Comment by mashurex** [comment]
+1

**Comment by gquipster** [comment]
+1

**Comment by shmuel613** [comment]
+1

**Comment by kandre** [comment]
+1

**Comment by guptalav** [comment]
+1

**Comment by alwaysbrightblue** [comment]
+1

**Comment by shareit** [comment]
+1

**Comment by shkm** [comment]
+1

**Comment by abobwhite** [comment]
+1

**Comment by jbajou** [comment]
+1

**Comment by TheSisb** [comment]
+1

**Comment by oBlissing** [comment]
+1

**Comment by daprezjer** [comment]
+1

**Comment by jvgriffis** [comment]
+1

**Comment by BabbagesCabbages** [comment]
+1

**Comment by doranxenos** [comment]
+1

**Comment by cburgos** [comment]
+1

**Comment by julianxhokaxhiu** [comment]
+1

**Comment by VicCebedo** [comment]
+1

**Comment by Splik** [comment]
+1

**Comment by meysampg** [comment]
:+1:

**Comment by tuxy** [comment]
+1 but for fa-measure better call it "measure" instead.

define: measure; Dimensions, quantity, or capacity as ascertained by comparison with a standard.
Source: https://www.wordnik.com/words/measure

define: ruler; One, such as a monarch or dictator, that rules or governs.
Source: https://www.wordnik.com/words/ruler

**Comment by martinlindhe** [comment]
+1

**Comment by MonkeyData** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/3502679/9143427/79876eda-3d14-11e5-94c5-5fb1bd22d017.png)

**Comment by cuhuak** [comment]
+1

**Comment by gtsop** [comment]
+1

**Comment by Anwardo** [comment]
+1

**Comment by MrHalfman** [comment]
:+1:

**Comment by JKnott** [comment]
+1 (another example)

https://www.dropbox.com/s/zod0lgwbpffggrx/icon-ruler.ai?dl=1
![icon-ruler](https://cloud.githubusercontent.com/assets/6241112/9758792/01ba2e6c-56e9-11e5-8960-54d6055ceb5b.png)

**Comment by extravagangsta** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by matias-piin** [comment]
+1

**Comment by iamsarin** [comment]
+1

**Comment by timint** [comment]
+1

**Comment by smolleyes** [comment]
+1

**Comment by HansVraga** [comment]
+1

**Comment by abdujuk** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by dhaupin** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by GeonetDuncan** [comment]
+1

**Comment by jourdain** [comment]
+1
![3f1519fc-da51-11e5-9b56-7e6ce774b54b](https://cloud.githubusercontent.com/assets/294518/13290228/26a3e8c4-dad0-11e5-8b97-5f275fdd0020.png)

**Comment by slauyama** [comment]
+1

**Comment by steel89ita** [comment]
+1
Needed!

**Comment by bugbee** [comment]
+1

**Comment by filjander** [comment]
+1

**Comment by nikitul** [comment]
+1

**Comment by z38** [comment]
+1

**Comment by BabbagesCabbages** [comment]
this icon is 3 years in the making. will it ever happen?

**Comment by dangnelson** [comment]
+1

**Comment by teclanDesign** [comment]
+1

**Comment by asantaniello** [comment]
+1

**Comment by Zone14** [comment]
+1 please. This seems to be a fundamental need and clearly a fan favorite.

**Comment by johnasp** [comment]
Me too.  Want.

**Comment by bstolle** [comment]
+1

**Comment by Ladiczek** [comment]
+1

**Comment by borchsenius** [comment]
+1

**Comment by Guerillero** [comment]
+1

**Comment by nicolas-goudry** [comment]
+1

**Comment by Allen0721** [comment]
+1

**Comment by fncap** [comment]
+1
must-have

**Comment by jmillspaysbills** [comment]
👍

**Comment by anaszakaria** [comment]
👍

**Comment by DecSander** [comment]
+1

**Comment by alenb** [comment]
👍  2016

**Comment by joshkeyes** [comment]
👍

**Comment by gtsop** [comment]
2,5 year old ticket...

**Comment by larrylampco** [comment]
👍

**Comment by tjscollins** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode emojis: #222

- [📏 U+1F4CF](http://emojipedia.org/straight-ruler/)
- [📐 U+1F4D0](http://emojipedia.org/triangular-ruler/)

**Comment by wayofthefuture** [comment]
+1

**Comment by SmartyMcFlyNL** [comment]
+1

**Comment by rxkh** [comment]
+1

**Comment by apremalal** [comment]
+1

**Comment by wayofthefuture** [comment]
If anyone wants to make some cash I'll pay to get this created. Thanks.

**Comment by ajanini** [comment]
+1

**Comment by marketfreshstudios** [comment]
+1

**Comment by Groman123** [comment]
+1

**Comment by gtsop** [comment]
:birthday:

**Comment by mdomnita** [comment]
+1

**Comment by schmijos** [comment]
How can this be open since 2013?

**Comment by thkirchner** [comment]
+1

**Comment by blazeworx** [comment]
+1

**Comment by ProgrammingIsHard** [comment]
+1

(will it ever happen?)

**Comment by Approach** [comment]
srsly? want one of us to make a pull request or something?

**Comment by MrDioamDev** [comment]
+1

**Comment by spacebel** [comment]
+1

**Comment by patrickjamescarr** [comment]
+1

**Comment by SolidTerre** [comment]
+1 (it will mose likely never happen lol)

**Comment by JuanMa06** [comment]
+1

**Comment by Samuel-Clarke123** [comment]
+1 (Seriously how isnt this a thing tho)

**Comment by gregschwartz** [comment]
+1's as reactions don't seem to be working, so I'm adding a +1 as a comment. Since this has been requested for 4.5+ years (May 2013 to Nov 2017), is there an issue in the way of adding this? Perhaps that can be solved :)

**Comment by TomasZmuda** [comment]
+1

**Comment by keyjote** [comment]
+1
+2
...
+10000

Is there a reason why there is no response from the maintainers regarding this? this icon has been requested multiple times and for a long time and it is still not out.

I am looking at the beta of fa-5 and it is not in there either :(

**Comment by teclanDesign** [comment]
Still no ruler in FA 5?

**Comment by sebalaini** [comment]
+1 I've started to create a job project and what a deception, no ruler and it's seems that you are not interested at all, new "useless" icon added but still not a basic one like a ruler that has been requested for years :(

**Comment by mframp** [comment]
Maybe they'll add it on the 5 year anniversary of the request!
Seriously though, spend two minutes this weekend and add it.

**Comment by gregschwartz** [comment]
I tweeted at them: https://twitter.com/fontawesome/status/954460069864857600

**Comment by sookoll** [comment]
+1

**Comment by kevikramer** [comment]
+1

**Comment by supernintendo** [comment]
This and https://github.com/FortAwesome/Font-Awesome/issues/1355 have both been open for 5 years and still nothing in FontAwesome I can use to signify dimensions (unless I'm missing something). How have useless icons like `fa-angrycreative` taken precedence? Do the FontAwesome maintainers accept payment to add company logos or something? I'm willing to throw down for a ruler if that's the case.

**Comment by loorlab** [comment]
+1

**Comment by fiskrens** [comment]
+1

**Comment by Greenka236** [comment]
+1

**Comment by bruntrd** [comment]
+1

**Comment by uygardonduran** [comment]
+1

**Comment by angechilada** [comment]
+1

**Comment by neoritter** [comment]
Hooli and Poo icons, but no basic icon like a ruler or some other sort of measure icon.... +1!

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by gtsop** [comment]
Ahhh! I 've been clicking the notifications on my mail to this page for almost 5 years now although I don't need it anymore (changed job) and laughing at this issue not getting closed. Now this fun little game ended. It 's been a wonderful journey.
