### ISSUE TITLE
Icon Request: fa-version

### ISSUE THREAD

**Issue by Plasmmer** [FortAwesome/Font-Awesome#10965]
Something like (vXX) symbolizing a versioning of a thing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not conviced of the above use case, IMHO it seems cryptic.

GitHub uses [`tag`](http://fontawesome.io/icon/tag/) to represent releases

There is also a "milestone" icon: http://fontawesome.io/icon/map-signs/
