### ISSUE TITLE
Icon Request: icon-ping

### ISSUE THREAD

**Issue by ronaldroe** [FortAwesome/Font-Awesome#10972]
An icon that represents a ping, such as a sonar wave. I am building an app for team-based task management, and will include the ability for the assigning party to "ping" users periodically for status on the task. I am currently using the bullseye icon, but it doesn't quite have the look I'm going for.
![ping](https://cloud.githubusercontent.com/assets/1720729/25258732/04a06314-2607-11e7-997e-d0b91acc4922.png)
The image above is roughly what I was envisioning, but [something like this](https://thenounproject.com/term/radar/652880/) would also work, though it's a bit more detailed than I think is necessary.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does http://fontawesome.io/icon/rss/ fit you use case?

**Comment by ronaldroe** [comment]
Thank you for the suggestion. It could work, but it could also be mistaken for RSS functionality. I think an icon like the one I posted (or another design that fits the idea) would be a little more clear.

**Comment by NonameSLdev** [comment]
@ronaldroe Perhaps naming the icon "radar" would be more efficient, because "ping" is hard to icon.

**Comment by jjr2000** [comment]
@ronaldroe  You can achieve a very similar icon using fa-stack if you are in need of this now.
![image](https://cloud.githubusercontent.com/assets/14221773/25389416/764e151e-29c8-11e7-8daa-fd095b0497b1.png)

the code for this is as so

` <span class="fa-stack fa-lg right" style="font-size: 32px;">
    <i class="fa fa-stack-1x fa-rss" style="-ms-transform: rotate(45deg); /* IE 9 */
    -webkit-transform: rotate(45deg); /* Chrome, Safari, Opera */
    transform: rotate(45deg); left:0.75em;top:0.1em"></i>
    <i class="fa fa-stack-1x fa-rss" style="-ms-transform: rotate(225deg); /* IE 9 */
    -webkit-transform: rotate(225deg); /* Chrome, Safari, Opera */
    transform: rotate(225deg); left:0;top:0;"></i>
  </span>`

Hope this is of help to you.

**Comment by ronaldroe** [comment]
Thank you. That may work in the interim.

**Comment by tagliala** [comment]
I will consider this closed by https://fontawesome.com/icons/signal-stream?s=solid
