### ISSUE TITLE
fa-check has lost its alias fa-ok

### ISSUE THREAD

**Issue by igordata** [FortAwesome/Font-Awesome#10971]
Hi!

Just realized that a check mark lost an alias "ok". It exist as alias for check on the web site, but it doesn't exit in css files any more.

Looks like it's a bug. fa-ok is useful when one decides to quickly switch from glyphicons to fontawesome icons.

Fix. Just add an alias :D
```
.fa-ok:before,
.fa-check:before {
  content: "\f00c";
}
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've checked the [icons.yml file at v4.0.0](https://github.com/FortAwesome/Font-Awesome/blob/v4.0.0/src/icons.yml#L86) and there is no "ok" alias.

The alias is also not present in [3.2.1](https://github.com/FortAwesome/Font-Awesome/blob/v3.2.1/src/icons.yml#L474)

Could you tell me which version has the `fa-ok` alias?

**Comment by igordata** [comment]
Sorry, my bad. I just checked, and I think it never was there.

But you definitely should add, because it simplifies use of Fontawesome icons in existing Bootstrap projects! :D
