### ISSUE TITLE
Icon Request: icon-jackpot

### ISSUE THREAD

**Issue by medinlu** [FortAwesome/Font-Awesome#1097]
![header](https://f.cloud.github.com/assets/832597/512982/72933b5a-be35-11e2-80fc-9049e3a51c6a.jpg)

**Comment by aethior** [comment]
Hi @medinlu,

Can we considered this request solved with [fa-slot-machine](https://fontawesome.com/icons/slot-machine) icon?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
> Can we considered this request solved with [fa-slot-machine](https://fontawesome.com/icons/slot-machine) icon?

I think so, closing here meanwhile
