### ISSUE TITLE
Icon request: icon-mineralwater

### ISSUE THREAD

**Issue by mrStenvik** [FortAwesome/Font-Awesome#10984]
Something in this area: 

![mineralwater](https://cloud.githubusercontent.com/assets/27947303/25326085/ce234eda-28ce-11e7-9f3e-f4d2d95debbe.JPG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10741, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by PeterShaggyNoble** [comment]
@tagliala, #10741 is a request for a larger water bottle that would be used in a water cooler, whereas this one looks to be a smaller bottle that you would buy in the shops.

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks.

Maybe a duplicate of #5365?
