### ISSUE TITLE
bug: position of icon "fa-download"

### ISSUE THREAD

**Issue by stevobm** [FortAwesome/Font-Awesome#10989]
I notice that there is a blank under the "bar" of the icon "fa-download", which makes it look like a little "higher" than the icon "fa-upload", as the following image shows :
![fontawesome_download_upload](https://cloud.githubusercontent.com/assets/5198256/25367010/d2cb5eaa-29a5-11e7-9d7a-30a6ebd63676.gif)
As the two icons are similar, should not they be drawn on a same position?

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

This is a known issue: #1624

It should be solved in the upcoming FA 5.0.0

Closing here
