### ISSUE TITLE
Icon request: fa-wattpad

### ISSUE THREAD

**Issue by innosuke** [FortAwesome/Font-Awesome#10988]
Hello Fort Awesome!

I just recently found your amazing site your icons helped me a lot in designing my blogsite.
It's that, I hope you'll add a wattpad icon to your list of icons for this will help online writer like me.

Thank you so much in advance!

Here is wattpad icon:
![images 1](https://cloud.githubusercontent.com/assets/27980515/25362579/72ffcec0-2987-11e7-9430-073f5696bde0.png)

**Comment by PeterShaggyNoble** [comment]
This is a duplicate of #3402; you should give that a 👍 instead.
