### ISSUE TITLE
Icon request: Fence

### ISSUE THREAD

**Issue by lxure** [FortAwesome/Font-Awesome#10980]
Fence icon
Uses: Fence, gate, privacy, gated area, Restricted access.

**Comment by ryankane** [comment]
This was already requested in #7926, but closed? Hmm…

![fence](https://cloud.githubusercontent.com/assets/1094151/25386399/3f20b9da-2995-11e7-9ba2-b048ccddaefe.png)

**Comment by tagliala** [comment]
@ryankane the author shutted down the original request. I don't feel comfortable reopening that and asking the author to disable notifications, so I'm keeping this as the reference request

**Comment by drooog** [comment]
+1 We need this for our application as well

**Comment by my-name-means-girl** [comment]
Would use icon for geo fencing, marketing for services and goods relating to fences and manual labor, Could also be used for sports D-Fence as well.

**Comment by tagliala** [comment]
Available in FA6 Pro https://fontawesome.com/v6.0/icons/fence?s=solid
