### ISSUE TITLE
Icon request: icon-smile, icon-frown, icon-meh

### ISSUE THREAD

**Issue by flipside** [FortAwesome/Font-Awesome#11]
Would love an icon that could be used to express 'maybe', 'kinda', 'sorta', 'meh' non-committal fuzziness. 

The tilde character ~ would seem to fit the bill. 

Thanks and I'm looking forward to playing around with Font-Awesome.

**Comment by byronyasgur** [comment]
Frown face is great but it is literally a frown ... it can't really be used as a sad face ... I tried to use it as a sad face if the user viewed their cart and the didn't have any products, but it looked like I was judging them for not buying anything ... had to remove it ... nice icon though, not sure how useful it will be
