### ISSUE TITLE
Icon Request: traffic icons 

### ISSUE THREAD

**Issue by Bmark201** [FortAwesome/Font-Awesome#11006]
Hej all for different driving schools I would like to request icons reflecting their offer. It also can be very helpful for other traffic related topics:

![auto](https://cloud.githubusercontent.com/assets/28147000/25529657/57686ce6-2c23-11e7-9219-72ae1baab458.png)
![bromfiets](https://cloud.githubusercontent.com/assets/28147000/25529656/57673a88-2c23-11e7-84ff-b5adbcc52070.png)
![brommobiel](https://cloud.githubusercontent.com/assets/28147000/25529660/576b427c-2c23-11e7-8da1-ebd2ba857bba.png)
![bus](https://cloud.githubusercontent.com/assets/28147000/25529661/576d4c2a-2c23-11e7-921c-5a60b969fac9.png)
![code_95](https://cloud.githubusercontent.com/assets/28147000/25529658/57690cdc-2c23-11e7-900a-d8f1e8614ad2.png)
![motor](https://cloud.githubusercontent.com/assets/28147000/25529659/5769fe6c-2c23-11e7-8642-dc97a89b1625.png)
![tandemasser](https://cloud.githubusercontent.com/assets/28147000/25529662/57828a36-2c23-11e7-9811-57dec739bb31.png)
![trekker](https://cloud.githubusercontent.com/assets/28147000/25529663/578609fe-2c23-11e7-8caa-4eef1c304159.png)
![vrachtauto](https://cloud.githubusercontent.com/assets/28147000/25529664/57872ad2-2c23-11e7-95eb-d55e45bea540.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by Bmark201** [comment]
@tagliala,

My suggestions would be an expansion of your already existing fonts. So I don't really get your answer. Is it because of my pore explanation with the suggestions?

**Comment by tagliala** [comment]
> The car, truck and motor are already existing font with you. Maybe I shouldn't have posted these? I thought that they might could be like an update for the existing ones?

Yes, as per [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons), you should make single requests for icons which are not already in the set, having care of [searching](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests.

Example: traktor is a duplicate of #5052

Please take another look at [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons), you should make single requests for icons which are not already in the set, having care of [searching](https://github.com/FortAwesome/Font-Awesome/search?type=Issues)
