### ISSUE TITLE
Icon request: icon-NC (etc)

### ISSUE THREAD

**Issue by ElevenMassMedia** [FortAwesome/Font-Awesome#11007]
Icons of the 50 states would be very helpful, particularly on websites where you're trying to indicate business locations. 
![sd-720](https://cloud.githubusercontent.com/assets/28153264/25536043/3d82b852-2c07-11e7-9c9b-1b3d6fe07397.png)

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment country silhouettes are out of scope.

Please use an .svg based approach.

Ref: #3108

Reasons: https://github.com/FortAwesome/Font-Awesome/issues/3992#issuecomment-73022665

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
