### ISSUE TITLE
Icon Request: Icon Deploy

### ISSUE THREAD

**Issue by Srijithr1** [FortAwesome/Font-Awesome#11004]
Request you to create an icon for Deploy or Deployment. It is commonly using one of the icons. 

Thanks & Best Regards,

Srijith

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px size example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by aethior** [comment]
@tagliala I think you can close here.

In any case, the most commonly used icon for `deployment` is `fa-rocket`.
