### ISSUE TITLE
Icon Request: fa-pivot

### ISSUE THREAD

**Issue by jitendrapc** [FortAwesome/Font-Awesome#11012]
Hello, I searched but failed to get the pivot grid and similar icon that I wanted to use for displaying pivot grid on a set of data. Is it possible to provide such icon?

I have attached a sample pivot image which can be a reference for the icon I am looking for.

Thanks a lot,
Jitendra
![pivot-table](https://cloud.githubusercontent.com/assets/28299457/25617631/e31ece5c-2f60-11e7-876b-2e55c399f370.png)

**Comment by arturgspb** [comment]
Maybe Google Analytics Icon more useful

![2017-05-11 20 20 07](https://cloud.githubusercontent.com/assets/1708175/25962659/4256a30e-3687-11e7-9dc4-471632dd6553.png)

**Comment by jitendrapc** [comment]
Thanks Artur, this icons should be useful, where can I find the font icon for this? is it part of font-awesome library?

**Comment by arturgspb** [comment]
No. It's a sprite gif in original.

**Comment by arturgspb** [comment]
Original url: https://ssl.gstatic.com/analytics/20170510/web/sprites.png

I select place in screenshot:
![2017-05-12 10 32 25](https://cloud.githubusercontent.com/assets/1708175/25987868/6fb98740-36fe-11e7-82d0-11f48a7e5d38.png)

**Comment by fandomfilms** [comment]
Need a pivot icon as well.  Says this is closed but not seeing it in the library.

**Comment by aethior** [comment]
Hi @jitendrapc,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/table-pivot

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
https://fontawesome.com/icons/table-pivot?f=classic&s=solid
