### ISSUE TITLE
Icon request: icon-at email

### ISSUE THREAD

**Issue by jiangshilin** [FortAwesome/Font-Awesome#1101]
Like this

![image](https://f.cloud.github.com/assets/4455361/517041/e117e3a2-bece-11e2-9767-a61e9c12f35d.png)

Thanks!

**Comment by atilkan** [comment]
Style of fa-at is not cool. I expected something better.

**Comment by tagliala** [comment]
@atilkan please open a new issue

**Comment by atilkan** [comment]
ok thanks.
