### ISSUE TITLE
Icon Request: fa-safety-belt

### ISSUE THREAD

**Issue by gandomi** [FortAwesome/Font-Awesome#11019]
I love FontAwesome. Thank you very much for this project.
I would ask for following icon:
![belt](https://cloud.githubusercontent.com/assets/13612997/25678414/df94582a-305e-11e7-90c9-2c64fb4552e9.png)

use case: AVL Tracking systems

**Comment by shaedrich** [comment]
Could be also named **fa-seat-belt**.

The icon could also look like this similar to what you can see in airplanes: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ020CQWdKIwWtkK_5jQnmywGhQYbG-we2q5e3fq5cWze95gRt

**Comment by destinybravos** [comment]
Any Update on this Icon?

**Comment by johnish** [comment]
I would love this, actually I need it right now for a very visible project.

**Comment by aethior** [comment]
Duplicate of #10294.

cc/ @tagliala
