### ISSUE TITLE
Icon Request: fa-level-across

### ISSUE THREAD

**Issue by Terhiman** [FortAwesome/Font-Awesome#11015]
Useful for indicating sub-levels of an item.
![level-across](https://cloud.githubusercontent.com/assets/27024441/25640939/82065616-2f89-11e7-93d8-79f99eeb3407.jpg)
Example where I would use it - 
![image](https://cloud.githubusercontent.com/assets/27024441/25641290/3c1742c6-2f8b-11e7-972d-bfc2f7d25e02.png)
Looks awful and too large but then im hopeless at photoshop

**Comment by FinesseRus** [comment]
Here it is, you can use it right now: ↳

**Comment by darksnake747** [comment]
I actually like this icon; though it has a similar use/desire to this request: https://github.com/FortAwesome/Font-Awesome/issues/16538

AND technically, you can get this icon as is with https://fontawesome.com/v5.15/icons/level-up-alt?style=solid and rotation/mirroring options: https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/rotating-icons.

I know this is a bit old, but I hope this can help somehow!

~Cheers~

**Comment by aethior** [comment]
Hi @Terhiman,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/turn-down-right

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
Duplicate of #4693.

cc/ @tagliala
