### ISSUE TITLE
Icon request: Data Types (binary, string, int, float, array, object, ...)

### ISSUE THREAD

**Issue by 26medias** [FortAwesome/Font-Awesome#11011]
It would be great for web applications to have main data type icons.

- null
- boolean
- binary
- string
- number
- array
- object

This would be useful for:

- Code and API documentations
- Online code editors
- Online administration tools

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
