### ISSUE TITLE
Icon request: LE & Riyal Currency icon

### ISSUE THREAD

**Issue by islamx** [FortAwesome/Font-Awesome#11017]
LE : Egypt Pound
Riyal Saudi : Saudi Arabia

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Please make single individual requests, providing an example of the icon and having care of searching before if a request already exist
