### ISSUE TITLE
Icon Request: fa-shopify

### ISSUE THREAD

**Issue by doprdele** [FortAwesome/Font-Awesome#11022]
I would like an icon to represent the shopify brand of ecommerce software, as represented here:
https://cdn.shopify.com/assets/images/logos/shopify-bag.png

This would be for text or chrome extensions that determine whether a site is a shopify ecommerce site

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
