### ISSUE TITLE
animation-charging: frame time unstable and constantly differs.

### ISSUE THREAD

**Issue by SuperPrower** [FortAwesome/Font-Awesome#11028]
```
[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%
; Only applies if <ramp-capacity> is used
ramp-capacity-0 = ï‰„
ramp-capacity-1 = ï‰ƒ
ramp-capacity-2 = ï‰‚
ramp-capacity-3 = ï‰
ramp-capacity-4 = ï‰€

; Only applies if <animation-charging> is used
animation-charging-0 = ï‰„
animation-charging-1 = ï‰ƒ
animation-charging-2 = ï‰‚
animation-charging-3 = ï‰
animation-charging-4 = ï‰€
; Framerate in milliseconds
animation-charging-framerate = 500
```

Title speaks for itself: animation is weird, it can wait more that delay for the first frame, and then run trough remaining frames faster than the blink of an eye, or be almost normal.
In other words, time that 1 frame stays drawn is different every time.

My version of polybar is:

```
$ polybar --version
polybar 3.0.5

Features: +alsa +curl -i3 -mpd +network
```

My OS is Arch Linux, with Intel Graphics (only).
I can't currently provide any screencast, but will do so if I have possibility.

**Comment by tagliala** [comment]
Hi, could you please clarify this request?

**Comment by SuperPrower** [comment]
Sorry if I am not clear enough; English is not my native language.
What I am trying to say is: animation-charging animation is acting weird; Some frames take more time than others, and on another loop, situation changer, one frames starting to take longer than other.
I believe this is just animation bug.
As I said, I will provide screencast of a problem later, when I will have opportunity. (can't get any of screencast programs work in openbox)

**Comment by tagliala** [comment]
is animation-charging a font awesome feature?

**Comment by SuperPrower** [comment]
Oh my god, sorry >_<
Wrong place, yes.

**Comment by tagliala** [comment]
@SuperPrower don't worry 👍
