### ISSUE TITLE
Update font files 

### ISSUE THREAD

**Issue by AilurusF** [FortAwesome/Font-Awesome#11025]
Where you should be uploading the fonts on a fully hosted wordpress site?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use stackoverflow if you need support

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues).
