### ISSUE TITLE
Glyph "fa-calendar-check-o" has an undesired margin at right

### ISSUE THREAD

**Issue by artsjedi** [FortAwesome/Font-Awesome#11023]
Check at fa-calendar-check-o character and compare to the fa-calendar. It does have an extra margin on the left. It leads to unexpected right or center alignment.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue, described at #8628 and scheduled for 5.0.0

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new issues

Closing here
