### ISSUE TITLE
icons now working in mac safari IOS

### ISSUE THREAD

**Issue by ankit-tm** [FortAwesome/Font-Awesome#11024]
Hello team 

fontawesome icons are not working in mac safari IOS could you please help me for that how I can sole this issue beacuse in IOS chrome IOS all is working properly 

only not working in Safari IOS

waiting for your reply 

thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Of course I cannot confirm this issue.

Can you see icons at [fontawesome.io](http://fontawesome.io)? If you can, please check your Font Awesome configuration.

Please also take a look at our [troubleshooting guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting)

Closing here
