### ISSUE TITLE
Icon Request: fa-pallet

### ISSUE THREAD

**Issue by sugarflux** [FortAwesome/Font-Awesome#11036]
Hi

I would like to request an icon that looks like a pallet please, ideally with variations fa-pallet-full, fa-pallet-empty for example.

Possibly something similar to this: https://goo.gl/images/DXP51L (empty)
Or this: https://goo.gl/images/iAI0zs (full / loaded)

We have many clients in logistics and currently struggle to find anything that can clearly infer when a shipping container or pallet is loaded or empty.

Open to suggestions though if you believe something similar already exists but I haven't yet found anything to meet this purpose.

Thanks

**Comment by sensibleworld** [comment]
There are a few options for this in the Logistics category in 5.0.7: https://fontawesome.com/icons?d=gallery&c=logistics
