### ISSUE TITLE
Etsy Unicode (f2d7) not rendering

### ISSUE THREAD

**Issue by craigtommola** [FortAwesome/Font-Awesome#11034]
Etsy Unicode (f2d7) is not rendering. Just getting a box.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure you are using Font Awesome 4.7.0

Take another look at our [Troubleshooting guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up).

Hope it helps, closing here

**Comment by craigtommola** [comment]
That's precisely the problem. I'd like to suggest that non-current versions reside at URLs with the version included, while the current version live at /current/ much the way WordPress's current version is always available at https://wordpress.org/latest.zip

Thx
CT

**Comment by tagliala** [comment]
> much the way WordPress's current version is always available at https://wordpress.org/latest.zip

The auto-update feature could be a nice addon, but it does come with a cost: https://github.com/FortAwesome/Font-Awesome/issues/10605#issuecomment-276996482
