### ISSUE TITLE
Icon request: icon-Facebook 360 icon 

### ISSUE THREAD

**Issue by thejameshay** [FortAwesome/Font-Awesome#11039]
I plan on using it as service based icon on my website. The usual Font Awesome blue color would be preferable, Thanks in advance! 
![360](https://cloud.githubusercontent.com/assets/28551362/25832818/40388af6-342a-11e7-9339-35a4857148ce.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If this is not a brand, I would consider this request a duplicate of #772.

Could you please check if this is a registered brand logo?

**Comment by tagliala** [comment]
No feedback, considering this a duplicate of #772

Closing here
