### ISSUE TITLE
Icon Request: fa-tuning-fork

### ISSUE THREAD

**Issue by itsonlycomputers** [FortAwesome/Font-Awesome#11033]
Requesting a new icon for a tuning fork.  Example attached.
![tuning](https://cloud.githubusercontent.com/assets/11696791/25810311/fc7c223a-33cc-11e7-9cc1-dc55eaab7b51.jpg)

Would prefer examples 3-5 in the attached image.
Thanks!

**Comment by tagliala** [comment]
Duplicate of #4474?

**Comment by joshstovall** [comment]
I would also like to see a tuning fork icon!

**Comment by tagliala** [comment]
No feedback

Closing here as a duplicate of #4474
