### ISSUE TITLE
Icon request: fa-fish

### ISSUE THREAD

**Issue by MarvDann** [FortAwesome/Font-Awesome#11043]

**Comment by MarvDann** [comment]
Use case is a travel site that wants to have a 'Things to Do' section with fishing as an option.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2722, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
