### ISSUE TITLE
Icon request: fa-shield-with-check

### ISSUE THREAD

**Issue by zxj112** [FortAwesome/Font-Awesome#11040]
![default](https://cloud.githubusercontent.com/assets/28553757/25835154/1aeba5aa-34af-11e7-9bc4-4624805bcc98.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a different use case from http://fontawesome.io/icon/shield/ ?

**Comment by pbksol** [comment]
I just want to add a different approach… Why not make an empty shield (without half of it black) to be able to simply stack the shield with the checkmark (or an x)?

```
<span class="fa-stack fa-lg">
  <i class="fa fa-shield fa-stack-2x"></i>
  <i class="fa fa-check fa-stack-1x"></i>
</span>
```

```
<span class="fa-stack fa-lg">
  <i class="fa fa-shield fa-stack-2x"></i>
  <i class="fa fa-times fa-stack-1x"></i>
</span>
```

Much more flexible, isn't it?

**Comment by mohamedabkd** [comment]
![fa verified shield](https://user-images.githubusercontent.com/35741579/35297150-734e2a42-007e-11e8-9f28-74ee08149d8a.jpg)
I combined the shield and check icons that exist already, the icon like this serves in websites as: verified account, verified listing, verified user, secure payment..
Would be very helpful if you include it.

**Comment by mohamedabkd** [comment]
+1

**Comment by pbksol** [comment]
It's included in FA5 pro

**Comment by mohamedabkd** [comment]
How much is it?

**Comment by aethior** [comment]
Hi @zxj112,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/shield-check

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to the Pro set

**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/63/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
