### ISSUE TITLE
SoundCloud Icon OffCentered

### ISSUE THREAD

**Issue by elijahb1411** [FortAwesome/Font-Awesome#11046]
I'm super new to GitHub - just made an account for this issue.

Every fa icon has been fantastic except for the SoundCloud icon.  I just updated to the latest version, but no matter how or where I place it, the SoundCloud logo is always off-centered compared to every other icon.  Any help would be appreciated!

//elijahb

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do you mean vertically or horizontally centered?

Could you please post a fiddle showing the issue? You can start with this one https://jsfiddle.net/tagliala/s3msxtbe/

**Comment by elijahb1411** [comment]
@tagliala Hey!  I'm sorry I'm a complete noob haha - I'm not quite sure how to do that.  Here are a few screenshots though!

![screen shot 2017-05-09 at 4 33 21 pm](https://cloud.githubusercontent.com/assets/28575527/25871418/61542e92-34d5-11e7-8078-078c28da31d7.png)
![screen shot 2017-05-09 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/28575527/25871419/615b6fae-34d5-11e7-978e-3f7ee67abc2b.png)

Let me know if there's any more info I can get to you to help get the solution!  Thank you!!  :)

**Comment by tagliala** [comment]
The problem is that the souldcloud icon is too near the instagram one?

**Comment by elijahb1411** [comment]
@tagliala right!!  If I swap the fa-soundcloud to any other icon like fa-bandcamp or fa-envelope-o it's perfectly aligned with all of the other icons.  It's only the SoundCloud one that is offset like that.  Again thank you for your help!

**Comment by tagliala** [comment]
@elijahb1411 got it.

At the moment I'm writing, font awesome icons have different width (this may change in FA 5.0) so you should add the `fa-fw` class to your icons (and fix your margins accordingly).

Take a look here: https://jsfiddle.net/tagliala/s3msxtbe/15/

Hope it helps

**Comment by elijahb1411** [comment]
@tagliala hey!!

Bad news - I just added those tags but to no avail.  I guess I should just wait until the next update and try the latest version?  Thank you!  

![screen shot 2017-05-10 at 4 19 27 pm](https://cloud.githubusercontent.com/assets/28575527/25919363/8fbb9816-359c-11e7-98b5-d7690cf8939a.png)

**Comment by tagliala** [comment]
you should add `fa-fw` to all icons

**Comment by elijahb1411** [comment]
@tagliala hmm, I tried that but I still get the same issue.  Any other things I could try?
![screen shot 2017-05-11 at 10 43 22 am](https://cloud.githubusercontent.com/assets/28575527/25955249/b7ef1066-3636-11e7-8112-89337835aa1e.png)

**Comment by tagliala** [comment]
@elijahb1411 try asking for help on stackoverlow

The github issue tracker should be used for requests and bug related to font awesome.

As you can see at https://jsfiddle.net/tagliala/s3msxtbe/15/ there are no issues with font awesome and the different width of icons is a design choice.

Also, if you are not satisfied with the results, you may need custom css rules to fine-tune the margins between icons.

Hope it helps
