### ISSUE TITLE
Icon request: fa-cc-maestro

### ISSUE THREAD

**Issue by kirazhy** [FortAwesome/Font-Awesome#11049]
also this is a payment that I need to make my website,thx
![image](https://cloud.githubusercontent.com/assets/22928961/25893272/b99d0432-35a9-11e7-963e-0a0aebde61f9.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4266, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
