### ISSUE TITLE
Icon request: suggestion chess icons

### ISSUE THREAD

**Issue by vasiliyaltunin** [FortAwesome/Font-Awesome#11047]
I create chess icons from old MeridaChess font, and now i wanna it to be added to AwesomeFont 

All sources and examples here - https://github.com/vasiliyaltunin/chess-merida-font

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are not accepting PR containing icons, but there are some folks that could be interested in your set. Please share your font here: #1815 

[Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md).
