### ISSUE TITLE
Icon Request: videores-raw, videores-2k, videores-6k, videores-8k, video-resolution

### ISSUE THREAD

**Issue by UltraCakeBakery** [FortAwesome/Font-Awesome#11051]
I'm working on a project that works with high-resolution video (raw camera demo footage) and it would be nice if you guys could add icons for video resolutions.

Usage:
- Video players
- Technical specification lists
- Search engine's

video-resolution:
![1168-resolution](https://cloud.githubusercontent.com/assets/12383587/25921001/16226506-35d4-11e7-9638-3e199b3e79de.jpg)

2K, 6k and 8k:
![download](https://cloud.githubusercontent.com/assets/12383587/25920636/e8a2f8d0-35d2-11e7-9efe-c8443fa1cf20.png)
RAW:
![images](https://cloud.githubusercontent.com/assets/12383587/25920724/28fdbf50-35d3-11e7-93df-c76c97278d14.jpg)

**Comment by Crissov** [comment]
Unicode / ARIB
--------
http://www.unicode.org/charts/beta/nameslist/c_1F100.html 
#222 

- 🆝 U+1F19D `SQUARED TWO K`
- 🆞 U+1F19E `SQUARED FOUR K`
- 🆟 U+1F19F `SQUARED EIGHT K`
- 🆨 U+1F1A8 `SQUARED HI-RES`
- 🆩 U+1F1A9 `SQUARED LOSSLESS`
- 🆪 U+1F1AA `SQUARED SHV`
- 🆫 U+1F1AB `SQUARED UHD`
- 🅊 U+1F14A `SQUARED HV`
- 🅌 U+1F14C `SQUARED SD`

**Comment by UltraCakeBakery** [comment]
I have been waiting for feedback for quite a while now. Can someone look at this again or close this if its a clear NO?

**Comment by sam3d** [comment]
Just bumping this issue, as this would be great 👍

**Comment by UltraCakeBakery** [comment]
Bumping this issue once again. Please just add this...

**Comment by UltraCakeBakery** [comment]
Closing this as the fontawesome team will probably not implement this anyways. It would make a lot of sense but they are really just focused on making money rn. If someone wants this badly feel free to open a new request.
