### ISSUE TITLE
Icon Request: education section

### ISSUE THREAD

**Issue by ricardomalias** [FortAwesome/Font-Awesome#11057]
Like medical section will be good if we has educational section with icons like teacher:

https://image.flaticon.com/icons/png/512/42/42912.png

blackboard

https://images.vexels.com/media/users/3/139696/isolated/preview/843361c3c336a29ea58b615242f7bedd-black-board-icon-by-vexels.png

And another ideas like ticket below:

knowledge: https://github.com/FortAwesome/Font-Awesome/issues/3297
school bus: https://github.com/FortAwesome/Font-Awesome/issues/7775

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
