### ISSUE TITLE
Icon request: icon-viber

### ISSUE THREAD

**Issue by amhadii** [FortAwesome/Font-Awesome#11050]
Viber is a social media app for chatting and calling like whatsapp. The icon will be help to everyone for their projects. Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3554, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
