### ISSUE TITLE
Icon request: fa-mathcompass (drawing circles)

### ISSUE THREAD

**Issue by AlmalkiLabs** [FortAwesome/Font-Awesome#11062]
-Used to represent accuracy and precision.

![acompass](https://cloud.githubusercontent.com/assets/25111897/26040815/524c993c-38f6-11e7-82f9-e74868fbb5b3.png)
![compass-256](https://cloud.githubusercontent.com/assets/25111897/26040819/56be58c0-38f6-11e7-9484-b6f1deb38737.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1378, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
