### ISSUE TITLE
Icon Request: fa-shopping-basket-o

### ISSUE THREAD

**Issue by KennethDanielsen** [FortAwesome/Font-Awesome#11079]
Some of the most generic icons lack an outlined version. 
In my case I'm missing the shopping-bag, shopping-basket and shopping-cart.

Something you'll consider? :-)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

shopping-cart-o is a duplicate of #10051, please 👍  that request
shopping-bag-o is a duplicate of #10321, please 👍  that request

Renaming this as `fa-shopping-basket-o`

**Comment by tagliala** [comment]
This icon is available in FA5 Pro

https://fontawesome.com/icons/shopping-basket?style=regular
