### ISSUE TITLE
Icon Request: fa-vip

### ISSUE THREAD

**Issue by lss5270** [FortAwesome/Font-Awesome#11082]
![vip](https://cloud.githubusercontent.com/assets/28615161/26183388/04efd696-3bb1-11e7-83d3-b6cd06ce32f9.png)

我想要一个关于会员（vip）的图标，其实本质就是一颗钻石的样子，图标名字你们可以重命名，不知道可以帮加不？

I want to be an icon of members (VIP), and the appearance of the fact that there is a diamond, the icon name you can rename, don't know can help with?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I'm not able to understand this request

Is VIP a brand? Could you please provide a website?

Font Awesome already has a diamond icon: http://fontawesome.io/icon/diamond/

**Comment by lss5270** [comment]
I got it, this is what I need, thank you!
