### ISSUE TITLE
Icon Request: fa-forklift

### ISSUE THREAD

**Issue by bwhite71** [FortAwesome/Font-Awesome#11083]
Hello, I would like to request a forklift icon to be used for our logistics web application.  This would be used to indicate the loading or unloading of freight.  This icon would be used within a service flow (i.e. fa-truck -> fa-forklift (i.e. load) -> fa-plane).

Thank you,
Brian

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
