### ISSUE TITLE
Icon Request: fa-transform

### ISSUE THREAD

**Issue by koMah** [FortAwesome/Font-Awesome#11081]
Hi I'm currently developing a 2D/3D web application and this icon is missing. Thanks

![transform-2-icon 1](https://cloud.githubusercontent.com/assets/1476359/26162693/baae1040-3b27-11e7-9ad5-6eac890ab9e6.png)

**Comment by aethior** [comment]
Hi @koMah,

This icon was added in v5.1.0.
Check https://fontawesome.com/icons/vector-square

Regards.

cc/ @tagliala
