### ISSUE TITLE
Icon Request: fa-hospitality

### ISSUE THREAD

**Issue by Fomoria** [FortAwesome/Font-Awesome#11095]
Hello, we are building an hotel website and a couple of icons are missing:
sauna
swimming pool
smoking area
hair dryer
laundry service

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
