### ISSUE TITLE
some icons not works propely on Firefox and showing just a square

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#11091]
Hi,
font awesome it is working perfect for me and chrome, but I noticed on firefox some icons not show up, any reason  what could be?

working
![screenshot from 2017-05-18 17-12-00](https://cloud.githubusercontent.com/assets/993318/26213190/0682a7a6-3bf0-11e7-82e0-26131d6f3ab9.png)

error
![screenshot from 2017-05-18 17-24-18](https://cloud.githubusercontent.com/assets/993318/26213019/5b38e5e0-3bef-11e7-81e7-5c57096e0b13.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Probably you are (directly or indirectly) using two different font versions and firefox is loading a version older than 4.7

Please check our Troubleshooting Guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Pay particular attention to point 5 (but please make sure you checked all the other points)

Hope it helps, closing here
