### ISSUE TITLE
Icon request: Python icon

### ISSUE THREAD

**Issue by davidmpaz** [FortAwesome/Font-Awesome#11098]
Hi FA,

Please could you add the snake python icon?

thanks for such a great project

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3016, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by davidmpaz** [comment]
Oops,

Sorry. I did, but obviously did not search properly. Thanks!! 

Reaction added.

Cheers
