### ISSUE TITLE
Icon request: fa-pedigree

### ISSUE THREAD

**Issue by jwilliamsen** [FortAwesome/Font-Awesome#11096]
A pedigree icon would be helpful to indicate a pedigree or family tree is available.  tags: ancestry, genealogy, pedigree, family tree

![image](https://cloud.githubusercontent.com/assets/28830458/26279026/239bb946-3d66-11e7-9050-2b89c1893f12.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think http://fontawesome.io/icon/sitemap/ does the job

Closing here

**Comment by jwilliamsen** [comment]
It does not do the job because a person or animal only has two parents - not 3

 

 

 

-----Original Message-----

**Comment by tagliala** [comment]
What about http://fontawesome.io/icon/share-alt/ ?

**Comment by jwilliamsen** [comment]
I saw that one but think it is very recognizable as "share."  If you look at sites like ancestry.com the connectors are more square instead of triangular like a traditional pedigree chart.
