### ISSUE TITLE
.small class is not in .fa namespace

### ISSUE THREAD

**Issue by govorov** [FortAwesome/Font-Awesome#11107]
Hi!
Arbitrary element on a page with `.small` class is affected by font awesome styles.
It seems to be a bug, and I suppose it's reasonable to use something like `.fa.small` instead.
Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/css/font-awesome.css

Cannot find an istance of `.small` in font-awesome's css.

That class comes from bootstrap, could you please check?

**Comment by govorov** [comment]
You're right, sorry. There's possibly a bug with sourcemap in my build configuration.
Closing this.
