### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by lucasdf** [FortAwesome/Font-Awesome#11108]
The [download link](http://fontawesome.io/assets/font-awesome-4.7.0.zip) for the zipped assets that is displayed on the [Get Started](http://fontawesome.io/get-started/) page is broken (404 file not found).

**Comment by nguyen-khoa** [comment]
Same problem

**Comment by BusyRich** [comment]
Having same issue. Using latest Chrome on Win 10.

**Comment by tagliala** [comment]
Could you please check again?

I think this has been fixed via https://github.com/FortAwesome/Font-Awesome/commit/d0dddaddbe884d66924a4f1570b5075a594e0ef3

**Comment by lucasdf** [comment]
@tagliala yes, it has been fixed.
