### ISSUE TITLE
where is the git-svn ?

### ISSUE THREAD

**Issue by sampsonliu** [FortAwesome/Font-Awesome#11100]
http://www.iconfont.cn/search/index?q=svn

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As you know, there is a request for the `svn` icon here: #7488 

Take a look to the [Customize Font Awesome wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) to understand how requests work

Please also take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Hope it helps
