### ISSUE TITLE
Grammar on Getting Started Page

### ISSUE THREAD

**Issue by benbotto** [FortAwesome/Font-Awesome#11109]
In the sentence that reads, "Then go complain to whomever decided your project needs IE7 support," the pronoun is wrong.  Even though it follows a proposition, it should be "whoever" in this case because it's the subject of the verb "decided."  As in, "she decided your project needs IE7 support."

Thanks for the great project!

**Comment by tagliala** [comment]
Hi,

Thanks for being part of the Font Awesome Community.

I'm not an English native speaker so I'm not confident in submitting a PR.

I'm going to assign Rob and Dave but if there are more feedbacks I will submit a fix by myself

**Comment by robmadole** [comment]
Thanks @benbotto for the correction. @tagliala I'll make the fix real quick.

**Comment by robmadole** [comment]
945e8bbd5e2dec63fe08cd06a243b422e9824e3e
