### ISSUE TITLE
Icon Request: fa-traxsource

### ISSUE THREAD

**Issue by thechefmusic** [FortAwesome/Font-Awesome#11103]
https://goo.gl/images/6qSCpp

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7919, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
