### ISSUE TITLE
Icon Request: fa-itunes

### ISSUE THREAD

**Issue by thechefmusic** [FortAwesome/Font-Awesome#11102]
https://goo.gl/images/kOyPlT

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #919 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
