### ISSUE TITLE
Icon Request - icon-Gitter

### ISSUE THREAD

**Issue by ArtyAastha** [FortAwesome/Font-Awesome#11113]
I need to use a Gitter icon for a webpage. Kindly add one. Thank you.
![image](https://cloud.githubusercontent.com/assets/26025751/26439657/bb0efba6-4146-11e7-91a2-4c2c7d1b8fc6.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6535, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
