### ISSUE TITLE
Icon Request: fa-delivery

### ISSUE THREAD

**Issue by ByrdeO** [FortAwesome/Font-Awesome#11110]
I would use it to represent delivery.

![delivery](https://cloud.githubusercontent.com/assets/28919612/26394112/2f518500-406c-11e7-87cb-60a4e1ea5e49.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think http://fontawesome.io/icon/truck/ do the job

If you need a "free delivery" icon, please fix the title.

Please keep in mind that the word "FREE" on the truck side, will barely fit 16px icon size and it is not international. We are trying to keep font awesome as international as possible

**Comment by tagliala** [comment]
no feedback, closing here
