### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by Superola86** [FortAwesome/Font-Awesome#11112]
I want this icon to link to my discord server, same way facebook and twitter, and teamspeak and so on :)

![discord_logo1600](https://cloud.githubusercontent.com/assets/16548971/26424745/93e4fa22-40d2-11e7-94bd-c74c03b5ee5e.png)

https://discordapp.com/ = the site to the program :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7574, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by Superola86** [comment]
okey, thanks, found it:)
