### ISSUE TITLE
Icon request: icon-stock-house

### ISSUE THREAD

**Issue by zeespogeira** [FortAwesome/Font-Awesome#11118]
Hi 
can you please create an icon for stock house?
the practical case is a warehouse that stores goods.

found this icon png as example

![factory-stock-house](https://cloud.githubusercontent.com/assets/3593156/26517122/2434d3e6-428a-11e7-9aa6-c6892de59eeb.png)

Thanks :)

**Comment by krilllind** [comment]
What would be the practical use for an icon like that? FontAwesome has bothe the [Home](http://fontawesome.io/icon/home/) and the [industry](http://fontawesome.io/icon/industry/), maybe onw of them could sute your needs?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4560, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
