### ISSUE TITLE
Old Facebook f still in use?

### ISSUE THREAD

**Issue by malberty** [FortAwesome/Font-Awesome#11115]
It seems that Facebook no longer wants anyone to use the f symbol alone according to https://en.facebookbrand.com/assets/f-logo

Why is the f still offered through font awesome if it is against their brand?
http://fontawesome.io/icon/facebook/

It would make it easier on developers if this just converted to the approved logo rather than update our code with the new css class.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this answer is still valid: https://github.com/FortAwesome/Font-Awesome/issues/1966#issuecomment-39986071

Hope it helps, closing here
