### ISSUE TITLE
JSONfeed.org icon

### ISSUE THREAD

**Issue by darkenedsky** [FortAwesome/Font-Awesome#11111]
https://jsonfeed.org/graphics/icon.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11106, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
