### ISSUE TITLE
I noticed font awesome icons still work even without @font face declaration in css

### ISSUE THREAD

**Issue by drnkwati** [FortAwesome/Font-Awesome#11114]
Can someone explain why fa icons still work even without @font face URL in css
I was trying to embed just a few to use in a small project and noticed this behaviour.
All the other css generated by sass are left in tact only the .../font-awesome/scss/path was commented.
I had not included any base64 encoded fonts. Just those fa generated css without the path
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I guess you have Font Awesome installed on your system.

https://jsfiddle.net/tagliala/yxaj57n5/

![image](https://cloud.githubusercontent.com/assets/556268/26447042/fadc6444-4146-11e7-807d-887e5088e3e0.png)

Hope it helps, closing here but feel free to comment if I'm wrong

**Comment by drnkwati** [comment]
Ohh yes. I installed for use with Photoshop projects.
