### ISSUE TITLE
how to change the font-weight property of the icon

### ISSUE THREAD

**Issue by Jerry-goodboy** [FortAwesome/Font-Awesome#11121]
I wanna thin the icon, but when I change the font-weight property, nothing to change, so what shall I do?

**Comment by Jerry-goodboy** [comment]
@rmm5t @scudco @jerodsanto @LightGuard @davidcelis

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I wanna thin the icon, but when I change the font-weight property, nothing to change, so what shall I do?

Hi, different font-weights are not supported. If you founded Font Awesome 5, you will get a Thin Icon Style with FA Pro, but I suppose it will be a different font file to keep the size small, so font-weight will not be supported too.

There is a request for thin icons at #1733 but please keep in mind that this requires a complete rewrite of each icon in the set.

The best you can do at the moment, is to use another icon set if FA doesn't match your design choices

Please also consider [buying FA 5 Pro](https://fontawesome.com/) or [Black Tie - Light](https://blacktie.io/products/light)

[NOTE: I'm not involved in the commercial part of Font Awesome]

Hope it helps

**Comment by davidcelis** [comment]
@Jerry-goodboy I couldn't help but notice that you @mention a bunch of completely random contributors every time you open an issue on a repository. Please don't do this, it's super spammy and you're never even really @mentioning maintainers. Just random people who may have opened an issue at one point and have never committed code.
