### ISSUE TITLE
Icon request: fa-laravel

### ISSUE THREAD

**Issue by bipin244** [FortAwesome/Font-Awesome#11126]
I want to icon for technology like laravel,code igniter,php ,jquery etc for my portfolio website

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
