### ISSUE TITLE
Icon request: fa-sneeze

### ISSUE THREAD

**Issue by DFreds** [FortAwesome/Font-Awesome#11132]
I would like this icon to depict someone's allergies similar to the one below.

![image](https://cloud.githubusercontent.com/assets/11878569/26731892/8c59ddba-4783-11e7-8822-af63edf14c6c.png)

**Comment by DFreds** [comment]
So uh.... turns out I don't really need this anymore. Maybe someone else does... lol ⏲️

**Comment by tagliala** [comment]
Oh, we now have https://fontawesome.com/v5.15/icons/head-side-cough?style=solid

It is not a sneeze, but it is quite similar

**Comment by DFreds** [comment]
Oh, that would have been perfect! Alright, closed.
