### ISSUE TITLE
Icon Request: Google Cast

### ISSUE THREAD

**Issue by mikhailmatveev** [FortAwesome/Font-Awesome#11137]
Hello! Could you add "Google Cast" icon? It looks like this https://avatars0.githubusercontent.com/u/4933765?v=3&s=200. I would be glad about this!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Duplicate of #1804? Chromecase has been renamed to Google Cast?

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by mikhailmatveev** [comment]
Sorry, I didn't see it in search maybe. It feature used in YouTube service for watching videos on connected devices (TV's etc.). I think there are the same issues. Thanks! I'll be waiting this icon for using in my app.

**Comment by tagliala** [comment]
No problem

Please add a 👍 reaction to #1804

I'm closing here
