### ISSUE TITLE
New Icon Request: Theatre Seat

### ISSUE THREAD

**Issue by SubinVs** [FortAwesome/Font-Awesome#11143]
Currently doing a project to show the theatre seat as occupied or unoccupied seat availability.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #155 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
