### ISSUE TITLE
address book icon no longer works

### ISSUE THREAD

**Issue by tamutti** [FortAwesome/Font-Awesome#11140]
As of 4.7 address book isn't available any more. These variations do not show anything

`<i class="fa fa-address-book" aria-hidden="true"></i>`
`<i class="fa fa-address-book"></i>`
`<i class="fa fa-address-book-o"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot confirm: https://jsfiddle.net/tagliala/s3msxtbe/16/

Please take another look at our troubleshooting guide. I suspect you are loading two different versions of font awesome and the older one is getting the priority

**Comment by skydevelopers** [comment]
Here are some steps to follow : 
1. Update the font-awsome.css file the older version css may not contain new fonts
2. Also update files inside your font folder. Download [font awsome](https://fontawesome.com/v4.7.0/assets/font-awesome-4.7.0.zip)

3. Ctrl+shift+R  hard refresh your page
 
Hope the above points help.
[Skydevelopers](www.skydevelopers.net)
