### ISSUE TITLE
Icon fa-universal-access not displaying

### ISSUE THREAD

**Issue by c00p3r** [FortAwesome/Font-Awesome#11145]
Icon fa-universal-access not displaying
![_029](https://user-images.githubusercontent.com/5259532/26917063-6a5ee3de-4c35-11e7-92b9-bf50a101c8ee.png)
![1_030](https://user-images.githubusercontent.com/5259532/26917103-9c6bcf0e-4c35-11e7-83eb-fdf2d0aae4ed.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here
