### ISSUE TITLE
fa-hashtag don't work

### ISSUE THREAD

**Issue by dave993** [FortAwesome/Font-Awesome#11144]
hi and thank you for your work.

I'm using font awesome on wordpress blog with latest version.
All font awesome icon work well but i've problem with "fa fa-hashtag".

It do not work, do not display :( it's a bug?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Pay particular attention to point 5

Hope it helps

Closing here

**Comment by dave993** [comment]
Thank you for answer. I'm not using plug in which are loading older/modified versions of Font Awesome.

and so? sorry i'm not expert, please help me

**Comment by tagliala** [comment]
@dave993 Sorry. I understand you but this is not a support forum

Please consider using stackoverflow

**Comment by dave993** [comment]
Solved. After update new fontawesome files, it's enough pure the site cache. ty for help

**Comment by tagliala** [comment]
glad you solved 👍
