### ISSUE TITLE
Icon request: fa-cookie / fa-cookie-o

### ISSUE THREAD

**Issue by cryocreations** [FortAwesome/Font-Awesome#11149]
Useful for food and browser cookies.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8158 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
