### ISSUE TITLE
Icon Request: icon-pocket

### ISSUE THREAD

**Issue by timngwena** [FortAwesome/Font-Awesome#1115]
An icon for sharing to Pocket (getpocket.com). Would be great to use it alongside other brand icons. The next web have something on their site that uses similar syntax to font-awesome but can't figure out if it's a custom build. See image.
![screen_shot_2013-05-18_at_19 33 50](https://f.cloud.github.com/assets/955277/521992/b411daae-bfe9-11e2-9adb-f5c607ac0bde.png)

**Comment by leo-o** [comment]
+1

**Comment by dgwyer** [comment]
+1

**Comment by marcelismus** [comment]
+1

**Comment by adinanp** [comment]
+1

**Comment by mjchamplin** [comment]
+1

**Comment by edmarriner** [comment]
+1

**Comment by Mr-Zer0** [comment]
+1

**Comment by Cam** [comment]
+ ∞

**Comment by cqcn1991** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch.

**Comment by pjf** [comment]
You rock!! <3

**Comment by voronianski** [comment]
finally! after more than 2 years of waiting :+1:

**Comment by timngwena** [comment]
Perfect :)
