### ISSUE TITLE
Icon Request: fa-freelyshout icons

### ISSUE THREAD

**Issue by markayim** [FortAwesome/Font-Awesome#11157]
Hello. I examined Font Awesome symbols, but I could not find the Freelyshout symbol. Would you please add the Freelyshout icon between the Font Awesome icons.
You can find the Freelyshout symbols this address. 
Icon Request: **Freelyshout Iconset** [http://info.freelyshout.com/Iconset.html#FreelyshoutIconset](http://info.freelyshout.com/Iconset.html#FreelyshoutIconset)

**Freelyshout** [https://freelyshout.com](https://freelyshout.com)
[Freelyshout Color](http://info.freelyshout.com/index.html#FreelyshoutLogos)
HEX: [#0076A3](http://www.color-hex.com/color/0076a3)
CMYK: 89/46/19/1
RGB: 0/118/163
HSB: 197/100/64

![freelyshout_app_logo_](https://cloud.githubusercontent.com/assets/28358834/25674593/111a714c-3044-11e7-97f2-a91f15a06266.png)

![freelyshout_app_newicon_](https://cloud.githubusercontent.com/assets/28358834/25674601/18cb0460-3044-11e7-9873-6e125547100b.png)

![freelyshout_font_icon-2](https://cloud.githubusercontent.com/assets/28358834/25673902/b0031d84-3041-11e7-9faa-b09f447bd826.png)

![freelyshout_font_icon-4](https://cloud.githubusercontent.com/assets/28358834/25673926/be88043c-3041-11e7-9f13-b3189c21caef.png)

![freelyshout_font_icon-8](https://cloud.githubusercontent.com/assets/28358834/25673929/c079ee2c-3041-11e7-9d1e-14f2c4ea9940.png)

you can download the Freelyshout icons from here.
[Freelyshout Font Icons.zip](https://github.com/FortAwesome/Font-Awesome/files/974253/Freelyshout.Font.Icons.zip)

Thank You Font-Awesome

## **Shout freely like a human - Freelyshout [https://freelyshout.com](https://freelyshout.com)**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You already requested a freelyshout icon at #11018

If you want to know how requests work, please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Closing here

**Comment by markayim** [comment]
@tagliala hi, Icon Request: fa-freelyshout icons  
What do I need to do to add an icon.
I did not understand.

**Comment by tagliala** [comment]
Hi @markayim , please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome to understand how requests work and to know how you can make a custom build
