### ISSUE TITLE
fa-free-code-camp icon not working

### ISSUE THREAD

**Issue by shankarvaidya** [FortAwesome/Font-Awesome#11150]
Hi Team,
I am trying to use fa-free-code-camp icon but nothing is displayed.
PFB my code:
`<i class="fa fa-free-code-camp"></i>`
I also tried:
`<i class="fa fa-free-code-camp" aria-hidden="true" ></i>`
All other icons are working properly except this one.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Maybe you are using (directly or indirectly, through plugins) an older version of Font Awesome.

Hope it helps

Closing here

**Comment by shankarvaidya** [comment]
Issue is resolved. Sorry for my silly mistake
