### ISSUE TITLE
Icon Request: fa-graph_number

### ISSUE THREAD

**Issue by MyIndicators** [FortAwesome/Font-Awesome#11162]
Dear FontAwesome, 

I am one of your customers who has purchased your product. 

I would love to request these icons as I unable to find the similar icons. The reason for request even some of the icons are differ slightly from the existing FontAwesome Icons but the differences are represent specific function of our webapplication. Thank you very much for your consideration. Looking forward to hear from you :)

[Iconsforrequest.docx](https://github.com/FortAwesome/Font-Awesome/files/1067751/Iconsforrequest.docx)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by MyIndicators** [comment]
Hi, 
Thank you. 
I will edit it and make a new request.
