### ISSUE TITLE
Icons not showing with child theme

### ISSUE THREAD

**Issue by luizbriganti** [FortAwesome/Font-Awesome#11168]
Hi, 
I have a child-theme and with it activated icons don't show. I've also tried to paste the script for loading fontawesome fonts, but still I see blank squares. 

What should I do? 
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is not a support forum, please consider using stackoverflow. You may consider asking for support to your theme developer.

If you think there is an issue with Font Awesome or with the CDN, please provide a reduced test case which shows the issue. 

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues).
