### ISSUE TITLE
Icon Request: fa-codefights-square

### ISSUE THREAD

**Issue by annguyendang14** [FortAwesome/Font-Awesome#11176]
![nhcretje_400x400](https://user-images.githubusercontent.com/13951407/27153305-8ec2584c-5116-11e7-8853-7a4a9dec3857.png)

I want to use this icon for my website to be in sync with the Facebook, Mail, GitHub icon I already using (I'm using the square icon for all of those)

**Comment by btargac** [comment]
is this request planned or not? I would also like to use this icon on my personal web site

**Comment by aethior** [comment]
>In 2018, the company changed the name of its platform from CodeFights to CodeSignal, and introduced a Coding Score that developers could share with technical recruiters, based on challenges completed on CodeSignal. ([more info](https://en.wikipedia.org/wiki/CodeSignal))

cc/ @tagliala

**Comment by tagliala** [comment]
I prefer to close here. If there is interest in CodeSignal, please open a new request
