### ISSUE TITLE
Icon Request: fa-1, fa-2, fa-3, fa-4, fa-5, fa-6, fa-7, fa-8, fa-9

### ISSUE THREAD

**Issue by adrienneSDSU** [FortAwesome/Font-Awesome#11175]
Hello, the way we currently use Font-Awesome in our CMS is to only allow an icon to be placed in an area. If it isn't a fa-icon then it won't show. With my current website design, I need to place in number icons. I can't alter the content to allow non fa-icons to appear. I thought the numbers could be clear easy to read sans-serif, non-frilly numbers.
![capture](https://user-images.githubusercontent.com/29438862/27146665-ee7d016a-50ee-11e7-8771-a0b32f4057b2.JPG)

**Comment by adrienneSDSU** [comment]
examples of the numbers:
![3](https://user-images.githubusercontent.com/29438862/27146707-1845b7b2-50ef-11e7-894c-54ea9f056888.gif)
![4](https://user-images.githubusercontent.com/29438862/27146704-182faaa8-50ef-11e7-8926-df5eff3fc728.gif)
![5](https://user-images.githubusercontent.com/29438862/27146706-1842e726-50ef-11e7-81a8-136e7f933f87.gif)
![6](https://user-images.githubusercontent.com/29438862/27146705-1833ebae-50ef-11e7-814f-459beb752210.gif)
![7](https://user-images.githubusercontent.com/29438862/27146708-184613c4-50ef-11e7-93ca-edd10c6c3217.gif)
![8](https://user-images.githubusercontent.com/29438862/27146710-184c1620-50ef-11e7-833d-3e6130c47971.gif)
![9](https://user-images.githubusercontent.com/29438862/27146709-184820e2-50ef-11e7-8307-4fa5ed98412e.gif)
![1](https://user-images.githubusercontent.com/29438862/27146711-184e2096-50ef-11e7-9275-7f9d4fd6e8f6.gif)
![2](https://user-images.githubusercontent.com/29438862/27146712-186c4f26-50ef-11e7-8f9c-7d269e0da088.gif)

**Comment by aethior** [comment]
Characters were discussed in the past: #5019.

**Comment by adrienneSDSU** [comment]
The solution does not work with my cms.

**Comment by tagliala** [comment]
@adrienneSDSU go for custom css. It will work

Example: http://jsfiddle.net/tagliala/c6W7M/

**Comment by adrienneSDSU** [comment]
Actually, none of the solutions provided work with the CMS we use.
