### ISSUE TITLE
Icon Request: fa-cloudflare

### ISSUE THREAD

**Issue by WebVeteran** [FortAwesome/Font-Awesome#11170]
Use Case: For showing Cloudflare option statuses, API calls, references, etc.
Example: Cloudflare's logo:
![cloudflare](https://user-images.githubusercontent.com/40175/27112488-862b0198-5085-11e7-81e8-9e4ec7c0c0c4.png)

Thank you again.

**Comment by aethior** [comment]
Duplicate of #5554.
