### ISSUE TITLE
Icon Request: icon-hotel (?)

### ISSUE THREAD

**Issue by xpertHands** [FortAwesome/Font-Awesome#11188]
hotel

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does http://fontawesome.io/icon/h-square/ fit your needs?

**Comment by UrsBeeli** [comment]
Or alternatively: [fa-bed](http://fontawesome.io/icon/bed)

**Comment by tagliala** [comment]
No feedback, closing here
