### ISSUE TITLE
ERR_INSECURE_RESPONSE error when going to https://use.fontawesome.com/c9f66ac4f1.js

### ISSUE THREAD

**Issue by hshroff** [FortAwesome/Font-Awesome#11185]
We're getting ERR_INSECURE_RESPONSE error when going to https://use.fontawesome.com/c9f66ac4f1.js

This worked fine up until this morning arount 8:00am EST.

Looks like the SSL certificate is invalid or expired.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11183. It should be resolved.

If it isn't for you please comment on the above issue

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by hshroff** [comment]
Confirmed this is working again.  Thanks for the quick response and resolution.
