### ISSUE TITLE
use.fontawesome.com HTTPS error

### ISSUE THREAD

**Issue by cylkee** [FortAwesome/Font-Awesome#11183]
Icons not displayed.  Found cause:

use.fontawesome.com uses an invalid security certificate.The certificate expired on 15 June 2017 at 13:00. The current time is 15 June 2017 at 13:23.Error code: SEC_ERROR_EXPIRED_CERTIFICATE

If I download the .js and generated .css over HTTP and use these files, icons appear as normal.

Tested in Firefox 53.

**Comment by connormcwood** [comment]
https://use.fontawesome.com/d3539ca1f0.js

Came to say this. Favicon icon has been removed or disappeared. 
Failed to load resource: the server responded with a status of 403 ()

**Comment by JamesMPrince** [comment]
Same for us.  Icons not appearing, using CDN method.

**Comment by jg2703** [comment]
Same again... sorry just typing out my issue!!

**Comment by lordcoste** [comment]
Same here.

**Comment by JamesMPrince** [comment]
Downloading them fixes the issue, but not ideal.

**Comment by gasulliv** [comment]
That sucks, but at least there is a work around! Thanks for letting us know, hopefully the CDN will be back up soon!!

**Comment by JamesMPrince** [comment]
I think they're back now?!

**Comment by jg2703** [comment]
Looks like they're up and running. I'll close this issue now unless anyone else is still having issues.

**Comment by gasulliv** [comment]
awesome! Let me check it out!

**Comment by Stereoide** [comment]
Yup, back up again. Thanks!

**Comment by tagliala** [comment]
@robmadole could you please confirm that everything is fine?

**Comment by robmadole** [comment]
This is resolved now. Sorry about that folks.

**Comment by tf-venegas10** [comment]
It happened again...

**Comment by brunopardim** [comment]
Hi Fort Awesome 
Team,

It happened again this problem.

Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
kit-free.fontawesome.com/releases/latest/css/free-v4-font-face.min.css:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
kit-free.fontawesome.com/releases/latest/css/free.min.css:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
kit-free.fontawesome.com/releases/latest/css/free-v4-font-face.min.css:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
kit-free.fontawesome.com/releases/latest/css/free.min.css:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

**Comment by tagliala** [comment]
Hi, thanks for reporting this. We are aware of the situation and StackPath, our CDN provider, is pushing a fix.

Quoting from: https://status.stackpath.com/incidents/22c999cbl1nh

> We have begun rolling out an update that will resolve the ongoing SSL errors StackPath customers are experiencing. We will continue to provide updates as this process continues forward.

Ref:
- https://status.stackpath.com/incidents/22c999cbl1nh
- https://status.fortawesome.com/

**Comment by brunopardim** [comment]
> 
> 
> Hi, thanks for reporting this. We are aware of the situation and StackPath, our CDN provider, is pushing a fix.
> 
> Quoting from: https://status.stackpath.com/incidents/22c999cbl1nh
> 
> > We have begun rolling out an update that will resolve the ongoing SSL errors StackPath customers are experiencing. We will continue to provide updates as this process continues forward.
> 
> Ref:
> 
>     * https://status.stackpath.com/incidents/22c999cbl1nh
> 
>     * https://status.fortawesome.com/

Tks @tagliala :)

**Comment by mengnans** [comment]
Today it happens to one of my clients, it happens on her home laptop and work desktop.
