### ISSUE TITLE
Cheatsheet Feature Request

### ISSUE THREAD

**Issue by simply-phil-1** [FortAwesome/Font-Awesome#11189]
Now that the list of icons is getting rather large, can you split the Cheatsheet into two: One for company logos/icons, and one list for everything else.

**Comment by sensibleworld** [comment]
You can now select the "cheatsheet" filter from any search view.

<img width="1580" alt="CleanShot 2022-09-12 at 15 51 01@2x" src="https://user-images.githubusercontent.com/529604/189743086-f9bf0c47-b47b-4b47-83de-07722731a6c2.png">
