### ISSUE TITLE
Empty Squares on iOS

### ISSUE THREAD

**Issue by jasonhibbs** [FortAwesome/Font-Awesome#1119]
I’m not getting any icons to display in Mobile Safari, iOS 6.1.3 — not iPhone nor iPad.

I’m not doing anything out of the ordinary here, so I can’t diagnose it, and haven’t found a fix.

Tried LESS and CSS, minified and not, files. No problems in Chrome and Safari.

**Comment by adrian7** [comment]
It seems to occur especially in "Private" browsing mode.

**Comment by inspire22** [comment]
Any fixes/workarounds for this?  I'm getting a lot of complaints from my iphone users about blank icon boxes after implementing font-awesome for our mobile navigation.

**Comment by jasonhibbs** [comment]
On much reflection, I suspect my issue was due to the font path being incorrect. With the font installed on my desktop it appeared to work correctly, but without the font installed on my mobile no characters were found in the default font.

**Comment by da-vid** [comment]
I've continued to face this issue over the last several months.  Had been simply linking the publically-CDN-hosted CSS file to implement.  I still consistently encountered this issue when first loading my page in iOS.  Tried self-hosting the CSS and fonts to see if would make a difference.  No luck.

Further googling seemed to indicate that iOS, while compatible with a number of font formats, seems to prefer SVGs.  I removed the reference to the SVG font in the CSS, and that seems to consistently work now.  

Suspect this is a bug in the way iOS Safari handles SVG fonts, but I can't prove it.

**Comment by cosme-benito** [comment]
I also have this problem with iOS Safari. Sometimes (usually the first load or so) I get squares, but after a while the icons show up. This doesn't seem to happen with Glyphicon so it's hard to blame iOS for it...

**Comment by anquinn** [comment]
I'm currently having this issue as well. I've tried the CDN, self hosting and the sass Gem. They all show are squares on iOS Safari. Sometimes they show after a while, often not.

**Comment by N1bbler** [comment]
An obvious tip, but triple check the relative paths to font awesome. In my case, somehow it was magically working on the desktop, but not on IOS. It turned out to just be a relative path problem. Once fixed, all was well across all platforms.

**Comment by gokmenkurtoglu** [comment]
This will be solve the problem;
`@media screen and (-webkit-min-device-pixel-ratio:0) {
  @font-face {
      font-family:'FontAwesome';
      src: url('fonts/fontawesome-webfont.svg?v=4.5.0#fontawesomeregular') format('svg');
  }
} `

**Comment by DoctorFitch** [comment]
@gokmenkurtoglu You're a God ! It works ! Thank's you so much

**Comment by eoinkelly** [comment]
I had this problem but it was because I had an adblocker setup on the device. Just leaving this comment here so you won't spend 30 mins puzzling over this like I did before checking that. ¯\_(ツ)_/¯

**Comment by hutilicious** [comment]
I couldn't find a solution for this problem. So i broke down my css, bits by bits.
The "solution" I found was removing Google Fonts from my project, and remove font declarations on selectboxes. Sounds weird, I know. This might help anyone searching for a solution, check your font declarations.

**Comment by cosme-benito** [comment]
I actually have Google Fonts on my project as well, that might be causing
it...
