### ISSUE TITLE
Alidad

### ISSUE THREAD

**Issue by Alidad3250** [FortAwesome/Font-Awesome#11199]
all icons are great, It would be great to add new icon "Clear" using as broom image. is not same as delete.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #239 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
