### ISSUE TITLE
Icon request: neighborhood

### ISSUE THREAD

**Issue by tsaixing** [FortAwesome/Font-Awesome#11202]
I've noticed that there is a single house icon (home), but not a group of houses (neighborhood)

I think this would be very useful to have for all things neighborhood + community related. Especially when there are cases where one needs to distinguish between the singular and plural form of a home. 

Thank you for all your hard work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9367, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
