### ISSUE TITLE
Request Icon - Kalaage [Brand] [www.kalaage.net]

### ISSUE THREAD

**Issue by aasseff** [FortAwesome/Font-Awesome#11204]
Kalaage is an ERP for Publications and a social network for writers and publications.
![13886446_1190113291040465_5802157978164130727_n](https://user-images.githubusercontent.com/29597075/27380965-b1c7d1e0-569e-11e7-86c3-f8b573923888.png)

**Comment by aethior** [comment]
The domain ([link](http://www.kalaage.net/)) is currently down and the [twitter account](https://mobile.twitter.com/kalaage_net) is inactive since 2019.

cc/ @tagliala
