### ISSUE TITLE
Site Design Suggestion: Current Website Design

### ISSUE THREAD

**Issue by Adondriel** [FortAwesome/Font-Awesome#11207]
I understand you guys are REALLY excited about the new FA5, I am too, I even pre-purchased it, but do you REALLY need that many banners? AND the email subscription list thing? 
![image](https://user-images.githubusercontent.com/1113496/27339028-a5a49e3e-55a4-11e7-9d18-f789ba8547ba.png)
Look at how pretty and easy to use the site is when I removed all the space-wasting crap from it! 
![image](https://user-images.githubusercontent.com/1113496/27338855-3f2dda6c-55a4-11e7-87b1-97e7db64860e.png)
Makes it so much easier to use.
Issues I have with the current site design:

1. I mistake the email subscription box thing, as the icon search box, why is this thing the first box on the icon page? This should be in the footer, not the first thing on the page.
2. Giant banners/headers take up so much space, I can't actually see what I'm looking for.
3. No icon search box on homepage, Why?

What I think a good solution would require:

1. Remove the stupid FA5 banner, OR Make it closeable, and remember when I close the banner, so it doesn't pop back up again.
2. Remove the stupid email subscription box from the top of the page, put it in the footer, or somewhere else.
3. put an icon search box on the homepage!
4. If you don't want to remove the page banner (The thing that says stuff like "The Icons!") at least make it take up less space... like, why does it have to take up half of the total page space? Also, isn't this why the navbar says the word "icons" do you really need to re-iterate that the current page is for icons? I don't think it's really needed... in the slightest. Just make the navbar slightly larger, to make the buttons easier to click.

Obviously this is just my opinion, what does everyone else think?

(If you are a member of the FA5 repo, you may have already seen this, this is because I followed their advise and moved it from there to here, because it doesn't really pertain to FA5 for the time being.)

Here is the uBlockOrigin filter for getting rid of the banners that I felt were unneeded:

```
! 6/20/2017, 10:33:11 AM http://fontawesome.io/icons/
fontawesome.io##.hidden-print.jumbotron-ad.jumbotron

! 6/20/2017, 10:33:17 AM http://fontawesome.io/icons/
fontawesome.io###social-buttons

! 6/20/2017, 10:33:48 AM http://fontawesome.io/
fontawesome.io##.hidden-print.jumbotron-carousel.jumbotron

! 6/20/2017, 10:34:05 AM http://fontawesome.io/icons/
fontawesome.io###banner

```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sharing your ideas

> I mistake the email subscription box thing, as the icon search box, why is this thing the first box on the icon page? This should be in the footer, not the first thing on the page.

This is a duplicate. There is at least this request: #10536, but there should be other requests about this. It happens to me too, a lot of times :)

**Comment by sensibleworld** [comment]
Thank you for the feedback! Looks like the email form is no longer on the FA 4 website. The banner remains, but it's important to us that we direct people to FA 5, as it's the most update-to-date and supported version of Font Awesome.
