### ISSUE TITLE
Icon Request: fa-invoice

### ISSUE THREAD

**Issue by AndreiVen** [FortAwesome/Font-Awesome#11219]
Some invoice file would help, like the excel file but with diffrent content (invoice-like content)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #477 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
