### ISSUE TITLE
Icon Request: fa-book-stack

### ISSUE THREAD

**Issue by nadiawillum** [FortAwesome/Font-Awesome#11213]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is a duplicate of #5098, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

If it isn't a duplicate, please clarify and I will consider reopening

Please also take a look at our [Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

Closing here
