### ISSUE TITLE
Icon Request: fa-algolia

### ISSUE THREAD

**Issue by michealjroberts** [FortAwesome/Font-Awesome#11210]
An icon for the Algolia searching tool. 

[Algolia Icon SVG Example](https://www.dropbox.com/s/jdcpqpj3l9x91fr/algolia-logo.svg?dl=0)

**Comment by tagliala** [comment]
Hi!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
