### ISSUE TITLE
Using icons with lists unintentional creates ::before

### ISSUE THREAD

**Issue by matsgm** [FortAwesome/Font-Awesome#11212]
Using icons and lists unintentional creates ::before which shows several icons.
Best seen in this codepen: https://codepen.io/matsgm/pen/GEEEME

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the example provide is missing the `</i>` close tag.

Hope it helps

Closing here

**Comment by matsgm** [comment]
Oh... Thanks :)
