### ISSUE TITLE
Icon Request: fa-parking

### ISSUE THREAD

**Issue by morislubin** [FortAwesome/Font-Awesome#11228]
Hi! Could you add please a Parking Icon? [P] Someting like that...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1559, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by morislubin** [comment]
Ok! Thanks!
