### ISSUE TITLE
Telegram issue

### ISSUE THREAD

**Issue by ArnoldGarry256** [FortAwesome/Font-Awesome#11226]
I can't seem to use Telegram icon but can use the rest. Anyone facing similar issue?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Probably you are using an old version of font awesome.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here
