### ISSUE TITLE
Icon Request: fa-bed-empty

### ISSUE THREAD

**Issue by ratios77** [FortAwesome/Font-Awesome#11225]
Hi Font-Awesome!
I would love to have a fa-bed-empty. So just like the fa-bed but without the person in it. I'm doing some work at a hospital and need to show an empty bed. Should be easy for you guys :) Thanks!
![bed-empty](https://user-images.githubusercontent.com/29683421/27513381-f6ea0c12-5931-11e7-89d1-1755ad958f85.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since we already have a bed, let's use #3629 for an empty bed

Closing here
