### ISSUE TITLE
Icon Request: fa-network-connected

### ISSUE THREAD

**Issue by ingared8** [FortAwesome/Font-Awesome#11232]
Icons Request for IOT 

1) fa-connected-to-network
2) fa-disconnected-from-network
3) fa-device-working
4) fa-device-error
5) fa-device_warning
5) fa-device-info-not_available

**Comment by webdes03** [comment]
+1, love this idea

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
