### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by TinMao** [FortAwesome/Font-Awesome#11238]
Hi, I have 12 icons for dentistry. Can I add them to you? I do not know English well, I'm sorry
![ic-desna](https://user-images.githubusercontent.com/29774606/27684460-6a7bba0e-5cca-11e7-8463-75fca05c50ab.png)
![ic-detski](https://user-images.githubusercontent.com/29774606/27684461-6a9454f6-5cca-11e7-85a1-526df0a97f7c.png)
![ic-diagnostika](https://user-images.githubusercontent.com/29774606/27684463-6a97ef80-5cca-11e7-8426-877e953b4c78.png)
![ic-gigiena](https://user-images.githubusercontent.com/29774606/27684462-6a973c48-5cca-11e7-86c3-4faebc73360a.png)
![ic-implant](https://user-images.githubusercontent.com/29774606/27684465-6a9b0594-5cca-11e7-8315-d503f97a6f46.png)
![ic-lechenie](https://user-images.githubusercontent.com/29774606/27684464-6a9898ea-5cca-11e7-98a9-40a8b6568855.png)
![ic-oms](https://user-images.githubusercontent.com/29774606/27684466-6a9c2e56-5cca-11e7-9dbd-88ebd4047917.png)
![ic-otbel](https://user-images.githubusercontent.com/29774606/27684468-6ab7ea74-5cca-11e7-9506-e246747c8c03.png)
![ic-prikus](https://user-images.githubusercontent.com/29774606/27684469-6ab81d50-5cca-11e7-8054-a3c8518e1296.png)
![ic-protez](https://user-images.githubusercontent.com/29774606/27684467-6ab68ee0-5cca-11e7-98ea-464fdda4ac3a.png)
![ic-udalenie](https://user-images.githubusercontent.com/29774606/27684470-6abaf7f0-5cca-11e7-8876-96156c23f079.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
