### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by mzabuawala** [FortAwesome/Font-Awesome#11231]
Hello,

First of all thank you for free icons :)

Would it be possible to add below icons in "Web Application Icons" section?
1) Step-in
2) Step-out
3) Step-over

Similar to the icons which are present in Chrome/Firefox browser developer tools.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
