### ISSUE TITLE
No icons for programming languages

### ISSUE THREAD

**Issue by sardul3** [FortAwesome/Font-Awesome#11240]
I believe the icons for programming languages are not included in the font-awesome package as of yet. It would be great to have them in the future!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take a look at the mfixx icon font for a comprehensive set of technologies: http://fizzed.com/oss/font-mfizz

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
