### ISSUE TITLE
Icon Request: fa-submit

### ISSUE THREAD

**Issue by filipe-maia** [FortAwesome/Font-Awesome#11251]
Hi,
I'm needing an icon for submitting information, example:
I have an application where the user needs to fill a large number of parameters, there is a save button for the user to save the already filled parameters, the save button is useful in case the user wants to leave before filling all the parameters and submitting the information (the user can return later and resume from where he left), the save button doesn't summit the information, the user is only allowed to submit the information once (all the parameters filled by the user shouldn't have mistakes).
Thanks.

**Comment by filipe-maia** [comment]
I was imagining a submit icon to be similar to the Enter key sign in a keyboard.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I was imagining a submit icon to be similar to the Enter key sign in a keyboard.

Please add a 👍 reaction to #1293 

Please also note that you could apply a 90-degree transformation to http://fontawesome.io/icon/level-down/ 

https://jsfiddle.net/tagliala/s3msxtbe/19/
