### ISSUE TITLE
icon request: icon-debian

### ISSUE THREAD

**Issue by snassar** [FortAwesome/Font-Awesome#1125]
icon-debian can be used for:
-   Decorative elements for websites pointing to Debian-related assets
-   For use on a site to indicate affiliation or affinity.

Icon:

![openlogo-nd-100](https://f.cloud.github.com/assets/4469008/529105/9515d152-c12c-11e2-996f-b2b9fa76a9a8.png)

**Comment by terceiro** [comment]
+1

please add both the plain version and a `-square` variant

**Comment by christian-momon** [comment]
:+1:

**Comment by hatclub** [comment]
+1 :)

**Comment by nIQnutn** [comment]
+1

**Comment by boolean-is-null** [comment]
+1

**Comment by satta** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by satta** [comment]
FYI: this is available elsewhere as part of https://github.com/Lukas-W/font-linux

**Comment by christian-momon** [comment]
The Microsoft Edge logo was very fast joined. Those of Debian, GNU project and Redhat wait for years.
How still doubt that Font-Awesome project is against free software?

**Comment by tagliala** [comment]
@christian-momon there are no plots

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome 

You can use svgs from the above repository shared by @satta

**Comment by kwendenarmo** [comment]
+1

**Comment by Petrouchka** [comment]
+1

**Comment by Angristan** [comment]
+1

**Comment by calumah** [comment]
+1

**Comment by souldanger** [comment]
+1

**Comment by romzie** [comment]
+1

**Comment by TCB13** [comment]
+1!!

**Comment by Petrouchka** [comment]
debian ico is now at https://forkawesome.github.io/Fork-Awesome/icons/

**Comment by christian-momon** [comment]
This Issue was created on 20 May 2013. More than 5 years to integrate a major GNU/Linux operating system ico. And the GNU ico is waiting again since 5 years too (#2665)  :disappointed: 
Admit it. Do you have a problem with free software? That's your right…

**Comment by jecky4an** [comment]
+1

**Comment by rickmills** [comment]
Kinda annoying that you've got Ubuntu, Fedora, CentOS, Redhat, Suse (how the heck did that make the cut?!) and the penguin but you've not got Debian, arguably more widely used than half of those.

**Comment by rhtyd** [comment]
Ping, any plans/update on this?

**Comment by Petrouchka** [comment]
Yes, it's here : https://forkaweso.me/Fork-Awesome/icon/debian/

**Comment by rickmills** [comment]
This really needs to make it to FA5 not a fork of FA4. Surely should be pretty simple for the one in the above mentioned fork to be pulled across?

**Comment by rhtyd** [comment]
Yes, if it already exists in a fork it would be great to get it included in the next FA release, PR please!

**Comment by Petrouchka** [comment]
It's better to use Fork Awesome, it's a more open project, where users can participate and are listened.

**Comment by Vndroid** [comment]
It has SUSE, Ubuntu, Redhat and so on, but it doesn't have Debian, It is very unreasonable.

**Comment by rhtyd** [comment]
It's good couple of years - can you comment @robmadole ?

**Comment by fedefrancescon** [comment]
+1

**Comment by SuperPat45** [comment]
+1

**Comment by chillje** [comment]
+1

**Comment by FloriaanLry** [comment]
up please !

**Comment by eaglei15** [comment]
+1

**Comment by TCB13** [comment]
Like seriously why do we have Ubuntu and Centos icons that are proprietary but not Debian? 

"The chart below identifies the overall usage of cloud-based preferences as of June 2019 via EC2 Statistics compiled from Amazon. "

![cloudstats](https://user-images.githubusercontent.com/6315832/101984070-cb53b400-3c76-11eb-95d7-850e049341e4.png)
from: https://www.liquidweb.com/kb/centos-vs-ubuntu-15-factors-to-consider/

According to Amazon in 2020 Debian is one of the most popular OS they've running one their datacenters. How some fontawsome doesn't have its icon?

**Comment by brunomartinspro** [comment]
+1!!!

**Comment by Brewd3v** [comment]
+1 Please

**Comment by aiso-net** [comment]
+1 Please

**Comment by frct1** [comment]
+1
Would be great

**Comment by kamaslau** [comment]
Please do deliver the Debian logo, it's one of the best Linux operation system distributions and the best community-maintained opensource one.

**Comment by sensibleworld** [comment]
I'll get this in the queue!

**Comment by TCB13** [comment]
> I'll get this in the queue!

Thank you!

**Comment by Neustradamus** [comment]
Important icon which must be here!

**Comment by sensibleworld** [comment]
This has been added: https://fontawesome.com/icons/debian?f=brands&s=solid

**Comment by Neustradamus** [comment]
@sensibleworld: Thanks a lot after 10 years, 2 months, 15 days! :)
