### ISSUE TITLE
Update CONTRIBUTING.md on How to create a new icon

### ISSUE THREAD

**Issue by dangiankit** [FortAwesome/Font-Awesome#11255]
As on date, 3041 of the 4110 open issues on this repo are for label:"new icon". Perhaps, update CONTRIBUTING.md with guidelines on how to create and contribute a new icon to Font Awesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from the [contributing guidelines for pull requests](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests):

> At the moment we are not accepting pull requests containing icons

If you need to create new icons, please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Closing here but feel free to comment

**Comment by dangiankit** [comment]
Perfect - the Wiki page addresses this issue. Thanks.
