### ISSUE TITLE
Does BlackTie have bt-headphones?

### ISSUE THREAD

**Issue by ianhd** [FortAwesome/Font-Awesome#11263]
I ordered and downloaded BlackTie Regular. I then used `<i class="btr bt-headphones"></i>` and nothing shows up. I do however see "fa fa-headphones" is an icon for FontAwesome. Any way that I could get an updated BlackTie Regular that includes `headphones`?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this question does not belong to here.

I'm trying to assign this issue to @davegandy @talbs and @robmadole, I hope they will provide you the proper way to manage this kind of issues

Regards

**Comment by robmadole** [comment]
@ianhd most likely Font Awesome 5 will supersede BlackTie. We will have "regular" and "light" styles for Pro that will work for this.
