### ISSUE TITLE
Icon Request: fa-lighthouse

### ISSUE THREAD

**Issue by nhbeachguy** [FortAwesome/Font-Awesome#11266]
Would love to see a couple of different lighthouse options.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5579, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
