### ISSUE TITLE
Icon request: icon-helmet icon-garage icon-brazillianflag

### ISSUE THREAD

**Issue by speshop** [FortAwesome/Font-Awesome#11260]
![bandeira-do-brasil---flag-brazil-152-63763](https://user-images.githubusercontent.com/29949529/27911361-305f90b0-622f-11e7-912c-a18bc7baa46a.png)
![favicon garage](https://user-images.githubusercontent.com/29949529/27911362-3062b8f8-622f-11e7-8482-c049d5acf8ed.png)

![helmet](https://user-images.githubusercontent.com/29949529/27911654-2c9a424e-6230-11e7-8032-a7b0bc70a674.jpg)

Hello, how are you?
I'm building a website and the theme i bought use fontawesome library.
I would be very thankful if you could add this icons so i can put in my site.
The color must be in black please.

Att

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

As per flags, please read https://github.com/FortAwesome/Font-Awesome/issues/1336#issuecomment-172343769

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
