### ISSUE TITLE
tag bullhorn as loudhailer

### ISSUE THREAD

**Issue by robhob** [FortAwesome/Font-Awesome#11261]
The bullhorn icon has been tagged as a megaphone but another common name for it is loudhailer.

Many thanks,

Rob

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thank for your suggestion.

After the release of FA5, we are monitoring icon searches: the most searched terms will be added as a filter, so if people is looking for loudhailer we will know and we will fix that.

Closing here
