### ISSUE TITLE
Icon request: icon-plus-circle-o

### ISSUE THREAD

**Issue by timtatt** [FortAwesome/Font-Awesome#11269]
Hi,

Really appreciate FontAwesome. It would be really cool if you could add some more -o icons. Such as a plus-circle-o etc.

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8316 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment]
Edit: duplicate of #2417
