### ISSUE TITLE
Icon Request: Import

### ISSUE THREAD

**Issue by ChrGriffin** [FortAwesome/Font-Awesome#11273]
Requesting an icon to indicate importing data or information from an external source. Essentially the same icon as the 'external-link' icons but with the arrow's direction reversed; example below.

![Example Image](http://www.clker.com/cliparts/b/5/e/e/1366374797725077757import.svg.med.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1020 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
