### ISSUE TITLE
Icon Request: Shapeways Brand

### ISSUE THREAD

**Issue by ChrGriffin** [FortAwesome/Font-Awesome#11274]
Requesting an icon for the Shapeways logo. Example image below.

![Example Image](https://static1.sw-cdn.net/files/cms/brand-resources/spark-blue-rgb-20141006.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1937, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
