### ISSUE TITLE
Icon request: sum/total

### ISSUE THREAD

**Issue by rwb196884** [FortAwesome/Font-Awesome#11288]
A capital sigma.
![download](https://user-images.githubusercontent.com/12090617/28162603-9afea6a0-67bf-11e7-85bc-13a6f1abf108.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4834 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by rwb196884** [comment]
Sorry. I did search for both `sum` and `total`.
