### ISSUE TITLE
Icon Request: fa-instagram-old

### ISSUE THREAD

**Issue by ArranGravestock** [FortAwesome/Font-Awesome#11283]
The old Instagram icons were so much better, I want to rebel and use their old logo! It's just so much better!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are doing our best to follow brand guidelines.

Please consider using an old version of font-awesome or a custom version if you need that icon: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Meanwhile, closing here
