### ISSUE TITLE
Icon Request: fa-note-slash

### ISSUE THREAD

**Issue by markrufino** [FortAwesome/Font-Awesome#11282]
Use cases for said request
• Counterpart for fa-music
• Mute button for features that play sounds that only need to be on or off. (rather than being able to be adjusted variably through a slider, so using fa-volume-off would be kinda awkward in this situation)

EDIT: Will be adding a preview since I pressed the submit button accidentally.
EDIT #2: Here's the preview:
![fa-music-slash](https://user-images.githubusercontent.com/30117352/28119206-93a25c18-6746-11e7-8ebc-995c3456a8ad.png)

**Comment by tagliala** [comment]
Refers to: #1181

**Comment by markrufino** [comment]
Thanks for the response.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/music-slash?style=solid
