### ISSUE TITLE
Icon Request: benchmark

### ISSUE THREAD

**Issue by rwb196884** [FortAwesome/Font-Awesome#11287]
![benchmark](https://user-images.githubusercontent.com/12090617/28162487-2279b896-67bf-11e7-8b62-439754b1e7b1.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by rwb196884** [comment]
What did I get wrong?

**Comment by tagliala** [comment]
Quoting from [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

> * Include a few use cases for your requested icon. How do you plan on using it?
> * Attach a single color image or two that represent the idea you're going for.
> * Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
