### ISSUE TITLE
Icon request: icon-Bloglovin'

### ISSUE THREAD

**Issue by danaikou** [FortAwesome/Font-Awesome#11294]
[Icon.zip](https://github.com/FortAwesome/Font-Awesome/files/1150529/Icon.zip)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2334, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by danaikou** [comment]
thanks!
