### ISSUE TITLE
Icon Request: fa-image-carousel

### ISSUE THREAD

**Issue by paulm17** [FortAwesome/Font-Awesome#11293]
I'm sure any of these will do:

![#1](https://d30y9cdsu7xlg0.cloudfront.net/png/201047-200.png)
![#2](https://d30y9cdsu7xlg0.cloudfront.net/png/258013-200.png)
![#2](https://d30y9cdsu7xlg0.cloudfront.net/png/665069-200.png)

**Comment by tagliala** [comment]
Related  to #855

**Comment by no1youknowz** [comment]
I respectfully disagree.

#855 relates to a gallery.  Which is usually a static row/column of images.

This is a carousel, which is a horizontal/vertically set of moving images, where at any time, only 1 is show.

Not related at all.

Also the OP of that post.  Has his images stacked.  There's a huge difference here.

**Comment by no1youknowz** [comment]
Looks like the guys who build Elementor know the difference between an image gallery and carousel.  /s

![#1](http://i.imgur.com/3NzpvMR.png)

**Comment by tagliala** [comment]
Hi,

> Not related at all.

Related doesn't mean they are duplicates.

People interested in Carousel may also be interested in "Gallery" or "Images" icon.

Hope it helps

**Comment by bmueller-sykes** [comment]
I'd like to add my voice to an `image-carousel` icon. I haven't found anything in FontAwesome's impressive library that really conveys "carousel" properly. @paulm17 suggestion from above seems like a suitable direction (though I don't know if those designs are subject to copyright concerns)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
https://fontawesome.com/icons/gallery-thumbnails?f=classic&s=solid
