### ISSUE TITLE
Letter request: Danish Capital letters Æ and Ø is missing

### ISSUE THREAD

**Issue by hhgabelgaard** [FortAwesome/Font-Awesome#11295]
These special danish letters are missing
U+00c6  Æ  LATIN CAPITAL LETTER AE
U+00d8  Ø  LATIN CAPITAL LETTER O WITH STROKE

The corresponding small letters are included:
U+00e6  æ  LATIN SMALL LETTER AE
U+00f8  ø  LATIN SMALL LETTER O WITH STROKE

![image](https://user-images.githubusercontent.com/7933710/28245101-579fa96c-69ff-11e7-8fcc-4e9ee7575c1f.png)

Checked on version 4.2.0 and 4.7.0

**Comment by tagliala** [comment]
I can confirm those characters are missing, but I don't know if this could be considered an issue.

Fiddle showing the issue: https://jsfiddle.net/tagliala/s3msxtbe/21/

#### Workarund
If I must use Font Awesome to represent letters, I would prefer my web application's font family

https://jsfiddle.net/tagliala/s3msxtbe/22/

**Comment by hhgabelgaard** [comment]
@tagliala Thanks for the quick response

> If I must use Font Awesome to represent letters, I would prefer my web application's font family
I kind of understand your point of view her, but why does FontAwesome then include A-Z and various other "national" characters?

**Comment by tagliala** [comment]
> I kind of understand your point of view her, but why does FontAwesome then include A-Z and various other "national" characters?

Sorry, but I don't know the answer.

BTW, `Ǣ` works, it looks like there are some letters deliberately excluded.

@davegandy could you please take a look?

**Comment by tagliala** [comment]
Just cleaning up old issues.

I'm going to close here, considering this as a special case of #5019

In version 5.0.0, small letters are also excluded

Please use your own font if you need special characters
