### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dhanyn10** [FortAwesome/Font-Awesome#11290]
this typo that never been solved so far 😆 
![2017-07-14_113735](https://user-images.githubusercontent.com/11478316/28198517-f8a88798-6888-11e7-9187-00ef58286d51.jpg)

**Comment by omkartapale** [comment]
@dhanyn10 moar is Internet slang, humorous (alternative form of) more

**Comment by Clonkex** [comment]
As @omkartapale said it's not a typo. If it weren't intentional, you'd also have to point out the severe grammatical issues that would exist in that sentence. Specifically, "be more betters" is not valid English.

**Comment by tagliala** [comment]
I suppose it is intentional. I'm going to close here
