### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by nullpixel** [FortAwesome/Font-Awesome#11301]
Since y'all ignoring #7574, please can you read the most upvoted and most commented issue on your repo?

**Your users are expressing their voice, please listen to them**

There's no reason for it to take years to add, _please_ actually do something about it - rather than leaving us, your users, in the dark

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Since y'all ignoring #7574

This is not true, please be patient or consider a custom build of font awesome https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Closing here

**Comment by nullpixel** [comment]
I've been patient for two years
