### ISSUE TITLE
Please make `map` and `map-o` the same width.

### ISSUE THREAD

**Issue by chapeljuice** [FortAwesome/Font-Awesome#11317]
Please see my live demo of the issue here:
https://codepen.io/chapeljuice/pen/ZJzeEP

Ideally similar icons should be the same size so we can toggle them without moving other adjacent elements around.

**Comment by rubentrf** [comment]
You can always use the `fa-fw` class for fixed width icons. It will keep all icons the same width, so you can easily toggle them without moving the rest of the elements.

Demo: https://codepen.io/rtrujillo/pen/yoEaNP

**Comment by chapeljuice** [comment]
That's pretty cool, I didn't know that existed!

However, for my particular situation right now I'm actually using the React Native Vector Icons pack and don't have access to classes like that.

**Comment by TexasSwede** [comment]
There are also some icons where different variations seems to be different sizes, e.g. `fa-box` and `fa-box-alt`, where the latter is smaller.
![image](https://user-images.githubusercontent.com/3178455/98989132-472ed500-24ee-11eb-980c-52c718b72558.png)
Here you can see that the middle icon is visibly smaller, making it look inconsistent. This is _with_ `fa-fw` added to all 3 icons.
The icon fa-box renders with a class `fa-w-16` while fa-box-alt uses `fa-w-14`.
I am using the SVG version of Font Awesome 5.15.0 (I also tried with 5.13.0, same result).
It would be nice if the same icon, with different variants, could have the same size.
You can also see the difference in size here:
![image](https://user-images.githubusercontent.com/3178455/98989994-801b7980-24ef-11eb-96d3-84f4a54113dd.png)

**Comment by tagliala** [comment]
This is not anymore an issue. In version 5.1.0 map have the same width

https://jsfiddle.net/tagliala/evhxprbg/5/

@TexasSwede I can also see that `box` and `box-taped` have the same width in FA 6 alpha
