### ISSUE TITLE
Icon Request: fa-banner

### ISSUE THREAD

**Issue by tdjohn** [FortAwesome/Font-Awesome#11310]
Hi - font-awesome is just that ;)

I'm looking for an icon to represent the management of Banners on a CMS system. Banners are images that usually go across the page and link to another page or external resource. Something like a plan towing a banner:

![image](https://user-images.githubusercontent.com/14178/28388017-2ccf3d20-6cc9-11e7-9076-60fd373cd4f5.png)

Or even a regular banner such as:

![image](https://user-images.githubusercontent.com/14178/28388058-486bf56e-6cc9-11e7-9cf0-4788e0006603.png)

Thanks!

**Comment by mfranjavier** [comment]
creo que la imagen es ideal para icono banner

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide a single color example suitable for 16px icon size.

The above examples are not good candidates

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tdjohn** [comment]
If I was an icons designer I would not be paying for font awesome I’d just do hem my self!

On 19 Dec 2017, at 09:20, Geremia Taglialatela <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

Thanks for being part of the Font Awesome Community.

Please provide a single color example suitable for 16px icon size.

The above examples are not good candidates

Please take another look at our Contributing guidelines<https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons>.

**Comment by tagliala** [comment]
@tdjohn if you are a pro backer, please post your request on the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

This is the issue tracker for Font Awesome Free and I need that requests meet our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
