### ISSUE TITLE
Icon request: icon-forklift

### ISSUE THREAD

**Issue by NicoleneL** [FortAwesome/Font-Awesome#11328]
Hi, is there a chance we can get a forklift icon please. Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
