### ISSUE TITLE
Icon request: icon-mno-telekom, icon-mno-vodafone, icon-mno-atandt, icon-mno-verizon, ...

### ISSUE THREAD

**Issue by Neologist** [FortAwesome/Font-Awesome#11320]
It would be great to have a set of icons to represent the largest mobile network operators. Possible use case: Form validation of mobile numbers

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
About the use case:

> Form validation of mobile numbers

Please note that becaouse of [MNP](https://en.wikipedia.org/wiki/Mobile_number_portability) you cannot make assumption on the operator by using the mobile number

**Comment by Neologist** [comment]
There are several APIs to gather correct information (such as MNP/MNO) from:
* https://www.messagebird.com/en/lookup
* https://www.hlrlookup.com/
* https://www.hlr-lookups.com/
So no need to make assumptions here.

If this was the reason for closing the issue, please re-open it.

**Comment by tagliala** [comment]
Hi,

> There are several APIs to gather correct information (such as MNP/MNO) from:

Thanks for letting me know.

> If this was the reason for closing the issue, please re-open it.

Nope, that is not the issue. It was just a consideration from a strictly client side form validation point of view.

Quoting from [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

> * Please do not request comprehensive sets of icons related to a very specific field.
> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Also, quoting from [Customize Font Awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

> So, if you [...] need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

I'm sorry but at the moment I cannot leave this open.
