### ISSUE TITLE
Can you guys please make icons for the following.

### ISSUE THREAD

**Issue by thebrettism** [FortAwesome/Font-Awesome#11324]
Hey just been looking through the alpha icons for font awesome 5 and have to say, i am a little disappointed at this point.

I have really been hoping that you could develop some more "tourism friendly" icons.

for example I run a website which deals with travel stuff and i would love it if there were icons for things like running, cycling, hiking and tramping, adventure, camping, and outdoorsy activities.

another big one that i find is missing is gym.. like weights, bodybuilding, protein and that kind of stuff. 

this is only a request from me, but i do think they are important icons to have.

**Comment by tagliala** [comment]
Hi,

please use the Font-Awesome-Pro repository
