### ISSUE TITLE
Add icons of different vehicle types

### ISSUE THREAD

**Issue by You85** [FortAwesome/Font-Awesome#11339]
Pickup, Micro, Van, Suv, Cabriolet, Campervan...

https://www.shutterstock.com/image-vector/cars-icons-set-different-car-types-336695264

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
