### ISSUE TITLE
New Icon for SPLat Controls

### ISSUE THREAD

**Issue by TorontoFred** [FortAwesome/Font-Awesome#11334]
Hello,
I'm working on my blog website (WordPress) and I need an icon to represent a company who manufactures microcontrollers.  I used to rep them in North America.  I'm retired now.  So, first,[ my web ](https://arduinocontrolworld.000webhostapp.com/) site that is basically set up and needs posts.  On the home page scroll down and you will see three icons... Android, Apple and an anchor.  That anchor needs to be replaced with SPLat's icon.  If you visit [SPLat's website](http://www.splatco.com/), you will see "SPLatty", the name of the SPLat logo.  It looks like a splat.  Original, eh? You will also see it in the tab on your browser.   

I guess that's it.  I'd love to polish this site off with SPLat's icon.   Thanks for your time.  

Fred P.  , Orlando, Florida.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons) and edit this issue accordingly?

Thanks

**Comment by TorontoFred** [comment]
I generated a second request with "Icon request: icon-SPLat".   I also added a bit more information in that second request.  Sorry for the mixup.  By the way, since you have icons for entities such as Android and Apple, the same argument can be placed for SPLat.  I just mentioned that in case there's a problem.  There isn't a problem, right?

OK... thanks.
