### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by ColinMoulds** [FortAwesome/Font-Awesome#11338]
I have seen so many discord icon post requests can we please make this a thing its been open since 2015.

Icon request: icon-discord #7574

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I must close this request, because it is a duplicate of #7574

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
