### ISSUE TITLE
Icon Request: Mathematical icons

### ISSUE THREAD

**Issue by monemihir** [FortAwesome/Font-Awesome#1133]
This is useful again when we specify a library version dependancy i.e <= .NET 4, or >= MVC3.

Also if there are any mathematical equations that need to be represented on a page using a proper less than equal to sign would look much better than using <=.

* icon-divide
* icon-less-than
* icon-greater-than
* icon-less-than-equal
* icon-greater-than-equal
* icon-equal

**Comment by ramajd** [comment]
+1 for mathematical icons.

**Comment by Undistraction** [comment]
+1

**Comment by nofxx** [comment]
+1 for equal

**Comment by h-taleghani** [comment]
+1

**Comment by gca88** [comment]
+1

**Comment by kanareykin** [comment]
+1

**Comment by SachinKainth** [comment]
+1

**Comment by okdewit** [comment]
+1 for ````fa-equal````!

**Comment by visby** [comment]
+1, equality for all!

**Comment by anstosa** [comment]
+1 for `fa-equal`

**Comment by tommyj1112** [comment]
Equal sign would be good.  But Division sign, Greater-Than-or-Equal-To, and Less-Than-or-Equal-To would be even better! 

The chevron-left and chevron-right can already be used for Greater-Than and Less-Than symbols. Simply adding a line underneath them would be really useful.

**Comment by catalint** [comment]
+1

**Comment by desmedth** [comment]
+1

**Comment by allpumpedup** [comment]
+1

**Comment by dpistole** [comment]
+1 equals icon, appreciate the library, thank you

**Comment by ntrench** [comment]
+1

**Comment by marstone** [comment]
+1

**Comment by screenpunch** [comment]
+1

**Comment by e-tobi** [comment]
+1

**Comment by wsaxton** [comment]
+1

**Comment by MNessa** [comment]
+1

**Comment by legendarydrew** [comment]
+1, yo.

**Comment by hmillet** [comment]
+1

**Comment by frlinw** [comment]
+1 for =, < and > !

**Comment by sikko** [comment]
+1 yolo

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by gtonioli** [comment]
+1

**Comment by Frucht** [comment]
+1

**Comment by nitmir** [comment]
+1

**Comment by thiagovieiracom** [comment]
+1

**Comment by alexmigf** [comment]
+1

**Comment by johnnyshields** [comment]
+1

**Comment by rodrigoroma** [comment]
+1 for a divide icon!

**Comment by rubenscd** [comment]
+1

**Comment by RobertHerhold** [comment]
+1

**Comment by iboylmz** [comment]
+1 for math

**Comment by nbunney** [comment]
+1

**Comment by kalverk** [comment]
+1

**Comment by mfrejnik** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by roulili** [comment]
+1

**Comment by yagobski** [comment]
+1

**Comment by dottorblaster** [comment]
+1

**Comment by caeldom** [comment]
+1

**Comment by BigShaw** [comment]
+ 1

**Comment by BigShaw** [comment]
+1

**Comment by Narshe1412** [comment]
+1

**Comment by Seb33300** [comment]
+1

**Comment by iabdulin** [comment]
+2

**Comment by hpvd** [comment]
+1

**Comment by rypsx** [comment]
+1

**Comment by alex-hall** [comment]
+1

**Comment by s-gto** [comment]
+1

**Comment by mabm** [comment]
+1

**Comment by hertog6** [comment]
+1!

**Comment by ellenhutchings** [comment]
+1

**Comment by httpJunkie** [comment]
+1 fa-equal

**Comment by gearsandcode** [comment]
+1 fa-equal

**Comment by mitulpanch** [comment]
+1 for fa-equal

**Comment by hicklin-james** [comment]
+1

**Comment by CathyMacars** [comment]
+1 for all, but especially for **fa-divide** and **fa-equal**

**Comment by hpvd** [comment]
icon-less-than / icon-greater-than could be used together with rotation function also
for unfold of more information
![2016-03-23_16h22_09](https://cloud.githubusercontent.com/assets/5681880/13990207/c22d025e-f113-11e5-8684-3c8a6fb604ca.png)

=>
+1

**Comment by hpvd** [comment]
just found something similar could be done with
angle-right or chevron-right
and
angle-down or chevron-down

this should also work for less-than,and greater than
angle-right or chevron-right
and
angle-left or chevron-left

**Comment by Sir-J** [comment]
+1

**Comment by CrisMVP3200** [comment]
+1

**Comment by humbertcostas** [comment]
+1

**Comment by sanek4life** [comment]
+`

**Comment by kaflan** [comment]
+1

**Comment by burgosh** [comment]
+1

**Comment by dmeh89** [comment]
+1

**Comment by jamesthomson** [comment]
+1

**Comment by SuperboltStudios** [comment]
+1 for Equal Sign

**Comment by zeroasterisk** [comment]
+1

**Comment by azZur0** [comment]
+1 for fa-qual

**Comment by erwan-haquet** [comment]
+1

**Comment by anltnmse60906** [comment]
+1

**Comment by meyersbs** [comment]
+1

**Comment by Sublime45** [comment]
+1

**Comment by saluce65** [comment]
@tagliala It's been a couple years since you posted that fiddle, but it would be better to use `\f7` for the content to get the division symbol:  http://jsfiddle.net/77re29ct/425/

**Comment by MichaelGriebe** [comment]
+1 mathematical

**Comment by suyashgulati** [comment]
+1 for divide sign

**Comment by DSwissK** [comment]
+1 fa-equal AND fa-equal-circle

I can see a lot of uses outside of pure maths. For exemple, for "same", "similar" or "synonym". It could even be used as "parallel" if you rotate it.

**Comment by hfekiss** [comment]
+1 for fa-divide

**Comment by mlametta** [comment]
+1 for all math signs

**Comment by nbunney** [comment]
Hey, not sure if it will include math symbols, but I am guessing it will...  You all need to check out and support the kickstarter for FontAwesome 5.  https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by vegarringdal** [comment]
+1 for all math signs

**Comment by ClaytonBrawley** [comment]
+1

**Comment by gnazarkin** [comment]
+1

**Comment by binard** [comment]
+1

**Comment by TheBananier** [comment]
+1

This is doing the job while waiting updates : **fa-pause fa-rotate-90**

**Comment by simone** [comment]
+1

**Comment by nateinaction** [comment]
+1

**Comment by shoulders** [comment]
+1

**Comment by imamassi** [comment]
+1

**Comment by sebnyberg** [comment]
+1

**Comment by laurentvergnaud** [comment]
+1

**Comment by antonberezan** [comment]
+1 especially for fa-equal

**Comment by dchosnek** [comment]
+1 for fa-divide

**Comment by guilemos** [comment]
+1 for fa-divide

**Comment by Smarello** [comment]
+1 fa-divide!

**Comment by iegoday** [comment]
+1 fa-divide

**Comment by mwthink** [comment]
+1

**Comment by jan-madeyski** [comment]
+1

**Comment by sudotribe** [comment]
+1

**Comment by dev-z** [comment]
+1 Please add Σ (summation) symbol

**Comment by LionDBell** [comment]
+1 The lack of a fa-divide when we have plus, minus, and times is frankly baffling.

**Comment by mkeuschn** [comment]
+1

**Comment by philik** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

Here are icons:
[divide icon](https://icons8.com/icon/9494/divide), [less than icon](https://icons8.com/icon/7925/less-than), [greater than icon](https://icons8.com/icon/60/forward), [less than equal icon](https://icons8.com/icon/7929/less-or-equal), [greater than equal icon](https://icons8.com/icon/7922/more-or-equal), and [equal icon](https://icons8.com/icon/9444/equal-sign).
[More math icons here](https://icons8.com/icon/set/math/all).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by apankov** [comment]
+1 fa-divide

**Comment by S-Kerrigan** [comment]
+1 for all math signs

**Comment by teenangst** [comment]
Why is it taking so long, need maths signs!

**Comment by cromartie1984** [comment]
would be awesome to get this "="

**Comment by Jeanguitoune** [comment]
+1 for "="

**Comment by youeee** [comment]
+1 for mathematical symbols

**Comment by RoxannaBatista** [comment]
+1 for all math signs

**Comment by rodrigojob** [comment]
Mathematical characters have in character maps, don't need icon.
Exemple: 
HTML Entity (Named) | &divide;
http://graphemica.com/%C3%B7

You can see others here: http://graphemica.com/categories/math-symbol

**Comment by princeofnaxos** [comment]
@rodrigojob When using the HTML entities, there is likely to be a problem with alignment with other FA icons. Therefor, I think it'd be better to have fa-plus, fa-divide, etc.

**Comment by Guigass** [comment]
+1

**Comment by o8e** [comment]
We need an equals sign.

**Comment by ErickXavier** [comment]
+1 for Mathematical icons

**Comment by seagullmouse** [comment]
+1

**Comment by hafrit** [comment]
:+1: for mathematical signs

**Comment by brijmcq** [comment]
+1

**Comment by Pargus** [comment]
+1

**Comment by zeikman** [comment]
+1

**Comment by mcalcote** [comment]
👍

**Comment by Script47** [comment]
Firstly, thanks for all the free icons available for usage.

Secondly, FontAwesome 5 is out and still no divide? Any chance this is in the pipeline?

**Comment by felyperennan** [comment]
I needed divide and multiply icons. "solved" it with &divide; and &times; 
it was shabby and shameful. But it worked for now.

**Comment by hybrid1969** [comment]
+1 for all math signs

**Comment by MyIndicators** [comment]
+1 for basic mathematical signs like 'divide', 'equal' signs. the pro and newest versions have not included them. Thank you for the consideration.

**Comment by JohnwMoody** [comment]
+1 for fa-equals

**Comment by sensibleworld** [comment]
We're working hard on new icons, and these are in the queue!

**Comment by Tom-Arnfeldt** [comment]
+1

**Comment by tijuhasz** [comment]
+1

**Comment by Script47** [comment]
Any chance of adding the percentage sign (%) too to the list?

**Comment by frontend-fxs** [comment]
+1

**Comment by sensibleworld** [comment]
@Script47 Yup! Just designed it. Hoping to get these into our next release.

**Comment by sensibleworld** [comment]
1+1=released. https://fontawesome.com/icons?d=gallery&c=mathematics
