### ISSUE TITLE
langages

### ISSUE THREAD

**Issue by grophies** [FortAwesome/Font-Awesome#11342]
Hello,

There are icons for html5 and css3, but not for javascript, php, sql, java, python, and other programming languages.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

There are also several duplicates ( #1711 #3016 #1420 ...)

Please also take a look at mfizz: http://fizzed.com/oss/font-mfizz
