### ISSUE TITLE
Icon request: icon-dumbbell

### ISSUE THREAD

**Issue by rdldigital** [FortAwesome/Font-Awesome#11348]
Hey all - needing a dumbbell or barbell FA icon for my fitness clothing site - www.musclefire.com
or a person flexing muscles.
thoughts and possibilities on this for font awesome?
thanks! - Ryan

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1500 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
