### ISSUE TITLE
Add sports icons

### ISSUE THREAD

**Issue by You85** [FortAwesome/Font-Awesome#11340]
https://thumbs.dreamstime.com/z/vector-sports-symbols-4513494.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
