### ISSUE TITLE
Icon request: Public Security

### ISSUE THREAD

**Issue by bmeetymiss** [FortAwesome/Font-Awesome#11346]
Public security network ready Icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

any example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
No feedback, closing here
