### ISSUE TITLE
Icon request: icon-ampersand

### ISSUE THREAD

**Issue by Susanvano** [FortAwesome/Font-Awesome#11344]
Could you add the ampersand icon? :and:

**Comment by tagliala** [comment]
IIRC, this is a duplicate but at the moment I'm unable to find the original request.

**Comment by martindubenet** [comment]
I can't find anything regarding « `ampersand` » in the within version 5.8.1... Is it available under an other nomenclature?

**Comment by tagliala** [comment]
@martindubenet AFAIK this icon is not available

**Comment by tagliala** [comment]
Available in FA6 Pro: https://fontawesome.com/v6.0/icons/ampersand?s=solid
