### ISSUE TITLE
fa fa-build

### ISSUE THREAD

**Issue by Mendistern** [FortAwesome/Font-Awesome#11350]
Please create a icon with 

- Screw driver 

- maintenance helmet

thankyou very much

**Comment by knight1219** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

helmet is a duplicate of #3934 , please add a 👍  reaction to that request.
screwdriver is a duplicate of #5687  , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
