### ISSUE TITLE
Icon request: Nutritionix [will be available in FA5]

### ISSUE THREAD

**Issue by Benjamin-Lee** [FortAwesome/Font-Awesome#11359]
https://www.nutritionix.com

**Comment by Quix0r** [comment]
Where is the icon?

**Comment by tagliala** [comment]
@Quix0r this is a request for adding Nutritionix icon

**Comment by Benjamin-Lee** [comment]
[http://www.nutritionix.com/images/image-coming-soon-medium.png](http://www.nutritionix.com/images/image-coming-soon-medium.png)

**Comment by Quix0r** [comment]
Looks nice. 👍

**Comment by tagliala** [comment]
Hi!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
