### ISSUE TITLE
[Question] Is this project dead?

### ISSUE THREAD

**Issue by mkg20001** [FortAwesome/Font-Awesome#11356]
It seems like no more new icons are being added and really nothing is happening here anymore.
Some requests are now waiting more than 5 Years https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc
Only duplicates and invalid requests are getting rejected, no requests get accepted.

So... is this project dead?
And if that's not the case: What is the reason why all these requests are never getting accepted if they aren't invalid?

**Comment by kirkbeard** [comment]
The project is definitely not dead, but their efforts are focused on [Font Awesome v5](http://fontawesome.com). An alpha test version was [released last month](https://www.kickstarter.com/projects/232193852/font-awesome-5/posts/1919869). It's a massive project, so we'll just need to be patient.

There's also [3,060 icon requests](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+label%3A"new+icon"), so I'm not surprised they don't implement every request they get.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA is definitely not dead. What @kirkbeard said is correct and today the first FA5 beta has been released!

Please be patient for a little longer

Closing here, hope it helps
