### ISSUE TITLE
The class name of currency icon "CNY"

### ISSUE THREAD

**Issue by wangxiaoweishy** [FortAwesome/Font-Awesome#11351]
Hello,
I've found that the class name of currency icon "cny" is a mistake.  The class name in the icons page (http://fontawesome.io/icons/) is "jpy“.
Even though I can also show this icon by naming the class "fa fa-cny", it may confuse some users and make them use the "jpy" in Chinese website, which is not appropriate. 
This may be a small issus, but I think it's necessary to correct it.
Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`cny` is an alias for `jpy`, you can use `fa-cny` as you wish.

This was discussed at #1338, please read the whole conversation

Hope it helps, closing here
