### ISSUE TITLE
Need icons for sports.

### ISSUE THREAD

**Issue by ageetey** [FortAwesome/Font-Awesome#11352]
Hey David

Thanks for doing this great work. Could you please add icons for sports in Version 5? I have alreday bought a small org license through Kickstarter :). I love your work. Thanks again!!!

Sincerely
Anand

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check out the https://github.com/FortAwesome/Font-Awesome-Pro repository which is exclusive for early bakers. If you don't have access, please make sure to sign in to your fontawesome.com account, and connect your GitHub account

Closing here
