### ISSUE TITLE
fa-linkedin-square

### ISSUE THREAD

**Issue by malyarevich** [FortAwesome/Font-Awesome#11353]
fa-linkedin-square 
http://fontawesome.io/icon/linkedin-square/

empty icon.
All sites doesnt work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Of course I cannot confirm: https://jsfiddle.net/tagliala/s3msxtbe/28/

Please take a look at our [Troubleshooting guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting).

**Comment by malyarevich** [comment]
Okay )
Why not work on the official site?

**Comment by malyarevich** [comment]
http://fontawesome.io/icon/linkedin-square/

**Comment by tagliala** [comment]
![image](https://user-images.githubusercontent.com/556268/28968585-ee44d286-7920-11e7-90fa-46cabc396474.png)

Cannot confirm. Please make sure you are not using adblock with outdated versions of fanboy block list: #1799

**Comment by malyarevich** [comment]
Adguard Adblocker 
*Social Filters

Many thanks!

**Comment by tagliala** [comment]
@malyarevich latest fanboy block list should not have this issue anymore, please make sure you updated your adblock's lists

**Comment by GreenRidingHood** [comment]
thank you.. i was getting crazy :) , but probably most of users have adblocker, how can we solve this problem. for being good developer  i/we need to create site usable for common browser and tech. 
Is linked library has issue?  
my liked url is : http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css

thanks

**Comment by tagliala** [comment]
Hi.

IIRC, all font awesome versions have this issue because that list blocks `fa fa-linkedin` and `icon-linkedin`.

You should create an alias, let's say `fa-blockthis` for linkedin.

```
.fa-blockthis:before {
  content: "\f08c";
}
```

By the way, your users deliberately chose to block social stuff, so it is supposed that they don't want to see linkedin and other social icons.

**Comment by malyarevich** [comment]
This is my way.
I was done the same thing.
