### ISSUE TITLE
Icon Request: audi-logo

### ISSUE THREAD

**Issue by You85** [FortAwesome/Font-Awesome#11362]
![audi-emblem-2016-black-1920x1080](https://user-images.githubusercontent.com/30325749/29003002-1248c040-7aaf-11e7-958b-f6de0c8b01e4.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6082, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
