### ISSUE TITLE
Icon Request: Pickup

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#11376]
![26596](https://user-images.githubusercontent.com/30325749/29092580-17d64e18-7c87-11e7-94d0-4ae92f412c6e.png)

**Comment by aethior** [comment]
Hi @ghost,

This icon was added in v5.2.0.
Check https://fontawesome.com/icons/truck-pickup

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.
