### ISSUE TITLE
Issue report: Icons are duplicating and more

### ISSUE THREAD

**Issue by mikijakov** [FortAwesome/Font-Awesome#11377]
On my site icons are duplicating. If I set only one icon in code it appears in next line where I also used different icons. Second problem is that if I set icons to 2x size with 'sufix' "fa-2x" on every icon my font size progressively grew up by the every line where are icons. 
Sample skeleton html file without css (i noticed this issues early while building so I didn't want to continue) : www.arkomp.tk/test/index.html
You can use source CTRL + U

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that `<i>` is not a self-closing tag.

```html
<!-- BAD -->
<i class="fa fa-arrow-down" aria-hidden="true"/>

<!-- GOOD -->
<i class="fa fa-arrow-down" aria-hidden="true"></i>
```

Hope it helps, closing here
