### ISSUE TITLE
Add translate filter to language icon

### ISSUE THREAD

**Issue by Buky77** [FortAwesome/Font-Awesome#11370]
Hello, it's possible to add a icon for translation ? 
It's a part of social as well.

![image](https://user-images.githubusercontent.com/18658299/29040017-d3563bb0-7bad-11e7-99e6-7702e6e1e76c.png)

Thank you in advance!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

http://fontawesome.io/icon/language/

There is the need for a filter in the docs because searching for `translation` / `translate` doesn't work
