### ISSUE TITLE
Icon request: icon-filter-sort

### ISSUE THREAD

**Issue by ajm0824** [FortAwesome/Font-Awesome#11371]
You have an icon for filter and an icon for sort, but do not have one that can be used in applications where should be combined to a single function "Filter and Sort" (to save screen real estate).

Something like this: [https://cdn0.iconfinder.com/data/icons/pixon-1/24/filter_list_order_sequence_sort_sorting-256.png](url)

![screen shot 2017-08-07 at 8 32 15 pm](https://user-images.githubusercontent.com/528169/29051432-af2ef5d0-7bb0-11e7-9a51-b12aff17253e.png)

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

http://fontawesome.io/icon/sliders/
