### ISSUE TITLE
Icon Request: fa-arvr

### ISSUE THREAD

**Issue by prajithnair** [FortAwesome/Font-Awesome#11378]
Requesting for icons on augmented,virtual and mixed reality
hololens,google glass,vive,rift and generic icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
