### ISSUE TITLE
Icon Request: fa-chess

### ISSUE THREAD

**Issue by Soaku** [FortAwesome/Font-Awesome#11385]
I wish there was a chess horse icon. Horse is often symbol of chess, right? 

It would be something like this:

![Chess Horse](https://image.freepik.com/free-icon/horse-black-head-shape-of-a-chess-piece_318-52446.jpg)

It will be nice as icon for board games. We've got fa-play or fa-gamepad, but they only fit video games.

Thanks!

**Comment by Soaku** [comment]
(I know about the fa-dice requests, but this isn't the same at all... don't close as duplicate of such request.)

**Comment by tagliala** [comment]
I'm going to leave this open, even if this request is a subset of #1815 (12 icons)

**Comment by tagliala** [comment]
Chess is available in 5.0.5: https://fontawesome.com/icons/chess?style=solid

https://fontawesome.com/icons/chess-knight?style=solid
