### ISSUE TITLE
Add Icon VR - AR

### ISSUE THREAD

**Issue by Bagmaz** [FortAwesome/Font-Awesome#11387]
Please add virtual reality icon and augmented reality icon
Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

VR is a duplicate of #6590, please +1 that request

If you need an icon for augmented reality, please open a new issue that meets our contributing guidelines

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
