### ISSUE TITLE
Task icons including status indicators

### ISSUE THREAD

**Issue by fsailer** [FortAwesome/Font-Awesome#11380]
It would be fantastic to be able to have a unified set of icons for tasks or work items and a series of statuses such as but not limited to:

1. Not Started
2. In Progress
3. In Review
4. Deferred
5. Completed
6. Not Applicable
7. Returned
8. Restarted
9. Approved
10. Not Approved
...etc

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
