### ISSUE TITLE
Icon request: animals

### ISSUE THREAD

**Issue by shotechs** [FortAwesome/Font-Awesome#11381]
Icon request: animals
like dogs, cat, bird, fish, chicken, and food like hamburger, Technical Support, Jobs

**Comment by timtjtim** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/1317
https://github.com/FortAwesome/Font-Awesome/issues/2226

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open. @timtjtim pointed out one of the reasons.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
