### ISSUE TITLE
copy a character from the web page

### ISSUE THREAD

**Issue by macness-pavelh** [FortAwesome/Font-Awesome#11383]
Sorry if I missed something or if it was discussed before... but there is really no way how to copy unicode character from the web page to the clipboard?

I mean character detail page like: http://fontawesome.io/icon/camera/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use the cheatsheet if you need this feature: http://fontawesome.io/cheatsheet/

**Comment by macness-pavelh** [comment]
wow! that's pretty cumbersome is not it? so I discover a character, look at its page, copy it's name, go to the cheatsheet, search it and copy... ok... ;)

**Comment by tagliala** [comment]
There is a request for implementing this feature at #2736, but as you can see it is not widely used

Cheatsheet page contain all icons, could you please elaborate why you need to look for an icon, open the detail page of that icon and then go to the cheatsheet to copy its unicode point?

**Comment by macness-pavelh** [comment]
wherever you use the font outside web you need unicode char... sometimes you may enter Unicode literal like \u{0f03} but in many cases you can not...  my case is developing iOS app. I have character name form the designer and I need to paste it to xcode as a single character... this workflow is terrible

**Comment by tagliala** [comment]
> I have character name form the designer and I need to paste it to xcode as a single character

On the cheatsheet you can search (via browser's default search) for:

1. Icon name (eg: `fa-home`)
2. Icon unicode point (eg: `f015`)

**Comment by macness-pavelh** [comment]
oh, sure I know this is possible... but why to limit the workflow to a single scenario...what if I'm doing ios app and I search for the right character, look at it appears in better resolution... why to stick to cheatsheet if it would be so tiny and nice feature on the  character page.

**Comment by macness-pavelh** [comment]
more explanation - if you want to paste the character to xcode (like label value) you need the CHARACTER in the clipboard, not it's unicode scalar value.

**Comment by macness-pavelh** [comment]
and more... you are telling me there is an alternative workflow to what I propose... and you are right. I'm telling you sometimes it's just to annoying to use it. I have nothing more to say :)

**Comment by tagliala** [comment]
@macness-pavelh thanks for explaining your use case.

Please upvote #2736, which is asking for the same feature
