### ISSUE TITLE
Add new icon phone-circle, please ?

### ISSUE THREAD

**Issue by VietPublic** [FortAwesome/Font-Awesome#11398]
Can you add new icon similar this picture [http://simpleicon.com/wp-content/uploads/phone-symbol-2.png](url)

Thankyou !

**Comment by tagliala** [comment]
Please consider using the stacking feature: http://fontawesome.io/examples/#stacked

**Comment by aethior** [comment]
Hi @VietPublic,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/circle-phone

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Free users, **in a web application**, can achieve this icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/626/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by VietPublic** [comment]
> Hi @VietPublic,
> 
> This icon has been added in v6.0.0-BETA1. Check https://fontawesome.com/icons/circle-phone
> 
> Regards.
> 
> cc/ @tagliala

Thank you !
