### ISSUE TITLE
Icon request: fa-shirt

### ISSUE THREAD

**Issue by moofawsaw** [FortAwesome/Font-Awesome#11391]
A shirt or a clothes hanger or something to represent clothing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #715 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
