### ISSUE TITLE
Add some padding to the right of the Visa icon to increase balance.

### ISSUE THREAD

**Issue by YesThatAllen** [FortAwesome/Font-Awesome#11396]
The visa icon is slated for updating per #10492

I'd like to consider how much space is on the right of the visa logo here:

<img width="83" alt="screenshot_2479" src="https://user-images.githubusercontent.com/2879972/29201598-3f7547b8-7e25-11e7-9204-0bcc36d598f9.png">

It seems that the border hugs the A too tightly, compare to the V (even considering the extended width of the V.

Basic measurements I've done seem to back this up, but I'm not an icon designer so I'll leave the math to others.

**Comment by bepursuant** [comment]
It looks a little close on the right but it's probably at least partially an optical illusion because of the shape of the V. I'll check BMAS tomorrow to see what their brand assets dictate for padding around the staged bandmark. I don't know how to make the font, but I can get vector or svg assets of the new staged mark and a sense of how it should be positioned.

**Comment by tagliala** [comment]
I've tried to check if Visa are doing something like that, and apparently they are.

I've taken this image from their twitter 

![image](https://user-images.githubusercontent.com/556268/30420847-31cc8d8e-993b-11e7-9f24-b1a0db42c447.png)

and I've checked margins

![image](https://user-images.githubusercontent.com/556268/30420871-3d9faaba-993b-11e7-8a71-dc0a176d21e8.png)

They are not symmetrical, as in FA.

Let's see if we can fix this

**Comment by tagliala** [comment]
@YesThatAllen what do you think?

![image](https://user-images.githubusercontent.com/163763/30436992-87bf4fb0-993b-11e7-9216-65b7b6b08b65.png)

**Comment by YesThatAllen** [comment]
It's amazing how a few pixels can make such a difference. Much better, thanks!

**Comment by tagliala** [comment]
I'm pretty sure this will be fixed in the upcoming FA 5.0.0

**Comment by bepursuant** [comment]
That looks great! 
As a note, the safety shape(box around the brandmark) should have square corners and less vertical padding according to the latest Visa Brand Standards. I'm not sure how that would look here though...

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes
