### ISSUE TITLE
Icon Request: fa-wallet

### ISSUE THREAD

**Issue by dukenst2006** [FortAwesome/Font-Awesome#11390]
Great work, Using Font-Awesome but can't find a generic wallet icon. Please add some. 
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2317 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
