### ISSUE TITLE
add icon please

### ISSUE THREAD

**Issue by fabianessy** [FortAwesome/Font-Awesome#11401]

**Comment by fabianessy** [comment]
![boton](https://user-images.githubusercontent.com/31011581/29279872-dc2e9a08-80de-11e7-87d5-2423c55b1cf1.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
