### ISSUE TITLE
Icon request: icon-Emacs

### ISSUE THREAD

**Issue by foxmean** [FortAwesome/Font-Awesome#11400]
Hello, I'm new i3 windows manager user; And I'll use this icon in my workspace create for Emacs.
The Icon that I've attach is suitable for my use. Thank you for your hard work. :)
![default](https://user-images.githubusercontent.com/13077459/29278025-b7b71984-813d-11e7-987e-d19663d8aecd.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7907, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
