### ISSUE TITLE
Add statistics filter to chart icons

### ISSUE THREAD

**Issue by Buky77** [FortAwesome/Font-Awesome#11410]
Hello, he miss an icon about statistic for tab in a dashboard (for exemple).

![image](https://user-images.githubusercontent.com/18658299/29353459-77c18a0c-826a-11e7-9051-b1c60c1a359b.png)

Thank you.

**Comment by Buky77** [comment]
May be add the reference "statistic" for available graphs

**Comment by tagliala** [comment]
@Buky77 yes, adding filters should do the job
