### ISSUE TITLE
Icon Request: home automation icons

### ISSUE THREAD

**Issue by yene** [FortAwesome/Font-Awesome#11416]
hi,

I just wanted to speak out for home automation icons. Like blinds open/close. Door open/close etc
There are projects like [Home Assistant](https://home-assistant.io/) which could really make use of them. 

thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
