### ISSUE TITLE
Icon Request: fa-javascript OR fa-js

### ISSUE THREAD

**Issue by alton1231** [FortAwesome/Font-Awesome#11419]
I want a javascript icon to go with the HTML5 and CSS3 icons. I like to promote coding on pages that I make, so I want to include a section in my footer that says:
Made with *HTML icon*, *CSS icon*, and *JS icon*
Where each of the icons contains a link to a place where you can start learning to use them.
I want the icons to look like the ones I've linked, but black and white. Their already exist font awesome icons for HTML and CSS, but the lack of one for JS is disappointing.
![html5_css_javascript](https://user-images.githubusercontent.com/30186107/29488525-f55a69d0-84da-11e7-8a39-5476f663b5eb.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1711 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by rituoapps** [comment]
<svg id="svg4525" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256.4 291.5" width="2199" height="2500"><style>.st0{fill:#d4b830}.st1,.st2{opacity:.986;fill:#ebebeb;fill-opacity:0;enable-background:new}.st2{fill-opacity:.9216}.st3{fill:#fdd83c}</style><g id="g5193" transform="translate(4.988 -113.385)"><path id="path5113" class="st0" d="M18.8 375.4L-5 113.4l256.4.1-23.6 261.7L123 404.8 18.8 375.4zm189.7-14.3l19.9-224.4h-105l.8 247.5 84.3-23.1zm-94.9-191.5H88.1l-.3 134.3-49.5-13.5.1 30.7 75.2 20.3V169.6z"/><path id="path5159" class="st1" d="M105.2 338.9c-3.3-1-19.6-5.4-36.2-9.9l-30.1-8.1v-15.1c0-14.8 0-15.1 1.5-14.6.8.3 11.8 3.3 24.4 6.8l22.9 6.3.2-67 .2-67h25v85.2c0 67.7-.2 85.2-.9 85.2-.5-.1-3.7-.9-7-1.8z"/><path id="path5157" class="st2" d="M38.4 321.1l-.1-30.7s31.6 8.9 49.5 13.5l.3-134.2h25.5v171.7l-75.2-20.3z"/><path id="path5117" class="st3" d="M123.4 136.6h105L208.5 361l-85.1 23.1V136.6zm79.7 186.8l6.9-83.9-51 5.7v-44.8l54.4-.2 2.2-30.6-82.1.4 1.1 111.4 49.6-8.5-.7 24.8-50 13.3.5 30.4 69.1-18z"/></g></svg>
