### ISSUE TITLE
Icon Request: fa-wizard-hat

### ISSUE THREAD

**Issue by mssteinke** [FortAwesome/Font-Awesome#11417]
I know this has been asked and answered, but the answer was to use the fa-magic icon.  I agree with this, except I need to use magic for a snap-in called "Automation" and the gears are already in use too.  I could really use a wizard hat if you would be so kind?  Thanks for your consideration.

Oh, and same use case.  It would be used to represent a guidance system for configuring my application.  Thanks again!

**Comment by tagliala** [comment]
Hi,

Thanks for being part of the Font Awesome Community.

Your request for adding a wizard is legit, but I would like to spend a few words on your example the use case

> I need to use magic for a snap-in called "Automation" and the gears are already in use too. I could really use a wizard hat if you would be so kind?

I'm not convinced about this use case.

I think that using `fa-magic` and a `wizard-hat` for different purposes in the same interface is still confusing. Why would a `wizard-hat` make something different than a `magic wand`?

IMHO a robot (#519) could represent a third option, or the "Automation" snap-in. Also, it already has several +1s

**Comment by timtjtim** [comment]
Yes, I agree the use case seems strange - but a magic hat would be great. 👍🏼

**Comment by mssteinke** [comment]
I should be more clear.  The automation snap-in is on the user side of the application.  The setup wizard is on the admin side.  The magic wand is being used to represent Automation on the user side of the app, the robot is a good idea; but I look at it and immediately think Android.  I don't really like that.

The gears are used to represent the button that opens administration.  So that is in use too.  I am open to other suggestions, thank you for your reply.  I'm still thinking wizard hat at the moment though.  Or magic wand and something different for automation.

Thanks again.

**Comment by timtjtim** [comment]
You could use spanner for gears and cogs for automation.

**Comment by mssteinke** [comment]
Ok, if you don’t want to do it that’s ok.  Thank you.  I’ll figure something out.

Sent from Mail for Windows 10

**Comment by mssteinke** [comment]
Ok, magic wand for the setup wizard.  Wrench for settings, and Cogs for automation.  Boom, thanks again.  This works for me.

**Comment by timtjtim** [comment]
Although I would still quite like a witch/wizard’s hat, so let’s leave this open.

**Comment by mssteinke** [comment]
Lol. Ok. I would use it.

**Comment by tagliala** [comment]
Good. Renaming this to `wizard-hat` and adding labels

Please use the 👍 reaction to upvote requests

**Comment by sensibleworld** [comment]
Thanks for Promo Wizard for sponsoring this icon! https://fontawesome.com/icons/hat-wizard?style=solid
