### ISSUE TITLE
I need icon

### ISSUE THREAD

**Issue by nicolasmarshall16** [FortAwesome/Font-Awesome#11413]
I´m happy

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which icon do you need?

Happy? => http://fontawesome.io/icon/smile-o/

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by Nharnahagyeman** [comment]
![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f...352d323032302532392e7376672f3132303070782d476f6f676c655f4b6565705f69636f6e5f253238323031352d323032302532392e7376672e706e67.png](https://user-images.githubusercontent.com/99493011/157412397-78d1801a-9342-4b9a-ae4b-2612937482d7.png)

**Comment by tagliala** [comment]
google keep => #18794 

Closing here
