### ISSUE TITLE
Icon request: fa-square-comment

### ISSUE THREAD

**Issue by sashberd** [FortAwesome/Font-Awesome#11426]
How about to add square icon of comment like:

![image](https://user-images.githubusercontent.com/11975561/29551655-75fedb46-871c-11e7-8bbc-38f1f370f85f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2790, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
