### ISSUE TITLE
Icon request: multiple icons

### ISSUE THREAD

**Issue by benratty** [FortAwesome/Font-Awesome#11425]
Multiple home related icons for home repairs related project on Oracle Apex.
Please could you look at these Web app icons for a housing repairs portal project.

Thanks

Front Door
![door](https://user-images.githubusercontent.com/31214623/29524466-cf9b7640-8687-11e7-84eb-08c6aa23c04a.png)
Garage
![garage](https://user-images.githubusercontent.com/31214623/29524480-d75079d0-8687-11e7-9e9e-140665dc88d8.png)
Roof
![roof](https://user-images.githubusercontent.com/31214623/29524491-e0b2c65e-8687-11e7-9b55-f090469ac7c0.png)
Sink
![sink](https://user-images.githubusercontent.com/31214623/29524507-e7ea5c5c-8687-11e7-96a3-10a6a9a66395.png)
Tap or Faucet
![tap](https://user-images.githubusercontent.com/31214623/29524515-eda4a5da-8687-11e7-8385-ef42ff8680f0.png)
WC or Toilet
![wc](https://user-images.githubusercontent.com/31214623/29524542-02d39ef2-8688-11e7-97eb-b77e9a5a731f.png)
Window
![window](https://user-images.githubusercontent.com/31214623/29524557-0dd6b280-8688-11e7-9e1a-6301eb483975.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
