### ISSUE TITLE
Docker icon is not exist

### ISSUE THREAD

**Issue by sauravsingh007** [FortAwesome/Font-Awesome#11422]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, Docker icon does not exist.

You can find a request for a Docker icon at #3316, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
