### ISSUE TITLE
Keep fa-phone consistent (face upper-right)

### ISSUE THREAD

**Issue by kenpropel** [FortAwesome/Font-Awesome#11437]
The "dial" or "phone" icon is almost universally facing upper-right; this is the case with FA4. Somehow, in FA5 beta, this has been turned around and is facing upper-left instead.

Here are common world examples:
<img width="216" alt="common" src="https://user-images.githubusercontent.com/24807338/29643722-c4a366cc-8825-11e7-8ca5-9196bb29ebff.png">

I have a little over 10 apps with voice call function, but yet to find an icon facing left. Well, I guess this is more for consistency sake, not saying it's wrong.

**Comment by tagliala** [comment]
Sorry, I'm going to close this. FA4 icon is ok, I was confused
