### ISSUE TITLE
Oh no! Medium changed it's icon( again)

### ISSUE THREAD

**Issue by sunipeyk** [FortAwesome/Font-Awesome#11431]
What can i say. It has not passed 2 years but they changed their icon and logo again. see: [medium.com](https://medium.com/)

**Comment by tagliala** [comment]
Thanks for reporting this

**Comment by sunipeyk** [comment]
@tagliala I really thank you for your speed reply. 👍 :)

**Comment by My1** [comment]
well the sole good thing of this change (I liked the green one more) is that it works well for iconfonts.

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes
