### ISSUE TITLE
Urgent - Buffer.com icon Missing

### ISSUE THREAD

**Issue by rkmodi** [FortAwesome/Font-Awesome#11438]
Please Add buffer.com Icon...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2110, please add a 👍  reaction to that request.

If you need this icon urgently, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
