### ISSUE TITLE
icon-request: icon-ohloh

### ISSUE THREAD

**Issue by macagua** [FortAwesome/Font-Awesome#1144]
Hi guys

I would like to know if there is possible to get the [Ohloh](https://www.ohloh.net/) icon sign.

Ohloh is a website which provides a web services suite and online community platform that aims to map the landscape of open source software development.

Logo : http://upload.wikimedia.org/wikipedia/en/2/2d/Ohloh_logo.png

Thanks!

Leonardo

**Comment by Neustradamus** [comment]
@davegandy: It has been renamed to OpenHub, can you look it?
- https://github.com/FortAwesome/Font-Awesome/issues/8347

cc: @macagua.

**Comment by macagua** [comment]
@Neustradamus thank you for your feedback
