### ISSUE TITLE
标志哪里，可否增加一个QQ空间的icon

### ISSUE THREAD

**Issue by feiyit** [FortAwesome/Font-Awesome#11442]
标志哪里，可否增加一个QQ空间的icon

一个五角星，里面有个z字

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use English

Closing here

**Comment by icai** [comment]
@tagliala he said  add a icon for Qzone.com social website (Tencent)

**Comment by tagliala** [comment]
@icai thanks

qzone is a duplicate of #3993
