### ISSUE TITLE
Icon request: fa-parentheses/fa-brackets

### ISSUE THREAD

**Issue by shaedrich** [FortAwesome/Font-Awesome#11444]
Hello Font-Awesome Team,
would be great if you could add an icon for parentheses. In my case I need to differentiate between "tags" and "script". But the icon can commonly be used to indicate a function or a dictionary (aka object, structure, etc.).
Thanks in advance!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this request a duplicate of #1797, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by shaedrich** [comment]
Hi!

Oh, sorry! I only searched for parentheses and got no result. Silly me.
