### ISSUE TITLE
Icon Update: fa-youtube

### ISSUE THREAD

**Issue by ryankane** [FortAwesome/Font-Awesome#11457]
The icon [has been changed](https://youtube.googleblog.com/2017/08/a-new-youtube-look-that-works-for-you.html), so I'm not sure how this will be handled. This change comes with Alphabet's (Google) transition to the use of it's [_Material Design_](https://en.wikipedia.org/wiki/Material_Design) across all of its Intellectual Property.

> [_YouTube has a new look and, for the first time, a new logo_](https://reddit.com/r/youtube/comments/6wrty5)

Here is a link to the logo:

> https://www.gstatic.com/youtube/img/branding/youtubelogo/svg/youtubelogo.svg

Not much has changed, they just moved the "Tube" text to the outside and replaced it with the play-button. This new icon is similar to the existing [**`fa-youtube-play`**](http://fontawesome.io/icon/youtube-play) icon.

![YouTube Logo](https://user-images.githubusercontent.com/1094151/29835459-106525fc-8cc0-11e7-8134-8b7eb3c79848.png)

[YouTube Branding](https://youtube.com/yt/about/brand-resources/#logos-icons-colors)

I suggest that the icon is just the wordmark. Simply remove the black bubble surrounding the "Tube" portion of this logo. Not sure how to handle this at this time.

**Comment by tagliala** [comment]
🤷‍♂️

**Comment by pagelab** [comment]
New logo usage guidelines: https://www.youtube.com/yt/about/brand-resources/

**Comment by mosherranch** [comment]
Will the icons for "youtube" and "youtube-square" be updated in v4.7.0 to the new YouTube branding?  These two icons use a vertical stacked version of the old logo, but the new branding requirements only has the horizontal layout and the play button by itself the same as the "youtube-play" icon.  We are wondering if these icons will be updated, or if we need to change our sites to use the "youtube-play" icon instead.

**Comment by tagliala** [comment]
Hi,

this is done in FA5.

The old youtube icon will not be available anymore and it will alias to youtube-play
