### ISSUE TITLE
icon request: icon-beach

### ISSUE THREAD

**Issue by rotoxl** [FortAwesome/Font-Awesome#1145]
Hi,

i love font-awesome and i love you too.

I'd  like to request a few icons:
- icon-pet ![tiposervicio-mascota-0](https://f.cloud.github.com/assets/4495919/546645/cad711c2-c2a1-11e2-9806-fd870c56fca0.png)
- icon-dog http://www.iconfinder.com/icondetails/113440/24/bone_dog_pet_puppy_treat_icon
- icon-cat (though github's is quite close)
- icon-sun
- icon-moon 
  (even meteorology)
- icon-mountain/icon-landscape (right i'm using icon-picture for this purpose)
- icon-beach

Thank you, your work is really awesome

**Comment by nikkiroylance** [comment]
+1 beach

**Comment by tagliala** [comment]
leaving this open as icon-beach

**Comment by DistantParadox** [comment]
+1 For moon, this could be used for the PaleMoon Web Browser.

**Comment by smyl3s** [comment]
+1 beach

**Comment by tekand** [comment]
+1 for beach is there an ETA? It is open for almost 4 years now.

**Comment by aaronbeaton** [comment]
+1 beach

**Comment by sensibleworld** [comment]
Does this icon (https://fontawesome.com/icons/umbrella-beach?style=solid) cover this request?

**Comment by tagliala** [comment]
@sensibleworld it should

I'm going to close here
