### ISSUE TITLE
Displaying icons as pseudo-element content

### ISSUE THREAD

**Issue by Visiluna** [FortAwesome/Font-Awesome#11456]
In previous versions of FontAwesome, I have been able to display icons as content in a css pseudo-element, like this.

`.selector::after { font-family: FontAwesome; content: "\f107"; }`

Using the new SVG framework (beta 5), all the icons being displayed as `<i class="fa fa-angle-down"></i>` are working fine, but I can't seem to use the above CSS method to display pseudo-element content any more.

Am I missing something, is this no longer supported, or is it just not ready yet?

I have included the framework like so:
`<head>`
`    <script src="/js/packs/regular.js"></script>`
`    <script src="/js/fontawesome.js"></script>`
`</head>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use https://github.com/FortAwesome/Font-Awesome-Pro for issues related to FA 5.0
