### ISSUE TITLE
Icon Request: fa-video-camera 

### ISSUE THREAD

**Issue by nimmyy** [FortAwesome/Font-Awesome#11453]
Hi,

I'd like to request an un-filled (outline only) video camera icon for your existing icon: http://fontawesome.io/icon/video-camera.

Example as seen from existing icons: http://fontawesome.io/icon/bell/, http://fontawesome.io/icon/bell-o/

I'd like this to highlight the difference between a selected and unselected camera.

Thank you!

**Comment by Nustix** [comment]
+1

**Comment by tagliala** [comment]
This icon is available in FA5 Pro

https://fontawesome.com/icons/video?style=regular
