### ISSUE TITLE
Icon Request: fa-pallet

### ISSUE THREAD

**Issue by GerritP** [FortAwesome/Font-Awesome#11466]
Hi there,
a package or a box icon would very well complement the Transport Section.

![image](https://user-images.githubusercontent.com/31493266/29900140-64c356a0-8db5-11e7-8673-4a5a6a68bddb.png)
![image](https://user-images.githubusercontent.com/31493266/29900151-71c1e5ec-8db5-11e7-8a94-1662667c0f67.png)

Greetings

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11036, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
