### ISSUE TITLE
Icon Request: fa-snowfall

### ISSUE THREAD

**Issue by nishanka-ss** [FortAwesome/Font-Awesome#11460]
![snow-fall](https://user-images.githubusercontent.com/16914866/29859520-0cd1bcd2-8d80-11e7-99ee-45d68eca3ff2.jpg)

**Comment by aethior** [comment]
Hi @nishanka-ss,

This icon was added in v5.5.0.
Check https://fontawesome.com/icons/cloud-snow

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Also subset of #155
