### ISSUE TITLE
Icon Request: icon-headset

### ISSUE THREAD

**Issue by ComaVN** [FortAwesome/Font-Awesome#1146]
Thanks for an awesome solution to my iconing needs :P

I'd like to request an icon of a headset: basically a variant of icon-headphones, with a mic added.

I'd use it to represent support tickets.

examples:
![headset](https://f.cloud.github.com/assets/3532339/547007/bf5e65c6-c2b4-11e2-8d16-53c37534a885.png)
![support](https://f.cloud.github.com/assets/3532339/547008/da56ef24-c2b4-11e2-8c96-d60f4122f547.png)
![head-with-headset](https://f.cloud.github.com/assets/3532339/547006/bf2d51fc-c2b4-11e2-9c34-feb3dd2cd7f7.png)

**Comment by kringon** [comment]
+1

**Comment by xvilo** [comment]
+1 waiting for it!

**Comment by zach-adams** [comment]
+1

**Comment by shawnmclean** [comment]
+1

**Comment by xvilo** [comment]
SEE! PEOPLE NEED DIS!

**Comment by lenamtl** [comment]
+1
I would use it for chat support

**Comment by JKFriedlander** [comment]
+1

**Comment by rickstar** [comment]
+1

**Comment by tristobal** [comment]
Great idea!

+1

**Comment by saguiitay** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by G-Driver** [comment]
+1 

<img src="https://cdn3.iconfinder.com/data/icons/glyph/227/Headphone-512.png">

**Comment by NShewmaker** [comment]
+1

**Comment by jcbadger** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by mattgow** [comment]
+1

**Comment by zhekaus** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by bgodkin** [comment]
+1

**Comment by MrKoopie** [comment]
+1

**Comment by wedocodeuk** [comment]
+1

**Comment by xvilo** [comment]
+1

**Comment by mikeslim7** [comment]
+1

**Comment by VitalyPankin** [comment]
+1

**Comment by open2discussion** [comment]
+1

**Comment by monsteronfire** [comment]
+1

**Comment by marcuson** [comment]
+1

**Comment by iamjon** [comment]
+1

**Comment by pvds** [comment]
+1

**Comment by heyfellows** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by jmelosegui** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by willia58** [comment]
I suspect that this has already been mentioned, but... 

if it could be designed to stack on top of the `user` icon that provide a customer service icon as well.

**Comment by tbaragao** [comment]
+1

**Comment by tbaragao** [comment]
@tagliala Help us with this icon!!!

**Comment by sanek4life** [comment]
+1

**Comment by haulpd** [comment]
+1

**Comment by ericfmatos** [comment]
+1

**Comment by serweb-labs** [comment]
+1

**Comment by simonc** [comment]
⚠️ Hi everybody. To stop spamming our friends, prefer the Emoji reactions on the issue description. Thanks and have an awesome day! 💕

**Comment by serweb-labs** [comment]
:+1:

**Comment by omargourari** [comment]
+1

**Comment by edwardmcconville** [comment]
+ 1 something for customer service

**Comment by chrisamsterdam1986** [comment]
+1

**Comment by arunkp** [comment]
+1

**Comment by vmtco** [comment]
+1

**Comment by zmeika** [comment]
+1

**Comment by Petrov-Dmitry** [comment]
+1 - user with headset needed

**Comment by arsnic** [comment]
+1

**Comment by ilya-dubovtsev** [comment]
+1

**Comment by Nosoulinside** [comment]
+1

**Comment by ericvillemure** [comment]
+1

**Comment by markhker** [comment]
+1

**Comment by vinnyamp** [comment]
+1

**Comment by GabrielBragaRJ** [comment]
+1

**Comment by Keized** [comment]
+1

**Comment by samupl** [comment]
+1

**Comment by tiagojco** [comment]
+1

**Comment by josecebe** [comment]
+288

**Comment by tiagowanke** [comment]
+1

**Comment by N4Design** [comment]
+1

**Comment by simonc** [comment]
Hey everyone. I'm glad many of us want this icon to come to life! I don't want this issue to be a source of spam for the FA team though.

I know not everyone will respect this but if you read my message please consider adding an emoji-reaction on the main message rather than adding a `+1` comment ☺️ 

Thanks for them ❤️

**Comment by lyh424** [comment]
🙏☺️

**Comment by sergiodlopes** [comment]
+1

**Comment by mehdiagharlou** [comment]
+1

**Comment by teodoz** [comment]
+1

**Comment by akashmantry** [comment]
:+1:

**Comment by aandrade1234** [comment]
+1

**Comment by EstebanFuentealba** [comment]
+1

**Comment by nzmi** [comment]
+1

**Comment by hingram** [comment]
+1

**Comment by YuryKondrashov** [comment]
+1

**Comment by roddeveloper** [comment]
+1

**Comment by katsar0v** [comment]
+1

**Comment by empierre** [comment]
+1

**Comment by eudesB** [comment]
+1

**Comment by gtilflm** [comment]
+1,000,000

**Comment by marketica** [comment]
+1,000,000

**Comment by gu10ng1t** [comment]
+1

**Comment by wenn32** [comment]
any status on this icon? btw +1

**Comment by santiagotoledo91** [comment]
+1

**Comment by marctorresbcn** [comment]
+1

**Comment by kappaknight** [comment]
+1

**Comment by cescobargiraldo** [comment]
+1

**Comment by jackdaniel9** [comment]
+1

**Comment by mgolkardev** [comment]
+1

**Comment by dawesi** [comment]
please note the difference between headset and headphones, headset has a mic.

**Comment by sensibleworld** [comment]
@dawesi Yup :) Icon has been designed and should be out in our next release.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/headset?style=solid

**Comment by gtilflm** [comment]
@sensibleworld : Thanks for your efforts, but it kinda looks like a ghost face to me instead of an actual headset.  Maybe I'm in the minority though.

**Comment by CPOI** [comment]
I'd like one with a non gender human. I;d rather use all font awesome than icons8 combo, 

![image](https://user-images.githubusercontent.com/31348106/48191192-59446e80-e33c-11e8-9658-c79a9fac72b0.png)

in this range
![image](https://user-images.githubusercontent.com/31348106/48191339-bfc98c80-e33c-11e8-846f-746e0b558a10.png)

**Comment by tagliala** [comment]
@CPOI there is another request for that: #5586
