### ISSUE TITLE
Icon request: icon-drone

### ISSUE THREAD

**Issue by dialjam** [FortAwesome/Font-Awesome#11475]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5446 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by jerrywalton** [comment]
so where the drone icon?

**Comment by jerrywalton** [comment]
how about stop playing games about how many/which request and add the drone icon already.
