### ISSUE TITLE
fa-terminal not aligned properly

### ISSUE THREAD

**Issue by Hacksaurus** [FortAwesome/Font-Awesome#11486]
Hello!
When I try to use the fa-terminal icon in [powerlevel9k](https://github.com/bhilburn/powerlevel9k) I noticed that there is a small space before the icon, as shown here:
![screenshot_2017-08-31_19-10-30](https://user-images.githubusercontent.com/24832107/30005638-d19c9d98-909b-11e7-8267-466c55ca932c.png)
Is this a issue with the actual icon? Or powerlevel9k itself... I have created an issue [here](https://github.com/bhilburn/powerlevel9k/issues/612), but nobody has responded so I might assume that this might be an issue with the icon itself.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

What should be the expected behaviour?

I've checked margins on fa-terminal and it does look fine.

Please note that the font awesome isn't a fixed width font (design choice), so some icons could be larger than others

**Comment by Hacksaurus** [comment]
Hm, now that I think about it the issue might be that there is a small space before the terminal...
But how do you get small spaces like this in a terminal?

**Comment by tagliala** [comment]
Could you please post an image with the expected behaviour?

Please use some photoshop/gimp/whatever to edit the above image because I cannot understand the issue

**Comment by Hacksaurus** [comment]
The measurement from the edge of the light gray to the very beginning of the icon is 10px, so what should be expected is another 10px to the right of the icon, or at very least the same length on both sides of the icon. This is what I have currently:
![screenshot_2017-09-03_12-37-47](https://user-images.githubusercontent.com/24832107/30006647-d6f8e312-90b1-11e7-8ae5-311b5131ec8f.png)
On the left side is the 10px length and on the right is just a normal space...
This is what I want to acheive:
![10px shell](https://user-images.githubusercontent.com/24832107/30006651-ecf5ac2c-90b1-11e7-8556-0af111dfdf3f.png)
And even 10px length on BOTH sides of the icon...

I hope this clears up some confusion....

**Comment by tagliala** [comment]
Could you please `fa-square` instead of the terminal icon and check if the issue is still there?

**Comment by Hacksaurus** [comment]
![screenshot_2017-09-04_10-41-08](https://user-images.githubusercontent.com/24832107/30035305-97438cca-915d-11e7-8eed-d6a247e6cf50.png)
The issue seems to be still there...
I think this may be a issue with powerlevel9k, but again... how did they create that small space?

**Comment by Hacksaurus** [comment]
The issue that I have referenced, the problem doesn't seem to be with the icons, but the actual terminal emulator itself...

Closing this issue, because the icons itself to be working fine
