### ISSUE TITLE
Sports icons

### ISSUE THREAD

**Issue by hybrisCole** [FortAwesome/Font-Awesome#11495]
There's lack of sports icons, it would be `awesome` if you add them ;)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
