### ISSUE TITLE
Icon Request: Telegram

### ISSUE THREAD

**Issue by nikitavoloboev** [FortAwesome/Font-Awesome#11491]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Telegram is already here: http://fontawesome.io/icon/telegram/

If you have troubles in making telegram icon work, please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here

**Comment by zerochka** [comment]
can you create an icon without circle ?

**Comment by tagliala** [comment]
@zerochka feel free to request a new request for an icon which is not official, but keep in mind that brand icons will usually follow brand guidelines
