### ISSUE TITLE
Icon Request: fa-earth-friendly

### ISSUE THREAD

**Issue by NBLFCK** [FortAwesome/Font-Awesome#11490]
Hey there!

Chris from Shopify here - I have a request to add [This Icon](https://s3.amazonaws.com/tasker-chat/uploads%2Fd727b1970b1a986106fddf33e6e619df%2F1504564807504-togmxzxg8v-856804e3aa1eeb520399e22778850434-Icon_Earth+Friendly.png) to the dirctory as per some requests.

Let me know what you can do.

Thanks :) <3

**Comment by sensibleworld** [comment]
Hey @NBLFCK doing some Github cleanup and came across this issue, but the link is no longer valid. Feel free to re-open if you have a new preview for us! Thanks!
