### ISSUE TITLE
Icon request: icon-comment-slash, icon-comment-slash-o

### ISSUE THREAD

**Issue by sailtake5** [FortAwesome/Font-Awesome#11499]
comment-slash-o
comment-slash

to match bell-slash

**Comment by tagliala** [comment]
Related to: #1181

**Comment by sensibleworld** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chat icon category](https://trello.com/c/OCAVwJe3/33-chat-icon-category)

**Comment by sensibleworld** [comment]
Released in 5.0.9
