### ISSUE TITLE
Icon request: fa-coins

### ISSUE THREAD

**Issue by Dexter-Andrei** [FortAwesome/Font-Awesome#11492]
There are a lot of requests. This is from 2013 https://github.com/FortAwesome/Font-Awesome/issues/1400

So, Font Awesome, we are in 2017. Where is the "**fa-coins**" icon ????

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add a +1 reaction to #1400

If you need this icon in a short while, please consider using a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
