### ISSUE TITLE
Icon Request: Unsplash

### ISSUE THREAD

**Issue by nikitavoloboev** [FortAwesome/Font-Awesome#11508]
It is a [really popular website](https://unsplash.com) to share photographs. They have a very simple looking logo too.

It would be wonderful if it would be added. Thank you.

**Comment by peiche** [comment]
As far as I can tell, it's pretty close (if not identical) to FA's [camera icon](http://fontawesome.io/icon/camera/).

**Comment by tagliala** [comment]
I agree with @peiche 

Closing here

**Comment by purzlbaum** [comment]
Unsplash has a new logo, so I'll open this issue again. Here's the svg code if you need it: 

`<svg  class="icon icon--unsplash" fill="currentColor" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="32px" height="32x" viewBox="0 0 122.4 122.4" style="enable-background:new 0 0 122.4 122.4;" xml:space="preserve"><path d="M122.4,54.1v68.3H0V54.1h38.6v34.1h45.3V54.1H122.4z M83.9,0H38.6v34.1h45.3V0z"/></svg>`

**Comment by purzlbaum** [comment]
@tagliala oh, that was quick.

**Comment by juanencalada** [comment]
Thanks guys! I was just about to open this request when I found it here. :)

**Comment by bcye** [comment]
So are there updates?

**Comment by eric-addcream** [comment]
+1 on this
Unsplash requires their logo to shown when using their API so this would be very nice to have.

**Comment by ian-patel** [comment]
+1

**Comment by stphnwlkr** [comment]
+1

**Comment by Bjornftw** [comment]
+1

**Comment by kirillzakharov** [comment]
@tagliala Any updates on this? We've had a few requests from our API partners about Unsplash in Font Awesome. 

Let me know if you need anything specific for the SVG. You can find our symbol here: https://unsplash.com/press

Various SVG sizes in here: https://www.dropbox.com/sh/y70gjcewa1n4p6u/AADCrWX6jCk19O2ZbIO4UUk4a?dl=0

**Comment by tagliala** [comment]
@kirillzakharov please take a look at [Brand Icons Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work

You may also be interested in a custom version of Font Awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by bcye** [comment]
For those +1'ing in this thread:

> Found an existing request you’d like to see added in? Help it get to the top of the Icon Leaderboard by adding a  to the request in our Font-Awesome GitHub project.
- https://fontawesome.com/community/leaderboard/brands#faqs

**Comment by tagliala** [comment]
Hi,

icon released in 5.13.1

https://fontawesome.com/icons/unsplash?style=brands

**Comment by stphnwlkr** [comment]
Thank you!!!!
