### ISSUE TITLE
Icon request: icon-coloradd-symbol(s)

### ISSUE THREAD

**Issue by Scummbuddy** [FortAwesome/Font-Awesome#11505]
Hello all!

I have some suggestions for new Accessibility Icons.

ColorADD has come out with universal color symbols to aid those suffering from color-blindness, but these symbols may be used everywhere to help differentiate colors. These could be added onto legends next to pie/bar charts to help those understand the colors. The card game UNO has just started to incorporate the symbols.

More information can be found here:
http://www.coloradd.net/code.asp

The current fa-square and fa-square-o could be used, or similar and larger ones may need to be added, to allow for the stacking of smaller icons inside.
While stacking is almost the idea behind ColorADD, they couldn't be stacked easily in FA. For instance, "purple" and "brown" are more different than just a line between the two wedges.

If we started with:
"fa-coloradd-blue, fa-coloradd-green, fa-coloradd-yellow, fa-coloradd-orange, fa-coloradd-red, fa-coloradd-purple, fa-coloradd-brown"
we would have the seven basic colors.
From there, stacking would work to create the seven color-light and seven color-dark icons. (Lighter colors could be shown stacked with a *new* 'fa-coloradd-white' and darker colors could be shown with 'fa-inverse' and a *new* 'fa-coloradd-black'.

That just leaves creating four more. Two of them (fa-coloradd-grey-light and fa-coloradd-grey-dark) could be made from one smaller-squircle (fa-coloradd-grey?) and just fa-inverse'd and stacked as needed.
The last two gold and silver require creating, in their terms, a parenthesis to the left of a large squircle; one coloradd-white and one coloradd-black. Gold and silver would likely require them being their own call out "fa-coloradd-gold" and "fa-coloradd-silver" because of alignments if we tried to stack icons.

And finally, if this is a duplicate, I am sorry. The Git search and Advanced Search appears to not be all that good at searching for previous suggestions. :(
![code_adicao](https://user-images.githubusercontent.com/31778541/30229961-09b7334a-94b2-11e7-86be-628fdf227fa8.gif)
![code_cinzas](https://user-images.githubusercontent.com/31778541/30229965-09bf0bd8-94b2-11e7-89fe-f366180dd15a.gif)
![code-claro-escuro](https://user-images.githubusercontent.com/31778541/30229964-09bc2f6c-94b2-11e7-96b1-606d46cb7b54.gif)
![codigo](https://user-images.githubusercontent.com/31778541/30229963-09b8877c-94b2-11e7-92fa-f62f1ce7ca5b.gif)
![codigo-final](https://user-images.githubusercontent.com/31778541/30229962-09b737b4-94b2-11e7-9881-272ec05d3eff.gif)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome has a high regard of accessibility, but unfortunately I cannot leave this issue open at the moment.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
