### ISSUE TITLE
Icon Request: fa- Cross, Star of DAvid etc

### ISSUE THREAD

**Issue by lainaDAZE** [FortAwesome/Font-Awesome#11509]
I would like a cross, star of David etc for religious websites I've been working on.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Cross: #1611 
kaaba: #9371

If you want to request a star of david, please rename this request and I will reopen

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
