### ISSUE TITLE
Update request: icon-bitbucket

### ISSUE THREAD

**Issue by Naereen** [FortAwesome/Font-Awesome#11519]
Hi,
[Bitbucket](https://bitbucket.org/) has updated their logo a few days ago.
Could FontAwesome update the icon for Bitbucket's logo?
New logo looks like this: ![](http://perso.crans.org/besson/_images/.bitbucket.jpg)

**Comment by tagliala** [comment]
Have they any monochrome version of this logo?

**Comment by Naereen** [comment]
I don't know what they officially have.
The logo on their website is a SVG with a js hack to make the color gradient.

I created a gray-scaled version for my website:
![](http://perso.crans.org/besson/_images/.bitbucket.png)

**Comment by tagliala** [comment]
Hi,

we cannot implement color gradients in a webfont. We need a single color logo

**Comment by Naereen** [comment]
I know. (I am not related to Bitbucket by the way)
Do you have an idea of how to get a single color logo from the grayscale?

**Comment by timtjtim** [comment]
It would appear that they do not allow a single colour logo - https://atlassian.design/guidelines/brand/logos

**Comment by Naereen** [comment]
@timtjtim Thanks for finding this.
Then I guess there is nothing else to do but to ask them.

If someone from fontawesome wants to send an email to someone at Atlassian and ask them what they prefer (either provide a nice SVG/webfont single color version of their logo, or decline the update).

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes

**Comment by Naereen** [comment]
OK @tagliala, thanks for letting me know.
