### ISSUE TITLE
The gift icon looks like a pressure cooker

### ISSUE THREAD

**Issue by zeroheure** [FortAwesome/Font-Awesome#11517]
I asked some women about the gift icon and none of them understood it. Of course that doesn't mean that all women can't understand it. But after one had said that it looks like a pressure cooker, I must admit that it's true.

**Comment by tagliala** [comment]
@zeroheure what about the new icon? https://fontawesome.com/icons/gift?style=solid

https://jsfiddle.net/tagliala/yxqqchjs/

**Comment by zeroheure** [comment]
Still look like a pressure cooker. Or a martian monster. :-)
IMHO the main problem is in the ribbon : 
1. color change between side and bow tie
1. loop are the same size
For example see this well known icon :
https://i.pinimg.com/236x/93/77/71/937771389a8b3218e2b66cd6d6e2a80c--programming-icons.jpg
