### ISSUE TITLE
Icon Request: fa-makingfuss

### ISSUE THREAD

**Issue by Iberocom** [FortAwesome/Font-Awesome#11512]
Hi!
The icon corresponds to an app of social, cultural and sporting events.
I would like to have the icon so that my users can add it next to the social networks.
Best regards
Hector Romero
![icosocialnet](https://user-images.githubusercontent.com/17808413/30271939-78d3a366-96f2-11e7-9a06-e175e503d7a4.gif)
![ico-squaresocialnet](https://user-images.githubusercontent.com/17808413/30271938-78d17122-96f2-11e7-95b1-f6bdababf345.gif)

**Comment by Iberocom** [comment]
Can someone tell me what is the next step?

**Comment by tagliala** [comment]
@Iberocom please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Iberocom** [comment]
Perfect. Thank you tagliala!
