### ISSUE TITLE
Lock the issues to avoid spam when followers are writing +1

### ISSUE THREAD

**Issue by HLFH** [FortAwesome/Font-Awesome#11516]
Hi,

When Font Awesome users are writing +1, can you lock the issue to avoid spam?
We have lot of spam on this repo, it is maybe the worst repo in terms of "+1". 
Your followers often use the "+1" instead of the emoji on top of the issue.
It should change.

Thank you,

**Comment by wolfy1339** [comment]
This is currently impossible, if you lock the issue then you can't add reactions (emojis) to show your support. But, I agree that a solution should be found for that problem

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

+1s comments are not against our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons) but they also don't meet them.

Sorry but we can do a little for this. Even if I delete the spamming comment, the notification would have been already sent (sorry if the verbs are wrong, I'm not an English native speaker)

**Comment by HLFH** [comment]
@wolfy1339 Yes, when an issue is locked - often because of spamming, GitHub followers of the repo should still be able to use the emoji reactions feature. I contacted GitHub: I can dream. If they answer, I will come back to you.

**Comment by HLFH** [comment]
I finally unsubscribed to all FontAwesome issues.

**Comment by tagliala** [comment]
@HLFH sorry about that.

The voting system is not ready yet we cannot do differently.

The following statement is still valid:

> Even if I delete the spamming comment, the notification would have been already sent (sorry if the verbs are wrong, I'm not an English native speaker)

And... I should post another comment explaining why I've deleted the +1, resulting in too much effort on my side
