### ISSUE TITLE
Icon Request: fa-skin or fa-theme

### ISSUE THREAD

**Issue by zotopteam** [FortAwesome/Font-Awesome#11524]
Icon Request: fa-skin or fa-theme ,it is common in the web use,thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

This request does not meet: 
> * Attach a single color image or two that represent the idea you're going for.
> * Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
