### ISSUE TITLE
TTF/OTF in Adobe Animate

### ISSUE THREAD

**Issue by pwnlusa** [FortAwesome/Font-Awesome#11529]
Hi guys. I'm developing apps in Animate and use _FontAwesome_ characters in my source as font all the time (windows machine). Where 4.x versions were perfectly usable, the pro version 5 I just bought shows up as "_undefined_" and a nearly empty character set. Installed the font 4 times, rebooted machine, checked registry entries, no luck. 

Any ideas?

![undefined fontawesome 5](https://user-images.githubusercontent.com/7004566/30443201-8f82ef70-9933-11e7-9ab8-2f47d46bb918.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use the pro repository to report this issues
