### ISSUE TITLE
Font-Awesome icons disappears only after page refresh in IE11. 

### ISSUE THREAD

**Issue by anuragvats25** [FortAwesome/Font-Awesome#11534]
IE8 has some issues with @font-face when combined with :before. Font Awesome uses that combination. If a page is cached, and loaded without the mouse over the window (i.e. hit the refresh button or load something in an iframe) then the page gets rendered before the font loads. Hovering over the page (body) will show some of the icons and hovering over the remaining icons will show those as well. See issue #954 for details.

IE11 is having the same issue ? Or it has been fixed in IE 11 ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I don't know if IE11 has the same issue.

There are other issues on IE11:
- #11250
- #7681
- #7375
- #10389

Closing here, please search for IE11 if you need more information
