### ISSUE TITLE
Icon Request: icon-kidney

### ISSUE THREAD

**Issue by jmesserer** [FortAwesome/Font-Awesome#11538]
![kidney-2](https://user-images.githubusercontent.com/304973/30603819-61c3f454-9d2e-11e7-84f4-2b8d3b53c9cc.PNG)
![kidney-1](https://user-images.githubusercontent.com/304973/30603818-61c09a5c-9d2e-11e7-9a2e-8a915d67c21d.PNG)

**Comment by Emi-C** [comment]
"payment icons" lol

**Comment by aethior** [comment]
Hi @jmesserer,

This icon was added in v5.2.0.
Check https://fontawesome.com/icons/kidneys

Regards.

cc/ @tagliala
