### ISSUE TITLE
Icon Request - torn sheet

### ISSUE THREAD

**Issue by Plavozont** [FortAwesome/Font-Awesome#11548]
This is for the case if something is broken on a web-site. Maybe some other icons that could be found by "broken", "fault", "error", "not found", "restricted" or "access denied" keywords.

![tornsheet](https://user-images.githubusercontent.com/7393355/30730576-46ece526-9f92-11e7-8540-5bf0cf493655.png)

**Comment by aethior** [comment]
Duplicate of #12408. (_the title of the other request is more clear and has more upvotes_)

cc/ @tagliala
