### ISSUE TITLE
New icon request

### ISSUE THREAD

**Issue by neilcor** [FortAwesome/Font-Awesome#11549]
Hi there:

Would like to request a new icon that represents "mapping of users".

Thanks in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide an example

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
