### ISSUE TITLE
Icon request: icon-pill

### ISSUE THREAD

**Issue by anavrinny** [FortAwesome/Font-Awesome#11541]
![image](https://user-images.githubusercontent.com/32119761/30626900-727d4222-9e10-11e7-8ee9-866c18e29be1.png) 
![image](https://user-images.githubusercontent.com/32119761/30627131-c7912458-9e11-11e7-8915-352dd051109b.png) 
![image](https://user-images.githubusercontent.com/32119761/30627135-d1e290c2-9e11-11e7-824b-8c5e85886aee.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9986 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
