### ISSUE TITLE
Icon request: icon-ethereum

### ISSUE THREAD

**Issue by haydencarlson** [FortAwesome/Font-Awesome#11544]
Hello! I'd love to see a ethereum font awesome icon in the future.

Anyone else want one aswell?

Cheers, happy thursday.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8754, you have already +1'd that request

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
