### ISSUE TITLE
Icon Request: fa-weather

### ISSUE THREAD

**Issue by preese13** [FortAwesome/Font-Awesome#11558]
weather Icons like those at 
https://erikflowers.github.io/weather-icons/
thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

From: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons **(e.g., a set of weather icons to build a forecast application)** our suggestion is to customize Font Awesome.
