### ISSUE TITLE
Icon Request: fa-cc-interac

### ISSUE THREAD

**Issue by jmadore** [FortAwesome/Font-Awesome#11556]
Interac is the Canadian debit scheme.
It is very common to include Interac in any payments related interface.

![image](https://user-images.githubusercontent.com/7064917/30811587-a2c632f8-a1d6-11e7-93f6-591f56e4b30f.png)

**Comment by timtjtim** [comment]
Is it similar to Visa / Mastercard?

**Comment by jmadore** [comment]
Yes, except is Debit only ( money comes out of your bank account immediately)

https://en.m.wikipedia.org/wiki/Interac

**Comment by timtjtim** [comment]
+1 thrn

**Comment by Cat5TV** [comment]
Duplicate 4445

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4445, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by Cat5TV** [comment]
@tagliala the issue you link to is for fa-interac. This issue (the one you closed) is for fa-cc-interac. It's my opinion that this one (fa-cc-interac) is correct, and not the other. The designation should be fa-cc-interac, **not** fa-interac.

**Comment by timtjtim** [comment]
I don’t think the specific name matters in this case - it’s asking for the same icon, right?
