### ISSUE TITLE
Icon request: icon-skull

### ISSUE THREAD

**Issue by GamerXCZ** [FortAwesome/Font-Awesome#11568]
Hello, please add some cool skull icons e.g. ☠

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #918 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
