### ISSUE TITLE
Icon Request: fa-import-export

### ISSUE THREAD

**Issue by TMLakhalani** [FortAwesome/Font-Awesome#11566]
I've checked all icons and I couldn't find any icon which combines import and export all in one. I also tried using fa-arrow-up and fa-arrow-down but not looks that much good. If you think my request will be useful for others as well, please create one 👍

**Comment by kirilmaz** [comment]
+1

**Comment by dennbagas** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for this late feedback

We have some import and export icons now:
https://fontawesome.com/icons?d=gallery&q=import
https://fontawesome.com/icons?d=gallery&q=export

Could you please provide an example of how this icon should look like?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
