### ISSUE TITLE
Icon request: icon-discord

### ISSUE THREAD

**Issue by Snarr** [FortAwesome/Font-Awesome#11573]
Use Cases:

- On my gaming community site I can add Discord to my social media section since that section is exclusive to FontAwesome icons
- I can add my Discord as a quick-link on my custom new tab page extension
- I can add my Discord to the bottom of my personal website as a contact method.

![Discord](https://vignette.wikia.nocookie.net/the-miners-haven-project/images/d/dd/Discord.png/revision/latest?cb=20170308033546)
![Discord2](https://www.adkgamers.com/uploads/monthly_2017_07/discord2.png.5e0948011f34c73b8a4be46e756544b4.png)

**Comment by tagliala** [comment]
Will be available in FA5

#7574
