### ISSUE TITLE
Icon Request: Driver icon & Activity Tours icon

### ISSUE THREAD

**Issue by maggisam** [FortAwesome/Font-Awesome#11577]
Hello my name is Magnus and I am new here on the forum.
I hope I am doing this the right way :)

1. I am in a need of a icon that I can use for my service. I am hiring myself out as a "Driving Tour Guide", So the best icon would be of a User and a Steering wheel.
![driver](https://user-images.githubusercontent.com/32422595/31049988-db3e8a7a-a62e-11e7-92ed-d6bfd51293df.jpg)

2. I am also in a need of a icon that would describe a the general term "Activity Tours". I will be using this icon to point my clients to a special page where they should book the third party activity tours (fx. snowmobile, diving/snorkeling, horse back riding, paragliding, glacier hiking, helecoper tours.......)
I am finding it difficault to find any symbols on google that would explane the general term "Activity Tours", however I do find many icons that describe 1 single activity/sport. Maybe somehow combine these icons here below somehow.
![tours](https://user-images.githubusercontent.com/32422595/31049991-e5aef8b4-a62e-11e7-8e61-5baa681bda1d.png) ![horse](https://user-images.githubusercontent.com/32422595/31050031-84e1702e-a62f-11e7-82e6-5c7dc2ad7270.png) ![paragliding](https://user-images.githubusercontent.com/32422595/31050034-89f482a4-a62f-11e7-9600-6930510bb73e.png) ![climb](https://user-images.githubusercontent.com/32422595/31050052-c4c7727e-a62f-11e7-9555-32299c1bbea4.png)

Thank you very much in advance

--
Magnus

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
