### ISSUE TITLE
font-family names don't match "Full Name"

### ISSUE THREAD

**Issue by EHackettTriCore** [FortAwesome/Font-Awesome#11576]
TL;DR 
Xcode and iOS require the font's full name to match font-family names.

I spent a couple hours this morning trying to get Font Awesome 5 Pro Light & Light working in Cordova for iOS and ran into an issue where the full name didn't match the css font-family: preventing it from being used in xcode.

The CSS name in `5.0.0-rc2` is `Font Awesome 5 Light` vs the font's full name `Font Awesome 5 Pro Light` - missing 'Pro'. This prevents Xcode and iOS from correctly connecting the two and results in a Error `An error occurred trying to load the resource.`.

**Comment by tagliala** [comment]
Hi,

could you please open this issue in the FA5 Pro repository?

https://github.com/FortAwesome/Font-Awesome-Pro

**Comment by EHackettTriCore** [comment]
Oh yeah sorry I didn't realize I was logged into a different git profile than the one I have access to and when I tried to visit it didn't load I assumed it had merged here or something my bad.
