### ISSUE TITLE
Icon Request: fa-responsive

### ISSUE THREAD

**Issue by iamjagannathr** [FortAwesome/Font-Awesome#11575]
Dear fontawesome team,
         Please add an icon for responsive. I always had to use images for this. Please add this.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1446, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
