### ISSUE TITLE
Play button not well centered

### ISSUE THREAD

**Issue by onigetoc** [FortAwesome/Font-Awesome#11578]
Play button not well centered.

I did a audio video player and the Font Awesome play button is not well centered and it look like my play button is moving, i know we can play with the margin ect but in between i have a buffering seeking loading and we can see it moving because i did put a margin on the play button to fix the fact that it is not in the center.

`fa-play` `fa-pause`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add `fa-fw` class to your icons

Ref: #3741
