### ISSUE TITLE
Icon Request: fa-thumbnail

### ISSUE THREAD

**Issue by riginoommen** [FortAwesome/Font-Awesome#11581]
Profile Thumbnail

**Comment by riginoommen** [comment]
https://www.google.co.in/search?q=profile+thumbnail&client=firefox-b-ab&dcr=0&tbm=isch&imgil=gPS-U7TWGlaRJM%253A%253B3-t_l235CtPGVM%253Bhttp%25253A%25252F%25252Fwww.netsocialblog.com%25252F2015%25252F01%25252Ffacebook-tweak-make-your-profile.html&source=iu&pf=m&fir=gPS-U7TWGlaRJM%253A%252C3-t_l235CtPGVM%252C_&usg=__kG-i7Q3zwX7mepEAreMe8GpM1nc%3D&biw=1920&bih=921&ved=0ahUKEwiLj7Pxv9TWAhUGSI8KHU8dDFQQyjcINA&ei=iojTWYuiBIaQvQTPurCgBQ#imgrc=gPS-U7TWGlaRJM:

**Comment by RoofTyler** [comment]
Isn't this just basically [fa-user](http://fontawesome.io/icon/user/) with a background?

**Comment by riginoommen** [comment]
Oh yes its the same thanks for pointing out it will be good if we add reference to fa-user with fa-thumbnail
