### ISSUE TITLE
Network icon

### ISSUE THREAD

**Issue by JKBC1800** [FortAwesome/Font-Awesome#11585]
I could not locate network icon in V4.7. Please suggest a solution to address this issue. Will appreciate you advise and solution.
Thanks
JKBC

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the late reply, I've missed this request

Could you please clarify? There aren't network icons in 4.7.0

If you want to request a network icon, please 👍 #5944 

If #5944's design is not what you mean, please provide a single color example of the icon you are looking for

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
