### ISSUE TITLE
Icon Request: fa-dinner

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11598]
hardly anything to the restaurant industry
[fa-dinner.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364617/fa-dinner.pdf)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3453, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
