### ISSUE TITLE
Icon Request: fa-burger

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11597]
hardly anything for the restaurant industry
[fa-burger.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364616/fa-burger.pdf)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1961, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
