### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by Flo59Flocon** [FortAwesome/Font-Awesome#11595]
It will be cool to have a discord app icon in Fontawesome.
I'll be able to use it of my contacts on my personnal website instead of a circle.
I think something like this can be great.
![](https://wiki.miranda-ng.org/images/4/4d/Discord-Logo-Black.png)

**Comment by Flo59Flocon** [comment]
Thank you in advance for your answer.

**Comment by tagliala** [comment]
Will be part of FA5

ref: #7574
