### ISSUE TITLE
Some icons not displaying properly in OS X

### ISSUE THREAD

**Issue by SublymeRick** [FortAwesome/Font-Awesome#11591]
A client sent me this screen shot of a credit card entry field:
![image](https://user-images.githubusercontent.com/3813238/31189184-f50755b0-a8fc-11e7-971d-047f261714f1.png)

Here is what that form is supposed to look like (and does on windows)
![image](https://user-images.githubusercontent.com/3813238/31189198-04340fd8-a8fd-11e7-84b0-1b7a24ae9df1.png)

I'm not sure whats going on. I know she does not have the font awesome font installed on her computer.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check that you are not including (directly or indirectly, through plugins) two versions of font awesome

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up, point 5

**Comment by SublymeRick** [comment]
@tagliala thanks for the response. I am not loading any additional font-awesome css or fonts:

![image](https://user-images.githubusercontent.com/3813238/31193637-4f4f2860-a90a-11e7-88fb-b37c9ad37d27.png)
The ones on the bottom are adobe type kit font packages.

![image](https://user-images.githubusercontent.com/3813238/31193656-604e5bea-a90a-11e7-95be-cc3a7b9cb494.png)

I've checked all css files to ensure there are no references to "fontawesome" in them.

**Comment by SublymeRick** [comment]
Also I've verified there are no bugs in the HTML and I even tried to swap the icons around and it seems no matter where I put `fa-address-book` it shows up blank on a mac

![image](https://user-images.githubusercontent.com/3813238/31195131-dd8da224-a90e-11e7-894e-0dd8419579b5.png)

**Comment by timtjtim** [comment]
Can you send the link to this page?

Tim Hitchins

**Comment by SublymeRick** [comment]
This is all local dev stuff so there is no link I could send you at the moment. Let me see if I can replicate it on the server and I'll send you a link to that.

**Comment by SublymeRick** [comment]
I got it working now. I just downloaded a fresh copy and over-wrote the font files and it works. Strange.
