### ISSUE TITLE
Icon request: icon-viber

### ISSUE THREAD

**Issue by ShamanFromSiberia** [FortAwesome/Font-Awesome#11609]
Hi,

Maybe on 100th time, I need a Viber messenger icon. I don't remember exactly, maybe a few years ago I requested one, but I didn't find it. And still, there's no Viber icon. Please, please, please - create it! I hope very much you'll hear me.

Best regards

P.S. Thanx for other icons!

**Comment by tagliala** [comment]
will be available in FA5

Ref: #3554
