### ISSUE TITLE
Icon Request: fa-softdrink

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11600]
hardly anything for the restaurant industry
[fa-softdrinks.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364619/fa-softdrinks.pdf)

**Comment by tagliala** [comment]
Related to: #6122

**Comment by timtjtim** [comment]
Pretty much a duplicate of that to be honest - at the small sizes these icons get to, a paper drinks cup is unlikely to be distinguishable.

**Comment by tagliala** [comment]
Duplicate of #6122
