### ISSUE TITLE
Icon Request: fa-switch, fa-router, fa-firewall

### ISSUE THREAD

**Issue by ReSTNSX** [FortAwesome/Font-Awesome#11605]
Hi - seeing if anything like the attached examples I created for my app will be in font awesome 5.  If not, if possible to get added.   Can you also send me sample screen shots of any new networking / security ones coming in 5.x?  I bought the 5.x preview package but don't see anything network related. 

Thanks! 

![ls](https://user-images.githubusercontent.com/32644485/31344467-c9e0aac0-ace0-11e7-9f68-71e08e3cff40.png)
![dfw](https://user-images.githubusercontent.com/32644485/31344468-c9e18936-ace0-11e7-9c5e-76c64eacebeb.png)
![lr](https://user-images.githubusercontent.com/32644485/31344470-ca1fc318-ace0-11e7-978a-2b31f958183b.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
