### ISSUE TITLE
Icon Request: fa-dessert

### ISSUE THREAD

**Issue by tzeller** [FortAwesome/Font-Awesome#11601]
hardly anything for the restaurant industry in the icon set so far
[fa-dessert.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364620/fa-dessert.pdf)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5561, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
