### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by robertjliguori** [FortAwesome/Font-Awesome#11608]
It would be nice to have explicit icons for all of the following: 

1  TOWER 
2  STACK 
3  TANK 
4  NAVAID
5  BLDG 
6  FENCE 
7  POLE 
8 GEN UTIL
9 COOL TWR 
10 T-L TWR 
11 BLDG-TWR 
12 CTRL TWR
13 BRIDGE
14 SIGN 
15 LGTHOUSE 
16 ELEC SYS
17 WINDMILL 
18 CATENARY 
19 ELEVATOR 
20 TRAMWAY
21 CRANE 
22 MONUMENT 
23 DOME 
24 SPIRE
25 STADIUM 
26 RIG 
27 REFINERY 
28 PLANT
29 AG EQUIP 
30 DAM 
31 BALLOON 
32 UTILITY POLE
33 WINDSOCK 
34 ANTENNA 
35 ARCH 
36 MET 
37 GRAIN ELEVATOR 
38 HANGAR

Reference: https://www.faa.gov/air_traffic/flight_info/aeronav/obst_data/

Thanks,
Robert

**Comment by timtjtim** [comment]
As the suggestion guidelines say, we like 1 icon per request, not 38 icons.

**Comment by timtjtim** [comment]
1. #8686
2. #11203 maybe - what do you mean by stack?
3. #10168 or #3656
4. 
5. What is a BLDG? Building? #8941
6. #10980
7. What's a pole? You want a line?
8. Whats a GEN UTIL?
9. #3325 is the closest to a cooling tower.
10. What's T-L TWR?
11. What's BLDG-TWR?
12. #8687
13. #4053
14. A sign representing what?
15. #5579
16. #2766 might be what you want?
17. #1300 although what they're suggesting is what I'd call a wind turbine. Is that what you want? I can't find a windmill which looks like a dutch windmill.
18. You want an icon which is a curved line?
19. #6047
20. #9181 
21. #4084 although that's also a poorly defined request.
22. Would statue be what you want - #7509? If not, what is a monument?
23. 
24. #2088 is the closest, but the suggestions do not have a spire.
25. #10540
26. #3644
27. 
28. #3810 is a living plant. You might mean building site plant like #2997 and as I said above, there's #4084 for crane / bulldozer. 
29. #5052 is a tractor
30.
31. #10177 or #3398 
32. See my response to 7.
33. In #2587 someone requested a windsock, but that request is also too broad.
34. #2581
35. 
36. I don't know what a MET is?
37.
38.

Please add a 👍 to each of the requests I referenced. Next time, please search before you ask, and split your requests up.

**Comment by tagliala** [comment]
@timtjtim wow, thanks, amazing job! 😮 

@robertjliguori 

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our contributing guidelines.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by timtjtim** [comment]
Lectures were cancelled today, needed something to do :P

**Comment by robertjliguori** [comment]
Thanks for the info... this is frequency of each item in the requested set...

TOWER: 115989
POLE: 63181
WINDMILL: 53148
BLDG: 40153
T-L TWR: 34029
FENCE: 14139
SIGN: 6285
TANK: 6212
CATENARY: 4896
NAVAID: 4747
STACK: 4099
GEN UTIL: 2354
ELEVATOR: 1930
ELEC SYS: 1817
BLDG-TWR: 698
CTRL TWR: 620
BRIDGE: 594
CRANE: 499
SPIRE: 332
PLANT: 293
UTILITY POLE: 202
RIG: 176
AG EQUIP: 159
MONUMENT: 129
REFINERY: 122
DAM: 89
COOL TWR: 87
DOME: 81
STADIUM: 37
TRAMWAY: 35
BALLOON: 13
ANTENNA: 12
LGTHOUSE: 9
MET: 7
ARCH: 5
WINDSOCK: 2
GRAIN ELEVATOR: 1
HANGAR: 1

Reference: https://www.faa.gov/air_traffic/flight_info/aeronav/obst_data/

**Comment by timtjtim** [comment]
I don’t think you really listened to us - as you can see many of the icons you ask for are already requested. Those that have not been requested need to be requested as individual issues, one for each icon. Do not make new requests for icons that have already been asked for; instead add a 👍🏼 to them. In addition a few of the ones you requested are really unclear - what’s a GEN UTIL, what’s a T+L TOWER etc. Re read my first message carefully, then follow the instructions we’ve given you.

**Comment by tagliala** [comment]
@robertjliguori although you could open individual issues (providing single color, 16px size suitable examples for each icon), having care of [searching for duplicates before](https://github.com/FortAwesome/Font-Awesome/search?type=Issues), I should advise you to consider a custom build of font awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Quoting from the above wiki:

> So, if you need a new icon in a short while, **or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application)** our suggestion is to customize Font Awesome.

(**emphasis** mine)
