### ISSUE TITLE
Do I need to include FontAwesome.otf for offline bundle?

### ISSUE THREAD

**Issue by kspearrin** [FortAwesome/Font-Awesome#11619]
We download, bundle, and reference font awesome locally since our application is used offline. In copying the font files over I noticed that `FontAwesome.otf` is not referenced in the CSS files:

```
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.7.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.7.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.7.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.7.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Since it doesn't appear to be referenced anywhere, do we need to include `FontAwesome.otf` in our application assets?

**Comment by tagliala** [comment]
Hi,

> Since it doesn't appear to be referenced anywhere, do we need to include FontAwesome.otf in our application assets?

Nope, it is not needed

Hope it helps

Closing here
