### ISSUE TITLE
Icon request fa-box icon

### ISSUE THREAD

**Issue by dharmenderkumar** [FortAwesome/Font-Awesome#11617]
Can we please get box icon for https://www.box.com/home

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1745, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
