### ISSUE TITLE
how to create icon blackberry in font awesome

### ISSUE THREAD

**Issue by urlsnort** [FortAwesome/Font-Awesome#11612]
how to create icon blackberry in font awesome, i'm not found in font awesome

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Wait for font awesome 5 or create a custom version of font awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps, closing here
