### ISSUE TITLE
Icon request: icon-forbidden

### ISSUE THREAD

**Issue by cbernth** [FortAwesome/Font-Awesome#11623]
Hi FA Team
Thanks for the awesome font set!
One thing I was searching for is a 'forbidden' or 'denied' icon to illustrate something you are not allowed to do. Similar idea as e.g. chrome uses when hovering the mouse over a disabled input field.

Use case is to indicate in regular UI that something is not allowed, or special cases where you have to represent a HTTP 403 response (forbidden) which is not exactly the same as an error. Examples - two variants:

![image](https://user-images.githubusercontent.com/32438452/31576444-5a0d5d0a-b0fb-11e7-98f2-eace5049c937.png)

![image](https://user-images.githubusercontent.com/32438452/31576451-67dd1344-b0fb-11e7-925f-a442ac2c87bb.png)

Thanks,
Claus

**Comment by JuaninTorres** [comment]
Are you looking for this?

- http://fontawesome.io/icon/ban/
- http://fontawesome.io/icon/minus-circle/

**Comment by tagliala** [comment]
@JuaninTorres thanks

closing here
