### ISSUE TITLE
Icon request: icon-vr-goggles

### ISSUE THREAD

**Issue by RedRock3D** [FortAwesome/Font-Awesome#11620]
virtual reality goggles 
Here is a web url to a site with many options: https://thenounproject.com/term/virtual-reality/123780/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Possible duplicate of #6590?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/head-vr?style=solid
https://fontawesome.com/icons/vr-cardboard?style=solid
