### ISSUE TITLE
Icon Request: fa-y

### ISSUE THREAD

**Issue by iloveyins** [FortAwesome/Font-Awesome#11629]
Make a 'Y' letter, white background, Y black

**Comment by iloveyins** [comment]
Make a 'W' letter, white background, W black

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a subset of #5019 

At the moment, we are not going to implement this

Please use plain css or something like:

```css
.fa-y:before {
  content: 'Y';
}
```
