### ISSUE TITLE
Icon request: fa-telegram (only paper plane)

### ISSUE THREAD

**Issue by zerochka** [FortAwesome/Font-Awesome#11626]
https://gist.github.com/m8rge/4c2b36369c9f936c02ee883ca8ec89f1 

alone image-icon without circle or square

pls

**Comment by filipesaraiva** [comment]
+1, please! I am using fa-circle behind contact icons in my webpage and Telegram icon is very ugly for this case.

**Comment by zzz** [comment]
+1

**Comment by mingtsay** [comment]
+1

**Comment by MSbitani** [comment]
Looks like this was created: https://fontawesome.com/icons/telegram-plane

**Comment by tagliala** [comment]
@MSbitani thanks!

Closing here
