### ISSUE TITLE
Icon Request: fa-medium

### ISSUE THREAD

**Issue by zoombear** [FortAwesome/Font-Awesome#11633]
Medium blog has changed their icon! Can we get an updated Medium icon?

https://medium.design/logos-and-brand-guidelines-f1a01a733592

![monogram](https://user-images.githubusercontent.com/6636473/31627355-e10142ba-b261-11e7-851a-6c76da975717.png)

**Comment by timtjtim** [comment]
Reported already - will be updated in FA 5.0

#11431

**Comment by aethior** [comment]
This icon is already updated. #17281

cc/ @tagliala

**Comment by aethior** [comment]
> This icon is already updated. #17281

@tagliala check here please. :)
