### ISSUE TITLE
Icon request: icon-abs (math)

### ISSUE THREAD

**Issue by SergoQA** [FortAwesome/Font-Awesome#11640]
Absolute value icon: 
![abs](https://user-images.githubusercontent.com/32882871/31686551-20174868-b38f-11e7-99b8-01996e916e00.PNG)
|x| icon is used:
- on charts in cases when absolute difference value visualization is needed;
- to make absolute and relative differences more human-readable (like actual vs planned time) and easily switch back and forth on the fly for data analytics;

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/value-absolute?style=solid
