### ISSUE TITLE
Icon request: icon-yammer

### ISSUE THREAD

**Issue by nicetohaveyou** [FortAwesome/Font-Awesome#11645]
Hi,

Could you please create font for the below.

![yammer](https://user-images.githubusercontent.com/10613266/31714913-a7978fd6-b3f9-11e7-91c9-06b11f19ca0b.png)

Thanks :)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2707, you should give that a 👍 instead.

Don't forget to search before creating new issues.
