### ISSUE TITLE
Google Plus Official Icon not showing up

### ISSUE THREAD

**Issue by urnewman** [FortAwesome/Font-Awesome#11652]
Hello,

When I put in the line code for the google plus official icon from Font-Awesome, no icon appears, but where the icon should be, the link is still valid and hyperlinked.  Do you know what's going on with this?  I used the same methodology for all of my other social media links, and there seems to be no issue.

**Comment by PeterShaggyNoble** [comment]
What version of FA are you using? `googe-plus-official` was only add in v4.6.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check that you are using the the latest version of FA and please make sure that there isn't a plugin loading an older version

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here

**Comment by tagliala** [comment]
Thanks @PeterShaggyNoble
