### ISSUE TITLE
Icon request: push-button-mobile

### ISSUE THREAD

**Issue by Vikestart** [FortAwesome/Font-Awesome#11659]
![rthjrtjrt](https://user-images.githubusercontent.com/3533096/31855542-7b14523a-b6ad-11e7-8871-01efa3b5e0e9.png)

From view of a push-button mobile phone, to distinguish from the smartphone (fa-mobile) icon and the landline (phone) icon.

**Comment by aethior** [comment]
Hi @Vikestart,

This icon was has been added in v6.1.0. (dupe #1670)
Check https://fontawesome.com/icons/mobile-retro

Regards.

cc/ @tagliala
