### ISSUE TITLE
Icon Request: icon-passport

### ISSUE THREAD

**Issue by galaxy79** [FortAwesome/Font-Awesome#11658]
i'm looking for a passport icon similar to this,
https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjvqJCWvoLXAhUHN48KHd1oDX8QjRwIBw&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F294097%2Fdocument_documents_pass_passport_visa_icon&psig=AOvVaw0vrOEQzIEJ3AAuXQrYCZOy&ust=1508701761061945

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3695, please add a 👍  reaction to that request and post there your example.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
