### ISSUE TITLE
OTF/TTF files are incomplete (some icons are showing as incorrect or squares)

### ISSUE THREAD

**Issue by mac-bhaird** [FortAwesome/Font-Awesome#11655]
Environment:
Windows 10
Word, Visio, etc.

Steps:
1) Download fa files
2) Install OTF file in Fonts
3) Open Word 
4) Change Font to FontAwesome
5) Copy and paste from fa cheatsheet
6) observe the following effect

![image](https://user-images.githubusercontent.com/11042510/31851265-5d2d648c-b630-11e7-841c-f7226be4add2.png)

![image](https://user-images.githubusercontent.com/11042510/31851271-75781af0-b630-11e7-82eb-6934a5caf237.png)

![image](https://user-images.githubusercontent.com/11042510/31851274-7d31f37e-b630-11e7-93c6-58c0866fafb2.png)

![image](https://user-images.githubusercontent.com/11042510/31851278-84dc4322-b630-11e7-937c-74e22c9dea68.png)

This also happens in the ttf file as well.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can partially confirm this.

Please chech that:

1. You have the latest version of font awesome installed (download and reinstall)
2. Do not past icons as HTML

![image](https://user-images.githubusercontent.com/556268/31860645-70092738-b71d-11e7-8da4-15c7994dbc54.png)

Text looks horrible when FA is selected as font, but as you can see icons are there

Hope it helps, closing here
