### ISSUE TITLE
Icon Request: fa-islam

### ISSUE THREAD

**Issue by saeed319** [FortAwesome/Font-Awesome#11656]
Icon Request: fa-islam
Icon Request: fa-christianity
Icon Request: fa-judaism
Icon Request: fa-hinduism
Icon Request: fa-sikhism
Icon Request: fa-athiesm

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are discussing about religion icons here: #2088 .

Sorry but I can't leave this open, it doesn't meet our contributing guidelines https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
>  * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
