### ISSUE TITLE
Font Awesome throughs a bunch of errors in Adobe Muse

### ISSUE THREAD

**Issue by joereplicator** [FortAwesome/Font-Awesome#11653]
Works but I get a bunch of errors  before preview or publish. 

Tested wtih Adobe Muse Support. They refered me to Font Awesome for support. 

Ideas??

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm sorry but I don't know how to help, please try both .ttf and .otf and other webfonts using PUA code area

Let's have a single thread for adobe muse.

Please report your issue here: #10433

Closing here
