### ISSUE TITLE
Size 1.5x

### ISSUE THREAD

**Issue by cinqlair** [FortAwesome/Font-Awesome#11668]
This is not an issue, but I don't know where adding a milestone, so I post here, sorry.

A 1.5x scaller would really be welcome. Standard size are sometime too small and 2x too big.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have [fa-lg](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L23) which sets font size at 1.3em

If you need 1.5, please use custom css. It is as easy as:
```css
.fa-1_5x {
  font-size: 1.5em;
} 
```

Closing here

**Comment by cinqlair** [comment]
Great !!! Thank you : exactly what I was looking for. It was not clear for me on the example page, I through that fa-lg was the standard size. Now I know it was written 
Maybe you could add the standard size icon just above the fa-lg on this page : http://fontawesome.io/examples/
Hope this will help.

**Comment by tagliala** [comment]
Hi @cinqlair , you're welcome

Please note that font awesome icons are no more than text, so you can apply all the css you want on them.

The standard size is based on your application, but if you need pixel perfect icons, you should consider using 14px (16px on FA5)

Then .fa-lg, .fa-2x will enlarge icons using `em` units, so it is up to you. If you need a specific font size (eg: 1.5x), go for custom css
