### ISSUE TITLE
Icon Request: fa-hill

### ISSUE THREAD

**Issue by RiemerBug** [FortAwesome/Font-Awesome#11660]
I´m looking for a icon like this
![image](https://user-images.githubusercontent.com/7061198/31861961-4a1df8be-b736-11e7-8df2-c49cd364cab5.png)
I´ll use the icon for an geographic webapplication to handle the shadedrelief layer.

**Comment by sensibleworld** [comment]
We have these icons now:

https://fontawesome.com/icons/mountain?s=solid&f=classic
https://fontawesome.com/icons/mountains?s=solid&f=classic
