### ISSUE TITLE
icons for furniture

### ISSUE THREAD

**Issue by desspro** [FortAwesome/Font-Awesome#11667]
Hello, sorry for my english. I use a translator to write this request. I use your icons in my projects for sites. For one of them I need furniture icons. I would be grateful if you make a complete category of furniture. Icons: a chair, a table, a stool, a closet.

Examples:
**icon-chair** [1](https://www.iconfinder.com/icons/2216570/chair_furniture_household_office_sit_icon#size=128) [2](https://www.iconfinder.com/icons/2216532/chair_furniture_household_office_sit_icon#size=128) [3](https://www.iconfinder.com/icons/2147994/chair_comfort_decor_furniture_seat_style_icon#size=128)
[**icon-table**](https://www.iconfinder.com/icons/2216573/bar_design_furniture_household_out_side_product_table_icon#size=128)
[**icon-sofa**](https://www.iconfinder.com/icons/2147974/chair_comfort_decor_furniture_seat_sofa_style_icon#size=128)
[**icon-armchair**](https://www.iconfinder.com/icons/2147964/chair_comfort_decor_furniture_seat_sofa_style_icon#size=128)
[**icon-commode**](https://www.iconfinder.com/icons/1831049/drawers_furniture_icon#size=128)

Thank you in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
