### ISSUE TITLE
Icon Request: fa-castle

### ISSUE THREAD

**Issue by garek007** [FortAwesome/Font-Awesome#11661]
I'm looking for an icon I can use for attractions or theme parks. A castle seems like a good option.

**Comment by garek007** [comment]
![castle](https://user-images.githubusercontent.com/15202953/31897436-5f65358a-b7e4-11e7-8fb5-39df19dd4884.JPG)

**Comment by timtjtim** [comment]
+1

**Comment by INGCRENGIFO** [comment]
+1

**Comment by nerdalertdk** [comment]
+1
maybe also add towers

**Comment by aethior** [comment]
Hi @garek007,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/castle and https://fontawesome.com/icons/fort

Regards.

cc/ @tagliala
