### ISSUE TITLE
there is no appointment icon

### ISSUE THREAD

**Issue by umeshramya** [FortAwesome/Font-Awesome#11679]
can one be suggested

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is no appointment icon, but [there](http://fontawesome.io/icon/calendar-minus-o/) [are](http://fontawesome.io/icon/calendar-check-o/) [some](http://fontawesome.io/icon/calendar-times-o/) [calendar](http://fontawesome.io/icon/calendar/) [related](http://fontawesome.io/icon/calendar-o/) [icons](http://fontawesome.io/icon/calendar-check-o/). 

Hope it helps, closing here.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
