### ISSUE TITLE
Icon request: icon-turbines

### ISSUE THREAD

**Issue by newcommervcc** [FortAwesome/Font-Awesome#11675]
Title :
Icon request: icon-automatic (e.g., Icon request: icon-automatic). 
Used:
To start Motors or turbines on a machine

Image example:
![automatic1](https://user-images.githubusercontent.com/33128258/32060997-bb0c66e0-ba70-11e7-90b8-79c7cf9935ff.jpg)
![mode_automatic](https://user-images.githubusercontent.com/33128258/32060998-bb2eef1c-ba70-11e7-985f-f4ad73472789.jpg)

might be for all machines starting and stopping a good idea. 
I thank you very much for caring about this

Best regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

What does exactly your icon represent?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by newcommervcc** [comment]
Hi,

 

ist for a machine. SO there is a automatic process.

this is this Button

than a manuell process. (for this we do show the hand)

 

also ther is a half automatic mode (than we show the sign and the hand in one)

 

so 3 modes. the automatic says it all full automatic turning

 

Gesendet: Donnerstag, 26. Oktober 2017 um 20:38 Uhr
Von: "Geremia Taglialatela" <notifications@github.com>
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: newcommervcc <nicolec1@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Icon request: icon-automatic (e.g., Icon request: icon-automatic). (#11675)


Hi!

Thanks for being part of the Font Awesome Community.

What does exactly your icon represent?

Please take another look at our Contributing guidelines.

**Comment by xmuskrat** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](Seems like fa-fan is close to this)

**Comment by tagliala** [comment]
https://fontawesome.com/icons/fan?f=classic&s=solid
