### ISSUE TITLE
WOFF2 performance alert...

### ISSUE THREAD

**Issue by GlennMartin1** [FortAwesome/Font-Awesome#11677]
I get this performance alert when I run the WP Engine page performance report.

![woff2](https://user-images.githubusercontent.com/30901407/32137526-ab20aae0-bbef-11e7-887c-729a74178e43.jpg)

Something that you can fix to improve performance?

**Comment by tagliala** [comment]
Is this plugin stating that `fontawesome-webfont.woff2` is not in `.woff2` format? 🤔 

Could you please switch to the CDN (instead of self-hosting) and test again?

**Comment by tagliala** [comment]
I think there could be an issue with MIME types on your server

```
$ curl -I http://www.hometowntrailers.com/wp-content/themes/storefront/assets/fonts/fontawesome-webfont.woff2
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 28 Oct 2017 19:15:35 GMT
Content-Type: application/x-font-woff <--
Content-Length: 77160
Last-Modified: Thu, 19 Oct 2017 19:18:19 GMT
Connection: keep-alive
Keep-Alive: timeout=20
ETag: "59e8fa7b-12d68"
X-Type: static/known
Cache-Control: public, max-age=2592000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
```

```
$ curl -I https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2
HTTP/1.1 200 OK
Date: Sat, 28 Oct 2017 19:17:04 GMT
Content-Type: application/font-woff2 <--
Content-Length: 77160
Connection: keep-alive
Last-Modified: Tue, 25 Oct 2016 15:50:14 GMT
ETag: "af7ae505a9eed503f8b8e6982036873e"
x-amz-meta-version-id: 7G0ec11eefKVnJqO2TDXZea7fEDW116p
Server: NetDNA-cache/2.2
Expires: Tue, 23 Oct 2018 19:17:04 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: Say hello back! @getBootstrapCDN on Twitter
X-Cache: HIT
Accept-Ranges: bytes
```

**Comment by GlennMartin1** [comment]
I'm not a super expert in these things.

I am using WP Engine's own CDN. No other CDN involved in any way.

**Comment by GlennMartin1** [comment]
@tagliala Yes, precisely. It is saying the WOFF2 file does not have WOFF2 compression/format.

**Comment by tagliala** [comment]
> No other CDN involved in any way.

Sorry, I need that you fix the mime types on your server (you should be able to do it via .htaccess) or test using the CDN. I'm pretty sure that the .woff2 file is a proper woff2 font, because of:

1. Binary file header
2. Size
3. Woff is bigger :)

**Comment by GlennMartin1** [comment]
I cannot answer your question, since I am not an expert in these things.

>>> I can say that this WOFF2 alert is shown for ALL my WordPress installations running Storefront or WooCanvas.

My host is WP Engine.

**Comment by tagliala** [comment]
Hi, please notify your hosting provider and tell them to set the proper MIME type on .woff2 files.

It should be `application/font-woff2` instead of `application/x-font-woff`
