### ISSUE TITLE
icon-tooth

### ISSUE THREAD

**Issue by hejtillanna** [FortAwesome/Font-Awesome#11674]
Hello!
I could really use a tooth icon on our webbsite: www.liv.se. 
Is that possible?
Have a great day!
Anna

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1289 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by timtjtim** [comment]
Duplicate of #1289
