### ISSUE TITLE
Icon request: icon-surveillancecamera

### ISSUE THREAD

**Issue by imadeddine01** [FortAwesome/Font-Awesome#11672]
i need it to motion that we have surveillance camera in our hostel 
![pict--security-camera-1-tv -photo-and-video---vector-stencils-library png--diagram-flowchart-example](https://user-images.githubusercontent.com/33119389/32046361-c356738a-ba3a-11e7-9042-6398ebc1144d.png)

**Comment by PeterShaggyNoble** [comment]
See #5140.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5140, please add a 👍  reaction to that request.

@PeterShaggyNoble thanks.

Also added surveillance surveillance camera to #5140's title

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
