### ISSUE TITLE
Icon Request: fa-living

### ISSUE THREAD

**Issue by GerardBol** [FortAwesome/Font-Awesome#11685]
Please put in a living room icon. for ex: https://www.flaticon.com/free-icons/living-room_190016

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We should find a better title for this. 

Most of the icons in your link represent a fireplace. Are you requesting a fireplace icon?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by keitetran** [comment]
Like for IoT icon set :(

**Comment by tagliala** [comment]
No feedback, closing here
