### ISSUE TITLE
Icon Request: icon-new-folder

### ISSUE THREAD

**Issue by shokmaster** [FortAwesome/Font-Awesome#1168]
A new folder icon (and its alt version), usually a folder icon like we've got already, and a plus symbol. Something like that:

![icons-folder](https://f.cloud.github.com/assets/1089750/561635/d20b44b6-c492-11e2-873a-f04c4bd8ad75.png)

Thanks for all of your hard work!

**Comment by KevinACrider** [comment]
+1

**Comment by gdufour** [comment]
+1

**Comment by tagliala** [comment]
closing this in favour of #1525
