### ISSUE TITLE
Icon Request: fa-scroll

### ISSUE THREAD

**Issue by jaycbrf4** [FortAwesome/Font-Awesome#11688]
Definitely need to add a mouse or scroll icon to the list. Two or three variations for animating too!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5308, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
