### ISSUE TITLE
icon request: equals sign

### ISSUE THREAD

**Issue by panxzz** [FortAwesome/Font-Awesome#11680]
There's a fa-plus and fa-minus with rounded corners, but no fa-equals icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1133, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
