### ISSUE TITLE
Icon Request: fa-cooker

### ISSUE THREAD

**Issue by RixBtrfly** [FortAwesome/Font-Awesome#11681]
A generic looking slow cooker/pressure cooker icon. Would be great for use in recipes to indicate a slow cooker/pressure cooker application.
![pressure cooker](https://user-images.githubusercontent.com/32779287/32140918-47eb34f2-bc37-11e7-9714-4af76f50daa2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3000, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by RixBtrfly** [comment]
That other one is for just a pressure cooker, wouldn't work for slow cooker.

**Comment by timtjtim** [comment]
+1 for slow cooker.
