### ISSUE TITLE
Icon request: fa-messenger

### ISSUE THREAD

**Issue by melihsaricam** [FortAwesome/Font-Awesome#11691]
Icon request for Facebook Messenger. Facebook Messenger presents a custom share url and is one of the most popular IM services.

![messengericon](https://user-images.githubusercontent.com/1915993/32196425-b3e7e484-bdd1-11e7-92ef-b65c5eb8b307.png)

Official assets are available on [Facebook Brand Resources](https://facebookbrand.com/assets/messenger-toolkit-2).

**Comment by tagliala** [comment]
Will be available in FA5 #6912
