### ISSUE TITLE
ERR_NAME_RESOLUTION_FAILED when trying to get https://use.fontawesome.com/c2cc0f71eb.js

### ISSUE THREAD

**Issue by dslade47** [FortAwesome/Font-Awesome#11699]
Hi,

I get the following error since this morning :
GET https://use.fontawesome.com/c2cc0f71eb.js net::ERR_NAME_RESOLUTION_FAILED

This worked fine up until this morning.

Thanks in advance for your help.

**Comment by tagliala** [comment]
Hi, this is working for me

Could you please check again?

If it doesn't work, could you please tell us where are you from? (country / provider)

**Comment by dslade47** [comment]
I am from France.
I checked again with no success.
But i can see that http://fontawesome.io/ is down today

**Comment by tagliala** [comment]
Hi, I'm from Italy.

I can properly see fontawesome.io as well as your linked file

Could you please check your DNS, your provider status and/or ask friends to check?

**Comment by dslade47** [comment]
I confirm, i have tested from out of my LAN (4G) and it works...strange.

**Comment by tagliala** [comment]
You're welcome, thanks for reporting this. 

Please let us know if this is a temporary problem with your provider or if there are some other issues involved

**Comment by tagliala** [comment]
Reopening because of: https://twitter.com/fontawesome/status/926126964171264000
