### ISSUE TITLE
fa-times icon does not align properly

### ISSUE THREAD

**Issue by robbiemilejczak** [FortAwesome/Font-Awesome#11695]
Issue: 

The fa-times icon does not align vertically with other fa icons, such as fa-plus or fa-minus.

Steps to reproduce:

Choose any font awesome icon and try to align it vertically with the fa-times icon. You can either wrap them in a container with the css properties display set to inline-block and vertical-align set to middle, or display set to flex and align-items set to center. Both will have the same result.

Live example: 

http://jsfiddle.net/xn6wtkco/1/

It's a bit hard to see so I've included the fa-times icon twice, once on each side. If you compare the alignment of fa-plus to fa-minus to the alignment of fa-times to fa-plus you can see that the the minus lines up perfectly with the middle dash of the plus, but the middle dash of the plus does not line up with the intersection in the times icon.

Adding 2/3 px bottom margin to the times icon makes it appear normally but I would rather avoid inline styles,  it would be nice if this behaved similarly to other icons. I am currently using material icons instead but would much rather use fa for this if possible. Obviously not a high priority issue but thought I might bring it to your attention regardless.

**Comment by tagliala** [comment]
I should check this on FA5

**Comment by tagliala** [comment]
I think this is solved in the upcoming FA5, let me know what do you think

![image](https://user-images.githubusercontent.com/556268/32232989-9e294510-be59-11e7-8e70-718c9f6ba000.png)

**Comment by robbiemilejczak** [comment]
yep, that looks perfect. I can't wait for FA5! Thanks
