### ISSUE TITLE
中文官网footer没居底部

### ISSUE THREAD

**Issue by Kelier** [FortAwesome/Font-Awesome#11706]
![image](https://user-images.githubusercontent.com/16694478/32359229-6cea0f58-c01a-11e7-9b1a-57fe0e03ee79.png)
🙀

**Comment by Kelier** [comment]
而且上的nav栏点击无效，这是为何

**Comment by tagliala** [comment]
@robmadole is there an official chinese website of font awesome?

**Comment by robmadole** [comment]
@tagliala no, we do not.

**Comment by tagliala** [comment]
@Kelier sorry, that site is not official and it does not come from Font Awesome. I should recommend you to use http://fontawesome.io/

Closing here

**Comment by Kelier** [comment]
get it
