### ISSUE TITLE
Icon request: icon-pool

### ISSUE THREAD

**Issue by fleurdr** [FortAwesome/Font-Awesome#11709]
An icon for the presence of a swimming pool would be really useful for all websites related to tourism like hotels, vacation rentals and holiday homes but also comunal services etc

**Comment by PeterShaggyNoble** [comment]
This is a duplicate of #3285, you should give that a 👍 instead.

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks, really appreciate
