### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by carlozuribe** [FortAwesome/Font-Awesome#11703]
hi bro.

i need create new icon by my web site, thanx

thanx

![50835-2](https://user-images.githubusercontent.com/18276328/32348400-5f891da4-bff2-11e7-9550-35396034335f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
No feedback, closing  here
