### ISSUE TITLE
Icon Request icon-monero (icon-xmr)

### ISSUE THREAD

**Issue by William2030** [FortAwesome/Font-Awesome#11717]
An icon for monero such as below:
![xmr 1](https://user-images.githubusercontent.com/31596855/32464603-967cc18e-c30e-11e7-900e-d10cb5c54dd4.png)

**Comment by tagliala** [comment]
This icon will be available in the upcoming FA5 

Ref: #8258

**Comment by William2030** [comment]
Great! :1st_place_medal:  :+1:  :+1:  :100:
