### ISSUE TITLE
Icon request: icon-virtual-tour

### ISSUE THREAD

**Issue by TotemaVR360** [FortAwesome/Font-Awesome#11714]
icon request: icon- name Virtual  Tour
![360-tour](https://user-images.githubusercontent.com/33390639/32413744-5798f54c-c218-11e7-8a96-97716816fb6f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5820 , please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tagliala** [comment]
Sorry, this is a brand. Reopening

**Comment by tagliala** [comment]
Nope, this is not a brand.

Could you please clarify this request?

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment]
No feedback, closing here
