### ISSUE TITLE
fa-motorcycle and fa-bicycle not appearing

### ISSUE THREAD

**Issue by mikechalmers** [FortAwesome/Font-Awesome#11716]
Site in progress:

I'm currently using 6 icons with no issue throughout the site, but can't get either of the above to display. Maybe something simple but I've tried for typos and other errors and can't figure it out. It's funny that it's too very similar icons.

Any thoughts? Page here, the motorcycle icon should appear in the first dropdown at the bottom amongst the others (starting "KTM"): http://www.bearenduro.com/tours/

Thanks in advance.

**Comment by tagliala** [comment]
Hi,

you are using font awesome 4.1, those icons were introduced in version 4.3

Please upgrade

Hope it helps

Closing here

**Comment by mikechalmers** [comment]
Thank you!
