### ISSUE TITLE
Use descriptions of the icon not what they could represent

### ISSUE THREAD

**Issue by ChangePlaces** [FortAwesome/Font-Awesome#11710]
The majority are named after what they describe, suitcase, trash, building etc, but some are named after what they could represent, e.g. close instead of 'cross', or legal instead of gavel, These are in the minority, but it'd be nice to see a final push to clean them up.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IMHO this would be a nice feature to have, and it is also endorsed by our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons):

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

Maybe there is room for this in FA 6

**Comment by William2030** [comment]
:+1:

**Comment by sensibleworld** [comment]
Just a note to say that we've implemented this in version 6. All of the old names will still work, but we've changed the base icon names to be more object-based and less opinionated about use case.
