### ISSUE TITLE
Icon Request: fa-box-arrow-up (iphone share)

### ISSUE THREAD

**Issue by jwilliamsen** [FortAwesome/Font-Awesome#11712]
I was looking for the box-arrow-up symbol used on an iPhone to send or save something.  I was going to use it in some help text describing how to bookmark our website on one's phone.

**Comment by aethior** [comment]
Hi @jwilliamsen,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/arrow-up-from-square

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
also duplicate of #10619
