### ISSUE TITLE
Icon Request: Couchsurfing

### ISSUE THREAD

**Issue by travelingorbis** [FortAwesome/Font-Awesome#11711]
I would like a icon for the community site www.couchsurfing.com

A round one like I've on the bottom of my page www.travelingorbis.com

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1938, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
