### ISSUE TITLE
window close icon in thin form

### ISSUE THREAD

**Issue by adeel3612** [FortAwesome/Font-Awesome#11727]
right now the window-close-o is a very bold icon is there any possibility i can get this in the thin form ?

**Comment by PeterShaggyNoble** [comment]
See #9623.

**Comment by tagliala** [comment]
or #1540

**Comment by tagliala** [comment]
Hi, this should be instead a duplicate of #10306 which has been fixed in 5.0.3: https://jsfiddle.net/tgzouajm/46/
