### ISSUE TITLE
Stylesheet loaded but icons not showing up in Chrome 61

### ISSUE THREAD

**Issue by YuKitAs** [FortAwesome/Font-Awesome#11729]
Hello dear fa team,

I've downloaded font-awesome icons in my project and imported `font-awesome.min.css` like

`<link rel="stylesheet" href="resources/font-awesome/css/font-awesome.min.css">`

And used them simply like

`<i class="fa fa-user-o" aria-hidden="true"></i>`

Some more detailed information:
-  The stylesheet was successfully loaded so there was no problem with the path.
-  The icons worked fine in Firefox, but didn't show up in Chrome 61 at all, neither in Win 10 nor Linux, so I guess it was nothing to do with OS.
-  I dont't have any plugin in Chrome that would be conflicting.
-  I've also tried `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">` but nothing changed.

Not sure if this is actually a fa issue or not, but I couldn't come up with anything that probably went wrong.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are too few information to help.

If you think there is an issue with font awesome, please host your project on a public accessible website and I will check

Please also take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

Closing here
