### ISSUE TITLE
fa-search and fa-music not shown on Firefox mobile for Android

### ISSUE THREAD

**Issue by jonaseberledmind** [FortAwesome/Font-Awesome#11720]
I do not understand why, but these icons are shown as 2 characters on Firefox mobile Android v56.0

The screenshots are from [fontawesome.io/icons/](http://fontawesome.io/icons/)

![fa-search](https://user-images.githubusercontent.com/10654488/32486415-deeacd06-c3a6-11e7-97cf-14e8968f31ac.png)
![fa-music](https://user-images.githubusercontent.com/10654488/32486478-081a73de-c3a7-11e7-9cc2-3e81a303694e.png)

I checked all other icons and they are fine.

**Comment by jonaseberledmind** [comment]
Is there anything i can do to provide more info?

**Comment by tagliala** [comment]
Don't have an Android device with firefox 56, cannot test this.

Waiting for feedbacks from other users

**Comment by tagliala** [comment]
> *Nexus 4 sends their regards*

Cannot replicate.

Firefox 57 on Nexus 4
![screenshot_20171123-194322](https://user-images.githubusercontent.com/556268/33186047-0882fb60-d087-11e7-8cc2-07b4a0d914e3.png)
![screenshot_20171123-194308](https://user-images.githubusercontent.com/556268/33186048-0a7d7f26-d087-11e7-8f7f-bdb43b190cb5.png)



Please note that firefox is starting messing up with web pages with unwanted features, as per: #11766 

Please comment here if you find something.

Meanwhile, closing here
