### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by smmsadrnezh** [FortAwesome/Font-Awesome#11739]
Hello,

[Goodreads](https://www.goodreads.com/) is one of the most famous social networks about the books. Having Goodreads brand logo in FA would be nice.

Thanks for the consideration!

![goodreads_icon_1000x1000-aed808dec2093e20867b35cd56d9862d](https://user-images.githubusercontent.com/712956/32661186-2d7674b6-c63b-11e7-97bd-b96c48b36750.png)

**Comment by tagliala** [comment]
Will be available in FA5

Ref #1715
