### ISSUE TITLE
Icon Request: fa-warkk

### ISSUE THREAD

**Issue by mrlubos** [FortAwesome/Font-Awesome#11735]
Hello,

I work on a platform called [Warkk](https://warkk.com), it would be awesome to have an icon under the same name. Our logo could be easily converted into a simple B&W vector version.

![logo](https://user-images.githubusercontent.com/12529395/32607571-5e9395a0-c551-11e7-97ba-a35cb625ae57.jpg)

Thanks for the consideration!

**Comment by aethior** [comment]
The domain ([link](https://warkk.com/)) is currently down and the social networks are inactive since 2017 ([twitter](https://twitter.com/letswarkk/) and [instagram](https://www.instagram.com/letswarkk/)).

cc/ @tagliala

**Comment by mrlubos** [comment]
Yup, wrapped up the project before I received a reply here
