### ISSUE TITLE
Icon Request: fa-wind

### ISSUE THREAD

**Issue by erosdet** [FortAwesome/Font-Awesome#11733]
Icon Request: fa-wind

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5726, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by weilinzung** [comment]
This icon is not showing on the latest 5.5.0 of the desktop version`otf`.

**Comment by tagliala** [comment]
@weilinzung sorry, cannot confirm.

![image](https://user-images.githubusercontent.com/556268/48960700-3dadaa80-ef6f-11e8-87bf-ac580984cc97.png)

Please make sure that you are using FA 5.5.0 and if you still think there are issues with FA please 
open a new request following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
