### ISSUE TITLE
Icon request: fa-translate

### ISSUE THREAD

**Issue by Klooven** [FortAwesome/Font-Awesome#11741]
**An icon that can be used for example in a "Translate"-button.**

I was thinking on something like this:

![image](https://user-images.githubusercontent.com/12278148/32668375-0a663f6e-c646-11e7-91cf-85c9b0ef5dae.png)

_Example icon from [Entypo](http://www.entypo.com/)._

**Comment by PeterShaggyNoble** [comment]
Try the [`language` icon](http://fontawesome.io/icon/language/).

**Comment by Klooven** [comment]
Oh, well it almost looks the same 😆 . Closing.

Thanks @PeterShaggyNoble!
