### ISSUE TITLE
Icon request: icon-friendship

### ISSUE THREAD

**Issue by AurianeWebCom** [FortAwesome/Font-Awesome#11746]
![2 - logo unapei vectorise](https://user-images.githubusercontent.com/33598808/32699505-2ffd75fe-c7b7-11e7-95e6-d4628d11bcce.png)

Hi, I would like to submit this fa-icon because I really need it for my work. I can pay for this job. I saw that you don't have au "friendship" icon, it would be the name of this fa-icon I need.

Please, tell me if it if possible or the price you estimate this job.

I wish a good sunday, best regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is an icon request for friends/friendship at #2883, please +1 that request if you are interested in a generic "friendship" icon.

If you need this exact design, please consider a custom build of font awesome. You can do that by yourself, it is quite easy. You will find both paid solutions (take a look at fort awesome) and free solutions.

All you need is a proper .svg file of the above icon (please note that icons must have a single color, so if you need dual color icons you need two icons)

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps, closing here
