### ISSUE TITLE
Icon request: icon-vue

### ISSUE THREAD

**Issue by rdytogokev** [FortAwesome/Font-Awesome#11742]
First, thanks for Font Awesome.

I noticed that **icon-react** is being included in the FontAwesome 5.0 milestone. It is nice to see Javascript frameworks getting some love.

I am writing to request that the Vue Javascript Framework (https://vuejs.org/ and https://github.com/vuejs/vue) also be considered for inclusion in Font Awesome. Like **react**, it is a popular open source framework.

Official Icon:
![vuejs](https://user-images.githubusercontent.com/2678654/32683174-3e4fc48e-c647-11e7-98c0-96477a44bfa2.png)

Black and White Version:
<img width="531" alt="screen shot 2017-11-10 at 6 44 05 pm" src="https://user-images.githubusercontent.com/2678654/32683180-4b968114-c647-11e7-9c0a-2b3c11bf6ac5.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Vue.js will be part of the upcoming FA5 👍
