### ISSUE TITLE
How about removing so much asshole design on the website?

### ISSUE THREAD

**Issue by georgemicheal21** [FortAwesome/Font-Awesome#11748]
# Would you like to try Font Awesome PRO for JUST $60? CHECK IT OUT RIGHT NOWWWW!!!

or

>No thanks I'll keep being a fag and get the shitty free version

-----

This project has turned into nothing more than a cashgrab for the author, it is against everything that open source stands for.

Yes yes I know, issue closing in 3...2...

**Comment by timtjtim** [comment]
I mean this is their job... I’m not sure what you expect them to do? Live with no money?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
