### ISSUE TITLE
Icon Request: fa-giftcard

### ISSUE THREAD

**Issue by dtrybula** [FortAwesome/Font-Awesome#11747]
A giftcard icon would be very handful for web designers.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of ##8692, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
