### ISSUE TITLE
Icon request: icon-holidays

### ISSUE THREAD

**Issue by tomakali** [FortAwesome/Font-Awesome#11753]
Icon request: icon-swim
Icon request: icon-trekking
Icon request: icon-climbing
Icon request: icon-diving
Icon request: icon-relaxing
Icon request: icon-surfing
Icon request: icon-paragliding
Icon request: icon-motosurfing
Icon request: icon-wild-safari
Icon request: icon-rafting
Icon request: icon-zorbing
Icon request: icon-skiing
Icon request: icon-camping
Icon request: icon-offroading
Icon request: icon-snorkeling
Icon request: icon-boating
Icon request: icon-fishing
Icon request: icon-scubadiving

as the no of icons are getting bigger it would be better to bundle/tag it in broad categories
holidays, hospital, education, travel, business, religion, etc

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
