### ISSUE TITLE
Icon Request: fa-recent

### ISSUE THREAD

**Issue by war88zone** [FortAwesome/Font-Awesome#11754]
Hello,

I would like to open a request to add a new icon. Actually I would have a recent icon. Please find bellow an exemple of the icon needed.
https://cdn0.iconfinder.com/data/icons/pixel-perfect-at-24px-volume-4/24/5064-512.png

I would use this icon for links about recent activity

Best regard,
Romain

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is already available: http://fontawesome.io/icon/history/

I'm going to add a recent filter so it will show up in the docs
