### ISSUE TITLE
Filter font awesome icons are disappeared after reloading in ie11 only

### ISSUE THREAD

**Issue by dhisharma** [FortAwesome/Font-Awesome#11760]
When i reload my application in ie11 the font-awesome icons disappear and same with the web fonts. i came across all these fixes but nothing really worked.

i have not added font awesome in bundling i cant actually .
i am using .net mvc and angularjs .
i am not using no-store.
i have done all the setting related fixes in ie11 but no change.
i have a content folder inside i ahve fonts folder having all the woff,eotand svg font file.
and in content folder i have font-awesome.css.
i have a main css file there i am calling all the font via @font-face.
i have done the part in mimeType but no luck.

**Comment by tagliala** [comment]
> and same with the web fonts. 

You mean all the webfonts on your page are disappearing as well?

**Comment by dhisharma** [comment]
yes but the major issue is the font awesome icons, i have been searching for this bug for too long.

**Comment by tagliala** [comment]
@dhisharma font awesome **is** a webfont.

Please try to host those files on a different server, or try the CDN

I've also seen your comments at #7681 we can continue there. I'm reading 👍
