### ISSUE TITLE
Icons don't show in new Firefox Photon UI on iOS

### ISSUE THREAD

**Issue by bronboek** [FortAwesome/Font-Awesome#11766]
I recently installed the newest Firefox with the Photon UI on my iPhone (iOS 11.1.2). Since then, Font Awesome icons do not show. In Safari they do show correct, see following links: 

[iOS Firefox](https://www.eyas.nl/fa-ios-firefox.jpg)
[iOS Safari](https://www.eyas.nl/fa-ios-safari.jpg)

I use the CDN hosted version:

`<link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" integrity="sha384-dNpIIXE8U05kAbPhy3G1cz+yZmTzA6CY8Vg/u2L9xRnHjJiAK76m2BIEaSEV+/aU" crossorigin="anonymous">`

In previous versions of Firefox there was no issue. Any ideas? Thanks in advance!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It appears that your other webfont is not working too:

![image](https://user-images.githubusercontent.com/556268/32940650-8c36ed3a-cb83-11e7-8184-201f03dc412d.png)

I cannot replicate this issue on fontawesome.io, it works on my iOS 11.2 beta3 / Firefox 10.2

Hope it helps, closing here

**Comment by bronboek** [comment]
In case anyone has the same problem: the cause was in the Tracking Protection settings, I had the block list setting (not yet documented in the link below?) set at 'Strict' instead of 'Basic'. Apparently this also blocks web fonts (or certain file extensions?), even if they're hosted at the local website... 

https://support.mozilla.org/en-US/kb/tracking-protection-ios

**Comment by tagliala** [comment]
@bronboek thanks.

I've also updated the troubleshooting wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#firefox-on-ios-caveats

Feel free to make some adjustments to the above wiki
