### ISSUE TITLE
Icon request: icon-construction

### ISSUE THREAD

**Issue by dinomet** [FortAwesome/Font-Awesome#11761]
I would like to have a construction icon for an internal dashboard about construction projects. Having a few construction related icons would be very helpful.
thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

If you are interested in a hard-hat, please +1 #5790 

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
