### ISSUE TITLE
icon request .  fa-expand . fa-compress . -- please add back into FA 5

### ISSUE THREAD

**Issue by pigsinspace** [FortAwesome/Font-Awesome#11771]
Not sure why these were replaced with the new version but please return these 2 in FA5

![image](https://user-images.githubusercontent.com/6531214/32988114-f1605f64-ccb1-11e7-9fff-40139c732a57.png)

![image](https://user-images.githubusercontent.com/6531214/32988116-01c1e4a4-ccb2-11e7-860c-5ff9aaf732f3.png)

just bought FA 5 Pro and can not use until these are added back

thanks

**Comment by tagliala** [comment]
Hi, please use the Pro repository to report FA5 issues

Closing here
