### ISSUE TITLE
hello！Dear sir！

### ISSUE THREAD

**Issue by zero1five** [FortAwesome/Font-Awesome#11777]
Hello, it's wrong to have the CDN path on the Chinese website of bootstrap China. I hope the official staff can quickly modify it to provide better services for the majority of users.

----------- Here is the website ↓
http://fontawesome.dashgame.com/

**Comment by tagliala** [comment]
Hi,

Thanks for being part of the Font Awesome Community.

There are no official chinese websites of Font Awesome, we do not manage the website you linked

I should advise you to use the official website of font awesome: http://fontawesome.io/

Hope it helps, closing here

Ref: https://github.com/FortAwesome/Font-Awesome/issues/11706#issuecomment-341706698
