### ISSUE TITLE
FA5 SVG does not support javascript removeClass and addClass

### ISSUE THREAD

**Issue by pigsinspace** [FortAwesome/Font-Awesome#11773]
example code

	$("#textIcon").removeClass("fa-comment");
	$("#textIcon").addClass("fa-sync fa-spin");

this work with FA4 and with FA5 web fonts but not with SVG icons.   

tested on FF, Chrome and Safari

**Comment by tagliala** [comment]
Hi, please use the Pro repository to report FA5 issues

Closing here
