### ISSUE TITLE
Problems with adding font-awesome.woff to private git repo

### ISSUE THREAD

**Issue by eldorak90** [FortAwesome/Font-Awesome#11775]
Hi

I am using the font-awesome.woff file in my web project and added it to the git repo for my application as well. While version 4.6.0 was working fine, it's not possible to add version 4.7.0 to my git repo.
It doesn't matter if I create a new branch, use an existing one or try to just update the current file.
This is the error message I receive:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --set-upstream origin feature/Logger:feature/Logger
Pushing to ssh://[path].git
remote: fatal: early EOF        
error: unpack failed: unpack-objects abnormal exit
To ssh://[path].git
 ! [remote rejected] feature/Logger -> feature/Logger (unpacker error)
error: failed to push some refs to 'ssh://[path].git'

Does anyone know how to solve this or is there maybe an error in the .woff file?
Disabling the compression in the git repo is no option

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but this is hard to replicate and debug

I'm going to close here but If this is still an issue with FA5, please comment and provide a reproducible test case
