### ISSUE TITLE
Icon request: icon-jar (or icon-cookie-jar)

### ISSUE THREAD

**Issue by connecteev** [FortAwesome/Font-Awesome#1177]
Ideally something that looks like this:
http://www.shutterstock.com/pic-104001290/stock-vector-jar-vector-icon.html

Applications:
Cookie jar, Tip jar, etc.

**Comment by oauo** [comment]
Also a version with a $ for a tip jar

**Comment by aethior** [comment]
🫙 [U+1FAD9](https://emojipedia.org/emoji/%F0%9F%AB%99/) Jar

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/jar?s=solid
