### ISSUE TITLE
Icon Request: fa-past-dates

### ISSUE THREAD

**Issue by pigsinspace** [FortAwesome/Font-Awesome#11770]
past dates and future dates

![image](https://user-images.githubusercontent.com/6531214/32988097-69235a8e-ccb1-11e7-9b7f-25c339d7e4dc.png)

![image](https://user-images.githubusercontent.com/6531214/32988098-7ae8f44a-ccb1-11e7-818f-271d83cced3f.png)

**Comment by igolden** [comment]
+1

**Comment by tagliala** [comment]
Sorry for the late reply, I've missed this request

Let's use #14724, it has a better title and contains instruction on how to implement those icons right now with the SVG framework
