### ISSUE TITLE
Icon Request: fa-hashnode

### ISSUE THREAD

**Issue by imjog** [FortAwesome/Font-Awesome#11774]
Hashnode is quora for coders. Please create a new icon for hashnode.
website: https://hashnode.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10437, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
