### ISSUE TITLE
Icon request: icon-storefront

### ISSUE THREAD

**Issue by ljkemper** [FortAwesome/Font-Awesome#11785]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do you mean the brand storefront? Could you please clarify this request and provide a single color, 16px suitable example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
No feedback,  considering this a duplicate of #1958
