### ISSUE TITLE
Icon Request: fa-juice

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11781]
Hello i need a juice/smoothies/milkshake icon for my website

**Comment by sdf1992** [comment]
i post you my handmade icon
![juice](https://user-images.githubusercontent.com/33875709/33670431-5572400c-daa5-11e7-82a9-35a50ff32a8b.jpg)

**Comment by tagliala** [comment]
@sdf1992 thanks for the example

I think this is a duplicate of #3068

**Comment by tagliala** [comment]
paper cup: #3068

for juice box, please use #14782
