### ISSUE TITLE
Icon Request: fa-waffle (food)

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11784]
Hello i need a waffle icon for my website

**Comment by sdf1992** [comment]
i post you my handmade icone
![waflle](https://user-images.githubusercontent.com/33875709/33677737-0bbaeae4-daba-11e7-8c7a-410d3cb3f13b.jpg)

**Comment by Crissov** [comment]
Related *future* Unicode emoji #222:

- [_N/A_](http://emojipedia.org/waffle/) U+1F??? Waffle

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/waffle?s=solid
