### ISSUE TITLE
Icon Request: fa-sandwich

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11783]
Hello i need a sandwich icon for my website

**Comment by sdf1992** [comment]
i post you my handmade icone
![paninio](https://user-images.githubusercontent.com/33875709/33677718-f91f9330-dab9-11e7-9949-d320a72749f8.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9874, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
