### ISSUE TITLE
Icon Request: fa-piece-of-cake

### ISSUE THREAD

**Issue by sdf1992** [FortAwesome/Font-Awesome#11782]
Hello i need a piece of cake icon for my website

**Comment by sdf1992** [comment]
i post you my handmade icon
![Uploading torta.jpg…]()

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🍰](http://emojipedia.org/shortcake/) U+1F370 Shortcake

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/cake-slice?s=solid
