### ISSUE TITLE
Icon request: icon-layers, icon-layers-add, icon-layers-remove

### ISSUE THREAD

**Issue by evitolins** [FortAwesome/Font-Awesome#1179]
A "icon-layers" icon option would be great when creating a certain applications (drawing tools, etc).  I imagine 3 rectangles overlapping, and possibly displaying opacity.  Supporting icons might be helpful as well, such as "icon-layer" (single), "icon-layer-add", "icon-layer-delete".

Cheers,
-eriks

**Comment by vtforester** [comment]
+1

**Comment by StuartHemming** [comment]
+1

I'd like to see icons, off-set top-right, that could be used for add, remove and new (plus, minus, asterisk).

**Comment by katelynnobrien** [comment]
+1

**Comment by tomay** [comment]
+1

**Comment by bogus-weber** [comment]
+1

**Comment by kalemontes** [comment]
+1

**Comment by zverev** [comment]
+1

**Comment by vlipman** [comment]
+1

**Comment by jdebbink** [comment]
:+1:

**Comment by seph1603** [comment]
+1

**Comment by ShockRaver** [comment]
+1

**Comment by mdiener21** [comment]
+1

**Comment by rontav** [comment]
+1

**Comment by prebm** [comment]
+1

**Comment by SolveSoul** [comment]
+1

**Comment by josef-brink** [comment]
+1

**Comment by kevinkaske** [comment]
+1

**Comment by isaksky** [comment]
+1

**Comment by jancel** [comment]
+1

**Comment by mfilotto** [comment]
+1

**Comment by padlas** [comment]
+1

**Comment by cmartin616** [comment]
+1

**Comment by worthlutz** [comment]
+1

**Comment by EricHedden** [comment]
+1

**Comment by sebastibe** [comment]
+1

**Comment by Peinkillar** [comment]
+1

**Comment by 3Nex** [comment]
I think there is no actual necessity to do this, as you can get pretty much the same icon by using .fa-clone with .fa-rotate-270, or possibly rotating it yourself by 225deg.

But whatever.

**Comment by Peinkillar** [comment]
scale(1, 0.75) rotate(225deg) is perfect for me
thx

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-layers was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by HarelM** [comment]
+1 although the solution above (with rotation) is nice it does not look good in some cases, for example (the lines does not look):
![image](https://cloud.githubusercontent.com/assets/3269297/14583768/cf4c83a4-0434-11e6-9382-afcdb2ec9906.png)
The extensions is a solution put I prefer not to add another library of font to my project if possible...

**Comment by AndreLGava** [comment]
Yea @HarelM  I agree with you, its just a simple solution for those who  want it quikly to their projects, I'll try to turn them better :D

**Comment by AAudusseau** [comment]
+1

**Comment by tgunnoe** [comment]
+1

**Comment by tgunnoe** [comment]
+1

**Comment by mike-mcgann** [comment]
+1

**Comment by Benjaki2** [comment]
+1

**Comment by chugcup** [comment]
+1

**Comment by rboller** [comment]
+1

**Comment by bpmweel** [comment]
+1

**Comment by espton** [comment]
+1

**Comment by cedrikv** [comment]
+1

**Comment by zuhrasofyan** [comment]
Ok. this should be included in the next release. :) +1

**Comment by saltnpixels** [comment]
+100
why hasnt this been included yet?

**Comment by martinisef** [comment]
+1

**Comment by tayvano** [comment]
+1

**Comment by Half-timber** [comment]
+1

**Comment by esiroka-at-eclinicalsol** [comment]
+1

**Comment by anthony-tsl** [comment]
+1

**Comment by jkubos** [comment]
+1

**Comment by wondie** [comment]
.

**Comment by HarelM** [comment]
I have lost hope on this icon request, moved my code base to use icomoon.io.

**Comment by kubark42** [comment]
Not to knock the project maintainers, but the fact that this has stayed open for so many years, without comment or resolution, would seem to point toward @HarelM's solution.

**Comment by joedjc** [comment]
+1

**Comment by lipegon** [comment]
+1

**Comment by fofi** [comment]
+1

**Comment by gulipad** [comment]
+1000

**Comment by mfajardo** [comment]
+1

**Comment by jslaulhe** [comment]
+1

**Comment by steveharman** [comment]
Amazed there isn't a 'layers' icon.  Surely one of the most common use cases of a map is to overlay different layers of information?   Anyway, +1 to this please.

**Comment by bjuneau** [comment]
+1 

not sure why we have a beer icon, but not this?

**Comment by XanderLuciano** [comment]
+1 Beer Icon

**Comment by ptlola** [comment]
+1

**Comment by ShaunForbes** [comment]
+1

**Comment by steveharman** [comment]
Good to see that today's update from FA includes "compact disc" but still no layers icon.   

I can't remember the last time I even saw a CD let alone wanted an icon for it in a web or mobile app.

**Comment by lipegon** [comment]
Indeed, @steveharman. To make it worse, just checked out Google's Material Design icons, which includes the layer icon from the very beginning.

**Comment by wsierradev** [comment]
+1

**Comment by Conrad777** [comment]
Until this comes into existence I am using the `fa-clone` icon rotated it by -45˚. This is obviously not a fulltime solution and the stacked layers icon is still very much wanted. But at least now I have a 2 layer stack instead of 3 ¯\_(ツ)_/¯

**Comment by dmland** [comment]
With one additional layer of `fa-clone` and a little bit of CSS transform, you can get this look:

![2018-06-12_09-41-18](https://user-images.githubusercontent.com/1907073/41304581-70123502-6e25-11e8-81fe-0da1fb0174f7.png)

**Comment by XanderLuciano** [comment]
Here's some quick sample code using the method @dmland suggested:

```html
<div class="fa-layers fa-fw">
    <i class="far fa-clone" data-fa-transform="rotate--45 shrink-6 up-1.25"></i>
    <i class="far fa-clone" data-fa-transform="rotate--45 shrink-6 down-1.25"></i>
</div>
```

Result:
![image](https://user-images.githubusercontent.com/13877593/41333391-7cf574f2-6e96-11e8-8f4f-528eecda9f40.png)

**Comment by WTIGER001** [comment]
+1

**Comment by tomatillodesign** [comment]
+1 Layers!

**Comment by steveharman** [comment]
So now we have a "travel pack" with loads of great new **travel** icons.   Which almost by definition will be used in products & services that have one or more _maps_.   

Yet still we don't have a **layers** icon ?   

sigh...

**Comment by sensibleworld** [comment]
Just added this to `in-progress` and hoping to get it included in a release soon.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/layer-group?style=solid
https://fontawesome.com/icons/layer-plus?style=solid
https://fontawesome.com/icons/layer-minus?style=solid

**Comment by XanderLuciano** [comment]
Wonderful! Thank you.

**Comment by steveharman** [comment]
Fannnnnntastic!

And happy birthday to the ticket.  Five years and two months to the day.  :-)

**Comment by Conrad777** [comment]
Which coincidentally

**Comment by Conrad777** [comment]
Which coincidentally 🧐turns out to be the release version too... Now that is one crazy easter egg
