### ISSUE TITLE
Circle Icon in stack looks bad (pixelated) Windows XP

### ISSUE THREAD

**Issue by tomasts248** [FortAwesome/Font-Awesome#11791]
I'm using for this:
```
<span class="fa-stack fa-lg">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
      </span>
```
and the circle icon border looks pixelated, even in the example page with the flag it does look bad. 
Regards,
Tomas

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which browser / OS?

![image](https://user-images.githubusercontent.com/556268/33166567-fb83f276-d03a-11e7-8fa7-b6f875b84213.png)

Does not look so bad on Windows 10 / Chrome 62

By the way, the stacking examples are advising bad practices, I hope that the new documentation will fix that (long story short: do not use `fa-lg` with stacks and stay with multiples of 14px)

Please take a look at this fiddle: https://jsfiddle.net/tagliala/k5a4gkag/

**Comment by tomasts248** [comment]
Well I ran Chrome and Firefox ESR in W/XP I know outdated. It does look better on chrome though, still not great though. I ended up creating the circles with css.. and using fontawesome brand icons. Yep the right circle icon looks better. 
Regards,
Tomas

**Comment by tagliala** [comment]
I'm closing here because of the operating system you are using
