### ISSUE TITLE
Icon request: fa-times-circle-thin

### ISSUE THREAD

**Issue by SuperCreek** [FortAwesome/Font-Awesome#11809]
The "fa-times-circle " icon "X" is relatively large, and in some cases a small "X" is needed.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9623 or #1540, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by PeterShaggyNoble** [comment]
@tagliala, they look like 3 different requests to me with #1540 being a request for a thin variant of `fa-times`, #9623 being for `fa-times-circle-o` and this one being for `fa-time-circle`.

**Comment by tagliala** [comment]
Right, thanks

Reopening

**Comment by tagliala** [comment]
Available in FA Pro: https://fontawesome.com/v5.15/icons/times-circle?style=light
