### ISSUE TITLE
Icon Request: fa-pocketaces

### ISSUE THREAD

**Issue by evydaemon** [FortAwesome/Font-Awesome#11804]
2 pocket aces french deck playing cards
something simple like this:
https://static3.depositphotos.com/1003857/182/i/950/depositphotos_1828852-stock-photo-playing-cards-pocket-aces.jpg

**Comment by aethior** [comment]
Hi @evydaemon,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/cards

Regards.

cc/ @tagliala
