### ISSUE TITLE
Icon request: ship-steering-wheel

### ISSUE THREAD

**Issue by rychoo2** [FortAwesome/Font-Awesome#11806]
Would be great to have an icon for ship steering wheel, something like this:
![image](https://user-images.githubusercontent.com/4820692/33265342-92b52fa0-d371-11e7-91b7-6e60845125d3.png)

Good candidate to work with spin animation as well.

Thanks

**Comment by PeterShaggyNoble** [comment]
Duplicate of #9791.

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks. Missed that one
