### ISSUE TITLE
Icon request: Article View (icon-post)

### ISSUE THREAD

**Issue by kkirsche** [FortAwesome/Font-Awesome#1180]
Article view. For use in projects such as CommaFeed. This let's you use icons such as icon-align-justify as a list view and then it would be great to have one which is just two larger rectangles representing the expanded article views.

**Comment by aethior** [comment]
> @kkirsche like a newspaper?
`fa-newspaper-o` was added in v4.2.

cc @tagliala

**Comment by tagliala** [comment]
Closing here

We have:
- http://fontawesome.io/icon/file-text-o/
- http://fontawesome.io/icon/file-text/
- http://fontawesome.io/icon/newspaper-o/
