### ISSUE TITLE
Icon Request: fa-image-slash

### ISSUE THREAD

**Issue by SAJUSJ** [FortAwesome/Font-Awesome#11817]
Need an image icon indicating there is no image.Something like the below one.
![icon-picture](https://user-images.githubusercontent.com/17780674/33412885-4a33a744-d5b4-11e7-9534-ad0b05a9cb96.png)

**Comment by tagliala** [comment]
Refers to #1181

**Comment by SAJUSJ** [comment]
My issue have not been resolved.Any help will be appreciated.

**Comment by tagliala** [comment]
@SAJUSJ please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome to understand how requests work

**Comment by aethior** [comment]
Hi @SAJUSJ,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/image-slash

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon is available in FA Pro

**In a web application**, it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/39/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by SAJUSJ** [comment]
Thanks for adding the icon.
The original issue had to be soled via image with size-setting.
But the newer solution will be of good use
