### ISSUE TITLE
Website UI suggestion: icon as a selectable text

### ISSUE THREAD

**Issue by synchronos-t** [FortAwesome/Font-Awesome#11810]
Could it be easily possible that when searching & viewing icons on the fontawesome.io that the icon would somewhere be as selectable (i.e. copy-pasteable) text?

I use the icons in Illustrator as well, with the desktop font, so it would be great to transfer the icon to Illustrator through clipboard (i.e. the correct character that would produce the correct icon with the font, not the vectors). It would save me the hassle of finding the icon among all the many others in the Illustrator glyph panel. Now all the icon instances on the website are put there with the icon class' ::before pseudo-elements, which are not selectable text.

**Comment by PeterShaggyNoble** [comment]
See #1034.

**Comment by synchronos-t** [comment]
Thanks. The cheat sheet helped.
