### ISSUE TITLE
Icon request: fa-rupiah

### ISSUE THREAD

**Issue by dwikodit** [FortAwesome/Font-Awesome#11816]
Please add icon of Indonesian Locale currency symbol : Rupiah
![rupiah](https://user-images.githubusercontent.com/7536887/33412903-f6215ca2-d5c0-11e7-8cbd-817f3f8b761d.jpg)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #1683 (which you +1ed *before* posting this!).
