### ISSUE TITLE
Icon Request: fa-discord-logo

### ISSUE THREAD

**Issue by YourMCGeek** [FortAwesome/Font-Awesome#11812]
Use as images in contact lists, since Discord is leaving the gaming world more and more and becoming a professional platform. Discords branding says that as long as it's not defaced (in attached picture, comes right from their branding presskit) you are free to use it.

![discord-logo-white](https://user-images.githubusercontent.com/6243879/33355008-91ad60f6-d483-11e7-9be7-5e0590e002ab.png)

**Comment by tagliala** [comment]
Will be available in FA5

#7574
