### ISSUE TITLE
Bug - user-o and user-circle

### ISSUE THREAD

**Issue by maltmann91** [FortAwesome/Font-Awesome#11822]
Hello! All icons are working for me except user-o and user-circle which aren't showing up for me at all. I'm fairly new to github so not sure how to include a live example.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident you are using an old version of Font Awesome. Please make sure you are using FA 4.7.0

Take a look at our tropubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here
