### ISSUE TITLE
Icon request: certificate-alt

### ISSUE THREAD

**Issue by gossi** [FortAwesome/Font-Awesome#1182]
E.g. SSL-Certificate or a cert you get from university.

![](http://www.777icons.com/libs/messenger-vista/certificate-icon.gif)

**Comment by terraelise** [comment]
+1

**Comment by nickstaw** [comment]
+1

**Comment by maximvd** [comment]
+1

**Comment by tagliala** [comment]
FFFFF!

Sorry!

There is a more recent duplicate with more +1s

I will +1 #4246 on your behalf by myself

**Comment by densenator** [comment]
+1

**Comment by tagliala** [comment]
locking here, please use #4246
