### ISSUE TITLE
Icones não estão sendo carregados na minha página Web

### ISSUE THREAD

**Issue by TiagoMRamos** [FortAwesome/Font-Awesome#11828]
Olá, os ícones não estão aparecendo na minha página.
Ja fiz o download do site FontAwesome, incorporei através do link (css) e ainda não apareceu os ícones.
Preciso de ajuda urgente!
Muito Obrigado.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per google translate:

> Hello, the icons are not showing up on my page.
I already downloaded the FontAwesome site, I incorporated it through the link (css) and the icons did not appear yet.
I need urgent help!
Thank you so much.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Please note that this repository is about requests and issues and it is not a support forum

Hope it helps, closing here
