### ISSUE TITLE
Icon Request: fa-coin / fa-coins

### ISSUE THREAD

**Issue by kgp43** [FortAwesome/Font-Awesome#11825]
Icon request: fa-coin and fa-coins

Coin as in money :)
Singular and plural.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4350  and #1400, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
