### ISSUE TITLE
icon request : icon-capture

### ISSUE THREAD

**Issue by meghna300** [FortAwesome/Font-Awesome#11826]
* use it as a website brand
* ![camera-shutter-512](https://user-images.githubusercontent.com/31474001/33522594-4b172f50-d816-11e7-8361-b58ab6fc521c.png)

**Comment by tagliala** [comment]
Could you please provide more information about this brand?

**Comment by axelrindle** [comment]
I don't think this is a brand but rather an icon for a camera application (**capture** images).

**Comment by tagliala** [comment]
@axelrindle thanks

the OP contains:

> use it as a website brand

btw, if this is not a brand, it is a duplicate of #6392

**Comment by tagliala** [comment]
No feedback, considering this a duplicate of #6392
