### ISSUE TITLE
Icon Request: icon-skin

### ISSUE THREAD

**Issue by lynnlovebear** [FortAwesome/Font-Awesome#11820]
添加衣服（皮肤）图标

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use english and provide a single color example of the icon you are requesting

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by lynnlovebear** [comment]
add a 'skin' icon #11820 

![skin2](https://user-images.githubusercontent.com/23694019/33477032-0b13b610-d6bf-11e7-948a-91a4b75e791b.png)

**Comment by tagliala** [comment]
@lynnlovebear this is a duplicate of #715 , please add a 👍  reaction to that request

Closing here
