### ISSUE TITLE
Icon request: icon-hang-loose

### ISSUE THREAD

**Issue by KANTA8Y** [FortAwesome/Font-Awesome#11839]
Hi, I want to use hang-loose icon in my web service which uses surfing motif. Could you make it?
Thank you for your help.

**Comment by PeterShaggyNoble** [comment]
You mean #8093?

**Comment by elenanelmes** [comment]
I was about to log a request for a shaka/hang loose icon.

**Comment by chryssajones** [comment]
My organization builds apps for Hawaiian culture-based educational initiatives.  We would also like to use a shaka icon in our applications, as that gesture originated here in Hawaii and is universally recognized here.

**Comment by tagliala** [comment]
@chryssajones is this request a duplicate of #8093?

**Comment by chryssajones** [comment]
Yes.  I did not make a new request, but I added comments and thumbs-ups to the three existing requests for this icon.  I hope to see it added!

**Comment by tagliala** [comment]
Thanks, closing here as a duplicate of #8093, please upvote that one
