### ISSUE TITLE
Doubts with Upcoming Updates Font Awesome

### ISSUE THREAD

**Issue by paulocrash** [FortAwesome/Font-Awesome#11835]
There would be some date expected to release the new version of Awesome Font that has TS3 icons, Discord, and other icons requested by users.

Thanks in advance!!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TS3 = TeamSpeak 3? TeamSpeak 3 is not planned for 5.0 release

Font Awesome 5.0 Pro has been just released, I think FA5 Free is on its way, but I don't have a release date

Hope it helps

Regards

Closing here
