### ISSUE TITLE
Icon Request: fa-play-button-with-time

### ISSUE THREAD

**Issue by xelpur** [FortAwesome/Font-Awesome#11836]
Hi,

I'm new to this site and this is my first time requesting an icon. I have searched for an icon that contains the play button and also displays the duration of the file (audio or video), but I haven't found it.

This is what I'm looking for:

![20171205_112847](https://user-images.githubusercontent.com/34279367/33618105-a10e1578-d9af-11e7-9925-9bfbf6af516e.jpg)

I'll be using this icon in Balsamiq, to represent the duration of audio or video files.

Thanks,

**Comment by wolfy1339** [comment]
This would be too custom of an icon. There are infinite values that one could want to put for the time value

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon would barely fit the base font size of 14px (16px in FA 5), so I suppose it should be used with font size greater than 14px.

Also, it will not play well with different durations (e.g: 01:10 and 01:00:00)

I would go for play css to implement this, something like

https://jsfiddle.net/tagliala/s3msxtbe/30/

Closing here
