### ISSUE TITLE
Icon Request: fa-tomato

### ISSUE THREAD

**Issue by rickghome** [FortAwesome/Font-Awesome#1183]
I need a little tomato for a pomodoro timer my app uses. This is probably way to non-general, but what the hey.

**Comment by G-Driver** [comment]
+1

<img src="https://cdn2.iconfinder.com/data/icons/bright-food-products/512/tomato-512.png">

**Comment by Foragers** [comment]
+1

**Comment by felonious** [comment]
+1

**Comment by rickghome** [comment]
+1

**Comment by pinusc** [comment]
+1

**Comment by tarunaggarwal54** [comment]
+1

**Comment by freeyoung** [comment]
+1

**Comment by PaNaVTEC** [comment]
+1

**Comment by Crissov** [comment]
🍅 [U+1F345](http://emojipedia.org/tomato/) Unicode emoji #222

**Comment by amberream** [comment]
+1

**Comment by smebberson** [comment]
This would be a great addition.

**Comment by sensibleworld** [comment]
<img width="654" alt="Screen Shot 2021-03-30 at 12 12 08 PM" src="https://user-images.githubusercontent.com/529604/113021019-28557600-9151-11eb-9cc9-521f6464cc4a.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
