### ISSUE TITLE
Icon Request: fa-digital-monitoring

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11849]
Hi Community,

This is to request to issue following icon for web applications

![fa-digital-monitoring](https://user-images.githubusercontent.com/34315455/33679008-b9a69658-dae7-11e7-976c-ae8c9afd9a36.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

What does this icon actually represent? An eye inside a display?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by fahim159** [comment]
It represent some one watching display for surveillance camera. That is virtual security guard.

**Comment by tagliala** [comment]
Duplicate of #5140, please +1 that request and post there your example
