### ISSUE TITLE
Last webfont.html problem issue

### ISSUE THREAD

**Issue by barbeapapier** [FortAwesome/Font-Awesome#11840]
You forgot this block in the header of webfont.html:
`<noscript>
	<link rel="stylesheet" href="../on-server/css/fontawesome.min.css">
	<link rel="stylesheet" href="../on-server/css/fa-solid.min.css">
	<link rel="stylesheet" href="../on-server/css/fa-regular.min.css">
	<link rel="stylesheet" href="../on-server/css/fa-light.min.css">
	<link rel="stylesheet" href="../on-server/css/fa-brands.min.css">
</noscript>`

Without this, the page works on Chrome but icons not on Firefox.
Hoping to help some other people.

Have a good day.

**Comment by PeterShaggyNoble** [comment]
This looks like it's related to FA5, you should probably report it over in the dedicated FA5 repo.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm leaving this open, because there is a "free" 5.0.0 available at https://fontawesome.com/

**Comment by PeterShaggyNoble** [comment]
@tagliala, didn't realise the free version of FA5 had been released. Looking at the site, all GitHub links point to this repo.

**Comment by tagliala** [comment]
@PeterShaggyNoble neither did I :) 

I'm trying to stay focused on the free repo and fontawesome.io at the moment, I will wait for feedback from the Pro team

**Comment by tagliala** [comment]
I think this is not an issue anymore
