### ISSUE TITLE
Icon Request: fa-graphics-designing

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11846]
Hi Community,

This is to request to issue following icon for web applications

![fa-graphics-designing](https://user-images.githubusercontent.com/34315455/33678858-4c3efa9c-dae7-11e7-8d4d-7456b2ce4353.png)

**Comment by aethior** [comment]
Hi @fahim159,

Something like [fa-bezier-curve](https://fontawesome.com/icons/bezier-curve) icon?

Regards.

cc/ @tagliala
