### ISSUE TITLE
Request for new Icons

### ISSUE THREAD

**Issue by fahim159** [FortAwesome/Font-Awesome#11844]
Hello Team GitHub,

First of all I would like to thanks entire team making an wonderful platform for icons. This is really appreciable.

I am a new armature web developer. I am developing my site (virtualstaffs.biz) using proteus medicpress wordpress theme. For services page I need icons like attached herewith. It will be really helpful for me and people who are doing outsourcing work to develop their site.

Also square icon for Instagram & Skype like fa-facebook-square.

Thanks.

fa-digital-monitoring
![fa-digital-monitoring](https://user-images.githubusercontent.com/34315455/33676697-aaa179f4-dae0-11e7-9534-583629bcdb9d.png)

fa-graphics-designing
![fa-graphics-designing](https://user-images.githubusercontent.com/34315455/33676698-aaecc4d6-dae0-11e7-877d-41dd7660df5d.png)

fa-madical-billing
![fa-madical-billing](https://user-images.githubusercontent.com/34315455/33676700-ab390710-dae0-11e7-845c-b7b27cbe91da.png)

fa-property-management
![fa-property-management](https://user-images.githubusercontent.com/34315455/33676701-ab7cb53c-dae0-11e7-8008-6a1f7f0e5a61.png)

fa-seo
![fa-seo](https://user-images.githubusercontent.com/34315455/33676702-abca7fa6-dae0-11e7-8dc1-0c09adeb7a83.png)

fa-virtual-assistance
![fa-virtual-assistance](https://user-images.githubusercontent.com/34315455/33676703-ac138b6a-dae0-11e7-9fed-060dfa4fd31a.png)

I have ai file (adobe illustrator) as well. I can provide if needed.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
