### ISSUE TITLE
Icon Request: Patreon

### ISSUE THREAD

**Issue by flaviotordini** [FortAwesome/Font-Awesome#11841]
What about a Patreon icon? I was surprised to discover it is still missing.

https://www.patreon.com/brand/downloads

PS. Thanks for making Font Awesome!

**Comment by tagliala** [comment]
Ciao Flavio,

Patreon will be available in the upcoming FA 5.0.0 (ref: #3257)

FA 5.0.0 free has been already released at https://fontawesome.com/ but it does not look backward compatible with FA4 (I'm waiting for feedback from the Pro team about this)

Hope it helps, closing here

**Comment by PeterShaggyNoble** [comment]
@tagliala, see https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by tagliala** [comment]
@PeterShaggyNoble oh, thanks, missed that one 🤦‍♂️
