### ISSUE TITLE
Icon Request: fa-mastodon

### ISSUE THREAD

**Issue by matthewgraybosch** [FortAwesome/Font-Awesome#11852]
I think it would be handy to have a fa-mastodon icon that resembles the mascot used by the [Mastodon networks](https://joinmastodon.org) for use as a social media follow icon similar to fa-twitter and fa-facebook. I could use it while customizing my installation of the [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) Jekyll theme.

Mastodon has almost one million users despite being non-commercial (if not anti-commercial), and will continue to grow as people realize that corporate social media outlets are screwing them.

An icon resembling [this logo](https://joinmastodon.org/static/media/logo_full.97822390.svg) would probably be fine.

**Comment by KJReid** [comment]
+1

**Comment by kingu-gidora** [comment]
+1

**Comment by bear454** [comment]
This is a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/10897

**Comment by matthewgraybosch** [comment]
Closing issue because it's a dupe, but it would be nice to see this in FA 5.1

**Comment by tagliala** [comment]
@bear454 thanks, missed that one.

Please +1 #10897

**Comment by bear454** [comment]
+1'd ;-)

**Comment by Clarkinia** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10897, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Locking here 🔒
