### ISSUE TITLE
TYPO3 logo missing - IMHO was backed in kickstarter

### ISSUE THREAD

**Issue by borishinzer** [FortAwesome/Font-Awesome#11858]
Hi,

afaik the TYPO3 Association has funded the kickstarter for Font Awesome 5. It seems that this logo is missing. Could you please check this? 

Thanks a lot.

Best regards,

Boris

**Comment by tagliala** [comment]
@robmadole could you please check this?

**Comment by robmadole** [comment]
@borishinzer I'll check on this right now

**Comment by robmadole** [comment]
@borishinzer can you send an email to hello@fontawesome.com? I'll work with you to get this fixed up.

**Comment by borishinzer** [comment]
Please check inbox.

**Comment by tagliala** [comment]
Fixed in 5.0.1
