### ISSUE TITLE
Icon Request: fa-hammer

### ISSUE THREAD

**Issue by AllPlayed** [FortAwesome/Font-Awesome#11851]
Add a Hammer as an Icon
Only that

**Comment by WulfGamesYT** [comment]
There is `fa-gavel` if that helps you?

**Comment by PeterShaggyNoble** [comment]
Duplicate of #1214.

**Comment by Tirzahe** [comment]
Construction or remodel website would be better with a hammer than a gavel. likethis set of tools icons. https://www.freepik.com/premium-vector/tool-icons-collection_1056122.htm#term=hammer&page=1&position=32

**Comment by tagliala** [comment]
Closing here as a duplicate of #1214
