### ISSUE TITLE
Some icons not loaded

### ISSUE THREAD

**Issue by bradhuang9999** [FortAwesome/Font-Awesome#11854]
I am trying to use foutawesome5 free. 
But some of the free icons can't be loaded.

[You can see that at the link of jsfiddle.](https://jsfiddle.net/r5tc4nyt/)
[All possible list at fontawesome site](https://fontawesome.com/icons?d=gallery&m=free)

**Comment by PeterShaggyNoble** [comment]
Check your class names; see "Styles & Prefixes" in the "Basic Usage" section [here](https://fontawesome.com/how-to-use/svg-with-js). If you're upgrading from FA4 then read [this](https://fontawesome.com/how-to-use/upgrading-from-4) too.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close here, but I'm going to investigate this with the Pro team

Please follow @PeterShaggyNoble's links
