### ISSUE TITLE
Submit Custom Icons

### ISSUE THREAD

**Issue by iamsfs** [FortAwesome/Font-Awesome#11857]
How can i submit my custom icons ? and what are the parameters from ur end to get it accepted.

Thnx

**Comment by viion** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

See section **Requesting new icons**

**Comment by iamsfs** [comment]
Thnx for the update, now is there is a way I can be a part of the font awesome AWSOME community by submitting my own set of icons for free that is available for everyone in the community to use, like I have created these sets of Home Appliances icons that I’m using in my site and I want them to be converted into fontawsome css / JavaScript class, so if u can guide me how can I submit my icons to u which u can guys can upload to ur community easily and then I can use it in my project by searching for them in my pro dashboard area.

**Comment by viion** [comment]
I don't think it really works like that, you could suggest some, or a set "Home Appliances" and submit your samples, then the FA team will get to work on adding it. Here is a example thread of an icon being suggested, ideas submitted and it going into production: https://github.com/FortAwesome/Font-Awesome/issues/7574

If you would like to give it a short yourself, you could try: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

The "Easy Way" is mostly for FA4 at the moment, but with FA5 just released I suspect a lot of font-package sites will still adopting (only for the FREE tier).

If you want to put in your own custom fonts along with PRO fonts, you will need to follow "The Hard Way" guide :)

**Comment by tagliala** [comment]
thanks @viion for the detailed and correct explanation 

Hi again @iamsfs ,

> like I have created these sets of Home Appliances icons that I’m using in my site and I want them to be converted into fontawsome css / JavaScript class

The best you can do is to make a custom version of Font Awesome. You can eventually share your work on another github repo. At the moment we are not accepting PR containing icons

---

>  but with FA5 just released I suspect a lot of font-package sites will still adopting

Fortunately, FA5 Free provides individual SVG files for icons, so you can upload them by yourself and customize immediately 🎉 

I've just tried to upload some SVGs on fontello and icomoon and they work just fine, so the above wiki is still valid 👍 

![image](https://user-images.githubusercontent.com/556268/33744609-5872d290-dbb2-11e7-849f-0456d335465e.png)

![image](https://user-images.githubusercontent.com/556268/33744873-c0800168-dbb3-11e7-8212-3119f1728d2b.png)

Hope it helps, Closing here
