### ISSUE TITLE
Extra scroll bars on all of the code examples

### ISSUE THREAD

**Issue by spencero91** [FortAwesome/Font-Awesome#11864]
On the new font awesome 5 site all of the code examples have 2 sets of horizontal and 2 sets of vertical scroll bars when in reality none of them need any scroll bars at all.

To fix this change:
```
.docs-generated .table-wrap, .overflow-scroll {
    overflow: scroll;
}
```
to
```
.docs-generated .table-wrap, .overflow-scroll {
    overflow: auto;
}
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is related to fontawesome.com, right?

**Comment by spencero91** [comment]
Yeah sorry I realized it wasn't clear I edited the post. That was a fast response.

**Comment by tagliala** [comment]
@spencero91 no problem

Thanks for reporting this.

At the moment there are two different websites and I'm a little bit confused too

**Comment by talbs** [comment]
Thanks for the heads up and sorry for the confusion. We've fixed this styling issue and it'll be out in our next release. In the meantime, apologies for all of the scroll bars. 😄

**Comment by talbs** [comment]
Okay, gang. I've resolved the scrollbars in all of our code samples/syntax bits. That should be all set on https://fontawesome.com. If you find some still popping up, please let us know and we'll wrangle them.

Thanks for the feedback on the new site/docs.
