### ISSUE TITLE
The stava icon is wrong

### ISSUE THREAD

**Issue by simonech** [FortAwesome/Font-Awesome#11866]
After almost 4 years of wait since first request #3313 the stava FA gets released, and is not the icon, but just the name.

https://fontawesome.com/icons/strava?style=brands

**Comment by ka3media** [comment]
You're right... unbelievable :(

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this.

I've checked myself and I was also surprised of the choice, but the icon is not wrong, it just follows their guidelines.

Ref: https://strava.github.io/api/v3/guidelines/

I'm going to leave this open, label as enhancement and assign @talbs, maybe he could help us

**Comment by cdobson** [comment]
@tagliala I don't think the API brand guidelines are relevant in every use case - you may simply be using the Stava icon to link to someone's profile.. Either way it looks like Strava has ditched the condensed icon for everything other than their favicon, which may be why FA elected to use the longhand version.

**Comment by tagliala** [comment]
@cdobson thanks

I'm adding by myself the links you provided in the other thread, so the Pro team could take a look at those unofficial SVGs

https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-242795145
https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-253169719
https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-279815447

**Comment by cdobson** [comment]
@tagliala cool. Reading the first comment again (242795145), @andyreagan states the SVGs he linked to were provided by Strava - proof of this would be helpful.

**Comment by simonech** [comment]
Yeah, indeed that what this icons will be used mostly. Also Strava blog uses the condensed icon.

**Comment by andyreagan** [comment]
Those icons are still available on the settings page:
<img width="913" alt="screen shot 2017-12-08 at 10 55 25 am" src="https://user-images.githubusercontent.com/3012361/33773564-565daa3a-dc06-11e7-8ec7-7c673a338721.png">

**Comment by cdobson** [comment]
@andyreagan oops, apologies

**Comment by tagliala** [comment]
@andyreagan thanks.

I'm seeing PNG logos, could you please check if there is an SVG file?

**Comment by talbs** [comment]
Thanks for all of the candid feedback, folks. We received this same heads up in our Pro repo just before release and will be updating the Strava logo to be the symbol - which coincides with Font Awesome's approach to brand icons better in general.

This should be out shortly.

**Comment by talbs** [comment]
Hi, all! Thanks for bringing our attention to this. This should be resolved in `5.0.1` - https://fontawesome.com/icons/strava?style=brands.
