### ISSUE TITLE
Icon Request: Museum / Library (capitol building)

### ISSUE THREAD

**Issue by GALOCINZA** [FortAwesome/Font-Awesome#1186]
Hello guys, I'm looking for a museum icon representing a building within 3 or 4 columns like a greek/roman monument for a historical renewing builders website in Italy, if possible a trowel (the one used by builders) would be great!

Many thanks!

**Comment by kwaaui** [comment]
+1

**Comment by obruchez** [comment]
+1

**Comment by tagliala** [comment]
Closing here, it should be done: http://fontawesome.io/icon/university/

If you have something different in mind or you want to request a filter, please open a new request with a proper example
