### ISSUE TITLE
Icon-Request: Airline Brands

### ISSUE THREAD

**Issue by OleAlbers** [FortAwesome/Font-Awesome#11860]
Would be nice to have the major airline brands as FontAwesome icons.

(No high priority issue, though)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

> * Please do not request comprehensive sets of icons related to a very specific field.
> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

If you are a Font Awesome Pro customer, try to request this as a category in the private repo
