### ISSUE TITLE
Text are getting out of space

### ISSUE THREAD

**Issue by parthshah000** [FortAwesome/Font-Awesome#11867]
while seeing icons as list view, text(Icon Name) are getting out of space.
For e.g.

![screen shot 2017-12-08 at 12 53 37 pm](https://user-images.githubusercontent.com/10954475/33755531-308fc89a-dc17-11e7-9655-e0d4adc15fbd.png)
![screenshot-fontawesome com-2017-12-08-12-53-13-616](https://user-images.githubusercontent.com/10954475/33755533-30d87ee6-dc17-11e7-82c3-ede22d5763ae.png)

**Comment by tagliala** [comment]
Thanks. I've also noticed this

**Comment by robmadole** [comment]
@talbs is the Doctor for this ailment

**Comment by talbs** [comment]
While not a licensed doctor in any state or country, I'll operate on this! 😛 

Seriously, thanks for the heads up, @parthshah000 and @tagliala.

**Comment by talbs** [comment]
Okay, we didn't forget about the patient (yuck yuck). This should be resolved and icon names are now contained in their white background upon hovering/focusing on them - https://fontawesome.com/icons?d=listing.
