### ISSUE TITLE
FA5: sliders-h icon is too wide

### ISSUE THREAD

**Issue by alecpl** [FortAwesome/Font-Awesome#11872]
Please make the icon width the same as e.g. address-card icon.

**Comment by PeterShaggyNoble** [comment]
You can get those 2 to sit nicely together using the `fa-fw` class and/or the `data-fa-transform` attribute: https://codepen.io/anon/pen/Rjzdej

**Comment by alecpl** [comment]
I know, but why the could not fit nicely together by default? I see the Pro version of sliders isn't so big.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Icons should follow a grid, I will label this as an enhancement and assign to... (waiting for feedback)

https://fontawesome.com/icons/address-card?style=solid
https://fontawesome.com/icons/sliders-h?style=solid

**Comment by alecpl** [comment]
I don't know your grid rules, but here's comparison with envelope icon. I understand some icons have to be wider, but for rectangle-like icons I expect the same size. Thanks.
![icons](https://user-images.githubusercontent.com/546788/33823893-f26e1d8a-de5c-11e7-9078-f2b451bb8599.png)

**Comment by amrocs** [comment]
Alecpl is right. sliders-h is too big. Square shape icon must not fulfill design area.
Icon sliders-h should be more small like FA4:fa-sliders, FA5:chat-line.

By the way, FA5 is inferior to FA4. Lack of uniformity of size, and design is ugly.
I like FA4 and I invested FA5 on kickstarter, but it is mistake. I am very disappointed.

**Comment by robmadole** [comment]
We'll take another look at this one. It looks like it is off by a tad.

**Comment by tagliala** [comment]
Fixed in 5.0.11

https://codepen.io/anon/pen/xjrZwN
