### ISSUE TITLE
Font Awesome 5: allow click-wheel on icons gallery

### ISSUE THREAD

**Issue by yannicka** [FortAwesome/Font-Awesome#11870]
When we are on the icons page (https://fontawesome.com/icons?d=gallery), the click-wheel on an icon opens a new tab, but with the same page (the gallery). I know it's because there is an anchor on the `a` tag and the page is opened with JavaScript; but please, use a normal link to do this, it is more accessible.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for reporting this. I think I've got it, I would definitely go for a plain link. If something happens when using the javascript link (eg: send events to google analytics), this could be done in a different way.

**Comment by robmadole** [comment]
Yeah this is nasty (I'm the one that did it.) It's on our list to get fixed in the next few days.

**Comment by tagliala** [comment]
I think this has been fixed. Also, this fix should also fix #11894
