### ISSUE TITLE
Fontawesome5: fa-layers-text misalignment when using with Bootstrap 4

### ISSUE THREAD

**Issue by mony-dev** [FortAwesome/Font-Awesome#11871]
I currently have the following div.col-lg which lists the techonology that was used to create a website. Since Bootstrap does not have its own fa-icon I tried out the new layer feature but am getting misalignments for that layered element.

```
<div class="fa-5x">
    <i class="fab fa-angular" style="color:red" data-toggle="tooltip" title="Angular 5"></i>
    <i class="fab fa-css3-alt" style="color:darkolivegreen" data-toggle="tooltip" title="CSS3"></i>
    <i class="fab fa-js-square" style="color:lightseagreen" data-toggle="tooltip" title="jQuery"></i>
    <span class="fa-layers fa-fw" data-toggle="tooltip" title="Bootstrap v4">
        <i class="fab fa-bootstrap" style="color:#563D7C"></i>
        <span class="fa-layers-text fa-inverse" data-fa-transform="shrink-4 down-0.5" style="font-weight:600">B</span>
    </span>
</div>
```

Upon reviewing the respective code with the browser-inspector I realized that it is not the i-element but the span-element that is misaligned and using too much space above and beneath itself. Am I missing anything here?

P.S: To avoid confusion, I added the rectangle fo the bootstrap logo to the fontawesome.js.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

With just a small change, it looks pretty good to me (win10, edge/chrome/safari): https://jsfiddle.net/tagliala/8oqL3b5p/1/

Which browser/os is causing you issues?

**Comment by mony-dev** [comment]
I am in Windows 10 and tried the solution on Edge/Firefox/Chrome. 
I believe there might be some problems when using Bootstrap4 at the same time. When I created a mockup-site with just the fontawesome.js and the div containers, everything worked perfectly. The only extra css I have is for an animated navbar and a footer. The moment I add the Bootstrap v4 CSS the last icon will be misaligned.

**Comment by tagliala** [comment]
I can confirm:

https://jsfiddle.net/tagliala/5bwe9Lwz/

**Comment by tagliala** [comment]
The problem is in the `vertical-align` attribute of `.fa-layers`.

We have `-.125em` in `.svg-inline--fa` and `-12.5%` in `.fa-layers`.

Workaround:
```css
.fa-layers {
  vertical-align: -.125em;
}
```

I'm labeling this as bug, but I don't know if there are other side effects of doing that

**Comment by mony-dev** [comment]
Thank you for your feedback so far. I will use the hotfix in the meantime.
Cheers.

**Comment by davegandy** [comment]
This is definitely a bug. For some reason I thought we already fixed this one. We'll get this right in 5.0.3

**Comment by davegandy** [comment]
(And @tagliala's "workaround" is exactly what we'll be using. Using EM alignment instead of % fixes a whole host of alignment issues that have always been there.)

**Comment by tagliala** [comment]
This is still an issue in 5.0.3

**Comment by robmadole** [comment]
targeting 5.0.4 now

**Comment by tagliala** [comment]
Fixed in 5.0.4

https://jsfiddle.net/tagliala/5bwe9Lwz/5/

**Comment by bhaskar-nair2** [comment]
`<span class="fa-layers fa-fw">
              <i class="fas fa-ban"></i>
              <i class="fab fa-facebook-f" data-fa-transform="shrink-6"></i>
   </span>`

Runs perfectly on JSfiddle but isn't working in chrome on Win-7
![image](https://user-images.githubusercontent.com/18023085/40990814-97fc7eb2-690f-11e8-9bdb-14c3c83051dc.png)
Image added for reference.

**Comment by robmadole** [comment]
@bhaskar-nair2 how can I see this? Help me reproduce this and I'll take a second look.

**Comment by bhaskar-nair2** [comment]
@robmadole 
A simple way I made this on JSfiddle was by 
1- Initialize a bootstrap template
2- Remove the default font-awesome link (dead) and put the link I got from https://fontawesome.com/get-started
3- HTML-

`<div>
        <span class="fa-layers fa-fw">
            <i class="fas fa-ban"></i>
            <i class="fab fa-facebook-f" data-fa-transform="shrink-6"></i>
        </span>
</div>`

and run. Isn't working on Fiddle as well now. I'm not sure where am I going wrong.

**Comment by tagliala** [comment]
@bhaskar-nair2 I'm not able to reproduce, please provide a reproducible test case

This is a fiddle with your code, based on:
- Bootstrap 4.1.1
- FA 5.0.13 SVG

https://jsfiddle.net/5bwe9Lwz/43/

It works on Chrome 67 / Win 10 and Yandex 14 (Chrome 35 based) on Windows 7

![image](https://user-images.githubusercontent.com/556268/41190119-51941f1c-6bd9-11e8-8c3a-796960cd6b63.png)

Also, please open a new issue, because this one has been fixed and it is different from yours.

Please make sure that your report follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by bhaskar-nair2** [comment]
@tagliala I told you the exact method by which I did it. I also copied your JSFiddle code and the result still is-
![image](https://user-images.githubusercontent.com/18023085/41190197-db18bf54-6bf7-11e8-9869-9cc64f778002.png)
So, i don't know how I can reproduce the issue in any other way. So, I'll give you all the details I can-
Windows 8.1
Chrome 66
Bootstrap 3 
Flask

Let me check any other possibilities and if the issue still isn't resolved, I'll open this as a new issue.

**Comment by tagliala** [comment]
@bhaskar-nair2 sorry, without a reproducible test case we cannot help. Please open a new issue with all the information we need.

At the moment, you did not specify which version/implementation of Font Awesome are you loading and how. Layers work on the [SVG version](https://fontawesome.com/how-to-use/svg-with-js#layering). If you are using the css version, you should go for [stacking](https://fontawesome.com/how-to-use/web-fonts-with-css#additional-styling)

Sorry, but I'm going to lock here because this issue has been resolved and we are off topic
