### ISSUE TITLE
Icon request: dental-service

### ISSUE THREAD

**Issue by fanuelson** [FortAwesome/Font-Awesome#11874]
![dental-service](https://user-images.githubusercontent.com/8229248/33765030-27e8163e-dbfe-11e7-95e9-f3922b91c31b.png)

Will be used in software made for dentists.

Kind Regards
Fanuel

**Comment by PeterShaggyNoble** [comment]
Related (possible dupe): #1289

**Comment by tagliala** [comment]
thanks @PeterShaggyNoble
