### ISSUE TITLE
typo at https://fontawesome.com/get-started/web-fonts-with-css

### ISSUE THREAD

**Issue by josmaissan** [FortAwesome/Font-Awesome#11877]
At this page:
 https://fontawesome.com/get-started/web-fonts-with-css
a "r" of "fa-**r**egular.css" is missing in the link:
 `<link href="/static/fontawesome/fa-egular.css" rel="stylesheet">`   :wink:

**Comment by talbs** [comment]
D'oh! Thanks for spotting that one, @josmaissan. We should have that back to "egular", err I mean, regular in our next release shortly. 😄

**Comment by talbs** [comment]
This should be fixed at https://fontawesome.com/get-started/web-fonts-with-css. Thanks for bringing it to our attention.
