### ISSUE TITLE
Icon Request: fa-party-popper

### ISSUE THREAD

**Issue by rolmo71** [FortAwesome/Font-Awesome#11888]
![holiday](https://user-images.githubusercontent.com/34396568/33795835-13fb1fe0-dce9-11e7-9846-ee9dd57f5287.png)

**Comment by tagliala** [comment]
Renamed to `party-popper`, as per: https://emojipedia.org/party-popper/

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🎉](http://emojipedia.org/party-popper/) U+1F389 Party Popper

**Comment by adamstickley** [comment]
+1 Would like this please

**Comment by jeanineharb** [comment]
+1!

**Comment by larrytheunicorn** [comment]
+1 🎉🎉🎉

I always look for this and forget it's not in the icon set! 😢

**Comment by dan003400** [comment]
+1

**Comment by ahmetkucukonder** [comment]
+99

**Comment by sensibleworld** [comment]
<img width="653" alt="Screen Shot 2021-03-30 at 12 11 23 PM" src="https://user-images.githubusercontent.com/529604/113020901-0cea6b00-9151-11eb-8641-5331b5174bdb.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
