### ISSUE TITLE
Icon Request: Youpic

### ISSUE THREAD

**Issue by sieursieurac** [FortAwesome/Font-Awesome#11893]
Would be nice to have the icon of the website : https://youpic.com/
SVG could be found here: http://www.ymages.com/images/youpic.svg
Thanks ! :-)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8056, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
