### ISSUE TITLE
404 on "Download Pro" links

### ISSUE THREAD

**Issue by antonioribeiro** [FortAwesome/Font-Awesome#11892]
Non-logged users are probably getting this on all download links:

![image](https://user-images.githubusercontent.com/3182864/33805814-cce9f672-dda5-11e7-94cd-9ddc12e7eb4f.png)

**Comment by robmadole** [comment]
@antonioribeiro thanks for the report. Are you seeing a link to download pro somewhere while not being logged in? (The error message is intentional but a link to download pro might not be)

**Comment by tagliala** [comment]
@robmadole on the home page, I get a 404 as a logged-in user

When I'm not logged in, I see "Check out Pro" which links to https://fontawesome.com/pro

**Comment by tagliala** [comment]
My cookies with the normal mode:

![image](https://user-images.githubusercontent.com/556268/33806969-1d6bb7aa-ddd0-11e7-87ac-c0a080d3ad4a.png)


I've removed all the cookies but I still see "Download Pro" 🤔

**Comment by antonioribeiro** [comment]
Looks like fixed now. When logged out it goes to https://fontawesome.com/pro, when logged in it downloads the zip file.

But earlier those links were pointing to the zip file while I was logged out, or kind of logged out, since I was logged in yesterday, but I when I first entered the page today I assumed my session was still active, but it wasn't, so those links and buttons were still pointing to the zip file, on a page I had just open and was browsing.

![image](https://user-images.githubusercontent.com/3182864/33806970-fa4c3c22-ddb6-11e7-9926-00eede8b5e6c.png)

**Comment by tagliala** [comment]
> Looks like fixed now. 

Closing here. Feel free to comment if this is still an issue
