### ISSUE TITLE
Please add more "-all" styles.

### ISSUE THREAD

**Issue by jsieler** [FortAwesome/Font-Awesome#11899]
In "svg-with-js" style, there is JS file "fontawesome-all.js" which includes all styles and brands. Can you add same file, but with only each style per file, like "fontawesome-regular.js" where then "fontawesome.js + fa-brands.js + fa-regular.js" are combined?

**Comment by robmadole** [comment]
We'll wait for the subsetter to add this level of functionality. However, if you'd like to do this DIY-style you can simply concatenate the files together and name them accordingly.
