### ISSUE TITLE
Icon Request: icon-India

### ISSUE THREAD

**Issue by DocWaz** [FortAwesome/Font-Awesome#11897]
I am looking for an icon that represents India. I run a food blog and have two sections, India and World and am looking for a FA icon that represents India. A tiny image of the India shape would be great. Thanks a ton.

![india-map](https://user-images.githubusercontent.com/34423662/33808428-0663add8-de0c-11e7-8491-d3175842ac0a.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, countries are out of scope at the moment

Please go for an alternative solution, like: http://datamaps.github.io/

Ref: #3992

Closing here
