### ISSUE TITLE
Typographical Error

### ISSUE THREAD

**Issue by adebiyial** [FortAwesome/Font-Awesome#11898]
https://fontawesome.com/how-to-use/use-on-desktop

At the link above is the wrong spelling of 'ligature'.

Thanks.
![sketch 1](https://user-images.githubusercontent.com/18689106/33810409-45674ff6-de04-11e7-92c0-8de70e4dd28a.png)

**Comment by talbs** [comment]
This should be fixed on https://fontawesome.com/how-to-use/use-on-desktop. Thanks for the heads up!
