### ISSUE TITLE
Now way to install via NPM

### ISSUE THREAD

**Issue by jeserkin** [FortAwesome/Font-Awesome#11904]
I know there is a NPM support (not sure if it is official) https://www.npmjs.com/package/font-awesome, but it seems, that there is no way to install 5.x version at the moment.

**Comment by TravisJones6** [comment]
That's the old font-awesome package. You want the new one: https://www.npmjs.com/package/@fortawesome/fontawesome

**Comment by lord-xeon** [comment]
@TravisJones6 , that NPM package is still re-directing to this github project though.  Something is messed up.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at https://fontawesome.com/how-to-use/use-with-node-js

**Comment by jeserkin** [comment]
@lord-xeon to what page it is redirecting doesn't matter, if the page has this sort of info like @TravisJones6  provided.

**Comment by lord-xeon** [comment]
Fair enough.  I'll make a new ticket to show the inconsistency there.

**Comment by lord-xeon** [comment]
@jeserkin, looks like this is a poorly worded ticket.

upon doing 

```
npm i --save @fortawesome/fontawesome
```

from the examples given here - https://fontawesome.com/how-to-use/use-with-node-js

version 4.7.0 of FontAwesome is installed. 

Producing webpack errors of:
```
Module not found: Error: Can't resolve '@fortawesome/fontawesome-free-solid'
```

**Comment by jeserkin** [comment]
@lord-xeon not excluding that possibility. Also I wonder
```
npm i --save @fortawesome/fontawesome
----------------^
```
if this is a typo.

**Comment by tagliala** [comment]
@jeserkin fo`r`tawesome is not a typo

**Comment by lord-xeon** [comment]
@tagliala what does this mean then?  Is NPM mis-configured?  Is it being cached?  This is a blocking bug right now.

**Comment by jeserkin** [comment]
I was able to install without any errors, but at the same time I do not see any simple way of how to use it. In *v4* I was able to just reference `css` file and that was it, Now when I reference css `/node_modules/@fortawesome/fontawesome/styles.css` and try to use `<i class="fas fa-cogs fa-lg"></i>`, nothing is rendered.

**Comment by lord-xeon** [comment]
@jeserkin nothing is being rendered because you have installed the `v4.7.0` branch.   There is still an error installing version 5 of FontAwesome right now.

**Comment by jeserkin** [comment]
Ou. So that what is the issue.

**Comment by lord-xeon** [comment]
@jeserkin 

also run these commands:

```
npm i --save @fortawesome/fontawesome-free-solid
npm i --save @fortawesome/fontawesome-free-regular
npm i --save @fortawesome/fontawesome-free-brands
```

That should fix your issues.

However, it still doesn't fix the mis-matched npm to github page

**Comment by tagliala** [comment]
@lord-xeon the font awesome free repo still has 4.7.0 code, please open a new issue to point out this

**Comment by lord-xeon** [comment]
@tagliala I did - https://github.com/FortAwesome/Font-Awesome/issues/11908

**Comment by SantoshPawar007** [comment]
Can't resolve '@fortawesome/fontawesome-free/css/all.min.css'

**Comment by craftymunz** [comment]
I am getting this error for vue mdb project... 
npm ERR! Could not install from "@fortawesome/fontawesome-free/css/all.min.css" as it does not contain a package.json file

**Comment by tagliala** [comment]
@craftymunz please open a new issue filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
