### ISSUE TITLE
Icon request: medium-icon

### ISSUE THREAD

**Issue by MAHHfew** [FortAwesome/Font-Awesome#11909]
Would love to see an updated version of the current Medium icon http://fontawesome.io/icon/medium/. I'd like to use it as part of some websites I'm currently working on. Thanks in advance!

Logos & brand guidelines for the Medium icon: https://medium.design/logos-and-brand-guidelines-f1a01a733592

Colours: Black

**Comment by PeterShaggyNoble** [comment]
It was updated with the release of FA5: https://fontawesome.com/icons/medium

**Comment by MAHHfew** [comment]
Oh great, thanks Peter! Didn't realize I was browsing on the old FA. Cheers!
