### ISSUE TITLE
FontAwesome 5 Tooltipster incompatibility issue

### ISSUE THREAD

**Issue by djkeltxo** [FortAwesome/Font-Awesome#11902]
Hi,

I'm implementing FA5 in our site and I have a problem with Tooltipster functionality. I have choose SVG implement method. In many icons I have something like this:

`<i class="fas fa-exclamation-triangle tooltip" Title="Help text"></i>`

Tooltip functionality (Tooltipster JS) works very well in FA4, but now, in FA5 it doesn't. In some cases I can with a strong effort move tooltip class to previous <a> html.

Any idea for fix this?
Do you will fix in a near future update?

Thank you very much for your great work.

**Comment by djkeltxo** [comment]
Hello,

Additional information about this issue.

In SVG implementation, javascript code removes 'Title' from <i> tag.

Thank you for your support.

**Comment by djkeltxo** [comment]
The same problem is at https://github.com/FortAwesome/Font-Awesome/issues/11966.
I put it for reference.
I hope it will be solved ASAP.
Thank you very much.

**Comment by robmadole** [comment]
@djkeltxo since the `<i>` tag is replaced with `<svg>` I'm not sure what would help you out here. You might consider switching to web fonts if you need a more compatible upgrade to FA5.

Also if you could provide a test case (reproduction) using codepen.io, jsbin.com, jsfiddle.net or similar that would help me understand exactly what you are dealing with.

**Comment by djkeltxo** [comment]
Hi,
My problem is explained in this and referenced issue. As @andrezgz mention, SVG implementation removes 'title' tag from <i> tag, so functionalities like Tooltipster don't work. I can't switch to web fonts because I need special features that SVG offer.
I hope that you solve this behaviour problem in a future FontAwesome update.
Thank you very much.

**Comment by robmadole** [comment]
Sorry, @djkeltxo I'm just not smellin' what your cookin'. Can you create a reproducible test case using something like codepen.io?

**Comment by robmadole** [comment]
We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by petraeus** [comment]
jQuery tooltips do not work with font awesome 5 svg/js implmentation

**Comment by serghost** [comment]
However you can workaround it by using a wrapper:
```
<div class="icon-with-tooltip">
  <i class="fas fa-exclamation-triangle tooltip" Title="Help text"></i>
</div>
```

**Comment by lamadipen** [comment]
> However you can workaround it by using a wrapper:
> 
> ```
> <div class="icon-with-tooltip tooltip" Title="Help text">
>   <i class="fas fa-exclamation-triangle"></i>
> </div>
> ```
I faced issue of getting two tooltips instead of one while using FontAwesome 5 as It will create additional SVG tag with bootstrap tooltip. I even disable the tooltip everywhere for bootstrap tooltip but still I was getting undesired tooltip. 

Issue can be reproduced with following code
> ```
> <span                
>            class="fa fa-question-circle"
>            data-toggle="tooltip"
>            data-placement="right"
>            title="Some Title"
>            data-tt-head="Some Header"
>            data-tt-footer="<a style='opacity: 70%' target='_blank' href=''>Read More ... 
> </a>" >
> </span>
> ```

And the issue was solved following the solution by @serghost using a wrapper

> ```
> <span                
>            class="fa fa-question-circle"
>            data-toggle="tooltip"
>            data-placement="right"
>            title="Some Title"
>            data-tt-head="Some Header"
>            data-tt-footer="<a style='opacity: 70%' target='_blank' href=''>Read More ... 
> </a>" >
>      <i class="fa fa-question-circle"></i>
> </span>
> ```
