### ISSUE TITLE
UiKit add custom Icons - Uniform Icon size 

### ISSUE THREAD

**Issue by marcelgeratsch** [FortAwesome/Font-Awesome#11907]
Hi there,

i just compiled the latest UiKit Version with all the Fontawesome 5 icons as custom icons. While using them i have noticed, that there seem to be 2 versions of icons. Some with a width and height of 20px and some without and a giant viewbox. Could you please unify the raw svg data? I dont want to set a width and height on 600+ icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the late reply, I've missed this issue

Is this still an issue?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

> Some with a width and height of 20px 

Example? (fa-...)

> some without and a giant viewbox

Example? (fa-...)
