### ISSUE TITLE
FontAwesome 5 how to switch icon

### ISSUE THREAD

**Issue by PrimozRome** [FortAwesome/Font-Awesome#11903]
So in previous version of font-awesome it was easy to switch icon on an element... you just replaced  the `fa-` class on the element. 

How does this work on font-awesome 5? The previous functionality is broken in our app because in version 5 you replace original element with `<svg>`.

For example. We had a "Loading Button" component that switched the button icon to `fa-spinner fa-spin` when the asynchronous action of the button was triggered and then back to the button icon when the asynchronous action ended.

**Comment by lord-xeon** [comment]
I'm having a similar issue replacing v4.x system to v5.x.  It looks like you're going to want to use the [web-fonts with CSS method](https://fontawesome.com/how-to-use/web-fonts-with-css) for FA5.

**Comment by robmadole** [comment]
As of 5.0.1 you can now modify the class and change the icon. Let me know if you have issues with this.
