### ISSUE TITLE
Icon fails to display: Twitter

### ISSUE THREAD

**Issue by greg-raven** [FortAwesome/Font-Awesome#11900]
The Twitter icon isn't displaying for me. Sometimes it seems to be getting scraped off by Ad Blocker, other times it's just not there. The other icons I'm using seem to be working fine. If I turn off Ad Blocker, it appears. Very strange.

**Comment by PeterShaggyNoble** [comment]
See the warning under the brand icons [here](http://fontawesome.io/icons/) - should also be applicable to FA5.

**Comment by tagliala** [comment]
AFAIK, the adblocker issue has been resolved a while ago: #1799

Please make sure your adblock lists are up to date, otherwise please report

- browser version
- adblock version
- fanboy list version

Meanwhile, closing here
