### ISSUE TITLE
text-shadow not working (FontAwesome5)

### ISSUE THREAD

**Issue by syuilo** [FortAwesome/Font-Awesome#11916]

**Comment by syuilo** [comment]
Sorry, I learned that FontAwesome 5 inherits only size and color.

**Comment by tagliala** [comment]
You should use the webfont version of FA5 to keep using text-shadow

https://jsfiddle.net/tagliala/tgzouajm/4/

**Comment by chocos10** [comment]
@tagliala  v5.0.6 text shadow is not working for the new release any updates on that .

**Comment by tagliala** [comment]
@chocos10 sorry, I cannot confirm

https://jsfiddle.net/tagliala/qq2eLxo1/8/

> You should use the webfont version of FA5 to keep using text-shadow

**Comment by chocos10** [comment]
@tagliala  should i open a issue ? or is there someone who can confirm this because i cannot use that ?

**Comment by tagliala** [comment]
@chocos10 feel free to open an issue but please make sure to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Also, if you are using the SVG Framework, text-shadow will not work and you should use the webfont version of FA5.

**Comment by aensley** [comment]
@charlygut That solution was just what I was looking for! I needed a way to ensure I could see a white "compress" icon no matter the background behind the element (dark or light). This worked:

```CSS
.fa-compress {
    filter: drop-shadow(0px 0px 1px #777);
}
```

**Comment by charlygut** [comment]
@aensley this also works for Web Fonts

 I post an example: https://codepen.io/charlygut/pen/vRWBdq

**Comment by chocos10** [comment]
Thanks for your help will look into Web Fonts :)

**Comment by arajay** [comment]
this does not work in IE

> @charlygut That solution was just what I was looking for! I needed a way to ensure I could see a white "compress" icon no matter the background behind the element (dark or light). This worked:
> 
> ```css
> .fa-compress {
>     filter: drop-shadow(0 0 1px #777);
> }
> ```

ths does not work in IE

**Comment by charlygut** [comment]
@arajay you're right. 
Look at this link and go to "browser support" https://www.w3schools.com/cssref/css3_pr_filter.asp

**Comment by aensley** [comment]
@arajay Here's a more comprehensive compatibility table: https://caniuse.com/#feat=css-filters
