### ISSUE TITLE
Some icons (e.g: fa-university/f19c) are off-center

### ISSUE THREAD

**Issue by danegraphics** [FortAwesome/Font-Awesome#11912]
The icon has a small empty space on the right side of it that pushes it off-center to the left.

I suspect that there are other icons with a similar problem.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which version of Font Awesome?

**Comment by danegraphics** [comment]
5.0.1

**Comment by tagliala** [comment]
I can confirm, but I don't know if this is an issue

![image](https://user-images.githubusercontent.com/556268/33900589-47d17ea8-df6f-11e7-88d1-413714cf6a0d.png)

![image](https://user-images.githubusercontent.com/556268/33900617-5b331b5a-df6f-11e7-8905-42e4899683d3.png)


Let's wait for @robmadole 's feedback

**Comment by danegraphics** [comment]
When doing webdesign, having large icons be obviously off center is REALLY disconcerting. I’ve had to add leftiside padding to it just to center it.

**Comment by tagliala** [comment]
I'm also reporting here other icons suffering from this issue:

* address-book (left side - solid, regular, light)
* behance-square (right side)
* js-square (right and left, different from all other square icons)
* mouse-pointer (right side - light)
* phone-volume (right side - light)
* university (right side - solid, regular)
* user-plus (right side - solid, light)
* user-times (right side - solid, regular, light)
* weixin (right side)

**Comment by davegandy** [comment]
These were designed with the whitespace intentionally, but I can definitely reconsider it. @tagliala is right, we did it so things would not blur when centered. Not so sure this is a real issue anymore with SVG. Requires some further testing.

Non of the brands should have this issue, though. We'll get that fixed up in 5.0.3. Great list, @tagliala. Is super helpful.

**Comment by davegandy** [comment]
Brand icons are being updated as we speak to fix this. I'm going to address this problem by actually re-designing the icons themselves to actually be an even pixel width. Hardest way to fix, but cleanest.
