### ISSUE TITLE
I love this, i'm using for years, but every time I need an icon from the website I need to click and open a new page. Is a pain.

### ISSUE THREAD

**Issue by freereikicourse** [FortAwesome/Font-Awesome#11910]
Can you please make it easier to copy a name of the icon from the website?

I understand you might want more page views, but that's terrible UX. I don't want to open a new page copy the icon and go back. Ah yeah, when I go back I lost my search and position... perfect.

Come on, please fix this one.

**Comment by wolfy1339** [comment]
FA5 or FA4?

**Comment by freereikicourse** [comment]
Not sure, just the website: http://fontawesome.io/icons/

**Comment by wolfy1339** [comment]
Well, yeah I knew you were using the website.
Because, there is fontawesome.io (v4) and fontawesome.com (v5). Which is why I had asked
________________________________

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can use http://fontawesome.io/cheatsheet/ for FA4, but on the new FA5 website https://fontawesome.com/ you have a lot of options to copy into clipboard

Hope it helps, closing here
