### ISSUE TITLE
fa-spin Broken in 5.0.1

### ISSUE THREAD

**Issue by purplekrayons** [FortAwesome/Font-Awesome#11919]
It looks like using `.removeClass('fa-spin')` is broken as of 5.0.1. In 5.0.0, I was using this without issue.

Example:
`myElement.addClass('fa-spin')`
`myElement.removeClass('fa-spin')`

In 5.0.1, the icon will start to spin when I add the class `fa-spin`, but will not stop when i remove the class `fa-spin`. I'm not seeing any errors in console related to this.

I am using the svg flavour and including these files:

`fa-light.min.js`
`fontawesome.min.js`

**Comment by purplekrayons** [comment]
Closing issue -- recreated under FA Pro here: https://github.com/FortAwesome/Font-Awesome-Pro/issues/927

**Comment by tagliala** [comment]
Reopening here too

**Comment by antonioribeiro** [comment]
Icon can only stay in it's first state, if it was first spinning, you cannot stop it, if it was stopped, you cannot make it spin. A VueJS bin here: http://jsbin.com/dogusifabe/edit?html,css,js,output

**Comment by tagliala** [comment]
Is this still an issue?

**Comment by tagliala** [comment]
No feedback, closing here
