### ISSUE TITLE
Typo in usage instructions

### ISSUE THREAD

**Issue by Ryuno-Ki** [FortAwesome/Font-Awesome#11911]
In [fontawesome.icon(iconDefinition, params)](https://www.npmjs.com/package/@fortawesome/fontawesome#fontawesomeiconicondefinition-params) there is a small typo:

Actual:
```js
import fontawesome from '@fortawesome/fontawesome'
import { faPlus } from '@fortaewsome/fontawesome-free-solid'
```

Expected:
```js
import fontawesome from '@fortawesome/fontawesome'
import { faPlus } from '@fortawesome/fontawesome-free-solid'
```
Note the `ew` vs. `we` for the solid fonts. Took me half an hour to spot it (I'm using Rollup in a project).

**Comment by robmadole** [comment]
Doh! Fixing now. How embarrassing.

**Comment by robmadole** [comment]
We're gonna push the documentation for this to https://fontawesome.com/how-to-use/use-with-node-js. We'll update this typo then.
