### ISSUE TITLE
Pseudo elements not working

### ISSUE THREAD

**Issue by kjdion84** [FortAwesome/Font-Awesome#11920]
All my icons show up fine when I use `<i class="fas fa-link"></i>`

However when I use:

```
.sidebar [data-toggle="collapse"]:before {
    content: "\f0c1";
    font-family: "Font Awesome 5 Free";
}
```

Its showing in chrome as an empty square. I'm using the webfonts/CSS version.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add `font-weight: 900;`

https://jsfiddle.net/tagliala/tgzouajm/5/

Hope it helps

Closing here

**Comment by JulioBastidas** [comment]
nope, not working

**Comment by tagliala** [comment]
@JulioBastidas please provide a reproducible test case

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by clefayomide** [comment]
> All my icons show up fine when I use `<i class="fas fa-link"></i>`
> 
> However when I use:
> 
> ```
> .sidebar [data-toggle="collapse"]:before {
>     content: "\f0c1";
>     font-family: "Font Awesome 5 Free";
> }
> ```
> 
> Its showing in chrome as an empty square. I'm using the webfonts/CSS version.

Hi, were you able to figure this out ? If yes,what did you do?  I'm experiencing the same problem at the moment

**Comment by tagliala** [comment]
@clefayomide  please provide a reproducible test case

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
