### ISSUE TITLE
Indicate if an icon is free or pro on the icon's page

### ISSUE THREAD

**Issue by jhpratt** [FortAwesome/Font-Awesome#11929]
As the subsetter isn't available yet, I'm going through hand-picking icons that I need, both to reduce the size of the files loaded and avoid licensing issues. However, it's not easy to tell if an icon is free or pro, as there's no indication of such on its page ([example page](https://fontawesome.com/icons/github-square?style=brands)).

It would be great to see this; it should be a relatively simple change since the metadata is already there.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Brands are all free

About icons, please take a look on the right side

![image](https://user-images.githubusercontent.com/556268/33966566-53c74cd2-e060-11e7-80c6-ab975513ac96.png)

Hope it helps, closing here

**Comment by jhpratt** [comment]
Ah, didn't notice it because I was looking at a brand. Thanks for the quick response!

**Comment by tagliala** [comment]
You're welcome. 

If we will receive more reports like this, I will ask the team to consider a different layout
