### ISSUE TITLE
Icon Request: fa-video-camera-slash

### ISSUE THREAD

**Issue by jpezninjo** [FortAwesome/Font-Awesome#11923]
Use: Want to use it with a web app that will have an option to turn off the video camera, similar to how there is a microphone and a microphone-slash counterpart

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3765 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by jpezninjo** [comment]
ahh shoot. sorry about that! thanks!
