### ISSUE TITLE
Icon request: icon-ad

### ISSUE THREAD

**Issue by cskodinski** [FortAwesome/Font-Awesome#11934]
I am looking for an icon to be made that is a computer monitor, but shows the words "Ad" on it. Or the monitor could show something besides a blank screen, but preferably tailored towards advertising.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please consider the stacking feature for this example: https://jsfiddle.net/tagliala/f019sa7v/5/ (SVG)

Feel free to provide another example, maybe without letters and suitable for 16px icon size and I will reconsider reopening

Closing here
