### ISSUE TITLE
Icon request: new icon

### ISSUE THREAD

**Issue by supercreator** [FortAwesome/Font-Awesome#11938]
I plan to use the new icon for showing the new message, new product or new information. Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #11002 ?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
