### ISSUE TITLE
Font generator?

### ISSUE THREAD

**Issue by divdax** [FortAwesome/Font-Awesome#11931]
Hey,

it is possible to create a font file generator so only the necessary icons are available?
The font is very large if you want to use e.g. solid + light version.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you are referring to Font Awesome Free, please check: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

You can create your own set starting from individual .svgs

If you are referring to Font Awesome Pro, a [Desktop Icon Subsetter](https://fontawesome.com/updates) tool will eventually be available

Hope it helps

Closing here
