### ISSUE TITLE
fa-stack with fa-hexagon as background

### ISSUE THREAD

**Issue by katie1348** [FortAwesome/Font-Awesome#11936]
I have been using Font Awesome 5.0.1 Pro and using the Hexagon as a background.

When placing icons into a circle, they align as expected, centred in the circle. Code is as follows:

```css			
<span class="fa-stack fa-2x">
    <i class="fas fa-circle fa-stack-2x" style="color: red;"></i>
    <i class="fas fa-envelope fa-stack-1x fa-inverse"></i>
</span>
```
When I use the same code, but use a hexagon, I get an offset to the left, which creates a visual anomaly. 

```css
<span class="fa-stack fa-2x">
    <i class="fas fa-hexagon fa-stack-2x" style="color: red;"></i>
    <i class="fas fa-envelope fa-stack-1x fa-inverse"></i>
</span>
```
It does not seem to matter which icon is used, as the few I have tried all do the same thing.

It is reasonably simple to see this in a page, as the code above with reference to "fontawesome-all.min.css" was all I had.

You can see the effect in the image below.

![icons](https://user-images.githubusercontent.com/4849251/34003492-49773b9c-e0ed-11e7-930b-90fbe4c23d31.PNG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please post this on the pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

**Comment by katie1348** [comment]
I have opened this in the other repository.

And therefore have closed this one.
