### ISSUE TITLE
Icon Request: fa-broken-glass

### ISSUE THREAD

**Issue by seba1rx** [FortAwesome/Font-Awesome#11939]
Hi, I think Font awesome should include an icon related to the state of integrity of something, like Broken or Mint condition (not broken)

I suggest to use a jar asthe icon image,  broken or not broken, for broken or mint condition.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by seba1rx** [comment]
Here is an example

fa-broken
fa-notbroken

![fa-broken](https://user-images.githubusercontent.com/15786046/34059562-3e2a6fe4-e1be-11e7-91e0-67e3488a7ccd.png)
![fa-not-broken](https://user-images.githubusercontent.com/15786046/34059564-3e4b13b6-e1be-11e7-825f-161a9b5f1916.png)
![fa-broken 32x32](https://user-images.githubusercontent.com/15786046/34059565-3e6b4d52-e1be-11e7-9e2f-7f359307b568.png)

**Comment by polkovnikov-ph** [comment]
I don't think broken glass can stand for some other broken stuff (like broken tests), because in other languages people tend to have different words for these. But the idea is great. What other icon could we use for it?

**Comment by tagliala** [comment]
> I don't think broken glass can stand for some other broken stuff (like broken tests),

I agree

> What other icon could we use for it?

[fa-check](https://fontawesome.com/icons/check?style=solid) and [fa-times](https://fontawesome.com/icons/times?style=solid), as [Travis CI](https://travis-ci.org) does fits this use case

![image](https://user-images.githubusercontent.com/556268/34079471-7ffaae5e-e32e-11e7-9c57-07ce4ea2106e.png)
