### ISSUE TITLE
Quora - Etsy broken 

### ISSUE THREAD

**Issue by bengrzybowski** [FortAwesome/Font-Awesome#11948]
Both the Quora and Etsy icons are not working, while all other icons I have tested are functioning properly.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot confirm: 
- SVG: https://jsfiddle.net/tagliala/f019sa7v/6/
- webfon: https://jsfiddle.net/tagliala/tgzouajm/14/

Please check your stylesheet for conflicts.

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps

Closing here
