### ISSUE TITLE
Font-Awesome 5 Bower/Npm Install

### ISSUE THREAD

**Issue by wautersj** [FortAwesome/Font-Awesome#11942]
Is there a way to use Font-Awesome 5 with bower or npm?

I didn't find an answer to that in the docs, maybe I missed it?

**Comment by wautersj** [comment]
Nevermind, I think I was too quick to log an issue, found it!

https://fontawesome.com/how-to-use/use-with-node-js

**Comment by brunolm** [comment]
I think it's not clear enough if I'm used to v4, how do I use v5 in the same way?

I use it sass like this:

```
npm i -S font-awesome
```

```
$fa-font-path: '../assets/fonts';
@import '../../node_modules/font-awesome/scss/font-awesome';
```

and then

```
<i class="fa fa-youtube"></i>
```

What's the equivalent with v5?

**Comment by tagliala** [comment]
@brunolm please try with https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts

**Comment by venkat-subramani** [comment]
Any updates on how to use FontAwesome 5 with bower, this one shows for npm and yarn only

**Comment by tagliala** [comment]
@venkat-subramani 

> Any updates on how to use FontAwesome 5 with bower, this one shows for npm and yarn only

Sorry. Font Awesome 5 will not support bower. Please consider an alternative.

Official answer: https://github.com/FortAwesome/Font-Awesome/issues/11908#issuecomment-353192558

Post on the bower blog: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Hope it helps
