### ISSUE TITLE
Icon request: fa-apps

### ISSUE THREAD

**Issue by oswee** [FortAwesome/Font-Awesome#11947]
Please add commonly used icon of 9 dots and 9 squares to represent apps or options.
![fa-apps_black_32](https://user-images.githubusercontent.com/20469200/34055708-2396ee4e-e1d9-11e7-9164-86c1dc801d59.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fa-th` could fit your needs: https://fontawesome.com/icons/th?style=solid

And there is also this request: #6299

**Comment by oswee** [comment]
I know this icon but it is not what suite well for some kind "App Launcher or Settings". Fa-th is not square. And there is no "9 dots" or "9 squares".

**Comment by huoxy** [comment]
Mark, same requirements.

**Comment by dawesi** [comment]
9 squares please!

**Comment by r-man** [comment]
+1

**Comment by a-ivanov81** [comment]
+1

**Comment by gwigz** [comment]
![image](https://user-images.githubusercontent.com/9297195/64873806-c81be380-d641-11e9-85a2-f0bdd90be988.png)

dots would be appreciated, [`fa-th`](https://fontawesome.com/icons/th?style=solid) or #6299 are too square

**Comment by DaleyKD** [comment]
Any luck on anything like this?  Android's right now in Google Play is 4 squares with some decent margin between them. I'd be content with the 9 dots or something that is a better designation.

**Comment by AdnanLatif93** [comment]
this would help you.
9-square. 
https://www.w3schools.com/icons/tryit.asp?filename=tryicons_google-apps

**Comment by Coops9** [comment]
This looks like an old thread but I would also love this icon to be added

**Comment by sensibleworld** [comment]
This was added in `6.4.0` https://fontawesome.com/icons/grid-round?f=classic&s=solid
