### ISSUE TITLE
Unicode f138 returns wrong Icon

### ISSUE THREAD

**Issue by zBestData** [FortAwesome/Font-Awesome#11945]
Version 5.0.1 .... \f138  is returning a magnifying glass instead of right chevron with circle.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/tgzouajm/11/

Please check other stylesheets for conflicts

Hope it helps, closing here

**Comment by zBestData** [comment]
Thanks for checking, but you are right.  Turned out to be a conflict with FlexSlider.  Sorry for wasting your time.
