### ISSUE TITLE
How to use this plugin after I install into my project with 'npm install font-awesome --save-dev'

### ISSUE THREAD

**Issue by pkwblack** [FortAwesome/Font-Awesome#11943]
I have installed this into my project, and it appears in node-modules.
What I want to know is how to use it, how to import into my own sass file?

`@import 'font-awesome'`

I import it directly, but errors.
```
Module build failed:
@import 'font-awesome'
^
      File to import not found or unreadable: font-awesome.
```

I'm a newer of vue, many thanks for your help.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Take a look at https://fontawesome.com/how-to-use/use-with-node-js

Please note that font awesome is using NPM scoped projects

https://www.npmjs.com/package/@fortawesome/fontawesome

**Comment by pkwblack** [comment]
@tagliala 
Many thanks for your help and patience.
But it still not work for me, could you give some suggestions?
I put the whole fontawesome folder into my project directly.
This is my own sass file:

```
@import './fontawesome/web-fonts-with-css/scss/fontawesome'
@import './fontawesome/web-fonts-with-css/scss/fa-solid'

$sidebar-icon-map: ("bp": fa-address-card, "contract": fa-handshake)

@each $code, $icon in $sidebar-icon-map
  .#{$code}-icon
    @extend .fa
    @extend .#{$icon}
```
this is my vue template:

`<div class="bp-icon"></div>`

there are some errors in console, seems like css-loader can not load font file. 
```
These relative modules were not found:

* ../webfonts/fa-solid-900.eot in ./node_modules/css-loader?{"sourceMap":false}!
./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/sass-loader
/lib/loader.js?{"indentedSyntax":true,"sourceMap":false}!./src/common/sass/icon.
sass
```
What should I do to make it works well?

**Comment by robmadole** [comment]
@pkwblack we recommend using the Vue component (which uses SVG) instead of web fonts.

Check out https://www.npmjs.com/package/@fortawesome/vue-fontawesome
