### ISSUE TITLE
Icon request: icon-dna

### ISSUE THREAD

**Issue by murphyke** [FortAwesome/Font-Awesome#1195]
This icon would represent DNA or other genomic data; it would be usable by medical and research apps and bio-hack games in which you can modify your character's DNA or gene expression patterns.

This is hard to get across in a tiny icon, but something like the following comes close.

![dna-sample](https://f.cloud.github.com/assets/928642/580221/f46bb128-c882-11e2-9c65-4706ad945ddf.png)

Note that there are two similar images in the noun project, but I prefer mine.  I did mine in Inkscape, but my svg is messy and wasteful and needs more work to be able to use a transparent background (I cheated for demo purposes).

---

**edit by @tagliala**

> ![science-dna-helix-icon](https://cloud.githubusercontent.com/assets/7817395/16649684/ed879e0c-4431-11e6-9c92-4db3e11d41a6.png)
> **Note that the strand ascending left to right should pass in front of the other strand.**

**Comment by Oceanswave** [comment]
:+1:

**Comment by dangunter** [comment]
+1

**Comment by Batmanian** [comment]
+1

**Comment by kvanderd** [comment]
+ 1

**Comment by badulesia** [comment]
+1
![2079](https://cloud.githubusercontent.com/assets/3285335/6195546/69114004-b3cf-11e4-8742-267b935182ac.png)

**Comment by sciple** [comment]
+1

**Comment by sebastian301082** [comment]
+1

**Comment by Biomedicas** [comment]
+1 please¡¡¡

**Comment by phpforfree** [comment]
+1

**Comment by phasjim** [comment]
+1

**Comment by desix75** [comment]
+1

**Comment by azankl** [comment]
+1 (especially the one from trich7)

**Comment by blacatena** [comment]
+1

**Comment by mir4ef** [comment]
+1

**Comment by alessandroraffa** [comment]
+1
even a simple one

**Comment by mileswest07** [comment]
+1
Surprised this hasn't been done yet (two years later)...

**Comment by merenzo** [comment]
+1

**Comment by uchitha** [comment]
+1

**Comment by Benjamin-Lee** [comment]
+1

**Comment by felipedaraujo** [comment]
+1

**Comment by etiology** [comment]
+1

**Comment by qhalid** [comment]
+1

**Comment by sitegoals** [comment]
+1 (if per user account/ +10 if allowed to include all co-workers who agree :)

**Comment by Ligaza** [comment]
+1

**Comment by abramadams** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by ice12192** [comment]
+1

**Comment by AndreLGava** [comment]
+1

**Comment by pmeisen** [comment]
+1 (asap! :smile:)

**Comment by RicCastagna** [comment]
+1 on this one!

**Comment by iznogud** [comment]
Please do the DNA
+1 (in all languages)
scientists are coders too, right?
:)

**Comment by wdmeeste** [comment]
+1

**Comment by snooz** [comment]
+1

**Comment by fhoess** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by EuMMCR** [comment]
+1

**Comment by mapace** [comment]
+1

**Comment by Dor-Ron** [comment]
+1

**Comment by pmoulos** [comment]
+1 please!

**Comment by supercerealoso** [comment]
+1

**Comment by kjolley** [comment]
+1 Note that the first two images suggested are left-handed DNA. DNA is usually a right-handed helix.

**Comment by tagliala** [comment]
@kjolley could you please provide me a proper single color example so I can edit the first post?

**Comment by kjolley** [comment]
![science-dna-helix-icon](https://cloud.githubusercontent.com/assets/7817395/16649684/ed879e0c-4431-11e6-9c92-4db3e11d41a6.png)

Not color, sorry. Found at https://icons8.com/web-app/for/all/DNA.  Note that the strand ascending left to right should pass in front of the other strand.

**Comment by RickZee** [comment]
+1

**Comment by echoStorms** [comment]
+1

**Comment by sjspielman** [comment]
+1

**Comment by jmcmurry** [comment]
+1

**Comment by dridk** [comment]
+1

**Comment by bill-mybiz** [comment]
+1

**Comment by reastwood** [comment]
+1

**Comment by djvreeman** [comment]
+1

**Comment by timbriscoe** [comment]
+1

**Comment by valinaga** [comment]
+1

**Comment by reinson** [comment]
+1

**Comment by sriadiga** [comment]
+1

**Comment by Revenga1** [comment]
+1

**Comment by KristopherWagner** [comment]
any update on this?

**Comment by edikblais** [comment]
+1

**Comment by Tamba32** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by jeponkz** [comment]
+1

**Comment by delicado54** [comment]
+1 !

**Comment by BSoeung** [comment]
+1

**Comment by bobular** [comment]
+1

**Comment by GenCodeDev** [comment]
+1

**Comment by munroe7** [comment]
+1. How come it has been almost 5 years and this is yet to be implemented?

**Comment by GenCodeDev** [comment]
Because it's a free product, not a frickin' McDonalds.
If you need it, do what the rest of us did and create your own or find an alternative.


-------- Original message --------

**Comment by fiskrens** [comment]
+1

**Comment by sensibleworld** [comment]
This icon is included in the latest 5.0.7 release of Font Awesome! The solid style is in Font Awesome 5 Free, with the regular and light styles included in Font Awesome 5 Pro. https://fontawesome.com/icons?d=gallery&q=dna

**Comment by jmcmurry** [comment]
yayyyyYYYYYYYY! Thank you. :)
