### ISSUE TITLE
[Request] New Icon (Unity3D)

### ISSUE THREAD

**Issue by plinio-jrm** [FortAwesome/Font-Awesome#11951]
Hi. Would be nice to have the Unity3D icon!
Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2888, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
