### ISSUE TITLE
Icon request:  fa-memory, fa-cpu

### ISSUE THREAD

**Issue by Bradyok** [FortAwesome/Font-Awesome#11956]
There are no icon for computer memory or CPU, is this something that can be added?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8630 and #3239 , please add a 👍  reaction to those request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
