### ISSUE TITLE
[I Think] that adding 'display: none' to pseudo-elements is not a nice method... when in SVG with js

### ISSUE THREAD

**Issue by Atanacius** [FortAwesome/Font-Awesome#11957]
Well, I'm stumbled the week working on some customers website where I used Font Awesome 4 with regular webfonts icons..

I mean, it's a bit tedious to add each pseudo-element classes the CSS line: `display: none`

When it will be more automatized abilities..
I have some days ago written some new CSS/JS code for show how automatically deal with old FA 4 icons.
WITHOUT any other change than the one which imply to replace "FontAwesome" by "Font Awesome 5 XXXX" in font-face/font attributes.

You can see it here: https://codepen.io/anon/pen/wpwZPY
If it help, I will be very happy, I just written it for me, for better deals with FA4 automatics stuff..

Anyway, if I written this it's firstly because I didn't be able to making working the fa-v4-shim.js script shipped in Font Awesome 5.

It launched an error (even perfectly loaded)..
This causing some JS prevented to run after that.

So, please, can you Pro Team considering look if my changes can help Font Awesome 5 to handle automatically without a .. compatibility script old icons from webfonts in FA 4 ?

Thanks for reading.
(if you close this, please drop me a message, even a private message, I want just help !)

**Comment by robmadole** [comment]
@Atanacius we'd recommend using web fonts with CSS if you are relying on FA4 in this way.

Can you tell us what error you ran into with `fa-v4-shim.js`?

**Comment by Atanacius** [comment]
Well @robmadole my tricks with my changes in fontawesome-all.js and the CSS works without any problems with FA4 syntax, so...
Why I will rely on webFonts if I want use SVG with JS automatically parsed (and working) within my changes ?
Without.. changing any markup !

Not really a good idea that display: none (I mean, it's not really a good idea when entering in compatibility with your older product which is always great !).

Yeah sure, next time I ran this error I will edit this post-issue and give the error line description/log when I will want took the time to push me into this headache again...
