### ISSUE TITLE
Icons request: Seeking to commission design of set of icons for conservation project

### ISSUE THREAD

**Issue by SMART-PM** [FortAwesome/Font-Awesome#11958]
edited by tagliala

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've temporarily removed your message because imho it doesn't follow our contributing guidelines.

I will let you know if it is allowed or not

**Comment by SMART-PM** [comment]
Hi

Thanks for your message. My apologies - it's my first post. Reading again your guidelines - am hoping you might be able to point me in the right direction if my message doesn't meet the criteria?

Thanks!

**Comment by tagliala** [comment]
@SMART-PM I'm still waiting for feedback

**Comment by SMART-PM** [comment]
@tagliala Any updates on next steps? Thanks!

**Comment by tagliala** [comment]
@SMART-PM sorry, no updates

**Comment by sensibleworld** [comment]
@SMART-PM Sorry for leaving this issue languishing for so long! It wasn't on my radar. I'm going to close this post, but you can write us directly at hello@fontawesome.com to discuss commissioning new icons. Thanks!
