### ISSUE TITLE
fontawesome.com very slow

### ISSUE THREAD

**Issue by premiumcuyuz** [FortAwesome/Font-Awesome#11953]
https://fontawesome.com/ very slow why?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It is slow for mee too, I suppose it is largely due to the size of the main app.js file

**Comment by robmadole** [comment]
@premiumcuyuz can you be more specific?

**Comment by tagliala** [comment]
@robmadole I think I can help:

![image](https://user-images.githubusercontent.com/556268/34099011-8246dd6c-e3de-11e7-938a-e4ddec8f2180.png)

![image](https://user-images.githubusercontent.com/556268/34099021-8c09f604-e3de-11e7-8378-a6561daee2a0.png)

The page tooks ~ 16 seconds to show

**Comment by viion** [comment]
For me:

- ~3s uncached
- ~1s or less cached

<img width="1656" alt="screen shot 2017-12-18 at 11 31 55" src="https://user-images.githubusercontent.com/270800/34104149-3c3e55bc-e3e7-11e7-9f54-9a6b9569a79f.png">

Does not feel slow at all, I haven't experienced this using it at home and at work (Both fiber connections, 80mb, in the UK)

**Comment by tagliala** [comment]
@viion thanks.

I'm in Italy with a 20Mbps

Do you mind to check with individual icon page?

It takes a lot of seconds to completely load the page on my side, with cache enabled:

![image](https://user-images.githubusercontent.com/556268/34104838-61f00e26-e3f2-11e7-967e-12e9a075a2ff.png)

**Comment by viion** [comment]
**Page:** https://fontawesome.com/icons/address-book?style=solid

- Cached: ~3s
- Uncached: 3-4s

One of the bigger time-consumers is `carbon.js` but I assume it's being used for advertising, so can't really remove (taking half a second to load). The other being the 2mb js file

**Comment by premiumcuyuz** [comment]
@tagliala okey solved. Thank you!

**Comment by tagliala** [comment]
@premiumcuyuz you're welcome but I did nothing. Is it ok now for you? I still have to wait an unreasonable amount of time before seeing icons

**Comment by premiumcuyuz** [comment]
@tagliala No problem 👍 speed very good.

**Comment by tagliala** [comment]
Closing here

**Comment by robmadole** [comment]
Thanks, everyone. I think we can address most of this issue when we get the CDN configured for the site. We are planning on using Fly.io just haven't gotten that finished yet. Appreciate you all taking the time!

**Comment by aguilera51284** [comment]
I'm not an expert, but the page is still slow and has problems with the use of memory ...

![image](https://user-images.githubusercontent.com/7749319/36042073-44eddb06-0d90-11e8-93f0-9474e09893bb.png)

**Comment by robmadole** [comment]
We'll take care of the non-network performance issues at a later time. The original issue here was network latency.
