### ISSUE TITLE
Treeshaking not working anymore

### ISSUE THREAD

**Issue by SpaceHeroGuide** [FortAwesome/Font-Awesome#11969]
Prior updating to the latest version, tree shaking worked as expected but with the latest version it always includes the complete package instead.

I created a repository to show the behaviour as it could also be a wrong usage of the npm packages by me:

1. Clone the repository https://github.com/SpaceHeroGuide/fa-treeshaking
2. Install dependencies: `npm i` and `npm i -g gulp-cli`
3. Execute Gulp: `gulp`

`out/out.js` now contains the whole free-solid package instead of only the fa-user icon as included in `src/in.js`.

When using the same source code in another project the build time also increased from 40s to 8.75min!

**Comment by SpaceHeroGuide** [comment]
Ok, I'll close this issue as it was a wrong usage of mine. For anyone else interested in using FontAwesome with Rollup, just check the latest commit in my repository or read on:

1. Add the commonjs plugin to your rollup configuration as the FontAwesome files are not written in ES6.
2. Instead of importing from the bundles, import each icon from its own file:
   ```js
   import {default as faUser} from "@fortawesome/fontawesome-free-solid/faUser";
   ```

@robmadole Maybe it would be possible to change the structure of the bundles so we could still use this import statement too?
```js
import {faUser} from "@fortawesome/fontawesome-free-solid";
```

**Comment by robmadole** [comment]
New docs up on tree shaking here. https://fontawesome.com/how-to-use/use-with-node-js#tree-shaking

We had to change things around just a bit with regard to tree shaking.
