### ISSUE TITLE
Icon Request: Store/Shop

### ISSUE THREAD

**Issue by AshSpera** [FortAwesome/Font-Awesome#11963]
Can you make a "**Store**" or "**Shop**" icon please? Something like:

[https://iconmonstr.com/?s=shop](https://iconmonstr.com/?s=shop)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1958 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by nerobdms** [comment]
Store not found.
