### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by frzsombor** [FortAwesome/Font-Awesome#11960]
I have a few suggestions to improve the icon search on fontawesome.com

- [ ] If I search for "gears", I would like to see "cogs" in the results (as it worked on the old .io site).
- [ ] The new "sun" icons also look like a gear/cog, and I worked with a design, where the designer used it as a gear in a "settings" link. Maybe an alias would be great.
- [ ] When I search for "factory", I only see the "industry" icons in the results, but not the "industry-alt" icons, which would be good.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I would not add a gear/cog filter to sun, but the third one is definitely an issue and the first one could be confirmed (maybe there are other people looking for gears)

**Comment by talbs** [comment]
Thanks for bringing this to our attention and apologies for the delay in responding. We updated our search metadata with your suggestions a while back. 

* A search for "gears" now shows `cogs` - https://fontawesome.com/icons?d=gallery&q=gears
* A search for "factory" now shows both `industry` and `industry-alt` - https://fontawesome.com/icons?d=gallery&q=factory

We've done away with aliases in version 5 and decided not to include `sun` in search results for "gear" and "cog". We'll continue to keep an eye on what folks search for and might revisit that in the future.

Thanks again for the help. 😄
