### ISSUE TITLE
Icon Request: icon-ribbon-finger

### ISSUE THREAD

**Issue by lubelski** [FortAwesome/Font-Awesome#1196]
So for my own personal whims and desires, I would like an icon that invokes "remembering to do something" which is related to, but slightly different from "bookmarking" something.  

My front runner is a simple ribbon icon, invoking the "put a ribbon on your finger" meme.  

![stock-illustration-9266613-reminder-ribbon-around-finger-to-remember](https://f.cloud.github.com/assets/195878/580658/8a74b710-c88c-11e2-8306-3e6ea920e7d8.jpg)
Figure 1.  An artist's rendering of a ribbon a finger.  

![130109124227](https://f.cloud.github.com/assets/195878/580659/8ee737b4-c88c-11e2-9763-d73d9d9d8b6d.jpg)
Figure 2.  A picture of a ribbon on a human finger.  

However, I imagine that a relatively abstract "ribbon" might work just fine for this and also be useful for other things, such as donations to causes that use ribbons as a way of signifying support.  

I created a "low fidelity mockup" of such an abstract ribbon.   

![ribbon](https://f.cloud.github.com/assets/195878/580754/a7ae4164-c88e-11e2-8c3b-2cb3c0aac104.png)
Figure 4.  A proposed generic ribbon icon.

**Comment by Timmerop** [comment]
+1

**Comment by ruimelodev** [comment]
![image](https://cloud.githubusercontent.com/assets/16306125/15803488/f7ae849a-2ad7-11e6-971f-7a57a20b7e0c.png)

**Comment by sensibleworld** [comment]
<img width="664" alt="Screen Shot 2021-03-30 at 12 33 08 PM" src="https://user-images.githubusercontent.com/529604/113023848-16c19d80-9154-11eb-9481-f3eceda9ac90.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
