### ISSUE TITLE
The Turkish character experience needs to be improved.

### ISSUE THREAD

**Issue by vdemir** [FortAwesome/Font-Awesome#11962]
The awesome font we use on our sites does not print some Turkish fonts correctly. For example, ş, ı, ğ.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome is not supposed to be used as a font

Could you please provide an example showing this issue?

**Comment by vdemir** [comment]
Thank you for the quick reply. I have such a problem in the fonts I use on the site because I have a lot of knowledge about the subject. For example, some letters in the https://jeruselam.github.io/Hacc-Suresi/ page look different, such as ş, ğ, ı.

**Comment by wolfy1339** [comment]
I checked the site, and FontAwesome is not used anywhere as the font except to actually use FontAwesome icons (.fa class). This issue is invalid. You should probably report it to source-sans-pro

**Comment by tagliala** [comment]
thanks @wolfy1339 

I think that the font is not properly imported from the CDN or the font on the CDN doesn't provide all the range of characters

I've tried to replace with
```
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
```

and it works fine

Before:
![image](https://user-images.githubusercontent.com/556268/34119490-a0ed3768-e422-11e7-866e-94c08ce06f92.png)

After:
![image](https://user-images.githubusercontent.com/556268/34119504-af037c5e-e422-11e7-8690-9120c7fa15e6.png)

Anyway, not a font awesome issue

Closing here
