### ISSUE TITLE
No 5.0.1 release on GitHub?

### ISSUE THREAD

**Issue by bkimminich** [FortAwesome/Font-Awesome#11961]
I would like to keep using Bower in while updating to FA5 in https://github.com/bkimminich/juice-shop/issues/421. Unfortunately FA5 does not have any 5.x release on GitHub yet, so Bower fails with:

```
bower fontawesome#~5        not-cached https://github.com/FortAwesome/Font-Awesome.git#~5
bower fontawesome#~5           resolve https://github.com/FortAwesome/Font-Awesome.git#~5
bower fontawesome#~5      ENORESTARGET No tag found that was able to satisfy ~5

Additional error details:
Available versions in https://github.com/FortAwesome/Font-Awesome.git: 4.7.0, 4.6.3, 4.6.2, 4.6.1, 4.6.0, 4.5.0, 4.4.0, 4.3.0, 4.2.0, 4.1.0, 4.1.0, 4.0.3, 4.0.2, 4.0.1, 4.0.0, 3.2.1, 3.2.0, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0.0, 2.0.0, 1.0.0
```

Is there any plan to add the 5.0.1 and following releases to GitHub as well, so Bower can pick them up automatically?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are aware of this issue, please post your comment at #11908 

Closing here
