### ISSUE TITLE
Icon request: icon-whatsapp

### ISSUE THREAD

**Issue by liquiddigitalit** [FortAwesome/Font-Awesome#11978]
I would like to request the whatsapp icon, I think it should be part of your icon catalog
![whatsapp_icon](https://user-images.githubusercontent.com/34729296/34238334-b5a35a20-e5c6-11e7-9963-79c6308f9769.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

WhatsApp is available since FA 4.3

http://fontawesome.io/icon/whatsapp/
https://fontawesome.com/icons/whatsapp?style=brands
https://fontawesome.com/icons/whatsapp-square?style=brands
