### ISSUE TITLE
If I need upgrade v4 to v5 only CSS, why don't use v4-shims.css?

### ISSUE THREAD

**Issue by adrianoresende** [FortAwesome/Font-Awesome#11973]
I use font-awesome with version 4 only CSS but to upgrade more simple I need to use v4-shims that increase +/- 300 kb of javascript, not good for me.

Why do not use CSS `v4-shims.css` for overwrite, is not it more simple and better?

**Comment by wolfy1339** [comment]
Because the fonts are all different weights, you wouldhave to define it for every icon

**Comment by justlevine** [comment]
@wolfy1339: easily solvable. Just include the `font-weight` in the base .fa class (like you do in fa5 when using pseudoelements).

**Comment by tagliala** [comment]
Hi,

I think this has been solved a while ago in version 5.1.0:

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims

Let me know if this is what you were looking for

**Comment by tagliala** [comment]
Closing here because of missing feedback, this should have been implemented
