### ISSUE TITLE
Font-Awesome v5.x won't display in select list like v4

### ISSUE THREAD

**Issue by dleffler** [FortAwesome/Font-Awesome#11975]
With Font-Awesome v4 I embed icons into my select menus with something like &#xf26e; which displays the icon in both the list of all items and as the selected item. However with v5 I can only see the icon as the selected item...within the list they are all appear as squares.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This was not supposed to work even with FA4, because of browser limitations

Our suggested way of using this feature is via javascript plugins

Refers to:  #996

Hope it helps

Closing here
