### ISSUE TITLE
Need to be able to just copy character off website

### ISSUE THREAD

**Issue by brooks-adcock-dude** [FortAwesome/Font-Awesome#11980]
There appears to be no way to just copy the character off the website and paste it into Illustrator or whatever (assuming font awesome is installed as a font in Illustrator). Why?

The below image shows what can/can't be selected on the icon page.

<img width="992" alt="screen shot 2017-12-21 at 10 32 10 am" src="https://user-images.githubusercontent.com/15834440/34262296-ff116184-e639-11e7-8c1c-6d3ad1a17c88.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you are using Font Awesome 4, you can on the [Cheatsheet](http://fontawesome.io/cheatsheet/)

Also, you could consider Font Awesome 5 which has the copy to clipboard feature on [icon pages](https://fontawesome.com/icons/clone?style=regular)

![image](https://user-images.githubusercontent.com/556268/34263745-c77e7770-e670-11e7-8f17-5bdd668bd2e2.png)


and supports ligatures

![ezgif-2-5395374b2e](https://user-images.githubusercontent.com/556268/34150559-f4e8c8ba-e4a8-11e7-9116-8237b4644631.gif)

Hope it helps

Closing here
