### ISSUE TITLE
SSR issue with @forawesome/fontawesome 1.1.0

### ISSUE THREAD

**Issue by juhaelee** [FortAwesome/Font-Awesome#11984]
I'm receiving the following error when trying to SSR with fontawesome:

```
Cannot read property 'doScroll' of undefined
as node_modules/@fortawesome/fontawesome/index.js:192:39
```

Looks like this line is being executed when DOCUMENT is undefined:
```
var loaded = (DOCUMENT.documentElement.doScroll ? /^loaded|^c/ : /^loaded|^i|^c/).test(DOCUMENT.readyState);

```

**Comment by robmadole** [comment]
Yep, I know what that is. My dumb mistake. I'll get to this quickly when we get back from holiday break.

**Comment by toadkicker** [comment]
For nuxt users I just rolled back a version and things were working again:

```package.json
    "@fortawesome/fontawesome": "=1.0.1",
    "@fortawesome/vue-fontawesome": "=0.0.21",
```

**Comment by OriginalEXE** [comment]
Is there any chance that you could prioritize this?

**Comment by jesdavpet** [comment]
@robmadole I came up with a workaround to enable my own use with Gatsby.js ... works for me.
Do you already have a fix underway for this? If not, would you be interested in a PR?

**Comment by eduludi** [comment]
There is also a `DOCUMENT.documentElement.classList` in  `node_modules/@fortawesome/fontawesome/index.js:1335` that mess SSR

**Comment by ezekielloves** [comment]
Is this the reason why fontawesome 5 icons are not rendering on VueJs?

**Comment by robmadole** [comment]
We'll be releasing some fixes for SSR hopefully today.

**Comment by robmadole** [comment]
5.0.6 should take care of all the SSR issues. Please let me know if you run into any more troubles.
