### ISSUE TITLE
Icon request: icon-filter-bars

### ISSUE THREAD

**Issue by sounders72** [FortAwesome/Font-Awesome#11996]
You currently have a "funnel" as the only option for a filter icon. Could you add one similar to sort_amount_desc (http://fontawesome.io/icon/sort-amount-desc/) but without the down arrow and the bars centered on the ones above it? 

Example below:
![screen shot 2017-12-26 at 8 31 30 am](https://user-images.githubusercontent.com/15475319/34360619-427c41c4-ea17-11e7-8e1f-187cae2ffdce.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I need a better title for this request, because `icon-filter`already exists.

Also, I need a reason for the new design, because [sort-amount-down](https://fontawesome.com/icons/sort-amount-down?style=solid) fit the same use case

**Comment by dcknight** [comment]
This Icon would open a dialog for how the user wants to sort or filter the list. This is a common icon on Android and iOS.

https://material.io/tools/icons/?search=filter&icon=filter_list&style=baseline

**Comment by Madmax-alt** [comment]
This icon is standard for Material Design, would be great to see it added.

**Comment by anderskravis** [comment]
+1 for this icon! Could name it filter-alt with some variations:

filter-alt
filter-alt-circle

**Comment by rintkid** [comment]
Hi guys,
It's 2021 here and there's still a need for this icon (which is quite standard as seen above)
Any news ?

Thanks for the help !
Have a great day

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/bars-filter?s=solid
