### ISSUE TITLE
Version 5.0.2  903 Free Icons Incorrect Count on Home Page

### ISSUE THREAD

**Issue by ravihariharan** [FortAwesome/Font-Awesome#11998]
Home page shows 903.

![image](https://user-images.githubusercontent.com/15189434/34365554-8dd523a0-ea5f-11e7-911b-f19729ca988c.png)

correct is 904 icons (verified thru fa-brands-400.svg,fa-regular-400.svg,fa-solid-900.svg)

![image](https://user-images.githubusercontent.com/15189434/34365551-804dfc84-ea5f-11e7-8825-0178be681d5b.png)

**Comment by tagliala** [comment]
Automaglically solved 🤷‍♂️
