### ISSUE TITLE
Some Icons Won't Show While Others Do

### ISSUE THREAD

**Issue by Jake-Fishman** [FortAwesome/Font-Awesome#11990]
I'm having trouble placing certain icons into my html code. Any suggestions are appreciated!

I'm using this to direct the font awesome code which is a local file:  <script defer src="fa/fontawesome-free-5.0.2/svg-with-js/js/fontawesome-all.js"></script>

All my other font awesome icons are working, but I cannot get the bar chart to show up. I can get the bar to show up by using this as the source file, but then I'm missing other icons:`<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

```
<div class="container text-center">
		<h1>The Arkive</h1>
		<i class="fas fa-archive fa-3x"></i>
	<div class="row">
		<div class="col-sm-4">
			<h2>Professionals</h2>
			<i class="fa fa-check-square fa-3x" aria-hidden="true"></i>
			<h4>By having professionals involved in the content of our website, we can bring men and the information they need together while allowing mental health professionals better understand the men they serve.</h4>
		</div>
		<div class="col-sm-4">
			<h2>Research </h2>
			<i class="fa fa-bar-chart fa-3x" aria-hidden="true"></i>
			<h4>Search the Arkive for the latest research on mental health. We are constantly updating our information and empowering researchers to be knowledgabe educators.</h4>

		</div>
		<div class="col-sm-4">
			<h2>Stories</h2>
			<i class="fa fa-book fa-3x" aria-hidden="true"></i>
			<h4>Read through the many men who have shared their experiences or add your own story to the Arkive. Whether you are looking for advice or have some to offer, join our conversation.</h4>
		</div>
		</div>
	</div>
```

**Comment by KattySanzana** [comment]
I have the same problem :(

**Comment by PeterShaggyNoble** [comment]
It's called `chart-bar` not `bar-chart`: https://fontawesome.com/icons/chart-bar

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks

https://jsfiddle.net/tagliala/h3Lbjh0t/3/
