### ISSUE TITLE
Does not print on Firefox. Chrome and IE9 ok.

### ISSUE THREAD

**Issue by Edddy** [FortAwesome/Font-Awesome#120]
Firefox
![Firefox](http://i.imgur.com/S4w4N.jpg)

IE9
![IE9](http://i.imgur.com/1Knjh.jpg)

**Comment by stfed** [comment]
Try to Reset all Firefox printer settings
Actually, delete or rename prefs.js. It worked for me.
https://support.mozilla.org/en-US/kb/fix-printing-problems-firefox#w_reset-firefox-printer-setting
![untitled-2](https://cloud.githubusercontent.com/assets/13393643/8761662/47f67f44-2d5d-11e5-8e72-d7fd8e3adc47.png)
