### ISSUE TITLE
Icon Request 

### ISSUE THREAD

**Issue by fuat122** [FortAwesome/Font-Awesome#12005]
Can you make your outgoing files your Font-Awesome icon? 
Thanks!

![scratch](https://user-images.githubusercontent.com/9469400/34407132-e7b63142-ebcd-11e7-85c6-f5ec56192005.png)
![small basic](https://user-images.githubusercontent.com/9469400/34407133-e7f3b80a-ebcd-11e7-92ef-8a5c97a59b8f.png)
![arduino](https://user-images.githubusercontent.com/9469400/34407134-e83a8d20-ebcd-11e7-9df6-5f17f021ccc9.png)
![kodu](https://user-images.githubusercontent.com/9469400/34407135-e89e1f48-ebcd-11e7-990a-5fd83cb7cd0d.png)
![makey-makey-logo](https://user-images.githubusercontent.com/9469400/34407136-e8c9cf44-ebcd-11e7-8b2b-17c6791a6480.png)
![mblock](https://user-images.githubusercontent.com/9469400/34407137-e8f4be0c-ebcd-11e7-9826-bf0953723aee.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

If an icon represent a brand, please provide information about the brand you are requesting
