### ISSUE TITLE
Icon request microblog

### ISSUE THREAD

**Issue by spotthehall** [FortAwesome/Font-Awesome#12006]
Please could we have an icon for Manton Reece's new micro.blog?
![micro](https://user-images.githubusercontent.com/311464/34409973-04631516-ebc5-11e7-8b05-03b26a65ed3c.png)
Thanks :)

**Comment by rickroberts** [comment]
+1

**Comment by mjdescy** [comment]
+1

**Comment by cdevroe** [comment]
+1

**Comment by jdsimcoe** [comment]
👍

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/microblog?style=brands

**Comment by RosemaryOrchard** [comment]
I just compiled FontAwesome from SCSS (I downloaded the new ones) and this icon is showing as some Japanese (I think) characters?

<img width="1058" alt="Screenshot 2019-12-19 at 00 08 21" src="https://user-images.githubusercontent.com/16113535/71130996-b1ae9680-21f3-11ea-8507-984971365bef.png">

**Comment by tagliala** [comment]
Hi @RosemaryOrchard , please provide a reproducible test case

You can fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Maybe taking a look here would help: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
