### ISSUE TITLE
Icon Request: Icon Crunchbase

### ISSUE THREAD

**Issue by InsaneNaman** [FortAwesome/Font-Awesome#12001]
I know i am reproducing this issue (#4652 ) and i am sorry for this but i think so most of the users are eagerly waiting for this icon. For every startup/company,  its a must to put a link to their crunchbase profile. So, i request Font Awesome to look into this.

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I understand your point, but I need to close this.

If you want to know how requests work please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by InsaneNaman** [comment]
Thanks :+1:
