### ISSUE TITLE
Icon Request: Cookie

### ISSUE THREAD

**Issue by yocmen** [FortAwesome/Font-Awesome#12015]
Hi, can we get a Cookie icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2845, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
