### ISSUE TITLE
Not showing some icons if included with css - Font Awesome Free 5.0.2

### ISSUE THREAD

**Issue by marxcisis** [FortAwesome/Font-Awesome#12016]
Here is example of what i did.
If you include icon with class, its working as its suppose to, but if i'am including with css there is white square.

Exemple:
https://jsfiddle.net/8s8vjy51/2/

**Comment by tagliala** [comment]
https://jsfiddle.net/tagliala/8s8vjy51/3/

Please pay attention to the font-weight for solid icons (should be 900) and maybe there is an issue with jsfiddle and `//` comments

Hope it helps, closing here

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-using-custom-css-classes-with-font-awesome-5-and-solid-icons-dont-show-up
