### ISSUE TITLE
Arch Icons broken?

### ISSUE THREAD

**Issue by Hacksaurus** [FortAwesome/Font-Awesome#12017]
Hello, I am currently using Arch Linux and today I have noticed that some of my icons are missing or changed, for instance all of the icons that existed in my polybar are now missing, 
Broken state:
![screenshot_2017-12-30_21-41-07](https://user-images.githubusercontent.com/24832107/34459313-330f611c-edaa-11e7-864b-d330cf6b7b90.png)
![screenshot_2017-12-30_21-41-57](https://user-images.githubusercontent.com/24832107/34459324-8a66feb6-edaa-11e7-8f42-9da20625bf48.png)
Original State:
![screenshot_2017-12-17_10-05-57](https://user-images.githubusercontent.com/24832107/34459331-a89eecea-edaa-11e7-8f32-cb74beb42f30.png)
![screenshot_2017-11-07_20-58-01](https://user-images.githubusercontent.com/24832107/34459338-f24da2d2-edaa-11e7-9b46-42f0edc390a2.png)

Even though the icons do not show in polybar they do seem to show in termite the terminal emulator, but they are still not the correct icons:
Broken State:
![screenshot_2017-12-30_09-53-36](https://user-images.githubusercontent.com/24832107/34459334-e0b0af60-edaa-11e7-8b9e-c7a2758bf126.png)
Original State:
Cannot find a screenshot of these icons but they are most definitely  not correct, I simply copy pasted these icons from here:http://fontawesome.io/cheatsheet/ and it seems like they have not changed.

The icons suddenly broke, I may have done an update of some type and then rebooted which caused this.

Thanks for any help!

**Comment by Hi-Angel** [comment]
Same here. FTR, [here's a reddit discussion on the topic](https://www.reddit.com/r/archlinux/comments/7n3uxw/font_awesome/).

**Comment by tagliala** [comment]
Is this somehow related to #10102 ?

**Comment by Hi-Angel** [comment]
Mhm, sorry, I personally don't have enough expertise to tell certainly, however the difference I see is that OP from #10102 just did *something*, and now it doesn't work, and also it was in 2016 year; whereas the current issue is about regression between 4.7.0 and 5.0.2, and is in fact reproducible back and forth by (up|down)grading the font-awesome, and restarting apps.

**Comment by tagliala** [comment]
5.0.2 and 4.7.0 are not compatible.

5.0.2 is based on three files: one with bold weight, one with regular weight, one with brands

Icon names are different, so you cannot simply upgrade from 4.7.0 to 5.0.2 without changing internals

**Comment by Hi-Angel** [comment]
Ok, I think you're right. For some reason I couldn't make i3bar working with the new naming of fonts, and lack of font-related debug output doesn't help either. However I think Font-Awesome per se is alright because on the linked reddit topic peoples who are using polybar managed to make it working by simply changing the name from FontAwesome to `FontAwesome5Free` and `FontAwesome5Brands`, and the fact it's not working for some app out there is not a concern of a font per se.

**Comment by Hacksaurus** [comment]
Downgrading to Font Awesome 4 did the trick, I guess this is an issue with naming, and I'll deal with that later, :P

**Comment by cheng93** [comment]
This worked for me
```
font-2 = FontAwesome5Free
font-3 = FontAwesome5Free:style=Solid
```

and I assume if you want to use brands use `FontAwesome5Brands`

`fc-list`
`fc-match`

to help debug

**Comment by Hi-Angel** [comment]
@cheng93 it's specific to polybar.

**Comment by Hacksaurus** [comment]
Huh, this is kinda weird `fc-list` gives me this:
![screenshot_2018-01-01_07-27-57](https://user-images.githubusercontent.com/24832107/34468406-7e506f10-eec5-11e7-910d-ea7456d96f38.png)
And `fc-match` also gives me this:
![screenshot_2018-01-01_07-30-05](https://user-images.githubusercontent.com/24832107/34468411-9b07fda8-eec5-11e7-9a01-1700b4266661.png)

(My icons are still working because I haven't started a new instance of it)

**Comment by Hacksaurus** [comment]
Meh, closing this issue because this seems to be a lot of changes that were expected, not bugs of any sort...
