### ISSUE TITLE
icon not show with css content

### ISSUE THREAD

**Issue by mrjk990** [FortAwesome/Font-Awesome#12019]
hi , i am first time use fa 5 it's awesome :smiley: 
my problem with css content
check at link https://jsfiddle.net/mrjk990/8v37sxrf/1/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that `\f0a9` is the unicode point of `arrow-circle-right`, which is not part of Font Awesome Brands.

https://jsfiddle.net/tagliala/8v37sxrf/3/

Hope it helps

Closing here

**Comment by DurgaPammi** [comment]
Hi i'm not able to get the content from font awesome 
                  <Collapsible
                  trigger={<div className={classes.collapsibleStyle}>REFINE SELECTION </div>}
                      open
                          >
 .Collapsible__trigger:after {
      font-family: 'Font Awesome\ 5 Free';
       content: "\f107" !important;
      font-weight: 900;
      position: absolute;
      right: 10px;
      top: 10px;
      display: block;
      transition: transform 300ms; 
    }
 Is there any imports needed for this??

**Comment by tagliala** [comment]
@DurgaPammi please open a new issue making sure to follow our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by SaiOduri** [comment]
@DurgaPammi @tagliala I'm having the same issue with the `.Collapsible__trigger:after`. Was this resolved?

**Comment by tagliala** [comment]
@SaiOduri please open a new issue making sure to follow our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
