### ISSUE TITLE
Icon Request: icon-certification

### ISSUE THREAD

**Issue by wloaiza** [FortAwesome/Font-Awesome#12013]
I am not sure if this icon will be included in one of the PRO packages in the future, but it will be nice to have an icon for certification/diploma, something like this: https://www.screencast.com/t/xnfQKdUziuXW

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4420 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
