### ISSUE TITLE
Which files do i need from npm package

### ISSUE THREAD

**Issue by eberhapa** [FortAwesome/Font-Awesome#12029]
Hi,

I installed FontAwesome5 via npm. Now i have the following structure in node_modules:

- @'fortawesome
   - fontawesome
   - fontawesome-free-brands
   - fontawesome-pro-light
   - fontawesome-pro-regular
   - fontawesome-pro-solid

Which files do i need from those folders if i want to use all icons? Please also explain those folders because the "fontawesome" folder includes js and css but no fonts and no svg's in js. 
The other folder include index.js and shakable.js. What is shakable.js?

thanks and best wishes,
Patrick

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does this help?

https://fontawesome.com/how-to-use/use-with-node-js

**Comment by eberhapa** [comment]
Thanks @tagliala but no. I've read the documentation before and it's still ned 100% clear for me.

**Comment by SimplyThomas** [comment]
@eberhapa I was able to pull in the entire library with the following:

`import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import light from '@fortawesome/fontawesome-pro-light'
import regular from '@fortawesome/fontawesome-pro-regular'
import solid from '@fortawesome/fontawesome-pro-solid'

fontawesome.library.add(brands, light, regular, solid)`

Then just make sure that you're compiled javascript file is included. The javascript will search for the correct classes and then make the switch to SVG for you.

Doing it this way, and not specifying which icon from the packs, will significantly bloat your compiled javascript and is not recommended for a production environment. Instead, if you do this for development, just keep track of which icons you end up using and selectively call those in.

**Comment by robmadole** [comment]
@eberhapa does this address you question?

**Comment by eberhapa** [comment]
Sorry, I was busy and got no notification. Yes, it's clear now. Thats the way to use it with ES. Without ES I just need the fontawesome.min.js and the [regular/brands/solid/light].js files or the fontawesome-all.min.js. Thanks for helping out.

**Comment by elasticsteve** [comment]
@SimplyThomas 

Thanks. I wish the imports were mentioned in the docs. I was tearing my hair out! :)
Especially this `fontawesome.library.add(brands, light, regular, solid)`

My next problem is that my config is not working.

I use:

```
window.FontAwesomeConfig = { autoReplaceSvg: 'nest', observeMutations: false };

import fontawesome from '@fortawesome/fontawesome';
import brands from '@fortawesome/fontawesome-free-brands';
import light from '@fortawesome/fontawesome-pro-light';
import regular from '@fortawesome/fontawesome-pro-regular';
import solid from '@fortawesome/fontawesome-pro-solid';
```

But it's not getting picked up.

Any idea?
