### ISSUE TITLE
Icon Request: RocketChat

### ISSUE THREAD

**Issue by razanjoshi** [FortAwesome/Font-Awesome#12026]
Rocket.Chat is the leading free open source team chat Slack alternative. It would be awesome to include their icon in the font awesome icon pack.
[https://rocket.chat/](
https://rocket.chat/)

**Comment by dlareg** [comment]
:+1:

**Comment by ianwijma** [comment]
Added since version 5.8.0: https://fontawesome.com/icons/rocketchat

**Comment by razanjoshi** [comment]
@ianwijma Looks super cool. Cheers 👍

**Comment by tagliala** [comment]
Thanks for the heads-up!
