### ISSUE TITLE
fontspec error: "font-not-found" 

### ISSUE THREAD

**Issue by arezd** [FortAwesome/Font-Awesome#12025]
Hi,

Thanks for providing this font on XeLaTex.
I tried to compile your examples but got this error : 

fontspec error: "font-not-found"
! 
! The font "FontAwesome" cannot be found.

The font is on the right folder so I do not understand why I got this...

Attached is my .log file

Thanks for your help !
[coverletter.log](https://github.com/FortAwesome/Font-Awesome/files/1596586/coverletter.log)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot help because I don't use that program.

> The font "FontAwesome" cannot be found.

Which version of Font Awesome are you using?

**Comment by tagliala** [comment]
No feedback, closing here
