### ISSUE TITLE
Icon Request: fa-selection

### ISSUE THREAD

**Issue by benaubin** [FortAwesome/Font-Awesome#12023]
An icon that represents selecting text.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4842, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by benaubin** [comment]
Whoops, sorry!
