### ISSUE TITLE
Light glyphs not showing in Photoshop

### ISSUE THREAD

**Issue by kristenseocom** [FortAwesome/Font-Awesome#12030]
I've installed the latest font files, but when I copy the glyph from your site, the solid and regular show up but the light ones do not. I tried to search for the SVG file but not all of the ones that show online are there.  I open my glyphs panel in Photoshop and some solid icons show up but the light ones are no where to be found.

**Comment by PeterShaggyNoble** [comment]
Do you have a Pro license?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this problem is specific to light fonts, which are an exclusive of FA5 Pro, please open this request in the pro repository.

I think this is related to font-weight but I cannot be sure

Closing here
