### ISSUE TITLE
fa-cc-amazon-pay and amazon-pay icons do not work in .less in pro5.0.2.

### ISSUE THREAD

**Issue by retailmind** [FortAwesome/Font-Awesome#12036]
<img width="733" alt="bildschirmfoto 2018-01-04 um 11 57 00" src="https://user-images.githubusercontent.com/2620091/34560578-87b9404e-f146-11e7-95f5-788c16c7d8eb.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use the Pro repository https://github.com/FortAwesome/Font-Awesome-Pro
