### ISSUE TITLE
icons flashing ? + ! instead of giving requested icon

### ISSUE THREAD

**Issue by virtualLast** [FortAwesome/Font-Awesome#12032]
I have a pro account and Im trying to use the light version of the icons. I've set the light style library to load before the main fontawesome lib, I can see that the <i> tag gets replaced by the <svg> in the dom but the icon doesnt come through its just a small circle that flashes between ? and !. no error reported nothing

help please

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since light icons are exclusive to Pro users, please open this issue in the Pro repository: https://github.com/FortAwesome/Font-Awesome-Pro

Closing here

**Comment by virtualLast** [comment]
Thanks - opened here : https://github.com/FortAwesome/Font-Awesome-Pro/issues/962
