### ISSUE TITLE
FA5 release notes / changelog

### ISSUE THREAD

**Issue by ispringer** [FortAwesome/Font-Awesome#12035]
It would be very helpful if release notes were released for FA5 releases, particularly since it appears FA5 is no longer open source. I'm interested in what changes are in 5.0.2 since 5.0.1.

Thanks!

**Comment by wolfy1339** [comment]
They haven't switched repos yet. Let's make sure they do this faster. It should have been done with the first public release of FA5

**Comment by robmadole** [comment]
We're working on it. It's a big migration and we don't want to create more problems than we fix. We appreciate everyone's patience.
