### ISSUE TITLE
fa 5.0.2: icons.json/.yml lacks category meta-data

### ISSUE THREAD

**Issue by TheDiveO** [FortAwesome/Font-Awesome#12034]
While upgrading a [Font Awesome plugin](https://github.com/TheDiveO/TW5FontAwesome) for [TiddlyWikis](https://www.tiddlywiki.com) I decided to add an icon cheat sheet (kind of interactive gallery) to the plugin demo wiki, in the spirit of https://fontawesome.com/icons?d=gallery.

In this process I noticed that the `icons.json` and `icons.yml` metadata files from the fontawesome-free-5.0.x distribution lack information about the categories. That is, the [Font Awesome icon galery](https://fontawesome.com/icons?d=gallery) has categories like "Accessibility", "Arrows", et cetera -- see the category checklist in the gallery's sidebar.

Would you please be so kind as to add the category metadata to the `icons.json` and `icons.yml` metadata files? This would allow other projects using Font Awesome icons to also offer icon cheat sheets. While the metadata files contain search terms, they lack any category information. In particular, the search terms can't be used (yet) as a substitute for categories -- for instance, while there is a `accessibility` **search term**, there is only one icon that has this search term, and that's the `fa-accessible-icon`. However, the accessibility **category** of the gallery shows 29 icons (for the free fonts).

Can you please support a `category` property in the metadata files?

**Comment by TheDiveO** [comment]
I noticed that (since 5.0.9?) the FontAwesome 5 GitHub repository contains  `Font-Awesome/advanced-options/metadata/categories.yml` which adds the metadata I've asked for. Thank you very much for this! The only piece now missing is to also offer this information via an npm package, such as maybe `@fortawesome/fontawesome-metadata` (providing the contents of the `Font-Awesome/advanced-options/metadata/` folder. The rationale here is that I can use this automatically in downstream projects; parsing of the .yml file is easy using some node.js yml parser.

**Comment by TheDiveO** [comment]
Unfortunately, as there seems to be no interest to support webfont (as opposed to SVG) installation via npm, I'm left dead in the waters. Thank you for the fish.

**Comment by tagliala** [comment]
@TheDiveO since [we do support installation of webfont via npm](https://www.npmjs.com/package/@fortawesome/fontawesome-free) and, if I'm correct, your original request has been implemented, there is a request to add metadata to npm repository available at #11696. You can upvote that request and follow updates
