### ISSUE TITLE
sports icons needed

### ISSUE THREAD

**Issue by ipeterfulop** [FortAwesome/Font-Awesome#12045]
Are you planning to add some spots icons? running, swimming and so on?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add an upvote to #714, even if #714 does not meet anymore our contributing guidelines

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
