### ISSUE TITLE
please add this icons

### ISSUE THREAD

**Issue by MajesticSJ** [FortAwesome/Font-Awesome#12049]
hey , 
please add this icons : 
[Uplay](https://uplay.ubi.com/)
[Origin](https://www.origin.com/usa/en-us/)
[Battle.net](https://us.battle.net/login/en/)
[Asus](https://www.asus.com/us/)
[Asus Rog](https://rog.asus.com/)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
