### ISSUE TITLE
SVG sprite, issue setting icon size.

### ISSUE THREAD

**Issue by abenz1267** [FortAwesome/Font-Awesome#12041]
Hello,

i can't get the icons to be the size i want.

F.e. i'll do this:

```
<svg>
          <use xlink:href="/public/images/fa-regular.svg#bars"></use>
</svg>
```

and in my css i do that:

```
svg {
    fill: $white;
    height: 1em;
 }
```

As a result i expect my icon to be 1em high and the width should be set automatically, to keep the ratio. The actual result makes me crazy: the svg has a height of 1em, ok...but the actual "use" element is always smaller, meaning: i can't make the actual icon 1em.

And idea? What am i missing?

Regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a fiddle showing what you are trying to achieve?

You can start with https://jsfiddle.net/tagliala/h3Lbjh0t/

Please also note that all icons have the same height and different width.

The bars icon has top and bottom padding, so it cannot "fill" 1em eight

![image](https://user-images.githubusercontent.com/556268/34583270-61e0311a-f197-11e7-8b32-320d9fd632de.png)

**Comment by robmadole** [comment]
The bars have that height so that it works well with the other icons in the category.  Sorry that's annoying to you @abenz1267 but this is a `wontfix`.
