### ISSUE TITLE
SVG w/Javascript does not work on Angular single page apps

### ISSUE THREAD

**Issue by toddjcrane** [FortAwesome/Font-Awesome#12046]
Icons do not load on single page apps made with angular. I suspect this is because the "pages" are loaded after first paint and thus FA doesn't process them

**Comment by NateRadebaugh** [comment]
The following angular-specific implementation will likely meet your needs when the project is production-ready: https://github.com/FortAwesome/angular-fontawesome/

**Comment by robmadole** [comment]
Correct. We'll be releasing the Angular component when we get that finished. Closing for now.
