### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by LouMaster** [FortAwesome/Font-Awesome#12042]
I've been using the new Font Awesome on my site, but i'm having problem while adding gradient color/background to it, how can i do it?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which version are you using? SVG or webfont?

**Comment by LouMaster** [comment]
I'm using svg


Em 5 de jan de 2018 00:42, "Geremia Taglialatela" <notifications@github.com>
escreveu:

**Comment by PeterShaggyNoble** [comment]
See #11925

**Comment by tagliala** [comment]
I suppose this is about *background* gradients

I don't see any issue: https://jsfiddle.net/tagliala/h3Lbjh0t/4/

**Comment by tagliala** [comment]
No feedback, closing here
