### ISSUE TITLE
js/packs/ missing

### ISSUE THREAD

**Issue by ZeroPie** [FortAwesome/Font-Awesome#12059]
where do i find "js/packs/solid.js"?
https://www.npmjs.com/package/@fortawesome/fontawesome
  
404
https://github.com/FortAwesome/Font-Awesome-Pro/tree/master/js/packs

**Comment by robmadole** [comment]
We renamed `packs` to `styles` a while back. Updated docs are here: https://fontawesome.com/how-to-use/font-awesome-api
