### ISSUE TITLE
Icon request: Azure

### ISSUE THREAD

**Issue by pratnala** [FortAwesome/Font-Awesome#12050]
Would be great to have an icon for Microsoft Azure `fa-azure` - one of the leading cloud services. Attached their logo below:

<img src=https://azurecomcdn.azureedge.net/cvt-4ba1ac63410bb2bbe9f1c2a7bedc57894bbe9754309d9d380deedcdf7850047e/images/shared/social/azure-icon-250x250.png>

**Comment by PeterShaggyNoble** [comment]
Duplicate of #5212
