### ISSUE TITLE
find duplicate icons

### ISSUE THREAD

**Issue by Artlant** [FortAwesome/Font-Awesome#12054]
im find duplicate icons:

1. ` fa-cog [&#xf013;]` and ` fa-gear (alias) [&#xf013;]`
2.  ` fa-cogs [&#xf085;]` and ` fa-gears (alias) [&#xf085;]`

**=the same**

made deliberately for compatibility?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Before introducing filters in documentation, we were using aliases in FA4 to improve search. (es `fa-close` alias of `fa-times` because people were looking for "close")

Hope it helps

Closing here
