### ISSUE TITLE
Why Font Awesome 5 not support Bower

### ISSUE THREAD

**Issue by jefer94** [FortAwesome/Font-Awesome#12053]
I have a project with a Angular.JS APP, because of the type of project, we not use webpack, and instead of use Bower for manage we project, I know that a within a short time, the ES Modules come to the browser, but for now we can't migrate it for ES Modules.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Bower has been "deprecated" a while ago

Official answer: https://github.com/FortAwesome/Font-Awesome/issues/11908#issuecomment-353192558

Post on the bower blog: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Hope it helps

Closing here

**Comment by jefer94** [comment]
Thanks

**Comment by brookjordan** [comment]
So for people stuck on bower, we're also stuck on font-awesome 4.7?

**Comment by wolfy1339** [comment]
Until the repo gets updated to v5, yes.
You can use the git repository in Bower

**Comment by jefer94** [comment]
It's true, I forgot it wolfy1339, and thanks
