### ISSUE TITLE
Icon request: mercadopago

### ISSUE THREAD

**Issue by mrnkr** [FortAwesome/Font-Awesome#12051]
Hello everyone!

First of al thanks for the awesome tool you provide us with, I just love it!

I was wondering if you guys could eventually add the icon for MercadoPago which is kinda like PayPal for Latin America (at a lower scale, obviously, we do have PayPal). The icon is the following:
![MercadoPago Logo](https://www.tarjetamercadopago.com.mx/assetsv3/images/logo_tarjetamercadopago_small.png)

I was planning on using it in a button inside my app next to the text 'Checkout with MercadoPago' which is above another button which has the same format but works with PayPal.

Thank you!

**Comment by PeterShaggyNoble** [comment]
Duplicate of #10072
