### ISSUE TITLE
Icon request: currency icon for peso

### ISSUE THREAD

**Issue by jalilyacob** [FortAwesome/Font-Awesome#12062]
![php](https://user-images.githubusercontent.com/4043117/34713803-4cd80a26-f562-11e7-909c-34bada290d00.jpeg)

**Comment by doodlefudge** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1267, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by jalilyacob** [comment]
Already voted for the previous request before creating this one, This request is for a generic Peso icon.

**Comment by tagliala** [comment]
Hi, since the example you provided is the same as #1267, I should consider this a duplicate.

If you are concerned about `(philippines)` in the title, it should not be a problem as long as the glyph is the same.
