### ISSUE TITLE
Medium logo for fa-medium is out of date

### ISSUE THREAD

**Issue by clwdesign** [FortAwesome/Font-Awesome#12065]
The logo for medium.com has changed and the logo available via fa-medium needs updating as well

Medium branding guidelines here -- https://medium.design/logos-and-brand-guidelines-f1a01a733592

**Comment by clwdesign** [comment]
My bad, I see this has been reported already.

**Comment by tagliala** [comment]
Hi, this has also been fixed in FA5: https://fontawesome.com/icons?d=gallery&q=medium
