### ISSUE TITLE
faAt seems to be missing

### ISSUE THREAD

**Issue by niknokseyer** [FortAwesome/Font-Awesome#12061]
I can't find it from:
`npm install --save @fortawesome/fontawesome-pro-regular`
or
`npm install --save @fortawesome/fontawesome-pro-light`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please report this to the Pro repository?

https://github.com/FortAwesome/Font-Awesome-Pro/issues

**Comment by robmadole** [comment]
Just ran these commands:

```
mkdir fa-at-check
cd fa-at-check
npm init -f
npm i --save @fortawesome/fontawesome-pro-regular
npm i --save @fortawesome/fontawesome-pro-light
```

Then:
```
find node_modules/@fortawesome | grep faAt
```

Output:
```
node_modules/@fortawesome/fontawesome-pro-light/faAt.js
node_modules/@fortawesome/fontawesome-pro-regular/faAt.js
```

If you still can't find it can you create a reproducible case?
