### ISSUE TITLE
Switch from regular to solid (fill-in effect) is bugged

### ISSUE THREAD

**Issue by boneyao** [FortAwesome/Font-Awesome#12067]
version: fontawesome v5.0.3

demo: 
https://jsfiddle.net/o4rgekk4/3/

I want onMouseEnter show "far" onMouseLeave show "fas" (opacity: 0.2;), They're not perfect。

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue has been reported by me in the Pro repository. It affects
- heart
- star
- thumbs-up

I should also point out that switching from outline to solid for every icon is not an intended feature.

Leaving this open for tracking purposes

**Comment by sensibleworld** [comment]
We have updated the heart icon so that it matches across styles, but are unlikely to make too many changes to other icons. Our styles are meant to work independently of each other, not necessarily as filled + outlined versions of the same icon. Though, with version 6, they should be much closer.
