### ISSUE TITLE
fill attribute is missing for svg sprites. 

### ISSUE THREAD

**Issue by yokun** [FortAwesome/Font-Awesome#12079]
Need to have fill="currentColor" with no JS option for SVG sprites.

Thank you!

**Comment by robmadole** [comment]
This can be accomplished with CSS which is the original intention with the SVG sprites.

**Comment by yokun** [comment]
CSS color was not working for me, only after I manually added  <path fill="currentColor" ... then the parent color was getting applied

**Comment by robmadole** [comment]
@yokun here is an example https://codepen.io/robmadole/pen/PQoQoP

**Comment by yokun** [comment]
Thanks a lot for the response. We were able to add fill: currentColor with css.
