### ISSUE TITLE
5.0.3 icon packs don't export an icon array

### ISSUE THREAD

**Issue by Torqode** [FortAwesome/Font-Awesome#12072]
In 5.0.2 icon packs (solid, regular, etc), the index.es.js (and shakable.es.js) had a default export that was an array of all the icons in the pack.

```
var icons$1 = { faAddressBook: faAddressBook, faAddressCard: faAddressCard, ... etc etc }
export default icons$1;
```

In 5.0.3, the packs now include an index.d.ts, which is nice, but all icons are exported individually.  This makes it impossible to import the entire pack.

```
import fontawesome from '@fortawesome/fontawesome';
import solid from '@fortawesome/fontawesome-free-solid';
fontawesome.library.add(solid);
```

The add method throws the following error:

> ERROR in app.module.ts(12,25): error TS2345: Argument of type 'typeof "myapp/node_modules/@fortawesom...' is not assignable to parameter of type 'IconDefinition'.
>   Property 'icon' is missing in type 'typeof "myapp/node_modules/@fortawesom...'.

**Comment by tagliala** [comment]
@robmadole could you please check?

**Comment by robmadole** [comment]
Sure thing. I believe this will be an easy fix.

**Comment by mlwilkerson** [comment]
I'm on it.

**Comment by mlwilkerson** [comment]
@Torqode I just released `@fortawesome/fontawesome` 1.1.2 and `@fortawesome/fontawesome-free-solid` (and other icon packs) 5.0.4 which I think will fix this—if tsc is configured for es2015 modules.

Could you try these and let me know?

**Comment by Torqode** [comment]
Thanks for the quick response.

My dev build is configured for commonjs and prod build for es2015.  Both are throwing the same error now:

> TS2345: Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinition'.
>   Property 'icon' is missing in type 'IconPack'.

**Comment by mlwilkerson** [comment]
@Torqode sorry about that. We're dealing with some challenges about how TypeScript tries to negotiate around various kinds of exports and the differences between CommonJS and ES2015. I have my own integration tests that are all passing, but they are based on my build configurations working in harmony together between tsc and rollup. You no doubt have a different build configuration. 

Does your `tsconfig.json` (or equivalent) have `allowSyntheticDefaults: true`?

Actively still working on a better solution here...

**Comment by Torqode** [comment]
Yes, allowSyntheticDefaults is true in my config.  I'm using webpack and Angular 5.

**Comment by mlwilkerson** [comment]
I'd like to try and reproduce your build scenario more closely. Can you give me any more specifics to help me do that?

If I just spun up a new app with Angular CLI, for example, would that basically be your scenario? Or are there are parts and configs?

**Comment by Torqode** [comment]
I would think an Angular CLI project would mimic my app fairly closely.  The only thing I can think that might not be handled by the CLI would be the aliases in webpack.  You might have to `ng eject` the CLI config and manually update it:

```
    var config = {
        entry: {  /* entry stuff here */ },
        resolve: {
            extensions: ['.ts', '.js', '.json'],
            alias:
            {
                '@fortawesome/fontawesome-free-solid$': '@fortawesome/fontawesome-free-solid/shakable.es.js',
                '@fortawesome/fontawesome-free-regular$': '@fortawesome/fontawesome-free-regular/shakable.es.js',
                '@fortawesome/fontawesome-free-brands$': '@fortawesome/fontawesome-free-brands/shakable.es.js'
            },     
        },
}
```

**Comment by mlwilkerson** [comment]
@Torqode I think I just spotted the problem here. It looks like it may not be the `import`, per se, but the function call signature for `library.add()`. (I have an Angular CLI app, Angular 5 working fine with the import, by the way). 

I've typed that `library.add()` function to accept a list of `IconDefinition`s as arguments, but you're passing it the whole pack object, which is an `IconPack`. So the TypeScript error makes sense. 

Analyzing our code more closely, it's clear that `library.add()` does need to be able to accept an `IconPack` or a list of `IconDefinitions`, which wasn't clear to me when I defined the types. Sorry to break your code! I'll make that fix and send you a pre-release soon to see if that fixes your problem.

**Comment by mlwilkerson** [comment]
@Torqode I've just published some pre-release packages for you to try. Could you let me know how these work for your use case?

`@fortawesome/fontawesome@1.1.3-1`
`@fortawesome/fontawesome-free-solid@5.0.5-1`

**Comment by Torqode** [comment]
Those changes worked.  The only modification I had to make was to add the libraries separately instead of all in one line.

`fontawesome.library.add(solid, regular, faFacebook, faGoogle);`

became

```
fontawesome.library.add(solid);
fontawesome.library.add(regular);
fontawesome.library.add(faFacebook, faGoogle);
```

Thanks for your quick response to this issue!

**Comment by mlwilkerson** [comment]
Right, OK. Maybe I can tweak it further to allow your one-liner. I'll look into it.

Thanks for the feedback. Really helps me get things worked out.

**Comment by mlwilkerson** [comment]
@Torqode I confirmed that our docs do recommend your initial usage—adding a mix of `IconDefinition` and `IconPack` objects in a single call to `library.add()`. So clearly that type definition needed another tweak. Here's another pre-release:
`@fortawesome/fontawesome@1.1.3-2`

Could you let me know if this lets you do the one-liner?
```
fontawesome.library.add(solid, regular, faFacebook, faGoogle);
```

**Comment by Torqode** [comment]
Yes, 1.1.3-2 lets the one-liner work again (tried using both fontawesome-free-solid 5.0.4 and 5.0.5-1).  Thanks!

**Comment by mlwilkerson** [comment]
Great! Thanks for the feedback.

**Comment by jhunexjun** [comment]
Looks like we have the similar/same issue only that my issue is for `@fortawesome/free-brands-svg-icons/`. Can you please check it?

I just saw this error reported, [14176](https://github.com/FortAwesome/Font-Awesome/issues/14176)
