### ISSUE TITLE
icon-request: front-side-truck

### ISSUE THREAD

**Issue by GangstaSunny** [FortAwesome/Font-Awesome#12075]
Hello,
it would be verry cool if you are going to add a lorry icon.

Same like the existing https://fontawesome.com/icons/car?style=solid icon but the front of a lorry.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not an English native speaker.

Do you mean a front side version of https://fontawesome.com/icons/truck?style=solid ?

**Comment by GangstaSunny** [comment]
Hey, thanks & yes.
It would be (font) awesome!

**Comment by aethior** [comment]
Hi @GangstaSunny,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/truck-front

Regards.

cc/ @tagliala
