### ISSUE TITLE
fa-share-alt missing

### ISSUE THREAD

**Issue by frigmous** [FortAwesome/Font-Awesome#12087]
The various versions of share-alt don't appear. There's a space for them, but no icon. Was share-alt not included in v5 or is this a bug? I'm guessing bug because if you click on the icon you can see the SVG outline - way off-center to the right and with no fill. No stroke, either, just handles and vertices.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate

https://fontawesome.com/icons/share-alt?style=solid
https://jsfiddle.net/tagliala/4gcqLvt9/2/


Closing here

**Comment by frigmous** [comment]
Only happens on Mac Safari, apparently. And only to that character, so I’m guessing there’s some tiny thing in the SVG somewhere that Safari trips on.

[cid:image001.png@01D38F87.C9ECE9A0]

**Comment by frigmous** [comment]
Never mind - not your bug. It's AdBlock Ultimate's. When I disable it, the glyph shows up just fine.
