### ISSUE TITLE
Icon request: icon-Gaming , Icon-Fantasy , and ...

### ISSUE THREAD

**Issue by zerokara** [FortAwesome/Font-Awesome#12097]
hi , thx for ur service and ur good work
i need follow icon from under: for my site menu Icons and u can see a good exaple from webnovel.com menu

Icon-Gaming
Icon-Xianxia 
Icon-Xuanhuan
Icon-Fantasy
Icon-Sci-fi
Icon-Romance
Icon-Other

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
