### ISSUE TITLE
Icon request: icon-aparat

### ISSUE THREAD

**Issue by navidviola** [FortAwesome/Font-Awesome#12090]
"Aparat" is an Iranian video sharing website. This is a social media network and we need theirs icon for using in social media icons. there is PNG here : https://www.aparat.com/logo
Thank u very much for adding this icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5204, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
