### ISSUE TITLE
Icon request: icon-font-square (font background color)

### ISSUE THREAD

**Issue by thekrotek** [FortAwesome/Font-Awesome#12094]
In Editors section an icon for background color is definitely missing. This one should be very simple: icon-font, but light text on dark background.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5570, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by thekrotek** [comment]
But that issue is back from 2015! Looks like it was forgotten a long time ago.
