### ISSUE TITLE
Icon request: icon-opensource

### ISSUE THREAD

**Issue by tandpfun** [FortAwesome/Font-Awesome#12092]
I might use this to show that my code is open source. The logo is included:

![open-source-software-](https://user-images.githubusercontent.com/28990589/34908095-57a48cce-f83f-11e7-87d2-7579d0be5740.jpg)

I think it would be a great addition to the icons!
thanks,
Codingpro/tandpfun

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This logo is already available as `fa-osi`

https://fontawesome.com/icons/osi?style=brands

Closing here

**Comment by tandpfun** [comment]
Thanks!
