### ISSUE TITLE
Icon request : icon-piano

### ISSUE THREAD

**Issue by MajesticSJ** [FortAwesome/Font-Awesome#12095]
Hey , please add piano icon . Thanks .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5054 or #770, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
