### ISSUE TITLE
Icons are not centered

### ISSUE THREAD

**Issue by franz-josef-kaiser** [FortAwesome/Font-Awesome#121]
The font is horizontally not aligned inside it's box (this is a problem with the font itself). If you add the following mark-up, you can check it yourself:

<pre>
<style type="text/css" title="text/css">
      .icon { 
                margin: 0 auto;
                position: relative;
                display: block;
                color: #fff;
                line-height: 1.3; /* can be used to fix the vertical alignment */
            background-color: #000;
            -webkit-border-radius: 9999px !important;
               -moz-border-radius: 9999px !important;
                    border-radius: 9999px !important;
      }
</style>
<div>
    <span class="icon icon-glass"></span>
    <span class="icon-label">Label</span>
</div>
</pre>

This shows that the font is positioned too close to the top-right corner. Should be fixed in the font-files themselves.

The problem can be seen in the screenshot:

<img src="http://i.imgur.com/kl3z5.png" />

**Comment by bjorn-ali-goransson** [comment]
@davegandy the issue here was actually horizontal positioning, not vertical ...
