### ISSUE TITLE
Wrong icon description

### ISSUE THREAD

**Issue by VladimirHumeniuk** [FortAwesome/Font-Awesome#12105]
Hey guys, looks like you have wrong description here:
https://fontawesome.com/icons/linkedin?style=brands
because it is a ```.fa-linkedin-square``` and not ```fa-linkedin```. 

And class ```fa-linkedin-in``` (https://fontawesome.com/icons/linkedin-in?style=brands) does not work, because it is ```fa-linkedin```.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Linkedin demands a square around the "in" so it is not an issue: https://brand.linkedin.com/

linkedin-in is a version which does not meet their brand guidelines (though doesn't violate them) for alternative usages

They both work for me: https://jsfiddle.net/tagliala/4gcqLvt9/3/

Hope it helps

Closing here
