### ISSUE TITLE
Icon request: icon-dogbuddy

### ISSUE THREAD

**Issue by jirachi155** [FortAwesome/Font-Awesome#12106]
Hello FA,

I'm the Lead Product Designer at DogBuddy and FA supporter since the beginning of times.
We kindly would like to ask you to help us getting our logo on your list of icons - we would love to see it there and have it handy for our DogBuddy website + partners!

DogBuddy is the leader in Europe when it comes down to finding a dog sitter and we've reached a great level of reputation and promotion around Europe in the past 3 years. 

I leave you the icon attached in SVG (in a zip) file + a preview in PNG in the hope to see it live:
![icon-dogbuddy](https://user-images.githubusercontent.com/7416861/34949519-99e54966-fa10-11e7-9b73-a5be53dc2145.png)
[icon-dogbuddy.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1632116/icon-dogbuddy.svg.zip)

Woof,
DogBuddy

**Comment by aethior** [comment]
DogBuddy was adquired by Rover.com in 2018. ([more info](https://www.geekwire.com/2018/rover-acquires-u-k-based-dog-care-company-dogbuddy-accelerating-european-expansion/))

Regards.

cc/ @tagliala
