### ISSUE TITLE
How to prevent auto convert on single words when typing on Sketch

### ISSUE THREAD

**Issue by l2aelba** [FortAwesome/Font-Awesome#12104]
**Example** I want to use **[facebook-square](https://fontawesome.com/icons/facebook-square)** icon

But when typing (or paste) on **[Sketch](https://www.sketchapp.com/)** is auto convert to **book** and **square** when typing.

![5xzyn8qusa](https://user-images.githubusercontent.com/983458/34944355-90244924-f9ff-11e7-8421-48dfa029ac67.gif)

**Any tick to prevent this ?**, Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Just guessing... please try with "Font Awesome 5 Brands" as font

**Comment by l2aelba** [comment]
OMG!!!! That what I did wrong.

Solved, Thanks @tagliala !

**Comment by tagliala** [comment]
You're welcome.

Closing here
