### ISSUE TITLE
Icon request: icon-dice (or: icon-pawn)

### ISSUE THREAD

**Issue by top-jonathan** [FortAwesome/Font-Awesome#12103]
Right now there is a nice gamepad icon to represent 'videogaming'.
I am looking for some symbol to represent board games. This could be a dice or a pawn.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2622 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
