### ISSUE TITLE
How do i upload our Own Company icon on Fontawesome.io ?

### ISSUE THREAD

**Issue by Rackons2015** [FortAwesome/Font-Awesome#12117]
How do i upload our Own Company icon on Fontawesome.io ?

Please suggest best answer then we will upload our company icon in fontawesome.io

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment this is not possible with fontawesome.io and fontawesome.com, but it is available at https://fortawesome.com/ (commercial product).

Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome to understand how to build a custom version of font awesome.

@robmadole is this going to change for FA5 Pro users?

Hope it helps

Closing here
