### ISSUE TITLE
arrows-alt not loading

### ISSUE THREAD

**Issue by leanda** [FortAwesome/Font-Awesome#12113]
Hi 

I don't seem to be able to get <i class="far fa-arrows-alt"></i> to load using <i class="fa fa-arrows-alt"> as an alternative. Any ideas why?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information?

I cannot replicate

5.0.3 CSS: https://jsfiddle.net/tagliala/4gcqLvt9/4/
5.0.3 SVG: https://jsfiddle.net/tagliala/a756ay7m/2/

Closing here

**Comment by leanda** [comment]
@tagliala Could this be because the CDN only supports the free icons?

**Comment by tagliala** [comment]
@leanda Yes, it does. 

AFAIK, the Pro CDN is still a work in progress: https://fontawesome.com/updates

If you are a Pro backer, please use the Pro repository to report issues https://github.com/FortAwesome/Font-Awesome-Pro/issues
