### ISSUE TITLE
Icon Request: fa-tent fa-camp fa-campfire fa-hiker

### ISSUE THREAD

**Issue by webypo** [FortAwesome/Font-Awesome#12110]
I like that you offer 2 kinds of trees, but for those with outdoor interests, a campfire, tent, or even a hiker would be nice additions of these, the tent and campfire would be my first choices with the hiker as a third choice in terms pf preference.  Thank you for considering these, I appreciate all you have done so far Keep up the good work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
