### ISSUE TITLE
Icon request: icon-double-level-up icon-double-level-down

### ISSUE THREAD

**Issue by oktav** [FortAwesome/Font-Awesome#1211]
Hi,

I'm using as reference the new 3.1.1 icons. I think it would be useful to have a icon-double-level-up and down like in icon-double-angle-up and down.

I'm using the level-up and level-down as priority modifiers. The single level up/down would increase/decrease by one, while the double ones would bring the priority to highest/lowest.

Thanks

**Comment by sensibleworld** [comment]
Doing some issue cleanup and came across this request. Happy sos ay that we have angle-double-up and angle-double-down in version 5 now.

https://fontawesome.com/icons/angle-double-up?style=solid
https://fontawesome.com/icons/angle-double-down?style=solid
