### ISSUE TITLE
[Logo Request] YP Logo

### ISSUE THREAD

**Issue by GitStl** [FortAwesome/Font-Awesome#12116]
Hey Guys, 

I get a lot of requests for the YP logo as there are a lot of customer reviews on it. There was a request submitted in 2014. Do you know when it will be added?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

YP = Yellow Pages? #4648 ?

Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome to understand how requests work

Hope it helps

Closing here

**Comment by GitStl** [comment]
Thanks, is there an estimate on when? It’s been requested for 5 years now.
