### ISSUE TITLE
FA Pro - React Native - Invariant Violation Error

### ISSUE THREAD

**Issue by jack828** [FortAwesome/Font-Awesome#12125]
EDIT: this may be in the wrong repo 😬 

Hey!

I'm trying to get Font Awesome 5 Pro into a new app I'm making 🎉 

I've followed the documentation as best as I can, as there's no specific docs for React Native.

In my App.js - 
```javascript
import fontawesome from '@fortawesome/fontawesome'
import FontAwesomeIcon from '@fortawesome/react-fontawesome' // Maybe not needed?
import faCoffee from '@fortawesome/fontawesome-pro-light/faCoffee'

fontawesome.config =
  { familyPrefix: 'fal'
  }
fontawesome.library.add(faCoffee)
```

In a React component's `render` - 

```jsx
import FontAwesomeIcon from '@fortawesome/react-fontawesome'
<FontAwesomeIcon icon={route.icon} />
```

Where `route.icon` is currently `coffee`.

This, however, causes the following error to be thrown: 
```
Could not find icon, Object {
  "iconName": "coffee",
  "prefix": "fas",
}
- node_modules/@fortawesome/react-fontawesome/index.js:450:37 in log
```

Which is interesting, because according to the docs this is how I should be able to change the default prefix.

If I explicitly ask for that prefix using

```jsx
import FontAwesomeIcon from '@fortawesome/react-fontawesome'
<FontAwesomeIcon icon={[ 'fal', route.icon ]} />
```

This causes a _different_ error to be thrown:
```
Invariant Violation: View config not found for name path

This error is located at:
    in path (created by FontAwesomeIcon$1)
    in svg (created by FontAwesomeIcon$1)
    in FontAwesomeIcon$1 (at grid2.js:58)
    in RCTText (at Text.js:557)
    in Text (at rkText.js:82)
    in RkText (at grid2.js:55)
    in RCTView (at View.js:112)
```

This happens if I remove the config change as well, and also if I change the icon import from the `light` version to the `solid` one. Even importing the icon and using it directly in the component's `render` function doesn't work!

Any ideas?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please report this on the Pro repository? https://github.com/FortAwesome/Font-Awesome-Pro/issues

**Comment by jack828** [comment]
Can do!

**Comment by shyaniv7** [comment]
I am trying to use font awesome pro with react native. So far no luck.
I have tried everything mentioned by @jack828 as well.

@jack828 any luck with this?

Thanks

**Comment by shyaniv7** [comment]
I wrote a package that will allow you to easily use your font awesome pro in react native

https://www.npmjs.com/package/react-native-fontawesome-pro

**Comment by jack828** [comment]
@shyaniv7 I had no luck and went to a working solution using FA4.
Nice library though! Do you have plans to support android as well? I can assist :grin:

**Comment by shyaniv7** [comment]
@jack828 thanks for letting me know. I refactored everything version 1.0.11 works on both android and iOS. Please follow the readme in order to install it currently 👍
