### ISSUE TITLE
icon-danger

### ISSUE THREAD

**Issue by 799160654** [FortAwesome/Font-Awesome#12126]
![default](https://user-images.githubusercontent.com/35522890/35077525-d8ed512e-fc38-11e7-88f5-5e64619ff589.png)

Danger / alarm / warning

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have three icons to represent danger:

https://fontawesome.com/icons/exclamation-triangle?style=solid
https://fontawesome.com/icons/exclamation-square?style=solid
https://fontawesome.com/icons/exclamation-circle?style=solid

Hope one of them will fit your use case.

If they don't please explain why you need the design in your example

Meanwhile, closing here
