### ISSUE TITLE
How to upload your own icon?

### ISSUE THREAD

**Issue by xiami619** [FortAwesome/Font-Awesome#12128]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

That works for the CSS version, I can't point out a solution for the SVG framework

Hope it helps

closing here

**Comment by xiami619** [comment]
I need to use it in js, I'm going to make the makecode library with js.

**Comment by tagliala** [comment]
@xiami619 sorry, I don't know about customization in JS.

@robmadole have you a better answer?

**Comment by robmadole** [comment]
@xiami619 sorry but this is not supported yet. It's on the todo list.
