### ISSUE TITLE
Knockout Click Event Firing Twice

### ISSUE THREAD

**Issue by Grandizer** [FortAwesome/Font-Awesome#12122]
I just noticed that when using KnockoutJS and an <i> tag that a click event fires twice.  The below code shows 4 different buttons that each send to the same Click event.  The 3 with the <i> tag and font-awesome icon fire twice.  The button without the <i> and thus no icon, fires a single time.  I am on FA 5.0.4 and 3.4.2 of KO.

```
<tbody data-bind="foreach: { data: LockedOutUsers, as: 'u' }">
	<tr>
		<td data-bind="text: u.FirstName"></td>
		<td data-bind="text: u.LastName"></td>
		<td><span data-bind="text: u.LockoutEnd().format('MM/DD/YYYY @@ hh:mm:ss')"></span></td>
		<td class="text-center">
			<i data-bind="click: $root.unlockUser" class="far fa-lock-open hand"></i>
			<button type="button"
							data-bind="click: $root.unlockUser"
							class="btn btn-sm btn-outline-primary"
							title="Click here to Unlock this User">Unlock User</button>
			<button type="button"
							class="btn btn-sm btn-outline-primary"
							title="Click here to Unlock this User">
				<i data-bind="click: $root.unlockUser" class="far fa-lock-open hand"></i>
			</button>
			<button type="button"
							data-bind="click: $root.unlockUser"
							class="btn btn-sm btn-outline-primary"
							title="Click here to Unlock this User">
				<i data-bind="click: $root.unlockUser" class="far fa-lock-open hand"></i>
			</button>
		</td>
	</tr>
</tbody>

```

**Comment by robmadole** [comment]
Hi there, create a codepen, jsbin, codesandbox or similar that demonstrates the problem and we'll take a look.

**Comment by Grandizer** [comment]
Okay, I have created one [here](https://jsbin.com/dafaqof/edit?html,js,output). However, I am unable to get the FA portion to work.  All of the icons just show question marks.  What is missing there?

If you tweak it to get the icons to show, the example should show that the first button "Works good" has no icon and just fires once.  The next 2 seem to always fire twice.  The last button will fire one time if I click on the button but outside of the icon.  However, if I click ON the icon, it will actually fire 3 times.

**Comment by tagliala** [comment]
> All of the icons just show question marks. What is missing there?

@Grandizer are you a FA-Pro user?

replace `far` with `fas` because only a subset of regular icons is available for Free users

**Comment by Grandizer** [comment]
I am a pro user.  Font Awesome 5 Early Backer #10523. 
I have [updated](https://jsbin.com/dafaqof/edit?html,js,output) the bin and the icons show but the ones with the Lock icon do not fire at all except the last one.

**Comment by robmadole** [comment]
@Grandizer we haven't specifically looked at what Knockout does but I can tell you that you probably should not try to do any binding on the `<i>` tag. Those get replaced with `<svg>` and your results are going to be unpredictable.

Instead do the following:

```
        <span data-bind="click: $root.unlockUser">
          <i class="fas fa-lock-open"></i>
        </span>
```

**Comment by Grandizer** [comment]
That did take care of it.  Good to know about the `<i>` tag being replaced.  Thank you.
