### ISSUE TITLE
Icon request: fa-end-to-end-secure

### ISSUE THREAD

**Issue by kirilmaz** [FortAwesome/Font-Awesome#12135]
An icon for end to end operations might be a good approach

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by kirilmaz** [comment]
![end-to-end-security-governance](https://user-images.githubusercontent.com/16680133/35193100-a179326a-fea6-11e7-8672-689a80f5b638.png)
