### ISSUE TITLE
FA 5 Pro difference in naming font cannot allow switch between css+webfont and svg+js

### ISSUE THREAD

**Issue by yourchoice** [FortAwesome/Font-Awesome#12130]
FA 5 Pro difference in naming font cannot allow switch between css+webfont and svg+js

For example to use it in pseudo for css-webfonts, require:

`font-family: 'Font Awesome 5 Pro'; `  and here is important font-weight: 300 or 900;

To use it in pseudo for svg+js, require:

`font-family: 'Font Awesome 5 Pro Light';`  and here doesn't matter font-weight: 300 or 900; If want filled icon is necessary to set font `font-family: 'Font Awesome 5 Pro Solid';`

Too many names for font-family. On v4 was named simple FontAwsome. It's better to have same  name and in v5.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Pro repository? https://github.com/FortAwesome/Font-Awesome-Pro/issues

**Comment by yourchoice** [comment]
Hi tagliala , your link return 404

**Comment by tagliala** [comment]
@yourchoice if you are a Font Awesome Pro backer, you should have accesso to the Pro repository

If you don't, please connect your github account @ fontawesome.com

https://fontawesome.com/account <-- scroll down to "linked accounts"

**Comment by yourchoice** [comment]
Thank You, 

Now ok

**Comment by Xerotherm1c** [comment]
The proper way to switch between font variations on a pseudo element looks to be using the `font-weight` attribute in conjunction with the `font-family` for Font Awesome.
```
font-family: "Font Awesome 5 Pro"; /* Do not put `Solid`, `Light`, etc. here */
font-weight: 300; /* Switch between versions by adding the appropriate `font-weight` */
```

It would perhaps be more 'readable' to be able to use `font-family: "Font Awesome 5 Pro Light";`, but my understanding is that this would defeat the purpose of keeping the font all together as one font, easily adjustable via the `font-weight` property, which would require each visitor to download _more_ data (if not an additional set of font files for each font variation) for the same font before your website can be fully rendered (which is of course undesirable). Unless there is a clear benefit I'm missing, I don't see why FA would change this.
