### ISSUE TITLE
Icon request: icon-playstation-vita

### ISSUE THREAD

**Issue by vieko** [FortAwesome/Font-Awesome#12138]
Please and thank you! Planning to use it in all our websites and stores.

For your reference: https://en.wikipedia.org/wiki/PlayStation_Vita

**Comment by aethior** [comment]
>Production of the system and physical game cards in the West ended in March 2019, with Sony having no plans for a successor. ([more info](https://en.wikipedia.org/wiki/PlayStation_Vita))

cc/ @tagliala
