### ISSUE TITLE
FA5 NPM Installation?

### ISSUE THREAD

**Issue by Knight-Yoshi** [FortAwesome/Font-Awesome#12136]
I'm a little confused as to installing FA5 via NPM.

The NPM page has this for the installation: `npm i --save @fortawesome/fontawesome`
However, there's no Sass files, SVGs, font files.
It's very empty

<img width="313" alt="screenshot 2018-01-20 11 56 35" src="https://user-images.githubusercontent.com/6134576/35185881-fed89456-fdd8-11e7-831a-e7f95ce794ea.png">

**Comment by TravisJones6** [comment]
I think the `@fortawesome/fontawesome` package is just for the FontAwsome API. You can download the rest of it from the website.

**Comment by Knight-Yoshi** [comment]
That's not a good way to manage dependencies. Font Awesome should be added to NPM :D

**Comment by tagliala** [comment]
Hi,

there are other individual packages.

https://fontawesome.com/how-to-use/use-with-node-js#free

Please let me know if this helps

**Comment by Knight-Yoshi** [comment]
That's actually perfect! Thanks!
