### ISSUE TITLE
Icons v4 to Icons v5

### ISSUE THREAD

**Issue by kiquenet** [FortAwesome/Font-Awesome#12134]
I use several icons in v4.

Now, I want use font-awesome v5.

How can I use it?

icon-chevron-right
icon-phone-sign
icon-envelope

```html
<a href="/Contacto.aspx" target="_self"
class="btn btn-info cabeceraContactoBoton"><i class="icon-chevron-right"></i>Contacto</a>

<a href="tel:91"><i class="icon-phone-sign"></i>+34 91 ...</a><br />
<a href="info.aspx" target="_self"><i class="icon-envelope"></i>Contáctanos</a>
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at https://fontawesome.com/how-to-use/upgrading-from-4

You will need javascript if you don't want to change your code.

PS: 

```html
<i class="icon-phone-sign"></i>
```

This is not FA4. It is supposed to be FA3 and you should manually update all your html classes. In this specific case, `<i class="icon-phone-sign"></i>` ➡️ `<i class="fas fa-phone-square"></i>`

Hope it helps

Closing here
