### ISSUE TITLE
Icon request: angle-triple-up/angle-triple-down/angle-triple-left/angle-triple-right

### ISSUE THREAD

**Issue by NescafeAbusive32** [FortAwesome/Font-Awesome#12139]
Would be really nice to really emphasize whatever is above/below/to the left/to the right.
Based of angle and angle-double.

Preview:
![fa-angle-triple](https://user-images.githubusercontent.com/22991229/35191256-6d94add8-fe44-11e7-9391-ca669a08a7d6.png)

**Comment by PeterShaggyNoble** [comment]
See also #10762

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Let's use #10762, I've changed that request to include all directions
