### ISSUE TITLE
Icon request: icon-facebook-messenger

### ISSUE THREAD

**Issue by dru-ward** [FortAwesome/Font-Awesome#12149]
Hey, 

I would like use this icon as part of a custom share widget.

i.e. fb-messenger://share/?link=http:%2F%2Ffontawesome.io%2Ficons%2F&app_id=XXXXXXXXXXXXXXX

![image](https://user-images.githubusercontent.com/9220450/35243335-667bd9a6-ffb4-11e7-9af9-f57299d8583d.png)

I hope there is no duplicate request for this, I could not find any when searching for "icon-facebok".

Kind regards,
Andrew

**Comment by tagliala** [comment]
Already here: https://fontawesome.com/icons/facebook-messenger?style=brands

**Comment by dru-ward** [comment]
I do apologise, thank you for pointing me in the right direction!

**Comment by tagliala** [comment]
No problem 👍
