### ISSUE TITLE
Icon Request: icon-hammer

### ISSUE THREAD

**Issue by coryasilva** [FortAwesome/Font-Awesome#1214]
This is an important icon in the GIS realm.
Thank you!

**Comment by filthyslider** [comment]
+1

**Comment by akholodenko** [comment]
+1

**Comment by dangnelson** [comment]
+1 for use to represent construction, rather than the wrench which would represent modification

**Comment by G-Driver** [comment]
+1 for hammer

**Comment by coryasilva** [comment]
![Stop!](http://www.flickeringmyth.com/wp-content/uploads/2014/11/soho-mc-hammer1-647x260-600x241.jpeg)

**Comment by G-Driver** [comment]
^_^ hahah you made me laugh ^_^

**Comment by nicomaro** [comment]
+1

**Comment by pengyuanzhao** [comment]
+1

**Comment by julianxhokaxhiu** [comment]
+1

**Comment by JuliaShier** [comment]
+1 please

**Comment by tysonlist** [comment]
+1

**Comment by valioDOTch** [comment]
+1

**Comment by idncom** [comment]
+1

**Comment by onedotsix** [comment]
+1 
Yes, please. Ditto dangnelson, the wrench for modification and hammer for construction. Hammer time...

**Comment by vriera** [comment]
+1

**Comment by jpswade** [comment]
:+1:

**Comment by tomfaller2** [comment]
+1

**Comment by facundomedica** [comment]
+1

**Comment by jbonnier** [comment]
+1

**Comment by vriera** [comment]
Maybe the don't want to add it because it already exist something very similar as a unicode character:

http://www.fileformat.info/info/unicode/char/1f528/index.htm

**Comment by valioDOTch** [comment]
@vriera
Thanks for pointhing this out. I'd disagree with the suggested conclusion however.
This unicode character will not be available on all systems, thus it needs to be loaded through a font.
Naturally I'd expect it to be available via Font Awesome.

i.e. it certainly would make sense that if a hammer icon gets added to FontAwesome, that it would be mapped to this unicode character.

**Comment by robgolbeck** [comment]
+1. I've needed this on a couple of projects now. It would be good if it was available in font awesome (along with other construction related icons) since we're using font awesome for all the other icons on the site anyhow.

**Comment by Dragomir-Ivanov** [comment]
+1. I need it too.

**Comment by mzeyrek** [comment]
+1

**Comment by dhaupin** [comment]
+1

**Comment by jdblundell** [comment]
+1 for a hammer and/or a hammer and wrench together.

**Comment by lifeiscontent** [comment]
+1 any updates on this? It's been a long standing issue.

**Comment by lerenardprudent** [comment]
I thought I would be the one searching for a tool icon!

+1.

**Comment by beefk1rky** [comment]
:+1:

**Comment by bulljustin** [comment]
+1

**Comment by kpingel** [comment]
👍

**Comment by jflats14** [comment]
+1

**Comment by MichaelSamteladze** [comment]
+1

**Comment by valioDOTch** [comment]
Probably adding a +1 on the original post would help

**Comment by Melloyell** [comment]
+1

**Comment by Soulfire86** [comment]
+1

**Comment by gitChang** [comment]
+1

**Comment by ranesr** [comment]
+1

**Comment by rwsansom** [comment]
+1

**Comment by wouter-vdb** [comment]
+1

**Comment by vwaltz** [comment]
please consider giving at least a hammer a high priority.

**Comment by hmundt** [comment]
+1

**Comment by KerryJones** [comment]
+1

**Comment by pRob3** [comment]
+1

**Comment by rqroz** [comment]
+1

**Comment by TroyMurphy** [comment]
+1

**Comment by jdeanwaite** [comment]
+1

**Comment by DERNERSERFT** [comment]
+1

**Comment by Soulfire86** [comment]
Almost 4 Years later...any particular reason this can't happen? There is plenty of people who would love to see this addition.

**Comment by eruminski** [comment]
+1 

Such a basic shape I was surprised to find it wasn't already included.

**Comment by carlosreig** [comment]
+1

**Comment by qool** [comment]
+1

**Comment by suculent** [comment]
+1 hammer makes sense as well as small triangular shovel, but in black-and-white flat the hammer is better. 

Wrench is settings (tuning), not creating.

**Comment by mariusl-a** [comment]
+1

**Comment by jannekeenzo** [comment]
+1

**Comment by tjkohli** [comment]
+1

**Comment by meladawy** [comment]
I was looking for this +1

**Comment by tjkohli** [comment]
+1

**Comment by Sonblind** [comment]
+1

**Comment by challe** [comment]
+1

**Comment by WeeBeasties** [comment]
+1

**Comment by plasmadancom** [comment]
+1

**Comment by tjkohli** [comment]
So it's been over 4 years—I don't think this is happening.

**Comment by suculent** [comment]
Actually, we’re recently made the hammer on our own. It’s available. 

Odesláno z iPhonu

26. 11. 2017 v 20:58, TJ Kohli <notifications@github.com>:

**Comment by tjkohli** [comment]
@suculent Where is it?

**Comment by qool** [comment]
@tjkohli We have generated custom icon font with _Icomoon project_ ... so do it yourself with desired shape or just grab our simple iconfont (with hammer-icon only). Howto included:
[https://rtm.thinx.cloud/public/download/hamer-icon-font.zip](url)

Original shape was based on: https://commons.wikimedia.org/wiki/File:Hammer_-_Noun_project_1306.svg

**Comment by DERNERSERFT** [comment]
It would still be nice if Font Awesome added this. I think the majority of us that really needed the hammer ended up using different icons.

**Comment by tjkohli** [comment]
@qool Thanks, but I already knew that was an option. Unfortunately, I need to use FontAwesome and that's why I'm here in the first place.

@DERNERSERFT Agreed.

**Comment by qool** [comment]
@tjkohli what is the difference? You can embed whole FA lib.

**Comment by myxibrium** [comment]
+1

**Comment by Soulfire86** [comment]
5 years later...no hammer 😢 I've long forgotten what I even need it for the first time I came here, haha.

**Comment by stphnwlkr** [comment]
+1

**Comment by sensibleworld** [comment]
Watch those fingers! https://fontawesome.com/icons/hammer?style=solid

**Comment by coryasilva** [comment]
Can't touch this!
