### ISSUE TITLE
linkedin icon ligature on Desktop

### ISSUE THREAD

**Issue by Pymous** [FortAwesome/Font-Awesome#12147]
Hey,

While doing a little document, I tried to use the Linkedin icon with the Font-Awesome 5 font (version 5.0.4) but the ligature is turning the "link" icon first, ignoring the whole string.

![image](https://user-images.githubusercontent.com/13593371/35228482-243e03a2-ff91-11e7-8e37-c81e8b79166a.png)

**Comment by PeterShaggyNoble** [comment]
It would appear that you're not using the correct font, namely `Font Awesome 5 Brands`.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that @PeterShaggyNoble is right

If that doesn't help, feel free to comment here
