### ISSUE TITLE
Full Weather Icon Set

### ISSUE THREAD

**Issue by michealjroberts** [FortAwesome/Font-Awesome#12142]
Would be awesome if we could have a full weather set - so sunny, cloudy and rain is covered but maybe snowy etc etc :D

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

This use case is also covered in our customization wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
