### ISSUE TITLE
Houseowner, Homeowner icon

### ISSUE THREAD

**Issue by MasterCEASER** [FortAwesome/Font-Awesome#12140]
<svg viewBox="0 0 24 24" style="    height: 22px;">
                        <path fill="currentColor" d="M12,3L2,12H5V20H19V12H22L12,3M12,8.75A2.25,2.25 0 0,1 14.25,11A2.25,2.25 0 0,1 12,13.25A2.25,2.25 0 0,1 9.75,11A2.25,2.25 0 0,1 12,8.75M12,15C13.5,15 16.5,15.75 16.5,17.25V18H7.5V17.25C7.5,15.75 10.5,15 12,15Z"></path>
                    </svg>

how can i include my own svg to work with font-awesome

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you are using the SVG framework, at the moment this is not possible.

If you are using the webfont, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
