### ISSUE TITLE
icon Laravel not showing

### ISSUE THREAD

**Issue by octolit** [FortAwesome/Font-Awesome#12146]
I have tries JS+SVG and Web Fonts - **none** of them shows **_Laravel_** icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate, closing here

SVG: https://jsfiddle.net/tagliala/29n98o6j/1/
Webfont: https://jsfiddle.net/tagliala/cxhgk1zy/1/
