### ISSUE TITLE
Icon Request: fa-hips

### ISSUE THREAD

**Issue by cavebring** [FortAwesome/Font-Awesome#12143]
Hips.com is backing fontawesome 5 via backerkit:

Your Logo in Font Awesome Free and Pro
Qty: 1 x $2,000.00

and should be included
[hips.zip](https://github.com/FortAwesome/Font-Awesome/files/1649847/hips.zip)

**Comment by talbs** [comment]
Hey, @cavebring. Sorry for the confusion with getting your sponsored logo Kickstarter reward into Font Awesome 5. I'll follow-up with you via email to get the next steps rolling around your logo sponsorship. 

Thanks for the reminder and for your patience.
