### ISSUE TITLE
Icon Request: App Usage Tracking or Monitoring

### ISSUE THREAD

**Issue by shivapoudel** [FortAwesome/Font-Awesome#12167]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example? Single color, suitable for 16px icon size

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by shivapoudel** [comment]
Something like this :)
![stats svg](https://user-images.githubusercontent.com/3774827/35605188-2c4c2dc8-066f-11e8-9fe9-5b7cc504e137.png)

**Comment by tagliala** [comment]
I think that one of the following fits your use case:

https://fontawesome.com/icons/chart-line?style=solid
https://fontawesome.com/icons/chart-bar?style=solid
https://fontawesome.com/icons/chart-bar?style=regular
https://fontawesome.com/icons/chart-area?style=solid

**Comment by shivapoudel** [comment]
Okay thanks! I have found the required one on Gridicons by Automattic.
