### ISSUE TITLE
Icon Request: fa-ruler-and-pencil (develop)

### ISSUE THREAD

**Issue by DevSachinGupta** [FortAwesome/Font-Awesome#12166]
![image](https://user-images.githubusercontent.com/12891680/35474167-8aa96b72-03b0-11e8-863f-7811b500bd95.png)
![tools](https://user-images.githubusercontent.com/12891680/35474182-c3875030-03b0-11e8-9cfe-58f0d085105e.png)
![image](https://user-images.githubusercontent.com/12891680/35474206-202a1e9e-03b1-11e8-93eb-a5a78549153f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #736 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by DevSachinGupta** [comment]
sorry to say but i need a little different
please see the images given for the reference

**Comment by tagliala** [comment]
@DevSachinGupta I'm reopening as `fa-ruler-and-pencil`

**Comment by DevSachinGupta** [comment]
what about this


![](https://user-images.githubusercontent.com/12891680/35474206-202a1e9e-03b1-11e8-93eb-a5a78549153f.png)

**Comment by DevSachinGupta** [comment]
thanks

**Comment by tablatronix** [comment]
I suggest draft for pencil ruler. Develop would be something else and more specific.
https://thenounproject.com/search/?q=Draft
