### ISSUE TITLE
Icon request: icon-salesforce

### ISSUE THREAD

**Issue by ali-farag** [FortAwesome/Font-Awesome#12178]
PLEASE & THANK YOU!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1744, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
