### ISSUE TITLE
Add SRI Hash to FontAwesome CDN

### ISSUE THREAD

**Issue by osamak** [FortAwesome/Font-Awesome#12170]
To improve security of FontAwesome CDN users, add the `integrity` attribute to the CDN `<script>` tags in the [Getting Started](https://fontawesome.com/get-started) page and update it with every release.

With the move to the JavaScript framework, this is more critical than ever.  It will be a further proof of the commitment of the project to integrity and user security, and it will promote the use of SRI hashes (which is also promoted by big players such as CDNJS, Bootstrap, and jQuery)

**Comment by robmadole** [comment]
We'll be working on this as part of the effort to launch Pro CDN. Thanks for the note.

**Comment by MrStevenHill** [comment]
This is a really serious issue for anyone currently using the 'SVG with JS' option recommended on the FontAwesome website. I don't think this should be purely part of a 'paid for' service because security affects everyone and the impact could be huge. Please see the following as an example of what can happen when things go wrong: https://www.troyhunt.com/the-javascript-supply-chain-paradox-sri-csp-and-trust-in-third-party-libraries/

**Comment by tagliala** [comment]
> I don't think this should be purely part of a 'paid for' service

I don't think that this will be available only to pro users. I think that Rob means that this feature will be implemented at the same time of the Pro CDN

By the way, I agree in an escalation of this issue

**Comment by robmadole** [comment]
Yeah sorry, I wasn't clear. We are doing the work to include SRI as part of the group of work for our PRO CDN effort. We will include SRI for all of our CDN assets that support it.

**Comment by rimatla** [comment]
That's great news. Looking forward to when it goes live.

**Comment by MrStevenHill** [comment]
Thanks for the clarification and glad to hear this is being treated as priority. Do you have an estimated release date for the update?

**Comment by ejgreenwald** [comment]
By the way for those looking for a quick workaround until this is implemented. You can use https://www.srihash.org/ to generate an sri hash. This would present issues with updates to font awesome though...

**Comment by DarthWound** [comment]
Upvoted previous comment, it's what I use and it works as intended with my strong CSP.

**Comment by robmadole** [comment]
Yep, that site is what we've been using to test and make sure our hashes are correct :)

**Comment by MrStevenHill** [comment]
Superb, thanks ej

**Comment by robmadole** [comment]
Ok everyone. We've deployed SRI hashes now as part of our CDN at fontawesome.com. Give this a go and tell us what you think and if you find any problems (we've checked and double-checked everything but I bet we've missed something).

Thanks for the patience! https://fontawesome.com/get-started

**Comment by osamak** [comment]
Thank you so much, @robmadole!

**Comment by rimatla** [comment]
Thank you @robmadole !

**Comment by robmadole** [comment]
Our pleasure! 😃

**Comment by skeet70** [comment]
Was support for this feature dropped recently? Is there reasoning for it somewhere?

**Comment by robmadole** [comment]
@skeet70 nope, what are you seeing?

**Comment by skeet70** [comment]
Realized we were using a 5 kit and it was dropped for kits (#16691). We'll lock to 5.11.2 until we can make the time to create a custom subset.
