### ISSUE TITLE
#Font awe for Rails 5 

### ISSUE THREAD

**Issue by Frederic-Barcelone** [FortAwesome/Font-Awesome#12171]
Hello, kinldy can you give me the status of rails 5 integration ?  do you have any instruction yet ? 
Thanks 
Frederic

**Comment by tagliala** [comment]
Hi, I'm using `webpacker` + `fa free css` in [this](https://github.com/diowa/ruby2-rails5-bootstrap-heroku) repo:

Relevant files:
https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/package.json#L5
https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/app/javascript/packs/application.scss#L2-L5
https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/config/webpack/environment.js#L5

Note: things may change on that repo, I would probably switch to the SVG framework and overwrite commits

**Comment by tagliala** [comment]
> Note: things may change on that repo, I would probably switch to the SVG framework and overwrite commits

Done that. Webpacker + Font Awesome SVG + Rails 5.2

Closing here
