### ISSUE TITLE
Icon fa-bath and icon fa-shower

### ISSUE THREAD

**Issue by Cachou82** [FortAwesome/Font-Awesome#12177]
Hello,

I have a problem with this two icon (bath and shower) ! when i put for example the <i class="fa fa-shower...." the icon doesn't appear, but it works with two others icons i use.. 

Hope somebody can help me !

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure you are using the latest version of Font Awesome

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Hope it helps, closing here

**Comment by Cachou82** [comment]
Thanks for your answer ! I found that now it’s not  "fa fa-shower"  but « fas fa-shower » but it’s still doesn’t work… !!

**Comment by tagliala** [comment]
@Cachou82 `fa` still works in this specific case.

Sorry but I cannot replicate

CSS: https://jsfiddle.net/tagliala/qq2eLxo1/1/
SVG: https://jsfiddle.net/tagliala/vLae8ted/1/

Please double check your page, browser console, etc.

Troubleshooting guide:  https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
