### ISSUE TITLE
FA 5.0.6 does not insert `data-fa-processed`

### ISSUE THREAD

**Issue by osamak** [FortAwesome/Font-Awesome#12172]
The documentation still states that `data-fa-processed` is automatically inserted, but FontAwesome 5.0.6 does not adhere to this behavior.  This affects CSS styling and JavaScript initialization.  Could this change be explained?

**Comment by tagliala** [comment]
@robmadole could you please check this one?

**Comment by robmadole** [comment]
`data-fa-processed` has been replaced with `data-fa-i2svg`. This attribute has existed as a way for the Font Awesome engine to detect and work with `<svg>` icons that have been processed with `fontawesome.dom.i2svg()`.

It was renamed to make the intent more clear and fix an existing bug. With 5.0.6 icons that are created with `fontawesome.icon` will not contain this attribute (this previously caused an issue with components like react-fontawesome and vue-fontawesome.)

@osamak can you help me understand the use case for why this is affecting your CSS and JS initialization?

**Comment by osamak** [comment]
I am using it the way documented in the [How to use (with jQuery)](https://fontawesome.com/how-to-use/svg-with-js#with-jquery) page.   `data-fa-processed` is used to capture elements created dynamically, as `<i>` elements are being replaced.

Dropping `data-fa-processed` is backward-incompatible and it can break many use cases.  I do not think such a change should be introduced in a minor release, surely not without a prior notice.

This is especially problematical as no CHANGELOG is being released.

**Comment by osamak** [comment]
Just noticed: the examples in the documentation, too, are broken.

**Comment by robmadole** [comment]
Yep, good points. We should have released that more carefully. We'll be posting the changelog to the public repo soon. (They are available on Font-Awesome-Pro only as of right now)

**Comment by osamak** [comment]
Great to hear!  As for the time being, is the next release going to settle for `data-fa-i2svg`?

**Comment by robmadole** [comment]
`data-fa-i2svg` is here to stay. :+1:
