### ISSUE TITLE
fas user* alignment

### ISSUE THREAD

**Issue by dropspace-io** [FortAwesome/Font-Awesome#12174]
![user](https://user-images.githubusercontent.com/35881079/35493414-ea6d278a-0467-11e8-9a73-c709e0f4cbb0.jpg)

Why are all solid user icons (but not regular or light):

fas fa-users
fas fa-user
fas fa-user-times
etc

All have an alignment issue around the neck in that they are not symmetrical - is it a bug that has been carried over from a master template, or a 'feature'?

Thanks!

**Comment by tagliala** [comment]
@davegandy could you please take a look at this?

**Comment by sensibleworld** [comment]
We made a bunch of updates to the user icons earlier this year, so this issue should be fixed! https://fontawesome.com/icons/user-alt?style=solid
