### ISSUE TITLE
CodePoint not working some icon

### ISSUE THREAD

**Issue by Tuguldur215** [FortAwesome/Font-Awesome#12186]
\f06a, \f12a not working pls help me 
`.twitter::before {
    font-family: "Font Awesome 5 Brands"; 
	content: "\f06a";
  }`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`f06a` is https://fontawesome.com/icons/exclamation-circle?style=solid
`f12a` is https://fontawesome.com/icons/exclamation?style=solid

They are not parte of "Font Awesome 5 Brands", you should use "Font Awesome 5 Solid" or "Font Awesome 5 Free" and `font-weight: 900` according to your usage

css: https://jsfiddle.net/tagliala/qq2eLxo1/2/
svg: https://jsfiddle.net/tagliala/vLae8ted/2/

Hope it helps, closing here

**Comment by Tuguldur215** [comment]
Thanks!
