### ISSUE TITLE
Icon Request: icon-teddy-bear (toy)

### ISSUE THREAD

**Issue by sebastienbrochot** [FortAwesome/Font-Awesome#12189]
Hi! It would be really great to have a "Teddy bear" icon or something else referring to the universe of childhood.

Many many thanks!

![3256-200](https://user-images.githubusercontent.com/35958628/35564069-341f4514-05b9-11e8-8d92-1935acbc6460.png)
![5373-200](https://user-images.githubusercontent.com/35958628/35564070-3437f564-05b9-11e8-9dc4-9690f3b77aa2.png)
![72539](https://user-images.githubusercontent.com/35958628/35564071-345221fa-05b9-11e8-8546-9ee2edf1e490.png)

**Comment by linguisten** [comment]
lovely!   +1

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🧸](http://emojipedia.org/teddy-bear/) U+1F9F8 Teddy Bear

**Comment by ivanlori** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/teddy-bear?s=solid
