### ISSUE TITLE
Icon request: fa-sms / fa-comment-rectangular

### ISSUE THREAD

**Issue by ErinPo** [FortAwesome/Font-Awesome#12188]
Perhaps it could be done using [far fa-rectangle-landscape](https://fontawesome.com/icons/rectangle-landscape?style=regular) with ["fa-layers-text"](https://fontawesome.com/how-to-use/svg-with-js/#layering) = SMS, but we would still need the tip at the bottom of the bubble to achieve the commonly used look as part of website share buttons:
[https://cdn4.iconfinder.com/data/icons/chat-icons-3-1/512/smss.png](https://cdn4.iconfinder.com/data/icons/chat-icons-3-1/512/smss.png)

**Comment by aethior** [comment]
Hi @ErinPo,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/message-sms

Regards.

cc/ @tagliala
