### ISSUE TITLE
Icon request: fa-middle-finger

### ISSUE THREAD

**Issue by arajay** [FortAwesome/Font-Awesome#12192]
I can think of multiple use cases for this icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2402 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
