### ISSUE TITLE
Icon Request: fa-bing

### ISSUE THREAD

**Issue by thesilvacesar** [FortAwesome/Font-Awesome#12193]
To most integration of bing search on my project

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2499 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
