### ISSUE TITLE
Icon Request: fa-brave

### ISSUE THREAD

**Issue by Flyer53** [FortAwesome/Font-Awesome#12201]
Would be nice to have a brands icon for the Brave browser
![brave_icon_shadow_300px](https://user-images.githubusercontent.com/6769021/35649132-6464e3ee-06d8-11e8-913f-72f425012cac.png)

**Comment by jonathansampson** [comment]
This would be an awesome addition! (Disclaimer: I work on the Brave team)

**Comment by vikingkarwur** [comment]
Agreed!

**Comment by jeloooooo** [comment]
Let's make it happen!

**Comment by JohnMarsing** [comment]
I vote yes

**Comment by wbmp** [comment]
I just looked into the icon pack just to find out, that a icon for Brave is still missing. So I wanted to request the icon. Then I found, that this is already been requested. So I upvote. Please make it happen!

**Comment by pavansrinivasmamidala** [comment]
I vote yes too..!!

**Comment by UncaughtTypeError** [comment]
Building an application that references browser data, had to reluctantly drop Brave after realising there was no icon available for it. The xml for the actual svg brand icon is too verbose, I was looking for something with a smaller DOM footprint (at author time); an icon would've been ideal.

**Comment by webstermath** [comment]
It would be great to have a fa icon to use with the Brave referral links.

**Comment by frederickalcantara** [comment]
I would like to for a brave fa icon as well. I use brave quite frequently and would like to have the unique fa icon on my tool kit as well.

**Comment by Uriel1339** [comment]
I need brace as an icon for various projects. Please handle this as high priority as we get plenty of complaints by existing users for lack of accessibility / inclusion for brave users.

**Comment by zab-allah** [comment]
I agtlree with the previous comments.  For accessibility reasons a brave fa icon should be added.

**Comment by iplanwebsites** [comment]
+1

**Comment by MentheFraiche** [comment]
Including Brave in the same way as other browsers in Font-Awesome would be good news.
Especially in terms of equity.

**Comment by w0ts0n** [comment]
I also work at Brave, I've emailed fa with our assets, hopefully they see this issue and add it.

**Comment by BitLayZzz** [comment]
I use Brave as my main browser, looking forward to a fa icon for them.

**Comment by AbdulmajedAhmad** [comment]
*Waiting for a fa-brave icon ...*

**Comment by PoseidonCoder** [comment]
I'm using i3 and I'm setting custom icons for my workspace titles. I would really like it if someone made a brave icon.

**Comment by foodornt** [comment]
why is it yet not added, it's been 2 years 😢

**Comment by ottowong** [comment]
This needs to happen!

**Comment by Rmlyy** [comment]
This should be added.

**Comment by zannis** [comment]
Another bump/request for a fa-brave icon!

**Comment by ivancucer** [comment]
Lol what? Almost 4 years?

**Comment by pavanbhat1999** [comment]
# add fa-brave

**Comment by The-Crocop** [comment]
Yep would be great

**Comment by Anthony6444** [comment]
It would be amazing if this got added

**Comment by kzhang2** [comment]
Bumping for visibility. I, as a brave browser user, would love to see its icon included in font awesome.

**Comment by akshayans** [comment]
Bump! Would be great to use for Brave Search (some sort of search engine picker) as well!

**Comment by aguscruiz** [comment]
Would be super cool to have it as part of the set for sure

![image](https://user-images.githubusercontent.com/15734630/224312845-1e62323e-1df6-4e8b-85e3-97679c695833.png)

**Comment by AlanBreck** [comment]
Love it!

**Comment by Timo-Meinhof** [comment]
we need this now!

**Comment by madhur** [comment]
Is there any plan to add this?

**Comment by SimonSwopes** [comment]
Can't wait to see this. I was just looking for this font for my i3blocks icons, glad to see it was already requested!

**Comment by sensibleworld** [comment]
Added! https://fontawesome.com/icons/brave?f=brands&s=solid
