### ISSUE TITLE
layout issue

### ISSUE THREAD

**Issue by devsubhani** [FortAwesome/Font-Awesome#12203]
congratulations for new design but there are some issue in layout please open given link ( http://prntscr.com/i8hwsp ) or
and apply all filters

**Comment by tagliala** [comment]
@talbs 

I'm able to reproduce on Chrome 63 / macOS 10.13

![image](https://user-images.githubusercontent.com/556268/36208409-40bc0cb2-1199-11e8-85ad-a38abe5ca639.png)

**Comment by talbs** [comment]
Roger that, @tagliala. I'll get this on our list to fix. Apologies for the filter overflow in the meantime.

**Comment by talbs** [comment]
This has been resolved and the fix is now live. Thanks for the heads up and helping us make things better, folks. 😄

**Comment by devsubhani** [comment]
Hi Guys,
hopefully you guys are doing well...i have found some more issues in your filter page layout let me make prototype for it then get back to you.

**Comment by devsubhani** [comment]
Hi Guys,
hopefully you guys are doing well...i have found some more issues in your filter page layout let me make prototype for it then get back to you.
