### ISSUE TITLE
fa-euro-sign not found

### ISSUE THREAD

**Issue by EvoWebFrance** [FortAwesome/Font-Awesome#12209]
Hello, in the version 5.0.6, "fa-euro-sign" is not not found, in fontawesome-all.css I have found instead "fa-euro-signo-sign" !!!
I have modified to "fa-euro-sign" and all is ok :-)

Best regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate

https://fontawesome.com/icons/euro-sign?style=solid
https://jsfiddle.net/tagliala/vLae8ted/3/

Closing here
