### ISSUE TITLE
fa-pencil-alt not found

### ISSUE THREAD

**Issue by EvoWebFrance** [FortAwesome/Font-Awesome#12208]
Hello, in the version 5.0.6, "fa-pencil-alt" is not not found, in fontawesome-all.css I have found instead "fa-pencil-alt-alt" !!!
I have modified to "fa-pencil-alt" and all is ok :-)

Best regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate

https://fontawesome.com/icons/pencil-alt?style=solid
https://jsfiddle.net/tagliala/vLae8ted/4/

Closing here

**Comment by EvoWebFrance** [comment]
Sorry I have made a mistake :(

**Comment by tagliala** [comment]
no problem
