### ISSUE TITLE
Can't find the bank icon

### ISSUE THREAD

**Issue by ApoorvTheTecHie** [FortAwesome/Font-Awesome#12204]
I could not find the bank icon. Please Help. <i class="fa fa-bank">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Here it is: https://fontawesome.com/icons/university?style=solid

@robmadole bank and institution were filters for `university`. I can't find them on the new docs, could you please check?

**Comment by ApoorvTheTecHie** [comment]
Thanks a lot, It was really helpful, Cheers.
