### ISSUE TITLE
Problem with fontawesome.com URL parameters

### ISSUE THREAD

**Issue by raniesantos** [FortAwesome/Font-Awesome#12206]
Page is not loaded when I directly specify URL parameters.

For example: https://fontawesome.com/icons?d=gallery&m=free

I just get a blank white page when I enter this in the address bar.

**Comment by raniesantos** [comment]
![f8f801fd-ce6b-4aaa-ac73-3be9d8248321](https://user-images.githubusercontent.com/8528269/35675200-26aa3608-0782-11e8-96f0-df6720a3c3aa.png)

**Comment by tagliala** [comment]
Could you please try to clear the cache and refresh?

**Comment by raniesantos** [comment]
Cache cleared, problem solved.
