### ISSUE TITLE
Icon Request: all about casino

### ISSUE THREAD

**Issue by i-nan** [FortAwesome/Font-Awesome#12205]
request all icon about casino like card, baccarat, Roulette or all gambling icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

If you are a Font Awesome Pro backer, please use the Pro repository to request such a category

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by bitedgecom** [comment]
+1
