### ISSUE TITLE
Add Pro label to Regular style

### ISSUE THREAD

**Issue by xblack21** [FortAwesome/Font-Awesome#12207]
Hi,

please update the style prefix documentation (https://fontawesome.com/how-to-use/svg-with-js#styles-and-prefixes) and add the pro label to `.far` prefix

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry if that brings some confusion.

A lot of `.far` icons are available to Free Users: https://fontawesome.com/icons?d=gallery&s=regular&m=free, so we cannot label that as "PRO". Anyway, I agree that the docs could be improved

@robmadole any thoughts?

**Comment by robmadole** [comment]
Agreed. We'll get this fixed up.

**Comment by xblack21** [comment]
maybe add to every icon page a info if this specific icon is available in the free ```.far``` package

**Comment by tagliala** [comment]
You can find that information on the top (small screens) or on the right side

![image](https://user-images.githubusercontent.com/556268/35859786-b2a9e258-0b41-11e8-9413-4152302b7e53.png)

**Comment by xblack21** [comment]
yes, but only if the icon is available in ```Font Awesome 5 Free```, for some one who do not know that and has read the doc below
![image](https://user-images.githubusercontent.com/11940171/35859964-7c300d28-0b42-11e8-91a1-898788fa659e.png)
can think that he must pay only for the ```.fal``` icon.  The purpose of this issue is to make the doc more user friendly and instinctive

**Comment by tagliala** [comment]
@xblack21 Yes, as I said, I agree that the documentation lacks of information in that paragraph

**Comment by xblack21** [comment]
nice! i don't noticed that you improved it so quickly

now it is rly (font)Awsome!
good job!
