### ISSUE TITLE
Download 404 in Downloads - font-awesome-3d-chess-set-1.0.0.zip

### ISSUE THREAD

**Issue by MarcusMorba** [FortAwesome/Font-Awesome#12213]
This file dl is not working: fontawesome.com ... font-awesome-3d-chess-set-1.0.0.zip

URL: https://fontawesome.com/account/downloads

**Comment by tagliala** [comment]
I can confirm. But this should be reported to FA-Pro repository

**Comment by talbs** [comment]
Sorry about that, @MarcusMorba. Thanks for giving us the heads up. I've just got a fix in and we'll get those files live shortly for you. 😄

**Comment by talbs** [comment]
This download link is now fixed on fontawesome.com. Thanks for bringing it to our attention.
