### ISSUE TITLE
ux issue: icon gallery performance

### ISSUE THREAD

**Issue by jpvillaseca** [FortAwesome/Font-Awesome#12215]
Browsing the [icons gallery](https://fontawesome.com/icons?d=gallery) feels very sluggish.
On Chrome on Ubuntu 17.10, with an i7 CPU, scrolling down the page drops the FPS to 2 multiple times. 
![image](https://user-images.githubusercontent.com/9826460/35687094-9125228a-074c-11e8-89d8-53f7c7ff53c7.png)

Browsing a subset of icons (663 in the solid pack) still goes below 10FPS multiple times.
![image](https://user-images.githubusercontent.com/9826460/35687154-bd8c014a-074c-11e8-8e6a-0a36a8feb8bc.png)

The old site, while showing all the icons, didn't have performance drops. The [new cheatsheet](https://fontawesome.com/cheatsheet) also works flawlessly, going around 40FPS.
![image](https://user-images.githubusercontent.com/9826460/35687482-a02bb98c-074d-11e8-9990-b986b9aac193.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Let's use #12588. I will copy your comment there
