### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by keturiosakys** [FortAwesome/Font-Awesome#12212]
Hi,

My icons are not showing up. I have tried using both font awesome installation methods (local and CDN). The website can be found here: https://coupledialogue.github.io the icons are three on the right side in the navigation bar (once you scroll past the opener).

Here's the source code: https://github.com/CoupleDialogue/coupledialogue.github.io/blob/master/index.html

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

These ones? 
![image](https://user-images.githubusercontent.com/556268/35682235-3d1f3c5c-0760-11e8-8f64-be636b2c4951.png)

**Comment by keturiosakys** [comment]
Huh, weird. It looks like this on my side.

<img width="216" alt="screen shot 2018-02-01 at 15 58 45" src="https://user-images.githubusercontent.com/17225208/35682336-056a1e90-0769-11e8-929b-8622d7f27e40.png">

I think you're seeing the old version of the site with FA4 there.

**Comment by tagliala** [comment]
Nope,

![image](https://user-images.githubusercontent.com/556268/35683026-f0ab6a1e-0762-11e8-9786-120b59bbf481.png)

**Comment by keturiosakys** [comment]
I have tested on three different browsers and two devices and it shows blank icons. The Medium icon in your picture is from version 4.x not 5.x I think.

**Comment by tagliala** [comment]
Please fix your website issues, then I will take another look

If you think there is an issue with Font Awesome, please provide a fiddle showing the issue.

You can start with the following:

SVG: https://jsfiddle.net/tagliala/vLae8ted/
CSS: https://jsfiddle.net/tagliala/qq2eLxo1/
