### ISSUE TITLE
Styles added to i element

### ISSUE THREAD

**Issue by sasoriza** [FortAwesome/Font-Awesome#12226]
Your upgrade guide should mention that all styles added to i elements used for fontawesome will be gone since i elements are replaced with svg. This may add a lot of extra work needed to upgrade.

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by sasoriza** [comment]
Here you go:

https://codepen.io/vit6/pen/wyzLqZ

**Comment by robmadole** [comment]
The `<i>` tag will get replaced with `<svg>`. So your CSS will not apply because the tag is no longer there.

Try

```
svg {
color: red;
}
```

**Comment by sasoriza** [comment]
Quoting myself: Your upgrade guide should mention that all styles added to i elements used for fontawesome will be gone **since i elements are replaced with svg**. This **may add a lot of extra work** needed to upgrade.
