### ISSUE TITLE
FA 4 vs FA5?

### ISSUE THREAD

**Issue by macwizard3** [FortAwesome/Font-Awesome#12220]
I'm using the CDN for FontAwesome, but when I try to use the icon for LinkedIn, I'm getting the wrong one.  I have a Pro license for FA 5.0.

<i class="fab fa-linkedin"></i>  Should be the one in the square. What I'm getting is the same as <i class="fab fa-linkedin-in"></i> which is without the square background.

To get the icon, I have my script tags with my personal embed code, I go back to the site to find the code for the font I want, but I'm not getting the right image: 

![image](https://user-images.githubusercontent.com/18473753/35704988-2392d7c6-076f-11e8-8305-1789d96cbe5c.png)

Also, how do I get rid of the little  _ that's appearing after the LinkedIn and Twitter icons???

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please post a fiddle showing your issue?

As far as I can tell, those are the old 4.7 icons. Please check your html

Take a look at how it should look like in 5.0.6: https://jsfiddle.net/tagliala/qq2eLxo1/4/

**Comment by macwizard3** [comment]
How do I access 5.0 icons?? As far as I know, that’s what I’m accessing, since the code is different (“fab-“ instead of “fa-“)

CZ

**Comment by tagliala** [comment]
@macwizard3 could you please provide a link to your website?

btw here it is the getting started guide: https://fontawesome.com/get-started

**Comment by macwizard3** [comment]
This SHOULD be the correct code for 5.0.6:
https://jsfiddle.net/C_Ztech/u4s620xn/        With THIS code, I get boxes (not icons!). 

IF I change the "fab" to "fa" I get the icons, but not the squared LinkedIn icon.
https://jsfiddle.net/C_Ztech/238qud5s/

Any/all help appreciated!! It was all I could do just to get any real icons to show up. The "get-started" is somewhat helpful, but could be improved (I'm a novice coder, currently in a boot-camp program).

**Comment by tagliala** [comment]
Hi, that is the old code for the font awesome CDN.

you should not use 

```html
<script src="https://use.fontawesome.com/0ef9977aad.js"></script>
```

if you need FA5.

Please take a look at the getting started guide of Font Awesome 5 at https://fontawesome.com/get-started

Hope it helps, closing here
