### ISSUE TITLE
Icon Request - new icons for electrical items

### ISSUE THREAD

**Issue by maniaddanki86** [FortAwesome/Font-Awesome#12224]
Hi Team,

I hope it would be great, if we have electrical home appliances icons like below
fa-fan, fa-cooler, fa-airconditioner, fa-washingmachine, fa-fridge, fa-woven, fa-dryer, fa-stove, fa-radio, fa-musicplayer, fa-socket, fa-charger, fa-light, fa-bedlight, fa-exhaustfan, fa-chimney, fa-gyser and so on

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
