### ISSUE TITLE
cant use sticker-mule icon on wordpress

### ISSUE THREAD

**Issue by 380891277** [FortAwesome/Font-Awesome#12225]
i use vdequator theme.in that theme i cant use a  lot of icons.

**Comment by 380891277** [comment]
i think the version in that theme is too old，what can i do？

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please get in touch with your theme creator and ask him to update font awesome or customize the theme by yourself.

Customizing a wordpress theme is out of the scope of this issue tracker, sorry

Hope it helps

Closing here
