### ISSUE TITLE
Typo mistake on new version of fontawesome 

### ISSUE THREAD

**Issue by hasan-r0ny** [FortAwesome/Font-Awesome#12229]
Hi, I was looking for an icon and got into fontawesome and I saw the new design of the site. 

So, when I copied a fontawesome icon's HTML code, I saw there's a typo mistake in the HTML code. 
There was a "s" with the "fa" word, it is: `<i class="fas fa-download"></i>` instead of `<i class="fa fa-download"></i>`

This mistake seems are in every icon with different words added after "fa".

Is it only me seeing this or everyone?

**Comment by rywn** [comment]
Font Awesome 5.0 deprecates the use of 'fa' in favor of new prefixes as seen here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

If you still need to reference 4.0 you can find it here: https://fontawesome.com/v4.7.0/

**Comment by tagliala** [comment]
thanks @rywn 

Closing here
