### ISSUE TITLE
Where can I find the old list of icons?

### ISSUE THREAD

**Issue by Craft-Lawrence** [FortAwesome/Font-Awesome#12232]
The new list of icons is absolutely not convenient and buggy.
archive.org/web/ for some reason does not have a backup site in its archive.
I really need the old way of searching for icons, or its analogue. Can someone help me?

**Comment by wolfy1339** [comment]
You mean v4? If so, http://fontawesome.io

**Comment by tiagomatosweb** [comment]
This is being redirecting to https://fontawesome.com/. I am also looking for v4 docs

**Comment by tiagomatosweb** [comment]
Actually, just found it.
https://fontawesome.com/v4.7.0/
