### ISSUE TITLE
Missing pull-right in FA5 breaks backward compatibility

### ISSUE THREAD

**Issue by FredFredrickson** [FortAwesome/Font-Awesome#12236]
Even in elements not using an icon, all use of pull-right is completely disabled in bootstrap.

Loaded:
fontawesome.min.js
fa-v4-shims.min.js
Version 5.0.6

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a fiddle/codepen showing the issue?

**Comment by Sobient** [comment]
This is indeed an issue. You'll have to use `fa-pull-right` or `fa-pull-left` for it to work. They seem to override bootstrap's classes, which is horrible.

**Comment by tagliala** [comment]
Could you please provide a fiddle showing the issue?

**Comment by FredFredrickson** [comment]
tagliala- I found the issue!

Bootstrap removed pull-right in Bootstrap 4. My script depended on pull-right. Looks like font-awesome 4 had it's own pull-right definition. I didn't notice upgrading bootstrap 4 because font-awesome took over. Now in Font-awesome 5 you no longer have pull-right, so it's gone from both.

I think the temporary fix is to add this to your v4 shims process:
`.pull-right {
  float: right;
}`

**Comment by tagliala** [comment]
@FredFredrickson thanks!

https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L79

I seen that pull-right and pull-left has been deprecated starting from 4.4.0. By the way, having them in the v4 shims could make sense

let's ask @robmadole his thoughts about this

**Comment by robmadole** [comment]
The shims are for icon names only. This one is easy enough for people to add if they still need it but it really shouldn't be in there at all. It was pretty nasty to have these in there from the beginning.

**Comment by piRGoif** [comment]
Hello,
I did understood you won't modify the v4 shims file, but could you add the removal in [the migration document](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) ? We did follow it and weren't aware of this removal, and discovered it by chance...
Thanks !

**Comment by tagliala** [comment]
@piRGoif thanks for the feedback

I also think that page should contain the information about the removal of the deprecated `pull-*` helpers

@talbs what do you think?

**Comment by thequy** [comment]
Change pull-* to float-* to fix this issue.
I'm using Boostrap 4.5.0, FA 5.15.1
