### ISSUE TITLE
New cheatsheet does not have -o (outline option) anymore?

### ISSUE THREAD

**Issue by ben4d85** [FortAwesome/Font-Awesome#12235]
On https://fontawesome.com/cheatsheet, since the new version, there appears to be no difference between:

+ check-circle with outline
+ check-circle with solid background

These used to be distinguished by adding -o to the name. But now if I copy them from the cheatsheet and paste them into Inkscape, both will give me the exact same symbol.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You should change the font name.

Solid: Font Awesome Solid
Outline: Font Awesome Regular

Ref: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps, closing here

**Comment by ben4d85** [comment]
Hi, how can I access the Old Cheatsheeet, please? I have used this for years without any issues whatsoever (and have even backed the Kickstarter).

I am still using whatever version is included in https://github.com/baruchvlz/angular-font-awesome and I won't be able to update to the new version until that project updates.

**Comment by tagliala** [comment]
@ben4d85 old docs are linked in the homepage

here it is: https://fontawesome.com/v4.7.0/cheatsheet/
