### ISSUE TITLE
DNA Icon

### ISSUE THREAD

**Issue by GenCodeDev** [FortAwesome/Font-Awesome#12237]
Would love to see a double-helix icon in FA!

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1195 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
