### ISSUE TITLE
Icon Request: fa-desktop-network (computer networking)

### ISSUE THREAD

**Issue by iTzEthqnHD** [FortAwesome/Font-Awesome#12246]
Can anyone please add a networking logo? Im thinking something along the lines of this:
![image](https://user-images.githubusercontent.com/36141762/35784380-d25aeb3c-09e4-11e8-8630-7682461853b7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've renamed the issue to what the icon actually represent. 

Please note that the example is too complex for the basic icon size of 16px. Is there something simpler?

Btw, there are other suggestions for networking: #5944, #5555 , #2565  

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by ethanboucon** [comment]
Well if you want it to be simpler, I would like this one:
![image](https://user-images.githubusercontent.com/36141762/35802097-c4d84038-0a3c-11e8-8d18-e43a09749952.png)

**Comment by tagliala** [comment]
@ethanboucon this is already available as sitemap

Solid (Free): https://fontawesome.com/icons/sitemap?style=solid
Regular (PRO): https://fontawesome.com/icons/sitemap?style=regular
