### ISSUE TITLE
FA5 Documentation for NPM seems incorrect

### ISSUE THREAD

**Issue by cshawaus** [FortAwesome/Font-Awesome#12249]
Hi,

I have watched FA5 grow and evolve into the stunning icon library that it now is, but until now I haven't had a chance to use it for any projects (long and boring reasons). That being said, I have noticed that the NPM implementation doesn't work the way the documentation says it should. I have messed around with it for a while now and am pretty sure the implementation has changed without the docs being updated.

So here goes nothing... as per the docs we are expected to use something like the below.

```js
import fontawesome from '@fortawesome/fontawesome'

import {
  faFacebookF,
  faTwitter,
} from '@fortawesome/fontawesome-free-brands'

fontawesome.library.add(faFacebookF)
fontawesome.library.add(faTwitter)
```

This is all good and well but the `add` method only accepts an array of icons which is the implementation I've used below.

```js
import fontawesome from '@fortawesome/fontawesome'

import {
  faFacebookF,
  faTwitter,
} from '@fortawesome/fontawesome-free-brands'

fontawesome.library.add([
  faFacebookF,
  faTwitter,
])
```

My way works perfectly and I'll explain why. Using the documented method yields only one icon for use, from what I've seen while debugging the compiled code any new icon overwrites the last one in an endless cycle which isn't fun.

As mentioned, I've been testing this for quite a while now and am pretty sure it's a simple disconnect between the NPM package and the documentation. For reference, I'm using the below packages which are all up-to-date.

```
"@fortawesome/fontawesome": "^1.1.3"
"@fortawesome/fontawesome-free-brands": "^5.0.6"
"@fortawesome/fontawesome-pro-light": "^5.0.6"
"@fortawesome/fontawesome-pro-regular": "^5.0.6"
"@fortawesome/fontawesome-pro-solid": "^5.0.6"
```

Hopefully, it's just a minor thing as FA5 is beautiful, elegant and extremely simple to integrate.

Thanks for reading 😄.

**Comment by tagliala** [comment]
@robmadole could you please take a look here?

**Comment by robmadole** [comment]
Thanks @cshawaus for submitting this.

Can you please share an example that reproduces the issue you are seeing? I created a quick example using your first code example and I'm not seeing the issue: https://codesandbox.io/s/pmv9wnvvp7.

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by cshawaus** [comment]
OK!

So far further debugging I have found that `fontawesome.library.add` is working as designed. Cool! What I also found is that the Babel build I have running is causing a recursive loop of some kind when `autoReplaceSvg` is enabled.

What happens is the following:

1. Icons are added successfully to the definitions list
2. The automatic replacement functionality begins to run in the background
3. The automatic replacement functionality runs up to 5 times for the same icon even if there's only one definition on the page and sometimes fails to find the icon in the definition list

The last point is the most intriguing as this is code which shouldn't have varying behaviour regardless of the transpiling method used. When it runs through the definitions it will sometimes get a correct icon object and other times it returns the unknown SVG object.

I also set up a project in codesandbox too and it worked which still doesn't tell me why my local build doesn't work correctly.

All that said, I'm doubting this is an issue with my local build script as I've tried getting it set up with both Babel 6&7 but to no avail, the same behaviour applies. I'm at a loss simply because this is the only script misbehaving in the JS source I'm building.

**Comment by cshawaus** [comment]
Hi @robmadole,

After integrating some logs in a local copy of the ES source I finally tracked the issue down and I believe it is a legitimate one. What I found is when the `addPack` hook runs, it automatically calls upon the `autoReplace` function which attempts to inject the SVG into the DOM. The injection functionality is working but what happens is this.

1. The core `fontawesome` library is completely loaded when the page load which means all `<i class="fa<x>"></i>` elements are available for it to find and use
2. I add an icon to the library which runs `autoReplace` again
3. I add another icon, but because the first addition runs `autoReplace`, the DOM element is no longer available for the library to use

I believe this is a basic oversight and that DOM elements without a matching library definition shouldn't be manipulated in any way.

Hope that helps explains the issue in more detail.

**Comment by robmadole** [comment]
Ok, I gotcha. I've confirmed the underlying issue with a test case. We'll get this fix in the queue.

**Comment by tagliala** [comment]
@robmadole is this still an issue?

**Comment by robmadole** [comment]
Pretty sure we’ve got this one fixed. Gonna close.
