### ISSUE TITLE
Icon Request: icon-android-pay

### ISSUE THREAD

**Issue by araskin** [FortAwesome/Font-Awesome#12240]
Hi,

There seems to be an icon for 'Android' and an icon for 'Apple Pay' but there does not seem to be specific icon for Android Pay

Like this: https://www.natwestinternational.com/img-nw/bg/android-pay-mobile-banking.png

**Comment by diegourban** [comment]
+1

**Comment by viniciusferneda** [comment]
+1

**Comment by tagliala** [comment]
Closing here in favour of #12519
