### ISSUE TITLE
Icon request: icon-ciscospark

### ISSUE THREAD

**Issue by levensailor** [FortAwesome/Font-Awesome#12245]
cisco spark has a huge developer community but there are no icons for it yet

use cases: login with cisco spark oauth button, post to cisco spark, sync with cisco spark
I have an immediate need for several applications to use this instead of png images.

![cisco_spark_logo_primary_vertical_cmyk](https://user-images.githubusercontent.com/2538218/35782651-f457797e-09af-11e8-8882-1fd5670de313.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is there any single color version of this logo?

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by tagliala** [comment]
Duplicate of #11441, in any case
