### ISSUE TITLE
CheatSheet

### ISSUE THREAD

**Issue by thefreecat** [FortAwesome/Font-Awesome#1224]
The CheatSheet is only visible from the main page in the "Desktop friendly" section. Having it handy in the menus would help.
Also, it would be nice to add a line explaining how to use Unicode in a CSS :

```
a.checked span:before {
    font-family: FontAwesome;
    font-style: normal;
    content: "\00F046"; /* icon-check */
}
```

**Comment by sensibleworld** [comment]
Closing this issue as it relates to an old version of Font Awesome. Let us know with a new issue if you're still experiencing issues. Thanks!
