### ISSUE TITLE
wrong code for hourglass

### ISSUE THREAD

**Issue by konicsek** [FortAwesome/Font-Awesome#12252]
[https://fontawesome.com/icons/hourglass?style=regular](url) tells content: f254
should be f250

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA5 uses a different approach for solid and outlined icons.

`hourglass` is always `\f254`, but you are required to switch font weight (or font name, if you are using svg) to switch between styles.

Examples:
SVG: https://jsfiddle.net/tagliala/vLae8ted/5/
CSS: https://jsfiddle.net/tagliala/qq2eLxo1/6/

Hope it helps

Closing here
