### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by diegocatalao** [FortAwesome/Font-Awesome#12264]
Is it possible to migrate the new version to bower? Because i found this:
Available versions:
  - 4.7.0
  - 4.6.3
  - 4.6.1
  - 4.6.0
  - 4.5.0
  - 4.4.0
  - 4.3.0
  - 4.2.0
  - 4.1.0
  - 4.0.3
  - 4.0.2
  - 4.0.1
  - 4.0.0
  - 3.2.1
  - 3.2.0
  - 3.1.0
  - 3.0.2

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry. Font Awesome 5 will not support bower. Please consider an alternative.

Official answer: https://github.com/FortAwesome/Font-Awesome/issues/11908#issuecomment-353192558

Post on the bower blog: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Hope it helps

Closing here
