### ISSUE TITLE
Icon Request: fa-plus-circle

### ISSUE THREAD

**Issue by deepak1745** [FortAwesome/Font-Awesome#12265]
The tag for above mentioned icon is wrongly mentioned as ```<i class="far fa-plus-circle"></i>```. Please check

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Is this an issue report?

Is this a request  for a new icon?

**Comment by deepak1745** [comment]
The code should be ```<i class="fa fa-plus-circle"></i>``` instead of ```<i class="far fa-plus-circle"></i>```.  Please check https://fontawesome.com/icons/plus-circle?style=regular

**Comment by tagliala** [comment]
Thanks for the clarification.

Font Awesome 5 works differently from FA5

The `r` in `far` stands for regular. `s` for solid. `fa` is a deprecated alias for "solid".

Also, please notice that `fa-plus-circle` in regular style is not available in Font Awesome Free

Hope it helps

Closing here
