### ISSUE TITLE
share-alt icon not working?

### ISSUE THREAD

**Issue by LG0012** [FortAwesome/Font-Awesome#12263]
Screenshot: http://prntscr.com/iaryjl

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate.

![image](https://user-images.githubusercontent.com/556268/35859507-9dd0d310-0b40-11e8-95a7-50250072288c.png)


Looks related to adblock / content blocking extensions

Please make sure your browser is not using content-blocking extensions that could interfere with Font Awesome.

Hope it helps

closing here

**Comment by LG0012** [comment]
Strange.. http://prntscr.com/iawy97

http://prntscr.com/iawz1e

Its on your website. Im using google chrome.

**Comment by LG0012** [comment]
Another screenshot: http://prntscr.com/iawzxe

**Comment by LG0012** [comment]
Sorry, you right, thats because im using adblock. But again, with 4.* versions everything was right, maybe you could adjust that icon little bit. Many peoples are using this extension, so I think someone have to take closer at this issue. Thanks in advance.

**Comment by tagliala** [comment]
> But again, with 4.* versions everything was right, maybe you could adjust that icon little bit. 

This is a long time issue. We cannot fix that. By the way, it should have been fixed a while ago in Fanboy's list. Also, adblock has some "social media" options that will prevent you to see icons

Ref: #1799, https://help.getadblock.com/support/solutions/articles/6000148708-adblock-blocks-font-awesome-social-media-icons, https://github.com/FortAwesome/Font-Awesome/issues/1799#issuecomment-24030031

If you need to fix this for your customers, please try ligatures: https://jsfiddle.net/tagliala/vLae8ted/6/

**Comment by LG0012** [comment]
Thank you so much! :)
