### ISSUE TITLE
cheatsheet and money-bill-alt

### ISSUE THREAD

**Issue by ChangePlaces** [FortAwesome/Font-Awesome#12266]
this is listed as having two different icons!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

**Comment by ChangePlaces** [comment]
https://fontawesome.com/cheatsheet

there are two `money-bill-alt` which show different icons

**Comment by PeterShaggyNoble** [comment]
You'll notice one's in the solid set and the other in the regular.

**Comment by tagliala** [comment]
Thanks for the clarification

as @PeterShaggyNoble pointed out, one is for solid style and the other one is for regular style

> also, isn't it just money?

The icon represents a money bill, so money bill is quite appropriate as a name

Hope it helps

Closing here
