### ISSUE TITLE
Use Font Awesome in UWP app doesn't work for Brands and Regular icons

### ISSUE THREAD

**Issue by tsjdev-apps** [FortAwesome/Font-Awesome#12262]
I wan't to use Font Awesome in my UWP app project. I've downloaded the `zip` file and copied the three `otf` files to my app project. Now I want to u se them, but only the *solid version* works.

```
<TextBlock Text="&#xf0d5;"
  FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Brands-Regular-400.otf#Font Awesome 5 Brands Regular"
  FontSize="32"
  Foreground="DeepSkyBlue"/>
        
<TextBlock Text="&#xf001;"
  FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free Solid"
  FontSize="32"
  Foreground="DeepSkyBlue"/>

<TextBlock Text="&#xf257;"
  FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Free-Regular-400.otf#Font Awesome 5 Free Regular"
  FontSize="32"
  Foreground="DeepSkyBlue"/>
```
So I can see the music note in the middle, but the other two Icons are displayed as rectangles. Can you explain What I'm doing wrong? Maybe the nameing of the Font is wrong, but I didn't find another nameing of the font.

Thanks for your help.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I can't help.

I'm going to leave this open, maybe someone else knows about UWP

**Comment by tsjdev-apps** [comment]
Tahnks for your answer. After investigating a little bit more into this topic i found the solution.

        <TextBlock Text="&#xf17a;"
                   FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Brands-Regular-400.otf#Font Awesome 5 Brands"
                   FontSize="32"
                   Foreground="DeepSkyBlue"/>
        
        <TextBlock Text="&#xf001;"
                   FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free Solid"
                   FontSize="32"
                   Foreground="DeepSkyBlue"/>

        <TextBlock Text="&#xf257;"
                   FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Free-Regular-400.otf#Font Awesome 5 Free"
                   FontSize="32"
                   Foreground="DeepSkyBlue"/>

The naming of the fonts are wrong and you have to change them.

**Comment by NicolasG3** [comment]
The family name is now _Font Awesome 5 Free_ for both Regular and Solid
`FontFamily="ms-appx:///Assets/Fonts/Font Awesome 5 Free-Solid-900.otf#Font Awesome 5 Free"`
