### ISSUE TITLE
font awesome 4 vs 5 stroke width

### ISSUE THREAD

**Issue by aaronyo** [FortAwesome/Font-Awesome#12269]
I upgraded to font awesome 5 and have noticed that the fonts have a thicker stoke width by default.

It looks like if I want to get many of my icons to look how they looked in font awesome 4, I need to upgrade to pro and use the 'fal' class.

Is that correct? Do the 'fal' icons correspond, more or less, to the v 4.x "-o" icons? Sorry if this was spelled our somewhere and I missed it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA5 uses a default font size of 16px, while FA4 uses 14px icons so they will not look the same and rendering of FA5 at 14px may not look good.

> Is that correct? Do the 'fal' icons correspond, more or less, to the v 4.x "-o" icons?

`far` icons  correspond to outline icons in FA4

Anyway, I cannot confirm:

https://jsfiddle.net/tagliala/yxqqchjs/7/

Hope it helps

Closing here
