### ISSUE TITLE
Map marker code issue

### ISSUE THREAD

**Issue by vishal-headway** [FortAwesome/Font-Awesome#12273]
There is an issue with marker code i.e. **f3c5**. When I use with ::before css, this shows a block, but when I use code **f041** form version 4.7.0, this reflects the marker icon. Please correct the code.
Thanks in advance

**Comment by PeterShaggyNoble** [comment]
`f041` in both FA4 and FA5 is the `map-marker` icon, while `map-marker-alt` was added in FA5 with the codepoint `f3c5`. I suspect you might need to upgrade from FA4 to FA5.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@PeterShaggyNoble's explanation is correct

Hope that helps

Ref: https://fontawesome.com/how-to-use/upgrading-from-4

Closing here
