### ISSUE TITLE
webfonts version

### ISSUE THREAD

**Issue by kukac7** [FortAwesome/Font-Awesome#12274]
why is there a different version of the webfonts?

`versions: [ '0.0.1', '1.0.0', '1.0.1', '1.0.2', '1.0.3' ],`

why not follow the repository?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That's a good question.

**Comment by robmadole** [comment]
We'll get some of the version stuff straightened out soon.
