### ISSUE TITLE
Icon request: "type of bet"

### ISSUE THREAD

**Issue by mduleone** [FortAwesome/Font-Awesome#1228]
I recently wrote an html5 implementation of craps (http://duleone.com/craps/ git: https://github.com/dantothelz/craps/), and I'm using images to represent column headers for a table of bets that are on the table. I really want a standardized set of headings/icons, and ones that make sense for that they're representing.  Below, I list the image I'm currently using followed by the icon name I suggested and description of the icon. There are two headings that I'm not entirely sure what should represent them, and they're listed last.

![id-card_green_small](https://f.cloud.github.com/assets/2913188/615862/8715cf7c-ce4b-11e2-8acd-1e1203ca376b.png)
id-card would represent the bet ID number
![chips_small](https://f.cloud.github.com/assets/2913188/615863/8a5898cc-ce4b-11e2-8fec-bbdc58f96fc1.png)
gambling-chips/bank/money-bag would represent the value the bet is worth
![power_button_black_small](https://f.cloud.github.com/assets/2913188/615864/8e143eee-ce4b-11e2-9766-30445a590c7f.png)
power would represent whether the bet is on or not
![restart_small](https://f.cloud.github.com/assets/2913188/615867/981ee312-ce4b-11e2-8aa1-7364c79a3c5c.png)
repeat would represent whether the bet is supposed to repeat on a win
![edit-clear_small](https://f.cloud.github.com/assets/2913188/615869/9a4325b8-ce4b-11e2-869b-9e173ce0e399.png)
broom (or sweep) would be a broom and represent clearing all clearable bets
![red_x_small](https://f.cloud.github.com/assets/2913188/615870/9c5899d2-ce4b-11e2-88b5-b48206cc24c3.png)
close would be an x or close "button" to remove a specific bet

The other two are:
![shapes_small](https://f.cloud.github.com/assets/2913188/615871/b3d0d976-ce4b-11e2-94e0-bebddd6f7fa3.png)
"type of bet", whether it be a passline bet or field bet, or any other bet on the craps table. I'm currently using shapes to represent this, but I'm sure there's a better option out there
and
![point_small](https://f.cloud.github.com/assets/2913188/615874/dabfb98a-ce4b-11e2-8ed1-4c05253c8169.png)
"bet point", specifically for Come and Don't Come bets that have their own point set on them. Again, I wasn't sure how to represent this, so I browsed the OpenClipartLibrary and decided a dodecagon wasn't a terrible idea

**Comment by aethior** [comment]
Hi @mduleone,

You can use these icons:

`fa-id-card`: https://fontawesome.com/icons/id-card
`fa-coins`: https://fontawesome.com/icons/coins
`fa-power-off`: https://fontawesome.com/icons/power-off
`fa-repeat`: https://fontawesome.com/icons/repeat
`fa-broom`: https://fontawesome.com/icons/broom
`fa-rectangle-xmark`: https://fontawesome.com/icons/rectangle-xmark
`fa-shapes`: https://fontawesome.com/icons/shapes
`fa-certificate`: https://fontawesome.com/icons/certificate

Regards.

**Comment by tagliala** [comment]
Closing here

Feel free to open new requests by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
