### ISSUE TITLE
Add the fontawesome-all.(min.)css file to the npm package

### ISSUE THREAD

**Issue by gcalmettes** [FortAwesome/Font-Awesome#12281]
Hi,
Thanks for the great work on the new version 5!
Any chance the fontawesome-all.css and fontawesome-all.min.css files could also be included in the [@fortawesome/fontawesome-free-webfonts](https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts) npm package?

**Comment by robmadole** [comment]
@gcalmettes if you are using the NPM packages, don't you have a tool that is doing this for you automatically?

**Comment by gcalmettes** [comment]
@robmadole probably ;) I was going with the lazy approach since it was a conditional import and I just wanted to add another instance of [html-webpack-include-assets-plugin](https://www.npmjs.com/package/html-webpack-include-assets-plugin) if people wanted to use CSS instead of the SVG framework, but yes, I can probably directly generate an isolated css from the sass files in the NPM package. Thanks!
