### ISSUE TITLE
Icon Request: fa-shippertag 

### ISSUE THREAD

**Issue by adamebrahem** [FortAwesome/Font-Awesome#12282]
hi, please help adding the icons for the shipping platform shippertag

here it is in all formats:

https://www.shippertag.com/fontawesome.svg
https://www.shippertag.com/fontawesome.png
https://www.shippertag.com/fontawesome.ai

Best Regards

**Comment by aethior** [comment]
`shippertag.com` domain is down.
I can't to find social profiles.

cc/ @tagliala
