### ISSUE TITLE
The fontawesome.io redirect should point to the old docs

### ISSUE THREAD

**Issue by BobVul** [FortAwesome/Font-Awesome#12285]
`fontawesome.io` seems to have been removed and now redirects to the 5.0 docs:

* `fontawesome.io` => `fontawesome.com`
* `fontawesome.io/icons/` => `fontawesome.com/icons/`
* `fontawesome.io/icon/font-awesome/` => `fontawesome.com/icons/font-awesome?style=brands`

However, there are (many) links to specific docs for 4.7 icons. While they now redirect to the 'new' docs, the new docs are actually incorrect for where they are linked from. For example, someone who follows an (old) link to the `font-awesome` icon from a projet that uses 4.7 will be told to use the incorrect new `fab` class instead of the correct `fa`.

It looks like those docs are still available under a subdirectory. Could the redirects point there instead? e.g.:

* `fontawesome.io` => `fontawesome.com/v4.7.0/`
* `fontawesome.io/icons/` => `fontawesome.com/v4.7.0/icons/`
* `fontawesome.io/icon/font-awesome/` => `fontawesome.com/v4.7.0/icon/font-awesome/`

**Comment by StemateF** [comment]
I also think that they should not remove the old docs, there are a lot of projects still using the old version (including mine).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IMHO fontawesome.io should point to the new documentation

Old docs are still available at https://fontawesome.com/v4.7.0/

You can find a link to the old docs in:
- Home page, below the download buttons
- Page footer

Hope it helps

Closing here

**Comment by BobVul** [comment]
Fair enough for the home page, which could be a link to the project as a whole and updating it is valid.

But doing so for the icons page, and especially specific icons, effectively breaks **every** existing link to those pages. Because anyone linking to the icons page or a specific icon of `.io` *must* be expecting 4.7, and none of the 5.0 icon classes will work on 4.7.

This is not beneficial for anyone - old projects now have broken links, and you now likely have people with no clue what's going on getting redirected to a broken icon list. Because, to 4.7 users, the 5.0 icon list is broken. You might be hoping this encourages people to upgrade - but the people visiting these links likely have no control over the version they are using and won't have a clue why it's not working.

We've already updated the links we're aware of in our projects. But I'm concerned about other projects, including at least one large framework, that now have broken links that are not feasible to update yet trivially fixed here by adjusting a redirect.

Sure, leave the home page redirecting to the new one. But, please, at least preserve links to the old content via redirect of the `/icon` path and subpaths.

**Comment by tagliala** [comment]
@BobVul thanks for explaining further.

I'm going to reopen this and wait for some feedback from the Pro team

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [.io redirect fixes](https://trello.com/c/oEhXOj97/35-io-redirect-fixes)

**Comment by My1** [comment]
I certainly agree that deeplinks should stay on the old docs so they wont break but moving around the homepage is fine
