### ISSUE TITLE
Icon Request: fa-iota

### ISSUE THREAD

**Issue by miili** [FortAwesome/Font-Awesome#12297]
Would be great to have an IOTA icon
https://iota.org

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10106, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
