### ISSUE TITLE
Power Transforms not working 

### ISSUE THREAD

**Issue by noopur-dabhi** [FortAwesome/Font-Awesome#12291]
I'm using **Web Fonts with Css** way to use icons in my application. I tried adding `data-fa-transform` attribute in icon, but it is not working.

Here is **[fiddle](https://jsfiddle.net/dt2m49vh/)**

**Comment by Murphy1976** [comment]
I am having the same issue, why was this closed?

**Comment by fatrickp** [comment]
I've got the same issue. There must be a new bug since both @Murphy1976 and I are writing this on the same day within three hours of each other.

**Comment by tagliala** [comment]
Hi, because power transform require the SVG framework

Ref: https://fontawesome.com/how-to-use/svg-with-js#power-transforms

🔒
