### ISSUE TITLE
onCLick event created other 'i' tag with svg

### ISSUE THREAD

**Issue by SerhiiBilyk** [FortAwesome/Font-Awesome#12292]
I'm using FA with React. In develop mode on localhost, icons work properly.
But if mode is production, icons interact on click event (every mouse click on icon create new svg tag).
I have not any onClick events on icons. 

I'm execting that icons will not interact with mouse events.

I'm using fontawesome 5 CDN
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

### Reproducible test case
I can't to insert URL

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information and a reproducible test case?

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by robmadole** [comment]
Yes, as @tagliala mentioned can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by gitdust** [comment]
https://codesandbox.io/s/l3ronx340m

**Comment by robmadole** [comment]
Here's an updated example using our `react-fontawesome` component.

https://codesandbox.io/s/zl1vnppnrl
