### ISSUE TITLE
Mixed up titles on front page

### ISSUE THREAD

**Issue by dekonkwehonwe** [FortAwesome/Font-Awesome#12305]
![image 11](https://user-images.githubusercontent.com/31400131/36028974-e0277b18-0da9-11e8-8172-f8a8fca78aa4.png)

**Comment by tagliala** [comment]
Thanks!

**Comment by talbs** [comment]
Fixed in our doc site's repo and should be out live shortly. 😄

**Comment by talbs** [comment]
This is now fixed on https://fontawesome.com. Thanks for the heads up, all.
