### ISSUE TITLE
Mental Health Icon

### ISSUE THREAD

**Issue by brynhowlett** [FortAwesome/Font-Awesome#12301]
http://serviciosdelaraza.org/wp-content/uploads/2016/01/Mental-Health-Icon-e1452576482162.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8443, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
