### ISSUE TITLE
Icon request: Draw shape/boundary

### ISSUE THREAD

**Issue by BasicSoft** [FortAwesome/Font-Awesome#12302]
It will be helpful for searching in maps some icons like these:

![index](https://user-images.githubusercontent.com/25501553/36023352-73d3d492-0d8c-11e8-8f06-11f8a7d5a9ac.png)
![search_raggio_bn](https://user-images.githubusercontent.com/25501553/36023355-7699d62c-0d8c-11e8-8998-6d45d8fa3543.png)
![search_recinto_bn](https://user-images.githubusercontent.com/25501553/36023358-793937ec-0d8c-11e8-9667-c7376f87392a.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=draw-&c=maps
