### ISSUE TITLE
Shims files do not match

### ISSUE THREAD

**Issue by homocomputeris** [FortAwesome/Font-Awesome#12308]
Hi,
[shims.json](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/shims.json) and [shims.yml](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/shims.yml) do not match.

E.g. they both have 
```
  [
    "bitbucket-square",
    "fab",
    "bitbucket"
  ],
```
```
bitbucket-square:
  name: bitbucket
  prefix: fab
```
but only the 1st has 
```
  [
    "legal",
    null,
    "gavel"
  ],
```

Is it supposed to be like this?

**Comment by robmadole** [comment]
Yes, this is intentional. Those are not 1-for-1 equivalent.

**Comment by homocomputeris** [comment]
What are use cases for both of them, then?

**Comment by robmadole** [comment]
`shims.yml` is the hand-edited file that expresses our intent with renaming. It does not include brand changes "fab" or any of the "-o" renames because these are automated.

`shims.json` is the actual data that drives the output of the shims file include in FA5.
