### ISSUE TITLE
Icon request: icon-checklist

### ISSUE THREAD

**Issue by webbushka** [FortAwesome/Font-Awesome#1230]
It would be very useful to have a checklist icon similar to:

[this](http://cdn3.iconfinder.com/data/icons/files/100/237035-file_document_checklist_todo-128.png) or [this](http://cdn2.iconfinder.com/data/icons/picons-essentials/57/checklist-128.png)

if you went with the clipboard one it could use the same clipboard that you do for #773

**Comment by QueenMerla** [comment]
+1

**Comment by jeffhuys** [comment]
+1

**Comment by pablo-meyer** [comment]
+1

**Comment by nukulb** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-checklist was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by JosMarRivera** [comment]
+1

**Comment by argonautical** [comment]
+1

**Comment by tagliala** [comment]
This is probably a duplicate of #896

I'm going to close this one and add "checklist" to #896's title
