### ISSUE TITLE
Composer package for Version 5

### ISSUE THREAD

**Issue by jkovacsab** [FortAwesome/Font-Awesome#12310]
Is there a PHP composer package available for Version 5 yet?  At the [packagist.org](https://packagist.org/packages/fortawesome/font-awesome) page, it specifies only v4.7.0.  Attempting a composer upgrade for "fortawesome/font-awesome": "5.*" is failing.  Please advise how to upgrade via composer, thanks.

**Comment by robmadole** [comment]
Can the NPM packages be used instead?

**Comment by jkovacsab** [comment]
I have several Bower packages in a PHP composer.json file the format of "bower-asset/[package]", that are loaded via "fxp/composer-asset-plugin".  I'm not sure how to configure NPM packages with composer.

I was able to get it working with the inclusion of:
`    "fxp/composer-asset-plugin": "~1.4.0"`
`    "bower-asset/fontawesome": "5.*"`

This also worked using the PHP composer package:
`    "fortawesome/font-awesome": "5.*",`
along with an additional entry under repositories (which is non-standard):
```
"repositories": [
       {
            "type": "package",
            "package": {
                "name": "fortawesome/font-awesome",
                "version": "5.0.6",
                "source": {
                    "url": "https://github.com/FortAwesome/Font-Awesome.git",
                    "type": "git",
                    "reference": "5.0.6"
                }
            }
        }
    ]
```
I noticed that the tag name format changed from v4.7.0 to 5.0.6, which may be related to why the [Packagist.org](https://packagist.org/packages/fortawesome/font-awesome) record is not updated.  Is there any other manual process needed to update the PHP package in case others have this problem?

**Comment by robmadole** [comment]
Honestly, I'm not sure. We don't have any experience with Composer and I would prefer to find a solution that leveraged the work we've already done for NPM. We have dropped official support for Bower however since the project has been deprecated.

**Comment by razvanphp** [comment]
@jkovacsab you could use:
```
"npm-asset/font-awesome" : "~5.1"
```
@robmadole to be honest, for PHP world, it would be nice to have this in native composer, since it was supported until now, I see it as a bug and not a feature. Maybe we can contribute the fix?

**Comment by WilliamStam** [comment]
add another +1 for the composer way. npm install just wont work in my project :(

**Comment by robmadole** [comment]
@WilliamStam can you explain why `npm` will not work?

**Comment by scottsawyer** [comment]
The lack of composer support has been an ongoing issue in the Drupal community for at least 2 years without a clear resolution: https://www.drupal.org/project/fontawesome/issues/2839928.

In the case of a Drupal project, requiring a separate build process just for Font Awesome is not feasible.  For Drupal modules, JavaScript libraries are loaded from /libraries.  Without a package.json, whenever a new Font Awesome version is released, the old library has to be deleted, the new library has to be manually downloaded, unpacked and dropped in the directory.  It's tedious and easily missed, increasing the likelihood of deploying a broken site ( as I almost did just now ).

A lot of PHP projects are composer based, and as evidenced by the (nearly) 46,000 active installs of the Drupal Font Awesome project ( https://www.drupal.org/project/fontawesome ), I would think offering a simple package.json could make a lot of people's lives easier.

For a great example of a JS library with a package.json, checkout https://github.com/kenwheeler/slick.

Thanks for giving this some consideration, the PHP community thanks you! ( not that I speak for the community :)

**Comment by sekjal** [comment]
I'm also going to weigh in deeply in favor of having Composer support for FA 5.  My IT shop is small, and I can't justify having multiple package managers (with multiple system requirements) just to do "the web".

I'm pretty sure composer.json and package.json from v4.7.0 could be used as very solid starting points for getting FA 5 into Packagist.org.  And while back-tagging the releases for 5.x would be great, we would really only need to start with 5.4.2 or 5.4.3.

**Comment by MrPetovan** [comment]
@robmadole Packagist (the Composer repo) picks up new versions based on tags, and it seems to only recognize tags with the format `v*.*.*` for your project. The last tag with this format was `v4.7.0` so Packagist doesn't provide newer version.

You just need to tag the next release with a `v5.*.*` tag and it will be picked up by Packagist, allowing people to update their version from Composer.

**Comment by derrabus** [comment]
> it seems to only recognize tags with the format `v*.*.*` for your project. 

Sorry, bit this is not true. Packagist recognizes tags with and without the leading `v`. But it ignores tags and branches without a composer.json file in the root directory. That file needs to come back if Packagist should pick up FontAwesome releases again.

**Comment by MrPetovan** [comment]
Indeed, that's why I added "for your project". I overlooked the absence of the composer.json file, nice find.

**Comment by MrPetovan** [comment]
This is what I'm using right now through the `fxp/composer-asset-plugin`, the Composer plugin this special repo is based on.

**Comment by derrabus** [comment]
> is https://asset-packagist.org a good solution to support Composer?

I'd say, it's a valid workaround for using packages in a project packages that don't support composer officially.

But since that solution requires either using an alternative package directory or a specific plugin, it is kinda hard to build composer packages that depend on packages that are only available through asset-packagist.

**Comment by robmadole** [comment]
Ok, all. We are going to rethink this. @mlwilkerson and I will chat about getting better support for Composer and hopefully smooth this out for all. Thanks for your patience and we'll check back in as soon as we can.

**Comment by MrPetovan** [comment]
Thank you for your work!

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Composer support for both Free and Pro repositories](https://trello.com/c/OGv1Q2Pi/416-composer-support-for-both-free-and-pro-repositories)

**Comment by WilliamStam** [comment]
thanks @robmadole  would defs be helpful for us

**Comment by robmadole** [comment]
Alright, we've added `composer.json` to the `master` branch. I've tested this by installing `dev-master` using composer and verifying that it works and that it adds the files to `vendor`.

The next release of Font Awesome will include this file and `5.7.0` should become the first major version 5 installable via composer.

If anyone can give this file a look and also test installation in whatever way is useful and give us feedback that would be great. Thanks everyone for the time and being patient with us.

**Comment by WilliamStam** [comment]
when installing it via composer 

` "fortawesome/font-awesome": "dev-master",`

it downloads 2 directories:
`css` and `js-packages`

both just contain css files 

![annheir 1](https://user-images.githubusercontent.com/182800/51665408-5dd80500-1fc4-11e9-8f34-2ef6fb3ecfb2.png)

there arent any font files included.

**Comment by derrabus** [comment]
@WilliamStam If I install `dev-master` via composer, I find the font files in `vendor/fortawesome/font-awesome/webfonts`.

**Comment by tagliala** [comment]
Hi,

We finally have a composer file: https://github.com/FortAwesome/Font-Awesome/blob/master/composer.json

Does the new Font Awesome 5.7.0 address this issue?

**Comment by tagliala** [comment]
Closing here

Feel free to comment if there are issues

**Comment by scottsawyer** [comment]
Seems to be working for me with 5.7.2.  Thank you for adding this to the project.

**Comment by noahheck** [comment]
I think it's really great that you've added Composer support! As far as I can determine at this time though, there's no way to download anything other than the free version of FontAwesome using Composer. Our work around is to just download the Pro version files and host them ourselves, being sure to keep an eye on releases and managing upgrades on our own (which sucks a little bit, obviously).

I see on your [Support page](https://fontawesome.com/support#license-general), you mention access to a private NPM repository for Pro customers. Composer/Packagist also offer private repository solutions. I have no experience setting them up myself, but thought I'd mention it as an option for you to consider. FontAwesome seems to be quite popular in PHP projects, and being able to manage the Pro version through our package manager might help drive adoption (and sales!).

As I said, I don't have any experience setting up private Composer repositories, but the Composer/Packagist documentation on the subject seems to be fairly comprehensive:

- [Composer - Handling Private Packages](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md)
- [Private Packagist](https://packagist.com/)

Thanks for all your hard work!

**Comment by tagliala** [comment]
Hi @noahheck thanks for your comprehensive feedback

I think you can open a new ticket in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro and copy there your comment

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by noahheck** [comment]
Thanks @tagliala. We'll check it out there.
