### ISSUE TITLE
Could we get a link to older versions of Font Awesome from the main documentation page?

### ISSUE THREAD

**Issue by RustyToms** [FortAwesome/Font-Awesome#12311]
We haven't gone through the upgrade process yet, and I can't get access to old versions through the current Font-Awesome main page. Googling doesn't seem to help much, just points me to the font awesome website, thought I managed to find one link.

It's https://fontawesome.com/v4.7.0/ for anyone else looking.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

1. In the home, below the "download" buttons
2. In the footer

This has also been requested at #12232

@talbs any thoughts?

**Comment by RustyToms** [comment]
Ah, thanks! Maybe I'm not all there today, I couldn't find those links on the page. A link in the header to older versions would be nice. Thanks for the great project!

**Comment by tagliala** [comment]
We have another request opened for this issue.

3 requests may be not statistically significant, but we should check that there we are doing our best to provide links to the old documentation

**Comment by talbs** [comment]
@tagliala, yep! Agreed. We have some thoughts on how to do this and will be helping those folks being directed from fontawesome.io or still using V4 out with some better wayfinding shortly.

**Comment by talbs** [comment]
Hi, folks. Thanks for the heads up, @RustyToms. We've added references to the old 4.7 docs and downloads in several places on fontawesome.com. You can find it on the homepage and in our footer (see screenie below). Let us know if there are any other places or times you were looking for it and couldn't find it (as well as any other feedback).

![v4-references](https://user-images.githubusercontent.com/163763/44409696-e5f74180-a530-11e8-870b-5b0874f18822.png)

Thanks again for the help making our docs better. 😄
