### ISSUE TITLE
Icon Request: Icon-Realtor

### ISSUE THREAD

**Issue by bobbyacker** [FortAwesome/Font-Awesome#12327]
Need an icon for Realtor.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4630, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
