### ISSUE TITLE
Faild to load content in version 5.0.6

### ISSUE THREAD

**Issue by chensMMG** [FortAwesome/Font-Awesome#12325]
I'm having difficulties to use your current version (5.0.6), my current version, for now, is 4.3.0.
I downloaded all files of the new version and load 'fontawesome-all.min.css' in the head of my index.php, from that moment some icons not working.
When I try to add 'content: "\f0e7"' for example to one of the elements in my CSS file the icon fails to load, in the previous version (4.3.0) that didn't happen.

Any ideas why?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that FA5 works differently from FA4 and unicode points could be different.

Take a look at how pseudo element works: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

My guess is that your css is configured with a wrong font name and/or you not using `font-weight: 900`

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

**Comment by LeSomeGuy** [comment]
I had a lot of issues using the Unicodes, the `font-weight` immediately resolved that for me.  Thanks you so much.
