### ISSUE TITLE
Icon Request: fa-zillow

### ISSUE THREAD

**Issue by bobbyacker** [FortAwesome/Font-Awesome#12328]
Need an icon for Zillow.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2623, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
