### ISSUE TITLE
In v5.0.6 tag, which file is the same with https://use.fontawesome.com/releases/v5.0.6/js/all.js

### ISSUE THREAD

**Issue by sufuf3** [FortAwesome/Font-Awesome#12323]
Hi @robmadole, @talbs & FortAwesome team
I'm a member of CDNJS.
I'm going to help update this library on CDNJS.

I referred to your homepage and known that the files which can be used in web front-end are under `web-fonts-with-css` & `svg-with-js`.
Also, I realized that the file `ajax/libs/font-awesome/5.0.6/web-fonts-with-css/css/fontawesome-all.min.css` is the same with https://use.fontawesome.com/releases/v5.0.6/css/all.css via the md5sum tool.
However, I don't know which file in the repository is the same with https://use.fontawesome.com/releases/v5.0.6/js/all.js, even I checked all files which under `web-fonts-with-css` & `svg-with-js` in v5.0.6.

Would you please let me know which file is the same with https://use.fontawesome.com/releases/v5.0.6/js/all.js?

This will be a great work for developers who want to use this lib from CDNJS.
Thank you very much.

cdnjs/cdnjs#12517
cdnjs/cdnjs#12307

**Comment by sagudev** [comment]
add both to cdnjs but recomended is svg-with-js

**Comment by tagliala** [comment]
Hi, there is a [fontawesome-all.min.js](https://github.com/FortAwesome/Font-Awesome/blob/master/svg-with-js/js/fontawesome-all.min.js) but it is not the same file, they have a different checksum.

Let's wait for feedback from the Pro Team

**Comment by sagudev** [comment]
File content is the same, but [all.js](https://use.fontawesome.com/releases/v5.0.6/js/all.js) hasn't got any tabs and spaces.

**Comment by sagudev** [comment]
I made comparison and there are some changes...
![slika](https://user-images.githubusercontent.com/16504129/36074325-e427b05c-0f3e-11e8-9025-444a5d48bf76.png)
The first line is [all.js](https://use.fontawesome.com/releases/v5.0.6/js/all.js) and the second line is [fontawesome-all.min.js](https://github.com/FortAwesome/Font-Awesome/blob/master/svg-with-js/js/fontawesome-all.min.js). There is even more changes.

**Comment by sufuf3** [comment]
@tagliala @robmadole Thank you for helping.
Would you please let me know that should CDNJS host the files under `sprites` and `svgs`? We will get the files from [@fortawesome/fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free).
Thanks

cc cdnjs/cdnjs#12517

**Comment by ScottHelme** [comment]
It'd be great to get an answer on this so we can have FA5 hosted on cdnjs.

**Comment by MattIPv4** [comment]
cc https://github.com/cdnjs/new-website/issues/260

**Comment by robmadole** [comment]
@sufuf3 you can use the files from this repository. Is there a reason why you are asking about the `use.fontawesome.com` CDN?
