### ISSUE TITLE
discord icon never appears

### ISSUE THREAD

**Issue by SwiftShard** [FortAwesome/Font-Awesome#12321]
this is my test code: 
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<i class="fa fa-car"></i>
<i class="fa fa-car" style="font-size:48px;"></i>
<i class="fa fa-car" style="font-size:60px;color:red;"></i>
<i class="fab fa-discord"></i>`

as you can see, the car icons display fine, but the discord icon will not. i got the discord icon from [https://fontawesome.com/icons/discord?style=brands](https://fontawesome.com/icons/discord?style=brands)

what am I doing wrong?

please excuse me if this post is vague or anything, as i am new to GitHub. thanks.

**Comment by da-edra** [comment]
Try adding a CDN for Font Awesome version 5 as fab (font awesome brand) was introduced on this new version.

**Comment by tagliala** [comment]
@da-edra thanks for the answer

**Comment by SwiftShard** [comment]
Thanks, worked perfect!
