### ISSUE TITLE
Icon Request: Fixed Apple Logo

### ISSUE THREAD

**Issue by Omerlan** [FortAwesome/Font-Awesome#12337]
The current Apple logo is a bit distorted and not accurate. The little Apple logo in the Apple Pay icon looks fine, if you could bring over that accurate version of the logo to the apple glyph, I would greatly appreciate it.

**Comment by wolfy1339** [comment]
This seems to be fixed in 5.0.7

**Comment by tagliala** [comment]
Oh yes, it is 👍 

Thanks

https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#changed
