### ISSUE TITLE
Eye not centered in circle or square

### ISSUE THREAD

**Issue by Taygair** [FortAwesome/Font-Awesome#12338]
Hello
Im using Font-Awesome 5.0 and just realized the fa-eye and eye-slash (maybe some more) will not be centered in fa-square or fa-circle while f.e. fa-trash will be centered:

`                <div id="eye-check" class="fa-2x">
                    <span class="fa-layers fa-lg">
                        <i class="far fa-square" data-fa-transform="shrink-1"> </i>
                        <i class="far fa-eye" data-fa-transform="shrink-10"></i>
                    </span>
                </div>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Icons have not the same width by design choice. Please add `fa-fw` class to `<span class="fa-layers fa-lg">`

**Comment by Taygair** [comment]
Ah, that helped, thank you! "fa-lg" was a left over from version 4.5 from which I'm coming. I was able to  remove fa-lg" by replacing it by "fa-lw" eventough I had to resize them all after.
