### ISSUE TITLE
False class 

### ISSUE THREAD

**Issue by Anu2biZ** [FortAwesome/Font-Awesome#12331]
Hi, on web page https://fontawesome.com/icons/edit?style=regular at the bottom of the page
write as "far far-edit"
need "fa fa-edit"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not able to find `far-edit` on that page
![image](https://user-images.githubusercontent.com/556268/36095196-8178d130-0ff1-11e8-8c86-992c7bce4910.png)

BTW, `far fa-edit` is correct. The `r` in `far` stands for regular. 

Please take a look here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes
