### ISSUE TITLE
Weird grey spot after updating to version 5

### ISSUE THREAD

**Issue by topn0tch** [FortAwesome/Font-Awesome#12335]
Hello,
I got this weird bug since I updated to version 5, any ideas?
![schermopname 76](https://user-images.githubusercontent.com/19737717/36111014-085ac540-1025-11e8-927f-f6a5698bce1f.png)

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).
