### ISSUE TITLE
:before attribute not rendering icons

### ISSUE THREAD

**Issue by AndyHaas** [FortAwesome/Font-Awesome#12347]
When I use the before attribute in SCSS the icon is not rendering as it had in version 4. I verify that the codepoint was correct. I am able to use the <i> tag and the icon does show.

Here is a code pen of what I am seeing

https://codepen.io/gunner1714/pen/VQzewa?editors=1100

Thank You
Andy

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that you are using both the SVG Framework (all.js) and the webfont version (all.css) of Font Awesome: they are different projects, and you must pick up just one of them.

If you need to use ::before pseudoelement, you should go for the webfont (as per documentation).

Let's say you want to go for the SVG Framework, you should

1. Remove the loading of the CSS
2. Enable the `searchPseudoElements` option
3. Add `display: none` option to pseudoelement
4. Move all the other css rules to a wrapper element

or

1. Do not use pseudoelements: replace `icon-con` with `fas fa-user`

Ref: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

Hope it helps, closing here

**Comment by AndyHaas** [comment]
@tagliala I have tried this and it works on some but not on others. Like below

`    font-family: "Font Awesome 5 Free";
    content: "\f058";`

Are we limited to which icons we can do when we are using the free version of font awesome and it will always choose the regular instead of which one is available?

**Comment by tagliala** [comment]
> ```font-family: "Font Awesome 5 Free"; content: "\f058";```

Nope, you should use ```font-family: "Font Awesome 5 Solid"; content: "\f058";``` or ```font-family: "Font Awesome 5 Regular"; content: "\f058";``` on the free version too

Ref: https://jsfiddle.net/tagliala/vLae8ted/5/

**Comment by AndyHaas** [comment]
@tagliala I did get that to work. Thanks for your notes.

**Comment by tagliala** [comment]
you're welcome
