### ISSUE TITLE
Brand icons not displayed (no adblock)

### ISSUE THREAD

**Issue by aureliendebord** [FortAwesome/Font-Awesome#12343]
Hello,
First of all, I hope this is not a duplicate:
Brand icons like Facebook or Trip Advisor are not showing.
I have seen AdBlock can cause problem, but I dot not have this installed on my browser.

Instead of the brand icon, I have got a circle with an exclamation/question mark animation...
No problem for others icon, so I assume the script is correctly loading.

<img width="139" alt="fa" src="https://user-images.githubusercontent.com/10230951/36145519-e9fe561a-10b1-11e8-9033-abfbcc2ca84f.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide all the required information and a reduced test case?

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by aureliendebord** [comment]
### Describe the problem

Using Font Awesome on a WordPress theme. Some icons are displayed, others not.

### What did you expect?

All icons must be displayed

### What version and implementation are you using?

Version: 4.6.1
Browser and version: Chrome 64.0
- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

See the footer: http://stei.debord.eu/
One of icon is not showing

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks.

Please note that you are loading both 4.6.1 and 5.0.6

```html
<!-- ... -->
<link rel="stylesheet" id="font-awesome-css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css?ver=4.9.4" type="text/css" media="all">
<!-- ... -->
<script defer="" src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
```

Please use only one version. I would remove the old 4.6.1

Also

```html
<i class="fas fa-facebook-square"></i>
```

Should be `fab`: `s` stands for solid, `b` for brands

Refs:
- https://fontawesome.com/how-to-use/upgrading-from-4#v4-shim
- https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes
- https://fontawesome.com/icons/facebook-square?style=brands

Hope it helps, closing here

**Comment by davidbuckleyni** [comment]
Thanks this helped me also I required to Use fab to access the brand icons
