### ISSUE TITLE
Cannot install via. yarn

### ISSUE THREAD

**Issue by Gmunker** [FortAwesome/Font-Awesome#12349]
```
$ yarn add @fortawesome/fontawesome
yarn add v1.3.2
warning ..\..\package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/fontawesome: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Owner\\desktop\\recipebox\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
```
$ yarn add @fortawesome/react-fontawesome
yarn add v1.3.2
warning ..\..\package.json: No license field
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/react-fontawesome: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Owner\\desktop\\reci
pebox\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I thought maybe I had space or something wrong somewhere, but i'm copy pasting from both the api docs, and from https://yarnpkg.com/en/package/@fortawesome/fontawesome.

**Comment by Gmunker** [comment]
Although i was able to install
`"dependencies": {
		"@fortawesome/fontawesome-free-solid": "^5.0.6",
`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate at the moment but I'm leaving this open because I cannot help

```
$ yarn add @fortawesome/fontawesome
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ @fortawesome/fontawesome-common-types@0.1.2
└─ @fortawesome/fontawesome@1.1.3
✨  Done in 8.14s.
```

**Comment by wgmv** [comment]
Getting the same error

```yarn add v1.3.2
[1/4] Resolving packages...
error Couldn't find package "@fortawesome/fontawesome" on the "npm" registry.```

I have an .npmrc file in the same dir as package.json with
`@fortawesome:registry=https://npm.fontawesome.com/XXXX-XXXX-XXXX-XXXX-XXXX`

**Comment by wgmv** [comment]
Just found the solution rather by accident because I checked the docs while beeing logged in:

the token for npm is under Profile/Linked Accounts (for me this location is not obvious) 
When not logged in the documentation under https://fontawesome.com/how-to-use/use-with-node-js just states "The TOKEN can be found in your Font Awesome account settings" and just links to the account - it should link to https://fontawesome.com/account/linked-accounts

When logged in the token is directly show in the docs which is good.

**Comment by wgmv** [comment]
@Gmunker maybe you also need to add the token as I see 

`warning ..\..\package.json: No license field`

in your output

**Comment by tagliala** [comment]
@wgmv the warning should be relative to a missing `license:` property in `package.json`

**Comment by Gmunker** [comment]
hmm ok, well I thought i had an account apprently not, and no funds to buy a license. I thought I could use the free ones with no problem, guess i'm wrong. I'll look back into this when i'm able to afford it, so i cannot confirm it fixes on my end at this time. Thanks for the responses!

**Comment by tagliala** [comment]
@Gmunker you don't need a pro license to use FA5 free with yarn

**Comment by Gmunker** [comment]
Thats what I thought, so i'm not sure what i'm doing wrong then. :/

**Comment by Gmunker** [comment]
So I did a `yarn cache clean` and then was able to install. Something must have been conflicting. Thanks for all your responses and help!

**Comment by tagliala** [comment]
@Gmunker glad you've solved.

I'm also sorry, because I known about that options but I didn't advise you to do that because I thought you already tried that.

**Comment by belackriv** [comment]
Adding to mention that @wgmv had the correct solution for me.  Make sure you are using the token from linked accounts.

**Comment by Hackbyrd** [comment]
It is confusing, you are using the wrong token. The token is under the "Services" tab and then under the "Tokens & Access Abroad" section. I ran into the same issue by using the token in the "Licenese" tab but that IS NOT THE CORRECT TOKEN!
