### ISSUE TITLE
Missing icons on webfont/regular @ fontawesome-free-5.0.6

### ISSUE THREAD

**Issue by carlosjln** [FortAwesome/Font-Awesome#12342]
Font regular not rendering properly with released files contained in fontawesome-free-5.0.6.zip
`<i class="fas fa-users"></i> (renders solid icon properly)`
`<i class="far fa-users"></i> (does not render)`

I replaced the directory "fontawesome-free-5.0.6\web-fonts-with-css\webfonts" with "fontawesome-pro-5.0.6\web-fonts-with-css\webfonts" and it displays properly. So the content of the free version differs from the pro version.

**Comment by PeterShaggyNoble** [comment]
You've already answered your own question; only the solid `users` icon is included in FA5 Free.

**Comment by carlosjln** [comment]
@PeterShaggyNoble Thanks for the update, I had [this tab](https://fontawesome.com/how-to-use/web-fonts-with-css) opened for a few days, I've just refreshed it and Regular is marked with Pro tag (before it wasn't, hence my question).
