### ISSUE TITLE
Bug: Icon remains in DOM after class changed

### ISSUE THREAD

**Issue by JohnDibling** [FortAwesome/Font-Awesome#12340]
I am writing an Angular 5 application with a hamburger menu in the top nav. The intention is to display 'fa-bars' when the menu is closed, and 'fa-times' when the menu is open in order to provide some feedback to the user.

The menu's open/closed state is reflected by a boolean variable in my control: isCollapsed. The variable is true when the menu is closed and false when the menu is open.

The template is defined as follows:

```
  <button class="navbar-toggler navbar-toggler-right float-right" type="button" (click)="isCollapsed = !isCollapsed">
    <ng-container *ngIf="isCollapsed"><i class="fal fa-bars"></i></ng-container>
    <ng-container *ngIf="!isCollapsed"><i class="fal fa-times"></i></ng-container>
  </button>
```

However because FA5's js library is simply replacing the <i> tag with an <svg> tag in the DOM, every time I open or close the menu an additional representation of the icon appears. Clicking it several times, it looks like this:

===XXX

Is there a way to control which icon is displayed dynamically, or is an icon forever in the DOM once it is put there the first time?

Epilogue:  I was able to get the functionality I wanted by using SCSS and webfonts, rather than JS and SVGs. However this isn't how I would prefer to use FA5. So I have a workaround, but a proper fix is highly desired.

**Comment by carlosjln** [comment]
Hi, @JohnDibling,

It seems that what you need is to use the ngClass directive to swap classes on the single icon tag instead of having two of them.

[https://docs.angularjs.org/api/ng/directive/ngClass](url)

**Comment by JohnDibling** [comment]
I've tried that, Carlos. That isn't the problem.

Sent from my handheld.

**Comment by robmadole** [comment]
@JohnDibling can you give our pre-release of the Angular component a try? https://github.com/FortAwesome/angular-fontawesome

**Comment by ronaldosjr** [comment]
I was having the same problem, solved removing the cdn js and replacing it by the css cdn.

**Comment by edworczak** [comment]
I have the same problem in Angularjs with ng-if, but also ng-class with condidtion. The icon should change to another if the condition is fullfilled, but it does only after refreshing the page. I suppose that switching to css version would solve the problem, but I would like to use svg.

**Comment by robmadole** [comment]
Please check out https://github.com/FortAwesome/angular-fontawesome. We developed this component specifically for the Angular community to use SVG.

**Comment by edworczak** [comment]
Thank you! I've tried ealier to go to link in your comment above, but something was wrong and there was 404. Now it's working.

**Comment by JohnDibling** [comment]
I can give it a try, @robmadole, but since this is pre-release I'm not going to be able to use it in production. Until it goes in to production, I'll have to use my SCSS hack.
