### ISSUE TITLE
problem with css

### ISSUE THREAD

**Issue by viral16d** [FortAwesome/Font-Awesome#12354]
when i am use this font with "content" property
eq:
content: '\f10d';
                    font: {
                        family: 'fontawesome';
                        size: 25px;
                    };

at that time font will not work on webpage,
so i request you give me proper guide to use it

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA5 comes with SVG and Webfont version, and they have a different approach for pseudo elements. Your style is not correct ("fontawesome" is wrong), but there is more.

Please take a look at:
- https://github.com/FortAwesome/Font-Awesome/issues/12347#issuecomment-365351586
- https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements (if you are using SVG)
- https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements (if you are using webfonts)

I'm going to close here

Please make sure that your request follows our [bug report request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
