### ISSUE TITLE
Icon request: icon-storify

### ISSUE THREAD

**Issue by erikwiffin** [FortAwesome/Font-Awesome#1235]
I would love to have a [storify](https://storify.com/) icon.

**Comment by sebhildebrandt** [comment]
+1

**Comment by Nancarrow** [comment]
would be great to have a Storify icon!

**Comment by andrewmallis** [comment]
+1

**Comment by daloev71** [comment]
+1

**Comment by dnicinski** [comment]
Any luck with the Storify icon? We could really use it too. 

![storify](https://cloud.githubusercontent.com/assets/13800933/10252341/df160f92-6904-11e5-8880-77499138f8d1.png)

**Comment by jhume** [comment]
+1

**Comment by kirstenkeister** [comment]
+1

**Comment by acezard** [comment]
+1

**Comment by kirstenkeister** [comment]
+1

**Comment by cbracco** [comment]
This icon is the only one we are missing for our use case over at Muck Rack ... will make our implementation a lot cleaner if it gets added! :crossed_fingers:

**Comment by aethior** [comment]
>Storify was launched in September 2010, and had been open to the public since April 2011. Storify was shut down on May 16, 2018. ([more info](https://en.wikipedia.org/wiki/Storify))

cc/ @tagliala
