### ISSUE TITLE
Icon change request: old smiley faces

### ISSUE THREAD

**Issue by tailoredanthony** [FortAwesome/Font-Awesome#12351]
Hello awesome people!

New version is great, but I was surprised when I came to use the smiley faces.  The new ones seem to be rolling their eyes.  I've just had a client complain and request something different, which is a shame.

Any chance we can get these wonderful simple smilies from version 4 back again?

![smiley-comparison](https://user-images.githubusercontent.com/26805957/36184284-7d0eb9fa-117e-11e8-8d38-17127246a8de.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I like the "3D" effect on `poo`'s eyes, but I personally agree with you on smiles.

**Comment by sensibleworld** [comment]
Sorry for missing this thread! We made updates to the smiley icons, and added a whole batch of new versions here: https://fontawesome.com/icons?d=gallery&c=emoji
