### ISSUE TITLE
fortawesome/fontawesome-pro-webfonts

### ISSUE THREAD

**Issue by 0dp** [FortAwesome/Font-Awesome#12368]
Hi there,

I am trying to figure out how to get the pro webfonts with scss files via npm.
The free pack is called `fortawesome/fontawesome-free-webfonts` but what about the pro pack?

Thanks in advance

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can install FA Pro via NPM by using your token: https://fontawesome.com/how-to-use/use-with-node-js#pro

If this doesn't help, I should ask you to open this issue in the Pro repository available at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the Pro repository, please make sure you have linked your github account to your fontawesome.com account.

I'm going to close here but feel free to keep commenting if you have any troubles

**Comment by tagliala** [comment]
@0dp you could also take a look at https://github.com/FortAwesome/Font-Awesome-Pro/issues/850#issuecomment-350105122

**Comment by 0dp** [comment]
@tagliala, that package does not exist!

Available packages can be seen here: https://www.npmjs.com/search?q=scope:fortawesome&page=1&ranking=optimal

**Comment by 0dp** [comment]
thanks!
