### ISSUE TITLE
Installing Pro Edition with npm

### ISSUE THREAD

**Issue by danieldugger** [FortAwesome/Font-Awesome#12367]
I was curious as to whether or not you had instructions that would allow me to install the Pro edition using NPM.

Having reviewed a couple of third party sites, it appears that I can use your product with Ionic. With that being said, I would like to use an installer so that I can ensure everything is installed correctly.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can install FA Pro via NPM by using your token: https://fontawesome.com/how-to-use/use-with-node-js#pro

If this doesn't help, I should ask you to open this issue in the Pro repository available at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the Pro repository, please make sure you have linked your github account to your fontawesome.com account.

I'm going to close here but feel free to keep commenting if you have any troubles
