### ISSUE TITLE
Linkedin icon not working on Desktop

### ISSUE THREAD

**Issue by eladnova** [FortAwesome/Font-Awesome#12363]
On a desktop, when trying to use the LinkedIn icon by typing **linkedin-in** you get the standard link icon first. IE the link icons appears followed by the remaining string.

![image](https://user-images.githubusercontent.com/1786476/36256093-5c3f62c6-1249-11e8-93a0-1d562e674858.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure you are using "Font Awesome 5 Free Brands" font. As far as I can tell, you are using Font Awesome 5 Regular"

Hope it helps

Closing here
