### ISSUE TITLE
Icon Request: fa-GoLang

### ISSUE THREAD

**Issue by HiepTLe** [FortAwesome/Font-Awesome#12371]
The one with the cute gopher

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9431 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
