### ISSUE TITLE
Icon request: globe / Earth

### ISSUE THREAD

**Issue by EmilePerron** [FortAwesome/Font-Awesome#12370]
The old version of the **globe** icon was really useful and seems to have disappeared when moving the Font Awesome 5. Would it be possible to get it back? Maybe as fa-earth, fa-planet or something like that.

Image: 
[https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Globe_font_awesome.svg/2000px-Globe_font_awesome.svg.png](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Globe_font_awesome.svg/2000px-Globe_font_awesome.svg.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, they will probably come back in three variants to cover all continents

For FA5, we preferred a more generic "global" icon

Please 👍  and ref to: #281 

Closing here
