### ISSUE TITLE
Styling JS/SVG icon as :before

### ISSUE THREAD

**Issue by janstieler** [FortAwesome/Font-Awesome#12374]
Hi,
if I use the icons through JS/SVG and with css :before.
I use this style for my before icon:
```
:before {
     display: none;
     font-family: "Font Awesome 5 Solid";
     content: "\f10e";
     margin-right: 8px;
}
```
The replaced SVG ignores the margin. Have I to style the SVG seperatly and if yes how can I style it if I have the same icon multiple times used?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I didn't fully get your request, but I think you need to enable the `searchPseudoElements` option.

Please take a look at the documentation here: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

Please also take a look at this example: https://jsfiddle.net/tagliala/vLae8ted/5/

Anyway, using pseudo elements with the SVG framework is not recommended, as you can see in the docs.

Hope it helps

Closing here

**Comment by janstieler** [comment]
Hi,
thanks for your fast reply!
I have the `searchPseudoElements` option enabled.

I don't want to change the integration of fontawesome only for two icons and i have no problems with performance or something similar.
I see I have to set the SVG if I want to change some attributes it doesn't work if I have to set it to the pseudoelement.

Thanks.

**Comment by tagliala** [comment]
Hi,

I don't know if that solved your issue or it didn't.

> I don't want to change the integration of fontawesome only for two icons and i have no problems with performance or something similar.

Please provide a reproducible test case if you need further help

Take a look at our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md))
