### ISSUE TITLE
Icon Request: fa-brain

### ISSUE THREAD

**Issue by mehooman** [FortAwesome/Font-Awesome#12379]
brain, thinking, imagining...
Thanks :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
