### ISSUE TITLE
Icon request: blanket

### ISSUE THREAD

**Issue by cazgp** [FortAwesome/Font-Awesome#12383]
### What can it be used for?

I'm rebuilding the CRM for a homeless shelter and we give out various items and need to record those. Rather than a list of text, it would be good to use icons.

It seems that a missing section of font-awesome is clothing. However there are already open issues for the ones we need. It seems as if "blanket", however, has not yet been registered.

### Example image (optional)

![image](https://user-images.githubusercontent.com/658873/36351010-79e34d6c-149a-11e8-9d3c-a8b169510753.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/blanket?style=solid
