### ISSUE TITLE
Unable to drag with KendoUIs sortable widget

### ISSUE THREAD

**Issue by Taygair** [FortAwesome/Font-Awesome#12381]
I'm switching from Font Awesome 4.5 to 5.0 (SVG with Javascript).
It took me a while to find this: I have some DIVs in vertical placed order. All those have a little DIV in it with a drag symbol (fa-sort) to show the user he can sort all vertical placed DIVs. The drag functionality (Kendo UI widget) does not work if the user clicks the mouse button while the mouse pointer is placed on the fa-sort icon. It works only if the user hits the DIV area around the fa-sort icon (see attachment). I don't know how to fix this. It looks like the icon blocks to call the drag operation. I have implemented it that way: 

`<div class="fas fa-sort fa-2x dragdiv"></div>`  (dragdiv class is the one supporting drag operations)

Previously I have used Font Awesome as CSS class and this was never an issue. Now, with "SVG with Javascript" I came up to this problem. This is no issue on clicking (buttons) on a font awesome icon, just dragging it. 

Maybe this is also a problem with other Javascript frameworks supporting drag operations. I just have found this with Kendo UI (Safari, Chrome, FF). Whats your recommendation how to implement Font Awesome icons so the drag operation is not ignored while click/drag ON a font awesome icon?
![drag](https://user-images.githubusercontent.com/21134000/36341249-b3695112-13eb-11e8-9dcf-5e13bbc380c2.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that if you have this need, you can keep using the webfont version of font awesome 5.

Since there are several libraries involved in your use case, you should provide a reduced test case which shows the issue, so we can help in debugging

Please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by Taygair** [comment]
Hi thanks for the quick answer!
It took me days (and I'm still not finished) to switch from Font Awesome 4.5 to 5. I have to change every single FA element that is involved. I have used the Javascript version of it since it was "recommended". Now you are telling me I shall head back to the CSS styles version. I initially added the FA CSS styles as it is described. Then I realized it wont work together with the JS version so I removed the include of the fontawesome-all.js to realize: All FA elements I have changed so far is screwed up! Oh no, I don't do the work again I did now for days! I have still checked the Webfonts CSS style related to my problem and it would work. But I will not used it for the price to now change all the stuff for days again.
As soon as I find time I will create a test sample you provided. All not very satisfying....

**Comment by tagliala** [comment]
Hi,

Sorry about that.

Please provide a reduced test case so we can investigate if this has something to do with the SVG Framework

**Comment by Taygair** [comment]
Done: https://github.com/FortAwesome/Font-Awesome/issues/12386

**Comment by tagliala** [comment]
Closing here
