### ISSUE TITLE
FA reflect issue while page loading...

### ISSUE THREAD

**Issue by smallersign** [FortAwesome/Font-Awesome#12385]
Hi FA team,

I got FA pro, but as I can see caching issue while every page loading the font reflecting.
Cache is more important for the web for faster loading. 
- Need guide which is the proper way to make cache the js file.
- I have found that you recommended to as CSS '<html class="fontawesome-i2svg-pending">" with Body Display: none method.... https://fontawesome.com/how-to-use/performance-and-security

Does it affect SEO with your recommended method or you recommend another method for cache or how to prevent the font refraction in a proper way?

Your response will be highly appreciated.

**Comment by smallersign** [comment]
Any answer we may expect for this question?

**Comment by tagliala** [comment]
@smallersign sorry but I don't know the answer and I didn't fully get the question.

Do you mean there is a FOUC issue?

I'm leaving this open for feedback from the community or someone else in the team.

**Comment by smallersign** [comment]
I mean each time icon loading after page load.

**Comment by robmadole** [comment]
@smallersign it's not a caching issue but as @tagliala mentioned it's similar to FOUC (or missing content in this case).

The documentation you referenced is the way to handle this.

**Comment by smallersign** [comment]
There is nothing missing, I think you won't understand. I will make a video.

**Comment by tagliala** [comment]
@smallersign yes, thanks. Please provide a reproducible test case or a screencast and I will take a look

**Comment by smallersign** [comment]
Hi, I just made a video and check there are the fonts reloaded every time when page reload or new page open. It's totally feeling boring due to the svg with js not caching. Let me know if there any solution.
https://www.youtube.com/watch?v=UH4zovyQhUg

**Comment by smallersign** [comment]
Does anyone review this?

**Comment by robmadole** [comment]
@smallersign ok, that video helped a lot. It looks like you are using pseudo-elements with SVG + JS. That is a side effect of how we are currently making that feature work.

I would recommend that you use web fonts with CSS if you are going to use pseudo-elements. https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

**Comment by smallersign** [comment]
I know that the CSS method will cache. But, I really loved your FA SVG with JS that totally raw functioning without fonts that's why bought pro. But we require the proper caching for the SVG with JS because fonts loading every time while page loading. 

I had applied and test for approx 1 month as Asynchronous Loading method. My site goes SEO down. Maybe its impact on SEO due to SEO robots cannot read body content because body CSS property none until fonts loaded. https://fontawesome.com/how-to-use/performance-and-security#async-loading-indicators

I Hope you understand my concern.

**Comment by robmadole** [comment]
Your best option is to avoid pseudo-elements with SVG with JS. If you can do this (and just use normal `<i class="fas fa-[icon]"></i>` style elements it will work much better for you.

**Comment by smallersign** [comment]
You mean you recommending to use Wesbfornts with CSS? Currently i am using SVG with JS & <i class="fas fa-user"></i> this format.

**Comment by robmadole** [comment]
Are you using pseudo-elements? The `::before` or `::after` CSS features?

**Comment by smallersign** [comment]
Nop, because I am using SVG with JS. I am looking solution for SVG with JS.

**Comment by robmadole** [comment]
Ok. What stack are you using? Why is your navigation reloading when you move to different pages? Are you using PJAX or Turbolinks? Tell me a little about why you need to re-render the page every time. Is this an SPA? Rails? Also if you are using the async loading optimizations are you hiding your entire `<body>` instead of just the nav?

You might also consider using Symbols. If you can get those icons rendered once in an area of your page that is not getting replaced you could use the sprite technique to improve rendering on the second transition on. https://fontawesome.com/how-to-use/performance-and-security#symbols-using-svg-sprites.

I'll re-open this as we work through this @smallersign

**Comment by smallersign** [comment]
It's happening any website for SVG with JS. The js file cashing as well but the problem is the SVG fonts re-creating when page reload or page open. 

You should try yourself to setup SVG with JS vs Wesbfornts with CSS, will understand the difference. (Recommend, test on cPanel server)

**Comment by smallersign** [comment]
If there any update about it, kindly let me know.

**Comment by robmadole** [comment]
Without seeing a live example of your site we can’t help you any further. Also if you’d like to fill in some of the answers to the questions I asked that would help too.

**Comment by smallersign** [comment]
Ok, will make a demo for you with 2 different page and will update you but maybe approx 7 days due to busy..
