### ISSUE TITLE
Create super light font

### ISSUE THREAD

**Issue by yosit** [FortAwesome/Font-Awesome#12396]
The current light font works really great when the font size is small, when you need large sized font the light version looks very thick.

![image](https://user-images.githubusercontent.com/123805/36426228-17685664-1652-11e8-8623-54e0906929b8.png)

**Comment by smallersign** [comment]
I think we need xlte & lite. Which xlite is current lite and lite will be the only outline. For example: https://thumb7.shutterstock.com/display_pic_with_logo/3943037/519039097/stock-vector-thin-line-user-icon-on-white-background-519039097.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that, at the moment I'm writing, this is a request for 662 new icons

**Comment by sensibleworld** [comment]
Doing some issue cleanup :) Font Awesome now includes Regular, Light, and Thin styles.
