### ISSUE TITLE
fa-institution fa-bank fa-university icon not displaying?

### ISSUE THREAD

**Issue by saelder** [FortAwesome/Font-Awesome#12390]
The institution icon just disappeared from my UI -- I can swap out for other icons, but curious to know what's going on.  Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please verify your code and provide a reproducible test case?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by saelder** [comment]
Thank you for responding!  Found the source of the issue -- it was an import in another js library that was importing an old version (4.0.3) of font-awesome.  Removed that reference, and it works!

**Comment by tagliala** [comment]
Glad you've solved

Closing here
