### ISSUE TITLE
How to update font awesome from version 4 to version 5 in beautiful Jekyll theme? 

### ISSUE THREAD

**Issue by allan9595** [FortAwesome/Font-Awesome#12399]
I want to use Discord font awesome in beautiful jekyll, but seems like beautiful jekyll still use version 4 for the font awesome. So my discord not works on my site. How can I fix this? 

https://deanattali.com/beautiful-jekyll/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You have different ways to upgrade to FA5, but you are required to edit the source code of your HTML files.

Docs: https://fontawesome.com/how-to-use/upgrading-from-4

You can also check open an issue at https://github.com/daattali/beautiful-jekyll/issues and ask the author to upgrade to FA5

Hope it helps

Closing here
