### ISSUE TITLE
Where I find support to older version or older documentations

### ISSUE THREAD

**Issue by RamyresZscan** [FortAwesome/Font-Awesome#12398]
I need mantein an software that use older version of fontawesome. You did remove all docs from the web

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for being part of the Font Awesome Community.

1. In the home, below the "download" buttons
2. In the footer

This has also been requested at #12232

Please continue on #12311

Closing here
