### ISSUE TITLE
Font Awesome API it is "styles" not "style" - Documentation needs to be corrected

### ISSUE THREAD

**Issue by DominicFath** [FortAwesome/Font-Awesome#12397]
Hi,
It took me quite a while to figure out why this did not work

```
const fontawesomeLayer = fontawesome.layer((push) => {
	push(fontawesome.icon(iconType, { 
			style: {'background-color': iconColor, color: 'white'}, 
			title: 'hans'
		})
	)
	push(fontawesome.text('1', {
			transform: {size: 10},
			styles: {'color': 'black'} 
		})
	)

});
```

its been a breaking change since:

https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#500-rc5----2017-11-28

it is calles "styles".

but in your documentation it says style

https://fontawesome.com/how-to-use/font-awesome-api#text

all the best,

Dominic

**Comment by robmadole** [comment]
Ah, yeah that's a doc bug. We'll get this fixed.

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Font Awesome API it is "styles" not "style" -](https://trello.com/c/S1oWTnXa/43-font-awesome-api-it-is-styles-not-style)

**Comment by mlwilkerson** [comment]
The fix for this has been made. Awaiting merge and publication.
