### ISSUE TITLE
Icon request:In and Out

### ISSUE THREAD

**Issue by TSStudio** [FortAwesome/Font-Awesome#12393]
Like this:
![Example of Image](http://img.sootuu.com/vector/2006-4/200641918529385.jpg)
and reverse(out)

**Comment by tagliala** [comment]
Already here as sign-in-alt and sign-out-alt

https://fontawesome.com/icons/sign-out-alt?style=solid
https://fontawesome.com/icons/sign-in-alt?style=solid
