### ISSUE TITLE
Darts

### ISSUE THREAD

**Issue by zippy6** [FortAwesome/Font-Awesome#12400]
Can we have a dart board or 3 darts as an icon ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This could be a duplicate of #11567, but I'm not sure.

Could you please check?

If this isn't a duplicate, please fill our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
No problem, please add a 👍  reaction to #11567
