### ISSUE TITLE
Icon-List with all icons

### ISSUE THREAD

**Issue by almfisch** [FortAwesome/Font-Awesome#12412]
Hi,

is there a easy way to generate or get a list of all icons like:
fab fa-500px
fab fa-accessible-icon
fas fa-align-center
fas fa-align-justify
...

In version 4 it was easy, because all icons had fa before, now there there are far, fas or fab.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Maybe you can create the list you need via [icons.yml](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml)

Does it help?

**Comment by almfisch** [comment]
Hi,

thank you for your comment.
I made a [PHP-Script](http://scripts.snippfish.de/fa5il.php), that converts the icons.yml into a list. (I need the list for example for an icon-picker).

**Comment by tagliala** [comment]
@almfisch Thanks for sharing

I'm going to close here
