### ISSUE TITLE
Icon Request: fa-type-size

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12419]
looking for the icon on type or size...  The T little T
![image](https://user-images.githubusercontent.com/36716550/36511806-fdd61e4a-171c-11e8-9f3c-6c1fef6e0a8f.png)

**Comment by aethior** [comment]
Hi @naluoli,

This icon was added in v5.9.0.
Check https://fontawesome.com/icons/text-size

Regards.

cc/ @tagliala
