### ISSUE TITLE
fa-facebook-f

### ISSUE THREAD

**Issue by websydaisy** [FortAwesome/Font-Awesome#12418]
I am trying to use the plain f for Facebook (not square). If I use the svg with js method, it works fine, BUT I need to put a text-shadow on it, so I switched to the webfont method (CDN), but it is displaying as the facebook square. 

I am using this: fab fa-facebook-f

But getting:

<img width="74" alt="screen shot 2018-02-21 at 4 56 15 pm" src="https://user-images.githubusercontent.com/4122190/36510311-2e7835d2-1728-11e8-808f-c72e3c9f1f8f.png">

Is this a bug in the webfont?

**Comment by websydaisy** [comment]
Just checked the fontawesome css and there it is:

.fa-facebook-f:before, .fa-facebook:before {
    content: "\f09a";
}

I'm just adding 

.fa-facebook-f:before {
    content: "\f39e"!important;
}

to my stylesheet. Leaving here in case it's an issue for anyone else.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm: https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/css/fontawesome-all.css#L982-L986

`fa-facebook-f` and `.fa-facebook` have their own separate unicode point

Please check that you are using the latest version of Font Awesome and there are not older versions or third party stylesheets involved

Closing here

**Comment by markhilton** [comment]
I am using latest pro version and I have the same issue with Facebook icon rendering as F in a square. @websydaisy solution worked for me.

**Comment by elektra3** [comment]
Having the same issue!

**Comment by elektra3** [comment]
The strange thing is that @websydaisy 's solution is not working for Chrome, but works for Opera and Safari.
