### ISSUE TITLE
User icon change request

### ISSUE THREAD

**Issue by webvitalii** [FortAwesome/Font-Awesome#1241]
Thank you very much for Font_awesome.

I have one small request about user icon.
On 14px font-size user icon now looks like catholic priest with white collar :)

![user-icon](https://f.cloud.github.com/assets/2699906/629366/1b1326d8-d145-11e2-9fc2-6aee723fbf4a.png)

IMHO this could be fixed just by connecting round head to the body in the icon.

**Comment by renarena** [comment]
+1
how will the user will be shaped / for when is 5.0 planned?

**Comment by thisisfranciswu** [comment]
+1

OMG yes, the user icon can use much-needed refinement.

**Comment by ShiftCtrlArt** [comment]
I would like to suggest a "users" icon that looks more like this for your consideration:
![fortawesome-suggestion-users](https://cloud.githubusercontent.com/assets/12486399/7671652/271bc75c-fc8e-11e4-839f-9c0ae41c7d1f.jpg)

**Comment by GermanKiwi** [comment]
@ShiftCtrlArt you should open a separate issue for that, as it's a separate request. This issue here is discussing the fa-user (singular) icon, not the fa-users (plural) icon.

**Comment by tagliala** [comment]
there is already a request like that: #2883

**Comment by tagliala** [comment]
I'm going to close this one because we have new user icons in FA5

https://jsfiddle.net/tagliala/tgzouajm/40/
