### ISSUE TITLE
import tree shaking not working with laravel mix

### ISSUE THREAD

**Issue by michaelmano** [FortAwesome/Font-Awesome#12429]
```
        "@fortawesome/fontawesome": "^1.1.3",
	"@fortawesome/fontawesome-pro-regular": "^5.0.6",
```
```
import fontawesome from '@fortawesome/fontawesome';
import {
 faPhone,
 faAngleRight,
} from '@fortawesome/fontawesome-pro-regular';

fontawesome.library.add(faPhone, faAngleRight);

```
The following imports the whole bloody library, my js ends up being around 700kb,

```
/**
 * Font Awesome settings, Singluar imports due to tree shaking not working
 */
import fontawesome from '@fortawesome/fontawesome';
import faPhone from '@fortawesome/fontawesome-pro-regular/faPhone';
import faAngleRight from '@fortawesome/fontawesome-pro-regular/faAngleRight';

fontawesome.library.add(faPhone, faAngleRight);
```
That works.. though its annoying.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I didn't get if they both don't work or if the first works and the second doesn't or viceversa

Could you please clarify?

**Comment by robmadole** [comment]
We're working on making this less annoying. Stay tuned @michaelmano

**Comment by michaelmano** [comment]
@tagliala sorry thought the title made it clear, the first does not work. Its with laravel mix which is based on webpack2

**Comment by tagliala** [comment]
@michaelmano don't worry. It appears to be a known issue, please stay tuned

**Comment by mlwilkerson** [comment]
@michaelmano would you like to try your laravel mix scenario with some of our pre-releases that are tuned for tree shaking that Just Works™️ ?

If I were to start with the code from your original post and redo for the pre-release package names and versions (as today's living-on-the-edge versions, that is), I think it would be:

```json
        "@fortawesome/fontawesome-svg-core": "^1.2.0-10",
	"@fortawesome/pro-regular-svg-icons": "^5.1.0-7",
```
```javascript
import { library } from '@fortawesome/fontawesome-svg-core';
import {
 faPhone,
 faAngleRight,
} from '@fortawesome/pro-regular-svg-icons';

library.add(faPhone, faAngleRight);
```

If you try it, please let us know how it goes.

**Comment by hal869** [comment]
@mlwilkerson fyi,

```
yarn add \
 @fortawesome/fontawesome@prerelease \
 @fortawesome/fontawesome-common-types@prerelease \
 @fortawesome/fontawesome-free-solid@prerelease \
 @fortawesome/fontawesome-free-regular@prerelease \
 @fortawesome/fontawesome-free-brands@prerelease \
 @fortawesome/fontawesome-svg-core@prerelease

yarn list | grep fortawesome├─ @fortawesome/fontawesome-common-types@0.2.0-5
	├─ @fortawesome/fontawesome-free-brands@5.1.0-3
	│  ├─ @fortawesome/fontawesome-common-types@^0.1.2-1
	│  └─ @fortawesome/fontawesome-common-types@0.1.3
	├─ @fortawesome/fontawesome-free-regular@5.1.0-3
	│  ├─ @fortawesome/fontawesome-common-types@^0.1.2-1
	│  └─ @fortawesome/fontawesome-common-types@0.1.3
	├─ @fortawesome/fontawesome-free-solid@5.1.0-3
	│  ├─ @fortawesome/fontawesome-common-types@^0.1.2-1
	│  └─ @fortawesome/fontawesome-common-types@0.1.3
	├─ @fortawesome/fontawesome-svg-core@1.2.0-10
	│  └─ @fortawesome/fontawesome-common-types@^0.2.0-5
	├─ @fortawesome/fontawesome@1.2.0-6
	│  └─ @fortawesome/fontawesome-common-types@^0.2.0-1

import {library} from '@fortawesome/fontawesome-svg-core';
import {
	faBars,
	faExclamationCircle,
} from '@fortawesome/fontawesome-free-solid';
fontawesome.library.add(
	faBars,
	faExclamationCircle,
);
```
seems to be working; in markup,
```
<i class="fa fa-bars"></i>
<i class="fa fa-exclamation-circle"></i>
```
are rendered as expected


but, examining webpack generated chunks

```
grep awesome /build/js/main.js
	/* harmony import */ var _fortawesome_fontawesome__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("./node_modules/@fortawesome/fontawesome/index.es.js");
	/* harmony import */ var _fortawesome_fontawesome_svg_core__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__("./node_modules/@fortawesome/fontawesome-svg-core/index.es.js");
	/* harmony import */ var _fortawesome_fontawesome_free_solid__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__("./node_modules/@fortawesome/fontawesome-free-solid/shakable.es.js");
	_fortawesome_fontawesome__WEBPACK_IMPORTED_MODULE_1__["default"].library.add(_fortawesome_fontawesome_free_solid__WEBPACK_IMPORTED_MODULE_3__["faBars"],  _fortawesome_fontawesome_free_solid__WEBPACK_IMPORTED_MODULE_3__["faExclamationCircle"]);

grep awesome /build/js/vendor.js

	/***/ "./node_modules/@fortawesome/fontawesome-free-solid/shakable.es.js":
	 * Font Awesome Free 5.0.4 by @fontawesome - http://fontawesome.com
	 * License - http://fontawesome.com/license (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
	/***/ "./node_modules/@fortawesome/fontawesome-svg-core/index.es.js":
	 * Font Awesome Free 5.1.0-7 by @fontawesome - https://fontawesome.com
	 * License - https://fontawesome.com/license (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
	var HTML_CLASS_I2SVG_BASE_CLASS = 'fontawesome-i2svg';
	/***/ "./node_modules/@fortawesome/fontawesome/index.es.js":
	 * Font Awesome Pro 5.0.6 by @fontawesome - https://fontawesome.com
	 * License - https://fontawesome.com/license (Commercial License)
	var HTML_CLASS_I2SVG_BASE_CLASS = 'fontawesome-i2svg';
	                // A tribute to the "awesome hack by Dean Edwards"
```

 it doesn't appear 'shaken'; i.e., as above

> The following imports the whole bloody library, my js ends up being around 700kb,

it's still immensely, all-inclusively "fat", at ~ 2.5Mb

<details>

 <summary>egrep ", \"fa|var fa" vendor.js </summary>

```
egrep ", \"fa|var fa" vendor.js 
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "fas", function() { return _iconsCache; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "faAddressBook", function() { return faAddressBook; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "faAddressCard", function() { return faAddressCard; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "faAdjust", function() { return faAdjust; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "faAlignCenter", function() { return faAlignCenter; });
...
var faAddressBook = { prefix: 'fas', iconName: 'address-book', icon: [448, 512, [], "f2b9", "M436 160c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12h-20V48c0-26.51-21.49-48-48-48H48C21.49 0 0 21.49 0 48v416c0 26.51 21.49 48 48 48h320c26.51 0 48-21.49 48-48v-48h20c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12h-20v-64h20c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12h-20v-64h20zm-228-32c44.183 0 80 35.817 80 80s-35.817 80-80 80-80-35.817-80-80 35.817-80 80-80zm128 232c0 13.255-10.745 24-24 24H104c-13.255 0-24-10.745-24-24v-18.523c0-22.026 14.99-41.225 36.358-46.567l35.657-8.914c29.101 20.932 74.509 26.945 111.97 0l35.657 8.914C321.01 300.252 336 319.452 336 341.477V360z"] };
var faAddressCard = { prefix: 'fas', iconName: 'address-card', icon: [512, 512, [], "f2bb", "M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm-288 80c38.66 0 70 31.34 70 70s-31.34 70-70 70-70-31.34-70-70 31.34-70 70-70zm112 203c0 11.598-9.402 21-21 21H85c-11.598 0-21-9.402-21-21v-16.207c0-19.272 13.116-36.072 31.813-40.746l31.2-7.8c25.464 18.316 65.195 23.577 97.974 0l31.2 7.8C274.884 294.721 288 311.52 288 330.793V347zm160-39c0 6.627-5.373 12-12 12H332c-6.627 0-12-5.373-12-12v-8c0-6.627 5.373-12 12-12h104c6.627 0 12 5.373 12 12v8zm0-64c0 6.627-5.373 12-12 12H332c-6.627 0-12-5.373-12-12v-8c0-6.627 5.373-12 12-12h104c6.627 0 12 5.373 12 12v8zm0-64c0 6.627-5.373 12-12 12H332c-6.627 0-12-5.373-12-12v-8c0-6.627 5.373-12 12-12h104c6.627 0 12 5.373 12 12v8z"] };
var faAdjust = { prefix: 'fas', iconName: 'adjust', icon: [512, 512, [], "f042", "M8 256c0 136.966 111.033 248 248 248s248-111.034 248-248S392.966 8 256 8 8 119.033 8 256zm248 184V72c101.705 0 184 82.311 184 184 0 101.705-82.311 184-184 184z"] };
var faAlignCenter = { prefix: 'fas', iconName: 'align-center', icon: [448, 512, [], "f037", "M352 44v40c0 8.837-7.163 16-16 16H112c-8.837 0-16-7.163-16-16V44c0-8.837 7.163-16 16-16h224c8.837 0 16 7.163 16 16zM16 228h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 256h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm320-200H112c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16h224c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16z"] };
...
```
</details>

**Comment by robmadole** [comment]
@hal869 we have new packages for the icon contents:

* @fortawesome/free-solid-svg-icons
* @fortawesome/free-regular-svg-icons
* @fortawesome/free-brands-svg-icons

Also you do not need @fortawesome/fontawesome any longer. Have a look at the upgrading guide: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

**Comment by hal869** [comment]
@robmadole 

As above, I'd had

```
yarn add \
 @fortawesome/fontawesome@prerelease \
 @fortawesome/fontawesome-common-types@prerelease \
 @fortawesome/fontawesome-free-solid@prerelease \
 @fortawesome/fontawesome-free-regular@prerelease \
 @fortawesome/fontawesome-free-brands@prerelease \
 @fortawesome/fontawesome-svg-core@prerelease
```

Readinng the UPGRADING link, still  a bilt unclear.

You mention
> you do not need @fortawesome/fontawesome

Does that imply that it's to be *replaced* by "@fortawesome/fontawesome-free", and not simply removed with no replacement?

Also, there's no explicit mention above, that I noticed, of either "fontawesome-common-types" or "fontawesome-svg-core".  Are they to be removed or replaced?  IS there new naming convention for them as well?

I.e., which are the following are/aren't needed to replace the above:
```
yarn add \
 @fortawesome/fontawesome-free \  ??????
 @fortawesome/fontawesome-common-types \   ??????
 @fortawesome/free-solid-svg-icons \
 @fortawesome/free-regular-svg-icons \
 @fortawesome/free-brands-svg-icons \
 @fortawesome/fontawesome-svg-core  ??????
```

Back to staring at that UPGRADING document ...

**Comment by robmadole** [comment]
@hal869 

Run this instead:

```
yarn add \
 @fortawesome/fontawesome-svg-core@prerelease \
 @fortawesome/free-solid-svg-icons@prerelease \
 @fortawesome/free-regular-svg-icons@prerelease \
 @fortawesome/free-brands-svg-icons@prerelease \
```

And then in your code example:

```javascript
import { library, dom } from '@fortawesome/fontawesome-svg-core';
import {
	faBars,
	faExclamationCircle,
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faBars,
	faExclamationCircle,
);

dom.watch()
```

**Comment by hal869** [comment]
@robmadole Ok, will give that a try here in a minute.

From the doc, it explicity says:
```
New packages available for browser-only integration

If you were previously using @fortawesome/fontawesome you need to switch to one of the new packages.

Our Free and Pro CDN provide access to JS, CSS, sprites, and separate SVG files.

We've now made these files conveniently available through NPM.

    @fortawesome/fontawesome-free
    @fortawesome/fontawesome-pro (private package, requires Pro subscription)
```

Which seems pretty clear, replace - not just remove.  Unless this is just due to the fact that I was using "@fortawesome/fontawesome" to get around the interim issues, above.

**Comment by hal869** [comment]
fwiw, at 1st attempt with the above changes, NONE of my used FA icons display -- ALL are simply dotted circele, alternatiing between "!" & "?"

**Comment by hal869** [comment]
Cleaning
```
yarn --force remove @fortawesome/fontawesome
yarn --force remove @fortawesome/fontawesome-common-types
yarn --force remove @fortawesome/fontawesome-free-solid
yarn --force remove @fortawesome/fontawesome-free-regular
yarn --force remove @fortawesome/fontawesome-free-brands
yarn --force remove @fortawesome/fontawesome-svg-core
```

Installing new packages
```
yarn add \
 @fortawesome/fontawesome-svg-core@prerelease \
 @fortawesome/free-solid-svg-icons@prerelease \
 @fortawesome/free-regular-svg-icons@prerelease \
 @fortawesome/free-brands-svg-icons@prerelease

grep awe package.json
    "@fortawesome/fontawesome-svg-core": "^1.2.0-12",
    "@fortawesome/free-brands-svg-icons": "^5.1.0-9",
    "@fortawesome/free-regular-svg-icons": "^5.1.0-9",
    "@fortawesome/free-solid-svg-icons": "^5.1.0-9",
```

Removing from webpack config now-unncessary shaking config
```
	resolve: {
		alias: {
-			'@fortawesome/fontawesome-free-solid$':   '@fortawesome/fontawesome-free-solid/shakable.es.js',
-			'@fortawesome/fontawesome-free-brands$':  '@fortawesome/fontawesome-free-brands/shakable.es.js',
-			'@fortawesome/fontawesome-free-regular$': '@fortawesome/fontawesome-free-regular/shakable.es.js'
		},
```

Replacing in site JS
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);
```

In markup, both
```
<i class="fa fa-asterisk" ></i>
<i class="fas fa-asterisk" ></i>
```

fail to render.

**Comment by hal869** [comment]
Cleaning
```
yarn --force remove @fortawesome/fontawesome
yarn --force remove @fortawesome/fontawesome-common-types
yarn --force remove @fortawesome/fontawesome-free-solid
yarn --force remove @fortawesome/fontawesome-free-regular
yarn --force remove @fortawesome/fontawesome-free-brands
yarn --force remove @fortawesome/fontawesome-svg-core
```

Installing new packages
```
yarn add \
 @fortawesome/fontawesome-svg-core@prerelease \
 @fortawesome/free-solid-svg-icons@prerelease \
 @fortawesome/free-regular-svg-icons@prerelease \
 @fortawesome/free-brands-svg-icons@prerelease

grep awe package.json
    "@fortawesome/fontawesome-svg-core": "^1.2.0-12",
    "@fortawesome/free-brands-svg-icons": "^5.1.0-9",
    "@fortawesome/free-regular-svg-icons": "^5.1.0-9",
    "@fortawesome/free-solid-svg-icons": "^5.1.0-9",
```

Removing from webpack config now-unncessary shaking config
```
	resolve: {
		alias: {
-			'@fortawesome/fontawesome-free-solid$':   '@fortawesome/fontawesome-free-solid/shakable.es.js',
-			'@fortawesome/fontawesome-free-brands$':  '@fortawesome/fontawesome-free-brands/shakable.es.js',
-			'@fortawesome/fontawesome-free-regular$': '@fortawesome/fontawesome-free-regular/shakable.es.js'
		},
```

Replacing in site JS
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);
```

Note, if I do what the doc says to 
```
import library.add(fas);
```

then webpack build FAILS compilation
```
	...
	38:8  error  Parsing error: Identifier 'library' has already been declared
	...
	Module build failed: SyntaxError: /srv/www/test/assets/js/main.js: Unexpected token (38:14)

	  36 | global.$ = require('jquery');
	  37 | 
	> 38 | import library.add(fas);
	     |               ^
	  39 | 
	...
```

In markup, both
```
<i class="fa fa-asterisk" ></i>
<i class="fas fa-asterisk" ></i>
```

fail to render.

**Comment by hal869** [comment]
@robmadole fyi

Cleaning
```
yarn --force remove @fortawesome/fontawesome
yarn --force remove @fortawesome/fontawesome-common-types
yarn --force remove @fortawesome/fontawesome-free-solid
yarn --force remove @fortawesome/fontawesome-free-regular
yarn --force remove @fortawesome/fontawesome-free-brands
yarn --force remove @fortawesome/fontawesome-svg-core
```

Installing new packages
```
yarn add \
 @fortawesome/fontawesome-svg-core@prerelease \
 @fortawesome/free-solid-svg-icons@prerelease \
 @fortawesome/free-regular-svg-icons@prerelease \
 @fortawesome/free-brands-svg-icons@prerelease

grep awe package.json
    "@fortawesome/fontawesome-svg-core": "^1.2.0-12",
    "@fortawesome/free-brands-svg-icons": "^5.1.0-9",
    "@fortawesome/free-regular-svg-icons": "^5.1.0-9",
    "@fortawesome/free-solid-svg-icons": "^5.1.0-9",
```

Removing from webpack config now-unncessary shaking config
```
	resolve: {
		alias: {
-			'@fortawesome/fontawesome-free-solid$':   '@fortawesome/fontawesome-free-solid/shakable.es.js',
-			'@fortawesome/fontawesome-free-brands$':  '@fortawesome/fontawesome-free-brands/shakable.es.js',
-			'@fortawesome/fontawesome-free-regular$': '@fortawesome/fontawesome-free-regular/shakable.es.js'
		},
```

Replacing in site JS
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);
```

Note, if I do what the doc says to 
```
import library.add(fas);
```

then webpack build FAILS compilation
```
	...
	38:8  error  Parsing error: Identifier 'library' has already been declared
	...
	Module build failed: SyntaxError: /srv/www/test/assets/js/main.js: Unexpected token (38:14)

	  36 | global.$ = require('jquery');
	  37 | 
	> 38 | import library.add(fas);
	     |               ^
	  39 | 
	...
```

In markup, both
```
<i class="fa fa-asterisk" ></i>
<i class="fas fa-asterisk" ></i>
```

fail to render.

**Comment by mlwilkerson** [comment]
re-joining the convo here, just one simple observation:

> Note, if I do what the doc says to
>> import library.add(fas);

That's a typo in the doc. I'm putting in a fix for that now.

**Comment by mlwilkerson** [comment]
@hal869 As for the replace/remove question, what we intend is that, where you previously had
`@fortawesome/fontawesome`, instead now use `@fortawesome/fontawesome-svg-core`. 

In your original comment, your `yarn add` included both of those packages.

**Comment by hal869** [comment]
@mlwilkerson 

> That's a typo in the doc. I'm putting in a fix for that now.
:+1:

> In your original comment, your yarn add included both of those packages.
RIght.  In the 'interim' state of affairs, both were necessary.

So, current state -- with info as above -- _is_ ***non***-functional

**Comment by mlwilkerson** [comment]
@hal869 Do you have a running example I could look at the browser? Either on a staging site somewhere, or with codesandbox.io?

**Comment by hal869** [comment]
@mwilkerson nope, sorry.  What specifically are you looking for?

**Comment by mlwilkerson** [comment]
I'd like to see what's contained in the JS bundles the browser is loading for starters. And possibly run it under a debugger.

Or maybe you could reproduce your situation in a little demo GitHub repo that I could clone and investigate?

**Comment by hal869** [comment]
@mlwilkerson 
It'd be likely be more helpful & easier if, seeing as how it apparently all works for you, to provide, as part of documentation, a working example.

In the meantime, this doesn't: https://codesandbox.io/s/o4845mkk6q

Never even header pf codesandbox, so no clue whether that's even properly built up.

Dropping back, here, to the 'interim' solution above stil works -- at least with rendering.

**Comment by jbelien** [comment]
Nice, I'll try to upgrade to `5.1.0` ! 👍 
It would be also nice to update https://fontawesome.com/how-to-use/use-with-node-js but I guess it's already planned ! 😄

**Comment by robmadole** [comment]
@jbelien sorry you got busy on this before I could share this link:

https://fontawesome.com/preview/how-to-use/use-with-node-js

We have some pre-release docs up (which I wish I could have gotten to you in time.)

Thanks for the PRs on the UPGRADING.md. Really appreciate you slogging through this, it's super helpful to us.

**Comment by robmadole** [comment]
@hal869 you were very close: https://codesandbox.io/s/k53zqoqox3

What was missing was the `dom.watch()`.

**Comment by hal869** [comment]
I'd seen the use of ```dom.watch()``` above; as it wasn't mentioned in the docs, I'd assumed, mistakenly, it was for debugging usage.

I now see at

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

that
```
// Kicks off the process of finding <i> tags and replacing with <svg>dom.watch()
```

has been added.

and at

https://fontawesome.com/preview/how-to-use/use-with-node-js

there's this mention
```
SVG core and icon content packagesWe also provide more advanced packages that are suitable for more specialized situations. These packages are side-effect free and provide no automatic replacement of <i> tags to <svg> tags. (Although it can still be used through dom.watch())
```

adding ```dom.watch()``` _does_, now get my FA icons rendered again.

Reading the above, I've still no idea what's going on with the apparently necessary (?) "replacement of ```<i>``` tags to ```<svg>``` tags". 

Should we be changing markup from ```<i>``` to ```<svg>```? Or is this necessarily done automagically with this ```dom.watch()``` call?

Can docs perhaps address this in some greater/understandable detail?

Next, to check generated sizes to make sure shaking's working as expected ...

**Comment by hal869** [comment]
@robmadole 

With dom.watch in place, and config as above, checking for tree shaking (i'm only actually using ~6 fa icaons, currently, in my site markup)

Without FA imports (commented out in site JS), after production webpack

```
ls -al public/build/js/*
        -rw-rw-r--+ 1 wwwrun www 5.6K May  3 06:45 public/build/js/main.38e7ffca207d0830a629.js
        -rw-rw-r--+ 1 wwwrun www 1.1K May  3 06:45 public/build/js/runtime_manifest.4e54a23f2527bc26fc20.js
        -rw-rw-r--+ 1 wwwrun www 209K May  3 06:45 public/build/js/vendor.e7dccc1a61a89ba07b70.js
```

WITH FA imports (included in site JS), after production webpack

```
ls -al public/build/js/*
        -rw-rw-r--+ 1 wwwrun www 5.8K May  3 06:46 public/build/js/main.024518d550f9619dcb70.js
        -rw-rw-r--+ 1 wwwrun www 1.1K May  3 06:46 public/build/js/runtime_manifest.4e54a23f2527bc26fc20.js
        -rw-rw-r--+ 1 wwwrun www 570K May  3 06:46 public/build/js/vendor.abb0d0a52df01e72bb25.js
```

Checking FA output
```
grep awesome public/build/js/vendor*.js > ~/fa.out && ls -al ~/fa.out
        -rw-r--r-- 1 wwwrun www 484K May  3 06:47 /var/lib/wwwrun/fa.out
```

output does not appear shaken, at 484K

**_since GitHub won't allow it,
``` You can't comment at this time — your comment is too long (maximum is 65536 characters).  ```_**

```
cat ~/fa.out ==>
```
 https://paste.fedoraproject.org/paste/foptZV~mxnghE9LyVRPsOg/raw

Which all clearly includes icons' src that I am _not_ using.

**Comment by robmadole** [comment]
@hal869 I have a PR out to improve that documentation in `how-to-use/use-with-node-js`. Thanks for the pointer there.

Thanks for sharing your bundle above. It's useful to see the file sizes and to see the output from your build but it's really hard for us to debug or help solve the issue unless the problem is reproducible. Anything else is really just a shot in the dark (a guess) as to what the issue is.

There are a lot of factors involved. Errant code, webpack version, webpack build config, transpiler, etc. It's just too difficult to help unless we have a reproducible example.

Perhaps you can put up a GitHub gist that strips down your project and illustrates the problem? I'd be overjoyed to help you solve it from there. But I need to be able to examine the whole forest and not the pinecones that are shaking off the tree (pun totally intended).

**Comment by robmadole** [comment]
@hal869 not trying to be a pain here (I know you're working hard to try and provide the information that we are asking for) but I need to be able to `git clone` something, run `yarn`, and then `yarn build` (or some command that runs Webpack). There is still just too much missing information here. I need the whole ball of wax that I can run locally.

**Comment by jbelien** [comment]
I see `webpack --env development --progress`.

As mentioned in my [previous comment](https://github.com/FortAwesome/Font-Awesome/issues/12429#issuecomment-386224022), `webpack` only  "enables" tree shaking in production mode (see https://webpack.js.org/guides/tree-shaking/#minify-the-output).

**Comment by hal869** [comment]
@robmadole 

Understood. Appreciate the efforts.

Sorry, but best I can do.  My setup works -- installs/updates, packs, etc -- in my env for my webapp.

As I mentioned above, since you're clearly of the view that it works for "you", it'd be MUCH simpler for you to post a *live* working example (codesandbox.io, or equiv), loading deps, webpacking, and demonstrating that both rendering and shaking functioning as expected.

That solves the problem of 'you' trying to solve everybody's issues, and gives 'us' something known to work to adapt to.

In the meantime, guess I need to unwind FA5 from production, or figure out how to 'manually' shake using the new versions of pkgs, until if/when this gets sorted.

**Comment by hal869** [comment]
@jbelien 

fwiw,

```
disable/comment out all FA from main.js

 yarn run wp:p
  yarn run v1.6.0
  $ webpack --env production --progress
  ...
  92% chunk asset optimization UglifyJSPlugin
  ...

 ls -al public/build/js/vendor.e7dccc1a61a89ba07b70.js
  -rw-rw-r--+ 1 root root 209K May  3 10:01 public/build/js/vendor.e7dccc1a61a89ba07b70.js
 grep -i awe public/build/js/vendor.e7dccc1a61a89ba07b70.js
  (empty)

enable/uncomment all FA

 yarn run wp:p
  yarn run v1.6.0
  $ webpack --env production --progress
  ...
  92% chunk asset optimization UglifyJSPlugin
  ...
 ls -al public/build/js/vendor.abb0d0a52df01e72bb25.js
  -rw-rw-r--+ 1 root root 570K May  3 10:03 public/build/js/vendor.abb0d0a52df01e72bb25.js
```

atm, that's an addition of ~360K of optimized JS due to the inclusion of FA5.

**Comment by robmadole** [comment]
@hal869 https://gist.github.com/robmadole/93ea58b5aff804cfb61bd6670bf2cc37

Clone that and follow the instructions in the README.md. Tree shaking is working in that very simple example. I'm wondering if your UglifyJSPlugin could be breaking tree shaking for you. Can you confirm that other libraries you are using (non FA) are being tree shaken?

**Comment by hal869** [comment]
@robmadole 

From

https://webpack.js.org/guides/tree-shaking/#conclusion

> So, what we've learned is that in order to take advantage of tree shaking, you must...
> 
>     Use ES2015 module syntax (i.e. import and export).
>     Add a "sideEffects" entry to your project's package.json file.
>     Include a minifier that supports dead code removal (e.g. the UglifyJSPlugin).

In your gist example, I don't see a "sideEffects" param either in your package.json, or  modules.rules

I don't see an explicit minifier invocation either in your webpack.config.js or your script cmd line.

How are your dealing with both requirements?  Are you simply assuming whatever the defaults of the embedded webpack dev server are?

I also don't see _usage_ of babel, and note that you're using old babel6x; whereas, I'm using @babel7 -- which may play a part.

**Comment by edmorley** [comment]
Sorry missed that - add `stats: "errors-only"` to your webpack configuration object instead :-)

> Are you simply assuming whatever the defaults of the embedded webpack dev server are?

> I don't use the webpack dev server

This might just be a ~typo -- but note that webpack dev server doesn't play a role in any of this, since tree shaking is only relevant for production mode, where dev server shouldn't be being used.

**Comment by edmorley** [comment]
`stats: "verbose"` even

**Comment by hal869** [comment]
I'm still looking for the explicit minify & sideEffects config in the gist ...

**Comment by robmadole** [comment]
@hal869 I'm not going to spend any more time on trying to reproduce your setup. I have illustrated that tree shaking does work with our library. If you'd like to share what you have I'll be happy to help. Otherwise I've gone as far as I'm willing to go in order to debug this in the dark with you.

**Comment by hal869** [comment]
Who's leaving whom in the dark is a matter of opinion.

But if you're not interested in selling your product, fine with me.  Good luck.

**Comment by luchaos** [comment]
1. followed step by step https://github.com/FortAwesome/Font-Awesome/issues/12429#issuecomment-386124097

```
import {dom, library} from '@fortawesome/fontawesome-svg-core';
import {faArrowRight} from "@fortawesome/free-solid-svg-icons";
library.add(faArrowRight);
dom.watch();
```

2. `npm run watch`:
```
/js/icons.js     495 kB       1  [emitted]  [big]  /js/icons
```

3. `npm run production`:
```
/js/icons.js    30.9 kB       1  [emitted]         /js/icons
```

4. happiness. works like a charm with laravel mix now - thanks!

**Comment by michaelmano** [comment]
@mlwilkerson mlwilkerson Thanks so much for that, Sorry I did not get back to you sooner, Some reason the issue was muted.

I have tried it out and it works like a dream :3
