### ISSUE TITLE
Typo on the site

### ISSUE THREAD

**Issue by armanrozika** [FortAwesome/Font-Awesome#12425]
https://fontawesome.com/icons/twitter?style=brands

the code provided there is `<i class="fab fa-twitter"></i>`,
I believe it should be `<i class="fa fa-twitter"></i>`, right?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Not a typo. FA5 works differently from FA4.

Please take a look here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
