### ISSUE TITLE
Icon request: Nintendo-3DS

### ISSUE THREAD

**Issue by TurtleP** [FortAwesome/Font-Awesome#12428]
### What can it be used for?

Much like with the Nintendo Switch icon, it can be used in websites for 3DS homebrew or even if official retailers have their own site which links to their Nintendo eShop page. Maybe have two different ones, one for an outline, the other one filled in for certain parts for a more solid look.

### Example image (optional)

Something similar to [this](https://thenounproject.com/search/?q=3ds&i=979917)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

P.S: For naming consistency, probably would be named `nintendo-3ds`, the name given in the title was for readability.

**Comment by tagliala** [comment]
Sorry, closing here as wontfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#582-to-590
