### ISSUE TITLE
Fa-bars used in ::before element not showing after updating from FontAwesome 4.6.0 to 5.0.6

### ISSUE THREAD

**Issue by Borromini** [FortAwesome/Font-Awesome#12430]
I am using a CSS which uses the [bars](https://fontawesome.com/icons/bars?style=solid) as content for a hamburger icon. In Chromium's (and Firefox's) mobile developer view, it looks fine (on a desktop) but the icon does not load on a truly mobile (Android) browser - Firefox, Chrome, Opera. It should look like this: [mobile view](https://postimg.org/image/ohobqzb99/) (upper right corner) but it never does. I have to point out it did use to work with FontAwesome 4.6.0 (I switched to 5.0.6). The Chromium console doesn't seem to show anything amiss...

CSS:
```
			#headerToggle {
				-moz-backface-visibility: hidden;
				-webkit-backface-visibility: hidden;
				-ms-backface-visibility: hidden;
				backface-visibility: hidden;
				-moz-transition: -moz-transform 0.5s ease;
				-webkit-transition: -webkit-transform 0.5s ease;
				-ms-transition: -ms-transform 0.5s ease;
				transition: transform 0.5s ease;
				display: block;
				height: 2.25em;
				left: 0;
				position: fixed;
				top: 0;
				width: 3.25em;
				z-index: 10001;
			}

				#headerToggle .toggle {
					position: absolute;
					left: 0;
					top: 0;
					width: 100%;
					height: 100%;
					outline: 0;
					border: 0;
				}

					#headerToggle .toggle:before {
						font-family: FontAwesome;
						text-decoration: none;
						font-style: normal;
						font-weight: normal;
						-webkit-font-smoothing: antialiased;
						-moz-osx-font-smoothing: grayscale;
						content: '\f0c9';
						font-weight: 900; /* Tried this as per the troubleshooting page but doesn't seem to help */
						color: #fff;
						font-size: 18px;
						line-height: 2.25em;
						background: rgba(128, 136, 144, 0.5);
						border-radius: 0.35em;
						text-align: center;
						position: absolute;
						left: 0.5em;
						top: 0.5em;
						display: block;
						width: 3.25em;
						height: 2.25em;
						line-height: 2.25em;
					}
```
Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you using the SVG or the webfont?

Anyway, the first error I can see is the `FontAwesome` family name. It is not supposed to be like that.

Please take a look at the docs:

SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
CSS: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Working fiddles
SVG: https://jsfiddle.net/tagliala/vLae8ted/68/
CSS: https://jsfiddle.net/tagliala/qq2eLxo1/31/

Next time, please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

Closing here

**Comment by Borromini** [comment]
Thanks. Turns out I had grabbed the CDN CSS, and the font name in there is Font Awesome\ 5, not Font Awesome 5... Silly me.

**Comment by kathrynlmclark** [comment]
5.0.7 - tried following this advice.  current situation: 
- Mac Chrome : showing rendered font is FontAwesome and i see the icons
- PC Chrome : showing rendered font is Arial and i see squares

tried using Font Awesome 5 Pro, Font Awesome\ 5 Pro and all i got is squares on my Mac.
code example below.

table.dataTable thead th.sorting:after,
table.dataTable thead th.sorting_asc:after,
table.dataTable thead th.sorting_desc:after {
    position: absolute;
    top: 12px;
    right: 8px;
    display: block;
    font-family: FontAwesome;
}

table.dataTable thead th.sorting:after {
    content: "\f0dc";
    color: #ddd;
    font-size: 0.8em;
    padding-top: 0.12em;
}
table.dataTable thead th.sorting_asc:after {
    content: "\f0de";
}
table.dataTable thead th.sorting_desc:after {
    content: "\f0dd";
}

**Comment by tagliala** [comment]
@kathrynlmclark 

> Font Awesome 5 Pro

SVG or CSS?

> font-family: FontAwesome;

This is wrong in both CSS ('Font Awesome 5 Pro') and SVG ('Font Awesome 5 Solid') versions

Please take a look at the docs:

SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
CSS: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Working fiddles
SVG: https://jsfiddle.net/tagliala/vLae8ted/68/
CSS: https://jsfiddle.net/tagliala/qq2eLxo1/31/

Hope it helps

**Comment by kathrynlmclark** [comment]
@tagliala was CSS mode.  tried again tonight and it worked just fine with font-family:"Font Awesome 5 Pro".  thx

**Comment by tagliala** [comment]
you're welcome
