### ISSUE TITLE
Icons show as flashing exclamation point/question mark FA 5 SVG

### ISSUE THREAD

**Issue by calebsurface** [FortAwesome/Font-Awesome#12432]
I'm trying to insert an icon into my markup, but instead of placing the icon I'm getting a dotted circle with an exclamation point and question mark that alternate back and forth.

I'm using the free CDN in my header and am trying to specifically use the angle right icon.

**Comment by calebsurface** [comment]
Solved my own problem. Somehow I was using far instead of fa for the class. Not sure how that happened.

**Comment by imperishableavinash** [comment]
Can you tell solution. I am also getting question mark after icon

**Comment by tagliala** [comment]
@imperishableavinash his solution:

> I was using far instead of fa for the class

**Comment by imperishableavinash** [comment]
i used fa still getting that blinking icon see it goo.gl/9PXuem

**Comment by gillespieza** [comment]
No, I have this problem to - using fab (as indicated for brand icons)

**Comment by tagliala** [comment]
@gillespieza please make sure you are importing fa brands (separate font style).

PS: locking here, this issue has many causes and one's solution will not work with others

If you think there is an issue with font awesome, please open a new issue with a reproducible test case
