### ISSUE TITLE
FontAwesome 5 Pro + Laravel

### ISSUE THREAD

**Issue by sigmoidal** [FortAwesome/Font-Awesome#12436]
I am using FA v5.0.6 with a laravel 5.5.x project via webpack's mix.

I have created a js resource asset file for font awesome:

```
import fontawesome from '@fortawesome/fontawesome';
import faArrowCircleUp from '@fortawesome/fontawesome-pro-regular/faArrowCircleUp';
import faArrowCircleDown from '@fortawesome/fontawesome-pro-regular/faArrowCircleDown';
import faCopy from '@fortawesome/fontawesome-pro-regular/faCopy';

fontawesome.library.add(faArrowCircleUp);
fontawesome.library.add(faArrowCircleDown);
fontawesome.library.add(faCopy);
```

No icons are rendered properly, instead the exclamation/question mark shows up.

When I change the code of the file above to:

```
import fontawesome from '@fortawesome/fontawesome';
import faArrowCircleUp from '@fortawesome/fontawesome-pro-regular/faArrowCircleUp';
import faArrowCircleDown from '@fortawesome/fontawesome-pro-regular/faArrowCircleDown';
import faCopy from '@fortawesome/fontawesome-pro-regular/faCopy';
fontawesome.library.add(faArrowCircleUp, faArrowCircleDown, faCopy);
```

All icons show up properly. 

Isn't the first case with successive calls to `fontawesome.library.add` supposed work?

**Comment by tagliala** [comment]
Ref: #12429, #12436

@robmadole is this a known issue?

**Comment by robmadole** [comment]
This is a confirmed bug. It's higher priority so we'll get to this as soon as we can.

**Comment by tagliala** [comment]
@robmadole thanks.

If this is the same issue of  #12429, can I close this one as a duplicate?

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/FortAwesome/Font-Awesome/issues/12436 https://github.com/FortAwesome/Font-Awesome/issues/12278 (branch started https://github.com/FortAwesome/fontawesome-buildsystem/tree/missing-icon-hijacking)](https://trello.com/c/36ttLzJ7/44-https-githubcom-fortawesome-font-awesome-issues-12436-https-githubcom-fortawesome-font-awesome-issues-12278-branch-started-https)

**Comment by robmadole** [comment]
@tagliala no this is not quite the same thing. Let's leave #12429 open please.

**Comment by ShaneXie** [comment]
any progress on this one?
the issue i have is I cant call library.add multiple time in separate js file,
eg.
```js
// file1.js
import fontawesome from '@fortawesome/fontawesome';
import faExternalLinkAlt from '@fortawesome/fontawesome-pro-regular/faExternalLinkAlt';
import faChevronDown from '@fortawesome/fontawesome-pro-solid/faChevronDown';

fontawesome.library.add(faExternalLinkAlt, faChevronDown);
``` . 
```js
// file2.js
import fontawesome from '@fortawesome/fontawesome';
import faFacebookF from '@fortawesome/fontawesome-free-brands/faFacebookF';
import faTwitter from '@fortawesome/fontawesome-free-brands/faTwitter';
import faPinterest from '@fortawesome/fontawesome-free-brands/faPinterest';

fontawesome.library.add(faFacebookF, faTwitter, faPinterest);
```
```js
// main.js
import 'file1';
import 'file2'
```

in this example only file1 icons get rendered in browser, however when i run `window.FontAwesome.library.definitions` in chrome console, I can see all of them.

**Comment by DimaFromCanada** [comment]
Any progress on this one? Still seems to be an issue, since I've just encountered it and spent over an hour debugging, until I found this thread.

**Comment by sigmoidal** [comment]
With Laravel 5.3.1 tree shaking in production works fine. I guess it's time to close this.
