### ISSUE TITLE
Icon Request: new home icon

### ISSUE THREAD

**Issue by Deep1387** [FortAwesome/Font-Awesome#12431]
Hi, is it possible to replicate the same icon as in the link: https://www.flaticon.com/free-icon/home-button_9282 for a new home icon without the background circle?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1397, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
