### ISSUE TITLE
Icon request: fa-save-with-arrow-right

### ISSUE THREAD

**Issue by Naicos** [FortAwesome/Font-Awesome#12446]
I am looking for a Save (diskette) with an arrow next to it to show save and send
instead of only save.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please consider the stacking feature to implement this:

Docs: https://fontawesome.com/how-to-use/svg-with-js#layering
Example: https://jsfiddle.net/vLae8ted/86/

Ref: #1181

**Comment by sensibleworld** [comment]
We have this icon now: https://fontawesome.com/icons/floppy-disk-circle-arrow-right?s=solid&f=classic
