### ISSUE TITLE
Issue with sports icons?

### ISSUE THREAD

**Issue by michealjroberts** [FortAwesome/Font-Awesome#12441]
Not sure if it is a known issue, but a number of the sports icons are coming back (!)

**Comment by michealjroberts** [comment]
Coming back with (i) - I’ve copied directly from the website for the icons I want, so tennis-ball etc etc 

I re-downloaded 5.0.4, but still nothing. I’ve checked and I have all four packages etc all other icons work fine.

**Comment by michealjroberts** [comment]
(!) (?) flashing

**Comment by tagliala** [comment]
@michealjroberts is this about Font Awesome Pro?

**Comment by michealjroberts** [comment]
Ahhh ok - I only have the option to download up to 5.0.4

**Comment by michealjroberts** [comment]
Where can I download the latest version?

**Comment by tagliala** [comment]
www.fontawesome.com or

https://github.com/FortAwesome/Font-Awesome/releases
