### ISSUE TITLE
Icon request: icon-form

### ISSUE THREAD

**Issue by naluoli** [FortAwesome/Font-Awesome#12465]
### What can it be used for?

help with design aspects of filling out a form, can be used as a form, or choice or selection

### Example image (optional)

![image](https://user-images.githubusercontent.com/36716550/36702563-70bb60f8-1b0c-11e8-93f7-9044c69245c9.png)

### Icon request checklist

- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
https://fontawesome.com/icons/list-alt?style=solid should fit the use case
