### ISSUE TITLE
Q: How to build custom SVG/JS library with Rollup

### ISSUE THREAD

**Issue by nwpappas** [FortAwesome/Font-Awesome#12477]
I am trying to build a smaller [SVG/JS library](https://fontawesome.com/how-to-use/svg-with-js) using FA5's [npm packages](https://fontawesome.com/how-to-use/use-with-node-js). I can build the library, but am unsure how to automatically parse when the library is imported.

I'm starting off simple. My entry point is the following, and I use Rollup to build.

```javascript
import fontawesome from '@fortawesome/fontawesome';
import fasCoffee from '@fortawesome/fontawesome-free-solid/faCoffee';

fontawesome.library.add(fasCoffee);

// tried with, and tried without
//fontawesome.dom.i2svg();

export default fontawesome;
```

The package builds, but when I include it in my HTML the icons are not automatically parsed. I have to go to the console and [manually access the API](https://fontawesome.com/how-to-use/font-awesome-api):

```javascript
MyFA5.dom.i2svg()
```

Any coffee cups instantly appear at this point.

How do cause my bundle to automatically parse the icons when it is included in an HTML `script` tag?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not having this issue, but I'm not using Rollup to build the bundle.

@robmadole any suggestion here?

**Comment by nwpappas** [comment]
Here is my `rollup.config.js` file, if useful:

```javascript
import buble from 'rollup-plugin-buble';
import commonjs from 'rollup-plugin-commonjs';
import { minify } from 'uglify-es';
import resolve from 'rollup-plugin-node-resolve';
import uglify from 'rollup-plugin-uglify';

const defaultPlugins = [
  buble({
    exclude: 'node_modules/**',
    objectAssign: 'Object.assign'
  }),
  resolve({
    jsnext: true,
    module: true
  }),
  commonjs()
];

export default [
  {
    input: './index.js',
    output: [
      {
        file: './dist/myfa5-icons.es.js',
        format: 'es',
        sourcemap: false
      },
    ],

    plugins: [
      ...defaultPlugins,
    ]
  },
  {
    input: './index.js',
    output: [
      {
        name: 'MyFA5Icons',
        file: './dist/myfa5-icons.js',
        format: 'iife',
        sourcemap: false
      },
    ],

    plugins: [
      ...defaultPlugins,
    ]
  },
  {
    input: './index.js',
    output: [
      {
        name: 'MyFA5Icons',
        file: './dist/myfa5-icons.min.js',
        format: 'iife',
        sourcemap: false
      },
    ],

    plugins: [
      ...defaultPlugins,
      uglify({}, minify)
    ]
  },
]
```

**Comment by robmadole** [comment]
Hey there,

We don't support this yet and it will be addressed when we work on the subsetter. I'd love to support this now but we need to focus on some other priorities.

Going to close.

**Comment by nwpappas** [comment]
Interestingly, it does appear to work.

Adding `fontawesome.dom.i2svg();` back into my bundle index has mysteriously started to work. I must have tweaked another item or two, but creating a custom bundle with the posted code does appear to work.
