### ISSUE TITLE
Icon request: icon-backup & icon-backup-restore

### ISSUE THREAD

**Issue by jonasarts** [FortAwesome/Font-Awesome#12472]
### What can it be used for?

For backup archive download links, for backup archive upload forms

### Example image (optional)

Use icon-archive or icon-file-archive with an upload / download arrow overlay?
Make it similar to icon-upload and icon-download, but with more 'archive' or 'file' style (instead of the 'server' style in the upload/download icons)

### Icon request checklist

- [pair] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate, only this very old one: https://github.com/FortAwesome/Font-Awesome/issues/1620 not conforming the new icon request format
- [no] I have included at least one example image if it could be helpful (optional)
- [yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld I can't find those two icons

**Comment by sensibleworld** [comment]
Based on the original description, here's what we have:
https://fontawesome.com/icons/folder-arrow-up?f=classic&s=solid
https://fontawesome.com/icons/folder-arrow-down?f=classic&s=solid

But can also be created via the Icon Wizard.
