### ISSUE TITLE
CSS pseudo elements not working as per documentation

### ISSUE THREAD

**Issue by twistedpixel** [FortAwesome/Font-Awesome#12482]
According to the documentation, you should use like this:

```
.selector:before {
    font-family: "Font Awesome 5 Solid";
    content: "\f007";
}
```

However, I get a "missing" icon when using this. I can only get it to work by using:

```
.selector:before {
    font-family: "Font Awesome 5 Pro";
    font-weight: bold;
    content: "\f007";
}
```

Is this a known issue? I couldn't find any relevant issues/comments.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The first approach is correct for the SVG framework

The second one is the way to go for the webfont version, so I suppose you are using the webfont  version

Ref: 

SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
Webfont:  https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Does this help?

**Comment by twistedpixel** [comment]
Crap, my bad - I thought I was in the CSS section in the docs. Feel free to hide this issue and hope nobody else sees it... 😛

**Comment by tagliala** [comment]
Don't worry.

This could be useful for others 👍
