### ISSUE TITLE
How do we know how many new fonts released? (version filter)

### ISSUE THREAD

**Issue by smallersign** [FortAwesome/Font-Awesome#12483]
How do we know how many new fonts released? I don't see any filter for the new icon filter.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I agree on this.

At the moment, there is the changelog: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#change-log

but I also think that a version filter on the docs could be useful for some use cases

**Comment by smallersign** [comment]
But mainly we need to know what the new icon released between version to version that would be great to avoid waste time.

**Comment by cowwebmanager** [comment]
I agree. I opened a duplicate request basically for the same thing - to add the ability to search for icons by version number. This would make it much easier to see the new icons in a release, or go back to see what was released in another version.

If we could search by version, like 5.0.0, or 5.0.13, that would be great!

**Comment by alystair** [comment]
Changelog doesn't actually link to or list the added icons, nor does the site actually provide a concise list...

**Comment by rbirmann** [comment]
Would be nice to have this version number clickable and leading to a subset of the icon gallery with only the icons released in that specific version...

![2018-05-10_1955](https://user-images.githubusercontent.com/39135342/39898246-5665f970-548c-11e8-96ee-421517f536bd.png)

Would be great also if searching for the version number worked....

![image](https://user-images.githubusercontent.com/39135342/39898316-94c3eca4-548c-11e8-815b-f850a66a8325.png)

**Comment by tagliala** [comment]
Please take a look here: #13116

**Comment by talbs** [comment]
Hey, gang. Thanks again for letting us know how important this is. I believe we addressed this in the issue @tagliala mentioned. You can read more at https://github.com/FortAwesome/Font-Awesome/issues/13116#issuecomment-399220456.
