### ISSUE TITLE
5.0.7 desktop fonts not working in Adobe Suite (ligatures are not working)

### ISSUE THREAD

**Issue by WeAreELIC** [FortAwesome/Font-Awesome#12486]
The latest version, 5.0.7, is no longer working in Adobe Illustrator or InDesign (the only 2 apps I've tested). The previous versions were working fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm this, Photoshop works fine and I don't have illustrator and indesign.

Please uninstall all the old fonts and make sure you are installing fonts from `/use-on-desktop` folder

Leaving this open and waiting for other feedbacks

**Comment by TReed21** [comment]
I'm having an issue with 5.0.7 and Adobe as well. Copying the Glyphs works just fine but typing out the names of the icons no longer works. Reverting back to 5.0.6 fixes the issue.

**Comment by tagliala** [comment]
could you please be more specific about the icons? (name and style)

**Comment by tagliala** [comment]
@robmadole @talbs I can confirm this on FA Pro.

Could you please take a look?

PS: please the next time specify that you are using FA Pro

**Comment by TReed21** [comment]
Sure thing, sorry about that. Thanks for the quick response.

**Comment by WeAreELIC** [comment]
Will do, thanks.

**Comment by robalan** [comment]
Not sure if you'd prefer this as a new thread, but I'm also experiencing ligature issues in Sketch 48.2 on Mac OS10.13.3. `shipping` related icons are not converting for me, or rather are converting "ship" but will not convert as new characters are added.

**Comment by tagliala** [comment]
> shipping related icons are not converting for me, or rather are converting "ship" but will not convert as new characters are added.

I suppose that there is no chance for shipping icons to work, because they were introduced in 5.0.7 and on FA 5.0.7 ligatures don't work

**Comment by robmadole** [comment]
We can confirm this and will work on getting a 5.0.8 out as soon as we identify the issue.

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ligatures back to Desktop .otfs in 5.0.7](https://trello.com/c/DppbGuL5/27-add-ligatures-back-to-desktop-otfs-in-507)

**Comment by robmadole** [comment]
We've got the issue fixed and will be cutting a release today.

**Comment by robmadole** [comment]
5.0.8 is now released and should fix this issue

**Comment by WeAreELIC** [comment]
Awesome, thanks! It seems to be working like expected.

**Comment by Coral9** [comment]
Hi All, version 5.0.10 Pro is not working in InDesign on Mac, do you have similar experience?

**Comment by tagliala** [comment]
@Coral9 please give a try to 5.0.12 and if that doesn't work please open a new issue in the Pro repository

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
