### ISSUE TITLE
Ligatures for FontAwesome Pro do not work in Sketch

### ISSUE THREAD

**Issue by ima-tech** [FortAwesome/Font-Awesome#12485]
I feel like I'm going crazy. Ligatures work for FontAwesome 5 Free, FontAwesome 5 Brands but not for Pro.... I installed them properly and can see the fonts in Font Book and in Sketch. But, the text doesn't change to the icon... 

Anyone had this issue?

**Comment by nickfedoroff** [comment]
@ima-tech , How did you resolve this? I'm having the same issue. Ligatures work in sketch one computer, but not the other.

**Comment by tagliala** [comment]
Please make sure you are using FA5 5.0.8 on both machines
