### ISSUE TITLE
Modify Flipboard icon?

### ISSUE THREAD

**Issue by sunipeyk** [FortAwesome/Font-Awesome#12481]
You added the icon depends on Flipboard brand guidelines, but they changed it. A minor change but changed anyway. See https://about.flipboard.com/brand-guidelines/ 
Are you going to modify it?

![logomark1-550x380](https://user-images.githubusercontent.com/9592953/36787691-0781a9e4-1c9c-11e8-8caf-9676b5b56c71.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this.

> Are you going to modify it?

Will definitely do that

**Comment by talbs** [comment]
Thanks for the heads up @sunipeyk and @tagliala. We'll get this work into the next release. 😄

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deal with Flipboard icon](https://trello.com/c/9FASxbI4/35-deal-with-flipboard-icon)

**Comment by talbs** [comment]
Hey, @sunipeyk. Apologies for the radio silence. This update was released a bit ago and the Flipboard brand icon is now current with the official guidelines - https://fontawesome.com/icons/flipboard?style=brands. Let us know if you spot anything else that needs some polish and dusting. 😄
