### ISSUE TITLE
The document is out of sync with the pro version.

### ISSUE THREAD

**Issue by brianmhunt** [FortAwesome/Font-Awesome#12489]
It's brutally unclear how to use fontawesome pro from npm, with most relevant information appearing to be either wrong or missing entirely.

Having followed the instructions to install pro version from here: https://fontawesome.com/how-to-use/js-component-packages :

```
$ yarn list | grep @fortawesome                                             
├─ @fortawesome/fontawesome-common-types@0.1.3
├─ @fortawesome/fontawesome-pro-light@5.0.7
│  └─ @fortawesome/fontawesome-common-types@^0.1.3
├─ @fortawesome/fontawesome@1.1.4
│  └─ @fortawesome/fontawesome-common-types@^0.1.3
```

The `README.md` in `node_modules/@fortawesome/fortawesome-pro-light` says to read:

1. https://fontawesome.com/get-started/svg-with-js 
1. https://fontawesome.com/how-to-use/svg-with-js
1. https://fontawesome.com/how-to-use/font-awesome-api

Starting with number 1.

- It says to download Font Awesome Pro via a link on the page but that undermines using a package manager like npm, and in any case doesn't contain the pro light version
- It says a file called `fontawesome-all.js` loads all the base features but `find . | grep -i fontawesome-all.js` in `node_modules/@fortawesome` yields no files
- There's no apparent other indication of any other files or sources of information
- The documentation references `fa-v4-shims.js` but  `find . | grep -i shim` in `node_modules/@fortawesome`  yields no files

Then if one turns to number 2 hoping to find some additional help, but that seems to be at the usage stage.

The third, `font-awesome-api` link, yields no useful information on setup/installation.

Perusing all the packages in the `@fortawesome` npm scope yields no indication of `fontawesome-all.js` or `v4-shims.js`. One does find files at https://github.com/FortAwesome/Font-Awesome/tree/master/svg-with-js/js, but there's no indication of how to install it via npm, whether it's necessary, or how to integrate it into the npm setup.

Purely by guessing on convention, I appear to have loaded some things by including:

```
node_modules/@fortawesome/fontawesome/index.js
node_modules/@fortawesome/fontawesome-pro-light/index.js
```

Expecting the docs here https://fontawesome.com/how-to-use/use-with-node-js to be of help, you'd extrapolate and guess this would work:

```
fontawesome.library.add(window['fontawesome-pro-light'])
```

You'd be wrong.  That errors with

> Uncaught TypeError: Cannot read property 'icon' of undefined

I browsed a dozen relevant questions on StackOverflow, none of which offered any useful information.

So the obvious questions are:

1. How do you load the pro icons from npm?
2. How do you shim for version 4 with the version from npm?

**Comment by sgwatgit** [comment]
I believe what you actually want is https://fontawesome.com/how-to-use/use-with-node-js

I also had a hard time finding this.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for you feedback.

There is something going on with NPM, please take a look at: https://github.com/FortAwesome/Font-Awesome/issues/11895#issuecomment-368647771

Maybe your feedback could be useful to @mlwilkerson

**Comment by mlwilkerson** [comment]
Oh my, @brianmhunt for the hassle you're experiencing. That's the sort of confusing we've been working to clean up with our forthcoming 5.1 release. As @tagliala mentioned, I'm in the process of re-working those packages, to be followed by a re-working of the corresponding documentation, in the hopes of things being less brutal in the future—or even perhaps pleasant.

So your feedback above is already helpful. But it would also be helpful if you could review this and let me know how this plan might have made things easier for you (it's not the full documentation, mind you, just the skeleton of the new packaging plan:
[Feedback Request: Packaging Font Awesome 5.1](https://paper.dropbox.com/doc/Feedback-Request-Packaging-Font-Awesome-5.1-6GlrjtIH851nc2TN71gno?_tk=share_copylink)

As for your specific concern about using Pro from npm. You've got the pro npm installed it seems. So now it's just about getting that icon package imported properly and added to the library. 

I spun up [this little demo repo on GitHub](https://github.com/mlwilkerson/FontAwesome-Pro-NPM-Use-Demo) to show one way to do this, using Rollup to bundle things, if you're trying to add the whole icon pack to the library.

**Comment by mlwilkerson** [comment]
Related thought: I can't tell for sure what you meant by 
> I appear to have loaded some things by including:
```
node_modules/@fortawesome/fontawesome/index.js
node_modules/@fortawesome/fontawesome-pro-light/index.js
```
But I infer that you mean that you loaded them by putting something like this in your html:
```
<script src="node_modules/@fortawesome/fontawesome/index.js"></script>
<script src="node_modules/@fortawesome/fontawesome-pro-light/index.js"></script>
<script type="text/javascript">
  fontawesome.library.add(window['fontawesome-pro-light'])
</script>
```
Is that close?
If so, I could make a few more comments that might shed some light on why this didn't work as you might have expected, how it was _really_ close, how I might recommend doing it instead, and how some of this will change in 5.1...if you're interested.

**Comment by brianmhunt** [comment]
Great feedback, thanks @mlwilkerson !

I'm so glad to see this issue on the radar.

Our use case is a full-blown web-application, so we're on the "deep" end of the complexity scale.

The demo on GitHub is helpful.  It'd be good to see a CommonJS equivalent (mostly just for comfort).

We load our libraries by concatenating them into a single e.g. `libs.js` and then loading that.  It looks something equivalent to this:

```
cat node_modules/@fortawesome/fontawesome/index.js \
  node_modules/@fortawesome/fontawesome-pro-light/index.js > font-libs.js
```

With `font-libs.js` being imported via a `<script>` tag.

We're using Knockout.js (I'm a maintainer of KO, incidentally).   Many of the icons are chosen programatically so we'd just include the whole library of icons.

I read through the packaging feedback on DropBox.  I don't see anything wrong with the reworking of the packages, but I feel it doesn't address the core concerns raised here, and there's nothing indicating how those concerns will be addressed from that.

From an intuitive perspective of what I'd expect as a user, when I downloaded the `@fortawesome/fontawesome-pro-light` I expected to find:

1. a `README.md` with instructions (e.g. linking to a GitHub repo like the one here) on how to use the fonts
  a. by including css / woff(2)
  b. by including javascript + svg
2. files that "just work" e.g. `src/all.js` that when included just makes the fonts happen - or - needs to be activated with some vanilla JS configuration options documented in the README.
3. Shimming for v4 should be an API call when fontawesome is included or a separate package with its own README. When the web pages refer to e.g. the v4-shim, and it's not in the pro version, it's not clear if I need to include a link to an external CDN (which we can't always do e.g. intranets) to get v4 support (and we need v4 backwards-compat because we have thousands of references to the v4 icons and it'll take years to clean them up).
4. Relatedly, I'd expect the fontawesome pages to either be correct or defer to the README for the pro versions.

Generally speaking, I'd stack the relevant docs in the README and defer there for npm users.  It'd be good to note that on the website.  Links to sample projects are a big bonus — GitHub and CodePen seem to be good choices.

Which is to say that the proposed changes to the package management are more structural, whereas the problems I've experienced related to the above seems to be content.

On the second comment re. the error experienced, that looks to still be a problem.  The libs are included as-above, and it seems to work correctly when I run (from the console):

```
>>> light = window['fontawesome-pro-light']
>>> fontawesome.library.add(light.default)
>>> fontawesome.dom.i2svg()
```

Which is perfectly fine — but should be documented.  However, this leads to the next couple issues in using FA5, being:

1. it appears that i2svg needs to be called every time an icon changes
2. i2svg destroys DOM elements (that may be bound to knockout bindings and otherwise change dynamically).  A *very* common use-case in the knockout world is e.g.

```html
<i class='fa {{ complete ? "fa-check" : "fa-circle" }}'></i>
```

where the ternary expression in the mustaches basically chooses the icon depending on the value of `complete`.  Here's a CodePen demonstrating this canonical form: https://codepen.io/brianmhunt/pen/rJPoLz

Running `i2svg` destroys the bound logic.  At the least, for FA5 to work, it would have to non-destructively interact with the DOM.  (A knockout binding to do this may be fairly trivial to revise when the DOM is modified, but you'd only want to run `i2svg` for children of a given node — not the whole DOM, that'd be a performance disaster; in any case the `i` node ought to be preserved).

Of course, none of that is necessary with CSS font-icons.

As mentioned, we're on the "deep" end of the complexity spectrum here, but I hope this helps give some illumination to the types of problems experienced so far.

**Comment by brianmhunt** [comment]
@mlwilkerson Sorry to pester — Any updates on this?  As you can glean from the linked issue, an underlying issue (DOM clobbering by FA) is being reported by Knockout users.  Cheers.

**Comment by brianmhunt** [comment]
... this library appears to remain unusable.

**Comment by mlwilkerson** [comment]
Hi @brianmhunt. I'm sorry to have lost track of this conversation.

So, yes, by default Font Awesome SVG with JavaScript will _replace_ the DOM element (the `<i>`) with the `<svg>`. But this is configurable. You can use the `nest` option instead, which will preserve the `<i>` to which KO is bound, and will render the `<svg>`s as child elements.

This CodePen is a fork of your demo (thanks for such a great reproduction), and demonstrates how you could configure with the `nest` option:
https://codepen.io/fontawesome/pen/yqoemp

You'll find documentation about what else can be configured, and other ways to set the configuration, on our web site here:
https://fontawesome.com/how-to-use/with-the-api/setup/configuration

NOTE: We had a pretty major overhaul on our docs within the past month or so. I hope you'll find it to be an improvement. Glad to hear the feedback, either way, though.

**Comment by brianmhunt** [comment]
Awesome, thanks @mlwilkerson — Will take a look!  🍻

**Comment by brianmhunt** [comment]
I just had a chance to have a look, and the organization of the project is now markedly better.  Making this work is now straightforward, meaning I think it's safe to close this.

Thanks & cheers
