### ISSUE TITLE
Icon request: icon-crane (building construction)

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12499]
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I need to find the place where I can order special construction vehicles._ 

### Example image 
![icon-crane](https://user-images.githubusercontent.com/30906472/36934563-e40add44-1eeb-11e8-94a9-d59012ce13ae.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes, but
	#4084 
	wasn’t a right way request** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by willidh** [comment]
+1

**Comment by larssielaff** [comment]
+1

**Comment by waveminded** [comment]
+1 or some sort of equipment icon such as a dozer, back hoe, earth mover

**Comment by Giplo** [comment]
+1

**Comment by SarahRathUX** [comment]
I would also like the crane icon.

**Comment by digittal** [comment]
+1

**Comment by jbnv** [comment]
Looking at the existing "construction" icons, none of them really connote building from scratch like a crane would. I'm actually struggling in choosing icons to represent "construction" and "repair" right now.

**Comment by sowjanya1409** [comment]
no i want as it is in above image here again for your reference i am uploading an image
![Capture](https://user-images.githubusercontent.com/54360222/90040650-d527d380-dce5-11ea-84fc-0727a0003e1b.png)

**Comment by ISSTJ** [comment]
+1 
We would love to have a tower crane, a crawler crane and lifting plattforms in font awesome. They would be a great addition to the logistics section.

**Comment by ISSTJ** [comment]
@tagliala can you assign "Construction" as category?

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🏗 [U+1F3D7](https://emojipedia.org/emoji/%F0%9F%8F%97/) Building Construction
Also known as `Crane`.

**Comment by LOGiST-fr** [comment]
Hello, MP to get SVG code for pro icons 

![image](https://github.com/FortAwesome/Font-Awesome/assets/159033024/5baeb3b4-7ef2-4de7-9fea-f52cac1f9760)
