### ISSUE TITLE
Stars empty and filled should be accessible without loading second font

### ISSUE THREAD

**Issue by Acts7** [FortAwesome/Font-Awesome#12495]
What is the logic behind star empty and star full being of different fonts?
I get the pro / paid version. (I am a kickstarter backer and have purchased business license etc)
But a star that is empty has different meaning if it is "active" or "inactive"
I'd really like to see both filled and empty stars available without loading a second font.
THoughts?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I'd really like to see both filled and empty stars available without loading a second font.

At the moment you can use the svg framework + node.js + tree shaking: https://fontawesome.com/how-to-use/use-with-node-js

I think this will be officially possible with the desktop subsetter tool, which is [not ready yet](https://fontawesome.com/updates)

Another chance is to build a custom webfont with other online services, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

@robmadole any thoughts?

**Comment by robmadole** [comment]
@tagliala you nailed all of the points :) no additional thoughts.

**Comment by tagliala** [comment]
@Acts7

I'm going to close here but feel free to comment
