### ISSUE TITLE
Icon request: graphql

### ISSUE THREAD

**Issue by blackxored** [FortAwesome/Font-Awesome#12508]
### What can it be used for?

Technical blogs, documentation, etc.

### Example image (optional)

![](http://graphql.org/img/logo.svg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (other than my previous request)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi @blackxored 

#12048 is fine. Thanks for filling out the icon request template, but let's use #12048

#12048 has 4 upvotes and it's perfectly fine. Also, the issue template was not available on Jan, 7th.
