### ISSUE TITLE
Icon request: icon-construction-material

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12500]
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I need to find where I can order new construction material._ 

### Example image 
![icon-construction-material](https://user-images.githubusercontent.com/30906472/36934631-0d5ed398-1eed-11e8-9eab-3f11f573a5ec.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by tagliala** [comment]
Any single color, 16px icon size suitable example?

**Comment by tablatronix** [comment]
Maybe a pile or box with Stacked circles.

https://thenounproject.com/search/?q=Pile&i=765200

**Comment by willidh** [comment]
+1

**Comment by larssielaff** [comment]
+1

**Comment by melksedeque** [comment]
+1
