### ISSUE TITLE
Icon request: icon-wheelbarrow or icon-pushcart

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12501]
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I can find the number of existing wheelbarrows on building sites._ 

### Example image 
![icon-wheelbarrow or icon-pushcart](https://user-images.githubusercontent.com/30906472/36934650-65987b18-1eed-11e8-8ade-d1a2f33e19f5.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes, but
	#11075
	wasn’t a right way request** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by tagliala** [comment]
Hi again,

let's use #11075 for the same reasons as https://github.com/FortAwesome/Font-Awesome/issues/12504#issuecomment-370148744

**Comment by larssielaff** [comment]
+1
