### ISSUE TITLE
Icon request: icon-lorry

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12502]
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I can easily find where can I order lorries._ 

### Example image 
![icon-lorry 1](https://user-images.githubusercontent.com/30906472/36934705-e4e1b66e-1eed-11e8-869c-a01e9abe605d.png)
![icon-lorry 2](https://user-images.githubusercontent.com/30906472/36934706-e6af6b80-1eed-11e8-82c0-98205532614e.png)
![icon-lorry 3](https://user-images.githubusercontent.com/30906472/36934707-e81bce28-1eed-11e8-95bc-ea8bed1aafa3.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes, but
	#711 was closed
	#543 is not what I need** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by stefanmerkel** [comment]
+1

**Comment by willidh** [comment]
+1

**Comment by larssielaff** [comment]
+1

**Comment by dflock** [comment]
There's already a [truck icon](https://fontawesome.com/icons/truck), in the [logistics pack](https://fontawesome.com/icons?c=logistics)

**Comment by TexasSwede** [comment]
@dflock : That is a covered truck, there are needs for other kinds of trucks, like flatbed trucks, garbage trucks and even 18-wheelers. For logistics they are all needed, since they are used for different things.

**Comment by dflock** [comment]
I guess so. I think those will all need to be separate icon requests,
though.

**Comment by sensibleworld** [comment]
Here are a few options that may cover it. https://fontawesome.com/icons/truck-container?style=solid
https://fontawesome.com/icons/truck-moving?style=solid
