### ISSUE TITLE
Pro webfonts only have 717 characters

### ISSUE THREAD

**Issue by alawson107** [FortAwesome/Font-Awesome#12505]
I purchased version 5.0.8 Pro yesterday for use with Bootstrap but there are only 717 characters in all of the webfont files. My understanding was there should be 2,481. They are all listed with unicodes in the css file but are not in the woff2 file (fa-amazon, fa-adversal... many more): 

![image](https://user-images.githubusercontent.com/3688129/36934749-0d58387a-1ebc-11e8-8488-c6cd862fe9e4.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

717 * 3 styles + 330 brands (separate font file) = 2,481

Hope it helps

Closing here
