### ISSUE TITLE
Icon request: icon-turnstile

### ISSUE THREAD

**Issue by YlloNieR** [FortAwesome/Font-Awesome#12503]
### What can it be used for?
**On websites or webapps which deal with construction buildings/ building sites, logistics & management of that.**  
For example:
_As a user, I can easily find the part of the website or wepapp which is about access control._ 

### Example image 
![icon-turnstile](https://user-images.githubusercontent.com/30906472/36934742-4226e6c8-1eee-11e8-9935-32cd5de18ddb.png)

### Icon request checklist
> This is a single icon or matched
	**single**

> The title starts with "Icon request: " and is followed by the requested icon name 	
	**Yes**

> I have [searched for existing issues] and to the best of my knowledge this is not a duplicate
	**Yes, but 
	#8384
	wasn’t a right way request** 

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)	
	**Yes**

**Comment by tagliala** [comment]
Hi again,

let's use #8384 for the same reasons as https://github.com/FortAwesome/Font-Awesome/issues/12504#issuecomment-370148744

**Comment by larssielaff** [comment]
+1
