### ISSUE TITLE
Icon request: tide-icon

### ISSUE THREAD

**Issue by mtpultz** [FortAwesome/Font-Awesome#12511]
### What can it be used for?

Set of icons indicating high and low tide for weather-related applications.

### Example image (optional)

![image](https://user-images.githubusercontent.com/599498/36943562-cb6bfd56-1f48-11e8-92c1-ee328f201094.png)

**Comment by pjsmits** [comment]
+1

**Comment by aethior** [comment]
Hi @mtpultz,

[fa-water-arrow-up](https://fontawesome.com/icons/water-arrow-up) and [fa-water-arrow-down](https://fontawesome.com/icons/water-arrow-down) icons were added in v5.5.0.

Regards.

cc/ @tagliala
