### ISSUE TITLE
Icon request: EyeEm

### ISSUE THREAD

**Issue by AntoniniP** [FortAwesome/Font-Awesome#12516]
[https://www.eyeem.com](https://www.eyeem.com)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2346, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
