### ISSUE TITLE
Icon request: fa-google-pay

### ISSUE THREAD

**Issue by boogsau** [FortAwesome/Font-Awesome#12519]
Google recently released Google Pay, a merge of Android Pay and Google Wallet. I assume this would replace the Google Wallet icon. This would go alongside fa-apple-pay and fa-amazon-pay

![google-pay](https://user-images.githubusercontent.com/8464333/36956670-6b266b64-207b-11e8-96c0-665a1baa877b.png)

https://pay.google.com/about/

**Comment by erx3** [comment]
Any updates on this icon?

**Comment by brucerpdx** [comment]
What amuses me is that not even the [competing font package] that is specifically for the payments industry doesn't have G Pay either. 

Are we Android users so minimal? 😢

**Comment by joeybab3** [comment]
+ 1, I have a number of payment icons on my site all in font awesome and would love to have them all be similar...

**Comment by jimrapc** [comment]
+1 Apple Pay is here, but I am looking for Google Pay too

**Comment by rmcfadzean** [comment]
+1 again. Would love to see this added.

**Comment by KlutzyBubbles** [comment]
+1 Could we also see this in the form of cc-google-pay?

**Comment by Niehaus1301** [comment]
+1

**Comment by Singe19** [comment]
+1 Surely this will be released soon??

**Comment by m4rcosx** [comment]
+1

**Comment by t-bo** [comment]
Still don't want to add it?

**Comment by sanek4life** [comment]
+1

**Comment by ratajs** [comment]
+1

**Comment by JustinObm** [comment]
Google Pay SVG:
https://pay.google.com/about/static_kcs/images/logos/google-pay-logo.svg

**Comment by OlleNeiman** [comment]
+1

I would really appreciate this being included.

**Comment by Smexhy** [comment]
a bit sad that this one is left out for 2 years

**Comment by parfilov** [comment]
+1

**Comment by LeaTark** [comment]
+1 also

**Comment by tagliala** [comment]
Hi,

icon released in 5.13.1

https://fontawesome.com/icons/google-pay?style=brands
