### ISSUE TITLE
Icon request: buoy-icon

### ISSUE THREAD

**Issue by mtpultz** [FortAwesome/Font-Awesome#12512]
### What can it be used for?

Buoy station for weather and oceanic observational applications.

### Example image (optional)

![image](https://user-images.githubusercontent.com/599498/36943611-411e60b6-1f49-11e8-8a92-6a8c7ac0813c.png)

**Comment by pjsmits** [comment]
+1

**Comment by xmuskrat** [comment]
+1

**Comment by RonSchofield** [comment]
+1

**Comment by aethior** [comment]
@tagliala `maritime (category)` and `map (category)` labels for this request?

**Comment by aethior** [comment]
Hi @mtpultz,

This icon was added in v6.2.1.
Check https://fontawesome.com/icons/buoy

Regards.

cc/ @tagliala
