### ISSUE TITLE
Rectangle shown until the font is loaded

### ISSUE THREAD

**Issue by SuperPat45** [FortAwesome/Font-Awesome#12527]
WebFonts Icons are replaced by rectangles while the font is not loaded.

This may be fixed for a short period after page load in latest browsers versions (except IE/Edge) by adding the new font-display property in the font face:
`font-display: optional;`
https://css-tricks.com/font-display-masses/
https://developer.mozilla.org/en-US/docs/Web/CSS/%40font-face/font-display

**Comment by tagliala** [comment]
Hi, sorry for the late reply.

The default `font-display` property value, `block`, is the best option for icon fonts. You can customize the option in the latest version of Font Awesome if you use a Sass or LESS pre-processor

Hope it helps

Closing here

**Comment by tagliala** [comment]
Ref: #14387
