### ISSUE TITLE
Clipboard Icon not loading through css

### ISSUE THREAD

**Issue by Emarkable** [FortAwesome/Font-Awesome#12528]
Clipboard icon is not loading when added through css.

**Implementation method used:** 
fontawesome-all.min.js (Font Awesome Pro 5.0.8)

CSS code:
`.btn-apply::before{
	font-family:FontAwesome;
	content: "\f328";
}`

most of the other icons are loading without any issues.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

 the first error I can spot is the `FontAwesome` family name. It is not supposed to be like that.

In your use case (FA5 Pro) It should rather be `Font Awesome 5 Solid` or `Font Awesome 5 Regular`

Please take a look at the docs:

SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
CSS: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Working fiddles
SVG: https://jsfiddle.net/tagliala/vLae8ted/68/
CSS: https://jsfiddle.net/tagliala/qq2eLxo1/31/
