### ISSUE TITLE
Typo in clipboard https://fontawesome.com/icons/info-circle?style=solid

### ISSUE THREAD

**Issue by Crytiqal** [FortAwesome/Font-Awesome#12529]
The clipboard code has a typo

`<i class="fas fa-info-circle"></i>`

It should be 
`<i class="fa fa-info-circle"></i>`

obviously 👍

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That is not a typo. The `s` stands for `solid`.

`fa` is a deprecated alias for `fas` and it will be removed in FA6

Refs: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
