### ISSUE TITLE
Possible to add Class ('fas', 'fal', etc.) in icons.yml file?

### ISSUE THREAD

**Issue by varundbest** [FortAwesome/Font-Awesome#12522]
It would be great if you guys could add/allow to add the Class or any discreet property that would give away class in the icons.yml.
Because currently there is no way to what what class the icons belongs to without manually checking for it.
For our Issue : https://github.com/farbelous/fontawesome-iconpicker/issues/58
What I'm doing with grunt is : 
Downloading the icons.yml while while building the project to keep our project automatically in sync with FA icons and have been able to distinguish 'fas' and 'fab' by categories but I'm helpless to distinguish 'far'. Is there any alternate file available?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I'm helpless to distinguish 'far'.

The .yml file contains the `styles` property with a list of all available styles

Example: https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml#L44

Does that help?

**Comment by varundbest** [comment]
Actually it does! Thank you!

**Comment by varundbest** [comment]
@tagliala Just wondering, is there any such list for Pro fonts as well?

**Comment by tagliala** [comment]
@varundbest yes, there is 👍

**Comment by varundbest** [comment]
@tagliala Where would that be? Or Does does this list contain pro icons as well? (Not sure I found any though)

**Comment by tagliala** [comment]
@varundbest are you a Pro Backer?

If yes, you can check by yourself in the Pro repository

If you aren't, it does not report if an icon is part of the free repo or it isn't. Imagine it as a comprehensive list of all icons with `solid`, `regular`, and `light` in `styles`.

You can write your own parser to parse them both and mark icons as "free" if they are in both files

**Comment by varundbest** [comment]
@tagliala I'm not a Pro backer. Well, even if [its just for free icons](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml) then also I would be fine it seems. So I'd assume a list of pro fonts isn't available?

**Comment by tagliala** [comment]
> So I'd assume a list of pro fonts isn't available?

We have the very same file (`icons.yml`) which containis a list of all FA5 Pro icons

**Comment by varundbest** [comment]
But that would be a private repo I'd assume? Thanks for the help btw!

**Comment by tagliala** [comment]
Yes, it is a private repo: Font Awesome 5 Pro is a commercial software.

If you need an up-to-date `icons.yml` with all the pro icons to provide a service to your FA5 Pro customers, please drop a line at hello@fontawesome.com

Please also link to this issue

**Comment by joshualyon** [comment]
@tagliala it seems as though the icons.yml in the Font-Awesome-Pro repository hasn't been updated for 7+ months. It looks like it was last updated as of 5.0.0-rc5 so a number of icons are missing from the yml file. Is this the icons.yml for Pro being stored in a different location now that 5.1.0 has been officially released? Or is the file just outdated?
