### ISSUE TITLE
Error in chevron-left code

### ISSUE THREAD

**Issue by drinu276** [FortAwesome/Font-Awesome#12532]
On the fontawesome website the code for chevron-left is listed as:

`<i class="fas fa-chevron-left"></i>`

however it should be

`<i class="fa fa-chevron-left"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That is not a typo. The `s` stands for `solid`.

`fa` is a deprecated alias for `fas` and it will be removed in FA6

Refs: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
