### ISSUE TITLE
Icon request: icon-evernote

### ISSUE THREAD

**Issue by brandonb927** [FortAwesome/Font-Awesome#1253]
We have built a very popular Evernote blogging platform called [Postach.io](http://postach.io) and we are in dire need of a nice Evernote @font-face icon! We use FontAwesome for all our themes because of the simplicity to integrate and the consistent updates :)

It would be amazing if we could have an "icon-evernote" based on the [Evernote elephant logo](http://evernote.com/media/img/logos/evernote_logo_center_4c-lrg.png).

Thanks!

Edit: I've since moved on from Postach.io, however I'm sure they wouldn't mind getting this into the icon pack!

**Comment by BassemN** [comment]
+5

**Comment by berendt** [comment]
+1

**Comment by leo-o** [comment]
+1

**Comment by daveismyname** [comment]
+1

**Comment by jacoblangston** [comment]
+1

**Comment by heitortsergent** [comment]
+1

**Comment by ctraganos** [comment]
Yes! You can grab the vector art for our elephant at http://en.wikipedia.org/wiki/File:Evernote_logo.svg
Let me know if you need any help, we'd love to share this with our developers :+1: 
@ctraganos // @evernote_dev

**Comment by SammyHerring** [comment]
+1

**Comment by brianrhea** [comment]
+1

**Comment by brendonseesdragons** [comment]
+1

**Comment by lucasblackhurst** [comment]
+1

**Comment by acloudburo** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by boylett** [comment]
+1

**Comment by the1994** [comment]
+1

**Comment by SamKO91** [comment]
+1

**Comment by lzilioli** [comment]
+1

**Comment by MarynaSukhomlynova** [comment]
+1

**Comment by sabgaby** [comment]
+1

**Comment by lucasroselli** [comment]
+1

**Comment by JimmyLv** [comment]
+1

**Comment by EdyHinzen** [comment]
+1
see https://commons.wikimedia.org/wiki/File:Evernote.svg for vector graphic

**Comment by A5308Y** [comment]
+1

**Comment by dmitriyfourier** [comment]
+1

**Comment by brandonb927** [comment]
To the `+1`'ers, please refrain from doing so and instead use the Reactions feature on the original comment please! It's better for everyone :)

**Comment by ThienNguyenMinh** [comment]
+1

**Comment by k4zzk** [comment]
+1

**Comment by osolano** [comment]
+1

**Comment by vinniejames** [comment]
👍

**Comment by Nirjonadda** [comment]
+1

**Comment by joshpalmeri** [comment]
+1

Any thoughts on this one yet? It's been around for a while :-)

**Comment by sbcr8ive** [comment]
+1

**Comment by thanhtruong0315** [comment]
+1

**Comment by tcffo** [comment]
+1

**Comment by jculverwell** [comment]
+1

**Comment by danpezzin-social** [comment]
+1

**Comment by piotrpliszko** [comment]
+1

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/evernote

Thanks for the patience and for continuing to vote this up! :smile:
