### ISSUE TITLE
No icons in the on-the-desktop oft files on Macos 10.13.3

### ISSUE THREAD

**Issue by BagelTheKid** [FortAwesome/Font-Awesome#12531]
### Describe the problem

I am trying install the 5.0.8 Font Awesome for some desktop use, primarily some system info desktop displays. When I open up the Free-regular-400 otf, I see no icons. 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/13815614/37054029-62cc63b0-2143-11e8-9288-f6a0d54ae40f.png">

The same happens with the other otfs.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/13815614/37054074-7f56446a-2143-11e8-9e79-62e3303d6199.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/13815614/37054098-89bf165c-2143-11e8-99ca-c916e39ce0c1.png">

I'm using Font Book to open them.

### What did you expect?

There should be the icons in the otfs.

### What version and implementation are you using?

Version: 5.0.8
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

### Reproducible test case

- Download 5.0.8 zip
- Extract the zip archive
- Open the otfs in the on-the-desktop folder with Font Book

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is not a bug, Font Awesome is actually a Font.

You should see icons in your programs. In example, try to open pages, select font awesome as font and write `user`: you should see characters turning into an icon

Ref: https://fontawesome.com/how-to-use/use-on-desktop

**Comment by BagelTheKid** [comment]
Hi!

Thanks for such a quick reply, seems like I mis-understood how using the fonts on desktop actually worked. Thank you for the clarification.

**Comment by tagliala** [comment]
you're welcome
