### ISSUE TITLE
Backward compatibility issue

### ISSUE THREAD

**Issue by dvdnhm** [FortAwesome/Font-Awesome#12536]
thanks! for removing some icons (ie: picture) with the new version and not mentioning it anywhere (like bootstrap does in the migration document)

and for backward compatibility, you should add old icons to all versions (regular, bold, light) some icons available only in one type.

I regret that I decided to switch to new version of font-awesome with an "about to launch" project. We need to go through every single page with an icon in it to make sure we have an icon instead of an empty space.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> thanks! for removing some icons (ie: picture) 

All FA4 icons are available in FA5 Free.  `picture-o` is now called `image` and it is available in both solid and regular style on FA5 Free: https://fontawesome.com/icons/image?style=solid

Did you try the Version 4 shim file? It is the fastest way to upgrade from FA4 to FA5 (SVG). However, you may have special needs (pseudoelements), so you may need more changes

> not mentioning it anywhere (like bootstrap does in the migration document)

Changes are mentioned here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Ref: 
- Shims: https://fontawesome.com/how-to-use/upgrading-from-4
- Pseudoelements: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

> and for backward compatibility, you should add old icons to all versions (regular, bold, light) some icons available only in one type.

Please let me know if you find an icon of FA 4.7.0 that is not available in FA5

Sorry about the breaking changes from FA4 to FA5. Reasons are fully explained on the first documentation link that I've provided to you

Hope it helps

Closing here

**Comment by dvdnhm** [comment]
> picture-o is now called image

That was my point.
