### ISSUE TITLE
Icon Request: fa-earn 

### ISSUE THREAD

**Issue by pateskinasy** [FortAwesome/Font-Awesome#12545]
Use case for adding an icon to earn.com https://earn.com 
To be used in personal blogs.
Earn allows responders to get paid to answer to questions. Bloggers may use the mechanism of Earn to get blog readers to pay to contact them.

**Comment by duncand0nuts** [comment]
I just made a site where I would like to use an earn.com fa icon!  if only i could get someone on earn.com to make me one huh?!

**Comment by pateskinasy** [comment]
Earn is dead, so... closing this...
