### ISSUE TITLE
Icon request: cloud-slash

### ISSUE THREAD

**Issue by edave** [FortAwesome/Font-Awesome#12554]
### What can it be used for?

This would be useful for indicating that the device is offline, or some sort of cloud functionality is not available

### Example image (optional)

Along the lines of https://fontawesome.com/icons?d=gallery&q=slash

### Icon request checklist

- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] This is a single icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/18/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by jaminroe** [comment]
Wow cool! Our engineers are using the icon font version right now so that's not an option. I'll save this though, thank you!

**Comment by martinweck** [comment]
+1 yes, please add this icon!

**Comment by lanceplaine** [comment]
+1. Would be great for "Offline" scenarios. `signal-slash` and `wifi-slash` are too specific in my opinion.

**Comment by aethior** [comment]
Hi @edave,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/cloud-slash

Regards.

cc/ @tagliala
