### ISSUE TITLE
//use.fontawesome.com DNS prefetch still exists

### ISSUE THREAD

**Issue by minimaluminium** [FortAwesome/Font-Awesome#12553]
I've been using `fontawesome-all.min.js` previously and removed it. However, all the Font Awesome related embeds still exist like below.

![screenshot 2018-03-09 08 29 44](https://user-images.githubusercontent.com/1418797/37184062-41a6d7aa-2374-11e8-9e08-128f106a349d.png)

![screenshot 2018-03-09 08 29 53](https://user-images.githubusercontent.com/1418797/37184063-41d87490-2374-11e8-89e3-4b5e18d5f1b1.png)

![screenshot 2018-03-09 08 30 24](https://user-images.githubusercontent.com/1418797/37184064-420a047e-2374-11e8-9c7e-f7242c0d6274.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

What is the behaviour you expect?

Is this supposed to stop working?

**Comment by sodbileg** [comment]
Hi there,

Sorry if I wasn’t clear enough. I expect it to not have any Font Awesome related code on the page. However, the page still contains these even if I removed the script I was using.

At first, I thought it was a browser related issue, but it doesn’t seem like. Cleared the cache and tried different browsers, no luck.

**Comment by minimaluminium** [comment]
Oops, replied from another account.

**Comment by tagliala** [comment]
Sorry, I'm still having troubles in understanding this issue

> I expect it to not have any Font Awesome related code on the page

This is code from the old font awesome cdn, it is not related to FA5's `all.js`

> However, the page still contains these even if I removed the script I was using.

Which page? Are you using a CMS? Maybe there is a plugin that is automatically adding those lines and you are not aware of that?

**Comment by minimaluminium** [comment]
Sorry about that. It was from the plugin I was using. If anyone have this issue on their WordPress theme using Kirki, update it to the latest version and good to go.

**Comment by tagliala** [comment]
Glad you solved
