### ISSUE TITLE
Can't install pro files via NPM

### ISSUE THREAD

**Issue by hcker2000** [FortAwesome/Font-Awesome#12550]
I have tried fallowing along with this https://fontawesome.com/how-to-use/use-with-node-js#pro

I have tried via .npmrc

When ever I try any of the following

```
npm i --save @fortawesome/fontawesome-pro-solid
npm i --save @fortawesome/fontawesome-pro-regular
npm i --save @fortawesome/fontawesome-pro-light
```

They all fail to install with a similar error message.

```
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/fontawesome-pro-light@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\webmaster\AppData\Roaming\npm-cache\_logs\2018-03-08T18_10_03_389Z-debug.log
```

Here is the output of the log file.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\webmaster\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   '@fortawesome/fontawesome-pro-light' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session ce15aa825e02cbf7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@fortawesome%2ffontawesome-pro-light 586ms
8 silly fetchPackageMetaData error for @fortawesome/fontawesome-pro-light@latest 404 Not Found: @fortawesome/fontawesome-pro-light@latest
9 verbose stack Error: 404 Not Found: @fortawesome/fontawesome-pro-light@latest
9 verbose stack     at fetch.then.res (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\webmaster\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd E:\Sites\fq2018
11 verbose Windows_NT 10.0.16299
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\webmaster\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "@fortawesome/fontawesome-pro-light"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: @fortawesome/fontawesome-pro-light@latest
17 verbose exit [ 1, true ]
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Did you set your token before?

```
$ npm config set @fortawesome:registry https://npm.fontawesome.com/YOUR-TOKEN
```

You should see your token at https://fontawesome.com/how-to-use/use-with-node-js#pro

PS: **KEEP YOUR TOKEN PRIVATE** do not share it in your logs or bug reports

If this doesn't solve, please open this issue in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro/issues

If you are not able to access to the Pro repository, please make sure you linked your github account to your fontawesome.com account at https://fontawesome.com/account/linked-accounts

Closing here

**Comment by robhadfield** [comment]
I really wish the docs had this - they state:
`$ npm config set @fortawesome:registry https://npm.fontawesome.com/`
not
`$ npm config set @fortawesome:registry https://npm.fontawesome.com/YOUR-TOKEN`

...and it silently fails without the token even if you set the _authToken config.

You also need to restart Terminal. I putting this here for next time I need it 👍

**Comment by AlexWang-16** [comment]
@robhadfield I have the same issue and the command `npm config set @fortawesome:registry https://npm.fontawesome.com/` did not work for me. It's still saying 

> npm ERR! code E404
> npm ERR! 404 Not Found: @fortawesome/fontawesome-pro-solid@https://registry.npmjs.org/@fortawesome/fontawesome-pro-solid/-/fontawesome-pro-solid-5.0.13.tgz

Any ideas?

**Comment by davidjpetersen** [comment]
I'm having the same issue. Thanks for any help!

**Comment by sciyoshi** [comment]
I'm seeing this issue as well as of today. This had previously been working, and my config hasn't changed. I tried changing the config to using `:_authToken` as well, still no luck.

**Comment by tagliala** [comment]
### Pro users

Please refer to: FortAwesome/Font-Awesome-Pro#1118

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by stevewinni-cc** [comment]
I recommend also checking out this upgrade from 5.0 to 5.1

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

Worked for me.

**Comment by carlotapia** [comment]
Also, make sure you're using the **token**, not the **license key**. They look similar and are on the same account page.

This was my mistake 🤦

**Comment by ganmuru** [comment]
Finally this worked for me 
$ npm config set "@fortawesome:registry" https://npm.fontawesome.com/
$ npm config set "//npm.fontawesome.com/:_authToken" <your token>

**Comment by ngerritsen** [comment]
One thing I can add is travis suddenly started using `npm ci` now by default instead of `npm install`. Somehow using config set before doesn't work anymore then so I overridden it with `npm install` again by using:

```
before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_TOKEN
install:
  - npm install
```

**Comment by coreyog** [comment]
Trying to install in a fresh project but I'm getting different feedback from npm than what's listed in this bug.

$ npm version
{
  npm: '7.5.3',
  node: '15.7.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}

$ npm install --save @fortawesome/fontawesome-pro
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/corey.ogburn/.npm/_logs/2021-02-09T19_20_49_435Z-debug.log

I've tried putting my key in the url, using :_authToken, specifying in the .npmrc, but I always get this E401 error.

**Comment by Umer919** [comment]
I Needed This Package in my website, It's a React Based Project, but I also got These Errors when i tried installing them, Is there any other command available for this Package or not ? Need Help 


npm install --save @fontawesome/free-brands-svg-icons

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fontawesome%2ffree-brands-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fontawesome/free-brands-svg-icons@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2021-06-23T12_58_41_784Z-debug.log

**Comment by tagliala** [comment]
@Umer919 please note that the npm scope is `@fortawesome`, you are trying to use `@fontawesome`

fo**R**tawesome is not a typo
