### ISSUE TITLE
Icon VK doesn't work

### ISSUE THREAD

**Issue by Teenie-weenie** [FortAwesome/Font-Awesome#12551]
Hi! I was very happy to find VK icon [https://fontawesome.com/icons/vk?style=brands](https://fontawesome.com/icons/vk?style=brands) in Font Awesome, but unfortunately it doesn't work. 
I use pseudo-element :before to show icons, so I added js scripts at the top of the page 

```
<script>
    FontAwesomeConfig = { searchPseudoElements: true };
</script>
<script defer src="js/fontawesome-all.min.js"></script>
```

CSS

```
.footer .footer-contacts > li > a
{
    font-family: 'RobotoLight';
    position: relative;
    padding: 0 0 0 20px;
    color: #fff;
}
.footer .footer-contacts > li > a > .svg-inline--fa
{
    position: absolute;
    top: 0;
    left: 0;
}
.footer .footer-contacts > li > a:before
{
    display: none;
}
.footer .footer-contacts > li > a.phone:before
{
    font-family: 'Font Awesome 5 Solid';
    content: '\f095';
}
.footer .footer-contacts > li > a.email:before
{
    font-family: 'Font Awesome 5 Solid';
    content: '\f0e0';
}
.footer .footer-contacts > li > a.vk:before
{
    font-family: 'Font Awesome 5 Solid';
    content: '\f189';
}
```

Screenshot
![screenshot_2](https://user-images.githubusercontent.com/6602126/37172840-093723f8-2323-11e8-9208-65f15647c48a.png)
As you could see, phone and email icons work just fine, but I see some strange instead of vk icon.
Is there any way to solve this?

**Comment by Teenie-weenie** [comment]
I have checked, when I use code
`<i class="fab fa-vk"></i>`
it works ok. But I really prefer to use pseudo-elements.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`font-family: 'Font Awesome 5 Solid';` is wrong, please use `Font Awesome 5 Brands`

Ref: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

Hope it helps

Closing here

**Comment by Teenie-weenie** [comment]
Sorry, my mistake. Thanks a lot for answering!

**Comment by tagliala** [comment]
No problem 👍
