### ISSUE TITLE
Add the "database" icon to the "computers" category

### ISSUE THREAD

**Issue by chriskonnertz** [FortAwesome/Font-Awesome#12567]
Hello,

just realized that the "database" icon ( https://fontawesome.com/icons/database ) is not part of the "computers" category.

Please add it to the "computers" category so it is easier to find.

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

**Comment by talbs** [comment]
Hi, @chriskonnertz. Thanks for bringing this to our attention and sorry for the delay. It looks like we fixed this a while ago (in March/April) but never followed up here. `database` in now part of our Computers category - https://fontawesome.com/icons?d=gallery&c=computers. 😄

**Comment by chriskonnertz** [comment]
Awesome

Also thank you for the update.
