### ISSUE TITLE
Update Houzz Icon with new logo

### ISSUE THREAD

**Issue by gmcz** [FortAwesome/Font-Awesome#12561]
House has a new logo and icon: https://www.houzz.com/ideabooks/104891305/list/introducing-the-new-houzz-logo 🎉

**Comment by gmcz** [comment]
Is there an expected timeframe for this issue to be closed? (I have clients asking me when I'm going to fix the logo.) 😬

**Comment by sensibleworld** [comment]
It's available now (in the 5.0.9 release): https://fontawesome.com/icons/houzz?style=brands

**Comment by gmcz** [comment]
Aw yeah! Thanks!
