### ISSUE TITLE
Icon-request: dna icon

### ISSUE THREAD

**Issue by hartly97** [FortAwesome/Font-Awesome#12565]
Several genealogy companies have asked me about genealogy icons. Would be fantastic if some were created.

An icon representing dna is needed. 

Thank you!!!

**Comment by tagliala** [comment]
Already here: https://fontawesome.com/icons/dna?style=solid

**Comment by hartly97** [comment]
Sorry guess I missed it. I wish I could get it to work.

**Comment by tagliala** [comment]
Please make sure you are using the latest version of font awesome (5.0.8)

**Comment by hartly97** [comment]
I am using the current version of font awesome. All the other fonts work for me except for the dna.
