### ISSUE TITLE
Missing fontawesome-all.css on NPM fontawesome-free-webfonts

### ISSUE THREAD

**Issue by Seb33300** [FortAwesome/Font-Awesome#12568]
Hello,

I added [FontAwesome CSS via NPM](https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts) but `fontawesome-all.css` is not provided.

It forces me to include all css files.

Is it normal (maybe I am doing something wrong) ? Or maybe the file is missing?

**Comment by tagliala** [comment]
@robmadole could you please take a look at this?

**Comment by robmadole** [comment]
We’ll be addressing this in 5.1.0 if Font Awesome. This is our top priority right now to get this done.

**Comment by JemiloII** [comment]
It's pretty annoying that the .min versions aren't installed.

**Comment by robmadole** [comment]
We've created some new packages as part of the 5.1.0 pre-release. Check out `@fortawesome/fontawesome-free` and `@fortawesome/fontawesome-pro`. @Seb33300 and @JemiloII if you get time please give these a try and let us know if they meet your expectation.

**Comment by JemiloII** [comment]
It still would be nice for the min version to come with the package so that I don't have to focus on minifying for smaller projects. But @robmadole I love these new packages. This is what I was expecting from the start as a whole. Everything in one easy to install repo!
