### ISSUE TITLE
Icon Request: fa-leaf (regular)

### ISSUE THREAD

**Issue by malenagiletti** [FortAwesome/Font-Awesome#12570]
Hi, 
I really hope you can help me. I'm customizing my website, which is Organic restaurants and cafes directory. I'd like to add a feature that shows the percentage of organic ingredients sourced from suppliers. Restaurants with one leaf - serve 15 - 25% organic produce; those with two leaves - serve 25 - 50% organic produce; those with three leaves - serve 50 - 75% organic produce; four-leaves - serve 75 - 95% organic produce; and five leaves - restaurants that serve 95 - 100% organic produce.

Could you please let me know if you can help me?

Icon request: icon- Serves 15 - 25% Organic Produce
Icon request: icon- Serves 25 - 50% Organic Produce
Icon request: icon- Serves 50 - 75% Organic Produce
Icon request: icon- Serves 75 - 95% Organic Produce
Icon request: icon- Serves  95 - 100% Organic Produce

Thank you in advance!

![serves-25-50 -organic-produce](https://user-images.githubusercontent.com/37257753/37259724-ee5ef61c-2581-11e8-9415-a5cc701d3d2e.png)
![serves-50-75 -organic-produce](https://user-images.githubusercontent.com/37257753/37259725-ee792a00-2581-11e8-836a-85b1cd72c935.png)
![serves-75-95 -organic-produce](https://user-images.githubusercontent.com/37257753/37259726-ee903ac4-2581-11e8-8d63-df39c60d002b.png)
![serves-95-100 -organic-produce](https://user-images.githubusercontent.com/37257753/37259727-eea6c7ee-2581-11e8-9b9f-43401d4ab92e.png)
![serves-15-25 -organic-produce](https://user-images.githubusercontent.com/37257753/37259728-eebe8078-2581-11e8-9d94-79001c4df45f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It looks like a stars rating system, so you basically need two icons: a leaf and an outlined leaf.

The free set already include a leaf:
https://fontawesome.com/icons/leaf?style=solid

If you are a FA 5 Pro Backer, you also have a leaf in regular style, so you could definitely implement that rating system

https://fontawesome.com/icons/leaf?style=regular

I'm going to rename this as `fa-leaf (regular)`

**Comment by malenagiletti** [comment]
Hi,

Thanks for your prompt answer.
I upload an image which shows where I can insert the feature icon, which gives me the option to insert only one leaf at a time (not 5). Probably the only way is to make changes to the code, which is something I have never done before.

Thanks for your help! :+1: 

Regards
MG
![github-leaf](https://user-images.githubusercontent.com/37257753/37289868-b28cf270-2602-11e8-86e8-155b0b4b6b1c.png)

**Comment by tagliala** [comment]
Hi,

you're welcome

>  Probably the only way is to make changes to the code, which is something I have never done before.

Yes, I think that you need a different approach. It looks like php and wordpress.

Maybe an extra property with html value (`<i class="fa fa-leaf"></i> <i class="far fa-leaf"></i>...") or a php leaf generator which takes a number as input.

Also, please keep in mind that only Font Awesome 5 Pro comes with a regular version of `leaf`

**Comment by malenagiletti** [comment]
Thanks :+1:
