### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by yeomihack** [FortAwesome/Font-Awesome#12576]
hello can you please add Medium, Telegram and Discord?

**Comment by tagliala** [comment]
Medium: https://fontawesome.com/icons/medium?style=brands, https://fontawesome.com/icons/medium-m?style=brands
Telegram: https://fontawesome.com/icons/telegram?style=brands, https://fontawesome.com/icons/telegram-plane?style=brands
Discord: https://fontawesome.com/icons/discord?style=brands
