### ISSUE TITLE
soccer filter in documentation

### ISSUE THREAD

**Issue by coderste** [FortAwesome/Font-Awesome#12579]
Version 4.7 has `fa-soccer-ball-o` for a soccer ball but Version 5 does not seem to have a soccer ball at all :/

Basically the icon would look exactly like the soccer ball icon that is in Version 4.7

https://fontawesome.com/v4.7.0/icon/futbol-o/

**Comment by coderste** [comment]
Seems like the icon is under `futbol` for version 5 aswell xD Maybe when searching for 'football' or 'soccer' it brings up the `futbol` result?

**Comment by talbs** [comment]
@coderste, thanks for the heads up. We'll add those terms into our icon search metadata - that should make finding things a bit easier. 😄

**Comment by coderste** [comment]
@talbs Great stuff!

**Comment by talbs** [comment]
Okay, you can now safely search for "soccer" again - https://fontawesome.com/icons?d=gallery&q=soccer. Closing this with that (slide-)tackled. 😛
