### ISSUE TITLE
Icon request: fa-dev-to (dev.to)

### ISSUE THREAD

**Issue by alvarocavalcanti** [FortAwesome/Font-Awesome#12589]
http://dev.to is a great platform which I have been using more frequently in the last couple of months. It has great articles and great discussions.

**Comment by benhalpern** [comment]
I'd LOVE for there to be a [dev.to](https://dev.to) font-awesome. There is a [badge page](https://dev.to/p/badges) containing the SVG but many folks would prefer font-awesome because this is how they handle their other icons. There is definitely big crossover between DEV and Font Awesome communities.

Here is the SVG on the badge page. Let me know if there is anything I can do to help make this happen @tagliala.

<img src="https://d2fltix0v2e0sb.cloudfront.net/dev-badge.svg" height="200"/>

**Comment by aspittel** [comment]
That would be awesome! Super helpful for portfolio sites!

**Comment by alvarocavalcanti** [comment]
In the meantime I've poorly converted that SVG into a font to use it here http://alvarocavalcanti.github.io

Thus, an official font-awesome glyph is still in need. 🙂

**Comment by Berkmann18** [comment]
It would be indeed really cool to have this.

**Comment by sirinath** [comment]
When would this be available?

**Comment by tagliala** [comment]
@sirinath please take a look here https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome and here https://fontawesome.com/community/leaderboard/brands

**Comment by benhalpern** [comment]
Hey @tagliala, how much does the leaderboard influence this process?

**Comment by jessleenyc** [comment]
Ahh I'm sure so many people from the community would use this!

**Comment by themindfuldev** [comment]
I can't wait to be able to consume this icon!

**Comment by jacoby** [comment]
I'm also wanting this icon.

**Comment by Zhao-Andy** [comment]
Excited to use this!

**Comment by mikenieva** [comment]
Please. Do it.

**Comment by benhalpern** [comment]
I'll add one thing about why DEV really belongs here: It is a social icon that software developers are now adding to their personal sites in a hurry. It's not "just another icon". Its presence will encourage software developers to continue to reach for FontAwesome as a viable solution for their personal sites.

Many dev.to users have had to create alternate versions to try and mimic the FA style. It would be very helpful for their user experience if they could reach straight for the FA icon alongside Twitter, LinkedIn, GitHub, etc.

**Comment by bmewing** [comment]
I would love to use this.

**Comment by deanveloper** [comment]
+1

**Comment by acflint** [comment]
Would be great to see!

**Comment by rhymes** [comment]
+1

**Comment by benhalpern** [comment]
Just broke the top 5 on the leaderboard 📈

**Comment by msyvr** [comment]
+1!

**Comment by aspittel** [comment]
Love seeing all the email notifications for this now!

**Comment by nestedsoftware** [comment]
I’d appreciate this as well!

**Comment by alvarocavalcanti** [comment]
Top 2 now! 📈

**Comment by chiangs** [comment]
Definitely want this as a premium user

**Comment by MartyHimmel** [comment]
Would love to see an official DEV icon!

**Comment by benhalpern** [comment]
Woohoo! We're number 1 on the board. The community has spoken!!

**Comment by MaxJohansen** [comment]
Hit it +1

**Comment by ChuksFestus** [comment]
+1

**Comment by rajbdilip** [comment]
+1

**Comment by davegandy** [comment]
Nice work folks. Nice work. So added to 5.4. Should come at the end of this month.

**Comment by davegandy** [comment]
@benhalpern Looks like there are a couple of versions of the logo. The square one posted here and the rectangular one on the website. Any preference? (We're personally fans of the rectangular one on your website. Also, the text would be larger.)

**Comment by lizrodriguez** [comment]
Yesssss +1!

**Comment by 0x15f** [comment]
+1

**Comment by benhalpern** [comment]
@davegandy Our typical "badge" is square with rounded edges, as in our sticker:

![](https://cl.ly/1e8ff442cc63/Image%202018-09-05%20at%2011.27.07%20AM.png)

But the logo can also be displayed in other ways, like just the DEV text in its Joystick font.

So my initial reaction, seeing that several brands have variations is:

![](https://i.imgur.com/6rZ8g8R.jpg)

Also, I feel like the SVG we have provided above is a bit imperfect in ways we haven't bothered fixing but we'd want to get to before this went in.

I think my co-founder @jessleenyc should be in charge of making sure this goes smoothly. Would you or someone from Font Awesome want to email jess@dev.to?

**Comment by talbs** [comment]
@benhalpern roger that. We'll stick with the square style for the brand icon.

 @jessleenyc, thanks for the help - I'll hold off on any work adding this until you get us a fixed version of the logo's .svg file. Feel free to attach it to this thread or email us at hello@fontawesome.com when you have that ready.

**Comment by talbs** [comment]
@benhalpern @jessleenyc, one more question - on your site (and in the comments here) I've seen your organization referred to as both `dev.to` and `DEV`. Which one is your official name?

**Comment by jessleenyc** [comment]
Hey @talbs! Our official name is DEV and the svg should be in your inbox :)
Thanks for making this happen, we're pumped. Let me know if you need anything else!

**Comment by talbs** [comment]
> Hey @talbs! Our official name is DEV and the svg should be in your inbox :)
Thanks for making this happen, we're pumped. Let me know if you need anything else!

Thanks, @jessleenyc. .svg received and we'll get this into our next release. 😄

**Comment by talbs** [comment]
Just gonna leave this nice URL right here - https://fontawesome.com/icons/dev. Thanks again for getting the enthusiasm train chugging along on this request, @benhalpern. 😄
