### ISSUE TITLE
React-FontAwesome, able to display icons not in library

### ISSUE THREAD

**Issue by ramyajanaki** [FortAwesome/Font-Awesome#12583]
I tried to create a library of icons. But I am able to display icons that it not part of library.How is that possible? I have code here
https://codesandbox.io/s/40v5jk6no7

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I suppose that tree shaking is not working. Tree shaking requires extra configuration, I don't know if that is possible on codesandbox

Ref: https://fontawesome.com/how-to-use/use-with-node-js#tree-shaking

**Comment by tagliala** [comment]
Hi, I think this has been fixed in FA >= 5.1.0

Ref: https://codesandbox.io/s/jlrv98nyw5
