### ISSUE TITLE
Icon Request: fa-tryghost

### ISSUE THREAD

**Issue by dprol** [FortAwesome/Font-Awesome#12587]
[ghost-icon.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1806371/ghost-icon.svg.zip)

**Comment by danieldanielecki** [comment]
There's a long discussion about it #2554, post it there.

**Comment by tagliala** [comment]
Are ghost and tryghost the same thing?

**Comment by tribet84** [comment]
Any update on this? Ghost is quite mature and spread not sure why is not included yet
