### ISSUE TITLE
fas fa-share-alt doesn't render in firefox

### ISSUE THREAD

**Issue by doomnuggets** [FortAwesome/Font-Awesome#12586]
### Describe the problem

I'm experiencing a missing icon for `fas fa-share-alt`. I'm using a local copy from the current version (free) in my website.

### What did you expect?

The `fas fa-share-alt` icon renders in all browsers, including Firefox.

### What version and implementation are you using?

Version 5.0.8 (master)
Browser and version: Mozilla Firefox v58.0.2 (Arch Linux)

- [x] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Use the defined Firefox browser version to access this fiddle: https://jsfiddle.net/e8ueyrtt/

Likewise the icon is also not rendering on the official FA page, as seen below:
(left Firefox, right Chromium)

![firefox_vs_chrome](https://user-images.githubusercontent.com/24980899/37331248-55f419b4-269b-11e8-9dcc-4a4a6b62037d.png)

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by doomnuggets** [comment]
Nevermind, it must've been a firefox plugin which did that :) sorry.

**Comment by tagliala** [comment]
> it must've been a firefox plugin which did that

which one? adblock related?

**Comment by doomnuggets** [comment]
@tagliala yes, it seems like ublock origin was the culprit.
