### ISSUE TITLE
Icon request: icon-clap (clapping hands)

### ISSUE THREAD

**Issue by j-francisco** [FortAwesome/Font-Awesome#1258]
Hi! You do a great job!

My icon request is for two hands in a clapping motion. It would be used like an "applaud button" similar to up-voting or "liking" an item. I would like to implement a feature in my app to "applaud" user actions, and it would be awesome if I had an icon that was like a hand clap.

Thanks so much and hope you find this as a useful idea!
Jeff

**Comment by udayrddy** [comment]
Hi j-francisco,

Cheers mate, I'm also searching for the similar use.

Hi FortAwesome Team,

In addition to clap, I would like to request the unclap button. Just like fa-star, fa-star-o. Hope this might be helpful for many other users.

Thanks in advance.

Regards,
Uday

**Comment by udayrddy** [comment]
+1

**Comment by cracker0dks** [comment]
+1

**Comment by duranmla** [comment]
+1

**Comment by thiagobruno** [comment]
+1

**Comment by dehbmarques** [comment]
:+1:

**Comment by scottb50** [comment]
+1

**Comment by cracker0dks** [comment]
you can use this from now on: http://fontawesome.io/icon/sign-language/ 
not perfect but a good start ;)

**Comment by joedf** [comment]
Nice suggestion

**Comment by clongeanie** [comment]
+1

**Comment by oluomoniyi** [comment]
+1

**Comment by maskinmedia** [comment]
Clapping hands - yes please!!

**Comment by pjlasl** [comment]
+1

**Comment by mkronenfeld** [comment]
+1

**Comment by nlubisch** [comment]
+1

**Comment by MacGyver-NRW** [comment]
I clap my Hands! +1 #please

**Comment by stefangre** [comment]
+1

**Comment by valenstical** [comment]
+1

**Comment by vivekkrishna** [comment]
+1

**Comment by SuhwanCha** [comment]
+1

**Comment by arnav13081994** [comment]
+1

**Comment by wilfredonoyola** [comment]
Hi! Do you know the progress about it?

**Comment by lgarcialuzzi** [comment]
+1 👍

**Comment by walkerk2** [comment]
👏 👏 👏 please! We are resorting to mixing an applause image png with a row of beautiful easy-to-manage font awesome icons

**Comment by lukemckinstry** [comment]
+1

**Comment by fajarsiddiqfs** [comment]
![Group 1](https://user-images.githubusercontent.com/20717334/89102131-d5e47e00-d438-11ea-987c-a96052bbcfcc.png)

**Comment by andykamin3** [comment]
+1

**Comment by sensibleworld** [comment]
👏 This is now available in the v6 Alpha release: https://fontawesome.com/download

**Comment by Damato** [comment]
This request is from 2013, now its in (2021) on the paid version. 
Sad to say, there is a reason load of people still uses v4.7 🥇
