### ISSUE TITLE
Incorrect code for including icon

### ISSUE THREAD

**Issue by Bogori** [FortAwesome/Font-Awesome#12594]
`<i class="fal fa-pencil-alt"></i>`
Should be `fa` instead of `fal`

Thanks for your work and services. I really appreciate FontAwesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That is not a typo. Moreover, `fa fa-pencil-alt` and `fal fa-pencil-alt` represent the same icon in different styles

`l` in `fal` stands for light. Light icons are not available to Free users
`r` in `far` stands for regular
`s` in `fas` stands for solid. `fa` is an alias for `fas` and will probably be removed in FA6

Hope it helps

Closing here
