### ISSUE TITLE
website is not usualy

### ISSUE THREAD

**Issue by arthurbonora** [FortAwesome/Font-Awesome#12591]
Hello, 

Excuse me , but i think the website in 5.0 version, are not good for navigation.
it´s possbile come back 4.0 version style?

thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for your feedback. We know that the website could be improved and there are other similar reports.

The greatest concern is performance at the moment.

Could you please be more specific?

**Comment by arthurbonora** [comment]
thanks for your attention, 

i think the 4.0 version are more fast and more easy find the icons

so, i think 4.0 version more clean

**Comment by tagliala** [comment]
About performance, please 👍 #12588

We can use this issue as a feedback for the search page, but you should be a little bit more specific: what we can do to improve search?

> fast and more easy find the icons

Sure it was faster before. 

About the easiness, what you did before that you cannot do anymore?

**Comment by arthurbonora** [comment]
it´s just a suggest
