### ISSUE TITLE
Layering icon

### ISSUE THREAD

**Issue by macagoraga** [FortAwesome/Font-Awesome#12597]
In the documentation there is how to use Layering icon, but there are classes used in the example that is not in the final sass/css code. 

Like 

                    <span class="fa-layers icon-fw" style="background:MistyRose">
                        <i class="fa fa-envelope"></i>
                        <span class="fa-layers-counter" style="background:Tomato">1,419</span>
                    </span>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You are probably using the webfont version of Font Awesome but you are reading the SVG documentation

Please take a look at "Stacked Icons" under the following section: https://fontawesome.com/how-to-use/web-fonts-with-css#additional-styling 

Hope it helps

Closing here, but feel free to comment if you have more questions
