### ISSUE TITLE
New Icon... Stop Light : )

### ISSUE THREAD

**Issue by caroham29** [FortAwesome/Font-Awesome#12604]
Hey guys and gals!

Wouldn't it be awesome if there was an icon that could be programmed like a stop light?!!!! 

Can it be done?  💯

**Comment by aethior** [comment]
Hi @caroham29,

You mean a traffic light?

`fa-traffic-light`: https://fontawesome.com/icons/traffic-light
`fa-traffic-light-go`: https://fontawesome.com/icons/traffic-light-go
`fa-traffic-light-slow`: https://fontawesome.com/icons/traffic-light-slow
`fa-traffic-light-stop`: https://fontawesome.com/icons/traffic-light-stop

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
**in a web application** it is possible to program the traffic light by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/94/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer
