### ISSUE TITLE
Font awesome displating as letters in Photoshop

### ISSUE THREAD

**Issue by adam071082** [FortAwesome/Font-Awesome#12600]
Hello,
I've been trying to use font awesome icons and I can't get them to work in Photoshop. Trying to copy the icon from cheatsheet and then pasting in Photoshop with fontawesome font set makes a bracket with "X" inside it. Also the preview of Font Awesome font in Photoshop shows letters instead of icons, same when I preview it from within Windows - It only shows letters. 

Any ideas on how to slove this issue ? Thanks in advance
Best,
Peter

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> the preview of Font Awesome font in Photoshop shows letters

This is ok. Font Awesome is basically a... font. :)

Which version are you using?

Please make sure that you are the 5.0.8 version of the otf file provided in the `use-on-desktop` folder.

If you are not sure of your version, uninstall your current Font Awesome fonts and install 5.0.8. If you are using windows, consider a reboot.

Usage docs: https://fontawesome.com/how-to-use/use-on-desktop

![image](https://user-images.githubusercontent.com/556268/37404487-4928aeb4-2792-11e8-9458-b4f4e61c08d8.png)

Hope it helps

Closing here but feel free to comment if you need more information

**Comment by tagliala** [comment]
One more thing... please make sure to select the Solid version if you are using solid-only icons on the free version (eg: `align-center`)

**Comment by adam071082** [comment]
And this was critically important - I had "Normal" set by default and this was the issue.
Working perfectly now - Thank you !
