### ISSUE TITLE
cdn.fontawesome only goes to version 4.7.0

### ISSUE THREAD

**Issue by ShaunaGordon** [FortAwesome/Font-Awesome#12615]
### Describe the problem

When I go to select a version for an embed code generated by [cdn.fontawesome.com](https://cdn.fontawesome.com), 4.7.0 is listed as the current version and version 5 isn't available at all.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/579361/37472254-08e0af54-2842-11e8-8a9c-d10531c4125f.png">

### What did you expect?

Since version 5 has been released, I expected to be able to select it as an option.

**Comment by wolfy1339** [comment]
This is a known issue

**Comment by ShaunaGordon** [comment]
@wolfy1339 Is there a public issue or other documentation for it? I tried looking and didn't find anything.

**Comment by tagliala** [comment]
@robmadole should this be updated to 5.0?

**Comment by robmadole** [comment]
We won't be updating `cdn.fontawesome.com` with version 5.0. It's available from https://fontawesome.com/get-started

**Comment by nlwillia** [comment]
What will happen to cdn.fontawesome.com?  How long do we have to migrate?

**Comment by robmadole** [comment]
We aren't shutting down `cdn.fontawesome.com` yet and honestly haven't even talked exactly about what we'll do with it. Millions use it and we know that.
