### ISSUE TITLE
Icon Request: fa-safe

### ISSUE THREAD

**Issue by GaetanLebaron** [FortAwesome/Font-Awesome#12611]
Hi,
The icon may be use for representing secured storage.
Thanks.

![safe-icon](https://user-images.githubusercontent.com/37405622/37462947-ea046014-2853-11e8-8ecd-1e9fb4718892.png)

**Comment by DonkeyAfterDark** [comment]
I would also like a Safe Icon of sorts. I'm surprised there isn't one!

**Comment by alex-woodall-premierfoods** [comment]
+1 please!!!

**Comment by tagliala** [comment]
fff sorry, this is a duplicate of #1813

Let's use #1813, which has more +1s
