### ISSUE TITLE
Icon Request: fa-office-chair

### ISSUE THREAD

**Issue by amielantonio** [FortAwesome/Font-Awesome#12621]
## Usage

This can be used in web applications that represents a workstation or related to an office or a CEO.

## Idea

A CEO chair or anything alike.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3984, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
