### ISSUE TITLE
Website scrolling performance unusable

### ISSUE THREAD

**Issue by victornpb** [FortAwesome/Font-Awesome#12629]
I just visited the new website and it is totally unresponsible, I can't scroll or interact with the website at all.

```
Chrome Version 67.0.3372.0 (Official Build) canary (64-bit)
macOS High Sierra 10.13.3 (17D102)
```

https://www.youtube.com/watch?v=D_wA8W3cGak

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I agree, performance is poor and it will addressed asap.

Let's use: #12588, I will copy your comment there

Closing here
