### ISSUE TITLE
Icon Request: fa-camera-slate

### ISSUE THREAD

**Issue by jennylijo** [FortAwesome/Font-Awesome#12622]
Hi! Love the work :)
We are in need of a Camera Slate icon. 

Something like this:
[link
](https://cdn2.iconfinder.com/data/icons/movie-8/500/slate_film-256.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #3130?

**Comment by aethior** [comment]
> Is this a duplicate of #3130?

Yes, this request is duplicate.
