### ISSUE TITLE
Bug with inventory and box icons not appearing

### ISSUE THREAD

**Issue by cbielich** [FortAwesome/Font-Awesome#12627]
I'm sure there is more than this but for some reason the inventory icon as well as the box will not render on screen. Many others I use render fine.

<i class="fal fa-inventory"></i>
<i class="fal fa-box"></i>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`inventory` is a FA5 Pro only icon, so I suppose you are using FA5 Pro.

If you are using FA5 Pro, please make sure you are using the latest 5.0.8 version

If you are using FA5 Pro 5.0.8 and you still have this issue, please open a bug in the FA5 Pro repository at: 
https://github.com/FortAwesome/Font-Awesome-Pro

Hope it helps

Closing here

**Comment by cbielich** [comment]
That was it, I already had pro just not the latest version. Thanks!
