### ISSUE TITLE
confused for include js

### ISSUE THREAD

**Issue by peterremote1980** [FortAwesome/Font-Awesome#12634]
Hi , i am using fontawesome with SVG, in your web i see:

```
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
```

But i don't have solid.js in my zip, there is fa-solid.js, should I use this one?

Thanks
From Peter

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> But i don't have solid.js in my zip, there is fa-solid.js, should I use this one?

Which zip file? The one you download from the website?

You don't need to download the zip file if you want to use the CDN.

Anyway, if you want to use also regular and brands, please check the "All" button

![image](https://user-images.githubusercontent.com/556268/37556822-8e453f10-29fb-11e8-954d-5b855ddeece6.png)

the inclusion tag will turn into
```
<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
```

**Comment by tagliala** [comment]
FWIW, I think the above instructions are quite confusing. I would start with the "All" option preselected
