### ISSUE TITLE
Not preserving the title attribute

### ISSUE THREAD

**Issue by barrychapman** [FortAwesome/Font-Awesome#12631]
### Describe the problem

I have an `<i>` that uses the SVG-JS framework. I have a class for a tooltip on that element, and it uses the 'title' attribute. When the SVG is replaced, it removes the title attribute, breaking all our tooltips:

WAS://

    

IS://

    <svg style="cursor: help; margin-top: -2px; vertical-align: middle; color: #1c5891; font-size: 22px;" title="" class="svg-inline--fa fa-question-circle fa-w-16 help-popup" data-original-title="Power of Attorney Document" aria-hidden="true" data-prefix="fa" data-icon="question-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M504 256c0 136.997-111.043 248-248 248S8 392.997 8 256C8 119.083 119.043 8 256 8s248 111.083 248 248zM262.655 90c-54.497 0-89.255 22.957-116.549 63.758-3.536 5.286-2.353 12.415 2.715 16.258l34.699 26.31c5.205 3.947 12.621 3.008 16.665-2.122 17.864-22.658 30.113-35.797 57.303-35.797 20.429 0 45.698 13.148 45.698 32.958 0 14.976-12.363 22.667-32.534 33.976C247.128 238.528 216 254.941 216 296v4c0 6.627 5.373 12 12 12h56c6.627 0 12-5.373 12-12v-1.333c0-28.462 83.186-29.647 83.186-106.667 0-58.002-60.165-102-116.531-102zM256 338c-25.365 0-46 20.635-46 46 0 25.364 20.635 46 46 46s46-20.636 46-46c0-25.365-20.635-46-46-46z"></path></svg>

It sticks my old title in data-original-title.

### What did you expect?
Preserve the title attributes so the site still works the way we want.

### What version and implementation are you using?

Version: 5.0.8
Browser and version: 
All browsers. Just tested it with Chrome and FF most rececently.

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Wouldn't this expose my credentials to the public as to how to download FA5Pro?

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Wouldn't this expose my credentials to the public as to how to download FA5Pro?

This will probably be reproducible also with FA5 Free

You can start with this https://jsfiddle.net/tagliala/qu83xrwp/60/ and add just the minimum amount of code to reproduce the issue.

I can see `data-original-title="Power of Attorney Document"` on your `<i>` element, so I suspect that your javascript library already checked for it and replaced the title attribute.

If this what is happening, there is the need to wait until the `<i>` tags are replaced by `<svg>`s.

At the moment I'm not sure if there is a callback

@robmadole any thoughts?

**Comment by barrychapman** [comment]
That is exactly what I ended up doing. Since the bootstrap tooltip does not support attaching to SVG's, I moved the bindings to the parent element. That works.

**Comment by tagliala** [comment]
@ScotsScripts put the icon tag in another element with the title attribute

It should be something like this: https://jsfiddle.net/tagliala/qu83xrwp/104/

I'm going to close here, because I can see the `title` element being preserved on SVG and it depends on a third-party script and async loading
