### ISSUE TITLE
Brand Icons not working

### ISSUE THREAD

**Issue by anshuldawar** [FortAwesome/Font-Awesome#12636]
![capture1](https://user-images.githubusercontent.com/10780826/37558487-fcb27104-2a3a-11e8-9c89-cd1eb41e3f47.PNG)
Font Awesome 5 Free Solid is installed on my laptop, I'm designing an UI on Adobe XD and when i tried to use facebook font, it's not working. After I tries to use an old fontawesome font with Pinterest icon it works, but still not working for the facebook icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that FA5 Brands has a separate font file, called Font Awesome 5 Brands. You should install that too and switch the used font.

Let me know if this helps

**Comment by anshuldawar** [comment]
Thanks@tagliala, It works now.

**Comment by tagliala** [comment]
Hi @oderindeolayemi 

please note that we have a react component: https://fontawesome.com/how-to-use/on-the-web/using-with/react

If you still have issues, please open a new issue that follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
