### ISSUE TITLE
Some Icons not Working

### ISSUE THREAD

**Issue by mnissov** [FortAwesome/Font-Awesome#12641]
I've downloaded and installed the latest version of Fontawesome for desktop use. I can copy and paste some icons fine, like safari, but others, like hdd, don't work. I've only been referencing the free cheatsheet so it shouldn't be a free vs pro issue.

**Comment by rtd62** [comment]
I had the same issue trying to use brand icons such as Facebook and Twitter ... was working over the past month.

**Comment by rtd62** [comment]
Oh wait ... I knew the docs had changed ... use this instead:

`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure you have installed all the available fonts (FA5 Brands, FA5 Regular, FA5 Solid) and you have selected the right font (and weight) for the icon you are pasting.

If this doesn't fix, please provide
- OS and version
- Software and version
- Version of FA installed

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by mnissov** [comment]
I think I am, I'm pasting from the font awesome cheatsheet and using the hdd symbol as my test: 

I have all of the fonts installed, brands, regular and solid. I'm running ubuntu 16.04 LTS with version 5.0.8 of Font Awesome using the opentype fonts.

**Comment by tagliala** [comment]
Where are you pasting the icon?

**Comment by mnissov** [comment]
In an i3blocks config file, using v1.4 of i3blocks

**Comment by tagliala** [comment]
Got it.

Please use #10102 for i3 related issues

We still don't have a solution

Closing here
