### ISSUE TITLE
Linkedin icon not showing (using CDN CSS)

### ISSUE THREAD

**Issue by GaiaGong** [FortAwesome/Font-Awesome#12649]
I've integrated through CSS, icons work fine except for the [linkdein icon](https://fontawesome.com/icons/linkedin?style=brands) (the one in a square)

Used the code `<i class="fab fa-linkedin"></i>` but it shows an empty square.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you are using the default settings

```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css" integrity="sha384-v2Tw72dyUXeU3y4aM2Y0tBJQkGfplr39mxZqlTBDUZAb9BGoC40+rdFCG0m10lXk" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/fontawesome.css" integrity="sha384-q3jl8XQu1OpdLgGFvNRnPdj5VIlCvgsDQTQB6owSOHWlAurxul7f+JpUOVdAiJ5P" crossorigin="anonymous">
```

![image](https://user-images.githubusercontent.com/556268/37659332-fb2d8348-2c4f-11e8-9401-226788e72cf2.png)

please note that **Brands are not included**, so you need to

- Enable "Brands" or
- Select "All" 

and update your html accordingly.

Please let me know if this is your issue

**Comment by psdesignmobile** [comment]
Having the same issue. 

When you say it's "not included", do you mean in the free version? It's on the free page. 

FWIW: Whether I select "all" or individually select each one, it's not working for me either.

**Comment by tagliala** [comment]
> When you say it's "not included", do you mean in the free version? It's on the free page.

Hi, things have changed: the default choice (`all.css`) now include brands

I'm going to close here. If you think there is an issue with Font Awesome, please open a new issue and make sure it follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by psdesignmobile** [comment]
in case its helpful to others: it has to be:
fab fa-linkedin NOT
fa fa-linkedin

**Comment by HiveMindNet** [comment]
Thank you psdesignmobile - your note was most helpful. In fact is was the only helpful comment on the page in my view.

**Comment by jessuppi** [comment]
I was having a similar issue, it turned out to be Adblock related, see this thread:

https://github.com/FortAwesome/Font-Awesome/issues/1799

**Comment by petervandenabeele** [comment]
@jessuppi found the relevant cause (see post above). Test turning off AdBlock Plus and if that has impact (it did for me in June 2019), check the thread shown above #1799 .

**Comment by Guscosta88** [comment]
I've tried this one and it worked:

<i className="fa fa-linkedin-square"></i>

**Comment by LauraRLT** [comment]
This worked for me:
brands fa-linkedin
