### ISSUE TITLE
Pixiv icon (?)

### ISSUE THREAD

**Issue by xcorpion77** [FortAwesome/Font-Awesome#12644]
Hello, community.

I would like to know if someone could design an icon for the website called "Pixiv".

Thanks greetings.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5093, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
