### ISSUE TITLE
Font-Awesome 5 delays images from loading in Bootstrap 4 carousel - Microsoft Edge

### ISSUE THREAD

**Issue by hugomiura** [FortAwesome/Font-Awesome#12652]
There is a bug with Microsoft Edge when using Bootstrap 4 carousel and Font-Awesome's "searchPseudoElements" is enabled. The second, third (and so on) images do not load correctly. Only after a mouse move.

**Comment by hugomiura** [comment]
https://www.youtube.com/watch?v=pKra9Ohh_1U

**Comment by tagliala** [comment]
@robmadole sorry, I cannot check this one. Could you please take a look?

@mlwilkerson is also working on searchPseudoElements performance. Maybe is something related to that?

(feel free to unassign)

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).
