### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Idered** [FortAwesome/Font-Awesome#12660]
My CircleCI builds randomly fail due to unstable npm server 

```
yarn

yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/XXXXX/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.1.3.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this still an issue?

**Comment by tagliala** [comment]
Closing here. Feel free to comment if it happens again

**Comment by nickcointracker** [comment]
Hey folks. Can't get rid of this:
`yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/2C2E4030-73DC-4A02-9236-D3800A25E5F9/@fortawesome/pro-light-svg-icons/-/pro-light-svg-icons-5.10.1.tgz: Request failed \"500 Internal Server Error\"".
`

**Comment by tagliala** [comment]
@nickcointracker hi, 

I've edited your comment but you have unintentionally disclosed your API Private Token (it must stay secret).

Please drop a line at hello@fontawesome.com because we probably need to change that.

Please also add a link to this issue in the email body

**Comment by charlex** [comment]
Hi I am seeing 500 errors too this morning from my builds:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-regular-svg-icons/-/pro-regular-svg-icons-5.10.2.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by JohnWelle** [comment]
Exact same problem as reported by @charlex in our CCI builds as well.

**Comment by ebakke** [comment]
We're seeing a mix between 500 Internal Server errors, and 504 Gateway Timeout errors.

**Comment by charlex** [comment]
This issue is related: https://github.com/FortAwesome/Font-Awesome/issues/15454
