### ISSUE TITLE
Icon request: fa-fuel-disp

### ISSUE THREAD

**Issue by borsn** [FortAwesome/Font-Awesome#12665]
I think the platform is missing an icon of a fuel dispenser.

![dispenser-icon-small](https://user-images.githubusercontent.com/14618565/37738100-00e4c6bc-2d67-11e8-835a-e6e9310b7610.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1676 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
