### ISSUE TITLE
text-shadow on svg-with-js?

### ISSUE THREAD

**Issue by corysimmons** [FortAwesome/Font-Awesome#12666]
Any way to define this or should I use the Web Fonts method?

**Comment by aensley** [comment]
There is a solution using CSS filter: drop-shadow(): https://github.com/FortAwesome/Font-Awesome/issues/11916#issuecomment-376271281

**Comment by corysimmons** [comment]
I didn't even think of using svg filters on svgs...

Once duotones come out, doing tone changes on hover will be so easy.

Thank you! Loving FontAwesome5 so much!
