### ISSUE TITLE
Icon request: icon-peso (philippine)

### ISSUE THREAD

**Issue by oobgam** [FortAwesome/Font-Awesome#1267]
For better currency support especially in places using the peso currency.
![peso](https://f.cloud.github.com/assets/2231446/646009/7a32f1e2-d3b7-11e2-80b6-1f9939fa8b1b.gif)

**Comment by keithics** [comment]
+1

**Comment by ljayz** [comment]
+1

**Comment by Angelo8828** [comment]
+1

**Comment by AlbertHeaviside** [comment]
+1

**Comment by cabillier** [comment]
+1

**Comment by marksegalle** [comment]
+1

**Comment by ajalbaniel** [comment]
+1

**Comment by magsudesu** [comment]
+1

**Comment by louiepiol** [comment]
+1

**Comment by ninoM** [comment]
+1 All we can do is hope.

**Comment by nkmswot** [comment]
+1

**Comment by jaycee04** [comment]
+1

**Comment by vinceurag** [comment]
+1

**Comment by doodlefudge** [comment]
+1

**Comment by julianjupiter** [comment]
+1

**Comment by asakapab0i** [comment]
+1 :100:

**Comment by Angelo8828** [comment]
Sa lahat po ng mga nag+1, please give :thumbsup: instead in the first comment. Likes 'yung mas nata-track sa [leaderboard](https://fontawesome.com/community/leaderboard/new), not the discussion.

**Comment by nogats07** [comment]
> @tagliala He said "places using the peso currency", Philippines is not the only country using Peso, but it is the only country using that sign. In my opinion there's not a good reason to implement a sign for a currency that is not widely used.

You don't seem to like philippines huh?

**Comment by xmarkclx** [comment]
There's already a unicode sign ₱ (you can copy paste it actually), but I agree we need a Font Awesome version that is solid. 

Kind of like:
https://fontawesome.com/icons/dollar-sign?style=solid

I know our economy isn't doing that well right now, but thats no reason not to make an icon for it. :/

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
