### ISSUE TITLE
Cannot Search for Icons based on fa- name

### ISSUE THREAD

**Issue by Andy65** [FortAwesome/Font-Awesome#12671]
I am unable to search for any icon based on it's name - e.g. try a search for fa-table = no results

**Comment by Bagera** [comment]
If you mean on the site. Try without "fa-". the icon is not called "fa-table" it is just called "table".

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons?d=gallery&q=table
