### ISSUE TITLE
Pro CSS/Webfont CDN is not showing brands

### ISSUE THREAD

**Issue by marcelmoreau** [FortAwesome/Font-Awesome#12675]
Using the Webfont CDN with a pro account, I am able to show light, regular, and solid variants in pseudo elements. I cannot display any brand icons.

My font-family is set to `font-family: 'Font Awesome 5 Pro';`

The site's UI indicates brands would be included. Is this not the case?

![screen shot 2018-03-22 at 5 08 45 pm](https://user-images.githubusercontent.com/2116946/37798656-c65c9d98-2df3-11e8-8577-2a0683985907.png)

**Comment by julien-mamalian** [comment]
Same issue here !

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot confirm

Is this still an issue?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot confirm

Please note that you need to use 

```css
  font-family: "Font Awesome 5 Brands";  content: "\f099";
```

as per documentation: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements

Also, you did not specified if you are using css or svg version
