### ISSUE TITLE
How do I use Font Awesome in a TinyMCE editor?

### ISSUE THREAD

**Issue by Tomicapo** [FortAwesome/Font-Awesome#12674]
I'm using latest version of TinyMCE and trying to use Font Awesome's latest version. Since it's pure Javascript, I don't know how I can implement it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information?

**Comment by Tomicapo** [comment]
I'm sorry. At the time, I didn't see the css version. You may disregard this issue. Thanks.

**Comment by Tomicapo** [comment]
I'm sorry. At the time, I didn't see the css version. You may disregard this issue. Thanks.

**Comment by tagliala** [comment]
No proble, glad you solved 👍
