### ISSUE TITLE
Icon request: sharpcaret-left

### ISSUE THREAD

**Issue by madcat007** [FortAwesome/Font-Awesome#12672]
Used for navigation on slides - right and left

So this is similar to fa-caret-left and right but with sharp corners - not rounded

Icon request checklist

Matched pair (left and right)

I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
 I have included at least one example image if it could be helpful (ignore blue background)
![example](https://user-images.githubusercontent.com/3470323/37775497-6d3fccae-2de3-11e8-8652-3bf4cd9218b3.gif)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The base Font Awesome style has soft corners: If we add sharp corners, it would be for a new icon style.

Meanwhile you can go for [plain css](http://www.cssarrowplease.com/) or your own SVG

Hope it helps

Closing here
