### ISSUE TITLE
On How to page there is a Typo

### ISSUE THREAD

**Issue by webdevtarun** [FortAwesome/Font-Awesome#12689]
On how to page, First HTML code is wrong 

```<i class="fas fa-camera-retro"></i>```

I think it should be 

```<i class="fa fa-camera-retro"></i>```

please check.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Not a typo. FA5 works differently from FA4.

Please take a look here: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
