### ISSUE TITLE
Icon fab fa-linkedin not working

### ISSUE THREAD

**Issue by auslanderrasque** [FortAwesome/Font-Awesome#12686]
Cannot get this one to work. Shows as a rectangle. Ones with fas working ok. Is it just fab ones?

**Comment by aizazshahid** [comment]
@auslanderrasque  Looks like its a typo, correct one is **fa fa-linkedin**

**Comment by auslanderrasque** [comment]
Sorry, that doesn't seem to work either. Any idea?
<img width="654" alt="screen shot 2018-03-26 at 1 07 41 pm" src="https://user-images.githubusercontent.com/37711872/37921068-b1c1b624-30f6-11e8-8e92-82ce095d2336.png">

<img width="1126" alt="screen shot 2018-03-26 at 1 06 14 pm" src="https://user-images.githubusercontent.com/37711872/37921030-9d11c0ca-30f6-11e8-8feb-904045b4855c.png">

**Comment by slyk-style** [comment]
Had similar issue. try font-awesome.min.css instead of .css

**Comment by auslanderrasque** [comment]
That did it. Thank You!!

**Comment by danieldanielecki** [comment]
Be also aware between differences between Font Awesome 5 & 4 and below, the `fab` means it's the newer version, i.e. it won't work on the old one. In my case it was the problem, I imported version 4.7 into my project, and tried to use icons from 5.

[Here ](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) you can find differences between these versions, including information about prefixes.

**Comment by hicham-mahi** [comment]
thank you so much , I do not know how this code worked, although the code you put is similar. All I have done is copy paste to find the code works. Thanks again.

**Comment by rushabhnaik16** [comment]
Use fab fa-linkedin and cpoy this <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

**Comment by EitharAlotoom95** [comment]
@rushabhnaik16  could u please explain more where to put the link ?  i'm new to programming .

**Comment by EitharAlotoom95** [comment]
@m-peterman  hi .. could u plz explain more where to put font-awesome.min.css this to help me fix my problem ?

**Comment by tagliala** [comment]
Hi @EitharAlotoom95 

> could u please explain more where to put the link ? i'm new to programming .

Usually they go in the `<head>` tag, but this issue tracker is only for icon/feature requests and bug reports, support is out of scope.

Please take a look at our documentation:

- Get Started (with Font Awesome kit): https://fontawesome.com/start Once you get a kit, the kit details page will provide instruciton on how to place and use it
- Upgrading from Font Awesome 4 to 5: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

We are sunsetting our official CDN, so we do not provide instruction on how to use font awesome from `use.fontawesome.com` anymore

You can still use third-party CDNs that host Font Awesome like [cdnjs](https://cdnjs.com/libraries/font-awesome), but we do not support this kind of installation anymore

> could u plz explain more where to put font-awesome.min.css this to help me fix my problem ?

If you have an issue and linkedin icon does not show up, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by j0nimost** [comment]
the react package `@fortawesome/react-fontawesome` has this same issue:

`<FontAwesomeIcon icon={['fab', 'fa-twitter']} />` does not work
