### ISSUE TITLE
lock-open & unlock Unicode bug

### ISSUE THREAD

**Issue by tomkuehl** [FortAwesome/Font-Awesome#12682]
Hi,

the unicode for lock-open (f3c1) doesn't work and unlock (f09c) has the wrong icon (using the unicode). 

Version: 5.0.8
Browser & Version: Chrome 64.0.3282.186

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case
https://codesandbox.io/s/9x1ywop8r

https://fontawesome.com/icons/lock-open?style=solid
https://fontawesome.com/icons/unlock?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fix:
1. Font name. It is supposed to be "Font Awesome 5 Free" 
2. Reset the font style of the `<i>` tag or, better, use `<span>`
3. Set the font-weight to 900 (solid)

Ref: https://codesandbox.io/s/1rv3m8rpqq

Hope it helps, closing here

**Comment by tagliala** [comment]
doc ref: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

**Comment by tomkuehl** [comment]
Thanks!

**Comment by tagliala** [comment]
You're welcome, sorry for the late reply
