### ISSUE TITLE
Broken CDN

### ISSUE THREAD

**Issue by xAphex** [FortAwesome/Font-Awesome#12691]
I updated to the newest CDN that includes a SHA384 integrity and now none of my fontawesome icons load.

Firefox browser console error:
`None of the “sha384” hashes in the integrity attribute match the content of the subresource.`

How do i fix this?

**Comment by slyk-style** [comment]
Which JavaScript are you using. The integrity is probably wrong when associate with that file. See below for an example with bootstrap. 
https://stackoverflow.com/questions/34818698/strange-error-when-using-css-boostrap

**Comment by xAphex** [comment]
i'm using this:
`<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>`

taken from: https://fontawesome.com/get-started

**Comment by slyk-style** [comment]
Hmm thats bizzaar. maybe remove integrity. as for the icons make sure they are <svg> and not <i>'s other than that i would suggest either switching to the css version which should work with 99% of browsers or self hosting the files and it might fix your issues(as you would know the only downside is it would take time to load the 1st time round).

**Comment by xAphex** [comment]
i have switched to the original CDN which is:
`<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"</script>`

and it works fine.

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by xAphex** [comment]
I no longer use the CDN because `use.fontawesome.com` is blocked by Privacy Badger.

Apparently Fontawesome website uses tracers so [Privacy Badger Addon](https://www.eff.org/privacybadger) blocked the CDN and prevented the js script from loading.

So i downloaded `all.js` script and linked it in my website.

**Comment by tagliala** [comment]
@robmadole could you please take another look at this?

**Comment by robmadole** [comment]
I can't reproduce this. Are you blocking the site @xAphex ? If you can provide a reproduction we'll be happy to take a look again.

**Comment by xAphex** [comment]
@robmadole the issue only exists if you have [Privacy Badger](https://www.eff.org/privacybadger) addon installed on Firefox or Chrome.

The addon blocks fontawesome site because your site has trackers.

![Privacy Badger](http://i.cubeupload.com/ZfPHJn.png)
