### ISSUE TITLE
I can't find the icon I want.

### ISSUE THREAD

**Issue by BigSnow1** [FortAwesome/Font-Awesome#12699]
I want the icon which represent for avatar.I am going to user it to point out the place where users can click to change their avatar

**Comment by DiseasedBones** [comment]
Will one of these work?
https://fontawesome.com/icons?d=gallery&q=profile

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can use icons proposed by @DiseasedBones 

If you have another idea, please open a new request and make sure it follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
