### ISSUE TITLE
sell

### ISSUE THREAD

**Issue by feather812002** [FortAwesome/Font-Awesome#12690]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I know that an example image is optional, but in this case you are requesting a "sell" and it is hard to figure it out how a sell looks like

Could you please provide an example?

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by aethior** [comment]
@tagliala I think you can close here.
