### ISSUE TITLE
Chrome v49 not showing all icons on Windows XP / Vista when GDI is enabled

### ISSUE THREAD

**Issue by omnimint** [FortAwesome/Font-Awesome#12693]
Chrome 49.0.2623.112 is not rendering icons, range f000 - f020 (may be others). Is there something I can do to solve this?
From https://fontawesome.com/how-to-use/web-fonts-with-css
![slika](https://user-images.githubusercontent.com/5503223/37869134-8fa5d722-2fb2-11e8-9aae-329468b4f699.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Chrome 49 is the latest chrome available for windows xp?

**Comment by palych3** [comment]
I'd like to confirm this issue.
Some icons on Windows XP are not rendering.
Chrome 49 is latest available version.
Also, icons from version 4.7 are visible, but after upgrade to 5.0 got broken.

For example:
fa-chart-pie
fa-search
fa-spinner

**Comment by robmadole** [comment]
Yeah, I don't know that we are going to spend a lot of time on this one. I'll get it in the list but XP is so old and this is outside of the official support for 5.

**Comment by tagliala** [comment]
> If I disable GDI (Enable DirectWrite) ALL THE ICONS WORK

@needforsuv thanks for the heads up

> FONT AWESOME 5 DOES NOT WORK WITH GDI
> NOW GO TEST IT with supported browsers WHICH DO RUN using windows GDI

Could you please open a new issue with a reproducible test case on a supported browser ([list for SVG version](https://fontawesome.com/how-to-use/svg-with-js#browser-support) [list for CSS version](https://fontawesome.com/how-to-use/web-fonts-with-css#browser-support)), filling out our 
[bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please also provide your OS version and steps to Enable / Disable GDI

**Comment by SukcesStrony** [comment]
+1 this, as it is also a bug in the last Chrome version for Windows Vista, not only XP

**Comment by SuperPat45** [comment]
> Please also provide your OS version and steps to Enable / Disable GDI

As directwrite was enabled since chrome version 37 for windows 7 and upper,
you can also see the bug with chromium portable version 36 or lower on any Windows version:
https://sourceforge.net/projects/crportable/files/ChromiumPortable_36.0.1985.18.paf.exe/download

**Comment by Nemixs** [comment]
I solved using all.min.js instead of all.min.css
`<script defer src="/your-path-to-fontawesome/js/all.js"></script>`

**Comment by RoelN** [comment]
See this answer that explains the issue and offers a solution: https://github.com/FortAwesome/Font-Awesome/issues/13156#issuecomment-2384975046
