### ISSUE TITLE
Icon request: invision

### ISSUE THREAD

**Issue by spidercam** [FortAwesome/Font-Awesome#12694]
### What can it be used for?

Invision related items like prototype links and projects.

### Example image (optional)

![invision_icon_pink](https://user-images.githubusercontent.com/113851/47231390-9cd13b80-d381-11e8-8ff7-606e3e6dccc8.png)
![invision_icon_black](https://user-images.githubusercontent.com/113851/47231394-9e9aff00-d381-11e8-8c20-47110cc62cc8.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by itsmelion** [comment]
Also love the idea of invision icons,
here is where you can find the official brand guidelines and assets for development of the icon:

https://www.invisionapp.com/company#media_kit
[Direct link](https://in.invisionapp.com/boards/FH3LW3S7XSD/)

**Comment by talbs** [comment]
Released in version 5.6.0 - https://fontawesome.com/icons/invision. 😄
