### ISSUE TITLE
NPM packages confusing

### ISSUE THREAD

**Issue by pantonis** [FortAwesome/Font-Awesome#12702]
I can see several packages in [npmjs](https://www.npmjs.com/search?q=scope%3Afortawesome).
What is the difference between @fortawesome/fontawesome-free and @fortawesome/fontawesome
What is the difference between @fortawesome/fontawesome-free and @fortawesome/fontawesome-free-solid, @fortawesome/fontawesome-free-regular, @fortawesome/fontawesome-free-brands.

Which do I need to install to use font-awesome 5? It is so confusing and the documentation on the website not straightforward.

**Comment by dflock** [comment]
These package names are going to change in 5.1, but here how you do it with the current version:

https://fontawesome.com/how-to-use/use-with-node-js#free

**Comment by raisonon** [comment]
Looks like this will get the SVG JS:

npm i --save @fortawesome/fontawesome

into @fortawesome folder (which is not a good name imo)

Very confusing! Looking forward to new package names. I was pulling from fontawesomenpm and getting version 4.7 :/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@raisonon is correct, this is going to change in 5.1

Please refer to this comment https://github.com/FortAwesome/Font-Awesome/issues/11895#issuecomment-368647771

Closing here
