### ISSUE TITLE
Icon Request: icon-theatre-mask (icon-drama, icon-theatre)

### ISSUE THREAD

**Issue by jasonhinkle** [FortAwesome/Font-Awesome#1270]
I would love to see a theater mask icon.  This is a great icon to represent a theater, venue, show or artistic performance.  Alternately I think people refer to it as a "tragedy" mask.  Attached is an example image.  Thanks for the awesome font!

![screen shot 2013-06-12 at 9 51 05 pm](https://f.cloud.github.com/assets/313176/646558/83835b34-d3d4-11e2-859b-4222431e91e5.png)

**Comment by Krule** [comment]
+1

**Comment by tpiechota** [comment]
+1

**Comment by littlestoatie** [comment]
+1 tragicomedy masks for theatre

**Comment by Henner** [comment]
+1

**Comment by zimmicz** [comment]
+1

**Comment by aydnbhdr** [comment]
+1

**Comment by sethbaugh** [comment]
+1

**Comment by ComedyTomedy** [comment]
+1

**Comment by PremiumWebServices** [comment]
I don't understand why so many fundamental icons (like this one) are missing while there are tons of icons that most normal people will never use.

+1

**Comment by chip-miller** [comment]
+1

**Comment by ygwain** [comment]
+1

**Comment by LukeStanbery89** [comment]
+1

**Comment by jkfoto** [comment]
+1

**Comment by Peterdoma** [comment]
+1

**Comment by simonfranz** [comment]
+1 for something like this
![mask](http://cdn2.iconfinder.com/data/icons/movie-icons/512/Theatre_Masks-512.png)

**Comment by sheebypanda** [comment]
+1

**Comment by tagliala** [comment]
@jasonhinkle thanks for keeping the title up to date with votes but it is not needed because we can sort by descendant number of comments: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+sort%3Acomments-desc

**Comment by kwaaui** [comment]
+1

**Comment by jasonhinkle** [comment]
thanks @tagliala I removed it from the title

**Comment by melbrs** [comment]
+1

**Comment by adamdiy** [comment]
+1

**Comment by bansaghi** [comment]
+1

**Comment by sators** [comment]
+1

**Comment by mariegithub** [comment]
+1

**Comment by popisms** [comment]
+1

**Comment by bootstrapsbootstraps** [comment]
+1

**Comment by sarahjsquire** [comment]
+1

**Comment by mentor2k1** [comment]
+1

**Comment by jymbob** [comment]
+1

**Comment by parag-datar** [comment]
+1

**Comment by JeroenCollier** [comment]
+1  Especially useful for cultural purposes.

**Comment by chaplinskiy** [comment]
+1

**Comment by dojorob76** [comment]
+1

**Comment by obruchez** [comment]
+1

**Comment by jacqueskang** [comment]
+1

**Comment by mtdinnyc** [comment]
+1

**Comment by ferimer-dev** [comment]
+1

**Comment by gauthier-delacroix** [comment]
+1

**Comment by olimaz** [comment]
+1

**Comment by bmkw** [comment]
+1

**Comment by kpingel** [comment]
👍

**Comment by traceyj2** [comment]
+1

**Comment by rub1e** [comment]
+1

**Comment by lesliemklo** [comment]
+1

**Comment by miguelalche** [comment]
+1

**Comment by dereksweet** [comment]
+1

**Comment by marstone** [comment]
+1

**Comment by hbsoftco** [comment]
+1

**Comment by kleiner5Punkt** [comment]
+1

**Comment by miguelalche** [comment]
+1

**Comment by Phainix** [comment]
+1

**Comment by jemoreto** [comment]
+1

**Comment by miguelalche** [comment]
Hey I really want this to happen for an app I'm making, can I help in any way? Would uploading an svg work?

**Comment by tagliala** [comment]
@miguelalche please take a look here

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

If you are going to fork the repository, please share your work here

**Comment by jamesrskinner** [comment]
+1

**Comment by glen-stephens** [comment]
+1

**Comment by Tebogo14** [comment]
+1

**Comment by MarceloRGomes** [comment]
+1 REALLY NEED THIS MASKS!!! Together and alone!

**Comment by stirlinghewitt** [comment]
+1

**Comment by adamjacobi** [comment]
+1

**Comment by earthcomedy** [comment]
+1

**Comment by Chyukasame** [comment]
+1

**Comment by tonywatkins** [comment]
+1

**Comment by kschaerer** [comment]
+1

**Comment by hbersey** [comment]
+1
