### ISSUE TITLE
Icon request: icon-pivot

### ISSUE THREAD

**Issue by VictoriqueMoe** [FortAwesome/Font-Awesome#12703]
### What can it be used for?

I have looked for this icon, but could not find it, and I think it could be a good idea if it was included, if not, then please do say.

The idea of this icon is that you can represent a button (for example) that when activated, brings up pivot controls for said table.

Representing this is difficult, but there are Pivot icons out there (windows 10 has one I think)
This request is similar to #11012 but instead this one can not really be substituted by the excel pivot 
use cases for this can be:

- Button to represent the activated of a pivot control modal 

- table axis control

### Example image 

the look of the icon could be:
![alt text](https://i.imgur.com/LiEG5Er.png "table pivot")

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ?)

thank you :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This request is similar to #11012 but instead this one can not really be substituted by the excel pivot
use cases for this can be:

Sorry but I can't have two requests titled "pivot" that are going to represent the same thing. If you want to provide an alternative example  for #11012, please post it in a comment at #11012

I'm going to consider this a duplicate
