### ISSUE TITLE
New icon charge issue

### ISSUE THREAD

**Issue by weihongyu12** [FortAwesome/Font-Awesome#12713]
Since v5.0.7, some of the icons are for a fee, such as the medical icon. In my understanding, only light is a charge. Is the new icon after most will be a charge icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Free icons are a subset of Pro icons also in the solid set

Eg: https://fontawesome.com/icons/alarm-clock?style=solid alarm clock is not available in font awesome free

You can filter for free icons on the docs with the "free" filter: https://fontawesome.com/icons?d=gallery&m=free

Hope it helps

Closing here
