### ISSUE TITLE
"How to use" documentation incorrectly uses `fas` class in examples

### ISSUE THREAD

**Issue by nickgrealy** [FortAwesome/Font-Awesome#12710]
### Describe the problem

"How to use" documentation incorrectly uses `fas` as a classname in the examples.

e.g.
```html
<i class="fas fa-camera-retro"></i>
```
https://fontawesome.com/how-to-use/svg-with-js#how-it-works

### What did you expect?

I expected an image of a camera icon to show. Instead, I received a square box (i.e. the icon was not found).

When I changed the class name to `fa`, the icon showed correctly.

i.e.
```html
<i class="fa fa-camera-retro"></i>
```

**Answer:** https://stackoverflow.com/a/21815998/782034

### What version and implementation are you using?

Version: `"font-awesome": "4.7.0"`
Browser and version: `Chrome Version 65.0.3325.181 (Official Build) (64-bit)`

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

http://jsbin.com/gerekoq/edit?html,output

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate**

** similiar...
- https://github.com/FortAwesome/Font-Awesome/issues/12692 - not properly completed issue
- https://github.com/FortAwesome/Font-Awesome/issues/12654 - relates to FontAwesome5 (not `4.7.0`)

**Comment by wolfy1339** [comment]
The docs are for FA5, you are using FA4.7

The docs for 4.7 are here: https://fontawesome.com/v4.7.0/
This issue can now be closed

**Comment by nickgrealy** [comment]
Perfect, thank you!
