### ISSUE TITLE
Icon Request: fab-java

### ISSUE THREAD

**Issue by Chifth** [FortAwesome/Font-Awesome#12711]
Please, add Java icon (not javascript). Coffee cup :) 
Also be useful to add icons for anotherold platforms: Symbian, N-Gage 2.0, Symbian 3, Dendy, Sega, Playstation, etc.. 

Or Extensions icon pack (exe, zip, txt, jpg, etc...)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #386, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
