### ISSUE TITLE
briefcase-medical is not working with Version 5.0.9

### ISSUE THREAD

**Issue by titosobabas** [FortAwesome/Font-Awesome#12723]
Hi. I'm working on WordPress and all the icons are working well, but with `<i class="fas fa-briefcase-medical"></i>`is not working, what I'm doing wrong? Thanks.

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).

**Comment by tagliala** [comment]
@titosobabas please check that you or your plugins are not loading an old version of font awesome

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

this is often the case with wordpress
