### ISSUE TITLE
Typo in the website

### ISSUE THREAD

**Issue by beratcelik** [FortAwesome/Font-Awesome#12734]
The code of the icon for the unlock has a typo. The class "fa" is written as "fas": <i class="fas fa-unlock-alt"></i>
check the link:
https://fontawesome.com/icons/unlock-alt?style=solid

**Comment by rywn** [comment]
This is correct for Font Awesome 5 (see [Icon Name Changes](https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes)), if you're using Font Awesome 4 the docs are here: [https://fontawesome.com/v4.7.0/](https://fontawesome.com/v4.7.0/)
