### ISSUE TITLE
Mailchimp icon

### ISSUE THREAD

**Issue by argoncobalt** [FortAwesome/Font-Awesome#12737]
Putting in a request for a Mailchimp icon; would definitely use if you had it. Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3379, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
