### ISSUE TITLE
Problem with loading font in IE9

### ISSUE THREAD

**Issue by cyChop** [FortAwesome/Font-Awesome#1273]
Hello,

I have just updated from Font-Awesome 3.0.2 (including FA's CSS in Bootstrap's LESS) to Font-Awesome 3.1.1 (compiling FA's LESS in Bootstrap's LESS) and I discovered icons just stopped working in IE9.

This is not restricted to my own website, as FA's documentation site will only display the unknown character instead of icons, even in FA 3.2.0.

This is a corporate IE9, so there might be settings which are eluding me, but the fact remains that FA 3.0.2 worked just fine and FA 3.1.1+ do not.

Am I missing something, or does it apply to anybody else?

Thanks for the great work anyway.

C.

**Comment by cyChop** [comment]
I guess this has gone stale. I cannot check on that installation anymore since this has changed, so I'll just close this and let anybody encountering this again open a new issue with more information.

**Comment by tagliala** [comment]
@cyChop thanks for the heads-up
