### ISSUE TITLE
Bad colors 

### ISSUE THREAD

**Issue by amindiary** [FortAwesome/Font-Awesome#12732]
https://fontawesome.com/cheatsheet
I don't think those colors are good! Im using Chrome and Windows 10

![image](https://user-images.githubusercontent.com/2544046/38084985-95dafc46-3357-11e8-8ac5-db3b097bac6e.png)

**Comment by robmadole** [comment]
@talbs would you mind taking a look at this?

**Comment by talbs** [comment]
@robmadole yep! On it and will make sure we don't give anyone a surprise eye exam with this any longer.

**Comment by talbs** [comment]
This contrast issue is fixed on the live cheatsheet views ([Free](https://fontawesome.com/cheatsheet) and [Pro](https://fontawesome.com/cheatsheet/pro) now. Thanks for letting us know about it. 😄 

![fontawesome com_cheatsheet](https://user-images.githubusercontent.com/163763/41741838-3f13cd2a-756a-11e8-9c95-f0068209fdd7.png)

![fontawesome com_cheatsheet_pro](https://user-images.githubusercontent.com/163763/41741850-4afd50de-756a-11e8-8f71-1f0213e66974.png)
