### ISSUE TITLE
Font size doesn't increase

### ISSUE THREAD

**Issue by davehowson** [FortAwesome/Font-Awesome#12739]
I am using FA in my Laravel project. I have installed it via npm and in my app.js

```
import fontawesome from '@fortawesome/fontawesome';
import faUser from '@fortawesome/fontawesome-free-solid/faUser';
fontawesome.library.add(faUser)
```

In my HTML, I have 

```
<div class="count-icon">
            <i class="fas fa-user"></i>
</div>
```

I tried increasing the size by
`<i class="fas fa-user fa-10x"></i>`
But it didn't work

By increasing the font-size of the parent div, but nothing works.
It only increases till 20px, and further, it will only increase the height of its svg container but not the font (icon) size.

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).
