### ISSUE TITLE
Icon Request: fa-kronos

### ISSUE THREAD

**Issue by EmmausHomes** [FortAwesome/Font-Awesome#12745]
![workforce ready logo 3](https://user-images.githubusercontent.com/37940964/38151727-f546025a-3453-11e8-95d2-e1860bc81816.png)
We would like to add this to our intranet site and link it to a url.
Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this icon?

**Comment by aethior** [comment]
>Kronos, PeopleDoc, and Ultimate Software rebrand as UKG
Company launches new brand identity to chart path forward as one of world’s largest cloud companies
([more info](https://www.ukg.com/en-GB/about-us/newsroom/kronos-ultimate-software-unveil-plans-rebrand-ukg))

cc/ @tagliala

**Comment by tagliala** [comment]
Closing here, we have a fancy new template to request brands: https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+

Feel free to create a new request if this brand is still needed
