### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by ironflamez** [FortAwesome/Font-Awesome#12747]
Please if it is possible can we have a bootstrap icon 

![image](https://user-images.githubusercontent.com/37951351/38161170-90ec7b96-3515-11e8-91f8-0984dcaf4b1b.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1828 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
