### ISSUE TITLE
 Icon request: fa-brain

### ISSUE THREAD

**Issue by cbielich** [FortAwesome/Font-Awesome#12743]
How do you not have a brain as an icon? I am requesting one.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
