### ISSUE TITLE
better business bureau icon needed for font awesome

### ISSUE THREAD

**Issue by thyronne** [FortAwesome/Font-Awesome#12740]
Help

**Comment by JCCasey** [comment]
@thyronne sorry but a lot of people have been waiting years for a BBB icon to be added. It won't happen anytime soon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5797, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
