### ISSUE TITLE
Tree shaking seems not to work for free-brands-svg-icons

### ISSUE THREAD

**Issue by karptonite** [FortAwesome/Font-Awesome#12744]
I'm importing font-awesome icons into an Angular project. Tree shaking seems to work fine for imports from `@fortawesome/pro-solid-svg-icons` and `@fortawesome/pro-regular-svg-icons`, but if I import any from `@fortawesome/free-brands-svg-icons`, it seems that I get the whole set of brand icons (over 300K).
my imports look like:
```
import { faFacebookF, faTwitter } from '@fortawesome/free-brands-svg-icons';
```

I'm using versions `5.1.0-4` for each of the icon packs, but even if I upgrade to pre-release, `5.1.0-7`, I seem to have the same problem. Is there something different about the free icon set that might cause this issue?

**Comment by robmadole** [comment]
@karptonite please provide a reproducible test case. codesandbox.io is a great choice to do this.

**Comment by karptonite** [comment]
Here is a reproducible test case: https://github.com/karptonite/icons-tree-shaking-test
To reproduce the problem clone the repo, then install the dependencies with `yarn`.
run `yarn run build-stats` to do a production build with stats.
then run `yarn run bundle-report`  to see the package breakdown. You'll see something like this:
![bundle stats](https://www.evernote.com/l/ABpBVuPYg6JDp5-oXrwAVbAgKZHw71blvO8B/image.png)

Note that it has over 300k of imports for a single icon from the brands icons. I did NOT see this this problem with `@fortawesome/pro-solid-svg-icons` icons, but didn't include them in this test so that a pro license wasn't required to see the problem.

**Comment by karptonite** [comment]
@robmadole were you able to get my repo running and verify the issue?

**Comment by karptonite** [comment]
Pushed a new version of the repro with the missing dependency added.

**Comment by tagliala** [comment]
This only affects 5.1.x, right?

**Comment by robmadole** [comment]
@tagliala the fix for this is in the 5.1 branch. That's where all of our tree shaking efforts are going.

@karptonite I've pushed the 5.1.0-8 pre release. Can you give this a try? I updated your repo to use the new version and it fixed the size for me locally.

**Comment by karptonite** [comment]
@robmadole That seems to have done the trick. Thanks for the quick action on this!

**Comment by c0bra** [comment]
@robmadole I'm having the same (or similar?) issue with fontawesome-free-solid. I tried the latest 5.1.x alpha but no joy. Maybe the fix hasn't made it in there?
