### ISSUE TITLE
Icon request: fa-tipi

### ISSUE THREAD

**Issue by mj-kirkpatrick** [FortAwesome/Font-Awesome#12759]
A tipi icon would be a great addition to help represent Indigenous or native topics on a website.

Something like this...
https://thenounproject.com/term/tipi/1751/

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [⛺](http://emojipedia.org/tent/) U+26FA Tent
- [🏕️](http://emojipedia.org/camping/) U+1F3D5 Camping

**Comment by aethior** [comment]
Hi @mj-kirkpatrick,

This icon was added in v5.4.0.
Check https://fontawesome.com/icons/campground

Regards.

cc/ @tagliala
