### ISSUE TITLE
ReadMe Logo Broken!

### ISSUE THREAD

**Issue by gkoberger** [FortAwesome/Font-Awesome#12754]
Oh no, seems like things got a bit wonky with the ReadMe logo :) Thanks for looking into this <3

### Describe the problem

https://fontawesome.com/icons/readme?style=brands

The brandmark on FontAwesome looks like this:

![image](https://user-images.githubusercontent.com/381393/38178187-2fe74044-35c2-11e8-9543-51f045a79c68.png)

### What did you expect?

It should look like this:

![image](https://user-images.githubusercontent.com/381393/38178199-697693d2-35c2-11e8-9f8a-37e84950dc21.png)

### What version and implementation are you using?

Version: 5.0.9
Browser and version: Chrome 65 (but also Firefox and Safari)

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

### Reproducible test case

https://fontawesome.com/icons/readme?style=brands

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by gkoberger** [comment]
Here's the SVG: https://cl.ly/1I1r2y1G2l0x/ReadMe_Logo-brandmark.svg

**Comment by robmadole** [comment]
@sensibleworld @talbs can you gents check this out?

**Comment by gkoberger** [comment]
Thanks @robmadole :)

**Comment by talbs** [comment]
Sorry about that, @gkoberger! We're getting this fixed right up for ya.

**Comment by talbs** [comment]
@gkoberger, our apologies again for that issue with the Readme.io logo. That should now be resolved in our latest 5.0.10 release - https://fontawesome.com/icons/readme?style=brands. Let us know if you spot anything else off.

**Comment by gkoberger** [comment]
Thank you so much, @talbs (and everyone else!). Really appreciate it!!
