### ISSUE TITLE
Icons not showing up and all.js is showing some error.

### ISSUE THREAD

**Issue by abhigyantiwari** [FortAwesome/Font-Awesome#12753]
I am using Font-Awesome (FortAwesome) v5.0.9. The icons won't show up and getting following error as in console:

![screenshot from 2018-04-01 17-50-37](https://user-images.githubusercontent.com/16822592/38173111-fa8596da-35d5-11e8-9a05-abbbbb7df922.png)

I have included cdn as follows:
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>

Other dependencies above the cdn:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Faster+One|Quicksand" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
```

As said every time to put scripts in footer, if I include cdn in footer than the page shows no icons. But, after refreshing, the icons show up.

Users sees this after login:
![screenshot from 2018-04-01 18-03-23](https://user-images.githubusercontent.com/16822592/38173188-57f4c3ee-35d7-11e8-9dca-0666d2856850.png)

What do I expect:
![screenshot from 2018-04-01 18-03-57](https://user-images.githubusercontent.com/16822592/38173190-625eb056-35d7-11e8-8e97-591872ee667b.png)

The project is SPA, AngularJS (1.6.x) based.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, angular needs its own component to work

Please refer to #12046

**Comment by abhigyantiwari** [comment]
Thanks for the link :+1:  Sorry for replying late.
