### ISSUE TITLE
Icon request: icon-satellite (icon-antenna, icon-radar, icon-dish, icon-cable)

### ISSUE THREAD

**Issue by harnishdesign** [FortAwesome/Font-Awesome#12757]
**Something Like this :**

<img src="https://cdn3.iconfinder.com/data/icons/gray-toolbar-5/512/antenna-128.png" />

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5659, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
