### ISSUE TITLE
Icon Request: fa-baby_bottle

### ISSUE THREAD

**Issue by SupremeSimon** [FortAwesome/Font-Awesome#12752]

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🍼](http://emojipedia.org/baby-bottle/) U+1F37C Baby Bottle

**Comment by vincentwansink** [comment]
I also need a baby bottle for a daycare app. but I guess since this was requested three years ago, this is not happening anytime soon.

**Comment by aethior** [comment]
@tagliala `childhood (category)` label for this request?

**Comment by sensibleworld** [comment]
This was released in 6.5.2: https://fontawesome.com/icons/bottle-baby?f=classic&s=regular
