### ISSUE TITLE
ethereum / bitcoin / btc

### ISSUE THREAD

**Issue by cooscreations** [FortAwesome/Font-Awesome#12762]
Consider adding 'ethereum' to category 'currency', or adding 'bitcoin' and 'btc' to 'payments & shopping' so that they can be found in the same place(s)

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this

**Comment by talbs** [comment]
Thanks for the suggestion, @cooscreations. Sorry for the radio silence and delay responding. I've made those changes to our metadata and they should go out with our next release shortly.

**Comment by talbs** [comment]
Thanks again for getting in touch, @cooscreations. 

* `ethereum` has been added to our "Currency" category - https://fontawesome.com/icons?d=gallery&c=currency.
* `bitcoin` and `btc` are now in our Payments & Shopping "category - https://fontawesome.com/icons?d=gallery&c=payments-shopping.

Let us know if we can make any other icon organization better.  😄
