### ISSUE TITLE
fa-hands-helping not in svg with JS? Or webfonts?

### ISSUE THREAD

**Issue by if-jds** [FortAwesome/Font-Awesome#12775]
Hi There!

I am having problems getting `hands-helping` to show up with a local installation of FontAwesome Pro 5.0.8, SVG with JS. I've tried experimenting with multiple icons using a vanilla page with an `<i>` tag. Something like `<i class="fa fa-alarm-clock"></i>` totally works (a pro-only icon to boot) but `<i class="fa fa-hands-helping"></i>` gives me a sad question mark box 😔 

I dug into `/svg-with-js/js/fontawesome-all.js` and could not find an SVG version when searching for the code `f4c4` (hands-helping). I totally see other stuff like alarm-clock (f34e).

I also switched to the WOFF version and I'm also getting blankness.

Is there something I'm doing wrong, or are we missing an SVG? I could download the raw SVG and add it to a file but I'm not sure whatsup. I grepped in the fontawesome directory and I don't see any "hands-helping."

Thank you in advance for your support!!

**Comment by if-jds** [comment]
Also an issue in 5.0.9

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since this is not an issue with the free version, could you please open this issue in the Pro repository?

Thanks

https://jsfiddle.net/tagliala/b1938pcs/1/
