### ISSUE TITLE
Newer Icons not working, checked FAQ

### ISSUE THREAD

**Issue by saeho** [FortAwesome/Font-Awesome#12779]
Hello, I'm a Font Awesome PRO user.

For some unknown reason, the newer icons (such as chess and person-carry) doesn't work. I made sure to download the latest 5.0.9 version, hosted the CSS/fonts locally-in-app, and also made sure to update all the webfont files.

Is there something I'm missing? I already checked the FAQ.

**Comment by tagliala** [comment]
Hi, 

could you please open this issue in the Pro repository since it does not affect the free version?

https://jsfiddle.net/tagliala/21sv06jc/1/

Thanks
