### ISSUE TITLE
Icon request: event-line

### ISSUE THREAD

**Issue by Bounty31** [FortAwesome/Font-Awesome#12774]
### What can it be used for?
It can be used to represent an Event/Event entry with people, Event check-in desk

### Example image (optional)
https://thenounproject.com/search/?q=barrier&i=1467007
Could be stacked with other available icons to make:
- https://thenounproject.com/term/velvet-rope/837277/
- https://thenounproject.com/term/red-carpet/1200466/
- https://thenounproject.com/term/red-carpet/609913/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I would like a better name for this request

**Comment by Bounty31** [comment]
Hello,

do you mean a better icon name? If yes then you could call it also one of the following:
- Event barrier
- Event rope

**Comment by Hipska** [comment]
This is similar as #9012, but then for people instead of cars.

**Comment by sensibleworld** [comment]
Closing in favor of: https://github.com/FortAwesome/Font-Awesome/issues/14321
