### ISSUE TITLE
Icon request: Charity with Euro Symbol

### ISSUE THREAD

**Issue by hebbet** [FortAwesome/Font-Awesome#12772]
currently in [charity category](https://fontawesome.com/icons?d=gallery&c=charity) all icons with currency have the dollar sign.

please provide also 

- [ ] box-euro
- [ ] donate-eur
- [ ] handholding-euro
- [ ] hands-euro
- [ ] euro-cirle
- [ ] euro-square

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by MYCODEC** [comment]
We are a German company that uses Fontawesome very intensively. The Dollar-Icons in a "Euro" version would be very important for us, because I can't use the Dollar-Icons because of our customers.

**Comment by tagliala** [comment]
Please keep in mind that this icon can be implemented with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/139/

Or with custom CSS

Demo: https://jsfiddle.net/tagliala/c9rxutqe/39/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by MYCODEC** [comment]
please provide also

- [ ] search-euro
- [ ] sack-euro
- [ ] lightbulb-euro
- [ ] funnel-euro
- [ ] comments-euro
- [ ] comment-euro
- [ ] badge-euro
- [ ] file-invoice-euro
- [ ] comments-alt-euro
- [ ] comments-alt-euro
- [ ] comment-alt-euro
- [ ] eur-square
- [ ] box-eur
- [ ] eur-circle
- [ ] hands-eur
- [ ] hand-holding-eur

**Comment by tagliala** [comment]
Let's use https://github.com/FortAwesome/Font-Awesome/issues/19891 for the request in subject

Feel free to open new, individual requests according to our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)
