### ISSUE TITLE
Icon Request：zhihu（知乎）

### ISSUE THREAD

**Issue by taylortaurus** [FortAwesome/Font-Awesome#12781]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4439, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by taylortaurus** [comment]
thx
