### ISSUE TITLE
New Icon Request : Google Pay

### ISSUE THREAD

**Issue by vinid223** [FortAwesome/Font-Awesome#12788]
I notice there is a Apple Pay but not a Google Pay for Android device. It could be interesting to have it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12519, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
