### ISSUE TITLE
Breaking VueJS

### ISSUE THREAD

**Issue by ilicmarko** [FortAwesome/Font-Awesome#12793]
Lets say you want to use Font awesome with Vuejs, you go in your header add the js file like in the [instructions](https://fontawesome.com/how-to-use/svg-with-js). All done right? **WRONG**

Including font-awesome like this will break your Vuejs conditional rendering where the icon appears. Because FA restructures the DOM and Vue doesn't know about it.

Here is a really simple example:
JS:
```javascript
new Vue({
  el: "#app",
  data: {
    isTrue: true
  }
})
```

HTML (in the header include the FA CDN):
```html
<div id="app">
  <button @click="isTrue = !isTrue">Break me</button>
  <div v-if="isTrue">
    Hi there
  </div>
  <div v-else>
    <i class="fas fa-user"></i>
  </div>
</div>
```

You can click on the button once and it will never work again.

Here is a [JSFiddle](https://jsfiddle.net/m4verick/eywraw8t/19100/).

I am not sure if this can get fixed but at least state it somewhere, because I lost an hour of work trying to debug a simple if. 
_Note: I didn't test this on react but it will probably break there to_

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not into Vue.JS, but did you take a look at this: https://fontawesome.com/how-to-use/js-component-packages#vue-js ?

**Comment by ilicmarko** [comment]
Thanks I did not notice that section, also didn't expect it to break Vue 😢
