### ISSUE TITLE
Icon request: fa-files-compare (two file side by side)

### ISSUE THREAD

**Issue by Meteor0id** [FortAwesome/Font-Awesome#12795]
Title sais it all. Suggesting fas and far versions to be part of font-awsome free.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example?

**Comment by Meteor0id** [comment]
![viewtab](https://user-images.githubusercontent.com/34976212/40551411-1c36e02c-603d-11e8-9800-965228c5ffb1.jpg)

It's just one of those features we see all over desktop world, on pretty much any OS. A way to show pages or documents side-by-side. But what I don't find everywhere is a good universal icon for it. Attached the first example I could find in a quick image search.

**Comment by tagliala** [comment]
Thanks for the clarification

Basically two `file` icons side by side
https://fontawesome.com/icons/file?style=solid

Meanwhile, You can achieve this with both the svg framework and transformations

**Comment by tagliala** [comment]
let's use #16514
