### ISSUE TITLE
fas fa-hands-helping not showing properly though css web use

### ISSUE THREAD

**Issue by Meteor0id** [FortAwesome/Font-Awesome#12797]
Haven't investigated why, unfortuantly I don't have the time at this moment. But it appears this icon is buggy.

While I am writing about this anyway, I would also like to propose that **fas fa-handshake-alt** be added to font-awsome free. (It is a rather basic icon for charities, and a good alternative to fa-hands-helping whithout a potential for being seen as a decending point of view.) Thank you for considering.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot replicate.

https://jsfiddle.net/tagliala/21sv06jc/4/

Please make 100% sure that you are using FA 5.0.9

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
