### ISSUE TITLE
couch icon in "@fortawesome/free-solid-svg-icons" package is missing

### ISSUE THREAD

**Issue by llell** [FortAwesome/Font-Awesome#12791]
It is available here: https://fontawesome.com/icons?d=gallery&q=couch&s=solid 
But i can't found couch icon, installed all free packages in my angular project, still cant find it there.. maybe i am missing something.
version is "5.1.0-4"

**Comment by PovarovDenis** [comment]
A lot of icons are missing in the package: instagram icon for example

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> version is "5.1.0-4"

please update to 5.5.0, 5.1.0-4 is a preview release that could be based on an older version of FA 5.0

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

Hope it helps

Closing here
