### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [FortAwesome/Font-Awesome#12806]
When adding a domain to the Pro CDN and forgetting to remove `http://`

```
Remove that http stuff!
What, are reading RFC 3986 right now? We'll take care of http and https for you.
```

should say
```
Remove that http stuff!
What, are we reading RFC 3986 right now? We'll take care of http and https for you.
```

**Comment by talbs** [comment]
Thanks for the heads up, @ChrisThompsonTLDR. We'll get that missing "we" added in. 😄

**Comment by talbs** [comment]
Okay, @ChrisThompsonTLDR. We got that typo fixed in the current version of https://fontawesome.com/account/services. Thanks again for bringing it to our attention. 😄 

![image](https://user-images.githubusercontent.com/163763/38622293-d8649e46-3d70-11e8-9d41-33cc4cf0473a.png)
