### ISSUE TITLE
Icon Request: fa-fingerprint

### ISSUE THREAD

**Issue by mantiqueira** [FortAwesome/Font-Awesome#12804]
For finger print authentications in mobile apps :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4431 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
