### ISSUE TITLE
Icon Request: fa-breastfeeding

### ISSUE THREAD

**Issue by Lydie84** [FortAwesome/Font-Awesome#12802]
Hi I am working on a baby site and a breeastfeeding icon is missing like this one https://png.icons8.com/ios/1600/breastfeeding.png would be amazing

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9657, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
