### ISSUE TITLE
New icon : Interac'

### ISSUE THREAD

**Issue by AlexandreBouille** [FortAwesome/Font-Awesome#12803]
Interac payment 
http://interac.ca/en/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4445, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
