### ISSUE TITLE
Icon Request: fa-stroller

### ISSUE THREAD

**Issue by Lydie84** [FortAwesome/Font-Awesome#12800]
Hi, I think that would be useful for accessibility to have a stroller icon like this one https://png.icons8.com/ios/1600/stroller.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6124, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
