### ISSUE TITLE
Depending on CDN src some work others break

### ISSUE THREAD

**Issue by tcardlab** [FortAwesome/Font-Awesome#12819]
Trying to use Google Drive Icon (free Icon)
`<a href="#" class="fab fa-google-drive"></a>`

Source from email: (recieved yesterday)
`<script src="https://use.fontawesome.com/[hexkey].js"></script>`
Everything but Google Drive works(::before does not appear in its html)

Source from [FA/get-started](https://fontawesome.com/get-started):
`<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>`
Only Google Drive works. All others are flash alternate ?/!.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The code received by email is the old CDN implementation for Font Awesome 4. If you are interested in FA5, please follow the instructions at https://fontawesome.com/get-started

> Only Google Drive works. All others are flash alternate ?/!.

FA4 and FA5 works differently. Please make sure you are following the updated instructions at https://fontawesome.com/how-to-use/svg-with-js

If you are not able to make FA5 work, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps, closing here
