### ISSUE TITLE
Problem: don't see home-heart in my web fontawesome Pro

### ISSUE THREAD

**Issue by Doctorrr** [FortAwesome/Font-Awesome#12810]
just don't see `<i class="far fa-home-heart"></i>` symbol.  fontawesome-pro-5.0.9.zip

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
