### ISSUE TITLE
Squarespace and fa-layers

### ISSUE THREAD

**Issue by bhrg** [FortAwesome/Font-Awesome#12816]
I uploaded the .woff file to use with my font-family for icons and in my Code Injection, I am linking to the Font Awesome 5 CDN. I am trying to add a layer style (fa-layers) but it is not working. What step am I missing?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by tagliala** [comment]
No feedback, closing here
