### ISSUE TITLE
icon request: jeton

### ISSUE THREAD

**Issue by tapastwain** [FortAwesome/Font-Awesome#12812]
poker chip / jeton like this: https://image.flaticon.com/icons/svg/33/33810.svg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1004, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
