### ISSUE TITLE
Serve PNG version in your webapp?

### ISSUE THREAD

**Issue by janstieler** [FortAwesome/Font-Awesome#12823]
Hi,
it would be great if the your webapp would also serve a png version of the icons and not only the svg. Sometimes I need a png version and to download is mostly the fastest way instead to create the png self or search it in my local pro folders.

Cheers

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but PNG version of icons are out of scope.

Feel free to use an alternative tool to convert all your SVGs to PNGs, with the color and the size you need for your project

Hope it helps

Closing here
