### ISSUE TITLE
Clipboard List not working

### ISSUE THREAD

**Issue by Adamghd** [FortAwesome/Font-Awesome#12824]
fa-clipboard-list is showing up as the flashing "?" 
Shown at http://amghd.com/homepage/homepage.html on the first D2L link.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You are using FA 5.0.6. clipboard-list has been introduced in 5.0.7

Please update your font awesome version

Hope it helps
