### ISSUE TITLE
fontawesome-i2svg and excluding certain elements

### ISSUE THREAD

**Issue by shazdeh** [FortAwesome/Font-Awesome#12826]
Is it possible to exclude certain elements from being affected by the "SVG with JS" script? I have some elements that have the `fa-` prefix however I do not want them to use the SVG icons.
Ideally having a certain classname (something akin to, `do-not-apply-i2svg`) that prevents the i2svg from being applied to that element would be really useful.

**Comment by robmadole** [comment]
You are 100% correct @tagliala

**Comment by tagliala** [comment]
Closing here, please check out  #12437

**Comment by shazdeh** [comment]
@tagliala Thank you for your consideration.
Main issue we're trying to solve is compatibility between FA v4 and and v5 being included in the same page (v5's `i2svg` script is being added by another app which we don't have control over), so that's another use case for such a feature.

**Comment by tagliala** [comment]
@shazdeh thanks. I will check again here after that #12437 will be resolved
