### ISSUE TITLE
fontawesome-free-brands - question about the license

### ISSUE THREAD

**Issue by paula-w** [FortAwesome/Font-Awesome#12821]
Hi guys,
I’m looking for some info about the license for thefontawesome-free-brands library.  According to [NPM](https://www.npmjs.com/package/@fortawesome/fontawesome-free-brands), it was released under “none” license. 
Can anybody help me out?  Thanks in advance!

**Comment by My1** [comment]
the package was moved around anyway. the new one has a proper license listed:
https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510
https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons

**Comment by tagliala** [comment]
Hi, sorry for the late reply!

This has been fixed in version 5.4.0 via 5362994408184a0f86b2b63b5971eac15eca1664

**Comment by tagliala** [comment]
Ref: #13808
