### ISSUE TITLE
Checkbox style with Fontawesome 5 not working on firefox

### ISSUE THREAD

**Issue by camdav** [FortAwesome/Font-Awesome#12838]
Hi, I'm trying to change the default checkbox style using Fontawesome 5.
Here is the code:

https://plnkr.co/edit/eFwKDCuNAMeY5IHjcgzf

This is working perfectly on the latest Chrome and Safari but not in Firefox.
Am I doing something wrong?

Thanks

**Comment by gbjbaanb** [comment]
yup, your link is broken.

**Comment by gbjbaanb** [comment]
I have no idea what your facheckinput class is, this looks the same in both FF and Chrome.

https://jsfiddle.net/wbovrf8w/1/

**Comment by camdav** [comment]
this is the css:

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've removed all references to font awesome in this pluck: https://plnkr.co/edit/TRreCDBup6qcIavEcxMA?p=preview

It works on chrome but it doesn't work on firefox. I'm using "C" for checked, "U" for unchecked.

This issue does not depend on Font Awesome. Please use another way of styling checkbox. I'm not convinced of `visibility: hidden`. 

Ref:
- https://getbootstrap.com/docs/4.0/components/forms/#checkboxes
- https://stackoverflow.com/questions/39732253/cross-browser-custom-checkbox

Hope it helps

Closing here

**Comment by camdav** [comment]
Thanks for the anwser. Bye
