### ISSUE TITLE
caret icon not working on mac

### ISSUE THREAD

**Issue by siyacr7** [FortAwesome/Font-Awesome#12830]
caret icon didn't work in font awesome 5 when using css psudo element unicode not supporting on mac book air (chrome)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by siyacr7** [comment]
[not working in mac air - chrome.zip](https://github.com/FortAwesome/Font-Awesome/files/1898265/not.working.in.mac.air.-.chrome.zip)

**Comment by tagliala** [comment]
@siyacr7 do you mind to host your reproducible test case elsewhere?

Maybe a fiddle on jsfiddle. You can start with this one: https://jsfiddle.net/tagliala/cy2gk6ys/

**Comment by siyacr7** [comment]
here is the updated link : https://jsfiddle.net/cy2gk6ys/1/
when fontawesome 4 fonts adding it'll work fine

**Comment by tagliala** [comment]
Got it.

https://jsfiddle.net/tagliala/cy2gk6ys/2/

Please remember `font-weight: 900`. The only font name to use should be `Font Awesome 5 Free`

Docs: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Hope it helps

**Comment by siyacr7** [comment]
I tried it works windows and ubuntu. But not working in apple mac (chrome browser)

**Comment by tagliala** [comment]
I'm on macOS 10.13.4 / Chrome 65 and it works.

Please double check that your css is correct.

Please also check this fiddle with the minimum amount of css required to make pseudo elements work: https://jsfiddle.net/tagliala/cy2gk6ys/3/
