### ISSUE TITLE
FA 5 rendering icons that should not be visible in Preact code

### ISSUE THREAD

**Issue by pjverity** [FortAwesome/Font-Awesome#12831]
I'm having a problem mentioned in [this issue](https://github.com/FortAwesome/react-fontawesome/issues/48) although I'm not using the react-fontawesome library. In this case I'm using the Preact library, having migrated off React. I'm exclusively using the `<i>` tag. I'm not using any React compatibility library either, just pure Preact. Also, it only seems to occur using the production build of the code and does not occur using FA 4. I have some JSX conditional rendering of the form

```
{expression-a &&
 <tr><td>Spinner <i class='fas fa-fw fa-circle-notch fa-spin' /></td></tr>
}
{expression-b &&
 <tr><td>No Spinner</td></tr>
}
```
It should render either 'Spinner (spinning icon)' or 'No Spinner', but what I get is 'Spinner (spinning icon)' > re-render > 'No Spinner (spinning icon)'

I'm using the following in my index.html

```
<script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
```

I've never seen this appear in the development build of my code (I'm using Webpack), but it always appears in the production build. I'm just getting my head in to all of this, so apologies if I've missed some important info!

**Comment by robmadole** [comment]
Hey @pjverity we don't have a Preact library. You should switch to web fonts with CSS instead.

**Comment by pjverity** [comment]
Ah, ok, thanks. I thought (naively) that as I was simply using `<i>` tags it wouldn't matter. I'll switch to the method you've suggested.
