### ISSUE TITLE
Icon request: icon-network-graph

### ISSUE THREAD

**Issue by ChristelSwift** [FortAwesome/Font-Awesome#12841]
hi there,
would it be possible to include an icon for a network graph?  just some bubbles linked by some lines would do the trick: 
 [https://en.wikipedia.org/wiki/Graph_theory](https://en.wikipedia.org/wiki/Graph_theory)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Maybe a duplicate of #5944 ?
