### ISSUE TITLE
Stripe logo not allowed

### ISSUE THREAD

**Issue by martinleblanc** [FortAwesome/Font-Awesome#12842]
I'm from Iconfinder (www.iconfinder.com) and we have a copy of the Font Awesome icons on the site. We just received a take-down notice from Stripe. They don't want their logo being distributed (even for free). It's a good idea to remove the Stripe logo from the official version of Font Awesome to avoid legal issues.

**Comment by davegandy** [comment]
Thanks for the heads up.

**Comment by PeterShaggyNoble** [comment]
@martinleblanc, was it just `stripe` and `stripe-cc` they asked you to remove or `stripe-s` also?
