### ISSUE TITLE
Typo in lastfm-square.svg

### ISSUE THREAD

**Issue by wttw** [FortAwesome/Font-Awesome#12847]
brands/lastfm-square.svg has a stray "&amp;gt;" inside it's svg element.

**Comment by tagliala** [comment]
Thanks!

Ref: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/advanced-options/raw-svg/brands/lastfm-square.svg

**Comment by tagliala** [comment]
Fixed in 5.0.11
