### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by ForbiddenChunk** [FortAwesome/Font-Awesome#12843]
I am using;
https://use.fontawesome.com/releases/v5.0.1/css/all.css

I have in my SCSS

`&:before{
        content: "\f0dd";
  	font-family: "Font Awesome 5 Solid";
}`

But still only getting square, if swap it for;

`&:before{ content: "\f16c";  font-family: "Font Awesome 5 Brands"; }`

It works, don't understand why it's not showing?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please notice that SVG version works differently from CSS.

Here it is a link to the proper documentation: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

(errors: `font-family` must be `"Font Awesome 5 Free"` and you should add `font-weight: 900`)

**Comment by jed84** [comment]
I have had the same font applied on the website for a long-time and at some point, the Sort-down Icon stopped loading.

Instead, an unwanted character is displayed:
![obraz](https://user-images.githubusercontent.com/47121522/164343055-ffb66597-b27f-4ce0-a2eb-f3a90e45791e.png)

The code in the css is as follow:
#site-navigation ul li.menu-item-has-children > a:after{content:'\f0dd'; font-family: FontAwesome; font-size:12px; position:absolute; top:-3px; padding-right:2px; padding-left: 10px;}

Could you please let me know what has changed and how can I fix it so the icon starts loading again?

**Comment by tagliala** [comment]
@jed84 please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) with all the information required and provide a reproducible test case, so we can help
