### ISSUE TITLE
FA 5.0.10 contains old 5.0.9 Font-Awesome/advanced-options/metadata/categories.yml 

### ISSUE THREAD

**Issue by TheDiveO** [FortAwesome/Font-Awesome#12844]
The recent release 5.0.10 contains the old 5.0.9  Font-Awesome/advanced-options/metadata/categories.yml albeit new icons were added. This can be seen both in the commit log as well as in GitHub's repo files view.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see two new icons:
- java
- pied-piper-hat

They both belong to brands category, which is not part of `categories.yml`. I think there aren't issue

@robmadole could you please confirm?

**Comment by robmadole** [comment]
:+1: confirmed

**Comment by TheDiveO** [comment]
Ahh, I didn't realize that. Thank you very much! I was under the (false?) impression that the brand icons were as well as catogorized into the different categories as the other icons. Good to know.

So can we then close this issue?

**Comment by tagliala** [comment]
@TheDiveO you're welcome

Closing here
