### ISSUE TITLE
Font Awesome 5 changed Unicode code points

### ISSUE THREAD

**Issue by garretwilson** [FortAwesome/Font-Awesome#12857]
From reading https://fontawesome.com/how-to-use/upgrading-from-4 I thought I could upgrade easily to Font Awesome 5. Nothing is ever easy.

I have a lot of CSS that adds pretty icons in front of certain styles, like this:

```css
 .annotation:not(.token):before {
    font-family: FontAwesome;
    content: "\F24A\00A0";
 }
```

The upgrade guide didn't tell me I needed to change the `font-family`.

The upgrade guide didn't tell me I need to add a certain font weight. (Why!? Now I have to look up each one of these codes.)

But worst of all, `F24A` doesn't work anymore!

1. I have to go to https://fontawesome.com/v4.7.0/cheatsheet/ to find out what F24A was for. Ah, it was a ` fa-sticky-note-o`.
2. Now I have to go to https://fontawesome.com/how-to-use/upgrading-from-4 and look up `sticky-note-o`, finding out it changed to `sticky-note` in the "regular" group.
3. Then I have to go to https://fontawesome.com/cheatsheet, go to the "regular" section, search for `sticky-note`, and find out that the code is now `F249`.

Why? _Why?_ It's the same icon. Why did the Unicode code point have to change??

Now I'm going to have to tediously go through each one of these encodings, which is very error prone and will take ages. Why, Font Awesome? Why switch Unicode code points around?? Why cause pain?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I understand your disappointment and we are sorry.

Font Awesome 5 is quite different from FA4 and we were not able to preserve backward compatibility for every use case, in particular with pseudo elements. [v4 shim](https://fontawesome.com/how-to-use/upgrading-from-4#v4-shim) do the job for the average use case.

Please note that FA4 and FA5 provide [variables](https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/scss/_variables.scss#L17-L891), so you can figure out which icon are you using in an easy way. I would recommend `$fa-var-sticky-note` instead of `\f249`. You should still find & replace some names, but the upgrade will be less painful

Hope it helps

Closing here

**Comment by garretwilson** [comment]
Oops, I may have written so much that you didn't pick up on my main points. Let me summarize.

* The documentation for upgrading to Font Awesome lists CSS name changes, but neglects to cover Unicode code point changes. Please put in a request to update the migration documentation.
* I wondered why Font Awesome 5 arbitrarily changed the Unicode code points for some icons but not for others. Saying that "Font Awesome 5 is different from Font Awesome 4" doesn't explain anything.

> Please note that FA4 and FA5 provide variables…

I think you're referring to [SASS variables](https://sass-lang.com/guide#topic-2), but I'm not using SASS. I'm just using plain CSS.

Anyway, Font Awesome 5 is out, and it is what it is. I don't want to belabor the issue or try further to get you to understand it, but it would be nice if you updated the documentation to cover the changed Unicode code points. Thanks, and have a good weekend.

**Comment by tagliala** [comment]
> The documentation for upgrading to Font Awesome lists CSS name changes, but neglects to cover Unicode code point changes. Please put in a request to update the migration documentation.

@talbs any chance of mentioning pseudo elements in the docs?

> I think you're referring to SASS variables, but I'm not using SASS. I'm just using plain CSS.

Got it. It will be definitely harder to upgrade but given your use case you should consider a preprocessor

> I wondered why Font Awesome 5 arbitrarily changed the Unicode code points for some icons but not for others. Saying that "Font Awesome 5 is different from Font Awesome 4" doesn't explain anything.

There are three different styles in FA5: light, regular and solid. Icons share the same unicode point between styles but they have different font weigt.

Eg: `sticky-note` and `sticky-note-o` have different unicode point in FA4 but they have the same unicode point in FA5. Keeping the same unicode points, would bring to unused unicode points in FA5. Hope it helps in understanding the reason of unicode changes

**Comment by talbs** [comment]
@tagliala and @garretwilson, thanks for the heads up and good suggestion. I'll see what we can do about getting those unicode changes documented alongside the name changes we currently have at https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes. Thanks much!

**Comment by talbs** [comment]
Okay, gang. We've added the Unicode values for version 5 icons right alongside the naming differences between versions 4 and 5 here - https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes.

I'll be adding some more details to help with upgrading when using CSS Pseudo elements shortly. Thanks for bringing this to our attention. 😄
