### ISSUE TITLE
Some Glyphs Missing from Font Files?

### ISSUE THREAD

**Issue by zoladesigners** [FortAwesome/Font-Awesome#12854]
I just downloaded and installed 5.0.10 font files. I am using the desktop method in photoshop.

I am trying to use the phone-plus icon by copy and pasting from the cheat sheet: https://fontawesome.com/cheatsheet/pro

Even if I already have a text layer with an icon in it using the FontAwesome font, trying to copy and paste it into that text field just gives me a blank icon. The regular phone icon works fine using the same method.

I looked at the font file using Font Book where you can actually see the glyphs in each font and that and some other icons I'm not able to use are not even there. For example piggy-bank is another icon I have this same issue with and I don't see that icon in Font Book when I am viewing Font Awesome either.

Any insight would be appreciated, thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this an issue with FA5 Free or Pro?

BTW, please
1. Double check that you have installed the latest version of FA (maybe remove the current installed version and reinstall)
2. Check your font style. Solid icons require **bold** style selected

![image](https://user-images.githubusercontent.com/556268/38755511-493cbdf0-3f66-11e8-8525-74733d8c5d0a.png)

FA 5.0.10 Pro / Windows 10 / Photoshop CC 2017

**Comment by zoladesigners** [comment]
Thank you!
This was happening with Font Awesome Pro, but removing the currently installed Font Awesome Pro fonts from Font Book then re-adding them solved my problem. 

I'll make sure to install them fresh for each update from now on.
