### ISSUE TITLE
Icon fa-spinner has unequal width and height for webfont

### ISSUE THREAD

**Issue by palych3** [FortAwesome/Font-Awesome#12850]
Icon fa-spinner has unequal width and height for webfont.
When big sized fa-spinner is used with fa-pulse it's not centered.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per #671, please use the SVG framework or make sure you are using 16px multiples to minimize the wobbling effect.

Sorry but we cannot fix this
