### ISSUE TITLE
Font Awesome 5 prevents CSS mixing of font weights.

### ISSUE THREAD

**Issue by garretwilson** [FortAwesome/Font-Awesome#12858]
I'm trying to convert to Font Awesome 5, and I'm highly skeptical of this newfangled approach of controlling by font weight. The problem is that it conflates icons! The difference between `question-circle-o` and `question-circle`, for example, is not that `question-circle` is merely "bolder" than the other. They are different icons!!

Consider this CSS from my existing Font Awesome 4.7 stylesheet (for real). For a `<q>` that has a `class` of `pedagogical question`, it shows a lightbulb and a question mark inside a circle:

```css
 q.question.pedagogical:before {
  font-family: FontAwesome;
  content: "\F0EB\00A0\F059\00A0";
 }
```

How do I do that in Font Awesome 5? Oops, `far fa-lightbulb` and `fas fa-question-circle` are now two different font weights!! I'll have to switch them both to the `far` or to the `fas` font weight.

My gut reaction is that the decision to classify `-o` icons as merely a different font weight misses the point. We want bolder or lighter things. We want solid or open things. Those are orthogonal concepts, and we shouldn't have to use font weight to control solidity.

Yes, I can work around this, and no, it's not a show stopper. I'm just pointing out the larger semantic problem.

**Comment by garretwilson** [comment]
I'm afraid I don't have the time, but I did provide a code snippet above. Just show me how I would do the same thing with Font Awesome 5; once you try I think you'll quickly understand the issue. Cheers!

**Comment by tagliala** [comment]
Where is the issue here? https://jsfiddle.net/tagliala/cy2gk6ys/6/

**Comment by tagliala** [comment]
Ah, ok, got it.

Sorry but this is not a supported use case.

Please use another approach:
1. https://jsfiddle.net/tagliala/cy2gk6ys/10/
2. https://jsfiddle.net/tagliala/cy2gk6ys/12/

Hope it helps

Closing here

**Comment by garretwilson** [comment]
You'll see the issue if you look at them both, side by side, under Font Awesome 4 and Font Awesome 5.

Look at https://fontawesome.com/v4.7.0/cheatsheet/ .

In Font Awesome 4, `F059` is a solid `fa-question-circle`, and you've turned it into a ` fa-question-circle-o`, which in Font Awesome 4.7 is `F29C`.

My greater point is not necessarily "how do I do this?" but trying to explain to the Font Awesome team that conflating the concepts of "filled vs open" with "bold versus regular" wasn't the best approach. These are two different concepts. `F059` and `F29C` were two different icons in FA 4.7, not just a "normal version and a bolder".

So my point is that tying `font-weight` to "solid versus regular" is mixing apples and oranges, and will cause issues such as the one I'm pointing out here.

**Comment by garretwilson** [comment]
> Sorry but this is not a supported use case.

But it was a supported case under Font Awesome 4.7!!!!

> Please use another approach

The approaches you provide are convoluted (absolute positioning in a pseudo-class?) and use bad CSS practices (pixel alignment). And in Font Awesome 4.7 I didn't have to do them.

Like I said, I know it's not going to change. I just wanted to bring it to the attention of the FA team. I'm not asking for an argument. I'm just asking that the team consider the implications of conflating the orthogonal concepts of "boldness" and "solidity". Thank you.

**Comment by tagliala** [comment]
> The approaches you provide are convoluted (absolute positioning in a pseudo-class?) and use bad CSS practices (pixel alignment). 

They are just examples, showing that you can achieve those results in different ways. Feel free to fix them for your needs

> Like I said, I know it's not going to change. I just wanted to bring it to the attention of the FA team. 

Thanks. As I mentioned in another thread, FA5 is different and this use case is no longer supported.

@robmadole Is there any chance to support again this use case?

**Comment by robmadole** [comment]
No, we had to weigh a lot of considerations when making this change with 5. We are locked in and it's not going to change.
