### ISSUE TITLE
Squared corners icons like in V4?

### ISSUE THREAD

**Issue by maximedupre** [FortAwesome/Font-Awesome#12851]
For example, this icon had squared corners in the V4 (https://fontawesome.com/icons/play?style=solid)

How can i achieve the same result using the V5?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The play icon on FA4 also has rounded corners, but they were less pronounced: https://fontawesome.com/v4.7.0/icon/play/

Font Awesome style requires soft corners for its icon, so the best you can do is to keep using FA4

At the moment, icons with shape corners are out of scope, they will require a separate style

Hope it helps

Closing here
