### ISSUE TITLE
Icon Request: fa-myspace

### ISSUE THREAD

**Issue by sonicmindsmusic** [FortAwesome/Font-Awesome#12861]
It is for myspace.com, formerly a very popular social media platform for bands and musicians,

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #831, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
