### ISSUE TITLE
Suggestion: when searching the icon gallery for "reload" or "refresh", then include "redo" in the search results

### ISSUE THREAD

**Issue by markmaruska** [FortAwesome/Font-Awesome#12862]
I was looking for an icon similar to the Chrome browser's "Reload this page" button --that is an arrow in a circular form pointing clockwise.  However, when I search for "reload" or "refresh" as common verbs for this action in the browser, then the icon gallery only matches to "sync" and "retweet", when really I was expecting it to match on "redo".

I'm talking about finding icons from the gallery online, here:  https://fontawesome.com/icons?d=gallery

SUGGESTION:  Please add a mapping so when people search for "reload" or "refresh", then the icon gallery search results will include the "redo" icon set.

Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is legit because browsers use "redo" (instead of sync) to represent a reload icon

**Comment by talbs** [comment]
@tagliala yep! We'll see what we can do about dusting off this icon's metadata shortly.

**Comment by talbs** [comment]
Sorry for the delay, gang. This metadata change should go out in our next release shortly.

**Comment by talbs** [comment]
Thanks again for bringing this to our attention @markmaruska. We've updated our metadata and https://fontawesome.com/icons?d=gallery&q=reload and https://fontawesome.com/icons?d=gallery&q=refresh now include `redo` as part of their results. 😄
