### ISSUE TITLE
Example needed for docs

### ISSUE THREAD

**Issue by gbjbaanb** [FortAwesome/Font-Awesome#12864]
I've noticed a few niggles in upgrading from FA 4.7, and one that niggles me the most is alignment.

So I'd like to request an example of a simple form, the login form that was shown in the 4.7 examples:

```
<div class="input-group margin-bottom-sm">
  <span class="input-group-addon"><i class="fa fa-envelope fa-fw"></i></span>
  <input class="form-control" type="text" placeholder="Email address">
</div>
<div class="input-group">
  <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
  <input class="form-control" type="password" placeholder="Password">
</div>
```

This produces the following in 4.7:
![image](https://user-images.githubusercontent.com/6808175/38780999-be2b6f6e-40d6-11e8-8b42-d81ae12b8991.png)

and the following in 5.0.8:
![image](https://user-images.githubusercontent.com/6808175/38781051-a1dfd4f2-40d7-11e8-8ba1-24888e4b8fb1.png)

Any chance you could show us how to make the latter look as good as the former? You'll notice the lack of border around the icons, and the icons are vertically aligned to the top of the associated control. 

Help from the experts who made FA would be appreciated here. thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the first example is using Twitter Bootstrap

Here it is an example using Twitter Bootstrap 4.1.0 and FA5 Free webfont with solid style

https://jsfiddle.net/tagliala/cy2gk6ys/16/

Hope it helps

Closing here

**Comment by gbjbaanb** [comment]
It does indeed - stick in the examples for everyone else. cheers.
