### ISSUE TITLE
This... I can't even describe how bad this is.....

### ISSUE THREAD

**Issue by DoubleThePsycho** [FortAwesome/Font-Awesome#12865]
The Discord icon has 2 different eyes, both of them being too big, one being completely messed up!
[https://imgur.com/a/H9E9P](https://imgur.com/a/H9E9P)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please double check that you are using the official Font Awesome 5.0.10 release?

https://fontawesome.com/icons/discord?style=brands

Meanwhile, closing here

**Comment by DoubleThePsycho** [comment]
Yes, I am currently on 5.0.10.

**Comment by tagliala** [comment]
@DoubleThePsycho could you please provide a reproducible test case?

**Comment by DoubleThePsycho** [comment]
It looks as if it has fixed itself, or my guy played with the CSS again.

**Comment by tagliala** [comment]
Glad you solved

**Comment by julian100004** [comment]
I still have this problem. Any known fix or mistake could be making?

**Comment by tagliala** [comment]
@julian100004 please download/use the CDN link of the latest official Font Awesome Release from https://fontawesome.com/

**Comment by julian100004** [comment]
@tagliala I'm using
_<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">_

isn't this the latest release?

**Comment by tagliala** [comment]
@julian100004 yes it is. Please provide a reproducible test case if you think there is an issue with font awesome. 

Working demo: https://jsfiddle.net/tagliala/auk4bgc6/1/

**Comment by julian100004** [comment]
I found my Problem. Here is a fiddle with the problem I had. Apparently the font-weight was the problem. I don't know if that is known or not but i know it now. Thanks for the help.

https://jsfiddle.net/auk4bgc6/3/

**Comment by DoubleThePsycho** [comment]
FontLimitedBecauseItDoesntLikeFontWeightButKindaCooIGuess > FontAwesome
