### ISSUE TITLE
OTF font file not installing/validating in OSX fontbook

### ISSUE THREAD

**Issue by mikeroyer** [FortAwesome/Font-Awesome#1287]
OSX 10.8.4

I've had no issues installing the .otf in the past but for some reason Font Book is rejecting this updated file "1 serious error was found. do not use this font."

**Comment by winghouchan** [comment]
Just a comment to say that I've had this exact problem as well on OSX 10.10.2 .

Not sure what is wrong since the error message isn't that helpful, but I'll try a few restarts over the course of today. Hopefully it'll work later.

**Comment by TYancy** [comment]
I have the same problem with OSX 10.11.6. If I try to install the .otf or the .ttf I always get a message, "1 serious error was found. Do not use this font." There is no explanation, just the message. I tried redownloading Font Awesome, but it makes no difference.

**Comment by jaltin** [comment]
I am also experiencing the exact same issue as @TYancy...
