### ISSUE TITLE
Icon request: fa-siren

### ISSUE THREAD

**Issue by Shyzer** [FortAwesome/Font-Awesome#12879]
I could desperately use a siren / alarm font. This could be used to highlight breaking news, emergency information, or anything else extremely important.

The [revolving light emoji](https://emojipedia.org/police-cars-revolving-light/) is a good example of this.

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🚨](http://emojipedia.org/police-cars-revolving-light/) U+1F6A8 Police Cars Revolving Light

**Comment by wmd-jrc** [comment]
A siren icon will make a great contribution to a public safety set. This icon will be used to indicate an emergency, emergency route, or warning. It could also be used to indicate emergency services that are available. 

Example Link:
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiV3-HDj9bkAhVQF6wKHZU9C3QQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fsiren%2Bicon&psig=AOvVaw0KWYDmnXjoE61tylBUHAmS&ust=1568750059462068

**Comment by aethior** [comment]
Hi @Shyzer,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/light-emergency and https://fontawesome.com/icons/light-emergency-on.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
@sensibleworld it looks like light-emergency and light-emergency-on are vertically centered but they do not use the same baseline

bell and bell-on behaves in a more consistent way, but I see that the "on" lines do not change the height of the icon

- https://fontawesome.com/icons/bell?s=solid
- https://fontawesome.com/icons/bell-on?s=solid

Is this something that should be addressed?

**Comment by sensibleworld** [comment]
This is fixed in our next build.

But I also wanted to note that we have a specific "siren" icon, too: https://fontawesome.com/icons/siren-on?s=solid
