### ISSUE TITLE
Icon request: Filter remove Icon

### ISSUE THREAD

**Issue by KTurle** [FortAwesome/Font-Awesome#12873]
You have a great icon for Filter called "Filter" but I would also love to see a Filter Remove Icon

something along the lines of the following (can be with an x or minus) 
![image](https://user-images.githubusercontent.com/21363991/38890253-df32c468-424e-11e8-8509-264fad757a5a.png)
thanks - hope to see this soon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #650 and #5309, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
