### ISSUE TITLE
Icon request: discord  (for 4.7)

### ISSUE THREAD

**Issue by ngowanlock** [FortAwesome/Font-Awesome#12872]
Hi I wanted to find out if the icon for Discord could be added to version 4.7?  as this would be really useful for some web design I'm working on.  Thanks!

I noticed its on V5 
https://fontawesome.com/icons/discord?style=brands

**Comment by tagliala** [comment]
Hi!

Thanks for 

Sorry but 4.7.0 is in EOL.

You can still [grab the svg from 5.0](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/raw-svg/brands/discord.svg) and [build a custom version](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

Hope it helps

Closing here
