### ISSUE TITLE
CDN examples from website do not work?

### ISSUE THREAD

**Issue by kspearrin** [FortAwesome/Font-Awesome#12883]
The basic CDN examples highlighted on the FA homepage do not seem to be working.

Javascript example (JS resource added): https://jsfiddle.net/b2k8a1pf/2/
CSS Example (in HTML head): https://codepen.io/anon/pen/JvPQEP

Am I doing something wrong?

**Comment by kspearrin** [comment]
Apparently `fal` is not included in "all".

**Comment by tagliala** [comment]
Hi,

thanks for being part of the Font Awesome community.

`fal` style is exclusive to FA pro.

If you are a Pro backer, please make sure you have logged in to fontawesome.com and that you have selected "Pro"

Hope it helps
