### ISSUE TITLE
Light font weight icons in free list of icons

### ISSUE THREAD

**Issue by suhsil-streammarket** [FortAwesome/Font-Awesome#12887]
Please provide light font weight icons in free list.   and add more e commerce icons 

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #1733, please follow that request

> and add more e commerce icons

If you need new icons, open new issues making sure that they follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
