### ISSUE TITLE
icon-request : icon-running

### ISSUE THREAD

**Issue by sidtechno** [FortAwesome/Font-Awesome#12893]
Icon for running, runner (male, female)
Good for Triathlon site, running club

**Comment by Ronyo** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
