### ISSUE TITLE
Icon request: sd-rose

### ISSUE THREAD

**Issue by anarchodin** [FortAwesome/Font-Awesome#12890]
### What can it be used for?

The rose held in a closed fist is an emblem of the social democratic movement. It is the logo of the Socialist International, and is used either directly or indirectly in the imagery of any number of significant political parties, including the French <i>Parti socialiste</i> and the United Kingdom's <i>Labour Party</i> - neither of which are today full members of the SI. The icon would be of use as a stylistically-compatible way of showing affiliation, for instance on a blog site side by side with social media links also represented by Font Awesome icons.

I understand that including political imagery can be controversial, but would also note that Font Awesome includes emblems from Star Wars. The fictional political movements these emblems represent are routinely used in point-scoring arguments over real politics, and therefore might have comparable, if lesser, issues.

I am unfortunately not aware of any iconography associated internationally with either the conservative or the liberal movements, so I cannot suggest competing icons for those.

### Example image (optional)

![A rose held in a fist](https://upload.wikimedia.org/wikipedia/en/thumb/1/1a/Red_Rose_%28Socialism%29.svg/170px-Red_Rose_%28Socialism%29.svg.png)
(From [Wikipedia](https://en.wikipedia.org/wiki/File:Red_Rose_(Socialism).svg))

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
