### ISSUE TITLE
Icon request: fa-file-png

### ISSUE THREAD

**Issue by code-johnson** [FortAwesome/Font-Awesome#12896]
Hi,

A png file icon would be awsome.

Maybe something like this:

![png-icon-example](https://user-images.githubusercontent.com/4602897/38946628-a80ec534-42ff-11e8-901a-25404268d05c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment those requests are out of scope.

Please take advantage of stacking and layering features to implement them.

SVG: https://fontawesome.com/how-to-use/svg-with-js#layering
CSS: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Hope it helps

closing here
