### ISSUE TITLE
Allow IP addresses for CDN version

### ISSUE THREAD

**Issue by corysimmons** [FortAwesome/Font-Awesome#12902]
I notice you automatically accept `localhost` addresses, and live domains like `example.com`, but you don't accept IP addresses (with or without ports).

Could you add support for this?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this about FA5 Pro CDN?

**Comment by corysimmons** [comment]
Yup

**Comment by tagliala** [comment]
Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here
