### ISSUE TITLE
Scholar icon

### ISSUE THREAD

**Issue by Willtl** [FortAwesome/Font-Awesome#12901]
Would be possible to add google scholar icon? 

https://scholar.google.com/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #541, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
