### ISSUE TITLE
Web site not showing Icons

### ISSUE THREAD

**Issue by carloshuggins** [FortAwesome/Font-Awesome#12914]
The website is listing the icons but can see the actual icon

![image](https://user-images.githubusercontent.com/12879002/39007575-bc4d460c-43cb-11e8-8579-1a59c55a06d1.png)

**Comment by tagliala** [comment]
Same here. 

> I think the service might be down or something?
Yes, there are some CDN issues in Europe.

https://status.fortawesome.com/

They are marked as solved but I can't see icons in Italy

**Comment by ajwilco** [comment]
Same. I haven't ever had a problem until today, but now I'm getting the following in my JS console.

> None of the “sha384” hashes in the integrity attribute match the content of the subresource.

**Comment by emileber** [comment]
I emptied my cache and did a hard reload and the icons aren't shown. I do not see any errors in the console.

One thing that looks weird is the "stub" like comments (usually seen with Vue component) in the source:

![image](https://user-images.githubusercontent.com/3286135/39018190-58b03d70-43f3-11e8-9cf9-831e5c6f8e1f.png)

**Comment by Some-T** [comment]
It is working on mine now.

**Comment by emileber** [comment]
It's back online! 🎉 🍾 ❤️

**Comment by tagliala** [comment]
Closing here

If it is still an issue, feel free to comment
