### ISSUE TITLE
Icon Request: icon-percent

### ISSUE THREAD

**Issue by jwaala** [FortAwesome/Font-Awesome#1292]
great shortcut link by the way to create the issue

This icon is for a "check our rates" link in a mobile banking application.

**Comment by fko2221** [comment]
+1000

**Comment by mnelsonwhite** [comment]
+1

**Comment by andreaslangsays** [comment]
+1

**Comment by martinsifra** [comment]
+1

**Comment by JoshWeb** [comment]
+1

**Comment by franco104** [comment]
+1

**Comment by KrunchMuffin** [comment]
well 4.3 came and went and no percent. really surprised and disappointed

**Comment by rakeshok** [comment]
+1

**Comment by bfvww2** [comment]
+1. Percent icon is absolutely necessary for many business projects.

**Comment by willynx** [comment]
+1. Percent, need it

**Comment by Purus** [comment]
+1 for percentage icon..

**Comment by visby** [comment]
+1

**Comment by LePaul** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1... how many do you want to have?

**Comment by boxheading** [comment]
+1

**Comment by meirotstein** [comment]
+1

**Comment by LePaul** [comment]
Why don't you (Font Awesome) do something like crowdfunding? I mean, if the "crowd" wants something, let them "fund" it. So, if an icon is badly wanted, set the price and wait for the donations reach the desired amount. Everybody happy..

**Comment by tagliala** [comment]
@LePaul Dave already did something like that with Font Awesome black tie: https://www.kickstarter.com/projects/232193852/font-awesome-black-tie

In this specific case, you can use [this simple workaround](http://jsfiddle.net/tagliala/e9yfxsfj/8/) (yes, I know about uniformity of glyphs...)

If you need to add a new icon in FA, there are many **free** options: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by dudapasquali** [comment]
+1

**Comment by aurevilly** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by himedlooff** [comment]
:+1:

**Comment by GwenLoguir** [comment]
+1

**Comment by Rewt0r** [comment]
+1

**Comment by parabol** [comment]
+1

**Comment by Mirozh** [comment]
+1

**Comment by coffeeontie** [comment]
+1

**Comment by rmwebs** [comment]
Probably pointless given how long this has now been open, but +1

**Comment by AladdinSuni** [comment]
+1

**Comment by matisoffn** [comment]
+1

**Comment by Igcorreia** [comment]
+1

**Comment by grapho** [comment]
+1 fa-percent

**Comment by ynelsoftware** [comment]
+1

**Comment by noyg** [comment]
+1

**Comment by rubenscd** [comment]
+1

**Comment by FilipeSantiago** [comment]
+1

**Comment by karimmtarek** [comment]
+1

**Comment by avackova** [comment]
+1

**Comment by bobmulder** [comment]
+1

**Comment by VicCebedo** [comment]
+1

**Comment by krv** [comment]
+1

**Comment by mnelsonwhite** [comment]
[ ] fa-percent
[x] fa-pied-piper
[x] fa-pied-piper-alt

I am sure glad we got that alt for pied piper. Very useful thanks :)

**Comment by MarcBalaban** [comment]
:+1

**Comment by lipefit** [comment]
+1

**Comment by grapho** [comment]
how to i stop watching this issue?  its depressing me...

**Comment by kylejeske** [comment]
I was thinking the same ... clearly this isn't happening.

**Comment by bobmulder** [comment]
Well... Nice way to chat with stangers XD

**Comment by broox** [comment]
on the right hand column of the github issue there is an "unsubscribe" button under a "notifications" sub-heading.

**Comment by KrunchMuffin** [comment]
4.4 came and went and fa-percent just went.

**Comment by lyhil** [comment]
+1

**Comment by gabyrh77** [comment]
+1

**Comment by theunexpected1** [comment]
+1

**Comment by TheMadComputerScientist** [comment]
+1

**Comment by cscrum** [comment]
+1

**Comment by TonGarcia** [comment]
+1

**Comment by beornf** [comment]
+100%

**Comment by trikadin** [comment]
+1

**Comment by angeldeejay** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by makavv** [comment]
+1

**Comment by TheSharpieOne** [comment]
+1

**Comment by ivoarm** [comment]
+1

**Comment by thehatter** [comment]
+1

**Comment by jijisv** [comment]
+1

**Comment by nitoloz** [comment]
+1

**Comment by Googlecloud12** [comment]
http://jsfiddle.net/

**Comment by felipediesel** [comment]
+1

**Comment by Thyme1152** [comment]
+1

**Comment by cameroun** [comment]
+1

**Comment by collinprice** [comment]
+1

**Comment by thmsmtylr** [comment]
+1

**Comment by anthony-sheehy** [comment]
+1

**Comment by Beaudinn** [comment]
+1

**Comment by mistryb** [comment]
+1

**Comment by b22n** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by krv** [comment]
+1

**Comment by arianmaykon** [comment]
+1

**Comment by camilopayan** [comment]
+1

**Comment by iboylmz** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by djravine** [comment]
+1

**Comment by Sir-J** [comment]
+1

**Comment by krivaten** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by KrunchMuffin** [comment]
Thank you!

**Comment by djravine** [comment]
Thank You!
