### ISSUE TITLE
Icon request: icon-prestashop

### ISSUE THREAD

**Issue by ManuStrozor** [FortAwesome/Font-Awesome#12924]
### What can it be used for?

This icon could be used to represent the dashboard page of prestashop or a shop made with prestashop. I'm creating a prestashop module/webapp and it could be create to add an icon to my <a> link that redirect to the dashboard of prestashop.

### image

It could be the popular mascot preston head.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2080, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by ManuStrozor** [comment]
That's not a duplicate...i talk about mascot preston head the #2080 is an old icon !
