### ISSUE TITLE
Icons missing from CDN and icon list

### ISSUE THREAD

**Issue by kyrrr** [FortAwesome/Font-Awesome#12927]
The ```share``` and ```share-alt``` icons are not displaying when fetched through ```cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/...```, nor are they listed in the icon list at ```https://fontawesome.com/icons?d=gallery&q=share```

This seems to also be affecting ```facebook-square```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is probably due to some third party extensions or privacy options that affects social related icons.

Ref: #1799
