### ISSUE TITLE
Using the Font Awesome Pro CDN on a localhost Domain

### ISSUE THREAD

**Issue by tone4407** [FortAwesome/Font-Awesome#12928]
Hey all.

I'm using the Font Awesome Pro CDN. I've added 'localhost' as one of my domains so I could use FA5 on my local machine before going live. It initially worked for about half a day, then all of a sudden it stopped. Now I'm receiving this error:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://pro.fontawesome.com/releases/v5.0.10/css/all.css' with computed SHA-256 integrity '0eNsFOuBYxbtHwGVdWGqjfzOWh1UHhGoPS6jRMSenEg='. The resource has been blocked.

Any ideas as to why?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by auxiliaryjoel** [comment]
anymore help on this issue?
I can load free icons in my localhost build ok, but not the Pro icons?

**Comment by tagliala** [comment]
Hi @auxiliaryjoel 

I've tried to replicate your issue but I couldn't.

Here it is my source code (`index.html`):

```html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Awesome Pro CSS -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-xVVam1KS4+Qt2OrFa+VdRUoXygyKIuNWUUUBZYv+n27STsJ7oDOHJgfF0bNKLMJF" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, <span class="fal fa-globe-americas"></span>!</h1>
  </body>
</html>
```

I've run a simple http server with python

```sh
python -m SimpleHTTPServer 8000
```

Here it is the output:

![image](https://user-images.githubusercontent.com/556268/57581224-bfa97580-74b4-11e9-920f-843b426621e5.png)

I didn't have to whitelist `localhost` because it has been already whitelisted in the CDN, IIRC

If you still have issues, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by auxiliaryjoel** [comment]
where did you get the Font Awesome Pro CSS link from?
I get told to "Step1. copy this code" on the Font Awesome website, but there is no code displayed and not links on the page that reference the code?  
So consequently I am using the URL to existing font awesome that I've always used:
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

**Comment by auxiliaryjoel** [comment]
@tagliala Here is example screenshot:
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/12387409/57590289-30609880-756e-11e9-8232-4823c72754b4.png">
As my site is currently http://localhost:8888/  Font Awesome won't allow me to enter that (it tells me it's already covered).
So I cannot progress from this window, and as you can see in Step 1 it tells me to copy code,but does not provide any code to copy?

**Comment by auxiliaryjoel** [comment]
Update: @tagliala I added a fake domain just so I could progress to next step, which then did allow me to obtain the new code to include in my head.
It works now, but Font Awesome should consider a way to provide that code to localhost users as currently the process is not very user-friendly.

**Comment by tagliala** [comment]
@auxiliaryjoel thanks, I've got the issue now. Let's continue on the Pro repository

**Comment by Relequestual** [comment]
What happened to the fontawesome pro repo?

**Comment by jeeshenlee** [comment]
I'm experiencing the same problem, my localhost URL would be http://abc.local:6851

I tried to whitelist on the portal but I'm getting this message "Jinkies, Scoob! That domain is not allowed. Testing domains are included by default (localhost, jsbin.com etc.)!"

**Comment by tagliala** [comment]
@jeeshenlee can you please check the development console and provide the error you are getting when trying to load the CDN from your local domain?

**Comment by jeeshenlee** [comment]
@tagliala I've attached the screenshot below

![image](https://user-images.githubusercontent.com/1011777/130428632-af98f1f8-8188-48fb-b064-2030b0ecea0a.png)

**Comment by tagliala** [comment]
Sorry, cannot replicate

I'm serving your kit on a `.local` tld, with a simple python server `python3 -m http.server 8000`:

![image](https://user-images.githubusercontent.com/556268/130435972-b0b95e5f-6150-496f-91f3-6a4460230be2.png)

Could you please:
- Avoid the redirect from `http://` to `https`
- Make sure you are including your kit with this very same markup:
  ```html
  <script src="https://kit.fontawesome.com/83006b2a72.js" crossorigin="anonymous"></script>
  ```
- Check your application CORS
- Check request headers

In any case, as a Pro Customer, you can ask for dedicated support by sending an email to hello@fortawesome.com

**Comment by MustafaHossaini** [comment]
localhost is fine . but `127.0.0.1` is not

**Comment by yuyuslab** [comment]
@MustafaHossaini 
I made the domain restriction to none, so that I can use that in local environment. Then, when I deployed, I set the domain. If that helps!
<img width="1289" alt="Screenshot 2025-01-12 at 13 45 25" src="https://github.com/user-attachments/assets/8536b88c-98d6-4256-a2b6-766feb5a57d0" />
