### ISSUE TITLE
Icon Request: fa-shopify

### ISSUE THREAD

**Issue by unlockr** [FortAwesome/Font-Awesome#12923]
Shopify icon :grin:

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3850, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by unlockr** [comment]
So sorry

**Comment by waltergammarota** [comment]
Since I needed this I did it on my own font. 
In case it can be useful for someone, here it is: 
https://github.com/waltergammarota/wgicons
[wgicons](https://github.com/waltergammarota/wgicons
)
