### ISSUE TITLE
Icon request: icon-required

### ISSUE THREAD

**Issue by ajtruckle** [FortAwesome/Font-Awesome#12938]
### What can it be used for?

On forms where a red asterix is shown

### Icon request checklist

- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [required] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [Yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi, does [asterisk](https://fontawesome.com/icons/asterisk?style=solid) fit your use case?

https://fontawesome.com/icons/asterisk?style=solid

**Comment by ajtruckle** [comment]
😃
