### ISSUE TITLE
Icon request: icon-enter (return)

### ISSUE THREAD

**Issue by pkuczynski** [FortAwesome/Font-Awesome#1293]
Enter key icon. Could be similar to level-down rotated 90 deg clockwise

**Comment by Extaze** [comment]
+1

**Comment by gregzx** [comment]
Guys, just use <i class="fa fa-level-down fa-rotate-90"> . It looks good.

**Comment by gregzx** [comment]
Guys, just use \<i class="fa fa-level-down fa-rotate-90"\> . It looks good.

**Comment by tostasqb** [comment]
good one @gregzx :+1:

**Comment by malard** [comment]
+1

**Comment by LarsSimonsen** [comment]
+1

**Comment by michalpalaxo** [comment]
+1

**Comment by tekpuf** [comment]
+1

**Comment by tibraga** [comment]
+1

**Comment by danielme85** [comment]
+1.

**Comment by FenixGit** [comment]
+1

**Comment by JasonQSY** [comment]
+1

**Comment by stuartBainbridge** [comment]
+1

**Comment by PezCoder** [comment]
+1

**Comment by dannygunawan** [comment]
+1

**Comment by ekandreas** [comment]
+1

**Comment by trousyt** [comment]
+1

**Comment by pravdomil** [comment]
+1

**Comment by CanyonCasa** [comment]
+1, using "far fa-share-square fa-rotate-180"

**Comment by mdestagnol** [comment]
+1. Would be really helpful to get all the other special keyboard keys y the way, in a style that works with each other: Escape, Control, Command, Option, Delete, Function, Shift, Tab, Windows, etc. They're helpful to display keyboard shortcuts.

**Comment by ilya-lopukhin** [comment]
doubling this!

**Comment by marounmelhem** [comment]
If you don't want to use the ↵ character, you can use: 
`<i class="fa fa-reply"></i>`
And rotate it:
`<i style="-webkit-transform: scaleX(-1);transform: scaleY(-1);" class="fa fa-reply"></i>`

**Comment by DavydeVries** [comment]
Why not use `<i class="fas fa-level-down"></i>` like your own suggestion and add the css class `fa-rotate-90` to rotate it?

**Comment by kisvegabor** [comment]
+1

**Comment by davizzx** [comment]
+1

**Comment by fahadmaqsood** [comment]
+1

**Comment by LoGA80** [comment]
Agreed, I could use a return icon as well.

**Comment by gsantner** [comment]
![grafik](https://user-images.githubusercontent.com/6735650/85478156-0294b280-b5bc-11ea-9cdb-928d9269146b.png)

`fa fa-level-down fa-rotate-90`

**Comment by codyreed** [comment]
+1

**Comment by SSBarik** [comment]
+1

**Comment by sensibleworld** [comment]
<img width="711" alt="Screen Shot 2021-03-30 at 12 15 55 PM" src="https://user-images.githubusercontent.com/529604/113021538-b03b8000-9151-11eb-8f5e-e2b37805a15d.png">

This is now available (as `arrow-turn-down-left`) in the latest alpha release of version 6: http://fontawesome.com/download

**Comment by anter090909** [comment]
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-down-left">
  <polyline points="9 10 4 15 9 20" />
  <path d="M20 4v7a4 4 0 0 1-4 4H4" />
</svg>

**Comment by anter090909** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-down-left">
  <polyline points="9 10 4 15 9 20" />
  <path d="M20 4v7a4 4 0 0 1-4 4H4" />
</svg>
`
