### ISSUE TITLE
Alternative "Help" icons?

### ISSUE THREAD

**Issue by ajtruckle** [FortAwesome/Font-Awesome#12947]
Hi !

Here is a bit of my menu:

![menu](https://user-images.githubusercontent.com/7985331/39231262-61fe785c-4861-11e8-978d-ab489c483c75.jpg)

Is it possible to perhaps have some alternative help icons? I am not sure what. But it would be nice for variety.

Thanks!

Andrew

**Comment by FlyHighest** [comment]
there are question,question-square and question-circle. maybe you'd like some rotations? you can use data-fa-transform="rotate-xx" in label <i> . detailed information about transforms can be found here https://fontawesome.com/how-to-use/svg-with-js

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Along with [transformations and rotations](https://fontawesome.com/how-to-use/svg-with-js#power-transforms), you could consider:
- https://fontawesome.com/icons/exclamation-circle?style=solid
- https://fontawesome.com/icons/star?style=solid

I'm going to close here at the moment for the following reasons:
- The use case: would a third entry in that menu require another alternative version of help?
- I should avoid requests for alternative versions of already existent icons if there are no strong motivations behind
