### ISSUE TITLE
Icon request: Jet.com

### ISSUE THREAD

**Issue by michaeljberry** [FortAwesome/Font-Awesome#12941]
### What can it be used for?

To be used with an Ecommerce application

### Example image (optional)

http://logos.wikia.com/wiki/File:Jet_logo.svg

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
>On May 19, 2020, Walmart announced that it was shutting down Jet.com,[10] which they later did without warning on June 4, directing visitors to use Walmart.com instead. ([more info](https://en.wikipedia.org/wiki/Jet.com))

cc/ @tagliala
