### ISSUE TITLE
Icon Request: fa-c# or fa-csharp

### ISSUE THREAD

**Issue by OdarGM** [FortAwesome/Font-Awesome#12955]
Can you add icon with the C# logo? :D

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8365, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
