### ISSUE TITLE
Fontawesome 4 and fontawesome 5 used in same project created issue

### ISSUE THREAD

**Issue by ruchitaghodasara** [FortAwesome/Font-Awesome#12959]
Help me for resolving conflict between fontawesome 4 and 5 issues when i used both file in same project then some of icon is missing due to new naming convention in fontawesome 5. As I could not replace fontawesome 4 with fontawesome 5 bcoz I have to make change in entire application and it will be difficult.

I have to use both file how can I ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You should customize the FA5 CSS and change the conflicting class name `fa` to something like `fa5`

Hope it helps

Closing here

**Comment by ruchitaghodasara** [comment]
@tagliala Thanks for ur support I will try.

**Comment by tagliala** [comment]
@ruchitaghodasara you're welcome. I advise you to consider the Sass preprocessor and change the value of `$fa-css-prefix` in [_variables.scss](https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/scss/_variables.scss)

**Comment by nikocraft** [comment]
@tagliala I need to do the same, however, I can not change the fa to fa5, can I customize old fontawesome 4 version instead? Because in my web app fontawesome 5 may be dynamically added by the user or it may not. How can I customize fontawesome 4 so that if fontawesome 5 is added it does not mess with my application icons?

**Comment by tagliala** [comment]
@nikocraft you can find scss source files of Font Awesome 4 at https://github.com/FortAwesome/Font-Awesome/tree/fa-4/scss, you can customize those and change `$fa-css-prefix:       fa !default;` in `variables.scss` to `$fa-css-prefix:       fa4;`.

Does this help?

**Comment by nikocraft** [comment]
yeah seems that's a good solution! Thanks.

**Comment by nikocraft** [comment]
@tagliala I only use 10 fa4 icons in my project, is it possible with sass to optimize and remove the rest of the icons so that I get smaller filesize? Ofc if and when I need additional icons in the future, I can add them back. Please let me know :)
