### ISSUE TITLE
Dynamic styling of i tag in angular

### ISSUE THREAD

**Issue by akash-potdar7** [FortAwesome/Font-Awesome#12962]
Hey guys,

So here's my problem, 
I'm getting bunch of font-awesome icon class names from an api, and i loop these in the html and trying to apply this.
`<div class="side-item-wrapper">`
`        <i (click)="goTo(item.data1)" class="item.style"></i>`
` </div>`

Can somebody help me out?

**Comment by smartamus** [comment]
Yes this approach won't work, as Angular processes these after the page is rendered, and the JS has done all the swapping of the I style class into the vector's.
