### ISSUE TITLE
Update CSP docs with instructions for those using NPM packages

### ISSUE THREAD

**Issue by edmorley** [FortAwesome/Font-Awesome#12969]
Hi

On this page there are instructions for how to avoid issues with Font Awesome on a site that specifies a Content Security Policy:
https://fontawesome.com/how-to-use/performance-and-security#content-security-policy

However the current instructions are only aimed at users who download the assets manually, rather than those using the NPM packages with a bundler like webpack.

Would it be possible to document:
1) which package/file is equivalent to the existing file reference (`/static/vendors/fontawesome/css/fa-svg-with-js.css`) - I'm guessing something like `'@fortawesome/fontawesome/styles.css'` from the `@fortawesome/fontawesome` package?
2) how to specify `autoAddCss: false` in JS
3) that users must remember to extract CSS from the bundle
4) that the "Web Fonts with CSS" case does not require these workarounds (it's not explicitly stated currently)

At a guess the example in the docs would look something like:

```js
import '@fortawesome/fontawesome/styles.css';
import fontawesome from '@fortawesome/fontawesome';

// Make sure this is before any other `fontawesome` API calls
fontawesome.config = {
  autoAddCss: false
}
```

My intuition is that the set of people who use CSP is much more likely to overlap with those using a bundler than those still manually managing assets - so making the steps clearer for this group would be really helpful.

Many thanks :-)

**Comment by talbs** [comment]
Sorry for the radio silence, @edmorley. Thanks for the good suggestion - I've got that content updated in a PR for fontawesome.com now. Here's a screenie of the revised info:

![localhost_4000_how-to-use_on-the-web_other-topics_security](https://user-images.githubusercontent.com/163763/44427933-e8718f80-a560-11e8-90a6-2bdf596c9320.png)

As a designer, this isn't my the subject I majored in during school. That content seem okay to you?

**Comment by talbs** [comment]
Thanks much, @edmorley. I had @robmadole on our team take a look. He made some changes that seem like they address exactly what you brought up with our package org changes. Rob's updated docs are live at https://fontawesome.com/how-to-use/on-the-web/other-topics/security.

Closing this issue with that mind. But, If you have any more feedback or thoughts around how to make these or other docs better, we're all ears and would appreciate it. 😄
