### ISSUE TITLE
'API reference' link broken on /how-to-use/use-with-node-js

### ISSUE THREAD

**Issue by edmorley** [FortAwesome/Font-Awesome#12967]
Hi!

On this page:
https://fontawesome.com/how-to-use/use-with-node-js

...there is:
```html
<p>See the <a href="#api-reference">API reference</a> for more information on what API is available.</p>
```

There is no such anchor tag on that page - I'm presuming the link should point here instead?
https://fontawesome.com/how-to-use/font-awesome-api

Many thanks :-)

**Comment by talbs** [comment]
@tagliala, sorry for the delay in addressing this issue. When we revamped our docs, we separated our API (https://fontawesome.com/how-to-use/with-the-api/) from using Font Awesome via package managers (https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers). I can't seem to find the copy and broken link you mentioned in the current docs codebase.

Can you confirm if this issue still exists in the docs?

**Comment by tagliala** [comment]
This issue doesn't exist anymore 👍
