### ISSUE TITLE
Cannot read property 'prefix' of undefined

### ISSUE THREAD

**Issue by alesil-alexandre** [FortAwesome/Font-Awesome#12966]
Hello, first of all sorry for English, I'm using the google translator.
Well, I'm starting to use FontAwesome 5 Pro with Angular 5 and I'm having a hard time using the direct import of the icons (not the complete package).
When calling the command "ng serve -prod" it works perfectly, but when running only "ng-serve", that is, development environment, I'm getting the error "Can not read property 'prefix' of undefined."
I used "npm" to install the pro (token) packages as described at [link](https://fontawesome.com/how-to-use/use-with-node-js#pro)
I also changed the tsconfig.js file and added the option "allowSyntheticDefaultImports": true in the "compilerOptions" block as recommended by some website (I can not remember which) so that ng recognizes the separate imports of the icons.

if I put just the following code, even without using the icon, the page already gives the error:

```
import fontawesome from '@fortawesome/fontawesome';
import faSquare from '@fortawesome/fontawesome-pro-solid/faSquare';

fontawesome.library.add(faSquare);
```

but if I change the import to:
`import {faSquare} from '@fortawesome/fontawesome-pro-solid'`
the error does not occur and everything works beautifully ...

![image](https://user-images.githubusercontent.com/30605981/39382505-187642be-4a3c-11e8-974a-90a68bc934b3.png)

![image](https://user-images.githubusercontent.com/30605981/39382527-26c3376e-4a3c-11e8-8cc7-c18857f53813.png)

![image](https://user-images.githubusercontent.com/30605981/39382881-7e38affa-4a3d-11e8-8232-e93cfa1f0c01.png)

![image](https://user-images.githubusercontent.com/30605981/39382904-990ef1cc-4a3d-11e8-9698-caf32faa1eae.png)

**Comment by piuccio** [comment]
I'm having the same problem with react + jest + webpack

**Comment by piuccio** [comment]
@alesil-alexandre 

change

```js
import faSquare from '@fortawesome/fontawesome-pro-solid/faSquare';
```

to

```js
import { faSquare } from '@fortawesome/fontawesome-pro-solid/faSquare';
```

**Comment by kevinwhoffman** [comment]
In 5.1.0, the packages were renamed so it should look like this:

`import { faSquare } from '@fortawesome/pro-solid-svg-icons/faSquare';`

Do NOT forget the curly brackets or you will get the prefix error.

**Comment by alesil-alexandre** [comment]
Thanks.

**Comment by gsccheng** [comment]
The docs need to be updated to reflect this.

**Comment by haf** [comment]
The docs don't state how to do this for pro:

> import { faSquare } from '@fortawesome/pro-solid-svg-icons/faSquare';

here https://fontawesome.com/how-to-use/on-the-web/using-with/react
