### ISSUE TITLE
Icon request: Drawing

### ISSUE THREAD

**Issue by roberthartung** [FortAwesome/Font-Awesome#1296]
Hi,

I am currently developing a web-tool to create canvas animations with an Adobe Flash-Like interface.

You will be able to create "objects" that can be placed on a canvas. You are also able to draw lines, circles and many more. Therefore I want to request "drawing" icons.

Here are some Icons I would like to see in the next FontAwesome release:

![fontawesome_request_draw_icons copy](https://f.cloud.github.com/assets/2265899/652724/3acee128-d4bb-11e2-848c-332ebf293483.png)

Regards and Thanks
Robert

**Comment by ericdrobinson** [comment]
Resurrecting this again(?).  In addition to those outlined above, I would really like to see a "clone" or "stamp" icon.

**Comment by sensibleworld** [comment]
Just about all of these icons (perhaps with the exception of the line-width icon) now exist in Font Awesome.

https://fontawesome.com/search?o=r&c=design&s=solid&f=classic
