### ISSUE TITLE
What for so to complicate?

### ISSUE THREAD

**Issue by sharomet** [FortAwesome/Font-Awesome#12963]
Why did you make it so complicated?
```
.owl-prev::after,
.owl-next::after {
	font-family: 'Font Awesome 5 Free';
	font-weight: 900;// If this is not written, it will not work in ios O_o
}
.owl-prev::after {
	content: "\f104";
}
.owl-next::after {
	content: "\f105";
}
```
I do not see the advantages in Font Awesome 5.
When I work with Font Awesome 5, I spend a lot of extra time.
```
.branding::after {
	content: "\f369";
	font-family: 'Font Awesome 5 Brands'; //Why not make it all in one font?
	//I do not want to take the time to find out which font to use.
}
.square::after {
	content: "\f0c8";
	font-family: 'Font Awesome 5 Free';
	font-weight: 400;//Why not 900 or not normal?
}
```
The new font awesome 5 does not work on the local server.

Fount Awesome 4.7 is much better.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm sorry about your frustration but we had to make some choices.

FA5 comes with 3 different independent styles and brands are now separated, so you can use just one style and avoid brands.

Icons share the same unicode point and so we use the font weight to identify their style, so we can have a 200% less css classes and unicode points.

900 (Solid), 400 (Regular or Brands), 300 (Light)

Docs:
SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
CSS: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

If you want, you can create a single file by customizing Font Awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

If you are happy with FA4, feel free to use the old version

Hope it helps, closing here

**Comment by sharomet** [comment]
I understood. Thank you.
