### ISSUE TITLE
Icon Request: fa-import

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12985]
Please create import icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Import

![import](https://user-images.githubusercontent.com/24258716/39442515-15cb8aa0-4c77-11e8-8e40-cb0014a97ef2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think you may be interested in the [logistics package]() of FA5 Pro

This icon is available as https://fontawesome.com/icons/pallet-alt?style=solid

Closing here but feel free to upvote this request
