### ISSUE TITLE
Icon Request: fa-clerk

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12986]
Please create clerk icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Clerk
Person
Man
Woman

![clerk-with-tie](https://user-images.githubusercontent.com/24258716/39442551-398bc158-4c77-11e8-8214-d9ee4885e08a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

"Clerk" is available as fa-user: https://fontawesome.com/icons/user?style=solid

Sorry but at the moment uman-shaped figures does not follow Font Awesome Style

Closing here
