### ISSUE TITLE
Icon Request: fa-forklift

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12984]
Please create enhanced forklift icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Forklift

![forklift](https://user-images.githubusercontent.com/24258716/39442461-ddf8216a-4c76-11e8-8cb7-ba09932c1720.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #692, please add a 👍  reaction to that request.

This icon is already available in FA5 Pro, but you can upvote #692 for future purposes

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
