### ISSUE TITLE
Icon Request: fa-trolley

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12983]
Please create trolley icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

Trolley

![trolley](https://user-images.githubusercontent.com/24258716/39441703-62242bbc-4c74-11e8-986d-258d9d8de0dd.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as `fa-dolly` in FA5 Pro: https://fontawesome.com/icons/dolly?style=solid

Closing here but feel free to upvote this request
