### ISSUE TITLE
Icon Request: fa-2018calendar

### ISSUE THREAD

**Issue by amyelzea** [FortAwesome/Font-Awesome#12982]
Please create 2018 calendar icon. We have a few icons, that would like to have extended access to via Font-Awesome.
Thanks.

2018 Calendar

![calendar](https://user-images.githubusercontent.com/24258716/39442330-669fcfb4-4c76-11e8-8500-68f0ba036a28.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take advantage of the layering feature for this request:

https://fontawesome.com/how-to-use/svg-with-js#layering

SVG implementation: https://jsfiddle.net/tagliala/kmgntg1b/4/

CSS blogpost: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/
