### ISSUE TITLE
Icon Request: icon-file-appname

### ISSUE THREAD

**Issue by TomThak** [FortAwesome/Font-Awesome#1299]
Hi,
I have several ideas for new icons:

European Union:
class="icon-eu"
![euicon](https://f.cloud.github.com/assets/1766079/653048/bd725d5c-d4cb-11e2-9d13-6bfcf493367d.jpg)

Usage: portals with legislation

File format icons:
class="icon-file-word"
class="icon-file-excel"
class="icon-file-powerpoint"
class="icon-file-pdf"
class="icon-file-zip"
class="icon-file-exe"

Example:
![files](https://f.cloud.github.com/assets/1766079/653094/5b8db0c6-d4cd-11e2-9591-47a41815c8ee.jpg)

Usage: Everywhere in web apps.

Legislation icons:
class="icon-paragraph"
class="icon-scales"
class="icon-hands"

Example:
![legisl](https://f.cloud.github.com/assets/1766079/653119/bc6d6c10-d4cd-11e2-8bb2-2dbdcddc90f3.jpg)

**Comment by tagliala** [comment]
Hi, 

after ~ 5 years we have implemented:
- balance scale: https://fontawesome.com/icons/balance-scale?style=solid
- handshake: https://fontawesome.com/icons/handshake?style=solid
- word, excel, ppt, pdf:  https://fontawesome.com/icons?d=gallery&c=files&m=free

requests meeting contributing guidelines to 👍 :
- paragraph: #1706 

eu is out of scope: #5831

Closing here
