### ISSUE TITLE
Icon request: icon-sunglasses

### ISSUE THREAD

**Issue by cloudwizard** [FortAwesome/Font-Awesome#13]
say sunglasses
Group - multiple people
Since you have FB, linkedIn, how about Google

**Comment by elanperach** [comment]
+1

**Comment by RainHeart257** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by VeeK727** [comment]
This is really old, I'm surprosed it hasn't been added yet

+1

**Comment by MrZach** [comment]
+1

**Comment by irthos** [comment]
+1

**Comment by AndreLGava** [comment]
+1
http://www.clipartbest.com/cliparts/xcg/ojr/xcgojrLAi.svg

**Comment by G-Driver** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by Basilakis** [comment]
+1

**Comment by VinnieDzg** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode emojis: #222

- **[🕶 U+1F576](http://emojipedia.org/dark-sunglasses/)**
- [😎 U+1F60E](http://emojipedia.org/smiling-face-with-sunglasses/)

**Comment by sagearslan** [comment]
+1

**Comment by sensibleworld** [comment]
The future's so bright, we've gotta wear `fa-sunglasses`: https://fontawesome.com/icons/sunglasses?style=solid
