### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by phosinski** [FortAwesome/Font-Awesome#13006]
Hi
I am trying to find out what is the process for putting in a request for an icon, what the cost is and if there are any specifications I need to abide by?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Just follow our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
