### ISSUE TITLE
Icon request: icon-windmill (wind-turbine)

### ISSUE THREAD

**Issue by alfonsofega** [FortAwesome/Font-Awesome#1300]
#### Use cases:
- Projects related to renewable energies.

![windmill](https://f.cloud.github.com/assets/2205032/653589/d73fca62-d4da-11e2-84dc-b625c13cfcad.png)

It would be very useful a icon set related to renewable energies.

Thanks in advance. I congratulate you on the project. It is very useful.

**Comment by cnordin** [comment]
+1

**Comment by jfkw** [comment]
+1

**Comment by ajgoff** [comment]
+1

**Comment by djpeachey** [comment]
+1

**Comment by G-Driver** [comment]
A related request to the windmill is the solar panel, see https://github.com/FortAwesome/Font-Awesome/issues/3326

**Comment by southcaliking** [comment]
+1

**Comment by cserpell** [comment]
+1

**Comment by Rear-Window** [comment]
+1

**Comment by vamsiampolu** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by pacofr** [comment]
+1

**Comment by amrocs** [comment]
+1

**Comment by Hekkenberg** [comment]
+1

**Comment by mrdixit** [comment]
+1

**Comment by Szymaniuk** [comment]
+1

**Comment by AlvaroRojas** [comment]
+1

**Comment by getwiththebrand** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by frobak** [comment]
+1

**Comment by Jowls1** [comment]
+1

**Comment by topvis** [comment]
+1

**Comment by casper60** [comment]
+1

**Comment by mfgaspar** [comment]
+1

**Comment by eharit** [comment]
+1

**Comment by stuermerr** [comment]
+1

**Comment by Leapness** [comment]
+1

**Comment by HarpunDK** [comment]
Found some inspiration here:
https://g.foolcdn.com/editorial/images/480299/xxx-green-energy-stocks-2_large.jpg
https://g.foolcdn.com/editorial/images/480299/153-energy-future_large.jpg

**Comment by CarlQLange** [comment]
This would be really great, it's hard to use FA for maps without it!

**Comment by sensibleworld** [comment]
We've finally switched to renewable energy at Font Awesome. https://fontawesome.com/icons/wind-turbine?style=solid

**Comment by HarpunDK** [comment]
I like that very much.

**Comment by CarlQLange** [comment]
I love it! I have already used it on [some maps](https://toughsoles.ie/maps)!

<img width="728" alt="Screenshot 2019-06-14 at 14 03 57" src="https://user-images.githubusercontent.com/859820/59511075-4505b880-8ead-11e9-8aee-321feab307fb.png">
