### ISSUE TITLE
Fa-eye regular is only available for PRO

### ISSUE THREAD

**Issue by jevanlingen** [FortAwesome/Font-Awesome#13001]
Today I am doing the transition from FA 4.7 to 5.0. When upgrading, it surprised me that [fa-eye regular](https://fontawesome.com/icons/eye?style=regular) is only available as PRO variant, while the [fa-eye-slash regular](https://fontawesome.com/icons/eye-slash?style=regular) is available for Free.

Should this be considered as a bug? Clearly the [fa-eye regular](https://fontawesome.com/icons/eye?style=regular) is the same as 4.7's [fa-eye](https://fontawesome.com/v4.7.0/icon/eye/) icon. If so, please make this icon Free again!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is legit

@robmadole 

5.0
❌ https://fontawesome.com/icons/eye?style=regular <-- PRO
✅ https://fontawesome.com/icons/eye-slash?style=regular <-- FREE

4.7
✅ https://fontawesome.com/v4.7.0/icon/eye/ <-- FREE
✅ https://fontawesome.com/v4.7.0/icon/eye-slash/ <-- FREE

**Comment by robmadole** [comment]
Yep, I agree with this. We should make `eye` regular part of Free and then change the shim so that `eye` forwards to `far fa-eye`. I'll forward this on to @talbs and see what he thinks.

**Comment by talbs** [comment]
@robmadole thanks for the ping. Yep, the ayes have it in my book (sorry, bad pun but couldn't resist). I'll get those changes into our icon build-system shortly for a near future release. 😄

**Comment by robmadole** [comment]
Oh don't thank me...@tagliala had the clear vision to bring this to our attention (wondering if the puns will work for our Italian friend) Perhaps even cause an eye-roll? 🙄

**Comment by tagliala** [comment]
> Actually, the regular style of "eye" is available. For FREE.

as it was supposed to be since 5.0.0 but it has been fixed in 5.0.11 😄
