### ISSUE TITLE
Icon request: joystick

### ISSUE THREAD

**Issue by iamvitali** [FortAwesome/Font-Awesome#13011]
### What can it be used for?
For games related subjects.

### Example image (optional)
https://en.wikipedia.org/wiki/Joystick#/media/File:Joyopis.svg

**Comment by tagliala** [comment]
> For games related subjects.

we have a gamepad for this use case: https://fontawesome.com/icons/gamepad?style=solid

**Comment by TexasSwede** [comment]
I think a joystick icon is as useful as the gamepad. If I had to pick, I rather have the joystick icon than the gamepad.

**Comment by iamvitali** [comment]
@TexasSwede exactly the reason why I created this request! :)

Also, joystick kind of conveys different meaning too - "control, steering, attention". Whereas gamepad is literally just - "having fun, playing a game".

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🕹️](http://emojipedia.org/joystick/) U+1F579 Joystick

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/joystick?style=solid
