### ISSUE TITLE
Brands icons are not working with unicode 

### ISSUE THREAD

**Issue by Eldenroot** [FortAwesome/Font-Awesome#13016]
When you wanna use :before and put unicode into content it is not working - for example wikipedia icon (use font with css).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please double check that you follow the instructions and pay attention to font name

SVG: https://fontawesome.com/how-to-use/svg-with-js#pseudo-elements
CSS: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

If you think there is an issue with FA, please open a new issue and follow our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
