### ISSUE TITLE
Icon Request: fa-direct-debit

### ISSUE THREAD

**Issue by smartamus** [FortAwesome/Font-Awesome#13015]
Requesting a direct debit icon. This is a heavily used payment method as well as debit / credit cards which you already have icons for. Logo for direct debit can be found at:

https://www.directdebit.co.uk/Style%20Library/Images/dd_logo.png

Many Thanks :-)

**Comment by smartamus** [comment]
Sorry realised there is one already :-)

**Comment by markmaguirepcc** [comment]
+1 on this
