### ISSUE TITLE
Icon Request: fa-trustpilot

### ISSUE THREAD

**Issue by mshovelt** [FortAwesome/Font-Awesome#13019]
Would be good to get an icon for TrustPilot (https://uk.trustpilot.com/).  Sites often link to TrustPilot in order to gather reviews.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10564, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
