### ISSUE TITLE
Icon Request: fa-policeman

### ISSUE THREAD

**Issue by pinky89** [FortAwesome/Font-Awesome#13037]
Hi,
I need a policeman icon. I have searched for it but could not found any. So, could you please help on this.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3372, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by pinky89** [comment]
Hi,
[#3372](https://github.com/FortAwesome/Font-Awesome/issues/3372), here the icon is not provided. And, also in fontawesome site we dont have any police icon. It would be helpful if you can provide the icon.
