### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by usabilitest** [FortAwesome/Font-Awesome#13043]
FA refers to https://fontawesome.com/account/settings where one should be able to list the sites they are planning to use the fonts on, however it appears the "Settings" page does not exist any longer.

**Comment by talbs** [comment]
Hi, @usabilitest. Thanks for the heads up on this. Can share where on our site you encountered the broken link you noted? I think with our docs re-work we may have fixed this, but I want to be sure. Thanks much!

**Comment by talbs** [comment]
I think we've squashed this issue when we revisited our documentation a bit ago. I can't find any reference to a "Settings" link in fontawesome.com's codebase. I'm closing this with those two things in mind, but please re-open it or let me know if that bad link is still out there somewhere.
