### ISSUE TITLE
Brand icons not working 5.0.12

### ISSUE THREAD

**Issue by rawsh** [FortAwesome/Font-Awesome#13041]
With the version 4 cdn fa-google loads:

![](https://screenshotscdn.firefoxusercontent.com/images/e19d9e01-7e8d-478d-af74-32ac57a908ae.png)

With 5.0.12 cdn:

![](https://screenshotscdn.firefoxusercontent.com/images/547175aa-16b7-4040-b344-fa22cf71e92c.png)

```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css">
<h3><span class="fa fa-google"></span> Google</h3>
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that FA5 is not backward compatible with FA4.

Please make sure you are using `fab` prefix for brands

Ref: https://fontawesome.com/how-to-use/upgrading-from-4

Hope it helps

Closing here

**Comment by rawsh** [comment]
@tagliala thanks, did not see that
