### ISSUE TITLE
Icon request: fa-rpg-dice

### ISSUE THREAD

**Issue by yovantichrist** [FortAwesome/Font-Awesome#13047]
I know there is an open dice icon request but what I'm asking for is a role game dice, with more than 6 sides (usually twelve or more).

I have a video game site where game genres are represented with FA icons and I would like to have a more accurate icon for the RPG genre.

Thanks!

https://www.google.com/search?q=rpg+dice

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color, 16px icon size suitable example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by yovantichrist** [comment]
Maybe something like this:

https://www.pinterest.es/pin/286330488786358017/
https://www.shutterstock.com/ja/image-vector/20-sided-20d-dice-numbers-flat-355147946

**Comment by sensibleworld** [comment]
We've added a basic d20 icon: https://fontawesome.com/icons/dice-d20?style=solid along with other common RPG dice: https://fontawesome.com/icons?c=gaming-tabletop
