### ISSUE TITLE
Icon:request Backspace

### ISSUE THREAD

**Issue by johBerlin** [FortAwesome/Font-Awesome#13045]
A backspace icon I am missing very often when using the font in layouts. 
Would be lovely to have :-)
Example: https://www.onlinewebfonts.com/icon/95429

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1980 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
