### ISSUE TITLE
Security Hole in Font Awesome Pro CDN

### ISSUE THREAD

**Issue by ArduousPH** [FortAwesome/Font-Awesome#13048]
I found a leak wherein I can access the raw file of the said js script. I just need to find a website that uses it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Please take a look here for responsible disclosure: https://fontawesome.com/how-to-use/performance-and-security

I'm going to edit your message

**Comment by robmadole** [comment]
Thanks @ArduousPH for taking the time to submit the issue. As this is a known condition I don't have any problem re-posting the original message here:

> I found a leak wherein I can access the raw file of the said js script. I just need to find a website that uses it.

This is a known concern. The Pro CDN is intentionally implemented to prevent accidental or inadvertent piracy. As with a lot of things on the ole Internet, if you are intent on stealing something it's hard to prevent it. Same thing here. We are not going to overly burden legitimate customers who wish to fairly use the Pro CDN with DRM. It just makes things suck for our real customers and forces people who wish to pirate Pro to spend a few more minutes figuring out how to steal it.
