### ISSUE TITLE
Icon request: icon-brand-vero 

### ISSUE THREAD

**Issue by sjamesmccarthy** [FortAwesome/Font-Awesome#13042]
Many people are leaving Facebook these days and the app "Vero" I think has some good potential. I have already started the migration but am just missing a brand icon for the platform. What do you all think? You can download it from the app store: Vero.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12758, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
