### ISSUE TITLE
Icon Request: animal-crossing-leaf (nintendo game)

### ISSUE THREAD

**Issue by QxZK** [FortAwesome/Font-Awesome#13052]
I, this is my request, animal crossing icons : https://www.google.fr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjPmNqb4fDaAhXC6RQKHWtVB0UQjRx6BAgBEAU&url=https%3A%2F%2Fwww.redbubble.com%2Fpeople%2Fmrpickle255%2Fworks%2F22044932-animal-crossing-leaf-logo%3Fp%3Dcanvas-print&psig=AOvVaw2-7kGDRpPZdeSf_PTVc7Hg&ust=1525684868958545

**Comment by QxZK** [comment]
oh yeah, sry

### What can it be used for?

for my website, like other icon : qxzk.pw

### Example image (optional)

https://www.google.fr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjPmNqb4fDaAhXC6RQKHWtVB0UQjRx6BAgBEAU&url=https%3A%2F%2Fwww.redbubble.com%2Fpeople%2Fmrpickle255%2Fworks%2F22044932-animal-crossing-leaf-logo%3Fp%3Dcanvas-print&psig=AOvVaw2-7kGDRpPZdeSf_PTVc7Hg&ust=1525684868958545

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Thanks.

If this is a brand, could you please provide more information about this brand?

Is there any official website?

**Comment by QxZK** [comment]
as you can see the sheet is present on the game box and it is the image that represents the game and this series. It's a bit like Mario, he doesn't have an official logo but a mushroom or his cap can represent him.

**Comment by QxZK** [comment]
https://images-na.ssl-images-amazon.com/images/I/91t1-tLXJ3L._SX342_.jpg and https://ih1.redbubble.net/image.222717190.4932/flat,800x800,075,f.u2.jpg

**Comment by tagliala** [comment]
Sorry, closing here as wontfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#582-to-590
