### ISSUE TITLE
fontawesome-all.min.css has backslas in the font name

### ISSUE THREAD

**Issue by Vasimovic** [FortAwesome/Font-Awesome#13050]
Hello,

Version fontawesome-pro-5.0.10, the minified file of (fontawesome-all.css) has a backslash "\\" in the font-family name

Example: font-family:**Font Awesome\\ 5 Pro;**

![image](https://user-images.githubusercontent.com/2503098/39666364-76f88ee8-5057-11e8-98d4-00c2ec40af94.png)

In Firefox this is interpreted without the backslash, producing some Dom Draw issues for me when exporting to PDF

FYI: When I remove the backslash it fixes the issue

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

Sorry for the late reply.

@robmadole is this a minification issue? It also happens in the free version. Is there a way to configure the css minimizer to avoid this optimization?

**Comment by robmadole** [comment]
We can take a look but I don't think that name is invalid. Isn't this a bug with Firefox?

**Comment by tagliala** [comment]
It is probably a browser issue, which also affects Chrome in some particular conditions (or OS?) #13231

@Remzi1993 which os?

**Comment by robmadole** [comment]
We might consider trying to fix this. However I stand behind the statement that it's not technically wrong. Here's a good article that talks about this: https://mathiasbynens.be/notes/unquoted-font-family.

We use `cssnano` to do this minification. Might be able to [alter how that works](http://cssnano.co/optimisations/minifyfontvalues/).

**Comment by tagliala** [comment]
> However I stand behind the statement that it's not technically wrong. 

Yes. I also did my investigation and it is not wrong. Anyway, if this change will fix unpredictable behaviour with some browser/os, I'm not against it.

**Comment by robmadole** [comment]
@tagliala agreed, sir

**Comment by robmadole** [comment]
We have a fix for this in our build system. Should get released in the next version or pre-release.

**Comment by Vasimovic** [comment]
Thank you so much, you guys are great!

**Comment by Remzi1993** [comment]
@tagliala This happens on Windows 10 64-bit

**Comment by Remzi1993** [comment]
@robmadole I know it's not needed but what @tagliala already said having single or double quotes will fix unpredictable behaviour. In Firefox sometimes it happens that it doesn't recognize the font family name.

Better safe than sorry :)

**Comment by Remzi1993** [comment]
Hi @tagliala and @robmadole is this issue fixed in the new version?
Just curious :)

**Comment by tagliala** [comment]
@Remzi1993 I would say yes, it is.

The downloaded package doesn't include the minified files (it's a bug) but I can see the fix in the source code at https://github.com/FortAwesome/Font-Awesome/blob/master/web-fonts-with-css/css/fa-brands.min.css (for example)
