### ISSUE TITLE
Icon request: fab fa-bootstrap

### ISSUE THREAD

**Issue by ratajs** [FortAwesome/Font-Awesome#13059]
Please, can you add a Bootstrap icon to brands icons.
Here is original icon:

![](http://getbootstrap.com/docs/4.1/assets/img/favicons/apple-touch-icon.png)

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1828, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
