### ISSUE TITLE
Error importing icons with library and TypeScript

### ISSUE THREAD

**Issue by netcitylife** [FortAwesome/Font-Awesome#13054]
Hi.

Environment: TypeScript, Aurelia project 

I am trying to import only several icons as described here: https://fontawesome.com/how-to-use/use-with-node-js, like this:

```typescript
import fontawesome from '@fortawesome/fontawesome'
import faUser from '@fortawesome/fontawesome-pro-solid/faUser'
import faCircle from '@fortawesome/fontawesome-pro-regular/faCircle'
import faArchive from '@fortawesome/fontawesome-pro-light/faArchive'
import faFacebook from '@fortawesome/fontawesome-free-brands/faFacebook'

fontawesome.library.add(faUser)
fontawesome.library.add(faCircle)
fontawesome.library.add(faArchive)
fontawesome.library.add(faFacebook)
```
but getting the following error:
`ERROR in /Users/dmitry/Projects/CommunityDialog/frontend/src/resources/elements/icon.ts
./src/resources/elements/icon.ts
[tsl] ERROR in /Users/dmitry/Projects/CommunityDialog/frontend/src/resources/elements/icon.ts(5,8)
      TS1192: Module '"/Users/dmitry/Projects/CommunityDialog/frontend/node_modules/@fortawesome/fontawesome-pro-solid/faUser"' has no default export.`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which version of FA are you using?

Please also take a look at #12429

**Comment by soulhunter1987** [comment]
Hi, currently 5.0.12.

New 5.1 version might solve my issue, when do you plan to release it?

**Comment by jmzagorski** [comment]
I know this is an old issue, but maybe it can be closed? @netcitylife I noticed you may be using https://github.com/jmzagorski/aurelia-fontawesome since you posted a few issues on that repo. Are you seeing any problems with the plugin? I have an app working with typescript and that plugin.

**Comment by tagliala** [comment]
> New 5.1 version might solve my issue, when do you plan to release it?

A while ago 😅 

This should have been fixed, closing here.

**Comment by jmzagorski** [comment]
@tagliala I noticed your organization has other repos for fontawesome plugins such a angular, vue, react, ember. Was your organizations plan to maintain external plugins for fontawesome or were those plugins created because your members programmed in reat, vue, angular etc? Just curious if the aurelia-fontawesome plugin would be better maintained within the fortawesome organization repo or not.

**Comment by tagliala** [comment]
@jmzagorski feel free to [request a new feature](https://github.com/FortAwesome/Font-Awesome/issues/new??title=Feature%20request:feature-name&template=feature-request.md) for official aurelia support.

AFAIK, we are building official components for the most used frameworks
