### ISSUE TITLE
no icons for HKD and SGD Currency

### ISSUE THREAD

**Issue by vijaychandramadrone** [FortAwesome/Font-Awesome#13057]
No icons were found for Hongkong currency (HKD) and Singapore currency (SGD).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I need this request splitted into two separate requests

Related to: #4986, #3028, #10896

Please note that you can use plain text for non-symbolic currencies

**Comment by tagliala** [comment]
Please open individual requests for non-symbolic currencies filling out [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
