### ISSUE TITLE
Icon f2c4 (Quora) is not appearing properly

### ISSUE THREAD

**Issue by jfrichne** [FortAwesome/Font-Awesome#13063]
Hi there!

I am unable to swap out an svg-icon's unicode to match the Quora logo using CSS. It works for other svg icons on the site but not the Quora logo ('\f2c4'). Is this due to a copyright issue of some kind? I am using this CSS:
```
.ico-step-icon-note:before {
   content: '\f2c4';
}
```
However, the end result is this:
![iconf2c4](https://user-images.githubusercontent.com/39071159/39730850-d63a43ca-5218-11e8-93ef-8f78e5de3025.png)

Is there something I'm missing here?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure tu have set the font-family to `Font Awesome 5 Brands`

Ref: https://fontawesome.com/how-to-use/web-fonts-with-css#pseudo-elements

Demo: https://jsfiddle.net/tagliala/jhusu54b/2/

Closing here

**Comment by jfrichne** [comment]
Hi! Thanks for your reply, I tried your advice of specifying the font-family, and still have no luck. I tried changing the pixel size to see if that was the issue and nothing seems to be working.

Any other suggestions?
[http://jmp.sh/mR5Afpg]

**Comment by tagliala** [comment]
Sorry, my mistake.

You are using FA 4. I don't know exactly which version, but please make sure you are using FA >= 4.7.0 because Quora has been introduced in FA 4.7

My instructions are for Font Awesome 5, please ignore them.
