### ISSUE TITLE
Icon Request: icon-brain

### ISSUE THREAD

**Issue by Zenurai** [FortAwesome/Font-Awesome#1306]
I see this is already referred to in issue #131 but not as a specific icon request in its own right.  Either a top down two hemispheres view or side on would do.  Even a brain inside a head in profile... anything really that could be used for a psychology category/section.

Using the stacked icon approach might also be an idea... having a profile of a head and then floating the cogs icon on top for example.

![head-parts-icons-set-prev](https://f.cloud.github.com/assets/2871146/655608/7c6ff2d2-d517-11e2-8efc-0dbec0416785.jpg)

Source of these examples is: http://graphicriver.net/item/head-brain-vector-icons-set/3636896

**Comment by Kurosaki87** [comment]
perfect this

**Comment by Kurosaki87** [comment]
+1

**Comment by tagliala** [comment]
ffff

Closing here in favour of #2075 which has more +1s

No need to +1 that request, I will do it by myself
