### ISSUE TITLE
Icon Request - Aircon

### ISSUE THREAD

**Issue by steveparkins0n** [FortAwesome/Font-Awesome#13062]
Icon request - Aircon

**Comment by tagliala** [comment]
Could
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request? Is Aircon a brand?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by TexasSwede** [comment]
I think he means air conditioning (a.k.a. A/C).

**Comment by aethior** [comment]
> Then it is a duplicate of #3211, but there I need an example of "AC"

@tagliala duplicated and solved. :)
