### ISSUE TITLE
Icon Request: icon-sort-alpha-up-alt for reversed

### ISSUE THREAD

**Issue by mkleehammer** [FortAwesome/Font-Awesome#13064]
I love the [sort alpha](https://fontawesome.com/icons/sort-alpha-up?style=solid) icons, but I think it might be better in some situations to have a pair of icons where the A and Z reversed instead of the the arrow reversing.  For example, here is the sorting menu in Excel - notice the first icon is roughly the same as FA, but in the second the letters are swapped and the arrow points down.

![screen shot 2018-05-07 at 11 07 10 pm](https://user-images.githubusercontent.com/27421/39737563-6e853d9c-524b-11e8-9d19-b0ff939764f1.png)

I'm using the sort icons to show sorting in tables when the user clicks a header.  On first click, the A->Z icon is displayed and the contents sort from A to Z.  This looks great and the icon and the content match well.

When you click again to reverse, the *arrow* in the icon reverses and points up, but the A is still on top and the Z is still on the bottom.  The contents of the table, however, are the opposite: "Z" items are on top and "A" items are on the bottom.  The visual mismatch is actually pretty noticeable.

What I'm suggesting, even if only in Pro, is an alternate just for the reversed version of the icon ("up").  This would be paired with the existing "down" icons.

Thanks for the great work.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue. Please refer to #9464

Closing here
