### ISSUE TITLE
Icon Request: fa-glitch

### ISSUE THREAD

**Issue by IbrahimTareq** [FortAwesome/Font-Awesome#13065]
https://glitch.com/

[glitch_logo.zip](https://github.com/FortAwesome/Font-Awesome/files/1982325/glitch_logo.zip)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11883, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
