### ISSUE TITLE
Donate and piggy-bank icons don't work

### ISSUE THREAD

**Issue by phazzled** [FortAwesome/Font-Awesome#13066]
Hello,

When I type 'donate' or 'piggy-bank' in Photoshop (with the Font Awesome Pro font selected), the correct item is not being displayed.

When I type 'donate', it shows up as 'don@e'. The 'piggy-bank' shows up as piggy-[banicon]k'. (The [banicon] being Font Awesome's ban icon). It seems that words Font Awesome recognises as icons are converted to icons before it recognises the full word as a single icon. I added a screenshot to illustrate the problem: 

![fa_donate_piggybank](https://user-images.githubusercontent.com/20245162/39742994-d0de9e6c-529f-11e8-9b3c-9a725a1ff12e.png) 

Thanks for your help!

Edit 1: I just checked the glyphs list and both icons don't seem to show up there either (unless I missed it).
Edit 2: I tested a few more. The following icons don't seem to work either:

- 'hand-holding-heart' turns into 'hand-holding-[hearticon]'
- 'user-astronaut' turns into '[usericon]-astronaut'
- 'user-slash' turns into '[usericon]-slash'
- 'user-shield' turns into '[usericon]-[shieldicon]'
- 'user-edit' turns into '[usericon]-[editicon]'
- 'truck-loading' turns into '[truckicon]-loading'
- 'truck-moving' turns into '[truckicon]-moving'
- 'wine-glass' doesn't change at all (it just says 'wine-glass')

These are the ones I tested; it seems to only happen when there's a hyphen in the icon name. Other icons, such as 'step-forward', 'table-tennis', 'battery-full' and 'arrow-alt-circle-left' (just a few I tested) do work, so it doesn't happen with all icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check that you are using the latest Font Awesome version? (5.0.12)

If you are not sure, uninstall your fonts and reinstall them back

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
