### ISSUE TITLE
Icon request: fab-ko-fi

### ISSUE THREAD

**Issue by pixelnourish** [FortAwesome/Font-Awesome#13061]
Creating one's own Ko-fi supporter button anywhere.
ko-fi.com

![image](https://user-images.githubusercontent.com/182633/39720405-1382c6b2-51f1-11e8-8f7c-3f604f436708.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12607, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by pixelnourish** [comment]
My apologies - I must've misspelt when searching. Thank you!
