### ISSUE TITLE
Font Awesome TTF >=5.0.11 is broken in some linux apps

### ISSUE THREAD

**Issue by jplatte** [FortAwesome/Font-Awesome#13067]
Possibly related to #13044 (since that is also happening since 5.0.11)

Before (5.0.10):

![bildschirmfoto vom 2018-05-08 10-02-52](https://user-images.githubusercontent.com/951129/39745242-0026f5a0-52a7-11e8-9fa0-d4e7f7548fc3.png)

After (5.0.11 - 5.3.1):

![bildschirmfoto vom 2018-05-08 10-01-04](https://user-images.githubusercontent.com/951129/39745265-0bb30008-52a7-11e8-86d8-82bbf408860d.png)

**Comment by mlwilkerson** [comment]
@jplatte is there any more information you can provide to help diagnose this? I did the work on those font file updates for `5.0.11` and it's not yet evident to me how those changes might give rise to those visual side effects in that status bar.

**Comment by mlwilkerson** [comment]
What _is_ evident is that those matrix looking things represent the unicode character `0020`, which is `space`. So they were displaying as horizontal whitespace before (as expected), and now they are not.

**Comment by mlwilkerson** [comment]
Normally, the Font Awesome typeface should not be applied to a space character. (And I wonder what font i3bar is trying to apply to those space characters.) However, when I do apply Font Awesome 5 Free (v5.0.13, OTF) to space characters in TextEdit on MacOS, such as in "quick brown fox", the spaces appear correctly as simply whitespace.

@jplatte Are you confident that the versions of i3bar and its dependencies are the all the same before and after changing the Font Awesome version, such that the _only_ difference between the working earlier version and the broken later version is the change version of the Font Awesome OTF files?

**Comment by jplatte** [comment]
Yes, I am confident that it is the Font Awesome version that caused this. I am running an up-to-date system with only the otf-font-awesome package pinned to 5.0.10 and it is working like it should.

**Comment by jplatte** [comment]
@mlwilkerson Is this just too much of a niche issue for it to be looked into? Can I provide any more information that would help track down the underlying problem?

**Comment by nfraprado** [comment]
I can confirm this same issue... The awkward part is that it affects just some of the icons from Font Awesome, as shown on the picture. My current workaround, since I can't find a solution, is to keep the otf-font-awesome package at version 5.0.9-1 (from the ArchLinux repository).

**Comment by jplatte** [comment]
As another bit of information about this: It's not only about the OTF, but also the TTF (which just isn't used by pango when an OTF is present). Removing the otf package and using the ttf package >= 5.0.11 results in the same issue.

@nfraprado 5.0.10 should also work. You can get the packages from the arch linux archive if you want to use that version too:

* https://archive.archlinux.org/packages/o/otf-font-awesome/otf-font-awesome-5.0.10-1-any.pkg.tar.xz
* https://archive.archlinux.org/packages/t/ttf-font-awesome/ttf-font-awesome-5.0.10-1-any.pkg.tar.xz

**Comment by jplatte** [comment]
Update: It's not both variations! It's only the TTF which causes this. This can be worked around by only installing otf-font-awesome (or uninstalling ttf-font-awesome).

**Comment by v44r** [comment]
Not only {i3,sway,way}bar are affected. All programs are. This is gedit:

ttf-font-awesome-5.8.1-1:

![image](https://user-images.githubusercontent.com/46873924/55680879-e9a0d280-591f-11e9-97b1-0b03600fb66b.png)

otf-font-awesome-5.8.1-1:

![image](https://user-images.githubusercontent.com/46873924/55680899-3d132080-5920-11e9-8b59-4d47700621f0.png)

I can see the same in geany.

**Comment by Arnaudv6** [comment]
> Update: It's not both variations! It's only the TTF which causes this. This can be worked around by only installing otf-font-awesome (or uninstalling ttf-font-awesome).

Should we find/create a GTK bug then? Pango?

**Comment by jplatte** [comment]
It could be a bug in pango, definitely not gtk (of the programs that I've seen this issue in, only waybar uses gtk).

**Comment by Arnaudv6** [comment]
https://gitlab.gnome.org/GNOME/pango/issues/265

**Comment by jplatte** [comment]
Fixed in pango 1.44: https://gitlab.gnome.org/GNOME/pango/merge_requests/67

**Comment by tagliala** [comment]
@jplatte thanks for letting us know!
