### ISSUE TITLE
Layered icons for multiple sites

### ISSUE THREAD

**Issue by usabilitest** [FortAwesome/Font-Awesome#13060]
I'm using layered icons utilizing all.js 
https://pro.fontawesome.com/releases/v5.0.12/js/all.js

How can I use FA in a white-label projects where customers can use their own domain? Do I have to add a domain every time new one is added?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
