### ISSUE TITLE
Issue: Goodreads icons do not show up when called within Hugo-academic theme of Hugo/Blogdown

### ISSUE THREAD

**Issue by jananiravi** [FortAwesome/Font-Awesome#13078]
I'm creating a webpage using Hugo Blogdown (using Hugo-academic theme).
For instance, the GitHub and other social network icons work when called in the config.toml page but not goodreads:
```
[[params.social]]
    icon = "goodreads"
    icon_pack = "fa"
    link = "//goodreads.com/jananiravi"
```
An almost identical bit that works:
```
[[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/jananiravi"
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this issue does not apply here.

Please ask https://github.com/gohugoio/hugo to [update font awesome](https://github.com/gohugoio/hugo/blob/master/examples/blog/static/css/font-awesome.css) from 4.5 to 5.0.12 or do the upgrade by yourself by forking that project

Hope it helps

Closing here
