### ISSUE TITLE
Icon Request: fa-sinusbot

### ISSUE THREAD

**Issue by Lulalaby** [FortAwesome/Font-Awesome#13071]
### What can it be used for?
It could be added to links for the sinusbot interface
https://sinusbot.com
SinusBot is MusicBot for TeamSpeak 3 and Discord from the Developer Michael Friese.

### Example images
SinusBot: [https://forum.sinusbot.com/sinusbot-logo.png](https://forum.sinusbot.com/sinusbot-logo.png) the "N" of the Logo.
![grafik](https://user-images.githubusercontent.com/14029133/39773681-17e63a28-52f9-11e8-9531-28faff15cf74.png)
![grafik](https://user-images.githubusercontent.com/14029133/39773716-1e349384-52f9-11e8-9dac-3ca19c7e82f6.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by LalaSatalinDeviluke** [comment]
Hope this is ok now

**Comment by LalaSatalinDeviluke** [comment]
i tried it myself, maybe it helps.
it would be nice if it would be added or anotherone makes a better version.

heres a grey version of sinusbot icon
with fixed size (24x23 px)
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200" style="enable-background:new 0 0 200 200;" xml:space="preserve"><style type="text/css">.grey{fill:#999999;}</style><g transform="translate(0.000000,200.000000) scale(0.100000,-0.100000)"><path class="grey" d="M880,1978c-41-6-77-12-79-14s4-13,13-23c28-31,88-181,156-386c122-371,177-470,246-444c51,18,92,106,202,429 c49,146,92,272,96,280c4,11-13,25-67,52c-127,64-184,83-319,103C1020,1992,990,1992,880,1978z"/><path class="grey" d="M574,1882c-211-103-398-315-473-539c-43-127-63-250-58-352c5-95,30-228,46-244c5-5,34,27,66,70 c126,173,262,431,324,618c83,248,134,390,158,438c13,26,22,47,20,47S618,1903,574,1882z"/><path class="grey" d="M1840,1264c-162-202-301-463-395-746c-85-256-112-334-136-380c-12-23-15-38-8-38c22,0,177,78,240,121 c80,54,195,169,250,250c155,229,206,542,131,808l-18,64L1840,1264z"/><path class="grey" d="M722,890c-50-21-108-150-217-480l-57-174l28-23c46-36,183-100,261-122c107-29,248-45,326-37c63,7,67,9,54,24 c-26,30-73,151-152,387c-88,264-142,384-184,414c-16,12-31,21-33,20C747,899,735,895,722,890z"/></g></svg>`


here is an colored version
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200" style="enable-background:new 0 0 200 200;" xml:space="preserve"><style type="text/css">.red{fill:#E13438;}</style><g transform="translate(0.000000,200.000000) scale(0.100000,-0.100000)"><path class="red" d="M880,1978c-41-6-77-12-79-14s4-13,13-23c28-31,88-181,156-386c122-371,177-470,246-444c51,18,92,106,202,429 c49,146,92,272,96,280c4,11-13,25-67,52c-127,64-184,83-319,103C1020,1992,990,1992,880,1978z"/><path class="red" d="M574,1882c-211-103-398-315-473-539c-43-127-63-250-58-352c5-95,30-228,46-244c5-5,34,27,66,70 c126,173,262,431,324,618c83,248,134,390,158,438c13,26,22,47,20,47S618,1903,574,1882z"/><path class="red" d="M1840,1264c-162-202-301-463-395-746c-85-256-112-334-136-380c-12-23-15-38-8-38c22,0,177,78,240,121 c80,54,195,169,250,250c155,229,206,542,131,808l-18,64L1840,1264z"/><path class="red" d="M722,890c-50-21-108-150-217-480l-57-174l28-23c46-36,183-100,261-122c107-29,248-45,326-37c63,7,67,9,54,24 c-26,30-73,151-152,387c-88,264-142,384-184,414c-16,12-31,21-33,20C747,899,735,895,722,890z"/></g></svg>`

**Comment by Lulalaby** [comment]
Push

**Comment by Lulalaby** [comment]
Push

**Comment by Lulalaby** [comment]
Hey could that be merged?

**Comment by Lulalaby** [comment]
@tagliala ?

**Comment by tagliala** [comment]
Hi @Lulalaby, please take a look at our [Brands Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), they contain a lot of information about how requests work

**Comment by Lulalaby** [comment]
ah okay?

**Comment by Lulalaby** [comment]
Due to the lack of work here, I'm closing this after 3 years now.
