### ISSUE TITLE
Solid icons stopped working in pro version in Firefox

### ISSUE THREAD

**Issue by lauraburgin** [FortAwesome/Font-Awesome#13072]
We are using Font Awesome Pro 5.0.8
This week, the solid icons on our websites have stopped working in **Firefox**. They were working last week. For example the solid cog wheel:` <i class="fas fa-cog"></i>` now displays a square. It works fine in Chrome.

FontAwesome Pro Version: 5.0.8
Firefox 59.0.2 /
Web Fonts with CSS

As a test, I downloaded and installed the newest version: Font Awesome Pro 5.0.12, and this seems to fix the issue. 

Screenshot in Firefox:
![screen shot 2018-05-08 at 11 26 38 am](https://user-images.githubusercontent.com/25495960/39775436-b67fca24-52b2-11e8-843e-d7fde3320d10.png)

This is what it should be:
![screen shot 2018-05-08 at 11 28 11 am](https://user-images.githubusercontent.com/25495960/39775504-ef4f85d8-52b2-11e8-8831-dd7d39ee064c.png)

Code pen:
https://codepen.io/lauraburgin/pen/mLpGeG

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

PS: cannot replicate on Firefox 59.0.3 on Windows 10
PS2: please take a look at our development console, there is a CORS issue: "(cross-origin): https://d2zfowlldib7se.cloudfront.net/assets/obits/fonts/fontawesome-pro-5.0.8/web-fonts-with-css/webfonts/fa-solid-900.woff2. Reason: missing header CORS “Access-Control-Allow-Origin” 

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Troubleshooting: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up
