### ISSUE TITLE
Duplicate usage of font-family name "Font Awesome 5 Free"

### ISSUE THREAD

**Issue by john357smith** [FortAwesome/Font-Awesome#13073]
Hello,

in /web-fonts-with-css/css/fontawesome-all.css you are using same family name "Font Awesome 5 Free" for solid and regular font in font-face definition. This can cause a problem in some special cases.

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information?

**Comment by john357smith** [comment]
As I wrote above look into fontawesome-all.css  I think it's pretty obvious:

`@font-face {
  **font-family: 'Font Awesome 5 Free';**
  font-style: normal;
  font-weight: 400;
  src: url("../webfonts/fa-regular-400.eot");
  src: url("../webfonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-regular-400.woff2") format("woff2"), url("../webfonts/fa-regular-400.woff") format("woff"), url("../webfonts/fa-regular-400.ttf") format("truetype"), url("../webfonts/fa-regular-400.svg#fontawesome") format("svg"); }

.far {
  font-family: 'Font Awesome 5 Free';
  font-weight: 400; }
@font-face {
  **font-family: 'Font Awesome 5 Free';**
  font-style: normal;
  font-weight: 900;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }

.fa,
.fas {
  **font-family: 'Font Awesome 5 Free';**
  font-weight: 900; } `

**Comment by john357smith** [comment]
Try this one in Chrome with .css version 4.7 and current 5 version:

4.7:
```
<SELECT style="font-family: 'FontAwesome';">
  <OPTION>up &#xf0d8;</OPTION>
  <OPTION>down &#xf0d7;</OPTION>
  <OPTION>up2 &#xf0d8;</OPTION>
</SELECT>
```

5.0.12:
```
<SELECT style="font-family: 'Font Awesome 5 Free';">
  <OPTION>up &#xf0d8;</OPTION>
  <OPTION>down &#xf0d7;</OPTION>
  <OPTION>up2 &#xf0d8;</OPTION>
</SELECT>
```

**Comment by wolfy1339** [comment]
That's because of the multiple font weights for the same character

**Comment by tagliala** [comment]
Hi,

please consider a javascript solution for your select elements, because your solution does not work on Chrome for Android and OSX (ref: #996). Also, this use case has never been supported by Font Awesome.

If it worked on your use case, please stay with FA4, because we had to make choices on FA5 and we need the same font name with different font weights

You can also consider a custom build of Font Awesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Ref: #996
