### ISSUE TITLE
Icon Request: fa-electric-car

### ISSUE THREAD

**Issue by stormvisions** [FortAwesome/Font-Awesome#13074]
Lots of 'green' issues and technologies might make for popular icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single colour, 16px icon size suitable example?

**Comment by stormvisions** [comment]
Have seen several people's efforts that might suggest good ways to try. Not sure about copyright so would have to be careful to make sure original (sorry my first time suggesting so not sure of the norm).

![image](https://user-images.githubusercontent.com/14931276/39832164-55b01c48-537b-11e8-88c7-796f20469282.png)
http://www.typophile.com/node/73434

![image](https://user-images.githubusercontent.com/14931276/39832239-8637974c-537b-11e8-80d7-ef077a8fa322.png)
getty images

![image](https://user-images.githubusercontent.com/14931276/39832294-ada461ac-537b-11e8-9c96-29e34c0578f2.png)

![image](https://user-images.githubusercontent.com/14931276/39832388-dfa0ee78-537b-11e8-85df-913d80938b3f.png)

![image](https://user-images.githubusercontent.com/14931276/39832431-009a2edc-537c-11e8-9759-79e829819403.png)

![image](https://user-images.githubusercontent.com/14931276/39832461-19b344da-537c-11e8-8ffe-0c7622796360.png)

Thanks.

**Comment by TexasSwede** [comment]
A simple passenger car with a lightning bolt would work well.

**Comment by madivad** [comment]
I very much like the first one that seems like and "E" and a plug combined. I know it doesn't represent a car, but very clever

**Comment by aethior** [comment]
Currently there are these icons:
- https://fontawesome.com/icons/car-bolt
- https://fontawesome.com/icons/car-circle-bolt

**Comment by tagliala** [comment]
Considering this fulfilled by `car-bolt`

If it is not the case, feel free to open a new request with a single color example suitable for 16px icon size

**Comment by stormvisions** [comment]
Does the job. Thanks.
