### ISSUE TITLE
NPM JS Package out of date

### ISSUE THREAD

**Issue by kamransaleem** [FortAwesome/Font-Awesome#13080]
see here: https://www.npmjs.com/package/font-awesome

still at 4.7.0

Can this be updated?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The above is not the official Font Awesome repository

Please use: https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts

Hope it helps

Closing here

Docs: https://fontawesome.com/how-to-use/use-with-node-js
