### ISSUE TITLE
Icon request: icon-graduate (mortar-board graduation-cap), icon-university

### ISSUE THREAD

**Issue by analytically** [FortAwesome/Font-Awesome#131]
It would be great if there would be an icon representing a school / college / university.

Some examples for inspiration:

http://www.lostinseattle.com/LIS/-images/-icons/icon-1-116.gif
http://content.apartmenthl.com/system/citypages/categories/colleges-universities/icon_desc.png

Bonus:
the academy icon:
http://www.worcestershire.gov.uk/cms/images/academy-icon.png

**Comment by user501254** [comment]
+1

**Comment by tagliala** [comment]
Locking here :lock: 
http://fontawesome.io/icon/graduation-cap/
