### ISSUE TITLE
Icon request: crossed swords, crossed swords with shield

### ISSUE THREAD

**Issue by KaelEdin** [FortAwesome/Font-Awesome#13106]
### What can it be used for?

Can be used for any app/game as a "fight" button. It can also symbolize conflict, dispute or martial arts equipment. With a shield can stand as a sigil or emblem.

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We have a few sword options now! https://fontawesome.com/search?q=sword&o=r&s=solid
