### ISSUE TITLE
Light version of exclamation-triangle has overlapping dots in svg path

### ISSUE THREAD

**Issue by lumierestudios** [FortAwesome/Font-Awesome#13109]
Hello, please take a look to exclamation-triangle icon, it has 2 dots overlapping.

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by lumierestudios** [comment]
Hi!

Your https://fontawesome.com/icons/exclamation-triangle?style=light icon has a bug.
In your vectorial file, you have put 2 overlapping dots.
It's present in the font, and SVG file in all your release versions.
BTW I use the latest 5.0.13 but if you check it's present also in the previous release.

Just download the SVG file from your website here:

https://fontawesome.com/icons/exclamation-triangle?style=light

and open it with illustrator, release the compounding path and you can see the problem.
Same thing on your .otf font and other versions.
It's bugged your source vectorial path.

**Comment by tagliala** [comment]
@lumierestudios thanks for the clarification

@sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
Will check it out, thanks!

**Comment by lumierestudios** [comment]
You can see the problem also in your sign in page.
Look at the background image and you can see the exclamation-triangle (light) without the dot.

https://fontawesome.com/sessions/sign-in

**Comment by talbs** [comment]
Sorry, gang. We said the magic word ("resolve") in a GH Pull Request to fix this, which closed this issue. The fix is merged in and will be out in our next release.

**Comment by talbs** [comment]
Just following up here. This fix has been released officially now and the light style of `exclamation-triangle` (https://fontawesome.com/icons/exclamation-triangle?style=light) should be behaving itself now.

Thanks for the heads up on this and let us know if you see any other funny business.
