### ISSUE TITLE
Icon request: group-add / group-del

### ISSUE THREAD

**Issue by jplusc** [FortAwesome/Font-Awesome#13113]
### What can it be used for?

for user management,  for adding a user to a group, or adding other things.
Two users in front of each other with a + sign, like materials's group_add but based on fa-user-plus and fa-user-friends

May be possible that I can do it with stacking, but was not sure if the fa-plus could be offset to the top-left over fa-user-friends

The matched pair would be the delete icon.

### Example image (optional)

similar to google's material's "group_add" icon
https://glyphsearch.com/?query=group_add
(also attached)

but based on fa-user-plus and fa-user-friends

### Icon request checklist

- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

<img width="144" alt="screenclip 20" src="https://user-images.githubusercontent.com/20580948/39925089-5c689c6c-54f8-11e8-9a77-dae1a7c50271.png">

**Comment by jplusc** [comment]
Or maybe just an offset +/- so we can stack it on whatever?  could  also solve issue 13112 https://github.com/FortAwesome/Font-Awesome/issues/13112

**Comment by HallDaniel** [comment]
Was also going to request the addition of "users-plus"
Would prefer that the + remain on the right side, and the background user is on the left

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
