### ISSUE TITLE
What icons were added in the latest version?

### ISSUE THREAD

**Issue by YamiOdymel** [FortAwesome/Font-Awesome#13116]
The change log doesn't tell us about what icons were added in each of the version. Is there a list about the new icons?

**Comment by Jas-n** [comment]
Going on from this, is there any change to get a "What's New" Section so we can easily see the icons on https://fontawesome.com/icons?

Thank you :)

**Comment by talbs** [comment]
Sorry that this isn't easier right now, folks. Here's a list of the icons added or updated in version 5.0.13:

| Icon  | URL | Changes
|---|---|---|
| balance-scale | https://fontawesome.com/icons/balance-scale | Updated |
| balance-scale-left | https://fontawesome.com/icons/balance-scale-left | New |
| balance-scale-right | https://fontawesome.com/icons/balance-scale-right | New |
| blender | https://fontawesome.com/icons/blender | New |
| book-open | https://fontawesome.com/icons/book-open | New |
| broadcast-tower | https://fontawesome.com/icons/broadcast-tower | New |
| broom | https://fontawesome.com/icons/broom | New |
| chalkboard | https://fontawesome.com/icons/chalkboard | New |
| chalkboard-teacher | https://fontawesome.com/icons/chalkboard-teacher | New |
| church | https://fontawesome.com/icons/church | New |
| coins | https://fontawesome.com/iconscoins/ | New |
| compact-disc | https://fontawesome.com/icons/compact-disc | New |
| crow | https://fontawesome.com/icons/crow | New |
| crown | https://fontawesome.com/icons/crown | New |
| dice | https://fontawesome.com/icons/dice | New |
| dice-five | https://fontawesome.com/icons/dice-five | New |
| dice-four | https://fontawesome.com/icons/dice-four | New |
| dice-one | https://fontawesome.com/icons/dice-one | New |
| dice-six | https://fontawesome.com/icons/dice-six | New |
| dice-three | https://fontawesome.com/icons/dice-three | New |
| dice-two | https://fontawesome.com/icons/dice-two | New |
| divide | https://fontawesome.com/icons/divide | New |
| door-closed | https://fontawesome.com/icons/door-closed | New |
| door-open | https://fontawesome.com/icons/door-open | New |
| equals | https://fontawesome.com/icons/equals | New |
| feather | https://fontawesome.com/icons/feather | New |
| frog | https://fontawesome.com/icons/frog | New |
| gas-pump | https://fontawesome.com/icons/gas-pump | New |
| glasses | https://fontawesome.com/icons/glasses | New |
| greater-than | https://fontawesome.com/icons/greater-than | New |
| greater-than-equal | https://fontawesome.com/icons/greater-than-equal | New |
| helicopter | https://fontawesome.com/icons/helicopter | New |
| infinity | https://fontawesome.com/icons/infinity | New |
| kiwi-bird | https://fontawesome.com/icons/kiwi-bird | New |
| less-than | https://fontawesome.com/icons/less-than | New |
| less-than-equal | https://fontawesome.com/icons/less-than-equal | New |
| memory | https://fontawesome.com/icons/memory | New |
| microphone | https://fontawesome.com/icons/microphone | Updated |
| microphone-alt | https://fontawesome.com/icons/microphone-alt | Updated |
| microphone-alt-slash | https://fontawesome.com/icons/microphone-alt-slash | Updated |
| microphone-slash | https://fontawesome.com/icons/microphone-slash | Updated |
| minus | https://fontawesome.com/icons/minus | Updated |
| money-bill | https://fontawesome.com/icons/money-bill | Updated |
| money-bill-alt | https://fontawesome.com/icons/money-bill-alt | Updated |
| money-bill-wave | https://fontawesome.com/icons/money-bill-wave | New |
| money-bill-wave-alt | https://fontawesome.com/icons/money-bill-wave-alt | New |
| money-check | https://fontawesome.com/icons/money-check | New |
| money-check-alt | https://fontawesome.com/icons/money-check-alt | New |
| not-equal | https://fontawesome.com/icons/not-equal | New |
| palette | https://fontawesome.com/icons/palette | New |
| parking | https://fontawesome.com/icons/parking | New |
| percentage | https://fontawesome.com/icons/percentage | New |
| plane | https://fontawesome.com/icons/plane | Updated |
| plus | https://fontawesome.com/icons/plus | Updated |
| project-diagram | https://fontawesome.com/icons/project-diagram | New |
| receipt | https://fontawesome.com/icons/receipt | New |
| robot | https://fontawesome.com/icons/robot | New |
| ruler | https://fontawesome.com/icons/ruler | New |
| ruler-combined | https://fontawesome.com/icons/ruler-combined | New |
| ruler-horizontal | https://fontawesome.com/icons/ruler-horizontal | New |
| ruler-vertical | https://fontawesome.com/icons/ruler-vertical | New |
| school | https://fontawesome.com/icons/school | New |
| screwdriver | https://fontawesome.com/icons/screwdriver | New |
| shekel | https://fontawesome.com/icons/shekel | Updated |
| shoe-prints | https://fontawesome.com/icons/shoe-prints | New |
| sitemap | https://fontawesome.com/icons/sitemap | Updated |
| skull | https://fontawesome.com/icons/skull | New |
| smoking-no | https://fontawesome.com/icons/smoking-no | New |
| store | https://fontawesome.com/icons/store | New |
| store-alt | https://fontawesome.com/icons/store-alt | New |
| stream | https://fontawesome.com/icons/stream | New |
| stroopwafel | https://fontawesome.com/icons/stroopwafel | New |
| times | https://fontawesome.com/icons/times | Updated |
| toolbox | https://fontawesome.com/icons/toolbox | New |
| tshirt | https://fontawesome.com/icons/tshirt | New |
| walking | https://fontawesome.com/icons/walking | New |
| wallet | https://fontawesome.com/icons/wallet | New |
| wrench | https://fontawesome.com/icons/wrench | Updated |

We'll be continuing to improve [fontawesome.com](https://fontawesome.com. Showing you see what's new and what each release/update contains is on our list. Hang tight! 😄

**Comment by alystair** [comment]
Useful but future lists need visuals in the future, no one wants to click individually through a long list. Get a shell guru to make a release generator script for the site/blog

**Comment by talbs** [comment]
Hey, gang. Thanks again for letting us know this was important. We've got two new things on fontawesome.com to help with learning about what's new with each release.

* A new CHANGELOG/release view - https://fontawesome.com/changelog/latest
* Latest Release filter in our Icons listing - https://fontawesome.com/icons?d=gallery&v=5.1.0

Hope this helps keep you in the know on what's new. 😄

**Comment by tagliala** [comment]
@talbs this doesn't work for me for version 5.2.0

https://fontawesome.com/icons?d=gallery&v=5.2.0
