### ISSUE TITLE
Icon request: clube-da-voz

### ISSUE THREAD

**Issue by ductba** [FortAwesome/Font-Awesome#13115]
Hi, I looked for a similar icon and I did not find it, it would be possible to create this icon below. is the Brand: Clube da Voz. 

I would like to use this icon in a web application

Thank you in advance.

![clubedavoz](https://user-images.githubusercontent.com/39117010/39925904-e10e0afa-5503-11e8-877d-eb2c016518ae.png)

**Comment by InsanityMeetsHH** [comment]
To request a new icon you have to read and use this [file](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
@ductba could you please provide more information on this brand?

**Comment by tagliala** [comment]
This should be a duplicate of #13117

**Comment by ductba** [comment]
this brand is from the voice club. professionals. Announcers, ask for a creation.
https://www.clubedavoz.com.br/sobre
