### ISSUE TITLE
Please add a half star

### ISSUE THREAD

**Issue by visavi** [FortAwesome/Font-Awesome#13114]
Please add a half star as in the old version
![2018-05-11 16-04-22](https://user-images.githubusercontent.com/826831/39925653-1e732de0-5535-11e8-9c3d-a529c96b11ab.png)

When displaying a rating, new stars look very bad
![2018-05-11 16-05-56](https://user-images.githubusercontent.com/826831/39925679-383fe984-5535-11e8-955e-c5b5b867c17c.png)

**Comment by Eldenroot** [comment]
+1

**Comment by ernsheong** [comment]
Yes, now we can only do this:
![image](https://user-images.githubusercontent.com/1343284/40222890-9fb5a5bc-5ab3-11e8-8ffc-42de08c916e6.png)

**Comment by AndreaPappi** [comment]
+1

**Comment by jpcbarros** [comment]
+1, it makes life a lot easier than needing to have a "background star" using the "regular" style just to accomplish this very simple thing.

**Comment by visavi** [comment]
added 5.1
