### ISSUE TITLE
Carcassonne Meeple icon

### ISSUE THREAD

**Issue by Eldenroot** [FortAwesome/Font-Awesome#13124]
Add Carcassonne meeple icon - http://game-icons.net/delapouite/originals/meeple.html

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4843, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
