### ISSUE TITLE
Font Awesome 5+ Does not render correctly on Chrome 51

### ISSUE THREAD

**Issue by needforsuv** [FortAwesome/Font-Awesome#13131]
Font Awesome 5+ Does not render correctly on Chrome 51
Some appear as boxes

**Comment by needforsuv** [comment]
picture

**Comment by needforsuv** [comment]
![1](https://user-images.githubusercontent.com/36807483/39977538-f98b451c-577d-11e8-81b5-1e7af9e59290.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is there a reason for using Chrome 51? Is there something preventing you to update?

We know there is the same issue on Chrome 49, but the reason is that Chrome 49 is the latest running version on Windows XP: #12693

Sorry but Chrome 55 is not officially supported by FA5, please take a look at: https://fontawesome.com/how-to-use/web-fonts-with-css#browser-support

**Comment by needforsuv** [comment]
Chrome 52+ Renders fonts poorly (GDI removed) and ugly and new released has ugly material design which can't be switched off
(That's a google problem)
I am bringing this up because it works fine in FIREFOX 51 and I FIND it DISAPPOINTING that you don't make it work on more browsers when it is intended to be universal
YOU SAY IE9 is supported yet your site doesn't even render in IE9 (Font Awesome 5)
THAT BEING SAID IF I copy the HTML from FF51 to IE9 it renders ALL THE FONTS
THE main problem is that ICONS which OTHERWISE render fine using font awesome 4 appear as boxes when the font is specified as FA5
SUMMERY: I get that older browsers may not support the full range of icons BUT WHEN FA5 RENDERS LESS icons than FA4 that's a bug
There should not be any reason the base code can't work on more browsers

**Comment by tagliala** [comment]
Hi, 

thanks for your clarification.

I'm sorry for your disappontment, I will try to clarify some points

> I am bringing this up because it works fine in FIREFOX 51 and I FIND it DISAPPOINTING that you don't make it work on more browsers when it is intended to be universal

Chrome 51, as well as Firefox 51, are not supported. In other words, if they work that's fine but if they don't work we will give low priority to those issues.

> YOU SAY IE9 is supported yet your site doesn't even render in IE9 (Font Awesome 5)

Font Awesome 5 webfont does support IE9, please take a look at https://tagliala.github.io/fa13131

Screenshot attached:
![image](https://user-images.githubusercontent.com/556268/40050171-fa6bfd46-5836-11e8-98f7-1a9e22d68f00.png)

The documentation website, instead, is a modern javascript web application that does not support IE9. In other words, the website does not support IE9, Font Awesome does.

> THE main problem is that ICONS which OTHERWISE render fine using font awesome 4 appear as boxes when the font is specified as FA5
> SUMMERY: I get that older browsers may not support the full range of icons BUT WHEN FA5 RENDERS LESS icons than FA4 that's a bug

Font Awesome 5 is more complex than FA4. FA5 provides way more icons, in different styles, so it uses the same font name with different weights. Also, brands come in a separate font. Maybe older browsers have issues with this approach. It is a design choice that could not work for your use case.

If you need support for unsupported versions of Chrome, please keep using FA 4.7.0. You may also be interested in a [custom version of FA5](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome)

If you want to get updates about Chrome 49, please subscribe to #12693. Maybe that one will solve those issue with Chrome 51 but, as I mentioned before, it has low priority.

Hope it helps

Regards

**Comment by needforsuv** [comment]
Thank you for the response
but what I find odd is that just substituting FA(4) in the F12 menu (font) renders more icons than FA5 without changing the class etc which are still FA5
Is there a particular reason IE9 is supported but not chrome 51 or older chrome versions?
It is released in 2011 and the only OS that doesn't support newer IE is vista
