### ISSUE TITLE
Icon display for old version (v.5.0.9)

### ISSUE THREAD

**Issue by rullymartanto** [FortAwesome/Font-Awesome#13135]
how can i see the list of icons in the old version 5.0.9 ?
Thanks

**Comment by InsanityMeetsHH** [comment]
e.g. [here](https://github.com/FortAwesome/Font-Awesome/blob/864e2422319243c59f45752623d1e2490557eb67/web-fonts-with-css/less/_icons.less)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is not possible at the moment.

Anyway, via [github releases](https://github.com/FortAwesome/Font-Awesome/releases) and tags, you will be able to get [yml](https://github.com/FortAwesome/Font-Awesome/blob/5.0.9/advanced-options/metadata/icons.yml) or [json](https://github.com/FortAwesome/Font-Awesome/blob/5.0.9/advanced-options/metadata/icons.json) metadata containing all the icons present in the specified version

Hope it helps

Feel free to close here if this answer your question

Also, this could refer to #13031

**Comment by rullymartanto** [comment]
Thanks guys ...
