### ISSUE TITLE
smoking ban not working

### ISSUE THREAD

**Issue by kateboothby** [FortAwesome/Font-Awesome#13134]
Hi, https://fontawesome.com/icons/smoking-ban?style=solid

Is not working. all other icons work but not this one.

Code Im using

	<i class="fa fa-4x fas fa-smoking-ban text-primary mb-3 sr-icons"></i>

where as this works
	<i class="fa fa-4x fas fa-home text-primary mb-3 sr-icons"></i>

**Comment by fxmountain** [comment]
Its working for me [Demo](https://jsfiddle.net/mLL3LL71/).

I am not shure if text-primary is a fa class?

Maybe this applies custom styling and you got some white icon on white bg? Idk.

**Comment by kateboothby** [comment]
Hi, please see attached screen shots.

**Comment by InsanityMeetsHH** [comment]
fa-smoking-ban is working.
It depends on the version you use.
You have to use at least version 5.0.13 to use this icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

as @InsanityMeetsHH mentioned, please make sure you are using FA >= 5.0.13.

Hope it helps

closing here
