### ISSUE TITLE
Icon request: fa-file-music (Sheet music icon)

### ISSUE THREAD

**Issue by webfelipemaia** [FortAwesome/Font-Awesome#13142]
Hello.
I would like you to create an icon for sheet music.
Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example?

**Comment by webfelipemaia** [comment]
ThanksThank you.
There are actually more possibilities for using musical icons. But there's another opportunity.

**Comment by tagliala** [comment]
Please notice that you can achieve this icon with the masking feature of the SVG framework: 

https://jsfiddle.net/tagliala/d7w55ryp/11/

Ref: https://fontawesome.com/how-to-use/svg-with-js#masking

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-music?style=solid
