### ISSUE TITLE
Icon Request: Cat and Dog

### ISSUE THREAD

**Issue by fusiongt** [FortAwesome/Font-Awesome#13145]
I've been using FontAwesome for a long time now and was surprised to find there's no cat or dog icon! I could see a use case for real estate or apartment sites that allow (or disallow) dogs and cats. There Could also be a use case where people just like using fun icons on a page!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cat is a duplicate of #2226, please add a 👍  reaction to that request.
Dog is a duplicate of #1317 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
