### ISSUE TITLE
Can't install pro files via NPM 401 Unauthorized

### ISSUE THREAD

**Issue by yingrm** [FortAwesome/Font-Awesome#13147]
Hello

I have tried fallowing along with this [https://fontawesome.com/how-to-use/use-with-node-js#pro](url)

`$ npm config set "@fortawesome:registry" https://npm.fontawesome.com/`
`$ npm config set "//npm.fontawesome.com/:_authToken" MY-TOKEN`

or

`$ npm config set @fortawesome:registry https://npm.fontawesome.com/MY-TOKEN`

but when I try 

`$ npm i --save @fortawesome/fontawesome`

It's fail with the error message.

`$ npm i --save @fortawesome/fontawesome `
`npm ERR! code E401`
`npm ERR! 404 401 Unauthorized: @fortawesome/fontawesome@latest`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!  C:\xxx\npm-cache\_logs\2018-05-15T08_41_35_212Z-debug.log`

Is there something wrong? Thanks

**Comment by nakulpuranik** [comment]
@yingrm I'm facing the same issue. How did you manage to solve it ?

**Comment by yingrm** [comment]
> @yingrm I'm facing the same issue. How did you manage to solve it ?



> @yingrm I'm facing the same issue. How did you manage to solve it ?

The first time,token is wrong.now when i use the token in diffrent computer,it happens again
