### ISSUE TITLE
fa-youtube-square has some issues.

### ISSUE THREAD

**Issue by DoubleThePsycho** [FortAwesome/Font-Awesome#13154]
Title says it all, the youtube-square icon doesn't display much, more like a square with 4 characters in it (F I 6 6)

([Image link](https://img.doublethepsycho.tk/sasupiviwe))

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check that you are using FA >= 5.0.3 ?

**Comment by DoubleThePsycho** [comment]
I'm currentøy on the latest release, sir ^^

**Comment by Amiba82** [comment]
**ima noob fron Google** I using the latest and foguring it out

**Comment by tagliala** [comment]
@DoubleThePsycho could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Of course I cannot replicate:
SVG: https://jsfiddle.net/tagliala/d7w55ryp/5/
CSS: https://jsfiddle.net/tagliala/6yrybgho/2/

Please also make sure that you are indirectly loading an older version (plugins, themes, etc.)

**Comment by DoubleThePsycho** [comment]
### Describe the problem
I tried inserting the `fa-youtube-square` icon on a forum I manage, and it returned very odd.

### What did you expect?
I honestly expected it to work, I mean FontAwesome 5 has had really few issues this far, not really expecting too many issues.

### What version and implementation are you using?
Version: v5.0.13
Browser and version: Google Chrome, Mozilla Firefox.

### Reproducible test case

https://forum.terratechgame.com/index.php#uix_stickyFooterSpacer
^ Icon is loaded in the footer ^

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [  ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
@DoubleThePsycho found it.

As I mentioned before

> Please also make sure that you are indirectly loading an older version (plugins, themes, etc.)

There is a plugin ora a library loading an older version of FA which is overriding FA5's css rules.

![image](https://user-images.githubusercontent.com/556268/40164252-4fdd4158-59b9-11e8-94b8-b1ecae74cbe7.png)


```
https://forum.terratechgame.com/styles/uix/uix/css/font-awesome.min.css
```

```
Font Awesome 4.6.3 by @davegandy - http://fontawesome.io - @fontawesome
```

Hope it helps

Closing here

**Comment by mitdibs** [comment]
Hi everybody,

I have the same problem and I verified, I'm not loading an old version of Font Awesome but the good one.

.fa-youtube-square::before {
    content: "\f431";
}

**Comment by tagliala** [comment]
Hi @mitdibs, please open a new issue following by filling out our bug report template: https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md
