### ISSUE TITLE
$.switchClass Not Working

### ISSUE THREAD

**Issue by iBrian71** [FortAwesome/Font-Awesome#13168]
When I perform a JQuery task on a toggle switch to change icon and color, it only changes the Icon
This is in Chrome, using FontAwesome Pro 5.0.13 SVG, Bootstrap 3.7, jquery 3.2.1
I went to SVG because fa-spin did not work in the CSS mode

i.e 
<i id="t" class="fas fa-toggle-off text-danger"></i>

JS
$('#t').switchClass('fa-toggle-off', 'fa-toggle-on');     Works
$('#t').switchClass('text-danger', 'text-success');     Does Not Work

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Did you read our documentation about jquery?
https://fontawesome.com/how-to-use/svg-with-js#with-jquery

Please notice that original elements in the dom are removed and replaced by their SVG counterpart

Could you please provide a reproducible test case? You can start with this one: https://jsfiddle.net/tagliala/d7w55ryp/6/ (FA SVG 5.0.13 + jQuery slim 3.1.1)

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by iBrian71** [comment]
I cannot seem to reproduce the exact problem in that fiddle. 
Seems like the best solution will be to go back to css without rewriting a lot of code, but can you confirm that fa-spin is a problem in the css version.  Instead of Spinning - it pulses..

as in <i class="fa fa-circle-notch fa-spin"></i>

Not working in Chrome Version 66.0.3359.181 (Official Build) (64-bit) and safari    

Noticed in Windows and OSX

**Comment by iBrian71** [comment]
Also 
This works as svg, but goes so wrong in css


    <div id="display-loading" style="display: none;" class="row well-lg">
       <div class="panel panel-primary col-xs-12 col-sm-12 col-md-12 col-lg-12 font-2" style="display: table; margin-left: auto; margin-right: auto; text-align: center;">

          <span class="fa-layers fa-fw margintop-3 marginbottom-3">
            <i class="far fa-circle-notch fa-spin fa-5x text-info"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-warning" data-fa-transform="shrink-4 rotate-60"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-danger" data-fa-transform="shrink-5 rotate-180"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-success" data-fa-transform="shrink-6 rotate-300"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-warning" data-fa-transform="shrink-7 rotate-90"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-danger" data-fa-transform="shrink-8 rotate-210"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-success" data-fa-transform="shrink-9 rotate-330"></i>
            <i class="fal fa-spinner-third fa-spin fa-5x text-danger" data-fa-transform="shrink-10 rotate--216 "></i>
            <i class="far fa-cog fa-spin fa-5x text-info faa-flash faa-slow animated" data-fa-transform="shrink-12 "></i>
          </span>
        </div>
    </div>

**Comment by tagliala** [comment]
Hi,

SVG and CSS work differently.

SVG docs: https://fontawesome.com/how-to-use/svg-with-js
CSS docs: https://fontawesome.com/how-to-use/web-fonts-with-css

`layers` is an SVG feature: https://fontawesome.com/how-to-use/svg-with-js#layering

> I went to SVG because fa-spin did not work in the CSS mode

Unable to reproduce: https://jsfiddle.net/tagliala/6yrybgho/4/

Going back to your issue, please notice that if you are using SVG and you want to toggle spin, you should use idempotent event because original elements of the dom are going to be replaced

Eg: https://jsfiddle.net/tagliala/d7w55ryp/10/

**Comment by iBrian71** [comment]
Thanks - I will go back and read the doco more thourougly
