### ISSUE TITLE
Font-Awesome-Full breaks documentation layout

### ISSUE THREAD

**Issue by ratajs** [FortAwesome/Font-Awesome#13160]
![prtscr](https://user-images.githubusercontent.com/19972986/40133403-eb5a461e-593f-11e8-901a-a2e8d9860071.jpg)
The icon Font-Awesome-Full is displaying as empty rectangle (missing character representation).
![prtscr2](https://user-images.githubusercontent.com/19972986/40133492-4147a846-5940-11e8-8d53-0c081ea2b44d.jpg)
In the details page it's very messy.

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this.

I can confirm (Chrome 66 / Windows 10)

![image](https://user-images.githubusercontent.com/556268/40134829-dbc6494c-5943-11e8-88bc-bf87de0145f3.png)

Given that this glyph is causing [other troubles](#13044), should we remove it?

**Comment by talbs** [comment]
As @mlwilkerson mentioned, `font-awesome-full` wasn't intended to be an icon listed in the gallery (its purpose is to help desktop users when selecting the right font). The icon has been removed from the gallery and this shouldn't be an issue any longer.

Thanks for the heads up and bringing this to our attention. 😄
