### ISSUE TITLE
font-awesome 5 pro webfonts don't render

### ISSUE THREAD

**Issue by ForkInSpace** [FortAwesome/Font-Awesome#13169]
Got .ttf format pro icons form a designer and after converting them to webfonts, I've dropped those physical files into my react project. 

None of the pro icons render, free ones do. 

Am I missing something here?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by ForkInSpace** [comment]
I personally don't have access to FA pro, so the link won't work for me.

**Comment by tagliala** [comment]
Sorry but if you don't have access to FA Pro, there is a license issue: redistribution is explictly forbidden

https://fontawesome.com/license

> "Distribute or Redistribute Font Awesome Pro."
