### ISSUE TITLE
icon Google Hangouts

### ISSUE THREAD

**Issue by PROCREATIVOS** [FortAwesome/Font-Awesome#13167]
[google-hangouts-logo.eps.zip](https://github.com/FortAwesome/Font-Awesome/files/2014808/google-hangouts-logo.eps.zip)

**Comment by aethior** [comment]
@tagliala `brand (category)` label for this request?

**Comment by tagliala** [comment]
Isn't hangouts going to be dismissed?

https://blog.google/products/workspace/latest-google-hangouts-and-upgrade-google-chat/

**Comment by tagliala** [comment]
Closing here, please refer to #18869 for google chat
