### ISSUE TITLE
Icon request:icon-rotate

### ISSUE THREAD

**Issue by dwjohnston** [FortAwesome/Font-Awesome#13177]
There's lots of examples of what I'm looking for: 

https://www.google.com.au/search?q=rotate+icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Already here: https://fontawesome.com/icons/redo?style=solid

Actually the documentation doesn't show this icon if you search for `rotate`, but we are constantly monitoring and improving search terms.
