### ISSUE TITLE
Icon request: snowman

### ISSUE THREAD

**Issue by uok** [FortAwesome/Font-Awesome#13179]
Request for a snowman icon, because they are fun and my air condition is broken :smile: 
Use cases: websites for (grown) kids and winter activities, seasonal, weather
Thanks!

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [☃️](http://emojipedia.org/snowman/) U+2603 Snowman
- [⛄](http://emojipedia.org/snowman-without-snow/) U+26C4 Snowman without Snow

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/snowman?style=solid
