### ISSUE TITLE
Icon Request: icon-dog

### ISSUE THREAD

**Issue by tvanprooyen** [FortAwesome/Font-Awesome#1317]
edit by @tagliala
## 

Im making a store for pets and i need some diffrent pets, like dog, cat, bird, fish, reptile, small animal. Then i would also need would be a food dish and toy. You can use these images because they are owned by the company i work for. Im sorry for them not being only one color though.

Thank you!

![iconfoods](https://f.cloud.github.com/assets/4705130/658321/cb24133c-d5d4-11e2-9f94-c33596433bcd.png)
![iconbirds](https://f.cloud.github.com/assets/4705130/658319/cb22c32e-d5d4-11e2-9af2-69f19db12748.png)
![icondogs](https://f.cloud.github.com/assets/4705130/658320/cb24ef78-d5d4-11e2-9d10-41d4b50fa375.png)
![iconcats](https://f.cloud.github.com/assets/4705130/658322/cb2595cc-d5d4-11e2-8b93-68acdf7c80db.png)
![icongetactive](https://f.cloud.github.com/assets/4705130/658323/cb25d14a-d5d4-11e2-8f71-b99036284439.png)
![iconfish](https://f.cloud.github.com/assets/4705130/658324/cb245770-d5d4-11e2-81f5-85388ab35d30.png)
![iconsmallanimals](https://f.cloud.github.com/assets/4705130/658326/cb2f8a46-d5d4-11e2-9bae-9b759ef0b67f.png)
![iconreptilesandamphibians](https://f.cloud.github.com/assets/4705130/658325/cb2e6ecc-d5d4-11e2-8a3b-f789043ebfe9.png)

**Comment by kellybj** [comment]
+1 please!

**Comment by G-Driver** [comment]
+1

**Comment by Bluetegu** [comment]
+ 1 for fa-dog and +10 for fa-dog-walker (needed for a dog walking service). Awesome work!!

**Comment by farukscan** [comment]
+1 for fa-dog
+1 for fa-cat

**Comment by GwenLoguir** [comment]
+1 for every animal (+rat)

**Comment by aduffett** [comment]
+1 for fa-dog
+1 for fa-cat

**Comment by viniciushaga** [comment]
+1 !

**Comment by jbarber1981** [comment]
+1
I work for a humane society and these would be great for all of our documents and website.  I'm improvising right now by using fa for almost everything, but then having to use img based icons for the rest and it's getting pretty tedious and annoying from a web-design perspective.  These could have many uses for folks in the animal-related fields (vets, shelters, humane societies, pet stores, health departments) and also for people who just like animals!  I also would like to see a fa-bat since bats and Rabies is something we're writing about a lot!

**Comment by lyhil** [comment]
+1 for all of them...
cat maybe like ? http://thumb9.shutterstock.com/display_pic_with_logo/85920/134691032/stock-photo-black-cat-sitting-and-looking-at-the-camera-isolated-on-white-134691032.jpg
or http://fscomps.fotosearch.com/compc/UNC/UNC218/u17637223.jpg
just sitting... dog too

**Comment by rhysd** [comment]
+1 :dog2:

**Comment by wraith13** [comment]
+1 🐾

**Comment by omespino** [comment]
+1 for fa-dog & fa-cat

**Comment by piergi74** [comment]
+1 for fa-dog & fa-cat

**Comment by tagliala** [comment]
Please +1 #2226 for a cat , let's use this one only for dog

**Comment by ansela** [comment]
+1 for fa-dog & fa-cat

**Comment by ahoulgrave** [comment]
+1

**Comment by joexanderson** [comment]
+1

**Comment by GertG** [comment]
+1

**Comment by Reyeh** [comment]
+1

**Comment by ajunior** [comment]
+1

**Comment by ajunior** [comment]
+1

**Comment by leesalminen** [comment]
+1

**Comment by MWTCymru** [comment]
+1

**Comment by noelcosgrave** [comment]
+1

**Comment by samhk222** [comment]
+1

**Comment by juliebarber** [comment]
+1 +1 +1 +1!!!!

A basic set of animals would be awesome.  Working at a Humane Society, I am in need of icons like that all the time!  Any vet clinic, humane organization, rescue group, shelter, farm, wildlife rehabilitation, or other animal related group could really use these!  

I would suggest at a minimum:  
fa-cat
fa-dog
fa-rabbit
fa-reptile
fa-turtle
fa-fish
fa-bird
fa-bat
fa-horse
fa-raccoon
fa-elephant (could also be political)
fa-donkey (could also be political)
fa-caduceus (veterinary symbol)

Others could be added but that would give a large number of animal groups a lot to work with.

Thanks!

**Comment by joexanderson** [comment]
@juliebarber Totally agree. It would be nice to actually see some movement on this one. We have icons for everything else so I hope we can get some animal icons :)

**Comment by jngr** [comment]
+1

**Comment by Crissov** [comment]
Of the animals listed by OP @tvanprooyen, @jbarber1981 and @juliebarber, these already have Unicode code points for emojis:

* **dog** 🐕 U+1F415, 🐩 U+1F429 (poodle), 🐶 U+1F436
* cat 🐈 U+1F408, 🐱 U+1F431 → #2226
* bird 🐦 U+1F426 → #5363
* (tropical) fish 🐠 U+1F420, also 🐟 U+1F41F → #2722
* rabbit 🐇 U+1F407, 🐰 U+1F430 → #2453
* turtle 🐢 U+1F422 → #2453
* bat 🦇 U+1F987 → ~ #1951
* reptile 🐸 U+1F438 (frog), 🦎 U+1F98E (lizard)
* horse 🐎 U+1F40E, 🐴 U+1F434 → #2049
* elephant 🐘 U+1F418 → #8592, #7382
* (tennis ball 🎾 U+1F3BE → #714)
* (caduceus ☤ U+2624 → #4325)

The rest is not standardized (yet):

* raccoon 
* donkey → #7382 
* (bowl)

**Comment by iuliux** [comment]
A good alternative is portrait 🐶

<img src="https://cloud.githubusercontent.com/assets/1446677/23992593/26e0e700-0a46-11e7-9df2-c75a3d1481b1.png" width="100px"/>

**Comment by timtjtim** [comment]
![dog](https://user-images.githubusercontent.com/6292691/29341445-3f8ddc6a-821c-11e7-920a-e9b2f36c5066.png)

**Comment by Lorewyn** [comment]
Dog icons would be great especially a bowl, bone, collar, dog. I have a few dog sites I have built that I would love to use these on.

**Comment by kenn213** [comment]
I'm honestly very surprised that very common animals like pets (dog, cat, bird, etc...) and farm animals (horse, cow, pig, chicken, etc...) aren't already included. These both seem like they'd be very useful.

**Comment by Wingo5315** [comment]
This would be very useful for many people. +1

**Comment by ajunior** [comment]
+1

**Comment by SLIcoreDesign** [comment]
+1 for doggo!

**Comment by NeogDesigner** [comment]
+1

**Comment by Ednas** [comment]
+1

**Comment by mijrs** [comment]
+1 for fa-dog

**Comment by Fatbat** [comment]
+1 for dog and cat icons.

**Comment by ATLAdamL** [comment]
+1

**Comment by sensibleworld** [comment]
Man's best friend has finally found a home in Font Awesome: https://fontawesome.com/icons/dog?style=solid (along with a version you can take for walks around town: https://fontawesome.com/icons/dog-leashed?style=solid).

**Comment by juliebarber** [comment]
Thank you!  These are awesome!  I’ll be adding them our Humane Society website starting Monday!

Sent from my iPhone

Find me at bluejcrochet.etsy.com<http://bluejcrochet.etsy.com>
Original crochet patterns and handmade crochet gifts for babies and children

On Oct 13, 2018, at 9:34 AM, Jory Raphael <notifications@github.com<mailto:notifications@github.com>> wrote:


Man's best friend has finally found a home in Font Awesome: https://fontawesome.com/icons/dog?style=solid<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fdog%3Fstyle%3Dsolid&data=02%7C01%7C%7C3bb1e46743ba4cb7235d08d631108fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636750344525533054&sdata=CTBByFMwq6rIwrbmLKMlTXVHGERBxiXnOfzsE0tb5IE%3D&reserved=0> (along with a version you can take for walks around town: https://fontawesome.com/icons/dog-leashed?style=solid<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fdog-leashed%3Fstyle%3Dsolid&data=02%7C01%7C%7C3bb1e46743ba4cb7235d08d631108fdc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636750344525533054&sdata=NVXACnKR9UisL90T0jvxYl11ARk7AbCYOfadO4DiJiI%3D&reserved=0>).

**Comment by sensibleworld** [comment]
@juliebarber There's also a new cat icon :) https://fontawesome.com/icons/cat?style=solid

**Comment by juliebarber** [comment]
I saw them all, I’m super excited.  #meganerd

Sent from my iPhone

Find me at bluejcrochet.etsy.com<http://bluejcrochet.etsy.com>
Original crochet patterns and handmade crochet gifts for babies and children

On Oct 13, 2018, at 1:51 PM, Jory Raphael <notifications@github.com<mailto:notifications@github.com>> wrote:


@juliebarber<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjuliebarber&data=02%7C01%7C%7Ce3bad203e745414d5a0808d6313481c9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636750498909393040&sdata=ad1t6UkxOehdf8U6IK6Cw4GR3fetlj%2Bji2ryF%2FHwHQo%3D&reserved=0> There's also a new cat icon :) https://fontawesome.com/icons/cat?style=solid<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fcat%3Fstyle%3Dsolid&data=02%7C01%7C%7Ce3bad203e745414d5a0808d6313481c9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636750498909393040&sdata=ciL3PRe9P56P0mm0TnZWBRbzil2GgP0Vuhy%2BVZzMvhc%3D&reserved=0>
