### ISSUE TITLE
Icon Request: number

### ISSUE THREAD

**Issue by iFA88** [FortAwesome/Font-Awesome#13175]
Greetings,
I would like to use an icon for declare the input type, but I don't find any similar icon for that.
It would great like `123`.

Many thanks!

**Comment by iFA88** [comment]
dump

**Comment by eduludi** [comment]
The same use case that @iFA88 describes is what I need. IMHO this is a basic icon that should be part of FA.

**Comment by sdh-olivier** [comment]
Roman numbers would be useful too.

**Comment by ColinLaws** [comment]
Yep, this would be useful to me as well. Roman numerals and circle-n would be awesome.

**Comment by hpvd** [comment]
+1

**Comment by okohll** [comment]
+1

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/input-numeric?

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, thanks.

I'm going to consider this closed by https://fontawesome.com/icons/input-numeric?s=solid&f=classic

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) if the above icons does not fit this use case.

Please also clarify why the actual icon does not fit the use case, why a different design is needed, and provide an example
