### ISSUE TITLE
Icon request: icon-fiverr

### ISSUE THREAD

**Issue by Selah1337** [FortAwesome/Font-Awesome#13183]
Icon for Fiverr marketplace. Useful for companies that would like to link back to their Fiverr page to help get more business on Fiverr through their personal website.

![untitled-1](https://user-images.githubusercontent.com/31610416/40329993-8927df46-5d19-11e8-9766-4dc7583bdc9c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #5970, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
