### ISSUE TITLE
 Icon request: webcam webcam-off

### ISSUE THREAD

**Issue by tecnoweb** [FortAwesome/Font-Awesome#1318]
For use in applications where you need to activate-deactive the user webcam.
![add_webcam](https://f.cloud.github.com/assets/1049542/1174083/cf7cf1a6-2142-11e3-839e-910fe4202f05.png)
![remove_webcam](https://f.cloud.github.com/assets/1049542/1174084/cfa8e3ba-2142-11e3-853d-b5b4edaf0839.png)

**Comment by ocedric** [comment]
Definitely +1

**Comment by haryanto-darma** [comment]
+1

**Comment by LauritzT** [comment]
+1

**Comment by afelicioni** [comment]
+1

**Comment by afelicioni** [comment]
+1

**Comment by zgababa** [comment]
+1

**Comment by Entwanderer** [comment]
+1

**Comment by designarti** [comment]
+1

**Comment by avaiyakirtib** [comment]
+1

**Comment by joehillen** [comment]
:+1:

**Comment by codyn329** [comment]
+1

**Comment by zarybnicky** [comment]
+1

**Comment by bartbutenaers** [comment]
+1

**Comment by Startouf** [comment]
+1
(Now that github supports voting on posts, I suggest you all do that on the first post)

**Comment by pgrodrigues** [comment]
+1

**Comment by ierpe** [comment]
+1

**Comment by sensibleworld** [comment]
hey folks... do these icons fit the bill, or is there still a need for a webcam-specific icon?

<img width="403" alt="screenshot 2018-03-21 14 18 42" src="https://user-images.githubusercontent.com/529604/37729305-081605a8-2d13-11e8-8ade-d8db72ac73cd.png">

**Comment by jesobreira** [comment]
@sensibleworld I think there is still seat for a proper webcam icon

**Comment by jjp390** [comment]
I agree that a proper icon is needed @sensibleworld we're having a hard time because we have two distinct things in our system. The camera is used for video that is uploaded. The webcam is something that is more active where they will be talking with a person.

**Comment by m-andrew-albright** [comment]
@sensibleworld Has there been any movement on this?  My team is using pro, and we were all surprised to find the absence of these icons (webcam / webcam slash).

**Comment by m-andrew-albright** [comment]
@BrandonZacharie They can, but not everyone is equal to the task of designing / laying things out in that manner.  I did eventually create a layered set of icons that resembles a webcam, but I did not attempt to do the slash version yet.  One font-awesome icon would definitely be preferable to using layers, but I made do.

Here's the layered representation of "webcam" that I was able to eke out:

![image](https://user-images.githubusercontent.com/4950445/50092090-c0263480-01d2-11e9-9e54-4591fa6a6d01.png)

And the jsx:

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTriangle } from '@fortawesome/pro-solid-svg-icons/faTriangle';
import { faCircle } from '@fortawesome/pro-solid-svg-icons/faCircle';

const WebcamIcon = ({ primaryColor, secondaryColor }) => (
  <span className="fa-layers fa-fw">
    <FontAwesomeIcon
      icon={faTriangle}
      color={primaryColor}
      size="sm"
      transform="shrink-4"
    />
    <FontAwesomeIcon
      icon={faCircle}
      color={primaryColor}
      size="sm"
      transform="shrink-2 up-3"
    />
    <FontAwesomeIcon
      icon={faCircle}
      color={secondaryColor}
      size="sm"
      transform="shrink-6 up-3"
    />
    <FontAwesomeIcon
      icon={faCircle}
      color={primaryColor}
      size="sm"
      transform="shrink-8 up-3"
    />
    <FontAwesomeIcon
      icon={faCircle}
      color={secondaryColor}
      size="xs"
      transform="shrink-10 up-3.5"
    />
    <FontAwesomeIcon
      icon={faCircle}
      color={primaryColor}
      size="xs"
      transform="shrink-9 up-4 right-1"
    />
  </span>
);

WebcamIcon.propTypes = {
  primaryColor: PropTypes.string,
  secondaryColor: PropTypes.string,
};

WebcamIcon.defaultProps = {
  primaryColor: '#000',
  secondaryColor: '#fff',
};

export default WebcamIcon;

```

I haven't worked with FA5 outside of react, so I am not currently familiar with their SVG/JS APIs, but it should be easy for someone who is to extract the meat of this markup and use it outside of react.

Icons used: `faTriangle` and `faCircle`, both are the solid variant.

Good luck!  If anyone creates a slash version before I do, please at-mention me so I can check it out.  Thanks!

**Comment by sensibleworld** [comment]
We're watching you: 
https://fontawesome.com/icons/webcam?style=solid

We're not watching you:
https://fontawesome.com/icons/webcam-slash?style=solid
