### ISSUE TITLE
Tshirt Icon not working for free users

### ISSUE THREAD

**Issue by protonhs** [FortAwesome/Font-Awesome#13184]
Hello,
I'm using many free icons from fontawesome and they're all working, except for the new Tshirt one, ( <i class="fas fa-tshirt"></i>) , it shows nothing.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

t-shirt has been introduced in Font Awesome 5.0.13

Please double check that you are using FA >= 5.0.13

Troubleshooting: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
