### ISSUE TITLE
Fontawesome SVG icon swap

### ISSUE THREAD

**Issue by usabilitest** [FortAwesome/Font-Awesome#13190]
I recently upgraded my fontawesome to the version which converts icons to SVGs with JS.

Before I did it, I was able to swap icon on click:

$("#em").removeClass("fa-times").hide().addClass("fa-spinner fa-pulse").fadeIn();

How do I do it with SVG is I need to replace one static icon with two classes creating animated one?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA5 SVG is going to replace the original element in the dom by a new SVG element, so if you attach events in that way it will not work

Please also note we advise to avoid jquery with the SVG framework

Anyway, you could consider to use a wrapper element: https://jsfiddle.net/tagliala/d7w55ryp/13/

Ref:
- https://fontawesome.com/how-to-use/svg-with-js#with-jquery

Hope it helps

Closing here

**Comment by robinjtuttle** [comment]
this link is dead: https://fontawesome.com/how-to-use/svg-with-js#with-jquery

**Comment by tagliala** [comment]
@robinjtuttle here it is the new link: https://fontawesome.com/how-to-use/on-the-web/using-with/jquery
