### ISSUE TITLE
list-alt icon missing spacing on the bottom

### ISSUE THREAD

**Issue by bgold0** [FortAwesome/Font-Awesome#13191]
I'm using font awesome with the this repository: [https://github.com/shyaniv7/react-native-fontawesome-pro](https://github.com/shyaniv7/react-native-fontawesome-pro)

Wondering if you guys knew the reason behind why the icon would look like this?

<img width="51" alt="screen shot 2018-05-22 at 4 16 07 pm" src="https://user-images.githubusercontent.com/4645400/40390705-ae119654-5ddb-11e8-8133-046d94ecf206.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Given that we cannot provide help or support for third party repositories, I'm not able to replicate this on FA 5.0.13 SVG

Different font sizes, from 16px to 30px
![image](https://user-images.githubusercontent.com/556268/40393619-856abbfa-5e20-11e8-86eb-0ae5405daf06.png)

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

I'm going to close here, but if you still have troubles please reopen this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by bgold0** [comment]
Okay thanks @tagliala , I'm currently using v5.0.9 so I will see if upgrading fixes anything
