### ISSUE TITLE
fa-magento not rendering

### ISSUE THREAD

**Issue by saiharsha6** [FortAwesome/Font-Awesome#13194]
Hello I am trying to use fa-magento icon on my website and it's not showing up. 

http://f5q.8ee.myftpupload.com/content-management-systems/

Please let me know if I am doing something wrong.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that your theme is loading Font Awesome 4.7.0, but Magento has been introduced in FA 5.0.0

https://fontawesome.com/icons/magento?style=brands

Providing support to third party themes is outside the scope of this issue tracker

Hope it helps

Closing here
