### ISSUE TITLE
There is a crow, dove, frog, and kiwi-bird but no dog or cat?

### ISSUE THREAD

**Issue by mtorcutt** [FortAwesome/Font-Awesome#13192]
What is this world coming to?

**Comment by InsanityMeetsHH** [comment]
If you like to see [dog](https://github.com/FortAwesome/Font-Awesome/issues/1317) and [cat](https://github.com/FortAwesome/Font-Awesome/issues/2226) icon then you could give the existing icon requests a thumb up.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Dog is a duplicate of #1317 , please add a 👍  reaction to that request.
Cat is a duplicate of #2226 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
