### ISSUE TITLE
Icon Request: Refresh

### ISSUE THREAD

**Issue by junbinku** [FortAwesome/Font-Awesome#13204]
I was looking for a refresh icon or something similar to represent refresh. It would be good to have.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/redo?style=solid
https://fontawesome.com/icons/redo-alt?style=solid
https://fontawesome.com/icons/sync?style=solid
https://fontawesome.com/icons/sync-alt?style=solid
