### ISSUE TITLE
Icon request :taxi icon 

### ISSUE THREAD

**Issue by hurricane22222** [FortAwesome/Font-Awesome#1320]
also a new icon for taxi would be very usefull..

exemple :http://www.iconfinder.com/icondetails/111918/128/taxi_icon

**Comment by Crissov** [comment]
- 🚖 [U+1F696](http://emojipedia.org/oncoming-taxi/) Unicode emoji #222 
- 🚕 [U+1F695](http://emojipedia.org/taxi/)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/taxi?style=solid
