### ISSUE TITLE
Icon request: vultr

### ISSUE THREAD

**Issue by Cannonb4ll** [FortAwesome/Font-Awesome#13205]
Would be nice to have the Vultr icon inside fontawesome as brand.

![Vultr](https://pbs.twimg.com/profile_images/659346821257560064/Nd5NqN3V_400x400.png)

https://www.vultr.com/

**Comment by sawyerclever** [comment]
+1 for Vultr icon

**Comment by adamjimenez** [comment]
It says completed but I can't find it on the font awesome website?

**Comment by tagliala** [comment]
This request has been closed by the author, feel free to open a new request

**Comment by adamjimenez** [comment]
done: https://github.com/FortAwesome/Font-Awesome/issues/19084
