### ISSUE TITLE
After upgrade: Uncaught TypeError: Cannot read property 'library' of undefined

### ISSUE THREAD

**Issue by driekus77** [FortAwesome/Font-Awesome#13216]
After upgrading my webpack packages to:
```
    "@fortawesome/fontawesome": "^1.2.0-6",
    "@fortawesome/fontawesome-free-brands": "^5.0.13",
    "@fortawesome/fontawesome-free-regular": "^5.1.0-3",
    "@fortawesome/fontawesome-free-solid": "^5.1.0-3",
    "@fortawesome/fontawesome-svg-core": "^1.2.0-11",
    "@fortawesome/vue-fontawesome": "^0.1.0-4",
```

And following your guide about adding icons to a fontawesome library via a special icons.js file:
```
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import { faSpinner } from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(brands, faSpinner)
```

I import above icons.js in my boot.js which also contains the Vuejs main app.

I get the following error when starting the brower (Chrome): 

> Uncaught TypeError: Cannot read property 'library' of undefined

Am I doing something wrong or is something broken in the newest version?

EDIT: 
Forgot to note that when looking in the chrome debugger the fontawesome is NOT undefined. So maybe a timing issue with the imports?

Kind regards,
Henry

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to give you a suggestion because I don't know exactly the issue here:

    "@fortawesome/fontawesome-free-regular": "^5.1.0-3",
    "@fortawesome/fontawesome-free-solid": "^5.1.0-3",
    "@fortawesome/fontawesome-svg-core": "^1.2.0-11",

Please note that you are importing pre-releases versions of those packages. FA 5.1 will work differently from FA 5.0. If you are interested in testing the prerelease versions, take a look at https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

Instructions for the current stable version are available at https://fontawesome.com/how-to-use/use-with-node-js#free are different

So, if you want to :
1. Remove `@fortawesome/fontawesome-svg-core`
2. Use latest stable versions of FA for `"@fortawesome/fontawesome-free-solid"` and `"@fortawesome/fontawesome-free-regular"` (5.0.13)
3. Use the library as per https://fontawesome.com/how-to-use/use-with-node-js#using-the-library

Maybe you have an issue related to #12429. In that case, give a try to the prerelease version of FA

**Comment by driekus77** [comment]
Thanks for the quick response @tagliala ! It explains a lot me living on the edge of a new pre-release :-)

For anybody interessted my icons.js file, which I import in my boot.js (main.js) now looks like:
```
import { config, library, dom } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

config.autoReplaceSvg = 'nest';

//import brands from '@fortawesome/fontawesome-free-brands'

// Default usage icons
import { faSpinner } from '@fortawesome/free-solid-svg-icons';
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import { faSignInAlt } from '@fortawesome/free-solid-svg-icons';
import { faSignOutAlt } from '@fortawesome/free-solid-svg-icons';
import { faEye } from '@fortawesome/free-solid-svg-icons';
import { faEyeSlash } from '@fortawesome/free-solid-svg-icons';
import { faAngleRight } from '@fortawesome/free-solid-svg-icons';
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons';
import { faCalendar } from '@fortawesome/free-solid-svg-icons';
import { faClock } from '@fortawesome/free-solid-svg-icons';

library.add(faSpinner);
library.add(faSearch);
library.add(faSignInAlt);
library.add(faSignOutAlt);
library.add(faEye);
library.add(faEyeSlash);
library.add(faAngleRight);
library.add(faAngleLeft);
library.add(faCalendar);
library.add(faClock);


// Icons for main page
import { faUniversalAccess } from '@fortawesome/free-solid-svg-icons';
import { faUserCircle } from '@fortawesome/free-solid-svg-icons';
import { faCaretDown } from '@fortawesome/free-solid-svg-icons';

library.add(faUniversalAccess);
library.add(faUserCircle);
library.add(faCaretDown);

// Icons for User management
import { faHdd } from '@fortawesome/free-regular-svg-icons';
import { faSyncAlt } from '@fortawesome/free-solid-svg-icons';
import { faUndoAlt } from '@fortawesome/free-solid-svg-icons';
import { faRedoAlt } from '@fortawesome/free-solid-svg-icons';
import { faPlusSquare } from '@fortawesome/free-solid-svg-icons';
import { faMinusSquare } from '@fortawesome/free-solid-svg-icons';

library.add(faHdd);
library.add(faSyncAlt);
library.add(faUndoAlt);
library.add(faRedoAlt);
library.add(faPlusSquare);
library.add(faMinusSquare);

// Kicks off the process of finding <i> tags and replacing with <svg>
dom.watch()
```

Thanks and keep up the good work with this awesome lib!

Kind regards,
Henry

**Comment by tagliala** [comment]
@driekus77 you're welcome

Is your issue solved?

Another question:

Does combining

```js
import { faSpinner } from '@fortawesome/free-solid-svg-icons';
import { faSearch } from '@fortawesome/free-solid-svg-icons';

// ...

library.add(faSpinner);
library.add(faSearch);
```

into

```
import { faSpinner, faSearch } from '@fortawesome/free-solid-svg-icons';

// ...

library.add(faSpinner, faSearch);
```

work?

**Comment by driekus77** [comment]
Ah thanks for the feedback: Yes they do work!

Note: '@fortawesome/fontawesome'  and '@fortawesome/vue-awesome'  are not needed in this set-up.

```
/*
 * FontAwesome 5.1 ! (Currrently a pre-release!)
 * 
 * Using SVG Icons from FontAwesome.
 */

import { config, library, dom } from '@fortawesome/fontawesome-svg-core'

config.autoReplaceSvg = 'nest';

// Default usage icons
import {
	faSpinner,
	faSearch,
	faSignInAlt,
	faSignOutAlt,
	faEye,
	faEyeSlash,
	faAngleRight,
	faAngleLeft,
	faCalendar,
	faClock
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faSpinner,
	faSearch,
	faSignInAlt,
	faSignOutAlt,
	faEye,
	faEyeSlash,
	faAngleRight,
	faAngleLeft,
	faCalendar,
	faClock
);

// Icons for main page
import {
	faUniversalAccess,
	faUserCircle,
	faCaretDown
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faUniversalAccess,
	faUserCircle,
	faCaretDown
);

// Icons for Master / Detail management
import {
	faHdd
} from '@fortawesome/free-regular-svg-icons';
import {
	faSyncAlt,
	faUndoAlt,
	faRedoAlt,
	faPlusSquare,
	faMinusSquare
} from '@fortawesome/free-solid-svg-icons';

library.add(
	faHdd,
	faSyncAlt,
	faUndoAlt,
	faRedoAlt,
	faPlusSquare,
	faMinusSquare
);

// Kicks off the process of finding <i> tags and replacing with <svg>
dom.watch()
```

Issue is solved! Thanks again!

Kind regards,
Henry

**Comment by tagliala** [comment]
@driekus77 one more question

Does tree-shaking work?

**Comment by driekus77** [comment]
Sorry I don't know what you mean with tree-shaking? 

The Icons are showing up on my Vue pages without the use of '@fortawesome/vue-fontawesome' components.
Also the nested SVG inside the <i.....> is working OK!

Is that an answer for you?

**Comment by tagliala** [comment]
> Sorry I don't know what you mean with tree-shaking?

Your compiled JavaScript file should only contain the icon have used: https://fontawesome.com/how-to-use/use-with-node-js#tree-shaking

So you should have a small file instead of a big one with every icon in the set

**Comment by driekus77** [comment]
The link states using :

> '@fortawesome/fontawesome-free-solid/shakable.es.js'

But does this work for the 5.1+ SVG packages as wel? 

In '@fortawesome/free-solid-svg-icons' I couldn't find a 'shakable.es.js' 

NOTE: I set-up gzip support both on server(Kestrel) and client(CompressionPlugin).

Currently my  dist/main.js is 2.9 Mb which is still huge but I came from arround 10 Mb.

**Comment by tagliala** [comment]
> But does this work for the 5.1+ SVG packages as wel?

In 5.1 tree shaking is now functional by default and no additional configuration is required to make it work. It should just work out of the box, you don't need to change your configuration

Meanwhile, closing here
