### ISSUE TITLE
Store Icon not showing

### ISSUE THREAD

**Issue by lydiarose97** [FortAwesome/Font-Awesome#13218]
Hi, 

I've added the store code to my site and it's not showing anything. 
I replaced with the shopping basket and it does pull through. 

The site is here: http://allabouteve.lydiarosedesign.co.uk/
It's THE STORE bit of text in the top bar. 

As you can see in the code, the basket is showing, just not the store icon. 
Let me know if you need anymore info.

Thanks
Lydia

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Note that your theme is using FA 5.0.10, but `store` has been introduced in FA 5.0.13

Upgrading the theme to the last version of Font Awesome will fix the issue

Hope it helps

Closing here
