### ISSUE TITLE
dice-six is one grid unit too high

### ISSUE THREAD

**Issue by swena56** [FortAwesome/Font-Awesome#13210]
<i className="fas fa-dice-six"></i>

Six dice needs to be lowered by one pixel, so it matches dice 1-5

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

**Comment by talbs** [comment]
Thanks for the heads up, @swena56 and apologies for the alignment issue. This should be fixed in our next release. 😄

**Comment by talbs** [comment]
Fixed in version 5.1.0 - https://fontawesome.com/icons/dice-six?style=solid.
