### ISSUE TITLE
fas class is removed by fontawesome js

### ISSUE THREAD

**Issue by crtl** [FortAwesome/Font-Awesome#13211]
Hello,
Ive upgraded my fontawesome version to v5.0.13.
Now the base fontawesome class `fas` gets removed from the elements when they get processed.
For example:
```
<i class="fas fa-phone"></i>
```

Gets transformed into:
```
<svg class="svg-inline--fa fa-envelope fa-w-16" ...>
    ...
</svg>
```

**Comment by InsanityMeetsHH** [comment]
If you don't want to use this feature then you have to remove the FontAwesome JavaScript file from your HTML.
````html
<!--<script type="text/javascript" src="fontawesome.js"></script>-->
````

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, this is the normal behaviour of the SVG framework

If you need extra css rules, please use another class

Ref: https://jsfiddle.net/tagliala/d7w55ryp/16/

Hope it helps

Closing here
