### ISSUE TITLE
Logos missing on list page / broken stylings

### ISSUE THREAD

**Issue by BPSBiro** [FortAwesome/Font-Awesome#13213]
Hey was going through the list; https://fontawesome.com/icons?d=gallery&m=free
and noticed the three font-awesome-logo-full icons were displaying as

F4
E6

clicking into them 

https://fontawesome.com/icons/font-awesome-logo-full?style=solid
https://fontawesome.com/icons/font-awesome-logo-full?style=regular
https://fontawesome.com/icons/font-awesome-logo-full?style=brands

also shows broken stylings

using Linux Mint Firefox

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue and the above glyph is going to be removed from the gallery

Thanks for reporting this

**Comment by tagliala** [comment]
Duplicate of #13160

**Comment by BPSBiro** [comment]
Ah my bad, I did a brief search to make sure I wasn't duping issues, perhaps I did too brief a search ahha :)
