### ISSUE TITLE
Icon Request: fa-policeman

### ISSUE THREAD

**Issue by allor** [FortAwesome/Font-Awesome#13223]
![policeman](https://user-images.githubusercontent.com/6686310/40584892-9d6f4962-61ec-11e8-8d57-4d7f0dcf5cd2.png)

Need icons for 000 (like 911) services

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3372, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
