### ISSUE TITLE
:hover cuts icon off

### ISSUE THREAD

**Issue by DaniSpringer** [FortAwesome/Font-Awesome#13237]
I set the color of an icon to purple and background to white, then set the :hover to the exact opposite.
Hovering hides half the icon (shows bottom half only).

1.
![01](https://user-images.githubusercontent.com/19246409/40693598-8629d22c-63b8-11e8-80f4-e1ce0d1200d4.png)

2.
![02](https://user-images.githubusercontent.com/19246409/40693619-a32635d2-63b8-11e8-8a51-fd2cf7109f39.png)

Edit: I'm applying those styles to a link, in which the icon is nested.
HTML:
```html
<a title="my title" href="example.com" rel="noopener">
    <i class="fas fa-youtube-square fa-2x"></i>
</a>
```

CSS:
```
a:active,
a:link,
a:visited {
    color:  #4c1742;
    text-decoration: none;
}

a:hover {
    color: #77cce6;
    text-decoration: none
}
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which version of font awesome are you using?

**Comment by DaniSpringer** [comment]
I'm not 100%, but I believe 5.0.13, because I downloaded the css like a day ago.

If it can help, here's the site I'm using them on: https://danispringer.github.io/gm.html
And the repo: https://github.com/DaniSpringer/danispringer.github.io 

Please let me know if you need any more info.

Thank you 

— 
- iOS Developer, Songwriter, Tea Drinker 
- Let’s connect on LinkedIn
- New music coming June 1. Ready to wake up? Follow me to get notified.

**Comment by tagliala** [comment]
It appears to be a custom version of FA 5.0.13 CSS

I'm not able to replicate on your website.

Here it is a fiddle with your css: https://jsfiddle.net/tagliala/6yrybgho/5/

Could you please edit the fiddle to replicate the issue, save and provide me the link?

**Comment by DaniSpringer** [comment]
Note that in order for hover changes to apply altogether, I changed span to <I>, which is suggested on the FA website.

Link:
https://jsfiddle.net/6yrybgho/6/ <https://jsfiddle.net/6yrybgho/6/>

Screen recording:



Replicated on Safari, Chrome, and Vivaldi. Running MacOS.


Thanks
— 
- Let’s connect on LinkedIn <https://www.linkedin.com/in/danispringer/>
- New music coming June 1. Ready to wake up? Follow <https://open.spotify.com/artist/6wp28GMW9iypStW4pCsCN9> me to get notified.

**Comment by tagliala** [comment]
Hi, thanks got it.

This is not an issue with FA

`<a>` tags have the default display property set to `inline`. Since you are inserting a font awesome icon with a `display: inline-block` inside an anchor tag, you should edit your `a` tags accordingly.

https://jsfiddle.net/tagliala/6yrybgho/7/

Please note that I do not recommend to set this rule, it is just an example.

```
a {
  display: inline-block;
}
```

You should go for a css class such as `.button` with display property set as `inline-block` and add that class to your button links

Hope it helps, closing here
