### ISSUE TITLE
Icon Request: Kodery

### ISSUE THREAD

**Issue by PaulAdamDavis** [FortAwesome/Font-Awesome#1324]
Bit of a self-involved request, but there's a service me & a friend and working on that should get a lot of use from devs.

Service is http://kodery.com, icon is: [this](https://f.cloud.github.com/assets/390392/659287/176ef708-d67e-11e2-946d-e8b751b20a79.png)
I have .ai files too if that's any help?

Use cases could be anything from a link to their snippets on the service, to custom styling of the embed code on a blog or something.

**Comment by aethior** [comment]
Kodery.com seems shut down currently. (check [domain](http://kodery.com/) and [social networks](https://twitter.com/kodery))

cc/ @tagliala
