### ISSUE TITLE
Icon jogging

### ISSUE THREAD

**Issue by otoman** [FortAwesome/Font-Awesome#13245]
Please add icon for jogging

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1156 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by otoman** [comment]
Oh sorry for duplicate :)
