### ISSUE TITLE
is project dead?

### ISSUE THREAD

**Issue by hsiboy** [FortAwesome/Font-Awesome#13241]
Is this project still maintained??

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, it definitely is.

Please take a look at the releases page: https://github.com/FortAwesome/Font-Awesome/releases

FA 5.0.13 has been released 20 days ago and we have a pre-release version of the upcoming 5.1

Hope it helps

Closing here

**Comment by hsiboy** [comment]
👍
