### ISSUE TITLE
Icon request: fa-brain

### ISSUE THREAD

**Issue by gatekeeperapps** [FortAwesome/Font-Awesome#13259]
we are the digital support team for an Australian brain cancer charity. we would love to integrate a font awesome brain icon into the charity's website. your consideration to create a brain icon would be greatly appreciated. 2 styles solid and outline

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2075 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
