### ISSUE TITLE
References to URLs are not working over https.

### ISSUE THREAD

**Issue by jarrettj** [FortAwesome/Font-Awesome#13269]
Hi,

Good day.

### Describe the problem
Loading the fontawesome css over https is a problem. All external references in the file, like below:
```
url('../fonts/fontawesome-webfont.woff2?v=4.7.0')
```
are not fetched over https causing a mixed content error. Is there anyway to get around this? 
### What version and implementation are you using?
fontawesome 4.7
Fails on all browsers.

### Reproducible test case
Using Apache web server, and I do redirect all requests from http to https. Using the redirect module in my virtual host file and I tried using a .htaccess as well.

Thanks.

Regards.
JJ

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA4 is in EOL, please consider upgrading to FA5.

It seems that your server is not properly configured. Please double check your server configuration and CSP. Troubleshooting guide could also be useful: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

As you can see here, I'm using a self-hosted version of FA 4.7.0 over https: https://ruby2-rails4-bootstrap-heroku.herokuapp.com/

Hope it helps

Closing here

**Comment by jarrettj** [comment]
Thanks for the help man! Much appreciated! 

In the example I can see in your source that your url() is different to mine:
```
url(/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot)
```
My references to urls seem to be relative. That might be the issue. Will check bower packages and update.

Regards.
JJ

**Comment by tagliala** [comment]
They are different because I'm using the asset pipeline of Ruby on Rails, so I had to change a couple of lines in the FA css and I also removed the version string (unneded with a fingerprint)

I think that urls are not causing the issue in your specific case, you should check something else
