### ISSUE TITLE
The page is not found while loading cdn url. https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css. 

### ISSUE THREAD

**Issue by solution7** [FortAwesome/Font-Awesome#13262]
20 / 100 times, on doing cache refresh. The page is not being able to be fetched. Also, after hitting url, I need to refresh the page twice to get the content back again.
![fontawesome-cdn](https://user-images.githubusercontent.com/5971373/40873729-c70cb336-6683-11e8-9341-39b2da6b195c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate. I'm in Italy, maybe a temporary issue in your country

Please open an issue at bootstrapcdn: https://github.com/MaxCDN/bootstrapcdn/issues

Closing here

**Comment by solution7** [comment]
Ok
