### ISSUE TITLE
Hi, How soon will Font-Awesome 5 be released?

### ISSUE THREAD

**Issue by inglesuniversal** [FortAwesome/Font-Awesome#13264]
Your Website Video mentions $20 bucks the Pro for early adopters, How does that work?

Is the fact that including my Own company Logo is in deed part of the Package above?

Best regards,

Hugo Barbosa

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> How soon will Font-Awesome 5 be released? 

FA5 has already been released! Get it at https://fontawesome.com/

> Your Website Video mentions $20 bucks the Pro for early adopters, How does that work?

If you are a Font Awesome Pro backer, you should be able to login at fontawesome.com and get FA5 Pro.

If you cannot login at our website, I'm sorry but at the moment I can't remember the how to steps to log in. please send an email to hello@fontawesome.com

If you didn't get answers or you are not able to login, please comment here and I will reopen

> Is the fact that including my Own company Logo is in deed part of the Package above?

Nope. https://www.kickstarter.com/projects/232193852/font-awesome-5

Hope it helps

Closing here
