### ISSUE TITLE
Icon request: icon-remove-formating

### ISSUE THREAD

**Issue by kolkov** [FortAwesome/Font-Awesome#13276]
Request for new icon: remove-formating
Something like this:
![image](https://user-images.githubusercontent.com/3740898/40968438-358c9e98-68be-11e8-8a52-6dc5972225f3.png)
https://www.onlinewebfonts.com/icon/2175

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/remove-format?style=solid
