### ISSUE TITLE
Icon Request: fa-solar-system

### ISSUE THREAD

**Issue by rwampler** [FortAwesome/Font-Awesome#13279]
hi,

thank you very much for all your effort on this project, it has made my life much easier!

i was hoping you'd be able to add an icon similar to this one, representing something like "planets in a solar system"

![fa-solar-system](https://user-images.githubusercontent.com/13138481/40992351-695596de-68ab-11e8-834f-99e8872f5a96.png)

if added, i'd like to use this icon for with an open-source economic simulation / mmo city building game. i think icon would otherwise thematically fit well with the existing astronaut, space-shuttle and rocket icons

thank you for considering!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/solar-system?style=duotone
