### ISSUE TITLE
Icon Request: fa-google-plus

### ISSUE THREAD

**Issue by mdmuhib** [FortAwesome/Font-Awesome#13270]

**Comment by mdmuhib** [comment]
i want to different google + icon  like this 
<i class="fa fa-google-plus" aria-hidden="true"></i>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> i want to different google + icon like this

Can't see the the example

The official Google Plus logo with the uppercase G is the one that is implemented on font awesome.

- https://fontawesome.com/icons/google-plus-square?style=brands
- https://fontawesome.com/icons/google-plus-g?style=brands
- https://fontawesome.com/icons/google-plus?style=brands

If you want the old logo, please consider a custom build https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps

Closing here
