### ISSUE TITLE
Icon request: surgery (scalpel with dotted line)

### ISSUE THREAD

**Issue by edelmeier** [FortAwesome/Font-Awesome#13288]
### What can it be used for?
Would be great to have a general surgery icon for various medical topics

### Example image 
![image](https://user-images.githubusercontent.com/1701392/41082444-a9e213e2-6a2e-11e8-9a72-e37a50915cb4.png)

Credit for sample: https://thenounproject.com/term/surgery/1523349/

**Comment by tagliala** [comment]
Hi, this icon is available in FA 5.2.0 Pro

https://fontawesome.com/icons/scalpel-path?style=solid

**Comment by edelmeier** [comment]
Thanks, great work!
