### ISSUE TITLE
icons don't display on my localhost wordpress? 

### ISSUE THREAD

**Issue by myuval** [FortAwesome/Font-Awesome#13281]
Hi, I am creating a new website on my localhost using wordpress Medicalpress template. 
The template offers me the option of using icons from FontAwesome. 
However, I've tried a few icons using the <i class="">.. </i> as in the example, but the icons didn't load. 
What should I do to solve that? 
Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The template offers me the option of using icons from FontAwesome.

Sorry but we do not provide support for third party themes or plugins. Please check your theme's documentation or contact the author.

If you want to add Font Awesome to your theme by yourself and you have basic WordPress knowledge, take a look at our documentation: https://fontawesome.com/get-started/svg-with-js

Hope it helps

Closing here
