### ISSUE TITLE
Icon request: user-unlock

### ISSUE THREAD

**Issue by jrsquared** [FortAwesome/Font-Awesome#13280]
### What can it be used for?

Just like user-lock, but with an unlocked lock

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Added this in 5.12.1: https://fontawesome.com/icons/user-unlock?style=duotone
