### ISSUE TITLE
fas fa-divide

### ISSUE THREAD

**Issue by rowejs** [FortAwesome/Font-Awesome#13285]
Hi

<i class="fas fa-divide"></i> isn't appearing on my website (I'm getting the animated question mark, exclamation mark symbol). <i class='fas fa-times'></i> works fine.

Thanks, James

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

fa-divide has been added in FA 5.0.13. Please make sure you are using FA >= 5.0.13

Hope it helps

Closing here

**Comment by rowejs** [comment]
Thank you that worked great!
