### ISSUE TITLE
Chart names

### ISSUE THREAD

**Issue by GregFrench** [FortAwesome/Font-Awesome#13297]
I couldn't figure out why all the chart icons wouldn't load. In the docs it lists the icon names for charts being for example "fa-line-chart" so I checked the code using version 5.0.13 and in the code the actual name is "fa-chart-line". This seems to be a problem for all the chart names. Just a heads up.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> In the docs it lists the icon names for charts being for example "fa-line-chart"

Where?

`fa-chart-line` in FA5, as per [docs](https://fontawesome.com/icons/chart-line?style=solid), "replaces Font Awesome 4's fa-line-chart"

**Comment by GregFrench** [comment]
Ah my bad. I was on the 4.7 docs: https://fontawesome.com/v4.7.0/icon/line-chart/ . Thanks!
