### ISSUE TITLE
Icon request: icon-factory

### ISSUE THREAD

**Issue by Elicitation** [FortAwesome/Font-Awesome#1330]
Need an icon to illustrate when something is made at factory rather than made by hand.

**Comment by cagrigurbuz** [comment]
+1

**Comment by JosepMartins** [comment]
:+1:

**Comment by JHarbourne** [comment]
+1 = factory, warehouse

**Comment by mraak** [comment]
+1

**Comment by juampi** [comment]
+1

**Comment by csharbel** [comment]
+1

**Comment by olyos** [comment]
+1 :)

**Comment by ghazispeakserve** [comment]
+1

**Comment by patrik2991** [comment]
+1

**Comment by marcnicholas** [comment]
+1

**Comment by gencebay** [comment]
+1

**Comment by luckynrslevin** [comment]
+1

**Comment by underfrog** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by 247Chon** [comment]
+1 but without clouds please :-)

**Comment by GwenLoguir** [comment]
+1

**Comment by fballiano** [comment]
+1

**Comment by manicko** [comment]
+1

**Comment by sl45sms** [comment]
+1

**Comment by NickolasAcosta** [comment]
+1

**Comment by creative-eye** [comment]
+1

**Comment by jacksonwj** [comment]
+1
Like this 
![factory](https://cloud.githubusercontent.com/assets/61455/7514537/cd51f09c-f4f0-11e4-994f-f9f65ac27c2d.png)

**Comment by Sivalingaamorthy** [comment]
+1

**Comment by athirah30** [comment]
+1

**Comment by tmo256** [comment]
+1

**Comment by liptonbeer** [comment]
+1

**Comment by bjornte** [comment]
+1

**Comment by edpichler** [comment]
+1

**Comment by hellsing71** [comment]
+1

**Comment by rbenech** [comment]
+1

**Comment by CoDEmanX** [comment]
![factory-alternative](https://cloud.githubusercontent.com/assets/1309249/8861125/afe990da-3188-11e5-84f2-4193e62d388c.png)
![factory-alternative2](https://cloud.githubusercontent.com/assets/1309249/8861303/ea68112c-3189-11e5-9072-d8638f416050.png)

**Comment by DUznanski** [comment]
+1

**Comment by tagliala** [comment]
Added in 4.4.0!

Closing here

**Comment by vuongtran** [comment]
+1

**Comment by wald-tq** [comment]
@vuongtran good news, it has been added in version 4.4.0: http://fontawesome.io/icon/industry/

**Comment by dezio** [comment]
+1

**Comment by tagliala** [comment]
locking here 🔒 

The icon is already in the set: http://fontawesome.io/icon/industry/
