### ISSUE TITLE
Icons disappear after turbolinks page change (webpack FA js)

### ISSUE THREAD

**Issue by tillcarlos** [FortAwesome/Font-Awesome#13304]
Hey community,

I haven't found this issue online yet, so here we go:

1. Page loads (or refresh): icons get displayed.
2. Click to a turbolinks link, back and forth, to the same page: icons **appear for a fraction of a second, then disappear**.

Here is a [quick screencast](https://monosnap.com/file/5yD1nAzdTzpktMXH0rqfsPTLgt4cS4) quick screencast of how it looks like.

My Stack:

- Rails 5.2 (fwiw)
- Webpack 4.12.0
- Including FA5 in a js pack

```
import Turbolinks from 'turbolinks';
Turbolinks.start();
import faClipboard from '@fortawesome/fontawesome-free-solid/faClipboard'
fontawesome.library.add(faClipboard)
```

My versions (package.json):

```
"@fortawesome/fontawesome": "^1.1.8",
"@fortawesome/fontawesome-free-solid": "^5.0.13",
```

Thanks for everything - awesome work!!

EDIT: I observed the html tag. It goes to pending, then `fontawesome-i2svg-active fontawesome-i2svg-complete`, and then stays there after turbolinks change. I guess that's the desired behaviour.

EDIT 2: I also tried `FontAwesome.dom.i2svg();` after `turbolinks:load` event - with no change

**Comment by tillcarlos** [comment]
Sorry for this to turn into a live debugging session. It seems to be caused by Vue. When I comment Vue loading out the icons appear. I'm testing possible solutions now.

**Comment by tillcarlos** [comment]
Okay, solved! The solution was to move the command AFTER the Vue statements. For anyone interested - this is the final code:

document.addEventListener('turbolinks:load', () => {
  
```
  // This code will setup headers of X-CSRF-Token that it grabs from rails generated token in meta tag.
  if (document.querySelector('meta[name="csrf-token"]')) { 
  const app = new Vue({
    el: '[data-behavior="vue"]',
  })
  FontAwesome.dom.i2svg();
})
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are currently issues with turbolinks, please check #12709
