### ISSUE TITLE
Icon Request: fa-sap

### ISSUE THREAD

**Issue by larenius1** [FortAwesome/Font-Awesome#13314]
I need a sap good looking logo, for a function within my application. would be font-awsome :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4882, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
