### ISSUE TITLE
Icon Request: fa-pivotal

### ISSUE THREAD

**Issue by Discostewart** [FortAwesome/Font-Awesome#13313]
https://a.slack-edge.com/ae7f/img/services/pivotaltracker_512.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
