### ISSUE TITLE
Icon Request: fa-redmine

### ISSUE THREAD

**Issue by Discostewart** [FortAwesome/Font-Awesome#13312]
http://www.redmine.org/projects/redmine/wiki/Logo

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1787, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
