### ISSUE TITLE
Icon Request: icon-new

### ISSUE THREAD

**Issue by realtebo** [FortAwesome/Font-Awesome#1331]
I'd like an icon able to transmit the idea of something 'new'. 

We'd like to use when releasing new feature in our software to catch user attention on new menu, new link or on sidebar tooltip when related to news feature.

I hate the classic yellow star with the word  "new" red colored on top

Sorry, but I've no idea of how to create this icon, it's litterally a request...

**Comment by AntonioMalatesta** [comment]
+1
![new](https://cloud.githubusercontent.com/assets/11273091/6623684/bcbd1dac-c8e4-11e4-8687-b79e1bdce7dc.png)

**Comment by PeterShaggyNoble** [comment]
If it helps any, Google have 2 icons to highlight new items:
https://design.google.com/icons/#ic_fiber_new
https://design.google.com/icons/#ic_new_releases

**Comment by densenator** [comment]
+1

**Comment by viggyprabhu** [comment]
+1

**Comment by alexsxx** [comment]
+1

**Comment by matejjurancic** [comment]
+1
