### ISSUE TITLE
fa-book-open not rendering

### ISSUE THREAD

**Issue by justlikeUNIBLAB** [FortAwesome/Font-Awesome#13315]
Hi 
Font-Awesome is awesome.

We're using https://use.fontawesome.com/releases/v5.0.10/js/all.js"
I'm on Windows 10, working in Chrome.

I'm using a number of icons successfully via React, but this one isn't rendering:

<span className="fas fa-book-open"></span>
https://fontawesome.com/icons/book-open?style=solid

If I switch the class to another icon, the same line of code renders perfectly (with the other icon).

Thanks
Josh

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[book open](https://fontawesome.com/icons/book-open?style=solid) has been introduced in FA 5.0.13 and you are using FA 5.0.10

Please update

Hope it helps

Closing here
