### ISSUE TITLE
Icon request: Teamspeak update

### ISSUE THREAD

**Issue by andreacw5** [FortAwesome/Font-Awesome#13328]
Teamspeak change is logo with a new one, I'm here to ask an update to `fa-teamspeak` icon with his new logo.

Teamspeak Web site: [https://www.teamspeak.com/en/](https://www.teamspeak.com/en/)

New svg icon: [https://www.teamspeak.com/assets/images/TeamSpeakSmirk-dark.svg](https://www.teamspeak.com/assets/images/TeamSpeakSmirk-dark.svg)

**Comment by Pandraghon** [comment]
So here we go again... :+1:

**Comment by talbs** [comment]
@andreacw5 and @Pandraghon, I got you folks on this one! We'll get this updated and into the next release which is coming very soon. 😄

**Comment by tagliala** [comment]
Available in 5.1.0

https://fontawesome.com/icons/teamspeak?style=brands
