### ISSUE TITLE
Icon request: square-root

### ISSUE THREAD

**Issue by SorenSaket** [FortAwesome/Font-Awesome#13335]
### What can it be used for?

There's already  superscript that can be used to set things in power of. Would be nice also to have a square/cubic/custom root icon.
I feel fontawesome is lacking a lot of other mathematical expression, but this is one of the more crucial ones.

### Example image (optional)

![root](https://user-images.githubusercontent.com/14962061/41508409-c91f36e0-7244-11e8-9150-e284796c01f4.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/square-root?style=solid
https://fontawesome.com/icons/square-root-alt?style=solid
