### ISSUE TITLE
Solid Tshirt icon

### ISSUE THREAD

**Issue by wgreen02** [FortAwesome/Font-Awesome#13339]
The solid Tshirt icon does not render on my website.  I'm using the following in a span:

"fas fa-tshirt"

All other icons seem to be working fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[tshirt](https://fontawesome.com/icons/tshirt?style=solid) has been introduced in version 5.0.13. Please make sure you are using FA >= 5.0.13

Hope it helps

Closing here
