### ISSUE TITLE
Minor addition - add categories.json next to categories.yml

### ISSUE THREAD

**Issue by kvnvandenbrande** [FortAwesome/Font-Awesome#13344]
https://github.com/FortAwesome/Font-Awesome/tree/master/advanced-options/metadata

Is it possible to add a categories.json next to the yml file? Just like it's done with the other files.

**Comment by tagliala** [comment]
Seems legit

**Comment by robmadole** [comment]
The JSON files are build artifacts from our system. The YML files are source files that power all the rest of the machinery. We aren't going to produce a JSON file version of each YML. Sorry @kvnvandenbrande .

**Comment by kvnvandenbrande** [comment]
@robmadole sad to hear. 

I do want to clarify the reason for it that I had in mind. If only icons / shims / categories are all available as json files, they can be used to easily import it in any database structure. JSON is a supported syntax in many different database applications. YML is sad fully not, they need to be parsed out with external tools or converted before using them.

When importing the JSON files you have a full list of all the available icons, including all the categories. A database can then be build to display a list all available icons just like it's done on the following page: https://fontawesome.com/icons?d=gallery

You maybe think, why in earth you want to build a tool that maps the search capabilities like it is on the website and not use it in the website itself? Well the reason is that the SVG files that you download from the website are for some database application not compatible. The reason is that they are missing a width and height parameter in the svg tag. With the build database tool this can be for seen and a user can add it directly as SVG to the database application. 

Another note: our company has bought a pro license. The pro icons can not be downloading directly as SVG from the website. You need to have access to the project itself and browse in the correct directory in order to find the specified icon as SVG file. Off course the pro project can only be accessed by a limited amount of people. With the build database file (for internal use) it can be used by all employees in an easy manner. Even those with no knowledge of github or whatsoever. When all three json files that I listed above exist a script could be made that updates the database without manually interfering.
