### ISSUE TITLE
Some icons not showing

### ISSUE THREAD

**Issue by ebatgerel** [FortAwesome/Font-Awesome#13348]
I used these icons
`<i class="fas fa-chalkboard-teacher"></i>` 
`<i class="fas fa-user-check"></i>`
`<i class="fas fa-hands"></i>`

 But its not rendering

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[chalkboard-teacher](https://fontawesome.com/icons/chalkboard-teacher?style=solid) has been introduced in FA 5.0.13
[user-check](https://fontawesome.com/icons/user-check?style=solid) has been introduced in FA 5.0.11
[hands](https://fontawesome.com/icons/hands?style=solid) has been introduced in FA 5.0.9

If you want to use all the above icons, please make sure you are using FA >= 5.0.13

If you still think there is an issue with Font Awesome, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
