### ISSUE TITLE
Github icon syntax error

### ISSUE THREAD

**Issue by adhi1234** [FortAwesome/Font-Awesome#13340]
There is an error in syntax of `<i class="fab fa-github"></i>` 

**How could it be rectified**
Change the code to `<i class="fa fa-github"></i>`

![bug](https://user-images.githubusercontent.com/11091122/41587968-181fe232-73ce-11e8-8fe8-10827d31fa91.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That is not a typo.

If it doesn't work in your application, you are probably using Font Awesome 4

Ref: https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Hope it helps

Closing here
