### ISSUE TITLE
Icon Request : fa-mirakee

### ISSUE THREAD

**Issue by Jaypatelbond** [FortAwesome/Font-Awesome#13347]
**What can it be used for?
Would be great if we can just used in our site to link to the writers paradise**

[Mirakee: A writers paradise](http://www.mirakee.com/)
![Mirakee](https://user-images.githubusercontent.com/29830677/41642334-9bd39fe4-7485-11e8-8ec0-e4a74ad56ff4.jpg)

**Comment by Jaypatelbond** [comment]
@tagliala you adding this as a brand icon?

**Comment by tagliala** [comment]
@Jaypatelbond nope, I'm just labeling this issue. It will follow request's lifecycle as any other request

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
