### ISSUE TITLE
Get a list of icon with CDN

### ISSUE THREAD

**Issue by iOiurson** [FortAwesome/Font-Awesome#13356]
When using FontAwesome CDN, is it possible to list all available icons of a CSS file (say, `solid.css` for instance) ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Afaik, that is not possible.

If you need to parse and list icons, you have some options here: https://github.com/FortAwesome/Font-Awesome/tree/master/advanced-options/metadata

Hope it helps

Closing here
