### ISSUE TITLE
"Connection is not secure" error on https site. FA xmlns="http://....  Is this the issue?

### ISSUE THREAD

**Issue by NJWebDesign** [FortAwesome/Font-Awesome#13351]
I have a problem whereby a website we've developed is producing a "Connection is not secure" error despite having a valid SSL certificate installed:
https://www.waterfronthotel.co.uk

I've been through the code with a fine toothed comb and the only non-https reference I can find is with the Font Awesome icons which are pulling in from xmlns="http://www.w3.org/2000/svg", for example...

<svg class="svg-inline--fa fa-envelope fa-w-16" aria-hidden="true" data-prefix="fal" data-icon="envelope" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M464 64H48C21.5 64 0 85.5 0 112v288c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48zM48 96h416c8.8 0 16 7.2 16 16v41.4c-21.9 18.5-53.2 44-150.6 121.3-16.9 13.4-50.2 45.7-73.4 45.3-23.2.4-56.6-31.9-73.4-45.3C85.2 197.4 53.9 171.9 32 153.4V112c0-8.8 7.2-16 16-16zm416 320H48c-8.8 0-16-7.2-16-16V195c22.8 18.7 58.8 47.6 130.7 104.7 20.5 16.4 56.7 52.5 93.3 52.3 36.4.3 72.3-35.5 93.3-52.3 71.9-57.1 107.9-86 130.7-104.7v205c0 8.8-7.2 16-16 16z"></path></svg>

Is this what's causing the issue?  It strikes me that I can do nothing about it unless a fix is issued.
Would appreciate any help offered.
Thank you.
NJ

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that this is not the issue.

I can see the following in the console:

```
Mixed Content: The page at 'https://www.waterfronthotel.co.uk/' was loaded over HTTPS, but requested an insecure image 'http://www.google.com/mapfiles/marker.png'. This content should also be served over HTTPS.
```

If you think there is still an issue with Font Awesome, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

Closing here

**Comment by NJWebDesign** [comment]
Hi tagliala.  I've fixed the issue with http://www.google.com/mapfiles/marker.png and the error remains so if you could keep this open?  Thank you.

**Comment by tagliala** [comment]
@NJWebDesign sorry but I cannot replicate your issue.

![image](https://user-images.githubusercontent.com/556268/41659804-9b8ac44e-749a-11e8-85ba-6669fbbe0886.png)

Please provide all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by NJWebDesign** [comment]
Sorry tagliala, I missed an additional reference to marker.png.  Sorted now. Thank you.
