### ISSUE TITLE
Icon request: steemit

### ISSUE THREAD

**Issue by hardikitalia** [FortAwesome/Font-Awesome#13357]
What can it be used for?
add this icon
steemit
[https://steemit.com/](url)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10703, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
