### ISSUE TITLE
Fontawesome 5.1.0 grin-wink regular is solid

### ISSUE THREAD

**Issue by designchapnl** [FortAwesome/Font-Awesome#13361]
Grin-wink regular is displayed as a solid icon

https://fontawesome.com/icons/grin-wink?style=regular

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

**Comment by talbs** [comment]
D'oh! We hate it when that happens. I'll get this fixed up and in a small release shortly. Thanks for letting us know, @designchapnl. 😄

**Comment by mikejf-pr** [comment]
Hey, just so I can schedule something, do you have a release date planned on that bugfix release?

**Comment by talbs** [comment]
@mikejf-pr, this should be coming out in version `5.1.1` either today or at the latest tomorrow. We're packing the mini-van now. 😄

**Comment by MeyaHoule** [comment]
Favourite Emoji Day!

**Comment by tagliala** [comment]
Seems fixed to me
