### ISSUE TITLE
Request icon: log file

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13369]
Example:
![28811](https://user-images.githubusercontent.com/280586/41741719-31c14832-759c-11e8-8239-c046f20e0c11.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment those requests are out of scope.

Please take advantage of stacking and layering features to implement them.

SVG: https://fontawesome.com/how-to-use/on-the-web/styling/layering
CSS: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Hope it helps

closing here
