### ISSUE TITLE
SVG Icons Not Working

### ISSUE THREAD

**Issue by chadsaun** [FortAwesome/Font-Awesome#13365]
I followed the instructions for v5.1.0 and included the `<script defer src="/your-path-to-fontawesome/js/all.js"></script>` in the head, and Chrome is loading it successfully, but then in Chrome Dev Tools under Networking it shows it failed to load `blob:http://localhost:8000/8171dd2a-8d79-4ae9-b398-9b5819d1f13e`.

My icons aren't showing and I'm thinking that `all.js` is trying to load the `blob`? Did I miss another step in using SVG icons?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by chadsaun** [comment]
### Describe the problem

I followed the instructions to get started using "Using SVG with JavaScript" and the icons didn't show up. Dev Tools in Chrome shows that `all.js` is loading successfully. But right after that I also see that it failed to load `blob:http://localhost:8000/8171dd2a-8d79-4ae9-b398-9b5819d1f13e`

### What did you expect?

The icons to show up on my page

### What version and implementation are you using?

Version: 5.0.1
Browser and version: Chrome 67.0.3396.87

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

I can't really use Codepen or the like since I'm hosting the files locally.

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
> blob:http://localhost:8000/8171dd2a-8d79-4ae9-b398-9b5819d1f13e

I'm pretty confident that the above error is not related to font awesome

Sorry, but without a reproducible test case we cannot help. Try to deploy your project on a public website

**Comment by chadsaun** [comment]
So the blob thing was actually from Adblock plugin.

I just saw that it is actually working. The icons were just the same color as the background 😬
