### ISSUE TITLE
5.1: documentation references unexisting plane-departing and plane-arriving icon

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#13364]
The links under "Travel Category Pack" as listed [here](https://fontawesome.com/changelog/latest) link to "plane-departing" and "plane-arriving" instead of "plane-departure" and "plane-arrival".

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

**Comment by talbs** [comment]
D'oh! Thanks for the heads up, @Studio384. We'll get that sorted right away.

**Comment by talbs** [comment]
Following up - this was fixed on fontawesome.com shortly after this issue was created. We've released 5.2 and the changelog view has since been updated. I'm closing this with all of that in mind. Thanks again for bringing this to our attention.
