### ISSUE TITLE
Icon request: icon-flag-usa

### ISSUE THREAD

**Issue by tvanprooyen** [FortAwesome/Font-Awesome#1336]
Just noticed this wasn't in the icons, it's a good suggestion to have in there
![usflag](https://f.cloud.github.com/assets/4705130/665398/f26344b2-d79c-11e2-8cab-b232827c33ad.jpg)

**Comment by nicolasbeauvais** [comment]
I got the same issue than @matbhz  where I just needed french / us flag.

**Comment by tagliala** [comment]
Please consider svg based solutions, like http://lipis.github.io/flag-icon-css/

**Comment by MOUNIKUMARMATHEY** [comment]
> I don't think it's good idea to include flags in black&white icons. Lots of country flags have the same shape, the only difference is in their colours (eg. France, Italy, ...)

Yes that's true.

**Comment by mapsmarketing** [comment]
So, `flag-usa` exists, but where are the rest? I'd like to use a UK flag which has an obviously different shape... @tagliala 

<img width="329" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/79551469/53b64ea9-e8bb-4350-9a24-0cc5555203d2">
