### ISSUE TITLE
Missing icons in Pro version 5.1.0

### ISSUE THREAD

**Issue by WeAreELIC** [FortAwesome/Font-Awesome#13360]
I just included the latest Pro 5.1.0 release in my web project, using NPM, and it seems some fonts are missing like "donate" and "hands-usd" in the JS versions. I tested "envelope" and "fax" and they worked fine, but haven't tested any others. I tested all.js and the individual js versions.

*Update: I just confirmed that downloading the JS files manually and including them works...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by WeAreELIC** [comment]
Will do, sorry about that.
