### ISSUE TITLE
5.1: fa-kiss regular and light are switched

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#13363]
As can be seen here: https://fontawesome.com/icons/kiss?style=light. The light style is the regular icon and the regular style is the light icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

**Comment by talbs** [comment]
D'oh! We hate it when that happens. I'll get this fixed up and in a small release shortly. Thanks for letting us know, @Studio384. 😄

**Comment by talbs** [comment]
The light and regular styles of `fa-kiss` should now be behaving themselves. Check out https://fontawesome.com/icons/kiss?style=regular and https://fontawesome.com/icons/kiss?style=light.

Thanks for helping us get this fix in. 😄
