### ISSUE TITLE
Icon Request: Alternate ADN icon

### ISSUE THREAD

**Issue by joeworkman** [FortAwesome/Font-Awesome#1337]
The new ADN icon (icon-adn) that was added in v3.2 does not follow the same scheme as other popular networks such as Facebook and Twitter. For both Facebook and Twitter, there is an alternate _sign_ icon that renders the icon in a shape. Its odd that icon-adn is not simply the A with an alternate similar to the other networks.

**Comment by tagliala** [comment]
Closing here because of ADN's shutdown https://en.wikipedia.org/wiki/App.net
