### ISSUE TITLE
Request icon: biological-virus

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13373]
Example:
![virus](https://user-images.githubusercontent.com/280586/41742070-35addd06-759d-11e8-894c-03f5629247a5.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does [bug](https://fontawesome.com/icons/bug?style=solid) fit your use case?

**Comment by dtouzeau** [comment]
No, if you want to illustrate a log file, you can have lines for bugs and viruses.
The icon is real a bug icon, a malware is not the same.

**Comment by tagliala** [comment]
So this is going to represent a *biological* virus

**Comment by sensibleworld** [comment]
We have a few options now: https://fontawesome.com/icons?d=gallery&q=virus

**Comment by bhsjacket** [comment]
Very timely ;)
