### ISSUE TITLE
Request icon: Certificate file

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13374]
example:
![28805](https://user-images.githubusercontent.com/280586/41742129-5b584eb0-759d-11e8-936a-9b33cdff0dc8.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment those requests are out of scope.

Please take advantage of stacking and layering features to implement them.

SVG: https://fontawesome.com/how-to-use/svg-with-js#layering
CSS: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Hope it helps

closing here
