### ISSUE TITLE
Request icon: Mail server

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13370]
Example:

![32261](https://user-images.githubusercontent.com/280586/41741780-508e09e4-759c-11e8-8069-a7cf5fa3c135.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is legit, but please keep in mind that you can obtain it with masking and layering: https://jsfiddle.net/tagliala/8oqL3b5p/271/

https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons
https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by dtouzeau** [comment]
Thanks, but sometimes there are a bug, when refreshing only the square is chown.
More simple if it is added in collection.
Closing the ticket
