### ISSUE TITLE
Old Houzz Logo

### ISSUE THREAD

**Issue by pikapumpkin** [FortAwesome/Font-Awesome#13379]
Houzz recently changed their logo & I was hoping you guys could update yours!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[houzz logo](https://fontawesome.com/icons/houzz?style=brands) has been changed in 5.0.9.

Maybe you are using an older version of Font Awesome?

Hope it helps

Closing here
