### ISSUE TITLE
Request icon: Backup file

### ISSUE THREAD

**Issue by dtouzeau** [FortAwesome/Font-Awesome#13375]
![29589](https://user-images.githubusercontent.com/280586/41742157-78572248-759d-11e8-894e-fb21636103f6.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment those requests are out of scope.

Please take advantage of stacking and layering features to implement them.

SVG: https://fontawesome.com/how-to-use/on-the-web/styling/layering
CSS: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Hope it helps

closing here
