### ISSUE TITLE
China mainland currency icon wrong.

### ISSUE THREAD

**Issue by muzuiget** [FortAwesome/Font-Awesome#1338]
I notice in version 3.2 font-awesome add some currency icons. But I think the China mainland is not right.

References to the wiki [Renminbi](http://en.wikipedia.org/wiki/Renminbi), it use the same sign [¥](http://en.wikipedia.org/wiki/%C2%A5) as the one Japan used.  

Because the icon normally put in front of the number, for example, we use `¥ 1.23` or `1.23 元`, or even `¥ 1.23 元`, but not use `元 1.23` and `元 1.23 元`, so don't need to make a "元" Chinese charactert icon.

So, just alias "icon-cny' to "icon-jpy". 

Also, "RenMinBi" standard abbreviation is ”RMB“, Chinese developers know this. So "icon-renminbi" can rename to "icon-rmb", and alias to "icon-jpy" too.

**Comment by wangxiaoweishy** [comment]
cyn != ypy, and certainly can not be an ailas of jpy, althought their icons are almost the same. This is a question of respect for Chinese!

**Comment by wangxiaoweishy** [comment]
cyn != ypy, and certainly can not be an ailas of jpy, although their icons are almost the same. This is a question of respect for Chinese!

**Comment by wangxiaoweishy** [comment]
cny != jpy, and certainly can not be an ailas of jpy, although their icons are almost the same. This is a question of respect for Chinese!

**Comment by chromafunk** [comment]
first of all, it's true that that initially placed symbol is wrong. And secondly, both japanese and chinese are extremely nationalist and they both deserve a differentiation if you don't want a war here. just add the damn fa-fa-cny and be done with it.
