### ISSUE TITLE
Searching for "json" in the icon search returns the person-carry/dolly icons?

### ISSUE THREAD

**Issue by dflock** [FortAwesome/Font-Awesome#13382]
### Describe the problem

If you [search for "json" in the icon search, it returns the person-carry/dolly icons](https://fontawesome.com/icons?d=gallery&q=json)?

![image](https://user-images.githubusercontent.com/47756/41752999-b5f296dc-757f-11e8-9cf2-aaffd0bb8be5.png)

### What did you expect?

I was looking for a json icon of some kind, but I don't think there are any, so I'd probably expect no results.

### What version and implementation are you using?

The FontAwesome website.

### Reproducible test case

n/a

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [na] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [na] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that json is near to `rson` in pe**rson**

@talbs could you please confirm?

**Comment by dflock** [comment]
Searching for `son` gets you the same results, so I guess that explains it. Thanks.
