### ISSUE TITLE
grip-horizontal & grip-vertical

### ISSUE THREAD

**Issue by theshelf** [FortAwesome/Font-Awesome#13381]
This is based on the fact that ellipsis has h/v instead of horizontal/vertical and also 2 styles of dot.

Changes suggested:
1. grip-horizontal renamed grip-h-alt
2. grip-vertical renamed grip-v-alt
3. grip-h added - 2 rows of ellipsis-h
4. grip-v added - 2 cols of ellipsis-v

**Comment by talbs** [comment]
Thanks for the heads up and suggestion. @sensibleworld what do you think we should do icon naming-wise?

**Comment by theshelf** [comment]
It doesn't need to be a breaking change immediately, could have an alias. Although these would be the first for FA5?

**Comment by sensibleworld** [comment]
Sorry for missing this! I think updating the naming to `-h` and `-v` makes sense.

**Comment by leeyeh** [comment]
Any update on this topic? It will be great to have a solid dot styled grip-vertical/grip-horizontal for the regular and light style (just like ellipsis).

**Comment by tagliala** [comment]
I think this has been addressed in `v6`

|FA5|FA6|
|--|--|
|grip-horizontal|grip|
|grip-vertical|grip-vertical|
|ellipsis-horizontal|ellipsis|
|ellipsis-vertical|ellipsis-vertical|

**Comment by sensibleworld** [comment]
Yup! We've got some updates available in the latest alpha: https://fontawesome.com/download

<img width="600" alt="Screen Shot 2021-01-04 at 9 23 25 AM" src="https://user-images.githubusercontent.com/529604/103544705-80405180-4e6e-11eb-8f85-7b73ad87c958.png">
