### ISSUE TITLE
Some icons missing from npm package 5.1.0-4

### ISSUE THREAD

**Issue by brian-hay** [FortAwesome/Font-Awesome#13380]
In my project I've just switched from the manually downloaded FA Pro 5.0.13 to the latest npm package FA Pro 5.1.0-4 and a number of icons have gone missing. I've confirmed they're not in _icons.scss

There maybe more missing but these are ones I've been using that have gone AWOL:

- fal fa-book-open
- fal fa-hands-helping
- fal fa-user-friends

**Comment by bradgenereux** [comment]
Also:
* fas fa-shipping-fast
* fas fa-parachute-box

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that 5.1.0-4 is a prerelease version.

Please check again with 5.1.0
