### ISSUE TITLE
fa-book-open doesn't work in regular OTF with 5.1

### ISSUE THREAD

**Issue by tonywatkins** [FortAwesome/Font-Awesome#13389]
The book-open icon works fine with light and solid but not in the regular OTF with the 5.1 (build: 1529524039) that I've just downloaded.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
