### ISSUE TITLE
fontawesome-pro package v5.1.0 not released on the private npm registry

### ISSUE THREAD

**Issue by cosmin2583** [FortAwesome/Font-Awesome#13386]
solid.js

fa-person-dolly
fa-home-heart
fa-user-check

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that 5.1.0-4 is a prerelease version.

Please check again with 5.1.0

**Comment by DanielRuf** [comment]
Sure but they should still be tagged and available on npm for other users.

**Comment by wfairclough** [comment]
It doesn't seem like `@fortawesome/fontawesome-pro@5.1.0` is available in the npm registry. Has 5.1.0 not been released for the pro version yet?

**Comment by DanielRuf** [comment]
Also release candidates and beta releases should be on npm, this can be done with SemVer.

**Comment by tagliala** [comment]
> It doesn't seem like @fortawesome/fontawesome-pro@5.1.0 is available in the npm registry. Has 5.1.0 not been released for the pro version yet?

Yes, sorry. Apparently `fontawesome-pro` hasn't be released

This should be addressed in the Pro Repository, but I'm leaving this open here

**Comment by robmadole** [comment]
Confirmed! I'm working to correct this. Sorry folks.

**Comment by robmadole** [comment]
OK, this should be resolved. @cosmin2583 @DanielRuf can you confirm?

**Comment by DanielRuf** [comment]
> "Unable to find a readme for @fortawesome/fontawesome-free@5.1.0"

=/

**Comment by tagliala** [comment]
Oh, just forgot: this issue has been fixed
