### ISSUE TITLE
Documentation: Hosting Font Awesome Yourself

### ISSUE THREAD

**Issue by josmaissan** [FortAwesome/Font-Awesome#13391]
At: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
Missing information about missing of fa- prefixes by CSS and js-files and missing minified versions

On this page:
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself
in the code

CSS:
```
<head>
  <!-- Our project just needs Font Awesome Solid + Brands -->
  <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/fa-brands.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/fa-solid.css" rel="stylesheet">
</head>
<body>
  <i class="fas fa-user"></i> <!-- uses solid style -->
  <i class="fab fa-github-square"></i> <!-- uses brand style -->
</body>
```
you are still have fa-brands.css and fa-solid.css
should be brands.css and solid.css

JS:
```
<head>
  <!-- Our project just needs Font Awesome Solid + Brands -->
  <script defer src="/your-path-to-fontawesome/js/fa-brands.js"></script>
  <script defer src="/your-path-to-fontawesome/js/fa-solid.js"></script>
  <script defer src="/your-path-to-fontawesome/js/fontawesome.js"></script>
</head>
<body>
  <i class="fas fa-user"></i> <!-- uses solid style -->
  <i class="fab fa-github-square"></i> <!-- uses brand style -->
</body>
```
you are still have fa-brands.js and fa-solid.js
should be brands.js and solid.js

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

> you are still have fa-brands.css and fa-solid.css
should be brands.css and solid.css
> you are still have fa-brands.js and fa-solid.js
should be brands.js and solid.js


That's right, files in the zip archive have different names from the ones on the repository

Ref: https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/css
Ref: https://github.com/FortAwesome/Font-Awesome/tree/master/svg-with-js/js

Also, archives are missing minified files 🤔

**Comment by talbs** [comment]
Thanks for the heads up, @josmaissan and @tagliala. I just took a look through the repo, our downloads, and docs. We've got a few file-naming things to sync up and will get everything squared away in the next update coming shortly.

**Comment by talbs** [comment]
Okay, gang. We should have our file naming synced up in our docs (https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-certain-styles) as well as in the repo with @robmadole's latest work on version 5.1.1 (https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/css).

Thanks for bringing this to our attention and keeping things super tidy and clear. 😄
