### ISSUE TITLE
Icon detail pages down

### ISSUE THREAD

**Issue by weshuiz** [FortAwesome/Font-Awesome#13399]
When browsing i noticed clicking on any icon to get its html will result a white empty page i can view the icon list and that is all icons are not acceseble any browser or device

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, the website is having some troubles

**Comment by weshuiz** [comment]
You realy think this bug and mine are the same when hey clicks the icon it goes back 
Links like icons/angry are empty nothing loads thats a whole other story

**Comment by tagliala** [comment]
The website has some major issues since yesterday, sorry.

I cannot fix by myself

**Comment by tagliala** [comment]
Reopening here, the issue is back

**Comment by mrkurt** [comment]
Will you post a URL that's exhibiting this please? Even better would be if you can run a curl to replicate, something like this on Linux or OSX:

```
curl -D - -o /dev/null -sS https://<url>
```

**Comment by supercodepoet** [comment]
@tagliala this should still be fixed so I am wondering if we have a bad link somewhere. Do you have steps to reproduce as in where you clicked from? Clicking on icons from /icons should work correctly.

**Comment by robmadole** [comment]
We just deployed a change for the icon detail pages. They were loading pre-rendered pages from S3 and they are now loading directly from origin (and being cached on the edge servers). If anyone is still having issues let us know what country you are from too.

**Comment by tagliala** [comment]
@robmadole 

Now it works again, but before the steps to reproduce were

1. Go to https://fontawesome.com/
2. Click on "Icons" in the navbar
3. Click on "accessible-icon"

**Comment by robmadole** [comment]
thanks @tagliala . We should have this solved now by the infrastructure change we made.
