### ISSUE TITLE
light-versions missing at repositories (Release 5.1.0)

### ISSUE THREAD

**Issue by josmaissan** [FortAwesome/Font-Awesome#13392]
At repositories:
https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/css
https://github.com/FortAwesome/Font-Awesome/tree/master/svg-with-js/js
light-versions seems to be missing

**Comment by maseyuk** [comment]
Also missing on this page https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Light version is an exclusive of Font Awesome 5 Pro.

Hope it helps

Closing here
