### ISSUE TITLE
documentation: Version 5.1.0 Released June 20, 2018

### ISSUE THREAD

**Issue by josmaissan** [FortAwesome/Font-Awesome#13390]
At: https://fontawesome.com/changelog/latest
links:
https://fontawesome.com/icons/plane-departing?d=gallery
https://fontawesome.com/icons/plane-arriving?d=gallery
should be: plane-departing >> plane-departure and plane-arriving >> plane-arrival

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13364, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
