### ISSUE TITLE
Version 4.7.0 documentation is not loading resources

### ISSUE THREAD

**Issue by millertn** [FortAwesome/Font-Awesome#13394]
1. navigate to https://fontawesome.com/v4.7.0/icons/ and try selecting an icon  (in my example I used clone)
2. redirecte here https://fontawesome.com/v4.7.0/icon/clone
3. none of the assets for the site are loading. if you look in the console there are alot of 404 GET request errors. All the information is still there, just a heads up about the assets.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I can confirm

The website is having some major issues, but I think there is more on this one

**Comment by antarasi** [comment]
5.1 page is having issues too.
Any icon page request is redirected back to homepage.
For example: [https://fontawesome.com/icons/align-justify?style=solid](https://fontawesome.com/icons/align-justify?style=solid)

**Comment by robmadole** [comment]
All fixed up!

**Comment by alitaha89** [comment]
I landed on this link: https://fontawesome.com/v4.7.0/icons , the page didn't load unless I added a "/'  at the end of link, the result is https://fontawesome.com/v4.7.0/icons/

**Comment by tagliala** [comment]
@alitaha89 that is a known issue.

> I landed on this link: https://fontawesome.com/v4.7.0/icons ,

Is there a page on the website or any official resource that points to that link?

**Comment by alitaha89** [comment]
@tagliala the link was saved in the browser history.

**Comment by robmadole** [comment]
We fixed this on last Friday I think. @alitaha89 can you try again?

**Comment by tagliala** [comment]
Looks fixed to me
