### ISSUE TITLE
[icon] Mixer

### ISSUE THREAD

**Issue by tremst** [FortAwesome/Font-Awesome#13409]
Formerly known as BEAM, a streaming platform currently owned by microsoft.

website:
https://mixer.com

**Comment by tagliala** [comment]
#
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11242, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
