### ISSUE TITLE
The icon `star-half-alt` doesn't work

### ISSUE THREAD

**Issue by tomderudderetna** [FortAwesome/Font-Awesome#13408]
### Describe the problem

The icon `star-half-alt` doesn't work (it doesn't appear).

### What did you expect?

Fix this please

### What version and implementation are you using?

Version: 5.0.13
Browser and version: Google Chrome Version 67

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

<i class="fas fa-star-half-alt"></i>

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[star-half-alt](https://fontawesome.com/icons/star-half-alt?style=solid) (sorry, documentation doesn't work at the moment) has been introduced in FA 5.1.0

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/metadata/icons.yml#L10346

Please upgrade

Closing here
