### ISSUE TITLE
Missing Pig Bank.

### ISSUE THREAD

**Issue by Netkompt** [FortAwesome/Font-Awesome#13404]
Please find Mr. Fatty Fat Fat.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[piggy-bank](https://fontawesome.com/icons/piggy-bank?style=solid)* has been introduced in Font Awesome 5.0.9

Please make sure that your Font Awesome installation is at least than 5.0.9

Hope it helps

Closing here

---

* Sorry, documentation doesn't work at the moment I'm writing
