### ISSUE TITLE
Fontawesome.com should be more stable (99.99% uptime) !

### ISSUE THREAD

**Issue by l2aelba** [FortAwesome/Font-Awesome#13416]
Good job anyway, and I bought the Pro version of Font Awesome because I like it so much :)

But I have to say about **[Fontawesome.com](https://fontawesome.com) should be 99.99% uptime!** or something **without errors**.

I got many times with `HTTP ERROR 502`, please don't waste our working hours about this.

![6qgkji5kll](https://user-images.githubusercontent.com/983458/41846467-0536bc88-7877-11e8-935f-d61b60065bb4.gif)

**Have a nice day FA team!**

**Comment by AKaravas** [comment]
I have the same problem.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I agree with you.

Sorry, the website is having issues in the last 3-4 days. I hope they will be sorted out as soon as possible

**Comment by CaelanStewart** [comment]
Yeah, same issues as above.

Considering pro, paid options are offered, having issues for 3-4 days of outage is not good.

**Comment by WillWammer** [comment]
Yeah.

They've been doing some maintenance on their site recently, so maybe that could be the problem?

**Comment by tagliala** [comment]
@CaelanStewart I do agree with you

I hope we could sort this out definitely

Ref: https://twitter.com/fontawesome/status/1011274306486263808

**Comment by th0mk** [comment]
Currently having issues with the documentation. Icons are not loading properly in the overview.

**Comment by l2aelba** [comment]
Still happening? @tagliala

**Comment by tagliala** [comment]
@l2aelba the website is working for me here (Italy), have you issues on a specific webpage?
