### ISSUE TITLE
Icon request: icon-volume-medium

### ISSUE THREAD

**Issue by DoomDesign** [FortAwesome/Font-Awesome#1341]
Hi there! Font Awesome is, well, awesome!
I'm currently using it in one of my projects and there is one icon that I'm missing, and I'm sure there are more people like me that would like to see (and use) this new icon:
icon-volume-medium
It's the same as the existing volume icons, with the sound waves coming out, but in this case, there are two sound waves (currently there are only icons with one or three sound waves). 
The use cases could be, when the icon with three waves looks too big (that's in fact my problem), or when you want to give the user some options to choose from (no volume - use the mute icon, low volume - use the volume icon with one wave, and so on...)

I also included an example (I just erased the third wave in photoshop) :
![example-icon-volume-medium](https://f.cloud.github.com/assets/466316/668246/669e2ee4-d80d-11e2-9fd3-4715df9bd7af.png)

**Comment by G-Driver** [comment]
+1

**Comment by Kagammor** [comment]
+1! I am sad to see this issue has been around since 2013 and likely won't be addressed soon. A mute and 2-wave speaker icon would really complete the subset.

**Comment by DUznanski** [comment]
+1

**Comment by KeitIG** [comment]
+1

**Comment by leothelocust** [comment]
+1

**Comment by hugohow** [comment]
+1

**Comment by guilhermefelipecgs** [comment]
:+1:

**Comment by prcd** [comment]
👍

**Comment by poddarh** [comment]
:+1:

**Comment by anithri** [comment]
:+1:

**Comment by jenskuhrjorgensen** [comment]
👍

**Comment by ethaligan** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks! This is available in FA Pro: https://fontawesome.com/icons/volume?style=solid

**Comment by Christilut** [comment]
It's kind of strange that this one is PRO but the other volume icons are not. I can go from `mute` to `off` to `down` to `up` but the medium volume icon does not fit in there.

**Comment by mikkelwf** [comment]
This is still an issue

**Comment by Ivorforce** [comment]
For future visitors, the icon has (silently?) changed from Pro to Free some time between 7.0 and 7.2. It is now finally available 🎉
