### ISSUE TITLE
Version selection on Getting Started misses CSS file

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#13411]
When using the version selector on [Getting Started](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css), it changes the version of the Font Awesome folder from:

```html
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-87DrmpqHRiY8hPLIr7ByqhPIywuSsjuQAfMXAE0sMUpY3BM7nXjf+mLIUSvhDArs" crossorigin="anonymous">
```

to

```html
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-oi8o31xSQq8S0RpBcb4FaLB8LJi9AT8oIdmS1QldR8Ui7KUQjNAnDlJjp55Ba8FG" crossorigin="anonymous">
```

However, it does not change the filename, which should be `fontawesome-all.min.css` not `all.css` for any 5.0.x version. The 5.0.13 documentation when switching from the upper right corner also shows the wrong filename.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> However, it does not change the filename, which should be fontawesome-all.min.css not all.css for any 5.0.x version. The 5.0.13 documentation when switching from the upper right corner also shows the wrong filename.

https://use.fontawesome.com/releases/v5.0.13/css/all.css works for me, as well as https://pro.fontawesome.com/releases/v5.0.13/css/all.css
