### ISSUE TITLE
Feature request: Add option to get/copy code in icon search page

### ISSUE THREAD

**Issue by RezaRahmati** [FortAwesome/Font-Awesome#13428]
Hello

Great work,

As user I want to be able to get or copy code in icon search page, so I wouldn't need to open icon and copy the code from detail

**Comment by sensibleworld** [comment]
Your wish is our command! Check out the new icon search with version 6: https://fontawesome.com/v6.0/icons?s=solid%2Cbrands

Click on any icon, and you'll get a detail view with all sorts of copy options.

<img width="843" alt="Screen Shot 2021-09-29 at 2 54 39 PM" src="https://user-images.githubusercontent.com/529604/135331137-a2c576f2-7b4f-4b64-aa5e-7dc5d6c409a2.png">
