### ISSUE TITLE
Error in json file (FA 5.1 Pro)

### ISSUE THREAD

**Issue by bwakabats** [FortAwesome/Font-Awesome#13429]
In the "simile-plus" icon, the "search" is set to
"terms []"
I assume this should be:
"terms": []

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Which json file?
`simile-plus`? 

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by bwakabats** [comment]
Sorry, never done this before...

### Describe the problem

Inside the file from the pro wen download:
fontawesome-pro-5.1.0-web\metadata\icons.json

There is a section for the icon "smile-plus" (line 56282)
Inside there there is a node called "search" (line 56288)
    "search": "terms []",
As you can see, the value is "terms []"

### What did you expect?

If you look at other examples (there are over 700), e.g. line 56231, the format should be
    "search": {
      "terms": []
    },

### What version and implementation are you using?

Version: 5.10
Browser and version: N/A

- [X] SVG with JS
- [X] Web Fonts with CSS
- [X] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Not sure what to put here, its just the file is in json file is in the wrong format at one point

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
@bwakabats thanks for reporting this.

A fix for this is on going

**Comment by tagliala** [comment]
This has been fixed a while ago in 5.1.1
