### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by FrancescoMussi** [FortAwesome/Font-Awesome#13437]
In the [following page](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css) there is a broken link.

It's the link to the **vue** related docs:

![screen shot 2018-06-27 at 17 23 52](https://user-images.githubusercontent.com/5312907/41980356-f95bcc00-7a2e-11e8-8e74-b5de150ecea0.png)

Correct link should be:
https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs

In that alert the link instead is:
https://fontawesome.com/how-to-use/on-the-web/using-with/vue

**Comment by tagliala** [comment]
Ciao!

Thanks for being part of the Font Awesome Community and for reporting this.

**Comment by talbs** [comment]
Thanks for the catch, @FrancescoMussi. We'll get that fixed up right away! 😄

**Comment by talbs** [comment]
Okay, this is fixed on https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs. Thanks for giving us the heads up. 😄
