### ISSUE TITLE
Icon request: mining pick and copper bar

### ISSUE THREAD

**Issue by Pablo-Araya** [FortAwesome/Font-Awesome#13434]
Hi may I ask to develop some sort of mining pick and a bunch of mineral (copper  or gold bar) for minery ?
Regards !
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by aethior** [comment]
Duplicate of #1680.

cc/ @tagliala
