### ISSUE TITLE
Backspace icon

### ISSUE THREAD

**Issue by ivancucer** [FortAwesome/Font-Awesome#13432]
### Describe the problem

`Backspace` icon doesn't recognize using desktop font.
https://fontawesome.com/icons/backspace

### What version and implementation are you using?

Version: 5.1.0
- [x] On the Desktop

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot confirm

Please double check that you are using FA 5.1.0. If you are in troubles, please uninstall Font Awesome and reinstall it back

Please also make sure that you are using **bold** font style

![image](https://user-images.githubusercontent.com/556268/41963788-bc610ed6-79f8-11e8-80cd-aa6b705eebf4.png)

PS: I'm assuming you are using Font Awesome 5 Free. If you are using the Pro version, please let me know

**Comment by ivancucer** [comment]
@tagliala thank you for your reply.
I'm a pro user and seems like this problem requires careful study.
I can confirm that I did install the latest 5.10 desktop fonts.

I can confirm it works on the Pages app:
![screen shot 2018-06-27 at 4 59 42 pm](https://user-images.githubusercontent.com/2349195/41982369-91083510-7a2b-11e8-8243-5060fa623f63.png)

but

it doesn't work on the Sketch app:
<img width="1363" alt="screen shot 2018-06-27 at 4 59 51 pm" src="https://user-images.githubusercontent.com/2349195/41982390-9a354c54-7a2b-11e8-9bf0-25e61b6de74e.png">

any ideas ?

**Comment by tagliala** [comment]
Please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

Please specify:
- That the issue is related to Sketch
- Sketch version
- Icon name
- Icon weight (light)

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
