### ISSUE TITLE
Missing icons in FA v5.1.0 

### ISSUE THREAD

**Issue by gtbu** [FortAwesome/Font-Awesome#13439]
As author of the  https://www.typesettercms.com/Plugins/338_Font_Awesome_5_Icons 
FA5 Typesetter-plugin with FA-5.0.13 i tried to update to FA-5.10 with
https://use.fontawesome.com/releases/v5.1.0/css/all.css, which is the foundation of the icons-dropdown.
just like  https://use.fontawesome.com/releases/v5.0.13/css/all.css

But in the dropwown appear more than 10 grayed out fonts, wich are not in the 5.10 files(woff, woff2 etc) like  fa-archway fa-atlas fa-award fa-backspace fa-bezier-curve fa-bong fa-brush fa-bus-alt fa-cannabis
fa-check-double fa-cocktail fa-concierge-bell fa-cookie fa-cookie-bite etc..

Most of the icons function and appear in the text - but those icons do not function either with fas , far or fab (v5.10). Please check why this is so. I think the glyphs are not in the font files.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate: https://jsfiddle.net/tagliala/en2kgbf7/4/

I'm using FA 5.1.0 via CDN. My browser is downloading the `woff2` file

![image](https://user-images.githubusercontent.com/556268/41991297-3afc7702-7a45-11e8-81bc-3e005f75b3fc.png)

Could you please provide a reproducible test case of your issue?

**Comment by gtbu** [comment]
In Typesetter i must disable the FA - class because it is styled with FA4.7, and the fa for FA5 gives me grayed out icons in the CMS.
* In the 5.10 css i read 
 .fa,.far,.fas{font-family:"Font Awesome 5 Free"}
.fa,.fas{font-weight:900}
So why can i not style those icons with far and fas , which have the same font-family ?

**Comment by tagliala** [comment]
Sorry, I still don't understand this issue.

I do not use Typesetter, if you can create a reproducible test case with font awesome I will take a look.

**Comment by nrdev88** [comment]
This doesn't need to be reproduced. It's plain simple: the icons he mentioned are not in the npm package distribution. I.e. bezier-curve is mentioned in the documentation to be under "solid":

![image](https://user-images.githubusercontent.com/21027153/45566599-7175a100-b857-11e8-9952-70c6de36ecc3.png)

It's not there. We can't use any of the mentioned icons by the TS.

**Comment by gtbu** [comment]
I see the the problem with 5.1 is in Typesetter CMS, as it functions in jsfidddle and i must find a workaround -thanks
