### ISSUE TITLE
Icon request: tree-view-vertical

### ISSUE THREAD

**Issue by DarkMajestic** [FortAwesome/Font-Awesome#1343]
Hello font awesome,
We love your library's awesomeness!
Please could you create an vertical tree view icon

We are building an app that monitors application servers and their configuration, using tree views to make navigation to nested parts of the configuration more intuitive.

something like this...
![tree-view-vertical](https://f.cloud.github.com/assets/4728803/674913/67861028-d8e5-11e2-9a7e-6292597b1b3e.png)

Thanks,

James

**Comment by imranmalik** [comment]
+1

**Comment by andyosbert** [comment]
+1

**Comment by vlipman** [comment]
+ 1 - would prefer too keep the tree's nodes generic - perhaps circles or squares - rather than folders

For example, to toggle a view from a list view to a tree view - where the tree represents any hierchical relationship

![image](https://cloud.githubusercontent.com/assets/11448869/6630076/05989d84-c8d2-11e4-9100-5b6090f39a34.png)

or 
![image](https://cloud.githubusercontent.com/assets/11448869/6630108/597604fa-c8d2-11e4-8f2a-3ad32b9518d2.png)

**Comment by SylvainCorlay** [comment]
Icon name  | Proposal
------------- | -------------
fa-treeview-vertical  | ![treeview](https://cloud.githubusercontent.com/assets/2397974/7922496/a962b07a-087a-11e5-9480-316e3e312a18.png)

**Comment by SylvainCorlay** [comment]
+1

**Comment by SylvainCorlay** [comment]
#2752 is a duplicate

**Comment by tagliala** [comment]
#2752 is about a folder tree. this is more like a vertical sitemap

**Comment by rdeslonde** [comment]
+1

**Comment by thiazzz** [comment]
+1

**Comment by namtab00** [comment]
+1

**Comment by ldstein** [comment]
+1

**Comment by vira-lytvyn** [comment]
+1

**Comment by rogyvoje** [comment]
+1

**Comment by genu** [comment]
+1

**Comment by jacobbroberg** [comment]
+1 (this could be similar to #8108)

**Comment by klein0r** [comment]
+1

**Comment by disruptek** [comment]
+1

**Comment by reyx** [comment]
+1

**Comment by derRoesi** [comment]
+1

**Comment by lazaa** [comment]
+1

**Comment by levithomason** [comment]
+1

**Comment by wggley** [comment]
+ 1

**Comment by alikhanz** [comment]
+1

**Comment by secelite** [comment]
+1

**Comment by sv0505** [comment]
+1

**Comment by jkubos** [comment]
+1

**Comment by gbarrionuevo** [comment]
+1

**Comment by leoc** [comment]
+1

**Comment by MasterAler** [comment]
+1, plz!

**Comment by r-man** [comment]
+1

**Comment by Rikijs** [comment]
+1

**Comment by knoxsp** [comment]
+1

**Comment by KingDumah** [comment]
+1

**Comment by fandomfilms** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available (list-tree) as part of the version 6 alpha release: https://fontawesome.com/download
