### ISSUE TITLE
Icon request: tree-view-horizontal

### ISSUE THREAD

**Issue by DarkMajestic** [FortAwesome/Font-Awesome#1344]
Hello font awesome,
We love your library's awesomeness!
Please could you create an horizontal tree view icon

same as my vertical tree view icon request but horizontal!

We are building an app that monitors application servers and their configuration, using tree views to make navigation to nested parts of the configuration more intuitive.

something like this...
![tree-view-horizontal](https://f.cloud.github.com/assets/4728803/674921/98349a1e-d8e5-11e2-85f2-ed6c29426050.png)

Thanks,

James

**Comment by sensibleworld** [comment]
We have a few icons that might work for this now.

https://fontawesome.com/icons/list-tree?s=solid
https://fontawesome.com/icons/diagram-nested?s=solid
https://fontawesome.com/icons/sitemap?s=solid
