### ISSUE TITLE
Icon request: icon-times-octagon (error)

### ISSUE THREAD

**Issue by KeithFrohn** [FortAwesome/Font-Awesome#13443]
### What can it be used for?

Used to highlight alerts of an Error severity (as opposed to Warning or Information).

The Warning icon (yield sign) is very nice.  I wish there was an Error icon in the shape of a stop sign.

### Example image (optional)

![image](https://user-images.githubusercontent.com/40650343/42011105-ea3f2e5c-7a5f-11e8-9677-9e1a0cc3f9f4.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro: https://fontawesome.com/icons/times-octagon?style=regular
