### ISSUE TITLE
GET https://cdn.fontawesome.com/js/stats.js 404 (Not Found)

### ISSUE THREAD

**Issue by glorp47** [FortAwesome/Font-Awesome#13441]
where is this request coming from and why is this particular page not found? Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details?

Are you still using the old Font Awesome CDN?

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by jimmyheaddon** [comment]
We've been seeing this for a few days now, 90 second timeouts each request to:

`<script src="https://use.fontawesome.com/34ae7a89dc.js"></script>`

It's like `stats.js` has been removed from the CDN

**Comment by tagliala** [comment]
@jimmyheaddon thanks for confirming that this affects the old cdn

@robmadole could you please take a look here?

**Comment by robmadole** [comment]
Yes, `stats.js` is no longer used. This was for an old feature that is no longer supported. You can find new instructions for using the CDN here: https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css

**Comment by WesleySmits** [comment]
@robmadole This still gives a 404 not found on the stats.js for projects still using font-awesome 4.x. (For example with this newly generated include URL: https://use.fontawesome.com/3d3a53909b.js)

**Comment by timokleemann** [comment]
> Yes, `stats.js` is no longer used. This was for an old feature that is no longer supported. You can find new instructions for using the CDN here: https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css

So where's the option to load **version 4** on that website? I don't think this issue is related to version 5 or higher.

**Comment by timokleemann** [comment]
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v4.7.0/css/all.css" integrity="..." crossorigin="anonymous">`

This doesn't work.

**Comment by tagliala** [comment]
@timokleemann please consider https://www.bootstrapcdn.com/fontawesome/ if you need a CDN for Font Awesome 4

**Comment by timokleemann** [comment]
Seems to work. Thank you!
