### ISSUE TITLE
counter() API documentation lists transform as an available param when it's not

### ISSUE THREAD

**Issue by shawnphoffman** [FortAwesome/Font-Awesome#13453]
Source: https://fontawesome.com/how-to-use/with-the-api/methods/counter

The FontAwesome API documentation currently states that the counter() operation supports transforms but looking at the source code, it does not. It would be **awesome** if it did support it but if that's not the plan then it should probably be removed from the docs site.

![2018-06-28 13_40_57-counter _ font awesome](https://user-images.githubusercontent.com/1154273/42059626-f15e90be-7ad8-11e8-97a8-c30b0d73a98c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

Don't know if this is a bug or a documentation issue, I've assigned both @robmadole and @talbs

**Comment by robmadole** [comment]
This is a documentation bug. I'll get this fixed up.

**Comment by talbs** [comment]
Looks like @robmadole fixed this for both our 5.2 docs (https://fontawesome.com/how-to-use/with-the-api/methods/counter) and our 5.0.13 ones (https://fontawesome.com/v5.0.13/how-to-use/with-the-api/methods/counter) as well.

Thanks for bringing this to our attention. It's much appreciated. 😄
