### ISSUE TITLE
Wrong Unicode code point

### ISSUE THREAD

**Issue by burtonsys** [FortAwesome/Font-Awesome#13451]
### Describe the problem

Your nifty table here:

https://fontawesome.com/cheatsheet

gives the Unicode code point of the "link" symbol as f0eb instead of the correct code point, which is 1F517 (🔗).

Dave
email: http://www.sealevel.info/ncdave.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The unicode point for `fa-link` is `f0c1`

![image](https://user-images.githubusercontent.com/556268/42058984-50720880-7b22-11e8-99f8-c23ebb1c7f67.png)

It is correct: https://jsfiddle.net/tagliala/en2kgbf7/5/

Please note that 1F517 is the emoji unicode point for link: https://www.fileformat.info/info/unicode/char/1f517/index.htm and it does not depend on Font Awesome. You can actually use `1F517` without Font Awesome.

Ref: #222

Hope it helps

Closing here
