### ISSUE TITLE
Icon request: paper-with-shield

### ISSUE THREAD

**Issue by ghuzhdij** [FortAwesome/Font-Awesome#13458]
Hi
I want this fa font for this png format image, please help me, I need it and it's emergency:
https://pasteboard.co/Hs7bnE1.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I need it and it's emergency:

I should advise you to consider a custom build of Font Awesome.

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by aethior** [comment]
Hi @ghuzhdij,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/file-shield

Regards.

cc/ @tagliala
