### ISSUE TITLE
Icon request: icon-plusminus

### ISSUE THREAD

**Issue by SoftCreatR** [FortAwesome/Font-Awesome#1345]
Just thought, this might be useful ;)

![glyph_plus_minus_00b1_147](https://f.cloud.github.com/assets/81188/668922/11dc7e7e-d821-11e2-9b65-dbbcec93d684.png)

**Comment by valioDOTch** [comment]
+1

**Comment by PhilPJL** [comment]
![image](https://user-images.githubusercontent.com/271656/51481160-25011b80-1d8b-11e9-9ae9-ee436b7702d9.png)

A plus or minus icon would be nicer than using text.

**Comment by aethior** [comment]
Hi @SoftCreatR,

Has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/plus-minus

Regards.

cc/ @tagliala
