### ISSUE TITLE
Missing or wrong Icons in 5.1

### ISSUE THREAD

**Issue by sylv3r** [FortAwesome/Font-Awesome#13456]
I upgraded my packages today to be able to use the new icons available in 5.1 but everything went wrong.

Packages version tested : 
```
    "@fortawesome/fontawesome-free-regular": "^5.1.0-3",
    "@fortawesome/fontawesome-free-solid": "^5.1.0-3",
    "@fortawesome/fontawesome-pro-light": "^5.1.0-3",
    "@fortawesome/fontawesome-pro-regular": "^5.1.0-3",
    "@fortawesome/fontawesome-pro-solid": "^5.1.0-3",
```

Not only the new icons aren't there (for example this one is missing : https://fontawesome.com/icons/smile-beam?style=light)

But old ones have disappeared (`faUserClock`) or mismatch with the look expected from your website (example the `faSmile` icon in `pro-light` version have really weird eyes now, which is not the case on the preview).

I have to downgrade my packages for now since it's messing up pretty much everything, but could you update either your packages or the website accordingly so we can know what to expect to find in there ?

Thanks.

**Comment by InsanityMeetsHH** [comment]
Font Awesome has changed the NPM packages. [Here is my solution](https://github.com/InsanityMeetsHH/gulp-templating/blob/master/package.json#L46-L49) to use version 5.1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#new-packages-available-for-browser-only-integration

Hope it helps, sorry for the breaking change

Closing here

**Comment by tagliala** [comment]
One more thing...

If bug reports/questions are related to Font Awesome Pro, please open issues in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by tagliala** [comment]
@sylv3r you are right, breaking changes are not supposed to be introduced within minor updates

**Comment by valentinocossar** [comment]
Hi to all, I've one question, I've seen the UPGRADING.md guide linked above, but I don't understand one thing. The `@fortawesome/fontawesome` is now deprecated in favor of `@fortawesome/fontawesome-svg-core`? This is what I've understood from the guide. Thank you.

**Comment by User934903920432** [comment]
@valentinocossar 

Yes, and you can add it from NPM
```
$ npm i --save @fortawesome/fontawesome-svg-core
```

**Comment by valentinocossar** [comment]
Thank you @User934903920432, but now I have another issue, how can I import the same icon from two different packages (eg, faHeart solid and light)? Thank you.

**Comment by valentinocossar** [comment]
Nevermind, [found the solution](https://github.com/FortAwesome/Font-Awesome/issues/13289), thank you. 😅
