### ISSUE TITLE
Icon request: fa-telescope

### ISSUE THREAD

**Issue by Tylerian** [FortAwesome/Font-Awesome#13455]
### What can it be used for?

The telescope icon can be used on space-related contexts, it also can be used as an analog to represent explore and discover features.

### Example image (optional)

![Example image](https://i.imgur.com/V691UA3.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🔭](https://emojipedia.org/telescope/) U+1F52D Telescope

**Comment by irontitan76** [comment]
I was looking for a telescope icon as well for an insights (articles) that I'm creating. I think would also be useful in various technology companies that work in aerospace or the cosmos.

**Comment by Nikki313** [comment]
I also would like a telescope icon. Another way to represent searching without the boring magnifying glass.

**Comment by T0T4R4** [comment]
I need one as well !

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/telescope?style=solid
