### ISSUE TITLE
js and css seem to fail to load on v. 4.7.0 icons page

### ISSUE THREAD

**Issue by rmlamarche** [FortAwesome/Font-Awesome#13459]
When loading the page as **https://fontawesome.com/v4.7.0/icons** the js and css fail to load with a 404, but when loading the page with an appended "/" **https://fontawesome.com/v4.7.0/icons/** the whole page seems to load fine.

edit: this seems to happen for other routes as well such as /cheatsheet

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue. Is there any link to `https://fontawesome.com/v4.7.0/icons` or `/cheatsheet` or you are inserting it manually in the navigation bar?

**Comment by rmlamarche** [comment]
It was a browser bookmark (which I have now updated to include the "/"), but it worked fine in the past without it so I just figured I'd throw an issue out there regardless.

Cheers.

**Comment by tagliala** [comment]
iirc, this has been an issue even with the old documentation.

I'm going to close here, but if you find a broken link please let us know
