### ISSUE TITLE
Icon Request: fa-star-and-cresent

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#13462]
This icon would be useful on specifically Muslim websites, for example, as it is the symbol of their religion. It could also be used on homework help sites, such as mine. It could look something like this:
![image](https://user-images.githubusercontent.com/25369857/42122170-8678deae-7c35-11e8-98b0-b4493f9d4d4e.png)

**Comment by Wingo5315** [comment]
Thanks @sensibleworld and all the folks at Font Awesome for making such an awesome software and adding my icon to your vast amount of icons!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/star-and-crescent?style=solid
