### ISSUE TITLE
Icons in 4.7 Docs Not Displaying

### ISSUE THREAD

**Issue by cruznunez** [FortAwesome/Font-Awesome#13460]
When loading the page https://fontawesome.com/v4.7.0/icons/ all the icons appear as squares.

I expected icons to load like they used to, like they do with Font Awesome v5 and v3 pages.

Version: v4.7.0
Browser and version: Chrome Version 67.0.3396.87 (Official Build) (64-bit), Safari Version 11.1 (13605.1.33.1.4)

On Macbook Pro (Retina, 13-inch, Early 2015)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check your browser console and report if you find any error?

**Comment by thomaskanzig** [comment]
Why happen this?

**Comment by tagliala** [comment]
I cannot replicate the error 500

@talbs could you please take a look?

**Comment by tagliala** [comment]
Ah, ok. I can confirm.

Got a 404 error on the woff2 file.

https://fontawesome.com/v4.7.0/assets/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0

**Comment by robmadole** [comment]
@cruznunez can you give it a try now? I think this is resolved.
