### ISSUE TITLE
How to install for angular ?

### ISSUE THREAD

**Issue by phil123456** [FortAwesome/Font-Awesome#13469]
Hi,

I cant make icon appear using local node_modules files

I installed this : 

`npm install --save-dev @fortawesome/fontawesome-free`

my .angular-cli.json :

```
 "styles": [
        "styles.css",
         "../node_modules/node_modules/@fortawesome/fontawesome-free/css/all.css",
      ],
      "scripts": [
      	"../node_modules/node_modules/@fortawesome/fontawesome-free/js/all.js",
      ],
```

no icon are apprearing

but it works using this :

```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
```

so why is it not working with local files ????

regards

**Comment by InsanityMeetsHH** [comment]
Just a  guess. Maybe you have to copy node_modules/@fortawesome/fontawesome-free/webfonts/ to your project folder.

Example directory structure:
- project/css/
- project/webfonts/
...

And your include looks weird "../node_modules/node_modules/...". Double "node_modules"?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not an angular developer

```
 "styles": [
        "styles.css",
         "../node_modules/node_modules/@fortawesome/fontawesome-free/css/all.css",
      ],
      "scripts": [
      	"../node_modules/node_modules/@fortawesome/fontawesome-free/js/all.js",
      ],
```

I think this is wrong, this is loading both css and js version. You should choose one of them.

Please take a look here: https://fontawesome.com/how-to-use/on-the-web/using-with/angular

let me know if that helps

**Comment by ahmadmu** [comment]
How can I use the imported icons in the (s)css psuedo elements in my stylesheet, if I imported the icons using the method in the link above? Do I still need to import the fontawesome css in my stylesheet (ie. all the icons)? Or is there a method where I can import the icons I need?

**Comment by dmitriydementor** [comment]
I added all styles in angular.json and it worked
`"styles": [
                            "node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss",
                            "node_modules/@fortawesome/fontawesome-free/scss/regular.scss",
                            "node_modules/@fortawesome/fontawesome-free/scss/solid.scss",
                            "node_modules/@fortawesome/fontawesome-free/scss/brands.scss",
                            "src/styles.scss"
                        ]`

**Comment by tagliala** [comment]
I'm going to close here, feel free to comment if this is still an issue
