### ISSUE TITLE
Icons missing from fontawesome-free-solid@5.1.0-3

### ISSUE THREAD

**Issue by joshfarrant** [FortAwesome/Font-Awesome#13479]
Some icons seem to be missing from the currently published version of `fortawesome-free-solid`, 5.1.0-3

The two that I've noticed are:

* table-tennis
* money-bill-wave

It appears that there are many more that are no longer available.

Apologies up-front if this is expected as 5.1.0-3 is not a full release 👍

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

5.1.0-3 is a prerelease version based on an older version of Font Awesome.

Please make sure to do a proper upgrade to 5.1.0, there are some breaking changes: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

**Comment by joshfarrant** [comment]
Hey @tagliala, thanks for the quick reply! 

I'd missed that totally, apologies. Cheers for the link 🍻

**Comment by tagliala** [comment]
@joshfarrant you're welcome, sorry for the breaking changes after a minor update
