### ISSUE TITLE
Multicolored Icons

### ISSUE THREAD

**Issue by SirSharanChakradhar** [FortAwesome/Font-Awesome#13483]
Is there anyway to get any multicolor for a same icon?

**Comment by InsanityMeetsHH** [comment]
Multicolored icons are planed but not yet startet. See [Duotone Colored Icons](https://fontawesome.com/updates).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As @InsanityMeetsHH mentioned, there will be a duotone icon package, but it will be available for Pro users. Ref: https://www.kickstarter.com/projects/232193852/font-awesome-5

I'm going to close here at the moment
