### ISSUE TITLE
Icon request: rainy-cloud

### ISSUE THREAD

**Issue by byMopo** [FortAwesome/Font-Awesome#13480]
### What can it be used for?

Helpful for displaying the weather

### Example image (optional)

Just like the existing cloud icon with some raindrops (as high as the cloud)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Wingo5315** [comment]
+1

**Comment by aethior** [comment]
Hi @byMopo,

This icon was added in v5.5.0.
Check https://fontawesome.com/icons/cloud-rain

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Subset of #155
