### ISSUE TITLE
Icon request: crane

### ISSUE THREAD

**Issue by Yannick86** [FortAwesome/Font-Awesome#13485]
For industry purposes.
You have icons for factories, trucks, etc, but this is an important missing icon which I need for several of our projects.

Example: https://image.freepik.com/free-icon/crane_318-61622.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12499, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
