### ISSUE TITLE
Icon request: folder-upload

### ISSUE THREAD

**Issue by SuperPat45** [FortAwesome/Font-Awesome#13484]
### What can it be used for?

Since Font awesome 5.1.0 has a file-upload icon, but I also need a folder upload icon for a google drive like menu item:

### Example image (optional)

![folder-upload-google-drive](https://user-images.githubusercontent.com/7791600/42324752-55916dfa-8064-11e8-8d6a-6c04249687a9.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Added this in a recent release: https://fontawesome.com/icons/folder-upload?style=solid
