### ISSUE TITLE
Icon request: Future / Past date

### ISSUE THREAD

**Issue by pigsinspace** [FortAwesome/Font-Awesome#13482]
### What can it be used for?

showing archived data or upcoming events

### Example image (optional)

https://icon-icons.com/id/icon/masa-lalu/55841

http://www.pixempire.com/icon/send-calendar-or-date-icon.html

both styles above requested with matched pair

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
MATCHED
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
YES
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
YES
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
OK

**Comment by aethior** [comment]
Hi @pigsinspace,

[**fa-clock-rotate-left**](https://fontawesome.com/icons/clock-rotate-left) was added in v4.1.0.
You can upvote #18870 request for `fa-clock-rotate-right` icon.

Regards.

cc/ @tagliala
