### ISSUE TITLE
Icon request: local-business

### ISSUE THREAD

**Issue by DevSmartSolutions** [FortAwesome/Font-Awesome#13492]
### What can it be used for?

**Local Business** or **Shop** icon.
Used for shops or small business.

### Example image
![image](https://user-images.githubusercontent.com/26815179/42380962-ecce69f4-812f-11e8-8c70-6f10fb41df3d.png)

![image](https://user-images.githubusercontent.com/26815179/42381003-03e07d1c-8130-11e8-8192-08c05476d950.png)

### Icon request checklist

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Already available:
- https://fontawesome.com/icons/store?style=solid
- https://fontawesome.com/icons/store-alt?style=solid

Please make sure you are using Font Awesome >= 5.0.13

Closing here
