### ISSUE TITLE
Icon request: Zomdi and YeWoKrom Icons

### ISSUE THREAD

**Issue by mikega1979** [FortAwesome/Font-Awesome#13499]
Hello,
Please, it would be nice to have these new social network platforms icon added to FA web applications list and other category list FA as deemed appropriate on the Font-Awesome list. 

These icons inclusion will enable developers and users to easily include the icons when apply the APIs of these website/platforms to their applications and websites.

**1. Zomdi Icon:**  
https://pasteboard.co/HtuT6jq.png

**2. Zomdi Name icon:**  
https://pasteboard.co/HtuTMF3.png

**3. Zomdi Messenger Icon:** 
https://pasteboard.co/HtuWCWF.png

**4. YeWoKrom Icon:** 
https://pasteboard.co/HtuZdF2.png

_**I am also attaching the here in order of the above list.**_ 

**1. Zomdi Icon:**  
![apple-touch-icon-114x114](https://user-images.githubusercontent.com/40944807/42419687-763e768c-82a9-11e8-87ed-3d8b90b4cfba.png)

**2. Zomdi Name icon:**  
![appicon](https://user-images.githubusercontent.com/40944807/42419696-959a3f7a-82a9-11e8-8ac0-febe44913676.png)

**3. Zomdi Messenger Icon:** 
![icon-fashionafrica_app_icon](https://user-images.githubusercontent.com/40944807/42419703-b9a9a982-82a9-11e8-822f-209932d5cf47.png)

**4. YeWoKrom Icon:** 
![icon-fashionafrica_app_icon](https://user-images.githubusercontent.com/40944807/42419718-de1b3d3a-82a9-11e8-8a6d-97551087861d.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please split this request in four individual requests, one for each brand / product

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by mikega1979** [comment]
Okay,
Am resubmitting please.

Thanks
