### ISSUE TITLE
PUT <i class="fa fa-chevron-down"></i> INSTEAD OF <i class="fas fa-chevron-down"></i>

### ISSUE THREAD

**Issue by ruska199** [FortAwesome/Font-Awesome#13494]
Write "i class="fa fa-chevron-down" instead of "i class="fas fa-chevron-down" in the browser field which contain link for user.

**Comment by Ednas** [comment]
Version 4 uses fa, whereas version 5 uses fas (far and fal as well). Check which version you're working with. Best of luck.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas` is not a typo.

Please refer to the documentation: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

If you are using font awesome 4 and you can't/won't update, here is the link to the old documentation: https://fontawesome.com/v4.7.0/

Hope it helps

Closing here
