### ISSUE TITLE
`fa-file-invoice` Not Displaying In Web CSS 5.0.13

### ISSUE THREAD

**Issue by mikebronner** [FortAwesome/Font-Awesome#13493]
### Describe the problem
```html
<i class="fas fa-file-invoice"></I>
```
Does not display.

### What did you expect?
To see the icon.

### What version and implementation are you using?
Version: 5.0.13 web download, using sass files.
Browser and version: Safari 11.1.1

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Added two screenshots to show that font-awesome is working, just not for this specific icon:
![screen shot 2018-07-06 at 11 55 20 am](https://user-images.githubusercontent.com/1791050/42395678-9393ccba-8113-11e8-9bc1-2373dcaa78da.png)
![screen shot 2018-07-06 at 11 55 33 am](https://user-images.githubusercontent.com/1791050/42395683-95a7422a-8113-11e8-8fb4-ac145d611864.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[file-invoice](https://fontawesome.com/icons/file-invoice?style=solid) has been added in version 5.1.0

Please update

Hope it helps

Closing here

**Comment by mikebronner** [comment]
@tagliala I tried this with 5.1.0 as well, and it is not displaying there either (cleared cache, all the usual).

**Comment by tagliala** [comment]
@mikebronner please provide a reproducible test case

http://jsfiddle.net/tagliala/en2kgbf7/10/

**Comment by mikebronner** [comment]
@tagliala I think the problem is with Webpack -- I'm using the SCSS files, and the CSS font files, compiling it down with Webpack (so I can't really reproduce it in in a fiddle). I'm open to suggestions.

**Comment by mikebronner** [comment]
@tagliala Bugger, never mind. Today it decided to start working. LOL Not sure why clearing of cache didn't fix that the first time around.

**Comment by tagliala** [comment]
Glad you've solved 👍
