### ISSUE TITLE
Icon request: Zomdi Name icon

### ISSUE THREAD

**Issue by mikega1979** [FortAwesome/Font-Awesome#13502]
### What can it be used for?

Hello,
Please, it would be nice to have these new social network platforms icon added to FA web applications list and other category list FA as deemed appropriate on the Font-Awesome list.

These icons inclusion will enable developers and users to easily include the icons when apply the APIs of these website/platforms to their applications and websites.

### Example image 
![appicon](https://user-images.githubusercontent.com/40944807/42421137-3523d20c-82c0-11e8-8756-b3a585b5aa75.png)

https://pasteboard.co/HtuTMF3.png 

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
I cant to find information about this app.
The domain `https://zomdi.com/` redirects to other website and the Google Play developer profile is empty ([link](https://play.google.com/store/apps/dev?id=4940104492074992054&hl=es)).

cc/ @tagliala

**Comment by aethior** [comment]
I cant to find information about this app.
The Google Play developer profile is empty ([link](https://play.google.com/store/apps/dev?id=4940104492074992054&hl=es)).

cc/ @tagliala
