### ISSUE TITLE
Icon request: file-spreadsheet or file-ods

### ISSUE THREAD

**Issue by SuperPat45** [FortAwesome/Font-Awesome#13506]
### What can it be used for?

Using the libreoffice/ODS file format instead of Excel, we need an icon for generic spreadsheet files or for specialized ODS files

### Example image (optional)

![ods](https://user-images.githubusercontent.com/7791600/42445108-5f207e72-8372-11e8-8fcb-4d6f5f60b492.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by spider-network** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the extremely late reply, I've missed this one.

I'm going to consider this a duplicate (subset, actually) of #8446, please +1 that request

Closing here
