### ISSUE TITLE
Missing Icons in FortAwesome Packages

### ISSUE THREAD

**Issue by canpan14** [FortAwesome/Font-Awesome#13508]
### Describe the problem

Some icons are missing in the packages listed [here](https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons#packages)

I'm using the free solid/regular packages

To name a couple that I was trying to use, "grin" and "grinHearts"

### What did you expect?

Expected all the icons to be there.

### What version and implementation are you using?

Version: 5.1.0-11 of the icon packages (prerelease)
Browser and version: Chrome 67
- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Look in the node modules folder after importing one of the above packages, and files for grin (and others aren't there).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-grin](https://fontawesome.com/icons/grin?style=solid) has been introduced in 5.1.0

5.1.0-11 is a prerelease version based on an old version of Font Awesome which does not include that icon

Please make sure you are using the latest released version of FA

Hope it helps

Closing here
