### ISSUE TITLE
Icon request: Zomdi Icon

### ISSUE THREAD

**Issue by mikega1979** [FortAwesome/Font-Awesome#13501]
### What can it be used for?

Please, it would be nice to have these new social network platforms icon added to FA web applications list and other category list FA as deemed appropriate on the Font-Awesome list. 

These icons inclusion will enable developers and users to easily include the icons when apply the APIs of these website/platforms to their applications and websites.

### Example image 

https://pasteboard.co/HtuT6jq.png  

(https://user-images.githubusercontent.com/40944807/42419687-763e768c-82a9-11e8-87ed-3d8b90b4cfba.png)  

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mikega1979** [comment]
What is the next step of action either from my side or from your side?
Could you please make all my issues available on version 4 and 5?

**Comment by tagliala** [comment]
> What is the next step of action either from my side or from your side?

This request will be follow the same life cycle of all [other brand requests](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+label%3A%22brand+icon%22+sort%3Acomments-desc)

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> Could you please make all my issues available on version 4 and 5?

Sorry, FA 4 is in EOL

**Comment by aethior** [comment]
I cant to find information about this app.
The domain `https://zomdi.com/` redirects to other website and the Google Play developer profile is empty ([link](https://play.google.com/store/apps/dev?id=4940104492074992054&hl=es)).

cc/ @tagliala
