### ISSUE TITLE
Icon request: balloon

### ISSUE THREAD

**Issue by PxLucasF** [FortAwesome/Font-Awesome#13510]
### What can it be used for?

Importante note: YES, this icon has been requested before, but since 2014 (when someone asked for it) we don't have it on Font Awesome yet. Here's the [original request](https://github.com/FortAwesome/Font-Awesome/issues/3398).

The balloon can be used to represent party and decoration stuff. Until now, the only icon I found in this category is the [gift](https://fontawesome.com/icons/gift) one.

Additionally, it could be a 'balloons' icons too, just like 'user' and 'users'.

### Example image (optional)

![Balloon Icon](https://i.imgur.com/JOjbjik.png)

![Balloon Icon](https://i.imgur.com/xSg5Uof.png)

### Icon request checklist

- [ ✔️ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ✔️ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ❌ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ✔️ ] I have included at least one example image if it could be helpful (optional)
- [ ✔️ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> YES, this icon has been requested before, but since 2014 (when someone asked for it) we don't have it on Font Awesome yet. Here's the original request.

Sorry, the best thing you can do is to upvote #3398. I can't leave this open

Closing here
