### ISSUE TITLE
Icon broken: rev rev.io

### ISSUE THREAD

**Issue by MazeWebArchitect** [FortAwesome/Font-Awesome#13514]
### Problem description:

The "rev"-icon seems to be broken.
On the single-icon Page it is not displayed:
https://fontawesome.com/icons/rev?style=brands
And if I try to implement it into my project it doesn't get rendered either.

### What version and implementation are you using?

Version: 5.0.6 (PRO) (Problem persists with 5.1.0 PRO)
Browser and version: Any browser, version and device

- [ untested ] SVG with JS
- [ fails ] Web Fonts with CSS
- [ fails ] SVG Sprites
- [ fails ] On the Desktop

### Reproducible test case

https://codepen.io/anon/pen/XBWKME

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @MazeWebArchitect. Sorry for any trouble this might have caused. We'll have this fixed in our next version coming out very shortly. 😄

**Comment by talbs** [comment]
Okay, folks. This is fixed as of version 5.1.1. Check out https://fontawesome.com/icons/rev?style=brands. And here's a working demo using the 5.2.0 SVG + JS version of Font Awesome - https://codepen.io/fontawesome/pen/ZjXzzv.

Thanks again for bringing this to our attention. 😄

**Comment by MazeWebArchitect** [comment]
Awesome thank you
