### ISSUE TITLE
Icon Request: fa-dharma-wheel

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#13515]
This icon would be very useful for Buddhist-specific sites, reference sites and homework help sites like mine. It would also add another religious icon to the vast amount that are "in progress." Here's an example: 
![image](https://user-images.githubusercontent.com/25369857/42523649-3c8ea6f0-8466-11e8-8385-d9c0cd65ffee.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/dharmachakra?style=solid
