### ISSUE TITLE
fa fa-handshake-o is not working v4.7

### ISSUE THREAD

**Issue by KarthickeswarKR** [FortAwesome/Font-Awesome#13519]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate: https://jsfiddle.net/tagliala/s3msxtbe/38/

Please also take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

If you think there is still an issue with Font Awesome, please make sure that your new bug report follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
