### ISSUE TITLE
Icon request: icon-category

### ISSUE THREAD

**Issue by siangboon** [FortAwesome/Font-Awesome#13523]
### What can it be used for?

for e-commerce back-end category

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Please provide a single color example

**Comment by siangboon** [comment]
https://www.kisspng.com/png-computer-icons-content-symbol-share-user-a-phrase-1295815/preview.html
https://iconscout.com/icon/shopping-category
https://www.iconfinder.com/icons/785045/card_card_sorting_category_information_architecture_label_organize_ux_icon

**Comment by tagliala** [comment]
Could you please provide an example suitable for 16px icon size?

> https://www.iconfinder.com/icons/785045/card_card_sorting_category_information_architecture_label_organize_ux_icon

It looks like a complex version of https://fontawesome.com/icons/sitemap?style=solid

**Comment by tagliala** [comment]
Closing because of missing example
