### ISSUE TITLE
Icon request: icon-hierarchy

### ISSUE THREAD

**Issue by siangboon** [FortAwesome/Font-Awesome#13528]
### What can it be used for?

for admin page, indicate organization hierarchy chart

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
We have [sitemap](https://fontawesome.com/icons/sitemap?style=solid) for this use case.

If you have something different in mind, please provide a single color example

**Comment by siangboon** [comment]
https://www.pinterest.com/pin/717620521847191939/

**Comment by tagliala** [comment]
Duplicate of: #12060
