### ISSUE TITLE
Pro Version: Angular Build Pseudo Element not rendered

### ISSUE THREAD

**Issue by thomae82** [FortAwesome/Font-Awesome#13529]
I have a Angular CLI Project and I am using Fontawesome Pro with a valid licence. Within my project I have css Pseudo element including icons. In development mode the icons are shown correctly. Also for production everything is working fine as long as I do not build in prod mode.

I had to append `--output-hashing bundles` and to remove '--prod' to the prod build command: `ng build --environment prod --output-hashing bundles`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by thomae82** [comment]
Here we go: https://github.com/FortAwesome/Font-Awesome-Pro/issues/1162
