### ISSUE TITLE
icon-request: icon-tube

### ISSUE THREAD

**Issue by MuyBien** [FortAwesome/Font-Awesome#1353]
Hi!
We are using your awesome FontAwesome in a hospital application. You made some usefull icons for this use but can you do more?

the icon-tube will be like the icon-beaker but more strait at the bottom...

![capture2](https://f.cloud.github.com/assets/1921522/673359/e64035d2-d8b4-11e2-9e03-b3841102c97c.png)

the icon-plate will be like the icon-building but whitout entry ^^
(a plate is a support where you drop sample in wells... the number of wells can change between plates).

![capture](https://f.cloud.github.com/assets/1921522/673374/69705b94-d8b5-11e2-94ae-5c0517298dd4.png)

Maybe it can be merge with https://github.com/FortAwesome/Font-Awesome/issues/150?source=cc

Thanks.

**Comment by vinneyk** [comment]
+1 came looking for a beaker but test tube would work; still, beaker would be cool...

**Comment by G-Driver** [comment]
+1

**Comment by phasjim** [comment]
+1!

**Comment by ringner** [comment]
+1

**Comment by ice12192** [comment]
+1

**Comment by rodryquintero** [comment]
+1

**Comment by tagliala** [comment]
Renaming this as `icon-tube`, please open a new request for `icon-plate`

**Comment by chodaboy14** [comment]
+1  I am interested in the tube having a cap (bung) that will display the colour.

**Comment by sriadiga** [comment]
+1

**Comment by labkey-jessim** [comment]
+1

**Comment by sensibleworld** [comment]
There are now a few options for this in the 5.0.1 release of Font Awesome Pro: https://fontawesome.com/icons?d=gallery&q=vials
