### ISSUE TITLE
Icon request: star-plus

### ISSUE THREAD

**Issue by Prawesome** [FortAwesome/Font-Awesome#13539]
### What can it be used for?
General use case. It can be used to signify that stars can be added which could be used in rating systems

### Example image (optional)
[https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-232_star_favorite_add-512.png](url)

![image](https://user-images.githubusercontent.com/12979222/42680642-32a23cd0-86a3-11e8-8156-cf4adf311e21.png)

**Comment by tagliala** [comment]
Refer to: #1181

You can implement this icon with the SVG framework: https://jsfiddle.net/tagliala/ydq3jrne/42/

Docs: 
https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Prawesome** [comment]
Thats a great idea, thanks. That will satisfy my needs for now
