### ISSUE TITLE
Icon request: Figma

### ISSUE THREAD

**Issue by scotato** [FortAwesome/Font-Awesome#13536]
### What can it be used for?

Linking to Figma documents

### Example image (optional)

![Figma Icon](https://cdn-images-1.medium.com/max/1600/1*6XgfDCVn81AYX68Xvd2I-g@2x.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by MrFevs** [comment]
+1

**Comment by talbs** [comment]
Released in version 5.6.0 - https://fontawesome.com/icons/figma. 😄
