### ISSUE TITLE
CSS pseudo element not working for non Pro icons

### ISSUE THREAD

**Issue by yasin-mesut** [FortAwesome/Font-Awesome#13543]
I'm trying to use a non Pro icon within a pseudo element (:before). I've been following up the docs but it's been no use.

I'm using vue.js (including vue-fontawesome).

My vendor looks like this:

```
import Vue from 'vue'
// the component
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
// the library
import { library, config } from '@fortawesome/fontawesome-svg-core'
// add more icon categories as you want them, even works with pro packs
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'

config.autoAddCss = false;

// asociate it to the library, if you need to add more you can separate them by a comma
library.add(fas, fal, fab);
Vue.component('font-awesome-icon', FontAwesomeIcon);
```

Doing so I can use Pro icons, including Brands, within pseudo elements just like so:

```
      &::before {
        font-family: "Font Awesome 5 Pro";
        content: "\f007";
      }
```

As I said, I can also use Brands by using `font-family: "Font Awesome 5 Brands";` but no matter what I do the Free fonts are not working. I've tried using `font-family: "Font Awesome 5 Solid";` since I'm using SVG fonts as well as the font-weight approach for web fonts - just for testing purposes.

Is there any problem with the vue plugin itself or am I just missing something?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I can't help you to fix this use case but here they are some hints.

**Check that the `searchPseudoElements` option is set to `true`**

I can't see this line `config.searchPseudoElements = true` in your javascript snippet

Ref: https://fontawesome.com/how-to-use/with-the-api/setup/configuration#options

**Check that you are using the latest stable version of the library, 5.1.0**
Please confirm that you are not using old prerelease versions of Font Awesome 5.1.0 (they have a dash in the version name).

**Fix your CSS**
Use the proper way of using pseudoelements with the SVG Framework:

```css
.icon::before {
  display: none;
  font-family: "Font Awesome 5 Solid";
  content: "\f007";
}
```

Demo: http://jsfiddle.net/tagliala/ydq3jrne/48/
Ref: https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements

*... last but not least ...*

**Avoid pseudoelements, or use the webfont version**
Quoting from: https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements
> Although you can use pseudo-elements with SVG and JS we do not recommend using this method. It does not provide as many usage options, is difficult to configure, and is the slowest method of using Font Awesome. (Painfully slow in some cases.)

**Comment by tagliala** [comment]
Closing here, please feel free to comment if your issue has not been solved

**Comment by stevewinni-cc** [comment]
Having worked with this I can reproduce this issue as described. Using GULP; Display: none I believe is an error in the docs, but it makes no difference anyway.

"devDependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/register": "^7.0.0",
    "@fortawesome/fontawesome-pro": "^5.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.10",
    "@fortawesome/free-brands-svg-icons": "^5.6.1",
    "@fortawesome/free-regular-svg-icons": "^5.6.1",
    "@fortawesome/free-solid-svg-icons": "^5.6.1",
    "@fortawesome/pro-light-svg-icons": "^5.6.1",
    "@fortawesome/pro-regular-svg-icons": "^5.6.1",
    "@fortawesome/pro-solid-svg-icons": "^5.6.1"
}

JS
import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'

library.add(fas, far, fab, fal)

dom.watch()
window.FontAwesomeConfig = {
      searchPseudoElements: true
 }

CSS
:before{
	content: '\f058'; 
	font-family: "Font Awesome 5 Pro";
 }

This works for Pro and Brands but not for any Regular / Free Icons.

Any Help would be appreciated.

**Comment by stevewinni-cc** [comment]
We also tried updating to 5.6.3 and same failure to load.

**Comment by tagliala** [comment]
Hi,

`Display: none` is not an error, it must be used

> font-family: "Font Awesome 5 Pro";

Please note that the font name is different. Try with `font-family: "Font Awesome 5 Solid";` or `font-family: "Font Awesome 5 Regular";` or `font-family: "Font Awesome 5 Free";` with a proper `font-weight` property (`400` for regular, `900` for solid)

Ref: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

> window.FontAwesomeConfig

Please configure how it is described in the docs: https://fontawesome.com/how-to-use/with-the-api/setup/configuration#configuration

![image](https://user-images.githubusercontent.com/556268/51130552-85450a00-182d-11e9-94bf-0d8b747835ba.png)

**Comment by stevewinni-cc** [comment]
Thanks for the feedback... I understand now that the replacement makes the display none required (Thanks for the insight).

Just to share further the replacement takes place as you can see its detecting but not resolving the icon.

<img width="910" alt="screenshot 2019-01-14 at 18 30 05" src="https://user-images.githubusercontent.com/25501022/51132665-c7b91780-182a-11e9-84e7-b3645c48b49f.png">

The CSS is configured ok;

<img width="361" alt="screenshot 2019-01-14 at 18 30 19" src="https://user-images.githubusercontent.com/25501022/51132685-d1427f80-182a-11e9-9552-ce2b7f4b5737.png">

We updated the code to match the documents, as we are including all the icons should this not work?

import { config } from '@fortawesome/fontawesome-svg-core'
import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'

library.add(fas, far, fab, fal)

config.searchPseudoElements = true;

dom.watch();

Any idea why?

**Comment by stevewinni-cc** [comment]
Update: Not sure why but after update npm again and rebuilding we have got this working see finished code;

NPM
"devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3",
    "@babel/register": "^7.0.0",
    "@fortawesome/fontawesome-pro": "^5.6.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.6.3",
    "@fortawesome/free-regular-svg-icons": "^5.6.3",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/pro-light-svg-icons": "^5.6.3",
    "@fortawesome/pro-regular-svg-icons": "^5.6.3",
    "@fortawesome/pro-solid-svg-icons": "^5.6.3"
}

CSS
 #container-search{
	position: relative;
    	padding: 1.875rem 1.875rem !important;

    	&:before{
		    content: "\f002";
		    font-family: "Font Awesome 5 Solid";
		    font-size: 1.5rem;
		    font-weight: 900;
		    display: none;

		}
    	svg{
    		position: absolute;
		    top: 0px;
		    bottom: 0px;
		    margin: auto;
		    left: 45px;
		     height: 35px;
    	}


JS
import { config } from '@fortawesome/fontawesome-svg-core'
import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { fal } from '@fortawesome/pro-light-svg-icons'

library.add(fas, far, fab, fal);

// Kicks off the process of finding <i> tags and replacing with <svg>
config.searchPseudoElements = true;

dom.watch();

This results in the expected;

<img width="372" alt="screenshot 2019-01-14 at 18 51 55" src="https://user-images.githubusercontent.com/25501022/51133654-81b18300-182d-11e9-8ea2-1e7ba3b7f043.png">

**Comment by stevewinni-cc** [comment]
Interesting when we switch the above to Pro Light;

content: "\f002";
font-family: "Font Awesome 5 Pro";
font-weight: 100;

In the above it fails again with undefined error:

index.es.js:836 Uncaught TypeError: Cannot read property 'f002' of undefined
    at byUnicode (index.es.js:836)
    at index.es.js:1456
    at Array.forEach (<anonymous>)
    at index.es.js:1439
    at Array.forEach (<anonymous>)
    at index.es.js:1438
    at disableObservation (index.es.js:983)
    at searchPseudoElements (index.es.js:1435)
    at Object.i2svg (index.es.js:1753)
    at autoReplace (index.es.js:1944)

API Key Issue?

**Comment by tagliala** [comment]
@stevewinni-cc please open a new issue with a reproducible test case and feel free to mention me, I will take a look

**Comment by marinameth** [comment]
Thanks for the feedback... I understand now that the replacement makes the display none required (Thanks for the insight)??

**Comment by tagliala** [comment]
@marinameth yes, `display: none` is required when you are using the SVG Framework

Please refer to:
https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

| Framework | `display: none`|
|-------------| :---: | 
|SVG            | ✔️ | 
|CSS            |  ❌ |

**Comment by iamface** [comment]
Hello,

I am having a very similar problem, but I cannot get my Pro icons to work with pseudo.. My example is very similar to the initial from @yasin-mesut. I am using Vue.js and have the following:

    // main.js
    import { library } from '@fortawesome/fontawesome-svg-core'
    import { fas } from '@fortawesome/pro-solid-svg-icons'
    import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
    library.add(fas)
    Vue.component('font-awesome-icon', FontAwesomeIcon)

    // component.js
    <a class="work"></a>Work<font-awesome-icon :icon="['fas', 'th']" />

    // css
    .work {
        display: inline-block;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;

        &:before {
          font-family: "Font Awesome 5 Pro";
          font-weight: 900;
          content: "\f007";
          color: red;
        }
      }

and I keep getting the following:
<img width="72" alt="screen shot 2019-01-17 at 4 26 34 pm" src="https://user-images.githubusercontent.com/4822242/51355603-e7dc1700-1a74-11e9-9513-ca7666cfaf65.png">
You can see I have the icons imported from my Pro library and they appear just fine as the inline, but not as the pseudo..
<img width="256" alt="screen shot 2019-01-17 at 4 26 52 pm" src="https://user-images.githubusercontent.com/4822242/51355651-08a46c80-1a75-11e9-9b84-7e652f2e6117.png">
The styles are showing correct, so I'm not sure why it won't appear!

Can someone tell me what I'm missing?

**Comment by tagliala** [comment]
@iamface 

Hi, as far as I know, pseudo elements are not supported by the vue.js component.

Also, we advice to avoid pseudoelements at all in the SVG framework

Ref: FortAwesome/vue-fontawesome#84

Docs: 
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements
- https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements
