### ISSUE TITLE
Icon request: fab fa-adobe-flash

### ISSUE THREAD

**Issue by ratajs** [FortAwesome/Font-Awesome#13545]
### What can it be used for?

It can be used as an Adobe Flash Player logo

### Example image

![image](https://image.flaticon.com/icons/svg/499/499442.svg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues?utf8=%E2%9C%93&q=flash) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sanek4life** [comment]
+1

**Comment by tagliala** [comment]
Sorry, closing this and labeling as cantfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150
