### ISSUE TITLE
Icon request: Elevator

### ISSUE THREAD

**Issue by NivNavick** [FortAwesome/Font-Awesome#13549]
Can be used to indicate floor number

![image](https://user-images.githubusercontent.com/11910876/42733048-df6deaae-8833-11e8-8e37-dc7b05a8da35.png)
![image](https://user-images.githubusercontent.com/11910876/42733055-f4789f2a-8833-11e8-821f-d0c994bd7a8e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6047, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
