### ISSUE TITLE
All of my icons are showing up as boxes

### ISSUE THREAD

**Issue by nofeenews** [FortAwesome/Font-Awesome#13544]
This past week I noticed that everywhere I used a fontawesome icon on my website, the icons just show as boxes now. I didn't touch anything having to do with fontawesome on my website. I even updated to the latest release and nothing changed. Any idea what's going on?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
