### ISSUE TITLE
Icon request: Unpin

### ISSUE THREAD

**Issue by hadi-shamsabadi24** [FortAwesome/Font-Awesome#13542]
### What can it be used for?

pin or upin file some online filemanager & etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #10749 ?

Or it is https://fontawesome.com/icons/thumbtack?style=solid

?

**Comment by nancycg** [comment]
Do we have a unpin icon available? I know font awesome is having pin icon but I can not find unpin which should be a cross line in mid of pin icon maybe... Please reply!

**Comment by sensibleworld** [comment]
`thumbtack-slash` will be in our next release
