### ISSUE TITLE
icon request: do not use/ warning

### ISSUE THREAD

**Issue by LauGugli** [FortAwesome/Font-Awesome#13555]
Hi, it would be nice to have an icon like this, just for "do not use"

![image](https://user-images.githubusercontent.com/14312277/42773407-7c549f14-8903-11e8-9ff2-07f855a65c1e.png)

thank you!

**Comment by nickdnk** [comment]
You mean this one? https://fontawesome.com/icons/ban?style=regular

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Warning: https://fontawesome.com/icons/exclamation-triangle?style=solid
Ban: https://fontawesome.com/icons/ban?style=solid

Hope it helps

Closing here

**Comment by LauGugli** [comment]
Thank you! I totally missed it! :(
