### ISSUE TITLE
CDN not serving minified all.min.css

### ISSUE THREAD

**Issue by lonix1** [FortAwesome/Font-Awesome#13554]
The [instructions say](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css) that the link is

````html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
````

But there is no equivalent `all.min.css` file.

What filename should I use?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The above file is already minified

Please take a look: https://use.fontawesome.com/releases/v5.1.0/css/all.css

Hope it helps

closing here

**Comment by lonix1** [comment]
@tagliala Lol... I didn't see `.min.` so naturally thought it was not minified. When I did check it my browser "unminified" it which added to the confusion. Thanks.
