### ISSUE TITLE
Multiple icons displaying instead of one

### ISSUE THREAD

**Issue by amachan** [FortAwesome/Font-Awesome#13568]
Hoping to use https://fontawesome.com/icons/file-signature?style=solid

However, it displays 
https://fontawesome.com/icons/file?style=solid
and
https://fontawesome.com/icons/sign?style=solid
with ature at the end instead.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

file signature has been introduced in FA 5.1.0 please make sure you are using the latest version of font awesome (5.1.1).

Hope it helps

Closing here
