### ISSUE TITLE
Icon request: Music Single Note

### ISSUE THREAD

**Issue by Legitti** [FortAwesome/Font-Awesome#13564]
### What can it be used for?

Music and to show Official YouTube Music Channel

You have music icon with double note, I would like to similar with single note.

### Icon request checklist

- [lock] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [lock] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [lock] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [unlock] I have included at least one example image if it could be helpful (optional)
- [lock] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by SorenSaket** [comment]
+1

**Comment by Legittti** [comment]
Thanks for the support, I would love to see this added.

**Comment by sensibleworld** [comment]
We've added this to 5.11:
https://fontawesome.com/icons/music-alt?style=solid
https://fontawesome.com/icons/music-alt-slash?style=solid
