### ISSUE TITLE
Icon request: fa-circle-quarter, fa-circle-three-quarters

### ISSUE THREAD

**Issue by mandymozart** [FortAwesome/Font-Awesome#1357]
A very common UI is to complete certain processes like filling in all data into your profile, or add a profile picture etc. etc.

Also usefull for progress tracking.

circle around and filling it up with black to the required percentage.

icon-progress-0
icon-progress-20
icon-progress-25
icon-progress-50
icon-progress-100

I suggest 5% increments, because that could be close enough

![td_graph_sm](https://f.cloud.github.com/assets/1228101/675012/67a16eca-d8e7-11e2-97e0-8ec1a24735aa.jpg)

thanks, and big up for the project.

**Comment by Grayda** [comment]
+1 for this, but in 25% increments, so:

fa-progress-0 (alias of fa-circle-o)
fa-progress-25
fa-progress-50
fa-progress-75
fa-progress-100 (alias of fa-circle)

Or, 

fa-circle-empty (alias of fa-circle-o)
fa-circle-quarter
fa-circle-half
fa-circle-three-quarters
fa-circle-full (alias of fa-circle)

These would be useful for things such as helpdesk tickets, where you want to indicate if a job is not yet started, started, half way done, almost done, and done.

![image](https://cloud.githubusercontent.com/assets/4891563/16608232/013937a8-438d-11e6-93f2-5e75c13e7773.png)

**Comment by tagliala** [comment]
Circle-empty: http://fontawesome.io/icon/circle-o/
Circle-half: http://fontawesome.io/icon/adjust/
Circle-full: http://fontawesome.io/icon/circle/

**Comment by Grayda** [comment]
It works for the most part, and here's a [pen that I whipped up](http://codepen.io/anon/pen/Eyvjgk). It looks good, except for the second example where there's a pixel or two of white

**Comment by aethior** [comment]
Hi @mandymozart,

[fa-circle-quarter](https://fontawesome.com/icons/circle-quarter), [fa-circle-half](https://fontawesome.com/icons/circle-half) and [fa-circle-three-quarters](https://fontawesome.com/icons/circle-three-quarters) icons have been added in v6.0.0-BETA1.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks

circle-quarter looks a litte bit off. https://fontawesome.com/icons/circle-quarter?s=duotone

@sensibleworld I've also checked in the buildsystem. This is mostly noticeable in duotone, when switching to a circle-half and back

Could you please take a look?

**Comment by sensibleworld** [comment]
Good eye, @tagliala! I've got a PR up to fix that. Things were off by .05 pixels :)
