### ISSUE TITLE
Does not working solid icon which is only available in solid for photoshop

### ISSUE THREAD

**Issue by harnishdesign** [FortAwesome/Font-Awesome#13572]
I am use font awesome latest Version 5.1.1. Does not work solid icon in photoshop. I have realized. **Does solid icon working which is available in Regular & solid. Does not working solid icon which is only available in solid for photoshop.**

have you face any this type issue?

I have install on desktop.

- Font Awesome 5 Brands-Regular-400.otf

- Font Awesome 5 Free-Regular-400.otf

- Font Awesome 5 Free-Solid-900.otf

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate.

Please make sure that you have installed the latest versions of Font Awesome (remove the font and install it again if you are uncertain and please double check that "solid" font style has been selected in the dropdown menu as showed in the screenshot

![image](https://user-images.githubusercontent.com/556268/42938379-5ef898ac-8b52-11e8-8199-3795be36b97c.png)

**Comment by tagliala** [comment]
One more thing...

If you still think there is an issue with font awesome, please open a new issue making sure that it follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
