### ISSUE TITLE
Library icon not available

### ISSUE THREAD

**Issue by raagoo** [FortAwesome/Font-Awesome#13573]
Please provide Library icon which is currently not available.
This will be very helpful.
Thank you

**Comment by raagoo** [comment]
Hi,

Thanks for taking this up.
I have updated details in below ticket. Please let me know if need further
details.
[FortAwesome/Font-Awesome] Library icon not available (#13573)Icon request:
icon-name #13584

**Comment by wolfy1339** [comment]
You didn't need to create a new issue. Editing this one and replying would have sufficed

**Comment by raagoo** [comment]
Sorry, realized it later :-)

**Comment by raagoo** [comment]
Thank you.
Please suggest when can I see it formally on https://fontawesome.com.

**Comment by tagliala** [comment]
@raagoo please take a look at these links:

- https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
- https://fontawesome.com/community/leaderboard/new
