### ISSUE TITLE
Skull font is not working 

### ISSUE THREAD

**Issue by rahulVerma27** [FortAwesome/Font-Awesome#13574]
### Title

Font skull isn't loading (class="fas fa-skull") 

### How I got this bug? 

I was searching for a skull font for use in my web page. I copied the above HTML <i> tag.But, when I used it in HTML code, it didn't worked :(

I want to use it. Please could you make it available soon? 

### Version and Implementation 

Version: 5.0.6
Implementation: https://use.fontawesome.com/releases/v5.0.6/css/all.css
Browser and version: 67.0.3396.87

- Web Fonts with CSS

### Reproducible test case

https://codepen.io/Rahul_V7/pen/WKGLaW

- I have filled out as much of the above information as I can
- I have included a test case because my odds go _way_ up that the team can fix this when I do

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-skull](https://fontawesome.com/icons/skull?style=solid) has been introduced in version 5.0.13. Please upgrade

https://codepen.io/anon/pen/EpNxQM

Hope it helps

Closing here

**Comment by rahulVerma27** [comment]
Hi Geremia,

My problem has been solved and the "skull" font is now visible. I
appreciate your support.

Thanks!

**Comment by tagliala** [comment]
You're welcome 👍
