### ISSUE TITLE
Problems  "font-family: 'Font Awesome\ 5 Free'" and content: "\f01d" 

### ISSUE THREAD

**Issue by EddyMejia** [FortAwesome/Font-Awesome#13588]
I tried this on the following jsfiddle.net link https://jsfiddle.net/tgzouajm/989/
by changing the CSS to 

.star:before {
	font-family: 'Font Awesome 5 Free';
	content: "\f01d";
       font-weight: 900;
}
.star-s:before {
	font-family: 'Font Awesome 5 Free' !important;
	content: "\f01d";
       font-weight: 900;
}

and I still get the little square icons instead of the "fa-play-circle-o". Am I missing something?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> and I still get the little square icons instead of the "fa-play-circle-o

Please note that outlined icons like [play-circle-o](https://fontawesome.com/v4.7.0/icon/play-circle-o) were replaced by regular icons in FA5

Plese refer to the new documentation available at [play-circle](https://fontawesome.com/icons/play-circle?style=regular) 

https://jsfiddle.net/tagliala/tgzouajm/995/

Hope it helps

Closing here
