### ISSUE TITLE
Icon request / change request: plane-arrival-wheels

### ISSUE THREAD

**Issue by Neyschka** [FortAwesome/Font-Awesome#13587]
### What can it be used for?

plane-arrival currently looks a bit too much like plane-crashing, any chance of a version with wheels visible?

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Added some wheels! https://fontawesome.com/v6.0/icons/plane-arrival?s=solid
