### ISSUE TITLE
Icon Request: fa-h4c-k3r

### ISSUE THREAD

**Issue by H4C-K3R** [FortAwesome/Font-Awesome#13598]

**Comment by H4C-K3R** [comment]
Please make icon of 

https://h4c-k3r.github.io

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please do not link your website or github repository and provide information about your brand

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by shoulders** [comment]
this should be closed

**Comment by tagliala** [comment]
No feedback, closing here
