### ISSUE TITLE
Icon request: fa-native

### ISSUE THREAD

**Issue by abhimanyusingh** [FortAwesome/Font-Awesome#13594]
I need an icon of native like this one

![native](https://user-images.githubusercontent.com/3057450/43031149-c2076e24-8c69-11e8-974b-7b4f60075f3f.png)

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That example does not represent "native", it is more like a "page layout", so I'm going to consider this a duplicate of #6100, please +1 that request
