### ISSUE TITLE
icon-spin-counterclockwise?

### ISSUE THREAD

**Issue by zglennie** [FortAwesome/Font-Awesome#1360]
Hey, thanks for the Awesome work!

I was just trying to put some icon-cogs together into a chain and I realized that there doesn't seem to be a counter-clockwise spin option available. Could this be included in a future release?

**Comment by BlaM** [comment]
:+1:

**Comment by alonsotorres** [comment]
I support this enhancement. Just happened I needed it on a project. :+1:

**Comment by sensibleworld** [comment]
This has been enhanced! https://fontawesome.com/v6.0/docs/web/style/animate#spin
