### ISSUE TITLE
Outdated files maybe to remove

### ISSUE THREAD

**Issue by amurzeau** [FortAwesome/Font-Awesome#13601]
Hi,

I found that some folders that were not updated in 5.1.x releases and were renamed [0]:
- advanced-options/use-with-node-js/fontawesome-free-brands -> free-brands-svg-icons
- advanced-options/use-with-node-js/fontawesome-free-solid -> free-solid-svg-icons
- advanced-options/use-with-node-js/fontawesome-free-regular -> free-regular-svg-icons
- advanced-options/use-with-node-js/fontawesome-free-webfonts -> fontawesome-free
- advanced-options/use-with-node-js/fontawesome

Also, these files have been renamed [1]:
- web-fonts-with-css/css/fa-brands{,.min}.css -> brands{,.min}.css
- web-fonts-with-css/css/fa-regular{,.min}.css -> regular{,.min}.css
- web-fonts-with-css/css/fa-solid{,.min}.css -> solid{,.min}.css
- web-fonts-with-css/less/fa-brands.less -> brands.less
- web-fonts-with-css/less/fa-regular.less -> regular.less
- web-fonts-with-css/less/fa-solid.less -> solid.less
- web-fonts-with-css/less/fa-brands.scss -> brands.scss
- web-fonts-with-css/less/fa-regular.scss -> regular.scss
- web-fonts-with-css/less/fa-solid.scss -> solid.scss

Shouldn't them be removed from git now ?
If so, maybe the process of updating git need to handle the "delete files not in the new release" case. 

[0] https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#renamed-packages
[1] https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#510-to-511

**Comment by InsanityMeetsHH** [comment]
They shouldn't removed from git.
1. Because of people how needs an old version
2. Removing files would cause a version raise to FA 6

https://github.com/FortAwesome/Font-Awesome#versioning

**Comment by amurzeau** [comment]
On July 23, 2018 9:21:19 AM GMT+02:00, InsanityMeetsHH <notifications@github.com> wrote:
>They shouldn't removed from git.
>1. Because of people how needs an old version

Older revisions can still be retrieved from git, and these folder doesn't match the current 5.1.1 available packages.
Are there actual projects that uses old, non updated  files while using git master branch ?

>2. Removing files would cause a version raise to FA 6

To my understanding, these folder were renamed in 5.1.1, so old paths are not in the current version. In that case, why a major version change is needed to remove them ?
Maybe related to projects using git master branch and who wants to keep the old folder anyway ?

>
>https://github.com/FortAwesome/Font-Awesome#versioning



-- 
Alexis Murzeau

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> They shouldn't removed from git.

They shouldn't but there has been a breaking change in version 5.1, so it makes sense to remove the old files, but I don't know if there is a reason to keep both.

Old files will be available in the versioned trees: https://github.com/FortAwesome/Font-Awesome/tree/5.0.13

@robmadole any thoughts?

**Comment by robmadole** [comment]
Yeah, I'm going to remove the old ones. Hang tight.

**Comment by robmadole** [comment]
#13608 takes care of this.

**Comment by robmadole** [comment]
Thanks @amurzeau
