### ISSUE TITLE
Icon request: fa-gravecross

### ISSUE THREAD

**Issue by TheMouster** [FortAwesome/Font-Awesome#13610]
It would be helpful to have an icon to represent deceased entities. Something along the lines of these;

![cross-001](https://user-images.githubusercontent.com/4576167/43116875-832ca946-8f3c-11e8-8276-259ff15b1a68.jpg)
![cross-003](https://user-images.githubusercontent.com/4576167/43116877-84ec2608-8f3c-11e8-89b9-537b812c3c60.jpg)

**Comment by aethior** [comment]
Hi @elmouster,

[fa-cross](https://fontawesome.com/icons/cross) icon was added in v5.3.0.
[fa-tombstone](https://fontawesome.com/icons/tombstone) icon was added in v5.4.0.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
I feel a little bit uncomfortable adding just the halloween category to this request, but ok

**Comment by aethior** [comment]
> I feel a little bit uncomfortable adding just the halloween category to this request, but ok

I think you can also use `religion` category. 👍

**Comment by tagliala** [comment]
Thanks, I will raise this discussion internally
