### ISSUE TITLE
Icon request: aeternum-network brand Icon

### ISSUE THREAD

**Issue by AeternumStudios** [FortAwesome/Font-Awesome#13611]
### What will it be used for?

I am currently developing an extensive platform allowing kids to make money doing freelance development, mainly web, while introducing them to production like environments, but still engage them to have fun and learn faster, better and stronger. >:P The Icon would be my platforms logo. I can and will provide the vectors needed, the icon would be used across our platform, including the websites, api, electron webapp, etc, and also allows the content creators to easily brand their work if they desire, (alot of them really do) While this is 100% not necessary, it would be extremely cool, and would allow for easier branding and marking, since everyone already uses fontawesome, and helps us avoid this:
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABG2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+Gkqr6gAAAYJpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZG7SwNBEIe/JErEVwQtRCyCqI1RYoSgjUWCL1CLJIJRm+TMQ8jjuEuQYCvYCgqija9C/wJtBWtBUBRBLKysFW1UzrlESBCzy+58+9uZYXYWrKGUktZr3JDO5LTAhM85H15w2p+xy2ymj46IoqszwfEQVcfHHRbT3vSbuar7/TsalmO6ApY64VFF1XLCk8LTqznV5G3hNiUZWRY+FXZpUqDwralHS/xicqLEXyZroYAfrC3CzkQFRytYSWppYXk53elUXvmtx3xJYywzFxTbJasTnQAT+HAyxRh+vAwyIruXfjwMyIkq8e5i/CxZiVVkVymgsUKCJDlcouYle0xsXPSYzBQFs/9/+6rHhzyl7I0+qH0yjLcesG/B96ZhfB4axvcR2B7hIlOOzx7A8Lvom2Wtex8c63B2WdaiO3C+Ae0PakSLFCWbLGs8Dq8n0BSG1muoXyz17Pee43sIrclXXcHuHvSKv2PpB2BwZ+PzUktQAAAACXBIWXMAAAsTAAALEwEAmpwYAAACbklEQVRYhe2Wu2tUQRTGfydECVHYmCgIAfXYKLKdhVia2kpQ8B/QNIoRJFgoiAgqCtlGDCkEQQtf2Fj5KEWEFCoRUdhZlKAW2cQX+Fh3LOZes/fuvXcmu0WafLDFzHzn+86emTN3YAXLDAlmGtsDTADrPMx5VI6GyvYGJwCngSNBTGPnUDkTQg2rgLFrgTqwKogPv4EhVL77iD2BgjeXYA6wGrgRQvRXwNgy8DKIm4QFyqi8LiKFVOBOB+ZEMXd9pOIEjD0IbOvAPMb2SCMX+f/MtV0dKHWRAMAXYBCVZtZiUQUuBpj/iX5FKAEX8hazK2DseuAD0OcRr0Ya6uH9BIZRqacX8ipwK8Ac4ACwP4DXB9zOWmhPwNhdwJ4A0YeoTKMyDTwK4I9E2gm0b4GxNWCzR6wBbEBlIYoZBD7jv9prqCS2K1kBY0cDzAEm/psD0d5WAuK2YOzh1onFChjbi2uZfo/IAu6eT7aVa9s5YMAT/wMYQKUByQpMBpgDHMrsaTc3GhC/BrgaD1wFjB0G3uO/mmdQKRcyjJ0Bdnh0msAmVGbjQ1MC/noS+Arcx9iqR7w/MijSEmArMNt6Bs4D4wVBx4DrwDtgyJOED89Q2U0qy3O4VsrCG+AKKvPAqS7Nm8C+eLCYgMo34GRO0Bgq8Z0/BbzqIoFrqHyMB8mLyLXSc2Bny+wDVPameCPA4w7MEy0I6YPiWqn1RdsAjrfJqDwB7nWQwFireXsCTvwp7g0IUEHlbY7YCeDXEsxrqEylJ/NaZRyoAWdz5VSqwOVAc4v7crah6EW0EZVPhbLuuV7BvYKL8AKVSx7OCpYH/wC9/JT0UJh5awAAAABJRU5ErkJggg==">`

Im sure this request comes up alot, and its a request I would gladly pay for if need be, but it would be immensely useful, and also bragging rights? (Yes FA is that cool we get to brag if we get our logo added. :^)
 Appreciated, and I promise i'm aware of how unrealistic a personalized branding request is.

### Image and vector

[aeternum_network.zip](https://github.com/FortAwesome/Font-Awesome/files/2222942/aeternum_network.zip)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by pelleknaap** [comment]
It would great if we could have this turned into an icon.

**Comment by Muijf** [comment]
+1 this would be great! 👍

**Comment by PhilMarlin** [comment]
Please do this.

**Comment by AaronStrange3** [comment]
This would be awesome as an icon

**Comment by Enscivwy** [comment]
Would be great

**Comment by AeternumStudios** [comment]
Project evolved, Branding has changed, larger company started, Requesting updated icon via new issue.

**Comment by tagliala** [comment]
@AeternumStudios please edit this request, otherwise upvotes will be lost
