### ISSUE TITLE
Icon request: fa-laurel-wreath (Greek Olympics)

### ISSUE THREAD

**Issue by onkarjit** [FortAwesome/Font-Awesome#13613]
A laurel wreath is a symbol of victory and honour. In Greek mythology, Apollo is represented wearing a laurel wreath on his head. In ancient Greece, wreaths were awarded to victors, both in athletic competitions, including the ancient Olympics

A Laurel Wreath icon would be nice for games that have tournaments/competitions.

My idea is that it's best to make three icons one for the left Laurel leaf, right Laurel leaf and one icon that has them both as in the examples below.

![4ca1d5daf9d24d341fe3f9d346bb98ba](https://user-images.githubusercontent.com/26631593/43191619-ce52721a-8ffb-11e8-94d9-4b1766df427b.jpg)

![unknown-1](https://user-images.githubusercontent.com/26631593/43191664-ea392ea6-8ffb-11e8-9a76-399be877f7f7.png)

![unknown-2](https://user-images.githubusercontent.com/26631593/43191673-ee1e65ae-8ffb-11e8-9bc6-87ad37689793.png)

![laurel-wreath-stencil](https://user-images.githubusercontent.com/26631593/43191682-f25097b4-8ffb-11e8-8f02-c8df70283fc4.jpg)

**Comment by JoshuaDoshua** [comment]
Older related (for votes)
#7855

**Comment by aethior** [comment]
> Older related (for votes) #7855

@tagliala related or duplicate?

**Comment by tagliala** [comment]
I would say a duplicate, closing here, thanks
