### ISSUE TITLE
route-highway and route-interstate reversed

### ISSUE THREAD

**Issue by frigmous** [FortAwesome/Font-Awesome#13621]
The route-highway icon is the shape of a U.S. interstate sign, and the route-interstate icon is the shape of a U.S. highway sign.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@talbs @sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
@frigmous Thanks for the catch! We'll get this fixed up.

**Comment by frigmous** [comment]
Happy to help! Love me some Font Awesome!

**Comment by davegandy** [comment]
Great catch @frigmous. Thanks for the assist!

![hqdefault](https://user-images.githubusercontent.com/1076721/43264708-75893626-90ac-11e8-87d6-9a3ebd766d60.jpg)

**Comment by talbs** [comment]
Hey gang, thanks again for the heads up. 

This has been fixed and is now released as part of version 5.3. 😄 

* https://fontawesome.com/icons/route-interstate?style=solid 
* https://fontawesome.com/icons/route-highway?style=solid

**Comment by frigmous** [comment]
Yay!
