### ISSUE TITLE
Icon request: Room plate

### ISSUE THREAD

**Issue by ChainMe** [FortAwesome/Font-Awesome#13637]
### What can it be used for?

Used for any accommodation services.

### Example image (optional)

![image](https://user-images.githubusercontent.com/41740433/43307301-642e614e-91b0-11e8-9eef-ad52012e5f22.png)

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I have to close this request.

While it doesn't specifically go against our contributing guidelines, it contains English text and we are trying to keep our icons as international as possible. Also, there are a lot of characters and they will not work at small font sizes

You can request the following icon:

![image](https://user-images.githubusercontent.com/556268/43276998-f7f75480-9106-11e8-8724-baf55f06c46c.png)

and then use the stacking feature to put the text you need inside

Feel free to edit the request and ping me and I will reopen

**Comment by ChainMe** [comment]
@tagliala I edited the request, can you please check whether it comply with the guidelines or not

**Comment by tagliala** [comment]
@ChainMe thanks. Could you please fix the title? It should describe the object that the icons represent

**Comment by ChainMe** [comment]
@tagliala  done

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
