### ISSUE TITLE
fa-layer-group does not render/display

### ISSUE THREAD

**Issue by tthorp** [FortAwesome/Font-Awesome#13638]
To recreate, setup fontawesome 5.1.1 on a page downloaded from the CDN and insert the icon. For me, it doesn't show an icon. Other icons work fine on page. I have not tested other releases of FA.

https://use.fontawesome.com/releases/v5.1.1/css/all.css
<i class="fas fa-layer-group"></i>

Thanks!

Tim

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[layer-group](https://fontawesome.com/icons/layer-group?style=solid) has been introduced in version 5.2.0

Please upgrade

Hope it helps

Closing here
