### ISSUE TITLE
fa-user-minus

### ISSUE THREAD

**Issue by Preeti-Kala** [FortAwesome/Font-Awesome#13634]
### Describe the problem

fa-user-minusfont awesome is not working in any browser.

### What did you expect?

fa-user-minus is a font icon available in the set of free font awesome. we are using font awesome in our project . rest of the icons are working well except this one. Need the help to fix this.

### What version and implementation are you using?

Version: fa-version : 5.0.8
Browser and version: 

- [ ] SVG with JS
**- [ ] Web Fonts with CSS** - using this one
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by Preeti-Kala** [comment]
I am using font awesome version 5.0.8 in my project. Now how to update the version to 5.2.0 via git bash or npm ? please suggest a way. as version 5.2.0 has introduced some new icons which we need.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[user-minus](https://fontawesome.com/icons/user-minus?style=solid) has been introduced in version 5.0.11 so it will not work on 5.0.8.

Please upgrade

> I am using font awesome version 5.0.8 in my project. Now how to update the version to 5.2.0 via git bash or npm ? please suggest a way. as version 5.2.0 has introduced some new icons which we need.

If you are using the npm package, there is a breaking change, please check : https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

(basically you have to replace  `fontawesome-free-webfonts` with `fontawesome-free`)

Hope it helps

Closing here
