### ISSUE TITLE
Icon brain does not work

### ISSUE THREAD

**Issue by jjodx** [FortAwesome/Font-Awesome#13643]
Hello,

I am using the following code to include a brain icon (fas fa-brain) in a Rmarkdown website:

 
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
 
<i class="fas fa-camera-retro"></i>
<i class="fas fa-brain"></i>
```
 

I can see the camera icon on my website but not the brain icon. Why is this?

Thanks
JJ

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: http://jsfiddle.net/tagliala/m6a4ot01/3/

Please make sure that there isn't a plugin/component/theme loading an older version of font awesome.

If you still think there is an issue with font awesome, please provide a reproducible test case

Hope it helps

Closing here

**Comment by jonfairbanks** [comment]
For anyone else facing this issue, upgrade from 5.1.0 to 5.2.0. Evidently the brain is new. 😸

**Comment by tagliala** [comment]
@jonfairbanks yes, it is

https://fontawesome.com/icons/brain?style=solid

Please check the version number as in the picture below

![image](https://user-images.githubusercontent.com/556268/44483939-af164e00-a64c-11e8-841c-71755f8c9555.png)

**Comment by jonfairbanks** [comment]
Totally missed that. Thanks @tagliala!
