### ISSUE TITLE
Icon request: fa-question-alt

### ISSUE THREAD

**Issue by mvanroon** [FortAwesome/Font-Awesome#13646]
### What can it be used for?

I'd love to see an different style of question mark icon. One that better matches the design of `times` and `check`. Like the current `question-circle`, but without the circle.

### Example image (optional)

![schermafbeelding 2018-07-27 om 17 10 28](https://user-images.githubusercontent.com/1309448/43329208-08c8d798-91c0-11e8-9a42-eadc346cacc2.png)

### Icon request checklist

- [x] This is a single icon (although I can imagine that it could be combined with an `exclamation-alt`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
With version 6, these icons have been standardized.
