### ISSUE TITLE
Request: NuGet Package Update to Latest

### ISSUE THREAD

**Issue by mseminatore** [FortAwesome/Font-Awesome#13641]
@davegandy When you get a chance can you please update the NuGet package for FA?  I'd like to be able to use the new 5.2 icons.  Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole do we have an official nuget package?

Refs:
- #6067
- #6140
- #7213

**Comment by mseminatore** [comment]
@tagliala @davegandy Yes, it at least appears that you do.  It was posted to NuGet by [Tieson Trowbridge](https://www.nuget.org/profiles/tieson.trowbridge) and last updated about a month ago.  Authors listed are Tieson Trowbridge and Dave Gandy.  [Here ](https://www.nuget.org/packages/Font.Awesome/)is the link to the package.

I am using this and appreciate the package availability.  Love the project, keep being Awesome!

Thanks!

**Comment by robmadole** [comment]
We don't actually maintain that package. You might contact the maintainer and ask them to do that @mseminatore

**Comment by mseminatore** [comment]
OK, I've contacted Tieson via NuGet.  However, you should be able to see that @davegandy is listed as one of the maintainers for the NuGet package.  And Dave is listed as an official maintainer of Font.Awesome in your README.md.  Is Dave no longer an active maintainer of FA?

**Comment by tagliala** [comment]
@mseminatore Dave is listed as author, which is correct, but not as owner.

We don't own that package, please try to get in touch with the owner

**Comment by tagliala** [comment]
@mseminatore you can mention him here: https://github.com/FortAwesome/Font-Awesome/issues/7213#issuecomment-390063831

**Comment by mseminatore** [comment]
Thank you, done!
