### ISSUE TITLE
Icon request: speaker (music)

### ISSUE THREAD

**Issue by theo0165** [FortAwesome/Font-Awesome#13654]
### What can it be used for?

Can be used for everything from webshops to opening a sound output menu in for example linux.

### Example image (optional)

![speaker](https://i.gyazo.com/1db6693944268ff3bfe07ec1b80c340a.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do https://fontawesome.com/icons/volume-up?style=solid or https://fontawesome.com/icons/volume-down?style=solid fit your use case?

**Comment by anthonylucio** [comment]
i echo this request! :)

**Comment by sensibleworld** [comment]
We now have some speaker icons in 5.11:
https://fontawesome.com/icons/speaker?style=solid
https://fontawesome.com/icons/speakers?style=solid
https://fontawesome.com/icons/computer-speaker?style=solid

**Comment by theo0165** [comment]
Forgot i even made this, thank you so much for this! 😃🙏
