### ISSUE TITLE
5.2 TTF/OTF fonts say version 5.1.

### ISSUE THREAD

**Issue by brentdanley** [FortAwesome/Font-Awesome#13667]
The version of the TTF fonts whenever I've downloaded the new 5.2 fonts--including forking this repo-- say version 5.1. I want the brain, `f5dc`, but it's not there. 

`Font-Awesome/web-fonts-with-css/webfonts/`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The version is wrong, but the file definitely belongs to the 5.2.0 version

PS: If you need to use the font on a desktop, please use the `.otf` version because `.ttf` is optimized for the web

![image](https://user-images.githubusercontent.com/556268/43422660-b90b2908-944a-11e8-83b1-b1f85b25b5ae.png)

**Comment by brentdanley** [comment]
Thank you, @tagliala. Any chance it's an issue with Pro?

<img width="873" alt="brain" src="https://user-images.githubusercontent.com/361306/43424077-32e2794a-941c-11e8-9db3-eeb50da2f618.png">

**Comment by brentdanley** [comment]
Bloody hell. Sorry, mate. I opened the page in Chrome after you verified the version and voila! Then I disabled caching in Firefox Dev Edition and refreshed. Again, voila! 

If there an "fa-embarrassed" icon? 

Thank you.

**Comment by tagliala** [comment]
Don't worry, glad you've solved

**Comment by tagliala** [comment]
Reopening here because the wrong version number is actually a bug

**Comment by giagam** [comment]
Just to confirm that the version number only, not the file, is wrong. Bye.
![screen shot 2018-07-31 at 11 53 46](https://user-images.githubusercontent.com/4989128/43454839-7a0378ea-94be-11e8-9dc1-83723d6d8d95.png)
![screen shot 2018-07-31 at 12 44 52](https://user-images.githubusercontent.com/4989128/43455348-cc8f130c-94bf-11e8-84b4-b45c5d77a8ca.png)

**Comment by robmadole** [comment]
We've got a fix for this in our builds now. This will go out in 5.3.0.

**Comment by dscottfont** [comment]
@giagam - how do you currently have your symbol setup in sketch? based on your screenshot it appears you have a FA icon as the symbol, and the overr ride "brain" is displaying the brain icon. I've always had FA icons appear as a [?] when applying to a symbol....
