### ISSUE TITLE
Icon request: TripAdvisor

### ISSUE THREAD

**Issue by senlin** [FortAwesome/Font-Awesome#1366]
TripAdvisor® is the world's largest travel site and massively popular in the hospitality industry and the people working in that industry are aware of that too.

Many restaurateurs and people working or hotels have verified profiles on TripAdvisor, so it would be really helpful to be able to add the logo as a font icon.

I have looked around a bit for a suitable image and on the tripadvisor site itself they seem to be a bit anal about giving an open link to a vector image. But via Google I found a large png file, hopefully that is suitable for making an icon font: http://5to9branding.files.wordpress.com/2012/01/tripadvisor.png

Hopefully you can add this to milestone 4 :)

**Comment by nathanmarks** [comment]
+1

**Comment by ahtaha** [comment]
+1

**Comment by jameswilson** [comment]
Please stop +1'ing this issue.  The correct issue to follow is #412.
