### ISSUE TITLE
Missing Icons in angular package

### ISSUE THREAD

**Issue by matt-chadbourne** [FortAwesome/Font-Awesome#13666]
Recently there have been a few icons that we've been wanting to use for our angular-based web app but haven't been able to, seeing that the icons are nowhere to be found in the node_modules.

We are currently using the latest _angular-fontawesome_ package and can see many icons in each of the weights, including brands. However, there are many that are missing entirely.

A few that we've wanted to use, in various weights, are:

- globe-asia
- globe-americas
- globe-africa
- grip-horizontal
- file-upload
- file-import

Is there something wrong with the implementation or are these simply not available for use yet. If the answer is the latter, they should be labeled as unavailable on your site.

**UPDATE**: Another thing to note is that none of these appear in the FA5 desktop font either.

**UPDATE 2**: We found the issue and it's been resolved.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not an angular developer but if I'm correct `angular-fontawesome` is just the angular component for font awesome.

You should still use the basic fontawesome packages: `fontawesome-free`, if you are using webfont and `fontawesome-svg-core` plus others if you use the SVG framework

Please make sure that you are using Font Awesome 5.2.0

Upgrading reference: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510

Does this help?

**Comment by matt-chadbourne** [comment]
@tagliala We are using the Font Awesome Pro 5.2.0 and things have been great!

My team and I have just began to notice that there some icons that are listed within the FA icon gallery (which are listed in my initial post) that are simply unavailable to us, even with the pro license and the latest angular-fontawesome package installed. AND they are also not included in the core font-family that can be installed on our desktop.

Again, if these are simply unavailable at the moment, that's fine; they should just be labeled as such.

**Comment by tagliala** [comment]
> Again, if these are simply unavailable at the moment, that's fine; they should just be labeled as such.

Could you please provide an example of icon that it is not available to you?

PS: since this is related to FA5 Pro, could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
