### ISSUE TITLE
Wrong class for comments-dot and comment-alt

### ISSUE THREAD

**Issue by qcoumes** [FortAwesome/Font-Awesome#13669]
The FA website give the class *-comment-dots* for the [comment dots icon](https://fontawesome.com/icons/comment-dots?style=regular) (which make sense), but it does not work. Instead, using the class *-comment-alt* display the comment dots icon instead of the [comment alt icon](https://fontawesome.com/icons/comment-alt?style=solid)]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the breaking change in the appearance, but comment-dots and comment-alt were switched in version 5.0.9, so I guess you are probably using FA <= 5.0.8

Please make sure that you are using the latest version of Font Awesome

Hope it helps

Closing here

Ref: https://github.com/FortAwesome/Font-Awesome/issues/12829#issuecomment-380846121
