### ISSUE TITLE
font family clashing via webfonts

### ISSUE THREAD

**Issue by gareth-gillman** [FortAwesome/Font-Awesome#13674]
I am using 5.2.0 and trying to pseudo elements, which don't work in FF 61 & Chrome 67, I get the missiing icon symbold in both browsers.

my code is:

```
.div:after {
 font-family:"Font Awesome 5 Free";
 content:"\f107";
}
```

I then opened fontawesome-all.css and looked at the @font-family calls, and there are 2 calls to the same font-family name, which is Font Awesome 5 Free.

I changed line 3662 to "Font Awesome 5 Solid" and my icons worked.

I don't know the ins and outs of why the icons don't work but i guess the clashing of names is confusing the browsers, this was happening on 5.1 as well, i upgraded to 5.2 to check to see if it still happened.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I changed line 3662 to "Font Awesome 5 Solid" and my icons worked.

This is the proper usage for the SVG Framework. So you are probably using the SVG Framework

If you are using the CSS version, you should go for

```
.div:after {
 font-family:"Font Awesome 5 Free";
 content:"\f107";
 font-weight: 900;
}
```

Example: http://jsfiddle.net/tagliala/m6a4ot01/5/

Hope it helps

Closing here

Ref:
- CSS https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements
- SVG https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements
