### ISSUE TITLE
How to ignore replacement to svg of specified element.

### ISSUE THREAD

**Issue by 4lex-gs** [FortAwesome/Font-Awesome#13677]
I am trying to use simplemde with Font Awesome 5 Pro.

FA5 replaces all element which has `fa` class.
It makes some problem to element generated by javascript library which has not FA5 capability.

Is there any way to skipping auto replacement on specified element?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue but at the moment there isn't a solution.

Let's continue on #12437
