### ISSUE TITLE
401 Unauthorized: @fortawesome/fontawesome-free@latest

### ISSUE THREAD

**Issue by azbatuk** [FortAwesome/Font-Awesome#13682]
Hello,

When I run "npm install --save-dev @fortawesome/fontawesome-free", 
NPM returns "401 Unauthorized: @fortawesome/fontawesome-free@latest" error.

Ubuntu 18.04.1
NPM 6.2.0

Thanks,

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate

Are you a Font Awesome Pro user? Could you please check that your `.npmrc` does not contain `@fortawesome:registry=https://npm.fontawesome.com/`?

npm 6.2.0
node 10.8.0
osx

```
$ npm install --save-dev @fortawesome/fontawesome-free
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN npm-fa-free@1.0.0 No description
npm WARN npm-fa-free@1.0.0 No repository field.

+ @fortawesome/fontawesome-free@5.2.0
added 1 package from 6 contributors and audited 1 package in 2.104s
found 0 vulnerabilities
```

**Comment by sajcics** [comment]
I had the same issue on Ubuntu 18.04. I tried to remove fontawesome from the project and install it again, and then I realize that I had a global .npmrc file (/home/<user>/.npmrc) which only containes `@fortawesome:registry=https://npm.fontawesome.com/`. I guess, for that reason font-awesome thinks that you have a pro version. Just access to global .npmrc file and comment all lines. And you good to go. I hope it helped.
