### ISSUE TITLE
Icon Request: A goodbye hand wave for log out screens!  

### ISSUE THREAD

**Issue by ScottMillerWesCoas** [FortAwesome/Font-Awesome#13687]

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [👋](https://emojipedia.org/waving-hand-sign/) U+1F44B Waving Hand Sign

**Comment by idoshkedi** [comment]
This is by far the most useful and important hand- icon (more than hand-rock, hand-paper, hand-scissors and hand-lizard..). Please add it already.

**Comment by cesc1989** [comment]
Wish this existed 😄 

I'm using `fas fa-power-off` instead. 🤷‍♂️

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/17734#issuecomment-810431660

**Comment by yhacohen** [comment]
Here's how I do it (a workaround...):
`<span class="fal fa-stack">
    <i class="fal fa-wifi fa-stack-1x" style="font-size: .6em; transform: rotate(102deg) translate(0, -14px);"></i><i class="fal fa-wifi fa-stack-1x" style="font-size: .6em; transform: rotate(280deg) translate(0, -13px);"></i>
    <i class="fas fa-hand-paper fa-stack-1x" style="transform: rotate(15deg); color: #fff;"></i>
    <i class="fal fa-hand-paper fa-stack-1x" style="transform: rotate(15deg);"></i>
</span>`
