### ISSUE TITLE
Typo or for purpose?

### ISSUE THREAD

**Issue by Janatbek** [FortAwesome/Font-Awesome#13689]
To install 5.2.0 you have to run this command
```npm install --save-dev @fortawesome/fontawesome-free```
but why the folder called fo```r```tawesome? with ```R``` instead of ```T```?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Not a typo. The organization name is Fo`r`t Awesome

https://twitter.com/fontawesome/status/420609150360375296

Hope it helps

Closing here
