### ISSUE TITLE
comment-alt shows comment-dots

### ISSUE THREAD

**Issue by ITOffcie** [FortAwesome/Font-Awesome#13684]
### Describe the problem

When I insert the comment-alt (Regular) icon I get to see the comment-dots icon

### What did you expect?

I expected to see the comment-alt regular icon the semi sqaure text balloon.

![schermafbeelding 2018-07-31 om 16 04 04](https://user-images.githubusercontent.com/9615240/43464430-668df5de-94db-11e8-9a75-1fb97d8690ce.png)

### What version and implementation are you using?

Version: 5.1.1 Pro
Browser and version: N/A

It's not in the browser, its on my Mac (macOS: 10.13.6) in Sketch (51.1)

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [X] On the Desktop

### Reproducible test case

![schermafbeelding 2018-07-31 om 16 01 03](https://user-images.githubusercontent.com/9615240/43464279-fccd879a-94da-11e8-81de-672c09453303.png)

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the breaking change in the appearance, but comment-dots and comment-alt were switched in version 5.0.9, so I guess you are probably using FA <= 5.0.8

Please make sure that you are using the latest version of Font Awesome

Hope it helps

Closing here

Ref: #12829 (comment)

**Comment by ITOffcie** [comment]
I was using 5.0.8, but after encountering this issue I updated to the 5.1.1 version.. And it still occurs

**Comment by tagliala** [comment]
Please remove the old font and reinstall

**Comment by ITOffcie** [comment]
Hello Tagliala,
That worked, thank you. Although I had to remove the font, reboot my mac, and install the font.
