### ISSUE TITLE
React stamp icon

### ISSUE THREAD

**Issue by sasharili** [FortAwesome/Font-Awesome#13693]
When I try to import the solid stamp icon I get this error:
`index.js:2178 ./src/helpers/fontawesome_library.js
4:205-212 '@fortawesome/free-solid-svg-icons' does not contain an export named 'faStamp'.`

I use the React component of the font and I import it in the library as `faStamp`.

Version: 5

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fa-stamp` has been introduced in version 5.1.0: https://fontawesome.com/icons/stamp?style=solid

Please make sure that you are using the latest version of font awesome (check your package.json's lock file)

Please also take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510
