### ISSUE TITLE
Masking & Layering are misslinked on Stacked Icons page

### ISSUE THREAD

**Issue by kiler129** [FortAwesome/Font-Awesome#13695]
### Describe the problem
I'm not sure if this is a right place to report bugs on the website itself, however I found something small.
On the page https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons you have "Our SVG + JS framework includes powerful ways to mask and layer". The word "mask" links to https://fontawesome.com/how-to-use/on-the-web/styling/layering while "layer" links to https://fontawesome.com/how-to-use/on-the-web/styling/masking.

### What did you expect?
Links should be swapped

### What version and implementation are you using?
N/A

### Reproducible test case
N/A

**Comment by talbs** [comment]
Thanks for the heads up, @kiler129. We'll get these crossed wires uncrossed shortly!

**Comment by talbs** [comment]
Thanks again for the help, @kiler129. These mixed up links are fixed now on https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons. 😄
