### ISSUE TITLE
Icon request: icon-bed

### ISSUE THREAD

**Issue by Mattvic** [FortAwesome/Font-Awesome#137]
Travel sites often need icons for traveling (airplane), sightseeing (camera) and accommodation (bed?). The airplane and camera are included in most font icon sets, but I haven´t fount one with a bed or an hotel icon. This would be a great addition.

Some examples:
http://www.istockphoto.com/stock-illustration-17443647-mobico-icons-hotel.php?st=b70dc83
http://www.civitatis.es/imagenes/iconos/viajeMini.png

**Comment by redben** [comment]
AIGA has some "standard symbols" for such things  http://www.aiga.org/symbol-signs/

**Comment by AndyWaters** [comment]
+1 For Bed
+1 Shower
+1 Bath/Spa
+1 Car Park Space ( Car )
+1 Boat ( Or Boat Berth )
Thank You

**Comment by mackski** [comment]
+1 Please bed, bath, any idea on a timeline for these?

**Comment by nathanwaters** [comment]
+1 Bed
+1 Bath
+1 Garage

Was surprised they weren't in the pack. Trying to find an alternate icon pack with them...

**Comment by TimothyGu** [comment]
@mackski FA is free. Nobody is payed for adding icons. So, no, no timeline.

**Comment by danniejpt** [comment]
+1 Please

**Comment by davegandy** [comment]
Bed icon added to 4.3.0-wip branch. Closing. Other icons you're looking for should be included in other issues.

**Comment by mitchelldemler** [comment]
Thanks Dave!

**Comment by simonmilz** [comment]
awesome! thanks for that!

**Comment by kliakos** [comment]
Many thanks, waiting for 4.3 to be released soon!

**Comment by AndyWaters** [comment]
Thank you

**Comment by CtrlF5** [comment]
Very much appreciated :)

**Comment by nblackburn** [comment]
Thanks @davegandy

**Comment by xitude** [comment]
Sweet.
