### ISSUE TITLE
Icon request: money-deposit

### ISSUE THREAD

**Issue by rent-is** [FortAwesome/Font-Awesome#13701]
### What can it be used for?

icon which indicates a deposit is paid>
eg renting a car, deposit must be paid,

### Icon request checklist

Might be handy to have 2 seperate icons
with lock locked = money in deposit
with lock open = money is retuned from deposit 

- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you basically asking for the following icons?

http://jsfiddle.net/tagliala/9tercwpy/34/

**Comment by sensibleworld** [comment]
We have a [lot of icons](https://fontawesome.com/search?q=money&o=r&s=solid&f=classic) that might work for this now, as well as new options that you can create with the Icon Wizard. [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
