### ISSUE TITLE
Some icons not showing on Chrome Version 68.0.3440.84 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by rangka-kacang** [FortAwesome/Font-Awesome#13703]
I wonder why some of the icons for example:

https://fontawesome.com/icons/share?style=solid
https://fontawesome.com/icons/share-alt?style=solid

They do not show up when I'm using the latest **Chrome Version 68.0.3440.84 (Official Build) (64-bit)** but it will render properly using **Microsoft Edge 42.17134.1.0**. I have not tested on other browsers yet. I'm on Windows 10 Pro 17134.165.

I first realized this when I saw a broken icon on my WHMCS "Transfer Domains" sidebar links:

https://whmcs.community/topic/290796-many-of-the-new-fa-fonts-broken/?tab=comments#comment-1304012

![untitled](https://user-images.githubusercontent.com/38172170/43678387-0b645c80-9845-11e8-8ba4-8f40e56c7a62.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot confirm.

Version 68.0.3440.84 64 bit / Win 10 Pro.

Please try top open Chrome without extension, maybe there is a third-party script / ad-blocker that messes up with Font Awesome

**Comment by rangka-kacang** [comment]
Silly me! I've just disabled my adblocker and that "share" icon is now working properly. No wonder it didn't work on my Chrome.

https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom
