### ISSUE TITLE
Change request: rebrand Google Wallet to G-Pay

### ISSUE THREAD

**Issue by shotzportraits** [FortAwesome/Font-Awesome#13705]
### What can it be used for?

Google has changed the name to G Pay (Previously Android Pay, which was previously Google Wallet before it branched off)

### Example image (optional)

https://pay.google.com/about/static/images/logos/google-pay-logo.svg

### Icon request checklist

- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Let's use #12519
