### ISSUE TITLE
Icon Request : Messenger

### ISSUE THREAD

**Issue by khushal21** [FortAwesome/Font-Awesome#13718]
Now a days facebook messenger is much needed icon to share some contain directly in messenger from the website. So i request to icon giant to add facebook messenger to font awesome icons(fa-icons).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/facebook-messenger?style=brands has been introduced in version 5.0.0

Please make sure you are using the latest version of font awesome

hope it helps

Closing here

**Comment by khushal21** [comment]
Is font awesome version 5.0.0 is free ?

**Comment by tagliala** [comment]
yes, please refer to https://fontawesome.com/how-to-use
