### ISSUE TITLE
Icons not shoiwing

### ISSUE THREAD

**Issue by kausaranjum** [FortAwesome/Font-Awesome#13729]
### Describe the problem

I found some of the icons are not working. 

I am using a free version of font awesome. Some icons are not showing listed below.
https://fontawesome.com/icons/hands-helping?style=solid
https://fontawesome.com/icons/handshake?style=solid
https://fontawesome.com/icons/hand-holding-usd?style=solid

### What did you expect?
Working icons

### What version and implementation are you using?
5.2.0

Version: 
Browser and version: 

- [ ] SVG with JS
- [  ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

I am using localhost server. I am not able to add url

### Bug report checklist

- [  ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [  ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm: https://jsfiddle.net/tagliala/m6a4ot01/12/

`hands-helping` and `hand-holding-usd` have been introduced in FA version 5.0.9.

`handshake` has been introduced in FA 4.7.0

To see all the above icons, please double check that you are using a version of Font Awesome >= 5.0.9

Note that you may indirectly load an older version through a plugin on your website

Ref: 

- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

If you still think there in an issue with Font Awesome, please provide a reproducible test case

Closing here
