### ISSUE TITLE
Icon Request: Facebook Messenger

### ISSUE THREAD

**Issue by khushal21** [FortAwesome/Font-Awesome#13728]
Nowadays facebook messenger is also being good platform to share the contains personally like whatsapp. And a lot of people do use it too. So I request font awesome community to create messenger icon. 

I am using it in website to share the link related to a single person where i have used whatsapp icon and i need messenger icon there and also in my many of the website.

**Comment by tagliala** [comment]
https://fontawesome.com/icons/facebook-messenger?style=brands

Ref: #13718

🔒
