### ISSUE TITLE
Gallery not working when using accessible fonts

### ISSUE THREAD

**Issue by Taxcamp** [FortAwesome/Font-Awesome#13723]
### Describe the problem

I've recently started using a font specifically made for dyslexic people which makes it a lot easier to read lots of text. This font overrides any custom webfonts. Utilising the SVG with JS route I can see all Icons so I wanted to continue using Fontawesome in my projects. However the gallery only shows a lot of broken squares.

![image](https://user-images.githubusercontent.com/7807969/43763222-7f1864a0-9a2a-11e8-8e5a-4e88d793fc69.png)

### What did you expect?

The gallery should show an overview of all icons.

### What version and implementation are you using?

Version: Fontawesome Website
Browser and version: Chrome 68 OSX High Sierra

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://fontawesome.com/icons?d=listing

Install any addon that forces the open dyslexic 3 font.

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This font overrides any custom webfonts

Is there any chance of adding exceptions on this plugin?

Please whitelist fontawesome

**Comment by Taxcamp** [comment]
Sadly the plugin I'm using does not have a whitelisting feature. However adding an !important to the font-family css rule overrides the plugin. (at least the one I'm using, which is force font)
Using !important may not be the most beautiful way of fixing this but it seems to work.

**Comment by Taxcamp** [comment]
The addon I'm using is simply adding a font-family: "Open Dyslexic"!important rule to the root of the document so it would likely require a full rewrite to allow a whitelisting option.
If I have the time I might write my own addon soon that would leave icon fonts as they are.

It would still be pretty awesome if you could fix this on the Fontawesome side as well because many people use custom fonts and only a small fraction of them would use my addon.

**Comment by robmadole** [comment]
@Taxcamp yeah I'm not sure how we'd fix this in Font Awesome itself. What did you have in mind?

**Comment by tagliala** [comment]
@robmadole he suggests to add `!important` to the `font-family: 'Font Awesome'` rule

**Comment by tagliala** [comment]
@robmadole I agree

@Taxcamp I know that this is useful for dyslexic people but we prefer to not add `!important` in the Font Awesome Core. 

Please contact the plugin author and report this issue about webfonts.

My suggestion is to provide a whitelist of classes that will not be affected by the `!important` rule.

Something like

```css
*:not(.fa),
*:not(.fab),
*:not(.far),
*:not(.fas),
*:not([class^="icon"]) {
  font-family: Whatever !important;
}
```

Closing here
