### ISSUE TITLE
Icon Request: air-bnb

### ISSUE THREAD

**Issue by JhayveeA8** [FortAwesome/Font-Awesome#13726]
I noticed you don't have this on your brand icons when I was looking for it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7650, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
