### ISSUE TITLE
FontAwesome 4.7 fa-expand and fa-compress in 5.x

### ISSUE THREAD

**Issue by ctr1key** [FortAwesome/Font-Awesome#13727]
### Describe the problem
The font-awesome 4.7 icons for .fa-expand (https://fontawesome.com/v4.7.0/icon/expand) and .fa-compress icons (https://fontawesome.com/v4.7.0/icon/compress) are not available in the 5.x free version. In 5.x, they are .fa-expand-alt and .fa-compress-alt in the pro version. 

### What did you expect?
Expected a similar equivalent of 4.7 .fa-expand and .fa-compress in the 5.x free version.

### What version and implementation are you using?
Version: Migrating from font-awesome@4.7.0 to @fortawesome/fontawesome-free@5.2.0
Browser and version: Chrome 68
- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is legit

@talbs 

https://fontawesome.com/icons/expand-alt?style=solid
https://fontawesome.com/icons/compress-alt?style=solid

are only available in FA5 Pro, but they are basically the updated versions of

https://fontawesome.com/v4.7.0/icon/expand
https://fontawesome.com/v4.7.0/icon/compress

Also, v4 shims should map expand to expand-alt and compress to compress-alt

What do you think?

**Comment by sensibleworld** [comment]
This should now be fixed!

**Comment by rovio-daniel-jackson** [comment]
This isn't mentioned in https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes

And linking related issue: https://github.com/FortAwesome/Font-Awesome/issues/11771
