### ISSUE TITLE
Icon request: pop-out

### ISSUE THREAD

**Issue by elegantscience** [FortAwesome/Font-Awesome#13725]
### What can it be used for?

This is a classic icon for UI circumstances in which a small window needs to be spawned to create a separate viewing area.

### Example image (optional)

http://freeiconshop.com/icon/pop-out-icon-glyph/

### Icon request checklist

- [√] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [√] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [√] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [√] I have included at least one example image if it could be helpful (optional)
- [√] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/external-link-alt?style=solid fit your needs?

**Comment by elegantscience** [comment]
Yes - just found it and was about to delete this. Thanks.
