### ISSUE TITLE
fas fa-shopping-cart icon not working

### ISSUE THREAD

**Issue by JoshCarey** [FortAwesome/Font-Awesome#13722]
### Describe the problem

I'm using a couple key FREE icons in a site project.  Some are working, however the "fas - fa-shopping-cart" one is not working.  Its just showing up as a square (in Chrome) as if the icon is missing (in Safari).

### What did you expect?

This should look like the shopping cart on the font-awesome site

### What version and implementation are you using?

Version: 5.2
Browser and version:  Chrome

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Using this locally at the moment, will be trying to upload this feature soon.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot reproduce. Please check that everything is fine in your application

https://jsfiddle.net/tagliala/m6a4ot01/7/

Take a look at the troubleshooting guide: https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting

If you still think there is an issue with font awesome, please provide a reproducible test case

**Comment by JoshCarey** [comment]
Apologies - There was another plugin (https://wordpress.org/plugins/ti-woocommerce-wishlist/) that has included fontawesome, and is using an older glyph, apparently.

**Comment by tagliala** [comment]
No problem, glad you've solved 👍

**Comment by ghost** [comment]
@tagliala the link you sent is not working any more. i have the same problem. i am trying to understand it. in my case, fa-sharp fa-light fa-cart-shopping appears as a square.

**Comment by tagliala** [comment]
Hi @sinke237 , can we have a reproducible test case? In those years we added a lot of new ways to use font awesome and it is hard to debug without any information

> in my case, fa-sharp fa-light fa-cart-shopping appears as a square.

So it looks like your application is using FA Pro. but this is still not enough, we need to understand if it is:
- css
- js
- self-hosted
- cdn
- js kit
- css kit
- other

Please fill out a [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

Closing here, but feel free to comment if I've missed something

Also, as a Pro Customer, you have dedicated support via hello@fontawesome.com

**Comment by ghost** [comment]
Oh great... anyway, i was using a css kit. but it is now working just fine.
