### ISSUE TITLE
Icon request: align-top, align-middle, align-bottom

### ISSUE THREAD

**Issue by borglin** [FortAwesome/Font-Awesome#13730]
### What can it be used for?

Indicating options for vertical alignment of text, like inside a table or spreadsheet.

### Example image

From the toolbar in Microsoft Excel:
<img width="97" alt="screen shot 2018-08-08 at 13 44 22" src="https://user-images.githubusercontent.com/6277414/43835266-aa0b368c-9b11-11e8-99bc-36387f7d08bd.png">

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2772, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
