### ISSUE TITLE
Icon request: icon-spellcheck

### ISSUE THREAD

**Issue by p3nnst8r** [FortAwesome/Font-Awesome#1373]
I would use this as a potential spell-checker for forms on the page. I created one, but would like to see it included in font awesome.

![lehighpr-icons](https://f.cloud.github.com/assets/4753303/684144/e09a7a60-d9f0-11e2-9fc9-7805f42896c0.png)

**Comment by henleywc** [comment]
+1

**Comment by NicoKnoll** [comment]
+1

**Comment by eocarragain** [comment]
+1 thanks

**Comment by joshknopp** [comment]
The stacking feature seems well suited for this.  This is a very crude example, but someone with a bit more skill could clean it up nicely, I'm sure... 

&lt;span class="fa-stack">
&emsp;	&lt;i class="fa fa-check fa-stack-1x">&lt;/i>
&emsp;	&lt;i class="fa fa-stack-1x" style="font-family:Arial, sans-serif; font-size:0.6em; top:-1em; left:-0.5em;">abc&lt;/i>
&lt;/span>

**Comment by TheChen5** [comment]
+1

**Comment by WillJW** [comment]
+1

**Comment by beliys** [comment]
+1

**Comment by w3l** [comment]
+1

**Comment by kdt** [comment]
+1

**Comment by jahnb** [comment]
+1

**Comment by rdiazv** [comment]
+1

**Comment by ndran** [comment]
+1

**Comment by raerae13** [comment]
👍

**Comment by bilo1967** [comment]
+1

**Comment by tlbignerd** [comment]
+1
I've looked for this three times now for different apps.

**Comment by stevelippert** [comment]
+1, looking to update all of our gif buttons with HTML buttons using Font Awesome for the icons.

**Comment by Berkmann18** [comment]
+1

**Comment by SuperPat45** [comment]
+1

**Comment by xuv** [comment]
Here is a proposition for a spell check icon.
<img width="1147" alt="screen shot 2019-02-13 at 13 01 31" src="https://user-images.githubusercontent.com/192539/52732999-9b123000-2f8f-11e9-8612-5186d939c7d9.png">

I've used AZ instead of abc to stay coherent with the Sorting icons that we have already.
https://forkawesome.github.io/Fork-Awesome/icon/sort-alpha-asc/

Let me know what you think.

**Comment by sensibleworld** [comment]
We fnially dicided to do smething aboat hour splling. https://fontawesome.com/icons/spell-check?style=solid
