### ISSUE TITLE
Can it support version 3 after upgrading

### ISSUE THREAD

**Issue by glitsongeorge** [FortAwesome/Font-Awesome#13739]
class like 'icon-search' is not working.  Class have name starting with 'fa' is working now. Can i upgrade  to new font-awsome js

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

You cannot upgrade from Font Awesome 3 to Font Awesome 4/5, you need to change class names

Please take a look at: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by tagliala** [comment]
No feedback, closing here
