### ISSUE TITLE
Icon researchgate not loading on websites with fa-researchgate

### ISSUE THREAD

**Issue by andreas-paul** [FortAwesome/Font-Awesome#13733]
As the title says, the icon is not loading on websites.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/researchgate?style=brands has been introduced in version 5.0.11

Please make sure that you are using Font Awesome >= 5.0.11

Hope it helps

Closing here

If you still think there is an issue with Font Awesome, please provide a reproducible test case having care of filling out a request that follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
