### ISSUE TITLE
Icon "far fa-heart" (regular heart) not working

### ISSUE THREAD

**Issue by epattermann** [FortAwesome/Font-Awesome#13746]
### Describe the problem

Hi there!

I am attempting to use the latest version of Font Awesome to display the "regular heart" (`"far fa-heart"`) icon in my project, and it's not displaying as I expect it to. I am using other icons in my project, and they're all working beautifully (i.e. displaying as I expect them to).

### What did you expect?

I expect to see an heart shape outlined in black (the default color) but unfilled/transparent, as seen here: https://fontawesome.com/icons/heart?style=regular

Instead, I am seeing a slightly downsized/smaller version of the "solid heart" icon (both outlined and filled with black), as seen here: https://fontawesome.com/icons/heart?style=solid

### What version and implementation are you using?

FA Version: v5.2.0
Browser and version: Chrome Version 68.0.3440.84; Safari Version 10.1.1 (11603.2.5); Firefox Version 59.0.3

- [x] Web Fonts with CSS

### Reproducible test case

1. Add the latest version of Font Awesome to your project: `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">`

2. Insert an element to display a FA "regular heart" icon: `<i class="far fa-heart"></i>`

3. Observe the icon.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't reproduce: http://jsfiddle.net/tagliala/m6a4ot01/15/

Please take a look at our troubleshooting guides:

- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

If you still think there is an issue with Font Awesome, please provide a reproducible test case.

**Comment by tblevins-pv** [comment]
Reproducable tutorial:

https://github.com/dersnek/chirp/blob/master/assets/css/app.scss
https://www.youtube.com/watch?v=MZvmYaFkNJI
