### ISSUE TITLE
Capital sigma letter icon

### ISSUE THREAD

**Issue by chrismasters** [FortAwesome/Font-Awesome#13754]
As an cue for aggregation, is it possible to add a Σ to the icon set?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4834 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
