### ISSUE TITLE
CDN pro version v5.2.0 does not contain fa-layers classes

### ISSUE THREAD

**Issue by tanthammar** [FortAwesome/Font-Awesome#13755]
### Describe the problem

The pro cdn link does not contain fa-layers classes
Icons are showing but not layering.
When I inspect the element I can see that the required fa-layers classes are missing.
Version: https://pro.fontawesome.com/releases/v5.2.0/css/all.css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
