### ISSUE TITLE
Amazon music icon

### ISSUE THREAD

**Issue by Bodybyloud** [FortAwesome/Font-Awesome#13753]
I just wanted to request the icon for amazon music.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13403, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
