### ISSUE TITLE
Packages out of date on npm

### ISSUE THREAD

**Issue by jesobreira** [FortAwesome/Font-Awesome#13757]
The following packages are out of date on npm and are missing several newly-introduced icons:

* fontawesome-pro-light (5.0.13)
* fontawesome-pro-regular (5.0.13)
* fontawesome-pro-brands (5.0.13)
* fontawesome-pro-webfonts (5.0.13)
* pro-solid-svg-icons (5.1.0-11)
* pro-regular-svg-icons (5.1.0-11)
* pro-light-svg-icons (5.1.0-11)

For reference, the package fontawesome-pro is at 5.2.0.

Tree shaking with recent icons (such as "passport") as well as usage with react-fontawesome is not possible if the docs are followed.

If they were deprecated, the docs must be updated.

If it is meant to be done somehow else, please guide me to the updated docs.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Before opening, please double check that your package,json does not contain `@prerelease` tags and maybe set the Font Awesome version requirement to ^5.2.0

Please also take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510
