### ISSUE TITLE
Icon request: fa-eu-emblem

### ISSUE THREAD

**Issue by pgroot91** [FortAwesome/Font-Awesome#13761]
Request icon: **EU emblem** the circle with the 12 stars.

Example: https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_the_European_Union_%28bw%29.svg/640px-Flag_of_the_European_Union_%28bw%29.svg.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I have to close this one because it is out of scope

For further information, take a look here: #9520
