### ISSUE TITLE
Icon request: Start Button

### ISSUE THREAD

**Issue by Welchen** [FortAwesome/Font-Awesome#13766]
Would be nice to have some type of icon that is similar to a scanner/copier start button.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example? 

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by InsanityMeetsHH** [comment]
I guess he is mentioned a square rotated by 45 degrees with a pipe inside and a circle with a triangle inside.
start = square with pipe
stop = circle with triangle
![copy-buttons](https://user-images.githubusercontent.com/35538671/44196141-67b72b80-a13b-11e8-9f77-f9ff944fd89e.png)

**Comment by tagliala** [comment]
Start is already available: https://fontawesome.com/icons/power-off?style=solid

Hope it helps,

closing here

**Comment by InsanityMeetsHH** [comment]
The power off icon is unlike square with pipe.
Square with pipe is like "start program" and circle with triangle is "stop program".
Sometimes these icons are also on microwaves.

**Comment by tagliala** [comment]
Sorry, reopening here I'm waiting for feedback from the author.

I need 1 single color icon that represents "start button"

**Comment by InsanityMeetsHH** [comment]
Start button: 
![se995 starticon](https://user-images.githubusercontent.com/35538671/44310215-d530b980-a3d2-11e8-98a7-bc0aa6682d94.png)

Stop button:
![se995 stopicon](https://user-images.githubusercontent.com/35538671/44310219-dc57c780-a3d2-11e8-9243-8bbcce7bc128.png)

**Comment by InsanityMeetsHH** [comment]
I made  a [demo](https://codepen.io/anon/pen/vQdgEE) with layers and added to [snippets wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Layering-and-Masking-snippets#program-start--stop).

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
