### ISSUE TITLE
maxcdn

### ISSUE THREAD

**Issue by sumitnath** [FortAwesome/Font-Awesome#13774]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this an icon request?

If it is, we already have maxcdn: https://fontawesome.com/icons/maxcdn?style=brands

If it isn't, please make sure that your report follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
