### ISSUE TITLE
Icon Request: Fraction Symbol

### ISSUE THREAD

**Issue by rowejs** [FortAwesome/Font-Awesome#13777]
Please could you make a symbol representing a fraction, like on a calculator? Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by rowejs** [comment]
I've used the new icon request template and opened this as a new issue #13780. Thank you.
