### ISSUE TITLE
FontAwesome 5 PRO - fal fa-user-circle - Not showing correctly

### ISSUE THREAD

**Issue by SGissubel** [FortAwesome/Font-Awesome#13782]
Using font-awesome pro with nativescript-angular 6.  The free version worked with the text, upgraded to pro -- text does not work -- I am using the unicode now and it is working.

But, `fal fa-user-circle` does not show the correct item.  

Should show: 
![image](https://user-images.githubusercontent.com/21371158/44285366-05d9ed00-a233-11e8-9d69-74d03f041bf6.png)

Is showing: 
![image](https://user-images.githubusercontent.com/21371158/44285373-0f635500-a233-11e8-9da9-d21c4dc158fe.png)

Not the correct user-icon AND is super thick. 

Code: 

```
		<Label
			row="0"
			class="fal icon"
			text="&#xf2bd;">
		</Label>	
```

Using css instead of fa - sizing, as I am unable to get it working:
```
.icon {
	font-size: 80; }
```

app.css:
```
.fab {
  font-family: Font Awesome 5 Brands, fa-light-400; }
.fal {
  font-family: Font Awesome 5 Pro, fa-regular-300;
  font-weight: 300; }
.far {
  font-family: Font Awesome 5 Pro, fa-regular-400;
  font-weight: 400; }
.fa,
.fas {
  font-family: Font Awesome 5 Pro, fa-regular-900;
  font-weight: 900; }
```

I have all.css imported into my app/fonts folder. 

app.module (imports):
```
        ...
  	TNSFontIconModule.forRoot({
			'fa': './assets/fontawesome.scss',
			'fal': './assets/fontawesome.scss',
			'fab': './assets/fontawesome.scss',
			'far': './assets/fontawesome.scss',
			'fas': './assets/fontawesome.scss',
  	})
        ...
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
