### ISSUE TITLE
Icon request: icon-drawing-compass

### ISSUE THREAD

**Issue by evanthorpe** [FortAwesome/Font-Awesome#1378]
Hi,

I think people would be able to find many uses for a "drawing compass." This could be used on architecture sites, to represent graphic design or illustration services or within many math/science contexts.

I would imagine it would be something simple like the link listed below:

http://labargemedia.com/dev/wp-content/uploads/2013/06/Compass.png

Thanks!

**Comment by matsair** [comment]
+1

**Comment by dougrawson** [comment]
I too would like to have the drafting compass. 
http://findicons.com/icon/558272/drafting_compass

**Comment by bedeviere** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/drafting-compass?style=solid
