### ISSUE TITLE
chart-pie should be pie-chart OR the other way round (?) 

### ISSUE THREAD

**Issue by hitteshahuja** [FortAwesome/Font-Awesome#13797]
Incidentally, 
fa-chart-pie doesnt work ( when it shouldnt) but pie-chart does !!! 

https://fontawesome.com/icons/chart-pie?style=solid

@skinnytech

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You are probably using Font Awesome 4.7, because `pie-chart` has been renamed `chart-pie` in Font Awesome 5

https://fontawesome.com/v4.7.0/icon/pie-chart
https://fontawesome.com/icons/chart-pie?style=solid

Hope it helps

Closing here
