### ISSUE TITLE
Need a flip camera icon

### ISSUE THREAD

**Issue by aniruddhashevle** [FortAwesome/Font-Awesome#13798]
There isn't any flip camera icon, we need that!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3956, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
