### ISSUE TITLE
Icon request: diploma

### ISSUE THREAD

**Issue by kkirsche** [FortAwesome/Font-Awesome#1379]
I think a diploma icon would be great to have for education based applications

**Comment by solid2core** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by Turok21** [comment]
+1

**Comment by eduardorochas** [comment]
+1

**Comment by pepalan** [comment]
+1

**Comment by wagneramaral** [comment]
+1

**Comment by Crissov** [comment]
Perhaps U+1F4DC  📜 in Unicode #222

**Comment by Tamraica** [comment]
+1

**Comment by Tarith** [comment]
+1

**Comment by stinow** [comment]
+1

**Comment by AguD** [comment]
+1 missing a lot of ed-related icons, diploma, a professor, a classroom, a study book, etc

**Comment by ashtromberg** [comment]
+1

**Comment by rousemw** [comment]
I prefer this image: 
![image](https://user-images.githubusercontent.com/38332336/38991864-030a37a4-43ad-11e8-9d76-46590466138f.png)

**Comment by rousemw** [comment]
How can I tell if my icon is being developed or if it was just closed.

**Comment by sensibleworld** [comment]
@rousemw We'll add an `in progress` label to icons that are being actively worked on. This icon, was just released.
