### ISSUE TITLE
Wrong icons displaying

### ISSUE THREAD

**Issue by ChubbyTio** [FortAwesome/Font-Awesome#13802]
When trying to use _calendar_ and _facebook-f_ different icons are displayed. I get _calendar-alt_
 _facebook_ instead. What am I doing wrong?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case?

You can start with the following, according to your version:
5.2.0 SVG: http://jsfiddle.net/tagliala/9tercwpy/
5.2.0 CSS: http://jsfiddle.net/tagliala/m6a4ot01/

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by ChubbyTio** [comment]
I received an email from Trevor. He assisted me. Thank you!
