### ISSUE TITLE
Icon Request: Veterinary

### ISSUE THREAD

**Issue by VeeDoubleYuh** [FortAwesome/Font-Awesome#13803]
There's a resonable amount of [medical icons](https://fontawesome.com/icons?d=gallery&c=health), but there are few that represent animals or veterinary practices.

I work on sites that sell pet products with an emphasis on being humane (no shock and such). Having icons to represent the above would be extremely helpful. I'm sure they would be even more helpful to an actual veterinary practice.

[Here's an example](https://www.123rf.com/photo_69222703_stock-vector-veterinary-icons-or-logo-elements-vector-collection-of-vet-and-pet-concept-sign-in-thin-line-style.html) that I think gives a fair idea of what the icons could look like.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does `fa-paw` fit your use case? https://fontawesome.com/icons/paw?style=solid

Also, you can take advantage of the SVG framework to achieve results like:
http://jsfiddle.net/tagliala/9tercwpy/73/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
- https://fontawesome.com/how-to-use/on-the-web/styling/masking

If none of the above fit your use case, please fix the title, providing a single example of the icon you need.

Eg: `Icon request: fa fa-cross-with-paw (veterinary)` or `Icon request: fa fa-heart-with-paw (veterinary)` or `Icon request: fa fa-heart-with-dog (veterinary)`

**Comment by VeeDoubleYuh** [comment]
Looks like I'm not as creative as I thought. Thanks for the ideas!

Most of the suggested images in that link can be generally replicated through those techniques, so I'd just count this ticket as another +1 to the Dog and Cat ticket then :)

Thank you!

**Comment by tagliala** [comment]
You're welcome 👍
