### ISSUE TITLE
package.json for free-brands-svg-icons is missing license

### ISSUE THREAD

**Issue by Findus23** [FortAwesome/Font-Awesome#13808]
Hi,

I just noticed that [`advanced-options/use-with-node-js/free-brands-svg-icons/package.json`](https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/use-with-node-js/free-brands-svg-icons/package.json) is missing the `license` parameter.
I guess it should look like this:
https://github.com/FortAwesome/Font-Awesome/blob/bab41b27a169f6b688996f24c10bd7a0697811e6/advanced-options/use-with-node-js/free-regular-svg-icons/package.json#L57

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

**Comment by robmadole** [comment]
Yes, thanks. We'll get this fixed.

**Comment by tagliala** [comment]
This has been fixed in version 5.4.0 via 5362994408184a0f86b2b63b5971eac15eca1664
