### ISSUE TITLE
"route" not rendering in 5.0.13 FREE

### ISSUE THREAD

**Issue by crobinson42** [FortAwesome/Font-Awesome#13804]
Using https://use.fontawesome.com/releases/v5.0.13/css/all.css class name `fa fa-route` is not rendering.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks. There is an issue in the documentation.

The icon has been added in FA Pro 5.0.9 and has been made available for free in version 5.2.0

Please make sure you are using FA 5.2.0

@talbs what can we do to fix issues like this? Bump up the version from 5.0.9 to 5.2.0?

**Comment by crobinson42** [comment]
Sorry I missed that! It is a bit ambiguous on the page here: https://fontawesome.com/icons/route?style=solid

I'll update my version! Thanks for the help!

**Comment by tagliala** [comment]
@crobinson42 yes, sorry.

Reopening because there actually is an issue in the documentation

**Comment by sensibleworld** [comment]
This is now fixed on our site. Thanks for bringing it to our attention, @crobinson42.
