### ISSUE TITLE
Using FontAwesome all.js with :after shows icon, but also shows the empty box symbol

### ISSUE THREAD

**Issue by LanceButters** [FortAwesome/Font-Awesome#13811]
I'm using Font Awesome 5.2 with all.js

`<script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js" data-search-pseudo-elements></script>`

I want to use an icon as an pseudo element, like this

```
div:after {
    display: none;
    content: '\f095';
    font-weight: 900;
    font-family: 'Font Awesome 5 Free';
    font-size: 20px;
    line-height: 20px;
    color: #333;
    display: block;
    position: absolute;
    top: 2px;
    left: 4px;
    width: 20px;
    height: 20px;    
  }

```

This outputs the icon, but also shows the empty box symbol which means that it didn't find the icon... but it did, so why does the box appear?

I have the issue on Firefox and Chrome.

https://imgur.com/a/JyZWba0

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that you are overriding the `display` property with a `block` value.

```
div:after {
    display: none;
    content: '\f095';
    font-weight: 900;
    font-family: 'Font Awesome 5 Free';
    font-size: 20px;
    line-height: 20px;
    color: #333;
    display: block; /* Remove this */
    position: absolute;
    top: 2px;
    left: 4px;
    width: 20px;
    height: 20px;    
  }
```

http://jsfiddle.net/tagliala/ybwe7Ldh/

Hope it helps

Closing here
