### ISSUE TITLE
Using latest icons from npm?

### ISSUE THREAD

**Issue by slavafomin** [FortAwesome/Font-Awesome#13818]
Hello!

Thank you for this great library!

However, how do I use the latest version of the icons through the npm?

According to the [releases page](https://github.com/FortAwesome/Font-Awesome/releases) the latest version of the library is `5.2.0`. However, the latest version available on npm is `4.7.0`.

I'm trying to use the free [`user-cog`](https://fontawesome.com/icons/user-cog?style=solid) icon available starting from `5.0.11`.

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome's official NPM packages are available under the `@fortawesome` scope.

Take a look here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers let me know if that helps

**Comment by slavafomin** [comment]
Thank you for clarifying this!

I'm using `angular2-fontawesome` package which depends on this package [font-awesome](https://www.npmjs.com/package/font-awesome). I've followed the link to GitHub repo from it's npm page and have got to this repo.

Looks like I should ping the authors of `angular2-fontawesome`.

**Comment by tagliala** [comment]
@slavafomin we have an official component for angular:

https://fontawesome.com/how-to-use/on-the-web/using-with/angular

**Comment by tagliala** [comment]
You're welcome. Glad you've solved 👍
