### ISSUE TITLE
Sometimes font icons are not working 

### ISSUE THREAD

**Issue by skchinna7** [FortAwesome/Font-Awesome#13816]
### Describe the problem

Some font icons are working using fa class some times it works too 
Some times it works with using fab
### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In FA5 we've changed a lot of stuff

If you need a brand icon, you have to use the `fab` class
If you need a solid style icon, you have to use `fas` (or `fa`, the old deprecated alias)
If you need an outlined icon, you have to use `far` (regular style icons)

Please take another look at our documentation:
https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes

If you still think there is an issue with font awesome, please provide a reproducible test case.

Hope it helps

Closing here
