### ISSUE TITLE
Add positive and negative search terms

### ISSUE THREAD

**Issue by shoulders** [FortAwesome/Font-Awesome#13821]
### What can it be used for?

A lot of people like to have the simple option of postive or negative. For instance in check lists but when you search for positive or negative there is not an entry. I have added this as new icon because there are no instructions for adding aliases.

I purpose the following aliases:

**positive**
-  fa-plus --> fa-positive

**negative**
- fa-minus --> fa-negative

### Icon request checklist

- [x] This is a matched pair
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Thanks.

I can reopen this as docs enhanchement

@talbs should we add `positive` and `negative` filters? Are they a common search?

**Comment by talbs** [comment]
> @talbs should we add positive and negative filters? Are they a common search?

Hi, all. This seems like a good thing to do. I'll put it on my short list when next updating our search metadata. Hang tight and stay **positive** (sorry, couldn't resist the dad joke). 😛

**Comment by talbs** [comment]
Thanks again for bringing this to our attention. We've added `positive` and `negative`-minded metadata to our icons and you can take advantage of that now on fontawesome.com...

* https://fontawesome.com/icons?d=gallery&q=positive
* https://fontawesome.com/icons?d=gallery&q=negative

Let us know if there's anything else we can do to make Font Awesome better!

**Comment by shoulders** [comment]
the - and + should come up first in the list, should i open a new issues?
