### ISSUE TITLE
Icon Request: Flipboard

### ISSUE THREAD

**Issue by brendanjryan** [FortAwesome/Font-Awesome#1382]
Flipboard Icon for Social Media integration
![flipboard](https://f.cloud.github.com/assets/1572504/689939/fa656dae-dac4-11e2-9426-f96be68622c1.jpeg)

**Comment by cleverscale** [comment]
+1

**Comment by jackcksn** [comment]
+1

**Comment by elitedevs** [comment]
+1

**Comment by dgsinclair** [comment]
Want

**Comment by mani-monaj** [comment]
+1

**Comment by Kapildhiman** [comment]
HI,

Can you please provide font icon for flipboard e.g. content: "\e030";

**Comment by stuartbruce** [comment]
+1

**Comment by thibaultis** [comment]
+1

**Comment by tuxracer** [comment]
+1

**Comment by Createstandard** [comment]
back to the top

**Comment by beathan** [comment]
+1

**Comment by arturoceballos** [comment]
+1

**Comment by ChayaCooper** [comment]
+1

**Comment by Faolon** [comment]
+1

**Comment by belkamax05** [comment]
+1
I agree, need this icon.

**Comment by redesigned** [comment]
+1 I need this icon as well.

**Comment by OPPtester** [comment]
+1 needed badly as well. 

Love to know where things stand, is this being implemented/rejected?

Thanks,

**Comment by jrobertriney** [comment]
I'm in need of a Flipboard icon, as well. Thank you kindly.

**Comment by GHawk1ns** [comment]
+1 I'd love to use this icon with FA

**Comment by njy** [comment]
@rene-hermenau sorry to reopen this, but since their vector logo looks like this https://worldvectorlogo.com/logo/flipboard , wouldn't it be possible to simply to something like this?
![image](https://cloud.githubusercontent.com/assets/1010086/19246637/9df731f4-8f27-11e6-92f2-bdd6daa66ed2.png)
With three simple rectangles I think we can convey the Flipboard brand quite effectively.

Opinions?

**Comment by rene-hermenau** [comment]
@njy Thats similar  what i did in the end for [MashShare](https://github.com/mashshare/Mashshare) plugin  ![Alt text](https://monosnap.com/file/VrTQS6l9MxgwCU8f6iikyYGjBLDaQt.png) Thats working well

**Comment by njy** [comment]
Great, so when you said "it can not be done as regular icon font" what did you mean? I don't know if you work on the FontAwesome icon set or not, so I'm asking who we should be talking with.
Thanks!

**Comment by rene-hermenau** [comment]
That answer by me was valid for the initial icon request. 
The suggestion by you can be done indeed as a regular icon font.

 I am not working on font awesome. I personally use fontello.com. You can import there any svg icon and export it than as an icon font. Here is my import file including the flipboard icon. Maybe its helpful for you:  [config.json.zip](https://github.com/FortAwesome/Font-Awesome/files/521413/config.json.zip)

Or you try to catch someone responsible who could import that icon into font awesome

**Comment by njy** [comment]
@rene-hermenau ok thanks for the clarification ;-) !

**Comment by anupam-047** [comment]
+1

**Comment by sunipeyk** [comment]
I would like to see[ Flipboard](https://flipboard.com/) icon. It is the best curate and/ or aggregator magazine app/service. And i am sure it is not difficult to make it, i suppose. :)
Thank you.
Icons from source
![a0aca554-d898-11e6-9e80-87a70f6fa1ec](https://cloud.githubusercontent.com/assets/9592953/22677770/58f0cca4-ed06-11e6-8f05-6e5a77a7ad21.png)
![f1312388-d898-11e6-89b4-712247e103a9](https://cloud.githubusercontent.com/assets/9592953/22677773/5bd4bee4-ed06-11e6-81b3-6dec7db381aa.png)

**Comment by beethedude** [comment]
A 3+ year old request and nothing?

**Comment by beethedude** [comment]
Since the request 3+ years ago, has any headway been made in adding this?

**Comment by JohnBain** [comment]
+1

**Comment by gerkevgarderen** [comment]
+1

**Comment by leowebdev** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
According to [their brand guidelines](https://s3.amazonaws.com/cdn.flipboard.com/wp-content/uploads/2015/02/Flipboard_-Basic-Brand-Guidelines_2015.pdf), there is a single colour version of the Flipboard logo, very similar to the one @njy posted. Note, though, that they state it should be "reserved for embroidery, screenprinting, embossing" and that, rather than 3 solid rectangles, the rectangles should be "knocked out" of a solid square.

**Comment by njy** [comment]
https://simpleicons.org/

just sayin'

**Comment by ersinkaya7** [comment]
+1

**Comment by leowebguy** [comment]
+!

**Comment by cjbatson** [comment]
I would like very much to see a Flipboard icon too!! If anyone knows when this is expected, please post that info or let us know!! Since this ticket is still open, I hope this is still in Font-Awesome's plans!

**Comment by vamshi29292** [comment]
+1

**Comment by talbs** [comment]
Hey, gang!

We've added this brand icon into Font Awesome 5 as part of the 5.0.5 release - https://fontawesome.com/icons/flipboard?style=brands. Happy Flipboard iconing!

Also, FYI, we went by [Flipboard's brand guidelines](https://about.flipboard.com/brand-guidelines/) and are using the single color treatment.
