### ISSUE TITLE
Ligatures not always working

### ISSUE THREAD

**Issue by cvesteghem** [FortAwesome/Font-Awesome#13826]
Hi,

I'm having a weird issue with ligatures, I was trying to use FA free 5 in Keynote, I followed the instructions for using FA on desktop and it was working ok. But now, I can not have some icons to render.

For example "user" and "hospital" are properly rendered but not anymore "user-md" or "dna", while I could have them properly rendered at some point. For "user-md", I get the icon "user" followed by the string "-md".
I'm using Keynote 8.1 on MacOS 10.13.6 (High Sierra) with FA free 5.2.0.

Is there something I'm missing?

Thanks in advance for any help.

Charles

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think I've got your issue

Please note that `user-md` is only available in **solid** style, so please make sure you've checked **bold** on the right side text panel

![image](https://user-images.githubusercontent.com/556268/44720629-a51aa200-aac7-11e8-8850-09ecabf502ad.png)

Hope it helps

Closing here

**Comment by cvesteghem** [comment]
Hi Geremia,

That's spot on, thanks a lot.

**Comment by tagliala** [comment]
You're welcome, glad you've solved 👍
