### ISSUE TITLE
Icon request:  fa-yes fa-no (alias)

### ISSUE THREAD

**Issue by shoulders** [FortAwesome/Font-Awesome#13820]
### What can it be used for?

A lot of people like to have the simple option of yes/no. For instance in check lists but when you search for yes or no there is not an entry. I have added this as new icon because there are no instructions for adding aliases.

I purpose the following aliases:

**yes**
-  fa-check --> fa-yes

**no**
- fa-times --> fa-no

### Icon request checklist

- [x] This is a matched pair
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Thanks.

I get both `check` and `times` when I search for yes and no

https://fontawesome.com/icons?d=gallery&q=yes&s=solid&m=free
https://fontawesome.com/icons?d=gallery&q=no&s=solid&m=free

Could you please confirm?

**Comment by shoulders** [comment]
I can confirm that. but when you take of solid and free loads comes up for no, yes there is a lot less. Is it possible to put them at the front of the list?

**Comment by tagliala** [comment]
I don't know.

@talbs do filters have priority?

**Comment by shoulders** [comment]
this issue is closed, will it still get looked at?
