### ISSUE TITLE
Clipboard Icon Bug/Issue

### ISSUE THREAD

**Issue by mykie92** [FortAwesome/Font-Awesome#13830]
The clipboard icon, " <i class="far fa-clipboard"></i> " is currently loading in the " <i class="far fa-paste"></i> " for some reason. I am not able to load in the Clipboard Icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Thanks

**Comment by aethior** [comment]
@tagliala I think you can close here.
