### ISSUE TITLE
Discussion: icons with dollar available with all other currencies

### ISSUE THREAD

**Issue by KelsoField** [FortAwesome/Font-Awesome#13834]
I am requesting that any icons that have a financial element (e.g: file-invoice-dollar, usd-square) have more currency options?
Yen, Euro, Pound etc
When developing a web application that should/would use such an icon and not based in the US, this causes a much understood confusion (and in some cases annoyance) of the end users.
I understand that this may be your primary currency Icon, but I am sure you have users all over the world and this would be appreciated by all. 
I also understand that there are many currency "icons" out there and do not propose you include them all, but the main group would be of use.

Many thanks for your consideration

**Comment by kromit** [comment]
Yes, using only the dollar sign limits the usage of those icons to dollar using countries. Not usable in the EU for example.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot leave this open as an icon request, because this will include ~ 20 icons * each currency available inside font awesome

I'm going to rename this as discussion

**Comment by adam-marshall** [comment]
I'd need `file-invoice-pound` if possible.

**Comment by danny-thinkbusinessloans** [comment]
Have these icons for the pound would be really useful for me.

**Comment by Rayden** [comment]
It would be commercial interesting to incude other currencies for all the icons which have the dollar sign in them.

Beside the dollar (US) these are the most common currencies

- EUR (€) Euro
- JPY (¥) Japanese Yen
- GBP (£) Pound sterling (GB)
- CNY (元) Renminbi (China)

**Comment by AndrewPaget** [comment]
Would definitely like to see other currencies. Perhaps like Rayden suggested, the most common. I of course would love to see file-invoice-pound as I am in the UK.

**Comment by robkovacs** [comment]
Why not _all_ currency symbols, on their own, and built into these other icons?
https://www.xe.com/symbols.php

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
Ref: #20294
