### ISSUE TITLE
Breaking changes in 5.3.1

### ISSUE THREAD

**Issue by zauguin** [FortAwesome/Font-Awesome#13836]
According to `UPGRADING.md` regarding the `5.3.0 ` to `5.3.1` update,

> There  are no breaking changes in this version upgrade.

But there is at least one breaking change: Some icons were removed because they were intended to be Pro only. 
I think this should be added to `UPGRADING.md`.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that a list of removed icon would be useful

**Comment by robmadole** [comment]
@tagliala @zauguin yeah that's a good point. We normally reserve that for code or API changes but I can see the logic there. Our chats about this internally was that it was a "bug" but technically there are some backward incompatible issues. I'll get those icons listed in there.
