### ISSUE TITLE
Icon Request : Membership Logo

### ISSUE THREAD

**Issue by nikul-serpentcs** [FortAwesome/Font-Awesome#13833]
* There is no Membership logo
Ex. like fa-membership

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Crown could represent membership: https://fontawesome.com/icons/crown?style=solid

If you have something specific in mind, please open a new request making sure that it follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here

**Comment by nikul-serpentcs** [comment]
@tagliala I want something the specific membership icon like this.

![membership_picture](https://user-images.githubusercontent.com/17664321/44786937-54807300-abb3-11e8-83fc-632a9ef2a556.PNG)

Or


![membership-count](https://user-images.githubusercontent.com/17664321/44787044-9dd0c280-abb3-11e8-968a-449160e0f2e9.png)

**Comment by tagliala** [comment]
@nikul-serpentcs sorry, the above examples are too complex to fit the 16px icon size

We have a badge: 
https://fontawesome.com/icons/certificate?style=solid

You can also use: 
https://fontawesome.com/icons/users?style=solid
