### ISSUE TITLE
Icon request:Pipe_Line

### ISSUE THREAD

**Issue by jorgechoypernia** [FortAwesome/Font-Awesome#13849]
Useful for Engineering web sites. Others could be instruments, valve, pump, etc

![exmple](https://user-images.githubusercontent.com/8151529/44869556-cd4fff80-ac85-11e8-963c-43b7fa508f6b.PNG)

Note this image is copied from a different site so i believe cannot be the same. It is just an example.

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #7837?

**Comment by aethior** [comment]
@tagliala I think you can close here. :)
