### ISSUE TITLE
Icon request: debug

### ISSUE THREAD

**Issue by markhealey** [FortAwesome/Font-Awesome#13842]
### What can it be used for?

Related to #6619 but different in that a `debug` icon in a button would represent an option to begin a debugging session.

I think this is a single icon, [`fa-bug`](https://fontawesome.com/icons?d=gallery&q=bug) already exists.

See also @sensibleworld 😼 😺 : https://twitter.com/fontawesome/status/1022453089314459648

Thanks!! 

### Example image (optional)

VS Code has a good debugger icon [shown here](https://code.visualstudio.com/docs/editor/debugging#_debug-view) and below.

![](https://code.visualstudio.com/assets/docs/editor/debugging/debugicon.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
@markhealey Your wish is my command: 
https://fontawesome.com/icons/debug?style=solid

**Comment by markhealey** [comment]
@sensibleworld 🙌🙌🙌
