### ISSUE TITLE
Website improvement: make the filters on the left fixed and scrollable

### ISSUE THREAD

**Issue by Ancinek** [FortAwesome/Font-Awesome#13846]
Good god, you have tons of issues 🙊Hope mine does not get lost :smile:

I really love your website, and your icons even more and I have a website CSS change proposal:

Wouldn't it be nice to make `aside.search-facets` element on your website fixed in one position?

When I look for an icon from a specific category, I have to scroll down to a category, where the results are not on the screen anymore. Selecting a category also makes the page jump to the top.

Having this element fixed in one position and with `overflow-y: scroll` would make the experience of browsing through the icon much better (at least for me).

Let me know what you guys think, and if in need I can create a PR (website repo?) in my free time to achieve this result :)

**Comment by prateekgoel** [comment]
Seems like this will be a good enhancement. I will work and submit a PR on this.

**Comment by sensibleworld** [comment]
We've done a bunch of improvements with our version 6 search. The category list isn't fixed, but it facets down to only icons and categories that include your search terms.

https://fontawesome.com/v6.0/icons?s=solid%2Cbrands
