### ISSUE TITLE
font awesome pro <i class="fab fa-creative-commons-zero"></i> not show (docs)

### ISSUE THREAD

**Issue by zabubakar** [FortAwesome/Font-Awesome#13850]
<i class="fab fa-creative-commons-zero"></i>icons not show in font awesome pro 5.3.1 svg

**Comment by zabubakar** [comment]
![Uploading Screenshot_2018-08-31 Font Awesome 5 creative-commons-zero.png…]()

**Comment by tagliala** [comment]
> icons not show in font awesome pro svg

Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot replicate.

[fa-creative-commons-zero](https://fontawesome.com/icons/creative-commons-zero?style=brands) has been introduced in Font Awesome 5.0.7 so please make sure that you are using FA >= 5.0.7

If you still have issues, please open a bug report at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here

**Comment by zabubakar** [comment]
Hi @tagliala  ,  I was tested it on font-awesome-pro 5.3.1

See here: https://fontawesome.com/icons/creative-commons-zero?style=brands

**Comment by tagliala** [comment]
@zabubakar thanks, there is an issue in the documentation. Are you reporting an issue in the documentation?

**Comment by devoto13** [comment]
Looks like I found the issue. This brand icon was incorrectly categorized as Pro instead of Free. It is the only Pro icon in the brands category https://fontawesome.com/icons?d=gallery&s=brands&m=pro.

**Comment by tagliala** [comment]
@devoto13 thanks

**Comment by talbs** [comment]
Thanks, @zabubakar, @devoto13, and @tagliala. We'll get this fixed up shortly and apologies for the missing icon and confusion in the docs.

**Comment by talbs** [comment]
Thanks again for bringing this to our attention. We fixed this in 5.4.1 and you can now use `creative-commons-zero` via Font Awesome Free (https://fontawesome.com/icons/creative-commons-zero/).

**Comment by kenperregaux** [comment]
I know this is an old post but I am using 6.4 and the icon talked about above is not in the npm package (free svg icons). Am I missing something obvious?

**Comment by devoto13** [comment]
@kenperregaux Not sure, seems to be there: https://yarnpkg.com/package?q=%40fortawesome%2Ffree-bran&name=%40fortawesome%2Ffree-brands-svg-icons&version=6.4.0&file=%2FfaCreativeCommonsZero.js

**Comment by kenperregaux** [comment]
@devoto13, here are the icons I have around where the CreativeCommonsZero icon should be

![image](https://github.com/FortAwesome/Font-Awesome/assets/24940607/6ebed333-3eb0-4096-bd8a-a1c24d2d697c)
