### ISSUE TITLE
Icon request: bicycle-riding , utensils-x

### ISSUE THREAD

**Issue by zabubakar** [FortAwesome/Font-Awesome#13858]
![screenshot_2](https://user-images.githubusercontent.com/34889246/44906250-32632e00-ad36-11e8-8456-8978e991fd28.png)

![screenshot_3](https://user-images.githubusercontent.com/34889246/44906423-adc4df80-ad36-11e8-8008-eebe77f95245.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per cutlery, does https://fontawesome.com/icons/utensils?style=solid fit your use case?

**Comment by zabubakar** [comment]
No, I already checked  `<i class="fas fa-bicycle"></i>`  and `<i class="fas fa-utensils"></i>`

[](https://fontawesome.com/icons/bicycle?style=solid)
[](https://fontawesome.com/icons/utensils?style=solid)

**Comment by tagliala** [comment]
@zabubakar could you please explain why you think Font Awesome needs an alternative version of the `utensils` icon and provide a use case ?

**Comment by zabubakar** [comment]
I think my new version is very similar to the kitchen but `<i class="fas fa-utensils"></i>`  is very similar to food. So, I think this should be a new icon.

**Comment by sensibleworld** [comment]
We have these now!

https://fontawesome.com/icons/person-biking?s=solid&f=classic
https://fontawesome.com/icons/fork-knife?s=solid&f=classic
