### ISSUE TITLE
Icon Request: icon-earth+

### ISSUE THREAD

**Issue by muonghoa** [FortAwesome/Font-Awesome#1385]
Hi, 
Just noticed you add the male-female icons, well done
It could be a good idea to add the signs of the genders, like below
http://en.wikipedia.org/wiki/Gender_symbol

![2](https://f.cloud.github.com/assets/3533768/690297/48b1f54a-dade-11e2-8e7a-9da9edbc0b9b.jpg)

Also, that cross on the circle (on top, instead of above) is the sign of the earth
Would be great to have it as well
Thanks for considering

**Comment by aethior** [comment]
Gender Icons were added in v4.3. (cc @tagliala)
