### ISSUE TITLE
Feature request: Place to contribute layered icons

### ISSUE THREAD

**Issue by CTiedeman** [FortAwesome/Font-Awesome#13863]
It would be nice to have a place to contribute layered icons so that other people can easily reuse them.  It may also cut down on new icon requests if a readily available layered one already exists.

Example of layered insert row above/below:  https://codepen.io/ctiedeman/pen/zJNmRL

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IMHO this is a fantastic idea 👍 

We could start with community managed wiki page

@talbs any thoughts?

**Comment by InsanityMeetsHH** [comment]
I made a page where people can add her snippets.
https://github.com/FortAwesome/Font-Awesome/wiki/Layering-and-Masking-snippets

**Comment by sensibleworld** [comment]
Wanted to pop into this old issue and let you know that we now have the icon wizard, which may solve some of these issues: https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader
