### ISSUE TITLE
Icon request: spell-check

### ISSUE THREAD

**Issue by kmhan0693** [FortAwesome/Font-Awesome#13862]
### What can it be used for?

For in an editor. It can be used for a spell checker

### Example image (optional)

![image](https://user-images.githubusercontent.com/42868082/44913116-60c31800-acfa-11e8-8b28-ae7b35ff0d14.png)

### Icon request checklist

- [x] This is a single icon  (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @kmhan0693,

This icon was added in v5.9.0.
Check https://fontawesome.com/icons/spell-check

Regards.

cc/ @tagliala
