### ISSUE TITLE
Icon Request: icon-bread

### ISSUE THREAD

**Issue by muonghoa** [FortAwesome/Font-Awesome#1386]
Hi, 
I let you guys imagine food icons, 
my contribution would be a piece of bread, what about yours ?

![3](https://f.cloud.github.com/assets/3533768/690303/2c1b9c6e-dadf-11e2-916d-cdfdcee36fc1.jpg)

Thanks for considering

**Comment by lbruschi** [comment]
+1

**Comment by nicho90** [comment]
+1

**Comment by dimoned** [comment]
+1

**Comment by hdbarahona** [comment]
+1. I need it for celiac people

**Comment by nextlevelshit** [comment]
+1 :+1:

**Comment by holtkamp** [comment]
+1 :+1:

**Comment by G-Driver** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by Crissov** [comment]
- 🍞 [U+1F35E](http://emojipedia.org/bread/) Unicode emoji #222 
- 🥖 [U+1F956](http://emojipedia.org/baguette-bread/)

**Comment by aqt01** [comment]
+1

**Comment by t3s** [comment]
+1

**Comment by sensibleworld** [comment]
I'm not sure if these contain gluten or not:

https://fontawesome.com/icons/bread-loaf?style=solid
https://fontawesome.com/icons/bread-slice?style=solid

**Comment by sowenjub** [comment]
🥖 would be a nice addition to the existing bread icons.

**Comment by tagliala** [comment]
@sowenjub feel free to open a new request `fa-baguette`
