### ISSUE TITLE
Strict math compatibility for Less

### ISSUE THREAD

**Issue by halfninja** [FortAwesome/Font-Awesome#13861]
### Describe the problem

For those of us running Less builds with strictMath turned on, importing FA5 results in a few broken rules, because some math operations are left as-is in the CSS.

With strict math, Less only does math if it's inside parentheses, otherwise it assumes it's for the browser to process as CSS. It's a global Less option so it's not possible to disable it for parts of a build.

Example from `_list.less`:

`margin-left: @fa-li-width * 5/4;`
becomes
`margin-left: (@fa-li-width * 5/4);`

### What version and implementation are you using?

Version: 5.3.1
Less 3.8.1 with http://lesscss.org/usage/#less-options-math

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

In a new project with `less` and `@fortawesome/fontawesome-free` installed from NPM:

```
$ npx lessc node_modules/@fortawesome/fontawesome-free/less/fontawesome.less | fgrep -A3 ".fa-ul {"
.fa-ul {
  list-style-type: none;
  margin-left: 2.5em;
  padding-left: 0;

$ npx lessc node_modules/@fortawesome/fontawesome-free/less/fontawesome.less -m=strict | fgrep -A3 ".fa-ul {"
.fa-ul {
  list-style-type: none;
  margin-left: 2em * 5/4;
  padding-left: 0;
```

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Thanks @halfninja we just missed this in one place that I can see. I've got a fix in our build system.

**Comment by tagliala** [comment]
@robmadole I think this has not been fixed yet: https://github.com/FortAwesome/Font-Awesome/blob/5.7.2/less/_list.less#L6

**Comment by robmadole** [comment]
Ok, I _really_ think I have it fixed in our build system now 😄
