### ISSUE TITLE
Add new icon

### ISSUE THREAD

**Issue by gaurav-Mann** [FortAwesome/Font-Awesome#13877]
as i searched you dont have a blogger icon in fa fa-icon class so i request you to please add this so we can use this from the same API.
![blogger-b-brands](https://user-images.githubusercontent.com/42924131/44967551-c532e100-af5f-11e8-89f8-d5724ea2081a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Blogger is already here: https://fontawesome.com/icons?d=gallery&q=blogger

Please make sure you are using the latest version of Font Awesome

Closing here
