### ISSUE TITLE
Icon request: what3words

### ISSUE THREAD

**Issue by Ancinek** [FortAwesome/Font-Awesome#13873]
Logo for an app, that converts geolocation to 3 unique words, with precision to 3 meters. I guess this is going to be a thing in a while and people will want to introduce their own 3 words address on their websites/ mobile apps.

Link to their website:
[what3words](https://map.what3words.com/)

**Comment by kawaiidesune** [comment]
+1

**Comment by jasonhibbs** [comment]
Dupe: https://github.com/FortAwesome/Font-Awesome/issues/13615

**Comment by tagliala** [comment]
@jasonhibbs thanks, I've missed this one
