### ISSUE TITLE
font-awesome@4.7.0 missing main in package.json

### ISSUE THREAD

**Issue by FDiskas** [FortAwesome/Font-Awesome#13870]
Please provide [main](https://docs.npmjs.com/files/package.json#main) setting in `package.json` file pointing to core scss file.
It will be more easy to use it like:
```jsx
import 'font-awesome';
```
vs
```jsx
import 'font-awesome/scss/font-awesome.scss';
```

Good example https://unpkg.com/bulma@0.7.1/package.json

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but we do not have any official NPM version of Font Awesome 4.

Hope it helps

Closing here

**Comment by Alfred-kai** [comment]
please provide main setting in package.json file pointing to core scss file,it will be more easy like this:
import 'font-awesome',instead of  import 'font-awesome/css/font-awesome.css'

**Comment by tagliala** [comment]
@Alfred-kai sorry, but we do not have any official NPM version of Font Awesome 4.

AFAIK, our official FA5 packages have both main and style properties

If you find issues in our official FA5 packages, feel free to open a new request

Locking here 🔒
