### ISSUE TITLE
Icon Request: icon-sanitation

### ISSUE THREAD

**Issue by muonghoa** [FortAwesome/Font-Awesome#1387]
Hi, 
Would use this if there would be something similar

![1](https://f.cloud.github.com/assets/3533768/690306/671b8dec-dadf-11e2-940a-52e1d2df0c5a.jpg)

Thanks for considering

**Comment by dangnelson** [comment]
+1 Hand Washing Icon / Sanitation

I would use this along side copy regarding sanitation.

![hanwash](https://cloud.githubusercontent.com/assets/8430446/6342726/3d3c4396-bbab-11e4-9ccf-f148c8beb18a.png)

**Comment by phpforfree** [comment]
+1

**Comment by aethior** [comment]
Hi @muonghoa ,

These icons were added in v5.0.9 and v5.13.0.
Check https://fontawesome.com/icons/hand-holding-droplet and https://fontawesome.com/icons/hands-bubbles.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks for the heads up!
