### ISSUE TITLE
Clearer CDN documentation needed

### ISSUE THREAD

**Issue by davidekarasek** [FortAwesome/Font-Awesome#13871]
### Describe the problem

1. CDN link is generating a 503 from our server:
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.3.0/css/all.css" integrity="sha384-yXyaKVWGB2SyDoYATyErcgoNH1iAnnf8fCXejZM4NYUbhWiGkZoMwh6IoJ4v5ogi" crossorigin="anonymous">

2. For local references, please name your stylesheet to something other than "all" preferably containing font-awesome, and use standard version such as "font-awesome-5.3.0.css"

Thanks.

### What did you expect?

No errors in console

### What version and implementation are you using?

Version: 5.03 pro
Browser and version: Chrome on Windows 7 Version 68.0.3440.106 (Official Build) (64-bit)

- [ ] SVG with JS
- [x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ x] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
