### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by rsa408** [FortAwesome/Font-Awesome#13879]
Hi
Unfortunately, I cannot buy FA from Iran. but I am using FA and I would like to ask you to add some collections, Please.
Shoe and Wears, underwears (men, women)
More store types (plant store, bookstore, pet store, drug store)
More building types( malls, towers, medical buildings, government buildings, pools or etc)
Public or private locations icons

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

> Unfortunately, I cannot buy FA from Iran

@davegandy @robmadole can we do something about that?

**Comment by rsa408** [comment]
Hi,
'Unfortunately, I cannot buy FA from Iran' is not my pleasure, this is my problem. I only wish to suggest more icons to FA gain better collections than others,  I already solved my problem with SVG Icons. but FA desires to be more comprehensive than others.

**Comment by rsa408** [comment]
Ok, let me ask in this way, I would like if I wish to design my requested fonts how can I do that in FA standards, Then I can share them with FA. 

Using SVG makes my app lazy loading but with iconic fonts, it is faster.


### What can it be used for?
Shoe and Wears, underwears (men, women):
To showing specific fashion stores: I hve used the some of following pack of Icons:
![image](https://user-images.githubusercontent.com/4402631/44995655-57b39e80-afb9-11e8-905e-c1a348be6371.png)

Buildings
To showing hospital or medical buildings, educational buildings gov buildings affairs


![image](https://user-images.githubusercontent.com/4402631/44995753-c8f35180-afb9-11e8-9654-c535ebaf4e2d.png)

Stores and shops:
Individual shops or stores and places of services some may look like: 
![image](https://user-images.githubusercontent.com/4402631/44996112-5daa7f00-afbb-11e8-8b3e-79a033b96025.png)



### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
@rsa408 sorry but your request doesn't meet our contributing guidelines

>  This is a single icon or matched pair (Ex: lock / unlock)

You cannot request a set of icons and

> I have searched for existing issues and to the best of my knowledge this is not a duplicate

There are duplicates
