### ISSUE TITLE
Icon request: united-nations

### ISSUE THREAD

**Issue by oliver-ni** [FortAwesome/Font-Awesome#13878]
### What can it be used for?

Represent the United Nations, icons for links, etc etc

### Example image (optional)

![United Nations](https://upload.wikimedia.org/wikipedia/commons/e/e9/Logo_of_the_United_Nations_%28B%26W%29.svg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Repost of #2604. But that issue is really old and hasn't gotten much attention at all. I hope this is okay

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Repost of #2604. But that issue is really old and hasn't gotten much attention at all. I hope this is okay

As per our contributing guidelines, you have to add a 👍 reaction to #2604

Closing here
