### ISSUE TITLE
Icon request: Harry Potter house symbols and symbols on banners

### ISSUE THREAD

**Issue by TheTechmo** [FortAwesome/Font-Awesome#13889]
### What can it be used for?

Badges to show what house you're in, banners for perhaps labels.

### Example image

Google Lol

_(Sorry if I did this wrong, it's my first request!)_

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
