### ISSUE TITLE
Unable to use one of the icons <i class="fal fa-users-class"></i>

### ISSUE THREAD

**Issue by iamcavic** [FortAwesome/Font-Awesome#13880]
I am a pro package subscriber, I am working locally on a project where I have downloaded pro css and I am hosting it my self. One of the icons is not showing up even with a 5.3.1 version dowload
<i class="fal fa-book"></i>

![image](https://user-images.githubusercontent.com/10718350/44978823-d7ddf380-af28-11e8-8269-74f8d6463e20.png)

![image](https://user-images.githubusercontent.com/10718350/44978889-f9d77600-af28-11e8-8456-12472f067212.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Meanwhile, I advise you to double check that you are using Font Awesome >= 5.2.0.

Both font files and css files have to be updated. If you are hosting on you own server, you also need to make sure that there aren't cache issues.

**Comment by iamcavic** [comment]
@tagliala  You are right I missed to update webfonts folder with the new files I only uploaded css... My bad thank you... everything is fine

**Comment by tagliala** [comment]
@iamcavic you're welcome, glad you solved 👍
