### ISSUE TITLE
faBalanceScale missing in @fortawesome/free-regular-svg-icons@^5.3.1

### ISSUE THREAD

**Issue by azbshiri** [FortAwesome/Font-Awesome#13896]
Hey, you did a great job creating `FontAwesomeIcon` component. Today I wanted to use `faBalanceScale` in a regular form but it seems it's missing in `@fortawesome/free-regular-svg-icons@^5.3.1` package.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per https://fontawesome.com/icons/balance-scale?style=solid, fa-balance-scale in regular is not available for Font Awesome Free

Hope it helps

Closing here
