### ISSUE TITLE
Icon request: Windows (House windows)

### ISSUE THREAD

**Issue by marcoraimondi** [FortAwesome/Font-Awesome#13892]
### What can it be used for?

Used for domotic application, to know how many windows are open and how many are closed

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
A pair: Open /Closed

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)

- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
not  a duplicate 

- [x] I have included at least one example image if it could be helpful (optional)
yes

- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
yes

**Comment by sensibleworld** [comment]
Do these work? https://fontawesome.com/icons?d=gallery&q=window-frame

**Comment by marcoraimondi** [comment]
Thanks,
Could you please add

Windows Frame with Blinds Open
Windows Frame with Blinds Partially Open
Windows Frame with Blinds Closed

?

Il giorno gio 12 dic 2019 alle ore 16:18 Jory Raphael <
notifications@github.com> ha scritto:

**Comment by sensibleworld** [comment]
You mean like these? https://fontawesome.com/icons?d=gallery&q=blinds&c=household :)

**Comment by dresende** [comment]
It would be great to have more levels of the blinds, similar to radio signal or battery capacity. The 2 that exist now (blinds and blinds-raised) look very good, but would be awesome to have blinds at 3/4 and 1/4 open.
