### ISSUE TITLE
fas fa-book-reader

### ISSUE THREAD

**Issue by Alexander-Kreisler** [FortAwesome/Font-Awesome#13909]
fas fa-book-reader is unavailable.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/book-reader?style=solid has been introduced in FA 5.2.0. Please make sure that you are using FA >= 5.2.0

Demo: https://jsfiddle.net/tagliala/j3gakye6/1/

If you still think there are issues with font awesome, please fill our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case
