### ISSUE TITLE
UIFontWeightTrait not set on iOS

### ISSUE THREAD

**Issue by hampustagerud** [FortAwesome/Font-Awesome#13900]
### Describe the problem

I am maintaining the FontAwesome 5 part of [`oblador/react-native-vector-icons`](https://github.com/oblador/react-native-vector-icons) in which we currently use hacks to get the right style to be chosen by React Native.

In the core of React Native it uses the ```UIFontWeightTrait``` trait to compare fonts of the same family. However, all Font Awesome 5 fonts are reporting a font weight of 0 which makes it impossible to predict (or choose) which style will be used to render the icon.

We are using the ```*.ttf``` files but ```.otf``` has the same problem.

### What did you expect?

I would like the ```UIFontWeightTrait``` to differ between the different styles in order for Xcode and React Native to be able to select the fonts natively.

### What version and implementation are you using?

Version: 5.3.1 (Pro and Free)

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

### Reproducible test case

I use the following code to check traits:

```objc
for (NSString *family in [UIFont familyNames]) {
  if ([family hasPrefix:@"Font Awesome 5"]) {     
    for (NSString *fontName in [UIFont fontNamesForFamilyName:family]) {
      UIFont *font = [UIFont fontWithName:fontName size:12];
        
      NSLog(@"%@", fontName);
      NSDictionary *traits = [font.fontDescriptor objectForKey:UIFontDescriptorTraitsAttribute];
      for (NSString *key in traits.allKeys)
        NSLog(@"\t%@: %@", key, [traits valueForKey:key]);
    } 
  }
}
```

Which produces:

<img width="274" alt="screenshot" src="https://user-images.githubusercontent.com/3395492/45155433-46e27300-b1db-11e8-9b2e-1f51d929c882.png">

Brands are never an issue since they have a different family name.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Possibly related to: #13557

**Comment by tagliala** [comment]
> which could mean that the files might end up being used on the web

Can you do the same with `.woff2` or `.woff`?

**Comment by hampustagerud** [comment]
This is currently no option and really shouldn't make a difference. Other fonts are working fine using ```.ttf```, ```.otf``` could be an option but ```.ttf``` would be preferable.

**Comment by robmadole** [comment]
<img width="327" alt="traits" src="https://user-images.githubusercontent.com/132895/50702228-e0992000-1015-11e9-9a68-b39eba7f7367.png">

@hampustagerud does this help? These are the numbers from what will be `5.7.0`.

**Comment by hampustagerud** [comment]
@robmadole Yes, this looks correct 🙌 I think it is the very same values that are set after we manually modify the font information before loading the font but this should render most of the hack redundant! Is there an ETA for 5.7.0? 🙂

**Comment by robmadole** [comment]
@hampustagerud we will probably be releasing 5.7.0 this week but don't hold my feet to the fire on that one.

**Comment by hampustagerud** [comment]
@robmadole That was sooner than I expected anyways, sounds awesome (😬)! Thanks for the reply and hard work put into the font!

**Comment by tagliala** [comment]
Font Awesome 5.7.0 has been just released. Could you please test and provide feedback?

**Comment by hampustagerud** [comment]
I can confirm that the numbers are now correct on iOS which now seems able to distinguish between the fonts by choosing Thin, Normal or Bold font 🙂

Thank you @tagliala and @robmadole, this issue seems resolved 🙌
