### ISSUE TITLE
fa-user-chart icons do not display

### ISSUE THREAD

**Issue by jmbronson** [FortAwesome/Font-Awesome#13906]
Pretty self-explanatory given the title. 'far', 'fal', and 'fas' all have the same issue. Please fix - I paid for the PRO version!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/user-chart?style=solid has been introduced in FA 5.3.0 Pro, could you please double check that you are using Font Awesome 5.3.0 or 5.3.1?

If this doesn't help, please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
