### ISSUE TITLE
the youtube icon does not display as shown on your website as only the play button. it shows the full text icon displaying the actual words youtube. i am using the latest version of FA within a wordpress website. all browsers on latest versions.

### ISSUE THREAD

**Issue by LarsFinley** [FortAwesome/Font-Awesome#13905]
### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by InsanityMeetsHH** [comment]
if you see this https://fontawesome.com/v4.7.0/icon/youtube then you have FA >= 3.2 < 5.
Maybe a plugin loads an old version into your website and overwrites your FA 5 integration.
You have to check the css files which on your rendered website.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@InsanityMeetsHH is right. Please check that your plugins are not loading an older version of Font Awesome.

Ref:
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
- https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting

Also, we do not support third party plugins

Hope it helps

Closing here
