### ISSUE TITLE
Icon request: icon-kinect 

### ISSUE THREAD

**Issue by cvkef** [FortAwesome/Font-Awesome#1390]
How about an icon for the Kinect for Windows/XBOX?

Example
http://thenounproject.com/noun/kinect/#icon-No9424

**Comment by aethior** [comment]
@tagliala `devices-hardware (category)` label for this request?

**Comment by aethior** [comment]
>Microsoft formally announced it would stop manufacturing Kinect for Xbox One on October 25, 2017. Microsoft eventually discontinued the adapter in January 2018, stating that they were shifting to manufacture other accessories for the Xbox One and personal computers that were more in demand. This is considered by the media to be the point where Microsoft ceased work on the Kinect for the Xbox platform. ([more info](https://en.wikipedia.org/wiki/Kinect))

cc/ @tagliala
