### ISSUE TITLE
Firefox - Dropdown-list + font-family:font-awesome 5 = partial work (work perfect on chrome)

### ISSUE THREAD

**Issue by jokamax** [FortAwesome/Font-Awesome#13912]
Hi,

On the last versions of fontawesome there is a problem in dropdown-list.
The selected item is OK, but the open list is NOK

Code : 
```
<div class="right-line-dbox">
                <select style="font-family: 'Font Awesome 5 Free', 'Font Awesome 5 Brands', Helvetica;" class="form-control form-control-special">
                  <option value="expword">&#xf1c2; &nbsp; WORD (.docx)</option>
                  <option value="exppdf">&#xf1c1; &nbsp; PDF (.pdf)</option>
                  <option value="exptxt">&#xf15c; &nbsp; TEXT (.txt)</option>
                  <option value="exphtml">&#xf13b; &nbsp; HTML (.html)</option>
                  <option value="expmd">&#xf1c9; &nbsp; MARKDOWN (.md)</option>
                </select>
</div>
```

With Firefox 61.0.2 :
![image](https://user-images.githubusercontent.com/6458818/45219509-cd6a8380-b2b3-11e8-816b-eb3e630ba3b2.png)

With Chrome : 
![image](https://user-images.githubusercontent.com/6458818/45219770-b37d7080-b2b4-11e8-9822-8a7fbb68dbfc.png)

Thanks by advance,

Jonathan

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but this feature is not supported.

Please use a javascript dropdown plugin like https://select2.org/

Ref: #996
