### ISSUE TITLE
Icon Request: icon-python

### ISSUE THREAD

**Issue by alsoicode** [FortAwesome/Font-Awesome#1391]
It would also be cool to have one for Django.

**Comment by christianhujer** [comment]
+1

**Comment by tagliala** [comment]
ffffff!!!

closing this in favour of #1391 which has more +1s.

Sorry @alsoicode

**Comment by meyersbs** [comment]
+1

**Comment by tagliala** [comment]
🔒 https://github.com/FortAwesome/Font-Awesome/issues/1391#issuecomment-77473940
