### ISSUE TITLE
Icon not rendering: users-cog

### ISSUE THREAD

**Issue by Mxater** [FortAwesome/Font-Awesome#13924]
I put version 5.3.1 in my page, and the icon **users-cog** don render
![imagen](https://user-images.githubusercontent.com/4630666/45259105-4d1f4d80-b39b-11e8-9f06-a1caeca8c11a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can't reproduce: https://jsfiddle.net/tagliala/j3gakye6/3/

Please double check that you are using Font Awesome >= 5.0.11

There could be other plugins in our website that are overriding your Font Awesome with an older version

Ref:
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

If you still think there is an issue with Font Awesome, edit this request following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and include a reproducible test case

**Comment by Mxater** [comment]
Hello, I used **i** as in the example given by fontawesoma.com
![imagen](https://user-images.githubusercontent.com/4630666/45266465-b5b90980-b431-11e8-9732-a1bb8f2b3e1e.png)
![imagen](https://user-images.githubusercontent.com/4630666/45266467-c7021600-b431-11e8-8297-ce187576e9c5.png)

But, I see, if I use **span** instead **i** like you, this work correctly
![imagen](https://user-images.githubusercontent.com/4630666/45266477-e7ca6b80-b431-11e8-8f80-59be84943f13.png)

**Comment by tagliala** [comment]
Please check your stylesheet, you may have conflicting rules for `<i>` tag.

Take another look at this checklist:
- [ ] Double check that you are using Font Awesome >= 5.0.11
- [ ] Double check that there aren't plugins/themes in our website that are overriding your Font Awesome with an older version
- [ ] If you still think there is an issue with Font Awesome, provide a reproducible test case

**Comment by Mxater** [comment]
I find the problem,
I use Font Awesome 5.3.1
Dont override FA with plugins or themes.

The problem is `font-weight: normal !important;`

https://jsfiddle.net/gpwd6Lyh/2/

**Comment by tagliala** [comment]
> The problem is font-weight: normal !important;

Please remove that rule because font awesome uses font-weight to select style.
