### ISSUE TITLE
Compile SASS version (web 5.2.0)

### ISSUE THREAD

**Issue by macagoraga** [FortAwesome/Font-Awesome#13926]
When compile sass version without changing anything, so keeping default variables, the path compiled appear like:

src: url(/fonts/fa-light-300.eot?ff09619bd2670851ff2e9022649140b0);

/fonts/ and not ../webfonts

**Comment by macagoraga** [comment]
Still the same also with 5.3.1

I am using laravel mix.

```js
let mix = require('laravel-mix');
mix.sass('resources/assets/sass/default/vendor/fontawesome/fontawesome.scss', 'public/assets/css');
```

fontawesome.scss contain:

```
@import 'fontawesome-pro-5.3.1-web/scss/fontawesome';
@import 'fontawesome-pro-5.3.1-web/scss/light';
```

But even if I include directly like below doesn't work:

```
mix.sass('resources/assets/sass/default/vendor/fontawesome/fontawesome-pro-5.3.1-web/scss/fontawesome.scss', 'public/assets/css');
```

In this case I also add:

```
@import 'variables';
@import 'mixins';
@import 'core';
@import 'larger';
@import 'fixed-width';
@import 'list';
@import 'bordered-pulled';
@import 'animated';
@import 'rotated-flipped';
@import 'stacked';
@import 'icons';
@import 'screen-reader';
@import 'light'; // added for testing
```


What I notice is that a /fonts/ folder is created in /public folder of Laravel.

I am using `npm run dev` command.

See screenshot on left there is folder "fonts" generated after compilation.
And see that path is wrong "/fonts" while default in variable is "web-fonts"

![screenshot from 2018-09-10 18-11-27](https://user-images.githubusercontent.com/5359394/45310214-fa25d180-b525-11e8-973f-121e9e5571c1.png)

**Comment by tagliala** [comment]
Maybe there is a plugin in your rollup/webpack (what laravel mix is actually using under the hood) configuration that copies asset and changes folder to reference them. I think that's the correct approach, I can also see a hash fingerprint after the `?`, which is not part of the Font Awesome scss.

I can't help on this specific case, leaving this open for feedback from the community

**Comment by macagoraga** [comment]
Ok, I will check that. Thanks
