### ISSUE TITLE
Icon request: portfolio, portfolio-open

### ISSUE THREAD

**Issue by ATLAdamL** [FortAwesome/Font-Awesome#13923]
### What can it be used for?

Links to portfolio pages and galleries

### Example image (optional)

Closed: 
![portfolio_icon-closed](https://user-images.githubusercontent.com/43093110/45255075-fa6c7400-b34f-11e8-8fda-d3c19606f427.png)

Open:
![portfolio_icon-open](https://user-images.githubusercontent.com/43093110/45255080-0821f980-b350-11e8-9ed5-58ca57a1178d.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ATLAdamL** [comment]
Dear Geremia,

I totally understand why you would recommend the folder icons! And, yes—those are very close! But the file folder bespeaks something much more corporate and document-related than a portfolio, which communicates artwork and design projects. So, more like this <https://www.jerrysartarama.com/creative-inspirations-portfolio?gclid=Cj0KCQjw5s3cBRCAARIsAB8ZjU04mI4wFjT7pD_Xhd-gjNb64CKkMqjgmYdVfgeRInYGFGfYP-KO9TIaAioXEALw_wcB> than this <https://www.uline.com/Product/Detail/S-19528/File-Folders/File-Folders-Letter-Manila?pricode=WB1254&gadtype=pla&id=S-19528&gclid=Cj0KCQjw5s3cBRCAARIsAB8ZjU1ZB9AqchyxNNxqjVe6xf-NlvlZycj1WoygrQKgmp_MCEpprpXb1NUaAkP-EALw_wcB&gclsrc=aw.ds>.

Does that clarify?




Adam

**Comment by tagliala** [comment]
@ATLAdamL yes, it does

I need to know:

- Are you requesting a single icon or two icons?
- What is the name of the object in the image? Art folder? (I'm not an English native speaker)

**Comment by ATLAdamL** [comment]
No worries!

Two icons: the portfolio closed and the portfolio open. I notice that, in many cases, FontAwesome provides a solid and an outlined version of its icons. If that were to apply in this case, then it would amount to four icons, total.
I think the standard term for it is just "portfolio!" While that word also has other meanings, if you were to do a web search on it, you'll find many hits that lead to this sort of case. In fact, Wiktionary offers it as the first definition of the word: https://en.wiktionary.org/wiki/portfolio 


Hope that's helpful!




Yours,

Adam

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
