### ISSUE TITLE
Icon Request: icon-google-drive

### ISSUE THREAD

**Issue by courthead** [FortAwesome/Font-Awesome#1393]
Now that there are icons for services such as Dropbox and Trello, I'd really like to see a Google Drive icon. I think a very common use-case for such icons is for those who are making services that allow users to import files from other applications, and Drive is almost always an option. The attachment below contains a good example of a monochromatic Drive icon:

![image](https://f.cloud.github.com/assets/148083/691515/9dd8180c-db91-11e2-88a6-965d7d729d37.png)

Thanks!

**Comment by jjaymerica** [comment]
+1

**Comment by rhythmus** [comment]
+1

**Comment by tagliala** [comment]
locking here, this is a duplicate of #835

:lock:
