### ISSUE TITLE
/F067 Plus doesn't work unicode

### ISSUE THREAD

**Issue by meganearnshaw** [FortAwesome/Font-Awesome#13932]
Example of one that does work:

`.angry:before{
font-family: 'Font Awesome\ 5 Free';
  content: "\f556";
`

Example of the plus sign not working:

`.plus:before {
  font-family: 'Font Awesome\ 5 Free';
  content: "\f067";
`

ex) https://codepen.io/anon/pen/JaLmZx

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Remember to set the `font-weight: 900;` property

https://codepen.io/anon/pen/vzjBzB

Ref: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here
