### ISSUE TITLE
Icon request: liquid-soap

### ISSUE THREAD

**Issue by cembranel** [FortAwesome/Font-Awesome#13931]
### What can it be used for?

I want to use in my website about cleaning supplies sales.
Is apreciated to describe higiene category items.

### Example image

<img src="https://www.shareicon.net/data/128x128/2016/11/15/853274_soap_512x512.png" />

**Comment by Crissov** [comment]
Related Unicode emoji #222:

- [🧴](https://emojipedia.org/lotion-bottle/) U+1F9F4 Lotion Bottle

**Comment by jeisel-northglenn** [comment]
This is kind of important with all the coronavirus stuff going around.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pump-soap?style=solid
