### ISSUE TITLE
Icon request: badge-euro

### ISSUE THREAD

**Issue by DavydeVries** [FortAwesome/Font-Awesome#13939]
### What can it be used for?
Discount on products or services in a web store. Instead of a dollar other currencies.

### Example image (optional)
See [badge-dollar](https://fontawesome.com/icons/badge-dollar?style=solid)

### Full list of types:
- badge-euro
- badge-pound
- badge-ruble
- badge-rupee
- badge-yen
- badge-won
- badge-lira
- others?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
