### ISSUE TITLE
Icon request: pulse

### ISSUE THREAD

**Issue by TheBuky** [FortAwesome/Font-Awesome#13934]
Hi,

Makes it's possible to add pulse icon?

![image](https://png.icons8.com/ios/1600/pulse-filled.png)

I know you already have "signature" but it's more rounded then a pulse icon.
Thank

**Comment by TheBuky** [comment]
Oh yes he can do the job, but you'll have to offer me the pro version :D 
May be, we can add a link for "pulse" and "activity" in the documentation to "heart-rate"?

**Comment by r-man** [comment]
+1

**Comment by aethior** [comment]
Can we considered this issue solved?

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, I can consider this closed by https://fontawesome.com/icons/wave-pulse?s=solid
