### ISSUE TITLE
Icon request: icon-alarm-sensor

### ISSUE THREAD

**Issue by Cysioland** [FortAwesome/Font-Awesome#1394]
Hi.
It would be good if Font Awesome had alarm sensor icon.
It could be useful for intelligent home control panels, websites, etc.
![Alarm sensor](http://www.o-digital.com/uploads/2226/2232-1/Alarm_Sensors_TC_al6_98.jpg)

**Comment by sensibleworld** [comment]
<img width="650" alt="Screen Shot 2021-03-30 at 1 29 59 PM" src="https://user-images.githubusercontent.com/529604/113030847-07465280-915c-11eb-9cfe-398ae1eee363.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
