### ISSUE TITLE
Icon request: home-secure

### ISSUE THREAD

**Issue by li-tin** [FortAwesome/Font-Awesome#13948]
### What can it be used for?
When linking to home pages that are using https or otherwise noting that home is secure

### Example image (optional)
https://www.shareicon.net/security-interface-secure-home-houses-house-703389
![image](https://user-images.githubusercontent.com/5340366/45570403-73b80b00-b817-11e8-85de-3b9b1d7cdc78.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) --> There is already a home/house icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @li-tin,

We can considered this request solved with https://fontawesome.com/icons/house-lock?

Regards.

cc/ @tagliala
