### ISSUE TITLE
The unicode for the lock icon isn't working

### ISSUE THREAD

**Issue by cmarydai** [FortAwesome/Font-Awesome#13949]
### Describe the problem
Trying to use the lock icon https://fontawesome.com/icons/lock?style=solid unicode for a CSS pseudo class and it is showing up as a square.

### What did you expect?

I expected to see a lock icon

### What version and implementation are you using?

Version: 4.0.7
Browser and version: chrome Version 68

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://codepen.io/cmarydai/pen/GXBdor

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

https://github.com/FortAwesome/Font-Awesome/issues/12682 Tried this fix and it didn't work

**Comment by cmarydai** [comment]
I just noticed when I put font-weight: 300 it works. This doesn't seem to correspond to what is said to do in the docs though https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements because 300 is supposed to be for light and I'm trying to use solid.

**Comment by InsanityMeetsHH** [comment]
> Version: 4.0.7

You are mixing FA 4 with FA 5 syntax and this could bring you problems.
Here is the FA 4 docu: https://fontawesome.com/v4.7.0/

**Comment by tagliala** [comment]
@InsanityMeetsHH thanks

Fixed codepen: https://codepen.io/anon/pen/NLBBwb

**Comment by cmarydai** [comment]
Awesome thanks. You might want to fix this doc too https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by tagliala** [comment]
@cmarydai you're welcome

https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements contains documentation for font awesome 5

CSS pseudoelements are not documented for version 4. You can find documentation for Font Awesome 4 at https://fontawesome.com/v4.7.0/
