### ISSUE TITLE
ESOCKETTIMEDOUT for free-solid-svg-icons 5.3.1

### ISSUE THREAD

**Issue by KrisB1022** [FortAwesome/Font-Awesome#13958]
### Describe the problem

Attempting to download free-solid-svg-icons package. 
I get the following error with ```yarn add @fortawesome/free-solid-svg-icons```

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.3.1.tgz: ESOCKETTIMEDOUT".
```

### What did you expect?

Expected the package to download and resolve.

### What version and implementation are you using?

Version: 5.3.1 (package) 1.9.4 (yarn) 8.11.3 (node)

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Add package ```yarn add @fortawesome/free-solid-svg-icons```
Error times out after 4 attempts.

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by KrisB1022** [comment]
Appears to have been an intermittent issue and has now been resolved.

**Comment by captDaylight** [comment]
I'm seeing the same thing with 5.5.0

**Comment by balajibrk** [comment]
For me also the same thing occur, how to solve this ..? @KrisB1022 
![Screenshot (3)](https://user-images.githubusercontent.com/32443133/62832772-7c94a500-bc51-11e9-96b4-99f23a4d9494.png)

**Comment by tagliala** [comment]
@balajibrk the free npm packages are hsoted on `registry.yarnpkg.com`, and we do not have control on that.

https://status.yarnpkg.com/ does not report issues, so it could also depend on your provider

I think it's a temporary network issue, please check your network connection and try again later

I cannot replicate this from Italy

```
 $ yarn upgrade
yarn upgrade v1.17.3
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @fortawesome/fontawesome-free@5.10.1
info All dependencies
└─ @fortawesome/fontawesome-free@5.10.1
✨  Done in 1.28s.
```

**Comment by balajibrk** [comment]
Issue solved by increasing the network timeout in .yarnrc file `yarn config set network-timeout 600000 -g`
`

**Comment by balajibrk** [comment]
Issue solved by increasing the network timeout in .yarnrc file `yarn config set network-timeout 600000 -g`
`

**Comment by wallasdevpy** [comment]
> Issue solved by increasing the network timeout in .yarnrc file `yarn config set network-timeout 600000 -g`
> `


2020/07
It worked this solution!
Thank you!!!

**Comment by savvior-ladieu** [comment]
I have searched for this solution for a long time. It makes me feel silly now that i know what it is. It took almost 3 minutes for yarn to install font-awesome.. no idea why as I am the only one in the office that has this issue.

**Comment by mom4uk** [comment]
> Issue solved by increasing the network timeout in .yarnrc file `yarn config set network-timeout 600000 -g`
> `

It worked
