### ISSUE TITLE
Icon Request: driver

### ISSUE THREAD

**Issue by el-duderino5** [FortAwesome/Font-Awesome#13959]
Would love to have an icon that represents a driver. Maybe something like this? 
![image](https://user-images.githubusercontent.com/6808300/45654249-e55ab800-baa8-11e8-8f0f-6b6078b8735a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #7743, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
