### ISSUE TITLE
FontAwesome.com stays blank with Ghostery plugin (Google Analytics)

### ISSUE THREAD

**Issue by Ionaru** [FortAwesome/Font-Awesome#13952]
### Describe the problem

The https://fontawesome.com website stays blank when Ghostery plugin is enabled.
It seems blocking the "Google Analytics" part is causing this issue.
This only applies to the home page, other pages like https://fontawesome.com/icons do work normally.

### What did you expect?

I'd like the website to work without forcing tracking on me.

### What version and implementation are you using?

Version: -
Browser and version: Chrome 69

### Reproducible test case

1. Add Ghostery plugin for Chrome & block everything during setup
2. Open https://fontawesome.com

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate with the default installation of Ghostery

Chrome 69.0.3497.92 / Windows 10 / Ghostery 8.2.4

Screenshot attached: (sorry for being so Italian)
![image](https://user-images.githubusercontent.com/556268/45590444-161bdf80-b939-11e8-8049-4be42b6442f4.png)

**Comment by Ionaru** [comment]
I don't know much Italian but I don't think your plugin is blocking anything by default.
Mine looks like this:
![image](https://user-images.githubusercontent.com/3472373/45596199-8a499800-b9b8-11e8-8230-626dc620588d.png)

**Comment by hudri** [comment]
Having the same issue, not using Ghostery though. Using Chrome and Adblock Plus here.

**Comment by hudri** [comment]
Additional information: Error message on console:

`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT https://m.servedby-buysellads.com/monetization.js
`
Disabling ABP does NOT help. Sub pages do load, with and without ABP

**Comment by Ionaru** [comment]
Seems to be resolved as of 2018-12-08, the page is displaying fine again! 😃

**Comment by Ionaru** [comment]
The https://fontawesome.com/ page stopped working again, looks like the same issue as before.

**Comment by tagliala** [comment]
@Ionaru thanks for the heads-up

I can confirm

**Comment by robmadole** [comment]
I’ve got a fix for this on its way

**Comment by robmadole** [comment]
This should be resolved now. @lonaru @tagliala when you get a moment can you double-check?

**Comment by Ionaru** [comment]
Looks good & resolved to me!

**Comment by tagliala** [comment]
Works for me too 👍
