### ISSUE TITLE
Icon request: money-check-pen (or modification to existing check) 

### ISSUE THREAD

**Issue by garnerv** [FortAwesome/Font-Awesome#13964]
### What can it be used for?

@sensibleworld and anyone else who worked on the icon in #2603 - thanks. But the icon is too similar to the appearance of a credit card. It looks like a modern credit card with a RFID chip instead of a check. Having the credit card and check symbols look so alike is not visually helpful.

I'd like to see one implemented as mentioned in the original request by @AbbyJanke with the pen. The pen/writing utensil being a part of the icon makes it very clear it is a check.

### Example image (optional)

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3438373739382f313736323638332f31306436663364382d363666622d313165332d396634382d6236323833623135326464662e706e67](https://user-images.githubusercontent.com/8377827/45700127-62ca0b00-bb31-11e8-971b-535284c3cc58.png)

### Icon request checklist

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate - this is a request to fix the original or just add one that is more clear (with the writing utensil)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by djpeacher** [comment]
👍

**Comment by sensibleworld** [comment]
@garnerv Thanks for the feedback. I'll look into it.

**Comment by sensibleworld** [comment]
We've added a couple of variants of this icon to Font Awesome Pro: 
https://fontawesome.com/icons/money-check-edit?style=solid
https://fontawesome.com/icons/money-check-edit-alt?style=solid
