### ISSUE TITLE
Icons Stopped Showing

### ISSUE THREAD

**Issue by m3tric** [FortAwesome/Font-Awesome#13965]
Hey Team, 
Just a little issue where icons have stopped showing...

Was present when we launched and client has recently noticed the icons are no longer appearing. 
Can see the code using Inspect > <i class="fab fa-youtube-square fa-4x"></i>

I have a Pro License and domain is added to license.

See footer (bottom right under "Follow")
https://www.naracoortelucindale.sa.gov.au/stay-do/

Any help would be.... "Awesome!"
Scott

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm getting this error:

```
Failed to load resource: the server responded with a status of 403 ()
```

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
