### ISSUE TITLE
Massive problems using FontAwesome Pro 5.3.1 TTF fonts in PowerPoint

### ISSUE THREAD

**Issue by DieterGust** [FortAwesome/Font-Awesome#13968]
### Describe the problem

Installing FontAwesome TTF fonts results in verious problems using any product:
Main Problem: The internal font naming in TTF obviously creates a complete mismatch as in PowerPoint these different fonts are neither shown as different fonts nor as different font styles of the same base font.
In addition most glyphs of FontAwesome Pro cannot be selected! - They don't appear at all.

### What did you expect?
No problems at all and reaching all glyphs - Using TTF is essential because OTF fonts cannot be embedded in PowerPoint files.
Aren't TTF fonts tested or only a conversion of OTF fonts. The bugs with TTF seem to are so heavy that usage in our team is not reliable and I have to withdraw the TTF fonts.

We'll have to test OTF types - first tests show a much better handling - but still problems with some import filters which do not transfer all code points from Font Awesome 5 Pro for example (Word import into FrameMaker) 
### What version and implementation are you using?
5.3.1
Pleas find attached a PPTX test file
[FA Test.pptx](https://github.com/FortAwesome/Font-Awesome/files/2397376/FA.Test.pptx)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by DieterGust** [comment]
Hi

> Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?
I couldn’t find my issue so I created it again
Regards

Dieter Gust
Aufsichtsrat, Leitung Forschung & Entwicklung

itl AG<http://www.itl.eu/>, München
+49 89 892623-600
Von: Geremia Taglialatela <notifications@github.com>
Gesendet: Mittwoch, 19. September 2018 16:46
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: Gust, Dieter <Dieter.Gust@itl.eu>; Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Massive problems using FontAwesome Pro 5.3.1 TTF fonts in PowerPoint (#13968)


Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by DieterGust** [comment]
What do you mean with "open this issue in the Font Awesome Pro repo ". I think that's what I've done.
Very strange: If I start again and want to list my open issues this one is not shown!

**Comment by tagliala** [comment]
@DieterGust thanks, I can see your post in the private repo

I'm going to close this one

**Comment by yhacohen** [comment]
We are facing the same issue apparently, on FA 5.6.1 pro - many Icons are not shown, although they do appear in the 'add symbol' dialog in PowerPoint. These icons also work fine with MS Word. Is there's any workaround or solution for this?

**Comment by DieterGust** [comment]
We finally switched from TTF to OTF (both refer to the extension of filenames) and this worked for us.
Be aware this is not OpenType vs. TrueType because both are OpenType.
OTF is Adobe Technology and TTF is Microsoft technology and refers only to the internal glyph definitions) to be able to use all the symbols. 
As far as I understand the font naming in TTF fonts of FA has not been the way PowerPoint expects it. In OTF fonts font naming seems to be ok for PowerPoint. But keep in mind that you cannot embed the symbols from OTF fonts in PowerPoint this is only works with TTF fonts.
I did not check the current version 5.6.1 with TTF but OTF seems to work in Powerpoint.

**Comment by tagliala** [comment]
@DieterGust thanks.

@yhacohen please make sure you are using the .otf files on desktop. If you still have issues, please open a new issue filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

ttf files are optimized for the web and for legacy browsers

**Comment by DieterGust** [comment]
@taglia- you said: "TTF files are optimized for the web and for legacy browser". 
Well for Microsoft systems and products you should use TTF fonts only - this is official Microsoft policy. Microsoft always tries to skip font support for fonts using extension .otf, so Adobe always has to remember Microsoft to accept this this extension of OpenType  .otf refers to Adobe technology inside the TTF-based OpentType technology.  

So I don't understand your preference of OTF. Ligatures are not a use case for Symbol fonts, or am I wrong? And TTF is the real the basis of the OpenType technology, so OpenType fonts with .ttf extension fonts should behave the same as fonts with .otf extension otherwise there is something wrong with the implemented internal font technology.

**Comment by tagliala** [comment]
> So I don't understand your preference of OTF. Ligatures are not a use case for Symbol fonts, or am I wrong? And TTF is the real the basis of the OpenType technology, so OpenType fonts with .ttf extension fonts should behave the same as fonts with .otf extension otherwise there is something wrong with the implemented internal font technology.

Hi, sorry if I didn't provide enough details. The TTF files are generated by the webfont generator, and those specific ttf files are not guaranteed to work on desktop.

We could definitely try to provide proper desktop-ready TTF files alongside OTF files, but it is another feature to manage and maintain

> Ligatures are not a use case for Symbol fonts

Ligatures are helpful on the desktop because you can do something like this

![output](https://user-images.githubusercontent.com/556268/50287786-2f668780-0464-11e9-8659-8f8b11f6c6ca.gif)

**Comment by DieterGust** [comment]
Thank you very much for this really worthfull information
