### ISSUE TITLE
Icon request: icon-home-alt (icon-home enhancement)

### ISSUE THREAD

**Issue by jurajkapsz** [FortAwesome/Font-Awesome#1397]
All the same as `icon-home`, but without chimney.

Use case: Just a bit cleaner version of the same use.

**Comment by renarena** [comment]
+1
maybe also remove the dor or alternatively the space below the roof (for cleaner look on small sizes) in an alternative version

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/6041432/9330b248-ac7c-11e4-82c3-61a7b3d9789b.png)

hmmm... also youtube switched to a version without the chimney

**Comment by TheChen5** [comment]
+1

**Comment by ckaz** [comment]
+1 
We'd use it for accessible in-house but the "house" in our case is a library

**Comment by tagliala** [comment]
Facebook and iPhone are still using home icons with chimneys

![image](https://cloud.githubusercontent.com/assets/556268/19967002/a24abfaa-a1ce-11e6-9947-b2fb91764fd2.png)

**Comment by davegandy** [comment]
Fair enough. We can definitely make an alt version without the chimney!

**Comment by sensibleworld** [comment]
Chimney? Where we're going, we won't need a chimney: https://fontawesome.com/icons/home-alt?style=solid

**Comment by tagliala** [comment]
> Facebook
> ![image](https://cloud.githubusercontent.com/assets/556268/19966833/cfc17dd0-a1cd-11e6-9739-549ee84f221d.png)

![image](https://user-images.githubusercontent.com/556268/109982994-b715d500-7d02-11eb-917a-466511b3bb19.png)

No chimney for Facebook
