### ISSUE TITLE
What is the difference from WEB and DESKTOP font awesome versions?

### ISSUE THREAD

**Issue by henrix343** [FortAwesome/Font-Awesome#13983]
Question is in title. Thanks for clarify this out.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you need to use Font Awesome in applications like Photoshop, you should go for the Destktop version and install the `otf` file. The `otf` version of Font Awesome includes useful features like ligatures, so if you need the user icon, you could simply type `user` without cuting and paste obscure unicode points.

The `ttf` file provided in the web version, is a `ttf` optimized for the web, so it does not contain ligatures, does not provide proper font names and it is designed to work just on ancient browsers.

Ref: https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started

Hope it helps

Closing here
