### ISSUE TITLE
fal not working (Light weight)

### ISSUE THREAD

**Issue by chintankotadia** [FortAwesome/Font-Awesome#13980]
Hi FA Team,

Light weight font awesome is not working.  Here is the jsfiddle link for reference: http://jsfiddle.net/nLgq0arf/6/

Am I missing anything? 

Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The Light style is only available for Pro users

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
