### ISSUE TITLE
Icon request: Cinema

### ISSUE THREAD

**Issue by MichSimi** [FortAwesome/Font-Awesome#13984]
Hi
Could you add some icons in Cinema theme? Like popcorn, director's chair, proiector, cinema sala and more.

Thaks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but we do not accept requests for icon sets.

If you are a Font Awesome Pro user, you can request a set in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
