### ISSUE TITLE
Icon request: farming

### ISSUE THREAD

**Issue by devdunham** [FortAwesome/Font-Awesome#13999]
### What can it be used for?

Agriculture, Precision Agriculture, Farming
### Example image (optional)

[tractor-field-farming-agriculture-plowing-plow-vehicle-37a269e1083485e9-512x512](https://user-images.githubusercontent.com/43550973/46008389-37d83d80-c082-11e8-9dcc-8f23583270e4.png)

### Icon request checklist

- [  X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ X ] I have included at least one example image if it could be helpful (optional)
- [ X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hey there! We're about to release a "tractor" icon. Would that cover this request?

**Comment by devdunham** [comment]
Yeah. That would suffice. Just not a bull dozer. Make sure it has a plat of land underneath to not get confused with construction though.

 

Thanks a lot!

**Comment by Crissov** [comment]
Unicode emoji #222:
🚜

**Comment by aethior** [comment]
> Unicode emoji #222: 🚜

Tractor icon was add in v5.4.0.
Check https://fontawesome.com/icons/tractor

**Comment by aethior** [comment]
> Unicode emoji #222:
🚜

Tractor icon was added in v5.4.0.
Check https://fontawesome.com/icons/tractor

cc/ @tagliala
