### ISSUE TITLE
Font export issue in Affinity Designer

### ISSUE THREAD

**Issue by Potzo** [FortAwesome/Font-Awesome#13990]
### Describe the problem

Weird issue when exporting PDF with embedded Font Awesome. I am using Affinity Designer for exporting. Illustrator works fine. Here's the weird part, it only happens on one of my PCs. 
Works fine on the other one. Have a look below on screenshots.

The other PC with the same OTFs installed and same software Affinity Designer exports it just fine.
It seems like some weird encoding (Custom vs Identity-H). 

### What did you expect?
I would want PDF font embedding working correctly.

### What version and implementation are you using?
Version: 5.3.1
OS: Win10
Affinity Designer: 1.6.5.123

### Reproducible test case
Affinity Designer on Windows. 

### Bug report checklist
- [x] Reinstalling Affinity Designer
- [x] Reinstalling Font Awesome fonts
- [x] Clearing Windows 10 font cache

### Preview & info
**This is PDF font info generated with PC 1**
![Font info 1](https://i.imgur.com/gusgiQw.png)
Preview:
![Font preview 1](https://i.imgur.com/ZhtZdAK.png)
**And this is PC 2 where it exports just fine**
![Font info 2](https://i.imgur.com/48jlufw.png)
Preview:
![Font preview 2](https://i.imgur.com/RF8pQxI.png)

Thank you in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

**Comment by Potzo** [comment]
Hey, sorry about that! I updated the topic.

**Comment by Potzo** [comment]
**FIXED!**
In short, it was a Windows problem on this PC. After Creators Update they handle fonts really weird.
If you try to manually view fonts installed on your system, it will open up default preview mode. Even with explorer. 

I managed to actually view the fonts files installed by using **_%systemroot%/fonts_** via start.

It turns out I installed fa fonts (ttfs) on this PC way before I did newer font files on the laptop (otf). 
And Windows keeps all the versions for some reason with the new ones. That's why I had problems with some other fonts being duplicated and showing up that way in Affinity.

These were being used:
![Old FA fonts](https://i.imgur.com/2KDYj9w.png)

So, in order to fix it is to remove all your duplicates (search for _0, _1, _2 etc.) and old Font Awesome fonts.
After that you have to [rebuild the font cache](https://winaero.com/blog/rebuild-font-cache-windows-10/).

So, this is some issue going on with Windows.
Hopefully this helps someone.

**Comment by tagliala** [comment]
thanks for sharing this 👍
