### ISSUE TITLE
Icon request: icon-train

### ISSUE THREAD

**Issue by cloudwizard** [FortAwesome/Font-Awesome#14]
Since there is a plane - it would be nice to have the travel set
hotel, train

**Comment by abariatti** [comment]
+1

**Comment by dansimau** [comment]
+1 for train.

**Comment by Termina1** [comment]
+1 for train

and may be subway?

**Comment by robbing** [comment]
+1 for an entire travel set.

**Comment by vworldat** [comment]
+1 for tram and train (distinct)
+1 for the full travel set

**Comment by maxime-lenne** [comment]
:+1: for train and full travel set

**Comment by agaio** [comment]
+1

**Comment by knitevision1** [comment]
+ for travel icons
will it be shipped someday?

**Comment by robbing** [comment]
Ticket opened almost 3 years ago. You think they would have made them by now.  :-(

**Comment by tagliala** [comment]
@robbing this is one of the oldest and more popular requests, I think Dave will take this in account.

Meanwhile, if you need these icons I should suggest you to consider a custom build of fontawesome.

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://icomoon.io/app/#/select
http://fontello.com/
http://fontastic.me/

**Comment by robbing** [comment]
I'll keep that in mind! The WP theme I bought uses Font Awesome specifically so I would be at a loss as to how I would integrate the others.

**Comment by davegandy** [comment]
Actually, adding a custom icon is now possible in the free tier. :)

**Comment by tagliala** [comment]
@davegandy thanks for the heads up!

**Comment by davegandy** [comment]
I'm merging the bed icon with the hotel icon. It's now in 4.3.0-wip branch.

**Comment by davegandy** [comment]
Added to 4.3.0-wip branch. Closing.

**Comment by norn** [comment]
+1 trolleybus, tram
