### ISSUE TITLE
Icon requested: far faCannabis

### ISSUE THREAD

**Issue by fmturati** [FortAwesome/Font-Awesome#14003]
Can't find this item (far faCannabis) inside the @fortawesome/free-regular-svg-icons'

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is working as expected, `far fa-cannabis` is only available to Font Awesome Pro

Ref: https://fontawesome.com/icons/cannabis?style=solid

Hope it helps

Closing here
