### ISSUE TITLE
Icon request: fa-party

### ISSUE THREAD

**Issue by andreamoehl** [FortAwesome/Font-Awesome#14001]
A simple party Icon (like a Party Hat with confetti coming out :)) It could be used if anything succeeds.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4039, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by MrDariusAD** [comment]
+1
