### ISSUE TITLE
Tent Icon

### ISSUE THREAD

**Issue by dankhouser** [FortAwesome/Font-Awesome#14002]
It would be (font) awesome if there was a tent icon. We sell tent spaces for tailgating at football games and would love to use a tent icon as bullets on our website. Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #3859 , please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
