### ISSUE TITLE
Icon Request: fa-user-with-tie

### ISSUE THREAD

**Issue by hareeshreddy13** [FortAwesome/Font-Awesome#14000]
icon request for user with tie, have to use it for manager

**Comment by InsanityMeetsHH** [comment]
[icon exists already](https://fontawesome.com/icons/user-tie?style=solid)

**Comment by sensibleworld** [comment]
As @InsanityMeetsHH mentioned, this icon is available: https://fontawesome.com/icons/user-tie?style=solid
