### ISSUE TITLE
Icon request: icon-coins

### ISSUE THREAD

**Issue by mwld** [FortAwesome/Font-Awesome#1400]
In some online selling/buying situations it makes sense to use coins to symbolize a small amount of money and to avoid being currency specific.

I would imagine to have a symbol showing a stack of three slightly disordered coins from a 30° angle which should be enough to make a clear image.

Example images to give an idea:
![coins](https://f.cloud.github.com/assets/3263178/695763/f5bba29e-dcd8-11e2-9cec-e5b01487dbd3.jpg)
![coins-icon](https://f.cloud.github.com/assets/3263178/695766/f94f05d6-dcd8-11e2-8244-ca38ee43a098.png)
![coins012](https://f.cloud.github.com/assets/3263178/695782/35b8492e-dcd9-11e2-808c-32a0eb615ca3.gif)

**Comment by maxaon** [comment]
+1

**Comment by DonBananos** [comment]
+1

**Comment by ftcminh** [comment]
+1

**Comment by petrgrishin** [comment]
:+1:

**Comment by stijnvanbael** [comment]
+1

**Comment by wamatt** [comment]
:+1:

**Comment by gawin** [comment]
+1

**Comment by flazzarotto** [comment]
+1

**Comment by julienfernandez** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by kevinrefvik** [comment]
+1

**Comment by aaclarkbede** [comment]
+1

**Comment by alexwebwork** [comment]
+1

**Comment by driplo** [comment]
+1

**Comment by castocolina** [comment]
+1

**Comment by Kelevari** [comment]
+1

**Comment by kalvinmoraes** [comment]
+1

**Comment by tzusman** [comment]
I just launched [CustomFontIcons.com](https://customfonticons.com/), a place to get crowd-commissioned icons.  I also launched a free font icon set.  A coins icon is part of that set, if you're interested.

**Comment by gtonioli** [comment]
+1

**Comment by DumboJetEngine** [comment]
+1

**Comment by Bigmacbook** [comment]
+1

**Comment by SynRJ** [comment]
+1

**Comment by andvla** [comment]
+1

**Comment by Dashue** [comment]
Wow it really takes that long from request to impl?

**Comment by jonnywhite** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by petrabarus** [comment]
+1

**Comment by enco164** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by litecart** [comment]
+1

**Comment by afsa** [comment]
+1

**Comment by sanazaidi** [comment]
+1

**Comment by bertoost** [comment]
+1

**Comment by nexiaz** [comment]
+1

**Comment by sanwv** [comment]
+1

**Comment by nisdis** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by spjwebster** [comment]
+1

**Comment by mungle** [comment]
any news?

**Comment by shreyashdholakia** [comment]
+1

**Comment by ThomasDdD** [comment]
+1

**Comment by alexinman** [comment]
+1

**Comment by psnma** [comment]
+1

**Comment by newsfusion** [comment]
+1

**Comment by accrossang** [comment]
+1

**Comment by mraxus** [comment]
+1

**Comment by babbarshaer** [comment]
+1

**Comment by MJafarMashhadi** [comment]
+1

**Comment by julif3r** [comment]
+1

**Comment by abobwhite** [comment]
+1

**Comment by andybandy89** [comment]
+1

**Comment by ivkremer** [comment]
+1

**Comment by bstremel** [comment]
+1

**Comment by Rodrigo54** [comment]
+1

**Comment by MJafarMashhadi** [comment]
Suggested icon:
![coins](https://cloud.githubusercontent.com/assets/3872947/11123544/894b55fe-8975-11e5-89f7-0da7707b9ff2.png)

**Comment by rotherfuchs** [comment]
+1

**Comment by rotherfuchs** [comment]
To all: as a temporary workaround, you could use fa-database as an alternative - that looks like a coins stack. somehow. :)

**Comment by MVcodeartbr** [comment]
+1

**Comment by bostondv** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by tomturner** [comment]
+1

**Comment by chrihech** [comment]
+1

**Comment by ttimpe** [comment]
+1 Much needed!

**Comment by CarlosHAraujo** [comment]
+1

**Comment by JeroenCollier** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by zyre91** [comment]
+1

**Comment by xeno** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by dan** [comment]
+1

**Comment by dolanmiu** [comment]
+1

**Comment by iamcarloseperez** [comment]
+1

**Comment by dgca** [comment]
+1

**Comment by damadorPL** [comment]
need pile of coin too ;p

**Comment by adrianbader** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by Patrick-W-McMahon** [comment]
I would like to see two icons fa-coin-h and fa-coin-t for heads and tails.

**Comment by Patrick-W-McMahon** [comment]
and maybe a fa-coin-stack or fa-coin-pile for a pile of coins or stack of coins

**Comment by marklanham** [comment]
+1

**Comment by fermon797** [comment]
+1

**Comment by ellenhutchings** [comment]
+1

**Comment by kirvesp** [comment]
+1

**Comment by irsh5** [comment]
+1

**Comment by MrLewk** [comment]
**# +1** many times over!

**Comment by nofxx** [comment]
+1 ... also as the friend above, my imagination let `fa-database` be it in the while.

**Comment by lorantkurthy** [comment]
+1

**Comment by franciscocosta** [comment]
+1

**Comment by mejt** [comment]
+1

**Comment by Varkal** [comment]
+1

**Comment by pepoteloko** [comment]
+1

**Comment by cwang22** [comment]
+1

**Comment by trybowski** [comment]
+1

**Comment by ilyago** [comment]
+1

**Comment by zubko** [comment]
+1

**Comment by StefanoGitHub** [comment]
+1 👍 
I found this site that somehow implements an icon probably very similar to font-awesome format:
https://nicbell.github.io/ucreate/icons.html (see `icon-coins-alt` for example)

**Comment by Kaan2106** [comment]
+1

**Comment by leandrohsilveira** [comment]
+1

**Comment by amirdeljuyi** [comment]
+1

**Comment by j-tap** [comment]
+1

**Comment by shawnbayer** [comment]
+1

**Comment by bizurk** [comment]
+1

**Comment by andreasindal** [comment]
+1

**Comment by nicolasbadia** [comment]
+1

**Comment by iamwillow** [comment]
+1, wow everyone wants this icon.
Design Ideas:

Coin:
![coin](https://cloud.githubusercontent.com/assets/3923914/17199109/6c1a69f0-54b5-11e6-994d-3daab862f784.jpg)

Coins:
![coins](https://cloud.githubusercontent.com/assets/3923914/17199114/70ae506c-54b5-11e6-83fd-b88c169d38b7.png)

**Comment by e2goon** [comment]
+1

**Comment by jjppof** [comment]
+1

**Comment by TheoDel** [comment]
+1

**Comment by tsucaet** [comment]
+1

**Comment by romram13** [comment]
+1
The second design of iamwillow is nice.
Thank you

**Comment by blitzmann** [comment]
+1

**Comment by CustomNet** [comment]
+1

**Comment by JefMari** [comment]
+1

**Comment by jrsalunga** [comment]
+1

**Comment by davidmelia** [comment]
+1

**Comment by rickerd** [comment]
Why since 2013 there is still no coin icon??

**Comment by mickedplay** [comment]
+1

**Comment by nixa333** [comment]
+1

**Comment by wmai** [comment]
+1

**Comment by maartenvsp** [comment]
+1

**Comment by Mar-k** [comment]
+1

**Comment by ilyago** [comment]
+1

**Comment by davidak** [comment]
+1 needed for donations

**Comment by eurolife** [comment]
+1

**Comment by vkollin** [comment]
+1

**Comment by DanilaKorepin** [comment]
+1

**Comment by JTallis** [comment]
+1

**Comment by rjjakes** [comment]
+1

**Comment by B1QB0SS** [comment]
+1

**Comment by mcgraphix** [comment]
+1

**Comment by Ranentil** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[Coins icon is here](https://icons8.com/web-app/21449/coins)

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones where [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382), [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574) and [Google Play] (https://github.com/FortAwesome/Font-Awesome/issues/2272)

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by eurolife** [comment]
i like the icons you have but do we have to include a link for credit?

**Comment by visualpharm** [comment]
Normally yes, but those that we release here are double licensed with Good Boy License and MIT. It's offficial.

**Comment by matthewcorreia** [comment]
+1

**Comment by markpenaranda** [comment]
+1

**Comment by TheUberKid** [comment]
It's been 4 years and coins are still missing from font awesome...

I would have thought this was a very common icon

**Comment by slbentley** [comment]
:+1:

**Comment by Kivien** [comment]
+1

**Comment by vitalyiegorov** [comment]
+1

**Comment by yusrilhs** [comment]
+1

**Comment by kpingel** [comment]
+1

**Comment by LeeviHalme** [comment]
+1
Why this is taking so long

**Comment by Maartincm** [comment]
+1

**Comment by mosinve** [comment]
+1

**Comment by stmn** [comment]
I would pay for Pro if coin icon could be available. ;)

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by tapastwain** [comment]
+1

**Comment by savadodesigns** [comment]
+1

**Comment by sensibleworld** [comment]
My money's on this icon: https://fontawesome.com/icons/coins?style=solid

**Comment by rickerd** [comment]
🖕🏻 Fontawesome 5.x
I Will never use 5.x. For me it’s 4.x or custom icons. No way i’m paying for icons or freemium content.

Adios fontdicksome

**Comment by sensibleworld** [comment]
@rickerd Not sure where the animosity is coming from. We will always support a free version of Font Awesome. In fact, Font Awesome 5 Free contains more icons that 4.x and continues to get new additions, including this icon.

**Comment by sensibleworld** [comment]
@davidak I can appreciate your point of view. We wouldn't be were we are without our community, and we're doing our best to serve them as well as we can. I can't speak directly to the decisions made prior to joining the team, but I can say that we value all feedback and take comments like this to heart.

My note above was more related to the rudeness shown by the previous commenter.

**Comment by alystair** [comment]
IMHO the released coin icon feels a bit tall to me, looks like a database icon

**Comment by davidak** [comment]
@sensibleworld thanks. sure the rudeness is not very constructive, but there are reasons for people feeling angry about decisions made and get emotional then. It was probably no easy decision since you can imagine that not everyone likes it, especially people that have contributed in the past and are now get left out of the whole product. You got a lot of money in the crowdfunding for such a project, and you deserve it for the awesome icons you have created in the past, but you could take that money and still provide everything as open source for everyone. I don't understand your decision, but i also havn't followed it that close.

This is why i prefer collaboration focused community projects over commercial efforts, even if both is open source. Companies quickly tend to prefer profit over a freely accessible product for everyone.

**Comment by rickerd** [comment]
That wasn’t rude at all if I was being rude you would be crying on a pillow 😂
