### ISSUE TITLE
Icon request: binary-1, binary-0

### ISSUE THREAD

**Issue by greg-raven** [FortAwesome/Font-Awesome#14007]
### What can it be used for?

Having non-page-font-dependent binary 0 and binary 1 icons would allow you to use -- for example -- a text font with old-style zeros and serifs on the ones and still be able to indicate in the text on and off (for power switches, etc.), as well as binary strings.

### Example image (optional)

I don't have a good example, sorry.

**Comment by thomascorthals** [comment]
> Is this a duplicate of #6812?

#6812 is meant to represent a binary stream. This request is about an individual binary ONE and an individual binary ZERO, basically a number as an icon.

You might go further than that and make a number-0, number-1 … number-9, number-A … number-F to cover all binary, octal, decimal and hexadecimal numbers.

**Comment by tagliala** [comment]
We have 0s and 1s in FA6:

- https://fontawesome.com/v6.0/icons/0?s=solid
- https://fontawesome.com/v6.0/icons/1?s=solid
