### ISSUE TITLE
Your CDN is DOWN!

### ISSUE THREAD

**Issue by arabenjamin** [FortAwesome/Font-Awesome#14019]
Cannot connect to use.fontawesome.com at all. Via ping, traceroute, etc...

HELP!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the inconvenience, it should be solved now. Could you please check?

**Comment by arabenjamin** [comment]
Sorry for the late reply. All seems to be good. I felt this was a good reason to download what I needed, and serve locally,  instead of pointing to the CDN :)
