### ISSUE TITLE
Icon browser in Safari: "No icons found"

### ISSUE THREAD

**Issue by waltsatan** [FortAwesome/Font-Awesome#14014]
When I go to the icons page (https://fontawesome.com/icons) in Safari, I get "No icons found" regardless of filter settings.  I have no plugins and there are no Javascript errors.  The last ajax call is to Algolia's "query" script which appears to be a properly formatted JSON "hits" object (when compared to a functional Firefox call).  It seems like it's not firing the rendering of the results.

Safari 10.0.3 (OS X El Capitan 10.11.6)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately I cannot check this, everything is working fine on Safari 12 / Mojave
