### ISSUE TITLE
LinkedIn Icon (fa-linkedin-in) not aligned to baseline

### ISSUE THREAD

**Issue by almirz** [FortAwesome/Font-Awesome#14025]
The LinkedIn Icon isn't aligned to the baseline (see image below), it's slightly lower than other icons and CSS can't fix it. These icons have no styles attached yet, this is them when I just imported them.

<img width="140" alt="screen shot 2018-09-27 at 13 54 06" src="https://user-images.githubusercontent.com/43655672/46174074-e20bbd00-c25c-11e8-8d7e-b8cdf52dd7b4.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm that there is room for improvement: http://jsfiddle.net/tagliala/j3gakye6/39/ 

The SVG is centered on the grid: https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/raw-svg/brands/linkedin-in.svg, but this icon could be improved like in #11396

@talbs what do you think?

**Comment by almirz** [comment]
Sorry, accidentally closed it; reopened it now

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @almirz. We'll get this fixed in our next release for you. 😄

**Comment by talbs** [comment]
Hey, gang. This has been fixed and released in version 5.4.1. Here's a quick demo - https://codepen.io/fontawesome/pen/ePELdm. Let us know if you spot any other issues and thanks again for the help with this one.
