### ISSUE TITLE
Icon request: icon-ubuntu

### ISSUE THREAD

**Issue by RafoxSama** [FortAwesome/Font-Awesome#14038]
http://konpa.github.io/devicon/devicon.git/icons/ubuntu/ubuntu-plain.svg

**Comment by troe** [comment]
Icons of other distros also need to be added.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #980 , please add a 👍 reaction to that request.

That request is in progress, popular linux distros will be soon part of the set 🎉 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
