### ISSUE TITLE
Is the desktop font up to date? 

### ISSUE THREAD

**Issue by stitchlipped** [FortAwesome/Font-Awesome#14037]
I've downloaded the latest version of the font from the website, but the divide icon still isn't working for me in InDesign/Word. Wondering if the .ttf files aren't full up to date with new inclusions?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Wondering if the .ttf files aren't full up to date with new inclusions?

.ttf files are up to date, but please use the .otf version on the desktop, the .ttf files is optimized for the web.

https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started

> the divide icon still isn't working for me 

Please make sure that your system uses Font Awesome >= 5.0.13. If you aren't sure

1. Download the new files at https://fontawesome.com/ (**For the Desktop** button)
2. Uninstall the old .ttf font files
3. Install the new .otf font files
4. Restart your system
5. Make sure you have selected the **Solid** style (divide icon isn't available in regular style on Font Awesome 5 Free)

Hope it helps

Closing here
