### ISSUE TITLE
No Samsung logo

### ISSUE THREAD

**Issue by boutzamat** [FortAwesome/Font-Awesome#14031]
Is it on purpose, maybe because of copyright stuff? Or simply not as important for you as Apple's logo?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4681, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
