### ISSUE TITLE
Icon request: fa-discord

### ISSUE THREAD

**Issue by RadicalZoey** [FortAwesome/Font-Awesome#14036]
We should be able to advertise our discord app servers on our websites.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> We should be able to advertise our discord app servers on our websites.

So let's do it! 😁 

https://fontawesome.com/icons/discord?style=brands

**Comment by RadicalZoey** [comment]
Hey!

Very embarrassed that I didn't notice this. Problem is, when I try to use it, I just get an empty square. If I try to use the style sheet it tells me to use, then it doesn't show up and all my icons become empty squares.

**Comment by tagliala** [comment]
Discord has been introduced in Font Awesome 5.0.0

Please make sure you are using Font Awesome 5.0.0 or newer

Upgrade guide: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
