### ISSUE TITLE
Icon Problem: kaggle icon not working properly

### ISSUE THREAD

**Issue by machadorafa** [FortAwesome/Font-Awesome#14034]
When using the tag <i id="kaggle" class="fab fa-kaggle fa-2x"></i> the icon doesn't show. I tried everything, but apparently the problem is within the tag itself, since other icons work perfectly.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

kaggle has been introduced in Font Awesome 5.2.0. Your project is probably using an older version, or a third party plugin/theme is overriding the latest version with an older one.

Please check that your project is using Font Awesome >= 5.2.0

Hope it helps

Closing here

If you still think there is an issue with Font Awesome, please open a new issue following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case
