### ISSUE TITLE
fa-clock-o - not work

### ISSUE THREAD

**Issue by dimastik86** [FortAwesome/Font-Awesome#14040]
this icon does not work for me. 
what could be the problem? 
attached file - all.css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that `fa-clock-o` is the old syntax for Font Awesome 5.

If you are using Font Awesome 5, you are supposed to use `far fa-clock`

Hope it helps

Closing here

Ref:
- fa-clock usage: https://fontawesome.com/icons/clock?style=regular
- Upgrading guide: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- Old docs: https://fontawesome.com/v4.7.0/
