### ISSUE TITLE
desktop font facebook icon not working

### ISSUE THREAD

**Issue by WaringMedia** [FortAwesome/Font-Awesome#14049]
The book and square show up fine, but it ends up rendering as fa-face(book icon)-(square icon).  Here is a screen:

https://snag.gy/2XAHTc.jpg

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure to install and select the proper font: *Font Awesome 5 Brands*

I'm pretty confident that you have selected *Font Awesome 5 (Free/Pro)* with regular style

Hope it helps

Closing here
