### ISSUE TITLE
fa- fa-stopcwatch Icon request: icon-name

### ISSUE THREAD

**Issue by pilitaz** [FortAwesome/Font-Awesome#14043]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

fa-stopwatch has been introduced in Font Awesome 5.0.0.

https://fontawesome.com/icons/stopwatch?style=solid

Please make sure you are using the latest version of Font Awesome

Hope it helps

Closing here
