### ISSUE TITLE
Icon request: icon-save (icon-floppy)

### ISSUE THREAD

**Issue by doedje** [FortAwesome/Font-Awesome#1405]
Just an alternative to the current icon-save. I find the icon-save does not work well when used small. I'd like to propose another design which works better when used small:
![icon-save-alt](https://f.cloud.github.com/assets/3636611/701540/389c33b8-dd78-11e2-825b-9cb368f2f732.png)

(.ai file available, but I have lousy illustrator-skills... I tried to make rounded corner and to cut out the label, but I just don't know how to... =] If needed I can try to perfect my AI skills to make a usable icon to save you some time, willing to learn!!!)

**Comment by gingersnap** [comment]
+1

**Comment by HillTravis** [comment]
:+1:

**Comment by thegreatmothra** [comment]
+1

**Comment by goanpeca** [comment]
:+1: , indeed the contour version does not match most of the other available glyphs.

**Comment by SylvainCorlay** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by auge8472** [comment]
+1

**Comment by Igcorreia** [comment]
+1

**Comment by Saluev** [comment]
+1

**Comment by doedje** [comment]
After two years of patiently waiting for this one I must say I get a little frustrated... :(

**Comment by alexpana** [comment]
+1

**Comment by BTMorton** [comment]
I needed this icon for a project I was working on, and made one as a slightly modified inverse of the current fa-floppy-o. Feel free to use it. I have a .svg or .ai available if you need

![fa-floppy](https://cloud.githubusercontent.com/assets/9026309/12375360/88ce21f0-bcb6-11e5-85ee-ded827a5e516.png)
[fa-floppy.pdf](https://github.com/FortAwesome/Font-Awesome/files/93162/fa-floppy.pdf)

**Comment by hpvd** [comment]
+1

**Comment by doedje** [comment]
Really hope this 5.0.0 milestone is bringing us a decent fa-floppy......

**Comment by djendreizak** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-floppy was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by doedje** [comment]
Three years have gone by and still we have to deal with this butt-ugly floppy icon....... The priority is clearly on corporate icons instead of improving the current set.... A pity.....

**Comment by wggley** [comment]
+1

**Comment by doedje** [comment]
I gave up on this....... I posted about the sloppy-floppy icon more than 4 years ago. We saw a gazillion (in my opinion worthless) company icons pass by (why people care about those, I really don't understand) But improving the icon for one of the most used functions on a computer; SAVE is just not happening...... I don't get it.... Freaks me out... It's just all $$$ to Dave and his friends I guess...

**Comment by doedje** [comment]
I am closing this issue, cause I really no longer care. I have built applications and websites with save-buttons without an icon for over 4 years and you know what? People click on those buttons anyway, simple because the say "SAVE".

**Comment by Saluev** [comment]
This issue has milestone assigned, maybe you shouldn't have closed it.

**Comment by timtjtim** [comment]
I think this should stay open - it's a valid request and there's no good reason to close it.

**Comment by KOTRET** [comment]
@Saluev @timtjtim : i can understand @doedje. Followed this issue that many years and nothing happened. Not even improving the current icon. This is ridiculous and embarrassing.
+1 for closing.

**Comment by Igcorreia** [comment]
We still believe in it! :)
