### ISSUE TITLE
Website not working on Firefox

### ISSUE THREAD

**Issue by Regna91** [FortAwesome/Font-Awesome#14054]
My specific

- OS: Win 8.1 (x64)
- Browser: Firefox 62.0.3 (x64)

I get a blank page when i use ghostery addons and i get the error `"window.ga is not a function".`  I think it's because of Google Analytics: It is possible to capsule Google Analytics?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known bug, duplicate of #13952 

Please follow that thread
