### ISSUE TITLE
Icon request: lightouse

### ISSUE THREAD

**Issue by jerome-benoit-jayb** [FortAwesome/Font-Awesome#14061]
### What can it be used for?

Hey, I'm looking for an icon which could fit for an alerting center, different from the usual notification icon (like the bell). A lighthouse and/or a rotating beacon are two valuable options.

### Example image (optional)

<img width="498" alt="capture d ecran 2018-10-03 a 17 42 38" src="https://user-images.githubusercontent.com/43821064/46422049-c9efde00-c733-11e8-8584-9b79d5746a24.png">
<img width="349" alt="capture d ecran 2018-10-03 a 17 42 29" src="https://user-images.githubusercontent.com/43821064/46422050-c9efde00-c733-11e8-965a-1f9cd499e988.png">

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues] for rotating beacon = no existing issues / for lighthouse (request #5579), there are no answers since 2015...
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by stphnwlkr** [comment]
[Icons8 ](https://icons8.com/icons/set/lighthouse) has some great examples and I think a merger of a couple of these would be ideal.

**Comment by velocitysystems** [comment]
Yes, a lighthouse icon would be great!

**Comment by tagliala** [comment]
Oh, ffff

`lighthouse ` there is a typo in the title, so I didn't notice that this is an older duplicate with more upvotes

Please +1 #5579
