### ISSUE TITLE
Make .fa-barcode pixel perfect

### ISSUE THREAD

**Issue by brunnopleffken** [FortAwesome/Font-Awesome#14062]
### Describe the problem

`.fa-barcode` is not pixel perfect at 16px at all, it's blurry even on Retina Displays. Using it in sidebar menus, for example, users will see just a bunch of grey pixels.

### What did you expect?

To be pixel perfect, perhaps something like `.fa-barcode-scan`, but without the dash; or the Glyphicons' `.glyphicons-barcode`.

### What version and implementation are you using?

Version: 5.3.1
Browser and version: All browsers

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

### Reproducible test case

Add an element `.fa-barcode` (SVG or CSS) at 16px or multiple. It's blurry.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This has been fixed up in version 6: https://fontawesome.com/v6.0/icons/barcode?s=solid
