### ISSUE TITLE
Icon request: textile icons

### ISSUE THREAD

**Issue by carloslongen** [FortAwesome/Font-Awesome#14068]
### What can it be used for?
We've go Pro, and want to ask you for textile/apparel/fashion icons, like pants, shirts, T-shirts, clothes sizes, processes, etc.

We make ERP software to apparel companies, and it would be very nice to have them on our apps.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repo at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
