### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by hadi-shamsabadi24** [FortAwesome/Font-Awesome#14069]
### What can it be used for?

For Admin Layout design

### Example image (optional)

https://www.materialui.co/materialIcons/action/dashboard_black_192x192.png

### Icon request checklist

This is a single icon .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The name of this request should be fixed

Does https://fontawesome.com/icons/columns?style=solid fit your use case?

**Comment by tagliala** [comment]
No feedback, closing here
