### ISSUE TITLE
Icon request: icon-user-with-clock

### ISSUE THREAD

**Issue by rajbrades** [FortAwesome/Font-Awesome#1407]
An icon to schedule an online appointment (medical).
![scheduleicon](https://f.cloud.github.com/assets/4819041/702805/fa7cc29e-dd9c-11e2-8e0f-443f520ae98a.png)

**Comment by sebastian301082** [comment]
+1

**Comment by tagliala** [comment]
Refers to #1181

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-clock?style=solid
