### ISSUE TITLE
fa-telegram issue

### ISSUE THREAD

**Issue by vivlachaga** [FortAwesome/Font-Awesome#14077]
Hi, i'm getting a wrong icon for fa-telegram, i'm using the CDN version for 5.3.1 so i guess the icon it's included in this bundle, maybe is a wrong implementation of my code?

<i class="far fa-telegram"></i>

![image](https://user-images.githubusercontent.com/29557581/46585027-06ffed00-ca20-11e8-892d-aee73ae745ca.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information?

At the moment, I could only suggest you to check your syntax. It should be `fab fa-telegram`

https://fontawesome.com/icons/telegram?style=brands

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by vivlachaga** [comment]
sorry for waste your time, i was misunderstanding, thinking brands was inside "regular" because the categories are related to the weight of the icon, now i see the brands icons are a separate style

thank you

**Comment by tagliala** [comment]
Don't worry, you're welcome, glad you solved 👍
