### ISSUE TITLE
Error in Site https://fontawesome.com/icons/github?style=brands

### ISSUE THREAD

**Issue by philson-philip** [FortAwesome/Font-Awesome#14076]
The HTML code for github icon given in the site is 
fab fa-github 
but the correct one is 
fa fa-github
. Correct it asap

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fab fa-github` is the correct syntax for Font Awesome 5.

You may be using Font Awesome 4, which had a different syntax. FA4 docs are available at https://fontawesome.com/v4.7.0/

Hope it helps

Closing here

Refers to:
- FA5 Docs: https://fontawesome.com/
- Upgrading guide: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
