### ISSUE TITLE
Pulsating spinner vibrates

### ISSUE THREAD

**Issue by malosupremo** [FortAwesome/Font-Awesome#14082]
### Describe the problem

I've used the animated spinner as by example
<i class="fas fa-spinner fa-pulse"></i>
as seen in your page https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons
If you look closely the spinner with pulse setting "vibrates" around. This is much annoying if the font size is small (12 px), it doesn't look right, doesn't look professional grade.

### What did you expect?

I expect the glyph to be better centered to rotate without vibrations.
The "fa-spin" version is much better, as it is a continuous animation.

### What version and implementation are you using?

Version:  current version as of 9 October, 2018
Browser and version: tested in Windows 10, 1809, with Edge and Chrome 69.

### Reproducible test case

https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons
Just check the second from the right. It's even more evident with smaller small fonts

### Bug report checklist

- [yes] I have filled out as much of the above information as I can
- [yes] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by malosupremo** [comment]
after the first report I've tested all the animated icons and the all vibrate especially up and nown. Just try a font-size of 12px in a box with height 16px, I see the icon moving up and down of about 1 or 2 px (very visible in a small space)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a known issue and we can't fix this in the webfont version of Font Awesome

If you need a pixel perfect spinner at any size, please use the SVG Framework or consider an .svg alternative

Hope it helps

Closing here

Ref: #671
