### ISSUE TITLE
Basic Use documentation grammer in unclear in Ligature section - "Until we all for subsetting"

### ISSUE THREAD

**Issue by bretself** [FortAwesome/Font-Awesome#14080]
### Describe the problem
Minor documentation issue.

On page https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use in section "Ligature use in Font Awesome on the web", the last sentence starts with "Until we all for subsetting of icons". It seems like a word is missing here since I'm not sure what "Until we all for subsetting of icons" means.  

### What did you expect?

I expected some other word to be present in "Until we all for subsetting of icons". I'm not sure what the sentence is telling me at the moment. Until we all what?

### What version and implementation are you using?

Version: Documentation/website on 2018-10-08
Browser and version: NA

NA
- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

On page https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use in section "Ligature use in Font Awesome on the web", the last sentence starts with "Until we all for subsetting of icons".

### Bug report checklist

- [ X] I have filled out as much of the above information as I can
- [ X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by talbs** [comment]
Thanks for the catch, @bretself. We've already got this fixed up in our site's repo and the properly structured sentence should be live on fontawesome.com shorty. 😄

**Comment by talbs** [comment]
Thanks again for bringing this up. That sentence at https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use should be a tad easier to understand now. :smile:

**Comment by bretself** [comment]
Thank you much!
