### ISSUE TITLE
Character not working

### ISSUE THREAD

**Issue by ahanssen** [FortAwesome/Font-Awesome#14087]
<img width="465" alt="captura de tela 2018-10-09 as 22 38 14" src="https://user-images.githubusercontent.com/645934/46708300-50189280-cc14-11e8-8c2d-c0879f0053f8.png">
### Describe the problem

"Traffic Light" character not working on Adobe Illustrator and Adobe InDesign. When I try to change font to FontAwesome, it turns back to Myriad. It only occurs with that only character, others are working correctly.

### What did you expect?

Apply FontAwesome Solid as selected character format, the way it works with all other characters.

### What version and implementation are you using?

I've tried FontAwesome 4, 5 and 5.3.1. MacOS 10.13 and 10.14

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ x ] On the Desktop

### Bug report checklist

- [ x ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[traffic-light](https://fontawesome.com/icons/traffic-light?style=solid) has been introduced in Font Awesome 5.2.0 and it is available for free in solid style.

Please try following:
1. Uninstall your current version of Font Awesome
2. Restart your machine
3. Install the latest .otf files (both regular and solid) from `fontawesome-free-5.4.0-desktop.zip` available at https://github.com/FortAwesome/Font-Awesome/releases
4. Select Font Awesome 5
5. Select Solid style
6. Check if traffic-light works
