### ISSUE TITLE
Icon headphones-alt not in desktop font

### ISSUE THREAD

**Issue by lastfuture** [FortAwesome/Font-Awesome#14089]
I copied the unicode glyph from https://fontawesome.com/icons/headphones-alt?style=solid to use in a layout, but the glyph did not show up in the latest OTF download of `Font Awesome 5 Free Solid`

I expected to see the glyph I copied in my layout or in macOS Font Book.

Version: Latest version of the OTF files, downloaded today (`fontawesome-free-5.3.1-desktop`)
- [x] On the Desktop

Reproduce by doing the following:
- Open Font Book
- uninstall all instances of `Font Awesome 5 Free` you may have
- download `fontawesome-free-5.3.1-desktop` from https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started
- install `Font Awesome 5 Free-Regular-400.otf` and `Font Awesome 5 Free-Solid-900.otf`
- copy the unicode glyph from https://fontawesome.com/icons/headphones-alt?style=solid by clicking it
- paste the glyph into the preview in Font Book, or into any program that is able to use the font

Checking the glyphs present in the font, I can see that the last glyph is code point `f4e3` while the glyph in question has code point `f58f` according to https://fontawesome.com/icons/headphones-alt?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> paste the glyph into the preview in Font Book, or into any program that is able to use the font

Could you please confirm that you have selected the **Solid** font style?

![image](https://user-images.githubusercontent.com/556268/46733767-834d3700-cc91-11e8-86a2-f1b1ebd0acd7.png)

**Comment by lastfuture** [comment]
Thank you,

yes I can confirm that I've selected the style solid. The following screenshot from macOS's Font Book shows the glyphs `headphones` and `headphones-alt` side by side in both Font Awesome 5 Regular and Bold

![screen shot 2018-10-10 at 13 55 09](https://user-images.githubusercontent.com/4239297/46734709-6403d900-cc94-11e8-821f-bb30a3f7eb64.png)

Missing glyphs for both are expected in Regular, since they're not part of Free, but Solid should contain both

**Comment by lastfuture** [comment]
Thank you, a restart solved it indeed. Maybe there were some font caches lingering. I can see and use both glyphs now.

**Comment by tagliala** [comment]
You're welcome, glad you solved
