### ISSUE TITLE
Add handshake icon

### ISSUE THREAD

**Issue by feyll** [FortAwesome/Font-Awesome#14097]
Hi, is it possible to add the "handshake" icon in the awesome font version 3.2.1?
[](https://fontawesome.com/v3.2.1/icons/)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, this is not possible: versions 2, 3 and 4 are in EOL.

Anyway, you can use an online tool to customize Font Awesome, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
