### ISSUE TITLE
Icon request: Workplace (brand)

### ISSUE THREAD

**Issue by pratikshan04** [FortAwesome/Font-Awesome#14096]
### What can it be used for?

Brand icon for [Workplace by Facebook](https://work.facebook.com). Icon to represent workplace, 'w' with one end extended as a curve.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10185, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
