### ISSUE TITLE
Icon Request - Google My Business Icon

### ISSUE THREAD

**Issue by SandraDevos** [FortAwesome/Font-Awesome#14091]
I have looked and cannot seem to find the Google My Business icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/2412#issuecomment-274662533 ?

**Comment by tagliala** [comment]
No feedback, closing here as a duplicate of #2412
