### ISSUE TITLE
Icon Request: fa-lacrosse icon

### ISSUE THREAD

**Issue by adamdjbrett** [FortAwesome/Font-Awesome#14106]
I love Font Awesome and I find the icon sets to be quite useful. It would be wonderful if y'all added a lacrosse icon to either the pro and/or free sets.  The lacrosse community and its developers would be greatly appreciative of this icon. Thanks.

**Comment by tagliala** [comment]
This should be available in FA6 alpha-3

![image](https://user-images.githubusercontent.com/556268/117349833-239c8400-aeac-11eb-98f6-032a3acb95d4.png)

**Comment by adamdjbrett** [comment]
Thank you
