### ISSUE TITLE
use.fontawesome.com is Down

### ISSUE THREAD

**Issue by MishUshakov** [FortAwesome/Font-Awesome#14103]
Hey, icons are not loading on my website
https://downforeveryoneorjustme.com/use.fontawesome.com

Says it's down for anyone

<img width="1436" alt="screenshot 2018-10-13 at 17 34 21" src="https://user-images.githubusercontent.com/10400064/46906572-50fc3d80-cf0e-11e8-823a-2f99b86d5aa2.png">

Need your feedback. Thank you, u are the best 🥇

**Comment by morgzz** [comment]
Seems to be working from my end.
Check https://status.fortawesome.com/

**Comment by MishUshakov** [comment]
Yeah, works again as expected, my location is EU/Germany.
Thank you.
