### ISSUE TITLE
Icon request: clock-1, clock-2, clock-3, ..., clock-12

### ISSUE THREAD

**Issue by robertotremonti** [FortAwesome/Font-Awesome#14113]
There's already a [clock icon set at 4:00 AM/PM](https://fontawesome.com/icons/clock?style=solid).
I suggest to add all 11 hours left, from 01:00 to 12:00.

**Comment by Crissov** [comment]
Unicode emoji #222:
🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛

**Comment by tagliala** [comment]
Now available in FA6 Pro: https://fontawesome.com/v6.0/icons?q=clock&new=yes&s=solid%2Cbrands
