### ISSUE TITLE
[Bug?] pseudo elements doesn't work on list elements with SVG/JS

### ISSUE THREAD

**Issue by medarob** [FortAwesome/Font-Awesome#14114]
Hi,

I noticed something strange and I don't know if I'm doing something wrong or if it's a bug...

I use FontAwesome 5 Free with SVG and Javascript.
I want to insert an Icon before a list element with the pseudo class ::before which worked on v4 but not now.

I get this:
![grafik](https://user-images.githubusercontent.com/33951787/46944772-3db6b280-d073-11e8-8e3e-74e72e95710c.png)

The icon is shown correct but there is still the square with the unicode value visible.

Here is my HTML Markup and CSS Code:
```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
	<style>
	ul{
		list-style-type: none;
	}
	ul li::before {
    	font-family: "Font Awesome 5 Free";
    	font-weight: 900;
    	content: "\f105";
	}
	</style>
	<script data-search-pseudo-elements src="fa54/js/all.min.js"></script>
</head>

<body>
	<ul>
		<li> <a href="#">Test1</a> </li>
		<li> <a href="#">Test2</a> </li>
		<li> <a href="#">Test3</a> </li>
		<li> <a href="#">Test4</a> </li>
		<li> <a href="#">Test5</a> </li>
		<li> <a href="#">Test6</a> </li>
		<li> <a href="#">Test7</a> </li>
		<li> <a href="#">Test8</a> </li>
	</ul>
</body>
</html>

```

Is it possible to remove the the square with the unicode value? I don't want to add ```<i>``` tags inside my list elements but not sure if that is possible... it has worked before with v4 but that was not SVG/JS.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is probably an issue in the documentation when using SVG and pseudoelements.

Please add ` display: none;` to `ul li::before` css rules

@talbs 

By following instructions at https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4, it is not clear that the SVG framework demands `display: none`

This is how a fiddle based on current instructions looks like: http://jsfiddle.net/tagliala/sLjurpda/

**Comment by medarob** [comment]
Thank you for your answer :-)

A simple solution for the problem.

**Comment by talbs** [comment]
Hey, gang.

Thanks for bringing this to our attention. We've updated the online docs to try to address this. You can find more information at https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#pseudo-elements and https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#with-svg-js.

Closing this with that update in mind. Please shout if anything is still confusing or could be made better. 😄
