### ISSUE TITLE
Icon request: icon-settings

### ISSUE THREAD

**Issue by nationalj** [FortAwesome/Font-Awesome#1411]
For general settings (when cogs are already used for a different purpose). What I think would be perfect is icon-tasks but with little pull handles separating the white and black in the bars.

**Comment by aethior** [comment]
There are several icons to represent settings:

- `fa-cog` (http://fontawesome.io/icon/cog/)
- `fa-cogs`(http://fontawesome.io/icon/cogs/)
- `fa-wrench`(http://fontawesome.io/icon/wrench/)
- `fa-sliders` (http://fontawesome.io/icon/sliders/)
- `fa-tasks` (http://fontawesome.io/icon/tasks/)

(cc @tagliala)

**Comment by tagliala** [comment]
Closing here, also because `settings` is quite abstract
