### ISSUE TITLE
fa-hammer class fails to produce a hammer icon

### ISSUE THREAD

**Issue by ryanwaldorf** [FortAwesome/Font-Awesome#14129]
Tried with fas and far--doesn't work for either

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

https://fontawesome.com/icons/hammer?style=solid has been introduced in Font Awesome 5.4.0.

Please double check that you are using FA >= 5.4.0

Please also check that there isn't another plugin/third party library loading older versions of Font Awesome that could be take precedence

If you still think there is an issue, please open a new request following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and add a reproducible test case

**Comment by ryanwaldorf** [comment]
I am a moron.  Thank you

**Comment by tagliala** [comment]
You're welcome, glad you solved... and please do not be so hard on yourself 😅
