### ISSUE TITLE
Icon request: allergy

### ISSUE THREAD

**Issue by amoralico** [FortAwesome/Font-Awesome#14132]
### What can it be used for?

In a medical app to highlight an alergy or a set of alergies.

### Example image (optional)

![image](https://user-images.githubusercontent.com/2392770/47170187-c056a080-d305-11e8-8429-87ee4f28f78b.png)
![image](https://user-images.githubusercontent.com/2392770/47170387-2b07dc00-d306-11e8-85f8-8a0efef0f9b4.png)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
@amoralico Does our current "allergies" icon cover this for you? https://fontawesome.com/icons?d=gallery&q=allergy

**Comment by amoralico** [comment]
Yes, it does. I did not realize that there was already one.
Thank you.

**Comment by DSwissK** [comment]
To be honest, this icon looks like a "soft glove". Could you provide an alternative ? (see example images above for some idea.)

Thank you-

**Comment by tagliala** [comment]
@DSwissK could you please open a new request and properly add example images?
