### ISSUE TITLE
Icon Request: fa-yammer

### ISSUE THREAD

**Issue by taralynnpeters** [FortAwesome/Font-Awesome#14133]
Could we have a Yammer icon, like this?

https://www.flaticon.com/free-icon/yammer_889159

![image](https://user-images.githubusercontent.com/26932125/47175381-d2195300-d2c7-11e8-824e-a28ef5c7757e.png)

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2707, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
