### ISSUE TITLE
Text Error in Icon Class

### ISSUE THREAD

**Issue by hackbal** [FortAwesome/Font-Awesome#14131]
### Describe the problem

https://fontawesome.com/icons/cloud?style=solid, Check this icon i class name.

itz like this `<i class="far fa-bookmark"></i>`

### What did you expect?

`<i class="fa fa-bookmark"></i>`

### What version and implementation are you using?

Version: Latest
Browser and version: Lastest

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://fontawesome.com/icons/cloud?style=solid

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`<i class="fas fa-cloud"></i>` is not a typo

Please take a look at https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use to understand how classes work in Font Awesome 5 and why `fa` prefix is still working.

Hope it helps

Closing here
