### ISSUE TITLE
Icon-request: Google Cloud

### ISSUE THREAD

**Issue by cbedwell** [FortAwesome/Font-Awesome#14137]
![google_cloud_48dp](https://user-images.githubusercontent.com/44295955/47222789-43ffa400-d37d-11e8-9631-f4c31dfe0dae.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12191, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by cbedwell** [comment]
Hi, sorry!
I did try to search and for some reason, it did not come up for me. Thanks!
