### ISSUE TITLE
Icon request: envelope-cog (email settings)

### ISSUE THREAD

**Issue by katie1348** [FortAwesome/Font-Awesome#14135]
### What can it be used for?

Email settings and configuration

### Example image (optional)

I would imagine, that it would be an envelope with a cog, like the other settings style icons.

This is not part of a pair, but could be part of a general settings or config set of icons for common configuration items in web apps or software.

### Icon request checklist

- [-] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that you can implement this icon with the SVG framework by taking advantage of layering and masking feature:

http://jsfiddle.net/tagliala/mfopk9qe/7/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by katie1348** [comment]
Hi Tagliala,

Thanks for your reply and for the demos, if working with HTML, that would indeed be a good solution and I do hope that it will help others with the HTML.

Unfortunately, I am using FA in a WPF app targeting windows, and that trick doesn't work. I can work around of course by compositing the icons on top of each other, but it is a lot of work and will not be as nice as an official icon.

:)

K

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
