### ISSUE TITLE
Icon request: IOT

### ISSUE THREAD

**Issue by m-peterman** [FortAwesome/Font-Awesome#14134]
What can it be used for?
In any purpose where instead of plain wifi where it only shows 1 connection this will show that they are interconnected like a cloud. It's a buzzword now. From mesh networks to bus GPS and all the way through to vending machines. this is really picking up. even brands like Netcomm and d-link are now calling their devices IoT instead of m2m or wifi as there is so much more than just the wifi symbol. it would be amazing to have a logo that becomes the norm.

Example image (optional)
![image](https://user-images.githubusercontent.com/20883398/47192039-47535980-d396-11e8-9ac0-c790d7399d76.png)
![image](https://user-images.githubusercontent.com/20883398/47192043-4d493a80-d396-11e8-8d98-3c2cfc07f96c.png)
![image](https://user-images.githubusercontent.com/20883398/47192033-3b679780-d396-11e8-8476-9dbe1e176f13.png)

Icon request checklist
  This is a single icon or matched pair (Ex: lock / unlock)
  The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
  I have searched for existing issues and to the best of my knowledge this is not a duplicate
  I have included at least one example image if it could be helpful (optional)
  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by danger89** [comment]
I also still want to see some kind of mesh-icon.
