### ISSUE TITLE
SVG + pseudo elements not working in Firefox 62.0.3

### ISSUE THREAD

**Issue by ErikAlbert** [FortAwesome/Font-Awesome#14138]
Hi, i'm using a node.js environment and i'm loading icons in an external js file (it's the first js file being loaded on the page) trough the svg api like this:

```
const library = require('@fortawesome/fontawesome-svg-core').library;
const dom = require('@fortawesome/fontawesome-svg-core').dom;
const config = require('@fortawesome/fontawesome-svg-core').config;
const fas = require('@fortawesome/free-solid-svg-icons').fas;
const far = require('@fortawesome/free-regular-svg-icons').far;
const fab = require('@fortawesome/free-brands-svg-icons').fab;

/* Initializations */
config.keepOriginalSource = false;
config.searchPseudoElements = true;
library.add(fas, far, fab);
dom.watch();
```

Then I use SASS to do the following styles:

```
.custom-radio {
    label {
        &::before {
            @extend .rounded-circle;
            box-shadow: 0px 0px 5px 2px rgba(0, 0, 0, 0.13);
        }

        &::after {
             display: none;
            font-family: "Font Awesome 5 Free";
            font-weight: 900;
            content: "\f111";
        }

        [data-fa-i2svg] {
            transform: scale(.2);
            color: $blue-deep;
        }
    }

    input:checked~label [data-fa-i2svg] {
        transform: scale(.5);
    }
}
```

Icons are showing well on chrome, but in firefox the svg tag is not added into the html:

![pseudo-not-shown](https://user-images.githubusercontent.com/28344692/47233641-ab484300-d3d3-11e8-8fb1-465e75ca7c0b.JPG)

This is how its being seen in chrome

![pseudo-being-shown](https://user-images.githubusercontent.com/28344692/47233638-a97e7f80-d3d3-11e8-945c-db00b9d31c5a.JPG)

Please help, I don't really understand whats happenning here.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can't replicate on Firefox 62.0.3 / Windows 10.

Could you please provide a reduced test case based on http://jsfiddle.net/tagliala/13endrp6/4/ ?

Please also note that [we do not recommend to use pseudoelements with the SVG framework](https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements)

**Comment by ErikAlbert** [comment]
Hi tagliala!

thanks for your response :)

I don't know how to reproduce my environment in a fiddle... i'm using node.js + gulp + browserify to automate my workflow.  (I'll tried many times the requirebin utility which has browserify, but always gave me cors error.)

I'll can give u more info about my project...

The first fragment of code I posted is a part of a file which is being loaded as the first javascript file in the footer of the page.

The only think I can think of is that Browserify causes all the code it exposes to be in a closure... may be this is somewhat a problem?

**Comment by ErikAlbert** [comment]
Well, I discovered what was causing the issue.... the label which has to have the after pseudo element was using a mixin a class to reset after styles:

```
@mixin pseudo-icon($pseudo-type) {
    &::#{$pseudo-type} {
        display: none;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
    }
}
```

After calling the mixin to reset the pseudo element styles, we add specific styles to the after pseudo element:

```
label {
        @include pseudo-icon(after);
        margin-bottom: 0;

        &::before,
        &::after,
        [data-fa-i2svg] {
            position: absolute;
            top: .25rem;
            left: 0;
            width: 13px;
            height: 13px;
            content: "";
        }

        &::before {
            background-color: white;
            border: 1px solid $input-border;
            cursor: pointer;
        }

        &::after {
            font-family: "Font Awesome 5 Free";
            font-weight: 900;
        }

        [data-fa-i2svg] {
            opacity: 0;
            transition: opacity 300ms ease-in-out, transform 300ms ease-in-out;
            cursor: pointer;
        }
    }
```

Well, the isssue is clear now... in chrome this is working as expected, but in firefox the after is not shown, maybe due to the "display:none" style from the mixin.

Why the svg element is not appended to the HTML in Firefox? curiosity :)

**Comment by ErikAlbert** [comment]
Hi again, I found the issue... but i don't understand why the svg element is not being added to the document in Firefox.

I'm using a mixin to reset the pseudo element styles and this is causing the issue with firefox.

This is the mixin:

```
@mixin pseudo-icon($pseudo-type) {
    &::#{$pseudo-type} {
        display: none;
        font-style: normal;
        font-variant: normal;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
    }
}
```

And this are the styles were we use them:

```
label {
        @include pseudo-icon(after);
        margin-bottom: 0;

        &::before,
        &::after,
        [data-fa-i2svg] {
            position: absolute;
            top: .25rem;
            left: 0;
            width: 13px;
            height: 13px;
            content: "";

            @include media-breakpoint-up(sm) {
                width: 15px;
                height: 15px;
            }
        }

        &::before {
            background-color: $white;
            border: 1px solid $input-border;
            cursor: pointer;
            content: "";
        }

        &::after {
            font-family: $fa-free;
            font-weight: 900;
        }

        [data-fa-i2svg] {
            opacity: 0;
            transition: opacity 300ms ease-in-out, transform 300ms ease-in-out;
            cursor: pointer;
        }
    }

    input:checked~label [data-fa-i2svg] {
        opacity: 1;
    }

.custom-radio {
    @include selector-animation($radio-transform);

    label {
        &::before {
            @extend .rounded-circle;
            box-shadow: 0 0 5px 2px rgba(0, 0, 0, 0.13);
        }

        &::after {
            content: "\f111";
        }

        [data-fa-i2svg] {
            transform: scale(.2);
            color: $blue-deep;
        }
    }

    input:checked~label [data-fa-i2svg] {
        animation: custom-selector 500ms ease;
        transform: scale(.5);
    }
}
```

Why this is causing the issue with Firefox?

**Comment by ErikAlbert** [comment]
test

**Comment by ErikAlbert** [comment]
test

**Comment by ErikAlbert** [comment]
test

**Comment by ErikAlbert** [comment]
test

**Comment by arjendejong12** [comment]
I'm having the same issues on Firefox 65.0a1 where the SVG is not rendered in a pseudo element.
I've followed the guide on the site to the T.
![image](https://user-images.githubusercontent.com/10572554/47839096-c8a4e600-ddb1-11e8-8328-4730cf591eff.png)

**Comment by tagliala** [comment]
Closing here, but if there are still issues feel free to open a new one by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
