### ISSUE TITLE
Icon request: icon-piggy-bank

### ISSUE THREAD

**Issue by allegrettimarco** [FortAwesome/Font-Awesome#1413]
Hi, would it be possible to create a piggy ban icon? I would like to use it to represent an overall amount.

Thanks,
Marco
![icon-piggy-bank](https://f.cloud.github.com/assets/4330618/706003/cc564850-dde1-11e2-8de4-9a1c9b58a4e6.png)

**Comment by roydejong** [comment]
+1

**Comment by tkwidmer** [comment]
+1

**Comment by richardsengers** [comment]
+1

**Comment by 4bdulll4** [comment]
when these icons will be released?

**Comment by gkorban** [comment]
+1

**Comment by cesarizu** [comment]
+1

**Comment by taylor-chen** [comment]
+1

**Comment by sebastien-fauvel** [comment]
:+1:

**Comment by caih** [comment]
+1

**Comment by monimerlo** [comment]
+1

**Comment by buzzudit** [comment]
+1

**Comment by TGWerner** [comment]
+1

**Comment by spjwebster** [comment]
+1

**Comment by ankitraturi** [comment]
+1

**Comment by gonzasdel** [comment]
+1

**Comment by max-favilli** [comment]
+1

**Comment by akz92** [comment]
+1

**Comment by katiebeee** [comment]
+1

**Comment by ITPrism** [comment]
+1

**Comment by WastedCharlie** [comment]
+1

**Comment by soodaa** [comment]
+1

**Comment by VeeK727** [comment]
+1 to piggy bank with coin icon

**Comment by chellem** [comment]
+1

**Comment by macdonaldr93** [comment]
+1

**Comment by vanderv** [comment]
+1

**Comment by Sybio** [comment]
Agreed to ! Need this icon in Awesome.

**Comment by LeartS** [comment]
+1

**Comment by melm73** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by angiejones** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by salazarp** [comment]
+1

**Comment by Coffeecream** [comment]
+1

**Comment by omnilight** [comment]
+1

**Comment by brcolow** [comment]
+1

**Comment by FlashBlack** [comment]
+1

**Comment by rajeev1982** [comment]
+1

**Comment by rjcristy** [comment]
+1

**Comment by bashkarev** [comment]
+1

**Comment by lofish72** [comment]
Please, can you add the piggy bank icon?

**Comment by arrutneo** [comment]
+1

**Comment by danielcorin** [comment]
:+1:

**Comment by simonfranz** [comment]
+1

**Comment by lsruthi** [comment]
+1

**Comment by jd987** [comment]
+1

**Comment by ITPrism** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by alxhotel** [comment]
+1

**Comment by LeartS** [comment]
Stop with the +1 guys, github introduced reactions specifically for things like these. Click on the emoticon on the first message, select the thumbs up and stop spamming the issue. That way we can all subscribe to the issue to receive updates if there are some new developments, without having to be spammed by 2 char messages.

**Comment by q2apro** [comment]
Here an extended pig: 

![payicon_guthaben-200](https://cloud.githubusercontent.com/assets/6764548/15464456/25fa18be-20d8-11e6-8f9f-d69a08d69eac.png)

**Comment by djdeniro** [comment]
+1

**Comment by johnnyshields** [comment]
A pig icon (not piggy bank) is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by cozzbie** [comment]
+1

**Comment by MaximeAnsquer** [comment]
+1

**Comment by hanns** [comment]
+1

**Comment by shgarg27** [comment]
+1

**Comment by rui-castro** [comment]
:+1:

**Comment by odubuc** [comment]
👍

**Comment by edwardmcconville** [comment]
+1 please

**Comment by tbagdzius** [comment]
+1.1

**Comment by saniaja** [comment]
+1

**Comment by leandrovr13** [comment]
+1

**Comment by axelys** [comment]
+1

**Comment by pavitaj** [comment]
+1

**Comment by fcomarbl** [comment]
+1

**Comment by web2tips** [comment]
+1

**Comment by andela-calim** [comment]
+1

**Comment by Necromancerx** [comment]
+1  :thumbsup:

**Comment by pinta83** [comment]
+1
I wonder if any of the developer even bother to read this issues.... almost 4 years and still nothing :(

**Comment by vinnyamp** [comment]
+1

**Comment by pprinz** [comment]
+1

**Comment by rajananimator** [comment]
+1

**Comment by codeurge** [comment]
+1

**Comment by yh0an** [comment]
+1

**Comment by pinta83** [comment]
4 years and still nothing, although the graphics are provided by the users in the same post... Same goes for[ "smoking" icon](https://github.com/FortAwesome/Font-Awesome/issues/726)....
Really a shame.....

**Comment by uxpool** [comment]
+1

**Comment by shanebrunette** [comment]
+1

**Comment by fr1ts** [comment]
+1

**Comment by Shento999** [comment]
+1

**Comment by Benraay** [comment]
+1

**Comment by ugurdinch** [comment]
+1

**Comment by zaqueoae** [comment]
+1

**Comment by spanglishwebs** [comment]
+1

**Comment by danvn** [comment]
+!

**Comment by BalalRaza** [comment]
+1
Please someone add this now!

**Comment by BloomCake** [comment]
+1

**Comment by lvlakku** [comment]
Also, 
![piggybank](https://user-images.githubusercontent.com/25906486/36884070-73686314-1e04-11e8-8df4-b00b27621ea2.png)

**Comment by sensibleworld** [comment]
It's on its way ;)

**Comment by sensibleworld** [comment]
Released in 5.0.9

**Comment by pinta83** [comment]
Wow... almost 5 years :)
I wonder when the "Smoking" / "No smoking" icon will be released :)

**Comment by sensibleworld** [comment]
@pinta83 Smoking was added recently, as well: https://fontawesome.com/icons/smoking?style=solid

The non-smoking icon is coming as part of our upcoming 5.1 release.

**Comment by pinta83** [comment]
Sweeeeeeet :) :+1:
