### ISSUE TITLE
Icon request: car-power

### ISSUE THREAD

**Issue by abdullahhafizh** [FortAwesome/Font-Awesome#14148]
### What can it be used for?

to show the power of car (hp)

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by abdullahhafizh** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Could you please provide an example?

![image](https://user-images.githubusercontent.com/19485897/62834584-d8beef80-bc78-11e9-8fa6-778a9c7446a5.png)

**Comment by tagliala** [comment]
Hi again, could you please provide a single color, small size (16px) suitable example?

**Comment by abdullahhafizh** [comment]
> Hi again, could you please provide a single color, small size (16px) suitable example?

![image](https://user-images.githubusercontent.com/19485897/62835399-50454c80-bc82-11e9-9d1d-075f3485f56b.png)

**Comment by tagliala** [comment]
@abdullahhafizh does https://fontawesome.com/icons/tachometer-alt?style=solid fit your use case?

**Comment by abdullahhafizh** [comment]
> @abdullahhafizh does https://fontawesome.com/icons/tachometer-alt?style=solid fit your use case?

ok, theres an update im not see it
