### ISSUE TITLE
Icon request: car-seat

### ISSUE THREAD

**Issue by abdullahhafizh** [FortAwesome/Font-Awesome#14146]
### What can it be used for?

to show count of seats in car

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Crissov** [comment]
Unicode emoji #222:
💺

**Comment by boxview** [comment]
Would really like to see this. It can be used in medical too.

**Comment by abdullahhafizh** [comment]
[seat-airline](https://fontawesome.com/icons/seat-airline) on PRO
