### ISSUE TITLE
<i class="fa fa-html5"></i>

### ISSUE THREAD

**Issue by Percipity** [FortAwesome/Font-Awesome#14140]
The "copy" on the icon for html5 reads 
i class="fab fa-html5"

instead of 

i class="fa fa-html5"

so that extra b causes it not to work.  Not a big deal, but thought you would like to know.  Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fab` is not a typo. You are probably using Font Awesome 4.

Please take a look here to see changes in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

Closing here
