### ISSUE TITLE
Icon request: icon-bag-coins, icon-money-bag

### ISSUE THREAD

**Issue by allegrettimarco** [FortAwesome/Font-Awesome#1414]
Hi,

related to issue #1413 , would it be also possible to create a bag of coins icon? It will be useful to alternate it with the piggy bank icon.

Thanks,
Marco
![icon-bag-coins](https://f.cloud.github.com/assets/4330618/706017/4e743b08-dde2-11e2-8915-dad5082c0c9f.png)

**Comment by krisdahl** [comment]
+1

**Comment by bertoost** [comment]
+1

**Comment by castocolina** [comment]
+1

**Comment by tzusman** [comment]
I just launched [CustomFontIcons.com](https://customfonticons.com/), a place to get crowd-commissioned icons.  All commissioned icons are then released as part of a free font icon set.  A coin bag icon has already been designed and is available in that set.

**Comment by caih** [comment]
+1

**Comment by dixalex** [comment]
+1

**Comment by sebastien-fauvel** [comment]
+1

**Comment by Kenith** [comment]
+1

**Comment by RensBonnez** [comment]
+1

**Comment by lossantis** [comment]
+1

**Comment by rotherfuchs** [comment]
+1

**Comment by ewillebrands** [comment]
+1

**Comment by lsruthi** [comment]
+1

**Comment by My1** [comment]
+1

**Comment by ITPrism** [comment]
+1

**Comment by edicius6** [comment]
+1

**Comment by joel2703** [comment]
+1

**Comment by johnsanmiguel** [comment]
+1

**Comment by edwardmcconville** [comment]
+1 please

**Comment by mrakholiya** [comment]
+1 please

**Comment by orzilca** [comment]
+1

**Comment by skylee91** [comment]
+1

**Comment by HeroRender** [comment]
+1

**Comment by DmStepanov** [comment]
Yes? I need a money bag!

**Comment by rwb196884** [comment]
+1 but please without the `$`; it isn't useful outside of North America.

**Comment by yadhu** [comment]
+1

**Comment by ErickXavier** [comment]
+1

**Comment by jahlela** [comment]
+1

**Comment by cblaettl** [comment]
+1

**Comment by hmkhafan** [comment]
+1

**Comment by thankgodr** [comment]
+1

**Comment by bkbonner** [comment]
Folks, I believe you have to click the 'thumbs up' icon next to the initial request.  I'm guessing that's why it isn't included yet.

**Comment by Batacus** [comment]
+1

**Comment by BloomCake** [comment]
+1

**Comment by lukaramishvili** [comment]
+1

**Comment by sensibleworld** [comment]
We stopped by Scrooge McDuck's vault and picked up a withdrawal: https://fontawesome.com/icons/sack-dollar?style=solid
https://fontawesome.com/icons/sack?style=solid

**Comment by urgent** [comment]
@allegrettimarco Is your image free for use with modification?

**Comment by allegrettimarco** [comment]
@urgent sure, you're free to use it with modification
