### ISSUE TITLE
Icon request: icon-football-field (soccer)

### ISSUE THREAD

**Issue by allegrettimarco** [FortAwesome/Font-Awesome#1415]
Hi,

since I am creating a website about football (or soccer as you wish), would it be possible to create an icon for the football field?

Thanks,
Marco
![icon-field](https://f.cloud.github.com/assets/4330618/706028/8c7bb5fc-dde2-11e2-9c77-b54e2d24fbd6.png)

**Comment by Elmister** [comment]
+1

**Comment by larsfjerm** [comment]
+1

**Comment by cassiebrooks** [comment]
+1

**Comment by elyrium** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/court-sport?f=classic&s=solid
