### ISSUE TITLE
Icon Request: fa-bauble

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#14156]
This icon could be used to represent christmas decorations and Christmas in general. Below is an example:
![image](https://user-images.githubusercontent.com/25369857/47281586-b36ed100-d5d3-11e8-93ee-6e230cc4461c.png)

**Comment by aethior** [comment]
Hi @Wingo5315,

This icon was added in v5.6.0.
Check https://fontawesome.com/icons/ornament

Regards.

cc/ @tagliala
