### ISSUE TITLE
Icon request: icon-brick-wall

### ISSUE THREAD

**Issue by leandrokemper** [FortAwesome/Font-Awesome#14151]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

**Comment by JizZuS** [comment]
Hello,
We would really appreciate the wall icon for our planning software. There is a tool for drawing walls and we are currently using a equals icon for that :-( , but the wall would be so much better.

Possible examples:

![image](https://user-images.githubusercontent.com/7282431/56798802-d646a000-6817-11e9-86ce-0ce6d2f7df58.png)

![image](https://user-images.githubusercontent.com/7282431/56798899-0db54c80-6818-11e9-96ac-c27cbd528bdc.png)

![image](https://user-images.githubusercontent.com/7282431/56798934-2160b300-6818-11e9-9d5d-5f3b37b45030.png)

Something like this but more simple, would be perfect...

**Comment by didix16** [comment]
Any news about the new wall icon?

**Comment by defaultsecurity** [comment]
+1

**Comment by aethior** [comment]
Hi @leandrokemper,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/block-brick

Regards.

cc/ @tagliala
