### ISSUE TITLE
Can't install this package with yarn when offline

### ISSUE THREAD

**Issue by ruslangaripov** [FortAwesome/Font-Awesome#14164]
I ended up with an issue installing \`\`fontawesome-free'' using the \`\`yarn'' package manager when running the [\`\`compiler explorer''][1] instance on an **offline** machine.

The \`\`fontawesome-free'' package was added in the [re5b1956][2] using the following declaration of a dependency:

> ...
> "@fortawesome/fontawesome-free": "^5.3.1",
> ...

This ends up with this in the 'yarn.lock' file:

> "@fortawesome/fontawesome-free@^5.3.1":
>   version "5.3.1"
>   resolved "https://registry.yarnpkg.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.3.1.tgz#5466b8f31c1f493a96754c1426c25796d0633dd9"

Okay. Now I try to `yarn install --offline` on an offline machine having the most recent snapshot of the \`\`compiler explorer''. There is downloaded 'fontawesome-free-5.3.1.tgz' tarball located in the yarn offline mirror, which (mirror) was set up on the offline machine. The offline mirror worked and works fine. After I have run `yarn install --offline`, it creates **empty** 'npm-\@ fortawesome' (*without space after \@, I just have to stop github from applying nick-names here*) directory in the yarn cache (while all other packages has its directories like 'npm-package_name-version-hash'). Because there is nothing in the yarn cache for \`\`fontawesome-free'' package, yarn fails to install this package in offline mode.

If I remove \`\`\@ fortawesome'' from the link in the 'yarn.lock' file (making `resolved` as "https://registry.yarnpkg.com/fontawesome-free/-/fontawesome-free-5.3.1.tgz#5466b8f31c1f493a96754c1426c25796d0633dd9" -- this is how all other dependencies' URLs look like), everything works fine and yarn now is able to install this package from the offline mirror (from 'fontawesome-free-5.3.1.tgz' tarball).

Therefore, why is there \`\`@ fortawesome'' existed in the link? How can I fix offline installation with yarn package manager without that ugly workaround?

**edit**: fix yarn cache's directory name (change from '\@ fortawesome' to 'npm-\@ fortawesome').

[1]: https://godbolt.org/
[2]: https://github.com/mattgodbolt/compiler-explorer/commit/e5b1956162d18c6b1e2191c1ea2f29ee09528fed

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I can't help here. Leaving this open for feedback from the Community

> Therefore, why is there ``@ fortawesome'' existed in the link

If you are referring to `@fortawesome`, it is an [npm scope](https://docs.npmjs.com/misc/scope)
