### ISSUE TITLE
Icon request: discord-alt

### ISSUE THREAD

**Issue by madebyjustas** [FortAwesome/Font-Awesome#14161]
### What can it be used for?

This can be used for numerous websites that want an icon redirect to their discord server, as existing Discord logo in Font Awesome library is great, but when it is small it can be hard to see and this one overall has the same meaning and similar look, but is also easy to see when in small size and overall looks better.

### Example image (optional)

![discord](https://user-images.githubusercontent.com/44247810/62101352-66700780-b295-11e9-93c7-f4ba444ad236.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Waterovsky** [comment]
@tagliala we need alternative Discord icon since 10.2018! Give it to us :/

**Comment by fishiflor** [comment]
Esports orgs are blowing up so having this icon would help me on multiple projects. Please consider!

**Comment by RaptorInternals** [comment]
![Capture](https://user-images.githubusercontent.com/73164889/117509146-a93e3380-af81-11eb-9412-2d22d718ff5b.PNG)
![Capture](https://user-images.githubusercontent.com/73164889/117508548-aee74980-af80-11eb-8176-436631a7141f.PNG)

I changed the icons on my website to alt versions and it looks a lot better - apart from the Discord for a lack of the alt version existing! +1

**Comment by tagliala** [comment]
Hi, apparently Discord listened and they've changed their logo to match this one :)

https://discord.com/brand-new/branding

Let's use #17897 to track this change, this will done for sure
