### ISSUE TITLE
typo in class name

### ISSUE THREAD

**Issue by Katerinka28** [FortAwesome/Font-Awesome#14177]
http://joxi.ru/MAjQ83lC4J1OY2

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
