### ISSUE TITLE
Icon Set request - wedding

### ISSUE THREAD

**Issue by giorgiopuoti** [FortAwesome/Font-Awesome#14179]
**Wedding Icon set**
This icon can be used on all website concerning wedding
example: https://www.shutterstock.com/image-vector/wedding-icon-set-vector-eps10-245321959

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but requesting icon sets does not meet pur [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md).

If you are a Font Awesome Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
