### ISSUE TITLE
 Icon request: icon-grin

### ISSUE THREAD

**Issue by seantcallahan** [FortAwesome/Font-Awesome#1417]
It would be great to have an additional emoticon that shows the teeth over a wide grin. If there were five emoticons I could see using these as a rating system, with grin, happy, meh, frown and grumpy.

![grin](https://f.cloud.github.com/assets/1906959/707029/46d23a80-de0a-11e2-97eb-1bd8ba153572.png)

**Comment by markgp** [comment]
+1

**Comment by dattard21** [comment]
+1 - would love to have this too!

**Comment by mcp84** [comment]
+1

**Comment by Garo263** [comment]
+1 I really need it for work

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&c=emoji
