### ISSUE TITLE
Feature request: different weight (solid,regular,light) for alpha-numerics: A:Z, 0:9

### ISSUE THREAD

**Issue by db28691** [FortAwesome/Font-Awesome#14183]
Not sure if "feature request" is appropriate in this case. I'd like to see a change to how existing glyphs are rendered.

All three FA styles carry alpha-numeric glyphs, e.g. far-x, far-three. It appears that all three styles carry the same version of a particular glyph, i.e. far-x, fas-x, and fal-x are all the same.

It'd be great if different font styles contained different characters, consistent with font-wide conventions. I'm picturing something similar to the differences between far-walking, fas-walking, and fal-walking.

Thanks a lot

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, this is out of scope at the moment

Ref: #2828
