### ISSUE TITLE
Icon request: icon-grumpy

### ISSUE THREAD

**Issue by seantcallahan** [FortAwesome/Font-Awesome#1418]
It would be great to have an additional emoticon for grumpy. If there were five emoticons I could see using these as a rating system, with grin, happy, meh, frown and grumpy.

![grumpy](https://f.cloud.github.com/assets/1906959/707037/aa14380a-de0a-11e2-8655-cdfe138bdfb8.png)

**Comment by aethior** [comment]
Hi @seantcallahan!

This request maybe be solved by [fa-angry](https://fontawesome.com/v5.15/icons/angry) or [fa-tired](https://fontawesome.com/v5.15/icons/tired) icons?

cc/ @tagliala

**Comment by tagliala** [comment]
I was trying to figure out if this icon has a specific unicode point, but I'm not able to figure it out, but given the use case

> with grin, happy, meh, frown and grumpy.

I would consider this fixed by angry
