### ISSUE TITLE
fab fa-bing

### ISSUE THREAD

**Issue by unstructuredprogrammer** [FortAwesome/Font-Awesome#14184]
It's nice to have the Bing icon among other icons
please create it! i really need it

**Comment by unstructuredprogrammer** [comment]
black and white <3

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2499, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
