### ISSUE TITLE
Icon Set request - Environment, Nat

### ISSUE THREAD

**Issue by giorgiopuoti** [FortAwesome/Font-Awesome#14180]
**Environment, Nat Icon Set**
This icon can be used on all website concerning sea, country, nat, environment
example: https://www.dreamstime.com/natural-icons-set-colorful-nature-elements-white-background-natural-icons-mountains-sea-sun-clouds-dolphin-flower-cactus-image116578714

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but requesting icon sets does not meet pur [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md).

If you are a Font Awesome Pro user, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
