### ISSUE TITLE
API to search/query the icons

### ISSUE THREAD

**Issue by arunkumar413** [FortAwesome/Font-Awesome#14193]
Hi Team,

Can you please provide an api for searching the icons? Currently we have to use the cheat sheet or search for icons using your website. It would be of great use for third-party apps if there is an api for searching the icons.

Thanks,
Arun

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please edit this request and follow our [feature request template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=feature-request.md)?

**Comment by arunkumar413** [comment]
Raised here:
https://github.com/FortAwesome/Font-Awesome/issues/14211

**Comment by whoiswillian** [comment]
i've done something like that and using a free azure service, so, if someone want to me to mantain, i'll need money or just dont abuse.

https://icon-leets.azurewebsites.net/api/Icons

skip take like

https://icon-leets.azurewebsites.net/api/Icons?skip=0&take=10 <---- this is default, params are not needle

and search like that

https://icon-leets.azurewebsites.net/api/Icons?search=instagram // {partial term or partial name} like "instagram" or "yout"

is fully on code, dont use DB
