### ISSUE TITLE
Strange behaviour with <a> around font-awesome

### ISSUE THREAD

**Issue by cgrisar** [FortAwesome/Font-Awesome#14197]
I use version 5.4.2, svg + js.

This is the code:

```
<div class="fa-2x">
        <a href="mailto:{{ e_mail }}">
          <span class="fa-layers fa-fw">
              <i class="fas fa-circle text-red-darker"></i>
              <i class="fas fa-at fa-inverse" data-fa-transform="shrink-6"></i>
          </span> 
        </a>
        
        <a href="{{ www }}">
          <span class="fa-layers fa-fw">
              <i class="fas fa-circle text-red-darker"></i>
              <i class="fas fa-globe fa-inverse" data-fa-transform="shrink-6"></i>
          </span>
        </a>

</div>
```

Please find the result in the file.

Seems OK, save for an "underscore" between the icons.

- The underscore is not a hard underscore: it doesn't appear in the HTML as an underscore
- The "underscore" is with the first <a>
- The "underscore" will disappear if I use only one of the icons (it doesn't matter which one goes away)
- The "underscore" will not disappear if I create 2 inline `<div class="inline fa-2x">`
- I use Safari, same issue in Firefox

Any ideas as to why the underscore appears and how to prevent it from appearing?

![screen shot 2018-10-30 at 22 38 46](https://user-images.githubusercontent.com/7884608/47752405-a5384900-dc94-11e8-8a80-00e2a063885f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that you are putting a `display: inline-block` element such as `.fa-layers` inside an `inline` element, as a basic `<a>` tag.

Please change your a element with icons to `display: inline-block` style or move the `<a>` 

You can see the same behaviour here without font awesome: http://jsfiddle.net/tagliala/81beyLzw/

Hope it helps

Closing here

**Comment by cgrisar** [comment]
Thanks. Works perfectly.
