### ISSUE TITLE
Root-me icon

### ISSUE THREAD

**Issue by Twuxx** [FortAwesome/Font-Awesome#14208]
Hi, i want to know if its possible to add root-me icon ? www.root-me.org.

If its possible to have fa-rootme for example 

Thanks ! :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12491, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
