### ISSUE TITLE
search icon class not working

### ISSUE THREAD

**Issue by Patilronya** [FortAwesome/Font-Awesome#14203]
### Describe the problem

<i class="fal fa-search"></i> is not working. because class name has extra "l" in it. 

### What did you expect?

ideally class name should be "fa fa-search"

### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab`/`fal` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
