### ISSUE TITLE
FontAwesome React Component not working properly

### ISSUE THREAD

**Issue by oderindeolayemi** [FortAwesome/Font-Awesome#14216]
### I expected the brand icons to work as well

![screenshot 418](https://user-images.githubusercontent.com/39890277/47952288-2c274300-df6d-11e8-85c2-507509a40305.png)
![screenshot 419](https://user-images.githubusercontent.com/39890277/47952289-2c274300-df6d-11e8-85e5-ba6b8a88732c.png)
![screenshot 420](https://user-images.githubusercontent.com/39890277/47952290-2cbfd980-df6d-11e8-9b65-1b2b648b15e9.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by tagliala** [comment]
Hi again @oderindeolayemi 

I think I've got your issue

Please change:
```html
<FontAwesomeIcon icon="facebook-f" />
```

with:
```html
<FontAwesomeIcon icon={["fab", "facebook-f"]} />
```


Example: https://codesandbox.io/s/o84659ok6
Ref: https://github.com/FortAwesome/react-fontawesome#build-a-library-to-reference-icons-throughout-your-app-more-conveniently

> The "check-square" icon is getting a default prefix of fas here too, which is what we want, because that icon also lives in the @fortawesome/free-solid-svg-icons package.

However, the "apple", "microsoft", and "google" brand icons live in the package @fortawesome/free-brands-svg-icons. So we need to specify a different prefix for them—not the default fas, but fab, for Font Awesome Brand.

Hope it helps, closing here

Feel free to comment and I will reopen if you still have issues
