### ISSUE TITLE
Icon "font-awesome-logo-full" is broken on cheatsheet page

### ISSUE THREAD

**Issue by InsanityMeetsHH** [FortAwesome/Font-Awesome#14215]
### Describe the problem

The icon for "font-awesome-logo-full" is broken.
https://fontawesome.com/cheatsheet
![screenshot_2018-11-02 font awesome 5 cheatsheet 1](https://user-images.githubusercontent.com/35538671/47935282-23d1f800-deda-11e8-938f-0d57bd68991d.png)

### What did you expect?

Icon should be removed from page or fixed.

### What version and implementation are you using?

Version: 5.5.0
Browser and version: FireFox 62.0.3 (64-Bit) Windows

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Go to https://fontawesome.com/cheatsheet and search for "font-awesome-logo-full".
See also: https://github.com/FortAwesome/Font-Awesome/blob/4f4cb7c2f55d14d24f10390ebfeab0d25af612f3/CHANGELOG.md#changed-4.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks for reporting this

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @InsanityMeetsHH and @tagliala. This icon is only meant to be used as a usability improvement when using Font Awesome on the desktop (to help in typeface selection menus). We've hidden it elsewhere from icon listings on the site and I'll do the same here. 😄

**Comment by talbs** [comment]
Thanks again for the heads up on this. We just updated https://fontawesome.com/cheatsheet and that icon shouldn't be causing any trouble or sneaking into the listing there any longer. 😄
