### ISSUE TITLE
FontAwesome React Component not working properly

### ISSUE THREAD

**Issue by oderindeolayemi** [FortAwesome/Font-Awesome#14217]
### Describe the problem

I installed the @fortawesome React component, but upon importing it in my React app. Only the solid icons are displaying, no brand icons are displaying and i dont know how to rectify the issue.

### What did you expect?

I expected the brand icons to display the same way that the solid icons do. 

### What version and implementation are you using?

I'm using the FontAwesome React Component

### Images
![screenshot 418](https://user-images.githubusercontent.com/39890277/47952748-8d9ee000-df74-11e8-8707-7ce2f9482cfc.png)
![screenshot 420](https://user-images.githubusercontent.com/39890277/47952749-8e377680-df74-11e8-8273-bfac9921126f.png)
![screenshot 419](https://user-images.githubusercontent.com/39890277/47952750-8e377680-df74-11e8-92e0-453da5f64bc5.png)

### Bug report checklist

- [* ] I have filled out as much of the above information as I can

**Comment by tagliala** [comment]
@oderindeolayemi sorry for being pedantic.

Please use #14216

Please edit the first post as shown here:
![image](https://user-images.githubusercontent.com/556268/47953087-ab6e4400-df78-11e8-80d8-00b204675f08.png)
![image](https://user-images.githubusercontent.com/556268/47953099-c345c800-df78-11e8-9f95-6c87b49b66d1.png)

Please fill all the information required, as required here: https://github.com/FortAwesome/Font-Awesome/issues/14216#issuecomment-435587816

> In order to be clearer:
>
> - Provide versions of all your components (node, react, yarn/npm, font awesome libraries)
> - Provide your package.json and package.lock/yarn.lock
> - Provide the actual code, not only screenshot
> - Browser and version
> - Make sure that you have included our react component and implemented as described in our documentation: https://fontawesome.com/how-to-use/on-the-web/using-with/react
> - Disable all extensions that may interfer with font awesome or javascript
> 
> 
> Last but not least:
> - Reproducible reduced test case

**Comment by oderindeolayemi** [comment]
Thanks for solution. I got via email about referencing the brand icons differently.
