### ISSUE TITLE
Icon request: healthgrades

### ISSUE THREAD

**Issue by damky** [FortAwesome/Font-Awesome#14214]
use case: for use on website to link to healthgrades profile.
![image](https://user-images.githubusercontent.com/18455931/47932302-856c7500-de8e-11e8-8c97-1fcd182de0ba.png)
![image](https://user-images.githubusercontent.com/18455931/47932368-ad5bd880-de8e-11e8-93f5-2cd75255c3ec.png)

https://www.healthgrades.com/

(the png looks a little smashed. the svg on the healthgrades site is better.)

**Comment by tagliala** [comment]
Hi @damky thanks for the heads up.  I will edit the logo at #10534
