### ISSUE TITLE
can you add Panda icon to animal icons

### ISSUE THREAD

**Issue by HaiyanDu7** [FortAwesome/Font-Awesome#14218]

**Comment by Crissov** [comment]
🐼 U+1F43C #222

**Comment by HaiyanDu7** [comment]
awesome!

Sean Du {Haiyan Du}
300 John Street, 7B, Greer, SC 29651 USA
Phone: 410-900-3452
Why wait in line, order online
https://www.GogoMenu.com <https://www.uphillsoft.com>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #8623, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
