### ISSUE TITLE
Version 5.5.0 for react missing new icons

### ISSUE THREAD

**Issue by samysam01** [FortAwesome/Font-Awesome#14229]
Hi,

i tried to use some of the new weather icons now available under version 5.5.0. Two of them worked fine but for an unknown reason the other free icons wouldnt import... here is my package:

"dependencies": {
    "@fortawesome/fontawesome-svg-core": "1.2.4",
    "@fortawesome/free-solid-svg-icons": "5.5.0",
    "@fortawesome/react-fontawesome": "0.1.3",

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate.

https://codesandbox.io/s/o84659ok6

> i tried to use some of the new weather icons now available under version 5.5.0. Two of them worked fine but for an unknown reason the other free icons wouldnt import... here is my package:

Please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)
