### ISSUE TITLE
fab fa-linkedin-in not working in firefox

### ISSUE THREAD

**Issue by iftifar-taz** [FortAwesome/Font-Awesome#14226]
### This is a bug regarding fab fa-linkedin-in
When I try to use
`<i class="fab fa-linkedin-in"></i>`
in Chrome, Opera and Edge it loads, but in Firefox it does not load.

### Expected behavior
To load icon in all browsers.

### Minimal steps to reproduce of the problem
1. Include font-awesome css in html head
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">`
2. Use following code in body
`<i class="fab fa-linkedin-in"></i>`

alternatively

visit [https://fontawesome.com/icons/linkedin-in?style=brands](url)

### Chrome version
70.0.3538.77 (Official Build) (64-bit)

### Edge version
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

### Opera version
Stable 56.0.3051.52

### Firefox version
63.0.1 (64-bit)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate

![image](https://user-images.githubusercontent.com/556268/48064608-8bcd5a80-e1c8-11e8-9010-5a3a1823f997.png)


I suppose there is a third-party extension (ad-blocker) that is causing this issue.

Could you please retry in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode#w_how-to-start-firefox-in-safe-mode)?

**Comment by iftifar-taz** [comment]
ad-blocker as the culprit... works perfectly if i disable it.

**Comment by mattonit** [comment]
I have the same issue. I'm using Chrome with AdBlock Plus. When ABP is running, the "linkedin-in" icon is being disabled. Ok, it's fine to disable AdBlock for my website, but how I'm supposed to tell my customers not to use AdBlock?

**Comment by pglejzer** [comment]
I have the same problem with 'fab fa-buysellads'. When I'm using AdBlock Plus, this icon is disappearing! I can't even search for this icon. Is it possible to fix this in a different way?

**Comment by tagliala** [comment]
Hi,

sorry about your troubles.

adblock related issues are covered in #1799, please take a look at the discussions and the workaround there

> Ok, it's fine to disable AdBlock for my website, but how I'm supposed to tell my customers not to use AdBlock?

This is your customers' choice, you should not tell them to avoid AdBlock.

If you think that Font Awesome's LinkedIn icon is not a privacy concern or an Ad, please try to get in touch with adblock and ask them to whitelist font awesome's icon

> I have the same problem with 'fab fa-buysellads'. When I'm using AdBlock Plus, this icon is disappearing! I can't even search for this icon. Is it possible to fix this in a different way?

If you are using the CSS framework, alias `fa-buysellads` to something else. That would be more complicated with the SVG framework.

Locking here, let's use #1799
