### ISSUE TITLE
Icon request: flash-off / flash-auto

### ISSUE THREAD

**Issue by partulaj** [FortAwesome/Font-Awesome#14230]
### What can it be used for?

Used to indicate the state of the flash.

### Example image (optional)

![baseline_flash_off_black_18dp](https://user-images.githubusercontent.com/6641273/48075163-df4ca200-e1e2-11e8-8da3-eebca97e7110.png)
![baseline_flash_auto_black_18dp](https://user-images.githubusercontent.com/6641273/48075164-df4ca200-e1e2-11e8-9702-5b315cfb5f4e.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @partulaj,

[fa-bolt-slash](https://fontawesome.com/icons/bolt-slash) and [fa-bolt-auto](https://fontawesome.com/icons/bolt-auto) icons have been added in v6.0.0.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
**in a web application** it is possible to create the requested icons in FA Free by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/99/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer
