### ISSUE TITLE
Can Font-Awesome be installed on our company's CDN in Azure?

### ISSUE THREAD

**Issue by zBestData** [FortAwesome/Font-Awesome#14237]
Can Font-Awesome be installed on our company's CDN in Azure?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@zBestData just for clarity, are you referring to Font Awesome Free or Font Awesome Pro?

**Comment by zBestData** [comment]
I have FontAwesome Pro.  Would like to service it from our Azure Blob Storage, and am guessing we would need change the references them using the full url since the blob's folders are virtual.

**Comment by tagliala** [comment]
Got it.

Could you please open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

I will then mention the right person to answer
