### ISSUE TITLE
Icon request: mouse (animal)

### ISSUE THREAD

**Issue by Crissov** [FortAwesome/Font-Awesome#14246]
In order to fully support all local variants of Asian zodiac signs #5927, a Mouse would be necessary.

🐭 U+1442D
🐁 U+1F401
#222

**Comment by yeou** [comment]
Or a rat icon would be good.

**Comment by jconcilio** [comment]
I'd like to upvote this and suggest another use case (the one that sent me looking for it): Laboratory animal medicine. I'm working on some information for researchers in small-mammal labs and could really have used a non-computer mouse!

**Comment by aethior** [comment]
Hi @Crissov,

This icon was added in v6.1.2.
Check https://fontawesome.com/icons/mouse-field

Regards.

cc/ @tagliala
