### ISSUE TITLE
Simple Updation !

### ISSUE THREAD

**Issue by zaahiir** [FortAwesome/Font-Awesome#14242]
Hi Fontawesome Team,

 I have small suugesstion with our CSS. In our CSS contains **fa-spin** and **fa-pulse** but that two classes with same animation. So kindly change the keyframes and class for fa-pulse to 

.fa-pulse {
  -webkit-animation: fa-pulse 1s infinite linear;
          animation: fa-pulse 1s infinite linear;
}

@keyframes fa-pulse {
 0% {
    -webkit-transform: scale(0);
            transform: scale(0); }
  50% {
    -webkit-transform: scale(1);
            transform: scale(1); }
  100% {
    -webkit-transform: scale(0);
            transform: scale(0); } }
Thanking You!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`spin` and `pulse` don't provide the same animation http://jsfiddle.net/tagliala/rodg718s/5/ and they are just two common ways of show loading status.

We will consider this if there will be new releases focused on animations. Meanwhile, feel free to implement whatever animation you like in your stylesheets.

Closing here
