### ISSUE TITLE
Change request: improve safari icon

### ISSUE THREAD

**Issue by pacho2** [FortAwesome/Font-Awesome#14240]
It's hard to see the white arrows in fa-safari icon with this size, if you don't pay attention, it looks like completely black. Maybe it would be interesting to make the arrows a bit bigger

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I agree with your point, let's leave this open as enhanchement

Anyway, I've found another safari icon

![image](https://user-images.githubusercontent.com/556268/48231246-c0e6d200-e3ad-11e8-9f65-08a0461b3db0.png)

(ref: https://support.apple.com/safari)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/safari?style=brands
