### ISSUE TITLE
Icon request: research gate

### ISSUE THREAD

**Issue by webernick79** [FortAwesome/Font-Awesome#14256]

**Comment by webernick79** [comment]
Would be awesome to have a research gate icon: https://www.researchgate.net

Thanks a ton!! you guys are F'ing Awesome!!!!

**Comment by tagliala** [comment]
Here it is: https://fontawesome.com/icons/researchgate?style=brands

Please make sure that you are using Font Awesome >= 5.0.11

**Comment by Krisselack** [comment]
I am using this icon with 5.2.0, but it is not displayed correctly. The embedding comes from a theme: https://github.com/ParitoshBh/grav-coder/blob/master/css/fontawesome.min.css

![image](https://user-images.githubusercontent.com/15987388/48678704-1e85d600-eb87-11e8-8e48-7d5d2aa879bc.png)

**Comment by tagliala** [comment]
@Krisselack sorry, we do not provide support for third party plugins or themes. Please contact your plugin's author
