### ISSUE TITLE
icon Request: icon users-tie

### ISSUE THREAD

**Issue by Lakshmanarao121777** [FortAwesome/Font-Awesome#14261]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fix this request by filling out our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by tagliala** [comment]
duplicate of #9418
