### ISSUE TITLE
Upgrade from 4.6.3 to latest

### ISSUE THREAD

**Issue by cralfaro** [FortAwesome/Font-Awesome#14263]
I am font awesome version 4.6.3 and i would like to upgrade to the latest version, but i am checking that some classes on 4.6.3 are not valid on the latest version of FA, so if i try to upgrade i need to check the entire site and replace the old icons with the new classes or most similar, am i doing something wrong or is not possible to upgrade from 4.6.3??

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can use the upgrade shims available at https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims

Hope it helps

Closing here
