### ISSUE TITLE
401 Error when deploying with Heroku

### ISSUE THREAD

**Issue by 13MS** [FortAwesome/Font-Awesome#14277]
I have been using Font Awesome Pro on a Node project for a few months without any problem but when trying to push a new version to Heroku, the app will not build because of the following error:
```
Building dependencies        
remote:        Installing node modules (package.json + package-lock)        
remote:        npm ERR! code E401        
remote:        npm ERR! 401 Unauthorized: @fortawesome/fontawesome-common-types@0.1.7
```

I have a .npmrc file at the root of the project and updated the code there to the new preferred language (after the first 401 error).
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=MY_TOKEN
```

I tried pushing again but with the same result. 

Is there something I'm missing? I'm using a mix of pro and brand icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
