### ISSUE TITLE
Icon request: scale-line

### ISSUE THREAD

**Issue by suzannehillman** [FortAwesome/Font-Awesome#14274]
**What can it be used for?**

In places where something might need rescaling - floorplans, maps, etc.

**Example image (optional)**

![image](https://user-images.githubusercontent.com/18105933/48498487-5e099680-e804-11e8-9128-2cdf05aa7501.png)

**Icon request checklist**

- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @suzannehillman,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/arrows-left-right-to-line

Regards.

cc/ @tagliala
