### ISSUE TITLE
Word 2016 with fontawesome-free-5.5.0-web

### ISSUE THREAD

**Issue by HenriApperloo** [FortAwesome/Font-Awesome#14278]
### Describe the problem

We install the fa-regular-400.ttf 
[test Font-Awesome5.docx](https://github.com/FortAwesome/Font-Awesome/files/2584448/test.Font-Awesome5.docx)
font. When I use this font in Word then 
all letter over each other.

### What did you expect?

we expect that we can use the font normal. With text and symbolic

### What version and implementation are you using?

Version: fontawesome-free-5.5.0-web
Browser and version: Word 2016 MSO (16.0.9123.2295) 32 bits

- [X ] On the Desktop

### Reproducible test case
see attachment

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please try with the `.otf` font file because it is designed to work on desktop

**Comment by HenriApperloo** [comment]
Hi,

Thanks for the quick response.

I have download the .otf from https://github.com/FortAwesome/Font-Awesome/tree/master/use-on-desktop

And it works fine! Thanks
