### ISSUE TITLE
fa-comment disappear 

### ISSUE THREAD

**Issue by maxguzenski** [FortAwesome/Font-Awesome#14270]
fa-comment is not working: 
https://fontawesome.com/icons?d=gallery&q=comment

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate

Could you please provide more information on your browser / OS?

**Comment by maxguzenski** [comment]
That is true. 
On Firefox it is working, on Chrome 70.0.3538.77 on macOS dosen't.

**Comment by maxguzenski** [comment]
<img width="803" alt="fontawesome" src="https://user-images.githubusercontent.com/6819/48434970-5e515580-e762-11e8-9dcb-ffc7bab0c84d.png">

**Comment by maxguzenski** [comment]
Element without ::before css selector...

<img width="484" alt="font2" src="https://user-images.githubusercontent.com/6819/48435178-fd764d00-e762-11e8-9d31-d68db9cdccb9.png">

**Comment by maxguzenski** [comment]
But this issue is NOT only on fontawesome website, it is on my app as well (webpack 4, react, @fortawesome/react-fontawesome LAST)

**Comment by tagliala** [comment]
@maxguzenski could you please

macOS 10.14.1 / Chrome 70.0.3538.77 

![image](https://user-images.githubusercontent.com/556268/48472361-68249880-e7f6-11e8-85f0-50be6468311d.png)

and Chrome 70.0.3538.102

![image](https://user-images.githubusercontent.com/556268/48472443-973b0a00-e7f6-11e8-8f95-c3d1eff9fb0e.png)



1. Check your development console
2. Load Chrome without third party extensions

**Comment by maxguzenski** [comment]
Sorry, my fault 
I forgot that I use a chrome extension called "Shut out", that remove no constructive comments on youtube and news sites. It looks like that last version start to remove comment icon from fontawesome as well.

**Comment by tagliala** [comment]
@maxguzenski thanks for the heads-up

If you will report this to the extension's author let us know
