### ISSUE TITLE
css content: "\f468"; doesnt work for some

### ISSUE THREAD

**Issue by ohabash** [FortAwesome/Font-Awesome#14276]
I am using the following method to display icons

`  &:before {
    font-family: Fontawesome;
    content: "\f468";
  }`

that works for about 30% of the icons. For example I tried the above, `f468` and that did not work but when i did `<i class="fas fa-boxes"></i>` the icon displayed. Can you see the problem?

Im using https://use.fontawesome.com/releases/v5.5.0/css/all.css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look here:

https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here
