### ISSUE TITLE
IE11 Syntax Error 5022 on querySelectorAll

### ISSUE THREAD

**Issue by BrotherErryn** [FortAwesome/Font-Awesome#14283]
It's trying to parse this selector when we see the error:

`.fa-layers-text:not([data-fa-i2svg]), .far:not([data-fa-i2svg]), .fal:not([data-fa-i2svg]), .fas:not([data-fa-i2svg]), .fa:not([data-fa-i2svg]), .fab:not([data-fa-i2svg])`

IE11 (Edge mode, using JS/SVG version of library) seems to really not like that selector.

**Comment by robmadole** [comment]
@BrotherErryn can you provide a reproducible example? I have tried here and was not able to reproduce it. https://codepen.io/robmadole/pen/REOBZp

**Comment by BrotherErryn** [comment]
It was back in November, using FA 5.3.1. Can't seem to reproduce it now.
