### ISSUE TITLE
Icon request: icon-Nauseated-Face

### ISSUE THREAD

**Issue by mirvlaa** [FortAwesome/Font-Awesome#14289]
It can be use for cases when you need to show bad condition of something (like poo but not so ugly). There emoji analogue  🤢 🤮

**Comment by Crissov** [comment]
Unicode emoji #222:

- [🤢](http://emojipedia.org/nauseated-face) U+1F922 Nauseated Face
- [🤮](http://emojipedia.org/face-with-open-mouth-vomiting) U+1F92E Face with Open Mouth Vomiting

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/face-nauseated?s=solid
https://fontawesome.com/v6.0/icons/face-vomit?s=solid
