### ISSUE TITLE
What is a blender-phone?

### ISSUE THREAD

**Issue by brightertools** [FortAwesome/Font-Awesome#14288]
What is this? is it a brand icon?

https://fontawesome.com/icons/blender-phone?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Seems legit 😅 

`blender-phone` is not a brand

@talbs is that a http://hackedgadgets.com/wp-content/blender_phone.jpg ?

**Comment by tagliala** [comment]
@brightertools Sorry. I don't know, I hope that someone else in the team could answer your question.

Anyway, I'm pretty sure that no one asked for the [poo-storm](https://fontawesome.com/icons/poo-storm?style=solid) icon, which is actually the best icon of all times IMHO 😁

**Comment by brightertools** [comment]
@tagliala haha, I have a small child and I can certainly relate to that one 🤘

**Comment by robmadole** [comment]
@brightertools @tagliala that was a sponsored icon which was part of our v5 Kickstarter.

**Comment by tagliala** [comment]
Thanks for the clarification

**Comment by slattkd** [comment]
So... no real answer here?

**Comment by tagliala** [comment]
@slattkd 

Rob provided an answer here: https://github.com/FortAwesome/Font-Awesome/issues/14288#issuecomment-454941522

> that was a sponsored icon which was part of our v5 Kickstarter.

More info on sponsored icons (search for commissioned icons): https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by slattkd** [comment]
Oh, sorry, thought that was in regards to the poo-storm icon.

**Comment by joemastersemison** [comment]
I sponsored it because I use it as a symbol for tech-for-tech's sake. A blender phone is something that was made because it seemed unique or cool as opposed to being useful. It's been helpful to have as an icon for presentations and apps I have made.

**Comment by robmadole** [comment]
@joemastersemison I'm glad we used it correctly on fontawesome.com.

<img width="2632" height="1124" alt="Image" src="https://github.com/user-attachments/assets/2223e388-4563-4b48-80df-cfcbeb3d03e2" />
