### ISSUE TITLE
Icon request: Unisex or male/female

### ISSUE THREAD

**Issue by MeanGreen11** [FortAwesome/Font-Awesome#14281]
I propose to add a unisex or combined male/female icon. It can be based on the existing male and female icons, combining two halves into a single new icon.

**What can it be used for?**
It's very useful in cases when indicating something unisex where the specific gender is not relevant.

**Example image**
![image](https://user-images.githubusercontent.com/26787397/48615916-73acc680-e992-11e8-9f2a-78e0330be849.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can achieve this icon by using masking and layering features of the SVG framework

https://jsfiddle.net/tagliala/wks0e6pa/7/

Docs:
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
- https://fontawesome.com/how-to-use/on-the-web/styling/masking

Related: #2670

**Comment by aethior** [comment]
Hi @MeanGreen11,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/person-half-dress

Regards.

cc/ @tagliala
