### ISSUE TITLE
Yarn install throws 401 Unathorized

### ISSUE THREAD

**Issue by simPod** [FortAwesome/Font-Awesome#14282]
This is thrown on CI when running `yarn install`

error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.2.8.tgz: Request failed \"401 Unauthorized\"".

I though that would be issue with `.npmrc` but that package should be free so no need for pro token?

However, for sake I tried to set all forms of `.npmrc`

```
@fortawesome:registry=https://npm.fontawesome.com/xxxxx-xxxx-xxx-xxx
```

and also

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=xxxxx-xxx-xx-x
```

What am I doing wrong?

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by robmadole** [comment]
@simPod send us an email to hello@fontawesome.com since this is security related...we'll get some info from you and get it figured out

**Comment by simPod** [comment]
Nobody answered the email... I don't remember what this was about anyway. Closing

**Comment by tagliala** [comment]
@simPod sorry for the missing response

Closing here

**Comment by muhaimincs** [comment]
what is the solution here? I just want to use to deploy strapi on heroku server

**Comment by robmadole** [comment]
@muhaimincs please send an email to hello@fontawesome.com. We aren't going to keep security-related conversations in GitHub issues.

**Comment by simPod** [comment]
Will he get a reply? I sent one on Nov 11 2018 but so far there was none.

**Comment by simPod** [comment]
Don't remember how or whether I solved this :/ Can't be of help @muhaimincs
