### ISSUE TITLE
Homepage: Invalid FontAwesome v4 link

### ISSUE THREAD

**Issue by maxis1718** [FortAwesome/Font-Awesome#14293]
### Describe the problem

404 for "Version 4 Files + Docs": https://origin.fontawesome.com/v4.7.0 

### What did you expect?

Should redirect to https://fontawesome.com/v4.7.0/

### What version and implementation are you using?

N/A, it's on FA homepage.

### Reproducible test case

1. Go to https://origin.fontawesome.com/
2. scroll all the way down 👇 

   ![image](https://user-images.githubusercontent.com/1659204/48667427-28b8bd80-eb10-11e8-923a-ae81800313fd.png)

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by talbs** [comment]
Hi, @maxis1718. Thanks for writing in. https://fontawesome.com is our official homepage, and https://fontawesome.com/v4.7.0 is the official documentation for version 4 of Font Awesome. All links should work when using those site ( If not, let us know with additional issues). Please use those URLs and don't rely on https://origin.fontawesome.com.
