### ISSUE TITLE
Some of icons not showing

### ISSUE THREAD

**Issue by OmidID** [FortAwesome/Font-Awesome#14309]
I have problem with some icons as you can see in attachment image.
CSS and Font file are perfect. I try with CDN url and downloaded font and result is same
I using version 5.5.0
![image](https://user-images.githubusercontent.com/956077/48904149-2767f780-ee66-11e8-8cce-c0ef9dc4942e.png)

**Comment by tiesont** [comment]
Works for me. To ask a stupid question, did you recently update? If so, you may need a hard-refresh for your browser to load the correct font file. Also, this looks like Firefox - does the same thing happen in other browsers?

**Comment by OmidID** [comment]
@tiesont thanks for reply. I had clean the cache fully and also different browsers! unfortunately same.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the `.countup-block i` rule is overriding FA's `font-weight` property.

![image](https://user-images.githubusercontent.com/556268/49003346-06ebb600-f162-11e8-88bd-8c4da33fc945.png)

Please fix that

Hope it helps

Closing here
