### ISSUE TITLE
Icon request: popsicle

### ISSUE THREAD

**Issue by zzzFelix** [FortAwesome/Font-Awesome#14308]
### What can it be used for?
Could be used to represent summer, ice cream, happiness :)

### Example image
https://www.w3schools.com/icons/tryit.asp?filename=trybs_ref_glyph_ice-lolly-tasted

**Comment by Crissov** [comment]
also see #1988

**Comment by sensibleworld** [comment]
This is now in version 6! https://fontawesome.com/v6.0/icons?q=popsicle
