### ISSUE TITLE
Bug: Icon fa-file-csv not working

### ISSUE THREAD

**Issue by Lanundso** [FortAwesome/Font-Awesome#14317]
Above referred is not working properly.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[file-csv](https://fontawesome.com/icons/file-csv?style=solid) has been introduced in Font Awesome 5.4.0. Please make sure that you are using FA >= 5.4.0. Note that third-party plugins/themes you are using may load an older version of font awesome

If you still think there is an issue with Font Awesome, please open a new request making sure that it follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

Closing here
