### ISSUE TITLE
Icon request: school curriculum subject set

### ISSUE THREAD

**Issue by redfoxhub** [FortAwesome/Font-Awesome#14319]
### What can it be used for?

School/college/university/third party web services for subject specific content (English, Maths, History, Physics etc). 

### Example image (optional)

No sample images, some existing icons would be suitable (fa-globe, fa-swimmer, fa-atom, fa-flask etc), but more are needed.

The following icons would cover most U.K. state schools: Art & Design, Applied Science, Biology, Business Studies, Chemistry, Childcare, Classical Civilisation, Computing, Dance, Drama, Electronics, English Language, English Literature, Food, French, Geography, German, Health & Social Care, History (Early), History (Modern), ICT, Latin, Mathematics, Mathematics (Applied), Mathematics (Pure), Media Studies, Music, Music Technology, Photography, Psychology, Physical Education, Physics, Politics, Religious Studies, Resistant Materials, Spanish, Statistics, Sociology, Textiles, Theatre Studies

### Icon request checklist

Apologies for requesting as set, rather a single icon, I was hoping to avoid creating 40 odd requests.

To the best of my knowledge this is not a duplicate request. Issue #2789 is in a similar area, but does not mention curriculum subjects.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Apologies for requesting as set, rather a single icon, I was hoping to avoid creating 40 odd requests.

Sorry, I understand your point but I cannot allow this request on the free repo. Icon sets are hard to manage. I have to ask you to open individual requests with single color examples.

Please note that if "icon-subject-music" is something like https://jsfiddle.net/tagliala/wks0e6pa/11/ or https://jsfiddle.net/tagliala/wks0e6pa/13/ you could consider the stacking feature

If you are a Pro backer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
