### ISSUE TITLE
Layering not working

### ISSUE THREAD

**Issue by Toyguns** [FortAwesome/Font-Awesome#14313]
### Describe the problem
Layering is not working for me
On this page you have an examples of layering.
https://fontawesome.com/how-to-use/on-the-web/styling/layering

I took the same code and put it on my page
https://test.lpc411.com/test2.php

it comes out side by side not stacked

### What did you expect?

im trying to get a message count with the envelope and a number to stack from the example below.
![2018-11-23_0-02-39b](https://user-images.githubusercontent.com/32375730/48929083-388b2580-eeb3-11e8-8e86-23d5b47f55ee.jpg)

### What version and implementation are you using?
I have a pro lic 
Version: v5.4.2
Browser and version: I tried IE and chrome
- [x] Web Fonts with CSS

### Reproducible test case

https://test.lpc411.com/test2.php
once you are on the page you can get the source  code but it is the same code you have on your page + the link for Fa fa awesome in the head 
![2018-11-22_23-59-07](https://user-images.githubusercontent.com/32375730/48929053-04176980-eeb3-11e8-8aa6-3afec6dac396.jpg)

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
Some of the stuff I found is from back in 2013 not helpful

**Comment by InsanityMeetsHH** [comment]
> ### Describe the problem
> Layering is not working for me
> On this page you have an examples of layering.
> https://fontawesome.com/how-to-use/on-the-web/styling/layering

At the top of the page stands.

> Heads Up!
> This feature requires that you use our SVG + JS version of Font Awesome.

So you have to use the JS file of Font Awesome (https://use.fontawesome.com/releases/v5.5.0/js/all.js for example).

**Comment by tagliala** [comment]
@InsanityMeetsHH thanks! ❤️ 

@Toyguns by the way, the css framework provides a simpler stacking feature documented here: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons

If you need the power of layering and masking and your use case allows that, you should consider to switch to the svg framework

Hope it helps

Closing here

**Comment by Toyguns** [comment]
Ok thanks for the help I didn't know the difference but if you go to
https://fontawesome.com/start
and change webfont to SVG it will work!
![2018-11-23_12-16-06](https://user-images.githubusercontent.com/32375730/48954963-a66a3800-ef19-11e8-8e85-feb970ed1535.jpg)
