### ISSUE TITLE
Add sync-alt to the spinners pack

### ISSUE THREAD

**Issue by dflock** [FortAwesome/Font-Awesome#14312]
They make excellent spinners and would be a good fit.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I already see `sync` in the spinners category: https://fontawesome.com/icons?d=gallery&c=spinners&m=free

Good catch on `sync-alt`, will do that

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @dflock. We just added that icon and a few more we thought would make good/fun material to spin in. They'll go out in our next release shortly. Here's a preview of what will be in the Spinners category...

![49052666-d421dc00-f1ba-11e8-854e-37c633f46879](https://user-images.githubusercontent.com/163763/49158468-3af4e180-f2f0-11e8-8d6e-3ec8b6de359b.png)

**Comment by talbs** [comment]
Alrighty, @dflock. We released 5.6.0 today, including a bunch of additions to the "Spinners" category - https://fontawesome.com/icons?d=gallery&c=spinners. Thanks for the great feedback and please keep it coming. 😄
