### ISSUE TITLE
Icon request: Thai Baht currency symbol

### ISSUE THREAD

**Issue by Phuvadol** [FortAwesome/Font-Awesome#1431]
Greetings, 

Could you please create a Thai Baht icon.  
![big-thai-currency-symbol-baht](https://f.cloud.github.com/assets/956439/714872/06ad9880-df0b-11e2-8849-614f8bac3e37.png)

(btw, very similar to the bitcoin icon :) )

Thank you much!

**Comment by kytwb** [comment]
+1

**Comment by bradonomics** [comment]
+1

**Comment by cloverink** [comment]
follow up :)

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
