### ISSUE TITLE
Icon request: citra-emu

### ISSUE THREAD

**Issue by stampylongr** [FortAwesome/Font-Awesome#14320]
### What can it be used for?
This icon could be used for linking to Homebrew software compatible with Citra (the emulator).

### Example image (optional)
![citra-emu](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Citra_Logo.svg/500px-Citra_Logo.svg.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by stampylongr** [comment]
@tagliala Has anyone been working on this? It's almost been a year.

**Comment by tagliala** [comment]
Hi @stampylongr , please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work

You can also take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome if you are interested in how to customize Font Awesome to add this icon

**Comment by stampylongr** [comment]
Closing this, as no progress has been made within the last three years.
