### ISSUE TITLE
Icon Request: Business Card

### ISSUE THREAD

**Issue by taralynnpeters** [FortAwesome/Font-Awesome#14324]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do https://fontawesome.com/icons/address-card?style=solid or https://fontawesome.com/icons/id-card?style=solid fit your needs?

If they don't, please make sure that your request matches our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example of the icon you need

**Comment by mengzy2018** [comment]
#14325
