### ISSUE TITLE
Generate a JS file with required icons only 

### ISSUE THREAD

**Issue by NolanCrochot** [FortAwesome/Font-Awesome#14329]
Hi,

I'm aware that we can import SVG individually as mentionned in this [documentation ](https://fontawesome.com/how-to-use/on-the-web/other-topics/performance ) in order to reduce the total weight of embed icons. 

However, the advantage of the JS version of FontAwesome is the capability to use the "fa" class on "i" tag to quickly generate an entiere SVG (and a "simpliest way" to use CSS properties by the way, with icons behaving like fonts). If we choose to download SVG one by one and import them individually, we must get by without this feature. 

I wonder if it currently exists (or if it's envisaged) to enable the user to select several icons he needs among the whole set of icons (in the main website of FontAwesome), then compile them in a JS script, like the existing [all.min.js](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself), but which only imports thoses choosen icons. A kind of custom.min.js 

Currently the weight of the FA JS file (all.min.js) is in the order of **1 Mo**, which is a bit heavy for a JS file. Even more when we need only a set of 15/20 icons among all of those available (1409). I presume this idea will help to reduce significantly the weight of the library by avoiding thousands lines of unused SVG strings. 

Or maybe you've a better alternative to suggest me ? 

Thank you in advance,

N.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I wonder if it currently exists (or if it's envisaged) to enable the user to select several icons he needs among the whole set of icons (in the main website of FontAwesome), then compile them in a JS script, like the existing all.min.js, but which only imports thoses choosen icons. A kind of custom.min.js

Yes, it does exist. It is based on the tree-shaking functionality of webpack. You can read more here: https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

Hope it helps

Closing here

**Comment by NolanCrochot** [comment]
Finally can't manage to use this way... 

I'm not really comfortable with webpack. 
I managed to compile a bundle importing the example (fa-coffee) but nothing happened in the result.
(And he seemed to import the whole FA script) 

Can you please add more details to the TreeShaking section ? 
I'm pretty sure we need to import something else that only the icon to make it works (_how can he knows we should use the fontawesome treatment functions to convert i tag as SVG for example ?_)

My initial question/suggestion was to manage it an easier way (directly from the website for example),  as it's actually possible to generate a font file in Fontello's website. This current way shouldn't be a solution for a classic user (not a great developer) who do not daily use Webpack. :(

**Comment by tagliala** [comment]
Hi @NolanCrochot, sorry for the late reply

You can manually edit the source javascript: https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting#subset

https://github.com/FortAwesome/Font-Awesome/blob/master/svg-with-js/js/fa-solid.js#L118

Would that work for you?

**Comment by NolanCrochot** [comment]
Hi,

Unfortunately not... 

Using this code imports the whole brands and solid SVG icons in my bundle.js : 

```
import { library } from '@fortawesome/fontawesome-svg-core'
import { faStroopwafel } from '@fortawesome/free-solid-svg-icons'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'

library.add(faStroopwafel, faTwitter)
```

But, I think I didn't really get the utility of tree shacking from the start. 
If I well understood, those kind of subsets are used in order to call some SVG icons in a React / Rollup application, or other technologies that support tree shacking. 

>  This process is known as tree shaking. Rollup and Webpack 2+ are a couple of tools that support tree shaking

What I was trying to do is a sort of "tiny and independent" js FA library with just a dozen of brand icons. 
So I could use it after that in an external "classic" (no-react based) website. So I think isn't really possible. I'm sorry for the misunderstanding...
