### ISSUE TITLE
Icon request for messenger instant message app

### ISSUE THREAD

**Issue by lehnerv** [FortAwesome/Font-Awesome#14330]
Hello i would like to insert Facebook messenger link like this: m.me/UjbudaIngatlan may website, would be very useful to others i guess. Regrds

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think you are requesting an icon for Facebook Manager, which is already in the set: https://fontawesome.com/icons/facebook-messenger?style=brands

Please make sure that you are using Font Awesome >= 5.0.0

Ref:
- https://fontawesome.com/
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

closing here
