### ISSUE TITLE
Many icons do not show up (Linux desktop)

### ISSUE THREAD

**Issue by Baggykiin** [FortAwesome/Font-Awesome#14346]
### Describe the problem

Many FontAwesome glyphs do not render at all on Linux. Only a small subset of them can be correctly displayed.

![image](https://user-images.githubusercontent.com/1516985/49394830-2a4fcb80-f735-11e8-8b8d-16ba02315e06.png)

### What did you expect?

All icons should display properly.

### What version and implementation are you using?

Version: 5.5.0

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [X] On the Desktop

### Reproducible test case

- Install `gucharmap` for your distribution, if it's not yet installed.
- Download the 5.5.0 desktop release: https://use.fontawesome.com/releases/v5.5.0/fontawesome-free-5.5.0-desktop.zip
- Extract the ZIP file.
- Copy the OTF files to `~/.local/share/fonts`
- Update the font cache by running `fc-cache` in a terminal
- Start `gucharmap`
- In the font chooser at the top left, enter `Font Awesome 5 Free`
- Press Ctrl-F, enter `F000`, press Enter, and close the window.
- All Font Awesome icons should now be visible.
- Select `View` -> `Show only glyphs from this font`. Most of the icons will now disappear.

This seems to affect several applications, the above test case with `gucharmap` is the easiest way to trigger it. Interestingly, the `Font Awesome 5 Brands` font appears to be unaffected by this bug.

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for this detailed bug report.

I'm not able to check this in linux, but I can see that you have selected Solid font style, but gucharmap is showing the regular font style, otherwisse you would have seen a filled-in heart ♥ instead of an empty one ♡.

**Comment by Baggykiin** [comment]
You're right, I had to set the font style to bold to make the solid characters appear, otherwise it will only show those glyphs that have an outline version available, which I guess is only a small subset of them because I'm using the free font. Thanks for your help!

**Comment by tagliala** [comment]
> which I guess is only a small subset of them because I'm using the free font. 

That is correct

So is this issue fixed?

**Comment by Baggykiin** [comment]
Yes it is, I'll close it.

**Comment by tagliala** [comment]
Thanks

**Comment by airtonix** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community and for this detailed bug report.
> 
> I'm not able to check this in linux, but I can see that you have selected Solid font style, but gucharmap is showing the regular font style, otherwisse you would have seen a filled-in heart hearts instead of an empty one ♡.

It's pretty easy imo....

- install virtual machine software
- boot up with live iso of reported linux distro.
- ????
- profit
