### ISSUE TITLE
Not working on my requested icon

### ISSUE THREAD

**Issue by AtomHydra7** [FortAwesome/Font-Awesome#14353]
I posted a Gameloft icon on Font Awesome,
but they are not working on it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome receives dozens of new requests every day. Some of them will eventually be included, others will not. [Popularity](https://fontawesome.com/community/leaderboard/new) is one of the factors taken into account, but it is not the only one.

Please check our [Leaderboard](https://fontawesome.com/community/leaderboard/brands) to take a look at the most requested brands

I hope that this clarifies how icon requests work

Closing here

**Comment by AtomHydra7** [comment]
why?
