### ISSUE TITLE
Icon request: business-model-canvas

### ISSUE THREAD

**Issue by BroosB** [FortAwesome/Font-Awesome#14355]
### What can it be used for?

To represent the business model canvas in dashboards, business plans, apps, etc. The business model canvas is a globally used visual model to describe for whom and how an organization creates and captures value. For more information please see: https://youtu.be/QoAOzMTLP5s or https://en.wikipedia.org/wiki/Business_Model_Canvas. It is developed by Alex Osterwalder and Yves Pigneur

### Example image (optional)

![image](https://user-images.githubusercontent.com/25501633/49447691-75bab600-f7d7-11e8-84e9-7217a47571f3.png) 
or 
![image](https://user-images.githubusercontent.com/25501633/49447704-823f0e80-f7d7-11e8-97cd-1a4f1ddebce0.png)

Please note that this icon is missing the middle bar in the lower rectangle (the BMC has 9 blocks, this one has 8).

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @BroosB,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/diagram-lean-canvas

Regards.

cc/ @tagliala

**Comment by BroosB** [comment]
Hi @aethior,

Thanks for letting me know! Really happy the icon has been added 🙌

Broos
