### ISSUE TITLE
Icons now showing in iOS 12

### ISSUE THREAD

**Issue by moonshark** [FortAwesome/Font-Awesome#14354]
Hi

The icons are showing in iOS 11, but on iOS12 they are not looking too great.

Any ideas?
![ios11](https://user-images.githubusercontent.com/6752993/49445560-1b672880-f7ca-11e8-9ac5-0a8c0a532951.jpg)
![ios12](https://user-images.githubusercontent.com/6752993/49445561-1b672880-f7ca-11e8-91d8-0472ee0c5250.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot confirm, icons are looking great here (iOS 12.1 / Safari)

Could you please make sure that your request follows our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide all the information required?

Could be this related to #7770 ?

![image](https://user-images.githubusercontent.com/556268/49476409-32356b80-f81a-11e8-99bf-6cbdc559035d.png)

Meanwhile, closing here
