### ISSUE TITLE
fa-scythe misnamed

### ISSUE THREAD

**Issue by nmsmith22389** [FortAwesome/Font-Awesome#14360]
### Describe the problem

The [fa-scythe](https://fontawesome.com/icons/scythe) icon is either incorrectly named or doesn't match it's icon. The icon actually depicts a sickle. The two items are visibly different

See:
[Description of a scythe.](https://en.wikipedia.org/wiki/Scythe)
[Description of a sickle.](https://en.wikipedia.org/wiki/Sickle)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this issue

@talbs could you please take a look?

**Comment by talbs** [comment]
@sensibleworld, what do you think? Looks like `fa-scythe` is closer to a `sickle`.

**Comment by sensibleworld** [comment]
@talbs Name change works for me.

**Comment by sensibleworld** [comment]
I think the best course of action would be to design a proper scythe icon, so that when we make the name change everything continues to work. This would go alongside renaming this particular icon to `fa-sickle`

**Comment by talbs** [comment]
> I think the best course of action would be to design a proper scythe icon, so that when we make the name change everything continues to work. This would go alongside renaming this particular icon to `fa-sickle`

@sensibleworld, sounds great to me. We'll tackle this issue in a future release when you've got a proper `scythe` icon handy. Thanks much!

**Comment by sensibleworld** [comment]
@nmsmith22389 Thanks again for the comment. We've updated the `fa-scythe` icon to be more accurate: 
https://fontawesome.com/icons/scythe?style=solid, and we've renamed the old icon to `fa-sickle`: 
https://fontawesome.com/icons/sickle?style=solid
