### ISSUE TITLE
The class of “arrow-up” may be wrong

### ISSUE THREAD

**Issue by mrgulc** [FortAwesome/Font-Awesome#14364]
```<i class="far fa-arrow-up"></i>```

should be

```<i class="fa fa-arrow-up"></i>```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

`far fa-arrow-up` is only available for Pro users

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
