### ISSUE TITLE
Icon request: chopsticks

### ISSUE THREAD

**Issue by Avalai** [FortAwesome/Font-Awesome#14365]
### What can it be used for?

Cultural icon, food-related indicators

### Example image (optional)

- Crossed ([Example](https://www.vectorstock.com/royalty-free-vector/chopsticks-element-isolated-icon-vector-16574315))
- Uncrossed ([Example](https://thenounproject.com/term/chopsticks/508941/))

Variation ideas:
- Resting on a holder ([Example](https://www.uncommongoods.com/images/items/21000/21064_1_640px.jpg))
- Holding noodles over a bowl ([Example](https://www.123rf.com/photo_38990591_stock-vector-bowl-of-noodles-with-a-pair-of-chopsticks-icon-thin-line-for-web-and-mobile-modern-minimalistic-flat.html))
- Holding a piece of sushi or other food ([Example](https://icons8.com/icon/3612/sushi))
- Sticking out of a bowl ([Example](https://www.colourbox.com/vector/set-of-bowl-of-rice-with-pair-of-chopsticks-icon-vector-14199885))

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is now in version6: https://fontawesome.com/v6.0/icons?q=chopsticks
