### ISSUE TITLE
FontAwesome Solid Not Showing in XD MacOS

### ISSUE THREAD

**Issue by SweetMuffins** [FortAwesome/Font-Awesome#14376]
### Describe the problem

FontAwesome Solid doesn't seem to be working in Adobe XD on MacOS. It seems to be working fine on Windows since I also have a Windows computer and I have installed it there as well and it works jut fine. 

### What did you expect?

I was expecting it would work just fine just like on Windows computer.

### What version and implementation are you using?

Version: 5.5.0
Browser and version: Chrome Version 71.0.3578.80 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ 5.5.0] On the Desktop

### Reproducible test case

N/A. Problem is within the Desktop Download fonts.

### Bug report checklist

- [Check ] I have filled out as much of the above information as I can
- [Check  ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ Check ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi, 

Could you please provide:
- Version of Adobe XD
- Version of macOS
- Screenshots of the wrong behaviour, including the font configuration

Then I would wait for feedback from the community, because I do not own Adobe XD

**Comment by SweetMuffins** [comment]
Hello, 

I have the Adobe XD Version 13.1.32.8

and MacOS Mojave 10.14.1.

Attached is the screenshot of the fonts list and how the icon looks like.
![screen shot 2018-12-10 at 8 58 31 am](https://user-images.githubusercontent.com/8256027/49737193-361e1f00-fc5a-11e8-97b2-50841b067fef.png)

**Comment by tagliala** [comment]
@SweetMuffins thanks.

Could you please provide a screenshot with the select dropbox collapsed and the icon you are trying to use?

**Comment by SweetMuffins** [comment]
This is the screenshot with the selected dropbox collapsed. I chose Font Awesome Free since Font Awesome Solid isn't showing up on XD.

![screen shot 2018-12-10 at 9 54 32 am](https://user-images.githubusercontent.com/8256027/49740275-daf02a80-fc61-11e8-9fe7-cee62c4eaba9.png)


And here's the screenshot of the icon I'm trying to use. 
![screen shot 2018-12-10 at 9 55 34 am](https://user-images.githubusercontent.com/8256027/49740305-ea6f7380-fc61-11e8-827c-29bb9d10f3e5.png)

**Comment by SweetMuffins** [comment]
Solved the issue. There is a dropdown below the font names list for the font weight. In the dropdown there's Regular and then there's Solid (see attached Screenshot). Sorry for the trouble. I just moved from a Windows computer to a Mac a few days ago. 

![screen shot 2018-12-10 at 2 51 38 pm](https://user-images.githubusercontent.com/8256027/49757744-266afe80-fc8b-11e8-94c1-f89877dba0b5.png)

**Comment by tagliala** [comment]
@SweetMuffins thanks, that's what I've thought but I wasn't 100% sure

Closing here
