### ISSUE TITLE
FontAwesome Solid Doesn't Work on Adobe XD in MacOS

### ISSUE THREAD

**Issue by SweetMuffins** [FortAwesome/Font-Awesome#14373]
Hello,

FontAwesome Solid doesn't seem to be working in Adobe XD on MacOS. I also have it on a Windows computer and it works just fine. I tried it on Photoshop, it works just fine too but when on XD, it doesn't even show on the fonts list. What's going on? Am I the only one having this issue? I've also already checked my Library>Fonts to see if it's really installed and it's obviously installed since it does work on PS. 

I have the latest XD btw.

Any help is greatly appreciated!

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out all the information required by our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

**Comment by SweetMuffins** [comment]
@tagliala, Just did!
