### ISSUE TITLE
Localhost Domain Input

### ISSUE THREAD

**Issue by NicMacRoy** [FortAwesome/Font-Awesome#14378]
I'm attempting to integrate our site to the Pro version instead of the basic free plan. Love the ease of use with the icons and some of the customization, very nice work and great job so far. Only issue I have is that I can't use this on my local setup, as I attempt to add my domain of localhost to the site I get the error saying I can't add a directory to domains. Is there a alternative to this issue?

**Comment by robmadole** [comment]
Hey @NicMacRoy send us a message to hello@fontawesome.com instead.
