### ISSUE TITLE
Error when deploy in server (user new version 5.6.0). The old version still works (5.5.0-2)

### ISSUE THREAD

**Issue by yugienter** [FortAwesome/Font-Awesome#14380]
![image](https://user-images.githubusercontent.com/7371616/49785837-63e78e80-fd54-11e8-921c-d5dec38cc743.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole could you please take a look at this? Could this be related to FortAwesome/Font-Awesome-Pro#1286 ?

I personally do not have issues with deploys on my demo application:
https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/package.json
https://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/yarn.lock

**Comment by mllustosa** [comment]
Hello guys and girls,

I'm also having a similar problem when trying to deploy the newest version.

![image](https://user-images.githubusercontent.com/3597619/49804035-d9059480-fd51-11e8-9875-84186c995d75.png)

**Comment by robmadole** [comment]
@yugienter I think this is related to #14382. I have the fix ready for this and will deploy in just a moment. You can test `5.6.1` and see if it resolves it. If it doesn't we'll need to get a reproducible test case from you to work on the fix.

**Comment by robmadole** [comment]
This should be all fixed up now with `5.6.1`. Let us know if you still have issues.
