### ISSUE TITLE
Fire icon changed on last update

### ISSUE THREAD

**Issue by maxguzenski** [FortAwesome/Font-Awesome#14391]
Hi,

I saw that fire icon totally change on last update (5.6). Can you please put it back as "fire-alt" or something like that ? 

https://fontawesome.com/icons/fire?style=light

**Comment by sensibleworld** [comment]
Yeah, we'll get this fixed in the next update. Sorry about that!

**Comment by alecpl** [comment]
I'd like to complain about the size of the fire icon. Imo, it's too small.

![fontawesome_fire](https://user-images.githubusercontent.com/546788/49994491-edcc6d00-ff89-11e8-9880-fbb52fa8dcc8.png)

**Comment by tagliala** [comment]
Oh, good catch. The icon doesn't seem to respect the grid. @sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
Yup. I'll get this tweaked in the next update.

**Comment by sensibleworld** [comment]
We've reverted to the original fire icon in 5.6.3 (https://fontawesome.com/icons/fire?style=solid) and added the new one as an `alt` (https://fontawesome.com/icons/fire-alt?style=solid).
