### ISSUE TITLE
"content" in CSS doesnt work in Font Awesome 5

### ISSUE THREAD

**Issue by Spartaa** [FortAwesome/Font-Awesome#14395]
.sidebar [data-toggle="collapse"]:before {
    content: "\f0d7";
    font-family: "Font Awesome 5 Free";
    font-weight: 900;
    position: absolute;
    right: 1rem;
}
I have tried everything but i dont know its only showing me a box
i am using it in Laravel Project with http://bootadmin.net
Can You Please Help me with that problem?
only icon from css with content  are not working.

**Comment by InsanityMeetsHH** [comment]
Did you read https://bootadmin.net/demo/docs?
If you have issues with bootadmin, then you have to go to there repo https://github.com/kjdion84/bootadmin.
If you see boxes instead of icons then is something wrong with `font-family` (or font files?).
https://codepen.io/anon/pen/gZaMbp

**Comment by tagliala** [comment]
@InsanityMeetsHH thanks, really appreciate

Hi @Spartaa

Thanks for being part of the Font Awesome Community.

We do not provide support for third party software, but if you provide a reproducible test case I will take a look

I'm going to close here but feel free to open a new issue or edit the first post following our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md), but please provide a reproducible test case we can debug

**Comment by Spartaa** [comment]
okay
