### ISSUE TITLE
Icon not loading properly: fa-fist-raised

### ISSUE THREAD

**Issue by ach206** [FortAwesome/Font-Awesome#14399]
Using on Squarespace. This is the only icon that is not displaying, the other 2 display as expected. I've tried both code snippets with no luck

``<center><i class="fa fa-fist-raised fa-2x"></i></center> ``
``<center><i class="fas fa-fist-raised fa-2x"></i></center> ``

![screen shot 2018-12-12 at 3 27 48 pm](https://user-images.githubusercontent.com/39183173/49905502-c9a24c00-fe22-11e8-85c2-eee5af9608b1.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that you are using Font Awesome version 4, I can tell from the appearance of `fa-bullhorn` and `fa-briefcase`.

This is how they look in FA5:
- https://fontawesome.com/icons/bullhorn?style=solid
- https://fontawesome.com/icons/briefcase?style=solid

`fa-fist-raised` has been introduced in FA 5.4, so please make sure that you are using at least that version.

I don't know how Squarespace works, but if you can't control your Font Awesome version, please contact your theme's author

Hope it helps

Closing here
