### ISSUE TITLE
Need Electronic health record (EHR) icon

### ISSUE THREAD

**Issue by me12b1037** [FortAwesome/Font-Awesome#14403]
Hi, we need new icon which will represent EHR(Electronic Health Record). 
Suggestion: https://www.google.com/search?rlz=1C1GCEU_enIN824IN824&biw=1920&bih=969&tbm=isch&sa=1&ei=qpATXNv2HsOv9QPa45bYAQ&q=ehr+icon&oq=ehr+icon&gs_l=img.3..0.113771.114323..114659...0.0..0.136.526.0j4......1....1..gws-wiz-img.......0i67j0i24.ENMbs8_Qh6s#imgrc=kunqojnup5LnNM:

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

IS EHR a brand?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by sensibleworld** [comment]
Hi there! We have a few icons that may work for this in our medical category: https://fontawesome.com/icons?d=gallery&s=solid&c=medical, but I might suggest this one in particular: https://fontawesome.com/icons/laptop-medical?style=solid
