### ISSUE TITLE
Icon request:  bottle

### ISSUE THREAD

**Issue by swapnilb0506** [FortAwesome/Font-Awesome#14401]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a https://fontawesome.com/icons/wine-bottle?style=solid, does it fit your use case?

Please check if https://github.com/FortAwesome/Font-Awesome/search?q=bottle&type=Issues contains the request with the icon you need and add a 👍 reaction to that request

If the bottle you need is unlisted, please provide a single color example

**Comment by aethior** [comment]
@tagliala I think you can close here.
