### ISSUE TITLE
Icon request: SMS

### ISSUE THREAD

**Issue by bamboorocket** [FortAwesome/Font-Awesome#1440]
Request for new icon, SMS, simple bubble with SMS

**Comment by demisx** [comment]
+1 Surprised it wasn't there.

**Comment by scottrouse** [comment]
+1

**Comment by dbsima** [comment]
+1

**Comment by otzy007** [comment]
:+1:

**Comment by vdemin** [comment]
+1

**Comment by charge-valtech** [comment]
+1

**Comment by arthurtalkgoal** [comment]
+1

**Comment by spiderr** [comment]
+4 (one for each thumb, and one for each big toe)

**Comment by RebeccaWeber** [comment]
+1

**Comment by fmaylinch** [comment]
+1  no one's using SMS nowadays I guess :wink:

**Comment by amirakbari** [comment]
+1

**Comment by laicosly** [comment]
+1

**Comment by RomanKoff** [comment]
+1

**Comment by bosk86** [comment]
+1

**Comment by mouradhamoud** [comment]
+1

**Comment by hariteritree** [comment]
+1

**Comment by misread** [comment]
+1

**Comment by reffer** [comment]
+1

**Comment by anawim** [comment]
+1

**Comment by ojkey** [comment]
+1

**Comment by ojkey** [comment]
+1

**Comment by sebbio** [comment]
+1

**Comment by MattAllmendinger** [comment]
+1

**Comment by chadbohannan** [comment]
+1

**Comment by mintuhouse** [comment]
+1

**Comment by hungnq1989** [comment]
:+1:

**Comment by eugene-rozov** [comment]
+1

**Comment by eeldwin** [comment]
+1

**Comment by pedubreuil** [comment]
+1

**Comment by ichuot** [comment]
:+1:

**Comment by ChezRD** [comment]
+1

**Comment by nabinca** [comment]
+1

**Comment by strihar** [comment]
+1

**Comment by finnmich** [comment]
+1

**Comment by supertassu** [comment]
+1

**Comment by finnmich** [comment]
Quick solution using stack: http://codepen.io/anon/pen/jWabaL

**Comment by callkeeper** [comment]
+1

**Comment by jonnywhite** [comment]
+1

**Comment by ElFoG** [comment]
+1

**Comment by nati22** [comment]
+1

**Comment by stevenejb** [comment]
+1

Strange..almost 3 years after opening this discussion, it still isn't implemented?

**Comment by shmaster** [comment]
+1

**Comment by bugbee** [comment]
+1

**Comment by pavgra** [comment]
+1

**Comment by BSLAdmin** [comment]
+1

However, on ios, the icon for SMS is basicaaly fa-comment stacked on top of a square.:

https://jsfiddle.net/mcyy2dmd/

**Comment by BSLAdmin** [comment]
+1

However on ios, the SMS icon is basically fa-comment with a green block background:

https://jsfiddle.net/mcyy2dmd/

**Comment by BSLAdmin** [comment]
+1

However on ios, the SMS icon is basically fa-comment with a green block background:

https://jsfiddle.net/mcyy2dmd/

**Comment by BSLAdmin** [comment]
+1

However on ios, the SMS icon is basically fa-comment with a green block background:

https://jsfiddle.net/mcyy2dmd/

**Comment by DutrowLLC** [comment]
+1

However on ios, the SMS icon is basically fa-comment with a green block background:

https://jsfiddle.net/mcyy2dmd/

**Comment by hdsnet** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by vvj5** [comment]
+1 (one that also says "TXT" would be snazzy as well)

**Comment by zigmoo** [comment]
+1

**Comment by isuvorov** [comment]
+1

**Comment by obsoleter** [comment]
+1

**Comment by SRautila** [comment]
+1

**Comment by elbartostrikesagain** [comment]
+1

**Comment by davidnguyen2205** [comment]
+1

**Comment by motowilliams** [comment]
Wonder if this issue would get more weight/metrics/priority if the +1s where converted to 'Add reaction'?

Just in case... 

+1

**Comment by cramae** [comment]
+1 - even though after all this time I don't believe it will help much.

**Comment by jsho32** [comment]
+1 - because i dont want this to die

**Comment by PortNumber53** [comment]
+1 because I need this and I work by his desk

**Comment by jjipson** [comment]
+1

**Comment by akiraspeirs** [comment]
+1

**Comment by paulgav** [comment]
+1

**Comment by juniorBR** [comment]
+1

**Comment by dupipi** [comment]
+1
very appreciated.

**Comment by gandriyko** [comment]
+1

**Comment by quakemaster** [comment]
+1

**Comment by brianyan** [comment]
+1

**Comment by saul-mtz** [comment]
+1

**Comment by andregomars** [comment]
+1 !!!

**Comment by ryscript** [comment]
Would be a good add for SMS icon

**Comment by facchiR** [comment]
+1

**Comment by atmarker** [comment]
Would have been super convenient today.
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1901028/28172200-8a29178e-67b0-11e7-9803-d5711cda7228.png">

**Comment by manuelsongokuh** [comment]
+1

**Comment by tacman** [comment]
+1

**Comment by yassine-khachlek** [comment]
+1

**Comment by bossibly** [comment]
+1 
Surprised there isn't one!

**Comment by lichtamberg** [comment]
+1000

**Comment by meizano** [comment]
+1

**Comment by abalter** [comment]
+1

**Comment by mschout** [comment]
+1

**Comment by lichtamberg** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by Chris-KCIT** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by ravatsinh** [comment]
+1

**Comment by ATLAdamL** [comment]
+1

**Comment by iBelit** [comment]
+1 still nothing?!

**Comment by LorincJuraj** [comment]
+1

**Comment by mengzy2018** [comment]
**I've always wanted it** +1

**Comment by sensibleworld** [comment]
Text your friends! 
https://fontawesome.com/icons/sms?style=solid
