### ISSUE TITLE
Icon request: mdb

### ISSUE THREAD

**Issue by filipkappa** [FortAwesome/Font-Awesome#14409]
### What can it be used for?

Lots of MDB Users are asking about MDB Icon to include in their projects.
Can be used for apps integrated with MDB, tutorials, independent plugins and more.
More than 800 000 web developers work with MDB every day and they'd make a good use of an asset like that. Our website: https://mdbootstrap.com/
This is a single icon.

### Example image (optional)

https://mdbootstrap.com/img/Marketing/general/logo/big/mdb.png

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by filipkappa** [comment]
@tagliala any updates on that? :)

**Comment by tagliala** [comment]
Please take a look at our leaderboard: https://fontawesome.com/community/leaderboard/brands

This request is going good, it's in the top 20

**Comment by dawidadach** [comment]
Keep it up! :)

**Comment by JStrebeyko** [comment]
all right, let's go!

**Comment by cArkadiusz** [comment]
+1

**Comment by catchmareck** [comment]
Top 10 already, let's go! :smile:

**Comment by primetrust** [comment]
Pumped!

**Comment by mattonit** [comment]
wow, that's amazing to hear!

**Comment by Martussky** [comment]
I think we'll achieve that soon! :)

**Comment by Bloodcast69** [comment]
Almost here!

**Comment by Rotarepmi** [comment]
Nice, go on! Almost first 3 :)

**Comment by marveluck** [comment]
I can't wait to see MDB icon 😍

**Comment by filipkappa** [comment]
Wow! Thanks for support guys!

**Comment by soccerdon1981** [comment]
💯 good luck fella

**Comment by adiela** [comment]
We want this icon

**Comment by filipkappa** [comment]
Wow! I see that my issue is first, is there any ETA for that kind of request?
I'd love to deliver the news to our developers so they could plan to add the mdb icon to our tools&layouts but I'm not sure how much time would it take for it to go to "in progress" and then to be "done".
Is there some standard waiting time? @tagliala

**Comment by tagliala** [comment]
@filipkappa congrats for bringing this at the top of our Leaderboard 🎉 !

A lot of brands [landed in 5.8.0](https://fontawesome.com/icons?d=gallery&s=brands&v=5.8.0,5.8.1) (including [Bootstrap](https://fontawesome.com/icons/bootstrap?style=brands)), so no surprise that this request rose up to number 1!

> Is there some standard waiting time? @tagliala

Nope, sorry, there is no standard.

I personally (I repeat: **personally**) believe that there are extremely good chances of seeing this included in the next round of brand icons.

Anyway, the FAQ section below the leaderboard contains a lot of information about how requests work: https://fontawesome.com/community/leaderboard/brands#faqs

**Comment by filipkappa** [comment]
Thanks, @tagliala that's very helpful :D we'll be tracking the changes then!

**Comment by Ugonna1054** [comment]
Nice work guys. Hope you get the font-awesome icon tag

**Comment by fahadjunaid60** [comment]
Thank you.

**Comment by filipkappa** [comment]
So @tagliala should we expect this any time soon? :)

**Comment by JStrebeyko** [comment]
Sexy news of the day! Let's see it happen && Congrats to the team for keeping it up!

**Comment by dasaed** [comment]
You guys have my vote!

**Comment by MasterKhatri** [comment]
Waiting for it. Good work.

**Comment by filipkappa** [comment]
@tagliala do you plan to release some new icons soon? :)

**Comment by filipkappa** [comment]
@tagliala ?

**Comment by jeankyle** [comment]
What do I have to import in the <head> section so as to use the icons? They are simply not showing.

**Comment by leonnelm62** [comment]
You did a good job 👏👏👏

**Comment by lofcz** [comment]
Ship it! ❤️

**Comment by JOFLIX** [comment]
Some good medical ones please?

**Comment by tagliala** [comment]
Is there any official, single color SVG file for this brand?

**Comment by filipkappa** [comment]
[mdb.zip](https://github.com/FortAwesome/Font-Awesome/files/3539739/mdb.zip)

**Comment by tagliala** [comment]
@filipkappa thanks, but that is an svg file with a base64-encoded png.

Any pure vector file?

**Comment by filipkappa** [comment]
I'm afraid not :/

**Comment by filipkappa** [comment]
@sensibleworld would that do? 
[MDB.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/3550539/MDB.svg.zip)

**Comment by guytzhak** [comment]
+1

**Comment by sensibleworld** [comment]
The MDB icon is now available in 5.11: https://fontawesome.com/icons/mdb?style=brands
