### ISSUE TITLE
Facebook-messenger icon doesn't working!

### ISSUE THREAD

**Issue by nguykhoatv** [FortAwesome/Font-Awesome#14408]
I cannot use facebook-messenger icon, it doesn't working with me. Help me, please!
My codepen: https://codepen.io/nguyn-khoa/pen/xmOjzN

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Facebook manager has been implemented in version 5.0.0 and you are still using FA 4.7.0

You should update to use the new icons (ps: we have just released 5.6.1, you may like it)

Upgrade guide: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

https://codepen.io/tagliala/pen/LMZrqy

Hope it helps

Closing here

**Comment by nguykhoatv** [comment]
Thank you very much for your answers. I have solved my problem.
Have a nice day!
