### ISSUE TITLE
Icon request: crystal-ball

### ISSUE THREAD

**Issue by LilianGee** [FortAwesome/Font-Awesome#14415]
### What can it be used for?

To start off, it would be an AMAZING addition to your collection of magical/Harry Potter-related stuff that I adore to death. Second and most importantly, I'm dying for a Crystal Ball icon to use on the websites I develop for a team of AI and predictive analysis. My idea is to give the less technical folks the feeling of "glancing into what can happen in the future".

### Example image (optional)

(simple ball with a pedestal and probably that starry/glittery effect you're already using on magic-related icons)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by malla** [comment]
I second this! Was just checking if there was such a icon but computer says no. :(

**Comment by vedangdate** [comment]
I second this too......or actually third this! xp

**Comment by trehutchison** [comment]
Lilian is exactly right - this is a very useful, and very common, icon for representing any type of forecast or predictive analysis.  The existing webcam icon is crystal-ball-ish, but not close enough to use in place of a proper crystal-ball icon.  I'm sure you'll style the icon so it's consistent with the rest of the FontAwesome characters, but here are a couple examples:

![image](https://user-images.githubusercontent.com/53543251/62253986-79293000-b3ac-11e9-92aa-9a0eccd89cf1.png)

![image](https://user-images.githubusercontent.com/53543251/62254002-83e3c500-b3ac-11e9-94c8-029e9c604377.png)

![image](https://user-images.githubusercontent.com/53543251/62254028-91994a80-b3ac-11e9-898e-89aaf6f34112.png)

**Comment by Lou47** [comment]
I want it too :D

**Comment by tagliala** [comment]
Available in FA6 Pro: https://fontawesome.com/v6.0/icons/crystal-ball?s=solid
