### ISSUE TITLE
Icon request: shield times 

### ISSUE THREAD

**Issue by matejar** [FortAwesome/Font-Awesome#14410]
Green one already exists in Font-Awesome (fas fa-shield-check). We need the red one:

![image](https://user-images.githubusercontent.com/15362309/50086394-2cb62900-01fd-11e9-8999-08caa902f4b9.png)

**Comment by matejar** [comment]
Tnx. Great solution. We will use masking for now.

**Comment by aethior** [comment]
Hi @matejar,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/shield-xmark

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to the Pro set

**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/44/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
