### ISSUE TITLE
img display:none print rule

### ISSUE THREAD

**Issue by cx99** [FortAwesome/Font-Awesome#14423]
Printing my page in safari for mac or iPad, _all_ images (not just Fontawesome icons) on my site vanished. This is with the Pro CDN

The culprit was this css in fontawesome-app.css line 23256

```
@media print {
//...
    article a[href^="#"]:after, img {
        content: "";
    }
//...
}

```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fontawesome-app.css` is not part of font awesome and I can't find that class in our source code

Could you please check that the file is coming from us?

**Comment by shorty2240** [comment]
Definitely seems to be!

![image](https://user-images.githubusercontent.com/1809714/50276630-4f815100-043a-11e9-8539-e577fb765708.png)

**Comment by tagliala** [comment]
Sorry, could you please clarify this request?

You are printing a page on font awesome's website? If yes, could you please provide me the link?

**Comment by shorty2240** [comment]
Well... I see what has happened here. No this is on a personal project, I must have followed some example or guide that included this file clearly in error. From a quick google there's a few example templates that say to include this but of course, that's their fault and mine, not yours! Sorry to bother you, feel free to just completely remove this as I doubt it'll ever help anyone else. PEBCAK, as they used to say 😅

**Comment by tagliala** [comment]
@cx99 do not worry at all!

Glad you've solved and we can definitely leave this here for future reference

Regards
