### ISSUE TITLE
Wrong css unicode value for fill circle and line circle. ( f111 )

### ISSUE THREAD

**Issue by shamseerahammedm** [FortAwesome/Font-Awesome#14424]
Both fill circle and line circle unicode values are equal "f111" ,
" f111 " how ever outputs a fill circle.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That is correct. Font Awesome 5 uses `font-weight` to differentiate between different styles

Maybe this could help: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#define

Closing here
