### ISSUE TITLE
Failed to decode downloaded font:

### ISSUE THREAD

**Issue by WenDaaa** [FortAwesome/Font-Awesome#14421]
当我在线下运行的时候是可以的部署到了服务器上就会报Failed to decode downloaded font:不显示图标
![1](https://user-images.githubusercontent.com/44088914/50213883-da6e3700-03b9-11e9-93ac-15632c756f8a.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`aitax.taxguard360.com` is not our official CDN so we cannot provide support for that.

If it is your own application server, please check that mime types and uploads are correct. Also, the font name makes me think to Font Awesome 4, is that the version you are using?

Hope it helps

Closing here but feel free to comment
