### ISSUE TITLE
Icon request: plug-slash

### ISSUE THREAD

**Issue by alexdgs** [FortAwesome/Font-Awesome#14434]
### What can it be used for?

To indicate some kind of network/database 'disconnected' or 'offline' state. Also for a button with a 'disconnect' action. We already have [plug](https://fontawesome.com/icons/plug?style=solid) for online/connected states.

### Example image (optional)

Same icon as [plug](https://fontawesome.com/icons/plug?style=solid), with an slash as in [user-slash](https://fontawesome.com/icons/user-slash?style=solid) 

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please note that this icon could be implemented by using the masking and layering features of the svg framework: http://jsfiddle.net/tagliala/mu0tcfx7/4/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
- https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by alexdgs** [comment]
As a desktop user the approach of implementing layering and masking _can be_ difficult. Luckily I found a way to do this within my framework: stack two glyphs, play with colors and voila! This could not be possible with e.g. menu items where your framework expects to display a single glyph as icon.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
