### ISSUE TITLE
Icon Request: Atlassian Service Desk

### ISSUE THREAD

**Issue by benjivm** [FortAwesome/Font-Awesome#14430]
You guys did a great job with the other [Atlassian icons](https://github.com/FortAwesome/Font-Awesome/issues/2724) and got most of them. Please consider adding [Service Desk](https://www.atlassian.com/software/jira/service-desk), a product we use frequently here and one that seems to be growing in popularity.

[Click here](https://i.imgur.com/jctO9O4.png) for the Service Desk logo.

**Comment by dwjalix** [comment]
+1
