### ISSUE TITLE
How to Upgrade from 5.0.13 to 5.6.3?

### ISSUE THREAD

**Issue by chobo2** [FortAwesome/Font-Awesome#14432]
Hi

I used to have these packages

```
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-brands": "^5.0.13",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
```
to

```
 "@fortawesome/fontawesome-free": "^5.6.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.6.3",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
```
and updated my reactjs project to be like this

```
import { library, icon } from '@fortawesome/fontawesome-svg-core'
import { faMoneyBill, faTrash, faSearch, faUserCircle, faEnvelope, faLock, faPlusSquare, faHome,
  faCogs, faTachometerAlt,  faBuilding, faPhone, faInfoCircle, faEdit, faAd, faMinusSquare } from '@fortawesome/free-solid-svg-icons'



library.add(faMoneyBill);
library.add(faTrash);
library.add(faSearch);
library.add(faUserCircle);
library.add(faEnvelope);
library.add(faLock);
library.add(faMinusSquare);
library.add(faPlusSquare);
library.add(faHome);
library.add(faCogs);
library.add(faTachometerAlt);
library.add(faBuilding);
library.add(faPhone);
library.add(faInfoCircle);
library.add(faEdit);
library.add(faAd);

```

Though webpack compiles my project I don't see any images once my site loads, I don't see any errors.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There ha been a breaking change in 5.1. I think you just need to import dom and call dom.watch, but please take a look here https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#no-more-default-imports and maybe herehttps://github.com/diowa/ruby2-rails5-bootstrap-heroku/blob/master/app/javascript/src/fontawesome.js#L1

(PS: you probably don't need `{ observeMutationsRoot: document }`)

Let me know if this helps

**Comment by chobo2** [comment]
@tagliala 

Yes it seems like dom.watch() is what i need, the instructions should be really written on this. would have never figured it out.

**Comment by tagliala** [comment]
@chobo2 glad you solved and sorry fot the breaking change :(

The new syntax is documented at https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core

Anyway, I'm monitoring issues like this so if they proliferate we will take action on the docs

Closing here
