### ISSUE TITLE
fa-bonds, fa-regular not working in safari 5.1.4 

### ISSUE THREAD

**Issue by amar-work** [FortAwesome/Font-Awesome#14443]
I used, fontawesome-all.css, with fa-bonds, fa-regular, fa-solid fonts. But in safari on windows showing squares..

**Comment by amar-work** [comment]
I used, fontawesome-all.css, with fa-bonds, fa-regular, fa-solid fonts. But in safari on windows showing squares..

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> But in safari on windows showing squares..

Sorry, but Safari on Windows is not supported

Quoting from: https://en.wikipedia.org/wiki/Safari_(web_browser)

> A Windows version was available from 2007 to 2012. [...] Safari 5.1.7 has become the last version of Safari developed for Windows.

Docs:
https://fontawesome.com/how-to-use/on-the-web/other-topics/browser-support

**Comment by tagliala** [comment]
I cannot help, but I'm leaving this open for feedback from the community

**Comment by amar-work** [comment]
I understand , thank you.
