### ISSUE TITLE
Icon Request: HockeyCircles

### ISSUE THREAD

**Issue by HockeyCircles** [FortAwesome/Font-Awesome#14444]
What can it be used for?

The branding icon from https://HockeyCircles.com, HockeyCircles is a social network solely for Hockey Players & Fans

Example image:

https://HockeyCircles.com/favicon.png

Icon request checklist

[Y] This is a single icon or matched pair (Ex: lock / unlock)
[Y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
[Y] I have searched for existing issues and to the best of my knowledge this is not a duplicate
[Y] I have included at least one example image if it could be helpful (optional)
[Y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
`hockeycircles.com` has moved to `sportsa.com` (check the link redirection).

cc/ @tagliala
