### ISSUE TITLE
Refused to apply style due to unsupported MIME type

### ISSUE THREAD

**Issue by timmackey** [FortAwesome/Font-Awesome#14441]
`Refused to apply style from 'http://localhost:4200/node_modules/@fortawesome/fontawesome-pro/css/all.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

...message is displayed in Chrome Version 71.0.3578.98 browser debug console, and icons are not visible for my AspNetZereo release 6.4.0 project.
AspNetZero release 6.2.0 does not display this message and all icons are visible.

I've attempted other solutions found in places like github and stackoverflow - without success.
The issue is related to "pro" icons only. Non-pro icons display normally.

What is required to fix this issue?

**Comment by timmackey** [comment]
Copying 'all.css' and 'all.min.css' to vendor file location is the solution, as suggested here:
https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type/50173968

**Comment by tagliala** [comment]
@timmackey thanks for letting us know

**Comment by shiknema** [comment]
If you put style.css file in the correct directory, the error will automatically disappear.
