### ISSUE TITLE
icon request  : fa-mLab

### ISSUE THREAD

**Issue by desraj173** [FortAwesome/Font-Awesome#14448]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please edit this request making sure that it follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by tagliala** [comment]
Closing here in favour of #14482
