### ISSUE TITLE
Icon-Request: icon-bring-to-front icon-bring-forward icon-move-to-back icon-move-backward

### ISSUE THREAD

**Issue by sboisse** [FortAwesome/Font-Awesome#1445]
Hello,

we would need those icons in an editor where we can z-order elements in a canvas, pretty much like in an editor where we can put shapes, images and similar objects.

Thanks!

**Comment by stbaer** [comment]
+1

**Comment by SilverSting** [comment]
+1

**Comment by ozanhazer** [comment]
+1

**Comment by dv3000** [comment]
+1

**Comment by frankydp** [comment]
+1

**Comment by av01d** [comment]
+1

**Comment by cvgellhorn** [comment]
+1

**Comment by bryanleetc** [comment]
+1

**Comment by tomrichmond** [comment]
+1

**Comment by newgrounds** [comment]
Something like this would be nice:
![image](https://cloud.githubusercontent.com/assets/667311/10081349/7f45df7c-62c2-11e5-9e52-e164c80741f9.png)

**Comment by costa974** [comment]
+1

**Comment by chadsaun** [comment]
+1

**Comment by craftyamie** [comment]
+1

**Comment by martypowell** [comment]
+1

**Comment by floriancargoet** [comment]
+1

**Comment by costa974** [comment]
+1

**Comment by d-amit** [comment]
+1

**Comment by iled** [comment]
+1

**Comment by stevensanborn** [comment]
+1

**Comment by muendiz** [comment]
+1

**Comment by photofinale** [comment]
+1

**Comment by mahasneh** [comment]
+1

**Comment by Lee-Taylor** [comment]
Anyone?! +1

**Comment by ericvillemure** [comment]
+1

**Comment by belgarion2k** [comment]
+1

**Comment by Frankstar** [comment]
mayb in Version 5 ?

**Comment by StevenFlecha** [comment]
+1

**Comment by qbonnard** [comment]
+1

**Comment by vmari** [comment]
+1

**Comment by jonnylink** [comment]
+1

**Comment by Frankstar** [comment]
still not in :(     
version 5.1.0 (free/pro)

**Comment by Frankstar** [comment]
can we at least get a response from the Team?
I mean its 5 years and we still use custom icons for that purpose ...

if you say "it will never come" - im fine with it.

**Comment by DaeHeeLim** [comment]
+1

**Comment by Lee-Taylor** [comment]
I moved to these icons instead:

https://materialdesignicons.com

**Comment by ric-h** [comment]
+1

**Comment by Lee-Taylor** [comment]
I would recommend moving to:

https://materialdesignicons.com

**Comment by Frankstar** [comment]
to be honest @Lee-Taylor - thats not a option at all for us.    

i think we should email them this issue since its not even on https://fontawesome.com/community/leaderboard/new

**Comment by r-man** [comment]
+1

**Comment by martylamoureux** [comment]
I still don't understand why those icons are not yet implemented!

**Comment by Frankstar** [comment]
Its on https://fontawesome.com/community/leaderboard/new    
now -> place 13

**Comment by sensibleworld** [comment]
Hey folks! We've added some options for this in Font Awesome Pro:

https://fontawesome.com/icons/send-back?style=solid
https://fontawesome.com/icons/send-backward?style=solid
https://fontawesome.com/icons/bring-forward?style=solid
https://fontawesome.com/icons/bring-front?style=solid
