### ISSUE TITLE
fa-gitlab terribly misaligned?

### ISSUE THREAD

**Issue by ndrmnl** [FortAwesome/Font-Awesome#14450]
Hi,

This is how `fa-gitlab` looks on my website:
![image](https://user-images.githubusercontent.com/1813536/50536928-3a06d800-0b5a-11e9-8255-b946d5c9fa04.png)
I'm not sure it's a bug on your end, but I googled a bit and couldn't find anything to be done on mine.

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details?

Please fill our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and maybe add a reproducible test case

**Comment by PxLucasF** [comment]
Maybe your files are needing an update or are corrupted? Try using Font Awesome via CDN just to check if it solves the problem.

```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
```

**Comment by ndrmnl** [comment]
Okay, in the process of giving you feedback I actually figured out what it was... In my CSS I was setting the font in the links to bold, thus causing this effect (on Linux only for some reason...). As soon as I remove the bold it goes back to normal.

Thanks for your replies!
