### ISSUE TITLE
Change alphabetical order of OTF

### ISSUE THREAD

**Issue by irenehardy** [FortAwesome/Font-Awesome#14456]
Ok, this is a really silly little request. But in future versions, would you consider making a slight variation in naming the brands vs regular font so that alphabetically, the brands one come second? The way it is now, every time I start to type Font Awesome in Adobe Creative Cloud, it autocompletes to the brands version and it's kind of a pain to keep typing the full name. :)

**Comment by sensibleworld** [comment]
Thanks for the feedback! I, too, feel this pain. We'll have to see if something like this is possible, but the likelyhood is that we'll need to keep naming as-is for our current versions.
