### ISSUE TITLE
Unable to uninstall fontawesome

### ISSUE THREAD

**Issue by blachawk** [FortAwesome/Font-Awesome#14469]
I accidently installed some depracticated versions of fontawesome.  I am not understanding how the process works for unisntalling them from npm packages.   I cannot find any documention on the web that relates to this matter.  I have the following local npm packages installed in my project:

```
@fortawesome/fontawesome@1.1.8
@fortawesome/fontawesome-free-solid@5.0.13
```

When I attempt to uninstall any of these packages, they still hang around.  Here is what I am using:

`npm uninstall @fortawesome/fontawesome@1.1.8` 

I also tried 

`npm uninstall fontawesome@1.1.8` 

What am I doing wrong?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does `npm uninstall @fortawesome/fontawesome` work for you?

**Comment by blachawk** [comment]
That worked.  Thank you so much for the lesson on that.

**Comment by tagliala** [comment]
You're welcome, glad you solved

**Comment by jaxkashif34** [comment]
![Capture PNG1](https://user-images.githubusercontent.com/28916829/132119745-331647a8-60af-4d5b-8f37-9a4590266361.PNG)
Hi @tagliala my name is Kashif Ali.
when i try to install any package from npm or uninstall font Awesome it throws me an ERROR every time i searched about almost everywhere but did not fint any perfect solution for my problem basicall in my prjoject node modules is missing so i try to install node modules by run these commands (npm install, npm install --force, npm install --legacy-peer-deps) and my  packges were about to install but at the end it stuck on @fontawesome  and throws an error showes in image. 
Thanks.

**Comment by tagliala** [comment]
Hi, I cannot properly understand the screenshot.

It looks like that the machine is not able to compile `node-sass`, which is not a required dependency of Font Awesome

Please try from the command line in a new folder

```bash
npm init --yes
npm install @fort-awesome/font-awesome-free
```

If you still have issues and you think it is an issue with Font Awesome, please fill in our 
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open because it doesn't meet our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide as many details as you can, including OS/version and version of tools used

**Comment by jaxkashif34** [comment]
Thank you so much for your reply☺️
Basically I am a beginner in react i have an error when i run npm install
it stuck on @fontaweaome and than throws an error please help me to resolve
this error if you know anything about this error it waste my 2 days.
Thanks for your help

**Comment by jaxkashif34** [comment]
I follow your commands and run these two commands in my vs code terminal
but again ERROR😓

**Comment by tagliala** [comment]
> it stuck on @fontaweaome and than throws an error please help me to resolve

Font Awesome does not have packages named `@fontawesome`

Font Awesome's official packages are listed under the `@fortawesome` (notice the `R`, it is not a typo) npm scope, all listed here: https://www.npmjs.com/search?q=%40fortawesome

Any other package does found on npm.js does not belong to us and it is not supported by us

> Basically I am a beginner in react

Docs for React: https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react

> I follow your commands and run these two commands in my vs code terminal
but again ERROR😓

Please open a new request by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide as many details as you can, including OS/version and version of tools used. Include the debug log

**Comment by jaxkashif34** [comment]
Ok, I'll check it out.

**Comment by MeryemTAIKOK** [comment]
"npm uninstall @fortawesome/fontawesome" works for me, thank you
