### ISSUE TITLE
Patreon icon showing as block

### ISSUE THREAD

**Issue by lilmisslotus** [FortAwesome/Font-Awesome#14460]
Hi, I am trying to use the patreon icon but it's showing up as a square. Using the same markup as several other icons that are working fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[Patreon](https://fontawesome.com/icons/patreon?style=brands) has been introduced in Font Awesome 5.0.0

Please make sure that your website is using Font Awesome >= 5.0.0 and there aren't third party plugins / themes / extensions that are loading older versions of Font Awesome or blocking icons

**Comment by lilmisslotus** [comment]
I changed my plugin settings and it worked! Thank you so much! Sorry about that! 



 <http://jessicakarp.com/>	
JESSICA KARP
770.689.6564 <tel:770.689.6564>
jessica@jessicakarp.com <mailto:jessica@jessicakarp.com> | jessicakarp.com <http://jessicakarp.com/>
