### ISSUE TITLE
Icon request: git-alt

### ISSUE THREAD

**Issue by MattIPv4** [FortAwesome/Font-Awesome#14463]
### What can it be used for?

Indicating the usage of git on a project, using the well known git icon instead of the text form.

### Example image (optional)

![](https://git-scm.com/images/logos/downloads/Git-Icon-Black.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Well, this is kinda odd 😅 

I suppose there is a reason why we are using the "git" text instead of the git icon. Also, the git text does not match style on git

@talbs

**Comment by talbs** [comment]
Thanks for this request and catch, @MattIPv4. We'll definitely get this symbol in as a `git-alt` and an updated text treatment for the `git` icon into our next release. Stay tuned and thanks for the help bringing this to our attention. 😄

**Comment by wmerussi** [comment]
I was a little confused when the icon for git was a text instead their icon. Gonna subscribe to get this one ASAP :)

**Comment by MattIPv4** [comment]
This was added in 5.8.2: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#582---2019-05-07

**Comment by tagliala** [comment]
@MattIPv4 thanks for the heads-up

https://fontawesome.com/icons/git-alt?style=brands
