### ISSUE TITLE
Radiation Icon is not copying

### ISSUE THREAD

**Issue by Johannawastaken** [FortAwesome/Font-Awesome#14462]
### Font Awesome 5 Pro

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

<img width="662" alt="screen shot 2019-01-03 at 3 55 15 pm" src="https://user-images.githubusercontent.com/46360723/50667877-62367280-0f70-11e9-8cb7-fbd6deb9273d.png">
<img width="435" alt="screen shot 2019-01-03 at 3 59 29 pm" src="https://user-images.githubusercontent.com/46360723/50667916-93af3e00-0f70-11e9-800b-8abb458052e8.png">

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Radiation has been introduced in version 5.6.0.

Could you please check that you are using FA >= 5.6.0?
