### ISSUE TITLE
svg_core local define func confused rjs parser

### ISSUE THREAD

**Issue by huochunpeng** [FortAwesome/Font-Awesome#14461]
This call to local define func.
https://github.com/FortAwesome/Font-Awesome/blob/fc377a13a36717464b61c045444fea1e35c26b6d/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L1607

It confused rjs parser which thinks it's a named AMD module definition. https://github.com/aurelia/cli/issues/1013#issuecomment-451309898

I know this is technically a rjs parser bug, but do you think it's a good idea to rename the internal `define` func to something like `_define`?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Well, it makes sense.

Let's see what @robmadole thinks about this

**Comment by robmadole** [comment]
Yeah this is an easy fix. That function is private so changing it is a find/replace. Should be released in `5.7.0`.

**Comment by huochunpeng** [comment]
Thx very much!

**Comment by huochunpeng** [comment]
Note this should be fixed in both commonjs (index.js) and esm build (index.es.js).

**Comment by robmadole** [comment]
Yep, we use Rollup.js to generate both of those from the same source file. They'll both be fixed. :)

**Comment by robmadole** [comment]
This should be resolved now in 5.7.1.
