### ISSUE TITLE
Icon-request: icon-multiplatform (icon-devices icon-responsive)

### ISSUE THREAD

**Issue by Geekarts** [FortAwesome/Font-Awesome#1446]
It would be great to have an icon to represent multiplatform.

**Comment by ElHamster** [comment]
+1
maybe like this: http://picload.org/image/cipawro/responsive-small.png

**Comment by edesdan** [comment]
+1

**Comment by vlipman** [comment]
+1 - I like ideirj's 
http://www.emthemes.com/media/em0074/key-features.png
left side: adaptive icon

but w/o the checkmark - for me, having just the superimposed devices would be more useful...

**Comment by boh717** [comment]
+1

**Comment by miksh7** [comment]
+1

**Comment by gligoran** [comment]
+1 for multiplaform; similar to the one mentioned in #5899 or the top left one in http://www.emthemes.com/media/em0074/key-features.png without the arrow.

**Comment by lohithatn** [comment]
+1

**Comment by yocmen** [comment]
+1

**Comment by GustavSt** [comment]
+1

**Comment by Pezhvak** [comment]
+1

**Comment by simona6** [comment]
Hi.  I see many folks have asked for an icon request that basically expresses "multi platforms".  A brilliant idea.  One that "layers" desktop, tablet and mobile.  Pity that over the 2 years of these requests, none have been done.  So I'd like to add my request to this one please.

**Comment by cherrador** [comment]
Ok, because lack of support, maybe like this using stacks could help for a while:
![03](https://cloud.githubusercontent.com/assets/12229855/13384438/8562e126-de63-11e5-9500-5302d79c6048.png)

Check my jsfiddle for how it's done.
https://jsfiddle.net/cherrador/jomgLb2h/

**Comment by simona6** [comment]
Sorry I don’t get how to install that .  Similar way to the usual ones?

“Lack of support”??

**Comment by simona6** [comment]
I’m sorry?
I replied asking for more help on this, and the matter gets closed?

I’ve no idea what to do.

**Comment by cherrador** [comment]
Yes, because this icon will be no be available for a while. So as alternative it could be build using stacks. This are done with the same FA base icons.

However, I have expanded the FA original CSS to include extra stacks functions. You could copy the CSS from the jsfiddle sample into a separated file that will be loaded after the base FA CSS is loaded. This will patch it to include the extra classes. Then find and copy the HTML tags that create the icon that you want, then paste it on your code where it's required. Make any required modifications (size, colors, shadows, actions, etc.) and you are done.

**Comment by simona6** [comment]
I need that ONE icon.
I don’t really want to use a ton of CSS and other stuff to do that.

When you say lack of support, do you mean font awesome just isn’t getting updated much these days?

**Comment by cherrador** [comment]
To achieve that icon, I combined 4 icons. The extra CSS is the glue to put them together.

If you want the ONE icon premade on the core font set, you will need to wait. How long? who knows... If you scan the requests here, you will find some popular icons had been on hold for more than 3 years, while other ones without too much request get integrated in less than 6 months.

So if you need this icon today, I will recommend to use the stacks alternative.

**Comment by tagliala** [comment]
@simona6 please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

you just need a proper .svg of the icon you want to add to Font Awesome

**Comment by TMMC** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by tidusjar** [comment]
+1

**Comment by caleyshemc** [comment]
+1

**Comment by dapitts08** [comment]
+1

**Comment by dctdct** [comment]
+1

**Comment by webappdesigner** [comment]
+1 .... always make me chuckle when i see 3 useless icons for a tv show (pied piper) but still no icon for 'responsive web design' or 'multi-platform' etc...

**Comment by spartanier7777** [comment]
+1 over two years and no progress. C'mon guys..

**Comment by mkozjak** [comment]
+1

**Comment by pkoretic** [comment]
+1

**Comment by inextable** [comment]
+1 please multi device/ multi plattform icon!

**Comment by vlanard** [comment]
+1

**Comment by Daijobou** [comment]
+1

**Comment by krynhild** [comment]
+1

**Comment by gischy** [comment]
+1

**Comment by bradenhutch** [comment]
+1

**Comment by Kokil** [comment]
+1

**Comment by graingerkid** [comment]
https://jsfiddle.net/jomgLb2h/116/

**Comment by c2ofh** [comment]
+1

**Comment by berkaybayraktar** [comment]
+1

**Comment by KingDumah** [comment]
+1

**Comment by MHolger77** [comment]
+1

**Comment by FrancoCab10** [comment]
Material Icons has 2 good examples! Would be very usefull to have a light version of those.
![Devices](https://material.io/tools/icons/static/icons/baseline-devices-24px.svg)
![Devices2](https://material.io/tools/icons/static/icons/baseline-important_devices-24px.svg)

**Comment by sensibleworld** [comment]
We've added a `phone-laptop` icon to Font Awesome Pro: https://fontawesome.com/icons/phone-laptop?style=solid
