### ISSUE TITLE
Icon request: fa-sparkles✨ (Like the ones in the "Magic" Icon to use for Layering)

### ISSUE THREAD

**Issue by gooeyideas** [FortAwesome/Font-Awesome#14473]
### What can it be used for?
A generic "sparkles" icon would be nice to have. It could be added to text or layered above other icons to highlight "new" features or events. 

![image](https://user-images.githubusercontent.com/6644447/51214120-9ef45900-18e2-11e9-880f-31183c92b2cc.png)

### Example image: (_forgive the spelling mistake_)
![image](https://user-images.githubusercontent.com/6644447/50714688-64b3cd80-103f-11e9-9918-dce237c8c752.png)
Using with the icon layers:

![image](https://user-images.githubusercontent.com/6644447/50715048-e8ba8500-1040-11e9-922e-0b9e0f454245.png)

**Comment by tagliala** [comment]
Thanks, got it

**Comment by PxLucasF** [comment]
That would be perfect for indicate something very clean or shiny :+1:

**Comment by sensibleworld** [comment]
Love this idea for an icon! I've added it to my to-do list :)

**Comment by sensibleworld** [comment]
`fa-sparkles` is now in Font Awesome Pro: https://fontawesome.com/icons/sparkles?style=solid

**Comment by ayancey** [comment]
Gotta be honest. Genius move to make the sparkles a pro only icon during the AI boom.

**Comment by ayancey** [comment]
Now if only Codex wouldn't try and use it...
