### ISSUE TITLE
Fontawesome 5 data-content not loading after upgrading from 4.7

### ISSUE THREAD

**Issue by pinktanha** [FortAwesome/Font-Awesome#14476]
### Describe the problem

During the usage of font awesome 4.7.0 the data-content unicode was displaying correctly. But I am using 5.6.3 fontawesome now and my data content is coming like an empty box.

### What did you expect?

The unicode to display properly

### What version and implementation are you using?

Version: 5.6.3
Browser and version: chrome

- [ ] SVG with JS
- [x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://jsfiddle.net/5nemLjrg/

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that Font Awesome 5 introduced breaking changes. Take a look at https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

You can fix your fiddle in this way: https://jsfiddle.net/tagliala/748hqybc/ (please note the font-weight attribute. Also, I've loaded the font awesome css and set the font family)

Hope it helps

Closing here

**Comment by pinktanha** [comment]
Thanks a lot! It worked!
