### ISSUE TITLE
Still Issues Using Font Awesome Po 5.6.3

### ISSUE THREAD

**Issue by DieterGust** [FortAwesome/Font-Awesome#14483]
I’ve tested the TTF Web fonts 5.6.3 in PowerPoint 365:
New is: All fonts are now available in the font drop down dialog – fine!

But:
1) For the brand font no icons are shown (empty line!) – for the other fonts the icons are shown 
(I strongly would prefer the Latin names)

2) Using Insert>Symbol: only some icons are shown:
But I can add the Unicode Code Point „via the code dialog and this works also for characters that are not shown.
3) The icons seem to have 0-width in PowerPoint, if you only use Font Awesome characters. 
4) You may enter any character of standard Unicode Code Points: This always inserts a blank space – except the official empty character which does nothing!
5) In the Windows Font dialog all Font Awesome web fonts are not grouped together but shown as single fonts
I re-checked 5.6.3 OTF fonts in PowerPoint
Font Awesome Pro fonts are shown as a grouped font in Windows font dialog – the brand font is shown separately
The Insert dialog shows with OTF fonts all characters - fine and Latin characters are also shown. 
The glyphs seem to have standard widths 8and not 0-widths as with TTF web fonts

But: 6) Not all Icons are inserted using the insert  > symbol dialog only icons below Code Point F100.

So everything is much better now with 5.6.3 but still a several bugs with TTF and even with OTF fonts
Dieter

**Comment by DieterGust** [comment]
I checked today the current OTF fonts  on my windows 10 platform and PowerPoint 365 : Now I could insert any glyph using insert symbol dialog and coping the glyph from Font Awesome website - wonderful!
Maybe yesterday I had a cahing problems as I installed and deleted TTF and reinstalld OTF fonts 
So I skip all TTF fonts for desktop usage.

**Comment by tagliala** [comment]
@DieterGust as far as I know, @robmadole is doing some changes on the TTF files in version 5.7.0, but I don't know if that will fix usage on desktop #13320

There will be some fixes on the OTF version too: #13900

If your issues are gone, could you please close this request?

**Comment by DieterGust** [comment]
I‘ll do some  last tests tomorrow and If they are positive i'll close the request. Thank you Dieter

Mit freundlichen Grüßen
Dieter Gust
itl AG


________________________________
Von: Geremia Taglialatela <notifications@github.com>
Gesendet: Donnerstag, Januar 10, 2019 6:23 PM
An: FortAwesome/Font-Awesome
Cc: Gust, Dieter; Mention
Betreff: Re: [FortAwesome/Font-Awesome] Still Issues Using Font Awesome Po 5.6.3 (#14483)


@DieterGust<https://github.com/DieterGust> as far as I know, @robmadole<https://github.com/robmadole> is doing some changes on the TTF files in version 5.7.0, but I don't know if that will fix usage on desktop #13320<https://github.com/FortAwesome/Font-Awesome/issues/13320>

There will be some fixes on the OTF version too: #13900<https://github.com/FortAwesome/Font-Awesome/issues/13900>

If your issues are gone, could you please close this request?

**Comment by DieterGust** [comment]
OTF fonts 5.6.3 (Desktop): I checked inserting the icons in PowerPoint 365 using  Insert > Symbols > Symbol.
I didn't test all glyphs but my random test: no errors any longer!  Copy and Paste into Word worked too.
Font names are shown with Latin characters. Wonderful.
I think we can close the issue regarding OTF fonts.
