### ISSUE TITLE
Icon request: dashboard

### ISSUE THREAD

**Issue by danielmorell** [FortAwesome/Font-Awesome#14488]
### What can it be used for?

A dashboard icon would be used for dashboard UIs that are textually and navigationally focused. Dashboards where tachometers and graphs numerical emphasis would be misleading. 

### Example image (optional)

![dashboard](https://user-images.githubusercontent.com/25595393/50995507-e181f400-14e4-11e9-8de8-85f3d266cffe.png)

### Icon request checklist

- [x] This is a **single icon**
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that this is a duplicate but at the moment I cannot recall the original request.

It's hard to find because this does not represent something concrete

May refer to #1461

**Comment by tagliala** [comment]
btw,

https://fontawesome.com/icons/th-large?style=solid
https://fontawesome.com/icons/th?style=solid

May fit the use case

**Comment by nigels-com** [comment]
There is a precedent for @danmorell 's suggestion from Material UI:
https://www.materialui.co/icon/dashboard

![dashboard_black_144x144](https://user-images.githubusercontent.com/545677/52708955-2e228880-2fd7-11e9-86d5-47b786b26f60.png)

**Comment by danmorell** [comment]
I, actually, just used the Material UI rounded icon.

[https://material.io/tools/icons/?search=dashboard&style=round](https://material.io/tools/icons/?search=dashboard&style=round)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/objects-column?f=classic&s=solid)
