### ISSUE TITLE
Icon request: envelope-slash

### ISSUE THREAD

**Issue by jnunderwood** [FortAwesome/Font-Awesome#14486]
### What can it be used for?

Missing email address. 

We currently use the "phone" icon for phone numbers and the "phone-slash" icon for missing phone numbers. We also use the "envelope" icon for email addresses. We would like to have similar icon for missing email addresses. 

### Example image (optional)

The new "envelope-slash" icon would be the existing envelope icon with a slash through it.

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon with the layering and masking features of the SVG framework:

http://jsfiddle.net/tagliala/u4h19ecy/13/

Docs:
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
- https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by jnunderwood** [comment]
Thank you very much for the assistance. I had tried something similar, but it created problems with spacing around the icon. I will try what you put in your example.

**Comment by jnunderwood** [comment]
I have tried this and it works! One downside is the requirement for including font-awesome/js/all.min.js. This adds another 1MB to the page download. So, a separate icon would be ideal. Thanks again; I really appreciate it.

**Comment by tagliala** [comment]
@jnunderwood you can use css stack http://jsfiddle.net/tagliala/5b9okq42/5/ (but it will not look that good and it is kinda hacky (no transparency)

If you use webpack in your development stack, you can drastically reduce the file size of the font awesome javascript framework including just the icons you need by taking advantage of the tree shaking feature

**Comment by jnunderwood** [comment]
This is for use in a [Grails](https://grails.org/) app, which uses the [asset-pipeline](http://www.asset-pipeline.com/) plugin for managing web assets. I'm not sure how well they will integrate, but I will definitely investigate. Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
