### ISSUE TITLE
Icon request: doner-menu (filter-alt / filter-apple)

### ISSUE THREAD

**Issue by elyrium** [FortAwesome/Font-Awesome#14485]
### What can it be used for?

There's only one icon to represent filter in FA. I've observed users puzzled by its shape and not understanding what it represents. It would be great to also have an alternative icon to be used to trigger filtering options. 

### Example image (optional)

Example of an alternate icon for filtering being used by some applications in the past couple of years. 
<img width="134" alt="filter-alternative" src="https://user-images.githubusercontent.com/2694250/50930561-4f1f1900-142e-11e9-86a5-b905d966c023.png">

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Just a couple of questions:

> being used by some applications in the past couple of years.

Any example?

Does https://fontawesome.com/icons/sort-amount-up?style=solid or https://fontawesome.com/icons/sort-amount-down?style=solid fit this use case?

**Comment by elyrium** [comment]
Hi @tagliala 

I think the presence of the arrow in the icon (fa-sort-amount-up/down) implies the items on the page would be re-ordered instead of excluded. The existing filter icon (fa-filter) fails to communicate that certain items on the page would be excluded, or that the result-set will be smaller. I hope this helps.

**Comment by tagliala** [comment]
@elyrium thanks, seems legit

**Comment by TALCGCG** [comment]
Did this ever go anywhere? I was about to submit this same request. How do we know if it's being considered?

**Comment by uxchameleon** [comment]
+1

**Comment by TALCGCG** [comment]
Hi! Does closed mean that it's been created/approved/denied? I'd still love to see this icon added but I'm not sure what the progress was. Thanks so much!

**Comment by dvbeek** [comment]
@TALCGCG As far as I know, the approve issues based on the amount of votes...
So as soon as this issue gets enough votes, it will probably be implemented.

**Comment by TALCGCG** [comment]
> @TALCGCG As far as I know, the approve issues based on the amount of votes...
> So as soon as this issue gets enough votes, it will probably be implemented.

Where does one vote?

**Comment by dvbeek** [comment]
With votes I meant thumbs-up, which you already did :)

**Comment by rintkid** [comment]
Hi guys !
I do need this icon here as well ! Let's hope it gets implemented soon as it feels pretty standard :o

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/bars-filter?f=classic&s=solid)
