### ISSUE TITLE
Font Mis-Match Between FontAwesome.com and Local Font

### ISSUE THREAD

**Issue by mattryyc** [FortAwesome/Font-Awesome#14499]
### Describe the problem

When using FontAwesome.com to select an icon, it looks different in the website preview of the icon as compared to local. For example 'smile' on website features a smiley face with dot eyes, but on local the eyes contain an extra pupil circle inside the eyes.

'users' contains 3 users with bottom of shoulders cropped but when using on local the shoulders are present.

### What did you expect?

The FontAwesome.com website preview should be an exact match to what is shown on the desktop font.

### What version and implementation are you using?

Version: 5.6.3
Browser and version: Chrome for Mac (Latest)

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [X] On the Desktop

### Bug report checklist

- [X ] I have filled out as much of the above information as I can
- [X ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm pretty confident that your website is loading an older version of font awesome which takes priority in your website.

Please check all your third party plugins / themes and make sure that you are using the latest version

Hope it helps

Closing here, but feel free to comment

**Comment by mattryyc** [comment]
Hi there,
My issue is on the desktop as opposed to website - I've checked across browsers and this issue has come up for a few colleagues now in our office. Let's take for example the 'smile' icon:

https://fontawesome.com/icons/smile?style=regular

When viewing version 5.6.3 of the font locally, the smile icon is different from that of the website. 

Here's a screen grab showing the two versions - one a screengrab of the icon from FontAwesome.com and the below the equivalent font from a freshly installed FontAwesome 5 Pro downlaod:
https://imgur.com/ZczJpXi 

I've encountered the same issue when using the 'users' icon, where the web preview appears to be out of sync with what's displayed on the website.

I appreciate you taking the time to review.

**Comment by tagliala** [comment]
Ah, sorry. Didn't get that.

Please uninstall all versions of Font Awesome installed on your system, restart your system and reinstall them all.

Let me know

**Comment by mattryyc** [comment]
I have just done this on a fresh install, it appears to be the same issue - are you not reproducing this on your side? If you could let me know which version you are seeing that would help me debug my local font vs. a web caching issue on FontAwesome.com. Thanks.

**Comment by tagliala** [comment]
1. Uninstalled my previous FA fonts

2. Downloaded FA 5.6.3 Pro from here:
![image](https://user-images.githubusercontent.com/556268/51146842-4d06f100-1858-11e9-9c62-219efcb2383c.png)

3. Installed new otf icons

4. Checked with MS Word
![image](https://user-images.githubusercontent.com/556268/51146971-d3bbce00-1858-11e9-9e34-8ba81d0dcb88.png)

**Comment by tagliala** [comment]
macOS pages:
![image](https://user-images.githubusercontent.com/556268/51147212-b9362480-1859-11e9-9fd4-888dc1beb339.png)

**Comment by tagliala** [comment]
@mattryyc any update? did you manage to sort this out?

**Comment by mattryyc** [comment]
Thanks for your help with this, I was able to test on a VM and the issue wasn't present there so I've cleaned all extra fonts off my machine and started from scratch and it is now working. Thanks again for your help and patience.

**Comment by tagliala** [comment]
@mattryyc you're welcome, glad you solved
