### ISSUE TITLE
icon does not show

### ISSUE THREAD

**Issue by vrob19** [FortAwesome/Font-Awesome#14494]
Hello,

When I attempt to add fa-baby, fa-warehouse ect to my site the icon will not show up on my wordpress dashboard. I have only been able to add fa-wifi and fa-credit-card

Am I doing something wrong. Some items show while others do not show up

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your WordPress instance is probably using an older version of Font Awesome. Please note that we do not provide support to third party plugins/themes

If you have manually added the latest Font Awesome's js/css from the CDN to your HTML's <head> tag, a theme / third party plugin is loading an older version that may have preference.

Please check how your website is loading Font Awesome and take action accordingly

Hope it help

Closing here, but feel free to comment
