### ISSUE TITLE
Yelp Icon

### ISSUE THREAD

**Issue by joenruschia** [FortAwesome/Font-Awesome#14491]
Check the yelp icon. Look really close (zoom in) by the "point". 
<img width="1280" alt="screen shot 2019-01-10 at 11 45 19 pm" src="https://user-images.githubusercontent.com/2938461/51019985-eb7e1400-1531-11e9-9607-7914698e96e6.png">

**Comment by talbs** [comment]
> @talbs you can find a proper .eps here: https://www.yelp.com/brand

@tagliala you got it! Thanks for bringing this to our attention, @joenruschia. I'll let you folks know what I find and when I have a fix.

**Comment by talbs** [comment]
Okay, gang. I've got a fix up in our build system. We'll get that merged in and included in our next release. Thanks again for the good eyes and help with this. 😄

**Comment by talbs** [comment]
Thanks for the catch, @joenruschia. I think we've got this solved in version `5.7.0`. Check out and download a fresh copy of the Yelp SVG at https://fontawesome.com/icons/yelp?style=brands. There should be no extra points nor jagged connections. Here's a screenshot of the vector zoomed into in Illustrator..

![image](https://user-images.githubusercontent.com/163763/51916456-51c8ba80-23ab-11e9-8fd1-0cf37542e74a.png)

Let me know if you're still having trouble or seeing anything else out of place. Thanks again for the help with this one. 😄
