### ISSUE TITLE
unlock-alt, unlock, Key & lock not working when used as webfont by adding CSS url link

### ISSUE THREAD

**Issue by storesbuzz** [FortAwesome/Font-Awesome#14496]
I have added 
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">`

this in my head and i am using font as
`<i class="fas fa-lock"></i>`

Other icons I tried are working fine but facing issue with above 4 icons. I have to use them for password field in forms.

These icons are appearing as:

![image](https://user-images.githubusercontent.com/30376399/51086707-f0c8a200-176f-11e9-9bdc-b20159565daf.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/3nd4sb80/

Please check third party plugins / themes / development console

I'm going to close here but feel free to comment
