### ISSUE TITLE
data-prefix is lost when using nesting with jQuery

### ISSUE THREAD

**Issue by felixoi** [FortAwesome/Font-Awesome#14493]
### Describe the problem

Then toggling the icon class of the `i`-tag with jquery when nested svg's are enabled, the `data-prefix` attribute of the nested svg is set to `null`. This leads to a broken icon. All other attributes like the `data-icon ` attribute are copied correctly to the svg then toggling the class on the `i`-tag.

### What did you expect?

When toggling the icon class on the `i`-tag, the `data-prefix` attribute should not be touched and stay in it's old state.

### What version and implementation are you using?

Version: 5.6.3
Browser and version: Chrome 71.0.3578.98 (Official Build) (64-bit)

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://codepen.io/felixoi/pen/QzJrLd

-> Click the button and see what happens!

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Seems like https://github.com/FortAwesome/Font-Awesome/issues/12556 but I'm not using knockout.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please edit the first post and fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) ?

Please also provide a reproducible test case. You an use codepen or jsfiddle

**Comment by felixoi** [comment]
Oh sorry! Somehow I missed this template. Updated the issue and added a test case.

**Comment by tagliala** [comment]
Thanks for the reproducible test case

As per documentation at https://fontawesome.com/how-to-use/on-the-web/using-with/jquery

When nest is enabled, you do not have to follow instructions about [not-nested elements](https://fontawesome.com/how-to-use/on-the-web/using-with/jquery#not-nesting)

Try to replace `.find("i[data-fa-i2svg]")` with `.find("svg[data-fa-i2svg]")`

https://codepen.io/tagliala/pen/pqQVLL

Hope it helps

Meanwhile, closing here
