### ISSUE TITLE
Icon request: icon-sword

### ISSUE THREAD

**Issue by abhinayrathore** [FortAwesome/Font-Awesome#1449]

**Comment by Shyzer** [comment]
I'd love a sword icon as well.

**Comment by mindstorm** [comment]
+1

**Comment by GwenLoguir** [comment]
+1 for everyting!

**Comment by renatodinhani** [comment]
+1

**Comment by Ribaz** [comment]
+1

**Comment by lyhil** [comment]
+1 beautiful, all of this

**Comment by huntingtown** [comment]
+1

**Comment by fr0980y** [comment]
+1

**Comment by aseckel** [comment]
+1

**Comment by winters-song** [comment]
+1

**Comment by Wruczek** [comment]
+1

**Comment by edasaki** [comment]
+1, hoping it can be added soon as the request seems to have support and has been open for over 2 years

**Comment by davidrouten** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by Wruczek** [comment]
Icon Examples:

<a href="http://icons.iconarchive.com/icons/icons8/windows-8/512/Military-Sword-icon.png"><img src="http://i.imgur.com/dzrEJlz.png" alt="http://icons.iconarchive.com/icons/icons8/windows-8/512/Military-Sword-icon.png"></a>

- http://icons.iconarchive.com/icons/icons8/windows-8/512/Military-Sword-icon.png

<a href="http://www.iconarchive.com/download/i78564/chrisl21/minecraft/Gold-Sword.ico"><img src="http://www.iconarchive.com/download/i78564/chrisl21/minecraft/Gold-Sword.ico" alt="http://www.iconarchive.com/download/i78564/chrisl21/minecraft/Gold-Sword.ico"></a>

- http://www.iconarchive.com/download/i78564/chrisl21/minecraft/Gold-Sword.ico

**Comment by rinaldo-ferreira** [comment]
+1

**Comment by andreasindal** [comment]
+1

**Comment by jasonCodeng** [comment]
+1

**Comment by Arugin** [comment]
+1

**Comment by sophie-li** [comment]
+1

**Comment by toonvanvr** [comment]
+1

**Comment by LFP6** [comment]
Also, crossed swords

**Comment by Phill93** [comment]
+1

**Comment by trikota** [comment]
+1

**Comment by RobertDoc** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a sword icon to Font Awesome Pro, along with a doubled up version.

https://fontawesome.com/icons/sword?style=solid
https://fontawesome.com/icons/swords?style=solid
