### ISSUE TITLE
use.fontawesome.com is down

### ISSUE THREAD

**Issue by Jfairfield1** [FortAwesome/Font-Awesome#14492]
My cdn link doesn't seem to be working right now:
https://use.fontawesome.com/releases/v5.3.0/css/all.css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@Jfairfield1 could you please provide more details about your country and connection?

Here in Italy (EU) everything is fine

**Comment by Jfairfield1** [comment]
I'm in the Western United States (Arizona)

**Comment by Jfairfield1** [comment]
Working again...

**Comment by tagliala** [comment]
Thanks
