### ISSUE TITLE
Icon request: icon-sinewave, icon-squarewave, icon-traingularwave

### ISSUE THREAD

**Issue by BSTomack** [FortAwesome/Font-Awesome#14508]
### What can it be used for?

There are obvious mathematical application uses for these 

### Example image (optional)

![sine-wave-symbol](https://user-images.githubusercontent.com/32340243/51286649-109ad880-19b1-11e9-95c5-01d4c65a8692.jpg)

**Comment by BSTomack** [comment]
might be a duplicate with #8815

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, this may be a superset of #8815

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/wave-triangle?style=solid
https://fontawesome.com/icons/wave-square?style=solid
https://fontawesome.com/icons/wave-sine?style=solid
