### ISSUE TITLE
Backward compatibility with FA4: Tasks Icon (Icon Request: FA4 icon-tasks) 

### ISSUE THREAD

**Issue by gooeyideas** [FortAwesome/Font-Awesome#14503]
Hello,

I made this issue in the fontawesome-pro repo but it does not appear that the issues there are being monitored as well as the ones here so I am re-posting here. I hope that is OK.

The tasks icon is different in FA5 than it is in FA4. 
![image](https://user-images.githubusercontent.com/6644447/46315777-f4a33080-c593-11e8-836d-6b19117e395d.png)

While I like the new icon much better for a simple checklist, the old icon was actually better for scheduled tasks, programmable function tasks, and other more technical interfaces that represent a sequence of events rather than a "to-do" list. Not having an alternative for the old icon is a breaking change in my opinion. 

Is there any way to get the FA$ icon-tasks as a tasks-alt icon in FA5?

**Comment by sensibleworld** [comment]
Thanks, @gooeyideas. We'll get the old icon added into FA5 as `tasks-alt`. Stay tuned!

**Comment by sensibleworld** [comment]
Thanks for the suggestion! We've added a `tasks-alt` icon to the latest Font Awesome Pro release: https://fontawesome.com/icons/tasks-alt?style=solid
