### ISSUE TITLE
Icon request:  arrow-merge / arrow-split

### ISSUE THREAD

**Issue by passionatelogic** [FortAwesome/Font-Awesome#14500]
### What can it be used for?

Issue #1089 (et al) was closed due to [code-merge](https://fontawesome.com/icons/code-merge?style=solid) and [code-branch](https://fontawesome.com/icons/code-branch?style=solid) being added to FA5, but the code-merge concept is very different from the arrow-centric icon examples provided where two equal sized lines merge into a single arrow, or one line splits into two arrows.

Arrows merging together provide a much clearer indication of merging two things (outside of coding/git usage), and can be used for things like merging records, transport-related directions (could be stacked on sign-shaped icons), and arrow-based diagram-related or logic tasks.

This also helps round out FA's arrow collection. Variations of this include spliting to the side (think highway exit sign's arrows) or merging in from the side (like highway merge lane signs).

### Example image (optional)
Main arrows:
![Arrows](https://cl.ly/28b87dd78360/Image%2525202019-01-14%252520at%2525202.28.17%252520PM.png)

Side variations:
![Variations](https://cl.ly/ffda71423505/Image%2525202019-01-14%252520at%2525202.27.18%252520PM.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by nicolasbadia** [comment]
This arrow-merge icon would be great for a deduplication feature

**Comment by kidalynch** [comment]
would love to see this live.

**Comment by kareem** [comment]
+1 for a merge icon (opposite of the split icon).
<img width="309" alt="Font Awesome 2022-02-23 19-30-11" src="https://user-images.githubusercontent.com/26123/155427113-309875ab-4ffd-4192-9499-3c27ee5b5edb.png">

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/merge?s=solid
