### ISSUE TITLE
Update Slack icon

### ISSUE THREAD

**Issue by mattonit** [FortAwesome/Font-Awesome#14510]
Today, Slack changed its logo so I think you should update the slack icon too. Here's the new logo:
![slack-new](https://user-images.githubusercontent.com/4998725/51313627-50fc6400-1a4e-11e9-8cbe-7c40cc0bfe67.jpg)

and [here's](https://twitter.com/SlackHQ/status/1085609385542459393) the confirmation that the logo has changed

**Comment by tagliala** [comment]
This has been already done by @talbs.

It will be released in the next version of Font Awesome

**Comment by talbs** [comment]
Hey, gang. We've got that new Slack brand icon all set for you in version `5.7.0` - https://fontawesome.com/icons/slack?style=brands. 😄
