### ISSUE TITLE
Icon-request: icon-ukr-hrivnya (ukranian currency)

### ISSUE THREAD

**Issue by HomaEEE** [FortAwesome/Font-Awesome#1451]
Please, add icon of ukrainian hrivnya with rouble in next update 
![urk](https://camo.githubusercontent.com/7568421c3fedf3ffd4a7abff40f16325def4360a/68747470733a2f2f63646e332e69636f6e66696e6465722e636f6d2f646174612f69636f6e732f63757272656e63792d322f3436302f556b7261696e652d487279766e69612d3132382e706e67)

**Comment by AndrewEastwood** [comment]
Hey @davegandy! how's it going?

**Comment by krekoten** [comment]
+1

**Comment by pokutnik** [comment]
:+1:

**Comment by atermenji** [comment]
:+1:

**Comment by fester** [comment]
+1

**Comment by virtax** [comment]
+2

**Comment by animatio** [comment]
+1

**Comment by ktaras** [comment]
:+1:

**Comment by reneval** [comment]
+1

**Comment by eugene-rozov** [comment]
+1

**Comment by Romix1994** [comment]
+1

**Comment by alexander-semikin** [comment]
+1

**Comment by vladislavmega** [comment]
+1

**Comment by the-valan** [comment]
+1

**Comment by rocknrollskyoveryou** [comment]
+1

**Comment by Vitalii2103** [comment]
+1

**Comment by z4y4ts** [comment]
+1

**Comment by anatol-s** [comment]
+1

**Comment by beliys** [comment]
+1

**Comment by margeslt** [comment]
+1

**Comment by nixegend** [comment]
+1

**Comment by vaso2** [comment]
+1

**Comment by AndrewEastwood** [comment]
+1

**Comment by MishaSavchak** [comment]
+1

**Comment by vbartkiv** [comment]
+1

**Comment by skuzmin** [comment]
+1

**Comment by kuzbida** [comment]
+1

**Comment by marko-zub** [comment]
+1

**Comment by sector119** [comment]
+1

**Comment by Roger-Waters** [comment]
+1

**Comment by Tempys** [comment]
+1

**Comment by premgrem** [comment]
+1

**Comment by SHooZ** [comment]
+1

**Comment by romaslmd** [comment]
👍

**Comment by stevenReed** [comment]
+

**Comment by svyatoslav-kubakh** [comment]
+1

**Comment by stevenReed** [comment]
+1

**Comment by frozeder** [comment]
+1

**Comment by IgorDobryn** [comment]
+1

**Comment by straybro** [comment]
It's approaching 3 years now. I'm beginning to think the ISSUE has been LOST.

**Comment by AndrewEastwood** [comment]
seems that author of this lib totally doesn't care. Am I right, @davegandy ?

**Comment by andrelinoge** [comment]
+1

**Comment by aerobium** [comment]
+1

**Comment by playka** [comment]
+1

**Comment by playka** [comment]
without circle

**Comment by firec0der** [comment]
+1

**Comment by Bad-Company** [comment]
+1

**Comment by firec0der** [comment]
Sorry guys. But according to our laws, the correct transliteration will be: **hryvnia**
Here is the mentioned law (in Ukrainian): [click me](http://zakon5.rada.gov.ua/laws/show/55-2010-%D0%BF)

**Comment by igor0ser** [comment]
+1

**Comment by RadoAz** [comment]
+1

**Comment by ashilay** [comment]
+1

**Comment by firec0der** [comment]
Hey, @tagliala! Maybe you can help us.

**Comment by HelenaSha** [comment]
+1

**Comment by borys-ihnatyev** [comment]
+1

**Comment by AtticusFetch** [comment]
+1

**Comment by disist** [comment]
+1

**Comment by blackswanny** [comment]
+1

**Comment by alexshenia** [comment]
+1

**Comment by watjs** [comment]
+1

**Comment by sdwvit** [comment]
+1️⃣

**Comment by melnykova** [comment]
+1

**Comment by Alimova** [comment]
+1

**Comment by sergsagan** [comment]
+1

**Comment by vskochko** [comment]
+1

**Comment by vovan211** [comment]
+1

**Comment by denysdovhan** [comment]
+1

**Comment by artdevjs** [comment]
+1

**Comment by Kilmyashkin** [comment]
+1

**Comment by Luceafarul** [comment]
+1

**Comment by Ne4istb** [comment]
+1

**Comment by AndriySikora** [comment]
+1

**Comment by ta-ni** [comment]
+1

**Comment by webknjaz** [comment]
+1

**Comment by cleac** [comment]
+1

**Comment by creageek** [comment]
+1

**Comment by dmitriyminer** [comment]
+1

**Comment by brain2dump** [comment]
Hi. What happened? What a growing interest in the icon of the hryvnia?
P.S.: Some years subscribe to this topic, but hight activities never seen before.

**Comment by webknjaz** [comment]
@brain2dump someone noticed that `hryvnia` name isn't transliterated correctly in this topic's description and title, posted that on the Facebook and it's got viral :)

FWIW there are lot's of Ukrainians using `font awesome`, so it's natural that we want our currency supported.

![](https://s-media-cache-ak0.pinimg.com/236x/7e/ff/1f/7eff1fa4c0c9689ebcb4a8a6d16a8560.jpg)

**Comment by z4y4ts** [comment]
Alright folks, we're getting some attention. Any chance we have someone who can create a Hryvna glyph?

**Comment by devslava** [comment]
+1

**Comment by zaccharles** [comment]
+1

**Comment by webknjaz** [comment]
@z4y4ts I'll ask @Suzzy for help. 
/cc: @rynarud

**Comment by AMashoshyna** [comment]
+1

**Comment by webknjaz** [comment]
@HomaEEE?

**Comment by NazarH** [comment]
+1

**Comment by Tempys** [comment]
+1

**Comment by GitVVV** [comment]
+1

>150 + . Four years. Obviously, the request is ignored intentionally. Why?

**Comment by zelds** [comment]
1+

**Comment by BOTKooper** [comment]
+1

**Comment by BOTKooper** [comment]
Hey, Font-Awesome, Ukraine is country with 40 millions people add their currency's icon please

**Comment by olexam** [comment]
+1

**Comment by vaso2** [comment]
Hi there! What about this Icon Request? By comments and thumbups this will easily rise to the top of [Icon Leaderbord](https://fontawesome.com/community/leaderboard/new)

**Comment by webknjaz** [comment]
ping @tagliala

**Comment by tagliala** [comment]
I'm going to reopen here to preserve upvotes.

@HomaEEE please ignore notifications if you are no more interested in this request, it will help others.

If you close this request again, I have no other chance of locking here and start again with a new request

**PS: in order to avoid spam, use reactions, do not comment with +1s**

**Comment by sensibleworld** [comment]
Released in 5.4: 
https://fontawesome.com/icons/hryvnia?style=solid

**Comment by brain2dump** [comment]
Аlleluia!
Я джва года ждал…

**Comment by Tempys** [comment]
+
