### ISSUE TITLE
Icon request: Meeple icon 

### ISSUE THREAD

**Issue by Sunthief** [FortAwesome/Font-Awesome#14523]
It's a gross oversight to not include the typical Meeple icon into Font Awesome. What would be more awesome?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4843, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
