### ISSUE TITLE
Icon Request: China Brand Icon

### ISSUE THREAD

**Issue by weihongyu12** [FortAwesome/Font-Awesome#14530]
In China, there are many large Internet companies, they have a wide range of influence, but in the brand directory, they do not have their icons, which makes it inconvenient for us to develop.

I have roughly sorted out the issue, and some of them are about Chinese brands. I think I can concentrate on them. The related issues are as follows:

alibaba #3855 E-commerce Company
taobao #3856 E-commerce Website
tmall #11395 E-commerce Website
unionpay #4561 Bank Card Issuer
weixin-work #13148 Enterprise Collaboration Platform
weixin-mini-programs #13143
weixin-pay #11069 Mobile Payment
weixin-moments #9835 Social
youku #3487 Video Site
bilibili #9789 Video Site
baidu #5380 Search Engine
dingtalk #14310 Enterprise Collaboration Platform

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for this list, but I cannot leave this open because it doesn't meet our contributing guidelines.

Please add a 👍 reaction to each one of those requests

Closing here

**Comment by avokhmin** [comment]
> Please add a 👍 reaction to each one of those requests

@tagliala https://github.com/FortAwesome/Font-Awesome/issues/3487 - 38 👍
