### ISSUE TITLE
Icon Request: icon-folder-add, icon-folder-up, icon-align-remove, icon-pain-bucket, icon-align-top, icon-align-middle, icon-align-bottom

### ISSUE THREAD

**Issue by sboisse** [FortAwesome/Font-Awesome#1453]
As a suggestion, see the icons in the following image: http://cdn.kendostatic.com/2013.1.514/styles/Default/sprite.png

Folder add and folder remove are useful in a UI where the user can browse around in a folder hierarchy.

Align-remove is useful for clearing align formatting in a rich text editor.

Paint-bucket is useful in a rich text editor UI for setting the background color of text.

align top, middle and bottom are also useful in an editor for aligning things.

**Comment by tagliala** [comment]
Hi

Unfortunately, I cannot leave this issue open anymore because it does not meet our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
