### ISSUE TITLE
Icon Request: fa-3d-force-layout

### ISSUE THREAD

**Issue by mmcsivakumar** [FortAwesome/Font-Awesome#14547]
Hi Team,

We have an one screen which displays 3D force layout graph (ThreeJS) and i need the icon to display the same in the tab. 

Please suggest/create any icon combined with Cloud + 3D + force layout network graph.

Many thanks in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example of the icon you need?
