### ISSUE TITLE
Icon request: icon-stocking

### ISSUE THREAD

**Issue by endodoug** [FortAwesome/Font-Awesome#1454]
I could use a stocking for a general stocking stuffer category or to highlight items that make good stocking stuffers.  Any site that advertises christmas items or sales could make use of it.  
![stocking](https://f.cloud.github.com/assets/3649119/725050/118cbdc8-e049-11e2-8669-2de2863db455.png)

Actually a christmas category might be useful, maybe a little santa hat or tree.  

Thanks

**Comment by Wingo5315** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/stocking?style=solid
