### ISSUE TITLE
icon request: fa-flag-eu

### ISSUE THREAD

**Issue by forcequit** [FortAwesome/Font-Awesome#14542]
Provide a flag for the EU and each EU country.  
You already have this for the US:
fas fa-flag-usa

EU &#x1F1EA;&#x1F1FA;

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I have to close this one for the moment.

Ref: #4735, #10258, #6193, #1336, and others

> But there is a USA flag!

Yes, I know.

**Comment by tagliala** [comment]
Reopened #9520, please use that request
