### ISSUE TITLE
Search for import/export returns wrong icon

### ISSUE THREAD

**Issue by Ugoku** [FortAwesome/Font-Awesome#14540]
### Describe the problem
* Go to https://fontawesome.com/icons?d=gallery
* Search for "export" and/or "import" (without quotes)

For "export", it also shows the "upload" icon, and for "import" it shows the "download" icon.

### What did you expect?
These should be the other way around: "download" for "export" and "upload" for "import"

### What version and implementation are you using?
N/A

### Reproducible test case
* https://fontawesome.com/icons?d=gallery&q=import
* https://fontawesome.com/icons?d=gallery&q=export

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

@talbs could you please take a look at search terms?

- export term should match *-download actions (or both)
- import term should match *-upload actions (or both)

![image](https://user-images.githubusercontent.com/556268/51603933-864ff880-1f0b-11e9-9db0-5fe554691fb4.png)

![image](https://user-images.githubusercontent.com/556268/51603955-923bba80-1f0b-11e9-8001-ecffe2151d2e.png)

**Comment by talbs** [comment]
Roger that, @tagliala and @Ugoku. Thanks for the heads up on this issue. I've got a PR in our build system to fix this right up and it should be shipped with our next release. Expect that shortly. 😄 

Please keep the good feedback coming!

**Comment by Ugoku** [comment]
Awesome! Great to see such a large project look at this so soon :) thanks for the upcoming fix and thanks for FA!

**Comment by talbs** [comment]
Thanks for the great feedback, @Ugoku. We just released `5.7.0` and with it those search improvements. Check out https://fontawesome.com/icons?d=gallery&q=import and https://fontawesome.com/icons?d=gallery&q=export. They should reflect the good fix you suggested.

Let us know if you run into any more trouble and please keep the good input coming. 😄
