### ISSUE TITLE
Icon request - fa-misc-miscellaneous

### ISSUE THREAD

**Issue by PsySc0rpi0n** [FortAwesome/Font-Awesome#14549]
Is it possible to add a free MISC/MISCELLANEOUS icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example and fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) ?

It is hard to understand how a "fa-misc-miscellaneous" icon should look like

**Comment by PsySc0rpi0n** [comment]
Already filled the template here:
https://github.com/FortAwesome/Font-Awesome/issues/14560

Thanks
Psy
