### ISSUE TITLE
Icon: coins desktop

### ISSUE THREAD

**Issue by vbach** [FortAwesome/Font-Awesome#14553]
### Describe the problem

Desktop font not working as intended. Specifically the coins icon when used  is not working. Tried it in Adobe XD, Illustrator, and a word doc. 

### What did you expect?

For 'coins' to change to its respective icon using Font Awesome 5 Free - Solid

### What version and implementation are you using?

Version: 5.6.3
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

### Reproducible test case

N/A

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by vbach** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Could you please edit this request and fill out this [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Done!

**Comment by tagliala** [comment]
I do not use XD / Illustrator. Specifying your OS will help

Could you please try the following:

1. Uninstall Font Awesome
2. Restart your machine
3. Download from https://github.com/FortAwesome/Font-Awesome/releases/download/5.6.3/fontawesome-free-5.6.3-desktop.zip
4. Install `otf` files
5. Try again, having care of selecting **Solid** from font-style dropdown

This is an example in macOS Pages (please note "Solid")
![image](https://user-images.githubusercontent.com/556268/51827248-36957680-22e9-11e9-8b6a-7f8be25ff87c.png)

**Comment by vbach** [comment]
Deleting the font and reinstalling it worked. Thank you.
