### ISSUE TITLE
Entire index.es.js being included in production bundle

### ISSUE THREAD

**Issue by mattoni** [FortAwesome/Font-Awesome#14552]
Hi, I'm doing a production build with webpack 4, and it looks like the entire index.es.js is being included in my compiled version, despite explicitly using the proper es import syntax, i.e. `import { faSearch } from "@fortawesome/pro-solid-svg-icons";`

Might also be important to note that I'm using Typescript, with the following module settings:

```
{
    "compilerOptions": {
        "module": "esnext",
        "strict": true,
        "target": "es6",
        "outDir": "dist",
        "noImplicitReturns": true,
        "sourceMap": true,
        "pretty": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "removeComments": false,
        "suppressImplicitAnyIndexErrors": true,
        "experimentalDecorators": true,
        "baseUrl": "./src",
        "moduleResolution": "node",
        "jsx": "react",
        "noEmitHelpers": true,
        "importHelpers": true,
        "lib": [
            "dom",
            "es6"
        ],
        "paths": {
            "__mocks__/*": [
                "../__mocks__/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "fuse.ts"
    ]
}
```

![image](https://user-images.githubusercontent.com/5110855/51792955-d5956380-216d-11e9-8ecb-a780540f6819.png)

Production webpack settings: 
```
const merge = require("webpack-merge");
const common = require("./webpack.common.js");

const BundleAnalyzerPlugin = require("webpack-bundle-analyzer")
  .BundleAnalyzerPlugin;

module.exports = env =>
  merge(common(env), {
    mode: "production",
    optimization: {
      splitChunks: {
        cacheGroups: {
          default: false,
          commons: {
            test: /[\\/]node_modules[\\/]/,
            name: "vendor_app",
            chunks: "all",
            minChunks: 2,
          },
        },
      },
    },
    plugins: [new BundleAnalyzerPlugin()],
  });
```

Versions:  
```
    "webpack": "^4.28.4",
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.6.3",
    "@fortawesome/pro-solid-svg-icons": "^5.6.3",
    "@fortawesome/react-fontawesome": "^0.1.4",
```

Let me know if you need anything else from this, but I'm hoping someone can shed some light for me.
Thanks so much!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but I cannot help on this.

Does https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking help?

Also, I think that "@fortawesome/fontawesome": "^1.1.8" is not required anymore, please take a look here: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#no-more-default-imports

Can you provide a reduced test case and host it on github? It will speed up things if there is an issue

Let's also wait for feedback from the community

**Comment by mattoni** [comment]
Hi,

I followed the tree shaking stuff initially and it says no extra config is needed for standard webpack stuff which is why it's confusing that it's pulling it in this way. I removed the extra lib, thanks for that info. I'll try and get a test around but I'm under some strict deadlines and I doubt I'll have time soon. 

Thanks again.

**Comment by tagliala** [comment]
> I followed the tree shaking stuff initially and it says no extra config is needed for standard webpack stuff 

That is true, I'm getting tree-shaking built-in in my Webpack 4 project, but I'm not using Typescript

> I'll try and get a test around but I'm under some strict deadlines and I doubt I'll have time soon.

Feel free to provide at your convenience a test case with the minimum amount of code (including full package.json, webpack configuration files, etc.) needed to reproduce your issue. I will take a look and escalate it as soon as I'm able to reproduce.

If someone else in the community is experiencing this issue, please let me know

**Comment by piernik** [comment]
I have the same problem - tree shaking is not working.
I'm using angular so typescript and `@fortawesome/angular-fontawesome`
I've made tests with only one icon:
```
import {faCircle} from '@fortawesome/pro-solid-svg-icons';
import {dom, library} from '@fortawesome/fontawesome-svg-core';

library.add(faCircle);
dom.watch();
```
And as a result I have >1MB in bundle:
![fa](https://user-images.githubusercontent.com/420691/53327208-ead5ed00-38e7-11e9-9795-3001cf6ab50d.png)

**Comment by piernik** [comment]
I changed import method to:
```
import {faCircle} from '@fortawesome/pro-solid-svg-icons/faCircle';
import {dom, library} from '@fortawesome/fontawesome-svg-core';

library.add(faCircle);
dom.watch();
```
and now it's working:
![fa2](https://user-images.githubusercontent.com/420691/53327657-88312100-38e8-11e9-9cd3-69d8c51c5d48.png)

Should we use `import {faCircle} from '@fortawesome/pro-solid-svg-icons/faCircle';` inseatd of `import {faCircle} from '@fortawesome/pro-solid-svg-icons';` ?

**Comment by tagliala** [comment]
Could you please provide a repository replicating this issue?

**Comment by piernik** [comment]
Well not exactly since I'm using pro version.
But it is very easy to reconstruct. with angular cli start a new project install:
```
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.13",
    "@fortawesome/pro-solid-svg-icons": "^5.7.0",
```

Import `FontAwesomeModule` to `AppModule` and in `app.component` import and use icons.

**Comment by tagliala** [comment]
@piernik not an angular developer here

Could you please provide a step-by-step tutorial?

Also, I do not know how to generate the above map to check sizes

**Comment by piernik** [comment]
I dived into fa docs and I think it's known issue:
https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking#production-mode

It wille be tree shaken in production. Well I changed import method to exact icon files so it's ok for me.

**Comment by mattoni** [comment]
Just to be clear, my issue IS happening in production builds.

**Comment by alflennik** [comment]
Here is a repro repository with parcel, another tool where this is happening:

https://github.com/alflennik/parcel-fontawesome-tree-shaking-repro

This is being tracked on the [Parcel issues page](https://github.com/parcel-bundler/parcel/issues/1664) as well, but if this is being reported with Webpack as well, it must be an issue with FontAwesome, not Parcel.

**Comment by andyrichardson** [comment]
While I'm sure explicitly importing files works, it's not really tree shaking (dead code elimination). It would be nice to have tree shaking support (e.g. `import { faCoffee } from '@fortawesome/free-solid-svg-icons';` would only include _faCoffee_ in the bundle).

Assuming the font packages are side-effect free (which they look to be), adding `sideEffects: false` to the _package.json_ will let webpack know that it is safe to ignore code that is not being imported (and allows for tree shaking).

There's more information about [adding tree shaking support here](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free).

**Comment by seanzi86** [comment]
Did anyone manage to come up with a solution without using deep imports?

**Comment by briangonzalezmia** [comment]
@andyrichardson Thanks! While not pretty (and not really tree shaking) it is effective.  I'll stick to this method for now.

**Comment by a-martynovich** [comment]
When I add `"sideEffects": false` to package.json in `@fortawesome/free-solid-svg-icons` tree-shaking works well, as well as the icons themselves. This seems like a great solution.

**Comment by tagliala** [comment]
Thanks @a-martynovich!

Are there side effects in adding `"sideEffects": false` ?

**Comment by a-martynovich** [comment]
@tagliala Not that I know of. It works for my use case (I'm using only webpack and JavaScript). And as @andyrichardson said, the packages look side-effect free.

**Comment by tagliala** [comment]
I'm not an expert node developer. I know about the sideEffect property, I've also tried to study that but I didn't understand it properly and I just have a guess of what it means, so sorry if I can't help

Let's ask to @mlwilkerson or @robmadole if they could help here

**Comment by robmadole** [comment]
I think we could probably set `sideEffects` to `false` for the SVG icon packages. I'll get this added to 5.12.0.

**Comment by robmadole** [comment]
5.12.0 is out. Please let me know if this helps.

**Comment by a-martynovich** [comment]
Unfortunately this does not help. I've just installed 5.12.0 and I'm getting the same issue. Here's my "big" bundle which gets 2MB+:
```
import {dom, library} from '@fortawesome/fontawesome-svg-core'

import {faBan, faCheckCircle, faCopy, faCheck, faQuestionCircle, faExclamationCircle, faEdit, faSave, faEye, faInfoCircle} from '@fortawesome/free-solid-svg-icons'
import {faGithub} from '@fortawesome/free-brands-svg-icons'
import {faSquare, faCheckSquare} from '@fortawesome/free-regular-svg-icons'


library.add([
    faBan,
    faCheck,
    faCheckCircle,
    faCheckSquare,
    faCopy,
    faEdit,
    faExclamationCircle,
    faEye,
    faGithub,
    faInfoCircle,
    faQuestionCircle,
    faSave,
    faSquare
]);
dom.watch();
```

And here's my "small" bundle which is 2x smaller:
```
import {dom, library} from '@fortawesome/fontawesome-svg-core'
import {faBan} from '@fortawesome/free-solid-svg-icons/faBan'
import {faCheckCircle} from '@fortawesome/free-solid-svg-icons/faCheckCircle'
import {faSquare} from '@fortawesome/free-regular-svg-icons/faSquare'
import {faCheckSquare} from '@fortawesome/free-regular-svg-icons/faCheckSquare'
import {faCopy} from '@fortawesome/free-solid-svg-icons/faCopy'
import {faCheck} from '@fortawesome/free-solid-svg-icons/faCheck'
import {faGithub} from '@fortawesome/free-brands-svg-icons/faGithub'
import {faQuestionCircle} from '@fortawesome/free-solid-svg-icons/faQuestionCircle'
import {faExclamationCircle} from '@fortawesome/free-solid-svg-icons/faExclamationCircle'
import {faEdit} from '@fortawesome/free-solid-svg-icons/faEdit'
import {faSave} from '@fortawesome/free-solid-svg-icons/faSave'
import {faEye} from '@fortawesome/free-solid-svg-icons/faEye'
import {faInfoCircle} from '@fortawesome/free-solid-svg-icons/faInfoCircle'


library.add([
    faBan,
    faCheck,
    faCheckCircle,
    faCheckSquare,
    faCopy,
    faEdit,
    faExclamationCircle,
    faEye,
    faGithub,
    faInfoCircle,
    faQuestionCircle,
    faSave,
    faSquare
]);
dom.watch();

```

**Comment by crowlKats** [comment]
been trying to get tree shaking to work with fontawesome in my react project, but it isnt working at all... [here](https://gist.github.com/crowlKats/ebe7fe8264207513025f0064a4bb5194) is my config. i get the whole index.es.js bundle, which is basically 2/3 of my project bundle size

**Comment by robmadole** [comment]
@crowlKats if you can provide a more complete example (with all the files needed to try the build) we'll take a look!

**Comment by crowlKats** [comment]
@robmadole due to the fact that it is a project for a business, i cant show the full project source code, so i took away as much as possible unrelated code to the issue. [Here is a bare-bones repo i just made from the relevant files for this problem](https://github.com/crowlKats/react-project-fontawesome-problem-barebones) (of course i checked if the issue still occurs and it indeed does). i hope this helps.

**Comment by crowlKats** [comment]
> @robmadole due to the fact that it is a project for a business, i cant show the full project source code, so i took away as much as possible unrelated code to the issue. [Here is a bare-bones repo i just made from the relevant files for this problem](https://github.com/crowlKats/react-project-fontawesome-problem-barebones) (of course i checked if the issue still occurs and it indeed does). i hope this helps.

actually to make this easier: [here](https://github.com/crowlKats/react-fontawesome-barebones) i made a react project with just using fontawesome to prove that tree shaking isnt working with fontawesome, but included also a bit of `lodash-es` to prove that tree shaking indeed works in the project

**Comment by rkovalyov** [comment]
@crowlKats have the same issue with my webpack config, threeshaking doesnt work with "@fortawesome/pro-light-svg-icons": "5.12.1",

**Comment by robmadole** [comment]
@crowlKats the `fortawesome` chunk is 31.8K. Tree-shaking is working and only the 3 icons you included are being bundled. What am I missing?

**Comment by rkovalyov** [comment]
@crowlKats treeshaking works well, I was also confused with webpack-bundle-analyzer.
`stats size` -  the size of the chunk before Webpack has performed any magic on it.
You need check  `parsed size`.

**Comment by tagliala** [comment]
I'm going to close here, since the sideEffects option has been added in FA 5.12.0

If someone is still experiencing issues, please open a new thread and provide a reproducible test case

**Comment by neoncube2** [comment]
(For anyone running across this issue, it's basically a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/18020, which has some good information in it)
