### ISSUE TITLE
CDN HTML link: `Crossorigin` instead of `crossorigin`?

### ISSUE THREAD

**Issue by patientplatypus** [FortAwesome/Font-Awesome#14559]
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">`

should be 

`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" Crossorigin="anonymous">` (capitalize C in Crossorigin)

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

As far as I know, [attributes are case-insensitive](https://www.w3.org/TR/html5/syntax.html#elements-attributes)

and [`crossorigin` is both valid and correctly written in lowercase](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-crossorigin)

**Comment by patientplatypus** [comment]
Hmm...I was getting a compile error in Next.js, but can't reproduce. Thank you for your timely response. Closing.

**Comment by patientplatypus** [comment]
Woops - here is the issue coming in Next.js
In terminal - 
```
 DONE  Compiled successfully in 2662ms                                                                                                                                                                                           11:42:46 AM

> Ready on http://localhost:3000
Warning: Invalid DOM property `crossorigin`. Did you mean `crossOrigin`?
    in link (at _document.js:9)
    in head
    in Head (at _document.js:8)
    in html (at _document.js:7)
    in MyDocument
```
In code - 
```
import Document, { Head, Main, NextScript } from 'next/document'

export default class MyDocument extends Document {
  render () {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"/>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```
This is a minor issue and easily fixed (from a dev standpt), but it is strange.

**Comment by tagliala** [comment]
Ok, thanks.

It is clearer to me now, mystery solved.

As far as I understand `Next.js` (which I do not use and I do not know) seems to use JSX templates. I can also see `onclik` [written as `onClick`](https://nextjs.org/docs/#imperatively)

> Warning:
Since JSX is closer to JavaScript than to HTML, React DOM uses camelCase property naming convention instead of HTML attribute names.
For example, `class` becomes `className` in JSX, and `tabindex` becomes `tabIndex`.

So, `crossorigin` => `crossOrigin`

Ref: https://reactjs.org/docs/introducing-jsx.html#specifying-attributes-with-jsx
