### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by PsySc0rpi0n** [FortAwesome/Font-Awesome#14560]
### What can it be used for?
To represent several things that might not be included in any other categories. It's a category to use for uncategorised items. Miscellaneous stuff.

In a torrent site, for example, there are many items that have no category. This would be to include those items.

### Example image (optional)
I don't have any example icon

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
Single Icon
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
Not sure wha this means

- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
yes

- [ ] I have included at least one example image if it could be helpful (optional)
No

- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
Not really. It's supposed to represent several things

**Comment by tagliala** [comment]
@PsySc0rpi0n 
> Not sure wha this means
Please edit the title of this request. Remove `name` and use the name that this icon should have in the set


>  I have included at least one example image if it could be helpful (optional)
I know that an example is optional, but ...

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
It

**Comment by tagliala** [comment]
We have a couple of icons that could fid this use case:
- https://fontawesome.com/icons/shapes?style=solid
- https://fontawesome.com/icons/box-full?style=solid (PRO)

**Comment by aethior** [comment]
@tagliala I think you can close here.
