### ISSUE TITLE
npm install fails, @fortawesome/fontawesome-common-types@^0.2.13

### ISSUE THREAD

**Issue by LegendAF** [FortAwesome/Font-Awesome#14563]
When I run `npm install` in my project that has `fontawesome-svg-core` inside of it, the install fails. 

Here is the output:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @fortawesome/fontawesome-common-types@^0.2.13
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@fortawesome/fontawesome-svg-core'
npm ERR! notarget
```

It looks like [v0.2.13](https://www.npmjs.com/package/@fortawesome/fontawesome-common-types) was published an hour ago. What am I doing wrong?

**Comment by allenh** [comment]
Having the same problem.
On the npm registry fortawesome/fontawesome-common-types@^0.2.13 is there in the versions but when running `npm view @fortawesome/fontawesome-common-types` latest is tagged with 0.2.12

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

I'm having the same issue for `@fortawesome/fontawesome-svg-core`

```
$ yarn outdated
yarn outdated v1.13.0
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package                            Current Wanted Latest Package Type URL                    
@fortawesome/fontawesome-svg-core  1.2.12  1.2.13 1.2.13 dependencies https://fontawesome.com
@fortawesome/free-brands-svg-icons 5.6.3   5.7.0  5.7.0  dependencies https://fontawesome.com
@fortawesome/free-solid-svg-icons  5.6.3   5.7.0  5.7.0  dependencies https://fontawesome.com
✨  Done in 1.94s.

$ yarn install
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
Couldn't find any versions for "@fortawesome/fontawesome-svg-core" that matches "^1.2.13"
```

Let's wait a little bit

**Comment by robmadole** [comment]
@LegendAF @allenh @tagliala I wonder if NPM was behind. Can you install now? I'm showing the packages are available now.

**Comment by allenh** [comment]
@robmadole I just tried installing the package (`@fortawesome/fontawesome-svg-core@1.2.13`) and it seems to be working now.

**Comment by robmadole** [comment]
Ok, I think it's good. If we still have issues I'll re-open this.

**Comment by tagliala** [comment]
Just checked, it is good for me too here in Europe

**Comment by maxguzenski** [comment]
I'm having this issue right now... :( I cant deploy my app.

**Comment by robmadole** [comment]
@maxguzenski send an email to hello@fontawesome.com please

**Comment by maxguzenski** [comment]
@robmadole I fixed, I have pro fontawesome icons and I see now that docs changes the way of write .npmrc file
