### ISSUE TITLE
Remove slack-hash Brand Icon

### ISSUE THREAD

**Issue by talbs** [FortAwesome/Font-Awesome#14568]
### Describe the problem

[Slack has rebranded](https://slackhq.com/say-hello-new-logo). Font Awesome has updated the `slack`brand  icon (https://fontawesome.com/icons/slack) with the new version of the logo, but there's also the `slack-hash` brand icon (https://fontawesome.com/icons/slack-hash) that isolated the now unofficial hashtag symbol of the old brand icon for easier styling/placement. 

**That icon should be removed as well to adhere to the updated [brand standards of Slack](https://slack.com/media-kit).**

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by Japangeek** [comment]
Perhaps rotate it to 0° degree and call it as fa-hash-alt since I like this hash. It look much better than fa-hashtag (https://fontawesome.com/icons/hashtag?style=solid)

**Comment by My1** [comment]
question tho is trademark stuff
