### ISSUE TITLE
fort awesome for React instructions incorrect

### ISSUE THREAD

**Issue by reposman33** [FortAwesome/Font-Awesome#14572]
### Describe the problem

I have an app in React 16.7.0; According to the instructions in https://fontawesome.com/how-to-use/on-the-web/using-with/react I installed the following fort awesome packages:
    "@fortawesome/fontawesome-svg-core": "^1.2.13",
    "@fortawesome/free-solid-svg-icons": "^5.7.0",
    "@fortawesome/react-fontawesome": "^0.1.4",
 I used the igloo icon in a component's  JSX as instructed
But I did not see the icon. Instead in the console an error message for each occurrence was logged:
*Could not find icon
    iconName: "igloo"
    prefix: "fas"*
### What did you expect?
to see the icon

### What version and implementation are you using?

Version: 
Browser and version: 
Chrome 71.0.3578.98
- [ 5.7.0] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case
I install the 3 packages through npm;
I add the following imports in the component where I want to use an icon
- import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
- import { faEdit } from "@fortawesome/free-solid-svg-icons/faEdit";

I use it as below in my JSX:
`<td><FontAwesomeIcon icon={faEdit} /></td>`

Only _then_ the icon shows up. This differs considerably from the instructions.

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Can you provide a reproducible test case using something like codesandbox.io of your original issue?
