### ISSUE TITLE
fas fa-business-time not working for me with FA Pro imported via npm

### ISSUE THREAD

**Issue by smares** [FortAwesome/Font-Awesome#14573]
Hey guys, I came across a problem with "fas fa-business-time" in my project and have no idea why it occurs. Tested with latest Chrome, Firefox and Edge as well as IE 11 and for some weird reason, for that specific glyph, "Arial Black" is used according to the "Rendered Fonts" section in the browser developer tools. I am including Font Awesome 5 Pro via npm and just updated to 5.7.0 after initially observing the problem with 5.6.3. All other icons work fine, including (but not limited to):

- fal fa-info-circle
- fal fa-user-tie
- fal fa-euro-sign
- fal fa-map-marker
- fal fa-envelope
- fal fa-file-pdf
- fal fa-file-signature
- and many more

If I check the styles for the i and i:before elements, there is nothing that overrides the styles from the FA CSS. No clue why that specific glyph is using Arial Black and not the Font Awesome 5 Pro font.

I also tried switching to "fas" and "far" but no luck. I don't have Font Awesome installed on my system as system font.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot reproduce: https://codesandbox.io/s/o84659ok6 (using NPM / FA SVG / React)

Could you please provide a reproducible test case?

Please also specify how you are using Font Awesome

**Comment by smares** [comment]
Any chance you could test with the woff2 version?

**Comment by tagliala** [comment]
Here it is: https://codesandbox.io/s/z67xz5w45m

**Comment by smares** [comment]
Hmm, none of the icons appear to work for me on the last link you posted and I am getting the following errors in the console:

Failed to decode downloaded font: https://z67xz5w45m.codesandbox.io/webfonts/fa-solid-900.woff2
(index):1 OTS parsing error: invalid version tag

**Comment by smares** [comment]
BTW, you can see the page in action here for example: https://www.pressebox.de/stellenangebote

I am currently refactoring the front-end. The woff2 served is https://www.pressebox.de/fonts/fa-light-300.woff2

If you replace one of the icons from that example page with fa-business-time, you'll notice that it doesn't render.

**Comment by tagliala** [comment]
Thanks

I'm pretty confident that the woff2 is not the proper one.

FA 5.6.3's fa-light-300.woff2's size is 157kb

Your .woff2 comes from FA 5.1.1
![image](https://user-images.githubusercontent.com/556268/52017508-d15ba400-24e7-11e9-906c-9584c3acb5de.png)

(I've compared MD5 with the version on the CDN)

Please try with icons added in 5.2.0: https://fontawesome.com/icons?d=gallery&v=5.2.0, they will not work.

Please check your build scripts, there is something going wrong in the asset generation
