### ISSUE TITLE
Icons don't appear on website pages in most cases(sometimes they do) in the new IE11

### ISSUE THREAD

**Issue by a92gerasimov** [FortAwesome/Font-Awesome#14579]
The icons of Font-Awesome don't appear on website pages but sometimes they do randomly after the browser has been restarted.
This happened after the IE11 was updated to:
Version: 11.0.9600.19204
Update Version: 11.0.100(KB4470199)
Everything works in other browsers such as Chrome, Opera etc.

P.S. fontawesome.com website doesn't work in this version of IE11 too.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot check this at the moment, will try later. Let's also wait for feedback from the community

**Comment by LeaTark** [comment]
May be related to #14580

**Comment by tagliala** [comment]
I can confirm that both FA 5.7.0 and the website are not working with IE11 (11.0.105).

Anyway, I do not know if the documentation webiste supports IE11.

**Comment by robmadole** [comment]
I'm on this!

**Comment by robmadole** [comment]
All fixed up.
