### ISSUE TITLE
Icon request: icon-statistics

### ISSUE THREAD

**Issue by ForwardDivision** [FortAwesome/Font-Awesome#14571]
### What can it be used for?

a simple statistical icon

### Example image (optional)

https://cdn0.iconfinder.com/data/icons/web-optimization/507/seo_13-512.png

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does one of the following fit your use case?
![image](https://user-images.githubusercontent.com/556268/51975822-814af600-2483-11e9-83fc-2ca457e642da.png)

We have more in FA Pro
![image](https://user-images.githubusercontent.com/556268/51975840-8dcf4e80-2483-11e9-9227-92c6d61be57d.png)
