### ISSUE TITLE
5.7.0 stopped working in IE11

### ISSUE THREAD

**Issue by LeaTark** [FortAwesome/Font-Awesome#14580]
5.7.0 pro svg with js

Console error in IE11: 'Promise' is undefined - all.min.js (1,3837347)

We've reverted to 5.6.0, which still works in IE11.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Roger that, I can confirm

IE 11.0.105
Win 10 build 1809

**Comment by robmadole** [comment]
We've got a fix for this in our build system. I'll be releasing `5.7.1` to address this issue today.

**Comment by dmcanaveral** [comment]
Pseudos aren't working for me with 5.7.1, can anyone else confirm?

**Comment by tagliala** [comment]
@dmcanaveral sorry, cannot confirm

https://jsfiddle.net/h6m0cbjq/

![image](https://user-images.githubusercontent.com/556268/52154620-01897b00-267f-11e9-8515-ea3951d33b3a.png)

Anyway, if you are experiencing issues with pseudoelements, please open a new issue filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by tagliala** [comment]
@LeaTark this has been fixed for me. I'm going to close here, feel free to comment if this is still an issue
