### ISSUE TITLE
Icon request: 2FA icon

### ISSUE THREAD

**Issue by Botan626** [FortAwesome/Font-Awesome#14582]
### What can it be used for?

It will be used as a button in ASF-ui, standalone interface for ASF.
2FA stands for "Two-factor authentication".
https://github.com/JustArchiNET/ASF-ui/issues/165

### Example image (optional)

![image](https://user-images.githubusercontent.com/28785698/52057122-3c9f8780-2575-11e9-8a7a-52d9c843862d.png)

### Icon request checklist

- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [y] I have included at least one example image if it could be helpful (optional)
- [y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Botan626** [comment]
If you have a better idea for an icon that symbols two factor auth then feel free to suggest it.

**Comment by Joyrex** [comment]
I think this should be used like an indicator (e.g., the LTE/4G indicator on a mobile device, or the "4K" icon on iTunes movies indicating 4K resolution) vs showing on/off or lock/unlock status.

**Comment by nullbio** [comment]
I just came here to request the same thing (a 2fa icon), although I think an image representation would be a better idea (instead of text). I'm sure someone can come up with a creative way to represent the idea of a 6 digit pin, most commonly done through a phone app.

**Comment by Botan626** [comment]
![image](https://user-images.githubusercontent.com/28785698/52118269-f440a200-2626-11e9-82b3-7be2b2786506.png)

**Comment by ajarov** [comment]
I suggest a lock with 2 key-holes.
Example:
![TwoFactorAuth](https://user-images.githubusercontent.com/1832140/54688589-a8758980-4afc-11e9-846b-b7ac9738d154.png)

**Comment by My1** [comment]
@ajarov good idea but not really. a lock with 2 holes is better for the 2 man rule, aka you need 2 different people to do something important or dangerous (like opening the main safe of a bank or whatever can probably be secured with this to prevent one rogue employee from doing bad stuff)

**Comment by acerspyro** [comment]
Hey I found this discussion randomly, what about something like this?

![image](https://user-images.githubusercontent.com/4400999/75789359-8ee24780-5d37-11ea-9710-15eea7a51241.png)

**Comment by Botan626** [comment]
Any progress in creating such icon?

**Comment by Botan626** [comment]
Is it going to be made someday?

**Comment by schappaughc** [comment]
![image](https://user-images.githubusercontent.com/300169/109567092-699f2b00-7aaa-11eb-86fd-5045e5f7bf72.png)

**Comment by schappaughc** [comment]
![image](https://user-images.githubusercontent.com/300169/109567246-ac610300-7aaa-11eb-81d4-45667ea72fac.png)

**Comment by My1** [comment]
@schappaughc I would say I prefer your first icon. the second just says basically use your phone as a key which doesnt have to be 2FA.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
