### ISSUE TITLE
[Feature] minified version of CSS/JS

### ISSUE THREAD

**Issue by RDIL** [FortAwesome/Font-Awesome#14583]
Can we please get a minified version?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have minified versions at https://github.com/FortAwesome/Font-Awesome/tree/master/css and https://github.com/FortAwesome/Font-Awesome/tree/master/js

They are also available in the bundled zip file.

Am I getting this request incorrectly?

**Comment by RDIL** [comment]
Nope, thanks.

**Comment by tagliala** [comment]
You're welcome
