### ISSUE TITLE
font awesome not working with react js v 5.7.0

### ISSUE THREAD

**Issue by Ghost173** [FortAwesome/Font-Awesome#14587]
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">`

i add think link in to index,html 

and this is my code 
```
<div className="social-link">
                    <a href="https://www.google.com" rel="noopener noreferrer" target="_blank">
                    <i className="fa fa-linkdin-square"  aria-hidden="true" />
                    </a>
                </div>
```

those icon are not showing 

**note: earlier i used the same way its working perfect  (link maxcd,...) version  4.7.0**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the syntax and names have changed between FA4 and FA5

> `<i className="fa fa-linkdin-square"  aria-hidden="true" />`

should be

> `<i className="fab fa-linkedin"  aria-hidden="true" />`

Ref:
- https://fontawesome.com/icons/linkedin?style=brands
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

closing here

**Comment by rimer10** [comment]
hey thanks same issue iam also facing 

`<i className="fa fa-envelope" aria-hidden="true" />`

then i realize 
`<i className="fas fa-envelope" aria-hidden="true" />`  this is correct :D thank you guys

**Comment by tagliala** [comment]
Well, 

I've just noticed that the syntax is incorrect.

`<i>` is not a self closing tag.

I've fixed my previous comment

```
<i className="fas fa-envelope" aria-hidden="true"></i>
```
