### ISSUE TITLE
Google PageSpeed Insıghts <link rel=preload> for Font-Awesome

### ISSUE THREAD

**Issue by batustun** [FortAwesome/Font-Awesome#14596]
Hi, There is a problem in my Google PageSpeed Insights.

It say you should use <link rel=preload> for "/wp-content/themes/cenote/assets/webfonts/fa-solid-900.woff2"

How can I do it?

Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> It say you should use for "/wp-content/themes/cenote/assets/webfonts/fa-solid-900.woff2"

That file is hosted on your own server and loaded by the `cenote` theme your website is using.

Please note that we do not provide support for third-party themes/plugins/extensions, and this is a general html question

As a general answer, if theme theme is loading fontawesome like

```html
<link rel="stylesheet" href="fontawesome.css">
```

then, to make Google PageSpeed Insights happy, it should change to

```html
<link rel="preload" href="fontawesome.css" as="style">
```

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

Hope it helps, closing here

**Comment by lad-siddhesh** [comment]
If you are using WordPress platform and facing this issue then check out this article on to [fix preload key request](http://freelancersiddheshlad.com/fix-preload-key-requests-with-fonts-in-wordpress/) 
REF: http://freelancersiddheshlad.com/fix-preload-key-requests-with-fonts-in-wordpress/
