### ISSUE TITLE
icon-circle-blank should have less border thickness in favor of icon-stack feature

### ISSUE THREAD

**Issue by daviedR** [FortAwesome/Font-Awesome#1459]
Font Awesome 3.0 has some new features, one of my favorite is icon stack feature. I have collaborate some icons used as the base, like icon-check, icon-check-empty, icon-circle, and icon-circle-blank. The problem is with the icon-circle-blank. I found the border is too thick, way thicker than the icon-check-empty has. It would be nice if you could reduce its thickness to be more like icon-check-empty has.

![icon-circle-blank](https://f.cloud.github.com/assets/1287713/726117/f542978e-e0d2-11e2-9526-7546c76cf645.jpg)

Thanks!

**Comment by sensibleworld** [comment]
Closing this issue as it relates to an old version of Font Awesome. Let us know with a new issue if you're still experiencing issues. Thanks!

**Comment by tagliala** [comment]
I think this issue has been fixed in FA 5, we have uniform circle and square

https://jsfiddle.net/tagliala/1nyx6efz/15/
