### ISSUE TITLE
Failed to compile Module Not Found

### ISSUE THREAD

**Issue by indiehjaerta** [FortAwesome/Font-Awesome#14603]
I just added React-FontAwesome to my new App created with create-react-app and I get this error:

> ./node_modules/@fortawesome/react-fontawesome/index.es.js
> Module not found: Can't resolve 'D:\Front-End\React-ShopplingList\shopping-list\node_modules\react-scripts\node_modules\babel-loader\lib\index.js' in 'D:\Front-End\React-ShopplingList\shopping-list'

I've done this on past apps and they're compiling

Old app dependencies from package.json:
```
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/react-fontawesome": "^0.1.3",
```

New app dependencies:

```
    "@fortawesome/fontawesome-svg-core": "^1.2.14",
    "@fortawesome/free-solid-svg-icons": "^5.7.1",
    "@fortawesome/react-fontawesome": "^0.1.4",
```

Also a lot of changes in babel files in package-lock.json

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Not a react expert, but I'm not able to replicate with a very simple package.json: https://codesandbox.io/s/o84659ok6

Could you please provide more details about your issue? (you are mentioning `create-react-app`, I never used that. please provide version, npm version, node version and anything else that could be useful to replicate the issue

**Comment by indiehjaerta** [comment]
Updating npm to 6.7.0 seemed to have solved it thanks didn't even think it could be that simple :D

**Comment by tagliala** [comment]
You're welcome, closing here
