### ISSUE TITLE
Icon Request: icon-azn (Azerbaijani manat symbol)

### ISSUE THREAD

**Issue by quickwritereader** [FortAwesome/Font-Awesome#1460]
Hi . Firstly, I want to thank you for this great job . 
I will be happy if you add my country (Azerbaijan) currency icon 
here how it looks like.
http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Azeri_manat_symbol.svg/450px-Azeri_manat_symbol.svg.png
thanks

**Comment by togrul614** [comment]
Hello,
Any news about it? How we can help about it?

**Comment by osmfarid** [comment]
This request was opened almost 5 years ago, but not resolved, is it so difficult?

**Comment by TunayNovruzov** [comment]
This request was opened almost 5 years ago, but not resolved, is it so difficult?

**Comment by kamranata** [comment]
Hi, https://fontawesome.com/support#fa-requests here you typed "Want to request a new icon? Here are some things to keep in mind: Please be nice. Font Awesome is a happy place. Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one."

Ok. You said "Font Awesome is a happy place", but why  you don't want the Azerbaijanis to be happy? :( Please add this symbol

**Comment by quickwritereader** [comment]
Is this issue still relevant? 
Lets use that sign normally and move on
http://www.unicode-symbol.com/u/20BC.html
I want to close the issue.

**Comment by kamranata** [comment]
> Is this issue still relevant?
> Lets use that sign normally and move on
> http://www.unicode-symbol.com/u/20BC.html
> I want to close the issue.

Then please delete dollar sign too. Unicode's manat doesn't supported in other font, that is why we asked fontawesome to add it. I'm sorry, but we are unhappy for now

**Comment by quickwritereader** [comment]
I'm not a designer. imho If you are a designer I would suggest to fork it and add there. Later you could PR too. Maybe they will merge it on main.

**Comment by mirzayev** [comment]
This request was opened almost 6 years ago, but not resolved, is it so difficult?

**Comment by soltancode** [comment]
This request was opened almost 6 years ago, but not resolved, is it so difficult?

**Comment by nicat97** [comment]
I wonder, how can be hard to create a symbol during 6 years? 
Aren't feedbacks important for you?!

**Comment by natiq2004** [comment]
Please add manat symbol. A lot of people are waiting for you.

**Comment by sensibleworld** [comment]
This is available in the version 6 alpha release: https://fontawesome.com/download

**Comment by eynullabeyli** [comment]
please make it, we are still waiting

**Comment by sensibleworld** [comment]
This is available as part of version 6: https://fontawesome.com/v6.0/icons/manat-sign
