### ISSUE TITLE
Icon request: chart-bar-alt

### ISSUE THREAD

**Issue by andreweone** [FortAwesome/Font-Awesome#14604]
### What can it be used for?

Bar charts where the bars are displayed horizontally instead of vertically

### Example image (optional)

![bar-chart-alt](https://user-images.githubusercontent.com/9558786/52291188-64a53700-2937-11e9-8bb1-3980312411e5.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by terryschwarz** [comment]
Yupp would like horizontal bar chart too (to use as a chart type icon).

I would suggest chart-bar-horizontal as a more obvious name for this new one than the original suggested name of chart-bar-alt.

**Comment by aethior** [comment]
Hi @andreweone,

This icon has been updated in v6.0.0-BETA3.
Now there are [fa-chart-bar](https://fontawesome.com/icons/chart-bar) (horizontal) and [chart-column](https://fontawesome.com/icons/chart-column) (vertical) icons.

Regards.

cc/ @tagliala
