### ISSUE TITLE
Icon request: comment-questionmark

### ISSUE THREAD

**Issue by thaune** [FortAwesome/Font-Awesome#14617]
### What can it be used for?

When you need to add a comment or start a chat for some help. The comment-exclamation is good for telling something, but not asking for anything, via chat.

### Example image (optional)

Same as comment-exclamation, just with your question mark in the chat-bubble. 

![artboard 1-100](https://user-images.githubusercontent.com/47423217/52419474-6fef9280-2af0-11e9-8c2a-ea96ad1ee85e.jpg)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Also, `fa-comment-exclamation` is only available for FA Pro, with this approach you can implement them in Font Awesome Free

Demo: https://jsfiddle.net/tagliala/L17f528g/44/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tagliala** [comment]
Ref: #15985

@sensibleworld Is there any chance to bring this in FA6 for icon parity with `message-exclamation`  and `comment-exclamation` for Pro customers?

Free users may use stacking / layering

**Comment by sensibleworld** [comment]
Yup! It's already in the v6 alpha!

**Comment by tagliala** [comment]
> It's already in the v6 alpha!

Wow, I searched before asking 😕

Searching again, I found them. I'm going to add v6.0 and Pro labels to this

**Comment by tagliala** [comment]
Available in FA6 Pro https://fontawesome.com/v6.0/icons/comment-question
