### ISSUE TITLE
Can't access to user profile by firefox

### ISSUE THREAD

**Issue by Pablo-Araya** [FortAwesome/Font-Awesome#14615]
Since the last commit (5 days ago) I can't access to my user profile on fontawesome.com when i'm using firefox.  Google Chrome works good.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm.

Logging in from: https://fontawesome.com/sessions/sign-in

Firefox 65, macOS 10.14.2

Could you please retry or provide more information?

**Comment by Pablo-Araya** [comment]
Trying to Log in from: https://fontawesome.com/sessions/sign-in
Firefox 65.0, Win10 Home
I have erased all the cache and session ... still not working
I have tried from firefox private session... still not working

Console doesn't show errors

===========================
If you say that you can log in.... then the issue should be my machine.. I'll try from another one and I'll let you know.

Thanks for your response.

**Comment by tagliala** [comment]
@Pablo-Araya you're welcome

> then the issue should be my machine.

I'm not sure of this, maybe there are other issues

I've just checked with my windows machine and it works. Could you please try Firefox in safe mode? (close firefox, hold shift while clicking on the firefox icon, you will get an alert, then firefox will load without any third party extension)

**Comment by robmadole** [comment]
Also, if you have any extensions installed in Firefox that may cause something to go off.

**Comment by Pablo-Araya** [comment]
> 
> 
> @Pablo-Araya you're welcome
> 
> > then the issue should be my machine.
> 
> I'm not sure of this, maybe there are other issues
> 
> I've just checked with my windows machine and it works. Could you please try Firefox in safe mode? (close firefox, hold shift while clicking on the firefox icon, you will get an alert, then firefox will load without any third party extension)


Well, I've tried that solution a few weeks ago and it didn't worked.... 
Good news are that I've tried today and it's working correctly.

**Comment by tagliala** [comment]
Glad it's solved 😅
