### ISSUE TITLE
Icon request: motion

### ISSUE THREAD

**Issue by maxcoffer** [FortAwesome/Font-Awesome#14610]
### What can it be used for?

For Internet of Things (IoT) motion detection, motion itself as an action, motion sensor.

### Example image (optional)

Can be found here - http://peoplepowerco.com/icons/

![motion](https://user-images.githubusercontent.com/3885715/52344663-a4454f00-2a1b-11e9-9b78-b8ef690ab642.jpg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by InsanityMeetsHH** [comment]
In FA this icon is called "running". https://fontawesome.com/icons/running?style=solid

**Comment by tagliala** [comment]
@InsanityMeetsHH thanks

This icon is available in FA Pro as https://fontawesome.com/icons/running?style=light and FA Free as https://fontawesome.com/icons/running?style=solid

Closing here
