### ISSUE TITLE
Icon request: mythical dragon

### ISSUE THREAD

**Issue by thatb96** [FortAwesome/Font-Awesome#14616]
### What can it be used for?

<! It can be used for profile pic-->

### Example image (optional)

<!--- 🗾 >

- [ locked] This is a single icon or matched pair 
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/dragon?style=solid fit your use case?

If it doesn't, please provide a use case and an example

**Comment by aethior** [comment]
@tagliala I think you can close here.
