### ISSUE TITLE
Icon Request: icon-treemap-chart (tiles)

### ISSUE THREAD

**Issue by 1nternerd** [FortAwesome/Font-Awesome#1461]
![icon-tiles-suggest](https://f.cloud.github.com/assets/3995160/726678/0e925264-e124-11e2-8852-61337d65703e.png)
It would be awesome to see some icon alike this one in one of the future collections.
Sincerely, Internerd

**Comment by vlipman** [comment]
+1

**Comment by Szczawik** [comment]
A case for having two separate icons for the tiles and a treemap can be found [here](https://github.com/FortAwesome/Font-Awesome/issues/9421).

**Comment by Szczawik** [comment]
I can only guess what was the business case for the tiles icon, but I (and apparently a user vlipman, who commented in the other request post) got the impression it was not intended particularly for the treemap. Perhaps the tiles were generally meant to represent a layout of generic objects or user interface components (other options from that collection hypotetically being: side-by-side vertically, horizontally, or cascade).

The particular design image suggested for the tiles design cannot represent a typical treemap: it is neither arranged by sorting (the largest block would be first in the top left corner), nor stable and optimized for aspect ratio (the largest block would be aligned to the right edge), but it is perfectly valid for a generic "tiles" layout.

I would like to request an icon that could sit well next to the pie-chart icon, not something that would be used for arranging windows. Perhaps their appearance - based on what they visually represent - is similar, but the business goals are distinct. This is at least based on my understanding of the tiles icon request.

**Comment by diegopiriz** [comment]
+1

**Comment by baselsalam** [comment]
+1. In an app with tiles showing treemap, a lot of users who know treemap exists can't seem to find it.
The Tile icon doesn't come across as a treemap.

**Comment by JPhillips92** [comment]
+1. Currently using the 'fa-th-large' for this but its not very clear and often gets confused with the 'fa-table' icon.

**Comment by rsiebeling** [comment]
+1

**Comment by DaniloSI** [comment]
+1

**Comment by aethior** [comment]
Hi @1nerd,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/chart-tree-map

Regards.

cc/ @tagliala
