### ISSUE TITLE
Icons Not Displaying in Microsoft Word

### ISSUE THREAD

**Issue by SAID-developer** [FortAwesome/Font-Awesome#14612]
I recently updated to the latest version of Pro and when I went to use the icons in Microsoft Word there are several icons missing from the symbol menu. I've previously used all of the icons without issue. You can see the icons I was using prior to the update in the screenshot at the bottom. Those are no longer there. I tried redownloading and reinstalling the fonts, rebooting, etc. Nothing is working. Help!

![image](https://user-images.githubusercontent.com/19313118/52356950-3a20b000-2a03-11e9-81a5-f42d1d5353d1.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Please also follow our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) (in the Pro repository, of course) and please provide

1. OS Version
2. Word Version
3. Font version
4. Font type you have installed (ttf / otf) - please make sure it is OTF for the desktop
5. Is this a regression? (show a screenshot from the older version)
6. Icons that are not working
