### ISSUE TITLE
Icon Request :: Desk / Table / Chair Icons ?

### ISSUE THREAD

**Issue by aycanyumusak** [FortAwesome/Font-Awesome#14620]
Hi we are using Font Awesome icons on the restaurant websites, thank you for great icons!

But for the Table booking Reservations we cannot find right icons ? If you can create Table & Chair icons would be great ! Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a chair: https://fontawesome.com/icons/chair?style=solid
We have a request for a restaurant table at #4149 (please +1 that request)
We have a request for a desk at #9495 (please +1 that request)

If you would like to see a different chair or a different desk, please open new individual requests having care of filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here

**Comment by savadodesigns** [comment]
@tagliala Why close all these icon requests? You mention #9495 for the desk, but that one is also closed...
