### ISSUE TITLE
domain icon

### ISSUE THREAD

**Issue by ashkandaei2** [FortAwesome/Font-Awesome#14621]
### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ashkandaei2** [comment]
i need domain icon

**Comment by ashkandaei2** [comment]
i need of simple domain icon can u do anything for me???

**Comment by InsanityMeetsHH** [comment]
This could fit https://fontawesome.com/icons/globe?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide a single color example of the icon you need

> * The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ashkandaei2** [comment]
Yes thank you very much😊

**Comment by tagliala** [comment]
Closing here
