### ISSUE TITLE
Icon request: fa-file-lock

### ISSUE THREAD

**Issue by Lionqueen94** [FortAwesome/Font-Awesome#14627]
### What can it be used for?

To represent encrypted files.

### Example image (optional)

The archive and/or file icon with a lock on it (in the middle or bottom right).
Possibly 2 icons, one with a lock and one with a key.

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please note that you can achieve this icon by taking advantage of the svg framework

Demo: https://jsfiddle.net/tagliala/z12wdapb/19/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Lionqueen94** [comment]
Thanks a lot for the super quick response! I had no idea this was possible, but we will create a layered icon then :)

**Comment by tagliala** [comment]
You're welcome!

**Comment by tagliala** [comment]
Available in FA6 Pro: https://fontawesome.com/v6.0/icons/file-lock?s=solid
