### ISSUE TITLE
Wrote article on custom SVG icons with font-awesome.

### ISSUE THREAD

**Issue by nsisodiya** [FortAwesome/Font-Awesome#14622]
I wrote article on how to use custom svg icons on font-awesome. Please let me know any feedback.

https://medium.com/@nsisodiya/hacking-font-awesome-for-custom-svg-icons-ea762118fa7b

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for sharing this.

There is a wiki page about customization and there is described your approach.

Feel free to edit the wiki and add the link in the proper paragraph at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
