### ISSUE TITLE
dot missing in fal fa-flower

### ISSUE THREAD

**Issue by InsanityMeetsHH** [FortAwesome/Font-Awesome#14634]
### Describe the problem

`fal fa-flower` should also have a dot in center like solid and regular style.
https://fontawesome.com/icons/flower?style=light

![bildschirmfoto 2019-02-13 um 11 58 13](https://user-images.githubusercontent.com/35538671/52707376-d6106580-2f87-11e9-9d36-3956ec6029b5.png)

### What did you expect?

The dot in center of the flower should be there.

### What version and implementation are you using?

Version: 5.7.0+
Browser and version: -

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

Can confirm "SVG with JS" could also effect all other frameworks/systems.

### Reproducible test case

https://fontawesome.com/icons?d=gallery&q=daff&s=light&v=5.7.0,5.7.1,5.7.2

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks

**Comment by tagliala** [comment]
Fixed in 5.8.0

https://fontawesome.com/icons/flower?style=light
