### ISSUE TITLE
campground and campfire

### ISSUE THREAD

**Issue by kaydeeweb** [FortAwesome/Font-Awesome#14635]
<i class="far fa-campground"></i>
<i class="fas fa-campfire"></i>

Not working in my project. All other PRO icons are working. Have most up to date PRO version of font awesome installed.

**Comment by kaydeeweb** [comment]
`<i class="fas fa-campfire"></i>`
`<i class="far fa-campground"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[Campfire](https://fontawesome.com/icons/campfire?style=solid) and [Campground](https://fontawesome.com/icons/campground?style=solid) have been introduced in version 5.4.0

Please double check that your project does not contain third-party themes/plugins/libraries that are loading older versions of Font Awesome

If you still have issues, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case so we can take a look

Ref:
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here, but feel free too comment
