### ISSUE TITLE
Hand-holding-usd not showing up on desktop

### ISSUE THREAD

**Issue by nicalorber** [FortAwesome/Font-Awesome#14638]
I have the latest Font Awesome font installed. I was an early kick starter backer.

I copy/pated from This screen: https://fontawesome.com/icons/hand-holding-usd?style=regular

Pasted into my Sketch file and I get the Question box that comes up when it doesn't have that icon in the font. Older icons work. I'm finding that many of the newer ones are having this issue. 

![image](https://user-images.githubusercontent.com/17770732/52743514-09a2be00-2f8f-11e9-8c64-7404db6e2037.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please try the following:
1 - Uninstall all Font Awesome versions you have installed
2 - Restart your machine
3 - Download FA Pro version 5.7.2 for desktop
4 - Install new .otf fonts
5 - Try again

If that does not work, please try with version 5.6.3 (5.7+ have issues on desktop for some applications)

If it still does not work, please report
- OS Version
- Sketch version

PS: [hand-holding-usd](https://fontawesome.com/icons/hand-holding-usd?style=regular) is a FA Pro icon, the next time please report this kind of issues on the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by tagliala** [comment]
No feedback, closing here.

Feel free to comment if this is still an issue
