### ISSUE TITLE
Star icon - half gold, half grey?

### ISSUE THREAD

**Issue by GiacomoLaw** [FortAwesome/Font-Awesome#14631]
Is this possible? Trying to do this for stars on a review site.

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Generally speaking, it is not possible to have multicolor icons.

You can take advantage of the layering feature of the svg framework

https://jsfiddle.net/tagliala/z12wdapb/29/

Docs: https://fontawesome.com/how-to-use/on-the-web/styling/layering

If you are using the css framework, you can do the same with a little bit of custom css

Hope it helps

Closing here

**Comment by talbs** [comment]
Hi, @GiacomoLaw! Thanks for the good question.

@tagliala's spot on with his recommendation and links. We've also put together a couple of Codepen demos that might be helpful for you too. Check out https://codepen.io/fontawesome/pen/WLrOjo and the older https://codepen.io/fontawesome/pen/GyjamK.

If you have any questions, feel free to share them here. 😄

**Comment by GiacomoLaw** [comment]
Awesome, thank you so much!

**Comment by GiacomoLaw** [comment]
They are appearing split on my site: https://takanodan.net/shield-hero/

Not sure what to do about it :/

**Comment by tagliala** [comment]
@GiacomoLaw the layering feature is only available with the SVG Framework

As I mentioned before, the CSS version of FA5 needs extra stylesheet rules

This is implemented with pseudoelements:
https://jsfiddle.net/tagliala/b485yk2c/14/

Docs: 
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by GiacomoLaw** [comment]
Thank you!
