### ISSUE TITLE
id-card: Light-weight icon is vertically unaligned

### ISSUE THREAD

**Issue by clausstadel** [FortAwesome/Font-Awesome#14633]
### Describe the problem
The light-version of the fa-id-card icon seem to be unaligned with its bold and regular siblings:
![id-card](https://user-images.githubusercontent.com/5147372/52699100-4497f800-2f75-11e9-98e2-3d3c93ee44e1.png)

### What did you expect?
That the light version would be vertically aligned a bit higher.
The light icon to be aligned similarly with the bod and regular version. 

### What version and implementation are you using?

Version: 5.72.
Browser and version: Chrome for Mac, 72.0.3626.96

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

![image](https://user-images.githubusercontent.com/556268/52700711-e5d47d80-2f78-11e9-864b-90b1ff9a472e.png)

![image](https://user-images.githubusercontent.com/556268/52700742-f4bb3000-2f78-11e9-8226-78088c57840f.png)

**Comment by tagliala** [comment]
Fixed in 5.8.0
