### ISSUE TITLE
Subscribe to Font-Awesome release News?

### ISSUE THREAD

**Issue by weilinzung** [FortAwesome/Font-Awesome#14646]
How about automatic post the Latest Version Release News to Slack Channel? However, Font-Awesome seems doesn't have the Release Blog or News Page. Please add that page with the `RSS.xml`. 

Thanks~

**Comment by weilinzung** [comment]
@tagliala  any updates?

**Comment by polyzen** [comment]
Release tags have notes attached:
https://github.com/FortAwesome/Font-Awesome/releases

You can subscribe with this feed:
https://github.com/FortAwesome/Font-Awesome/releases.atom

**Comment by polyzen** [comment]
Also https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md

**Comment by tagliala** [comment]
@polyzen thanks!
