### ISSUE TITLE
new slack icon class not working

### ISSUE THREAD

**Issue by bhaskarhc** [FortAwesome/Font-Awesome#14641]
`<i class="fab fa-slack"></i>`

i'm using this tag , but not getting updated icon what ur showing !
instead of this i'm getting old one ! 
link of slack icon what i referred :```https://fontawesome.com/icons/slack?style=brands```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The [slack logo](https://fontawesome.com/icons/slack?style=brands) has been updated in version 5.7.0

I'm pretty confident that your application is loading an older version of Font Awesome. Please double check that you are using the latest version (5.7.2)

Please also note that some third-party plugins, themes, or libraries could be loading older versions of Font Awesome that may have priority.

Hope it helps

Closing here but feel free to keep commenting
