### ISSUE TITLE
v5.7.2 OTF missing most glyphs in desktop installation on Windows 7

### ISSUE THREAD

**Issue by Gehanii** [FortAwesome/Font-Awesome#14642]
Upgraded my locally installed OTFs from v5.6.3 to v5.7.2 only to discover almost all the glyphs no longer appeared. The notification on the download screen about recent changes in how the fonts are being named did not provide *any* details on what to do if things were broken. My only recourse at this time has been to reinstall 5.6.3.

I've attached a screenshot of the Win7 charmap util with v5.7.2 installed (it's still broken after reinstalling v5.6.3 and rebooting, so I don't have a comparison to share.)

![v572 charmap](https://user-images.githubusercontent.com/40069515/52808983-d3c80d00-3054-11e9-830a-7437d0a20c65.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this issue.

We are already aware of this issue, let's continue on #14614

Please downgrade to 5.6.3 meanwhile
