### ISSUE TITLE
Icon request: soon

### ISSUE THREAD

**Issue by JMD49591** [FortAwesome/Font-Awesome#14655]
### What can it be used for?
For a cycle of things that's gonna be new every time, like a broadcasting schedule or other things.
I just noticed you guys don't have an icon like that, and I need it at the moment. You have an open circle (fa-circle-notch) but not with an arrow to show that it's like a cycle. (fa-sycn might get close as well) The name might not be fitting but I hope you get what I ment.

### Example image (optional)
![circle](https://user-images.githubusercontent.com/36740020/52959278-1dd32a80-3396-11e9-8a9c-fafe4a753d2a.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> (fa-sync might get close as well)

Could you please clarify a different use case for this icon? Is it only a design choice?

**Comment by JMD49591** [comment]
> Anyway, layering, masking and power transformation features of the SVG Framework can help to create this icon
Oh wow I didn't knew this was possible. That makes font-awesome even more amazing.

> Could you please clarify a different use case for this icon?
I can't really think of any other use case than for a **repeating cycle**. Like some schedule.
'fa-redo' comes even closer but for my use case it's too much reminding of...yea a redo of course and not a repeating cycle.

Other than that 'fa-times-circle' seems to be 'fa-circle' and 'fa-times' fused together to one icon (for easier usage I guess).
So maybe creating an icon for my described use case would make it easier for everyone to use as well.
