### ISSUE TITLE
faTools missing from svg directory

### ISSUE THREAD

**Issue by devilchild656** [FortAwesome/Font-Awesome#14654]
After installation off npm package icon tools is missing from node_modules.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Please report name and version of the package you are using

**Comment by tagliala** [comment]
No feedback, closing here
