### ISSUE TITLE
Wrong icon showing up when making a search

### ISSUE THREAD

**Issue by davidvanbeveren** [FortAwesome/Font-Awesome#14650]
Hi there,

I work for a very large animal-rights organization, we want to add font-awesome to our site and other projects but when we searched for the icon "vegan", we just ended up getting a picture of bacon xD

http://prntscr.com/mlvglb

We're guessing someone was poking a little fun with vegans by adding that keyword to the bacon icon lol, but would it be at all possible to remove the tag "vegan" from the bacon icon and instead attach it to the "leaf" and/or "seedling" icons? That'd be way more relevant and helpful!

(or having the official vegan leaf as an icon as an additional icon request, that'd be _awesome_!)

Thanks, appreciate the help!

**Comment by UltraCakeBakery** [comment]
Hi @davidvanbeveren 

I also work for a very large animal-rights organization and we are currently writing an article about 'hidden front-end vegan harassment'.

We wanted to embed this issue in our next blog post but we couldn't help ourselves from noticing that your profile picture looks like a dead pig laying on its belly. 

I guess you are just sending subliminal messages lol, but would it be at all possible to remove your profile picture and change it from this "dead pig" to a "dead leaf" and/or "salad" instead? That'd be way more relevant and thoughtful!

(or just use a actual profile picture, that'd be awesome!)

Thanks, appreciate the afford!

**Comment by davidvanbeveren** [comment]
Hi @UltraCakeBakery!

Are you talking about the one [I have here](http://prntscr.com/mn5lbg)? It was an auto-generated default avatar given to me by github, I didn't think anything of it. I went ahead and updated it to a little piggy with his tongue out :)

Shoot me an email? Maybe we know each-other! If not, I love meeting other passionate vegan activists - we're also based in the Netherlands (lovely weather the last week).

It would also be great if you could link to our organization in your article if you mention me directly.

Email: david (at) youaretheirvoice.org

Hope to hear from you soon, and best of luck with your article!

David.

**Comment by sensibleworld** [comment]
Thanks for the feedback, @davidvanbeveren. We'll get this fixed.

**Comment by davidvanbeveren** [comment]
@sensibleworld @tagliala Thank you so much for the help! Vegans typically use the V with a circle around it as an icon, or the V with a leaf at the end (you can google "Vegan Symbol or Vegan Icon" for reference). Really appreciate you folks looking into it for us, let me know if you need anything else and have a wonderful weekend!

**Comment by tagliala** [comment]
@davidvanbeveren you're welcome, and sorry for the messed-up filters. I can see the fix are not live yet

Actually, there are three request about vegan symbols:
- #4950
- #8293
- #12590 

Please 👍 the request your are looking for

**Comment by sensibleworld** [comment]
Search results for "vegan" are fixed in our most recent release: https://fontawesome.com/icons?d=gallery&q=vegan

Thanks for bringing up the issue, @davidvanbeveren

**Comment by davidvanbeveren** [comment]
@sensibleworld @tagliala Hey there - thank you so much! Stoked that you guys were able to fix and improve on the search suggestion so fast, and appreciate the follow up tremendously. Thanks again - you guys are awesome! 🐷 💕
