### ISSUE TITLE
No icons are showing on https://fontawesome.com/icons with Ghostery enabled (Google Analytics)

### ISSUE THREAD

**Issue by Ionaru** [FortAwesome/Font-Awesome#14659]
The webpage https://fontawesome.com/icons displays no icons when I load the page with the Ghostery plugin (for Chrome) enabled and blocking all trackers.

![image](https://user-images.githubusercontent.com/3472373/53084937-234d8380-3502-11e9-9886-3abfbd407157.png)

The console is displaying a number of errors:
![image](https://user-images.githubusercontent.com/3472373/53085382-06658000-3503-11e9-8bc6-743dd9726df8.png)

I suspect the issue here is similar to #13952, an issue with Google Analytics.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are already aware of this issue, let's use #14649

Closing here
