### ISSUE TITLE
Icons are unaligned on desktop in version 5.7 and higher

### ISSUE THREAD

**Issue by andyhqtran** [FortAwesome/Font-Awesome#14664]
### Describe the problem
Icons are unaligned when adding a line-height to it. Prior to 5.7, it was working completely fine.

![image](https://user-images.githubusercontent.com/6789067/53134079-76d3c780-352a-11e9-9825-616fe71331f1.png)

### What did you expect?
Adding a line height should vertical align this

### What version and implementation are you using?

Version: 5.7.2 
Browser and version: Sketch -- Desktop Font  v5.7.2 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

### Reproducible test case
- Install Font Awesome into Font Book on MacOS
- Open Sketch
- Type `circle` and apply the font-family `Font Awesome 5 Pro`
- Add a line-height of `36px`
- Add another text called `Button` and apply a line-height of `36px`
- Center them horizontally

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

AFAIK, this issue has been solved in 5.7.2: 

https://github.com/FortAwesome/Font-Awesome/releases/tag/5.7.2

> Vertical alignment issues using OTF and TTF files in desktop applications that differ from previous
Font Awesome versions (< 5.7.0)

Could you please confirm that you are using FA 5.7.2? 

![image](https://user-images.githubusercontent.com/556268/53157816-9fa79b80-35c2-11e9-8e29-0382c85231d5.png)

**Comment by andyhqtran** [comment]
I had the latest version installed, from investigating between version - upgrading from 5.6 to 5.7+ while having an app that used this font open breaks the font. After talking with live chat, I was able to resolve the issue.
