### ISSUE TITLE
use.fontawesome.com coming up as malware

### ISSUE THREAD

**Issue by themarydouglas** [FortAwesome/Font-Awesome#14668]
### Describe the problem
My website got hit with malware and one of the files being shown is use.fontawesome.com is malicious https://www.maltiverse.com/hostname/use.fontawesome.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that the above service is showing malware websites using the public Font Awesome CDN. In other words, it is not saying that use.fontawesome.com contains malware.

I think that we cannot do anything about that: how websites use Font Awesome is out of our control.

Please also take a look at
- https://www.maltiverse.com/hostname/facebook.com (malware websites using facebook)
- https://www.maltiverse.com/hostname/code.jquery.com (malware websites using jQuery)

Hope it helps

Closing here

@robmadole could you please review this answer and share your thoughts?

**Comment by robmadole** [comment]
@tagliala I agree with you assessment 100%.
