### ISSUE TITLE
Power Transforms Not Working on Light (fal) Icons

### ISSUE THREAD

**Issue by sfhaney** [FortAwesome/Font-Awesome#14662]
I am trying to leverage power transforms on some icons that use a light styling.  I realize I have to reference the JS files as this is not a pure CSS only feature.

However, I am finding that the transform doesn't seem to apply if its a light style icon (fal).

See https://codepen.io/anon/pen/ZwZLwy

**Comment by sfhaney** [comment]
Another oddity is that <i class="far fa-rectangle-portrait"></i> doesn't appear to be working for some reason.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I realize I have to reference the JS files as this is not a pure CSS only feature.

Yes, power transforms require the SVG framework to work.

Please do not use both CSS and SVG on the same website: pick up the framework that fits your needs and go for it.

> However, I am finding that the transform doesn't seem to apply if its a light style icon (fal).

The demo codepen is loading the free version of font awesome pro SVG, which does not include light icons

https://codepen.io/tagliala/pen/PVgjro

Hope it helps

Closing here, but feel free to comment

**Comment by sfhaney** [comment]
Thank you Geremia.  Here is ultimately what I'm trying to do.

I was trying to build out some icons for dashboard column configurations.
There is only a single icon for columns (which includes 2).  So I was
trying to basically "smoosh" together a square (transformed a tad larger)
and and a rectangle.

For our sites purposes I will be using CSS 99.9% of the time so I'd rather
not change everything to use JS/SVG just for this purpose.

Can you think of any other alternatives ?

**Comment by tagliala** [comment]
You're welcome!

> Can you think of any other alternatives ?

Yes, I think there are alternatives. Could you please provide me an image of the icon you want to achieve by combining square and rectangle?

(please note that e-mail attachments don't work, update the image on github at https://github.com/FortAwesome/Font-Awesome/issues/14662)

**Comment by sfhaney** [comment]
I ended up doing the following.  I created this using divs w/ specific css and then just in-laid the FA5 icons and adjusted the font-size property to try and get the desired scaling.

![image](https://user-images.githubusercontent.com/6844484/53178659-e348d800-35b7-11e9-943d-a0c3aaece5cc.png)

**Comment by tagliala** [comment]
@sfhaney that's a better solution

Take a look at the stacking feature for more complex use cases https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons
