### ISSUE TITLE
Icons in the f6-- and f700 range aren't rendering properly in webfont

### ISSUE THREAD

**Issue by elizabethyalkut** [FortAwesome/Font-Awesome#14663]
### Describe the problem

I'm working on a project using webfonts, and downloaded 5.7.2. Most of the icons are working properly, but a number in the Unicode range starting with f6 and f7 render as the dreaded boxes. I've tested with over a dozen icons (calendar-related ones, baby, blender-phone) and in Chrome and Firefox.

### What did you expect?

I expect to see the icons as I do on the FontAwesome website gallery.

### What version and implementation are you using?

Version: 5.7.2 Webfont
Browser and version:  Chrome 72.0.3626.109 (Official Build) (64-bit); Firefox 65.0.1 (64-bit).

- [ ] SVG with JS
- [ x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

I'm testing this on localhost and I'm not sure how to reproduce this! I've attached a screenshot, and if you have a suggestion about how to test-case, I'm happy to do so.

### Bug report checklist

- [ X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
![headers___pattern_library](https://user-images.githubusercontent.com/593970/53129476-a3411100-3535-11e9-83ca-1d63d8bbb5df.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example of icon that does not work and related css / html?

A fiddle showing the issue would be great. You can start with this one https://jsfiddle.net/tagliala/1o7sevju/

**Comment by elizabethyalkut** [comment]
Sure. I've updated that fiddle with my HTML and SCSS.

**Comment by tagliala** [comment]
@elizabethyalkut could you please share the link to the updated fiddle?

**Comment by tagliala** [comment]
No feedback, closing here
