### ISSUE TITLE
Icon request: chinese-food

### ISSUE THREAD

**Issue by JackZeled0n** [FortAwesome/Font-Awesome#14667]
What can it be used for?

To include in websites and apps for restaurants that offert this kind of food.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Would #14365 fit your needs?

Or maybe noodles? 🍜 

Closing here

**Comment by JackZeled0n** [comment]
Hi @tagliala,
It's look good but is there any material design icon for that?

**Comment by tagliala** [comment]
> It's look good 

Good! I need a better title for this request. If chinese food could be represented by noodles, please add a 👍 reaction to that request and close this one

> but is there any material design icon for that?

I don't know if there is a material design icon for that.

If you mean a Font Awesome icon for that, then the answer is "no, it isn't" 😅

**Comment by JackZeled0n** [comment]
I will work with that icon for the moment.

Thanks @tagliala
