### ISSUE TITLE
Icon request: fa-marketplace - for App Stores or digital Marketplaces

### ISSUE THREAD

**Issue by adiepenbrock** [FortAwesome/Font-Awesome#14676]
### What can it be used for?

This Icon can be used for all kinds of Marketplaces, App Stores or to express a functionality to purchase or sell extensions, apps and so on for a specific app.

My current real-world use case: 
I am developing a web application that have a marketplace where users can sell extensions for this application to other users.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color example of this icon?

**Comment by sensibleworld** [comment]
Hi @adiepenbrock. We already have a couple of "store" icons that could fit this request. If you have an example of something specific or concrete that you're looking for, please fill out a [new icon request form](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md).
