### ISSUE TITLE
fal fa-snow-blowing not working

### ISSUE THREAD

**Issue by GLAJL** [FortAwesome/Font-Awesome#14671]
### Describe the problem

Using fal with "Web Fonts with CSS" does not show.

fas and far works fine.

### What version and implementation are you using?

Version: 5.7.2
Browser and version: Firefox and Chrome for Mac

- [x] Web Fonts with CSS

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/mfv9Lq0x/2/

If you are hosting the font by yourself, please double check that your font files are up to date and that there aren't css rules / javascript extensions preventing that icon to show

**Comment by GLAJL** [comment]
Hello @tagliala 

I have gone back to our test site and cannot still see it, I then ran some more tests in Browserstack and it is showing so it must just be cached for us still, odd though as I said the far and fas work fine.

Sorry to bother and thanks for looking into it.

**Comment by tagliala** [comment]
No problem, glad you've solved 👍
