### ISSUE TITLE
Kanye west

### ISSUE THREAD

**Issue by adammoisa** [FortAwesome/Font-Awesome#14679]
![kanye](https://user-images.githubusercontent.com/6547161/53309634-f6d59680-3876-11e9-939f-5939d8a23462.png)

I dunno how this hasn't been suggested yet... unless ppl aren't allowed?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please edit this request and fill out [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by sensibleworld** [comment]
Hey @adammoisa! We're unlikely to add icons of celebrities to Font Awesome. That said, a `user-musician` icon would certainly be appropriate. If that's of interest to you, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
