### ISSUE TITLE
Icon request: user-cycling

### ISSUE THREAD

**Issue by xuopled** [FortAwesome/Font-Awesome#14682]
### What can it be used for?

There are walking, hiking, running, skating and a lot more icons in the user category but for me, it miss some icons about biking : biking, mountain biking for examples

### Example image (optional)

<img width="94" alt="screenshot 2019-02-25 at 11 20 47" src="https://user-images.githubusercontent.com/2683300/53330693-6e470c80-38ef-11e9-8e35-126ea393fdd6.png">

### Icon request checklist

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Fonant** [comment]
To simplify, remove the backpack and helmet, and perhaps even the bike frame?

**Comment by xuopled** [comment]
For a simple "cycling" icon, yes. But for a "mountain biking" variant icon, it's better to keep the bakpack and the helmet

**Comment by Crissov** [comment]
Related Unicode emojis: #222

- [🚴 U+1F6B4](https://emojipedia.org/bicyclist/) BICYCLIST
- [🚵 U+1F6B5](https://emojipedia.org/mountain-bicyclist/) MOUNTAIN BICYCLIST

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/biking?style=solid
https://fontawesome.com/icons/biking-mountain?style=solid
