### ISSUE TITLE
Icon request: view-details

### ISSUE THREAD

**Issue by jbrowning391** [FortAwesome/Font-Awesome#14688]
### What can it be used for?

If you are wanting to bring up a details page within a grid or table. This icon could serve as a "view details" indication for how to do that. 

### Example image (optional)

![image](https://user-images.githubusercontent.com/31710413/53439621-0ca6a100-39c8-11e9-891d-1d458c0e86d3.png)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

**Comment by sensibleworld** [comment]
Hey @jbrowning391! We have a file-search icon in the works. It's being tracked here: https://github.com/FortAwesome/Font-Awesome/issues/640
