### ISSUE TITLE
Icon request: icon-close-fullscreen (fa-arrows-inwards-alt)

### ISSUE THREAD

**Issue by sdbernard** [FortAwesome/Font-Awesome#1468]
Hi there,

Love your work on the icons. May I suggest a close full screen option to complement your current icon- fullscreen. It can can be similar to your icon-resize-small icon, except it wil have 4 arrows going into a central point as opposed to just 2. See attached as an example.

Best
Steve
![icon-close-fullscreen](https://f.cloud.github.com/assets/2511348/730107/9237c7f4-e249-11e2-9b37-76eda0f37fc6.png)

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/461#issue-6877296

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/461#issuecomment-28679563

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/461#issuecomment-47423340

**Comment by goanpeca** [comment]
:+1:

**Comment by SylvainCorlay** [comment]
Here is the design we use for the Spyder IDE, which now uses font-awesome plus some ad-hoc design for what we found was missing. 

Icon name  | Example
------------- | -------------
fa-arrows-inwards-alt  |  ![inward](https://cloud.githubusercontent.com/assets/2397974/7922396/f75b2d3a-0879-11e5-949c-723915a17218.png)

I have svg and glyph versions of this icon if you are willing to use this design. (Should be pixel-perfect at 14px).

**Comment by Mctalian** [comment]
+1

**Comment by soberstadt** [comment]
+1

**Comment by sieira** [comment]
+1

**Comment by axertion** [comment]
+1

**Comment by szegheo** [comment]
+1

**Comment by kevinyuliawan** [comment]
+1

**Comment by frontendstacked** [comment]
+1

**Comment by sroutledge** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by gareth-ferneyhough** [comment]
+1

**Comment by AmitMY** [comment]
+1

**Comment by Azeranex** [comment]
+1

**Comment by eaxexe** [comment]
+1

**Comment by IanMuirhead** [comment]
+1

**Comment by nmcclay** [comment]
I was just surprised to find this didn't exist, +1

**Comment by Jwomers** [comment]
+1

**Comment by alexcheninfo** [comment]
+ 1

**Comment by w3soto** [comment]
+1

**Comment by lucassouza1** [comment]
+1

**Comment by rontav** [comment]
+1

**Comment by PxSonny** [comment]
+1

**Comment by jirkapinkas** [comment]
+1

**Comment by zmalic** [comment]
+1

**Comment by kingrollo** [comment]
+1 from me!

**Comment by fraserr** [comment]
+1

**Comment by jey07ro** [comment]
+1

**Comment by planigan** [comment]
+1

**Comment by yyakovlev** [comment]
+1

**Comment by Emerceen** [comment]
+1

**Comment by vvidala** [comment]
+1

**Comment by josephzhao** [comment]
+1

**Comment by is-ef** [comment]
+1

**Comment by jbress** [comment]
+1

**Comment by gpfreund** [comment]
+1

**Comment by deansteen** [comment]
+1

**Comment by sohan5005** [comment]
This icon is still not there -_-

**Comment by sohan5005** [comment]
+1

**Comment by iCrashed** [comment]
+1

**Comment by Neverlastinger** [comment]
+1

**Comment by sohan5005** [comment]
+1 again -_-

**Comment by dsalunga** [comment]
+1

**Comment by alex-3logic** [comment]
+1

**Comment by alex-3logic** [comment]
Is this a joke? Four years and still nothing....!!!

**Comment by wgv-sethlivingston** [comment]
Honestly the creator (of this great collection of free icons) is doing some things differently these days, so I wouldn't bet on this getting done. Which is fine, cause like I said, he did it for free. Personally I'm going to unsubscribe from this issue.

**Comment by lumantovanini** [comment]
+1

**Comment by babacardiop** [comment]
+1

**Comment by spo** [comment]
+1

**Comment by nealshail** [comment]
+1

**Comment by flotos** [comment]
+1

**Comment by jafetbjarkar** [comment]
+1

**Comment by Beny-Muler** [comment]
+1, will it be added?

**Comment by GarethPW** [comment]
+1

**Comment by landowskitomasz** [comment]
+1

**Comment by drkwolf** [comment]
+1

**Comment by Zlerp** [comment]
+1

**Comment by jamaiolo** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by sensibleworld** [comment]
We can finally close this issue: 
https://fontawesome.com/icons/compress-arrows-alt?style=solid
