### ISSUE TITLE
The Hard-Hat solid does not seem to work.

### ISSUE THREAD

**Issue by ghyut1** [FortAwesome/Font-Awesome#14695]
Using the emojis is working very well for me, except for the hard-hat so far. Thanks for the help, and your time.
![image](https://user-images.githubusercontent.com/9854668/53516302-fa953300-3a99-11e9-9712-c15112705223.png)
![image](https://user-images.githubusercontent.com/9854668/53516374-2adcd180-3a9a-11e9-9851-f57823b36ec2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[hard-hat](https://fontawesome.com/icons/hard-hat?style=solid) has been introduced in Font Awesome 5.7.0

I'm pretty confident that your application is loading an older version of Font Awesome. Note that there could be third party plugins / themes / libraries loading older version of Font Awesome that may take precedence over your version.

Please double check in the console that the proper css and font files are being loaded

Closing here, but feel free to comment
