### ISSUE TITLE
Getting the old (4.x) fa-list design 

### ISSUE THREAD

**Issue by ccleve** [FortAwesome/Font-Awesome#14696]
The older icon for fa-list, in 4.x, had four bullet points in it. The newer 5.x fa-list has three.

I'm trying to do a logo with it and the four-bullet version looks better. I can get the older font just fine on the web, but using it in a desktop app (Sketch) is difficult because I'd have to delete the 5.x font from my Mac and install the older one. As I understand it, you can't have both installed at the same time.

Ultimately, all I want is an .svg of the logo with the older version. What's my best option?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> 
Ultimately, all I want is an .svg of the logo with the older version. What's my best option?

Voilà: https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/svg/list.svg

Please note that FA 4.x has its own grid and icons are pixel perfect at 14 px. FA 5.x, instead, uses a 16px grid and base size, so you may need other changes to make the old icon work together with the new ones

Hope it helps

Closing here, but feel free to comment

**Comment by ccleve** [comment]
This works perfectly. Thank you.
