### ISSUE TITLE
Icon request: user-nurse-neutral

### ISSUE THREAD

**Issue by JamesBrining** [FortAwesome/Font-Awesome#14691]
### What can it be used for?

There is already a nurse icon (user-nurse) but this could be interpreted as being female due to the long hair and low cut top. A more gender neutral icon would be useful.

### Example image (optional)

![genderneutralnurse](https://user-images.githubusercontent.com/46819499/53497595-709a9980-3a9c-11e9-9ba5-2425fbcc30ed.PNG)
![nursegeneric2](https://user-images.githubusercontent.com/46819499/53497596-709a9980-3a9c-11e9-8d49-4a4e253f2339.PNG)

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
@JamesBrining Thanks for the feedback! The current icon was actually a specific sponsored icon request (with the longer hair), but I agree that a more neutral icon would be helpful, too. Will add it to my list!

**Comment by JamesBrining** [comment]
> @JamesBrining Thanks for the feedback! The current icon was actually a specific sponsored icon request (with the longer hair), but I agree that a more neutral icon would be helpful, too. Will add it to my list!

Great, thanks!

**Comment by sensibleworld** [comment]
The updated nurse icon is now available: https://fontawesome.com/icons/user-nurse?style=solid
