### ISSUE TITLE
Icon request: fa-swap

### ISSUE THREAD

**Issue by mrthking** [FortAwesome/Font-Awesome#14701]
### What can it be used for?

This would be use to express changing one item out with another. 

### Example image (optional)

![swap](https://user-images.githubusercontent.com/48102739/53590903-a2b50580-3b47-11e9-8776-9b3e47ae9575.png)

### Icon request checklist
 
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) Single
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as [fa-random](https://fontawesome.com/icons/random?style=solid)

@talbs could you please add a `swap` filter to this icon?

**Comment by mrthking** [comment]
Thanks.
