### ISSUE TITLE
Icon request: beginner-drivers-sign (shoshinsha 🔰)

### ISSUE THREAD

**Issue by tsunehisa** [FortAwesome/Font-Awesome#14703]
![default](https://user-images.githubusercontent.com/11070567/53691105-bfa53f00-3dba-11e9-9140-c2bc13c747ef.gif)
### What can it be used for?

Indicate　for  beginners or first visits

### Example image (optional)

![_120](https://user-images.githubusercontent.com/11070567/53691127-fa0edc00-3dba-11e9-88e1-3490ba9c0591.jpg)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) single
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Does this represent a brand? If yes, could you please provide more information about this brand?

**Comment by Ethiarpus** [comment]
It looks like something similar exists already, and could be used to represent a new user. What about [fa-seedling](https://fontawesome.com/icons/seedling?style=solid) or [fa-leaf](https://fontawesome.com/icons/leaf?style=solid)?

**Comment by reydajp** [comment]
@tagliala Hi
No it's  japanese beginner's sign. It's normally use for beginner driver but many of jpn website use as help mark, especially for their new users.

[Shoshinsha mark](https://en.wikipedia.org/wiki/Shoshinsha_mark)

**Comment by tagliala** [comment]
@reydajp thanks for the heads-up!

Since we are limited to a single color (or at most duotone svg icons for Pro users), does this sign make sense in only black color?

**Comment by reydajp** [comment]
@tagliala 
Not sure about it as I never seen this icon in mono-color. But if you search on [google](https://www.google.com/search?q=%E5%88%9D%E5%BF%83%E8%80%85%E3%83%9E%E3%83%BC%E3%82%AF+%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiC5qaTi-_iAhUDvbwKHa_hCZgQ_AUIECgB&biw=1920&bih=969), it's commonly used with 2 colors,  so a duotone svg like the [shield icon](https://fontawesome.com/icons/shield-alt?style=solid) may be better.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
