### ISSUE TITLE
Icon Request: icon-farm

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1470]
Hello!
I appreciate you taking the time to consider my request. I'm looking to have an additional font/icon added the the great list.  This would be of a farm building (see attached.), much like the image below:

![roofing-icon](https://f.cloud.github.com/assets/4910349/732286/a4e6301c-e27f-11e2-9e7d-b86666badb73.jpg)

Please let me kno your thoughts on the matter.  The icon would be used on the homepage of the revenant theme, insight one of the circles.

Thank you for your time.

**Comment by juansalvatella** [comment]
+1 icon-farm

**Comment by ethanclevenger91** [comment]
+1 icon-farm

**Comment by SBadr** [comment]
+1 icon-farm

**Comment by martinlindhe** [comment]
+1 icon-farm

**Comment by 247Chon** [comment]
+1 icon-farm

**Comment by edudoda** [comment]
+1

**Comment by kpingel** [comment]
👍

**Comment by fravel77** [comment]
+1

**Comment by fsasvari** [comment]
+1

**Comment by j-c-o-l-l-i-n-s** [comment]
+1

**Comment by sensibleworld** [comment]
We've added `fa-farm` icon to Pro: https://fontawesome.com/icons/farm?style=solid
