### ISSUE TITLE
New Set for Alphabets & Numbers

### ISSUE THREAD

**Issue by itlegendyt** [FortAwesome/Font-Awesome#14708]
# New Set for Alphabets & Numbers

### Sometimes we do not have icons for a particular thing. So in conditions like this can we can use the first letter of that thing. Even we can make our logo or a heading. 
___

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I have to close this request because letters and numbers are out of scope at the moment

Ref: #5019

**Comment by credenceweb** [comment]
I am hoping that you will reconsider this. It would make life a lot easier for those of us that work with various themes, and plugins such as Wordpress Divi.
