### ISSUE TITLE
Icon request: raise

### ISSUE THREAD

**Issue by AntoniniP** [FortAwesome/Font-Awesome#14705]
### What can it be used for?

For example, to link to a gallery to showcase my photography.

### Example image (optional)

[https://raise.usa.canon.com/](https://raise.usa.canon.com/)

**Comment by aethior** [comment]
>The RAISE Photo Community Platform (“RAISE”) is being shut down on Wednesday December 30, 2020, 11:59AM PST
After RAISE is shut down, you will no longer be able to access your account or your images. ([more info](https://www.usa.canon.com/internet/portal/us/home/about/to-our-customers/raise-faq))

cc/ @tagliala
