### ISSUE TITLE
Icon request: icon-pinball

### ISSUE THREAD

**Issue by gfisher42** [FortAwesome/Font-Awesome#14710]
### What can it be used for?

This icon can be used for arcades/gaming/pinball (a quick growing e-sport)

### Example image (optional)

https://cdn.dribbble.com/users/35567/screenshots/593438/doc6.jpg 

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @gfisher42,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/person-pinball

Regards.

cc/ @tagliala
