### ISSUE TITLE
Icon request: user-dollar-sign

### ISSUE THREAD

**Issue by RodrigoASantos1979** [FortAwesome/Font-Awesome#14729]
### What can it be used for?

asks to be used in links or buttons to register guarantors, or to identify guarantor in an application

### Example image (optional)

![guarantor](https://user-images.githubusercontent.com/22460649/54085830-19f55100-4321-11e9-8d77-d3859792fabe.png)

the svg vector created by me based on your "user" icon can be found at this link.
http://imagens.meussites.net.br/guarantor.html

### Icon request checklist

- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes ] I have included at least one example image if it could be helpful (optional)
- [ yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I need a better title for this request. ` user-dollar-sign`  or `users-dollar-sign` are better names.

After editing the title, your request will meet our contributing guidelines, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/hro14y5w/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tagliala** [comment]
Another version using `fa-users-cog`: https://jsfiddle.net/hro14y5w/1/

**Comment by sensibleworld** [comment]
This can now be created with our Icon Wizard.

![CleanShot 2024-07-12 at 11 52 52@2x](https://github.com/user-attachments/assets/ba5b655b-8644-4b37-abd8-2ce0472dc342)
