### ISSUE TITLE
Possible size inconsistency between fa-list-alt and fa-image

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#14734]
### Describe the problem

The following icons look inconsistent when used near each-other
- https://fontawesome.com/icons/list-alt?style=solid
- https://fontawesome.com/icons/image?style=solid

### What did you expect?

I'm not sure, but `list-alt` does not seem to follow the grid. It is different from both

- https://fontawesome.com/icons/rectangle-landscape?style=solid
- https://fontawesome.com/icons/square?style=solid

but it is the same size of other icons, such as
- https://fontawesome.com/icons/table?style=solid

Icons should follow this grid (image taken from the Kickstarter campaign)
![image](https://cloud.githubusercontent.com/assets/556268/22787239/f138d052-eedb-11e6-8821-53da24ab115e.png)

### What version and implementation are you using?

Version: 5.7.2 CSS
Browser and version: n/a

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

### Reproducible test case
https://jsfiddle.net/tagliala/1o7sevju/3/

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Splitted out from #1281

**Comment by robmadole** [comment]
@sensibleworld what's your take on this?

**Comment by sensibleworld** [comment]
Hmmm... these were icons designed before I came on board. I'm always a bit wary changing anything that's been in the ecosystem for a while, as it may be considered a breaking change.

It wouldn't be very difficult to increase the height of `fa-image` to 14px, as opposed to its current 12px to bring it more in line. I'll bring this up with Mr. Gandy :)

**Comment by sensibleworld** [comment]
Hey @tagliala! Because these icons have been a part of FA5 since its initial release, I'm hesitant to do any updates to them, as it may inversely affect some implementations. This may be a case where we need to create another alternate version of the icon, but for now, I think we'll need to keep it as-is.

**Comment by tagliala** [comment]
Thanks @sensibleworld 

I've added the breaking change label and I will keep this open for tracking purposes and future references

**Comment by sensibleworld** [comment]
We've made some updates in v6, and these should now be consistent
