### ISSUE TITLE
Icon request: paper-plane-alt

### ISSUE THREAD

**Issue by superboss224** [FortAwesome/Font-Awesome#14737]
### What can it be used for?

The icon would be used to send a message

### Example image (optional)

https://fontawesome.com/icons/paper-plane?style=solid
The same as here, but horizontal, like material icons's send:
https://material.io/tools/icons/?search=send&icon=send&style=baseline
To have a simple and horizontaly symetric icon to send messages

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
