### ISSUE TITLE
Bug: fa-flip-both and SVG+JS

### ISSUE THREAD

**Issue by HaoLuu** [FortAwesome/Font-Awesome#14735]
### Describe the problem

The class fa-flip-both works fine with CSS + web fonts method but does not work with SVG+JS method. I'm seeing a circled, flashing "?" and "!". The upside is that they ("?" and "!") are indeed flipped both horizontally and vertically.
![image](https://user-images.githubusercontent.com/48443728/54139147-81abb900-4453-11e9-86e8-15d8f4a48865.png)
(from the test case below)
### What did you expect?

I expected it to work the same for both CSS and JS.

### What version and implementation are you using?

Version: 5.7.2 
Browser and version: Google Chrome 72.0.3626.121 (Official Build) (64-bit)

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://codepen.io/anon/pen/MxEgbZ

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

(I'm sorry that I could not check if this has been reported before because there are nearly 5000 open issues right now)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm, let's assign @robmadole

**Comment by robmadole** [comment]
I'm on it! Thanks.

**Comment by HaoLuu** [comment]
Confirm that it's been fixed in latest release (v5.8.1)
