### ISSUE TITLE
Icon Request: icon-teamspeak

### ISSUE THREAD

**Issue by CGollhardt** [FortAwesome/Font-Awesome#1474]
Hello There,

thank you for your great work. My current Project is to develope a CMS for Clans (E-Sport). It should be better than WordPress, Ilch and so on.

It would be nice to see in Version 4 the following Pics:
- Xbox Logo (http://images.wikia.com/vsrecommendedgames/images/archive/3/3d/20130522005626!Microsoft_Xbox_One_logo.png)
- PSN Logo (http://www.spieleradar.de/Playstation3/spiele/news/playstation-3/uploads_cms/pics/PSN_1372164799.jpg)
- Steam Logo (http://www.wasder.net/wp-content/uploads/2012/09/43557-steam-steam-logo-wallpaper2.png)
- Teamspeak (http://rocketdock.com/images/screenshots/ts.jpg)

I dont think it is generic enough but Icons for Counterstrike/Call of Duty/Minecraft/Battlefield would be very nice, because a Webinterface for Server is still in developement.

Sorry for my bad english and thank you for your attention.

**Comment by TheServibilis** [comment]
+1

**Comment by qeterme** [comment]
+2 for teamspeak

**Comment by jensz12** [comment]
+1

**Comment by Sapiensy** [comment]
+1

**Comment by MoBue** [comment]
+1

**Comment by luk1lucas** [comment]
+1

**Comment by soulgriever** [comment]
+1 for TS

**Comment by k725** [comment]
+1 :+1:

**Comment by 3DDario** [comment]
+1 for TeamSpeak 3 icon

**Comment by tssge** [comment]
+1 for TeamSpeak 3 icon

**Comment by hroost** [comment]
+1 for teamspeak icon

**Comment by davePlug** [comment]
+1 for TS3 icon

**Comment by HadrienX** [comment]
+1 for TeamSpeak

**Comment by paralin** [comment]
+1

**Comment by ntom** [comment]
+1

**Comment by Autopoietico** [comment]
+1

**Comment by madsendk** [comment]
+1

**Comment by thasmog** [comment]
+1 for ts3

**Comment by MeddlingMoose** [comment]
+1

**Comment by Geniks** [comment]
+1

**Comment by bypit** [comment]
+1 for Teamspeak

**Comment by Shytoos** [comment]
+1

**Comment by Raphouphe** [comment]
+1

**Comment by Staticpast** [comment]
+1 for teamspeak

**Comment by dhardtke** [comment]
+1 for teamspeak

**Comment by Olegatro** [comment]
+1 for teamspeak

**Comment by Vladeksh** [comment]
+1 for teamspeak

**Comment by LukasJK** [comment]
+1 for TS

**Comment by xXKeyleXx** [comment]
+1

**Comment by LukvonStrom** [comment]
+1

**Comment by vav17** [comment]
+1 I need that teamspeak icon

**Comment by 2Kable** [comment]
+Wake up !

**Comment by QuartzzEU** [comment]
+1 for TS Icon - Would look really nice on gaming related websites that have clans that use Teamspeak for communication - being able to link to their TS and have the fa-icon there will make it look a lot more professional than a homemade one, plus easier to insert with xenforo :)

**Comment by Dunceantix** [comment]
+1

**Comment by cjmaxik** [comment]
+1

**Comment by ryankane** [comment]
# Vectors

Here are some vectors I produced from the reference SVGs below. These were exported to 512px images.

## fa-xbox

![fa-xbox](http://i.imgur.com/Y5sXNTD.png)

## fa-playstation

![fa-playstation](http://i.imgur.com/NxpUnuQ.png)

## fa-psn

![fa-psn](http://i.imgur.com/pXuwoGp.png)

## fa-teamspeak

![fa-teamspeak](http://i.imgur.com/WpdqZAn.png)

# References

* https://commons.wikimedia.org/wiki/File:Xbox_Logo.svg
* https://commons.wikimedia.org/wiki/File:PlayStation_4_logo_and_wordmark.svg
* http://vsrecommendedgames.wikia.com/wiki/File:PlayStation_Network_logo.svg
* https://upload.wikimedia.org/wikipedia/de/c/c7/Teamspeak-Logo.svg

**Comment by Geniks** [comment]
awesome thx

**Comment by LubricantJam** [comment]
+1 for TeamSpeak

**Comment by Dooleylabs** [comment]
+1 TeamSpeak

**Comment by phil568622** [comment]
+1...

Why isnt this implemented?

**Comment by serubi** [comment]
+1

**Comment by joshualawson** [comment]
+1

**Comment by leesolway** [comment]
+1

**Comment by stormtrooper42** [comment]
+1 Wake UP ! 
Why isnt this implemented 3 icons for Facebook and 0 for Teamspeak o_O

**Comment by baslr** [comment]
+1

**Comment by ryankane** [comment]
If Teamspeak is to be added, Discord might as well be added too.

# Discord Vectors

**Note:** Rendered at 512 pixels.

### fa-discord

![fa-discord](http://i.imgur.com/eYwy8lc.png)

### fa-discord-o

![fa-discord-o](http://i.imgur.com/tyovIce.png)

## References

- https://en.wikipedia.org/wiki/File:Discord_logo.svg

**Comment by naurel06** [comment]
+1

**Comment by BeryJu** [comment]
+1

**Comment by GuurgleOS** [comment]
+1

**Comment by grafnicolas** [comment]
+1

**Comment by MostlyHarmlessGHG** [comment]
+1

**Comment by Foorack** [comment]
+1

**Comment by Mythen96** [comment]
+1

**Comment by JoshWareing** [comment]
+1 for this taking ages...

**Comment by NoHacks** [comment]
+1 for teamspeak

**Comment by GnuTalux** [comment]
+1 for teamspeak

**Comment by okanozdemir** [comment]
+1 for teamspeak

**Comment by groovybluedog** [comment]
It's 2016 and this still isn't in Font Awesome yet... is it really that awesome when it's been over three years yet we still don't have the icon for the most popular "speciality" voice platform?

**Comment by SergeOvD** [comment]
+10 for teamspeak

**Comment by SergeOvD** [comment]
Hey guys where is my ts3 icon? :dancer:

**Comment by Alydus** [comment]
1+ for TS3, what is this madness, no TS?

**Comment by zInvalid** [comment]
:+1: Please :smile:

**Comment by MrPalamen** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by groovybluedog** [comment]
Only 5 more years to wait lads!

**Comment by NerdisDev** [comment]
+1

**Comment by groovybluedog** [comment]
They will in about 43 years xD
Another icon project could start from nothing and build up the same and double the icons Font Awesome does at the rate it takes them to add highly requested icons... xD

**Comment by nomadichayward** [comment]
It's been more than a year now since TeamSpeak icon and other highly requested icons be added. There are some really rubbish icons which made it in, so why can't these? This project seems to have just stood still for a long time !!

**Comment by Maelstromeous** [comment]
+1

**Comment by Natedanp** [comment]
+1

**Comment by Nik99** [comment]
+1

**Comment by DaniNotFound** [comment]
+1

**Comment by unkn0wn1337** [comment]
+1

**Comment by leesolway** [comment]
Some feedback would be great. If they don't want to do it, feed that back please.

**Comment by jmlt** [comment]
+1

**Comment by thereis** [comment]
+1

**Comment by codebucketdev** [comment]
+1

**Comment by maxibanki** [comment]
+1

**Comment by ReStFaI** [comment]
+1 Teamspeak

**Comment by niklas4444** [comment]
+1 for Teamspeak icon

**Comment by T0biii** [comment]
+1 for Teamspeak icon

**Comment by JakubPanek** [comment]
+1

**Comment by SausageParty69** [comment]
As said above, any updates in this issue - icon request?

**Comment by haywardgb** [comment]
Some of the icons they've added are just plain dumb and so random, so yeah, they'll waste time on those icons but not a commonly requested one like TeamSpeak.  Seems to me like someone on the dev team simply doesn't like TS and that's why it's not being added.

**Comment by SausageParty69** [comment]
@haywardgb Take a look at this

https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669

Not that they don't like TS, other icons are on hold for 2 years aswell

**Comment by HumanTree92** [comment]
+1

**Comment by skmedix** [comment]
+1

**Comment by SnowyTerror** [comment]
+1 Please add fa-teamspeak <3

**Comment by hamidkag** [comment]
+1 please add teamspeak

**Comment by rafal-olszewski** [comment]
+1 for ts

**Comment by aJoKer96** [comment]
+1 for Teamspeak

**Comment by paulocrash** [comment]
+1 for Teamspeak

**Comment by blizzard2023** [comment]
+1 for Teamspeak

**Comment by VerHext** [comment]
+1 for TeamSpeak and Discord

**Comment by byjokese** [comment]
+1 teamspeak

**Comment by sigtus** [comment]
+1

**Comment by FrozenBeard** [comment]
How the hell is teamspeak not added yet?

**Comment by Pyroman-FEAR** [comment]
+1

**Comment by IdiotBox** [comment]
+1 for Teamspeak

**Comment by Foorack** [comment]
Who even uses TeamSpeak anymore? We migrated to Discord over a year ago.

Also this issue was created in **Jul 2 2013** and there are currently 1363 `brand icons` issues. I think there is very little chance for this to ever get merged. 😕

**Comment by haywardgb** [comment]
@Foorack Discord is aimed at gamers, it feels like such too. TeamSpeak still has advantages over Discord, which is why myself and others still continue to use it.  As for not having the time due to the 1363 other brand issues, they've added Gulp of all brands, you telling me that Gulp deserves priority over TeamSpeak. I'm telling you now, this is personal, whoever runs this project probably doesn't like TeamSpeak and agrees with your sentiments 

Shame. FontAwesome was starting to grow on me. Glad there's alternatives out there.

**Comment by ReconV** [comment]
+1 for Teamspeak

**Comment by byjokese** [comment]
+1 I think we have more than enough request for Teamspeak, is that difficult to put it in? Other icon had already been added but not this one....

**Comment by grand-marshall** [comment]
+1 for teamspeak

**Comment by kaziu687** [comment]
+1 teamspeak

**Comment by Taminoful** [comment]
+1 teamspeak

**Comment by olegatro** [comment]
too long, no, thanks, there are alternatives

**Comment by HumanTree92** [comment]
Yeah i agree that this is taking way to long are a lot of horse shit. Whoever runs Font Awesome is probably some low life momma's boy who still lives with his mom. Must really hate TeamSpeak.

**Comment by dtvmedia** [comment]
+1 teamspeak

**Comment by aequasi** [comment]
How many more months of +1s are there gonna be before people realize you should just add a reaction to the first post.

**Comment by sensibleworld** [comment]
@HumanTree92 The simple answer is that Font Awesome was a one-man show for many years, completely free, and run as a side-project. That is no longer the case, and we're doing our best to be more transparent and responsive to the community.

**Comment by ReconV** [comment]
After 5 years... finally

**Comment by talbs** [comment]
https://fontawesome.com/icons/teamspeak

**Comment by ReconV** [comment]
Please update TeamSpeak 3 icon

**Comment by tagliala** [comment]
@ReconV please open a new issue

**Comment by VerHext** [comment]
+1 Update to the new TeamSpeak icon

**Comment by talbs** [comment]
Hey, gang. The icon was updated to the newest brand treatment in our last release - https://fontawesome.com/icons/teamspeak?style=brands. Hope that helps! 😄
