### ISSUE TITLE
End of Life - Font Awesome v1.x to v4.x

### ISSUE THREAD

**Issue by babatundeko** [FortAwesome/Font-Awesome#14740]
Hi, Font Awesome Help Desk Support,

My organization is currently using Font Awesome v4.7.1 for the internal web application and plan to upgrade v.5.4.1 due to end of life (EOL). However, is a Font Awesome v1.x, v2.x and v3.x end of life(EOL) as well? And no longer supported and maintained? If not, then we need an upgrade to Font Awesome v5.x. Please confirm and provide a brief description of why these versions no longer supported/maintained. Any significance information relates to EOL would be appreciated.

Thanks,
Kazeem

**Comment by robmadole** [comment]
@babatundeko only version 5 will be actively worked on. It's the new version.
