### ISSUE TITLE
react regular icons not working

### ISSUE THREAD

**Issue by daliborhomola** [FortAwesome/Font-Awesome#14743]
Hello, I've tried it several times, but when I use package 'free-regular-svg-icons', it´s not working. 
'free-solid-svg-icons' is working fine to me.
Problem is that icon have regular theme, but when I try to use it from regular-icons package, 
the icon does not appear on the page.

### What version and implementation are you using?
I use 5.7.2 (latest) version of this package. I tried it in .net core 2.2 project with template React and Redux.

Browser and version: Google chrome  72.0.3626.121

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate: https://codesandbox.io/s/o84659ok6

We have a react plugin that could be useful for your use case: https://github.com/FortAwesome/react-fontawesome

If you still think there is an issue with font awesome, please provide a reproducible test case or as many information as you can

Closing here, but feel free to comment.
