### ISSUE TITLE
Custom svg icon import 

### ISSUE THREAD

**Issue by steve8la** [FortAwesome/Font-Awesome#14742]
How can I include my Own design custom icons in font awesome? 

Ad an icon designer I have this issue: all developer ask me for a fontawesome but in font awesome  I'm not able to are my custom design icons.

is there a way?

**Comment by InsanityMeetsHH** [comment]
I have no experience with it, but here you can read about the topic.
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment]
Hi,

You will find information on how to customize Font Awesome SVG at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework

I've also added a live example: https://jsfiddle.net/tagliala/we7gtcvk/1/

Hope it helps.

Closing here

**Comment by designbyadrian** [comment]
@tagliala In the guide, it's unclear what the third parameter is for `icon`. It looks like a unicode placement, but what are the limitations? See "e001" below:

```
// replace 1568, 1568 with your SVG viewbox
// replace 'M256...' with your single-path SVG
var faListOldStyle = {
  prefix: 'fac',
  iconName: 'list-old-style',
  icon: [1568, 1568, [], 'e001', 'M256...']
}

FontAwesome.library.add(
  faListOldStyle
)
```

**Comment by tagliala** [comment]
@designbyadrian thanks for the feedback.

Yes, that is a Unicode point in the private `e` area, which is not used by Font Awesome.

I'm going to edit the wiki, so it will also support pseudoElements

https://jsfiddle.net/tagliala/we7gtcvk/12/
