### ISSUE TITLE
Icon request: icon-berries

### ISSUE THREAD

**Issue by TheSwedishChef** [FortAwesome/Font-Awesome#14748]
### What can it be used for?

I'm developing a food related app, and I need an icon that represents the food type "berries". A specific type of berry would work as well, such as a cherry, strawberry, or blueberry. Ideally it represents the generic idea of the "berry" type of food.

### Example image (optional)

![avatar_1baee9c548e8_128](https://user-images.githubusercontent.com/5175941/54304323-84f59080-458a-11e9-93e5-47f7a3166692.png)

🍓🍒🍇

### Icon request checklist

- [√ ] This is a single icon
- [√] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [√ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [√] I have included at least one example image if it could be helpful (optional)
- [√] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> A specific type of berry would work as well, such as a cherry, strawberry, or blueberry. I

There is a request for a strawberry at #6069, please add a 👍 reaction to that request.

Closing here
