### ISSUE TITLE
Mama, just killed a man Put a gun against his head Pulled my trigger, now he's dead Mama, life had just begun But now I've gone and thrown it all away Mama, oh oh  Didn't mean to make you cry If I'm not back again this time tomorrow Carry on, carry on, as if nothing really matters

### ISSUE THREAD

**Issue by uchiharabi1** [FortAwesome/Font-Awesome#14756]
### What version and implementation are you using?

Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
![tenor](https://user-images.githubusercontent.com/556268/54418061-15a3ac00-4704-11e9-8588-5ad1a8f41e9e.gif)
