### ISSUE TITLE
wallet icon not rendering 

### ISSUE THREAD

**Issue by kstvigilante** [FortAwesome/Font-Awesome#14769]
`<i class="fas fa-wallet"></i>`
copying and pasting this doesnt render a wallet icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Of course I cannot reproduce this issue in version 5.7.2.

SVG: https://jsfiddle.net/tagliala/xr5ckmgn/1
CSS: https://jsfiddle.net/tagliala/1o7sevju/14/

[fa-wallet](https://fontawesome.com/icons/wallet?style=solid) has been introduced in version 5.0.13, so please check that you are using a version of Font Awesome >= 5.0.13

Sometimes third-party plugin/themes/libraries load an older version of Font Awesome that could override yours. Please check that this is not your case

Troubleshooting guides:
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting

I'm going to close here, but feel free to comment and if you still think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case
