### ISSUE TITLE
Icon request: scribble

### ISSUE THREAD

**Issue by jhil** [FortAwesome/Font-Awesome#14762]
### What can it be used for?

Drawing tools, freeform selections, etc. Part of the design set. Options with scribble+pencil and only scribble would be valuable. Thanks so much!

### Example images

- https://thenounproject.com/term/draw/1338973/
- https://thenounproject.com/term/draw/2271432/
- https://thenounproject.com/term/arrow/2296781/
- https://cdn3.iconfinder.com/data/icons/doodles/100/doodles-30-512.png
- http://icons.iconarchive.com/icons/franksouza183/fs/256/Actions-draw-freehand-icon.png

**Comment by aethior** [comment]
Hi @jhil,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/scribble

Regards.

cc/ @tagliala
