### ISSUE TITLE
Icon request: fa-directions

### ISSUE THREAD

**Issue by dpawlyk** [FortAwesome/Font-Awesome#14760]
### What can it be used for?

There is a "solid" (white-on-black) version of the directions icon but most signs are black-on-white.

fas fa-directions

There should be an option for a black-on-white icon.

That is:

far fa-directions

### Icon request checklist

- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is Available in FA Pro, I'm going to close here for the moment
