### ISSUE TITLE
volume-mute(f6a9) gets displayed as glass (f804). 

### ISSUE THREAD

**Issue by SirWindfield** [FortAwesome/Font-Awesome#14761]
Checked with the provided free font from this repo. The mute icon shows up as the glass icon on my machine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/1o7sevju/7/

If you think there is an issue with Font Awesome, please edit your first post and fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md). A reproducible test case will be hugely appreciated.

Please also take a look at our troubleshooting page: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Closing here, but feel free to keep commenting.

**Comment by SirWindfield** [comment]
Very strange. Well, at least I know that it is a problem on my side.

Cheers!
