### ISSUE TITLE
Icon request: octopus

### ISSUE THREAD

**Issue by massimocristofori** [FortAwesome/Font-Awesome#1477]
this is an icon that i need in my wordpress theme
![octopus](https://f.cloud.github.com/assets/4113425/735947/c7571d42-e305-11e2-8936-069af4ea140b.png)

**Comment by dustcrawler** [comment]
Since this issue is still open. Here a proper icon reference for a octopus icon.

<img src="http://icons.iconarchive.com/icons/icons8/android/256/Animals-Octopus-icon.png" alt="octopus" />

**Comment by aethior** [comment]
The original post is a very concrete icon (not animal icon) for his company's website.

@tagliala What do you think about to create a new issue for `octopus (animal)`?

**Comment by tagliala** [comment]
I'm going to close this request for inactivity.

If anyone is interested in an octopus, please open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
