### ISSUE TITLE
Social icons being blocked by uBlock Origin

### ISSUE THREAD

**Issue by GiacomoLaw** [FortAwesome/Font-Awesome#14778]
### Describe the problem

Since updating to v5 of Font Awesome, social icons are being blocked by uBlock Origin. How can I avoid this?

Issue relates to #1799

### What did you expect?

Social icons to show.

### What version and implementation are you using?

Version: v5.0.7
Browser and version: Chrome, latest GA release

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://giacomolaw.me

Simply install uBlock.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (the issue does not give a solid method to solve it)

**Comment by tagliala** [comment]
Hi Giacomo,

that is the very same issue as #1799, Font Awesome classes are included in certain blocklists included by some Ad Blockers, so 🤷‍♂️ 

Also, if the users of your website have chosen to not display social media icons by enabling social filters in uBlock origin, you should respect them.

We are not going to play cat-and-mouse games, so please consider to implement a custom solution.

I'm not going to provide a workaround here, sorry

Closing here, feel free to continue at #1799

**Comment by GiacomoLaw** [comment]
Okay, thank you!
