### ISSUE TITLE
Font Awesome Icons only printing in Black

### ISSUE THREAD

**Issue by calcagnom** [FortAwesome/Font-Awesome#14771]
Hi, i'm trying to print a page with fontawesome icons (i used fortawesome). The issue is that when you go to print, the Font Awesome icons will not print in color, but when the page is printed the icons are solid black. Is there any way to print icons with color?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think there is an issue with your CSS. Please check under the [`print` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Targeting_media_types)

Bootstrap 3.4, in example, sets this: https://github.com/twbs/bootstrap/blob/68b0d231a13201eb14acd3dc84e51543d16e5f7e/less/print.less#L14

If you still think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Closing here, but feel free to keep commenting
