### ISSUE TITLE
Icon Request: icon-download-alt

### ISSUE THREAD

**Issue by aastrouski** [FortAwesome/Font-Awesome#14776]
Can you please add a more modern Download icon as alternative. See below.

![image](https://user-images.githubusercontent.com/576008/54601924-4f045080-4a51-11e9-90ba-b25dc93c2e2e.png)

**Comment by aethior** [comment]
Hi @aastrouski,

`fa-arrow-down-to-bracket` icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/arrow-down-to-bracket

Regards.

cc/ @tagliala
