### ISSUE TITLE
no icon at fontawesome.com

### ISSUE THREAD

**Issue by mailfox** [FortAwesome/Font-Awesome#14788]
http://prntscr.com/n1fe83

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Looks like a network issue, but CDN is working fine here in Italy

![image](https://user-images.githubusercontent.com/556268/54821730-60449b80-4ca3-11e9-9d07-4c1ecde36290.png)

Could you please:
1. Retry in a short while
2. Retry inside an incognito window (to exclude third-party extensions)

If it still does not work, could you please tell us where are you from? It could be a regional issue of our CDN provider

**Comment by sensibleworld** [comment]
Hi @mailfox I'm closing this issue, as we haven't heard back. Please let us know if the problem continue.
