### ISSUE TITLE
Only "all" works CDN

### ISSUE THREAD

**Issue by nothingrandom** [FortAwesome/Font-Awesome#14789]
### Describe the problem

When using specifically only one of the solid / regular / light / brands CDN nothing shows up. When using all, it does work.

### What did you expect?

Being able to use just one of solid / regular / light / brands CDN instead of all.

### What version and implementation are you using?

Version: 5.8.1, both webfont and svg
Browser and version: Chrome on macOS

- [x] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

Don't have one, if you can't duplicate happy to share one.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but I cannot replicate.
All: https://jsfiddle.net/tagliala/6rhmuj25/6/
Solid: https://jsfiddle.net/tagliala/6rhmuj25/1/
Regular: https://jsfiddle.net/tagliala/6rhmuj25/3/
Brand: https://jsfiddle.net/tagliala/6rhmuj25/5/

Maybe you forgot to add `fontawesome.css`?

Instructions: https://fontawesome.com/start 

Free webfont solid:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/solid.css" integrity="sha384-QokYePQSOwpBDuhlHOsX0ymF6R/vLk/UQVz3WHa6wygxI5oGTmDTv8wahFOSspdm" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/fontawesome.css" integrity="sha384-vd1e11sR28tEK9YANUtpIOdjGW14pS87bUBuOIoBILVWLFnS+MCX9T6MMf0VdPGq" crossorigin="anonymous">
```

Closing here, but if you think there is an issue with font awesome feel free to comment and provide a reproducible test case
