### ISSUE TITLE
Icon request: mobile2

### ISSUE THREAD

**Issue by massimocristofori** [FortAwesome/Font-Awesome#1478]
i think mobile is not just a phone icon, it should be a tablet icon as well
![mobile2](https://f.cloud.github.com/assets/4113425/735955/f4a8e582-e305-11e2-8b39-f9a7fddb93de.png)

**Comment by sensibleworld** [comment]
I think this icon may satisfy this request: https://fontawesome.com/v6.0/icons/laptop-mobile?s=solid
