### ISSUE TITLE
user-headset icon wont display on skecth

### ISSUE THREAD

**Issue by mstomeo** [FortAwesome/Font-Awesome#14781]
I've copied the user-headset icon glyph to skecth and it displays always the question mark setting the font family to .lastresort. 

I've installed the latest fontawesome Pro from you website but this specific icon wont display. 
Other icons are working fine.

**Comment by tagliala** [comment]
Hi,

I think this comment from @sensibleworld could be helpful

> Hey folks! Font management can be notoriously tricky. Most programs aren't optimized for needing to update fonts to new versions (because most fonts don't regularly release new versions).
> 
> For those still experiencing issues here, my suggestion would be to first delete the existing Font Awesome OTF files from your font management software and then install the new OTFs files. (Make sure you've closed any applications using FA first.) Simply installing a new version on top of the old version usually won't work.
> 
> Also note that we made a couple of updates to the OTF files in version 5.7 https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#56x-to-570:

Please also take a look here: https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#icon-noshow

Long story short:
1. Uninstall Font Awesome
2. Restart your system
3. Install the latest version of Font Awesome
4. Try again.

If it still doesn't work, please provide as many information as you can, including:
1. OS version
2. Software and version
3. Font Awesome version (screenshot from Font Book or Windows control panel)

**Comment by sensibleworld** [comment]
Thanks, @tagliala! I actually don't think restarting the system is necessary. (At least in most cases.) Just making sure your apps are closed before deleting/reinstalling the fonts should do the trick.
