### ISSUE TITLE
LinkedIn Icon Square Incorrect

### ISSUE THREAD

**Issue by wccit** [FortAwesome/Font-Awesome#14790]
I want to use the square LinkedIn icon in the footer of my website. I am using the LinkedIn square code: < i class="fab fa-linkedin"></ i>

However, it is displaying the LinkedIn icon that is not in a square.
![fab fa-linkedin](https://user-images.githubusercontent.com/48834259/54833106-7181ae00-4c8b-11e9-8177-662a14f4a1b7.PNG)

I tried using the fab.fa-linkedin-in class too, and it also displays the icon without a square:
![fab fa-linkedin-in](https://user-images.githubusercontent.com/48834259/54834005-384a3d80-4c8d-11e9-9d6d-c77158cf2eee.PNG)

I am using the following:
WordPress v5.1.1
Font Awesome v5.8.0
Viewing in Chrome v72.0.3626.121

**Comment by tagliala** [comment]
@wccit it has been fixed in 5.8.1, please give a try

**Comment by wccit** [comment]
It seems that our IDX Broker plugin was overwriting Font Awesome  v5.8.1 with v4.7.0

Thank you for your assistance!
