### ISSUE TITLE
Icon Request: flag-uk

### ISSUE THREAD

**Issue by Wingo5315** [FortAwesome/Font-Awesome#14793]
I think there should be a UK flag in the style of the flag-usa icon. It could look like this:
![image](https://user-images.githubusercontent.com/25369857/54863392-fd551200-4d3f-11e9-9543-ab5c4420ab29.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I have to close this one for the moment.

Ref: #4735, #10258, #6193, #1336, and others

> But there is a USA flag!

Yes, I know.

**Comment by tagliala** [comment]
@Wingo5315 please upvote #4735, I've reopened that one
