### ISSUE TITLE
Icon Request: Can (Pepsi / Cola) Or without brand for general uses

### ISSUE THREAD

**Issue by pixieaka** [FortAwesome/Font-Awesome#14795]
![coke-v-pepsi-hed-2016](https://user-images.githubusercontent.com/17777237/54868266-6154f600-4d93-11e9-8554-2ae4f2b4ca0d.png)

**Comment by tagliala** [comment]
Hi,

I was pretty confident that this was a duplicate, but I wasn't able to find the original request... until now 😅 

Duplicate of #9217, please add a 👍 reaction to that request
