### ISSUE TITLE
Icon Request: MMA Fight hand

### ISSUE THREAD

**Issue by pixieaka** [FortAwesome/Font-Awesome#14802]
![il_570xN 1217464914_5gdf](https://user-images.githubusercontent.com/17777237/54872929-c67d0b80-4dd4-11e9-83ed-9b6e88fe065a.jpg)

![products-Red-CombatSport-Gloves](https://user-images.githubusercontent.com/17777237/54872961-60dd4f00-4dd5-11e9-9a5c-b809c6eb216b.png)

**Comment by bitedgecom** [comment]
Why is this closed? I need this.
