### ISSUE TITLE
how to generate a new icon

### ISSUE THREAD

**Issue by Gianmarco77** [FortAwesome/Font-Awesome#14814]
Hello, we have a website based on Open Cart 3 , we would like to add our logo to our icon selection. How can be done? Thanks.
![batterfly-farfalla](https://user-images.githubusercontent.com/48919679/54930662-f254da00-4f17-11e9-9148-a9416507095e.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request and fix the title?

**Comment by Gianmarco77** [comment]
Hello, we request a new icon where the object is our logo. thanks

**Comment by tagliala** [comment]
Hi,

if you want your logo in Font Awesome, please edit this request by filling in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Then, please take a look at https://fontawesome.com/community/leaderboard/brands#faqs, there is a lot of information on how icon requests work.

If you want to customize Font Awesome and add your own logo to the set, which is the best option in this specific case, take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope that helps

**Comment by sensibleworld** [comment]
@Gianmarco77 I'm closing this issue, as we haven't heard back. If you'd like to formally open a request to have your logo added to Font Awesome, please follow the instructions above. Alternately, there's some information on how to sponsor an icon at the bottom of our leaderboard page: https://fontawesome.com/community/leaderboard/new
