### ISSUE TITLE
Including svg in bundle, rather than client-side replacement

### ISSUE THREAD

**Issue by mikestopcontinues** [FortAwesome/Font-Awesome#14816]
I'm using parceljs to bundle a wordpress theme. This keeps me from being able to do server-side embedding, though I'd still prefer to avoid client-side replacement. 

Ideally, I'd like my bundler to write the SVG to disk. Bonus points if it gets the SVG elements as a single file. In either case, I could simply reference the icons in my PHP code, avoiding client-side replacement. 

I understand moving to pure svg over icon-fonts, but I suspect this is a use-case others would find useful. Apologies if there's already a solution to this issue—please point me in the right direction!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I don't know Parcel.js

We have a section of the docs about server-side rendering but it does not cover your use case: https://fontawesome.com/how-to-use/on-the-web/other-topics/server-side-rendering

> I'd like my bundler to write the SVG to disk

[fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free) package contains individual svgs under the folder `node_modules/@fortawesome/fontawesome-free/svgs/`

Does that help?

**Comment by mikestopcontinues** [comment]
Thanks, @tagliala. That works!
