### ISSUE TITLE
TRACTOR icon is not working on 5.8.1

### ISSUE THREAD

**Issue by alyssonfranklin** [FortAwesome/Font-Awesome#14828]
Any idea what could be? Trying to add the icon via sketch but its just showing text instead

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at https://github.com/FortAwesome/Font-Awesome/issues/14781#issuecomment-474762003, let me know if that fixes

If it still doesn't work, please provide as many information as you can, including:

OS version
Software and version
Font Awesome version (screenshot from Font Book or Windows control panel)

**Comment by alyssonfranklin** [comment]
Hello Tagliala, yeah, it worked, thanks, but all other FA Free fonts are now broken. 

I'm experiencing another weird issue. Lets say that I want to use the icon **facebook-f**

the system do not recognize the ligature, turning the text in something like face**fontawesome book icon**-f.

So you can imagine *user-check* or *user-cog* looks like.

**Comment by alyssonfranklin** [comment]
![Screen Shot 2019-03-28 at 8 45 54 AM](https://user-images.githubusercontent.com/590107/55162489-f2322580-5135-11e9-9977-5715de1ec84d.png)
there u go

**Comment by alyssonfranklin** [comment]
and yes, my ligature demo file is showing the same problem:
![Screen Shot 2019-03-28 at 9 01 01 AM](https://user-images.githubusercontent.com/590107/55163594-10008a00-5138-11e9-9ba7-e8379a679691.png)

**Comment by tagliala** [comment]
@alyssonfranklin I'm pretty confident that 

> ![Screen Shot 2019-03-28 at 8 45 54 AM](https://user-images.githubusercontent.com/590107/55162489-f2322580-5135-11e9-9977-5715de1ec84d.png)
there u go

Is using the wrong font family. It should be `Font Awesome 5 Brands`

**Comment by alyssonfranklin** [comment]
it worked, thanks!

**Comment by tagliala** [comment]
@alyssonfranklin glad you've solved 👍
