### ISSUE TITLE
php

### ISSUE THREAD

**Issue by Rosoldier** [FortAwesome/Font-Awesome#14829]
### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Rosoldier** [comment]
i like

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

php is already available: https://fontawesome.com/icons/php?style=brands

Please make sure that you are using Font Awesome >= 5.0.5

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

If you want to request an alternative version of the php brand, please +1 #14464 

Hope it helps

closing here
