### ISSUE TITLE
Icon request: credit card

### ISSUE THREAD

**Issue by aloisdg** [FortAwesome/Font-Awesome#14837]
Hello,

There is a lot of [credit cards](https://origin.fontawesome.com/icons?d=gallery&q=creadit-card) supported by this awesome project.
Some new or more specific players gain a lot of traction and it would be awesome to see them included.
This project ask for a request for an icon, uless strictly related icons. I think all credit card are strictly related and it make sense to group them together.

> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

[CONTRIBUTING.md#requesting-new-icons](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Here is a quick list. Feel free to link any relevent missing issue. I will keep this post updated.

# Maestro

We already have an up-to-date MasterCard icon. Lets have this one too!

Previous issue: #4266

[Wikipedia](https://en.wikipedia.org/wiki/Maestro_(debit_card))
![Logo](https://upload.wikimedia.org/wikipedia/commons/8/80/Maestro_2016.svg)

# UnionPay

It is the largest card payment organisation (debit and credit cards combined) in the world offering mobile and online payments based on total value of payment transactions, ahead of Visa and Mastercard

Previous issue: #4561

[Wikipedia](https://en.wikipedia.org/wiki/UnionPay)
![Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/UnionPay_logo.svg/1920px-UnionPay_logo.svg.png)

# Rupay

In India, 90% of credit card transactions and almost all debit card transactions are domestic; however, the cost of transactions was high due to the dominance of foreign card schemes like Visa and Mastercard. RuPay facilitates electronic payment at all Indian banks and financial institutions.

Previous issue: #9955

[Wikipedia](https://en.wikipedia.org/wiki/RuPay)
![Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/RuPay.svg/1920px-RuPay.svg.png)

# Dankort

The Dankort is the national debit card of Denmark.

Previous issue: #8460

[Wikipedia](https://en.wikipedia.org/wiki/Dankort)
![Logo](https://upload.wikimedia.org/wikipedia/commons/5/51/Dankort_logo.png)

# Mir

Mir is a national payment system established by the Central Bank of Russia by the law adopted in May 1, 2017

Previous issue: #12250

[Wikipedia](https://en.wikipedia.org/wiki/Mir_(payment_system))
![Logo](https://upload.wikimedia.org/wikipedia/commons/a/a9/Nspk-mir.png)

# Uatp

Universal Air Travel Plan, Inc. (UATP) is the airline owned payment network accepted by thousands of merchants for air, rail, hotel and travel agency payments. UATP is owned by 32 airline shareholders, issued by 26 major airlines and accepted by merchants around the world.

Previous issue: #14838

[Official website](https://uatp.com)    
[Wikipedia](https://en.wikipedia.org/wiki/Universal_Air_Travel_Plan)
![Logo](https://uatp.com/wp-content/uploads/2015/08/UATP_logo_header.png)

# T-Union

Previous issue: _coming soon_

[Wikipedia](https://en.wikipedia.org/wiki/China_T-Union) 
![Logo](https://ccard-generator.com/assets/images/CardMedium/china-t-union.png)

# InterPayment

Previous issue: _coming soon_

I didn't find any logo about InterPayment card.
The official website talked about InterPayment card as a FIS Debit Card.
FIS provides financial software, world-class services and global business solutions.
There is no mention of InterPayment on FIS' Wikipedia's page and on FIS' official website.
They are linked on [Twitter](https://twitter.com/lmtdslip/status/529647516870901760).
I think we could contact [@FisGlobal](https://twitter.com/FISGlobal) about this.

[InterPayment official website](https://interpaymentcard.com/index.cfm)
[Fis official website](https://www.fisglobal.com/)
[Fis' Wikipedia](https://en.wikipedia.org/wiki/FIS_(company))
[Fis' icon](https://upload.wikimedia.org/wikipedia/en/4/48/FIS_%28company%29_Fidelity_National_Information_Services_Inc._Corporate_Logo.svg)

Similar issue: #12815, #14260

Source:
* [Payment Card Number on Wikipedia](https://en.wikipedia.org/wiki/Payment_card_number)
* [Credit Card Generator](https://ccard-generator.com/)

Thank you for all the good work.

Cheers,

### What can it be used for?

If the other credit cards are relevent so does those. Russia and China mainly have their own provider. Currently, we exclude them by not supporting their cards. Others countries like India are also impacted by this. There is a lot of russian in Goa (Nice play to visit btw).  😄 

### Icon request checklist

- [x] This is a matched group. I will open individual issue for each icon without issue.
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi @aloisdg 

Thanks for this list, but those brands are not strictly related and have different popularity, so it is better to have individual requests for each of them

Feel free to open individual requests for the missing brands

Closing here

**Comment by aloisdg** [comment]
Hello @tagliala,

I am currently opening issue for missing card. How do you measure popularity of each card? They are not MasterCard or Visa but each have their own usage and userbase (most who are nor westerner nor english speaker). 

Sorry for the breaking of the strictly related policy, I thought that those card were related enough.

Thank you for your quick answer by the way. You are fast! :)

**Comment by tagliala** [comment]
> They are not MasterCard or Visa but each have their own usage and userbase (most who are nor westerner nor english speaker).

I know that and I respect each userbase.

If you take a look at https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+label%3A%22payment+%28category%29%22+sort%3Areactions-%2B1-desc, you will see a list of requests labeled with "payment" sorted by reactions: that could be considered our list. In fact, if a future release of Font Awesome will focus on payment methods, we can count on a dedicated leaderboard. This helps the team in either tracking requests and respecting upvotes of individual requests.

I hope that the clarification is useful, but I also have to say that the popularity of each single payment method does matter. If someone needs a not so widespread payment method, [customization](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) is the fastest way. And with the SVG framework, adding a new svg icon is [as easy as writing few lines of JavaScript](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#with-localcdn-fontawesomealljs)

**Comment by aloisdg** [comment]
>  In fact, if a future release of Font Awesome will focus on payment methods

This is a great news! Thanks for your comment. I will see what to do with the less popular ones.

**Comment by tagliala** [comment]
@aloisdg if you need all the payment methods because your application is focused on payment methods, it is much like a "weather application" situation, as described in the customization guide:

> Said so, if you need a new icon in a short while, or you need a comprehensive set of icons **(e.g., a set of weather icons to build a forecast application)** our suggestion is to customize Font Awesome.

**emphasis mine**

We eventually included a lot of weather icons, but they could not be enough for a complex weather application (e.g.: application with lunar phases, application with different wind strength)

**Comment by aloisdg** [comment]
@tagliala it make sense.
