### ISSUE TITLE
Icon request: phpfusion

### ISSUE THREAD

**Issue by RobiNN1** [FortAwesome/Font-Awesome#14836]
Official logo for PHP-Fusion CMS - https://github.com/php-fusion/PHP-Fusion | https://www.php-fusion.co.uk/home.php

### Example image
[logos.zip](https://github.com/FortAwesome/Font-Awesome/files/3276137/logos.zip)

![php-fusion-icon-3d](https://user-images.githubusercontent.com/11664877/59264817-3bc5e300-8c44-11e9-9dfb-d7ad71728d9d.png)

**Comment by RobiNN1** [comment]
+1

**Comment by FrederickChan** [comment]
+1

**Comment by iriatum** [comment]
+1

**Comment by Jimmi08** [comment]
+1
