### ISSUE TITLE
Bug: Regular weight not working in Indesign

### ISSUE THREAD

**Issue by brandonpeat** [FortAwesome/Font-Awesome#14832]
### Describe the problem

I'm a FA Pro member. I uninstalled my old OTF version of FA (5.6.3) and installed the newest (5.8.1). Brands, Light, and Solid work fine. Regular weight works in Photoshop but not in Indesign. It installs fine but Indesign can't read it for some reason. Opening up my old projects shows Font Awesome Regular as a missing font.

![Screen Shot 2019-03-28 at 9 19 21 AM](https://user-images.githubusercontent.com/28932371/55160870-a33abf00-513a-11e9-927d-2ac7f6aff967.png)

I tested older versions and reproduced this error back through 5.7.0. I had to revert to my original 5.6.3 before the Regular weight showed up in Indesign again.

### What version and implementation are you using?

Version: 5.7.0 through 5.8.1
On the Desktop
InDesign CC 14.0.1
Mac OSX 10.14.3

### Bug report checklist

- [ X ] I have filled out as much of the above information as I can
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There has been a font name change for otf files between 5.6.x and 5.7.0: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#otf-and-ttf-files

Does this comment help? 

https://github.com/FortAwesome/Font-Awesome/issues/14781#issuecomment-474762003

**Comment by brandonpeat** [comment]
Hmm, it does seem like that could be related. But no, that isn't applicable directly. I just install the OTF file directly no matter what the name is. Maybe that name change isn't being parsed correctly by Indesign. 

But the other weights are working, so it must be something with the Regular file specifically.

**Comment by tagliala** [comment]
@sensibleworld @robmadole  any idea?

I don't use InDesign

**Comment by sensibleworld** [comment]
Just tested this on my machine with the latest version of InDesign, and it seems to be working fine. 

@brandonpeat Can you try deleting the OTF from your font manager again? I would also quit out of InDesign. Then install the 5.8.2 OTFs again, and re-open InDesign.

**Comment by brandonpeat** [comment]
Ha, welp, it's working now! I tried that _exact thing_ multiple times yesterday and today, but THIS time it worked for some reason. Thanks and sorry for the hassle!
