### ISSUE TITLE
Icon request: fa-bell-ringing (youtube style bell)

### ISSUE THREAD

**Issue by emma-15** [FortAwesome/Font-Awesome#14847]
About 1,300million people use YouTube and most of them want subscribers. 
I know there is already a fa-youtube icon, but with the subscribe bell icon, people could use it as a referral link to subscribe to their youtube channel.
example: `https://www.youtube.com/channel/CHANNEL_ID?sub_confirmation=1`
![bell1](https://user-images.githubusercontent.com/48891420/55279922-a70e4300-52ec-11e9-9b0c-893752ab791f.png)
![bell2](https://user-images.githubusercontent.com/48891420/55279923-a83f7000-52ec-11e9-805c-e8e3113e5719.png)

**Comment by aloisdg** [comment]
We already ha ve a [bell icon](https://fontawesome.com/icons/bell?style=solid). IMHO, the 'ringing' bell would be a nice addition.

**Comment by qwazix** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/1202892/60968085-e5bc8c00-a324-11e9-8637-3ded75c323b0.png)

**Comment by moofawsaw** [comment]
The bell-ringing would be a great addition. Is there an update?

**Comment by tagliala** [comment]
I think this has been addressed in FA6 Pro: https://fontawesome.com/v6.0/icons/bell-on?s=solid

**Comment by aloisdg** [comment]
@tagliala so now way to get it in the free version?

**Comment by drewgeraets** [comment]
Is this a dupe of https://github.com/FortAwesome/Font-Awesome/issues/7518

**Comment by aethior** [comment]
> Is this a dupe of #7518

@tagliala please check this.

**Comment by tagliala** [comment]
I've not considered this a duplicate because of the "on" style, but they both work for the same use case. Don't know exactly what to do

@sensibleworld ?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/bell-ring?f=classic&s=solid
