### ISSUE TITLE
fa-underline not aligned

### ISSUE THREAD

**Issue by tomgie** [FortAwesome/Font-Awesome#14843]
The icon fa-underline is not aligned with other icons such as fa-bold, fa-italic, and fa-strikethrough as seen in the image below.

![image](https://user-images.githubusercontent.com/48775270/55271857-0daa4700-5282-11e9-8e02-037ee8b8b140.png)

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this.

I've compared Google docs, Font Awesome and Word 2016 and Font Awesome's underline `U` seems shifted up by a pixel. Looks like the same situation as #14025

![image](https://user-images.githubusercontent.com/556268/55274471-2560ea00-52d9-11e9-9693-c6014fd237f6.png)

The following is the proposed fix, am I right?

![image](https://user-images.githubusercontent.com/556268/55274582-f9923400-52d9-11e9-8c16-25edad3dcfb9.png)

@sensibleworld could you please take a look?

**Comment by tomgie** [comment]
I wasn't sure if there are any standards to fitting icons in a specific size but I think it would be more accurate to align the text with the others. Just an idea.

![my-proposal2](https://user-images.githubusercontent.com/48775270/55278709-c782d100-52dd-11e9-865d-7cc53b1f4c42.png)

**Comment by tagliala** [comment]
@tomgie that would not be easy because `fa-underline` is already using all the available vertical space. Check out the grid at https://fontawesome.com/icons/underline?style=solid

having B, I, U, and S of the same size will require to rewrite all those icons

**Comment by sensibleworld** [comment]
Thanks for the report, @tomgie (and the heads up @tagliala)! We're limited to our 16px grid for these, and I hesitate to "hard-code" any extra spacing or alignment directly into the icons themselves, as they need to work independently of each other.

That said, I'll definitely give these icons another look, as I can already see some improvements that would be helpful.
