### ISSUE TITLE
Are you gonna delete Google+ icon?

### ISSUE THREAD

**Issue by mattonit** [FortAwesome/Font-Awesome#14848]
A few months ago, Google announced they are going to turn off their Google+ social network. Since the FontAwesome is one of the most important dependencies of a project that I & my colleagues are working on (and it's used by around 800 000 developers), we're worried about what will gonna happen with the Google+ icons. Will G+ icon be deleted? Is it still safe to use?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have no plans to remove the Google+ icon

Hope it helps

Closing here
