### ISSUE TITLE
fas-ice-cream isn't working

### ISSUE THREAD

**Issue by bassman88** [FortAwesome/Font-Awesome#14853]
### Describe the problem

We tried using fas-ice-cream, its not working

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.
CSS Demo: https://jsfiddle.net/tagliala/6rhmuj25/11/
SVG Demo: https://jsfiddle.net/tagliala/we7gtcvk/16/

[ice-cream](https://fontawesome.com/icons/ice-cream?style=solid) has been introduced in Font Awesome 5.7.0, so please double check that you are using Font Awesome 5.7.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
