### ISSUE TITLE
Icons for Salesforce, Jira, and Confluence are not working. 

### ISSUE THREAD

**Issue by Richard-Barrett** [FortAwesome/Font-Awesome#14858]
I posted the issue in Stackoverflow as well to see if anyone might have an issue with using it.
But essentially I cannot use the following icons within the following dashboard panel.

```
menuItem("Salesforce", icon = icon("salesforce"), 
                                   href = "https://#######.my.salesforce.com/"),
```

Please advise on [https://stackoverflow.com/questions/55435687/trouble-with-certain-icons-loading-within-the-dashboard-menu-as-menuitemname]

**Comment by Richard-Barrett** [comment]
https://stackoverflow.com/questions/55435687/trouble-with-certain-icons-loading-within-the-dashboard-menu-as-menuitemname

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[Salesforce](https://fontawesome.com/icons/salesforce?style=brands) has been introduced in Font Awesome 5.8.0
[Confluence](https://fontawesome.com/icons/confluence?style=brands) has been introduced in Font Awesome 5.6.0

As the first thing, please check that you are using Font Awesome >= 5.8.0

> menuItem("Salesforce", icon = icon("salesforce"), 
                                   href = "https://#######.my.salesforce.com/"),

Sorry but I don't know what the above line of code is trying to do. It does not look like any of the Font Awesome approach I know. Is this some kind of framework / third party application?

Ref:
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by Richard-Barrett** [comment]
It’s the reference code I am using in a shiny web application I am developing out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tagliala** [comment]
Any chance to see the actual HTML output of that code?

**Comment by Richard-Barrett** [comment]
Do you want the r code or the html output from inspect tool?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tagliala** [comment]
the html output from inspect tool

**Comment by Richard-Barrett** [comment]
Hey Sorry I have not been able to to get to this until now. 
As I have been building out other things, in any event here is the requested output with the icon called:
I had to use wget and then I pulled out and copied out the chunk of data where things are messing up at.

`              <li>
                <a href="https://mirantis.my.salesforce.com/" target="_blank">
                  <i class="fa fa-salesforce"></i>
                  <span>Salesforce</span>
                </a>
              </li>
              <li>`

**Comment by avishshah** [comment]
i can help u

**Comment by Richard-Barrett** [comment]
In terms of your help what can you tell me in terms of making the icon work?

Many Thanks,

Richard Barrett

Mirantis - L1 Engineer
Phone:1+(737)-999-5094
Texas A&M University - Central Texas: B.S. and M.S. in Liberal Studies
Texas A&M University - Corpus Christi: Master's in Business Administration

DISCLAIMER: "This email, any reply, or any forwarded communications and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. Also, by receipt of this message, you agree to indemnify and hold me and any affiliated organization, institution, and business harmless of any and all liability and/or damages for the views expressed within this email and/or any attachments that may cause harm. You also agree to not use this message or any part in any type of arbitration or litigation proceedings. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited."


________________________________

**Comment by tagliala** [comment]
@Richard-Barrett sorry for the late reply

> `<i class="fa fa-salesforce"></i>`

This is not the proper markup.

Please fix your code generator and take in consideration the font prefix (`fab` for brands)

Ref:
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
