### ISSUE TITLE
sim-card needs tweaking

### ISSUE THREAD

**Issue by Garconis** [FortAwesome/Font-Awesome#14863]
The sim-card icon has the notch in the wrong side/corner.

https://github.com/FortAwesome/Font-Awesome/issues/2445#issuecomment-446586297

**Comment by sensibleworld** [comment]
Thanks, @Garconis! I’ll get this fixed up.

**Comment by sensibleworld** [comment]
Fixed in 5.8.2 https://fontawesome.com/icons/sim-card?style=solid
