### ISSUE TITLE
Icon request: toilet paper "under" version

### ISSUE THREAD

**Issue by danrydell** [FortAwesome/Font-Awesome#14864]
Although the preference of **over** seems to be dominant, there is inconclusive data on the subject, with preferences of **under** starting from as much as 49% in some polls. I think a toilet paper under version is really needed.

More on the subject: https://en.wikipedia.org/wiki/Toilet_paper_orientation

**Comment by DiemenDesign** [comment]
Except for this:
https://www.businessinsider.com.au/patent-shows-right-way-to-hang-toilet-paper-2015-3?r=US&IR=T

I have seen other original patents that I could not be bothered to find the show Over as the original Patent.

**Comment by danrydell** [comment]
The intention of the patent proves nothing. Think about this hot dog bun warmer patent https://patents.google.com/patent/US1690926 and the imaginative use people have made of it. Once in the open is out to the world to decide an object's use.

Be that as it may, the fact remains that a huge percentage of people are disenfranchised by the lack of an _under_ icon. Font-Awesome should not cater to XIX audiences, but to current ones.

I believe it was JFK who said: "If we cannot now end our differences, at least we can help make the world safe for **diversity**." [ John Fitzgerald Kennedy, circa sometime before November 22, 1963 12:30pm]

**Comment by glimpsedchaos** [comment]
Out in the open, those who are "disenfranchised" could do what people do in the real world... turn the roll over. Example on the page when you scroll down: [https://fontawesome.com/icons/toilet-paper?style=solid](url)

**Comment by sensibleworld** [comment]
As someone who has taken a stance on this in the past (https://twitter.com/sensibleworld/status/913198085110665216), it pains me to say that this is a valid request. ;)

I'll get this icon in the queue.

**Comment by sensibleworld** [comment]
Hey folks. This is now available as part of the v6 alpha: https://fontawesome.com/download
