### ISSUE TITLE
Icon update: Facebook Messenger

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#14866]
A while ago, the Facebook Messenger logo was updated to be less charp with a bolder lighting within. Font Awesome should reflect that change: https://en.facebookbrand.com/assets/messenger/.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

**Comment by talbs** [comment]
Thanks for the heads up about this, @Studio384 and @tagliala. We've got this update ready and it'll be out in the next version we release. 😄

**Comment by talbs** [comment]
Okay, the `facebook-messenger` brand icon has been updated in our latest release, [5.8.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.2) - https://fontawesome.com/icons/facebook-messenger.

Thanks for bringing this to our attention. :smile:

**Comment by tagliala** [comment]
This icon will also receive a tweak in the next release of FA to fix proportions when used together with the new Facebook logo
