### ISSUE TITLE
npm.fontawesome is down?

### ISSUE THREAD

**Issue by aviaryan** [FortAwesome/Font-Awesome#14868]
I have a pro license of FontAwesome and I am trying to do a `yarn add` but I see this error.

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.7.2.tgz: Request failed \"401 Unauthorized\"".
```

npm.fontawesome.com looks down as per https://downforeveryoneorjustme.com/npm.fontawesome.com.

![Screen Shot 2019-04-09 at 8 23 33 PM](https://user-images.githubusercontent.com/4047597/55810550-62ad4f00-5b05-11e9-9954-d0f9e42010e8.png)

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

It is actually working for me in Italy, but I'm getting the same results as yours here

![image](https://user-images.githubusercontent.com/556268/55811384-561afd80-5ae9-11e9-97ef-2a84bd268e86.png)

I will inform the team.

Please if someone else is having issues upvote this

**Comment by tagliala** [comment]
@aviaryan did you check your AUTH TOKEN and `.npmrc` as per https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro ?

(do not share your token here)

**Comment by aviaryan** [comment]
@tagliala Thanks for getting back so quick. Yes, it's correct as per the `per-project` npmrc format.

**Comment by tagliala** [comment]
Do you live in India? I'm asking because that could be a local issue

Also, I think that errors reported by websites are normal, because page answers with 401 instead of 200.

Anyway, I've reported this issue to the team, let's wait.

**Comment by robmadole** [comment]
Yes, we can't use sites like `downforeveryoneorjustme.com` or Uptrends because this service does not behave like a normal website.

@aviaryan send us a message at hello@fontawesome.com and we can help you out since this is security related. I'm going to close it here in favor of that channel.

**Comment by aviaryan** [comment]
@robmadole Ok, just sent the email.

**Comment by bartoszhernas** [comment]
Is there a status page for it? It is down again, and our build process fail now :( 

```
62 error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/pro-light-svg-icons-5.11.2.tgz: ESOCKETTIMEDOUT".
```

**Comment by daniandl** [comment]
Very annoying how many times this has broken my builds...
Can we get an update on when the new infrastructure is planned?

**Comment by robmadole** [comment]
We have it scheduled for next week.
