### ISSUE TITLE
Icon request: icon-chef

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#14873]
Hi, it could be useful to have an icon which represent the chef's category, like the ones below
![chef](https://user-images.githubusercontent.com/7620920/55884111-c6885400-5ba7-11e9-840c-1e0e7c409044.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2598, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
