### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by NepCono** [FortAwesome/Font-Awesome#14874]
### What can it be used for?

I was wondering if it could be possible to add the allergens icons.
This would be handy for menu cards for restaurants for instance.

### Example image (optional)

Example.
https://erudus.com/standardised-food-allergy-icons/

### Icon request checklist

Please vote :-)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13383, please take a look at that request

Closing here
