### ISSUE TITLE
Wordpress solid icon is missing

### ISSUE THREAD

**Issue by MrAcalf** [FortAwesome/Font-Awesome#14876]
I believe the wordpress icon is missing from the free solid icons pack. Someone fix this please, if this is really a mistake and not something Intentionally removed.

[Free solid svg Icons](https://github.com/FortAwesome/Font-Awesome/tree/master/js-packages/%40fortawesome/free-solid-svg-icons)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

wordpress is part of brand icons: https://github.com/FortAwesome/Font-Awesome/tree/master/js-packages/%40fortawesome/free-brands-svg-icons

Hope it helps

Closing here, but if it doesn't answer your question feel free to comment
