### ISSUE TITLE
icon request: nodejs, ruby on rails, aws icons, dreamhost, dream objects, mysql

### ISSUE THREAD

**Issue by mikedevita** [FortAwesome/Font-Awesome#1487]
I currently use all of these logos on various projects in the footer, it'd be great to have them in some  freaking fontawesome awesome icons

**Heres an example:**

![image](https://f.cloud.github.com/assets/2991640/747811/7921ffc8-e474-11e2-8b26-349c8477081d.png)

**Here's the list again..**
- nodejs
- ruby on rails
- aws icons
- dreamhost
- dream objects
- mysql

**Comment by dimanyc** [comment]
+1. Any updates on this?

**Comment by stevefuller** [comment]
+1 for dreamhost
![dh_icon-a-2014](https://cloud.githubusercontent.com/assets/12478484/13581597/963c5104-e475-11e5-95e8-c214882290f3.png)

**Comment by tagliala** [comment]
Locking here :lock: 

https://github.com/FortAwesome/Font-Awesome/issues/1487#issuecomment-32025881

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
