### ISSUE TITLE
Icon request: epicgames-logo

### ISSUE THREAD

**Issue by nahasco** [FortAwesome/Font-Awesome#14882]
### What can it be used for?

At game stores

### Example image (optional)

![image](https://user-images.githubusercontent.com/49368477/55980297-d5046780-5c9c-11e9-9349-836130eaefdf.png)
![image](https://user-images.githubusercontent.com/49368477/55980389-0b41e700-5c9d-11e9-9435-2129fe6d06c3.png)
![image](https://user-images.githubusercontent.com/49368477/55980410-1563e580-5c9d-11e9-9060-d6ad89b70ae2.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by shaderwitch** [comment]
+1 request, since EGS is used along-side Steam, Xbox, Playstation etc to advertise on game websites it would be useful to have Epic's Store Logo in Font-Awesome.
