### ISSUE TITLE
New social media icons

### ISSUE THREAD

**Issue by zebulon888** [FortAwesome/Font-Awesome#14880]
How about new ICONS for:
GAB (https://gab.com)
DISSENTER (https://dissenter.com)
MINDS (https://www.minds.com/)
STEEMIT (https://steemit.com/)
BITCHUTE (https://www.bitchute.com)
DTUBE (https://d.tube/)

**Comment by sensibleworld** [comment]
Hi @zebulon888! The best way to request new icons is to follow our icon request form here: https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md
