### ISSUE TITLE
Icon Request: annotation

### ISSUE THREAD

**Issue by chitgoks** [FortAwesome/Font-Awesome#14886]
annotate or annotation

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

Please also provide an example of the icon you are thinking to

**Comment by chitgoks** [comment]
sample annotate image like this

im not really sure what the right icon for annotation is. but those same annotations in the pdf. maybe a mix of different shapes like triangle square and circle perhaps
![annotate](https://github.com/user-attachments/assets/38d7a512-72cc-4c9d-8892-4f19ad79ab93)
