### ISSUE TITLE
 SVG & JS results in enormous icons in Reader View in Firefox

### ISSUE THREAD

**Issue by skyfaller** [FortAwesome/Font-Awesome#14899]
### Describe the problem

I sprinkled Font Awesome SVG icons liberally through a document. At some point I decided to look at the document in Reader View in Firefox. To my surprise the document became unreadable because each icon was now huge, the width of the screen.

### What did you expect?

I expected the icons to not show up at all, they are graphics that ought to be stripped out in Reader View. Safari and the mobile version of Chrome doesn't show the icons in their reader views.

### What version and implementation are you using?

Version: v5.8.1
Browser and version: Mozilla Firefox 66.0.3 (latest stable version) and the latest nightly version 68.0a1 (2019-04-15) (64-bit). Both on macOS Mojave 10.14.4 (18E226), but I don't think that matters.

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://codepen.io/skyfaller/pen/EJbLjG

(1) View the page in debug mode in Firefox: https://s.codepen.io/skyfaller/debug/EJbLjG/PBMNWNOXEXgr

(2) Then toggle Reader View.

(3) Observe enormous icons that reduce readability.

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I can confirm.

Since the debug view expired, I've made a copy of your test case at https://tagliala.github.io/fa14899.html

I don't know if we can do something about that.

Maybe detect that it is a reader view mode and do not replace icons with svgs?

@robmadole thoughts?

**Comment by skyfaller** [comment]
I filed a bug for Firefox as well, https://bugzilla.mozilla.org/show_bug.cgi?id=1545453

**Comment by skyfaller** [comment]
This appears to have been fixed in Readability https://github.com/mozilla/readability/issues/541

I no longer experience this issue in current versions of Firefox.

**Comment by tagliala** [comment]
Thanks for letting us know
