### ISSUE TITLE
Icon request: single antenna

### ISSUE THREAD

**Issue by nothingrandom** [FortAwesome/Font-Awesome#14901]
The current antenna look to be "large" antenna; ie, broadcast tower. I'd be nice to have a small / single antenna icon

For example:
![antenna](https://cdn3.iconfinder.com/data/icons/hotel-5-1/48/240-512.png)
![wlan antenna](https://images.iconfu.com/sets/8-omni/icons/wlan_antenna_icon.png)
![radiate antenna](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi2cA6bKZAlx3XUsyEJU5Xy-tHAzpNWLjB_pvWjMX6isJXoX8pGA)

**Comment by aethior** [comment]
Hi @nothingrandom,

This icon has been updated in v6.0.0-BETA1.
Check https://fontawesome.com/icons/tower-broadcast

Regards.

cc/ @tagliala

**Comment by nothingrandom** [comment]
@aethior looks fantastic! Very happy to see this added!
