### ISSUE TITLE
Unicode in CSS "content" displays old icon design

### ISSUE THREAD

**Issue by giliardgomes** [FortAwesome/Font-Awesome#14905]
When I use one Unicode from a icon on CSS attribute "content", the icon shows a old version instead new 5.0.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

**Comment by giliardgomes** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

I already filled, this topic contains the description of the bug.

**Comment by tagliala** [comment]
Sorry, this is what I see
![image](https://user-images.githubusercontent.com/556268/56235778-60f50580-6088-11e9-8966-76c6b3810c73.png)

If the aboce is correct, please provide more information

This is the template to fill out:
```
### Describe the problem

<!--- What happened? What are you seeing? How did you arrive here? -->

### What did you expect?

<!--- How would you like this to work instead? -->

### What version and implementation are you using?

Version: <!--- Give us the version number here -->
Browser and version: <!--- If applicable give us the browser specs -->

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

<!--- Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever -->

<!--- Describe any details about the test case that we need to know like "whatever you do, don't click the red button" -->

### Bug report checklist

- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

```

**Comment by giliardgomes** [comment]
Ok then...

Screenshots:

Icon SVG: https://i.imgur.com/LzrIDaq.png
Icon using UNICODE in CSS (content: 'f073';) shows the old icon: https://i.imgur.com/zrRXRoh.png

v5.8.1

See (https://www.youni.com.br/#numbers) the icons of calendar and wi-fi, on hover of the element shows the same icon in big size, but isn't no more SVG, change to unicode ON CSS, and that Unicode shows the icon in old FontAwesome,  (v4.7 I think).

**Comment by tagliala** [comment]
Ok, got it, thanks

Please note that there is a plugin that is loading an older version of Font Awesome

```
https://www.youni.com.br/wp-content/plugins/elementor/assets/lib/font-awesome/css/font-awesome.min.css?ver=4.7.0
```

We do not provide support for third-party themes / plugins / libraries / extensions

We have an official wordpress plugin that could help: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress

Hope it helps

Closing here, but feel free to comment if you need more information
