### ISSUE TITLE
Unable to purchase font-awesome

### ISSUE THREAD

**Issue by d3signmonk3y** [FortAwesome/Font-Awesome#14907]
I'm trying to purchase a Pro license but I keep getting the error "We couldn't process your order. [object Object] After fixing the issue you can try again." 

![image](https://user-images.githubusercontent.com/1819320/56256918-9efa2580-6098-11e9-8967-7948097943cf.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the inconvenience.

Please also send an email at hello@fontawesome.com

Let me know here if you don't receive an answer in the next 8/9 hours

**Comment by sensibleworld** [comment]
Closing, as we haven't heard back. @d3signmonk3y If you're still experiencing issues, please drop us a note at hello@fontawesome.com Thanks!
