### ISSUE TITLE
SVG needed for CSS?

### ISSUE THREAD

**Issue by garretwilson** [FortAwesome/Font-Awesome#14915]
The [documentation](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself) for "Using Web Fonts with CSS" says:

> Copy the entire `/webfonts` folder …

But the `/webfonts` folder also contains the huge `*.svg` files, such as `fa-solid-900.svg`. Why do I need these files if I'm using web fonts with CSS?

Can I safely delete the `*.svg` files if I'm only using web fonts with CSS? If so, perhaps the documentation should be updated to clarify this.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> But the /webfonts folder also contains the huge *.svg files, such as fa-solid-900.svg. Why do I need these files if I'm using web fonts with CSS?

That is the webfont file in svg format. It is not related to the SVG framework.

svg is needed by some ancient browsers as per https://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/

If you require a modern browser feel free to remove the .svg file and edit the font-face accordingly

Eg:

https://github.com/FortAwesome/Font-Awesome/blob/master/css/all.css#L4324

From:
```css
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }
```

to:
```css
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"); }
```

According to the browsers supported by your application, you may also remove .eot and .ttf

Ref:
- https://caniuse.com/#search=woff
- https://caniuse.com/#feat=svg-fonts

Hope it helps

Closing here

**Comment by garretwilson** [comment]
> That is the webfont file in svg format. It is not related to the SVG framework.

Ah, thanks for the clarification. This is not obvious.

> If you require a modern browser feel free to remove the .svg file and edit the font-face accordingly

Wait, I can't just leave out the SVG files? I have to edit the Font Awesome CSS source code, and then re-minimize it?

But what bad will happen if I just delete the SVG files and only use modern browsers? They will never even request the SVG files, will they? So is it really _required_ that I edit the CSS? It would just break on old browsers, but it would continue to work on new browsers with no problem, right?

> According to the browsers supported by your application, you may also remove .eot and .ttf

Here again, can I just delete the font files without modifying the CSS? Will it continue to work fine on new browsers, and only break on old browsers?

Besides, old browsers would simply try to load the SVG/EOT/TTF files and not find them, right? Why would that hurt? I would guess it would simply load the page without the fonts, and maybe log a warning in the console, but visibly it would be no different than removing the references from the CSS would it?

And can I strongly suggest that all this be documented? This information is not obvious from the documentation, and I would imagine it is a recurring question. At least it would be useful to many people.

**Comment by tagliala** [comment]
> But what bad will happen if I just delete the SVG files and only use modern browsers? They will never even request the SVG files, will they? So is it really required that I edit the CSS? It would just break on old browsers, but it would continue to work on new browsers with no problem, right?

Right.

But the same will happen if you load the .svg files: they will be there, only ancient browsers will load them. Are really ~1.2MB too big for your hosting?

> Here again, can I just delete the font files without modifying the CSS? Will it continue to work fine on new browsers, and only break on old browsers?

Yes, you can.

**Comment by garretwilson** [comment]
Thanks for the clarifications, @tagliala .

> Are really ~1.2MB too big for your hosting?

The hosting is not what I'm worried about. I don't want to mess with these big, unnecessary (for us) files in our source control repository (Git). Think about how much room in history will be taken up by these with every incremental change. Sure, maybe some of the SVG changes will only store the delta. Maybe even some of the binary files. And yes I could use LFS. Or…

… or I could just delete them because I have no use for them. :)

So if I edit the CSS files not to reference the files, old browsers won't tried to load those files. If I don't edit the CSS files but still remove the assets, old browsers will attempt to load the files but can't, but the page will still look the same. So I don't see any purpose in editing the CSS files. Thanks again for your clarification; the initial explanation seemed to imply that editing the CSS files was something that was necessary.

And lastly, let me reiterate that this is useful, non-obvious information. It really should be part of your public documentation. Is this something that I can help do?
