### ISSUE TITLE
Icon request: Join button

### ISSUE THREAD

**Issue by dangolf44** [FortAwesome/Font-Awesome#14917]
### What can it be used for?

We are looking to put a "join" button on all of our websites. Basically just a white circle with dark blue text that says join. If you go to www.af.mil or any air force website you can see the exact color blue we are looking for. This will be used as an icon on all websites ending in af.mil about 350 currently. It will link to our recruiting page for people interested in joining the Air Force. 

### Icon request checklist

- [ICON] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ JOIN BUTTON] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ YES ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes] I have included at least one example image if it could be helpful (optional)
- [ YES] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hi there! We typically try to avoid including words within our icons. It seems like this request would be a solution better implemented in CSS.
