### ISSUE TITLE
<i class="fal fa-donate"></i>

### ISSUE THREAD

**Issue by jasbin** [FortAwesome/Font-Awesome#14911]
the donate icon doesnot work <i class="fal fa-donate"></i>
it should be <i class="fas fa-donate"></i> instead
please change it

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate.

5.8.1 SVG: https://jsfiddle.net/tagliala/e1bfz6gc/10/
5.8.1 CSS: https://jsfiddle.net/tagliala/64hzm2wx/1/

Given that [fa-donate](https://fontawesome.com/icons/donate?style=solid) has been introduced in FA 5.0.9 and the light style is a Font Awesome Pro feature, I have three guesses for your issue:

-  Your application is using a version of Font Awesome older than 5.0.9
-  Your application is using Font Awesome 5
-  Your application is properly loading the latest Font Awesome 5 Pro assets but there is a third party plugin loading an older version or a conflicting version.

If you still think there are issues with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Closing here, but feel free to comment
