### ISSUE TITLE
Icon request: fas fa-update

### ISSUE THREAD

**Issue by ronitovi** [FortAwesome/Font-Awesome#14929]
Looking for an "update" icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Maybe an icon representing an update action is already here: https://fontawesome.com/icons?d=gallery&q=update

Could you please fix this request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

Please also provide a single color example of the icon you have in mind

**Comment by aethior** [comment]
Hi @ronitovi,

As update icon is usually used [**fa-rotate**](https://fontawesome.com/icons/rotate) icon.

Regards.
