### ISSUE TITLE
Icon request: My Kill

### ISSUE THREAD

**Issue by artuupl** [FortAwesome/Font-Awesome#14926]
I have my own forum and its characteristic icon distinguishes it above all else. It would be nice if it was placed on the Font Awesome platform in the form of `Brand`. In the near future I intend to promote my project - this is the forum. I did my best during its creation, and here is its result: https://mykill.pl/assets/logo.png

**Comment by Artuuuu** [comment]
Could I know the current status? Will the icon be added and how does it go?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
