### ISSUE TITLE
Mailchimp icon - update needed

### ISSUE THREAD

**Issue by ecksteing** [FortAwesome/Font-Awesome#14938]
The Mailchimp 'Freddie' logo has been amended by Mailchimp (e.g. no 'M' on hat, other design changes https://mailchimp.com/design/). Would love to see the FontAwesome Mailchimp icon updated to reflect the new Mailchimp design.

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

**Comment by talbs** [comment]
Thanks, @ecksteing and @tagliala. I'll get this brand icon updated and we'll include it in our next release coming soon.

**Comment by talbs** [comment]
Okay, the `mailchimp` brand icon has been updated in our latest release, [5.8.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.2) - https://fontawesome.com/icons/mailchimp.

Thanks for bringing this to our attention. :smile:
