### ISSUE TITLE
Icon request: globe-sync

### ISSUE THREAD

**Issue by ronitovi** [FortAwesome/Font-Awesome#14931]
### What can it be used for?

Can be used to indicate any type of update. 

### Example image (optional)

https://i1.wp.com/macmule.com/wp-content/uploads/2015/11/SoftwareUpdate.png?w=256&ssl=1

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve a similar icon with power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/we7gtcvk/38/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by xmuskrat** [comment]
Maybe it'd be cool to offer a supplemental library of virtual icons, that are just pre=setup power transforms, masking and layers.   Since you're already building them in a lot of these issues anyway.

**Comment by ronitovi** [comment]
Hi again,
first of all, thanks for all your help an reply.

Unfortunately, I must say that I gave up using power transforms, masking
and layering stuff right after I got them working due to dramatically
reduced browser performance - even tho on a very good computer (i7 4790K
CPU with GTX 570 graphic card on a very strong motherboard)
On a particular page, I needed to use lots of them in a table (one for each
row with 100+ rows) and the loading (rendering) performance of the page has
gone terribly poor. That stuff literally made the page freeze for at least
1.5 secs while rendering stage.
Then I decided to make my own layer+mask stuff with pure css code, it
actually worked like a charm but this time the data (content-lenght) of the
page has increased way too much because I needed to use several divs and at
least two of <i> font-awesome DOM elements for each icon.
So finally I decided to remove all those and use a regular .jpg version
instead and the problem has been solved.

Anyway, thank you again for your interest. I really appreciate your work, I
just wanted to give you a feedback about this. In short, power transforms,
masking and layering may cause problems on a big scale.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
