### ISSUE TITLE
I need the google scholar icon 

### ISSUE THREAD

**Issue by MERCEDESMK** [FortAwesome/Font-Awesome#14934]
WHy do you always close this request?  If you closed once for 4 years ago, and we continue to ask for it. Why don't you open it again?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`google-scholar` has been requested in #541, which is **not** closed.

google-scholar has been highly requested during these years.

Here it is the answer to your question: https://github.com/FortAwesome/Font-Awesome/issues/541#issuecomment-446348271

We try our best to follow brand guidelines, if you can find any official resource for the Google scholar logo, please post it in #541 and we will be happy to take a look.

Hope it helps, closing here
