### ISSUE TITLE
Icon request: StatusBar Icons

### ISSUE THREAD

**Issue by steven-tk** [FortAwesome/Font-Awesome#1494]
iPhone & Android Status Bar Icons (wifi level, connection level, battery level/charging, ...) would be much appreciated! (and many thanks for the work done so far!!)

**Comment by mihib** [comment]
+1 for charging battery

**Comment by aethior** [comment]
I think we considered this issue solved.

In the [energy category](https://fontawesome.com/icons/categories/energy) there are some battery level icons and in [conectivity category](https://fontawesome.com/icons/categories/connectivity) there are also some wifi and signal level icons

cc/ @tagliala

**Comment by tagliala** [comment]
yes, this should be closed

If there are missing icons, feel free to fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before
