### ISSUE TITLE
Icon request: Chatbot icon

### ISSUE THREAD

**Issue by anithats1988** [FortAwesome/Font-Awesome#14941]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

Please also provide an example of the icon you have in mind

**Comment by tagliala** [comment]
let's use #15006
