### ISSUE TITLE
fab fa freecodecamp

### ISSUE THREAD

**Issue by royalgreen50** [FortAwesome/Font-Awesome#14944]
![fafab problem](https://user-images.githubusercontent.com/48810044/56735661-b8037600-672b-11e9-904b-cb312ffe0d71.PNG)

I have and extra piece.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.

CSS (5.8.1): https://jsfiddle.net/tagliala/6rhmuj25/20/
SVG (5.8.1): https://jsfiddle.net/tagliala/we7gtcvk/40/

Please double check your css for extra spaces or underline text decoration

If you still think there is an issue with Font Awesome, please provide a reproducible test case and fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Hope it helps

Closing here, but feel free to comment
