### ISSUE TITLE
Icon request: icon-cactus

### ISSUE THREAD

**Issue by Epistol** [FortAwesome/Font-Awesome#14940]
### What can it be used for?

To describe a cactus, or any kind of desert / arid place (or even for a 404 page why not).

### Example image

https://www.istockphoto.com/fr/photos/cactus
https://www.pinksandgreen.co.uk/wp-content/uploads/2017/07/cactus-money-box.jpg
https://www.la-pilounette.com/wp-content/uploads/2017/03/cactus-pictures-8.jpg

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cactus?style=solid
