### ISSUE TITLE
calendar-week not displaying through CDN

### ISSUE THREAD

**Issue by ericmoolin** [FortAwesome/Font-Awesome#14958]
This might be an issue for only me, but when I attempt to load calendar-week through the CDN no content loads. Other icons are fine. It also appears to work fine as an SVG.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.

SVG: https://jsfiddle.net/tagliala/we7gtcvk/42/
CSS: https://jsfiddle.net/tagliala/6rhmuj25/22/

Please note that calendar-week has been introduced in version 5.6.0, so double check that you are using Font Awesome >= 5.6.0

Please also note that third-party themes/plugins/libraries may load an older version of font awesome that might take precedence on your own up-to-date version

Hope it helps

Closing here, but feel free to keep commenting

If you still think there is an issue with Font Awesome itself, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

**Comment by ericmoolin** [comment]
Sorry, I did not realize my version number was wrong on this project!

CL SIMPLEX
Eric Moolin
Creative Director
Email eric@clsimplex.com
Address #108 - 713 Columbia Street, New Westminster
Phone 778.862.3742 <7788623742>
Site https://clsimplex.com
