### ISSUE TITLE
Different type signature when using relative import

### ISSUE THREAD

**Issue by carpben** [FortAwesome/Font-Awesome#14952]
### Describe the problem

In a React Typescript project. 
I have a component IconW which receives only the icon:  
```tsx
interface IconWProps extends IStyledComponentProps {
	icon: IconDefinition
}

const IconW: DRSFC<IconWProps> = ({ icon, stl }) => {
   return (
		<Box stl={stl}>
			<FontAwesomeIcon icon={icon}/>
		</Box>
   )
}
```
Then in other components I do the following: 
```tsx
import {faTimes} from "@fortawesome/pro-light-svg-icons"
class SomeComponent {
  render(){
    return (
      <div>
         ....
         <IconW icon={faTimes} />
      </div>
    )
  }
}
```

This works well. The problem starts when I try to make a relative import to minimize the bundle 
```tsx
import faTimes from "@fortawesome/pro-light-svg-icons/faTimes"
class SomeComponent {
  render(){
    return (
      <div>
         ....
         <IconW icon={faTimes} />
      </div>
    )
  }
}
```
the icon attribute is marked by typescript, and the error states: "Property 'icon' is missing in type 'typeof import("c:/Users/carpb/projects/gw/gw-ts/node_modules/@fortawesome/pro-light-svg-icons/faTimes")' but required in type 'DRObject<IconDefinition>'.ts(2741)"
![image](https://user-images.githubusercontent.com/13496178/56851345-92869000-6916-11e9-984c-28fb32741441.png)

### What did you expect?
Same behavior for both import types, same type signature. 

### What version and implementation are you using?
from package.json
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/pro-light-svg-icons": "^5.5.0",
    "@fortawesome/pro-regular-svg-icons": "^5.5.0",
    "@fortawesome/pro-solid-svg-icons": "^5.5.0",
    "@fortawesome/react-fontawesome": "^0.1.3",

Version: 
Browser and version: 

- [x ] SVG with JS

### Bug report checklist

- [ x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
I don't think it's necessary, but will be done upon demand. 
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot help directly, but:

> The problem starts when I try to make a relative import to minimize the bundle

The tree shaking features should work also with

```js
import {faTimes} from "@fortawesome/pro-light-svg-icons"
```

Or, at least, it works for me

@robmadole @mlwilkerson any help here?

**Comment by carpben** [comment]
Thanks @tagliala. 
As far as I know a relative import is cheaper. I base it on https://stackoverflow.com/questions/35250500/correct-way-to-import-lodash and my experience, checking the analysis of the bundle size.

**Comment by tagliala** [comment]
You're welcome.

Maybe this would help, too: https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking#issues

```
import { faCoffee } from '@fortawesome/free-solid-svg-icons/faCoffee' // <-- note the extra faCoffee there
```

do you get the same result if you replace

```js
import faTimes from "@fortawesome/pro-light-svg-icons/faTimes"
```

with

```js
import { faTimes } from "@fortawesome/pro-light-svg-icons/faTimes"
```

?

**Comment by carpben** [comment]
@tagliala , 
I just came across relevant information. It seems a bit more complex. 
https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/
```ts
import {obj} from "package"
```
Allows tree shaking. But it might require to change babel-preset-env which isn't possible on the Create-React-App I'm using.

**Comment by carpben** [comment]
@tagliala ,
Your suggestion 
```ts
import {faTimes} from "@fortawesome/pro-light-svg-icons/faTimes"
```
solves the problem. 
Thanks again.
