### ISSUE TITLE
Icon request:  fa-arrows-from-line-horizontal and fa-arrows-to-line-horizontal

### ISSUE THREAD

**Issue by Dommar92** [FortAwesome/Font-Awesome#14959]
Hi, I'd suggest an icon set like that:

![splitmerge](https://user-images.githubusercontent.com/1678813/56946062-6bec7300-6b29-11e9-8b2c-c32139896e52.png)

It can be used to describe a split/merge operation when dividing surfaces.
By now there are only the single arrow ones.

**Comment by dbarwikowski** [comment]
I'd like to see also some icons like:
![a](https://cdn2.iconfinder.com/data/icons/split-arrows/512/xxx037-128.png) ![a](https://image.flaticon.com/icons/png/128/32/32232.png)

**Comment by cfourt** [comment]
I was just about to draft an issue and found this! This would be super useful with merging and splitting entries. Code merge and branch work only for cases where the viewer is privy to coding terms.

**Comment by aethior** [comment]
The requested icons are [**fa-arrows-from-line**](https://fontawesome.com/icons/arrows-from-line) and [**fa-arrows-to-line**](https://fontawesome.com/icons/arrows-to-line) in horizontal version.

cc/ @tagliala

**Comment by tagliala** [comment]
This request is legit, please consider the rotation feature, available in both CSS and SVG frameworks:

https://jsfiddle.net/tagliala/2s78abqk/11/
