### ISSUE TITLE
Icon request: fa-plus-thin-circle

### ISSUE THREAD

**Issue by Krystian95** [FortAwesome/Font-Awesome#14954]
Hi, I was looking for an icon with the thin plus inside a circle, something like this: 

![designa_tesserato_warning](https://user-images.githubusercontent.com/24765669/56866834-5ae31b00-69de-11e9-8bfc-c90ba43e9654.png)

Looks like the existing icon solid plus-circle, but with the plus more thin, likes the plus in the light style.

Many thanks :)
Chris.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon with the power transforms, masking, and layering feature of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/e1bfz6gc/17/ (of course this requires a font size larger than the default 16px)

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Also, could you please provide a use case of this icon and why it is important to have both `plus-circle` and `plus-thin-circle`?

I would like to see something different than "the current plus-circle doesn't work for my design"

**Comment by gt-novelt** [comment]
`faCirclePlus` is missing from free-regular-svg-icons but can be found in free-solid-svg-icons.

I think the _"thin"_ plus circle should be found as the regular circle plus icon and as the solid one in free-solid-svg-icons.

That would correspond to what can be found when looking for circle-plus:
- https://fontawesome.com/icons/circle-plus?s=regular&f=classic
- https://fontawesome.com/icons/circle-plus?s=solid&f=classic

### Edit

The regular or thin version aren't free.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
