### ISSUE TITLE
Regarding the file count in font-awesome-5.8.1

### ISSUE THREAD

**Issue by NishealJ** [FortAwesome/Font-Awesome#14956]
Hi,

The number of files in font-awesome-5.8.1 is near to 6K whereas in font-awesome-4.7.0 was 700. Is this correct?  or i've downloaded a wrong version?

Is there any way to customize the download of font-awesome-5?

Thanks :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The number of files in font-awesome-5.8.1 is near to 6K 

Yes, that's the proper file count of the source code.

The source code contains a lot of stuff (such as [individual svg files for each icon](https://github.com/FortAwesome/Font-Awesome/tree/master/svgs) and [individual javascript files for each icon](https://github.com/FortAwesome/Font-Awesome/tree/master/js-packages/%40fortawesome/free-solid-svg-icons)) that you probably don't need in the average use case.

Are you including font awesome as a git submodule? If yes, please consider to add it as [an npm dependency](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)

> Is there any way to customize the download of font-awesome-5?

It depends on what you exactly need.

Take a look at the [Getting Started page](https://fontawesome.com/start#other-methods), there you will find a lot of options (npm, yarn...)

If none of those methods fit your use case, we have a downloadable zip file for the web (fontawesome-free-5.8.1-web.zip
 available at [this page](https://github.com/FortAwesome/Font-Awesome/releases)) that contains fewer files, but you still don't need them all in your application (and you should not commit all of them in your repository).

The filse you need depend on what implementation of Font Awesome you are going to provide: [SVG](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-svgs) or [CSS](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-web-fonts).

You will find all the information you need to host Font Awesome by yourself at https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

Hope it helps

Closing here, but feel free to comment

**Comment by NishealJ** [comment]
Hi @tagliala ,
I've switched to fontawesome-free-5.8.1-web as suggested, this has very less files compared to other versions Thank-you :) !
