### ISSUE TITLE
Icon update: fa-facebook

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#14965]
Facebook has now updated its logo, it is now round: https://facebookbrand.com/.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the prompt heads-up.

We pay a lot of attention in keeping brand logos up-to-date.

Has the roll-out of the new logo already started? I don't see it on app store / play store / website

**Comment by Studio384** [comment]
Facebooks own social pages on Facebook/Twitter already do use the new logo and as far as I'm aware this is rolling out already. Also, as per the docmentation linked, it is now their guideline to use this logo, not the old one.

**Comment by dalibor-sanzeru** [comment]
We've get email from facebook that we violates policy rules and facebook login will be disabled - we have used facebook-f logo.

Can new logo be added to this icon set conformed with this?
Quote: 
the "f Logo" which is located on the button. It is not in compliance with our Platform Policies and we would kindly ask you to change it to the logo available at https://en.facebookbrand.com/assets/f-logo/?audience=landing

Change was requested to do till 3.5.2019 else they disable login provider for page.

**Comment by talbs** [comment]
Okay, all of the Facebook brand icons have been updated in our latest release, [5.8.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.2). 

* https://fontawesome.com/icons/facebook
* https://fontawesome.com/icons/facebook-square
* https://fontawesome.com/icons/facebook-messenger
* https://fontawesome.com/icons/facebook-f

Thanks for bringing this to our attention. :smile:
