### ISSUE TITLE
Pro fontawesome slow

### ISSUE THREAD

**Issue by microb1002** [FortAwesome/Font-Awesome#14961]
since 1 hour, font awesome pro version is very very slow...
any suggestion ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you referring to the Pro CDN?

I can confirm that error pages do not load properly, but I'm not having issues when the assets are loaded on a whitelisted third-party website.

Could you please provide more information?

**Comment by microb1002** [comment]
yes indeed.
when i use a free version, it's ok.

**Comment by microb1002** [comment]
![Capture d’écran 2019-04-30 à 17 22 40](https://user-images.githubusercontent.com/50146159/56973228-b9d69a80-6b6c-11e9-8ad1-f7c69d13172c.png)

**Comment by tagliala** [comment]
Could you please send an email at hello@fontawesome.com ?

**Comment by gregrobsonoxb** [comment]
Just as a bump on this - the CDN has been effectively down as of now (along with the website) for 11 hours with no update.

This isn't the first long outage on the CDN and I'll be moving all the sites I manage off the CDN once I can access the website again. I don't have any faith in the reliability of the CDN any more. 😞 

@robmadole - I contributed the KickStarter for FontAwesome5 and really had faith in the team to deliver, but the lack of communication over CDN issues is really denting my faith in the project. I hope we get a blog post with some kind of explanation for the outage and what you're doing to rectify matters going forward. I don't think I've had more than 99% availability from Font Awesome Pro.

![image](https://user-images.githubusercontent.com/51821848/69329069-469b8f80-0c48-11ea-9231-58901f6f8e41.png)

**Comment by robmadole** [comment]
Just posted an update to status.fortawesome.com. We will be switching hosting providers this morning. We'll be working hard over the next year to win back some of the faith that the community has lost in us. It's our desire to offer everyone the best services possible and the pro.fontawesome.com product has never lived up to that goal.

We'll post updates directly on status.fortawesome.com and I'll try to post an update here once the transition is complete.

**Comment by gregrobsonoxb** [comment]
@robmadole Thanks for the update. I realise things hit the fan from time to time, but there has just been a few too many "long" outages this last year as you mention. Having radio silence from status page really didn't help.

As a request: when you rebuild/fix all the CDN stuff, can you make sure pro.fontawesome.com and fontawesome.com are structurally isolated? At least if the CDN goes down in the future we can still grab a zip and the instructions to host FontAwesome locally. 🙂

**Comment by robmadole** [comment]
Hosting provider has been switched and the performance problems have been fixed as far as we are aware.
