### ISSUE TITLE
Icon request: align-left-slash

### ISSUE THREAD

**Issue by leifcr** [FortAwesome/Font-Awesome#14964]
Similar to eye-slash, text-slash would be a great indicator when using in wysiwyg editors, and indicating that text is hidden. (Or indicating cutting/removing text parts)

I suggest basing it off align-left with a slash over.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/50/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by leifcr** [comment]
@tagliala Yes, I agree that it's possible to achieve, it's not looking as good as e.g. camera-slash.
I do think both text-slash (align-left-slash) and image-slash would be a nice additions, to match video-slash, volume-slash, comment-slash.

**Comment by sensibleworld** [comment]
We've added an `align-slash` icon to Font Awesome Pro: https://fontawesome.com/icons/align-slash?style=solid
