### ISSUE TITLE
Icon update Request: With respective to new redhat brand

### ISSUE THREAD

**Issue by riginoommen** [FortAwesome/Font-Awesome#14978]
Existing Icon
https://fontawesome.com/icons/redhat?style=brands

New Brand
**https://www.redhat.com/en/about/brand/new-brand?intcmp=701f20000012hnbAAA**

Red Hat has updated the icon last day

**Comment by talbs** [comment]
Okay, the `redhat` brand icon has been updated in our latest release, [5.8.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.8.2) - https://fontawesome.com/icons/redhat.

Thanks for bringing this to our attention. :smile:

**Comment by riginoommen** [comment]
@talbs Thanks I appreciate your efforts.
