### ISSUE TITLE
Icon request: fa-shutter (blinds)

### ISSUE THREAD

**Issue by fr4ncesco** [FortAwesome/Font-Awesome#14979]
Can be useful if you can add icon for the blinds control in order to have the icon to identify some actions like the following icons
![image](https://user-images.githubusercontent.com/16837890/57145835-52b32300-6dc4-11e9-9c75-b0343148cc38.png)
![image](https://user-images.githubusercontent.com/16837890/57145852-59da3100-6dc4-11e9-8870-43537b44d9e1.png)
![image](https://user-images.githubusercontent.com/16837890/57145865-62326c00-6dc4-11e9-93a1-50eea7d906e3.png)
![image](https://user-images.githubusercontent.com/16837890/57145879-69597a00-6dc4-11e9-9906-75d823820868.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since we already have a [blind](https://fontawesome.com/icons/blind?style=solid) icon and this issue seems related to something else, could you please fix the title?

**Comment by xmuskrat** [comment]
I think he meant blinds, not blind.  The s matters.

**Comment by fr4ncesco** [comment]
Yes I forgot the 's'. Thanks for the suggestion.

**Comment by fr4ncesco** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Since we already have a [blind](https://fontawesome.com/icons/blind?style=solid) icon and this issue seems related to something else, could you please fix the title?

Is the new title with the 's' ok?

**Comment by fr4ncesco** [comment]
Maybe shutter is also better I change the title with this

**Comment by StanBarrows** [comment]
**What can it be used for?**
I'm building an application for smart-homes and would like to display an icon for automatic shutter controls. 

**Example image (optional)**
![500_F_135163313_C37tXF5yzUViE9Psf4l1NyMsiXOSZ4Bb](https://user-images.githubusercontent.com/10268813/59570690-86a88600-909c-11e9-86a5-e11466b40363.jpg)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=blinds&c=household
