### ISSUE TITLE
What happened to the old 4.0 icons?

### ISSUE THREAD

**Issue by Bangkokian** [FortAwesome/Font-Awesome#14982]
This page appears to be down: 

https://fontawesome.com/v4.7.0/icons/

Is there another archive set up somewhere?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the late reply. The page is ok for me now, could you please check again? Maybe it was a temporary fault

**Comment by Bangkokian** [comment]
Thanks for the response, but I still get a blank page. 

Tried it through a VPN too.
Tried it in a different browser too.

Sure looks down to me. 

OSX 10.14
Chrome 73.0. 
Southeast Asia.

**Comment by tagliala** [comment]
Thanks for the heads-up. It is just that page or the whole website?

Is the browser console showing something wrong?

**Comment by Bangkokian** [comment]
It's just that page. The console shows nothing. 

The entire page seems empty. Here's the full HTML:

`<html>
<head></head>
<body></body>
</html>`

**Comment by tagliala** [comment]
> If it looks good for you, maybe it's a CDN issue somewhere?

Definitely it could be a local issue, but it is not only local, it is also related to a specific part of the website.

Unfortunately I don't have the tools to check that other than https://www.uptrends.com/tools/uptime and everything looks fine there

![image](https://user-images.githubusercontent.com/556268/57178047-4635d580-6e6b-11e9-9c71-42c06784b6f9.png)

I'm keeping this open for feedback from other members of the community or someone else in the FA team. Any chance to test outside the VPN or with another internet provider in your area?

**Comment by Bangkokian** [comment]
Ah... I think it's okay. Looks like it's something local. My guess is some CDN (or something more local) didn't cache it right at the last-mile. 

I went Incognito and geo-shifted my VPN through NYC and it looks fine. 

False alarm. Thanks for your help.

**Comment by tagliala** [comment]
You're welcome.

Thanks for the heads-up, closing here
