### ISSUE TITLE
Icon request: more medical icons

### ISSUE THREAD

**Issue by BoomRocker** [FortAwesome/Font-Awesome#150]
We work for a hospital company and have need of many medical icons. Here is what we think would be most wonderful to have included as a selection of medical icon elements...
- ~~Stethoscope~~
- ~~Hospital~~
- ~~Medical Cross~~
- ~~Medical Bag~~
- Caduceus: #4325 
- Prescription RX: #768 
- ~~Ambulance~~
- ~~Doctor Silhouette~~
- Nurse Silhouette: #4326 
- Band-Aid: #4298 
- X-Ray: #681 
- Cardiogram Line: #1059 or #3206 
- ~~Wheel Chair~~
- Pill Bottle: #4328 
- Microscope: #515

**Comment by paxtonhare** [comment]
+1 Rx Icon

**Comment by tagliala** [comment]
locking here, please +1 the proper icon or open new requests
