### ISSUE TITLE
Icon request: fas fa-chatbot

### ISSUE THREAD

**Issue by Brunnn** [FortAwesome/Font-Awesome#15006]
### What can it be used for?
Icon to display chatbot interations.

### Example image (optional)

![chatbot](https://user-images.githubusercontent.com/42523274/57471936-b2954800-7262-11e9-94f1-9304d91318cc.png)

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit. Meanwhile, with the use of power transforms, masking, and layering features of the SVG Framework, you can achieve an icon that could fit your use case.

Demo: https://jsfiddle.net/tagliala/cb8zLvyw/6/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment]
Hi @Brunnn,

`fa-message-bot` icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/message-bot

Regards.

cc/ @tagliala
