### ISSUE TITLE
IconRequest: fa-Quantopian

### ISSUE THREAD

**Issue by rasulkireev** [FortAwesome/Font-Awesome#15002]
Please add a logo for Quantopian. Image attached is their logo (.pn
!
[quantopian_logo](https://user-images.githubusercontent.com/8257474/57410792-c6d13a80-71b9-11e9-9ffa-f7c5a9bac9b4.png)
g)

**Comment by aethior** [comment]
>In November 2020, Quantopian announced it will shut down after having operated for 9 years. ([more info](https://en.wikipedia.org/wiki/Quantopian))

cc/ @tagliala
