### ISSUE TITLE
Icon Request: fa-question-circle-o does not work in npm 4.7.0

### ISSUE THREAD

**Issue by SunCooper** [FortAwesome/Font-Awesome#15017]
The fa-question-circle-o does not work when install by npm font-awesome@4.7.0, but fa-thermometer-empty work.

fa-question-circle-o work when install by npm font-awesome@4.6.3

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We don't have any official npm package for version 4.7.0. Please contact the package's author

Also, version 4 is in EOL 

Sorry, closing here
