### ISSUE TITLE
Icon request: phonograph/gramophone

### ISSUE THREAD

**Issue by diomed** [FortAwesome/Font-Awesome#15012]
### What can it be used for?

it could be used on music sites

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/gramophone?style=solid
