### ISSUE TITLE
Brand icon Bootstrap not showing while all other brand icons okay.

### ISSUE THREAD

**Issue by dumaisf** [FortAwesome/Font-Awesome#15014]
Here is my code:
`<i class="fab fa-bootstrap"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-bootstrap](https://fontawesome.com/icons/bootstrap?style=brands) has been introduced in version 5.8.0

I'm pretty confident that your website is loading an older version of Font Awesome. Please double check that you are using the latest one.

Please also note that some third-party themes/libraries/plugins can load older version of Font Awesome which can take precedence over the latest one

Hope it helps

Closing here, but feel free to comment if you are not able to solve your issue

**Comment by dumaisf** [comment]
Thanks Geremia!
