### ISSUE TITLE
npm install: 'jekyll' is not in the npm registry. & 'lessc' is not in the npm registry. / package.json

### ISSUE THREAD

**Issue by mattes** [FortAwesome/Font-Awesome#1501]
package.json contains invalid dependencies:

```
  "dependencies": {
    "jekyll": "1.0.2",
    "lessc": "1.3.3"
  }
```

```lessc``` should be ```less```. No idea which ```jekyll``` package is meant though.

**Comment by tagliala** [comment]
This should not be an issue anymore
