### ISSUE TITLE
Icon request: fa-combine (combine objects, merge objects)

### ISSUE THREAD

**Issue by HTMLGuyLLC** [FortAwesome/Font-Awesome#15028]
### What can it be used for?

Merging/combining objects/items. For instance, I would like to use it for merging clients or merging contacts.

### Example image

![Screen Shot 2019-05-14 at 6 46 19 PM](https://user-images.githubusercontent.com/2415447/57737149-96d1dd80-7678-11e9-9569-5d15ba2e7f1a.png)

**Comment by ddssff** [comment]
I have the same need, but I was thinking more in terms of road signs with arrows.   There is the code-merge icon but its pretty geeky, I don't think my clients would recognize it.

**Comment by aethior** [comment]
Hi @HTMLGuyLLC,

`object-union` icon has been added in v6.0.0.
Check https://fontawesome.com/icons/object-union

Regards.

cc/ @tagliala
