### ISSUE TITLE
Icon Request: icon-ups, icon-usps, icon-fedex, icon-dhl

### ISSUE THREAD

**Issue by playnox** [FortAwesome/Font-Awesome#1502]
I thought would be a great idea to include our major shipping carriers... will work great for dropdowns and etc.
Thanks!

**Comment by dougkillmer** [comment]
+1

**Comment by nontoxicmike** [comment]
+1

**Comment by yonib05** [comment]
+1

**Comment by morozow** [comment]
+1

**Comment by Arvraepe** [comment]
+1

**Comment by batteriesinaflash** [comment]
+1

**Comment by batteriesinaflash** [comment]
As stated in my last request #7131 I can make the icons as a contribution. 

Here is a link to the svg and eps for the USPS icon..
https://www.dropbox.com/sh/je4eo66fqk3dew2/AADtl6QG-kgQjRMgKYh736nwa?dl=0

**Comment by calumbrodie** [comment]
-1 Rather than adding a whole bunch of couriers to this font library, wouldn't it be better to have a font _just_ for couriers (ala http://paymentfont.io/)? At this stage I can't see any well trodden pattern for having open source font libraries on github, I'd perhaps be able to start this endeavour as we have a requirement for this on our ecommerce site. Just not sure how to start

**Comment by webuxr** [comment]
@calumbrodie ... where were you months ago on this! ;)
This is great! Thanks for sharing. I'm now a -1 as well.

**Comment by batteriesinaflash** [comment]
@calumbrodie @webuxr  I would like to gently remind you this request is for Shipping Carriers and Shipping icons not payment icon. Font Awesome already has payment icons anyhow. I would also like to point out that the reason we need a comprehensive Font for icons is because that loading a bunch of different sources is just taxing on your system.

**Comment by webuxr** [comment]
Guess I should have taken more than a quick glance at the http://paymentIcons.io site before assuming it also included shipping carrier icons. It does not. And yes, @batteriesinaflash is right. FA would still really benefit from having its own shipping carrier icons as having them would keep us from having to add a separate font just for shipping icons. Keeping http requests to a minimum is hard enough.

**Comment by batteriesinaflash** [comment]
Although I had a difference of opinion to @calumbrodie, it did give me an idea. It would be beneficial for people who only need a small part of FontAwesome to have them broken into category segments. This will allow for a smaller footprint. So you didn't have to include the entire file for all the fonts. So for example, is you only needed payment carriers, then you use the sub section Payments. Helps reduce requests and load time. I know you can do this yourself but its additional time that you may not have when you are working for clients or developing on a team. @webuxr thank you for the second thought.

**Comment by kennethscott** [comment]
+1

**Comment by stonefishdesign** [comment]
+1 
need it in navigation bar. Thanks!

**Comment by playnox** [comment]
Originally requested on Jul 5, 2013 and still no response :(

**Comment by spidre409** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by moeiscool** [comment]
over +9000

**Comment by Argus9** [comment]
+1

**Comment by chrisramaro** [comment]
+1

**Comment by karpalig** [comment]
+1 icon-EMS

**Comment by hpvd** [comment]
+1
would perfectly fit in new "logistics" category of FA 5.07 :-)

**Comment by hpvd** [comment]
including fa-Hermes and fa-dpd would be also nice.

**Comment by jpennal** [comment]
+1

**Comment by mickey90210** [comment]
+1

**Comment by TantumLabs** [comment]
+1

**Comment by anthonator** [comment]
👍

**Comment by MikeImken** [comment]
+1

**Comment by playnox** [comment]
Thanks!
@dktue Hey, I still remember that day 🤣

**Comment by webuxr** [comment]
Holy cow! We finally have these shipping icons in v5.6.0! Thanks @talbs !

**Comment by PrestaShark** [comment]
Daaaaaaaam :⭕️

**Comment by batteriesinaflash** [comment]
its about time..

**Comment by dolibarr95** [comment]
Hi!
What about TNT?
Tks ;)

**Comment by dolibarr95** [comment]
hello !
What about TNT ?
