### ISSUE TITLE
Icons missing, and not even empty rectangles on Internet Explorer

### ISSUE THREAD

**Issue by DayKirby** [FortAwesome/Font-Awesome#15025]
### Describe the problem

User reports seeing empty space (not empty rectangles) where where I have included Font Awesome icons. Only users within one organization as far as I know, no other similar reports.

### What did you expect?

For all users to see the icons, or to be able to troubleshoot the issue.

### What version and implementation are you using?

Version: Both (non pro) 4.1.0 and (pro) 5.3.1 
Browser and version: Internet Explorer

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

https://ncmoves-demo.metroquest.com/ (non pro)
https://ncdot-stip.metroquest.com/#!/?p=web&u=ncdot-stip-demo&pm=dynamic&theme=v7 (pro)
For second link above, pasting user submitted screenshot with empty space circled, as well as expected screenshot seen by other users, with same spaces circled.
![image](https://user-images.githubusercontent.com/19862410/57653574-fea7fb80-7586-11e9-8a91-be1cf788f459.png)
![image](https://user-images.githubusercontent.com/19862410/57653592-0d8eae00-7587-11e9-9569-e24e634390d6.png)

### Bug report checklist

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi,

> Both (non pro) 4.1.0 

Font Awesome 4.1.0 is in EOL and it is not supported

>  and (pro) 5.3.1

As far as I can tell, the website is using FA 5.0.10 CSS version from the CDN

![image](https://user-images.githubusercontent.com/556268/57681850-d248b980-7630-11e9-929c-c39c3ba49c38.png)

> Browser and version: Internet Explorer

Could you please provide:
- OS and Internet Explorer versions affected by this issue
- A screenshot of https://fontawesome.com/v4.7.0/ taken with the browser experiencing the issue

**Comment by DayKirby** [comment]
Maybe I wasn't clear. This is being reported by a user - I can't reproduce the issue, and I don't have access to exact versions etc. I actually don't think it's a Font Awesome issue, but I'm hoping this is something that has been seen before due to, perhaps, firewall or browser settings and I can at least get some advice for diagnosing what I expect is an issue on the user side. I feel like the important clue is the missing icons but no empty rectangles. I'm hoping that this has happened before and you can point me in useful directions. I use Font Awesome extensively and am very happy with it, but the user happens to work for one of my most important clients.

**Comment by tagliala** [comment]
Ok, I will leave this open for feedback from the community

**Please do not +1 this request**, only useful comments will be allowed

**Comment by DayKirby** [comment]
Finally heard back from the user, turns out it was a Group Policy within an organization. I figured it was a user issue, but couldn't diagnose it from the outside.

**Comment by tagliala** [comment]
@DayKirby thanks for the heads-up

> a Group Policy within an organization

any further detail about this group policy?

**Comment by DayKirby** [comment]
Here's the full reply "Issue solved. Our updated Group Policy has been applied". Sadly I'm not expecting to get any further info from them. If I ever find out I'll be sure to post it here.
