### ISSUE TITLE
Request for new icons

### ISSUE THREAD

**Issue by tjpatange** [FortAwesome/Font-Awesome#15026]
Hi could you add shapes of diamonds in the list

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do:
- https://fontawesome.com/icons/gem?style=solid
- https://fontawesome.com/icons/gem?style=regular

fit your use case?

If they don't, please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by aethior** [comment]
@tagliala I think you can close here.
