### ISSUE TITLE
SVG Core not updating icon

### ISSUE THREAD

**Issue by craigpotter** [FortAwesome/Font-Awesome#15021]
Hi, 

We are using the SVG Core and pulling a list of icons. 

I'm trying to update a SVG on click however it doesn't seem to be working. 

Here is my webpack: 

```
import {library, dom, config} from "@fortawesome/fontawesome-svg-core";

import {faChevronDown as faChevronDown_fal_pro} from "@fortawesome/pro-light-svg-icons/faChevronDown";
import {faChevronUp as faChevronUp_fal_pro} from "@fortawesome/pro-light-svg-icons/faChevronUp";

library.add(faChevronDown_fal_pro, faChevronUp_fal_pro);


dom.watch();

```

My HTML
```
<div id="newslettertab" class=" p-3 bg-primary text-white">
    <div class="tab-header">
        Sign up for exclusive offers <i class="fal fa-chevron-down"></i>
    </div>
</div>
``` 

JS
```
$("body").on('click', '#newslettertab', function(e){
	e.preventDefault(); 
	$(this).toggleClass('open');
	console.log($(this).hasClass('open'));
	if($(this).hasClass('open'))
	{
		console.log('down');
		$(this).find('svg').removeClass('fa-chevron-up').addClass('fa-chevron-down');
	}else{
		console.log('up');
		$(this).find('svg').removeClass('fa-chevron-down').addClass('fa-chevron-up');
	}
});
```

The chevron down works on initial load. When I click the `#newslettertab`, I can see the class on the SVG change. This triggers the change of the `data-icon` attribute as well. 

The Icon next changes however. Not sure what i'm doing wrong  ?

I've tried manually setting `config.observeMutations = true;` and `config.autoReplaceSvg = true;` and still no luck. 

I'm using `@fortawesome/fontawesome-svg-core@1.2.18`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've tried to replicate your issue on CodeSandbox (using font awesome free icons), but it seems to work fine: https://codesandbox.io/s/0vmroqpqjl

I'm not using any custom configuration option, please take a look at the `index.js` file

**Comment by craigpotter** [comment]
Hmmm ok, I will check for other conflicts which could be stopping this.
