### ISSUE TITLE
Updates page: 'Fruits & Vegetables' mispelled url

### ISSUE THREAD

**Issue by alexdgs** [FortAwesome/Font-Awesome#15031]
On the [Updates](https://fontawesome.com/updates) page, Icons Pack section, when clicking on the Carrot icon to view the 'Fruit & Vegetables' category we are taken to this url:
https://fontawesome.com/icons?d=gallery&c=fruit-vegtable
But that page shows 'Sorry, we couldn't find any icons related to "".' This due to a mispelling on the word `vegtable` in the url. Changing it to `vegetable` should fix the problem:
https://fontawesome.com/icons?d=gallery&c=fruit-vegetable
Greetings.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm, there is a typo

**Comment by talbs** [comment]
Thanks for the heads up about this broken link. Sorry if it caused you any trouble.

We've got this fixed in the codebase and it should be pushed live to https://fontawesome.com/updates shortly.

**Comment by talbs** [comment]
Just following up - this link is fixed on https://fontawesome.com/updates now and access to carrots, hot peppers, and salad should be easier than ever. 😛 

Thanks again for reporting this and helping us fix things up.
