### ISSUE TITLE
Some Brand Icons are not showing up on site.

### ISSUE THREAD

**Issue by moeler** [FortAwesome/Font-Awesome#15038]
I noticed in the footer of my website that the Facebook, Youtube and Twitter square icons were missing. So I went to the Font Awesome website to find that they are missing from there as well. fa-facebook-square, fa-youtube-square, fa-twitter-square

https://fontawesome.com/icons?d=gallery&q=twitter
https://fontawesome.com/icons?d=gallery&q=facebook
https://fontawesome.com/icons?d=gallery&q=youtube

Version: 5.6.3
Browser and version: Chrome 74.0.3729.131

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is probably due to an ad-blocker

Ref: #1799 

Hope it helps

Closing here
