### ISSUE TITLE
<i class="fab fa-facebook-f"></i>

### ISSUE THREAD

**Issue by chhayach** [FortAwesome/Font-Awesome#15037]
When used <i class="fab fa-facebook-f"></i>  "fab fa-facebook-f" code is shown as in circular style, screnshote attached 
![fb-issue](https://user-images.githubusercontent.com/50699931/57845014-c30f6a80-77ee-11e9-91d6-30c5fc3c341d.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> When used "fab fa-facebook-f" code is shown as in circular style

That is correct!

In Font Awesome 5.8.2 we have replaced the old facebook logo with the new one, as per https://en.facebookbrand.com/assets/f-logo/?audience=landing

Hope it helps

Closing here
