### ISSUE TITLE
Icon request: fa-star-pencil (write a rating), fa-star-arrow (rating has income)

### ISSUE THREAD

**Issue by PaykomanVll** [FortAwesome/Font-Awesome#15036]
### What can it be used for?
Use it after a transaction between users, so can rated between this...
Put to transaction overview:
[fa-rate-out] symole for i must rate / have rated
[fa-rate-in] i have received rating / not received

After the / is alternative for lock/unlock, but this can be visibled with different colors

### Example image (optional)
Sorry i have not...
rate-out = Star with pen
rate-in = Star with incoming symbole (like arrow?)

### Icon request checklist

- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [O] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

x = yes
o = no

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve icons to fit this use case with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/72/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
