### ISSUE TITLE
Webserver down

### ISSUE THREAD

**Issue by Philipp97714** [FortAwesome/Font-Awesome#15040]
if I click on any Icon in the gallery I get this error
`Error: Error: Error: connect ECONNREFUSED 107.23.219.159:443`
for example if I open this url: https://fontawesome.com/icons/adjust?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up.

We are aware of this issue, anyway the website is working fine for me at the moment

Ref: https://twitter.com/fontawesome/status/1129123620511453197
