### ISSUE TITLE
Icon Request: tournament-bracket

### ISSUE THREAD

**Issue by xyeLz** [FortAwesome/Font-Awesome#15041]
Right now there's nothing to indicate a tournament other than a trophy. Would be nice to have a bracket.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any single color example of the icon you would like to see?

**Comment by xyeLz** [comment]
Hi Geremia,

You guys actually have a few icons that are very close already. For example, folder-tree, network-wired, and project-diagram almost look like a bracket, but they obviously aren't the accurate representation. The tough part with something like this is designing it so that it can be represented in a scaled-down format without making it unrecognizable.

The most accurate icon I was able to find would be this one: http://onlinetournamentmanager.000webhostapp.com/icon/bracketIcon.png

However, I can't say I'm really very fond of that and I think you folks could certainly make it look a bit flashier without overcomplicating it.

**Comment by tagliala** [comment]
Thanks for the example

**Comment by tagliala** [comment]
Let's use #3819, it has more +1s
