### ISSUE TITLE
Icon request: baguette

### ISSUE THREAD

**Issue by sowenjub** [FortAwesome/Font-Awesome#15049]
### What can it be used for?

It can be used to represent a baguette in a list of food items (shopping list, restaurant menu, bakery product, recipe ingredient …).
It's also a matter of localization (it is a more suitable representation for "bread" in France, and maybe in Vietnam as well).

### Example image (optional)

🥖

### Icon request checklist

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/baguette?s=solid

**Comment by sowenjub** [comment]
Awesome, thank you 🥳
