### ISSUE TITLE
icon request: icon-whatsapp

### ISSUE THREAD

**Issue by iwarner** [FortAwesome/Font-Awesome#1504]
Hi

Could you possible add these two widely used chat apps

Line
http://line.naver.jp/en/

WhatsApp
http://www.whatsapp.com/

Thanks

**Comment by moritzpeikert** [comment]
+1

**Comment by rukhairy** [comment]
+1

**Comment by alap** [comment]
+1

**Comment by rhoffmann** [comment]
+1

**Comment by Luntegg** [comment]
+1

**Comment by cagataygurturk** [comment]
+1

**Comment by fabiovaz** [comment]
+1

**Comment by yannickoo** [comment]
@tagliala 2nd place ;)

**Comment by tagliala** [comment]
@yannickoo I'm pretty sure that dave will take a look at the most requested icons before releasing a new version... or at least I hope he will do :)

**Comment by yourule** [comment]
+1

**Comment by tiefenb** [comment]
+1

**Comment by d-bro** [comment]
+1

**Comment by Bertuzb** [comment]
+1

**Comment by d-claassen** [comment]
+1 Would love to use a font awesome icon as a whatsapp share button for our website! http://whatsapp-sharing.com/

**Comment by duxan** [comment]
@d-claassen I love your script! I plan on using it at mobile version of https://wesavvy.herokuapp.com/ and that's exactly the reason it would be great to have it in FA :).

**Comment by relbraun** [comment]
whatsup

**Comment by sirion89** [comment]
I understand this is not the same but its the closest we can get atm with the current iconset if u dont want to use external resources. I think the crompromise is quite good (just a bit vertically stretched!)
<span class="fa-stack fa-lg">
          <i class="fa fa-comment-o fa-stack-1x"></i>
          <i class="fa fa-phone fa-stack-1x"></i>
        </span>

**Comment by SaifurRahmanMohsin** [comment]
+1
y u no add whatsapp icon?

**Comment by skftn** [comment]
+1

1.5 year old thread to add a damn icon. Wow.

**Comment by Bertuzb** [comment]
+2

**Comment by tagliala** [comment]
@mksalles  @skftn if you need this icon please consider a custom build of fontawesome

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

**Comment by alex-pl** [comment]
+1

**Comment by SaifurRahmanMohsin** [comment]
I have done as @tagliala suggested and put it up in my git repo. You can find it here >> https://github.com/SaifurRahmanMohsin/whats-awesome

**Comment by tagliala** [comment]
@SaifurRahmanMohsin thanks for sharing this

**Comment by vicemediabenelux** [comment]
@SaifurRahmanMohsin thanks

**Comment by skftn** [comment]
@SaifurRahmanMohsin Thanks

**Comment by johncatley** [comment]
@tagliala Is there a particular reason why the whats app icon can not be included in font-awesome?

**Comment by tagliala** [comment]
@johncatley this is a popular request like other popular requests. As I said, I'm pretty confident that Dave will take this into account before releasing a new version

**Comment by johncatley** [comment]
@tagliala ok,thx!

**Comment by SaifurRahmanMohsin** [comment]
@tagliala @skftn you're welcome

**Comment by davegandy** [comment]
Added to 4.3.0-wip branch. Closing.
