### ISSUE TITLE
Icon request: easy, intermediate, and advanced (or easy, medium, difficult)

### ISSUE THREAD

**Issue by willdayble** [FortAwesome/Font-Awesome#15052]
### What can it be used for?

For describing levels of difficulty in games, online lessons, recipes, or anything with increasing levels.

Note, this is distinct from spiciness, temperature, speed, connectivity, or other things that can increase.

The standard in most recipes / lessons / etc seems to just be "easy, medium, advanced".

### Example image (optional)

![image](https://user-images.githubusercontent.com/29651/58439876-04224b80-811a-11e9-95e4-cbddc066efaf.png)

The background to the above example is a shield, but to avoid any military connotations it could also be another more generic icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please explain why an arbitrary number of star icons do not fit this use case?

E.g: https://jsfiddle.net/tagliala/ryncaLg7/9/

**Comment by willdayble** [comment]
Heya!

Thanks for welcoming me. :)

We've tried the star thing, and users misunderstand it as "user rating", not difficulty.

'Difficulty' tends to be represented as a scale of some kind, perhaps there's a "rank" feel that could be borrowed? 

E.g. https://www.google.com/search?q=difficulty+icon 

It's a tricky one!

**Comment by tagliala** [comment]
Thanks for the information!

I see that someone is using a tachometer or signal, as well stars:

- https://fontawesome.com/icons?d=gallery&q=tachometer
- https://fontawesome.com/icons?d=gallery&q=signal

Anyway, we need a better title and example for this request, as per [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

**Comment by willdayble** [comment]
Yeah that's getting there with the tachometer, but again not quite right.

Good call on the example, I will add something to the original post, thank you!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
