### ISSUE TITLE
Issue upgrading from 4.7  to 5.8.2

### ISSUE THREAD

**Issue by echjordan** [FortAwesome/Font-Awesome#15057]
Hi!

I'm trying to upgrade from 4.7.2 to 5.8.2. I have a pro token. Per the [upgrading docs](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4), I removed all assets/references to font-awesome 4, uninstalled 4 from npm (this wasn't explicitly specified in the docs but I assumed), set my npm config up with PRO token and installed 5. Everything is compiling but the prefixes (far, fal) render as empty squares and 5 specific icons like 'abacus' don't render.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information on your build system and implementation of Font Awesome used (CSS vs SVG)?

Could you please also check that everything in your browser's development tools (from network requests, to css/javascript) is fine?

**Comment by echjordan** [comment]
We're using webpack, and a CSS implementation. Nothin' suspicious in devtools.

Also forgot to mention I'm using the css v4 shims
`<script defer src="https://use.fontawesome.com/releases/v5.8.2/js/all.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.8.2/js/v4-shims.js"></script>`

**Comment by tagliala** [comment]
Well... I'm a little bit confused 🤔 

If you are using webpack and npm packages, you should be able to compile and serve Font Awesome from your assets and you don't need the CDN links as above.

css and shims files are under the `css` folders of the `fontawesome-pro` package

Also, the CDN links are related to Font Awesome Free, so you will not find Pro icons there

Does this help?

Related docs and links:
- https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
- https://www.npmjs.com/search?q=%40fortawesome

**Comment by echjordan** [comment]
I'll try removing the shim CDN links for v4 and go from there. Thank you

**Comment by echjordan** [comment]
I solved my issue, we had some wacky custom import behavior for 4.7 that I discovered. Thanks for help!

**Comment by tagliala** [comment]
@echjordan you're welcome, glad you've solved!
