### ISSUE TITLE
Icon request: hand-wave

### ISSUE THREAD

**Issue by idoshkedi** [FortAwesome/Font-Awesome#15061]
A hand waving hello or goodbye - the most useful hand icon (surely more than hand-rock, hand-paper, hand-scissors and hand-lizard), is still missing from FA. Please add it!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13687, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by geigel** [comment]
How in gods name is "wave" _**STILL**_ not part of the set?
