### ISSUE TITLE
Icon request: candy-bar

### ISSUE THREAD

**Issue by jgreiss** [FortAwesome/Font-Awesome#15065]
### What can it be used for?

like a chocholate bar

### Icon request checklist

- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We now have a candy bar! https://fontawesome.com/v6.0/icons/candy-bar?s=solid
