### ISSUE TITLE
Icon request: nginx

### ISSUE THREAD

**Issue by russkel** [FortAwesome/Font-Awesome#1507]
Hi,

Thanks for your hard work, it's an absolute pleasure to use this.

As for the request: The nginx logo would make a nice icon to put in footers. The icon would be the 'G' in the logo seen here http://nginx.org/nginx.gif

Thanks!

Russ

**Comment by drastik** [comment]
Feels wrong commenting on something so old, but it is the only issue I see for an Nginx icon!

:+1:

**Comment by tvld** [comment]
:+1:

**Comment by itsmelion** [comment]
Love to have the 'G' icon, although we must respect the press resources provided by the official nGinx people.

https://www.nginx.com/press/
Icons resources : [download here](https://cdn-1.wp.nginx.com/wp-content/files/nginx-logos-kit.zip?_ga=2.117624649.198371895.1539889932-1058498482.1536466435)

Hope it gets released soon. 🤞

**Comment by pmjcreations** [comment]
Hello,

Any news on nginx icon?

**Comment by DannyDeeps** [comment]
I endorse this request!

**Comment by itsmelion** [comment]
The [Leaderboards](https://fontawesome.com/community/leaderboard/brands) are serious.. really?
Brands like MDB, Concrete5, orcid.. or others ive never seen in my life, top Brand icons leaderboard... wtf..
ahead of gigantic platforms like MongoDB, GraphQL, and Nginx etc..

Seem some companies mobilize gather theyr devs, to react to these issues, so they top the leatherboard.
It feels like sabottage and this must stop.

**Comment by itsmelion** [comment]
Shall we react a lot to this issue, may sabbotage the leatherboard either.. since this is how its done?

**Comment by tagliala** [comment]
@itsmelion I've hidden your comments because they do not respect our community guidelines and standards:
- https://fontawesome.com/support#fa-requests
- https://github.com/FortAwesome/Font-Awesome/blob/master/CODE_OF_CONDUCT.md#our-standards

The leaderboard also contains a lot of information on how requests work: https://fontawesome.com/community/leaderboard/brands#faqs

Hope that helps
