### ISSUE TITLE
fa-facebook icon is not round but square?

### ISSUE THREAD

**Issue by mathiasselleslach** [FortAwesome/Font-Awesome#15083]
Might be related to https://github.com/FortAwesome/Font-Awesome/issues/14965

When using
```
<i class="fab fa-facebook"></i>
```
in version 5.8.2 (latest version at this time of writing), the icon displayed is not
https://fontawesome.com/icons/facebook?style=brands

but this
https://fontawesome.com/icons/facebook-square?style=brands

Is somebody else experiencing this?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm: https://jsfiddle.net/tagliala/nf4x3uk1/2/

Please make sure that you are using the latest version of Font Awesome. If you are hosting the CSS files yourself, please check that you have also updated the webfont files and there aren't cache issues.

Please also note that some third-party libraries/plugins/themes may load an older version of Font Awesome that could have priority over yours.

Take a look here:
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Hope it helps

Closing here, but feel free to comment
