### ISSUE TITLE
fab fa-facebook-square gone

### ISSUE THREAD

**Issue by Irene1997** [FortAwesome/Font-Awesome#15086]
### Describe the problem

The "fab fa-facebook-square" icon suddenly disappeared from my website. I am using the class='fab fa-facebook-square' version of the Icon, and it did not display anymore. It does not display in Chrome, but it DOES display in Edge. I then used the Unicode and that did work.

### What did you expect?

Previously it worked fine and displayed on any browser without problems.

### What version and implementation are you using?

Version: 5.6.3
Browser and version: Chrome 74.0.3729.169 (64-bits)

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Reproducible test case

This stopped working:
\<i class='fab fa-facebook-square' style='font-size:27px;color:#3B3B3B'>\</i>
But the unicode still works.
\<i class='fab' style='font-size:27px;color:#3B3B3B'>\&#xf082;\</i>
Also, I have the same problem with W3Schools:
https://www.w3schools.com/icons/tryit.asp?icon=fab_fa-facebook-square&unicon=f082 

### Bug report checklist

- [X] I have filled out as much of the above information as I can
- [1/2] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you using an Ad-blocker?

If you aren't, could you please provide a reproducible test case?

**Comment by oom-** [comment]
![image](https://user-images.githubusercontent.com/11071671/89197123-8a9eac80-d5ab-11ea-9393-4e72ba77d8d0.png)
It was hidden by the Adblock-Plus chrome extension for me. Hope it can help.
