### ISSUE TITLE
It's line-chart and not chart-line

### ISSUE THREAD

**Issue by SuperThinking** [FortAwesome/Font-Awesome#15084]
In React-Native, the name is line-chart, please update in website https://fontawesome.com/icons/chart-line?style=solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details?

`line-chart` was the old name of `chart-line` in Font Awesome 4. https://fontawesome.com/v4.7.0/icon/line-chart

> In React-Native

Is this about some third-party library using an older version of Font Awesome? 

As a reference, this is our official react-native component: https://github.com/FortAwesome/react-native-fontawesome#installation

Working demo: https://codesandbox.io/s/zqfr1 (note: this is my first attempt with react-native ever)

**Comment by SuperThinking** [comment]
Ok, so I was using "react-native-vector-icons/FontAwesome" rather than FontAwesome5.
Thanks for the help! Closing the issue.

**Comment by tagliala** [comment]
You're welcome, glad you've solved
