### ISSUE TITLE
Font Awesome don't pass pagespeed insights

### ISSUE THREAD

**Issue by mogurimogu** [FortAwesome/Font-Awesome#15085]
### Describe the problem
I have an error when analyze my website with google pagespeed insights

> Ensure text remains visible during webfont load
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading

I'm using Google AMP and I need use the web font, this problem can be solved with `font-display: swap` or `fallback` in css

### What version and implementation are you using?
Version: 5.8.2 Webfont
Browser and version: Chrome Versión 74.0.3729.169 (Build oficial) (64 bits)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

### Screenshot
![developers google com_speed_pagespeed_insights__hl=en url=http%3A%2F%2Fnew majestichotelgroup com%2Fes](https://user-images.githubusercontent.com/40238711/58549256-66a74480-820b-11e9-83cc-2bfce27d7977.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I'm using Google AMP and I need use the web font, this problem can be solved with font-display: swap or fallback in css

Unfortunately this cannot be done with webfonts. Even if you customize the `font-display` property with your own value, you will find icons appearing as a square before being replaced with the actual icons. icon fonts should stay at the default value of block

Please take a look at https://github.com/FortAwesome/Font-Awesome/issues/14387#issuecomment-475097395

Please post your comment at #14387, let's continue there

**Comment by xpertyst** [comment]
I also implemented the font-display: swap; property but couldn't work. I am on a wordpress theme. page speed tool is still showing the same font issues.

**Comment by tagliala** [comment]
@xpertyst could you please provide a link? Please also note that `font-display: swap` will make Google happy, but users of your website *may* see a square before the actual icon

**Comment by xpertyst** [comment]
@tagliala : https://xpertyst.com/

Thanks for concerning.
