### ISSUE TITLE
fa-share and fa-share-alt are not rendering correctly

### ISSUE THREAD

**Issue by JamesClow** [FortAwesome/Font-Awesome#15093]
![Screen Shot 2019-05-31 at 9 33 42 AM](https://user-images.githubusercontent.com/12902886/58716895-4dc39e00-8387-11e9-96ae-cd4a8096590d.png)
![Screen Shot 2019-05-31 at 9 33 57 AM](https://user-images.githubusercontent.com/12902886/58716903-50be8e80-8387-11e9-9acd-23c91dd31751.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is probably due to an ad-blocker third party extension. Try without extensions or with another browser

Ref: #1799 

Hope it helps

Closing here, but if I'm wrong feel free to keep commenting and I will reopen

**Comment by JamesClow** [comment]
Thanks! Turning off "Block social media icons tracking" in Ad Block Plus seemed to do the trick.
