### ISSUE TITLE
fab fa-yammer logo not working

### ISSUE THREAD

**Issue by jsibo** [FortAwesome/Font-Awesome#15094]
the yammer logo is not loading when testing this locally using the following shortcode:
`<i class="fab fa-yammer"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/nf4x3uk1/4/

[fa-yammer](https://fontawesome.com/icons/yammer?style=brands) has been introduced in Font Awesome 5.8.0.

My best guess is that your webiste is using an older version of Font Awesome, please double check that it is using 5.8.0 or newer (5.8.2 at the moment I'm writing)

Please note that third party themes/libraries/plugins may load an older version of Font Awesome that have priority on the version you are loading. Please check that this is not your case

If you still think there is an issue with Font Awesome, feel free to fill out a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md), providing all the information required and even better a reduced test case

Hope it helps

Closing here

**Comment by jsibo** [comment]
resolved - thanks!
