### ISSUE TITLE
icon request: follow

### ISSUE THREAD

**Issue by quocvu** [FortAwesome/Font-Awesome#1509]
Could you please add follow and following icons?

It's something we see on many social networks and would be very useful
Thanks

**Comment by chalist** [comment]
following and follower icon please

**Comment by SorJEF** [comment]
+1

**Comment by ajibarra** [comment]
+1

**Comment by chalist** [comment]
no, that's AddUser or FollowUser. Following icon is different

**Comment by tagliala** [comment]
Please provide a single color example, suitable for 14px icon size, maybe an icon actually used by a social network.

Twitter uses `user-add`, Facebook uses `icon-rss`, Instagram uses `icon-plus`. They all use "follow" alongside the icon
