### ISSUE TITLE
IMDb icon visibility issues

### ISSUE THREAD

**Issue by ffxsam** [FortAwesome/Font-Awesome#15102]
Hi, Pro user here. Just wanted to let you know that the IMDb icon is rather difficult to make out.

**Describe the bug**
IMDB icon is difficult to read compared to other brand icons.

**To Reproduce**
![image](https://user-images.githubusercontent.com/12532733/58815655-9ed4cb80-85ed-11e9-9129-e98b8297dc1e.png)

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
It might be a good idea to remove the square from around the logo, or make it a rectangle as the current IMDb logo looks. Or possibly offer a variation of this icon that has no box at all.

**Screenshots**

**Version and implementation**
Version: 5.8.2

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [N/A] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hey @ffxsam. Your suggestion seems to go against the brand guidelines from what I can tell.

Do you come to a similar conclusion after reading https://www.imdb.com/pressroom/brand-guidelines/?

**Comment by ffxsam** [comment]
Ahh, bummer. You're right about that.. thanks for pointing that out.
