### ISSUE TITLE
Icon request: salt

### ISSUE THREAD

**Issue by laumega1** [FortAwesome/Font-Awesome#15101]
**What can it be used for?**
It can be used to indicate salinity, salt shaker, pepper, among others.

**Example image (optional)**
![icon](https://user-images.githubusercontent.com/46464089/58786220-5ca88b80-85e7-11e9-8728-271ece2148f6.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by CodeJunkieio** [comment]
I agree, however make it stand upright and use the alt to include the actual salt dots

**Comment by yannroberge** [comment]
I agree with this request. Note that this has other, non-culinary uses. I would like to use it to represent my group's League of Legend tournament.

**Comment by CodeJunkieio** [comment]
Also its use in puns
Example:
The balloon was a-**salt**-ed by the 3 year old

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/salt-shaker?s=light
