### ISSUE TITLE
Release notes for 5.9.0 point to private repo

### ISSUE THREAD

**Issue by rodrigoaguilera** [FortAwesome/Font-Awesome#15107]
I noticed that the the release notes here
https://github.com/FortAwesome/Font-Awesome/releases/tag/5.9.0
point to
https://github.com/FortAwesome/Font-Awesome-Pro/blob/master/UPGRADING.md
When they should be pointing to
https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

Can this be fixed or avoided in the next releases?

**Comment by robmadole** [comment]
All fixed.
