### ISSUE TITLE
search-plus icon is not working in CSS

### ISSUE THREAD

**Issue by Mish325** [FortAwesome/Font-Awesome#15116]
I tried using "search-plus" icon with CSS but it didn't work. But the icons which was in the example section working fine.

Here's my CSS code.

.tz-gallery .lightbox:before {
	position: absolute;
	top: 50%;
	left: 50%;
	margin-top: -13px;
	margin-left: -13px;
	opacity: 0;
	color: #fff;
	font-size: 26px;
	font-family: "Font Awesome 5 Free"; 
	font-weight: 400;
	content: '\f00e';
	pointer-events: none;
	z-index: 9000;
	transition: 0.4s;
}

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In Font Awesome Free, `search-plus` is only available in solid style.

Solid style requires `font-weight: 900` property

Working example: https://jsfiddle.net/tagliala/c9rxutqe/2/

Docs: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here

**Comment by Mish325** [comment]
Hi,

Thanks a lot for the quick response. Yes, now it is working fine. Thanks
again for your help.

Mishari Tamara

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
