### ISSUE TITLE
5.9 Kit (Pro / webfont) - fas fa-route does not work

### ISSUE THREAD

**Issue by paulfoster777** [FortAwesome/Font-Awesome#15128]
Hi.  I've just updated my project to use the 5.9 kits and "fas fa-route" has stopped loading.  It's also showing as a blank on the fa site.

Cheers,

Paul

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I can confirm the icon is not working on fontawesome.com (both Chrome / Edge)
- https://fontawesome.com/icons?d=gallery&q=route

I can confirm that the kit does not work:
- https://jsfiddle.net/tagliala/xjazof9w/

It does work on SVG and CSS, both Free and Pro:
- SVG / Free https://jsfiddle.net/tagliala/7hod8jy3/1/
- CSS / Free https://jsfiddle.net/tagliala/c9rxutqe/5/
- SVG / Pro https://jsfiddle.net/tagliala/c061tk3e/1/
- CSS / Pro https://jsfiddle.net/tagliala/9oj78abe/1/

Does not look like a documentation issue, let's assign @robmadole 

More context about `route` icon and why it could be different from the others: it has been added before on FA Pro only and in a later release to FA Free icons

**Comment by WallaceChan** [comment]
When will it be fixed?

**Comment by robmadole** [comment]
This has been fixed in 5.10.0.
