### ISSUE TITLE
Rust language

### ISSUE THREAD

**Issue by lucasmantoani** [FortAwesome/Font-Awesome#15120]
Hi, saw it was opened here : https://github.com/FortAwesome/Font-Awesome/issues/13764
but still no rust-lang icon almost a year later, and it will be really usefull since a lot of people start to learn it !

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but the best thing you can do is to upvote #13764

> still no rust-lang icon almost a year later

Our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs) contain a lot of information on how requests work, please take a look there

Closing here
