### ISSUE TITLE
Icon Request: Standard Forum Icons

### ISSUE THREAD

**Issue by rienholt** [FortAwesome/Font-Awesome#1513]
I am sure more than just I could use the following icons as they are pretty standard for internet fora. Hope one post for all of them is ok.

General Text Editor:
+ Horizontal Rule Icon
+ Text Color Selector / Palette Icon
+ Text Background Selector Icon
+ True Type Font Icon
+ Glow Icon
+ Shadow Icon

Internet Specific Text Editor:
+ Marquee or Move Icon
+ Blink Icon

Protocol Icons:
+ AOL Instant Messenger
+ Yahoo Instant Messenger
+ Windows Live / MSN Messenger
+ ICQ Messenger
+ Xfire Messenger

**Comment by beliys** [comment]
+1 Protocol Icons

**Comment by tagliala** [comment]
Please do not +1 this request

Please open individual requests having care of searching before

Closing here

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
