### ISSUE TITLE
Icon request: icon-imdb(non-square)

### ISSUE THREAD

**Issue by makccr** [FortAwesome/Font-Awesome#15138]
I think it would be great to have an IMDb icon that isn't the square version. Something like the image below would be *awesome*😉 

![343-3433420_imdb-icon-png-for-kids-imdb-logo png](https://user-images.githubusercontent.com/18688578/59225869-6c9c0e80-8b97-11e9-9af2-c375950871ad.jpeg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close here because of #15102

Hope it helps
