### ISSUE TITLE
Space shuttle flip vertical does nothing

### ISSUE THREAD

**Issue by pmauer456** [FortAwesome/Font-Awesome#15142]
When you choose the space shuttle and the "flip vertical" option there is no visible change to the icon.  If you are looking at the space shuttle from the top and flip it vertically (so you would see the bottom) there would be changes that would occur.  The windows and the tail section would not be seen for example.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> flip it vertically (so you would see the bottom) 

That would be nice, but it is not how flip works

`fa-flip-vertical` is only going to apply a vertical mirror transformation to the icon.

It is not the same of a 180 degree rotation.

You can better see the difference on an usimmetric icon: https://jsfiddle.net/tagliala/xjazof9w/21/

Hope it helps

Closing here
