### ISSUE TITLE
Icon request: fa-prod and fa-test

### ISSUE THREAD

**Issue by gregsenne** [FortAwesome/Font-Awesome#15152]
Id like two icons, just like fa-dev. It's a box with the word DEV in it.
I'd like 2 more, one that says TEST and one that says PROD.

**What can it be used for?**
I'm building a view that needs to inform us what environment that a service is active in. In the row, I'd like to have the 3 icons (dev, test, and prod), then color them red or green accordingly.

**Example image (optional)**
Just a solid box with the word TEST or the word PROD in it

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit and meets our contributing guidelines, but please note that we are trying our best to avoid words in icons.

If you need to put text inside icons, our SVG framework provides a helpful feature:

Demo: https://jsfiddle.net/tagliala/7hod8jy3/6/
Docs: https://fontawesome.com/how-to-use/on-the-web/styling/layering

> Id like two icons, just like fa-dev. It's a box with the word DEV in it.

The `dev` icon you are referring to, is the logo of https://dev.to/, requested by our community at #12589

Please note that any usage of the DEV logo that does not represent the DEV brand should be avoided. Take a look at https://fontawesome.com/icons/dev?style=brands, you will find information on how to properly use brand icons.

Hope it helps

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
