### ISSUE TITLE
Icon request: fa-hockeyapp

### ISSUE THREAD

**Issue by DXCrailprojects** [FortAwesome/Font-Awesome#15169]
**What can it be used for?**
Login to HockeyApp for up-/downloading apps

**Example image (optional)**
![image](https://user-images.githubusercontent.com/32732673/59667606-50135e00-91b7-11e9-97ec-4c9bb3e0b5a2.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
>**HockeyApp is being retired**
The time has come to say goodbye.
Last year we announced the transition from HockeyApp to [Visual Studio App Center](https://appcenter.ms/), a single solution for continuously building, testing, releasing, and monitoring your apps. ([more info](https://devblogs.microsoft.com/appcenter/hockeyapp-is-being-retired/))

cc/ @tagliala
