### ISSUE TITLE
Icon request: icon-history

### ISSUE THREAD

**Issue by vbo** [FortAwesome/Font-Awesome#1516]
Please add "period" icon. We use it as a metaphor for subscription billing.

Something like this:
![period](https://f.cloud.github.com/assets/255308/760788/38c3661a-e7b7-11e2-830d-986d4acec984.png)

**Comment by aethior** [comment]
Added to v4.1. `fa-history` (http://fontawesome.io/icon/history/)

cc @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here. ;)
