### ISSUE TITLE
Deezer icon missing

### ISSUE THREAD

**Issue by antoineWPA** [FortAwesome/Font-Awesome#15166]
Hello,

I feel like the Deezer icon is missing. 
There is a page for it so I think it used to be there : https://fontawesome.com/icons/deezer

Thank you for your help

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is a request for Deezer at #2802, please add a 👍 reaction to that request.

> I feel like the Deezer icon is missing.
> There is a page for it so I think it used to be there

That page is just a custom 404 error, take a look at [nonexistent-brand](https://fontawesome.com/icons/nonexistent-brand).

Anyway, Deezer fells in the highlighted case:

![image](https://user-images.githubusercontent.com/556268/59660375-a4fba800-91a8-11e9-8fc8-70647620ba56.png)



Closing here
