### ISSUE TITLE
Icon request: viking-helmet

### ISSUE THREAD

**Issue by sissinho997** [FortAwesome/Font-Awesome#15165]
**What can it be used for?**
Our departement name's : Viking Technologies division

**Example image (optional)**
https://www.shareicon.net/download/2017/05/09/885791_console.svg
Otherwise we accept any other suggestion. 

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this request?

Is this a brand?

**Comment by anasinho997** [comment]
No, it's not a brand. It's just our intern department name and we will use
in our squad.
