### ISSUE TITLE
Icon request: window-shutter

### ISSUE THREAD

**Issue by StanBarrows** [FortAwesome/Font-Awesome#15160]
**What can it be used for?**
I'm building an application for smart-homes and would like to display an icon for automatic shutter controls. 

I don't like the style of the provided issuer #14979

**Example image (optional)**
![500_F_135163313_C37tXF5yzUViE9Psf4l1NyMsiXOSZ4Bb](https://user-images.githubusercontent.com/10268813/59570690-86a88600-909c-11e9-86a5-e11466b40363.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I don't like the style of the provided issuer #14979

Don't worry. That design is just an example. The actual style will be decided by the Font Awesome team, because it should be simple enough to fit the 16px icon size.

Please post your example at #14979

Closing here
