### ISSUE TITLE
Only the brand icons are working

### ISSUE THREAD

**Issue by sir-red-dab** [FortAwesome/Font-Awesome#15179]
**Describe the bug**
In my project I am using Fontawesome with the npm function. But when I import the css files into my own css file I can only use the brand icons. When I import Fontawesome with a CDN it works fine, but I don't want to use it that way so I can reduce html requests.

**To Reproduce**
My Github repo: https://github.com/sir-red-dab/webtail/tree/dev

**Expected behavior**
All the icons should work.

**Version and implementation**
Version: 5.9.0
Browser and version: Chrome - 74.0.3729.169

**Comment by InsanityMeetsHH** [comment]
Can't confirm on your website: https://sir-red-dab.github.io/webtail/
![Bildschirmfoto 2019-06-19 um 11 04 49](https://user-images.githubusercontent.com/35538671/59752405-7a7e1d80-9282-11e9-9941-2f8b8dadb304.png)
![Bildschirmfoto 2019-06-19 um 11 06 50](https://user-images.githubusercontent.com/35538671/59752407-7a7e1d80-9282-11e9-8f9d-7d2ce9847e5c.png)

**Comment by sir-red-dab** [comment]
Didn't fix it and no longer using the code.
