### ISSUE TITLE
Font Awesome is spelled "Font Aweosme" on the plans page

### ISSUE THREAD

**Issue by zachallia** [FortAwesome/Font-Awesome#15177]
**Describe the bug**
There is a misspelling of awesome on the plans page

**To Reproduce**
Go to https://fontawesome.com/plans and scroll to the FAQ question "Why do I have to pay for Font Awesome icons now?" The word awesome is spelled Aweosme in one instance.

**Expected behavior**
Should be spelled Awesome

**Comment by tagliala** [comment]
@zachallia thanks for the report!

**Comment by talbs** [comment]
@zachallia oh my! Thanks for the heads up on this one. We'll get things back to "awesome" very shortly. 😄

**Comment by talbs** [comment]
Okay, this should be all fixed up now on https://fontawesome.com/plans#faq-why-pay. Thanks again for bringing this to our attention.
