### ISSUE TITLE
Audible Icon Does not seem to work

### ISSUE THREAD

**Issue by abhivr** [FortAwesome/Font-Awesome#15178]
**Describe the bug**
I am seeing a box when I try to add the audible icon through css. 

**To Reproduce**
https://jsfiddle.net/749sqnLd/1/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the proper css properties to use a brand are `font-family: "Font Awesome 5 Brands";` and the proper `font-weight` is `400` (the default value)

Fixed fiddle: https://jsfiddle.net/tagliala/gvo6t32f/

Ref: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps 

Closing here
