### ISSUE TITLE
Icon request: columns-3

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#15170]
**What can it be used for?**
indicate more columns than current 2 column image

**Example image (optional)**
![image](https://user-images.githubusercontent.com/47600614/59694731-16daee00-91b7-11e9-8a23-18c847100f13.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @terryschwarz,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/columns-3

Regards.

cc/ @tagliala
