### ISSUE TITLE
Icon Request: cherries

### ISSUE THREAD

**Issue by teddiemucha** [FortAwesome/Font-Awesome#15176]
**What can it be used for?**
It can be used to represent cherries in a list of food items (shopping list, restaurant menu, bakery product, recipe ingredient…). 
It can also be used by food companies to represent a product or category of products. 

**Example image**
![image](https://user-images.githubusercontent.com/3446000/59700232-ca3be680-91a7-11e9-9498-858bdd4f0c8b.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We've added a cherries icon! https://fontawesome.com/v6.0/icons/cherries?s=solid
