### ISSUE TITLE
Icon request: border-center-h, border-center-v

### ISSUE THREAD

**Issue by terryschwarz** [FortAwesome/Font-Awesome#15173]
**What can it be used for?**
Current series has top, bottom, left, right and inner variation, but is missing variations where just the inner horizontal or vertical are solid. Use to indicate an upper/lower or left/right portion of a series of cells.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/47600614/59692177-623ecd80-91b2-11e9-9eba-9480d7feeb2f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that `border-center-v` and `border-center-h` (with `-v` and `-h` suffixes as in [ellipsis-v](https://fontawesome.com/icons/ellipsis-v?style=solid)*ertical*, [ellipsis-h](https://fontawesome.com/icons/ellipsis-h?style=solid)*orizontal*) are better name for these icons. What do you think?

**Comment by terryschwarz** [comment]
I'm fine with your choices, mine were only first thing that came to mind.

**Comment by sensibleworld** [comment]
@terryschwarz Thanks for the suggestion! I meant to get those into the last release, but someone dropped them during the icon creation process. They'll be in our next update.

**Comment by sensibleworld** [comment]
These were added in our most recent release: https://fontawesome.com/icons/border-center-v?d=gallery&style=solid and https://fontawesome.com/icons/border-center-h?d=gallery&style=solid
