### ISSUE TITLE
Wrong icon when using FA Pro OTF with Microsoft Word 365

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#15181]
Hello, thank you for comprehensive answer. Let met provide you with additional information. 
I am at windows 10, using microsoft word 365, installed only one font "font awesome 5 pro-solid-900 otf." Lets say I wish insert your icon: ellipsis-v. with unicode f1c3. I type to application in regular font (e.g. calibri). I see "f881". With selected string I press alt-x and switch to awesome font. The result is a Flask with different unicode (f0c3). With previously mentioned codes above I see a) blank square b) different icon, not matching with your guide. Am I doing something wrong, or is it a bug with font?

_Originally posted by @JanKudera in https://github.com/FortAwesome/Font-Awesome/issues/13433#issuecomment-503452845_

**Comment by tagliala** [comment]
@JanKudera 

let's try the following

#### Use ligatures

1. Open word
2. Select Font Awesome 5 Pro regular
3. type `file-excel`
4. Post a screenshot

### Rollback to Font Awesome 5.6.3

Font Awesome 5.7+ has some issues with some softwares and ligatures. Please try again with version 5.6.3 and report results

Ref: #14614

**Comment by JanKudera** [comment]
Hello, Iam back at wordkk, could you please navigate me, where I can get version 5.6.3?

**Comment by tagliala** [comment]
Here: https://github.com/FortAwesome/Font-Awesome-Pro/releases

Direct link: https://github.com/FortAwesome/Font-Awesome-Pro/releases/download/5.6.3/fontawesome-pro-5.6.3-desktop.zip

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account#linked-accounts

**Comment by JanKudera** [comment]
I see that account is linked to my colleague that is out of office now. I have to wait...

**Comment by JanKudera** [comment]
@tagliala: I can confirm version 5.6.3 is working fine for us. You can close the issue.
![obrazek](https://user-images.githubusercontent.com/36691097/60078669-b276dc00-972c-11e9-80cc-a97763e8c9d8.png)

**Comment by tagliala** [comment]
@JanKudera thanks.

This bug still does not have a fix, but let's  continue on #14614
