### ISSUE TITLE
Globe europe unicode

### ISSUE THREAD

**Issue by youssef294** [FortAwesome/Font-Awesome#15182]
Globe icons don't work except for the normal globe "f0ac"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/c9rxutqe/8/

Please:
- Check that you are using the latest version of Font Awesome (5.9.0 at the moment I'm writing)
- Make sure that no third party library / theme / plugin loads an older version of Font Awesome which takes priority on your version
- Check your pseudoelements syntax, it is different from FA4 https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

If you still think there are issues with Font Awesome, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

**Comment by Asbjoedt** [comment]
I have same issue. The Europe icon does not work and the icon for globe shows the icon for America.

**Comment by tagliala** [comment]
> The Europe icon does not work and the icon for globe shows the icon for America.

Hi, please make sure that you are using Font Awesome 5: https://fontawesome.com/start

**Comment by Asbjoedt** [comment]
Nice. Thanks.
I was calling: https://www.bootstrapcdn.com/fontawesome/
They only have 4.7 but that is not your responsibility.
