### ISSUE TITLE
Font Awesome 5 Free unicode icons do not work with ::before in chrome

### ISSUE THREAD

**Issue by MrMarqua** [FortAwesome/Font-Awesome#15183]
Trying to get the ::before to work with Font Awesome 5 Free. and all i get is little squares.
Naturally this isnt cool, so i searched solutions.. Sure i can get Font awesome 5 brands to work fine using the pseudo but not a simple telephone icon. 
**HTML** 
`<a href="tel:1-2555-565656">+1 2555 565656</a>`
**CSS**
```
.contact a[href^="tel:"]::before {
    display: inline-block;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    font-family: "Font Awesome 5 Free"; 
    font-weight: 900; 
    content: "\f87b";
}
```
**Result:** 
![Screenshot 2019-06-20 at 14 28 46](https://user-images.githubusercontent.com/20854200/59849404-cd7dd080-9367-11e9-8e9c-3d5b96cf2092.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate

CSS: https://jsfiddle.net/tagliala/c9rxutqe/10/
SVG: https://jsfiddle.net/tagliala/7hod8jy3/8/

As far as I can tell from the screenshot, there is a css rule preventing the icon to show, maybe a `font-weight: 400` with higher priority

Docs:
- https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

If you still think there is an issue with Font Awesome, please provide a reproducible test case

**Comment by MrMarqua** [comment]
here is a link to a live version...  I saw it works in your fiddle.
Side note, i am using the fontawesome kit.js not all.css.

http://www.marqua.co.za/test/

ps i am design lecturer and this is one of my training pages

**Comment by MrMarqua** [comment]
Also why did you close it, the bug has not been resolved. 
Please see test site link above

**Comment by tagliala** [comment]
@MrMarqua ok thanks, got it.

There is an issue with pseudo elements and kits, please use the following workaround at the moment:

```css
font-family: "Font Awesome 5 Pro", "Font Awesome 5 Free"
```

Demo: https://jsfiddle.net/tagliala/n4dhqjcv/2/

You can read about this bug at #15137
