### ISSUE TITLE
Icon request: filter-minus

### ISSUE THREAD

**Issue by HarpunDK** [FortAwesome/Font-Awesome#15193]
**What can it be used for?**
Indication of deselection of filter. Or disable/remove filter.
Single icon - "add" already exists. Or could be cool with +filter

**Example image (optional)**
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjIl_r1rITjAhUKFpoKHd-qAToQjRx6BAgBEAU&url=https%3A%2F%2Fwww.iconfinder.com%2Fsearch%2F%3Fq%3Dfilter&psig=AOvVaw2GoHnUAi5nXWzSB7ZNmpc3&ust=1561542404157408

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve this icon with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/102/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Related to: #650

**Comment by HarpunDK** [comment]
I accept this, thx for the demo and the useful reply.
