### ISSUE TITLE
Icon request: A Tobacco/Smoking Pipe

### ISSUE THREAD

**Issue by BrynnMountain** [FortAwesome/Font-Awesome#15192]
There is a large online community for pipe smokers and aficionados, and I think this would be a fantastic icon for the community. Beyond that, I think a pipe is a great symbol for leisure or relaxation, as well as its association with fantasy themes (e.g. Lord of the Rings / Halfling pipe use in D&D/Pathfinder etc.)

[Image Example 1](https://bit.ly/2J4NxaZ)

[Image Example 2](https://bit.ly/2Xufli1)

**Comment by aethior** [comment]
Hi @BrynnMountain,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/pipe-smoking

Regards.

cc/ @tagliala
