### ISSUE TITLE
Desktop font awesome icons don't print properly

### ISSUE THREAD

**Issue by kwrosenzweig** [FortAwesome/Font-Awesome#15191]
**Describe the bug**
From Apple pages, printing to HP color laser printing, the icons print distorted.

How do I get them to print properly?  

I don't even see font awesome font in Word, so can't try that (Mac).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)?

Here is the getting started guide for the desktop: https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started

**Comment by kwrosenzweig** [comment]
Hi.  Clicking on the link for the bug report template just takes me to create a new issue.  I looked over the getting starting... I have the fonts installed. I can see them on the screen, but printing them is the issue.

**Comment by tagliala** [comment]
@kwrosenzweig feel free to start a new issue with all the information required, I will close this one.

**Comment by tagliala** [comment]
Continues on #15194
