### ISSUE TITLE
fas fa-phone-alt is not working in any devices in version 5.9.0 

### ISSUE THREAD

**Issue by kishanpaul** [FortAwesome/Font-Awesome#15190]
"<i class="fas fa-phone-alt"></i>" is not working in any devices in version 5.9.0 .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot confirm.
SVG: https://jsfiddle.net/tagliala/7hod8jy3/10/
CSS: https://jsfiddle.net/tagliala/c9rxutqe/12/
Kit (CSS): https://jsfiddle.net/tagliala/n4dhqjcv/6/
Kit (SVG): https://jsfiddle.net/tagliala/0r5L9dfz/1/

If I have to guess, there are chances that:
1. You are using the CDN, but a third party plugin / theme / library loads an older version of font awesome which takes priority over yours
2. You are hosting the font by yourself, but webfonts have not been updated
3. You are hosting the font by yourself, but there are caching issue 

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting


If you still think there is an issue with Font Awesome, please open a new request and fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md). Please remember to provide all the information required and a reproducible test case will help a lot

Hope it helps

Closing here
