### ISSUE TITLE
Font awesome icon having unknown margin

### ISSUE THREAD

**Issue by pinktanha** [FortAwesome/Font-Awesome#15197]
I used font awesome on my website, it was working fine, suddenly last few weeks it's acting weird.

`<div class="rate_row">
                  <span class="rate_star review_star" data-value="1"><i class="star-f-icon"></i></span>
                  <span class="rate_star review_star" data-value="2"><i class="star-f-icon"></i></span>
                  <span class="rate_star review_star" data-value="3"><i class="star-f-icon"></i></span>
                  <span class="rate_star review_star" data-value="4"><i class="star-f-icon"></i></span>
                  <span class="rate_star review_star" data-value="5"><i class="star-f-icon"></i></span>
                  <input type="hidden" class="get_star" id="get_star" name="rate_star">
               </div>`

As you can see, same classes are applied for all the stars but the last star is acting weird and having an unknown margin on the left whereas I didn't put any margin to the last child. It was fine a few weeks back, suddenly it's happening.

Screenshot of the view -> https://prnt.sc/o6s4on

live website view ->
https://royaltybd.com/partner-profile/Khanas/28

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue does not depend on Font Awesome:
![image](https://user-images.githubusercontent.com/556268/60158352-32667a00-97f1-11e9-9b96-60b48c527c74.png)

Please strip all the extra spaces between tags, they matter, or provide style that does not depend on whitespaces

The actual style of the stars below the title is the following:

```
<i class="star-f-icon"></i><i class="star-f-icon"></i><i class="star-f-icon"></i><i class="star-f-icon"></i>
  <i class="star-f-icon"></i>
```

Demo: https://jsfiddle.net/tagliala/c9rxutqe/22/


Hope it helps

Closing here
