### ISSUE TITLE
Icon request: soda cans, plastic water bottles, glass bottles

### ISSUE THREAD

**Issue by slm04c** [FortAwesome/Font-Awesome#15200]
**What can it be used for?**
To describe cans, plastic water bottle, glass bottle

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
