### ISSUE TITLE
Icon Request: icon-Inflate 

### ISSUE THREAD

**Issue by eSeFBe** [FortAwesome/Font-Awesome#15210]
Hi,

I hope I'm not blind.

I found this implemented icons:

1. direction right: icon-expand
2. direction up: icon-collapse-top
3. direction down: icon-collapse

But I did't find an icon with direction left.

I suggest to add:
icon-inflate

Based on icon-expand with direction left instead of right.

<img width="526" alt="Bildschirmfoto 2019-06-30 um 07 43 18" src="https://user-images.githubusercontent.com/41141754/60392807-6dc3ba00-9b0b-11e9-9c3f-314c08f2f1ba.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do
- https://fontawesome.com/icons/caret-square-left?style=solid
- https://fontawesome.com/icons/caret-square-left?style=solid

fit your use case?

**Comment by aethior** [comment]
@tagliala I think this icon with regular version can be considered solved.
