### ISSUE TITLE
brackets-curly icon is not showing in UI

### ISSUE THREAD

**Issue by areekray** [FortAwesome/Font-Awesome#15214]
fal fa-brackets-curly
fal fa-brackets-curly
fa fa-brackets
fa fa-brackets

These icons are not getting rendered in UI

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-brackets](https://fontawesome.com/icons/brackets?style=solid) and [fa-brackets-curly](https://fontawesome.com/icons/brackets-curly?style=solid) have been introduced in Font Awesome 5.7.0 Pro. So, I'm going to assume that you are using FA 5.7.0 Pro or newer. If you are hosting Font Awesome by yourself, please check that all files are up to date and that there are no cache issues.

Said so, sorry but I can't reproduce on 5.9.0:
SVG: https://jsfiddle.net/tagliala/c061tk3e/8/
Webfont: https://jsfiddle.net/tagliala/9oj78abe/4/
Kit (SVG): https://jsfiddle.net/tagliala/97r8f4y6/2/
Kit (Webfont): https://jsfiddle.net/tagliala/9w3c1ud5/1/


If you still think there is an issue with Font Awesome itself, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case
