### ISSUE TITLE
Bug: Sort-amount-down-alt has incorrect regular version

### ISSUE THREAD

**Issue by ReneS1991** [FortAwesome/Font-Awesome#15213]
### Describe the problem

The regular version of `sort-amount-down-alt` is incorrect, the solid and light versions of that icon are fine. I noticed it in my project but it can also be seen on the fontawesome icons page:

https://fontawesome.com/icons?d=gallery&q=sort-amount-down-alt

![image](https://user-images.githubusercontent.com/17007821/60425697-5eb83700-9bf3-11e9-98a4-2359b243aff2.png)

There you can see that the regular version has the lines in the opposite order, which is incorrect.

### What did you expect?

The regular version to have the lines in the same order as the solid and light version have.

### What version and implementation are you using?

Version: 5.9.0 (latest)
Browser: Any

### Reproducible test case

I think this is a good enough test case?
https://fontawesome.com/icons?d=gallery&q=sort-amount-down-alt

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This has been already fixed in the build system, and will be available in the next release

Leaving this open for tracking purposes

**Comment by sensibleworld** [comment]
This is now fixed in our latest release! Thanks for the heads-up, @ReneS1991 

https://fontawesome.com/icons?d=gallery&q=sort-amount-down-alt
