### ISSUE TITLE
Why are there top and bottom padding for icons?

### ISSUE THREAD

**Issue by hohkfuyuhi** [FortAwesome/Font-Awesome#15215]
My icon has an animation that plays when hovering over it, and I want to know if it is possible to remove the padding on both the top and bottom.

The padding is also making aligning the icons impossible because it just doesn't display dead center, but instead skewed to the top because the bottom padding is larger than the top padding.

![image](https://user-images.githubusercontent.com/47074452/60436182-170acd00-9c3e-11e9-829d-eb1fde9b3a75.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I suppose that you are using the webfont version of Font Awesome, and it is basically text. The "bottom padding" is a limitation of fonts.

This is documented at https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons#issues

If you need pixel perfect animations, you should switch to the SVG Framework

Ref: #671

Hope it helps

Closing here

Feel free to keep commenting if you are not using the webfont version

**Comment by hohkfuyuhi** [comment]
Been frustrated at this issue for a long time coming, but the SVG Framework helped a lot.

Thank you so much!
