### ISSUE TITLE
Icon request: ferris-wheel

### ISSUE THREAD

**Issue by ricktheartist** [FortAwesome/Font-Awesome#15219]
**What can it be used for?**
Represent theme or entertainment parks.

Example
![image](https://user-images.githubusercontent.com/8051661/60458680-46edac80-9c0d-11e9-8a9e-42c282015e6e.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mickaelpch** [comment]
+1 for this :)
The entry does not appear on the icon leaderboard, is there any reason why ?

**Comment by sensibleworld** [comment]
<img width="666" alt="Screen Shot 2021-03-30 at 12 10 26 PM" src="https://user-images.githubusercontent.com/529604/113020760-ea585200-9150-11eb-9eb5-862aee14010d.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
