### ISSUE TITLE
Icons show on local grunt build, but do not show properly when depolyed via docker.

### ISSUE THREAD

**Issue by onionknightbeer** [FortAwesome/Font-Awesome#15226]
**Describe the bug**
I am hosting all of the font awesome files locally. I am including the all.css file in the header of my index.html page, and all of the fontawesome icons appear normally on my local build of my web application. When I deploy via docker, my icons show up as blank squares. Also, the icons that have animations are still animated but as blank squares (in Firefox some of the icons have the content values in them). The problem does not occur when using the svg with js implementation, but I want to use the Web Fonts with CSS implementation instead.

**Version and implementation**
Version: 5.6.3
Browser and version: Chrome 75.0.3770.100 (64-bit), Firefox: 67.0.4 (64-bit)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case (ie: a link to the production website)?

**Comment by onionknightbeer** [comment]
Figured it out. Had the references to the webfonts folder incorrect for the docker environment!

**Comment by tagliala** [comment]
Glad you solved and thanks for sharing the solution
