### ISSUE TITLE
Need alternate CDN for v5.2.0/css/all.css and v5.6.3/css/all.css while the CDN is down.

### ISSUE THREAD

**Issue by verlocalDev** [FortAwesome/Font-Awesome#15225]
Need an alternate CDN

**Describe the bug**
The CDN is down.

**To Reproduce**

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**

**Screenshots**

**Version and implementation**
Version: 5.2.0, 5.6.3

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi, we are migrating to a new DNS provider

Sorry about the issue

Ref: https://status.fortawesome.com/incident/101

**Comment by tagliala** [comment]
Let's use #11146, even if it is closed
