### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by rohitmarneni** [FortAwesome/Font-Awesome#15223]
I am using the free fontawesome kit that I just created after signing up. I am able to hit that js file. However some of the css files are not being served. And chrome console throws an error saying

`GET https://kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css net::ERR_NAME_RESOLUTION_FAILED`
`GET https://kit-free.fontawesome.com/releases/latest/css/free.min.css net::ERR_NAME_RESOLUTION_FAILED
`

And few minutes before, even the home page was down. Tried checking it in incognito mode as well. Didn't vpn yet, so not sure if this is a local problem.

**Comment by timdows** [comment]
Looks like it, got the same issue right now
Will check again in an hour, hope it will be back up!

**Comment by fabswt** [comment]
Same here with:

> Error: Error: Error: getaddrinfo EAI_AGAIN origin.fontawesome.com origin.fontawesome.com:443

**Comment by tagliala** [comment]
Hi, we are migrating to a new DNS provider

Sorry about the issue

Ref: https://status.fortawesome.com/incident/101

**Comment by tagliala** [comment]
Let's use #11146, even if it is closed
