### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Senbonzakura1234** [FortAwesome/Font-Awesome#15224]
cannot load resource from server
my kit script:
<script src="https://kit.fontawesome.com/f4bb5974c6.js"></script>

**Comment by rohitmarneni** [comment]
I think their cdn is down or something. even I have a similar problem, just posted an issue. I guess we can wait for an hour and see if it works again. Maybe the cdn that they are using is under maintenance or something.

**Comment by tagliala** [comment]
Hi, we are migrating to a new DNS provider

Sorry about the issue

Ref: https://status.fortawesome.com/incident/101

**Comment by tagliala** [comment]
Let's use #11146, even if it is closed

**Comment by Senbonzakura1234** [comment]
Is this problem relate to the cloudflare? I was also cannot download fontawesome to the client
