### ISSUE TITLE
Icon request: Hospitality industry

### ISSUE THREAD

**Issue by rotorboy** [FortAwesome/Font-Awesome#15228]
**What can it be used for?**
 hospitality industry, particularly for hotel operations; housekeeping, do-not-disturb, service required, vacancy, dirty, clean, made-bed, unmade-bed, etc…

**Example image (optional)**
Insert the example image here if necessary.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Feel free to open new individual requests, having care of [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before, but requests for icon sets do not meet our contributing guidelines, so I have to close this request.

If you are a Font Awesome Pro customer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
