### ISSUE TITLE
Error when try to install font awesome using yarn

### ISSUE THREAD

**Issue by zverexe** [FortAwesome/Font-Awesome#15227]
When running yarn install, I have this error when font awesome installing:

error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.7.2.tgz: getaddrinfo EAI_AGAIN npm.fontawesome.com:443".

My font awesome package version is - "@fortawesome/fontawesome-pro": "^5.5.0",

Also, as I saw font awesome website inst' accessible.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry but at the moment we are switching our DNS provider and I think that this issue depends on that. Anyway, it should work now

Ref: 
- https://status.fortawesome.com/
- https://status.fortawesome.com/incident/102
- https://status.fortawesome.com/incident/101
