### ISSUE TITLE
Icon request: generic export

### ISSUE THREAD

**Issue by julchen812** [FortAwesome/Font-Awesome#15233]
**What can it be used for?**
icon to enable to export anything

**Example image (optional)**
![download](https://user-images.githubusercontent.com/52497990/60595321-0fb30300-9da7-11e9-8ae6-53e02c260a06.png)

**Icon request checklist**
+ [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
+ [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
+ [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
+ [x] I have included at least one example image if it could be helpful (optional)
+ [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon looks like https://fontawesome.com/icons/share-square?style=solid

Does that fit your use case?

**Comment by julchen812** [comment]
yes, it does.

thanks!
________________________________

**Comment by tagliala** [comment]
You're welcome, closing here
