### ISSUE TITLE
Brands Icons not displaying

### ISSUE THREAD

**Issue by CraigSheppardSoftware** [FortAwesome/Font-Awesome#15231]
I have a business application in which I am using fontawesome to provide the icoms. All is well for the standard and solid icons, but there is just a rectangle when using Chrome and an empty space when using IE or Edge.

To get it working I downloaded the font awesome pack and added the reference to that all.css into the page header. I checked that both all.css and the three font files were loaded, and they were. As you can see below. Then I referenced the icons in the page and when I used brand icons they were blank. If I changed them in the debugger to a standard icon it was visible. If a changed a standard icon to a brand one, it was not.

Here is code for a brand one:
`<div class=" x-tree-icon x-tree-icon-custom x-tree-icon-leaf x-fa fab fa-jenkins" role="presentation"></div>`
and code for a standard one. 
`<div class=" x-tree-icon x-tree-icon-custom x-tree-icon-leaf x-fa far fa-arrow-alt-circle-right" role="presentation"></div>`
I can simply change the fab fa-Jenkins with the far fa-arrow-alt-cirecle-right and the element icons start/stop working.

![image](https://user-images.githubusercontent.com/9721879/60592947-982aa700-9d99-11e9-93c9-5401fe827260.png)

I'm sorry but I am using ExtJS to as my application framework and that makes it difficult to isolate the bits for a fiddle.

Does anyone have any idea why just the brands won't work?

I'm using version fontawesome-free-5.9.0-web

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any chance that one of the following css classes `x-tree-icon x-tree-icon-custom x-tree-icon-leaf x-fa` contains rules that conflict with Font Awesome's ones?

**Comment by CraigSheppardSoftware** [comment]
Great thought!
I removed the classes in turn and found that removing the x-tree-icon-leaf allowed the icon to be visible. I just need to investigate that further to see what to do about it. 
Anyway, your work is done. Thanks very much for your pointer

Craig

**Comment by tagliala** [comment]
You're welcome, glad you've solved
