### ISSUE TITLE
Icon request: icon-hiawatha (wampum)

### ISSUE THREAD

**Issue by moadom** [FortAwesome/Font-Awesome#15241]
**What can it be used for?**
This icon can be used as one of a few, that depict the native american wampums.

**Example image (optional)**
```
-[]-[]-/\-[]-[]- (Hiawatha wampum)

[]-------[] (friendship wampum)

======= (two row wampum)
```
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I'm having troubles in understanding this request.

- How many icons you are requesting? The title suggestes one, I'm understanding three
- Could you please find single color, 16px icon size suitable examples? Eg: if I want to request a `car`, my example would be like  ![car](https://user-images.githubusercontent.com/556268/60730538-b0d7c000-9f45-11e9-8cf6-503c00c84b69.png)

**Comment by moadom** [comment]
Hi, thank you sorry for the confusion, the Hiawatha wampum would be the official request.

![image](https://user-images.githubusercontent.com/52563119/60730958-ebbd0200-9f0b-11e9-9dee-3b8b2a2f8680.png)

I can try to make a vector version.  This belt represents the oldest living participatory democracy, the forerunner for the american constitution.

**Comment by tagliala** [comment]
Thanks for the clarification

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
