### ISSUE TITLE
Duotone Signal Suggestion

### ISSUE THREAD

**Issue by adhayward** [FortAwesome/Font-Awesome#15249]
Looking at the duotone signal-1 .. 4 icons. Personally, I think it would be nice if the two colours could represent "active" and "inactive" bars and thought it would be worth raising.

![image](https://user-images.githubusercontent.com/18305551/60818180-0a81f980-a195-11e9-9678-bc7b99a8d087.png)

I find the current signal-1 particularly difficult as on its own without the other bars it just appears as a small dot which doesn't explain much about what it is. The addition of the other bars in a muted colour clarifies its purpose.

While I guess this could be achieved by layering multiple solid icons on top of one another, it would just be nice with the addition of the duotone icons to allow this via a single icon.  

The same could also be applied to the wifi icons too.

**Comment by sectokia** [comment]
You can use fa-stack to stack a black signal-1 on top of a gray signal-4.

There can't be two colour icons since you can't have a two colour font.

**Comment by tagliala** [comment]
@sectokia thanks for sharing your idea to implement this

I think that @adhayward is referring to the Duotone icons, an exclusive feature of FA Pro and the SVG Framework.

So I think that the best place for this request is the FA Pro repository

@adhayward could you please open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by adhayward** [comment]
Apologies for posting in the wrong project - [the preview documentation where I was looking at the Duotone](https://fontawesome.com/preview/icons?d=gallery) points to this Repo rather than the pro one.
I'll repost this there

**Comment by tagliala** [comment]
@adhayward thanks, sorry for the misleading link and do not worry at all!

Just a clarification

> an exclusive feature of FA Pro and the SVG Framework.

duotone icons are an exclusive feature of FA Pro, but they will be available in both the SVG and Webfont versions. The feature will take advantage of both `:before` and `:after` to display duotone icons

I've edited my previous post

**Comment by tagliala** [comment]
Demo implementation for FA 5 Free SVG, without overlapping icons https://jsfiddle.net/tagliala/L17f528g/134/
