### ISSUE TITLE
Icon Request: icon-source (remote)

### ISSUE THREAD

**Issue by ivan-tellez** [FortAwesome/Font-Awesome#1524]
Hi, this is an Amazing idea, I saw the Video Player Icons and also some others lile Off and Vol.

I think it woul be a great idea if you can add other Remote control Icons to the Set, Like:

Mute: Just like the icon-volume-off but with an X or an crossed out circle
Rec:  Just a filled circle
Source: Its Like a rounded square with an arrow
Exit:  A door wit an arrow
Enter:  icon-level-down rotated like the Intro key
Dash: Maybe an alias for minus
Menu: Something like the icon-list-alt 

Could be used for an advanced player, games, etc

Thanks

**Comment by sensibleworld** [comment]
We have a few icons that could work for this: https://fontawesome.com/v6.0/icons?q=arrow%20to&s=solid%2Cbrands
