### ISSUE TITLE
Icon request: pump

### ISSUE THREAD

**Issue by NormanL** [FortAwesome/Font-Awesome#15259]
**What can it be used for?**
Any type of pump, but not a gas/fuel pump

**Example image (optional)**
These are examples from flaticon.com 
![pump](https://user-images.githubusercontent.com/1788919/61149441-2cd68880-a4af-11e9-9bb7-3f6fc709eb1c.png)
![pump (1)](https://user-images.githubusercontent.com/1788919/61149442-2cd68880-a4af-11e9-9833-d059ad766ce9.png)

**Comment by xmuskrat** [comment]
+1

**Comment by NormanL** [comment]
I have several SVG files for different pump types if anyone is interested.

[pumps.zip](https://github.com/FortAwesome/Font-Awesome/files/3591751/pumps.zip)

**Comment by aethior** [comment]
Hi @NormanL,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/pump

Regards.

cc/ @tagliala
