### ISSUE TITLE
Icon request: fa-camera-slash

### ISSUE THREAD

**Issue by imaxx21** [FortAwesome/Font-Awesome#15252]
Hi, 

you have a video camera with slash, do you think it would be possible to release a camera with slash?

Meaning: combine the two icons:  fal fa-camera + fal fa-slash

Greetings
Carsten

**What can it be used for?** No Picture or No Photo available.
Describe how this could be used / the use case for this icon.

**Example image (optional)** overlay fal fa-camera + fal fa-slash
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve `camera-slash` with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/111/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by AndreasHerss** [comment]
I know this is not related to react-native, but i had the exact same problem. 
@tagliala That's correct, but as i understand, this is not possible in react-native? isn't that correct? 

I can do the masking, and transform, but no kind of layer or stack as i read it? 

There's of course two solutions for that, either the icon, or the layer implemented in react-native :)

**Comment by aethior** [comment]
Hi @imaxx21,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/camera-slash

Regards.

cc/ @tagliala
