### ISSUE TITLE
fa-fw does not work when using icons with size bigger than 1em

### ISSUE THREAD

**Issue by ASL07** [FortAwesome/Font-Awesome#15261]
Hi,

I am experiencing this issue:

I  have a group of icons with fa-fw and fa-5x css classes

The fa-fw class sets the width of the icon to 1.28571em; however this is "overridden" by fa-5x, that sets the font-size to 5em

Is there any easy workaround for this?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate

Demo: https://jsfiddle.net/tagliala/c9rxutqe/32/

> The fa-fw class sets the width of the icon to 1.28571em; however this is "overridden" by fa-5x, that sets the font-size to 5em

`fa-fw` sets `width` property, `fa-5x` sets `font-size` property, I can't see conflicts with the "average" use case

If there is an issue please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Closing here, but feel free to keep commenting
