### ISSUE TITLE
Remove space from code

### ISSUE THREAD

**Issue by chandanndeep** [FortAwesome/Font-Awesome#15272]
Remove space from [Icons In a List](https://fontawesome.com/how-to-use/on-the-web/styling/icons-in-a-list) page

![image](https://user-images.githubusercontent.com/17069784/61356977-0a6cb280-a895-11e9-907d-8dc2eead41f4.png)

**Comment by tagliala** [comment]
Thanks!

**Comment by talbs** [comment]
Thanks for the heads up, @tagliala and @chandanndeep. This is fixed in our code base and should be released to the live docs shortly.

**Comment by chandanndeep** [comment]
@talbs 

Confirmed
![image](https://user-images.githubusercontent.com/17069784/61544333-d810b000-aa62-11e9-81e2-c4dd5e04d1a0.png)
