### ISSUE TITLE
Icon Request: icon-dot

### ISSUE THREAD

**Issue by tristanthar** [FortAwesome/Font-Awesome#1527]
Hello,

I simply love your icons, they're totally awesome. 
I'm only missing two icons, the 'at' sign (@), and the 'dot' (.). My e-mail address is usually written like: something [at] domain [dot] com to avoid spam robots picking it up. I would really look better with these two icons put there instead of these placeholders.

Thanks!

PS: sorry, I don't have an image, but you get the idea.

**Comment by aethior** [comment]
Hi @tristanthar,

This issue is solved with the new 'fa-period' icon?
Check https://fontawesome.com/icons/period.

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.
