### ISSUE TITLE
FontAwesome React - Can't add text in icon

### ISSUE THREAD

**Issue by JeremieLeblanc** [FortAwesome/Font-Awesome#15279]
When trying to replicate the demo at "https://fontawesome.com/how-to-use/on-the-web/styling/layering" with the react-fontawesome package I am unable to re-create the calendar example with the correct transformations on the text.

Here is a code example: https://codesandbox.io/s/friendly-mclaren-fe04x

I would expect the react-fontawesome package to include a component for the text, but it does not seem to exist.
The data-fa-transform attribute does not seem to work either when just placed on a span.

Here is a screenshot of the icon;
![image of icon](https://image.prntscr.com/image/EU3KmAPISie2Z91hmQh5Fw.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Yes, unfortunately that feature is still missing from our React component.

Please follow https://github.com/FortAwesome/react-fontawesome/issues/225 for updates. Please also upvote that request

Hope it helps

Closing here

**Comment by barrychapman** [comment]
When will this feature be added?

**Comment by barrychapman** [comment]
When will this feature be added?
