### ISSUE TITLE
Icon phone-laptop missing in desktop font

### ISSUE THREAD

**Issue by sommereder** [FortAwesome/Font-Awesome#15283]
**Describe the bug**
Cannot use the icon phone-laptop in desktop font.

**To Reproduce**
I use Affinity Designer and FontAwesome works well with other icons, but when I copy the glyph for icon "phone-laptop" to the clipboard and paste it into the text field, the icon does not appear.

I also installed the latest version of FontAwesome in case I missed an update, but this doesn't fix the behaviour.

**Version and implementation**
Version: 5.10.0-11

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I do not own that program.

[phone-laptop](https://fontawesome.com/icons/phone-laptop?style=solid) has been introduced Font Awesome Pro 5.9.0, so please double check that you are using Font Awesome Pro 5.9.0 or newer (5.10.0-11 is a pre-release and it is fine)

Screenshot with Apple Pages
![image](https://user-images.githubusercontent.com/556268/61626729-55643c80-ac7e-11e9-91f4-bebf32def0a3.png)

I should ask you to completely uninstall Font Awesome from your desktop, restart, and install it again.

We also have a troubleshooting guide available at https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#updating 

If that does not help, please provide
1. Software version
2. OS version
