### ISSUE TITLE
Website always mobile?

### ISSUE THREAD

**Issue by danilopaulinodasilva** [FortAwesome/Font-Awesome#15284]
Hi there, 

The FontAwesome website is always showing as mobile to me. Using a Mac OSX 10.14.5 Chrome 75.

The screenshots are attached. 

![Captura de Tela 2019-07-22 às 08 11 36](https://user-images.githubusercontent.com/5751920/61628417-9b0e0e80-ac58-11e9-9fa2-cddb048096d9.png)
![Captura de Tela 2019-07-22 às 08 11 24](https://user-images.githubusercontent.com/5751920/61628418-9ba6a500-ac58-11e9-8754-d473d42257b7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It looks like that you are viewing the webiste at 500% zoom. Please press `CTRL+0` to reset the zoom at 100%

**Comment by danilopaulinodasilva** [comment]
Duuuude! A was struggling for months. Thanks :)
