### ISSUE TITLE
new icon request template?

### ISSUE THREAD

**Issue by dakshsorathia** [FortAwesome/Font-Awesome#15282]
Request for put new "Music Festival" like Tomorrowland Logo as icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please edit this request by fixing the titile and filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

**Comment by dakshsorathia** [comment]
Yes sure why not.

**Comment by tagliala** [comment]
No feedback, closing here
