### ISSUE TITLE
Can't install font-awesome-pro in an Azure DevOps Pipeline

### ISSUE THREAD

**Issue by Dipx** [FortAwesome/Font-Awesome#15296]
Hello,

I try to install font-awesome-pro in a pipeline build in Azure DevOps with no luck after countless tries. (the project is built with asp .netcore 2.2 & angular 7)

I've already seen the issue #14717 and tried what I saw.

Adding a .npmrc in the build pipeline. I tried these File path:

- d:\a\1\npm\${Build.BuildId}.npmrc
- d:\a\1\npm\ClientApp\${Build.BuildId}.npmrc
- d:\a\1\s\${Build.BuildId}.npmrc
- d:\a\1\s\ClientApp\${Build.BuildId}.npmrc
- .npmrc

I also tried the two custom npm command to set the registry globally
- config set "@fortawesome:registry" https://npm.fontawesome.com%/
- config set "//npm.fontawesome.com%2f:_authToken" ${FONT_AWESOME_TOKEN}

(${FONT_AWSOME_TOKEN} is a variable linked to my pipeline)

the publish instruction in the .NET core pipeline always fail with:

![image](https://user-images.githubusercontent.com/6554671/61998456-b8a40380-b0b0-11e9-8a7f-90f04825e6e7.png)

and if I try an npm install I got the same error:

![image](https://user-images.githubusercontent.com/6554671/61998530-e0479b80-b0b1-11e9-9213-ab15c1e631f0.png)

I'm really stuck with this so hopefully you'll be able to help me.
Maybe @acaravia or @pardonmeme will be able to help has they did it ?

Anyway, I'll take any hint to achieve this goal,
thanks

**Comment by acaravia** [comment]
@dipx what does the content of your npmrc file look like? I don't see the complete log but from what I can tell it found your npmrc file but it's trying to access an invalid registry.

**Comment by tagliala** [comment]
I'm pretty confident that the project is not loading the proper `.npmrc` files, since it is trying to download the `fontawesome-pro` package from the npm public registry `registry.npmjs.org`

**Comment by Dipx** [comment]
This is what my .npmrc looks like:
`@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONT_AWESOME_TOKEN}`

I took it from the ["Installing the Pro version of Font Awesome"](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro)

**Comment by Zebirdman** [comment]
> @tagliala , @acaravia

> Well you were right, it was pulling a configuration from another place and it overrode the correct npmrc.
> I tried for 3 hours straight to figure it out. Then I abandonned for some hours, and with your input, I correctly targeted the problem, and easily fixed it. That's frustrating to spend 3hours for something like that haha.

Be amazing if you actually detailed how you got the pipeline to actually use the correct .npmrc

**Comment by djechelon** [comment]
> @tagliala , @acaravia This is what my .npmrc looks like: `@fortawesome:registry=https://npm.fontawesome.com/ //npm.fontawesome.com/:_authToken=${FONT_AWESOME_TOKEN}`

Have you tried `$(FONT_AWESOME_TOKEN)` with round brackets?
