### ISSUE TITLE
Fab facebook circle icon is actually a square not a circle

### ISSUE THREAD

**Issue by smorganTechtonic** [FortAwesome/Font-Awesome#15294]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

I included the  "<i class="fab fa-facebook"></i>" icon on my webpage but the class displays as the square version of the facebook icon and not the round version as expected.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

```
<span class="icon social-icons">
    <i class="fab fa-facebook"></i>
</span>

<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
```

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
I need the circular version of the facebook logo as shown on the website.

**Screenshots**

**Version and implementation**
Version: 

Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ X] On the Desktop

**Bug report checklist**
- [ X] I have filled out as much of the above information as I can
- [X ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[Facebook icon](https://fontawesome.com/icons/facebook?style=brands) has been updated in version 5.8.2

I can see that you are using 5.3.1, please update

Hope it helps

Closing here, but feel free to comment
