### ISSUE TITLE
Icon Request: icon-jenkins

### ISSUE THREAD

**Issue by palerique** [FortAwesome/Font-Awesome#1529]
plan to use it in the menu that will link to the server.

http://thedeveloperworldisyours.com/wp-content/uploads/jenkins_logo.png

**Comment by AlberTajuelo** [comment]
+1

**Comment by jonnung** [comment]
+1

**Comment by floatics** [comment]
+1

**Comment by penne12** [comment]
OMG The +1 is real....

**Comment by CobbleCity** [comment]
+1

**Comment by pbrooks** [comment]
+1

**Comment by adamansky** [comment]
+1

**Comment by jasonmorehead** [comment]
+1

**Comment by penne12** [comment]
Too many +1. Waiting for an awesome person to add this :smile:

**Comment by alibabzo** [comment]
+1

**Comment by tduchateau** [comment]
+1

**Comment by mrchief** [comment]
:+1:

**Comment by nicoco007** [comment]
This issue was opened almost a year ago (one more day to go), and no one from the Font Awesome team has been seen here yet. I'm sad :(

Anyways, here's a black & white svg of the Jenkins logo, if that's useful to anyone:
http://content.nicoco007.com/images/jenkins/Jenkins_logo.svg

**Comment by mrchief** [comment]
They don't accept PRs for fonts and guessing by the new popups on the site, I guess the authors are focusing elsewhere (shift of priorities most likely). Can't blame them though... With so many requests open for new fonts, I feel that this project may have hit its plateau.

**Comment by kaixi** [comment]
+1

**Comment by dales** [comment]
+1

**Comment by mrchief** [comment]
@nicoco007 As a workaround, you can use IcoMoon to generate a font icon from your SVG file.

**Comment by xmj** [comment]
+1

**Comment by qenchi** [comment]
+1

**Comment by ojacquemart** [comment]
+1

**Comment by Alagaros** [comment]
+1

**Comment by mercion** [comment]
+1

**Comment by MCHacker1706** [comment]
+1

**Comment by nagarakesh4** [comment]
+1

**Comment by Trekmarvel** [comment]
+1

**Comment by kgogolek** [comment]
+1

**Comment by twmartin** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by ctrl-f5** [comment]
+1

**Comment by vfiebig** [comment]
+1

**Comment by LuizPanariello** [comment]
+1

**Comment by aanc** [comment]
+1

**Comment by rmorandi** [comment]
+1

**Comment by merlosy** [comment]
+1

**Comment by Stormsys** [comment]
+1

**Comment by zhouguangming** [comment]
+1

**Comment by K-4U** [comment]
+1.. How long does this usually take?

**Comment by wtbarnes** [comment]
+1

**Comment by vargaLaszlo** [comment]
+1

**Comment by vvatsa** [comment]
+1

**Comment by flambert70** [comment]
+1

**Comment by dcoraboeuf** [comment]
FYI, the artwork for the Jenkins logo is available officially at https://wiki.jenkins-ci.org/display/JENKINS/Logo

**Comment by daliati** [comment]
+1

**Comment by Reo7s** [comment]
+1

**Comment by DrOfAwesomeness** [comment]
+1

**Comment by osigida** [comment]
+1

**Comment by pielambr** [comment]
+1

**Comment by ericycoding** [comment]
+1

**Comment by RegionsJob** [comment]
+1

**Comment by siming85** [comment]
+1

**Comment by epgtid** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
