### ISSUE TITLE
Icon request: unity-engine

### ISSUE THREAD

**Issue by JasperDre** [FortAwesome/Font-Awesome#15292]
**What can it be used for?**
This is a frequently requested icon for [Unity](https://unity.com/), a popular game engine.

**Example image (optional)**
<img src="https://img.icons8.com/ios-filled/50/000000/unity.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

I understand that this might be a duplicate of #2888 , but I've added the icon request template.

**Comment by andynataco** [comment]
Thank you Sir!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I understand that this might be a duplicate of #2888 , but I've added the icon request template.

Thank you for having filled out the request template, but #2888 is fine because:
- at the time we didn't have a request template
- the request is pretty self-explanatory
- this is a duplicate 😅 

Please upvote #2888

Closing here

**Comment by andrewio** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > I understand that this might be a duplicate of #2888 , but I've added the icon request template.
> 
> Thank you for having filled out the request template, but #2888 is fine because:
> 
> * at the time we didn't have a request template
> * the request is pretty self-explanatory
> * this is a duplicate 😅
> 
> Please upvote #2888
> 
> Closing here

How many votes you need to implement the icons? When, dude?

**Comment by tagliala** [comment]
@andrewio please take a look at our [Brand  Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work
