### ISSUE TITLE
Missing Logo Nintendo

### ISSUE THREAD

**Issue by Dams920** [FortAwesome/Font-Awesome#15291]
Hi,

I just wanted you to know that Nintendo's logo missing

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately we had to remove Nintendo logo by legal request of Nintendo of America Inc.

Ref:
- https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#582-to-590
- https://fontawesome.com/icons/nintendo-switch?style=brands

Hope it helps

Closing here

**Comment by zypA13510** [comment]
> ## Versioning
> * A `minor` release **may include backward-incompatible changes** but we will write clear upgrading instructions in UPGRADING.md
> * A `minor` or `patch` release will never remove icons

So much for never remove icons. At least please adhere to your own <del>semantic</del> versioning and make it a new major version.

**Comment by tagliala** [comment]
@zypA13510 sorry for that. I hope you can understand the reason because we removed an icon for legal reasons without a major version bump

**Comment by zypA13510** [comment]
I understand the legal reasons, but I don't understand the reluctance to bump the major version as promised. It is the problem semver is trying to solve after all.

**Comment by RetroGameTalk** [comment]
What an utterly disgusting company the more you learn the worse it gets.
Blaming FA for removing the icon is childish.
