### ISSUE TITLE
Font Awesome 5.9.0 Failed to decode downloaded font

### ISSUE THREAD

**Issue by BenjaminHoegh** [FortAwesome/Font-Awesome#15299]
Font Awesome 5.9.0
```
Failed to decode downloaded font: http://localhost:8888/webfonts/fa-solid-900.woff2
Failed to decode downloaded font: http://localhost:8888/webfonts/fa-solid-900.woff
Failed to decode downloaded font: http://localhost:8888/webfonts/fa-solid-900.ttf
```

But it works without any issue in Font Awesome 5.6.x

**Version and implementation**
Version: 5.9.0
Browser and version: Safari 12, Google Chrome 75.0.3770.142, Firefox, Edge

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Since you are hosting Font Awesome on your server, you should check this on your side or provide a reproducible test case

**Comment by BenjaminHoegh** [comment]
**Okay a little update:**
The issue seems to only take effect when trying to use it in [Laravel](https://laravel.com), even on a clean install of both

@tagliala No issue displaying Font Awesome on my server or localhost

**Comment by BenjaminHoegh** [comment]
Found a solution

**Comment by tagliala** [comment]
@BenjaminHoegh feel free to share your solution with others, maybe it will help someone else

**Comment by viveksacademia4git** [comment]
> Found a solution

Can you please share the solution, because I have encountered the same issue. But in my case, the issue is occurring in Angular 8.x.
