### ISSUE TITLE
Icon request: fa-peach

### ISSUE THREAD

**Issue by loyaltyrewardstamp** [FortAwesome/Font-Awesome#15293]
**What can it be used for?**
used for a variety of icons on applications and software development. 

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
![peach icon - Copy](https://user-images.githubusercontent.com/53310105/61889580-5047fd00-aecb-11e9-96d6-296ab7805752.PNG)

**Comment by sensibleworld** [comment]
We've got this icon now! https://fontawesome.com/v6.0/icons/peach?s=solid
