### ISSUE TITLE
Icon Request: icon-gitlab

### ISSUE THREAD

**Issue by palerique** [FortAwesome/Font-Awesome#1530]
plan to use it in the menu that will link to the server.

https://avlux.net/images/gitlab.png

**Comment by cfarence** [comment]
+1

**Comment by baco** [comment]
+1

**Comment by baco** [comment]
gitlab-square would also be nice

**Comment by dblessing** [comment]
:+1:

**Comment by DouweM** [comment]
Note that as of May 20th, we've got a new logo! Check it out here: https://about.gitlab.com/2015/05/18/a-new-gitlab-logo/

![GitLab logo](https://about.gitlab.com/images/new_logo/A.jpg)

Obviously, we would love a GitLab icon in Font Awesome as well.

**Comment by JobV** [comment]
:+1: for the new GitLab logo (fd: I'm a GL engineer)

**Comment by jjatria** [comment]
+1

**Comment by JobV** [comment]
Find the new logo as SVG, EPS, PDF or PNG here:
https://gitlab.com/gitlab-com/gitlab-artwork/tree/master/new_logo

**Comment by dosire** [comment]
Please let us know if we can make it easier to add to Font Awesome (submit an outline or something like that).

**Comment by tsumi** [comment]
+1

**Comment by marcelolebre** [comment]
+1

**Comment by jvanbaarsen** [comment]
+1

**Comment by vsizov** [comment]
:+1:

**Comment by ayufan** [comment]
:+1:

**Comment by randx** [comment]
:+1:

**Comment by michiels** [comment]
:+1:

**Comment by jacobvosmaer** [comment]
+1

**Comment by Razer6** [comment]
:+1:

**Comment by TehRawrz** [comment]
+1

**Comment by sycom** [comment]
:+1:

**Comment by axilleas** [comment]
:+1:

**Comment by gagiD** [comment]
+1

I want GitLab in my social icons! :smile:

**Comment by gbraad** [comment]
+1

**Comment by breisamoralde** [comment]
+1

**Comment by davblayn** [comment]
+1 for the new logo

**Comment by praveenscience** [comment]
:+1:

**Comment by tiffanytse** [comment]
:+1:

**Comment by mlanin** [comment]
:+1:

**Comment by maspalio** [comment]
+1

**Comment by fetzealsvanouds** [comment]
+1 
![+1](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by NurFaizin** [comment]
+1

**Comment by juanwolf** [comment]
+1

**Comment by alemedeiros** [comment]
+1

**Comment by oredigger8806** [comment]
+1

**Comment by bak1an** [comment]
:+1:

**Comment by hobarrera** [comment]
@dosire I'm sure a PR would be most welcome ;)
(sorry, I'm far from being a designer or capable of this sort of work myself).

**Comment by awylie** [comment]
+1

**Comment by riblee** [comment]
+1

**Comment by n3xtSA** [comment]
:+1:

**Comment by gersande** [comment]
+1 !!!!!

**Comment by rwmpelstilzchen** [comment]
+1

**Comment by reveliant** [comment]
+1

**Comment by LukasMa** [comment]
+1 ! :+1:  We need this :)

**Comment by codynguyen1116** [comment]
+1

**Comment by frznchckn** [comment]
+1

**Comment by vindarel** [comment]
+1

**Comment by zeptomoon** [comment]
+1

Attached is the outline in simple, plain, black-on-transparent, as SVG at 1000px square. 
(Added .txt to be able to upload it..)
[gitlab-logo-outline.svg.txt](https://github.com/FortAwesome/Font-Awesome/files/93049/gitlab-logo-outline.svg.txt)

**Comment by dennismarwood** [comment]
+1

**Comment by rockerest** [comment]
+1 - Switching from Github to Gitlab! Would love to be able to update my site(s) to have a nice Gitlab icon.

The Zeptomoon submission looks pretty great.

**Comment by wolverine2k** [comment]
+1

**Comment by Random-Primate** [comment]
+ 1

**Comment by mike-koch** [comment]
+1

**Comment by vptheron** [comment]
+1

**Comment by jamietanna** [comment]
@zeptomoon is there any chance you can send in a PR? It may speed things along somewhat, as it just requires checking by the FontAwesome team, then they can merge it in.

**Comment by ryankane** [comment]
:+1:

**Comment by zeptomoon** [comment]
@jamietanna I'd be happy to submit a PR, but unfortunately the [CONTRIBUTING.md guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests) say:
> **Pull requests**
> • At the moment we are not accepting pull requests containing icons

So, posting the SVG and some rendered example is as far as I can go, I'm afraid...

**Comment by tsigo** [comment]
:+1:

**Comment by jasonchrin** [comment]
+1

**Comment by lukebabb** [comment]
+1

**Comment by d-stephane** [comment]
+1 really useful

**Comment by rockerest** [comment]
For anyone who's interested, I used the SVG uploaded by Zeptomoon above:

```
<!--?xml version="1.0" encoding="UTF-8" standalone="no"?-->
<svg 
    style="margin-top: -0.35em; margin-bottom: -0.35em;" 
    xmlns:svg="http://www.w3.org/2000/svg" 
    xmlns="http://www.w3.org/2000/svg" version="1.1" 
    width="28" height="28"
>
    <path
        transform="scale(.025)" 
        style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1" 
        d="m 186.84485,39.419676 c -5.25074,0 -10.50147,2.07575 -14.19709,6.2261 -0.33602,0.37724 -0.65846,0.77022 -0.96762,1.18176 -0.92808,1.23544 -1.72763,2.62337 -2.37147,4.16792 -0.21455,0.51442 -0.41254,1.04548 -0.59088,1.5942 -3.9e-4,0.001 3.9e-4,0.003 0,0.004 L 1.8663608,566.10769 c -0.6378906,1.96341 -1.10632039,3.95182 -1.41574269,5.94452 -0.77355601,4.98178 -0.53988906,9.99982 0.61467809,14.78004 0.2309109,0.95609 0.4973051,1.90062 0.8010646,2.83545 0.6077251,1.87087 1.3615774,3.69343 2.2524982,5.45279 0.8903449,1.75825 1.919562,3.45245 3.0813224,5.06416 0.58088,0.80585 1.1934745,1.589 1.8400689,2.35165 6.759e-4,7.9e-4 -6.759e-4,0.004 0,0.004 0.647146,0.76348 1.3268247,1.50103 2.0383517,2.21681 1.421017,1.4295 2.970606,2.76065 4.639829,3.9736 L 500.00157,960.5804 984.28076,608.73067 c 8.5e-4,-6.3e-4 0.004,6.1e-4 0.004,0 1.67002,-1.21352 3.21832,-2.54333 4.63982,-3.9736 1.42176,-1.43002 2.71666,-2.96072 3.87842,-4.57242 5.22706,-7.25356 7.7632,-16.16853 7.09062,-25.14232 -0.1495,-1.99416 -0.4558,-3.98984 -0.92796,-5.9723 -0.23612,-0.99121 -0.51386,-1.98064 -0.8328,-2.96234 L 831.28142,52.593616 c -3.9e-4,-10e-4 3.8e-4,-0.003 0,-0.004 -0.17828,-0.54872 -0.37642,-1.07977 -0.5909,-1.59419 -0.64382,-1.54455 -1.44338,-2.93249 -2.37147,-4.16792 -2.47277,-3.29232 -5.84452,-5.48556 -9.51362,-6.583 -2.29319,-0.68601 -4.70182,-0.94481 -7.08269,-0.77331 -0.95105,0.0685 -1.89904,0.20713 -2.83149,0.41243 -10e-4,2.7e-4 -0.002,-2.7e-4 -0.004,0 -2.79999,0.61709 -5.47283,1.85312 -7.76873,3.70393 -7.7e-4,6.2e-4 -0.004,-6.2e-4 -0.004,0 -0.76549,0.61731 -1.48528,1.30369 -2.15733,2.05818 -1.34409,1.50898 -2.48487,3.29198 -3.34306,5.34969 -0.21456,0.51442 -0.41254,1.04547 -0.59088,1.59419 l -110.89588,341.309004 -368.25174,0 L 204.97599,52.593576 c -5.3e-4,-0.002 -0.004,-0.002 -0.004,-0.004 -0.17787,-0.54706 -0.37301,-1.08123 -0.58693,-1.59419 -0.42899,-1.02902 -0.92709,-1.98727 -1.48702,-2.87908 -3.63946,-5.79676 -9.8476,-8.69671 -16.05301,-8.69671 z" 
        id="path1">
    </path>
</svg>
```

It works pretty well. You'll have to mess with the `<svg>` `style` and `width`/`height` to get the effect you want, but it looks great. From [the comment](https://github.com/FortAwesome/Font-Awesome/issues/1530#issuecomment-172248717), the original size is 1000px square, so adjust accordingly.

**Comment by Heliosmaster** [comment]
:+1:

**Comment by l0ner** [comment]
+

**Comment by team-core** [comment]
+1

**Comment by jzola** [comment]
+1

**Comment by M-Medhat** [comment]
+1

**Comment by jjatria** [comment]
Github implemented a new [reactions feature](https://github.com/blog/2119-pull-request-and-issue-reactions) to add support (or whatever!) to tickets without having to keep adding extra `+1`s.

**Comment by ryankane** [comment]
@jjatria, @tagliala would still like people to comment with :+1:s because, he cannot sort by reactions yet.

**Comment by sh1n0b1** [comment]
+1

**Comment by tachyons** [comment]
:+1:

**Comment by mttn** [comment]
+1

**Comment by davegandy** [comment]
Spoke with the GitLab folks. Have a very nice version of the icon going in. Coming very soon.

**Comment by rauko1753** [comment]
+1

**Comment by kfrz** [comment]
@davegandy  The TIMING! I just started building my site and am a huge gitlab fan. Glad to see this is coming.

**Comment by rockerest** [comment]
Awesome to hear @davegandy! Thanks so much for working on this!

**Comment by davegandy** [comment]
Added to 4.6.0-wip branch. Closing.
