### ISSUE TITLE
Icon request: death-star

### ISSUE THREAD

**Issue by simranz** [FortAwesome/Font-Awesome#15308]
**What can it be used for?**
It'll be cool to have it with other star wars icons.

**Example image (optional)**
We all know what a death star looks like.

**Comment by aethior** [comment]
Hi @simranz,

I think [fa-space-station-moon](https://fontawesome.com/icons/space-station-moon) and [fa-space-station-moon-construction](https://fontawesome.com/icons/space-station-moon-construction) icons have a certain resemblance to your request. 😉

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please. :)
