### ISSUE TITLE
twitter.svg: always showing 403

### ISSUE THREAD

**Issue by DoomerDGR8** [FortAwesome/Font-Awesome#15306]
In my console, I get this error logged:

Console:
![image](https://user-images.githubusercontent.com/825078/62116677-a4881e00-b2cb-11e9-849c-d2adde12da8a.png)

Network:
![image](https://user-images.githubusercontent.com/825078/62116614-87ebe600-b2cb-11e9-8633-ad2ad9b34147.png)

Why is this so?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think I've got the issue

![image](https://user-images.githubusercontent.com/556268/62119090-2160cb00-b2bf-11e9-8d22-0c2511b9f43d.png)

Twitter is not part of the `solid` sets but of the `brands` one

The proper usage of the icon is:

```html
<span class="fab fa-twitter"></span>
```

Ref: https://fontawesome.com/icons/twitter

Hope it helps

Closing here, but feel free to comment if it does not fix your issue

**Comment by DoomerDGR8** [comment]
That's the issue here... I'm using the new kit format of using SVG FA5 to
my site. Ever since I converted to the Kit format, I'm always getting this
console error and to further make things worse, I'm not even using the
twitter icon anywhere... there is no "twitter" word in my whole solution.

Regards,
Hassan Gulzar

**Comment by tagliala** [comment]
@DoomerDGR8 could I have a link to your website?

**Comment by DoomerDGR8** [comment]
Intranet Goverment website... No linking

Regards,

Hassan Gulzar
