### ISSUE TITLE
Duotone webfont

### ISSUE THREAD

**Issue by mr21** [FortAwesome/Font-Awesome#15307]
Hi, thanks for your great work!

In the package of the last version (5.10) there are webfonts for the duotone.. it's an error right?
Duotone is only SVG right?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Nope, it's not an error (if you are referring to FA Pro)!

Duotone icons take advantage of before and after pseudoelements.

Here it is an example: https://jsfiddle.net/tagliala/wyzg79d1/4/ 

Hope it helps, closing here

**Comment by mr21** [comment]
Wow amazing! i forgot this possibility :O
Incredible work :)
