### ISSUE TITLE
Missing Duotone style for some icons

### ISSUE THREAD

**Issue by branchard** [FortAwesome/Font-Awesome#15309]
**Describe the bug**
There are missing Duotone style for icons: fa-border-center-h, fa-border-center-v, fa-phone-alt and fa-phone-square-alt.

**Version and implementation**
Version:  5.10.0 

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by rudyleclercq** [comment]
+1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
@branchard Thanks for the heads-up! We'll get these icons properly duotoned!

**Comment by Bene-Graham** [comment]
I also have found that duotone don't work with : ```fa-spinner-third```

**Comment by sensibleworld** [comment]
We've got the missing icons fixed in the most recent 5.10.1 release.

@Bene-Graham Can you open another issue with the `fa-spinner-third` issue you're seeing? Thanks!
