### ISSUE TITLE
Icon request: Curriculum Vitae

### ISSUE THREAD

**Issue by PDACN** [FortAwesome/Font-Awesome#15301]
**What can it be used for?**
can be used as Icon Button to download CV from site

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has been implemented as [fa-file-user](https://fontawesome.com/icons/file-user?style=solid) and it is available in FA Pro

You can also implement `fa-file-user` by using the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/145/

Ref:
#3533
https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here
