### ISSUE TITLE
Icon request: brackets-curly-plus (add metadata)

### ISSUE THREAD

**Issue by kathrine-swe** [FortAwesome/Font-Awesome#15310]
**What can it be used for?**

This icon could be used on UI's where users need to add metadata to whatever it is they originally want to add. A different icon than an ordinary add icon would be necessary if they need to add metadata and then add the original thing that the metadata describes as well. A specific use case can be seen in the geospatial sciences where features drawn on a map might require added metadata to describe the feature. An example of a geospatial science-related UI that uses this symbol can be seen at [Descartes Labs](https://viewer.descarteslabs.com/).

**Example image**
Sorry it's dark - it happened during converting svg to jpg. Act as if it's inverted.
![metadata-add-icon](https://user-images.githubusercontent.com/26444678/62150325-f3798780-b2ba-11e9-8d32-54bb44a0ea7d.jpg)

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/c061tk3e/13/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by kathrine-swe** [comment]
Thanks for the reply. The only reason I posted it as a request was because Jupyter Widgets only allows for fa-icons on their buttons.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
