### ISSUE TITLE
Documentation Issue: Wrong links in 5.10 changelog

### ISSUE THREAD

**Issue by SaswatPadhi** [FortAwesome/Font-Awesome#15317]
The latest changelog (<https://fontawesome.com/changelog/latest>) has a couple of wrong links:
- In the 4th bullet, cotton-bureau should point to [https://fontawesome.com/icons/cotton-bureau?d=gallery&style=**brands**](https://fontawesome.com/icons/cotton-bureau?d=gallery&style=brands) instead of <https://fontawesome.com/icons/cotton-bureau?d=gallery&style=solid>
- In the 8th (last) bullet, facebook-messenger should point to [https://fontawesome.com/icons/facebook-messenger?d=gallery&style=**brands**](https://fontawesome.com/icons/cotton-bureau?d=gallery&style=brands) instead of <https://fontawesome.com/icons/facebook-messenger?d=gallery&style=solid>

On a related note, I think it would be nice to have a separate template for documentation issues ...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @talbs 

> On a related note, I think it would be nice to have a separate template for documentation issues ...

Nice idea!

**Comment by talbs** [comment]
Thanks for the great catches, @SaswatPadhi. We'll get these fixed up right away. 😄

**Comment by talbs** [comment]
Sorry for not following up, gang. `5.10`'s release view was fixed and since then we've updated things to `5.11`. Closing this with all that in mind.
