### ISSUE TITLE
Bug: duotone arrow-alt-to-top, arrow-alt-down, arrow-alt-up point to the wrong side

### ISSUE THREAD

**Issue by Blastius** [FortAwesome/Font-Awesome#15327]
**Describe the bug**
`arrow-alt-to-top` (duotone) arrow points to the bottom like `arrow-alt-to-bottom`.

**Expected behavior**
The icon should point to the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/10246822/62358328-c2948f00-b514-11e9-9668-922648d05aff.png)

**Version and implementation**
Version: 5.10.0
Browser and version: Google Chrome 75

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks!

I've also spotted a couple more:
- [ ] https://fontawesome.com/icons/arrow-alt-down?style=duotone
- [ ] https://fontawesome.com/icons/arrow-alt-up?style=duotone

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
These have been fixed as of 5.10.1
