### ISSUE TITLE
duotone, window-minimize, sort-up, sort-down

### ISSUE THREAD

**Issue by mr21** [FortAwesome/Font-Awesome#15324]
Hi,

The duotone icon for [window-minimize](https://fontawesome.com/icons/window-minimize?style=duotone) is not aligned at the bottom like the others solid/regular/light

**Comment by mr21** [comment]
And this unique path should may be in the `::before` currently it's in the `::after` no?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@sensibleworld is currenty improving a lot of duotone icons, let's add this to the checklist

**Comment by sensibleworld** [comment]
@mr21 Thanks for the report! Getting this fixed in the next update.

**Comment by sensibleworld** [comment]
These are fixed in our most recent update!

**Comment by mr21** [comment]
it's works perfectly :)
