### ISSUE TITLE
duotone, play

### ISSUE THREAD

**Issue by mr21** [FortAwesome/Font-Awesome#15325]
Hi :)

The [play duotone icon](https://fontawesome.com/icons/play?style=duotone) doesn't follow the same logic of [stop](https://fontawesome.com/icons/stop?style=duotone)/[circle](https://fontawesome.com/icons/circle?style=duotone)/[triangle](https://fontawesome.com/icons/triangle?style=duotone) is it normal?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@sensibleworld is currenty improving a lot of duotone icons, let's add these to the checklist

**Comment by sensibleworld** [comment]
The play icon now has `duotone` styling.
