### ISSUE TITLE
Duotone Circle is no longer duotone

### ISSUE THREAD

**Issue by mjsmith037** [FortAwesome/Font-Awesome#15334]
Where the duotone circle used to have two layers: an outer circle (primary) with a faded center (secondary), now it is all one faded color on the [documentation](https://fontawesome.com/icons/circle?style=duotone) and apears indistinguishable from the solid version in practice (i.e. --fa-primary-color and --fa-secondary-color appear to not affect appearance).

**Code Pen Reproduction**
https://codepen.io/mjsmith037/pen/mNBGgL

Version: 5.10.1 SVG with JS

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm that the icon changed from 5.10.0 to 5.10.1, but I don't know if this is an intended change or not

@sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
The circle icon is now properly duotone again :)
