### ISSUE TITLE
ngClass condition with FontAwesome icons SVG

### ISSUE THREAD

**Issue by plixxer** [FortAwesome/Font-Awesome#15333]
ngClass does not work with @fortawesome/fontawesome-free@5.9.0 correctly because the `<i>` dom is replaced with an `<svg>` dom.

`<button type="button" class="btn btn-sm btn-primary" aria-label="Left Align" (click)="toggleVisiblity()">
     <i class="fa fa-lg" [ngClass]="(visible)? 'fa-chevron-up' : 'fa-chevron-down'"></i> {{visible}}
</button>`

Other variations of ngClass also do not work. This is an issue with FontAwesome, not angular.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have an official angular component available at https://github.com/FortAwesome/angular-fontawesome

Does this help?

**Comment by jmarbutt** [comment]
I have issues with the angular version because it can't use the duo tone. So if you are changing the [ngClass] the fontawesome js doesn't update the ui.

**Comment by plixxer** [comment]
@tagliala yes thank you

**Comment by tagliala** [comment]
Thanks, closing here
