### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2fpro-light-svg-icons: Not found".

### ISSUE THREAD

**Issue by gazpachu** [FortAwesome/Font-Awesome#15332]
Not found: https://registry.yarnpkg.com/@fortawesome/pro-light-svg-icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You are trying to download a Font Awesome Pro package from the global public yarn registry

You should configure an `.npmrc` as described here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

Hope it helps

Closing here, but feel free to comment if you still have issues
