### ISSUE TITLE
Duotone Exclamation (fad fa-exclamation)

### ISSUE THREAD

**Issue by KingDumah** [FortAwesome/Font-Awesome#15339]
**Describe the bug**
The Duotone Version of the Exclamation-Icon is not Duotone.

**To Reproduce**
https://fontawesome.com/icons/exclamation?style=duotone

**Expected behavior**
I think it should be the same way as the Question-Icon:
https://fontawesome.com/icons/question?style=duotone

**Screenshots**
![image](https://user-images.githubusercontent.com/8233357/62456380-937e5780-b778-11e9-90d3-937cd6715e0f.png)
![image](https://user-images.githubusercontent.com/8233357/62457049-2ff52980-b77a-11e9-9160-b83adaa9d124.png)

**Version and implementation**
Version: 5.10.1
Browser and version: Chrome v75.0.3770.142

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I don't know if this is a wanted behaviour

Anyway, the docs are loading 5.10.0 in the gallery and 5.10.1 in the individual icon page

Let's assign both @talbs for the documentation and @sensibleworld for the icon

Demo:
- 5.10.0 https://jsfiddle.net/tagliala/wyzg79d1/10/
- 5.10.1 https://jsfiddle.net/tagliala/o1qtda9h/5/

**Comment by sensibleworld** [comment]
The exclamation icon should now be properly duotone: https://fontawesome.com/icons/exclamation?style=duotone
