### ISSUE TITLE
Name is not correct 

### ISSUE THREAD

**Issue by mehulRojasara** [FortAwesome/Font-Awesome#15338]
I think it can be an issue, but it can't be.
I found that in npm package it register as **@fortawesome**, I think it can be **@fontawesome**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Thanks for the report, Fort Awesome is not a typo, the organization name is Fo`r`t Awesome

Ref: https://twitter.com/fontawesome/status/420609150360375296

Hope it helps
