### ISSUE TITLE
Icon request: numpad

### ISSUE THREAD

**Issue by BrianThorne** [FortAwesome/Font-Awesome#15335]
**What can it be used for?**
Code, PIN code

**Example image (optional)**
Numeric pad as is used for entering PIN codes on doors etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6266, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
