### ISSUE TITLE
Icon fas fa-tasks-alt is not pixelperfect with 16px

### ISSUE THREAD

**Issue by mira-matze** [FortAwesome/Font-Awesome#15347]
The black solid icon fas fa-tasks-alt is gray at some points with 16px. This looks inconsistent with other icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

Demo: https://jsfiddle.net/tagliala/o1qtda9h/11/

I can definitely see the issue, let's assign @sensibleworld, so he can take a look

**Comment by sensibleworld** [comment]
Hi there! So, this icon is appearing as designed. We have a limited amount of space at 16px, and because this icon has three "bars" within it, we needed to revert to a 1.5px border within them, as opposed to the standard 2px border in the solid icons.
