### ISSUE TITLE
Search not working with Iranian IP!

### ISSUE THREAD

**Issue by MajideND** [FortAwesome/Font-Awesome#15341]
Hello, I use FA every time but in these recent days I can't search in https://fontawesome.com with Iranian IP.
So I use vpn to use fontawesome website! Why your website and tools are available for Iranian but your search is not working?

**Comment by pgroot91** [comment]
Probably the search engine provider is blocking you due to the sanctions of the US Government.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@robmadole have you any chance to check this?

**Comment by robmadole** [comment]
@MajideND can you provide a trace route to m19dxw5x0q-dsn.algolia.net?

**Comment by MajideND** [comment]
@robmadole when I use trace route I found :
7   140 ms   139 ms   138 ms  et-5-0-0-0.ffttr6.frankfurt.opentransit.net [193.251.154.103]
  8   141 ms   141 ms   140 ms  et-10-0-2-0.ffttr7.frankfurt.opentransit.net [193.251.128.74]
  9     *        *        *     Request timed out.
 10   175 ms   180 ms   173 ms  ae-1.r24.frnkge08.de.bb.gin.ntt.net [129.250.6.206]
 11   427 ms   425 ms   426 ms  ae-4.r20.sngpsi07.sg.bb.gin.ntt.net [129.250.7.63]
 12   426 ms     *      423 ms  ae-1.r01.sngpsi07.sg.bb.gin.ntt.net [129.250.3.100]
 13   398 ms   397 ms   396 ms  116.51.31.54
 14   359 ms   359 ms     *     182.79.188.40
 15   364 ms   360 ms   360 ms  dsl-ncr-static-114.67.16.125.airtelbroadband.in [125.16.67.114]
 16   361 ms   359 ms   360 ms  180.179.197.122
 17   364 ms   361 ms   360 ms  e2e-6-46.e2enetworks.net.in [205.147.109.46]

I have a timeout in trace route!

**Comment by robmadole** [comment]
@MajideND it looks like something is blocking your connection to that service. Unfortunately we can't help you track this down. Your ISP or something further up stream is blocking the connection from you. Sorry we can't help.
