### ISSUE TITLE
Gallery icons don't load (Connection Refused Error)

### ISSUE THREAD

**Issue by InfoSysCodeStudent** [FortAwesome/Font-Awesome#15342]
I'm not really sure what else I can say. I tried it on my phone too so I'm certain the issue is not with my computer. Here's a screenshot:

![Screenshot (17)](https://user-images.githubusercontent.com/51916554/62481785-10113600-b779-11e9-8e3e-fd0cbdb18626.png)

Note the `ERR_CONNECTION_REFUSED` console error for the `pro.min.css` file in Chrome. In Edge the file request returns 200 (OK) but the icons still don't show up.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

We have some issues in Europe, but they don't mention the pro CDNs https://status.fortawesome.com/

I cannot reproduce in Italy, but I'm leaving this open for a while

**Comment by AaronBeaudoin** [comment]
It worked fine for me before the recent update but now this is all I get. Everything works fine on individual icon pages. It's just the gallery that won't load the icon.

**Comment by AaronBeaudoin** [comment]
I just tried opening the page in Opera with the VPN enabled and it works fine. Out of curiosity I tried without the VPN and **it still works...**

Edge doesn't work. So in Chrome and Edge the gallery icons don't load by in Opera they do. What!?

**Comment by tagliala** [comment]
@AaronBeaudoin sorry, cannot confirm. Edge and IE work fine for me.

Could you please provide us more information about your connection (Country / Provider ... it could be a regional issue)?
Could you please try in incognito mode?
Could you please provide us the output of traceroute to `kit-pro.fontawesome.com` from your device with the same network settings of the browser?

**Comment by AaronBeaudoin** [comment]
**Country:** United States (Lincoln, Nebraska)
**Provider:** Network Nebraska (Union College)
**Incognito Mode:** No difference.
**Traceroute Output:** Below...
```
Microsoft Windows [Version 10.0.17134.885]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\MyUserFolder>tracert kit-pro.fontawesome.com

Tracing route to y2e2h8x2.stackpathcdn.com [151.139.128.10]
over a maximum of 30 hops:

  1     *        *        *     Request timed out.
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  ...and so on.
```

I forced stopped it after 27 lines of this.

Please note that although I am on a college network and as such cannot confirm that there are no other factors at play, this issue was not occurring for me at all before the latest update (5.10.0) with the duotone icons.

**Comment by AaronBeaudoin** [comment]
Double checked Opera (which still works) and it reports this `User-Agent` string:

```
[Partially Omitted] ...Chrome/75.0.3770.142 Safari/537.36 OPR/62.0.3331.116
```

While Chrome reports this one:

```
[Partially Omitted] ...Chrome/76.0.3809.100 Safari/537.36
```

Perhaps something changed recently in Chrome 76. It was only released 11 days ago... very close to Font Awesome 5.10.0. I don't know how in the world to confirm this though.

Also it seems that the request to https://kit-pro.fontawesome.com/releases/v5.10.1/css/pro.min.css actually succeeds in Edge, but the icons still don't show up. Baffling.

**Comment by tagliala** [comment]
@robmadole is there anything we can do here?

**Comment by InfoSysCodeStudent** [comment]
My `User-Agent` string still has Chrome `75.0.3770.142`...

**Comment by InfoSysCodeStudent** [comment]
So we took a closer look at our network and so far we haven't found any problems on our end. Is it possible that [this](https://wordpress.org/support/topic/stackpath-cdn-doesnt-work/) is related? Here is [another](https://support.stackpath.com/hc/en-us/articles/360001377786-CORS-Headers-How-to-Fix-Missing-Fonts-and-Stylesheets) possibly related page.

It just doesn't make sense to me that the icons seem to load fine on every page of the website except the gallery. Today I tried it again on my iPhone and weirdly some of the icons load but not all of them. Probably about 10-15% of the icons remain blank seemingly at random.

**Comment by robmadole** [comment]
@InfoSysCodeStudent can you look in your Network tab and send us any additional information you find in there? It sounds like the network in your university is blocking this request.

To test this use `curl`. Running `curl -v -o nul https://kit-pro.fontawesome.com/releases/v5.10.1/css/pro.min.css`. If you see `HTTP/2 200` in the output the request succeeds. We should be able to narrow it down with this since the browsers are being a bit flaky on you. Try running that command on multiple networks (university, VPN, mobile hotspot).

**Comment by InfoSysCodeStudent** [comment]
Here is the output I get on our university network.

```
~ $ curl -v -o nul https://kit-pro.fontawesome.com/releases/v5.10.1/css/pro.min.css
* STATE: INIT => CONNECT handle 0x2530990; line 1404 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x2530990; line 1440 (connection #0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.139.128.10...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x2530990; line 1521 (connection #0)
* connect to 151.139.128.10 port 443 failed: Connection refused
* Failed to connect to kit-pro.fontawesome.com port 443: Connection refused
* Closing connection 0
* The cache now contains 0 members
curl: (7) Failed to connect to kit-pro.fontawesome.com port 443: Connection refused
```

I am not able to test using a VPN at the moment because I do not have full access to the computer I'm using or mobile hotspot because it connects to the network via Ethernet.

I'm pretty confident, however, that VPN and mobile hotspot will have no issues at all.

**Comment by InfoSysCodeStudent** [comment]
I think I found the problem. I spoke with the network guy here at the college and apparently the IP address (151.139.128.10) that `kit-pro.fontawesome.com` routes to is on the following [firehol_level3](http://iplists.firehol.org/?ipset=firehol_level3) blacklist which the college uses. It turns out a quick Google search lists the IP address as being [involved](https://www.abuseipdb.com/check/151.139.128.10) in malicious activities.

Understandably, he does not plan on making any changes on our end to whitelist the IP address. My only option, then, is to use a VPN in order to see the gallery.

It seems rather silly that I have to do that. Can you guys consider using an alternate CDN or clearing the issue with your existing one?

**Comment by robmadole** [comment]
This is a false positive @InfoSysCodeStudent. If your network which is actively blocking a false positive refuses to _not_ block the IP there isn't anything we can do.

**Comment by ErnestPH** [comment]
Hello Guys, I stumbled upon this issue when I tested it in [`www.w3schools.com `](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_social_media_buttons).
It's actually blocked or refusing to connect to social media accounts. Normal websites are ok...

`<a href="https://www.facebook.com/Moonshinepost/"><i class="fa fa-facebook"></i></a>
<a href="https://twitter.com/moonshineatl?lang=en" ><i class="fa fa-twitter"></i></a>
<a href="https://www.instagram.com/moonshinepost/" ><i class="fa fa-instagram"></i></a>
<a href="https://vimeo.com/moonshinepost/" ><i class="fa fa-vimeo"></i></a>`

**Comment by robmadole** [comment]
@ErnestPH please check that you don't have an ad blocker or similar extension that is blocking social icons. Most of the time this is what's happening.

**Comment by ErnestPH** [comment]
> @ErnestPH please check that you don't have an ad blocker or similar extension that is blocking social icons. Most of the time this is what's happening.

Nothing that I can think of... All browsers affected, even Opera. Maybe it the latest upgrade on browser security something. Not sure though.
