### ISSUE TITLE
Duotone fa-swap-opacity doesn't work with some icons (mostly files)

### ISSUE THREAD

**Issue by mira-matze** [FortAwesome/Font-Awesome#15346]
Affected icons:
- [ ] fa-copyright
- [ ] fa-file-download
- [ ] fa-file-edit
- [ ] fa-file-excel
- [ ] fa-file-exclamation
- [ ] fa-file-medical
- [ ] fa-file-minus
- [ ] fa-file-pdf
- [ ] fa-file-plus
- [ ] fa-play-circle

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Reproducible test case: https://jsfiddle.net/tagliala/o1qtda9h/9/

I think I've got what is going on: some file layers are not cut out.

I can also add a couple more:
- fa-file-download
- fa-file-medical

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
These should be fixed in the 5.10.2 release
