### ISSUE TITLE
Icon Request: hair-woman, hair-man

### ISSUE THREAD

**Issue by TrinityG** [FortAwesome/Font-Awesome#15344]
**What can it be used for?**
For beauty industry websites (salons/barber/etc), beauty search engines, in blog articles. Would love a WOMAN / MAN version

**Example image (optional)**
![image](https://user-images.githubusercontent.com/25444686/62489195-fb35a200-b77a-11e9-865e-c122d04167c1.png)
![image](https://user-images.githubusercontent.com/25444686/62489205-02f54680-b77b-11e9-8d63-0a7aa0823453.png)
![image](https://user-images.githubusercontent.com/25444686/62489227-16a0ad00-b77b-11e9-8b3c-f195e51d0e4c.png)
![image](https://user-images.githubusercontent.com/25444686/62489274-32a44e80-b77b-11e9-9b1e-2e2c884221ad.png)
![image](https://user-images.githubusercontent.com/25444686/62489284-389a2f80-b77b-11e9-8804-f15629a1dc54.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
I'm going to consider this closed by 

https://fontawesome.com/icons/user-hair?s=solid
https://fontawesome.com/icons/user-hair-buns?s=solid
https://fontawesome.com/icons/user-hair-long?s=solid
https://fontawesome.com/icons/user-hair-mullet?s=solid

I understand that this could not fit the use case, and if they don't, feel free to fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md), and remember to add:

- Use cases
- small size, 16px friendly icons
- Why the existing `user-hair` icons do not fit the use case

Thanks

**Comment by ivoryrolland95** [comment]
thanks for sharing!
