### ISSUE TITLE
Duotone Phone (fad fa-phone / fad fa-phone-alt)

### ISSUE THREAD

**Issue by KingDumah** [FortAwesome/Font-Awesome#15340]
**Describe the bug**
The Duotone Version of the Phone-Icon is not Duotone.

**To Reproduce**
https://fontawesome.com/icons/phone?style=duotone

**Expected behavior**
Should be like in the Gallery:
https://fontawesome.com/icons?d=gallery&q=phone&s=duotone

**Screenshots**
![image](https://user-images.githubusercontent.com/8233357/62457217-99753800-b77a-11e9-9d9d-a5fda9a0bda9.png)
![image](https://user-images.githubusercontent.com/8233357/62457307-d93c1f80-b77a-11e9-922f-230d447119b6.png)

**Version and implementation**
Version: 5.10.1
Browser and version: Chrome v75.0.3770.142

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I don't know if this is a wanted behaviour

Anyway, the docs are loading 5.10.0 in the gallery and 5.10.1 in the individual icon page

Let's assign both @talbs for the documentation and @sensibleworld for the icon

Demo:
- 5.10.0 https://jsfiddle.net/tagliala/wyzg79d1/7/
- 5.10.1 https://jsfiddle.net/tagliala/o1qtda9h/2/

**Comment by sensibleworld** [comment]
We've made a minor update to add duotone coloring to the phone icon: https://fontawesome.com/icons/phone?style=duotone
