### ISSUE TITLE
Icon bug: bell-plus Pro

### ISSUE THREAD

**Issue by guibohu** [FortAwesome/Font-Awesome#15354]
Hi! When I copy the Unicode Glyph of the bell-plus icon in any design app (Figma, Sketch, etc) it turns into a kind of arrow instead the bell-plus.

https://fontawesome.com/icons/bell-plus?style=light

![Captura de pantalla 2019-08-08 a las 8 40 17](https://user-images.githubusercontent.com/32207356/62680738-38d33e80-b9b8-11e9-9d7c-fa515169c16e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please make sure that you have installed the latest version of Font Awesome?

https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#updating

**Comment by guibohu** [comment]
Ooops! Yeah, I've checked it and there was a conflict with the .otf file, but I've replaced it and now ir works perfect. Thank you :)
