### ISSUE TITLE
Icon request: Body Part Injured ( Set )

### ISSUE THREAD

**Issue by LeahPike** [FortAwesome/Font-Awesome#15357]
**What can it be used for?**
Our customers have a form they fill in regarding an injury at the workplace. We would like to provide icons on our form so it is easier to understand for people where English is not their first language.

This would be a set of icons:

- Ankle
- Arm
- Back
- Elbow
- Eyes
- Face
- Fingers
- Foot
- Groin
- Hand
- Head
- Internal
- Knee
- Neck
- Skin
- Toes
- Torso
- Wrist

**Example Image**
A college of mine has mocked up some examples of what they'd like:
![image](https://user-images.githubusercontent.com/6124100/62692939-75f3fc80-b9c9-11e9-9c60-b6ebeeaa6633.png)

I have read the guidelines and will happily create 18 issues ( one per icon ) if you'd prefer.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I have read the guidelines and will happily create 18 issues ( one per icon ) if you'd prefer.

Yes, please create individual requests

If you are a Font Awesome Pro customer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
