### ISSUE TITLE
Website Create Account Link

### ISSUE THREAD

**Issue by aecmax** [FortAwesome/Font-Awesome#15350]
The create account link redirects to fontawesome.com/start rather than presenting a form :( 
![image](https://user-images.githubusercontent.com/38046236/62619507-f68cfd00-b8e4-11e9-91dc-d465e3d988fc.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That should be correct, please provide your email address and then you should receive information on how to access your new account

Let me know

**Comment by aecmax** [comment]
I feel dumb, but it doesn't seem to be most intuitive it looks like a search bar so I dismissed it! Thanks.

**Comment by tagliala** [comment]
@aecmax You're welcome, but I think you're right: it does not feel like a registration form 😅
