### ISSUE TITLE
Icon request: hockey-goal

### ISSUE THREAD

**Issue by bramroos** [FortAwesome/Font-Awesome#15353]
Hockey goal to symbolise all small sport goals would be awesome ;-)
Leaving out the hockey puck it would suit sports like hockey, field hockey, indoor football/soccer etc.

![Screenshot 2019-08-07 at 16 21 07](https://user-images.githubusercontent.com/53786058/62631141-8906be00-b930-11e9-92d0-1dbfe6076771.png)

[X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
[X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
[X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
[X] I have included at least one example image if it could be helpful (optional)
[X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @bramroos,

`fa-goal-net` icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/goal-net

Regards.

cc/ @tagliala
