### ISSUE TITLE
Icon request: fa-cart-times

### ISSUE THREAD

**Issue by Julie-ringelmann** [FortAwesome/Font-Awesome#15366]
**What can it be used for?**
cart cancellation/abandonment in relation to online shopping

**Example image (optional)**
![Cancel-Order](https://user-images.githubusercontent.com/45173737/62929883-a5d14480-bdbb-11e9-830e-ebd95e64dd60.png)
![icon_cancellations](https://user-images.githubusercontent.com/45173737/62929884-a669db00-bdbb-11e9-9803-f4441f0889c6.gif)
![images (1)](https://user-images.githubusercontent.com/45173737/62929886-a7027180-bdbb-11e9-8621-82da5a5025b0.png)
![images](https://user-images.githubusercontent.com/45173737/62929887-a79b0800-bdbb-11e9-8622-98be76a645b4.png)
![istockphoto-912163278-1024x1024](https://user-images.githubusercontent.com/45173737/62929889-a8339e80-bdbb-11e9-8201-b73cdbf1940f.jpg)
![online_shop_ecommerce_shopping-46-512](https://user-images.githubusercontent.com/45173737/62929890-a8339e80-bdbb-11e9-9546-39e74f3820a1.png)

**Icon request checklist**
- [ ] This is a single icon
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/154/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment]
Hi @Julie-ringelmann,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/cart-circle-xmark

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to the Pro set

In a web application it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:https://jsfiddle.net/tagliala/bfa6uhse/70/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
