### ISSUE TITLE
Icon request: cart-desktop & cart-store

### ISSUE THREAD

**Issue by Julie-ringelmann** [FortAwesome/Font-Awesome#15368]
**What can it be used for?**
Icon pair depicting online vs offline shopping. 

**Example image (cart-online)**
![8-512](https://user-images.githubusercontent.com/45173737/62931096-019ccd00-bdbe-11e9-9223-5674ad5fcde5.png)
![Computer-columns-interface-monitor-desktop_43-512](https://user-images.githubusercontent.com/45173737/62931097-019ccd00-bdbe-11e9-890a-ee706b90951f.png)
![shopping-23-512](https://user-images.githubusercontent.com/45173737/62931098-019ccd00-bdbe-11e9-8a1f-8a5d914a874d.png)

**Example image (cart-offline)**
![cart_from_shopping_store-512](https://user-images.githubusercontent.com/45173737/62931112-06fa1780-bdbe-11e9-9643-dca06f862298.png)
![store-cart-shop-shops-stores-512](https://user-images.githubusercontent.com/45173737/62931114-06fa1780-bdbe-11e9-97a1-c005e02fdfad.png)

**Icon request checklist**
- [ ] This is a matched pair (Ex: `cart-online` / `cart-offline`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please split this request into two separate ones

Your request is legit, but please keep in mind that `cart-desktop` could be achieved with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/13/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
