### ISSUE TITLE
version 4.7.0 not loading in IE

### ISSUE THREAD

**Issue by memoshasinha** [FortAwesome/Font-Awesome#15371]
Font awesome 4.7.0 is not loading in IE, but works in chrome.
Its an angular project. Included in angular-json as 
 "node_modules/font-awesome/css/font-awesome.min.css",
 <meta http-equiv="X UA-Compatible" content="IE=edge"> is added in head in index.html

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but version 4.7.0 is in EOL and we do not have an official angular component for FA4

If you are able to replicate this issue with FA5, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
