### ISSUE TITLE
辅助功能图标第二行第一列显示问题

### ISSUE THREAD

**Issue by yumu101** [FortAwesome/Font-Awesome#15374]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per google translate:

> Accessibility icon second row first column shows problem

Sorry, I cannot understand this issue

Could you please fill out in English our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

Thanks!

**Comment by yumu101** [comment]
I can’t speak English.
Maybe:
The accessibility icon shows the problem in the second row and first column.
![QQ图片20190814170418](https://user-images.githubusercontent.com/53859433/63008823-e90fde00-beb5-11e9-82c5-fd96cfc5a37f.png)

**Comment by tagliala** [comment]
@yumu101 that's ok, please try google translate

The screenshot does not look like Font Awesome's official website.

Can you please provide a link to the page showing the issue?

**Comment by yumu101** [comment]
I‘m sorry
