### ISSUE TITLE
Desktop doesnt work use Photoshop - Duotone and 5.10.1 icons

### ISSUE THREAD

**Issue by tatof** [FortAwesome/Font-Awesome#15378]
Photoshop can't use some icons like:
fa-rings-wedding

Every time I copy -> paste the icon it changes back to "myriad pro".
Also the "duotone" icons don't work, they just only show the dark part.

-----
Fontawesome PRO version 5.10.1.
Windows 10 - updated to latest
Photoshop CC - updated to latest

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Also the "duotone" icons don't work, they just only show the dark part.

About duotone icons, does https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/duotone-icons#using-ligatures help?

> fa-rings-wedding

I didn't understand why the title reports 5.0.7, you mean 5.7.0?

Meanwhile, could you please follow this guide to make sure that version 5.10.1 is installed and there aren't older versions cached somewhere?

https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#updating

**Comment by tagliala** [comment]
by the way, I cannot reproduce with ligatures

![image](https://user-images.githubusercontent.com/556268/63011147-075ee500-be88-11e9-9c6a-a6fc7c24953f.png)

I've also tried to copy the unicode glyph from https://fontawesome.com/icons/rings-wedding?style=solid and everything is fine

Using W10 1903 / FA Pro 5.10.1 otfs / Photoshop CC 2018

**Comment by tatof** [comment]
Its working now, there is this weird bug with windows where it just doesn't install or replaces fonts.
Every release I install the new font awesome. But somehow it removes icons made in version 5.7.0.

Anyhow it works now! thanks for the quick support

**I've got feature request:**
I use the site alot to copy -> paste icons in my photoshop documents. Could both Glyphs for duotones be posted so I can copy both from the website?

**Comment by tagliala** [comment]
> I use the site alot to copy -> paste icons in my photoshop documents. Could both Glyphs for duotones be posted so I can copy both from the website?

I was actually thinking about the same feature, let's say something like
![image](https://user-images.githubusercontent.com/556268/63015639-c8ce2800-be91-11e9-95ba-878e68de780d.png)

@talbs @robmadole given that ligatures are not recommended, is there any chance of implementing this?

**Comment by tatof** [comment]
Yes thats perfect!
