### ISSUE TITLE
Icon request: icon-blackberry

### ISSUE THREAD

**Issue by Ruben-E** [FortAwesome/Font-Awesome#1537]
Thanks for the icons! 

However, I would like to see the blackberry logo next to the Apple and Android logo.

Thanks!

**Comment by pierreluctg** [comment]
Any reason why this is still pending?

**Comment by shahzoorali** [comment]
+1

**Comment by juriejan** [comment]
+1

**Comment by mbhnyc** [comment]
Need this also! +1

**Comment by iamrauu** [comment]
+1

**Comment by LauritzT** [comment]
+1

**Comment by halgatewood** [comment]
+1

**Comment by tc7200** [comment]
+1

**Comment by geeksamu** [comment]
+1

**Comment by VinceZampella** [comment]
+1

**Comment by Wohlraj** [comment]
+1

**Comment by clegginabox** [comment]
+1

**Comment by santolead** [comment]
+1

**Comment by baliomega** [comment]
+1

**Comment by anonprophet** [comment]
+1

**Comment by 756gzdz5** [comment]
+1

**Comment by komaval** [comment]
+1

**Comment by kirchrath** [comment]
+1

**Comment by 3Nex** [comment]
+1 How do these requests get prioritized that Blackberry still doesn't exist...? :-/

**Comment by shmshd12** [comment]
+1

**Comment by komputa** [comment]
+ 1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by rahst12** [comment]
+1

**Comment by sirwoetang** [comment]
+1

**Comment by jamesbs** [comment]
+1

**Comment by wolfy1339** [comment]
Here's an SVG version of the icon (because I know they prefer SVG examples):

![BlackBerry Logo without wordmark](https://upload.wikimedia.org/wikipedia/commons/0/08/Blackberry_Logo_without_wordmark.svg)

**Comment by iamrauu** [comment]
Used icomoon instead.. no point waiting years for an approval.

**Comment by vaeum** [comment]
+1

**Comment by tiff7** [comment]
+1

**Comment by kazuser** [comment]
From first message (10 Jul 2013) to last (20 Jan 2016) = almost 2,5 years and still no any movements...

**Comment by efixdent** [comment]
+1

we need fontawesome to provide blackberry icon, thank you very much.

So long time from 2013 until now 2016. Did font-awesome hate blackberry? why don't you provide blackberry icon in font awesome's database icon...?

**Comment by anonprophet** [comment]
+1k

**Comment by amreladawy** [comment]
Is there any legal issues preventing making this icon?

**Comment by janpieper** [comment]
+1

**Comment by kazuser** [comment]
Almost 3 years just for one small BlackBerry icon - still can't believe...


:facepalm:

**Comment by akaien** [comment]
+1 pretty please :)

**Comment by kazuser** [comment]
Please get ready everyone: 10 Jul we will celebrate "**3 years for 1 BlackBerry icon**" anniversary! See you soon!

**Comment by matthax** [comment]
If I donate can we get this done? This is absolutely ridiculous, I'm going to have to start tagging BlackBerry devs...

**Comment by 3Nex** [comment]
At this point, they're not gonna make it just to spite the requests.

**Comment by iamrauu** [comment]
++1.. eventhough I've moved on to icomoon.

**Comment by baliomega** [comment]
Let's move on!

**Comment by daveliao** [comment]
+1, even though demand for this is probably pretty low at this point.

**Comment by kazuser** [comment]
Ta-daaaaa: **3 years**!

![3](https://cloud.githubusercontent.com/assets/3335273/16789888/15290d9c-48d3-11e6-8563-85e23c118b18.jpg)

**Comment by Viras-** [comment]
+1

**Comment by edwinkrisnha** [comment]
+1

**Comment by gowthamdandu** [comment]
+1

**Comment by leonardoalves2** [comment]
+1

**Comment by VitaliiKotliar** [comment]
+1

**Comment by iamrauu** [comment]
@tagliala this still has traction.. any eta?

**Comment by noormaulida** [comment]
+1

**Comment by sachin10190** [comment]
wow!

**Comment by pandhu** [comment]
any good news yet?
it's almost 4 years. 
this request will get a bachelor degree in 2 months

**Comment by shahzoorali** [comment]
Hahahhahahaha

**Comment by jbmikk** [comment]
There! It moved.

2017-05-14 8:54 GMT-03:00 shahzoorali <notifications@github.com>:

**Comment by kazuser** [comment]
![happy-4th-birthday](https://user-images.githubusercontent.com/3335273/28447505-fa463aa4-6df2-11e7-8de4-ae09e95c1127.jpg)

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by daveliao** [comment]
@urlsnort you'll need a time machine: travel to the future when Font Awesome 5.0 comes out, then you can use the BlackBerry emoji. 😉

**Comment by kazuser** [comment]
**Ruben-E** they (F-A) finally did it! Can you see their answer, man? You got it after ~4,5 years waiting, about 100 comments, 15 similar topics, and here is the "5.0" with f###ing BB-icon now.

BTW, BB is almost dead already - but they think it's ok.

I believe a BB-icon is like (or instead?) a memorial to BB. F##k! Why you have sooooo slowly reaction, F-A? :(

**Comment by timtjtim** [comment]
Please calm down Kaz. This project is their project. When you create a massive icon set and give it away for free, you’re welcome to add all the icons people request on the day they request them. Till then, be happy with what they give us.

**Comment by kazuser** [comment]
I'm already calm and happy with another icon sets - I'm just don't understand why they are so deaf and blind to the requests of their own community: 4,5 years for 1 icon of 7 dots. I still can't believe 🤦‍♂️
