### ISSUE TITLE
Unable to reference "free" glyphs unless they're font family is "Pro"

### ISSUE THREAD

**Issue by kavery22** [FortAwesome/Font-Awesome#15373]
Summary:
The "Free" version is no longer rendering the glyphs in html outputs. When changing the "Font-Family" to "Font Awesome 5 Pro" from "Font Awesome 5 Free" we are able to render the glyph. However, we don't have a pro license, and this is a "free" kit.

Repro:
https://codepen.io/kellie7/pen/PoYZQRK

Notes:
Please advise if we're doing something incorrectly.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This has already been reported in #15137, please follow that issue

Closing here
