### ISSUE TITLE
Icon request: angle-to-left, angle-to-right

### ISSUE THREAD

**Issue by mira-matze** [FortAwesome/Font-Awesome#15370]
**What can it be used for?**
In Grid or Table footer. Go to first page / Go to last page. For example in material ui table.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
These icons should now be available: https://fontawesome.com/search?q=angle&o=r&s=solid
