### ISSUE TITLE
Documentation at @fortawesome/fontawesome-common-types is out of date

### ISSUE THREAD

**Issue by rooby** [FortAwesome/Font-Awesome#15384]
**Describe the bug**
The documentation at https://www.npmjs.com/package/@fortawesome/fontawesome-common-types is out of date.

It says:

> If you are trying to import types from this package we highly recommend you do the following instead as all types in this package are re-exported to the main fontawesome package.
> your.ts
> ```
> import {
>   IconName
> } from `@fortawesome/fontawesome`
> 
> const myIcon: IconName = "..."
> ```

However @fortawesome/fontawesome is deprecated now.

**Comment by tagliala** [comment]
Hi!

Thanks for the report

Let's assign @robmadole and @mlwilkerson

**Comment by robmadole** [comment]
Thanks @rooby we've got this fixed and it will go out in the next release of Font Awesome.
