### ISSUE TITLE
Feature request: Figma Plugin

### ISSUE THREAD

**Issue by johnbwoodruff** [FortAwesome/Font-Awesome#15383]
**Is your feature request related to a problem? Please describe.**
Not a problem with Font Awesome. More a workflow annoyance for me individually.

**Describe the solution you'd like**
Figma now allows for plugins. There is a new Material Design Icons plugin that allows you to easily search for an icon and add it to your design. I use and love Font Awesome, and currently I simply have the SVG files downloaded to my computer, and I drag and drop those in, then resize them to fit my needs. It would be amazing if there was an official Font Awesome plugin (that ideally even included the pro icons) that would allow me to do the same as the Material Design Icons plugin.

**Describe alternatives you've considered**
I've considered building such a plugin myself as a third party offering, although I'm not super familiar with how I might do that with how Font Awesome's repo is built. I'm still investigating it, but a first party solution is always a better option.

**Additional context**
Here's a screenshot of how the plugin works:

<img width="1680" alt="Screen Shot 2019-08-15 at 3 05 08 PM" src="https://user-images.githubusercontent.com/5883616/63126883-2e8fe200-bf6e-11e9-98ee-be5ff3ef6339.png">

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hey @johnbwoodruff, thanks for the suggestion! We've actually been discussing this internally already. No set plans yet, but it's definitely on our radar, and something we'd like to make happen.

**Comment by azilnik** [comment]
Potentially an addition to this feature, or a separate request—what about going the other way? It would be amazing if one is able to create icons in Figma and use Figma to sync these designs into Fort Awesome.

**Comment by megaroeny** [comment]
> Potentially an addition to this feature, or a separate request—what about going the other way? It would be amazing if one is able to create icons in Figma and use Figma to sync these designs into Fort Awesome.

That kind of thing would only be internal to the team.

**Comment by sensibleworld** [comment]
No progress yet on the Figma plugin, unfortunately. We've been hard at work on other features and icons for Font Awesome 6. That said, we're definitely open to collaboration on this, if someone  has experience with building plugins for Figma.

As for sending things from Figma TO Font Awesome... we're launching a new Icon Upload feature soon!

**Comment by kuvahaku** [comment]
+1 for the plugin for the designer

**Comment by megaroeny** [comment]
Following-up some years later... 😅 

Any consideration for this? Other icon libraries have done the same thing. Check out [Phosphor's](https://phosphoricons.com/) approach. Very elegant. They offer a "raw" stroke format and a flattened/optimized version:
- [Phosphor plugin](https://www.figma.com/community/plugin/898620911119764089/Phosphor-Icons)

**Comment by sensibleworld** [comment]
Yup! We'll get there. Sorry for the massive delay. The plan is to link the plugin directly to one of your Font Awesome Kits, so you have access to not only FA icons, but any custom icons you uploaded or built, as well. We've been focused on other things, but our attention is shifting back in this direction.

**Comment by elioqoshi** [comment]
@sensibleworld another follow up from me here! Would be great to have this. 

In fact this is the only thing which is blocking us from getting FontAwesome Pro as the Figma integration is quite cumbersome. As far as I am concerned, having all pro icons on Figma would be currently a manual job by putting all SVG files into a Figma library, right? As Pro icons are not free, there is also no way to get it from Figma community. Maybe a less cumbersome approach for you would be to bundle all SVG's into a .fig file for every release? Would that be sensible (no pun intended)?

**Comment by sensibleworld** [comment]
Hey there! We have a plugin in the works! If all goes well, it should be in your hands in 2-3 weeks. Stay tuned.

In the meantime, we do already have a component file that takes advantage of our typeface and ligatures: https://www.figma.com/community/file/994237671938398148

**Comment by sensibleworld** [comment]
Took longer than we'd hoped, but we've finally released an official Font Awesome Figma Plugin. Check it out here: https://www.figma.com/community/plugin/1283461555078380603/font-awesome-icons-official
