### ISSUE TITLE
two youtube icons display incorrectly

### ISSUE THREAD

**Issue by secret-agent-girl** [FortAwesome/Font-Awesome#15393]
Regarding:
https://fontawesome.com/icons/youtube?style=brands
https://fontawesome.com/icons/youtube-square?style=brands

I've inserted both of these YouTube icons in turn, and neither displayed correctly. In both cases the play triangle does not show up but instead the text "You" over the text "Tube" displays.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that there is an old version of Font Awesome that is conflicting with the newer one.

Please check that you are using the latest version of Font Awesome (5.10.1) and that your application does not have third-party plugins/themes/libraries loading an older version of Font Awesome

Hope it helps

Closing here
