### ISSUE TITLE
Icon Request: icon-gender, icon-gender-male, icon-gender-female (all genders)

### ISSUE THREAD

**Issue by dinusuresh** [FortAwesome/Font-Awesome#1539]
my suggestion for the icon is illustrated in the below pictures,

![connected_male_and_female_symbols_stickers](https://f.cloud.github.com/assets/1288053/774319/9e3cf92c-e954-11e2-81ed-ede6e425b606.jpg)
![male-and-female-signs](https://f.cloud.github.com/assets/1288053/774320/9e6e5346-e954-11e2-824c-a340af5fb8c3.jpg)

I would like to use it in forms when asking the user for their gender.

and PS
awesome set of icons :)

**Comment by Deathangel908** [comment]
Common guys, +1 )

**Comment by Kowts** [comment]
:+1:

**Comment by Kyttias** [comment]
+1 
Adding the current female/male symbols next to cats and dogs to show their genders just isn't going to fly. Venus/mars symbols would be great!

**Comment by dipth** [comment]
:+1:

**Comment by seanmhanson** [comment]
+1 for a transgender-friendly symbol (see http://en.wikipedia.org/wiki/LGBT_symbols#Transgender for the most standard). 
+1 for fa-gender-female and fa-gender-male as well

-1 for usage of fa-male and fa-female. They're inappropriate for being inclusive, and are tied to cultural stereotypes that need to be avoided in UI/UX (and honestly everywhere).

**Comment by melinath** [comment]
+1 for gender-inclusive symbols

**Comment by davegandy** [comment]
Pretty extensive set has been added to 4.3.0-wip. It includes all 13 gender symbols found here: http://en.wikipedia.org/wiki/Gender_symbol

**Comment by jplehmann** [comment]
And there was much rejoicing.

**Comment by tagliala** [comment]
Great :+1:

**Comment by Lynda333** [comment]
Awesome Work!

**Comment by dinusuresh** [comment]
Nice work :100:  

they are awesome :+1:

**Comment by ARoddis** [comment]
I realy! appreciate the deversity. :+1: 

Thanks alot!

**Comment by pkurek** [comment]
hahahahahahaha tumblr on github
