### ISSUE TITLE
Icon request: hand-holding-rupee

### ISSUE THREAD

**Issue by thammuio** [FortAwesome/Font-Awesome#15392]
**What can it be used for?**
Hand Holding Rupee

**Example image (optional)**
₹
<img width="139" alt="Screen Shot 2019-08-18 at 1 37 40 PM" src="https://user-images.githubusercontent.com/6325610/63228759-604ab800-c1bd-11e9-8142-d665c41b841f.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/167/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by thammuio** [comment]
Here is the code I wrote for React for this icon:

![Screen Shot 2019-08-21 at 8 58 20 PM](https://user-images.githubusercontent.com/6325610/63480147-732be980-c456-11e9-82f7-2d30222dc572.png)


```
<span className="fa-layers fa-fw text-center">
    <FontAwesomeIcon className="text-white text-center" icon="hand-holding" size="3x" transform="left-4" />
    <FontAwesomeIcon className="text-white text-center" icon="rupee-sign" size="3x" transform="up-4 shrink-6" />
</span>
```

**Comment by davidrojo** [comment]
Hello, althouhg it is possible to make this icon joining the two icons, I think that, as there is already a version with usd `hand-holding-usd`, there should be a version for euro, rupee, ruble, pounds, etc.  to maintain consistency.

Think for example a website with € and $, to change the icon just a variable change can do the job.

`<i class="fas fa-hand-holding-{ currency }"></i>`

**Comment by tagliala** [comment]
Hi @davidrojo 

I understand the need and easiness of having a single icon, and I can also agree on the consistency point of view. Doing that will require the effort of build 44 new icons (11 currencies * 4 styles)

Also, the above icon `hand-holding-usd` has been sponsored, as you can see in the docs

![image](https://user-images.githubusercontent.com/556268/64515735-709e1080-d2ed-11e9-9ed0-fee9129c6862.png)

Anyway... in the application you described, you can move the variable to the other icon in the stack. That will also allow for a free duotone implementation

```
<div class="fa-layers fa-3x fa-fw">
  <span class="fas fa-hand-holding"></span>
  <span class="fas fa-{ currency }" data-fa-transform="up-4 shrink-8"></span>
</div>
```

**Comment by thammuio** [comment]
Thanks all.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by tagliala** [comment]
Ref: #20294
