### ISSUE TITLE
I can't find the brand Icon of NetEase

### ISSUE THREAD

**Issue by Patrick-Jun** [FortAwesome/Font-Awesome#15395]
Netease is a big company in China, who can submit an icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that this request is a duplicate of #8255, please add a 👍 reaction to that request. If this isn't a duplicate, feel free to comment and provide more information

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Please also take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs), you will find a lot of information on how requests work

Closing here
