### ISSUE TITLE
Icon request: icon-H-sans-serif, icon-L-sans-serif, icon-D-sans-serif

### ISSUE THREAD

**Issue by mattdurso** [FortAwesome/Font-Awesome#15408]
**What can it be used for?**
In weather mapping apps, low-pressure, high-pressure, and tropical-depressions are visualized as "L", "H", and "D". It would be helpful to incorporate these ideas, that are more granular states of developing storms, as FA icons.

**Example image (optional)**
![high and low pressure](https://user-images.githubusercontent.com/54330640/63379774-9ec9a980-c35a-11e9-8343-05206ab0345a.png)
This depicts High and Low pressure systems, and Tropical-depressions are simply a "D" in the same style.

Thank you!

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

H is already here: https://fontawesome.com/icons/heading?style=solid

**Comment by mattdurso** [comment]
Hi - the style for the weather icons is distinctly sans serif, as opposed to the slab-style of the header icon, but thank you for the feedback

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/h?f=classic&s=solid
https://fontawesome.com/icons/l?f=classic&s=solid
