### ISSUE TITLE
icon request: icon-thin-close (thinner icon-times / icon-close)

### ISSUE THREAD

**Issue by fxck** [FortAwesome/Font-Awesome#1540]
could you add a lighter version of `<i class="icon-remove"></i>`

similar to angle/chervon fashion

**Comment by jsalonen** [comment]
+1

**Comment by gtn130** [comment]
+1

**Comment by becevka** [comment]
+1

**Comment by tabosque** [comment]
+1

**Comment by cvsguimaraes** [comment]
+1

**Comment by nesrinkalender** [comment]
+1

**Comment by hongyanh** [comment]
+1

**Comment by bgold0** [comment]
+1

**Comment by skerrvy** [comment]
+1

**Comment by mquandalle** [comment]
+1

**Comment by lutzhoeger** [comment]
+1

**Comment by homerjam** [comment]
+1

**Comment by knownasilya** [comment]
:+1:

**Comment by vmasto** [comment]
+1

This is much needed for mobile navigation close buttons or slickier-looking remove buttons of larger size, e.g. http://d.pr/i/18ad7

e.g. here's the dashicons equivalent: http://d.pr/i/xso7

**Comment by jreiter** [comment]
+1

**Comment by aphex13** [comment]
+1

**Comment by Hrafnkellos** [comment]
+1

**Comment by borysboyko** [comment]
+1

**Comment by grssnbchr** [comment]
+1

**Comment by teyou** [comment]
+1 for the thinner version of X

**Comment by mg1075** [comment]
+1

**Comment by johnnyghost** [comment]
+1

**Comment by iamgraeme** [comment]
+1

**Comment by iMestav** [comment]
+1

**Comment by larsbo** [comment]
+1

**Comment by vosnikopa** [comment]
+1

**Comment by njcameron** [comment]
+1

**Comment by 3nki** [comment]
jsalonen's posted solution works great! however, this really does need to be officially included, so i'll give it Yet Another +1

**Comment by nikolowry** [comment]
+1

**Comment by saytionne** [comment]
+ 1

**Comment by jennyma** [comment]
+1

**Comment by homerjam** [comment]
https://materialdesignicons.com/

**Comment by omniosi** [comment]
+1

**Comment by zorahrel** [comment]
+1

**Comment by nixon1333** [comment]
+1

**Comment by alvarotrigo** [comment]
+1

**Comment by nextriot** [comment]
+1

**Comment by YesThatAllen** [comment]
+1 please, and thanks!

**Comment by TheChen5** [comment]
+1

**Comment by warps** [comment]
+1

**Comment by rhysd** [comment]
+1

**Comment by jhall3rd** [comment]
+1

**Comment by alitabatabaei** [comment]
+1

**Comment by eumesmo1** [comment]
A beautiful set of icons but the close button is horrible, a real shame.

**Comment by iorrah** [comment]
+1

**Comment by rafistrauss** [comment]
+1

**Comment by adriansprod** [comment]
+1 pretty please

**Comment by ovidiua2003** [comment]
+1

**Comment by meetajhu** [comment]
+1

**Comment by scooterlord** [comment]
+1

**Comment by srmor** [comment]
+1

**Comment by mib23** [comment]
+1

**Comment by rubaff** [comment]
+1

**Comment by alexmigf** [comment]
+1

**Comment by menzow** [comment]
+1

**Comment by nikolowry** [comment]
Was reminded of this issue after being seeing v4.6 on HackerNews. You guys really dropped the ball - would be super simple to implement and eliminate the need for users to modify source or prevent them from choosing a different icon font altogether.

**Comment by KamaKAzii** [comment]
+1

**Comment by teemuremes** [comment]
+1

**Comment by 3nki** [comment]
+2

**Comment by jholt1** [comment]
+1

**Comment by becker1** [comment]
+1

**Comment by PeteFromSales** [comment]
+1

**Comment by SannePetersx** [comment]
+1

**Comment by dustincaruso** [comment]
+1

**Comment by fourroses666** [comment]
so many icons but this thin one is really missing

+1

**Comment by DarrenPaulWright** [comment]
+1

**Comment by canariasnorlyGXA** [comment]
+1

**Comment by vc1492a** [comment]
+1

**Comment by chenzhihao** [comment]
+1

**Comment by mkarganov** [comment]
+1

**Comment by 3chordme** [comment]
+1

**Comment by aidangarza** [comment]
+1

**Comment by dtab428** [comment]
+1

**Comment by tsucharoku** [comment]
+1

**Comment by aidangarza** [comment]
I have temporarily found a work-around in my app by using this:

```
<style>
  .join { margin-right: -0.125em }
</style>

<i class="fa fa-angle-right join"></i>
<i class="fa fa-angle-left"></i>
```

**Comment by mrosinski** [comment]
+1

**Comment by SuperPat45** [comment]
+1

**Comment by XanderGlassman** [comment]
+1

**Comment by gerardliu** [comment]
+1

**Comment by sibnerian** [comment]
+1

**Comment by peterpme** [comment]
@tagliala mind closing this thread? At this point we're beating a dead horse here.

**Comment by YSavir** [comment]
+1

**Comment by tomdav999** [comment]
x100

**Comment by marketica** [comment]
+1

**Comment by Boomwav** [comment]
+1

**Comment by pavanesh2009** [comment]
+1

**Comment by joffff** [comment]
+1

**Comment by kkriminal** [comment]
+1

**Comment by fabtho** [comment]
+1 thanks

**Comment by catalin88** [comment]
Yeah +1

**Comment by TUNER88** [comment]
+1

**Comment by Flyer53** [comment]
+1
Not only the close icon. I need a whole set of well fitting icons for actions like Close, Maximize, Minimize, Normalize. All sorts of icons you could use in a window/layout manager

**Comment by benunternaehrer** [comment]
+1

**Comment by anraiki** [comment]
This is still not in?! +1!

**Comment by fourroses666** [comment]
+2

**Comment by andyblack19** [comment]
How the f*ck has this not been addressed yet... I'm actually switching away from FA for this reason, I presume many others have too

**Comment by case12** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by keikreutler** [comment]
+1

**Comment by Shekhargupta06** [comment]
+1

**Comment by swiltshire-studygroup** [comment]
+1

**Comment by rosariogueli** [comment]
+1

**Comment by evanschris** [comment]
+1

**Comment by R-G-B** [comment]
+1

**Comment by kubilaysalih** [comment]
+1

**Comment by euvl** [comment]
+1

**Comment by fourroses666** [comment]
-1

**Comment by mintaras** [comment]
+1

**Comment by jeison-fox** [comment]
+1

**Comment by Jwata** [comment]
+1

**Comment by leowebdev** [comment]
+1

**Comment by epicfaace** [comment]
+1

**Comment by asim-bashir-confiz** [comment]
+1

**Comment by aorcsik** [comment]
Add this to your css:

```
.fa-angle-times::before {
    content: "\F105\F104";
    letter-spacing: -0.15em;
}
```

**Comment by clearchaos** [comment]
Perfect @aorcsik !  Thank you.

**Comment by nicolassharp** [comment]
+ 1

**Comment by remcokalf** [comment]
+1 for icon-thin-close
It would be nice if it pairs well with the thinness of fa-bars, for hamburger menu open/close actions.

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[Thin close icon is here](https://icons8.com/icon/46/delete)

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280) and [Line icon](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534).

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by PrestaShark** [comment]
Still nothing?! Almost 4 and a half year and no thin close/times icon? OMFG

**Comment by silverkorn** [comment]
Still waiting for my broom (#239)... 
Dust has accumulated for 5 years and an half now...

**Comment by wpexplorer** [comment]
+1

**Comment by Putzilla** [comment]
I believe this is solved by `<i class="fal fa-times"></i>` in Font Awesome 5 Pro correct?

**Comment by PrestaShark** [comment]
@Putzilla correct. 
But i have PRO TIP for You guys!

✖ works really well. The HTML code is &#10006;
and it's free!
