### ISSUE TITLE
Update fa-laravel

### ISSUE THREAD

**Issue by hebbet** [FortAwesome/Font-Awesome#15406]
Laravel got a redesign with a new logo. please update fa-laravel

new logo:
https://laravel.com/img/logomark.min.svg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up!

Assigned both @talbs and @sensibleworld: please let me know if you have any preference when I have to assign brand related issues

**Comment by sensibleworld** [comment]
@tagliala Thanks! Go ahead and assign these to me.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/laravel?style=brands
