### ISSUE TITLE
Duotone: spinner-third add a circle on the background

### ISSUE THREAD

**Issue by mr21** [FortAwesome/Font-Awesome#15409]
Hi :)

With the [spinner-third](https://fontawesome.com/icons/spinner-third?style=duotone) icon, if you add a circle in the background (the `::after` is not used here) we could custom this spin even more!

See the Twitter spinner for example:
![image](https://user-images.githubusercontent.com/850754/63388969-7f5a6d00-c3aa-11e9-9203-c0897b98492f.png)

**Comment by sensibleworld** [comment]
Great idea, @mr21! This has been fixed in the most recent release!

**Comment by mr21** [comment]
Thanks, it's work as expected :)

**Comment by rarenatoe** [comment]
any plans to have a thinner option of this?
