### ISSUE TITLE
jail icon

### ISSUE THREAD

**Issue by briciou62500** [FortAwesome/Font-Awesome#15404]
**What can it be used for?**
On my WebSite, I have an option put in prison. 

**My problem**
On your website, I don't find a jail Icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #12945, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
