### ISSUE TITLE
Icon request: Country Flags

### ISSUE THREAD

**Issue by AndrewPaget** [FortAwesome/Font-Awesome#15405]
**What can it be used for?**
A range of country flags. To be used, for example, when a customer creates an account and specifies their country, the flag representing their nation will be next to their account details...this would be a nice touch Or  When setting their contact number...a menu with the flags that represent their country code

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment we are accepting individual requests with flags that make sense in single color, take a look here: https://github.com/FortAwesome/Font-Awesome/labels/flags%20%28category%29

Anyway, please keep in mind that a lot of world flags doesn't make sense in single color (🇫🇷 , 🇮🇹 , 🇧🇪 , 🇮🇪, 🇷🇴 , 🇹🇩 , 🇭🇺 , 🇳🇱 , 🇷🇺, ...), so we should provide full color svgs just like other flag libraries out there

Hope it helps

Closing here
