### ISSUE TITLE
Some of the free icons are not showing !!!

### ISSUE THREAD

**Issue by jyotiprakash111** [FortAwesome/Font-Awesome#15410]
Some fre icons are not showing in my project , it's really annoying.

    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-vector-icons": "^6.6.0"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

> react-native-vector-icons

By the way, that is not Font Awesome 😅

**Comment by tagliala** [comment]
Continues on #15411
