### ISSUE TITLE
FontAwesome  icon not showing(Some icons)

### ISSUE THREAD

**Issue by jyotiprakash111** [FortAwesome/Font-Awesome#15411]
**Describe the bug**
i am using _FontAwesome_ icons in my react-native project, but unfortunately some icons are showinf  & some are not showing (https://fontawesome.com/icons?d=gallery,). some icons are showing and some are showing like Question mark icon.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

**Screenshots**
![Issues FontAwesome](https://user-images.githubusercontent.com/45302047/63404392-aba0d880-c400-11e9-8408-9319c6bc1b38.jpeg)

**Version and implementation**
Version: 
Browser and version: 

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do

**Comment by tagliala** [comment]
Hi,

could you please provide a reproducible test case and provide all your relevant information from `package.json`?

The bell icon doesn't look like Font Awesome's [fa-bell](https://fontawesome.com/icons/bell?style=solid)

The same happens with [backward](https://fontawesome.com/icons/backward?style=solid)

**Comment by jyotiprakash111** [comment]
{
  "name": "BookMyShow",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by jyotiprakash111** [comment]
these are the icon lists: the commented one are not working. and remaining are working out of the box.


                <Icon name='area-chart' size={20} color='red'/>
                <Icon name='angle-right' size={20} color='blue'/>
                <Icon name='heart' size={20} color='red'/>
                <Icon name='apple' size={20} color='red'/>
                <Icon name='facebook' size={20} color='red'/>
                <Icon name='bookmark' size={20} color='red'/>
                <Icon name='500px' size={20} color='red'/>
                <Icon name='chrome' size={20} color='red'/>
                <Icon name='clipboard' size={20} color='red'/>
                {/* <Icon name='clock' size={20} color='red'/> */}
                <Icon name='cloud' size={20} color='red'/>
                <Icon name='arrow-down' size={20} color='#19b5fe'/>
                {/* <Icon name='asterisk' size={20} color='#19b5fe'/> */}
                {/* <Icon name='aircraft' size={20} color="blue" /> */}
                {/* <Icon name='award' size={20} color='#19b5fe'/> */}
                <Icon name='bell' size={20} color='#19b5fe'/>
                <Icon name='bomb' size={20} color='#19b5fe'/>
                {/* <Icon name='burn' size={20} color='#19b5fe'/> */}
                <Icon name='bullseye' size={20} color='#19b5fe'/>
                {/* <Icon name='box-open' size={20} color='#19b5fe'/> */}
                {/* <Icon name='book-open' size={20} color='#19b5fe'/> */}

                <Icon name='backward' size={20} color='#19b5fe'/>
                <Icon name='bars' size={20} color='#19b5fe'/>

                <Icon name='angle-double-down' size={40} color='#000'/>
                {/* <Icon name='airbnb' size={40} color='#EE0060'/> */}
                <Icon name='amazon' size={40} color='#000'/>
                {/* <Icon name='apple-alt' size={40} color='#000'/> */}
                <Icon name='arrow-circle-left' size={40} color='#000'/>
                <Icon name='angle-right' size={40} color='#000'/>
                <Icon name='angle-left' size={40} color='#000'/>
                <Icon name='arrow-right' size={40} color='#000'/>
                {/* <Icon name='aws' size={40} color='#000'/> */}
                <Icon name='backward' size={40} color='#000'/>
                {/* <Icon name='atom' size={40} color='#000'/> */}
                <Icon name='ban' size={40} color='#000'/>
                {/* <Icon name='adn' size={40} color='#000'/> */}
                <Icon name='battery-empty' size={40} color='#000'/>
                <Icon name='battery-full' size={40} color='#000'/>

**Comment by tagliala** [comment]
Sorry, but I cannot see font awesome in `package.json`

`react-native-vector-icons` is not font awesome, it looks like this repository to me: https://github.com/oblador/react-native-vector-icons

It looks like a third-party plugin using Font Awesome 5.7 and we do not have control on it, sorry!

**Comment by tagliala** [comment]
@jyotiprakash111 did you fix this issue?

**Comment by jyotiprakash111** [comment]
yeah i think there are some premium icons are there,only those icons are not showing.
