### ISSUE TITLE
 Icon request: gopay

### ISSUE THREAD

**Issue by futamiyarn** [FortAwesome/Font-Awesome#15418]
**What can it be used for?**
because the motorcycle has entered the global market, it never hurts to use this

**Example image (optional)**
![gopay](https://lelogama.go-jek.com/component/howto/howto_steps/gopay-1.jpg)
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ianpwk** [comment]
Please
