### ISSUE TITLE
Icon request: aviutl

### ISSUE THREAD

**Issue by parselmouths** [FortAwesome/Font-Awesome#15412]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more information about this brand?

Is there any official website?

**Comment by parselmouths** [comment]
Thank you for your reply.
There is no official website. But the software distribution site is the
link below.

http://spring-fragrance.mints.ne.jp/aviutl/



2019年8月21日(水) 23:11 Geremia Taglialatela <notifications@github.com>:

**Comment by tagliala** [comment]
@parselmouths thanks.

Could you please post a single color example of the brand? I'm not able to understand what is the official logo of AviUtl

**Comment by parselmouths** [comment]
@tagliala 
Sorry. I can present only the link below.
[https://aviutl.info/wp-content/uploads/2015/11/AviUtl_icon-150x150.png](https://aviutl.info/wp-content/uploads/2015/11/AviUtl_icon-150x150.png)

**Comment by tagliala** [comment]
Ok, thanks.

I know that it is not the same and that brand icons must be implemented as they are, but we already have a similar icon: https://fontawesome.com/icons/film?style=solid

**Comment by parselmouths** [comment]
Oh, I didn't know that.
Thank you, I'll use it.

**Comment by tagliala** [comment]
You're welcome.

This request is valid, but feel free to close it if `fa-film` fits your use case and you don't need this one anymore
