### ISSUE TITLE
Duotone "minus-circle" icon not consistent

### ISSUE THREAD

**Issue by HapLifeMan** [FortAwesome/Font-Awesome#15413]
Hey, I'm switching my light icons to duotone icons since the release (🎉) and I just noticed that the duotone `minus-circle` icon is exactly the same as the solid.
I think this is an error because it is inconsistent with the `plus-circle` which is correct and follow other duotone guidelines (transparency, etc...).

**Please see below the render of both duotone icons:**

![Capture d’écran 2019-08-21 à 14 10 35](https://user-images.githubusercontent.com/1854141/63430781-b7e75e80-c41d-11e9-8ccb-dd96e3210993.png)

And here is the `minus-circle` icons on the gallery: https://fontawesome.com/icons?d=gallery&q=minus-circle.

Can you take a look at this? Thanks and great work otherwise 😊

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm.

I've also checked other duotone circle icons https://fontawesome.com/icons?d=gallery&q=circle&s=duotone and this is the only one that looks inverted

**Comment by sensibleworld** [comment]
@HapLifeMan @tagliala We'll get this fixed in the next release!

**Comment by sensibleworld** [comment]
@HapLifeMan Thanks for the heads up on this issue. The `minus-circle` icon has been fixed.

**Comment by HapLifeMan** [comment]
Thank you very much! 😁
