### ISSUE TITLE
Icon Request: icon-bathtub

### ISSUE THREAD

**Issue by ldsenow** [FortAwesome/Font-Awesome#1542]
Hi,

I would like to request some icons for a real estate website that I am dealing with.
It would be perfect that this project can include more and more industry icons. 

![capture](https://f.cloud.github.com/assets/177045/774519/520be696-e95c-11e2-92c9-ecbde9abf128.PNG)

PS: This is project is super super awesome!!!!! Thanks for all the hard work

**Comment by xoomboom** [comment]
+1

**Comment by Crissov** [comment]
- 🛁 [U+1F6C1](http://emojipedia.org/bathtub/) Unicode emoji #222 
- 🛀 [U+1F6C0](http://emojipedia.org/bath/)

**Comment by sensibleworld** [comment]
Closing this old issue, as we now have these icons available :)

https://fontawesome.com/icons/bed?style=solid
https://fontawesome.com/icons/bath?style=solid
https://fontawesome.com/icons/car-side?style=solid
