### ISSUE TITLE
I come from China, I hope to provide China site, the site opened too slowly

### ISSUE THREAD

**Issue by antusen** [FortAwesome/Font-Awesome#15424]
I come from China, I hope to provide China site, the site opened too slowly

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@antusen could you please confirm that the website you mean is https://fontawesome.com/ ?

**Comment by antusen** [comment]
Yes, page loading is sometimes slow and you want to provide a Chinese website

**Comment by tagliala** [comment]
Thanks for the feedback

@robmadole is there any chance to check speed in China?

**Comment by robmadole** [comment]
@antusen are you using Kits?

**Comment by antusen** [comment]
I'm still using version 4.7.
