### ISSUE TITLE
fa-sort-amount-down-alt is missing

### ISSUE THREAD

**Issue by komidesign** [FortAwesome/Font-Awesome#15430]
**fa-sort-amount-down-alt** is missing from Font Awesome 5 Free Solid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/q2oa94hv/1/

[sort-amount-down-alt](https://fontawesome.com/icons/sort-amount-down-alt?style=solid) has been introduced in Font Awesome 5.9.0

Please check that you are using the latest version available (5.10.2) and there aren't third-party plugins/themes/library loading older versions of Font Awesome that may take priority over the latest version
