### ISSUE TITLE
fa-spin issue when using web-font based kit

### ISSUE THREAD

**Issue by lu3do** [FortAwesome/Font-Awesome#15432]
```
<i class="fas fa-spinner-third fa-spin"></i>
or 
<i class="fas fa-circle-notch fa-spin"></i>
```

the icon doesn't spin around the center.

I created a jsfiddle with using my FA kit and just the icon html, to make sure it wasn't some of my css that affected the icon spinning, also tried different icons.

when changing to svg instead of webfont the issue doesn't occur, but i'm actually dependent on web-font so I can't use svg instead.

video of issue:
https://www.dropbox.com/s/glrjdirwaxrb4dr/font-awe-issue.mov?dl=0

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That's a known issue and we can't do anything about that, sorry

It is also documented at https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons#issues

Hope it helps

Closing here

Ref: #671

**Comment by tinwe** [comment]
filter: blur(0);
Worked like a charm for me. Just hoping they add this to the standard CSS code.
