### ISSUE TITLE
Icon-request: union and intersection (math)

### ISSUE THREAD

**Issue by luk156** [FortAwesome/Font-Awesome#1544]
AND and OR symbol

**Comment by Aliuken** [comment]
I think intersection would be better understandable with circles
https://en.wikipedia.org/wiki/Intersection_%28set_theory%29#/media/File:Venn0001.svg

**Comment by cassiopagnoncelli** [comment]
For mathematical symbols please refer to [native HTML codes](https://www.w3schools.com/charsets/ref_utf_math.asp). Standard fonts provide a variety of styles.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/intersection?style=solid
https://fontawesome.com/icons/union?style=solid
