### ISSUE TITLE
Icon request: data-room

### ISSUE THREAD

**Issue by mkollarc** [FortAwesome/Font-Awesome#15441]
This icon can be used for representing data rooms, securely files stored online or vaults.

Example image
![image](https://user-images.githubusercontent.com/54618801/63835071-4cffcf80-c9a9-11e9-8834-52103a9a418e.png)

**Comment by aethior** [comment]
Hi @mkollarc,

This icon has ben added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/vault

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Duplicate of #1813
