### ISSUE TITLE
Icon request: line-chat

### ISSUE THREAD

**Issue by charatwit** [FortAwesome/Font-Awesome#15440]
**What can it be used for?**
LINE it is a most popular social media in asia Ex. Thailand , Japan, Korea

**Example image (optional)**
https://line.me/en/logo
https://line.me/en/

Icon request: line-chat

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[line](https://fontawesome.com/icons/line?style=brands) is available in Font Awesome 5.0.0

Please make sure that you are using the latest version available (5.10.2 at the moment I'm writing)
