### ISSUE TITLE
Bad Gateway Drone CI FontAwesome-pro-5.9.0

### ISSUE THREAD

**Issue by CarlosAzocar** [FortAwesome/Font-Awesome#15454]
**Describe the bug**
In my Drone configuration when initializing and trying to download the FontAwesome-pro-5.9.0, respond with a BadGateway

```
npm ERR! code E504
npm ERR! 504 Gateway Time-out - GET https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.9.0.tgz
```

**Comment by Adriiad** [comment]
Same here

**Comment by wicowen** [comment]
get 500 error on travis-ci build

$ npm install
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/pro-light-svg-icons-5.10.2.tgz
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-08-29T16_01_38_060Z-debug.log
```

**Comment by RyanMarshCodes** [comment]
Experiencing this with Yarn on Azure Pipelines as well:
![image](https://user-images.githubusercontent.com/41705585/63959316-c5659f80-ca40-11e9-9631-b2106f0d02ff.png)

**Comment by truthuntold** [comment]
I'm also getting the 504 errors. It seems like they are aware of the issue.

https://status.fortawesome.com/

> We are again seeing slow response times (around 30 seconds for some) from the NPM registry server. Since we are proxying requests to their service it proportionately impacts our private NPM server as well. We are keeping an eye on things and will update everyone as we discover information.

**Comment by SquallX** [comment]
Hi,

I've same error for FA 5.10.1

Are you working on it ? Thanks

**Comment by bfagundez** [comment]
Same here: 
https://downforeveryoneorjustme.com/npm.fontawesome.com

Says is down for everyone.

**Comment by charlex** [comment]
Seeing:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free-solid/-/fontawesome-free-solid-5.0.13.tgz: ESOCKETTIMEDOUT".
```

**Comment by EIrwin** [comment]
Any update on this?

**Comment by bloodf** [comment]
Guys any update? Got a big hotfix to deliver and it is stuck because of this down!!!

![image](https://user-images.githubusercontent.com/1626923/63964099-c3193a80-ca6c-11e9-897d-18fc707f05b6.png)

**Comment by clovenlife** [comment]
+1

**Comment by sunitadhamankar** [comment]
any update?

**Comment by charlex** [comment]
I just received this response from the FA support email:

```

Hi there,Very sorry for the inconvenience.  We are looking into this issue now.  You can keep track of the status here: https://status.fortawesome.com/.--Trevor
--
 

```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Sorry for the late reply and sorry for the inconvenience, we are already aware of issues on the npm pro repository: https://status.fortawesome.com/incident/115

@charlex thanks for sharing the answer you've got by email

**Comment by charlex** [comment]
@tagliala Does FortAwesome have plans to host the pro packages on the public registry if you can't bring up the private registry?

**Comment by tagliala** [comment]
@charlex I definitely agree that something should be done on our side to increase pro repository's uptime, but I don't know if using the public repository is a viable solution, sorry.

Let's me ask internally if there are plans to increase the uptime

**Comment by KKS1** [comment]
This seems resolved now ! Thank you so much !

**Comment by ermalsh** [comment]
> This seems resolved now ! Thank you so much !

+1 back up for me as well.

**Comment by robmadole** [comment]
We are looking at some alternative package managers.

One issue is that whenever the main NPM registry has an issue they manifest in our private registry as well. A lot of the downtime today was related to network conditions to the NPM registry servers. (Not all, we had an EC2 instance that went south on us too.) Some of the problems we can control and some of them we cannot. However, it doesn't matter if it's us or them; if it's not working for our customers it's not working.

So what are we planning to do about it?

Right now the goal is to find a solution that will allow us to host private repositories that does not rely on the main NPM registry. There are a few offerings out there. We just need to pick one and implement it.

I'm not sure I understand what @charlex is asking but the answer is: no, we will not make Pro packages publicly available. What we'll do is work toward a better solution for private package management.

**Comment by bfagundez** [comment]
Is this solved...?

**Comment by robmadole** [comment]
@bfagundez as far as we know. If you are having issues send us an email at hello@fontawesome.com.

**Comment by bfagundez** [comment]
Confirmed it is solved on my end as well. thanks @robmadole

**Comment by designbyadrian** [comment]
Seems to be new issues since September 3rd. https://status.fortawesome.com

**Comment by robmadole** [comment]
We are holding the npm.fontawesome.com service as having "Performance issues" until we can get a replacement setup.

**Comment by HodofHod** [comment]
Still an issue here.

**Comment by robmadole** [comment]
We'll be upgrading this service very soon to new infrastructure. @HodofHod is it the 502 Bad Gateway error?

**Comment by HodofHod** [comment]
@robmadole, No, I get ESOCKETTIMEDOUT (like #15455, which was closed in favor of this) and when I increase the network timeout, yarn throws "unexpected end of input" when unzipping the tgz.

**Comment by robmadole** [comment]
@HodofHod the infrastructure upgrade will hopefully fix that for you.

**Comment by robmadole** [comment]
We have now fully deployed the rollout of the new infrastructure. Anyone who was previously having problems please test again and report back if you still have issues.

**Comment by bloodf** [comment]
I've deleted the lock files when I get this error and sometimes it works.

**Comment by robmadole** [comment]
@bloodf feel free to send us an email to hello@fontawesome.com to work on this. Our new hosting provider, CloudSmith, is very responsive to issues and we'd like to get this fully fixed for you if we can.
