### ISSUE TITLE
ESOCKETTIMEDOUT error while installing font awesome

### ISSUE THREAD

**Issue by zverexe** [FortAwesome/Font-Awesome#15455]
**Describe the bug**
while running yarn add @fortawesome/fontawesome-pro I have this error:

info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.10.2.tgz: ESOCKETTIMEDOUT".

Is it some problems with your servers? If no, how I fix that error?

**Comment by KKS1** [comment]
+1 This is effecting us huge. Can we please get a resolution!

**Comment by KKS1** [comment]
just to mention, this is happening irrespective of the version ^5.9.0 or 5.10.2.

**Comment by clovenlife** [comment]
+1

**Comment by charlex** [comment]
This issue appears linked: #15454

**Comment by ermalsh** [comment]
Happening globally right now - the fontawesome-pro registry may be down. I get as far as Fetching Packages 2024/2025 before it fails. Even --network-timeout xxxxx won't help.

**Comment by pvaliyaveedan** [comment]
+1

**Comment by MikeFielden** [comment]
+1

**Comment by aaj** [comment]
+1

**Comment by CarlosAzocar** [comment]
+1

**Comment by deantoni** [comment]
Any updates?

**Comment by FullofQuarks** [comment]
+1

**Comment by thomas-nguyen-roostify** [comment]
+1

**Comment by robclancy** [comment]
This is an on and off issue because of how they do the dependencies. I don't know how many times it needs to come up until they package it better. Our deployment has been blocked by this.

**Comment by zverexe** [comment]
@robclancy ours blocked too

**Comment by tagliala** [comment]
Hi everyone and sorry for this

Let's use a single post: #15454

**Comment by robmadole** [comment]
We have upgraded the infrastructure and this should fix the root cause of these gateway errors.

Please let us know if you still have issues.
