### ISSUE TITLE
Pin Icon Request

### ISSUE THREAD

**Issue by obscurecodes** [FortAwesome/Font-Awesome#15451]
Please Create Pin Icon.
Regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/map-marker-alt fit your use case?

**Comment by obscurecodes** [comment]
Hi
I had problem, I can't see any icon but after turning on VPN it be ok.

**Comment by obscurecodes** [comment]
Thanks!
