### ISSUE TITLE
Icon request: rockrms

### ISSUE THREAD

**Issue by frogydiak** [FortAwesome/Font-Awesome#15456]
**What can it be used for?**
Brand logo for opensource project Rock RMS which actually supports FontAwesome Free and Pro.

**Example image (optional)**
![touch-icon-ipad-retina](https://user-images.githubusercontent.com/1373815/63985402-73df0400-ca84-11e9-8f6e-fda764683b3b.png)

I can provide SVG version if needed. Thanks!

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by frogydiak** [comment]
Sorry my bad I didn't realized that there's already an icon, someone pointed it out.

**Comment by tagliala** [comment]
Sorry, I didn't realize either
