### ISSUE TITLE
webfont/fa-solid-900.wff2 NOT FOUND

### ISSUE THREAD

**Issue by zentaker** [FortAwesome/Font-Awesome#15468]
the file in the webfont Folder fa-solid-900.woff2 give an error like is no there
ERR_FILE_NOT_FOUND

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please start another issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?
