### ISSUE TITLE
Wrong viewbox for some Duotone icons

### ISSUE THREAD

**Issue by branchard** [FortAwesome/Font-Awesome#15471]
**Describe the bug**
Some Dutone icons have wrong viewboxes.
E.g. the "fa-calculator" icon does not have the same SVG viewbox in Solid and Duotone sets.
I haven't listed all the icons that have this issue, but I observed it for the following icons: Anchor, Blind, Calculator, Directions...

**To Reproduce**
https://codepen.io/branchardb/pen/VwZMmXv

**Expected behavior**
E.g. the "fa-calculator" icon should have the same SVG viewbox in Solid and Duotone sets.

**Screenshots**
![fa-screenshot](https://user-images.githubusercontent.com/6990948/64124763-30e49f80-cda8-11e9-8c20-57bf4016d825.jpg)

**Version and implementation**
Version: 5.10.2

- [x] SVG with JS
- [ ] Web Fonts with CSS (untested)
- [x] SVG Sprites
- [ ] On the Desktop (untested)

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by rudyleclercq** [comment]
+1 same problem, many duotone icons has wrong viewbox

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld could you please take a look here?

**Comment by sensibleworld** [comment]
Thanks for the heads up. Looks like this is definitely an issue on a few icons. Oops! We'll get this fixed.

**Comment by branchard** [comment]
Here's the list of icons that have this issue (I may have forgotten some of them):
- Anchor
- Blind
- Brain
- Calculator
- Alternate Calculator
- Chair
- Office Chair
- Clone
- Directions
- Filter
- Gopuram
- Face With Tongue
- Wizard's Hat
- Location
- Minus Hexagone
- Times Hexagone
- Tire Flat
- Palm Tree
- Trophy
- Alternate Trophy
- Whale

I also spotted other issues:
- The clapper of the Duotone Bell is not centered
- The Duotone Filter and the Duotone Paperclip only have one color.

**Comment by sensibleworld** [comment]
These should all be fixed in 5.11.
