### ISSUE TITLE
Icon request: user-search

### ISSUE THREAD

**Issue by trollsyn** [FortAwesome/Font-Awesome#15473]
**What can it be used for?**
To search for users, and as a complement to other user-icons. We already have great search icons (magnifiers), but in some cases it's very usable with specific types of search - like searching for a user. If your application already has a search icon present, it might be confusing with a duplicate icon for a user-scoped search.

**Example image (optional)**
![fa-user-search-example](https://user-images.githubusercontent.com/2777940/64161136-6e473c80-ce3d-11e9-9bba-32340fe9e8e7.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/227/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by trollsyn** [comment]
Thank you! That is an awesome solution for now. And a powerful demonstration of the mentioned features 😮

**Comment by mrlife** [comment]
Please make this icon happen :)

Not everyone can use the SVG/javascript framework...

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
