### ISSUE TITLE
Icon request: emoji-hype/drooling

### ISSUE THREAD

**Issue by cosmo-101** [FortAwesome/Font-Awesome#15479]
**What can it be used for?**
This icon would be using for describe "hype", there is a lot of hype these days.
**Example image (optional)**
This is the image I want for hype/drooling icon. I prefer much this one over the rest of existing drooling icons (or very similar).
![hype_icon](https://user-images.githubusercontent.com/40916628/64253199-0405c900-cf1d-11e9-9f25-5f0486fac039.PNG)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @cosmo-101,

`fa-face-drooling` icon was added in v6.0.0.
Check https://fontawesome.com/icons/face-drooling

Regards.

cc/ @tagliala
