### ISSUE TITLE
Icon request: lifecycle

### ISSUE THREAD

**Issue by joe-mills** [FortAwesome/Font-Awesome#15470]
**What can it be used for?**
Application lifecycles, repeating process, process flow

**Example image (optional)**
![image](https://user-images.githubusercontent.com/46459393/64106374-f65f1080-cd6f-11e9-92f5-9e7a5b125e28.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have this icon in two flavors!
https://fontawesome.com/icons/sync-alt?style=solid
https://fontawesome.com/icons/sync?style=solid

**Comment by joe-mills** [comment]
sync!  thanks :)

**Comment by tagliala** [comment]
🍦 you're welcome
