### ISSUE TITLE
Icon Request: icon-fish

### ISSUE THREAD

**Issue by rubyvi** [FortAwesome/Font-Awesome#15489]
We are using a new version of Geonetwork open source and we would like to have an icon about fishing, because the issues we handle refer to the sea. 

We will make use of the ship icon but we also require a fish icon for biota topic.

![boton-04](https://user-images.githubusercontent.com/54993057/64439596-e9a02c80-d08f-11e9-8443-bbc9cdd09d67.png)

**Comment by mapto** [comment]
Have you considered using [the currently exisiting one](https://fontawesome.com/icons/fish?style=solid)? It does not have the waves, but it is just the fish symbol, which is more universal.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Closing here because we already have a fish icon.

Also, there is a request for fishing at #6445

Closing here
