### ISSUE TITLE
icon not showing. version 5.10.2

### ISSUE THREAD

**Issue by nikanjuri** [FortAwesome/Font-Awesome#15487]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
I do not see the 'hackerrank' icon when i try to add it to my code.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

nikhilanjuri.com - 4th circle in the about section. it's hackerrank icon.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 5.10.2
Browser and version: Google Chrome Version 76.0.3809.132

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm seeing the following error

```
GET https://nikhilanjuri.com/css/font-awesome.min.css net::ERR_ABORTED 404
```

**Comment by nikanjuri** [comment]
it should work now. but i had to upload the old file. which is version 4.7. the new 5.10.2 version was named 'fontawesome.min.css' when i downloaded it. that's uploaded too. but i still don't see the icon.

**Comment by tagliala** [comment]
Ok, I can download the file, but version is 4.7

```
/*!
 *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome
 *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
 */
```

Anyway... the website is also using the old syntax

`fa fa-brand` 4.7 => `fab fa-brand` 5.x

Please make sure you have upgraded
- stylesheet
- webfont folder
- syntax

then try again

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

**Comment by nikanjuri** [comment]
I added the kit and changed the syntax. it's working now. Thank you.

**Comment by tagliala** [comment]
You're welcome, glad you've solved 👍

**Comment by yaser-alazem** [comment]
Hello, I'm having about the same issue here with this website (http://hussam-alraie.com/)
some icons are not showing, in the console I get this error :

`https://www.hussam-alraie.com/wp-content/themes/growth/assets/css/font-awesome-5-pro.css?ver=1.0.1 net::ERR_ABORTED 404`

How can I solve this? The website built with WordPress.

**Comment by tagliala** [comment]
Hi @yaser-alazem 

I can see from the link that your wordpress website is self-hosting font awesome pro inside a theme called `growth`.

The file is actually not present on the website (error 404), so you should fix that

Please note that this is a support request. As a Font Awesome Pro customer, you can send an email to hello@fontawesome.com to get support, but the Free repo is not intended for support

Hope it helps
