### ISSUE TITLE
Icon request: vector-polygon, vector-circle 

### ISSUE THREAD

**Issue by gooeyideas** [FortAwesome/Font-Awesome#15480]
**What can it be used for?**
Currently there is are `draw-square` and `vector-square` icons. I think font awesome should continue the pattern and provide the `vector-polygon` and `vector-circle` counterparts to the  `draw-polygon` and `draw-circle` icons.

Most vector editing tools use square handles and it would be useful to have an icons that reflected this.

**Example image (optional)**
***vector-square***
![image](https://user-images.githubusercontent.com/6644447/64295169-438cdf00-cf36-11e9-84c1-90cc8d58c442.png)

***vector-polygon***
![image](https://user-images.githubusercontent.com/6644447/64295043-e6912900-cf35-11e9-8708-809a893d6984.png)

***vector-circle***
![image](https://user-images.githubusercontent.com/6644447/64295060-f6107200-cf35-11e9-9a96-c8cf9824c2f6.png)

**Icon request checklist**
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @gooeyideas,

[fa-vector-polygon](https://fontawesome.com/icons/vector-polygon) and [fa-vector-circle](https://fontawesome.com/icons/vector-circle) icons have been added in v6.0.0-BETA1.

Regards.

cc/ @tagliala
