### ISSUE TITLE
Strategy

### ISSUE THREAD

**Issue by ClaireKerr** [FortAwesome/Font-Awesome#15481]
I see someone has already requested this some time ago #9659 - This would be perfect to suit our needs to indicate sport strategy

https://github.com/FortAwesome/Font-Awesome/issues/9659

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please add a 👍 reaction to #9659.

Please also take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information on how requests work
