### ISSUE TITLE
Icon request: chevron-circle (down, right, up, and left) in regular style

### ISSUE THREAD

**Issue by khglynn** [FortAwesome/Font-Awesome#15497]
**What can it be used for?**
When a designer wants to draw more attention to an arrow than they could with a standard chevron, but add less weight to the page than a solid chevron-circle

**Example image (optional)**
Mockup: https://drive.google.com/file/d/1bZjdEzt6o70dfXwEKYJ6J1O9OeBGzjKZ/view?usp=sharing

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework of Font Awesome Free.

Demo: https://jsfiddle.net/tagliala/L17f528g/178/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Hope it helps

Closing here

**Comment by khglynn** [comment]
That's so neat!!! Thanks for sharing and for the outstanding product :D

–

*Kevin Halladay-Glynn*Product Manager, Silversheet
407.234.0248 <(407)%20234-0248>
kevinhg.com <https://www.kevinhg.com/>
