### ISSUE TITLE
Icon request: numbers icons 0,1,2,3,...,9

### ISSUE THREAD

**Issue by kraftstudio** [FortAwesome/Font-Awesome#15495]
**What can it be used for?**
Numbers icons needs for process element on the page.

**Icon request checklist**
- [ ] Ten numbers icons from 0 to 9
- [ ] The titles are "number-zero", "number-one", "number-two", ..., "number-nine"
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is probably a duplicate, but since I'm not able to find the original request I will leave this open

Please notice that this is a request for **40** new icons.

**Comment by hpvd** [comment]
+1

**Comment by hpvd** [comment]
another request for this can be found here: https://github.com/FortAwesome/Font-Awesome/issues/15527

**Comment by groovybluedog** [comment]
Having numbers is so under rated, surprised Font Awesome can be called awesome with so many icons but NO NUMBERS?!

**Comment by tagliala** [comment]
Numbers and letters will be part of FA6 (Free)

FA6 is available in alpha for Pro customers at https://fontawesome.com/download
