### ISSUE TITLE
Icon request: weather icons

### ISSUE THREAD

**Issue by webmaven** [FortAwesome/Font-Awesome#155]
Some icons for basic weather conditions would come in handy:
- [x] Sun
- [x] Moon
- [x] Cloud
- [x] Snowflake(s)
- [ ] Raindrop(s)
- [ ] Wind
- [x] Lightning (bolt)
- [ ] Sun and Cloud
- [ ] Moon and Cloud
- [ ] Cloud w. Rain
- [ ] Cloud w. Snow
- [ ] Cloud w. Lightning

There are, of course, quite a few combos beyond these basics, like 'Sun and Cloud w. Rain', but I didn't want to push my luck. ;-)

**Comment by byrock** [comment]
+1

**Comment by Hates** [comment]
+1

**Comment by abdelouahabb** [comment]
@KOTRET I guess those are in dejavu font ?

**Comment by KOTRET** [comment]
@abdelouahabb here is a screen with DejaVu Sans, i highlighted the relevant ones:
![dejavusans](https://cloud.githubusercontent.com/assets/1357504/6685744/d972111c-cc9c-11e4-901d-ba1811dda6b5.PNG)

**Comment by abdelouahabb** [comment]
@KOTRET  this is what i did :D i forked weather-fonts, and added some icons (so i can animate them using CSS), here is the repo:
https://github.com/abdelouahabb/weather-fonts

**Comment by G-Driver** [comment]
+1 Raindrop(s)
+1 Wind
+1 Sun and Cloud
+1 Moon and Cloud
+1 Cloud w. Rain
+1 Cloud w. Snow
+1 Cloud w. Lightning

**Comment by codyn329** [comment]
+1

**Comment by erikflowers** [comment]
For anyone following this who still wants weather based icons, it's evolved quite a bit since my last post here, 2 years aog.... up to 215 icons http://weathericons.io

**Comment by tagliala** [comment]
@erikflowers thanks again

**Comment by marmoj** [comment]
+1 for the raindrop!

**Comment by rdenadai** [comment]
I think @erikflowers font http://weathericons.io is the way to go to add those types of icon... I can be another request on your web site or another file to be loaded in your android app, but it has a lot of icons... i mean a LOT!!!

**Comment by tagliala** [comment]
@rdenadai you can consider a custom build: https://icomoon.io/app/#/select

**Comment by ntvsx193** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by grahamehorner** [comment]
+1

**Comment by kpingel** [comment]
:+1:

**Comment by christinekatz** [comment]
+1

**Comment by dwyer14** [comment]
+1—a basic snowflake, raindrop & wind would be awesome! Thanks for the great work.

**Comment by bumbeishvili** [comment]
+1

**Comment by shawnlunny** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. I created a lot of icons related to this sun, cloud, rain, snow, moon, wind, storm etc. If there are any problem please create an issue on the GitHub project

**Comment by toddjcrane** [comment]
+1

**Comment by Roger-Waters** [comment]
+1

**Comment by twohumans** [comment]
+1

**Comment by Souldat** [comment]
+1

**Comment by beechies** [comment]
+1

**Comment by prokki** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode emojis: #222

Weather
--------

- [🌫 U+1F32B](http://emojipedia.org/fog/)
- [❄️ U+2744](http://emojipedia.org/snowflake/)
- [💧 U+1F4A7](http://emojipedia.org/droplet/)
- [💦 U+1F4A6](http://emojipedia.org/splashing-sweat-symbol/)
- [🌀 U+1F300](http://emojipedia.org/cyclone/)
- [🌪 U+1F32A](http://emojipedia.org/cloud-with-tornado/)
- [☁️ U+2601](http://emojipedia.org/cloud/)
- [🌨 U+1F328](http://emojipedia.org/cloud-with-snow/)
- [🌧 U+1F327](http://emojipedia.org/cloud-with-rain/)
- [🌩 U+1F329](http://emojipedia.org/cloud-with-lightning/)
- [⚡ U+26A1](http://emojipedia.org/high-voltage-sign/)
- [⛈ U+26C8](http://emojipedia.org/thunder-cloud-and-rain/)
- [⛅ U+26C5](http://emojipedia.org/sun-behind-cloud/)
- [🌥 U+1F325](http://emojipedia.org/white-sun-behind-cloud/)
- [🌤 U+1F324](http://emojipedia.org/white-sun-with-small-cloud/)
- [🌦 U+1F326](http://emojipedia.org/white-sun-behind-cloud-with-rain/)
- [☀️ U+2600](http://emojipedia.org/black-sun-with-rays/)
- [🌈 U+1F308](http://emojipedia.org/rainbow/)

Anthropomorphic Celestial Objects
-----------------------------------

- [🌬 U+1F32C](http://emojipedia.org/wind-blowing-face/)
- [🌞 U+1F31E](http://emojipedia.org/sun-with-face/)
- [🌑 U+1F311](http://emojipedia.org/new-moon-symbol/)
- [🌒 U+1F312](http://emojipedia.org/waxing-crescent-moon-symbol/)
- [🌓 U+1F313](http://emojipedia.org/first-quarter-moon-symbol/)
- [🌔 U+1F314](http://emojipedia.org/waxing-gibbous-moon-symbol/)
- [🌕 U+1F315](http://emojipedia.org/full-moon-symbol/)
- [🌖 U+1F316](http://emojipedia.org/waning-gibbous-moon-symbol/)
- [🌗 U+1F317](http://emojipedia.org/last-quarter-moon-symbol/)
- [🌘 U+1F318](http://emojipedia.org/waning-crescent-moon-symbol/)
- [🌙 U+1F319](http://emojipedia.org/crescent-moon/)
- [🌚 U+1F31A](http://emojipedia.org/new-moon-with-face/)
- [🌛 U+1F31B](http://emojipedia.org/first-quarter-moon-with-face/)
- [🌝 U+1F31D](http://emojipedia.org/full-moon-with-face/)
- [🌜 U+1F31C](http://emojipedia.org/last-quarter-moon-with-face/)

Weather-Related Objects
-------------------------

- [🌂 U+1F3D6](http://emojipedia.org/closed-umbrella/)
- [☂ U+2602](http://emojipedia.org/umbrella/)
- [☔ U+2614](http://emojipedia.org/umbrella-with-rain-drops/)
- [⛱ U+26F1](http://emojipedia.org/umbrella-on-ground/)
- [☃ U+2603](http://emojipedia.org/snowman/)
- [⛄ U+26C4](http://emojipedia.org/snowman-without-snow/)
- [🌡 U+1F321](http://emojipedia.org/thermometer/)
- [🛰 U+1F6F0](http://emojipedia.org/satellite/)

Sceneries
----------

- [🌁 U+1F301](http://emojipedia.org/foggy/)
- [🌅 U+1F305](http://emojipedia.org/sunrise/)
- [🌄 U+1F304](http://emojipedia.org/sunrise-over-mountains/)
- [🌇 U+1F307](http://emojipedia.org/sunset-over-buildings/)
- [🌆 U+1F306](http://emojipedia.org/cityscape-at-dusk/)
- [🌃 U+1F303](http://emojipedia.org/night-with-stars/)
- [🌌 U+1F30C](http://emojipedia.org/milky-way/)

Non-Emoji Characters
----------------------

- 🗲 U+1F329 Lightning Mood
- ☇ U+2607 Lightning
- ☈ U+2608 Thunderstorm

**Comment by nagylzs** [comment]
+1

**Comment by webmaven** [comment]
Wow, hard to believe this issue is still going! I guess it serves a purpose if only as something that other issues can be marked as duplicates of. :smiling_imp:

**Comment by getricj** [comment]
+1 on this, https://erikflowers.github.io/weather-icons/ is now no longer actively maintained, font awesome should take go in to take ownership on this.

**Comment by BikersPost** [comment]
Yes, weather icon please. Sun, Cloud, and Rain combined in one

**Comment by freetanga** [comment]
+1 Please :)

**Comment by gabsoftware** [comment]
+1. Hope it would be available as a new pack someday!

**Comment by earthcomedy** [comment]
+1

**Comment by neoteknic** [comment]
+1

**Comment by Wingo5315** [comment]
+1
I hope that your next icon pack will be "weather icons".

**Comment by BikersPost** [comment]
![weather-icon-font-ms01preview](https://user-images.githubusercontent.com/12618841/43026209-b644b424-8c42-11e8-8e2f-9565e1aca51c.png)

**Comment by BikersPost** [comment]
+1
Cloud w/ Rain

**Comment by jnahas55** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by igor-smyrnov** [comment]
+1

**Comment by sensibleworld** [comment]
There's a 100% chance of weather icons in our latest release: https://fontawesome.com/icons?d=gallery&c=weather

**Comment by dwyer14** [comment]
`poo-storm`, dying. 😆 Thanks for sharing that, @sensibleworld!
