### ISSUE TITLE
Feature request: Animated ellipsis

### ISSUE THREAD

**Issue by ccleve** [FortAwesome/Font-Awesome#15509]
I want to be able to have "Loading..." or "Searching..." messages with an animated ellipsis, like this:

https://codepen.io/thetallweeks/pen/yybGra 

You could implement this as another kind of animation, like fa-spin or fa-pulse. Could call it fa-wipe or fa-swipe or something.

As long as you're at it, you might consider adding other kinds of animations, like fade, wipe up/down, flash, grow/shrink, what have you.

If this is all just css, you might be able to get away with adding how to do it in the documentation, without any need to add anything to the core package.

**Comment by KKS1** [comment]
Are there any updates on this request ?

**Comment by gupta-anchal** [comment]
Any updates on this?

**Comment by tagliala** [comment]
Hi!

> As long as you're at it, you might consider adding other kinds of animations, like fade, wipe up/down, flash, grow/shrink, what have you.

During the years, many other animations mentioned here have been implemented.

Ref: https://fontawesome.com/docs/web/style/animate

As you can see, we tend to implement animations that may work for most of the icons.

The animation requested in the title, ellipsis, may work for some icons, and should be implemented case by case according to the shape of the icon itself

Example: https://jsfiddle.net/tagliala/ex4hp3yn/9/

If you need more animations like this, please implement custom CSS

Closing here

**Comment by nh2** [comment]
> Example: https://jsfiddle.net/tagliala/ex4hp3yn/9/

For others having the same problem, this animation is not very good, because the house icon is never fully shown.

## Solution

I made a correct ellipsis animation here (it uses the unicode ellipsis character `…` and does not need FontAwesome):

https://stackoverflow.com/questions/13014808/is-there-any-way-to-animate-an-ellipsis-with-css-animations/75179539#75179539
