### ISSUE TITLE
Brands does not work in all.css

### ISSUE THREAD

**Issue by jeghedderchristoffer** [FortAwesome/Font-Awesome#15500]
**Describe the bug**
Brands showing as a squares, all other types of icons works as expected

**To Reproduce**
In the head: 
`<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-XxNLWSzCxOe/CFcHcAiJAZ7LarLmw3f4975gOO6QkxvULbGGNDoSOTzItGUG++Q+" crossorigin="anonymous">`

In the body: 
`<i class="fab fa-facebook-square"></i>`
`<i class="fab fa-google"></i>`

**Expected behavior**
The Facebook and Google icon should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/17568855/64519626-c32efb00-d2f4-11e9-96e7-28d1eb4fe051.png)

**Version and implementation**
Version: 5.10.2

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/2o9w0c6h/

Could you please check that there aren't third-party extensions (ad blockers) blocking those icons?

Otherwise, please provide a reproducible test case

**Comment by jeghedderchristoffer** [comment]
I will do, and otherwise open a new issue with a reproducible test case.
