### ISSUE TITLE
Icons flipping vertically

### ISSUE THREAD

**Issue by VagyokC4** [FortAwesome/Font-Awesome#15512]
Not sure why but your icons are flipping for no apparent reason.  You should fix this.

![image](https://user-images.githubusercontent.com/253250/64661030-d7a7ec00-d3f7-11e9-95a5-24c1dda7ce31.png)

Once I hover over the upside-down image, it flips back the right way.

![image](https://user-images.githubusercontent.com/253250/64661084-1047c580-d3f8-11e9-8f03-329c144ecb29.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You mean this page? https://fontawesome.com/icons/key?style=solid

**Comment by VagyokC4** [comment]
I've posted this to Microsoft Edge and it appears they have fixed the issue.

**Comment by tagliala** [comment]
👍 thanks for the heads-up!
