### ISSUE TITLE
Icon request: network-graph

### ISSUE THREAD

**Issue by peterclemenko** [FortAwesome/Font-Awesome#15519]
**What can it be used for?**
Network graphs and force directed graphs. This is a single icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Do you have any single color, small icon size suitable example?

**Comment by aethior** [comment]
Duplicate of #5944.
Check https://fontawesome.com/icons/chart-network

Regards.

cc/ @tagliala
