### ISSUE TITLE
Icon request: Equal Housing

### ISSUE THREAD

**Issue by Melisunde** [FortAwesome/Font-Awesome#15523]
**What can it be used for?**
Showing your business is an equal housing lender/offers equal housing opportunity is requested on many housing and financial websites.

**Example image (optional)**
(Something like the current icon "home-heart" with an equal sign in place of the heart would work)
![image](https://user-images.githubusercontent.com/4312550/64812073-853c0c00-d56c-11e9-8be4-077d228c1a2f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Melisunde** [comment]
This would just be the house graphic without the text for Equal Housing Lender/Opportunity. (I've had requests for just the graphic, though in probably 90% of cases one of the other two would suffice.)

**Comment by rwilsond** [comment]
There is an Official EPS file that can be used right here<br>
[(https://www.hud.gov/library/bookshelf11/hudgraphics)](url)

**Comment by tagliala** [comment]
Let's use #3574
