### ISSUE TITLE
Numbers : number-one, number-two ... number-nine

### ISSUE THREAD

**Issue by Psyster8** [FortAwesome/Font-Awesome#15527]
**What can it be used for?**
Basicaly we are using a shinydashboardplus timeline component and instead of using it as a timeline we want to use it as a step by step process (1, 2 , 3 etc)
matched icons from one to nine

**Example image (optional)**
![1](https://user-images.githubusercontent.com/55275480/64849429-a4da3f80-d613-11e9-9e6c-11f239d70cc5.jpg)

**Comment by hpvd** [comment]
+1

**Comment by groovybluedog** [comment]
Having numbers is so under rated, surprised Font Awesome can be called awesome with so many icons but NO NUMBERS?!

**Comment by tagliala** [comment]
Duplicate of #15495, sorry, missed this one
