### ISSUE TITLE
Icon request: icon-code-alt

### ISSUE THREAD

**Issue by johnsheehan** [FortAwesome/Font-Awesome#1552]
The current icon-code has a very liberal definition of code and should really be called icon-markup. I would like to see icon-code-alt be a pair of braces `{ }`. Using actual text braces doesn't look quite right next to the other icons.

**Comment by Saluev** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by helenst** [comment]
:+1: I'm working on a system based around software projects / code repositories which are very rarely markup-related. Something like this would be far more suitable than the icon depicting markup.
![braces](https://cloud.githubusercontent.com/assets/217966/10133310/3416d6b8-65d4-11e5-9681-39db9cae8ef4.png)

**Comment by tagliala** [comment]
hmmm #1797 is a duplicate of this one, with a better title and more +1s

I will close this one, I will take care to add your +1s on #1797
