### ISSUE TITLE
Webfonts not loading on website using $fa-font-path

### ISSUE THREAD

**Issue by venuscrush** [FortAwesome/Font-Awesome#15534]
Trying to load the fontawesome webfonts with no luck. `@import` rules work except the `$fa-font-path`. The file I'm loading all the fontawesome modules in is a css file (everything is set up to handle npm/gulp/etc.

Here's the code in my `fontawesome.css` file (I'm not using Sass or Less):
```
$fa-font-path: "~@fortawesome/fontawesome-free/webfonts";

@import "../../../node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css";
@import "../../../node_modules/@fortawesome/fontawesome-free/css/solid.min.css";
```

`$fa-font-path: "~@fortawesome/fontawesome-free/webfonts";` is the only part in the above code not loading on my website. What am I doing wrong?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but I think I do not have enough details to help here

> (I'm not using Sass or Less):

`$fa-font-path` requires a sass implementation to work, it will not have effect on plain CSS

> `@import "../../../node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css";`

It looks like you are importing the css from a node_modules folder, but I don't know if you are using an asset bundler which understands that Font Awesome is referring to some font files and it is copying them to your application

Please provide more details, we have a bug report template: [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

PS: if you are using gulp, this may help: https://stackoverflow.com/questions/37057531/use-gulp-to-copy-all-bower-package-font-files-to-build-directory
