### ISSUE TITLE
Icon request: pen-slash

### ISSUE THREAD

**Issue by ramsesmoreno** [FortAwesome/Font-Awesome#15531]
**What can it be used for?**
To determine an element is not editable when other items in one list shows the normal edit, pen and pencil.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/30059695/64900558-4a62d280-d657-11e9-9a0e-480e853b7a56.png)
.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/184/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by IoanaAlexandru** [comment]
How can I get an svg file from the HTML code above?

**Comment by tagliala** [comment]
Pencil slash: #4906
Edit slash: #16702 

@IoanaAlexandru 

Sorry for the very late reply.

Unfortunately we do not have a way to convert the above HTML code to a single SVG

**Comment by aethior** [comment]
Hi @ramsesmoreno,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/pen-slash

Regards.

cc/ @tagliala

**Comment by ramsesmoreno** [comment]
Great!
