### ISSUE TITLE
Icon Change Request: fa-user-nurse

### ISSUE THREAD

**Issue by kayla-glick** [FortAwesome/Font-Awesome#15530]
I expect that I will get some backlash for this, but I feel that this would be a great change to this icon and I hope you will hear me out regardless of personal views.

**Current Icons**
![image](https://user-images.githubusercontent.com/12898988/64874620-6a73a100-d619-11e9-992b-8983a7c641d0.png)

**Issues**
The current `fa-user-nurse` icon looks like it was modeled to be a female nurse because of the hair (or hat if that's what it was intended to be) and the added curves around the chest area. By contrast, the current `fa-user-md` icon looks gender neutral, but when comparing it to the `fa-user-nurse` icon, it looks a lot more like a male doctor and female nurse (see screenshot)

![image](https://user-images.githubusercontent.com/12898988/64874931-fdacd680-d619-11e9-9ea2-401d0a1aed72.png)

Am I saying the `fa-user-md` icon looks inherently male? No. But the nurse icon shouldn't look inherently female either. Together, these two icons reinforce the idea that doctors and men and nurses are women. Regardless of your personal views, I hope that you will agree with me that both stereotypes are bad and we can easily make it better.

**My Proposal**
It doesn't take much to make a big improvement to the `fa-user-nurse` icon. I propose that removing the hair (or back of a hat?) and straightening the chest to match the `fa-user-md` icon makes the icon feel much more gender neutral.

**Bad MS Paint Edit of `fa-user-nurse`**
![Capture](https://user-images.githubusercontent.com/12898988/64881530-fd680780-d628-11e9-9ac5-35006e9cd83b.PNG)

**`fa-user-md` for comparison**
![image](https://user-images.githubusercontent.com/12898988/64881734-8b43f280-d629-11e9-92e3-98442e896815.png)

* **Solid Variant**: Remove hair and slightly straighten bottom of chest to less-resemble bust
* **Regular Variant**: Remove hair, straighten sides of chest, slightly reduce v-neck to less-resemble bust
* **Light Variant**: Remove hair, straighten sides of chest, slightly reduce v-neck to less-resemble bust
* **Duotone Variant**: Remove hair and slightly straighten bottom of chest to less-resemble bust, plus fill in face to match `fa-user-md`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for bringing this to our attention.

As you can see in the docs, [user-nurse](https://fontawesome.com/icons/user-nurse?style=solid) is a sponsored icon

Anyway, I agree that a gender neutral version of a nurse should be part of the set

**Comment by sensibleworld** [comment]
Hi @kayla-glick! You're absolutely right, and thanks for bringing this to our attention. There's another [open issue here](https://github.com/FortAwesome/Font-Awesome/issues/14691), but I'm going to try to get an update into our next release.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-nurse?style=solid
