### ISSUE TITLE
Icon request: building-cog

### ISSUE THREAD

**Issue by hoeneste** [FortAwesome/Font-Awesome#15539]
**What can it be used for?**
If you have an application in which you have to manage your company, this icon can be used.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/3438198/64959973-9cdc0300-d892-11e9-968b-2e3c4a7629bd.png)

**Icon request checklist**
- [x]  single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/186/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by hoeneste** [comment]
Hi, just wanted to ask if you could already add some new icon here. Because we have the same problem here as with the add company. We only can add a single icon as class and no additional transformations etc. Is there a chance to get the icon included in the lib soon?
