### ISSUE TITLE
Icon request: document-scan

### ISSUE THREAD

**Issue by Dilakshi** [FortAwesome/Font-Awesome#15537]
For document scanning

[image 1](https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fusability-test%2F100%2Fjan_yulck-26-512.png&imgrefurl=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F975292%2Fcamera_capture_capturing_document_scan_scanning_icon&docid=q0StjDY7sv2DDM&tbnid=_0kJVUEk3ZtroM%3A&vet=10ahUKEwiwn6X_ztTkAhVGfd4KHSzJDkwQMwhdKAEwAQ..i&w=512&h=512&safe=active&bih=639&biw=1342&q=document%20scan%20icon&ved=0ahUKEwiwn6X_ztTkAhVGfd4KHSzJDkwQMwhdKAEwAQ&iact=mrc&uact=8)
[Image 2](https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn4.iconfinder.com%2Fdata%2Ficons%2Foffice-material-outline%2F100%2Fscaner-512.png&imgrefurl=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F2043085%2Fdoc_document_scan_scaner_scanner_stapler_icon&docid=ybjQdIqqJqe0wM&tbnid=lfKKHk6hhJ7U0M%3A&vet=10ahUKEwiwn6X_ztTkAhVGfd4KHSzJDkwQMwhoKAgwCA..i&w=512&h=512&safe=active&bih=639&biw=1342&q=document%20scan%20icon&ved=0ahUKEwiwn6X_ztTkAhVGfd4KHSzJDkwQMwhoKAgwCA&iact=mrc&uact=8)
[Image 3](https://www.freepik.com/free-icon/document-scanning_785631.htm)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by lucasmantoani** [comment]
This one would be helpful !

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

A scanner icon (second example) is available in Font Awesome Pro: https://fontawesome.com/icons/scanner-image?style=solid

The first example is available with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/289/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

If you have something different in mind, please fix the title and provide just a single color example, then I will reopen this
