### ISSUE TITLE
Icon Request: web-form

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#15545]
Use case: represent web form library

![image](https://user-images.githubusercontent.com/17099726/64990959-bcb8fa00-d885-11e9-84b6-130767894d00.png)

**Comment by mheidebrecht** [comment]
Actually, I need icons for both web pages that are forms and another for a more generic, non-form web page. Thx

**Comment by tagliala** [comment]
Oh sorry, this is a duplicate of #780. Let's use that one, has more +1s
