### ISSUE TITLE
Icon request: add-company

### ISSUE THREAD

**Issue by hoeneste** [FortAwesome/Font-Awesome#15540]
**What can it be used for?**
You can add a new company in an app. It is a ready to use combined icon.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/3438198/64960376-78345b00-d893-11e9-8c34-1c196b4fa5f5.png)

**Icon request checklist**
- [x] Single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/188/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by hoeneste** [comment]
Hi! Thanks for your feedback! I know that there is the option to do that this way with masking etc. But we have a dynamic angular MDB app which does not allow the adding of snippets we only can add a single class there. Or if you have a good solution through which we can use that please let me know.

**Comment by hoeneste** [comment]
Hi! Are there any news on that topic. Isn't it possible to just add the icon as one new icon? Because the point is we can only add single class and no combination of classes.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
