### ISSUE TITLE
Icon request: gif

### ISSUE THREAD

**Issue by jsonjuri** [FortAwesome/Font-Awesome#15551]
**What can it be used for?**
Icon for gif images

**Example image**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/11409905/65005483-8e452880-d932-11e9-9185-4ae95a511243.png)

![image](https://user-images.githubusercontent.com/11409905/65005489-956c3680-d932-11e9-9077-c2cd59c92e4e.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by lofcz** [comment]
I second this request 
Ship this 🎉

**Comment by forresthopkinsa** [comment]
[Here's](https://material.io/resources/icons/?search=gif&icon=gif&style=baseline) a good reference for a gif icon

**Comment by digiiitalmb** [comment]
I second this request too

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
