### ISSUE TITLE
Don't show any icons on Icons page https://fontawesome.com/icons?d=gallery in Russian Federation

### ISSUE THREAD

**Issue by IlyaIndigo** [FortAwesome/Font-Awesome#15555]
Don't show any icons on Icons page in Russian Federation.
[https://fontawesome.com/icons?d=gallery](https://fontawesome.com/icons?d=gallery)
![1](https://user-images.githubusercontent.com/2612812/65024938-6b207600-d93e-11e9-8132-25dabac011d6.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate from Italy. Maybe this depends on region/country

Where are you connecting from?

**Comment by IlyaIndigo** [comment]
Thank you! :-)
Yes, it's Russian Federation. :-(

**Comment by tagliala** [comment]
Thanks 
@robmadole any chance to check the website from Russia?

**Comment by robmadole** [comment]
Sorry, but we don't have a way to check from Russia. :(

**Comment by IlyaIndigo** [comment]
The problem was solved by itself.
Now it is showing normally.
