### ISSUE TITLE
Icon request: approximate / estimate

### ISSUE THREAD

**Issue by gmw-web** [FortAwesome/Font-Awesome#15557]
It would be nice to have an icon that depicts an estimate or approximate measure.

An idea would be to have an icon comparable to the 'asymp' html entity:
# &asymp;

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/tilde?style=solid fit your needs?

**Comment by gmw-web** [comment]
> Does https://fontawesome.com/icons/tilde?style=solid fit your needs?

_sorry for the late reply_
Yeah, it does actually. Thanks!
