### ISSUE TITLE
Icon request: add-user

### ISSUE THREAD

**Issue by hoeneste** [FortAwesome/Font-Awesome#15556]
**What can it be used for?**
There is a user plus icon i know but i assume that this is meant to be a special user with enhanced rights. I would like to have an add user action icon which can be used to add a new user which is an action that could be used in many applications with user management.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/3438198/65027330-74a7df00-d93a-11e9-945d-6651665fc818.png)

**Icon request checklist**
- [x] This is a single icon 
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is already available: https://fontawesome.com/icons/user-plus?style=solid

**Comment by hoeneste** [comment]
Hi yes as i wrote there is an icon user-plus already but i thought this is to represent a user with more rights for instance "expert user" But i think to have that in the same style for all add new icons the + should be on another position as the cog also is. Correct me if i am wrong but that was my interpretation here.
