### ISSUE TITLE
Icon request: pet-ban

### ISSUE THREAD

**Issue by 2theplace** [FortAwesome/Font-Awesome#15553]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Could you imagine to offer a banning pet icon as your smoking-ban one ?

**Example image (optional)**
Insert the example image here if necessary.
the dog icon with a built-in slash 

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/191/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by 2theplace** [comment]
Hi there,

I know Fontawesome has capability for banning icons. 
But in my case i,e, with such product Elementor Pro and using icons list widget we have to add an icon, html code is not accepted.

That's the reason of myproposal.

Thks 

L

**Comment by ninjaval** [comment]
I would like this too, because I am having the same issue where a website builder relies on one icon name in order to work. I've seen this request at least twice. Please consider adding it.
