### ISSUE TITLE
dog icon issue

### ISSUE THREAD

**Issue by macsupport** [FortAwesome/Font-Awesome#15560]
Ok, this is a very minor issue but since I am a Veterinarian and I use the icon,  I need to mention it.   The location of the eye is way too low for any breed of dog I've ever seen. It looks like the dog has eye's on its cheek! A bit higher to at least where the bridge of the nose meets the forehead would be good. . 😉

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this bug report.

Sometime we take compromises to make the icon look good at small sizes, so that could explain why the eye is a little bit shifted down, anyway let's ask @sensibleworld !

**Comment by sensibleworld** [comment]
Thanks for bringing this to our attention @macsupport! We have a limited amount of space to work with at 16px, but I've gone ahead and shifted the eyes up a bit in all of the dog icons. We'll get that fixed in the next release.

**Comment by sensibleworld** [comment]
The dogs can now see a bit easier: https://fontawesome.com/icons/dog?style=solid

**Comment by armplinker** [comment]
A clear case of the tail wagging the Font Awesome dog.
