### ISSUE TITLE
Upload icon taller than others

### ISSUE THREAD

**Issue by brettp** [FortAwesome/Font-Awesome#15561]
**Describe the bug**
As requested in https://github.com/FortAwesome/Font-Awesome/issues/1281#issuecomment-497233044, I am reporting that the upload icon's height breaks the 16px grid system.

**To Reproduce**
https://jsfiddle.net/zen9pq5w/1/

**Expected behavior**
Icons should be the same size so they look correct when lined up horizontally.

**Version and implementation**
Version: 5.10.2
Browser and version: Chrome

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community, thanks for bringing this to our attention, and sorry for the very late reply.

I'm not sure that this icon breaks the grid but let's check: @sensibleworld could you please check that `icon-upload` (and `download` respect the grid?)

**Comment by sensibleworld** [comment]
I've double-checked and the icons mentioned all snap correctly to our grid. In this case, it looks like the upload/download icons are all 16px tall, whereas the home and camera are actually 14px. We do our best to optically align proportions of icons, but I do agree that the home icon in this case is a bit too short optically. Unfortunately, it's one of our most used icons so we can't make an overall design change to it without a breaking change. We DO however have a number of alternates, including `home-alt` which could work for your use case.
