### ISSUE TITLE
Icon Request: Azure Devops

### ISSUE THREAD

**Issue by louagej** [FortAwesome/Font-Awesome#15566]
What can it be used for?
Azure DevOps pointer

Example image: [Azure Devops](https://aidanfinn.com/wp-content/uploads/2019/08/AzureDevOps.png)

Icon request checklist
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by hebbet** [comment]
duplicate of #14058

**Comment by tagliala** [comment]
@hebbet thanks
