### ISSUE TITLE
Missing 'black-tie' icon

### ISSUE THREAD

**Issue by AndreiBehel** [FortAwesome/Font-Awesome#15575]
**Describe the bug**
Official site says that 'black-tie' icon is available for free use, but in real it can not be found in free-solid-svg-icons directory.

**Expected behavior**
The icon should available for use

**Screenshots**
![image](https://user-images.githubusercontent.com/16404722/65311568-470ca100-db99-11e9-9c46-f4c416c6bf98.png)
On github:
![image](https://user-images.githubusercontent.com/16404722/65311897-1842fa80-db9a-11e9-9260-0d20d61e017f.png)

**Version and implementation**
@fortawesome/free-solid-svg-icons": "^5.10.2",
@fortawesome/react-fontawesome": "^0.1.4"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[black-tie](https://fontawesome.com/icons/black-tie) is actually a brand and it is available in Brand icons: https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/black-tie.svg

https://blacktie.io/

Hope it helps

Closing here
