### ISSUE TITLE
Icon Request: icon-markdown

### ISSUE THREAD

**Issue by cloose** [FortAwesome/Font-Awesome#1557]
I need a markdown icon for my editor project. It would be great if you could add this to font awesome.

Use cases:
- Identify a text input area as markdown capable
- As icon for menu entry to select the syntax code highlighting

One idea would be to base the icon on the [dcurtis/markdown-mark](https://github.com/dcurtis/markdown-mark) which uses the license Creative Commons CC0 Universal Public Domain Dedication.

![32x20](https://f.cloud.github.com/assets/603132/786816/797837e0-eac7-11e2-8642-817c93128ae0.png)

Thank you!

**Comment by internalfx** [comment]
+1

**Comment by makcyd** [comment]
+1

**Comment by alchemydigital** [comment]
+1

**Comment by lukejanicke** [comment]
+1

**Comment by divad** [comment]
+1

**Comment by rubenprins** [comment]
+1

**Comment by KissLick** [comment]
+2

**Comment by batisteo** [comment]
+1

**Comment by mdaniels5757** [comment]
+1

**Comment by hernandev** [comment]
+1

**Comment by vinicius73** [comment]
+1

**Comment by vluzrmos** [comment]
:+1:

**Comment by PLJNS** [comment]
:+1:

**Comment by wI2L** [comment]
:+1:

**Comment by WispProxy** [comment]
+1

**Comment by TylerTemp** [comment]
+1

**Comment by tsigo** [comment]
:+1: Yes please!

**Comment by kevinmccartney** [comment]
:+1:

**Comment by vimxts** [comment]
+1

**Comment by foodaka** [comment]
+1

**Comment by mlt** [comment]
:+1:

**Comment by peerpressure** [comment]
+1

**Comment by benpate** [comment]
+1

**Comment by TJohnson93** [comment]
+1

**Comment by tillkruss** [comment]
+1

**Comment by tchret** [comment]
+1

**Comment by bushev** [comment]
+1

**Comment by tnotm** [comment]
+1

**Comment by nIQnutn** [comment]
+1

**Comment by blambeau** [comment]
+1

**Comment by alanchavezgar** [comment]
+1

**Comment by cnelissen** [comment]
+1

**Comment by tiberiucorbu** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
> The issue is closed but where is the icon ? is it dropped or added ?

Where did you see that? The issue is still open.

**Comment by spikying** [comment]
+1

**Comment by peerpressure** [comment]
> The issue is closed but where is the icon ? is it dropped or added ?

> Where did you see that? The issue is still open.

OP's handle is "cloose" lol.

**Comment by willdady** [comment]
+1

**Comment by martinkearn** [comment]
+1

**Comment by slavidodo** [comment]
+1

**Comment by duyetdev** [comment]
+1

**Comment by andrewgioia** [comment]
+1

**Comment by DRFrenette** [comment]
+1

**Comment by Guichaguri** [comment]
+1

**Comment by troygnichols** [comment]
+1

**Comment by roadmanfong** [comment]
+1

**Comment by Razer6** [comment]
+1

**Comment by pmphillips** [comment]
+1 **dooooo it**. Oh the irony, Markdown supported in _these_ comments.

**Comment by thegreatrazz** [comment]
+1

**Comment by ourcore** [comment]
+1

**Comment by ewankirk** [comment]
+1 from me too.  Would be very usefull

**Comment by filerun** [comment]
+1

**Comment by valtlfelipe** [comment]
+1

**Comment by KojiIzawa** [comment]
+1

**Comment by oarrabi** [comment]
+1

**Comment by dextermb** [comment]
👍

**Comment by sinkcup** [comment]
@JaredCubilla devicons is good, I am using it at http://localhost:3000/c/242/d/asc=0+sort=ni+view=list/

but it's size is not same as FortAwesome ...

![2017-01-10 13-58-47](https://cloud.githubusercontent.com/assets/4971414/21799862/00605f98-d756-11e6-8816-1fe77deea437.png)

**Comment by sinkcup** [comment]
@JaredCubilla devicons is good, I am using it at https://maya.io/c/280/d/asc=0+sort=nf+view=list/

but it's size is not same as FortAwesome ...

![2017-01-10 13-58-47](https://cloud.githubusercontent.com/assets/4971414/21799862/00605f98-d756-11e6-8816-1fe77deea437.png)

**Comment by mrkkrp** [comment]
+1

So everyone is upvoting this, but apprarently it doesn't work. No markdown icon since 2013 :-(

I'm using Octicons instead **mostly because that set of icons has markdown sybmol**. The symbol alone adds much more value than a lot of stuff Font Awesome adds. Pwwwt...

**Comment by pmphillips** [comment]
**I will donate $100 USD** to the FontAwesome people, or a charity of their choice if a Markdown icon is added by July 31, 2017. How many +1's does that count for?

**Comment by cnelissen** [comment]
@pmphillips Check out http://five.fontawesome.io, it says they are going to be shipping in May and is supposed to have a thousand or so icons, hopefully one of which will be Markdown. If you are going to throw $100 bucks at anything you might as well get the new version...

**Comment by rogersachan** [comment]
+1

**Comment by CharlesLiuyx** [comment]
+1

**Comment by Tetsumaki** [comment]
And 👍

**Comment by matthaliski** [comment]
+1

**Comment by jcano** [comment]
I'm guessing this is not going to happen until 5, but still I'll add my :+1: here

**Comment by r0the** [comment]
+1

**Comment by r0the** [comment]
+1

**Comment by Taminoful** [comment]
+1

**Comment by MrFevs** [comment]
+1

**Comment by maxxcrawford** [comment]
+ 1

**Comment by jrmessias** [comment]
+1

**Comment by kknopper** [comment]
+1

**Comment by blizzardengle** [comment]
+1

**Comment by pratik-sinha** [comment]
+1

**Comment by Diaoliu** [comment]
+1
