### ISSUE TITLE
Icon request: zhihu

### ISSUE THREAD

**Issue by L1cardo** [FortAwesome/Font-Awesome#15584]
**What can it be used for?**
This is a new icon for `zhihu`, except for `fab fa-zhihu`.
The origin zhihu icon is two Chinese character and it may be to wide in some situation. We need a new zhihu icon. 
#4439
https://github.com/FortAwesome/Font-Awesome/issues/4439#issuecomment-209439477

**Example image (optional)**
![截屏2019-09-22下午3 54 41](https://user-images.githubusercontent.com/33802186/65384184-9695cd00-dd51-11e9-9f27-ffed0aea3b22.png)

**Icon request checklist**
- [single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [yes] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [yes] I have included at least one example image if it could be helpful (optional)
- [yes] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by YinglaiYang** [comment]
I support this. As a further reference, here is the favicon:
![Bildschirmfoto 2019-10-22 um 21 58 29](https://user-images.githubusercontent.com/768468/67326664-24163980-f517-11e9-91fa-11f535b02918.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community, thanks for reporting this and sorry for the late reply.

I can definitely see the single-character icon in the favicon, but are there any official brand guidelines for Zhihu?

**Comment by L1cardo** [comment]
I do not know if this is ok? https://www.zhihu.com/terms#sec-licence
I did not find any other stuff related to brand guidelines

**Comment by YinglaiYang** [comment]
Hi @tagliala, 

unfortunately it looks like Zhihu (like a lot of other Chinese companies) does not have a comprehensive brand guideline.

Do you need it for the rights to the icon or for the guideline to the look?

About the rights, here is a translated snippet from the source added by @L1cardo:
<img width="1278" alt="Bildschirmfoto 2020-02-16 um 15 11 28" src="https://user-images.githubusercontent.com/768468/74606225-f14c0e80-50ce-11ea-931e-954c5eb2280e.png">

About the looks, I think the only other indicator I can give would be the results on the Chinese website iconfont.cn:
- [https://www.iconfont.cn/search/index?q=知乎]() 
- [https://www.iconfont.cn/search/index?q=zhihu]()

<img width="1273" alt="Bildschirmfoto 2020-02-16 um 15 19 39" src="https://user-images.githubusercontent.com/768468/74606315-c7471c00-50cf-11ea-986c-44ed054ac821.png">


The majority of the icons is using the single character representation with only the "知“. But as far as I can see, there doesn't seem to be any rule that tells whether e.g. the background needs to be filled or what color/shape the background should have if present.

Hope it helps?
