### ISSUE TITLE
embedding all.js in <head>

### ISSUE THREAD

**Issue by rubaboo** [FortAwesome/Font-Awesome#15588]
**Describe the bug**
```
function coerce(val) {
…
    // For example <script data-search-pseudo-elements src="..."></script>
…
```
I need to insert the entire text of `all.js` inside `<head><script>…</script></head>`. But when I do that, the comment line quoted above is interpreted as the end of the script. Not sure if it's a bug of Firefox 69 or not, but it would be great if the closing `</script>` tag was removed from that comment. I don't think that would make the comment less valid.

**Expected behavior**
Should be able to embed the script directly in `<head>`, not only load via <script src=…>

**Version and implementation**
Version: 5.11.1
Browser and version: Firefox 69

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry for the late reply

I think that this should be managed by your application, since it is a pretty special use case

@robmadole any thoughts?

**Comment by robmadole** [comment]
@rubaboo this is a very special use case. I would recommend that you edit the contents yourself for your specific usage.
