### ISSUE TITLE
slow response from fontawesome.com

### ISSUE THREAD

**Issue by zubairYar** [FortAwesome/Font-Awesome#15582]
this is zubar yar i am using font awsome from such a long time and it really helped me out while i am working on projects but these days i am facing a problem that your webiste is really made me board because its too slow whenever i search an icon it takes about 20 seconds to find. i hope there will be a good way to help me.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've also noticed slow response time here in Italy for a couple of days

![image](https://user-images.githubusercontent.com/556268/65374020-50733780-dc85-11e9-915b-5778d4b6dc93.png)
(chrome incoginito window)

Maybe it is a regional issue, where are you from?

**Comment by zubairYar** [comment]
I am from Afghanistan

**Comment by tagliala** [comment]
@robmadole any chance to check site speed?

**Comment by zubairYar** [comment]
there you go

**Comment by lgirma** [comment]
I second that. That particularly happens when looking for an icon.

**Comment by robmadole** [comment]
Hmm, can anyone else send a network tab screenshot like @tagliala did?
