### ISSUE TITLE
Website: two scanner icons are overlaid

### ISSUE THREAD

**Issue by halfninja** [FortAwesome/Font-Awesome#15586]
When searching for scanner on the website there seem to be a flatbed scanner and a barcode scanner overlaid in the same slot.

![Screenshot_20190922-172037~2](https://user-images.githubusercontent.com/72052/65391129-84219080-dd5d-11e9-9663-2dd5433667f1.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm, there is actually a bug in FA Pro CSS, with `scanner-image` and `scanner` icons sharing the same unicode point `\f488`

Demo: https://jsfiddle.net/tagliala/rLw7bxt4/3/

Let's assign both @robmadole @sensibleworld 

@robmadole any chance to add a sanity check to prevent this in the future?

**Comment by sensibleworld** [comment]
Thanks for the report! We're getting this fixed up in 5.11.2 shortly, and will definitely be adding a test for this.
