### ISSUE TITLE
Broken Link on website changelog

### ISSUE THREAD

**Issue by williamhatcher** [FortAwesome/Font-Awesome#15583]
On https://fontawesome.com/changelog/latest for version 5.11 there is a broken link.
[brands](https://fontawesome.com/icons?d=gallery&c=brands) links to "Found Nothing We Have" because it is trying to link to the brands _category_ (`&c=`) even though brands is a _style_ (`&s=`).

Should be an easy fix, just change 
`https://fontawesome.com/icons?d=gallery&c=brands`
to
`https://fontawesome.com/icons?d=gallery&s=brands`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @talbs

**Comment by williamhatcher** [comment]
No problem! @talbs enjoy fixing it!

**Comment by talbs** [comment]
Sorry, gang. Re-opening this after GitHub auto-closed when merging the bug fix in. I'll close this for realsies when it's live and we can confirm.

**Comment by talbs** [comment]
This should be all fixed up on the live site. Thanks again for bringing this to our attention, @williamhatcher. Shout if you see anything else fishy around the site. 😄
