### ISSUE TITLE
Icon request: Number with circle around it.

### ISSUE THREAD

**Issue by njcbone** [FortAwesome/Font-Awesome#15591]
**What can it be used for?**
Numbers within a circle can be used in a number of different situations. Especially for Indicating steps.

**Example image (optional)**
![number2_circle](https://user-images.githubusercontent.com/6045708/65444010-2b093980-ddfd-11e9-910c-cc725c740456.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (0 - 9)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at leas
t one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by halfninja** [comment]
I think you can do this yourself with icon stacking in tandem with whatever number or text you like, as per this blog post

http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by njcbone** [comment]
> I think you can do this yourself with icon stacking in tandem with whatever number or text you like, as per this blog post
> 
> http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

This worked, thanks!!

**Comment by hpvd** [comment]
to make it even nicer, circle icon plus numbers from this request:
https://github.com/FortAwesome/Font-Awesome/issues/15527

please vote for it ;-)

**Comment by aethior** [comment]
Hi @njcbone,

Numbers icons with circle have been added in v6.0.0-BETA1.
Check [numbers icons](https://fontawesome.com/icons/categories/numbers) category.

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please. :)

**Comment by tagliala** [comment]
Numbers with circles are limited to FA Pro

FA Free users, **in a web application**, can create the requested icons by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/51/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
