### ISSUE TITLE
balance-scale-right and balance-scale-left not rendering in version 5.5.0

### ISSUE THREAD

**Issue by justlikeUNIBLAB** [FortAwesome/Font-Awesome#15597]
**Describe the bug**
"fas fa-balance-scale-right isn't rendering for me.
Same for -left
however "fas fa-balance-scale" DOES render for me.

Is there a typo in the code for this icon, or a bug?

**Version and implementation**
Version: 5.5.0
Browser and version: Chrome77  on Windows 10

thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this bug report.

I can confirm the issue, but it is a documentation issue.

`balance-scale-left` and `balance-scale-right` have been added to the FA Free set in version 5.9.0, so please upgrade Font Awesome. At the moment the latest version available is 5.11.2

SVG demo: https://jsfiddle.net/tagliala/raz41dLh/2
CSS demo: https://jsfiddle.net/tagliala/1nyx6efz/1/

@talbs @sensibleworld any chance to fix the `updated` tag from 5.0.13 to 5.9.0?

https://fontawesome.com/icons/balance-scale-left?style=solid
https://fontawesome.com/icons/balance-scale-right?style=solid

**Comment by sensibleworld** [comment]
@tagliala Yup! We'll get this fixed up.
