### ISSUE TITLE
Icon request: icon-parking

### ISSUE THREAD

**Issue by rudi911** [FortAwesome/Font-Awesome#1559]
I would love the famous P which (in Europe) stands for a car park. I'm using font-awesome to point out positions on a map, and while I could use a car icon, the P is just so much more obvious.

![imgres](https://f.cloud.github.com/assets/2655153/787409/3283b668-ead9-11e2-90d7-c64b07d2de63.jpeg)

**Comment by mhadaily** [comment]
+1

**Comment by designiq** [comment]
+1

**Comment by Alticaro** [comment]
+1

**Comment by karmen1087** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by wrey75** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by jodibean** [comment]
+1

**Comment by luisamor** [comment]
+1

**Comment by moisesflorenciano** [comment]
+1

**Comment by IgorDmitriev** [comment]
+1

**Comment by jibe84** [comment]
+1

**Comment by JeroenKnockaert** [comment]
+1

**Comment by nicho90** [comment]
+1

**Comment by NichyXD** [comment]
+1

**Comment by Atez01** [comment]
+1

**Comment by wellseee** [comment]
+1

**Comment by Giplo** [comment]
+1

**Comment by ArtworkAD** [comment]
2 years later :+1:

**Comment by Samoht-fr** [comment]
+1

**Comment by Arnau-ads** [comment]
+1

**Comment by schrealex** [comment]
+1

**Comment by deefees** [comment]
+1

**Comment by SirDarquan** [comment]
+1

**Comment by maxthev** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by mbosek** [comment]
+1

**Comment by tvirelli** [comment]
Here is a solution using icon stacking and fonts:
http://jsfiddle.net/wdozmays/1/

**Comment by Marchrius** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by Marc-pi** [comment]
+1

**Comment by landonreed** [comment]
+1

**Comment by herman-rogers** [comment]
+1

**Comment by eithe** [comment]
+1

**Comment by edumucelli** [comment]
+1

**Comment by aamirchaudhary** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by Doch70** [comment]
+1

**Comment by burgons** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by tkisme** [comment]
+1

**Comment by Chilled** [comment]
+1

**Comment by lovePizza** [comment]
+1

**Comment by hrpc** [comment]
+1

**Comment by hjansen** [comment]
+1

**Comment by Rafnuss** [comment]
+1

**Comment by corvine88** [comment]
Hello!
I would use this icon for some website, im doing two website of B&B, and this will be perfect for the area of the services offered or available.

I think can be really useful for this kind of website

Thankyou

**Comment by BirkMd** [comment]
3 years later ...

**Comment by peetcamron** [comment]
+1

**Comment by JuCyFrUiT** [comment]
+1

**Comment by peterppm** [comment]
+ 1

**Comment by leiyan** [comment]
+1

**Comment by Crissov** [comment]
🅿️ [U+1F17F](http://emojipedia.org/negative-squared-latin-capital-letter-p/) Unicode character #222

**Comment by evabat** [comment]
+1

**Comment by alxhotel** [comment]
+1

**Comment by octaviohelpling** [comment]
+1

**Comment by tavioto** [comment]
+1

**Comment by mpiontek** [comment]
+1

**Comment by lano-vargas** [comment]
+1

**Comment by chanthafef** [comment]
+1

**Comment by djzk** [comment]
+1

**Comment by zuruckzugehen** [comment]
+1
And I'd suggest, following the accessibility icons, to include an adapted parking also
![parking-for-disabled-persons-sign_318-51215](https://user-images.githubusercontent.com/30662192/28880501-88a3bfa4-77a5-11e7-848d-a30ad5818671.jpg)

**Comment by You85** [comment]
+1

**Comment by fad115** [comment]
+1

**Comment by WolfgangFahl** [comment]
+1

**Comment by mylen** [comment]
+1

**Comment by sipox11** [comment]
+1

**Comment by Optimaximal** [comment]
+1

**Comment by karthiknamburu** [comment]
+1

**Comment by csi00153** [comment]
+1

**Comment by acvmultimedia** [comment]
+1

**Comment by studioavanti** [comment]
+1000!
Please consider adding this icon, it's unavoidable to signal car park here in France, and in many other countries i guess. 
The design is quite simple: see attached. 
![aiga-parking1](https://user-images.githubusercontent.com/8690161/38098756-27c18c08-3379-11e8-92a5-110622335f80.png)
Thanks!

**Comment by lano-vargas** [comment]
@tagliala How many more +1 is it required for FortAwesome to realise it about time to get this out there this has been going on since 2013 it's ridiculous!

**Comment by peterppm** [comment]
They seem to think these requests are just a joke:
'Found Nothing We Have
Sorry, we couldn't find any icons related to "parking".'
Apparently we can have Spock and Lizard hand signs from the Big Bang game, but nothing of practical use to people.
Does anyone from Font Awesome actually acknowledge or appreciate the very real need we are all expressing?

**Comment by herman-rogers** [comment]
Man I’ve been through a lot of projects since I’ve +1 this. That app could have seriously used this icon but alas that was years ago now. Interesting to come back every now and then and see it’s still not in. Become a bit of a joke now.

**Comment by peterppm** [comment]
Hi Mike,
Thank you for your prompt reply.
I really do appreciate the work you all do and sincerely value your products.

However, it does baffle me, and I would love to know the logic behind, the decision that prioritised the Rock Paper Scissors Lizard Spock icons over the ones we need for everyday use, such as parking.

It might be a great TV programme but if we invest our time, money and efforts into building your icons into our websites, I think it would really help to give us the ones our clients ask for.

**Comment by peterppm** [comment]
Thanks Mike,
I shall take a look but it might be beyond me - that's why I am a big fan of Font Awesome.

No worries, I am not in a bind,  and I look forward to your new icons.
Best wishes, 
Peter

**Comment by paddelboot** [comment]
I just searched through the 1000+ icons of FA and found out there's no "Parking" icon. Then I realized it has been requested multiple times since 2013. ?!? Implementing it would probably take 50% of the time it took @mlwilkerson to write all these answers.

**Comment by bumrufus** [comment]
just use this: https://fontawesome.com/icons/product-hunt?style=brands

**Comment by sensibleworld** [comment]
No need to circle the block any longer, we found your spot: https://fontawesome.com/icons/parking?style=solid
