### ISSUE TITLE
icon-record

### ISSUE THREAD

**Issue by parkerbennett** [FortAwesome/Font-Awesome#156]
It would be great to have just a plain circle. Bonus points for solid and outline versions.

**Comment by Crissov** [comment]
Either #156 or #2555 should be closed as a duplicate, or one should be changed to `-o`.

**Comment by tagliala** [comment]
I think that http://fontawesome.io/icon/circle/ http://fontawesome.io/icon/circle-thin/ and http://fontawesome.io/icon/circle-o/ do the job

Please let me know if record should be different
