### ISSUE TITLE
Icon request: fa-eunicycle, fa-segway, fa-escooter, fa-esk8, fa-ebike

### ISSUE THREAD

**Issue by hhfrancois** [FortAwesome/Font-Awesome#15600]
**What can it be used for?**
For show new transportation modes

Describe how this could be used / the use case for this icon.
I 'm doing a free web application for compare models of these new transportation mode.
I need some icons to present sections

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi @hhfrancois 

I will explain how requests work with my own words, sorry for being pedantic.

>  This is a single icon or matched pair (Ex: lock / unlock)

This is a requirement for a on the free repository: single-requests (or requests for strictly-related icons) are more manageable than icon sets.

Feel free to open new individual requests, and we would be grateful if you provide examples for icons that are not self-explanatory (`esk8`)

Anyway, if you are a Font Awesome Pro customer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro. If you are a Font Awesome Pro customer but you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here too
