### ISSUE TITLE
new issue Icon request: icon-dashboard, icon-interviews, icon-contacts, icon-monitoring, icon-reports, icon-documents and icon-analytics

### ISSUE THREAD

**Issue by veereshmeesala** [FortAwesome/Font-Awesome#1560]
Hi,

We are planning to use font awesome in one of our projects, can we get the below mentioned fonts.

Attached the screen of the icons which resembles the as per the numbering.

![image](https://f.cloud.github.com/assets/4812146/787999/bc7b6eb4-eaee-11e2-9132-ff433da318fe.png)

1.	icon-dashboard (exist not similar to our needs)
2.	icon-interviews ( request new one)
3.	icon-contacts ( request new one)
4.	icon- check ( exists) 
5.	icon-monitoring (request new one)
6.	icon-reports (request new one)
7.	icon-documents (request new one)
8.	icon-analytics (request new one)

Thanks
Veeresh.

**Comment by ITPrism** [comment]
+1

**Comment by tagliala** [comment]
Sorry, closing here because of updated contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please open new individual requests to ask for redesign or new icons
