### ISSUE TITLE
Font-awesome kit: it loads all font versions

### ISSUE THREAD

**Issue by Shulepov** [FortAwesome/Font-Awesome#15618]
Why it loads so much font versions?
Screenshot: https://imgur.com/a/98UST2m

**Comment by livthomas** [comment]
You've probably encountered the same problem that is being discussed in issue #15167.

**Comment by tagliala** [comment]
@livthomas thanks for the heads-up.

Closing this as a duplicate of #15167.

I've opened a new internal ticket to increase the priority of that issue, but unfortunately we still don't have a solution, sorry
