### ISSUE TITLE
Telegram icon redesign

### ISSUE THREAD

**Issue by smartcorestudio** [FortAwesome/Font-Awesome#15614]
In 2019 Telegram icon was redesigned. Here is the [new icon](https://en.wikipedia.org/wiki/Telegram_(software)#/media/File:Telegram_2019_Logo.svg). Update, please!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can definitely see the new icon in my iPhone, even if I'm not able to find an official blog post or page about this change

Let's assign @sensibleworld

**Comment by smartcorestudio** [comment]
Here you can see a short mention about the new icon: [https://telegram.org/blog/archive-and-new-design](https://telegram.org/blog/archive-and-new-design#android-39s-new-clothes), although in some places they still use their old icon 😕

**Comment by sensibleworld** [comment]
I'm hesitant to update this icon until we get official word, or official assets for the new icon. The linked SVG above looks like it was auto-traced from their app icon.

**Comment by tagliala** [comment]
Going to close here in favor of #16664
