### ISSUE TITLE
Twitch icon redesign

### ISSUE THREAD

**Issue by ThibaultVlacich** [FortAwesome/Font-Awesome#15616]
Twitch redesigned it's logo yesterday. Changes to "glitch" are very subtle, but there are changes.

Here's the announcement blog post: https://blog.twitch.tv/en/2019/09/26/nice-to-meet-you-again-for-the-first-time/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up!

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/twitch?style=brands
