### ISSUE TITLE
Icon request: icon-mask

### ISSUE THREAD

**Issue by kylemwhite** [FortAwesome/Font-Awesome#1562]
something like the icon in firefox when browsing in private. my use case is for when one user is impersonating another user... but could also mean something about privacy.

**Comment by jabarnes** [comment]
+1 for an icon to denote impersonating a user.

**Comment by Ludophiles** [comment]
+1

**Comment by tompazourek** [comment]
+1

**Comment by tagliala** [comment]
#refers to #1270

**Comment by tompazourek** [comment]
@tagliala: It's different. #1562 refers to "incognito", "anonymous", "impersonation", whereas #1270 more to "drama", "theatre", "comedy".

**Comment by mariegithub** [comment]
+1

**Comment by tobia** [comment]
+1 for user impersonation

**Comment by babarizbak** [comment]
+1

**Comment by allenwq** [comment]
+1 for user masquerading

**Comment by asaletnik** [comment]
+1

**Comment by gauthier-delacroix** [comment]
+1

**Comment by clopezcapo** [comment]
+10

**Comment by yoda** [comment]
+100

**Comment by nibbleshrew** [comment]
Yeah, +1 from me. This was started 3 years ago, so what the criteria for getting it in. What threshold do we have to hit?

**Comment by tagliala** [comment]
is this the same icon requested at #1270?

**Comment by mnpenner** [comment]
As mentioned before in this thread, no it is not. These have two very
different meanings. One is about privacy, the other is about theatre.

**Comment by knozis** [comment]
+1

**Comment by michaelbilcot** [comment]
+1

**Comment by eliseumds** [comment]
:+1:

**Comment by alystair** [comment]
Is this in consideration for 2018?

**Comment by lucianorc** [comment]
+1

**Comment by lucianorc** [comment]
+1

**Comment by ighunter** [comment]
+1

**Comment by solidscape** [comment]
Here's another picture. <img src="http://icons.iconarchive.com/icons/iconsmind/outline/256/Mask-icon.png"></img>
