### ISSUE TITLE
Icon Request: icon-directions

### ISSUE THREAD

**Issue by Showcase-Joz** [FortAwesome/Font-Awesome#1563]
this icon would be used on responsive sites to allow the user to "get directions" to a map location

i did try making this with a level-down rotated in a box.....its not a diamond so didnt work well

![directions_icon](https://f.cloud.github.com/assets/3405708/792900/1f7700f2-ebce-11e2-94b2-4dd268ce20f9.gif)

**Comment by groupnet** [comment]
+1

**Comment by theill** [comment]
+1

This is how it looks in Google Maps with sharp edges:

![diamond with a right-arrow inside](http://d.pr/i/1kc36+)

**Comment by danilocasa** [comment]
+1

**Comment by JavierM42** [comment]
+1

**Comment by yleviel** [comment]
+1

**Comment by yleviel** [comment]
@sensibleworld Thank you for taking on this ticket.  Is there any timeframe being looked at for release?  Asking because my company is stuck between hand crafting (similar to what @Showcase-Joz mentioned), using the Material icon, or waiting until font awesome includes the icon.

**Comment by sensibleworld** [comment]
@yleviel The icon has been designed, and I'm hoping to get it into our next release. Should be in the next few weeks.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/directions?style=solid

**Comment by yleviel** [comment]
Thank you!
