### ISSUE TITLE
Icon request: fa-unlock-times

### ISSUE THREAD

**Issue by spigott24** [FortAwesome/Font-Awesome#15638]
**What can it be used for?**
This can be used for error handling and messaging. When a user's attempt to lock in a price is cancelled, this will help visually communicate it. 

**Example image (optional)**
<img width="153" alt="Screen Shot 2019-10-01 at 12 01 32 PM" src="https://user-images.githubusercontent.com/56044061/65987553-48fd1c80-e443-11e9-9297-096de4e1aabb.png">

**Icon request checklist**
- [Y] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Y] I have included at least one example image if it could be helpful (optional)
- [Y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms and masking features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/208/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking

**Comment by spigott24** [comment]
Wow, thank you! Our team had no idea this was possible. Really appreciate your quick and thorough reply!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
