### ISSUE TITLE
Icon request: Coffin with no cross

### ISSUE THREAD

**Issue by DarthBilly** [FortAwesome/Font-Awesome#15646]
**What can it be used for?**
To signify a funeral, a death, a burial and so on. Font Awesome has a coffin icon, but it has a cross on it thus giving it a religious connotation. I'd like to have a non-religious coffin icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ y] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [n ] I have included at least one example image if it could be helpful (optional)
- [y ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Updated the existing coffin icon to remove the cross, and added a new coffin-cross icon:

https://fontawesome.com/icons/coffin?style=solid
https://fontawesome.com/icons/coffin-cross?style=solid
