### ISSUE TITLE
Glyph contours could be optimized

### ISSUE THREAD

**Issue by puzrin** [FortAwesome/Font-Awesome#1565]
When writing [svg2ttf](https://github.com/fontello/svg2ttf) convertor and trying to optimize output file size, I found, that some FA glyphs contains "useless" points, placed nearby. See attached screenshot (near corsor). Their count can be significantly reduced without loss of quality. I guess, your font editor has tools to optimize points count.

![fa_useless_points](https://f.cloud.github.com/assets/319465/794124/bcdf0f56-ec73-11e2-868e-9d56b37509b5.png)

PS. My best wishes for your work!

**Comment by sensibleworld** [comment]
Cleaning up some old issues, and came across this one. The process with all of our newer icons should  fix most of these issues. Certainly let us know if any icons in version 5 need optimization.

Thanks!
