### ISSUE TITLE
Misspelling in Clock glyph page

### ISSUE THREAD

**Issue by Alfetta159** [FortAwesome/Font-Awesome#15650]
Should it be 

`<i class="far fa-clock"></i>` 

or

`<i class="fas fa-clock"></i>`

See: [clock](https://fontawesome.com/icons/clock?style=regular)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, maybe I didn't get this issue, but if that is a question, the answer is "both `fas` and `far` are correct".

We are using different prefixes for different styles, so `fas` means solid and `far` regular (the old "outline" of FA 4.7)

Demo: https://jsfiddle.net/tagliala/1nyx6efz/3/

If my answer helps, please close this issue
