### ISSUE TITLE
Issues ont desktop since release 5.7.0

### ISSUE THREAD

**Issue by jo-laurendeau** [FortAwesome/Font-Awesome#15667]
Hello,

Since release 5.7.0, desktop Font Awesome Desktop doesn't work anymore (new icons are not visible, icons are not well incorporated on documents (ex. power point, etc.)).

Version 5.6.3 works well and I tested every version since 5.7.0 and none of them is working.
=> icons are not visible and are no longer incorporated in powerpoint presentation nor pdf.
(see attachment)

Can you please see what happens and fix this issue ?

Regards,
Jean-Olivier
![v5 6 3](https://user-images.githubusercontent.com/46871187/66512120-967b2880-ead8-11e9-8d9f-1bd97173a3ac.png)
![v5 7 0](https://user-images.githubusercontent.com/46871187/66512121-9713bf00-ead8-11e9-853e-56612541be2c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, we are aware of this issue with microsoft products but unfortunately we don't have a solution yet

Please keep an eye on #14614
