### ISSUE TITLE
Icon request : Instagram multicolor version

### ISSUE THREAD

**Issue by sammmuel** [FortAwesome/Font-Awesome#15665]
**What can it be used for?**
Glyph icon Instagram multicolor version  to point our presence online. Do you plan to vectorize this model?

**Example image (optional)**
This example was downloaded from https://en.instagram-brand.com/assets/icons.
![image](https://user-images.githubusercontent.com/28735669/66481000-36689000-eaa0-11e9-8067-0b016ad9c464.png)

Thanks

**Comment by sensibleworld** [comment]
Hi there! We're limited to single-color icons for our brand logos. But you can always add your own treatments to them!
