### ISSUE TITLE
Bug: duotone opacity swap on envelope-open-text

### ISSUE THREAD

**Issue by matthewmb** [FortAwesome/Font-Awesome#15676]
**Describe the bug**
When using class "fa-swap-opacity" on icon "envelope-open-text", the lettering disappears, creating a blank letter

**To Reproduce**
1. Go to https://fontawesome.com/icons?d=gallery&q=envelope-open-text&s=duotone
2. Inspect the icon
3. Add class "fa-swap-opacity"

**Expected behavior**
The lettering should swap to the secondary colour

**Screenshots**
![Example](https://user-images.githubusercontent.com/29061406/66621707-79556f80-ec28-11e9-9781-ace169d68c6e.gif)

**Version and implementation**
Version: latest
Browser and version: Firefox latest, Chrome latest

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Thanks for the heads-up! We'll get this fixed in the next release.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/envelope-open-text?style=duotone
