### ISSUE TITLE
[Critical] Font Awesome registry is down

### ISSUE THREAD

**Issue by kaiyoma** [FortAwesome/Font-Awesome#15680]
`yarn install` fails with this:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-regular-svg-icons/-/pro-regular-svg-icons-5.11.2.tgz: Request failed \"502 Bad Gateway\"".
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@kaiyoma is this still a problem? sometimes there are temporary issues

@robmadole could you please check

**Comment by kaiyoma** [comment]
Looks like it's back up (`yarn install` is working again). Feel free to close.

**Comment by tagliala** [comment]
Thanks for the heads-up

**Comment by olivierbeaulieu** [comment]
What is the cause of this issue? We get failing builds every once in a while because of this. https://status.fortawesome.com/ indicates that npm.fontawesome.com has been having performance issues, with the last update being from September 3rd. The update states:

> The service up-time of this tool is well below what we'd like to maintain. We will be investigating some new solutions within the next week and will send announcements regarding our plans to make this service more reliable.

Has any announcement been made?

**Comment by robmadole** [comment]
Not yet. We have picked a solution and we are implementing it now. We'll send an announcement when it's finished.
