### ISSUE TITLE
Specify a color on the icon details page

### ISSUE THREAD

**Issue by Pixelrise** [FortAwesome/Font-Awesome#15686]
Hey Fonticons Team,
first of all, thank you for your awesome work! 👌

I have a short question or maybe an idea for the fontawesome.com site.
Is it possible to provide a color to the icon detail page, like it is possible for the style?

If not, I would really love to see something like this:
[https://fontawesome.com/icons/coins?style=solid&**color=FFD700**](https://fontawesome.com/icons/coins?style=solid&color=FFD700)

This would provide the possibility to send someone an icon with a specific style **and a color**, which would be totally great.
Btw. you also could add a color picker on the detail page as well. 😉

Best regards

**Comment by silenteyesoncode** [comment]
can I work on this

**Comment by sensibleworld** [comment]
This is now possible! https://fontawesome.com/icons/coins?f=classic&s=solid&pc=%2374C0FC
