### ISSUE TITLE
Font weight issue when using with some frameworks

### ISSUE THREAD

**Issue by FragsterAt** [FortAwesome/Font-Awesome#15689]
Initial bug in quasar framework
https://github.com/quasarframework/quasar/issues/5191

In that case it can be fixed with !important modifier for font-weight in .fas class (and other generic classes).

**Comment by tagliala** [comment]
Hi!

Thanks again for the PR, but we are not going to add `!important` rules in FA

Ref: https://github.com/FortAwesome/Font-Awesome/pull/15690#issuecomment-542206791
