### ISSUE TITLE
希望下载的包中包含 图标的 json 文件

### ISSUE THREAD

**Issue by yue792069154** [FortAwesome/Font-Awesome#15682]
功能场景：
提供图标选择功能

希望下载的包中包含 图标的 json 文件以便第三方集成开发

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate:

> Functional scenario:
> Provide icon selection
> 
> I want to download the package containing the json file of the icon for third-party integrated development.

a json file is available in the metadata folder at https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.json

Hope it helps

Closing here

**Comment by yue792069154** [comment]
Thank you




------------------ 原始邮件 ------------------
发件人: "Geremia Taglialatela"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 下午4:24
收件人: "FortAwesome/Font-Awesome"<Font-Awesome@noreply.github.com>;
抄送: "乐文"<792069154@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FortAwesome/Font-Awesome] 希望下载的包中包含 图标的 json 文件 (#15682)




Hi!
 
Thanks for being part of the Font Awesome Community.
 
From google translate:
  
Functional scenario:
 Provide icon selection
 
I want to download the package containing the json file of the icon for third-party integrated development.
  
a json file is available in the metadata folder at https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.json
 
Hope it helps
 
Closing here
