### ISSUE TITLE
Font-Awesome icons missing entirely in edge and displaying as empty boxes in chrome

### ISSUE THREAD

**Issue by mharp1030** [FortAwesome/Font-Awesome#15681]
This issue was brought to my attention today where icons I am using (Phone, horizontal bar, maps car, clock, tools, and several others) have all stopped loading and display either empty boxes or nothing at all in their place. I was on version 5.6.3 and I even went into the archives to find an older version of my code that has a local copy Font-Awesome and they all have the same issues. I went ahead and upgraded to the latest version of font-awesome and the issue is still not fixed. I have attempted trying it on multiple devices and I'm still having issues. Some icons (left arrow, right arrow, up arrow, envelope, facebook, yelp, and twitter) still work, but those are it. No changes were implemented between the time it was working and when it suddenly stopped... it seems to have broke out of nowhere (maybe a change in chrome and edge has caused the icons to not load, but it's weird that it picks and chooses).

When I execute the conflict detector I am shown that there is no conflict found, but I do the message that everyone else seems to be getting in the console "A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."

I don't believe this is the reason why everything stopped working, as no one else seems to be running into issues, but as of now, it's all I have.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?
