### ISSUE TITLE
Update Android Icon

### ISSUE THREAD

**Issue by hebbet** [FortAwesome/Font-Awesome#15697]
**What can it be used for?**
Google changed the Logo of Android with the release of Android 10 in summer 2019
the removed the body of the android.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/1423115/66919289-590b2380-f021-11e9-89d0-0499179befbf.png)

https://upload.wikimedia.org/wikipedia/commons/3/3b/Android_new_logo_2019.svg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

maybe you should keep the old as android-alt

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/android?style=brands
