### ISSUE TITLE
Icon request: icon-engine

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#15704]
**What can it be used for?**
Fo represent an car engine

**Example image (optional)**

**Icon request checklist**
- [ cob/piston/gas] This is a single icon or matched pair

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could this be considered a duplicate of #4175 ?

**Comment by lucasmantoani** [comment]
No, the check-engine light is something different from the engine representation that he talk about IMO

**Comment by afroty** [comment]
+1

**Comment by aethior** [comment]
I think this request can be considered a duplicate of #15275.

cc/ @tagliala
