### ISSUE TITLE
Icon request: fa-curtain-open, fa-curtain-closed, fa-curtain-half-open (shades)

### ISSUE THREAD

**Issue by vergoossen** [FortAwesome/Font-Awesome#15702]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.
![curtain_open_690679](https://user-images.githubusercontent.com/25444741/67004447-9f738780-f0e0-11e9-8ed9-8e7bfdd3e635.png)

This one is for open, and another for closed and half open.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Closing here in favour of #15598
