### ISSUE TITLE
Icon request: mouse-left-click / mouse-right-click

### ISSUE THREAD

**Issue by quasipickle** [FortAwesome/Font-Awesome#15700]
I'm aware these have been requested before (most recently it looks like #13250), but most requests are closed - some for not following the template.  Hopefully this follows the template well enough.

**What can it be used for?**
This icon could be used in legends or documentation to indicate what happens when a user left-clicks or right-clicks.

**Example image (optional)**
A regular `fa-mouse` with the left or right buttons filled in would suffice.  For `fas`, make the un-clicked button an outline.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

#13250 is open and is receiving upvotes, we can use that one

Closing here
