### ISSUE TITLE
Icon change request for fa-piano

### ISSUE THREAD

**Issue by uxchameleon** [FortAwesome/Font-Awesome#15705]
Hi awesome Fontawesome-team!
I am stoked to see the release of so many great instrument icons!
One of which is fa-piano.

A piano has the black keys grouped in 3 and 2 keys. The icon currently has a single black key in the middle, which looks wrong.

Attached the suggestion for the change.

![fa-piano](https://user-images.githubusercontent.com/12539828/67079963-790f2400-f194-11e9-8cba-162e1730c77f.png)

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I'm going to assign @sensibleworld

**Comment by sensibleworld** [comment]
Thanks again for the suggestion! https://fontawesome.com/icons/piano?style=solid
