### ISSUE TITLE
Contradicting license for @fortawesome/fontawesome-common-types: MIT or Pro

### ISSUE THREAD

**Issue by PhilippWendler** [FortAwesome/Font-Awesome#15714]
**Describe the bug**

The [npm package `@fortawesome/fontawesome-common-types`](https://www.npmjs.com/package/@fortawesome/fontawesome-common-types) in its latest version (0.2.25) has a `package.json` that declares `"license": "MIT"`, but the `LICENSE.txt` file in the package contains the "Font Awesome Pro License". At least one of this must be wrong.

I am not sure why this happens because https://github.com/FortAwesome/Font-Awesome/blob/master/js-packages/%40fortawesome/fontawesome-common-types/LICENSE.txt was last changed 10 months ago and contains the "Fontawesome Free License" (which is still not ideal, but at least refers to MIT for code), although the npm package was published just one month ago.

**To Reproduce**

Download [fontawesome-common-types-0.2.25.tgz](https://registry.npmjs.org/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.2.25.tgz) and compare content of `package.json` and `LICENSE.txt`.

**Expected behavior**

License declaration for package and actual license text should match.

**Version and implementation**
Version: 0.2.25

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I think there is a mistake in the downloadable package

@robmadole could you please take a look?

**Comment by robmadole** [comment]
This is just a mistake. We'll get it fixed in 5.12.0. It should be MIT which is for the JavaScript code.

**Comment by haf** [comment]
So if this happens:

```
$ npm install @types/styled-jsx

npm ERR! code E402
npm ERR! 402 Payment Required - GET https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/0.2.25/fortawesome-fontawesome-common-types-0.2.25.tgz?source=t-mNfJaFFoPPIt&signature=gAAAAABeGEoQhtGhkcKOkbNXvWqXAcuax4PYdnF4rf3h0M0vk86xJRZr1zB69uou-W-WJRqPSzmryHFae-sZ-yDWGZcXS1cYjqWRr9T-HhFfiV3GP2_KrHPhkSXlIj7S39Q0ELJv6gq9
```

When you depend on these packages:

```

    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.7",
```

What's up then?

**Comment by tagliala** [comment]
@haf sorry, the license server is down. Please follow up on #16046

**Comment by robmadole** [comment]
The NPM outage has been resolved

**Comment by PhilippWendler** [comment]
In [version 0.2.26](https://registry.npmjs.org/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.2.26.tgz), there is fortunately no longer the wrong reference to the Font Awesome Pro License. Thanks!

However, `LICENSE.txt` contains the Font Awesome Free License whereas `package.json` declares `MIT`, so there is still some inconsistency. The Font Awesome Free License actually says that all files in this package are under the MIT license, but people might still wonder why `LICENSE.txt` does not just contain the same license as declared in `package.json`.

If this is intended, this issue can be closed.

**Comment by tagliala** [comment]
Thanks for the heads-up

> However, LICENSE.txt contains the Font Awesome Free License whereas package.json declares MIT, so there is still some inconsistency. 

I think it has been done to keep just one LICENSE.txt across all the packages.

The same happens for fontawesome-svg-core, another package with MIT license: https://github.com/FortAwesome/Font-Awesome/blob/master/js-packages/%40fortawesome/fontawesome-svg-core/LICENSE.txt

Going to close here for the moment
