### ISSUE TITLE
CORS issue with Pro account

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#15718]
Getting the error, "No 'Access-Control-Allow-Origin' header is present on the requested resource." with my Pro subscription on the site loadexpress.statesolutions.us.

This seems to be a problem with the latest version (5.11.2) as a rollback to 5.8.1 is working.

**Comment by sgbj** [comment]
Can confirm this is happening to us as well. 5.11.0 seems to be the latest version that still works for us. The CDN link was working yesterday, so it must've started sometime today.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot confirm this, my console output only shows

```
A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by roarytubbs** [comment]
I can confirm rolling back to 5.8.1 is the current work around I found too.

**Comment by tagliala** [comment]
Any chance to have a reproducible test case?

**Comment by sgbj** [comment]
It's working for me now. I think this was due to https://status.fortawesome.com/incident/122

**Comment by tagliala** [comment]
@sgbj thanks

I'm going to close here, feel free to ping me if this is still an issue
