### ISSUE TITLE
Linkedin Square Icon incorrect.

### ISSUE THREAD

**Issue by airliajsmith** [FortAwesome/Font-Awesome#15716]
Just letting you know that the square Linkedin Icon url is incorrect. The link is the same as the original, but should include "-square" on the end.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that the current implementation is right

[linkedin](https://fontawesome.com/icons/linkedin?style=brands) matches [LinkedIn's Brand Guidelines](https://brand.linkedin.com/downloads)

Our old [linkedin-square](https://fontawesome.com/v4.7.0/icon/linkedin-square) didn't, in fact the border radius does not match the official one as well as the one of other icons with `-square` prefix (ex: [facebook-square](https://fontawesome.com/icons/facebook-square?style=brands))

Hope it helps

Closing here
