### ISSUE TITLE
IP address (151.139.128.10) that kit-pro.fontawesome.com routes to is blacklisted

### ISSUE THREAD

**Issue by martin-panacea** [FortAwesome/Font-Awesome#15728]
**Describe the bug**
The IP address for the kit is blacklisted in several places, font awesome cannot be loaded and any site using font awesome cannot be loaded correctly.

**To Reproduce**
Use Font Awesome from behind a proxy

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Black listing sites where the IP address is listed**
https://dnslytics.com/ip/151.139.128.10 
https://www.abuseipdb.com/check/151.139.128.10

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IIRC, this has already been reported, but I think that we can't do anything about that

@robmadole any chance to fix this?

**Comment by robmadole** [comment]
These are false positives. If you are using these services (dnslytics.com, and abuseipdb.com) please report that the results are false to them.

**Comment by aaww01** [comment]
So all those security scanners that are reporting abuse from the IP of the CDN are ALL false positives?  I doubt it.

**Comment by robmadole** [comment]
I happen to know exactly what is running on those IP addresses :) They are false positives.

**Comment by aaww01** [comment]
@robmadole, the mere fact that there are over 10,000 domains hosted on that one IP address, 151.139.128.10, (dnslytics reports 13,740 domains), the doubt is raised that some of these virtual hosts be serving malware?  
Virustotal, a reputable source of information, agrees and indicates that a number of files / content contain malware, See: https://www.virustotal.com/gui/ip-address/151.139.128.10/relations

The point is that enterprise firewalls are using black lists that continuously list 151.139.128.10, and consequently are preventing browsers from reaching malicious sites hosted there (we want that) as well as preventing legitimate traffic from reaching kit.fontawesome.com, and in the end the clients are not enjoying an great experience.

**Comment by robmadole** [comment]
@aaww01 the IP address is an anycast IP for a CDN (a reputable one). These security tools are lumping all the customers and domains into one bucket and then demanding that there be no abuse. It's impractical. That was my point about it being a false positive. Until these security tools can differentiate ([and some can](https://www.virustotal.com/gui/domain/kit.fontawesome.com/details)) the domain + IP (kit.fontawesome.com + 151.139.128.10) and intelligently handle anycast networks they aren't going to be useful.

So we (Font Awesome) are kinda stuck. If you know of a way to handle this that I don't I'm all ears. The whole thing is frustrating for everyone involved.

**Comment by aaww01** [comment]
@robmadole, Thanks, I do appreciate your response and the challenge that both Font Awesome and the community at large are dealing with.  Domain + IP is clearly the smart way to deal with this, but as you said the security tools are lacking.

**Comment by nate-knight** [comment]
We are also getting reports from customers stating that icons are not loading, due to security measures (eg. ThreatStop) blocking access to the IP address listed above. We will have to turn to self-hosting fontawesome unless there is another resolution (CDN vendor replacement?).

**Comment by rschiefer** [comment]
> We are also getting reports from customers stating that icons are not loading, due to security measures (eg. ThreatStop) blocking access to the IP address listed above. We will have to turn to self-hosting fontawesome unless there is another resolution (CDN vendor replacement?).

@nate-knight did self hosting work?  it looked like the script had urls to download more content from font-awesome which just have the same error right?

**Comment by robmadole** [comment]
@rschiefer are you experiencing issues? We've been on a dedicated, non-shared IP for several months now.

**Comment by rschiefer** [comment]
A customer reported that FontAwesome had been flagged by their security software. We reached out to get more details but haven't heard back.  If they do I'll let you know.
