### ISSUE TITLE
Not loading icons?

### ISSUE THREAD

**Issue by repositoriomedia** [FortAwesome/Font-Awesome#15720]
The webpage cannot load icons,
And also it doesn't load on my own webpage, not pretty sure is and issue with your site, but I need help. Look:
![image](https://user-images.githubusercontent.com/55359441/67344491-de994280-f4fd-11e9-940a-d0df3e40f52f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this still an issue?

**Comment by uthirapandian** [comment]
Hi. we are also having problems with the icons loading on our website. Our icons.css is using below URL which fails to load with SSL certificate error.

https://file.myfontastic.com/q2SthnZcH57HXYXJb4cmxk/fonts/1506629835.woff

![image](https://user-images.githubusercontent.com/23666872/67697050-4d532180-f97e-11e9-963e-a744385a62c8.png)

![image](https://user-images.githubusercontent.com/23666872/67697100-63f97880-f97e-11e9-89d8-b3d83c72cc70.png)

**Comment by tagliala** [comment]
Hi @uthirapandian , the official Font Awesome website is https://fontawesome.com/

**Comment by sensibleworld** [comment]
Following up from @tagliala's note, it appears that these are two different issues. The second issue seems unrelated to us, as the domain being referenced isn't hosted by us.

I'm going to close this thread, but please re-open if you're still experiencing the issue with our website.
