### ISSUE TITLE
New NPM Release

### ISSUE THREAD

**Issue by RonanDConnolly** [FortAwesome/Font-Awesome#15722]
The last version published to NPM was done 3 years ago.
It's now out of date.

Can we get a new release published?

Current Releases:
https://www.npmjs.com/package/font-awesome?activeTab=versions

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at our scoped npm repository, you will find the latest official versions of Font Awesome: https://www.npmjs.com/search?q=scope%3Afortawesome

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Hope it helps

Closing here
