### ISSUE TITLE
Icon Request: fa-client

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#15723]
The use case is to represent people and organizations who give you money in exchange for goods or services. This is in contrast to a _vendor_, who you give money in exchange for goods or services. (fa-vendor already requested at #13185.) 

I'm really not sure what an icon for "client" would look like. The traditional "group of people" icon is too generic. There also needs to be a distinction between this meaning of "client" and other meanings of "client." (A [search on "client"](https://fontawesome.com/icons?d=gallery&q=client) turns up a bunch of icons pertaining to fire, which isn't at all what I think of when I think of "client.")

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can leave this open, but we need
- a better title
- an example

> I'm really not sure what an icon for "client" would look like.

Client will probably end up with `user-with-something`, where something is dollar sign, shopping bag, and it will depend on the specific use case

Demo: https://jsfiddle.net/tagliala/L17f528g/222/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by jbnv** [comment]
I ended up using the handshake icon for this purpose.
