### ISSUE TITLE
<i class="fal fa-user-hard-hat"></i> not working...

### ISSUE THREAD

**Issue by ashish-sharma91** [FortAwesome/Font-Awesome#15726]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome Light style is only available in FA Pro, so I guess that you are using FA Pro

[hard-hat](https://fontawesome.com/icons/hard-hat?style=solid) has been introduced in version 5.7.0, please double check that you are using FA 5 Pro version 5.7.0 or newer

Example (on 5.11.0) https://jsfiddle.net/tagliala/rLw7bxt4/5/
