### ISSUE TITLE
Icon Request: fa-services

### ISSUE THREAD

**Issue by RicardoLeonardoTorres** [FortAwesome/Font-Awesome#15731]
I need a icon for the helpdesk system. For example: the worker or construction hat. 
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> or construction hat.

So let's have a costruction hat! 

https://fontawesome.com/icons/hard-hat?style=solid

Or maybe a Pro user with a construction hat on their head: https://fontawesome.com/icons/user-hard-hat?style=solid

Or even a Free user with a construction hat, achieved with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/214/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
