### ISSUE TITLE
Brand Icon: Plesk

### ISSUE THREAD

**Issue by ShaunR** [FortAwesome/Font-Awesome#15739]
Plesk is a popular web hosting control panel.

This brand icon is a direct competitor of the cPanel brand icon that already exists within font-awesome as well. I also submitted a request for another control panel brand icon called Direct Admin.

It would be nice to see this icon added as well so we can use matching icons for each brand.

**Comment by ShaunR** [comment]
Brand Information for plesk is @ https://www.plesk.com/brand/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've seen your upvote at #12086, and this is the right approach to follow when a request is found

I'm closing here as a duplicate, but if this is not the same request please clarify and I will reopen
