### ISSUE TITLE
Icon request: fa-shopping-bag-empty

### ISSUE THREAD

**Issue by romanown** [FortAwesome/Font-Awesome#15744]
**What can it be used for?**
online shop. if i use fa-shopping-bag bad view the number of products
![изображение](https://user-images.githubusercontent.com/7169357/67754990-6c1dea80-fa48-11e9-9825-c1558c4c419a.png)

single
**Example image (optional)**
as fa-shopping-bag but white for inner and without horizontal line
![изображение](https://user-images.githubusercontent.com/7169357/67754665-e863fe00-fa47-11e9-988a-f66f24de88ec.png)

in the website when user adding to shop card it is 
![изображение](https://user-images.githubusercontent.com/7169357/67755165-b3a47680-fa48-11e9-9005-db8f4bda846b.png)
thank You

**Comment by Tofandel** [comment]
It already exists https://fontawesome.com/icons/shopping-bag?style=regular
It's a pro icon

**Comment by romanown** [comment]
https://fontawesome.com/ is not worked

**Comment by romanown** [comment]
the site does not work correctly. only the home page opens

**Comment by romanown** [comment]
can I make this icon for myself in version 4?

**Comment by romanown** [comment]
thank You.
