### ISSUE TITLE
FreeCodeCamp's icon has been updated.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [FortAwesome/Font-Awesome#15740]
Thank you for having the freecodecamp logo on Font-Awesome

Since the freecodecamp logo has been updated, would it be possible to update it here as well in the next release?  

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for bringing this to our attention.

I can see the updated logo, but both https://design-style-guide.freecodecamp.org/ and https://github.com/freeCodeCamp/assets contain the old one

Do you have any official resource with the updated logo?

**Comment by ahmadabdolsaheb** [comment]
Thank you for your prompt reply.
https://design-style-guide.freecodecamp.org/ has been updated with the new logo.
https://github.com/freeCodeCamp/assets will be updated in the next 24hrs.

**Comment by tagliala** [comment]
@sensibleworld let's keep an eye on this 👀

**Comment by ahmadabdolsaheb** [comment]
@sensibleworld @tagliala I double checked with the maintainers.
The https://github.com/freeCodeCamp/assets is no longer used and has been archived so it will not be updated.

On the other hand https://design-style-guide.freecodecamp.org/ and its repo https://github.com/freeCodeCamp/design-style-guide will be used as the single source of truth for assets. 

Please let me know if you would like additional information before updating the freecodecamp logo on your side. Thank you

**Comment by tagliala** [comment]
@ahmadabdolsaheb I think assets at https://github.com/freeCodeCamp/design-style-guide/tree/master/downloads are fine

**Comment by ahmadabdolsaheb** [comment]
yes, I just optimized the assets a little and modified the logo in minor way and updated the repo and the design style guides accordingly. I just wanted to communicate that to make you use the latest version.

Thank you for your responsiveness and look forward to seeing freecodecamp's new logo in fontawesome.

**Comment by tagliala** [comment]
AFAIK @sensibleworld didn't start working on this ticket

**Comment by sensibleworld** [comment]
This will be updated in our next release!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/free-code-camp?style=brands
