### ISSUE TITLE
Needs to change fas instead of far

### ISSUE THREAD

**Issue by jayakumar4u** [FortAwesome/Font-Awesome#15746]
![image](https://user-images.githubusercontent.com/6740303/67820577-d4c2a100-faf4-11e9-8216-be992bc34339.png)

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

**Comment by Tofandel** [comment]
I'm guessing he means that the stop-circle icon is in the wrong icon category, it looks like a solid icon but is in the regular icon set

**Comment by tagliala** [comment]
Sorry, but stop-circle icons look good to me

![image](https://user-images.githubusercontent.com/556268/68534379-4213d480-0334-11ea-8777-b2df2b3eeb6a.png)

If there is any trouble about `fab`/`fas`/`far`/`fal`/`fad` classes, please refer to the documentation: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Closing here, but if this is still an issue, feel free to comment
