### ISSUE TITLE
Dispositioned pupil fad fa-grin-tongue-wink

### ISSUE THREAD

**Issue by designchapnl** [FortAwesome/Font-Awesome#15747]
**Describe the bug**
Pupil is not in center of eye. Assuming this should be in center of eye.

**To Reproduce**
https://fontawesome.com/icons/grin-tongue-wink?style=duotone

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/29886711/67849516-faf13c80-fb06-11e9-9bf0-752bc49ca0e5.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
We've got this one fixed: https://fontawesome.com/icons/grin-tongue-wink?style=duotone
