### ISSUE TITLE
Icon request: fa-collection (fa-album-collection for generic elements)

### ISSUE THREAD

**Issue by uxchameleon** [FortAwesome/Font-Awesome#15754]
**What can it be used for?**
Any kind of collections/albums. It is a generic album-icon

**Example image (optional)**
<img width="144" alt="Bildschirmfoto 2019-10-31 um 09 18 44" src="https://user-images.githubusercontent.com/12539828/67930337-d4dba300-fbbf-11e9-8bc9-efd8733a496d.png">

**Comment by aethior** [comment]
Hi @uxchameleon,

Something like [fa-rectangle-history](https://fontawesome.com/icons/rectangle-history)?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
I would say so
