### ISSUE TITLE
fa-hand-peace icon has its palm facing the wrong way

### ISSUE THREAD

**Issue by mkalam-alami** [FortAwesome/Font-Awesome#15751]
**Describe the bug**
The icon is showing the back of the hand instead of the palm, which our users reported can be interpreted as a insulting gesture. Source: https://en.wikipedia.org/wiki/V_sign#As_an_insult

**To Reproduce**
Icon: https://fontawesome.com/icons/hand-peace?style=regular

**Expected behavior**
The "hand peace" sign should have the palm face the viewer instead.

**Version and implementation**
Version: 5.X
Browser and version: Any

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this

Well, even if it looks like a left-handed ✌🏼sign, the thumb should be clearly visible here!

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This is now fixed in the v6 Alpha release: https://fontawesome.com/download
