### ISSUE TITLE
Icon Request:icon-pineapple

### ISSUE THREAD

**Issue by ludoblues** [FortAwesome/Font-Awesome#1576]
More globally, it could be nice to have a "fruit" or "food" section.

**Comment by G-Driver** [comment]
+1

Some example
<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/021_Pineapple-512.png">

**Comment by osdavison** [comment]
+1

**Comment by Crissov** [comment]
🍍 [U+1F34D](http://emojipedia.org/pineapple/) Unicode emoji #222

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of version 6: http://fontawesome.com/download
