### ISSUE TITLE
Missing icons: fa-tags, fa-tag

### ISSUE THREAD

**Issue by hellqvist** [FortAwesome/Font-Awesome#15762]
**Describe the bug**
According to fontawesome.com fa-tags and fa-tag shall be a part of the free solid icons but I can't find it among the svg-icons in the free-solid-svg-icons package.

**To Reproduce**
```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faTags } from '@fortawesome/free-solid-svg-icons';

library.add(faTags);

<FontAwesomeIcon icon={'fa-tags'} />
```
**Expected behavior**
I'm expecting icon from https://fontawesome.com/icons/tags?style=solid to be shown but nothing is shown. 

**Screenshots**
No screenshot

**Version and implementation**
Version: fontawesome-svg-core: 1.2.25, free-solid-svg-icons: 5.11.2, react-fontawesome: 0.1.7
Browser and version: Not applicable

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

```js
<FontAwesomeIcon icon={'fa-tags'} />
```

Please try with

```js
<FontAwesomeIcon icon={"tags"} />
```

Ref: https://www.npmjs.com/package/@fortawesome/react-fontawesome

Demo: https://codesandbox.io/s/o84659ok6

But... we could have a wrong example

@robmadole

Is the `faCoffee` example at

https://www.npmjs.com/package/@fortawesome/react-fontawesome#explicit-import

correct?
