### ISSUE TITLE
duotone cheatsheet error - person-dolly is person-dolly-empty

### ISSUE THREAD

**Issue by esharden** [FortAwesome/Font-Awesome#15767]
On the latest Pro cheatsheet, the duotone icon for person-dolly is wrong (the box is missing). Instead, the person-dolly-empty icon is shown twice.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot confirm

![image](https://user-images.githubusercontent.com/556268/68077247-c5777800-fdc0-11e9-9db1-dbcb503b29c6.png)

Person dolly has the box on the primary glyph (top-left)

Ref: https://fontawesome.com/cheatsheet/pro/duotone

Could you please clarify this issue?

**Comment by tagliala** [comment]
No feedback, closing here meanwhile
