### ISSUE TITLE
Icon update request: Microsoft Edge

### ISSUE THREAD

**Issue by Studio384** [FortAwesome/Font-Awesome#15771]
**What can it be used for?**
Replace the current fa-edge icon.

**Example image (optional)**
See https://github.com/alrra/browser-logos/pull/180#issuecomment-549565755

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up

Let see if we manage to do this in the upcoming release of FA

**Comment by sensibleworld** [comment]
We'll get this updated, but I'd like to wait until the browser is out of beta.

**Comment by x-rated** [comment]
> We'll get this updated, but I'd like to wait until the browser is out of beta.
You can download Esge stable here:
https://go.microsoft.com/fwlink/?linkid=2069324&Channel=Stable&language=en

**Comment by beko1997** [comment]
The stable version of Edge based on Chromium will be officially launched on the 15th of January (https://www.microsoftedgeinsider.com/whats-new). It would be great if we could manage the new version for Edge icon in Font Awesome somewhere close to that date.

**Comment by pimterry** [comment]
The new version & logo are now officially launched & stable: https://twitter.com/MSEdgeDev/status/1217492875878887430. It'd be great to get this into Font Awesome ASAP.

**Comment by sensibleworld** [comment]
Does anyone have a link to an official vector version of the logo (single color, if possible)?

**Comment by x-rated** [comment]
This one looks pretty well https://upload.wikimedia.org/wikipedia/commons/9/98/Microsoft_Edge_logo_%282019%29.svg

**Comment by sensibleworld** [comment]
This is live now: https://fontawesome.com/icons/edge?style=brands
