### ISSUE TITLE
Duotone clock icon is inconsistent with other clock icons and too heavy

### ISSUE THREAD

**Issue by lllopo** [FortAwesome/Font-Awesome#15779]
The 'clock' duotone icon is light hands on dark font face, while the other similar icons, like 'alarm-clock', 'stopwatch' and 'watch' all have dark hands on light font face. They are better looking, not so heavy and also consistent with other duotone icons like 'map-marker-alt', 'calendar' etc. 
So, I think the 'clock' icon needs to be fixed, by swapping the hands and clock face colors.

- [ ] alarm-clock
- [ ] stopwatch
- [ ] watch (???)
- [ ] watch-fitness (???)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can definitely see your point, there is an inconsistency here https://fontawesome.com/icons?d=gallery&q=clock&s=duotone

@sensibleworld could you please take a look=

**Comment by sensibleworld** [comment]
Got this fixed up in the 5.12.1 release: https://fontawesome.com/icons/clock?style=duotone
