### ISSUE TITLE
Icon request: icon-pause-sign

### ISSUE THREAD

**Issue by fplanque** [FortAwesome/Font-Awesome#1577]
Hello, I'd very much like to have an icon-pause-sign which would be the natural cousin to icon-play-sign and icon-pause.

I already tried to create the icon by stacking icon-pause over icon-circle, but it's not great:
![icon-pause-sign](https://f.cloud.github.com/assets/1156771/802171/9172dc16-edb9-11e2-8a02-6819d1ab1044.png)

First it's not aligned with other "-sign" icons which is probably fixable. 

But more problematic: the pause sign doesn't have enough breathing space inside of the circle.

Am I making sense?

**Comment by Crissov** [comment]
This is `fa-pause-circle`, right? That’s been added in v4.5, released on 23 Nov 2015.

This issue should therefore be closed as solved.

**Comment by aethior** [comment]
(cc @tagliala)

**Comment by tagliala** [comment]
Thanks
