### ISSUE TITLE
Icon request: fa-golf-cart

### ISSUE THREAD

**Issue by obrienware** [FortAwesome/Font-Awesome#15773]
Thank you guys for your amazing work. The electric golf cart was originally requested #10330 but was closed due to a duplicate request #11277 now also closed because it was a duplicate of 10330. i.e. they are both closed and there is no open request for it, so - please can we have a golf cart icon? Many thanks in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

#10330 is correctly open, but GitHub adds a label and that may be confusing

Hope it helps

Closing here
