### ISSUE TITLE
Icon request: user-unlock

### ISSUE THREAD

**Issue by tquensen** [FortAwesome/Font-Awesome#15784]
**What can it be used for?**
There already is the icon user-lock ( https://fontawesome.com/icons/user-lock?style=solid )
user-unlock is for the opposite action of user-lock

**Example image (optional)**
as user-lock is user + lock-alt, user-unlock should be similar to a combination of user + unlock-alt

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by CoolScratcher** [comment]
Good idea!
Where would this be used in a website?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/250/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tquensen** [comment]
Hi!
Thanks for responding.

My use case for those icons are toggles to allow/disallow users to change certain settings (Changes allowed for users / changes not allowed for users)
Unfortunately I am using the css only webfont version where power transforms are not available, so a new icon would be the easiest way to achieve this :)

**Comment by aethior** [comment]
Hi @tquensen,

This icon was added in v5.12.1
Check https://fontawesome.com/icons/user-unlock

Regards.

cc/ @tagliala
