### ISSUE TITLE
Tooltip does not show in IE browser due to title element positioning

### ISSUE THREAD

**Issue by mosquitobite82** [FortAwesome/Font-Awesome#15782]
**Describe the bug**
The example below is a "fa-question-circle" Icon.
The structure of the font awesome generated elements will be as follows:
```
    <svg>
        <title></title>
        <path></path>
    </svg>
```
However, when running this in Internet Explorer it does not show a tool tip when hovering over the Icon. But when using the structure given here (title being the first child of path-element):
```
    <svg>
        <path>
            <title></title>
        </path>
    </svg>
```
… it works in Internet Explorer. I found support for this markup here:
https://www.w3.org/TR/SVG11/struct.html#DescriptionAndTitleElements
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
so it should be a preferable way to go, given all browsers are ok with it.

**To Reproduce**
I created a plunk so that you can try it out;
http://plnkr.co/edit/u29uFr?p=preview

**Expected behavior**
A tooltip based on an existing title element would appear when hovering over the fontawesome Icon using all major browsers, including Internet Explorer.

**Version and implementation**
Tested in fontawesome 5.4.2 & 5.5.0
Browser and version: IE 11

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for bringing this to our attention.

So, if you are using Font Awesome SVG Framework and your markup is like

```html
<span class="fas fa-question-circle" title="test"></span>
```

You suggest to put the `<title>` tag inside the <path> element instead of the SVG one to workaround an old ie issue

I can read from the link you provided that

> The <title> element provides an accessible, short-text description of any SVG container element or graphics element.

Container element includes <svg>, so it should be fine.

I think that this is something that we could do just for IE, but I cannot take a look at the moment because I do not have a windows machine with me

@robmadole could you please take a look?

**Comment by robmadole** [comment]
The last time I looked at this (and tried it) the issue was that the tooltip doesn't show up unless you are hovering over a portion of the icon that is black. So for a lot of our thinner icons that do not have large shapes this just wouldn't work.

**Comment by mosquitobite82** [comment]
Hi @tagliala and @robmadole andthank you for your responses!
@tagliala : Yes, I thought so to. The link to W3C suggested both markup alternatives so they both should be good to go. However, after I have tried it out, the only thing that makes it work in IE is the markup:
```
<svg>
    <path>
        <title></title>
```
and not 
```
<svg>
    <title></title>
```

@robmadole : 
That's a good point, but in the provided code demo you can see that this is not the case. Ive scaled the icon up so you can hover over it easily to see when the cursor is over the vector path and when it's not.

**Comment by robmadole** [comment]
@mosquitobite82 I tried latest Safari, Firefox, and Chrome on Mac and the tooltip only appears if you are hovering over the black part of the icon. Do you see this as well or am I missing something?

**Comment by mosquitobite82** [comment]
@robmadole Thank you for your response. Yes, it works in Safari, Firefox and Chrome. The issue I'm describing is about the browser Internet Explorer, so that's the thing you missed.
If you open up the plunk http://plnkr.co/edit/u29uFr?p=preview in Internet Explorer and do the following:
Uncomment one title tag at a time and hover over the icon. The one that says "Does not work in IE" will not appear if you've opened it up in Internet Explorer. The one that says "Does work in IE" will appear when hovering over the icon.

**Comment by robmadole** [comment]
@mosquitobite82 the problem is that if we change this behavior it will create a problem for the other browsers (as I described). So this fix is not worth breaking the other 3 or 4 major browsers to fix the older IE. If we can come up with a solution that doesn't sacrifice the others I'd be more interested in using it.

**Comment by mosquitobite82** [comment]
@robmadole Ah I see. Well, I've made a work around for IE in our application and I can dig into this issue and maybe suggest a way to implement a solution that is being nice to all browsers.

Yeah, it feels quite strange for me to dig this deep into an issue with IE. But more than 30% of our users sits behind old IE browsers and needs alot of tooltips so my primary dev browser right now is IE. It feels quite exotic. :)

Thank you so much for your involvement. I'll  contact you again when I've come up with a suggestion and see if you like it.

Best regards, Johannes

**Comment by robmadole** [comment]
> Yeah, it feels quite strange for me to dig this deep into an issue with IE. But more than 30% of our users sits behind old IE browsers and needs alot of tooltips so my primary dev browser right now is IE. It feels quite exotic. :)

I totally understand that 😄. I can remember the days not too long ago when our primary browser target was IE6 at a place I worked.
