### ISSUE TITLE
Example not working (light style with font awesome free)

### ISSUE THREAD

**Issue by zombiesbyte** [FortAwesome/Font-Awesome#15780]
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-web-fonts

Shows an example of

```
<head>
  <link href="/your-path-to-fontawesome/css/all.css" rel="stylesheet"> <!--load all styles -->
</head>
<body>
  <i class="fas fa-user"></i> <!-- uses solid style -->
  <i class="far fa-user"></i> <!-- uses regular style -->
  <i class="fal fa-user"></i> <!-- uses light style -->
  <!--brand icon-->
  <i class="fab fa-github-square"></i> <!-- uses brands style -->
</body>
```

The fal fa-user icons do not show at all... how is this an example of how to start.

I put in the following line...
`<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>`
...and get 3 of the 4 icons working (the fal fa-user only shows as a square/missing icon)

Is there some secret to understanding examples that don't represent the correct way of doing things?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The fal fa-user icons do not show at all... how is this an example of how to start.

Light stile is an exclusive of our commercial product Font Awesome Pro, so it will not work with FA Free (the one loaded in the example)

If you are a Font Awesome Pro customer, please use the pro cdn / kit and let me know if your issues has been fixed

**Comment by ahmadraza348** [comment]
waste
