### ISSUE TITLE
Icon request: icon-old-phone

### ISSUE THREAD

**Issue by tuananhtn** [FortAwesome/Font-Awesome#1578]
Hello, I already tried to create the icon, a draw by photoshop:

![old-phone](https://f.cloud.github.com/assets/5018001/802372/34945276-edc4-11e2-8bbc-db415b53c559.png)

Hope you will accept it. Thanks.

**Comment by G-Driver** [comment]
+1

**Comment by DOBss** [comment]
+1 please add this to FontAwesome itself also - I am personaly not using bootstrap on the frontend of every project

**Comment by brunowerneck** [comment]
+1

**Comment by bryne78** [comment]
Hey guys. I will very appreciate if you can make home phone icon. Something like that one
http://www.clipartbest.com/cliparts/RiA/L5z/RiAL5zdiL.jpeg
It will very help me because the phone icon you have not really looks nice for our web.
If need i can definitely pay for the job.
Thank you

**Comment by ferman2147** [comment]
+1

**Comment by AndreLGava** [comment]
@bryne78 you can create your icon sending a photo to http://fontastic.me/ this generates a css that you can use into your project, if you really need it fast

**Comment by Ramsz** [comment]
Where did this icon go? I thought an old version of FA supported this.. did it not?

**Comment by IanSd** [comment]
+1

**Comment by pjuvigny** [comment]
+1

**Comment by kjensenxz** [comment]
+1

**Comment by sdfsdhgjkbmnmxc** [comment]
+1

**Comment by mhjb** [comment]
+1

**Comment by papplebee** [comment]
+1

**Comment by zacchaeusluke** [comment]
+1 please

**Comment by kymburley** [comment]
+1

**Comment by akalongman** [comment]
+1

**Comment by boillatlucas** [comment]
+1

**Comment by Jorgemunive** [comment]
+1

**Comment by davidkonrad** [comment]
+1

**Comment by mahald** [comment]
+1

**Comment by alesub** [comment]
+1

**Comment by sensibleworld** [comment]
Version 5.11 has a rotary phone icon: https://fontawesome.com/icons/phone-rotary?style=solid
