### ISSUE TITLE
double http requests when using kit

### ISSUE THREAD

**Issue by khashabawy** [FortAwesome/Font-Awesome#15798]
![double-request](https://user-images.githubusercontent.com/400698/68593538-5bd12b00-049e-11ea-8162-534976bbffc7.png)

**Comment by usabilitest** [comment]
I only get 2 JS files and the rest are SVGs.
![image](https://user-images.githubusercontent.com/5130744/68709614-aebce800-055b-11ea-8d03-31067de6300d.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Let's use #15167 for this issue.

Please also note that Rob is asking for HAR files to debug this issue
