### ISSUE TITLE
Bug Report: f884 & f885

### ISSUE THREAD

**Issue by LucasCiocari** [FortAwesome/Font-Awesome#15794]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
square instead of icon
**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
https://codepen.io/lucasciocari/pen/yLLqJQq
Describe any details about the test case that we need to know like "whatever you do, don't click the red button."
do whatever I guess
**Expected behavior**
How would you like this to work instead?
show the right icon
**Screenshots**

**Version and implementation**
Version: 4.3.0
Browser and version: Firefox 70.0.1 

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by LucasCiocari** [comment]
Hopefully the report is good enough, any other info please let me know

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your codepen is using Font Awesome 4.7.0, which is in EOL

Also, I cannot see f884 here: https://fontawesome.com/v4.7.0/cheatsheet/, so I'm going to assume that we are talking about 

https://fontawesome.com/icons/sort-amount-down-alt?style=solid
https://fontawesome.com/icons/sort-amount-up-alt?style=solid

Font Awesome 5 has a completely different usage from v4, please take a look at our docs if you have troubles: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Please also note that FA4 is not compatible with d3, and in FA5 we have individual SVG files that could help

Ref: https://github.com/FortAwesome/Font-Awesome/issues/12268#issuecomment-363570898

Hope it helps

Closing here

**Comment by LucasCiocari** [comment]
Thank you, I was not aware of any of this. 

Conectado 16/11/2019 04:14:34, Geremia Taglialatela <notifications@github.com> escreveu:
Hi!
Thanks for being part of the Font Awesome Community.
Your codepen is using Font Awesome 4.7.0, which is in EOL
Also, I cannot see f884 here: https://fontawesome.com/v4.7.0/cheatsheet/ [https://fontawesome.com/v4.7.0/cheatsheet/], so I'm going to assume that we are talking about
https://fontawesome.com/icons/sort-amount-down-alt?style=solid [https://fontawesome.com/icons/sort-amount-down-alt?style=solid]
https://fontawesome.com/icons/sort-amount-up-alt?style=solid [https://fontawesome.com/icons/sort-amount-up-alt?style=solid]
Font Awesome 5 has a completely different usage from v4, please take a look at our docs if you have troubles: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use [https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use]
Please also note that FA4 is not compatible with d3, and in FA5 we have individual SVG files that could help
Ref: #12268 (comment) [https://github.com/FortAwesome/Font-Awesome/issues/12268#issuecomment-363570898]
Hope it helps
Closing here
