### ISSUE TITLE
Icon Request: Discord

### ISSUE THREAD

**Issue by BetaHackerYT** [FortAwesome/Font-Awesome#15790]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fp7.hiclipart.com%2Fpreview%2F89%2F257%2F298%2Fdiscord-computer-icons-logo-simplify.jpg&imgrefurl=https%3A%2F%2Fwww.hiclipart.com%2Ffree-transparent-background-png-clipart-mggfq&docid=jaSkWW8vZb4ibM&tbnid=ZYreeWYLKmD2mM%3A&vet=10ahUKEwidyuyIjdvlAhWEyaQKHUGsB3YQMwhXKAYwBg..i&w=800&h=800&bih=979&biw=1920&q=discord%20transparent%20png&ved=0ahUKEwidyuyIjdvlAhWEyaQKHUGsB3YQMwhXKAYwBg&iact=mrc&uact=8

**Comment by tagliala** [comment]
voila! https://fontawesome.com/icons/discord?style=brands

Just make sure that you are using Font Awesome >= 5.0.0
