### ISSUE TITLE
Icon update request: Mozilla Firefox

### ISSUE THREAD

**Issue by x-rated** [FortAwesome/Font-Awesome#15799]
**What can it be used for?**
Replace the current fa-firefox icon.

**Example image (optional)**
https://upload.wikimedia.org/wikipedia/commons/a/a0/Firefox_logo%2C_2019.svg

**Comment by lucasmantoani** [comment]
Hey ! 
There is already an issue here [#15729](https://github.com/FortAwesome/Font-Awesome/pull/15729) 
I think you should upvote the one that already exist !

**Comment by tagliala** [comment]
Hi, this is coming in the next version of FA 👍
