### ISSUE TITLE
Icon request: Marijuana Leaf

### ISSUE THREAD

**Issue by buxton161** [FortAwesome/Font-Awesome#15797]
With the legalization moving closer and the 420 industry moving faster with more and more 420 sites out there, I would like to request a Marijuana leaf icon.

One dark and one outlined ( 0 )

Could even be placed into the medical field for recreational marijuana.

Thank you.

Mike

**Comment by flyboarder** [comment]
@buxton161 there is already the "cannabis" icon

**Comment by buxton161** [comment]
I did not see one ? Is it also in -0

**Comment by flyboarder** [comment]
https://fontawesome.com/icons/cannabis?style=solid

I believe this is what you are looking for, there is no `-o` variation, but I do recommend the light theme if you are using PRO.

**Comment by tagliala** [comment]
Thanks, closing here
