### ISSUE TITLE
Icon request: icon-dino

### ISSUE THREAD

**Issue by ikhwanul** [FortAwesome/Font-Awesome#1580]
hello .

I want to request icons dino:

Tirex, the long neck, and early humans.

**Comment by thekondrashov** [comment]
+1

**Comment by elenamg75** [comment]
+1

**Comment by thumptech** [comment]
+1

**Comment by charlex** [comment]
+1

**Comment by jperezlatimes** [comment]
+1

**Comment by mgd722** [comment]
+1

**Comment by ranesr** [comment]
+1

**Comment by Crissov** [comment]
U+1F995 and U+1F996 in Unicode 10.0 probably #222

http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f995

**Comment by blackbret94** [comment]
2018 and keeping the +1 going!!!

**Comment by fiomerino** [comment]
+1 !

**Comment by corwinperdomo** [comment]
+1

**Comment by BillLudwig** [comment]
+1

**Comment by fabswt** [comment]
+1

Say, a diplodocus.

I'd use this to illustrate a browser support error, e.g. "This site is not compatible with Internet Explorer".

**Comment by rthomas88** [comment]
wow. this has been a suggestion since 2013 and still no movement? I also wanted to use the dinosaur to mean outdated but I was shocked it doesn't exist. I mean really, Font Awesome has a honeybadger but not a single dinosaur???

**Comment by tundralogic** [comment]
+1 of this as well, would really like to use this for "outdated"

**Comment by Dono7** [comment]
+1 !
Dinosaures are so cool, FontAwesome needs to have at least the 2 basic ones !
- Sauropod / Diplodocus 🦕 
- T-rex 🦖

**Comment by ElectroNugget** [comment]
+1
We have loads of star wars, bees and all sorts of other random critters. But no love for the guys who ruled the earth for 165 million years? :D

**Comment by SquaredStudios-MC** [comment]
new year, new +1

**Comment by BillLudwig** [comment]
Keeping the dream alive. +1

**Comment by rthomas88** [comment]
NINE YEARS. It has been NINE YEARS since this was requested. At this point I feel like the developers are doing this on purpose. Seriously, do they even look at these requests?

**Comment by fabswt** [comment]
How long have dinosaurs been off the surface of the Earth? Well... It might take as long for this dino to spawn into life 😅

**Comment by millertn** [comment]
gotta leave a +1, keep the dino dream alive

**Comment by thestepafter** [comment]
Long live dinos. +1

**Comment by sensibleworld** [comment]
We're saur-y it's taken so long(neck).

https://fontawesome.com/icons/dinosaur?f=classic&s=solid

**Comment by tundralogic** [comment]
> We're saur-y it's taken so long(neck).
> 
> https://fontawesome.com/icons/dinosaur?f=classic&s=solid

https://media.tenor.com/daNUZaNUSFEAAAAC/holyshit-jurassic-park.gif

**Comment by SquaredStudios-MC** [comment]
yeepee!

**Comment by rthomas88** [comment]
Hooray!!! Now we just need a t-rex...hopefully it will take less than 10 years this time :)

**Comment by tagliala** [comment]
@Neustradamus this is a request for the animal, not the application. If you want to request a Dino.im icon, please fill out a [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

**Comment by sensibleworld** [comment]
Our dinosaur icon now has a friend! https://fontawesome.com/icons/t-rex?f=classic&s=solid

**Comment by AstroSquared** [comment]
Hooray! Only took about ten years.
