### ISSUE TITLE
signal-slash and wifi-slash 

### ISSUE THREAD

**Issue by Mahesh-Sriramula** [FortAwesome/Font-Awesome#15807]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Mahesh-Sriramula** [comment]
please provide signal-slash and wifi-slash icons if possible.


Thanks in advance

**Comment by sensibleworld** [comment]
Hi @Mahesh-Sriramula! Thanks for being a part of the community! The good news is that both of those icons already exist as part of Font Awesome Pro:

https://fontawesome.com/icons/signal-slash?style=solid
https://fontawesome.com/icons/wifi-slash?style=solid

**Comment by Mahesh-Sriramula** [comment]
Hi Jory Raphael


thanks and is there not available driver icon i think so.





Thanks in Advance

*Mahesh B Sriramula*
Mob:9440229402
Email: mahesh.harjit@gmail.com
Portfolio: https://www.behance.net/mahesh-sriramula

**Comment by sensibleworld** [comment]
I'm not sure I follow your question. Are you asking if there's a "driver" icon? Could you provide an example of what you're looking for? You can see all of our icons here: http://fontawesome.com/icons

**Comment by Mahesh-Sriramula** [comment]
Am not able to find driver icon..

**Comment by sensibleworld** [comment]
@Mahesh-Sriramula I am unclear what you mean by "driver" icon.
