### ISSUE TITLE
Circle Regular listed as free, but only comes with Pro

### ISSUE THREAD

**Issue by jrothra** [FortAwesome/Font-Awesome#15809]
According to the gallery (and the icon's own page), the Circle Regular is part of Font Awesome 5 Free.

Screen shot: https://www.dropbox.com/s/vorelvyqpzl2toa/FA5%20Free.jpg?dl=0

However, when viewing the icon's own page, it's listed as free, yet has a "far" class (Pro only).

Screen shot: https://www.dropbox.com/s/35ndsboue0jz8u2/FA5%20Circle%20Regular.jpg?dl=0

When trying to use it on a site, only the solid circle shows up because F111 free, per the icon's own page, is both the solid and regular circle.  This seems inconsistent to list it as a free icon, but group it as a pro-only icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are using `font-weight` to differentiate between solid and regular styles, so it is correct that f\\\ is the unicode point for all circle icons

Demo: https://jsfiddle.net/tagliala/1nyx6efz/8/

Ref:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#define

Hope it helps

Closing here
