### ISSUE TITLE
Icon request: fa-forumbee

### ISSUE THREAD

**Issue by JerryChin** [FortAwesome/Font-Awesome#15814]
**What can it be used for?**
I need it for navigation.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

PS:

I've imported font-awesome (^5.11.2) in my vue project, and I try to use `forumbee` icon, but it's missing from the icon library.

**Comment by tagliala** [comment]
Voilà!

https://fontawesome.com/icons/forumbee?style=brands

> I've imported font-awesome (^5.11.2) in my vue project, and I try to use forumbee icon, but it's missing from the icon library.

Please make sure that you are using the proper styles (forumbee is in brand category) and configuration. Also, we have a vue.js plugin that should be used for Vue projects

If you still have issues, please fill out  our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
