### ISSUE TITLE
Icon requests: icon-drum, icon-flask, icon-testtube, icon-guitar, icon-erlenflask, icon-microscope, icon-thermometer, icon-piano, icon-wheelchair

### ISSUE THREAD

**Issue by muekoeff** [FortAwesome/Font-Awesome#1581]
Hello.

I'd like to request some new icons for FontAwesome.

![drum](https://f.cloud.github.com/assets/3207399/804286/56c4cfde-ee09-11e2-8e58-e86e01a2dc69.png)
![instrument-round-bottom-flask](https://f.cloud.github.com/assets/3207399/804287/56d8fcac-ee09-11e2-87f6-9037d60e8b8d.png)
![instrument-test-tube](https://f.cloud.github.com/assets/3207399/804288/56ee56f6-ee09-11e2-80fb-dc853942a442.png)
![guitar](https://f.cloud.github.com/assets/3207399/804289/56f664e0-ee09-11e2-94cb-d0e739222fb1.png)
![instrument-erlenmeyer flask](https://f.cloud.github.com/assets/3207399/804290/56f77cea-ee09-11e2-8db6-8a39ed3759bc.png)
![instrument-microscope](https://f.cloud.github.com/assets/3207399/804291/56f3a8d6-ee09-11e2-96fe-8ec83800a208.png)
![instrument-thermometer](https://f.cloud.github.com/assets/3207399/804292/57036924-ee09-11e2-8328-f02c1e6622c5.png)
![piano](https://f.cloud.github.com/assets/3207399/804293/570ed1ce-ee09-11e2-8cc8-3813715c9d12.png)
![wheelchair](https://f.cloud.github.com/assets/3207399/804294/570f0518-ee09-11e2-9354-83a64e55f3c4.png)

**Comment by billshannon** [comment]
+1 for icon-drums
+1 for icon-guitar
+1 for icon-bass
+1 for icon-vocals
