### ISSUE TITLE
Icon request: quick-shopping-cart-fast (quick order)

### ISSUE THREAD

**Issue by RoarAtme** [FortAwesome/Font-Awesome#15810]
**What can it be used for?**
An icon used to represent adding a quick-order 
**Example image (optional)**
![image](https://user-images.githubusercontent.com/5816805/68843904-2eb49080-06c9-11ea-8fa1-3c19358f3147.png)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @RoarAtme,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/cart-shopping-fast

Regards.

cc/ @tagliala
