### ISSUE TITLE
CDN for kit.fontawesome.com frequently on blacklists

### ISSUE THREAD

**Issue by aaww01** [FortAwesome/Font-Awesome#15812]
kit.fontawesome.com is hosted on CDN at stackpathcdn.com.
kit.fontawesome.com ultimately resolves to 151.139.128.10
This specific IP address has been on blacklists, and listed over at ipabusedb.com (and others) on and off for many months, consequently any sites that reference kit.fontawesome.com or kit-pro.fontawesome.com do not load or take a long time to load.

See: https://www.abuseipdb.com/check/151.139.128.10

Changing the blacklist in use is out of my control, but anything can be done on font-awesome side?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I have an official response from here: https://github.com/FortAwesome/Font-Awesome/issues/15728#issuecomment-546534172

Hope it helps

Closing here
