### ISSUE TITLE
 Icon request: stock-full

### ISSUE THREAD

**Issue by uok** [FortAwesome/Font-Awesome#15816]
Hello,
Please add icon(s) that can be used to represent stock status, e.g. full (in stock), in a shop.
Right now the battery icon could be used, but it just does not fit the scope.
Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example?

**Comment by uok** [comment]
I was thinking something like this, preference first one with 5 states like battery
![stock-status](https://user-images.githubusercontent.com/9367272/69006945-3e391100-0937-11ea-8d16-00db25776966.png)

**Comment by sensibleworld** [comment]
We have some options that might work for this: https://fontawesome.com/search?q=warehouse&o=r&s=solid&f=classic
