### ISSUE TITLE
A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by pttepley** [FortAwesome/Font-Awesome#15815]
Chrome reports the following:

A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #15643, let's use that thread
