### ISSUE TITLE
brands/nintendo-switch.svg is missing metadata

### ISSUE THREAD

**Issue by disrvptor** [FortAwesome/Font-Awesome#15824]
**Describe the bug**
*What happened? What are you seeing? How did you arrive here?*
`brands/nintendo-switch.svg` is missing metadata in `metadata/categories.yml` and `metadata/icons.yml`

**To Reproduce**
*Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.*
Not applicable

**Expected behavior**
*How would you like this to work instead?*
Add metadata to `metadata/categories.yml` and `metadata/icons.yml` for `brands/nintendo-switch.svg`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
Not applicable

**Version and implementation**
Version: 5.11.2 and master
Browser and version: Not applicable

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [x] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Nintendo Switch has been removed by request of Nintendo USA. Font Awesome will not include any icon from Nintendo

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#590---2019-06-04

Hope it helps

Closing here

**Comment by disrvptor** [comment]
@tagliala thanks for the prompt reply! However, if it was removed in 5.9.0 then why is the asset still in the repository as of 5.11.2? Does another issue need to be created to remove the asset?

https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/brands/nintendo-switch.svg
https://github.com/FortAwesome/Font-Awesome/blob/5.11.2/svgs/brands/nintendo-switch.svg

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by robmadole** [comment]
Good catch! This needs to be removed. I'll do that now.

**Comment by robmadole** [comment]
Fixed in 516a62816c76255dc92ed55b906e9dca5a21b28b
