### ISSUE TITLE
Icon Request: phone icon

### ISSUE THREAD

**Issue by DiKey-kov** [FortAwesome/Font-Awesome#15836]
You've got main contacts icons what people use in design.
it's: Phone, Mail and socials. Some of them looks like solid, some like lined. But I can't make them looks same (without outline process) and it's freaks me out.

Please make them look the same.
<img width="670" alt="Снимок экрана 2019-11-21 в 19 56 39" src="https://user-images.githubusercontent.com/56240218/69359419-9b1b2b00-0c99-11ea-9050-2397dbb8ed67.png">

**Comment by sensibleworld** [comment]
Hi there! What version of Font Awesome are you using? We have multiple styles, as well as a separate brand style. https://fontawesome.com/icons?d=gallery

**Comment by DiKey-kov** [comment]
understand... I just need pro) thank you!
