### ISSUE TITLE
fas fa-history

### ISSUE THREAD

**Issue by amadrocky** [FortAwesome/Font-Awesome#15834]
hello, 

when i want to se the page for to copy the icon "history clock" (<i class="fas fa_history"></i>), the website rediret to the homepage.

Thanks !

**Comment by sensibleworld** [comment]
@amadrocky Thanks for the report! I believe this issue has been fixed. Can you let me know if you're still experiencing it?

**Comment by tagliala** [comment]
@sensibleworld may this be a duplicate of #15834 ?
