### ISSUE TITLE
Icon request: condom

### ISSUE THREAD

**Issue by lzzzzzzz** [FortAwesome/Font-Awesome#15832]
**What can it be used for?**
A rolled out condom icon for use in sexual health promotion, sex education, and sale of sexual health products.

**Example image (optional)**
https://cdn.iconscout.com/icon/premium/png-256-thumb/condom-38-307437.png

**Comment by aethior** [comment]
This request is duplicate of #6127.
Please add a 👍 reaction to that request.

cc/ @tagliala
