### ISSUE TITLE
icons details page

### ISSUE THREAD

**Issue by abidinozler** [FortAwesome/Font-Awesome#15838]
icon's detail page is not working. It is redirecting to the main menu

**Comment by RomanKoff** [comment]
Same problem with the site. If you delete the cookies of the site, everything works the first time, and when you re-enter again redirect to the root

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

Is this still an issue?

**Comment by RomanKoff** [comment]
No, it's settled, thank you.

**Comment by tagliala** [comment]
No problem, closing here
