### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by pddzaic** [FortAwesome/Font-Awesome#15845]
On the [webside for version 4.7](https://fontawesome.com/v4.7.0/get-started/) there is the following content:

**Download & CustomizeEasy**
Want to manage and host Font Awesome assets yourself? You can download, customize, and use the icons and default styling manually. Both CSS and CSS Preprocessor (Sass and Less) formats are included.

The link 

[https://fontawesome.com/v4.7.0/assets/font-awesome-4.7.0.zip/](https://fontawesome.com/v4.7.0/assets/font-awesome-4.7.0.zip/)

seems not to be valid anymore.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Apparently we have an issue on the old documentation

Let's use #15844

**Comment by jdneo** [comment]
Hi!

Seems this link is still inaccessible: https://fontawesome.com/v4.7.0/assets/font-awesome-4.7.0.zip/?
