### ISSUE TITLE
Icon Request: Pound Sterling Icons

### ISSUE THREAD

**Issue by AlecWeekes** [FortAwesome/Font-Awesome#15848]
**What can it be used for?**
You currently support icons such as `comment-dollar`, `donate` & `badger-dollar` and I believe it would be very helpful if you could add further support for additional currencies in these icons. There are plenty of icons I could make use of it they featured the correct currency for the region I operate in.

While my request is more specific to the Pound Sterling, I understand that globally the use of it is limited compared to the Dollar, but adding in support for some of the more common currencies would make it more viable to use these icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request could bring to ~ 280 icons if we are going to provide all variations

Your request is legit, but please keep in mind that you can implement some of those icons with the power transforms, masking, and layering features of the SVG Framework.

I think that providing a neutral version of the icons to provide an easier customization is simple

Also, most of the icons with dollar sign have been sponsored during the kickstarter campaign, the sponsor is thanked in the documentation page
- https://fontawesome.com/icons/comment-dollar?style=solid
- https://fontawesome.com/icons/comments-dollar?style=solid
- https://fontawesome.com/icons/donate?style=solid

Demo: https://jsfiddle.net/tagliala/L17f528g/286/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
Closing this issue in favor of: https://github.com/FortAwesome/Font-Awesome/issues/20294
