### ISSUE TITLE
Icon request: wash-basin or sink

### ISSUE THREAD

**Issue by sera-e** [FortAwesome/Font-Awesome#15856]
**What can it be used for?**
Bathroom related products, categories, & shops.
Home related products, categories, & shops.
Hygiene related products, categories, & promos.

**Example image (optional)**
![wash-basin](https://user-images.githubusercontent.com/53708595/69576460-54c81380-0f9a-11ea-8b58-f93b6f2c8f30.png)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @sera-e,

This icon was added in v5.13.0.
Check https://fontawesome.com/icons/sink

Regards.

cc/ @tagliala
