### ISSUE TITLE
"https://npm.fontawesome.com/@fortawesome%2freact-fontawesome: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by futurespike** [FortAwesome/Font-Awesome#15857]
**Describe the bug**
We have been successfully using the file .npmrc to get install react-fontawesome until last Friday,  (11/22). Now all our builds fail on `yarn install` when attempting to fetch react-fontawesome. I uninstalled react-fontawesome, and the install completes. When I attempt to reinstall react-fontawesome `yarn install -dev @fortawesome/react-fontawesome`, I get the error below.

**error:**
`$ yarn add --dev @fortawesome/react-fontawesome
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2freact-fontawesome: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/Users/.../ui-client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

.npmrc: 
`@fortawesome:registry=https://npm.fontawesome.com
//npm.fontawesome.com/:_authToken=XXXXXXXXXXXX`

**Comment by robmadole** [comment]
@futurespike is this still an issue?

**Comment by kharsha** [comment]
I am also facing the same issue , any insights ?

**Comment by multivoltage** [comment]
Me too

**Comment by tagliala** [comment]
Please send an email to hello@fontawesome.com

**Comment by robmadole** [comment]
Yes, send us an email since this might have some security sensitive stuff going on.

But the first thing we'll have you check is "man-in-the-middle" proxy action.

@futurespike @kharsha @multivoltage can you run this and provide the output:

```
echo | openssl s_client -showcerts -servername npm.fontawesome.com -connect npm.fontawesome.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

**Comment by multivoltage** [comment]
@tagliala . Send an email: for what? who shoud be the senderr? What I' have to write inside?
@robmadole I am not very skilled in terminal commands. Does this command show some kind of private key?

**Comment by robmadole** [comment]
@multivoltage you can send an email to hello@fontawesome.com and we can work through the issue that you have. Give us the error output when you run your `npm` or `yarn` command.

Regarding the `openssl` command I gave: it shows the certificate details that your device is receiving when connecting to `npm.fontawesome.com`.

**Comment by kharsha** [comment]
@robmadole thanks for your inputs, i am getting below error - 

unable to load certificate
140735564915656:error:0906D06C:PEM routines:PEM_read_bio:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.3/libressl/crypto/pem/pem_lib.c:704:Expecting: TRUSTED CERTIFICATE

**Comment by robmadole** [comment]
@kharsha are you behind a firewall or some kind of security appliance?

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by DanyPell** [comment]
Same error:

error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2ffontawesome-svg-core: unable to get local issuer certificate".


No error log.

**Comment by tagliala** [comment]
Hi, not the same issue because `https://npm.fontawesome.com` is our private NPM repository, while ` https://registry.yarnpkg.com` is the public yarn repository we do not have control on

If you are a Pro customer with an active subscription and you want to use the private NPM repo, please refer to the documentation
