### ISSUE TITLE
Icon request: soap-bar

### ISSUE THREAD

**Issue by sera-e** [FortAwesome/Font-Awesome#15855]
**What can it be used for?**
Bathroom related products, categories, & shops.
Hygiene related products, categories, & promos.

**Example image (optional)**
![soap-bar](https://user-images.githubusercontent.com/53708595/69576262-ed11c880-0f99-11ea-96c1-d2b5466a9896.png)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by jeisel-northglenn** [comment]
This is kind of important right now with all the coronavirus stuff going around.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/soap?style=solid
