### ISSUE TITLE
Icon request: plastic-dispenser

### ISSUE THREAD

**Issue by sera-e** [FortAwesome/Font-Awesome#15865]
**What can it be used for?**
Bathroom related products, categories, & shops.
Hygiene related products, categories, & promos.
Salon related products, categories, and shops.

Note: This could be made into separate icons as well. Not sure if that requires two additional requests (i.e. fa-shampoo & fa-conditioner)
[Revised per comment]

**Example image (optional)**
Either of these (maybe make the tear into a circle so that it can be reversible?):
![plastic-dispenser](https://user-images.githubusercontent.com/53708595/69644589-d9667080-1032-11ea-8329-5a032f5f0537.png)
![plastic-container-2](https://user-images.githubusercontent.com/53708595/69646141-4bd85000-1035-11ea-9c7a-c483cef1227e.png)

**Icon request checklist**
- [ single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This could be made into separate icons as well. Not sure if that requires two additional requests (i.e. fa-shampoo & fa-conditioner)

I think that a better title and request could be useful. It is hard to represent a shampoo and a conditioner, but a "plastic dispenser" or something like that would fit more use cases

**Comment by sera-e** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > This could be made into separate icons as well. Not sure if that requires two additional requests (i.e. fa-shampoo & fa-conditioner)
> 
> I think that a better title and request could be useful. It is hard to represent a shampoo and a conditioner, but a "plastic dispenser" or something like that would fit more use cases

Revised per your comment. Thanks!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
