### ISSUE TITLE
Icon request: emoji-sick

### ISSUE THREAD

**Issue by dustcrawler** [FortAwesome/Font-Awesome#15863]
**What can it be used for?**
To indicate that you, or someone else is sick.

**Example image (optional)**
Edited: I added 3 images because it can be interpreted in different ways

<img src="https://i.dlpng.com/static/png/6340450_thumb.png" alt="emoji sick" />

<img src="https://cdn3.iconfinder.com/data/icons/emoji/100/Emoji_Sick-512.png" alt="emoji sick" />

<img src="https://cdn4.iconfinder.com/data/icons/emoticons-29/737/11-_Sick-512.png" alt="emoji sick" />

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We've added some more sick emoji to version 6! https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=sick&s=light&c=emoji
