### ISSUE TITLE
"fas fa-fan" is not rendering properly

### ISSUE THREAD

**Issue by arsenanai** [FortAwesome/Font-Awesome#15862]
**Describe the bug**
When I use fontawesome with npm, "fas fa-fan" is not rendering properly

**To Reproduce**
https://codesandbox.io/s/intelligent-wind-yofy5?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
Should be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/4026277/69614689-b604eb00-105d-11ea-8f9c-9b5fab2812d9.png)

**Version and implementation**
Version: 5.11.2
Browser and version: chrome Version 78.0.3904.108 (Official Build) (64-bit)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
![image](https://user-images.githubusercontent.com/556268/69616614-3532f880-1037-11ea-9cb8-c1b11779c941.png)

**Comment by arsenanai** [comment]
Here is screenshot from safari from iphone se, ios 13
![C28A3D04-BE54-421E-8E9E-AB2CDDD13B54](https://user-images.githubusercontent.com/4026277/69618005-5f021480-1063-11ea-9b12-91b88451bbe2.jpeg)

**Comment by tagliala** [comment]
Sorry for the late reply, I can see that the woff files are served with a wrong mime type: 
![image](https://user-images.githubusercontent.com/556268/70836131-88f75d00-1dff-11ea-9e2c-071f40c5e187.png)

Please check the following: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

**Comment by arsenanai** [comment]
> Sorry for the late reply, I can see that the woff files are served with a wrong mime type:
> ![image](https://user-images.githubusercontent.com/556268/70836131-88f75d00-1dff-11ea-9e2c-071f40c5e187.png)
> 
> Please check the following: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

One thing is for sure, next time I’ll download and set dependencies manually. It is sad that you can’t correct version of files in npm server by yourself, with correct whatever types

**Comment by tagliala** [comment]
> One thing is for sure, next time I’ll download and set dependencies manually. It is sad that you can’t correct version of files in npm server by yourself, with correct whatever types

Sorry, maybe I didn't understand, but if you download the dependencies manually and serve them from the same server with misconfigured mime types, you will run into the same error

**Comment by arsenanai** [comment]
I hope that the official website always will have correct versions

**Comment by tagliala** [comment]
> I hope that the official website always will have correct versions

If you mean the Font Awesome CDN, yes, the mime types are properly configured

Any other hosting does not depend on font awesome, there is nothing we can do about mime types set on other servers

Hope it helps

Meanwhile, closing here

Ref: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types
