### ISSUE TITLE
Azure devops build failing with correctly set .npmrc

### ISSUE THREAD

**Issue by Zebirdman** [FortAwesome/Font-Awesome#15860]
We are now having issues with our CI builds in Azure devops failing with the following output 

error An unexpected error occurred: "https://npm.fontawesome.com/OUR_CORRECT_TOKEN/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.11.2.tgz: Request failed \"404 Not Found\"".

We have updated our .npmrc to match the new format in the docs and the output from yarn config list can be seen here

![image](https://user-images.githubusercontent.com/21305250/69593847-987c5500-104e-11ea-90b3-4a280d5d859a.png)

I see no reason why this should not work as the output from the config list command is running in the same directory that we are trying to run the yarn install task. Is there something I am missing?

**Comment by Zebirdman** [comment]
ok so the issue here is that the url that was set in my yarn.lock was in a format that has apparently changed. Although I had yarn remove -> yarn add on the font awesome package to hopefully let yarn do its thing and set the resolved url correctly I wasnt taking into account the cached version.

After clearing my yarn cache and then running yarn remove, yarn add again the resolved url was set to the new format that does not have the token in the url (instead it sends the token via auth headers in the request).

Hope this helps someone else, closing this one out cheers o/

**Comment by tagliala** [comment]
@Zebirdman thanks for the heads-up
