### ISSUE TITLE
probably missing shimmed icons from 4.6.3 to 5.11.2

### ISSUE THREAD

**Issue by cicciogeppo88** [FortAwesome/Font-Awesome#15878]
Bug Description
Trying to move from version 4.6.3 to 5.11 I couldn't find  the icons 

- fa-envelope
- fa-pie-chart
- fa-check-square-o
- fa-file-excel-o
- fa-file-o

they needed to be replaced with

- fa-envelope
- fa-chart-pie
- fa-check-square
- fa-file-excel
- fa-file

Probably is just some missing shim 

To reproduce:
In order to reproduce you should try to start a project fa 4.6 or 4.7 and try to insert those icon and then try to update and you will probably get some missing icons issues

Expected Behaviour:
Ideally, the icons with replaced name should not give missing icons issues

**Version and implementation**
Version: 4.6.3 -> 5.11.2

**Bug report checklist**
- [ y] I have filled out as much of the above information as I can
- [ n] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
I can't reproduce this @cicciogeppo88. Here is an example of those icons being shimmed correctly.

https://codepen.io/robmadole/pen/VwYaJVa

If you can provide a reproduction we'll take a look (and reopen)
