### ISSUE TITLE
Icon request: Meetup

### ISSUE THREAD

**Issue by jrfernandes** [FortAwesome/Font-Awesome#1588]
Is it possible to include icons for Meetup?

Thanks

**Comment by KamilHavlicek** [comment]
+1

**Comment by RinkeRiezebos** [comment]
+1

**Comment by jcontini** [comment]
+1

**Comment by amlange** [comment]
+1  Please make a Meetup icon.

**Comment by grantneufeld** [comment]
+1

**Comment by jcontini** [comment]
Does anyone know of FA would accept a pull request if one of us were to just create it?

**Comment by tagliala** [comment]
@jcontini no, sorry, we can't accept pull requests containing icons.

But feel free to share your fork here, I'm pretty sure everyone here will appreciate

**Comment by kofronpi** [comment]
+1

**Comment by forres** [comment]
+1

**Comment by Random-Primate** [comment]
+1

**Comment by 972creative** [comment]
+1

**Comment by MattBroach** [comment]
I also needed a meetup icon, so I decided to fork and add my own.  Anyone still looking is more than welcome to grab my fork [here](https://github.com/MattBroach/Font-Awesome).

**Comment by tagliala** [comment]
@MattBroach thanks for sharing this

**Comment by 972creative** [comment]
As FontAwesome updates their system will yours be updated automatically?


[image: 972 creative] <http://www.972creative.com/>

*Todd Edelman*
Founder *| *972 creative <http://www.972creative.com/>
Israel: 052-332-1099
USA: +1-347-502-2628
UK: +44(0)20-3734-7271

**Comment by MattBroach** [comment]
Not automatically, no -- it basically exists in a separate stream from the actual Font Awesome repo.  I'll do my best to keep it updated, though.

**Comment by sirspens** [comment]
+1

**Comment by JayHoltslander** [comment]
+1

**Comment by mostofreddy** [comment]
+1

**Comment by Mattwig** [comment]
+1 for Meetup icon

**Comment by nategunn** [comment]
+1 for Meetup icon

**Comment by Arrested22** [comment]
+1

**Comment by JayHoltslander** [comment]
I've looked for an SVG vector version of the Meetup.com logo before so that I could perhaps add an icon for it to Font Awesome via Fontello. Never did find one. So I made it. 

This could be used as an icon if it helps anyone. It's included here in [SVG format...](https://github.com/JayHoltslander/Components-for-Sketch/tree/master/Logos/Meetup-logo)

![Meetup.com vector logo](https://raw.githubusercontent.com/JayHoltslander/Components-for-Sketch/master/Logos/Meetup-logo/preview.jpg)

**Comment by sonnyt** [comment]
+1

**Comment by henrik** [comment]
+1

**Comment by earldodd** [comment]
+1

**Comment by friendofdog** [comment]
+1

**Comment by shonlb** [comment]
+1

**Comment by mucahit** [comment]
+1

**Comment by tdeck** [comment]
+1

**Comment by archy-bold** [comment]
+1

**Comment by CesarTrigo** [comment]
+1

**Comment by lclc** [comment]
+1

**Comment by pjnovas** [comment]
+1

**Comment by GGFM** [comment]
+1

**Comment by anotherjung** [comment]
+1

**Comment by imithemes** [comment]
+1

**Comment by rojoko** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by dittoddt** [comment]
+1

**Comment by seglo** [comment]
+1

Thanks @JayHoltslander for the workaround

**Comment by JayHoltslander** [comment]
@seglo Glad I could help.

**Comment by flavioalves** [comment]
+1

**Comment by mustafawm** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by altsalt** [comment]
+1

**Comment by crystalgroves** [comment]
+1

**Comment by gwulfs** [comment]
+1

**Comment by mikehenken** [comment]
+1

**Comment by goorancid** [comment]
+1

**Comment by mrbgit** [comment]
+1

**Comment by terzano** [comment]
+1

**Comment by sabgaby** [comment]
+1

**Comment by vargaLaszlo** [comment]
+1

**Comment by vargaLaszlo** [comment]
+1

**Comment by pdoggi** [comment]
+1

**Comment by shoichiaizawa** [comment]
+1

**Comment by EarthLord** [comment]
+1

**Comment by shadowoflightt** [comment]
+1

**Comment by NavitBar** [comment]
+1

**Comment by w3on** [comment]
:+1: 
+1

**Comment by javierdaza** [comment]
:+1: 
+1

**Comment by YNedderhoff** [comment]
+1

**Comment by hlwaymack** [comment]
+1

**Comment by prashannth** [comment]
+1

**Comment by guangningyu** [comment]
+1

**Comment by ouadie-lahdioui** [comment]
+1

**Comment by kaaloo** [comment]
+1

**Comment by JordanMajd** [comment]
+1

**Comment by atomsmith** [comment]
+1

**Comment by robasaad** [comment]
+1 (cmon guys, seriously)

**Comment by nacame** [comment]
+1

**Comment by williamsrz** [comment]
+1

**Comment by showaid** [comment]
+1

**Comment by Velochic** [comment]
+1

**Comment by jjafuller** [comment]
+1

**Comment by brunomeira** [comment]
+1

**Comment by miccferr** [comment]
+1

**Comment by pqliberty** [comment]
+1

**Comment by rygel** [comment]
+1

**Comment by zazatek** [comment]
+1

**Comment by spaeps** [comment]
Meetup logo [has recently changed](http://blog.meetup.com/meetup-rebrand/).
![image](https://cloud.githubusercontent.com/assets/1037160/19292058/91b87978-9019-11e6-9171-82cf2ce50706.png)
So this request should be updated to include the **new logo**.

Here is the same image vectorized with Inkscape in two versions as a [ZIP file](https://github.com/FortAwesome/Font-Awesome/files/523208/meetup-new-logo.zip) (github does not allow SVG).

meetup-new-logo-vector.svg is the standard one
meetup-new-logo-invert-vector.svg is the complementary (inverse colors)

Feel free to use them for generating the font character.

**Comment by AlchemyUnited** [comment]
To @spaeps  point, the new Meetup M should be fairly easy to do.

Yes please... +1

**Comment by davegandy** [comment]
Added to 4.7.0 branch. Closing.
