### ISSUE TITLE
Icon request: file-cv (or file-resume)

### ISSUE THREAD

**Issue by helgebe** [FortAwesome/Font-Awesome#15880]
**What can it be used for?**
Visualization of cv/resume type documents.
There is already file-prescription, file-invoice, file-contract and many more, but not cv
There is an earlier request on this, but it is closed.
https://github.com/FortAwesome/Font-Awesome/issues/3533
and none of the solutions look like a cv, so in my opinion, this does not qualify as a duplicate.

**Example image (optional)**
Stolen from issue https://github.com/FortAwesome/Font-Awesome/issues/3533:
![cv](https://user-images.githubusercontent.com/33450211/69812424-67d42100-11f0-11ea-9620-9d26f61fc206.png)
![cv2](https://user-images.githubusercontent.com/33450211/69812442-6c98d500-11f0-11ea-81a0-59f980dc1a6d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate. 
*( https://github.com/FortAwesome/Font-Awesome/issues/3533 may be a duplicate depending on definition)
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro as per #3533

Also, you can achieve a variation with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/280/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Hope it helps

Closing here
