### ISSUE TITLE
Icon request: Bilibili

### ISSUE THREAD

**Issue by eternityqjl** [FortAwesome/Font-Awesome#15884]
If you can support the icon of Bilibili, a Chinese video website.
https://www.bilibili.com/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #9789, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
