### ISSUE TITLE
Webpack ICON

### ISSUE THREAD

**Issue by ayoubkhan558** [FortAwesome/Font-Awesome#15892]
Webpack ICON is missing, Its needed in brand icons
https://webpack.js.org/
![image](https://user-images.githubusercontent.com/20210961/69985552-3b583600-155d-11ea-8b54-3ee785d1709e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13714, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
