### ISSUE TITLE
cant search icons in your site - No icons found

### ISSUE THREAD

**Issue by farshad-fr4** [FortAwesome/Font-Awesome#15896]
hi dear developer
there is problem in your site https://fontawesome.com
when i search anything just this message comes  "No icons found"

sample search for google icon : https://fontawesome.com/icons?d=gallery&q=google
shows "No icons found"

ty alot

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

Is this still an issue?

If yes, could you please check if the browser's development console is showing errors?

**Comment by farshad-fr4** [comment]
hi again ,
its fixed now , ty

**Comment by tagliala** [comment]
you're welcome, closing here
