### ISSUE TITLE
FA blocks bigger company websites, small unknown websites are not blocked.

### ISSUE THREAD

**Issue by ErnestPH** [FortAwesome/Font-Awesome#15909]
**Describe the bug**
Using the icon won't work if BIG companies are in the link ex. Facebook, Google, Apple... not only social media
**To Reproduce**
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_social_media_buttons
- Just change the URL to well-known companies. and compare to unknown websites.
Unknown websites are not blocked.
`<a href="https://facebook.com/"><i class="fa fa-facebook"></i></a>`

**Expected behaviour**
When clicking the icon it should open the URL and load the site whether big or small companies

**Screenshots** 
I have a video
https://www.loom.com/share/0fea5ba9402044d69d9edce3232a2d12

Probably this is similar to this case, https://github.com/FortAwesome/Font-Awesome/issues/15342

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is related to third-party ad-blocking plugins

Ref: #1799

**Comment by ErnestPH** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> I think this is related to third-party ad-blocking plugins
> 
> Ref: #1799

Thanks for the reply -maybe it's related but it's a different scenario. Icons are actually displaying well but we're not clickable. (when I tested it on my website).

But when tested on w3c, icons we're clickable but website links won't load (please see loom video)

**Comment by tagliala** [comment]
Hi, thanks for sharing the code

Please note that:

- The example is using  FA 4.7, which is in EOL
- The example is using an approach that is not suggested. We advise to use `<i>` (or a more semantically appropriated `<span>`) tags inside anchors

**Comment by ErnestPH** [comment]
Ok I am closing this one now... I think this has to do with Paid versions. Thanks
