### ISSUE TITLE
Duotone Icons loose the opacity part of the icon

### ISSUE THREAD

**Issue by cmumbert** [FortAwesome/Font-Awesome#15904]
**Describe the bug**
Duotone icons look great until I force the page into a responsive state. Then the light opacity disappears completely and the spinning version gets wonky and also loses the light opacity part of the icon.

**To Reproduce**
https://timothyplan.com/

Reduce the page width and you will see what happens.

**Expected behavior**
I would like the icons to like they do in the regular width of the page.

**Screenshots**
https://prnt.sc/q6a5bs (regular functioning icons)
https://prnt.sc/q6a5zj (wonky icons)

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are problem in `responsive.css`:

```css
.top-nav > ul > li > a i:after {
	display: none
}
```

The above rule is hiding the secondary part of duotone icon below `1070px` and it is duplicated below `1050px`

![image](https://user-images.githubusercontent.com/556268/70183469-28bd3880-16e6-11ea-8808-00dfb40c8e05.png)


PS: please optimize contents of that website, it is eating a lot of CPU and makes my fans spin

![image](https://user-images.githubusercontent.com/556268/70183158-84d38d00-16e5-11ea-8ea9-72a793f0f694.png)

Hope it helps

Closing here
