### ISSUE TITLE
Icon request: Amazon Alexa

### ISSUE THREAD

**Issue by samsethi** [FortAwesome/Font-Awesome#15901]
**What can it be used for?**
I would use it on my website to link to my Alexa Skill and my Flash Briefing

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13452, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
