### ISSUE TITLE
Icon request: Musical instruments / cables / Jacks

### ISSUE THREAD

**Issue by krstf** [FortAwesome/Font-Awesome#1590]
Greetings from Prague : )
I would love to ask for more specific music related icons. If you happen to have some spare time, i'll be happy for those!! Let me know on www.krstf.com what could i do in repay since i want quite a few of those!! 

Thanks mate!!

Icons I would really really need : 
- Drums
- Guitar
- Bass guitar
- Keyboards
- XLR cable
- Cinch cable
- Mini Jack
- Big Jack

**Comment by hetzijzo** [comment]
+1

**Comment by dimwit91** [comment]
+1

**Comment by billshannon** [comment]
+1 Be great to have some musical instrument icons. Thanks!

**Comment by nagulian** [comment]
+1

**Comment by peiche** [comment]
+1

**Comment by Elorfin** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by lfzawacki** [comment]
+1

**Comment by ocruz** [comment]
+1

**Comment by mcfadden** [comment]
+1

**Comment by tcbmedia** [comment]
+1

**Comment by KevinArturia** [comment]
+1

**Comment by damusix** [comment]
+1

**Comment by tso-unlimited** [comment]
+1

**Comment by aethior** [comment]
Currently there are many [Music & Audio](https://fontawesome.com/icons/categories/music-audio) icons.
Isn't it better to use individual suggestions?

cc/ @tagliala

**Comment by billshannon** [comment]
Wow, six years ago, nice! Yes some have been added. How about clefs also - treble and bass. Bass instruments - bass guitar - p or j bass and double bass would be welcome in the collection. Thanks!

**Comment by tagliala** [comment]
> Isn't it better to use individual suggestions?

Absolutely!

This is an ancient request, a lot of icons have been implemented in this category. New icons should be individually requested for better tracking 

We have a fancy new template here: https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+

Closing here
