### ISSUE TITLE
An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.8/react-fontawesome-0.1.8.tgz: Request failed \"502 Bad Gateway\"".

### ISSUE THREAD

**Issue by esetnik** [FortAwesome/Font-Awesome#15919]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
52 error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.8/react-fontawesome-0.1.8.tgz: Request failed \"502 Bad Gateway\"".

**To Reproduce**
add to package.json
```
    "@fortawesome/fontawesome-svg-core": "1.2.25",
    "@fortawesome/pro-light-svg-icons": "5.11.2",
    "@fortawesome/pro-regular-svg-icons": "5.11.2",
    "@fortawesome/pro-solid-svg-icons": "5.11.2",
    "@fortawesome/react-fontawesome": "0.1.8",
```

run yarn install
**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole even if I think we need more data for this issue, could you please follow up? Maybe I can note down what we need and proceed by myself next time

**Comment by robmadole** [comment]
@esetnik we've contacted Cloudsmith and they said that these can sometimes occur when they are deploying changes to their system. How many times did this occur? If this is disrupting your work we'll raise that up to them.

**Comment by robmadole** [comment]
also pinging @deathnfudge on this one

**Comment by esetnik** [comment]
It's happened ~30 times over the last several weeks. It seems bizarre that they'd experience downtime like this every time they deploy changes to their system.

**Comment by robmadole** [comment]
@esetnik I think we have a support thread going with you through email. We'll focus our communication there.
