### ISSUE TITLE
Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack' as of @fortawesome/fontawesome-svg-core@1.2.26

### ISSUE THREAD

**Issue by adambowles** [FortAwesome/Font-Awesome#15927]
**Describe the bug**
Can't add icon packs to library in TypeScript after updating to `@fortawesome/fontawesome-svg-core@1.2.26`
```
Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack'.
  Type 'IconPack' is missing the following properties from type 'IconDefinition': icon, prefix, iconName  TS2345

    1 | import { library } from '@fortawesome/fontawesome-svg-core';
    2 | import { fal } from '@fortawesome/pro-light-svg-icons';
    3 | import { far } from '@fortawesome/pro-regular-svg-icons';
    4 | import { fas } from '@fortawesome/pro-solid-svg-icons';
  > 5 | library.add(fal, far, fas);
      |             ^
```

**To Reproduce**
Updated from `@fortawesome/fontawesome-svg-core@1.2.25` to `@fortawesome/fontawesome-svg-core@1.2.26`

**Version and implementation**
Version: `@fortawesome/fontawesome-svg-core@1.2.26`

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
@adambowles you'll have to provide a reproducible test case that we can actually run locally and debug.

**Comment by elramus** [comment]
I'm running into this too I believe... I think it's a thing with the new firefox icon that was just added. I'm not using it in my project, but it's showing up in an error message right after updating to latest version.

![Screen Shot 2019-12-11 at 3 14 58 PM](https://user-images.githubusercontent.com/24811404/70661032-09179a00-1c29-11ea-9066-850026ea6ad4.png)

**Comment by robmadole** [comment]
I just checked the types for those and they look ok. Happy to work on this if someone can provide a reproduction. Please make sure that you've upgraded the `@fortawesome/fontawesome-common-types` package as well.

**Comment by elramus** [comment]
Thanks @robmadole. Tried to reproduce my error in a fresh environment but it worked perfectly. Then I tried restarting my TS server after these package updates and that fixed the error message 🙃

"Hello IT, have you tried turning it off and on again?"

**Comment by robmadole** [comment]
@elramus no worries! "I'll just put this over here with the rest of...the fire"

**Comment by adambowles** [comment]
Adding `@fortawesome/fontawesome-common-types` to my dependencies fixes it

**Comment by robmadole** [comment]
Good deal :+1:
