### ISSUE TITLE
fas fa-code

### ISSUE THREAD

**Issue by selwynorren** [FortAwesome/Font-Awesome#15923]
This icon has been made considerably thicker than previously in 4.7 and does not match up at all to similar icon like the far fa-heart. Can the fa-code not be made thinner?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is legit,  comparing [fa-code](https://fontawesome.com/icons/code?style=solid) to [fa-brackets-curly](https://fontawesome.com/icons/brackets-curly?style=solid)

@sensibleworld any thoughts?

**Comment by sensibleworld** [comment]
We put the `code` icon on a diet for version 6: https://fontawesome.com/v6.0/icons/code?s=solid
