### ISSUE TITLE
Freelancer.com, Upwork, Fiverr icons requested

### ISSUE THREAD

**Issue by ankitkanojia** [FortAwesome/Font-Awesome#15926]
Hi there, you're doing well. Thank you for everything you shared.

just need to request new icons for Freelancer.com, Upwork, Fiverr if as soon as possible.

Thank you in advanced.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Freelancer.com is a duplicate of #6426, please add a 👍 reaction to that request.
Upwork is a duplicate of #6537 , please add a 👍 reaction to that request.
Fiverr is a duplicate of #fiverr , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

All duplicates, closing here

If you are interested in how requests work, take a look at our [Brand Icons Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)
