### ISSUE TITLE
Improve Caravan Regular Icon

### ISSUE THREAD

**Issue by chandanndeep** [FortAwesome/Font-Awesome#15932]
**Describe the bug**
Door handle placement is wrong. Merge with door. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/17069784/70685541-bd6bfb80-1ccf-11ea-8769-29fd0b12b18c.png)
https://fontawesome.com/icons/caravan?style=regular

**Expected behavior**
I have created a draft.
![image](https://user-images.githubusercontent.com/17069784/70685765-5ac72f80-1cd0-11ea-8fd5-b8aa787df780.png)

**Version and implementation**
Version: 5.12.0

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I do not think that the placement is wrong, but I'm going to ask @sensibleworld some thoughts

**Comment by chandanndeep** [comment]
Thanks you @tagliala

**Comment by sensibleworld** [comment]
Thanks for the report @chandanndeep. This was a design decision we made to keep the handle closer to the side of the door, as opposed to the center. As you can see, we don't have a ton of space to work with in the regular style. We'll likely keep it as is for now, but I'll certainly consider an update in the future.
