### ISSUE TITLE
Icon request: insert

### ISSUE THREAD

**Issue by doubledeej** [FortAwesome/Font-Awesome#15931]
**What can it be used for?**
Used to add an item into the middle of an existing collection

**Example image (optional)**

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example?

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by doubledeej** [comment]
I don't have an example, but I'd imagine it to be a series of horizontal bars (representing a list of items) with an arrow/triangle to the left pointing into the stack to show that something is being inserted into the middle of the list.

**Comment by aethior** [comment]
Hi @doubledeej,

Something like https://fontawesome.com/icons/indent?

Regards.

**Comment by doubledeej** [comment]
Similar, yes. But the horizontal lines would all be the same size.
