### ISSUE TITLE
Icon request: icon-cloverleaf

### ISSUE THREAD

**Issue by meerderideen** [FortAwesome/Font-Awesome#1593]
Hello,

I would like to see a cloverleaf icon in Awesome Fonts. Why? For example for contests. I am doing contests sometimes and would like to put a cloverleaf right beside the text "contest".

Is that possible? A nice cloverleaf :-)

**Comment by fyyyyy** [comment]
+1

**Comment by nbmiller28** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by flaviaspaula** [comment]
+1

**Comment by meerderideen** [comment]
I guess it will never be released. Too hard to do, I guess. I mean, a cloverleaf needs high-end skills, right?... Yeah. Closing this thread after more than 1 year.

**Comment by tagliala** [comment]
@meerderideen Sorry.

I'm going to reopen here for the other people who +1'd this icon. The advice of considering a custom build is always valid: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by meerderideen** [comment]
Interesting...

**Comment by gEndelf** [comment]
+1

**Comment by RPiAwesomeness** [comment]
+1

**Comment by TerraPrime** [comment]
+1

**Comment by FluffyPancakes** [comment]
+1

**Comment by RandomArray** [comment]
+1

**Comment by Kellamity** [comment]
+1 4 leaf clover. Surprised it's not in there, it's a very common emoji.

**Comment by otoman** [comment]
+1

**Comment by pierreavinain** [comment]
+1

**Comment by brucesantos** [comment]
🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀

**Comment by brucesantos** [comment]
where's it? since 2013... not upvoted enough? what's the deal?

**Comment by tagliala** [comment]
@brucesantos please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), there is a lot of information on how requests work

**Comment by brucesantos** [comment]
Already did. All requests for the clover are close and reference each other.

----

Um abraço,

Bruno Santos
(15) 99118-5772

**Comment by brucesantos** [comment]
the opened one is the one I’ve commented on…


----

Um abraço,

Bruno Santos
(15) 99118-5772

**Comment by giopebero** [comment]
Example: ![image](https://user-images.githubusercontent.com/7444191/96130680-8de1dd00-0ef8-11eb-9d1f-cce45697857f.png)
It symbolizes luck!

**Comment by mrighelli** [comment]
+1

**Comment by giopebero** [comment]
> +1

+1

**Comment by giopebero** [comment]
> +1
> Maybe an example:
> ![leaf](https://camo.githubusercontent.com/7cbb692a43f40bb1cbbd06b29f90c2d382be4cc9/68747470733a2f2f692e70696e696d672e636f6d2f363030783331352f65622f36632f63642f65623663636431333035623837373635303631633364646134343039653935372e6a7067)
> Thank you !! :)

+1

**Comment by mrighelli** [comment]
> Example: ![image](https://user-images.githubusercontent.com/7444191/96130680-8de1dd00-0ef8-11eb-9d1f-cce45697857f.png)
> It symbolizes luck!

Nice example

**Comment by giopebero** [comment]
> +1
> 
> 4 leaf clover symbolizes luck, irish, St. Patrick's day.

+1

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
