### ISSUE TITLE
Icon request: icon-male-female

### ISSUE THREAD

**Issue by gijsfijn** [FortAwesome/Font-Awesome#15941]
**What can it be used for?**
Marriage, wedding, dating (couple)

**Example image (optional)**
<img width="73" alt="Schermafbeelding 2019-12-12 om 14 54 26" src="https://user-images.githubusercontent.com/5747154/70717798-60803d80-1cef-11ea-8a59-4238e6817cb3.png">

Gijs

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Even if we prefer to use gender neutral icons to represent users, we have `user-male` and `user-female` that could fit this use case

**Comment by gijsfijn** [comment]
I agree, but sometimes we need a combined icon for a couple (dating business)

**Comment by aethior** [comment]
Hi @gijsfijn,

This icon was added in v6.0.0.
Check https://fontawesome.com/icons/people

Regards.

cc/ @tagliala
