### ISSUE TITLE
Icon request: icon-amusement-ride (roller coaster or carousel)

### ISSUE THREAD

**Issue by CODECRATER** [FortAwesome/Font-Awesome#15950]
**What can it be used for?**
Used to show roller coasters or amusement park rides

**Example image (optional)**
https://i.imgur.com/VDSPf9P.png
A carousel might work well.

**Icon request checklist**
- [ ✔️] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔️ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔️ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✔️ ] I have included at least one example image if it could be helpful (optional)
- [✔️ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by padoko** [comment]
would love such icons!

**Comment by caassandra** [comment]
Looks like this was asked for almost [a decade ago](https://github.com/FortAwesome/Font-Awesome/issues/336), but I think the example images make it seem like this is doable :)

**Comment by sensibleworld** [comment]
<img width="690" alt="Screen Shot 2021-03-30 at 12 09 09 PM" src="https://user-images.githubusercontent.com/529604/113020594-bc730d80-9150-11eb-9798-28e708bdd18c.png">
<img width="695" alt="Screen Shot 2021-03-30 at 12 09 18 PM" src="https://user-images.githubusercontent.com/529604/113020621-c1d05800-9150-11eb-85f3-704dc238a31d.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
