### ISSUE TITLE
Linkedin-in icon not showing up

### ISSUE THREAD

**Issue by gquinsey** [FortAwesome/Font-Awesome#15951]
**Describe the bug**
The linkedin-in icon isn't rendering, either on my site or on FontAwesome's search.

**To Reproduce**
https://fontawesome.com/icons?d=gallery&q=linkedin

Icon name appears in search, but not icon.

**Expected behavior**
Would like preview of icon and icon to appear on site.

**Screenshots**
![Screen Shot 2019-12-16 at 10 56 52 AM](https://user-images.githubusercontent.com/57100133/70921840-0df69800-1ff3-11ea-919a-e59e165d68c5.png)

**Version and implementation**
Version: 4
Browser and version: Chrome

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This may be ad-block related #1799

**Comment by gquinsey** [comment]
Hi!

Thanks for getting back to me! You’re right, it is because of ad block. Is there a work around?

**Comment by tagliala** [comment]
> Is there a work around?

We decided to not take actions and play cat and mouse game

You can rename the linkedin class to something else and use the alias, or report this issue to the list of your adblocker of choice

**Comment by slawa-dev** [comment]
> Is there a work around?

Don't use block-lists that block harmless icons.

**Comment by tagliala** [comment]
Closing here
