### ISSUE TITLE
Parent font-weight makes fab icon look bad

### ISSUE THREAD

**Issue by febLey** [FortAwesome/Font-Awesome#15952]
**Describe the bug**
I've got a button containing a link, which contains a brand icon.
The button has a font-weight of 700. Because of that the brand icon looks off.

**To Reproduce**
Have a look: https://jsfiddle.net/febLey/aqc34kpf/2/

**Expected behavior**
The brand icons shouldn't be affected by the parents font-weight.
This could be fixed by setting a `font-weight: 400` on the `.fab` class.
Similar to the other Fontawesome icon classes.
Although I'm sure if this change would affect other brand icons.

**Version and implementation**
Version: 5.12.0
Browser and version: Chrome 79, Safari 13.0.4, Firefox 71.0

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

The font-weight is set in the font-face but not in the class itself, I also think there is an issue

@robmadole could you please take a look?

**Comment by robmadole** [comment]
I think we can set this explicitly. That would help! Thanks @febLey. We'll get this fixed in the next version of FA.

**Comment by febLey** [comment]
What happend to this, was it fixed?

**Comment by tagliala** [comment]
Reopening here for tracking purposes. @febLey this has been fixed internally but not yet released

**Comment by tagliala** [comment]
This has been fixed in 5.12.1
