### ISSUE TITLE
Feature request: Filter *out* BRANDS would make the gallery 438 times better

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [FortAwesome/Font-Awesome#15967]
**Is your feature request related to a problem? Please describe.**
On the gallery page of icons here
https://fontawesome.com/icons?d=gallery

As a developer it's very difficult to peruse the full gallery of icons and choosing for various purposes because there are trademarked brand icons all over the place.  
The general useful icons are all mixed up with trademarked branded icons.
It would be trivially easy to pick a nice looking icon for a purpose only to receive a cease and decist letter later in the mail for this mistake.

**Describe the solution you'd like**
I would like to see a checkbox to filter *OUT* all brands from the list or see the brands just not included in the default full gallery view.

**Feature request checklist**
- [X ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ X] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by uberfuzzy** [comment]
Doesnt just using the existing filtering in the sidebar, and click the 4 groups and not brand (thus leading to https://fontawesome.com/icons?d=gallery&s=duotone,light,regular,solid ) do this?

**Comment by WhatFreshHellIsThis** [comment]
Convoluted but yes it does.  I would still like to see a simple one click option for the same thing or more ideally for correct UI design no brands at all unless you check it which is the inference most people would make when they see it as an option right up front like that.  A very tiny minority of people using this are looking for brands specifically surely you agree on that?

**Comment by sensibleworld** [comment]
Our new icon search for v6 is more geared towards this and allows much easier sorting: https://fontawesome.com/v6.0/icons?s=solid%2Cbrands
