### ISSUE TITLE
Icon Request: Repo Specific Icons

### ISSUE THREAD

**Issue by lawloretienne** [FortAwesome/Font-Awesome#1596]
So I noticed that there is one icon 'icon-code-fork' that is specific to a repository action.  Are there any more repository specific action icons such as pull, merge, push, ...?

**Comment by tduchateau** [comment]
+1
+ an icon to illustrate a "repository" :-)

**Comment by sensibleworld** [comment]
<img width="721" alt="Screen Shot 2021-03-30 at 1 31 01 PM" src="https://user-images.githubusercontent.com/529604/113030999-2c3ac580-915c-11eb-9d06-5f6374463a0a.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
