### ISSUE TITLE
Adobe font f778

### ISSUE THREAD

**Issue by WebbWear** [FortAwesome/Font-Awesome#15968]
The font is not showing, all other fonts are showing on site. Is this icon still supported?

Adobe font f778

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorrym can't get this issue. Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) ?

**Comment by tagliala** [comment]
No feedback, closing here
