### ISSUE TITLE
All fonts display except Adobe f778

### ISSUE THREAD

**Issue by WebbWear** [FortAwesome/Font-Awesome#15969]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
When I use the font f778 it does not display, all other icons do.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.  https://jsfiddle.net/webbwear/3odLksp9/5/

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
To look like the icon, not a square.

**Screenshots**

<img width="725" alt="Screen Shot 2019-12-19 at 10 06 33 AM" src="https://user-images.githubusercontent.com/33703149/71184233-6d4ce600-2247-11ea-90cc-f2f529dfd921.png">

**Version and implementation**
Version: 
Browser and version: 
Google Chrome

- [ x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ x] I have filled out as much of the above information as I can
- [x ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please note that the demo is using an approach that is not suggested for Font Awesome, so if you have special needs you should fix them by custom css / javascript

If you need to work with unicode points or pseudoelements, please note that we have different font names (`"Font Awesome 5 Brands"`, `"Font Awesome 5 Free"`) as well ass different font weights. THe proper font name for Brands is `"Font Awesome 5 Brands"`, you should not use Font Awesome.

Also, the `gem` comes from Font Awesome Regular, so the proper font name is `"Font Awesome 5 Free"`

Ref: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here
