### ISSUE TITLE
Icon request: Sidebar layout

### ISSUE THREAD

**Issue by brennvs** [FortAwesome/Font-Awesome#15963]
**What can it be used for?**
For sidebar functionality.

**Example image (optional)**
https://icons.getbootstrap.com/

- Layout sidebar reverse
- Layout sidebar 

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by fpstidston** [comment]
Controlling on screen panels is an essential purpose for an icon

**Comment by aethior** [comment]
Hi @brennvs,

[**fa-sidebar**](https://fontawesome.com/icons/sidebar) and [**fa-sidebar-flip**](https://fontawesome.com/icons/sidebar-flip) icons were added in v6.0.0.

Regards.

cc/ @tagliala
