### ISSUE TITLE
Require Js Error

### ISSUE THREAD

**Issue by apomili** [FortAwesome/Font-Awesome#15965]
**Describe the bug**
Fontawesome kit raise a require error (blocking other scripts).
This is a new error, no problem last days. This morning I was investigating and seems that sometimes this files response with different content

https://kit.fontawesome.com/ae2ee3ba6f.js

[correct.txt](https://github.com/FortAwesome/Font-Awesome/files/3979665/correct.txt)
[error.txt](https://github.com/FortAwesome/Font-Awesome/files/3979666/error.txt)

**To Reproduce**
https://www.savetheduck.it/   

Open the console and found a big JS error starting with

Uncaught Error: Mismatched anonymous define() module: function(){"use strict";function t(e){return(t="function"==typeof Symbol&&"symbol"==type ...

**Comment by apomili** [comment]
Sorry, I had to do a local copy of the file to avoid the error that cause too much troubles on the production site.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply

Is this still an issue?

**Comment by apomili** [comment]
Hi @tagliala 
seems to work now.

**Comment by tagliala** [comment]
Thanks for letting me know!

Closing here. Feel free to comment if this comes up again
