### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by gitmendy** [FortAwesome/Font-Awesome#15975]
**What can it be used for?**
Web/Admin Dashboard .

**Example image (optional)**
https://www.flaticon.com/free-icon/home_1035850?term=dashboard&page=1&position=16
https://www.flaticon.com/free-icon/dashboard_2172161?term=dashboard&page=1&position=19

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The provided examples are too complex to fit in a 16x16 icon size. Do you have something simpler in mind?

We also need to fix the title to match contributing guidelines

**Comment by aethior** [comment]
Related or duplicated of #16889?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
