### ISSUE TITLE
Google Chrome jumps to the top of the page on DOM manipulation

### ISSUE THREAD

**Issue by adeeb1** [FortAwesome/Font-Awesome#15970]
Font Awesome rendering method: SVG with JS
Google Chrome version (Windows 10): 79.0.3945.88 (Official Build) (64-bit)

I originally posted the issue [here](https://github.com/tomkra/font_awesome5_rails/issues/48). Whenever I perform an AJAX request and the response manipulates the DOM with HTML that contains an icon, Google Chrome jumps to the top of the page as if it's performing a page reload. This creates a poor user experience.

I switched to loading Font Awesome with Webfonts, and I no longer experience the issue, so the issue lies somewhere in the JavaScript. I've tried changing the `mutateApproach` configuration setting to both `async` and `sync` to no avail. I also do not experience this issue on other browsers.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reduced test case for this issue?

**Comment by adeeb1** [comment]
This is actually an issue with another package. See comment: https://github.com/tomkra/font_awesome5_rails/issues/48#issuecomment-588158725
