### ISSUE TITLE
Icon request: trailer

### ISSUE THREAD

**Issue by cbezzy** [FortAwesome/Font-Awesome#15972]
**What can it be used for?**
Trailer Icon For transport industries

![image](https://user-images.githubusercontent.com/20892051/71198684-55cf2680-2262-11ea-994f-c364095647dc.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a request for a truck trailer at: #15934, please +1 that request

We have also a trailer for FA5 Free: https://fontawesome.com/icons/trailer?style=solid and a truck ramp https://fontawesome.com/icons/truck-ramp?style=solid for FA Pro

Hope it helps

Closing here
