### ISSUE TITLE
Html code to include any icon is giving problems.

### ISSUE THREAD

**Issue by Dakshbarad** [FortAwesome/Font-Awesome#15973]
The one that the site is providing is this:
```<i class="fas fa-plus"></i>```

But for it to work it has to be this:
```<i class="fa fa-plus"></i>```

**fixed by @tagliala**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Maybe you are using an older version of Font Awesome.

`fa` prefix: FA4 and FA5 (deprecated)
`fas` prefix: FA5 only

Please take a look at our documentation https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
