### ISSUE TITLE
Icon request: comments-question-*

### ISSUE THREAD

**Issue by AikoWest** [FortAwesome/Font-Awesome#15985]
I would be happy if you could create the "comment-icon-collection" with a **question mark**.

To express that you are asking a question and not just looking for help. For example in an audit or a questionnaire.

![1](https://user-images.githubusercontent.com/59164153/71348771-959d5300-256d-11ea-84d6-1cae8cae4924.PNG)
![2](https://user-images.githubusercontent.com/59164153/71348772-959d5300-256d-11ea-8dc0-27e2e1786737.PNG)
![3](https://user-images.githubusercontent.com/59164153/71348775-9635e980-256d-11ea-89ad-a295eee08350.PNG)
![4](https://user-images.githubusercontent.com/59164153/71348776-9635e980-256d-11ea-887c-9ade69abd218.PNG)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/295/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by AikoWest** [comment]
Hi!

Thanks for your response.

Power Transforms looks like an awesome feature, but is there a way or tutorial how you can use it in Xamarin?

Currently I am using FontAwesome for my Xamarin.Android project like this:

[Ein Bild, das Screenshot enthält.  Automatisch generierte Beschreibung]

[cid:image002.png@01D5C9DF.3691C330]


Best regards,
Aiko



Aiko Westmeier
Softwareentwicklung BITqms

Telefon: +49 (0) 6078 78059-478
E-Mail: aiko.westmeier@bitworks.net

Optimale Unterstützung für Ihre Unternehmensprozesse.
Einfach. Flexibel. Effizient. Zuverlässig.

[cid:bitqms-200-pixel-breit_c6c6734b-a71b-4864-81e4-96a6bc69a8591.png]



NEU: Entdecken Sie PizzBlitz<https://www.pizzblitz.de/> - Management mit System
[cid:PizzBlitzLogo_9aac18c2-0a35-4062-95ce-06c3a1e8944f.jpg]<https://www.pizzblitz.de/>
Ein Gemeinschaftsprojekt der QZ-Online<https://www.qz-online.de/specials/pizzblitz> und BITWORKS.

Anhand der Story über die Freunde Marius und Luisa erklären wir Ihnen einfach und pragmatisch, den Umgang mit BITqms.
Es werden Beiträge veröffentlicht zu Themen wie der Aufbau der Dokumentation, Prozesse, Workflows, Mitarbeiter-, Standort-, Kunden- und Lieferantenmanagement, Begehungen, Audits, Maßnahmen, elektronische Formulare, Portale etc.
Alles muss gemeistert werden, ohne die Motivation und den Spaß aus den Augen zu verlieren.

BITWORKS EDV-Dienstleistungs GmbH · Dörrwiesenweg 23, 64823 Gross-Umstadt · Wittichstrasse 7, 64295 Darmstadt · www.bitworks.net<http://www.bitworks.net>
Geschäftsführung: Helmut Habermann, Dipl.-Informatiker; Frank Effenberger, Dipl.-Informatiker | Eingetragen beim Amtsgericht Darmstadt, HRB 33131, USt.-ID: DE 163737418
Von: Geremia Taglialatela <notifications@github.com>
Gesendet: Montag, 6. Januar 2020 10:13
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Cc: Aiko Westmeier <westmeier@bitworks.net>; Author <author@noreply.github.com>
Betreff: Re: [FortAwesome/Font-Awesome] Icon request: comments-question-* (#15985)


Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/295/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tagliala** [comment]
> Power Transforms looks like an awesome feature, but is there a way or tutorial how you can use it in Xamarin?

Sorry, I think they are not available on Xamarin

**Comment by tagliala** [comment]
Available in FA6 Pro https://fontawesome.com/v6.0/icons?q=question&s=solid%2Cbrands

**Comment by OlsonDev** [comment]
Hi, I couldn't find it elsewhere, but I was wondering if we could get a `comments-question-xmark` icon added to this collection? My use-case is someone proposes a change to an organization's settings, and then someone else rejects it -- and this kind of icon would be a historical "it was rejected" whereas the "check" would be "it was accepted".

If you'd like me to create another issue, let me know. :-)

Thanks!

**Comment by tagliala** [comment]
Hi @OlsonDev , feel free to open a new request by filling in our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
