### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by smegee** [FortAwesome/Font-Awesome#15980]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
1up - player1 player2 - / every 80's 90's website ever...
**Example image (optional)**
Insert the example image here if necessary.
**1up**
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by smegee** [comment]
...if you have ever player a video game / board game / multiplayer game... this is pretty straight forward..

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, could you please clarify this request?

Any single-color, 16px icon size suitable example is good

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
