### ISSUE TITLE
Пожалуйста.

### ISSUE THREAD

**Issue by Garik908** [FortAwesome/Font-Awesome#15994]
Прошу изготовить иконку вентилятора. Три лопасти. Спасибо!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per google translate,

> Please make a fan icon. Three blades. Thanks!

We have a [4 blade fan](https://fontawesome.com/icons?d=gallery&q=fan), any particular reason why that icon does not fit your use case?

We have also a fan table in FA Pro: https://fontawesome.com/icons/fan-table?style=solid

**Comment by Garik908** [comment]
Thank you for answering! The fan you suggested doesn't fit into MajorDomo, another extension. Icons only work with Font Awesome 4.7.0. http://fontawesome.ru/all-icons/28.12.2019, 12:58, "Geremia Taglialatela" <notifications@github.com>:Hi!
Thanks for being part of the Font Awesome Community.
As per google translate,

Please make a fan icon. Three blades. Thanks!

We have a 4 blade fan, any particular reason why that icon does not fit your use case?
We have also a fan table in FA Pro: https://fontawesome.com/icons/fan-table?style=solid

**Comment by tagliala** [comment]
> Icons only work with Font Awesome 4.7.0.

Hi, unfortunately FA 4.7.0 is in EOL, please ask MajorDomo developers to update to FA5

Hope it helps

Closing here
