### ISSUE TITLE
Icon request: fa-fishbone

### ISSUE THREAD

**Issue by crtmneric** [FortAwesome/Font-Awesome#15990]
**What can it be used for?**
We are trying to develop a web based application which has a topic about occupational health and safety and we have lots of analysis sections. Ishikawa analysis is the one of the most used methods in these kind of applications. It's actually a fishbone diagram so we need a fishbone icon.

Describe how this could be used / the use case for this icon.
We want to make a button with fishbone icon ( 🐟 Ishkawa Analysis ) 
**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/16175654/71399042-749f3580-2633-11ea-921a-0bac50eedd35.png)

**Icon request checklist**
- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✔] I have included at least one example image if it could be helpful (optional)
- [✔] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> for [4.7.0]

Sorry, is this a request for FA 4.7.0? If yes, Font Awesome 4 is in EOL

Also, the example is way too complex to play well with small icon size.

Is this a request for a simple fishbone, like this

![image](https://user-images.githubusercontent.com/556268/71399773-06537680-2625-11ea-944a-996d6dc6ce5c.png)


or a fishbone-diagram like this?

![image](https://user-images.githubusercontent.com/556268/71399786-12d7cf00-2625-11ea-89e3-5befb18f4951.png)

**Comment by crtmneric** [comment]
Hi there,
thank you for creating awesome icons! actually i wrote that 4.7.0 for version 4.7 but it's okay to add this updated versions specially the bottom diagram icon is good for our stuation but it will be better if we add the **classic fish bone icon like in the first image.** Beacuse diagram is much more spesific, it will be more useful if we add the first fishbone.

**So yes simple one will be awesome ! :)**

**Comment by tagliala** [comment]
@crtmneric you're welcome, and thanks for the clarification.

I will add the food category

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/fish-bones?s=solid
