### ISSUE TITLE
Error deploying free version to production: NPM requires http basic auth

### ISSUE THREAD

**Issue by aforty** [FortAwesome/Font-Awesome#15998]
**Describe the bug**
I can't seem to deploy my project to our server on DigitalOcean. When I do and it installs all the packages through yarn I get the following error:

```
An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.12.0/fontawesome-free-5.12.0.tgz: Request failed "401 Unauthorized"".
```

I do not have an `.nvmrc`. I simply added the package via `yarn add @fortawesome/fontawesome-free`.

I can confirm that if I try to access it via browser I am prompted for http basic auth.

**To Reproduce**
Try to open this URL in your browser: [https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.12.0/fontawesome-free-5.12.0.tgz](https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.12.0/fontawesome-free-5.12.0.tgz)

**Expected behavior**
The NPM repository probably shouldn't be behind an auth wall.

**Comment by aforty** [comment]
Nevermind. I fixed it by removing the package and re-adding it. However judging by the number of issues people have had with this it might be worth looking into why this keeps happening. I'd be happy to provide details from my environment to help out.

**Comment by tagliala** [comment]
> why this keeps happening

I think it is because your configuration is trying to get the free package from our private npm repository `npm.fontawesome.com` instead of the public `registry.yarnpkg.com`.

It could depend on old `.npmrc` configurations

Glad you sovled, closing here

**Comment by aforty** [comment]
@tagliala I guess the issue was that I had an npmrc setup to use pro on one project but then when I tried to use free on another this happened. I'm not sure there's a way around this but maybe worth looking into, or at least putting a warning there for pro users who are following instructions.

**Comment by tagliala** [comment]
@aforty if the `.npmrc` files are per-folder, you should be able to use different FA Free and FA Pro on different projects.

The problem may be when you switch from Pro to Free in the same project without uninstalling / installing again
