### ISSUE TITLE
font-family "Font Awesome 5 Free" in CSS Pseudo-element doesn't work

### ISSUE THREAD

**Issue by mathieuprog** [FortAwesome/Font-Awesome#15992]
I tried the CSS below to show the solid caret-right icon
(https://fontawesome.com/icons/caret-right?style=solid)

```
content: "\f0da";
font-family: "Font Awesome 5 Free";
font-weight: 900;
```

It shows a square; however, if I replace Free by Pro in the font name, the caret shows up:

```
content: "\f0da";
font-family: "Font Awesome 5 Pro";
font-weight: 900;
```

As a potential customer, this scares me off honestly as the icons were appearing for a long time but suddenly noticed the squares, which makes my site look unprofessional if it were to be in production already.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  if I replace Free by Pro in the font name, the caret shows up:

I think that you are using kits. This was a known issue, but it has been fixed: #15137

Could you please try with the latest version of kit or provide a reproducible test case?

**Comment by mathieuprog** [comment]
Below my _kit_ is written:
Font Awesome Free
Latest version (when hovered appears 5.12.0)

Do you have a Codepen or other playground available which uses kits so that I can reproduce the error?

**Comment by tagliala** [comment]
> Do you have a Codepen or other playground available which uses kits so that I can reproduce the error?

Supposing that you are using CSS: https://jsfiddle.net/tagliala/xjazof9w/28/

Please note that instructions for pseudo-elements and SVG are different: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements#with-svg-js (and it is advised to avoid this combination)

**Comment by mathieuprog** [comment]
The fiddle you provided displays a square for me; tried on Chrome and Firefox, latest versions.

**Comment by mathieuprog** [comment]
Pasted the link to a friend who is not a Font Awesome user, and he sees a square as well (that was just to make sure it is not some obscure caching/version issues my side).

**Comment by tagliala** [comment]
Ok, thanks, I was able to reproduce. It was using the font installed on the system

@mathieuprog so apparently #15137 has not been fixed yet. I can clearly see `Pro` in the font definition again.

Please keep using the workaround, I will reopen the other issue

**Comment by mathieuprog** [comment]
Thank you. Can I take advantage of this chat and ask you a very quick question: how is my kit code linked to only my website? Can someone can take my kit link, and use up all my quota?

**Comment by tagliala** [comment]
You're welcome.

Sorry, since I'm not 100% sure of the answer let's ask @robmadole 

>  how is my kit code linked to only my website? Can someone take my kit link, and use up all my quota?
