### ISSUE TITLE
13 Icon Suggestions: Based on needs of web apps/sites

### ISSUE THREAD

**Issue by buraktuyan** [FortAwesome/Font-Awesome#16]
Here are some icon suggestions for you to review - along with a small description of why they would be needed in a web app :
- ~~man: For gender variety to the user icons.~~ #475
- ~~woman: For gender variety to the user icons.~~ #475
- ~~notes: For notes. (There are file and book  but no notes.)~~ #896
- ~~attach: Again, this is very needed for attachments.~~ Done
- ~~history: For version tracking, etc.~~ #895
- ~~charts: For stats, charts, etc. (The current chart icon doesn't look clear on smaller sizes, maybe something without a border?)~~ #171
- ~~adress_book and/or vcard: To represent "contact" or "address book".~~ #898
- ~~unshare: For "undo" or "unshare" operations and to accompany the share/redo icon.~~ #899
- ~~pin: For pinning or sticky commands. (Maybe a simpler and 2D looking one, as an alternative to yours?)~~ newest one is 2D
- ~~envelope_read: To represent an open/read mail.~~ #897
- ~~coin(s): For payment options.~~ #584
- ~~clipboard:~~ icon-paste should do
- ~~calculator~~ #521

Thanks again for your already great work!

**Comment by RetinaInc** [comment]
Skrill & Pay by Skrill icon

**Comment by tagliala** [comment]
@RetinaInc #4668 

:lock: ing here
