### ISSUE TITLE
Feature Request: Balance the plus symbol in file-plus and folder-plus

### ISSUE THREAD

**Issue by dsmmcken** [FortAwesome/Font-Awesome#16004]
**Is your feature request related to a problem? Please describe.**
The file-plus and folder-plus are related icons, that often appear near each other in a UI, yet have annoyingly different visual weighting of the plus, such that it doesn't feel like a cohesive set.

**Describe the solution you'd like**
The folder icon plus should be altered to better match the file icon plus weight or vice versa.

**Describe alternatives you've considered**
Using the solid version, and layering on a plus symbol so scale matches, works but I should be able to just use the default icons.

**Additional context**
![Screen Shot 2019-12-30 at 3 59 28 PM](https://user-images.githubusercontent.com/1576283/71600595-acb7e400-2b1d-11ea-9f6b-def6febff08a.png)

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this suggestion.

@sensibleworld I think it is worth to take a look if we can do something

**Comment by sensibleworld** [comment]
Got this fixed in the 5.12.1 release: https://fontawesome.com/icons/file-plus?style=solid and https://fontawesome.com/icons/folder-plus?style=solid
