### ISSUE TITLE
Icon Request: fa-candy

### ISSUE THREAD

**Issue by aiman-mumtaz** [FortAwesome/Font-Awesome#16009]
Hi there!
I use font awesome to include all my icons in the webpages I make. I was making a candy museum project and it would be nice to have a lollipop or/and a candy icon.
Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #6015, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
