### ISSUE TITLE
Icon request: california

### ISSUE THREAD

**Issue by trymes** [FortAwesome/Font-Awesome#16008]
**What can it be used for?**
I see this as one of a complete set of US state icons. I would envision using it for office locations, service areas, Regional subpages, and such.

**Example image (optional)**
https://www.shutterstock.com/search/california+state+outline

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

For the moment, I'm going to close here for the reasons explained at #3992

Comment: https://github.com/FortAwesome/Font-Awesome/issues/3992#issuecomment-73022665

Hope it helps

Closing here

**Comment by trymes** [comment]
OK, thank you. I have no idea why the issue you linked didn't pop up when I searched.

**Comment by tagliala** [comment]
@trymes you're welcome, don't worry about the search 👍
