### ISSUE TITLE
Icon request: hnetwork

### ISSUE THREAD

**Issue by hacibank** [FortAwesome/Font-Awesome#16001]
**What can it be used for?**
We are a new social network, and we would like users to be able to post our icon on their site

**Example image (optional)**
https://hnetwork.ru/content/themes/default/images/favicon.png

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ +] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [+ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [+ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
The domain ([link](https://hnetwork.ru/)) is currently down.
I can't to find social networks.

cc/ @tagliala
