### ISSUE TITLE
Icon request: scoop.it

### ISSUE THREAD

**Issue by CelebxxCom** [FortAwesome/Font-Awesome#16016]
https://www.scoop.it site icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1603, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
