### ISSUE TITLE
wrong setting icon's class name. 

### ISSUE THREAD

**Issue by pawankushwah850** [FortAwesome/Font-Awesome#16010]
in place  of  `<i` class="fa `fa-cog"></i>` 
 you have written `<i` class="fas `fa-cog"></i>` in your code.

https://fontawesome.com/icons/cog?style=solid

please correct the class name --> `<i` class="fa `fa-cog"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
