### ISSUE TITLE
Icon request: hat-construction

### ISSUE THREAD

**Issue by skylerknight** [FortAwesome/Font-Awesome#16012]
It would be nice if the hard-hat had an alt name related to construction

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> It would be nice if the hard-hat had an alt name related to construction

We dropped alias in FA5. If you need an alias, please consider a custom build

Also, if you search for construction you will see the hard-hat: https://fontawesome.com/icons?d=gallery&q=construction

Hope it helps

Closing here
