### ISSUE TITLE
Icon request : puzzle-pieces-matching, puzzle-pieces-unmatching

### ISSUE THREAD

**Issue by dolibarr95** [FortAwesome/Font-Awesome#16026]
**What can it be used for?**
This icon will be usefull to show compatibility/incompatibility between two item, software,...

**Example image (optional)**

![example](https://user-images.githubusercontent.com/24292300/71823826-77207700-3098-11ea-9ac1-22c64b9d7f7a.png)

For incompatibility we could use two puzzle piece that doesn't match

**Icon request checklist**
- [x] This is a matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is legit, we should rename it puzzle-pieces-matching, puzzle-pieces-unmatching

but...

> This icon will be usefull to show compatibility/incompatibility between two item, software,...

why `check` and `times` do not match this use case? check = compatible, times (or better no icon) = not compatible

Ref: https://www.apple.com/ios/numbers/compatibility/

**Comment by dolibarr95** [comment]
Hi
Tks for this answer
Yes times and check do the job.
But in an industrial (for example) context it more easy to understand (I think).

**Comment by dolibarr95** [comment]
Hi
Tks for the title :)

**Comment by sensibleworld** [comment]
We have a few puzzle icons: https://fontawesome.com/search?q=puzzle&o=r&s=solid
