### ISSUE TITLE
Conflict unicode of `user-robot` icon

### ISSUE THREAD

**Issue by bobmk2** [FortAwesome/Font-Awesome#16028]
**Describe the bug**

I attempted to use `user-robot` icon. But it shows me '屢' character.

The unicode `f94b` of `user-robot` icon will be conflicted.

- Unicode character
  - https://www.fileformat.info/info/unicode/char/f94b/index.htm

Thanks.

**To Reproduce**

```html
<span class="fa">&#xf94b;</span>
```

Sorry, I could not run example code using `pro` fontawesome css at jsfiddle.net. 🙇 
Is there any good way?

**Expected behavior**

I expected `user-robot` icon shown. 🤖 

**Screenshots**

- Regular `user-robot` and Solid `user-robot`

![image](https://user-images.githubusercontent.com/1858949/71869322-068b6000-3155-11ea-9002-5eddd39083b2.png)

- Copy and paste gif at [`user-robot` page](https://fontawesome.com/icons/user-robot?style=solid).

![user-robot](https://user-images.githubusercontent.com/1858949/71869911-3b98b200-3157-11ea-93a9-b10508b05faa.gif)

**Version and implementation**
Version: 5.12.0
Browser and version: Google Chrome (ver.`79.0.3945.88`)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Sorry, I could not run example code using pro fontawesome css at jsfiddle.net. 🙇

I've whitelisted jsfiddle for pro css. Here it is a working test case: https://jsfiddle.net/tagliala/goL9jwe5/2/

**Comment by bobmk2** [comment]
Sorry for wasting your time. :bow:

I can confirm your working test case , and It looks like my local cache was bad.

> I've whitelisted jsfiddle for pro css. 

Thank you for teaching.

**Comment by tagliala** [comment]
no problem, glad you solved 👍
