### ISSUE TITLE
icons are not working properly in html (sublime text 3

### ISSUE THREAD

**Issue by dangerbha1** [FortAwesome/Font-Awesome#16022]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
i just wanna tell you that the icons (in html in sublime text 3) are not working properly in your current version  v5.12.0  .
i.e., class="fas fa-search"

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
so, just replace "fas fa-search" into " fa fa-search" 

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
"fa fa-search"

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> so, just replace "fas fa-search" into " fa fa-search"

Sorry, cannot replicate:

SVG: https://jsfiddle.net/tagliala/puyn0ef8/1/
CSS: https://jsfiddle.net/tagliala/tr0gjszn/1/

Please provide a reproducible test case

Hope it helps

Closing here
