### ISSUE TITLE
Icon Request: cents

### ISSUE THREAD

**Issue by ghusse** [FortAwesome/Font-Awesome#1602]
In a web application, I'd like to use both $ and a ¢ signs.

It'll be really usefull, to let user choose if something is valuable ($, $$ or $$$) or not really (¢).

Plus, it can be used for at least currencies in $ and € 

[Wikipedia article on this sign](https://en.wikipedia.org/wiki/Cent_sign)

**Comment by parampreetGit** [comment]
👍

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
