### ISSUE TITLE
Amex new logo / favicon

### ISSUE THREAD

**Issue by jamabrey** [FortAwesome/Font-Awesome#16024]
**Describe the bug**
Old Logo for Amex icon 

**To Reproduce**
_fab fa-cc-amex_
https://fontawesome.com/icons/cc-amex?style=brands

**Expected behavior**
• Update to logo — See R's and C of [brand update here](https://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_american_express_by_pentagram.php).
• Smaller icon only uses "Amex" — see favicon of [amex site](https://www.americanexpress.com/).

**Screenshots**
See links above for images.

**Version and implementation**
Version: 5.7.0
Browser and version: N/A, but current Chrome version 79.0.3945.88.

- [X] SVG with JS
- [X] Web Fonts with CSS
- [X] SVG Sprites
- [X] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by limmidy** [comment]
+1

Looks like this still hasn't been changed in version 6.0.
It would be awesome if `cc-amex` was updated!

Adding their smaller "AMEX" icon would be a bonus. Maybe as `cc-amex-box` or `cc-amex-square`?

The current Amex logos can be found here: https://about.americanexpress.com/newsroom/media-library/media-library/default.aspx

**Comment by tagliala** [comment]
Oh, completely missed this one

Thanks for the heads-up

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cc-amex?s=brands
