### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by lkcodk** [FortAwesome/Font-Awesome#16038]
Hi FA

Can you add number icons to your archive?

Like
1.
2.
3.
4.

With a circle?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15591, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
