### ISSUE TITLE
@font-face uses an empty font-family in Pro's all.css

### ISSUE THREAD

**Issue by richard-ob** [FortAwesome/Font-Awesome#16034]
In Pro version `5.12.0` the `all.css` file in the Pro files, the `font-family` for the `@font-face` rules is set to an empty value, however this does not seem to be the case in any of the other files (e.g. `solid.css`, `regular.css`).

The results seems to be that in some scenarios (appears to be running locally, so I assume there potentially a `@font-face` or web server nuance here), the Font Awesome webfonts do not get loaded by the browser, seemingly because it doesn't know to load them. Icons just show as the usual blank empty square.

In version `5.12.0-1` of the Free version, I can see that `all.css` does contain populated `font-family` properties.

Excerpt from Pro's `all.css`:
```
@font-face {
  font-family: '';
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }

.fa,
.fas {
  font-family: '';
  font-weight: 900; }
```
Excerpt from Free's `all.css`:
```
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"), url("../webfonts/fa-solid-900.woff") format("woff"), url("../webfonts/fa-solid-900.ttf") format("truetype"), url("../webfonts/fa-solid-900.svg#fontawesome") format("svg"); }

.fa,
.fas {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900; 
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've checked the final versions of FA 5.12.0 on:
- CDN https://pro.fontawesome.com/releases/v5.12.0/css/all.css (this will not work if called directly)
- GitHub source code https://github.com/FortAwesome/Font-Awesome-Pro/blob/master/css/all.css
- Downloaded zip file

and I cannot find the empty font-family declaration.

Could you please provide more details?

**Comment by richard-ob** [comment]
Apologies, I've just re-investigated, and the issue wasn't present in the zip. It looks like I must've somehow unwittingly cleared all of the `font-family` properties in `all.css`. Absolutely no idea how, but can confirm that this is in fact not a Font Awesome issue. 

Sorry to have wasted your time! Not sure how I managed that..

**Comment by tagliala** [comment]
No problem at all, glad you've solved 👍

**Comment by richard-ob** [comment]
I appreciate the prompt response! Thank you!
