### ISSUE TITLE
icon request: fa-pilot (user-with-pilot-hat)

### ISSUE THREAD

**Issue by raindancemedia** [FortAwesome/Font-Awesome#16044]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Aviation related sites
**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

pilot = user with pilot hat?

**Comment by raindancemedia** [comment]
That would be great. I was picturing just a pilot hat like you have for
some other careers but that would also be good. Anything aviation related
would be great.

You have a road one. I thought it would be possibly easy to take make one
like it but runway. Not sure it would translate that small but I think the
lines could just be a little different and it might work? Runway is like
target....could be good for a lot of people? :-)

Also you have plane, jet plane, fighter jet and helicopter. How about a
small plane? Like a cessna type training plane? General aviation kind of
plane. That would be awesome.

Thanks for asking. I know you get a billion requests.

**Comment by mikejmorgan** [comment]
I want to show my support for this icon.  I would use it right away.

**Comment by shaedrich** [comment]
Some suggestions:
![image](https://user-images.githubusercontent.com/11225821/78118776-c3652400-7407-11ea-9751-39b051cd47f3.png)

This could be `fa-pilot-alt`
![image](https://user-images.githubusercontent.com/11225821/78118720-adeffa00-7407-11ea-9958-0832fb4414cb.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons?q=user-pilot
