### ISSUE TITLE
Icon request: trustpilot-star

### ISSUE THREAD

**Issue by shmaltz** [FortAwesome/Font-Awesome#16055]
I am requesting a Trustpilot star icon. Many websites use Trustpilot for their company reviews, just like Yelp, Google and other review platforms. It can be used to display links to a trustpilot review page.

Link for reference: www.trustpilot.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10564, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by shmaltz** [comment]
I did search for it, but did not notice it. Thank you!
