### ISSUE TITLE
Incorrect font-family when using the Kit with the FREE version

### ISSUE THREAD

**Issue by Afif13** [FortAwesome/Font-Awesome#16054]
I registerd to get the Font Awesome kit and when I tried to use pseudo element it wasn't working:

https://jsfiddle.net/rkfmqbLa/2/

To my surprise and when I inspected the CSS code, I found that the font family need to be the Pro one instead of the Free one:

https://jsfiddle.net/rkfmqbLa/3/

As described here: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements the Pro version is only available for Pro users.

This is a bit confusing and I consider it as a "bug" since it's not trivial to know that Pro is the correct font when everything in the Doc state that Free need to be used.

In this file : https://kit-free.fontawesome.com/releases/latest/css/free.min.css we can clearly see thigs like:

@font-face{
  font-family:"Font Awesome 5 Pro";
   font-style:normal;
   font-weight:900;
    src:url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.eot);
    src:url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.eot?#iefix) format("embedded-opentype"),url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.woff2) format("woff2"),url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.woff) format("woff"),url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.ttf) format("truetype"),url(../../../algo/2/webfonts/fa-solid-900-free-5.0.0.svg#fontawesome) format("svg")}

and 

.fa,
.fas {
  font-family: 'Font Awesome 5 Pro';
  font-weight: 900;
}

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the report.

I can confirm, this is a known issue. We are discussing about this at #15137

I'm going to ping Rob there again there
