### ISSUE TITLE
Chrome Reports CrossSite Error

### ISSUE THREAD

**Issue by subrayamallya** [FortAwesome/Font-Awesome#16067]
When rendering a page with FA link in the head, Chrome raises this error in the console - 

>  A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #15643 and has been already fixed, please follow the discussion there.

Solution for already persisted cookies: https://github.com/FortAwesome/Font-Awesome/issues/15643#issuecomment-551365537

Hope it helps

Closing here
