### ISSUE TITLE
Icon Request: fa-shirt

### ISSUE THREAD

**Issue by Magnogen** [FortAwesome/Font-Awesome#16074]
Hello.
I'm making a website for a clothing company, and it would be very helpful to have a shirt icon. I would also need it for a chatbot I'm working on for the UI.

Thanks, Connor.

Idea:
![thB37MIM0F](https://user-images.githubusercontent.com/25611707/72436284-ff3d0580-3797-11ea-82b0-ce4272bca07b.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Here it is: https://fontawesome.com/icons/tshirt?style=solid

Just make sure that you are using Font Awesome 5.10.2 or newer

Closing here
