### ISSUE TITLE
Feature request: Set `font-display` rule to `block` to make Lighthouse happy

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#16077]
**Is your feature request related to a problem? Please describe.**
There is a problem when validating Font Awesome websites using the css. In FA 5.7.0, we have switched to `font-display: auto` to allow users to use (the wrong) `swap` value, but now we have the chance to use `font-display: block` and get rid of the warning

**Describe the solution you'd like**
If we set the default `font-display` to `block`, as agreed in https://github.com/FortAwesome/Font-Awesome/issues/14387#issuecomment-567093531, we can pass the validation without breaking stuff and fix rendering on browsers that do not honor the "similar to the block value" behaviour.

**Describe alternatives you've considered**
Ask users to change the scss files and recompile on our behalf, or override the css

**Additional context**
Ref:
- GoogleChrome/lighthouse#10127
- #14387
- https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by deLisle** [comment]
Looking forward to getting this fixed!

**Comment by guix77** [comment]
Following this

**Comment by MDzyga** [comment]
@robmadole 
Could you release this no later than next Wednesday? My client really need this fix ASAP.

**Comment by tagliala** [comment]
@MDzyga 

> My client really need this fix ASAP.

You can customize the css and host it on your server

Anyway, in my understanding, this fix is just a convention to avoid the lighthouse warning, there are no performance benefits

Ref: https://github.com/GoogleChrome/lighthouse/issues/10127#issuecomment-574794516 (comment by Lighthouse's creator)

**Comment by guix77** [comment]
@MDzyga Could you fix your attitude no later than next Wednesday ? I really need it ASAP.

**Comment by MDzyga** [comment]
Sorry guys, my client has a bit big pressure on audit logs

**Comment by robmadole** [comment]
@MDzyga it never hurts to ask :) The reason that we can't commit to that is that we have a lot of other dependencies that are still up in the air for 5.12.2. While the fix for this is simple, it's just one piece of luggage on a large train with other bags.

**Comment by MDzyga** [comment]
@robmadole I understand.
Do you know how can I set cache and change link rel on preload?
here is my issue with screenshots from lighthouse: https://github.com/FortAwesome/Font-Awesome/issues/16271

**Comment by robmadole** [comment]
@MDzyga I responded in that ticket. Please do not cross-post in other issues to try and get responses. That just clutters up everyone's email and irritates the people who are trying to provide help.

**Comment by tagliala** [comment]
Hi, could you please check 5.13.0?

**Comment by tagliala** [comment]
I've checked myself, looks like it has been fixed

Green: https://tagliala.github.io/fa16077-513.html
Warning: https://tagliala.github.io/fa16077-512.html

Closing here, but free to comment if anything is still wrong

**Comment by oleksandrzaiats** [comment]
> I've checked myself, looks like it has been fixed
> 
> Green: https://tagliala.github.io/fa16077-513.html
> Warning: https://tagliala.github.io/fa16077-512.html
> 
> Closing here, but free to comment if anything is still wrong

Hi!
It seems that the issue still persist when using Font Awesome Wordpress plugin (https://wordpress.org/plugins/font-awesome/). I am using that plugin and I get `Leverage the font-display CSS feature...` in the report from Lighthouse. This warning displays fonts from urls like `https://use.fontawesome.com/releases/v5.15.2/webfonts/fa-**` as affected.
I checked the code of that plugin and it seems like there is no `font-display` set. 
Is it possible to fix that? Thanks!

**Comment by tagliala** [comment]
Hi, I'm not familiar with the official wordpress plugin.

This is the proper repo to report issues: https://github.com/FortAwesome/wordpress-fontawesome

> I checked the code of that plugin and it seems like there is no font-display set. I did not find any issue tracking for that plugin so I decided to write here.

Before opening a new issue, please share your website so I can take a look

**Comment by oleksandrzaiats** [comment]
@tagliala Nice! Thanks for the link.
Here is a url: https://www.la-school.net/

**Comment by robmadole** [comment]
@oleksandrzaiats we have `font-display` set in the CSS. You'll have to take this up with the Lighthouse team as it appears they want `swap`?

**Comment by oleksandrzaiats** [comment]
@robmadole I have looked through the WP plugin and did not manage to find any `font-display` there.
That plugin adds such css where there is no font-display specified:
```
@font-face {
font-family: "FontAwesome";
src: url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.eot"),
		url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.eot?#iefix") format("embedded-opentype"),
		url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.woff2") format("woff2"),
		url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.woff") format("woff"),
		url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.ttf") format("truetype"),
		url("https://${license_subdomain}.fontawesome.com/releases/v${version}/webfonts/fa-brands-400.svg#fontawesome") format("svg");
}
```

**Comment by robmadole** [comment]
@oleksandrzaiats ah thank you. I was able to find it with that. I will get a PR in the Wordpress plugin repo for that.

**Comment by oleksandrzaiats** [comment]
@robmadole Great, thanks! Actually I have create an issue there already https://github.com/FortAwesome/wordpress-fontawesome/issues/108.
I think you know it, but just in case, there are multiple constructions (like I mentioned) in the plugin that should be fixed.

**Comment by ma-deldari** [comment]
> I've checked myself, looks like it has been fixed
> 
> Green: https://tagliala.github.io/fa16077-513.html
> Warning: https://tagliala.github.io/fa16077-512.html
> 
> Closing here, but free to comment if anything is still wrong

I update font Awesome 5.10 to 5.15 it work for me thanks alot
