### ISSUE TITLE
Missing user chat icon

### ISSUE THREAD

**Issue by trashcanfun** [FortAwesome/Font-Awesome#16070]
I swear there was an User chat icon, with a user icon and a word bubble next to the head, much like the user-md-chat icon, just with a plain user.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I do not recall that icon, but since we have a request for that, I guess it didn't exist before #14887

Closing here

**Comment by swrobel** [comment]
@trashcanfun you should upvote #14887
