### ISSUE TITLE
Indesign does not found phone-icon in the glyphs window

### ISSUE THREAD

**Issue by janstieler** [FortAwesome/Font-Awesome#16072]
**Describe the bug**
In Indesign CC 2020 I can*t use the `phone`-icon.
This is the expected phone-icon: https://fontawesome.com/icons/phone?style=solid

**To Reproduce**
Go to the Indesign glyphs window and type phone. So no phone icon like on https://fontawesome.com/icons/phone?style=solid is shown. Only other phone-icons. But there should are more than the displayed ones. It should found the same like on the website.

**Expected behavior**
If I copy the glyph I can paste it in Indesign or can search the glyph window in Indesign to phone.

**Screenshots**
![Bildschirmfoto 2020-01-15 um 03 22 11](https://user-images.githubusercontent.com/754880/72399363-44384c00-3746-11ea-9704-ef75b376ed8b.jpg)

**Version and implementation**
Fontawesome-Version: 5.12.0 Pro
Indesign-Version: CC2020, 15

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [X] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot help here and I don't know if searching for glyphs inside indesign is a supported feature

Does it work if:
1. You copy the glyph code from the website and paste in an in-design project
2. You use ligatures without searching

?

**Comment by janstieler** [comment]
Hi,
the paste `n` copy works sometimes. With the phone-icon it has worked but not with the `envelope-open-text`. It is strange.

**Comment by tagliala** [comment]
> You use ligatures without searching

just select Font Awesome Pro as a font and write `phone`

**Comment by janstieler** [comment]
Hi,
yes this works with `phone` but not with `envelope-open-text`.
I have also deleted the system- and Adobe-fontcache with Fontexlorer. No change with `envelope-open-text` in solid.

**Comment by tagliala** [comment]
`envelope-open-text` has been introduced in FA 5.12.0, my best guess is that despite your tries, Indesign is not loading the latest Font Awesome version.

I'm not an InDesign user, please uninstall Font Awesome, restart your system, install a freshly downloaded 5.12.0 pro, retry

**Comment by janstieler** [comment]
Okay I have it got to work.
Search in Fontexplorer the libary-folder `Fonts` to `awesome` delete everything what it find and than add the fontfile to your group and delete the Adobe-fontcache, reorganize the database and open InDesign. Now delete the `envelope-open-text`text and write it new. Now the icon should shown.

@tagliala thank you very much for your help and patience!

**Comment by tagliala** [comment]
You're very welcome, glad you solved and thanks for sharing the solution 👍

**Comment by janstieler** [comment]
@tagliala this should be normal :) .
Can you delete the `waiting for feedback`label? I think its wrong now.
