### ISSUE TITLE
Website Package Manager Instructions Typo

### ISSUE THREAD

**Issue by anywhichway** [FortAwesome/Font-Awesome#16073]
You have a typo on https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

npm install --save @fortawesome/fontawesome-pro // note the 'r' rather than 'n' in font

should read

npm install --save @fontawesome/fontawesome-pro

**Comment by anywhichway** [comment]
Well ... maybe it is not a bug, there are @fortawesome packages in npm. However, there is not one for pro under either @fontawesome or @fortawesome. npm install fails for missing package.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FoRt Awesome is not a typo, the package scope `@fortawesome` is correct

Please follow the instructions for installing the NPM Pro packages

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by anywhichway** [comment]
Thanks ... I had a typo in my command.

**Comment by tagliala** [comment]
you're welcome, glad you solved
