### ISSUE TITLE
Check & circle has wrong css class

### ISSUE THREAD

**Issue by laurartucker** [FortAwesome/Font-Awesome#16078]
HTML to copy has `<i class="far fa-check-circle"></I>` instead of `<i class="fa fa-check-circle"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
