### ISSUE TITLE
Don't you have Qzone's logo?

### ISSUE THREAD

**Issue by xubingtao** [FortAwesome/Font-Awesome#16083]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment QZone is not available in Font Awesome.

There is a request for QZone available at #3993, please add a 👍 reaction to that request.

If you want more information on how requests work, please take a look at our [Brand Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs)

Closing here
