### ISSUE TITLE
Missing user-edit

### ISSUE THREAD

**Issue by tomasr1981** [FortAwesome/Font-Awesome#16092]
In this CDN https://use.fontawesome.com/releases/v5.0.2/css/fontawesome.css is missing icon user-edit.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[user-edit](https://fontawesome.com/icons/user-edit?style=solid) has been introduced in version 5.0.11, the link points to version 5.0.2

Please make sure to use FA >= 5.0.11 if you need that icon

Hope it helps and sorry for the late reply

Closing here
