### ISSUE TITLE
Can't authenticate to npm.fontawesome.com

### ISSUE THREAD

**Issue by kopax** [FortAwesome/Font-Awesome#16094]
**Describe the bug**

I have the following error that happened in my CI when I try to authenticate with the fontawesome registry:

```
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

**Expected behavior**

I expect to login correctly using my token

What have changed recently?

**Comment by tagliala** [comment]
Hi,

just to be sure, we are referring to Font Awesome Pro, right?

We have recently changed the `.npmrc` required format, please check yours

Docs: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by kopax** [comment]
I have checked that page and I have configured my host globally as described in [font awesome documentation](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)

I am running the following:

```
npm config set "@fortawesome:registry" https://npm.fontawesome.com/
npm config set "//npm.fontawesome.com/:_authToken" "${NPM_FONT_AWESOME_AUTH_TOKEN}"
```

I have the following error: 

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

I expect to authenticate.

If you access from a browser https://npm.fontawesome.com/ , you have a Basic auth, I am not sure what I should expect here as I have never tried before.

This happened recently, the configuration was working for year. Is it me or fontawesome server?

How to fix fontawesome npm authentication?

**Comment by kopax** [comment]
IT seems that my subscription ended on ` Jan 16, 2020`, but I should be able to access `Version 5.12.0`, I have thhe perpetual license on it.

**Comment by tagliala** [comment]
@kopax please send an email to hello@fontawesome.com, you can add a link to https://github.com/FortAwesome/Font-Awesome/issues/16094 so you don't need to explain again the issue

**Comment by kopax** [comment]
Thanks, I have just forwarded the request to hello@fontawesome.com, in the meantime, could you please share with me by email the archives 5.12.0 that fulfill our checksum lock file requirement  (the one distributed by the npm proxy we were relying on in the past, and not the direct download  available one on your website)

**Comment by kopax** [comment]
No answer from the font awesome customer service. 

They refused to provide us with the proper archives. It was very frustrating. They asked us to resubscribe. My advice: **do not pay for fontawesome**. We just wrote our own adapter and use it with an npm. No way we would pay a subscription for such a misunderstanding, and no way we pay again for such poor customer service.

**Comment by supercodepoet** [comment]
@kopax I sent a response email to your request 2 days ago. Did you not receive it?

**Comment by kopax** [comment]
Unless that was the one telling me to subscribe order to get support. No, I have not received it.

**Comment by supercodepoet** [comment]
@kopax It was an email explaining that we charge for services we pay for. Some services are given us for free so we pass that along. I also stated for your case I am willing to grab what you need if you provide me the packages, version numbers, and hashes.

**Comment by kopax** [comment]
@supercodepoet I have not received it. Can you please reforward it. I am willing to get all the private and paid packages for version:

   "@fortawesome/fontawesome-pro": "^5.12.0",
    "@fortawesome/pro-light-svg-icons": "^5.12.0",
    "@fortawesome/pro-regular-svg-icons": "^5.12.0",
    "@fortawesome/pro-solid-svg-icons": "^5.12.0",

I have not received anything yet. Can you please reopen and forward those archives as you apparently offered ?

**Comment by supercodepoet** [comment]
@kopax an email was sent with a .zip attachment of the requested packages. Let me know if you don't get it.

**Comment by kopax** [comment]
@supercodepoet I can't find it. Could you please hint me on the timestamp and address you have emailed to?

**Comment by kopax** [comment]
> @kopax an email was sent with a .zip attachment of the requested packages. Let me know if you don't get it.

Thanks @supercodepoet but I can't find your email. Could you please hint me on the timestamp and address you have emailed to?

**Comment by afenrir** [comment]
I also have this problem. I can no longer access the pro package that I paid for under my perpetual license. I can download previous version fonts, but that is no good for my React project installed via NPM. I need the NPM package.

**Comment by kopax** [comment]
@supercodepoet I still didn't get your email.... any chance to get it before the apocalypse ?

**Comment by tagliala** [comment]
@kopax I've just sent a reminder to hello@fontawesome.com with a link to this discussion.

Since this is a support ticket about FA Pro, please keep using the email.

Feel free to ping me here if you don't manage to get your files

**Comment by kopax** [comment]
Thank you, I'll watch out for their email.

**Comment by supercodepoet** [comment]
The email has been sent again. Let me know if you get it.

**Comment by kopax** [comment]
No, I have checked all my mail client, nothing arrived, can you please send it again to two email, the one from my github profile and the same one but instead of `.vn`, using `.com`. Also, you can use the first letter of my firstname dot my family name at gmaiI dot com

**Comment by kopax** [comment]
I have received the email, thank you.

**Comment by jr-k** [comment]
@supercodepoet Same problem here, I have license for 5.12.1, but I can't get dependencies from "pro" repository, can I have access to these repositories ? Thanks.

**Comment by mOewa** [comment]
Hello, same behavior here, I followed the methods with npm config and npmrc and this ended with the same error.

**Comment by tagliala** [comment]
Hi guys,

I'm going to lock here because @kopax issue is related to expired license and that needs to be solved through email support

@jr-k if you have an expired license and you want a copy of the latest packages your license can download, please send an email to hello@fontawesome.com

@mOewa please send an email to hello@fontawesome.com
