### ISSUE TITLE
Review icon

### ISSUE THREAD

**Issue by nicolasvahidzein** [FortAwesome/Font-Awesome#16102]
We need an icon for user reviews

maybe a check list with stars in it or something along those lines. Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.
 
Could you please fix this request and fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)?

We need
- a better title (you can leave "review", but we also need a description of what the icon actually represents)
- a single color example of the icon you have in mind

**Comment by nicolasvahidzein** [comment]
we can close this, i realized we can use thumb up. Thanks.
