### ISSUE TITLE
Clean up Font Awesome Brand icons

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#16105]
**Describe the bug**
The Font Awesome Icon has a small imperfections here en there.

Ref: simple-icons/simple-icons#2447

**To Reproduce**
1. Go to https://fontawesome.com/icons/font-awesome (https://fontawesome.com/icons/font-awesome-flag also contains an extra point)
2. Zoooooom in

**Expected behavior**
See a clean SVG path

**Screenshots**
![image](https://user-images.githubusercontent.com/556268/73008536-0c4c9b00-3e0f-11ea-81b2-e37e3db74e0f.png)

**Version and implementation**
Version: 5.12.0
Browser and version: n/a

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by PeterShaggyNoble** [comment]
As pointed out by @ericcornelissen in the Simple Icons issue, the top imperfection, where the flag meets the pole is also present in `fontawesome-flag`.

**Comment by sensibleworld** [comment]
Thanks for the report! We've got this fixed up (with our new logo, too!) in the latest v6 alpha release.
