### ISSUE TITLE
Icon request: Airplane Tail

### ISSUE THREAD

**Issue by mikejmorgan** [FortAwesome/Font-Awesome#16109]
I would like to request an airplane tail icon that looks similar to this:
[https://photos.app.goo.gl/Gn88hMdXBaa633fA6](url)

This would fit with the #1976 request and the #16044 request.  

I could use this with my pro account today, and would be willing to donate to the cause to get these made.  I would prefer all three in duotone options.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/plane-tail?s=solid
