### ISSUE TITLE
Update request: yammer

### ISSUE THREAD

**Issue by polys** [FortAwesome/Font-Awesome#16111]
**What can it be used for?**
An icon for Yammer already exists but is outdated.  Unfortunately, users who weren't familiar with older versions of Yammer don't seem to recognise the existing icon.

Not sure if replacing the existing icon is a good idea or not.
Could be added as `yammer-alt` or `yammer-office-365` or similar maybe. 
It's part for the Office 365 suite, so it's continuously updated.

**Example image (optional)**

![image](https://user-images.githubusercontent.com/4301432/73117952-40c27300-3f45-11ea-9768-c9f361a73f44.png)

![image](https://user-images.githubusercontent.com/4301432/73117911-c85bb200-3f44-11ea-858d-0ba40a4f00db.png)

**Icon request checklist**
- [x] This is a single icon ~or matched pair (Ex: `lock` / `unlock`)~
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thanks!

**Comment by tagliala** [comment]
Thanks for reporting this

**Comment by sensibleworld** [comment]
Does an official one-color version of this exist anywhere?

**Comment by polys** [comment]
> Does an official one-color version of this exist anywhere?

There's an SVG on the top-left corner of their 404 page:
https://www.yammer.com/images/some-bad-url

It looks like this:
![image](https://user-images.githubusercontent.com/4301432/101382367-ca560780-38af-11eb-986b-89725b4a5710.png)

**Comment by sensibleworld** [comment]
@polys Awesome. Thanks!

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
