### ISSUE TITLE
Icon request: Discord

### ISSUE THREAD

**Issue by Kashotex** [FortAwesome/Font-Awesome#16110]
This can be used for displaying icons that lead to discord server links

There are 2 that i would like to be added, the loading icon and the main logo

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Discord is available starting from FA 5.0.0: https://fontawesome.com/icons/discord?style=brands

> There are 2 that i would like to be added, the loading icon and the main logo

If you want to request another icon, please fill up our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Hope it helps

Closing here
