### ISSUE TITLE
Your email does not exist

### ISSUE THREAD

**Issue by alexandrudinu** [FortAwesome/Font-Awesome#16112]
Hello!

I try to request my account deletion at **cdn@fontawesome.com** but the email is not getting delivered. How can I have my account deleted if that email above does not work?

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Where did you get that email address?

Anyway, please send an email to hello@fontawesome.com

**Comment by alexandrudinu** [comment]
Hello!
The email is in all policies of your website... You may consider updating. Thanks!

**Comment by tagliala** [comment]
@alexandrudinu thanks

Are you referring to https://cdn.fontawesome.com/help ?

**Comment by alexandrudinu** [comment]
Yes!

Also this:
https://cdn.fontawesome.com/tos
https://cdn.fontawesome.com/privacy

**Comment by alexandrudinu** [comment]
No problem! Have a good day!

**Comment by tagliala** [comment]
Thanks. That is an old service

@robmadole could you please take a look?
