### ISSUE TITLE
Can't add a prefix to the library with deep importing

### ISSUE THREAD

**Issue by jeffcstock** [FortAwesome/Font-Awesome#16120]
**Describe the bug**
There is no option to deep import a prefix (`far, fal, fad, etc.`) from one of the pro weights to add to the library. The only way is to use tree shaking.

My app currently doesn’t permit tree shaking, so I’m using deep imports to access the icons.

i.e.The following works because it defaults to a solid import.
```
import { faCoffee } from '@fortawesome/pro-solid-svg-icons/faCoffee'

library.add(faCoffee)
```
However, if you're trying to use something not in the solid category of fonts, you have to use a prefix and add that to the library as well:

```
import { fal } from '@fortawesome/pro-light-svg-icons/fal'
import { faCoffee } from '@fortawesome/pro-light-svg-icons/faCoffee'

// Does not work because there is no file called 'fal'
library.add(fal, faCoffee)
```

So, deep importing becomes useless if you're using anything but solid fonts. In order to get the above to work, you'd have to use the following:

```
import { fal } from '@fortawesome/pro-light-svg-icons'
```

But that means that you'd have to enable treeshaking. Doing so would fix the problem but it would import all of the `pro-light-svg-icons` index file into the app.

Is it possible to use prefixes without treeshaking? So in other words - deep importing?
The example you have on your website uses solid fonts. I'm interested in knowing what you would do for my situation. https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

**To Reproduce**
Try and deep import one of the font prefixes - `fal, far, fad`.
Notice that this doesn't work, and there's no alternative unless you use the tree shaking method.

**Expected behavior**
Provide a deep import for the prefix, so that I can get my project to work with deep imports for other font weights than "Solid".

**Screenshots**

**Version and implementation**
Version: 5.12

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this detailed report.

Unfortunately my knowledge is not enough to provide an answer, I'm leaving this open for feedback from the community

Maybe @robmadole or @mlwilkerson may know more

**Comment by jeffcstock** [comment]
Sorry this is actually my mistake, and I received this answer from (very helpful!) support.

It was a misunderstanding of the documentation around adding icons to the library.

I mistakenly thought that in order to be able to access a certain style of icon, you _had_ to pass the prefix into the library.

i.e. 
```
import { faCheck } from '@fortawesome/pro-light-svg-icons/faCheck'
import { fal } from '@fortawesome/pro-light-svg-icons'

library.add(fal, faCheck)
```

However, doing so automatically adds the entire icon set to the library (the opposite of what i wanted to do. 

I just wanted a few different icons using a deep import to keep my bundle size low, so doing the following worked:
```
import { faCheck } from '@fortawesome/pro-light-svg-icons/faCheck'

library.add(faCheck)
```

It seems obvious in retrospect but that little piece didn't come through in the documentation. I made a suggestion of possibly making those distinctions separately - one that you can add individual icons to use in the library, and the other that, if you just want to add all at once, you can use the prefix... but neither is necessary.

**Comment by jeffcstock** [comment]
I'm going to close this as this isn't an actual issue.

**Comment by robmadole** [comment]
Ah, ok! :+1:
