### ISSUE TITLE
Icon Request: icon-dove (peace)

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#1612]
Would like a new icon of a dove - something like http://commons.wikimedia.org/wiki/File:Peace_dove_icon.svg 

This is to be used for religious non-profit work.

**Comment by pittster** [comment]
+1

**Comment by 12lamat** [comment]
+1

**Comment by Guestrevu** [comment]
+1

**Comment by vxzry** [comment]
+1

**Comment by sensibleworld** [comment]
Released in 5.0.9
