### ISSUE TITLE
[Bug] Icon moving for the versions >= 5.7.0

### ISSUE THREAD

**Issue by s0h3ck** [FortAwesome/Font-Awesome#16133]
**Describe the bug**
The fontawesome library affects the behavior of the element when switching from one icon to another. It's moving from right to left.

**To Reproduce**
Download the code here: https://www.jqueryscript.net/form/Show-Hide-Passwords-Bootstrap-4.html

**Bug:**
In index.html, replace line 10 by 

```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
```

Click on the hide/show button. It's moving. 

**Working version:**
Replace the same line with 

```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
```

Why there is no [v.5.6.4](https://github.com/FortAwesome/Font-Awesome/releases?after=5.7.0) in the release section in Github? I know your little secret, but it is not longer a secret ;p

**Expected behavior**
I expect FontAwesome library to not move the element when switching from an icon to another. It should be static.

**Screenshots**
NA

**Version and implementation**
Bug affects all the versions >= 5.7.0.
Bug does not affect the versions <= 5.6.4.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Download the code here: https://www.jqueryscript.net/form/Show-Hide-Passwords-Bootstrap-4.html

Could you please prepare a jsfiddle showing the issue?

https://jsfiddle.net/

> Why there is no v.5.6.4 in the release section in Github? I know your little secret, but it is not longer a secret ;p

I don't know, this is the only change in the css and looks like it has only been tracked and reported internally:
![image](https://user-images.githubusercontent.com/556268/73522257-38b47880-4408-11ea-9eff-713f92149e42.png)

**Comment by s0h3ck** [comment]
Hi! :)

> Could you please prepare a jsfiddle showing the issue?

Working version: https://jsfiddle.net/qnL0oz6m/
Buggy version: https://jsfiddle.net/qnL0oz6m/1/

Line of interest:

```html
<link rel="stylesheet" 
 href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
```

**Comment by tagliala** [comment]
Hi @s0h3ck thanks, I've got it

Sorry, but per design choice Font Awesome icon have not the same width, and in FA 5.7.0 the slash has been fixed for uniformity with other slashed icons

Please use `fa-fw` helper class if you need the icon to use the same space: https://jsfiddle.net/tagliala/rtsb2jah/

Hope it helps

Closing here

**Comment by s0h3ck** [comment]
Sweet thanks!
