### ISSUE TITLE
Request to add an Apple Music icon

### ISSUE THREAD

**Issue by sarahwefald** [FortAwesome/Font-Awesome#16138]
I make websites for bands and like to use Font Awesome for social media logos, but there's no Apple Music logo like there is for Spotify.

Apple Music branding: https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#apple-music-icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #10500, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
