### ISSUE TITLE
Icon request: add-book, book-check

### ISSUE THREAD

**Issue by irmapersoon** [FortAwesome/Font-Awesome#16143]
**What can it be used for?**
In my case, it would be used as an icon to add a bibliography or to indicate whether a citation is already added to a bibliography (check). I can imagine it could also be used more literally, for example on a book website to indicate whether you've read the book. Or to add a book to your book list. 

**Example image (optional)**
<img width="122" alt="Screen Shot 2020-02-03 at 10 04 49 AM" src="https://user-images.githubusercontent.com/58599385/73639593-fd66b380-466c-11ea-9a9e-e12c3e9c257b.png">
<img width="365" alt="Screen Shot 2020-02-03 at 10 04 38 AM" src="https://user-images.githubusercontent.com/58599385/73639596-ff307700-466c-11ea-9c8d-b3a1adba6d7e.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/308/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by irmapersoon** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.
> 
> Demo: https://jsfiddle.net/tagliala/L17f528g/308/
> 
> Ref:
> 
> https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
> https://fontawesome.com/how-to-use/on-the-web/styling/masking
> https://fontawesome.com/how-to-use/on-the-web/styling/layering

Thanks, I didn't know about this functionality!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
