### ISSUE TITLE
As per cheatsheet the special char code for "map-marker-alt " is &#xf3c5; but the output is obtained by using &#xf041; which belongs to map-marker.  

### ISSUE THREAD

**Issue by Pawan16123** [FortAwesome/Font-Awesome#16152]
link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/

input type="text" placeholder="&#xf3c5; &#xf041; Mumbai" class="location" style="font-family:FontAwesome"/

![Screen Shot 2020-02-05 at 4 08 26 PM](https://user-images.githubusercontent.com/46003170/73834558-f0df8800-4831-11ea-91ec-1963c7192305.png)

![Screen Shot 2020-02-05 at 4 12 20 PM](https://user-images.githubusercontent.com/46003170/73834773-529ff200-4832-11ea-8974-17c12babd211.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> ink href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/

I can see this is using Font Awesome 4.7.0, but you are referring to icons that are available in FA 5.

Please upgrade or use the old documentation available at https://fontawesome.com/v4.7.0/cheatsheet/

Hope it helps

Closing here
