### ISSUE TITLE
documentation edit suggestion (Using Our Mixins scss)

### ISSUE THREAD

**Issue by 0usssama** [FortAwesome/Font-Awesome#16169]
in the case of use **Regular fonts**, a line is missing which is `@import "./fontawesome/scss/regular.scss"` in [using our mixing](https://fontawesome.com/how-to-use/on-the-web/using-with/sass#mixins), i know it's small thing but it's good to avoid an exception since most of the files are loaded.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that the example is fine, it is showing how to create a custom build of Font Awesome

Quoting from the docs:

> Use `@extend .fas;` to create an icon in the Solid style. **Import other styles to use other prefixes**

(emphasis mine)
