### ISSUE TITLE
Icon request: fa-lucky

### ISSUE THREAD

**Issue by brucesantos** [FortAwesome/Font-Awesome#16160]
**What can it be used for?**
A 4 leaf clover to represent Luck

**Example image (optional)**
🍀

**Icon request checklist**
- [X] Single Icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi @brucesantos, #1593 is correctly open 👍
