### ISSUE TITLE
Icon request: nfc-reader

### ISSUE THREAD

**Issue by acidkilla** [FortAwesome/Font-Awesome#16177]
**What can it be used for?**
- Used for buttons where you can initiate NFC tag reading on mobile devices.

**Example image (optional)**
https://www.iconfinder.com/icons/2953833/contactless_mobile_nfc_pass_pay_payment_phone_icon

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`) = Single icon
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (not this icon)
- [x ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by alystair** [comment]
Might make more sense for a generic/general NFC logo since that doesn't exist either.. perhaps as brand, or stylized https://commons.wikimedia.org/wiki/File:NFC_logo.svg

**Comment by jabronus** [comment]
Thanks for requesting an icon! But we actually already have a couple glyphs in Font Awesome Pro that might fit the bill:

- https://fontawesome.com/icons/nfc?f=classic&s=solid
- https://fontawesome.com/icons/nfc-symbol?f=classic&s=solid
