### ISSUE TITLE
Typos on the Accessibility page

### ISSUE THREAD

**Issue by jswetnickoig** [FortAwesome/Font-Awesome#16170]
Hello,

Please note that following 2-typos are on your website: https://fontawesome.com/v4.7.0/accessibility/

Accessibility

Make your icons awesome for all of your users
Icons are symbols that can convey a ton of information and really help people comprehend directions, signs, and interfaces. It's important that we create and use them so that they can reach the largest amount of people possible. 

About Icon Fonts & Accessibility
Modern versions of assistive technology, like screen readers, will read CSS generated content (how Font Awesome icons are rendered), as well as specific Unicode characters. When reading our default markup for rendering icons, **assisistive** technology may have the following problems. 
•	The assistive technology may not find any content to read out to a user 
•	The assistive technology may read the unicode equivalent, which could not match up to what the icon means in context, or worse is just plain confusing 

Using Font Awesome with **Acessibility** in mind

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

FA 4.7 is in EOL, but let's ask see if @talbs can fix this

**Comment by jswetnickoig** [comment]
Hello again,

I know I alerted you to 2-typos on the FA Accessibility page... but as a visually impaired user, I have to say the Font Awesome site is not very accessible. The way the words are displayed in the page titles makes reading them very hard on the eyes/brain. Because of the double lettering, it really is hard to look at. It is like Op Art and pops off the page in a not-very accessible manner.

Also, do you know you have a lazy loading issue on all the main landing pages? The icons to the left of the page titles' text appear a few nano-seconds after the text. The size and layout location of the icons and the text also jumps between partially loaded and fully loaded states.

Hope you can fix. Thx!

Julie

**Comment by talbs** [comment]
Sorry for the radio silence. We fixed up those typos a bit ago. Thanks for bringing them to our attention!
