### ISSUE TITLE
Category change: wheelchair

### ISSUE THREAD

**Issue by DarkenedSky** [FortAwesome/Font-Awesome#16173]
The "wheelchair" icon is currently in the Accessibility section on the icons browser page of fontawesome.com. It should probably also be in the "Medical" section, along with the "walker" icon that's already there.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this suggestion.

@talbs can you please add `medical` category to wheelchair?

**Comment by sensibleworld** [comment]
This should be good to go!
