### ISSUE TITLE
Bug between fontawesome and animate

### ISSUE THREAD

**Issue by alain01** [FortAwesome/Font-Awesome#16175]
Hi,
i found a bug between fontawesome and [animate](https://github.com/daneden/animate.css)

To explain in details, 
see the codepen page [here](https://codepen.io/alain01/pen/KKppxmR)

I used a class with _animate_ + _fa-flip-horizontal_ but the icon isnt flip.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this depends on both frameworks trying to use the `transform` attribute.

Please write a custom css rule for the flipped animation 

Hope it helps

Closing here
