### ISSUE TITLE
Icon request: Airplay icon

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1618]
Requesting a Airplay icon to add.

![Airplay](http://images.apple.com/osx/whats-new/images/features_airplay_icon.jpg)

**Comment by WonderPolls** [comment]
This is old, but I think an AirPlay icon would be helpful.

**Comment by s3bubble** [comment]
airplay and chromecast would be good ;)

**Comment by toutflou** [comment]
I was also looking for a Fontawesome airplay icon. I'm surprised it does not exist yet.

**Comment by aethior** [comment]
Hi,

This icon was added in v6.0.0.
Check https://fontawesome.com/icons/airplay

Regards.

cc/ @tagliala
