### ISSUE TITLE
NoSuchBucket 404

### ISSUE THREAD

**Issue by EdithAllison** [FortAwesome/Font-Awesome#16180]
Hi, 

I've been using your kit but I now get 404 not found.

URL: https://kit.fontawesome.com/207868e4c5.js
```

<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>kit.fontawesome.com</BucketName>
<RequestId>4EAAA480B8F23041</RequestId>
<HostId>
Au23VA3Z8o/NAUHb9mnIUGLf3S8Boq2r74yPc61kbg6iXRP9F2Xk9mJLTWpIBI/B9xzw8dbvIOU=
</HostId>
</Error>
```

Can you advise how I can fix this? Many thanks, Edith

**Comment by joshuaajones** [comment]
Same here.  Our kit (even a newly created one) simply returns net::ERR_ABORTED 404 with the above output when accessed directly in the browser.  Please advise asap.

**Comment by AubreyHewes** [comment]
FYI, They are working it out...

* https://status.fortawesome.com/incidents/xsxc0k6fnyy8
* https://twitter.com/fontawesome/status/1227257808997011456

**Comment by lofcz** [comment]
same here

**Comment by joshuaajones** [comment]
switching to the CDN version worked for us:
https://fontawesome.com/account/cdn

**Comment by EdithAllison** [comment]
Confirmed as working again, thank you for quick fix!
