### ISSUE TITLE
Icon request: bicep

### ISSUE THREAD

**Issue by aggie1288** [FortAwesome/Font-Awesome#16183]
**What can it be used for?**
I want a single icon to replace the "lock" icon that is on the checkout button for a website.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You mean 💪 ?

**Comment by sensibleworld** [comment]
Closing in favor of: https://github.com/FortAwesome/Font-Awesome/issues/2076
