### ISSUE TITLE
Microblog icon display problem 

### ISSUE THREAD

**Issue by mikoou96** [FortAwesome/Font-Awesome#16190]
Hi, the icon "Microblog" is not rendering correctly. Instead of displaying the icon, it displays a chinese character (See the screencapture).

Regards,
Mikael

![Capture](https://user-images.githubusercontent.com/15670936/74423918-572b6280-4e51-11ea-9fd5-85c038425c7b.PNG)

**Comment by robmadole** [comment]
This icon is a brand icon. Are you using the `fab` prefix?

**Comment by mikoou96** [comment]
Hi,
Yes I am using the fab prefix, so I guess it should be a Cache issue.
Thanks for the reply
Regards,
Mikaël

Le mar. 18 févr. 2020 à 21:02, Rob Madole <notifications@github.com> a
écrit :

**Comment by robmadole** [comment]
@mikoou96 perhaps you can share a reproducible test case?

**Comment by tagliala** [comment]
No feedback, closing here
