### ISSUE TITLE
Font subset

### ISSUE THREAD

**Issue by shalamos** [FortAwesome/Font-Awesome#162]
Hi, 

it would be a super-cool feature to be able to download custom subsets of the font, where only the icons you actually use are included. This could massively reduce the overhead of unused icons and thus the filesize of the font. 

What do you think?

Cheers, 
Amos

**Comment by tobilg** [comment]
Does icnfnt.com still work?

**Comment by kaj** [comment]
I can't reach icnfnt.com at the moment.  But http://fontello.com/ seems to work just fine, allowing creation of subsets of Font-Awesome and some other icon fonts.

**Comment by tobilg** [comment]
Thanks, I'll use the one you proposed. I was just wondering, because http://icnfnt.com is still linked from the http://fortawesome.github.io/Font-Awesome/3.2.1/ page.
