### ISSUE TITLE
faHandPointer does not load

### ISSUE THREAD

**Issue by trutherford2388** [FortAwesome/Font-Awesome#16200]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

I am trying to import faHandPointer from '@fortawesome/free-solid-svg-icons' and include it on my page, but I keep getting a console error stating "Could not find one or more icon(s) 'handPointer'." 

```
<template>
  <div>
    <font-awesome-icon icon="faHandPointer"></font-awesome-icon>
  </div>
</template>
<script>
  import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
  import {faHandPointer} from '@fortawesome/free-solid-svg-icons';

  export default {
    components: [FontAwesomeIcon]
  }
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

Sorry, can't replicate.

Demo: https://codesandbox.io/s/modest-robinson-vwkfk

Docs: https://github.com/FortAwesome/vue-fontawesome#recommended

Hope it helps

Closing here
