### ISSUE TITLE
确保文本在webfont加载期间保持可见

### ISSUE THREAD

**Issue by MHuiG** [FortAwesome/Font-Awesome#16202]
利用 font-display 这项 CSS 功能，确保文本在网页字体加载期间始终对用户可见。[了解详情](https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown)。

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate: 

> Use font-display, a CSS feature, to ensure that text is always visible to the user during web page font loading. Learn more.

Unfortunately for webfont there is no other choice of `font-display: block`, anyway this is going to be fixed by #16077
