### ISSUE TITLE
Icon request: send later

### ISSUE THREAD

**Issue by arj-89** [FortAwesome/Font-Awesome#16203]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
a single icon to be used instead of the normal send, it will be used to schedule the job for a future time (based on the user selection).

**Example image (optional)**
Insert the example image here if necessary.

1- <img width="574" alt="Screen Shot 2020-02-15 at 2 13 46 PM" src="https://user-images.githubusercontent.com/2502552/74586893-70711200-4ffd-11ea-86ad-ebbe413e11e8.png">
could be a combination of (share + history -but with reversed arrow direction-).

2- <img width="53" alt="Screen Shot 2020-02-15 at 2 04 38 PM" src="https://user-images.githubusercontent.com/2502552/74586779-41a66c00-4ffc-11ea-92a2-52c0acf38006.png">
screenshot from (Spark - an email client).

Hopefully, you got the idea 😅

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please fix the title and keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/p8uz0ryo/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by arj-89** [comment]
Thanks for the comment and sorry for the delay. And I’ll dig into the SVG framework more.

Much appreciated.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
