### ISSUE TITLE
"Unexpected token: else" in FontAwesome JS on Chrome Mobile

### ISSUE THREAD

**Issue by rangoo94** [FortAwesome/Font-Awesome#16211]
**Describe the bug**

Some of the users experience the problem with loading FontAwesome kit, getting the error `Unexpected token 'else'` during `<script>` load.

```
      {
        "stacktrace": {
          "frames": [
            {
              "abs_path": "https://XXX/",
              "module": "<unknown module>",
              "filename": "https://XXX/",
              "lineno": 1,
              "colno": 219,
              "in_app": false,
              "data": {
                "orig_in_app": 1
              },
              "context_line": "{snip} al-scale=1,shrink-to-fit=no\"><script src=https://use.fontawesome.com/XXXXXXXXXX.js integrity=sha384-XXX {snip}"
            }
          ]
        },
        "type": "SyntaxError",
        "mechanism": {
          "type": "onerror",
          "handled": false
        },
        "value": "Unexpected token 'else'"
      }
```

**To Reproduce**

Load script:

```
<script src="https://use.fontawesome.com/xxxxxxxxxx.js" integrity="sha384-xxx" crossorigin="anonymous"></script>
```

**Expected behavior**

Just working, without errors.

**Version and implementation**
Version: recent one, probably 5.12.1 (but first issue we monitored on Dec 7, 2019
Browser and version:
* Chrome Mobile WebView 70.0.3538
* Chrome Mobile 78.0.3904

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please disclose the kit ID and provide a reproducible test case?

**Comment by rangoo94** [comment]
Hi @tagliala! Thanks for quick answer.

## Kit ID

The kit ID is `c783fb7868`.

```html
<script src="https://use.fontawesome.com/c783fb7868.js" integrity="sha384-4h4+KEprKNN39bTl8y3t6f5MqlFnWR3HJs6HlrwnnZ7u8DJQluBrr4/v+6LmWPpZ" crossorigin="anonymous"></script>
```

## Reproducible example

I tried to reproduce it with BrowserStack (even on original code), but with no luck - seems like it happens only on physical device, or in some special circumstances which I can't recognize yet.

We are basically creating in-flight `<i class="fa fa-SOMETHING"></i>` elements with Vue (happened on Mithril too), so I believe that something like this should be more-less reproducing real situation:
```html
<!doctype html>
<script src="https://use.fontawesome.com/c783fb7868.js" integrity="sha384-4h4+KEprKNN39bTl8y3t6f5MqlFnWR3HJs6HlrwnnZ7u8DJQluBrr4/v+6LmWPpZ" crossorigin="anonymous"></script>
<script>
    setTimeout(function () {
        const element = document.createElement('i');
        element.className = 'fa fa-camera';
        document.body.appendChild(element);
    }, 3000);
</script>
```

## Additional information about event

**It's worth to note, that this error may happen multiple times during a single session, despite fact that it's `onerror` handler.** To expose as much data as I can, there is a segmentation of event occurrences:

<img width="1708" alt="Zrzut ekranu 2020-02-20 o 08 21 12" src="https://user-images.githubusercontent.com/3843526/74910229-513a0200-53ba-11ea-83c8-ababcc92345b.png">

**Comment by tagliala** [comment]
Hi,

I cannot recognize this as a kit.

It looks like the old CDN implementation, and it definitely uses FA4, which is in EOL.

Could you please try with a new Kit?

https://fontawesome.com/kits

**Comment by rangoo94** [comment]
Ahh, I wasn't aware that FA4 is no longer supported, thought that it's too. We will try to migrate to the newer version soon. I am closing this ticket in that case.

Thanks for help!

**Comment by tagliala** [comment]
You're welcome

Please notice that FA5 also offers an official NPM package and integration with VUE. You should use this if your stack includes VUE

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
https://fontawesome.com/how-to-use/on-the-web/using-with/vuejs
