### ISSUE TITLE
dom.watch() causes page to scroll to top when inserting icons dynamically

### ISSUE THREAD

**Issue by simmerz** [FortAwesome/Font-Awesome#16217]
If an XHR request returns content with an icon in it, `dom.watch()` scrolls the page to the top, meaning the user loses their current position.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a reproducible test case?

**Comment by simmerz** [comment]
I've figured out this was actually caused by https://github.com/tomkra/font_awesome5_rails/issues/48#issuecomment-588158725 so closing this as it's not a bug with FA directly.
