### ISSUE TITLE
font-awesome V5.12 for html select-option (unicode)

### ISSUE THREAD

**Issue by KinkiWu** [FortAwesome/Font-Awesome#16228]
The code is normal in V4.7 version., after upgrade to font-awesome V5.12.1, I can't using the unicode to display the icon in the select optioin. 
some icon normal(ex: fa-android) , but some icon abnormal (fa-cog).
```
<select>
    <option value='fa-cog'>&#xf013; fa-cog</option>
    <option value='fa-android'>&#xf17b; fa-android</option>
</select>

```

Icon not show in the option dropdown list. but after select the fa-cog option the icon show in the selected item.
https://prnt.sc/r5fxvh

I write a sample code to reproduce the issue in the codepen
https://codepen.io/Kinki666/pen/yLNaPVQ

Version: font-awesome V5.12.1
Browser and version: Chrome 79.0.3945.130

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, we never supported this usage and we strongly advise to use a javascript plugin for this use case because the above implementation is not cross-platform compatible.

Ref: #996

Hope it helps

Closing here

**Comment by KinkiWu** [comment]
Thanks @tagliala .

According to your advice, finally I use **Select2** jQuery plugin to implement.
https://select2.org/

I also use **ui-select** in my angularjs project.
https://angular-ui.github.io/ui-select/
```
<ui-select ng-model="info.selectName">
   <ui-select-match>
      <span><i class='fas fa-cog'></i> {{$select.selected.Name}}</span>
   </ui-select-match>
   <ui-select-choices repeat="option in info.list| filter: $select.search">
      <span><i class='fas fa-cog'></i> {{option.Name}}</span>
   </ui-select-choices>
</ui-select>
```

**Comment by tagliala** [comment]
@KinkiWu perfect!

Thanks for sharing your approach
