### ISSUE TITLE
Currency Icon request: Florin

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1622]
Florin sign: ƒ

also called a gulden or guilder

Now used in Aruba, Netherlands Antillean
Previously used in the Netherlands, Suriname

**Comment by sensibleworld** [comment]
<img width="207" alt="Screen Shot 2021-03-30 at 1 31 22 PM" src="https://user-images.githubusercontent.com/529604/113031036-3957b480-915c-11eb-8067-769d2352aa9f.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
