### ISSUE TITLE
Icon request: PDF icon that isn't the Adobe Acrobat Reader brandmark

### ISSUE THREAD

**Issue by mkstix6** [FortAwesome/Font-Awesome#16226]
**What can it be used for?**
I would like to use a file-pdf icon that is not the brandmark for Adobe Acrobat Reader.

My reasoning being …personally, I haven't used Adobe Acrobat Reader in many many years and I don't associate the Acrobat symbol with PDFs anymore. _Perhaps others think like me but I don't have any data to back this up_. I also think this the letters "PDF" would be clearer for all users of the site I'm working on, regardless of their familiarity with the Acrobat symbol.

**Example image (optional)**
I guess the new icon would look like the existing `file` or `file-pdf` icon but simply with the letters "PDF" instead of the Adobe Acrobat Reader brandmark.

I believe my request here is related to older issues but is different:

1. https://github.com/FortAwesome/Font-Awesome/issues/1911
1. https://github.com/FortAwesome/Font-Awesome/issues/1970
1. https://github.com/FortAwesome/Font-Awesome/issues/7452

**Comment by Alfinch** [comment]
I agree that the letters "PDF" would make more sense. Most people now use the PDF readers integrated into their browsers. Using the Acrobat logo seems a bit old fashioned to me.

**Comment by aethior** [comment]
Hi @mkstix6,

This icon was updated in the last version.
Check https://fontawesome.com/icons/file-pdf

Regards.

cc/ @tagliala
