### ISSUE TITLE
Icon Request:  Ravelry

### ISSUE THREAD

**Issue by innocent92** [FortAwesome/Font-Awesome#1623]
I would like to request a icon for the social media site "Ravelry".  Ravelry is a social media site for the knitting and crocheting world.  It has more than 3 million users.

The logo is:  http://badges.ravelry.com/square_24.png

**Comment by franhaselden** [comment]
+1

**Comment by tagliala** [comment]
closing this in favour of #3314, which has more +1s

sorry @innocent92. no need to +1 #3314 , I will do it by myself
