### ISSUE TITLE
Icon request: fa-dependency

### ISSUE THREAD

**Issue by Gahnterr** [FortAwesome/Font-Awesome#16237]
**What can it be used for?**
We want to use this icon to represent dependencies. For example, in the context of tasks and subtasks, it would be nice to have a generic icon to represent that X element has child elements, as well as parent elements.

I know there's folder tree, but it's pretty linked to folders. We're looking for something more generic.

**Example image (optional)**
[Example icon](https://user-images.githubusercontent.com/45857109/75175006-6da1ab80-56e6-11ea-8614-aeb624bbbac9.png)
![Another example](https://user-images.githubusercontent.com/45857109/75175878-0127ac00-56e8-11ea-8244-4b4f8f4e18b0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not convinced of the name of this request

Does https://fontawesome.com/icons/sitemap?style=solid fit this use case?

**Comment by Gahnterr** [comment]
Hi, thanks for the quick reply.

We've looked at fa-sitemap, but we find it looks more like it represents a whole diagram/sitemap, instead of representing just "child element". We also think it's a bit too complex. We're looking for something that says "single element depends to another single element", like in the second example. As in, a single dependency. Hopefully I explained it well 😅

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/diagram-nested?f=classic&s=solid
