### ISSUE TITLE
what  different desktop and web？？

### ISSUE THREAD

**Issue by handashuai** [FortAwesome/Font-Awesome#16248]
fontawesome-free-5.12.1-desktop.zip

fontawesome-free-5.12.1-web.zip

what  different desktop and web？？？

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Web is for websites or web applications, desktop is for desktop applications like Photoshop, InDesign, Word, etc.

Ref:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/how-to-use/on-the-desktop/setup/getting-started

Hope it helps

Closing here
