### ISSUE TITLE
Icon update: TripAdvisor brand

### ISSUE THREAD

**Issue by alexsmacd** [FortAwesome/Font-Awesome#16249]
I just noticed that TripAdvisor updated their logo in January 2020, which is actually a simpler version, since it doesn't have the double eye rings.

https://tripadvisor.mediaroom.com/logo-guidelines

Old:
![image](https://user-images.githubusercontent.com/4443644/75465988-764ce880-5957-11ea-9707-60aee8ab78ac.png)

New:
![image](https://user-images.githubusercontent.com/4443644/75466022-81a01400-5957-11ea-972b-155038d5a949.png)

Can this be updated in FontAwesome?

**Comment by alexsmacd** [comment]
Old:
![image](https://user-images.githubusercontent.com/4443644/75465988-764ce880-5957-11ea-9707-60aee8ab78ac.png)

New:
![image](https://user-images.githubusercontent.com/4443644/75466022-81a01400-5957-11ea-972b-155038d5a949.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by tagliala** [comment]
Hi, 

this icon has been updated in 5.13.1 but it has issues in the CSS version.

I'm going to open a new issue
