### ISSUE TITLE
Some icons are not vertically centered (briefcase, comment[ing], comment[ing]-o, download, external-link, gamepad, thumbs-down)

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#1624]
The vertical alignment of some even-height icons could be improved
- [x] `fa-briefcase` should be shifted `down` by "1 grid unit"
- [x] `fa-comment` should be shifted `up` by "1 grid unit"
- [x] `fa-commenting` should be shifted `up` by "1 grid unit"
- [x] `fa-comment-o` should be shifted `up` by "1 grid unit"
- [x] `fa-commenting-o` should be shifted `up` by "1 grid unit"
- [x] `fa-download` should be shifted `down` by "1 grid unit"
- [x] `fa-external-link` should be shifted `down` by "1 grid unit"
- [x] `fa-gamepad` should be shifted `up` by "1 grid unit"
- [x] `fa-thumbs-down` should be shifted `up` by "1 grid unit" (NOTE: `fa-thumbs-o-down` is fine)

How I noticed?

Added a "grid" option to my comparison tool: http://tagliala.github.io/vectoriconsroundup/

Here is a fiddle showing the issue: <s>http://jsfiddle.net/tagliala/Vxq69/</s> <s>http://jsfiddle.net/tagliala/e9yfxsfj/7/</s> http://jsfiddle.net/tagliala/e9yfxsfj/32/

Refers to #1553

**Comment by mickeyvip** [comment]
+1

Not fixed in `v4.6.1`

**Comment by jv-PintoBobcat** [comment]
@mickeyvip Please use the new github reactions instead of posting "+1"

**Comment by BorzdeG** [comment]
+1

**Comment by tagliala** [comment]
Fixed in 5.0.0

http://jsfiddle.net/tagliala/e9yfxsfj/43/
