### ISSUE TITLE
Font Awesome site unavailable in China

### ISSUE THREAD

**Issue by tankerkiller125** [FortAwesome/Font-Awesome#16250]
**Describe the bug**
The Font Awesome website with icons is currently unavailable to Chinese users. This is starting to become a problem for some our application users over on Flarum (we ship with the open source version) who are unable to view the icon listings and are there for unable to know icon names.

**To Reproduce**
Visit https://fontawesome.com from China or a VPN that lets you set China as your country

**Expected behavior**
The website should work in china, it does not appear that Chinas Great Firewall is blocking the connection based on some basic testing.

**Version and implementation**
Version: Any
Browser and version: Any

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Let's use #16148

**Comment by tankerkiller125** [comment]
That request appears to be specifically for kit.fontawesome.com, would updating the CDN also impact the main fontawesome.com site?

**Comment by tagliala** [comment]
Let's ask @robmadole if he prefers two separate requests for kit and for the documentation website

**Comment by robmadole** [comment]
@tankerkiller125 you mentioned you have done some testing. What procedures have you followed?

We are not actively blocking anything from China so my assumption is that it's blocked from inside. This is a rough one to fix. Do you have a suggestion?

**Comment by tankerkiller125** [comment]
@robmadole

Unfortunately I haven't done much testing myself (except the one time I managed to get access to a VPN that exited in China), it's mostly something we've heard from our Chinese users. We did get an update recently from a user in china who informed us that they managed to get it to load but it took a very long time, so they think that it may not be blocked but rather is just very slow.

**Comment by robmadole** [comment]
We'd be happy to look at how we can fix this but at the moment don't have a good solution.

**Comment by tankerkiller125** [comment]
Someone did create a mirror for FontAwesome but it's stuck at FontAwesome 4 because that was the last fully open source one (if my memory of this project is correct) Maybe a trusted Chinese user/contributor/partner could host a mirror for FontAwesome 5 in china with a Chinese URL?
