### ISSUE TITLE
Zodiac sign icons

### ISSUE THREAD

**Issue by gitumen** [FortAwesome/Font-Awesome#16251]
I'm surprised there are no zodiac sign icons at all. An icon to represent zodiac signs in general would be useful as well.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2831, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
