### ISSUE TITLE
Google scholar

### ISSUE THREAD

**Issue by limbz-sami** [FortAwesome/Font-Awesome#16265]
It'd be nice if we could use google scholar icons. 

Thank you for your awesome work

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #541 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
