### ISSUE TITLE
icon request: Avocado

### ISSUE THREAD

**Issue by dripclub** [FortAwesome/Font-Awesome#16269]
**What can it be used for?**
All things Avocado

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You mean avocado 🥑 the fruit?

**Comment by mickr** [comment]
I am going to venture yes. I am in need of the avocado icon as well.

**Comment by aethior** [comment]
Hi @dripclub,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/avocado

Regards.

cc/ @tagliala
