### ISSUE TITLE
Firefox Viewport Bug

### ISSUE THREAD

**Issue by Chri-B** [FortAwesome/Font-Awesome#16267]
Uncompatibility issue using your script kit and firefox viewport: firefox doesn't rescale the viewport and a "white box" appear to fill the gap: it only disappear after page refresh.

![Schermata 2020-03-04 alle 12 16 18](https://user-images.githubusercontent.com/59871650/75874517-261bcd80-5e12-11ea-8529-722f4b3155e6.png)

https://codepen.io/federicobartoli/pen/ExjvzLa

**Comment by tagliala** [comment]
Ciao!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

What should I do to replicate the issue in the codepen you provided?

**Comment by Chri-B** [comment]
Hi,
I’m gonna try explain you the issue by attaching a few more screenshot.
Let me know if it'is more understandable.
Also I’ll try to be more specific: when i try to rescale browser window (only with FIREFOX - screenshot nr.1 is the starting situation), the new window appears like the screenshot nr. 3.
In the screenshot nr.1 you can see the complete code.
If I try the same action without your script link, the issue doesn’t happen.
Thank you.

Christian Beretta
Il 4 mar 2020, 12:37 +0100, Geremia Taglialatela <notifications@github.com>, ha scritto:

**Comment by tagliala** [comment]
Hi Christian, please do not use email attachment, they don't work

Paste images at https://github.com/FortAwesome/Font-Awesome/issues/16267#issuecomment-594561037

**Comment by federicobartoli** [comment]
i have the same problem

**Comment by tagliala** [comment]
@Chri-B the page on the screenshot does not mach the one on the codepen, could you please provide the screenshot code in a codepen / jsfiddle?

Codepen:
![image](https://user-images.githubusercontent.com/556268/75967165-b5d18280-5ecb-11ea-9772-c512496f6090.png)

Screenshot:
![image](https://user-images.githubusercontent.com/556268/75967126-a7836680-5ecb-11ea-96fb-3454b831d0a4.png)

**Comment by Chri-B** [comment]
Code in codepen related to the lasts screenshot: please notice that in the header there is Fontawesome script kit.
https://codepen.io/chri-b/pen/abOLygX

**Comment by tagliala** [comment]
Thanks, I was able to replicate

https://tagliala.github.io/fa16267.html

Firefox 73.0.1 (64 bit) - macOS 10.14.5

Still not sure that it is Font Awesome's related, keeping investigate

**Comment by Chri-B** [comment]
The issue continues to be there for me.
![Schermata 2020-03-05 alle 16 24 36](https://user-images.githubusercontent.com/59871650/75996403-1da0c100-5efe-11ea-8a92-f2d6ed9a9029.png)

Firefox Developer Edition 74.0b9 - macOS 10.15.3

**Comment by tagliala** [comment]
Looks like a browser issue, reproduced without Font Awesome: https://tagliala.github.io/fa16267-nofa.html

@Chri-B please report this to Mozilla, let keep us up to date

**Comment by tagliala** [comment]
@Chri-B I cannot reproduce this on Firefox 77.0.1 

I'm going to close here, but I would like to add a reference to the mozilla bugtracker, if you have one
