### ISSUE TITLE
Back to top

### ISSUE THREAD

**Issue by Techboyreal** [FortAwesome/Font-Awesome#16278]
Scroll to top button

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that the following Pro icons do the job:

- https://fontawesome.com/icons/arrow-to-top?style=solid
- https://fontawesome.com/icons/arrow-alt-to-top?style=solid

Also, there are free icons that can fit this use case

- https://fontawesome.com/icons?d=gallery&q=up&s=solid&c=arrows&m=free

Hope it helps

Closing here
