### ISSUE TITLE
unity logo don't work 

### ISSUE THREAD

**Issue by TryndaFullStuff** [FortAwesome/Font-Awesome#16277]
https://origin-staging.fontawesome.com/icons/unity

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't confirm.

PS: where does the subdomain `origin-staging` comes from?

Please use `www` or the naked domain: https://fontawesome.com/icons/unity

![image](https://user-images.githubusercontent.com/556268/76023107-ccf28d80-5f28-11ea-8c64-2c4040070bd7.png)

Closing here
