### ISSUE TITLE
Brand icons now showing

### ISSUE THREAD

**Issue by AJVA2580** [FortAwesome/Font-Awesome#16281]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
- I am building a simple HTML file and I am trying to add Font awesome brand icons but they are not showing.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

- NA

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
I would like to see the icons

**Screenshots**
I can see the letters but not Icones 

My code 
```

<footer class="footer">
            <!-- Replace with my email address-->
            <a href="mailto:hello@myemail.ca" class="footer__link">hello@myemail.ca</a>
            <ul class="social-list">
                <li class="social-list__item">
                    <a class="social-list__link" href="https://codepen.io"><i class="fab fa-codepen"></i></a></li>
                <li class="social-list__item">
                    <a class="social-list__link" href="https://codepen.io">b</a></li>
                <li class="social-list__item"><a class="social-list__link"
                href="https://twitter.io">c</a></li>
                <li class="social-list__item"><a class="social-list__link"
                href="https://github.io"><i class="fab fa-github"></i> </a></li>
            </ul>
        </footer>
```

![Screen Shot 2020-03-06 at 6 47 05 AM](https://user-images.githubusercontent.com/35407721/76092621-b2063480-5f8d-11ea-9193-f02a972eba10.png)

**Version and implementation**
Version: 
Browser and version: 

- [ ] Web Fonts with CSS

**Bug report checklist**
- [x ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi @AJVA2580 

thanks for waiting my answer

Could you please provide a reproducible test case?

Cannot replicate: https://jsfiddle.net/tagliala/tr0gjszn/2/

Meanwhile, closing here
