### ISSUE TITLE
Icon request: electronic symbols (transistor, etc)

### ISSUE THREAD

**Issue by RichardNeill** [FortAwesome/Font-Awesome#16287]
** Requesting various circuit/component symbols,  such as these (though perhaps in simplified form) https://en.wikipedia.org/wiki/Electronic_symbol

I propose, in particular:

* Transistor  (NPN).
Example: https://en.wikipedia.org/wiki/File:BJT_NPN_symbol_(case).svg
although the B,C,E labels could be removed.
[optionally also: PNP or FET]

* Resistor   - the "ANSI" version not the "IEC" one,
Example: https://en.wikipedia.org/wiki/File:Resistor,_Rheostat_(variable_resistor),_and_Potentiometer_symbols.svg
(use the one labelled "a")

* Capacitor:
Example: https://en.wikipedia.org/wiki/File:Capacitor_Symbol.svg

* Diode
Example: https://en.wikipedia.org/wiki/File:Diode_symbol.svg
although exclude the labels "anode","cathode" and perhaps shorten the legs a little.
The triangle is often solid rather than outline.

* LED (light-emitting diode)
Example: https://en.wikipedia.org/wiki/File:LED_symbol.svg
remove the labels anode/cathode,  and often LEDs have a circle surrounding them as per the transistor)

* Logic symbols : AND, NAND,Or,XOR,NOT.
https://en.wikipedia.org/wiki/File:Circuit_elements.svg
(the lead-in/lead-out wires are optional)

* Op-amp:
https://en.wikipedia.org/wiki/File:Op-amp_symbol.svg
though this could be simplified just to be the triangle, with the + and - on the inputs.

(and of course there are many more one might add: inductor, switch,DIL IC,)

**What can it be used for?**

The various electronic symbols can be used either as generic "tech emblems" or to represent the items themselves. The logic gates are also useful as math symbols and perhaps for the various logical rules. Diode symbol is useful for indicating flow direction. Op-amp useful as an "amplifier" symbol.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't leave this open. This request does not meet the following point:

> This is a single icon or matched pair (Ex: lock / unlock)

If you are a Font Awesome Pro costumer, you can request icon sets at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Proc customer but you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here

**Comment by RichardNeill** [comment]
Is it possible to be a FontAwesomePro customer and request icons that will go into the non-Pro iconset? I would be happy to contribute something financially, but we can't take non-open-source-licensed items into our codebase.

**Comment by tagliala** [comment]
> Is it possible to be a FontAwesomePro customer and request icons that will go into the non-Pro iconset? 

It is possible to sponsor icons, please send an email to hello@fontawesome.com

Ref: https://fontawesome.com/community/leaderboard/new#faqs
