### ISSUE TITLE
Icon Request: fa-yahoo (update)

### ISSUE THREAD

**Issue by coliff** [FortAwesome/Font-Awesome#16288]
The icon for Yahoo is an old one. (https://fontawesome.com/icons/yahoo?style=brands)

I'd like to see it updated to something like: https://s.yimg.com/rz/l/favicon.ico (favicon from https://www.yahoo.com/)

There's an SVG version here too: https://s.yimg.com/cv/apiv2/default/icons/favicon_y19_32x32_custom.svg

I did search to see if this request had already been made and the only other mention I found was a comment in the request for a Yahoo Japan icon (https://github.com/FortAwesome/Font-Awesome/issues/7752)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by tagliala** [comment]
Hi,

icon available in 5.13.1

https://fontawesome.com/icons/yahoo?style=brands
