### ISSUE TITLE
Icon request: Need FullScren and ExitFullScreen icons

### ISSUE THREAD

**Issue by mohanelankuppan** [FortAwesome/Font-Awesome#16298]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
In my project want to use on click full screen will maximize my application, on exit will minimize my application

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/45821696/76315694-385ca680-62ff-11ea-95fe-afe2cca1c4a5.png)
![image](https://user-images.githubusercontent.com/45821696/76315709-3db9f100-62ff-11ea-98ce-7be8d98df287.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The following icons should fit your use case:
- https://fontawesome.com/icons/expand-arrows-alt?style=solid
- https://fontawesome.com/icons/compress-arrows-alt?style=solid
- https://fontawesome.com/icons/compress?style=solid
- https://fontawesome.com/icons/expand?style=solid

Hope it helps

Closing here, but feel free to comment

**Comment by mohanelankuppan** [comment]
May i know compress icon are in which release? I am using 4.7

**Comment by tagliala** [comment]
@mohanelankuppan hi, please update to FA5: FA 4 is on EOL.

https://fontawesome.com/start
