### ISSUE TITLE
get a callback from i2svg with kits

### ISSUE THREAD

**Issue by LeaTark** [FortAwesome/Font-Awesome#16309]
Is it possible to get a callback from i2svg with kits?

[https://fontawesome.com/how-to-use/with-the-api/methods/dom-i2svg](https://fontawesome.com/how-to-use/with-the-api/methods/dom-i2svg)

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole is this possible?

**Comment by robmadole** [comment]
@LeaTark you can. But it's not exactly pretty.

Here's an example: https://codepen.io/fontawesome/pen/LYVdGJj

**Comment by LeaTark** [comment]
> @LeaTark you can. But it's not exactly pretty.
> 
> Here's an example: https://codepen.io/fontawesome/pen/LYVdGJj

Thanks @robmadole 

I wonder how much of a delay this might introduce or what kind or performance hit there'd be right when everything else is trying to load.

It's certainly a better supported solution than the ResizeObserver I'm currently working with.

Thank you.

**Comment by robmadole** [comment]
At some point we can think about producing an API for Kits that is more friendly toward something like this. We just don't have that yet 😀
