### ISSUE TITLE
@fortawesome/fontawesome-free@latest is not in the npm registry

### ISSUE THREAD

**Issue by dereknelsen** [FortAwesome/Font-Awesome#16308]
**Describe the bug**
After trying to go through the normal process of installing fontawesome-free on a project, npm is throwing errors that fontawesome-free doesn't exist in the npm registry. Looking at the npm website here [https://www.npmjs.com/package/@fortawesome/fontawesome-free](url) shows that everything (readme, files, etc.) is missing.

**To Reproduce**
npm install --save @fortawesome/fontawesome-free

**Expected behavior**
npm installs the package as normal

**Logs**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.13.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@fortawesome/fontawesome-free' ]
2 info using npm@6.14.2
3 info using node@v11.13.0
4 verbose npm-session cbe82a842739fd72
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://npm.fontawesome.com/FA565DEB-383F-4765-BAD9-F5A35D26EAF8/@fortawesome%2ffontawesome-free 349ms
8 http fetch GET 404 https://npm.fontawesome.com/FA565DEB-383F-4765-BAD9-F5A35D26EAF8/@fortawesome%2ffontawesome-free 201ms
9 silly fetchPackageMetaData error for @fortawesome/fontawesome-free@latest 404 Not Found - GET https://npm.fontawesome.com/FA565DEB-383F-4765-BAD9-F5A35D26EAF8/@fortawesome%2ffontawesome-free
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 6062ms
12 verbose stack Error: 404 Not Found - GET https://npm.fontawesome.com/FA565DEB-383F-4765-BAD9-F5A35D26EAF8/@fortawesome%2ffontawesome-free
12 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:86:5)
13 verbose statusCode 404
14 verbose pkgid @fortawesome/fontawesome-free@latest
15 verbose cwd /Volumes/c$/Users/username/source/project/projectname
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/Cellar/node/11.13.0/bin/node" "/usr/local/bin/npm" "install" "--save" "@fortawesome/fontawesome-free"
18 verbose node v11.13.0
19 verbose npm  v6.14.2
20 error code E404
21 error 404 Not Found - GET https://npm.fontawesome.com/FA565DEB-383F-4765-BAD9-F5A35D26EAF8/@fortawesome%2ffontawesome-free
22 error 404
23 error 404 '@fortawesome/fontawesome-free@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```

**Version and implementation**
Version: 5.12.1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that you are using the private NPM repo with the old authentication method.

Also, I can see that you have inadvertently disclosed your secret token. I've edited the post, but you should go to https://fontawesome.com/account#pro-npm-tokens and regenerate the token

Then please follow our new docs to configure `.npmrc`: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

Hope it helps

Closing here, but feel free to comment

**Comment by dereknelsen** [comment]
Thanks for the edit!

The issue was that the free version of fontawesome was also looking at the @fortawesome:registry token for some reason. Deleting this config line from  .npmrc fixed the issue.

**Comment by tagliala** [comment]
@dereknelsen you're welcome! but if you are still a Pro customer and that token is valid, please regenerate it
