### ISSUE TITLE
some geologic icon requests

### ISSUE THREAD

**Issue by iamplug** [FortAwesome/Font-Awesome#16302]
We have a number of geologically related icons we'd love have:

oil well
landslide
quarry and/or mine
rock
sinkhole
hammer and pick

Thanks!
-Doug Curl 
Kentucky Geological Survey

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, we do not accept requests for icon set in our free repository.

If you are a Font Awesome Pro customer, you can request Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
