### ISSUE TITLE
Npm Not found 

### ISSUE THREAD

**Issue by zackmoun** [FortAwesome/Font-Awesome#16316]
Hello, 
I tried to install some npm such as: @fortawesome/pro-solid-svg-icons@latest and @fortawesome/pro-regular-svg-icons@latest
but I got these error messages: 
'@fortawesome/pro-solid-svg-icons@latest' is not in the npm registry.
'@fortawesome/pro-regular-svg-icons@latest' is not in the npm registry.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check your `.npmrc` configuration? 

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

```
$ npm install --save @fortawesome/pro-solid-svg-icons@latest
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN fa5pro@1.0.0 No description
npm WARN fa5pro@1.0.0 No repository field.

+ @fortawesome/pro-solid-svg-icons@5.12.1
updated 2 packages and audited 2 packages in 6.907s
found 0 vulnerabilities
```

**Comment by zackmoun** [comment]
Thanks. tagliala

**Comment by tagliala** [comment]
@zackmoun has this been solved?

**Comment by zackmoun** [comment]
@tagliala yes, the problem solved, thanks :)
