### ISSUE TITLE
Icon request: Sports-related icons

### ISSUE THREAD

**Issue by luiscabanillas** [FortAwesome/Font-Awesome#1631]
It would be great if you can add some sports-related icons like:

-Balls (Baseball, Football, Soccer, Basketball, Tenis, Golf, etc)
-Accessories (Baseball helmet/cap/bat/glove, Football helmet, Soccer shoes, Basketball basket, etc.)
-General sports icons: running, swimming, wrestling, gymnastics, etc.

Thanks!

**Comment by zeebe** [comment]
+1 for all sports icons

**Comment by tagliala** [comment]
I should probably close this request since it is not popular and it doesn't meet our contributing guidelines

**Comment by bverhallen** [comment]
+1 for sports icons

**Comment by WolfgangVonL** [comment]
+1 for main sports icons (soccer, football, basket, rugby, tennis, golf, motor racing)

**Comment by tagliala** [comment]
Sorry, I can't keep this issue open, as per our contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

PS: soccer is already here
