### ISSUE TITLE
Icon request: Text Editor or IDE

### ISSUE THREAD

**Issue by firmanjabar** [FortAwesome/Font-Awesome#16314]
Need icon text editor or IDE like notepad, notepad++, vscode, sublime, atom, intelliJ, android studio, etc.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single color, 16px icon size suitable example of how this icon should look like?

**Comment by firmanjabar** [comment]
vscode:
![vscode](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/64px-Visual_Studio_Code_1.35_icon.svg.png)

intelliJ:
![intelliJ](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/IntelliJ_IDEA_Logo.svg/64px-IntelliJ_IDEA_Logo.svg.png)

Notepad++:
![Notepad++](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Notepad%2B%2B_Logo.png/128px-Notepad%2B%2B_Logo.png)

Sublime:
![Sublime](https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Sublime_Text_3_logo.png/150px-Sublime_Text_3_logo.png)

**Comment by tagliala** [comment]
Ok, thanks.

Please open individual requests having care of searching for duplicates before (eg: #16231 )
