### ISSUE TITLE
Twitter Icon and Its Guideline

### ISSUE THREAD

**Issue by MokkeMeguru** [FortAwesome/Font-Awesome#16318]
ref. #9224
I think some website use your Twitter Icon without official blue/white color.

I wonder we can use it with some color e.g. black.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please read the copyright note in any brand icon page: https://fontawesome.com/icons/twitter

> This work includes material that may be protected as a trademark in some jurisdictions. If you want to use it, you have to ensure that you have the legal right to do so and that you do not infringe any trademark rights. The use of these trademarks does not indicate endorsement of the trademark holder by Font Awesome, nor vice versa. See the trademark owner for rules about appropriate use of their trademarks.

Hope it helps

Closing here
