### ISSUE TITLE
Icon request: Coronavirus (COVID-19)

### ISSUE THREAD

**Issue by iamazik** [FortAwesome/Font-Awesome#16315]
To all the designers, why don't we create an icon specifically for Corona (COVID-19) like a kind of virus symbol, maybe a shield but not exactly that. There are already some on other icons library but would love to see some on font awesome.

I am not a designer though but would love to help if I can :)

**Comment by jeisel-northglenn** [comment]
They do have a 'disease' icon - not sure if that's what you're looking for.

I was hoping for soap and/or tissues. All the other stuff I was able to piece together from the available icons.

**Comment by iamazik** [comment]
Disease icon doesn't really look like a virus to me since COVID-19 is a serious one that the world will remember for a long time. I am thinking something similar to a virus 😃

**Comment by luger19** [comment]
This is a good idea!

**Comment by sensibleworld** [comment]
Hoping to get an update out soon with some new additions.

**Comment by riginoommen** [comment]
This is a good proposal at this moment. Many web tools and services can make use of it. like covidout.in

**Comment by sensibleworld** [comment]
Latest release is out: https://fontawesome.com/changelog/latest

**Comment by iamazik** [comment]
Yay! What an awesome gift. Thanks man 👏

**Comment by Araw830** [comment]
can you please design a Telemedicine icon.................

**Comment by tagliala** [comment]
@Araw830 feel free to make a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by batisteo** [comment]
Oh gosh, there’s toilet paper under this tag :joy:

**Comment by AncestorHunter06** [comment]
There are several sets [here](https://www.iconfinder.com/p/coronavirus-awareness-icons).

This is one of my personal favorites, though.
[Just Icon: COVID-19](https://www.iconfinder.com/iconsets/covid-19-2?utm_campaign=Virus%20awareness&utm_medium=landing%20page&utm_source=Webflow&utm_content=Covid%20nineteen%20by%20Just%20Icon)

**Comment by Araw830** [comment]
> @Araw830 feel free to make a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Yeah Sure....

**Comment by Araw830** [comment]
> There are several sets [here](https://www.iconfinder.com/p/coronavirus-awareness-icons).
> 
> This is one of my personal favorites, though.
> [Just Icon: COVID-19](https://www.iconfinder.com/iconsets/covid-19-2?utm_campaign=Virus%20awareness&utm_medium=landing%20page&utm_source=Webflow&utm_content=Covid%20nineteen%20by%20Just%20Icon)

Branding Work....
