### ISSUE TITLE
Using free kit. Some icons are missing in font.

### ISSUE THREAD

**Issue by codexsoft** [FortAwesome/Font-Awesome#16311]
**Describe the bug**
**To Reproduce**

```
<script src="https://kit.fontawesome.com/***.js" crossorigin="anonymous"></script>
...
<i class="fab fa-instagram-square fa-3x"></i>
<i class="fab fa-phone-square fa-3x"></i>
```
icon with .fa-phone-square renders as empty square (missing symbol in font). Removing **fa-3x** makes no difference. CSS class is successfuly applied from free.min.css:
```
.fa-phone-square:before {
    content: "\f098";
}
```
but seems that wrong font (not "Font Awesome 5 Brands") is used for symbol rendering or something like this...

**Expected behavior**
Icon **fa-instagram-square** is rendered as described at https://fontawesome.com/icons/phone-square?style=solid

**Screenshots**
![test](https://user-images.githubusercontent.com/29902572/76575305-54c03500-64f1-11ea-9244-cba48c32d60a.jpg)

**Version and implementation**
Google Chrome Версия 80.0.3987.132 (Официальная сборка), (64 бит)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> `fab fa-phone-square fa-3x`

`fa-phone` requires the `fas` prefix. `fab` is for brands

> fab fa-instagram-square fa-3x

About this one, it is possible that the kit is using an older version of font awesome that does not iclude `fa-instagram-square`, added in [5.12.1](https://fontawesome.com/icons/instagram-square?style=brands). Feel free to disclose the Kit ID

Ref: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by codexsoft** [comment]
Oh, I see, my fail, thank you very much and excuse me for disturbing! Have a nice day!

**Comment by tagliala** [comment]
No problem 👍
