### ISSUE TITLE
Icon request: edge-legacy

### ISSUE THREAD

**Issue by DictationScratchPad** [FortAwesome/Font-Awesome#16328]
**What can it be used for?**
Edge has been updated to use Chromium and now sports a new logo! However the old Edge browser [Microsoft Edge Legacy](https://support.microsoft.com/en-us/help/4533505/what-is-microsoft-edge-legacy) is not replaced automatically. Users are required to manually update. The logos, both old and new, are therefore still relevant to show.

**Example image (optional)**
![Edge](https://www.underconsideration.com/brandnew/archives/microsoft_edge_2019_logo_before_after.jpg "Old and new Edge logo")

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for pointing this out

@sensibleworld any chance to resurrect the old logo as `edge-legacy` ?

**Comment by DictationScratchPad** [comment]
I would also like to emphasize that Edge Legacy is still the default browser on Windows 10.

**Comment by tagliala** [comment]
Hi,

this icon is resurrected in 5.13.1

https://fontawesome.com/icons/edge-legacy?style=brands
