### ISSUE TITLE
Icon request: quote-round-right

### ISSUE THREAD

**Issue by shworan** [FortAwesome/Font-Awesome#16324]
Quotation Marks icons would be very useful for putting near testimonials or quotes on a page.  Currently the quotation mark icon from Fontawesome is very blocky (square).
quote-right and quote-left

I am requesting a more rounded version...

![image](https://user-images.githubusercontent.com/62219973/76710567-cfda4480-66c5-11ea-9ecc-98db79640ea2.png)

quote-round-right and quote-round-left could be the name

This is the existing fontawesome icon...  
![image](https://user-images.githubusercontent.com/62219973/76710690-d5845a00-66c6-11ea-8e31-ad3bd9f14fda.png)

 [YES ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by gewissen-digital** [comment]
Yes, this icon is required. box icon doesn't suit the design well for some themes.

**Comment by tagliala** [comment]
In FA6 the icons are now round

https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=quote&s=solid

Feel free to request design variations, but please keep in mind that icons in Font Awesome should be coherent among themselves rather than any other use case.

If rounded quotes feel more natural in the set, then the quotes will be rounded, otherwise - like in FA5 - they can have different corners

**Comment by hudri** [comment]
I'm sorry, but for me the new v6 quote icon is enemy of the state no. 1 :-(

The old v5 ones have been blocky, but at least looked like quotes. The new quotes don't look like quotes at all, they are numbers! In the icons above, the line going away from the bullet is fairly straight, with only a slight curve. In 6, the line going away from the bullet makes a heavy turn/curve, which totally turns the qutoes into sixes and nines.

A round style like the one from shworan is dearly missed

**Comment by brandonpeat** [comment]
> The new quotes don't look like quotes at all, they are numbers!

+1 to this, agree completely.

**Comment by sensibleworld** [comment]
The current quotes have been updated to be blockier, again: https://fontawesome.com/icons/quote-right?f=classic&s=solid

In relation to this request, a more rounded/delicate version doesn't seem quite in line with our current design guidelines. Going to close this request.
