### ISSUE TITLE
'findIconDefinition' is not exported by node_modules\@fortawesome\fontawesome-svg-core\index.js when trying to bundle UMD using rollup

### ISSUE THREAD

**Issue by yukipastelcat** [FortAwesome/Font-Awesome#16329]
**Describe the bug**
I'm importing `@fortawesome\fontawesome-svg-core` package inside Svelte component, and trying to create umd bundle using rollup and getting this error:

```
Error: 'findIconDefinition' is not exported by node_modules\@fortawesome\fontawesome-svg-core\index.js, imported by src\FontAwesomeIcon.svelte
```

This doesn't seem to have something to do with Svelte compilation, since I tried to remove exports of .svelte components from index.js and replaced it with following code:

```
import {
  parse as faParse,
  icon as faIcon,
  findIconDefinition as faFindIconDefinition
} from "@fortawesome/fontawesome-svg-core";
```

When bundling following code I'm getting `Import of non-existent exports` warning

```
> fontawesome-svelte@1.0.0-beta.15 build D:\Users\yukipastelcat\Documents\Repositories\GitHub\svelte-fontawesome
> rollup -c


src/index.js → ./dist/fontawesome-svelte.esm.js...
(!) Unused external imports
parse,icon,findIconDefinition imported from external module '@fortawesome/fontawesome-svg-core' but never used
created ./dist/fontawesome-svelte.esm.js in 886ms

src/index.js → ./dist/fontawesome-svelte.umd.js...
(!) Import of non-existent exports
src\index.js
1: import { parse as faParse, icon as faIcon, findIconDefinition as faFindIconDefinition } from "@fortawesome/fontawesome-svg-core"; // export { default as FontAwesomeIcon } from './FontAwesomeIcon.svelte';
            ^
2: // export { default as FontAwesomeLayers } from './FontAwesomeLayers.svelte';
3: // export { default as FontAwesomeLayersText } from './FontAwesomeLayersText.svelte';
...and 2 other occurrences
created ./dist/fontawesome-svelte.umd.js in 1.9s
```

**To Reproduce**
https://github.com/yukipastelcat/svelte-fontawesome/tree/feature/ssr-support

To reproduce issue install dependencies and run `npm run build`.

**Expected behavior**
Build works normally with rollup when creating umd bundle.

**Version and implementation**
Version: 1.2.26

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the detailed report.

I'm not a node developer

In a minimal environment, with just Font Awesome, I cannot replicate: https://codesandbox.io/s/elated-thunder-7y54h

I've also tried locally with rollup

rollup.config.js

```js
export default {
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'umd',
    globals: {
      '@fortawesome/fontawesome-svg-core' : 'fontawesomeSvgCore'
    }
  },
  external: [ '@fortawesome/fontawesome-svg-core' ]
};
```

main.js
```js
import {
  parse as faParse,
  icon as faIcon,
  findIconDefinition as faFindIconDefinition
} from "@fortawesome/fontawesome-svg-core";

console.log(faParse);
console.log(faIcon);
console.log(faFindIconDefinition);
```

Output:
```
$ node -v
v13.11.0
$ npm -v
6.14.3
$ rollup -v
rollup v2.1.0
$ rollup -c rollup.config.js 

main.js → bundle.js...
created bundle.js in 10ms
$ node bundle.js 
{ transform: [Function: transform] }
[Function (anonymous)]
[Function: findIconDefinition]
```

**Comment by yukipastelcat** [comment]
Looks like the problem was solved in newer versions.
