### ISSUE TITLE
Icon request: drag-dots

### ISSUE THREAD

**Issue by shworan** [FortAwesome/Font-Awesome#16323]
A decent drag indicator for indicating components can move around on a page.
Currently you have one that is squares and is very heavy.  It is not well designed and one with round drag dots would be more appropriate/standard.

![image](https://user-images.githubusercontent.com/62219973/76710341-0adb7880-66c4-11ea-8d50-d786fddb360d.png)

This is a single icon but could have a vertical and a horizontal version.  In addition, regular and light versions could have different dot sizes.  

One thing to look at is the exiting ellipsis-v and ellipsis-h icons that you already have.  Think of those as doubled. 

This is the existing drag icon at Fontawesome....
![image](https://user-images.githubusercontent.com/62219973/76710726-1bd9b900-66c7-11ea-85b3-9f5c21d3e8cf.png)

[ YES ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by dylanmahler** [comment]
@shworan I would love to see this implemented!

Running into this same issue. We use primarily light or regular icons in our product and this is a frequently used icon for drag and drop features. The square grip handles are adding too much visual weight, where the content is no longer the focus. We've explored reducing the color of the icon if located next to text, but it still appears inconsistent with the rest of the icon system.

![image](https://user-images.githubusercontent.com/17200745/82558479-592d4d80-9b33-11ea-8207-e6c84ff703b9.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/grip-dots-vertical?s=solid
