### ISSUE TITLE
Icon request: face-mask

### ISSUE THREAD

**Issue by TechOverflow** [FortAwesome/Font-Awesome#16338]
**What can it be used for?**
In light of recent events, a face-mask icon would be nice.

**Example image (optional)**
https://previews.123rf.com/images/barks/barks1903/barks190300076/119203229-face-mask-flu-mask-icon-man-.jpg

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi, this is coming 👍

**Comment by TechOverflow** [comment]
Great job, guys!
