### ISSUE TITLE
Icon request: book

### ISSUE THREAD

**Issue by CarlosBG16** [FortAwesome/Font-Awesome#16337]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi, we have a lot of book related icons

https://fontawesome.com/icons?d=gallery&q=book

Hope it helps

Closing here

**Comment by CarlosBG16** [comment]
Ok .
Thanks

A quinta, 19/03/2020, 18:34, Geremia Taglialatela <notifications@github.com>
escreveu:
