### ISSUE TITLE
Why kaaba icon not working ?

### ISSUE THREAD

**Issue by rmhridoy** [FortAwesome/Font-Awesome#16343]
Kaaba icon not working my local file why this problem?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-kaaba](https://fontawesome.com/icons/kaaba?style=solid) has been introduced in version 5.3.0

Please make sure that you are using FA 5.3.0 or newer

Troubleshooting:
- WEB: https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting#icon-noshow
- DESKTOP: https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting#updating

Hope it helps

Closing here
