### ISSUE TITLE
Icon request: webflow

### ISSUE THREAD

**Issue by Pckool** [FortAwesome/Font-Awesome#16345]
**What can it be used for?**
This icon would be used for the same purpose as any other brand icon. It is a simple way to represent a brand, in this case, the website building tool WebFlow.

**Example image (optional)**
https://d3e54v103j8qbb.cloudfront.net/img/webflow-black.ef3f174957.svg

**Icon request checklist**
- [✔ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ✔] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ✔] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ✔] I have included at least one example image if it could be helpful (optional)
- [ ✔] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by alxdxn** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/webflow?f=brands&s=solid
