### ISSUE TITLE
Duotone fa-magic-wand

### ISSUE THREAD

**Issue by tbone849** [FortAwesome/Font-Awesome#16351]
The spikes on the duotone wand are lumped in with the secondary color and the stars. I believe they should be part of the wand. Very minor issue, but would look better if fixed.

DUOTONE
![image](https://user-images.githubusercontent.com/11409836/77337393-37644580-6cff-11ea-87a5-f45bc61efbd3.png)

JUST THE WAND
![image](https://user-images.githubusercontent.com/11409836/77337555-6bd80180-6cff-11ea-876d-d2e575dfb4ce.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is intended, and those spikes are supposed to be stars in the background, but let's check with @sensibleworld

**Comment by tbone849** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> I think this is intended, and those spikes are supposed to be stars in the background, but let's check with @sensibleworld

I thought so too, until I checked the wand by itself. (second pic)

**Comment by sensibleworld** [comment]
Nope. This is an error! Sorry about that. Will get it fixed.

**Comment by sensibleworld** [comment]
We've got this fixed in the latest v6 Alpha release: http://fontawesome.com/download
