### ISSUE TITLE
fab fa-instagram-square is not working

### ISSUE THREAD

**Issue by jessica6994** [FortAwesome/Font-Awesome#16359]
I am using this cdn with the latest version of font awesome:
`<link href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" rel="stylesheet" />`

All other square icons I am using are working: Facebook, LinkedIn and Twitter.`
The link wrapped around the Instagram icon is present but no icon is showing.

 The icon is added into the project the same as the other mentioned above:
`<a href=""><i class="fab fa-instagram-square p-1"></i></a>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

That  is expected because `instagram-square` has been introduced in version 5.12.1

Ref: https://fontawesome.com/icons/instagram-square?style=brands 

Please update

Hope it helps

Closing here
