### ISSUE TITLE
wrong aspect ratio when set font-size to 12px

### ISSUE THREAD

**Issue by witcat** [FortAwesome/Font-Awesome#16362]
**Describe the bug**
wrong aspect ratio when set font-size to 12px

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**
12px:  
![C526BC39-5418-45ED-BE3E-470F35A117BC](https://user-images.githubusercontent.com/19653028/77458846-c70e0f00-6e39-11ea-9ba2-4452fa40bbdc.png)
16px:  
![F2133137-A059-49AB-8DEF-C1A5DA9AF1FF](https://user-images.githubusercontent.com/19653028/77458848-c83f3c00-6e39-11ea-8354-2f5c1d80f79d.png)

**Version and implementation**
Version: 1.2.26
Browser and version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this related to the light version of this icon in Font Awesome Pro?

https://jsfiddle.net/tagliala/zrcxo5d8/3/

![image](https://user-images.githubusercontent.com/556268/78502172-ef620b80-775f-11ea-955a-991cb9e73c40.png)

Figure: `fas fa-times`, `far fa-times`, `fal fa-times` at 16px, 12px, 18px


I can see just a slightly distortion on MacBook Pro retina display

I'm not sure we can guarantee pixel perfections of icons (in particular the light one) for any font size, (in particular for small sizes)

![image](https://user-images.githubusercontent.com/556268/78502180-0143ae80-7760-11ea-82ec-f3f013c18194.png)

Figure: `fal fa-circle` at 16px, 12px, and 8px

**Comment by witcat** [comment]
I found the faTimes icon has a .fa-w-10 className,it set SVG element's Width to 0.625em.
disable this className or set SVG element to 1em, the icon will be displayed correctly.
but some icons will take up a wider space

**Comment by tagliala** [comment]
@witcat thanks for the heads-up

> disable this className or set SVG element's width to 1em, the icon will be displayed correctly.

Yes, maybe some minor css adjustments are needed if you need different font sizes, but it has to be done by developer according to use cases.

This is an explanation of `fa-w-10` and `0.625em` come from.

We use a base grid of 16 units to design icons. [fal fa-times](https://fontawesome.com/icons/times?style=light) is 10 unit wide, so 10/16, so 0.625.

If you are going to change the base grid to 12 px, then the icon will occupy 7,5 pixels, and it _may_ render better at 8px, so you should probably go for `0.66667em`

Ref: https://jsfiddle.net/tagliala/zrcxo5d8/6/

![image](https://user-images.githubusercontent.com/556268/78673171-0af51f80-78e2-11ea-9ff4-43b0b022edd1.png)

Hope it helps
