### ISSUE TITLE
Icons missing in categories.yml

### ISSUE THREAD

**Issue by alvarotrigo** [FortAwesome/Font-Awesome#16369]
I'm trying to get metadata for all the icons and I'm interested in getting the categories for each possible icon.

However, not all icons are on the [categories.yml file you guys provide](https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/categories.yml).

In fact, some like `500px`, `facebook`, `twitter` that were in fontawesome v4 under the `Brands icons` category are nowhere now, under no category. 

This creates a problem in our side as we can't categorise all icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole should we add a `brands` category?

**Comment by robmadole** [comment]
Brands was broken out into it's own style in Font Awesome 5. So you would need to parse the [icons.yml](https://github.com/FortAwesome/Font-Awesome/blob/master/metadata/icons.yml) file and filter for `styles: brands` from there.

**Comment by robmadole** [comment]
@tagliala I don't think so. We have re-enforced the separation of brands from the other icons. And I think we want to stick with that.

**Comment by alvarotrigo** [comment]
I'm not sure what's your purpose of having those metadata files, but if they mean to help developers like me to integrate Font Awesome in web applications, then the file as it is now is making things more difficult for us.

If we want to provide our users a way to filter by category, we clearly need to add the `brands` category too. But now, we have to do the job ourselves instead of relying on the official library metadata.

We have to:

- Parse icons.json and look for all `brands` styles.
- Then parse `categories.yml` 
- Add the brands category and it's icons.
- Then convert `categories.yml` to `json` format.


And not considering we might want to have a proper list with icons and categories in a single `json` file.
At the moment we have to:

- Read `categories.yml` and parse it.
- Read `icon.json`
- Do magic here to add all categories in each icon in `icon.json`

Now we have a list wit all icons + all icons properties + categories. 1 hour we could have saved :)

**Comment by robmadole** [comment]
Sorry @alvarotrigo this is not in the format you'd like. Those metadata files are just 1-to-1 copies of the source files we use to build Font Awesome with our tooling. We're not manipulating them–they are what is most convenient for our own system.

It's also important to note, as I eluded to before, that for version 5 brands is its own style. This is an important distinction in our opinion. So by you putting brand icons back in to the categories you are actually using a construct from version 4 that we have deliberately removed. There is unfortunately going to be some work for you if you disagree with this direction.

We've been working on a GraphQL API for a while and that's where our future efforts will most likely focus. This could be a more familiar or easier way to access stuff.
