### ISSUE TITLE
Icon request: truck-tow

### ISSUE THREAD

**Issue by mjcampagna** [FortAwesome/Font-Awesome#16370]
**What can it be used for?**

It's a tow truck! My company is in roadside assistance, and we would use the tow truck all over the place, for sure.

If only one icon, then I suppose the class winch-style, with the raised hook on the back of the truck. If multiple icons, then winch, flat-bed, loaded (with vehicle in tow) and unloaded ... lots of flexibility here for design. There are light, medium and heavy duty trucks, etc.

In general, I would love to see more service vehicle representation. I see a lot of icons for delivery vehicles, and not much else.

(there are similar, past requests, but from FontAwesome 4 days and 4-5 years old; hopefully this new request passes current guidelines)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> there are similar, past requests, but from FontAwesome 4 days and 4-5 years old; hopefully this new request passes current guidelines)

Thanks for opening a new request meeting contributing guidelines, but at the time we didn't have contributing guidelines so old requests are more than fine. Please 👍 #4972

If you are wondering why requests form 2013 are still here, you can take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information on how requests work

Hope it helps

Closing here
