### ISSUE TITLE
Feature Request: Add cache busting to webfonts

### ISSUE THREAD

**Issue by dpeekstok** [FortAwesome/Font-Awesome#16375]
**Is your feature request related to a problem? Please describe.**
I recently upgraded to FontAwesome 5.13 and when I did, users were getting caching issues. The main css file, `all.min.css`, was up to date but the urls to the font files were still the same so browsers didn't update the fonts. Thus, instead of displaying the icons, users were seeing Asian characters.

**Describe the solution you'd like**
In each of the css files provided by FontAwesome, when making `url()` calls to the font files, the current FontAwesome version could be appended to the url. This change would be enough to force a browser to load the new version.

E.g.
`url("../webfonts/fa-brands-400.eot")`
would become
`url("../webfonts/fa-brands-400.eot?v=5.13.0")`

**Describe alternatives you've considered**
Appending other cache busting techniques would also work, such as a using a file hash. 

**Additional context**
These are the icons that users were seeing
![image](https://user-images.githubusercontent.com/10521217/77783185-cc807a80-702e-11ea-980c-a4c72b237aaf.png)

**Feature request checklist**
- [ X ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ X ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify if you are using the CDN or your own server?

**Comment by dpeekstok** [comment]
The files are locally hosted on our own server

**Comment by tagliala** [comment]
Ok, thanks.

We have deliberately removed version strings from font files some years ago to avoid caching issues .(ref: #3286). If you are serving Font Awesome files from your own servers, please use one of the following approach:
- Customize the CSS
- Fingerprint assets 
- Scope the font files inside a folder with version name (as we do in the CDN)

Hope it helps

Closing here
