### ISSUE TITLE
500 Internal Server Error - GET https://npm.fontawesome.com/@fortawesome%2fpro-solid-svg-icons

### ISSUE THREAD

**Issue by felix-voicehub** [FortAwesome/Font-Awesome#16378]
All my builds are failing because of `npm` failing here:

> 500 Internal Server Error - GET https://npm.fontawesome.com/@fortawesome%2fpro-solid-svg-icons

**Comment by lskillen** [comment]
Lee from @cloudsmith-io here (we service `npm.fontawesome.com` for Font Awesome); we're working on a major database upgrade within our maintenance window, and it's taking a bit longer than expected, but it's *very* nearly there. You can follow status updates on the [Cloudsmith Status Page](https://status.cloudsmith.io).

Apologies for any interruptions to your weekend build/delivery pipelines! Keeping you all up is extremely important to us, as it is important to the Font Awesome team too.

**Comment by felix-voicehub** [comment]
@lskillen Thanks! Working again.
