### ISSUE TITLE
Adding License Seats Not Working Properly

### ISSUE THREAD

**Issue by Bruno2049** [FortAwesome/Font-Awesome#16388]
When assigning License Seats the licenses are not activated.

Can you please help me with this?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please send an e-mail to hello@fontawesome.com

I'm going to close here (this issue tracker is for bugs and requests), but let me know if you didn't get answers in a reasonable time
