### ISSUE TITLE
Icon Request: fa- fa-virus

### ISSUE THREAD

**Issue by sunsekar** [FortAwesome/Font-Awesome#16392]
Hello there.

You folks are doing a great job and continue doing it.
Please work on "virus" icons for medical related apps like covid-19, ebola, influenza,etc

Also, please work on a common "symptom" icon for any medical related issues.
Thanks

regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at the newly released FA 5.13: https://fontawesome.com/icons?d=gallery&q=virus&m=free

> Also, please work on a common "symptom" icon for any medical related issues.

Feel free to start a new request, by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). Also please provide an example, __symptom__ is abstract

Hope it helps

Closing here
