### ISSUE TITLE
icon request: action-lines (movement lines, three lines as in star-shooting)

### ISSUE THREAD

**Issue by Yishmeray** [FortAwesome/Font-Awesome#16391]
**What can it be used for?**
With any existing icon to denote action/movement.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/60681976/77959962-b83db700-7294-11ea-9317-be501c547863.png)

the star-shooting icon has action lines already. 
![image](https://user-images.githubusercontent.com/60681976/77960159-0b176e80-7295-11ea-9513-fba210eb87a7.png)

the stream icon is close.
![image](https://user-images.githubusercontent.com/60681976/77960174-1074b900-7295-11ea-8163-8550d1234931.png)

could be something like this:
![image](https://user-images.githubusercontent.com/60681976/77960825-29ca3500-7296-11ea-8345-3ca4c15cb342.png)

or this:
![image](https://user-images.githubusercontent.com/60681976/77960855-32bb0680-7296-11ea-8995-c172bda3d305.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺) [it's not a concrete object, but it is a very common symbol used in cartooning, for example]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/align-left?style=solid fit your use case?

**Comment by Yishmeray** [comment]
> 
> 
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Does https://fontawesome.com/icons/align-left?style=solid fit your use case?

Hi Tagliala - well, it's OK. My own home-grown examples above were not meant to be prescriptive - just ideas about how a real artist might do action lines.

I don't think action lines usually come in the form you've suggested - short/long/short/long in a set of 4.

Witness the three action lines used on the existing star-shooting. 
Two lines are often used. Sometimes a cloud at their end.
I don't recall seeing 4. I could be mistaken!

Obviously the current fontawesome team saw the value of motion lines, or there wouldn't be any on the star-shooting! I just want to get that (or something similar) away from the star.

Thank you for the attention and response. Your suggestion is not entirely bad!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
