### ISSUE TITLE
Icon request: hive-chain

### ISSUE THREAD

**Issue by gryter** [FortAwesome/Font-Awesome#16393]
**What can it be used for?**
The icon would be used by people linking their Hive ecosystem frontends, projects, tools, blogs and accounts. 

Hive is a Graphene-based DPoS blockchain. Since it’s launch on March 20, 2020, Hive is growing and evolving day by day. It has a large ecosystem composed of a variety of innovative projects, many of which utilize Font Awesome. 

**Example image (optional)**
Branding is available here:
https://hive.io/brand (downloadable zip in a variety of formats linked off site)

<img width="219" alt="logo_transparent@2" src="https://user-images.githubusercontent.com/31012685/77990641-dab0ee00-72ef-11ea-8e46-e00498647555.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Vheissu** [comment]
Yes please. This would be great for my dApps.

**Comment by bala41288** [comment]
Yes this will be a nice one for Hive ecosystem.

**Comment by wehmoen** [comment]
This would be actually useful for 3speak.online. I hope this gets added soon :)

**Comment by meladoro** [comment]
Yes please! This would be wonderful to have. Thank you Font Awesome! ❤️

**Comment by Snaddyvitch-Dispenser** [comment]
I would love for this to be added to font-awesome!

**Comment by nachofigx** [comment]
That's something nice to have the Hive logo.

**Comment by BorislavZlatanov** [comment]
Would be super helpful to have the Hive logo.

**Comment by StuffBySpencer** [comment]
Considering how easy dapps are to create for Hive, and how many developers use Font-Awesome in said dapps, this would make for a great addition!

**Comment by tagliala** [comment]
Hi, 

Thanks for your enthusiasm in this request!

Please do not comment, just use reactions to upvote

Ref: https://fontawesome.com/community/leaderboard/brands#faqs

**Comment by tagliala** [comment]
This has been introduced in 5.15

https://fontawesome.com/icons/hive?s=solid&f=brands
