### ISSUE TITLE
Icon request: sack-check

### ISSUE THREAD

**Issue by Daniel4Digital** [FortAwesome/Font-Awesome#16397]
**What can it be used for?**
It can be used for valid sales, for example.

There is already some as sack, sack-dollar, this one could be sack-valid / sack-check and it could be done too the sack-times / sack-invalid

**Example image (optional)**
![Valid Sales](https://i.imgur.com/4mDMeP2.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/9k5vgr6q/4/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Daniel4Digital** [comment]
Thanks, but since I'm using duotone it makes it more difficult or even impossible to use the SVG one.

**Comment by tagliala** [comment]
> Thanks, but since I'm using duotone it makes it more difficult or even impossible to use the SVG one.

You mean this?

https://jsfiddle.net/tagliala/9k5vgr6q/6/

This is also doable with CSS, with the stack functionality: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons

https://jsfiddle.net/tagliala/goL9jwe5/9/

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
