### ISSUE TITLE
Shopify bug

### ISSUE THREAD

**Issue by stuscrim** [FortAwesome/Font-Awesome#16400]
Hi guys,

The Shopify icon fab fa-shopify is not displaying correctly for me. Instead of the Shopify logo I'm getting an Asian text character. I've checked this in Chrome, Firefox and Edge and all show the same. I have also checked this on my Microsoft notebook, my Android phone and iPad, all have the same issue.

Thannks in advance for the great icons!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-shopify](https://fontawesome.com/icons/shopify?style=brands) has been introduced in version 5.12.1, please make sure that your Font Awesome version is up to date.

https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

If you still have issues, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Hope it helps

Closing here
