### ISSUE TITLE
Chrome warned me about kit

### ISSUE THREAD

**Issue by umpire274** [FortAwesome/Font-Awesome#16402]
Hi all.

I'm developing a new site on Drupal 8 and I used in html template the call to my Pro kit:

`<script src="https://kit.fontawesome.com/xxxx.js" crossorigin="anonymous"></script>`

All icons are displayed well, but in console window of Chrome Inspector I found this warning message:

> A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

I don't know if I wrong something or it is real. You know that?

Alex.

**Comment by umpire274** [comment]
Hi again.

I found the issue #15643 similar to mine. I tried the solution proposed inside and the warning has gone.

This issue is closed.

**Comment by tagliala** [comment]
Hi,

>  I tried the solution proposed inside and the warning has gone.

Which solution? Please do not use `SameSite`, there are a few comments of mine there

**Comment by umpire274** [comment]
Hi Geremia.

I hav been answer to you in #15643.

Thanks.

**Comment by umpire274** [comment]
According with https://github.com/FortAwesome/Font-Awesome/issues/15643#issuecomment-606222380 I reopen this issue.

**Comment by tagliala** [comment]
Let's use #15643
