### ISSUE TITLE
vr-cardboard

### ISSUE THREAD

**Issue by alishabelle** [FortAwesome/Font-Awesome#16401]
**Describe the bug**
When  I try to use the vr-cardboard in my site it shows up as a question/explanation mark and will not render the icon needed. 

**Screenshots**

<img width="352" alt="Screen Shot 2020-03-31 at 8 38 49 PM" src="https://user-images.githubusercontent.com/33044111/78087573-7d6c7980-738f-11ea-80b7-3729d490e671.png">

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[vr-cardboard](https://fontawesome.com/icons/vr-cardboard?style=solid) has been introduced in version 5.4.0

It is possible that your web application uses an older version of Font Awesome.

Please also note that third-party themes/plugins/libraries may replace your Font Awesome version with an older one

Ref:
-https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

If you still have issues, please provide a reproducible test case

Hope it helps

Closing here
