### ISSUE TITLE
Icon Request: icon-screenshot vs icon-crosshair

### ISSUE THREAD

**Issue by zxfrank** [FortAwesome/Font-Awesome#1640]
I think the screenshot icon look more like a crosshair and I think it could look more like that: 
![screenshoticon](https://f.cloud.github.com/assets/1887075/848716/491dcc3c-f467-11e2-9e4c-1020e6c4b768.jpg)

My 2 cents

**Comment by sensibleworld** [comment]
We have this now: https://fontawesome.com/v6.0/icons/camera-viewfinder?s=solid
