### ISSUE TITLE
Icon request: map-marker-minus-slash / map-marker-plus-slash

### ISSUE THREAD

**Issue by Daniel4Digital** [FortAwesome/Font-Awesome#16413]
**What can it be used for?**
It could be used for old/new untracked things as sales for example

**Example image (optional)**
Its the map-marker-plus and the map-marker-minus with the slash, I am not able to do it with the stack

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of Font Awesome Pro's SVG Framework.

Demo: https://jsfiddle.net/tagliala/zrcxo5d8/23/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
