### ISSUE TITLE
Icon change request for fa-skeleton & fa-x-ray

### ISSUE THREAD

**Issue by YanDevDe** [FortAwesome/Font-Awesome#16414]
Hello everyone,

currently the fa-skeleton and fa-x-ray look too much like leviathan symbol (guess I played too much The Binding of Isaac lol) so it would confuse for end-users a lot. At first I though it was **leviathan symbol** but then I figured out that it was just skeleton.

![image](https://user-images.githubusercontent.com/1526048/78272518-e7129200-750d-11ea-9b28-252efb885de0.png)
![image](https://user-images.githubusercontent.com/1526048/78272528-eaa61900-750d-11ea-9cef-4ac9184bb027.png)

Thanks

**Comment by YanDevDe** [comment]
Inspiration: 
![image](https://user-images.githubusercontent.com/1526048/78885963-c42c3480-7a5d-11ea-95d5-8e4f0d6fe2b3.png)

**Comment by sensibleworld** [comment]
`skeleton` has been improved to include more accurate hip bones: https://fontawesome.com/icons/skeleton?f=classic&s=solid

As has `x-ray`: https://fontawesome.com/icons/x-ray?f=classic&s=solid

And we've also added a new `skeleton-ribs`: https://fontawesome.com/icons/skeleton-ribs?f=classic&s=solid
