### ISSUE TITLE
Icon Request: fa-user-desktop (remote screen)

### ISSUE THREAD

**Issue by leojh** [FortAwesome/Font-Awesome#16410]
**What can it be used for?**
For remote users, other non main users to a system. 

**Example image (optional)**
![untitled copy](https://user-images.githubusercontent.com/1440435/78218143-4d0a0580-748b-11ea-90f8-0513a1bc4f08.jpg)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/348/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by leojh** [comment]
Thank you @tagliala. My first pass at the icon was using transforms, masking, and layering but then the icon behaved differently in different contexts in my system. 
As far as I know there is no way to create a unified icon using these strategies so that presented other challenges as well. 
For now, the custom SVG I created is the best solution for me.

**Comment by tagliala** [comment]
You're welcome

> the icon behaved differently in different contexts in my system

If you want to provide more information, we can check if we can improve some stuff, unless you know that it depends on your specific use case

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
