### ISSUE TITLE
Broken link on free cheatsheet

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#16415]
**Describe the bug**
Broken link in the font awesome free cheatsheet

**To Reproduce**
1. Go to https://fontawesome.com/cheatsheet/free/regular
2. click on "Why are these in Font Awesome Free?"

**Expected behavior**
Bring somewhere else in the documentation

Ref: #16389

Maybe it was supposed to be a link to https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#changes

**Comment by talbs** [comment]
Thanks for the heads up, @tagliala. I've got a fix in for this that should be released shortly.

**Comment by talbs** [comment]
This is fixed on fontawesome.com now - https://fontawesome.com/cheatsheet/free/regular.

Thanks again for the heads up and for the help in getting this fixed.
