### ISSUE TITLE
Icon request:leaderboard

### ISSUE THREAD

**Issue by rafalou38** [FortAwesome/Font-Awesome#16417]
**What can it be used for?**
Make a leader board icon on nav bar

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are using [fa-trophy-alt](https://fontawesome.com/icons/trophy-alt?style=solid) for our [Leaderboard](https://fontawesome.com/community/leaderboard/new).

FA Free has [fa-trophy](https://fontawesome.com/icons/trophy?style=solid)

If you have something different in mind, please provide an example

Closing here
