### ISSUE TITLE
Jquery brand icon not found

### ISSUE THREAD

**Issue by inamullahmdi** [FortAwesome/Font-Awesome#16420]
![image](https://user-images.githubusercontent.com/31799163/78418990-d58ccf80-765e-11ea-999b-8d749adc9ca7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #1665 , please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
