### ISSUE TITLE
Website search result prediction overwrite final search

### ISSUE THREAD

**Issue by septatrix** [FortAwesome/Font-Awesome#16421]
*This is a bug about fontawesome.com and not about FontAwesome itself. I just wanted to report it somewhere. Also maybe not the most precise issue title*

**Describe the bug**
When entering a term in the search bar at [the fontawesome website](https://fontawesome.com/icons) (e.g. 'car') the icons are dynamically previewed below the input bar. Sometimes however the final search gets overwritten by another result even though the correct result was shown for a brief moment.

**To Reproduce**
Go to the fontawesome website and search for an icon. As this presumably depends on network speed and latency it may help to open devtools and throttle the connection as well as disable caching. Maybe use search terms of different length e.g. 'car', 'network' etc.

**Expected behavior**
The final result should not get overwritten by another one.

**Screenshots**
![Screenshot from 2020-04-04 15-32-19](https://user-images.githubusercontent.com/24257556/78452155-e6066f80-7689-11ea-9cae-a07cd453b2cd.png)
I may add a video if you are unable to produce this

**Version and implementation**
Browser and version: Chrome 80.0.3987.162

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm this issue, there are some throttling / debouncing issues on user input

Let's assign @robmadole

**Comment by avin-kavish** [comment]
Is the website open source?

**Comment by tagliala** [comment]
Hi @avin-kavish 

No, the documentation website not open source, sorry

**Comment by tagliala** [comment]
Hi, this is happening more often than before, so I've just reported this in our private repository

**Comment by robmadole** [comment]
@tagliala we think we've got this fixed. Can you confirm?

**Comment by tagliala** [comment]
@robmadole looks like it is fixed, but it scrolls the page at the top when I insert something in the search field. Is this intended?

**Comment by septatrix** [comment]
I can also confirm that this if fixed. Just out of curiosity: Do you just compare the length of the query string or actually transmit some timestamp (which would be more resilient but I have not been able to find one)?

**Comment by robmadole** [comment]
@septatrix the issue was with Algolia search results paging. When you search for two characters like "bu" the number of results coming back requires 2 separate requests to get all the results back. If you then search for "bus" that only needs one request. So we had a somewhat odd race condition. We solved this by making sure the results coming back matched what was currently being search for. For example, if a network response matched "bu" but the search box currently was set to "bus" we just threw the results out.

**Comment by robmadole** [comment]
@tagliala the scrolling behavior is intended. Does that feel off to you?

**Comment by tagliala** [comment]
@robmadole IMHO yes, especially if the FA6 banner is expanded

Use case:

1. Search for a common name (email)
![image](https://user-images.githubusercontent.com/556268/85892849-f5610900-b7f1-11ea-8c07-ca2908d1e3d3.png)
2. Scroll down a little bit to see results
![image](https://user-images.githubusercontent.com/556268/85892889-0b6ec980-b7f2-11ea-9a23-ececfc1664c6.png)
3. Try to refine your search (insert just a simple space in the search field)
4. Page jumps up, and you need to scroll again to see more results
![image](https://user-images.githubusercontent.com/556268/85892926-1aee1280-b7f2-11ea-84e6-8e9603494c51.png)


I would scroll at the top just if for some reason the search bar is not in the current view (user scrolls when a slow search is still running?)

**Comment by avin-kavish** [comment]
Scrolling the search bar to the top of the page could work...
