### ISSUE TITLE
`.es.js` should be renamed `.mjs`

### ISSUE THREAD

**Issue by mikestopcontinues** [FortAwesome/Font-Awesome#16439]
**Describe the bug**
This bug is described fully @ https://github.com/benmosher/eslint-plugin-import/issues/1717

The quick version is that `eslint-plugin-import` throws some errors reading `.es.js` files. The fix is to rename the files `.mjs` which officially indicates they are modules, not common-js style exports.

**Expected behavior**
I expect other libraries to have easy inter-op with fontawesome.

**Version and implementation**

```json
    "@fortawesome/fontawesome-svg-core": "1.2.28",
    "@fortawesome/free-brands-svg-icons": "5.13.0",
    "@fortawesome/free-regular-svg-icons": "5.13.0",
    "@fortawesome/free-solid-svg-icons": "5.13.0",
    "@fortawesome/react-fontawesome": "0.1.9",
```

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [-] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's see if @robmadole and @mlwilkerson can help

> unless their package.json has type: module, which that one doesn't. 

I also read this, but I don't know if it is the case of this repo

**Comment by ljharb** [comment]
I’m other words, “.es.js” is not a thing. Published .js files should be CJS and transpiled; if you don’t want to do the best practice, then they should be .mjs files.

**Comment by robmadole** [comment]
We'll start by evaluating [the node.js doc on ECMAScript Modules](https://nodejs.org/api/esm.html) and go from there.

**Comment by IanVS** [comment]
Hi, has there been any decision made on use of `.js` vs `.mjs` extensions, @robmadole?

**Comment by ljharb** [comment]
`.mjs` remains the proper file extension for ESM.

node has type:module to override `.js` (which is supposed to mean Script/CJS) to mean ESM, but `.mjs` is the proper universal extension for this. File extensions are only at the end - `.es.js` is just `.js`, and thus is not reliably distinguishable from any other `.js` file.

**Comment by mikestopcontinues** [comment]
This is becoming a bigger impediment as time goes on. Any movement?

**Comment by robmadole** [comment]
How is this a bigger impediment? Has something changed?

**Comment by mikestopcontinues** [comment]
@robmadole I keep hitting on compatibility issues that require workarounds. 

The most recent one was that I don't bundle `@fortawesome` packages in a lib that depends on them (and I shouldn't), however when referencing that library from another package for some `vitest` tests, the code breaks. I was forced to explicitly include `@fortawesome` elements in the library bundle.

It's difficult to say whether this issue comes down to `vitest`, `tsup` (bundler), or `typescript` package resolution. However `vitest` reported the issue, and the error message explicitly suggested `.mjs` to resolve it. Funny enough, I'd completely forgotten I opened this issue two years ago, until Google landed me here.

**Comment by ljharb** [comment]
Precisely zero tools expect `.es.js` - all of them expect `.js` with type module, or `.mjs` always, to mean ESM - because that's what node does, and node's decision *defines* what's correct for the node ecosystem.

**Comment by robmadole** [comment]
All we are going to focus the conversation about this in the PR https://github.com/FortAwesome/Font-Awesome/pull/19041
