### ISSUE TITLE
Getting this error on installing the font-awesome package.

### ISSUE THREAD

**Issue by imrishabh18** [FortAwesome/Font-Awesome#16430]
![image](https://user-images.githubusercontent.com/38923768/78662218-a9d34900-78ed-11ea-86e7-efdeafa9c619.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can you provide more details? the one in the debug log that is shown at the end of the shell output

**Comment by imrishabh18** [comment]
I don't why when i trying to install the font-awesome module it gave ne this error. I have already used this module before it was working fine but don't know why it's showing this error now.
