### ISSUE TITLE
Icon request: fa-filter-apple

### ISSUE THREAD

**Issue by uxchameleon** [FortAwesome/Font-Awesome#16444]
**What can it be used for?**
It is a more abstract icon for the filter function not using a symbolic funnel.

**Example image**
![FilterAppleRequest](https://user-images.githubusercontent.com/12539828/78903073-f1d3a680-7a7a-11ea-969c-3694614efe00.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to consider this a duplicate of #14485 , please 👍 that request

**Comment by uxchameleon** [comment]
👍
