### ISSUE TITLE
Icon request: tik-tok

### ISSUE THREAD

**Issue by tmsmscott** [FortAwesome/Font-Awesome#16441]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

Could be used for websites (social media menu) to have the link for tiktok the way other social media sites are listed

**Example image (optional)**
![tiktok](https://user-images.githubusercontent.com/63382894/78852108-7e358900-79e9-11ea-96dd-c08458bd9494.png)

**Icon request checklist**
- [x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by rock112293** [comment]
maybe not on menu.maybe for web function or link logo

**Comment by tmsmscott** [comment]
That's what I want it for, the top of my website where I list icons that when clicked they route to our social media page for that icon

**Comment by rock112293** [comment]
yah is best....

**Comment by tmsmscott** [comment]
thank you

**Comment by rock112293** [comment]
your welcome

**Comment by rock112293** [comment]
make this for social ads it makea your website poweful......

**Comment by sensibleworld** [comment]
Hey there! We've already go an open issue for this: https://github.com/FortAwesome/Font-Awesome/issues/14340

(And we're working to include this icon soon)

**Comment by rock112293** [comment]
nice!great!
