### ISSUE TITLE
Cache bust fonts FA5

### ISSUE THREAD

**Issue by richRubie** [FortAwesome/Font-Awesome#16442]
We had an issue upgrading from 5.10 to 5.13, the icons we wanted to use were not showing up. It turns out that while we were cache busting the css using .net framework MVC bundles the fonts were not subject to that process.

I can't find any best practices for doing this, can you help?
I saw a very old issue where you were adding the version to the fonts path (https://github.com/FortAwesome/Font-Awesome/issues/663), the product has moved on since then should this be re-implemented or are we doing something wrong.

Thanks in advance

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a generic question, please take a look here:  https://github.com/FortAwesome/Font-Awesome/issues/16375#issuecomment-605177196

**Comment by tagliala** [comment]
Closing here, but feel free to comment
