### ISSUE TITLE
Icon Request: canadian-maple-leaf

### ISSUE THREAD

**Issue by lukenjohnson** [FortAwesome/Font-Awesome#1645]
Would it be possible to create a maple-leaf icon? Canadian sites, artists, and businesses often like to promote "Canadian Content". A maple leaf icon would be useful to have because it is Canada's most recognizable image. I've attached a single-colour maple leaf, and an example image of how it might be used with text.

Thanks!

Luke

![canadian_content](https://f.cloud.github.com/assets/987881/852804/c08cff4e-f4bd-11e2-9b70-0e2ed16f4e07.png)
![maple_leaf](https://f.cloud.github.com/assets/987881/852805/c093c8b0-f4bd-11e2-8462-5fc0cd0e1d4e.png)

**Comment by yacpro13** [comment]
Definitely +1.
I would have used Awesome Font for a Canadian project I am currently working on if it would have had a maple leaf. I'm sure this icon could also be used for non-country related purposes as well, as mentioned by other users above.

**Comment by johnfraney** [comment]
+1. This would be unbeleafably convenient!

**Comment by beforeyouknowit** [comment]
+1. Please add this.

**Comment by settinghead** [comment]
+1

**Comment by aethant** [comment]
Actually, I could really use this. Need it for a project that has special rules due to Canadian opt in laws. Would be a real help. +1

**Comment by SethDavenport** [comment]
+1

**Comment by wzaghal** [comment]
+1

**Comment by winkerVSbecks** [comment]
+1 Here's a public domain vector file you can use: http://thenounproject.com/term/canada/210/

**Comment by aethant** [comment]
@winkerVSbecks thanks!

**Comment by x9a3k** [comment]
So any hope of getting this on font awesome? It's been over a year since I commented and I'm still hoping for this!

**Comment by tagliala** [comment]
@x9a3k please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by brianolynyk** [comment]
+1 This would be a fantastic addition to font awesome.

**Comment by josepot** [comment]
+1

**Comment by AllGoNShow** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by mphdavidson** [comment]
+1 Would be an excellent addition.

**Comment by milanvrekic** [comment]
+1

**Comment by twhyte** [comment]
+1

**Comment by bettymakes** [comment]
+1 :)

**Comment by daemonhunter** [comment]
+1

**Comment by lclc** [comment]
+1

**Comment by mark-monteiro** [comment]
+1

**Comment by quinen** [comment]
+1

**Comment by devisscher** [comment]
+1

**Comment by agos** [comment]
+1

**Comment by maikunari** [comment]
+1

**Comment by iamlinzee** [comment]
+ 1

**Comment by craighooghiem** [comment]
+1

**Comment by LeviBarker** [comment]
+1

**Comment by matthewhtc** [comment]
+1

**Comment by JboyJW** [comment]
+1

**Comment by Lyxpudox** [comment]
+1

**Comment by DioPLR** [comment]
+1

**Comment by bigyellowtaxi** [comment]
+1

**Comment by molly-ls** [comment]
+1

**Comment by giltee** [comment]
1+

**Comment by ScottAgirs** [comment]
Any updates on this? 
+1

**Comment by wyattbaldwin** [comment]
+1
Give some Love to Canadians Please

**Comment by kaitlinnewson** [comment]
+1

**Comment by codebloo** [comment]
+1

**Comment by adipramono** [comment]
+1

**Comment by supercody** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a maple leaf icon to Font Awesome Pro: https://fontawesome.com/icons/leaf-maple?style=solid

(This is obviously not the maple leaf used in the Canadian flag. If that's what is being requested, we can/should update this to be a brand icon request and for inclusion in our brand icon font.)

**Comment by newsonaut** [comment]
@sensibleworld Your maple leaf looks great. But I think the request is more along the lines of a symbol for Canada.

**Comment by sensibleworld** [comment]
Updating this request to be a "brand" icon, and will get the Canadian maple leaf in the queue.

**Comment by wyattbaldwin** [comment]
does that mean the icon is coming?

**Comment by sensibleworld** [comment]
Yup. I'll get it added to one of our next releases.

**Comment by talbs** [comment]
O Canada, we stand on guard for thee (and added thee to Font Awesome Free) - https://fontawesome.com/icons/canadian-maple-leaf.

**Comment by chr0s** [comment]
... wow. I Google this icon two days ago to use it, amazing timing considering it's been 5 years since it was requested :D
