### ISSUE TITLE
Icon request: park-bench

### ISSUE THREAD

**Issue by tbone849** [FortAwesome/Font-Awesome#16451]
**What can it be used for?**
To indicate a park or benched player on a sports team

**Example image (optional)**
![image](https://user-images.githubusercontent.com/11409836/78999923-a1f7ec80-7b19-11ea-801b-f823a73db241.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- x[ ] I have included at least one example image if it could be helpful (optional)
- [x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by JaHe-Facito** [comment]
👍
