### ISSUE TITLE
Broken Site Search

### ISSUE THREAD

**Issue by avin-kavish** [FortAwesome/Font-Awesome#16468]
As the image demonstrates, typing `location` does not bring up location icons but brings ones starting with `ly`, `lu` etc

![image](https://user-images.githubusercontent.com/48435155/79252172-d3b4de80-7e9e-11ea-9b3a-1e5f28cdfddf.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm, this has been already reported here: #16421
