### ISSUE TITLE
Icon request: Pipeline

### ISSUE THREAD

**Issue by benyaminjava** [FortAwesome/Font-Awesome#16469]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any idea on how a pipeline should look like?

**Comment by drewgeraets** [comment]
Something like this would be great:
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1134233/165989099-07e685b1-e45d-4eee-9e45-a850bb1229ac.png">

Our use case is showing sales pipelines.

Potentially related to [#16260](https://github.com/FortAwesome/Font-Awesome/issues/16260)

**Comment by aethior** [comment]
Duplicate or related? #2998

cc/ @tagliala

**Comment by tagliala** [comment]
I would say so, closing here
