### ISSUE TITLE
Icon request: truck-arrow-up truck-arrow-down (loading-alt unloading)

### ISSUE THREAD

**Issue by SirNeslo** [FortAwesome/Font-Awesome#16463]
**What can it be used for?**
Font Awesome has several icons within the Logistics business sector but none show a clear directional flow of goods moving onto and off of a truck/forklift/loading dock.  The goal of these two icons is to show that directional flow. 

**Example image (optional)**
![image](https://user-images.githubusercontent.com/63591832/79120343-436c8180-7d58-11ea-94b3-fbfeaff7ba5c.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/380/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by tagliala** [comment]
Also, there is already a truck-loading icon: https://fontawesome.com/icons/truck-loading?style=solid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
