### ISSUE TITLE
Icon request: ARS

### ISSUE THREAD

**Issue by ars-1** [FortAwesome/Font-Awesome#16464]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
For my web Logo

**Example image (optional)**
Insert the example image here if necessary.
[``](https://4.bp.blogspot.com/-oxIJnp6KBnM/XpRfJf6M6yI/AAAAAAAABsk/jSzgM1NXxLMnzE2MMT16FAm8LtXncYB5gCLcBGAsYHQ/s1600/d%2B%25282%2529.jpg)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Is this a request for your own website logo?

**Comment by wolfprince14777** [comment]
Yes

**Comment by wolfprince14777** [comment]
![ARS](https://user-images.githubusercontent.com/56891476/80316720-d2799f00-8818-11ea-911f-5255f941d18a.png)
