### ISSUE TITLE
Icon request: tin-can

### ISSUE THREAD

**Issue by jevijevi** [FortAwesome/Font-Awesome#16467]
**What can it be used for?**
e-shop menu

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ x ] This is a single icon 
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We now have a `can-food` icon. https://fontawesome.com/v6.0/icons/can-food?s=solid

**Comment by jevijevi** [comment]
Thank you very much!

I would like to ask when will it appear on Font Awesome Pro


Thanks again



Tzevi Onsounoglou
Diamantis Masoutis S.A.
Web Designer
IT Department
phone: 2310803795

[cid:masoutis_8a186626-7b04-4ada-9334-8413a7c7a7fc.jpg]<http://www.masoutis.gr/>

**Comment by sensibleworld** [comment]
@jevijevi It's available now as part of the version 6 beta: https://fontawesome.com/v6.0
