### ISSUE TITLE
Direct Link doesn`t work at "Docs"

### ISSUE THREAD

**Issue by botsula** [FortAwesome/Font-Awesome#16470]
Hey!
Here is a little bug:
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#additional-styling-options - this direct link isn't working properly, maybe some mistake in `<id>`.

Thanks for your work!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Yes, the id is missing in the h2 element

Let's assign @talbs

**Comment by talbs** [comment]
Thanks for the heads up, @botsula and @tagliala. I'll take care of this quickly and we'll get a fix out shortly.

**Comment by talbs** [comment]
This is fixed on fontawesome.com now - https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#additional-styling-options.

Thanks again for the heads up and for the help in getting this fixed.
