### ISSUE TITLE
Upgrade form v4 to v5 instructions does not work for some icons

### ISSUE THREAD

**Issue by bric3** [FortAwesome/Font-Awesome#16477]
**Describe the bug**
Reading https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

I applied the js script in the head section of my html page :

```html
<head>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/v4-shims.min.js" integrity="sha256-prFmieX9aRVhOV/ldXGklUUhS7NRBQUijQU4HcdnO8Q=" crossorigin="anonymous"></script>

</head>
```

I alos tried 

```html
<head>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/solid.min.js" integrity="sha256-UM1HRu0Wd16k4L5wgrk17BYWzKkjZSe0BYr5T5qw2Ww=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/brands.min.js" integrity="sha256-z0T3r+4uTjAkB5CHxybF9RQwAzHEdFB5+hJe/pGAcPg=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/fontawesome.min.js" integrity="sha256-NP9NujdEzS5m4ZxvNqkcbxyHB0dTRy9hG13RwTVBGwo=" crossorigin="anonymous"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/v4-shims.min.js" integrity="sha256-prFmieX9aRVhOV/ldXGklUUhS7NRBQUijQU4HcdnO8Q=" crossorigin="anonymous"></script>

</head>
```

What happened? What are you seeing? How did you arrive here?

```html
<i class="fa icon-tip"></i>
<i class="fa fa-close"></i>
```

**To Reproduce**
I don't know how to reproduce this with jsfiddle.net this file is enough

```
<head>
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/v4-shims.min.js" integrity="sha256-prFmieX9aRVhOV/ldXGklUUhS7NRBQUijQU4HcdnO8Q=" crossorigin="anonymous"></script>
</head>

<body>
  <i class="fa icon-tip"></i>
  <i class="fa fa-close"></i>
</body>

```

**Expected behavior**
Either document the limitation of the upgrade, or it's a bug.

**Screenshots**
without solid.min.js :
<img width="260" alt="image" src="https://user-images.githubusercontent.com/803621/79361033-0e715200-7f45-11ea-91c1-e09c4bd53d47.png">

with solid.min.js or all.min.js :
<img width="244" alt="image" src="https://user-images.githubusercontent.com/803621/79361084-1e893180-7f45-11ea-9316-95949ac9af8f.png">

**Version and implementation**
Version: 5.13.0
Browser and version: Firefox 75.0

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I don't know from where `<i class="fa icon-tip"></i>`, but it is not a valid Font Awesome icon or syntax.

You are looking for FA5's [far fa-lightbulb](https://fontawesome.com/icons/lightbulb?style=solid), that is correctly being changed from FA4's [fa fa-lightbulb-o](https://fontawesome.com/v4.7.0/icon/lightbulb-o)

Demo: https://jsfiddle.net/tagliala/ru2oj39s/1/

Hope it helps

Closing herre, but feel free to comment

(OT: I think I will not stop amending the double `r`s that my MacBook's butterfly keyboard is deliberately adding)

**Comment by bric3** [comment]
@tagliala hi thanks for replying quickly! Indeed I've identified `fa-lightbulb-o` but for some reason Asciidoctor uses `icon-tip`. They say they use FA4. and I'm trying to integrate the rendered document in a site that already make use of FA5. I was thinking it could be _aliases_ ?



In the screenshot above where I reload the site I can quickly see the bulb icon appearing then it's replaced by the _question mark placeholder_. And in this site if I remove the solid.min.js then the bulb icon is rendered as expected, but not the new FA5 glyphs. I wasn't able to reproduce properly elsewhere this behavior in particular.

I don't know to really troubleshoot this.

**Comment by bric3** [comment]
Ah I'll need to instigate it seems there's an Asciidoctor CSS trick in this case as explaned there https://github.com/asciidoctor/asciidoctorj/issues/381

**Comment by tagliala** [comment]
Yes, please check there

https://github.com/asciidoctor/asciidoctor/blob/a1fa9d555eaca835cdc1e30fb2ddc2c83523bd81/data/stylesheets/asciidoctor-default.css#L372-L377

This will not work with FA5, but please note that if you use the SVG framework:
- [using pseudoelements is not recommended](https://fontawesome.com/how-to-use/with-the-api/setup/configuration#searchpseudoelements)
- `text-shadow` will not work

**Comment by bric3** [comment]
@tagliala Actually this work when only using the CSS, but the other part of the page uses HTML to SVG via JS, so adding all.min.js in the header, replaces the before element but the missing icon indicator.

So having the following works

```html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
</head>
<body>
  <i class="fa icon-tip"></i>
</body>
```

```css
.icon-tip::before {
  font-family: 'Font Awesome 5 Free';
  content: "\f0eb";  // equivalent to <i class="far fa-lightbulb"></i>
  //text-shadow: 1px 1px 2px rgba(155, 155, 0, 0.8);
  color: #111;
}
```

But when adding the all.min.js script, without shims, the lightbullb icon is replaced but missing icon indicator.

```html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" data-search-pseudo-elements integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=" crossorigin="anonymous"></script>
</head>
<body>
  <i class="fa icon-tip"></i>
</body>
```

I wonder if the presence of the `fa` class has something to do with it.
