### ISSUE TITLE
Icon request: folder-pen

### ISSUE THREAD

**Issue by stilyansky** [FortAwesome/Font-Awesome#16473]
**What can it be used for?**
Icon for renaming a folder 

**Example image (optional)**
![Screenshot 2020-04-15 at 12 56 29](https://user-images.githubusercontent.com/31994426/79329710-91c87e80-7f18-11ea-983a-6d35e09894d5.png)

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/424/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by stilyansky** [comment]
Hey @tagliala, 

thanks for the welcoming :))

yeah this is true and I know it, my point was that it would be nice to make the **folder set** of icons a bit closer to the **file set** of icons like:

**file-edit:** https://fontawesome.com/icons/file-edit?style=regular

but yeah, I see your point. I will close the request :)) 

Have a lovely day :)
