### ISSUE TITLE
Icon request: icon-lamppost

### ISSUE THREAD

**Issue by jorisjandevries-cloud** [FortAwesome/Font-Awesome#16479]
**It can be used to mark lampposts on the map.**

**Example image (optional)**
Insert the example image here if necessary.
![image]
(https://user-images.githubusercontent.com/63774623/79425147-8bdaa800-7fc1-11ea-8be9-8257eeebe2ae.png)

![image](https://user-images.githubusercontent.com/63774623/79425710-65693c80-7fc2-11ea-90ad-0fc9e23da6e4.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @jorisjandevries-cloud,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/lamp-street

Regards.

cc/ @tagliala
