### ISSUE TITLE
location

### ISSUE THREAD

**Issue by xwkj** [FortAwesome/Font-Awesome#16471]
Could someone help me find an icon that is location.It is at top-left of this page ?  https://m.helijia.com/?1586923754118#/?_k=so2wrb thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can find location-related icons here: https://fontawesome.com/icons?d=gallery&q=location&s=solid&m=free

This is the one you are looking for: https://fontawesome.com/icons/map-marker-alt?style=solid

(note that the light style is only available in FA Pro)

Hope it helps

Closing here
