### ISSUE TITLE
icon-plus-sign is not in perfect round shape

### ISSUE THREAD

**Issue by nipuntrivedi9** [FortAwesome/Font-Awesome#1648]
http://blacksheep.webinfo4you.com/
I have added icon-plus-sign in accordian section.but the circle is not coming perfectly rounded in shape. I have checked all the css related to this also but nit finding any solution .
Please help. Its urgent

**Comment by sensibleworld** [comment]
Cleaning up some older issues, and came across this one. Any issues with this icon should be fixed in version 5. Let us know if that's not the case! Thanks :)
