### ISSUE TITLE
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by laurarg81** [FortAwesome/Font-Awesome#16484]
Hello!

For about 1h, I'm receiving these errors:
Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID  https://kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css

![Untitled-1](https://user-images.githubusercontent.com/55237663/79587971-fb44ba80-80db-11ea-86a2-2f20169e6abb.jpg)

It was working fine until now.

Best regards

**Comment by tagliala** [comment]
Ref: #16483
