### ISSUE TITLE
This server could not prove that it is kit-free.fontawesome.com; its security certificate is from *.ssl.hwcdn.net. This may be caused by a misconfiguration 

### ISSUE THREAD

**Issue by kaizensystech** [FortAwesome/Font-Awesome#16487]
This server could not prove that it is kit-free.fontawesome.com; its security certificate is from *.ssl.hwcdn.net. This may be caused by a misconfiguration

**Comment by tagliala** [comment]
Thanks for reporting this, we are aware of the situation and sorry for the inconvenience

More information: https://status.fortawesome.com/

Duplicate of: #16482
