### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by smafrica** [FortAwesome/Font-Awesome#16489]
Ricevo questo errore:

La connessione non è privata
Gli utenti malintenzionati potrebbero provare a carpire le tue informazioni da kit-free.fontawesome.com (ad esempio, password, messaggi o carte di credito). Ulteriori informazioni
NET::ERR_CERT_COMMON_NAME_INVALID

Contribuisci a migliorare la sicurezza di Chrome inviando a Google gli URL di alcune pagine visitate, informazioni limitate sul sistema e alcuni contenuti delle pagine. Norme sulla privacy
RicaricaNascondi avanzate
kit-free.fontawesome.com in genere utilizza la crittografia per proteggere le tue informazioni. Questa volta, quando Google Chrome ha provato a connettersi a kit-free.fontawesome.com, il sito web ha restituito credenziali insolite e sbagliate. È possibile che un malintenzionato stia cercando di spacciarsi per il sito kit-free.fontawesome.com oppure che una schermata di accesso alla rete Wi-Fi abbia interrotto la connessione. Le tue informazioni sono ancora al sicuro perché Google Chrome ha interrotto la connessione prima che avvenissero scambi di dati.
Al momento non puoi visitare il sito web kit-free.fontawesome.com perché utilizza HSTS. In genere gli errori di rete e gli attacchi sono temporanei, pertanto questa pagina potrebbe funzionare più tardi.

**Comment by tagliala** [comment]
Thanks for reporting this, we are aware of the situation and sorry for the inconvenience

More information: https://status.fortawesome.com/

Duplicate of: #16482
