### ISSUE TITLE
use.fortawesome.com is having issues

### ISSUE THREAD

**Issue by bvossler** [FortAwesome/Font-Awesome#16485]
I am getting an SSL errors where the SSL cert does not match the domain name of use.fortawesome.com. Started this morning. Any update on this? Customers are having issues!

Looks like cert is actually for *.ssl.hwcdn.net

Thank you

**Comment by bvossler** [comment]
Got notification that they see the issue and are working on it. Will close this. Thanks

**Comment by tagliala** [comment]
Thanks for the report

https://status.fortawesome.com/

#16482
