### ISSUE TITLE
Icon request: heart-plus

### ISSUE THREAD

**Issue by maya** [FortAwesome/Font-Awesome#16492]
Heart with medical plus inside

**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/384/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by maya** [comment]
will check it out, thanks!

**Comment by maya** [comment]
how do you add a color to the mask? to achieve a duotone effect?

**Comment by maya** [comment]
nvm! found the layers page

**Comment by sensibleworld** [comment]
Does this work? https://fontawesome.com/icons/heart-circle-plus?s=solid

Or do you need a version that has a "+" embedded in the heart itself?
