### ISSUE TITLE
Icon request: shield-heart

### ISSUE THREAD

**Issue by maya** [FortAwesome/Font-Awesome#16493]
Shield with a heart inside

**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/zrcxo5d8/8/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment]
Hi @maya,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/shield-heart

Regards.

cc/ @tagliala

**Comment by maya** [comment]
Nice, thanks! ❤️ 🛡️
