### ISSUE TITLE
Icon Request: fa-cast

### ISSUE THREAD

**Issue by nacalb** [FortAwesome/Font-Awesome#16497]
![cast](https://user-images.githubusercontent.com/63920602/79643317-cfc3dd80-8178-11ea-9a93-2afb0e4da4ab.png)

This icon is very useful to indicate contents where the information can be transmitted by video cast.

Thanks you ver much!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as [fab fa-chromecast](https://fontawesome.com/icons/chromecast?style=brands)

Hope it helps

Closing here
