### ISSUE TITLE
Icon request: icon-az-index

### ISSUE THREAD

**Issue by bdaley** [FortAwesome/Font-Awesome#1650]
Simply, "A-Z"

Example: http://t2.ftcdn.net/jpg/00/27/54/33/400_F_27543338_aNLXnHFCf0rlgfi9HppTsScTUmNSnYkD.jpg

Use cases:
Departmental directories or phone books.
Many colleges/universities and large organizations provide A-Z indexes for the sites on their domain.

Use case examples:
http://www.ucsc.edu/tools/azindex.html
http://www.bls.gov/bls/topicsaz.htm

**Comment by japope** [comment]
Agree, this would be a really useful icon to have.

**Comment by garzasays** [comment]
I missed this in my initial search and created an issue with the same request. This would be extremely helpful if they added this to the icon library!

**Comment by sensibleworld** [comment]
Does this work? https://fontawesome.com/v6.0/icons/arrow-down-a-z?s=solid
