### ISSUE TITLE
hand-holding-water not showing up!

### ISSUE THREAD

**Issue by dandacode** [FortAwesome/Font-Awesome#16509]
Hi! we were playing with the hand-holding series and hand-holding-water does not show up! please check it out!

Thanks!
![image](https://user-images.githubusercontent.com/13155728/80045382-d5992600-84cc-11ea-956a-20236d42762e.png)
![WhatsApp Image 2020-04-22 at 7 05 02 PM](https://user-images.githubusercontent.com/13155728/80045392-da5dda00-84cc-11ea-95dc-f135d23f8cff.jpeg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

There is an error in the documentation.

This icon has been introduced in Font Awesome 5.0.9., but it has made available fro Free users in our COVID related release 5.13.0, so please make sure that you are using the latest Font Awesome version available

Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours.

Hope it helps

Ref: 
- https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting
- https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-

**Comment by tagliala** [comment]
@talbs @sensibleworld could you please change the updated tag for this icon to 5.13.0 instead of 5.0.9 ?

**Comment by talbs** [comment]
Thanks for the feedback and sorry for the hiccups with this icon's history making it unavailable in Font Awesome Free. I've got a PR up to address this. It should be merged in and released shortly.
