### ISSUE TITLE
Icon request: utility-smart-meter

### ISSUE THREAD

**Issue by erd2119** [FortAwesome/Font-Awesome#16500]
**What can it be used for?**
For people building energy related apps

**Example image (optional)**
https://www.shutterstock.com/image-vector/utility-meter-icon-smart-1184586529

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/tachometer-alt?style=solid fit your use case?

**Comment by erd2119** [comment]
Yeah that’s what we use now, problem is we use that same icon for our dashboard so we have the same icon twice.

**Comment by aethior** [comment]
Hi @erd2119,

`fa-meter` icon was added in v6.0.0.
Check https://fontawesome.com/icons/meter

Variants:
- https://fontawesome.com/icons/meter-bolt
- https://fontawesome.com/icons/meter-droplet
- https://fontawesome.com/icons/meter-fire

Regards.

cc/ @tagliala
