### ISSUE TITLE
Icon Request: Propellor

### ISSUE THREAD

**Issue by dylanglockler** [FortAwesome/Font-Awesome#16507]
**What can it be used for?**
It would be great to suggest propulsion, ocean activities, sea travel and in my case - on an app for ship systems, the propulsion systems in the vessel.

**Example image (optional)**
![transport-travel-transportation_155-512](https://user-images.githubusercontent.com/3084083/80013363-bf737180-849c-11ea-980a-f23a5e491d50.png)

**Icon request checklist**
- [ no] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The design is different, but is there any chance that https://fontawesome.com/icons/fan?style=solid fit your use case?

**Comment by rock112293** [comment]
fan is using for logo of a brand product like selling fan,stand fan,wall fan,
or other usage etc......
it use for logo on webpage about air ventilation product.
but..request directly to fontawesome.com

**Comment by dylanglockler** [comment]
It is slightly different but in the context of a marine-based app, I think it sells well enough - why didn't I think to search for that? Thanks for pointing it out.
