### ISSUE TITLE
Error in the Bulleye icon html tag

### ISSUE THREAD

**Issue by AjinkyaGokhale1** [FortAwesome/Font-Awesome#16506]
the copy tag on your site contains 
`<i class="fas fa-bullseye"></i>`
where "fas" is incorrect 
it should be 
`<i class="fa fa-bullseye fa-4x"></i>`
![fas](https://user-images.githubusercontent.com/56818401/79944340-e4f68000-8488-11ea-8581-f3c4ed182efc.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
