### ISSUE TITLE
Icon request: peanut

### ISSUE THREAD

**Issue by michaelbjacobson** [FortAwesome/Font-Awesome#16502]
**What can it be used for?**
Useful to indicate dishes containing peanuts (or any nuts) in a food menu. I have used the acorn icon previously for this purpose, but on several occasions got feedback from clients and their customers that it wasn't very appropriate as acorns are basically inedible.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Ref: #13383

Does https://fontawesome.com/icons/acorn?style=solid fit your use case?

**Comment by michaelbjacobson** [comment]
> Ref: #13383
> 
> Does https://fontawesome.com/icons/acorn?style=solid fit your use case?

@tagliala I have used the acorn icon previously for this purpose, but on several occasions got feedback from clients and their customers that it wasn't very appropriate as acorns are basically inedible.

**Comment by tagliala** [comment]
@michaelbjacobson thanks for the clarification

**Comment by hazelnutcreative** [comment]
I second this request for a peanut for usage on menus

**Comment by sensibleworld** [comment]
We've added a couple of `peanut` icons: https://fontawesome.com/v6.0/icons?q=peanut

**Comment by hazelnutcreative** [comment]
Awesome work!
