### ISSUE TITLE
Icon request: rings-wedding-slash

### ISSUE THREAD

**Issue by dacasine** [FortAwesome/Font-Awesome#16513]
... would be grate to have.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any (gender neutral, if possible) example?

**Comment by dacasine** [comment]
Hi

Two rings slashed ?

Kind regards

>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework and FA Pro.

Demo: https://jsfiddle.net/tagliala/L17f528g/398/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by dacasine** [comment]
Got it, thx for the answer, it helps a lot.

Kind regards,

**Comment by santoshandrei** [comment]
If you have a set of jewellery which needs fixing, repair or polish, then this article will help you with the right insight to have the right questions to ask from a **[jewellery repair store](https://www.coesbespokejewellers.com/blog/questions-to-ask-before-choose-jewellery-repair-shop/)** to ask before you choose a service from them.

**Comment by santoshandrei** [comment]
Your cherished pieces of adornments reflect your emotions and your style. The option to purchase jewelry ranges from offline to online. The jewelry that you buy online needs a definition to make it attractive. **[Jewelry photo retouching](https://www.eretouchingindia.com/blog/what-is-importance-of-jewelry-photo-retouching-services/)** adds the right amount of finesse to the products and makes it more appealing.

**Comment by santoshandrei** [comment]
Sterling silver necklace for mom, **[birthstone necklaces](https://www.allperfectstories.com/buy-mothers-birthstone-necklace/)** for her, custom necklace for mother’s day, diamond charm necklace, sister’s necklace. Are you planning to buy a mothers birthstone necklace? If yes, then this is the right article you’ve come across. We have given all the information that you need to consider while making the purchase.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
