### ISSUE TITLE
Icon Request: icon-hand-stop

### ISSUE THREAD

**Issue by matob** [FortAwesome/Font-Awesome#1651]
![stop_hand](https://f.cloud.github.com/assets/1113857/859205/6fc304da-f578-11e2-9021-926d8880cb2c.png)

Stop / Hand symbol ;)

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/3933#issuecomment-51087199

**Comment by MMokhtari** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by VitalyPankin** [comment]
Really need it, but not in the circle, just like that

![877a3066-cc23-11e4-9c5c-0a023b4877b9](https://cloud.githubusercontent.com/assets/2627271/7842446/b6bbbbea-04ab-11e5-9176-0492bac15e3d.png)

Circle, borders and etc we can add in CSS

**Comment by dzalozhnov** [comment]
+1

**Comment by akaravashkin** [comment]
+1

**Comment by SergeyJey** [comment]
+1

**Comment by 33-Elephants** [comment]
+1

**Comment by tagliala** [comment]
Added in 4.4.0, closing here!
