### ISSUE TITLE
Unicode Issue with fa-virus Icon?

### ISSUE THREAD

**Issue by dani3lr0se** [FortAwesome/Font-Awesome#16522]
We have a client who's site is a Drupal 8 cms. They were using fontawesome version 4 and I recently upgraded them to version 5 free version. 

My process for upgrading was to manually download the latest version, 5.13.0, and then I manually replaced the client's existing version in the code repo. Everything seemed to work fine with no issues.

The reason for the upgrade to version 5 was so we could use the `fa-virus` [icon](https://fontawesome.com/icons/virus?style=solid). The client wanted me to add a section to their menu on the homepage for COVID-19 Updates and they wanted to use the `fa-virus` icon for the link. This updated went fine on my end and everything seems to be setup correctly in the site.

I then had the client review the site and they reported seeing a chinese character in the place where the icon was supposed to be despite my clearing the site cache already. I had them clear the browser cache which ultimately fixed this issue. 

Well today the client sent us an urgent issue which reported that a chinese student at their school viewed the site and reported seeing the chinese character instead of the virus icon. They mentioned that the chinese student was offended because they saw the chinese character instead of the icon in the COVID-19 Updates section. 

<img width="240" alt="fa-virus-icon-issue" src="https://user-images.githubusercontent.com/12372245/80254453-3188b980-8649-11ea-9e85-de84e261fbf9.png">

I thought that the icons used were PUA, but this particular icon doesn't appear to be? Nevertheless, despite my thinking that I did the upgrade correctly, perhaps I am missing something? I admit this isn't my area of expertise so I'm open to any feedback. 

I wanted to report this because I'm curious what others think and I wanted to let the Fontawesome team know that this actually happened in case anyone ever happens to see something similar. It seems to be more of a coincidence, but I wanted to mention it anyways in case this is a legit issue that the team should know about. 

Thanks again for any feedback.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please notice that icon-virus has been introduced in FA 5.13.0, released few days ago.

Could you please make sure that you are using the latest version of Font Awesome?

If you still can't fix, feel free to fill out a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Closing here

**Comment by dani3lr0se** [comment]
Yes, I used the latest version.

**Comment by tagliala** [comment]
@dani3lr0se please provide a reproducible test case so I can take a look
