### ISSUE TITLE
Vertical alignment off with svg, layers, icon-sizes inside layer

### ISSUE THREAD

**Issue by mrlife** [FortAwesome/Font-Awesome#16526]
In the following, the layered icon (with or without the checkmark commented out) is positioned slightly higher than the preceding icon.

```
<div>
	<i class='fas fa-lg fa-times-circle'></i>
	<span class='fa-layers'>
		<i class='fas fa-lg fa-times-circle'></i>
		<!--<i class='fas fa-check' data-fa-transform='shrink-5 right-17' style='color: #C84E00'></i>-->
	</span>
</div>
```

**Version and implementation**
Version: 5.13.0
Browser and version: Safari 13.1 for macOS 

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm: https://jsfiddle.net/tagliala/42meju9o/4/

![image](https://user-images.githubusercontent.com/556268/80288182-80604d00-8736-11ea-8654-95a6641a2c3b.png)

This is an edge case and depends on the use of `font-size` inside the `.layer` with its `vertical-align` property 

Workarounds:
- Use a custom class (and place it: https://jsfiddle.net/tagliala/42meju9o/12/
- Apply `.fa-lg` to an outer div: https://jsfiddle.net/tagliala/42meju9o/19/

@robmadole should we do something here? Maybe in the docs to ask to avoid setting the font size inside the layer

Ref:
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
- https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons#scale

**Comment by mrlife** [comment]
When using Bootstrap, the font size is set on the `<body>` by default. It would be a lot to add the workaround every time this situation comes up. Possible to fix in the codebase?

**Comment by tagliala** [comment]
> It would be a lot to add the workaround every time this situation comes up. 

Could you please clarify? Is this about some automatic content creation and reuse of code? 

> Possible to fix in the codebase?

I've tried several approaches but the fix is not straightforward. Feel free to submit a PR if you manage to fix this.

This is the result of my investigation, it could be useful in finding a solution:
- Issue happens every time the size of the icon is changed inside the layer (not only `fa-lg`, but `fa-sm`, `fa-2x`)
- Isue happens for all browsers (https://jsfiddle.net/tagliala/42meju9o/20/)
- Alignment is fine for any other size except `fa-lg`, as long as the size class is applied to the `fa-layer` element
- Alignment is fine with any size, as long as  if they are applied to an outer div
- The documentation examples at https://fontawesome.com/how-to-use/on-the-web/styling/layering sets the side in a wrapper container
- The documentation at https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons#scale clearly advises of a different vertical-align for `fa-lg` class (it was used to keep the icon in line with normal size text)

@robmadole any thoughts?

**Comment by mrlife** [comment]
The following fixes it, but I'm not sure if it would affect anything else.

I added the following to a fork of your repro:

```
.svg-inline--fa {
  height: auto;
}
```

https://jsfiddle.net/31hm5zej/

**Comment by tagliala** [comment]
Yes, it has side effects and does not work with fa-2x.

Check the icon size and alignment with text here:
- https://jsfiddle.net/y6vdzheL/
- https://jsfiddle.net/y6vdzheL/1

**Comment by tagliala** [comment]
@mrlife could you please check this with safari?

https://jsfiddle.net/tagliala/9rqezxfs/8/

it seems it does not affect the CSS framework. In this case we can provide a fix at javascript level

**Comment by mrlife** [comment]
This looks good to me in Safari. Thank you!

**Comment by tagliala** [comment]
@mrlife sorry, I said something wrong.

The `layers` feature is exclusive for the SVG framework, I get confused with the [stack](https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons). I've deleted the not relevant comments

Wait for Rob's feedback here

**Comment by mrlife** [comment]
Here's a slightly augmented potential CSS solution.

https://jsfiddle.net/6g72jecv/

**Comment by tagliala** [comment]
Thanks

Not yet the same thing. `fa-layers` renders as an inline block:
- https://jsfiddle.net/tagliala/y693z45a/5/
- https://jsfiddle.net/tagliala/y693z45a/6/

Also, setting the size inside the layers makes them overlap if you put them one near other:

- https://jsfiddle.net/tagliala/y693z45a/9/
- https://jsfiddle.net/tagliala/y693z45a/10/

**Comment by robmadole** [comment]
Hmm...yeah I'm not sure how we want `fa-lg` to behave in this situation. It's a special case with that vertical align.

@mrlife can you use one of the other size classes? Can you set the font-size in another way?

```html
<div title="Works" style="font-size: 1.33em;">
	<i class='fas fa-times-circle'></i>
	<span class='fa-layers'>
		<i class='fas fa-times-circle'></i>
	</span>
</div>
```

**Comment by mrlife** [comment]
@robmadole and @tagliala Thank you for your suggestions and efforts. I found a way to make the custom class approach work in my scenario.

Just out of curiosity, why does the `.fa-lg` have the 2 extra lines of CSS?

```
.fa-lg {
	font-size: 1.33333em;
	line-height: .75em;
	vertical-align: -.0667em;
}
```

> Maybe in the docs to ask to avoid setting the font size inside the layer

Seems like it would be helpful for others.

**Comment by tagliala** [comment]
Hi @mrlife , answered here before:

> Just out of curiosity, why does the .fa-lg have the 2 extra lines of CSS?

The documentation at https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons#scale clearly advises of a different vertical-align for fa-lg class **(it was used to keep the icon in line with normal size text)**

**Comment by leecollings-sb** [comment]
Why has this been closed if the issue is still there? (All of my stacked icons the inner icon is slightly higher than centre) - on version 5.15.4.

![Screenshot 2021-09-15 at 15 47 22](https://user-images.githubusercontent.com/12139008/133455893-c14da66a-64d1-4235-a1f1-78ec6ff72fe0.png)

**Comment by tagliala** [comment]
> Why has this been closed if the issue is still there? (All of my stacked icons the inner icon is slightly higher than centre) - on version 5.15.4.
> 
> ![Screenshot 2021-09-15 at 15 47 22](https://user-images.githubusercontent.com/12139008/133455893-c14da66a-64d1-4235-a1f1-78ec6ff72fe0.png)

Hi, this issue has been closed by the opener

The main reason is that we can only document this issue and [it has been done](https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/stacking-icons)

![image](https://user-images.githubusercontent.com/556268/133461648-feefd009-cf01-4dcc-bc8d-6beb6a8c18a8.png)

Ref: https://github.com/FortAwesome/Font-Awesome/issues/16526#issuecomment-620770678

CSS does not play well with this case of perfect vertical center of stacked/animated icons. I should mention issue #671 , labeled as cantfix

It depends on a lot of variables, including browser, icon, screen dpi, and font-size.

Exact multiples of the base font size (16px) provide a better output

Here it is a reduced test case of your screenshot: https://jsfiddle.net/tagliala/vbhdn9te/5/

It looks fine on macOS / Chrome and Firefox on both retina and non-retina display

### Retina (16px - Chrome)

![image](https://user-images.githubusercontent.com/556268/133458579-79008dd3-2774-404f-b641-78c0c105d782.png)

### 1080 (16px - Chrome)

![image](https://user-images.githubusercontent.com/556268/133460028-ee35cec8-6bba-4e07-b275-f6ede2eceea7.png)

but for example if you want smaller social icons, then the issue kicks in

### Retina (12px - Chrome)

![image](https://user-images.githubusercontent.com/556268/133461047-87419703-a9d4-4ab2-a965-897659fdeca6.png)


### 1080 (12px - Firefox)

![image](https://user-images.githubusercontent.com/556268/133461107-06136fe7-a38c-401d-aff7-4257343c03ba.png)

**Comment by leecollings-sb** [comment]
So what you're saying is, if anyone sets the font size of body, your icons are not aligned properly...?

**Comment by tagliala** [comment]
> So what you're saying is, if anyone sets the font size of body, your icons are not aligned properly...?

Nope. I'm referring to the `fa-stack` element and perfect vertical alignment of webfonts (especially at small sizes and non multiples of the base font size). As said before, there are things to keep in mind. `font-size` is one of them

Demo: http://jsfiddle.net/tagliala/vbhdn9te/14/

### Retina

![image](https://user-images.githubusercontent.com/556268/133467164-a5c98a7a-4607-40d8-8d4a-67e9eafb92f7.png)

### 1080p

![image](https://user-images.githubusercontent.com/556268/133467232-8ef298c7-d1f5-494a-9936-ac57a9d9f63b.png)


As you can see, according to the font size, the vertical alignment changes. The effect is minimal at 16px and almost non-existent at 32px, but you may notice that 18px does not play well on 1080p displays. Please also keep in mind that OSes have their own font rendering and anti aliasing libraries. Browser may display fonts differently. Font Awesome CSS uses a webfont, so font-size applies to icons

If your use case needs the best rendering results and perfect vertical alignment, especially at small sizes or non-multiples of 16px, you should opt for the SVG framework and ad-hoc transformations.

Example: https://jsfiddle.net/tagliala/L17f528g/581/

### Retina
![image](https://user-images.githubusercontent.com/556268/133467935-51d5c3b0-bbfb-42b9-a82e-178c5c1067bb.png)

### 1080p
![image](https://user-images.githubusercontent.com/556268/133467976-d0f056e3-2733-4436-9d61-847d19e2784c.png)
