### ISSUE TITLE
Icon request: Sourcerer

### ISSUE THREAD

**Issue by thisIsTheFoxe** [FortAwesome/Font-Awesome#16525]
**What can it be used for?**
Brand-Icon: [Sourcerer](https://sourcerer.io)
To link a Sourcerer profile. And to customise it if needed, since Sourcerer only provides a fully coloured svg with background and everything....

**Example image (optional)**
![Image](https://sourcerer.io/icons/logo-sharing.svg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by thisIsTheFoxe** [comment]
<img src="https://svgshare.com/i/KVX.svg" alt="drawing" width="100"/>
Not perfect but maybe a starting point or sth..  .-.

**Comment by edoardottt** [comment]
Up. I would like to have this.

**Comment by thisIsTheFoxe** [comment]
Closing this as Sourcerer shut down: 😔
- https://github.com/sourcerer-io/sourcerer-app/issues/632

cc: @abhishekv5055
