### ISSUE TITLE
Icon request: icon-share

### ISSUE THREAD

**Issue by arLevi** [FortAwesome/Font-Awesome#1652]
I like this form of share icon ( the box with the arrow )

Yet, if you can make the box and arrow more to the standard, otherwise it just looks weird ... like a driving sign on the road that wants me to take a right :)
Example: http://www.share-stuff.com/Content/img/linkIcon.png

Possible ?

**Comment by sakulich** [comment]
+1

**Comment by sensibleworld** [comment]
There a bunch of options for this now: https://fontawesome.com/v6.0/icons?q=share&s=solid%2Cbrands
