### ISSUE TITLE
Icon request: Major Digital Notation Workstation Icons for Engraving Sheet Music.

### ISSUE THREAD

**Issue by ShikiSuen** [FortAwesome/Font-Awesome#16523]
**What can it be used for?**
If a music engraving technology discussion community makes subforums for each DNW (Digital Notation Workstation), then each subforum deserves a standalone icon for each DNW.

**Example image (SVG)**
icons of 5 major DNW softwares made by myself in similar style.
(Dorico, Finale, Lilypond, MuseScore, Sibelius.)
[DNW Icons (SVG).zip](https://github.com/FortAwesome/Font-Awesome/files/4532222/DNW.Icons.SVG.zip)

**Icon request checklist**
- [pair] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [*] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [*] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [*] I have included at least one example image if it could be helpful (optional)
- [*] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> icons of 5 major DNW softwares made by myself in similar style.

Sorry, but if this request is about 5 brands, I cannot consider it a single/matched pair.

Please create different requests, having care of inserting the brand in the title

Closing here
