### ISSUE TITLE
Fullscreen Icon missing

### ISSUE THREAD

**Issue by miguelmello** [FortAwesome/Font-Awesome#16527]
Hi There,

Just for a suggestion, it would be cool a "Fullscreen" icon. I came along this recently when I was looking for an icon for.

Cheers,

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Actually we have a fullscreen icon but the search could be improved:

- https://fontawesome.com/icons/expand?style=solid
- https://fontawesome.com/icons/expand-wide?style=solid (FA Pro)

@talbs any chance to add `expand-*` to fullscreen search results? I'm only getting `compress` at the moment: https://fontawesome.com/icons?d=gallery&q=fullscreen&s=solid

**Comment by talbs** [comment]
Thanks for the good catch and feedback. And my apologies for the delay. I've got a PR set to update the metadata for all of our `expand` icons. This should be merged in and released shortly.
