### ISSUE TITLE
Leetcode logo :)

### ISSUE THREAD

**Issue by aaron-aguerrevere** [FortAwesome/Font-Awesome#16536]
Hi @Font-Awesome, 

Would it be at all possible for you to make a LeetCode icon?

Thanks for being indeed awesome!
Aaron

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #15337, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
