### ISSUE TITLE
Icon request: Mixcloud (new logo)

### ISSUE THREAD

**Issue by mistadizzle** [FortAwesome/Font-Awesome#16532]
Hey guys, Mixcloud have updated their logo and branding - is it possible to update it in the Elementor icons pls?

Many thx!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I cannot find official logo resources on mixcloud. It is not clear if for a squareish version of the logo they use just the M (as in favicon) or MIX (as in app store)

Any clarification?

**Comment by mistadizzle** [comment]
Hi,

Thx for getting back. The new one has the I and the X 90 degrees rotated.

Their support is: https://help.mixcloud.com/hc/en-us/requests/new

Hope this helps!

**Comment by dyrec** [comment]
Logo explained here : 
https://blog.mixcloud.com/2020/02/18/mixcloud-is-10/
https://www.studio-output.com/work/mixcloud/

**Comment by dyrec** [comment]
Assets attached 
![MIXCLOUD](https://user-images.githubusercontent.com/55164385/83977434-80737100-a8ce-11ea-89af-f11aec6328a3.png)
[MIXCLOUD-VECTOR.pdf](https://github.com/FortAwesome/Font-Awesome/files/4742710/MIXCLOUD-VECTOR.pdf)

**Comment by aethior** [comment]
> I cannot find official logo resources on mixcloud. It is not clear if for a squareish version of the logo they use just the M (as in favicon) or MIX (as in app store)

https://www.mixcloud.com/about/#brand
[MIX_Guidelines_AW_LowRes.pdf](https://github.com/FortAwesome/Font-Awesome/files/8508221/MIX_Guidelines_AW_LowRes.pdf) (page 16)

**Comment by aethior** [comment]
@tagliala `bug (category)` label for this request?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mixcloud?s=brands
