### ISSUE TITLE
FontAwesome Icons 4 on page and 5 in a specific box

### ISSUE THREAD

**Issue by Joooonathan** [FortAwesome/Font-Awesome#16534]
Hello,

I'm not sure if I'm in the right place, because my problem doesn't directly affect FontAwesome but JavaScript.
I generally use the FontAwesome icons in version 4 on my website (WoltLab Burning Board).
I have created a box in which I have included the JavaScript for the new version 5. But now the script affects the whole page and not only the box. In the rest of the page the icons should be in version 4 as before.
Is there a way to limit the JavaScript code or to check if the icon is in this box?
Thanks in advance, I hope you can help me.

With kind regards
Jonathan Chittka

My code (Box):
https://pastebin.com/AkBpb84P

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  Is there a way to limit the JavaScript code or to check if the icon is in this box?

Sorry, this is not possible at the moment. You should customize FA4 or manual edit FA5's javascript to fit your needs

It should be possible when a whitelist / blacklist approach will be implemented

Let's use #16438

Closing herre
