### ISSUE TITLE
Issue in fab fa-pinterest-p and fa-pinterest-square of Font Awesome 4 and 5 not  showing in Microsoft Edge

### ISSUE THREAD

**Issue by UltraHopeful** [FortAwesome/Font-Awesome#16546]
I spotted the issue of **fab fa-pinterest-p** and  **fab fa-pinterest-square** is not working on **_microsoft edge_** only fab fa-pinterest is working on Microsoft Edge. So, please solve this issue.
Please keep it add icons to your collection because it  is very helpful and easy to use by css classes instead of downloading the icons and use it as image(.png).
Here is  the screenshot from chrome latest version
![image](https://user-images.githubusercontent.com/43093789/80564003-4c24af00-8a0a-11ea-8d57-9551316d890e.png)

Here is the screenshot from Microsoft edge latest version
![image](https://user-images.githubusercontent.com/43093789/80564064-6f4f5e80-8a0a-11ea-9606-2173c51f12ac.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that your browser is loading a lot of extensions. One of them may be related to ad-blocking and some default filters hide social icons

Could you please retry in a private window?

Ref: #1799

**Comment by UltraHopeful** [comment]
**So Sorry** for that yes it is working in private window. So, as you say some of my extension hide pinterest. Again extremely sorry for that. Please remove this issue or close if possible.

**Comment by tagliala** [comment]
@UltraHopeful don't worry, glad you solved 👍
