### ISSUE TITLE
Icon request: user-circle-slash

### ISSUE THREAD

**Issue by interduo** [FortAwesome/Font-Awesome#16543]
**What can it be used for?**
The opposite of user-circle. Meaning "delete user-circle".

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Existing icons do not have a `times` variant, there are some `slash`ed options (eg: [users-slash](https://fontawesome.com/icons/users-slash?style=solid)

For the use case of deleting an user, there is [fa-user-times](https://fontawesome.com/icons/user-times?style=solid)

Could you please provide an example of how this icon should look like?

Please also keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/389/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by interduo** [comment]
In our app we use: 
- user - as normal user,
- user-circle - as owner,
- chalkboard-teacher - as verifier,

It would be marvelous if those icon have "+" and "x" versions.

**Comment by interduo** [comment]
> Demo: https://jsfiddle.net/tagliala/L17f528g/389/

First one is ok for all of the 3 icons.

**Comment by tagliala** [comment]
@interduo I will rename this request `user-circle-slash`, please open separate requests for the other two

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
