### ISSUE TITLE
Icon request: twitch

### ISSUE THREAD

**Issue by susanpaigen** [FortAwesome/Font-Awesome#16551]
Use: brand / social media icon

twitch tv logo

![twitch](https://user-images.githubusercontent.com/44618514/80654059-4e99ff80-8a30-11ea-9f88-5bdb6629c30e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Twitch is already here: https://fontawesome.com/icons/twitch?style=brands
