### ISSUE TITLE
IE11 - Icons is not loading in some iframes?

### ISSUE THREAD

**Issue by Rob1993** [FortAwesome/Font-Awesome#16556]
Only in IE11: When embedding 2 or more iframes that uses icons, only some iframes loads the icons. The other seems to be empty.

I created a fiddle: https://jsfiddle.net/Laxuz/8yj4u0dq/embedded/result,css,html,js

See this screenshot:
![image](https://user-images.githubusercontent.com/22733827/80703719-96c62a00-8ae3-11ea-8217-1c5445c56cf6.png)

One iframe got the icons, the other two didnt?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IE11 issue with webfonts here: http://jsfiddle.net/tagliala/kw7ohjvq/1/embedded/result

![image](https://user-images.githubusercontent.com/556268/80705068-089f7300-8ae6-11ea-8205-a9b0a2c2e380.png)

This will also affect CSS implementation of Font Awesome

For this use case, you may be interested in switching to SVG+JS implementation

Demo: 
- http://jsfiddle.net/tagliala/kw7ohjvq/3/embedded/result
- https://jsfiddle.net/tagliala/18v26o0z/

Hope it helps

Closing here

PS: FA 4.7 is in EOL, please upgrade to FA5
