### ISSUE TITLE
Icon Request: fa-orcid

### ISSUE THREAD

**Issue by meretaeppli** [FortAwesome/Font-Awesome#16567]
Hi!
I wanted to ask if you could make an icon for ORCID (https://orcid.org/). This ID is frequently used in academia to identify researchers. I would like to use it on my personal website. I think this icon could also be of use for others! The logo is fairly straight-forward, it is the letters 'id' in a circle:
[orcid.logo.icon.pdf](https://github.com/FortAwesome/Font-Awesome/files/4569303/orcid.logo.icon.pdf)
Thanks for considering my request :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

orcid is already here: https://fontawesome.com/icons/orcid?style=brands

Make sure that you are using Font Awesome >= 5.11.0

Closing here
