### ISSUE TITLE
Icon request: street-view-alien

### ISSUE THREAD

**Issue by panascope** [FortAwesome/Font-Awesome#16566]
**What can it be used for?**
To be used as a Street View Alien - Hopefully my finished version will meet standards

![street-view-alien](https://user-images.githubusercontent.com/23144580/80871977-2a297600-8d03-11ea-949a-1b7da9ce4e37.png)

**Example image (optional)**
[street-view-alien.pdf](https://github.com/FortAwesome/Font-Awesome/files/4568473/street-view-alien.pdf)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but could you please provide a use case?

Please also keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework and Font Awesome Pro.

Demo: https://jsfiddle.net/tagliala/L17f528g/402/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by panascope** [comment]
oh wow! that is some wonderful technique Geremia to mix and match icons parts like you have in this example. I had no idea that was possible.

**Regarding use case**: well none specifically.  I just love your existing alien icons and use them here: https://panascope.nz my site uses street view a good deal as well. So it inspired the icon mashup

cheers : )

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
