### ISSUE TITLE
Icon request: allsocial

### ISSUE THREAD

**Issue by jasonmorehead** [FortAwesome/Font-Awesome#16565]
**What can it be used for?**

Adding links to profiles on [Allsocial](https://allsocial.com/) (a relatively new social network).

**Example image (optional)**

![icon-1024](https://user-images.githubusercontent.com/1703762/80865687-9d25e480-8c50-11ea-9839-fdf7748a6ef8.png)

**Icon request checklist**

- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
AllSocial was closed in 2020 without a public announcement.

<sup>1</sup>https://boisedev.com/news/2020/11/24/allsocial-eagle-idaho-offline/
<sup>2</sup>https://opuszine.us/posts/what-happened-allsocial

cc/ @tagliala
