### ISSUE TITLE
Icon request: fa-snowflake-play

### ISSUE THREAD

**Issue by mark-steven-au** [FortAwesome/Font-Awesome#16579]
icon request 
snowtv

This logo can cover any videos filmed in the snow as currently there is nothing even close available.
Describe how this could be used / the use case for this icon.
It can be used for any button that denotes a snow-video.
An icon on buttons Play button or other similar use.
**Example image (optional)**
Insert the example image here if necessary.
![SnowTV](https://user-images.githubusercontent.com/53360974/81042270-18a6c080-8ef3-11ea-9ade-17da676fa3b7.png)
[snowtv.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/4579289/snowtv.svg.zip)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
Unlocked svg file and png example
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
"snowtv"
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
There is nothing close hence why I built this one as example
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mark-steven-au** [comment]
![SnowTV](https://user-images.githubusercontent.com/53360974/81294613-7d5c4980-90b2-11ea-84e8-2c5721c77b7a.png)
Have a SVg version too if needed

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for a brand?

**Comment by mark-steven-au** [comment]
HI Geremia,
No it is for a new icon to cover snow videos that anyone can use.

Any other questions by all means drop me an email.

Hope this helps

Cheers
Mark

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/407/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by mark-steven-au** [comment]
Hi Geremia,
Yes understand I can build them for my own use.
But would still like to release this to the community as I see place for a snow video icon as there was nothing like it anywhere.
Hence why I contacted you guys on this as there is a hole in the offerings.

Hope the home quarantining is going well.

Cheers
Mark

**Comment by mark-steven-au** [comment]
Hi Geremia,
Just following up in case I need to do anything more on my side in this regard?
Or is it in a pipeline somewhere now and just wait?

Cheers
Mark

**Comment by tagliala** [comment]
Hi,

Take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

My suggestion is to create a custom version of Font Awesome or use layering feature if you need this icon in a short while

Ref:
- https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by mark-steven-au** [comment]
HI Geremia,
Thanks yet again for that.
Have read the docs and support pages for information as 
I see that the icon I have requested is not on the request leader board and as far as I can tell I have done everything my end
So do I just leave it with the organisation and it eventually finds its way onto that board so others can vote on it?
If it is just a matter of waiting for things to happen then that’s fine as there is no rush.

Sorry to pester but the steps seem unclear.

Also see you can sponsor a logo through. 
How does that work as could not find any information on that idea eeither

Regards
Mark

**Comment by tagliala** [comment]
> I see that the icon I have requested is not on the request leader board and as far as I can tell I have done everything my end

Correct

> So do I just leave it with the organisation and it eventually finds its way onto that board so others can vote on it?

If someone else is interested in this icon, they will upvote.

> If it is just a matter of waiting for things to happen then that’s fine as there is no rush.

It isn't only a matter of waiting, we have still issue open from 2013. Take another look at the FAQs: https://fontawesome.com/community/leaderboard/new#faqs

> Also see you can sponsor a logo through.

Yes, you can sponsor an icon if you definitely need it. But this is out of the scope of the issue tracker, please contact hello@fontawesome.com for more details

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
