### ISSUE TITLE
Could not find a declaration file for module '@fortawesome/fontawesome-pro'. 

### ISSUE THREAD

**Issue by fmrogers** [FortAwesome/Font-Awesome#16570]
**Describe the bug**
Installed @fortawesome/fontawesome-pro from NPM and tried to import into my Create-React-App project only to get the warning: 

```
Could not find a declaration file for module '@fortawesome/fontawesome-pro'. '/home/fmrogers/Projects/rottlan-count-down/node_modules/@fortawesome/fontawesome-pro/js/fontawesome.js' implicitly has an 'any' type.
  Try `npm install @types/fortawesome__fontawesome-pro` if it exists or add a new declaration (.d.ts) file containing `declare module '@fortawesome/fontawesome-pro';`ts(7016)
```
I looked in the modules folder and could not find any .d.ts file.

**Install command:**
npm i @fortawesome/fontawesome-pro

**Version and implementation**
Version: "@fortawesome/fontawesome-pro": "^5.13.0",

-

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Disclaimer: I'm not a javascript developer

`fontawesome-pro` is an all-in-one package that contains everything from css, to js packages, to desktop otf.

in that package, `/js` folders contains the JavaScript distribution file for the web. I do not expect `.d.ts` to be mandatory for such a file

Maybe you are interested in more specific packages, such as `@fortawesome/fontawesome-svg-core`, `@fortawesome/pro-solid-svg-icons`, and `@fortawesome/react-fontawesome`

Please also take a look here: https://github.com/FortAwesome/react-fontawesome#introduction

Let me know if this helps

**Comment by fmrogers** [comment]
@tagliala Thank you i just assumed the all-in-one package would include the `.d.ts` files i tried your suggestions and it worked perfectly.

**Comment by tagliala** [comment]
Hi @fmrogers , sorry I've fixed my answer above.

I don't know which implementation you exactly need, but there is this package: `@fortawesome/fontawesome-common-types` that you may interested to explicitly require if for some reasons `@fortawesome/fontawesome-pro`. Note: this is not tested, I'm not getting that warning

**Comment by danawoodman** [comment]
Bit of feedback @tagliala: Highly recommend the [docs on setup](https://fontawesome.com/v6/docs/web/setup/packages) for npm list all the available npm packages as the default recommendation just says to install `@fortawesome/fontawesome-pro` which has no typing. 

You have to look at something like the react docs to know these exist so if you're like me using Svelte, you'd never see these without googling (as I just did 😉)
