### ISSUE TITLE
Icon request: social_profiles

### ISSUE THREAD

**Issue by urShadoww** [FortAwesome/Font-Awesome#16576]
**What can it be used for?**
A usual website has its presence on several social networks. Usually, all those networks are displayed as icons/images, together in a line, on a website. It is not easy to make space for all those icons and adding or removing an icon can break the design. Sometimes to make space, those icons are made too small, that those can be easily missed by the visitor.
I want to propose an icon which should represent social profiles/networks. A user can click on that icon to see all available social profiles/networks.
I am currently using this strategy on the menu of my website by using a custom image to represent social profiles/networks: [The Clear Evidence](https://theclearevidence.org/)

**Example image (optional)**
[Custom image to represent social profiles/networks on my website](https://theclearevidence.org/wp-content/uploads/2019/01/The-Clear-Evidence-Social-Media-Icon.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I understand the need of having a "social profiles" icon, but we should find another solution. 

We are doing our best to meet brand guidelines, and squashing twitter and Facebook together in a single icon is a practice that you can do as a user, but we would like to avoid in the framework

**Comment by urShadoww** [comment]
Hi @tagliala 

Thanks for your response.

I did not intend to recommend using FB and Twitter icons together to make the social profiles icon, it was just an example. I wanted to suggest that there should be a unique icon, like the hamburger icon is recognized for representing a menu, something similar, which might take some time to catch up but can become a de facto to represent social profiles.

**Comment by tagliala** [comment]
>  which might take some time to catch up but can become a de facto to represent social profiles.

I can leave this open for feedback from the community, that's the best I can do

>  I have included at least one example image if it could be helpful (optional)
> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

The above points are not met, I've unchecked them

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
