### ISSUE TITLE
No license header in build files

### ISSUE THREAD

**Issue by ihmels** [FortAwesome/Font-Awesome#16580]
**Describe the bug**
I'm using @fortawesome/vue-fontawesome to embed Font Awesome Free icons in a Vue.js web application. The resulting build does not contain any [attribution in the form of a comment](https://fontawesome.com/license/free).

I think the problem is that none of the imported packages include such a license comment.

**To Reproduce**
```js
import Vue from 'vue';
import { library, config } from '@fortawesome/fontawesome-svg-core';
import { faBan } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

config.autoAddCss = false;

library.add(faBan);

Vue.component('font-awesome-icon', FontAwesomeIcon);
```

**Expected behavior**
I would expect that the resulting build contains a comment like the following:

```js
/*!
 * Font Awesome Free 5.13.0 by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
 */
```

**Screenshots**
N/A

**Version and implementation**

Versions:

- @fortawesome/fontawesome-common-types: 0.2.28
- @fortawesome/fontawesome-svg-core: 1.2.28
- @fortawesome/free-solid-svg-icons: 5.13.0
- @fortawesome/vue-fontawesome: 0.1.9

Browser and version: N/A

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can replicate with my webpack(er) build, I can see this on the top of the js file:

```
/*! For license information please see application-e80170240d9041910ae2.js.LICENSE.txt */
```

And that file does not include FontAwesome's license comment

https://ruby2-rails6-bootstrap-heroku.herokuapp.com/packs/js/application-e80170240d9041910ae2.js.LICENSE.txt 

(Source: https://github.com/diowa/ruby2-rails6-bootstrap-heroku/blob/master/app/javascript/src/fontawesome.js)

I'm going to assign @robmadole

**Comment by ihmels** [comment]
Hi! Are there any news on this issue yet? 😇

**Comment by robmadole** [comment]
Thanks @ihmels . Make sense and you are 100% right. We'll get this on the todo list.
