### ISSUE TITLE
Strava Icon

### ISSUE THREAD

**Issue by Jamesdurling** [FortAwesome/Font-Awesome#16599]
Hi,

I recently start my blogger website and was so happy to find your code for Strava! I have successfully added the code and it's working. However, the symbol does not appear as noticeable as my others. Can you look at my site www.jamesdurling.ca and you will see what I mean. My question is is there a different code I should use?

Thanks for your help!
James

**Describe the bug**
What happened? What are you seeing? How did you arrive here?

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your website is loading Font Awesome 4.6.3 through the old CDN

```
<link rel="stylesheet" href="https://use.fontawesome.com/90ef38dbc3.css" media="all">
```

[strava](https://fontawesome.com/icons/strava?style=brands) has been introduced in Font Awesome 5.8.0

Please make sure to update to Font Awesome >= 5.8.0

Please also note that FA 5 contains breaking changes, and it requires a different prefix for brands

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

Closing here

**Comment by Jamesdurling** [comment]
Thank you. The only code I used was <i class="fab fa-strava"></i>
.....should I use something different? Should have mentioned that at the
beginning as I am not a Pro user

Thanks,
James

**Comment by tagliala** [comment]
You're welcome

> The only code I used was <i class="fab fa-strava"></i>
.....should I use something different?

This is the correct code

> Should have mentioned that at the
beginning as I am not a Pro user

No problem, this is the correct repo to report issues and brands ara available for free users. There is no need to be a Pro user to use strava icon on your website, just make sure to use the latest font awesome version

**Comment by Jamesdurling** [comment]
Sorry I am not clear....if thats the only code I am using and its the right
one. How do I update it so its more uniform with the ones I am using for
Linkendin, Instagram, etc?

**Comment by tagliala** [comment]
Hi, 

> if thats the only code I am using and its the right
one. 

This
```
<link rel="stylesheet" href="https://use.fontawesome.com/90ef38dbc3.css" media="all">
```

is the code to an outdated version of font awesome that is no longer supported.

You can request a kit: https://fontawesome.com/start or use font awesome css from a third party cdn https://cdnjs.com/libraries/font-awesome

In the process of updating font awesome from 4 to 5, please keep in mind of breaking changes: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps 

Closing here
