### ISSUE TITLE
Icon request: icon-hanger

### ISSUE THREAD

**Issue by irfaan** [FortAwesome/Font-Awesome#1659]
Hello!

I was thinking that a hanger would be a useful addition to the project - i quite like the following, which does not create a closed loop.

![ironduck_m](https://f.cloud.github.com/assets/1435018/867438/52701bdc-f6f6-11e2-920a-59609e2d8b61.jpg)

Thoughts?

**Comment by semenov-anton** [comment]
+1
https://cloud.githubusercontent.com/assets/6369471/5218514/d1973594-761b-11e4-8461-f51af197073b.png

**Comment by carloct** [comment]
+1

**Comment by showplans** [comment]
+1

**Comment by richnicholls404** [comment]
+1

**Comment by lidfill** [comment]
+1

**Comment by lifeiscontent** [comment]
not sure if you guys want it, but I designed this SVG hanger http://codepen.io/lifeiscontent/pen/XmGBgw

**Comment by alinearielo** [comment]
+1

**Comment by 9nix6** [comment]
fa-hanger would definitely com in handy as well as other clothing related icons for online clothing shops.

**Comment by TheCre8r** [comment]
+1

**Comment by elterko** [comment]
+1

**Comment by xavigarcia** [comment]
I prefer something like this, better than an empty hanger:

<img width="62" alt="screen shot 2016-11-26 at 13 49 40" src="https://cloud.githubusercontent.com/assets/2465208/20640521/036da59a-b3e0-11e6-82e7-f494a757cea3.png">

**Comment by rodu-pereira** [comment]
+1

**Comment by jakeseaton** [comment]
+1

**Comment by heartsash** [comment]
+1

**Comment by nicojones** [comment]
+1

**Comment by matthiasgoossens** [comment]
+1

**Comment by petsoukos** [comment]
Opened up fontawesome website to look for it being sure it would exist and was shocked not to find it!!
:+1:

**Comment by Tylerian** [comment]
> I prefer something like this, better than an empty hanger:
> 
> <img alt="screen shot 2016-11-26 at 13 49 40" width="62" src="https://cloud.githubusercontent.com/assets/2465208/20640521/036da59a-b3e0-11e6-82e7-f494a757cea3.png">

+1 for either designs

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download

**Comment by LucasGorgal** [comment]
+1
