### ISSUE TITLE
Icons are minimal size and sometimes just a box and sometimes a question mark

### ISSUE THREAD

**Issue by Nerdtek** [FortAwesome/Font-Awesome#16602]
I've just installed version 5.13.0 and can't get any of the icons to work.  I've tried a stand-alone test with no other conflicting css, and in my web app as well.
The first one was the cog I got just copied the code right from the website.
<i class="fas fa-cog"></i>
it renders super small and is a question mark.  I had to zoom in to see that
Next I tried the motorcycle 
<i class="fas fa-motorcycle"></i>
This shows as a box but of normal size.
The home icon shows as a supersmall (once again had to zoom in to see it) tilde.
<i class="fas fa-home"></i>

I've downloaded a copy from your website to try and eliminate a faulty version at cdnjs.  I've isolated with no other css or javascript and get the same behaviour.  I've accounted for cache issues as well, no change in behaviour with refreshed page.  (ctrl f5 in chrome, also manually clearing cache via history)  Firefox is demonstrating exactly the same behaviour as is Microsoft Edge.  The behaviour is the same on Ubuntu 20.04 as well as Windows 10.  (obviously didn't test Edge in Ubuntu)

Not sure what's up, but really disappointed as I am starting a new project and was looking forward to using your icons for it.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If you provide a reproducible test case I will take a look

**Comment by Nerdtek** [comment]
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='lib/font-awesome/css/fontawesome.min.css' />
</head>
<body>
    <div><i class="fas fa-cog"></i></div>
    <div><i class="fas fa-motorcycle"></i></div>
    <div><i class="fas fa-home"></i></div>
    
    <script src="lib/font-awesome/js/fontawesome.min.js"></script>
</body>
</html>

**Comment by Nerdtek** [comment]
I've installed fontawesome in my lib/font-awesome/js/font-awesome folder.

**Comment by Nerdtek** [comment]
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='lib/font-awesome/css/fontawesome.min.css' />
</head>
<body>
    <div><i class="fas fa-cog"></i></div>
    <div><i class="fas fa-motorcycle"></i></div>
    <div><i class="fas fa-home"></i></div>
    
    <script src="lib/font-awesome/js/fontawesome.min.js"></script>
</body>
</html>
```

**Comment by tagliala** [comment]
Hi @Nerdtek 

I can see that you are using both CSS and SCG implementation. They should not be used together, you should pick the one that most suits your use case.

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

If you decide to go for CSS implementation, please also copy webfonts and make sure that the fontawesome css is able to find the font files in the proper folder (check development console). Also, your application server should have the proper mime types for font files

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-web-fonts

Hope it helps

Closing here but feel free to comment
