### ISSUE TITLE
Icon is not getting displayed for handshake

### ISSUE THREAD

**Issue by shrutigudhka** [FortAwesome/Font-Awesome#16614]
<i class="fas fa-handshake-slash"></i>
<i class="fas fa-handshake-alt-slash"></i>

These two fonts are not visible

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

Meanwhile, closing here
