### ISSUE TITLE
Icon request: icon-scribd

### ISSUE THREAD

**Issue by CasperBHansen** [FortAwesome/Font-Awesome#1661]
I'd like to request the brand icon for Scribd, for the same type of use as with any social/sharing network icons. I cannot find any vector images of their logo on their site, sorry.

http://www.scribd.com/

**Comment by tiagoangelo** [comment]
Hi!

So, there's a request since 2013 and still haven't created scribd icon?... :/
I need it too... please...

**Comment by aleksandar-todorovic** [comment]
We could definitely use this icon since Scribd is practically a place to go if you want to publish your papers and presentations. Adding an icon inside of this pack would allow anyone to use this icon to provide a link to their Scribd profile where they will showcase their writings.

:+1:

**Comment by aethior** [comment]
+1

**Comment by adipau** [comment]
I'm needing this too please... +1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.
