### ISSUE TITLE
Icon Request: customer service

### ISSUE THREAD

**Issue by hc-mia-li** [FortAwesome/Font-Awesome#16617]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have some icons that could represent a customer service:
- https://fontawesome.com/icons/user-headset?style=solid (pro)
- https://fontawesome.com/icons/life-ring?style=solid
- https://fontawesome.com/icons/headset?style=solid

If you have something more specific in mind, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example

Closing here
