### ISSUE TITLE
Icon Request: Hoodies and Zipper

### ISSUE THREAD

**Issue by Timer91** [FortAwesome/Font-Awesome#16623]
It would be nice to have more clothes icons including hoodies and/or zippers.

Thx ✋ ❤️

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please split this request in two separate ones?

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by tagliala** [comment]
Hi!

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
