### ISSUE TITLE
Icon request: Medical - Imaging Icons MRI , CTSCAN

### ISSUE THREAD

**Issue by npagare** [FortAwesome/Font-Awesome#16629]
**What can it be used for?**
Healthcare | Medical 

Hello, would you please help with icons for Medical Imaging modalities such as MRI, CTScan, Mammography, Tomotography, BSGI/MBI.... Along with Biopsy and Surgical

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/26844611/81913959-485e6400-9596-11ea-98ab-97780d28e6a8.png)

![image](https://user-images.githubusercontent.com/26844611/81914024-5e6c2480-9596-11ea-8461-955c08734694.png)

![image](https://user-images.githubusercontent.com/26844611/81914196-9a9f8500-9596-11ea-96ab-c5550a3a2c67.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by IoTFier** [comment]
Hello, any thoughts on this request ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late response.

I can't correctly understand this request.

Is it a request for multiple icons?

If yes, Then it should split into different individual icons, each one with its own example, **unless** they are so strictly related that they should come both in the same request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
