### ISSUE TITLE
Icon request: fa-topic (horizontal cylinder, horizontal stack)

### ISSUE THREAD

**Issue by mattrpav** [FortAwesome/Font-Awesome#16625]
**What can it be used for?**
Indicating a 'topic' used by computer applications to move data asynchronously, or between distributed systems

Note-- this is also related to a queue or stack (#11203). 

Contextually:
* Queues/Stacks are 1-to-1
* Topics are 1-to-many

**Example image (optional)**
horizontal cylinder 

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> horizontal cylinder

Sorry, can't get the example, could you please provide an image?

**Comment by mattrpav** [comment]
I quickly drew this one and attached

For reference, here is a more technical view.. the topic is generally represented as a horizontal cylinder. The producers and consumers are different objects, and should not be considered part of the ‘topic’ in terms of designing the icon.

Technical reference of related concepts:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/media/service-bus-java-how-to-use-topics-subscriptions/sb-topics-01.png

https://flylib.com/books/2/228/1/html/2/images/jboss_0704.jpg

https://www.oreilly.com/library/view/java-message-service/0596000685/httpatomoreillycomsourceoreillyimages138785.png

https://www.novell.com/documentation/extend5/Docs/help/MP/jms/concepts/images/pubsub.gif

**Comment by mattrpav** [comment]
![fa-topic](https://user-images.githubusercontent.com/512119/81842653-faa01800-9511-11ea-8481-378bfb2d0547.png)

**Comment by tagliala** [comment]
@mattrpav thanks

just the horizontal cylinder? I'm asking because the icon should work at small sizes (16px), and the two arrows with circles make it hard to implement

**Comment by mattrpav** [comment]
@tagliala maybe horizontal cylinder w/ 4 or so bars in the middle (representing data as events or messages)? The microsoft at flylib ref links above give you an idea.

I think the challenge is to make it not look like the battery indicator icon.
![fa-topic-2](https://user-images.githubusercontent.com/512119/81843434-35ef1680-9513-11ea-9671-e82759691344.png)

**Comment by mattrpav** [comment]
bonus design points would be the 'vertical' version of the same icon solves for the 'queue' or 'stack' concept which is common to be described alongside a topic. 

ref: fa-stack/queue request: #11203

**Comment by tagliala** [comment]
Ok, thanks 👍🏼

> ![fa-topic-2](https://user-images.githubusercontent.com/512119/81843434-35ef1680-9513-11ea-9671-e82759691344.png)

This should look good at small sizes

> <img width="139" alt="fa-topic-ms-reference" src="https://user-images.githubusercontent.com/512119/81843583-646cf180-9513-11ea-88a0-12a766d64914.png">

This one too

> I think the challenge is to make it not look like the battery indicator icon.

yes, a horizontal stack will just look like a battery without the cathode

**Comment by mattrpav** [comment]
![Canvas 1](https://user-images.githubusercontent.com/512119/81846441-b1eb5d80-9517-11ea-85d2-6c10cc53444a.png)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
