### ISSUE TITLE
Icon request: mother-holding-baby

### ISSUE THREAD

**Issue by createitcarlos** [FortAwesome/Font-Awesome#16621]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Will be used on a non-profit website that serves low-income first-time mothers with new babies

**Example image (optional)**
Insert the example image here if necessary.

[https://www.shutterstock.com/image-vector/mother-baby-stylized-vector-symbol-382112551](https://www.shutterstock.com/image-vector/mother-baby-stylized-vector-symbol-382112551)

[https://www.shutterstock.com/image-vector/woman-mother-mom-nurse-holding-newborn-516879589](https://www.shutterstock.com/image-vector/woman-mother-mom-nurse-holding-newborn-516879589)

**Icon request checklist**
- [ X] This is a single icon or matched pair (Ex: `lock` / `unlock`) 
single
- [ X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`) 
mother-holding-baby
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
Yes
- [X ] I have included at least one example image if it could be helpful (optional) - as links
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @createitcarlos,

Something like https://fontawesome.com/icons/person-breastfeeding?

Regards.

**Comment by tagliala** [comment]
Given the examples, I would consider this request fulfilled
