### ISSUE TITLE
Icon request: thinking (smiley)

### ISSUE THREAD

**Issue by fabien-michel** [FortAwesome/Font-Awesome#16639]
**What can it be used for?**
Illustrate situation where user choices are not obvious, and may need double-ckeck.
Illustrate situation where machine is computing

**Example image (optional)**
![kisspng-emoji-thought-clip-art-think-5ac00a5c45bd26 1212722715225350042857](https://user-images.githubusercontent.com/1167556/82023421-8c349480-968e-11ea-890c-dd30acce568a.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by hpvd** [comment]
+1

**Comment by aethior** [comment]
Hi @fabien-michel,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/face-thinking

Regards.

cc/ @tagliala
