### ISSUE TITLE
Embed code from cdn.fontawesome.com returns v4.7.0

### ISSUE THREAD

**Issue by janus-crey** [FortAwesome/Font-Awesome#16632]
**Describe the bug**
I wanted to use Font Awesome as a CSS `@import`, but unfortunately I couldn't find that option in the documentation on fontawesome.com.

I searched for a solution and ended up on cdn.fontawesome.com, and proceed to generate an embed code to use. However, it didn't work.

I discovered that the given URL returns an older version and there is no way to specify a newer version.

**To Reproduce**
This is the URL that using cdn.fontawesome.com gives me:

https://use.fontawesome.com/c19504a186.css

**Expected behavior**
I wanted a working version :-)

I suspect that cdn.fontawesome.com is not supported any more?

But I would really like a way to use a CSS @import rather than HTML or JS.

**Version and implementation**

Browser and version: Newest Firefox Dev Edition and Chrome.
- [ ] SVG with JS
- [ x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ x ] I have filled out as much of the above information as I can
- [ x ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I suspect that cdn.fontawesome.com is not supported any more?

Correct, cdn.fontawesome.com is an old service, sorry 😅

Font Awesome's official CDN is being sunsetted, but there are third parties like cdnjs: https://cdnjs.com/libraries/font-awesome

Hope it helps

Closing here, but feel free to comment

**Comment by janus-crey** [comment]
Great, thank you very much!

**Comment by f0o** [comment]
Would you mind updating your page stating so? Right now it still advocates to create a FontAwesome CDN Account and be stuck on 4.7.0 (literally just happened to me).

**Comment by tagliala** [comment]
@f0o 

> Right now it still advocates to create a FontAwesome CDN Account and be stuck on 4.7.0 (literally just happened to me).

which page?

**Comment by f0o** [comment]
https://fontawesome.com/start

**Comment by tagliala** [comment]
@f0o that is correct

It is asking to create a Font Awesome account to use Font Awesome Kits. If you are not interested in Kits, feel free to self-host Font Awesome or use third party services 


Font Awesome Kits do not support FA 4.7, why are you stuck on 4.7?

**Comment by f0o** [comment]
You're correct for some reason I ended up on https://cdn.fontawesome.com/embed-codes when I was looking for integrating fontawesome yesterday.

Disregard my comments :upside_down_face:

**Comment by tagliala** [comment]
@f0o I suspected that 😅

@robmadole any chance to put a big alert on  https://cdn.fontawesome.com ?
