### ISSUE TITLE
Some icons showing as question mark. 

### ISSUE THREAD

**Issue by JamesVanWaza** [FortAwesome/Font-Awesome#16644]
**Describe the bug**
I copied and pasted the bars icon, in Adobe XD but it was a question mark, but when I tried the 500px icon it worked. 

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
I would like any glyph I copy it should work. 

**Screenshots**
I have video, how do I submit that? 

**Version and implementation**
Version: 5.13.0

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I do not own Adobe XD, so I will provide generic hints

> when I tried the 500px icon it worked.

Font Awesome Brands use the default font weight of 400, so you just need to to select the font and copy the glyph

> I copied and pasted the bars icon, in Adobe XD but it was a question mark, 

If we are referencing to Bars icon in Solid Style, then just selecting the font is not enough, you should also select the font-weight and set it to bold 

Docs: https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-glyphs

**Comment by JamesVanWaza** [comment]
@tagliala, that did help. Thank You Very Much 

<img width="1333" alt="Screen Shot 2020-05-16 at 10 03 32 AM" src="https://user-images.githubusercontent.com/4000076/82121629-9a50e680-975c-11ea-8241-ffa6a313134f.png">

**Comment by tagliala** [comment]
Welcome, closing here
