### ISSUE TITLE
Icon request: fab-microsoft-store

### ISSUE THREAD

**Issue by ratajs** [FortAwesome/Font-Awesome#16640]
**What can it be used for?**
It can be used for links to Microsoft Store application. You have Google Play, you should also have Microsoft Store.

**Example image (optional)**
![Microsoft Store](https://upload.wikimedia.org/wikipedia/commons/a/a7/Microsoft_Store.svg)
![Microsoft Store](https://upload.wikimedia.org/wikipedia/commons/1/1b/Windows_Store_Logo.svg)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to rename #13914 as `microsoft-store`, because it is the correct name

Please +1 that request

Closing here
