### ISSUE TITLE
Hi on my website the icons dosen't show onlay on home page however it was showing befor #16656

### ISSUE THREAD

**Issue by MohammdKopa** [FortAwesome/Font-Awesome#16657]
Hi on my website the icons dosen't show onlay on home page however it was showing befor
My websit is:https://www.keba-dresses.com
i use OceanWp theme And elemntor all up to date

i have the Font Awesome plugin her is my sttings 
![image](https://user-images.githubusercontent.com/65500530/82157640-69bb9a80-988b-11ea-978a-cfab605a7492.png)

**Comment by tagliala** [comment]
Let's use #16656
