### ISSUE TITLE
Hi on my website the icons dosen't show onlay on home page however it was showing befor

### ISSUE THREAD

**Issue by MohammdKopa** [FortAwesome/Font-Awesome#16656]
Hi on my website the icons dosen't show onlay on home page however it was showing befor
My websit is:https://www.keba-dresses.com
i use OceanWp theme And elemntor all up to date

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Hi on my website the icons dosen't show onlay on home page however it was showing before

I can see font awesome icons on your homepage

Some icons that I cannot see are not relative to font awesome (e.g.: `icon-envelope`, belonging to `'simple-line-icons'`)

> i use OceanWp theme And elemntor all up to date

I can notice that they are loading font awesome twice, you should fix that and load font awesome once. You may be interested in our official plugin for Wordpress: https://wordpress.org/plugins/font-awesome/

Please note that we do not provide support for third party extensions

Hope it helps

Closing here

**Comment by MohammdKopa** [comment]
@tagliala i did instal the plugin but same problem here a screenshot 
![image](https://user-images.githubusercontent.com/65500530/82155859-77b7ee00-9880-11ea-84c7-cfc4ad92a23b.png)
are they currect?

**Comment by tagliala** [comment]
Hi,

good, now I can see also 5.13.0 installed, but third parties are still loading their version of font awesome.

Please run the conflict scanner. Docs: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress#troubleshooting

**Comment by tagliala** [comment]
Please also notice that I'm getting errors that do not depend on font awesome while browsing your website:

![image](https://user-images.githubusercontent.com/556268/82157803-f4989700-9883-11ea-8e1e-1688a6254fce.png)
