### ISSUE TITLE
Icon request: Pakistani Rupee

### ISSUE THREAD

**Issue by KhanzadaArbaaz** [FortAwesome/Font-Awesome#16651]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
i wanaa Rs icon represent to Pakistani Rupee sign
**Example image (optional)**
Insert the example image here if necessary.
[https://www.flaticon.com/free-icon/pakistan-rupee-currency-symbol_33181](url)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by ayoubkhan558** [comment]
Yes we need that.

**Comment by KhanzadaArbaaz** [comment]
![image](https://user-images.githubusercontent.com/50293635/82355552-c9e14680-9a1b-11ea-8f03-fb82e74474bf.png)
No its something like that because its offical pakistani rupee sign

**Comment by sensibleworld** [comment]
Hey folks. This is available in the version 6 alpha release: https://fontawesome.com/download

**Comment by ayoubkhan558** [comment]
Good to see PKR icon in font awesome.

**Comment by ayoubkhan558** [comment]
![image](https://user-images.githubusercontent.com/20210961/112047455-8c9d8780-8b0a-11eb-9e40-b3ad5572af6e.png)
Is this a Pakistani rupee icon???

**Comment by ayoubkhan558** [comment]
I can not see Pakistani rupee icon latest alpha release. You have added indian rupee icon instead of Pakistani rupee icon.

**Comment by sensibleworld** [comment]
@ayoubkhan558 In the research we did, we found the [Pakistani rupee](https://www.google.com/search?q=Pakistani+rupee+symbol&client=safari&rls=en&ei=xvVYYKLzEI6b_Qa3xgE&oq=Pakistani+rupee+symbol&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEEYQ-wE6BwgAEEcQsAM6BAgAEEM6CAgAELEDEIMBOgIIADoFCAAQyQM6BggAEBYQHlCbD1iZF2CnGGgBcAJ4AIABdYgB9wWSAQM2LjKYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=gws-wiz&ved=0ahUKEwii7uLh1sTvAhWOTd8KHTdjAAAQ4dUDCAw&uact=5) listed with the [₨ symbol](https://en.wikipedia.org/wiki/Pakistani_rupee). Is that not correct?

**Comment by ayoubkhan558** [comment]
@tagliala You have added Indian rupee icon instead of Pakistani rupee icon.

**Comment by tagliala** [comment]
@ayoubkhan558 there is also a `₨` symbol, available as `rupee-sign`

![image](https://user-images.githubusercontent.com/556268/112130185-8241c300-8bc8-11eb-94ce-1eb273420173.png)

If this is not correct, please provide an official reference

**Comment by ayoubkhan558** [comment]
https://www.quora.com/What-is-the-National-Currency-Symbol-of-Pakistan


![image](https://user-images.githubusercontent.com/20210961/112136117-ca8ec000-8b8b-11eb-9a07-2f9e78e45e1e.png)

![image](https://user-images.githubusercontent.com/20210961/112136382-19d4f080-8b8c-11eb-937e-3771ea03cd46.png)

**Comment by sensibleworld** [comment]
That article still isn't 100% clear. Which of the two symbols shown is correct? It also mentions: "The Pakistani rupee روپیہ‎ / Rūpiyah ₨ is made up of 100 paise and is often represented by the symbol Rp. It is often referred to as rupees, rupaya, or rupaye." We have both the Rs and the Rp symbol in v6.

**Comment by tagliala** [comment]
@ayoubkhan558 If I may add, any governative reference or wikipedia page would work better than Quora.

If the problem is that the symbol used daily hasn't a Unicode reference so it is digitally written as Rs or ₨, then please clarify

@sensibleworld I think that the unicode entity ₨ should be preserved in any case and this request should stay closed. We may then open a new request and wait for other feedback and clarifications

Quoting from the opening post:

> i wanaa **Rs** icon represent to Pakistani Rupee sign

(**emphasis** mine)

**Comment by sensibleworld** [comment]
@tagliala Agreed. When possible, I try to reference the Unicode representations, but am certainly open to alternates if there's precedent or support. A new issue would be best.

**Comment by ayoubkhan558** [comment]
Here is Wikipedia reference
https://en.wikipedia.org/wiki/National_symbols_of_Pakistan
https://en.wikipedia.org/wiki/Pakistani_rupee
