### ISSUE TITLE
Update Telegram logo to the new one

### ISSUE THREAD

**Issue by sprtako** [FortAwesome/Font-Awesome#16664]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sprtako** [comment]
This is the new one:
[https://telegram.org/img/t_logo.png?1](url)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by tagliala** [comment]
ping @sensibleworld

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
