### ISSUE TITLE
Icon request: lww-icon

### ISSUE THREAD

**Issue by luke-wilson180** [FortAwesome/Font-Awesome#16668]
**What can it be used for?**
My new website company where i am creating content managment systems for clients.

**Example image (optional)**
<i class="fab fa-mdb"></i> 

^ Very similar to this icon but with the letters 'LWW'. The same colour or a solid black.

**Icon request checklist**
- [N] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [Y] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [Y] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [Y] I have included at least one example image if it could be helpful (optional)
- [Y] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

If this is a brand, please provide more details about the brand as well as an image representing the actual logo

**Comment by luke-wilson180** [comment]
Hi,

That’s for the speedy response and I’m glad to be a part of the community. The icon is for a new side business I am creating where I am developing content management systems for business in my local area. I a few years experience and I am finally putting this experience into developing this brand. Because the brand is new I do not have a logo created but this is something I am looking at doing within the next week. The icon will be used throughout different parts of my website eg. Footer. In my post I specified that I would like the icon to look something similar to the MDB icon already in the Font Awesome library. I hope this provides enough information.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
