### ISSUE TITLE
fas fa-photo-video doesn't work

### ISSUE THREAD

**Issue by NerofleLincoln** [FortAwesome/Font-Awesome#16672]
**Describe the bug**
Including `<i class="fas fa-photo-video"></i>` in the code doesn't show the icon.

**To Reproduce**
[https://www.w3schools.com/icons/tryit.asp?icon=fas_fa-photo-video&unicon=f87c](https://www.w3schools.com/icons/tryit.asp?icon=fas_fa-photo-video&unicon=f87c)

**Version and implementation**
Version: fontawesome v5.7.1
Browser and version:  Opera GX : Opera 68 on Windows 10

**Comment by tagliala** [comment]
@robmadole anyone in the team using Opera?

**Comment by robmadole** [comment]
It shows up for me on Mac with Opera 68 and through browser stack on Windows 10.

@NerofleLincoln can you provide any additional information? We can't reproduce this.

**Comment by NerofleLincoln** [comment]
Here is my code:
`<head>
    <meta charset="utf-8">
    <title>Title</title>
    <link rel="stylesheet" href="/style.css" />
    <link rel="icon" href="/img/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Hind&display=swap" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
  </head>
<body class="loggedin">
  <div class="loggedin">
    <div class="location">
      <h3>
        <a href="/accueil">OHF31 - Espace musiciens</a>
        <i class="fas fa-angle-right"></i>
        <a href="/stockage">Stockage</a>
        <i class="fas fa-angle-right"></i>
        <a href="/stockage/photos-et-videos">Photos & vidéos</a>
      </h3>
    </div>
    <div class="title">
      <div class="line">
        <i class="fas fa-photo-video"></i>
        <h1>Photos & vidéos</h1>
      </div>
      <h3><i class="fas fa-list-ul"></i>Dossiers</h3>
    </div>
    <div class="content">
      <p>content</p>
    </div>
  </div>
</body>`
For now, I use `<i class="fas fa-images"></i>` and it works. I use this structure for all my pages, so I don't know what information I can provide you.

**Comment by robmadole** [comment]
The `photo-video` icon was added in version 5.9.0. I think if you upgrade that will get you fixed up!
