### ISSUE TITLE
Icon request: fa-trailer

### ISSUE THREAD

**Issue by bertoost** [FortAwesome/Font-Awesome#16688]
**What can it be used for?**

I am working parttime as driving instructor and one of the courses we provide is driving with a trailer. There is a separated driving license for it in the Netherlands (probably in other countries as well). Many transport icons are available in FA, but I am missing this one.

**Example image (optional)**

![image](https://user-images.githubusercontent.com/398492/82534174-ff358380-9b44-11ea-9495-ade30983151d.png)

![image](https://user-images.githubusercontent.com/398492/82534272-2ee48b80-9b45-11ea-9bb4-c4f4f1d29dc3.png)

![image](https://user-images.githubusercontent.com/398492/82534311-386df380-9b45-11ea-8eb8-08e63bd50e8b.png)

I'd prefer a "closed" trailer, without windows and straight forward.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi @bertoost , we have two types of trailers already implemented, just make sure that you are using FA >= 5.12.0:

- https://fontawesome.com/icons/caravan?style=solid
- https://fontawesome.com/icons/trailer?style=solid

**Comment by bertoost** [comment]
Oh damn.. I just was one version behind 🙈 nice catch!
Now waiting on the moped... https://github.com/FortAwesome/Font-Awesome/issues/6897
