### ISSUE TITLE
Update Linode Brand Logo to Newest Version

### ISSUE THREAD

**Issue by mdonaberger** [FortAwesome/Font-Awesome#16692]
**Describe the bug**
The `Linode` logo in the Brands is an old version – I am the Art Director at Linode, so this is hot off the presses. :-)

**To Reproduce**
https://fontawesome.com/icons/linode?style=brands

**Expected behavior**
https://fontawesome.com/icons/linode?style=brands

**Screenshots**
The following are the new ones:
https://us-east-1.linodeobjects.com/lin-creative/Temp/1c-linode-logo-black.svg
https://us-east-1.linodeobjects.com/lin-creative/Temp/linode-logo-square-rgb.svg

**Version and implementation**
Version: 
Browser and version: 

- [X] SVG with JS
- [X] Web Fonts with CSS
- [X] SVG Sprites
- [X] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up!

I've assigned @sensibleworld

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
