### ISSUE TITLE
Icon request: fa-football

### ISSUE THREAD

**Issue by ayoubkhan558** [FortAwesome/Font-Awesome#16698]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/20210961/82663496-368d5880-9c49-11ea-9e22-ff8e210a4b4d.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as [fa-futbol](https://fontawesome.com/icons/futbol?style=solid)

Hope it helps

closing here
