### ISSUE TITLE
Icon request: fa-sports-cricket

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [FortAwesome/Font-Awesome#16700]
**What can it be used for?**
It  can be used in sports apps

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/20210961/82663601-66d4f700-9c49-11ea-8dd9-0b55da4b7609.png)
![image](https://user-images.githubusercontent.com/20210961/82663663-8c620080-9c49-11ea-81b0-36f352e959dd.png)
![image](https://user-images.githubusercontent.com/20210961/82663702-9e43a380-9c49-11ea-8898-77f50d56116f.png)
![image](https://user-images.githubusercontent.com/20210961/82663724-aac7fc00-9c49-11ea-8f08-11292fe1ee4a.png)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does #5706 fit also this use case?

**Comment by ayoubkhan558** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Does #5706 fit also this use case?

I think its better to create a cricket instead of creating separate icons bat, wickets, ball etc.

**Comment by aethior** [comment]
Hi @ayoubkhan558-zz,

This icon was added in v5.0.5.
Check https://fontawesome.com/icons/cricket-bat-ball

Regards.

cc/ @tagliala
