### ISSUE TITLE
Broken search results

### ISSUE THREAD

**Issue by damianogui** [FortAwesome/Font-Awesome#16707]
When I search an icon from the website by writing a search term, the right results appear and then are immediately replaced by other, less relevant results. This happens all the time and it's extremely frustrating since I use your website search feature all the time to look for the icons I need.
(Chrome 74.0.3729.169 on Mac OS Catalina 10.15.4)
Pleas fix it and anyway, lots of love and keep up your awesome work!

**Comment by tagliala** [comment]
Ciao!

Thanks for being part of the Font Awesome Community.

We know about this issue, it has been already reported in #16421

Let's continue there
