### ISSUE TITLE
Icon request: blocks

### ISSUE THREAD

**Issue by gezakerecsenyi** [FortAwesome/Font-Awesome#16722]
**What can it be used for?**
The idea for this icon is to represent blocks like those in Blockly, or other click-and-drag coding packages. This icon could be used on navigation pages on websites employing Blockly, as well as to represent different types/levels of coding in lots of places (even when not necessarily using the Blockly library in particular, it could be used to represent simple programming for younger audiences)

**Example image (optional)**
Incredibly roughly, something like:
![fa-blocks](https://user-images.githubusercontent.com/32415108/82906355-07365e80-9f5d-11ea-89ad-d9a8dfee5b70.png)

Or something like:
![block2](https://user-images.githubusercontent.com/32415108/82906733-90e62c00-9f5d-11ea-9cea-04297571b9cf.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/puzzle-piece?style=solid fit your use case?

**Comment by gezakerecsenyi** [comment]
Thank you for the response.

I suppose that the fa-puzzle-piece does work for most use cases, and I have been able to use it previously in my code, along with fa-code in some cases. However, I'm not sure if it could always work in all contexts.
