### ISSUE TITLE
Free icons aren't loading

### ISSUE THREAD

**Issue by ellentk** [FortAwesome/Font-Awesome#16724]
Hello, I'm trying to use some of the free FA icons for a non-profit site I'm working on and the freebies aren't working. Examples: fa-truck, fa-car-alt, fa-store and a slew of others I tried. 
Can you test these? Seems like they are supposed to be free https://fontawesome.com/icons?d=gallery&m=free  I'm using it as part of the ListingsPro theme...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I'm using it as part of the ListingsPro theme...

Sorry, we do not provide support for third party plugins/themes/libraries.

From the description of the problem, I guess that your website is using an old version of Font Awesome. The icon you mentioned, per se, do not have issues.

Demo: https://jsfiddle.net/tagliala/42meju9o/25/

We also have an official plugin for WordPress: https://github.com/FortAwesome/wordpress-fontawesome

Docs: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress

If you think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Closing here, but feel free to comment
