### ISSUE TITLE
Icon request: GitLab icon update

### ISSUE THREAD

**Issue by mocha** [FortAwesome/Font-Awesome#16727]
**What can it be used for?**
There is currently a GitLab icon in [FontAwesome](https://fontawesome.com/icons/gitlab) but it isn't the official outline logo. It should get updated to the official one!

**Example image (optional)**
[![Screenshot from Gyazo](https://gyazo.com/4551869f41c9cb476f4696cbd4f03ba4/raw)](https://gyazo.com/4551869f41c9cb476f4696cbd4f03ba4)

Available in the press kit here: 

- https://about.gitlab.com/press/press-kit/
- https://about.gitlab.com/images/press/logo/svg/gitlab-icon-1-color-black-rgb.svg

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by mocha** [comment]
I'm the Product Manager for the [GitLab Design System](https://design.gitlab.com/) -- feel free to reach out if I can help further!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this!

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This is available in the latest alpha release of v6.
