### ISSUE TITLE
Icon request: google icon(multicolor)

### ISSUE THREAD

**Issue by jaybhoyar** [FortAwesome/Font-Awesome#16725]
**What can it be used for?**
Can be used in OAuth buttons on web portals.

**Example image (optional)**

![google-96](https://user-images.githubusercontent.com/41126433/83031701-848fcb00-a052-11ea-89b2-5fcf0c181128.png)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Sorry, this is out of scope at the moment

There is a request for duotone brands at #16060

Closing here (for the moment)
