### ISSUE TITLE
Need help figuring out inside/outside paths

### ISSUE THREAD

**Issue by felixmariotto** [FortAwesome/Font-Awesome#16746]
Hi,

I want to improve support for Font-Awesome icons in [three.js](https://github.com/mrdoob/three.js/), and in particular in this [VR user interface add-on](https://github.com/felixmariotto/three-mesh-ui), because I'm struggling with holes. I understand that the default way of determining if a path is a hole, is [according to MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule) by : 

> drawing a ray from that point to infinity in any direction, and then examining the places where a segment of the shape crosses the ray. Starting with a count of zero, add one each time a path segment crosses the ray from left to right and subtract one each time a path segment crosses the ray from right to left. After counting the crossings, if the result is zero then the point is outside the path. Otherwise, it is inside.

That's what three.js does, it considers that paths should be clockwise and holes counterclockwise.

However when I try to load [this Font-Awesome icon](https://fontawesome.com/icons/backspace?style=solid) in three.js, I get this : 
![aa](https://user-images.githubusercontent.com/46470486/83329181-4da2fa80-a288-11ea-9898-b44f592e2187.jpg)

Which is the reverse of the expected result.
When I reverse the inside/outside detection algorithm, I get the expected result.

My question is, are you consistently doing paths clockwise and holes counterclockwise ? If not, how does the browser determine where are the holes, even without `fill-rule` attribute, [like in this pen ?](https://codepen.io/felixmariotto/pen/abveLBy)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I do not know the answer, but we can ask @sensibleworld that is actually designing icons if he has an answer
