### ISSUE TITLE
Select font weight on Windows Form and Font Awesome

### ISSUE THREAD

**Issue by TheYashe** [FortAwesome/Font-Awesome#16748]
There are 2 icons with name "Square". One of them is full, and another is empty.
I can't get this one which i wanted to have in my project.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> There are 2 icons with name "Square"

That's correct and expected.

In FA 5 Free, we have:
- `fas fa-square`, which is a square in solid (`fas`) style. This is the filled-in square.
- `far fa-square`, which is a square in regular (`far`) style. This is the outline square.

You need to switch the style (fas / far) to select the icon you need

Please refer to: 
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

If your question is related to pseudo elements, please refer to:
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here, but feel free to comment

**Comment by TheYashe** [comment]
I cant find any information about how to implement this "style" in my .NET (Windows Forms). What I can do is type: 
`"this.maxButton.IconChar = FontAwesome.Sharp.IconChar.Square;"`

and nothing more. Do I missing something ?

**Comment by tagliala** [comment]
Hi, 

>  .NET (Windows Forms)

Are you using the OTF files on desktop?

In this case, you should change the font weight from 900 to 400 (it is the same approach of pseudoelements). Please also note that Regular and Solid are two different font giles

Ref:

- https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-glyphs#styles

**Comment by TheYashe** [comment]
In properties window I couldn't find any weight of font. [(ref)](https://i.imgur.com/MHeJuQs.png)
Maybe it's not even possible in Window Forms project to have other style icons.

Thanks for your time anyway :)

**Comment by tagliala** [comment]
I'm going to reopen here and wait for feedback from the community, since this is related to .NET and Windows Forms

**Comment by tagliala** [comment]
Sorry, closing here.

Since there are two different fonts for Regular and Solid, please install both of them and select the proper Font and Style accordingly. Bold should be false in both cases

User Solid:
![image](https://user-images.githubusercontent.com/556268/83353802-249c6b80-a355-11ea-811b-cd8e9b313222.png)


User Regular:
![image](https://user-images.githubusercontent.com/556268/83353746-059dd980-a355-11ea-9206-8ff8c01ebaa3.png)


Note: I do not know how Font Embedding works in C# distributable applications
