### ISSUE TITLE
How to submit new Icons.

### ISSUE THREAD

**Issue by hiteshpatwari** [FortAwesome/Font-Awesome#1674]
Hey guys,

Me and my team were working on a project, which led us to create new Icons for our needs, we are very happy with Font-Awesome and would like to contribute to the open-source community as a token of appreciation. Can you guide us through the process, How can I submit new Icons ? Not the New- Icon request. @davegandy

**Comment by sgtpep** [comment]
Imho icons should be represented in repository as individual svg files and compiled to font files using tools like font-builder https://github.com/fontello/font-builder. So one icon = one plain-text svg file, easily manageable using git.
