### ISSUE TITLE
Icon request: user-manual or instruction-manual (book with hand)

### ISSUE THREAD

**Issue by NiklasO** [FortAwesome/Font-Awesome#16750]
**What can it be used for?**
As an button/link to an user manual or instructions manual. For example indicate a downloadable user manual  (not support or help).

**Example image (optional)**
The following images are examples that I think would work well.
[Example 1](https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Funiversity-set-4%2F512%2F18-512.png&imgrefurl=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F732381%2Fbook_learning_manual_pointer_finger_reading_textbook_icon&tbnid=1JY9lfUa9KnpsM&vet=12ahUKEwjeptKAz9jpAhXRsyoKHUaZC7oQMygAegUIARCIAg..i&docid=rtbUmctxQ6LznM&w=512&h=512&q=icon%20for%20manual&client=firefox-b-d&ved=2ahUKEwjeptKAz9jpAhXRsyoKHUaZC7oQMygAegUIARCIAg#h=512&imgdii=6xqXBqTPRU6cnM:&vet=12ahUKEwjeptKAz9jpAhXRsyoKHUaZC7oQMygAegUIARCIAg..i&w=512)

[Example 2](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg.icons8.com%2Fall%2F500%2Fuser-manual.png&imgrefurl=https%3A%2F%2Ficons8.com%2Ficon%2F20319%2Fuser-manual&tbnid=DUlVqzFD0OC4QM&vet=12ahUKEwjeptKAz9jpAhXRsyoKHUaZC7oQMygDegUIARCQAg..i&docid=VKlhbTHS81D2RM&w=500&h=500&q=icon%20for%20manual&client=firefox-b-d&ved=2ahUKEwjeptKAz9jpAhXRsyoKHUaZC7oQMygDegUIARCQAg)

**Icon request checklist**
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
