### ISSUE TITLE
Icon request: icon-gas-pump (icon-fuel, icon-petrol)

### ISSUE THREAD

**Issue by FadhelChaabane** [FortAwesome/Font-Awesome#1676]
Hello all,
 It would be very useful if you can add a gas pump icon. it would be used when tagginf Fuel stations etc... on maps.

Thank you very much,

![gas-pump](https://f.cloud.github.com/assets/686884/878241/1d52490e-f90b-11e2-899c-a178af0a8295.png)

**Comment by Yahtze** [comment]
+1

**Comment by thefeldkircher** [comment]
+1

**Comment by gca88** [comment]
+1

**Comment by ndickiso** [comment]
+1

**Comment by pvtai** [comment]
+1

**Comment by pvtai** [comment]
When we will have this icon?
Thanks

**Comment by eddiegichuhi** [comment]
+1

**Comment by sweco-sehrbe** [comment]
+1

**Comment by sweco-seajaa** [comment]
+1

**Comment by haferje** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by saqueib** [comment]
+1

**Comment by robholmes** [comment]
+1

**Comment by EduardoRMello** [comment]
+1

**Comment by SoullessSentinel** [comment]
+1

**Comment by WispProxy** [comment]
+1
=)

**Comment by peterjford** [comment]
+1

**Comment by tspec1** [comment]
+1

**Comment by abdelrahman-elkady** [comment]
+1 :wink:

**Comment by mastermind1981** [comment]
:+1:

**Comment by mastermind1981** [comment]
+1

**Comment by dosjota** [comment]
+1

**Comment by eric55** [comment]
+1

**Comment by iweindesmedt** [comment]
+1

**Comment by kosuhin-lexa** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by raphjutras** [comment]
+1

**Comment by fducharme** [comment]
+1

**Comment by ik0** [comment]
+1

**Comment by stanleywym** [comment]
+1

**Comment by tylerchilds** [comment]
+1

**Comment by bvodola** [comment]
+1

**Comment by n0ne** [comment]
+1

**Comment by Browne** [comment]
+1

**Comment by kmengvik** [comment]
+1

**Comment by infrazfull** [comment]
+1

**Comment by AAAnderson7301** [comment]
+ 1

**Comment by G-Driver** [comment]
+1

**Comment by Izopi4a** [comment]
+1

**Comment by BabyDino** [comment]
+1

**Comment by Dibort** [comment]
+1

**Comment by a-ivanov81** [comment]
+1

**Comment by alihassan0** [comment]
+1

**Comment by janxb** [comment]
+1

**Comment by ebrake** [comment]
+1

**Comment by kmengvik** [comment]
I think it is useless to request icons through this thread. The fuelfump icon has been requested for three years now, and is still missing. How hard can it be to add it, and why is such obvious icon not included from the beginning???

**Comment by aloverso** [comment]
+1

**Comment by Yourney** [comment]
+1

**Comment by Yourney** [comment]
This request has been open for almost 3 years.
This request has over 65 '+1' remarks.
Please add it?

**Comment by ezaNU** [comment]
+1

**Comment by alexandrustefan** [comment]
+1

**Comment by andgonza** [comment]
+1

**Comment by LostInBrittany** [comment]
+1

Could be please get some feedback from developers? After three years, even if it is only a *we won't do it*, but at least say something...

**Comment by stud3nt3** [comment]
+1

**Comment by kojimairiguchi** [comment]
+1

**Comment by odiego** [comment]
+1
3 years now, and still no gas pump =/

**Comment by flyswatter** [comment]
+1!!  How many upvotes is enough?

**Comment by kumavis** [comment]
+1
![pumpin that gas](https://media.giphy.com/media/gV8YI8qMzZYKA/giphy.gif)

**Comment by kfreezen** [comment]
+1

**Comment by pekastel** [comment]
+1

**Comment by meterlongcat** [comment]
+1

**Comment by kalligator** [comment]
+1

**Comment by ryanskidmore** [comment]
+1

**Comment by andrecavallari** [comment]
+1

**Comment by giovannibenussi** [comment]
+1

**Comment by andrewthong** [comment]
Been lurking this thread for awhile now, figure I'd +1 in vain too.

But seriously, this would be a great addition to the "transportation" or "map" grouping in FA. I'd settle for a fuel gauge, but the pump station is readily recognizable.

**Comment by Yourney** [comment]
Jul 30, 2013 · 86 comments
I have abandoned ship to the competition: https://design.google.com/icons/
They have fuel pump and even electric car charge station!

**Comment by zerochka** [comment]
+1

**Comment by Sharj** [comment]
+1

**Comment by alvarohoro** [comment]
+1

**Comment by Crissov** [comment]
⛽️ [U+26FD](http://emojipedia.org/fuel-pump/) Unicode character #222

**Comment by felixcheruiyot** [comment]
Any plan to have this settled soon?

**Comment by Yourney** [comment]
The initial request is from Jul 30, 2013.
Draw your own conclusions :-(
Wouter

**Comment by Yourney** [comment]
Dunno how to make your own icon.
I have switched to the font family you mention.

**Comment by markartim** [comment]
+1

**Comment by jouanc** [comment]
+1

**Comment by leoaccorsi** [comment]
+1

**Comment by Yourney** [comment]
There have now been 88 +1's, so 89 people want this.
And still it is not yet implemented. :-(

**Comment by BlueTeck** [comment]
+1 ?!

**Comment by robinsonlam** [comment]
+1

**Comment by okle4ka** [comment]
+1

**Comment by chopj** [comment]
+1

**Comment by manamachado** [comment]
+1

**Comment by takdol** [comment]
+1

**Comment by johnwmcarneiro** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by MaskaZan** [comment]
+1

**Comment by jdeboer-geoplan** [comment]
+1

**Comment by Ferouk** [comment]
+1

**Comment by nicoaquin** [comment]
+1

**Comment by loginetsolutions** [comment]
+1

**Comment by jrmacks** [comment]
+1

**Comment by marlongichie** [comment]
+1

**Comment by vladimirsolovey** [comment]
+1

**Comment by visualpharm** [comment]
I've started a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The gas station icon is here](https://icons8.com/icon/18109/gas-station).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), [clean](https://github.com/FortAwesome/Font-Awesome/issues/239#issuecomment-304473340), [church](https://github.com/FortAwesome/Font-Awesome/issues/2088#issuecomment-305039560) and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by cristiangirlea** [comment]
+1

**Comment by renanmedina** [comment]
+1

**Comment by MechanicsPal** [comment]
+1 @tagliala

**Comment by Optimaximal** [comment]
+1

**Comment by geekvaibhav** [comment]
+1

**Comment by nicomorales** [comment]
+1

**Comment by chevybowtie** [comment]
+1

**Comment by fipstree** [comment]
+1

**Comment by PaznerA** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by euricovidal** [comment]
+1

**Comment by kikarodaima** [comment]
+1

**Comment by nimeshabuddhika** [comment]
+1

**Comment by edvaldoribeiro** [comment]
+1

**Comment by agil-NUBBA** [comment]
+1

**Comment by saydax** [comment]
**+1**

**Comment by ljayz** [comment]
+1

**Comment by bcingle** [comment]
+1

**Comment by joffreyroy** [comment]
+1

**Comment by thojaw** [comment]
+1

**Comment by agenciabahia** [comment]
+1

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by netAction** [comment]
After just 5 years, 120 upvotes and some large surverys about missing icons! Yeah!

**Comment by agenciabahia** [comment]
ole!

**Comment by borsn** [comment]
+1

**Comment by jackkitley** [comment]
Where is this icon?

**Comment by jackkitley** [comment]
+ 1 X 10000

**Comment by sensibleworld** [comment]
@jackkitley Icon is done, and should be available when our 5.1 release goes live.

**Comment by MaximSemenov** [comment]
+1

**Comment by sensibleworld** [comment]
We were running on empty. No longer! https://fontawesome.com/icons?d=gallery&q=pump
