### ISSUE TITLE
Icon request: keyboard-wasd

### ISSUE THREAD

**Issue by kodaline** [FortAwesome/Font-Awesome#16769]
**What can it be used for?**
In case you have some mapping on keyboard keys, such as over wasd. It would be nice to have the icons to describe the command [usage.]

**Example image (optional)**

![w](https://user-images.githubusercontent.com/9247877/83852035-7a856080-a713-11ea-8d46-dae64f6f50cb.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a basically a request for a `keyboard-letter-w`, which could open to `keyboard-letter-*`, and so ~ 400 new icons and more. So, for the moment, I'm going to close here.

If you are interested in a generic key, please upvote #14991

If you are interested in stacking letters on icons, take a look at our docs: https://fontawesome.com/how-to-use/on-the-web/styling/layering

Demo: https://jsfiddle.net/4x1zjy0e/
