### ISSUE TITLE
Icon request: codepen

### ISSUE THREAD

**Issue by amotor-AM** [FortAwesome/Font-Awesome#16762]
**What can it be used for?**
for linking my codepen.io account to my portfolio

**Example image (optional)**

![codepen](https://user-images.githubusercontent.com/66324211/83554344-782bc800-a4c1-11ea-8fe3-7adc6199787e.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by chadwithuhc** [comment]
a codepen icon exists: https://fontawesome.com/icons?d=gallery&q=codepen&s=brands

**Comment by tagliala** [comment]
Correct, codepen has been implemented in FA 5.0.0

Closing here
