### ISSUE TITLE
Icon not showing up correctly

### ISSUE THREAD

**Issue by amotor-AM** [FortAwesome/Font-Awesome#16765]
**Describe the bug**
I tried to import the icon for codepen to add it to my portfolio. I called it using the correct code 
("fab fa-codepen") and it just shows up as a broken image. I have another fontawesome icon for github right next to it so i know my website is able to connect to fontawesome. This seems like an issue specific to this ONE icon. Has anybody else had any issues with this? Pic below. Thanks!

![unnamed](https://user-images.githubusercontent.com/66324211/83572678-d7e49c00-a4de-11ea-9ee7-5765f54ed32d.png)

**Comment by amotor-AM** [comment]
LOL I literally just solved this. Fontawesome had their icon fetch parameters incorrect. the correct code should have been ("fa fa-codepen")

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Fontawesome had their icon fetch parameters incorrect. the correct code should have been ("fa fa-codepen")

`fab fa-codepen` is not a typo

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps
