### ISSUE TITLE
Not working icons

### ISSUE THREAD

**Issue by Mischa007** [FortAwesome/Font-Awesome#16795]
The icons: 

"fa-house-user"
"fa-laptop-house"

are not working and are causing the error sign "?".

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.
CSS Demo: https://jsfiddle.net/tagliala/c8eupagr/10/
SVG Demo: https://jsfiddle.net/tagliala/y693z45a/26/

Both the above icons have been introduced in FA 5.13.0, please make sure that your application is using FA 5.13.0

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
