### ISSUE TITLE
Discord icon doesn't work

### ISSUE THREAD

**Issue by KingslayerKyle** [FortAwesome/Font-Awesome#16792]
Hi,

All icons are working for me (That I have used up to yet)

Except the Discord icon, doesn't load. Just blank

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-discord](https://fontawesome.com/icons/discord?style=brands) has been introduced in Font Awesome 5.0.0, so please double check that you are using Font Awesome 5.0.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
