### ISSUE TITLE
Microsoft Icons

### ISSUE THREAD

**Issue by Australian** [FortAwesome/Font-Awesome#16797]
**What can it be used for?**
writing technical documentation
Referring to Microsoft products from websites

**Example image (optional)**
https://www.onmsft.com/wp-content/uploads/2019/07/Screenshot-2019-07-16-at-16.28.25.png

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? 

I do not recognize the application in the example

Please remember that icons for sets are not allowed, and there are already requests for all office applications at #2884 and other microsoft products #13914 #5212 #16231 

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

**Comment by forresthopkinsa** [comment]
The icon they posted is the Exchange logo

**Comment by tagliala** [comment]
Thanks. Exchange is here: #5696

**Comment by aethior** [comment]
> Thanks. Exchange has been requested here: #5696

In this case I think you can close here.
