### ISSUE TITLE
Icon request: tiktoc

### ISSUE THREAD

**Issue by connollyz** [FortAwesome/Font-Awesome#16805]
**What can it be used for?**
tiktoc social media icon

**Icon request checklist**
- [Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ tiktoc] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

- [logo ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Tiktok will be available in the next FA release. No ETA yet, sorry

Ref: #14340
