### ISSUE TITLE
Use of <i> is an accessibility issue

### ISSUE THREAD

**Issue by kdmarks** [FortAwesome/Font-Awesome#16807]
Hi! Automated accessibility checkers (like Wave, Siteimprove, etc.) will mark every instance of `<i>` elements as a compliance issue with [WCAG 1.3.1 Info and Relationships Level A](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#info-and-relationships)--for not separating presentation from content. We have to change the `<i>` elements to `<span>` elements to achieve compliance. Really wish FontAwesome used  `<span>` elements out of the box.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please follow the discussion at #16790
