### ISSUE TITLE
Font Awesome Kit CSS randomly disappears on Safari iOS

### ISSUE THREAD

**Issue by webwiz** [FortAwesome/Font-Awesome#16802]
I'm using Font Awesome 5 Free via a kit.  On desktop, the icons work perfectly.  But on mobile (iOS chrome (normal and incognito), iOS firefox focus, iOS safari), they behave like Schrödinger's cats...

On first page load, the icons appear.  Tap reload and they disappear and are replaced by small squares.  Tap reload _**again**_ and they **_re_**appear.  Every _**other**_ tap of reload shows or hides the icons.

I notice the same behavior if I toggle back and forth between "request desktop site" and "request mobile site".  (I'm not sure what's really going on under the hood there since the page renders the same either way.)

Since they do appear correctly, at least part of the time, I don't think it's a cross-origin problem or a caching problem.

An example page is here: https://onlinesafetyzone.com/learn/learning-zone.php

I've read many posts, here and on stackoverflow and none of the solutions has worked.  Anyone have a clue what's going on?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any chance to provide a reduced test case without other javascript / css / third party libraries?

**Comment by webwiz** [comment]
@tagliala Thanks for making me think about debugging differently!  I cloned a web page, commented out all css and js references, and then added them back one-by-one until the Font Awesome icons broke.  This helped me narrow down the problem to one css file and one js file.  But this was a red herring.

I remembered that last week, I switched from referencing Bootstrap (css and js) and jQuery (js) files from local copies to CDNs.  When I switched back to the local versions in my "cloned" page, the FA icons began behaving correctly and consistently.

So there must be something in the CDN versions that's messing things up.  I'm OK (I think) with just reverting back to my local copies.  (I had switched to CDNs for better performance, but now I'm also using Cloudflare, so I'm probably getting equally good performance due to their caching.)

I noticed, though, that my local files are much older than the CDN versions:
bootstrap.min.css: CDN is v4.5.0, my local is 4.2.1
bootstrap.min.js: CDN is 4.5.0, my local is 4.2.1
jQuery.min.js: CDN is 3.5.1, my local is 1.12.4

I'm hoping the older local versions isn't going to cause compatibility or other issues in the future!

**Comment by tagliala** [comment]
Hi, welcome

> bootstrap.min.css: CDN is v4.5.0, my local is 4.2.1
bootstrap.min.js: CDN is 4.5.0, my local is 4.2.1
jQuery.min.js: CDN is 3.5.1, my local is 1.12.4

I think that the above libraries are not a problem

We are aware of some random issues with iOS and Safari due some memory-related and/or cache-related issues.

Ref: https://github.com/FortAwesome/Font-Awesome/issues/7770#issuecomment-504114161

**Comment by webwiz** [comment]
Yes, after more debugging, I now agree that the Bootstrap / jQuery thing has nothing to do with the problem.

I tried downloading the "fontawesome-free-5.13.0-web" zip file, uploading the files to my server, and referencing "all.css" and "all.js" directly from my server.  In this configuration, everything worked fine, on desktop and mobile, and even through multiple refreshes.

So there must be something going wrong with the remote server references to either the Font Awesome javascript kit or the files on BootstrapCDN.  Furthermore, the mobile browsers must be doing something different from desktop browsers (other than just sending a different user-agent string).  It's very odd that it breaks consistently every other time on mobile, almost as if I'm flipping between two remote servers - one with the assets and one without them.

**Comment by tagliala** [comment]
Closing here in favor of #7770

Let's use a single thread for safari iOS random issues
