### ISSUE TITLE
Create an icon pack related to the fire department

### ISSUE THREAD

**Issue by cassiompf** [FortAwesome/Font-Awesome#16801]
I'm making a website for the fire department in my city and I wanted to give you a suggestion to create an icon pack related to the fire department. I don't want you to do it thinking you're going to do it just because I want to. I want you to do this to help the whole community that needs it too and is looking for it in various places!

Some icons:

- Fire brigade truck
- Hydrants (Most wanted)
- Fire Department Hat
- Fire brigade person
- Fire extinguisher
- among others...

Thanks :D

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have some individual requests for fire department related icons, please upvote those

#4813 
#5738 
#4810

Contributing guidelines do not allow requests for set in the free repository, they are hard to maintain and implement. 

Font Awesome Pro customers may request icon sets in the Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Closing here

Ref: [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
