### ISSUE TITLE
Icon Request: icon-pickaxe

### ISSUE THREAD

**Issue by payne8** [FortAwesome/Font-Awesome#1680]
Hey I love using the font awesome icons! I am making a CRM for my work and would love to have a pickaxe to represent Prospects. A quick google image search for pickaxe has plenty of examples that would be simple yet recognizable. Thanks!

**Comment by lucasmartins** [comment]
How can I add this myself to font-awesome? I've read the [Submitting Pull Requests](https://fortawesome.github.io/Font-Awesome/community/) instructions and it says not to send any new icons.

If I make the SVG will anybody add it to the font?

**Comment by lucasmartins** [comment]
Just referencing (I think both are kinda related): https://github.com/FortAwesome/Font-Awesome/issues/2442

**Comment by lucasmartins** [comment]
If you need a workaround, check the [Noun Project](https://thenounproject.com/term/pickaxe/1015)

**Comment by andygrodecki** [comment]
+1
Hiyah - I am new to GitHub - not familiar with the lingo. We use FA on our website qld.gov.au/sciencedirectory  I specifically after a 'mining' icon such as icon-pickaxe (mining) - has one been created?

**Comment by JDiPierro** [comment]
+1

**Comment by Beej126** [comment]
+1

**Comment by Wmeng98** [comment]
+1 - Was anyone able to find a solution to this yet?

**Comment by joeleoli** [comment]
7 years later, no update 🥇

**Comment by payne8** [comment]
Yeah no update on this. I've had three different jobs since I originally posted this. For one of my projects we created our own icon font so we could easily pull in icons from our designers.

The noun project is also excellent but you either pay for the icons you want to use or a subscription (I think).
There are also ways of pulling SVGs into your markup. Most stock photo sites also sell vector images you can convert to SVGs pretty easy which makes it possible to use any icon you want.

Font awesome is great for most use cases but if you need a specific icon they don't already have, I found it easier to go a different route.

**Comment by andygrodecki** [comment]
7 years on I can’t recall why I asked! :) Thanks for your replies anyway

Regards

Andy Grodecki
[Sent while away from my desk]
Senior Project Officer [Mon, Tues, Wed & Fri only | Thurs > study/project day]
Science Partnerships and Development | Science and Technology | Department of Environment and Science
__________________________________
07 3170 5759 | 0411 361 044 | andy.grodecki@qld.gov.au
Web: qld.gov.au/science | Facebook: QldScience | Twitter: QldScience
________________________________

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
⛏ [U+26CF](https://emojipedia.org/emoji/%E2%9B%8F/) Pick
Also known as `Pickaxe`.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pickaxe?s=solid&f=classic
