### ISSUE TITLE
Background image not showing in 5.13.1

### ISSUE THREAD

**Issue by tal3nce** [FortAwesome/Font-Awesome#16811]
Hi, I updated from 5.13.0 to 5.13.1 and my background image on home page ("banner") didn't show after compiling my assets - it just showed a black background instead of the image. When I reverted to 5.13.0 the image was there again.

Here's a very simple example of the section where the bug happened, nothing fancy here (I use Laravel, Tailwind and Vue):
https://codepen.io/tal3nce/pen/MWKJjbB
Please let me know if you'd like me to insert entire HTML, or this section is sufficient.

The image IS loaded, I checked the network tab, it's there. When I manually navigate to the url in the backgorund-image: url() it is there. Actually, nothing in this section was changed, as mentioned, it worked in 5.13.0

**Version and implementation**
Version: 5.13.1
Browser and version: Chrome 83.0.4103.106 (Official Build) (64-bit)
Tried in Edge as well, didn't check Opera, FF etc.

Thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Please let me know if you'd like me to insert entire HTML, or this section is sufficient.

Thanks, but that doesn't help

Please provide a full reproducible test case. A link to your website (if it is broken) could be useful

**Comment by tal3nce** [comment]
Hi. Sorry, I updated a few things that day, including some node dependencies. It was one of them that was the culprit, sorry.
