### ISSUE TITLE
Tripadvisor icon does not render properly in CSS

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#16817]
**Describe the bug**
The newly update tripadvisor icon does not render properly in CSS

**To Reproduce**
5.13.1 CSS: https://jsfiddle.net/tagliala/pw94dbvc/

(SVG not affected: https://jsfiddle.net/tagliala/58v2yjfd/2/)

**Expected behavior**
Renders correctly

**Screenshots**
https://fontawesome.com/icons?d=gallery&q=tripadvisor
![image](https://user-images.githubusercontent.com/556268/85181716-e70d6d00-b286-11ea-8401-2cac8f38d5f4.png)

**Version and implementation**
Version: 5.13.1 CSS
Browser and version: Chrome/Edge/Firefox Windows 10

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Ref: #16249 16249

**Comment by akidaniel** [comment]
Not any solution yet? ☹️

![Screenshot_20200711_193655_com android chrome](https://user-images.githubusercontent.com/21230497/87230722-098c3500-c3b2-11ea-975b-1e5d6fe3743a.jpg)

**Comment by robmadole** [comment]
I can confirm we've got this fixed in the build system. This will go out today with 5.14.0.

**Comment by tagliala** [comment]
Confirm fixed in 5.14.0 https://jsfiddle.net/tagliala/pw94dbvc/8/
