### ISSUE TITLE
Subsetter does not open project files from previous version(s)

### ISSUE THREAD

**Issue by morpolspc** [FortAwesome/Font-Awesome#16818]
The subsetter does not open saved *.yaml project files from a previous version that were saved.

The simple solution is to open your project file and change the version number to the current (5.13.0 to 5.13.1 for example), save it, and then it can be opened with the new subsetter version.

This does seem like an oversight to me though.  You release a new version and any project created with the versions before no longer load without manual manipulation to the file?  Really?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please open this issue in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

You can also send an email to hello@fontawesome.com

Closing here (this is the repository for the free icon set)
