### ISSUE TITLE
Icon request: encrypt decrypt icon

### ISSUE THREAD

**Issue by jackthegooner** [FortAwesome/Font-Awesome#16819]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that

- https://fontawesome.com/icons/lock?style=solid
- https://fontawesome.com/icons/unlock?style=solid 

fit the use case described in the title.

You may be interested in #14627, but please note that you can achieve this icon by taking advantage of the svg framework

Demo: https://jsfiddle.net/tagliala/z12wdapb/46/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
