### ISSUE TITLE
paper-plane missing

### ISSUE THREAD

**Issue by joeyre** [FortAwesome/Font-Awesome#16814]
Searched for 'email' icons, clicked on paper-plane and it says the icon doesn't exist

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We had some issues with search today, but at the moment I'm not able to replicate the issue with `paper-plane`

I did your steps

1. Search for `email`
2. Click on `paper-plane`

Correctly landed on https://fontawesome.com/icons/paper-plane?style=solid

Could you please retry?

If you still have issues, could you please paste the URL which says that the icon does not exist?
