### ISSUE TITLE
phone-alt not working using stylesheet, not scripts

### ISSUE THREAD

**Issue by lindenism** [FortAwesome/Font-Awesome#16825]
<i class="fal fa-phone-alt"></i>

This shows a square. I have stylesheet all.css and web fonts all updated to latest version.

**Comment by lindenism** [comment]
https://fontawesome.com/icons/phone-alt?style=light
< i class="fal fa-phone-alt" > < / i >

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.
CSS Demo: https://jsfiddle.net/tagliala/ex25p3rq/16/
SVG Demo: https://jsfiddle.net/tagliala/58v2yjfd/4/

[phone-alt](https://fontawesome.com/icons/phone-alt?style=light) has been introduced in Font Awesome 5.10.2, so please double check that you are using Font Awesome 5.10.2 or newer versions

> `< i class="fal fa-phone-alt" > < / i >`

Light style is only available in Font Awesome Pro, please make sure that you are using Font Awesome Pro 5.10.2

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
