### ISSUE TITLE
Symbol € 

### ISSUE THREAD

**Issue by carabao72** [FortAwesome/Font-Awesome#16822]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
The same symbols but in EURO €

**Example image (optional)**
Insert the example image here if necessary.

https://fontawesome.com/icons?d=gallery&q=dollard

Thank You

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Euro symbol is already available: https://fontawesome.com/icons/euro-sign?style=solid

Please make sure that you are using a supported version of Font Awesome

Hope it helps

Closing here

**Comment by carabao72** [comment]
Yes for the EURO symbol not for the other icons with the € symbol

**Comment by tagliala** [comment]
@carabao72 thanks for the clarification

@sensibleworld there are several requests about adding existing currency variations to all dollar icons.

This request covers about ~ 70 new icons, but there are some others about subsets or individual variations of icons with a dollar (couple of recent examples: #16821, #15848)

What do you suggest?
