### ISSUE TITLE
Shoe-prints icon has disappeared 

### ISSUE THREAD

**Issue by Nancyjaycollins** [FortAwesome/Font-Awesome#16828]
The shoe-prints icon is visible in the search results but is not accessible

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please retry?

I'm not experiencing issues at the moment https://fontawesome.com/icons/shoe-prints?style=solid

**Comment by robmadole** [comment]
Hmm, do we have any more information on it?

**Comment by tagliala** [comment]
Nope, sorry, but sometimes it appears that the icon detail page does not show

Ref:
- #16814
- #16835

This kind of reports started up recently. I thought you may have some information on the website log

**Comment by talbs** [comment]
We haven't seen any recent issues with this and things seem to be resolved now. I'm going to close this issue, but please let us know if things still seem off.
