### ISSUE TITLE
Icon request: icon-rupiah

### ISSUE THREAD

**Issue by realodix** [FortAwesome/Font-Awesome#1683]
Please add icon-rupiah to currency icon.
The rupiah (Rp) is the official currency of Indonesia.

**Comment by garpepi** [comment]
+1 to Indonesian Rupiah

**Comment by idmahardika** [comment]
+1 to Indonesian Rupiah

**Comment by shirone** [comment]
+1 to Indonesian Rupiah

**Comment by timpamungkas** [comment]
+1 for indonesian rupiah

**Comment by shcode** [comment]
+1 for this

**Comment by bayu41** [comment]
+1 for indonesian rupiah

**Comment by morphdhitia** [comment]
+1 for Indonesian rupiah

**Comment by edwinkun** [comment]
+1 for Indonesian rupiah

**Comment by husenEF** [comment]
+1 for Indonesian rupiah

**Comment by shinoby11** [comment]
+1 for Indonesian rupiah

**Comment by cahkaibon** [comment]
+1 for Indonesian rupiah

**Comment by sektonic** [comment]
+1 for Indonesian rupiah

**Comment by mrhabibie** [comment]
+1 for Indonesian Rupiah

**Comment by lutfiidham** [comment]
+1 for Indonesian Rupiah

**Comment by derit** [comment]
1 for Indonesian Rupiah

**Comment by Rukaan** [comment]
+1 for Rupiah

**Comment by tatataufik** [comment]
+1 for Rupiah

**Comment by Va1iant** [comment]
+1 for Rupiah

**Comment by renofizaldy** [comment]
+1 for Rupiah

**Comment by dwikodit** [comment]
+1 for Rupiah, ok

**Comment by fendiseptiawan0709** [comment]
+1 for Rupiah

**Comment by Arisdolanan** [comment]
Indonesian Rupiah

**Comment by ferluk** [comment]
+1 for Rupiah

**Comment by magrumadha** [comment]
+1 for Indonesian rupiah

**Comment by naufaldi** [comment]
+1 for Indonesia rupiah currency

**Comment by dediardiansyah** [comment]
+! for Indonesia Rupiah currency

**Comment by mimbar** [comment]
I love Indonesia Rupiah Icon

+1

**Comment by hscstudio** [comment]
I love too

**Comment by virbo** [comment]
+1 for Rupiah currency

**Comment by sheillendra** [comment]
+1

**Comment by erycamel** [comment]
+1

**Comment by cahyasatya77** [comment]
+1

**Comment by randyviandaputra** [comment]
+1

**Comment by yhoyoex** [comment]
+1

**Comment by misbahartra** [comment]
+1

**Comment by kaboel** [comment]
+1

**Comment by jeffnst** [comment]
+1 for fa-rupiah

**Comment by waqid** [comment]
+1 for rupiah

**Comment by H29id** [comment]
+1 for Rupiah

**Comment by retinationdev** [comment]
Let's make rupiah icon become real

**Comment by sunardo** [comment]
+1 for Rupiah

**Comment by butirpadi** [comment]
It's been 6 years, but there is still no solution.

**Comment by fathur** [comment]
need this, any progress?

**Comment by sensibleworld** [comment]
Yup! It'll be coming as part of Font Awesome 6

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
