### ISSUE TITLE
where is the minus circle?

### ISSUE THREAD

**Issue by parikshit223933** [FortAwesome/Font-Awesome#16833]
Where is the minus circle in font-awesome  6? It was really useful.
![image](https://user-images.githubusercontent.com/47470038/85646706-4b329580-b6ba-11ea-87c8-82d533ee50db.png)

**Comment by aethior** [comment]
Now is `fa-circle-minus`. ;)
Check https://fontawesome.com/v6/icons/circle-minus

cc/ @tagliala
