### ISSUE TITLE
Icon request: FriendBros

### ISSUE THREAD

**Issue by friendbros** [FortAwesome/Font-Awesome#16846]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details about this brand?

**Comment by hamza-potter** [comment]
It's an Information developing information technology company.

**Comment by tagliala** [comment]
Hi, please provide more details:

1. Official website
2. How other developers can use this brand if it included in Font Awesome core
