### ISSUE TITLE
Instagram-square icon appearing like some chinese text

### ISSUE THREAD

**Issue by akashrwx** [FortAwesome/Font-Awesome#16842]
Hi,

I am using the font awesome 5.13.1 and the Instagram-square icon is appearing like a Chinese text. Unicode and glyph everything is showing the same icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Web or Desktop?

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by akashrwx** [comment]
Sure I have filled it.

https://github.com/FortAwesome/Font-Awesome/issues/16844
