### ISSUE TITLE
Font Awesome Pro 5.13.1 instagram-square icon webfont appearing like chinese text

### ISSUE THREAD

**Issue by akashrwx** [FortAwesome/Font-Awesome#16844]
**Describe the bug**
Font Awesome Pro 5.13.1 Webfont fa-instagram-square icon appearing like Chinese text

**To Reproduce**
https://fontawesome.com/icons/instagram-square?style=brands

Just copy the Unicode glyph or code and it will appear like Chinese text 

![font-awesome-bug](https://user-images.githubusercontent.com/40183051/85940433-0026b580-b93a-11ea-877d-515bdb35f114.png)

**Comment by tagliala** [comment]
Thanks for filling out the bug report

Could you please provide a link to your website or a reproducible test case?
