### ISSUE TITLE
Extra styling: fab fa-teamspeak / fab fa-discord

### ISSUE THREAD

**Issue by HerrSammyDE** [FortAwesome/Font-Awesome#16843]
**Describe the bug**
There are too few style fonts for this icon

**Version**
5.13.1

**Please add these stylefonts**
- fad, far, fas, fal

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

**Comment by HerrSammyDE** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Could you please clarify this request?

Hi, I would like to have several style fonts to choose from for these 2 icons.

**Comment by tagliala** [comment]
Teamspeak and discord are brands. 

We do our best to follow brand guidelines, so we are implementing brands as they are without any modification. 

Could you please clarify:
- the use case 
- how the brands in different style should look like
- why just those two brands

References:
- https://discord.com/branding
- https://www.teamspeak.com/tr/more/media-pack/
