### ISSUE TITLE
Fake News: Facts categorized as Fiction

### ISSUE THREAD

**Issue by TacticalCode** [FortAwesome/Font-Awesome#16847]
**Describe the bug**
Various icons categorized as "Science **Fiction**" are not fictional at all, since they are well-understood real-world objects or depictions of concepts according to science's current understanding.

The following icons are incorrectly labeled "ficticious" despite the fact that they depict real objects/concepts:

- `atom*`
- `comet`
- `drone*`
- `eclipse*`
- `galaxy`
- `globe`
- `meteor`
- `moon*`
- `planet*`
- `radar`
- `robot`
- `rocket*`
- `satellite*`
- `solar-system`
- `space-shuttle`
- `star-shooting`
- `stars`
- `telescope`
- `user-astronaut`
- `user-robot`
- `watch-calculator`

While it could be argued that icons such as `atom*` and `solar-system` are only artists' concepts of the real deal and have nothing to do with reality (size, scale, shape, orbit lines etc.), I think it's fair deal to assume users know this is not an accurate scale model but rather a depiction of a very real thing or concept not subject to fantasy or fiction.

And while one could argue they all have that *SciFi vibe*, especially `robot` and `user-robot`, fiction is not a subset or intersection of reality. Science Fiction depends on Reality, not vice versa.

I don't think we (need | should have) a discussion about the **Moon**, **Rockets**, **Telescopes** etc. being real.

**To Reproduce**
Go to https://fontawesome.com/icons?c=science-fiction

Think: Given opportunity and money, could I touch or see the thing depicted? Have they already been observed?

**Expected behavior**
Categorize icons based on science, not feelings.
Above icons should be categorized as something along the lines of **Astronomy** or **Space** (which, funny enough, is listed as a *search term* on the front page and shows some of the *Science Fiction* icons under there, but clicking the link only yields the `people-arrows` icon variations because of version filters).
Icons not listed above shall remain labeled as **Fiction** (until proven to be real).

The term "Science Fiction" can still be associated to all those icons by means of **tags** or **keywords** in its description, as they are relevant to SciFi content.

**Screenshots**
*(None, visit https://fontawesome.com/icons?c=science-fiction and see yourself)*

**Version and implementation**
Version: 5.11.1
Browser and version: *ALL*

*(render mechanisms not applicable)*

**Bug report checklist**
- [**X**] I have filled out as much of the above information as I can
- [**X**] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [**X**] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

*Note: I'm sorry for the funny title, but I'm serious. A telescope is not fiction, period.*

**Comment by sensibleworld** [comment]
Hey @TacticalCode! Thanks for writing in, and for the thoughtful post. We're not meaning to imply that the icons listed are fictional, only that they're common objects and ideas that fit within the science fiction genre (one of our favorites!). But, I can certainly see the confusion that could arise by the way we've categorized items. I think adjusting the category name to "Space" to similar could fix the issue (with some modifications). 

Look for some updates as we move forward with version 6.

Thanks!
