### ISSUE TITLE
Icon request: Confused-face (😕)

### ISSUE THREAD

**Issue by saagar408** [FortAwesome/Font-Awesome#16840]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To be used where a user is not concerned about a choice presented to them. For example: Do you want a garage when buying a house. Available options might be: Yes / No. However, if I don't have a car then I will be indifferent about this question. So I want to present an option

**Example image (optional)**
Insert the example image here if necessary.
Something like this. Would be better if it is not an emoji as it looks unprofessional but couldn't figure out how to represent indifferent:
![image](https://user-images.githubusercontent.com/67509263/85923621-84b6fc80-b884-11ea-838c-34d4e7779ed8.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) 
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
😕

**Comment by aethior** [comment]
Hi @saagar408,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/face-confused

Regards.

cc/ @tagliala
