### ISSUE TITLE
Icon request: icon-pepper (icon-chili)

### ISSUE THREAD

**Issue by grolimur** [FortAwesome/Font-Awesome#1684]
Would be great for indicating the level (easy - medium - hard) of a tutorial or an article

An example can be found here: http://flashinformatique.epfl.ch/spip.php?rubrique496
Beside every article stands 1, 2 or 3 pepper to tell the reader if the article has a low, medium or high technical level.

Thanks for this great font!

**Comment by ninikene** [comment]
+1 needed for restaurant dishes to show heat levels!

**Comment by cebence** [comment]
+1

**Comment by rlarcombe** [comment]
+1

**Comment by TomTheBomb** [comment]
+100

**Comment by Newnab** [comment]
+1

**Comment by cash3p** [comment]
+1  Definitely could use a chili pepper icon :)

**Comment by Fatbat** [comment]
+1 again. Let's get this important icon into the next update.

**Comment by AncientSwordRage** [comment]
:+1: This would be awesome!

**Comment by Taapo** [comment]
+1 this is quite important to include now

**Comment by MrZach** [comment]
+1

**Comment by HarmOo** [comment]
+1, quite interesting for the restaurant business to show how spicy a dish is.

**Comment by Emaitch** [comment]
+1

**Comment by tarunaggarwal54** [comment]
+1

**Comment by luckyagarwal3247** [comment]
+1

**Comment by praditha** [comment]
+1

**Comment by JonathanRys** [comment]
+1

**Comment by maemae79** [comment]
+1, oh please oh please

**Comment by maemae79** [comment]
guess this isn't going to happen, we've been waiting more than 3 years, so just adding my little +1 hopefully, *sniff.

**Comment by JonathanRys** [comment]
Well only 4 people have actually given a thumbs up to the idea, so all these +1 comments are in vain.

**Comment by maemae79** [comment]
oops. I'm new to all this, I will add a thumbs up then (sorry was copying everyone else!!)


________________________________

**Comment by tdhsmith** [comment]
Reactions are preferred nowadays (precisely due to these extremely unreadable chains of +1's). But the issue long predates Github's reaction system so there's a lot of old responses here. 

🌶

**Comment by AdrienTorris** [comment]
+1, needed for an application, for a notation like stars but for a "hot" notation.

**Comment by AdrienTorris** [comment]
It could be great if this icon could be release with his empty-dude icon, _icon-pepper-o_, to use them like [user](http://fontawesome.io/icon/user/) and [user-o](http://fontawesome.io/icon/user-o/), [star](http://fontawesome.io/icon/star/) and [star-o](http://fontawesome.io/icon/star-o/), ...

**Comment by ColmansMustardSaves** [comment]
hi there how i do all these im a starter and I want to add some icons to my wp site and awesome fonts havent gont what I need . I need this pepper and a coffee machine when I can fint them and add them to my servises

**Comment by Wingo5315** [comment]
+1

**Comment by linguisten** [comment]
+ 1

**Comment by Fatbat** [comment]
+1 again. This is quite a common icon in restauranting (Indian, Thai, Szechuan, Mexican, Caribbean, etc. etc.) and really should be a priority IMO. Would love to see both a regular chili and a flaming chili.

The food and drink section is pretty much non existent and needs a lot of love. I see a few food icons have been covered now, but not enough to warrant an entire category yet.

**Comment by jasonhancock** [comment]
+1

**Comment by sensibleworld** [comment]
This icon is hot: https://fontawesome.com/icons/pepper-hot?style=solid
