### ISSUE TITLE
Icon request: icon-ok / icon-ok-sign (icon-odnoklassniki)

### ISSUE THREAD

**Issue by antonkorda** [FortAwesome/Font-Awesome#1685]
This is a request for a brand icon for Odnoklassniki - russian social network (translation - Classmates). 

Font awesome has a lot of social networks icons, but this one is still missing. I think it would be useful for russia federation and other countries who work with russian people, because it's second popular social network in this region, after VK (vk logo already included in font-awesome). 

This social network has a very simple logo with O and K letters under each other, which form something like human silhouette:

<img width="150" height="150" src="http://www.logotypes101.com/logos/681/E4690654D4FCB5F47EBD5A952DDE51E9/odnoklassniki.png" />

Here is an sign icon example:

<img width="150" height="150" src="http://www.fanrayhon.uz/logo/odnoklassniki.png" />

I found a lot of resourses with this logo in .eps format, here some:

https://www.brandsoftheworld.com/logo/odnoklassniki?original=1
http://www.logotypes101.com/free_vector_logo/95777/Odnoklassniki

Sorry if I did mistakes, english is not my native language. 
I use font awesome with pleasure and will be very appreciated if you include this social network logo in next version of FA.

**Comment by ajayver** [comment]
+1

**Comment by maksimchuk** [comment]
+1

**Comment by ucozlab** [comment]
+1

**Comment by githubfantom** [comment]
+1

**Comment by XandeR350** [comment]
+1

**Comment by ivansu** [comment]
+1

**Comment by twopix** [comment]
+10

**Comment by alexok** [comment]
+1

**Comment by d4mk0** [comment]
Also wanna see this icon in new FA icons set. Please! :)

**Comment by irudoy** [comment]
+1

**Comment by shvetsovdm** [comment]
@irudoy +1 =D

**Comment by hasesanches** [comment]
+100500

**Comment by pendolf** [comment]
+1

**Comment by SmileMD** [comment]
+1

**Comment by bora89** [comment]
+1

**Comment by fatumandu** [comment]
+1
The request is 2013 year ! 
Its a problem to make this icon? WHY NO? 
How many year you need to make this icon?

**Comment by iegik** [comment]
+1 http://apiok.ru/wiki/pages/viewpage.action?pageId=42476299 http://apiok.ru/wiki/download/attachments/42476299/OK.RU_logo.pdf?version=1&modificationDate=1416996613000&api=v2

**Comment by bora89** [comment]
> How many year you need to make this icon?
Aha-ha, the sanctions taking place )))

**Comment by iegik** [comment]
Found old ones: http://apiok.ru/wiki/display/api/Graphical+elements+for+web

**Comment by bora89** [comment]
> Found old ones: http://apiok.ru/wiki/display/api/Graphical+elements+for+web

Don't you understand that even the "new" icon had not implemented yet? Nobody cares about old icons.

**Comment by iegik** [comment]
https://github.com/fontello/brandico.font - this ticket can be closed.

**Comment by ste93cry** [comment]
Unfortunately this means loading a new font just to have social network icons. That font seems awesome, but I would prefer to not have to load another resource just to have this icon in my theme

**Comment by bora89** [comment]
> https://github.com/fontello/brandico.font - this ticket can be closed.

When you speak or write something - think about it before!

**Comment by tagliala** [comment]
Sorry guys, I know this logo is important for all you Russian devs.

Meanwhile please consider a custom build of fontawesome which includes this logo. You could fork the repository, edit the .otf, regenerate the whole thing and share here

I'm not going to close this issue

**Comment by d4mk0** [comment]
@tagliala hm okay, thanks 4 u answer!

**Comment by musayab** [comment]
+1

**Comment by iegik** [comment]
https://github.com/FortAwesome/Font-Awesome/pull/5639

**Comment by tagliala** [comment]
thanks @iegik . Please also share the link to your fork. I can't do very much with the PR

**Comment by margani** [comment]
+1

**Comment by iegik** [comment]
https://github.com/iegik/Font-Awesome/tree/4.3.1-wip

**Comment by Hunternnm** [comment]
+1

**Comment by genok** [comment]
+1

**Comment by alexeyahuel** [comment]
+1

**Comment by EvanWieland** [comment]
+1

**Comment by simpleadm** [comment]
+1

**Comment by codemotion** [comment]
+1

**Comment by bmate23** [comment]
+1

**Comment by musayab** [comment]
+1


Воскресенье, 08 марта 2015, 10:58 -07:00 от bmate23 <notifications@github.com>:
>+1
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Musayab 
musayab@mail.ru

**Comment by nchervyakov** [comment]
+1

**Comment by mardukkkurios** [comment]
+1

**Comment by 1nSaneRu** [comment]
+1

**Comment by ostashevdv** [comment]
+1

**Comment by awaro** [comment]
+
end -  mail.ru
+++++++++++++++++++++++++++++++++++++++++100500

**Comment by NBAH1990** [comment]
+

**Comment by orientalpers** [comment]
+1

**Comment by tivuh** [comment]
+1

**Comment by pafnuty** [comment]
@1nSaneRu 
@ostashevdv
@awaro
@NBAH1990 
@orientalpers
@tivuh 
Ребята, вы хоть читайте иногда, что написано https://github.com/FortAwesome/Font-Awesome/issues/1685#issuecomment-73512793 прежде, чем постить #плюсодины

**Comment by shalomanov** [comment]
Я только не понял, с OK кастомный билд только, или в новую версию войдет? А то я шрифт с  CDN  гружу...

**Comment by G-Driver** [comment]
+1 why not ;)

**Comment by Carteisus** [comment]
Как добавить? можно подробный хауту?

**Comment by sinyayadynya** [comment]
+1 and please within round shape too (https://github.com/FortAwesome/Font-Awesome/issues/6409)

**Comment by thekondrashov** [comment]
+1

**Comment by cema93** [comment]
+1

**Comment by soulkoden** [comment]
+1

**Comment by adechandra** [comment]
+1

**Comment by sunyoureyes** [comment]
+1

**Comment by cgwic** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
**tagliala** commented:
> Sorry guys, I know this logo is important for all you Russian devs.

but **tagliala**.. not only Russian. Ukranian, Kasakh, Belarussian.. Almost all East Europe and a part of Asia are waiting for the icon. Is this icon really so complex? vk.com is already here (fortunately), but that network only 30% more popular than Odnoklassniki (70 million vs. 45 million hits a day). Furthermore there are icons of much less popular services in Font Awesome, some of which I have never heard about.

Still hoping to get the icon.

Thank you in advance.

**Comment by 1ione** [comment]
+1

**Comment by weblegko** [comment]
+1

**Comment by AlexTikhonov** [comment]
+1

**Comment by nemonweb** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.

**Comment by apschool** [comment]
+1

**Comment by d4mk0** [comment]
Already added. Slow..

**Comment by pafnuty** [comment]
..poke ))
