### ISSUE TITLE
Icon Request: fa-washingmachine

### ISSUE THREAD

**Issue by jeroenst** [FortAwesome/Font-Awesome#16859]
I would like to have a washingmachine icon

https://previews.123rf.com/images/blankstock/blankstock1908/blankstock190801772/128734688-laundry-line-icons-dryer-washing-machine-and-dirt-shirt-laundromat-hand-washing-laundry-service-icon.jpg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro

https://fontawesome.com/icons/washer?style=solid
