### ISSUE TITLE
Wrong Facebook Icon

### ISSUE THREAD

**Issue by aguilar1181** [FortAwesome/Font-Awesome#16851]
Something change out of nowhere. I'm using this <i class="fab fa-facebook-f"></i> which it should be just the facebook "f" however is displaying the same icon as this <i class="fab fa-facebook"></i> with the rounded circle.

You can see the issue in the footer of my site http://capri.umgdevcloud.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is a third party plugin (`shiftnav-responsive-mobile-menu`) loading an older version of Font Awesome (4.7) on your website.

We do not support third party plugins, you could ask the developer to update it or you can edit it manually

We have a WordPress plugin with conflict detection that could help: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress


Closing here, but feel free to comment
