### ISSUE TITLE
fa-lungs icon not loading

### ISSUE THREAD

**Issue by mathewhiley** [FortAwesome/Font-Awesome#16856]
Hi, we use the free version of Font Awesome and are considering purchasing the pro license. So far we have found most icons to fit or needs, but recently discovered the "fas fa-lungs" icon does not render for us, despite it being a freely available icon. Could you please verify why this is the case. The two HTML approaches below both fail:

`<div class="fas fa-lungs"></div>`
and
`<div><i class="fas fa-lungs"></i></div>`

We are using v5.8.1:

`<link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" rel="stylesheet">`

Please advise?
Regards,
Mat

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Please upgrade to 5.13.0, there is an issue in the documentation

This icon has been added to the free set in the 5.13.0 "COVID-19" release, but we forgot to change the version numbers of some icons.

It affects:
- [ ] disease
- [ ] faucet
- [ ] hospital-user
- [ ] lungs

@sensibleworld or @talbs could you please update the version of the above icons to 5.13.0 ?

**Comment by mathewhiley** [comment]
Awesome, thank you! That worked.
________________________________
