### ISSUE TITLE
fa-hand-holding-medical NOT WORKING

### ISSUE THREAD

**Issue by eduhAgostinho** [FortAwesome/Font-Awesome#16865]
the icon with the class "fas fa-hand-holding-medical" doesn't appear. I already use others icons in my project btw, this is the only one that doesn't work

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-hand-holding-medical](https://fontawesome.com/icons/hand-holding-medical?style=solid) has been introduced in Font Awesome 5.13.0, so please double check that you are using Font Awesome 5.13.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
