### ISSUE TITLE
Icon request: icon-clothing (Hoodie, Shoes, Underwear, Bikini, etc)

### ISSUE THREAD

**Issue by PacificBracelets** [FortAwesome/Font-Awesome#16878]
**What can it be used for?**
e-commerce websites, fashion brands, catalogs, etc.

**Example image (optional)**
https://imgur.com/Ame9Fmk

**Icon request checklist**
- [ matched set ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ yes ] I have included at least one example image if it could be helpful (optional)
- [ yes ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Hoping that since i paid for Font Awesome Pro 5, and preordered Pro 6, that maybe you guys could create a new set of icons for e-commerce fashion sites/clothing sites. There are many many uses for these icons, not just for shopping websites.

Looking for the following icons:
- Hoodie/Pullover Hooded Sweater
- Zip-Up Hoodie
- Long Sleeve Shirt
- Womens Underwear (Bra and Panties)
- Mens Underwear (Boxer Briefs)
- Shoes (Sneakers/Casual Shoes)
- Womens Dresses
- Tank Top
- Shorts
- Hat (baseball hat)
- Beanie (Snow Hat)

Im shocked that with 7,000+ icons that none of these exist except a t-shirt.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> [ matched set ] This is a single icon or matched pair (Ex: lock / unlock)

Sorry, I cannot keep requests for set open in the Free Repo

> Hoping that since i paid for Font Awesome Pro 5, and preordered Pro 6, that maybe you guys could create a new set of icons for e-commerce fashion sites/clothing sites. There are many many uses for these icons, not just for shopping websites.

Perfect! Requests for set are allowed into Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Just check if you have access, I can move the issue to the other repo so you don't need to recreate it

**Comment by tagliala** [comment]
Closing here
