### ISSUE TITLE
New Fonts

### ISSUE THREAD

**Issue by Natdog1113** [FortAwesome/Font-Awesome#16873]
Hi 

I See there are so many awesome fonts but there are some that I need that are missing like the google drive and one drive icons. I see you have the dropbox icon which is great but can you maybe include these two. Its just weird to have a couple cloud storage icons but not the whole range.

Thanks and am a great supporter of font-awesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> like the google drive

This icon is available in FA 5: https://fontawesome.com/icons/google-drive?style=brands

Please make sure to update your version of Font Awesome to the latest available one.

Ref:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

> one drive icons

This icon has been requested in #2887, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
