### ISSUE TITLE
Icon request: two-way-arrows

### ISSUE THREAD

**Issue by technotion** [FortAwesome/Font-Awesome#16876]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
Traffic - Network Traffic - Two Way Traffic
Two opposing way arrows.

**Example image (optional)**
Insert the example image here if necessary.
https://fontawesome.com/icons/long-arrow-alt-left?style=duotone
![two-way-arrow](https://user-images.githubusercontent.com/7366409/86525990-27aae000-be5c-11ea-87a4-bbb01f427b15.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think you are looking for [fa-exchange](https://fontawesome.com/icons/exchange-alt?style=solid)

[arrows-alt-h](https://fontawesome.com/icons/arrows-alt-h?style=solid) may also be an alternative

Hope it helps

Closing here
