### ISSUE TITLE
License of fontawesome

### ISSUE THREAD

**Issue by FerusAndBeyond** [FortAwesome/Font-Awesome#16884]
I apologize if this is a dumb question but I want to know about the licensing, so if I go to the site and the [plans](https://fontawesome.com/plans) page, there is a limt of 10K Pageviews/Month for the free plan. But in old versions there was a MIT-license. So is it still possible to use the old versions with no restrictions (as in MIT licensing) or does this new plan apply to them to?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> there is a limit of 10K Pageviews/Month for the free plan.

This is a limitation of our hosted kits. Kits are improved versions of CDN hosted files, with some options to upgrade font awesome without deploy, switch from CSS to SVG implementation, enable auto-accessibility, etc.

More (a little bit outdated) information about kits here: https://blog.fontawesome.com/introducing-font-awesome-kits/

> So is it still possible to use the old versions with no restrictions (as in MIT licensing) or does this new plan apply to them to?

Sure!

You can:

1. Self-host Font Awesome (https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself)
2. Use any other method described at https://fontawesome.com/start#other-methods
3. Use third-party CDNs (Example: https://cdnjs.com/libraries/font-awesome)

@robmadole if you would like to add something

**Comment by robmadole** [comment]
@tagliala no sir, couldn't have said it better myself

**Comment by tagliala** [comment]
Thanks! 

@FerusAndBeyond hope it helps

Closing here, but feel free to comment

**Comment by FerusAndBeyond** [comment]
@tagliala That answered all my questions, thanks!
