### ISSUE TITLE
The NPM package for 5.13.1 PRO includes itself

### ISSUE THREAD

**Issue by noelmccrory** [FortAwesome/Font-Awesome#16890]
Download from https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/5.13.1/fontawesome-pro-5.13.1.tgz

![image](https://user-images.githubusercontent.com/11225700/87149833-e2960c00-c2a8-11ea-87ab-20c955878311.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm.

@robmadole could you please take a look?

**Comment by robmadole** [comment]
Ok, we've got this fixed and it will be released in the next 5.x version. Thanks for the report @noelmccrory

**Comment by jasonlundien** [comment]
A fix was released with 6.0.0-beta2.
