### ISSUE TITLE
Tripadvisor icon does not render properly in Android/Chrome

### ISSUE THREAD

**Issue by akidaniel** [FortAwesome/Font-Awesome#16895]
**Describe the bug**
Tripadvisor icon does not render properly in Android/Chrome

**To Reproduce**
https://jsfiddle.net/tagliala/pw94dbvc/

I've read [this issue](https://github.com/FortAwesome/Font-Awesome/issues/16817), the icon renders well in desktop browsers but not on Android/Chrome

**Expected behavior**
Renders correctly

**Screenshots**
![Screenshot_20200711_193655_com android chrome](https://user-images.githubusercontent.com/21230497/87231157-034b8800-c3b5-11ea-8330-121fc3e6d785.jpg)

**Version and implementation**
Version: 5.13.1 CSS
Browser and version: Android 10 – Chrome 83.0.4103.106

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This is a known issue and it will be fixed in the next release.

Please follow #16817 

Hope it helps

Closing here
