### ISSUE TITLE
Icon Request : Pikachu - Most Iconic Pokemon In The Franchise (face icon)

### ISSUE THREAD

**Issue by Almigra** [FortAwesome/Font-Awesome#16901]
**What can it be used for?**
There is around 900 Pokemon species actually, but only few of them are recognized by everyone. I wonder if we can have them as icons. 
Can we have at least only Pikachu with a face icon like in "Pokemon Shuffle"  game?

**Example image**
![Pikachu](https://user-images.githubusercontent.com/63087888/87461299-8582b900-c60e-11ea-82ff-7a27a51859d0.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by Almigra** [comment]
Some other popular Pokemon like Bulbasaur, Squirtle, Charmander, Mew and Mewtwo can be interesting too !

![Bulbasaur](https://user-images.githubusercontent.com/63087888/87461687-0f328680-c60f-11ea-8c42-78494ccfefd6.png)
![Squirtle](https://user-images.githubusercontent.com/63087888/87461692-0f328680-c60f-11ea-9ef4-f7b269245c2d.png)
![Charmander](https://user-images.githubusercontent.com/63087888/87461693-0fcb1d00-c60f-11ea-9eaf-e2872b952318.png)
![Mew](https://user-images.githubusercontent.com/63087888/87461695-0fcb1d00-c60f-11ea-9638-0b6ffab43604.png)
![Mewtwo](https://user-images.githubusercontent.com/63087888/87461698-0fcb1d00-c60f-11ea-89a5-592a59fc6e26.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld are you willing to implement 900 * 4 * 2 icons? 😅

Jokes aside, I can read that Pokemon is trademarked/registered by Nintento (source: pokemon.com), so I must close this and label as cantfix

Ref: https://github.com/FortAwesome/Font-Awesome/issues/15291#issuecomment-514653683
