### ISSUE TITLE
itch.io

### ISSUE THREAD

**Issue by jony100200** [FortAwesome/Font-Awesome#16903]
**What can it be used for?**
This can be used for game developers who have games showed on https://itch.io/

**Example image (optional)**
Insert the example image here if necessary.

![itch](https://user-images.githubusercontent.com/7604468/87527283-e4b9eb00-c659-11ea-8281-dc9d8377ce30.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

itch.io has been implemented in FA 5.8.0

https://fontawesome.com/icons/itch-io?style=brands

Please make sure that you are using FA 5.8.0 or newer

Hope it helps

Closing here
