### ISSUE TITLE
Icon request: fab-drupal

### ISSUE THREAD

**Issue by xdega** [FortAwesome/Font-Awesome#16906]
**What can it be used for?**
The Drupal brand icon already exists, it is just using an out of data graphic. Here is the official post regarding the rebranding: https://www.drupal.org/blog/new-drupal-brand-ready-for-drupal-9-launch

**Example image (optional)**
![EL_blue_RGB(1)](https://user-images.githubusercontent.com/8093386/87555059-c9ef7280-c669-11ea-8e0d-06f12acb5b57.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by xdega** [comment]
Here's the Black SVG image from the brand kit, if that helps.

[EL_black_CMYK.zip](https://github.com/FortAwesome/Font-Awesome/files/4926440/EL_black_CMYK.zip)

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
