### ISSUE TITLE
Icon request: Aircraft/sectional icons

### ISSUE THREAD

**Issue by cullub** [FortAwesome/Font-Awesome#16913]
**What can it be used for?**
These icons are used for marking FAA sectionals.  For example, sites like skyvector.com use these shapes to mark maps.  They're pretty well defined already, and it might be nice to include them in the FontAwesome package.

**Example image**
From the official FAA [knowledge testing supplement](https://www.faa.gov/training_testing/testing/supplements/media/sport_rec_private_akts.pdf) 

![image](https://user-images.githubusercontent.com/7533931/87619752-91d84600-c6e2-11ea-936f-ae8c756a00bd.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, this looks more like a set of icons than a single icon/matched pair

If you are a Font Awesome Pro customer, you can request for sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Pro customer but you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Feel free to clarify if this is a request for a single icon, meanwhile closing here
