### ISSUE TITLE
Icon request: ocean waves

### ISSUE THREAD

**Issue by TimWhite77** [FortAwesome/Font-Awesome#16917]
**What can it be used for?**
We need to use this for a product

**Example image (optional)**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F1178525%2Fmicrowaves_ocean_radiation_ripple_sea_water_waves_icon&psig=AOvVaw1RKlmHWiLzbrm5EU2GtKXx&ust=1594994247195000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNCqjd720eoCFQAAAAAdAAAAABAI
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/water?s=solid&f=classic
