### ISSUE TITLE
Icon request: codeigniter

### ISSUE THREAD

**Issue by bilalkachara** [FortAwesome/Font-Awesome#16929]
**What can it be used for?**
It is used tto addin my site

**Example image (optional)**
![image](https://user-images.githubusercontent.com/68458474/87846788-21067900-c8f0-11ea-9b34-050f1be3bebf.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #4316, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
