### ISSUE TITLE
桌子

### ISSUE THREAD

**Issue by das2348** [FortAwesome/Font-Awesome#16925]
桌子

**Comment by das2348** [comment]
桌子

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate (guess: chinese?)

> 桌子 ➡️  table

Table may be a duplicate of #4149, #14819, #3519, #9495 please add a 👍 reaction to the request that you are looking for.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
