### ISSUE TITLE
Icons request - RFID alias

### ISSUE THREAD

**Issue by kpapado** [FortAwesome/Font-Awesome#1692]
You could make an alias to the icon-rss for rfid. For example icon-rfid
Also an icon for nfc. For example icon-nfc
For the nfc logo see here: http://www.nfc-forum.org/aboutnfc/

I am missing also an icon for smartcardFor example: icon-smartcard

**Comment by Alplob** [comment]
Yes, that icon would be great! :+1:

**Comment by tagliala** [comment]
hi, this request is about an alias... please +1 #6111 for rfid

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
