### ISSUE TITLE
Se les rompe la pagina

### ISSUE THREAD

**Issue by maximo1611** [FortAwesome/Font-Awesome#16927]
Se les des vincula el css o algo asi al pasar unos segundos.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate:

> The css or something like that is detached after a few seconds.

If the translation is correct, it doesn't look like something that depends on Font Awesome

Please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case so we can take a look
