### ISSUE TITLE
Instagram,Gmail icons

### ISSUE THREAD

**Issue by Pravinkannan12** [FortAwesome/Font-Awesome#16935]
I am unable to get instagram and gmail icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Instagram is already here: 
- https://fontawesome.com/icons/instagram?style=brands
- https://fontawesome.com/icons/instagram-square?style=brands

If you have troubles in how to use icons, please refer to our documentation: https://fontawesome.com/start

gmail has been requested at #4655 , please add a 👍 to that request

Closing here
