### ISSUE TITLE
people-arrows icon is not working on v5.14.0

### ISSUE THREAD

**Issue by SamAriafar** [FortAwesome/Font-Awesome#16937]
I'm using the CSS type of FontAwesome v5.14.0 (free license) on my web application and everything seems working except one of my icons:

![image](https://user-images.githubusercontent.com/8606282/87977780-92505280-cacf-11ea-8155-61465a0b979a.png)

Here is the code:

`<i class="fas fa-people-arrows"></i>`

P.S. JS type works fine...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case?

**Comment by tagliala** [comment]
> Also doesn't work for me, using the built-in FA support in Elementor Pro / Wordpress.

Hi @tiagoefreitas sorry, we do not support third-party software

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

**Comment by m4limo** [comment]
Same here - `fa-people-arrows` does not work, other PRO icons work just fine..

**Comment by tagliala** [comment]
Hi @m4limo, feel free to open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) with all the information required and provide a reproducible test case

I'm going to close here because this post lacks of information and the issue is not reproducible: https://jsfiddle.net/tagliala/0x1qe4by/8/
