### ISSUE TITLE
Icon request - NFC

### ISSUE THREAD

**Issue by kpapado** [FortAwesome/Font-Awesome#1695]
Icon for nfc. For example icon-nfc
For the nfc logo see here: https://nfc-forum.org/our-work/nfc-branding/n-mark/guidelines-and-brand-assets/

**Comment by kylemantesso** [comment]
+1 

http://hotline.ccsinsight.com/_images-article/NFC.png

**Comment by adrianbader** [comment]
+100
@kpapado, @ctadlock your links are broken!
@kylemantesso: I think this is not what kpapado meant; this is not NFC but RFID. -> fa-rfid would also be a good icon, however.

https://de.wikipedia.org/wiki/Near_Field_Communication#/media/File:NFC-N-Mark-Logo.svg
(without TM)

**Comment by ErnestRoca** [comment]
There are different symbols to represent this.

Contactless payments:
One symbol with a hand and other without the hand
https://en.m.wikipedia.org/wiki/Contactless_payment

NFC :

https://de.wikipedia.org/wiki/Near_Field_Communication#/media/File:NFC-N-Mark-Logo.svg

And for RFID, I think there are not specified icon:

https://en.m.wikipedia.org/wiki/Radio-frequency_identification
El dia 16 febr. 2016 11:38 AM, "adrianbader" <notifications@github.com> va
escriure:

**Comment by adrianbader** [comment]
Since this is the request for icon-nfc, in my opinion, the only correct one would be the NFC logo already linked: https://de.wikipedia.org/wiki/Near_Field_Communication#/media/File:NFC-N-Mark-Logo.svg

Contactless payment would be e.g. fa-contactless-payment: another icon (which I would appreciate too). Contactless payment is not equal with NFC; The communication used for contactless payment is ISO14443, which is only a subset of NFC.

**Comment by kpapado** [comment]
Hello.

I agree this is the correct icon to use for NFC. It may be a legal problem to use the NFC logo without the TM.

You can contact NFC forum her: http://nfc-forum.org/contact-us/ and ask for their advice.

 

Best regards,

Kostas P.

**Comment by vHeemstra** [comment]
I opened a separate request for fa-contactless-indicator and fa-contactless-symbol [here](https://github.com/FortAwesome/Font-Awesome/issues/8617).

( For use as described and prescribed at: [http://www.emvco.com/best_practices.aspx?id=117](http://www.emvco.com/best_practices.aspx?id=117) )

**Comment by matejjurancic** [comment]
+1

**Comment by phuzi** [comment]
+1

This has been open for 3 years, there must be a reason it hasn't already been added?

**Comment by bojingo** [comment]
We have a big need for this font icon. We are very interested in having this, WITH the legal attribution.

**Comment by Alplob** [comment]
Yes, this icon would be really useful 😃

**Comment by 2ndGAB** [comment]
My 2cents https://github.com/FortAwesome/Font-Awesome/issues/10650

**Comment by 2ndGAB** [comment]
@vHeemstra Personnaly I find the contactless indicator really too close to wifi.

**Comment by 2ndGAB** [comment]
I think this [one](https://www.brandsoftheworld.com/logo/nfc-6) is better

**Comment by mxzgithub** [comment]
+1

**Comment by pdowse** [comment]
+1 - yes please!

**Comment by Legenyes** [comment]
+1

**Comment by Legenyes** [comment]
+1

**Comment by VictorBNT** [comment]
+1 Please !

**Comment by timrichardt** [comment]
+1

**Comment by hmoule** [comment]
+1

**Comment by Nathanael-design** [comment]
Do you want an nfc logo?
I give you a ready to use svg

![nfc](https://user-images.githubusercontent.com/69514182/89902948-5c425200-dbe7-11ea-9070-da6a7c8bede4.png)
[Logo-nfc.zip](https://github.com/FortAwesome/Font-Awesome/files/5057229/Logo-nfc.zip)

Nath.P

**Comment by tagliala** [comment]
Please notice  that this is the request for the official NFC logo (link in the first post)

If you need a generic contact-less icon, please upvote #9887

**Comment by alfikr** [comment]
up

**Comment by OscarBeiro** [comment]
+1

**Comment by copiri-six** [comment]
👍

**Comment by sensibleworld** [comment]
We have a number of options available for this now: https://fontawesome.com/search?q=nfc&o=r&s=solid
