### ISSUE TITLE
Icon request: toggle-center

### ISSUE THREAD

**Issue by somethingSTRANGE** [FortAwesome/Font-Awesome#16964]
**What can it be used for?**
Used along with "toggle-on" and "toggle-off" to represent a third state.

Perhaps "toggle-center", "toggle-mid", or "toggle-partial".

Similar to physical 3-position slide switches that have three states: "manual / off / auto", "left / off / right", "off / preset / max" or something like that. I might use something like this for a foldout where "off" is fully collapsed, "mid" is showing a few details, and "on" shows all details.

The Pac-Man Ghost LED light sitting on my desk has a three-way toggle: "on / off / party".

**Example image**
![fa-toggle](https://user-images.githubusercontent.com/6905832/88845048-6f413500-d198-11ea-8a12-d448535bacfa.png)

![Miniature-SPDT-Slide-Switch-3-Position-1P3T-_1](https://user-images.githubusercontent.com/6905832/88845791-8a607480-d199-11ea-9f85-f598cb43d1bb.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) - _Single icon that complements an existing matched pair._
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by somethingSTRANGE** [comment]
Similar "three state switch" functionality could also be gained with this [Icon request: caret-down-right #16965](https://github.com/FortAwesome/Font-Awesome/issues/16965).

**Comment by aethior** [comment]
@tagliala `toggle (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
