### ISSUE TITLE
Not able to Register and Sign in- "The Setup link is BAD"

### ISSUE THREAD

**Issue by JayanthApagundi** [FortAwesome/Font-Awesome#16960]
Cannot access the CDN- Content Delivery Network 
"The setup link is BAD"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

**Comment by JayanthApagundi** [comment]
I think the issue is been fixed. 😄 Thanks.
The issue was I was not able to sign/reset my password. I would get a mail to reset the password but as I click on that I use to get "The setup link is BAD".
