### ISSUE TITLE
Icon request: data types

### ISSUE THREAD

**Issue by nathan-rapidstash** [FortAwesome/Font-Awesome#16978]
**What can it be used for?**
Signifying common data types: string, integer, boolean, array, object, date, file, null etc.

**Example image (optional)**
https://ux.stackexchange.com/questions/43695/graphic-representation-of-various-data-types

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this request open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

>  This is a single icon or matched pair (Ex: lock / unlock)
