### ISSUE TITLE
Icon request: icon-catapult

### ISSUE THREAD

**Issue by Bolza** [FortAwesome/Font-Awesome#1697]
Hello guys. I very appreciate your work, i'm using your icons on tvshowmark.it, a tv-series management webapp. So, first of all, thank you for your efforts.

Now, it would be nice if you add a catapult to your icons. Yes, i know you have plenty of requests, some of which very serious like NFC, SMART-CARD and other boring stuff. But think of how much Font-Awesome would be improved by adding a wonderful Catapult. 
1. Catapults are REALLY awesome stuff and you are Font-Awesome, can you really afford to keep going without a catapult in your list?
2. Catapults means a lot! They mean you really want to do something, let's say... like a catapult. Just think about: "I'm going there LIKE A CATAPULT", or "I'm about to CATAPULT you out of here", or "Ehi, where's my CATAPULT?"... did you see? Every day in our life we talk about catapults!
3. In our app we need an icon for "Similar". Well, there isn't. Not your fault guys, there's no icon for "Similar" in the whole internet. So what can we do when there's no icon to mean something? We use a CATAPULT, of course! 

So if you could implement something like this:
http://inkwellideas.com/wp-content/uploads/2010/07/catapult2.png

That would be absolutely AWESOME. 

Thank you guys,
see you soon, like a catapult!

Stefano

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by Bolza** [comment]
Wait, are you telling me i waited eleven years, sitting at my desk, refreshing this page every ~30mins to **not** get a Catapult Icon? Very disappointing.

Ok then, listen up, what about a Trebuchet?

**Comment by qaisjp** [comment]
I was just a young lad when I posted on this issue 10 years ago. What am I now? Scarred.

See you in another 10 years friends.
