### ISSUE TITLE
Icon request: Hyves

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1698]
Hyves is a dutch social network

![Hyves](https://si0.twimg.com/profile_images/1605805863/Icon-Hyves-RGB-512px.png)

**Comment by aethior** [comment]
>In 2013, the social network was officially discontinued, due to the huge decrease in accounts due to the growing popularity of other social networks like Facebook and Twitter in the Netherlands. The site continued as Hyves Games, where members could use their Hyves accounts to play social games. ([more info](https://en.wikipedia.org/wiki/Hyves))

cc/ @tagliala
