### ISSUE TITLE
npm.fontawesome.com is down again

### ISSUE THREAD

**Issue by aleksandrlat** [FortAwesome/Font-Awesome#16987]
We are having intermittent issues today
```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-light-svg-icons/-/5.14.0/pro-light-svg-icons-5.14.0.tgz: Request failed \"502 Bad Gateway\"".
```

Builds are failing and blocking us

**Comment by saransh-malik** [comment]
Facing the same issues. Blocked on a release due to this

**Comment by danawoodman** [comment]
Yup, same here. Would be nice if there was a status page since that endpoint is probably relied on by many thousands of products to deploy.

**Comment by aleksandrlat** [comment]
This is what I found https://status.fortawesome.com/
Would be nice to see something on twitter too https://twitter.com/fontawesome

**Comment by danawoodman** [comment]
Ah nice, I google for "fontawesome" not "fortawesome". Would be neat if they had a notification on the fontawesome.com site of major outages so people like us don't have to resort to Github 😄

**Comment by aleksandrlat** [comment]
Oh found the link from https://fontawesome.com/ in the footer
![image](https://user-images.githubusercontent.com/3708309/89337778-2dd2ed00-d6a4-11ea-9365-ab76eacf267e.png)

**Comment by danawoodman** [comment]
🤦  should have checked the footer. Assumed Google "knows all" but just got a lot of "fontawesome status icon" results 😆

**Comment by tagliala** [comment]
Hi everyone, sorry for the delay

Has this been fixed?

**Comment by saransh-malik** [comment]
Yes, all good now 👍

**Comment by tagliala** [comment]
Thanks, closing here
