### ISSUE TITLE
Fontawesome authentication issue

### ISSUE THREAD

**Issue by kundanv** [FortAwesome/Font-Awesome#16997]
I get this error, using fontawesome pro, Please suggest

Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"

**Comment by hunterlong** [comment]
+1

**Comment by tsworman** [comment]
+1

Verified token is good and working. Starting worked for one of our developers last night randomly. Doesn't work for the rest of us.

**Comment by tsworman** [comment]
Response from Font Awesome:
"The way you had been authenticating (with the token in the url) was deprecated awhile back and the switchover to the new infrastructure enforced that change. You'll want to set up a .npmrc file with the token in it. Check out the docs here https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers to see how to do it. That is the correct way to authenticate now. You'll also need to remove any yarn lock files and try your install again. If you still have issues after setting that up, try clearing your npm cache and running the build."

**Comment by hunterlong** [comment]
authentication changed during/after npm server failures. I'm a pro user, but I'm using the free icons/packages. Free shouldn't require authentication. :( It adds another task to the CI build process...

**Comment by kundanv** [comment]
the issue is resolved, the problem is our license has been expired, but it works for other developers, somehow I am the only person getting this error on an npm install. after the renewal, it builds fine.
just updating; so it might help others.
