### ISSUE TITLE
Icon request: Barometer

### ISSUE THREAD

**Issue by rept** [FortAwesome/Font-Awesome#16994]
**What can it be used for?**
To indicate the current air pressure in a home.

**Example image (optional)**
This could be a gauge or a barometer.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

If I search on google for "Barometer", I can see that examples are similar to our tachometer, available at: https://fontawesome.com/icons/tachometer-alt?style=solid

I think that the tachometer can represent a barometer in a specific context

**Comment by rept** [comment]
@tagliala you are right.  I didn't see that one.  I searched for 'gauge' but it didn't come up.  Maybe add that tag to the tachometer.

**Comment by tagliala** [comment]
Hi @rept, thanks for the suggestion. We are adding new terms constantly, let's see if @talbs can add this one to the docs
