### ISSUE TITLE
Icon Request: Flinders Street Station

### ISSUE THREAD

**Issue by kochie** [FortAwesome/Font-Awesome#16990]
**What can it be used for?**
Flinders Street Station is an iconic landmark of Melbourne, Australia and is used extensively by the community as way of representing the city similar to how the Sydney Opera House and Eiffel Tower represent their respective cities. Having an icon in the pack would be awesome for the thousands of developers in Melbourne who want to represent their city on sites.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/10809884/89362208-9f488500-d710-11ea-80b1-f5d2d5d45606.png)
![image](https://user-images.githubusercontent.com/10809884/89362219-a7082980-d710-11ea-8ecf-cfff25af475b.png)
![image](https://user-images.githubusercontent.com/10809884/89362245-b4bdaf00-d710-11ea-9db7-bd0256c08494.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to close this for the moment because landmarks are out of scope

Ref: #2661
