### ISSUE TITLE
fa-files missing in FA 5

### ISSUE THREAD

**Issue by Herz3h** [FortAwesome/Font-Awesome#16993]
**Describe the bug**
Trying to upgrade from FA 4 -> FA 5 and turns out there is no `fa-files` icon. In FA 4, I used: `fa fa-files-o` which according to documentation, the `-o` suffix is to be replaced and gives: `far fa-files` except that the icon does not render anything. Upon checking online, there is no fa-files in FA 5 wtf ?

**To Reproduce**
**Expected behavior**
Shouldn't FA 5 add new icons instead of removing existing ones ?

**Screenshots**
No icon displayed with `far fa-files`
**Version and implementation**
Version: 5.14.0
Browser and version: Chrome latest

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop
 
Importing less files (fontawesome.less, solid.less, regular.less)

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In FA5 we have dropped aliases, so you can use `fa-files-o` with its original name, `fa-copy`, even if `fa-files` would have been a better name

Ref:
- https://fontawesome.com/icons/copy?style=regular
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes

Hope it helps

Closing here
