### ISSUE TITLE
Not Working in Datatables

### ISSUE THREAD

**Issue by rmdhfz** [FortAwesome/Font-Awesome#17000]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
I put an awesome font in the datatables, but it can't appear on the page

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
			foreach ($data as $key => $value) { $no++;
				$id   = $value->id;
				$opsi = '
					<button id="alokasi" class="btn btn-sm btn-flat btn-primary" data-id="'.$id.'">Alokasi</button>
					<button id="detail" class="btn btn-sm btn-flat btn-info" data-id="'.$id.'">Detail</button> '.$this->options($id);
				$result['data'][$key] = [
					$no,
					$value->fullname,
					$value->username,
					$value->email,
					$value->phone,
					$value->branch,
					$value->total_voucher.' <i class="fa fa-dashboard"></i>',
					$opsi
				];
			}

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ true ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ true  ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, didn't get this issue. Could you please provide a reproducible test case?

**Comment by rmdhfz** [comment]
Hmm... I have embed the code with the reprocedure but github hides my code, briefly I embed it in another way

**Comment by rmdhfz** [comment]
Hi @tagliala ,

i'm sorry, this case is solved. I just typo
