### ISSUE TITLE
https://registry.yarnpkg.com/@fortawesome/fontawesome-svg-core/-/fontawesome-svg-core-1.2.29.tgz

### ISSUE THREAD

**Issue by namik-hajiyev** [FortAwesome/Font-Awesome#17001]
Request to https://registry.yarnpkg.com/@fortawesome/fontawesome-svg-core/-/fontawesome-svg-core-1.2.29.tgz returns "error": "Not found"
This happens when I run yarn install command in my react app.The app have following references of Fonr-Awsome

```
    "@fortawesome/fontawesome-svg-core": "^1.2.29",
    "@fortawesome/free-solid-svg-icons": "^5.13.1",
    "@fortawesome/react-fontawesome": "^0.1.11",
```

**Comment by mnavarrocarter** [comment]
https://status.npmjs.org/

**Comment by namik-hajiyev** [comment]
@mnavarrocarter  thank you for your response indeed npm package installation status is "Partial Outage". The  outage was causing that error.
