### ISSUE TITLE
FontAwesome 6 Page Typo

### ISSUE THREAD

**Issue by Gallaghera** [FortAwesome/Font-Awesome#17006]
Hey FontAwesome team! I was looking through your FontAwesome v6 web page and I noticed a typo so I figured I'd share. Thank you so much for all you do!

![image](https://user-images.githubusercontent.com/13204604/89540547-c9f31600-d7c2-11ea-97ee-9b860a75002f.png)

**Comment by frrrances** [comment]
Thanks so much for the heads up! It's all fixed now!
