### ISSUE TITLE
Can't find Billing icon

### ISSUE THREAD

**Issue by krunal8123** [FortAwesome/Font-Awesome#17003]
Can't find Billing icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You mean one of the following?
- https://fontawesome.com/icons/file-invoice?style=solid
- https://fontawesome.com/icons/file-invoice-dollar?style=solid
- https://fontawesome.com/icons/receipt?style=solid

**Comment by krunal8123** [comment]
what's fas ? i have implemented from the given links but can't see any icon.

**Comment by tagliala** [comment]
>what's fas ? 

Font Awesome Solid prefix, introduced in FA5

> i have implemented from the given links but can't see any icon.

could you please clarify?

Docs:
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
