### ISSUE TITLE
Icon request: Google meet icon 

### ISSUE THREAD

**Issue by sabesansathananthan** [FortAwesome/Font-Awesome#17015]
**What can it be used for?**
Most of the people use it for video chat 

**Example image (optional)**
![768px-Google_Hangouts_Meet_icon](https://user-images.githubusercontent.com/36799589/89737851-00b28000-da92-11ea-87f1-001e565c3924.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

I would rename #4045 to google meet to preserve upvotes, given that Hangouts will be eventually shut down

Ref: https://arstechnica.com/gadgets/2019/01/the-great-google-hangouts-shutdown-begins-october-2019/

**Comment by tagliala** [comment]
No feedback, let's use #4045
