### ISSUE TITLE
Direct API calls inside the Icons stops rendering the icons

### ISSUE THREAD

**Issue by darkRaspberry** [FortAwesome/Font-Awesome#17028]
**Describe the bug**
I simply used a Whatsapp icon with whatsapp api. And the icons got lost. Icons doesn't renders.
https://allinoneengclasses.ga/notice.html
See this website's `footer`. It shows only 1 icons as facebook. But it contain 2 icons.
Even in body near the email icon it also contain a another whatsapp icon.

Now go to homepage https://allinoneengclasses.ga/
The same footer shows 2 icons(i have removed conflicting property.).

**To Reproduce**
I used this to render a whatsapp icons and when click it redirect to a link.
`<a href="https://api.whatsapp.com/send?phone=91XXXXXXXXXX&text=&source=&data=&app_absent="><i class="fab fa-whatsapp"></i></a>`

This renders as in Inspect element.

```html
<a href="https://api.whatsapp.com/send?phone=91XXXXXXXXX">
 <svg class="svg-inline--fa fa-whatsapp-square fa-w-14" aria-hidden="true" data-prefix="fab" data-icon="whatsapp-square" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
  <path fill="currentColor" d="M224 122.8c-72.7 0-131.8 59.1-131.9 131.8 0 24.9 7 49.2 20.2 70.1l3.1 5-13.3 48.6 49.9-13.1 4.8 2.9c20.2 12 43.4 18.4 67.1 18.4h.1c72.6 0 133.3-59.1 133.3-131.8 0-35.2-15.2-68.3-40.1-93.2-25-25-58-38.7-93.2-38.7zm77.5 188.4c-3.3 9.3-19.1 17.7-26.7 18.8-12.6 1.9-22.4.9-47.5-9.9-39.7-17.2-65.7-57.2-67.7-59.8-2-2.6-16.2-21.5-16.2-41s10.2-29.1 13.9-33.1c3.6-4 7.9-5 10.6-5 2.6 0 5.3 0 7.6.1 2.4.1 5.7-.9 8.9 6.8 3.3 7.9 11.2 27.4 12.2 29.4s1.7 4.3.3 6.9c-7.6 15.2-15.7 14.6-11.6 21.6 15.3 26.3 30.6 35.4 53.9 47.1 4 2 6.3 1.7 8.6-1 2.3-2.6 9.9-11.6 12.5-15.5 2.6-4 5.3-3.3 8.9-2 3.6 1.3 23.1 10.9 27.1 12.9s6.6 3 7.6 4.6c.9 1.9.9 9.9-2.4 19.1zM400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zM223.9 413.2c-26.6 0-52.7-6.7-75.8-19.3L64 416l22.5-82.2c-13.9-24-21.2-51.3-21.2-79.3C65.4 167.1 136.5 96 223.9 96c42.4 0 82.2 16.5 112.2 46.5 29.9 30 47.9 69.8 47.9 112.2 0 87.4-72.7 158.5-160.1 158.5z">
  </path>
 </svg>
<!-- <i class="fab fa-whatsapp-square" aria-hidden="true"></i> -->
</a>
```

And doesn't show anything.
Direct API calls like above example not work fine.

After replacing with indirect API calls as
`<a href="https://wa.me/91XXXXXXXXXX"><i class="fab fa-whatsapp"></i></a>`
Works fine,

**Expected behavior**
The icon used should render in chrome.
**It works fine with morzilla**

**Screenshots**
![Screenshot (11)_LI](https://user-images.githubusercontent.com/56693429/90061252-8426d800-dd03-11ea-9bf4-ac4b18e980d4.jpg)
![Screenshot (13)_LI](https://user-images.githubusercontent.com/56693429/90061286-90129a00-dd03-11ea-84e6-8de657378a11.jpg)
Taking screenshot in incognito  to remove any cache.

**Version and implementation**
Version: In webkit listed as latest
Browser and version: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Cannot replicate

Chrome / Incoginito / Win 10 / 84.0.4147.105 

![image](https://user-images.githubusercontent.com/556268/90063284-69e00080-dce9-11ea-9d0c-05b0bbe22854.png)

**Comment by darkRaspberry** [comment]
I got the problem.
My extension [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) blocking this icon rendering. And i don't know why thanks again,

And i seriously don't know why [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) has problem with this icon's direct api calls,

**Comment by tagliala** [comment]
> And i seriously don't know why uBlock Origin has problem with this icon's direct api calls,

This is probably due to some denylist that filters out social media icons

Ref: #1799

Closing here
