### ISSUE TITLE
Icon request: data grouping / ungrouping

### ISSUE THREAD

**Issue by wisercoder** [FortAwesome/Font-Awesome#17020]
**What can it be used for?**
Grouping data. Excel has icons for grouping / ungrouping. This is a common operation in data oriented applications. What it does is to group a set of records into groups based on some attributed. For example you can group data by customer, by region, by product, and so on.

**Example image (optional)**
See Excel. Each record can be represented by a horizontal line. These horizontal lines need to be divided into groups or sets.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

> See Excel. Each record can be represented by a horizontal line. 

Could you please provide screenshots of the icons?

**Comment by wisercoder** [comment]
Here's an example for grouping icon:
https://raw.githubusercontent.com/microsoft/fluentui-system-icons/master/assets/Group%20List/SVG/ic_fluent_group_list_24_regular.svg

![image](https://user-images.githubusercontent.com/17690993/101859017-ae589d00-3b1f-11eb-8cb4-cf4fb637b2fb.png)

**Comment by wisercoder** [comment]
Excel's icons look like this:
![image](https://user-images.githubusercontent.com/17690993/101859197-11e2ca80-3b20-11eb-8860-1cc8fee3f6dd.png)

**Comment by tagliala** [comment]
Thanks for the example

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
