### ISSUE TITLE
Icon request: single brackets

### ISSUE THREAD

**Issue by icehaunter** [FortAwesome/Font-Awesome#17022]
**What can it be used for?**
Right now, FontAwesome includes icons for curly and square brackets. Those cannot be used as a single bracket for cases where I'd like to specify the opening/closing of the bracket. For example, we are building a visual builder thing which includes specifying the form of the JSON object. I'd like to make that pretty and explicit via opening and closing curly brackets at the beginning and the end of the block.

I generally found myself needing all three types of brackets (round brackets included, but those are missing even as a non-paired icon when creating formula builders and more.

I don't think we need a matched pair (maybe only for duotone reasons), because the second icon is done via `data-fa-transform="flip-h"` if needed

**Example image (optional)**
This image shows a WIP interface iteration with only "round brackets" (which are done via `far fa-spinner-third` rotated and translated), but this is an example of the interface where I'd like to be able to use any type of bracket

![image](https://user-images.githubusercontent.com/1357760/89882168-1ed1ca80-dbcf-11ea-9527-bbf21df17b9e.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify:
- is this a request for 6 new icons (round-bracket-left, round-bracket-right, square-bracket-left, square-bracket-right, curly-bracket-left, curly-bracket-right)?
- do you have considered to use plain text for this use case?

**Comment by icehaunter** [comment]
@tagliala As I had stated, I think three icons could be plenty (singular bracket for each case)

Plain-text could be a solution for me, but, considering I am using basic mathematical operations from the FontAwesome (`fa-plus`, `fa-times`, and others from the mathematics set), I'd like for them to be stylistically similar. I could switch them all to plaintext, but then what's the point of having mathematics set in the first place.

**Comment by sensibleworld** [comment]
I think these would be a great addition, and the use-case makes sense.

**Comment by icehaunter** [comment]
I was most surprised to see the round brackets missing, as they are the only thing missing from the maths package to actually represent formulas. I mean, I could use reverse polish notation, but that is just slightly non-intuitive :D

**Comment by sensibleworld** [comment]
This icon is now available as part of the version 6 alpha: https://fontawesome.com/download
