### ISSUE TITLE
calendar-plus shows as camera in iOS

### ISSUE THREAD

**Issue by nickdnk** [FortAwesome/Font-Awesome#17039]
**Describe the bug**
https://fontawesome.com/icons/calendar-plus?style=regular renders as https://fontawesome.com/icons/camera?style=regular on native iOS.

**To Reproduce**
Import newest OTF files (5.14.0) into iOS, register fonts etc., create a label and set its text to the value of the icon and its font to FontAwesome. Observe that the icon is wrong. In our case this happens with the title attribute of a BarButtonItem.

I checked that the icon is actually F271 () by doing some search-matching in the sourcecode, and in all cases it does match the icon called calendar-plus. I should note that all other icons that we use work as expected. This is not a case of a bad copy/paste.

**Expected behavior**
I would like for it to render calendar plus and not the camera.

**Version and implementation**
Version: 5.14.0
Browser and version: iOS 13.5.1

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [X] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

I cannot check this, leaving this open for feedback from the community

**Comment by nickdnk** [comment]
Hello

It seems this was a bug in XCode. We had an enum list of strings mapped to icons, but for some reason when changing this list, if you don't do a proper clean/build and/or remove derived data, the enums will map to the wrong icons and give weird/unpredictable results when the application runs, sometimes even crashing it. I don't think this is a bug with FontAwesome. I will confirm tomorrow and close the issue if XCode is to blame.

**Comment by tagliala** [comment]
Thanks for the heads-up! Let us know

**Comment by nickdnk** [comment]
I can confirm that this was a clean/build issue.
