### ISSUE TITLE
Cant use icon "fa-percent"

### ISSUE THREAD

**Issue by RobinGL** [FortAwesome/Font-Awesome#17030]
Hey there,

if I click "Start using this Icon" fontawesome.com will export this snippet like `<i class="fas fa-percent"></i>`
But it just works with  `<i class="fa fa-percent"></i>`

Greets :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here

**Comment by RobinGL** [comment]
Hey, damn sorry for this :sweat_smile: 
Thank's for explaining this.
