### ISSUE TITLE
RSS icons seem to be broken

### ISSUE THREAD

**Issue by OrangeDog** [FortAwesome/Font-Awesome#17038]
**Describe the bug**
None of the RSS icons are displaying. They seem to be missing from the css.

**To Reproduce**
https://fontawesome.com/icons?d=gallery&q=rss

On that site I get a couple of logs in the console, but not on my own site.
```
downloadable font: maxp: Bad maxZones: 0 (font-family: "t" style:normal weight:400 stretch:100 src index:0) source: data:application/font-woff2;base64,d09GMgABAAAAAADcAAoAAAAAAggAAACWAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABk4ALAoUNAE2AiQDCAsGAAQgBSAHI … /xIBBqq61FIQRJhC/+QA/08PJQJ3sK5TZFMlWzC/iK5GUN40psgqvxwBjBOg6JUSJ7ewyKE2AAaXZrfUB4v+hze37ugJ9d+DeYqiDwVgCawviwVFGnuttkLqIMGivmDg
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:798679
```

**Expected behavior**
These icons should appear.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/675056/90237573-6731f800-de1c-11ea-82b5-d11a34c9d204.png)

**Version and implementation**
Version: 5.14.0
Browser and version: Firefox 79.0

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate from EU - Italy

Could you please try in an incognito window, without extensions?

Also, this could be related to region and provider. Could you please tell us from where you are connecting from?

**Comment by OrangeDog** [comment]
Turns out ublock origin was blocking it, via "Fanboy's Annoyance" list.
He really doesn't like RSS buttons for some reason.
