### ISSUE TITLE
Icon request: hands-graduation-cap (academic-support)

### ISSUE THREAD

**Issue by glisczni** [FortAwesome/Font-Awesome#17033]
**What can it be used for?**
Colleges and universities could use it to indicate support services they offer such as tutoring, study groups, mentorship programs, etc.

**Example image (optional)**
Hands holding a graduation cap or mortar
![image](https://user-images.githubusercontent.com/69652475/90187270-23d57c00-dd7f-11ea-9b84-16072efcd0b9.png)

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/436/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

https://fontawesome.com/icons/graduation-cap?style=solid
https://fontawesome.com/icons/hands?style=solid

**Comment by glisczni** [comment]
Excellent! Thank you!

Nicole Glisczinski
Digital Experience Manager
Fox Valley Technical College
glisczni@fvtc.edu<mailto:glisczni@fvtc.edu>
920-225-5935

Fox Valley Tech is moving forward with a full set of offerings using remote and in-person instruction to ensure your safety and success. Learn more: http://www.fvtc.edu/Forward.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
