### ISSUE TITLE
Icons not display depending of computers

### ISSUE THREAD

**Issue by mariangio** [FortAwesome/Font-Awesome#17058]
**Describe the bug**
Depending of which computer or phones I try to see the icones on my website, sometimes it is displayed, sometimes there are square instead of the icones. I have already clear the caches in all the supports but still same problem/

**To Reproduce**
www.viviennalorikeet.com.au
The icons on the menu, as well as the products page, are not always displayed.

I have relinked the pack of fontawesome to my website and still the same problem. I have checked if there is any conflict with previous versions I would not be aware but no error.

Thanks for your help!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please check your browser's development console:

```
Uncaught SyntaxError: Unexpected token '<'
```

I can see that your website is trying to load font awesome inside a javascript with an HTML tag

```
<script src="https://kit.fontawesome.com/8361a508ea.js" crossorigin="anonymous">
```

This is supposed to be in the `<head>` of the HTML document

Hope it helps

Closing here

**Comment by mariangio** [comment]
Thanks Tagliala. I removed it from there . I have a PHP file as it is a wordpress. I believe that is the same as an html as I don't have Html file. Am I right?

**Comment by tagliala** [comment]
Welcome

> . I have a PHP file as it is a wordpress.

We have an official wordpress plugin: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress

> I believe that is the same as an html as I don't have Html file. Am I right?

Correct, you should edit header PHP file, but it is better to integrate in WordPress's head scripts/assets (instructions and support are out of the scope of this repo, sorry)

**Comment by mariangio** [comment]
Thanks Tagliala. I have actually already a file called font-awesome.min.css already in my file.
I am not sure why it needed a new script. I removed the script above and still not working. I could use the plugin but I am afraid it will upset the file font-awesome.min.css that is already in there. Would it?
