### ISSUE TITLE
Icon Request: icon-paragraph/icon-section (law) 

### ISSUE THREAD

**Issue by greq7** [FortAwesome/Font-Awesome#1706]
there is already a legal-icon: "icon-legal" 
(http://fortawesome.github.io/Font-Awesome/icon/legal/)

Would be nice if there would be also a paragraph-icon: "icon-paragraph"
like <b>§</b>

**Comment by szegheo** [comment]
+1

**Comment by dennym** [comment]
+1

How many plus one has to happen that the icon gets implemented?

**Comment by tagliala** [comment]
@dennym +1s help us to keep track of most requested icons: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+sort%3Acomments-desc

Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by otmezger** [comment]
+1

**Comment by pergerch** [comment]
+1

**Comment by dakira** [comment]
+1

**Comment by tuxy** [comment]
+1

**Comment by melino** [comment]
+1

**Comment by AlexanderPilhar** [comment]
+1

**Comment by craftbyte** [comment]
+1

**Comment by mcmz** [comment]
+1

**Comment by LevelZwo** [comment]
+1

**Comment by phaldan** [comment]
+1

**Comment by saintjon** [comment]
+1

**Comment by eX00r** [comment]
+1 for the §

**Comment by DankoHR** [comment]
+1

**Comment by danielehrhardt** [comment]
+1

**Comment by Opalo** [comment]
+1

**Comment by foxacid** [comment]
+1 using custom HTML or CSS pseudo-elements is not always an option.

**Comment by lonesomewalker** [comment]
+1

**Comment by bloxberg** [comment]
+1 for § -> heavily needed

any predicitions when the sign will be added?!

**Comment by sfischer13** [comment]
+1

**Comment by saintjon** [comment]
+1

**Comment by Codecamv** [comment]
+1

**Comment by bamboohome** [comment]
+1

**Comment by jupath** [comment]
+1

**Comment by christianwgd** [comment]
+1

**Comment by shaedrich** [comment]
+1

**Comment by cg001** [comment]
+1

**Comment by Jennymarthine** [comment]
+1

**Comment by DR4RCON** [comment]
+1

**Comment by cenkdominic** [comment]
+1

**Comment by Nikdro** [comment]
+1

**Comment by Syr3L** [comment]
+1

**Comment by KingDumah** [comment]
+1

**Comment by MCStreetguy** [comment]
+1

**Comment by ethan1saacson** [comment]
+1

**Comment by Evohwoo** [comment]
+1

**Comment by SKHirsch** [comment]
+1

**Comment by K3ll06s** [comment]
+1

**Comment by yurianu** [comment]
+1

**Comment by lollolgag** [comment]
+1

**Comment by Spixx90** [comment]
+1

**Comment by Neuronauten** [comment]
+1

**Comment by febsn** [comment]
+1

**Comment by 5plus12** [comment]
+1

**Comment by CountCount** [comment]
+1

**Comment by georg-tiefenbrunn** [comment]
+1

**Comment by helenekr** [comment]
+1

**Comment by Butz85** [comment]
+1

**Comment by Qrzysio** [comment]
+1

**Comment by shaedrich** [comment]
This would also offer a new (layered) icon: fa-law/fa-code-legal (fa-paragraph + fa-book-alt)

![vectorpaint-_1_](https://user-images.githubusercontent.com/11225821/69042306-45245a00-09f1-11ea-8919-7cf296f927bb.png)

**Comment by grantejohnson** [comment]
+1

**Comment by tomas-eklund** [comment]
+1

**Comment by tomas-eklund** [comment]
This symbol is also known as section symbol, section mark, double-s or silcrow - for anyone searching, I'm quite surprised it still isn't added. Where I live this is THE symbol to represent a legal text, statutes or similar. It would be very useful.

**Comment by M-B89** [comment]
+1

**Comment by elvisgraho** [comment]
+1

**Comment by gastlich** [comment]
+1

**Comment by TheNaderio** [comment]
2020 and still no § icon?
is there a reason why this icon is not included?

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
