### ISSUE TITLE
Icon request: fab fa-bulma => Bulma.io logo, 40k+ stars on Github. With svg code.

### ISSUE THREAD

**Issue by hugolpz** [FortAwesome/Font-Awesome#17077]
Bulma project has 40k+ stars on Github, see : https://github.com/jgthms/bulma

Bootstrap project has 144k+ stars on Github, see: https://github.com/twbs/bootstrap
@FontAwesome has a Bootstrap icon : https://fontawesome.com/icons/bootstrap?style=brands

**What can it be used for?**
Like for the  Bootstrap icon, for the undred thousands websites using the Bulma CSS framework.

**Example image (optional)** : 
* https://jsfiddle.net/2xkbovtg/1/ -- jsfiddle
![Screenshot_2020-08-25_11-23-43](https://user-images.githubusercontent.com/1420189/91157332-7723c480-e6c5-11ea-9849-49cf4a27cbef.png)
![Screenshot_2020-08-23_14-57-08](https://user-images.githubusercontent.com/1420189/91157358-8145c300-e6c5-11ea-9ed0-5a56f606ee99.png)

```
<svg width="220px" height="320px" viewBox="0 0 220 320" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <polygon points="0 220 20 80 100 0 200 100 140 160 220 240 100 320" fill="#00D1B2"></polygon>
</svg>
```

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate. Duplicate of #13076, which was not properly written nor argued for.
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this well written request.

> Duplicate of #13076, which was not properly written nor argued for.

For requests like this, it is fine to not fill out the template, because the request is self-explanatory and straightforward.

Let's keep using #13076, so we can preserve upvotes and comments there

Closing here
