### ISSUE TITLE
We can have access to the pro icons without buying a pro pack( in free account )

### ISSUE THREAD

**Issue by saroj-dev** [FortAwesome/Font-Awesome#17082]
edited by @tagliala

**Comment by tagliala** [comment]
Hi @saroj-dev , thanks for reporting this

I've sent an email to hello@fontawesome.com, I think it is a better way to report issues like this

Let's wait for some feedback

**Comment by saroj-dev** [comment]
ok thanks sir i was wondering the issue like this is not ideal to post
publicly thanks sir..

**Comment by robmadole** [comment]
Thanks for the report @saroj-dev ! The issue that you reported is a known problem and we are actively working to remedy it. I'm going to close this issue but thanks again for taking the time.
