### ISSUE TITLE
401 Unauthorized installing FontAwesome free edition in GitHub Actions workflow

### ISSUE THREAD

**Issue by jsakas** [FortAwesome/Font-Awesome#17085]
**Describe the bug**

I cannot `yarn install @fortawesome/fontawesome-free` in a GitHub actions environment.

**To Reproduce**

Here is a repository with a package json with a single dep, with an actions workflow with only a yarn install:

https://github.com/jsakas/fa-free-test

Here is the failed workflow:

https://github.com/jsakas/fa-free-test/runs/1033072186?check_suite_focus=true

Here is the error:

```
yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.14.0/fontawesome-free-5.14.0.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/fa-free-test/fa-free-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]Process completed with exit code 1.
```

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**

I should be able to install font awesome free in my repository as part of CI.

**Version and implementation**
Version: 5.14
Browser and version: N/A

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi,

I think there is an `.npmrc` somewhere on your local machine that downloaded Font Awesome's free package from `npm.fontawesome.com`, which is our private repo.

Please try to remove yarn.lock and retry, the file should be downloaded from the public yarn registry `registry.yarnpkg.com`.

I'm pretty confident this is the issue, so I'm going to close here, but feel free to comment

**Comment by jsakas** [comment]
@tagliala removing the yarn.lock worked as a test, but how does one fix this in a project without deleting the lock file? Keeping the lock file in the repo is important.

I have a pro account and was set my npm config up according to the docs. There are some open source projects I have that want to use the font awesome free package. So I need to be able to work on those projects and yarn install without making them unusable for other people.

I think this issue has been closed too early as "deleting the lock file" is not really a solution. As soon as I yarn install again, the incorrect registry is used.  If I delete `~/.npmrc`, and also run `npm config delete @fortawesome:registry && npm config delete //npm.fontawesome.com/:_authToken` I cannot install even the free version:

```
yarn add @fortawesome/fontawesome-free
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-free: authentication required".
```

**Comment by tagliala** [comment]
Hi @jsakas 

> Keeping the lock file in the repo is important.

So you should fix locally, configuring `.npmrc` that downloads Font Awesome from the Free Repo, even if you are a Pro customer and you have globally set the Pro Repo.

You can achieve that with the following `.npmrc`:

```
@fortawesome:registry=
```

Does this help?

**Comment by justinIs** [comment]
Hey @tagliala I've tried your solution with the npmrc file but no luck, I still get

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffree-solid-svg-icons: authentication required".
```

**Comment by tagliala** [comment]
It is still trying to download from the private npm repository, yarn is not honoring the configuration file.

Is this file manually edited? I can see the proper public repo here: https://github.com/jsakas/fa-free-test/blob/master/yarn.lock

**Comment by justinIs** [comment]
I see, I just updated my `.npmrc` file to have
```
@fortawesome:registry=https://registry.yarnpkg.com
```
and the install worked.  Is this expected though? shouldn't it just go there by default?

**Comment by tagliala** [comment]
> and the install worked. Is this expected though? shouldn't it just go there by default?

This is surprising for me, I should check, but I'm not on my development machine at the moment

yarn version?

**Comment by jsakas** [comment]
> and the install worked. Is this expected though? shouldn't it just go there by default?

I was wondering the same thing - seems like it gets stored/cached somewhere. Just not sure where.

**Comment by justinIs** [comment]
```
yarn --version
1.22.4

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
```

I wonder if there's some caching somewhere. I had npmrc configured for pro recently...

**Comment by tagliala** [comment]
Try with 

```
yarn config list
```

If you see

```
  '@fortawesome:registry': 'https://npm.fontawesome.com/',
```

Then it is not good.

If you see 

```
  '@fortawesome:registry': '',
```

In my case it falls back to the default registry  `registry: 'https://registry.yarnpkg.com',`

**Comment by jsakas** [comment]
@tagliala thanks. 

This also resolved the issue for me:

```
npm config set "@fortawesome:registry" https://registry.yarnpkg.com
```
