### ISSUE TITLE
Free Icons require authentication for npm registry

### ISSUE THREAD

**Issue by justinIs** [FortAwesome/Font-Awesome#17088]
**Describe the bug**
I am trying to add some of the free icons (@fortawesome/free-solid-svg-icons, @fortawesome/free-brands-svg-icons ) to my app. When I try to `yarn add` them, I get an `authentication required` error

But 

**To Reproduce**
```
yarn add @fortawesome/free-solid-svg-icons @fortawesome/free-brands-svg-icons  -D
```
output:
```
yarn add v1.22.4
warning package.json: No license field
warning ... No license field
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffree-solid-svg-icons: authentication required".
info If you think this is a bug, please open a bug report with the information provided in "..."
```

It seems like the `free-solid-svg-icons` are requiring authentication. Is this expected? Do I need to have a pro license to use that package?

**Expected behavior**
It should install free icons without requiring authentiation

**Version and implementation**
Version: trying to install latest version of the package

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It's the same issue described here: https://github.com/FortAwesome/Font-Awesome/issues/17085#issuecomment-681065874

Closing here, but feel free to comment
