### ISSUE TITLE
GT Metris Results

### ISSUE THREAD

**Issue by webuser20** [FortAwesome/Font-Awesome#17084]
Hi, I have ran GT Metrix and get errors when reviewing the waterfall (attached screenshot). Any help would be appreciated. Thanks

https://371390-1161228-raikfcquaxqncofqfm.stackpathdns.com/wp-content/plugins/elementor/assets/lib/font-awesome/webfonts/fa-solid-900.woff2 | (failed) | 371390-1161228-raikfcquaxqncofqfm.stackpathdns.com | 0 | 294.7ms |  
-- | -- | -- | -- | -- | --
fa-brands-400.woff2 | (failed) | 371390-1161228-raikfcquaxqncofqfm.stackpathdns.com | 0 | 293.3ms |  
fa-brands-400.woff | (failed) | 371390-1161228-raikfcquaxqncofqfm.stackpathdns.com | 0 | 178.9ms |  
fa-solid-900.woff | (failed) | 371390-1161228-raikfcquaxqncofqfm.stackpathdns.com | 0 | 178.9ms |  
analytics.js | 200 | google-analytics.com | 18 KB | 25.7ms |  
hotjar-1646363.js?sv=7 | 200 | static.hotjar.com | 1.8 KB | 82.3ms |  
fa-brands-400.ttf | (failed) | 371390-1161228-raikfcquaxqncofqfm.stackpathdns.com | 0

![fonts](https://user-images.githubusercontent.com/69789579/91338893-8beb7f80-e7cd-11ea-8f54-35d9744b6d8e.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It looks like that you are using Font Awesome through a wordpress plugin called "Elementor".

We do not provide support for third-party plugins/applications and self-hosting configuration

We have an official plugin for Wordpress: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress

Hope it helps

Closing here
