### ISSUE TITLE
Icon request: ORCID iD

### ISSUE THREAD

**Issue by marcovolino** [FortAwesome/Font-Awesome#17090]
**What can it be used for?**
"ORCID provides a persistent digital identifier (an ORCID iD) that you own and control, and that distinguishes you from every other researcher. You can connect your iD with your professional information — affiliations, grants, publications, peer review, and more. You can use your iD to share your information with other systems, ensuring you get recognition for all your contributions, saving you time and hassle, and reducing the risk of errors."
https://orcid.org/

**Example image (optional)**
![image](https://user-images.githubusercontent.com/6390901/91487824-46e74c00-e8a6-11ea-962e-2763eeee20f1.png)
Icon preview - https://orcid.figshare.com/ndownloader/files/8439047/preview/8439047/preview.jpg
Icon Library - https://orcid.figshare.com/articles/ORCID_iD_icon_graphics/5008697

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

orcid is already here: https://fontawesome.com/icons/orcid?style=brands

Make sure that you are using Font Awesome >= 5.11.0

Closing here

**Comment by jantaratkss** [comment]
Ss

ดาวน์โหลด Outlook for iOS<https://aka.ms/o0ukef>
________________________________
จาก: Geremia Taglialatela <notifications@github.com>
ส่ง: Friday, August 28, 2020 2:58:03 AM
ถึง: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
สำเนาถึง: Subscribed <subscribed@noreply.github.com>
ชื่อเรื่อง: Re: [FortAwesome/Font-Awesome] Icon request: ORCID iD (#17090)


Closed #17090<https://github.com/FortAwesome/Font-Awesome/issues/17090>.
