### ISSUE TITLE
Including Duotone CSS only will only apply secondary icon half

### ISSUE THREAD

**Issue by 1stKarkan** [FortAwesome/Font-Awesome#17096]
**Describe the bug**
I wanted to add Font Awesome by CSS while only adding Duotone icons. But when only importing the duotone.css file in my HTML, solely the secondary part of each icon gets rendered. This is due to the ::before element of Duotone icons is not set in the duotone.css.

**To Reproduce**
To reproduce, simply only link the duotone.css in you HTML file and use any icon like:` <i class="fad fa-kiwi-bird"></i>`

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" type="text/css" href="/fa/css/duotone.css">

    </head>
    <body>
        <i class="fad fa-kiwi-bird"></i>
    </body>
</html>
```

**Expected behavior**
While it is useful to only add the secondary-half of the icon with the duotone, when other Font Awesome files are also loaded, there should be an option to load everything that is necessary to display duotone icons within only a single file.
Is it possible to add a webfont/css-file for the case of only loading duotone icons specifically?

**Version and implementation**
Version: 5.14.0
Using the duotone.css

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot verify at the moment, but you should still need to import both `fontawsome.css` and `duotone.css`

Ref: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#additional-styling-options

Let me know

**Comment by 1stKarkan** [comment]
Hello!

I'm sorry for my confusion, you are right :+1:
