### ISSUE TITLE
Icon Request: icon-mortar-pestle

### ISSUE THREAD

**Issue by jamesakers** [FortAwesome/Font-Awesome#1709]
I think something similar to this would be a good addition to the medical icons. Keep up the good work!

![mortar_and_pestle-512](https://f.cloud.github.com/assets/1858/902743/c536ac1a-fb9e-11e2-9368-4877b91d7079.png)

**Comment by cguzman1028** [comment]
+1

**Comment by eddieebeling** [comment]
+1

**Comment by Benqzq** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mortar-pestle?style=solid
