### ISSUE TITLE
SCSS Bug: Items after \f0ea not rendered

### ISSUE THREAD

**Issue by NNi23** [FortAwesome/Font-Awesome#1710]
I've integrated font-awesome scss into my project. At first glance it worked fine, but then some items were not rendered. I found out, that all items up to \f0ea are rendered properly, all items after \f0ea were not. 

Happens in IE10, FF, Chrome (all i tested).

Any idea?

**Comment by bsara** [comment]
My guess is how the characters are referenced in the SCSS files. It can be really touchy. are you still seeing this issue?

**Comment by essobasha** [comment]
please help me font awesome is awesome 
every font render fine inside website but  :after     not working home page  appear the content code not icon f0d7  i'dont able to solve it .

**Comment by dtrunk90** [comment]
Same here. Using JAWR and SCSS version of FontAwesome I can only see the content code. The font is loaded properly (network debugger). CSS version is working well. Reference: https://github.com/j-a-w-r/jawr-main-repo/issues/49

**Comment by sensibleworld** [comment]
If folks are still having rendering issues, could you open a new issue with specific details and code examples? Thanks!
