### ISSUE TITLE
"far fa-check" is added and copied as "far fa-check"

### ISSUE THREAD

**Issue by UthaiahBollera** [FortAwesome/Font-Awesome#17101]
https://fontawesome.com/icons/check?style=regular
There is a spelling mistake in copy as HTML. Instead of **fa-check** it shows and copies **far-check**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fas`/`far`/`fab` aren't typos 😀

Please take a look at our documentation to understand how style prefixes work in Font Awesome 5:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
