### ISSUE TITLE
'drone' light-style is skewed/thicker in the bottom-left corner

### ISSUE THREAD

**Issue by chrisnicholson** [FortAwesome/Font-Awesome#17106]
**Describe the bug**
The 'drone' icon, 'light' version is slightly larger/chunkier in the bottom left corner. This causes the drone blades/propellers to fall outside the bounds of the canvas.

**To Reproduce**
Clipping is clearly visible on the FontAwesome website: https://fontawesome.com/icons/drone?style=light
It's also possible to see the slightly increased thickness of the blade.

**Expected behavior**
I would expect the propeller circles to be equal in all four corners.

**Screenshots**
FontAwesome website:
![drone-capture](https://user-images.githubusercontent.com/5024027/91909486-37e90b00-eca5-11ea-9eee-d5120562b2ba.PNG)

Photoshop guidelines:
![drone-capture-ps](https://user-images.githubusercontent.com/5024027/91909741-a928be00-eca5-11ea-90c4-3d00eaeba9e1.PNG)

**Version and implementation**
Version: 5.14.0
Browser and version: Chrome 84

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This is fixed in the v6 alpha: http://fontawesome.com/download

**Comment by chrisnicholson** [comment]
@sensibleworld will this fix be made available in v5? We cannot commit to v6 in its alpha state - let alone the fact we may not purchase v6 (no decision made yet). It would be a shame for all v5 users to be stuck with an obvious bug.

**Comment by sensibleworld** [comment]
Yup, sorry. Been heads down on v6 work, but will get this fix in the queue for v5.

**Comment by tagliala** [comment]
Reopened for tracking purposes

**Comment by sensibleworld** [comment]
This is fixed as of the most recent release: https://fontawesome.com/v5.15/icons/drone?style=light
