### ISSUE TITLE
Icon request: icon-javascript (icon-js)

### ISSUE THREAD

**Issue by hoobdeebla** [FortAwesome/Font-Awesome#1711]
There are already Font Awesome icons for HTML5 and CSS3, so one for JS would be logical. Something based on the [community JavaScript logo](https://github.com/voodootikigod/logo.js) would be awesome. Maybe an alt for the icon would be the [specific use case logo](https://github.com/voodootikigod/logo.js/tree/master/specific-uses) from the repository mentioned above to go better with the existing HTML5 and CSS3 icons.

**Comment by v0009** [comment]
+1

**Comment by Trackhe** [comment]
+1

**Comment by cyrilschumacher** [comment]
+1

**Comment by rubenprins** [comment]
+1

**Comment by acarl005** [comment]
+1

**Comment by vmasto** [comment]
+1 for all programming languages (like this awesome icomoon set from codewards.com http://d.pr/i/1lAJ6)

**Comment by xdumaine** [comment]
+1

**Comment by kostasx** [comment]
+1

**Comment by G33kman** [comment]
+1

**Comment by bomb-on** [comment]
+1 for all the geeky stuff :)
also, font-mfizz doesn't seem to be maintained anymore, the syntax follows old FA namespace and icons are in a bit offset from FA icons (visible when you use them together, one next to each other)

**Comment by mfulham** [comment]
+1

**Comment by akapa** [comment]
+1

**Comment by chrisvfritz** [comment]
+1

**Comment by TJohnson93** [comment]
+1

**Comment by ecksteing** [comment]
+1

**Comment by ChoiZ** [comment]
+1

**Comment by antimatter96** [comment]
+1

**Comment by Xawier** [comment]
+1

**Comment by carltonstith** [comment]
+1

**Comment by ashleighy** [comment]
+1

**Comment by gastongouron** [comment]
+1

**Comment by EoghainC** [comment]
+1 and +1 for PHP, jQuery

**Comment by josephdubon** [comment]
+1 and +1 for jQuery

**Comment by marrokin** [comment]
+1
+1 icons for  JS, JQUERY, NODE, PHP, RUBY, PYTHON, JADE, SASS, SCSS, STYLUS, REACTJS, MONGO, MYSQL, GULP, GRUNT

**Comment by SamBrishes** [comment]
+1

**Comment by Suryanarayanamurthy** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by stijnvanbael** [comment]
+1

**Comment by richcahill** [comment]
+1

**Comment by CalebGrove** [comment]
+1

**Comment by johnbendi** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Caleb GroveSent: Wednesday, December 9, 2015 7:09 PMTo: FortAwesome/Font-AwesomeReply To: FortAwesome/Font-AwesomeSubject: Re: [Font-Awesome] Icon request: icon-javascript (icon-js) (#1711)+1

—Reply to this email directly or view it on GitHub.

**Comment by Bamuel** [comment]
+1

**Comment by jaimemyers** [comment]
+1

**Comment by phbo85** [comment]
+1

**Comment by RandomlyKnighted** [comment]
+1 any chance this will be implemented soon?

**Comment by marathia** [comment]
+1

**Comment by fabiangigler** [comment]
+1

**Comment by Crecket** [comment]
+1, still waiting for this

**Comment by paulstam** [comment]
+1

**Comment by jasonkhanlar** [comment]
+1

**Comment by danteangels** [comment]
+1

**Comment by TMMC** [comment]
+1

**Comment by faridlab** [comment]
+1

**Comment by Zimcod** [comment]
+1 plz

**Comment by knightknight** [comment]
+1

**Comment by levlas** [comment]
+1

**Comment by CheeseAndToasted** [comment]
+1

**Comment by tonyporto** [comment]
+ 10

**Comment by tonyporto** [comment]
+1

**Comment by Guichaguri** [comment]
+1

**Comment by groundberry** [comment]
+1

**Comment by miche-atucha** [comment]
+1

**Comment by ThatGuySamUK** [comment]
+1

**Comment by no81no** [comment]
+1

**Comment by evanre** [comment]
+1

**Comment by Ardakilic** [comment]
+1

**Comment by monkeym4ster** [comment]
+1

**Comment by egfx** [comment]
+1

**Comment by mcombellick** [comment]
+1

**Comment by NeonMonk** [comment]
+1

**Comment by jefflivsky** [comment]
+1

**Comment by Jmateus88** [comment]
+1

**Comment by alsoknownasdrew** [comment]
+1

**Comment by ihinckle** [comment]
+1

**Comment by celamb4** [comment]
+1 icons for JS, JQUERY, NODE, PHP, RUBY, PYTHON, JADE, SASS, SCSS, STYLUS, REACTJS, MONGO, MYSQL, GULP, GRUNT

**Comment by fabiangigler** [comment]
Hi, 

I've decided to spend  a  couple of days in camping, just take a  look at that place <http://light.clinicaloptics.com/lnwnzoo>

Warm regards, fgigler

**Comment by fabiangigler** [comment]
Hi, 

I've  been looking for some information  and came across these nice articles, they ma be helpful for you.You may read  them here <http://friend.primarymusicsource.com/lnnvsmv>

Cheers, fgigler

**Comment by CrixtiaN** [comment]
+1

**Comment by shaunsational** [comment]
+1

**Comment by SleekDevigner** [comment]
+1

**Comment by natGalynker** [comment]
+1

**Comment by marcusjanke** [comment]
+1

**Comment by kajensen** [comment]
http://devicon.fr/

**Comment by DrMajkrosoft** [comment]
+1

**Comment by Binternet** [comment]
+1

**Comment by ButTheRegrets** [comment]
+1

**Comment by swaters86** [comment]
+1. The Font Awesome team said there will be a JS icon and other icons for other frameworks and languages in Font Awesome 5 after I asked them this on Twitter.  In case you haven't heard already, they are raising money for this new version of Font Awesome here: https://www.kickstarter.com/projects/232193852/font-awesome-5?ref=card

**Comment by prahladyeri** [comment]
+1

**Comment by tbsvttr** [comment]
+1

**Comment by sjclayton** [comment]
+1

**Comment by mahi13c** [comment]
+1

**Comment by huskycdn** [comment]
+1

**Comment by lffg** [comment]
+1

**Comment by jhalls** [comment]
+1

**Comment by gdlm91** [comment]
+1

**Comment by linusg** [comment]
Same, +1

**Comment by pknad505** [comment]
+1

**Comment by shayeglin** [comment]
+1

**Comment by JustineWin** [comment]
+1

**Comment by MateuszKawka** [comment]
Im hungryy +1

**Comment by asazs** [comment]
+1

**Comment by asazs** [comment]
+1

**Comment by kwendenarmo** [comment]
This is now available in Font Awesome 5 beta-2

**Comment by wmellema** [comment]
@kwendenarmo Could you point out where we can find this? I've searched for it, but can't find the specific branch or commit where it's added....

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by adsingh14** [comment]
Is there any plan to add these icons in v4.7 ?

**Comment by tagliala** [comment]
@adsingh14 no, there aren't.

Sorry, 4.7 is in EOL
