### ISSUE TITLE
Icon request: snapchat-outline

### ISSUE THREAD

**Issue by denete** [FortAwesome/Font-Awesome#17115]
**What can it be used for?**
An outline-only icon would meet the current brand guidelines for Snapchat.
https://www.snap.com/en-US/brand-guidelines

**Example image (optional)**
![Ghost Logo (for dark backgrounds)](https://user-images.githubusercontent.com/214807/92130200-74665500-edd2-11ea-9532-fb87ae1a9ca2.png)
![Ghost Logo (for light backgrounds)](https://user-images.githubusercontent.com/214807/92130201-74665500-edd2-11ea-806c-6653a7311e14.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

So ghosts in 

- https://fontawesome.com/icons/snapchat-ghost?style=brands
- https://fontawesome.com/icons/snapchat-square?style=brands
- https://fontawesome.com/icons/snapchat?style=brands

should be turned into an Outline

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
