### ISSUE TITLE
New Icon Request - States! Like the 50 United States, an icon for each. fa-nevada

### ISSUE THREAD

**Issue by GhostBoulton** [FortAwesome/Font-Awesome#17116]
Wouldn't it be great to be able to say fa-california ?   I need it for California privacy laws. More laws coming so we'll need all the states.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment, I'm closing all requests about country silhouettes because they are out of scope

Ref: #3992

Closing here
