### ISSUE TITLE
Icon request: washing-machine  Washing instructions (washing machine, dryer, iron) 

### ISSUE THREAD

**Issue by bubalina** [FortAwesome/Font-Awesome#17114]
**What can it be used for?**
For washing instructions, Examples include heat resistant up to 100ºC, machine wash cold, do not dryclean, iron on low, etc etc 

**Example image (optional)**
![washing-machine-icon-vector-23806090](https://user-images.githubusercontent.com/70701167/92113461-94831d80-edac-11ea-9653-fe9cba8cc0ce.jpg)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, cannot allow requests for icon set in the free repo.

If you are a Font Awesome Pro customer, you can request icon sets in the Font Awesome Pro repository at https://github.com/FortAwesome/Font-Awesome-Pro?

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
