### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by ezrakelly** [FortAwesome/Font-Awesome#17131]
**What can it be used for?**
Social media
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.(Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a plenty of Facebook icons:
- https://fontawesome.com/icons/facebook-f?style=brands
- https://fontawesome.com/icons/facebook?style=brands
- https://fontawesome.com/icons/facebook-square?style=brands
- https://fontawesome.com/icons/facebook-messenger?style=brands

If you don't see those, please make sure that you don't have ad blocker blocking social icons
