### ISSUE TITLE
Icon Request: fa-broken-heart

### ISSUE THREAD

**Issue by dudarts** [FortAwesome/Font-Awesome#17135]
https://www.google.com/imgres?imgurl=https%3A%2F%2Ff0.pngfuel.com%2Fpng%2F552%2F776%2Fbroken-heart-computer-icons-broken-heart-png-clip-art.png&imgrefurl=https%3A%2F%2Fwww.pngfuel.com%2Ffree-png%2Fnelfi&tbnid=93OvNRXGsUX9xM&vet=10CCkQMyh5ahcKEwi43frsrN_rAhUAAAAAHQAAAAAQAg..i&docid=f6JDEnCceQs0JM&w=910&h=512&itg=1&q=broken%20heart%20icon&hl=pt-BR&ved=0CCkQMyh5ahcKEwi43frsrN_rAhUAAAAAHQAAAAAQAg

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have this: https://fontawesome.com/icons/heart-broken?style=solid

Please make sure that you are using Font Awesome >= 5.10.2
