### ISSUE TITLE
squarespace icon not loading

### ISSUE THREAD

**Issue by ryanbuckleyca** [FortAwesome/Font-Awesome#17140]
I've been using the <i class="fab fa-squarespace"></i> tag but the icon isn't loading, although others have been working fine.

I've also tried <i class="fa fa-squarespace"></i> (using fa instead of fab, as it works for others) but still no dice.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Squarespace has been introduced in Font Awesome 5.1.0: https://fontawesome.com/icons/squarespace?style=brands

My best guess is that you are using an older version of Font Awesome. Please note that there could be third-party plugins/themes/libraries loading an older version that may have priority over yours one.

If you still think this is a problem with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Closing here
