### ISSUE TITLE
Accessible-icon not working

### ISSUE THREAD

**Issue by schinowsky** [FortAwesome/Font-Awesome#17146]
**Describe the bug**
I tried to insert the accessible-icon into my webpage and it came up as a blank box. Other icons work perfectly fine. I know I'm typing the name correctly because if I introduce a typo, the blank box goes away entirely. 

**Screenshots**
![image](https://user-images.githubusercontent.com/71287301/93125422-b88a0d00-f690-11ea-8033-55a41019a0c2.png)

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [x ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`accessible-icon` is a brand, please try with `fab` prefix

https://fontawesome.com/icons/accessible-icon?style=brands

**Comment by schinowsky** [comment]
Thank you!
