### ISSUE TITLE
Icon Request: icon-goodreads

### ISSUE THREAD

**Issue by ivapelc** [FortAwesome/Font-Awesome#1715]
![goodreads logo](http://s.gr-assets.com/assets/icons/goodreads_icon_200x200-fa9a8e09604ec938fbb3ce2db4b8d08d.png)

I'd like to link my profile on Goodreads from my blog and as I already use your icons, it'd be great if you could include their icon in it...
I think it would be good to make two versions - first one just of the black "g", second one inverted ("g" on black background).

Thank you in advance.

**Comment by lauriemrauch** [comment]
+1

**Comment by bekirkarul** [comment]
+1

**Comment by creativecatapps** [comment]
+1

**Comment by aandrezero** [comment]
+1, how is this not added yet??

**Comment by Amorymeltzer** [comment]
:+1:

**Comment by BenSibley** [comment]
+1

**Comment by colmarius** [comment]
:+1:

**Comment by terrorbox** [comment]
+1

**Comment by aleksandar-todorovic** [comment]
We definitely need this one. :+1:  
+1

**Comment by nenecadet** [comment]
:+1:

**Comment by jcontini** [comment]
+1

**Comment by daveschumaker** [comment]
+1

**Comment by sskarakaya** [comment]
+1

**Comment by Kassiah** [comment]
+1

**Comment by almartin82** [comment]
:+1:

**Comment by ryanchrys** [comment]
+1  pleeeease!! :)

**Comment by labyrwa** [comment]
+1

**Comment by revxx14** [comment]
+1

**Comment by justforpractice** [comment]
+1

**Comment by MFIMichael** [comment]
+1

**Comment by barefists** [comment]
+1

**Comment by bonbonelan** [comment]
+1

**Comment by juliemmh** [comment]
+1

**Comment by waxcreative** [comment]
+1

**Comment by jamercier** [comment]
+1

**Comment by brikis98** [comment]
+1

**Comment by utdemir** [comment]
+1

**Comment by FriendlyWP** [comment]
+1

**Comment by Hippo313** [comment]
+1

**Comment by wintre** [comment]
+1

**Comment by OJFord** [comment]
+1

**Comment by cbrokaw** [comment]
+1

**Comment by sorenweite** [comment]
+1

**Comment by iamfantastikate** [comment]
+1

**Comment by chrysta460** [comment]
+1

**Comment by mruwek** [comment]
+1

**Comment by nickigreenwood** [comment]
+1

**Comment by tvpham11** [comment]
+1

**Comment by hasssan** [comment]
+1

**Comment by carrieloves** [comment]
+1

**Comment by samcunliffe** [comment]
+1

**Comment by sengopal** [comment]
+1

**Comment by zablotski** [comment]
+1

**Comment by MohannadNajjar** [comment]
+1
+1
+1

**Comment by RobertDiebels** [comment]
+1

**Comment by legalalien37** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by sgtFloyd** [comment]
:+1:

**Comment by Kaymuhr** [comment]
+1

**Comment by lynzt** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by aymericbeaumet** [comment]
+1

**Comment by shiva** [comment]
+1

**Comment by jeremygibbs** [comment]
+1

**Comment by Lasoulane** [comment]
+1 How is it that there are icons for so many obscure brands yet none for Goodreads?!

**Comment by LavenderMeadows** [comment]
It is ridiculous that this list has been going on for over two years and still no icon for goodreads, yet they have all these icons for all these obscure things, the majority of which I have never even heard of...I will add my +1 here, although at this point it seems like an exercise in futility.  I was told I could always edit and make my own, trust me, if I possessed the skills, I would be happy to do so and make a LOT of other people happy in the process...seriously, at this point I would almost be willing to pay for one !!

**Comment by evnm** [comment]
Really though, isn't languishing in underdevelopment and lowered expectations the absolute essence of being a Goodreads user?

**Comment by LavenderMeadows** [comment]
per the creator of Font Awesome

"Icons are added by priority of how folks vote for it. Goodreads just didn't have enough votes to get added yet. You can add the icon yourself with Fort Awesome and get the best of all worlds.
Best,
-Dave Gandy"

**Comment by revxx14** [comment]
It seems to have quite a few votes >_>

**Comment by AmrEldib** [comment]
The workaround [listed above](https://github.com/FortAwesome/Font-Awesome/issues/1715#issuecomment-22649207) doesn't seem to work anymore, it didn't work for me. This did:
```
<span class="fa-lg" style="font-family:helvetica;vertical-align:text-top;">g</span>
```
The vertical-align raises the letter above a bit to line it up with a row of other social network icons.

**Comment by alanyee** [comment]
“If you go home with somebody, and they don't have books, don't fuck 'em!” ― John Waters
+1 We need a Goodreads icon, not workarounds that become unreliable overtime.

**Comment by Bege13mot** [comment]
+1

**Comment by vensko** [comment]
+1

**Comment by MarkEEaton** [comment]
+1

**Comment by kevinsiji** [comment]
+1

**Comment by alexrodba** [comment]
+1

**Comment by CDuy** [comment]
+1

**Comment by BenSibley** [comment]
+1

**Comment by LavenderMeadows** [comment]
it's never gonna happen, you might as well give up adding your plus ones

**Comment by robertohernando** [comment]
+1

**Comment by RobertDiebels** [comment]
I think it might help if we mention some of the top contributors of the last release to get some attention on this. So here it goes: @davegandy and @tagliala .

**Comment by iamfantastikate** [comment]
Hey, look, everyone. We got an icon for Envira, a WordPress gallery plugin, but still nothing for a website that's in Alexa's top 500 sites. In the world. Cool. Makes sense.

**Comment by julia-r** [comment]
+1

**Comment by 2AbbyNormal** [comment]
+1

**Comment by cryptostrophe** [comment]
+1!

**Comment by tbombach** [comment]
+1

**Comment by TravisCarden** [comment]
+1

**Comment by lenina101** [comment]
+1

**Comment by RobertDiebels** [comment]
We could also check if we can create a pull request which solves this issue. Since there are 111 participants one should probably know how to do it. I could take a look next weekend. However I've never done something like this before (could be a great learning experience though).

**Comment by bonyboy** [comment]
+1

**Comment by l0stiwisd0m** [comment]
+1

**Comment by logological** [comment]
:+1:

**Comment by RationalG** [comment]
+1

**Comment by CourtneyDion** [comment]
+1

**Comment by nosegraze** [comment]
+1

**Comment by annamariie** [comment]
+1

**Comment by pet0ruk** [comment]
+1

**Comment by freeborboleta** [comment]
+1

**Comment by ksykes** [comment]
+1

**Comment by drewdavidpaul** [comment]
+1

**Comment by elcgray** [comment]
+1

**Comment by selenashang** [comment]
+1

**Comment by harbingerofdeath** [comment]
+1

**Comment by anshbansal** [comment]
+1

**Comment by FlandersBurger** [comment]
+1

**Comment by shashankbalaji** [comment]
+1

**Comment by AndreyAzimov** [comment]
+1111

**Comment by ndeason** [comment]
+1

**Comment by jcabdesign** [comment]
+1

**Comment by seoptor** [comment]
+1

**Comment by mcekiera** [comment]
+1

**Comment by bragboy** [comment]
+1

**Comment by rdbinteractive** [comment]
+1

**Comment by julianvmodesto** [comment]
+1

**Comment by PilgrimShadow** [comment]
+1

**Comment by RobertDiebels** [comment]
Ok so since this issue has existed for over 3 years. I've just decided to contact GoodReads with a request to answer some questions about their icon(s).

I asked them the following:
1. What font they use for their logo.
2. Whether or not they have octicons available for their logos
3. Whether or not they would want to assist with the creation of an icon for FontAwesome.

The first 2 questions should help with the creation of an icon by a member of this community (I'm willing to do this, though I've never done it before so it won't be done fast). It might make it into 5.0 if the pull request gets accepted.

The last could mean they would be willing to create the icon themselves or that they will help us do it.

I'm expecting an answer within 3-7 days. Though I don't know how fast their customer support is.

**Comment by bragboy** [comment]
thanks @RobertDiebels for taking the plunge !

**Comment by RobertDiebels** [comment]
I just had an email conversation with customer support. The first reply I got did not answer any of my questions, they just referred me to their normal icons.

The last response basically stated that they are not willing to help. And that they have no octicons or vector-based icons available and are not willing to add any for public use.

(I can post the email-convo if needed)

However I was able to find an icon set: https://alexpeattie.com/projects/justvector-icons
Which has .svg format and actually provides photoshop files.

So anyone willing to look into this further could start there. 

Maybe I will get some time this weekend (though I doubt that).

**Comment by davegandy** [comment]
We love Goodreads here at Font Awesome! Sorry it's taken a while to get in. We're working on it!

**Comment by Redrazor** [comment]
+1

**Comment by cobauer** [comment]
+1

@davegandy Thanks for taking the lead. Any updates? I have access to Photoshop if you need some assistance...

**Comment by taha27** [comment]
@davegandy Hi there, any updates on the goodreads icon?

**Comment by cdtinney** [comment]
+1

**Comment by KuraFire** [comment]
+1 because what's this gonna take?!

**Comment by cobauer** [comment]
+1 again. What's the hold up? What can we do to help out? This request has been open since 2013 and there's clearly a lot of interest... cc @davegandy

**Comment by Lasoulane** [comment]
My annual +1. We're talking 'bout a plain old g here, people!! Is it not enough of a challenge or something?

**Comment by RationalG** [comment]
I just give up.

**Comment by cobauer** [comment]
I tweeted FontAwesome to ask why the goodreads icon hadn't been created yet, and this was the response I received...

"Yep. Thousands of open requests, many with more requests than Goodreads."
https://twitter.com/fontawesome/status/836306963365564416

I did a little digging and discovered that Goodreads has the 2nd largest number of comments from their open requests. Am I missing something? I'm not trying to be rude or create trouble. But I work with a lot of authors and I'm astounded this hasn't been addressed yet. 

I believe there are many people on this thread (myself included) who would be happy to help provide any design support needed. PLEASE let us know how we can expedite the process.

If you're on Twitter feel free to jump on this conversation thread to let them know what you think...

cc @davegandy @tagliala

Best,

Caitlin

**Comment by RobertDiebels** [comment]
@cobauer I've tried reaching out before as well. I have no doubt that their intentions are good and that eventually this icon will get in. Even-though I feel that after 3 years the state of this issue should have been addressed. Either it gets in, or it doesn't. 

Clearly enough people are interested and even willing to help out.

I've hit the thumbs-up for good measure.

**Comment by christianhoward** [comment]
@cobauer It's disappointing to see that response. I'd love to have this and the Strava icon at my disposal.

+1

**Comment by javierph** [comment]
+1

**Comment by bill-c-martin** [comment]
+1

**Comment by pipdig** [comment]
I don't think they count comments as a "vote". You need to "thumbs up" the original post.

**Comment by twinklebob** [comment]
Added my thumbs up! I want it for my blog.

**Comment by evgshk** [comment]
C-mon, FontAwesome... We need this icon so much :)

**Comment by cobauer** [comment]
@bill-c-martin, @javierph, @christianhoward, @RationalG, @Lasoulane, @KuraFire, @cdtinney, @taha27, @Redrazor, @RobertDiebels, @bragboy, @PilgrimShadow, @julianvmodesto, @rdbinteractive, @mcekiera, @seoptor, @jerzgirldesign, @ndeason, @AndreyAzimov, @shashankbalaji, @FlandersBurger, @anshbansal, @harbingerofdeath, @selenashang, @aethior, @elcgray, @drewdavid, @ksykes, @freeborboleta, @pet0ruk, @annamariie, @nosegraze, @CourtneyDion, @RationalG, @logological, @devkoskinen, @bonyboy, @lenina101, @TravisCarden, @tbombach, @zgracem, @2AbbyNormal, @julia-r, @iamfantastikate, @robertohernando, @ghost, @BenSibley, @CDuy, @alexrodba, @kevinsiji, @MarkEEaton, @vensko, @bege13mot, @alanyee, @AmrEldib, @evnm, @jeremygibbs, @shiva, @aymericbeaumet, @SamanthaNguyen, @lynzt, @Kaymuhr, @sgtFloyd, @PeterShaggyNoble, @legalalien37, @MohannadNajjar, @zablotski, @sengopal, @samcunliffe, @carrieloves, @hasssan, @TheChen5, @tvpham11, @nickigreenwood, @mruwek, @chrysta460, @iamfantastikate, @sorenweite, @cbrokaw, @OJFord, @Hippo313, @FriendlyWP, @utdemir, @brikis98, @jamercier, @waxcreative, @juliemmh, @bonbonelan, @barefists, @MFIMichael, @solraxy, @JacobDB, @labbydev, @ryanchrys, @almartin82, @Kassiah, @sskarakaya, @daveschumaker, @jcontini, @eenagy, @aleksandar-todorovic, @terrorbox, @colmarius, @BenSibley, @Amorymeltzer, @aandrezero, @creativecatapps, @agaio, @lauriemrauch, @alessandrococco, @Egga, @johnmarinelli, @activars, @Rebecca50, @ryan-p-randall, @seanthenderson, @theonetruebix, @jenniferlynparsons, @aucrawford, @jgrahamthomas, @cristianosequeira, @jadeproulx, @JamesWhitman, @enummela, @antigravity, @karlnippoldt, @eeshan89, @AgentEm, @marcbertone, @benstewart, @activars, @seanosaur, @darrenturpin, @gaplauche, @iceydesigns, @ernstae, @AnalogJ, @artmechanix, @Snik4er, @stevejohnson-ilikewp, @elleestcrimi, @ranaramez, @igas, @boydm, @ahmadajmi, @sajanp, @robertboloc, @JayHoltslander, @sam327: 

**Not sure if you saw my previous post, but if you haven't hit the thumbs up on the original post at the top of this thread, you should go ahead and do that. From what I understand the developers are counting the number of requests via "thumbs ups" instead of by the number of comments on the thread.**

Thanks!

**Comment by RobertDiebels** [comment]
@cobauer It's in the top 10 now. 😄

**Comment by thelaughinganon** [comment]
+1
So... I got tired of waiting and decided to do it myself. It's not perfect but its all I cad do. 
I basically replaced the "dribbble" icon for a goodreads one and also the "Be" icon for the deviantart one.
![untitled](https://cloud.githubusercontent.com/assets/28929306/26415108/bb9c791e-4087-11e7-9186-835f24b58805.jpg)
For my site the best one would've been only the "g" but I didn't like how it turned up, so I went for the one with a square background. I can basically replace any icon for any of the goodreads ones presented here: https://www.iconfinder.com/icons/43148/goodreads_icon

It works for me, at least until we get the official one... if we do :/

**Comment by Skylith86** [comment]
+1

**Comment by mindeeforman** [comment]
+1

Why has this been a request for FOUR YEARS and it hasn't happened yet?

I also noticed there's no Blogger icon...

Thanks for the great icons!

**Comment by sdhiaeddine** [comment]
**+1**

**Comment by griggril000** [comment]
+1

**Comment by iamalotaibi** [comment]
+1

**Comment by kohnewlife** [comment]
+1
Please please do that. 4 years for an icon. An explanation at least would make us happy somewhat

**Comment by Kero76** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by cobauer** [comment]
That’s great news. Any idea when that will launch?

Best,

Caitlin O’Brient Bauer
