### ISSUE TITLE
TripAdvisor doesn't show up correctly on mobile 

### ISSUE THREAD

**Issue by trangvo2306** [FortAwesome/Font-Awesome#17153]
I caught some weird issue with tripadvior icon on mobile. It's OK on tablet and desktop, it only happens with mobile (both android and iOS).

![IMG_2649](https://user-images.githubusercontent.com/19234714/93272287-00c92e00-f76a-11ea-8f92-35b7b7794e93.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has been fixed in Font Awesome 5.14.0, please update to the latest version

Ref: #16817
