### ISSUE TITLE
The font is not displayed if I use a reset rule: body * { font-family: sans-serif !important; } 

### ISSUE THREAD

**Issue by matih** [FortAwesome/Font-Awesome#1716]
In previous version (I don't know which, because the version number is missing in the css) - the `font-family` rule was applied more specific, on the `:before` selector :
`[class^="icon-"]:before,[class*=" icon-"]:before {
    font-family: 'FontAwesome';`

But now it's applied on the class selector:
`class^="icon-"],[class*=" icon-"] {
  font-family: FontAwesome;
`
and cause a conflict with global reset rules that override the less specific rules.

**Comment by tagliala** [comment]
Closing here, please use custom css if you have a similar issue
