### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by hrkristian** [FortAwesome/Font-Awesome#17163]
**Describe the bug**
Running npm install on a Windows machine causes the following error output

```
[INFO] npm ERR! code E401
[INFO] npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

Project-local .npmrc contains the necessary credentials:
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken={redacted}
```

The packages being installed are 
```
"@fortawesome/fontawesome-svg-core": "^1.2.27",
"@fortawesome/pro-light-svg-icons": "^5.12.1",
"@fortawesome/pro-solid-svg-icons": "^5.13.0",
"@fortawesome/vue-fontawesome": "^0.1.9",
```

Normally I would suspect a global config, but there's no global config file to be found, and running npm -g config list returns no font-awesome specific settings.  
This is also happening on multipe Windows machines, so it being a global config case seems unlikely.

Have attempted to remove lock file and node_modules.

From existing issue reports it seems to be a problem related to the free version, however the free version is not in this project, pro version only.

**To Reproduce**
Unsure how to reroduce. There is nothing special about this project that I'm aware of.   
It builds perfectly fine on Linux but fails on Windows machiens.

**Expected behavior**
Expect the packages to be installed.

**Version and implementation**
Versions:   
"@fortawesome/fontawesome-svg-core": "^1.2.27",  
"@fortawesome/pro-light-svg-icons": "^5.12.1",  
"@fortawesome/pro-solid-svg-icons": "^5.13.0",  
"@fortawesome/vue-fontawesome": "^0.1.9",  
Browser and version: ---

[ x ] SVG with JS
[ ] Web Fonts with CSS
[ ] SVG Sprites
[ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Same issue as #17147?

**Comment by leimd** [comment]
Same problem with us as well

**Comment by tagliala** [comment]
Is this the same license-related issue described at #17147?

**Comment by f15u** [comment]
I don't know if the issue is the same as #17147 because our license is "Pro (Legacy)", as stated in that link issue, but after contacting the support and waiting almost 3 days without a response, is it possible to install the pro packages via NPM?

We are pretty confused about the license thing that might be the problem.

What can we do or provide in order to resolve the problem?

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by tagliala** [comment]
@FedericoBiccheddu I cannot help on this issue directly, but in the meanwhile I can try.

If I'm getting this correctly, this is about a kickstarter perpetual FA5 Pro license with an expired subscription to the private NPM repository (ref: https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692775989)

If this is the case, you should be able to see the following page in the docs: https://fontawesome.com/v5/docs/web/setup/use-npm-downloads#using-the-local-filesystem

You should then be able to download the npm Pro packages from here: https://fontawesome.com/download#v5-pro-packages

Then you have different options to self-host packages. Some are listed in the docs, others are mentioned here https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692687539

Refs:
- https://fontawesome.com/v5/docs/web/setup/use-npm-downloads#using-the-local-filesystem
- https://fontawesome.com/download#v5-pro-packages
- https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692687539
- https://github.com/FortAwesome/Font-Awesome/issues/17147#issuecomment-692775989

**Comment by f15u** [comment]
We resolved the issue following your hints. Thank you so much.

Just to know, should we change the plan in order to use your private registry? This will semplify our setup a lot!

**Comment by tagliala** [comment]
Welcome!

> Just to know, should we change the plan in order to use your private registry? This will semplify our setup a lot!

As per documentation, an active subscription to a Pro Plan is required to have access to the private npm repository

Ref:
- https://fontawesome.com/docs/web/setup/packages#_1-configure-access
- https://fontawesome.com/plans (check npm bandwidth)

**Comment by robmadole** [comment]
@hrkristian @leimd you can send an email to hello@fontawesome.com. Since we are dealing with account email addresses and security-sensitive topics we are not going to help you directly in this GH issue.
