### ISSUE TITLE
Icon request: network-broken

### ISSUE THREAD

**Issue by N445** [FortAwesome/Font-Awesome#17172]
**What can it be used for?**
It can be used when network with a device is lost

**Example image (optional)**
![Internet_and_Wifi_Expand-07-128](https://user-images.githubusercontent.com/25900291/93607372-8696e480-f9c9-11ea-856b-fd38242b7511.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`) network ok / network lost
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is already available in FA Pro: https://fontawesome.com/icons/wifi-slash?style=solid

It can also be implemented in FA by using the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/439/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
