### ISSUE TITLE
Icon request: velux-open / velux-closed

### ISSUE THREAD

**Issue by mpejstrup** [FortAwesome/Font-Awesome#17179]
Hi
Would love an animated skyligt icon for my Velux windows, in my home automation UI. Opening and closing
A whole range of skylights would be nice, but a flat roof, similar to below is what I personally need.

Thanks in advance
![skylight](https://user-images.githubusercontent.com/55014016/93707337-9d564c00-fb2d-11ea-86ba-476642d37ebd.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify if this request consists in a couple of icons (velux-open / velux-closed) ?

Ref: [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md):


I think that animated icons are out of scope of the moment, at the least on the free repo.

**Comment by mpejstrup** [comment]
Hi

Of course

Well one open and one closed would be nice. But I would be prepared to pay for the pro version for an animated one.
Can the icons be imported into Illustrator so I can snimste it myself?

Br
Martin

**Comment by tagliala** [comment]
> But I would be prepared to pay for the pro version for an animated one.

I don't know if there are any plans for commissioned animated icons. At the moment Font Awesome Pro does not have animated icons at all

Please send an email to hello@fontawesome.com if you are interested in commissioning an icon and also add a link to this request

**Comment by mpejstrup** [comment]
Okay. 

I consider that? But the request is still open here then??

**Comment by tagliala** [comment]
> But the request is still open here then??

This is a request for two strictly related, non-animated icons: velux-open and velux-closed. This is a valid request and I see no reason for closing it

**Comment by mpejstrup** [comment]
Sounds great. 

So How do I know if this will be worked on. Sorry for the dumb questions, this is the first time I'm making this type of request

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
