### ISSUE TITLE
Add version selector on website icons page

### ISSUE THREAD

**Issue by unikitty37** [FortAwesome/Font-Awesome#1718]
For various reasons, I'm stuck on 3.0.2 for now. I can't find a way to get the icons page to show me only the icons that are available in the version I'm using.

Would it be possible to add a version selector to the icon page which greys out icons that aren't available in the version selected? (archive.org won't go back past 3.1.1, and the Github history for the page doesn't go back any further, either — was the page at a different address before then?)

**Comment by sensibleworld** [comment]
I know this is super late responding to this issue, but we now have a version selector on the version 5 icon search. You can choose to search for "latest" release (example: `https://fontawesome.com/icons?d=gallery&v=5.8.0`)... and can manually change that `v` number in the address bar to target other versions.
