### ISSUE TITLE
Icon Request: Bangladeshi Taka (BDT)

### ISSUE THREAD

**Issue by mehdiakram-zz** [FortAwesome/Font-Awesome#1719]
Can you add Bangladeshi Taka (BDT) in Font-Awesome Currency Icons?
Unicode (&#2547;)
Thanks

**Comment by kcoitk** [comment]
+1

**Comment by smartrahat** [comment]
We need it

**Comment by maksbd19** [comment]
+1

**Comment by Nabil5352** [comment]
+1

**Comment by foyzulkarim** [comment]
+1

**Comment by shamimmoeen** [comment]
+1

**Comment by TahmidRahman** [comment]
+1

**Comment by hasantarak5** [comment]
Hey friends i will give u BDT Currency code. Here it is--- Enjoy.

HTML Entity (decimal) | &#2547;
-- | --
HTML Entity (hex) | &#x9f3;
How to type in Microsoft Windows | Alt +09F3
UTF-8 (hex) | 0xE0 0xA7 0xB3 (e0a7b3)
UTF-8 (binary) | 11100000:10100111:10110011
UTF-16 (hex) | 0x09F3 (09f3)
UTF-16 (decimal) | 2,547
UTF-32 (hex) | 0x000009F3 (09f3)
UTF-32 (decimal) | 2,547
C/C++/Java source code | "\u09F3"
Python source code | u"\u09F3"

**Comment by mazhar266** [comment]
@hasantarak5 We obviously didn't want that lolz.

**Comment by al2helal** [comment]
I feel need of this.

**Comment by sandiproy876** [comment]
We need it.

**Comment by Riyaz0001** [comment]
We Need It in Font-Awesome icons.

**Comment by jacques** [comment]
+1

**Comment by Basher7** [comment]
Dear concern,
we need bangladeshi curency(taka) as a Font-Awesome font. please add this as a icon
Optionally I add a svg file link for your help
[https://drive.google.com/open?id=1nka1ahRLOVRrj0bRG3UBAYWmoCEEthC3](url)

**Comment by OmarPUC** [comment]
we need it!

**Comment by ashikjs** [comment]
+1 
We need it........

**Comment by nahid1146** [comment]
+1 
What takes Font awesome 6 years to add this icon? Are you seriously ignoring this, font awesome team?

**Comment by Basher7** [comment]
> Dear concern,
> we need bangladeshi curency(taka) as a Font-Awesome font. please add this as a icon
> Optionally I add a svg file link for your help
> [https://drive.google.com/open?id=1nka1ahRLOVRrj0bRG3UBAYWmoCEEthC3](url)

Dear FontAwesome Team,
Humble request to add this in your Icon list.

**Comment by TareqMonwer** [comment]
Thanks :O

**Comment by Khanstore** [comment]
it is badly needed

**Comment by jamilcse13** [comment]
you may use this HTML &#2547;

**Comment by Chowdhury-Joy** [comment]
> you may use this HTML `&#2547;`

Thanks

**Comment by tanim3221** [comment]
You can use this one for taka sign. 

element:before {
  content: "\09f3";
  margin-right: 6px;
  font-size: 128px;
  vertical-align: middle;
}

**Comment by iamsarker** [comment]
+1

**Comment by AtifChy** [comment]
+1

**Comment by sohailsami** [comment]
Same here, need bangladeshi currency icon.

**Comment by Saagoor** [comment]
Why the hell the Font Awesome team hasn't added it yet.....

**Comment by sensibleworld** [comment]
Hey folks! This is coming to Font Awesome 6.

**Comment by RiajulKashem** [comment]
> Hey folks! This is coming to Font Awesome 6.
checked Font Awesome 6 alpha there is no icon for BD currency :(

**Comment by sensibleworld** [comment]
We've still got another batch of icons to be added to the first v6 release, and this is on the list. Sorry for the delay!

**Comment by sensibleworld** [comment]
<img width="690" alt="Screen Shot 2021-03-30 at 12 15 18 PM" src="https://user-images.githubusercontent.com/529604/113021452-99952900-9151-11eb-8d9e-1ba52656914e.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
