### ISSUE TITLE
Icon request: Text Wrap

### ISSUE THREAD

**Issue by ashish-sharma91** [FortAwesome/Font-Awesome#17190]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any example of how this icon should look like?

**Comment by ashish-sharma91** [comment]
https://www.flaticon.com/svg/static/icons/svg/565/565738.svg

**Comment by tagliala** [comment]
Is this request a subset of #16188?

**Comment by ashish-sharma91** [comment]
Yes

**Comment by tagliala** [comment]
So one of the following icons:

![image](https://user-images.githubusercontent.com/556268/94007186-612b2180-fda1-11ea-8cf9-adfc85cf0330.png)

will fit this use case?

**Comment by ashish-sharma91** [comment]
Yes, second one fits. But what I have sent you as link is more relavant.

**Comment by tagliala** [comment]
Ok thanks. I'm going to close here as a duplicate, please add a 👍 request to #16188
