### ISSUE TITLE
Can't use the downloaded pro packages.

### ISSUE THREAD

**Issue by plamenh** [FortAwesome/Font-Awesome#17194]
I know you want to make money by forcing us to pay a subscription, but this goes beyond imagination:

```
xxx@www yyy_zzz % npm install assets/npm/fontawesome/fortawesome-pro-duotone-svg-icons-5.14.0.tgz assets/npm/fontawesome/fortawesome-pro-light-svg-icons-5.14.0.tgz assets/npm/fontawesome/fortawesome-pro-regular-svg-icons-5.14.0.tgz assets/npm/fontawesome/fortawesome-pro-solid-svg-icons-5.14.0.tgz
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

**So, you've hidden the types and svg behind a paywall?:**

```
 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-common-types 227ms
23 silly fetchPackageMetaData error for @fortawesome/fontawesome-common-types@^0.2.30 Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```
```
7 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-svg-core 818ms
8 silly fetchPackageMetaData error for @fortawesome/fontawesome-svg-core@latest Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

**Comment by plamenh** [comment]
#17185

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> So, you've hidden the types and svg behind a paywall?:

Nope 😅

Please just try to remove the dedicated `.npmrc` configuration entries

`fontawesome-svg-core` and `fontawesome-common-types` are freely available on the public npm repo

Ref:
- https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core
- https://www.npmjs.com/package/@fortawesome/fontawesome-common-types

If you need instruction on how to use the npm pro packages locally, we have a new page in the docs: https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download

/cc @robmadole

**Comment by plamenh** [comment]
Thanks for the guide, @tagliala, but, unfortunately none of that seems to work (deleting .npmrc, npm variables, node_modules, etc.). 

Plus, I believe the common-types for the free version are missing the pro types (found that out the hard way with npm pack on the downloaded free package js-packages subfolders).

I dealt with that by copying older version files from our prod environment. Not nice.
