### ISSUE TITLE
Can't install pro-* packages

### ISSUE THREAD

**Issue by pixels-farm** [FortAwesome/Font-Awesome#17195]
I did both steps described here https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers (config set and .npmrc created with latest auth recomendations)

yarn add @fortawesome/fontawesome-pro
gives:
**error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: authentication required".**

npm install @fortawesome/fontawesome-pro
gives:
**npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"**

Nothing helps. 

yarn 1.22.5
npm 6.14.6
node v12.18.3

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check that your subscription to services is still valid?

https://fontawesome.com/account

I think this could be the same issue described in #17147

**Comment by pixels-farm** [comment]
So, if i got you right - even though i have lifetime licence for using FontAwesome 5 - i can't use yarn or npm to mange fontawesome lib anymore?

**Comment by tagliala** [comment]
>  i can't use yarn or npm to manage fontawesome lib anymore?

Correct, you can keep using Font Awesome 5 but you can't download pro npm packages through Font Awesome's private npm repo

We have provided new instructions on how to keep using npm packages: https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download

/cc @robmadole

**Comment by pixels-farm** [comment]
Ok, so the problem is solved. Thanx! We can close this thread
