### ISSUE TITLE
Icon Request: Marijuana/Cannabis

### ISSUE THREAD

**Issue by LDigital84** [FortAwesome/Font-Awesome#1720]
Hi,

I would like to request a marijuana/cannabis leaf icon. I know this request could be controversial but I live in Colorado which has both medical and recreational marijuana use. I build websites for the marijuana industry and I absolutely LOVE Font Awesome. If this icon was included it would really make Font Awesome even more Awesome! Also there are no other icon fonts (that I know of) that contain a marijuana leaf.

I would use this on the sites that I build for the marijuana industry. So far I have to rely on images for handling this. Since I already use Font Awesome on many of these sites I would prefer not to have to rely on an image.

I appreciate your consideration.

Lynda 
![marijuana-icon](https://f.cloud.github.com/assets/1938824/907697/5622c408-fd56-11e2-9e54-9b3627a74a29.jpg)

**Comment by andrewkatz** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by wilblack** [comment]
+1
any status change on this?

**Comment by moesfeld** [comment]
+1

**Comment by xereon** [comment]
+1 I've been waiting for the cannabis leaf text/font symbol for years. Font-Awesome is the answer. <3

**Comment by originalslicey** [comment]
+1 There are several icons I need for the websites I build for the medical cannabis community. This is one of them.

**Comment by wilblack** [comment]
+1 I am working on a website for the soon-to-be legal marijuana industry in Oregon. This icon as a font would be Awesome!

**Comment by Fatbat** [comment]
+1 again.

**Comment by harigopalakrishna** [comment]
+1

**Comment by XenRevo** [comment]
+1
+420

**Comment by mwthink** [comment]
+1

**Comment by Fatbat** [comment]
Would really love to see this make it into the next update.

**Comment by msamoylov** [comment]
+1

**Comment by schulzefelix** [comment]
+1

**Comment by thatrubylove** [comment]
still no?

+420

**Comment by bensayersllc** [comment]
+1

**Comment by 420connect** [comment]
+100%

**Comment by beanfan78** [comment]
Would be amazing to have this. It would really help on many of my clients sites. +1, the industry is growing (no pun intended), and a font-awesome icon would be another vote of legitimacy!

**Comment by tbeckman1234** [comment]
+1

**Comment by niteshp** [comment]
+1

**Comment by d1git31** [comment]
Come on guys! We could really use this icon. Industry is booming and seems to be a popular need among the community. Its like this thread is 419 and +1 by many, but we can get seem to get to the holy 420 :)

**Comment by iddcom** [comment]
+1

**Comment by beanfan78** [comment]
I am working with a lot more MMJ-related sites and would like to give this another +1. I am also assisting the brand for [Ted's Marijuana Forum](https://www.tedsmarijuanaforum.com) and I really would like to implement a standard leaf or I can create a unique one as well. Is there any chance this type of icon will be added anytime soon? I am happy to do a .svg or any other type of file to get this.

**Comment by kennyose** [comment]
+1

**Comment by Zeddi-Ink** [comment]
+1

**Comment by edofritz** [comment]
+1

**Comment by NightOwlPrgmr** [comment]
+1
Looks to still be wanted by many! I know you're probably extremely busy with FA5, but please include this request in with the new icon sets!

**Comment by alwye** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by gpon4H** [comment]
+1

**Comment by vincefav** [comment]
+1. We already have alcohol and cigarette icons. This would be a useful addition.

**Comment by d1git31** [comment]
Lord have mercy! Get with the times guys! Maybe we need a little bit of social media pressure. Seems to do the trick for everything else. Who has you bought? Big alcohol and tobacco?

`<drug_war>
</drug_war>`

**Comment by Fatbat** [comment]
Closing in on 5 years since this was first requested.

**Comment by retlehs** [comment]
aaaaand the number of states that have introduced medical and/or recreational cannabis has increased, and canada is [likely] about to be legalizing

**Comment by asurace** [comment]
+1

**Comment by thonydam** [comment]
+1 :)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=marijuana
