### ISSUE TITLE
ver.5.15.0: vest.svg and vest-patches.svg is colored

### ISSUE THREAD

**Issue by ruedap** [FortAwesome/Font-Awesome#17211]
**Describe the bug**
ver.5.15.0: vest.svg and vest-patches.svg is colored. Is this correct?

**To Reproduce**

* https://github.com/FortAwesome/Font-Awesome/blob/5.15.0/svgs/solid/vest.svg
* https://github.com/FortAwesome/Font-Awesome/blob/5.15.0/svgs/solid/vest-patches.svg

`style="fill:#193154"`

**Expected behavior**

no style attr

**Screenshots**

![image](https://user-images.githubusercontent.com/289671/94577795-ed61ab00-02b1-11eb-9df0-944bd7d66d1c.png)

![image](https://user-images.githubusercontent.com/289671/94577831-f6527c80-02b1-11eb-8c91-f2cd6af28b93.png)

**Version and implementation**
Version: 5.15.0

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I suppose it isn't, but let's ask @sensibleworld to check

@robmadole if this is something that it should not happen, would it be possible to add a check that `style` attribute is not present in the SVG?

**Comment by sensibleworld** [comment]
Yup! This was an error on my part. We'll get it fixed up. Our normal import process strips this sort of thing out, but I manually added this one and missed it.

**Comment by sensibleworld** [comment]
Just confirming that this was fixed in version 15.5.1: https://github.com/FortAwesome/Font-Awesome/blob/5.15.1/svgs/solid/vest.svg
