### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by igorducca** [FortAwesome/Font-Awesome#17212]
**What can it be used for?**
I want this icon to use on my projects, to improve my branding.

**Example image (optional)**
https://i.imgur.com/RwkRzMH.png
![igo-black](https://user-images.githubusercontent.com/72057800/94579770-8f9c7700-024f-11eb-8004-0ddb00228cc8.png)

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide more details about this brand and clarify how other users of Font Awesome can use this icon?

**Comment by jabronus** [comment]
@igorducca Thanks for requesting a new icon, but since you haven’t provided any additional information this is going to be closed. Feel free to reach out with more details if you'd like us to reconsider!
