### ISSUE TITLE
Cannot confirm account at fontawesome.com

### ISSUE THREAD

**Issue by andym0908** [FortAwesome/Font-Awesome#17218]
Hey, I've been trying to set up an account, and finally got an confirmation email, but the link it takes me to is being blocked by Chrome.  Privacy error issue (due to NET::ERR_CERT_COMMON_NAME_INVALID).

So, it won't let me proceed. Screenshot attached.

**Comment by andym0908** [comment]
Oops.
![fontawesome_issue](https://user-images.githubusercontent.com/4673649/94718376-94ddec80-0349-11eb-98aa-3ee338c768ca.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@robmadole could you please take a look?

**Comment by andym0908** [comment]
Thank you for the swift response!

**Comment by NovamationCEO** [comment]
That IS swift!  For what it's worth, I'm seeing the same issue when I try to confirm my account.

**Comment by robmadole** [comment]
Hey all, send an email to hello@fontawesome.com and our support team will get you fixed up. We switched to a different email delivery service provider and this happened during the transition.
