### ISSUE TITLE
Change icon "ban-circle" to conform to international sign-design guidelines

### ISSUE THREAD

**Issue by Luzifr** [FortAwesome/Font-Awesome#1721]
The Ban-Sign in Font-Awesome features a Circle, striked through by a bar from left bottom to right top. That is not a proper ban sign, just look at international traffic-signs. There a ban is always the reverse sign of yours, while your's means releasing some ban. 

Ban sign always has a bar going from left top to right bottom. The graphic-designers explanation for that sign: 
In psychology the direction of "future" is to the right, coming from left. Also positive is to the top, while negative is to the bottom. So a sign showing a strike-through like the ban-sign of Font-Awesome is actually releasing a ban, not setting it, because the bar goes up and shows a move to the positive. That's why a proper ban-sign has a bar coming from the top going down to the negative bottom symbolizing a ban. No = down! 

Please either change the icon's strike-through bar direction or do another ban-icon which is designed the other way round. Thanks! ;-) 

I've attached an image of a proper ban-sign: 
![10236730 height 150 width 150 no-ban-sign](https://f.cloud.github.com/assets/915591/908825/88a57df6-fda8-11e2-80fd-ee2520dd8e7a.png)

BTW: Yes, there are many signs like your's out there, but you know: Somebody sometimes got it wrong and it spread around and now most of the people don't know what the correct sign is. But that doesn't mean that the reversed signs are correct. ;-)

**Comment by mzaslavsky** [comment]
Not only would the symbol have to be flipped horizontally to mimic the ISO 3864 standard (which can still be achieved in the meanwhile with the the "fa-flip-horzontal" class), the current style is also not ideal for stacking since the strike-though is too thick and would cover too much of the icon in the background.

I suppose for versatility it would be useful to also have fa-ban-square as well (useful for larger background icons).

https://en.wikipedia.org/wiki/No_symbol

**Comment by tagliala** [comment]
added to 5.0.0 milestone so Dave will eventually take a look

**Comment by Luzifr** [comment]
That would be very welcome!

**Comment by heyneff** [comment]
+1

**Comment by davegandy** [comment]
Very interesting! Yes, we will definitely get to this in 5.0.

**Comment by dondi2112** [comment]
Yes, I echo the OP's thoughts exactly; as a designer, it is unnerving when I see the "not symbol" used incorrectly. As the OP stated, the intention of the design of the symbol's slash being drawn from top-left to bottom-right is to invoke a negative declaration when reading from left-to-right. The "motion" is therefore in the downward direction. This symbol was specifically designed to invoke such subconscious emotions to the reader, i.e., down = negative, red = negative/stop/danger/loss, up = positive, green = positive/gain/go/proceed/ok, etc.

**Comment by tagliala** [comment]
Fixed in 5.0.0
