### ISSUE TITLE
fad icon not using custom colouring

### ISSUE THREAD

**Issue by WilliamMayor** [FortAwesome/Font-Awesome#17228]
**Describe the bug**
This morning we noticed that the custom colours on our fad icons weren't working and were instead just using the current text colour as the secondary (we think??) colour.

**To Reproduce**
I've forked the official codepen for exploring the custom colours, bumped to the latest version, and added the half star customisation that we're using.

https://codepen.io/wmayor/pen/LYNKqaQ

**Expected behavior**
The star should be first hald gold, second half gray. Instead the first half is white and the second is black.

**Screenshots**
Here's what we're trying to acheive:
![Screenshot 2020-10-02 at 12 28 53](https://user-images.githubusercontent.com/403126/94918642-dd60eb80-04aa-11eb-8807-94ab30245317.png)

Here's what we currently see
![Screenshot 2020-10-02 at 12 28 42](https://user-images.githubusercontent.com/403126/94918646-e05bdc00-04aa-11eb-8ecc-5c4d874ec5aa.png)

**Version and implementation**
Version: 5.15.0 (works on 5.14.0)
Browser and version: Firefox and chrome on MacOS.

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

I think this is related to #17226 but that ticket talks about missing parts of the icon, we're seeing the wrong colours? This is could be the same issue?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thank for reporting this.

> I think this is related to #17226 but that ticket talks about missing parts of the icon, we're seeing the wrong colours? This is could be the same issue?

Same issue as #17226
