### ISSUE TITLE
Is it legal to use a FA icon in a company logo?

### ISSUE THREAD

**Issue by VictorioMolina** [FortAwesome/Font-Awesome#17220]
Hello, I have implemented an app using FA and one of your icons is in a lot of parts of the app so it would be great to design my app logo based on this icon, I mean, using it as the main part of the logo.

Is this legal? If not, is there any way to use it?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IIRC it is possible to do that, but you cannot trademark/register the logo

Please wait for @robmadole's confirmation

**Comment by VictorioMolina** [comment]
Okey, thank you. I need registration :,C if @robmadole confirm that is not legal, could it be via payment or something?

Thank you.

**Comment by robmadole** [comment]
Hi @VictorioMolina. The best I can do is point you to the license for:

- [Pro](https://fontawesome.com/license)
- [Free](https://fontawesome.com/license/free)

We can't give legal advice or make a determination for you based on your usage. Feel free to ask follow-up questions about the license and we can try to help answer, though.
