### ISSUE TITLE
fad not showing full

### ISSUE THREAD

**Issue by totoprayogo1916** [FortAwesome/Font-Awesome#17226]
**Describe the bug**
icon on duotone not showing full today

**Screenshots**
![image](https://user-images.githubusercontent.com/2387514/94886147-63296a80-049c-11eb-8327-593e23e4e91c.png)

**Version and implementation**
Version: latest
Browser and version: Microsoft Edge Chromium

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by totoprayogo1916** [comment]
fad fa-globe
![image](https://user-images.githubusercontent.com/2387514/94886876-f2d01880-049e-11eb-85ae-35661f71f041.png)

fad fa-users
![image](https://user-images.githubusercontent.com/2387514/94886904-0bd8c980-049f-11eb-9486-b57a82324b91.png)

fad fa-user 
![image](https://user-images.githubusercontent.com/2387514/94886944-28750180-049f-11eb-8da2-b4ffda87254d.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide:
- FA version (5.xx)
- Implementation (svg/css)
- Hosting method (kit/cdn/self-hosted)

?

**Comment by totoprayogo1916** [comment]
using CDN
`<script defer src="https://kit.fontawesome.com/xxxxxxxxxxx.js" data-auto-replace-svg="nest" crossorigin="anonymous"></script>`

FA Version: 5.15.0 and implementation using SVG/JS ..

**Comment by tagliala** [comment]
Confirmed, thanks!

Demo: https://jsfiddle.net/tagliala/0kd5xqm4/1/

I think this is a known issue and it has been fixed in the build system, but let's assign @robmadole

**Comment by SamMorrowDrums** [comment]
And confirmed pinning kit to 5.14.0 also addresses the issue for those affected. Quite a prominent icon on my site had been changed. I won't be using "latest" again with Fontawesome kits - too much risk to avoid manual upgrades.

**Comment by robmadole** [comment]
We've got a fix for this already merged and we'll get it deployed on Monday. Sorry folks, we caught this one pretty fast but not before it manifested on your sites.

**Comment by SamMorrowDrums** [comment]
OK can confirm that using 5.15.1 is working and I imagine the issue can be closed.
