### ISSUE TITLE
Icon request: fa-flag-fr 🇫🇷

### ISSUE THREAD

**Issue by philippeberck** [FortAwesome/Font-Awesome#17223]
Hi,

Have you icons flags ?
France and Englang flags.

Philippe Berck

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please split this request into two separate requests, one for France flag, one for England

You can edit the title of this one and open a new one

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
