### ISSUE TITLE
url5101.fontawesome.com’s server IP address could not be found.

### ISSUE THREAD

**Issue by javanigus** [FortAwesome/Font-Awesome#17230]
When I try to confirm my email address, I always get this error.

This site can’t be reachedurl5101.fontawesome.com’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Same issue as #17218

Solution: https://github.com/FortAwesome/Font-Awesome/issues/17218#issuecomment-702176745

Closing here
