### ISSUE TITLE
Icon Request: scriptogr.am

### ISSUE THREAD

**Issue by surfstationcc** [FortAwesome/Font-Awesome#1723]
![scriptogram](https://f.cloud.github.com/assets/5137160/915142/caf28c7e-fe5e-11e2-9963-41a6bdce0572.png)

Hi,

I would like to request a scriptogr.am icon.
I'd like to link my blog on scriptogr.am  from my website.

Thanks.

**Comment by kshiteesh** [comment]
I'm just bumping this request instead of creating a new one.

**Comment by kshiteesh** [comment]
+1

**Comment by tagliala** [comment]
@kshiteesh you did the right thing but as you can see there is very few traction for this brand. 

I should advise you to consider a custom build:  https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by kshiteesh** [comment]
@tagliala, thanks for the link. I'll take a look. :)

**Comment by aethior** [comment]
>Scriptogram will discontinue operation on August 14th, 2015. ([source](https://twitter.com/scriptogram/status/621660023459049472))

`scriptogr.am` now redirects to `pdfbear.com`.

cc/ @tagliala

**Comment by tagliala** [comment]
Closing here
