### ISSUE TITLE
401 Status Code followed by FontAwesome Pro Repository not found in NPM

### ISSUE THREAD

**Issue by Damo1155** [FortAwesome/Font-Awesome#17248]
Our projects were upgraded to FontAwesome Pro about 6 weeks ago with me being unaware of the NPM repository changes.

Some colleagues have only just made the necessary changes to their environments and immediately hit a 401 authentication issue. They were all instructed to add the following configuration to the NPMRC file as per the documentation.

`@fortawesome:registry=https://npm.fontawesome.com/ && \`
`//npm.fontawesome.com/:_authToken=<KEY>`

Our upgrade finished just prior to the repository changes so it continued working for me until cleaning the local YARN cache. Since then I've now been able to replicate the 401 issue and after looking at other similar issues have removed the LOCK files from all solutions and tried running `yarn install`. That subsequently hit other problems which were easily resolved by remove FA references from the `package.json` file.

After dealing with the above and with the mentioned NPMRC configuration I've run `yarn add @fortawesome/fontawesome-pro`, the error has now changed to the following.

![image](https://user-images.githubusercontent.com/16608228/95378871-7729fd80-08dc-11eb-8629-4cf56a729a3b.png)

We purchased our key back in June/July 2020 so as far as I'm aware it's subscription based (standard, paid yearly). Based on this we should still have access to the NPM repository from everything I've read.

I'll be validating the key details tomorrow with a colleague who has access to the account. However, for the time being I'm fairly certain it's not a lifetime license so would be greatful for any clarification and/or a solution to be able to get the packages from NPM without having to download and host them ourselves.

**Similar Issues:**

[Issue #17147](https://github.com/FortAwesome/Font-Awesome/issues/17147)
[Issue #17195](https://github.com/FortAwesome/Font-Awesome/issues/17195)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please try with

```
yarn --verbose add @fortawesome/fontawesome-pro
```

and paste the log here? 

Please to remove all sensitive information from the log, if any

**Comment by Damo1155** [comment]
As requested.

> $ yarn --verbose add @fortawesome/fontawesome-pro
yarn add v1.10.1
warning package.json: "dependencies" has dependency "gulp" with range "^3.9.1" that collides with a dependency in "devDependencies" of the same name with version "^3.9.0"
warning package.json: "dependencies" has dependency "gulp-sourcemaps" with range "^1.11.1" that collides with a dependency in "devDependencies" of the same name with version "^1.6.0"
verbose 0.31 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\<PROJECT NAME>\\.npmrc".
verbose 0.311 Checking for configuration file "C:\\Users\\<MACHINE NAME>\\.npmrc".
verbose 0.311 Found configuration file "C:\\Users\\<MACHINE NAME>\\.npmrc".
verbose 0.312 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\npmrc".
verbose 0.313 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\<PROJECT NAME>\\.npmrc".
verbose 0.313 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\.npmrc".
verbose 0.314 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\.npmrc".
verbose 0.314 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\.npmrc".
verbose 0.314 Checking for configuration file "C:\\Dev\\Repos\\.npmrc".
verbose 0.315 Checking for configuration file "C:\\Dev\\.npmrc".
verbose 0.317 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\<PROJECT NAME>\\.yarnrc".
verbose 0.317 Checking for configuration file "C:\\Users\\<MACHINE NAME>\\.yarnrc".
verbose 0.318 Found configuration file "C:\\Users\\<MACHINE NAME>\\.yarnrc".
verbose 0.318 Checking for configuration file "C:\\Program Files\\nodejs\\etc\\yarnrc".
verbose 0.319 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\<PROJECT NAME>\\.yarnrc".
verbose 0.319 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\<SOLUTION NAME>\\.yarnrc".
verbose 0.32 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\Code\\.yarnrc".
verbose 0.32 Checking for configuration file "C:\\Dev\\Repos\\<REPOSITORY NAME>\\.yarnrc".
verbose 0.321 Checking for configuration file "C:\\Dev\\Repos\\.yarnrc".
verbose 0.321 Checking for configuration file "C:\\Dev\\.yarnrc".
verbose 0.324 current time: 2020-10-07T20:31:05.614Z
warning <OTHER PROJECT NAME>@0.0.0: "dependencies" has dependency "gulp" with range "^3.9.1" that collides with a dependency in "devDependencies" of the same name with version "^3.9.0"
warning <OTHER PROJECT NAME>@0.0.0: "dependencies" has dependency "gulp-sourcemaps" with range "^1.11.1" that collides with a dependency in "devDependencies" of the same name with version "^1.6.0"
[1/4] Resolving packages...
verbose 0.741 Performing "GET" request to "https://npm.fontawesome.com/%20&&%20//@fortawesome%2ffontawesome-pro".
verbose 0.931 Request "https://npm.fontawesome.com/%20&&%20//@fortawesome%2ffontawesome-pro" finished with status code 404.
verbose 0.935 Error: Couldn't find package "@fortawesome/fontawesome-pro" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Couldn't find package "@fortawesome/fontawesome-pro" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by tagliala** [comment]
Any windows user knows if  `%20&&%20//` is normal?

**Comment by tagliala** [comment]
Ok, answering my self

```
@fortawesome:registry=https://npm.fontawesome.com/ && \
//npm.fontawesome.com/:_authToken=<KEY
```

That is a script for linux/macOS (and hopefully WSL?)

Please try to manually create an `.npmrc` file with the content you can find here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by Damo1155** [comment]
Thanks for the response, I'll give that a try first thing in the morning as I've logged off for the day. If it works I'll post on here and close the issue.

**Comment by Damo1155** [comment]
Thanks for the help, removing the `&& \` from the configuration fixes the issue.

I'd recommend modifying the documentation on the page you linked as it makes no mention that the `&& \` is for Linux/MacOS.

![image](https://user-images.githubusercontent.com/16608228/95420422-504ae600-0933-11eb-8d40-e8b6ab09ff36.png)

I've never worked on Linux/MacOS so was completely oblivious to that being specifically for those environments. Don't want others hitting this documentation issue in the future as I spent about 5-6 hours investigating and digging for an answer.

**Comment by tagliala** [comment]
@robmadole any chance to 

1. Split the command lines into two separate ones; or
2. Provide a single-line version which works for both linux and windows; or
3. Specify it is for for linux only?

**Comment by StudentBOU** [comment]
give us a screenshot of the commands you enter

**Comment by tagliala** [comment]
> give us a screenshot of the commands you enter

Sorry, I do not understand this comment

However, we have a brand new troubleshooting guide for node package managers available at https://fontawesome.com/docs/web/setup/packages#_5-troubleshooting-your-configuration
