### ISSUE TITLE
fa-adobe - what happened to it?

### ISSUE THREAD

**Issue by jjgleim** [FortAwesome/Font-Awesome#17242]
What happened to the Adobe icon fa-adobe?  

**What can it be used for?**
I create posts for my school district and many of the posts I publish relate to Adobe and Creative Cloud.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We've got a copyright claim by Adobe

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150

Hope it helps

closing here

**Comment by jjgleim** [comment]
Nevermind.  Saw the info in the changelog which is really disappointing.

https://fontawesome.com/changelog/latest

**Comment by jjgleim** [comment]
Thanks for responding.
