### ISSUE TITLE
Feature request: Same size icons

### ISSUE THREAD

**Issue by erickrubiales** [FortAwesome/Font-Awesome#17250]
**Is your feature request related to a problem? Please describe.**
I have problems with spacing between icons

**Describe the solution you'd like**
I need a library with same size icons e.g. 16px. x 16px

**Describe alternatives you've considered**
I have no idea

**Additional context**
The next image happens when I set a same width for all icons. 
<img width="418" alt="Screen Shot 2020-10-07 at 17 13 44" src="https://user-images.githubusercontent.com/6951331/95382713-75ead780-08c0-11eb-9618-983e5470277b.png">

**Feature request checklist**
- [ ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome uses icons with different width by design choice

CSS implementation has an helper class, `fa-fw`, to horizntally center icons in a display of a fixed width

Does this help?
