### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by hamoud333310** [FortAwesome/Font-Awesome#17251]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.
280DEV Community 👩‍💻👨‍💻
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Please fix the title and provide an example. If the request is a brand, please also provide information about the brand

**Comment by hamoud333310** [comment]
لا موعلامه تحاريه

‫في الأربعاء، 7 أكتوبر 2020 في 11:58 م تمت كتابة ما يلي بواسطة ‪Geremia
Taglialatela‬‏ <‪notifications@github.com‬‏>:‬

**Comment by tagliala** [comment]
> لا موعلامه تحاريه

as per google translate: "Not a brand"

Ok thanks.

Can I have further clarifications?

Please:
1. Fix the title (e.g.: `Icon request: icon-car`)
2. Provide a single color, 16px icon size suitable example (e.g:)

![image](https://user-images.githubusercontent.com/556268/96337432-7422d000-1087-11eb-8696-a69f147310d1.png)

Please remember that email attachments don't work

Use the website at https://github.com/FortAwesome/Font-Awesome/issues/17251

**Comment by aethior** [comment]
@tagliala I think you can close here.
