### ISSUE TITLE
Icon request: icon-bandcamp

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1725]
bandcamp
icon-bandcamp

**Comment by UndeadRedPanda** [comment]
+1

**Comment by resonancedesign** [comment]
+1

**Comment by mmarquez** [comment]
+1

**Comment by Hellseher** [comment]
+1

**Comment by Ardakilic** [comment]
+1

**Comment by oguzhanaslan** [comment]
+1

**Comment by idleberg** [comment]
+1

**Comment by noahdayan** [comment]
+1

**Comment by Jelkster** [comment]
+1

**Comment by jantequera** [comment]
+1

**Comment by antodippo** [comment]
+1

**Comment by sdjespersen** [comment]
+1

**Comment by jarvelov** [comment]
+1

**Comment by chibitheunicorn** [comment]
+1

**Comment by alebx** [comment]
+1

**Comment by 3eBoP** [comment]
+1

**Comment by gmmarc** [comment]
+1

**Comment by ironoxidey** [comment]
+1

**Comment by sidewalkdriver** [comment]
+1

**Comment by chajoe** [comment]
+1

**Comment by benpolinsky** [comment]
+1

**Comment by Satak** [comment]
+1

**Comment by powlow** [comment]
+1

**Comment by trixbengel** [comment]
+1

**Comment by terrybolontine** [comment]
+1

**Comment by carriep63** [comment]
+1

**Comment by brentoneill** [comment]
+1

**Comment by rdewolff** [comment]
+1

**Comment by 20100FR** [comment]
+1

**Comment by planetariumarts** [comment]
+1

**Comment by Navin108** [comment]
+1

**Comment by rollerz** [comment]
+1

**Comment by silentFred** [comment]
+1

**Comment by adrianricardo** [comment]
+1

**Comment by jaumeavila** [comment]
+1

**Comment by ItsHamty** [comment]
+1

**Comment by odhs** [comment]
+1

**Comment by vertiges** [comment]
+1

**Comment by KhyamAllami** [comment]
+1

**Comment by sangrita22** [comment]
+1 please

**Comment by julientonton** [comment]
+1 please

**Comment by Elmolesto** [comment]
+1

**Comment by riwal** [comment]
:+1:

**Comment by juancarlosfarah** [comment]
+1

**Comment by fredbegin11** [comment]
+1

**Comment by simmons6** [comment]
+1

**Comment by Cojomax99** [comment]
+1

**Comment by okushama** [comment]
+1

**Comment by fkaa** [comment]
+1

**Comment by medsouz** [comment]
:+1:

**Comment by Corosauce** [comment]
:+1:

**Comment by rakiru** [comment]
+1

**Comment by soycode** [comment]
+1 and also would be nice to have a -square version.

**Comment by murasame78** [comment]
Any recent news ? 

+1

**Comment by Balauue** [comment]
+1

**Comment by Zetalia** [comment]
+1

**Comment by hlilje** [comment]
+1

**Comment by noyz319** [comment]
+1

**Comment by gmiddleb** [comment]
+1, please oh please

**Comment by takeaweb** [comment]
hi! +1 for the bandcamp icon, please
thank you! :-)

**Comment by yurrriq** [comment]
:+1:

**Comment by cryptostrophe** [comment]
+1!

**Comment by exoentropy** [comment]
+1

**Comment by xTear** [comment]
+1

**Comment by mindundermohawk** [comment]
+1!

**Comment by azeos** [comment]
+1

**Comment by ryanbarringtoncox** [comment]
+1

**Comment by jtg567** [comment]
+1

**Comment by eubenesa** [comment]
+1

**Comment by boulund** [comment]
+1

**Comment by mskalandunas** [comment]
+1

**Comment by trollverk** [comment]
+1

**Comment by thur3os** [comment]
+1

**Comment by elainaleone** [comment]
+1

**Comment by pdinklag** [comment]
+1

**Comment by squarecandy** [comment]
+1

**Comment by computerartsde** [comment]
+1 ... please

**Comment by squarecandy** [comment]
Here's my slightly insane temporary workaround until the official fa-bandcamp comes out:

`<span class="fa-stack"><i class="fa fa-eraser fa-stack-1x"></i><i class="fa fa-eraser fa-rotate-180 fa-stack-1x"></i><i style="padding-left:0.4em;" class="fa fa-eraser fa-stack-1x"></i><i style="padding-right:0.4em;" class="fa fa-eraser fa-rotate-180 fa-stack-1x"></i></span>`

Crazy what you can do with font-awesome!

**Comment by pll33** [comment]
+1

**Comment by julientonton** [comment]
+2

**Comment by andyesp** [comment]
+1

**Comment by skylergreene** [comment]
+1

**Comment by ajoyousworker** [comment]
+1

**Comment by dshoreman** [comment]
+1. Something like this would be perfect, in either circle or square versions:
![bandcamp-blk](https://cloud.githubusercontent.com/assets/1521802/11919710/fe424972-a751-11e5-91b7-a9804a3f8058.png)

Original white png below. Black version posted above for visibility
![bandcamp](https://cloud.githubusercontent.com/assets/1521802/11919719/52f5b63e-a752-11e5-898f-a3310434a3ed.png)

**Comment by christophersisk** [comment]
+1

**Comment by Emnaon** [comment]
+1

**Comment by emmawinston** [comment]
+1.

**Comment by benjaminmarsico** [comment]
+1!

**Comment by codynguyen1116** [comment]
+1

**Comment by kofdog** [comment]
+1

**Comment by heyjones** [comment]
+1

**Comment by LiamSauve** [comment]
+1

**Comment by precabal** [comment]
+1

**Comment by jamband** [comment]
+1

**Comment by zGreg** [comment]
+1 please :) 
And thanks for the good work

**Comment by sixkilleraz** [comment]
+1

**Comment by pjohnst2** [comment]
+1

**Comment by newdensity** [comment]
+1

Bands and record labels need this.

**Comment by acenkus** [comment]
+1

**Comment by clodewerks** [comment]
+1

**Comment by antonisloizou** [comment]
+1

**Comment by richsoni** [comment]
+100

**Comment by computerartsde** [comment]
common! ... please - all musicians needs this icon! +1

**Comment by maylortaylor** [comment]
+1 !!

**Comment by kevincompton** [comment]
Well they completely ignored our request for this useful sensible icon but hey, at least they added a castle. Stupid

**Comment by emmawinston** [comment]
Yeah, I'd be interested to know why they appear to be ignoring the most requested icons on Github. Is there any logic to what gets selected, I wonder?

**Comment by newdensity** [comment]
Does there need to be an Assignee?  The sidebar says there isn't one.  Anyways, I agree and fail to see how this Icon could be set aside and not even attempted by them.  There's a soundcloud.  Bandcamp is probably even more important nowadays.

**Comment by internethering** [comment]
+1

**Comment by squarecandy** [comment]
I disagree with the logo suggested by @dshoreman 

I think we just need the simple parallelogram logo to match the simplicity of fa-twitter, fa-facebook, fa-soundcloud, etc.
![](http://squarecandy.github.io/images/Screenshot%202016-03-10%2018.50.14.png)

A "square" version of it would be nice too, as in fa-twitter vs fa-twitter-square.

A logo kit that includes EPS files is available from bandcamp here: https://bandcamp.com/img/buttons/bandcamp-button-circle-whiteblack.zip

@tagliala - any news on if this will be included in the near future? If this is not on the list of planed additions, can you let us know why?

@kevincompton - the castle is the logo for their new paid service "fort awesome". Let's all take a moment to appreciate how wonderful and how free font awesome is, bandcamp icon or no.

Please let us know if there is anything we can do to help move this forward.  Thanks!

**Comment by dshoreman** [comment]
@squarecandy All the other brand icons are blessed with actual recognisable icons (the bird for Twitter) or styled letters (The `f` in Facebook/Foursquare, or `Be` in Behance) so people know what they are. The bandcamp icon in its simplest form doesn't have that luxury.

Based on the [official icons](https://bandcamp.com/buttons) I'd probably go with [the parallelogram with `bc` text](https://bandcamp.com/img/buttons/bandcamp-button-bc-circle-black-512.png) next to it.<sup>[[zip]](https://bandcamp.com/img/buttons/bandcamp-button-bc-circle-black.zip)</sup> It's a nice compromise between too much text, and such little detail that it's nothing more than an ordinary shape.

**Comment by squarecandy** [comment]
I would argue that `fa-twitter` is just a bird unless you know twitter's branding - there's no "tw" next to the bird. `fa-facebook` is just the letter F, etc. I think if a user is familiar with bandcamp just the parallelogram will be sufficient to make the inference and if a user is not familiar with bandcamp they still won't know what it is if the logo has "bc" next to it. I also think it's important that it fit within the generally "approximately square" aspect ratio of all the other social icons.

I do see your point that just the shape is very simple. I mean ideally we could have one that is just the shape and one that says bc or bandcamp like `fa-youtube` vs `fa-youtube-play`.  

It seems our main challenge is to convince them to just add it at all - I would be happy to have it added no matter how they choose to implement it.

**Comment by Antimatzist** [comment]
+1

This would be really really cool. I think all thre choices, square, circle and the simple parallelogram (https://bandcamp.com/buttons) should be added. This is a must for every band that uses bc. I wonder why this request is ignored. Soundcloud does exist...

**Comment by clickysteve** [comment]
Would be great to see this happen sooner rather than later.

**Comment by Potato83** [comment]
+1

**Comment by claudiaii** [comment]
+1

**Comment by richsoni** [comment]
This has been working for me while I am waiting:

.fa-bandcamp::before {
  content: "b";
  background: black;
  width: 1em;
  color: transparent;
  display: inline-block;
  height: 1em;
  transform: skew(-25deg);
  -webkit-transform: skew(-25deg);
  -moz-transform: skew(-25deg);
  -ms-transform: skew(-25deg);
  -o-transform: skew(-25deg);
}

**Comment by thedrc123** [comment]
+1

**Comment by nontoxicmike** [comment]
+1

**Comment by heyjonmanning** [comment]
+1

**Comment by rodobodolfo** [comment]
+1 !!

**Comment by schmeter** [comment]
+1

**Comment by haloproject** [comment]
+1

**Comment by andylincoln** [comment]
+1

**Comment by vdaluz** [comment]
+1

**Comment by macrocosme** [comment]
+1

**Comment by drieschel** [comment]
+1 

A bandcamp logo would be (font-)awesome!^^

**Comment by peric** [comment]
+1

**Comment by rayjon** [comment]
+1

**Comment by lenina101** [comment]
+1

**Comment by N30N173** [comment]
+1

**Comment by BradySmith6357** [comment]
+1

**Comment by MEDIAMACHINE** [comment]
+1

**Comment by duberton** [comment]
+1

**Comment by plinplon** [comment]
+1

**Comment by erro** [comment]
+1

**Comment by newpxsn** [comment]
+1

**Comment by kfirlevari** [comment]
My two cents:
.fa-bandcamp::before {
content:"▱";
top: 94%; 
-webkit-transform: translate(0, -6%); 
transform: translate(0, -6%);
}

**Comment by ohwillie** [comment]
+1

**Comment by MakeWeirdMusic** [comment]
+1

**Comment by logol** [comment]
+1

**Comment by bkaminski** [comment]
+1

**Comment by enelbus** [comment]
+1

**Comment by Pavelitooo** [comment]
+1

**Comment by anahamkarah** [comment]
+1

**Comment by juyeongkim** [comment]
+1

**Comment by A-Au** [comment]
👍

**Comment by mareksl** [comment]
+1

**Comment by krisrobinson** [comment]
+1

**Comment by LunkRat** [comment]
+11

**Comment by LunkRat** [comment]
@kfirlevari thanks for the snippet, it's brilliant!

**Comment by jamie-f** [comment]
+1 please :)

**Comment by qrenz** [comment]
+1

**Comment by vheimpel** [comment]
+1

**Comment by propagated** [comment]
+1

**Comment by matimatoox** [comment]
+1 ... no news for bandcamp icon?

**Comment by waspeer** [comment]
+1

**Comment by nathansh-mec** [comment]
👍

**Comment by davegandy** [comment]
Circle with parallelogram inside is the simplest and I think identifiable. That's what we'll use.

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch. Closing.

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch. Closing.

**Comment by peric** [comment]
Where can we expect official release of 4.7.0?

**Comment by ziomyslaw** [comment]
using a content from fa-square and rotate it as @richsoni did, the effect is as @squarecandy proposed

```
.fa-bandcamp::before {
	content: "\f04d";  //fa-square content
	display: inline-block; //inline elements can't be transformed
	transform: skew(-25deg);
	-webkit-transform: skew(-25deg);
	-moz-transform: skew(-25deg);
	-ms-transform: skew(-25deg);
	-o-transform: skew(-25deg);
}

```
@richsoni example doesn't work with fa-stack, but present work

```
<span class="fa-stack fa-2x">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-bandcamp fa-stack-1x fa-inverse-dark"></i>								
</span>
```
