### ISSUE TITLE
Feature Request: Icons associated with Wolfram Language 

### ISSUE THREAD

**Issue by sunandopatra** [FortAwesome/Font-Awesome#17256]
I have been searching for icons associated with the Wolfram Language, e.g., for Mathematica, Wolfram Language, Wolfram Alpha, etc., in the [fontawesome ](https://fontawesome.com/) site, and there are none. Given the span of brand icons covered, it's surprising that none of these are there.

I would like to see these in the icons list.

There is [another related open issue](https://github.com/FortAwesome/Font-Awesome/issues/4226), but it talks just about Wolfram Alpha.

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> There is another related open issue, but it talks just about Wolfram Alpha.

Please open new individual requests for each icon
