### ISSUE TITLE
Icon request: invitation

### ISSUE THREAD

**Issue by inland-rob** [FortAwesome/Font-Awesome#17263]
**What can it be used for?**
Icon for sending an invitation - as in an invitation to sign up to a web site or service

**Example image (optional)**
Many here: https://www.google.com/search?q=invitation+icon&rlz=1C5CHFA_enUS909US909&oq=invitation+icon&aqs=chrome..69i57j0j0i22i30l5j69i60.2205j0j7&sourceid=chrome&ie=UTF-8

The matched pair part of this request would be to create a "resend invitation" for cases where a web site admin has to resend a previously sent invitation. Perhaps use the invitation created above with an overlay of the fa-undo circle arrow, but with a clockwise arrow (because it is in the future)

**Icon request checklist**
- [✓] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✓] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✓] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✓] I have included at least one example image if it could be helpful (optional)
- [✓] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as [envelope-open-text](https://fontawesome.com/icons/envelope-open-text?style=solid)

If you have something different in mind, please provide a single color, 16px icon size suitable example

Hope it helps

Closing here

@talbs any chance to manually add `invitation` to the search list?

**Comment by inland-rob** [comment]
Geremia - please re-read the request.
This is not for an open envelope. It is for resending an invitation.

**Comment by tagliala** [comment]
> This is not for an open envelope. It is for resending an invitation.

Will definitely reopen, but please edit the original request:

1. Change the title. Invitation is too generic, if the request is for a re-invitation. Also, prefer concrete objects as per our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome) _The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)_
2. Provide a single color example of the icon you are requesting. The google link shows icons like `fa-envelope-open-text`

If you need something like `fa-envelope-open-text-redo`, you can achieve that icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/2s30azyt/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
