### ISSUE TITLE
Icon request: Push-Like

### ISSUE THREAD

**Issue by salsakungen** [FortAwesome/Font-Awesome#1726]
Hi!
I run a pinterest inspired community and I'm in need of a new, specific icon. The icon purpose is to encurage users to share images or videos they like.The existing Push-pin icon is "to much Pinterest" and feels overused. I think there's room for a alternative icon for this common purpose in your icon set.

![awsomefonts](https://f.cloud.github.com/assets/5173584/916419/866fb72e-fe8c-11e2-84bf-db082190d5b8.jpg)

**Comment by aethior** [comment]
Duplicate of #2106.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks, nice catch
