### ISSUE TITLE
facebook icons not working in cheatsheet

### ISSUE THREAD

**Issue by gstlouisgit** [FortAwesome/Font-Awesome#17269]
**Describe the bug**
I ahve tried to do an import with 
/*  @import url("https://use.fontawesome.com/releases/v5.8.1/css/all.css");  */
/*@import url("https://use.fontawesome.com/releases/v5.8.2/css/all.css"); */
@import url("https://use.fontawesome.com/releases/v5.0.0/css/all.css"); 
from this site cheatsheet
https://www.fontawesomecheatsheet.com/font-awesome-cheatsheet-5x/
or
https://www.fontawesomecheatsheet.com/

none of the facebook ones work?  I can only use pseudo for what I'm working on 

**Expected behavior**
the other icons in the list work fine

**Bug report checklist**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.



`fontawesomecheatsheet.com` is a third party service and we do not provide support for third party libraries, sorry

> the other icons in the list work fine

Maybe it is related to adblock? #1799 

If you still think there is an issue with font awesome, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), and provide a reproducible test case

Hope it helps

Closing here
