### ISSUE TITLE
Icon request: folder-slash, file-slash

### ISSUE THREAD

**Issue by somethingSTRANGE** [FortAwesome/Font-Awesome#17265]
**What can it be used for?**
The proposed icons would complement the existing file and folder icons and cover the "hidden" or "missing" state.

The new icons could be used to represent a missing or hidden file or folder. or more likely a tool state that represents many files or folders in the view. For example, to indicate a sparsely populated SVN workspace where some files/folders have been excluded from the checkout.

**Example image**
Matching the style of the other "slashed" icons:
<img src="https://user-images.githubusercontent.com/6905832/95800493-5a127780-0cac-11eb-9de7-b44a0eb68444.png" alt="folder-slash-solid" width="160"/>
<img src="https://user-images.githubusercontent.com/6905832/95800496-5aab0e00-0cac-11eb-889a-34e8f0d65250.png" alt="folder-slash-regular" width="160"/>

<img src="https://user-images.githubusercontent.com/6905832/95800494-5aab0e00-0cac-11eb-835f-33d3cae212e3.png" alt="file-slash-solid" width="160"/>
<img src="https://user-images.githubusercontent.com/6905832/95800497-5b43a480-0cac-11eb-8ad1-c23bf590448e.png" alt="file-slash-regular" width="160"/>

Alternative/additional dotted outline versions could be useful.
![folder-missing-regular](https://user-images.githubusercontent.com/6905832/95801088-19b3f900-0cae-11eb-93a6-82f64dbc8f9f.png)
![file-missing-regular](https://user-images.githubusercontent.com/6905832/95801087-19b3f900-0cae-11eb-83f7-1fc81ea570e9.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/443/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by somethingSTRANGE** [comment]
That's good to know. I have been using Font Awesome exclusively in app development at this point, which uses the font file directly, and not SVG files or CSS. I would love to use the duotone icons, but that's really not possible on desktop apps that don't utilize web client rendering.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
