### ISSUE TITLE
Icon request: icon-fan

### ISSUE THREAD

**Issue by turner72** [FortAwesome/Font-Awesome#17270]
Since font-awesome icons are often used in node red, an icon set for a fan (ventilator) would be nice.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a [fan](https://fontawesome.com/icons/fan?style=solid) available in FA Free and a [fan-table](https://fontawesome.com/icons/fan-table?style=solid) available in FA Pro

If you have something different in mind, feel free to open a new request by filling out our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md), with a different title and an example of the icon you have in mind

Closing here
