### ISSUE TITLE
Icon MIssing: fa-ticket icon

### ISSUE THREAD

**Issue by lokeshsn22** [FortAwesome/Font-Awesome#17272]
Hi Team, 

 The below mentioned icon is missing in the latest font-awesome code. Can you please update the same 

   https://fontawesome.com/v4.7.0/icon/ticket

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community

`ticket` is available as `ticket-alt` in Font Awesome 5 Free

Ref:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
- https://fontawesome.com/icons/ticket-alt

Hope it helps

Closing here
