### ISSUE TITLE
Icon request: ROS, Gazebo, MoveIt icons (Robotics-Community related)

### ISSUE THREAD

**Issue by liangyuwei** [FortAwesome/Font-Awesome#17282]
**What can it be used for?**
Some open-source platforms related to robotics, such as ROS, Gazebo, and MoveIt, could be used for describing one's skillsets.

**Example image (optional)**
*1. ROS*
![image](https://www.ros.org/wp-content/uploads/2013/10/rosorg-logo1.png)
Source: [https://www.ros.org//](url)

*2. Gazebo*
![image](http://gazebosim.org/assets/gazebo_vert-af0a0ada204b42b6daca54e98766979e45e011ea22347ffe90580458476d26d6.png)
Source: [http://gazebosim.org/](url)

*3. MoveIt*
![image](https://moveit.ros.org/assets/logo/moveit_logo-white.png)
(Text is white, in black background..)
Source: [https://moveit.ros.org/](url)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Please split this request into three separate ones

**Comment by tagliala** [comment]
@liangyuwei thanks

New requests fixed and labeled
