### ISSUE TITLE
ICON: Medium logo was changed

### ISSUE THREAD

**Issue by sabesansathananthan** [FortAwesome/Font-Awesome#17281]
**What can it be used for?**
Medium is an online publishing platform. People could add the medium button on their website

**Example image (optional)**

![uazw6gFQuEC29mxMM55Tpb](https://user-images.githubusercontent.com/36799589/96227773-3acc6080-0fb2-11eb-837f-f5026d472969.jpg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up.

I can definitely see the new logo, but still no updates on the official branding guidelines and on the github repo.

I've added "waiting for feedback" label, please help me to check when the official assets will be available

Ref:
- https://help.medium.com/hc/en-us/articles/213481348-Medium-Logos-Brand-Guidelines
- https://medium.design/logos-and-brand-guidelines-f1a01a733592
- https://github.com/medium/medium-logos

**Comment by My1** [comment]
they changed their logo again? lol

**Comment by krankj** [comment]
I liked the previous one better!

**Comment by My1** [comment]
I liked the original one (yes it wasnt made for mono, but I liked the design)

**Comment by sabesansathananthan** [comment]
Now they updated their logo on the official sites.  @tagliala

**Comment by tagliala** [comment]
Thanks for the update, now we have official files in the repo https://github.com/medium/medium-logos

Let's also ping @sensibleworld

**Comment by sabesansathananthan** [comment]
@tagliala Will you update? Waiting .....

**Comment by tagliala** [comment]
Hi, the new logo will be released in the second alpha of Font Awesome 6

No ETA yet, sorry

**Comment by sensibleworld** [comment]
Yup. This is already in the latest Alpha of v6: https://fontawesome.com/download. I'll see what we can do to get a spot release of brand icons out sooner, though.

**Comment by sabesansathananthan** [comment]
Is there any CDN link for v6 alpha

**Comment by sensibleworld** [comment]
Not yet. We'll be adding more ways to use as we get into the Beta release. For now, the Alpha requires self-hosting. A workaround for the time being could be to use our icon upload feature as part of Font Awesome kits, and manually add the new logo there.
