### ISSUE TITLE
Icon request: icon-users-group-cogs (Operation Icon/Management Icon)

### ISSUE THREAD

**Issue by lutuandat0411** [FortAwesome/Font-Awesome#17307]
**What can it be used for?**
Icon will be used to show that a function relate to operation system or a link direct to operation system page

**Example image (optional)**
<img width="644" alt="Screen Shot 2020-10-23 at 12 01 52 PM" src="https://user-images.githubusercontent.com/37680849/96958466-c05a8e00-1527-11eb-8a93-342f8b81f6e1.png">

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The example looks too complex to be represented as an icon.

Icons should work also at small sizes (16px), do you have another example?

**Comment by lutuandat0411** [comment]
Thanks for your reply.
I will attach a new example for this icon below: 
![operationicon](https://user-images.githubusercontent.com/37680849/96967965-6fa06080-153a-11eb-8c66-dfa123904b5d.png)

**Comment by tagliala** [comment]
Ok thanks

I think that [users-cog] can fit your use case: https://fontawesome.com/icons/users-cog?style=solid

Does it?

**Comment by lutuandat0411** [comment]
Sure, i can. 
But I'll replace it if the icon requested by me appear in the next version.
Thanks a lot.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
