### ISSUE TITLE
Icon request: text editor icons like bold,italic

### ISSUE THREAD

**Issue by anshulhub** [FortAwesome/Font-Awesome#17302]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a lot of icons for text editors, please take a look here: https://fontawesome.com/icons?d=gallery&c=editors&m=free

If you want to request new icons, please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Closing here
