### ISSUE TITLE
Icon request: user-teacher and user-student icon

### ISSUE THREAD

**Issue by petr-slipek** [FortAwesome/Font-Awesome#17303]
**What can it be used for?**
Hi, in these days when online learning is much more important and icons representing teacher and student will be really usefull in projects where working with students, classes and teachers accounts. 

**Example image (optional)**
You have only user-graduate icon, but not icon for teachers or k-12 students and pupils. 

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a single-color, small icon size suitable examples of how those icons should look like?

I think that [chalkboard-teacher](https://fontawesome.com/icons/chalkboard-teacher?style=solid) can represent a teacher

**Comment by petr-slipek** [comment]
Hi,

chalkboard-teacher is not consistent icon with other user-* icons. In most icon packs the teacher is drawed with pointer in hand. Also how can application user separate functions which belongs to student and class and teacher. 

Now I can use:
chalkboard-teacher .... for teacher (not consistent with user- icon.)
user-class or users ... for classes
user or user-graduate ... for students 

so I am missing icon with user-* style representing teacher and students which are not in graduate level of education. It should look the same way, how you represent all other variants.

I have problems with uploading images... so please visit following urls for teacher and student icon examples
https://www.toglic.com/files/webfonts/request/teacher1.jpg
https://www.toglic.com/files/webfonts/request/teacher2.png
https://www.toglic.com/files/webfonts/request/teacher3.png (prefered style for user-teacher)
https://www.toglic.com/files/webfonts/request/student1.png
https://www.toglic.com/files/webfonts/request/student2.jpg

for user-student some icon, where there is a school bag on  user icon. 

Hope it helps you.

**Comment by tagliala** [comment]
Hi, 

thanks for the examples

The best way to proceed is to:
- Open new individual requests, one for teacher, one for student. you can edit the first post of this one and open a new one
- Explain why the existing icon does not fit the use case (your explanation is legit)
- Add the example inline on GitHub by using [Markdown](https://guides.github.com/features/mastering-markdown/). Avoid links, they may expire
- Prefer gender-neutral icons (`student2` is gender neutral, all the other ones aren't)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
