### ISSUE TITLE
Font Awesome Pro Registry Not Found

### ISSUE THREAD

**Issue by ScubaShneve** [FortAwesome/Font-Awesome#17304]
I followed the steps "Installing the Pro version of Font Awesome" found here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

In my app's root folder, I did the Global Set Up:
`npm config set "@fortawesome:registry" https://npm.fontawesome.com/`
then
`npm config set "//npm.fontawesome.com/:_authToken" TOKEN`
I replaced "TOKEN" with the Guid found under "Pro npm Package Token".

I then ran:
`npm install --save @fortawesome/fontawesome-pro`

In my package-lock.json file, I have:

```
"@fortawesome/fontawesome-free": {
      "version": "5.15.1",
      "resolved": "https://registry.npmjs.org/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.1.tgz",
      "integrity": "sha512-MyValueHere"
    },
    "@fortawesome/fontawesome-pro": {
      "version": "5.15.1",
      "resolved": "https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/5.15.1/fontawesome-pro-5.15.1.tgz",
      "integrity": "sha512-MyValueHere"
    },
```

I am able to run it and see all of the icons.  I checked this all into Git.  Another developer pulled down my branch.  He ran, `npm install` in the app's root folder and got this error:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2ffontawesome-pro - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/fontawesome-pro@5.15.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'manage'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Why is the registry not found and it failing to install fontawesome pro for him?

**Comment by tagliala** [comment]
Hi,

```
GET https://registry.npmjs.org/@fortawesome%2ffontawesome-pro
```

npm is not getting the correct configuration, so I guess that your colleague does not have its `.npmrc` configured.

I would not configure .npmrc globally and prefer a per-repository setting, so you can use both Font Awesome Pro and Font Qwesome free

> Why is the registry not found and it failing to install fontawesome pro for him?

I would commit `.npmrc` into the repository, without the token.

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONT_AWESOME_AUTH_TOKEN}
```

then set an environment variable `FONT_AWESOME_AUTH_TOKEN=your-token`

Does this help?

**Comment by ScubaShneve** [comment]
@tagliala thank you for that information and explanation.  Our app has sub-apps and when I was reading the tutorial about global settings, I was thinking globally for all the sub-apps.  Setting the registry up as you mentioned, which is the way the "Per Project" part of the tutorial explains fixed the issue.  Thanks again.

**Comment by nayana1989** [comment]
I experienced the same error today.
```
➤ YN0027: @fortawesome/fontawesome-pro@unknown can't be resolved to a satisfying range
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro`
```
I'm already configured. .npmrc
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=[AUTH_CODE]
```

**Comment by MemeDeveloper** [comment]
I had similar issues. Docs seem out of date / incorrect. I found that the format of .npmrc file like this: 

```
npmScopes:
fortawesome:
  npmAlwaysAuth: true
  npmRegistryServer: "https://npm.fontawesome.com/"
  npmAuthToken: XXXXX
```
  
**Did not seem to work**. While this: 

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXX
```

**Did.** 

N.B. I also updated npm with 

`npm install -g npm@latest `

And found this command useful to check the settings in the .npmrc file  
  
`npm config ls -l`

**Comment by SujitSingh** [comment]
Mentioned error stills occurs.
All installation options mentioned in the [2nd step "Add Icon Packages"](https://docs.fontawesome.com/web/use-with/react#2-add-icon-packages) throws error of missing registry.

![Screenshot 2024-04-17 134752](https://github.com/FortAwesome/Font-Awesome/assets/26189654/67b9ed8f-3ca1-4f6d-bbcc-f4e848cb8ad6)

I haven't tried adding local configuration, but I believe that shouldn't be a necessary step in normal cases. 

**Edit -** 
If someone still stuck with this error, as per [Package Manager Usage](https://docs.fontawesome.com/web/setup/packages#1-configure-pro-package-access) instructions, you can skip all those steps and install [free icons package](https://docs.fontawesome.com/web/setup/packages#the-free-packages).

**Comment by tagliala** [comment]
Hi, please double check the following:

1. The project folder contains a `package.json`
2. `npm` is configured for kit packages as explained in https://docs.fontawesome.com/web/setup/packages#for-kit-packages
3. The kit is configured to be used as a npm package: `https://fontawesome.com/kits/{KIT_CODE}/settings`
  ![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/7bbc5d7f-aec6-497c-8085-d39d17c48aa7)
4. `KIT_CODE` has been replaced with your kit code

I can confirm that by following these instructions the kit download through npm works

![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/38a220af-8574-49e3-9370-4ec7f53550df)

---

PS: You have better instructions at `https://fontawesome.com/kits/{KIT_CODE}/package`

![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/97cf9184-8301-42af-b779-e68eea68422a)


---

PS2: We can't do too much on the free repo for this kind of issues, they may be related to license or something else. As a Pro customer, you can ask for private support to hello@fontawesome.com
