### ISSUE TITLE
The kit loads the same ID on multiple calls

### ISSUE THREAD

**Issue by linab** [FortAwesome/Font-Awesome#17301]
WCAG2 (AA) 4.1.1 (F77)
Duplicate id attribute value "font-awesome-5-kit-css" found on the web page.

Is there a way for the kit to load unique IDs or to use classes instead?

![Screen Shot 2020-10-21 at 2 40 21 PM](https://user-images.githubusercontent.com/4512894/96768274-b0b63a80-13ab-11eb-9c8a-80394e414ef4.png)
![Screen Shot 2020-10-21 at 2 40 35 PM](https://user-images.githubusercontent.com/4512894/96768340-c461a100-13ab-11eb-889b-70a7d04f028e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IIRC this has been fixed. Could you please retry to regenerate your kits (just save them)?

**Comment by linab** [comment]
This works, thanks!

**Comment by tagliala** [comment]
Welcome, glad you solved

Ref: #16149
