### ISSUE TITLE
Install issue with Yarn Version 2

### ISSUE THREAD

**Issue by Fibs7000** [FortAwesome/Font-Awesome#17317]
**Describe the bug**
When upgrading from yarn 1 to yarn 2 installing fontawesome does not work anymore...

**To Reproduce**
```bash
#make new folder
mkdir test
cd test
#create empty project
yarn init -y
#set yarn version to 2. (without doing this step it works)
yarn set version berry
#add the pro package
yarn add @fortawesome/fontawesome-pro
```

**Expected behavior**
It should install as expected.

**Screenshots**
```bash
yarn add @fortawesome/fontawesome-pro
➤ YN0027: @fortawesome/fontawesome-pro@unknown can't be resolved to a satisfying range:

HTTPError: Response code 404 (Not Found)
    at o.<anonymous> (C:\Development\SeekInnovation\test\.yarn\releases\yarn-berry.js:23:12912)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

➤ Errors happened when preparing the environment required to run this command.
```
**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by Fibs7000** [comment]
Found the solution:

Just add this to your Yarn config.

```diff
plugins:
  ...

yarnPath: .yarn/releases/yarn-berry.js

+ npmRegistries:
+     //npm.fontawesome.com/:
+       npmAuthToken: ffffffff-ffff-ffff-ffff-ffffffffffff
+ npmScopes:
+     fortawesome:
+       npmRegistryServer: https://npm.fontawesome.com/  
```


Please add this to the documentation!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment Font Awesome does not officially provide instructions for Yarn 2

Let's continue on #16156

There is also a question from my side
