### ISSUE TITLE
game-board-alt's checkered pattern warps unexpectedly

### ISSUE THREAD

**Issue by JeremyTCD** [FortAwesome/Font-Awesome#17321]
**Describe the bug**
Hi! game-board-alt's checkered pattern warps unexpectedly.

**To Reproduce**
1. Navigate to https://fontawesome.com/icons/game-board-alt?style=solid.
2. Note the checkered pattern, warping is especially pronounced in the smallest image.

**Expected behavior**
Should not warp.

**Screenshots**
![fa-bug](https://user-images.githubusercontent.com/11733898/97256346-bdc0a700-184d-11eb-986a-1c4b4582217c.png)

At 16 px x 16 px:
![warping](https://user-images.githubusercontent.com/11733898/97256622-7d155d80-184e-11eb-8076-367458582f80.png)

**Version and implementation**
Version: 5.9.0
Browser and version: Chrome  86.0.4240.111

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This is all fixed up in the latest release of the v6 alpha: https://fontawesome.com/download
