### ISSUE TITLE
Icon request: incomplete-tally (tally without slash)

### ISSUE THREAD

**Issue by gffelisberto** [FortAwesome/Font-Awesome#17328]
**What can it be used for?**
Display incomplete number of something. Example: Incomplete reports, incomplete state for an action

**Example image (optional)**
( create a version without the stroke to represent the incomplete state )
https://fontawesome.com/icons?d=gallery&q=tally 

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
<img width="646" alt="Screen Shot 2020-11-02 at 2 02 38 PM" src="https://user-images.githubusercontent.com/529604/97907995-12639680-1d14-11eb-9081-e06c2c92dc73.png">

We've got this coming to version 6!

**Comment by sensibleworld** [comment]
(It's available now as part of the alpha release: https://fontawesome.com/download
