### ISSUE TITLE
bacteria not showing

### ISSUE THREAD

**Issue by SuusHex008000** [FortAwesome/Font-Awesome#17325]
the bacteria icon shows up as free icon but when I copy the icon code the icon is not showing. Now I'm using the viruses icon witch does show.

I don't know why the bacteria icon is not showing
<i class="fas fa-bacteria"></i>

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.
CSS Demo: https://jsfiddle.net/tagliala/0x1qe4by/7/
SVG Demo: https://jsfiddle.net/tagliala/7xb2e854/4/

[ice-cream](https://fontawesome.com/icons/bacteria?style=solid) has been introduced in Font Awesome 5.14.0, so please double check that you are using Font Awesome 5.14.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here
