### ISSUE TITLE
Icon request: fa-print-thermal

### ISSUE THREAD

**Issue by alfvicente** [FortAwesome/Font-Awesome#17330]
**What can it be used for?**
To help identify the proper printer when there are multiple types of printing media, in this case for thermal paper (i.e. Epson TM-T20 printers and such)

**Example image (optional)**
![Screenshot_2020-10-28 Título Ticket, check, coupon, printing, paper, recipe, getting icon](https://user-images.githubusercontent.com/26693592/97497572-79b2cc80-1949-11eb-89e5-892b75fd589c.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/receipt?style=solid fit this use case?

**Comment by alfvicente** [comment]
Thank you @tagliala, I'll give it a try. I swear I couldn't find anything like it, tried "ticket", "thermal", etc.
