### ISSUE TITLE
Ultralight version of icons

### ISSUE THREAD

**Issue by jbranc** [FortAwesome/Font-Awesome#1733]
it would be cool if we could have 'ultralight' versions of the images. essentially thin versions of most all icons, much like the new glyphish as it adapts to ios7.

supporting font-weight:300 would be amazing, but a _thin version is probably more inline with how font-awesome works.

**Comment by homerjam** [comment]
+1

**Comment by knownasilya** [comment]
:+1:

**Comment by deepakkj** [comment]
+1

**Comment by n-amabile** [comment]
+1

**Comment by astralspark** [comment]
Could You please do something about that? Some of the icons looks too bold. Lighter version, at least some of them would be awesome. For me - lighter version of search icon. It's not the first request though. [https://github.com/FortAwesome/Font-Awesome/issues/8486](url)

**Comment by IanSd** [comment]
At larger sizes most of the outlined or stroked icons look icons look heavy.

I would suggest thinner strokes on all the outlined icons  fa-thin or fa-light.
