### ISSUE TITLE
v6 alpha: duotone.less contains scss-like code

### ISSUE THREAD

**Issue by shanewhitehead** [FortAwesome/Font-Awesome#17354]
**Describe the bug**
The duotone.less file contains a number of references to the fa-content function that seems to actually be a scss function.
It only seems to occur on icons that as ALIASES of other icons

**To Reproduce**
Add an icon for "fad fa-contact-card" to a page. It does not render as expected

In the less file, the address-card looks fine, the contact-card has the erroneous fa-content reference:

.fad.@{fa-css-prefix}-address-card:after, .fa-duotone.@{fa-css-prefix}-address-card:after { content: "\10f2bb"; }
.fad.@{fa-css-prefix}-contact-card:after, .fa-duotone.@{fa-css-prefix}-contact-card:after { content: **fa-content(**\10f2bb); }

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
The alias icons should render the same as the originals

**Screenshots**
This image shows the 5 variations of the address card and 5 of the contact card 
![image](https://user-images.githubusercontent.com/73833064/97872558-25736800-1d0e-11eb-9f56-82239bdd9b50.png)
As you can ass, all render ok except the duotone contact card

**Version and implementation**
Version: 6 Alpha
Browser and version: Chrome (latest)

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@robmadole could you please take a look?

**Comment by deathnfudge** [comment]
Thanks for reporting this. We'll have this fixed in the next alpha release.

**Comment by talbs** [comment]
It looks like we've resolved this as of Alpha 2's release. I'm closing this, but please shout if you see something funny and thanks again for bringing this to our attention.
