### ISSUE TITLE
[Icon request] Oceania

### ISSUE THREAD

**Issue by lulibo** [FortAwesome/Font-Awesome#17365]
Hi,
there are icons only for 4 continents. There are [Europe](https://fontawesome.com/icons/globe-europe), [Africa](https://fontawesome.com/icons/globe-africa), [Americas](https://fontawesome.com/icons/globe-americas), [Asia](https://fontawesome.com/icons/globe-asia?style=regular), but Oceania is missing..
Is it possible to produce the Oceania icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Even if I can see Australia in `globe-asia` icon, I think that having a oceania-centric earth is legit, as it happened for `globe-europe` and `globe-africa`

@sensibleworld what do you think?

**Comment by sensibleworld** [comment]
Yup. This is a great request, and one we've heard before. I'll get it added to my list.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons?q=oceania
