### ISSUE TITLE
Site Very Very Slow!!!

### ISSUE THREAD

**Issue by paulsonjpaul** [FortAwesome/Font-Awesome#17369]
Hello. 
Whenever I go to fontawesome.com, it takes so much time to load (up to 1 minute!) and is so much irritating. Because of this reason, I tried to use other icon sets instead of Font Awesome but none reaches your standard. So, I came back to your site today and it still takes too much time to load. Icon searching has normal speed, but when I select my desired icon, nothing happens at all. Even if I keep clicking on the icon, it will not take me to that icon page. Because of that, I have to copy the link of that icon and go to it directly from the browser's address bar. Still, it takes a lot of time. And after it stops loading, I see a white background and nothing at all!!!

This is so much frustrating! Please fix this issue. Thanks in advance!

This is the first issue I have opened. Apologies if I did not provide as much information as possible.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for your feedback.

We know that Font Awesome website is slow and that is in the to-do list. Docs should be improved with the upcoming version 6

Any other information about your country and connection speed?

**Comment by paulsonjpaul** [comment]
Hi. Sorry for the late reply. I am from India. My connection speed is very good (4G). Any other questions?

**Comment by tagliala** [comment]
Nope, thanks

**Comment by paulsonjpaul** [comment]
So, you are saying that you will fix this in the upcoming version? If yes, when will the new version come?

**Comment by tagliala** [comment]
> So, you are saying that you will fix this in the upcoming version?

Working on documentation performance is on the to-do list

> If yes, when will the new version come?

Sorry, no ETA
