### ISSUE TITLE
Icon Request: cassette-tape

### ISSUE THREAD

**Issue by redengin** [FortAwesome/Font-Awesome#1736]
https://cdn3.iconfinder.com/data/icons/pictofoundry-pro-vector-set/512/Tape-128.png

A more traditional way to say "archive" on reel-to-reel or cassette tape.

**Comment by lickmydesign** [comment]
+1 aka 'voicemail', 'memo'

**Comment by kohenkatz** [comment]
:+1:

**Comment by Metalgrid** [comment]
+1, very nice for tape storage and/or voicemail.

**Comment by c00lz3r0** [comment]
+1

**Comment by stevenmills** [comment]
+1

**Comment by jperelli** [comment]
+1 is a basic thing to use a tape in a storage center. This is far more important than an umbrella! :)

**Comment by chevin99** [comment]
+1

**Comment by kawalsky** [comment]
For people wanting a more traditional cassette:

![tape](https://cloud.githubusercontent.com/assets/12035501/8832723/d935e634-30aa-11e5-97a5-ec7fc9b75b42.png)

https://d.maxfile.ro/adbjmorvmw.svg

**Comment by skiddychang** [comment]
+1 for the traditional one

**Comment by devilcius** [comment]
+1 for the traditional cassette

**Comment by kohenkatz** [comment]
Maybe we can have both: one as `cassette-tape` and one as `cassette-tape-alt`.

**Comment by fme-samuelbirk** [comment]
+1

**Comment by jverne** [comment]
+1 for the traditional cassette.

**Comment by AlexandreFournier** [comment]
+1, very nice for tape storage and/or voicemail.

**Comment by AlexandreFournier** [comment]
+1, very nice for tape storage and/or voicemail.

**Comment by SylvainBILLIEMAZ9** [comment]
+1

**Comment by olya-gary** [comment]
+1

**Comment by kbilinski** [comment]
+1 for the traditional cassette

**Comment by MVcodeartbr** [comment]
+1 for the traditional cassette

**Comment by aethior** [comment]
+1 traditional cassette.

**Comment by asq1859** [comment]
+1 for any cassette

**Comment by patiati** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by ohmybside** [comment]
what about this one
![dark_tape_512px](https://cloud.githubusercontent.com/assets/10530469/21206344/adafe592-c261-11e6-9386-487c90c5c92a.png)

**Comment by timelessthee** [comment]
+1

**Comment by nuwen** [comment]
+1

**Comment by sensibleworld** [comment]
You can finally make your own mixtapes with version 5.11: https://fontawesome.com/icons/cassette-tape?style=duotone
