### ISSUE TITLE
Vest and Vest-patches missing from THIN versions

### ISSUE THREAD

**Issue by shanewhitehead** [FortAwesome/Font-Awesome#17366]
**Describe the bug**
Not sure if this intentional, but all the icons now have a thin version with the exception of vest and vest-patches

**To Reproduce**
Try to render a font using fat fa-vest

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Render the font thin

**Screenshots**

**Version and implementation**
Version: 6 alpha
Browser and version: Chrome (latest)

- [X] SVG with JS
- [X] Web Fonts with CSS
- [X] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Thanks for the report! I've identified the issue, and have a fix ready for our next alpha release.
