### ISSUE TITLE
Some Square-# icons are the wrong size in 6.0-alpha1

### ISSUE THREAD

**Issue by RobotGizmo** [FortAwesome/Font-Awesome#17362]
**Describe the bug**
The square-1, square-2, square-7, square-8 icons have the wrong size embedded. If I use an SVG -> PNG converter they end up being a different size than the other square icons. The others are 448x512 but the incorrect ones are 640x512.

**To Reproduce**
You can use this online converter to see the issue: [](https://svgtopng.com)

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
The square icons should all have the same size embedded so that they are all the same when rasterized.

**Version and implementation**
Version: 6.0-alpha1

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Confirmed

Let's assign @sensibleworld, but I can see that think this has been already fixed upstream

**Comment by sensibleworld** [comment]
Yup! Thanks for the report. We've got a fix ready for the next alpha release.

**Comment by RobotGizmo** [comment]
Excellent, thanks for the quick response!

**Comment by sensibleworld** [comment]
Should be fixed in the latest v6 Alpha release: https://fontawesome.com/download
