### ISSUE TITLE
Allergy

### ISSUE THREAD

**Issue by surenthj** [FortAwesome/Font-Awesome#17372]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have this icon to represent allergies: https://fontawesome.com/icons/allergies?style=solid

If you have something different in mind, pleas fill in our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example

Closing here
