### ISSUE TITLE
temperature-sun has space after in metadata

### ISSUE THREAD

**Issue by aspan** [FortAwesome/Font-Awesome#17374]
Fontawesome 6.0-alpha1 contains an error in the metadata file.
The temperature-sun icon has a space after the name.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can see this fixed upstream, but I'm going to mention @sensibleworld for a confirmation

**Comment by sensibleworld** [comment]
Yup! We've got this fixed, and will be out in the next alpha. Thanks for the report! (And certainly keep the coming, if you see any more bugs.)

**Comment by sensibleworld** [comment]
This should be fixed in the latest release. Let us know if you find any other errors in the alpha!
