### ISSUE TITLE
 Using pro resources

### ISSUE THREAD

**Issue by BurhanMiroj** [FortAwesome/Font-Awesome#17379]
Dear Fontawesome team, I have felt something wrong in your system, my current position is using free fontawesome, but I still easily use font resources by copying HTML which should only be obtained when the user status is subscribing to the pro package, please do so. check it out

Thanks
![fontawesome](https://user-images.githubusercontent.com/62690855/98455830-605f1b00-21a8-11eb-93bb-e157c0d6742c.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I think that we cannot prevent people copying svgs, but please note that this behavior it is not legitimate and it is violating a commercial product license, so it can be considered piracy

/cc @robmadole
