### ISSUE TITLE
FontAwesome 5

### ISSUE THREAD

**Issue by jinneeeeehue** [FortAwesome/Font-Awesome#17373]
While using fontawesome 5 in React Native. I discovered that the use of "phone-alt " icon will result in a missing icon. "phone" works but there is an issue with "phone-alt".

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[phone-alt](https://fontawesome.com/icons/phone-alt?style=solid) has been added in version 5.10.2, is it possible that your application is using an older version of Font Awesome?

**Comment by jinneeeeehue** [comment]
That might be possible. Let me give it a check. Thank you.
