### ISSUE TITLE
Icon Request: fa-strava

### ISSUE THREAD

**Issue by sgowtham** [FortAwesome/Font-Awesome#17397]
Greetings.

Could you please create an icon fro Strava (https://www.strava.com/)? I plan on using in my "social navigation menu" in my website - https://sgowtham.com/.

![press-thumbnail-asset-logo-02](https://user-images.githubusercontent.com/3024808/98961394-84d23480-24d3-11eb-82d4-48170a3ae244.jpg)

Thank you,
Gowtham

**Comment by tagliala** [comment]
Hi,

Thanks for being part of the Font Awesome Community.

Strava is already here: https://fontawesome.com/icons/strava?style=brands

Please make sure that you are using Font Awesome >= 5.8.0

**Comment by sgowtham** [comment]
Thank you!

Apart from not searching correctly within the pro edition, turned out to be a typo on my end - I was using fa instead of fab.

My best,
Gowtham
