### ISSUE TITLE
Icon Request: Patreon

### ISSUE THREAD

**Issue by starcallinq** [FortAwesome/Font-Awesome#17399]
i would love to see a patreon icon! i wish to use it on my toyhouse page to link my patreon.

![58481774cef1014c0b5e4992](https://user-images.githubusercontent.com/74383345/99001713-3b193680-2533-11eb-8b21-530d31e4f601.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Patreon is already available: https://fontawesome.com/icons/patreon?style=brands

Please make sure that you are using Font Awesome >= 5.0.3

Please also note that your example depicts the old logo, replaced by the one you can find in Font Awesome. https://www.patreon.com/brand
