### ISSUE TITLE
Icon request: truck-crane

### ISSUE THREAD

**Issue by one1973** [FortAwesome/Font-Awesome#17396]
**What can it be used for?**
To represent the towing of a vehicle.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

https://www.flaticon.com/free-icon/crane_226360

**Comment by aethior** [comment]
Hi @one1973,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/truck-tow

Regards.

cc/ @tagliala
