### ISSUE TITLE
离线的examples中katex内容显示失败

### ISSUE THREAD

**Issue by ZhangJiaLei123** [FortAwesome/Font-Awesome#17394]
examples中的editormd.js对katex的url定义是'**//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min**',导致离线编辑器中,无法预览科学公式 TeX(KaTeX).
* 建议将**katex.min.css**和js存放到项目中.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate: 
> ### Katex content in offline examples failed to display
> 
> The editormd.js in the examples defines the url of katex as'//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min', resulting in the offline editor, unable to preview the scientific formula TeX (KaTeX) .
> 
> It is recommended to store katex.min.css and js in the project.

I think this request is not related to Font Awesome, closing here
