### ISSUE TITLE
v6a1 Misaligned Duotone fa-life-ring

### ISSUE THREAD

**Issue by Jas-n** [FortAwesome/Font-Awesome#17392]
**Describe the bug**
The primary and secondary layers are misaligned.

**To Reproduce**
Search and click life-ring on the icons page.

**Expected behavior**
The primary colour would be nicely aligned over the gaps in the secondary

**Screenshots**
![image](https://user-images.githubusercontent.com/14942820/98663500-18273080-2341-11eb-97af-a3ee7a55d9ee.png)

**Version and implementation**
Version: 6a1
Browser and version: https://www.whatsmybrowser.org/b/VM4ZQ

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can see that this is still an issue upstream

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Thanks! This is happening to quite a few icons duotone icons in v6 so far. Working on a more global fix :)

**Comment by sensibleworld** [comment]
This should be fixed in the latest release: https://fontawesome.com/download
