### ISSUE TITLE
6.0.0-alpha1 fa-spinner-third glyph rendered in a distinct way

### ISSUE THREAD

**Issue by alexdgs** [FortAwesome/Font-Awesome#17401]
**Describe the bug**
Glyph for fa-spinner-third is rendered in a distinct way in v6.0.0-alpha1. The arc seems not well positioned and when rotating the glyph looks weird.

**To Reproduce (on desktop)**
- Install Font Awesome 6.0.0-alpha1
- Use any graphic software to insert a fa-spinner-third symbol in a text. Make text centered both horizontally and vertically.
- Either manually or using an animation script (if used software provides any) rotate the text element.
- Glyph rotates like this:
![fa-spinner-bug](https://user-images.githubusercontent.com/7460734/99076489-98dc6b80-2591-11eb-908f-8ddb104a267c.gif)

**Expected behavior**
- Glyph should rotate like this:
![fa-spinner-ok](https://user-images.githubusercontent.com/7460734/99076450-89f5b900-2591-11eb-83f7-a9124c749d27.gif)

**Version and implementation**
Version: 6.0.0-alpha1

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm this is still an issue in the build system and I do not see an incoming PR fixing this, so let's assign to @sensibleworld

**Comment by sensibleworld** [comment]
This should be fixed in the latest release: https://fontawesome.com/download
