### ISSUE TITLE
Icon Request: Mouse Click

### ISSUE THREAD

**Issue by danskionline** [FortAwesome/Font-Awesome#1740]
Hey Dave,

I think that would be nice, although icon-hand-up works too, in a way.

Cheers.

**Comment by aethior** [comment]
Checking Google Images one of the proposed images is `fa-hand-pointer-o` (http://fontawesome.io/icon/hand-pointer-o/). Without an example is difficult know what is the proposed icon exactly.

@tagliala What do you think about this?

**Comment by tagliala** [comment]
yes, or we could consider this a duplicate of #2376
