### ISSUE TITLE
Icon request: pix

### ISSUE THREAD

**Issue by doceazedo** [FortAwesome/Font-Awesome#17414]
**What can it be used for?**
Pix is a brand new payment system created by the Central Bank of Brazil that supports instant 24/7 transfers and payments. It's planned to be the main payment method in Brazil and is already being used by all Brazilian bank institutions and a lot of fintechs. Additional info is available in [this article](https://business.ebanx.com/en/resources/payments-explained/pix-instant-payment-system) and in [the official Central Bank website](https://www.bcb.gov.br/en/pressdetail/2334/nota). This may be as essential as money bill, credit card or money check icons in Brazil.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/33992396/99478346-fcb8b880-2932-11eb-8451-7f2f35335c04.png) ![image](https://user-images.githubusercontent.com/33992396/99478349-ff1b1280-2932-11eb-8776-1942bbe1a52a.png) ![image](https://user-images.githubusercontent.com/33992396/99478353-00e4d600-2933-11eb-8228-4bafe8571507.png)

The [Pix brand book](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_ManualdeUsodaMarcaPix-versao1.pdf) may also be helpful.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by hmaesta** [comment]
| <img src="https://user-images.githubusercontent.com/741969/99538099-3b7a5d00-298b-11eb-9f4f-c3d0cd4a5280.png" alt="Solid symbol" width="30"/> | Solid symbol 	| 1.09 kb 	|
|---	|-------	|---------	|

```svg
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <defs/>
  <g fill="#4BB8A9" fill-rule="evenodd">
    <path d="M112.57 391.19c20.056 0 38.928-7.808 53.12-22l76.693-76.692c5.385-5.404 14.765-5.384 20.15 0l76.989 76.989c14.191 14.172 33.045 21.98 53.12 21.98h15.098l-97.138 97.139c-30.326 30.344-79.505 30.344-109.85 0l-97.415-97.416h9.232zm280.068-271.294c-20.056 0-38.929 7.809-53.12 22l-76.97 76.99c-5.551 5.53-14.6 5.568-20.15-.02l-76.711-76.693c-14.192-14.191-33.046-21.999-53.12-21.999h-9.234l97.416-97.416c30.344-30.344 79.523-30.344 109.867 0l97.138 97.138h-15.116z"/>
    <path d="M22.758 200.753l58.024-58.024h31.787c13.84 0 27.384 5.605 37.172 15.394l76.694 76.693c7.178 7.179 16.596 10.768 26.033 10.768 9.417 0 18.854-3.59 26.014-10.75l76.989-76.99c9.787-9.787 23.331-15.393 37.171-15.393h37.654l58.3 58.302c30.343 30.344 30.343 79.523 0 109.867l-58.3 58.303H392.64c-13.84 0-27.384-5.605-37.171-15.394l-76.97-76.99c-13.914-13.894-38.172-13.894-52.066.02l-76.694 76.674c-9.788 9.788-23.332 15.413-37.172 15.413H80.782L22.758 310.62c-30.344-30.345-30.344-79.524 0-109.868"/>
  </g>
</svg>
```

---

| <img src="https://user-images.githubusercontent.com/741969/99538133-492fe280-298b-11eb-81a2-66779343e064.png" alt="Solid symbol" width="30"/> | Outline symbol 	| 1.92 kb 	|
|---	|-------	|---------	|


```svg
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <defs/>
  <g fill="#4BB8A9" fill-rule="evenodd">
    <path d="M393.072 391.897c-20.082 0-38.969-7.81-53.176-22.02l-77.069-77.067c-5.375-5.375-14.773-5.395-20.17 0l-76.784 76.786c-14.209 14.207-33.095 22.019-53.179 22.019h-9.247l97.521 97.52c30.375 30.375 79.614 30.375 109.988 0l97.239-97.238h-15.123zm-105.049 74.327c-8.55 8.53-19.93 13.25-32.05 13.25h-.02c-12.12 0-23.522-4.721-32.05-13.25l-56.855-56.855c7.875-4.613 15.165-10.248 21.758-16.84l63.948-63.948 64.23 64.23c7.637 7.66 16.188 14.013 25.478 18.952l-54.439 54.46zM310.958 22.78c-30.374-30.374-79.613-30.374-109.988 0l-97.52 97.52h9.247c20.082 0 38.97 7.834 53.178 22.02l76.784 76.785c5.57 5.592 14.622 5.57 20.17 0l77.069-77.068c14.207-14.187 33.094-22.02 53.176-22.02h15.123l-97.239-97.237zm6.028 96.346l-64.23 64.23-63.97-63.97c-6.593-6.592-13.86-12.206-21.736-16.818l56.853-56.877c17.69-17.645 46.476-17.668 64.121 0l54.44 54.461c-9.292 4.961-17.842 11.315-25.479 18.974h.001z"/>
    <path d="M489.149 200.97l-58.379-58.377h-37.706c-13.838 0-27.394 5.635-37.185 15.426l-77.068 77.069c-7.202 7.18-16.623 10.77-26.067 10.77-9.443 0-18.885-3.59-26.066-10.77l-76.785-76.785c-9.792-9.814-23.346-15.427-37.207-15.427h-31.81L22.78 200.97c-30.374 30.375-30.374 79.614 0 109.988l58.095 58.074 31.81.021c13.86 0 27.416-5.635 37.208-15.426l76.784-76.764c13.925-13.947 38.208-13.924 52.133-.02l77.068 77.066c9.791 9.792 23.346 15.405 37.185 15.405h37.706l58.379-58.356c30.374-30.374 30.374-79.613 0-109.988zm-362.19 129.724c-3.763 3.786-8.942 5.917-14.273 5.917H94.302l-48.59-48.564c-17.689-17.69-17.689-46.476 0-64.143L94.3 175.296h18.385c5.331 0 10.51 2.154 14.295 5.918l74.74 74.74-74.761 74.74zm339.257-42.647l-48.848 48.87h-24.305c-5.309 0-10.508-2.155-14.251-5.92l-75.023-75.043 75.023-75.023c3.743-3.764 8.942-5.918 14.252-5.918h24.304l48.847 48.891c8.573 8.551 13.273 19.93 13.273 32.05 0 12.141-4.7 23.52-13.273 32.093z"/>
  </g>
</svg>
```

---

Both files were extracted from [official brand book](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_ManualdeUsodaMarcaPix-versao1.pdf), resized to 512x512 and optimized with [SVGO.](https://github.com/svg/svgo)

**Comment by GilbertoCharles** [comment]
I hope this get merged, gonna be really helpfull

**Comment by Emesilver** [comment]
Really important!!!

**Comment by AllanDaemon** [comment]
I never saw so many reactions in a post here in github.  But it makes sense as this is really important for people in Brazil.

**Comment by arturxz** [comment]
It would be really greate for Brazilian developers! Or developers that want to use this payment method in Brazil

**Comment by wandersonxs** [comment]
It's quite important! Waiting for it.

**Comment by tagliala** [comment]
# 😮 

Thanks for your enthusiasm for this request

Please remember that you should only use reactions to upvote, comment will spam people subscribed to this request

**Comment by dionizio82** [comment]
Boa! Estou aguardando para usar também! Parabéns pela iniciativa.

**Comment by Mun1z** [comment]
So cool S2 great job o/

**Comment by DouglasHoffmann** [comment]
Great ideia !

**Comment by rafaelmsantiago** [comment]
Waiting for it! ❤

**Comment by hmaesta** [comment]
🇧🇷 Ei pessoal, estamos todos muito entusiasmados com o Pix e com certeza a adição do símbolo ao Font Awesome vai ser algo muito apreciado por nós brasileiros.

Mas ao comentar aqui todos que participam da thread são notificados e isso acaba sendo bem chato – além de tirar o foco de possíveis discussões que possam _realmente_ agregar valor quando essa demanda começar a ser executada.

### → Para incentivar o pessoal do Font Awesome basta dar um **_JOINHA_** lá na [primeira mensagem](https://github.com/FortAwesome/Font-Awesome/issues/17414#issue-745291292) 👍 

Não é necessário adicionar um novo comentário.

**Comment by WillianBR** [comment]
I  hope it'll be merged sooner!

**Comment by AllanDaemon** [comment]
hey @hmaesta , since you provided the SVG, could you create a PR for this issue?

I think some people are mistaken this as a Pull Request to be merged, but it's only the issue. Someone have to create the PR to this be closed.

**Comment by hmaesta** [comment]
> could you create a PR for this issue?

[FontAwesome doesn't accept Pull Requests.](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests)

**Comment by sensibleworld** [comment]
Just added: https://fontawesome.com/v6.0/icons/pix?s=brands
