### ISSUE TITLE
Font Awesome Pro Repo Issues

### ISSUE THREAD

**Issue by ChanceLeachman** [FortAwesome/Font-Awesome#17413]
**Describe the bug**

When I am attempting to `npm install`:

`"@fortawesome/fontawesome-common-types": "^0.2.32",`
   ` "@fortawesome/fontawesome-pro": "^5.15.1",`
    `"@fortawesome/fontawesome-svg-core": "^1.2.32",`
    `"@fortawesome/pro-light-svg-icons": "^5.15.1",`
    `"@fortawesome/react-native-fontawesome": "^0.2.6",`

I am getting this error from npm:

`npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/0.2.32/fortawesome-fontawesome-common-types-0.2.32.tgz?created=1605654812&expires=1605656012&source=t-dsWeXpNbbx2Z&signature=gAAAAABftFkc3TWGFrsrByz8FV4rD02Ry9nLmhtXJs-Q5ogschxSDHDdMR4HueIgZTKt22DM8zJl-eG20nS7WQaLPY_cTzsLKW2N7VNEJWS6GU70CUMvaU774v_VYtbiuIu9TJyBZbSk failed, reason: write EPROTO 140033789138752:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
npm ERR! `

This has been working previously without issues. Everything is dockerized.

`RUN npm config set "@fortawesome:registry" https://npm.fontawesome.com/`
`RUN npm config set "//npm.fontawesome.com/:_authToken" '${FONTAWESOME_NPM_AUTH_TOKEN}'`

`ARG FONTAWESOME_NPM_AUTH_TOKEN`
`RUN FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN} npm install`

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've reported this issue to hello@fontawesome.com, let's wait for feedback

**Comment by robmadole** [comment]
@ChanceLeachman it looks like you are using the `dl.fontawesome.com` host instead of `npm.fontawesome.com`. Can you remove your `package-lock.json` or `yarn.lock` file and re-run `npm install` or `yarn install` to regenerate the file? That `dl.fontawesome.com` host should not be used (I'm not sure how it got into your files!)

**Comment by ChanceLeachman** [comment]
That worked great! Thank you, Rob! Not sure how `dl.fontawesome.com` got there either.
