### ISSUE TITLE
arrow-down-big-small icon has an old version next to it

### ISSUE THREAD

**Issue by 1stKarkan** [FortAwesome/Font-Awesome#17416]
**Describe the bug**
Testing the new v6-first-roast Alpha, i encountered a bug in arrow-down-big-small and similar icons. The icons will show an older version from FontAwesome 5 beside the actual icon.

**To Reproduce**
http://localhost:3000/documentation/icons/ 
search for: arrow-down-big-small

**Expected behavior**
Show the new icon and only once

**Version and implementation**
Version: 6 Alpha 1

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can see the error in the docs, but I'm not sure if it has been fixed upstream. The SVG file is correct, but I can't clearly see the wrong one

@sensibleworld could you please take a look?

**Comment by sensibleworld** [comment]
Thanks for the report! I've got this fixed and ready to go for the next alpha.

**Comment by sensibleworld** [comment]
This is all fixed up in the latest release of the alpha: https://fontawesome.com/download
