### ISSUE TITLE
CORS issue on fonts

### ISSUE THREAD

**Issue by amazium** [FortAwesome/Font-Awesome#17427]
Typical cors shit:

Access to font at 'https://ka-f.fontawesome.com/releases/v5.13.1/webfonts/free-fa-regular-400.woff2' from origin 'http://localhost:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I added 'http://localhost:8082' in the domains in FA kit, but to no avail.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

IIRC, there is no need to add localhost to domains (it's automatically whitelisted)

Also, i can see from `curl -i https://ka-f.fontawesome.com/releases/v5.13.1/webfonts/free-fa-regular-400.woff2`

```
Access-Control-Allow-Origin: *
```

Also, I've checked with a very simple local implementation in python (`python -m http.server 8082`)

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/de0d2bc70c.js" crossorigin="anonymous"></script>

    <title>Hello, world!</title>
  </head>
  <body>
    <span class="fas fa-home"></span>
  </body>
</html>
```

and it works

![image](https://user-images.githubusercontent.com/556268/100019362-2fa0f780-2dde-11eb-9117-74dbeb28d2ff.png)


Could you please paste the output of 

```
curl -i https://ka-f.fontawesome.com/releases/v5.13.1/webfonts/free-fa-regular-400.woff2
```
