### ISSUE TITLE
Font Awesome not working with content: \

### ISSUE THREAD

**Issue by jkenway2908** [FortAwesome/Font-Awesome#17422]
I've been trying to get this to work for days to no avail so any help would be much much appreciated. I'm trying to get FontAwesome icons to work with my Bootstrap accordion.

**My CSS:**

main #exhibit .spec-care {
        position: relative;
}

main #exhibit .spec-care::after {
        content: "\f078";
	right: 0px;
	position: absolute;
        font-family: 'Font Awesome 5 Free';
        font-weight: 900;
}

main #exhibit .spec-care[aria-expanded="true"]::after {
	content: "\f077";
}

**I'm calling Font Awesome using:**
(<) link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet" (>)

_... but I'm seeing the icons rendered just as 'f078' (and f077)._

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/nLg2dza1/1/

Please check other css and use the inspect tool of you browser to confirm that everything is correct

If you think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Docs:
- https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

**Comment by vastcomtech-sam** [comment]
very easy and silly way to solved
when u get the page for the picture u can see it has mentioned a version like
![image](https://user-images.githubusercontent.com/89188627/151921862-c5300006-3d80-4546-8ba2-429ac92b1783.png)
well u can add 4 and 5 version CDN to HTML
exsample:
```
<link rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" 
        integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" 
        crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
        <link 
        href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
        rel="stylesheet"  type='text/css'>

```

that's why I talking about silly but work!
