### ISSUE TITLE
Icon virus & viruses not showing - instead chinese characters

### ISSUE THREAD

**Issue by fugo** [FortAwesome/Font-Awesome#17420]
kind of the issue #16804 ?

On a web project I tried to use the virus (tried viruses, virus-slash, shield-virus, head-side-virus) icon.
I tried a few different browsers (Firefox 83.0 | Pale Moon 28.15.0 | Vivaldi 3.4 ...) all showing chinese characters not the virus icon.
I use the latest version of Grav (https://getgrav.org/), a flat file CMS with Markdown, Twig, PHP ( I use 7.3.21)
Bacteria icon is working.

![](https://i.imgur.com/SxoQWlR.png)

Fontawesome Version: Pro 5.15.1
- [x] Web Fonts with CSS

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> kind of the issue #16804 

Yes. Please double check that you are using FA >= 5.14.0. Please note that third party libraries / plugins / framework may load an older version of Font Awesome and take precedence over your version

If you still have issues, fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case
