### ISSUE TITLE
Cannot install using npm: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"

### ISSUE THREAD

**Issue by manova-rainer** [FortAwesome/Font-Awesome#17426]
**Describe the bug**
tried to install the pro version following the [instructions](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
...
```

tried global/per project/environment versions

**To Reproduce**

`
mkdir /tmp/fa-npmtest
cd /tmp/fa-npmtest
FONTAWESOME_NPM_AUTH_TOKEN=***** npm install --save @fortawesome/fontawesome-pro
`

**Expected behavior**
successfull installation

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have already contacted hello@fontawesome.com on 2020-11-09, no answer yet

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please send an email to hello@fontawesome.com

**Comment by robmadole** [comment]
@manova-rainer did you configure an `.npmrc`?

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```

**Comment by manova-rainer** [comment]
@robmadole just omitted the .npmrc part in the reproduction, yes .npmrc was configured with

`@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}`

**Comment by robmadole** [comment]
@manova-rainer if you don't use the FONTAWESOME_NPM_AUTH_TOKEN environment variable and instead put the token directly in the `.npmrc` do you still have issues?

**Comment by manova-rainer** [comment]
@robmadole 

```
>cat .npmrc
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

>npm install --save @fortawesome/fontawesome-pro
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rainer/.npm/_logs/2020-11-23T20_01_52_418Z-debug.log

cat /home/rainer/.npm/_logs/2020-11-23T20_01_52_418Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/rainer/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/home/rainer/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@fortawesome/fontawesome-pro' ]
2 info using npm@6.11.3
3 info using node@v10.16.3
4 verbose npm-session ff7d99d25fe55414
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro 502ms
8 silly fetchPackageMetaData error for @fortawesome/fontawesome-pro@latest Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 525ms
11 verbose stack Error: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
11 verbose stack     at res.buffer.catch.then.body (/home/rainer/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:94:17)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose statusCode 401
13 verbose pkgid @fortawesome/fontawesome-pro@latest
14 verbose cwd /tmp/fatest
15 verbose Linux 5.4.0-54-generic
16 verbose argv "/home/rainer/.nvm/versions/node/v10.16.3/bin/node" "/home/rainer/.nvm/versions/node/v10.16.3/bin/npm" "install" "--save" "@fortawesome/fontawesome-pro"
17 verbose node v10.16.3
18 verbose npm  v6.11.3
19 error code E401
20 error Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
21 verbose exit [ 1, true ]

```
still the same issue

**Comment by robmadole** [comment]
@manova-rainer that's about as far as we can go in the public repo. We'll have to chat with you now over email. Try again to send an email to hello@fontawesome.com. I'll look for your message.

**Comment by robmadole** [comment]
@manova-rainer I have replied to you. Let me know if you don't receive the email.

**Comment by manova-rainer** [comment]
@robmadole 

message received, thanks
