### ISSUE TITLE
Icon request: Safe-Online

### ISSUE THREAD

**Issue by Creeper39x** [FortAwesome/Font-Awesome#17423]
**Example image (optional)**
https://www.google.com/url?sa=i&url=https%3A%2F%2Fpngio.com%2FPNG%2Fa69513-safety-icon-png.html&psig=AOvVaw3cnzACOy7gCjT-nRlVYtt_&ust=1606005885744000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCwm6i0ku0CFQAAAAAdAAAAABAD

**Icon request checklist**
- [✅ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ✅] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✅ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✅ ] I have included at least one example image if it could be helpful (optional)
- [ ✅] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro as [shield-check](https://fontawesome.com/icons/shield-check?style=solid)

or...

you can achieve a similar icon with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/471/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
