### ISSUE TITLE
number icons (request)

### ISSUE THREAD

**Issue by manudevcode** [FortAwesome/Font-Awesome#17438]
I've been looking for this number icon pack but can't find them.

![image](https://user-images.githubusercontent.com/11260098/100296696-87f90600-2f52-11eb-9fe1-0f695d8f6e14.png)

**Comment by sensibleworld** [comment]
Hey there! We have number icons available as part of the Font Awesome 6 alpha release: https://fontawesome.com/download

**Comment by manudevcode** [comment]
Omg awesome!!!!  tanks!
