### ISSUE TITLE
Icon request: fa-pinata

### ISSUE THREAD

**Issue by MontoyaTech** [FortAwesome/Font-Awesome#17432]
**What can it be used for?**
Birthday celebration for other cultures! You know hit the thing on the string till candy comes out? Fun stuff!

**Example image (optional)**
This one might be a little tricky to make given the size.. but maybe just an outline in this orientation?

https://www.google.com/search?q=pinata&tbm=isch&ved=2ahUKEwi90JSPhpztAhWLIzQIHRi-AV8Q2-cCegQIABAA&oq=pinata&gs_lcp=CgNpbWcQAzIHCAAQsQMQQzIFCAAQsQMyBAgAEEMyBAgAEEMyBAgAEEMyAggAMgQIABBDMgIIADICCAAyBAgAEENQ9vwaWJWCG2CMgxtoAHAAeACAAXCIAccEkgEDNC4ymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=w3C9X_3iJovH0PEPmPyG-AU&bih=969&biw=1920&rlz=1C1SQJL_enUS842US842#imgrc=aBQighlBiNDaBM

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @MontoyaTech,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/pinata

Regards.

cc/ @tagliala
