### ISSUE TITLE
Wrong version number in hospital-user icon

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#17435]
**Describe the bug**
`hospital-user` has the wrong version number, because it can't be used with FA 5.7.0. It happened because of 5.13.0 release, in which we moved some existing pro icons to the free set.

**To Reproduce**
1. https://fontawesome.com/icons/hospital-user?style=solid
2. Check the version number (5.7.0)
3. Try to use `hospital-user` in 5.7.0

**Expected behavior**
Has correct version number

**Screenshots**
n/a

**Version and implementation**
Version: < 5.13
Browser and version: n/a

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by talbs** [comment]
@tagliala, sorry for the radio slience on this one. It looks like we corrected the version number associated with `hospital-user` - https://github.com/FortAwesome/fontawesome-buildsystem/blob/5.x/icons/icons.yml#L19508. I've tested out referencing this icon with a kit running Font Awesome `5.7.0` and all seems well - https://codepen.io/fontawesome/pen/mdmLdpq.

Let us know if this doesn't seem resolved to you. We'll re-open and fa-wrestle it down to the ground.

**Comment by tagliala** [comment]
Hi @talbs maybe I was not clear that I was referring to the free set

> Try to use hospital-user in 5.7.0 **edit: in FA Free**

When we released 5.13.0, the one with COVID icons, we moved some icons from the pro set to the free set

One of those icons is `fa-hospital-user`, that can be used with FA 5 free starting from version 5.13.0 (but not with 5.7.0)

Since:
- docs are related to both versions
- we do not have a distinction between `fa-pro` version and `fa-free` version
- the solid icon does not have a "Pro" label because it is now part of the free set

I've asked to change the "updated" to version 5.13.0, so free users know that if they want to use that icon, they should update to 5.13.0

**Comment by sensibleworld** [comment]
@tagliala Thanks for the clarification! I've got a fix up for this.
