### ISSUE TITLE
Icon request: building-user

### ISSUE THREAD

**Issue by e-belair** [FortAwesome/Font-Awesome#17434]
**What can it be used for?**
Show an icon about a user belong to a company
An example would be the same as the user-hospital, but with a building

**Icon request checklist**
- [x] This is a single icon I guess
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but you can achieve a similar icon with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/8e6kLv5z/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by e-belair** [comment]
wow, impressive! I didn't aware of that feature!

**Comment by sensibleworld** [comment]
This icon new exists: https://fontawesome.com/v6/icons/building-user?s=solid

**Comment by e-belair** [comment]
@sensibleworld Thanks for the feedback :)
