### ISSUE TITLE
US Map Outline and US States Map Outlines

### ISSUE THREAD

**Issue by jay-mancini** [FortAwesome/Font-Awesome#17437]
**What can it be used for?**
I would like to add US map and US States Outline when users are selecting a US state/country. Also it would be nice to have a US State Icon next to selected state in an address book or anything around that line.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X
![Screen Shot 2020-11-25 at 2 55 43 PM](https://user-images.githubusercontent.com/73600639/100275714-5f5f1500-2f2e-11eb-9b47-1ac14cc1ec3e.png)
![Screen Shot 2020-11-25 at 2 56 50 PM](https://user-images.githubusercontent.com/73600639/100275800-80276a80-2f2e-11eb-97c2-edc133f90950.png)
![Screen Shot 2020-11-25 at 2 57 05 PM](https://user-images.githubusercontent.com/73600639/100275807-83225b00-2f2e-11eb-9cf9-ba7026406da8.png)

] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment, I'm closing all requests about country silhouettes because they are out of scope

Ref: #3992

Closing here
