### ISSUE TITLE
Icon request: fa-cake-slice

### ISSUE THREAD

**Issue by MontoyaTech** [FortAwesome/Font-Awesome#17431]
**What can it be used for?**
Conveying birthday celebration! We have a cake icon.. but no slice of cake? Portal fans are left out as well.. Um, also cake is awesome?

**Example image (optional)**
https://www.google.com/search?q=slice+of+cake&tbm=isch&ved=2ahUKEwi9m83NhZztAhUVIX0KHXgiDbgQ2-cCegQIABAA&oq=slice+of+cake&gs_lcp=CgNpbWcQAzIHCAAQsQMQQzICCAAyAggAMgQIABBDMgQIABBDMgIIADICCAAyAggAMgIIADICCAA6BQgAELEDOggIABCxAxCDAVCznwhY-6kIYIKrCGgAcAB4AIABiAGIAe0JkgEEMTAuM5gBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=OnC9X72WCZXC9AP4xLTACw&bih=969&biw=1920&rlz=1C1SQJL_enUS842US842

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/cake-slice?s=solid

**Comment by tagliala** [comment]
Duplicate of #11782
