### ISSUE TITLE
Icon request: icon-salesforce

### ISSUE THREAD

**Issue by jvandyke** [FortAwesome/Font-Awesome#1744]
For use with Salesforcey things.

Of course, a generic cloud icon already exists, but this is a unique shape. I'm not sure what else could ensure that it's unique enough. Putting the stylized 'f' inside would be one way, but no one would associate that. 'sf' would be closer, but still no one would know. I think it will have to be left to the context.

Full color logo:
![Full color simple logo](http://www2.sfdcstatic.com/common/assets/img/logo-company.png)

Single color logo
![Salesforce mono color logo](http://dreamforcenews.salesforce.com/sites/dfnews.newshq.businesswire.com/themes/dfnews_newshq_businesswire_com_theme/client_files/images/nav-icons6.jpg)

**Comment by jufemaiz** [comment]
+1

**Comment by bchristie** [comment]
To update @hemclohumi 's addition: http://jsfiddle.net/zww3r1Lv/5/

Uses `ƒ` instead to mimic saleforce's font.

**Comment by cazala** [comment]
+1000

**Comment by seanfahey** [comment]
:+1:

**Comment by eignerchris** [comment]
+1

**Comment by pRatikSathaye** [comment]
+1

**Comment by jmetric** [comment]
+1

**Comment by brandfocus** [comment]
+1

**Comment by oliversalzburg** [comment]
+1

**Comment by E-Xor** [comment]
+1

**Comment by edbury** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by alker7** [comment]
+1

**Comment by austinwang** [comment]
+1

**Comment by corytheboyd** [comment]
+1

**Comment by ktichenor** [comment]
+1

**Comment by dylanz** [comment]
+1

**Comment by ManuZenou** [comment]
+1

**Comment by jcalabro** [comment]
+1

**Comment by Menacho** [comment]
+1

**Comment by stepanvitecek** [comment]
Hello FontAwesome, will you release an icon of Salesforce soon? Thanks!

**Comment by SwapnaNethi** [comment]
Is this available now for use?

**Comment by SwapnaNethi** [comment]
+1

**Comment by robisenberg** [comment]
+1

Ideally would have a square version too like with the other social icons e.g. `twitter`, `twitter-square`.

**Comment by maxkaplan** [comment]
+1

**Comment by tomkell29** [comment]
+1

**Comment by markkesty** [comment]
+1

**Comment by brianwertz** [comment]
+1

**Comment by ali-farag** [comment]
+10000000

**Comment by ccurtisj** [comment]
+ 10000001

**Comment by ianoti** [comment]
+1

**Comment by idanelor** [comment]
+1

**Comment by vmeira** [comment]
+1

**Comment by kelvinau** [comment]
+1

**Comment by tomschweers** [comment]
A trailhead one would be good for link to badges and such on personal website

**Comment by redzioch** [comment]
+1

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) (For use with "Salesforcey" things.) - https://fontawesome.com/icons/salesforce

Thanks for the patience and for continuing to vote this up! :smile:
