### ISSUE TITLE
font-awesome iconview doesn't appear on linux scene builder

### ISSUE THREAD

**Issue by taiq-sabri** [FortAwesome/Font-Awesome#17443]
**Describe the bug**
I switched from windows to linux(Pop!_OS )and downloaded intelliJ and scene builder but when I added the fontAwesome library to the scene builder the components didn't show

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
see the component in the custom window or when I search for it 

**Screenshots**
![Edited](https://user-images.githubusercontent.com/57255961/100537227-33de7200-322f-11eb-92de-c24b500eea45.png)
![Screenshot from 2020-11-29 10-52-36](https://user-images.githubusercontent.com/57255961/100537406-0d213b00-3231-11eb-8da5-6c562b295080.png)

**OS info**
Distro: Pop!_OS
Version: 20.10

**Font Awesome and Scene Builder info**
SceneBuilder Version: 11.0.0
FontAwesome Version: 4.7.0-11
it was added by SceneBuilder Library Manager and I didn't need to download any ```.otf``` files..it was working fine on the windows SceneBuilder with the same steps I made..Adding the repos from library manager and include the dependencies in my IDE(since I am using JavaFX with Maven)

**Version and implementation**
Version: 4.7.0-11 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**CRUCIAL UPDATE**
I noticed that when I re-add the repos from the library manager it shows me that I can import the component but when I check and click import it does not get imported...so I can see it in the library manager but not in the toolbox

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I can't help. I will leave this open waiting for feedback community, but

> Version: 4.7.0-11

Is this the Font Awesome version you are using?

If yes, please download the latest available version (5.15.1 at the moment I'm writing) and install the official `otf` fonts, then update the opening post, including:
- details about OS (distro and version)
- version of linux scene builder
- version of Font Awesome used
- Confirm that you have properly installed the latest `.otf` files and it is working in other applications

**Comment by taiq-sabri** [comment]
> **Describe the bug**
> I switched from windows to linux(Pop!_OS )and downloaded intelliJ and scene builder but when I added the fontAwesome library to the scene builder the components didn't show
> 
> **To Reproduce**
> Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
> 
> Describe any details about the test case that we need to know like "whatever you do, don't click the red button."
> 
> **Expected behavior**
> see the component in the custom window or when I search for it
> 
> **Screenshots**
> ![Edited](https://user-images.githubusercontent.com/57255961/100537227-33de7200-322f-11eb-92de-c24b500eea45.png)
> ![Screenshot from 2020-11-29 10-52-36](https://user-images.githubusercontent.com/57255961/100537406-0d213b00-3231-11eb-8da5-6c562b295080.png)
> 
> **OS info**
> Distro: Pop!_OS
> Version: 20.10
> 
> **Font Awesome and Scene Builder info**
> SceneBuilder Version: 11.0.0
> FontAwesome Version: 4.7.0-11
> it was added by SceneBuilder Library Manager and I didn't need to download any `.otf` files..it was working fine on the windows SceneBuilder with the same steps I made..Adding the repos from library manager and include the dependencies in my IDE(since I am using JavaFX with Maven)
> 
> **Version and implementation**
> Version: 4.7.0-11
> Browser and version:
> 
>     * [ ]  SVG with JS
> 
>     * [ ]  Web Fonts with CSS
> 
>     * [ ]  SVG Sprites
> 
>     * [x]  On the Desktop
> 
> 
> **Bug report checklist**
> 
>     * [x]  I have filled out as much of the above information as I can
> 
>     * [x]  I have included a test case because my odds go _way_ up that the team can fix this when I do
> 
>     * [x]  I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
> 
> 
> **CRUCIAL UPDATE**
> I noticed that when I re-add the repos from the library manager it shows me that I can import the component but when I check and click import it does not get imported...so I can see it in the library manager but not in the toolbox


I updated the opening post...Thanks for giving us your time

**Comment by tagliala** [comment]
> FontAwesome Version: 4.7.0-11

Please upgrade to the latest version of Font Awesome. Font Awesome 4 is in EOL, latest version is 5.15.1 (note: don't know where the `-11` part comes from)
