### ISSUE TITLE
Icon Request: fa-tiktok

### ISSUE THREAD

**Issue by kuznetsov-e** [FortAwesome/Font-Awesome#17444]
What can it be used for?
It is a new icon (Categories: Brand Icons) of popular social network / video hosting [https://www.tiktok.com/](https://www.tiktok.com/). 

Example image (optional)
[https://sf16-scmcdn-sg.ibytedtos.com/goofy/tiktok/web/node/_next/static/images/logo-dark-e95da587b6efa1520dcd11f4b45c0cf6.svg](https://sf16-scmcdn-sg.ibytedtos.com/goofy/tiktok/web/node/_next/static/images/logo-dark-e95da587b6efa1520dcd11f4b45c0cf6.svg)

Icon request checklist
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TikTok has been introduced in version 5.14.0, please make sure you are using version 5.14.0 or newer

https://fontawesome.com/icons/tiktok?style=brands

Closing here
