### ISSUE TITLE
TikTok Icon not showing while others do.

### ISSUE THREAD

**Issue by justinewer** [FortAwesome/Font-Awesome#17450]
https://fontawesome.com/icons/tiktok?style=brands

![tiktok code](https://user-images.githubusercontent.com/75327918/100770840-54d7cc00-33c3-11eb-89ec-86b142c8a2fa.png)
![tiktok missing](https://user-images.githubusercontent.com/75327918/100771122-a5e7c000-33c3-11eb-9624-eaf9a89d07a6.png)

using this stylesheet link - https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TikTok has been introduced in version 5.14.0: https://fontawesome.com/icons/tiktok?style=brands

Please upgrade

Hope it helps

Closing here
