### ISSUE TITLE
Icon request: icon-brush

### ISSUE THREAD

**Issue by rafaelcastrocouto** [FortAwesome/Font-Awesome#1746]
All photoshop like icons (brush, gradient, etc)

http://www.digitalfamily.com/wp/wp-content/uploads/2012/09/photoshop-tool-bar.gif

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=brush

**Comment by rafaelcastrocouto** [comment]
Hi @sensibleworld,

The issue is asking for all icons not only the brush. 
I did search for each one of them and despite a few misses (like the lasso, gradient, dodge and smudge)
almost all of them are available. Great job!
Here is a quick cheat for those seeking this icons https://codepen.io/rafaelcastrocouto/pen/RBEdPN
![untitled](https://user-images.githubusercontent.com/422159/43957068-dd9cba7c-9c7c-11e8-8f0d-61aea843cb0a.png)
