### ISSUE TITLE
icon not vertically centered with text (Chrome)

### ISSUE THREAD

**Issue by JTHOUMEL** [FortAwesome/Font-Awesome#17469]
**Describe the bug**
When a `<i>` icon and text (`<span>` or pure text) are positioned horizontally in a box:
- the text is properly vertically centered
- the icon is not properly vertically centered : it is positioned a bit too high.

I've looked at the different HTML elements, tried to change many CSS properties `(display`, `align-items`, `line-height`, `height`, etc) : no explanation.

Important: it occurs with Chrome, but not with Firefox.

**To Reproduce**

```
<!doctype html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/***.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <div style="margin-left: 50px; margin-top: 200px; background-color: red; display: flex; align-items: center; font-size: 15em">
      <i class="fa fa-times" style="background-color: orange"></i>
      <span style="background-color: pink">SPAN</span>
      TEXT
    </div>
  </body>
</html>
```

Notice that the `<i>` is properly vertically centered inside the `<div>`. It is the text icon that is not propertly vertically centered inside the `<i>`. If i add `display:flex; align-items: center` to the `<i>` style, it doesn't change anything.

**Expected behavior**
I want the text icon propertly vertically centered in the `<i>`.

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/46707652/101760023-9dd20380-3ada-11eb-8c22-3a9d215f60ce.png)

I added a blue line to show the `<div>` horizontal center. That line is 2px large for Chrome and 1px large for Firefox because the `<div>` height for Chrome is even (276 px) and for Firefox is odd (277 px). That difference is also strange : it might be related to the main centering bug ?

**Version and implementation**
Font Awesome: last online version (we pay the kit)
Browser: Chrome 87.0.4280.88

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Please share your kit id so I can check the configuration

**Comment by JTHOUMEL** [comment]
@tagliala : is it OK if I share my kit link here publicly?

**Comment by tagliala** [comment]
### Option 1
- If it is a pro kit limited on some domains, it is ok
- If it is a pro kit and it is not limited, the code is visible in the source code of your application, so visitors of your website may use it.

To limit kits: `https://fontawesome.com/kits/<KIT_ID>/settings`

### Option 2
You can only share configuration, please check the first lines of the javascript and omit `token`:

```
window.FontAwesomeKitConfig = {"asyncLoading":{"enabled":false},"autoA11y":{"enabled":true},"baseUrl":"https://ka-p.fontawesome.com","detectConflictsUntil":null,"iconUploads":{},"license":"pro","method":"js","minify":{"enabled":true},"token":"OMISSIS","uploadsUrl":"https://kit-uploads.fontawesome.com","v4FontFaceShim":{"enabled":true},"v4shim":{"enabled":true},"version":"5.15.0"};
```

### Option 3
Go to the settings page `https://fontawesome.com/kits/<KIT_ID>/settings`
and past all the configuration options (icons, technology, version, features)

**Comment by JTHOUMEL** [comment]
![image](https://user-images.githubusercontent.com/46707652/101884170-8fe2b800-3b98-11eb-9289-3c6f631fbe0b.png)

**Comment by JTHOUMEL** [comment]
Hi @tagliala,

Any news about it?

Have a nice day

**Comment by tagliala** [comment]
Apologies for the late reply

I can confirm this issue.

It is because of a known issues with Pro CSS and kits, and it is caused by the optimized webfont, caused by the descend probably

It is the same issue described in #16495, which I think it has not been fixed yet

Let's move there
