### ISSUE TITLE
fab fa-edge displays as legacy Edge icon

### ISSUE THREAD

**Issue by jbrnm** [FortAwesome/Font-Awesome#17465]
`<i class="fab fa-edge"></i>`, which should display the new Chromium-based Microsoft Edge icon, still displays the legacy "blue E" icon of the old version of Edge, which is also assigned to `<i class="fab fa-edge-legacy"></i>`.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Looks like you are using an older version of Font Awesome, please make sure that you are using FA >= 5.14.0

Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

**Comment by jbrnm** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Looks like you are using an older version of Font Awesome, please make sure that you are using FA >= 5.14.0
> 
> Please also double check that there aren't third-party plugins/themes/libraries loading an older version of Font Awesome that may have priority over yours

Hi tagliala!

Thanks for the reply. I'm just getting into the use of FontAwesome, but what I gather from your comment (feel free to correct me if I'm wrong) is that the icon that's ultimately displayed is specific to the version of FA that's being deployed by the platform I'm using. In this case, the platform is Wiki.js, which I'm running the latest stable version of (2.5.170). It sounds like they're still deploying an older version of FA that doesn't contain the updated Edge icon, however. Thank you for the clarification.

**Comment by tagliala** [comment]
Hi

> is specific to the version of FA that's being deployed by the platform I'm using.

Yes, this is the most probable reason

>  the platform is Wiki.js, which I'm running the latest stable version of (2.5.170).

I've checked the source code but I wasn't able to understand what version they use. In `package.json`, I cannot even see Font Awesome but `mdi`. 

We do not provide support to third party software. The best things you can do is:
- Check if you can upgrade font awesome yourself
- Ask in the third party's community

Hope it helps

Closing here
