### ISSUE TITLE
Icon request: menu-hierarchy / menu-structure

### ISSUE THREAD

**Issue by klonos** [FortAwesome/Font-Awesome#17475]
**What can it be used for?**
In the open source project Backdrop CMS we are using fa icons for the admin menu at the top of the page:

![image](https://user-images.githubusercontent.com/2423362/101979144-0350fc00-3c63-11eb-82cb-a349b19b414a.png)

As you can see, we are currently using the https://fontawesome.com/icons/sort-amount-down for the "Structure" menu item, but that is not an ideal fit for the purpose of that menu (it holds submenus for taxonomy, menus, layouts, etc.). We are considering to use the sort-amount-down icon for the sorting of tables (as it's meant to be used for that), so we'd need to find a different icon for the "Structure" menu.

Our brothers at Drupal are using the https://fontawesome.com/icons/sitemap icon for the respective menu, which is equally not ideal:

![image](https://user-images.githubusercontent.com/2423362/101980199-6f842d80-3c6c-11eb-9d47-ab02330108e2.png)

**Example image (optional)**

I believe that something like these following images would be a more fitting icon instead:

<img src="https://user-images.githubusercontent.com/2423362/101978066-e284a880-3c5a-11eb-8548-4bff57dea5e4.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/456816

<img src="https://user-images.githubusercontent.com/2423362/101978052-caad2480-3c5a-11eb-90d7-8833337afab6.png" width=10% height=10%>

https://www.onlinewebfonts.com/icon/456815

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be available in FA6 as `list-tree`

![image](https://user-images.githubusercontent.com/556268/101981234-9ee66a80-3c6b-11eb-98a7-d2f5892c42c6.png)

I don't know if it will be part of the Free set or exclusive to Pro, I will add the correct label as soon as FA6 will be released

**Comment by klonos** [comment]
Thanks for the very prompt reply @tagliala 👍 

> I don't know if it will be part of the Free set

Hoping 🤞 ...this is for an open-source project.

**Comment by tagliala** [comment]
Released as part of FA 6 Pro
