### ISSUE TITLE
Icon request: Yummly

### ISSUE THREAD

**Issue by CookingwithTyannne** [FortAwesome/Font-Awesome#17480]
This can be used to save recipes to yummly so other people can find them on that search engine. The last request for this icon was 5 years ago, which is a long time ago, so I am requesting it again. It's 2020 and people are cooking more than ever before! Yummly needs to be an icon in every icon provider.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The best thing you can do is to upvote #6138

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
