### ISSUE TITLE
客服

### ISSUE THREAD

**Issue by suzheng112** [FortAwesome/Font-Awesome#17483]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From google translate:

> 客服
>
> Customer service

We have some icons that may represent customer service:
- https://fontawesome.com/icons/user-headset?style=solid (pro)
- https://fontawesome.com/icons/headset?style=solid (free)
- https://fontawesome.com/icons/life-ring?style=solid (free)

If you have something different in mind, please open a new issue and provide an example

Hope it helps

closing here
