### ISSUE TITLE
Wrong icon in XD

### ISSUE THREAD

**Issue by petrholusa** [FortAwesome/Font-Awesome#17487]
Hello,

I noticed different icon in Adobe XD.

I copied this:

![Snímek obrazovky 2020-12-16 105239](https://user-images.githubusercontent.com/12070572/102333176-568dbc00-3f8d-11eb-84c2-38dbfe126eca.png)

But I get this:

![Snímek obrazovky 2020-12-16 105446](https://user-images.githubusercontent.com/12070572/102333195-5ee5f700-3f8d-11eb-99c8-ba0ed3cbf788.png)

Have a good day.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that you are getting the regular version of this icon

Can you please check that you have selected the bold font style?

Ref: https://fontawesome.com/how-to-use/on-the-desktop/referencing-icons/using-glyphs#styles

**Comment by sensibleworld** [comment]
Looking at the text style in the screenshot, you just need to change where it says "Regular" to "Solid".
