### ISSUE TITLE
SASS variable $fa-fw-width is not declared with !default

### ISSUE THREAD

**Issue by blahDL** [FortAwesome/Font-Awesome#17482]
**Describe the bug**
I wanted to override _$fa-fw-width_ in the SASS stylesheets, but it is not declared with _!default_ in the source https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L12

**To Reproduce**
Define _$fa-fw-width_ before importing font awesome, check the CSS output for _.fa-fw_ and _.fa-stack_

$fa-fw-width: 1em;
@import '@fortawesome/fontawesome-pro/scss/fontawesome';

**Expected behavior**
The value defined in $fa-fw-width is used in the CSS output 

**Screenshots**
N/A

**Version and implementation**
Version: 5.15.1
Browser and version: N/A

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm this is still an issue in 6.x, let's assign @talbs

**Comment by talbs** [comment]
D'oh! Sorry about that. We'll get this fixed up in Font Awesome 6 (starting with our next Alpha).
