### ISSUE TITLE
`sr-only` class has side-effects on Chrome scrolling behavior

### ISSUE THREAD

**Issue by Lou117** [FortAwesome/Font-Awesome#17481]
**Describe the bug**
`sr-only` class has side-effects with Chrome scrolling behavior.

I contacted Chromium team about I thought was a scrolling behavior bug on their side (https://bugs.chromium.org/p/chromium/issues/detail?id=1154640). It turns out it's not:

> It appears there is an element within each row of the table which is contributing scrollable-overflow to the outer scroll container. This is styled with the class:
>
> `.sr-only {
  border: 0;
  clip: rect(0,0,0,0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px
}`
>
> Specifically this element ends up being 1x1, and as it is "position: absolute", it will "punch through" to its container.
>
> In this case:
`document.getElementsByClassName('sr-only')[0].offsetParent`
will be the "viewport-main" element.
>
> There a few potential fixes:
> 1. Size the element such that it is 0xN, or Nx0 (e.g. "width: 0" or similar).
> 2. Make the element "display: none".
> 3. Surround the element in a 0x0 div which is also "position: absolute".
> 4. Make "viewport-router" a containing block (e.g. "position: relative" or similar).
> 5. Change the "viewport-main" to "overflow-y: hidden" or similar.
> 
> Historically scrollable overflow has been poorly defined, however we believe that our current behaviour is correct as per the CSSWG specification for this.

I am fully aware that the last 2 fixes discussed can be implemented on our (user) side, and will be until you (possibly) implement a fix. But because I think I will not be the only one, it would be great if you consider a "fix" (more of a tweak imho).

**To Reproduce**
A static version of the page is attached. Keep in mind that this behavior is specific to Chrome, as I tested with Firefox and not had this issue (this is why I thought it was a Chrome bug).

**Expected behavior**
SR-only class should not interfere with scrolling behavior in Chrome (or any) browser.

**Version and implementation**
Version: v5.15.1
Browser and version: Chrome 87.0.4280.88

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

[static.zip](https://github.com/FortAwesome/Font-Awesome/files/5688936/static.zip)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this detailed report.

Since this implementation is inherited from Bootstrap, I've checked the latest version available:

https://github.com/twbs/bootstrap/blob/b5fb84a91d43d5178c3a6732355f346fdc3a113c/scss/mixins/_visually-hidden.scss

It references to Orange-OpenSource/Orange-Boosted-Bootstrap#84

Is this the same issue you are reporting?

Anyway... Can I ask you to check if this is also reproducible with bootstrap's implementation of `._visually-hidden`?

**Comment by tagliala** [comment]
> But I suspect they have good reasons to not use display property...

My guess is the same.

There are two articles linked in their css, one is: https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/

Quoting from the above article:

> Developers commonly use display: none to hide content on the page. Unfortunately, this common action can be problematic for people who use screen readers, especially if the hidden content was meant to be for them to discover...

So I would say that this is all about not using `display: none` 😅

Anyway, if this is a problem with Bootstrap's implementation, I think they have more expertise on this specific matter

Any chance to create a jsfiddle/codepen/codesandbox reproducing the issue, without the need of downloading zip files?

**Comment by tagliala** [comment]
FA6's implementation is similar to Tailwind CSS's one: https://tailwindcss.com/docs/screen-readers

**Comment by talbs** [comment]
Thanks for bringing this to our attention. We've got a revised and updated `.fa-sr-only` utility in our latest V6 Alpha. As the awesome @tagliala mentioned, it should address this Chrome bug. If you kick the tires on the Alpha, let us know if this isn't the case (and if anything else is off).

**Comment by Shashank-Bhatt1** [comment]
Hi all, I was also getting the strange scrollbar and after debugging for more than 5 hours, i was able to found this `sr-only` class. 
As of now i have added position relative above the `sr-only` parent. 
Can anyone please suggest what is the proposed solution for this?

**Comment by drskullster** [comment]
@Shashank-Bhatt1's message is two years old, but for anyone arriving here in search of a fix you can add this in your css rules:

```css
.sr-only {
  top: 0;
  left: 0;
}
```
