### ISSUE TITLE
Font Awesome Brands free icons show up as blank squares

### ISSUE THREAD

**Issue by therandomfool** [FortAwesome/Font-Awesome#17499]
Trying to add font awesome icons to new project.  
1. I have included my embed code in the head and verified it on the Font Awesome site.
2. I do not currently have any CSS set up to override the FA
3. Initially trying to use fab fa-css3-alt, fab fa-java, fab fa-js with a basic button set up.

![Screen Shot 2020-12-18 at 5 38 04 PM](https://user-images.githubusercontent.com/49601011/102677547-dbc4cc80-4157-11eb-90a1-27e57599a0e3.png)
![Screen Shot 2020-12-18 at 5 37 40 PM](https://user-images.githubusercontent.com/49601011/102677549-dc5d6300-4157-11eb-886f-392247845741.png)

I tried a few icons with basic fa fa- notation and they work fine so I am set up correctly.
![Screen Shot 2020-12-18 at 6 11 21 PM](https://user-images.githubusercontent.com/49601011/102678330-77583c00-415c-11eb-89a7-532005d780ab.png)

UPDATE:

**I have solved my issue.  Of course it was to human error.  Thanks for having this great community**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From the paper plane design, I'm pretty confident that you are using Font Awesome 4.

Please upgrade to FA5: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Closing here, but feel free to comment
