### ISSUE TITLE
Icon request: Huawei App Gallery <4

### ISSUE THREAD

**Issue by konipro** [FortAwesome/Font-Awesome#17495]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I guess this request is a duplicate of #17213, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

If this is not a duplicate, feel free to comment and clarify

Closing here

**Comment by wazeer-bravo** [comment]
What the link for Huawei AppGallery? I find not found it? @tagliala
