### ISSUE TITLE
Icon request: icon-landslide

### ISSUE THREAD

**Issue by mar-design** [FortAwesome/Font-Awesome#17502]
**What can it be used for?**
This icon is to be used to represent landslides for property owners, roadways, geological emergencies, safety....
**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/76451594/102816240-8c161900-4382-11eb-90e6-9c4961f0eb16.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @mar-design,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/hill-rockslide

Regards.

cc/ @tagliala
