### ISSUE TITLE
Icon Request: icon-ranking (leaderboard)

### ISSUE THREAD

**Issue by ludoblues** [FortAwesome/Font-Awesome#1750]
Something simple like:

http://fpm.pt/pt-pt/data/uploads/slideshow/imagens/ranking.jpg
or
http://blog.educpros.fr/community-manager-a-l-universite/files/2012/12/google-ranking.jpg

**Comment by Stexe** [comment]
+1. But very simple. Just three podium standings: 3-1-2 with 3 being the lowest, 1 being the highest, and 2 in between. Used for "leaderboards" and other things.

**Comment by nitzanwilnai** [comment]
Any ETA on this one?

**Comment by tagliala** [comment]
no timeline, sorry

you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by velosipedist** [comment]
+1

**Comment by lots0logs** [comment]
+1

**Comment by jpsantos7** [comment]
+1

**Comment by iarroyo5** [comment]
+1

**Comment by jeremierichard** [comment]
+1

**Comment by Vixxd** [comment]
Definitely interested in this - a medal/trophy implies 'achievements' that are being unlocked, whereas a leaderboard (1, 2, 3 on podiums) very clearly indicates ranking. I think they should remain separate. Would love this for a game - thanks.

**Comment by manofspirit** [comment]
+1

**Comment by tagliala** [comment]
Let's use #4467, which is newer but has more +1s (and a better name)

By the way [Font Awesome's Icon Leaderboard](https://fontawesome.com/community/leaderboard/new) uses `fa-trophy`
