### ISSUE TITLE
Icon request: CVV / CVC Number

### ISSUE THREAD

**Issue by gregsaxton** [FortAwesome/Font-Awesome#17501]
**What can it be used for?**
used to illustrate where to find the 3 digit security code (called the CVC or CVV number) on the back of your credit/debit card.

**Example image (optional)**
![CVC Icon](https://user-images.githubusercontent.com/659467/102747915-4aeb2c80-43b5-11eb-9fbc-98211af80f2e.png)

**Icon request checklist**
- [ x ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x ] I have included at least one example image if it could be helpful (optional)
- [ x ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This number is also known as CV2, and it exists as a request here: #4373 and I was waiting for a feedback

Please post your example there and add a 👍  request, so I will change the title to include CVV / CVC and add proper labels

Spoiler alert: that request is 6 year old and does not have upvotes
