### ISSUE TITLE
Icon request: icon-bbus

### ISSUE THREAD

**Issue by romeoagbo** [FortAwesome/Font-Awesome#17500]
![logo_full](https://user-images.githubusercontent.com/39996150/102686904-365b3880-41eb-11eb-8943-6b1820843f32.png)
![logo_icon](https://user-images.githubusercontent.com/39996150/102686914-3fe4a080-41eb-11eb-979a-05f20ed6e717.png)
![iconebus](https://user-images.githubusercontent.com/39996150/102686983-dadd7a80-41eb-11eb-8c2e-63cd24eb6b2e.png)
![icone_paiement](https://user-images.githubusercontent.com/39996150/102686985-dc0ea780-41eb-11eb-8253-ffbd76be397b.png)
![icone_billetterie](https://user-images.githubusercontent.com/39996150/102686986-dca73e00-41eb-11eb-8878-d1b75b84084a.png)
![iconecompagnie](https://user-images.githubusercontent.com/39996150/102686987-dd3fd480-41eb-11eb-84a0-00a3fd0cf02f.png)
![icone_colis_courrier](https://user-images.githubusercontent.com/39996150/102686988-dd3fd480-41eb-11eb-8846-30d46196fd2e.png)
![personnel](https://user-images.githubusercontent.com/39996150/102686989-ddd86b00-41eb-11eb-98ce-0b9eb9724437.png)

**What can it be used for?**
Describe how this could be used / the use case for this icon.
public icon to be used for transport (buses)

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] unlock
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

There are a lot of different examples, plus something that looks like a brand but I'm not able to find information on Google

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
