### ISSUE TITLE
Can you please send the checksum archive 5.12.0 of fontawesome pro by email ?

### ISSUE THREAD

**Issue by kopax** [FortAwesome/Font-Awesome#17527]
First of all, happy new year,

**Describe the bugg**
This issue follow https://github.com/FortAwesome/Font-Awesome/issues/16094 where I asked for the correct archive installed in my project, hello@fontawesome.com did send me some archive that I am now trying to reinstall but it's missing the package `@fortawesome/fontawesome-pro` v5.12.0 so I still can't get started with this project.

May I ask to get this one mailed as well? It's really annoying.

**Comment by tagliala** [comment]
Hi, do you have access to this page?

https://fontawesome.com/download#pro-packages

**Comment by kopax** [comment]
I have just mailed this to `hello@fontawesome.com:

```
Hello & Happy new year,


I am still stuck with the archive you've emailed to me, see the following issues for tracking:

https://github.com/FortAwesome/Font-Awesome/issues/16094
https://github.com/FortAwesome/Font-Awesome/issues/17527

I wanted the 5.12.0 to avoid having package-lock.json error in an old project.

This is what you have emailed to me:

fortawesome-pro-duotone-svg-icons-5.12.0.tgz
fortawesome-pro-regular-svg-icons-5.12.0.tgz
fortawesome-pro-solid-svg-icons-5.12.0.tgz
fortawesome-pro-light-svg-icons-5.12.0.tgz

This is the package I am missing: @fortawesome/fontawesome-pro@5.12.0.tgz

I expect to respect the package-lock.json so my project won't break as if I was recreating it after 2 years of break in the development, this is how I want to configure my package.json dependencies:

    "@fortawesome/fontawesome-pro": "file:fortawesome-fontawesome-pro-5.12.0.tgz",
    "@fortawesome/fontawesome-svg-core": "^1.2.18",
    "@fortawesome/free-brands-svg-icons": "^5.12.1",
    "@fortawesome/free-regular-svg-icons": "^5.12.1",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@fortawesome/pro-light-svg-icons": "file:fortawesome-pro-light-svg-icons-5.12.0.tgz",
    "@fortawesome/pro-regular-svg-icons": "file:fortawesome-pro-regular-svg-icons-5.12.0.tgz",
    "@fortawesome/pro-solid-svg-icons": "file:fortawesome-pro-solid-svg-icons-5.12.0.tgz",

This is somehow urgent and I am surprised that you did not pay more attention to the archive you've mailed before.

I hope this can be solved fast, 

Best regards,
```

The problem with your link is that it gets a different distributed archive which is not for npm nor `package-lock.json`, can you please ask the staff to take care of this issue?

**Comment by kopax** [comment]
This is the content of the downloaded archive using your link:

![image](https://user-images.githubusercontent.com/1866564/103457343-c080c200-4cfe-11eb-984b-ba14f3869ee8.png)

This won't help match the checksum from my `package-lock.json`

**Comment by tagliala** [comment]
Ok, got it. I'm not referring to that file

I've selected "5.12.0" from the dropdown menu and I was able to download `fortawesome-fontawesome-pro-5.12.0.tgz`. Can you see the below section on your page?


![image](https://user-images.githubusercontent.com/556268/103457356-f0c86080-4cfe-11eb-83bf-f879f928c0fc.png)

**Comment by kopax** [comment]
This is the whole page:

![image](https://user-images.githubusercontent.com/1866564/103457392-3c7b0a00-4cff-11eb-88b1-8d3378bb59bd.png)


How did you get access to that file?

**Comment by tagliala** [comment]
> How did you get access to that file?

It should be visible in that page, but I may got this feature wrong. 

@robmadole isn't this supposed to work also for old subscriptions, locked to the latest version available at the moment the subscription ended?

> Can you please email it to me using my GitHub email?

Apologies, I can't. I do not provide this kind of support

> Can you please ask the staff to take care of this issue?

The best thing we can do is send an email. If you don't get an answer in 1 business day feel free to ping here

Another question for you

In this page, https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Can you see "Using the npm Download" in the right sidebar?
![image](https://user-images.githubusercontent.com/556268/103457519-5bc66700-4d00-11eb-9516-fa6d18d6c2bc.png)

**Comment by kopax** [comment]
> Apologies, I can't. I do not provide this kind of support

You just showed me that you had access, so did I, please reconsider and make an exception for that particular case... My fontawesome email is `kopx@free.fr`, you can also mail it here, this is the proof that it is my account (upper right corner in the menu):

![image](https://user-images.githubusercontent.com/1866564/103457591-eeff9c80-4d00-11eb-92ba-15acc12b010a.png)


> Can you see "Using the npm Download" in the right sidebar?

No I can't

![image](https://user-images.githubusercontent.com/1866564/103457563-afd14b80-4d00-11eb-9d40-f174b68f52fd.png)

**Comment by tagliala** [comment]
Ok, so I didn't get how that features work or there is an issue.

> You just showed me that you had access, so did I, please reconsider and make an exception for that particular case..

Apologies, I can't. Let me know if you don't get answers from the support

**Comment by kopax** [comment]
> Ok, so I didn't get how that features work or there is an issue.
> 
> > You just showed me that you had access, so did I, please reconsider and make an exception for that particular case..
> 
> Apologies, I can't. Let me know if you don't get answers from the support

Why can't you? If you do, I can get started with my work now and spend time with my kids.

**Comment by tagliala** [comment]
> Why can't you?

I'm not in charge of customer service and license-related issues

I thought this issue could be solved on user side through the recently added "Pro packages" section, but now I think I didn't get that functionality correctly :\

**Comment by kopax** [comment]
You still have access to that package and most likely the repository. I must insist, can I send you the `tar.gz` so you can notice I have in my possession part of the version, I don't know what else I can do to get more help from you than you are supposed to. I hope your management can understand that you served during the weekend and fixed a mistake done by the owner of fontawesome himself. Forwarding our conversion on your email where I got from him half of the version would be good enough for you,... I hope.  In all case, if you don't, I might now lose days of development for an issue caused by fontawesome.

**Comment by tagliala** [comment]
> I hope your management can understand that you served during the weekend and fixed a mistake done by the owner of fontawesome himself

I tried to help by proposing that solution. Unfortunately it didn't work, so we should wait for an answer from `hello@fontawesome.com`. Let me know when you have solved

**Comment by robmadole** [comment]
@kopax I'm looking up your information now

**Comment by robmadole** [comment]
@kopax I'll answer you in the email you sent to hello@fontawesome.com

**Comment by kopax** [comment]
Hi @robmadole , I did not received any reply except thosefrom GitHub. Can you send again please ?

**Comment by kopax** [comment]
Hi @robmadole , thanks for the kind answer and understanding for your customer (old but still) being stuck with a pro version not available since access to it was cut without any notice, I appreciated it. I understand that's not convenient that it happen now during holiday and new year. I still think and wished this should not have happened at all and we all get some frustration out of it. Issue is still not resolved.

**Comment by robmadole** [comment]
@kopax yep, I see the reply to our hello@fontawesome.com email thread. (Do you have difficulty getting these emails? We use a service called Helpscout.)

I do understand your frustration and even though you may not be a paying subscriber you are still part of our community. We'll get this figured out and get you fixed up when we our team is back in the office.

**Comment by kopax** [comment]
Hi @robmadole , would you mind re-opening this? thanks in advance,

**Comment by robmadole** [comment]
@kopax I do mind. We'll use the help ticket created by the email you sent to hello@fontawesome.com.
