### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by lancethunder** [FortAwesome/Font-Awesome#17525]
**What can it be used for?**
different database brand logos; MySQL, MongoDB, PostgreSQL, Oracle

FontAwesome has a nice collection of different technology logos but none of the popular database brands are represented. Having those logos in the collection would help me out a lot in one of my personal projects and I am sure others could use them too. You may even be able to get commissions to make these logos if you approach the organizations that maintain these technologies.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This is a single icon or matched pair (Ex: lock / unlock)

Sorry, icon sets are not allowed by our contributing guidelines.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
