### ISSUE TITLE
Migrating from standard FontAwesome to using a Kit

### ISSUE THREAD

**Issue by leeroygbiv** [FortAwesome/Font-Awesome#17521]
I was just playing around with your Kit feature for the first time.

I ran into an issue. In a theme that I maintain, there are various places where I have nested invisible text inside of an icon. Example, the inside of the mobile menu button may look like this:

`<i class="fa fa-bars"><span class="sr-only">Toggle Navigation</span></i>`

There is no problem with this, using the standard (non-Kit) version of Font Awesome. But, the Kit JS throws a fit here - and fails to load the icon.

I then tested the following:

```
<i class="fa fa-search">test 1</i>
<i class="fa fa-search"><span class="sr-only">test 2</span></i>
```

The Kit also throws a fit.

Is this intentional? Or a known issue? Nothing can be nested inside of an icon, or the Kit will fail to load the SVG?

In the first example, the "Toggle Navigation" is there for ADA purposes. I would argue, your Kit should grab any text inside, and apply that as a title / alt / aria-label / whatever. Rather than just fail.

Now - if you were to inform me that putting my ADA text inside of the icon (`<i></i>`) is semantically incorrect, or goes against web standards... then I would just re-work my base theme to comply. If this is just a bug, or short-coming in your Kit - it would be nice if it could be... "fixed", rather than me having to locate and redo all offending buttons in the theme.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> ```html
> <i class="fa fa-search">test 1</i>
> <i class="fa fa-search"><span class="sr-only">test 2</span></i>
> ```

The above is not a supported use case (it never was). Please use empty tags for icons.

Example for JS kits:
```html
<!-- Decorative icon. JS Kit will add aria-hidden attribute -->
<i class="fa fa-search"></i> test 1

<!-- Semantic icon. JS Kit will take care of transforming the title attribute for screen readers -->
<i class="fas fa-search" title="test 2"></i>
```

Docs:
- https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility

Hope it helps

Closing here, but feel free to comment

**Comment by leeroygbiv** [comment]
> The above is not a supported use case (it never was). Please use empty tags for icons.|
Well it *does* work, perfectly fine, for the standard (non-Kit) Font Awesome. It has never been a problem. Until I tried to use Kit.

But I will go ahead and adjust my theme!

Thanks.

**Comment by tagliala** [comment]
> Well it does work, perfectly fine, for the standard (non-Kit) Font Awesome. It has never been a problem. Until I tried to use Kit.

It may work for your use case, but it is not officially supported and it has side effects.

The Font Awesome style class (`fa` in 4.7, `fa*` in 5.x) contains the font-family definition, so it is a problem if your web application uses a different font-family

Demo: https://jsfiddle.net/tagliala/L5fum0ea/7/

Screen:

![image](https://user-images.githubusercontent.com/556268/103380337-d61c9e80-4ae8-11eb-98b8-a4936480793c.png)

Hope it helps to clarify
