### ISSUE TITLE
Re-install of fonts is necessary to use in streamlabs obs

### ISSUE THREAD

**Issue by Cynera** [FortAwesome/Font-Awesome#17536]
**Describe the bug**
When I install the fonts and open StreamlabsOBS, I can use the icons in a text label. However once I reboot my PC, I have to reinstall the fonts before they will render in StreamlabsOBS again.

**To Reproduce**
1. Download the FontAwesome Free for Desktop from https://fontawesome.com/download
2. Install the 3 fonts located in /otfs folder. (You can install by double clicking a font, or drag and drop into the windows Fonts settings)
3. Open StreamLabsOBS
4. Add a `Text (GDI+)` to any scene, change the font family to Font Awesome 5 Free Solid, and paste the unicode glyph into the text box (eg: )
5. Notice that the icon is correctly displayed.
6. Reboot the PC.
7. Open StreamlabsOBS, notice that the icons are not displaying
8. Repeat step 2, then close and re-open StreamlabsOBS
9. Notice the icons are correctly displayed.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
I should not have to re-install the fonts on Windows every time I want to open StreamlabsOBS

**Screenshots**
Not Displayed
![image](https://user-images.githubusercontent.com/18402715/104083355-c725a280-51f2-11eb-8a20-1a1784f6b604.png)
Displayed
![image](https://user-images.githubusercontent.com/18402715/104083387-f63c1400-51f2-11eb-90a4-9dfce73bd71c.png)

**Version and implementation**
Versions: 
FontAwesome: fontawesome-free-5.15.1-desktop
StreamlabsOBS: 0.26.0
Windows 10 Home

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

**Comment by Cynera** [comment]
Done!

**Comment by tagliala** [comment]
Thanks.

Could you please try:

- Another otf webfont: https://github.com/google/material-design-icons/tree/master/font
- Font Awesome icons with regular style

**Comment by Cynera** [comment]
Perhaps I'm downloading them incorrectly, but none of the ots fonts available in that link are "valid font files". I will try with a different otf from somewhere on the wide googles.

**Comment by Cynera** [comment]
Ah ok, the same occurs with another OTF I've found online, as well as the Font Awesome Regular style. Is it possible to yet the FontAwesome icons in TTF format?

**Comment by tagliala** [comment]
> Is it possible to get the FontAwesome icons in TTF format?

Yes, you can find them in the web package

### ⚠️ Disclaimer
Please notice that those TTF are optimized for the web and are not supposed to be used for desktop or printing purposes, so they are not supported for desktop use case (e.g., wkhtmltopdf/wkhtmltopdf#2022)

Please also report this issue to https://github.com/stream-labs/streamlabs-obs/
