### ISSUE TITLE
Square icons color is not filled for CSS pseudo elements

### ISSUE THREAD

**Issue by duck-nguyen** [FortAwesome/Font-Awesome#17537]
**Describe the bug**
I'm trying to use `square(\f0c8)` and `square-full(\f45c)` as the content for pseudo elements in my CSS. The icons show up as square (or full square) but are the color is not filled in as the [cheatsheet](https://fontawesome.com/cheatsheet) indicate. 

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

**Expected behavior**
Base on how it's listed in the cheatsheet and on the icons page. I expected the color to be filled.

**Screenshots**
Here's an example screenshot. As you can see, using `\f0c8` shows a red-bordered square, not a filled in square as shown in the cheatsheet or listed in the icons page.

![Screen Shot 2021-01-07 at 7 59 42 PM](https://user-images.githubusercontent.com/77133996/103973137-9460a900-5123-11eb-9a06-cefb7305f36a.png)

**Version and implementation**
Version: Font Awesome 5 Pro
Browser and version: Chrome on IMac

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think it is just the `font-weight` missing on solid icons

Ref: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here, but feel free to comment
