### ISSUE TITLE
FA won't load icons on home page of https://stnoel.org

### ISSUE THREAD

**Issue by BenjaminBarnett** [FortAwesome/Font-Awesome#17530]
**Describe the bug**
FA was previously loading, pre-5.0.x, with a call embedded in my client's WordPress site theme. When I noticed FA icons on home page were broken, I installed your plugin and suppressed the theme's old library call. Icons still aren't loading though.

**To Reproduce**
https://stnoel.org

**Expected behavior**
Row of quick links (calendar / bulletin / facebook / YouTube / etc.) should show their FA icons above each text link

**Screenshots**

**Version and implementation**
Version: 5.15.1 (with 4.x compatibility switched off, and using free CDN)
Browser and version: NA, it appears broken for all browsers

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see in the `<head>` tag that there is still a call to FA 4.7.0, but I can't see any reference to 5.x

```
<link rel='preload' href='//cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css?ver=4.7.0' data-rocket-async="style" as="style" onload="this.onload=null;this.rel='stylesheet'" type='text/css' media='all' />
```

> I installed your plugin and suppressed the theme's old library call. 

https://wordpress.org/plugins/font-awesome/ is the one and only official Wordpress plugin. Can you please confirm that you are using the latest available version of this plugin?

If you do, please check the troubleshooting guide: https://fontawesome.com/how-to-use/on-the-web/using-with/wordpress#troubleshooting

If you still have issues, please let me know
