### ISSUE TITLE
Issue: Fontawesome.com SSL Issue - SEC_ERROR_REVOKED_CERTIFICATE

### ISSUE THREAD

**Issue by Snexed** [FortAwesome/Font-Awesome#17535]
**Describe the bug**
The whole site including kits is currently down in the latest version of Firefox Nightly which got released this morning (7th) because of an SSL Issue. 

The SSL issue is:
An error occurred during a connection to www.fontawesome.com. Peer's Certificate has been revoked.

Error code: SEC_ERROR_REVOKED_CERTIFICATE

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.

This is only an issue in the latest version of Firefox Nightly and is fine in Chrome and Edge and Fontawesome is the only website which I'm having difficulty loading at all.

**To Reproduce**
https://www.fontawesome.com on Firefox Nightly.

**Expected behavior**
N/A

**Screenshots**
N/A

**Version and implementation**
Version: All Versions
Browser and version: Firefox Nightly v86.0a1

- [X] SVG with JS
- [X] Web Fonts with CSS
- [X] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by xXBuilderBXx** [comment]
I'm getting the same issue too and tried contacting font awesome by email.

**Comment by tagliala** [comment]
@xXBuilderBXx with Firefox nightly?

**Comment by xXBuilderBXx** [comment]
@tagliala yes with Firefox Nightly 68

**Comment by mesosoi** [comment]
I confirm that. I'm using Firefox Nightly 68 on Windows 10.

**Comment by cyrill62** [comment]
I have the same issue with Firefox Nightly 86 on Linux x86_64

**Comment by dpeukert** [comment]
This has been fixed by the Firefox folks (https://hg.mozilla.org/mozilla-central/rev/d6749ac7de51) and will probably appear in the nightly builds soon.

**Comment by tagliala** [comment]
Thanks for the heads-up, please let me know when it is fixed, so I can close here

**Comment by mesosoi** [comment]
Fixed! :D
