### ISSUE TITLE
Icon request: dog

### ISSUE THREAD

**Issue by LaurentC14** [FortAwesome/Font-Awesome#17544]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
https://fontawesome.com/icons/dog?style=solid :)

**Comment by LaurentC14** [comment]
Merci, j'ai pu aller jusqu'à là, mais c'est pour réupérer l'icone. j'ai ce code <i class="fas fa-child"></i>, mais ça ne marche pas.

Thanks, I was able to get there, but it's to retrieve the icon. I have this code <i class = "fas fa-child"> </i>, but it doesn't work.


De : Geremia Taglialatela<mailto:notifications@github.com>
Envoyé le :lundi 11 janvier 2021 12:34
À : FortAwesome/Font-Awesome<mailto:Font-Awesome@noreply.github.com>
Cc : LaurentC14<mailto:laurent.claude14@hotmail.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [FortAwesome/Font-Awesome] Icon request: dog (#17544)


https://fontawesome.com/icons/dog?style=solid :)

**Comment by tagliala** [comment]
Hi @LaurentC14 

Please make sure that you are using Font Awesome 5.12.0 or newer (latest version is 5.15.1)

> `<i class = "fas fa-child"> </i>`

This code is for a different icon. Anyway, if you have an issue please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by LaurentC14** [comment]
Site donated by openclassrooms
https://fontawesome.com/



Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Geremia Taglialatela<mailto:notifications@github.com>
Envoyé le :lundi 11 janvier 2021 15:55
À : FortAwesome/Font-Awesome<mailto:Font-Awesome@noreply.github.com>
Cc : LaurentC14<mailto:laurent.claude14@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [FortAwesome/Font-Awesome] Icon request: dog (#17544)


Hi @LaurentC14<https://github.com/LaurentC14>

Please make sure that you are using Font Awesome 5.12.0 or newer (latest version is 5.15.1)

<i class = "fas fa-child"> </i>

This code is for a different icon. Anyway, if you have an issue please fill out our bug report template<https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md>

**Comment by tagliala** [comment]
Apologies, didn't get the last message

> Site donated by openclassrooms
> https://fontawesome.com/

Could you please clarify?

Please avoid emails if you are trying to paste contents, use GitHub at https://github.com/FortAwesome/Font-Awesome/issues/17544

**Comment by LaurentC14** [comment]
Of course !!
The link I sent you was given to me by my training organization openclassrooms to retrieve the icons of the site that I make in htlm
Do you understand ?

De : Geremia Taglialatela<mailto:notifications@github.com>
Envoyé le :lundi 11 janvier 2021 16:18
À : FortAwesome/Font-Awesome<mailto:Font-Awesome@noreply.github.com>
Cc : LaurentC14<mailto:laurent.claude14@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [FortAwesome/Font-Awesome] Icon request: dog (#17544)


Apologies, didn't get the last message

Site donated by openclassrooms
https://fontawesome.com/

Could you please clarify?

Please avoid emails if you are trying to paste contents, use GitHub at #17544<https://github.com/FortAwesome/Font-Awesome/issues/17544>

**Comment by tagliala** [comment]
> The link I sent you was given to me by my training organization openclassrooms to retrieve the icons of the site that I make in htlm

Ok, thanks. Got it.

That is correct, it is the official website with documentation and instructions on how to install and use Font Awesome

We use this GitHub tracker to track bug and issues, if you need support please read the docs and then ask StackOverflow if you have questions

Docs:
- Getting started: https://fontawesome.com/start
- Basic usage: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

If you still have issues and you think there is an issue with Font Awesome, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md), taking care of providing all the information required

**Comment by LaurentC14** [comment]
Hi Geremia,

Thanks very much for your help 😊
Best regards

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Geremia Taglialatela<mailto:notifications@github.com>
Envoyé le :lundi 11 janvier 2021 16:28
À : FortAwesome/Font-Awesome<mailto:Font-Awesome@noreply.github.com>
Cc : LaurentC14<mailto:laurent.claude14@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [FortAwesome/Font-Awesome] Icon request: dog (#17544)


The link I sent you was given to me by my training organization openclassrooms to retrieve the icons of the site that I make in htlm

Ok, thanks. Got it.

That is correct, it is the official website with documentation and instructions on how to install and use Font Awesome

We use this GitHub tracker to track bug and issues, if you need support please read the docs and then ask StackOverflow if you have questions

Docs:

  *   Getting started: https://fontawesome.com/start
  *   Basic usage: https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

If you still have issues and you think there is an issue with Font Awesome, feel free to fill out our bug report template<https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md>, taking care of providing all the information required
