### ISSUE TITLE
Icon Request: Magento

### ISSUE THREAD

**Issue by ideirj** [FortAwesome/Font-Awesome#1754]
Magento is an open source e-commerce web application.
More info: http://www.magentocommerce.com/

**Comment by jstrobel** [comment]
+1

**Comment by pinedamg** [comment]
+1

**Comment by RobXYZ** [comment]
+1

**Comment by raybogman** [comment]
+1

**Comment by laebs** [comment]
+1

**Comment by zrosenbauer** [comment]
+1

**Comment by conversiongreen** [comment]
+1

**Comment by Celldweller** [comment]
+1

**Comment by vicalopez** [comment]
+1

**Comment by tomsommer** [comment]
#5624

**Comment by tomsommer** [comment]
+1

**Comment by sandeepvaishnav** [comment]
+1

**Comment by dancingmongoose** [comment]
+1

**Comment by mongbatstar** [comment]
+1

**Comment by renanseni** [comment]
+1

**Comment by Bogardo** [comment]
+1

**Comment by ogojack** [comment]
+1

**Comment by royduin** [comment]
+1

**Comment by TJohnson93** [comment]
+1

**Comment by LironNave** [comment]
+1!

**Comment by kayintveen** [comment]
+1

**Comment by pinedamg** [comment]
+1

**Comment by tomassouto** [comment]
+1

**Comment by devunion** [comment]
+1

**Comment by royduin** [comment]
For the time being, you can use a additional font: https://github.com/websiddu/technology-icons

**Comment by skishyfish** [comment]
+1

**Comment by pixelive** [comment]
+1

**Comment by rbrugnollo** [comment]
+1

**Comment by alvinnguyen** [comment]
+1

**Comment by dimasdwika** [comment]
+1

**Comment by webeks** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by loorlab** [comment]
+1 Please !

**Comment by aguilar1181** [comment]
+1

**Comment by team-core** [comment]
+1

**Comment by cameronjonesweb** [comment]
+1

**Comment by IamSwap** [comment]
+1

**Comment by fabioplateroti** [comment]
+1

**Comment by wilcotickles** [comment]
+1

Come on guys, it's been two years since wordpress has been added, and this request is older. Wordpess and Magento both are huge platforms in the webdevelopment industry, please add the Magento icon too.

**Comment by tagliala** [comment]
The original request for wordpress was #221 (https://github.com/FortAwesome/Font-Awesome/issues/221#issuecomment-36605869)

**Comment by wilcotickles** [comment]
@tagliala That makes it even worse that Magento still hasn't received a spot into the pack. :(

**Comment by charliedemsky** [comment]
+1!

**Comment by gxjansen** [comment]
+1

**Comment by sprankhub** [comment]
+1

**Comment by akira28** [comment]
+1

**Comment by wsakaren** [comment]
+1

**Comment by mbrinton01** [comment]
+1

**Comment by digitalpianism** [comment]
+1

**Comment by swieczorek** [comment]
+1

**Comment by amenk** [comment]
+5

**Comment by Khaleel** [comment]
+1

**Comment by avoelkl** [comment]
+1

**Comment by thienlan** [comment]
+1

**Comment by Wesdesignz** [comment]
+1

**Comment by tzyganu** [comment]
:+1: x :100:

**Comment by joshuaswarren** [comment]
+1

**Comment by dct2012** [comment]
+1

**Comment by scercrow** [comment]
+1

**Comment by aleron75** [comment]
+1

**Comment by talesh** [comment]
+1

**Comment by RebeccaLTroth** [comment]
+1

**Comment by adampmoss** [comment]
+1

**Comment by nuovecode** [comment]
+1 Jeee!

**Comment by adinca** [comment]
👍

**Comment by johnhughes1984** [comment]
+1

**Comment by barbanet** [comment]
+1

**Comment by tniebergall** [comment]
+1

**Comment by SeoFood** [comment]
+1

**Comment by themecs** [comment]
+1

**Comment by kalenjordan** [comment]
+1

**Comment by mcspronko** [comment]
+2

**Comment by HirokazuNishi** [comment]
+1

**Comment by kesonno** [comment]
+1 🙏

**Comment by rafaelstz** [comment]
+1

**Comment by johandekruijf** [comment]
+1

**Comment by rubenRP** [comment]
+1

**Comment by DanCarlyon** [comment]
+1

**Comment by jjeroennl** [comment]
+1

**Comment by loorlab** [comment]
+zzzzzzzzzzzzzzzzzzzzzz

**Comment by marcelmaagdenberg** [comment]
+1000000000

When add Magento icon?

**Comment by loorlab** [comment]
2013-2017

**Comment by marcelmaagdenberg** [comment]
There more requists...

Telegram
Magento
osCommerce

**Comment by jaimiedijstra** [comment]
+1 too!!!
This request has been going for some time, wondering if this is a licensing issue with Magento/Ebay's rules quoting their page at [https://magento.com/legal/licensing](https://magento.com/legal/licensing):

> Magento logo and Magento-owned graphic symbols - You may not use the Magento logo or any other Magento graphic symbol, logo, or icon on or in connection with web sites, products, packaging, manuals, promotional/advertising materials, or for any other purpose except pursuant to an express written agreement (such as a Business Partner Agreement).

Can anyone clarify what's happening so this topic is not left out in the void with no progress or clarification?

**Comment by loorlab** [comment]
@jaimiedijstra Really ? Magento is Magneto. http://www.cosas-que-pasan.com/wp-content/uploads/magento.jpg

**Comment by jaimiedijstra** [comment]
hehe, wondering though if this topic is going to go anywhere, it would great to add it after all this time.

**Comment by raNikola** [comment]
+1

**Comment by leandrovr13** [comment]
+1

**Comment by josephfelix** [comment]
+1

**Comment by SolsWebdesign** [comment]
+1

**Comment by cadence-labs** [comment]
+1

**Comment by doprdele** [comment]
👍 +1

**Comment by podenemus** [comment]
+1

**Comment by ecenica** [comment]
+1

**Comment by StVak** [comment]
+1

**Comment by Skorm92** [comment]
+1!

**Comment by channelriyas** [comment]
+1

**Comment by kuzmit4** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by LuigiMdg** [comment]
+1 for management purpose ([Management Software](https://donagest.com))
