### ISSUE TITLE
trash-alt vs trash-alt-alt

### ISSUE THREAD

**Issue by ReefmanKoen** [FortAwesome/Font-Awesome#17549]
Hello,

We recently purchased Font Awesome Pro.
I noticed that there is a difference between the free version (and the description) and the pro version in using the [trash-alt icon](https://fontawesome.com/icons/trash-alt?style=regular).
In the [free version](https://use.fontawesome.com/releases/v5.15.1/css/all.css) we could use _fa-trash-alt_ whereas in the pro version (also 5.15.1) that same icon is used as _fa-trash-alt-alt_. (trying to use the regular icon with the far prefix).
Is this discrepancy intended? Should we use fa-trash-alt-alt or is this a temporary workaround?
Or is this a bug?

Thank you in advance for your help.

**Comment by tagliala** [comment]
Hi,

I cannot see `fa-trash-alt-alt` in FA Pro 5.15.1's sources

Could you please check that there aren't third-parties to load custom styles?

Fa 5.15.1 Free: https://jsfiddle.net/tagliala/L5fum0ea/12/
Fa 5.15.1 Pro: https://jsfiddle.net/tagliala/requh9sz/1/

**Comment by ReefmanKoen** [comment]
In /css/fontawesome.css and /css/all.css I find on line 6360:

.fa-trash-alt-alt:before {
  content: "\f2ed"; }

Is it possible my colleague downloaded some sort of FA 4 compatible version with this in it?
All files used are from FA directly

**Comment by tagliala** [comment]
> Is it possible my colleague downloaded some sort of FA 4 compatible version with this in it?

V4 compatibility is separated and is provided in a different file, [this one](https://github.com/FortAwesome/Font-Awesome/blob/master/css/v4-shims.css) I can't find `alt-alt` here neither

Please check the css you are using against the original ones

**Comment by ReefmanKoen** [comment]
Just logged in, downloaded the original files from the website and compared,
literally just the fa-trash-alt icons (x12) are different.
Either the issue has already been fixed or we changed something on our end.
Either way, my issue is not a bug (anymore), thanks for helping

**Comment by tagliala** [comment]
Welcome, glad you solved
