### ISSUE TITLE
money transfer

### ISSUE THREAD

**Issue by bbthardikn** [FortAwesome/Font-Awesome#17545]
**What can it be used for?**
money transfer button

**Example image (optional)**
https://www.google.com/search?q=money+transfer+icon&rlz=1C1CHBD_enIN927IN927&sxsrf=ALeKk01VJZV34iKUK7DXSJBManALma4aPA:1610366732476&tbm=isch&source=iu&ictx=1&fir=Lz8dyZT-PQeaDM%252CoFPI8bJhBMLfAM%252C_&vet=1&usg=AI4_-kTac9GHtLJKHeRyc8mD_xZ1nsU0OA&sa=X&ved=2ahUKEwjuyq_I65PuAhUqxjgGHQ18B2cQ9QF6BAgTEAE&biw=1920&bih=969#imgrc=gC9dPKcZ31akXM

**Icon request checklist**
- [x] This is a single icon

**Comment by aethior** [comment]
Hi @bbthardikn,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/money-bill-transfer

Regards.

cc/ @tagliala
