### ISSUE TITLE
Icon request: CV-File 

### ISSUE THREAD

**Issue by andrewderry** [FortAwesome/Font-Awesome#17555]
**What can it be used for?**
Use to indicate that a file is a CV.

**Example image (optional)**
File with the letters CV written inside 

**Icon request checklist**
- [Y ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by andrewderry** [comment]
Used to indicate a CV for recruitment

**Comment by tagliala** [comment]
Hi, we have #3533 available in Font Awesome Pro

You can obtain a similar icon in FA Free by using stacking / layering features from the SVG / JS framework

Demo: https://jsfiddle.net/tagliala/L17f528g/482/

Hope it helps

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
