### ISSUE TITLE
Icon request: Adobe Photoshop

### ISSUE THREAD

**Issue by priyagupta9** [FortAwesome/Font-Awesome#17554]
**What can it be used for?**
Can be used in websites as icon

**Example image (optional)**
![1200px-Adobe_Photoshop_CC_icon svg](https://user-images.githubusercontent.com/55286745/104570194-9ffa2580-5677-11eb-8094-617653bfa1e8.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, can't implement Adobe logos because of Copyright reasons

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150

> The adobe icon has been removed by legal request of Adobe.
>
> Font Awesome is no longer able to provide any logos or marks for the Adobe brand or their products.
