### ISSUE TITLE
Icon request: switch 

### ISSUE THREAD

**Issue by polinar68** [FortAwesome/Font-Awesome#17561]
**What can it be used for?** to unlock everything under the sun
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide an example?

**Comment by defaultsecurity** [comment]
Something like this perhaps? It was derived from the router icon.
![router](https://user-images.githubusercontent.com/34036534/106371001-d9ad7a80-635f-11eb-908b-41f2f8a801e7.png)

**Comment by polinar68** [comment]
@defaultsecurity yes it's perfect so the top round button for turning on, and the top 4 square objects for other option eg. activity status while turning on.,😊
the second round button for turning off, and each square objects working to secure each account connected on it, it looks like any account connected to 'SWITCH' symbol having a STRONG FOUR WALLS to protect it by themselves...😠

**Comment by defaultsecurity** [comment]
@polinar68 
Wait, are we talking about the same thing? I meant a network switch.
![switch](https://user-images.githubusercontent.com/34036534/106379337-852fec80-63ab-11eb-9506-32f8505cda4e.jpg)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
