### ISSUE TITLE
Having Trouble with '-alt' Endings in V6

### ISSUE THREAD

**Issue by jeisel-northglenn** [FortAwesome/Font-Awesome#17562]
I turned off V5 and turned on V6. 

When I opened up InDesign, the items that have 'alt' at the end are not showing up correctly - it looks like 'alt' has its own symbol now? Is there something I need to do?

I also tried funnel-dollar: https://fontawesome.com/icons/funnel-dollar?style=solid - and that's not working, either.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`funnel-dollar` has been renamed to `fa-filter-circle-dollar`
`-alt` have been renamed to something more meaningful

`fa-lock-alt` => `fa-lock-keyhole`

Does this work?
