### ISSUE TITLE
fa-th-large shows regular version when requesting the solid version in v6 alpha

### ISSUE THREAD

**Issue by XanderTenBoden** [FortAwesome/Font-Awesome#17569]
**Describe the bug**
In the FA alpha version, when using `<i class="fa-solid fa-th-large"></i>` loads the regular version of the icon instead of the solid version. Tested on two separate projects and with multiple icons. It happens on both projects, and (as far as tested) only with this icon. Other icons I've used work as expected.

**Expected behavior**
i suspect to see this icon:
https://fontawesome.com/icons/th-large?style=solid
Instead, I get this icon:
https://fontawesome.com/icons/th-large?style=regular

**Version and implementation**
Version: Font Awesome Pro 6.0.0-alpha2
Browser and version: Any

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

We are referring to FA6's `<i class="fa-solid fa-table-cells-large"></i>`

The icon is not the same, I can definitely see the solid version being ticker than the regular one

In FA6, an icon similar to FA5's `th-large` is `<i class="fa-solid fa-grid-2"></i>`

I don't know if the change is intended let's ask @sensibleworld

**Comment by XanderTenBoden** [comment]
Ah, right. The fa-grid-2 is indeed the one I was looking for.

Is there a similar page on which I can look up the FA6 icons?

**Comment by tagliala** [comment]
> Is there a similar page on which I can look up the FA6 icons?

AFAIK, there is the ability to host documentation on your development machine, just download the alpha package and take a look at the readme
