### ISSUE TITLE
Conflicting unicode between custom icons and standard icons

### ISSUE THREAD

**Issue by jbwharris** [FortAwesome/Font-Awesome#17572]
**Describe the bug**
When I try to use the unicode described in the custom icons I uploaded, it's the same as unicode used with another standard icon

**To Reproduce**
Create custom icons, reference their unicode value and see if the right icon shows up. In my screenshots you can clearly see e003 corresponds to the Comet icon, despite being the same value as the custom icons. My scenario for usage is using pseudo classes.

**Expected behavior**
It would show my custom icon. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2962327/105416252-dc91c800-5c07-11eb-920d-22ab5758f25f.png)
![image](https://user-images.githubusercontent.com/2962327/105416327-f6330f80-5c07-11eb-8d8e-d93d9fa9d365.png)
![image](https://user-images.githubusercontent.com/2962327/105416351-fe8b4a80-5c07-11eb-9c23-3b0f24c8be83.png)

**Version and implementation**
Version: Latest
Browser and version: Firefox 85 Developer Edition

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@robmadole could you please take a look?

**Comment by robmadole** [comment]
@jbwharris are you using pseudo-elements with SVG + JS?

**Comment by jbwharris** [comment]
Yes, after pseudo class and the SVG kit

**Comment by jbwharris** [comment]
I just switched to using the web font and can confirm I'm seeing the same issue there too.
![image](https://user-images.githubusercontent.com/2962327/105731250-38f13200-5efd-11eb-8761-76b639684a7a.png)

**Comment by robmadole** [comment]
I think we need much better documentation on this @jbwharris ! Glad it's not a bug that is blocking you. Thanks for reporting it.

**Comment by jbwharris** [comment]
Agreed, you can definitely tell the documentation is still for FA5, while addressing some FA6 specific details.
