### ISSUE TITLE
x

### ISSUE THREAD

**Issue by Agassy** [FortAwesome/Font-Awesome#17581]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is kinda legit, but please keep in mind that you can achieve that icon with the power transforms, masking, and layering features of the SVG Framework.

Also, we support multiple currencies and multiple devices throughout 4 different styles, so this could easily lead up to 9 (currencies) * 4 (mobiles) * 4 (styles) = 144 icons

Demo: https://jsfiddle.net/tagliala/L17f528g/486/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
