### ISSUE TITLE
@defaultsecurity yes it's perfect so the top round button for turning on, and the top 4 square objects for other option eg. activity status while turning on.,😊

### ISSUE THREAD

**Issue by polinar68** [FortAwesome/Font-Awesome#17596]
@defaultsecurity yes it's perfect so the top round button for turning on, and the top 4 square objects for other option eg. activity status while turning on.,😊
the second round button for turning off, and each square objects working to secure each account connected on it, it looks like any account connected to 'SWITCH' symbol having a STRONG FOUR WALLS to protect it by themselves...😠

_Originally posted by @polinar68 in https://github.com/FortAwesome/Font-Awesome/issues/17561#issuecomment-770325614_

**Comment by tagliala** [comment]
Hi, I'm going to close this. Any chance that it has been opened by mistake?
