### ISSUE TITLE
Icon request: outsourced company

### ISSUE THREAD

**Issue by Situatedtech** [FortAwesome/Font-Awesome#17593]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
The (single) icon will be used to inform that someone works for an outsorced company, that is for a company hired to do some tasks in another company (i.e. in the main company) . So, imagine that everyone has a label with their name on the helmet, but those who are not emplyees from the main company, but from an outsourced company, would have this icon just after their name. In short, the icon would be used for all outsorced companies instead of using different logos from each of the outsourced companies. 

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Could you please provide a better title and description of this icon and maybe find an example?

The request is quite abstract and the description does not help

**Comment by Situatedtech** [comment]
Hi! 

Ok... let's try it. The icon should represent that the person is **not** from the company that the person is currently working for. That is, the person is from an autsourced company, a company that was hired by the main company to do some work for a longer period of time (such as providing security, clean the offices, etc). 

I am trying to come up with something you have that is close to it, but I still think it is just close. See attached. 

Thanks a lot. 
![Icone Terceiro 3 - Address CArd](https://user-images.githubusercontent.com/78240443/106353111-f9449480-62c6-11eb-9e6b-5c0cd5cc3839.PNG)
![Icone Terceiro 5 - Cogs](https://user-images.githubusercontent.com/78240443/106353116-03ff2980-62c7-11eb-8be2-d440c11a8a97.PNG)

**Comment by tagliala** [comment]
Ok, thanks, so you are requesting something like this? 

https://jsfiddle.net/tagliala/L17f528g/488/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Situatedtech** [comment]
Hi Tagliala!

Thanks a lot. I have to think about because the two justaposed looks like the person is hired to deal with mechanics...

Cheers,
            Rodrigo.

**Comment by tagliala** [comment]
> I have to think about because the two justaposed looks like the person is hired to deal with mechanics...

what about https://jsfiddle.net/tagliala/L17f528g/492/ ?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
