### ISSUE TITLE
Icon Request: icon-spy (icon spook)

### ISSUE THREAD

**Issue by ahsteele** [FortAwesome/Font-Awesome#1759]
It would be useful to have an incognito icon similar to what is provided during incognito mode of Chrome. Specifically the guy in the upper right hand corner of the browser: ![Chrome UI in incognito mode](http://upload.wikimedia.org/wikipedia/en/b/b1/Google_Chrome_Incognito.png)

**Comment by BarisJKaraali** [comment]
+1

**Comment by tagliala** [comment]
added in 4.3.0

**Comment by G-Driver** [comment]
tnx @davegandy

**Comment by gauthier-delacroix** [comment]
@tagliala If you're talking about `user-secret`, I tried it but in 16px nobody sees what this icon is...a mask icon like #1562 would be clearer IMHO.
