### ISSUE TITLE
fa-plus-square-o

### ISSUE THREAD

**Issue by ophthal** [FortAwesome/Font-Awesome#17598]
fa-plus-square-o was in 4 and is now missing...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In FA5 we changed a lot of names to accomodate the new `Solid` and `Regular` styles

FA4's `fa fa-plus-square-o` is now accessible with `far fa-plus-square`

Hope it helps

Closing here

Docs: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
