### ISSUE TITLE
Icon request: icon-book-open

### ISSUE THREAD

**Issue by dpwolf** [FortAwesome/Font-Awesome#176]
It would be great to have an icon for an open book.

A simplified version of this:

![Open book example](http://thumb15.shutterstock.com/photos/thumb_large/617908/617908,1296121386,5.jpg)

**Comment by DanLew** [comment]
I cant believe this wasn't one of the first icons added +1

**Comment by acoulton** [comment]
+1

**Comment by gbozee** [comment]
+1

**Comment by TLJens** [comment]
+1

**Comment by kymetro9999** [comment]
Yes please! an open book is the traditional symbol for a library. Much needed! 

Two good options:

![book_icon](https://cloud.githubusercontent.com/assets/11318280/6489478/c30a76f6-c26c-11e4-8d5f-bf78b444994b.png)

and 

![book_icon2](https://cloud.githubusercontent.com/assets/11318280/6489486/ce556d9a-c26c-11e4-9e01-352344566c06.png)

**Comment by jrochkind** [comment]
Even though the [contribution guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) suggest filing an issue for new icons and +1'ing it for a "vote"... I'm not sure anyone is actually paying attention to these?  There's lots of +1's here, but I don't think the maintainers are interested in adding new icons, or something?

**Comment by buzzcloudau** [comment]
+1

**Comment by tomarrell** [comment]
I feel like this thread is making no progress towards getting the icon added to a final release. Does anyone have any idea as to how we could ensure the creator got his eyes on this?

**Comment by tagliala** [comment]
@jrochkind @tomarrell please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

This request is not one of the most popular but I ensure that +1s count

**Comment by stephendwolff** [comment]
Thanks @tagliala, that's v. helpful. I was wondering how i could go about do just that the other day!

**Comment by drouillard** [comment]
+1

**Comment by tannerm** [comment]
+1

**Comment by nathancharles** [comment]
+1

**Comment by jbyers** [comment]
+1

**Comment by Pseudo-Nym** [comment]
+2

**Comment by tildemark** [comment]
amazing leanpub is added, how many +1 do we need to get this added?

**Comment by Hippo313** [comment]
+1

**Comment by ruisoftware** [comment]
+1

**Comment by melissaburpo** [comment]
+1

**Comment by mkhan3189** [comment]
+1

**Comment by tuxy** [comment]
+1 for fa-open-book, here is another example > https://github.com/FortAwesome/Font-Awesome/issues/7012

**Comment by roddavis9** [comment]
+1

**Comment by Miralo** [comment]
+1

**Comment by mdzhang** [comment]
+1

**Comment by DUznanski** [comment]
+1

**Comment by QueenMerla** [comment]
+ 1

**Comment by aethior** [comment]
+1

**Comment by angiejones** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by jouanc** [comment]
+1

**Comment by AndreLGava** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by DanielRomanMartinez** [comment]
+1

**Comment by Doch70** [comment]
+1

**Comment by tomarrell** [comment]
I've got a feeling this thread has been simply left to die.

**Comment by DanielRomanMartinez** [comment]
Sadly yes, this thread is going to die, if is not dead.

**Comment by bistory** [comment]
+1

**Comment by ionutt** [comment]
+1

**Comment by jasonmorehead** [comment]
+1

**Comment by stephen-thornhill-ms** [comment]
+1

**Comment by TheGreenTea** [comment]
+1

**Comment by DustinIsTheName** [comment]
+1

**Comment by dipankar08** [comment]
+1

**Comment by SoerenHenning** [comment]
+1

**Comment by msnyderdev** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by price84** [comment]
+1

**Comment by 0x0c** [comment]
+1

**Comment by thatbignerdguy** [comment]
+1

**Comment by bsmith008** [comment]
+1

**Comment by pepalan** [comment]
+1

**Comment by danielignatius** [comment]
+1

**Comment by pytlus93** [comment]
+1

**Comment by maffpool** [comment]
+1

**Comment by NickOgbourne** [comment]
Looks like a long standing request that i would like to support.  I am looking for an open version of the existing book icon fa-book.

Thanks for a great tool.

**Comment by robertosanval** [comment]
+1

**Comment by alexkafer** [comment]
+1

**Comment by Flav900** [comment]
+1

**Comment by StellaLuc** [comment]
+1 - Does anyone know how many requests they need before they add it?

**Comment by NishantUpadhyay-BTC** [comment]
+1

**Comment by arLevi** [comment]
From my experience it's not depended on "how many requests" or "+1" ... it's simply up to them to decide what they want to design right now :)

**Comment by aramboyajyan** [comment]
+1

**Comment by esl-douglas** [comment]
+1

**Comment by Crissov** [comment]
Unicode emoji: #222

- [📖 U+1F4D6](http://emojipedia.org/open-book/)

**Comment by shaedrich** [comment]
Or something like github uses: data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' aria-hidden='true' height='16' version='1.1' width='16'><path fill-rule='evenodd' d='M3 5h4v1H3V5zm0 3h4V7H3v1zm0 2h4V9H3v1zm11-5h-4v1h4V5zm0 2h-4v1h4V7zm0 2h-4v1h4V9zm2-6v9c0 .55-.45 1-1 1H9.5l-1 1-1-1H2c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h5.5l1 1 1-1H15c.55 0 1 .45 1 1zm-8 .5L7.5 3H2v9h6V3.5zm7-.5H9.5l-.5.5V12h6V3z'/></svg>

```
<svg aria-hidden="true" class="octicon octicon-book" height="16" version="1.1" viewBox="0 0 16 16" width="16">
    <path fill-rule="evenodd" d="M3 5h4v1H3V5zm0 3h4V7H3v1zm0 2h4V9H3v1zm11-5h-4v1h4V5zm0 2h-4v1h4V7zm0 2h-4v1h4V9zm2-6v9c0 .55-.45 1-1 1H9.5l-1 1-1-1H2c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h5.5l1 1 1-1H15c.55 0 1 .45 1 1zm-8 .5L7.5 3H2v9h6V3.5zm7-.5H9.5l-.5.5V12h6V3z"></path>
</svg>
```

+1

**Comment by PeteMichaud** [comment]
+1

**Comment by alexrada** [comment]
+1

**Comment by TedHopp** [comment]
+1

**Comment by AlliMartel** [comment]
+1

**Comment by SilverHazeLazers** [comment]
+1

**Comment by didikbowo** [comment]
+1

**Comment by srsteinberg** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks! Happy to announce that this will be included in our 5.1 release!

**Comment by NickOgbourne** [comment]
Thanks Raphael


--------------------------------------------------------------------------------
Nick
Skype nick.ogbourne
phone+61 (0)2 6586 1627
mobile +61 (0)418 139 156
--------------------------------------------------------------------------------

------ Original Message ------

**Comment by sensibleworld** [comment]
Sorry for keeping our book closed for so long: https://fontawesome.com/icons?d=gallery&q=book-open
