### ISSUE TITLE
Icon Request: fa- tiktok

### ISSUE THREAD

**Issue by Nollsie** [FortAwesome/Font-Awesome#17609]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Instagram icon is already available:
- https://fontawesome.com/icons/tiktok?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
