### ISSUE TITLE
Icon request: stairs/steps

### ISSUE THREAD

**Issue by RebeccaGrotte** [FortAwesome/Font-Awesome#17607]
Hello, 

I could really use the icon of "steps/stairs", like this one: 
![image](https://user-images.githubusercontent.com/78549966/106910066-28ad3400-6701-11eb-82ba-c4e7170a352b.png)

I'm working for a Cave and Wildlife Park and need this icon to explain on the website the number of stairs that each visit has. In this way, elderly people or invalid people, or also people coming to visit us with dogs, can choose the visit with the least steps. 

It would be probably great to also have an icon of "no stairs", so a barred stairs icon. But I'll probably not need it myself.

Thank you so much in advance!
Best regards,
Rebecca

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as `fa-stairs` in Font Awesome 6.0.0.alpha2 (Pro)

Ref:  #5881
