### ISSUE TITLE
icon request: files

### ISSUE THREAD

**Issue by edippity** [FortAwesome/Font-Awesome#17605]
**What can it be used for?**
When you have a collection of file objects

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [■] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [■] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [■] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [■
![Files](https://user-images.githubusercontent.com/57457850/106810953-a60e7100-663b-11eb-8343-0f41ae01a464.png)
] I have included at least one example image if it could be helpful (optional)
- [■ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does [fa-copy](https://fontawesome.com/icons/copy?style=solid) fit your use case?

**Comment by edippity** [comment]
It could but I think it is well known as a copy icon so an icon with another document in the layer would be ideal

**Comment by sensibleworld** [comment]
We've got a new `files` icon coming to the next v6 alpha.

**Comment by sensibleworld** [comment]
<img width="642" alt="Screen Shot 2021-03-30 at 12 08 36 PM" src="https://user-images.githubusercontent.com/529604/113020507-a9f8d400-9150-11eb-8193-079353c3341b.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
