### ISSUE TITLE
Icon request: user-drowning

### ISSUE THREAD

**Issue by robkerry** [FortAwesome/Font-Awesome#17602]
**What can it be used for?**
For swimming/sports, medical/lifesaving and if a user/staff member needs help

**Example image (optional)**
https://thenounproject.com/search/?q=drowning&i=2696249

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aethior** [comment]
Hi @robkerry,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/person-drowning

Regards.

cc/ @tagliala
