### ISSUE TITLE
Some icons appear distorted after migrating from FontAwesome 4 to FontAwesome 5

### ISSUE THREAD

**Issue by CaMer0n** [FortAwesome/Font-Awesome#17604]
## Describe the bug
Recently switched out FA4 for FA5 (using shims) . 
Markup is the same, but some icons appear distorted. (lacking contrast/clarity) 

## To Reproduce
Compare in browser:  `<i class="fa fa-th"></i>` using FA4 and FA5. 

## Expected behavior
Retain the quality observed in FA4. 

## Screenshots
FA4:  
![image](https://user-images.githubusercontent.com/2825679/106761279-83536c80-65e9-11eb-948e-ef61822acdff.png)

Computed CSS for the` i `tag of this item: 

```
box-sizing: border-box;
color: rgb(255, 255, 255);
cursor: pointer;
display: inline-block;
font-family: FontAwesome;
font-feature-settings: normal;
font-kerning: auto;
font-language-override: normal;
font-size: 14px;
font-size-adjust: none;
font-stretch: 100%;
font-style: normal;
font-variant: normal;
font-variant-alternates: normal;
font-variant-caps: normal;
font-variant-east-asian: normal;
font-variant-ligatures: normal;
font-variant-numeric: normal;
font-variant-position: normal;
font-weight: 400;
line-height: 14px;
text-align: center;
text-rendering: auto;
text-shadow: rgba(0, 0, 0, 0.3) 1px 1px 1px;
white-space: nowrap;
```

FA5:
![image](https://user-images.githubusercontent.com/2825679/106762595-d4179500-65ea-11eb-9ef3-ccbbf026f799.png)

Computed CSS for the` i `tag of this item: 

```
box-sizing: border-box;
color: rgb(255, 255, 255);
cursor: pointer;
display: inline-block;
font-family: "Font Awesome 5 Free";
font-size: 14px;
font-style: normal;
font-variant: normal;
font-variant-alternates: normal;
font-variant-caps: normal;
font-variant-east-asian: normal;
font-variant-ligatures: normal;
font-variant-numeric: normal;
font-variant-position: normal;
font-weight: 900;
line-height: 14px;
text-align: center;
text-rendering: auto;
text-shadow: rgba(0, 0, 0, 0.3) 1px 1px 1px;
white-space: nowrap;
```

## Version and implementation
Version: **5.15.2**
Browser and version:  **Firefox 85.0**

- [X] Web Fonts with CSS

## Bug report checklist
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Font Awesome 5 uses a base font size of 16px

I can see that your computed font-size is `14px` even in FA5, so pixel perfection is compromised.

Please set icon size to 16px and multiples

Hope it helps

Closing here, but feel free to comment

**Comment by CaMer0n** [comment]
Thank you @tagliala ! Good to know! :-)
