### ISSUE TITLE
Add Class Documentations for the Font-Awesome

### ISSUE THREAD

**Issue by lmwenda** [FortAwesome/Font-Awesome#17606]
We need to know all of the Image Classes in like a Documentation

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not sure I've got this request, but if you need a list of all the icons available we have the cheatsheet: https://fontawesome.com/cheatsheet

If you need that list for development purposes, you may want to take a look at the [metadata folder](https://github.com/FortAwesome/Font-Awesome/tree/master/metadata)

Does it help?

**Comment by lmwenda** [comment]
Thanks!
________________________________
