### ISSUE TITLE
Icon Request: fa-fruit 

### ISSUE THREAD

**Issue by regiomag** [FortAwesome/Font-Awesome#17618]
Hi,

To be used on food website, it would be nice to have a fa-fruit representing for instance an apple but not the mac one as we do have with fa-apple ;)

<img width="136" alt="Screenshot 2021-02-09 at 09 27 40" src="https://user-images.githubusercontent.com/3803152/107336170-16dcdf80-6ab9-11eb-9eec-12efe4537be9.png">

In fact, it would be amazing to also have 
fa-vegetable 
fa-bread 
fa-egg

<img width="252" alt="Screenshot 2021-02-09 at 09 30 21" src="https://user-images.githubusercontent.com/3803152/107336603-95d21800-6ab9-11eb-9da3-6cb4ba2e3b7c.png">
<img width="504" alt="Screenshot 2021-02-09 at 09 31 03" src="https://user-images.githubusercontent.com/3803152/107336607-97034500-6ab9-11eb-829c-3bb88c5f7a6e.png">
<img width="177" alt="Screenshot 2021-02-09 at 09 31 18" src="https://user-images.githubusercontent.com/3803152/107336609-979bdb80-6ab9-11eb-82d0-39726a754231.png">

All these pics are just printscreen found on google, I can provide you with home made images if you wish :) 

Thank you for your amazing app and have a great day

Michael

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Apple (the fruit) icon is already available:
- https://fontawesome.com/icons/apple-alt?style=solid

And we also have carrot: https://fontawesome.com/icons/carrot?style=solid and [some other vegetables](https://fontawesome.com/icons?c=fruit-vegetable)

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
