### ISSUE TITLE
Please rename fa-suse to fa-opensuse

### ISSUE THREAD

**Issue by dcermak** [FortAwesome/Font-Awesome#17619]
**Describe the bug**

The icon fa-suse has a misleading name: it indicates that this is the SUSE logo, but SUSE did a rebrand and no longer uses this logo, openSUSE still uses it though.

**To Reproduce**
Search for suse on fontawesome.com and get presented with the opensuse logo instead of the suse logo.

**Expected behavior**

Either provide the suse logo or rename the current suse logo to opensuse. 

**Screenshots**
fontawesome.com: 
![image](https://user-images.githubusercontent.com/45594031/107337079-2f99c500-6aba-11eb-9e44-23481ec6cc8d.png)

brand.suse.com:
![image](https://user-images.githubusercontent.com/45594031/107337205-548e3800-6aba-11eb-9d7f-a52ad2d12341.png)

**Version and implementation**
Version: 5.15.2 and older
Browser and version: irrelevant

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I've also noticed that:
- the version we are using is slightly different from the [official openSUSE one](https://en.opensuse.org/openSUSE:Artwork_brand)
- If this request was originally intended for SUSE rather than openSUSE, we should update the logo and keep the name

Let's assign @sensibleworld

**Comment by dcermak** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community and thanks for reporting this.
> 
> I've also noticed that:
> 
>     * the version we are using is slightly different from the [official openSUSE one](https://en.opensuse.org/openSUSE:Artwork_brand)

You can find the svg here: https://raw.githubusercontent.com/openSUSE/artwork/master/logos/official/logo-color.svg

Unfortunately the logo itself is all right reserved and not using the same license as openSUSE/artwork, so not sure if that is a blocker for inclusion?

> 
>     * If this request was originally intended for SUSE rather than openSUSE, we should update the logo and keep the name

I would suggest to have both present: update SUSE to be the current brand logo and openSUSE to use the existing one.

**Comment by tagliala** [comment]
> I would suggest to have both present: update SUSE to be the current brand logo and openSUSE to use the existing one.

This is a good option, but I think that a request for SUSE should follow the same process as other requests.

In our [Brand Leaderboard](https://fontawesome.com/community/leaderboard/brands) there is debian at the`#35`th place: adding SUSE before Debian would not be fair.

I would fix this name to `opensuse`. Then we can open a new request for `suse`, where we can wait for community feedback and act accordingly

@sensibleworld any thoughts?

**Comment by sensibleworld** [comment]
My preference would be to update this current logo with the new SUSE symbol, as that seems the most straightforward. If I recall, this logo was added to reference SUSE, not openSUSE? In which case, a new request for the latter makes sense.

That said... I don't know the ins and outs of the relationship between SUSE and openSUSE. Is there any issue with the two marks being so similar? Seems like the copyright of one would negate the other?

**Comment by dcermak** [comment]
Jory Raphael <notifications@github.com> writes:

> My preference would be to update this current logo with the new SUSE symbol, as that seems the most straightforward. If I recall, this logo was added to reference SUSE, not openSUSE? In which case, a new request for the latter makes sense.
>
> That said... I don't know the ins and outs of the relationship between SUSE and openSUSE. Is there any issue with the two marks being so similar? Seems like the copyright of one would negate the other?

As far as I know (but I am not 100% certain) the logos used to be the
same, but SUSE did a rebrand last year whereas openSUSE kept the old
logo. The relationship w.r.t the logos is relatively simple: SUSE owns
all the trademarks of the openSUSE project, because openSUSE is not a
legal entity. Concerning the legal implications I can only direct you
towards: https://brand.suse.com/

**Comment by sensibleworld** [comment]
The Suse logo now matches their official logo: https://fontawesome.com/icons/suse?f=brands&s=solid

And we've added a new openSUSE logo that matches: https://fontawesome.com/icons/opensuse?f=brands&s=solid

**Comment by dcermak** [comment]
Thank you, this is perfect!

**Comment by hellcp** [comment]
> As far as I know (but I am not 100% certain) the logos used to be the
> same, but SUSE did a rebrand last year whereas openSUSE kept the old
> logo. The relationship w.r.t the logos is relatively simple: SUSE owns
> all the trademarks of the openSUSE project, because openSUSE is not a
> legal entity. Concerning the legal implications I can only direct you
> towards: https://brand.suse.com/

I mean, this is partially true, the logos were in fact the same, but the time is wrong. SUSE changed the logo to a different one in 2011, and so the logo that was `.fa-suse` and is now `.fa-opensuse` was never an openSUSE logo.

Here's a grafic I made in 2020 after a bit of research about it
![3600px-SUSE_Logo_evolution.svg.png](https://github.com/FortAwesome/Font-Awesome/assets/30577011/dc0a6c47-d2d8-466f-b407-9b142b19c03d)

And as for trademark, both logos have always been a SUSE owned trademark, though openSUSE trademark is separate from the SUSE one as well on the account of them being different.
