### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by AnSenpai1** [FortAwesome/Font-Awesome#17616]
Hello,

It gonna be really nice if u are adding an Discord Icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Instagram icon is already available:
- https://fontawesome.com/icons/discord?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
