### ISSUE TITLE
icon-forum

### ISSUE THREAD

**Issue by weifeng-l** [FortAwesome/Font-Awesome#17625]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by weifeng-l** [comment]
hoping you can create an icon for forum pages

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide an example, how you would represent a `forum`?

**Comment by weifeng-l** [comment]
![Forum](https://user-images.githubusercontent.com/73148013/108379815-3e624380-7241-11eb-8072-d269a09a353a.png)

**Comment by tagliala** [comment]
Hi, so you are looking for an open book

We already have this: https://fontawesome.com/icons/book-open?style=solid
