### ISSUE TITLE
Icon request: icon-paddle

### ISSUE THREAD

**Issue by Compu08** [FortAwesome/Font-Awesome#17624]
**What can it be used for?**
This sport is a played around all the world and very popular. Can be used for web or mobile apps of sports.

**Example image (optional)**
https://thumbs.dreamstime.com/z/paleta-tenis-20101847.jpg

**Icon request checklist**
- [✔] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [✔] I have included at least one example image if it could be helpful (optional)
- [✔] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by oriadam** [comment]
there is a very similar icon for racket https://fontawesome.com/v5.15/icons/racquet

**Comment by walva** [comment]
**What can it be used for?**
Hello !

I'm the owner of a sport venue directory and I'm a happy user of Font Awesome for years.
It miss a few sports and one the fatest growing sports is missing: padel. It's a racquet sport, not to be confused with (stand-up) paddle.

It's quite close to pickleball. According to the growth rate, this sport will surpass pickleball, or even tennis in the coming years. 

Pickleball: 36.5 million
Padel: 25 million

https://www.padel.fyi/blog/padel-statistics

**Example image (optional)**

![image](https://github.com/FortAwesome/Font-Awesome/assets/3897363/b80708cd-cb36-4078-a3c7-e9187e0fde44)
![image](https://github.com/FortAwesome/Font-Awesome/assets/3897363/e104f58b-f594-4edf-8a0d-4f695e9d5800)

@oriadam there is also an icon for [pickleball](pickleball), [badminton](https://fontawesome.com/icons/badminton?f=classic&s=solid), [table tennis](
https://fontawesome.com/icons/table-tennis-paddle-ball?f=classic&s=duotone)... it would be nice to have a proper one for padel 🙏

**Comment by pepito2k** [comment]
I'd love to have an icon for Padel, I need to differentiate it from tennis on my app, so using the current icons is not an option.

**Comment by ivanvarela** [comment]
I need them for Padel and Pickleball

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
