### ISSUE TITLE
CDN 404 Error

### ISSUE THREAD

**Issue by VinceSanityyy** [FortAwesome/Font-Awesome#17626]
**Describe the bug**
I got an error in the console saying ` GET https://kit.fontawesome.com/a076d05399.js net::ERR_FAILED`

**To Reproduce**
Im using laravel and I put in script tag like a CDN `<script src="https://kit.fontawesome.com/a076d05399.js"></script>`

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Icons will show

**Version and implementation**
Version: N/A
Browser and version: N/A

- [ x ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [  x ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There has been a change on our side to prevent misuse of a w3schools kit, please take a look at #17622
