### ISSUE TITLE
Collapse icons & expand icons

### ISSUE THREAD

**Issue by jslegers** [FortAwesome/Font-Awesome#1763]
I was wondering if you would consider the following name changes in your icon set :

```
* icon-collapse ----> icon-expand-down
* icon-collapse-top ----> icon-expand-up
* icon-expand ----> icon-expand-right
* NEW ICON ----> icon-expand-left

* icon-expand-alt ----> icon-expand-plus
* icon-collapse-alt ----> icon-expand-minus
```

These naming conventions are more consistent.

Also, they have the additional advantage of being able to use an alias 'icon-collapse' as a reference to two such icons and use a 'collapsed' modified to pick select which of both icons to use. In fact, you would be able to use the 'icon-collapse' with the 'collapsed' modifier on any two icons in the icon set.

I've been using the 'icon-caret-down' and 'icon-caret-right' for collapsibles in Cascade Framework ( http://www.cascade-framework.com/ ) using the technique described above. The suggested name change would also allow me to continue using Font Awesome without any changes to the naming conventions of either project.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
