### ISSUE TITLE
Watersports

### ISSUE THREAD

**Issue by GavOutdoors** [FortAwesome/Font-Awesome#17632]
**What can it be used for?**
There are not many icons for watersports. 
E.g. kayaking, canoe, waterski, surfing, paddle boarding, jetski, scuba, snorkelling, windsurfing, etc.
These are useful for maps, listing details of activities, etc. 

**Example image (optional)**
There are plenty of examples over here https://mapicons.mapsmarker.com/?s=canoe

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, icon sets are not allowed by our contributing guidelines.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
