### ISSUE TITLE
Icon request: calendar-users

### ISSUE THREAD

**Issue by HugoSanchezGarcia** [FortAwesome/Font-Awesome#17639]
**What can it be used for?**
Appointments for group activities, so it can be different from solo appointments

**Example image (optional)**
A mix of 
https://fontawesome.com/icons/calendar?style=light 
and
https://fontawesome.com/icons/users?style=light

**Comment by sensibleworld** [comment]
<img width="1072" alt="Screen Shot 2021-03-04 at 2 42 08 PM" src="https://user-images.githubusercontent.com/529604/110020621-ce02fa00-7cf7-11eb-9633-74db7bed3e52.png">

We have a few new calendars coming to v6! Does the "calendars" icon shown here work for you?

**Comment by HugoSanchezGarcia** [comment]
Sorry for not answering. Didn't get notified.
I think those don't solve the same problem. It needs to symbolize an appointment for a **group**, for example, you can have a gym and you want to know when a grupal gym class takes place or if it's an individual session. So you can know directly with the icon if it's something grupal or individual without looking into details of the appointment saving some time doing so.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/521/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
We have a new "calendar-users" icon in 6.4.0: https://fontawesome.com/icons/calendar-users?f=classic&s=duotone&sc=%231E3050
