### ISSUE TITLE
SVGs do not match the Icon Font / Cheatsheet

### ISSUE THREAD

**Issue by hulmerous** [FortAwesome/Font-Awesome#17642]
![Screen Shot 2021-02-17 at 10 06 05 AM](https://user-images.githubusercontent.com/38261221/108248077-49658880-7108-11eb-9020-9234118a5a7d.png)
Hi, not sure if this is the right place but I can't get in touch with tech support.

I downloaded the folder of SVGs from the FontAwesome website bu they are completely different from what is seen on the website (the Cheatsheet for font copy-paste). Some icons are missing completely. Some are named something else.

I am a FontAwesome Pro user.

Example: Looking for a swimming pool icon. On the cheatsheet they have one called:
swimming-pool 
Or 
swimmer 

In the folder of SVGs they only have: 
man-swimming

And it's NOT the same icon as the "swimmer" on the cheatsheet. There are slight differences (true for all the other icons too).

I designed using the font and am now being asked by devs to provide SVGs instead. So I really need them to match, and am trying to do this quickly. Sadly because the names are different, I can't just "search" for each icon and put them in a folder. Anyone else have this problem? Anyone here actually from FontAwesome and can address?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You download the alpha 2 version of Font Awesome 6, which is in private alpha

The version on the website is the latest stable. If you need icons from the website, please download Font Awesome 5

Hope it helps

Closing here but feel free to comment

**Comment by hulmerous** [comment]
Thank you SO MUCH! I've been going crazy trying to figure this out. I appreciate it!

**Comment by tagliala** [comment]
Welcome, glad you solved
