### ISSUE TITLE
Getting ERR ABORTED 403

### ISSUE THREAD

**Issue by Rasputin2** [FortAwesome/Font-Awesome#17645]
**Describe the bug**
I have been using font-awesome for about a year and a half on my site.  All of a sudden, about a week ago, all my fonts disappeared.  If you look in the console, this is the error I am getting:

GET https://kit.fontawesome.com/a076d05399.js net::ERR_ABORTED 403

**To Reproduce**
just go to www.mioconsigliere.com and look at the developer tools

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?
I'd just like to see the icons working.

**Screenshots**

![image](https://user-images.githubusercontent.com/43117960/108274990-3fa94880-713b-11eb-9e3a-e6ac4c6d06c2.png)

**Version and implementation**
Version: 
Browser and version: 
I have used Microsoft Edge, and Google Chrome and Firefox. 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X ] I have filled out as much of the above information as I can
- [X ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

NOte that there was a similar issue noted about a year ago with the same problem.  There was a statement that it was just a 'caching' issue that got resolved.   But I cleared my cache and I am still having this issue.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue is pinned on the top: #17622, you basically need to create your own kit because that is the one from w3schools

Hope it helps

Closing here
