### ISSUE TITLE
Icon Request: fa-Brush

### ISSUE THREAD

**Issue by sacha4769** [FortAwesome/Font-Awesome#17647]
Icon Request: fa-Brush
Icon Request: fa-Comb

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have a [brush](https://fontawesome.com/icons/brush?style=solid), but I think you are requesting a hair brush

Please upvote #15867
Comb: please upvote #15868

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here

**Comment by sacha4769** [comment]
Wow you guys are awesome! 

 

Thank you so much!

**Comment by sacha4769** [comment]
Hi there, 

When will these be available to use?

**Comment by tagliala** [comment]
> When will these be available to use?

Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
