### ISSUE TITLE
Icon request: icon-tally

### ISSUE THREAD

**Issue by gabejbrenner** [FortAwesome/Font-Awesome#1764]
I would love to see an icon-tally introduced. I'm imagining that it would basically look something like this:
http://goo.gl/YoPfkX

Why am I asking? I'm currently developing an app to manage a pay-per-task system, and the client wants to be able to tally the managees tasks. That aside, I've seen many online cases using a similar mark to what I want.

So long and thanks for all the icons

**Comment by m52go** [comment]
+1
