### ISSUE TITLE
Kit throwing 403 + potential information disclosure

### ISSUE THREAD

**Issue by trjconsulting** [FortAwesome/Font-Awesome#17651]
Redacted by @tagliala

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I've redacted your message and following up in a private repo.

I will let you know what we decide to do

**Comment by trjconsulting** [comment]
also our dev was positive they generated that kit ID on their own so i am wondering if there is a collision of IDs in addition to the info disclosure issue.  i was able to verify at least 1 other site was using the same ID

**Comment by tagliala** [comment]
> also our dev was positive they generated that kit ID on their own

So you should see it in your kits page at https://fontawesome.com/kits

**Comment by trjconsulting** [comment]
we generated a new one for now, but you can see startribune.com and risecannabis.com using the same ID and https://www.americanautoshipping.com/ and https://piqqit.store (and i assume most/all of the others that were showing up when i was hitting the URL)

**Comment by tagliala** [comment]
> (and i assume most/all of the others that were showing up when i was hitting the URL)

yes, because this is the code from w3schools and a lot of developers are using it, as per the pinned issue #17622

**Comment by trjconsulting** [comment]
Ahhh now it all makes sense.  Either way thanks for the quick replies we're good on our end!
