### ISSUE TITLE
Icon request: icon-open-door

### ISSUE THREAD

**Issue by SayantaniBhattacharjee** [FortAwesome/Font-Awesome#17657]
**What can it be used for?**
Hi! I am working on a project that is looking to use the solid icon as a marker to represent entrances/exits in buildings and corridors in a map.

**Example image (optional)**
Here are links to couple of examples:
![image](https://user-images.githubusercontent.com/24310321/108891423-b41d3500-75dc-11eb-8cc6-2cd9633d9b1f.png)
![image](https://user-images.githubusercontent.com/24310321/108891502-cac38c00-75dc-11eb-9e11-399ec40c978c.png)

Thanks a lot!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is already available: https://fontawesome.com/icons/door-open?style=solid

Closing here
