### ISSUE TITLE
Forklift, golf and mobility carts

### ISSUE THREAD

**Issue by fadstaewtbadsfgadftgh** [FortAwesome/Font-Awesome#17660]
Currently, it looks like there's very limited number of icons representing vehicles in the project. My suggestion would be to add more, starting from the one I have attached. The reason for including this particular icon is that it is really versatile because it may represent at least the following types of vehicles:

1. Forklifts
2. Golf carts
3. Mobility carts
4. Disability vehicles
5. Electric cars

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, icon sets are not allowed by our contributing guidelines.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services
