### ISSUE TITLE
Bootstrap logo (fa-bootstrap) is out of date

### ISSUE THREAD

**Issue by jonasbirkelof** [FortAwesome/Font-Awesome#17668]
Bootstrap have a new logotyp that they are using for their new version, Bootstrap 5.

Suggestion: rename the current Bootstrap logo to "fa-bootstrap-legacy" and create the new logo naming it "fa-bootatrap".

Old:
![bs-1](https://user-images.githubusercontent.com/61730892/109184941-c4c1dc80-778f-11eb-889c-0e8fd1c012e2.jpg)

New:
![bs-2](https://user-images.githubusercontent.com/61730892/109184946-c68ba000-778f-11eb-9d6a-b466452f00a1.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The new logo has been already added to FA6 private alpha 2 and will be released with FA6

>  rename the current Bootstrap logo to "fa-bootstrap-legacy" 

The old logo will be removed

Ref #17436
