### ISSUE TITLE
power transforms don't work correctly on non-512px svg framework icons

### ISSUE THREAD

**Issue by dsmmcken** [FortAwesome/Font-Awesome#17671]
**Describe the bug**
Following the steps to create a custom icon via the [svg framework](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#svg-framework), and applying a data transform such as `grow-4` causes the icon given in the example to scale incorrectly. If the icon size is smaller than 512 it transforms up, if it's larger it will transform down rather than from center.

**To Reproduce**
Test case: https://jsfiddle.net/guxtpj4y/
First two icons are 16 and 2048 for viewbox size, next one is exactly 512. Regular icon for behavior reference.

**Expected behavior**
Icon power transforms work still work. I believe this is because in the transformForSvg function, width is correct as width/2, but height is hardcoded as 256 (aka 512/2). I am not sure why this wouldn't also use icon height instead of hardcode value.

```
function transformForSvg(_ref) {
  var transform = _ref.transform,
      containerWidth = _ref.containerWidth,
      iconWidth = _ref.iconWidth;
  var outer = {
    transform: "translate(".concat(containerWidth / 2, " 256)")
  };
...
  var path = {
    transform: "translate(".concat(iconWidth / 2 * -1, " -256)")
  };
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1576283/109211801-b9b18100-777c-11eb-9322-ca7748d3683a.png)

**Version and implementation**
Version: 5.8
Browser and version: Chrome

- [X] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this thorough report.

> I am not sure why this wouldn't also use icon height instead of hardcode value.

I don't know if there is a reason behind the fixed height, except that all icons have the same height in FA while width is variable.

The code hasn't change from its initial commit

Let's ask @robmadole

**Comment by robmadole** [comment]
Thank you @dsmmcken for this.

Yep, we do this because it's a hard constraint that icons be exactly 512 high. We probably will not change this in the near term but instead provide tools like our Kits icon upload that perform the work to get a non-conformant SVG to be conformant.

So I'm going to tag this one as won't fix as it's not something we are currently interested in supporting.
