### ISSUE TITLE
Giving 403 Error intermittently 

### ISSUE THREAD

**Issue by MaksadAnnamuradov** [FortAwesome/Font-Awesome#17675]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
I am using font-awesome icons for my personal portfolio here: maksadannamuradov.com. The problem that I am having is sometimes the icons that I have embedded are displaying and sometimes they are not. For example, when I just checked my website yesterday, all the icons I embedded from font-awesome were displaying, but today it is not showing anything. You can refer to the picture I added. But when I open the network on Chrome, here is the error I am getting:

Request URL: https://kit.fontawesome.com/a076d05399.js
Request Method: GET
Status Code: 403 
Remote Address: 104.18.22.52:443
Referrer Policy: strict-origin-when-cross-origin

When I checked when the icons were showing, it did not give this error. I am not sure what the problem is but I would really like to find out if it is error on font-awesome server code, or something is wrong on my own code. 
![Screenshot 2021-02-28 122721](https://user-images.githubusercontent.com/46725876/109430947-100f0180-79c1-11eb-8ca4-32b006066b95.png)

**To Reproduce**
https://maksadannamuradov.com

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
It should display the embedded icons

**Screenshots**
I have added the screenshot of the icon not displaying right

**Version and implementation**
Version: 
Browser and version: I have tried accessing the website through Firefox, Chrome, MS Edge, Safari and all are not displaying the icons right. 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at the pinned issue #17622

Closing here

**Comment by MaksadAnnamuradov** [comment]
Thanks I was able to fix that error!

**Comment by tagliala** [comment]
Welcome, glad you solved
