### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by miih23** [FortAwesome/Font-Awesome#17670]
Bom, o site de vocês estão com diversos problemas, as amostras do icones não carregam, alguns botões não funcionam.
E também o site está apenas com os textos, não está com interface nenhuma.
Espero que arrumem em breve, tá *impossivel* usar o fontawesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Bom, o site de vocês estão com diversos problemas, as amostras do icones não carregam, alguns botões não funcionam.
> E também o site está apenas com os textos, não está com interface nenhuma.
> Espero que arrumem em breve, tá _impossivel_ usar o fontawesome.

As per Google Translate:

> Well, your site has a lot of problems, the samples of the icons don't load, some buttons don't work.
> Also, the site is only with texts, it has no interface.
> I hope you fix it soon, it's impossible to use fontawesome.

Are you talking about https://fontawesome.com/ ?
