### ISSUE TITLE
Icon request: inkwell/bottle/vase/potion

### ISSUE THREAD

**Issue by madmadisson** [FortAwesome/Font-Awesome#17674]
**What can it be used for?**
A bottle/potion/inkwell would go well with the existing scroll and feather icon. An addition to the existing bottles and the flask. Also a staple for fantasy settings. What differs from the flask is the round silhouette.

**Example image (optional)**
[Potion or bottle](https://static.thenounproject.com/png/1121420-200.png)
[Vase or inkwell](https://www.onlinewebfonts.com/icon/426243)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, icon sets are not allowed by our contributing guidelines.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Please also [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) to check if an individual request already exists

Closing here

**Comment by madmadisson** [comment]
Sorry for the confusion. It wasn't meant to be a set but examples for names and such. I noticed that Pro has a bottle close to what I was looking for. Thank you~
