### ISSUE TITLE
Icon Request : tiktok

### ISSUE THREAD

**Issue by CharuSharma03** [FortAwesome/Font-Awesome#17682]
**What can it be used for?**
to be used with tiktok brand

**Example image (optional)**
https://fontawesome.com/icons/tiktok?style=brands

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by CharuSharma03** [comment]
Could we please get an icon for tiktok too?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Tik Tok icon is already available:
- https://fontawesome.com/icons/tiktok?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here

**Comment by CharuSharma03** [comment]
Thank you for the quick response. Just confirming, because I am using an
older version of font awesome, if I upgrade, is there a chance that some
things won't work? Does the upgrade delete or remove certain things? Or
does it only add?

**Comment by tagliala** [comment]
Hi

>  if I upgrade, is there a chance that some
things won't work?

It depends. If you are upgrading from FA4, you may need manual work. Ref: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

If you are upgrading from 5.x, occasional breaking changes are still possible: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md

**Comment by CharuSharma03** [comment]
Thank you for the quick reply. That's very helpful..
