### ISSUE TITLE
Icon Request: icon-litecoin (icon-ltc)

### ISSUE THREAD

**Issue by nvk** [FortAwesome/Font-Awesome#1768]
Now that bitcoin symbol was included is time to have "Litecoin", many websites support both and would be great to only have to use one library.

I made a first attempt at it, feel free to change it as long as it still represents the common usage of Litecoin.

[Litecoin SVG](http://cl.ly/0w442j0y1q1V)
![litecoin svg___95 __cmyk_preview_](https://f.cloud.github.com/assets/797193/962694/5f148d9e-04f4-11e3-9e72-41f8d7cb5ed8.png)

New version
![kiticon_glyphs_-_kitecoin](https://f.cloud.github.com/assets/797193/2180674/05b20714-9729-11e3-9c56-c9a67e789a5a.png)

Rodolfo
Coinkite.com

**Comment by jayc89** [comment]
+1 please

**Comment by aspect** [comment]
+1

We are porting MultiBit HD to Litecoin and had to temporarily modify Font Awesome to include Litecoin symbol.  Please add this as soon as possible.

**Comment by challal** [comment]
+1

**Comment by Baker** [comment]
+1

**Comment by sikfeng** [comment]
+1

**Comment by mariodian** [comment]
+1 yes please

**Comment by itemdop** [comment]
+1

**Comment by bkimminich** [comment]
👍

**Comment by aslabs** [comment]
+1

**Comment by jason5515** [comment]
+1 from myhacks.net

**Comment by Kirhchoff** [comment]
+1

**Comment by jackmallers** [comment]
+1

**Comment by jdmadriz** [comment]
+1

**Comment by KVNHNF** [comment]
+1

**Comment by KVNHNF** [comment]
+1

**Comment by NullFragment** [comment]
+1

**Comment by iamcryptoki** [comment]
+1

**Comment by jha** [comment]
+1

**Comment by PaulHughes01** [comment]
+1

**Comment by shyd** [comment]
+1

**Comment by Fiat2LTC** [comment]
+1 please!

**Comment by Fiat2LTC** [comment]
How do we move forward with this?

**Comment by shyd** [comment]
I didn't want to wait and added this SVG <https://commons.wikimedia.org/wiki/File:Litecoin.svg> hardcoded in html

```
<svg class="svg-litecoin" aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0.847 0.876 329.254 329.256"><path d="M330.102 165.503c0 90.922-73.705 164.629-164.626 164.629C74.554 330.132.848 256.425.848 165.503.848 74.582 74.554.876 165.476.876c90.92 0 164.626 73.706 164.626 164.627" fill="currentColor"/><path d="M295.15 165.505c0 71.613-58.057 129.675-129.674 129.675-71.616 0-129.677-58.062-129.677-129.675 0-71.619 58.061-129.677 129.677-129.677 71.618 0 129.674 58.057 129.674 129.677" fill="currentColor"/><path d="M155.854 209.482l10.693-40.264 25.316-9.249 6.297-23.663-.215-.587-24.92 9.104 17.955-67.608h-50.921l-23.481 88.23-19.605 7.162-6.478 24.395 19.59-7.156-13.839 51.998h135.521l8.688-32.362h-84.601" fill="#fff"/></svg>
```

and styled it with

```
.svg-litecoin {
    display: inline-block;
    height: 1em;
    overflow: visible;
    vertical-align: -.125em;
    font-size: 3em;
}
```

Then it fits in there nicely: <https://schuett.io/wtf/>

**Comment by Shyzer** [comment]
+1 for Litecoin being added, especially since BTC and ETH are already in!

**Comment by pascalandy** [comment]
Yes please :-p

![2018-07-14_17h22](https://user-images.githubusercontent.com/6694151/42728555-8e31dffa-878a-11e8-8f21-726d800a0dc6.jpg)

**Comment by 54** [comment]
Throwing in my support as well. It would be nice to have for my payments screen.

**Comment by MakoMakox** [comment]
+1

**Comment by Sijisu** [comment]
+1

**Comment by NbaYB** [comment]
+1111111111111

**Comment by kawaiidesune** [comment]
+1

**Comment by Oncorporation** [comment]
+1

**Comment by FrBillyD** [comment]
+1 🤣

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
