### ISSUE TITLE
instagram-dotted

### ISSUE THREAD

**Issue by SurjenduBiswas** [FortAwesome/Font-Awesome#17695]
**What can it be used for?**
This is the dotted instagram icon. The dots will be transparent which will display the background behind. So that we can use good combinations of `color`s and `background-color`s to get a nice dotted pattern on instagram icon.

**Example image (optional)**
![Untitled62](https://user-images.githubusercontent.com/77108861/110125471-58775680-7de9-11eb-8058-ab2171121ed6.png)

**Icon request checklist**
- [x] This is a single icon
- [x] Icon request: instagram-dotted
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
As this is not an official Instagram icon, we have decided not to add it to Font Awesome. You are, however, welcome to create your own version of it and upload it to a custom kit.
