### ISSUE TITLE
fa fa-remove

### ISSUE THREAD

**Issue by marcuspramirez** [FortAwesome/Font-Awesome#17694]
I was working on a tutorial this was an x

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think I didn't understand this request.

Are you looking for [fa-times](https://fontawesome.com/icons/times?style=solid) ?

**Comment by marcuspramirez** [comment]
Ah yes that’s it.  Thank you!

**Comment by tagliala** [comment]
Welcome, closing here
