### ISSUE TITLE
Icon request: Flag-BD 🇧🇩 

### ISSUE THREAD

**Issue by saakeeb** [FortAwesome/Font-Awesome#17697]
**What can it be used for?**
Logo for displaying Bangladesh country flag

**Example image (optional)**
![bangladesh-4866534_1280](https://user-images.githubusercontent.com/60483192/110199314-10f0d900-7e82-11eb-9321-f727a0309218.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

https://en.wikipedia.org/wiki/Flag_of_Bangladesh

**Comment by saakeeb** [comment]
It will be impressive feelings to see the Bangladeshi flag in font-awesome, It will boost the speed of our work.

**Comment by tagliala** [comment]
I'm leaving this open, but flags (especially the ones that need colors) are out of scope at the moment

Please consider alternatives

Ref: #13944

**Comment by saakeeb** [comment]
There is no alternative for the flag. Color may be an issue, hope proper scope takes place in the future.

**Comment by tagliala** [comment]
> There is no alternative for the flag.

I mean an alternative library. There are many out there, this is an example, and is listed in #13944: https://flagicons.lipis.dev/

**Comment by saakeeb** [comment]
Thank you

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
