### ISSUE TITLE
Icon request: Gizmo (or 3d coordinate system)

### ISSUE THREAD

**Issue by aeris170** [FortAwesome/Font-Awesome#17705]
This is probably a duplicate of #14906 but I think the icon in there is a bit off.

**What can it be used for?**
Mostly for 3D rendering software where some pieces of a scene can be moved using a control named Gizmo. It can also be used for representing a 3D coordinate system. [example](https://user-images.githubusercontent.com/25724155/110259330-25cf8880-7fb8-11eb-98d3-aa8dc06383ba.png)

**Example image (optional)**
![giz](https://user-images.githubusercontent.com/25724155/110259067-d2106f80-7fb6-11eb-8f49-dab194ddef67.png)
I used paint, don't judge 🤷 

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This is probably a duplicate of #14906 but I think the icon in there is a bit off.

Please post your example there explaining why the example is wrong. I will then add "Gizmo" to the title for easier searching

Closing here
