### ISSUE TITLE
Icon Request: icon-java

### ISSUE THREAD

**Issue by mcrose** [FortAwesome/Font-Awesome#1770]
Hi all
I just want to know if the java icon could be added to the list, as the icons for jboss, tomcat, primefaces, eclipse ide and so on as well

the point is, if you can see my page http://icarusdb.com.py/html5/#work you can read I share some thoughts with icons

well, I want to add other tag called "tools" so I add tools I use for developing systems, when you fill a CV in the web, they use to call it "skills" I prefer to call them tools because they are tools, the way you used them to develop or implement things are really the skills 

well, that's the idea, hope to hear from you soon, thanks

**Comment by famaridon** [comment]
+1 for all commons language java, php, c, c++, ...

**Comment by ab-test** [comment]
+1

**Comment by ab-test** [comment]
+1 for java.  Still hoping
