### ISSUE TITLE
Icon request: shushing-face (silence)

### ISSUE THREAD

**Issue by coorasse** [FortAwesome/Font-Awesome#17703]
**What can it be used for?**
For something that should be secret 🤫  and not being told

**Example image (optional)**
🤫 
A face with a finger in front of the mouth.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Ref: https://emojipedia.org/shushing-face/

**Comment by aethior** [comment]
Hi @coorasse,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/face-shush

Regards.

cc/ @tagliala
