### ISSUE TITLE
Icon-request: team-badge

### ISSUE THREAD

**Issue by markraus** [FortAwesome/Font-Awesome#17706]
Hello there
I know the identifier 'badge' is already used for this icon: https://fontawesome.com/icons/badge
Maybe someone can suggest a better name for this kind of icon I am looking for (see examples)

**What can it be used for?**
The icon can be used for sports teams (and also in medieval environments)

**Example image**
![image](https://user-images.githubusercontent.com/15369568/110307614-6999b080-7fff-11eb-9029-f8f8d83450bd.png)
![image](https://user-images.githubusercontent.com/15369568/110307646-74544580-7fff-11eb-898f-197ef8e62af4.png)
![image](https://user-images.githubusercontent.com/15369568/110307668-79b19000-7fff-11eb-9bf0-bcd4d9568ed4.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you looking for the [shield](https://fontawesome.com/icons/shield?style=solid) icon available in FA Pro?

**Comment by markraus** [comment]
thank you @tagliala
This is exactly the icon I was looking for. I don't know why 'shield' didn't come to my mind while searching
