### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by SharonMcIntosh** [FortAwesome/Font-Awesome#17719]
**What can it be used for?**
We're looking to use circle versions of the social media icons (Facebook, Twitter, Instagram, LinkedIn and YouTube). Would you be able to create round icons, similar to the image attached please?

**Example image (optional)**

![Social media logos_burgundy_2021](https://user-images.githubusercontent.com/80464480/110793356-6eaf6780-826c-11eb-8203-85d73ab066db.jpeg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, this is a request for a set and it doesn't meet our contributing guidelines for the free repo

You can open single, individual request for each brand (but please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones)

Or achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/496/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
