### ISSUE TITLE
购买PRO专业版用于内置在开发的软件中，软件用户使用还需要再购买PRO授权吗？

### ISSUE THREAD

**Issue by deepdfhy** [FortAwesome/Font-Awesome#17720]
购买PRO专业版用于内置在开发的软件中，软件用户使用还需要再购买PRO授权吗？

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per google translate

> Buying the PRO professional version is used to be built into the developed software, do software users still need to purchase PRO authorization again?

If this is an inquiry about license, and answers at https://fontawesome.com/support#license-general doesn't help, please send an email to hello@fontawesome.com

Please also send details about the developed software and how it is including Font Awesome Pro

Hope it helps

Closing here
