### ISSUE TITLE
Missing fonts I have used on my webpages

### ISSUE THREAD

**Issue by rickj61** [FortAwesome/Font-Awesome#17723]
Missing fonts I have used on my webpages for over a year and are now not found. The following fonts in particular are
fas fa-drafting-compass and fas fa-bezier-curve.

I've poked around to see if they were renamed but not finding anything that matches or closely resembles what they look like.

TIA!
Rick...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The following fonts in particular are fas fa-drafting-compass and fas fa-bezier-curve.

Sorry, cannot replicate: https://jsfiddle.net/tagliala/zvkwmf1L/1/

I cannot leave this issue open because it doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome).

If you think there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md). Please also provide a reproducible test case

**Comment by rickj61** [comment]
Thanks for the reply.

Yes, that is how I have them designated on my web page. Several others are working these 2 are not and display empty default symbol.

fas fa-drafting-compass and fas fa-bezier-curve again these 2 do not work anymore and show an empty default icon. Others work just fine.

My site is hosted by GoDaddy and created with wordpress version 5.7. Well actually created with much earlier version but it has been upgraded to this version.
***@***.***D71748.2587A610]
Left one is: fas fa-drafting-compass
Middle one is: fas fa-bezier-curve
Right one is: fas fa-shopping-cart

Another page has fas fa-cubes and it works. These seem to be the only 2 not working in my environment. I have tried many more just to see if any of ther other fonts would not display but so far they all have worked.

This is what it looks like zoomed in
***@***.***D7174A.A4A69BC0]

Cheers!

Rick Johnston, sUAS Remote Pilot, GISP, Reality Capture, AR/VR and 3D Modeling/Printing Enthusiast

Mobile: 937.604.2220

***@***.***D71742.9268C8A0]<https://www.linkedin.com/in/rick-johnston-17266a8>

"Autodesk ReCap doesn't just reduce ambiguity, it eliminates it. Three dimensional modeling allows us to be there, to see it as it is. This isn't an interpretation of the data; you are in the data. It's a paradigm shift for the way we see our underground vaults."
  -- Everett Clary and Forrest Roy, Anchorage Municipal Light & Power

Have you seen the Anchorage Municipal Light and Power Reality Capture Video...<https://youtu.be/s48qVfYJrXw>

Read their Article...<http://bimontherocks.com/small-projects-award-2014-excellence-in-infrastructure>

Article in CE News...<http://cenews.com/article/10004/seeing-what-is-underground>

**Comment by tagliala** [comment]
Hi, please don't use email attachments (they don't work) and please do not use screenshot, they will not work for this case :)

Use https://github.com/FortAwesome/Font-Awesome/issues/17723 to upload attachments

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.
