### ISSUE TITLE
Icon request: vehicle-tow

### ISSUE THREAD

**Issue by 2ne** [FortAwesome/Font-Awesome#17729]
**What can it be used for?**
This icon will represent a vehicle being towed.

**Example image (optional)**
https://www.autodna.com/blog/wp-content/uploads/2017/08/basics-of-towing.jpg

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per #4972, this icon is available in the upcoming FA6 (now in private alpha). I still don't know if this icon will be included in the free or in the pro set

![image](https://user-images.githubusercontent.com/556268/111064081-5af54280-84b2-11eb-9997-fd57d6f2d986.png)

Closing here
