### ISSUE TITLE
404 Error With CDN Which May Cause Icons To Not Load In

### ISSUE THREAD

**Issue by Sousa8697** [FortAwesome/Font-Awesome#17736]
Hello, I have noticed a slight issue that I'm unsure if it is out of your control but I have an application that uses the CDN and have had no problem with the requests coming back as 200 until just recently I have been getting 404 errors here and there when requesting the icons. I am unsure if this is a problem on my end but this just started recently so I don't feel like it is. The URL that I have been using is https://kit.fontawesome.com/3e6b4782cd.js . Any help understanding the issue and how to fix it would be greatly appreciated, thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We had a short interruption in our kit cdn: https://status.fortawesome.com/#past-incidents

Could you please check that everything is fine now?

**Comment by Sousa8697** [comment]
Everything seems fine at the moment. I will let you know if anything changes, thank you!

**Comment by tagliala** [comment]
Welcome, closing here
