### ISSUE TITLE
Feature request: Customization - Personal Font Set

### ISSUE THREAD

**Issue by buttjer** [FortAwesome/Font-Awesome#1773]
Choose every letter and/or category to build a personal webfont of FontAwesome. That would reduce the filesize and it would be easier to add much more icons to FontAwesome without having size considers.

I recommend a basic set based on the current state for the cdn and regular download.

**Comment by PeterBowater** [comment]
+1

**Comment by tagliala** [comment]
The font subsetter is available in FA Pro

The built in tree-shaking functionality of many asset bundlers to reduce the output font size

Feel free to use other alternatives to create custom webfont files
