### ISSUE TITLE
Bullseye Icon - Duotone style is the same for both rings

### ISSUE THREAD

**Issue by 2ne** [FortAwesome/Font-Awesome#17730]
**Describe the bug**
Bullseye duotone style is the same for both rings

**Expected behavior**
Should be able to change opacity or color of both rings.

**Version and implementation**
Version: 5.10.1

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm the issue and this is an issue also in the upcoming FA6: https://fontawesome.com/icons/bullseye?style=duotone

Let's assign @sensibleworld
