### ISSUE TITLE
Docs: increase contrast of "pro" icons for expired subscriptions

### ISSUE THREAD

**Issue by BieleckiLtd** [FortAwesome/Font-Awesome#17739]
"Pro" icons are washed out and its hard to see them. Also not good from accessibility point of view. I would understand this design decision if the user was not logged in, but when they are and they purchased the license? Nuisance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I would understand this design decision if the user was not logged in, but when they are and they purchased the license?

That is how it should work

Could you please check if your subscription is still valid?

### Logged out

![image](https://user-images.githubusercontent.com/556268/111898417-3bb46300-8a26-11eb-957a-1e4cd0c6ba50.png)

### Logged in

![image](https://user-images.githubusercontent.com/556268/111898407-217a8500-8a26-11eb-838a-591b36540588.png)

**Comment by BieleckiLtd** [comment]
My subscription is no longer valid, however I can still use PRO icons from the point in time when subscription was active.

**Comment by tagliala** [comment]
Thanks for the clarification

Let's assign @robmadole

**Comment by sensibleworld** [comment]
We've changed the way we display Pro icons in version 6, and no longer de-emphasize any icons.

https://fontawesome.com/v6.0/icons?s=solid%2Cbrands
