### ISSUE TITLE
Icon request: storefront-door

### ISSUE THREAD

**Issue by sgladney** [FortAwesome/Font-Awesome#17744]
**What can it be used for?**
for a store with a door and window

**Example image (optional)**
![image](https://user-images.githubusercontent.com/80801957/111407752-8cd0f980-86aa-11eb-908e-aadaec73adfd.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ x] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have:
- https://fontawesome.com/icons/store?style=solid
- https://fontawesome.com/icons/store-alt?style=solid

Hope it helps

Closing here
