### ISSUE TITLE
Icon request: fingers-crossed

### ISSUE THREAD

**Issue by jeremy-illuminate** [FortAwesome/Font-Awesome#17752]
**What can it be used for?**
Any interaction on a button where the results are hopeful but unclear.  For instance, the "I feel lucky" button on Google.  In our particular application, the user gets to select several options and then try to process a file.  If it doesn't look good, they can try again.

**Example image (optional)**
🤞 

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hey @jeremy-illuminate. This icon is available as part of the Font Awesome 6 alpha release. Check it out here: http://fontawesome.com/download
