### ISSUE TITLE
refresh icon request (as seen in fontawesome 4.7)

### ISSUE THREAD

**Issue by hyfydistro** [FortAwesome/Font-Awesome#17757]
**What can it be used for?**
I use it a load or spinner icon. If I need my user to refresh, this could also hint that.

**Example image (optional)**
![refresh icon](https://user-images.githubusercontent.com/24542308/111939673-7c33df80-8aff-11eb-9742-829927405b71.png)

I'm unable to find the `refresh` icon in the svg folder. I often use it in fontawesome 4.7. Will you be able to put it in?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I'm unable to find the refresh icon in the svg folder. I often use it in fontawesome 4.7. Will you be able to put it in?

It's called `sync`

- https://fontawesome.com/icons/sync?style=solid
- https://fontawesome.com/icons/sync-alt?style=solid

Ref:
- https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Hope it helps

Closing here
