### ISSUE TITLE
Icon request: Zoom (brand icon)

### ISSUE THREAD

**Issue by cool-beanz1** [FortAwesome/Font-Awesome#17769]
**What can it be used for?**
Specifically for use with the TeamDynamix application. Icons represent Services in the Service Catalog and Knowledge base. This is a brand icon

**Example image (optional)**
![Zoom-Logo](https://user-images.githubusercontent.com/81185152/112324751-1bccab80-8c81-11eb-8d2d-4a444112839d.png)

**Icon request checklist**
- [x] This is a **single** icon 
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by cool-beanz1** [comment]
#16079 also requests the Zoom icon, but there's been no action since January 2020.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> #16079 also requests the Zoom icon, but there's been no action since January 2020.

You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Please 👍🏼 that request
