### ISSUE TITLE
Icon request: ethnicity

### ISSUE THREAD

**Issue by djechelon** [FortAwesome/Font-Awesome#17761]
**What can it be used for?**

An icon that displays human ethnicity can be used in inclusive context. For example, I am currently performing a research study on GDPR privacy statements, and in Europe the "racial and ethnical origin" are extremely protected personal information. I would like to represent them in a privacy statement for a (hypothetical) company that is processing this kind of information.

In my mind, the icon should juxtapose a _white_ person with a _black_ person, of the same size, possibly in a way that makes no preference or priority of any.

I understand that today this is a particularly sensitive topic that must be treated with proper neutrality and tact.

**Example image (optional)**

![Image 1](https://user-images.githubusercontent.com/3042285/112036328-cd17f800-8b40-11eb-9696-6894bb7dd529.png)
I would personally remove the smile and leave the shapes

[Source](https://thenounproject.com/term/ethnicity/88194/) (Creative Commons)

![Image 2](https://user-images.githubusercontent.com/3042285/112036614-24b66380-8b41-11eb-9f25-1d7b8873cfad.png)
This one is without smiles etc, but could be too complex for smaller sizes

[Source](https://thenounproject.com/term/ethnicity/94199/) (Creative Commons)

**Icon request checklist**
- [X] This is a single icon. The _reverse_ can be achieved by flipping it
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate (searched for `race`, `ethnicity`, `ethnical`
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object: it is for two humans

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
