### ISSUE TITLE
Icon request: webhook

### ISSUE THREAD

**Issue by thomas-price** [FortAwesome/Font-Awesome#17775]
**What can it be used for?**
Used as a webhook
Refer to https://github.com/FortAwesome/Font-Awesome/issues/5139 open since 2014

**Example image (optional)**
Refer to image in https://github.com/FortAwesome/Font-Awesome/issues/5139

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Refer to #5139 open since 2014

You may be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
