### ISSUE TITLE
Icon request: Patreon

### ISSUE THREAD

**Issue by mikictino** [FortAwesome/Font-Awesome#17772]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Patreon icon is already available:
- https://fontawesome.com/icons/patreon?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
