### ISSUE TITLE
Icon request: geo

### ISSUE THREAD

**Issue by tiagorangel2011** [FortAwesome/Font-Awesome#17779]
Hi, I would really like to request an icon.
The icon name can be something like fa-geo, but it is not _very_ important

**What can it be used for?**
For example, travelling apps like booking

**Example images**
![image](https://user-images.githubusercontent.com/70700766/112761099-6a67a600-8ff1-11eb-8081-bd8a2424a199.png) ![Demo from material design icons](https://user-images.githubusercontent.com/70700766/112760921-9fbfc400-8ff0-11eb-9cef-b87ec9a47f38.png)

I searched around the issues and there is not any duplicate.

Greetings,
Tiago Rangel de Sousa

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is already available for our Pro customers:
- https://fontawesome.com/icons/location?style=solid

If you want to know why some icons are added only to the Pro set, please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs): "Why are some (highly requested) icons not available in Font Awesome Free?"

Closing here
