### ISSUE TITLE
In some Figma document my font work in some other not

### ISSUE THREAD

**Issue by st0ckaEvooq** [FortAwesome/Font-Awesome#17773]
This 20sec recording say it all.
I tried to copy paste the icon and it work on some document and not on some other....
Speechless.

https://www.awesomescreenshot.com/video/3170969?key=f7fa2cd037a05f1cae582b6e13bfea76

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can't help here

I know that @sensibleworld uses Figma, do you have a clue?

**Comment by sensibleworld** [comment]
Not entirely sure what's happening, but the one thing I always try first is to close Figma, and then delete the Font Awesome Pro OTF file from my font manager. Then I reinstall a fresh download of the OTF and re-open Figma. Most programs cache font files (not expecting them to be "updated" often).

You could also try selecting the type within that text field to ensure that Font Awesome is selected as the typeface. Sometimes the text box and the text itself have different styles applied to them.

**Comment by st0ckaEvooq** [comment]
alright thanks for your answers, will try this ;)


Le jeu. 25 mars 2021 à 07:14, Jory Raphael ***@***.***> a
écrit :

**Comment by st0ckaEvooq** [comment]
sure, i mean it work 50% of the time but that's ok for me
