### ISSUE TITLE
Inconsistency in icons.json file (FA 6.0.0-alpha3)

### ISSUE THREAD

**Issue by shanewhitehead** [FortAwesome/Font-Awesome#17786]
**Describe the bug**
All the "aliases" sections in the icons.json file are in the format:

```
"aliases": {
  "names": [
    <name of alias>,
    <name of alias>,
    <name of alias>,
    ...
  ]
}
```

The aliases section for the new "apostrophe" icon (line 5532 if that helps) is in the format:

```
"aliases": {
  "unicodes": [
    "e08e"
  ]
},
```

(Which broke my parser :) )
I assume this is an error

**To Reproduce**
Just look in the file I guess

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Expected the format to be similar to all other occurrences

**Screenshots**

**Version and implementation**
Version: 6.0.0-alpha3
Browser and version: N/A

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@robmadole is this change intended?

**Comment by robmadole** [comment]
Yes this change is intentional. We don’t foresee any more monkey business with the format so this should be the final scheme.

**Comment by tagliala** [comment]
Thanks!

Closing here
