### ISSUE TITLE
Icon Request: Add Kiwismedia

### ISSUE THREAD

**Issue by rahxuls** [FortAwesome/Font-Awesome#17787]
**What can it be used for?**
It can be used in portfolio and blog links. 

**Example image (optional)**
All the SVG =>  https://github.com/kiwismedia/kiwismedia-brandkit/tree/master/svg

**Comment by aethior** [comment]
>KiwisMedia is now [@FuelerHQ](https://www.instagram.com/FuelerHQ/) a community of passionate multiskilled makers and creators. ([more info](https://www.instagram.com/kiwismedia/))

Regards.

cc/ @tagliala
