### ISSUE TITLE
(css) grid alignment and justification icons request

### ISSUE THREAD

**Issue by chris-kruining** [FortAwesome/Font-Awesome#17788]
I would love to have icons for css grid properties, much like webflow uses. or as illustrator has.

webflow:
![image](https://user-images.githubusercontent.com/5786905/113291801-d6992100-92f3-11eb-9e4c-16ee1b0f1276.png)

illustrator:
![image](https://user-images.githubusercontent.com/5786905/113291857-efa1d200-92f3-11eb-83be-9597173cd1e0.png)

**Comment by sensibleworld** [comment]
@chris-kruining I completely agree, and have actually already started working on them for version 6!

**Comment by timtjtim** [comment]
I think this is a duplicate of #4390, although that one is now missing an image, so hard to tell!

**Comment by tagliala** [comment]
@timtjtim thanks

Closing as a duplicate of #4390 

BTW Jory is working on those icons ans they will be part of FA6 https://twitter.com/sensibleworld/status/1390386497984114690
