### ISSUE TITLE
CSS property `transform: scale()` does not affect size of pseudo-unicode (via SASS)

### ISSUE THREAD

**Issue by hyfydistro** [FortAwesome/Font-Awesome#17782]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG Sprites
- [ ] SVG with JS
- [*] Web Fonts with CSS
- [*] On the Desktop

**Bug report checklist**
- [*] I have filled out as much of the above information as I can
- [*] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [*] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

I'm trying to animate or make a small css effect when a checkbox input is checked. With Font Awesome v4, the `transform: scale()` property worked fine. However, in this case, with Font Awesome v5.15.3, nothing happens. 

I use the following as my dev environment:
- Webpack 
- SASS preprocessor
- CDN for FontAwesome v5
```
  <!-- Font Awesome v5 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
    crossorigin="anonymous" />
```

HTML
```
          <label class="contact-list__icon--favorite">
            <input type="checkbox" id="checkboxID">
            <span for="checkboxID" class="pseudo--favorite"></span>
          </label>
```

SASS
```
.contact-list__icon--favorite {
  cursor: pointer;

  input[type="checkbox"] {
    display: none;

    + .pseudo--favorite {
      display: inline-block;
    }

    + .pseudo--favorite::before {
      content: "\f005";
      font-family: "Font Awesome 5 Free";
      font-style: normal;
      font-weight: normal;
      font-variant: normal;
      text-transform: none;
      line-height: 1.5;
      color: base.$text-color;
      width: 24px;
      vertical-align: middle;
    }

    &:checked + .pseudo--favorite::before {
      content: "\f005";
      color: base.$favourites-icon-color;
      font-weight: 900;
      animation: pop 180ms;
    }
  }
}

// Star Icon
.contact-list__icon--favorite:hover > .pseudo--favorite::before {
  // font-size: 34px;
  transform: scale(3) !important;
  color: base.$favourites-icon-color !important;
}

@keyframes pop {
  0% {
      transform: scale(0);
  }

  90% {
      transform: scale(1.3);
  }

  100% {
      transform: scale(1);
  }
}
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This issue is reproducible without Font Awesome and IIRC this is a browser limitation

Demo: https://jsfiddle.net/tagliala/4m8ykjo2/13/

Solution: do not apply `transform` to pseudo elements

https://jsfiddle.net/tagliala/4m8ykjo2/14/

Hope it helps

Closing here

**Comment by hyfydistro** [comment]
Alright, thanks for letting me know. 👍 I end up reproducing the effect with font-sizes.
