### ISSUE TITLE
Feature request: host individual packages alongside releases

### ISSUE THREAD

**Issue by rlueder** [FortAwesome/Font-Awesome#17789]
**Is your feature request related to a problem? Please describe.**
This feature request is related to those that have a lifetime license like myself but are no longer subscribers (which means no access to the npm registry). This feature relates to issues like https://github.com/FortAwesome/Font-Awesome/issues/17620, https://github.com/FortAwesome/Font-Awesome/issues/17147, https://github.com/FortAwesome/Font-Awesome/issues/17163,  https://github.com/FortAwesome/Font-Awesome/issues/17185

**Describe the solution you'd like**
I'm wondering if the FontAwesome team would consider including the individual packages as part of their releases, so for example `fortawesome-pro-light-svg-icons-5.15.3.tgz` would be available to npm install directly from Github so that installing would be something similar to the command below:

`npm install https://github.com/FortAwesome/Font-Awesome-Pro/releases/download/5.15.3/fortawesome-pro-duotone-svg-icons-5.15.3.tgz`

**Describe alternatives you've considered**
The alternative is to follow the steps described here: https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download and host the file locally (not great if you're on a team) or publish a private npm registry (which itself requires a subscription to either npm Pro or Team).

**Feature request checklist**
- [ x ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ x ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by johnbaro** [comment]
+++1 for this (a year later) @rlueder.

The instructions mentioned (https://fontawesome.com/how-to-use/on-the-web/setup/using-the-npm-download) say to download the npm package (even if subscription is expired), this does not seem to be possible anymore, is it the same for you?

As an FYI re private NPM, Azure Devops provides free private NPM registries. [Instructions](https://limelightmarketing.com/blogs/creating-your-own-private-npm-package-in-azure-devops/)

**Comment by rlueder** [comment]
@johnbaro I haven't used FontAwesome since, part of the decision to move away was the lack of support, I still think this is a valid request but obviously not a priority for FontAwesome.
