### ISSUE TITLE
Deezer icon not working on my site while all others I am trying do

### ISSUE THREAD

**Issue by mdkberry** [FortAwesome/Font-Awesome#17792]
`<i class="fab fa-deezer"></i>` 

taken from here - https://fontawesome.com/icons/deezer?style=brands  Updated: Version 5.14.0

added to a button in my html page but nothing shows up. I am using 6 other fab icons in exactly the same format and they are working fine so it isnt my code. 

**To Reproduce**
example of the code line above not producing the symbol and the ones that do work can be seen on this page
https://markdkberry.com/linktreemusic.html

tried it in brave and chrome and same results

EDIT: using browser inspect I can see it is sizing itself to 0x0 for some reason.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[deezer](https://fontawesome.com/icons/deezer?style=brands) has been introduced in Font Awesome 5.14.0, your website is using 5.12.1

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

Hope it helps

Closing here
