### ISSUE TITLE
Icon request: icon-syringe (icon-drug, icon-injection)

### ISSUE THREAD

**Issue by concordian** [FortAwesome/Font-Awesome#1779]
Category: medical

icon-name:  syringe

Desc:  syringe w needle

My graphic skills aren't sufficient to create a draft.

**Comment by RVXD** [comment]
+1

**Comment by Crayon2000** [comment]
+1

**Comment by afrome** [comment]
+1

**Comment by G-Driver** [comment]
+1 

Also a vaccine would be great

**Comment by LucasVandroux** [comment]
+1

**Comment by jbteague** [comment]
+1

**Comment by phpforfree** [comment]
+1

**Comment by cityofsleep** [comment]
+1

**Comment by Dret42** [comment]
+1

**Comment by mwarnock** [comment]
+1

**Comment by sebasorribas** [comment]
+1   any news about this one? Thanks

**Comment by blacatena** [comment]
+1

Also have an alias, fa-inject (for use of the action "inject" in any application, such as "inject this attribute into the target").

**Comment by alex21** [comment]
+1

**Comment by AlxZb** [comment]
+1

**Comment by tildemark** [comment]
+1

**Comment by alex21** [comment]
How much votes we need to approve this?

**Comment by tagliala** [comment]
@alex21 https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Heinerion** [comment]
+1

**Comment by jmichelsen** [comment]
+1

**Comment by nxtdesigns** [comment]
+1

**Comment by IgorRocha** [comment]
+1

**Comment by safadig** [comment]
+1

**Comment by TonyValenti** [comment]
+1

**Comment by ahoulgrave** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by luisaguilerac** [comment]
+1

**Comment by yvaucher** [comment]
+1

**Comment by paulgailey** [comment]
+1

**Comment by tarunguptapec** [comment]
+1

**Comment by mrjlynch** [comment]
+1

**Comment by runderworld** [comment]
+1

**Comment by gozaa** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by pl21** [comment]
+1

**Comment by dougludlow** [comment]
+1

**Comment by dougludlow** [comment]
Use case: to represent vaccines or immunizations

**Comment by keviano** [comment]
+1

**Comment by Naam** [comment]
+1

**Comment by Tarek-Adra** [comment]
+1

**Comment by deanpcmad** [comment]
Any news on this? It was requested 3 years ago...

**Comment by nsimeonov** [comment]
SymbolIcons has 3 https://fortawesome.com/sets?q=syringe
MiniIcons, Streamline and SteadyIcons have too.
FlatIcons can find you a total of 176: http://www.flaticon.com/search?word=syringe

Yes I would love to have all the icons I need from font awesome as they are totally the best and I don't like using like 10 different fonts with icons, but it's not the end of the world. Bitching about that is not the way IMO.

**Comment by chodaboy14** [comment]
+1

**Comment by ezetojo** [comment]
+1

**Comment by pepperstreet** [comment]
+1 please. 
In general, medical icons are pretty weak. Why sooo many niche company logos? ;)

**Comment by FMassimiliano** [comment]
+1

**Comment by tortellinitony** [comment]
+1

**Comment by andreixk** [comment]
+1

**Comment by brianwood** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by andreschabur** [comment]
+1

**Comment by per3ian** [comment]
+

**Comment by codingtub** [comment]
+1

**Comment by Motassem-MK** [comment]
+1

**Comment by Andrend** [comment]
+1

**Comment by ArthurAlagul** [comment]
+1

**Comment by nflorentin** [comment]
+1

**Comment by sensibleworld** [comment]
A syringe icon is included in the latest 5.0.7 release of Font Awesome: https://fontawesome.com/icons?d=gallery&q=syringe
