### ISSUE TITLE
Icon Request: fa-docker

### ISSUE THREAD

**Issue by cinderblockgames** [FortAwesome/Font-Awesome#17797]
I'd love to see docker's whale-with-containers icon available though fa -- it'd be great for linking to docker hub packages.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Docker icon is already available:
- https://fontawesome.com/icons/docker?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
