### ISSUE TITLE
paperclip icon in version 6 undesirably different than in version 5

### ISSUE THREAD

**Issue by isadoracreative** [FortAwesome/Font-Awesome#17796]
It appears the paperclip icon got a design change that makes it look different than the paperclip icon that is ubiquitously used in email applications to represent an attachment. This is undesirable as we have an app that relies on that icon to represent attachments in a fake email client. Please do not change the paperclip icon. Otherwise we will have to use two versions of font awesome simultaneously to avoid breaking the meaning of the paperclip. The one currently in the version 6 alpha does not hold the same meaning as the one in version 5 unless gmail, outlook, and other popular email clients were to change the way attachments are indicated. In outlook, the icon is slanted and the wires of the paperclip are close together (as in version 5). In gmail, the icon is sometimes vertical (as in version 6), but again the wires of the paperclip are close together.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please copy & paste your comment at #5336, there is already a discussion ongoing about the new paperclip design

Closing here

**Comment by sensibleworld** [comment]
@isadoracreative Yup! We've heard this feedback and are going to keep the orientation of the current paperclip (from v5), but also add in a new "vertical" variant as well (with a design update over what's currently in the alpha). I just posted the latest updates in [the thread](https://github.com/FortAwesome/Font-Awesome/issues/5336) that @tagliala mentioned above.
