### ISSUE TITLE
Bug Icon - one leg is shorter than the other

### ISSUE THREAD

**Issue by ZsharE** [FortAwesome/Font-Awesome#17800]
**Describe the bug**
The bug icon has one leg shorter than the other one.

**To Reproduce**
https://fontawesome.com/icons/bug?style=light

**Expected behavior**
The bug legs should have the same size.

**Screenshots**
![Bug smaller leg](https://dev.seomat.com/sources/bug-leg-smaller.png)

**Version and implementation**
Version: 5.0.0
Browser and version: Chrome 89

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Good catch!

I can confirm that this has been fixed in FA6, but let's assign @sensibleworld , so it can be fixed also in FA5 together with #17106

**Comment by sensibleworld** [comment]
This should now be fixed: https://fontawesome.com/v5.15/icons/bug?style=light
