### ISSUE TITLE
Django 3.2 The app label is not a valid Python identifier.

### ISSUE THREAD

**Issue by Dyocius** [FortAwesome/Font-Awesome#17801]
**Describe the bug**
Error when using runserver in Django 3.2 
Works with Django 3.1.8

**To Reproduce**
pip install Django==3.2
pip install fontawesome-free==5.15.3

Add 'fontawesome-free' to your installed apps in your settings.py file.

python manage.py runserver

`Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
web_1  |     autoreload.raise_last_exception()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
web_1  |     raise _exception[1]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
web_1  |     autoreload.check_errors(django.setup)()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
web_1  |     app_config = AppConfig.create(entry)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
web_1  |     import_module(entry)
web_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
web_1  | ModuleNotFoundError: No module named 'fontawesome-free'
web_1  | /code/ecoprofile/settings.py changed, reloading.
web_1  | Watching for file changes with StatReloader
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
web_1  |     autoreload.raise_last_exception()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
web_1  |     raise _exception[1]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
web_1  |     autoreload.check_errors(django.setup)()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
web_1  |     apps.populate(settings.INSTALLED_APPS)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
web_1  |     app_config = AppConfig.create(entry)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 255, in create
web_1  |     return app_config_class(app_name, app_module)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 38, in __init__
web_1  |     raise ImproperlyConfigured(
web_1  | django.core.exceptions.ImproperlyConfigured: The app label 'fontawesome-free' is not a valid Python identifier.`

**Version and implementation**
Version: 5.15.3

**Comment by tagliala** [comment]
@robmadole any hint here?

**Comment by Dyocius** [comment]
Related resources:
https://code.djangoproject.com/ticket/32285
https://github.com/django/django/commit/8b2a30f6f16cb1f3538847954030d69da005bc7f

**Comment by Antoni-Czaplicki** [comment]
I have that same problem

**Comment by ziouf** [comment]
As mentioned in #17812

The quick solution is to rename pypi package from `fontawesome-free` to `fontawesome_free`.

**Comment by robmadole** [comment]
I'll get with @deathnfudge and chat about this. Is this new in Django 3.2? Why was this change made does anyone know?

**Comment by ziouf** [comment]
Hyphen issue in package name is not new. It's in Python language specs (https://www.python.org/dev/peps/pep-0008/) :

> Package and Module Names Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.
> Since module names are mapped to file names, and some file systems are case insensitive and truncate long names, it is important that module names be chosen to be fairly short -- this won't be a problem on Unix, but it may be a problem when the code is transported to older Mac or Windows versions, or DOS.

**Comment by deathnfudge** [comment]
This was my bad. Not sure how I missed this. I will get a fix in soon.

**Comment by robmadole** [comment]
So Django started enforcing it in 3.2? I'm trying to figure out if this was always an issue or if a recent change to Django is causing this. Why does the package repository allow uploads of packages that violate the spec?

**Comment by robmadole** [comment]
Oh wait...I wonder if our private repository allows hyphens! We are using Cloudsmith and maybe they allow it when Pypi does not? That could be.

**Comment by ziouf** [comment]
As far as I remember, pypi allows hyphen even if it's violating python specs ... 
We have to be careful

**Comment by robmadole** [comment]
Well that's a :foot: :gun:. Ok. We'll get this figured out and fixed as timely as we can.

**Comment by ziouf** [comment]
Python's setuptools renames packages to remove hyphen at build time. But I agree, the check should be implemented in pypi itself

**Comment by Dyocius** [comment]
> I'll get with @deathnfudge and chat about this. Is this new in Django 3.2? Why was this change made does anyone know?

https://github.com/FortAwesome/Font-Awesome/issues/17801#issuecomment-815996334

@robmadole Yes, see the links I referenced. The intent was to prevent users from using a period in their app name.

**Comment by jacklinke** [comment]
This is an issue on fontawesome-pro + django 3.2+ as well.

**Comment by mingfengwan** [comment]
for a quick fix:
in settings.py before installed_apps add
`sys.modules['fontawesome_pro'] = __import__('fontawesome-pro')`

**Comment by robmadole** [comment]
Ok all. We thought this through and we are going to rename these two projects to `fontawesomefree` and `fontawesomepro`.

That seemed to be the most Pythonic way of dealing with this. If there are any technical objections or "hey, whoa, stop!" thoughts let us know. We've got this work completed for our 6.x branch and we'll back port to 5.x when we get some time.

**Comment by mingfengwan** [comment]
> Ok all. We thought this through and we are going to rename these two projects to `fontawesomefree` and `fontawesomepro`.
> 
> That seemed to be the most Pythonic way of dealing with this. If there are any technical objections or "hey, whoa, stop!" thoughts let us know. We've got this work completed for our 6.x branch and we'll back port to 5.x when we get some time.

I installed fontawesomepro 5.15.3, but when I collectstatic it shows 6.0.0-beta1
