### ISSUE TITLE
Icon request: fa-share-flipped-h (undo alt)

### ISSUE THREAD

**Issue by rugk** [FortAwesome/Font-Awesome#17803]
**What can it be used for?**
Used together with `undo`, when `undo` icon is used for rotation of elements

**Example image (optional)**
![image](https://user-images.githubusercontent.com/556268/127731283-68b07496-88da-4a04-849c-a789d312ea63.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that you can use a flipped version of [fa-share](https://fontawesome.com/icons/share?style=solid)

https://jsfiddle.net/tagliala/zvkwmf1L/3/

**Comment by rugk** [comment]
Thanks, that's a good workaround of course! :smiley:

**Comment by rugk** [comment]
Why was this issue closed?

This…
> I think that you can use a flipped version of fa-share

…was only a workaround. A good one, possibly, but still not a solution for the underlying problem.

IMHO, the underlying problem is still not fixed.

**Comment by tagliala** [comment]
@rugk will transform this request into an icon request

**Comment by aethior** [comment]
Hi,

`fa-reply`: https://fontawesome.com/icons/reply (*the atached image in the first post*)
`fa-share`: https://fontawesome.com/icons/share

Regards.
