### ISSUE TITLE
Apply font-awesome spinner in ::before or ::after doesn't work

### ISSUE THREAD

**Issue by afillion** [FortAwesome/Font-Awesome#17810]
**Describe the bug**
I use pseudo-element ::after or ::before to put font-awesome icon with unicode icon in content property of pseudo-element.
It's working as expected, but not for spinner icon.
See :

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I use pseudo-element ::after or ::before to put font-awesome icon with unicode icon in content property of pseudo-element.

This is not supported by browsers

Demo without Font Awesome: https://jsfiddle.net/tagliala/3y76jcg1/3/

Hope it helps

Closing here

**Comment by afillion** [comment]
This is working on Chrome & Firefox ! 
![image](https://user-images.githubusercontent.com/16117496/114305201-58006880-9ad7-11eb-81c4-22441c00e5fc.png)
