### ISSUE TITLE
BUG : Mastodon icon can't appear when i use unicode

### ISSUE THREAD

**Issue by engkrek** [FortAwesome/Font-Awesome#17811]
**mastodon icon can't appear when I call it with unicode**
I want to use mastodon icon with unicode ( `&#xf4f6;` ) because I can't use fontawesomes icon in option in select. So, i use the unicode. Whatsapp, Twitter, envelope and Telegram icons works well, while Mastodon not. I tried it with span, without span (just unicode) and combine span and unicode, but still not solved

**To Reproduce**
Just paste it on 'register.html' in adminLTE 3.1.0
```
<div class="input-group mb-3">
        <div style="width: 68px;">
          <select class="form-control unit" id="pilihan" name="medsos" style="font-family: 'FontAwesome'; font-size: 16pt;" onchange="chg_kontak()">
            <option selected disabled class="fas">&#xf0c0;</option>
            <option value="telegram" class="fab">&#xf2c6;</option>
            <option value="whatsapp" class="fab">&#xf232;</option>
            <option value="email" class="fal">&#xf0e0;</option>
            <option value="mastodon" class="fab">&#xf4f6;<span class="fab fa-mastodon"></span></option>
            <option value="twitter" class="fab">&#xf099;</option>
          </select>
        </div>
        <input type="text" class="form-control" id="oth_contact" name="oth_contact" placeholder="kontak lain" required disabled onfocus>
        <div class="input-group-append nanggung" id="dikit">
          <div class="input-group-text">
          </div>
        </div>
      </div>
```

**Expected behavior**
Mastodon icon can appear after I choose it (the mastodon option on select box)

**Version and implementation**
Version: 5.15.2 and 5.15.3
Browser and version: Chromium (89.0.4389.114)

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate.
CSS Demo (5.15.3): https://jsfiddle.net/tagliala/ajLpzuf8/2/

[mastodon](https://fontawesome.com/icons/mastodon?style=brands) has been introduced in Font Awesome 5.8.0, so please double check that you are using Font Awesome 5.8.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Two more things:

> adminLTE 3.1.0

We do not provide support for third-party software

> `<option value="mastodon" class="fab">&#xf4f6;<span class="fab fa-mastodon"></span></option>`

This is not a supported use case and you should implement a different solution if you need macOS support. On macOS, select box dropdown is rendered natively and cannot use webfonts. Ref: #996

Hope it helps

Closing here
