### ISSUE TITLE
Icon request: eBay logo

### ISSUE THREAD

**Issue by ntom** [FortAwesome/Font-Awesome#1783]
Icon request: eBay logo

**Comment by dzoladz** [comment]
+1

**Comment by ingenuitor** [comment]
+2.5675 maybe even just the entire alphabet / keyboard layout, then we could really have fun.

**Comment by baimeizhong** [comment]
+1 ebay icon

**Comment by lcp2000** [comment]
+1 +2 +3

**Comment by tamardesign** [comment]
+1

**Comment by minhaj-resgef** [comment]
+1

**Comment by viktorgino** [comment]
+1 +2 +3

**Comment by rentrop** [comment]
+1

**Comment by minhaj-resgef** [comment]
yeah thanks

**Comment by TJohnson93** [comment]
+1

**Comment by stockwerk** [comment]
+1

**Comment by nadiTime** [comment]
+1

**Comment by humpfle** [comment]
+1

**Comment by craigerskine** [comment]
+1

**Comment by stonecold123** [comment]
+1

**Comment by miguelrincon** [comment]
+1

**Comment by daverich204** [comment]
+1

**Comment by jtrienekens** [comment]
+1

**Comment by andrescastillodf** [comment]
+1

**Comment by GarPit** [comment]
+1

**Comment by rbrugnollo** [comment]
+1

**Comment by hajjat** [comment]
+1
Please add eBay and Microsoft!

**Comment by jeshurun** [comment]
Microsoft icon is already available:
https://fortawesome.github.io/Font-Awesome/icon/trash/

**Comment by rcluke** [comment]
+1

**Comment by loppis** [comment]
+1
we really need this :)

**Comment by Joe-Peterson** [comment]
please

**Comment by juannenna** [comment]
+1 please :)

**Comment by JTuwiner** [comment]
+1

**Comment by xvilo** [comment]
+1

**Comment by autopten** [comment]
Amazon & PayPal icon, but no eBay? That's weird... When is the eBay icon coming? +1

**Comment by Vahn84** [comment]
lol, i was sure that the ebay icon was there. I can't imagine one single reason for it not being listed as others

+1 for god sake

**Comment by JTPlatnum** [comment]
+1

**Comment by CristianOG** [comment]
+1

**Comment by tp303** [comment]
+1

**Comment by daverich204** [comment]
+1

**Comment by hugnat** [comment]
Is there an Ebay icon in FontAwesome yet?

**Comment by hugnat** [comment]
+1

**Comment by salopot** [comment]
+1

**Comment by Alex12321** [comment]
+1

**Comment by mtin79** [comment]
+1

**Comment by hudhaifas** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by timeceeper** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by qibolun** [comment]
+1

**Comment by zhouzr** [comment]
+1

**Comment by frantique** [comment]
+1

**Comment by Emalton** [comment]
+1

**Comment by mattw3003** [comment]
+1

**Comment by Parker1090** [comment]
+1

**Comment by jlahijani** [comment]
+1

**Comment by sprakashtd** [comment]
+1

**Comment by xvilo** [comment]
+1

**Comment by hasangursoy** [comment]
We're waiting for ebay icon :)

**Comment by GaryStanton** [comment]
+1

**Comment by leahcodes** [comment]
+1

**Comment by hrbocutti** [comment]
+1 eBay, Rakuten, Sears ...

**Comment by objoe** [comment]
+1

**Comment by FireFoxII** [comment]
+1

**Comment by sascha1337** [comment]
+1

**Comment by dgwaldo** [comment]
+1

**Comment by hafnis** [comment]
+1

**Comment by joebos** [comment]
+1

**Comment by nacoleman** [comment]
+1

**Comment by jamston** [comment]
+1 ebay

**Comment by timramseyjr** [comment]
+1

**Comment by johnwc** [comment]
+1

**Comment by BenLewisWatson** [comment]
+1

**Comment by LorenzoRogai** [comment]
+1

**Comment by ristaumedia** [comment]
+1

**Comment by wdmtech** [comment]
+1

**Comment by marcospgp** [comment]
+1

**Comment by JustDevZero** [comment]
+1

**Comment by Muccitas** [comment]
+1

**Comment by Siebertron** [comment]
Just wanted to +1 this. I'm surprised this hasn't happened yet. Hopefully in Font Awesome 5.

**Comment by GaryStanton** [comment]
It's been three and a half years - at this point I can only assume there's some kind of licensing issue preventing this.

**Comment by Siebertron** [comment]
I'm assuming as much as well, but am still hoping. Fingers and eyes crossed!

**Comment by autofab** [comment]
+1

**Comment by maykino** [comment]
Where is the ebay icon? +1

**Comment by RandomArray** [comment]
+1

**Comment by Tech-CF** [comment]
+1; the logo or the ebay 'e'

**Comment by densenator** [comment]
+1

**Comment by disruptek** [comment]
:thumbsup: eBay

**Comment by skollro** [comment]
+1

**Comment by temkagordin** [comment]
+

**Comment by kimhjona** [comment]
+1 ebay icon please

**Comment by LucaColombi** [comment]
👍 +1 

WTF? Is not here?

**Comment by alexanderdejong** [comment]
+1

**Comment by GarageWeb** [comment]
+1

**Comment by xvilo** [comment]
Four years later and no Ebay icon. I know they are busy with FA-5. But this is jus ridiculous.

**Comment by visualpharm** [comment]
I've started a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The eBay icon is here](https://icons8.com/icon/31080/ebay).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), [clean](https://github.com/FortAwesome/Font-Awesome/issues/239#issuecomment-304473340) and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by mraburn** [comment]
+1

**Comment by Reconix** [comment]
+1

**Comment by cmunden** [comment]
👍 

Some variation of either this:

![image](https://user-images.githubusercontent.com/705833/27867560-97ebd34e-6174-11e7-93a2-c1511d19a766.png)

or this:

![image](https://user-images.githubusercontent.com/705833/27867607-c71120ac-6174-11e7-8547-6c2db8359796.png)

**Comment by dhm80** [comment]
+1

**Comment by mrcily** [comment]
+1 for ebay icon

**Comment by vinsbg** [comment]
4 years later and no ebay icon. That's sad.

**Comment by dhm80** [comment]
+1

**Comment by ajhar** [comment]
+1

**Comment by JohnJonnyJohn** [comment]
+1

**Comment by hotmachiato** [comment]
+1

**Comment by dfranczuk** [comment]
+1

**Comment by keithieopia** [comment]
+1

**Comment by nanotron** [comment]
+1

**Comment by timtjtim** [comment]
+1

**Comment by skcin7** [comment]
+1

**Comment by ChangePlaces** [comment]
I get the feeling this is never going to happen judging by how old it is!

**Comment by nathan-dealerwebs** [comment]
I still can't believe this hasn't been done. Could absolutely use this right now.

**Comment by GaryStanton** [comment]
Give it up, it's been 4 years.

**Comment by cmunden** [comment]
eBay favicon
![image](https://user-images.githubusercontent.com/705833/32376965-3ffd6340-c089-11e7-86dd-a26eaff7c87a.png)

font-awesome suitcase
![image](https://user-images.githubusercontent.com/705833/32376996-5506ab3e-c089-11e7-9d35-053a09465578.png)

Close enough for me... been using it and one ever yet has cared enough to question me on it.  Moving on. 😉

**Comment by ChangePlaces** [comment]
it's a shopping bag, not a suitcase

**Comment by YuvalPruss** [comment]
+1

**Comment by ChangePlaces** [comment]
people, instead of +1 spam, we have the "thumbs up emotion". let's use it, huh?

**Comment by IDLe-Engineering** [comment]
+1 for eBay

**Comment by ChangePlaces** [comment]
people - please stop with +1. github have introduced the thumbs up on the comment you agree with. so all subscribers who get excited thinking it's been sorted only to find "+1".

use the thumbs up by clicking the smiley face on a comment

**Comment by talbs** [comment]
https://fontawesome.com/icons/ebay

**Comment by talbs** [comment]
> as awsome as this is, it's a shame you didn't keep with the actual logo rather than the brand name, e.g. amazon is an 'a' with a "smile" underneath it. If I want "ebay" written out, I'll write it out!

Yep, as @johnwc notes, this is the official eBay logo now. Its our standard practice to use the official logo when it is specified and available. Sadly, there's no official abbreviated version of this (i.e. the eBay "e"). Thanks for understanding, @ChangePlaces.

**Comment by ChangePlaces** [comment]
@talbs thanks for the explanation! it's a sad situation, but good work on the icon!

**Comment by johnwc** [comment]
Only thing that would make it better is if web fonts supported color. :-)
