### ISSUE TITLE
FA website "Space" icon category link doesn't work

### ISSUE THREAD

**Issue by mbomb007** [FortAwesome/Font-Awesome#17840]
**Describe the bug**
Clicking the Space category link shown on the Kit use page (`https://fontawesome.com/kits/[KIT]/use`) doesn't work, shown below.

**To Reproduce**
The link goes here: https://fontawesome.com/icons?d=gallery&p=1&c=space

No icons show up in the results.

**Expected behavior**
Space-related icons should show

**Screenshots**
![Capture](https://user-images.githubusercontent.com/22807401/115734142-15e4eb80-a34f-11eb-85ca-7bde2d7d7b35.PNG)

**Bug report checklist**
- [x ] I have filled out as much of the above information as I can
- [x ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm the issue

@talbs could you please check?

**Comment by talbs** [comment]
Thanks for pointing this broken link out and apologies for the dust that has collected here. This should be resolved shortly!

**Comment by talbs** [comment]
Okay, gang. This should be resolved and the broken link should point to https://fontawesome.com/v5.15/icons?q=space.
