### ISSUE TITLE
Icon request: icon- telephon

### ISSUE THREAD

**Issue by masayuki272** [FortAwesome/Font-Awesome#17845]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

**Comment by aethior** [comment]
Currently there are alot of telephone icons...

`fa-phone`: https://fontawesome.com/icons/phone
`fa-phone-rotary`: https://fontawesome.com/icons/phone-rotary
`fa-phone-office`: https://fontawesome.com/icons/phone-office
`fa-phone-intercom`: https://fontawesome.com/icons/phone-intercom

Regards.

cc/ @tagliala
