### ISSUE TITLE
Icon request: naira currency symbol 

### ISSUE THREAD

**Issue by HuziTaiwo** [FortAwesome/Font-Awesome#17853]
**What can it be used for?**
I'm currently working on an E-commerce website and I really need the naira sign to complete my work, therein some products that the price will be converted to naira. I really love fontawesome.com icon and I'm obsessed with it, using other icons doesn't make my work awesome 

**Example image (optional)**
![32974-removebg-preview](https://user-images.githubusercontent.com/75940823/116251089-3b666080-a766-11eb-980f-c96ed582802e.png)
**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by HuziTaiwo** [comment]
I'd love to see the icon available the next time I look for more awesomeness in fontawesome.com

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in 6.0.0.alpha1 (private alpha for Pro customers), as per #1969

I'm pretty sure this will also be part of the public betas and the final FA 6.0 Free release

Closing here
