### ISSUE TITLE
Icon Request: icon-OA_home

### ISSUE THREAD

**Issue by Alice3331** [FortAwesome/Font-Awesome#17856]
![OA_home](https://user-images.githubusercontent.com/83323127/116336514-44f5d400-a80b-11eb-932a-9bb58bfe4591.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have different home icons, both for Free and for Pro, and they will also change in FA6:
- https://fontawesome.com/icons?d=gallery&p=2&q=home

Could you please clarify this request?

Meanwhile, closing here
