### ISSUE TITLE
Icon request: confetti-cannon

### ISSUE THREAD

**Issue by austin-event-penguin** [FortAwesome/Font-Awesome#17877]
**What can it be used for?**
Using icons to describe a party or to say congratulations.

**Example image (optional)**
[:tada:](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/mozilla/36/party-popper_1f389.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We just added this to version 6: https://fontawesome.com/v6.0/icons/party-horn?s=solid
