### ISSUE TITLE
Icon request: Balloon

### ISSUE THREAD

**Issue by austin-event-penguin** [FortAwesome/Font-Awesome#17878]
**What can it be used for?**
For a party or calibration

**Example image (optional)**
:balloon:

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This will be available in FA6 (still don't know if also for Free)

https://github.com/FortAwesome/Font-Awesome/issues/3398#issuecomment-810392259
