### ISSUE TITLE
Icon Request: fa-briefcase-arrow-left, fa-briefcase-arrow-right

### ISSUE THREAD

**Issue by juliusbanting** [FortAwesome/Font-Awesome#17873]
Hello Font Awesome,

I am creating an inventory system, and I need an icon for (item out) and (item in) buttons. 

I am hoping for your consideration,

Thank you & God Bless,

![ico-item-management-item-issue-1](https://user-images.githubusercontent.com/26789155/116955244-8c290c80-acc4-11eb-86c6-597f11fd9a3e.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/524/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
We've added the first option to version 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=briefcase&s=solid&c=new-in-v6. Easiest way to get the second option would be to add an `fa-flip-horizontal` class.
