### ISSUE TITLE
Icon request: malt

### ISSUE THREAD

**Issue by Pyrrha** [FortAwesome/Font-Awesome#17888]
**What can it be used for?**
Malt is a great French plateform for freelances. The usage is the same as another social icon, such as LinkedIn, and will probably be used to link Malt profiles on other applications.

**Example image (optional)**
![Malt](https://user-images.githubusercontent.com/23195290/88169086-bcaf2680-cc1b-11ea-8b41-d115efe212a5.png "Malt")

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) ~~and to the best of my knowledge this is not a duplicate~~ #14700 was not well formatted regarding to contribution guidelines
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> was not well formatted regarding to contribution guidelines

Thanks for providing a better request, but as far as the request can be unequivocally associated to a concept/brand, then it is fine

Feel free to use and 👍🏼 #14700, it already has some +1s and they help
