### ISSUE TITLE
Icon request: envelope-circle

### ISSUE THREAD

**Issue by harryaravind** [FortAwesome/Font-Awesome#17899]
**What can it be used for?**
It can be used to represent messages received notification. This icon is with a circular background which is not there in the icon pack right now

**Example image (optional)**

![New email indicator (1)](https://user-images.githubusercontent.com/76443558/118235695-bd6abf00-b4b2-11eb-9e64-e8b8b76c6d3c.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be part of Font Awesome 6, now in private alpha for Pro customers. I don't know if this icon will make it for the Free set.

Please also keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/526/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
