### ISSUE TITLE
Icon Change Request: Quran should be facing RtL direction

### ISSUE THREAD

**Issue by timtjtim** [FortAwesome/Font-Awesome#17890]
Quran icons currently face towards the right, as a LtR book does. The Quran is traditionally written in Arabic, a RtL script.

I think it should probably face towards the left, the same direction as the Tanakh (traditionally written in Hebrew, also a RtL script).

![F5A22668-2040-4481-B911-8F2786F98173](https://user-images.githubusercontent.com/6292691/117852916-bf007100-b27f-11eb-9d28-d345d59378ef.png)
![5C437769-1E33-48AD-8D6A-453A6E9EBB0A](https://user-images.githubusercontent.com/6292691/117852920-c0319e00-b27f-11eb-8ca6-e1a192b20044.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by frrrances** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this. We've already fixed it in our Version 6 Beta and will be updating the Version 5 icon in an upcoming release!

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/book-quran?f=classic&s=solid)

**Comment by tagliala** [comment]
> it already exists in Font Awesome Pro! 

In FA Free too, as a religious icon it's available in the free set

Ref: https://jsfiddle.net/tagliala/v9hn342s/2/
