### ISSUE TITLE
"Hosting Font Awesome Yourself" Package allow and dont allow you to use it for free at the same time.

### ISSUE THREAD

**Issue by VincentJOBS** [FortAwesome/Font-Awesome#17891]
I am currently programming my website which I use with Wordpress and OceanWP as a theme. Today I made a research about the icons which OceanWP and thus thousands of users (commercial or not) use. What unfortunately comes across to me quite contradicting is that on the website of the icon provider https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself it is said that the CSS and JS files named:
**"regular.css, light.css, regular.js and light.js"** can only be used with Pro. But if you download the free package at the beginning of the page, these files are included and the license says: 

    Font Awesome Free is free, open source, and GPL friendly. You can use it for
    commercial projects, open source projects, or really almost whatever you want.
    Full Font Awesome Free license: https://fontawesome.com/license/free.
    
    # Icons: CC BY 4.0 License (https://creativecommons.org/licenses/by/4.0/)
    In the Font Awesome Free download, the CC BY 4.0 license applies to all icons
    packaged as SVG and JS file types.
    
    # Fonts: SIL OFL 1.1 License (https://scripts.sil.org/OFL)
    In the Font Awesome Free download, the SIL OFL license applies to all icons
    packaged as web and desktop font files.
    
    # Code: MIT License (https://opensource.org/licenses/MIT)
    In the Font Awesome Free download, the MIT license applies to all non-font and
    non-icon files. 

And, if it were only allowed to use it under Pro, OceanWP, for example, would make itself punishable on their own website.

**Can someone help me and solve the mystery of whether I can incorporate and use the orders as a whole commercial?**

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> "regular.css, light.css, regular.js and light.js" can only be used with Pro. But if you download the free package at the beginning of the page, these files are included

Could you please double check? That file should include regular.js and regular.css, but not light.*

This is not the first report about this section of the documentation. The fact is that **some** regular icons are part free set, but the whole regular icon isn't. FA5's Free regular icons are all FA4's outlined icons and some new useful additions

Example:
- https://fontawesome.com/icons/star?style=regular is available for Free (you don't see the "Pro" label under the regular version)
- https://fontawesome.com/icons/home?style=regular is not available for Free

![image](https://user-images.githubusercontent.com/556268/117996768-b886fd80-b342-11eb-8c7a-2be193ffa978.png)

Hope it helps to clarify

@talbs any chance to improve this part of the documentation?

![image](https://user-images.githubusercontent.com/556268/117997136-04d23d80-b343-11eb-9946-c09dd71bac45.png)

**Comment by VincentJOBS** [comment]
Many thanks for the quick response,
You are right the "light documents" aren't included. I assume that the downloaded folder only contains those regular (icons and files) that I can also use for free and for commercial purposes.
Am I right?

**Comment by tagliala** [comment]
> You are right the "light documents" aren't included. I assume that the downloaded folder only contains those regular (icons and files) that I can also use for free and for commercial purposes.
> Am I right?

Correct! Feel free to use any icon you find in the downloaded free package for commercial purposes

**Comment by tagliala** [comment]
Closing here
