### ISSUE TITLE
icon request: circle-half, circle-quarter, circle-third, etc

### ISSUE THREAD

**Issue by kriswill** [FortAwesome/Font-Awesome#1789]
It would be awesome - to be able to compose circular icons with parts of circles.  

Examples might include:
- multiple colors applied to quarters/halves of a circle icon
- compose a multi-colored pie-chart icon _(maybe even pie-slice icons?)_
- compose custom spinners

**Comment by andrepearce** [comment]
+1

**Comment by memeplex** [comment]
There are empty, quarter, half, three-quarter and full circles in unicode geometric section.
