### ISSUE TITLE
Icon request: Update discord

### ISSUE THREAD

**Issue by iHildy** [FortAwesome/Font-Awesome#17897]
**What can it be used for?**
Discord's logo

**Example image (optional)**
![image](https://user-images.githubusercontent.com/25069719/118152463-58dc3100-b3da-11eb-9540-ed9349ea1af7.png)

They updated their logo today: https://discord.com/brand-new/branding

**Comment by HilbertGilbertson** [comment]
Was just about to post the same.

Before:
<img src="https://discord.com/assets/41484d92c876f76b20c7f746221e8151.svg" width="100">

After:

![](https://discord.com/assets/202a6a6b9646ea62c7587850aa83be4f.svg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for bringing this to our attention.

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Yup. We'll get this in the next release!

**Comment by HilbertGilbertson** [comment]
I'm glad to see the new Discord icon now already in the FontAwesome 6.0~beta1 release (which is indeed ridiculously good looking). I'm sure it will follow in the next v5 update soon enough.

**Comment by sensibleworld** [comment]
Yup. It's queued up already for the next v5 update :)

**Comment by Panquesito7** [comment]
Glad to hear it's going to get updated! 😄

**Comment by Miodec** [comment]
Any estimates on when we can expect this update to be released?

**Comment by trustedmercury** [comment]
Yep, when is this going to launch publicly?

**Comment by milanmdev** [comment]
^ - would like to see this on my site :)

**Comment by trustedmercury** [comment]
Just noticed that it's been updated on the site, thanks!

**Comment by tagliala** [comment]
Thanks for the heads-up, closing here
