### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by vungocanh1989** [FortAwesome/Font-Awesome#17919]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
For footer of website
**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/84608709/119212393-d6541100-ba6c-11eb-9489-a74d022c4751.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Discord icon is already available:
- https://fontawesome.com/icons/discord?style=brands

Also, there is a request to update the brand icon as per #17897 

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
