### ISSUE TITLE
Icon request: bangladeshi-taka

### ISSUE THREAD

**Issue by mabromuela88** [FortAwesome/Font-Awesome#17924]
**What can it be used for?**
This is for easily using the icon to represent Bangladeshi currency.

**Example image (optional)**
![Capture](https://user-images.githubusercontent.com/84679362/119270603-528e5600-bc1f-11eb-9925-d4b9f298fe07.PNG)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)

- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be part of FA6, as per #1719.

Stay tuned!
