### ISSUE TITLE
Can't authenticate to npm.fontawesome.com when on another user or another computer

### ISSUE THREAD

**Issue by phos-dev** [FortAwesome/Font-Awesome#17921]
**Describe the bug**
I am working fine with my current computer, but want to work on the other one. I tried `npm install`, but got "401 unauthorized". The same occurs if I create a new user on my current computer and try to do the same.

**To Reproduce**
When I did `npm install` and `npm ci`.

**Expected behavior**
Install successfully like my main user.

**Screenshots**
![image](https://user-images.githubusercontent.com/38169759/119213422-41b1d900-ba95-11eb-972c-5834598a33d7.png)

**Version and implementation**
My `.npmrc`:
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=TOKEN
```

I am getting 401 on all these packages.
```
"@fortawesome/fontawesome-pro": "^5.15.3",
"@fortawesome/fontawesome-svg-core": "^1.2.35",
"@fortawesome/free-brands-svg-icons": "^5.15.3",
"@fortawesome/free-regular-svg-icons": "^5.15.3",
"@fortawesome/free-solid-svg-icons": "^5.15.3",
"@fortawesome/pro-duotone-svg-icons": "^5.15.3",
"@fortawesome/pro-light-svg-icons": "^5.15.3",
"@fortawesome/pro-regular-svg-icons": "^5.15.3",
"@fortawesome/pro-solid-svg-icons": "^5.15.3",
"@fortawesome/react-fontawesome": "^0.1.14"
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If the very same license works on another computer, then this could be a configuration issue

If you are using npm, please provide the full output of `npm install --verbose`, having care of removing any sensitive information

Then, you should see something like

```
npm timing config:load:file:/Users/user/.nvm/versions/node/v14.16.1/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:file:/Users/user/fa5pro/.npmrc Completed in 1ms
npm timing config:load:file:/Users/user/.npmrc Completed in 1ms
```

Please double check that the proper npm configuration is loaded and has priority over others

If you still have issues, please send an email at hello@fontawesome.com to get dedicated Pro support

Closing here, but feel free to comment

**Comment by phos-dev** [comment]
I got that(Ignoring some things), in that same order: 
```
npm info using npm@7.14.0
npm info using node@v14.17.0
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
npm timing config:load:file:/home/user/Projects/Project1/.npmrc Completed in 1ms
npm timing config:load:file:/home/user/.npmrc Completed in 0ms
```
Is the ` /home/user/.npmrc`  overwriting the Project1 `.npmrc`?

**Comment by tagliala** [comment]
> Is the /home/user/.npmrc overwriting the Project1 .npmrc?

It should not. If you confirm that `/home/user/Projects/Project1/.npmrc` contains the proper credentials and they are exactly the same of the working computer, please ask for dedicated support at hello@fontawesome.com 

You can add a reference to this issue
