### ISSUE TITLE
Icon request: cart-outline

### ISSUE THREAD

**Issue by dtran2108** [FortAwesome/Font-Awesome#17922]
**What can it be used for?**
This could be use for shopping pages to display the items in the user's cart (it's an regular icon for the existing cart solid icon)

**Example image (optional)**
![image](https://user-images.githubusercontent.com/43706393/119217037-bde20600-bb01-11eb-9650-afde9cc2b3f1.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by phuze** [comment]
The `light` version of `shopping-cart` is what you're looking for.
https://fontawesome.com/icons/shopping-cart?style=light
