### ISSUE TITLE
travel

### ISSUE THREAD

**Issue by sayarkunggyi** [FortAwesome/Font-Awesome#17937]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a whole category for travel icons: https://fontawesome.com/v5.15/icons?d=gallery&p=2&c=travel

If you have something specific in mind, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) having care of providing a good title and an example

Closing here
