### ISSUE TITLE
Icon request: jain-om

### ISSUE THREAD

**Issue by ManasMadrecha** [FortAwesome/Font-Awesome#17935]
**What can it be used for?**
It represents Jainism religion's Om version. 

**Example image (optional)**
https://commons.wikimedia.org/wiki/File:Om_ja%C3%AFn_orange.svg

UNICODE A8FD: ꣽ

![image](https://user-images.githubusercontent.com/65993481/119629764-f0567080-be2b-11eb-9d16-c85a4ea33ac0.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that this symbol is different from #3522, but we have the same title

Could you please elaborate the differences and provide a different title for this request, if it is not a duplicate?

**Comment by ManasMadrecha** [comment]
The already existing ॐ is called om which basically denotes God. 

But, the above image though pronounced as om, has totally different  history, connotation, meaning, etc. It relates to **Jainism** religion, whereas ॐ relates to Hinduism religion. https://en.wikipedia.org/wiki/Jainism

The `jain-om` represents a combination of 5 alphabets A + A + A + U + M (the _panch paramesthi_ or five supreme beings), 
1. **A**rihant
2. **A**sharira (siddha)
3. **A**charya
4. **U**padhyaya
5. **M**uni

(Their translations and more info here: https://en.wikipedia.org/wiki/Pañca-Parameṣṭhi#Overview)

So, merging of A + A + A + U + M results in pronunciation same as Om, but it denotes something totally different.

More info can be found here: https://en.wikipedia.org/wiki/Om#Jainism

### Title
It can be `jain-om` or `jainism-om`. If the former may conflict with some potential brand called jain, then latter is also fine. 

-----

### Need
1. the normal Om can be written easily on keyboard using <kbd>windows</kbd> + <kbd>.</kbd> like this ॐ, whereas there's genuine need for the jainism-om to have an icon. 
2. Currently, there is not a single icon for Jainism religion in the nonetheless awesome library of FontAwesome. So, having `jainism-om` would be a good start.

**Comment by tagliala** [comment]
Thanks for the thorough clarification

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
