### ISSUE TITLE
Duotone screwdriver-wrench alignment off

### ISSUE THREAD

**Issue by Jas-n** [FortAwesome/Font-Awesome#17945]
**Describe the bug**
The darker screwdriver-wrench layer on the duotone icon seems higher than it should be over the opaque layer.

**To Reproduce**
Search for screwdriver-wrench on [DuoTone icons](https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=setting&s=duotone)

**Expected behavior**
The screwdriver should sit nicely between the gap on the wrench

**Screenshots**
![image](https://user-images.githubusercontent.com/14942820/119789900-5fcf6d00-becb-11eb-89f2-628d85afb983.png)

**Version and implementation**
Version: 6.0 beta 1
Browser and version: [What's My Browser](https://www.whatsmybrowser.org/b/08GZ2)

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks!

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Fixed in 6.4.0: https://fontawesome.com/icons/screwdriver-wrench?f=classic&s=duotone&sc=%231E3050
