### ISSUE TITLE
Icon request: color picker

### ISSUE THREAD

**Issue by anonymuos1** [FortAwesome/Font-Awesome#1794]

**Comment by AjiMIde** [comment]
+1

**Comment by remypar5** [comment]
+1

**Comment by w3l** [comment]
+1

**Comment by webprom** [comment]
it is implemented and called fa-eyedropper

**Comment by sensibleworld** [comment]
I think we have a few options now that should work for this :) 
https://fontawesome.com/icons?d=gallery&q=color
