### ISSUE TITLE
Upgrading from version 4 documentation is missing content

### ISSUE THREAD

**Issue by boondaburra** [FortAwesome/Font-Awesome#17951]
Since release of the v6 beta update, the [Upgrading from Version 4](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4) page is missing all of its content

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign both @talbs and @robmadole

**Comment by robmadole** [comment]
Great! Thank you. We'll get this fixed tomorrow.

**Comment by robmadole** [comment]
We're deploying this fix now. Will be just a bit.

**Comment by robmadole** [comment]
All fixed now. Thanks @boondaburra for reporting this.
