### ISSUE TITLE
code-compare rendering misaligned

### ISSUE THREAD

**Issue by markkraft** [FortAwesome/Font-Awesome#17958]
**Describe the bug**
The new `code-compare` icon seems misaligned (not 90°, as the other weights) in regular weight and a gap is visible where the arrows connect in the light weight.

**To Reproduce**
https://fontawesome.com/v6.0/icons/code-compare?s=regular
https://fontawesome.com/v6.0/icons/code-compare?s=thin

**Screenshots**
<img width="699" alt="fa-code-compare-regular" src="https://user-images.githubusercontent.com/26097927/120227201-ffcd2380-c248-11eb-9afd-a42c9163682c.png">
<img width="679" alt="fa-code-compare-light" src="https://user-images.githubusercontent.com/26097927/120227189-fba10600-c248-11eb-9915-d6fcd812df14.png">

**Version and implementation**
Version: 6.0.0-beta1
Browser and version: Opera

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This is job for @sensibleworld!

**Comment by sensibleworld** [comment]
Gah! Thanks for the report. Will get it fixed in the next release.

**Comment by markkraft** [comment]
Sure, my pleasure ☺️  Thanks for all the good work and superb development 👍

**Comment by tagliala** [comment]
I think this has been fixed in 6.0.0-beta2

https://fontawesome.com/v6.0/icons/code-compare?s=solid

Please let me know if I'm wrong
