### ISSUE TITLE
Icon request: delivered

### ISSUE THREAD

**Issue by deadmann** [FortAwesome/Font-Awesome#17966]
**What can it be used for?**
This can be useful in dashboards and menus

**Example image (optional)**
Insert the example image here if necessary.
https://image.flaticon.com/icons/png/512/1337/1337104.png
https://cdn1.iconfinder.com/data/icons/ios-edge-line-3/25/Delivered-512.png
https://www.pngfind.com/pngs/m/371-3716341_package-delivery-svg-png-icon-free-download-transparent.png
https://cdn4.iconfinder.com/data/icons/shopping-e-commerce-43/64/x-47-512.png

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm going to rename this as `fa-truck-check`

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/543/

Please also consider [fa-box-check](https://fontawesome.com/v5.15/icons/box-check?style=solid) for this use case

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
We already have this icon: https://fontawesome.com/v6.0/icons/box-circle-check?s=solid

Does that work for this case?

**Comment by deadmann** [comment]
> We already have this icon: https://fontawesome.com/v6.0/icons/box-circle-check?s=solid
> 
> Does that work for this case?

that looks good. although it's not readable in the first look

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
