### ISSUE TITLE
Duotone square-xmark is missing the square

### ISSUE THREAD

**Issue by markkraft** [FortAwesome/Font-Awesome#17961]
**Describe the bug**
The duotone icon `square-xmark` is missing the square.

**To Reproduce**
https://fontawesome.com/v6.0/icons/square-xmark?s=duotone

**Screenshots**
<img width="1167" alt="square-xmark" src="https://user-images.githubusercontent.com/26097927/120241827-dec5fc00-c263-11eb-9d9c-01e20376f2e7.png">

**Version and implementation**
Version: 6.0.0-beta1
Browser and version: Opera

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this.

Let's assign @sensibleworld 

@sensibleworld I'm checking the PR with the 6.x icon fixes to make sure these issues have not been fixed upstream. This does not appear the case

**Comment by sensibleworld** [comment]
Thank for the report. This actually looks related to another bug we're dealing with related to duotone icon rendering in browsers like Chrome and Opera, specifically in regards to pseudo elements. We're working on a fix.

(If you view the above link in either Safari or Firefox, the icon renders as expected.)

**Comment by sensibleworld** [comment]
This should be fixed now!
