### ISSUE TITLE
Icon Request: rounded-triangle (sign-blank)

### ISSUE THREAD

**Issue by orzoe** [FortAwesome/Font-Awesome#1796]
Think it would be nice to have a rounded-triangle icon, similar to the base of icon-warning-sign, so it can be used as a stack base like the basic circle and square. 

e.g.
![screen shot 2013-08-16 at 6 21 57 pm](https://f.cloud.github.com/assets/3590257/979110/a190008e-06db-11e3-821e-ecfc9d022ebe.png)

Thanks in advance!

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/triangle?s=solid
