### ISSUE TITLE
Icon request: processing-<x>

### ISSUE THREAD

**Issue by deadmann** [FortAwesome/Font-Awesome#17968]
**What can it be used for?**
This icon should indicate if a topic, data, or item, is in middle of processing by the team, or machine or ... (my current intent is the logistic environment, but even other than that, we only have a CPU like `Chip` icon within the list of icons.

**Example image (optional)**
I include many processing icon in different means include processing, file processing, item processing, logistic processing...
Also note that we have few Icon alike `fa-shipment-fast`, but I rather use it for buttons to send items.

https://th.bing.com/th/id/OIP.EngJEOFQDfwXaD2jy1U_HAHaJQ?pid=ImgDet&rs=1
https://cdn4.iconfinder.com/data/icons/document-26/64/batch_processing-512.png
https://image.flaticon.com/icons/png/512/1925/1925166.png
https://image.flaticon.com/icons/png/512/1122/1122371.png
https://cdn4.iconfinder.com/data/icons/3d-modeling-printing-volume-2/64/file-processing-512.png
http://cdn.onlinewebfonts.com/svg/img_358925.png
https://th.bing.com/th/id/OIP.mGIFKnfWYZzPVvnMaiqT9AHaHa?pid=ImgDet&rs=1
https://cdn1.iconfinder.com/data/icons/industry-and-manufacturing-solid-line-processing/512/conveyer-512.png
https://cdn2.iconfinder.com/data/icons/logistics-delivery-3-3/66/141-512.png
https://cdn2.iconfinder.com/data/icons/logistics-delivery-5-1/66/224-512.png
https://cdn0.iconfinder.com/data/icons/logistics-4/512/production-256.png
https://th.bing.com/th/id/OIP._EiG8QdNYInihZv94qA-vwHaHa?pid=ImgDet&rs=1
https://th.bing.com/th/id/OIP.oVXEQfNnXzYDm1eyzN7-OQHaHa?pid=ImgDet&rs=1
https://cdn1.iconfinder.com/data/icons/business-e-commerce-logistics-outline-set-1/91/Business_E-commerce__Logistics_53-512.png
https://cdn4.iconfinder.com/data/icons/logistics-and-shipping-9/48/Logistics_expand-10-512.png
http://cdn.onlinewebfonts.com/svg/img_308640.png

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by deadmann** [comment]
In my icon I tried to target a global scenario, finding icons in different categories...

but actually something like this, showing the package moving from a source to their destination is more desirable for me...
https://cdn0.iconfinder.com/data/icons/logistics-4/512/production-256.png
https://cdn2.iconfinder.com/data/icons/logistics-delivery-5-1/66/224-512.png

also the 

> An existing icons may fit the use case:
>
> https://fontawesome.com/v5.15/icons/cogs?style=solid

is a good idea in some cases

**Comment by sensibleworld** [comment]
Does this icon work for you? https://fontawesome.com/v6.0/icons/conveyor-belt-boxes?s=solid

**Comment by deadmann** [comment]
> Does this icon work for you? https://fontawesome.com/v6.0/icons/conveyor-belt-boxes?s=solid

Although I look for perfection, but it's cool

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
