### ISSUE TITLE
Icon request: watermelon

### ISSUE THREAD

**Issue by jwochsauce** [FortAwesome/Font-Awesome#17972]
**What can it be used for?**
Fruit, summer

**Example image (optional)**
https://image.similarpng.com/very-thumbnail/2020/05/Slice-watermelon-clipart-Vector-PNG.png

**Icon request checklist**
- [X] This is a single icon
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We've got this added in version 6 :) https://fontawesome.com/v6.0/icons/watermelon-slice?s=duotone
