### ISSUE TITLE
Duotone fa-star is not loading

### ISSUE THREAD

**Issue by jfiander** [FortAwesome/Font-Awesome#17974]
**Describe the bug**
The duotone icon for fa-star is not loading. Noticed this on my own site after switching to v6 beta, but found the same icon missing on the v6 icon search page.

**To Reproduce**
Icon not present: https://fontawesome.com/v6.0/icons/star?s=duotone
Comparison with other star styles: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=star&s=all

**Screenshots**
From my (svg+js) implementation:
![Screen Shot 2021-06-02 at 15 51 38](https://user-images.githubusercontent.com/11098058/120543603-7e959e00-c3ba-11eb-9a66-ed2f297ec20a.png)

From FontAwesome v6 icon search:
![Screen Shot 2021-06-02 at 15 49 36](https://user-images.githubusercontent.com/11098058/120543304-2bbbe680-c3ba-11eb-8212-bb91c79ab9dc.png)

**Version and implementation**
Version: 6.0.0-beta1
Browser and version: Chrome 90.0.4430.212 x86_64

- [x] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**

- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go way up that the team can fix this when I do
- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I think this could be the same issue as #17961, @sensibleworld feel free to close as a duplicate if it is the case

**Comment by sensibleworld** [comment]
Yup. This is the same bug from the other issue. Closing this, but it's very much on our to-do list for fixing!
