### ISSUE TITLE
Icon request: fa-brackets (curly braces)

### ISSUE THREAD

**Issue by JamesNK** [FortAwesome/Font-Awesome#1797]
There is an icon-code that can be used to represent HTML and XML - http://fortawesome.github.io/Font-Awesome/icon/code/ - but there is nothing that can be used for JSON, one of the most used technologies on the web.

I think something like:

```
{ }
```

or

```
{...}
```

would make a good JSON icon.

**Comment by gitChang** [comment]
:+1: a must have.

**Comment by spookprod** [comment]
:+1:

**Comment by nodesocket** [comment]
:+1: :+1: :+1:

**Comment by no81no** [comment]
+1

**Comment by alipsmith** [comment]
+1

**Comment by birhoff** [comment]
+1

**Comment by jirkapinkas** [comment]
+1

**Comment by joubin** [comment]
+200

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issue-16612952

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-21286688

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-29581338

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-51470707

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-121408530

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-129078936

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1552#issuecomment-143703046

**Comment by codynguyen1116** [comment]
+1

**Comment by mathiasdb** [comment]
+1

**Comment by fourmisz** [comment]
+1

**Comment by omartek0** [comment]
+1

**Comment by dennis2k** [comment]
+1

**Comment by timrsmith** [comment]
How is this not a thing?

**Comment by booleangate** [comment]
+1

**Comment by zesda** [comment]
+1

Shame I'm still waiting for this one :(

**Comment by deansteen** [comment]
+1

**Comment by burunin** [comment]
+1

**Comment by kliakos** [comment]
+1

**Comment by s-Hale** [comment]
👍

**Comment by Displee** [comment]
+1

**Comment by jackcary** [comment]
+1

**Comment by jfuentesve** [comment]
+1

**Comment by SathishRaju** [comment]
<g-emoji class="g-emoji" alias="+1" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png">👍</g-emoji>

**Comment by UmangThapliyal** [comment]
+1

**Comment by agrothe** [comment]
+1

**Comment by rivers488** [comment]
![bracket_02](https://user-images.githubusercontent.com/40579030/42232229-01566ba6-7eab-11e8-9ada-f18e2be675f6.png)

I would really like this 'bracket' icon included in FontAwesome. Do I understand correctly that GitHub is the way to facilitate this?
Signed: Confused

**Comment by allenlongbaobao** [comment]
does ite accepted? i do like this icon

**Comment by UmangThapliyal** [comment]
why is it taking soo much time

**Comment by denis-tchaikovsky** [comment]
👍

**Comment by iAmien** [comment]
+1

**Comment by Tango459** [comment]
+1

**Comment by jrmessias** [comment]
+1

**Comment by LincolnPuzey** [comment]
would also be great to have a curly braces version of file-code

**Comment by mattroche** [comment]
Any progress on this, @sensibleworld ?

**Comment by sensibleworld** [comment]
@mattroche Should be out in the next day or so.

**Comment by sensibleworld** [comment]
Hey folks! Curly brackets have been added to the latest Font Awesome Pro release, along with some regular brackets.

https://fontawesome.com/icons/brackets-curly?style=solid
https://fontawesome.com/icons/brackets?style=solid
