### ISSUE TITLE
findIconDefinition always shows undefined 

### ISSUE THREAD

**Issue by ooo2003003v2** [FortAwesome/Font-Awesome#17977]
I am using findIconDefinition to check if the icon props exist in fas. But it's always returns false even if I input 500px. 
Can anyone help me?

```
GetIcon("500px")
GetIcon(icon:string)=>{ 
console.log(findIconDefinition({ prefix: "fas", iconName: icon as IconName }))
} 
///result shows false
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

500px is a brand, I expect it returns false if searched in `fas`

**Comment by ooo2003003v2** [comment]
Oh I saw where the problem were. Thx for answering me that.
