### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by Momojnight** [FortAwesome/Font-Awesome#17988]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this request is a duplicate of #16690, please add a 👍 reaction to that request, but please also provide an example, "artificial intelligence" is hard to represent

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
