### ISSUE TITLE
Mastodon Icon fails to render

### ISSUE THREAD

**Issue by codinghedgehog-python** [FortAwesome/Font-Awesome#17980]
**Describe the bug**
I'm trying to get Mastodon icon `<i class="fab fa-mastodon"></i>` to work on my blog I'm hosting with Blogger.

**To Reproduce**
Allegedly this CDN link should do the trick:
`<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.0/css/all.min.css' rel='stylesheet'/>`

**Expected behavior**
Mastodon icon rendered just like the others.

**Screenshots**
https://www.dropbox.com/s/mur2dxpxgwz1w7w/imageedit_1_3099256616.png?raw=1

**Version and implementation**
Version: 5.8
Browser and version: Firefox 89

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> to work on my blog I'm hosting with Blogger.

Sorry, don't know how to replicate.

[mastodon](https://fontawesome.com/v5.15/icons/mastodon?style=brands) has been introduced in Font Awesome 5.7.0, so please double check that you are using Font Awesome 5.7.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If Blogger has a theme / library which provides an older version of Font Awesome, please get in touch with them and ask for an update

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case (a screenshot is appreciated but does not help in this case)

Hope it helps

Closing here
