### ISSUE TITLE
Icon Request: fa-thrust

### ISSUE THREAD

**Issue by CalumChilds** [FortAwesome/Font-Awesome#17994]
**What can it be used for?**
This icon can be used to represent thrust for sites that deal with aviation. 

**Example image (optional)**
https://game-icons.net/icons/000000/ffffff/1x1/felbrigg/thrust.png

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify why the existing [arrow-up](https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=arrow%20up&m=free) icons do not fit this use case?

**Comment by Wingo5315** [comment]
Because, the thickness of the line is consistent in the arrow-up icons, whilst this one has a gradual decrease in the thickness of the line as the line goes up.

**Comment by arbaminim** [comment]
I am looking for similar symbols: a 3d arrow forward, and 3d arrow back. I need to represent all six spatial directions (left, right, forward, backward, up, and down). An arrow with perspective could represent in toward the medium or out toward the viewer.
