### ISSUE TITLE
TikTok icon not showing but blank space is clickable

### ISSUE THREAD

**Issue by FairytalesAndTea** [FortAwesome/Font-Awesome#17997]
**Describe the bug**
I am using a premade theme by premiumcoding (the Laura theme) and it has a built-in area to add FontAwesome icons. I have Pinterest and Instagram icons and they both show up and work. However, the TikTok icon does not appear. The blank space where the icon should be at the top left corner is clickable (between the Pinterest and Instagram icons), but the two other social media icon locations on the website are not clickable (sidebar and footer area). I've entered the icon code in the same format as the other two icons but no luck. They are all entered as fa-(insert social media). 

**To Reproduce**
https://fairytalesandtea.com/

**Expected behavior**
I'd like for the TikTok icon to be visible and clickable. 

**Version and implementation**
I'm not sure if this is what you want (I'm very new at this), but the TikTok version number I'm trying to use is 5.14.0
I'm using Google Chrome. 

Please let me know if you need more information. Again, I'm pretty new to all of this, so forgive my ignorance!
Cheers,
Lydia

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I am using a premade theme by premiumcoding (the Laura theme) and it has a built-in area to add FontAwesome icons.

We do not provide support to third party plugins/libraries

Said so, I can see that the web application is using Font Awesome 4, which is in EOL, and it is loaded through the old CDN.

As you mentioned in the OP, you need Font Awesome >= 5.14 to use TikTok

You have at least two options:
- Contact theme's developer and ask for an update
- Create a Font Awesome kit and a [child thime](https://developer.wordpress.org/themes/advanced-topics/child-themes/) to fix the theme by yourself
- Try our official wordpress plugin: https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/wordpress, which also has a conflict detection mode that could help


Closing here, but feel free to comment
