### ISSUE TITLE
Icon Request: icon-cog-wrench (repair service)

### ISSUE THREAD

**Issue by Aniaketer** [FortAwesome/Font-Awesome#17993]
This icon might describe products spare parts or repairing service

![repairing-service](https://user-images.githubusercontent.com/85689441/121539288-36a3f600-ca0e-11eb-981a-089b85fe1c95.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have some icons that may work for this use case:
- https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=cog&m=free
- https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=tools&m=free

**Comment by Aniaketer** [comment]
Thank you
