### ISSUE TITLE
Update the Discord icon to new one

### ISSUE THREAD

**Issue by Void48** [FortAwesome/Font-Awesome#17996]
https://discord.com/branding
Branding page has been updated to new logos. FontAwesome still has the old discord icon

**Comment by Void48** [comment]
Here's the link btw. https://fontawesome.com/v5.15/icons/discord?style=brands

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #17897. No need to +1, that will be done in the next FA5 release

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here
