### ISSUE TITLE
Bug: FA6's unicode glyphs not displayed on Desktop (Gimp / Win 10)

### ISSUE THREAD

**Issue by xeniun** [FortAwesome/Font-Awesome#18002]
**Describe the bug**
bullhorn isn't displayed correctly with solid font version 6 in Gimp for Windows 10. It is replaced by an emoji.

**Version and implementation**
Version: 6.0.0-beta1

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm the issue (Win 10 21H1, Gimp 2.10.24, I don't know if it is a known one.

As a workaround, please use ligatures (write `user` or `graduation-cap`)

@robmadole more details:
- ligatures work, unicode glyph doesn't
  ![image](https://user-images.githubusercontent.com/556268/121806843-ce455680-cc51-11eb-8659-8e8b7adfe975.png)
- The font doesn't work at all on Word 2019 / Win 10 21H1
  
  ![image](https://user-images.githubusercontent.com/556268/121806914-1d8b8700-cc52-11eb-9040-c596f4d2a5f9.png)

  ![image](https://user-images.githubusercontent.com/556268/121806881-f92faa80-cc51-11eb-8e05-6adfe7967ad3.png)

**Comment by xeniun** [comment]
I didn't know how ligatures work. Thank you so much! 😄

**Comment by robmadole** [comment]
Ok. I tried to reproduce this with Gimp on macOS. And it's not exactly the same but there is some strange behavior. I can't seem to get _any_ Emoji character to show up. So perhaps this is a bug with Gimp? Does it work with Font Awesome 5?

**Comment by xeniun** [comment]
> Ok. I tried to reproduce this with Gimp on macOS. And it's not exactly the same but there is some strange behavior. I can't seem to get _any_ Emoji character to show up. So perhaps this is a bug with Gimp? Does it work with Font Awesome 5?

Windows 10 and GIMP 2.10.24 (revisione 3)

When I try to copy user-friends Unicode glyph from FA5 to Gimp:

1. Copy gliph from your website
2. Set correct font 5 Pro
3. Paste
4. Done. Right.

When I try to copy user-friends Unicode glyph from FA6 to Gimp:

1. Copy gliph from your website
2. Set correct font 6 Pro
3. Paste
4. A wonderfull emoji in Windows style

If I use ligatures, glyph looks correctly.
Look at @tagliala message and screens.

It's not my first time with Gimp and FA fonts =)

**Comment by tagliala** [comment]
Ciao @xeniun, thanks for the follow up

I think there is an issue with FA6 since Word 2019 does not work at all

**Comment by sensibleworld** [comment]
@xeniun Can you test this issue again using the latest beta (6.0.0-beta2) release?

**Comment by tagliala** [comment]
@sensibleworld here it is my report

I confirm that Gimp works on Win 10 with FA6 Free/Pro 6.0.0-beta2, both with ligatures and by copying glyphs

I have still issues in Word 19, where the font does not work at all (no ligatures, no copy & paste). Ref: https://github.com/FortAwesome/Font-Awesome/issues/18002#issuecomment-860201521

**Comment by xeniun** [comment]
@sensibleworld no issues with beta2. Thanks!

**Comment by tagliala** [comment]
Ok, thanks for the feedback

I'm going to close here and split the word problem into a new issue
