### ISSUE TITLE
Icon Request: Various Text Editor Icons Addons

### ISSUE THREAD

**Issue by Tukulka** [FortAwesome/Font-Awesome#1800]
Since I'm developing an HTML text editor I would like to ask and suggest some missing icons:

- Color (An "A" or a "T" with a drop on it?)
- Font Weight (Usually displayed with an "A"or "T" in 3 different Weight)
- Font Size (Usually displayed with an "A"or "T" in 2 different Size)
- Line Height (A on A with arrow)
- Letter Spacing (A - spacer - A)
- Text Transform Uppercase (TT)
- Text Transform Capitalize (Tt)
- Text Transform Lowercase (tt)

If it's ok I will post a possible list for a Layout Category I think it could be useful :)

**Comment by EinSteein** [comment]
+1
nearly any text editor has these icons. this would be a great extension
just to give an example: Within Mozilla Thunderbird's Write window or Microsoft Word

**Comment by tagliala** [comment]
Sorry, cannot leave this open

Updated contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

There are some individual requests for the above icons, please use the search bar
