### ISSUE TITLE
6.0.0-beta1 and 6.0.0-beta2 with SVG/JS Kit can't show duotone icons with only a secondary layer

### ISSUE THREAD

**Issue by 1stKarkan** [FortAwesome/Font-Awesome#18016]
**Describe the bug**
I have a Kit that can't show fad fa-angle-left and -right respectively. It behaves as if the icon did not exist. The fas versions work. Also using Version 5 works.

**To Reproduce**
Create a Kit and select SVG+JS and version 6.x. Then add the kit and `<i class="fad fa-angle-right"></i>` to your page.

**Expected behavior**
It should show the SVG icon of Duotone angle-right.

**Screenshots**
Kit
![image](https://user-images.githubusercontent.com/8205102/122681520-f0604b00-d1f4-11eb-9945-dcf936d6e03f.png)

Output on website
![image](https://user-images.githubusercontent.com/8205102/122681541-0a019280-d1f5-11eb-8096-d9a76769057b.png)

**Version and implementation**
Version: 6 Beta 1
Browser and version: Chrome 91 on Linux
- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
I think this may be the same issue as #17961

@sensibleworld

**Comment by 1stKarkan** [comment]
Hello,
Yes it seems the rendering problems are related. I missed that when searching for existing issues

**Comment by 1stKarkan** [comment]
Hello @sensibleworld, yes the issue still persists with Beta 2. I checked again with the Kit i used. Maybe the issue is related to Kits with JS/SVG only. I also just noticed that the issue could be related to the colors. All icons which have this issue only have a single color.

It's easy to reproduce in a small html file:

![image](https://user-images.githubusercontent.com/8205102/135307708-f012d814-398d-456c-abee-f508ab85fde4.png)


Output:

![image](https://user-images.githubusercontent.com/8205102/135307391-f0a323b3-608c-42a7-b949-8a608099da1e.png)


As you can see, all icons with just a single color were not found while any duo-tone which actually uses two colors was rendered like expected

**Comment by tagliala** [comment]
@1stKarkan any chance to paste your code from the screenshot so I can test with my kit without rewriting?

**Comment by 1stKarkan** [comment]
@tagliala of course, sorry

```<html>
<head>
<script src="https://kit.fontawesome.com/[kitcode].js" crossorigin="anonymous"></script>
</head>
<body style="font-size: 64px;">
<i class="fad fa-ghost"></i>
<i class="fad fa-times"></i>
<i class="fad fa-angle-left"></i>
<i class="fad fa-angle-right"></i>
<i class="fad fa-angle-down"></i>
<i class="fad fa-angle-up"></i>
<i class="fad fa-angle"></i>
<i class="fad fa-triangle"></i>
<i class="fad fa-angles-right"></i>
<i class="fad fa-angles-left"></i>
<i class="fad fa-triangle-exclamation"></i>
<i class="fad fa-rectangle-wide"></i>
<i class="fad fa-rectangle-xmark"></i>
<i class="fad fa-0"></i>
<i class="fad fa-1"></i>
</body>
</html>
```

**Comment by tagliala** [comment]
Confirm it's still an issue and the Kit is using 6.0.0-beta2. Looks like it is not happening when using the CDN

Reproducible test case: https://jsfiddle.net/tagliala/qdu6n7m1/1/

**Comment by robmadole** [comment]
Thanks everyone! I ended up finding this bug by accident as well today. We'll get it fixed for beta3!
