### ISSUE TITLE
Font awesome console error on startup:  Unexpected token '.'

### ISSUE THREAD

**Issue by ttaylor29** [FortAwesome/Font-Awesome#18011]
**Describe the bug**
I installed Font Awesome Free 5.15.3  into my asp.net core 3.1 application in wwwroot/lib folder. When I run the application, I see this error: 

Uncaught SyntaxError: Unexpected token '.'

![image](https://user-images.githubusercontent.com/23564255/122418368-c6d2c580-cf4f-11eb-9f49-e9d1de6418aa.png)

This error occurs on the initial startup. The font awesome icons seem to load fine.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
The error to not display!

**Version and implementation**
Version:  Font Awesome Free 5.15.3
Browser and version: Google Chrome Version 91.0.4472.106 (Official Build) (64-bit)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you trying to load this file as a javascript? Could you please provide the source of your HTML file?

**Comment by ttaylor29** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Are you trying to load this file as a javascript? Could you please provide the source of your HTML file?

Ugghhhhhh, you are right. My bad. I did this at 1am... haha


This is what I need:

`    <link rel="stylesheet" href="~/lib/fontawesome-free-5.15.3-web/css/all.css" asp-append-version="true" />`

This is what I had:

`    <script src="~/lib/fontawesome-free-5.15.3-web/css/all.css"></script>`

Thanks! Error is gone now. This is resolved!
