### ISSUE TITLE
希望添加一个Windows 11的图标

### ISSUE THREAD

**Issue by cddehsy** [FortAwesome/Font-Awesome#18017]
希望添加一个Windows 11的图标

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From Google Translate:

> Hope to add a Windows 11 icon

When Windows 11 will be officially presented and if the official logo will be different from Windows 10's one, feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

Meanwhile, closing here
