### ISSUE TITLE
Cannot install FA6 using Website instructions

### ISSUE THREAD

**Issue by saeho** [FortAwesome/Font-Awesome#18028]
I’m trying to follow the instructions to install the FA6 react packages. But nothing is working. I just can’t install the packages at all.

Here’s what I tried.

npm i --save @fortawesome/fontawesome-svg-core@next (Did not work)
npm i --save @fortawesome/fontawesome-svg-core (Worked)
npm i --save @fortawesome/pro-solid-svg-icons@next (Did not work)
npm i --save @fortawesome/pro-solid-svg-icons (Did not work)
npm install --save @fortawesome/fontawesome-pro@next (Did not work)
npm install --save @fortawesome/fontawesome-pro@next (Did not work)

All of these lines (copy pasted from the website) failed to install the packages.

One of them worked when I removed @next, but still couldn’t proceed with the installations because the rest of the installations failed.

Please tell me what to do to figure this out.

NOTE: I'm trying to install & use FA6, not FA5

Thank you.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, cannot replicate:

```
$ npm i --save @fortawesome/pro-solid-svg-icons@next

added 2 packages, changed 2 packages, and audited 17 packages in 5s
```

Could you please run the command with `--verbose` and provide the output log, by having care of checking every line and removing possible sensitive information (just remove sensitive information, in example the local user name) not the whole line)?

Otherwise, since the beta is limited to Pro users, you can send an email to hello@fontawesome.com and ask for dedicated support

**Comment by saeho** [comment]
`npm timing command:install Completed in 1741ms
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icons - Not found
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb stack     at async Arborist.[retrieveSpecName] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:502:18)
npm verb stack     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:474:20
npm verb stack     at async Promise.all (index 0)
npm verb stack     at async Arborist.[applyUserRequestsToNode] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:446:7)
npm verb stack     at async Arborist.[applyUserRequests] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:402:7)
npm verb stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:136:5)
npm verb statusCode 404
npm verb pkgid @fortawesome/pro-solid-svg-icons@next
npm verb cwd /Users/PATH_TO_FOLDER/client
npm verb Darwin 20.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "@fortawesome/pro-solid-svg-icons@next" "--verbose"
npm verb node v12.18.1
npm verb npm  v7.17.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-solid-svg-icons@next' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm timing npm Completed in 2289ms
npm verb code 1`

**Comment by saeho** [comment]
I still cannot install the package (with above errors using --verbose)

However, I still would really really like to use SVG FA6 icons **without** installing a React package.

I used FA5 svg icons everywhere previously without a package, and my large codebase has "<i />" tags everywhere with font awesome icon class names.

It would be extremely difficult and waste of my time to convert all my code base to use a npm package.

I would really appreciate it if you could just tell me how to make SVG icons work without crashing without a React package.

**Comment by tagliala** [comment]
```
T https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icons - 
```

This is not correct, the private npm FA repo is not configured properly and npm is trying to download font awesome from the public npm repo.

Please follow the instructions at: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro

If you still have troubles, as a FA Pro customer, please get in touch with hello@fontawesome.com to get dedicated support 

Closing here, but feel free to comment

**Comment by saeho** [comment]
I did e-mail hello@ .. but practically the same as this thread ..

To be honest, what I really want is the ability to *not* use a npm package......

As a pro customer, it is the number 1 thing I want and I really hope you guys consider it.....

**Comment by tagliala** [comment]
> I did e-mail hello@ .. but practically the same as this thread ..

You mean that the configuration issue has been identified and the support asked you to fix?

> To be honest, what I really want is the ability to not use a npm package......

Of course you can, there are a lot of different ways to use Font Awesome. If you don't want to use npm, you can self-host the webfont https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself or use KiTs https://fontawesome.com/kits
