### ISSUE TITLE
fa-refresh is missing

### ISSUE THREAD

**Issue by uri-rodberg** [FortAwesome/Font-Awesome#18022]
https://fontawesome.com/v4.7/icon/refresh

**Comment by uri-rodberg** [comment]
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=fa-refresh

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In FA5 we have dropped aliases, so refresh is now called `sync-alt`: https://fontawesome.com/v5.15/icons/sync-alt?style=solid

Docs: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4

Note: if you search for just `refresh` it appears

Hope it helps

Closing here

**Comment by uri-rodberg** [comment]
Thank you.
