### ISSUE TITLE
Loaded only used Font Awesome Icons

### ISSUE THREAD

**Issue by ZENwww** [FortAwesome/Font-Awesome#18027]
Hi! Please add feature where there's a option to load Font Awesome icons that are used on the site.

**Feature request checklist**
- [ * ] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ * ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [ * ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Hi! Please add feature where there's a option to load Font Awesome icons that are used on the site.

This feature is already available through [Pro Kits](https://fontawesome.com/plans), [Pro Subsetter](https://fontawesome.com/v5.15/how-to-use/on-the-desktop/other-topics/subsetter) and [Tree Shaking](https://fontawesome.com/v5.15/how-to-use/javascript-api/other/tree-shaking)

Other options (free customization of the font files) may be possible via third-party services

Hope it helps

Closing here
