### ISSUE TITLE
Icon Request: fa-manufacturing

### ISSUE THREAD

**Issue by kkaim13** [FortAwesome/Font-Awesome#18024]
Used to have these icons. Plan to use them under or locations and directions for location types (manufacturing, sales, sales and service).

![manufacturing facility](https://user-images.githubusercontent.com/86364485/123116116-a3f05780-d40e-11eb-8e75-9f6656296e5b.PNG)
![icons](https://user-images.githubusercontent.com/86364485/123116133-a5ba1b00-d40e-11eb-9b97-bbf5a70f8bf9.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available as [fa-industry](https://fontawesome.com/v5.15/icons/industry?style=solid)

Pro users also have [an alternative version](https://fontawesome.com/v5.15/icons/industry-alt?style=solid)

Closing here
