### ISSUE TITLE
Sass deprecation warning

### ISSUE THREAD

**Issue by CheetahDev** [FortAwesome/Font-Awesome#18029]
Hi there,

**Describe the bug**
We are getting Sass deprecation warnings when we build our project (Angular 12 project).

**To Reproduce**
Just tried the following scenario:
- ng new sass-issue (choose SCSS)
- npm install --save @fortawesome/fontawesome-free
- Add the following imports to styles.scss
- ng build

```
@import '~@fortawesome/fontawesome-free/scss/fontawesome.scss';
@import '~@fortawesome/fontawesome-free/scss/solid.scss';
```

**Expected behavior**
No warning at build

**Screenshots**
```
ng build
⠋ Generating browser application bundles (phase: building)...WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules\@fortawesome\fontawesome-free\scss\_variables.scss 12:25  @import
    node_modules\@fortawesome\fontawesome-free\scss\fontawesome.scss 5:9   @import
    src\styles.scss 1:9                                                    root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(4em, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
6 │   font-size: (4em / 3);
  │               ^^^^^^^
  ╵
    node_modules\@fortawesome\fontawesome-free\scss\_larger.scss 6:15     @import
    node_modules\@fortawesome\fontawesome-free\scss\fontawesome.scss 8:9  @import
    src\styles.scss 1:9                                                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(3em, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
7 │   line-height: (3em / 4);
  │                 ^^^^^^^
  ╵
    node_modules\@fortawesome\fontawesome-free\scss\_larger.scss 7:17     @import
    node_modules\@fortawesome\fontawesome-free\scss\fontawesome.scss 8:9  @import
    src\styles.scss 1:9                                                   root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($fa-li-width * 5, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
6 │   margin-left: $fa-li-width * 5/4;
  │                ^^^^^^^^^^^^^^^^^^
  ╵
    node_modules\@fortawesome\fontawesome-free\scss\_list.scss 6:16        @import
    node_modules\@fortawesome\fontawesome-free\scss\fontawesome.scss 10:9  @import
    src\styles.scss 1:9                                                    root stylesheet

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files               | Names         |       Size
main.bc9ffbe86b12d43fcb26.js      | main          |  213.86 kB
styles.17ec057c9f3961c59719.css   | styles        |   53.97 kB
polyfills.f8b0c9de1febdb39c63e.js | polyfills     |   35.96 kB
runtime.bc815340e3511725dfba.js   | runtime       | 1023 bytes

                                  | Initial Total |  304.80 kB

Build at: 2021-06-25T08:48:47.262Z - Hash: 370723f24a94f49dd0eb - Time: 28011ms
```

**Version and implementation**
Version: 5.15.3

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this. We already know about this issue #17940

Can't be fixed in this repo, we will fix it upstream

**Comment by CheetahDev** [comment]
Thanks @tagliala.
Don't know why the issue didn't came up in my search earlier...
Sorry for the duplicate.

**Comment by csimpi** [comment]
@CheetahDev Not your fault, for some reason this doesn't appear in Google when you search for `fontawesome sass deprecation`. I've tried several combinations, finally came here to report, and saw this at the last moment :)

@tagliala: When can we expect a new version where this is fixed? You may use the official migration plugin:
https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration

**Comment by tagliala** [comment]
Hi @csimpi we would like to preserve the compatibility with libsass, we are probably going to replace divisions by multiplications and use a magic number for the `/ 3`

**Comment by wjgvm** [comment]
use npm install -g sass-migrator global or npm install sass-migrator in proyect
your require it package
