### ISSUE TITLE
heart

### ISSUE THREAD

**Issue by wjddpwls** [FortAwesome/Font-Awesome#18039]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Instagram icon is already available:
- https://fontawesome.com/v5.15/icons/heart?style=solid
- https://fontawesome.com/v5.15/icons/heartbeat?style=solid
- https://fontawesome.com/v5.15/icons/heart-broken?style=solid

If you are looking for a heart as in anatomical heart, please add a 👍🏼 reaction to #16374

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
