### ISSUE TITLE
Font Awesome 6 Beta download 404

### ISSUE THREAD

**Issue by AntonTrapp** [FortAwesome/Font-Awesome#18031]
Wanted to take a look at it... clicking download -> you must be signed in (which I am), signing in -> 404

Accont details -> Version 6.0.0-beta1  the latest version your perpetual license grants you -> click on Version 6.0.0. beta 1 -> 404

Can't find a way to get the beta...

**Comment by frrrances** [comment]
Hi! Thanks for being part of the Font Awesome community. If you're a Pro subscriber and you're still having trouble downloading the Version 6 beta, you can [contact support](mailto:hello@fontawesome.com) and we'll get you unstuck.
