### ISSUE TITLE
Icon request: icon-media

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1803]
Hello Everyone,
Greates icons collection!!1))

I want to request media icon if it's possible.
You have Pictures icon, Camera, Video and etc. but no media, like general icon.

http://www.kudlian.net/products/mediabrowser/images/media_browser_icon.jpg
http://jarederickson.com/wp-content/uploads/2011/10/wp-33-admin-icon-560x259.jpg

sorry could not find better picture of wordpress media icon, but I like this one most

**Comment by sensibleworld** [comment]
We don't yet have a photo-video-music icon, but we do now have a photo-video icon: https://fontawesome.com/icons/photo-video?style=solid

**Comment by sensibleworld** [comment]
<img width="682" alt="Screen Shot 2021-03-30 at 12 02 39 PM" src="https://user-images.githubusercontent.com/529604/113019652-d4965d00-914f-11eb-9431-b02ae4544df7.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
