### ISSUE TITLE
REQUEST: moving apple-core from v6-pro to v6-free

### ISSUE THREAD

**Issue by nielsnl68** [FortAwesome/Font-Awesome#18044]
**What can it be used for?**
Telling the system to see the measurement being done before of after a meal.

**Example image (optional)**
I'm working on a free to use web-app project to manage the blood sugar level for persons with diabetes. On of the futures is to show of the value is measured before of after dinner. 

I have been validating of going pro is worth the money for just one or two icons that are needed from the pro version. Sadly i came to the conclusion that it is not.
More of because of the free nation of the application's i'm working on.

So now i wondering, are you willing to move it to the free plan? I'm happy to do a small donation for it.

**Comment by sensibleworld** [comment]
Hey @nielsnl68! Thanks so much for the request. We're always happy to consider updating icons, but we're unlikely to move an icon from Pro to Free unless there's overwhelming support to do so. I will say that you can gain access and a license to the Pro icons by paying the upgrade fee (currently only $79!) and then canceling the subscription. You'll still have lifetime access to the icons, but won't get ongoing support, new icons, or features.
