### ISSUE TITLE
Can't see TikTok Icon

### ISSUE THREAD

**Issue by sitzophrenic** [FortAwesome/Font-Awesome#18046]
Hello, I have FA Pro, I use Font Awesome Pro 5 and I set my font-family to 'Font Awesome 5 Brands' like the other brands and it doesn't show.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[tiktok](https://fontawesome.com/v5.15/icons/tiktok?style=brands) has been introduced in Font Awesome 5.14.0, so please double check that you are using Font Awesome 5.14.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here

>  I use Font Awesome Pro 5

As a Font Awesome Pro user, if the above doesn't help, you can ask for dedicated support by sending an email to hello@fontawesome.com
