### ISSUE TITLE
Bug: unicode fa-whatsapp not working

### ISSUE THREAD

**Issue by dustcrawler** [FortAwesome/Font-Awesome#18047]
**Describe the bug**
I tried to use the Unicode for the whatsapp icon ( f232 ) but it doesn't work. Tried other fonts with the Font Awesome 5 Pro family but they all worked.

**To Reproduce**
https://jsfiddle.net/yhj0u6tm/

**Expected behavior**
The correct unicode on website or to fix the unicode.

**Screenshots**
![image](https://user-images.githubusercontent.com/31991407/124264444-c41dc600-db34-11eb-902b-9000acf15c3d.png)

**Version and implementation**
Version: Latest 5.x
Browser and version: Firefox Version 90

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The proper `font-family` name for Brand icons is "Font Awesome 5 Brands"

https://jsfiddle.net/tagliala/sq7wj981/1/

Docs: https://fontawesome.com/v5.15/how-to-use/on-the-web/advanced/css-pseudo-elements

Hope it helps

Closing here

**Comment by dustcrawler** [comment]
Yes. My bad. Thanks for addressing the issue I had.

**Comment by tagliala** [comment]
Welcome, glad you solved
