### ISSUE TITLE
Icon request:Custom Icon

### ISSUE THREAD

**Issue by habeebkambrath** [FortAwesome/Font-Awesome#18059]
**What can it be used for?**
for using personal project

**Example image (optional)**
image link:https://i.postimg.cc/Hxx5yqHy/HGHVH.png

**Comment by aethior** [comment]
Hi @habeebkambrath,

You can use [**fa-standard-definition**](https://fontawesome.com/icons/standard-definition) icon.

Regards.

cc/ @tagliala
