### ISSUE TITLE
Pairing with glyphicons: New icons

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#1805]
Refers to #940 
- [ ] [compressed](http://tagliala.github.io/vectoriconsroundup/#compressed)
- [x] [copyright-mark](http://tagliala.github.io/vectoriconsroundup/#copyright-mark) (#375)
- [ ] [export](http://tagliala.github.io/vectoriconsroundup/#export) (#1020)
- [ ] [floppy-open](http://tagliala.github.io/vectoriconsroundup/#floppy-open)
- [ ] [floppy-remove](http://tagliala.github.io/vectoriconsroundup/#floppy-remove)
- [ ] [floppy-save](http://tagliala.github.io/vectoriconsroundup/#floppy-save)
- [ ] [floppy-saved](http://tagliala.github.io/vectoriconsroundup/#floppy-saved)
- [ ] [hd-video](http://tagliala.github.io/vectoriconsroundup/#hd-video)
- [x] [header](http://tagliala.github.io/vectoriconsroundup/#header) (#747)
- [ ] [import](http://tagliala.github.io/vectoriconsroundup/#import) (#1020)
- [ ] [new-window](http://tagliala.github.io/vectoriconsroundup/#new-window)
- [ ] [open](http://tagliala.github.io/vectoriconsroundup/#open)
- [ ] [phone-alt](http://tagliala.github.io/vectoriconsroundup/#phone-alt) (#1578)
- [ ] [record](http://tagliala.github.io/vectoriconsroundup/#record)
- [ ] [registration-mark](http://tagliala.github.io/vectoriconsroundup/#registration-mark)
- [ ] [save](http://tagliala.github.io/vectoriconsroundup/#save)
- [ ] [saved](http://tagliala.github.io/vectoriconsroundup/#saved)
- [ ] [sd-video](http://tagliala.github.io/vectoriconsroundup/#sd-video)
- [x] [send](http://tagliala.github.io/vectoriconsroundup/#send) (#1566)
- [ ] [sound-5-1](http://tagliala.github.io/vectoriconsroundup/#sound-5-1)
- [ ] [sound-6-1](http://tagliala.github.io/vectoriconsroundup/#sound-6-1)
- [ ] [sound-7-1](http://tagliala.github.io/vectoriconsroundup/#sound-7-1)
- [ ] [sound-dolby](http://tagliala.github.io/vectoriconsroundup/#sound-dolby)
- [ ] [sound-stereo](http://tagliala.github.io/vectoriconsroundup/#sound-stereo)
- [ ] [stats](http://tagliala.github.io/vectoriconsroundup/#stats)
- [x] [subtitles](http://tagliala.github.io/vectoriconsroundup/#subtitles) (#968)
- [ ] [tower](http://tagliala.github.io/vectoriconsroundup/#tower)
- [ ] [transfer](http://tagliala.github.io/vectoriconsroundup/#transfer)
- [ ] [tree-conifer](http://tagliala.github.io/vectoriconsroundup/#tree-conifer)
- [ ] [tree-deciduous](http://tagliala.github.io/vectoriconsroundup/#tree-deciduous)

**Comment by cgarcia75** [comment]
Ok so how do  I create a header

**Comment by tagliala** [comment]
@cgarcia75 please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by mbeijen** [comment]
I know I should just +1 this issue but then I can't specify the specific icon I'm looking for: the Dolby icon.

**Comment by sensibleworld** [comment]
Closing this, as most of these icons already exist in FA 5. If we're still missing specific icons, let us know with a new request!
