### ISSUE TITLE
6.0 duotone fa-hourglass and fa-hourglass-end are missing secondary color

### ISSUE THREAD

**Issue by arbaminim** [FortAwesome/Font-Awesome#18055]
The outline of glass bulbs is not visible, but only the sand and the ends.

![hourglass](https://user-images.githubusercontent.com/8258651/124597600-4b1ab900-de29-11eb-8b88-736cf0a5bfae.png)

Also the properties  "--fa-primary-color" and "--fa-secondary-color" both seem to affect the same path (the visible sand and ends).

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this

@sensibleworld any chance it is the same bug as #17730 ?

**Comment by sensibleworld** [comment]
@tagliala Nope. It's the same as this bug, though: https://github.com/FortAwesome/Font-Awesome/issues/17961

Basically our pseudo-elements support got all wonky with the first beta due to some unicode changes. We're still working on a fix, and should have it out with the second beta.

**Comment by tagliala** [comment]
Thanks. Closing here as a duplicate and adding a `duotone` label to #17961
