### ISSUE TITLE
Problem with Pro: Script link is publicly available

### ISSUE THREAD

**Issue by Sly-Little-Fox** [FortAwesome/Font-Awesome#18057]
Hello! If a site uses Font Awesome, script link is publicly available. Any website can use it then, which is not good. A solution would be to manually whitelist hosts.

**Comment by Sly-Little-Fox** [comment]
Note: I accidentally created this issue without content, edited now.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Hello! If a site uses Font Awesome, script link is publicly available. Any website can use it then, which is not good. A solution would be to manually whitelist hosts.

Yes, there is an allowlist in kit settings. Please restrict your kit to the domain it is allowed

![image](https://user-images.githubusercontent.com/556268/124796560-99c37280-df51-11eb-9c7c-ca13394d9772.png)

**Comment by Sly-Little-Fox** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> > Hello! If a site uses Font Awesome, script link is publicly available. Any website can use it then, which is not good. A solution would be to manually whitelist hosts.
> 
> Yes, there is an allowlist in kit settings. Please restrict your kit to the domain it is allowed
> 
> ![image](https://user-images.githubusercontent.com/556268/124796560-99c37280-df51-11eb-9c7c-ca13394d9772.png)

Whoops, sorry. I didn't know. Why doesn't your website use whitelisting though?

**Comment by tagliala** [comment]
> Why doesn't your website use whitelisting though?

Could you please be more specific? Which link?

**Comment by Sly-Little-Fox** [comment]
> > Why doesn't your website use whitelisting though?
> 
> Could you please be more specific? Which link?

Sorry, looks like I was wrong. I'm talking about https://use.fortawesome.com/349cfdf6.js and https://use.fortawesome.com/1ce05b4b.js scripts on Font Awesome 6 page.

**Comment by tagliala** [comment]
Ok, thanks

Those are not Kits (kits use the domain `kits.fontawesome.com`), they are js assets used by our documentation website. Are you able to use Font Awesome Pro by including the above scripts in another website?

**Comment by Sly-Little-Fox** [comment]
> Ok, thanks
> 
> Those are not Kits (kits use the domain `kits.fontawesome.com`), they are js assets used by our documentation website. Are you able to use Font Awesome Pro by including the above scripts in another website?

I tested, I can't. But I looked into network panel and found links to v6 font. Is it expected? 🤔
Here are they: 
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-duotone-900.woff2
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-regular-400.woff2
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-solid-900.woff2
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-thin-100.woff2
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-brands-400.woff2
https://pro.fontawesome.com/releases/v6.0.0-beta1/webfonts/fa-light-300.woff2

**Comment by tagliala** [comment]
> I tested, I can't. But I looked into network panel and found links to v6 font. Is it expected? 🤔

Yes, we can't do anything about that, it is in the nature itself of a webfont

Anyway, FA Pro is a commercial product and using it without a valid license is Software Privacy

@robmadole any thoughts?

**Comment by Sly-Little-Fox** [comment]
> Anyway, FA Pro is a commercial product and using it without a valid license is Software Piracy
~~Yes, all problems can be solved with law~~

**Comment by Sly-Little-Fox** [comment]
> Yes, we can't do anything about that, it is in the nature itself of a webfont

You can at least only allow requests from your website (Origin header), so that people can't load it from your CDN. You can also split fonts into many small fonts with limited character sets so it's harder to use them.

**Comment by robmadole** [comment]
Hi there. We are aware of this and have plans to deal with it. Thanks for reporting it @Sly-Little-Fox
