### ISSUE TITLE
Icon request: alarm-snooze-slash

### ISSUE THREAD

**Issue by yeshehl** [FortAwesome/Font-Awesome#18064]
Hi,

I'll be happy to Have on your library an unsnooze icon.
it could be used to stop the snooze action.

this icon is a pair for the snooze icon.
Thanks 
Yuval

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you requesting something like `snooze-slash`?

If yes, your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/hufysvg0/22/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by yeshehl** [comment]
Hi,
Sorry, I wasn't clear enough...
I'm looking for the opposite of this alarm clock (cancel the alarm snooze)
https://fontawesome.com/v5.15/icons/alarm-snooze?style=light
Like it appears in this example:
https://www.123rf.com/photo_142301090_stock-vector-alarm-off-icon-editable-vector-outline-symbol-notification-off-single-pictogram.html
Thanks

**Comment by tagliala** [comment]
Hi, thanks for the clarification, I've edited the title

Given that your request is valid, the aforementioned approach still works

Demo: https://jsfiddle.net/tagliala/hufysvg0/28/

**Comment by yeshehl** [comment]
Hi,
Thank you very much!
I opened the Link, but I'm not sure I understand how to transform the Html to SVG file so I can use it in XD

**Comment by tagliala** [comment]
Welcome

> so I can use it in XD

Sorry, that is not possible, SVG Framework is a feature for the web

**Comment by DawnM** [comment]
In case you haven't found a solution yet, you can just layer the text versions on top of each other in XD, if you have the desktop fonts installed

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
