### ISSUE TITLE
OS icons instead of FA displayed, updating from 6.0 alpha to 6.0 beta

### ISSUE THREAD

**Issue by EtienneDelepine** [FortAwesome/Font-Awesome#18060]
I wanted to use 6.0.0 beta 1 instead of 6.0.0 alpha 2 and I was not expecting to see the OS icons displayed in place of the FA.
I just put the new all.min.css and the difference is on the joined pic
![pb 6beta fw](https://user-images.githubusercontent.com/50837574/125067051-048cbf00-e0b4-11eb-8a2f-f9f261bda743.png)

In this example, the fa-puzzle-piece uses f12e in aplha2 but 1f9e9 in beta1; fa-dna uses  f471 in alpha2 but 1f9ec

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can just assign to @robmadole

**Comment by tagliala** [comment]
hmm...

> I just put the new all.min.css and the difference is on the joined pic

Did you also update the webfont files and make sure the application is loading the new ones (purge cache)

**Comment by EtienneDelepine** [comment]
Oh! that's the point, old webfonts in the browser!
I'm very sorry for the inconvenience! It's my fault!
Font Awesome is so great and the team also !
Thanks

**Comment by tagliala** [comment]
No problem, glad you've solved and thanks for the feedback
