### ISSUE TITLE
Allow HTTP Options method

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#18068]
Hi,

Shouldn't the HTTP OPTIONS for https://kit.fontawesome.com/272d3a8e61.js also return Access-Control-Allow-Origin header? 
(So as the rest of Access-Control-* headers i.e. Allow-Methods, Allow-Headers and Max-Age)

If I try it with HTTP GET it does
![image](https://user-images.githubusercontent.com/37901240/125318519-32833500-e33a-11eb-959a-986f4271b9bb.png)
As you can see returned header Access-Control-Allow-Methods contains GET and OPTIONS

But for HTTP OPTIONS it returns status code 404 and of course it does not contain the Access-Control-* headers.
![image](https://user-images.githubusercontent.com/37901240/125321717-454b3900-e33d-11eb-94c6-08b5c274ca0a.png)

According to this
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
I think it should work and return the headers also for OPTIONS

it seems that it is the case of my scenario
![image](https://user-images.githubusercontent.com/37901240/125319007-acb3b980-e33a-11eb-8f20-1b02547385f6.png)
![image](https://user-images.githubusercontent.com/37901240/125319148-c94ff180-e33a-11eb-99cd-9f7a102af102.png)

Could you check it please?

_Originally posted by @martinrulf in https://github.com/FortAwesome/Font-Awesome/issues/17402#issuecomment-878400046_

**Comment by martinrulf** [comment]
@tagliala thx

**Comment by robmadole** [comment]
Ok, yep this totally makes sense. I'll get this on the todo list.

**Comment by norwen** [comment]
Hello! Any updates on this one?
@robmadole

**Comment by mlwilkerson** [comment]
I've got a fix ready for this now, on its way to code review.

**Comment by robmadole** [comment]
This has been deployed. I'm going to close the ticket and we can re-open if needed.
