### ISSUE TITLE
Why is there no turn-right icon?

### ISSUE THREAD

**Issue by saeho** [FortAwesome/Font-Awesome#18066]
In FA6, there is a "turn-down", "turn-up" and "turn-down-left" icon.

But there is no "turn-down-right" icon.

Why?

Is it because we can "transform 45deg" the turn-up icon?

Or was this an unintentional bug?

I'd like to know.

**Comment by sensibleworld** [comment]
It's just a complete oversight on my part! When updating 13,000+ icons, I'm bound to miss a few.

I'll get this added.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/turn-down-right?s=solid
