### ISSUE TITLE
Icon request: faCircleExclamation

### ISSUE THREAD

**Issue by brlrb** [FortAwesome/Font-Awesome#18061]
**What can it be used for?**
The font icon "faCircleExclamation" is currently not available in `@fortawesome/free-solid-svg-icons` and it would be useful if we have it to use to alert users on the website.

**Example image (optional)**
- https://fontawesome.com/v5.15/icons/exclamation-circle?style=solid

**Icon request checklist**
- [ yes ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ yes ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ yes ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [  yes ] I have included at least one example image if it could be helpful (optional)
- [ yes  ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The font icon "faCircleExclamation" is currently not available in @fortawesome/free-solid-svg-icons and it would be useful if we have it to use to alert users on the website.

Could you please clarify? The correct name is `exclamation-circle`, and can be imported ad `faExclamationCircle`

This icon is available in the free set

Demo: https://codesandbox.io/s/fa5-18061-c9ovq?file=/src/index.js

If you have troubles in using the JavaScript API, please take a look at our documentation: https://fontawesome.com/v5.15/how-to-use/on-the-web/advanced/svg-javascript-core

If you still think there is an issue with Font Awesome, please provide a reproducible test case

Hope it helps

Closing here
