### ISSUE TITLE
Stack and duotone misaligned

### ISSUE THREAD

**Issue by cedric-r-mycelium** [FortAwesome/Font-Awesome#18077]
In pure Web Fonts with CSS fa-stack on duotone fa-store-alt and fa-home :after is not align to :before
i have not test all icon

```
<span class="fa-stack">
   <i class="fad fa-store-alt fa-stack-2x"></i>
</span>
<span class="fa-stack">
   <i class="fad fa-homet fa-stack-2x"></i>
</span>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/46491128/125746544-43c556e4-6666-4754-a27a-e35413dbb158.png)

**Version and implementation**
Version: 5.15.3 pro
Browser and version: Firefox 91.0b2  / Edge 91.0.864.67

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please check https://jsfiddle.net/tagliala/8fktzj4h/3/ ?

I cannot replicate on MacOS Firefox 90.0.1 / Chrome 91 / Safari

**Comment by cedric-r-mycelium** [comment]
Thanks for your help.

But it's wrong css property in other css, not error from FrontAwesome.

Sorry for my wrong issue

**Comment by tagliala** [comment]
@cedric-r-mycelium don't worry, glad you solved

Closing here
