### ISSUE TITLE
Icon Request: Teradata logo

### ISSUE THREAD

**Issue by kumarbhaskar8** [FortAwesome/Font-Awesome#18072]
Hi, I am building a Dataiku plugin for Teradata and want to use the Teradata logo for that plugin. 
Dataiku uses **font awesome** for their plugins. This plugin will be very useful for many customers. I kindly request you to add the Teradata logo as a new icon. 

URL for icon 1: https://icons-for-free.com/teradata-1324440242767643357/
URL for icon 2: https://icons8.com/icon/108544/teradata

I hope you will consider my request. 

Thanks,
Kumar Adabala

**Comment by tdEmpl064** [comment]
Hi,

Is there some action we could/should take to facilitate this request move forward, please?
Per the guidelines at https://fontawesome.com/support there appears to have been no promotion of the proposed "icon-teradata" brand icon request to the icon leaderboard at https://fontawesome.com/community/leaderboard/brands.
Please let us know whether you might have icon specifications that were not covered by Kumar's request so we can revise/improve our submission.

Best regards,
Alexander Kolovos.

**Comment by tagliala** [comment]
Superseded by #18746
