### ISSUE TITLE
fa-ad icon is missing

### ISSUE THREAD

**Issue by liorwohl** [FortAwesome/Font-Awesome#18078]
**Describe the bug**
I noticed that "fas fa-ad" font icon I was using stopped showing.
Its also broken in your gallery site
![Screen Shot 2021-07-15 at 11 02 26](https://user-images.githubusercontent.com/10486742/125751990-74918c5a-eb3a-4c31-8864-dfccad68d3cb.png)

**Version and implementation**
Version: 5.15.3
Browser and version: Chrome 91.0.4472.114 in Mac 11.4

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Probably this is due to some ad-blocker

Ref: #18063 and #1799

Hope it helps

Closing here
