### ISSUE TITLE
pls add a discord icon

### ISSUE THREAD

**Issue by brekzR6** [FortAwesome/Font-Awesome#18087]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Discord icon is already available:
- https://fontawesome.com/v5.15/icons/discord

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

If you are requesting to update the logo of discord to the latest version, it will be done in the next release #17897 (no ETA) 

Hope it helps

Closing here
