### ISSUE TITLE
Issue with FA 6 beta OTFs in XD and AI (Big Sur 11.4)

### ISSUE THREAD

**Issue by JamesNortonDesign** [FortAwesome/Font-Awesome#18088]
Just wondering if you have encountered this issue with Beta 6 version of FA when trying use the OTFs. 

**Issue**
When I copy the glyph info from the beta website (say square-glyph or circle-dot) and paste into a text field in XD and set the font to FA 6 Pro it defaults to the system glyph? See image below...

In Illustrator when you choose the font for these two glyphs it just reverts back to Myriad Pro and I can't select the font at all.. All I see is the box with an X in it. Seems to happen for glyphs that might already be in a standard font set and not something custom like 'box with lightning bolt...'

I tried it back with the latest version of FA 5.15.3 and it seems to work ok.
Do you think it is a system issue or a font issue?I'm on a Mac running
Big Sur 11.4
Illustrator 25.3.1
XD 41.1.12.9 x64

![image](https://user-images.githubusercontent.com/25446671/126270467-d11dca86-1e1a-4e58-81dd-7d99874478fa.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

I do not own XD, so I can try to assign to @sensibleworld to check if everything is fine

**Comment by sensibleworld** [comment]
I have a theory on why this may be happening (related to some Unicode changes). I'll investigate and report back!

**Comment by sensibleworld** [comment]
@JamesNortonDesign Would it be possible to share an AI (and XD) file where this issue is happening?

**Comment by JamesNortonDesign** [comment]
Hi Jory,
Sure thing - an update from me...
I downloaded the latest Beta version of the OTFs and this seemed to fix a
lot of the issues.
I needed to remove the old files and restart the computer.
I can still see an issue with Chevron right arrow as this unicode defaults
to a mac default japanese font.
There may be other unicodes that have an issue, but these were just some I
use a lot...

Is there a reason you guys moved away from a unique F unicode naming system?
See example files: Ai files and some JPEGs / PDFs.

*AI*
FA tests.ai
FA tests-Illustrator-Example.jpg

*XD*
FA tests.xd
FA tests-XD-Example.pdf

Cheers,
James

*JND*
*We specialise in visual strategy.*

PO Box 638
Forestville NSW 2087
Australia

Tel: +61 (0) 403 848 604 <+61%20403%20848%20604>
Skype name: jamesnortondesign
FaceTime: +61 403 848 604 <+61%20403%20848%20604>
Instagram: www.instagram.com/jamesnortondesign/

***@***.***
www.jamesnortondesign.com
*______________________*

This email and any attachments may contain confidential or
privileged information intended solely for the use of the intended
recipient. If you are not the intended recipient, you must not copy,
distribute, disclose or use any of the information contained within.
Confidentiality and privilege are not waived or lost by reason of mistaken
delivery to you. If you have received this communication in error, please
notify us by reply email and immediately and permanently delete this
message and any attachments. It is your responsibility to scan this message
and any attachments for computer viruses or other defects. Thank you.

**Comment by sensibleworld** [comment]
@JamesNortonDesign Can you check this issue out with the most recent beta release? Hoping this resolves the issue!

**Comment by sensibleworld** [comment]
Hey James - Two steps forward and one step back! If you wouldn't mind sending me an email at hello@fontawesome.com, I can get you a file to test out that should fix the permissions error.

**Comment by sensibleworld** [comment]
Closing this issue, as I believe the inability to save bug was fixed already. Let me know if not!

**Comment by JamesNortonDesign** [comment]
Hi Jory,
This was fixed by your latest beta.

Ta
James

James Norton
+61 (0) 403 848 604



James Norton Design
PO Box 638
Forestville NSW 2087 Australia
jamesnortondesign.com

   


JND acknowledges the Gai-mariagal, Traditional Custodians of the land on which we live and work. We pay our respect to their Elders past and present and extend that respect to all Aboriginal and Torres Strait Islander peoples today.
