### ISSUE TITLE
Icon request: recepit-lock

### ISSUE THREAD

**Issue by cybvitthal** [FortAwesome/Font-Awesome#18080]
**What can it be used for?**
To display receipt icons with a lock.

**Example image (optional)**
[icon in kit](https://fontawesome.com/kits/014ff667da/uploaded-icons)
![Receipt-Private](https://user-images.githubusercontent.com/24604853/125898634-a4cb1454-6786-48d4-b64f-23269eae523a.png)

We would like to include it in pro-light OTF file. Thanks!

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, and you can achieve an ok-looking icon with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/553/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by cybvitthal** [comment]
If possible, we would like to include  this icons in **pro-light OTF** for FontAwesome. We basically need to for mobile project.

**Comment by tagliala** [comment]
> We already have required SVG. We would like to embed it in font file. (OTF/TTF)

Hi, afaik this is not possible. The [Pro Desktop Subsetter](https://fontawesome.com/v5.15/how-to-use/on-the-desktop/other-topics/subsetter) does not allow to upload custom icon as far as I can tell.

As a Pro customer, you can send an email to hello@fontawesome.com to get dedicated support

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
