### ISSUE TITLE
Icons used in svg mockups

### ISSUE THREAD

**Issue by RitaS** [FortAwesome/Font-Awesome#1809]
My team wants to use Font Awesome in our svg mockups and we have installed the font on our desktops. The problem is that whenever we update to a new version the characters assigned to the icons change, and it becomes problematic to use the font (e.g., bookmark icon changed to other different icon and doesn't make any sense now). Is There any possibility to maintain compatibility with previous versions? Or specify in the version changelog which icons have changed character?

Thanks

**Comment by sensibleworld** [comment]
This has been fixed in all of our recent versions :)
