### ISSUE TITLE
Icon request: LINE

### ISSUE THREAD

**Issue by ppvrpo** [FortAwesome/Font-Awesome#18093]
**What can it be used for?**
Enable people to click and link to LINE official chat from a shopify website.

**Example image (optional)**
![line-icon](https://user-images.githubusercontent.com/87850627/126751285-94a035d4-d9cc-429b-8531-4d7c302cccf6.png)

**Icon request checklist**
- [Single ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [/ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [/ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [/ ] I have included at least one example image if it could be helpful (optional)
- [ /] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Instagram icon is already available:
- https://fontawesome.com/icons/line?style=brands

Line brand guidelines: https://line.me/en/logo

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here

**Comment by ppvrpo** [comment]
Thank you so much for your help! I've tried inserting LINE Icon by typing fab fa-line but it doesn't work. I'm not sure if I've made any mistake or not.
![Uploading Capture-1.JPG…]()

**Comment by ppvrpo** [comment]
> 
> 
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Instagram icon is already available:
> 
>     * https://fontawesome.com/icons/line?style=brands
> 
> 
> Line brand guidelines: https://line.me/en/logo
> 
> If you have troubles in using or upgrading Font Awesome, please check our documentation
> 
> https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use
> 
> Hope it helps
> 
> Closing here
Thank you so much for your help! I've tried inserting LINE Icon by typing fab fa-line but it doesn't work. I'm not sure if I've made any mistake or not.
![Capture-1](https://user-images.githubusercontent.com/87850627/126756809-51de7795-210a-479a-b3ec-e3d3cc000860.JPG)

**Comment by tagliala** [comment]
> Thank you so much for your help! I've tried inserting LINE Icon by typing fab fa-line but it doesn't work. I'm not sure if I've made any mistake or not.

Hi, `line` requires Font Awesome 5.

As I can see from the icon syntax `fa fa-facebook`, this library uses FA4. Since we do not provide support for third-party plugins or libraries, please contact the author and ask to update

If this is a WordPress plugin, you may be interested in our official WordPress plugin: https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/wordpress, which has a system to detect and resolve conflicts

**Comment by ppvrpo** [comment]
Thank you so much!
