### ISSUE TITLE
Missing ad icon

### ISSUE THREAD

**Issue by kanadaj** [FortAwesome/Font-Awesome#18094]
**Describe the bug**
The icons for `fa-ad` are missing both on our own website and on the Font Awesome docs page

**To Reproduce**
https://fontawesome.com/v5.15/icons/ad?style=solid

Check the missing icons in the "In the Wild" section

**Expected behavior**
It should display properly

**Screenshots**

**Version and implementation**
Version: 5.13 Pro, also on the live docs website
Browser and version: Confirmed on Chromium based Edge (latest) and on Firefox (latest)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by kanadaj** [comment]
Actually, it appears to be ad blockers that cause the issue. EasyList or something, seems to somehow block fa-ad...

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, it is ad-block related. Please contact the author of the blocking list

Ref: #1799

Closing here
