### ISSUE TITLE
Icon request: HackerRank logo

### ISSUE THREAD

**Issue by AnshikaSharma210** [FortAwesome/Font-Awesome#18101]
Please include the icon of HackerRank too. I need to use it in my website and can't find it here.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Hackerrank icon is already available:
- https://fontawesome.com/v5.15/icons/hackerrank?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
