### ISSUE TITLE
fas fa-cog

### ISSUE THREAD

**Issue by frei19jerez** [FortAwesome/Font-Awesome#18103]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cog icon is already available:
- https://fontawesome.com/v5.15/icons/cog?style=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
