### ISSUE TITLE
fas fa-code

### ISSUE THREAD

**Issue by frei19jerez** [FortAwesome/Font-Awesome#18102]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Code icon is already available:
- https://fontawesome.com/v5.15/icons/code?style=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
