### ISSUE TITLE
Google Products icons are not available 

### ISSUE THREAD

**Issue by Ash515** [FortAwesome/Font-Awesome#18100]
If it is nice to have all google products icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Some of the icons mentioned in the title already exist in the set:

- https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=google&s=brands

and other exist as a request (e.g.: #13295, 4655, #541): please add a 👍🏼 reaction to those requests

If you want to request more google services, please search for existing requests at https://github.com/FortAwesome/Font-Awesome/search?type=Issues (also search for synonyms or variations), then feel free to open individual requests for the missing icons in the free repository

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
