### ISSUE TITLE
Icon request: jxl

### ISSUE THREAD

**Issue by danielfranz** [FortAwesome/Font-Awesome#18116]
Thanks for your great work. Awesome stuff. Suggesting a JXL logo icon for the Brands style.

**What can it be used for?**
Atlassian and Jira logo icons already exist. Would be great to also have a JXL icon to use along with them.

**Example image (optional)**

Vector data:

![dark](https://jxl.app/public/jxl-icon-mono-dark-transparent.svg)

![light](https://jxl.app/public/jxl-icon-mono-light-transparent.svg)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
This has been added in 6.5.2: https://fontawesome.com/icons/jxl?f=brands&s=solid
