### ISSUE TITLE
Icon request: Devil face/Pitchfork

### ISSUE THREAD

**Issue by Gingrposh** [FortAwesome/Font-Awesome#18111]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To symbolize evil or mad or grumpy

**Icon request checklist**
- [x] This is a single icon or matched pair 'lock'
- [x] The title starts with "Icon request: " and is followed by the requested icon name 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Evil faces 👿  😈  will be available in FA6 Pro and are already part of the beta

https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=face%20horns&s=solid

Closing here
