### ISSUE TITLE
icon ad not working

### ISSUE THREAD

**Issue by salimbenchaaben** [FortAwesome/Font-Awesome#18118]
i was using this icon "fas fa-ad" and it was working fine but suddenly it vanished.
i checked the website and i found the title without the icon so please can you verify it.
![Capture2](https://user-images.githubusercontent.com/44969407/127365495-16a1f599-78d7-4fae-a50b-e25e7296a2c0.PNG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is an issue with a third party ad-blocker

Please contact the ad-blocker list developer and ask to exclude the icon from the rules

Ref: #18094 #1799

Hope it helps

Closing here

**Comment by Xuanvy195** [comment]
> tôi đang sử dụng biểu tượng này "fas fa-ad" và nó đang hoạt động tốt nhưng đột nhiên nó biến mất. 
> Tôi đã kiểm tra trang web và tôi tìm thấy tiêu đề không có biểu tượng, vì vậy bạn có thể xác minh nó không.
> ![Capture2](https://user-images.githubusercontent.com/44969407/127365495-16a1f599-78d7-4fae-a50b-e25e7296a2c0.PNG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is an issue with a third party ad-blocker

Please contact the ad-blocker list developer and ask to exclude the icon from the rules

Ref: #18094 #1799

Hope it helps

Locking here 🔒
