### ISSUE TITLE
Icon request: shovel

### ISSUE THREAD

**Issue by Gingrposh** [FortAwesome/Font-Awesome#18110]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
To symbolize a digger or digging in general
**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair 'lock'
- [x] The title starts with "Icon request: " and is followed by the requested icon name 
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] The request is for a concrete object

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Shovel is available in FA5 Pro: https://fontawesome.com/v5.15/icons/shovel?style=solid

Ref: #2257
