### ISSUE TITLE
Icon request: icon-input-text

### ISSUE THREAD

**Issue by pengbo-netquity** [FortAwesome/Font-Awesome#1811]
This icon will tell user that it is for single line text input field.

**Comment by mikethedj4** [comment]
+1 

![textbox](https://cloud.githubusercontent.com/assets/2473707/5607353/c48bf694-941d-11e4-9b2c-5797bbdbf225.png)

**Comment by henleywc** [comment]
+1

**Comment by dmland** [comment]
+1, but not with the letter "I", because, first, "i" or "I" means Italic in text editors (sorry, people who speak other languages than English), and second, it looks too much like a text input cursor. "A" is probably a better choice.

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.

**Comment by JeroenHauser** [comment]
Cannot see it in the 4.4.0?
I can see a cursor, but not one indicating a textfield (see pengbo-netquity example)

**Comment by mulvaney** [comment]
This doesn't seem to be in 4.4.0.  Can we reopen it, or was the icon voted down?

**Comment by tagliala** [comment]
Sorry...

Please open a new request with another example
