### ISSUE TITLE
Security Issue in conflict detection

### ISSUE THREAD

**Issue by stone2dbone** [FortAwesome/Font-Awesome#18114]
My employer uses Fortify software by Micro Focus to scan our projects for security vulnerabilities. A scan of my project resulted in the attached finding. Anyone have any recommendations as to how to correct this or explain what is actually happening if it is not a  vulnerability?

![fontAwesomeStigError](https://user-images.githubusercontent.com/19313052/127210410-fdbf47fe-9adc-455e-a750-ecf0d6870e45.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please wait for confirmation by @robmadole 

In version [5.10.0](https://github.com/FortAwesome/Font-Awesome/blob/5.10.0/CHANGELOG.md#5100---2019-07-29), a new script has been added to detect conflicts  **for diagnostic use only**

Ref: https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/conflict-detection

This script **is not part of the production code** and should not be included / deployed on a server / loaded from a web page in normal conditions

As per the offending lines of codes

https://github.com/FortAwesome/Font-Awesome/blob/d79d85c3fad85ad1885e87ed558f4afd6fce8289/js/conflict-detection.js#L730

https://github.com/FortAwesome/Font-Awesome/blob/d79d85c3fad85ad1885e87ed558f4afd6fce8289/js/conflict-detection.js#L797

as a non JavaScript developer, I can't tell if there is a security issue

**Comment by stone2dbone** [comment]
Thanks, for this information. I haven't specifically ENABLED the conflict detector script, and I don't need it, so it sounds as if it should be safe for me to remove the files altogether. I will confirm that functionality is not affected and proceed. Thank you.

**Comment by tagliala** [comment]
@robmadole since the question has been asked again at #18434, I'm going to ask if this should/could be addressed, if we are interested in a PR showing how to mitigate this, or if it is ok since this is a diagnostic tool that should not be used in production

**Comment by tagliala** [comment]
@robmadole question asked again in #18489
