### ISSUE TITLE
Some icons appearing very large

### ISSUE THREAD

**Issue by GreenpointWebmaster** [FortAwesome/Font-Awesome#18126]
**Describe the bug**
Seemingly overnight, SOME icons on one of our client websites is appearing very large, other appear just fine.

**To Reproduce**
On the mobile menu of https://www.nutriment.co.uk you will see for the second group of menu items, there is a prefix which is font awesome icons. You will see all the font awesome icons which are solid (those which are fas- icons) have grown huge.

**Expected behavior**
These solid fas icons should appear the same size as the smaller far icons, as they did yesterday

**Screenshots**
![image](https://user-images.githubusercontent.com/88193834/127651894-a7f583f6-c1ea-466b-a225-5a220ed92bd0.png)

**Version and implementation**
Version: No idea, how can I check? I just used this code for example: <i class="fas fa-truck"></i>
Browser and version: Any and all

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fix this custom CSS rule:

![image](https://user-images.githubusercontent.com/556268/127655851-60268a6a-49c7-4f60-a526-c3d6aa256e1b.png)

Hope it helps

closing here
