### ISSUE TITLE
Icon request: Icons for barber shops (Moustache, Beard, Hair, Razor)

### ISSUE THREAD

**Issue by dejvidko** [FortAwesome/Font-Awesome#18127]
**What can it be used for?**
We are making a website for a barbershop but we were very surprised that there are no icons like mustache, beard, hair, razor, or even shampoo or pomade. It is very hard to make a menu without these icons. 

**Example image (optional)**
![github ikonky](https://user-images.githubusercontent.com/88290591/127784407-0b251047-ac06-4dbf-b6e4-065bfe80948d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for sets do not meet our contributing guidelines

Feel free to request individual icons, but please search for existing requests at https://github.com/FortAwesome/Font-Awesome/search?type=Issues (also search for synonyms or variations).

E.g.: moustache #3356

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
