### ISSUE TITLE
TikTok Icon Issue

### ISSUE THREAD

**Issue by lindsayavellino** [FortAwesome/Font-Awesome#18129]
Hello, 
I'm using the tiktok icon on my site and it isn't showing up at all. I have checked I am using the correct code.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please provide a link to your website or a reproducible test case?

**Comment by lindsayavellino** [comment]
hi! yes it's https://www.onwildlife.org/ located in the top right.

**Comment by birdmii** [comment]
Hello! Have you checked the Font Awesome version using on your website? 
I changed the Font Awesome cdn version to 5.15.4 on chrome dev tool and the tiktok icon showed up right away. 
On this link [https://fontawesome.com/v5.15/icons/tiktok?style=brands](url) you can also check an updated version of this icon. 
It's currently 5.14.0. Hope this helps!

**Comment by tagliala** [comment]
Hi @birdmii thanks

@lindsayavellino apologies for the late reply

I can see that your website is using Font Awesome 5.8.2, and everything said @birdmii is correct

Hope it helps, closing here
