### ISSUE TITLE
Icon Request: fa-jira

### ISSUE THREAD

**Issue by sakshamgupta789** [FortAwesome/Font-Awesome#18133]
please include jira icon, thanks so much 
https://vecta.io/symbols/85/brands-ja-jz/33/jira-icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Jira icon is already available:
- https://fontawesome.com/v5.15/icons/jira?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
