### ISSUE TITLE
Icon request: icon-vault (icon-safe, icon-strongbox)

### ISSUE THREAD

**Issue by jitenm** [FortAwesome/Font-Awesome#1813]
Huge fan - thanks very much for your continued superb contributions!

Would love a vault (like a bank vault or a safe which stored offline goods securely). We would use this denote something had been stored safely offline, where it could not again be accessed online.

Thanks in advance!

**Comment by RaphaelRheault** [comment]
+1 please

**Comment by MatthewLilley** [comment]
+1

**Comment by gvlekke** [comment]
+1

**Comment by slejnej** [comment]
+1 for this. Can contribute if needed. Just please add it to next update.

Thank you in advance.

**Comment by michalmau** [comment]
+1

**Comment by aubrianpeters** [comment]
+1

**Comment by etweb37** [comment]
+1

**Comment by FinlayDaG33k** [comment]
+1

**Comment by po7a7o** [comment]
+1

**Comment by heliohead** [comment]
+1

**Comment by SnowboiTheGr8** [comment]
+1

**Comment by kboronka** [comment]
+1

**Comment by sanbotto** [comment]
+1

**Comment by jpsantos7** [comment]
+1

**Comment by robertholf** [comment]
+1 Please!

**Comment by repat** [comment]
+1 :)

**Comment by tfjorge** [comment]
+1

**Comment by bobbybouwmann** [comment]
+1

**Comment by bessone** [comment]
+1

**Comment by TCardinal** [comment]
+1 

also with an open door

**Comment by W4775** [comment]
+1

**Comment by Krystian95** [comment]
+1

**Comment by alex-woodall-premierfoods** [comment]
+1

**Comment by lodb** [comment]
+1 here!

**Comment by Nisutec** [comment]
+1

![Image of  vault icon](https://cdn2.iconfinder.com/data/icons/security-add-on-glyph/48/Sed-04-512.png)

**Comment by jeisel-northglenn** [comment]
+1

**Comment by nakwa** [comment]
+1
![image](https://user-images.githubusercontent.com/5612181/77983074-4d30c680-730e-11ea-8ed7-cde6fc19de2f.png)

**Comment by mahdimortazavi** [comment]
+1 Please!

my suggestion
[safebox.zip](https://github.com/FortAwesome/Font-Awesome/files/5304698/safebox.zip)

**Comment by sensibleworld** [comment]
This has been added to the latest release of our v6 Alpha: https://fontawesome.com/download
