### ISSUE TITLE
Icon request: chess set (chess coins, 12 icons)

### ISSUE THREAD

**Issue by fellowgeek** [FortAwesome/Font-Awesome#1815]
Hi,

thanks for all the awesome work, can you create a set of chess piece icons, both black and white.

Thanks

**Comment by gugulethu** [comment]
+1

**Comment by jheusala** [comment]
+1

**Comment by IanKroniX** [comment]
+1

**Comment by jmz-b** [comment]
+1

**Comment by AnhaytAnanun** [comment]
+1

**Comment by tronsha** [comment]
+1

**Comment by Aidurber** [comment]
+1

**Comment by DJIO** [comment]
+1

**Comment by Garrcomm** [comment]
+1

**Comment by fellowgeek** [comment]
+8

**Comment by jbkunst** [comment]
+9

**Comment by posixpascal** [comment]
This issue is almost 2 years old and I still get +1 in my inbox regulary. 

Any updates on this? I think the potential is huge.

**Comment by faeb187** [comment]
+1

**Comment by vnenkpet** [comment]
+1

**Comment by zbeekman** [comment]
+1

**Comment by atsepkov** [comment]
+1

**Comment by lemtzas** [comment]
+1

**Comment by nIQnutn** [comment]
+1

**Comment by Assios** [comment]
+1

**Comment by atsepkov** [comment]
FYI, just found out that chess pieces are already included in unicode (♔♕♖♗♘♙♚♛♜♝♞♟): https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode

I would, however, like if the font included more medieval items like catapults, bows, maces, swords, etc.

**Comment by darkenedsky** [comment]
+1. What are your criteria for selecting what to do? Seems many icons have large numbers of +1 and still don't get produced.

**Comment by jbkunst** [comment]
+ 1e100

**Comment by Mindstormer619** [comment]
+1

**Comment by jtouza** [comment]
+1

**Comment by kingofkingshf** [comment]
+1

**Comment by benbern** [comment]
+1

**Comment by slayer925** [comment]
+1 (specially for the king crown)

**Comment by staff0rd** [comment]
:+1:

**Comment by cguilhermef** [comment]
+1

**Comment by chgc** [comment]
+1

**Comment by jbnv** [comment]
+1

**Comment by mziii** [comment]
+1

**Comment by Dub5tep** [comment]
+1

**Comment by shajjar-zenefits** [comment]
+1

**Comment by brunobbbs** [comment]
+1

**Comment by cottie** [comment]
+1

Chess Merida would be a nice design:
![chess_merida](https://cloud.githubusercontent.com/assets/19688969/15712661/7ca5764e-2813-11e6-9217-c15a4b790830.gif)

It's a freeware True Type Font by Armando H. Marroquin (http://www.enpassant.dk/chess/downl/merid_tt.zip)

**Comment by cguilhermef** [comment]
YES cottie!! Just this icons included in FA.

I can´t understand why they do not did it yet.

**Comment by k24dizzle** [comment]
+1

**Comment by Lmpessoa** [comment]
+1. A rook, in special.

**Comment by Luke1298** [comment]
+1

**Comment by Arvraepe** [comment]
+1

**Comment by py-crash** [comment]
+1

**Comment by vladimirsolovey** [comment]
+1

**Comment by lasley** [comment]
👍  - It saddens me having to use Glyphicons for this 😦

**Comment by vichou** [comment]
+1

**Comment by tejassharma96** [comment]
+1

**Comment by figaw** [comment]
+1

**Comment by faeb187** [comment]
http://www.dafont.com/chess.font
parts for the board in font included =)

**Comment by camccar** [comment]
+1

**Comment by Luc45** [comment]
+1 - How long until they implement this?

**Comment by migueltorrescosta** [comment]
+1

**Comment by qwertologe** [comment]
+1

**Comment by zachinscho** [comment]
+1

**Comment by cguilhermef** [comment]
READ BEFORE "add +1"

Ladies and gentlemen, when you like some idea in a Github issue, don't flood the issue using "+1"! Just use the "reaction" button. Issue isn't to "feature vote"! 

Yes, I done it too. I was wrong. But a learn that it is wrong and now I'm tryng to teach it to another people.

**Comment by vasiliyaltunin** [comment]
Hi all i created iconset for chess based on old ChessMerida font, you can find all info here https://github.com/vasiliyaltunin/chess-merida-font i hope it helps you.

**Comment by davegandy** [comment]
This will be in 5.0.5.

**Comment by sensibleworld** [comment]
These are live! https://fontawesome.com/icons?d=gallery&c=chess
