### ISSUE TITLE
vip icon

### ISSUE THREAD

**Issue by CyberDepot** [FortAwesome/Font-Awesome#18153]
hi
i cant find vip icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> i cant find vip icon

It does not exist in the set

There is a request for "VIP" in #2862, please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
