### ISSUE TITLE
Icon request: VueJS

### ISSUE THREAD

**Issue by Yash-Singh1** [FortAwesome/Font-Awesome#18163]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

VueJS is a framework for building web apps

**Example image (optional)**
Insert the example image here if necessary.
![](https://vuejs.org/images/logo.svg)
**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Vue icon is already available:
- https://fontawesome.com/v5.15/icons/vuejs?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
