### ISSUE TITLE
fontawesome's flags

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18167]
Hi,

Please add country flags as well as international organizations flags, e.g. United Nation.

Squares, Circle, Rectangle..

Thanks,
Jassim

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

At the moment we are accepting individual requests with flags that make sense in single color, take a look here: https://github.com/FortAwesome/Font-Awesome/labels/flags%20%28category%29

Anyway, please keep in mind that a lot of world flags doesn't make sense in single color (🇫🇷 , 🇮🇹 , 🇧🇪 , 🇮🇪, 🇷🇴 , 🇹🇩 , 🇭🇺 , 🇳🇱 , 🇷🇺, ...), so we should provide full color svgs just like other flag libraries out there

Hope it helps

Closing here
