### ISSUE TITLE
What happened to Tripadvisor icon

### ISSUE THREAD

**Issue by gab1982** [FortAwesome/Font-Awesome#18164]
Hi guys I was using the tripadvisor font awesome icon on my site but it now no longer works and I cannot find it in the fontawesome.com library, will it be coming back?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Tripadvisor asked to remove the icon, it will not come back

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5154---2021-08-04
