### ISSUE TITLE
Icon request: line-chat

### ISSUE THREAD

**Issue by venser2020** [FortAwesome/Font-Awesome#18161]
**What can it be used for?**
Same use as the other Social Networks that are available on Fontawesome.

**Example image (optional)**
https://th.bing.com/th/id/R.2af2421409002257776b3cc36794a6cc?rik=iQos%2fm1LVAQooA&riu=http%3a%2f%2fexpandedramblings.com%2fwp-content%2fuploads%2f2014%2f05%2fLINE_icon01.png&ehk=nCsPN2QFPVLU4oyDP48%2fpbUxKAG9wtLXdDG0LWR7ccg%3d&risl=&pid=ImgRaw&r=0.

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)
- 
![Linechat](https://user-images.githubusercontent.com/64116701/129168228-7d88b17d-970a-4bd7-a46e-4d90bf48ca9b.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Line icon is already available:
- https://fontawesome.com/v5.15/icons/line?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here
