### ISSUE TITLE
Wrong Discord Icon

### ISSUE THREAD

**Issue by surphury** [FortAwesome/Font-Awesome#18171]
When I try to get this icon:
 ![image](https://user-images.githubusercontent.com/68794693/129505250-69a457eb-9be4-48c8-aadb-664b712c226e.png)

I get this one:
 ![image](https://user-images.githubusercontent.com/68794693/129505347-29777684-f36c-44cd-9be4-e013b3340a14.png) 

Using this HTML code:
![image](https://user-images.githubusercontent.com/68794693/129505566-da1b53e7-f953-42f7-b9ec-e3986c108bd7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The Discord icon has been updated in version 5.15.4, as per docs: https://fontawesome.com/v5.15/icons/discord?style=brands. Please make sure that your application is using version 5.15.4

Please notice that some third party libraries/framework may override your Font Awesome installation and give priority to an older version

Refer to https://fontawesome.com/start for starting guide

Hope it helps

Closing here, but feel free to comment
