### ISSUE TITLE
What is the correct way to import FA Solid icons?

### ISSUE THREAD

**Issue by streater3000** [FortAwesome/Font-Awesome#18188]
I am able to import Regular and Brand icons... but not the solid icons. I am using this in my header:

`<link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet" />
`

BTW... this is how I am formating the CSS so it should work on that end:
`author-name:before{
content:"\f007";
  font-family: 'Font Awesome\ 5 Free';
font-weight: 900;
}`
Any ideas here to get solid icons?

**Comment by tagliala** [comment]
Closing in favor of #18188
