### ISSUE TITLE
Icon request: icon-chair

### ISSUE THREAD

**Issue by SophieRSG** [FortAwesome/Font-Awesome#18185]
**What can it be used for?**
Describe how this could be used / the use case for this icon.
For selling or representing furniture or objects in the home (e.g. chair, vase, sofa, bed, lamp)

**Example image (optional)**
Insert the example image here if necessary.
![image](https://user-images.githubusercontent.com/89204140/130079115-d5a499d2-535f-4d5f-96c0-60ad00b7f3e9.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hey there! We've got a few options for "chair" icons in both Font Awesome 5 (https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=chair) and Font Awesome 6 (https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=chair&s=solid).
