### ISSUE TITLE
fa fa-tiktok

### ISSUE THREAD

**Issue by RobertoRangel** [FortAwesome/Font-Awesome#18181]
Hello!

Please help me to create an icon for my old website. I need the icon "fa fa-tiktok" in version 4.7.0. Please

Thank you so much for your support!

**Comment by sensibleworld** [comment]
Hey Roberto!

We're no longer adding new icons to 4.7, but we do have Tiktok icon in version 5 (and 6!) https://fontawesome.com/v5.15/icons/tiktok?style=brands

**Comment by RobertoRangel** [comment]
Okay!  Thank you very much for attending my request.

**Comment by 1810-will** [comment]
how can i get the icon version for tiktok

**Comment by tagliala** [comment]
Just update Font Awesome

**Comment by 1810-will** [comment]
what is the updated version of font awesome

**Comment by manueldinisjunior** [comment]
Hi!

The fa-tiktok icon does not exist in Font Awesome 4.7.0 — it was added much later in version 5.15.3, so you won't be able to use it natively in that version.

How you fix this depends on your setup. If you're using **WordPress** with the **Salient Theme**, here's exactly how to solve it:

Go to Salient Theme Options → Social Media and paste your TikTok URL into the TikTok field
Go to Theme Options → Custom CSS and add:

css.fa.fa-behance:before {
  font-family: "Font Awesome 5 Brands" !important;
  content: "\e07b" !important;
}

Go to Theme Options → General → Do the hard-refresh to your browser (Ctrl+Shift+R)

⚠️ Note: this fix substitutes the white Behance icon and replaces it with the TikTok glyph. If you actively use the Behance icon elsewhere on your site, this will affect it too.

If you're not using Salient, the approach will differ depending on your theme and setup — you'll need to either upgrade Font Awesome or use a custom SVG icon as a workaround.
Hope this helps! #18181

**Comment by 1810-will** [comment]
Thank you for the information
