### ISSUE TITLE
tripadvisor missing in 5.15

### ISSUE THREAD

**Issue by aten-dev-avalade** [FortAwesome/Font-Awesome#18180]
The icon is not found in https://fontawesome.com/v5.15/icons/tripadvisor?style=brands
The icon cannot be used in CSS via fa-tripadvisor or content: "\f262"

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Tripadvisor asked to remove the icon and it has been done in version 5.15.4

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5154---2021-08-04
