### ISSUE TITLE
Icon request: comment-question

### ISSUE THREAD

**Issue by web-tailor** [FortAwesome/Font-Awesome#18197]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

The icon comment-exclamation exist in the icon library. It would be great to pair it with a comment-question icon. In that way, you can use it to build up an FAQ (question, answer).

**Example image (optional)**
Insert the example image here if necessary.

![comment-question](https://user-images.githubusercontent.com/52778434/130431430-339fde5c-88ff-4215-82ed-36c809b8bbfb.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
We've added one as part of Font Awesome 6! https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=comment%20question&s=solid
