### ISSUE TITLE
Icon request: Pregnant woman

### ISSUE THREAD

**Issue by rmalago** [FortAwesome/Font-Awesome#1819]
Example:
http://pictogram-free.com/material/172.png
http://t1.ftcdn.net/jpg/00/23/54/72/400_F_23547221_VFmiD8GptHEg70MTKsixCzHSekCTZHiv.jpg 
http://t2.ftcdn.net/jpg/00/48/18/91/110_F_48189147_pyDiHpj6sHcogVFRrs2RTDhXGA3BXYdD.jpg

**Comment by desix75** [comment]
+1 Pregeant Woman

and Woman with Child

**Comment by Asparagirl** [comment]
+1

**Comment by jpsantos7** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by roberthantink** [comment]
+1

**Comment by pitkiwi** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by SamiJansen** [comment]
+1 Pregnant woman

**Comment by mahi13c** [comment]
+1 Pregnant woman

**Comment by samshameem** [comment]
+1 Pregnant woman

**Comment by alexfoxetech** [comment]
+1

**Comment by Qraxin** [comment]
+1

**Comment by alexfoxetech** [comment]
+1

**Comment by sansagara** [comment]
+1 for Pregnant Woman/ Woman with CHild

**Comment by pystucki** [comment]
+1

**Comment by drooog** [comment]
+ 1 Pregnant Woman

**Comment by vitorccs** [comment]
+1

**Comment by RafaelAngelRamirez** [comment]
+1 for a pregnant woman

**Comment by ondouglas** [comment]
+1 for pregnant woman.
Example https://www.flaticon.com/free-icon/pregnant_1014552?term=pregnant&page=1&position=8

**Comment by LoGA80** [comment]
+1 for pregnant woman icon.
Could be similar to female with a bigger belly or some indication of the pregnancy (small heart/baby icon inside the belly area)

**Comment by beohoang98** [comment]
+1 for pregnant woman.

**Comment by lizzbrazen** [comment]
+1

**Comment by Cundalf** [comment]
+1
