### ISSUE TITLE
Tiktok Icon Glyph code isn't working correctly

### ISSUE THREAD

**Issue by Frazzz101** [FortAwesome/Font-Awesome#18198]
Copying the glyph code for the Tiktok icon is resulting in as if the font isn't installed (it is though and all other icons are fine!)

**Comment by tagliala** [comment]
Hi, we had some problems with TikTok in older version, please make sure you are using Font Awesome 5.15.4

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

If you still think there is an issue with Font Awesome, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case
