### ISSUE TITLE
Lower scripts file for Angular

### ISSUE THREAD

**Issue by dfquicazanr** [FortAwesome/Font-Awesome#18201]
**Is your feature request related to a problem? Please describe.**
I'm adding font-awesome to an angular project and I want to use it with angular material, I mean, as explained [here](https://stackoverflow.com/a/54276496/6616058). The only issue is that the scripts file got 7mb bigger when I added the font-awesome pro js file. Is there a way to be able to load the icons and have them compatible with angular material, (<mat-icon>...) but keeping the scripts file smaller?

**Describe the solution you'd like**
A smaller js file or a way to import the library that only loads the icons I need

**Describe alternatives you've considered**
I've tried only calling the js files related to the kind of icons I'm using but got some issues with some icons not loading correctly, I changed to the minified version (is still too big). I've considered [@fortawesome/angular-fontawesome](https://www.npmjs.com/package/@fortawesome/angular-fontawesome) but I didnt's see any compatibility with angular-material.

**Additional context**
-

**Feature request checklist**
- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [-] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome-Pro/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
You could try using our Pro subsetter to create smaller JS files: http://fontawesome.com/download

(Sorry for the super long delay in reply!)
