### ISSUE TITLE
Create API Please

### ISSUE THREAD

**Issue by borm** [FortAwesome/Font-Awesome#1820]
Hi,
create pleae API for use in our CMS Admin Panel
We will get your api json, and check new icon

**Comment by tagliala** [comment]
Let's continue on #14821

**Comment by whoiswillian** [comment]
i've done something like that and using a free azure service, so, if someone want to me to mantain, i'll need money or just dont abuse.

https://icon-leets.azurewebsites.net/api/Icons

skip take like

https://icon-leets.azurewebsites.net/api/Icons?skip=0&take=10 <---- this is default, params are not needle

and search like that

https://icon-leets.azurewebsites.net/api/Icons?search=instagram // {partial term or partial name} like "instagram" or "yout"

is fully on code, dont use DB
