### ISSUE TITLE
Wordpress Theme Nightmare, - some icons work, some do not. HELP!

### ISSUE THREAD

**Issue by norfolknetworks** [FortAwesome/Font-Awesome#18209]
Hi,

I'm trying to recreate my website (built on a web builder) into Wordpress. 

I purchased a Theme called 'Create' and none of the icons worked. Whilst I'm not new to Wordpress, I'm a little rusty, but I've never seen error codes like this before: "has been blocked by CORS policy:...etc" My test site is riddled with them.

OK... so, after days of research, - I've now downloaded the Font Awesome's WP plugin, AND set up one of the kits. Only 'half' the problem has been solved. 

I can now see the icons on my Menu and Footer, but all other icons are still showing just a square. The crazy thing is, they work ONLY on Safari (iPhone test) but not on ANY other Browser.

What I'm looking for is the fix. I'm in constant contact with the Theme Developers, my Hosts (GoDaddy) and now you guys - nobody seems to know what to do? With each party appearing to blame another party.

Here's my test site so you can see what I'm talking about, www.krumble.co.uk 

ALL and ANY help is appreciated! This is just becoming ridiculous! 

Thanks again,

Richard

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I purchased a Theme called 'Create' and none of the icons worked. Whilst I'm not new to Wordpress, I'm a little rusty, but I've never seen error codes like this before: "has been blocked by CORS policy:...etc" My test site is riddled with them.

The purpose of this repository is to track issues related to Font Awesome. We do not provide support to third party plugins/libraries/themes and we do not offer support about generic configuration issues with CORS

Third-parties may load a different / outdated version of Font Awesome which conflicts with the one you are loading through kits. The official WordPress plugin offers a conflict detection scanner, you can read about it at https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/wordpress#troubleshooting

If you have troubles in using the conflict detector, please try the dedicate WordPress support forum at https://wordpress.org/plugins/font-awesome/ 

Again, apologies if this could be frustrating on the developer side, but there are a lot of different ways of using Font Awesome, and this repository should be used to report bugs of the main implementation

Said so...

> Here's my test site so you can see what I'm talking about, www.krumble.co.uk

I can see from the browser development console that:

1. there are a lot of JavaScript errors unrelated to Font Awesome. Please fix those before debugging FA
  ![image](https://user-images.githubusercontent.com/556268/131223285-34ca4ca3-faad-47b4-b1f3-37c41026fbfd.png)

2. `themetrust-create` is loading FA 4.7 is trying to load Font Awesome 4 but fails on CORS
  ![image](https://user-images.githubusercontent.com/556268/131223338-ffc6c027-f586-40a0-a396-4c9ba9afd11b.png)


3. The kit is loaded twice, please remove one of the occurrences from the HTML source

Hope it helps

Closing here but feel free to comment

**Comment by norfolknetworks** [comment]
Hi Tagliala,

Thank-you very much for taking the time to respond, I appreciate it and it's helped me a lot.

Thank-you :)

Richard
