### ISSUE TITLE
arrow

### ISSUE THREAD

**Issue by ZahraRahmanii** [FortAwesome/Font-Awesome#18211]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a lot of arrow-related icons:
- https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=arrow&s=solid&m=free

[Even more are coming in FA6](https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=arrow&s=solid&m=free), including [bow-arrow](https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=bowarrow&s=solid) for our Pro customers

There also a lot of requests to include more arrows:
- https://github.com/FortAwesome/Font-Awesome/search?q=arrow&type=issues

If you want to request an arrow-related icon which is not in the set and it has not been requested already, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example

Hope it helps

Closing here
