### ISSUE TITLE
"Forgot Password"

### ISSUE THREAD

**Issue by MarkusDa2nd** [FortAwesome/Font-Awesome#18210]
Hello, 
 So I am having a problem back into Font Awesome. I have forgotten my password so I clicked the forgotten password link after that, I was asked to put in my email address, this is standard. When I put in my email, I got confirmation that I would be sent some help but I never received any email from Font Awesome! Even after I tried again and again, several times, I still have never received an email from Font Awesome. 
Help me please!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Did you check the spam folder? It is not explicitly stated in the opening post

Anyway, please send an email to hello@fontawesome.com explaining your issue

Hope it helps

Closing here, but feel free to comment
