### ISSUE TITLE
all js icons presented as free but in fact compiled over pro.css version

### ISSUE THREAD

**Issue by jehkinen** [FortAwesome/Font-Awesome#18224]
![image](https://user-images.githubusercontent.com/3656173/131580194-2a37624a-0349-4346-990b-80915dbeb6a1.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this issue?

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by jehkinen** [comment]
@tagliala hello, sure. All js (square, node and etc) icons missed from free version of font awesome, but on the site they could be found with free filter

**Comment by tagliala** [comment]
> All js (square, node and etc) icons missed from free version of font awesome

I can't confirm: https://jsfiddle.net/tagliala/fmo25dxa/1/

Any reproducible test case?

There are a lot of ways of using Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

**Comment by jehkinen** [comment]
I think it was wrong prefix usage for brand icons
