### ISSUE TITLE
Networking Icons

### ISSUE THREAD

**Issue by danieltkach** [FortAwesome/Font-Awesome#18223]
This can be used in so many different areas. I'd need them to display a network graph.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from new icon request template:

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request. Please make sure to provide a good title and an example

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here
