### ISSUE TITLE
Icon request: domains

### ISSUE THREAD

**Issue by shukiv** [FortAwesome/Font-Awesome#18222]
Hello,

It would be very nice to have domains related icons. Like
'www' for example.
.org https://en.wikipedia.org/wiki/.org
.com': https://en.wikipedia.org/wiki/.com

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request. Please make sure to provide a good title and an example.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
