### ISSUE TITLE
@fortawesome/fontawesome-common-types appears to be missing FontAwesome 6 icons

### ISSUE THREAD

**Issue by jessicalc** [FortAwesome/Font-Awesome#18237]
**Describe the bug**
We have a pro account and are trying to upgrade to FontAwesome 6 🎉 It doesn't appear that FontAwesome common types have been upgraded for V6. Is this a known issue, or am I missing something? 

**To Reproduce**

Our package.json looks like th is:
```
    "@fortawesome/fontawesome-pro": "next",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
    "@fortawesome/pro-light-svg-icons": "next",
    "@fortawesome/pro-solid-svg-icons": "next",
    "@fortawesome/react-fontawesome": "^0.1.15",
```

With FontAwesome 5, we were able to use `<FontAwesome icon="user-circle" />`  just fine. 

After upgrading to FontAwesome 6, I have to do the following to make the icon work: 

```
<FontAwesome icon={['fas', 'circle-user']} >
```

However, I end up with a typescript error coming from common types:
`Type '"circle-user"' is not assignable to type 'IconName'`  The circle-user details page (https://fontawesome.com/v6.0/icons/circle-user?s=solid) says that `user-circle` should work as an alias, but it doesn't seem to. 

When I look in @fortawesome/fontawesome-common-types, I don't see `circle-user` anywhere: 
https://github.com/FortAwesome/Font-Awesome/blob/7d3d774145ac38663f6d1effc6def0334b68ab7e/js-packages/%40fortawesome/fontawesome-common-types/index.d.ts

I'm experiencing a similar issue with the icon formerly known as `sign-out-alt` and the icon formerly known as `ellipsis-h`. (The alias not working should probably be filed as an additional issue) 

When I run `yarn why @fortawesome/fontawesome-pro`, I get this:
```> yarn why @fortawesome/fontawesome-common-types
├─ @fortawesome/fontawesome-svg-core@npm:1.2.36::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-svg-core%2F-%2F1.2.36%2Ffontawesome-svg-core-1.2.36.tgz
│  └─ @fortawesome/fontawesome-common-types@npm:0.2.36::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F0.2.36%2Ffontawesome-common-types-0.2.36.tgz (via npm:^0.2.36)
│
├─ @fortawesome/free-brands-svg-icons@npm:6.0.0-beta1::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffree-brands-svg-icons%2F-%2F6.0.0-beta1%2Ffree-brands-svg-icons-6.0.0-beta1.tgz
│  └─ @fortawesome/fontawesome-common-types@npm:0.2.36::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F0.2.36%2Ffontawesome-common-types-0.2.36.tgz (via npm:^0.2.33-beta1)
│
├─ @fortawesome/pro-light-svg-icons@npm:6.0.0-beta1::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Fpro-light-svg-icons%2F-%2F6.0.0-beta1%2Fpro-light-svg-icons-6.0.0-beta1.tgz
│  └─ @fortawesome/fontawesome-common-types@npm:0.2.36::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F0.2.36%2Ffontawesome-common-types-0.2.36.tgz (via npm:^0.2.33-beta1)
│
└─ @fortawesome/pro-solid-svg-icons@npm:6.0.0-beta1::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Fpro-solid-svg-icons%2F-%2F6.0.0-beta1%2Fpro-solid-svg-icons-6.0.0-beta1.tgz
   └─ @fortawesome/fontawesome-common-types@npm:0.2.36::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F0.2.36%2Ffontawesome-common-types-0.2.36.tgz (via npm:^0.2.33-beta1)
```

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Thank you! :pray:

**Comment by tagliala** [comment]
@robmadole could you please take a look?

**Comment by robmadole** [comment]
Hi @jessicalc . I think what's going on is that our version numbers are a bit wonky between 5 and 6.

Can you try pinning the version to:

- @fortawesome/fontawesome-svg-core@1.2.33-beta1
- @fortawesome/fontawesome-common-types@0.2.33-beta1

**Comment by jessicalc** [comment]
Thanks @robmadole!

Here's what I have: 

```
    "@fortawesome/fontawesome-common-types": "0.2.33-beta1",
    "@fortawesome/fontawesome-pro": "next",
    "@fortawesome/fontawesome-svg-core": "1.2.33-beta1",
    "@fortawesome/free-brands-svg-icons": "next",
    "@fortawesome/pro-light-svg-icons": "next",
    "@fortawesome/pro-solid-svg-icons": "next",
    "@fortawesome/react-fontawesome": "^0.1.15",
```

However, I'm now getting


```
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@fortawesome/fontawesome-svg-core (/Users/jchong/code/foo/packages/client/build/server/pages/_document.js:160:18)
    at __webpack_require__ (/Users/jchong/code/foo/packages/client/build/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./src/pages/_document.tsx:4:91)
/Users/jchong/code/foo/node_modules/@fortawesome/fontawesome-svg-core/index.es.js:3033
export { noAuto$1 as noAuto, config$1 as config, library$1 as library, dom$1 as dom, parse$1 as parse, findIconDefinition$1 as findIconDefinition, toHtml$1 as toHtml, icon, layer, text, counter, api };
^^^^^^
```

Have you ever come across this? Thanks!

**Comment by robmadole** [comment]
Yes, looks like Typescript is not setup to process `node_modules` but it's trying to load the ES module file anyway (`index.es.js`). I don't know off the top of my head how to fix that one but you [might check the `target`](https://stackoverflow.com/questions/46611503/unexpected-token-import-export-typescript).

**Comment by jessicalc** [comment]
Our current implementation and tsconfig setting uses these exact versions. FontAwesome 5 works fine with this: 

```
    "@fortawesome/fontawesome-pro": "^5.15.3",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/pro-light-svg-icons": "^5.15.3",
    "@fortawesome/pro-solid-svg-icons": "^5.15.3",
    "@fortawesome/react-fontawesome": "^0.1.14",
```

tsconfig:
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "isolatedModules": true,
    "noImplicitReturns": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "strictBindCallApply": true,
    "jsx": "preserve"
  },
}
```

It looks like something changed about the module export format of `@fortawesome/fontawesome-svg-core`

**Comment by robmadole** [comment]
Yeah, I think so. It's probably [the `package.json`'s `exports` attribute](https://nodejs.org/api/packages.html#packages_exports).

Can you help me reproduce your environment? I need to get a hold of setup where it's using the new `exports` attribute but it needs the CommonJS formatted files. I suspected that this was a use case I just haven't been able to reproduce it.

**Comment by smebberson** [comment]
@robmadole, you can use https://github.com/smebberson/next-tailwind-fontawesome/tree/with-fontawesome as an example of a scenario where it needs the CommonJS formatted files. This project uses Next.js and it expects CommonJS formatted files.

If you run that branch locally with `yarn && yarn dev`, you should see something like the following error:
```
/workspaces/next-tailwind-fontawesome/node_modules/@fortawesome/fontawesome-svg-core/index.es.js:3033
export { noAuto$1 as noAuto, config$1 as config, library$1 as library, dom$1 as dom, parse$1 as parse, findIconDefinition$1 as findIconDefinition, toHtml$1 as toHtml, icon, layer, text, counter, api };
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.@fortawesome/fontawesome-svg-core (/workspaces/next-tailwind-fontawesome/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/workspaces/next-tailwind-fontawesome/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.js:5:91)
```

There is no TypeScript involved in this project, however, it seems to recreate the same issue.

**Comment by smebberson** [comment]
@robmadole, does that repository do the trick for you?

**Comment by eikaramba** [comment]
sveltekit seems to be broken now too when trying to build
```
import { faCartShopping } from "@fortawesome/free-solid-svg-icons";
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'faCartShopping' not found. The requested module '@fortawesome/free-solid-svg-icons' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

**Comment by robmadole** [comment]
@smebberson yes that's perfect thank you! I'll start trying to figure out what's going on.

**Comment by robmadole** [comment]
@smebberson I just opened a PR against your repro. https://github.com/smebberson/next-tailwind-fontawesome/pull/3

It just upgrades to the full `6.0.0` release. Can you give this a try?

**Comment by smebberson** [comment]
@robmadole, that worked perfectly. You can see the final result at https://github.com/smebberson/next-tailwind-fontawesome.
