### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18246]
Please add a Circle QR code icon.

**Comment by tagliala** [comment]
Hi!

Can I have a clarification? What is Circle QR? Any chance to fill in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example?

**Comment by tagliala** [comment]
Superseded by #18248
