### ISSUE TITLE
Send Icon

### ISSUE THREAD

**Issue by shivang1809** [FortAwesome/Font-Awesome#18247]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I have included at least one example image if it could be helpful (optional)
>  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

"Send" is an abstract concept, it is hard to represent.

Anyway, we have some "send" related icons: https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=send&s=solid&m=free

Closing here, but feel free to open a new request with a better title and an example
