### ISSUE TITLE
Icon request: qrcode-circle

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18248]
**What can it be used for?**
This is to be used for mobile apps.

**Example image (optional)**
![2033108](https://user-images.githubusercontent.com/6236241/132121012-63597e2e-faf3-4a6e-8e16-72d3beb6c46c.png)

**Icon request checklist**
- [X ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X ] I have included at least one example image if it could be helpful (optional)
- [X ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that you can achieve those icons with the power transforms, masking, and layering features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/560/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by Xuanvy195** [comment]
> **Những gì nó có thể được sử dụng cho? **
> Điều này sẽ được sử dụng cho các ứng dụng dành cho thiết bị di động.
> 
> **Hình ảnh ví dụ (tùy chọn)**
> ![2033108](https://user-images.githubusercontent.com/6236241/132121012-63597e2e-faf3-4a6e-8e16-72d3beb6c46c.png)
> 
> **Danh sách kiểm tra yêu cầu biểu tượng**
> 
> * [X] Đây là một biểu tượng đơn lẻ hoặc một cặp phù hợp (Ví dụ: `lock`/ `unlock`)
> * [X] Tiêu đề bắt đầu bằng "Yêu cầu biểu tượng:" và theo sau là tên biểu tượng được yêu cầu (Ví dụ `Icon request: magical-unicorn`:)
> * [X] Tôi đã [tìm kiếm các vấn đề hiện có](https://github.com/FortAwesome/Font-Awesome/issues) và theo hiểu biết của tôi thì đây không phải là bản sao
> * [X] Tôi đã bao gồm ít nhất một hình ảnh ví dụ nếu nó có thể hữu ích (tùy chọn)
> * [X] Yêu cầu dành cho một đối tượng cụ thể (khó tạo biểu tượng đại diện cho hạnh phúc, tạo mặt cười thì dễ hơn. ☺)

**Comment by jrahma** [comment]
But how to do the masking in Xamarin Forms?

**Comment by tagliala** [comment]
> But how to do the masking in Xamarin Forms?

Hi, that is not possible, apologies.

I will edit my template answer to better clarify that SVG + JS framework is limited to web applications

**Comment by jrahma** [comment]
Is it something you are considering in future?

**Comment by tagliala** [comment]
> Is it something you are considering in future?

You mean this request or a feature like masking and layering on Xamarin?

**Comment by jrahma** [comment]
> > Is it something you are considering in future?
> 
> You mean this request or a feature like masking and layering on Xamarin?

Yes, I mean provide the ability of transforming and masking in Xamarin.

**Comment by tagliala** [comment]
> Yes, I mean provide the ability of transforming and masking in Xamarin.

I'm not familiar with Xamarin, does it use `ttf` / `otf`?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
