### ISSUE TITLE
> **Những gì nó có thể được sử dụng cho? **

### ISSUE THREAD

**Issue by Xuanvy195** [FortAwesome/Font-Awesome#18250]
> **Những gì nó có thể được sử dụng cho? **
> Điều này sẽ được sử dụng cho các ứng dụng dành cho thiết bị di động.
> 
> **Hình ảnh ví dụ (tùy chọn)**
> ![2033108](https://user-images.githubusercontent.com/6236241/132121012-63597e2e-faf3-4a6e-8e16-72d3beb6c46c.png)
> 
> **Danh sách kiểm tra yêu cầu biểu tượng**
> 
> * [X] Đây là một biểu tượng đơn lẻ hoặc một cặp phù hợp (Ví dụ: `lock`/ `unlock`)
> * [X] Tiêu đề bắt đầu bằng "Yêu cầu biểu tượng:" và theo sau là tên biểu tượng được yêu cầu (Ví dụ `Icon request: magical-unicorn`:)
> * [X] Tôi đã [tìm kiếm các vấn đề hiện có](https://github.com/FortAwesome/Font-Awesome/issues) và theo hiểu biết của tôi thì đây không phải là bản sao
> * [X] Tôi đã bao gồm ít nhất một hình ảnh ví dụ nếu nó có thể hữu ích (tùy chọn)
> * [X] Yêu cầu dành cho một đối tượng cụ thể (khó tạo biểu tượng đại diện cho hạnh phúc, tạo mặt cười thì dễ hơn. ☺)

_Originally posted by @Xuanvy195 in https://github.com/FortAwesome/Font-Awesome/issues/18248#issuecomment-913198285_

**Comment by Xuanvy195** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/18248#issuecomment-913198285

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

From Google translate, looks like a translation of #18248.

Closing here
