### ISSUE TITLE
Icon request: book-comments (graphic-novel)

### ISSUE THREAD

**Issue by JacobDB** [FortAwesome/Font-Awesome#18259]
**What can it be used for?**
Similar in use to the newspaper, useful for representing information related to graphic novels or comic books. This could be a wholely unique icon, or could be a variant of `book` (i.e. `book-comic`).

**Example image (optional)**
![image](https://user-images.githubusercontent.com/1123997/132907718-eedf007f-76ef-4536-bc99-f27b6b79e80f.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any simpler example that could play well at 16px?

Maybe something based on our current book icons: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=book&s=solid&m=free

**Comment by tagliala** [comment]
Maybe `book-comments`?

Demo: https://jsfiddle.net/tagliala/hufysvg0/32/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by JacobDB** [comment]
Ah, I completely forgot you could layer icons like that. That's definitely a route I can play with.

**Comment by tagliala** [comment]
@JacobDB may I assume that this is a request for an icon like `book-comments` ?

**Comment by JacobDB** [comment]
Yeah, that'll work alright.

**Comment by tagliala** [comment]
I've reopened. this icon could be achieved for Pro users like explained, but the request is valid

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
