### ISSUE TITLE
I Can't Use "handshake-o" Icon

### ISSUE THREAD

**Issue by petrustjoi** [FortAwesome/Font-Awesome#18267]
I can't use this icon:
[fa-handshake-o](https://fontawesome.com/v4.7/icon/handshake-o)
on my html code:
`<div class="media-left"><i class="icon-linear fa fa-handshake-o"></i></div>`.

I hope this icon appears like other icons.
![image](https://user-images.githubusercontent.com/66345222/133055544-92bb9bfc-10a3-4914-8fc4-5b75ddb28a81.png)

[This issue](https://github.com/FortAwesome/Font-Awesome/issues/13519) does not match my problem, because I use different html code.

Version: 4.3.0 by @davegandy 
Browser and version: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

- [ ] SVG with JS
- [✔] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [✔] I have filled out as much of the above information as I can
- [✔] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [✔] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Version: 4.3.0

FA 4 is in EOL, please upgrade to FA 5

> https://fontawesome.com/v4.7/icon/handshake-o

FA5 documentation is much clearer, but FA4 also provides version information. To use `handshake-o`, you should have at least version 4.7.0

![image](https://user-images.githubusercontent.com/556268/133058414-b6148815-5be4-459c-a0bb-9d391e2078f9.png)
