### ISSUE TITLE
v6 duotone `hourglass` and `hourglass-end` both broke

### ISSUE THREAD

**Issue by mikestopcontinues** [FortAwesome/Font-Awesome#18261]
**Describe the bug**
Both browsing the catalogue online, as well as when trying to use the icons in a project with the icon font, they don't work.

**To Reproduce**
https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=hour&s=duotone

**Version and implementation**
Version: v6.0.0-beta1
Browser and version: Chrome (most recent)

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Maybe the same issue as #17961

**Comment by mikestopcontinues** [comment]
@tagliala Ahh yeah, I think so. I'm sure you've seen there's at least a dozen icons affected. I'll close this since you've got a handle on it. Thanks!
