### ISSUE TITLE
Can we use api.fontawesome.com || api-canary.fontawesome.com in production?

### ISSUE THREAD

**Issue by l2aelba** [FortAwesome/Font-Awesome#18275]
_Just quick question…_

Can we use `api.fontawesome.com` or `api-canary.fontawesome.com `

for listing icons or search icons in **production**?

Thanks 🚀

**Comment by robmadole** [comment]
We have documentation for using our GraphQL API here:

https://fontawesome.com/v5.15/how-to-use/graphql-api/intro/getting-started

**Note** that you should use `api-canary.fontawesome.com`. This is not advertised to the public for a reason :)

**Comment by mlwilkerson** [comment]
You could also use our [Icon Chooser web component](https://github.com/FortAwesome/fa-icon-chooser), which is a whole front-end UI that leverages `api.fontawesome.com`.
