### ISSUE TITLE
Icon Request: guilded-icon

### ISSUE THREAD

**Issue by mikeomni** [FortAwesome/Font-Awesome#18278]
**What can it be used for?**
Guilded is a full featured Discord alternative, so it's a single, social icon that would be used for linking to a guilded.gg/serverofsomekind, a la facebook F, or twitter bird.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/6571414/133727197-f5c1712c-dbb2-43bf-a9e6-9a9962342f0d.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hey there! This has been added as part of version 6: https://fontawesome.com/v6.0/icons/guilded?s=brands

**Comment by tagliala** [comment]
Oh, this is part of 5.15.0 as well

https://fontawesome.com/v5.15/icons/guilded?style=brands

Closing here
