### ISSUE TITLE
Chrome mobile problem (chrome 93 / android 7)

### ISSUE THREAD

**Issue by vitopapa** [FortAwesome/Font-Awesome#18289]
I'm using CDN (https://use.fontawesome.com/releases/v5.5.0/css/all.css) and in the recent period I realized, icons not showing in chrome, but only on mobile. On IOS it works. Any idea?
Thanks in advance

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide a reproducible test case, as well as information on the browser and os affected

**Comment by vitopapa** [comment]
Hi!
I tested on Android 7, and the version of Chrome is: 93.0.4577.82
After Chrome was downgraded, works fine. Same OS with other browser also works fine. I think the latest Chrome update was the reason.

**Comment by tagliala** [comment]
Any chance to provide a reproducible test case?

Are you able to reproduce on https://tagliala.github.io/fa16077-512 ?

**Comment by vitopapa** [comment]
Here is my code, this produces the same error.
```
<!DOCTYPE html>
<html lang="hu">
  <head>
    <title>fa</title>
    <meta name="description" content="fa" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous" />   
  </head>
  <body>
    <i class="fa fa-bars"></i>
  </body>
</html>
```

**Comment by vitopapa** [comment]
With v5.12.1 works. Question is we have to change it on every earlier project?

**Comment by tagliala** [comment]
I've created a demo with your code at https://tagliala.github.io/fa18289.html

I will try with the same version of chrome on Android and I'm leaving this open for feedback

**Comment by tagliala** [comment]
@vitopapa could you please test with the newly released Chrome 94?

**Comment by vitopapa** [comment]
@tagliala I'm not able to upgrade Chrome. In the play store 93 is the newest. 
But very interesting on your github link it works but on my own hosting icons are not visible. Any idea?

**Comment by tagliala** [comment]
> But very interesting on your github link it works but on my own hosting icons are not visible. Any idea?

You mean the very same example?

**Comment by vitopapa** [comment]
> 
> 
> > But very interesting on your github link it works but on my own hosting icons are not visible. Any idea?
> 
> You mean the very same example?

Yes. I have no idea. I tested on 2 separated servers.
This is the same code:
https://design.kleinart.hu/fa.html
Can you test it maybe with chrome 93?
Thanks in advance.

**Comment by tagliala** [comment]
> Can you test it maybe with chrome 93?

I didn't experience that issue on my demo page with the very same chrome version on macOS

I don't know if I can test the very same version with Android

**Comment by tagliala** [comment]
My windows 10 machine with  93.0.4577.82 works on both pages

**Comment by vitopapa** [comment]
I can reproduce only on android 7 with chrome 93. I will waiting chrome 94. On ios 94 is available and it works. If doesn't solve i have to change fa versions. Thanks anyway!

**Comment by tagliala** [comment]
Out of curiosity, does newer version of android work?

**Comment by vitopapa** [comment]
I can test only on this one. But I think chrome version is the reason. Same os other browser works.

**Comment by tagliala** [comment]
Works on Nexus 4 / Android 10 (LineageOS 17.1) / Chrome 93.0.4577.82

I'm going to close here
