### ISSUE TITLE
Icon Request: bootstrap

### ISSUE THREAD

**Issue by ideirj** [FortAwesome/Font-Awesome#1828]
sorry, if it's dupe, but too more search found...

example:
http://blog.getbootstrap.com/public/ico/apple-touch-icon-144-precomposed.png
http://blog.tmimgcdn.com/wp-content/uploads/2012/12/Bootstrap-icon.jpg

**Comment by xxxdepy** [comment]
+1 for Bootstrap Icon

**Comment by berlincount** [comment]
+1

**Comment by rlilja** [comment]
+1

**Comment by shefik** [comment]
+1

**Comment by cuttingedgehobbies** [comment]
:+1:

**Comment by erfurtjohn** [comment]
+1

**Comment by FabianKoestring** [comment]
:+1:

**Comment by berlincount** [comment]
We'll probably have to wait until it's over 9000.

**Comment by chnwentao** [comment]
+1

**Comment by TJohnson93** [comment]
+1

**Comment by loki1000101** [comment]
+1

**Comment by TheCrambler** [comment]
+1

**Comment by webappdesigner** [comment]
+100 

Considering most of the people using font-awesome are web designers/developers, and considering the popularity of Bootstrap, i'm surprised this has not already been implemented already, yet you have an icon for 'pied-piper' ...... 

Come on people.....

**Comment by mizerydearia** [comment]
+1

**Comment by TMMC** [comment]
+1

**Comment by ThatGuySamUK** [comment]
+1

**Comment by nikneb** [comment]
+1

**Comment by Bazar6** [comment]
+1

**Comment by dynamicsites** [comment]
+1

**Comment by alsoknownasdrew** [comment]
+1

**Comment by htmgarcia** [comment]
+1

**Comment by wolfy1339** [comment]
Here's the SVG version, as needed in icon requests: 
<img src="https://upload.wikimedia.org/wikipedia/commons/e/ea/Boostrap_logo.svg" width="256">

**Comment by joelmora** [comment]
+1

**Comment by atulbhats** [comment]
+1

**Comment by sjclayton** [comment]
+1

**Comment by ojdon** [comment]
+1

**Comment by flokX** [comment]
👍 +1
Although the issue is quite old, Bootstrap is full of life with the soon stable 4.0.

**Comment by SawnFx** [comment]
+1

**Comment by wasthishelpful** [comment]
+1

**Comment by marcreichel** [comment]
+1

**Comment by xxxdepy** [comment]
I wonder how FA hasn't yet included the Bootstrap icon (even in the FA5!). The icon set has icons of companies that nobody would ever need, still

**Comment by Isaac-Aguilar** [comment]
+1

**Comment by Patrickoli** [comment]
+1

**Comment by Berkmann18** [comment]
+1

**Comment by JoshWeb** [comment]
+1

**Comment by zakbell** [comment]
+1

**Comment by htmgarcia** [comment]
We're posting _+1_ since 2013 😄

**Comment by TheTechKid** [comment]
+1

**Comment by ThandekaBhengu** [comment]
+1

**Comment by justasofficial** [comment]
+1

**Comment by xxxdepy** [comment]
It's so strange that FA 5 included so many brand icons that nobody needed other than the brands itself, still they have not added Bootstrap.

**Comment by qeekus** [comment]
They don't consciously add an icon 😒

**Comment by enricomarogna** [comment]
+1

**Comment by Smartappli** [comment]
+1

**Comment by boutzamat** [comment]
+1

**Comment by SamMoher** [comment]
+1

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/bootstrap

Thanks for the patience and for continuing to vote this up! :smile:

**Comment by SjorsHartwijk** [comment]
Bootstrap announced a new and updated logo: 
https://v5.getbootstrap.com/

**Comment by tagliala** [comment]
Hi @SjorsHartwijk , thanks for the heads-up, please open a new request 👍
