### ISSUE TITLE
account register

### ISSUE THREAD

**Issue by iamowaisazam** [FortAwesome/Font-Awesome#18292]
I m Trying To Create Account i have submited my email i did not receive any registration email..

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Apologies for the late reply. Did you receive the registration email?

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by tagliala** [comment]
Hi!

I'm closing here for inactivity, but feel free to comment if this issue has not been resolved
