### ISSUE TITLE
fa-ad not working

### ISSUE THREAD

**Issue by thedavidhoffman** [FortAwesome/Font-Awesome#18297]
Using font awesome version 5.15.4, and I can't get the fa-ad icon to render/display.

Any other icon I use, renders correctly.

Coping the code from the font awesome icon documentation...

https://fontawesome.com/v5.15/icons/ad?style=solid

I have verified that it is in the all.css file...

.fa-ad:before {
  content: "\f641"; }

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This should be ad-block related. Ref: #18118

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
