### ISSUE TITLE
Icons not showing in a Bootstrap Modal

### ISSUE THREAD

**Issue by nico-apps** [FortAwesome/Font-Awesome#18304]
**Describe the bug**
I'm trying to use the spinning sync icon on my website. When using it in a `<div>` element, it works fine, but not when it's put in a Bootstrap Modal (using Bootstrap 5.0.1).
What's even weirder, is that the spinning effect is applied. If I use `<i class='fa-spin'>a</i>`, then I see the letter a that rotates. The icons simply do not appear, no matter if I'm using `fa-spin` or not.
Tried using other icons like `fas-fa-bars`, but no success.

**To Reproduce**
The issue can be seen on my german webpage for an admin tool: http://montemanager.de/admin.php

Add a Bootstrap modal and then put a Font Awesome icon somewhere in it's body.

**Expected behavior**
The icon appears, followed by the text.

**Current behavior**
The icon is scaled to 0x0, and doesn't appear at all.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35093969/134911788-28a0b0c1-6e95-4d4e-b0e0-cc39c0ffdc0e.png)

**Version and implementation**
Version: Font Awesome 5.15.4
**Edit:** Using Fontawesome Free
Browser and version: Firefox 92.0.1, Chrome 93.0.4577.82, Microsoft Edge 94.0.992.31

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've checked your layout and there is an error when referencing the icon

`fas-fa-sync fa-spin` is not correct, the proper FA5 classes are: `fas fa-sync fa-spin`

![image](https://user-images.githubusercontent.com/556268/134917577-1110dd66-155f-47c0-9ce3-e21c3d77c67b.png)

If you have troubles in using Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by nico-apps** [comment]
@tagliala Im such an idiot. Thanks, that worked!
