### ISSUE TITLE
Icon modification request: soft-serve (creemee)

### ISSUE THREAD

**Issue by julienlegault** [FortAwesome/Font-Awesome#18305]
The new soft-serve ice cream cone icon is great, but I would love to see the name changed. 

In my experience, and based on some online research[[1]](https://delishably.com/desserts/Creemee-VS-Soft-Serve), the only place in the world that I can find that calls such a frozen treat a 'creemee' is Vermont, USA. As someone who lives in Vermont, I despise the word and can't stand that people around me find no issue with a soft dairy-based desert being named after a sexual advance. 

On a slightly more serious note, I do think that more people around the globe will know the cone by it's name 'soft-serve'. Soft-serve is only 2 characters longer than creemee, so I don't see a glaring reason why creemee might have been chosen over soft-serve. 

Feel free to decline this rename request, I understand that soft-serve is a valid alias, I just think creemee may confuse some people as they look for that specific icon.

**Comment by tagliala** [comment]
Hi!

Thanks for this feedback

As a non English native speaker, I should mention @sensibleworld and @robmadole here

**Comment by sensibleworld** [comment]
Hey @julienlegault. I've already got this name change queued up for our next release. `soft-serve` already works as an alias, so you can go ahead and use that in the meantime.

As a Vermonter myself, I personally find no issue with the name, but I recognize that it could be confusing. (And honestly, it was an accidental inclusion! Sometimes when naming a bunch of new icons, baked-in biases can take root.)

**Comment by julienlegault** [comment]
@sensibleworld I knew one of y'all had to be a Vermonter! 

In the future, have you considered using the official Unicode names for some of these symbols? I know they spend a massive amount of time deciding exactly what phrase describes the icon best. Those names may be a bit too long for fa-options though.

**Comment by sensibleworld** [comment]
@julienlegault Champlain Valley FTW :)

And yes, we definitely consult unicode standards when naming, but in a lot of cases, our icon names need to be a bit more generic. Especially in cases where emoji rely heavily on color for differentiation. That said, version 6 supports aliases, so we try to include those when possible. (Which is why the `creemee` icon also works with the name `soft-serve`. And the reverse will be true with the next update.)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/soft-serve?s=solid
