### ISSUE TITLE
soccer-ball-o  There is a problem with the icon and cannot be called remotely

### ISSUE THREAD

**Issue by cyberxsboy** [FortAwesome/Font-Awesome#18311]
There is a problem with the icon and it cannot be called remotely. The problem is what the title reflects. Calling other icons does not have this problem.

**Comment by cyberxsboy** [comment]
<i class="fa fa-soccer-ball-o" aria-hidden="true">

**Comment by cyberxsboy** [comment]
`<i class="fa fa-soccer-ball-o" aria-hidden="true"></i>`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> `<i class="fa fa-soccer-ball-o" aria-hidden="true"></i>`

The above syntax is the old deprecated syntax for Font Awesome 4. Font Awesome 4 is in EOL and is not supported anymore

As per [documentation](https://fontawesome.com/v5.15/icons/futbol?style=solid), the correct usage in FA5 is: `<i class="far fa-futbol"></i>`.

Demo: https://jsfiddle.net/tagliala/vbhdn9te/54/

If you need FA4 backward compatibility, please use v4 shim. Documentation is available at https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/upgrading-from-version-4#manually

Demo with shim: https://jsfiddle.net/tagliala/vbhdn9te/49/

If you still think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Hope it help

Closing here
