### ISSUE TITLE
Outdated version needed

### ISSUE THREAD

**Issue by guardian-dev-005** [FortAwesome/Font-Awesome#18316]
I am making a web solution that uses the 5.3.1 version of the Font Awesome icons. 
I want to include this package internally on the project.
I've tried to include the latest version on the project but it won't work
But because it is an outdated version of the service, i can't find it anywhere to download. 

I need help just to find where to download this specific library.

**Comment by sensibleworld** [comment]
Just visit https://fontawesome.com/download and click on the "Looking for Previous or Other Versions" link.

<img width="1084" alt="Screen Shot 2021-09-29 at 1 48 10 PM" src="https://user-images.githubusercontent.com/529604/135322066-1f37c55e-ced6-447a-ba0b-26a2943f104d.png">

**Comment by guardian-dev-005** [comment]
Thank you so much!!!
I was in a hurry. Couldn't see this there.
