### ISSUE TITLE
Icon request: register

### ISSUE THREAD

**Issue by TimothyFran** [FortAwesome/Font-Awesome#18322]
**What can it be used for?**
The icon could be used on a website for the button used to register an user to the service.

**Example image (optional)**
Could be a form (digital or paper) filled by a pencil/pen

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a few icons that may fit this use case:
- https://fontawesome.com/v5.15/icons/file-signature?style=solid
- https://fontawesome.com/v5.15/icons/file-edit?style=solid (Pro)
- https://fontawesome.com/v5.15/icons/user-edit?style=solid
- https://fontawesome.com/v5.15/icons/user-plus?style=solid

In a **web application**, it is also possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/587/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

Closing here, but if none of the above icons fit your use case, feel free to comment and edit the opening post by providing a better title (register is abstract) and clarify why the existing icons do not fit the use case
