### ISSUE TITLE
SCSS for Font Awesome 6 not compatible with scssphp

### ISSUE THREAD

**Issue by TimWolla** [FortAwesome/Font-Awesome#18320]
Please see this issue in scssphp for details: https://github.com/scssphp/scssphp/issues/504

While this is an bug in scssphp, it appears that there is a simple workaround for Font Awesome, by removing the parentheses around the `divide()` function. Thus I would like to request that this is done.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Even if scssphp is not a supported compiler, I think that the parentheses could be removed, if the linter is not requiring them for other purposes and they are redundant for that specific use case

**Comment by robmadole** [comment]
We'll take a look at this and see if we can remove the extra `(` `)`.

**Comment by robmadole** [comment]
Ok I think we've removed the extra parentheses in 6.0.0-beta3. @TimWolla would you be able to give it a try?

**Comment by TimWolla** [comment]
@robmadole Thank you. I can confirm that the issue with scssphp is fixed.

Beta 2:
```
.fa-xl {
  font-size: 1.6 * 1em;
  line-height: 0.0416666682 * 1em;
  vertical-align: 0.25 - 0.375 * 1em;
}
```

Beta 3:
```
.fa-xl {
  font-size: 1.6em;
  line-height: 0.0416666682em;
  vertical-align: -0.125em;
}
```

Leaving this issue open so you can appropriately label it before closing.
