### ISSUE TITLE
Tiktok Icon not working

### ISSUE THREAD

**Issue by MollyKoury** [FortAwesome/Font-Awesome#18338]
I don't think it's a problem that can be replicated, but I was trying to use the TikTok icon and it would not load in

![werty](https://user-images.githubusercontent.com/32551244/136140845-c7a118a5-42d2-4122-8fe2-83e763c8333a.png)

The icon should be appearing in the bottom right square. As is obvious, I have successfully gotten the other icons to work no problem, and as far as I can tell, I'm not doing anything different for the TikTok icon. I'm just copying and pasting it into the code, as such

![erty](https://user-images.githubusercontent.com/32551244/136140991-1267b56c-e284-4eb4-9218-f185dc6273b7.png)

Might be worth noting that the code I'm working on isn't mine, I'm just editing and adding stuff to it. So I understand very basic HTML, but can't start from scratch on my own. I tested the icon in other codes and had the same issue, so it's not the code itself that's the problem. It would be weird if I'm the only one having this issue, but I haven't seen any other posts about it

The icon I'm trying to use https://fontawesome.com/v5.15/icons/tiktok?style=brands

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[tiktok](https://fontawesome.com/v5.15/icons/tiktok?style=brands) has been introduced in Font Awesome 5.14.0, so please double check that you are using Font Awesome 5.14.0 or newer versions

Please note that third-party plugins/themes/libraries may load an older version of Font Awesome that may take precedence on yours: check that it is not your case. Our [Troubleshooting Guide](https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting) and [Troubleshooting Wiki](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) could help.

If you still think that there is an issue with Font Awesome, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md) and provide a reproducible test case

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
