### ISSUE TITLE
Icon request: camera-flash

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18333]
**What can it be used for?**
Please add camera flash icon

**Example image (optional)**

![7733308](https://user-images.githubusercontent.com/6236241/135936962-d9eb08cc-4d2b-4bdc-9da5-fac49f302703.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
Hey there! This icon exists in version 6: https://fontawesome.com/v6.0/icons/bolt
