### ISSUE TITLE
Icon request: change-camera

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18332]
**What can it be used for?**
Please add the Change / Camera icon

**Example image (optional)**

![png-transparent-computer-icons-camera-camera-logo-backup-camera-brand-thumbnail](https://user-images.githubusercontent.com/6236241/135936761-774cf571-4ca9-4ad1-a468-50973d351b09.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/camera-rotate?s=solid
