### ISSUE TITLE
Icon request: flash-off

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#18334]
**What can it be used for?**
Please add camera flash off icon

**Example image (optional)**

![flashoff](https://user-images.githubusercontent.com/6236241/135937189-eba80c13-688b-4302-9628-8f6ae5562e81.png)

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/bolt-slash
