### ISSUE TITLE
icon request: broom-alt

### ISSUE THREAD

**Issue by oriadam** [FortAwesome/Font-Awesome#18347]
**What can it be used for?**
Clearing form data

**Example image (optional)**
![image](https://user-images.githubusercontent.com/2786617/136686963-40448fb0-e1b5-47c5-b7c3-8b42b4b65517.png)

**Icon request checklist**
- [V] This is a **single** icon or matched pair (Ex: `lock` / `unlock`)
- [V] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [V] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [V] I have included at least one example image if it could be helpful (optional)
- [V] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

There is an existing [broom icon](https://fontawesome.com/v5.15/icons/broom) but to our users it looks more like a paintbrush rather than a cleaning device:
![image](https://user-images.githubusercontent.com/2786617/136687086-d0491bc4-7f51-4c45-a4d2-7aab33f8c930.png)

Semi-related to #15776

**Comment by sensibleworld** [comment]
Added in 6.3.0: https://fontawesome.com/icons/broom-wide?f=classic&s=duotone&sc=%231E3050
