### ISSUE TITLE
Icon update: vk logo

### ISSUE THREAD

**Issue by map788** [FortAwesome/Font-Awesome#18356]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

Vk.com new logo 
https://www.dropbox.com/sh/0vbjgnwalaypfhk/AABoW1TqTsKkryiaV531u5c6a?dl=0
**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/vk?s=brands
