### ISSUE TITLE
Check please 

### ISSUE THREAD

**Issue by 35678476** [FortAwesome/Font-Awesome#18366]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?
![Screenshot_20211015-222756_Chrome](https://user-images.githubusercontent.com/92312173/137569879-37ed5c44-85c7-4854-bec1-31ec3ffdb0bd.jpg)

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

**Screenshots**

**Version and implementation**
Version: 
Browser and version: 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this issue

I cannot replicate, it may depend on region or temporary failure.

Could you please:

1. Check again
2. Provide information about your connection (country and provider)

**Comment by tagliala** [comment]
No feedback, closing here
