### ISSUE TITLE
Icon Request: valign-top

### ISSUE THREAD

**Issue by rizen** [FortAwesome/Font-Awesome#18367]
**What can it be used for?**
This would be a matched set of icons: valign-top, valign-middle, and valign-bottom

Any app that has positional elements for alignment. You already have horizontal icons for alignment, but icons for vertical alignment would also be great.

**Example image (optional)**
<img width="262" alt="Screen Shot 2021-10-16 at 10 45 19 AM" src="https://user-images.githubusercontent.com/170009/137593794-cfbfadff-7178-4ee3-9b08-529f5bf8e33c.png">

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be part of FA 6 Pro: https://fontawesome.com/v6.0/icons/objects-align-top

**Comment by rizen** [comment]
Woot!
