### ISSUE TITLE
Icon Update: fa-unity

### ISSUE THREAD

**Issue by somethingSTRANGE** [FortAwesome/Font-Awesome#18368]
**Describe the bug**
Unity has rebranded and has a new logo design.
[Unity Brand Guide](https://brandguide.brandfolder.com/unity/logo)

As shown in the following image, the "Logo variations" section includes single-color logo variations.
![image](https://user-images.githubusercontent.com/6905832/137639568-131b01f6-4273-4a04-b152-7918e96df430.png)

**Test Case**
Use the current **fa-unity** logo and the old logo is shown.

**Screenshots**
### Old Logo
![image](https://user-images.githubusercontent.com/6905832/137639757-a5ea9ee7-047c-421d-aeda-de151048b5cb.png)

### New Logo
![image](https://user-images.githubusercontent.com/6905832/137639768-d0f838c2-c86d-4e04-addc-7efb14e4b95a.png)

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tjkohli** [comment]
Looks like we'll have to use the single-color logo here.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/unity?s=brands
