### ISSUE TITLE
Проблема отображения!

### ISSUE THREAD

**Issue by Karen270698** [FortAwesome/Font-Awesome#18376]
![Снимок экрана (32)](https://user-images.githubusercontent.com/85614091/138094404-d8e86cf8-330e-493e-8e8c-2c9f4a958517.png)
Что за ошибка?

**Comment by idegree** [comment]
У всех, кроме тебя, все работает.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If this is still an issue, could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?
