### ISSUE TITLE
Font Awesome v5 Sass Div Deprecation 

### ISSUE THREAD

**Issue by vinnycodes** [FortAwesome/Font-Awesome#18371]
Currently one of our sites uses font awesome v5.8 and getting the following errors: 

`DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($fa-li-width * 5, 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

  ╷
6 │   margin-left: $fa-li-width * 5/4;
  │                ^^^^^^^^^^^^^^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-pro/scss/_list.scss 6:16        @import
    node_modules/@fortawesome/fontawesome-pro/scss/fontawesome.scss 10:9  @import`

After doing some research I stumbled across this comment stating that this issue would be resolved in v5 and v6.

https://github.com/FortAwesome/Font-Awesome/pull/17940#issuecomment-901216145

Unfortunately, after updating to newer versions of Font Awesome v5, we are still having the above errors come up. Has this issue been resolved in v5 or are we still waiting for it to be updated?

**Comment by pableu** [comment]
@robmadole any idea when a new version of 5 is going to be released with this fix?

**Comment by pasevin** [comment]
any updates on this issue?

**Comment by nicmare** [comment]
will there be an update of font awesome subsetter app too?

**Comment by yeya** [comment]
Just upgrade to 6

**Comment by bobvandevijver** [comment]
A sample PR was already submitted quite a while back (https://github.com/FortAwesome/Font-Awesome/pull/19117), it looks like support for 5.x has been dropped completely.

**Comment by tagliala** [comment]
> it looks like support for 5.x has been dropped completely.

FA6 has been a priority, but there are some fixes that should be backported to FA5 and as far as I know the support has not been dropped. Unfortunately we cannot merge here and the fix must be backward-compatible with other Sass implementation

@robmadole any ETA on when FA5 can receive these fixes?

**Comment by robmadole** [comment]
Plans have changed on fixing this issue with version 5. We won't be addressing this.
