### ISSUE TITLE
Icon request: Breast

### ISSUE THREAD

**Issue by pixelwiz** [FortAwesome/Font-Awesome#18395]
**What can it be used for?**
Can be used for Breast Health, also to indicate if someone has implants or not.  Mostly in medical field, like patient chart, etc.

**Example image (optional)**
![image](https://user-images.githubusercontent.com/485516/139131580-8ed0ebc9-91e0-4f2b-8191-48bd9fe8d6f1.png)
![image](https://user-images.githubusercontent.com/485516/139131829-6695fc7c-eb14-45af-9897-d293b28b4ba4.png)
![image](https://user-images.githubusercontent.com/485516/139131918-662b12c3-b679-4b1f-a03d-d3d3602dc6ef.png)
![image](https://user-images.githubusercontent.com/485516/139131948-60a5427a-e1e7-43ad-ac37-741ba7fc9435.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by lloydjatkinson** [comment]
![image](https://user-images.githubusercontent.com/5633938/140629385-2fd6e2c6-114c-43f7-928c-b2ff0e7e68f2.png)

**Comment by LilPidgey** [comment]
Who making one for penis health?
Me, as a male, feel very excluded from font awesome icons

**Comment by ianrandmckenzie** [comment]
Testicles are usually more vulnerable to health complications. A groin icon would probably be more useful for the medical field. I suppose then ovaries would need an icon as well. Perhaps there should be an anatomy pack in general?

**Comment by Sokoo92** [comment]
> Who making one for penis health?
> 
> Me, as a male, feel very excluded from font awesome icons

Agreed, we also need one of the anus, f.e. to show one needs a colonoscopy.

**Comment by TAGC** [comment]
> Testicles are usually more vulnerable to health complications. A groin icon would probably be more useful for the medical field. I suppose then ovaries would need an icon as well. Perhaps there should be an anatomy pack of icons in general?

As someone who takes anabolic steroids, I assume we'd be able to get an `fa-xs` version of the testicles icon?

**Comment by rasimavci** [comment]
anatomy pack would be great. we also need genetic and biology packs.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
