### ISSUE TITLE
Icon request: icon-computer-chip (or icon-chip)

### ISSUE THREAD

**Issue by amirmc** [FortAwesome/Font-Awesome#1840]
Some kind of computer chip icon.  Either a schematic view (from above and flat) or perspective (from the side/corner with depth).  Not sure which would work better.

Here are some examples:

from the top:
http://www.stereomojo.com/MINI%20AMP%20SHOOTOUT/images/NF12X201.jpg
http://rocketdock.com/images/screenshots/Computer-Chip.png

from an angle:
http://ps4daily.com/wp-content/uploads/2013/04/memory-chip-icon.jpg
http://www.circuitstoday.com/wp-content/uploads/2011/01/Microcontroller-Chip1.jpg

**Comment by kyakan** [comment]
+1

**Comment by coxley** [comment]
+1

**Comment by uraimo** [comment]
definitely +1

**Comment by TwistTheNeil** [comment]
+1

**Comment by connorjsmith** [comment]
+1

**Comment by nathraQ** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by shlomiassaf** [comment]
+1

**Comment by Gator92** [comment]
+1, a simple sine wave would be nice

**Comment by nounoursheureux** [comment]
+1

**Comment by joni2back** [comment]
+1 come on guys, request from 2013.......

**Comment by tagliala** [comment]
@joni2back please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by ArtemZ** [comment]
@tagliala so adding this simple icon would require buying a commercial software or subscribing to a commercial service, e.g https://fonticons.com (BTW it's created by @davegandy, creator of Font Awesome.)? Is it what Font Awesome is all about? Create a base icon set and then ask your users to pay just for ability to extend the icon set? Great business model, 10 out of 10.

**Comment by joni2back** [comment]
@tagliala come on... we suggest this icon to don't do that you mention

**Comment by tagliala** [comment]
@ArtemZ

Font Awesome is not a silver bullet: it might simply not work with your use case.

Fontello and icomoon are free. Forks are free. You could use a free software to edit the .otf file. There are many other options with an open build process.

@joni2back right, but you are asking Dave to do that on your behalf

**Comment by davegandy** [comment]
@joni2back @artemz 

Right now we're looking at the long tail. So far 38 people out of at least 3 million users have asked for a microchip. That's not a lot. When new versions happen, I tend to sort by how many users have requested a particular icon. This hasn't popped high enough on that list yet.

But oddly enough, I work the way most people do. When someone wants a favor, I tend to respond to folks asking nicely.

I sometimes see people here act like small children. I mean that quite literally. I have a one year old. He's starting to throw tantrums when the slightest thing goes wrong. He cannot imagine any perspective but his own. Because he has not yet learned empathy.

@ArtemZ YES. The Fonticons business model is to help folks be able to do whatever they want with icons. It can be used by everyone, no matter what they need. If it isn't right for you, then no sweat. There are lots of great tools. But it solves the problem with the long tail of requests. 

Additionally, your sarcasm is not appreciated. If I closed this issue right now because of you, it wouldn't be nice for the others who have very politely added a +1 and not wasted my time.

@ArtemZ, I would ask you to consider being a positive member of the community. Logical arguments work well. Help me see why this icon would be a good addition. But in the end, being polite really matters.

@tagliala Thanks for suffering through threads like this. You're awesome.

**Comment by ArtemZ** [comment]
@davegandy @tagliala I'm really sorry for my harsh words, I guess I just had a really bad day :(
Thank you for your great work, I'm sorry you have to read rants like this sometimes.
Hope this request won't get closed thanks to me.

**Comment by vlrprbttst** [comment]
+1

**Comment by sorahn** [comment]
Kickstarting Dave's projects is a good way to get your icon requests heard too ;)

+1 for a microchip!

**Comment by EvanWieland** [comment]
+1

**Comment by davegandy** [comment]
@ArtemZ Thanks for saying so. It is very much appreciated.

**Comment by CodingUniverse** [comment]
not cool

**Comment by shlomiassaf** [comment]
@davegandy, you words are too polite.

For me, open source is not free for other to loot, it is free for other to LEARN.
Open source code is the revolution of learning.

There are a lot of MIT projects out there with a profitable business model behind them, there`s not shame in that and it should be said out loud.

Open source is giving the people the option to do it on their own, learning in the process.

**Comment by vlipman** [comment]
+1

**Comment by RamzyVirani** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by hightekjonathan** [comment]
+1 A microchip or any kind of hardware related icon would be amazing!

**Comment by mbroadst** [comment]
+1

**Comment by yadayada** [comment]
+1

**Comment by ScriptorNY** [comment]
+1

**Comment by dave-irvine** [comment]
+1

**Comment by pootzko** [comment]
+1 would be most (font)awesome if we had this one :)

**Comment by tomuench** [comment]
+1 i will be happy if this icon will be there!

**Comment by neeasade** [comment]
+1

**Comment by EveryWell** [comment]
+1

**Comment by PlasmaPower** [comment]
+1

**Comment by npantos** [comment]
+1

**Comment by SaatvikShukla** [comment]
+1

**Comment by omashano** [comment]
+1

**Comment by MingcongBai** [comment]
+1

**Comment by vivi168** [comment]
+1

**Comment by uok** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by vansoest** [comment]
+1

**Comment by satheesh1991** [comment]
+1

**Comment by polmes** [comment]
+1

**Comment by aviemet** [comment]
Along similar lines, I think it would be great to have a set of circuitry symbols, such as the resistor, ground, capacitor, diode. Maybe even some of the common circuits like the bridge rectifier too. Don't know how many people would be into that, not sure if it should be a separate request or not.

**Comment by rockerest** [comment]
+1 for CPU (chip as OP indicates) as well as RAM and HDD/SSD

**Comment by asdrubalsantander** [comment]
+1 fa!

**Comment by jverne** [comment]
+1

**Comment by FrBillyD** [comment]
+1

**Comment by Mindstormer619** [comment]
:+1:

**Comment by capitantrueno** [comment]
+1

**Comment by tetsi** [comment]
+1

**Comment by justbuchanan** [comment]
+1

**Comment by floriansegginger** [comment]
+1

**Comment by metamet** [comment]
+1

**Comment by 06chaynes** [comment]
+1

**Comment by SNeilson** [comment]
+1

**Comment by tomdcc** [comment]
+1

**Comment by mmequignon** [comment]
+1

**Comment by taufique71** [comment]
+1

**Comment by wedens** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by tabakisp** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by armorking5** [comment]
+1

**Comment by VladVP** [comment]
+1

**Comment by Atomkraftzwerg** [comment]
+1

**Comment by ncnlinh** [comment]
+1

**Comment by davegandy** [comment]
Adding to 5.0.

**Comment by kousha-icracked** [comment]
+1

**Comment by groovymax** [comment]
+1

**Comment by ColinLaws** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by WhyKickAmooCow** [comment]
+1

**Comment by gimiki** [comment]
+1

**Comment by HaCk3Dq** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by BmanDesignsCanada** [comment]
+1

**Comment by apinner** [comment]
+1

**Comment by nashdeshpande** [comment]
+1

**Comment by rkhitin** [comment]
+1

**Comment by sialvi** [comment]
+1

**Comment by itotallyrock** [comment]
+1

**Comment by marcossilvajnr** [comment]
+1

**Comment by jpotier** [comment]
+1

**Comment by n-kolodziej** [comment]
+1

**Comment by co3moz** [comment]
+1

**Comment by kmbriedis** [comment]
+1

**Comment by ntrp** [comment]
It's been two years.... I think it is time to integrate it considering the fact that some users have already provided examples

**Comment by awreece** [comment]
+1

**Comment by kpillis** [comment]
+1

**Comment by olivierlambert** [comment]
+1

**Comment by redzioch** [comment]
+1

**Comment by mickep76** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-chip was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by dragomang87** [comment]
+1

**Comment by elston-jja** [comment]
+1

**Comment by graipher** [comment]
+1

**Comment by namaserajesh** [comment]
+1

**Comment by johnrivelt** [comment]
+1

**Comment by ashishpatel1992** [comment]
+1

**Comment by arturmamedov** [comment]
+1

**Comment by iboshkov** [comment]
+1

**Comment by hitech95** [comment]
3 Years later....
+1

**Comment by rubik** [comment]
So what's blocking this? Considering there are quite a few examples to choose from...

**Comment by tinohager** [comment]
+1

**Comment by JohnyR** [comment]
+1

**Comment by meyersbs** [comment]
+1

**Comment by Qhiliqq** [comment]
+1

**Comment by prashantghimire** [comment]
+1

**Comment by abkds** [comment]
+1

**Comment by huiyiqun** [comment]
+1

**Comment by bstolle** [comment]
+1

**Comment by mister-walter** [comment]
+1

**Comment by nunomazer** [comment]
+1

**Comment by santiagosalazar** [comment]
+1

**Comment by KennyWibowo** [comment]
+1

**Comment by nicolasbeauvais** [comment]
+1

**Comment by glowGrape** [comment]
+1

**Comment by martin0x** [comment]
+1

**Comment by leothelocust** [comment]
+1

**Comment by vladiuz1** [comment]
+1

chip, circut board, may be some electronic elements like resistor, etc...

**Comment by davegandy** [comment]
Added to 4.7.0 branch. Closing.

**Comment by AdGalesso** [comment]
+1

**Comment by tagliala** [comment]
@AdGalesso http://fontawesome.io/icon/microchip/

**Comment by janhieber** [comment]
+1 for cpu and ram

**Comment by tagliala** [comment]
🔒  http://fontawesome.io/icon/microchip/
