### ISSUE TITLE
Not allowed when Origin missing

### ISSUE THREAD

**Issue by Zaramay2** [FortAwesome/Font-Awesome#18401]
Hello! sorry for the inconvenience, I wanted to ask you if you can enable this script https://kit.fontawesome.com/a076d05399.js because it stops working? I implemented it for my project and it does not work, it is important for me, can you enable it? Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Apparently you are using a kit by w3schools

Please take a look at https://github.com/FortAwesome/Font-Awesome/issues/17622 and the relevant comment https://github.com/FortAwesome/Font-Awesome/issues/17622#issuecomment-777408205

Hope it helps

Closing here

**Comment by nati8oy** [comment]
Unfortunately I am still getting this issue using my own kit on Squarespace.
`<script src="https://kit.fontawesome.com/581fbdf8fd.js" crossorigin="anonymous"></script>`
 I am using the following kit but am not able to see anything at all when inputting the code for the icons. I have put this code into the code injector section of my site but am still getting the "Not allowed when Origin missing" when I try and load the JS file in a browser. Any thoughts on this?

**Comment by rgbinnovation** [comment]
Also experience the same at the moment.

**Comment by ulysses4ever** [comment]
I have the same problem after creating my own kit (https://kit.fontawesome.com/29065672f5.js at https://a.pelenitsyn.top/). Please, help.
