### ISSUE TITLE
Icon Request: fa-glass of wine

### ISSUE THREAD

**Issue by Tuscanytour** [FortAwesome/Font-Awesome#18418]
We would like to have a glass of wine icon
Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Wine glass icons are already available:
- https://fontawesome.com/v5.15/icons/wine-glass?style=solid
- https://fontawesome.com/v5.15/icons/wine-glass-alt?style=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
