### ISSUE TITLE
Some icons not working - showing exclamation point, question mark in a circle

### ISSUE THREAD

**Issue by joegiglio** [FortAwesome/Font-Awesome#18427]
Some icons work but others do not.  Here are a few that do not work.

```
<i class="fas fas-laptop-house"></i>
<i class="fas fa-user-clock"></i>
<i class="fas fa-globe-americas"></i>
```

Based on the research I have done, this can be caused by having the incorrect classes but I am copying this from the Fontawesome site.

I was not initially using kit code but I just installed it a while ago and have the same issue.

**Comment by tagliala** [comment]
> this can be caused by having the incorrect classes but I am copying this from the Fontawesome site.

May also depend by the version of Font Awesome used, or third-party libraries/plugins overriding your version

Could you please provide a reproducible test case?

**Comment by joegiglio** [comment]
It turns out I had a conflicting fontawesome .js file in my HEAD tag.  Not sure where that came from but I got rid of it and all is well.  Thanks!
