### ISSUE TITLE
free kit CDN 문제

### ISSUE THREAD

**Issue by bakseungho** [FortAwesome/Font-Awesome#18429]
kit에서 제공하는 cdn을 적용시키고,
무료인 fa-plus랑 fa-search를 HTML 안에 삽입했을 때 아이콘이 나오지 않습니다.

Apply the cdn provided by the kit,
When the free fa-plus and fa-search are inserted into HTML, the icon does not appear.

**Comment by bakseungho** [comment]
I found it. The cause was a font thickness problem.

**Comment by tagliala** [comment]
So I guess this is solved
