### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by lbbruno** [FortAwesome/Font-Awesome#18426]
Hello!
I need a help. I having problems to use the icons.

I have the link <script src="https://kit.fontawesome.com/978fac42f7.js" crossorigin="anonymous"></script> but when i use the icon this not appear.
For exemple:
If i use class="fab fa-whatsapp" it's ok.

But if I use class="fa-brands fa-whatsapp" it's not appearing.

May you help me?

Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The kit is using FA 5.15.4

> If i use class="fab fa-whatsapp" it's ok.

This is the correct syntax for FA5

> But if I use class="fa-brands fa-whatsapp" it's not appearing.

This is the new preferred syntax for FA6, so you can:

1. Update your kit to FA6 beta
2. Rename to `fab`
3. Create a custom css class `.fa-brands` on FA5 which mimics `.fab`

Docs:
- FA5: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/getting-started
- FA6: https://fontawesome.com/v6.0/docs/

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
