### ISSUE TITLE
Icon request: delete-selected

### ISSUE THREAD

**Issue by ermaneng** [FortAwesome/Font-Awesome#18438]
**What can it be used for?**
This would be a list of selected icons which are used like "Delete Selected", "Edit Selected", "Move Selected" ... etc

**Example image (optional)**
something like that
![2021-11-13 01_23_44-Free Download Manager](https://user-images.githubusercontent.com/6246331/141545523-6010f7ad-78c1-4e4d-aa91-c6e88a4b74bc.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/594/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by ermaneng** [comment]
layering is great but there are 2 issues.
1) think you will use it inside a <button>. it would be great just to add an icon as simple as "fa-delete-selected" with no additional doms. 
2) for layering you have to import all.js to your project which costs 3.7mb

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
