### ISSUE TITLE
Icon request: ear icon is not free why

### ISSUE THREAD

**Issue by MusaTahir007** [FortAwesome/Font-Awesome#18439]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The answer is available in our Leaderboard FAQs at https://fontawesome.com/community/leaderboard/new:

>  ### Why are some (highly requested) icons not available in Font Awesome Free?
> Font Awesome began as a free resource and it’s important to us that there will always be a free version of it that is more-than-usable by anyone who needs icons. But to keep Font Awesome going, we need paid options like Font Awesome Pro to help sustain the company and the people making the icons and services. Also, the introduction of Font Awesome Pro made it possible to more than double the size of Font Awesome Free!
> 
> With that all in mind, when planning out a category or release, we consider what icons can be added to Free to form a usable subset. If an icon doesn’t make that cut, it’s because it covers a deeper or more nuanced subject (e.g. toilet-paper-alt) or it isn’t essential to that focused subset of a category we included in Free (e.g. the range of tachometer-slowest to tachometer-fastest). If you find yourself really needing one of those icons, we hope you’d consider supporting the team and project.

As a side note, the request for Ear is #3726, and it was not highly requested

Anyway, the following icons in the accessibility category are free:
- https://fontawesome.com/v5.15/icons/deaf?style=solid
- https://fontawesome.com/v5.15/icons/assistive-listening-systems?style=solid

Hope it helps

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
