### ISSUE TITLE
Risk of code injection in conflict-detection.js

### ISSUE THREAD

**Issue by alexmamh** [FortAwesome/Font-Awesome#18434]
The use of WINDOW.location at line 730 and 797 as it is allows unvalidated user inputs to be used. 

More specifically it poses problem in the setTimeout of the domready function (line 94).

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

We already have a report here: #18114 

As mentioned in the other thread, 

> In version 5.10.0, a new script has been added to detect conflicts for diagnostic use only
> 
> Ref: https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/conflict-detection
> 
> This script is not part of the production code and should not be included / deployed on a server / loaded from a web page in normal conditions

I will ping Rob on the other thread, let's continue there
