### ISSUE TITLE
Fontawesome-svg-core common types missing version update in dependencies

### ISSUE THREAD

**Issue by dkovtuncode** [FortAwesome/Font-Awesome#18432]
**Describe the bug**
Im using **FA6 6.0.0-beta2**, importing all icons via fontawesome-svg-core => `library.add(fas, fab, fal)`
My tslint warns: 
_Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack'.
  Type 'IconPack' is missing the following properties from type 'IconDefinition': icon, prefix, iconNamets(2345)_
  
My package.json FA deps list: 
```
  "@fortawesome/fontawesome-common-types": "^0.2.36",
  "@fortawesome/fontawesome-svg-core": "^1.2.36",
  "@fortawesome/free-brands-svg-icons": "^6.0.0-beta2",
  "@fortawesome/pro-light-svg-icons": "^6.0.0-beta2",
  "@fortawesome/pro-solid-svg-icons": "^6.0.0-beta2",
  "@fortawesome/react-fontawesome": "^0.1.16",
```

**Expected behavior**
I found out that if I manually change version of fontawesome-common-types in lockfile to 0.3.0-beta2, warning message perishes.
Can you please fix fontawesome-svg-core inner dependency of 0.2.36

**Screenshots**
Lockfile prior to my manual change:
<img width="532" alt="Screenshot 2021-11-11 at 16 54 44" src="https://user-images.githubusercontent.com/90396045/141312447-37a60290-304c-4345-983c-569f51008fab.png">

Lockfile after my manual change (solves this problem): 
<img width="446" alt="Screenshot 2021-11-11 at 17 10 03" src="https://user-images.githubusercontent.com/90396045/141312251-d60f4fe3-f9ab-4b99-a242-aea2935c65b7.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply

Is this still an issue on the beta 3?

**Comment by dkovtuncode** [comment]
I'll check it out soon, ty for reply

**Comment by dkovtuncode** [comment]
Actually same thing for beta 3 ;(

**Comment by tagliala** [comment]
@robmadole any chance to take a look?

**Comment by robmadole** [comment]
@dkovtuncode You need to upgrade the `@fortawesome/fontawesome-svg-core` dependency.

The version that goes along with `6.0.0-beta3` is `1.3.0-beta3`.

Can you give that a try and let me know?

**Comment by dkovtuncode** [comment]
@robmadole Yeah it worked! Thank you very much!

**Comment by dkovtuncode** [comment]
@tagliala thank you very much for your response!
