### ISSUE TITLE
Icon request: location-arrow-slash

### ISSUE THREAD

**Issue by RobertJC31** [FortAwesome/Font-Awesome#18461]
**What can it be used for?**
This would be based off the already existing icon “location-arrow” except for with a slash in it. This would be useful in use cases where “location-arrow” is used but at a time where location is not available or not being used. 

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**

 ✔️  This is a single icon or matched pair (Ex: lock / unlock)
 ✔️  The title starts with "Icon request: " and is followed by the requested icon name (Ex: Icon request: magical-unicorn)
✔️  I have searched for existing issues and to the best of my knowledge this is not a duplicate
✔️  I have included at least one example image if it could be helpful (optional)
✔️  The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by MontoyaTech** [comment]
I was just about to post a request for this. Would love to have this icon in the FontAwesome icon set!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/166/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by MontoyaTech** [comment]
@tagliala Thanks for the reply! While that does work and I agree the transform system built into FontAwesome is great, it doesn't look quite as well as the native location-slash icon and it doesn't allow me to inject an icon like this into the content of a pseudo element.

Keep up the great work, hopefully an icon like this can exist natively someday!

Thanks.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
