### ISSUE TITLE
Icon request: cookies-check, cookies-times, cookie-cog

### ISSUE THREAD

**Issue by AlessandroVecchi** [FortAwesome/Font-Awesome#18466]
**What can it be used for?**
Icon set for cookies options

**Example image (optional)**
es.
![check](https://user-images.githubusercontent.com/20642463/143438120-afc408ce-387f-4c7e-81ad-2c4229f0847c.jpg)
![times](https://user-images.githubusercontent.com/20642463/143438125-50105d52-257c-48ff-89fa-6b9e57d2a313.jpg)
![gear](https://user-images.githubusercontent.com/20642463/143438127-b7300554-08e8-4878-9629-0bfa2443dbdf.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=&template=icon-request.md&title=):

> **Icon request checklist**
> - [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
> - [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
> - [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
> - [ ] I have included at least one example image if it could be helpful (optional)
> - [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

Requests for icon sets (= more than two strictly related icons) are not allowed in the free repo, but I can consider the above icons strictly related and keep the request open.

It is important though to understand that this is a request for 15 new icons (3 icons for each different style: solid, regular, light, thin, duotone)

Also, **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/599/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
