### ISSUE TITLE
npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by vqasimov** [FortAwesome/Font-Awesome#18462]
> npm install @fortawesome/fontawesome-svg-core
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-duotone-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-duotone-svg-icons@^5.15.4' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

npm is trying to download the Pro package from the public npm repository, and this is wrong

If you are a Pro customer, please follow instructions at https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro

If you don't see the pro instructions, please login and try again

If this is about a production server, please make sure to deploy the correct `.npmrc` and configuration variables

PS: as a pro customer, you can ask for dedicated support by sending an email at hello@fontawesome.com

Closing here, but feel free to comment and provide more information
