### ISSUE TITLE
Icon request: soil / sand / gravel / ground

### ISSUE THREAD

**Issue by TravelingTartar** [FortAwesome/Font-Awesome#18464]
**What can it be used for?**
We need an icon that can be used to describe ground, gravel, sand, pebbles, stones.

**Example image (optional)**
Imagine a series of different sized, not perfectly round, circles. Maybe some with a line over them to create the sensation of 'under' the ground.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I didn't get this request

Is it a request for a single icon representing "elevation"?

![image](https://user-images.githubusercontent.com/556268/143680877-2effea74-f6cb-4ba3-8d86-5d56a8df7943.png)

**Comment by TravelingTartar** [comment]
Hi.
Thanks so much for getting back to me.
No, though an 'elevation' icon would also be very very useful.
What I was referring to was icon(s) depicting the material itself: sand, or soil, or gravel or the actual ground. Another way of saying it, is that FA should have icons for: air, sea/water, flora, fauna, and ground/earth/soil, etc. Often we are called to depict the various elements making up our planet.
Hope this helps and thanks for your continued awesome product.
Cemil

**Comment by tagliala** [comment]
Thanks for the clarification

I still did not get if this is a request for a single icon or it isn't

> Imagine a series of different sized, not perfectly round, circles. Maybe some with a line over them to create the sensation of 'under' the ground.

If this is a request for a single icon, could you please provide a single color, 16px icon size suitable example?

PS: email attachments don't work, you should upload the image by following this link: https://github.com/FortAwesome/Font-Awesome/issues/18464

**Comment by TravelingTartar** [comment]
Hi, sorry, I did not realize you wanted a sample or model to work from. This is my first time suggesting an icon so I did not know how it works. I’ll gladly come up with a couple of ideas and send them to you. Give me a few days to think about how best to represent my idea.
Is that okay?
Thanks again.
Cemil

**Comment by TravelingTartar** [comment]
Hi.
Though I’m a graphic designer, I can’t seem to come up with something that 'I feel' fits with the FA family. All my attempts are too complex. I’m going to pass for now but if I come up with a simple concept I’ll send it your way. Meantime, of course, if any of your designers come up with a concept for the ground/soil/gravel paradigm, that would be great.
Thanks again for an otherwise great lineup!!!
Cemil

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
