### ISSUE TITLE
desktop: Play icon not well centered

### ISSUE THREAD

**Issue by alexjpwalker** [FortAwesome/Font-Awesome#18468]
The Font Awesome play icon is not well centered on Desktop.

This has been addressed for Web platforms in:
- #11578
- #3741

The advice in these issues is to add the `fa-fw` CSS class, however our Desktop platform does not use CSS.

How would we achieve the centering of the icon (or use of fixed-width icons) on Desktop?

**Screenshots**
From the Font Awesome website:
![image](https://user-images.githubusercontent.com/14253102/143482140-6ed09d50-6288-476c-919a-08d01680eeb7.png)

**Version and implementation**
Version: Font Awesome 6.0
- [x] On the Desktop, using OTF font

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@sensibleworld could you please take a look?

**Comment by alexjpwalker** [comment]
Closing this issue as it appears to be fixed in the latest Font Awesome (checked against the TTF font)

**Comment by sensibleworld** [comment]
Oh, yup! Sorry... didn't do my due diligence and follow up here :)
