### ISSUE TITLE
"Could not find icon" error in React

### ISSUE THREAD

**Issue by markbiek** [FortAwesome/Font-Awesome#18470]
After following the [React documentation](https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react), I can only get icons to appear by importing them individually.

I can't get any icons to render using strings and/or specifying the icon prefix.

In the `package.json`, I have the following dependencies:
```
"@fortawesome/fontawesome-free": "5.15.4",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
    "@fortawesome/free-regular-svg-icons": "5.15.4",
    "@fortawesome/free-solid-svg-icons": "5.15.4",
    "@fortawesome/react-fontawesome": "0.1.16",
```

and the following code
```
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCoffee } from "@fortawesome/free-solid-svg-icons";

import "./styles.css";

export default function App() {
  return (
    <div className="App">
      <FontAwesomeIcon icon="coffee" />
      <FontAwesomeIcon icon={["far", "coffee"]} />
      <FontAwesomeIcon icon={faCoffee} />
    </div>
  );
}
```

The only icon that renders is the final one (using `faCoffee`). The others throw _"Could not find icon {prefix: "fas", iconName: "coffee"}"_ and _"Could not find icon {prefix: "far", iconName: "coffee"}"_ console errors, respectively.

Not being able to use strings for icon definitions makes programmatically changing the style of a icon kind of tedious.

CodeSandbox Example:
https://codesandbox.io/embed/hopeful-sunset-zeimn?fontsize=14&hidenavigation=1&theme=dark

**Comment by markbiek** [comment]
My ultimate goal was to selectively use the solid `faHeart` icon or the regular `faHeart` depending on the context.

I can work around it by doing this:
```
import { faHeart as fasHeart } from '@fortawesome/free-solid-svg-icons';
import { faHeart as farHeart } from '@fortawesome/free-regular-svg-icons';
```
and then returning
```
<FontAwesomeIcon icon={solid ? fasHeart : farHeart} />;
```

But that's a lot of importing. It'd be much nicer to just use strings.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can confirm that 

```
      <FontAwesomeIcon icon="coffee" />
      <FontAwesomeIcon icon={["far", "coffee"]} />
```

do not work. Also, `far` is an issue here because `coffee` is not available in regular style for Font Awesome Free. Anyway, I got the same result when using `fas`

@robmadole any chance to take a look?

**Comment by robmadole** [comment]
@markbiek you might look at using the `library`. It's a little further down in the documentation.

Here is an example:

```javascript
import ReactDOM from 'react-dom'
import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { faCheckSquare, faCoffee } from '@fortawesome/free-solid-svg-icons'

library.add(fab, faCheckSquare, faCoffee)
```

You can then do this:

```jsx
<FontAwesomeIcon icon={["fas", "coffee"]} />
```
