### ISSUE TITLE
Security issue in conflict-detection.js

### ISSUE THREAD

**Issue by stackoverfloweth** [FortAwesome/Font-Awesome#18489]
The file: public/fonts/font-awesome/js-packages/@fortawesome/fontawesome-pro/js/conflict-detection.js

The issue: According to GitHub security scan provided by [CodeQL](https://codeql.github.com/codeql-query-help/javascript/js-remote-property-injection/) this file fails `js/remote-property-injection` on line 892 and 894

<img width="966" alt="Screen Shot 2021-12-07 at 7 44 57 AM" src="https://user-images.githubusercontent.com/6098901/145040248-518d5100-0ff4-466b-93ca-c666f32cf99b.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This is a duplicate of #18114

Please take a look at my answer there: https://github.com/FortAwesome/Font-Awesome/issues/18114#issuecomment-887788132

Feel free to comment on the other topic

Closing here
