### ISSUE TITLE
 Icon Request: Meta

### ISSUE THREAD

**Issue by Shiftcoder94** [FortAwesome/Font-Awesome#18481]
**What can it be used for?**
It can be used by social websites

**Example image (optional)**
[
[Meta Box Icon.zip](https://github.com/FortAwesome/Font-Awesome/files/7642670/Meta.Box.Icon.zip)
](url)

**Icon request checklist**
- [Single] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [✔ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [✔ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ✔] I have included at least one example image if it could be helpful (optional)

**Comment by coliff** [comment]
This has been added now: https://fontawesome.com/icons/meta?s=brands

The strange thing is that it's a pro icon, unlike the 462 other brand icons which are free. is that a bug? (I don't personally mind much, I'm a Pro subscriber, but thought I'd mention)

**Comment by aethior** [comment]
> The strange thing is that it's a pro icon, unlike the 462 other brand icons which are free. is that a bug? (I don't personally mind much, I'm a Pro subscriber, but thought I'd mention)

@davegandy Can you explain this please?  Thanks.

**Comment by tagliala** [comment]
Hi, thanks for the report

I think this is a mistake

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/meta?s=brands
