### ISSUE TITLE
fa-ad does not seem to work any more

### ISSUE THREAD

**Issue by AuspeXeu** [FortAwesome/Font-Awesome#18490]
![image](https://user-images.githubusercontent.com/2115696/145165829-218c485e-842b-4ba7-b4da-e63961c33871.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is caused by a third-party extension. Please take a look at this pinned issue: #18118

Closing here as a duplicate
