### ISSUE TITLE
Types missing for library.definitions in svg-core

### ISSUE THREAD

**Issue by Pearce-Ropion** [FortAwesome/Font-Awesome#18502]
**Describe the bug**
The type definition for the `library.definitions` property in `fortawesome/fontawesome-svg-core` is missing.
This makes it difficult to iterate on added icons in the typescript environment. 

**To Reproduce**
https://codesandbox.io/s/fontawesome-typescript-library-definitions-error-c1ryo

In this example, I created a simple icon selector that creates react-select options from the library
Have a look at App.tsx. Once the typescript loads, you can see that typescript is warning that  `definitions` does not exist on the library
```
Property 'definitions' does not exist on type 'Library'.
```

**Expected behavior**
The type definition should exist for the `library.definitions` property

**Version and implementation**
Version: @fortawesome/fontawesome-svg-core v1.2.36
Browser and version: N/A

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by mikey-gray** [comment]
For now I've been extending the interface as a work around:

```tsx
import { Library, library } from '@fortawesome/fontawesome-svg-core'

interface Library2 extends Library {
  definitions?: {
    far: Record<string, unknown[]>
    fas: Record<string, unknown[]>
  }
}

const lib = library as Library2
```

I personally only need the icon keys so this is enough to get them with `Object.keys(lib.definitions.far)`.
