### ISSUE TITLE
Tiktok Icon

### ISSUE THREAD

**Issue by dwernz** [FortAwesome/Font-Awesome#18512]
Hello Font Awesome,
All the other social media icons work just fine, but the TikTok one either displays a circle with alternating "?" and "!", or does not appear at all. Is there a recommended fix?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure that you are using Font Awesome >= 5.14.0 (current stable version is 5.15.4)

If you are using an up to date version of Font Awesome and you still experience issues, please fill our  [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Closing here, but feel free to comment with a reproducible test case and I will reopen

**Comment by dwernz** [comment]
Using up-to-date font-awesome worked with "normal" pages, but it is not working with React pages.

**Comment by tagliala** [comment]
> but it is not working with React pages.

Please provide a reproducible test case
