### ISSUE TITLE
Icon request: floppy-disk-circle-check

### ISSUE THREAD

**Issue by DiscipvIvs** [FortAwesome/Font-Awesome#18516]
**What can it be used for?**
Right now there are:
-floppy-disk
-floppy-disk-circle-arrow-right
-floppy-disk-circle-xmark
Which could be interpreted as "Save!", "Saving" & "Save Failed"

A floppy disk with a checkmark in the circle would be really helpful to represent "Save Successful"

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/602/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by DiscipvIvs** [comment]
Thank you for your swift and comprehensive reply,

I am using the icons within `<button>` tags and would like to keep them pure CSS. 

I ended up using stacking to create a similar result as you showed me. It's a bit more complicated than the single icon solution would have been, but the option of having the circles in a different color is definitely interesting. :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
