### ISSUE TITLE
Icon request: sign-in-alt-slash

### ISSUE THREAD

**Issue by durangod** [FortAwesome/Font-Awesome#18513]
**What can it be used for?**
I have online log reports that list the failed logins that have occured and would like to show a failed login icon rather than the normal sign-in icon.   I would also like to show in on my failed login page, as well as my failed login documentation. 

**Example image (optional)**
You already have a sign-in icon, [fa fa-sign-in] i am requesting a similar icon with a slash  through it (some might call it a login buster icon)   Its just a sign-in icon with a slash through it, or a circle with a slash like a buster sign.

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by durangod** [comment]
![failedlogin_suggestion](https://user-images.githubusercontent.com/50722740/146636895-e7e17279-698e-44b7-9d4f-df52e16e99aa.jpg)

something like this

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/7vst50jk/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by durangod** [comment]
OK thanks for the information and the links.  I was not aware i could create new icons legally like that. Being a php developer i really respect the license of others.  I appreciate the reply :)
 
On Saturday, December 18, 2021 at 4:19 AM, Geremia Taglialatela ***@***.***> wrote:



Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that in a web   application it is possible to create the requested icon by using   power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/7vst50jk/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

—
Reply   to this email directly, view   it on GitHub, or unsubscribe.
Triage   notifications on the go with GitHub Mobile for iOS   or Android.   
You are receiving this because you authored the thread.Message   ID:   ***@***.***>
   [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/FortAwesome/Font-Awesome/issues/18513#issuecomment-997181357", "url": "https://github.com/FortAwesome/Font-Awesome/issues/18513#issuecomment-997181357", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
