### ISSUE TITLE
Icons no longer loading due to SSL certificate error 526

### ISSUE THREAD

**Issue by Clarkey87** [FortAwesome/Font-Awesome#18510]
Hi,

As per the title, I am receiving an SSL certificate error (526) each time I view a URL on kit.fontawesome.com - see screenshot below. Please resolve asap.

![FontAwesome - SSL Error 526](https://user-images.githubusercontent.com/74078139/146102084-35e5545a-8443-4a7b-806d-d23aa19cae3d.PNG)

Many thanks,
Clarkey

**Comment by chnebx** [comment]
I have the exact same problem

**Comment by Clarkey87** [comment]
Looks like it's working again :)

**Comment by tagliala** [comment]
Yes, this was a temporary issue, apologies

Let us know if it is still an issue
