### ISSUE TITLE
Can't install @fortawesome/pro-duotone-svg-icons

### ISSUE THREAD

**Issue by fanttm** [FortAwesome/Font-Awesome#18525]
Refer to "https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react", I had installed pro-(solid|regular|light)-svg-icons, but can not install @fortawesome/pro-duotone-svg-icons.

[OS & npm config]
OS: windows 10 Home
npm config: 
    //npm.fontawesome.com/:_authToken = (protected)
    registry = "https://registry.npm.taobao.org/"

[Installed info]
PS E:\dev\my-app03> npm ls @fortawesome/pro-solid-svg-icons
my-app03@0.1.0 E:\dev\my-app03
`-- @fortawesome/pro-solid-svg-icons@5.1.0-5

PS E:\dev\my-app03> npm ls @fortawesome/pro-regular-svg-icons
my-app03@0.1.0 E:\dev\my-app03
`-- @fortawesome/pro-regular-svg-icons@5.1.0-8

PS E:\dev\my-app03> npm ls @fortawesome/pro-light-svg-icons
my-app03@0.1.0 E:\dev\my-app03
`-- @fortawesome/pro-light-svg-icons@5.3.1

[Error info]
PS E:\dev\my-app03> npm i --save @fortawesome/pro-duotone-svg-icons
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/@fortawesome%2fpro-duotone-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-duotone-svg-icons@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fanttm\AppData\Local\npm-cache\_logs\2021-12-20T08_43_58_125Z-debug.log

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

It looks like a configuration issue, since npm is trying to download font awesome pro from the public npm repository at ` https://registry.npmjs.com`

Please make sure that you have followed the instructions at https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro and that npm is able to read the proper repository configuration from `.npmrc`

**Comment by fanttm** [comment]
The results I tried are as follows: 

PS E:\dev\my-app03> npm config get
; "user" config from C:\Users\fanttm\.npmrc

registry = "https://registry.npm.taobao.org/"

; "project" config from E:\dev\my-app03\.npmrc

@fortawesome:registry = "https://npm.fontawesome.com/"
//npm.fontawesome.com/:_authToken = (protected)

; node bin location = D:\Program Files\nodejs\node.exe
; cwd = E:\dev\my-app03
; HOME = C:\Users\fanttm
; Run `npm config ls -l` to show all defaults.
PS E:\dev\my-app03> npm i --save @fortawesome/pro-duotone-svg-icons
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fanttm\AppData\Local\npm-cache\_logs\2021-12-22T02_09_18_329Z-debug.log

**Comment by tagliala** [comment]
At this point I think this may be an issue with the license. Please send an email at hello@fontawesome.com

Please also add a link to this issue
