### ISSUE TITLE
Icon request: ltk (previously liketoknow.it)

### ISSUE THREAD

**Issue by barrelaged** [FortAwesome/Font-Awesome#18520]
**What can it be used for?**
To link directly to the LTK website/app for one click social shopping. 

**Example image (optional)**
![LIKEtoKNOW it_Icon](https://user-images.githubusercontent.com/96354965/146655072-668d52dc-73f6-47d5-8564-d1596655917f.png)

**Icon request checklist**
- [ x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x ] I have included at least one example image if it could be helpful (optional)
- [ x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Let's use #11155, I will add ltk to the title

**Comment by barrelaged** [comment]
Thanks!

Kind Regards,

Barrel Aged Creations

**Comment by barrelaged** [comment]
How can I get the "name" to use? I cannot locate it on the brand page?

*Kind Regards,*

*Barrel Aged Creations*

<https://barrelagedcreations.com/>
<https://www.facebook.com/barrelagedcreations/>
<https://www.instagram.com/barrelagedcreations/>
<https://www.pinterest.com/barrelagedcreations/boards/>

**Comment by tagliala** [comment]
> How can I get the "name" to use? I cannot locate it on the brand page?

 #11155 exists as a request, please add a 👍🏼 reaction to that request

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
