### ISSUE TITLE
Incorrect types for Pro light icons (React)

### ISSUE THREAD

**Issue by lifedup** [FortAwesome/Font-Awesome#18524]
**Describe the bug**
The types for `pro-light-svg-icons` are set to type `IconDefinition` and `FontAwesomeIcon` prop `icon` expects type `IconProp`

The exact typescript error is: _Type 'IconDefinition' is not assignable to type 'IconProp'._

**To Reproduce**
Add a pro light icon in a typed environment to the `FontAwesomeIcon` component.  

```
import { faCommentsAlt } from '@fortawesome/pro-light-svg-icons';
<FontAwesomeIcon icon={faCommentsAlt} />
```

**Expected behavior**
The type wouldn't throw an error when using default icons

**Version and implementation**
@fortawesome/fontawesome-svg-core v6.14.15
@fortawesome/pro-light-svg-icons v6.14.15

- [X] SVG with JS

The current workaround is redefining the type inline.

```
import { IconProp } from '@fortawesome/fontawesome-svg-core';
<FontAwesomeIcon  icon={faCommentsAlt as IconProp} />
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

@robmadole any chance to take a look?

**Comment by robmadole** [comment]
@lifedup can you double-check the version numbers? either they are wrong or you have time-traveled?!

**Comment by lifedup** [comment]
You caught me.  I knew it was bound to happen. 

![image](https://user-images.githubusercontent.com/2423551/146796986-f5d29217-88b5-4cb5-b5d1-3f0a80c5f1ce.png)


I  ran `npm @fortawesome/pro-light-svg-icons -v ` - Is there a different way to check the version?

**Comment by robmadole** [comment]
Can you show me all the entries in your `package.json` file that mention `@fortawesome`?

Something like this might work:

```
cat package.json | grep @fortawesome
```

**Comment by lifedup** [comment]
I copied the install docs.  The `pro-light-svg-icons` icons are v 6.0.0-alpha2

```
    "@fortawesome/fontawesome-pro": "^6.0.0-beta3",
    "@fortawesome/fontawesome-svg-core": "^1.3.0-beta3",
    "@fortawesome/pro-light-svg-icons": "^5.15.4",
    "@fortawesome/pro-regular-svg-icons": "^6.0.0-beta3",
    "@fortawesome/pro-thin-svg-icons": "^6.0.0-beta3",
    "@fortawesome/react-fontawesome": "^0.1.16",
```

**Comment by robmadole** [comment]
No, you don't need `fontawesome-pro`. You can delete that one.

It looks like the `pro-light-svg-icons` package has not been upgraded yet. It's still at 5.15.4. Try upgrading that one as you did the others and see if that resolves the issue.

If you are still having trouble with missing icons, give me a few examples to check.

**Comment by lifedup** [comment]
I uninstalled all fortawesome packages and reinstalled them with the `@next` version, which fixed all of them.

All icon versions and core packages now say version `6.14.15`. 

The original issue was fixed - the types are now correct, and all of the missing icons are now found!  

Thank you!

**Comment by robmadole** [comment]
Glad to hear!

**Comment by tagliala** [comment]
> All icon versions and core packages now say version 6.14.15.

Hi, apologies if I didn't notice this before, but `npm -v` returns the version of `npm`

To check the version of an installed package, you should try `npm ls package`, e.g., `npm ls @fortawesome/fontawesome-free`
