### ISSUE TITLE
Updated logo for Fedora Project / Fedora Linux

### ISSUE THREAD

**Issue by mattdm** [FortAwesome/Font-Awesome#18537]
**Describe the bug**

See discussion in #980. Because at the time Fedora did not have a logo which works in a single-color treatment, the icon included in Font Awesome is an interpretation. We'd like that fixed — and we have a new logo which works in a single-color treatment. (In fact, the Font Awesome need was one of the big reasons we went through the whole process of creating a new logo.)

**To Reproduce**
Look at [existing fa-fedora](https://fontawesome.com/v5.15/icons/fedora?style=brands), feel sad.

**Expected behavior**

We have a new logo! And, I have clearance from the Fedora Council (as stewards of the trademark) and our legal for it to be in Font Awesome officially. I've attached the official SVG below (in a zipfile, as github won't let me attach the SVG directly).

Additionally:

----

The Fedora Council grants permission for a version of the official Fedora logo to be included in your collection of icons, unmodified from the logo image we are providing here except in size and/or file format, provided you include this text, the legal notice below, and a link to https://docs.fedoraproject.org/en-US/project/brand/ in any relevant accompanying documentation and websites. Please do not create modified versions of the logo, even to match a style or theme.

ACKNOWLEDGMENT FOR LOGO USE:

The "Fedora" logo provided as part of this collection is a trademark of Red Hat, Inc. and is provided solely for use to accurately identify Fedora or its products. To use this logo, you must agree to only use the logo in compliance with the Fedora Trademark Guidelines: https://fedoraproject.org/wiki/Legal:Trademark_guidelines, and never to use any logo or trademark of Red Hat in a manner that suggests that Red Hat or Fedora owns, sponsors, or endorses your products or services, or that you own any rights in the logo or trademark.

----

I hope this works for you. Let me know if there's anything more I can do to help.

**Screenshots**

PNG of new logo. Of course, please do not use / trace this — use [the SVG version](
[fedora_fa.zip](https://github.com/FortAwesome/Font-Awesome/files/7771608/fedora_fa.zip)
).

![fedora_fa](https://user-images.githubusercontent.com/123367/147295369-51d30003-4bf9-424c-8193-abd822fe924c.png)

**Version and implementation**
Version: 5.x, 6.x
Browser and version: n/a

I hope that you can address this in an update to 5.x, as well as the upcoming 6!

- [x] SVG with JS
- [x] Web Fonts with CSS
- [x] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

[fedora_fa.zip](https://github.com/FortAwesome/Font-Awesome/files/7771608/fedora_fa.zip)

**Comment by mattdm** [comment]
I should probably note that the https://docs.fedoraproject.org/en-US/project/brand/ site is currently a placeholder. Didn't get finished in end-of-year stuff, but that's where the new official guidelines will be soon, and I didn't want to wait any longer on this!

**Comment by sensibleworld** [comment]
Thanks, @mattdm! I'll get this in for the next release!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/fedora?s=brands
