### ISSUE TITLE
Does @fortawesome/fontawesome-pro include @fortawesome/pro-{solid|regular|light|duotone}-svg-icons

### ISSUE THREAD

**Issue by fanttm** [FortAwesome/Font-Awesome#18531]
https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react

This document explain：
  npm i --save @fortawesome/pro-solid-svg-icons
  npm i --save @fortawesome/pro-regular-svg-icons
  npm i --save @fortawesome/pro-light-svg-icons
  npm i --save @fortawesome/pro-duotone-svg-icons

https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro

This document explain:
  npm install --save @fortawesome/fontawesome-pro

So does @fortawesome/fontawesome-pro include @fortawesome/pro-{solid|regular|light|duotone}-svg-icons

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`@fortawesome/fontawesome-pro` is an all-in-one package which contains the distributable js files under `/js` folder as well as css files and webfonts, svg sprites, metadata

If you are interested in using react, please follow instructions at https://fontawesome.com/v5.15/how-to-use/on-the-web/using-with/react
