### ISSUE TITLE
Icon request: Nepalese Rupee

### ISSUE THREAD

**Issue by ksvgyw** [FortAwesome/Font-Awesome#18544]
**What can it be used for?**
It can be used for Nepalese rupee sign

**Example image (optional)**
Rs

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this icon has been implemented in FA6:
https://fontawesome.com/v6.0/icons/rupee-sign?s=solid

If this is not the icon you are requesting, please provide an example and a link to a wikipedia page

Meanwhile, closing here

**Comment by ksvgyw** [comment]
Thank you for prompt reply. Yes that is the symbol in english but actually
the symbol is under symbol section of the link i provided below. And I'm
wondering can i use v6 icons under v5?
https://en.m.wikipedia.org/wiki/Nepalese_rupee

**Comment by tagliala** [comment]
> And I'm
wondering can i use v6 icons under v5?

Hi, new icons will not be backported

You can:
- Use FA6 beta 3: https://fontawesome.com/v6.0
- Wait for the official release of FA6 in February 22
- Customize FA5 (with SVG is easy): https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
