### ISSUE TITLE
Problem with the figma component on icons link and open book

### ISSUE THREAD

**Issue by Berlureau** [FortAwesome/Font-Awesome#18545]
Hi,

we are experiencing an issue using the v6 component under Figma. Some icons like Link, open book, are not 24x24 perfect for example. See attached examples.
Best regards
![Capture d’écran 2021-12-30 à 10 33 01](https://user-images.githubusercontent.com/56669782/147739808-95b82936-143e-42cc-befc-7c53d3a6886b.png)
![Capture d’écran 2021-12-30 à 10 33 07](https://user-images.githubusercontent.com/56669782/147739809-b0792518-7cd8-466c-9ac8-36615730ca06.png)
,

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld could you please take a look?
