### ISSUE TITLE
money bill wave icon

### ISSUE THREAD

**Issue by tonythewhat** [FortAwesome/Font-Awesome#18547]
Icon is appearing as as question mark and exclamation mark within a dotted circle.

https://codepen.io/tonythewhat/pen/qBPoVar

https://fontawesome.com/v5.15/icons/money-bill-wave?style=solid

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Would like to see the money bill wave icon

**Version and implementation**
Version: 5.0.13
Browser and version: 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

> Version: 5.0.13

`money-bill-wave` has been introduced in version 5.0.13, but your fiddle is using FA 5.0.6.

Please upgrade Font Awesome to use that icon

Closing here, but feel free to comment
