### ISSUE TITLE
dog icon issue

### ISSUE THREAD

**Issue by tonythewhat** [FortAwesome/Font-Awesome#18546]
Icon is appearing as as question mark and exclamation mark within a dotted circle.

**To Reproduce**
[Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.
](https://codepen.io/tonythewhat/pen/wvrmPgQ)
Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
Would like to see the dog icon  instead.
**Screenshots**

**Version and implementation**
Version: Version 5.12.0
Browser and version: 

- [ ] SVG with JS
- [x] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi again,

same as the other issue

> Version 5.12.0

The fiddle is using 5.0.6

Please make sure that your application is using the correct Font Awesome version, which is 5.12.0 in this case

Fixed fiddle: https://codepen.io/tagliala/pen/QWqmOZW
