### ISSUE TITLE
Icons inverted

### ISSUE THREAD

**Issue by yuribertoli** [FortAwesome/Font-Awesome#18549]
<i class="fas fa-phone"></i>     and     <i class="fas fa-phone-alt"></i>    are inverted and show up the wrong icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) that could help
