### ISSUE TITLE
Icon Request: icon-prayer (icon-praying-hands)

### ISSUE THREAD

**Issue by Shylmysten** [FortAwesome/Font-Awesome#1855]
The icon would be praying hands. I would be using this in prayer request boxes in conjunction with the wordpress Avada theme that is currently the #1 sold theme on Themeforest. 
![phand_black](https://f.cloud.github.com/assets/5308615/1023436/c4ab84c8-0deb-11e3-89aa-e026c5b53695.png)
![phand1](https://f.cloud.github.com/assets/5308615/1023439/d29769a8-0deb-11e3-803d-af35bb059142.png)
![screentshot_icons_in_avada_theme](https://f.cloud.github.com/assets/5308615/1023441/41c2ad88-0dec-11e3-89eb-b49e222a4572.jpg)

Thanks you very much!!!

**Comment by kanekokoudai** [comment]
+1 soooo good! thanks

**Comment by bluezuccini** [comment]
+1 

I also need an icon of praying hands. We have an icon menu that leads people to the prayer request form but no one can find it bc I had to use an icon doesn't really represent prayer.
![hands](https://cloud.githubusercontent.com/assets/12254064/7473733/326f9f98-f30b-11e4-847c-5137aa07197e.jpg)

**Comment by freak3dot** [comment]
+1 I was looking for this to use in a reveal.js presentation.

**Comment by cdavis411** [comment]
+1 this would be very helpful.

**Comment by Kelevari** [comment]
+1 this would be very helpful.

**Comment by dbarcelos** [comment]
+1 this would be very helpful.

**Comment by gustavohellwig** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by MVprobr** [comment]
+1

**Comment by mwthink** [comment]
+1 very useful for religious-themed websites

**Comment by pappavic** [comment]
+1

**Comment by Subair-tc** [comment]
+1

**Comment by anonymousabyss** [comment]
Greetings, Was this request ever fulfilled?  I am in need of a praying hands icon to a christian theme I am working on.  This addition would be very useful.  Thanks in advance.

**Comment by Dsign** [comment]
This might be a more iconic suggestion: 
![pray](https://cloud.githubusercontent.com/assets/20301719/18100351/97928e7e-6eb8-11e6-895a-48d0ed5b7765.png)

**Comment by Crissov** [comment]
## Unicode emojis
* [🙏 U+1F64F Person with Folded Hands](http://emojipedia.org/person-with-folded-hands)
* [🛐 U+1F6D0 Place of Worship](http://emojipedia.org/place-of-worship)

**Comment by hvtuongpixa** [comment]
+1

**Comment by jsilvanus** [comment]
+1 would be very much appreciated

**Comment by PamelaN426** [comment]
I really need this icon as well. Thanks!

**Comment by Anorwyn** [comment]
+1 we're a church and could really do with a praying hands icon, thanks!

**Comment by rombodhidharmainternational** [comment]
+1 Simple prayer icon much needed for buddhist temple website:
![pray](https://user-images.githubusercontent.com/33168618/32131579-f827fa00-bbdb-11e7-87bd-4d4760a07590.png)
![pray 2](https://user-images.githubusercontent.com/33168618/32131580-f9425f66-bbdb-11e7-8af2-b9ed8ba2d39c.png)

**Comment by danyellnoe** [comment]
+1 Would love to see this added as well

**Comment by vastdevops** [comment]
+1 Need

**Comment by Wingo5315** [comment]
You could change the name to fa-hands-together. Or you could use this icon instead:
![image](https://user-images.githubusercontent.com/25369857/43057576-112d81a0-8e3b-11e8-86ec-33cd182bb302.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pray?style=solid
https://fontawesome.com/icons/praying-hands?style=solid

**Comment by corydbrown** [comment]
bless you lol 🙏

**Comment by Shylmysten** [comment]
Very Awesome! Thank you very much!!

**Comment by vastdevops** [comment]
Full blown awesome!
