### ISSUE TITLE
Icon request: icon-clean

### ISSUE THREAD

**Issue by amoretty** [FortAwesome/Font-Awesome#18556]
** What can it be used for? **
It is used to clean the records of a view.

** Example image **
![image](https://user-images.githubusercontent.com/23409467/148413126-892b0198-3215-4717-b296-370f8b9ab47a.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

broom icon is already available:
- https://fontawesome.com/v5.15/icons/broom?style=solid

Closing here, but feel free to comment and provide more information if I didn't get this request
