### ISSUE TITLE
CDN is down

### ISSUE THREAD

**Issue by NimeshDhruve** [FortAwesome/Font-Awesome#18567]
**Describe the bug**
Fontawesome CDN seems to be down.

**To Reproduce**
Example: Put this URL in browser and you will get "This site can't be reached"
https://use.fontawesome.com/releases/v5.0.6/js/all.js
https://use.fontawesome.com/releases/v5.8.1/js/fontawesome.js

**Expected behavior**
Should provide minified JS file

**Screenshots**
![image](https://user-images.githubusercontent.com/7783989/148583009-33914709-7d5e-49e3-a2d3-e13653e46e46.png)

**Version and implementation**
Version: v5.0.6, 5.8.1
Browser and version: Latest version of Chrome, Firefox and Eduge

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Cannot replicate in my region (EU / Italy)

Maybe a region issue?
