### ISSUE TITLE
Icon request: question-chat a question mark in a chat bubble

### ISSUE THREAD

**Issue by pocheco** [FortAwesome/Font-Awesome#18565]
**What can it be used for?**
Describe how this could be used / the use case for this icon.

Could be used for indicating conversations that have questions.

**Example image (optional)**
Insert the example image here if necessary.

**Icon request checklist**
- [ ] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [ ] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [ ] I have included at least one example image if it could be helpful (optional)
- [ ] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon will be available in Font Awesome 6 Free: 
- https://fontawesome.com/v6.0/icons?q=message-question&s=solid

FA6 is in public beta and it will be released in February

https://fontawesome.com/v6.0

Hope it helps

closing here

**Comment by tagliala** [comment]
**in a web application** it is possible to create the requested icon for free by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/607/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
