### ISSUE TITLE
NPM postinstall scripts error

### ISSUE THREAD

**Issue by nickian** [FortAwesome/Font-Awesome#18571]
I have Node/NPM installed via NVM. I am running as root. I have the latest LTS (node v16.13.1) installed. I can't simply install Font Awesome like it's normally done:

`npm install --save @fortawesome/fontawesome-free`

This causes errors and fails. I have to add this in order to get it working:

`npm install --save @fortawesome/fontawesome-free --ignore-scripts`

Without `--ignore-scripts` I get the errors in the log below. What exactly is happening here?

```
123 info run @fortawesome/fontawesome-free@5.15.4 postinstall node_modules/@fortawesome/fontawesome-free node attribution.js
124 info run @fortawesome/fontawesome-free@5.15.4 postinstall { code: 127, signal: null }
125 timing reify:rollback:createSparse Completed in 246ms
126 timing reify:rollback:retireShallow Completed in 0ms
127 timing command:install Completed in 2314ms
128 verbose stack Error: command failed
128 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
128 verbose stack     at ChildProcess.emit (node:events:390:28)
128 verbose stack     at maybeClose (node:internal/child_process:1064:16)
128 verbose stack     at Socket.<anonymous> (node:internal/child_process:450:11)
128 verbose stack     at Socket.emit (node:events:390:28)
128 verbose stack     at Pipe.<anonymous> (node:net:687:12)
129 verbose pkgid @fortawesome/fontawesome-free@5.15.4
130 verbose cwd /my-dir/
131 verbose Linux 5.4.0-91-generic
132 verbose argv "/root/.nvm/versions/node/v16.13.1/bin/node" "/root/.nvm/versions/node/v16.13.1/bin/npm" "install" "--save" "@fortawesome/fontawesome-free"
133 verbose node v16.13.1
134 verbose npm  v8.1.2
135 error code 127
136 error path /my-dir/node_modules/@fortawesome/fontawesome-free
137 error command failed
138 error command sh -c node attribution.js
139 error sh: 1: node: Permission denied
140 verbose exit 127
```

**Comment by tagliala** [comment]
Sorry, cannot replicate

```
root@docker:/app/fatest# uname -a
Linux docker 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@docker:/app/fatest# whoami
root
root@docker:/app/fatest# nvm --version
0.38.0
root@docker:/app/fatest# node --version
v16.13.1
root@docker:/app/fatest# npm --version
8.1.2
root@docker:/app/fatest# npm install --save @fortawesome/fontawesome-free

added 1 package, and audited 2 packages in 4s

found 0 vulnerabilities
root@docker:/app/fatest# 
```

**Comment by nickian** [comment]
Hmm. The only difference is that my NVM is version 0.39.1, but I don't think that should matter. I'm running as root, so I don't understand. I still tried doing `sudo chown -R $(whoami) ~/.npm` but I didn't matter, as I suspected.

I don't think it's a $PATH issue. Mine looks like this:
`/root/.nvm/versions/node/v16.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

The weird thing is that when I change back to an older version (e.g., `nvm use 12.22.8`), then it works without any issues.

**Comment by lensbart** [comment]
This issue can be resolved by removing the `postinstall` script, or, as a workaround if you’re using [Yarn PnP](https://yarnpkg.com/features/pnp), by adding the following to your `package.json`:

```
"dependenciesMeta": {
  "@fortawesome/fontawesome-common-types": {
    "built": false
  },
  "@fortawesome/fontawesome-svg-core": {
    "built": false
  },
  "@fortawesome/free-brands-svg-icons": {
    "built": false
  },
  "@fortawesome/free-solid-svg-icons": {
    "built": false
  },
},
```

See this issue: https://github.com/FortAwesome/Font-Awesome/issues/18803

**Comment by tagliala** [comment]
~Could you please clarify if this is an issue with Font Awesome?~

Ok, I'm reading at #18803

**Comment by tagliala** [comment]
I would close this in favor of #18803, which has more details and it is also planned for 6.2 release

Please comment if this is a different issue
