### ISSUE TITLE
fa-whatsapp won't show using vue-fontawesome

### ISSUE THREAD

**Issue by jerichosiahaya** [FortAwesome/Font-Awesome#18578]
I tried to use Whatsapp icon from brands category. I'm using Vue with `:icon` binding like this `<font-awesome class="ml-2" :icon="['fab', 'fa-whatsapp']" />`, but nothing show up. Meanwhile, if I use `github` or `twitter` icon, it works just fine. Any idea why this is happen?

This is packages that I've installed:
```json
"@fortawesome/fontawesome-svg-core": "^1.2.36",
"@fortawesome/free-brands-svg-icons": "^5.15.4",
"@fortawesome/free-solid-svg-icons": "^5.15.4",
"@fortawesome/vue-fontawesome": "^2.0.6",
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the very late reply.

I've tried to replicate this issue but I wasn't able.

Here it is my code: https://codesandbox.io/s/dank-currying-0runty?file=/src/App.vue

Could you please provide a reproducible test case?

I've just followed instructions at https://github.com/FortAwesome/vue-fontawesome

**Comment by jerichosiahaya** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community and apologies for the very late reply.
> 
> I've tried to replicate this issue but I wasn't able.
> 
> Here it is my code: https://codesandbox.io/s/dank-currying-0runty?file=/src/App.vue
> 
> Could you please provide a reproducible test case?
> 
> I've just followed instructions at https://github.com/FortAwesome/vue-fontawesome

Definitely my mistake. I didn't add the icon to the library yet. Thanks for the solution.
