### ISSUE TITLE
Icons request: icon-comment-add

### ISSUE THREAD

**Issue by EbenBosman** [FortAwesome/Font-Awesome#1857]
Hi guys,

I thought this might add to your collection and be useful to others and not just for me. Would it be possible to add an icon for a new comment to be added. Like a comment with a plus sign? 

Example attached

Kind regards
Eben

![commentsadd16](https://f.cloud.github.com/assets/5286116/1025041/987aa72e-0e38-11e3-8337-d67f3f5bdf87.png)

**Comment by nyon** [comment]
I've added fa-comment-plus (and others) to fontawesome-actions here: http://github.com/nyon/fontawesome-actions

**Comment by sensibleworld** [comment]
<img width="776" alt="Screen Shot 2021-03-30 at 1 31 47 PM" src="https://user-images.githubusercontent.com/529604/113031098-47a5d080-915c-11eb-8d42-4cd948563b14.png">

https://fontawesome.com/icons/comment-plus?style=solid
