### ISSUE TITLE
v6 Duotone Icons not imported in SCSS

### ISSUE THREAD

**Issue by gluecksmensch** [FortAwesome/Font-Awesome#18585]
**Describe the bug**
I upgraded to v6 Pro via npm (yes, we have a plan and registry token) and imported all the FA entry files into our SASS environment. After compiling and testing CSS, I found that duotone icons look different and spin animation was off. After investigation, I found that none of the FA6 entry files import the partial `_duotone-icons.scss`.

**To Reproduce**
Create a project with an SCSS entry file and import all necessary FA6 entry files (`node_modules` gets resolved by our build):
```css
@import "@fortawesome/fontawesome-pro/scss/fontawesome";
@import "@fortawesome/fontawesome-pro/scss/regular";
@import "@fortawesome/fontawesome-pro/scss/light";
@import "@fortawesome/fontawesome-pro/scss/solid";
@import "@fortawesome/fontawesome-pro/scss/brands";
@import "@fortawesome/fontawesome-pro/scss/duotone";
@import "@fortawesome/fontawesome-pro/scss/thin";
```
Compile the CSS to CSS and check in the Browser. Once you include the partial `_duotone-icons.scss` into your entry file, everything works as expected:

```css
@import "@fortawesome/fontawesome-pro/scss/fontawesome";
@import "@fortawesome/fontawesome-pro/scss/regular";
@import "@fortawesome/fontawesome-pro/scss/light";
@import "@fortawesome/fontawesome-pro/scss/solid";
@import "@fortawesome/fontawesome-pro/scss/brands";
// added:
@import "@fortawesome/fontawesome-pro/scss/duotone-icons";
@import "@fortawesome/fontawesome-pro/scss/duotone";
@import "@fortawesome/fontawesome-pro/scss/thin";
```

**Expected behavior**
I would expect the `_duotone-icons.scss` partial to be imported by the `duotone.scss` entry file. If there are good reasons for not importing this partial, I would expect some hints in the documentation as to which SCSS imports I need to get the same CSS result as in your precompiled `all.css`.

**Screenshots**
`<i class="fad fa-spinner-third fa-2x fa-spin"></i>`
Broken version:
![duotone-icons-spin](https://user-images.githubusercontent.com/483622/149511753-cb6fefe7-a72a-4df9-9a9f-d658e79c22c7.gif)

Expected:
`<i class="fad fa-spinner-third fa-2x fa-spin"></i>`
![duotone-icons-spin-expected](https://user-images.githubusercontent.com/483622/149512084-e8901db7-bbfe-45bd-9927-d03a99a50129.gif)

**Version and implementation**
Version: 6.0.0-beta3
Browser and version: Chrome

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply. 

I can see that this is still an issue with the stable version of FA6.

I would expect the same, but let's ask @robmadole if there is a reason

**Comment by KirkNicholson** [comment]
I had the same issue with duo-tone icons

Screenshot - Broken Version
![image](https://user-images.githubusercontent.com/6919352/156573840-f6cb5374-7581-439d-9dd9-a683025593de.png)

Screenshot - Expected (Version 5)
![image](https://user-images.githubusercontent.com/6919352/156573912-8d22b650-21c7-438e-8273-de06c7658e5a.png)

**Comment by robmadole** [comment]
Hey @gluecksmensch. Does this answer your question? https://fontawesome.com/docs/web/setup/upgrade/scss-less#breaking-changes

**Comment by jacknkandy** [comment]
@robmadole thanks for the link, this did it for me, in my main scss file:

`
@import '~@fortawesome/fontawesome-pro/scss/duotone-icons';
`
