### ISSUE TITLE
Icon request: pilot-wings

### ISSUE THREAD

**Issue by eric-norcross** [FortAwesome/Font-Awesome#18581]
**What can it be used for?**
In general there aren't many aviation industry themed icons, but in general this could be used as a type of award, or an indicator for aviation-related menu options.

**Example image (optional)**
[Example "Pilot Wings" from ShutterStock](https://image.shutterstock.com/image-vector/aviation-emblems-badges-logo-patches-600w-396474760.jpg)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

FA6 Pro comes with two icons that could fit the use case:
- https://fontawesome.com/icons/user-pilot?s=solid
- https://fontawesome.com/icons/user-pilot-tie?s=solid

Do they work?
