### ISSUE TITLE
v6.0 Website Search Bar Very Slow / Glitchy

### ISSUE THREAD

**Issue by MitchTalmadge** [FortAwesome/Font-Awesome#18584]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

On https://fontawesome.com/v6.0/icons?s=solid%2Cbrands the search bar acts very glitchy and slow, often erasing part of what I am typing. 

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

1. Visit https://fontawesome.com/v6.0/icons?s=solid%2Cbrands
2. Type something into the search bar.
3. Notice how it deletes random parts of what you type, and is slow in general.

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
How would you like this to work instead?

Should be quick and not mess up my input.

**Screenshots**

![](https://i.imgur.com/0nvpDgS.gif)

Here I type "Hello World this is a test of the search bar." and then the alphabet.

**Version and implementation**
Version:  6.0
Browser and version:  Chrome 97.0.4692.71 64 Bit

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop
- [x] On the Website

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Thanks @MitchTalmadge we've had a few other reports about this too. We'll get it looked at!

**Comment by robmadole** [comment]
Ok. I think we've got this fixed. @MitchTalmadge if you have time to check we'd appreciate that.

**Comment by MitchTalmadge** [comment]
@robmadole It is working great now, I appreciate it!
