### ISSUE TITLE
Missing Tripadvisor icon in Fontawsome 5.15.4

### ISSUE THREAD

**Issue by CallMeDams** [FortAwesome/Font-Awesome#18590]
Hi,

I am actually upgrading a website which uses an old version of FA with the FA 5 version.

The Tripadvisor icon is missing in the last 5 version.

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately this is correct, Trip Advisor asked to remove their logo from the set

Please refer to the pinned issue #18180

Closing here

**Comment by CallMeDams** [comment]
Thanks for the quick answer
