### ISSUE TITLE
Icon request: icon-name (P+, P-, P edit, P clone)

### ISSUE THREAD

**Issue by hakkinepally** [FortAwesome/Font-Awesome#18591]
Hi,

I see, currently Product (P) icon already exists today.
Can you please add P+ (Product Add), P- (Remove Product), Product Edit and Product Clone.

Thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Product (P) icon already exists today.

`P` may be used to represent a Product for some languages, but it is not specifically related to a real object: it is just the letter "P"

This request may lead to the whole combination of LETTERS * [+, -, edit, clone] * [solid, regular, light, thin, duotone], so it may include hundreds of variations.

I would consider this class of requests out of scope for the moment

Also, **in a web application**, it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/0adgjefp/2/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

@sensibleworld what do you think of this class of requests?

**Comment by sensibleworld** [comment]
Yeah, adding +/-/etc to icons is a slippery slope. There are certainly cases where having variants are important, but in general I think we'll only consider them if they have a lot of community support, or have a proven need. I don't really see P+, P-, etc as commonly used metaphors to reference "Product" though. 

Are you referring to the Product Hunt brand logo? https://staging.fontawesome.com/icons/product-hunt?s=brands

If so, that's a protected mark and meant to be used only when referencing the company Product Hunt itself.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
