### ISSUE TITLE
Icon request: image-plus

### ISSUE THREAD

**Issue by LarsFlieger** [FortAwesome/Font-Awesome#18602]
**What can it be used for?**
If you upload an image it would be great to have an icon for it. Could be used for all image uploads in general. 

**Example image (optional)**
![image](https://user-images.githubusercontent.com/47084064/150646422-52b49358-1a7e-4cc2-b801-9f146041bfe0.png)
![image](https://user-images.githubusercontent.com/47084064/150646453-66d5ba5e-c3df-4843-8229-7001e67c1ae5.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/609/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by LarsFlieger** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.
> 
> Demo: https://jsfiddle.net/tagliala/L17f528g/609/
> 
> Ref:
> 
> https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms https://fontawesome.com/how-to-use/on-the-web/styling/masking https://fontawesome.com/how-to-use/on-the-web/styling/layering

That's nice to see! Thanks for the tip! This will solve my issue. However why are some icons which are quite easy to build than an own icon? For example: https://fontawesome.com/v5.15/icons/smile-plus?style=solid

What are the reasons for an own icon?

**Comment by tagliala** [comment]
Hi, welcome

> What are the reasons for an own icon?

It depends on many things:
- SVG layering is not available for every use case, so you may want to have plus variation in a single glyph
- Some icons like `user-plus` have been implemented in FA4, when the SVG advanced features were not available
- Other icons like `folder-plus` have enough requests to have their own glyph #1525
- Some icons have been sponsored, and this is the case of `smile-plus`. You can check if an icon has been sponsored in the docs

![image](https://user-images.githubusercontent.com/556268/150651021-3ecc9169-0e45-4ab3-95dc-73f8253b92de.png)

Hope this clarifies

**Comment by sensibleworld** [comment]
I'll also note that we're not against adding variations on icons, as needed. In the case of this particular request, I can definitely see the benefit :) I'm adding it to my list.

**Comment by LarsFlieger** [comment]
> I'll also note that we're not against adding variations on icons, as needed. In the case of this particular request, I can definitely see the benefit :) I'm adding it to my list.

That's nice to hear! Yes, I think this icon is quite common for uploading images :)
