### ISSUE TITLE
Missing Metadata folder (FA 6.0.0 Beta 3 Pro)

### ISSUE THREAD

**Issue by bwakabats** [FortAwesome/Font-Awesome#18608]
**Describe the bug**
The metadata folder is missing from the pro download.
Is this intentional?

**To Reproduce**
Look in the zip file :)

**Expected behavior**
You should see the folder :)

**Screenshots**
N/A

**Version and implementation**
Version: 6.0.0 Beta 3 Pro
Browser and version: N/A

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

yes, this is intentional

More details at FortAwesome/Font-Awesome-Pro#1577, feel free to provide your thoughts there

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by bwakabats** [comment]
> FortAwesome/Font-Awesome-Pro#1577
Sorry, what does this mean?
Many thanks.

**Comment by tagliala** [comment]
> Sorry, what does this mean?

Please follow the link with the discussion

As a Font Awesome customer, you should be able to access the Pro repository when this removal is being discussed

If you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

**Comment by sensibleworld** [comment]
@bwakabats Wanted to give a quick update that, as of our [6.3.0 release](https://fontawesome.com/docs/changelog/), we've added back the search terms to our metadata files, where they'll stay. Apologies for the poor communication and frustration we caused around this matter.
