### ISSUE TITLE
Use of FontAwesome in Visio (2013)

### ISSUE THREAD

**Issue by sbelyea** [FortAwesome/Font-Awesome#1860]
I'm currently unable to use FontAwesome in Visio.  Partly due to how Visio 2013 doesn't support .otf, but that's not the entire story.  Even installing and attempting to use the .ttf results in Visio not recognizing the characters and displaying boxes with question marks inside of them.

![image](https://f.cloud.github.com/assets/1383728/1037343/a50b5c52-0f4d-11e3-8d54-dc6bd8e86b67.png)

**Comment by alphabase** [comment]
Experiencing the same, really interested in a solution. Selecting font doesn't work, jumps right back to default font. Copy paste from cheatsheet doesn't work either. Using FA 4.3.0.

**Comment by tagliala** [comment]
Sorry, I can't help

**Comment by kerry-chin** [comment]
Visio stopped supporting the OTF font format starting at Visio 2003.  Visio will only see TTF fonts.  I tried converting FA 4.3.0 via an online converter, but it didn't work.  I also tried using the webfont TTF file, and it still didn't work.  There is probably something malformed about the original file.  I know that FontForge thinks there are some errors in it.  As jimlamb commented above, the Ligature Symbols font works, so maybe check out its file structure?

**Comment by tagliala** [comment]
@kerry-chin could you please try conversion via font squirrel at http://www.fontsquirrel.com/tools/webfont-generator having care to set "subsetting" to "no subsetting"?

**Comment by kerry-chin** [comment]
@tagliala :  Unfortunately, the Font Squirrel version did not work.  There were a lot of other settings for the conversion.  Maybe I will try changing one or two of the other settings, and I will try again.

**Comment by tagliala** [comment]
@kerry-chin thanks. Let us know

**Comment by jamesoliverband** [comment]
I am having the exact same problem with the 4.4.0 version. anyone who go it running?

**Comment by lgm42** [comment]
+1

**Comment by konalion** [comment]
+1

**Comment by tagliala** [comment]
Please do not +1. If you know how to fix this, please help

**Comment by konalion** [comment]
I used +1 to indicate that the problem still exists for me.  As I'm sure the poster before me, that was also deleted, was using it for the same reason.  Given the vast amount of time since this issue was opened, it appears that more people need to post that it's an issue for them, so that maybe someone knowledgeable and capable will make it a priority to solve.

**Comment by tagliala** [comment]
you can use github reactions

![image](https://cloud.githubusercontent.com/assets/556268/15156739/b427281a-16e8-11e6-857b-afd3b32d8c49.png)

**Comment by konalion** [comment]
Although I'm not a font developer, I'm hoping the following information might be useful to someone that is.

Microsoft provides some font developer tools ([https://www.microsoft.com/en-us/Typography/DevToolsOverview.aspx]), one which is called Font Validator.  I ran it against fontawesome-webfont_0.ttf and have attached the output in a PDF file.  There are several Warnings and Errors, which I suspect may be contributing to the Visio issue.  I've also included PDF files for the Error, Warning and Informational messages from Font Validator.

Again, I hope this information is helpful to a knowledgeable and capable font developer that might be able to resolve this issue.

[fontawesome-webfont.ttf MS Font Validator Report (051016).pdf](https://github.com/FortAwesome/Font-Awesome/files/258164/fontawesome-webfont.ttf.MS.Font.Validator.Report.051016.pdf)
[MS Font Validator - Error Messages (051016).pdf](https://github.com/FortAwesome/Font-Awesome/files/258165/MS.Font.Validator.-.Error.Messages.051016.pdf)
[MS Font Validator - Warning Messages (051016).pdf](https://github.com/FortAwesome/Font-Awesome/files/258178/MS.Font.Validator.-.Warning.Messages.051016.pdf)
[MS Font Validator - Informational Messages (051016).pdf](https://github.com/FortAwesome/Font-Awesome/files/258180/MS.Font.Validator.-.Informational.Messages.051016.pdf)

**Comment by tagliala** [comment]
@konalion thanks

as I said before, ttf font is generated by [Font Squirrel Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator), so we need to know if it possible to fix the `.otf`. I've seen that the `.otf` contains much less errors than the `.ttf`, so you can play with fontsquirrel setup in an attempt to provide a working file

**Comment by mac-bhaird** [comment]
Also experiencing the same problem with 4.7 and Visio 2016

**Comment by tagliala** [comment]
@mac-bhaird could you please check with FA 5.0 ?

Please install fonts under the `/use_on_desktop` folder

**Comment by mac-bhaird** [comment]
@tagliala Tried this using Visio 2016 and 5.11.2-desktop, still no luck :(

**Comment by tagliala** [comment]
@mac-bhaird 
 
Does Visio 2016 support OTF format?

If it does, please try OTF format. If OTF format doesn't work, please try Font Awesome OTF 5.6.3 and let me know. Please remember to set bold font style for solid style icons

**Comment by sensibleworld** [comment]
We have a related update in the works that _might_ fix this issue. I'll try to keep this thread updated as we move forward with it. Plan is to release with version 5.12.0

**Comment by sensibleworld** [comment]
With version 6, we've changed how we write our font files. Could someone on this thread try using one of the latest releases to see if this continues to be a problem? https://fontawesome.com/download

**Comment by thekingofspain** [comment]
I was able use the fonts in fontawesome-free-6.0.0-beta2-desktop without issue in Visio 2016 Professional.  This was not case when attempting to use FontAwesome 4.7.0. fonts.
