### ISSUE TITLE
New icon request: dance

### ISSUE THREAD

**Issue by kiranaida** [FortAwesome/Font-Awesome#18615]
Would love to see you guys add an icon related to dance! I searched for a bunch of different terms and clicked through all the categories but didn't find anything. The closest thing seems to be the running/walking icons.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request can be a duplicate of #8254 or #1082 or #7563, or [others](https://github.com/FortAwesome/Font-Awesome/search?q=dance&state=open&type=issues)

Feel free to upvote by using 👍🏼 reaction on the opening post of the request you are looking for (or all of them)

Closing here
