### ISSUE TITLE
Icon request: clapperboard

### ISSUE THREAD

**Issue by CaveMobster** [FortAwesome/Font-Awesome#18614]
**What can it be used for?**
In my specific case I want something that indicates one or multiple events happening as a result of clicking a button.
It could also be used in a more literal sense: in movie/theatre related environments, or in video/stream editing/recording software.

**Example image (optional)**
[Example](https://iconscout.com/icon/clapperboard-2233711)

**Icon request checklist**
- [x] This is a single icon
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

A clapperboard icon will be available in FA6 Free
- https://fontawesome.com/v6.0/icons/clapperboard?s=solid

FA6 is in beta and can be used today: https://fontawesome.com/v6.0/docs/web/setup/quick-start/

The ETA for the stable release is in February 2022

Hope it helps

Closing here but feel free to comment
