### ISSUE TITLE
Icon request: engine

### ISSUE THREAD

**Issue by ezejde** [FortAwesome/Font-Awesome#18610]
**What can it be used for?**
I'm writing a blog post on seo. I was looking through the mountain of spectacular icons, but I couldn't find anything that looked like an engine/machine (I was going to use the magnifying glass, then engine to signify SEO). This icon could be great for signifying mechanical parts, inner workings, and of course, engines.

**Example image (optional)**
Search 'engine illustration' on google. Simpler version of those.

**Icon request checklist**
Request cheks all the boxes

**Comment by sensibleworld** [comment]
Hi there! We have a new engine icon in version 6: https://fontawesome.com/v6.0/icons/engine?s=solid
