### ISSUE TITLE
Types missing for import.macro in svg-core

### ISSUE THREAD

**Issue by Pearce-Ropion** [FortAwesome/Font-Awesome#18616]
**Describe the bug**
The type definitions for the `import.macro` in `@fortawesome/fontawesome-svg-core` is missing.
This makes it difficult to get types, auto-completion, etc for the import macros. 

**To Reproduce**

In a local environment:
```
npm install @fortawesome/fontawesome-svg-core@1.3.0-beta3 -E
//
yarn add @fortawesome/fontawesome-svg-core@1.3.0-beta3
```

Open the `node_modules` directory and navigate to `@fortawesome/fontawesome-svg-core` directory. No declaration files exist

**Expected behavior**
Typescript declarations should exist

**Screenshots**
![Screen Shot 2022-01-27 at 2 56 57 PM](https://user-images.githubusercontent.com/32177944/151457146-723f7df7-6875-4c0b-8383-99d8f63b1680.png)

**Version and implementation**
Version: 1.3.0-beta3
Browser and version: N/A

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [x] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by Pearce-Ropion** [comment]
This is what I am using as a workaround for now
```typescript
// typings/fontawesome-svg-core.d.ts
declare module '@fortawesome/fontawesome-svg-core/import.macro' {
    import {
        IconDefinition,
        IconName,
    } from '@fortawesome/fontawesome-svg-core';

    function brands(iconName: IconName): IconDefinition;
    function duotone(iconName: IconName): IconDefinition;
    function light(iconName: IconName): IconDefinition;
    function regular(iconName: IconName): IconDefinition;
    function solid(iconName: IconName): IconDefinition;
    function thin(iconName: IconName): IconDefinition;
}
```

**Comment by DevSlashRichie** [comment]
Is this related to this? 
![image](https://user-images.githubusercontent.com/8129679/154755633-970ce095-36a5-4fbb-aa93-9babfc4ca7be.png)

**Comment by Pearce-Ropion** [comment]
> Is this related to this? 
> 
> ![image](https://user-images.githubusercontent.com/8129679/154755633-970ce095-36a5-4fbb-aa93-9babfc4ca7be.png)
> 
> 

That looks completely unrelated to even fontawesome. If you are sure it's a fontawesome issue, I'd recommend making a separate issue with more detailed information about your environment/setup/what you are trying to do.

**Comment by DevSlashRichie** [comment]
> > Is this related to this?
> > ![image](https://user-images.githubusercontent.com/8129679/154755633-970ce095-36a5-4fbb-aa93-9babfc4ca7be.png)
> 
> That looks completely unrelated to even fontawesome. If you are sure it's a fontawesome issue, I'd recommend making a separate issue with more detailed information about your environment/setup/what you are trying to do.

Cool thanks. I removed the `macro.import` and the error disappeared.

**Comment by Pearce-Ropion** [comment]
> > > Is this related to this?
> 
> > > ![image](https://user-images.githubusercontent.com/8129679/154755633-970ce095-36a5-4fbb-aa93-9babfc4ca7be.png)
> 
> > 
> 
> > That looks completely unrelated to even fontawesome. If you are sure it's a fontawesome issue, I'd recommend making a separate issue with more detailed information about your environment/setup/what you are trying to do.
> 
> 
> 
> Cool thanks. I removed the `macro.import` and the error disappeared. 

It might be related to your babel macros setup. But this issue is more about the typings for the macro's functions, not the function's not working themselves

**Comment by Meierschlumpf** [comment]
> This is what I am using as a workaround for now

To add this you can add a global.d.ts file in the src-directory of your React project and paste that in

**Comment by esetnik** [comment]
Will this be fixed in v6.1.0?

**Comment by robmadole** [comment]
@esetnik this fix is not available in 6.1.0

**Comment by craighutch** [comment]
There was a similar issue a while back with the `styles.css` file being missing from this package (#18360).  I don't know if the same solution for that would be applicable to the typings or not.

**Comment by robmadole** [comment]
We just released 6.1.1 which should fix this up. Can anyone give it a try?

**Comment by craighutch** [comment]
@robmadole I installed 6.1.1 and I see the `import.macro.d.ts` file is present now.  Thanks!

**Comment by robmadole** [comment]
thanks @kb3eua !
