### ISSUE TITLE
Icon ( Eye - Light ) Issue

### ISSUE THREAD

**Issue by Marvv90** [FortAwesome/Font-Awesome#18629]
Dear Font-Awesome Team,

I have a Display Issue with the Icon. The Little Eyeball be missing.

**Version and implementation**
Version: 6 PRO  ( CDN & Local File Download ) 

Browser and version: Firefox 96.0.3 / Chrome 97.0.4692.99 / Safari 15.2 on OS X

- [ ] SVG with JS
- [X] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

![Bildschirmfoto 2022-02-01 um 19 17 55](https://user-images.githubusercontent.com/25277416/152027206-08d03633-ebed-487f-9a64-5502823ef728.png)
![Bildschirmfoto 2022-02-01 um 19 17 46](https://user-images.githubusercontent.com/25277416/152027207-6c3f8e3f-68b9-4e9a-9be1-2f08eaf26336.png)
![Bildschirmfoto 2022-02-01 um 19 22 06](https://user-images.githubusercontent.com/25277416/152027749-362a0130-abee-4915-8c38-479cf2b6085c.png)
![Bildschirmfoto 2022-02-01 um 19 21 48](https://user-images.githubusercontent.com/25277416/152027754-a79dcd23-96a5-41ad-941b-f79e6f24d6d6.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that your kit is using FA6, so you should check FA6 icons: https://fontawesome.com/v6.0/icons/eye?s=light

You can change your kit settings to use FA5 here: https://fontawesome.com/kits

**Comment by Marvv90** [comment]
sorry, I'm embarrassed now you're right!

**Comment by tagliala** [comment]
No problem, glad you've solved 👍🏼
