### ISSUE TITLE
Missing icons on mobile website

### ISSUE THREAD

**Issue by lukaszeich** [FortAwesome/Font-Awesome#18628]
Hello,
I have weird situation with displaying some icons on mobile website. The same website, wit the same icons on PC is displayed well, but on mobile phone I don't see the icons - have the same website on two different url's and have different view. Below You can find 4 screenshots - two of them are from my smartphone and next two are from my PC. Additionally on each screen You have URL. 

leich.herokuapp.com - desktop OK, phone I see nothing
probe-app.herokuapp.com - desktop OK, phone: some icons OK, some don'd displaying properly.

Can someone help me with this case? 
Using lastest version of fontawesome. 

![Screenshot_20220201-121919](https://user-images.githubusercontent.com/96284738/151959736-e21bc19d-0c16-4b95-8cfa-25069d55bed1.png)
![Screenshot_20220201-121928](https://user-images.githubusercontent.com/96284738/151959759-a4144c57-be2c-472c-9403-311f7e9ef041.png)
![probe_desktop](https://user-images.githubusercontent.com/96284738/151959910-76029816-580c-4fd0-91d0-da9c02576e12.JPG)
![leich_desktop](https://user-images.githubusercontent.com/96284738/151959939-ae6af031-d72d-4bdc-87fc-77c3d15322eb.JPG)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I cannot replicate

I've noticed that the mobile has an issue with the certificate, and that could prevent the resource to be fetched

![image](https://user-images.githubusercontent.com/556268/151961788-58dbfcf4-2784-442e-a0cd-e8618e14e149.png)

Could you please ~check why~ try on https?

**Comment by lukaszeich** [comment]
Tried with HTTPS (screens below). 
If on Your phone it looks good (please confirm) maybe I have problem with my phone.  I will ask someone to check it on different hardware. 

![Screenshot_20220201-124436](https://user-images.githubusercontent.com/96284738/151963213-88b039e3-e52f-45d5-970f-8df6cd5a2993.png)
![Screenshot_20220201-124441](https://user-images.githubusercontent.com/96284738/151963224-43b5e299-80a9-417f-a2f5-af1402343a60.png)

**Comment by tagliala** [comment]
> If on Your phone it looks good (please confirm)

I can confirm it looks fine on iOS 15 / iPhone 12 Pro

**Comment by lukaszeich** [comment]
OK, I have checked on Win10 mobile and it's look great - can anyone check it on Android mobile?

**Comment by tagliala** [comment]
Could you please provide information about the phone causing issues, like manufacturer, OS, version, browser, browser version?

**Comment by lukaszeich** [comment]
LG K42 with Android OS
Android version: 11
Software version: V20a-EEA-XX

Browser: Google Chrome Mobile 
Browser version: 97.0.4692.98

**Comment by tagliala** [comment]
Closing here for the moment, but feel free to comment and if there is an issue with a specific kit or a Font Awesome feature I will reopen
