### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by Weh-gh** [FortAwesome/Font-Awesome#18620]
Hello, FontAwesome

I searched for the icon named "TypeScript" in FontAwesome, but no icon was found. Why is this icon missing?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There is a request for Typescript at #11890, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
