### ISSUE TITLE
Icon Request: fa-thought-bubble and fa-thought-bubble-o

### ISSUE THREAD

**Issue by Supuhstar** [FortAwesome/Font-Awesome#1863]
We have speech bubbles, but why not thought bubbles? Seems simple enough.

Something like this, which I modified from [one](http://thenounproject.com/term/thought-bubble/49763/) by [Adriano Emerick](http://thenounproject.com/esteves_emerick):

![Kyli's thought bubbles based on Adriano Emerick's](https://cloud.githubusercontent.com/assets/1350020/5092771/b7f4c8ac-6f1f-11e4-9d9d-1553e0fac085.png)

**Comment by MathewBoyles** [comment]
+1

**Comment by ckpicker** [comment]
+1

**Comment by TALlama** [comment]
+1

**Comment by shaunakay** [comment]
+1

**Comment by Saevon** [comment]
+1 This would be great when posting "thoughts"

**Comment by Supuhstar** [comment]
@Saevon or when you have an "Thoughts & Opinions" button or something to let people submit feedback!

**Comment by QueenMerla** [comment]
+1

**Comment by loremipsumdolor** [comment]
+1

**Comment by sodiumlights** [comment]
+1

**Comment by rachelreveley** [comment]
:+1:

**Comment by nielsvanrijn** [comment]
👍🏻

**Comment by atempel** [comment]
👍🏻

**Comment by pegarm** [comment]
+1

**Comment by ouarez** [comment]
+1

there are millions of "normal" bubbles for comments etc. but none for thoughts!

It's been seven years, please consider throwing this one in on the next round :)

I'll be happy to pay for coffee!

**Comment by seanreiser** [comment]
+1

**Comment by TangentFoxy** [comment]
+1 Would be very much appreciated!

**Comment by tbrazel** [comment]
+1 Just tried to find a thought bubble on FA and was surprised not to find one! Would definitely use if implemented :)

**Comment by sensibleworld** [comment]
<img width="590" alt="Screen Shot 2021-03-30 at 12 30 25 PM" src="https://user-images.githubusercontent.com/529604/113023521-b6326080-9153-11eb-85dd-c8c0cca93849.png">

This is available in the latest alpha release of Font Awesome v6: http://fontawesome.com/download
