### ISSUE TITLE
Font Awesome icons will not show on Squarespace

### ISSUE THREAD

**Issue by whatever1000** [FortAwesome/Font-Awesome#18632]
On a Squarespace site, I added the icon library to the Custom CSS and a couple of simple icons in a code block on a page.

I have a free account, the two icons are free versions and i didn't change the HTML at all - no customizations or anything. I even took out the link reference so it's just the icon html in the code block. 

And...nothing.  Doesn't show at all. 

Went through all the troubleshooting steps on the FA site and everything looks as it should.  No typos, no changes, no pro icons, nothing that's any different than the very basic steps to put an icon on a web page. 

Not including a test case because i'd just be showing a blank space on a webpage.   The basic function just doesn't work. 

Any ideas ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Not including a test case because i'd just be showing a blank space on a webpage. The basic function just doesn't work.

Please do :)

**Comment by whatever1000** [comment]
![Screen Shot 2022-02-01 at 4 50 03 PM](https://user-images.githubusercontent.com/98851876/152057349-541afa64-2a6a-4991-a480-4e24ff66ccc9.png)

**Comment by whatever1000** [comment]
As i said, there's just a blank page, not rendering at all

here's the code box:
![Screen Shot 2022-02-01 at 4 52 26 PM](https://user-images.githubusercontent.com/98851876/152057618-c93fe062-560f-40f3-9159-d45ffc6e4cf4.png)

**Comment by whatever1000** [comment]
so that code box is on the page with two very basic icons and the icon library is in the Custom CSS.  it should work right ?

**Comment by tagliala** [comment]
Hi, apologies but I meant a reproducible test case

Of course a screenshot does not help in this case, but a reduced test case or the actual website experiencing the issue would

**Comment by whatever1000** [comment]
i'm not sure how to show you that.  the website isn't published yet otherwise, i'd give you the URL.   

as I said, all i've done is add the HTML to a code box on that page and add the icon library to the CSS.   Is there anything else i'm supposed to do ?   it's the most basic function of FA, nothing special at all and i've copied the HTML direct from the FA site with no alterations at all.

**Comment by tagliala** [comment]
Sorry but it is hard to debug without details

We have a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) that could help you in providing us the information we need to confirm an issue.

You can see the minimum code required to run Font Awesome here: https://jsfiddle.net/tagliala/7fc628ks/1/ (approach: CSS / Third Party CDN)

**Comment by tagliala** [comment]
#18634
