### ISSUE TITLE
Basic icons not showing on Squarespace webpage 

### ISSUE THREAD

**Issue by whatever1000** [FortAwesome/Font-Awesome#18634]
**Describe the bug**
What happened? What are you seeing? How did you arrive here?

What happened is i entered the HTML in the code box and the Icon Library in the CSS and nothing happened.  It doesn't show anything.

**To Reproduce**
Insert a URL to your test case - use codepen.io, jsfiddle.net, jsbin.com, codesandbox.io, or whatever.

the site is not published yet but all you would see is a blank space where the icons should appear. 

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

there's no test case to show other than the HTML i put in the Custom CSS and in the code box on that page.
Icon Library:  @import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css');
Code box HTML:  <i class="fab fa-linkedin></i></a>
<i class="far fa-envelope"></i></a>

**Expected behavior**
How would you like this to work instead?

I would like the two icons i put in the box to show up on the webpage.

**Screenshots**

![Screen Shot 2022-02-01 at 5 34 15 PM](https://user-images.githubusercontent.com/98851876/152062942-821be21b-2fa0-4cfb-ac5f-e94e8b7f3227.png)
![Screen Shot 2022-02-01 at 5 36 07 PM](https://user-images.githubusercontent.com/98851876/152063149-7033b6cd-1330-4444-ac3c-8c4b8b98be2e.png)

**Version and implementation**
Version:   latest 5.x
Browser and version:   Safari  Version 15.2 (16612.3.6.1.8, 16612)

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [X ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi, 

sorry, cannot replicate: https://jsfiddle.net/tagliala/jwhao48q/

Could you please check your development console if there are errors?

**Comment by sensibleworld** [comment]
@whatever1000 I just made a test Squarespace site to see if I could get things to work, and was only successful after making sure to add a kit code to the main header in the site.

You'll want to start by creating a Free kit here: https://fontawesome.com/start

Once you get your unique kit code, you'll want to add it to the header of your Squarespace site. In Squarepsace, visit: Settings > Advanced > Code Injection > Copy kit code into the "Header" section.

<img width="767" alt="CleanShot 2022-02-11 at 13 30 45@2x" src="https://user-images.githubusercontent.com/529604/153649135-e1fd4af4-27b1-44dd-adad-fe93de8fbd9f.png">

**Comment by whatever1000** [comment]
thanks Jory. 

I figured it out with the same solution.  using the kit fixed it.

appreciate the update !
