### ISSUE TITLE
Icon request: circle-slash

### ISSUE THREAD

**Issue by JacobDB** [FortAwesome/Font-Awesome#18630]
**What can it be used for?**
Similar to the `smoking-ban` icon, having a single `circle-slash` that can be layered with other icons to create `$icon-ban` variants would be extremely useful.

**Example image (optional)**

On its own:

![image](https://user-images.githubusercontent.com/1123997/152039010-c2dcb7f5-c795-434d-bed9-e09871c96cea.png)

Merged with another icon ("no dogs allowed"):

![image](https://user-images.githubusercontent.com/1123997/152038951-74e6c597-180e-4dec-9b52-433a97411418.png)

**Icon request checklist**
- [x] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [x] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [x] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by tagliala** [comment]
Hi!

This icon is available as [fa-ban](https://fontawesome.com/v5.15/icons/ban?style=solid)

**Comment by JacobDB** [comment]
Ah! I *knew* it had to be *somewhere*, but I was so fixated on `circle-slash`. Thanks!
