### ISSUE TITLE
Tripadvisor icon missing?

### ISSUE THREAD

**Issue by MWaterreus84** [FortAwesome/Font-Awesome#18636]
Dear fontAwesome,
I've used your icons for a couple of years now but this week I notised that the Tripadvisor icon changed to a standard airplane. So I've searched your libarary for the original brand icon but couldn't find it anymore. Can you please bring it back?
Thanks in advance.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the inconvenience.

> Can you please bring it back?

Unfortunately we can't. Trip Advisor icon has been removed by request of the copyright holder

More information on the pinned issue #18180

Closing here
