### ISSUE TITLE
Issue with fas fa-air-freshener

### ISSUE THREAD

**Issue by loizosVas** [FortAwesome/Font-Awesome#18640]
I'm working with GeoDirectory plugin in Wordpress and found an issue with one of the icons. This plugin allows me to create categories for map locations, for example Shops in Brazil could be categorized as restaurants, gyms, beauty care, etc.

For each map location I can upload a fas icon to be using in both category name and pinpoint on the map.

When I use the fas fa-air-freshener icon it will take it for the category name but for the pinpoint it will change it to something else. Can you please check for any bugs in your end??

See screenshot: [here](https://paste.pics/8d63f2e2e371159d3686c8179899533c)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The air freshener icon has been redesigned by request of the trademark owner in version 5.15.3: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5153---2021-03-16

You may want to check if there are conflicts in versions.

![image](https://user-images.githubusercontent.com/556268/152307420-9d044597-b1d4-4904-8958-da8dbde2beaa.png)

I do not recognize this icon

Closing here, but feel free to comment
