### ISSUE TITLE
enhancement: fa-spin-ccw

### ISSUE THREAD

**Issue by brimwd** [FortAwesome/Font-Awesome#18645]
`fa-spin` only rotates clockwise, but some icons (like `fa-fan` and `fa-hurricane`) should spin CCW based on the orientation of the icons.

Can you add a fa-spin-ccw class to rotate the icons in the opposite direction?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`spin-reverse` will be available in FA6 and is available in FA6 beta

Please take a look at my comment here: https://github.com/FortAwesome/Font-Awesome/issues/688#issuecomment-1030584164
