### ISSUE TITLE
fa-chrome icon update

### ISSUE THREAD

**Issue by x-rated** [FortAwesome/Font-Awesome#18647]
**Describe the bug**
Slightly changed icon after 8 years https://9to5google.com/2022/02/04/google-chrome-icon-update/, now without triangular shadow and with bigger circle, should look like this now:
![new-chrome](https://user-images.githubusercontent.com/16560025/152675454-c4c16286-2b2b-428f-8c12-80e93301883e.svg)

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this. Same as the other request, I will track this internally

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/chrome?s=&f=brands
