### ISSUE TITLE
The link in 6.0.0 release notes returns 404 error

### ISSUE THREAD

**Issue by slaweet** [FortAwesome/Font-Awesome#18653]
The release notes in https://github.com/FortAwesome/Font-Awesome/releases/6.0.0 say

> Change log available at https://fontawesome.com/docs/changelog/

but the linked page is a 404:

![fontawesome-6-release-log](https://user-images.githubusercontent.com/1254342/152944671-fe92436c-f0a2-4473-b0b2-ee88d9f20190.gif)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

FA6 has not been deployed yet on fontawesome.com, AFAIK it will be done today

**Comment by sensibleworld** [comment]
Yup! Check back in a few hours. We had to get everything fully released here before updating the website.
