### ISSUE TITLE
FA 6 with vuejs 2 is causing a javascript error

### ISSUE THREAD

**Issue by craiggeil** [FortAwesome/Font-Awesome#18667]
I'm using vuejs 2 and FA 5.15 without any issues. I tried going to FA 6 yesterday but kept getting the following error --
TypeError: Cannot read properties of undefined (reading 'prefix')

I checked the docs and there's nothing that I could find that changed with this version upgrade. Has anyone else had any issues with upgrading to FA 6 using vuejs?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have a recent unconfirmed bug report about vue at FortAwesome/vue-fontawesome#363

Don't know if it is the same thing

**Comment by craiggeil** [comment]
Not really. That has to do with a vuejs 3 update. I'm using vuejs 2 which should keep working. As long as there weren't any breaking changes between v5.15 and v6?

**Comment by kelseythejackson** [comment]
Hey @craiggeil, have you checked your imports?
https://fontawesome.com/docs/web/use-with/vue/add-icons#set-up-the-library

**Comment by craiggeil** [comment]
> Hey @craiggeil, have you checked your imports? https://fontawesome.com/docs/web/use-with/vue/add-icons#set-up-the-library

Yes I did, even double checked. Like I said nothing has changed between v5.15 and v6, it should work with the code as is.

**Comment by craiggeil** [comment]
I might need to create a quick code example showing this failure so everyone can see it.

**Comment by kelseythejackson** [comment]
Yes, that would be awesome. Thanks

**Comment by craiggeil** [comment]
Here is a codesandbox example -- https://codesandbox.io/s/gallant-snow-tv1qk?file=/src/App.vue
Right now it's set to FA v5.15 and the example works. However if you switch it to v6 it fails.

**Comment by kelseythejackson** [comment]
Hey @craiggeil, codesandbox was unresponsive, but I was able to rebuild your sample locally and it worked fine. Did you imort Font Awesome in you main.ts file?

**Comment by kelseythejackson** [comment]
@craiggeil I pushed what I built if you want to check it out: https://github.com/kelseythejackson/fa-test

**Comment by craiggeil** [comment]
@kelseythejackson Thank you! Let me play with it this weekend and see if I can replicate my issue.

**Comment by craiggeil** [comment]
@kelseythejackson I was unable to make your project fail like the project I am working on. Let me try a few more things to find out what is going on in my project. Thanks.

**Comment by kelseythejackson** [comment]
@craiggeil good deal. I'm gonna close this issue out. If you're still having trouble, feel free to open a new issue and tag me on it. Thanks
