### ISSUE TITLE
FA 6.0.0 with Nuxt: FA css is missing after build

### ISSUE THREAD

**Issue by designchapnl** [FortAwesome/Font-Awesome#18666]
I'm using Vue with Nuxt. During developing all icons look fine. After build, Font Awesome css is missing and so all icons are not sized.

I've set up like the docs and tested it by using Nuxt wrapper. Both give same result.

Here are 2 screenshots:
<img width="199" alt="Schermafbeelding 2022-02-09 om 15 31 42" src="https://user-images.githubusercontent.com/29886711/153222111-4afb1e0a-e749-4090-b89c-4f803e1aa32f.png">

<img width="632" alt="Schermafbeelding 2022-02-09 om 15 31 00" src="https://user-images.githubusercontent.com/29886711/153221999-92018ada-03e0-4843-9bb3-a75bd0643d3d.png">

Version: 6.0.0
Browser and version: every latest browser

- [x] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
maybe related to #18654

**Comment by nevil2** [comment]
Also had icons disappear when building with docker.  Locked versions to 1.2.36 / 5.15.3 to resolve.

**Comment by tchiteu** [comment]
In my case (I don't use the latest version of font awesome) I solved the problem by installing [@fortawesome-svg-core](https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core) 1.2.36.

**Comment by andre-lergier** [comment]
I had the same problem with my Nuxt.js application only in production mode.
Adding `@import '@fortawesome/fontawesome-svg-core/styles.css';` on top of my main SCSS file fixed it.

**Comment by BibekStha** [comment]
> I had the same problem with my Nuxt.js application only in production mode. Adding `@import '@fortawesome/fontawesome-svg-core/styles.css';` on top of my main SCSS file fixed it.

This workaround worked for me on Nuxt

**Comment by designchapnl** [comment]
It was resolved for me in 6.1

**Comment by wesdevpro** [comment]
Why does this workaround work? and has anyone identified the actual problem?

**Comment by Qa5imm** [comment]
> I had the same problem with my Nuxt.js application only in production mode. Adding `@import '@fortawesome/fontawesome-svg-core/styles.css';` on top of my main SCSS file fixed it.

hello,
I am new to nuxt, can you please let me know which scss file are you talking about ?
