### ISSUE TITLE
Using a Package Manager Documentation References Beta 3

### ISSUE THREAD

**Issue by Jas-n** [FortAwesome/Font-Awesome#18672]
**Describe the bug**
I've been using beta 3 via a local copy, moving to NPM based version, but documentation describes `npm install --save @fortawesome/fontawesome-pro@next` or `npm install --save @fortawesome/fontawesome-free@next` which resolves to `@fortawesome/fontawesome-pro  ^6.0.0-beta3`

**To Reproduce**
[See Docs > Web > Set-up > Packages](https://fontawesome.com/docs/web/setup/packages#_2-install-your-package)

**Expected behavior**
Documentation snippets should read:
`npm install --save @fortawesome/fontawesome-pro` or
`npm install --save @fortawesome/fontawesome-free`
Same with the Yarn equivalents.

**Screenshots**
N/a

**Version and implementation**
Version: v6
Browser and version: N/a

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [x] I have filled out as much of the above information as I can
- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [x] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this

I can see the `@next` version tag, I think it is a leftover and should be removed from the documentation

Let's assign @talbs!

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @Jas-n. And apologies for any trouble that gave you when getting and running with Font Awesome 6.

As @tagliala mentioned, that was definitely a leftover artifact from our v6 Alpha and Beta days. We've removed that `@next` bit from our docs and everything should be more accurate now - https://fontawesome.com/docs/web/setup/packages#_2-install-your-package.

Let us know if you see anything else amiss and thanks again for the help!
