### ISSUE TITLE
Puzzle icon is incorrect

### ISSUE THREAD

**Issue by extenzw** [FortAwesome/Font-Awesome#18674]
**Describe the bug**
The puzzle icon (fa-puzzle) is a bit... puzzling. Hehe. 

**To Reproduce / Expected behavior**
So here's what it's supposed to look like:
<img width="287" alt="Screenshot 2022-02-10 at 13 01 53" src="https://user-images.githubusercontent.com/63393430/153404993-cc9c1881-018e-4722-8c80-595451da0237.png">

But here's what the light and thin icons look like:
<img width="287" alt="Screenshot 2022-02-10 at 13 02 40" src="https://user-images.githubusercontent.com/63393430/153405163-bd18caa7-3ef9-4d10-9edd-5b40a938cba2.png">
It looks like the top left piece is missing the little bit on the side? Regular and solid are both fine.

**Version and implementation**
Version: V6, it's [live on the website](https://fontawesome.com/v6/icons/puzzle?s=light) 

- [ ] SVG with JS
- [ ] Web Fonts with CSS
- [ ] SVG Sprites
- [ ] On the Desktop

**Bug report checklist**
- [ ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [ ] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

I've also noticed this problem, but I think there are chances that this has been done intentionally, because of the outline

Let's ask @sensibleworld

**Comment by jayaram-ramanaraynan** [comment]
> **Describe the bug** The puzzle icon (fa-puzzle) is a bit... puzzling. Hehe.
> 
> **To Reproduce / Expected behavior** So here's what it's supposed to look like: <img alt="Screenshot 2022-02-10 at 13 01 53" width="287" src="https://user-images.githubusercontent.com/63393430/153404993-cc9c1881-018e-4722-8c80-595451da0237.png">
> 
> But here's what the light and thin icons look like: <img alt="Screenshot 2022-02-10 at 13 02 40" width="287" src="https://user-images.githubusercontent.com/63393430/153405163-bd18caa7-3ef9-4d10-9edd-5b40a938cba2.png"> It looks like the top left piece is missing the little bit on the side? Regular and solid are both fine.
> 
> **Version and implementation** Version: V6, it's [live on the website](https://fontawesome.com/v6/icons/puzzle?s=light)
> 
> * [ ]  SVG with JS
> * [ ]  Web Fonts with CSS
> * [ ]  SVG Sprites
> * [ ]  On the Desktop
> 
> **Bug report checklist**
> 
> * [ ]  I have filled out as much of the above information as I can
> * [ ]  I have included a test case because my odds go _way_ up that the team can fix this when I do
> * [ ]  I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Interesting catch!

**Comment by sensibleworld** [comment]
Okay. So. Yes, this was entirely intentional on my part. Because of the strokes, the shapes in the `light` and `thin` icons are wider than those in the `solid` and `regular` styles. Adding in the extra nubbin' was causing issues with spacing and the "harmony" of the design.

Question... if you have JUST seen the `light` and `thin` icons, would the missing element be that noticeable?

**Comment by simube** [comment]
In solid, the two bottom pieces are "wrong" too ;)

**Comment by sensibleworld** [comment]
Due to the design constraints of a 16px grid, I'm going to mark this as "won't fix" and close.
