### ISSUE TITLE
MacOS FontBook error when installing FA 6 Pro-Thin

### ISSUE THREAD

**Issue by rintkid** [FortAwesome/Font-Awesome#18673]
**Describe the bug**
The first time I tried to install the whole set of otfs from the fontawesome-pro-6.0.0-desktop folder, I got a critical error (red cross) from macOS Font Book not allowing me to install Font Awesome 6 Pro-Thin-100.
/!\ It only happened the first time I tried to install them all. Then it worked

**To Reproduce**
MacOS 11.5.2
Installing the whole set of otfs from the fontawesome-pro-6.0.0-desktop from FA website for the first time.
Font Awesome 6 Pro-Thin-100 triggers an alert

Describe any details about the test case that we need to know like "whatever you do, don't click the red button."

**Expected behavior**
The OTFs fonts to install with no errors

**Version and implementation**
MacOS 11.5.2
fontawesome-pro-6.0.0-desktop

- [X] On the Desktop

**Bug report checklist**
- [X] I have filled out as much of the above information as I can
- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I wasn't able to replicate on 12.2 (21D49)

I've tried to install all the fonts together and I did not receive warning or errors

<img width="752" alt="image" src="https://user-images.githubusercontent.com/556268/153385561-60356944-93af-460e-afd5-7dc922b25bde.png">

> /!\ It only happened the first time I tried to install them all. Then it worked

Can you give more information about the error or warning you got?

Leaving this open for feedback from the community

**Comment by rintkid** [comment]
Hi Tagliala,

Well I hesitated to post this because I couldn't replicate it.

It only happened on the very first install of the whole group of files (selected them all in the Finder, then clicked "Install" in Font Book).
It worked fine on second try and when I tried to replicate by uninstalling and reinstalling

As I said, in the window you're showing, I had a red cross icon, pretty sure the message was the following I saw online "1 serious error was found. Do not use this font file."

Please feel free to remove this issue it doesn't appear to be relevant

**Comment by sensibleworld** [comment]
Thanks, @rintkid. Let us know if a similar problem pops up in the future!
