### ISSUE TITLE
trash-alt alias not working in 6.0.0

### ISSUE THREAD

**Issue by cah-brian-gantzler** [FortAwesome/Font-Awesome#18688]
When upgrading from 5.15.4 to 6.0.0 the `trash-alt` icon was no longer working. I see this is an alias and is stated as also an alias in 6.0 but it does not work. Using `trash-can` does work in 6.0.0, just wasnt expecting to have to change all my icon strings. 

Other strings not working, check a few they were aliases as well. May be all aliases. I put in parens the new name, but it still says the alias should be supported

search (magnifying-glass), cog (gear), sign-out-alt, unlock-alt, calendar-alt, exclamation-triangle, pencil-alt, exclamation-circle, shopping-cart (cart-shopping), exchange-alt, plus-circle, search-plus, save (floppy-disk), undo, plus-circle, angle-double-left, angle-double-right, sync (arrows-rotate)

**Comment by sensibleworld** [comment]
Hi there, can you give us example of the code you're using, or a site where the issue is happening? The aliases _should_ be working... so it'd be great to pin down where this bug is originating.

**Comment by cah-brian-gantzler** [comment]
The site is private so I cant give you a working example but here is our code (we are using ember-fontawesome)
```
<FaIcon
              data-test-button-delete
              @icon={{constants.button.delete.icon}}
              {{on "click" (fn @onDeleteRow record)}}
            />
```
Luckily we are using a constants file so I should have to change the names in one place. This works in 5.14.4 if I update my package.json to 6.0.0 I get the following in the console and the element is never rendered. I found this when our tests failed that checked to see if the correct icon was being rendered and failed to find the element

sadly there is not too much in the way of information in the console there
![image](https://user-images.githubusercontent.com/1529286/153677961-9bb9fe35-fb5e-4e1f-843e-51419b817123.png)


This could ultimately be an ember-fontawesome problem, but it manifests when the only thing I do is update the version of this repo so thought I should start here.

**Comment by robmadole** [comment]
Let's keep this work over in https://github.com/FortAwesome/ember-fontawesome/issues/177

Going to close here.
