### ISSUE TITLE
Minor bug with the documentation (ver. 6.0.0)

### ISSUE THREAD

**Issue by nortonandreev** [FortAwesome/Font-Awesome#18692]
[https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6](url) here it says that **university** icon has been renamed to **bank** — should be **building-columns** instead.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @talbs

**Comment by sensibleworld** [comment]
Gah! You're right. This was a last-minute change on my part, so that we weren't being too opinionated on what the building represented. The good news is that `university` and `bank` will still work when referencing that icon. We'll get it fixed.

**Comment by talbs** [comment]
Sorry for the radio silence on this thread, folks. As @sensibleworld mentioned, this was a later change when we released `6.0.0`. [Our renamed in v6 icon list](https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6) should now be accurate and note `building-columns` as the current nam.

Thanks much for bringing this to our attention, @nortonandreev.
