### ISSUE TITLE
Is version 6 actually released or not?

### ISSUE THREAD

**Issue by DaSchTour** [FortAwesome/Font-Awesome#18690]
I got the newsletter, that version 6 was release, but I'm not really sure if it actually is. Updates don't show up and upgrade instructions are not really clear about which packages are updated.

When I run `npx npm-check-updates --filter "/@fortawesome.*/" --target greatest` I get this:

@fortawesome/fontawesome-svg-core   ^1.2.36  →        ^1.3.0     
@fortawesome/free-brands-svg-icons  ^5.15.4  →        ^6.0.0     
@fortawesome/pro-duotone-svg-icons  ^5.15.4  →  ^6.0.0-beta3     
@fortawesome/pro-light-svg-icons    ^5.15.4  →  ^6.0.0-beta3     
@fortawesome/pro-regular-svg-icons  ^5.15.4  →  ^6.0.0-beta3     
@fortawesome/pro-solid-svg-icons    ^5.15.4  →  ^6.0.0-beta3

So it looks like version 6 was only release for brands?

**Comment by Tausif4171** [comment]
Hello DaSchTour,
I think it is not released yet I got this message on google => "Released in Beta! New to v6 Pro – Thin Style! ... Thousands of New + Refreshed Icons!"

**Comment by DaSchTour** [comment]
Okay, I think there is an issue with using a NPM Proxy in front of fontawesomes repository. For some time it worked pretty nice to have Nexus connected to the fontawesome private repository, but that seams to not work anymore.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads up about the proxy.

I can confirm that FA 6 Pro has been released and it is available in the Pro repository

```
$ npm show @fortawesome/pro-solid-svg-icons version
6.0.0
```

Closing here, but feel free to comment

**Comment by Tausif4171** [comment]
Thanks for letting me know :)
