### ISSUE TITLE
the icons are not displayed

### ISSUE THREAD

**Issue by Nocteln** [FortAwesome/Font-Awesome#18718]
Hi,
i use font awesome free but some icons are displayed while others are not can you help me please ( I put an image as an example)  

![image](https://user-images.githubusercontent.com/99535202/154719906-871c24c1-ea52-4103-ae65-f45c77e9d491.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There are some other information we need to debug this issue

Could you please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?

Also, a reproducible test case would help

Feel free to edit the first post or create a new issue and close this one

**Comment by Nocteln** [comment]
sorry but i don't understand wan't you want

idk what is a "reproducible test case

**Comment by tagliala** [comment]
> idk what is a "reproducible test case

An actual website, or a fiddle like this https://jsfiddle.net/tagliala/4f8gp2wL where I can reproduce the problem

A screenshot does not help in this case

**Comment by Nocteln** [comment]
oh ok you can go in https://kstcat.site (sorry its a french website)

**Comment by tagliala** [comment]
Thanks

The website is using FA6 syntax (`fa-solid`), but the Kit is loading FA5 icons (5.15.4)

You can change the kit to FA6 or update the syntax to work with FA5 (`fa-solid` -> `fas`)

Docs:
- Kit: https://fontawesome.com/v6/docs/web/setup/use-kit#what-s-a-kit
- FA 5 syntax: https://fontawesome.com/v5/docs/web/reference-icons/

Hope it helps

Closing here but feel free to comment

**Comment by Nocteln** [comment]
thank you so much its working
