### ISSUE TITLE
Search in documentation does not work in nested pages

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#18715]
Search is broken in nested pages

- ✅ https://fontawesome.com/docs 
- ❌ https://fontawesome.com/v6/docs/web/use-with/react/dig-deeper#contentHeader
- ❌ https://fontawesome.com/v5/docs

<img width="433" alt="image" src="https://user-images.githubusercontent.com/556268/154579307-f13f3490-005e-4935-a9f8-009dfc4b0eac.png">

**Comment by talbs** [comment]
Thanks for noting this and apologies for letting it become frozen in carbonite, @tagliala. 

I'm not able to reproduce these console errors nor the issue with search on the URLs you provided. A couple of questions:

- Are you still seeing this issue on fontawesome.com? If so, are those URLs still accurate?
- I'm assuming you're referring to our Docs search fields/form on those URLs. Is that a correct assumption?

**Comment by tagliala** [comment]
Can't replicate anymore
