### ISSUE TITLE
Icon Request: Globe with Meridians

### ISSUE THREAD

**Issue by bribes** [FortAwesome/Font-Awesome#18728]
Something like this:
![image](https://user-images.githubusercontent.com/52789876/154872043-a91382b2-cee8-4f7c-a621-7d0c55d8e568.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for the already existing [fa-globe](https://fontawesome.com/icons/globe?s=solid)?

**Comment by bribes** [comment]
No, it’s not I’d like a separate icon for a globe with meridians that looks like the image I’ve sent at the top.

**Comment by tagliala** [comment]
> No, it’s not I’d like a separate icon for a globe with meridians that looks like the image I’ve sent at the top.

Could you please elaborate why icon globe does not fit your use case?

**Comment by bribes** [comment]
I’m using it as a placeholder for a site icon, and a icon like this is usually used.

**Comment by tagliala** [comment]
> I’m using it as a placeholder for a site icon, and a icon like this is usually used.

Apologies, let me try to clarify my question

We already have [fas fa-globe](https://fontawesome.com/icons/globe?s=solid) available for everyone, and Pro users can use other styles including [far fa-globe](https://fontawesome.com/icons/globe?s=regular). `fa-globe` look almost identical to the request above, at least in the intention, keeping also in mind the limitation of a base 16px icon size

<img width="656" alt="image" src="https://user-images.githubusercontent.com/556268/154987444-24a0d06d-e3d1-4727-b7ae-9e5d6317e76f.png">

Can you please clarify why `fa-globe` does not fit the design and the use case described here?

**Comment by bribes** [comment]
Oh sorry, I didn't see those.
