### ISSUE TITLE
book-genre

### ISSUE THREAD

**Issue by TimLewis1207** [FortAwesome/Font-Awesome#18725]
This is a request for many icons to cover book genres as a way for websites to categorize and display themes for titles to include, but not limited to, Science Fiction, Horror Thriller, Fantasy, Epic Fantasy, Noir, Action-Adventure, Classic, Mystery, Non-fiction, Drama, Romance, Dystopian, Paranormal, and so on. This may also be addressed by adding additional tags on existing icons to create a grouping/theme for these genres.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#contributing-to-font-awesome), so I need to close it

Please open individual request, one per genre, by filling out our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md). 

Please also:
- Check that the icon is not already here at https://fontawesome.com/icons (e.g: [alien](https://fontawesome.com/icons/alien?s=solid) to represent science fiction?, [dragon](https://fontawesome.com/icons/dragon?s=solid) to represent fantasy?)
- Check that there isn't already a request for the icon you want to request at https://github.com/FortAwesome/Font-Awesome/issues
- Provide a single color example of the icon you are requesting. "Action-Adventure" and "Classic" are abstract concepts hard to implement
