### ISSUE TITLE
Feature request: Allow use of the TTF font in IE9+ by setting installable flag

### ISSUE THREAD

**Issue by tomdcc** [FortAwesome/Font-Awesome#1873]
Background: I would like to include Font Awesome in my web app's [application cache](https://developer.mozilla.org/en/docs/HTML/Using_the_application_cache). However, when using the application cache, ALL files in the cache will be downloaded, regardless of whether they are actually used. So if I include all the different font awesome files, they will all be downloaded by every browser.

I do not need to support older versions of IE, but I do care about mobile browsers. If I want the browsers to download just use one font file, my options are:
- Use WOFF, but this [won't work on any version of the Android browser](http://caniuse.com/woff)
- Use TTF, but this [won't work on IE](http://caniuse.com/ttf) without the [installable flag set](http://blogs.msdn.com/b/ie/archive/2010/07/15/the-css-corner-better-web-typography-for-better-design.aspx).

The installable flag is not currently set in the Font Awesome TTF file.

For my own purposes I can just patch the TTF file using e.g. [ttfpatch](http://www.derwok.de/downloads/ttfpatch/) to set the font to installable, but I figure that I can't be the only person that will ever want to put Font Awesome in their application cache, so maybe the project would consider setting the flag for people wanting to do this.

Thanks, Tom

**Comment by bendytree** [comment]
+1 

I'm using font-awesome 4.4.0 and received this error in IE 11:

    @font-face failed OpenType embedding permission check. Permission must be Installable.

For anyone using node/npm, [ttembed-js](https://www.npmjs.com/package/ttembed-js) offers an easy way to set it:

    npm install -g ttembed-js
    ttembed-js fontawesome-webfont.ttf

**Comment by softforge** [comment]
+1 - this should definitely be set
