### ISSUE TITLE
Postcss version conflict

### ISSUE THREAD

**Issue by sva71** [FortAwesome/Font-Awesome#18732]
I'm trying to upgrade my free font-awesome version from 4 to 6 (Angular 12 project).

After editing path to css in index.html, angular.json and angular-cli.json during project building I receive this error:

"Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.5, but postcss-preset-env uses 7.0.36. Perhaps this is source of the error below."

A guess that problem is in angular-devkit/build-angular package that uses postcss of version 8.3.5 and postcss-preset-env of version 6.7.0. But before fontawesome version update that wasn't a problem.

Help please, what should I do with this?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've double checked all font awesome official packages' `package.json` and I can confirm that no one requires postcss

https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome

Could you please double check that font awesome is causing this issue and provide a reproducible test case?

**Comment by turneye** [comment]
Hi @sva71

Had the same issue and it was solved by updating the .browserslistrc file.  

Just generate a new angular project and copy the contents of the .browserslistrc generated there into the one in your existing project. 

Hope that helps.
