### ISSUE TITLE
Icon Request: fa-JAVASCRIPT

### ISSUE THREAD

**Issue by Gladys-tech** [FortAwesome/Font-Awesome#18738]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Javascript icon is already available:
- https://fontawesome.com/icons/js?s=brands
- https://fontawesome.com/icons/js-square?s=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
