### ISSUE TITLE
Request: Please update the Teradata brand icon

### ISSUE THREAD

**Issue by tdEmpl064** [FortAwesome/Font-Awesome#18745]
Hi,

My colleague Kumar informed me his request  #18072 did not go through last July, because he was notified there is already an active icon for Teradata. However, I just checked the website, and the response at "https://fontawesome.com/search?p=1&q=teradata&s=solid%2Cbrands" states there are no results whatsoever for Teradata.

Regardless the Teradata icon status (existing or not), I would hereby like to request an update (if existing) or a new icon (if not), please, as we recently underwent a change in our official brand graphics. For the new/updated icon, please feel free to use any of the icons in the following links, or respond with any particular specifications you may mandate.
URL for icon 1: https://icons-for-free.com/teradata-1324440242767643357
URL for icon 2: https://icons8.com/icon/108544/teradata

Best regards,
Alexander Kolovos, Ph.D.
Sr. Staff Software Architect
Product Engineering; Vantage Core and SQL Engine
Teradata

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The icon does not exist

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here, but feel free to comment

**Comment by tdEmpl064** [comment]
Thank you @tagliala for the quick response, the validation about the non-existing icon, and the formal steps. Things are slightly different from what I remembered, and will proceed right ahead to file a formal request via the dedicated form.
Bests,
Alexander.
