### ISSUE TITLE
Incorrect `aliases` and `ligatures` type definitions

### ISSUE THREAD

**Issue by chadwickellis** [FortAwesome/Font-Awesome#18751]
**Package**

`@fortawesome/pro-light-svg-icons`

**Version**

`6.0.0`

**Issue**

`aliases` and `ligatures` constants are denoted as string arrays; however, numerical values are sometimes present within these arrays. A complete list of affected icons is below.

**Icons**

- faA
- faAbacus
- faAddressBook
- faAddressCard
- faAlarmClock
- faAlbum
- faAlien
- faAlien8bit
- faAnchor
- faAngleDown
- faAngleLeft
- faAngleRight
- faAnglesLeft
- faAnglesRight
- faAngleUp
- faAnkh
- faAppleWhole
- faArrowDown
- faArrowDownFromLine
- faArrowLeft
- faArrowLeftFromLine
- faArrowLeftToLine
- faArrowRight
- faArrowRightArrowLeft
- faArrowRightFromLine
- faArrowRightToLine
- faArrowRotateLeft
- faArrowRotateRight
- faArrowsRepeat1
- faArrowsRotate
- faArrowUp
- faArrowUpFromLine
- faAsterisk
- faAt
- faAtom
- faAxe
- faB
- faBackpack
- faBackward
- faBackwardFast
- faBacon
- faBadgerHoney
- faBagel
- faBagsShopping
- faBaguette
- faBan
- faBandage
- faBanjo
- faBanSmoking
- faBaseball
- faBasketball
- faBath
- faBatteryEmpty
- faBatteryFull
- faBatteryHalf
- faBatteryLow
- faBatteryQuarter
- faBatteryThreeQuarters
- faBed
- faBedEmpty
- faBell
- faBellConcierge
- faBellOn
- faBellSlash
- faBicycle
- faBiohazard
- faBolt
- faBomb
- faBone
- faBook
- faBookBlank
- faBookmark
- faBookOpen
- faBooks
- faBoombox
- faBoot
- faBowArrow
- faBowlScoop
- faBowlScoops
- faBowlSpoon
- faBox
- faBoxBallot
- faBoxesStacked
- faBoxingGlove
- faBrain
- faBreadLoaf
- faBriefcase
- faBroccoli
- faBroom
- faBrowser
- faBuilding
- faBullhorn
- faBullseyeArrow
- faBurgerCheese
- faBurrito
- faBus
- faButter
- faC
- faCabinetFiling
- faCactus
- faCakeCandles
- faCakeSlice
- faCalculator
- faCalendar
- faCamcorder
- faCamera
- faCameraMovie
- faCameraRetro
- faCampground
- faCandleHolder
- faCandy
- faCandyBar
- faCanFood
- faCar
- faCarrot
- faCarSide
- faCartShopping
- faCassetteTape
- faCassetteVhs
- faCat
- faChair
- faChampagneGlasses
- faChartLineDown
- faCheck
- faCheeseSwiss
- faChessBishop
- faChessKing
- faChessKnight
- faChessPawn
- faChessQueen
- faChessRook
- faChestnut
- faChevronLeft
- faChevronRight
- faChurch
- faCircle
- faCircleCheck
- faCircleDot
- faCircleDown
- faCircleH
- faCircleHalfStroke
- faCircleLeft
- faCirclePause
- faCirclePlay
- faCircleQuestion
- faCircleRadiation
- faCircleRight
- faCircleStop
- faCircleUp
- faCircleUser
- faCircleXmark
- faCity
- faClipboard
- faClock
- faCloud
- faCloudArrowDown
- faCloudArrowUp
- faCloudBolt
- faCloudFog
- faCloudRain
- faCloudSnow
- faCloudSun
- faCloudSunRain
- faClub
- faCoffin
- faCoin
- faComment
- faCommentDots
- faComments
- faCompactDisc
- faCompass
- faComputerMouse
- faCookie
- faCopyright
- faCorn
- faCow
- faCrab
- faCreditCard
- faCricketBatBall
- faCroissant
- faCross
- faCrown
- faCucumber
- faCupcake
- faCupStraw
- faCurlingStone
- faCustard
- faD
- faDeer
- faDeleteLeft
- faDesktop
- faDharmachakra
- faDiamond
- faDice
- faDiceFive
- faDiceFour
- faDiceOne
- faDiceSix
- faDiceThree
- faDiceTwo
- faDivide
- faDna
- faDog
- faDogLeashed
- faDollarSign
- faDonut
- faDoorClosed
- faDove
- faDragon
- faDroplet
- faDrum
- faDrumstick
- faDuck
- faE
- faEar
- faEarthAfrica
- faEarthAmericas
- faEarthAsia
- faEgg
- faEject
- faElephant
- faEmptySet
- faEnvelope
- faEnvelopeOpen
- faEquals
- faEuroSign
- faExclamation
- faEye
- faF
- faFaceAngry
- faFaceBeamHandOverMouth
- faFaceDiagonalMouth
- faFaceDotted
- faFaceFlushed
- faFaceFrown
- faFaceFrownOpen
- faFaceGrimace
- faFaceGrin
- faFaceGrinBeam
- faFaceGrinBeamSweat
- faFaceGrinHearts
- faFaceGrinSquint
- faFaceGrinSquintTears
- faFaceGrinStars
- faFaceGrinTears
- faFaceGrinTongue
- faFaceGrinTongueSquint
- faFaceGrinTongueWink
- faFaceGrinWide
- faFaceHandOverMouth
- faFaceHandPeeking
- faFaceHoldingBackTears
- faFaceKiss
- faFaceKissBeam
- faFaceKissWinkHeart
- faFaceLaughBeam
- faFaceMeh
- faFaceMehBlank
- faFaceMelting
- faFaceRollingEyes
- faFaceSadCry
- faFaceSadTear
- faFaceSaluting
- faFaceSmile
- faFaceSmileBeam
- faFaceSmileWink
- faFaceSurprise
- faFaceTired
- faFalafel
- faFaucetDrip
- faFax
- faFeather
- faFieldHockeyStickBall
- faFile
- faFileImage
- faFileLines
- faFilePen
- faFilm
- faFire
- faFireExtinguisher
- faFish
- faFlag
- faFlagCheckered
- faFlagPennant
- faFlashlight
- faFlatbread
- faFlatbreadStuffed
- faFloppyDisk
- faFlower
- faFlowerDaffodil
- faFlowerTulip
- faFolder
- faFolderOpen
- faFonduePot
- faFontAwesome
- faFootball
- faForward
- faForwardFast
- faFrenchFries
- faFutbol
- faG
- faGamepadModern
- faGarlic
- faGasPump
- faGaugeHigh
- faGaugeSimpleHigh
- faGear
- faGem
- faGhost
- faGift
- faGlass
- faGlassesRound
- faGlobe
- faGraduationCap
- faGreaterThan
- faGrid
- faGuitarElectric
- faH
- faHammer
- faHand
- faHandFist
- faHandMiddleFinger
- faHandPeace
- faHandPointUp
- faHandshakeSimple
- faHandSpock
- faHanukiah
- faHardDrive
- faHashtag
- faHeadphones
- faHeart
- faHeartCrack
- faHelicopter
- faHexagon
- faHippo
- faHoneyPot
- faHorizontalRule
- faHorse
- faHospital
- faHotdog
- faHotel
- faHourglass
- faHourglassEnd
- faHourglassStart
- faHouse
- faHouseChimney
- faHryvniaSign
- faHundredPoints
- faI
- faIceCream
- faIceSkate
- faIdCard
- faInboxIn
- faInboxOut
- faIndustryWindows
- faInfinity
- faIntersection
- faIslandTropical
- faJ
- faJackOLantern
- faJoystick
- faK
- faKaaba
- faKey
- faKeyboard
- faKeySkeleton
- faKhanda
- faKite
- faKnifeKitchen
- faL
- faLandmark
- faLaptop
- faLeafMaple
- faLeafyGreen
- faLeftRight
- faLemon
- faLessThan
- faLightbulb
- faLink
- faLips
- faLiraSign
- faListOl
- faLobster
- faLock
- faLollipop
- faLungs
- faM
- faMagnet
- faMagnifyingGlass
- faMailbox
- faMap
- faMapPin
- faMars
- faMarsAndVenus
- faMarsDouble
- faMarsStroke
- faMarsStrokeRight
- faMarsStrokeUp
- faMartiniGlass
- faMasksTheater
- faMeat
- faMedal
- faMegaphone
- faMercury
- faMeteor
- faMicrophoneLines
- faMicrophoneStand
- faMicroscope
- faMinus
- faMobile
- faMonkey
- faMoon
- faMosque
- faMotorcycle
- faMountain
- faMountains
- faMugHot
- faMushroom
- faMusic
- faN
- faNeuter
- faNewspaper
- faNoteSticky
- faO
- faOctagon
- faOm
- faOnion
- faOtter
- faP
- faPager
- faPalette
- faPalletBoxes
- faPancakes
- faPanFood
- faPanFrying
- faPaperclip
- faPaperPlane
- faParagraph
- faPause
- faPeace
- faPeanuts
- faPen
- faPencil
- faPenFancy
- faPenNib
- faPepper
- faPepperHot
- faPercent
- faPerson
- faPersonBiking
- faPersonBikingMountain
- faPersonPraying
- faPersonRunning
- faPersonSkiing
- faPersonSnowboarding
- faPersonSwimming
- faPersonWalking
- faPhone
- faPhoneFlip
- faPhoneRotary
- faPianoKeyboard
- faPie
- faPig
- faPizza
- faPlaneArrival
- faPlaneDeparture
- faPlaneEngines
- faPlanetRinged
- faPlay
- faPlug
- faPlus
- faPoo
- faPopcorn
- faPotato
- faPotFood
- faPowerOff
- faPretzel
- faPrint
- faPuzzlePiece
- faQ
- faQuestion
- faQuoteLeft
- faQuoteRight
- faR
- faRabbit
- faRadio
- faRainbow
- faRam
- faReceipt
- faRectangle
- faRectangleXmark
- faRecycle
- faRegistered
- faRepeat
- faRepeat1
- faReply
- faRibbon
- faRight
- faRoad
- faRobot
- faRocketLaunch
- faRotate
- faRubleSign
- faRuler
- faRulerTriangle
- faRupeeSign
- faS
- faSackDollar
- faSalad
- faSaltShaker
- faSandwich
- faSatellite
- faSatelliteDish
- faSaxophone
- faScaleBalanced
- faScarf
- faSchool
- faScissors
- faScrewdriver
- faScroll
- faSeedling
- faShareFromSquare
- faSheep
- faShekelSign
- faShield
- faShieldCross
- faShip
- faShirt
- faShower
- faShrimp
- faShuffle
- faSigma
- faSignal
- faSignalBars
- faSignalBarsFair
- faSignalBarsGood
- faSignalBarsWeak
- faSignalFair
- faSignalGood
- faSignalStrong
- faSignalWeak
- faSkull
- faSkullCrossbones
- faSmoking
- faSnake
- faSnooze
- faSnowflake
- faSnowman
- faSoap
- faSocks
- faSoftServe
- faSpade
- faSparkles
- faSpider
- faSpiderWeb
- faSpoon
- faSquare
- faSquareCheck
- faSquareDown
- faSquareFull
- faSquareHeart
- faSquareInfo
- faSquareLeft
- faSquareMinus
- faSquareParking
- faSquarePlus
- faSquareRight
- faSquareRoot
- faSquareUp
- faSquareUpRight
- faSquareXmark
- faSquid
- faStar
- faStarAndCrescent
- faStarHalf
- faStarOfDavid
- faStarShooting
- faSteak
- faSterlingSign
- faStethoscope
- faStop
- faStopwatch
- faSuitcase
- faSun
- faSunCloud
- faSunglasses
- faSunrise
- faSunset
- faSushi
- faSword
- faSwords
- faSymbols
- faSynagogue
- faSyringe
- faT
- faTableTennisPaddleBall
- faTaco
- faTag
- faTally
- faTamale
- faTaxi
- faTelescope
- faTemperatureEmpty
- faTemperatureFull
- faTemperatureHalf
- faTemperatureQuarter
- faTemperatureThreeQuarters
- faTengeSign
- faTennisBall
- faThumbsDown
- faThumbsUp
- faTicket
- faTilde
- faToilet
- faToiletPaper
- faTombstoneBlank
- faToolbox
- faTooth
- faToothbrush
- faToriiGate
- faTornado
- faTractor
- faTrademark
- faTrafficLight
- faTrain
- faTrainTram
- faTransgender
- faTrashCan
- faTree
- faTreeChristmas
- faTreeDeciduous
- faTreePalm
- faTriangle
- faTriangleExclamation
- faTrophy
- faTruck
- faTruckMedical
- faTruckPickup
- faTrumpet
- faTurnDown
- faTurnUp
- faTurtle
- faTv
- faTvRetro
- faU
- faUfo
- faUmbrellaBeach
- faUnicorn
- faUnion
- faUnlock
- faUpDown
- faUser
- faUserGroup
- faUserHelmetSafety
- faUserNinja
- faUserSecret
- faUtensils
- faV
- faVanShuttle
- faVenus
- faVenusDouble
- faVenusMars
- faVial
- faViolin
- faVolcano
- faVolleyball
- faVolume
- faVolumeHigh
- faVolumeLow
- faVolumeSlash
- faW
- faWaffle
- faWatch
- faWaveSine
- faWhale
- faWhiskeyGlass
- faWifi
- faWifiFair
- faWifiWeak
- faWindowFrame
- faWindowMaximize
- faWindowMinimize
- faWineGlass
- faWonSign
- faWrench
- faX
- faXmark
- faY
- faYenSign
- faYinYang
- faZ

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @robmadole

**Comment by chadwickellis** [comment]
No worries at all. It's worth mentioning that this issue doesn't just affect the `@fortawesome/pro-light-svg-icons` package. For example, in the case of `faA`:

[https://github.com/FortAwesome/Font-Awesome/blob/0078392516a3c27e5549c5643fd8237a9063b344/js-packages/%40fortawesome/free-solid-svg-icons/faA.d.ts#L11](https://github.com/FortAwesome/Font-Awesome/blob/0078392516a3c27e5549c5643fd8237a9063b344/js-packages/%40fortawesome/free-solid-svg-icons/faA.d.ts#L11)
[https://github.com/FortAwesome/Font-Awesome/blob/0078392516a3c27e5549c5643fd8237a9063b344/js-packages/%40fortawesome/free-solid-svg-icons/faA.js#L7](https://github.com/FortAwesome/Font-Awesome/blob/0078392516a3c27e5549c5643fd8237a9063b344/js-packages/%40fortawesome/free-solid-svg-icons/faA.js#L7)

**Comment by robmadole** [comment]
The numbers are unicode aliases. I'll get the types file updated to reflect this.

**Comment by chadwickellis** [comment]
@robmadole, closing this issue in light of the latest release.
