### ISSUE TITLE
 Session token in URL

### ISSUE THREAD

**Issue by Amal03-bit** [FortAwesome/Font-Awesome#18764]
https://ka-p.fontawesome.com/releases/v5.15.4/svgs/brands/linkedin.svg?token=b7e79643d9
 

Sensitive information within URLs may be logged in various locations, including the user's browser, the web server, and any forward or reverse proxy servers between the two endpoints. URLs may also be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third parties via the Referer header when any off-site links are followed. Placing session tokens into the URL increases the risk that they will be captured by an attacker.

**Comment by robmadole** [comment]
Hi there. This is not a session token but a unique identifier for the Kit. There is no sensitive information. Going to close but if you feel like we've missed something let us know.
