### ISSUE TITLE
Icon request: Social Distancing

### ISSUE THREAD

**Issue by NitchScoot** [FortAwesome/Font-Awesome#18785]
Two people icons spaced out with "6ft" and arrows or lines in between

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We have https://fontawesome.com/icons/people-arrows-left-right?s=solid for this use case

> 6ft

we usually do not add text inside icons for a some reasons, including internationalization

@talbs any chance to add "social distancing" keyword to `people-arrows-left-right`?

**Comment by aethior** [comment]
This is the icon proposed by OCHA (UN) ([link](https://brand.unocha.org/d/xEPytAUjC3sH/icons)) for social distancing (physical distancing).
Is it really necessary to create a new icon in FA?

![Physical-distancing](https://user-images.githubusercontent.com/1769227/164949044-90be25a2-a509-443c-8d1d-f272bc2a863a.png)

In any case, I think it's a good idea to add the alias `social distancing` to the `fa-people-arrows-left-right` icon to improve the search.

**Comment by tagliala** [comment]
> Is it really necessary to create a new icon in FA?

Since `people-arrows-left-right` has been added to humanitarian icons, I think it is fine for this use case

> social distancing

Maybe just a search term

**Comment by sensibleworld** [comment]
We've got this prepped for our next release.
