### ISSUE TITLE
Icon request: fa-brands fa-gab

### ISSUE THREAD

**Issue by AverageJ0E** [FortAwesome/Font-Awesome#18781]
Please add fa-brands fa-gab

**Comment by tagliala** [comment]
Hi!

This request is a duplicate of #10304, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
