### ISSUE TITLE
TypeScript: Some T-shirt sizes not listed in SizeProps

### ISSUE THREAD

**Issue by daven97** [FortAwesome/Font-Awesome#18788]
TypeScript error saying that the `xl` size is invalid.
![Screen Shot 2022-03-07 at 1 20 29 PM](https://user-images.githubusercontent.com/35749306/157111674-ec14ea09-1c02-49bc-9b65-8556800c6f6b.png)

![Screen Shot 2022-03-07 at 12 35 46 PM](https://user-images.githubusercontent.com/35749306/157105236-d1718122-e639-4bf1-a0af-b963f21a91ea.png)

The docs at https://fontawesome.com/docs/web/style/size has this list of size options:
![Screen Shot 2022-03-07 at 12 53 57 PM](https://user-images.githubusercontent.com/35749306/157107933-b04bb2e1-4660-42da-b2a8-d36b88d9a9f2.png)

and the fontawesome-react docs at https://fontawesome.com/docs/web/use-with/react/style#size state:
> Font Awesome supports t-shirt size scale from 2xs to 2xl as well as literal sizing from 1x to 10x.

However, looking at @robmadole's changes to `SizeProp` in https://github.com/FortAwesome/Font-Awesome/blob/65f4bdb5025759ba25cd3432568de288b6a67527/js-packages/%40fortawesome/fontawesome-svg-core/index.d.ts as part of https://github.com/FortAwesome/Font-Awesome/pull/18652, several of the sizes from the table above are missing, including `xl`.

![Screen Shot 2022-03-07 at 1 03 23 PM](https://user-images.githubusercontent.com/35749306/157109250-3f471459-9a52-4f1d-9177-d6906dd60284.png)

The icon is displaying at the correct size, so this is simply a TypeScript error.

**Comment by daven97** [comment]
I believe this is as simple as updating the type, so I have created this PR: https://github.com/FortAwesome/Font-Awesome/pull/18789.

**Comment by tagliala** [comment]
Thanks. I've assigned both @mlwilkerson and @robmadole

**Comment by theDanielJLewis** [comment]
Thanks for reporting this and creating the PR, @daven97! I'm running into this issue, too. So I'll be grateful when the PR is merged.

**Comment by tagliala** [comment]
I can see it fixed in 6.2.0

https://github.com/FortAwesome/Font-Awesome/blob/d3a7818c253fcbafff9ebd1d4abb2866c192e1d7/js-packages/%40fortawesome/fontawesome-svg-core/index.d.ts#L22-L38

**Comment by daven97** [comment]
Sorry I missed that this issue had been closed. This is working for me now in 6.2.0! Thanks!
