### ISSUE TITLE
How to rebuild JS files from the SVG sources?

### ISSUE THREAD

**Issue by rolandmas** [FortAwesome/Font-Awesome#18796]
Hi, I'm Roland Mas, and I'm currently preparing Debian packages of fontawesome (-free, of course). Part of the process includes building the assets from their source files, this term being generally understood as the "preferred form for modification". My understanding is that the source files for the icons are the SVG files, which are correctly present both in the published tarballs and in the Git repository. However, I haven't been able to find out how to regenerate the JS files from the SVG ones. I was hoping that the CONTRIBUTING.md file would give me a hint, but no luck. I also looked at other repositories, but none seemed likely to contain the build scripts.
So… could someone in the know point me in the right direction?
Thanks for FA!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has been discussed in the past at #13467

There is also a discussion on the Debian bug report tracker at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902981#27

Hope it helps

Closing here, but feel free to comment

**Comment by rolandmas** [comment]
Well, it doesn't really help concretely, but it certainly does help clarify things.

To clarify some more, I suggest renaming the tarballs for the next releases by removing the misleading "Source" component from the title, since they only contain part of the source and miss the parts required to rebuild the assets.

Thanks for the reply!

**Comment by tagliala** [comment]
> To clarify some more, I suggest renaming the tarballs for the next releases by removing the misleading "Source" component from the title, 

You mean these ones?

![image](https://user-images.githubusercontent.com/556268/157720616-491b2b02-70e0-412e-8fe4-24f9818fcaa6.png)

**Comment by rolandmas** [comment]
Yes. I suggest something like "all formats" or so instead.
