### ISSUE TITLE
Folder blank icon

### ISSUE THREAD

**Issue by Sozialarchiv** [FortAwesome/Font-Awesome#18799]
In v5 the folder-icon looked like the the folder-blank-icon in v6.

But the new folder-blank-icon is now in the non-free part.

For consistency reason it would be great if you could offer folder-blank-icon in the free part or switch the icons.

Thank you very much.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There were some design changes for the free set in V6, like the new `bolt` icon

Anyway, for this particular use case, I'm asking @sensibleworld if it is possible to switch the icons or add `folder-blank` to the free set for uniformity when using stacking/masking

V5: https://jsfiddle.net/tagliala/bfa6uhse/61/
V6: https://jsfiddle.net/tagliala/bfa6uhse/60/

**Comment by sensibleworld** [comment]
Thanks for the feedback. I think I'd like to revert the styling of the base icon to be the same as v5.

So `folder-blank` and `folder` would both reference the legacy design.

I would then give the "new" design a different name: `folder-closed` to match `folder-open`.

Would that work for y'all?

**Comment by tagliala** [comment]
> I would then give the "new" design to a different name: `folder-closed` to match `folder-open`.

Makes sense to me

**Comment by Sozialarchiv** [comment]
> I think I'd like to revert the styling of the base icon to be the same as v5.

Your suggestion sound really great. Thank you very much.

**Comment by sensibleworld** [comment]
This has been fixed: https://fontawesome.com/icons/folder?s=solid + https://fontawesome.com/icons/folder-closed?s=solid

**Comment by Sozialarchiv** [comment]
Thank you very much. 

As user of the free version (for open source projects) and baker I really can admin that fontawesome is awesome.
