### ISSUE TITLE
Icon request: icon-split

### ISSUE THREAD

**Issue by jakepearson** [FortAwesome/Font-Awesome#188]
Hi,
I created a new split and copy icon to add to you library.  I didn't have the tools to regenerate all the fonts so I have attached svg files for each:
- ![Copy](http://joapy.com/assets/icons/icon-copy.svg)
- ![Split](http://joapy.com/assets/icons/icon-split.svg)

I hope they are close to what you need to add them.  Please let me know if there are any problems.

thanks,
Jake

**Comment by G-Driver** [comment]
+1

**Comment by liptonbeer** [comment]
+1

**Comment by johntrepreneur** [comment]
+1

**Comment by projecteon** [comment]
+1

**Comment by TakitIsy** [comment]
I have another image in mind for the icon, but also for  "split".
<img src="http://ntakit.com/.inc/phpList/icons/sys/Default/Split.png" />

I think of the 2nd image in the first post of this thread as a "fork".

**Comment by nimrod-cohen** [comment]
+1

**Comment by franciskovitch** [comment]
![image](https://cloud.githubusercontent.com/assets/2789398/16114885/93411508-33bb-11e6-9512-f30eb64c7d72.png)

+1

This icon, top to bottom direction

**Comment by billystalnaker** [comment]
+1

**Comment by easaw** [comment]
Any updates on this? It's not in v5.5...

**Comment by jshah4517** [comment]
+1 for the split arrow icon

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
