### ISSUE TITLE
Icon Request: Rock Climbing / Bouldering / Lead Climbing / Belaying

### ISSUE THREAD

**Issue by QuinnKWolter** [FortAwesome/Font-Awesome#18804]
We've got luchador masks, it seems only fair we'd draft something up for this newly Olympicized sport.

**Comment by aethior** [comment]
Hi @QuinnKWolter,

This request is duplicate of #13649.
Please 👍 that request.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Reopening and renaming #13649 as rope climbing

**Comment by tagliala** [comment]
Nope, sorry, I got confused. This is a duplicate of #13649
