### ISSUE TITLE
New icon Request

### ISSUE THREAD

**Issue by mehmoodakhter5** [FortAwesome/Font-Awesome#18805]
Kindly add new Payments icons Which are in need for Pakistani peoples https://www.vhv.rs/dpng/d/473-4736946_easypaisa-logo-png-transparent-png.png
https://play-lh.googleusercontent.com/9-0wlkGycWAJRsuQ-p_bMqDGE0liYgihxKka0PtRjxqEiRVkDKaROEyFxYg520lLbpk=s180-rw
These two are needed

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please open two individual request, one for each brand

Please provide information about the brand as well as an official website

Please make sure that your request follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and make sure that the title and all the information required are provided

Closing here
