### ISSUE TITLE
Type definition files are incorrectly named, so Icons are not imported

### ISSUE THREAD

**Issue by mylnikovD** [FortAwesome/Font-Awesome#18800]
Hey guys, thanks for awesome work! We are using your library to dynamically import icons for our project to reduce final bundle size, but recently when updating to version 6 we've encountered that some icons have a mismatch in type definition and js declaration files, for example 
![image](https://user-images.githubusercontent.com/46220817/157838046-ff95635f-237e-4132-b735-59e5656ee26c.png)
Full list of problematic icons we've found are: 
faEyeDropper
faPaintbrush
faPaintbrushFine
faThumbtack
in pro-solid, pro-regular and pro-light packages

Would very appreciate addressing those, thanks in advance!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has already been reported in #18665 and has been addressed upstream, but let's check with @robmadole if all icons in the list have been fixed

**Comment by robmadole** [comment]
We're getting this fixed up for 6.1.0. Thanks for reporting @mylnikovD !

**Comment by robmadole** [comment]
6.1.0 is released now. @mylnikovD if you get a moment let me know if this is fixed.
