### ISSUE TITLE
Instagram icon is missing

### ISSUE THREAD

**Issue by d7mtg** [FortAwesome/Font-Awesome#18801]
<img width="1102" alt="CleanShot 2022-03-11 at 09 17 14@2x" src="https://user-images.githubusercontent.com/40274365/157885004-2cf41086-e5b9-4926-a058-5378b1a3faf3.png">
<img width="362" alt="CleanShot 2022-03-11 at 09 18 23@2x" src="https://user-images.githubusercontent.com/40274365/157885049-ea7eb14d-53ef-43e1-a5fe-874c62484c00.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is related to an ad-blocker with an anti-social network filter

Please try again with all extensions disabled or with a different browser

Ref: pinned issue #18118

Hope it helps

Closing here but feel free to comment

**Comment by d7mtg** [comment]
Yes, you're right.

https://github.com/AdguardTeam/AdguardFilters/issues/112577#issue-1166478270

**Comment by tagliala** [comment]
Oh thanks for the heads-up.

I use AdGuard Pro, but I do not have this issue by default

It can be replicated by enabling "I don't care about cookies" list, others don't look like to be affected
