### ISSUE TITLE
icon-lock to small?

### ISSUE THREAD

**Issue by SharpNoiZy** [FortAwesome/Font-Awesome#1881]
Hi,

I tried to use icon-lock in a bootstrap input group in an input-group-addon.
But it was smaller than the icon-envelope I use exactly the same way on the same page.
Then I swap icon-lock with icon-key and it looked good, so there seems to be a size issue with the icon-lock?!

Kind regards

**Comment by yunti** [comment]
I have this issue as well. Shame not to be able to use the lock, feels more secure than a key. :)
