### ISSUE TITLE
Telegram ico wont work.

### ISSUE THREAD

**Issue by RaulmmBr** [FortAwesome/Font-Awesome#18818]
<li><a class="twitter" href="#"><i class="fa fa-instagram"></i></a></li>
                  <li><a class="linkedin" href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a class="dribbble" href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a class="rss" href="#"><i class="fa fa-telegram"></i></a></li>

All icons work fine, but telegram dont show.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see from your example that you are using Font Awesome 4 syntax, so I'm not sure what exact version of FA you are running. 

[telegram](https://fontawesome.com/icons/telegram?s=brands) has been introduced in FA 4.7.0, which is in EOL, so we do not provide support for that

Please check that you are using FA >= 5

If you think there is an issue with Font Awesome, fill our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

Closing here, but feel free to comment
