### ISSUE TITLE
Triangle flag not working

### ISSUE THREAD

**Issue by swathi894** [FortAwesome/Font-Awesome#18815]
<i class="fa-solid fa-flag-pennant"></i> .it's not working ,I have tried multiple times.
Please look into this

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot understand this request

Does "triangle flag" refer to [flag-pennant](https://fontawesome.com/v6/icons/flag-pennant?s=solid)?

In that case, I cannot replicate: https://jsfiddle.net/tagliala/2s78abqk/1/

If you still think there is an issue with Font Awesome, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

PS: `flag-pennant` is a Pro icon. As a Pro customer, you can send an email to hello@fontawesome.com and get dedicated support

Closing here, but feel free to comment

**Comment by swathi894** [comment]
Hi Tagliala,

Thank you for your reply,

Yes Trinangle  flag referes to flag-pennant.
Infont awesome webisite  the icon synatx is  <i class="fa-solid fa-flag-pennant"></i> but
https://jsfiddle.net/tagliala/2s78abqk/1/ ---> the icon synatx is  <span class="fas fa-flag-pennant"></span>--this one not worked for me.

Please help on this

**Comment by swathi894** [comment]
Thank you Tagliala
