### ISSUE TITLE
Icon Request: new youtube

### ISSUE THREAD

**Issue by ideirj** [FortAwesome/Font-Awesome#1882]
http://www.theverge.com/2013/8/29/4671362/youtube-brand-new-logo-design

:)

**Comment by ImBobby** [comment]
I think we need to create [youtube's "official logo"](http://youtube.com/yt/brand/using-logo.html). Current icons such as [fa-youtube](http://fortawesome.github.io/Font-Awesome/icon/youtube/) and [fa-youtube-square](http://fortawesome.github.io/Font-Awesome/icon/youtube-square/) are not the official logo.

**Comment by sensibleworld** [comment]
Cleaning up some old issues :) We have the new YouTube logo in FA5: https://fontawesome.com/icons?d=gallery&q=youtube&s=brands
