### ISSUE TITLE
Question: Will 'Pro' icons be included in the metadata/icons.json file?

### ISSUE THREAD

**Issue by matthewrdev** [FortAwesome/Font-Awesome#18826]
Hi FontAwesome team.,

As per my title, will meta-data for the "Pro" icons be included in the [icons.json](https://github.com/FortAwesome/Font-Awesome/blob/6.x/metadata/icons.json) file? Currently it appears that only free tier icons have this information included.

**Context**
I'm the maintainer of the [fa2cs open source project](https://github.com/matthewrdev/fa2cs); a code generator that consumes the [cheatsheet](https://fontawesome.com/v5/cheatsheet/pro) and generates a C# class containing a public property for all icons. This makes FontAwesome *much* easier to consume/maintain in any C# based application.

I'd like to update the generator to use the `icons.json` file. This allows me to give additional details like "Introduced In Version", "Last Modified In Version" and should be less maintenance overhead going forward. The `icons.json` only appears to contains the free icons; this is a considerable issue for the project as the static class should contain *all* icons and note in its API docs which tier and font family it belongs in.

**Comment by sensibleworld** [comment]
@matthewrdev Yup! The metadata is now available in version 6.1.0 :)

**Comment by matthewrdev** [comment]
@sensibleworld Apologies if I'm missing something here but doing a search for a pro icon such as ["Abacus"](https://fontawesome.com/icons/abacus?s=solid) or ["bridge-suspension"](https://fontawesome.com/icons/bridge-suspension?s=solid) in the 6.1.0 meta data returns zero results.

Is there a separate meta data file for Pro icons that you could link me to?

**Comment by sensibleworld** [comment]
Hey @matthewrdev. Where are you looking? The icons.json files in both the free + pro downloads should include that info. https://fontawesome.com/download

**Comment by matthewrdev** [comment]
Hey @sensibleworld! I'm looking specifically within this file:

https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/metadata/icons.json

As an example of the missing pro icons in the icons.json file, do a search for [`bridge`](https://fontawesome.com/search?q=bridge&s=solid%2Cbrands) in the Font Awesome icon explorer and in the icons.json. The explorer shows the `bridge-suspension` icon (plus the other bridge variants included in the free tier) whereas the `bridge-suspension` is not with the icons.json.

I've noticed that the file includes the SVG content for all icons which may be why the Pro icons aren't within it.

As an aside, do you know when to expect a cheat-sheet to be available for the 6.X icons? 

EG: 
v5: https://fontawesome.com/v5/cheatsheet/pro
v6: https://fontawesome.com/v6/cheatsheet/pro (currently a 404).

**Comment by sensibleworld** [comment]
Hey @matthewrdev. Gotcha. Yeah, sorry I think I misunderstood your original question. The Pro icons are available in our Pro icons.json file, which is available when you have an active Pro subscription. We don't list them in the Free icons.json file.

As for the v6 cheatsheet, we've built it in to our current icon search:

<img width="1196" alt="CleanShot 2022-03-22 at 18 13 15@2x" src="https://user-images.githubusercontent.com/529604/159585048-57bfa0ed-c97e-4ec0-ace0-ddf812e0dde3.png">

**Comment by matthewrdev** [comment]
@sensibleworld Thanks for following up so quickly.

I'll update the code generator to use the Pro icons.json; where would I find this in my account's portal?

**Comment by matthewrdev** [comment]
@sensibleworld Ok, I've found the icons.json in the pro icon set. Thanks for your help!

PS: The code generator will use a locally kept, non-distributed version of the icon.json inline with the Pro TCs.

**Comment by matthewrdev** [comment]
@sensibleworld Just following up on this one last time!

I've upgrade fa2cs to use the `icons.json` from the pro icons archive; this should make for some happy .NET/C# FontAwesome users. 🙂

[The final output of this upgrade can be found here](https://raw.githubusercontent.com/matthewrdev/fa2cs/master/FontAwesomeIcons.cs).

Thanks again for you help.
