### ISSUE TITLE
Fontawesome 6.1.0 changelog is missing

### ISSUE THREAD

**Issue by esetnik** [FortAwesome/Font-Awesome#18821]
Release 6.1.0 at https://github.com/FortAwesome/Font-Awesome/releases/tag/6.1.0 links to https://fontawesome.com/docs/changelog/ but there is no changelog for the 6.1.0 release.

**Comment by sensibleworld** [comment]
It's coming! We need to release things in a certain order, and the website is usually the last domino to fall. Stay tuned :)

**Comment by sensibleworld** [comment]
Changelog is now live: https://fontawesome.com/docs/changelog/
