### ISSUE TITLE
xmark missing

### ISSUE THREAD

**Issue by robvaneck** [FortAwesome/Font-Awesome#18828]
In package:
```"@fortawesome/free-solid-svg-icons": "^5.15.4"```

The following icons are missing:
```
"xmark" // https://fontawesome.com/icons/xmark?s=solid
```

These icons are named differently:
```
"file-lines" vs "FileAlt" // https://fontawesome.com/icons/file-lines?s=solid
"ellipsis-vertical"  vs  "EllipsisV"  // https://fontawesome.com/icons/ellipsis-vertical?s=solid
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I think this is a reference to FA6 documentation.

The proper name of `xmark` in FA5 is `times`

https://fontawesome.com/v5/icons/times?s=solid

I think that there are some issues in the documentation and there is not an easy change from v6 to v5 in detail pages, but in this way you will ensure that searches are done against v5

<img width="836" alt="image" src="https://user-images.githubusercontent.com/556268/158858623-5ba8f20e-8aa4-40fb-9033-1be96e6a705e.png">

Hope it helps

Closing here but feel free to comment

**Comment by robvaneck** [comment]
Your response time is awesome :)
