### ISSUE TITLE
Feature Request: Support Colorful Icons in FontAwesome

### ISSUE THREAD

**Issue by complabs28** [FortAwesome/Font-Awesome#18827]
Hello,
I would love to have Support for Colored Icons in FontAwesome!

**Comment by mbomb007** [comment]
Icons can be colored using CSS. If you use the font/CSS method, use `color`. If you use SVGs, you can use [this method](https://stackoverflow.com/a/53336754)

**Comment by complabs28** [comment]
Forgot to close issue 😜. Closing now.
