### ISSUE TITLE
Power transform missing redirect

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#18834]
Hi @talbs , we have a lot of references to the `power-transforms` link

https://fontawesome.com/docs/web/style/power-transforms

together with `masking` and `layering` In a lot of requests (e.g., https://github.com/FortAwesome/Font-Awesome/issues/16598#issuecomment-625748776)

Some days ago I've removed the trailing `s` and the link was working, but now it has been pointed out in https://github.com/FortAwesome/Font-Awesome/issues/18795#issuecomment-1072456845 that this link does not work anymore, and the original link does not properly redirect

I'm asking if it possible to check redirects so that old reference to the documentation will keep working

**Comment by talbs** [comment]
Sorry for the delay on this, @tagliala and thanks for bringing this up. I've got a PR up that should address this and handle the older Power Transform docs URL more gracefully.

**Comment by talbs** [comment]
Okay, @tagliala. We've pushed those redirect changes and the following older URLs should now resolve to their current docs counterparts...

- https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
- https://fontawesome.com/how-to-use/on-the-web/styling/masking
- https://fontawesome.com/how-to-use/on-the-web/styling/layering
