### ISSUE TITLE
Icon enhancement: Bookmark duotone

### ISSUE THREAD

**Issue by senaiboy** [FortAwesome/Font-Awesome#18839]
The duotone bookmark icon is basically the same as a non-duotone icon. Can the duotone be 2 colours, split into halves? Eg primary colour is left half of the bookmark, secondary colour is right half.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

This may actually be a bug, let's ask @sensibleworld

**Comment by sensibleworld** [comment]
The duotone bookmark icon how includes two layers: https://fontawesome.com/icons/bookmark?s=duotone&f=classic
