### ISSUE TITLE
Less class change on 6.1 is broken

### ISSUE THREAD

**Issue by adrienfr** [FortAwesome/Font-Awesome#18835]
Hi,

Since v6.1, I think there is an issue with Less class attributes.
In [v6.0](https://github.com/FortAwesome/Font-Awesome/blob/6.0.0/less/_core.less) we had `.fas, .fa-solid`, `.far, .fa-regular`, ... but since [v6.1](https://github.com/FortAwesome/Font-Awesome/blob/6.1.0/less/_core.less), we have `.fas, .fa--solid`, `.far, .fa-regular`, ... .

Am I missing a configuration change somewhere? In v.6.1 all my FontAwesome icons are _`italic` because `.fa-solid` is not defined here but `fa--solid` :

<img width="282" alt="Capture d’écran 2022-03-18 à 17 06 19" src="https://user-images.githubusercontent.com/4313077/159039576-2afe2aaa-aea2-4153-b0d3-9b010bb0a9c5.png">
_

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this issue.

Looks like an issue to me, let's assign @robmadole

**Comment by robmadole** [comment]
Thanks @adrienfr we'll get this fixed up in 6.1.1.

**Comment by robmadole** [comment]
@adrienfr I'm afraid this didn't make it in to 6.1.1. We'll try and get it into the next release though.

**Comment by adrienfr** [comment]
Hi @robmadole, do you have any ETA for this fix to be released? Thanks

**Comment by robmadole** [comment]
@adrienfr no ETA yet but it's slotted in for the next v6 release

**Comment by talbs** [comment]
Thanks for bringing this to our attention and apologies for the less than awesome Less compilation. 

I've taken this off of @alexpoiry's hands and have a fix up for review. As @robmadole mentioned, this should be fixed in our next release shortly. I'll keep you folks posted once that's on its way out the door.

**Comment by robmadole** [comment]
This fix is now released in 6.1.2. Give it a go everyone and let us know if you still have problems.
