### ISSUE TITLE
Misc icons just not showing (with several websites)

### ISSUE THREAD

**Issue by leecollings-sb** [FortAwesome/Font-Awesome#18849]
I'm using the compiled CSS file, however I continually find that a lot of icons just aren't showing up and for no real reason.

For this example I'm using unicode, and can get some icons showing, but now I've just tried the Gauge High icon (f625) and this is just showing a blank space.

I can find the unicode reference in the FA css file but when looking on front end, it's not matchin git with anything so not showing an icon.

This is incredibly frustrating that I've actually been having this on multiple sites over the past few months.

.woocommerce-MyAccount-navigation a:before {
    font-family:'FontAwesome';
    display:inline-block;
    content:'\f192';
    margin-right:.5rem;
    color:var(--nl-secondary);
}
.woocommerce-MyAccount-navigation-link--dashboard a:before {
    content:'\f625';
    font-weight:900;
}

This is what I'm using. The default icon is showing fine, the individual one isn't. I've checked and the icon is free, and I'm using 6.0.0 which is included.

What am I doing wrong? Please answer urgently.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think that this code is just missing the proper `font:` css rule. This is documented in the upgrading guide available at https://fontawesome.com/docs/web/setup/upgrade/pseudo-elements

Demo: https://jsfiddle.net/tagliala/4f8gp2wL/14/

Hope it helps

Closing here, but feel free to comment

**Comment by leecollings-sb** [comment]
Hi, it still doesn't work...

As you can see, the gauge icon I'm trying to load doesn't, but the others do (this is exactly as it was working when I opened the issue).

You can see in the inspector I am using the new rules you kindly linked to as well.

![Screenshot 2022-03-24 at 16 37 28](https://user-images.githubusercontent.com/12139008/159966010-61f8166b-51b1-4e06-9a0b-360bd848d40d.png)

**Comment by tagliala** [comment]
Sorry, screenshot does not help. Could you please provide a reproducible test case?

**Comment by leecollings-sb** [comment]
How am I supposed to provide that? I'm giving you all the evidence I have. For some reason your example works, so my next thing is thinking it's the FA CSS file I'm using, so I'm trying to get that to you, but I can't upload it here. Any ideas how I can get this CSS file to you?

**Comment by leecollings-sb** [comment]
I've even taken the all.css used in your example, and replaced the contents of my CSS file with this, and it still doesn't show.. It is getting quite frustrating because I've got this on several sites now, and have no idea what's going on, and I ideally could do with someone who knows the project to be able to offer help and ideas.

I've followed all of the guidelines to get it working.

**Comment by tagliala** [comment]
> How am I supposed to provide that? 

A publicly accessible website showing the issue

**Comment by leecollings-sb** [comment]
Right now I cannot provide that to you (which is why I used a screenshot...).

However, I'm just attempting to download a completely fresh copy of the project and replacing the contents.

**Comment by leecollings-sb** [comment]
No that still doesn't show anything up, the file is now 6.1.1 as opposed to 6.0.0 which is what it was.

**Comment by leecollings-sb** [comment]
There is one more thing I've thought of, I have them installed on my computer as local fonts, which may be overriding this instead.. so I'm just disabling these to find out.

**Comment by leecollings-sb** [comment]
It works when I use any of the icons I've used in my sidebar, as you can see. There's clearly something up with that particular icon when trying to be used with unicode. SUrely you have had this reported before? LIke I said, I've had this with several websites.

**Comment by leecollings-sb** [comment]
I've resolved it now, sorry my mistake.. I didn't update the webfont files

**Comment by tagliala** [comment]
No problem, glad you solved
