### ISSUE TITLE
Typo in documentation for import of brand icons

### ISSUE THREAD

**Issue by OmKakatkar** [FortAwesome/Font-Awesome#18842]
While reading the docs for version 6.1.0, I came across a typo in the import statement for brand icons in the [react part](https://fontawesome.com/v6/docs/web/use-with/react/add-icons#add-icons-globally).

Code snippet from the docs
```import ReactDOM from 'react-dom'
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { faTwitter, faFontAwesome } from '@fortawesome/free-brand-svg-icons'

library.add(fas, faTwitter, faFontAwesome)
```

By using the above code, I tried to install the `free-brand-svg-icon package`

But received the following error:
```
PS F:\Projects\notes-app> yarn add @fortawesome/free-brand-svg-icons 
yarn add v1.22.17
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2ffree-brand-svg-icons: Not found".info If you think this is a bug, please open a bug report with the information provided in "F:\\Projects\\notes-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

After search through npm and yarn registry, found that the package name is `@fortawesome/free-brands-svg-icons` and not `@fortawesome/free-brand-svg-icons` given in the docs.

The correct version of the code snippet inside the docs should be:
```import ReactDOM from 'react-dom'
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
import { faTwitter, faFontAwesome } from '@fortawesome/free-brands-svg-icons'

library.add(fas, faTwitter, faFontAwesome)
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and. thanks for reporting this.

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @OmKakatkar and apologies for the confusion when trying to get brand icons working in your React project.

It looks like we already have this fix in place on fontawesome.com's docs - https://fontawesome.com/v6/docs/web/use-with/react/add-icons#add-icons-globally as a team member or customer may have caught it as well.

I'm going to close this with that in mind, but if anything else feels fa-fishy with our docs, feel free to shout again.
