### ISSUE TITLE
Icon Request: fa-invoice

### ISSUE THREAD

**Issue by javaYoosh** [FortAwesome/Font-Awesome#18856]
Looking for icons for financial functions such as invoice, billing, ledger

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Invoice icon is already available:
- https://fontawesome.com/icons/file-invoice?s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

If you want to request a new icon, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md), having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening a new one

Closing here
