### ISSUE TITLE
Icon request: `grip-lines-triple`, `grip-lines-triple-vertical`, `grip-dots-triple`, `grip-dots-triple-vertical`

### ISSUE THREAD

**Issue by babakfp** [FortAwesome/Font-Awesome#18854]
3 line version (also the same for vertical version):

![Screenshot 2022-03-25 163932](https://user-images.githubusercontent.com/44144724/160215026-89d91857-1e9b-4350-8c34-2bee5cbeb7e1.png)

3 line version (I know about bars icon):

![Screenshot 2022-03-25 164022](https://user-images.githubusercontent.com/44144724/160215028-3aaa2e28-347c-4488-bcbf-4600adeeecdb.png)

(I'm not sure about the naming)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Naming is fine, but can you please also add a use case and why the existing icons don't work?

**Comment by babakfp** [comment]
Hi
Thanks
Nevermind, I find better alternatives👍
I wss going to use dots as menu toggle and lines for main menu toggle. bars icon lines are a little to far from eachother, but in my current project it looks fine.
