### ISSUE TITLE
CSS classes are not working on font awesome icon 6.1.1 

### ISSUE THREAD

**Issue by raviraj-gardi** [FortAwesome/Font-Awesome#18857]
I am using 
`<i className='topIcon' class="fa-brands fa-twitter-square"></i>`

```
  .topIcon {
    font-size: 20px;
    margin-right: 10px;
    color: rgb(153, 74, 74);
    cursor: pointer;
  }
```
with 
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />`

but it does not apply styling. on the other hand css classes are working on local elements such as img etc.

please help , how to resolve this .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> `<i className='topIcon' class="fa-brands fa-twitter-square"></i>`

the correct attribute name is `class` (not `className`) and should go with other css classes

❌ `<i className='topIcon' class="fa-brands fa-twitter-square"></i>`
✔️  `<i class="topIcon fa-brands fa-twitter-square"></i>`

Hope it helps

Closing here, but feel free to open a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case if you think there is an issue with Font Awesome

**Comment by raviraj-gardi** [comment]
@tagliala Thank you so much. I was following a tutorial and was stuck on this. 
It's working, sorry for bothering with such a silly mistake.

**Comment by tagliala** [comment]
No problem, glad you solved
