### ISSUE TITLE
fa-rss doesn't work in Safari

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18858]
[`fa-rss`](https://fontawesome.com/icons/rss?s=solid) doesn't appear in Safari (macOS).

[`fa-square-rss`](https://fontawesome.com/icons/square-rss?s=solid) does work, however.

What I've tested:
- Another WebKit browser (it works)
- Without content blockers (does not work)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I can't replicate (macOS 12.3 / Safari 15.4)

Demo: https://jsfiddle.net/tagliala/ex4hp3yn/1/

<img width="571" alt="image" src="https://user-images.githubusercontent.com/556268/160278545-8238f973-20ec-4b3c-9054-52f6872975d2.png">


There are a lot of different ways to use Font Awesome (self-hosted, CDN, npm, JS, CSS, Kits) and two major supported versions with different syntax (`fa-solid` vs `fas`), so it is hard to debug without information and a reproducible test case

Closing here, but feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) with a reproducible test case
