### ISSUE TITLE
Broken link in v5 docs on upgrading from v4

### ISSUE THREAD

**Issue by rodnolan** [FortAwesome/Font-Awesome#18851]
[This paragraph](https://fontawesome.com/v5/docs/web/setup/upgrade-from-v4#icon-name-changes) contains a link to a named anchor that is invalid. 

The text "some of those names" links to: 

https://fontawesome.com/v5/docs/web/setup/upgrade-from-v4#name-changes 

whereas it should point to: 

https://fontawesome.com/v5/docs/web/setup/upgrade-from-v4#icon-name-changes-between-version-4-and-5

**Comment by talbs** [comment]
Thanks for pointing this out, @rodnolan and apologies for the stinky linky.

I've got a PR up to fix this issue and will let you know when we release it to fontawesome.com.

**Comment by talbs** [comment]
Thanks again for letting us know about those broken links. They are now fixed on https://fontawesome.com/v5/docs/web/setup/upgrade-from-v4.
