### ISSUE TITLE
phone-alt not working in V5

### ISSUE THREAD

**Issue by travisbotello** [FortAwesome/Font-Awesome#18862]
phone-alt icon is not working in current V5. See official docs:

<img width="1152" alt="Bildschirmfoto 2022-03-28 um 12 33 11" src="https://user-images.githubusercontent.com/1157380/160380176-ea344326-3489-48ce-8ee6-2dd7ad7d1e12.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I cannot replicate (Chrome / macOS)

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/556268/160388603-453b8ec1-8024-4219-a913-d2fe1bc68b0f.png">

Could you please:
- try again
- check in incognito with content blocker disabled
- check that you have not installed an older version of FA on the system (< 5.9) which may take precedence

If the problem persists, please add more information (browser, os, etc.)

**Comment by travisbotello** [comment]
Mb...indeed ad blocker on duty :D

**Comment by tagliala** [comment]
> Mb...indeed ad blocker on duty :D

Any specific reason to block `phone-alt` ? Should not be filtered by social icons related filters

**Comment by travisbotello** [comment]
I am using ublock origin on chrome. I disabled/enabled again, but now I can't reproduce the missing phone-alt icon anymore. Strange...
