### ISSUE TITLE
issue with design

### ISSUE THREAD

**Issue by spatel7112000** [FortAwesome/Font-Awesome#18864]
plan page design not working. i don't know css file or something but unappropriate page.
https://fontawesome.com/plans

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please retry?

If it  still does not work, could you please provide more information, like browser, OS, country (may be region related), check in incognito without extensions (maybe an extension), check development console for errors

**Comment by spatel7112000** [comment]
Yes it's work

**Comment by tagliala** [comment]
thanks for the feedback, closing here
