### ISSUE TITLE
Broken "stack icons" and "fixed-width" links v5 docs 

### ISSUE THREAD

**Issue by hellodaniel** [FortAwesome/Font-Awesome#18860]
The link here for stacking icons: 
https://fontawesome.com/v5/docs/web/style/

Goes here: 
https://fontawesome.com/v5/docs/web/style/stack-icons/
"Hmm, we couldn't find a doc there."

Should go here: 
https://fontawesome.com/v5/docs/web/style/stack

(also the link for "fixed-width" is incorrect)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

> The link here for stacking icons:
> https://fontawesome.com/v5/docs

I cannot see the link in this page, where I can find it?

**Comment by hellodaniel** [comment]
> > The link here for stacking icons:
> > https://fontawesome.com/v5/docs
> 
> I cannot see the link in this page, where I can find it?

Sorry, I posted the wrong link 😅 have updated - the link is here: 
https://fontawesome.com/v5/docs/web/style/

The links for "fixed-width" and "stack" are incorrect

**Comment by tagliala** [comment]
Thanks, I can confirm, let's assign @talbs

**Comment by talbs** [comment]
Thanks for pointing this out, @hellodaniel. It's much appreciated (as is the help triaging the issue, @tagliala). I've got a PR that should tackle this up.

I'll let you and this thread know when that fix is released.

**Comment by talbs** [comment]
Thanks again for pointing out these broken links in our docs, @hellodaniel. They are now fixed on https://fontawesome.com/v5/docs/web/style/.
