### ISSUE TITLE
Icon fa-right not working

### ISSUE THREAD

**Issue by x-Foz3R-x** [FortAwesome/Font-Awesome#18863]
In all fa-6 icons, icon fa-right is not showing up probable by the fact that in all.css fa-right icon is not included in the code.

![Zrzut ekranu 2022-03-28 183909](https://user-images.githubusercontent.com/98351320/160446155-7433d26c-c707-4ecd-a9bb-2bfc0360318c.jpg)

**Comment by x-Foz3R-x** [comment]
![Zrzut ekranu 2022-03-28 184115](https://user-images.githubusercontent.com/98351320/160446404-f2810b52-fd33-472f-82f0-bb59ec8647c8.jpg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

[fa-right](https://fontawesome.com/icons/right?s=solid) is a pro icon and I confirm it is present in FA6 Pro

Could you please provide more details?
