### ISSUE TITLE
Timer icon missing from "free-solid-svg-icons"

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#18879]
I am trying to use the solid timer icon and it's throwing:

`Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons/faTimer'`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As far as I can tell, [fa-timer](https://fontawesome.com/icons/timer?s=solid) is a Pro icon and it is not available in the free set

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by ghost** [comment]
Oh Sorry, Thanks for the help :)
