### ISSUE TITLE
Icon request??

### ISSUE THREAD

**Issue by Shah-Haque** [FortAwesome/Font-Awesome#18876]
Hi I really like the icon designs this website is offering but I am looking for a specific icon and that is C# so would it be possible if you can add the programming icons for most languages??

I don't personally mind the design of the logo, attached is a reference you can use..
![c sharp](https://user-images.githubusercontent.com/93956445/161402465-60b1f3bd-3ccc-4f73-9e25-c4e38c2cdbc7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

C# has been requested at #8365 , please add a 👍 reaction to that request.

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
