### ISSUE TITLE
Font awesome 6 - SVG Pseudo Issue

### ISSUE THREAD

**Issue by GashyDev** [FortAwesome/Font-Awesome#18872]
A colleague of mine discovered that their Pseudo elements were not displaying on Safari when using the SVG version of FA6, but the webfont version does.

I tried it myself just to see if they had set it up incorrectly, but I too had the same issue even after following the recommended guide.

It seems to work fine on all the other browsers that I have tested - Chromium & Firefox.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and sorry for the late reply.

I cannot confirm after following instructions at https://fontawesome.com/v6/docs/web/add-icons/pseudo-elements#set-pseudo-elements-to-display-to-none

https://jsfiddle.net/tagliala/3vhx0tn1/

<img width="586" alt="image" src="https://user-images.githubusercontent.com/556268/164294431-f8ed96a4-0b12-4baa-987f-4eea0818aa55.png">

Could you please provide more information and a reproducible test case?

Meanwhile, closing here

**Comment by GashyDev** [comment]
Hey thanks for the reply

The CSS and safari version
<img width="702" alt="image" src="https://user-images.githubusercontent.com/34476863/165083839-24ea146e-a53d-45d1-80ff-d51742b1c4fb.png">

OS version
![image](https://user-images.githubusercontent.com/34476863/165084329-0ba73660-0975-40c8-a6be-f531a6dd707a.png)

This is using a FA6 kit that is using SVGs and not the webfont.
The render (the same outcome happens if I use the CSS variables listed in the FA6 pseudo documentation as well)
![image](https://user-images.githubusercontent.com/34476863/165083873-1e372793-2bc4-41dd-9146-a62546cbc9de.png)

Works absolutely fine in chromium and firefox
![image](https://user-images.githubusercontent.com/34476863/165084079-e289ac08-9a68-4c60-8537-c543ec8dc30b.png)
![image](https://user-images.githubusercontent.com/34476863/165084134-c79106d5-2958-44de-a272-e4fe8369dc4a.png)

**Comment by tagliala** [comment]
Hi,

I've tried with an svg based Pro Kit and I'm not able to replicate

Can you see pseudoelements at  https://jsfiddle.net/tagliala/2s78abqk/19/ ?

Please double check instructions at https://fontawesome.com/v6/docs/web/add-icons/pseudo-elements#set-pseudo-elements-to-display-to-none and provide a reproducible test case (screenshots don't help)

**Comment by GashyDev** [comment]
That resolved the issue, thank you I was missing the data attribute on the script tag, I think the main reason why I missed this is because I was looking here originally - https://fontawesome.com/v6/docs/web/setup/upgrade/pseudo-elements

Thank you for the help, you're a star!
