### ISSUE TITLE
Add 'fa-cactus' to the 'nature' category

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18888]
I think [fa-cactus](https://fontawesome.com/icons/cactus) icon should be part of the `nature` category.
Similar to [fa-tree](https://fontawesome.com/icons/tree), [fa-tree-palm](https://fontawesome.com/icons/tree-palm) or [fa-mushroom](https://fontawesome.com/icons/mushroom) icons.

Regards.

**Comment by sensibleworld** [comment]
This'll be in the next release.
