### ISSUE TITLE
Craigslist Icons

### ISSUE THREAD

**Issue by robertegnacheski** [FortAwesome/Font-Awesome#1888]
I work for a company that works closely with craigslist and we utilize Font Awesome. It would be great to have the craigslist text logo and peace logo available.

**Comment by thomaslpetry** [comment]
+1

**Comment by kieferhagin** [comment]
+1

**Comment by tylerprobst** [comment]
+1

**Comment by Emalton** [comment]
+1

**Comment by tagliala** [comment]
closing here in favour of #3515
