### ISSUE TITLE
Icon request: icon-nintendo

### ISSUE THREAD

**Issue by pd51189** [FortAwesome/Font-Awesome#18887]
Hi thanks for all of your efforts in creating a diverse icons library!

I have a gaming store and would like to use the Nintendo brand logo/icon for my website but it isn't available in font-awesome.

Surprisingly enough PlayStation and Xbox are available but no Nintendo.

I am requesting that you guys create the Nintendo logo icon in black.

Please advise. Thanks!

**Comment by tagliala** [comment]
Sorry, this is not possible 

https://github.com/FortAwesome/Font-Awesome/blob/5.x/UPGRADING.md#582-to-590

> The nintendo-switch icon has been removed by legal request of Nintendo of America Inc.
>
> Font Awesome is no longer able to provide icons related to Nintendo, their gaming consoles, accessories, or games.
