### ISSUE TITLE
Where to download the pro node svg package?

### ISSUE THREAD

**Issue by Extarys** [FortAwesome/Font-Awesome#18889]
I've been using FA for a long time and backed up the v5 campaign, but didn't see any reason to renew as I don't use any services.

Except now, I want to use the SVG in a project and no longer have access to the private NPM repo, which is fine because I should have access to the zip files on the download page.

But sadly no, the pro package on the website doesn't contain a js file for the individual svgs like the npm package does :thinking: . Or did I miss the link to download the equivalent `pro-*-svg-icons` ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I miss the link to download the equivalent `pro-*-svg-icons` ?

I think that you should be able to download the individual NPM packages at https://fontawesome.com/download#v5-pro-packages

Docs: https://fontawesome.com/v5/docs/web/setup/use-npm-downloads

**Comment by Extarys** [comment]
Ahh now I feel dumb! I didn't scroll down enough... I mean, wow! :smile: Thanks for that!

Yes sadly I missed the v6 early access but when I emailed the team they just replied with the link of the early access ending page lol so no v6 pro for me :/ I guess I'll just wait for the v7 early access :joy:
