### ISSUE TITLE
Font Awesome Pro - Reset Password Email Issue

### ISSUE THREAD

**Issue by chris-burton-fxp** [FortAwesome/Font-Awesome#18896]
My company has recently purchased a pro license on my behalf with my email address. Unfortunately I cannot log into the account at all and the password reset is not getting to me.

I think the issue is that I signed up for an account a while ago with the same email but did not confirm my email address.

I have emailed the hello@fontawesome email address a few times now but have had no response.

I have confirmed with the IT team that this is not an issue with spam filters or blocks.

**Comment by sensibleworld** [comment]
Hey there! Could you send another email in? I'll keep an eye out for it specifically. Feel free to mention me in it.

**Comment by chris-burton-fxp** [comment]
Thanks, I've just requested another password reset and emailed the hello@fontawesome address again also

**Comment by sensibleworld** [comment]
Looks like you may be all set now? Closing this issue, but please let us know if you need anything else
