### ISSUE TITLE
Icon request: mobile-notch-button

### ISSUE THREAD

**Issue by LevaCompany** [FortAwesome/Font-Awesome#18892]
Smartphone icon in category [Devices + Hardware Icons](https://fontawesome.com/icons/categories/devices-hardware)

Preview: 📱

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for a mobile variation having both notch and button?

https://fontawesome.com/search?q=mobile&s=solid

**Comment by LevaCompany** [comment]
@tagliala Thank you!
