### ISSUE TITLE
Icon request: icon-name - Adobe Creative Suite

### ISSUE THREAD

**Issue by limatwo** [FortAwesome/Font-Awesome#18893]
Hello 
Thanks so much for reading my request. If possible can Adobe Creative Suite icon be included ?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, this is not possible

Regards

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150

> The adobe icon has been removed by legal request of Adobe.
> 
> Font Awesome is no longer able to provide any logos or marks for the Adobe brand or their products.
