### ISSUE TITLE
Add 'fa-vest' and 'fa-vest-patches' to the 'clothing+fashion' category

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18913]
I think [fa-vest](https://fontawesome.com/icons/vest) and [fa-vest-patches](https://fontawesome.com/icons/vest-patches) icons should be part of the `clothing+fashion` category.

Regards.

**Comment by aethior** [comment]
I don't know if this can be considered a bug (maybe it's an expected behavior).
When the url contains the version number (e.g. `https://fontawesome.com/v6/icons/vest?s=solid`) the category label redirect to the homepage (click on `Maps` label in this case).

@tagliala If this is a bug, feel free to move this comment to a new issue.

**Comment by sensibleworld** [comment]
This'll be in the next release!

**Comment by sensibleworld** [comment]
Oh, and yes the category label redirecting to the homepage is a bug. I'll open an internal issue.
