### ISSUE TITLE
icon request: icon-moneybag

### ISSUE THREAD

**Issue by admstr** [FortAwesome/Font-Awesome#18917]
icon request: icon-moneybag
![image](https://user-images.githubusercontent.com/103953390/163842148-dbd9b03d-5cec-4de6-9f0d-102eb0ebead2.png)
![image](https://user-images.githubusercontent.com/103953390/163842182-f100decd-f1d1-448b-8d32-66ebbde3db62.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Money bag icon is already available:
- https://fontawesome.com/icons/sack-dollar?style=solid&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by admstr** [comment]
I'm sorry, I don't see it on this list.
https://fontawesome.com/v4/cheatsheet/

*Tracy L. Roberts | University Registrar*
*Office of the Registrar
<https://www.murraystate.edu/academics/RegistrarsOffice/index.aspx>, Murray
State University*
113 Sparks Hall, Murray, KY 42071
*phone *270.809.3380      |  *fax *270.809.3777
***@***.***

Check out *Racer One Stop Self-Service <https://murraystate.edu/onestop/>*
for common questions, forms, and tutorials.
PLEASE TELL US HOW WE ARE DOING.  TAKE OUR SHORT SURVEY
<https://docs.google.com/forms/d/1lBlReO9hwj7Wntd8eAu4fmSdiNpp4W0hX-aFmMKA4g8/viewform>

**Comment by tagliala** [comment]
Hi, that is the cheatsheet for Font Awesome 4

The current version and minimum required version to use that icon is Font Awesome 6.1.0

https://fontawesome.com/docs/web/setup/upgrade/
