### ISSUE TITLE
url https://use.fontawesome.com is not responding. google chrome TLS issue?

### ISSUE THREAD

**Issue by sehrun** [FortAwesome/Font-Awesome#18926]
Today this page https://use.fontawesome.com/releases/v5.14.0/css/all.css won't load in chrome from my IP (I also cleared cookies)(no response)(err_connection_timed_out).
It's not an IP issue, because page loads instantly in firefox.
It's not a chrome issue because if I change IP it loads instantly in chrome. 
I even tryed to simulate get request with same as chrome headers but page loads instantly.
What could be the problem? It's the first time I face such a problem...

**Comment by sehrun** [comment]
I've sent get requests with `user-agent: github issue #18926` for you to troubleshoot my IP.
```
> GET / HTTP/2
> Host: use.fontawesome.com
> user-agent: github issue #18926
> accept: */*
```
seems to be TLS issue, as http request gets response
```
HTTP/1.1 307 Internal Redirect
Location: https://use.fontawesome.com/
Cross-Origin-Resource-Policy: Cross-Origin
Non-Authoritative-Reason: HSTS
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Is this still an issue?

**Comment by sehrun** [comment]
> Is this still an issue?

Yes, it's still an issue. https url won't open in google chrome from for example this IP 94.181.73.64. But it works from firefox.

Could be google chrome issue. But other websites open without problems.

**Comment by tagliala** [comment]
@robmadole are you aware of any similar issue?

**Comment by sehrun** [comment]
I wonder if you can see any logs for this 94.181.73.64, maybe like TLS negotiation failed or something

**Comment by sehrun** [comment]
I've asked in google chrome, so it's "Use secure DNS" issue, most likely not font-awesome problem, so closing
