### ISSUE TITLE
My account doesn't reflect my new license - I can't use FA Pro until you fix this.

### ISSUE THREAD

**Issue by TinaMnWhite** [FortAwesome/Font-Awesome#18925]
I purchased the pro plan today.

Receipt number: XXXX
| Invoice number: XXXX

I did not realize that I already had an account with an expired plan (admin@blueridgepride.org).  Unfortunately, that account does not reflect my new purchase. 
I would create a new acccount, but your confirmation email doesn't include any activation or download link.

I am therefore unable to download and use FontAwesome 6.  Please fix this and let me know how to activate.
Thanks

!

**Comment by sensibleworld** [comment]
@TinaMnWhite I just updated this to remove details about your personal account. Can you send an email to hello@fontawesome.com with your info? We'll get it sorted. Thanks!
