### ISSUE TITLE
New Teamspeak Logo

### ISSUE THREAD

**Issue by nrauschcom** [FortAwesome/Font-Awesome#18924]
Hi there,

TeamSpeak recently contacted us, saying that they don't want their old logo be displayed on our website. Seems like the logo currently included in Font Awesome is no longer the official logo.

This is the current logo:
![ts_logo_vertical_rgb](https://user-images.githubusercontent.com/1051009/164260006-93965585-249e-4637-9f4f-9104f79e97cc.png)

Here is the official logo kit (including SVG):
https://drive.google.com/drive/folders/1xJ6iIU2L6gXDVVQzSB_wCv12soJ18gJl?usp=sharing

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I'm asking if there is a link to official brand guidelines together with an official single color version of the logo that can be used in Font Awesome, otherwise

**Comment by nrauschcom** [comment]
Unfortunately I cannot find any Brand Guide for the new Logo.
I asked my sponsoring manager at TeamSpeak and will provide you with info once I have it.

**Comment by nrauschcom** [comment]
Here's the answer:

> In relation to the media pack side of things, this hasn't been created yet (we used to have this on the website, however we are actually building a new website in the background as it stands, so ours won't be updated until after the website is complete).
> Honestly, as long as the actual logo isn't stretched out of shape etc, then if the graphics person alters the colouration that's fine with us. Here's an example of another sponsor and what they did so it fit their branding: https://twitter.com/REHGaming/header_photo so as you can see here, they've basically whited it so it fits in with their current branding. That's totally fine with us, so I guess what I'm trying to say to you, is go ahead and create something that fits your branding. If you're unsure about it, I don't mind having a quick look at what has been created and I can let you know if anything needs to be altered. 99/100, it should be fine.

**Comment by tagliala** [comment]
Ok thanks

I'm pasting here the logo as a reference

<img width="111" alt="image" src="https://user-images.githubusercontent.com/556268/167163748-c80567f1-3ef9-4eef-b536-73ecf8412258.png">

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/teamspeak?f=brands&s=solid
