### ISSUE TITLE
Icon request: work-desk

### ISSUE THREAD

**Issue by IgorIlgiyaev** [FortAwesome/Font-Awesome#18933]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request? Is this a duplicate of #9495?

**Comment by IgorIlgiyaev** [comment]
Yes Something like this for a person to work on desk

**Comment by tagliala** [comment]
>  for a person to work on desk

Maybe a duplicate of #15143

**Comment by IgorIlgiyaev** [comment]
The first one was more accurate
