### ISSUE TITLE
Icons show in the "wild" but not within your site

### ISSUE THREAD

**Issue by rjbalsi** [FortAwesome/Font-Awesome#18937]
FREE icons not available using "fa-solid" (some are free and work with "fas")

Using FontAware Kit 6.1.1 (free), and ALL.JS

•	&lt;i class="fa-solid fa-car-side"&gt;&lt;/i&gt; - doesn't display anything.
•	&lt;i class="fas fa-car-side"&gt; &lt;/i&gt; - works fine.

Browsing the free library of icons in the wild on my browser https://fontawesome.com/icons/car-side?s=solid shows me the icon, and the type as "fa-solid", icon name as "fa-car-side", and unicode f1b9.

However, "fa-solid" needs to be replaced to "fas".  

According to https://fontawesome.com/docs/web/setup/host-yourself/svg-js your "solid" and "brands" are free so "fa-solid" should work.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Using FontAware Kit 6.1.1 (free), and ALL.JS

Sorry, I cannot replicate:
- Kit: https://jsfiddle.net/tagliala/xc1u4yre/
- all.js: https://jsfiddle.net/tagliala/wr154e6x/12/

`fa-solid` is the new syntax available in FA6. I can only think that there is an older version of font Awesome loading and taking priority over the new one

Could you please provide a reproducible test case?

Meanwhile, closing here

**Comment by rjbalsi** [comment]
Hi  Tagliala I supplied the downloaded kit and issue to them directly but was told to use github.

Do I reply here or open a new issue or.send direct to their support email?

**Comment by tagliala** [comment]
Hi,

>  I supplied the downloaded kit

Kit are not supposed to be downloaded, it is a code with a javascript to use in the `head`

Please reply here with a reproducible test case. Please do not attach files or add screenshots, those won't help, just provide a link to a reproducible test case

**Comment by rjbalsi** [comment]
HiUnfortunately  it's hosted in-house for an australia government website.It's all internal and not accessible by General public.Sent from my Galaxy
-------- Original message --------From: Geremia Taglialatela ***@***.***> Date: 23/4/22  6:20 pm  (GMT+10:00) To: FortAwesome/Font-Awesome ***@***.***> Cc: rjbalsi ***@***.***>, Author ***@***.***> Subject: Re: [FortAwesome/Font-Awesome] Icons show in the "wild" but not within your site (Issue #18937) 
Hi,

I supplied the downloaded kit

Kit are not supposed to be downloaded, it is a code with a javascript to use in the head
Please reply here with a reproducible test case. Please do not attach files or add screenshots, those won't help, just provide a link to a reproducible test case
