### ISSUE TITLE
Icon request: melting-face

### ISSUE THREAD

**Issue by LevaCompany** [FortAwesome/Font-Awesome#18930]
Melting face icon in category [Emoji and Users + People](https://fontawesome.com/search?c=users-people%2Cemoji)

Preview: 🫠

Learn more: [Link](https://emojipedia.org/melting-face/)

Super idea! :wink:

**Comment by aethior** [comment]
Hi @LevaCompany,

This icon was added in v6.0.0 for [FA PRO](https://fontawesome.com/plans) version.
Check: https://fontawesome.com/icons/face-melting

Regards.

**Comment by LevaCompany** [comment]
thank you!

**Comment by LevaCompany** [comment]
@aethior Please create for free version

**Comment by aethior** [comment]
> @aethior Please create for free version

I'm not a FA team member. Sorry. :)
