### ISSUE TITLE
React yarn installation instructions missing packages

### ISSUE THREAD

**Issue by josephmarkus** [FortAwesome/Font-Awesome#18939]
If you go to https://fontawesome.com/v5/docs/web/use-with/react#get-started

And click `yarn`

It says that you should install FontAwesome as `yarn add @fortawesome/fontawesome-free`

Instead, it should say `yarn add @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome`

Without additional packages, it doesn't run

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

Let's assign @talbs

**Comment by talbs** [comment]
Thanks for letting us know about this issue with v5's React set up docs, @josephmarkus. We've got a fix with your good suggestions going and should have that on fontawesome.com shortly.

**Comment by talbs** [comment]
Okay, folks. We've got those docs updated with the great suggestions. I've also added `yarn` specific instructions for how to add additional styles on that page as well - https://fontawesome.com/v5/docs/web/use-with/react#get-started.

Thanks again for the help and please shout if anything else seems out of place on fontawesome.com
