### ISSUE TITLE
Icon request: c-sharp

### ISSUE THREAD

**Issue by Vedbhagat** [FortAwesome/Font-Awesome#18948]
c-sharp is a programing language.
#18805

**Comment by aethior** [comment]
Hi @nick,

Duplicate of #8365.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
Hi @Vedbhagat,

Duplicate of #8365.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala
