### ISSUE TITLE
Typo: fo"r"tawesome

### ISSUE THREAD

**Issue by ywbird** [FortAwesome/Font-Awesome#18944]
In many of documents in installing npm packages `fontawesome` is `fortawesome`.
![image](https://user-images.githubusercontent.com/83404333/164905153-3ba7133b-bc4d-4218-b9e7-f8f8ed0daffd.png)
![image](https://user-images.githubusercontent.com/83404333/164905841-c3a3c400-958f-4773-8f44-f007fbb0f7b5.png)

Its all over the whole documents I can't tell it one by one.
(It looks like every `fontawesome` in side of code block is `fortawesome`)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Apologies for the confusion, but this is not a typo, the organization name and the package scope on NPM is actually `foRtawesome`

https://twitter.com/fontawesome/status/420609150360375296

Hope it helps

Closing here
