### ISSUE TITLE
Enhancement: Differences between 'wine-glass' and 'wine-glass-empty'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18949]
There is a small inconsistency (almost imperceptible) between the two glasses.
Check the base (floor) and the stem of the wine glasses.

The work of the FA team is wonderful.
These details only strive for perfection.

![wineglass](https://user-images.githubusercontent.com/1769227/164957793-c2f48db2-b438-468b-94b9-c4279370c4c2.gif)

**Comment by tagliala** [comment]
Good find, thanks

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
This has been fixed in our upcoming 6.3 release.
