### ISSUE TITLE
Font awesome duotone icon broken

### ISSUE THREAD

**Issue by diesl** [FortAwesome/Font-Awesome#18945]
It looks like the Font Awesome Duotone Icon is broken on the website
https://fontawesome.com/icons/font-awesome?s=duotone

![image](https://user-images.githubusercontent.com/3629547/164944595-e093091d-3486-46f4-a4d7-09e534f59ee0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

This is a known issue, they are broken just in the documentation

http://jsfiddle.net/tagliala/2s78abqk/17/

Closing as a duplicate of #18931

**Comment by diesl** [comment]
Ah, sorry for the duplicate. My previous search did not show appropriate results...
