### ISSUE TITLE
Add 'fa-knife' and 'fa-knife-kitchen' to the 'household' category

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18946]
I think [fa-knife](https://fontawesome.com/icons/knife) and [fa-knife-kitchen](https://fontawesome.com/icons/knife-kitchen) icons should be part of the `household` category.
Similar to [fa-fork](https://fontawesome.com/icons/fork), [fa-spoon](https://fontawesome.com/icons/spoon) or [fa-chopsticks](https://fontawesome.com/icons/chopsticks) icons.

Regards.

**Comment by sensibleworld** [comment]
This will be in the next release.
