### ISSUE TITLE
[DO NOT +1] Food Icon Categories

### ISSUE THREAD

**Issue by AndreiEzhov** [FortAwesome/Font-Awesome#1895]
I would love some food icons. The knife and fork are great, but it would be nice to have icons for different types of food.

Off the top of my head, I'm thinking food groups like: 
- icon-food-grains, 
- icon-food-vegetable, 
- icon-food-meat (seafood, poultry, beef, pork) 
- icon-food-dairy, 
- icon-food-fruit, 
- icon-food-pasta. 
  I could go on for a long time.

Also some classifications of food, like:
- icon-food-healthy ([carrot](https://github.com/FortAwesome/Font-Awesome/issues/1499)), 
- icon-food-junk ([hamburger](https://cdn3.iconfinder.com/data/icons/line/36/burger-512.png)), 
- icon-food-dessert ([ice-cream](http://st.depositphotos.com/1010754/1959/v/950/depositphotos_19592409-Ice-cream-icons.jpg)), 
- icon-food-dinner (a plate or something?), and 
- icon-food-snaks (like a [bon-bon](https://cdn0.iconfinder.com/data/icons/cosmo-food-2/40/candy_2-128.png)).

Not sure about the naming-scheme. What thinks?

---

edit by @tagliala

Groups:
- icon-food-grains: Wheat/spike/sheaf #2405
- icon-food-vegetable: Carrot #1499
- icon-food-meat #6510
- icon-food-soup: ?
- icon-food-fish: Fish #2722
- icon-food-dairy: Milk? Cheese? #3663 #8046
- icon-food-fruit: Apple #2979 
- icon-food-pasta: ?
- icon-food-pizza: Pizza #4493

Classification:
- Healthy: Carrot #1499
- Fast food: Hamburger #1961 
- Dessert: Ice Cream #1988
- <s> icon-food-dinner</s> [Cutlery](http://fortawesome.github.io/Font-Awesome/icon/cutlery/)
- icon-food-snacks Lollipop or candy? cookie #2845

**Comment by tabacha** [comment]
+1

**Comment by WaSa42** [comment]
+1

**Comment by tagliala** [comment]
Sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here

**Comment by kris** [comment]
With the number of food related sites (restaurants, recipes, etc), I find it hard to believe that food icons are specific to a field, yet a space shuttle and dirt bike icon are not.

**Comment by tagliala** [comment]
@kris restaurant icon would be fine, recipe icon would also be fine

Individual requests like #1499  #2979 are still welcomed, I need to switch down huge sets that are hard to manage and implement, sorry

**Comment by davegandy** [comment]
@kris You'll notice there are a scattered few icons of certain topics (including a few food-related icons). If you absolutely need a certain icon, you can email me and we'll figure something out. :)

**Comment by tagliala** [comment]
btw I think that 5 (five) icons about food categories would be a nice addition to the core

icon-food-healthy (carrot) --> #1499 (also for veg*)
icon-food-junk (hamburger) --> #1961 
icon-food-dessert (ice-cream) --> #1988
icon-food-dinner (a plate or something?) <-- example needed
icon-food-snaks (like a bon-bon) --> new request needed (candy, lollipop)

**Comment by kris** [comment]
@davegandy thanks for the heads up, I might do that soon. @tagliala That would work, or even just having an icon to represent the basics, eg: kosher, gluten-free, carb-free, etc, since they are most common across all recipe/food sites.

**Comment by Chibuzo** [comment]
+1
A generic food. Something like a flat plate, with a cover plate on top will serve a lot of purposes.

**Comment by tagliala** [comment]
Reopening here.

**Please do not request new icons related to food, the purpose of this thread is to improve the request and get a generic tiny subset of food related icons into FA**

I'm going to edit the first post and link to related individual requests

**Comment by michaelminter** [comment]
+1

**Comment by tagliala** [comment]
please do not +1 this request.

help me identifying missing icons or unsubscribe if you are not interested, thanks!

**Comment by G-Driver** [comment]
@kris here a request for gluten free icon https://github.com/FortAwesome/Font-Awesome/issues/2405

**Comment by AndreiEzhov** [comment]
Awesome. 

I do think there should be some classifications of meat, especially if we're going to differentiate between "meat" and "fish". There's already the symbolic animals request: https://github.com/FortAwesome/Font-Awesome/issues/5927, the generic animals request: https://github.com/FortAwesome/Font-Awesome/issues/957 and the domestic animals request: https://github.com/FortAwesome/Font-Awesome/issues/5703, so there's some re-use possible here. Bovine (https://github.com/FortAwesome/Font-Awesome/issues/1122 and https://github.com/FortAwesome/Font-Awesome/issues/4166) works for beef, pig works for pork, rooster works for poultry, rabbit could work for game.

I think we should try to stay away from specific "dishes", like fried egg https://github.com/FortAwesome/Font-Awesome/issues/6019, spaghetti https://github.com/FortAwesome/Font-Awesome/issues/4343
and hotdog https://github.com/FortAwesome/Font-Awesome/issues/4291 unless they're can be used for multiple purposes.

**Comment by latiosthinh** [comment]
+1

**Comment by stevschmid** [comment]
Please consider adding a pistachio icon as well.

**Comment by mittalabhas1** [comment]
Any updates on this?

**Comment by martingg88** [comment]
+1

**Comment by ChefSQL** [comment]
+1

**Comment by G-Driver** [comment]
@stevschmid you have to start a new request

**Comment by tagliala** [comment]
trying to put `[DO NOT +1]` at the start of the title

**Comment by laynx** [comment]
1+

**Comment by trybowski** [comment]
+1 for “generic food” icon

**Comment by tagliala** [comment]
@trybowski sorry, I cannot accept upvotes for this request.

Generic food: http://fortawesome.github.io/Font-Awesome/icon/cutlery/
If you have something different in mind, please +1 the proper request or start a new request following our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by oriadam** [comment]
IMO this is the best icon for icon-food-vegan:
http://images.sasongsmat.nu/vegetarianmark/vegetarian-mark.svg

preview:
 ![](http://rachot.cz/wp-content/uploads/2017/05/LogoVegan-150x150.jpg)

**Comment by YLAG** [comment]
Banana!!

![afbeelding](https://user-images.githubusercontent.com/5198450/29968981-65654c84-8f1e-11e7-9cd8-2cd2361b6f54.png)

**Comment by stevschmid** [comment]
That is one gorgeous banana.

**Comment by castoldi** [comment]
+1

**Comment by Wingo5315** [comment]
Please add some food icons!

**Comment by madivad** [comment]
I'm not sure why this is titles as a "do not +1" 
* is it clickbait? 
* what is the intent? 
* it should be indicated in the message.

What I have done is gone through and clicked on the most relevant linked issues to what I'm looking for and added my thumbs up (I am guessing that is the original intent of this thread?)

This is a big thread with lots of references (which is great), it would be more beneficial if the links provided in the comments could be added to the top message.

**Comment by tagliala** [comment]
Closing here, we have a food category:
https://fontawesome.com/icons?d=gallery&c=food

Upvotable Individual requests: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+sort%3Acomments-desc+label%3A%22food+%28category%29%22
