### ISSUE TITLE
Enhancement: Differences between 'clipboard' and 'clipboard-question' 

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18957]
![clipboard-01](https://user-images.githubusercontent.com/1769227/165144674-1493c162-268b-4e17-9fa2-a46c22b050a3.gif)

![clipboard-02](https://user-images.githubusercontent.com/1769227/165144682-7dcf7b71-0282-469b-97cf-7b68cc8249a0.gif)

**Comment by sensibleworld** [comment]
Fixed in 6.4.0
