### ISSUE TITLE
Bug: spider and spider-black-widow slightly different

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#18950]
Similarly  to #18949

Fast switch between:
- https://fontawesome.com/icons/spider?s=solid
- https://fontawesome.com/icons/spider-black-widow?s=solid

At big sizes, you can notice that spider legs are a little bit different and spiders seem moving 😨😨😨 😱 😱 😱

**Comment by aethior** [comment]
>At big sizes, you can notice that spider legs are a little bit different and spiders seem moving 😨😨😨 😱 😱 😱

![spider](https://user-images.githubusercontent.com/1769227/164979093-df126e8b-8ef8-441e-9ab9-6689c82e9079.gif)

**Comment by sensibleworld** [comment]
I have a fix in the works for our next release.
