### ISSUE TITLE
Enhancement: Differences between 'glass-empty' and 'glass-water'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18952]
To be honest I don't know if this is a bug or expected behavior for `glass-water` and `glass-water-droplet` icons.
There are also differences between the `solid` and the `duotone` versions (this is unusual).

![glass](https://user-images.githubusercontent.com/1769227/164996637-a252b746-0e0e-44fd-9d9b-358090c6eb3d.gif)
![duotone](https://user-images.githubusercontent.com/1769227/164996639-51f778f5-c894-44bc-a795-d9a8487ce3d5.gif)

**Comment by sensibleworld** [comment]
These have been updated to be more consistent.
