### ISSUE TITLE
Keep one icon from v5 and use v6 (for dashboard icon)

### ISSUE THREAD

**Issue by lenamtl** [FortAwesome/Font-Awesome#18954]
Hi, 

I'm in process to migrate from v5 to v6
I'm using tachometer / gauge and the icon is very different since v6 this is now completely round.
So is there a way to use Fontawesome v6 and use the v5 icon only for this icon?

https://fontawesome.com/v5/icons/tachometer-alt?s=solid
https://fontawesome.com/v6/icons/gauge-high?s=solid

Hope you will readd the shape as an extra icon alternative.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

With a Pro Kit, you can customize it and add the version from V5

If you are using the SVG Framework, customization is still easy and possible: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by lenamtl** [comment]
Hi,

I'm still using v4 for my application.
I do have v5 pro license but never had the time to switch, at the moment I'm a template migration process.
I'm not using the SVG framework at the moment but your solution seems viable.

Other question about font compatibily & look and feel font size / font weight migration.
For example I'm using v4 and the font size was set to `font-size: inherit;`  almost everywhere.
What would you recommend for the upgrade to keep as much as possible the same look. 

At the moment by defaut with the free icon in v6 with shim icon are bigger or bolder compare to v4.
Does the pro add something that can solve the problem (maybe using the thinner icon could be an option).
Any recommendation is welcome

Thanks

**Comment by tagliala** [comment]
> At the moment by defaut with the free icon in v6 with shim icon are bigger or bolder compare to v4.

Apologies for the late reply

In Font Awesome 5+, the default font size changed from 14px to 16px. Other Pro styles will have the same behavior, thin in particular

You can still change the default size back to 14px, but icons will not look pixel perfect. SVG framework will help
