### ISSUE TITLE
Enhancement: Differences between 'shield' and 'shield-*'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18955]
All `shield-*` icons need a revision.
There are a little differences between `6.0.0` and `6.1.0` icons.

![shield-01](https://user-images.githubusercontent.com/1769227/165142484-7df0d15e-77cd-47f0-89e2-871f04721462.gif)

![shield-02](https://user-images.githubusercontent.com/1769227/165142493-2ba9dd67-30ec-4339-9c1a-400c38ce988d.gif)

**Comment by sensibleworld** [comment]
Fixed in 6.4.0
