### ISSUE TITLE
Confused newbie - please help :)

### ISSUE THREAD

**Issue by katielola** [FortAwesome/Font-Awesome#18966]
I'm having a slight problem - please see screenshots. I'm trying to add an icon next to 'Confidence' but it just isn't working. 'Training' and 'Community' were fine, but I just can't get this to work, even when I create a brand new block.

I'm using Elementor inside WP.

Please could you advise?

![Screen Shot 2022-04-25 at 3 01 29 pm](https://user-images.githubusercontent.com/104492316/165474274-955bfdfc-51da-4361-ae2d-3690626ed66b.png)
![Screen Shot 2022-04-25 at 3 03 05 pm](https://user-images.githubusercontent.com/104492316/165474281-66c4ba3e-fe52-48ec-a175-5872a237781c.png)
![Screen Shot 2022-04-25 at 5 58 57 pm](https://user-images.githubusercontent.com/104492316/165474296-75053a5a-531e-4f9c-8f6c-c999345b8db0.png)
?

**Comment by pixiekat** [comment]
Are you using Font Awesome Free or do you have a licence for Font Awesome Pro? To use icons from the pro pack, you need a pro licence.

**Comment by katielola** [comment]
Oh fantastic - that makes sense now thank you! I use Free, but didn't realise I was trying to use  a Pro icon. Thank you :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Glad you solved

Closing here
