### ISSUE TITLE
Icon request: instagram-share

### ISSUE THREAD

**Issue by m-charchit** [FortAwesome/Font-Awesome#18967]
Hi, 
Please add the instagram share icon.

Thank You

![image](https://user-images.githubusercontent.com/77086901/165516813-53a2ac1d-6804-41f0-92e4-4320cd4f116f.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have https://fontawesome.com/icons/paper-plane?s=solid and https://fontawesome.com/icons/paper-plane-top?s=solid for Pro users

Given that the regular style is just one of the possible styles and this icon will look like a rotated version of `paper-plane-top`,  could you please clarify the use case for this icon?

**Comment by m-charchit** [comment]
Thanks for the the paper-plane icon. I was looking for the same. No need to add this icon.
