### ISSUE TITLE
Enhancement: Differences between 'file' and 'file-*'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18965]
![file_01](https://user-images.githubusercontent.com/1769227/165436753-2b8169ad-a0e5-424e-b3d3-02f27b2cb44e.gif)
![file_02](https://user-images.githubusercontent.com/1769227/165436756-253d8942-9cad-4873-be35-12d0456c6ae7.gif)
![file_03](https://user-images.githubusercontent.com/1769227/165436758-d64150af-d77a-4006-b316-08f66295fe0d.gif)

**Comment by sensibleworld** [comment]
This should be fixed in 6.4.0
