### ISSUE TITLE
Enhancement: Differences between 'bowl-chopsticks' and 'bowl-chopsticks-noodles' 

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18975]
Check also the little differences between the `SOLID` and `DUOTONE` versions.

![bowl-chopsticks](https://user-images.githubusercontent.com/1769227/165926564-6e6a941c-e609-43c4-8808-004e2a8ce488.gif)

![solid-duotone](https://user-images.githubusercontent.com/1769227/165928143-006391ed-faf7-47a5-8cc2-b36acd0b1eac.gif)

**Comment by sensibleworld** [comment]
These should be more consistent now.
