### ISSUE TITLE
Enhancement: Differences between 'lungs' and 'lungs-virus'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18972]
![lungs](https://user-images.githubusercontent.com/1769227/165848063-2588f82c-13fd-4702-a677-4e1e2d507ebb.gif)

**Comment by sensibleworld** [comment]
This is due to how an SVG gets redrawn during the import process. We'll be doing a full re-draw pass at all of the regular icons soon which should hopefully fix this (and other similar issues).
