### ISSUE TITLE
Icons in 4,7 changed?

### ISSUE THREAD

**Issue by avduo** [FortAwesome/Font-Awesome#18976]
I know these are old, but have been using these of these for a project, 

Search and window close icons seem to be not correct?

[See site here](https://fontawesome.com/v4/icons/)

Also noticed search minus, search plus, sign in, sign out, seem to have all been changed to currencies?

Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I didn't get this question

![image](https://user-images.githubusercontent.com/556268/166038879-1f8b74d7-a192-4c6a-8ef6-01c231aa62d3.png)

Do you see something different?

**Comment by avduo** [comment]
That's interesting if you're on 4.7

mine shows [link to screenshot](https://mega.nz/file/VKIT3AhR#vPK6IuVVdwdSowulabfQhqQBoXF9Yl2sASyWUBF4Ngc)

**Comment by tagliala** [comment]
Can't replicate.

Could you please check:
- in incognito, without extensions enabled
- if on your system there is a different version of Font Awesome installed having priority. In this case, uninstall it
- that there are no errors in the development console of your browser (except for `Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/jsdelivr-rum/1.5/jsdelivr-rum.min.js'`)

If the above does not work, please provide:
- browser and version
- os and version

**Comment by avduo** [comment]
Ok seems to work in incognito without changing anything, tried clearing cookies.

I've not installed any version of Font awesome in windows 10  21h2 using chrome Version 100.0.4896.127 (Official Build) (64-bit)

So what are the next steps to resolve this.
Thanks for your help with this.

**Comment by tagliala** [comment]
> Ok seems to work in incognito without changing anything, tried clearing cookies.

If it works in incognito, please check that there aren't third party browser extensions or settings that may cause this issue

**Comment by avduo** [comment]
Thanks for the response looks like it's a conflict with => File Converter - By Online-Convert.com...

**Comment by tagliala** [comment]
Is it possible that that extension uses its own version of Font Awesome?

**Comment by schtorch** [comment]
Hi there, thank you for your report, we have fixed the issue. A new release of our Chrome extension is available.
