### ISSUE TITLE
Icon request: icon-medal (award / honour)

### ISSUE THREAD

**Issue by claudchan** [FortAwesome/Font-Awesome#1898]
Can request icons for general type like for awards and medals?

**Comment by Spadbob** [comment]
+1

**Comment by s1doryak** [comment]
+1

**Comment by s1doryak** [comment]
Example
![medal-with-star-and-ribbon_318-9647](https://cloud.githubusercontent.com/assets/7103375/5736285/2baa76ba-9be5-11e4-9015-8bed0a0c0a9e.jpg)

**Comment by lokashur** [comment]
+1

**Comment by christophermoura** [comment]
+1

**Comment by cvsguimaraes** [comment]
+1

**Comment by naaraxi** [comment]
+1

**Comment by angelambrosio** [comment]
+1

**Comment by cpoyraz** [comment]
+1

**Comment by sarukuku** [comment]
+1

**Comment by bridgepub** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by tommyj1112** [comment]
+1

**Comment by psoulier** [comment]
+1

**Comment by danMontague** [comment]
+1

**Comment by jevanlingen** [comment]
+1

**Comment by bakatrouble** [comment]
+

**Comment by romaintb** [comment]
+1

**Comment by zsaffir** [comment]
+1

**Comment by fredjsf** [comment]
+1

**Comment by veturi** [comment]
+1

**Comment by 7aduta** [comment]
+1

**Comment by baronbiosys** [comment]
+4 .. our whole team could use these.

**Comment by andrewvk** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by extra-0** [comment]
+1 for 3 separate icons : gold silver bronze

**Comment by Lynda333** [comment]
+1

**Comment by fareskalaboud** [comment]
+1

**Comment by tonyedwardspz** [comment]
+1

**Comment by dpfahlert** [comment]
+1

![award1](https://cloud.githubusercontent.com/assets/18060386/14034638/4e2c7ea0-f1e2-11e5-8100-b71d48e1b47e.jpg)

**Comment by plopes3000** [comment]
I'd +1 a medal like a military person or hero would receive as opposed to a ribbon or sporting medal. Reference: http://thumb1.shutterstock.com/display_pic_with_logo/971035/383411230/stock-vector-medal-icon-medal-icon-vector-medal-icon-art-medal-icon-eps-medal-icon-image-medal-icon-logo-383411230.jpg

**Comment by charlieholder** [comment]
+1

**Comment by mibamur** [comment]
+1

**Comment by pinchtools** [comment]
+1

**Comment by raymon2683** [comment]
+1

**Comment by nodecode** [comment]
+1

**Comment by joehoughton** [comment]
+1

**Comment by mfdeveloper** [comment]
+1

**Comment by beta3designs** [comment]
+1

**Comment by gventuri** [comment]
+1

**Comment by mnimmagari** [comment]
+1

**Comment by MadTiago** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode characters #222:

- 🏅 [U+1F3C5 Sports Medal](http://emojipedia.org/sports-medal/)
- 🥇 [U+1F947 First Place Medal (gold)](http://emojipedia.org/first-place-medal/) 
- 🥈 [U+1F948 Second Place Medal (silver)](http://emojipedia.org/second-place-medal/)
- 🥉 [U+1F949 Third Place Medal (bronze)](http://emojipedia.org/third-place-medal/)
- 🎖 [U+1F396 Military Medal](http://emojipedia.org/military-medal/) #3641
- 🏆 [U+1F3C6 Trophy](http://emojipedia.org/trophy/) #2778, `fa-trophy`
- 🎀 [U+1F380 Ribbon](http://emojipedia.org/ribbon/) #4246, #3747
- 🏵 [U+1F3F5 Rosette](http://emojipedia.org/rosette/) #4246
- 💮 [U+1F4AE White Flower](http://emojipedia.org/white-flower/)

**Comment by Alaa-Ellethey** [comment]
+1

**Comment by mattes42** [comment]
+1

**Comment by gpatry** [comment]
+1

**Comment by weibangtuo** [comment]
+1

**Comment by thiagogarbazza** [comment]
**+1** 

[In this set] contains a good example of the medal icon. 

[In this set]:http://www.entypo.com/

**Comment by LuisJoseSanchez** [comment]
+1

**Comment by danMontague** [comment]
+1

**Comment by onkarjit** [comment]
+1 Maybe something like:

https://d1yn1kh78jj1rr.cloudfront.net/preview/medal-glyph-icon_zymBHpUu_M.jpg

**Comment by aldric** [comment]
+1

And just to add : trophy is great but ribbon is not the exact same meaning. especially for rankings and comparisons. This issue is open for 3 years so from my end, without any offence :), either you close it and we will never have any ribbon style icon or you make us happy. 
Cheers,
A.

**Comment by podrivo** [comment]
+1

**Comment by rakaalrian** [comment]
+1

**Comment by rakaalrian** [comment]
how can i get the fa medal icon? please help

**Comment by rakaalrian** [comment]
never mind, i use [this](https://icomoon.io/app/#/select)

**Comment by aidan-fitz** [comment]
Yes!

**Comment by choonggg** [comment]
+1

**Comment by joshjGCB** [comment]
+1

**Comment by alsahahari** [comment]
+10

**Comment by lucassmacedo** [comment]
+10
