### ISSUE TITLE
Enhancement: Differences between 'head-side-cough' and 'head-side-cough-slash'

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#18985]
![cough](https://user-images.githubusercontent.com/1769227/166123864-584c8780-2cb9-4b31-af4b-2213eaf1d29b.gif)

![cought-duotone](https://user-images.githubusercontent.com/1769227/166123867-8e14e7ab-355e-455a-9ff4-c36bd3b9c0de.gif)

**Comment by sensibleworld** [comment]
Fixed in 6.4.0
