### ISSUE TITLE
Changed order in the name: user-house circle-info

### ISSUE THREAD

**Issue by Grzesiek23** [FortAwesome/Font-Awesome#19006]
It doesn't work me for 6.1.1 free version.

Works: house-user and info-circle

**Comment by sensibleworld** [comment]
@GrzesiekPasko For the `house-user` icon, you can use both that name and `home-user`. I do not believe there was ever a version that worked using the name `user-house`? And both `circle-info` and `info-circle` should be working. Could you supply an example of where it's breaking for you?

**Comment by tagliala** [comment]
No feedback, closing here but feel free to comment
