### ISSUE TITLE
Icon Request: Kobo

### ISSUE THREAD

**Issue by sbarclay01** [FortAwesome/Font-Awesome#19019]
I'd like to request Kobo be added to the Brands icons. Kobo is another store widely requested by authors for use on websites to sell books.

Here's a sample:

![NicePng_kobo-logo-png_9227572](https://user-images.githubusercontent.com/98122410/167323534-d8b29a92-2f17-46b2-a5a3-65877b0fda3d.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13659, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
