### ISSUE TITLE
Icon request: B&N, Smashwords, and Kobo Brand Icons

### ISSUE THREAD

**Issue by sbarclay01** [FortAwesome/Font-Awesome#19014]
A lot of authors sell books through stores like Barnes & Noble Nook, Smashwords, and Kobo, and they all need website icons. Can you include these in the Brands section?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please open individual requests, one for each brand, having care of:
- search for existing requests before (kobo: #13659), including extended names. Search here: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+label%3A%22brand+icon%22
- add the official website of the requested brand
