### ISSUE TITLE
Icon request: tree-freshener

### ISSUE THREAD

**Issue by jssmtmmns** [FortAwesome/Font-Awesome#19013]
A sort of combo of 'tree' and 'sparkles' with a hang string or hole at the top and a rectangular label at the bottom.
Use case: keepin it fresh.

![image](https://user-images.githubusercontent.com/105083254/167219378-91c8deb2-f9a8-479e-b72b-e45c7c07c3c6.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, we can't use this design

Ref: https://github.com/FortAwesome/Font-Awesome/blob/5.x/CHANGELOG.md#5153---2021-03-16
