### ISSUE TITLE
Icon request: gitlab (update)

### ISSUE THREAD

**Issue by ArnaudLier** [FortAwesome/Font-Awesome#19015]
GitLab's branding has been updated: https://about.gitlab.com/press/press-kit/
Seems like they don't provide outlines anymore:
![New icon](https://about.gitlab.com/images/press/logo/svg/gitlab-icon-1-color-black-rgb.svg)

**Comment by tagliala** [comment]
Hi!

Thanks for the heads-up.

We were already working on this, the new icon will be part of the next release

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/gitlab?s=brands
https://fontawesome.com/icons/square-gitlab?s=brands
