### ISSUE TITLE
Icon Request: icon-crown-king , icon-crown-queen 

### ISSUE THREAD

**Issue by ignaciocarre** [FortAwesome/Font-Awesome#1903]
Fist of all, CONGRATZ!!! this is a realy grate project, you don´t know the time you are saving me, since i´m a developer, not a designer.
Second: it would be nice to have this icons:
icon-crown-king , icon-crown-queen 

![18655305-king-crown-icons](https://f.cloud.github.com/assets/358968/1064926/cb7a9acc-135f-11e3-8624-8e95d735e6a2.jpg)

:)

**Comment by skyepn** [comment]
+1

**Comment by andrkrn** [comment]
+1

![king chrown image](https://cdn0.iconfinder.com/data/icons/online-shopping-3/78/Shopping_icons_vector-11-512.png)

**Comment by ignaciocarre** [comment]
You are awesome! Thanks :)

**Comment by bakatrouble** [comment]
+1

**Comment by lemtzas** [comment]
nice icon

+1

**Comment by jtouza** [comment]
+1

**Comment by kingofkingshf** [comment]
+1

**Comment by staff0rd** [comment]
:+1:

**Comment by miradnan** [comment]
+1

**Comment by Vioner** [comment]
+1

**Comment by RamonSmit** [comment]
:+1:

**Comment by michelevirgilio** [comment]
+1

**Comment by mziii** [comment]
+1

**Comment by nurikabe** [comment]
+1

**Comment by khasky** [comment]
+1

**Comment by enco164** [comment]
+1

**Comment by mcassiano** [comment]
+!

**Comment by jesusignazio** [comment]
+1

**Comment by scfl** [comment]
+1

**Comment by tomoki7** [comment]
+1

**Comment by 00F100** [comment]
+1

**Comment by Daijobou** [comment]
+1 need it for "premium"-users

**Comment by aethior** [comment]
@tagliala Check #486. Related? Duplicate?

**Comment by tagliala** [comment]
fff... 

Let's say I'm going to close this one.

Given that #486 is about a "generic" crown, let's say a king crown, if anyone is interested in a queen crown, please open a new request explaining why it is important to have both. If the reason is about chess, please +1 #1815

**Comment by shde** [comment]
+1

**Comment by iruy** [comment]
So, after 4 years, was this even taken into consideration?

**Comment by 00F100** [comment]
There are several types of crowns, not one crown only! Just this!

**Comment by glossyweb** [comment]
+1

**Comment by 00F100** [comment]
+1

**Comment by Luiz0tavio** [comment]
+1

**Comment by irfan-dahir** [comment]
+1

**Comment by otanim** [comment]
+1

**Comment by dotneet** [comment]
+1

**Comment by mihnsen** [comment]
+1

**Comment by mekela** [comment]
+1

**Comment by tagliala** [comment]
https://fontawesome.com/icons/chess-king?style=solid
https://fontawesome.com/icons/chess-queen?style=solid

🔒
