### ISSUE TITLE
Icon Request: Kotlin

### ISSUE THREAD

**Issue by Martmists-GH** [FortAwesome/Font-Awesome#19034]
Kotlin is a programming language developed by Jetbrains, and should be included as a brand icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #13450, please add a 👍 reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
