### ISSUE TITLE
nine dot icon to open ecosystem widget like on facebook and google

### ISSUE THREAD

**Issue by morgunder** [FortAwesome/Font-Awesome#19051]
is there a nine dot icon like the one that facebook and google use to open their ecosystem widget?  i couldn't find it in the icon search bar.  would like to use it in a current project.

**Comment by tagliala** [comment]
Hi!

Are you looking for https://fontawesome.com/icons/grid?s=solid ?

Or there is a request for a circled version of that icon at #15452, so in this case I'm closing here as a duplicate
