### ISSUE TITLE
Bug: wind-turbine icon is not recognized on Flutter package

### ISSUE THREAD

**Issue by elmar001** [FortAwesome/Font-Awesome#19059]
### Bug description

https://fontawesome.com/icons/wind-turbine - this icon is not recognized on Flutter package. I know naming of the icons is a bit different for Flutter. For example, icon solar-panel is like solarPanel in Flutter. But wind-turbine icon does not work even that style naming. None of them working below:

IconButton(
                                icon: FaIcon(FontAwesomeIcons.wind-turbine,
                                    color: Color.fromARGB(255, 81, 154, 191)),
                                onPressed: () {}),
IconButton(
                                icon: FaIcon(FontAwesomeIcons.windTurbine,
                                    color: Color.fromARGB(255, 81, 154, 191)),
                                onPressed: () {}),

Just noticed, seems like it is same with utility-poll icon as well. This icon also not working on Flutter.

### Font Awesome version

10.1.0

### Application and Operating System

Flutter app environment:
  sdk: ">=2.16.2 <3.0.0"

FontAwesome version:   font_awesome_flutter: ^10.1.0

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> FontAwesome version: font_awesome_flutter: ^10.1.0

font_awesome_flutter is a third-party library not maintained by Font Awesome, please report your issues to https://github.com/fluttercommunity/font_awesome_flutter

Closing here, but feel free to comment and provide more information if I didn't get this request
