### ISSUE TITLE
Icon request: odometer

### ISSUE THREAD

**Issue by one1973** [FortAwesome/Font-Awesome#19052]
Odometer
![Counter48](https://user-images.githubusercontent.com/24562284/169351873-0bd4c56b-dbc3-48d9-bb9c-3184f30ab584.png)

**Comment by one1973** [comment]
![images](https://user-images.githubusercontent.com/24562284/169352285-14f53226-757a-4b86-a761-cda889f430d2.png)
![odometer](https://user-images.githubusercontent.com/24562284/169352291-262eecca-456c-476f-9595-348c475208b1.png)

**Comment by tagliala** [comment]
I remember this is a duplicate, but at the moment I can't find the original request, so I'm leaving this open.

I've also searched for synonyms, @aethior you may have success :)

**Comment by aethior** [comment]
> I've also searched for synonyms, @aethior you may have success :)

Maybe #11089?

**Comment by tagliala** [comment]
Yes, that one :)

The example in the opening post is almost identical, but I think it is not the same thing

Anyway, closing here as a duplicate of #11089
