### ISSUE TITLE
Icon Request: fa-pet-bowl

### ISSUE THREAD

**Issue by Wh1terat** [FortAwesome/Font-Awesome#19061]
Hi,

Quite a corner case request, but I'd like to request an icon of a pet bowl - ideally 2 showing empty or full.

Something like:
![image](https://user-images.githubusercontent.com/1288525/169715413-b6e6a586-d591-4bd7-a17d-92a567394a8f.png)

The request stems from having a smart pet feeder in Home Assistant which utilises FA.

Thanks.

**Comment by aethior** [comment]
Duplicate of #10594.
Regards.

cc/ @tagliala
