### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by ArtemFrontendACTUM** [FortAwesome/Font-Awesome#19069]
@stuartcusackie if you have different projects and just some of them uses FA Pro, you can use per-project `.npmrc` instead of a global one

You can do the opposite if you need FA Free in just some of them

ie: 
```
@fortawesome:registry=
```

should reset the registry to the default one (registry.npmjs.org for npm, registry.yarnpkg.com for yarn). Please also delete your lockfile before running npm install or yarn install with the new repo setting

_Originally posted by @tagliala in https://github.com/FortAwesome/Font-Awesome/issues/13794#issuecomment-514589153_

It solves nothing:
https://github.com/FortAwesome/Font-Awesome/issues/13794#issuecomment-514589153

![image](https://user-images.githubusercontent.com/92377236/170098430-5904b0f8-c429-4fb3-9b19-ec304f411db8.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, I do not understand this issue

Could you please fill out our bug report template at https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+ ?

**Comment by stuartcusackie** [comment]
Hi. My problem is sorted. I wrote that  comment about 3 years ago but I haven't had any problems since.

Thanks for checking!

**Comment by tagliala** [comment]
Sorry, I'm going to close here

@ArtemFrontendACTUM feel free to open a new issue with a step to step guide to reproduce, with as many details as possible (except for sensitive ones like email or Font Awesome Pro token) so we can understand the issue and try to help

Please also note that as Font Awesome Pro developer you can ask for custom support at hello@fontawesome.com
