### ISSUE TITLE
Icon request: sniper-rifle, assault-rifle, shotgun, machine-gun, submachine-gun

### ISSUE THREAD

**Issue by casually-creative** [FortAwesome/Font-Awesome#19077]
### Use case

There are quite a bunch of melee weapon icons, but not of firearms. This would be beneficial for anything covering shooter games.

Thinking of sniper rifles (also requested by #3560), assault rifles, shotguns, machine gun, submachine gun, ..

Here is a list of all different firearms. Don't think we need them all, just the most popular ones, or the most used ones in video games: https://www.britannica.com/topic/list-of-weapons-2058724#ref333237

### Example image

![image](https://user-images.githubusercontent.com/5587999/170614498-a180e138-f92a-4223-b22c-cdd6ae6b9351.png)
![image](https://user-images.githubusercontent.com/5587999/170614551-67295577-1d5e-4c4b-9b24-dbcaa3d8e5e7.png)
![image](https://user-images.githubusercontent.com/5587999/170614572-32f0e599-cee4-4278-a022-1ae1686b68c3.png)
![image](https://user-images.githubusercontent.com/5587999/170614803-01ff73da-75f0-4bfd-b667-40cfc9ba6dfb.png)
![image](https://user-images.githubusercontent.com/5587999/170614688-e9df8ace-09fa-44d9-8844-bbf667222aca.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request. Please make sure to provide a good title and an example.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
