### ISSUE TITLE
Broken links in Angular documentation.

### ISSUE THREAD

**Issue by victorwvieira** [FortAwesome/Font-Awesome#19089]
There are some broken links in the Angular documentation (v6.1.1) https://fontawesome.com/docs/web/use-with/angular.
Follow below what I think should be the correct link:

- [the SVG+JS method of Font Awesome](https://fontawesome.com/docs/web/dig-deeper/webfont-vs-svg#svg-js)
- [Kit](https://fontawesome.com/docs/web/setup/use-kit)
- [self-hosting](https://fontawesome.com/docs/web/setup/host-yourself/webfonts)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm, let's assign @talbs

**Comment by talbs** [comment]
Hi, @victorwvieira! Thanks for bringing this to our attention.

I've got a PR that updates our Angular Docs with your suggestions. That should be merged in and pushed to fontawesome.com shortly. I'll let you know when that's live.

Please keep the good recommendations coming!

**Comment by victorwvieira** [comment]
Thank you @talbs

**Comment by talbs** [comment]
Thank you for the heads up. Those linkies on https://fontawesome.com/docs/web/use-with/angular should be less stinky now.
