### ISSUE TITLE
Icon request: square-half-stroke & square-half-stroke-diagonal

### ISSUE THREAD

**Issue by 1-0-1** [FortAwesome/Font-Awesome#19099]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and provide examples for the two requested icons

Closing here, but feel free to comment if I've missed something
