### ISSUE TITLE
Bug: Missing icons in parse function

### ISSUE THREAD

**Issue by simecek-m** [FortAwesome/Font-Awesome#19096]
### Bug description

I'm using FontAwesome library (v6.1.1) with React and I initialized it by [documentation ](https://fontawesome.com/docs/web/use-with/react/add-icons#add-icons-globally)like this:
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';

library.add(fas);
```
When I want to use icon I can just call it by name like this:
```
<FontAwesomeIcon icon="rocket" />
```
But I found out that I'm getting `{ "prefix": "fas", "iconName": null }` error for few specific icons:

>backward-fast
forward-fast
person-falling
person-falling-burst
truck-fast

When I was trying to figure out, what's going on I found out that `parse.icon('backward-fast')` returns `{prefix: "fas", iconName: null}` but `parse.icon({ prefix: "fas", iconName: "backward-fast" })` returns correct icon. So I'm guessing there are missing mappings for those 5 icons in the parse function when you call it with iconName?

Am I doing something wrong? Thanks for clarification.

### Reproducible test case

https://codesandbox.io/s/missing-font-awesome-icons-61dc3d?file=/src/App.js

### Font Awesome version

v6.1.1

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

Chrome 102 on Windows 11

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
@robmadole any thoughts?

**Comment by simecek-m** [comment]
I've just tried to test this and in [v6.3.0](https://github.com/FortAwesome/Font-Awesome/releases/tag/6.3.0) this bug should be resolved. Closing.

**Comment by tagliala** [comment]
Thanks for the heads-up
