### ISSUE TITLE
'circle-info' not working

### ISSUE THREAD

**Issue by BTMDesign** [FortAwesome/Font-Awesome#19090]
The code 'circle-info' is not working. Seems to only pick up the 'info' part of the text.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

Closing here, but feel free to comment if I've missed something
