### ISSUE TITLE
Unable to compile scss with older Ruby SASS Compiler (fa 6.1.1)

### ISSUE THREAD

**Issue by schmidetzki** [FortAwesome/Font-Awesome#19097]
Compiling the scss code gives the following error:

    Sass::SyntaxError: Invalid CSS after "...style-family }"": expected "{", was ";"

The reason is the following code in solid.scss (and others) defining css variables:

    :root, :host {
      --#{$fa-css-prefix}-font-solid: normal 900 1em/1 "#{ $fa-style-family }";
    }

An easy fix would be to define and use a separate sass variable like this:

    :root, :host {
      $fa-css-var-prefix: --$fa-css-prefix;
      #{$fa-css-var-prefix}-font-solid: normal 900 1em/1 "#{ $fa-style-family }";
    }

This would help users that are not able to update their ruby sass compiler for some reason (like me).
I patched my fa version that way and it works now. But I have to do this on every update in the future.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Which version of Ruby Sass this issue is related to?

**Comment by schmidetzki** [comment]
Hi,

> Am 02.06.2022 um 22:18 schrieb Geremia Taglialatela ***@***.***>:
> Which version of Ruby Sass this issue is related to?
> 
We use JRuby.
As far as I can see the sass-gems is version 3.1.19

Regards
Wolfgang Schmidetzki

**Comment by tagliala** [comment]
> sass-gems is version 3.1.19

Hi, sass 3.1.19 has been released in 2012:

[3.1.19](https://rubygems.org/gems/sass/versions/3.1.19) - May 26, 2012 (227 KB)

I cannot replicate this issue with Ruby Sass 3.7.4, released in 2019

@robmadole I would like to close this as wontfix, any thoughts?

**Comment by schmidetzki** [comment]
I Know that this ruby-gem version is old but we can't change it because it's part of a larger architecture ...
And because the suggested fix is simple and effects only a few lines of code ... 

Anyway. I tried to switch to LESS.
But also the .less files does not compile using the actual version 1.17.2 of less4j:

    no viable alternative at input '2xs' in abstract mixin or namespace (which started at 27:1)   
     27: .fa-sizes() {
     28:   2xs                   : @fa-size-scale-2xs;
     29:   xs                    : @fa-size-scale-xs;

**Comment by tagliala** [comment]
Sorry closing here
