### ISSUE TITLE
org.webjars:font-awesome:6.1.1 not available on maven-central

### ISSUE THREAD

**Issue by ursjoss** [FortAwesome/Font-Awesome#19092]
I would like to consume `org.webjars:font-awesome:6.1.1` from maven-central. Currently the latest version available there is 6.1.0 only.

Please publish version 6.1.1 to maven-central. Or point me to where to file this request, if it belongs somewhere else. Thanks a lot :-)

**Comment by solomax** [comment]
@ursjoss maybe the issue should be created here https://github.com/webjars/font-awesome :)

**Comment by ursjoss** [comment]
Yep, that sounds very fitting. Sorry for the noise over here...
