### ISSUE TITLE
Icon request: yahoo

### ISSUE THREAD

**Issue by Gannn0047** [FortAwesome/Font-Awesome#19107]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yahoo icon is already available:
- https://fontawesome.com/icons/yahoo?s=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
