### ISSUE TITLE
Icon request: fa-ghost-slash

### ISSUE THREAD

**Issue by AlexAnimateMp4** [FortAwesome/Font-Awesome#19119]
### Example image

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 567"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M 309.95 461.5 Q 314.75 456.05 321.95 456.05 329.2 456.05 333.95 461.5 L 374.6 507.3 Q 379.3 511.95 385.9 511.95 392.55 511.95 397.2 507.3 L 420.45 481.2 130 253.55 130 464 Q 130 469.15 132.85 473.2 135.5 476.95 139.9 478.75 144.25 480.55 148.75 479.75 153.65 478.9 157.25 475.25 L 182.25 456.75 Q 187.2 453 193.4 453.65 199.6 454.3 203.75 459 L 246.75 507.3 Q 251.45 511.95 258.05 511.95 264.65 511.95 269.35 507.3 L 309.95 461.5 M 513.95 191.95 Q 513.95 152.15 498.35 115.95 483.25 81 455.85 54.3 428.35 27.6 392.9 13.5 356.1 -1.1 316.1 0.1 277.55 1.25 242.7 17.85 209.3 33.8 183.65 61.8 158.25 89.5 144.3 124.85 141.4 132.15 139.15 139.55 L 38.8 60.9 Q 30.95 54.75 21.1 55.95 11.2 57.15 5.1 64.95 -1 72.8 0.2 82.65 1.05 89.65 5.2 94.8 5.75 95.15 6.3 95.6 L 598.25 559.6 Q 600.5 561.35 602.2 563.4 609.6 568.65 618.85 567.55 628.75 566.35 634.9 558.55 641 550.75 639.8 540.9 638.6 531 630.75 524.9 L 513.95 433.35 513.95 191.95 M 354 191.95 Q 354 178.75 363.4 169.35 372.75 159.95 386 159.95 399.2 159.95 408.6 169.35 418 178.75 418 191.95 418 205.2 408.6 214.55 399.2 223.95 386 223.95 372.75 223.95 363.4 214.55 354 205.2 354 191.95 M 226.9 191.95 Q 226.9 178.8 236.15 169.35 245.4 159.95 258 159.95 270.7 159.95 280.25 169.35 290 178.9 290 191.95 290 205.2 280.6 214.55 271.2 223.95 258 223.95 244.85 223.95 235.85 214.55 226.9 205.3 226.9 191.95 Z"/></svg>
```
![ghost-slash](https://user-images.githubusercontent.com/48261899/173205326-f4fe2916-e5af-454d-8d7c-603e3e633c4b.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/151/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
