### ISSUE TITLE
Icon Request: icon-acrobat-reader

### ISSUE THREAD

**Issue by adieunix** [FortAwesome/Font-Awesome#1911]
Please add for icon acrobat reader

**Comment by DiogoFontes** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by ptkdev** [comment]
+1

**Comment by isteiger** [comment]
issue should be closed as of #1970 has everything

**Comment by tagliala** [comment]
Can't fix

https://github.com/FortAwesome/Font-Awesome/blob/5.x/CHANGELOG.md#5150---2020-09-28

Closing here
