### ISSUE TITLE
Icon Request: fa-icon-dividesymbol

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#19111]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Divide icon is already available:
- https://fontawesome.com/icons/divide?s=solid
- (or https://fontawesome.com/icons/slash-forward?s=solid)

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
