### ISSUE TITLE
Icon request: Outlook, Outlook Express, Gmail, Hotmail, company, return item, special

### ISSUE THREAD

**Issue by Gannn0047** [FortAwesome/Font-Awesome#19116]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Please also make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here
