### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Zak99099** [FortAwesome/Font-Awesome#19112]
[23](https://vimeo.com/718788536/2a8e8d0e33)

**Comment by Zak99099** [comment]
23

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Closing here, but feel free to comment if I've missed something
