### ISSUE TITLE
Icon Request: icon-for-sale-sign

### ISSUE THREAD

**Issue by RHochreuter** [FortAwesome/Font-Awesome#1912]
Hi,

I have really been missing an icon for selling or renting out a property.

My idea is that it should look like this:
![](http://playground.devx.dk/icon-sign.png)

**Comment by daven009** [comment]
+1 if include whole bunch of facility icons like airbnb would be really cool

**Comment by haisum** [comment]
+1

**Comment by coffeelady** [comment]
+1

**Comment by pieterjd** [comment]
+1 yes please :+1:

**Comment by rodchenkov** [comment]
+1

**Comment by eli007** [comment]
:+1:

**Comment by heathbo** [comment]
+1

**Comment by boryn** [comment]
+1

**Comment by YaroslavNuznenko** [comment]
+1

**Comment by empierre** [comment]
+1

**Comment by Wairangu** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/sign?style=solid
