### ISSUE TITLE
[Hosted Font Awesome Free 6.1.1] file-pen, clipboard-user, file-circle-plus showing box with X

### ISSUE THREAD

**Issue by parkerscobey** [FortAwesome/Font-Awesome#19134]
Self hosted Sass configuration. I see the unicode for the icons in `_variables.sass`. Other icons are working fine.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Self hosted Sass configuration. I see the unicode for the icons in `_variables.sass`. Other icons are working fine.

I'm thinking that font files (woff / woff2) may have not be updated, or they are cached on the browser causing it to use the old versions

Sorry but there are too few details to debug this issue, please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

In this case, a reproducible test case would help

Closing here, but feel free to comment if I've missed something
