### ISSUE TITLE
Bug: Wrong code for Linkedin square icon

### ISSUE THREAD

**Issue by Mourat** [FortAwesome/Font-Awesome#19133]
### Bug description

Hello.
I see wrong html code for Linkedin square icon in 5 and 6 versions.

### Reproducible test case

https://fontawesome.com/icons/linkedin?s=brands

### Screenshots

![image](https://user-images.githubusercontent.com/2405030/173842754-c9c086e2-8fd4-45f7-ae5c-ed44a1ca4fa0.png)

### Font Awesome version

v6 v5

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome 102

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Actually the code is correct. `fa-linkedin-square` is the class name from V4, please double check the syntax used in your application

### v6

As per documentation at https://fontawesome.com/icons/linkedin?s=brands, the proper syntax for V6 is

```html
<i class="fa-brands fa-linkedin"></i> <!-- V6 syntax, only works on V6 -->
```

The old V5 syntax also works on V6

```html
<i class="fab fa-linkedin"></i> <!-- V5 syntax, works on V5 and V6 -->
```

Demo: https://jsfiddle.net/tagliala/bfa6uhse/152/
V6 with V5 syntax: https://jsfiddle.net/tagliala/bfa6uhse/154/

### v5

Docs: https://fontawesome.com/v5/icons/linkedin?s=brands

Syntax

```html
<i class="fab fa-linkedin"></i> <!-- V5 syntax, works on V5 and V6 -->
```

Demo: https://jsfiddle.net/tagliala/ch8wo2k6/1/

```

Closing here, but feel free to comment
