### ISSUE TITLE
Icon request: multiple icons

### ISSUE THREAD

**Issue by Minakie** [FortAwesome/Font-Awesome#19151]
Hello everyone!

I would like to suggest a few icons that I noticed were missing:
- ferret
- maze
- mouse (the animal, not the peripheral)
- pixie/fairy
- raccoon
- thief

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

In example - please search for others - mouse has been requested at #14246. Please add a 👍🏼 reaction to that request

If there isn't already a request for the icon you need, feel free to fill out individual [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+), one for each icon

Closing here, but feel free to comment if I've missed something
