### ISSUE TITLE
Ethernet Icon should also be part of the Connectivity category

### ISSUE THREAD

**Issue by clipteez** [FortAwesome/Font-Awesome#19155]
Just a tiny little hint, I was looking for the ethernet icon and couldn't find it under the connectivity category. Turns out it was under the devices category. It should definately also be in the connectivity category.

**Comment by sensibleworld** [comment]
The ethernet icon is now in the connectivity category, as well: https://fontawesome.com/icons/ethernet?s=solid&f=classic
