### ISSUE TITLE
Brand request: fa-rockylinux (Rocky Linux)

### ISSUE THREAD

**Issue by istiak101** [FortAwesome/Font-Awesome#19166]
### Description

Linux distro similar to:

https://fontawesome.com/icons/redhat?s=brands
https://fontawesome.com/icons/centos?s=brands

https://avatars.githubusercontent.com/u/75713131?s=200&v=4

### Official website

https://rockylinux.org/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by brianclemens** [comment]
Icon is available at https://github.com/rocky-linux/branding/tree/main/logo/src

**Comment by brianclemens** [comment]
@istiak101 was this actually added? I'm not seeing it on https://fontawesome.com/leaderboard/released
