### ISSUE TITLE
Icon request: Gas cylinder

### ISSUE THREAD

**Issue by fabien-michel** [FortAwesome/Font-Awesome#19168]
### Use case

Picture a propane or other gas energy source

### Example image

![gas-cylinder-bottle-icon-simple-style-vector-33864447](https://user-images.githubusercontent.com/1167556/177121063-e7ce6a1a-df2a-472e-b280-a58424fde021.jpg)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment]
Duplicate or related to #17574.
Regards.

cc/ @tagliala
