### ISSUE TITLE
Icon request: icon-repeat-all

### ISSUE THREAD

**Issue by vjacheslavravdin** [FortAwesome/Font-Awesome#1916]
An example from iTunes.

![icon-repeat-all](https://f.cloud.github.com/assets/5282451/1073671/08abe076-14ab-11e3-9ba5-dde413be9af5.jpg)

**Comment by Crissov** [comment]
Some apps use an infinity symbol `∞` with arrow-head(s) instead.

Related standard icon:

[![IEC 60417-5557](https://www.iso.org/iobp/graphics/grs/ISO263681_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5557)

**Comment by aethior** [comment]
Hi @vjacheslavravdin!

This icon was added in v5.0.0.
Check https://fontawesome.com/v5.15/icons/repeat

cc/ @tagliala

**Comment by tagliala** [comment]
@aethior thanks for helping out with these requests!

**Comment by tagliala** [comment]
Also, this has been added to the free set in FA6: https://fontawesome.com/v6.0/icons/repeat
