### ISSUE TITLE
Icon request: icon-repeat-one

### ISSUE THREAD

**Issue by vjacheslavravdin** [FortAwesome/Font-Awesome#1917]
An example from iTunes.

![icon-repeat-one](https://f.cloud.github.com/assets/5282451/1073681/5a3a5e86-14ab-11e3-96d5-a9faa0d10927.jpg)

**Comment by Crissov** [comment]
If `fa-repeat-all` from #1916 used the infinity symbol with arrows, this one would not need the index with the digit 1. Also, one or two arrow heads are fine.

Related standard symbols (for actions, not states):

[![IEC 60417-5125A](https://www.iso.org/iobp/graphics/grs/ISO263284_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5125A)
[![IEC 60417-5862](https://www.iso.org/iobp/graphics/grs/ISO263952_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5862)

**Comment by aethior** [comment]
Hi @vjacheslavravdin,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/repeat-1

Regards.

cc/ @tagliala
