### ISSUE TITLE
Icon request: AR (Augmented Reality)

### ISSUE THREAD

**Issue by MarcoNeiko** [FortAwesome/Font-Awesome#19175]
AR (Augmented Reality) icon for 3D objects

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is either a duplicate of #11394 (please add a 👍 reaction to that request, if it is the case) or already addressed as [head-side-goggles](https://fontawesome.com/icons/head-side-goggles?s=solid)

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

You may also be interested in taking a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

Closing here, but feel free to comment if I've missed something
