### ISSUE TITLE
wrong npm and yarn typo command in font awesome doc

### ISSUE THREAD

**Issue by devruhul** [FortAwesome/Font-Awesome#19171]
In set up with react page which you can find font awesome doc all of the npm and yarn commands are like this npm i --save @**fortawesome**/fontawesome-svg-core
isn't fortawesome is the fontawesome? in my project it works with fortawesome. It should be fontawesome if I am wrong please correct me.

**Comment by tagliala** [comment]
Hi!

Apologies for the confusion

`foRtawesome` is correct and it's the name of the npm scope where `foNtawesome` packages are published

Closing here, but feel free to comment and provide more information if I didn't get this request
