### ISSUE TITLE
Bug: Missing certain icons in Chrome, with fix

### ISSUE THREAD

**Issue by MonkeyTrainer12** [FortAwesome/Font-Awesome#19189]
### Bug description

Several icons, **specifically fa-shopping-cart**, would display normally on all browsers **EXCEPT Chrome**.  These font-awesome icons would display normally on ALL other platforms, along with the rest of the font-awesome icon set.

I discovered that the template being used for the site had assigned a default **font-weight** of **500** to all divs in that section of the layout.  When I used CSS to modify the font-weight to either **400**, **600**, or **700**, all font-awesome icons would display in Chrome normally.

ALSO: I always add the following CSS which allows me to load a font-awesome icon within any div without overriding the Font-Family style of that div:

```
.far:before,
.fas:before {
	font-family: "Font Awesome 5 Free" !important; }
```

### Font Awesome version

v5.14

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

Chrome on all platforms

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has already been discussed in the past, but we are not going to add `!important` to Font Awesome CSS

Please fix the template or feel free to add `!important` rule to your application stylesheet

Hope it helps

Closing here

Ref: https://github.com/FortAwesome/Font-Awesome/pull/15690#issuecomment-542206791
