### ISSUE TITLE
Icon request: Gym equipment

### ISSUE THREAD

**Issue by james182** [FortAwesome/Font-Awesome#19182]
### Use case

In the fitness industry your icons while awesome lack variety in fitness particulary gym equipment, like free weights, treadmills, stationery bikes, bench press, dumbells, sauna, etc..

### Example image

<img width="669" alt="Screen Shot 2022-07-11 at 8 40 17 am" src="https://user-images.githubusercontent.com/415228/178164795-ac220a7b-6829-4c5c-8921-a3df27b2c67a.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request. Please make sure to provide a good title and an example.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by cjaxsn** [comment]
I agree with the request. I currently have a use case for treadmill and workout bench
