### ISSUE TITLE
Icon request: fa-gingerbread

### ISSUE THREAD

**Issue by TylerMWise** [FortAwesome/Font-Awesome#19185]
**Use case**
Myself and quite a few people are currently using gingerbread people images as icons, but it would be perfect to have a gingerbread person emoji we could use. This icon would be perfect for Cafés or other places which rely on food icons.

**Example image**
![image](https://user-images.githubusercontent.com/74430503/178511531-1c075e0a-aa74-4522-9048-380bd94b7337.png)

**Icon request checklist**
 The title starts with "Icon request: " and is followed by the requested icon name
 This icon does not represent a brand
 This is a single icon or matched pair (Ex: lock / unlock)
 The request is for a concrete object, or I've included an example image
 I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
 I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by aethior** [comment]
Hi,

`gingerbread-man` was added in v5.6.0 as a `PRO` icon.
Check https://fontawesome.com/icons/gingerbread-man

Regards.

cc/ @tagliala
