### ISSUE TITLE
Feature request: Change default search filter from "s=solid,brand" to "m=free"

### ISSUE THREAD

**Issue by septatrix** [FortAwesome/Font-Awesome#19184]
### Is your feature request related to a problem?

Every time when I search for icons on the fontawesome website I must change the search filter for relevant results.
In the best case this only wastes time. However there are also some solid icons which are not available in the free version and discovering that after having performed the search can be frustrating. Furthermore forgetting to change the filter can also lead to the user not discovering a great icon in the regular style of which some are free.

I assume that the vast majority (>99%) of visitors use the free version and are equally affected.

### Feature description

The default filter for the icons search on the fontawesome website should be changed from `solid,brand` to `free`.

### Alternatives

A decent alternative would be to store the previously used search filter in localStorage or a cookie like it is already done for the layout (grid, list).
This would be more complex but result in an even better user experience. Users who currently work on an app where duotone icons are used would simply return to that as their default and so forth. This should however probably only consider the "style" and "free" flags and maybe new, sponsored and staff favorites. The freetext from the previous search is probably not worth saving similar to the category.

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hey @septatrix. Thanks so much for the feedback. We'll certainly consider a different default search, or perhaps even saving preferences per user.

In the meantime, my suggestion would be to bookmark your preferred filters and use those. For instance, if you use the following link, it'll default to only searching free icons: https://fontawesome.com/search?o=r&m=free

**Comment by septatrix** [comment]
Do you perform some internal bookkeeping of issues like these? Otherwise I would prefer to have this this open until it is really completed.
