### ISSUE TITLE
Configuration examples refer to hijacked domain

### ISSUE THREAD

**Issue by ius** [FortAwesome/Font-Awesome#19180]
I carelessly copy pasted a configuration example from the [documentation](https://fontawesome.com/docs/apis/javascript/configuration#setting-the-configuration), not realizing it refers to an example domain.

    <html>
      <head>
        <script src="https://your-site-or-cdn.com/fontawesome/v6.1.1/js/all.js" data-auto-a11y="true" ></script>
      </head>
      <body></body>
    </html>

Soon enough I noticed some shady JS being loaded. It turns out an enterprising individual has registered `your-site-or-cdn.com` for nefarious purposes and is serving arbitrary JS to unaware users (like me).

Probably better to use a safe domain like `example.com` - or something in control of Font Awesome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

This should be immediately addressed

**Comment by robmadole** [comment]
Yep, thanks @ius. This is highest priority and we'll get it fixed.

**Comment by robmadole** [comment]
This is now fixed on fontawesome.com. Thanks again @ius .
