### ISSUE TITLE
icon-thumbs-up and icon-thumbs-up-alt does not line up

### ISSUE THREAD

**Issue by MaZderMind** [FortAwesome/Font-Awesome#1919]
Hi

we're using icon-thumbs-up and icon-thumbs-up-alt as an on/off indicator and when placing the two nearby or toggeling between it get's obvious, that they don't line up nicely and look a tiny amout different.

![up-unsym](https://f.cloud.github.com/assets/142237/1079952/80363bfe-1556-11e3-860b-9b2b6755b0c0.png)

Best regards,
Peter

**Comment by kernc** [comment]
:+1: The alternative can be used to indicate state. And it doesn't look as good if it resizes when changing state.

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone so Dave will eventually take a look

Also refers to #1624. #1624 should be addressed before this one

**Comment by tagliala** [comment]
Still an issue

https://jsfiddle.net/tagliala/tgzouajm/37/

**Comment by tagliala** [comment]
Fixed in FA 6.0

https://jsfiddle.net/tagliala/wr154e6x/10/
