### ISSUE TITLE
Bug: duotone album-collection broken in safari

### ISSUE THREAD

**Issue by jonriec** [FortAwesome/Font-Awesome#19195]
### Bug description

album-collection is misaligned.
usage: fad fa-album-collection fa-fw

Installed using NPM (@fortawesome/fontawesome-pro)

### Reproducible test case

https://fontawesome.com/search?q=album-collection&s=brands%2Cduotone

### Screenshots

![image](https://user-images.githubusercontent.com/38163554/179520750-9bfe145a-3be7-4b31-ace8-69d8c89b0a1f.png) 
![image](https://user-images.githubusercontent.com/38163554/179520857-8e706265-6a17-4716-9efc-24e603c47a27.png) (my project)

### Font Awesome version

v6.1.1

### Serving

Other (as specified in the bug description)

### Implementation

CSS

### Browser and Operating System

MacOS 12.4 
Safari 15.5

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Confirmed, thanks

**Comment by danielswiatek** [comment]
I got the same on macOS Catalina 10.15.4. with Safari 13.1

**Comment by jonriec** [comment]
It looks like the issue got fixed
