### ISSUE TITLE
Bug: SVG code of free icons on fontawesome.com includes Pro license

### ISSUE THREAD

**Issue by tnir** [FortAwesome/Font-Awesome#19191]
### Bug description

"Copy SVG code" feature from https://fontawesome.com/icons/magnifying-glass?s=solid (Font Awesome 6.1.3) gives us the code with Pro license as below while the icon has been included since 1.0.0 (formerly known as `search` in version 5) and (as far as I understand correctly) is Free in Font Awesome 6.

```html
<!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
```

#### Current behavior

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/></svg>
```

#### Expected behavior
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc. --><path d="M500.3 443.7l-119.7-119.7c27.22-40.41 40.65-90.9 33.46-144.7C401.8 87.79 326.8 13.32 235.2 1.723C99.01-15.51-15.51 99.01 1.724 235.2c11.6 91.64 86.08 166.7 177.6 178.9c53.8 7.189 104.3-6.236 144.7-33.46l119.7 119.7c15.62 15.62 40.95 15.62 56.57 0C515.9 484.7 515.9 459.3 500.3 443.7zM79.1 208c0-70.58 57.42-128 128-128s128 57.42 128 128c0 70.58-57.42 128-128 128S79.1 278.6 79.1 208z"/></svg>
```

https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/@fortawesome/fontawesome-free/svgs/solid/magnifying-glass.svg

#### magnifying-glass classification in Font Awesome 6
- https://fontawesome.com/search?q=magnifying-glass&m=free
- https://github.com/FortAwesome/Font-Awesome/blob/65f4bdb5025759ba25cd3432568de288b6a67527/js-packages/%40fortawesome/free-solid-svg-icons/faMagnifyingGlass.js
   - shows `magnifying-glass` is included in free-solid-svg-icons
   - `@fortawesome/fontawesome-free` license: `CC-BY-4.0 AND OFL-1.1 AND MIT` according to https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/js-packages/%40fortawesome/fontawesome-free/package.json

### Reproducible test case

https://fontawesome.com/icons/magnifying-glass?s=solid

### Screenshots

n/a

### Font Awesome version

v6.1.1

### Serving

Other (as specified in the bug description)

### Implementation

SVG Sprites

### Browser and Operating System

Independent from browser and operating system

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

This is happening for every icon as far as I can see

**Comment by tnir** [comment]
@tagliala Thanks. Yes, as you are pointing out, I guess this happens to every Free icon of 1900+ while I did not check it.

So I think you need to visit https://github.com/FortAwesome/Font-Awesome/blob/b452a2c086a5e3f319df61b1ce1db7d8e1ad2b7c/js-packages/%40fortawesome/fontawesome-free/svgs/solid/magnifying-glass.svg to get a SVG code with the precise license, like I did.

**Comment by tagliala** [comment]
> So I think you need to visit https://github.com/FortAwesome/Font-Awesome/blob/b452a2c086a5e3f319df61b1ce1db7d8e1ad2b7c/js-packages/%40fortawesome/fontawesome-free/svgs/solid/magnifying-glass.svg to get a SVG code with the precise license, like I did.

Yes, please use this workaround in the meanwhile

There is also an `/svgs` folder in the main repo: https://github.com/FortAwesome/Font-Awesome/blob/6.1.1/svgs/solid/magnifying-glass.svg

**Comment by tnir** [comment]
Thank you! The location you showed was not easily found just with GitHub search. 😍

**Comment by kiriri** [comment]
The fact that this issue was not fixed within a week, let alone a year, seems outright malicious to me.

**Comment by sensibleworld** [comment]
This has been fixed.
