### ISSUE TITLE
Bug: The requested module does not provide an export named 'faSausage'

### ISSUE THREAD

**Issue by richardhedges** [FortAwesome/Font-Awesome#19199]
### Bug description

When attempting to import `faSausage` from `@fortawesome/free-solid-svg-icons`, the following error is produced:

**The requested module '/node_modules/.vite/deps/@fortawesome_free-solid-svg-icons.js?v=3db64a08' does not provide an export named 'faSausage'**

I have checked the `@fortawesome/free-solid-svg-icons` file and can confirm `faSausage` is omitted.

### Font Awesome version

v6.1.1

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

Chrome 103.0.5060.114 on macOS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is expected

`fa-sausage` is a Pro icon and should be limited to the Pro set

Ref: https://fontawesome.com/icons/sausage?s=solid

Closing here, but feel free to comment and provide more information if I didn't get this request
