### ISSUE TITLE
Typo in Accessibility docs page

### ISSUE THREAD

**Issue by gonzonieto** [FortAwesome/Font-Awesome#19203]
Just reporting that in the first paragraph of the [Auto-Accessibility with Kits section on the Accessibility page](https://fontawesome.com/docs/web/dig-deeper/accessibility#auto-accessibility-with-kits), the word "accessibility" is misspelled as "accessiblity":
<img width="1080" alt="Screen Shot 2022-07-22 at 3 54 44 PM" src="https://user-images.githubusercontent.com/5186441/180517624-7bc6f96d-2ac4-4fd6-8b09-b5a5cc297e3c.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I can confirm and there are different typos

- 1 occurrence of `accessiblity`
- 4 occurrences of `accessiblility`

**Comment by talbs** [comment]
Thanks for the heads up about these typos, they should all be resolved now on fontawesome.com at https://fontawesome.com/docs/web/dig-deeper/accessibility.
