### ISSUE TITLE
Bug: Missing changelog for version 6.1.2

### ISSUE THREAD

**Issue by intgr** [FortAwesome/Font-Awesome#19211]
### Bug description

The GitHub release 6.1.2 at https://github.com/FortAwesome/Font-Awesome/releases/tag/6.1.2 points users to read changelog at https://fontawesome.com/docs/changelog/

The latter changelog however has not been updated and still shows 6.1.1 as the latest release.

### Font Awesome version

v6.1.2

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

-

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Usually the documentation is updated some hours after the, so this is not optimal but expected

**Comment by tagliala** [comment]
The changelog is available now
