### ISSUE TITLE
Icon Request: spinner-alt (FA4 version)

### ISSUE THREAD

**Issue by My1** [FortAwesome/Font-Awesome#19214]
### Use case

basically a different style of spinner which isnt having a missing circle but rather circles of different sizes.

### Example image

https://fontawesome.com/v4/icon/spinner

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
This is now released! https://fontawesome.com/icons/spinner-scale?f=classic&s=solid

**Comment by My1** [comment]
thanks a ton, I guess perseverance pays off, had asked for this in other places (eg the pro repo) since 2017 at least :-)

**Comment by sensibleworld** [comment]
Sorry it took so long!

**Comment by My1** [comment]
no problem, at least we have it now and now in more variations than ever (sharp looks actually hilarious lol)
