### ISSUE TITLE
Bug: BDT currency incorrectly being in pro pack

### ISSUE THREAD

**Issue by istiak101** [FortAwesome/Font-Awesome#19220]
### Bug description

Almost all the currency icons are in Free version but BDT is in Pro version. Is this intended or a bug?

https://fontawesome.com/icons/indian-rupee-sign?s=solid
https://fontawesome.com/icons/dollar-sign?s=solid
https://fontawesome.com/icons/euro-sign?s=solid
https://fontawesome.com/icons/lira-sign?s=solid
https://fontawesome.com/icons/baht-sign?s=solid

### Reproducible test case

https://fontawesome.com/icons/bangladeshi-taka-sign?s=solid

### Screenshots

![Screenshot from 2022-07-30 17-23-27](https://user-images.githubusercontent.com/30789544/181908683-9d0c5063-6d85-4f74-a937-fe9e0861b71f.png)

### Font Awesome version

v6.1.2

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Chrome 100 on Linux

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I think this is a bug

Let's confirm with @sensibleworld

**Comment by istiak101** [comment]
Any update on this?

**Comment by sensibleworld** [comment]
This is fixed in 6.2.1 https://fontawesome.com/icons/bangladeshi-taka-sign?s=solid&f=classic
