### ISSUE TITLE
Brand request: Kofi

### ISSUE THREAD

**Issue by kctolli** [FortAwesome/Font-Awesome#19223]
### Description

Kofi Donation service

### Official website

https://ko-fi.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is a duplicate of #12607

**Comment by tagliala** [comment]
Closing, feel free to comment if this is not a duplicate
