### ISSUE TITLE
没有bilibili 图标

### ISSUE THREAD

**Issue by VirtualHotBar** [FortAwesome/Font-Awesome#19226]
如题建议加入bilibili 图标

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Bilibili icon is already available:
- https://fontawesome.com/icons/bilibili?s=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by VirtualHotBar** [comment]
谢谢，我当时用的v4版本，见谅
