### ISSUE TITLE
Icon request: ResearchGate icon

### ISSUE THREAD

**Issue by SasaniP** [FortAwesome/Font-Awesome#19224]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Research Gate icon is already available:
- https://fontawesome.com/icons/researchgate?s=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
