### ISSUE TITLE
Bug: Unable to Finish Setting up my FontAwesome Account

### ISSUE THREAD

**Issue by jdlsc** [FortAwesome/Font-Awesome#19238]
### Bug description

When I click on the "Set Up Your Account" link in the email sent to me after purchasing licenses, I get a message that the Link Isn't Valid so I'm unable to manage my team's licenses.

I've tried this link on both Chrome and Edge.

### Screenshots

![image](https://user-images.githubusercontent.com/110611561/182853770-794cd957-8477-4aa9-9ef4-d276443add49.png)

### Font Awesome version

Unknown

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome 103 on Windows 10
Edge 103 on Windows 10

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Sorry for the late reply, please get in touch with the Pro support Team at hello@fontawesome.com

Please feel free to comment if you don't receive an answer in 2 business days

**Comment by jdlsc** [comment]
I sent requests to hello@fontawesome.com on 8/2/22 and 8/3/22 and received no response.

**Comment by tagliala** [comment]
Apologies for that. Let me try to escalate this

**Comment by sensibleworld** [comment]
@jdlsc Can you share what email you sent your support requests from (and what email you're using for your account)? That'll help me track down the issue and see both why we haven't been receiving your requests and what the issue may be with the link. Thanks!

**Comment by jdlsc** [comment]
Any update on this issue?  I am still unable to login and manage my licenses.  If I can’t get this resolved, I am going to have no choice but to dispute the charge on my credit card.

John Lester
803.356.7676 (office)
803.356.4942 (fax)
212 Palmetto Park Blvd.
Lexington, SC  29072
[escription: ***@***.***<http://www.teamia.com/>
For new support issues, please
contact ***@***.******@***.***>

**Comment by sensibleworld** [comment]
Hey John! In my message above, I asked if you could share the email address for your account and the one you used (if different) to send the support message. That'll help me track it down in our system. Thanks!

**Comment by jdlsc** [comment]
I sent that.  The address used for the purchase is ***@***.******@***.***>.  The support one might show up as ***@***.******@***.***>.  Both to the same mailbox.

John Lester
803.356.7676 (office)
803.356.4942 (fax)
212 Palmetto Park Blvd.
Lexington, SC  29072
[escription: ***@***.***<http://www.teamia.com/>
For new support issues, please
contact ***@***.******@***.***>

**Comment by sensibleworld** [comment]
Hey John, sorry about that. It looks like Github hides email address (rightly so!), so I can't see them from my end. I was, however, able to track down your account on our end. I'll send you an email directly.

**Comment by jdlsc** [comment]
Thanks!

John Lester
803.356.7676 (office)
803.356.4942 (fax)
212 Palmetto Park Blvd.
Lexington, SC  29072
[escription: ***@***.***<http://www.teamia.com/>
For new support issues, please
contact ***@***.******@***.***>

**Comment by jdlsc** [comment]
***@***.******@***.***> for my purchase.

It’s possible my reply address shows ***@***.******@***.***>; both go to the same mailbox.

John Lester
803.356.7676 (office)
803.356.4942 (fax)
212 Palmetto Park Blvd.
Lexington, SC  29072
[escription: ***@***.***<http://www.teamia.com/>
For new support issues, please
contact ***@***.******@***.***>

**Comment by sensibleworld** [comment]
Hey John - This issue has been closed, and we've had some back and forth already via our support email. If you're still having trouble, please reach out there. Thanks!
