### ISSUE TITLE
Icon request: nintendo-switch

### ISSUE THREAD

**Issue by consideredcreative** [FortAwesome/Font-Awesome#19242]
For game developers, publishers and content creators to use to promote titles on this console.
SVG from Wikimedia Commons: https://commons.wikimedia.org/wiki/File:Nintendo_Switch_Logo_%28without_text%29.svg

![Nintendo_Switch_Logo_(without_text)](https://user-images.githubusercontent.com/25511867/183071992-73d8c841-b2fd-43f7-bfc8-727c56a924e3.svg)

**Comment by tagliala** [comment]
Sorry, this is not possible 

https://github.com/FortAwesome/Font-Awesome/blob/5.x/UPGRADING.md#582-to-590

> The nintendo-switch icon has been removed by legal request of Nintendo of America Inc.
>
> Font Awesome is no longer able to provide icons related to Nintendo, their gaming consoles, accessories, or games.
