### ISSUE TITLE
Icon request: cargo trailer - open/flatbed

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#19244]
Wanting something like a landscape/cargo trailer. Double axle with low rails and a tongue. No top or cover.

**Comment by tagliala** [comment]
Hi!

Is this request about one of the following icons?

- https://fontawesome.com/icons/truck-ramp?s=solid
- https://fontawesome.com/icons/truck-ramp-box?s=solid
- https://fontawesome.com/icons/truck-ramp-couch?s=solid

If it isn't, please open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) from GitHub's website

Please also provide a single color example, suitable for small icons (16px), of the icon you have in mind
