### ISSUE TITLE
Icon request: Tiktok Icon

### ISSUE THREAD

**Issue by sarwanthapa** [FortAwesome/Font-Awesome#19247]
### Use case

Hello,
Greeting!!!
I found that the icon pack is missing icon of tiktok or I might not able to find it. Can someone guide me?

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TikTok icon has been added to Font Awesome in version 5.13.1:
- https://fontawesome.com/icons/tiktok?style=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by sarwanthapa** [comment]
Thank-Q for feedback
I found that I am using an old version (v 5.4). Is there any possibility that I can use the icon in that version?

**Comment by tagliala** [comment]
> I found that I am using an old version (v 5.4)

Any reason why you can't update to the latest 5.x version?

> Is there any possibility that I can use the icon in that version?

If you are using SVG+JS Framework, it is easy: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sarwanthapa** [comment]
Looks like there are no other options. I will update.
Thanks For help
