### ISSUE TITLE
Icon request: cargo trailer

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#19245]
### Use case

Used to depict trailers that are used to haul in the open air. These trailers are used from anything to moving one's house to picking up a load of landscaping mulch.

The current [trailer](https://fontawesome.com/icons/trailer) icon doesn't look like a trailer to me. It looks like a camper with weird stripes.

### Example image

![Trailer](https://user-images.githubusercontent.com/3402707/183139744-c832c11e-d585-4e65-8e44-513439d0c016.svg)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by manattweb** [comment]
![Trailer2](https://user-images.githubusercontent.com/3402707/183141615-c45c107f-4055-465b-abbe-2c624cc82a1c.svg)

Update: wheels not solid

**Comment by manattweb** [comment]
![Trailer-Duotone](https://user-images.githubusercontent.com/3402707/183141872-b4dc1896-49eb-4819-88b7-0af956b812f5.svg)

Duotone?

**Comment by tagliala** [comment]
Thanks for opening a new request

Could you please also clarify why the current trailer icon does not fit the use case?

https://fontawesome.com/icons/trailer?s=solid

Also, please notice that icons should fit a square-ish grid (20x16), and the above one's aspect ratio does not play well

Ref: https://fontawesome.com/v5/docs/web/use-kits/icon-design-guidelines

**Comment by manattweb** [comment]
Fine - close it then.

**Comment by tagliala** [comment]
> Fine - close it then.

Apologies, does it mean that `fa-trailer` is ok for this use case?

**Comment by manattweb** [comment]
No, it doesn't. That doesn't look like a trailer to me. It looks like a camper with weird stripes. It's clear though that the idea isn't going to get any traction

**Comment by tagliala** [comment]
>  No, it doesn't. That doesn't look like a trailer to me. It looks like a camper with weird stripes

Got it

> It's clear though that the idea isn't going to get any traction

That was not my intention

I'm reopening for tracking purposes and we can also get feedback or different design ideas from the community

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
