### ISSUE TITLE
Docs: Confusing wording in React usage guide

### ISSUE THREAD

**Issue by MythicManiac** [FortAwesome/Font-Awesome#19253]
There seems to be a minor mistake in the React usage info docs phrasing here: https://fontawesome.com/v5/docs/web/use-with/react

Specifically, I'm assuming:

> don't want to use React and not React Native

should be:

> want to use React and not React Native

![image](https://user-images.githubusercontent.com/8225825/183964047-44eafd7b-8c69-47c3-b0d7-4fdc2cdc62bd.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @talbs

**Comment by talbs** [comment]
Thanks for the heads up on this and sorry for the confusion. https://fontawesome.com/v5/docs/web/use-with/react should be a lot less confusing now.
