### ISSUE TITLE
Icon-request: icon-zones

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#1925]
Basically I would need the Icon for a surface of a system. 
![nav_zones](https://f.cloud.github.com/assets/5346389/1087730/dc516ed0-161f-11e3-853b-36f18a367e1e.png)

**Comment by aethior** [comment]
Hi @ghost,

Something like [fa-regular fa-sliders-up](https://fontawesome.com/icons/sliders-up)?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
> Something like [fa-regular fa-sliders-up](https://fontawesome.com/icons/sliders-up)?

Assuming so

Closing here, but feel free to open a new request
