### ISSUE TITLE
Feature request: Add support for custom uploaded duotone icons in kits

### ISSUE THREAD

**Issue by shawnphoffman** [FortAwesome/Font-Awesome#19254]
### Is your feature request related to a problem?

Nope.

### Feature description

I would like to be able to upload custom duotone icons for kits. Ideally, we could upload an svg with solid shapes and something like 40% opacity shapes and have it render accordingly. 

### Alternatives

I've tried achieving this by uploading 2 distinct custom icons, stacking them, and adjusting them each accordingly. This is painful because there can be weird alignment issues and I feel like I'm jumping through 50 hoops to achieve it.

### Additional context

Thanks for everything you do!  
![thank you](https://media.giphy.com/media/osjgQPWRx3cac/giphy.gif)

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
@shawnphoffman This feature is now available!

**Comment by chandlersimon** [comment]
Is there an ETA on on when Duotone custom icon uploads will be available in downloaded Kits?
