### ISSUE TITLE
Outlook 

### ISSUE THREAD

**Issue by bubba-123** [FortAwesome/Font-Awesome#19252]
https://github.com/bubba-123

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Closing here, but feel free to comment if I've missed something
