### ISSUE TITLE
Icon request: Rocky Linux

### ISSUE THREAD

**Issue by Dulux-Oz** [FortAwesome/Font-Awesome#19259]
Hi All,

How about an icon for Rocky Linux

https://seeklogo.com/vector-logo/409448/rocky-linux

Cheers

Dulux-Oz

**Comment by istiak101** [comment]
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/19166

**Comment by tagliala** [comment]
thanks, searching by "Rocky Linux" does not bring up that result. Will edit #19166's title to improve search
