### ISSUE TITLE
Icon request: gauge-ampere, circle-ampere, circle-bolt-ampere, square-bolt-ampere ...

### ISSUE THREAD

**Issue by SebZar** [FortAwesome/Font-Awesome#19275]
### Use case

Hi,
I'm looking for some icons to electical values/units looking awesome:

- Electric current, Ampre
1. gauge with A in small circle
2. circle with A
3. circle-bolt with A in small circle
4. square-bolt with A in small circle

- Electric potential, Volt
1. gauge with V in small circle
2. circle with V
3. circle-bolt with V in small circle
3. square-bolt with V in small circle

- Power, watt / kilo watt
1. gauge with kW in small circle
2. circle with kW
3. circle-bolt with kW in small circle
4. square-bolt with kW in small circle
5. gauge with W in small circle
6. circle with W
7. circle-bolt with W in small circle
8. square-bolt with W in small circle

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request form](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request, having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. Please make sure to provide a good title and an example.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
