### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by nadaworks** [FortAwesome/Font-Awesome#19278]
Hello! I would love to have the magicaVoxel icon "cat-girl" available,
![catgirl](https://user-images.githubusercontent.com/103444407/185746046-005c1fd1-e21b-4395-829e-9cc293f932c9.png)

Happy coding!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+), if this icon is protected by copyright or trademark

Also please provide a single color example suitable for 16px icon size

Closing here, but feel free to comment if I've missed something
