### ISSUE TITLE
Icon request: icon-border-left / icon-border-right / icon-border-top / icon-border-bottom

### ISSUE THREAD

**Issue by mozzbozz** [FortAwesome/Font-Awesome#1927]
Until now, I could find every icon I needed in Font Awesome - thanks for that, it is REALLY awesome! :D

However, now I was looking for a "table border" icon just like you can find it in LibreOffice / OpenOffice.org or in Microsoft Excel. You can add new borders with that little Icon in the Toolbar. There should be one for every side: left, right, top, bottom. It should look like a Rectangle and than have one thicker border.

It could look something like this:
![border-left](https://f.cloud.github.com/assets/1001601/1088605/0d77cb92-1636-11e3-988d-35ca361553be.png)

**Comment by sensibleworld** [comment]
We've added a bunch of `border` icons to the latest release: https://fontawesome.com/icons?d=gallery&q=border&v=5.9.0&c=editors
