### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by ailsablair** [FortAwesome/Font-Awesome#19270]
I would like to see an icon pack for vets/vet clinics

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request form](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request, having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. Please make sure to provide a good title and an example.

If you are a Font Awesome Pro customer, you can request icon sets at repository at https://github.com/FortAwesome/Font-Awesome-Pro

If you are a Font Awesome Pro customer and you don't have access to the above repository, please make sure you have linked your Font Awesome Account to your GitHub account at https://fontawesome.com/account/services

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
