### ISSUE TITLE
FONT AWESOME ICONS NOT LOADING ON WEBSITE

### ISSUE THREAD

**Issue by PrinceOsagie** [FortAwesome/Font-Awesome#19271]
1st: Successfully Added Kit code:  inside my head tag 
2nd: Successfully Added my <i tag in my html webpage
font awesome icon did not load on my webpage

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) 

Closing here, but feel free to comment if I've missed something
