### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Annsuree** [FortAwesome/Font-Awesome#19298]
https://github.com/FortAwesome/Font-Awesome/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by tagliala** [comment]
Hi @Annsuree,

Thanks for being part of the Font Awesome Community

If you need help in using GitHub to open issue, please take a look at https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue

Closing here
