### ISSUE TITLE
Missing Icon 

### ISSUE THREAD

**Issue by memorabilien** [FortAwesome/Font-Awesome#19294]
### Bug description

I am on version 6.1.2, and I am using the web font with font-weight 400.
I noticed that the external link icon is missing. 

`<i class="fa-solid fa-arrow-up-right-from-square"></i>`

It just shows a crossed out square. With font weight 900 it works perfectly fine.

### Reproducible test case

https://codepen.io/memorabilien/pen/rNdXJPB

### Font Awesome version

v6.1.2

### Serving

Font Awesome CDN, Self-hosted

### Implementation

CSS

### Browser and Operating System

 Google Chrome Version 104.0.5112.102

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hey @memorabilien! The majority of our 1,388 free icons are in the 900 weight, Font Awesome Solid. There are a handful (163) that are also in our Regular style, 400 weight, to have parity with some of the old -o style icons we had in earlier versions. So the behavior above is expected, if you need the regular weight of that particular icon, you'll want to use Font Awesome Pro.
