### ISSUE TITLE
"album-collection" not aligned correctly

### ISSUE THREAD

**Issue by aidenguinnip** [FortAwesome/Font-Awesome#19295]
The shapes within the regular weight icon for "album-collection" isn't properly aligned—the other weights look correct.

The "disc" shape isn't centered horizontally with the "rectangles" around it. However, the inside "hole" does seem to be centered.

https://fontawesome.com/icons/album-collection?s=regular

Image attached shows the misalignment. White is current, red is where it should be.

![image](https://user-images.githubusercontent.com/9369962/187480453-67fd1e6a-5499-4a87-954e-0eb0d83ad09e.png)

**Version and implementation**
Version: V6, it's [live on the website](https://fontawesome.com/icons/album-collection?s=regular)

**Comment by sensibleworld** [comment]
Thanks for the report!

**Comment by sensibleworld** [comment]
This should be fixed in 6.2.1: https://fontawesome.com/icons/album-collection?s=regular
