### ISSUE TITLE
Icon request: icon-waveform

### ISSUE THREAD

**Issue by kia2882** [FortAwesome/Font-Awesome#193]
Something like this: http://i.imgur.com/9USgd.png

How could I implement this myself?

**Comment by brianruff** [comment]
+999! Yes!

**Comment by G-Driver** [comment]
+1

**Comment by GitChrit** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode character: #222 

* ∿ U+223F Sine Wave

The sample picture shows a digitized analog signal, though.

**Comment by poposhka** [comment]
this would be great.

**Comment by weavermedia** [comment]
Wow. Six years and still no waveform icon!

Massive +1 on this.

https://thenounproject.com/search/?q=waveform

**Comment by sensibleworld** [comment]
Font Awesome 5.11 is out with a few new waveform icons: https://fontawesome.com/icons?d=gallery&q=waveform
