### ISSUE TITLE
Bug: npm install pro-solid-svg-icon error

### ISSUE THREAD

**Issue by StevenInc** [FortAwesome/Font-Awesome#19305]
### Bug description

Set Up with Vue JS errors
In following the directions for setting up Fontawesome for vuejs:
https://fontawesome.com/docs/web/use-with/vue/

The following npm installation fails:
npm i --save @fortawesome/pro-solid-svg-icons

Yields:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icon

### Reproducible test case

npm i --save @fortawesome/pro-solid-svg-icons

### Font Awesome version

v6.0.2

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Terminal

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by StevenInc** [comment]
Same is true for:
@fortawesome/pro-regular-svg-icons
@fortawesome/pro-light-svg-icons
@fortawesome/pro-thin-svg-icons
@fortawesome/pro-duotone-svg-icons

**Comment by StevenInc** [comment]
This was an issue with our token being incorrect configured.
I didn't realize this was a link with the examples:
(See screenshot:A) Because the page redirect was broken.
See screenshot: B

**Comment by StevenInc** [comment]
B: <img width="709" alt="Screen Shot 2022-09-02 at 2 50 54 PM" src="https://user-images.githubusercontent.com/791500/188240055-5bb6b463-6573-41bd-9d6f-984199933278.png">
A:
<img width="1042" alt="Screen Shot 2022-09-02 at 2 50 46 PM" src="https://user-images.githubusercontent.com/791500/188240233-c53cccf4-e3cc-4af1-88f0-ebfeed527d42.png">

**Comment by tagliala** [comment]
> This was an issue with our token being incorrect configured.

So I assume this is not an issue anymore

Closing here
