### ISSUE TITLE
Bug: SVG + JS not reactive

### ISSUE THREAD

**Issue by ChrisPlease** [FortAwesome/Font-Awesome#19316]
### Bug description

Swapping class names on svg + js icons do not update the icon instance. Given an icon with class `fa-plus`, when the class changes to `fa-times` for example, the `plus` icon is still shown. (See reproducible link).

Marked as self hosted because that's how I discovered it, but using the CDN for the repro link.

I've troubleshooted this and found this only happens when using svg + js implementation of FA6. If using the CSS + Webfont, icon updates as expected.

### Reproducible test case

https://codesandbox.io/s/jolly-sutherland-bq4xz1?file=/App.svelte

### Font Awesome version

6.2.0

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

Chrome 104
FF 103

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think this is because of Svelte

As mentioned at https://github.com/FortAwesome/Font-Awesome/issues/18611#issuecomment-1052562796, I think this needs  a specific component

@robmadole can you please confirm?

**Comment by robmadole** [comment]
We have a new Svelte component. Can you give it a try? https://github.com/FortAwesome/svelte-fontawesome

We'll re-open if this is still an issue.

**Comment by ChrisPlease** [comment]
Installed @fortawesome/svelte-fontawesome, issue is still present. I can't update/fork codesandbox because I can't find the dependency in the deps list. Attached a screenshot and a trivial icon component

![dropdown](https://user-images.githubusercontent.com/2982692/188904561-01766978-b60a-4f2a-b3d9-425e77038175.gif)

```ts
// icon.ts
import { library } from '@fortawesome/fontawesome-svg-core'

import { faAngleUp, faAngleDown } from '@fortawesome/pro-light-svg-icons'

library.add(faAngleUp, faAngleDown)
```

```svelte
<script lang="ts">
  import type { IconName } from '@fortawesome/fontawesome-svg-core'
  import { FontAwesomeIcon, type FontAwesomeIconProps } from '@fortawesome/svelte-fontawesome'
  import './icon'

  export let variant: 'regular' | 'solid' | 'thin' | 'duotone' | 'light' = 'light'
  export let name: IconName

  let props: FontAwesomeIconProps = {
    icon: `fa-${variant} fa-${name}`,
  }

</script>

  <span>
  {name} <!-- reactive -->
  <FontAwesomeIcon {...props} />
  </span>
```

```svelte

<Icon name={isOpen ? 'angle-up' : 'angle-down'} />

```

**Edit**: `flip` prop also doesn't seem to work.

```svelte
        <Icon
          variant="light"
          flip={isOpen ? 'vertical' : undefined}
          name="angle-down"
          class="toggle-icon"
          size="sm"
        />
```

**Edit 2**: I thought maybe abstracting `FontAwesomeIcon` into my own `Icon` component may have lost reactivity, that's not the case, same issue when using `FontAwesomeIcon` directly

```svelte
<FontAwesomeIcon icon={`fa-light fa-${isOpen ? 'angle-up' : 'angle-down'}`} />
```

**Comment by ChrisPlease** [comment]
Additionally, I did see the originally referenced svelte ticket, but imho, this bug doesn't seem related to svelte. 

As I mentioned in the original ticket, this is only reproduced when using SVG+JS. When using web fonts+CSS, icons update as expected.

**Comment by ChrisPlease** [comment]
for posterity: here's a reproduction link of the bug with vanilla JS. https://codesandbox.io/s/reverent-almeida-7ghqlj?file=/index.html

**Comment by tagliala** [comment]
> for posterity: here's a reproduction link of the bug with vanilla JS.

I'm getting an error:

```
TypeError
Cannot read properties of undefined (reading 'classList')
```

Anyway, I think that the documentation about jQuery can also help here

https://fontawesome.com/docs/web/use-with/jquery

The problem is that with SVG+JS, the original element is removed from the DOM and converted to an SVG

If you inspect the DOM you will see

<img width="504" alt="image" src="https://user-images.githubusercontent.com/556268/189127751-56cfa8b0-f230-4aa8-b921-3e7a3b88ac40.png">

This is stated in the jQuery docs

> Avoid creating JavaScript variable references to icons
> 
> Since Font Awesome is dynamically replacing and modifying your icons, any held reference to an icon will not work as expected.

That is what the codesandbox is doing:

```js
var [icon] = document.getElementsByClassName("fa");
```

You may want to use a different approach, by using nest or by adding another class or an ID to the SVG, and target the element that is not going to be replaced in the DOM

This may help (but you may want to use ES6): https://stackoverflow.com/questions/46210501/switch-between-icons-when-using-fontawesome-5-0-svg-framework

**Comment by ChrisPlease** [comment]
Thanks @tagliala , I was able to get it working with vanilla js by targeting `[data-fa-i2svg]` as noted in the jQuery docs. Still having issues with svelte-fontawesome, but at least I have options now.
