### ISSUE TITLE
Feature request: Add !default to $fa-icons and $fa-brand-icons

### ISSUE THREAD

**Issue by cbracco** [FortAwesome/Font-Awesome#19317]
### Is your feature request related to a problem?

Hi there! Love the library, we @muckrack are long-time users, and now happy FA6 Pro users 😄.

I noticed the other day that the `!default` keyword is missing from both the `$fa-icons` and `$fa-brand-icons` Sass maps in `_variables.scss`. This makes it impossible to override these values without having to maintain our own "vendored" copy of this file in our repository. It would be great if that wasn’t the case, so that upgrading to future versions is less clunky for us.

### Feature description

All that would need to change is adding `!default` to the end of each Sass map in `_variables.scss` before the terminating semicolon.

```scss
$fa-icons: (
    ...
) !default;

$fa-brand-icons: (
    ...
) !default;
```

### Additional context

I wasn’t sure if this was a feature or bug (ie. intentional or not), but decided to submit as a feature request here. Is this a change you are open to making? It would be really useful for us. Any help is appreciated, thanks!

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by talbs** [comment]
Hey there! I've dusted this issue off and it should be in place for our upcoming Font Awesome 7 release. Thanks for bringing it to our attention, @cbracco.

**Comment by cbracco** [comment]
@talbs glad to hear it! thanks for adding it to the upcoming release 👍🏻
