### ISSUE TITLE
Bug: Faulty SVG for tower-broadcast (sharp)

### ISSUE THREAD

**Issue by sonovice** [FortAwesome/Font-Awesome#19334]
### Bug description

https://fontawesome.com/icons/tower-broadcast?s=solid&f=sharp

See here:
![image](https://user-images.githubusercontent.com/8217108/190232466-1559b2f4-376b-4f48-8c7b-5b794acb2505.png)

### Font Awesome version

v6.2.0

### Application and Operating System

n/a

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@sensibleworld I've assigned you, but if you prefer someone else for Sharp icons let me know

**Comment by sensibleworld** [comment]
@tagliala Thanks, assigning them to me is just fine.

**Comment by sensibleworld** [comment]
We've got this fixed up in 6.2.1 https://fontawesome.com/icons/tower-broadcast?s=solid&f=sharp
