### ISSUE TITLE
Feature request: Add Search Terms back to the .yml and json metadata

### ISSUE THREAD

**Issue by denny99** [FortAwesome/Font-Awesome#19339]
### Is your feature request related to a problem?

We tried to construct our own UI Element to select and style fontawesome icons. For that we used the metadata files and especially the search terms inside to provide the same search functionality as the fontawesome homepage.

This works fine with v5 but in v6 the search terms are removed from the meta data file.
https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/metadata/icons.yml#L43
https://github.com/FortAwesome/Font-Awesome/blob/d3a7818c253fcbafff9ebd1d4abb2866c192e1d7/metadata/icons.yml#L160

### Feature description

Can these be added back to the files? Or is there any specific reason that they had to be removed?

### Alternatives

The alternative would be to use api calls to search for the icons, but this is not possible for us, as this would require a connection to the outside web and our product is often used in internal networks and is not allowed to access the external world due to security reasons

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
@denny99 Wanted to give a quick update that, as of our [6.3.0 release](https://fontawesome.com/docs/changelog/), we've added back the search terms to our metadata files, where they'll stay.
