### ISSUE TITLE
Bug: duotone album-collection problem 

### ISSUE THREAD

**Issue by Gera-G-Guiles** [FortAwesome/Font-Awesome#19345]
Hello, i find this problem with duotone album-collection icon. Also Duotone font-awesome icon have a problem (this one is visible in font awesome web.)
<img width="351" alt="Captura de Pantalla 2022-09-21 a las 14 26 20" src="https://user-images.githubusercontent.com/57091288/191503371-3c74fd28-8e2d-4a22-8114-b5acd3cc0ffa.png">

**Comment by sensibleworld** [comment]
Thanks, @Gera-IC. We've got a fix in the works for it already. Hoping to get it released soon. Also, if I may ask, where is that screenshot from? I don't recognize the interface.

**Comment by sensibleworld** [comment]
Fixed in `6.4.0` https://fontawesome.com/icons/album-collection?f=classic&s=duotone&sc=%231E3050
