### ISSUE TITLE
Bug: N and M have some issues

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#19340]
### Bug description

I've updated my windows installation to 6.2.0 but I've noticed that in the preview something is weird.

![image](https://user-images.githubusercontent.com/556268/190855498-0a4cb730-9f27-4c8d-99fa-23b92e1ba501.png)

![image](https://user-images.githubusercontent.com/556268/190855485-d7384060-4db0-4f3c-ab9b-981b017617db.png)

The bug is also (slightly) visible at https://fontawesome.com/icons/n?s=solid&f=classic

![image](https://user-images.githubusercontent.com/556268/191019404-966c0564-47ef-4786-8d5e-c41d1bfd265b.png)

### Font Awesome version

v6.2.0

### Application and Operating System

- Windows 10

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This should be fixed in the 6.2.1 release.
