### ISSUE TITLE
Bug: use macros but  

### ISSUE THREAD

**Issue by yz-xlame** [FortAwesome/Font-Awesome#19353]
### Bug description

config:
`babel-plugin-macros.config.js`:
```
module.exports = {
  'fontawesome-svg-core': {
    license: 'pro', // my team is using the pro version
  },
};
```
`.babelrc`:
```
{
  "presets": [...],
  "plugins": [
    "macros",
     ...
  ]
}
```
--- 
build result:
```
Module not found: Error: Can't resolve '@babel/helper-module-imports' in '... /node_modules/@fortawesome/fontawesome-svg-core'
Module not found: Error: Can't resolve 'fs' in '... node_modules/babel-plugin-macros/node_modules/resolve/lib'
Module not found: Error: Can't resolve 'module' in '... node_modules/import-fresh/node_modules/resolve-from'
Module not found: Error: Can't resolve 'fs' in '... node_modules/import-fresh/node_modules/resolve-from'
```
if chang webpack config:
```
...
    fallback: {
      fs: false,
      module: false,
    },
...
```
error: 
Module not found: Error: Can't resolve '@babel/helper-module-imports'

run `npm i @babel/helper-module-imports`
build success, but `@fortawesome/fontawesome-svg-core/import.macro` icon return undefined

### Font Awesome version

v6.2.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

mac os 11.6, chrome 105

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by yz-xlame** [comment]
i think code maybe has error, but i use:
```
...
return macroIcon({
        name: 'coffee',
        style: 'solid',
      });
...
```
result: 
```
{"payload":{"error":"(0 , _fortawesome_fontawesome_svg_core_import_macro__WEBPACK_IMPORTED_MODULE_3__.icon) is not a function"},"stacktrace":"TypeError: (0 , _fortawesome_fontawesome_svg_core_import_macro__WEBPACK_IMPORTED_MODULE_3__.icon) is not a function\n 
```

**Comment by yz-xlame** [comment]
```
...
return macroIcon({
        name: 'coffee',
        style: 'solid',
      });
...
```
result:

**Comment by tagliala** [comment]
@robmadole any thoughts?

**Comment by yz-xlame** [comment]
import icon(macroIcon) is undefined
```
WARNING in ./node_modules/babel-plugin-macros/dist/index.js 75:22-29
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
WARNING in ./node_modules/import-fresh/index.js 32:31-48
Critical dependency: the request of a dependency is an expression
```

**Comment by yz-xlame** [comment]
I was able to get results using create react app, I think the webpack configuration may not be right, I have to try it
