### ISSUE TITLE
Icon Request: icon-dance-...

### ISSUE THREAD

**Issue by tjhanks** [FortAwesome/Font-Awesome#1935]
This request is actually a request for multiple dance indicting icons that represent the following

Ballet (ballerina)
Ballroom (two people dancing)
Irish Dance (leprechaun w/iconic bowler hat in dancing mode)
Contemporary or Jazz Dancing (think gronk?)
Tap Dance ( a tap dancer looking person) 

Don't care about gender.

**Comment by bejayoharen** [comment]
+1 I am also thinking of the dancer emoji.

**Comment by MsCharla** [comment]
+1

**Comment by kanaaneh** [comment]
I develop a community site for tango dancers. And I search for icons for male, female and couple tango dancer. Also music instruments like piano, pandoneon, accordion etc...

**Comment by simonfranz** [comment]
+1

tap dancer
![image](https://cloud.githubusercontent.com/assets/1003559/7747562/ea6a17ce-ffbb-11e4-9c6a-a08a00818b12.png)
![imga](http://previews.123rf.com/images/chachar/chachar1309/chachar130900004/22435187-Set-of-ballroom-dancing-and-ballet-icons-illustration--Stock-Vector.jpg)

**Comment by MichaelJCole** [comment]
+1  Let there be fun!

**Comment by Annyeong** [comment]
+1

**Comment by tagliala** [comment]
Sorry, can't leave this open

It doesn't meet our contributing guidelines anymore

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

You are free to open new individual requests but I advise to consider a custom build, merging font awesome with a dance-specific icon set (if any) https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
