### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by bahusafoo** [FortAwesome/Font-Awesome#19364]
Add Discord icon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

discord icon has been added to FontAwesome in version 5.0:
- https://fontawesome.com/icons/discord?f=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
