### ISSUE TITLE
Icon request: icon-scratch

### ISSUE THREAD

**Issue by Nels-J** [FortAwesome/Font-Awesome#19368]
Hi, I've seen an old request from 2016 so I will create a fresh one.

My goal is to be able to use for our association(charity) website.
Our goal is to educate children from 8 to 12 years on coding software skills using Scratch platform as a first tool.

Could you please try to create an Awesome icon 👍🏽 related on Scratch programming language 🙏🏽 

Reference:
Favicon https://scratch.mit.edu/favicon.ico from the official website.
Logo version https://scratch.mit.edu/images/scratch-og.png from the same official website.

Thanks in advance for your huge work !!!
Regards.
Nelson

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Hi, I've seen an old request from 2016 so I will create a fresh one.

Please add a 👍 reaction to #9336

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Comment by Nels-J** [comment]
@tagliala thanks for your answer.
Apologies for my request.
I find a way to add a 👍🏽  reaction on to #9336
Ciao
