### ISSUE TITLE
Bug: Slow Loading Website's main page

### ISSUE THREAD

**Issue by chintan0513** [FortAwesome/Font-Awesome#19363]
### Bug description

Slow Loading Website's main page

### Font Awesome version

6.x

### Serving

Other (as specified in the bug description)

### Implementation

SVG+JS

### Browser and Operating System

Latest Chrome and Windows 11

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Slow Loading Website's main page

Sorry, do you mean fontawesome.com?

**Comment by chintan0513** [comment]
yes a few hours ago it was slow in my region.

**Comment by tagliala** [comment]
Is it now solved?

**Comment by chintan0513** [comment]
yes sir :)

**Comment by tagliala** [comment]
Thanks, closing here
