### ISSUE TITLE
Bug: Font display property missing when using Font Awesome Kit

### ISSUE THREAD

**Issue by comi91** [FortAwesome/Font-Awesome#19376]
### Bug description

Lighthouse reports: Ensure text remains visible during webfont load. This can be solved with font-display:swap for @font-face. See https://web.dev/font-display/?utm_source=lighthouse&utm_medium=devtools
When using a kit with web font, we can not set this property.

### Font Awesome version

latest 6.x version

### Serving

Kit

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome 106 on MacOs

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

This is a false positive and we cannot fix it on our side. Having `font-display:swap` is wrong with icon fonts

In the past I think someone on lighthouse side added FontAwesome to an allowlist of fonts. 

Ref: #16077

Closing here, but feel free to comment
