### ISSUE TITLE
Icon request: Country Flags

### ISSUE THREAD

**Issue by cyleolson-viavi** [FortAwesome/Font-Awesome#19372]
Would be great to see an option to use country flags for something like a website language switcher.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Flags are out of scope, more information at https://github.com/FortAwesome/Font-Awesome/issues/13944#issuecomment-774090007

Please consider an alternative like https://flagicons.lipis.dev/

Closing here
