### ISSUE TITLE
Bug: Sharp cloud-slash looks weird on bottom right

### ISSUE THREAD

**Issue by justinkruit** [FortAwesome/Font-Awesome#19377]
### Bug description

https://fontawesome.com/icons/cloud-slash?s=solid&f=sharp

The Sharp version of cloud-slash has a weird look on the bottom right.

### Screenshots

![image](https://user-images.githubusercontent.com/1642830/195328969-3b76721f-f60a-467d-be85-2f9093f77f71.png)

### Font Awesome version

v.6.2.0

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

- All

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This should now be fixed: https://fontawesome.com/icons/cloud-slash?s=solid&f=sharp
