### ISSUE TITLE
Bug: droplet-percent is smaller than other related icons in height (not occupying the full height)

### ISSUE THREAD

**Issue by nothing-personal-gh** [FortAwesome/Font-Awesome#19384]
### Bug description

This icon https://fontawesome.com/icons/droplet-percent?s=solid&f=classic is not occupying the full height and this looks smaller than its related icons. See the red lines in the screenshot and details.

When this icon is placed next to other Font Awesome icons, it looks smaller and out of scale.

Expected - It needs to be of the same size as the rest of the FA icons.

### Screenshots

This screenshot is taken from https://fontawesome.com/icons/droplet-percent?s=solid&f=classic ('Icons in Action' section).

If you zoom into the `droplet-percent` icon, you'll notice it is smaller than the rest of the icons.

<img width="1227" alt="droplet-percent" src="https://user-images.githubusercontent.com/111722528/195969800-2ba9143a-e787-472d-b107-979b2b97c336.png">

In the 2nd screenshot, notice the gap at the top and the bottom that could be used to make this icon look the same proportion as the rest of the icons.

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/111722528/195969878-bd76e5e2-cd53-497c-867b-b3b7670fd6fb.png">

### Font Awesome version

v6.2.0

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

- Chrome latest on Mac 12.5

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@sensibleworld could you please take a look if the grid is respected for this icon? I can see that it is smaller than [droplet](https://fontawesome.com/icons/droplet?s=solid&f=classic) but has the same size as [droplet-degree](https://fontawesome.com/icons/droplet-degree?s=solid&f=classic)

It is legit to think that `droplet` and `droplet-percent` should have the same size, but I'm not sure

**Comment by nothing-personal-gh** [comment]
@tagliala @sensibleworld Is there an update on this issue? We can submit an issue through a different channel if you prefer as we have a 'Pro' plan.

**Comment by sensibleworld** [comment]
Thanks for the reminder, @nothing-personal-gh. I'm looking into it now.

**Comment by sensibleworld** [comment]
The droplet icons should now be standardized: https://fontawesome.com/icons/droplet-percent?s=solid&f=classic
