### ISSUE TITLE
Icon request: beer

### ISSUE THREAD

**Issue by matkoniecz** [FortAwesome/Font-Awesome#19387]
### Use case

It is clearly popular icon for many purposes, starting with pub POIs

### Example image

https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/svgs/solid/beer.svg (it is gone from v6 release)

See also https://github.com/FortAwesome/Font-Awesome/issues/49 - previous beer icon request

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

You can find the icon with the new name https://fontawesome.com/icons/beer-mug-empty?s=solid&f=classic, but `beer` should still be an alias: https://jsfiddle.net/tagliala/wr154e6x/17/

Hope it helps

Closing here but feel free to comment

**Comment by matkoniecz** [comment]
Sorry that I missed it!
