### ISSUE TITLE
Icon request: Greenhouse Gas, Greenhouse Gas Reduction, general Sustainability

### ISSUE THREAD

**Issue by lnmezz** [FortAwesome/Font-Awesome#19380]
Lots of work happening in the world to save the planet, hoping you guys will jump on this for some greenhouse gas icons!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request form](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+):

>  This is a single icon or matched pair (Ex: lock / unlock) *
>  The request is for a concrete object, or I've included an example image *

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request, having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. Please make sure to provide a good title and an example.

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
