### ISSUE TITLE
UI/bug SignIn in your website Website

### ISSUE THREAD

**Issue by vinaysreddy** [FortAwesome/Font-Awesome#19388]
Hello ! FontAwesome !

Hi I'm Vinay from Hyderabad,India.
My Contact :
mail: omitted
LinkedIn : omitted

I'd like to inform you that there is a UI issue/bug on your website.
Your sign in page functions correctly, however when you follow my steps, a UI issue occurs.
I've provided you with the steps to reproduce the problem/Issue.

steps to reproduce the problem :
1. Go to https://fontawesome.com/
2. in the nav bar go to the docs
3. On the left side chhose the web option
4. Under the web ,On the left side click the Get Started
5. Under the Get Started section go to step one and click on the Set Up the kit
6. raw html page opens.It doesnt have any kind of style.

![image](https://user-images.githubusercontent.com/62655250/196345321-fb89579b-d589-46ae-ad28-abecf0ecff13.png)
![image](https://user-images.githubusercontent.com/62655250/196345372-04b5b844-77fb-4475-8a78-a83905fbc1fb.png)
![image](https://user-images.githubusercontent.com/62655250/196345412-5bbfa625-963f-44c1-96b3-e7c78cf5ee45.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

@talbs it is reproducible by navigating to https://fontawesome.com/kits in an incognito window (= not logged in), I think the style got messed up during the redirect

**Comment by vinaysreddy** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community and thanks for reporting this.
> 
> @talbs it is reproducible by navigating to https://fontawesome.com/kits in an incognito window, I think the style got messed up during the redirect
> Even not in incognito also..may be
Thank You

**Comment by tagliala** [comment]
> Even not in incognito also..may be

Correct. I've asked to check in incognito because this does not affect logged in users

**Comment by jasonlundien** [comment]
Hey there @vinaysreddy ---

This is fixed up now.  If you have other issues or we need to reopen just let us know.
