### ISSUE TITLE
Icon request: baby-bottle

### ISSUE THREAD

**Issue by netdjw** [FortAwesome/Font-Awesome#19395]
It would be nice if there would be added a collection of icons in baby topic.

For example:
- baby bottle
- baby swing
- baby bed
- baby monitor
- diaper
- nappy

...and some other basic things

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from our [new icon request form](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+):

>  This is a single icon or matched pair (Ex: lock / unlock)

Sorry, requests for icon sets are not allowed by our contributing guidelines.

Feel free to open individual requests for the icons you want to request, having care of [searching existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. Please make sure to provide a good title and an example.

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by netdjw** [comment]
@tagliala Thank you for the informations.

It's just a single icon request, the other commented examples are just other ideas. Please feel free to ignore it.

**Comment by tagliala** [comment]
Hi @netdjw ,please add a 👍🏼 reaction to this request: #12752
