### ISSUE TITLE
Bug: notdef icon removed in 6.2.0

### ISSUE THREAD

**Issue by javier-godoy** [FortAwesome/Font-Awesome#19394]
### Bug description

[Notdef](https://github.com/FortAwesome/Font-Awesome/blob/6.1.2/svgs/solid/notdef.svg) icon from 6.1.2 was removed in version 6.2.0 (or, according to https://fontawesome.com/icons/notdef?s=solid it was moved to the Pro library). If it's an intended breaking change, it's not mentioned in the release notes.

### Font Awesome version

v6.2.0

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this issue.

@sensibleworld @robmadole could you please take a look?

**Comment by robmadole** [comment]
@javier-godoy I think this is just a bug. We'll get it added back into the free subset.

**Comment by sensibleworld** [comment]
This should now be fixed!

https://fontawesome.com/icons/notdef?s=solid
