### ISSUE TITLE
Bug: compilation issues when using dart-sass

### ISSUE THREAD

**Issue by vertic4l** [FortAwesome/Font-Awesome#19418]
### Bug description

there are a lot of issues inside of _variables.scss due to missing usage of sass math which should be considered asap.

### Font Awesome version

v6.2.0

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

doesn't matter

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
> there are a lot of issues inside of _variables.scss due to missing usage of sass math which should be considered asap.

Hi, are you referring to FA5? Could you please provide the output of the issues?

**Comment by vertic4l** [comment]
```Bash
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16) or calc(20em / 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules/.pnpm/@fortawesome+fontawesome-pro@6.2.0/node_modules/@fortawesome/fontawesome-pro/scss/_variables.scss 12:25  @import

```

**Comment by vertic4l** [comment]
So your sass code is not compliant which is really bad, see https://sass-lang.com/d/slash-div

**Comment by tagliala** [comment]
Hi, this has been fixed a while ago

https://github.com/FortAwesome/Font-Awesome/blob/d3a7818c253fcbafff9ebd1d4abb2866c192e1d7/scss/_variables.scss#L10

Could you please double check that the npm repo is up to date and that there are no custom overrides of that file?

**Comment by vertic4l** [comment]
Ya, sure here you go:

```bash
Error: Undefined operation "2em * fa-divide(5, 4)".
   ╷
37 │ $fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default;
   │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/.pnpm/@fortawesome+fontawesome-pro@6.2.0/node_modules/@fortawesome/fontawesome-pro/scss/_variables.scss 37:27  @import
  src/common/framework/_settings.scss 67:9                                                                                    @import
  src/common/framework/foundation.scss 1:61                                                                                   root stylesheet
error during build:
Error: Undefined operation "2em * fa-divide(5, 4)".
   ╷
37 │ $fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default;
   │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by tagliala** [comment]
Could you please make sure that `functions` is imported before `variables` ?

Ref:

https://github.com/FortAwesome/Font-Awesome/blob/d3a7818c253fcbafff9ebd1d4abb2866c192e1d7/scss/fontawesome.scss#L9

**Comment by vertic4l** [comment]
i see, my colleague simply imported _variables.scss -.-

thanks for clarifying!

**Comment by tagliala** [comment]
> thanks for clarifying!

Welcome. Glad you have solved

> i see, my colleague simply imported _variables.scss -.-

That was the correct approach. In order to fix this deprecation issue, we had to introduce this new `functions` partial and probably this is an undocumented breaking change for scss customizations, sorry
