### ISSUE TITLE
Bug report: font-awesome script causes error in W3C HTML validator

### ISSUE THREAD

**Issue by andy-guttridge** [FortAwesome/Font-Awesome#19423]
Tested using Google Chrome on Mac OS Monterey.
Script tag in head of HTML is `<script src="https://kit.fontawesome.com/8e1ff888c3.js" crossorigin="anonymous"></script>`.
The error flagged in the validator is **Error: CSS: transform: var(--fa-rotate-angle, none) is not a transform value**.

**Comment by barryp** [comment]
I'm seeing this too with the Nu HTML Validator https://github.com/validator/validator 

For us it's coming from `scss/_rotated-flipped.scss` line 29

```
.#{$fa-css-prefix}-rotate-by {
  transform: rotate(var(--#{$fa-css-prefix}-rotate-angle, none));
}
```

I wonder if it would make more sense to replace the `none` with `0`.  When I tried that the validator was satisfied.

**Comment by robmadole** [comment]
@barryp agreed. `0` makes more sense. Thanks.
