### ISSUE TITLE
I didn't find icon "fa-presentation-screen"

### ISSUE THREAD

**Issue by anfha1** [FortAwesome/Font-Awesome#19424]
Node: v16.18.0
Npm: 8.19.2

Vite: 3.0.9
Vue-tsc: 0.40.7
Vue:  3.2.38

<font-awesome-icon icon="fa-solid fa-presentation-screen" />

I Use
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUser, // OK
  faPresentationScreen, // ERROR
  // 'faPresentationScreen' is declared but its value is never read.ts(6133)
  // Module '"@fortawesome/free-solid-svg-icons"' has no exported member 'faPresentationScreen'.ts(2305)
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faUser, // OK
  faPrescription, // ERROR
)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see that your application is using `@fortawesome/free-solid-svg-icons` but `presentation-screen` is only available in Font Awesome Pro

https://fontawesome.com/icons/presentation-screen?s=solid&f=classic

Hope it helps

Closing here but feel free to comment
