### ISSUE TITLE
Icon request: I want to create a unique icons for my bitcoin cryptocurrency website.

### ISSUE THREAD

**Issue by mardocksteve** [FortAwesome/Font-Awesome#19436]
### Use case

I have a website based on Bitcoin Recovery Tools
Bitcoin recovery tools For seed-based recovery, this is primarily useful in situations in [best bitcoin cash wallet](https://bitrecoverytools.com/) where you have lost/forgotten parts of your mnemonic, or have made an error transcribing it.
I want to create high quality icons for my site.
Please suggest me some new premium as I didnt like the free versions. Thanks. 

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by alex07270** [comment]
Thanks to Mrs Jane who helped me recover all my lost funds in forex and crypto trading including my profits, i was a big fool giving my hard earned money to greedy and scammed brokers, but am so happy i met Jane silva a honest woman who helped me recover all my lost funds, and she also gave me the right signal and platform to trade with, now am able to make $5000 weekly, and am very happy, that is why i cant stop testifying about her, if you are out there still experiencing failure trading in binary option, crypto and forex trading or you want to recover your lost funds trading in binary/ forex trade i will advice you to reach out to
her via email on   janesilva0727 gmail com

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
