### ISSUE TITLE
I found bug in font awesome.

### ISSUE THREAD

**Issue by prankush-sharma** [FortAwesome/Font-Awesome#19437]
I found a bug in the icon for example if you copy direct code from the font awesome website and You use that then the font awesome icon does not work. But if add just fa in last then it worked fine. See below  I added a screenshot of that bug.

![image](https://user-images.githubusercontent.com/60103497/202867818-0c63cc3f-53c5-4ac0-bc61-9306a570d247.png)
The above Image is without adding fa in last.
The below Image is after adding fa in last.
![image](https://user-images.githubusercontent.com/60103497/202867862-510e5dc4-f30b-475f-88d1-846d416075f8.png)

@robmadole

**Comment by sensibleworld** [comment]
@prankush-sharma Hey there! In the example provided, it looks like you're referencing a Duotone icon. Is the kit you're loading a Pro kit, or a Free kit? If a Free kit, then the code you'd want to include is:

`<i class="fa-solid fa-briefcase"></i>`

**Comment by prankush-sharma** [comment]
@sensibleworld thanks for your guidance.
