### ISSUE TITLE
Bug: FA CDN is timing out

### ISSUE THREAD

**Issue by maupin** [FortAwesome/Font-Awesome#19443]
### Bug description

Requests to URLS such as 

https://ka-f.fontawesome.com/releases/v5.15.4/css/free.min.css
https://ka-f.fontawesome.com/releases/v5.15.4/webfonts/free-fa-solid-900.woff2

are not responded to.

### Reproducible test case

See above

### Font Awesome version

v5.15.4

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

Chrome on Windows 10
Chrome on Ubuntu 20.04

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by maupin** [comment]
Appears to be working now.

**Comment by tagliala** [comment]
Thanks for the heads-up
