### ISSUE TITLE
Using the Font Awesome Pro 6.2.1 and instead of the icon it shows weird characters like "ï„…"   "ï€•"  "ï€Š"

### ISSUE THREAD

**Issue by manjindersarkaria** [FortAwesome/Font-Awesome#19449]
I am Using the Font Awesome Pro 6.2.1 and instead of the icon it shows weird characters like "ï„…"   "ï€•"  "ï€Š".

This issue happens only sometime, and on reload page it goes away. I have seen some other people also reported the same in the past like the issue #14660
![Screenshot (49)](https://user-images.githubusercontent.com/21108847/204378198-80d4c1c5-b5d9-4115-b680-1ba47087096e.png)
![Screenshot (50)](https://user-images.githubusercontent.com/21108847/204378201-4fce7c3e-675c-49b7-810f-77e055f5bb28.png)

**Comment by tagliala** [comment]
Hi, I guess your application is using a self-hosted css file compiled from scss.

If it is the case, I recommend you to read throughout #17644

Most relevant comments should be:
- How a proper output css should look like: https://github.com/FortAwesome/Font-Awesome/issues/17644#issuecomment-1222170343
- Attempt to upgrade to dart-sass >= 1.38.0 https://github.com/FortAwesome/Font-Awesome/issues/17644#issuecomment-1071144856
- How to manually fix  the issue (requires effort on every FA upgrade containing new icons): https://github.com/FortAwesome/Font-Awesome/issues/17644#issuecomment-1097828871

If you have more questions, please continue on #17644
