### ISSUE TITLE
rug icon

### ISSUE THREAD

**Issue by ZarminaAhmadi** [FortAwesome/Font-Awesome#19450]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

rug icon has been added to FontAwesome in version 6.1.0:
- https://fontawesome.com/icons/rug?s=solid&f=classic

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

If this request is about something else, pleae fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Closing here, but feel free to comment if I've missed something
