### ISSUE TITLE
Bug: SassError using NextJS CSS compiler

### ISSUE THREAD

**Issue by V-iktor** [FortAwesome/Font-Awesome#19469]
### Bug description

```
SassError: Undefined operation "2em * fa-divide(5, 4)".
   ╷
37 │ $fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default;
   │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@fortawesome\fontawesome-pro\scss\_variables.scss 37:27  @import
```

packages.json

    "@fortawesome/fontawesome-pro": "^6.2.1",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-brands-svg-icons": "^6.2.1",
    "@fortawesome/free-regular-svg-icons": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.2.1",
    "@fortawesome/pro-regular-svg-icons": "^6.2.1",
    "@fortawesome/react-fontawesome": "^0.2.0",

    "next": "12",
    "next-compose-plugins": "^2.2.0",
    "next-routes": "^1.4.2",

### Font Awesome version

6.2.1

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

NodeJS on Windows

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This could be related to a custom css implementation and an update from an older version, please refer to #19418 to find a solution

Also, I can see that this is importing both `@fortawesome/fontawesome-pro` and `@fortawesome/fontawesome-svg-core`.

Usually those are two mutual exclusve implementations, one css-based and one svg-based, so if you are using the css probably it is not needed to import all the svg packages

Ref: https://fontawesome.com/docs/web/setup/packages#_2-install-your-package

**Comment by V-iktor** [comment]
Thanks for the swift reply, this solved my problem: https://nextjs.org/docs/basic-features/built-in-css-support#customizing-sass-options
```js
# next.config.js
module.exports = {
  sassOptions: {
    includePaths: [path.join(__dirname, "src/scss/")],
  },
```
