### ISSUE TITLE
Icon request: flag-nordic-cross

### ISSUE THREAD

**Issue by Xikura** [FortAwesome/Font-Awesome#19463]
What I'm requesting is an off-centered cross on a flag.
A lot of flags have some sort of off-centered cross, in Scandinavia we call it the Nordic cross, but it might have a better and more universal name.

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
