### ISSUE TITLE
Bottom corners Light version shirt

### ISSUE THREAD

**Issue by githubvandeburen** [FortAwesome/Font-Awesome#19472]
The bottom corners of the Light version of the shirt icon are not equal to each other. The corner radius differs.

<img width="626" alt="Scherm­afbeelding 2022-12-19 om 11 51 05" src="https://user-images.githubusercontent.com/120562760/208409562-95c472b2-c434-402a-8f6a-d23ac0d967c0.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and apologies for the late reply.

Thanks for this report, let's assign @sensibleworld !

**Comment by sensibleworld** [comment]
Fixed in `6.4.0`: https://fontawesome.com/icons/shirt?f=classic&s=light
