### ISSUE TITLE
Some icons seem to be shadowed by ligatures

### ISSUE THREAD

**Issue by hgkjshegfskef** [FortAwesome/Font-Awesome#19487]
### Bug description

I was trying to use Font Awesome's icons in a Qt QML program. I have picked 3 icons from a regular free otf font: f09c, f015 and f002 (unicode values according to the search on FA website). The first two depict correctly. The last one is supposed to be a magnifying glass, but in my program it renders as 'fl'. When I try f001 it renders as 'fi'.

So, I think there is some overlap of icon codes with ligatures given that fl and fi are common ligatures. Should I look for some hints to the font renderer inside Qt that I can pass to disable ligatures, or how is this supposed to be handled? This is not necessarily a bug, more of a "what am I supposed to do" type of question.

Note that I also tried FA v4.7 and f002 rendered correctly, probably because v4 did not support ligatures.

v6 (bad):

![2022-12-21-174539_196x430_scrot](https://user-images.githubusercontent.com/83143323/208959222-6ea99571-6cfa-48b4-a1c6-e71dba6af6bd.png)

v4 (good):

![2022-12-21-174554_199x348_scrot](https://user-images.githubusercontent.com/83143323/208959276-75373213-4fb1-49ac-801b-90065dba68d6.png)

### Font Awesome version

v6.2.1

### Application and Operating System

- Qt QML
- Linux

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The first example does not look like FA6

In fact, in FA6, `user-plus` is a lot different: https://fontawesome.com/icons/user-plus?s=solid&f=classic

<img width="625" alt="image" src="https://user-images.githubusercontent.com/556268/208983645-144cabb8-b2e9-408b-a033-73c274e673e7.png">

Please double check

**Comment by hgkjshegfskef** [comment]
Hi! Indeed, the icons in both cases look identical to FA4. Which is strange, because I see in console that I'm using font family "Font Awesome 6 Free" in the first case and "FontAwesome" in the second. In particular, "Font Awesome 6 Free-Regular-400.otf" and "fontawesome-webfont.ttf" respectively. Well, it's only getting more confusing... Seems like the problem is not related to ligatures, it is more fundamental. I'll get back to this if I find anything more.
