### ISSUE TITLE
Brand request: Mastodon.social

### ISSUE THREAD

**Issue by adamjacobi** [FortAwesome/Font-Awesome#19483]
### Description

As many users are fleeing Twitter, individuals and organizations will be adopting other platforms, such as Mastodon.social. 

### Official website

https://mastodon.social/

### Brand guidelines

https://joinmastodon.org/branding

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Isn't this a request for the already existing https://fontawesome.com/icons/mastodon?s=&f=brands ?

**Comment by adamjacobi** [comment]
Strange— I swear that when I searched the icon library yesterday for “Mastodon,” it returned zero results. Please delete/remove this request.
