### ISSUE TITLE
Bug: 401 on @fortawesome/fontawesome-free

### ISSUE THREAD

**Issue by tidusjar** [FortAwesome/Font-Awesome#19488]
### Bug description

Getting the error in my CI builds:
```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/6.2.1/fontawesome-free-6.2.1.tgz: Request failed \"401 Unauthorized\"".
```

package.json contains
```
    "@fortawesome/fontawesome-free": "^6.0.0",
```

I am using yarn in the CI builds.
`.yarnrc.yml` contains
```
nodeLinker: node-modules
```

### Font Awesome version

v6.0.0

### Application and Operating System

Github  Actions

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> `error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/6.2.1/fontawesome-free-6.2.1.tgz: Request failed \"401 Unauthorized\"".`

This is using the private NPM repository, which is limited to Pro users. This may happen if someone installed packages with a specific `.npmrc` configuration on their development machine.

Please reinstall the package using the public npm / yarn repository, or make sure that the CI is able to read the font awesome pro token from a configuration variable and has its correct `.npmrc`

Closing here, but feel free to comment

**Comment by thegecko** [comment]
Just hit this same problem in CI when updating a free version of font-awesome. `yarn.lock` changed from:

```
...
https://registry.yarnpkg.com/@fortawesome/fontawesome-free/-/fontawesome-free-6.3.0.tgz#b5877182692a6f7a39d1108837bec24247ba4bd7
...
```

to:
```
...
https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/6.4.0/fontawesome-free-6.4.0.tgz#1ee0c174e472c84b23cb46c995154dc383e3b4fe"
...
```

When developing projects both with and without the pro license, is the expectation to remember to temporarily rename/move any global `.npmrc` file on the developer's machine during any upgrade of the free package or is there an easier way?

**Comment by tagliala** [comment]
>  is the expectation to remember to temporarily rename/move any global .npmrc file on the developer's machine during any upgrade of the free package or is there an easier way?

Hi, I think per-project `.npmrc` would be the best approach. Maybe you want to commit an `.npmrc` forcing Font Awesome's npm to the public registry
