### ISSUE TITLE
Icon request: fa-flag-my 🇲🇲

### ISSUE THREAD

**Issue by maythukhin4597** [FortAwesome/Font-Awesome#19496]
### Use case

Flag icon for Myanmar which can be used in changing language ( internationalization )
Country : Myanmar 
Language : Burmese
Language-code : my

### Example image

![flag-of-myanmar-logo](https://user-images.githubusercontent.com/39905554/209698068-b25a51b0-e856-43db-9be1-dc6752eb5f73.png)

_Black and white style_
![flag-of-myanmar-logo-black-and-white](https://user-images.githubusercontent.com/39905554/209698115-92725d01-c563-463e-9ebe-55226b931f46.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
