### ISSUE TITLE
Icon request: fa-form

### ISSUE THREAD

**Issue by Roybrussel** [FortAwesome/Font-Awesome#19499]
Hi there,

Wondering if Font Awesome could add a form icon.

Currently there's a fa-wpform that has two "shark-teeths" at the top, but I would like to see a form icon without those shark-teeths, called fa-form.

Let me know your thoughts on this.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #780, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here
