### ISSUE TITLE
Icon request: angle-up-down (or angle-sort)

### ISSUE THREAD

**Issue by pjrvs** [FortAwesome/Font-Awesome#19497]
Similar to "sort": https://fontawesome.com/icons/sort?s=regular&f=classic

But with angles, not triangles, like so:

<img width="278" alt="Screenshot 2022-12-27 at 9 15 53 AM" src="https://user-images.githubusercontent.com/6045483/209699755-9cd0cff0-786f-4876-b19d-28dd4a8082e1.png">

Basically - just combine `angle-up` and `angle-down` :)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is a duplicate of #19434, please add a 👍🏼 reaction to that request

Closing here
