### ISSUE TITLE
Icon request: location-arrow-up

### ISSUE THREAD

**Issue by GaryNicol** [FortAwesome/Font-Awesome#19501]
It would be great to have an icon that could be used for indicating bearing or direction of travel.

The location-arrow icon would be ideal if it was pointing up, as the fa-rotate-by class could then be used to show the appropriate bearing. However currently there's no guarantee the location-arrow will be at a known reference angle, and as it's currently pointing north east it's more complicated to calculate the correct rotation in degrees.

Maybe have bearing-north, bearing-south, bearing-east, and bearing-west icons based on the existing location-arrow icon?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for [location-arrow](https://fontawesome.com/icons/location-arrow?s=solid&f=classic) pointing north?

> However currently there's no guarantee the location-arrow will be at a known reference angle, and as it's currently pointing north east it's more complicated to calculate the correct rotation in degrees.

I do agree, but it is just adding +/-45 to the calculations

Demo: https://jsfiddle.net/tagliala/wr154e6x/23/

**Comment by GaryNicol** [comment]
Hi, yes all I'd really like to see is location-arrow-up or location-arrow-north, but suggested the four bearings as most other arrows are provided in those orientations. In practice, the angle could be anywhere in the range 0-359 so it's not practical to have classes for each degree.

The main reason for the request is that the location arrow just happens to point northwest in the current design, but as this isn't part of the name/definition it could (even if unlikely) change in future.

A named version pointing up would guarantee a starting position (as up will always be up), and by pointing up the bearing in degrees can be used as-is with the FontAwesome custom rotation classes without any additional calculations.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.

**Comment by GaryNicol** [comment]
Happy for this to be marked as completed, but the declined label is incorrect as it was actually implemented earlier this year, I think in 6.5.0? :)
https://fontawesome.com/icons/location-arrow-up

**Comment by sensibleworld** [comment]
Oops! Sorry. We were processing a LOT of open requests and may have mislabeled this one. Fixing!
