### ISSUE TITLE
Icon update: planet-ringed

### ISSUE THREAD

**Issue by Arkellys** [FortAwesome/Font-Awesome#19504]
I don't think the current solid icon for [ringed-planet](https://fontawesome.com/v5/icons/planet-ringed?s=solid&f=classic) is very recognizable compared to the same icon in other styles. Maybe a little update to make the ring more visible would be beneficial. I'm not sure what would be the best way to do that, but here are some examples:

![image](https://user-images.githubusercontent.com/32762018/210208428-0aa6d412-07da-4e23-9abd-5a04cd8fd9cc.png)

**Comment by Arkellys** [comment]
It's not mentioned in the changelog, but if I look on the website the icon seems updated on `v6.6.0`? I have not renewed my pro license yet, so I can't check to confirm.

**Comment by tagliala** [comment]
> It's not mentioned in the changelog, but if I look on the website the icon seems updated on v6.6.0?

Thanks for the heads-up

This has been fixed in 6.5.0

### Before (6.4.2) vs After (6.5.0)
<img width="926" alt="image" src="https://github.com/user-attachments/assets/6943b605-ac41-4f3a-890c-557ca3244b55">
