### ISSUE TITLE
Brand request: WWE Logo

### ISSUE THREAD

**Issue by loveforall1** [FortAwesome/Font-Awesome#19509]
### Description

hi plaese add WWE (World Wrestling Entertainment) Logo
https://1000logos.net/wp-content/uploads/2017/05/WWE-logo.jpg

### Official website

https://www.wwe.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi, please refer to https://github.com/FortAwesome/Font-Awesome/issues/19508#issuecomment-1374820925
