### ISSUE TITLE
FontAwesome wasm takes ~2min to load

### ISSUE THREAD

**Issue by Irtiza90** [FortAwesome/Font-Awesome#19511]
The fontawesome file https://fontawesome.com/wasm/0e56045fcece45e29bc7.wasm
Takes around 2 minutes to load on the [/search](https://fontawesome.com/search) route, on the website
Until it loads it essentially just blocks the entire website from rendering
I don't feel like it's my internet connection, since everything(even when uncached) loads almost instantly

![image](https://user-images.githubusercontent.com/61447963/211526870-cc6bec64-d0a8-4653-8bb2-01cc91918313.png)

**Comment by mlwilkerson** [comment]
Hi @Irtiza90, thanks for the report. I'm looking into it.

I haven't been able to reproduce this yet, despite trying through VPN from several places around the world. From a few places in North America, I'm seeing it load in a matter of milliseconds. From places much further away, I've seen in take as long as about 3 seconds (while everything else takes much longer too).

Could you say approximately from where in the world you're connected to the internet when you see such a slow load time? And what browser you're using?

**Comment by Irtiza90** [comment]
I was experiencing this issue for a couple of days now
Though it seems to have been resolved as the full uncached website now takes ~9s to load
