### ISSUE TITLE
Feature request: Sharp Macro in @fortawesome/fontawesome-svg-core

### ISSUE THREAD

**Issue by mantism** [FortAwesome/Font-Awesome#19516]
### Is your feature request related to a problem?

I wanted to use the new sharp icons in a project of mine but realized there's no macro for it like the following: https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/fontawesome-svg-core/import.macro.d.ts

### Feature description

Adding macro support for sharp icons

### Additional context

I have a commit on my own fork with what I can tell is the necessary change, but I couldn't test with linking the package locally. Linking caused my project to break since it couldn't find the "babel-plugins-macros" after I linked my local "@fortawesome/fontawesome-svg-core" changes. 

Happy to raise a PR if my commit is the necessary change; otherwise looking forward to the feature being added! 
Commit: https://github.com/FortAwesome/Font-Awesome/compare/6.x...mantism:Font-Awesome-Sharp-Macro-Test:6.x

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by mantism** [comment]
Created a PR with my change to hopefully get some attention :) https://github.com/FortAwesome/Font-Awesome/pull/19517

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and also thanks for the PR.

I think this is an issue, let's assign @robmadole and @mlwilkerson

**Comment by mantism** [comment]
Awesome! Excited to see the change 😁

**Comment by robmadole** [comment]
We've updated the docs to account for this: https://fontawesome.com/docs/web/use-with/react/add-icons#add-the-icons-to-your-project
