### ISSUE TITLE
Icon request: Plant-Crop

### ISSUE THREAD

**Issue by nsauce** [FortAwesome/Font-Awesome#19518]
It would be awesome if there was an icon that could represent a crop or field of plants.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Please also provide a single color example, suitable for small icon size
