### ISSUE TITLE
Icon request: Web3

### ISSUE THREAD

**Issue by ZakFerris** [FortAwesome/Font-Awesome#19515]
### Use case

Universal web 3 icon

### Example image

![4657796-200](https://user-images.githubusercontent.com/5018167/212202170-f973f57b-aba7-43f0-974e-d98ac9626427.png)
![Web3-Icon-3](https://user-images.githubusercontent.com/5018167/212202171-d66febd2-4ed8-4342-b2a5-59a2930833cb.png)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Universal web 3 icon

Is this a brand? Is there any official web3 icon?
