### ISSUE TITLE
Icon request: tik tok

### ISSUE THREAD

**Issue by cyberknights2011** [FortAwesome/Font-Awesome#19519]
### Use case

social icons on websites.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TikTok icon has been added to FontAwesome in version 5.13.1:
- https://fontawesome.com/icons/tiktok?s=&f=brands

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
