### ISSUE TITLE
Bug: Can't find fa-twitter in free-solid-svg-icons for example

### ISSUE THREAD

**Issue by Glutch** [FortAwesome/Font-Awesome#19512]
### Bug description

According to the website, free has 2018 icons. But a ton of them is not available in react with free-solid-svg-icons.

I have installed
"@fortawesome/fontawesome-free": "^6.2.1",
"@fortawesome/fontawesome-svg-core": "^6.2.1",
"@fortawesome/free-solid-svg-icons": "^6.2.1",

I've read the docs for 1 hour and tried an insane amount of things, i've honestly never in my life been more confused and irritated with a library. I was interested in purchasing pro but after this experience i'm at a loss for words. Sorry for being dramatic but damn, please make better installation guides.

In multiple instances it says regular is not available for free, but user-regular and others clearly show up in the free category as well
![image](https://user-images.githubusercontent.com/11299527/211555626-9c510b92-119b-45ff-95a3-d8a1e44f3808.png)

### Font Awesome version

v6.2.1

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Windows 11

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> According to the website, free has 2018 icons. But a ton of them is not available in react with free-solid-svg-icons.

That is correct.

Twitter is a brand, so it is part of the [@fortawesome/free-brands-svg-icons](https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons) package

> I have installed
> "@fortawesome/fontawesome-free": "^6.2.1",
> "@fortawesome/fontawesome-svg-core": "^6.2.1",
> "@fortawesome/free-solid-svg-icons": "^6.2.1",

According to your use case, you need only `@fortawesome/fontawesome-free` or `@fortawesome/fontawesome-svg-core + @fortawesome/free-solid-svg-icons`.

If I'm got it correctly, you need this in react, so you should go for `@fortawesome/fontawesome-svg-core + @fortawesome/free-solid-svg-icons + @fortawesome/react-fontawesome` 

Ref: https://fontawesome.com/docs/web/use-with/react/

> I've read the docs for 1 hour and tried an insane amount of things, i've honestly never in my life been more confused and irritated with a library. I was interested in purchasing pro but after this experience i'm at a loss for words. Sorry for being dramatic but damn, please make better installation guides.

Apologies for the confusion, there are a lot of information and a lot of different approaches to use Font Awesome. It may definitely improve, but it is not straightforward to provide a solution that works for everyone

In case of React, I would mainly refer to:

- https://fontawesome.com/docs/web/use-with/react/

And then take a look at:
- https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment
