### ISSUE TITLE
Icon request: Adobe Experience Manager 

### ISSUE THREAD

**Issue by gururajkoni04** [FortAwesome/Font-Awesome#19520]
Adobe Experience Manager 
![adobe-experience-manager](https://user-images.githubusercontent.com/58479039/212835499-535d7655-84a5-4ad5-bca5-4fc5644c4f59.svg)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We can't add Adobe icons. Existing ones have been removed in version 5.15 by request of Adobe

Closing here
