### ISSUE TITLE
Icon request: resale

### ISSUE THREAD

**Issue by ablyanant** [FortAwesome/Font-Awesome#19521]
please create an icon for resale.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Please also provide a single color example, suitable for small icon size
