### ISSUE TITLE
Icon request: icon-motorbike

### ISSUE THREAD

**Issue by ranaanees** [FortAwesome/Font-Awesome#1953]
Please Add Vehicle Icons for

~~Cars~~
Motorbikes
~~Boats~~
~~Accessories~~

I will be great full for adding above icons. Please also guide how to add by myself.

**Comment by auro1** [comment]
+1 motorcycle

**Comment by filipecoelho** [comment]
+1 motorcycle

**Comment by filipecoelho** [comment]
How +1 you take into account to send an icon to production

**Comment by tagliala** [comment]
@filipecoelho on every new release, dave takes a look at the most popular requests sorted by comments descending. So popular requests have more chances of being included (but this is not a guarantee they will be included)

If you need this icon, you should consider a custom build of fontawesome

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

**Comment by Izopi4a** [comment]
+1

**Comment by tagliala** [comment]
added to 4.3.0
