### ISSUE TITLE
Conflict with Classic Editor

### ISSUE THREAD

**Issue by dkeil1** [FortAwesome/Font-Awesome#19537]
I thought I would pass this on. I had an issue with the Rank Math pop-up to edit snippet in a blog post getting jammed to the bottom right of the admin window and being uneditable. I ran through support with Thrive architect, and I'd like to pass on what was found. 

From Thrive Support:
Thank you for the staging site. I also reproduced the issue using my test site when the following plugins are active.

- Font Awesome
- Classic Editor
- Rank Math
- Thrive Architect

There are no issues with Thrive Architect and Rank Math. The Font Awesome plugin has CSS styling and changes the display position of the snippet editor.
Please see: [https://share.getcloudapp.com/geuODmEz](https://share.getcloudapp.com/geuODmEz)
This happens when the Classic Editor plugin is active. When the editor plugin is not active, it displays the Rank Math snippet editor properly, including when Thrive Architect is not active.
Please see: [https://share.getcloudapp.com/JruyQOeq](https://share.getcloudapp.com/JruyQOeq)
I also checked this on your staging site. I temporarily deactivated the Classic Editor and Thrive Architect.
I left the other plugins active, including your Blankslate Child theme. Please see the attached file for the result. It also shows the snippet editor properly when Thrive Architect is active.
I ensured all the plugins are active after troubleshooting the staging site.
Could you reach out to Font Awesome support to get their insights about the CSS styling on this [link][https://staging7.3dmusclelab.com/wp-content/plugins/font-awesome/admin/build/13-1f33c0125262002faa9f.css](https://staging7.3dmusclelab.com/wp-content/plugins/font-awesome/admin/build/13-1f33c0125262002faa9f.css)? It changes when the Classic Editor is active.
Please see: [https://share.getcloudapp.com/qGuZ47BQ](https://share.getcloudapp.com/qGuZ47BQ)
We hope that helps. Let us know what they say, or if you have questions.
Best regards,
Bel
[https://thrive-themes-c066d11065e2.intercom-attachments-1.com/i/o/661802370/030b4f6f6acdc2ec441b74cd/Font+Awesome+and+Classic+Editor+conflict.mp4](https://thrive-themes-c066d11065e2.intercom-attachments-1.com/i/o/661802370/030b4f6f6acdc2ec441b74cd/Font+Awesome+and+Classic+Editor+conflict.mp4)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

@mlwilkerson does this belong to the https://github.com/FortAwesome/wordpress-fontawesome repository?

**Comment by mlwilkerson** [comment]
@tagliala yes, it does appear that the CSS rules producing this conflict come from code in the `wordpress-fontawesome` repo, so that's the appropriate place for the issue.

**Comment by tagliala** [comment]
Unfortunately I do not have permission to transfer this issue to wordpress-fontawesome

**Comment by dkeil1** [comment]
Sorry about posting it here. It was the link I was given by Thrive. I'll repost it there.
