### ISSUE TITLE
service

### ISSUE THREAD

**Issue by Alkeshit** [FortAwesome/Font-Awesome#19531]
please Service icon Provide.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something
