### ISSUE TITLE
fahome in V5 icon lost in V6

### ISSUE THREAD

**Issue by redevill** [FortAwesome/Font-Awesome#19538]
### Use case

fahome icon in V5 has a chimney and a see through "eve"
While looking through the documented name changes
e.g. home -> house
The house icon IS NOT THE SAME ICON in V6... looking through all the renames involving home, NONE of these icons is the same.

What did you expect?
That we don't lose the use of icons through the upgrade process

this is NOT so awesome.

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> The house icon IS NOT THE SAME ICON in V6... looking through all the renames involving home, NONE of these icons is the same.

Apologies for the inconvenience

You can use https://fontawesome.com/icons/house-chimney?s=solid&f=classic

Icons in FA6 have been redesigned, including home. Having a home without the chimney has been requested by the community, you can take a look at #1397 for more details

A proper replacement for FA5's `home` would have been FA6's `house-chimney`, but we may not consider minor changes or improvement to the icon style as breaking changes. The intention here was to provide a more modern design for the house icon by default, leaving the option to go back to the old design on choice

Hope it helps, closing here but feel free to comment

/cc @robmadole
