### ISSUE TITLE
Bug: Changelog 6.3.0

### ISSUE THREAD

**Issue by ppizarror** [FortAwesome/Font-Awesome#19549]
### Bug description

Changelog https://fontawesome.com/docs/changelog/ points to [circle-three-quarter-stroke](https://fontawesome.com/icons/circle-three-quarter-stroke?s); however, the such icon does not exist, as there is a typo; the icon name must be "circle-three-quarters-stroke".

Also, searching https://fontawesome.com/search?q=circle-quarter&o=r does not return "circle-three.." results, which is weird.
Thanks for your amazing work!

### Font Awesome version

6.3.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- N/A

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

I've also noticed this, I think that @sensibleworld is already on it

**Comment by kamilsk** [comment]
Hi! I want to add extra scope to the issue to avoid opening a new one. Version 6.3.0 has incorrect reference in `@fortawesome/pro-light-svg-icons` to `@fortawesome/fontawesome-common-types`. Please take a look at dependabot's build https://github.com/tact-app/web/actions/runs/4141564937/jobs/7161282273#step:6:19
