### ISSUE TITLE
Icon request: curriculum-vitae CV icon

### ISSUE THREAD

**Issue by Toppercitos** [FortAwesome/Font-Awesome#19542]
It would be helpful for portfolio websites. So employers could directly download the CV  or be redirected to it by clicking on the icon.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro: https://fontawesome.com/icons/file-user?style=solid&s=solid&f=classic

Please remember that **in a web application** it is possible to create the requested icon in FA Free by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/178/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

Hope it helps

Closing here
