### ISSUE TITLE
tripadvisor icon not working

### ISSUE THREAD

**Issue by BryanGarro25** [FortAwesome/Font-Awesome#19545]
"fab fa-tripadvisor" is not working, I tried to find it in the newest version and I couldn't. I have a tourism platform and I really need it. 

Version fontawesome-pro-6.2.0-web

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

as per the pinned issue #18180, Tripadvisor asked to remove the icon and it has been done in version 5.15.4

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5154---2021-08-04
