### ISSUE TITLE
faFileSignature

### ISSUE THREAD

**Issue by CreativeArtDesign** [FortAwesome/Font-Awesome#19541]
faFileSignature this does not work for me in reactjs freefonts all other works so far.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) and provide a minimum reduced test case showing the issue

Closing here, but feel free to comment if I've missed something
