### ISSUE TITLE
Bug: asterisk and plus icons break on FontAwesome 6

### ISSUE THREAD

**Issue by dwilches** [FortAwesome/Font-Awesome#19548]
### Bug description

I updated from version 5.15.4 to 6.2.1 and noticed the fa-plus and fa-asterisk icons started to look very small.

Upon closer inspection I saw in DevTools that `.fa-plus::content` had unicode `\f067` in my app when using FontAwesome 5, but when using FrontAwesome 6 it had unicode `\2b`.

I then tested adding to my v6 app this custom CSS, and the icon started looking good again:

```
.fa-plus::content {
  content: "\f067";
}
```

I also tried with this CSS, and it also makes the v6 icon look good:

```
.fa-plus {
  font-family: "FontAwesome", serif;
}
```

Is this a bug in FontAwesome?

This is how I'm importing FontAwesome in my app:

    <link rel="stylesheet" href="assets/fontawesome/css/all.min.css" >
    <link rel="stylesheet" href="assets/fontawesome/css/v4-shims.min.css" >
    <link rel="stylesheet" href="assets/fontawesome/css/v5-font-face.min.css" >

I tested removing v4-shims and v5-font-face and the result was the same, so it didn't look like the compatibility was the issue.

Finally, I noticed on the [changelog](https://fontawesome.com/docs/changelog/) of version 6.1.1 you mentioned:
> Brought back a handful of version 4 compatibility unicode aliases (like "plus" and "asterisk") that were incorrectly removed in 6.1.0
Which seemed related as it mentions the 2 icons I'm having trouble with.

Thanks.

### Screenshots

This is how my app used to look like with v5:
![image](https://user-images.githubusercontent.com/3975401/217110640-7bb02f98-a03f-4544-9eae-e78542730837.png)

And this is with v6, the icon looks quite small:
![image](https://user-images.githubusercontent.com/3975401/217110692-1321a739-f608-4ae9-8c4c-98d1b6f69535.png)

### Font Awesome version

6.2.1

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Browser: Chrome Version 109.0.5414.119 (Official Build) (64-bit)
OS: Ubuntu 22.04.1 LTS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by dwilches** [comment]
I came back today to the same application, same code, and now both fa-plus and fa-asterisk look correctly on FontAwesome 6. A bit thinner, but with the right size.

Maybe something related with a cache in Chrome?

**Comment by tagliala** [comment]
> Maybe something related with a cache in Chrome?

Hi, yes, that is possible. 

> ```
> <link rel="stylesheet" href="assets/fontawesome/css/all.min.css" >
> <link rel="stylesheet" href="assets/fontawesome/css/v4-shims.min.css" >
> <link rel="stylesheet" href="assets/fontawesome/css/v5-font-face.min.css" >
> ```

I suggest to fingerprint your assets

Eg: `assets/fontawesome/css/all.some-long-hash.min.css`
Eg: `assets/fontawesome/webfonts/fa-solid-900.some-long-hash.woff2`

and add long expiry time in response headers if you are self-hosting Font Awesome. This will eliminate cache issues and preserve performance

Please also remember to always update the `webfonts` folder together with the css
