### ISSUE TITLE
Brand request: new Ubuntu logo

### ISSUE THREAD

**Issue by garak** [FortAwesome/Font-Awesome#19553]
### Description

Ubuntu recently changed its main logo

Attached (sorry, it's white on transparent, so you can see it only with dark backgrounds):
![CoF_white](https://user-images.githubusercontent.com/179866/217744371-518a9d17-739e-4b77-ae9c-7eccf02a3d4f.svg)

### Official website

https://design.ubuntu.com/resources#logos

### Brand guidelines

https://design.ubuntu.com/brand

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Ciao,

thanks for the heads-up!

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Looks like this logo hasn't quite been rolled out everywhere. They're still using the old logo on the ubuntu homepage. I'm hesitant to change our glyph until that's been updated.

![CleanShot 2023-03-01 at 09 02 21@2x](https://user-images.githubusercontent.com/529604/222162990-961852d3-c041-470f-8ae4-c7c4be90522e.png)

Also, it seems like the new logo might need to be contained within the vertical rectangle?

**Comment by garak** [comment]
If you check all their official social media (twitter, instagram, facebook), the logo is simply inside a circle, no need for the rectangle

**Comment by Neustradamus** [comment]
Any progress on it?

**Comment by sensibleworld** [comment]
Sorry, folks. This was meant to be added to the 6.4.2 release, but it slipped through the cracks. I've added it to our next release.

**Comment by sensibleworld** [comment]
This has been updated: https://fontawesome.com/icons/ubuntu?f=brands&s=solid

**Comment by Neustradamus** [comment]
@sensibleworld, @tagliala: Thanks a lot!
