### ISSUE TITLE
front awesome not working on Microsoft edge 

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#19559]
I use a apple MacBook to code and my main browser is safari but at times I also use Microsoft edge

when I use Microsoft edge the font awesome I have used does not work but it does work on safari

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/106849792/218756131-06a93cfd-c019-47dd-a0c8-bb764b071bab.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/106849792/218756192-0fa69d21-a0d4-4bfb-a3bb-151cdf34aa3b.png">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

Closing here, but feel free to comment if I've missed something
