### ISSUE TITLE
bug: fa-gear duotone is only a single tone

### ISSUE THREAD

**Issue by lilyhilldev** [FortAwesome/Font-Awesome#19550]
Couldn't find a better place to put this issue since I assume the duotone/pro libraries are private.

The `gear` duotone primary and secondary layers are identical so it doesn't actually behave like a duotone - it's just an alternate solid icon. I would expect the middle dot within the gear to be on the secondary layer but this isn't the case. I have some older copies of this SVG from a couple of months ago (as well as [the v5.15.4 docs](https://fontawesome.com/v5/icons/cog?s=duotone&f=classic) which seems to have the inner circle placed on the second layer correctly so I assume this is a regression in a recent release. 

See this image below from the v6.3.0 official docs:

https://fontawesome.com/icons/gear?s=duotone&f=classic

![image](https://user-images.githubusercontent.com/12396191/217448115-7540b35d-c95a-4c4d-8265-bfe839e885e2.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Assigning to @sensibleworld

**Comment by sensibleworld** [comment]
Fixed in `6.4.0`: https://fontawesome.com/icons/gear?f=classic&s=duotone&sc=%231E3050

**Comment by lilyhilldev** [comment]
Thank you!
