### ISSUE TITLE
Regular `narwhal` variant appears to be incorrect

### ISSUE THREAD

**Issue by cah-bryce-glass** [FortAwesome/Font-Awesome#19566]
The [Classic Regular Narwhal](https://fontawesome.com/icons/narwhal?s=regular&f=classic) icon appears to be improperly filled, and looks kind of like a degraded 'Solid' variant instead. 

**Problem in Context**

Here's a comparison of several of the `Regular` animal icons all in context. The narwhal is the only one that isn't a medium stroke with no / transparent fill. 

![image](https://user-images.githubusercontent.com/81712313/219687459-87354fbe-3eb1-43c9-a8d4-626ff9e07d07.png)

** Steps to Confirm ** 

1. Visit the Browse / gallery page for all `Classic Regular Animals` icons: https://fontawesome.com/search?o=r&c=animals&s=regular&f=classic
2. Visually confirm that the narwhal stands out amongst the set. It's the only one w/a filled, `Solid` appearance
3. Visit the search results for all Narwhal variants: https://fontawesome.com/search?q=narwhal&o=r&c=animals to further compare. It's missing an eye! 

TIA for looking into it!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

Let's assign @sensibleworld

**Comment by sensibleworld** [comment]
Fixed in `6.4.0`: https://fontawesome.com/icons/narwhal?f=classic&s=regular

**Comment by cah-bryce-glass** [comment]
Narwhals rejoice!
