### ISSUE TITLE
Bug: Dynamic Import does not work with React and Vite

### ISSUE THREAD

**Issue by mtrivera** [FortAwesome/Font-Awesome#19560]
### Bug description

I'm trying to Dynamic Import fonts with React and Vite but it does not work. I have a `babel-plugin-macros.config.cjs` with the provided code from the docs. See sandbox for issue.

### Reproducible test case

https://codesandbox.io/p/github/mtrivera/business-card/draft/nameless-river?workspaceId=40e5ff70-66f3-488d-915e-e4b3677ef383&file=%2Fsrc%2Fcomponents%2FFooter.jsx&selection=%5B%7B%22endColumn%22%3A2%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A11%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cle5h2eov0004fth1hcazc2yp%2522%252C%2522openFiles%2522%253A%255B%2522%252Fbabel-plugin-macros.config.cjs%2522%252C%2522%252Fvite.config.js%2522%252C%2522%252Fsrc%252Fcomponents%252FFooter.jsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cle5h2h8s000e2a6f5bmhtzis%2522%253A%257B%2522key%2522%253A%2522cle5h2h8s000e2a6f5bmhtzis%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cle5h2lfl007u2a6ffxf3cq1n%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cle5h2js0003t2a6fg6zhkne2%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cle5h2h8s000e2a6f5bmhtzis%2522%252C%2522spacesOrder%2522%253A%255B%2522cle5h2h8s000e2a6f5bmhtzis%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### Screenshots

![Untitled](https://user-images.githubusercontent.com/10368105/218990120-f722436d-559b-4e5c-903d-a91428d10269.png)

### Font Awesome version

v6.3.0

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

- Firefox 109.0.1 on Windows 10 64-bit

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi,

the reproducible test case link is broken, however

> config license must be either 'free' or 'pro'

please take a look at #18711 and #18714

**Comment by mtrivera** [comment]
#18711 resolved my issue
