### ISSUE TITLE
Bug: Gear icon is off-centered, and looks bad when spinning

### ISSUE THREAD

**Issue by hugoattal** [FortAwesome/Font-Awesome#19564]
### Bug description

Just the title: the gear icon is off-centered. I think it's a regression because I think it was centered a few versions back... When spinning, it looks a bit cheap (you can see a live example in the FontAwesome documentation).

### Reproducible test case

https://fontawesome.com/icons/gear?s=solid&f=classic

### Screenshots

![image](https://user-images.githubusercontent.com/4563971/219498894-eae0dccd-2759-44b5-89b4-73b47db75532.png)

### Font Awesome version

v6.3.0

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

Firefox, Chrome, probably all of them

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

I think this is a regression introduced in 6.3.0

6.2.0: https://jsfiddle.net/tagliala/ryuf9kdb/
6.3.0: https://jsfiddle.net/tagliala/ryuf9kdb/1/

Let's assign @sensibleworld

**Comment by jxn-30** [comment]
I've seen the same issue for `arrows-rotate` icon:
![grafik](https://user-images.githubusercontent.com/27238105/219661058-d866cb88-fca9-4178-bc57-4afcbd9c78e9.png)

**Comment by sensibleworld** [comment]
Yup. Sorry about this folks. We had a regression introduced in some of our upload code that we missed. We'll get these fixed up in the next release.

**Comment by sensibleworld** [comment]
Fixed in `6.4.0`

![CleanShot 2023-03-27 at 13 49 23](https://user-images.githubusercontent.com/529604/228024614-be78f161-5064-4385-aee1-cfb50e18b7e4.gif)
