### ISSUE TITLE
Bug: Error: https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro: Not found

### ISSUE THREAD

**Issue by JoelBonetR** [FortAwesome/Font-Awesome#19574]
### Bug description

I followed the instructions on the [documentation](https://fontawesome.com/docs/web/setup/packages#installing-pro)

First I added a `.yarnrc.yml` with the required content like that:

```
npmScopes:
 fortawesome:
   npmAlwaysAuth: true
   npmRegistryServer: "https://npm.fontawesome.com/"
   npmAuthToken: "MY-TOKEN"
```

Then:

`yarn add @fortawesome/fontawesome-pro`

I get:

```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro: Not found".
```

Then I added the `.npmrc` like that:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=MY-TOKEN
```

and then `yarn add @fortawesome/fontawesome-pro` worked in my machine, though it wasn't clear I need both according to the documentation, it looks like different options to reach the same to me ( **do we really need both?** ).

_________________

**Issue:**

Still, when I commit everything, it fails in the CI pipeline (GCP, Cloud Build) as:

`An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2ffontawesome-pro: Not found".`

- Tested running `yarn cache clean`
- Tested deleting `node_modules` and `yarn.lock`
- Tested without `.yarnrc.yml`
- Tested without `.npmrc`

And no difference at all on any of those tries.
_________________

To avoid duplicates, I already checked those issues:

https://github.com/FortAwesome/Font-Awesome/issues/15332
https://github.com/FortAwesome/Font-Awesome/issues/12349

And some different issues in sources other than github

### Font Awesome version

v6.3.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- Chrome@latest on Macbook Pro 14 with M1 Pro (latest OSx)
- Build failed in Cloud Build. Dockerfile raising **node:18.12.1-alpine**

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> do we really need both?

No, both are not needed

Which version of yarn are you using? 

Please check on both your machine and on the CI. `.yarnrc.yml` is only supported by yarn >= 2.x

**Comment by JoelBonetR** [comment]
Hi @tagliala thank you for your quick response.

Right then, my bad on this one as I didn't check the details. We're using yarn v1.x (latest), I may try to migrate to yarn v2.x.

Am I right assuming we should use `.npmrc` with yarn 1.x while using `.yarnrc.yml` when using yarn 2.x?

If it's the case, I already tested deleting the `.yarnrc.yml`, keeping the `.npmrc` and the issue persists.

**Comment by tagliala** [comment]
> Am I right assuming we should use .npmrc with yarn 1.x while using .yarnrc.yml when using yarn 2.x?

Correct. Maybe not that visible, but it's in the documentation too

> If it's the case, I already tested deleting the .yarnrc.yml, keeping the .npmrc and the issue persists.

Please remove font awesome from the lock file and reinstall, being sure that the `.npmrc` is there and has been correctly loaded and configured.

You can use:
1. `yarn --verbose` to check the list of configuration files that yarn is trying to include and what is actually included
2. `yarn config list` to check that the `//npm.fontawesome.com/:_authToken':` is properly set

Then check that in the lock file the font awesome package urls are pointing to the private NPM repo (`https://npm.fontawesome.com/`)

You may need to run those commands also on the CI

**Comment by JoelBonetR** [comment]
Hi @tagliala thank you for your insights.

Realized that the .npmrc was not being copied inside the workdir of the CI, now everything seems to work just fine, thank you

**Comment by tagliala** [comment]
Welcome, glad you solved
