### ISSUE TITLE
Icon request: fa-tiktok

### ISSUE THREAD

**Issue by carolinagalvan** [FortAwesome/Font-Awesome#19583]
### Use Case
- Social media icon for Tik Tok

### Example Image
- Example of icon [here](https://cdn-icons-png.flaticon.com/512/1946/1946552.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

TikTok icon has been added to FontAwesome in version 5.13.1:
- https://fontawesome.com/icons/tiktok?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
