### ISSUE TITLE
Add 'fa-monument' to the 'maps' category

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#19584]
I think [fa-monument](https://fontawesome.com/icons/monument) icon should be part of the `maps` category.

Regards.

**Comment by sensibleworld** [comment]
This is now live!

<img width="1177" alt="CleanShot 2023-03-27 at 13 51 00@2x" src="https://user-images.githubusercontent.com/529604/228024939-31a2355c-6201-4646-bfc6-1ec720b72331.png">
