### ISSUE TITLE
Bug: fontawesome kit causes CORS error

### ISSUE THREAD

**Issue by ChiuMungZitAlexander** [FortAwesome/Font-Awesome#19586]
### Bug description

As the screenshot shows, the kit js `https://kit.fontawesome.com/205d88d001.js` is successfully loaded and executed.

But the scripts - `https://ka-f.fontawesome.com/releases/v6.3.0/css/free-v5-font-face.min.css?token=205d88d001` triggered by kit js throw CORS error.

Also, I haven't set any domains, which means any domain could call the kit script.

For more details please check this codepen https://codepen.io/alexandermzchiu/pen/RwYKRRx.

### Screenshots

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22234622/221786492-0b2329aa-c4bb-4f82-8557-f32bb694eb3d.png">

<img width="671" alt="image" src="https://user-images.githubusercontent.com/22234622/221787316-08a24442-94c7-4cc7-adb6-4f92826720a4.png">

### Font Awesome version

Latest 6.x

### Serving

Kit

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- Chrome 110

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hi @ChiuMungZitAlexander I was unable to reproduce

![eiffrYqj@2x](https://user-images.githubusercontent.com/132895/221893117-59529344-73b0-4745-be1d-ffe47b234cdc.png)

Could this be something specific to the browser you are using? Chrome extensions? Network firewall or security applicance?

**Comment by ChiuMungZitAlexander** [comment]
> Hi @ChiuMungZitAlexander I was unable to reproduce
> 
> ![eiffrYqj@2x](https://user-images.githubusercontent.com/132895/221893117-59529344-73b0-4745-be1d-ffe47b234cdc.png)
> 
> Could this be something specific to the browser you are using? Chrome extensions? Network firewall or security applicance?

I tried on Chrome, Edge and Safari, and found the problem only occurs on Chrome. I got a solution from stackoverflow that chrome auto banned the scripts which it regards as insecure ones.

To solve, go to `chrome://flags` and disable `Block insecure private network requests.`.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/22234622/222040058-a0e8b485-35e9-4d5d-ae47-6c819fada6a9.png">

**Comment by csteel03** [comment]
I am having the same issue as well but just loading the kit JS file renders a CORS error. This is happening on Firefox Version 113.0.1 (Mac OS Monterey).
![Screen Shot 2023-05-30 at 2 35 09 PM](https://github.com/FortAwesome/Font-Awesome/assets/1828669/4b3b80ad-04ba-450f-ab15-9676a7da3337)

**Comment by csteel03** [comment]
Looks to be fixed as of 2023-05-30 19:07 UTC.

**Comment by robmadole** [comment]
We believe we have this service back on and 100% operational. We'll do an investigation as to the root cause and update the incident on status.fortawesome.com.

**Comment by robmadole** [comment]
We've posted a post-mortem for those interested: https://status.fortawesome.com/incidents/4mtvlkjd09ng.

**Comment by bambielli** [comment]
Is this happening again? I just noticed it today.

**Comment by charleslstone** [comment]
Me as well....

**Comment by hungtruongquoc** [comment]
I have the same problem now
![Screenshot 2024-04-25 at 3 11 37 PM](https://github.com/FortAwesome/Font-Awesome/assets/1299962/f5a851d3-c4c9-4d03-a3de-71a20d3275ba)

**Comment by jasonbraun** [comment]
Me too.

**Comment by sheadawson** [comment]
+1. I think half the world's icons are not loading...

**Comment by tagliala** [comment]
Hi, apologies for the inconvenience

This is affecting the hosted kits. Please follow incident updates at https://status.fortawesome.com/

**Comment by julianmaria** [comment]
here comes again!

**Comment by bernespinoza** [comment]
here comes again!
