### ISSUE TITLE
YouTube icon in violation of YouTube branding guidelines (if colored and used on a non-white background without additional CSS)

### ISSUE THREAD

**Issue by robjbrain** [FortAwesome/Font-Awesome#19587]
I've been contacted by YouTube and told that my website is not following [YouTube branding guidelines](https://developers.google.com/youtube/terms/branding-guidelines) because the colours in the icon (red and white) have changed. Although it is easy to colour the icon red (#FF0000) it seems like the symbol in the middle is always transparent so it's impossible to use it on anything other than a white background.

This screenshot is taken from your own [Youtube Icon Example Page](https://fontawesome.com/icons/youtube?s=solid&f=brands) which shows the symbol in the middle taking the background colour rather than staying white.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/10143910/222007948-ef22d97e-1f72-42b3-9f1e-79aa73cf4ae7.png">

I assume this is a common issue but haven't found anyone else talking about it.

I believe we are at risk of losing our access to the YouTube API and the ability to login to YouTube via oAuth unless we are able to resolve this.

Is there a way to force the icon to follow YouTube's branding guidelines?

**Comment by sensibleworld** [comment]
@robjbrain As noted on all of our brand icon pages, we recommend checking with trademark owners for rules about appropriate use of their trademarks. In the case of the YouTube logo, I did look at their recommendations, and it seems the following are okay.

<img width="851" alt="CleanShot 2023-03-13 at 14 09 03@2x" src="https://user-images.githubusercontent.com/529604/224791407-75be9590-3b7b-4752-aa35-ecff074b5d77.png">

And from this page: https://www.youtube.com/howyoutubeworks/resources/brand-resources/#logos-icons-and-colors

> If it's difficult to see the full-color logo over a specific color or image you can use a monochrome logo instead.
> 
> In monochrome logos the icon is the same color as the wordmark (either Almost Black or White). The triangle in the icon is knocked out so the background shows through.
