### ISSUE TITLE
Icon request: icon-pronouns

### ISSUE THREAD

**Issue by ivanasetiawan** [FortAwesome/Font-Awesome#19592]
I work at a company that focuses on diversity and inclusion. We ask all of our users "What pronouns do you use?" so it would be great if we can have an icon for it.

Thank you in advance.

**Comment by aethior** [comment]
Hi @ivanasetiawan,
Something like https://pronouns.design/?

@tagliala `genders (category)` label for this request? (is not perfect, but it is the most related)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  so it would be great if we can have an icon for it.

It is hard to make an icon to represent pronouns, so it is why in our [icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) we ask for concrete objects

Closing here, but feel free to edit the first message with an example and I will reopen or start a a new request by filling out the [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

---

> Something like https://pronouns.design/?

I would rather create a different issue, or even a brand request

Also, quoting from that website:

> This project is currently work in progress and is subject to a little more reviewing and tweaking of the concept to ensure icons are available in a vast variety of weights and styles, but also meet accessibility criteria around contrast ratios and colour blindness.

PS: An icon with three circles is also used to represent filters (iOS Photo), and this design looks pretty common: https://thenounproject.com/icon/colors-2812202/
