### ISSUE TITLE
Feature request: Color selector for icon on website

### ISSUE THREAD

**Issue by jceb** [FortAwesome/Font-Awesome#19619]
### Is your feature request related to a problem?

From time to time I copy icons directly from the fontawesome website into a word document or miro. Esp. miro isn't able to do much with the SVG apart from displaying in the color that is stored in the document. I'd change the color of the icon directly on the fontawesome website so that the SVG comes with right color directly encoded.

### Feature description

I'd like to have an extended version of the Icon Wizard that allows me to pick a color for the icon and the option to directly download the modified version.

### Alternatives

Improve miro's and various other application's SVG capabilities so that I can select the desired color in the application.

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This should now be possible with our latest site update! Just change the color of an icon, and click the download button.

https://fontawesome.com/icons/bulldozer?f=classic&s=solid&pc=%23ff9300
