### ISSUE TITLE
Icon request: icon-hamburger

### ISSUE THREAD

**Issue by florenceyeun** [FortAwesome/Font-Awesome#1961]
A hamburger icon would be quite useful.
- Hamburgers are delicious.
- (No) hamburgers are the universal symbol for (no) food. [ISO 7010:2011](https://www.iso.org/obp/ui/#!iso:grs:7010:2:P022)

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone via #1895 

Note that this could be shifted to a future release

**Comment by G-Driver** [comment]
+1
<img src="https://cdn0.iconfinder.com/data/icons/cosmo-food-2/40/burger_2-512.png">

**Comment by Bana0615** [comment]
+1

**Comment by zamus1** [comment]
+1

**Comment by abidin13** [comment]
+1

**Comment by kwaaui** [comment]
+1
![burger](https://cloud.githubusercontent.com/assets/484470/8330929/36b3024c-1a85-11e5-9427-3153c76bcd2e.png)

**Comment by nicho90** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by ThiagoFerreir4** [comment]
+1

**Comment by mikejoyceio** [comment]
+1

**Comment by indigoshade** [comment]
+1

**Comment by jenevedube** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-hamburger was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by newdark** [comment]
+1

**Comment by Crissov** [comment]
🍔 [U+1F354](http://emojipedia.org/hamburger/) Unicode emoji #222

**Comment by mrStenvik** [comment]
+1

**Comment by tzeller** [comment]
i have created a burger icon which can be used.
[fa-burger.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364630/fa-burger.pdf)

**Comment by gsisko** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cheeseburger?style=solid
https://fontawesome.com/icons/hamburger?style=solid
