### ISSUE TITLE
How to get Tiktok icon in favicon

### ISSUE THREAD

**Issue by vishdew19** [FortAwesome/Font-Awesome#19623]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) or [bug report template for any other issue](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=101_other_bug_report.yml&title=Bug%3A+)

Closing here, but feel free to comment if I've missed something
