### ISSUE TITLE
Icon request: website-call-to-action

### ISSUE THREAD

**Issue by TrevorWatBT** [FortAwesome/Font-Awesome#19637]
<img width="300" alt="Screen Shot 2023-03-30 at 10 50 58 am" src="https://user-images.githubusercontent.com/48667706/228694518-e27b7f21-b0c2-438e-8615-b621fff3134f.png">

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/globe-pointer?f=classic&s=solid
