### ISSUE TITLE
Icon request: moodle version icons

### ISSUE THREAD

**Issue by mtsyr3** [FortAwesome/Font-Awesome#19638]
Hi - I'm a technologist at an institute that is part of the University of London. We like to use fontawesome icons in our technology guides, we use Moodle, an open-source VLE, it is being upgraded to 4.0. We still need some old 3.9 guidance available, so we would like to have one icon that is 4.0 and another that is 3.9.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)?
