### ISSUE TITLE
Bug: Broken links in docs

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#19634]
### Bug description

All anchor links at https://fontawesome.com/v5/docs/web/use-with/react in anchors are broken

Example: Swap Duotone Icon Layer Opacity links to `https://fontawesome.com/web/style/duotone-icons`

### Font Awesome version

n/a

### Application and Operating System

n/a

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by AshwanthramKL** [comment]
Hey @tagliala, can I work on this

**Comment by tagliala** [comment]
Hi, thanks for your willing to help but unfortunately the documentation website is not open source

**Comment by AshwanthramKL** [comment]
That's alright. Thanks

**Comment by Samsonroyal** [comment]
> ### Bug description
> All anchor links at https://fontawesome.com/v5/docs/web/use-with/react in anchors are broken
> 
> Example: Swap Duotone Icon Layer Opacity links to `https://fontawesome.com/web/style/duotone-icons`
> 
> ### Font Awesome version
> n/a
> 
> ### Application and Operating System
> n/a
> 
> ### Web bug report checklist
> * [x]  I have included a test case because my odds go _way_ up that the team can fix this when I do
> * [x]  I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

I just discovered another broken link; configure access for pro button on the [react page](https://fontawesome.com/docs/web/use-with/react/)
when the button is clicked it redirects here
![image](https://github.com/FortAwesome/Font-Awesome/assets/26835888/c007e39b-8a95-4950-8f89-53362bdbdd90)

**Comment by ej2** [comment]
This no longer an issue since the docs were moved to a new platform.
