### ISSUE TITLE
Icon request: fa-subscript-2, fa-superscript-2, fa-superscript-3

### ISSUE THREAD

**Issue by delijah** [FortAwesome/Font-Awesome#19648]
### Use case

In our rich text editor we have a toolbar button, which lets the user format the selected text as "subscript" or "superscript" (for these actions we use the already available icons "fa-subscript" and "fa-superscript").

But we have another set of toolbar buttons, which lets the user
- insert a subscripted character "<sub>2</sub>"
- insert a superscripted character "<sup>2</sup>"
- insert a superscripted character "<sup>3</sup>"

For these actions we would need according icons.

### Example image

<img width="330" alt="Screenshot 2023-04-03 at 16 49 10" src="https://user-images.githubusercontent.com/237739/229545903-d1469969-8b9f-4e0f-96c9-23a91159375a.png">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
> But we have another set of toolbar buttons, which lets the user

This could lead to `superscript-n` / `subscript-n` with n from 0 to 9, for a total of ~200 icons (5 styles * 2 families * 20 icons)

Any chance to consider icon stacking or a different solution?

**Comment by delijah** [comment]
I think 2 and 3 are the most common numbers when it comes to subscripting or superscripting.

The problem with stacking is, that we somehow have to overwrite the number of the original subscript/superscript icon. This is not really possible, if we want to use the icon on different background colors. Also we have to shrink the number way more than the letter "X" which makes its appearance much thinner, which looks strange.

Using the letter x icon, is not so nice since fontawesome styles icons use serifes, but the letter icons not.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
