### ISSUE TITLE
Icon request: New Categories

### ISSUE THREAD

**Issue by rastek1** [FortAwesome/Font-Awesome#19657]
### Use case

Hello there.  sory I will not request an Icon but Icon sets.. There is zero or one icon for the categories **Genetics,  Chemistry** ), **Banking, Office, Insurance, Movie & Entertainment, Cloud, Material Science, Earthquake, etc. etc.**. These are very common areas and its hard to understand why they are not being implemented as seperate sets..

for example;
Genetics -> we have only fa-dna but there a lot of things according to genetics actualy..

for Chemistry we have Science icons but not enough

and there is no icon for some common words such as portfolio, risk, segmentation

I can name a lot of them.

Hope we will see those categories soon.

### Example image

 When I loook at cetegorial view of fontawesome in w3schools in the link below, I do not see those categories
https://www.w3schools.com/icons/fontawesome5_icons_communication.asp

for now at least we have to make do with **Pharmcy**!

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

>  I will not request an Icon but Icon sets.

Sorry, but as you might have seen in our contributing guidelines and in the request checklist

>  This is a single icon or matched pair (Ex: lock / unlock)

Request for sets are hard to manage, but feel free to open individual requests

I'm going to close here
