### ISSUE TITLE
fa-border doesn't work with stacked icons

### ISSUE THREAD

**Issue by ppazos** [FortAwesome/Font-Awesome#19658]
I have a circle plus icon stack and wanted to add a border to the circle. When the class fa-border is added to the stack or to the circle icon, the whole stack breaks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Any chance to fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) with a reproducible test case?

**Comment by syum-akhlaque** [comment]
I have also faces this issue 

In my case, I try to do something like this  by adding a extra class and custom css.
```
.custom-circle g g path {
    stroke: red;
    stroke-width: 50;
}

`````

**Comment by tagliala** [comment]
Sorry, going to close here.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) with a reproducible test case, so we can provide help
