### ISSUE TITLE
Brand request: GoCardless (updated logo)

### ISSUE THREAD

**Issue by maxresnikoff** [FortAwesome/Font-Awesome#19653]
### Description

_(2014 post regarding this shows old logo, this is their new one)_

GoCardless is a big company, and would be very helpful to be able to use their logo when showing a payment method.

![63a288e099da9171691cd7ba_gocardless](https://user-images.githubusercontent.com/48560713/230035367-937d4d93-a2a4-4864-8efb-607ea0771f68.svg)

### Official website

https://gocardless.com/

### Brand guidelines

https://brand.gocardless.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

> (2014 post regarding this shows old logo, this is their new one)

This is not a problem, we will use the latest available logo

Please upvote #4512

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

**Comment by fhdalikhan** [comment]
+1
