### ISSUE TITLE
Bug: cart-shopping does not exist for regular style

### ISSUE THREAD

**Issue by jimmy-e** [FortAwesome/Font-Awesome#19656]
### Bug description

* You can see [here](https://fontawesome.com/icons/cart-shopping?f=classic&s=regular), that font awesome's website shows the `cart-shopping` icon in regular style. You can even download it.
* Despite this, you cannot use the `cart-shopping` icon. If you try to import the `faCartShopping` icon, like in the image below, you get the error `TS2305: Module '"@fortawesome/free-regular-svg-icons"' has no exported member 'faCartShopping'.`.
* Why is this happening? This is because `faCartShopping` does not exist as part of the `free-regular-svg-icons` package (but it does exist as part of the `free-solid-svg-icons` package). If you look at the source code for this package, [here](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome/free-regular-svg-icons), you will see that `faCartShopping.js` is nowhere to be found.

![image](https://user-images.githubusercontent.com/25621956/230646533-4a8b2450-2b8b-4669-8475-da3172436814.png)

### Font Awesome version

^6.4.0

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Chrome 111 on Mac OS Ventura 13.0

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This is expected, cart-shopping is available in regular style only for Pro users

> You can even download it. 

If you are logged in as a Pro user. Please try in an incognito window, you will get a modal asking to subscribe to FA Pro
