### ISSUE TITLE
Icon request: phish-hook

### ISSUE THREAD

**Issue by mheidebrecht** [FortAwesome/Font-Awesome#19666]
a fishing hook to represent phishing

**Comment by tagliala** [comment]
Does https://fontawesome.com/icons/fishing-rod?f=classic&s=solid fit this use case?

**Comment by aethior** [comment]
Duplicate of #19666?

**Comment by aethior** [comment]
Duplicate of #9771?

**Comment by mheidebrecht** [comment]
> Does https://fontawesome.com/icons/fishing-rod?f=classic&s=solid fit this use case?

Thanks, but I think it is not a concrete as the suggested ideas.

**Comment by sensibleworld** [comment]
Closing in favor of: https://github.com/FortAwesome/Font-Awesome/issues/9771
