### ISSUE TITLE
Question: transformation classes

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#19669]
Hi,

I am developing a website and I use many of your icons on the site. One which is very useful is fa-signal, which I use to visually indicate an increasing intensity. However, if would be useful if you had CSS classes such as fa-lr, fa-rl, fa-up, and fa-dn to transform the direction in horizontal and vertical axes. Is this possible?
One could then have fa-signal fa-lr meaning increasing positively, fa-signal fa-rj meaning decreasing and so on.

Dermot
dermot@dermotnolan.ie

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I think you are looking for [Power transforms](https://fontawesome.com/v6/docs/web/style/power-transform#rotating-and-flipping) or [Rotate classes](https://fontawesome.com/v6/docs/web/style/rotate#rotate-classes)

Demo (CSS): https://jsfiddle.net/tagliala/vuren0mg/9/

> One could then have fa-signal fa-lr meaning increasing positively, fa-signal fa-rj meaning decreasing and so on.

Please also take into consideration trend icons:
- https://fontawesome.com/icons/arrow-trend-up?f=classic&s=solid
- https://fontawesome.com/icons/arrow-trend-down?f=classic&s=solid

**Comment by ghost** [comment]
Hi Geremia,

 

Thanks for your prompt reply – I did not know about the rotate classes so this is very helpful.

 

All the best,

 

Dermot

 

Dermot Nolan, Master of Wine

Fáilte Ireland National Tour Guide  

 

Master of Wine #230 of 415

 <http://www.dermotnolan.ie/> www.dermotnolan.ie

 <https://www.mastersofwine.org/dermot-nolan-mw> The Institute of Masters of Wine

 <http://dermotswineblog.blogspot.com/> My blog

 <http://www.linkedin.com/in/dermot-nolan-mw-b555a12a> My LinkedIn
