### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by davidanton1d** [FortAwesome/Font-Awesome#19677]
### Bug description

When using the amazing and awesome new Icon Wizard, I'm afraid the glyph "door-open" does not render correct.

Specifically, this variation:
fa-regular-door-open-circle-plus 

To reproduce:
1. Visit https://fontawesome.com/icons/door-open?f=classic&s=regular with a pro account
2. Click "Icon wizard"
3. Select any of the "circle" modifiers.
4. The issue is visible in the preview as well as when using the kit in a web browser.

Thank you for a great product!

Best regards, David

### Reproducible test case

https://fontawesome.com/icons/door-open?f=classic&s=regular

### Screenshots

<img width="549" alt="image" src="https://user-images.githubusercontent.com/3294797/232753787-58861eeb-2342-416c-b189-8ed0a55f03f6.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/3294797/232753844-92944134-180c-44a7-82f6-cedaa24d46e8.png">

### Font Awesome version

v6.0.0

### Serving

Kit

### Implementation

CSS, SVG+JS

### Browser and Operating System

Chrome Version 112.0.5615.49 on MacOS Ventura 13.3, M1 processor (ARM architecture)

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
@davidanton1d Apologies for the delay in replying to this. These issues should now be fixed. Let me know if you're still experiencing oddities with the Wizard.

**Comment by davidanton1d** [comment]
Awesome, thanks guys.
