### ISSUE TITLE
Bug: arrow-down-wide-short is the same as arrow-down-short-wide for classic light

### ISSUE THREAD

**Issue by JimKnoxx** [FortAwesome/Font-Awesome#19673]
### Bug description

Hello
The icon 'arrow-down-wide-short' in the classic light version is wrong. All other versions have the wide line on top and the short line on the bottom, only this version is the same as the 'arrow-down-short-wide' version.

### Reproducible test case

https://fontawesome.com/v6/search?q=arrow-down-wide-short&o=r&f=classic%2Csharp

### Screenshots

![image](https://user-images.githubusercontent.com/5279128/232492779-d2fecca7-1e3c-4263-ba40-693876bceb9c.png)

### Font Awesome version

v6.4.0

### Serving

Font Awesome CDN

### Implementation

CSS, SVG+JS, SVG Sprites

### Browser and Operating System

Affects any browser and operating system.

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Thanks for the report! We'll get this fixed in the next release.

**Comment by Cow258** [comment]
I got same issue
![螢幕截圖 2023-07-13 10 50 40](https://github.com/FortAwesome/Font-Awesome/assets/14261588/aec7febc-9590-496a-b98b-5f5aa8ea14ea)

**Comment by sensibleworld** [comment]
Thanks for the report. I fix is in the works and will be out in our 6.4.1. release.

**Comment by sensibleworld** [comment]
This is fixed!

<img width="1143" alt="CleanShot 2023-08-03 at 07 48 23@2x" src="https://github.com/FortAwesome/Font-Awesome/assets/529604/45186aaf-895a-4768-814d-325530e63bda">
