### ISSUE TITLE
Icon Request: icon-smiley-wink, icon-smiley-laugh

### ISSUE THREAD

**Issue by pfefferminzz** [FortAwesome/Font-Awesome#1968]
Hi,

additionaly to the three smileys which already exist:
:) icon-smile
:| icon-meh
:( icon-frown

i suggest these two to be added:
;) icon-wink (icon-smile with one modified eye, winking)
:D icon-laugh (icon-smile with modified mouth, like U+1F604, eyes untouched)

Thanks for reading, keep up the great work!

**Comment by A5hleyRich** [comment]
+1

**Comment by whoacowboy** [comment]
+1

**Comment by DimasInchidi** [comment]
+1

**Comment by phlegx** [comment]
+1

**Comment by kdt** [comment]
+1

**Comment by DomenicoMammola** [comment]
+1

**Comment by fabswt** [comment]
+1

**Comment by NuhaKhaled** [comment]
+1

**Comment by lunaru** [comment]
+1

**Comment by NikoLicht** [comment]
+1

**Comment by pobegov** [comment]
+1

**Comment by CodyFitzpatrick** [comment]
+1 for the wink

**Comment by stefanogorla** [comment]
+1 for the wink ;-)

**Comment by umar-qureshi2** [comment]
+1 for laugh

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&v=5.1.0&c=emoji

**Comment by pfefferminzz** [comment]
And it only took from september 2013 to december 2018. ;D
