### ISSUE TITLE
Icon Request: fa - industry-settings

### ISSUE THREAD

**Issue by MelafiX** [FortAwesome/Font-Awesome#19685]
![Industry-settings](https://user-images.githubusercontent.com/131366796/233372896-a8d7613f-6b01-4a1b-aeb4-45a2f0f2d8ce.png)

Need a new icon for the edit factory app option. 

Thank you.

**Comment by sensibleworld** [comment]
With the new icon wizard, you can create your own!

<img width="1250" alt="CleanShot 2023-05-02 at 07 56 45@2x" src="https://user-images.githubusercontent.com/529604/235659629-f04b862f-bbfa-433b-ac0c-f32f1d44dd14.png">

https://fontawesome.com/docs/web/add-icons/icon-wizard
