### ISSUE TITLE
Bug: Dinosaur does not display 

### ISSUE THREAD

**Issue by ezoehunt** [FortAwesome/Font-Awesome#19686]
### Bug description

Just upgraded to Pro Kit to 6.4. Using CSS method. Tried to use fa-dinosaur. 

- When using the class name nothing appears on screen. In view source, the HTML is visible but there is no ::before attached to the &lt;i&gt;.
- Tried using unicode by overriding the ::before content of another icon. "\e5fe" shows the X in rectangle on screen. 

### Screenshots

Classname
![fa-bug-class](https://user-images.githubusercontent.com/234670/233601683-98e58cfe-a919-4d75-a861-da4c648f5580.PNG)

Unicode
![fa-bug-unicode](https://user-images.githubusercontent.com/234670/233601680-df83675c-4793-48b3-8034-65269e451487.PNG)

### Font Awesome version

v6.4.0

### Serving

Kit, Self-hosted

### Implementation

CSS

### Browser and Operating System

Chrome on Windows

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Sorry for missing this issue! If it's still a problem... can you write in to hello [at] font awesome [dot] com with some more details?
