### ISSUE TITLE
sharp font path is missing in all.min.css / all.css

### ISSUE THREAD

**Issue by andrenoel** [FortAwesome/Font-Awesome#19683]
hi Font-Awesome,
i downloaded the 6.4.0 pro web version to use the new sharp font but it doesn't loaded when i use all.min.css or all.css, the path is missing. I added manually the @font-face path to the webfont folder for the font-weight 300,400,900.

// path missing for sharp font...
@font-face {
  font-family: 'Font Awesome 6 Sharp';
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url("../webfonts/fa-sharp-solid-900.woff2") format("woff2"), url("../webfonts/fa-sharp-solid-900.ttf") format("truetype"); }

**Comment by ezoehunt** [comment]
Hi. I just figured this out. By default, Sharp is not included in the all.css/all.min.css. You need to include it manually. 

I'm self-hosting so here's the link to that info: https://fontawesome.com/docs/web/setup/host-yourself/webfonts#hosting-your-own-downloaded-kit

**Comment by ingeniumdesign** [comment]
New Updates?

**Comment by robmadole** [comment]
Hey, folks. This is intentional. The `all.css` file has gotten so large that we don't recommend using it. Instead, choose specific styles or even better use a Kit and pick the specific icons that you are using.
