### ISSUE TITLE
Bug: "fab fa-telegram-plane" displays as "fab fa-telegram" in fontawesome-free-web-5

### ISSUE THREAD

**Issue by N-ux5** [FortAwesome/Font-Awesome#19687]
### Bug description

If I use downloaded "web" fontawesome-5 free files from https://fontawesome.com/v5/download (tested with fontawesome-free-5.8.2-web and fontawesome-free-5.15.4-web):

/css : 
- brands.min.css

/webfonts : 
- all fa-brands files

And use in my html :
```
<i class="fab fa-telegram-plane"></i>
<i class="fab fa-telegram"></i>
```

They are both showing as https://fontawesome.com/v5/icons/telegram?f=brands&s=solid

But the first one should be https://fontawesome.com/v5/icons/telegram-plane?f=brands&s=solid

This is not reproduced in files loading from online fontawesome 5 JS script, examples from :
- https://jsfiddle.net/tagliala/ryncaLg7/5/
- https://www.w3schools.com/icons/tryit.asp?icon=fab_fa-telegram-plane&unicon=f3fe

CF closed 
https://github.com/FortAwesome/Font-Awesome/issues/13338

### Font Awesome version

v5

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Firefox 112 on Windows 10

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This is not reproduced in files loading from online fontawesome 5 JS script, examples from :

Sorry, we can't help in this case, please provide a reproducible test case.

Note that if you are self-hosting Font Awesome, you should double check that you have also updated the webfont files and that there are no cache issues

Ref: https://fontawesome.com/v5/docs/web/setup/host-font-awesome-yourself

Hope it helps, closing here

**Comment by OmkarKamble1** [comment]
I understood the problem. but don't know how to run the code.

**Comment by OmkarKamble1** [comment]
I checked the code. The path for telegram and telegram-plane is same. Updating the path will help to resolve this issue.
SVG path for telegram is "m -93.6 -157.1 Z M 269.352 19.56 c -3.732 39.215 -19.881 134.378 -28.1 178.3 c -3.476 18.584 -10.322 24.816 -16.948 25.425 c -14.4 1.326 -25.338 -9.517 -39.287 -18.661 c -21.827 -14.308 -34.158 -23.215 -55.346 -37.177 c -24.485 -16.135 -8.612 -25 5.342 -39.5 c 3.652 -3.793 67.107 -61.51 68.335 -66.746 c 0.153 -0.655 0.3 -3.1 -1.154 -4.384 s -3.59 -0.849 -5.135 -0.5 q -3.283 0.746 -104.608 69.142 q -14.845 10.194 -26.894 9.934 c -8.855 -0.191 -25.888 -5.006 -38.551 -9.123 c -15.531 -5.048 -27.875 -7.717 -26.8 -16.291 q 0.84 -6.7 18.45 -13.7 q 108.446 -47.248 144.628 -62.3 c 68.872 -28.647 83.183 -33.623 92.511 -33.789 c 2.052 -0.034 6.639 0.474 9.61 2.885 a 10.452 10.452 0 0 1 3.53 6.716 A 43.765 43.765 0 0 1 269.352 19.56 Z"
