### ISSUE TITLE
Icon Request: icon-orcid

### ISSUE THREAD

**Issue by freek200194** [FortAwesome/Font-Awesome#19692]
Can be used in a resume to refer to Orcid-page which is prevalent in academia.

Example: https://www.google.com/url?sa=i&url=https%3A%2F%2Fcommons.wikimedia.org%2Fwiki%2FFile%3AORCID_iD.svg&psig=AOvVaw3mTEv-Xr4ThCb2W-pXJlD0&ust=1682506600737000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCJDv2NPvxP4CFQAAAAAdAAAAABAE

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

orcid has been added to FontAwesome in version 5.11.0:
- https://fontawesome.com/icons/orcid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
