### ISSUE TITLE
Icon Request: fa-simchange

### ISSUE THREAD

**Issue by sartusd** [FortAwesome/Font-Awesome#19696]
Hello, I need a SIM card slot change button for our Mikrotik control system. Thank you very much in advance
![sim](https://user-images.githubusercontent.com/70641818/234509133-67cae465-08f5-419b-bf9f-30434b76b695.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/sim-cards?f=classic&s=solid
