### ISSUE TITLE
How to use pro icons with open source projects

### ISSUE THREAD

**Issue by patrickelectric** [FortAwesome/Font-Awesome#19693]
So, I have a open source project that runs offline, is it possible to use the pro icons with it ?
If so, how ?

**Comment by tagliala** [comment]
Hi, 

please take a look at https://fontawesome.com/support#can-i-use-in-open-source-projects

**Comment by tagliala** [comment]
Closing here, but if it is not clear feel free to comment

**Comment by 2mik** [comment]
Hi,
The above link contains:

> Can I use Pro in my theme or open source project?
For themes and open source projects, right now it's best to just use Font Awesome Free. We are working on a better solution...

What approach is planned to use in the mentioned better solution? We work on an open source web application, and some Pro icons would be useful for it.
