### ISSUE TITLE
Brand Icon request: TypeScript Logo

### ISSUE THREAD

**Issue by NathanHannon** [FortAwesome/Font-Awesome#19705]
The JavaScript logo exists, so why not have the TypeScript one too? It would be identical to the current JavaScript ones except replace "JS" with "TS".

https://www.typescriptlang.org/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #11890, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Comment by MohammadAliJa** [comment]
@tagliala Hello, how many years do you still need to add the icon?!

**Comment by InterMaus1154** [comment]
@tagliala it's 2025 August, still no typescript...maybe time to catch up huh?

**Comment by brianwalczak** [comment]
Yeah haha, looking forward to it as well 😉

**Comment by Irfan140** [comment]
Any TS icon ?

**Comment by InterMaus1154** [comment]
Needed 3 years but it is here

https://fontawesome.com/icons/brands/solid/typescript
