### ISSUE TITLE
Icon Request: Adobe Icons

### ISSUE THREAD

**Issue by LDigital84** [FortAwesome/Font-Awesome#1970]
I would like to request Adobe Icons for the various Adobe Programs that many of us use.

Here is a list that corresponds to the photo below:

Acrobat, After Effects, Audition, Bridge, Creative Cloud, Dreamweaver,
Edge Animate, Edge Code, Edge Inspect, Edge Reflow, Fireworks, Flash Pro,
Illustrator, InCopy, InDesign, Lightroom, Muse, Photoshop,
Prelude, Premier Pro, SpeedGrade, Adobe Logo, Adobe PDF, Business Catalyst

![adobe-icons](https://f.cloud.github.com/assets/1938824/1144246/651a8cb2-1d80-11e3-8acc-b5436658ed31.jpg)

I know Acrobat Reader has been requested (#1911). Also I do not consider this an all inclusive list just a list of programs I know are popular.

Note: In the photo you see the shortcut icon in the bottom left. This is a screenshot of my desktop icons and is not a part of the icon.

**Comment by ncoetzer** [comment]
+1

**Comment by cprobert** [comment]
+1

**Comment by EddieOne** [comment]
pdf and swf or flash would be great. +1

**Comment by royduin** [comment]
For the time being, you can use a additional font: https://github.com/websiddu/technology-icons

**Comment by djwesterfield** [comment]
Any update on this?

**Comment by Quin452** [comment]
+1

Hopefully soon???

**Comment by gabriel-sen** [comment]
+1

**Comment by sudheesh001** [comment]
Totally need this !! 👍

**Comment by dezindzer** [comment]
+100000000000000000000000000

**Comment by renebaudisch** [comment]
+1

**Comment by Wingo5315** [comment]
Please do this. I beg you! +1

**Comment by PamposDev** [comment]
Any update for this icon font?

**Comment by dennishochhaus** [comment]
+1 Would also like to see Adobe CC Icons in the brand icon set

**Comment by ptkdev** [comment]
+1

**Comment by Wingo5315** [comment]
I'd like to add a few:
- Adobe Lightroom CC (the new one)
- Adobe Lightroom Classic CC
- Adobe Typekit
- Adobe XD
- Adobe Dimension

**Comment by bymotive** [comment]
+1

**Comment by Berkmann18** [comment]
+1

**Comment by itsmelion** [comment]
+1

**Comment by jerald-lim** [comment]
+1

**Comment by morgzz** [comment]
Definitely in need of the Adobe Acrobat logo

**Comment by MattIPv4** [comment]
+1

**Comment by jenstroeger** [comment]
Is there any progress on this issue?

**Comment by isteiger** [comment]
+1
@jenstroeger i saw that.... [like this one for Dreamweaver](https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/adobedreamweaver.svg)

**Comment by hdrdla** [comment]
+1 Adobe Xd and Adobe Premiere Pro!

**Comment by sanek4life** [comment]
+1

**Comment by ratajs** [comment]
Here are some official vectors:
![https://www.adobe.com/content/dam/cc/us/en/products/ccoverview/ps_cc_app_RGB.svg](https://www.adobe.com/content/dam/cc/us/en/products/ccoverview/ps_cc_app_RGB.svg)
[https://www.adobe.com/content/dam/cc/us/en/products/ccoverview/ps_cc_app_RGB.svg](https://www.adobe.com/content/dam/cc/us/en/products/ccoverview/ps_cc_app_RGB.svg)
![https://www.adobe.com/content/dam/cc/icons/illustrator.svg](https://www.adobe.com/content/dam/cc/icons/illustrator.svg)
[https://www.adobe.com/content/dam/cc/icons/illustrator.svg](https://www.adobe.com/content/dam/cc/icons/illustrator.svg)
![https://www.adobe.com/content/dam/cc/icons/indesign.svg](https://www.adobe.com/content/dam/cc/icons/indesign.svg)
[https://www.adobe.com/content/dam/cc/icons/indesign.svg](https://www.adobe.com/content/dam/cc/icons/indesign.svg)
![https://acrobat.adobe.com/content/dam/dx-dc/images/product-icon-acrobat.svg](https://acrobat.adobe.com/content/dam/dx-dc/images/product-icon-acrobat.svg)
[https://acrobat.adobe.com/content/dam/dx-dc/images/product-icon-acrobat.svg](https://acrobat.adobe.com/content/dam/dx-dc/images/product-icon-acrobat.svg)
![https://www.adobe.com/content/dam/cc/icons/aftereffects.svg](https://www.adobe.com/content/dam/cc/icons/aftereffects.svg)
[https://www.adobe.com/content/dam/cc/icons/aftereffects.svg](https://www.adobe.com/content/dam/cc/icons/aftereffects.svg)

**Comment by ratajs** [comment]
These icons are already in their font:
https://www.adobe.com/etc.fps.clientlibs/beagle/fe/resources/font/aceui-fonts.ttf?v=0.6.0
https://www.adobe.com/etc.fps.clientlibs/beagle/fe/resources/font/aceui-fonts.woff?v=0.6.0
https://www.adobe.com/etc.fps.clientlibs/beagle/fe/resources/font/aceui-fonts.svg?v=0.6.0

**Comment by vdmeijer** [comment]
+1

**Comment by romapad** [comment]
+1

**Comment by jeztucker** [comment]
I also agree that this would be entirely useful.

**Comment by itsmelion** [comment]
At least we have a *Adobe* icon.
https://fontawesome.com/icons/adobe?style=brands

**Comment by renebaudisch** [comment]
> At least we have a _Adobe_ icon.
> https://fontawesome.com/icons/adobe?style=brands

And it's there since v5.6.0 - 2018-12-07 - thx @itsmelion

**Comment by MattIPv4** [comment]
The full product icon set would definitely still be rather useful though

**Comment by tagliala** [comment]
Sorry, closing this and labeling as wontfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150
