### ISSUE TITLE
Bug: Icons not showing correctly after opening devtools

### ISSUE THREAD

**Issue by djschilling** [FortAwesome/Font-Awesome#19709]
### Bug description

In general using the Font-Awesome icons works. But if i reload my side, then open the devtools and then reload my side again the icons show random utf8 symbols. After another reload the icons work again:

<img width="564" alt="Bildschirmfoto 2023-05-02 um 17 29 03" src="https://user-images.githubusercontent.com/3503166/235713106-68e6d616-7559-4de4-a19b-5f08346efea3.png">

### Reproducible test case

https://review.church.tools/

### Font Awesome version

v6.4.0

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Chrome 112.0.5615.137 on MacOs

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
> Self-hosted

I suspect this may be related to #17644

Please try by hosting on the CDN

This should be a the best fix (nginx level): https://github.com/FortAwesome/Font-Awesome/issues/17644#issuecomment-1362785107

I can confirm from:

1. ![image](https://user-images.githubusercontent.com/556268/235774233-82fd3d6c-a36a-473a-bda7-d0978980b1a3.png)
2. Charset is missing from CSS (but this will not fix 100% of the cases)
3. Charset is missing from response headers of  `index-19625735.css`
