### ISSUE TITLE
Bug: DoNotEnter not included in 5.x

### ISSUE THREAD

**Issue by k-funk** [FortAwesome/Font-Awesome#19718]
### Bug description

When looking at v5.14.4 in github https://github.com/FortAwesome/Font-Awesome/tree/5.15.4/js-packages/%40fortawesome/free-solid-svg-icons I do not see `faDoNotEnter.js`. However, it is documented in https://fontawesome.com/v5/search?q=do%20not%20enter&o=r&s=regular%2Csolid for both Regular and Solid sets.

### Screenshots

<img width="1604" alt="Screenshot 2023-05-09 at 17 30 16" src="https://github.com/FortAwesome/Font-Awesome/assets/1933021/5142a1b3-4f6e-4396-9092-14b86efe42c7">
<img width="320" alt="Screenshot 2023-05-09 at 17 30 10" src="https://github.com/FortAwesome/Font-Awesome/assets/1933021/55c2e880-9b5c-4566-ac03-e0cb43c1b9c6">

### Font Awesome version

v5.14.4

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

N/A

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Those icons are available in the Pro Set. Are you using Font Awesome Pro?

Ref: https://fontawesome.com/v5/search?q=do%20not%20enter&o=r&m=free&s=regular%2Csolid

**Comment by k-funk** [comment]
I was under the impression that the entire Solid set was free. Is that not the case?

I am not using Font Awesome Pro

**Comment by tagliala** [comment]
> Is that not the case?

No, unfortunately it is not the case. Please check "Free" filter to see what it is included

**Comment by k-funk** [comment]
My mistake. Thanks for the quick response.
