### ISSUE TITLE
Bug: Icon not showing in browser/ but is on mobile.

### ISSUE THREAD

**Issue by wegoDi** [FortAwesome/Font-Awesome#19717]
### Bug description

I'm reaching out because I'm currently experiencing an issue with Font Awesome icons on my website. Specifically, I'm having trouble getting an icon to display correctly on desktop browsers.

The icon in question is only showing up as a square with an X in the middle on desktop, but on mobile it displays correctly. I've added Font Awesome through a single code script in the <head> section, and I've also installed the plugin.
Also cleared cache of my desktop browser and tried the edge browser aswell.

I would greatly appreciate any help or advice you can provide on how to fix this issue. I've added screenshots of the issue.

![WhatsApp Image 2023-05-09 at 16 57 20](https://github.com/FortAwesome/Font-Awesome/assets/133030710/b5749afb-9b40-426c-81c6-f498c7986ff9)
![WhatsApp Image 2023-05-09 at 16 58 07](https://github.com/FortAwesome/Font-Awesome/assets/133030710/3fb5011f-7197-4448-9a23-357ae9d7876a)

### Font Awesome version

v5/v6

### Application and Operating System

IOS/Safari/Edge
Windows/iOS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please provide a reproducible test case, otherwise it is not possible to debug this issue

Closing here, but feel free to comment. I will reopen if this is an actual issue with Font Awesome
