### ISSUE TITLE
Icon request: icon-untappd [will be available in FA5]

### ISSUE THREAD

**Issue by infomofo** [FortAwesome/Font-Awesome#1971]
Untappd is a beer database, application, API, and oauth provider used by other beer related applications.  

The icon could be used by sites attributing use of the untappd api, or as a login button when the untappd oauth protocol is powering the login information or beer database.

There are two social badges that untappd provides, both could be used in single color version to make a good icon, for example:

![untappdcheers](https://f.cloud.github.com/assets/539599/1144254/4e86214a-1d81-11e3-9a24-4e18c940eab8.png)

**Comment by wanderingbrewer** [comment]
+1

**Comment by spangard** [comment]
:+1:

**Comment by CalebAmesbury** [comment]
:+1:

**Comment by ramsey** [comment]
:+1:

**Comment by dhruska** [comment]
:+1:

**Comment by pezholio** [comment]
:+1:

**Comment by moncini** [comment]
c'mon it is easy to add it!

**Comment by axelseaa** [comment]
+1

**Comment by jedsplit** [comment]
So...it's been nearly two years since this was requested, and Untappd usage has only skyrocketed...any timeline on it's inclusion?

**Comment by tagliala** [comment]
@jedsplit sorry no timeline. you should consider a custom build if you need this icon:  https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Rvanlaak** [comment]
:+1:

**Comment by bbarto3** [comment]
+1

**Comment by qjac** [comment]
+1

**Comment by Quantastical** [comment]
I created a couple of vectors for `untappd` and `untappd-square` icons in Illustrator for a side job I'm working on. I didn't feel like figuring out how to incorporate them into Font-Awesome because I have other tasks to address, but maybe this helps push it along. I ended up just creating a custom icon font from [icomoon.io](https://icomoon.io) because I figure I may have to add a few more at some point.

[untappd-square.svg.txt](https://github.com/FortAwesome/Font-Awesome/files/101636/untappd-square.svg.txt)
[untappd.svg.txt](https://github.com/FortAwesome/Font-Awesome/files/101635/untappd.svg.txt)

**Comment by filipe0513** [comment]
+1

**Comment by Lynzaddy** [comment]
+1

**Comment by sndrsk** [comment]
:+1:

**Comment by Taubin** [comment]
Is there any chance this will actually be added? It's been requested for nearly 3 years now, with no update other than "no timeline". 

Should we just give up on this request?

**Comment by pezholio** [comment]
I have had a dig around, and it should be pretty easy to add the svgs that @Quantastical mentioned via http://fontello.com/, generate some font files and submit a pull request. That said, there are rather a lot of PRs in the backlog, so I'm not sure the turnaround time would be that quick. That said, if you only want the Untappd logo for you own personal use, then Fontello might be the best way forward.

I'm pretty busy at the mo, but may well have a crack at doing a PR in the next week or so.

**Comment by veswill3** [comment]
That would be great if you did get around to it @pezholio, but shouldn't someone at untappd handle this? I mean, you would think it would be good for their branding and all...
I will send an email to info@untappd.com to see if someone wants to take a look at this.

**Comment by gregavola** [comment]
Hey everyone, this is Greg from Untappd. I had no idea that this request was 2yr+ old - but if someone wants to let us know what you need in terms of design - we can make it happen. We have Vector/AI of the Untappd logo - but I'm not sure what your looking for. Let me know and we can make it happen. Cheers!

**Comment by Lynzaddy** [comment]
Thanks for getting this moving.  I've got a brewery client that needed this
so I started the thread and people said the request was made several
times.  Excited to put that in!



Thanks,


*Matt Olson, CSM*Owner @lynzaddy
<https://www.linkedin.com/profile/view?id=8357367&trk=hp-identity-headline>
Lynzaddy.com | 402-370-6411 | matt@lynzaddy.com

<https://twitter.com/lynzaddy>  <https://www.facebook.com/lynzaddy>
<https://www.linkedin.com/in/lynzaddy>

**Comment by electricbrick** [comment]
Thank you, Greg. It's much appreciated and a relief to finally see traction on this request!

**Comment by gregavola** [comment]
@electricbrick @Lynzaddy What do you guys need? Just the a Vector/AI file?

**Comment by veswill3** [comment]
Thanks for getting on the thread @gregavola. I suspect that most people on this issue dont actually know what it takes to create the new icons (including me). We just want it to use them.
It sounds like @pezholio might know the specifics though. Do you think you could help Greg out when you have the time?

**Comment by jakelisby** [comment]
Hey @gregavola if you could provide either the AI file or an EPS that would be awesome!

**Comment by gregavola** [comment]
@jakelisby See below - let me know if this works!

[Untappd_Icon_Square.ai.zip](https://github.com/FortAwesome/Font-Awesome/files/247621/Untappd_Icon_Square.ai.zip)

**Comment by riotbr** [comment]
Almost 3 years. Is that right?

**Comment by gregavola** [comment]
@riotbr I provided the AI file... :-)

**Comment by riotbr** [comment]
Sorry about my english =)

@gregavola I'm already using it. Thanks a lot! What I did was to create a font and include on the HTML using the same tag, so it's 100% compatible with my CSS.

**Comment by goodcompanybrewing** [comment]
Yes Please!

**Comment by hcw-rohan** [comment]
Is this far off? Could definately use it for a brewery customer :)

**Comment by LotteNoteboom** [comment]
👍

**Comment by Taubin** [comment]
Is there any chance this will be added to the upcoming FA 5?

**Comment by grungyape** [comment]
Wow, what's the hold up?

**Comment by pezholio** [comment]
I guess it's not a priority for the core team really. I've never worked out how to contribute as I don't have a copy of Adobe Illustrator, and I find Inkscape borderline unusable.

**Comment by hegelstad** [comment]
Please add this A.S.A.P.

**Comment by golles** [comment]
👍

**Comment by brewtalizer** [comment]
👍🏼

**Comment by Tess91** [comment]
👍🏼

**Comment by Tess91** [comment]
+1

**Comment by kjellum** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by brewtalizer** [comment]
Grazie Geremia!
