### ISSUE TITLE
Brand request: fa-dart-lang

### ISSUE THREAD

**Issue by cheogm28** [FortAwesome/Font-Awesome#19714]
### Description

googles Dart icon can be used in Dart projects and documentations

### Official website

https://dart.dev/

### Brand guidelines

https://dart.dev/brand

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi again, #8003

Are you using a specific page for searches? If yes, can you send me the link?

**Comment by cheogm28** [comment]
@tagliala I search for Fa-dart and did not find it. I am using the github search. :7 sorry 🙇🏽

**Comment by tagliala** [comment]
I have results for fa-dart here too: 

https://github.com/search?q=repo%3AFortAwesome%2FFont-Awesome++Fa-dart+&type=issues

> sorry

No problem. Just checking if we have an outdated link
