### ISSUE TITLE
Icon request: C# 

### ISSUE THREAD

**Issue by migueloliveiradev** [FortAwesome/Font-Awesome#19727]
I saw that there are many icons related to programming, however, there are no icons related to the C# programming language

- C# 
- .NET 
- ASP.NET
- Entity Framework

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+), having care of [searching for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones.

Closing here
