### ISSUE TITLE
Icon Request: icon-font-size

### ISSUE THREAD

**Issue by ixar** [FortAwesome/Font-Awesome#1974]
Icon font size, for example Photoshop:
![font-size](https://f.cloud.github.com/assets/4320593/1145017/05bb27b8-1de9-11e3-9503-2ec890b409b2.PNG)

**Comment by u12206050** [comment]
Something like this please:
![image](https://cloud.githubusercontent.com/assets/6641242/7316447/6594f630-ea77-11e4-88f7-1ce2e5fb9756.png)

**Comment by tagliala** [comment]
dup of #1469
