### ISSUE TITLE
Squares instead icons on iPad

### ISSUE THREAD

**Issue by Fireroman** [FortAwesome/Font-Awesome#19748]
I can't find an answer to why icons don’t show on iPad on my website but on other browsers and gadgets, fine. Can anybody help me?M

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

There could be many reason, but please keep in mind that this is not a support forum but an issue and request tracker

If you think there is an issue with Font Awesome, please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) and provide a reproducible test case

Closing here, but feel free to comment if I've missed something
