### ISSUE TITLE
Kit bundle forwarding to cloudflare waiting room, causing a CORB block

### ISSUE THREAD

**Issue by RDN-Tony** [FortAwesome/Font-Awesome#19743]
Hi,

Fontawesome icons have been cutting in and out this morning. Currently, trying to open to our kit is taking us to a Cloudflare waiting room page (attached), which is causing a CORB block on the website.

Console output:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://kit.fontawesome.com/6e5feed5a0.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

![Untitled](https://github.com/FortAwesome/Font-Awesome/assets/102176901/11820b4e-66e3-49ba-a0e3-6861c83b8231)

**Comment by gu3st** [comment]
This is also affecting us

**Comment by tagliala** [comment]
Thanks for the report, and sorry for the inconvenience, this is a known issue

Please take a look at https://status.fortawesome.com/ for updates

**Comment by tagliala** [comment]
Should have been fixed, please let us know if it isn't

**Comment by RDN-Tony** [comment]
This issue was fixed on our end - thanks.
