### ISSUE TITLE
Icon Request: icon-airport

### ISSUE THREAD

**Issue by deepu105** [FortAwesome/Font-Awesome#1976]
Airline industry icons like checkin, airport, runway

Examples:

Checkin:
![check-in](https://f.cloud.github.com/assets/1107223/1148497/8a14ed7e-1ec4-11e3-9448-f87234a457d3.jpg)

Runway: 
![runway_icon-data](https://f.cloud.github.com/assets/1107223/1148510/052acf42-1ec5-11e3-85b4-bd3969ef7f5e.jpg)

Airport:
![aport](https://f.cloud.github.com/assets/1107223/1148511/0e93b4b8-1ec5-11e3-9530-dd3a1c7f2d68.jpg)

**Comment by yvaucher** [comment]
:+1:

**Comment by slayer925** [comment]
an airport icon would be nice too

![](https://cdn1.iconfinder.com/data/icons/airport-set-1/512/8-512.png)

**Comment by deepu105** [comment]
so no body is interested in airport related icons is it?

**Comment by tagliala** [comment]
@deepu105 apparently it is... meanwhile, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Lesik** [comment]
I'd like to have this in FontAwesome aswell.

**Comment by tagliala** [comment]
departure and arrival are here #326 and I'm going to split them out

This request should be improved according to new contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by nick-iCars** [comment]
Need an airport icon

👍🏻

**Comment by tagliala** [comment]
Check-in is available as [luggage-cart](https://fontawesome.com/icons/luggage-cart?style=solid)

Let's use #16043 for runway

Keeping this open as "airport", but airport can be represented with plane

**Comment by mikejmorgan** [comment]
I strongly support an airport icon.  I have an immediate use for @slayer925's example or a control tower by itself.  Would prefer a duotone as well.

**Comment by GordonWerner** [comment]
Yes we need an airport w/control tower

**Comment by RyanBJ** [comment]
+1 on @slayer925's icon.

**Comment by sensibleworld** [comment]
We now have a bunch of airport-related icons:

- https://fontawesome.com/v6.0/icons/tower-control?s=solid
- https://fontawesome.com/v6.0/icons/user-pilot?s=solid
- https://fontawesome.com/v6.0/icons/plane-arrival?s=solid
- https://fontawesome.com/v6.0/icons/plane-departure?s=solid

Closing this issue, but let me know if there's something specific we're still missing.
