### ISSUE TITLE
Icon request: Atomic Whirl

### ISSUE THREAD

**Issue by jrahma** [FortAwesome/Font-Awesome#19769]
### Use case

Please add the logo of Atomic Whirl to represent (No religion) to the free edition as well as all editions.

[https://en.wikipedia.org/wiki/Atomic_whirl](https://en.wikipedia.org/wiki/Atomic_whirl)

### Example image

Please refer to Wikipedia:

[https://en.wikipedia.org/wiki/Atomic_whirl](https://en.wikipedia.org/wiki/Atomic_whirl)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/atom?f=classic&s=solid fit this use case?

**Comment by jrahma** [comment]
Yes Thanks
