### ISSUE TITLE
Icon request: icon-Truth Social

### ISSUE THREAD

**Issue by Gondath** [FortAwesome/Font-Awesome#19774]
I searched and did not find a Truth Social Icon or request. It would be great to have that icon so I can add it to my share buttons on my website.

![truthsocial](https://github.com/FortAwesome/Font-Awesome/assets/137379401/42d923b4-adef-48d0-a692-5a7a55856625)

Thank you for your time.

**Comment by TylerMWise** [comment]
🙃 https://github.com/FortAwesome/Font-Awesome/issues/19367

**Comment by tagliala** [comment]
Thanks

**Comment by NicholasEli** [comment]
Bump

**Comment by emkowale** [comment]
This should not be closed because it is not solved. With Inauguration Day right around the corner we need this. Please put politics aside and celebrate America. Here is the svg to get this going. 

<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
	<path d="M 382.695312 306.738281 L 312.859375 306.738281 L 312.859375 363.828125 L 382.695312 363.828125 Z M 382.695312 306.738281 "/>
	<path d="M 355.382812 208.074219 L 355.382812 150.414062 L 213.082031 150.414062 L 213.082031 363.273438 L 285.714844 363.273438 L 285.714844 208.074219 Z M 355.382812 208.074219 "/>
	<path d="M 116.007812 150.414062 L 185.734375 150.414062 L 185.734375 208.058594 L 116.007812 208.058594 Z M 116.007812 150.414062 "/>
</svg>

**Comment by tagliala** [comment]
> This should not be closed because it is not solved.

Hello, this is a duplicate of #19367, please add a +1 to that request
