### ISSUE TITLE
Feature request: Yellow-Page icon is expected ...

### ISSUE THREAD

**Issue by jiapei100** [FortAwesome/Font-Awesome#19772]
### Is your feature request related to a problem?

Won't be able to find anything related to **yellow page** from [https://fontawesome.com/search?q=yellow&o=r](https://fontawesome.com/search?q=yellow&o=r) .

Looking forward to **yellow page** 

### Feature description

Just a new icon 

### Alternatives

N/A

### Additional context

No need

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a duplicate of #4648?

**Comment by jiapei100** [comment]
Thank you @tagliala 

Yes, it is a duplicate of [https://github.com/FortAwesome/Font-Awesome/issues/4648](https://github.com/FortAwesome/Font-Awesome/issues/4648) .
