### ISSUE TITLE
No Tea font icon showing on https://fontawesome.com/v4/icons/ - font icon library 

### ISSUE THREAD

**Issue by deecurious** [FortAwesome/Font-Awesome#19776]
Hi All,
I'd like to report a digital crime against tea and its lack of representation on https://fontawesome.com/v4/icons/ - font icon library. 
Could you please back port and add a font for the tea icon on this version (I know its old but I have a system referencing V4/icons).
I currently see a representation for coffee, but I'm more of a tea drinker!
<i class="fa fa-coffee" aria-hidden="true"></i>
Happy to stand corrected if I've missed something.
Do you have a public href link for font awesome  v5.15.4 CSS style sheet? 
P.S I am new to this so please indulge me on my ignorance and educated me if you do know better! :) 
Thanks,
Dee

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> Could you please back port and add a font for the tea icon on this version (I know its old but I have a system referencing V4/icons).

This is not possible, sorry, v4 is in end of life. You should customize your own  version if you need

> Do you have a public href link for font awesome v5.15.4 CSS style sheet?

We do not provide first party free CDN support anymore, but you can refer to third party services like https://cdnjs.com/libraries/font-awesome

Hope it helps

**Comment by deecurious** [comment]
Fair enough. Thanks for reply @tagliala
