### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by vikashjalandra** [FortAwesome/Font-Awesome#19787]
Please add the slide up and slide down icon as the photo shows.[](url)
![Screenshot 2023-06-30 210448](https://github.com/FortAwesome/Font-Awesome/assets/75132736/e2d326ae-f59d-46be-b62f-4012f121cba0)

```[tasklist]
### Tasks
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for https://fontawesome.com/icons/chevron-down ?

**Comment by vikashjalandra** [comment]
Thank you and sorry actually I didn't know its name.
