### ISSUE TITLE
NPM FORTAWESOME PROBLEM

### ISSUE THREAD

**Issue by feroztia** [FortAwesome/Font-Awesome#19789]
Hey guys!
I have a problem with installing fortawesome package, which I need to finish my project.
Here's the command that I put in terminal: npm i --save @fortawesome/fontawesome-free
And here's my output:
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an 
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.    
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
npm ERR! A complete log of this run can be found in: C:\Users\vzakr\Ap

Does anyone know what is the problem here by any chance? I tried to remove package-lock, but it didn't help.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please run `npm config list` and make sure that there are no settings related to `@fortawesome:registry`. They may come from other `.npmrc` in the tree

**Comment by feroztia** [comment]
Here's what I've got:
PS C:\Users\vzakr\Desktop\coursera-portfolio> npm config list
; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc

prefix = "C:\\Users\\vzakr\\AppData\\Roaming\\npm" 

; "user" config from C:\Users\vzakr\.npmrc

@fortawesome:registry = "https://npm.fontawesome.com/"
//npm.fontawesome.com/:_authToken = (protected)
//registry.npmjs.org/:_authToken = (protected)

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v20.3.0
; npm local prefix = C:\Users\vzakr\Desktop\coursera-portfolio
; npm version = 9.6.7
; cwd = C:\Users\vzakr\Desktop\coursera-portfolio
; HOME = C:\Users\vzakr
; Run `npm config ls -l` to show all defaults.

**Comment by tagliala** [comment]
Please remove settings related to font awesome from `C:\Users\vzakr.npmrc`

**Comment by feroztia** [comment]
Thank you so much for your help! Have a great weekends.
