### ISSUE TITLE
Icon Request: fa-arrows-in

### ISSUE THREAD

**Issue by Gabriel-Sur** [FortAwesome/Font-Awesome#19788]
Heyy, wanned to see if you guys could create the icon "Arrows-in" or "Minimize-icon" just like the minimize icon on the other version of Font Awesome. 

Thx!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Are you looking for https://fontawesome.com/icons/arrows-minimize?f=classic&s=solid ?
