### ISSUE TITLE
Icon Request: fa-trafficsignal

### ISSUE THREAD

**Issue by kandamene** [FortAwesome/Font-Awesome#19783]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Is this a request for https://fontawesome.com/icons/traffic-light?f=classic&s=solid ?

If it isn't, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) 

Closing here, but feel free to comment if I've missed something
