### ISSUE TITLE
Brand request: Threads

### ISSUE THREAD

**Issue by jandreaucodes** [FortAwesome/Font-Awesome#19800]
### Description

Meta's new Threads app is now available. Would love to see an icon to support the new social media service.

### Official website

https://www.threads.net

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by TylerMWise** [comment]
The platform has blown up!

![image](https://github.com/FortAwesome/Font-Awesome/assets/74430503/555a483c-f326-4f13-a2ed-4cb3fa775852)

**Comment by SethuSenthil** [comment]
Here is the SVG file for anyone who needs it! 
![thread](https://github.com/FortAwesome/Font-Awesome/assets/20134046/726be2be-7b74-4585-984f-5348b1789e99)

**Comment by cbracco** [comment]
Would love to see this one move quicker since the platform blew up!

**Comment by TylerMWise** [comment]
Same, it will be used on so many platforms

**Comment by abbetuck** [comment]
Please and thank you.

**Comment by tjldesigns** [comment]
Yes, it would be great, as we have a lot of sites needing it too

**Comment by foxtucker** [comment]
Please and thanks you

**Comment by gorbyoz** [comment]
Looking forward to having it.

**Comment by sensibleworld** [comment]
This should be released by next week. Sorry for the delay!

**Comment by abbetuck** [comment]
Cool. Thank you.

**Comment by TylerMWise** [comment]
Is there an estimated date? :)

**Comment by shreddshark** [comment]
Would love to have this one added as well, it's been a big one for some of our clients.

**Comment by sensibleworld** [comment]
It's been added to our build system and should be fully released before the week is out. Early next week at the absolute latest.

**Comment by buckmanhands** [comment]
Don't believe the hype. Threads is a bust. But we still need the icon, thanks for making this happen so my clients don't think I am an old person (I am). :)

**Comment by sensibleworld** [comment]
This has been added: https://fontawesome.com/icons/threads?f=brands&s=solid

**Comment by abbetuck** [comment]
Bravo. Thank you.

**Comment by cbracco** [comment]
Amazing, thank you!!

**Comment by TylerMWise** [comment]
Thank you!

**Comment by uwemdev** [comment]
Lovely, Awesome!
