### ISSUE TITLE
Icon Request: backspace  (aka erase to the left)

### ISSUE THREAD

**Issue by rsperberg** [FortAwesome/Font-Awesome#1980]
Please add a backspace icon, also known as "erase to the left," to the text editor or web application icons.

![backspace](https://f.cloud.github.com/assets/56674/1150760/9d1ea7c2-1eef-11e3-8282-e8002313bc56.png)

This is Unicode character U+232B

The reason I think backspace would be a useful icon is that the iPhone contains only one font with this character, which is very poorly executed.  Implementing a calculator app, say, or any input palette requires some way to indicate that the most recent entry should be erased.

(I access Font-Awesome icons using the RubyMotion gem, motion-awesome.)

Thanks,

Roger Sperberg
rsperberg at gmail

**Comment by JustinDrake** [comment]
+1

**Comment by e-tobi** [comment]
:thumbsup:

**Comment by JustinDrake** [comment]
I'm putting a $20 bounty for this icon. (Open for 6 weeks, payable in Bitcoin.) cc @davegandy

**Comment by edwardmp** [comment]
+1

**Comment by rpinna** [comment]
+1

**Comment by zygous** [comment]
In the meantime one could use Noto Sans Symbols or Fira Sans (the latter is a white cross on a black field). Arial Unicode MS has a nice glyph too, but I imagine its licence is too restrictive for web use.

```css
.fa-erase-left:before{
    font-family: "Noto Sans Symbols";
    content:"⌫";
}
```

**Comment by Klemen1337** [comment]
+1

**Comment by timaschew** [comment]
+1

**Comment by drmonty** [comment]
:+1:

@zygous thanks, this works :v: .

**Comment by frakesy** [comment]
+1

**Comment by jonathanwoahn** [comment]
+1

**Comment by CTimmerman** [comment]
+1. Non-Apple keyboards use long-arrow-left though. eraser or a rotated shield might also work.

**Comment by mike-compeat** [comment]
+1

**Comment by KeKs0r** [comment]
+1

**Comment by caeldom** [comment]
![](https://camo.githubusercontent.com/34337f613cc9fb9a4c057d55029c2c1832ee525a/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333238323937332f313938353235372f39643465663339652d383433622d313165332d383930632d3639396163353733326166392e706e67)

**Comment by invot** [comment]
+1

**Comment by habibzadeh** [comment]
+1

**Comment by gamecubate** [comment]
+2

**Comment by dvolvenl** [comment]
+1

**Comment by timaschew** [comment]
and how many +1 do you need to proceed with this issue?

**Comment by mbeijen** [comment]
+1

**Comment by kevinbarabash** [comment]
+1

**Comment by jhowarth** [comment]
:+1: How is this not here?

**Comment by Fatbat** [comment]
+1. Not holding my breath though.

**Comment by gamecubate** [comment]
one can almost hear the wind blowing across the empty plain for this one...

**Comment by Shabonkerz** [comment]
+1

**Comment by sbruton** [comment]
+1

**Comment by suyashgulati** [comment]
+1

**Comment by peletiah** [comment]
+1

**Comment by arLevi** [comment]
+1

**Comment by MartinKocour** [comment]
+1

**Comment by vladcrasnaru** [comment]
+1

**Comment by Kowts** [comment]
+1

**Comment by rubensedanoc** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by minglethepringle** [comment]
+1 👍

**Comment by vlad309523** [comment]
+

**Comment by codehead** [comment]
+1

**Comment by Szymaniuk** [comment]
+1

**Comment by sdevn** [comment]
+1

**Comment by kisvegabor** [comment]
+1

**Comment by tonister** [comment]
+1

**Comment by trumpetx** [comment]
+1

**Comment by iakwvina** [comment]
👍

**Comment by ginkosen** [comment]
+1

**Comment by LukasLSC** [comment]
+1

**Comment by alexanderdejong** [comment]
+1

**Comment by pohzipohzi** [comment]
+1

**Comment by NikhilMTomy** [comment]
+1

**Comment by lekterable** [comment]
+1

**Comment by Fatbat** [comment]
How has this icon not been made yet? It's in literally every app interface that has an input function. Does Dave Gandy have something against this icon? It's a 5 and a half year old request that should have made it into an early version of FontAwesome. I just don't understand.

**Comment by lekterable** [comment]
@Fatbat yeah, I thought the same thing! Imagine making a backspace button without that icon, there's no real alternative for that!  C'mon FontAwesome guys, it's just one icon!

**Comment by sensibleworld** [comment]
@Fatbat @lekterable The bad news is that these icon requests have been gathering dust for some time now. The good news is that times are changing! With every new release of FA 5, we're adding new icons, and I'm keeping a close eye on open requests here. In fact, we recently released a more transparent way of keeping track of our progress here: https://fontawesome.com/community/leaderboard/new. It's not perfect, but gives a little insight into what's being worked on, and what's been released.

**Comment by AndreaPappi** [comment]
+1

**Comment by kisvegabor** [comment]
Than you! :)
