### ISSUE TITLE
Icon request: fa-sort-circle-xmark

### ISSUE THREAD

**Issue by SamThilmany** [FortAwesome/Font-Awesome#19814]
### Use case

In version 6.0.0, you added the `filter-circle-xmark` icon with its respective variants, which is of great use for filter resetting buttons. Although, to date, a similar icon for sorting resetting buttons is missing; I am thus requesting an `fa-sort-circle-xmark` icon.

As there are numerous variants of sort buttons, some of which already contain a fair amount of shapes, I'm curious whether it is possible to come up with an appealing solution for every variant. Still, it should be no issue for the basic sorting icons.

### Example image

![sort-circle-xmark-solid_16px](https://github.com/FortAwesome/Font-Awesome/assets/20460039/98b43115-8526-4b7d-a2a3-a4f8ea52aff5)

![sort-circle-xmark-solid_64px](https://github.com/FortAwesome/Font-Awesome/assets/20460039/654921c2-01b0-44f3-8f5b-97d1c39b211c)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
@SamThilmany This is possible using our Icon Wizard feature!

<img width="1345" alt="CleanShot 2023-07-17 at 12 31 24@2x" src="https://github.com/FortAwesome/Font-Awesome/assets/529604/1722feed-7e91-4081-b6d6-b205bc7e5235">

**Comment by SamThilmany** [comment]
The Icon Wizard is a great tool for pro users that adds further value to the upgrade. However, a Pro license is not worth it for smaller, especially private projects. Since the icon requested here would probably enjoy wide use, as it could be found in many applications similar to the already existing `filter-circle-xmark`, I think despite the possibility of the Icon Wizard, the implementation of a `sort-circle-xmark` icon would be a useful upgrade to the free version of Font Awesome.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
