### ISSUE TITLE
Icon request: scrollreveal-icon

### ISSUE THREAD

**Issue by Dojacom** [FortAwesome/Font-Awesome#19816]
Here's a possible description for how it could look:

The "scrollreveal" icon could represent the concept of revealing content as the user scrolls. It could feature an arrow pointing upward or downward, indicating the direction of the scroll. The arrow could be combined with a visual element that signifies unveiling or revealing, such as a curtain, window, or an unfolding shape.

Here are ways it can benefit a user:

1.Visual representation: Having a specific icon for "scrollreveal" allows users to visually communicate the concept of revealing content as they scroll. It provides a clear and recognizable symbol that represents this functionality, making it easier for users to understand and identify.

2. Consistency and familiarity: FontAwesome is widely used across various websites and applications. By adding a "scrollreveal" icon to the library, users can maintain consistency in their design and visual language. They can rely on the established FontAwesome style and aesthetics, ensuring a cohesive user experience.

3. Streamlined design process: By including a "scrollreveal" icon, users can save time and effort that would otherwise be spent designing or sourcing a custom icon. They can quickly access and integrate the icon into their projects, enhancing the visual appeal and functionality of their scrolling components.

4. Clarity and user guidance: The "scrollreveal" icon can serve as a form of guidance, indicating to users that there is hidden or additional content that will be revealed as they scroll. This can enhance the user experience by providing a clear indication of how to interact with the page and encouraging exploration

A user may choose to use the "scrollreveal" icon in various contexts where the concept of revealing content through scrolling is present. Here are a few examples:

1. Websites: Users may include the "scrollreveal" icon on their websites, particularly on landing pages or long-scrolling pages where there is hidden or additional content that becomes visible as users scroll down. The icon can be placed near sections or elements that will be revealed upon scrolling, serving as a visual cue for users.

2. Single-page applications: Applications that rely heavily on scrolling, such as single-page applications or interactive storytelling websites, can benefit from the "scrollreveal" icon. It can be used to indicate that there is more content below the current view, encouraging users to scroll and explore further.

3. User interfaces: In user interfaces, the "scrollreveal" icon can be utilized in scenarios where there are scrollable panels, carousels, or sections with hidden content. It helps users understand that additional information or options are available by scrolling within those elements.

4. Mobile apps: Mobile applications that have long lists or horizontally scrollable sections can make use of the "scrollreveal" icon. It can be placed at the top or bottom of the screen to indicate that users can scroll to access more content, navigation options, or additional features.

5. Tutorials or onboarding screens: When providing instructional content or onboarding experiences, the "scrollreveal" icon can be employed to guide users on how to proceed through the content. It can indicate that users should scroll to reveal the next step or piece of information.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
