### ISSUE TITLE
Brand request: X (New Twitter branding)

### ISSUE THREAD

**Issue by Maxou44** [FortAwesome/Font-Awesome#19827]
### Description

This morning Elon Musk launched Twitter's "X" rebranding with a new logo.

I think we should keep the old Twitter logo and add this one as **faTwitterX** or **faTwitterAlt** while people get used to the new logo and brand identity.

Once the transition is complete, replacing the old logo could be a solution.

![xlogo](https://github.com/FortAwesome/Font-Awesome/assets/8138585/e9e13421-89cf-445b-b2e2-e50e0864789f)

### Official website

https://x.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

1. Is the recent change to the Twitter logo permanent, or is it just a temporary update?
2. Could you please provide an official link to the new brand guidelines that include details about the updated logo?

**Comment by refreeman4** [comment]
I would lean the other way instead of a million websites needing to change code I think the new brand should be reflected in the existing fonts with new font names added with the old branding: ex. fab fa-twitter-old

**Comment by tagliala** [comment]
> I would lean the other way instead of a million websites needing to change code I think the new brand should be reflected in the existing fonts with new font names added with the old branding

This is usually our approach, but we should make sure that this change is permanent and have access to new official brand guidelines

**Comment by Maxou44** [comment]
Given the changes on Twitter over the last few months, I'd say Elon Musk remains unpredictable. I'm hoping the logo will be changed to something more friendly and more "pro", but it looks like that's the way to go for now.

The logo guidelines haven't been updated yet, and the migration will probably take several days to complete. Only the site has changed its icon for the moment, the application haven't been updated yet.

Elon Musk plans to move twitter.com to x.com, changing the logo and "removing references to birds".

**Comment by candalfigomoro** [comment]
If the idea is to rename "Twitter" to "X", we might as well leave the bird logo as the Twitter icon and just add a new icon for "X".

**Comment by hm-harshit** [comment]
We need this asap 😂

**Comment by jasongaylord** [comment]
I agree with @candalfigomoro. @tagliala I know the usual approach is to replace the old, but this isn't just a brand change. This is a permanent change to the company. See this article from today: https://www.cnbc.com/2023/07/25/musk-explains-why-hes-rebranding-twitter-to-x.html. This is just one of dozens you'll find.

**Comment by refreeman4** [comment]
Yes... it's looking like a brand new company so it would make sense to create brand new art.

**Comment by munierujp** [comment]
The brand guidelines are here, but do not appear to have been updated yet.

https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by Maxou44** [comment]
The logo has been updated, the website use a bolder version of the logo
![x_v2](https://github.com/FortAwesome/Font-Awesome/assets/8138585/3d935a39-9abc-4ba6-94d4-b8e163756c27)

**Comment by mattly** [comment]
What happens if/when the Twitter brand assets are sold off and someone attempts to rehydrate that into a different service? Does X still exist under `fa-twitter` and the new twitter become `fa-twitter-new`?

**Comment by refreeman4** [comment]
It is looking pretty clear this is a new company and twitter should be left alone with new fa-x artwork created

**Comment by tagliala** [comment]
> Does X still exist under fa-twitter and the new twitter become fa-twitter-new?

As mentioned earlier, it depends. At the moment I'm writingm having a separate icon looks the most appropriate choice

>  new fa-x artwork created

`fab fa-x-com` or `fab fa-x-app` probably, `x` is taken by the letter X and already available: https://fontawesome.com/icons/x?f=classic&s=solid

**Comment by candalfigomoro** [comment]
The Twitter app for Android has been updated with the new logo (the app name is still "Twitter" but with the X logo).

> The brand guidelines are here, but do not appear to have been updated yet.
> 
> https://about.twitter.com/en/who-we-are/brand-toolkit

This page doesn't exist anymore and it redirects to the home page now.

**Comment by candalfigomoro** [comment]
> `fab fa-x-com` or `fab fa-x-app` probably, `x` is taken by the letter X and already available: https://fontawesome.com/icons/x?f=classic&s=solid

If you create a new icon instead of replacing the Twitter one, I'd suggest `fa-x-corp` as in the footer:

![Screenshot 2023-07-28 alle 08 32 50](https://github.com/FortAwesome/Font-Awesome/assets/50733646/6d647287-eec4-44f0-94a0-47b9c9a7de91)

**Comment by NickStees** [comment]
My opinion `fa-twitter` should just be updated to the `X` logo **when it final, and that I guess is determined when branding guides are released.** I really don't think they are going to go as far to changing everything to X, `<meta name="twitter:card"`, for example. 

But also maybe the best advice right now is to watch longer, this article indicates **the current X design is a placeholder** https://www.theverge.com/2023/7/26/23809087/elon-musk-x-logo-twitter-trademark#:~:text=While%20Musk%20says%20the%20current%20X%20design%20is%20just%20a%20placeholder%2C%20that%20still%20hasn%E2%80%99t%20stopped%20him%20from%20plastering%20the%20logo%20all%20over%20Twitter%E2%80%99s%20desktop%20site%20and%20even%20on%20its%20headquarters.

**Comment by esviza** [comment]
Twitter icon is important for a lot of FontAwesome users. We use this library for public websites and that icon is common for share content. I already have a complaint asking to change the icon on a newspaper site. The X is the new public image. All mass media is noticing that. Even in the case they come back later and change it again, I think fontawesome must provide a quick response, adding a new one or changing the current icon. I vote for update the current icon. Best regards and thank you all at fontawesome for so awesome work!

**Comment by sparkktv** [comment]
Seeing the X already being used by other companies on branding also (Saw the X logo being used on AEW & WWE already on TV). Musk is likely going to be sued because it was reported last week he doesn't own the X copyright. Microsoft owns it for video games and Facebook owns it for Social Media.
But it needs to be changed for all versions of Font Awesome because many people use this on their website and would need the new X logo instead of the current bird logo. 

Also @NickStees it is a placeholder logo, the X name is the main part, but seeing how the X is already a sign he is placing above his building, I don't see Musk changing this X despite is being a placeholder and was suppose to be replaced with a new logo. Unless Musk is forced to in court which is looking likely as I pointed out above.

**Comment by Neustradamus** [comment]
Several possibilities:
- create a "fa-x-com"
- update the current "fa-twitter" logo
- rename the current "fa-twitter" to another name and create a new "fa-twitter"

Twitter is the old name of X.

**Comment by Barcov** [comment]
I agree with previous comments, X.com is an entirely different company. It looks like a pivot with existing users of the platform. In terms of icons, some people will keep using fa-twitter for a while and others will switch to the x logo immediately. Would be great to have both options and deprecate that beautiful bird icon gracefully. 

Do we have an ETA for the X icon to go live yet?

**Comment by bartfeenstra** [comment]
Speaking as someone who delivers stakeholder requests that involve a lot of social media scrambling: a separate brand would allow users to switch when their stakeholders ask for it, rather than switching whenever they pull in the latest FA release.

**Comment by ekinox** [comment]
Anyone could share a .svg of the new icon, ready to be added to a FontAwesome kit? I found some .svg on the web, but cannot figure how to add them, the files don't match the criterias:
_This icon will not be uploaded due to the following errors...
This SVG contains objects with transforms applied that cannot be converted into an icon._

**Comment by robliberty** [comment]
Twitter is X and millions of sites shouldn’t need manual updates. The bird should just go away, all -twitter icons should also function as -x icons and be the X logo. 

There’s no reason to keep the bird.

**Comment by joao-guerreiro-asp** [comment]
I agree with @robliberty. The Twitter bird is now gone and has now been replaced by 𝕏, and whether it's currently under another umbrella company or not, it doesn't really matter, 𝕏 is now the official logo for Twitter.

**Comment by berryanne-le** [comment]
> Anyone could share a .svg of the new icon, ready to be added to a FontAwesome kit? I found some .svg on the web, but cannot figure how to add them, the files don't match the criterias: _This icon will not be uploaded due to the following errors... This SVG contains objects with transforms applied that cannot be converted into an icon._

![x](https://github.com/FortAwesome/Font-Awesome/assets/111457719/c64df44e-d7b1-4554-b4ac-2f7a8b616e71)

**Comment by mdl2934** [comment]
@ekinox 
https://fontawesomeicons.com/fa/twitter-x-logo

https://static.wikia.nocookie.net/logopedia/images/7/7a/X_2023_2.svg/revision/latest?cb=20230725192625

maybe these?

**Comment by Maxou44** [comment]
@ekinox The SVG extracted from the website :
![faTwitterAlt](https://github.com/FortAwesome/Font-Awesome/assets/8138585/a8266731-0d6f-4374-9df1-b44bf6915b39)

And a JS version if you import them to use it with the font awesome component :
[faTwitterAlt.zip](https://github.com/FortAwesome/Font-Awesome/files/12233514/faTwitterAlt.zip)

**Comment by ekinox** [comment]
> @ekinox https://fontawesomeicons.com/fa/twitter-x-logo
> 
> https://static.wikia.nocookie.net/logopedia/images/7/7a/X_2023_2.svg/revision/latest?cb=20230725192625
> 
> maybe these?

The one from fontawesome icons works perfectly in a kit, thank you

**Comment by sensibleworld** [comment]
This is now available in 6.4.2: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

**Comment by robliberty** [comment]
Awesome! But it should be the default and the bird, for some reason, should be the opt-in option for those who can’t cope with change. I mean, you’re not still hosting the original Instagram icon anymore.

**Comment by manuel-calzolari** [comment]
> Awesome! But it should be the default and the bird, for some reason, should be the opt-in option for those who can’t cope with change. I mean, you’re not still hosting the original Instagram icon anymore.

Instagram is still called Instagram, while Twitter is migrating to the X name. The Android app is now called "X" and the Twitter name doesn't appear anymore

**Comment by Maxou44** [comment]
Thanks guys 👍

**Comment by bartfeenstra** [comment]
Thanks! Happy stakeholders :)

**Comment by refreeman4** [comment]
Thanks! Will it be added to Font Awesome 5 Brands?
https://fortawesome.com/sets/font-awesome-5-brands

**Comment by sensibleworld** [comment]
@refreeman4 We don't currently have plans to add it to version 5, alas.

**Comment by lancedouglas1** [comment]
Brand guide was updated: https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by candalfigomoro** [comment]
> Brand guide was updated: https://about.twitter.com/en/who-we-are/brand-toolkit

Weird fact: the logo on the brand toolkit page is the original X logo (the thin one) and not the bolder one that was released later

**Comment by sensibleworld** [comment]
Interesting. We'll keep an eye on it. The one we're using in FA was pulled directly from the website.

**Comment by tagliala** [comment]
Other "fun" facts:
- favicon (https://abs.twimg.com/favicons/twitter.3.ico) is also showing the thin version
- home page and the loading screen use the bolder version
- [iOS icon](https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ae/41/24/ae412431-a176-74f1-42ad-f0d934fcb0aa/ProductionAppIcon-1x_U007emarketing-0-7-0-0-0-85-220.png/434x0w.webp) from the App Store is using the lighter (or a slightly lighter) version
- [Android icon](https://play-lh.googleusercontent.com/A-Rnrh0J7iKmABskTonqFAANRLGTGUg_nuE4PEMYwJavL3nPt5uWsU2WO_DSgV_mOOM=w240-h480-rw) from the Play Store is using the bolder version

**Comment by Neustradamus** [comment]
It has been updated: https://business.twitter.com/ but not yet completely https://about.twitter.com ^^

**Comment by joedag32** [comment]
> Thanks! Will it be added to Font Awesome 5 Brands? https://fortawesome.com/sets/font-awesome-5-brands

Hoping it will be made available for version 5 as well.

**Comment by AdsDawson** [comment]
This definitely should be changed to the twitter icon to prevent people having to crawl hundreds of sites to change an icon class in multiple places on each site

**Comment by sparkktv** [comment]
> This definitely should be changed to the twitter icon to prevent people having to crawl hundreds of sites to change an icon class in multiple places on each site

Agreed, it's officially the logo now and being used by many broadcast TV networks and even some websites are now starting to use it. It should be made the default Twitter logo and the old logo should be called fa-old-twitter or fa-bird-twitter.

**Comment by munierujp** [comment]
This is the X logo, not the Twitter logo.

<img width="716" alt="スクリーンショット 2023-08-29 12 53 25" src="https://github.com/FortAwesome/Font-Awesome/assets/20086673/426947f3-21d6-4fe6-9bbc-8cd62b72c67d">

I think that diverting identifiers for convenience is not a good choice. X itself still uses `twitter` as its domain, though 😅

**Comment by robliberty** [comment]
With that logic, the bird logo should be removed as an option entirely as it doesn’t represent any standing company.

The X logo is both the new Twitter logo and the logo for X the brand.

**Comment by sparkktv** [comment]
They have now even updated their apps to use the name X or X Beta depending on version you are using. Also their website in a browser when it loads says X as the title instead of Twitter now... Plus x.com redirects to twitter.com

**Comment by AdsDawson** [comment]
I mean regardless it should update the original icon name to avoid mass
edits to sites i have over 300 sites that use that icon for twitter in its
social links. Its insane that i now have to go through each one and change
the icon class from twitter to x just for the argument of being so pedantic

**Comment by davidcast19** [comment]
@sensibleworld Any thoughts about making X the original icon?

**Comment by refreeman4** [comment]
Honestly I don't care which way as long as it gets added to Font Awesome 5 Brands

**Comment by rcanand** [comment]
My webpage does not display this icon `fa-x-twitter` - it displays `fa-twitter` and other icons as usual.

**Comment by baritarek** [comment]
> My webpage does not display this icon `fa-x-twitter` - it displays `fa-twitter` and other icons as usual.

Having the same issue as well

**Comment by tagliala** [comment]
Please make sure you have updated to 6.5.1

Please double check that there aren't third party libraries loading an older version of FontAwesome

If you think there is an issue with Font Awesome itself, please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+) or [bug report template for any other issue](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=101_other_bug_report.yml&title=Bug%3A+)

**Comment by baritarek** [comment]
> 6.5.1

Thank you! It worked
