### ISSUE TITLE
When will you support the new Social Media network "X" (previously Twitter). I don't see the X icon as of yet.

### ISSUE THREAD

**Issue by garymgordon** [FortAwesome/Font-Awesome#19838]
When will you support the new Social Media network "X" (previously Twitter). I don't see the X icon as of yet.

Can you let me know if and when you'll have this Icon in Font Awesome?

Thanks,
Gary Gordon

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at the pinned issue #19827
