### ISSUE TITLE
Instead of icon appears strange rectangle 

### ISSUE THREAD

**Issue by Kirmez** [FortAwesome/Font-Awesome#19832]
![Screenshot 2023-07-25 181253](https://github.com/FortAwesome/Font-Awesome/assets/107321567/896de3df-03de-4cae-8f29-79fc561fb0c1)
I used (link) at the head with link from cdn library
But the icon doesn't appear
How can change that ?
Regards

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+). Please provide a reproducible test case

Closing here, but feel free to comment if I've missed something
