### ISSUE TITLE
Icon request: 

### ISSUE THREAD

**Issue by vikash-singh-iphtech** [FortAwesome/Font-Awesome#19835]
![Screenshot 2023-07-28 at 3 13 01 PM](https://github.com/FortAwesome/Font-Awesome/assets/133772183/72013220-9f14-4168-99dd-d2e803dfa719)
when I'm using LastPass... chrome extension getting this error whenever clicking on email text field or password text field in Login page

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'icons')

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)
