### ISSUE TITLE
Bug: square- icons corner radius is inconsistent

### ISSUE THREAD

**Issue by candalfigomoro** [FortAwesome/Font-Awesome#19830]
### Bug description

square- icons corner radius is inconsistent

For example, the corner radius of the `square-envelope` icon is larger than the corner radius of the `square-twitter` and `square-facebook` icons (see the attached screenshot).

### Screenshots

![radius](https://github.com/FortAwesome/Font-Awesome/assets/50733646/5d3d1ac4-f268-4d3b-af67-a8c83082db2f)

### Font Awesome version

v6.4.0

### Serving

Other (as specified in the bug description)

### Implementation

CSS

### Browser and Operating System

Chrome 114 on macOS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for this report.

@sensibleworld I can see that some (most of) square brands have an inconsistent square

https://fontawesome.com/search?q=square&o=r&f=brands

In example, [square-snapchat](https://fontawesome.com/icons/square-snapchat?f=brands&s=solid) is using the same square as non-brand icons

**Comment by candalfigomoro** [comment]
@tagliala Also, in general, wouldn't it be better if the radius were consistent across all FontAwesome icons (brand and non-brand)? Perhaps the only exception could be brand icons that natively have a square logo with their own specific radius.

**Comment by tagliala** [comment]
> wouldn't it be better if the radius were consistent across all FontAwesome icons (brand and non-brand)? 

That's the idea

> Perhaps the only exception could be brand icons that natively have a square logo with their own specific radius.

Correct. And this is the approach we are following: if the brand requires a square, then we use brand's rules.

**Comment by sensibleworld** [comment]
This'll be fixed in the next release.

**Comment by sensibleworld** [comment]
These have been standardized: https://fontawesome.com/search?q=square&o=r&f=brands
