### ISSUE TITLE
Icon Request: icon-xtwitter

### ISSUE THREAD

**Issue by mzsenevi** [FortAwesome/Font-Awesome#19841]
Hi, thanks for the hard work. 

My kind request would be to add the **new Twitter icon** "𝕏". Also please add the current animations to it (not just the icon) :-)

Use cases: Updated social media icons is a must  I think (still keep the old icon too though).

<img width="43" alt="Screenshot 2023-08-01 at 16 23 46" src="https://github.com/FortAwesome/Font-Awesome/assets/44942825/3a5b1bb5-f455-4b20-94d8-bbe6b501f10d">

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at the pinned issue #19827
