### ISSUE TITLE
Icon request: Missing Filter Icon

### ISSUE THREAD

**Issue by ayushkumarbhadani** [FortAwesome/Font-Awesome#19851]
### Use case

Please add this icon in the library.

### Example image

<img width="260" alt="Screenshot 2023-08-04 at 11 47 41 AM" src="https://github.com/FortAwesome/Font-Awesome/assets/73775939/9109f5e7-a30e-46d6-887b-4fa0661d3926">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon exists as [fa-sliders](https://fontawesome.com/icons/sliders?f=classic&s=solid)

We may consider to add a "filter" keyword to the documentation, /cc @talbs 

Hope it helps, closing here

**Comment by ayushkumarbhadani** [comment]
Thanks, @tagliala, consider adding a "filter" tag to that as well.
