### ISSUE TITLE
Bug: Unable to use environment variable to install pro package, resulting in `E401`

### ISSUE THREAD

**Issue by xsjcTony** [FortAwesome/Font-Awesome#19859]
### Bug description

Following the setup guide, I'm unable to install pro packages by using `.npmrc` and `.env`.

### Using token in `.npmrc` straight away will work, but that's not my preferred way:
![image](https://github.com/FortAwesome/Font-Awesome/assets/45784210/26c0ca82-b78a-4212-b195-d141cdb2e8a2)

### However, put token into `.env` and use a reference in `.npmrc` will results in `E401`:
![image](https://github.com/FortAwesome/Font-Awesome/assets/45784210/06a97711-2e0a-43dd-aa82-7bdac764773f)
![image](https://github.com/FortAwesome/Font-Awesome/assets/45784210/1ac4f162-2464-4b12-a85b-a4d049235d90)

#### some common details in case you need:
![image](https://github.com/FortAwesome/Font-Awesome/assets/45784210/55f680d5-51c8-4255-8aa7-d1fe4660ad13)

### Font Awesome version

v6.4.2

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- Chrome 115 on Windows 11

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hi there! If this is an issue related to a Pro package, I'd send an email message directly to hello[at]fontawesome[dot]com. That way, our official support can help out!

**Comment by pmwangi** [comment]
Was this resolved? Currently experiencing same error

**Comment by yonepv** [comment]
I had a similar error, I found this solution that worked for me: [How to replace Environment Variables in a .npmrc File](https://dev.to/dennzimm/how-to-replace-environment-variables-in-a-npmrc-file-jpg). Have an .npmrc.config, your env file and then run the command `npx npmrc-replace-env`.
