### ISSUE TITLE
Bug: Free icon packages suddenly 401 error requiring npm auth causing failed pipelines

### ISSUE THREAD

**Issue by KevinVandy** [FortAwesome/Font-Awesome#19857]
### Bug description

I have used the free package versions of FA for a couple years in a project. I did some package upgrades today and was surprised to see that the font awesome packages are not able to be installed because even the free versions of font awesome are requiring auth. Is this intentional or a mistake? These packages have never required NPM auth before.

```json
"@fortawesome/fontawesome-svg-core": "^6.4.2",
"@fortawesome/free-solid-svg-icons": "^6.4.2",
"@fortawesome/react-fontawesome": "^0.2.0",
```

```bash
ERR_PNPM_FETCH_401  GET https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/6.4.2/fontawesome-svg-core-6.4.2.tgz: Unauthorized - 401
--
11:51:07.711 |  
11:51:07.711 | No authorization header was set for the request.
11:51:07.711 |  
11:51:07.711 | No authorization settings were found in the configs.
11:51:07.711 | Try to log in to the registry by running "pnpm login"
11:51:07.711 | or add the auth tokens manually to the ~/.npmrc file.
11:51:07.755 | Error: Command "pnpm install" exited with 1
```

### Screenshots

<img width="1243" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/28243511/598f8229-6717-410c-84cb-9c1728234965">

### Font Awesome version

v6.4.2

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Vercel Pipelines

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The private NPM repository (`npm.fontawesome.com`) requires an active Font Awesome Pro subscription

Can you confirm that you have a valid and active subscription?

Otherwise, you can:
- remove the custom .npmrc configuration for private repository
- remove font awesome occurrences in your package manager lockfiles
- add font awesome packages again

This will use dependencies from the public npm repository, without eating private quota and without requiring an active subscription

**Comment by KevinVandy** [comment]
@tagliala 

> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> The private NPM repository (`npm.fontawesome.com`) requires an active Font Awesome Pro subscription
> 
> Can you confirm that you have a valid and active subscription?
> 
> Otherwise, you can:
> 
> * remove the custom .npmrc configuration for private repository
> * remove font awesome occurrences in your package manager lockfiles
> * add font awesome packages again
> 
> This will use dependencies from the public npm repository, without eating private quota and without requiring an active subscription

I have never had a subscription. I do NOT use the pro version. Only the free version. This has never been a problem before. I have also not installed any new dependencies when this started happening.

I have had these fontawesome dependencies installed for a couple years with 0 problems and no pro subscription at all.

`"@fortawesome/fontawesome-svg-core"` has never been private before. Why is it suddenly now?

**Comment by tagliala** [comment]
Is it possible that for some reason the package repository has been configured for the Pro version and checked in?

Please look for changes in the configuration of the package manager 

![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/2f66b484-16e6-4c1d-8f5a-376474e76633)

> has never been private before.

It is not an issue with the package being private, it is the npm repository used.

Please switch to the public repo as instructed above

We have some troubleshooting here for yarn and npm:

https://fontawesome.com/docs/web/setup/packages#_5-troubleshooting-your-configuration

It should also apply to https://pnpm.io/it/

**Comment by tagliala** [comment]
An example of the fix on a Ruby On Rails application using yarn as package manager is available here: diowa/ruby2-rails5-bootstrap-heroku@3146c8569fb2acf6a367c8e353595865143c8ff3

**Comment by KevinVandy** [comment]
Ok, I created a new `.npmrc` file like this:

```
@fortawesome:registry=https://registry.npmjs.org
```

And it worked, but only after I also regenerated the package lock file.

Turns out that the `.npmrc` file in my home directory on my work computer with the pro license key changed the package lock to point to the pro registries, I guess. I ran package upgrades on my work computer instead of my personal just this one time.

**Comment by tagliala** [comment]
> Turns out that the .npmrc file in my home directory on my work computer with the pro license key changed the package lock to point to the pro registries, I guess

Correct, `npm` traverses all the directory up to the root for `.npmrc`s, so I suggest to use per-project configuration: https://fontawesome.com/docs/web/setup/packages#set-up-npm-token-for-a-specific-project

So, instead of having a global Pro configuration that will affect all the projects, it is better to have `.npmrc` in the specific project that uses Font Awesome Pro
