### ISSUE TITLE
Bug: Pro license not honored

### ISSUE THREAD

**Issue by camposfyi** [FortAwesome/Font-Awesome#19854]
### Bug description

Sorry to write this as a bug, but there's absolutely no way to contact support.

My organization has a pro license. I am added as one of the seats. The issue is that when I log in I ended up in this free account which I believe I created before my organization created its account and added me.

I'm trying to use some of the pro features, but I can't because the site thinks I'm on a free account.

When I try changing my email on the free account to see if next time I log in, it logs me into the pro account, it says it sent a code to my email which I never actually get.

### Font Awesome version

6

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

Windows

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Have you sent an email to hello[at]fontawesome.com? I'm wondering if it's being filtered out somehow.

**Comment by camposfyi** [comment]
> Have you sent an email to hello[at]fontawesome.com? I'm wondering if it's being filtered out somehow.

I just sent an email. I'll wait and see if they can help. Thanks.

**Comment by sensibleworld** [comment]
In regards to the "seats", at this moment, we don't have individual logins for folks other than the primary account holder. The account owner can share the assets and downloadable files or their login credentials with seat users.

We know this isn't the greatest solution for everyone, and are working on improvements.

**Comment by camposfyi** [comment]
Thanks. I was trying to use the icon wizard and it can only be used if you're logged in with a pro account. In our case this is a problem as the account is under the finance department, so the actual developers needing access to this can't access it unless finance shares their username and password with all the devs.
