### ISSUE TITLE
Icon Request: fa- 𝕏 for Twitter Icon 

### ISSUE THREAD

**Issue by cladvi** [FortAwesome/Font-Awesome#19869]
We have to add Twitter Icon to 𝕏 to be relevant and up to date
i do not know how seen other websites using it we want to make like that too... 
![Screenshot 2023-08-19 211812](https://github.com/FortAwesome/Font-Awesome/assets/22783276/84f3ed4a-2776-4453-907e-0a3884aa9458)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

twitter-x icon has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid
- https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
