### ISSUE TITLE
Bug: Weird characters are appearing with fontawesome-pro

### ISSUE THREAD

**Issue by vineeth-ktp** [FortAwesome/Font-Awesome#19863]
### Bug description

Weird characters are appearing with fontawesome-pro - We are using npm package to map pro version `    "@fortawesome/fontawesome-pro": "^5.15.4",
`

![Screenshot 2023-07-27 at 11 50 11 AM (1)](https://github.com/FortAwesome/Font-Awesome/assets/97179771/ffe8008a-d1a0-456c-be20-b386a625d1b0)

I went through existing tickets, but they are either in closed state or the one which are in open state are with self hosted (https://github.com/FortAwesome/Font-Awesome/issues/17644)

### Screenshots

![Screenshot 2023-07-27 at 11 50 11 AM (1)](https://github.com/FortAwesome/Font-Awesome/assets/97179771/a9b98240-0147-46b7-8e8b-c4b28dc845a7)

### Font Awesome version

v5.15.4

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

- Chrome 91

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> I went through existing tickets, but they are either in closed state or the one which are in open state are with self hosted (https://github.com/FortAwesome/Font-Awesome/issues/17644)

This should be the cause of the issue and the ticket is not closed, it is open

It contains a lot of information on how it is possible to fix this issue. I can clearly see that the output CSS contains wrong characters

<img width="572" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/736a6662-509a-4b3d-b11a-03ad4c86db2d">

Please read through that thread and find the solution that works better for your use case

Feel free to comment on #17644 for any other question

**Comment by vineeth-ktp** [comment]
@tagliala : I agree there is already a similar issues, I was able to take a look into those tickets raised. But we have 4+ sites which are using this library and it is happening at random on any site page. We could have tried overriding or pre-load, but this is just a temporary solution for npm package. Hence raised a new ticket for this.

**Comment by tagliala** [comment]
> and it is happening at random on any site page.

Yes, this is a random issue. Did you try to use the latest dart-sass version?

This can be also fixed at nginx level: https://github.com/FortAwesome/Font-Awesome/issues/17644#issuecomment-1362785107

There are a lot of workarounds, but we can't fix in 6.x because it will break backward compatibility
