### ISSUE TITLE
Icon request: FreeYork

### ISSUE THREAD

**Issue by adamszokol** [FortAwesome/Font-Awesome#19875]
Dear,
I have a social media platform services, and i think it's good. This is the FreeYork, and here is the logo.
![freeyork-official](https://github.com/FortAwesome/Font-Awesome/assets/143278538/78cc9c3b-6146-4466-8c4e-919d4ed7c84c)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)
