### ISSUE TITLE
Bug: Can not install fontawesome free on Netlify

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#19884]
### Bug description

Hi guys,

I'm getting the following output when I try to build it on Netlify

`ERR_PNPM_FETCH_401  GET https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/6.2.1/fontawesome-svg-core-6.2.1.tgz: Unauthorized - 401`

What is going wrong? It's happening on all versions.

Tried to update .npmrc and add flags to netlify, but nothing helps

**package.json**

```json
{
  "private": true,
  "version": "1.0.0",
  "devDependencies": {
    "@nuxt/devtools": "^0.8.2",
    "@nuxt/image-edge": "^1.0.0-27840416.dc1ed65",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "nuxt": "^3.7.0",
    "sass": "^1.57.1",
    "sass-loader": "^13.2.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "6.2.1",
    "@fortawesome/fontawesome-svg-core": "6.2.1",
    "@fortawesome/free-brands-svg-icons": "6.2.1",
    "@fortawesome/free-regular-svg-icons": "6.2.1",
    "@fortawesome/free-solid-svg-icons": "6.2.1",
    "@fortawesome/vue-fontawesome": "3.0.2",
    "@storyblok/nuxt": "^5.6.11",
    "axios": "^1.3.2",
    "moment": "^2.29.4",
    "swiper": "^8.4.6"
  }
}
```

**pnpm config list (local)**
```
//npm.fontawesome.com/:_authToken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@fortawesome:registry=https://npm.fontawesome.com/
global=false
registry=https://registry.npmjs.org/
shamefully-hoist=true
strict-peer-dependencies=false
user-agent=pnpm/8.7.1 npm/? node/v16.20.2 win32 x64
```

**pnpm config list (global)**
```
//npm.fontawesome.com/:_authToken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@fortawesome:registry=https://npm.fontawesome.com/
global=true
registry=https://registry.npmjs.org/
shamefully-hoist=true
strict-peer-dependencies=false
user-agent=pnpm/8.7.1 npm/? node/v16.20.2 win32 x64
```

### Font Awesome version

6.4.2

### Serving

Other (as specified in the bug description)

### Implementation

SVG+JS

### Browser and Operating System

    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 4.25 GB / 15.41 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0)
    Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> ERR_PNPM_FETCH_401  GET https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/6.2.1/fontawesome-svg-core-6.2.1.tgz: Unauthorized - 401

I can see this is attempting to use the Pro repository, which is only available to paying customers with an active subscription

Please take a look at our troubleshooting section:

https://fontawesome.com/docs/web/setup/packages#_5-troubleshooting-your-configuration

PS: if you are a pro customer, you can ask for dedicated support at hello@fontawesome.com

**Comment by tagliala** [comment]
I can see that `pnpm`, has a `pnpm config list` like npm, but does not provide information on where the settings are stored

~I understand that `pnpm` does not traverse the tree up to the root, so it is either local (per-project) config or global config, so the pro repository configuration "leaked" from a `.npmrc` in the current directory or from a global `.npmrc`.`~

```
pnpm config list --local # if output contains `//npm.fontawesome.com/:_authToken=`, then FA is locally configured
pnpm config list --global # if output contains `//npm.fontawesome.com/:_authToken=`, then FA is globally configured
```

https://pnpm.io/npmrc says that there are four relevant configuration files. Please check according to your package manager where is the file that contains the wrong configuration

If there are multiple developers working on the same project, we suggest that all developers remove their Font Awesome configuration from the global `.npmrc` and configure it per-project, otherwise there could be unintended changes to `pnpm-lock.yaml`

**Comment by stijns96** [comment]
Hi @tagliala ,

I am a pro user, but don't need and want to add the pro package to this project.

I also had this issue with npm tho.

What about the .npmrc? Locally everything works fine, because I can simply install the dependancies and do a npx nuxi generate. But for some reason, on Netlify I'm getting this error. As soon as I remove the fontawesome package, everything seems to work fine.

**Comment by ghost** [comment]
Hi @tagliala ,

I am a pro user, but don't need and want to add the pro package to this project.

I also had this issue with npm tho.

I did the CLI commands and I've updated my ticket. You can now see the npmrc values. I have them locally for the pro sub, but as you can see in my package.json, I'm only using free packages in this project. So I'm not really sure what is happening.

**Comment by tagliala** [comment]
> I am a pro user, but don't need and want to add the pro package to this project.

That is why we suggest to configure per-project npmrc only in projects where pro is needed

> I also had this issue with npm tho.

Yes, it's the same configuration file, this is expected

> You can now see the npmrc values.

Thanks. As far as I can tell, Pro is set for both local and global `.npmrc`s. You should remove the configuration entry from the global and local one, delete font awesome entries in the lockfile, and `pnpm install` again.

I do not exactly understand what `per-workspace configuration file (the directory that contains the pnpm-workspace.yaml file)` means, so please check that this yml file does not contain the token

Maybe `npm config list --verbose` may help in identifying files

For project that need Pro, create a `.npmrc` in the root of the project and add the token here. It would be better to add token with an environment variable to prevent it to be committed by mistake

Ref https://pnpm.io/npmrc

> Values in the .npmrc files may contain env variables using the ${NAME} syntax. The env variables may also be specified with default values. Using ${NAME-fallback} will return fallback if NAME isn't set. ${NAME:-fallback} will return fallback if NAME isn't set, or is an empty string.

**Comment by ghost** [comment]
Hi @tagliala,

That worked perfectly! Many thanks.
