### ISSUE TITLE
Feature request: Find what site is consuming the bandwidth

### ISSUE THREAD

**Issue by danielgutierrezcolorado** [FortAwesome/Font-Awesome#19887]
### Feature description

When using the font awesome free, you can't figure out what site is using the bandwidth

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Hi there! Send us a message at hello [at] fontawesome [dot] com, and we can look into this for you.
