### ISSUE TITLE
Icon Request: icon-ice-cream

### ISSUE THREAD

**Issue by konradsroka** [FortAwesome/Font-Awesome#1988]
A tasty ice cream icon: 
(for me) something incredible important with a wide variety to use..  

Can be used to show anything cool, tasty, funny, nice, beautiful things to show off. 

Would be also a nice icon to use for a showcase, for summer topics, for special deals, ... many many ideas for usage of ice cream and tasty sweet things :) 

cheers, konrad

**Comment by jberta93** [comment]
+1

**Comment by thomps** [comment]
+1

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone via #1895 

Note that this could be shifted to a future release

**Comment by G-Driver** [comment]
+1

**Comment by akerd** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-ice-cream and fa-popsicle was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by charlesr1971** [comment]
fa-ice-cream sounds great. 

I have been waiting for this with anticipation. 

Is it available, if I use this extension?

Thanks

Charlie

Charles Robertson

Classroom, Technical Director

E: cdesign@btinternet.com
U: www.classroom.me.uk

**Comment by charlesr1971** [comment]
I see what you mean.
I have just looked at:

font-awesome-extenssion.svg

I can't wait to see some of these, like fa-hamburger!

I never realised that font-awesome icons come from SVG, but it makes sense though. 

Do you create them in Adobe Illustrator?

Thanks for this...

Charlie

Charles Robertson

Classroom, Technical Director

E: cdesign@btinternet.com
U: www.classroom.me.uk

**Comment by AndreLGava** [comment]
@charlesr1971  Yea I have used Adobe Illustrator, You can use fa-icecream and others :D

**Comment by charlesr1971** [comment]
Andre

 

These are fantastic. I have just opened them up in my browser!

 

fa-ice-cream was worth waiting for!

 

Charlie

**Comment by AndreLGava** [comment]
<3 thanks. I'll try to to increase this as soon as possible, with new icons and more documentation, just hope that anothers use and love this :). Share ;)

**Comment by charlesr1971** [comment]
Thanks Andre. I will share!

Charles Robertson

Classroom, Technical Director

E: cdesign@btinternet.com
U: www.classroom.me.uk

**Comment by garfieldnate** [comment]
:+1:

**Comment by Crissov** [comment]
- 🍨 [U+1F368](http://emojipedia.org/ice-cream/) Ice Cream (dairy) Unicode emoji #222
- 🍦 [U+1F366](http://emojipedia.org/soft-ice-cream/) Soft Ice Cream (dairy)
- 🍧 [U+1F367](http://emojipedia.org/shaved-ice/) Shaved Ice (water/juice)

**Comment by charlesr1971** [comment]
Amazing!

Charles Robertson

Establish Mindfulness, Technical Director

E: cdesign@btinternet.com
U: app.establishmindfulness.com

**Comment by elenamg75** [comment]
+1

**Comment by charlesr1971** [comment]
And maybe fa-lolly-pop, whilst we are on the ice cream theme!😋

**Comment by sensibleworld** [comment]
Hey folks! We added an ice cream cone in version 5.7.0. Does that fit work for this reqyuest? https://fontawesome.com/icons?d=gallery&q=ice%20cream

**Comment by charlesr1971** [comment]
Looks really great!

**Comment by tagliala** [comment]
If https://fontawesome.com/icons/ice-cream?style=solid does not fit your needs, feel free to comment

Meanwhile, closing here
