### ISSUE TITLE
Bug: at least 2 icons in the documentation are missing from the CDN

### ISSUE THREAD

**Issue by bearaxe** [FortAwesome/Font-Awesome#19881]
### Bug description

My project is currently using the volume-slash and the volume icons. When i go to the cdn and search for the unicode string in the cdn, there are no results. I don't know how this happened as when I first built this page, the icons existed and pulled in just fine.

Reproduce the issue by:
going to this cdn link: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css
searching for the volumn-slash class: fa-volume-slash -> find nothing
searching for the volume-slash unicode: \f2e2 -> find nothing
searching for the volume class: fa-volume -> find nothing
searching for the volume unicode: \f6a8 -> find nothing

See the links where we got these icons in the first place:
https://fontawesome.com/icons/volume?f=classic&s=solid
https://fontawesome.com/icons/volume-slash?f=classic&s=solid

### Reproducible test case

can't get codepen to work with fontawesome, sorry about that. screenshots should suffice as this appears to be a css inclusion issue

### Screenshots

<img width="1325" alt="Screenshot 2023-08-31 at 6 07 58 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/20572230/cef96893-d06f-4949-bc53-1aa555b4fb2b">
<img width="1331" alt="Screenshot 2023-08-31 at 6 06 24 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/20572230/e0698d0a-0c5e-4b58-a666-fd545699d230">
<img width="1345" alt="Screenshot 2023-08-31 at 6 05 37 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/20572230/bd5109bb-66a7-4de3-abdd-63c1d8f0d9af">
<img width="1333" alt="Screenshot 2023-08-31 at 6 09 37 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/20572230/1cf6c83d-8ed9-4e2a-b1f8-f6817cb5f116">

### Font Awesome version

v6.4.2

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

- Chrome mac / all

### Web bug report checklist

- [x] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please notice that `fa-volume` and `fa-volume-slash` are only available in FA Pro

In the future, documentation will be improved to make this more clear in the icon documentation page

For the moment, please make sure to select "free" when using search: https://fontawesome.com/search?q=volume&o=r&s=solid

It is also worth to mention that **in a web application** it is possible to create `volume-slash` icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:
- https://jsfiddle.net/tagliala/bfa6uhse/211/

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader
