### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by TJRelly** [FortAwesome/Font-Awesome#19883]
Free
For Free icons, you can add either -- or both -- of these styles:

# Free icons styles
npm i --save @fortawesome/free-solid-svg-icons
npm i --save @fortawesome/free-regular-svg-icons

*** Should include: npm i --save @fortawesome/free-brands-svg-icons ***
I'd like to change it, but unsure of how.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

The documentation source code is hosted in a private repository

Can you please send me the link in the documentation where you want to make the changes?

**Comment by TJRelly** [comment]
https://fontawesome.com/docs/web/use-with/react/

**Comment by tagliala** [comment]
Thanks.

@talbs any chance to edit the documentation at https://fontawesome.com/docs/web/use-with/react/#free to include `brands` ?

**Comment by talbs** [comment]
Thanks for bringing this to our attention, @TJRelly! We've got these docs updated with your great suggestion at https://fontawesome.com/docs/web/use-with/react/#free. Shout if you see anything else that's less than Awesome around the site.

**Comment by TJRelly** [comment]
Glad that I could help!
