### ISSUE TITLE
twitter logo icon

### ISSUE THREAD

**Issue by amitkt19** [FortAwesome/Font-Awesome#19890]
Kindly update it

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon x-twitter has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid
- https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
