### ISSUE TITLE
Bug: "mutateApproach" field missing from Config object in typescript declaration file

### ISSUE THREAD

**Issue by SeanMaclochlainn** [FortAwesome/Font-Awesome#19898]
### Bug description

In js-packages/@fortawesome/fontawesome-svg-core/index.d.ts, the Config object is missing the field "mutateApproach"
![image](https://github.com/FortAwesome/Font-Awesome/assets/9976582/761b0a8c-018c-4293-b30f-4b08af0ea6a8)

As per the documentation this field should be listed here: https://fontawesome.com/v6/docs/apis/javascript/configuration#contentHeader 

Screenshot from my application:
![image](https://github.com/FortAwesome/Font-Awesome/assets/9976582/d4bc483c-c7a2-4431-93d2-e9b2a1295e6f)
(as a workaround, I add // @ts-ignore and it works ok)

### Font Awesome version

v6.4.0

### Application and Operating System

N/A

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by SeanMaclochlainn** [comment]
At @tagliala if you'd like I could make a PR with the fix for this? Should just be an update to the Config object in the typescript declaration file

**Comment by robmadole** [comment]
We'll get this fixed in 6.5.0 which should be going out very soon.

**Comment by SeanMaclochlainn** [comment]
> We'll get this fixed in 6.5.0 which should be going out very soon.

Great, thanks!
