### ISSUE TITLE
Bug: `solid``copy` icon and `regular``copy` icon are the same

### ISSUE THREAD

**Issue by eremannisto** [FortAwesome/Font-Awesome#19902]
### Bug description

In Font Awesome 6 Subsetter desktop app `Version 6.4.0 (6.4.0-ts.1695718074234)`, the `copy` icon is the same for `solid` and `regular`. This happens both in `rounded` and `sharp` mode.

<img width="721" alt="Screenshot 2023-09-26 at 12 20 23" src="https://github.com/FortAwesome/Font-Awesome/assets/102978426/6e9b467f-9c5d-4c62-90f6-697b2861b69b">

### Font Awesome version

v6.4.0 (6.4.0-ts.1695718074234)

### Application and Operating System

- MacBook Pro 2021 (Apple M1 Max) - Ventura (13.4.1)

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This has been fixed in 6.4.2, please upgrade

Ref: #19674

Closing here
