### ISSUE TITLE
Icon request: icon-x

### ISSUE THREAD

**Issue by fannyspotlight** [FortAwesome/Font-Awesome#19906]
### Use case

Icon to be used on websites to lead to own social media account 

### Example image

<img width="668" alt="Screenshot 2023-09-26 at 14 37 08" src="https://github.com/FortAwesome/Font-Awesome/assets/146127560/3e72e06e-79a9-4e75-ba45-a8f686ed1ce3">
<img width="662" alt="Screenshot 2023-09-26 at 14 37 15" src="https://github.com/FortAwesome/Font-Awesome/assets/146127560/ccd4e2f5-7911-413c-81ae-1dc1db413c0f">

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

X icon has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid
- https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by adaniello** [comment]
@tagliala Why not add this to FontAwesome 5.15 too for consistency?

Thanks

**Comment by tagliala** [comment]
> Why not add this to FontAwesome 5.15 too for consistency?

Sorry, FA5 is maintenance mode only for bug fixes

Ref: https://fontawesome.com/support#is-font-awesome-5-still-being-supported
