### ISSUE TITLE
Brand request: 

### ISSUE THREAD

**Issue by gresavage** [FortAwesome/Font-Awesome#19919]
### Description

[Mattermost](https://www.mattermost.com/) is an open source, self-hosted Slack-alternative.

This is the same request as https://github.com/FortAwesome/Font-Awesome/issues/9727 but perhaps it is not seen because the subject is improperly formatted

```html
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="500" height="500" viewBox="0 0 500 500">
  <path id="mattermost" fill="#000000" stroke="none"
        d="M 250.05,34.00
           C 251.95,34.04 253.85,34.11 255.65,34.20
             255.65,34.20 225.86,69.71 225.86,69.71
             225.79,69.72 225.71,69.74 225.63,69.75
             149.26,84.10 98.22,146.50 98.22,222.97
             98.22,264.53 121.29,313.47 157.97,342.07
             186.58,364.39 222.26,378.97 259.18,378.97
             352.58,378.97 419.33,310.36 419.33,222.97
             419.33,188.06 403.34,150.20 377.57,122.21
             377.57,122.21 375.94,74.82 375.94,74.82
             430.39,113.97 465.89,177.84 466.00,249.99
             466.00,250.00 466.00,250.00 466.00,250.00
             466.00,369.29 369.30,466.00 250.00,466.00
             130.71,466.00 34.00,369.29 34.00,250.00
             34.00,130.71 130.71,34.00 250.00,34.00
             250.00,34.00 250.05,34.00 250.05,34.00 Z
           M 314.15,54.29
           C 314.81,54.25 315.47,54.32 316.11,54.54
             319.12,55.54 319.96,58.11 320.04,60.99
             320.04,60.99 323.88,207.87 323.88,207.87
             324.64,236.53 306.72,276.31 263.49,276.43
             232.52,276.51 199.81,255.60 199.81,216.30
             199.82,201.57 205.42,185.04 219.06,168.19
             219.06,168.19 309.09,57.01 309.09,57.01
             310.24,55.59 312.17,54.43 314.15,54.29
             314.15,54.29 314.15,54.29 314.15,54.29 Z" />
</svg>
```

### Official website

https://mattermost.com/

### Brand guidelines

https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/brand-and-visual-design-guidelines

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

> This is the same request as https://github.com/FortAwesome/Font-Awesome/issues/9727 but perhaps it is not seen because the subject is improperly formatted

#9727 is fine, the new template has been introduced after so you may see some differences

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here

**Comment by gresavage** [comment]
Thanks for the fast feedback. I appreciate your support

I see that a mattemost icon is among the leaders on the leaderboard in similar demand to some other notable large brands (Netflix, Kubernetes, Arduino, MS 365). Hopefully this means it will be added soon!
