### ISSUE TITLE
Icon request: fa icon-turtle

### ISSUE THREAD

**Issue by OneNoneBlond** [FortAwesome/Font-Awesome#19926]
Turtle often used as symbol is missing in font awsome and it would be awsome to have it :)

![11](https://github.com/FortAwesome/Font-Awesome/assets/146766116/c005c34a-10c3-4bd1-a3f4-bf743ed9c927)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon turtle has been added to Font Awesome Pro in version 5.4.0:
- https://fontawesome.com/icons/turtle?f=classic&s=solid

Hope it helps

Closing here
