### ISSUE TITLE
Twitter X - in Font Awesome 5 Brands

### ISSUE THREAD

**Issue by sarah-sweatt** [FortAwesome/Font-Awesome#19931]

**Comment by pragyamishra56** [comment]
@sarah-sweatt If it would be possible then can you assign me to this issue I want to resolve this would be my first contribution

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Quoting from: https://fontawesome.com/support#is-font-awesome-5-still-being-supported

> ### Is Font Awesome 5 still being supported?
>
> Yes, Font Awesome 5 is officially supported until we announce otherwise. **However, all new icons,** features, and services **will be under the umbrella of Version 6**. We'll continue to provide fixes for bugs and issues in Version 5.
>
> Existing services like Kits, Pro CDN, and packages, that provide access to Version 5 will also continue to be available.

**Emphasis** mine

So I would say that FA5 will not receive this update

/cc @robmadole

**Comment by sensibleworld** [comment]
Thanks, @tagliala. To confirm, we are no longer adding new icons to Version 5. The X logo is already available in Font Awesome 6, so we would suggest updating to that.
