### ISSUE TITLE
New patreon logo

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#19936]
### Discussed in https://github.com/FortAwesome/Font-Awesome/discussions/19935

<div type='discussions-op-text'>

<sup>Originally posted by **Spinball** October  6, 2023</sup>
There is a new Patron logo.
https://news.patreon.com/articles/patreon-redesigned

Is the Fontawesome icon f3d9 going to get swapped out?
</div>

**Comment by sensibleworld** [comment]
Updated: https://fontawesome.com/icons/patreon?f=brands&s=solid
