### ISSUE TITLE
Icon request:Bayes or Bell Curve or Gaussian

### ISSUE THREAD

**Issue by RonItelman** [FortAwesome/Font-Awesome#19939]
Would love to have some data science icons, a bell curve would be great!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+)

Closing here, but feel free to comment if I've missed something
