### ISSUE TITLE
Icon request: icon-category

### ISSUE THREAD

**Issue by xWenChen** [FortAwesome/Font-Awesome#19949]
the tag icon is exist, but a category icon is not exist

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I've just closed [#13523](https://github.com/FortAwesome/Font-Awesome/issues/13523) which is a duplicate of this request

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) by providing a single color, 16px icon size suitable example of how a "category" should look like

Closing here
