### ISSUE TITLE
Icon request: fa-pronouns

### ISSUE THREAD

**Issue by liellnima** [FortAwesome/Font-Awesome#19948]
### Use case

Hi there,

as pointed out this March in [Issue number 19592] (https://github.com/FortAwesome/Font-Awesome/issues/19592) it would be great to have an icon that can be used to depict "pronouns". So far it has not been included (to the best of my knowledge).

Different use-cases apply obviously. Just giving one example here would be wanting to put your pronouns on a CV and have an icon for it similarly like for your phone / email address / website.

As pointed out in the issue there is already an established icon - I attached the image. There would also be the possibility to add several icons for the different subsets of pronouns as you can see in the second image.

Thank you very much for considering adding this as an icon! :D 

Suggested pronoun icon by [The Noun Project](https://thenounproject.com/icon/colors-2812202/):

![pronouns](https://github.com/FortAwesome/Font-Awesome/assets/44509330/0a8c7e15-2cfa-4b69-a1d4-1cdfa2210595)

Potential additional pronoun icons (can be seperate requests I guess):

![pronoun_icon_range](https://github.com/FortAwesome/Font-Awesome/assets/44509330/5543afe9-404a-4d4b-ae9d-93a6c4e3ea31)

### Example image

![pronouns](https://github.com/FortAwesome/Font-Awesome/assets/44509330/ce7d3496-5b85-4c20-9d8a-d3a953bcf8fa)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by liellnima** [comment]
[Here is the link for the second image](https://coxy.co/wp-content/webp-express/webp-images/uploads/2021/06/Pronoun-Icon-Range-2048x535.png.webp)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
