### ISSUE TITLE
The new Print icon in Duotone is awful when colored

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#19944]
### Discussed in https://github.com/FortAwesome/Font-Awesome/discussions/19943

<div type='discussions-op-text'>

<sup>Originally posted by **tinwe** October 12, 2023</sup>
The new version of Print has a cut out in the middle of its pages, which only makes it confusing and misleading when colored. The previous version did not have this problem.

![Skärmbild 2023-10-12 080835](https://github.com/FortAwesome/Font-Awesome/assets/4280267/bac3b713-0426-40c6-8409-a432fd40264c)
</div>

**Comment by sensibleworld** [comment]
This has been fixed in 6.5.2 https://fontawesome.com/icons/print?f=classic&s=duotone
