### ISSUE TITLE
Icon request: donut-chart

### ISSUE THREAD

**Issue by leroyuk1983** [FortAwesome/Font-Awesome#19945]
something like this

[https://www.flaticon.com/free-icon/donut-chart_5369023?term=donut+chart&page=1&position=37&origin=tag&related_id=5369023](https://www.flaticon.com/free-icon/donut-chart_5369023?term=donut+chart&page=1&position=37&origin=tag&related_id=5369023)

**Comment by aethior** [comment]
Duplicate of #7520.
Please add a 👍 reaction to that request.

Regards.

cc/ @tagliala

**Comment by leroyuk1983** [comment]
> Duplicate of #7520. Please add a 👍 reaction to that request.
> 
> Regards.
> 
> cc/ @tagliala

Thanks for that, thumbs to the duplicate post
