### ISSUE TITLE
Bug: Unable to sign up for a FontAwesome account

### ISSUE THREAD

**Issue by elioqoshi** [FortAwesome/Font-Awesome#19955]
### Bug description

Unable to sign up for a fontawesome account:

`{ "reason": "token_expired", "failure": "invalid_token" } `

### Reproducible test case

https://fontawesome.com/start

### Screenshots

<img width="1120" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/5436686/c3a69fa4-4e78-46c8-ab35-f1b1d6c6d118">

### Font Awesome version

6.4.2 

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Firefox 117.01 on macOS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hi @elioqoshi send us a message at hello@fontawesome.com and we can take a look at your account.

**Comment by sivy** [comment]
Same here - trying to register today and getting this error. Firefox 130.0.1 (64-bit)
