### ISSUE TITLE
Icon request: dietary restrictions

### ISSUE THREAD

**Issue by nicemodernwebsites** [FortAwesome/Font-Awesome#19956]
Icons representing lactose-free, pareve, halal, vegan etc. to apply to food, drink, and other consumable products; i.e. a restaurant site with an online menu.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Possibly related to: #5228 

Closing here, but feel free to comment if I've missed something
