### ISSUE TITLE
Icon request: fa-twitter-new for version 5 and 4

### ISSUE THREAD

**Issue by margaret8554** [FortAwesome/Font-Awesome#19959]
### Use case

Hello,

We are using Twitter icons on most of the State of NJ websites. The sites are still using Font awesome version 4 or 5. Unfortunately the X icon is available only for version 6. Would be possible to update the icon or add the new one to the previous versions of Font Awesome?

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, as per https://fontawesome.com/support#is-font-awesome-5-still-being-supported, FA5 will only receive bug fixes and FA4 is in EOL

New icons are not considered bug fixes, please upgrade your Font Awesome version or use a custom build

Closing here but feel free to comment
