### ISSUE TITLE
Icon Request: fa-hdf5  fa-nexusformat

### ISSUE THREAD

**Issue by vedina** [FortAwesome/Font-Awesome#19953]
Hello,

Would be nice to have icons for the following formats.
fa-hdf5  https://www.hdfgroup.org/solutions/hdf5/
fa-nexusformat https://www.nexusformat.org/

Use case- icons for download in online scientific databases .

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out two separate [brand request templates](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something
