### ISSUE TITLE
Icon request: icon-browser-interworking

### ISSUE THREAD

**Issue by Sporran** [FortAwesome/Font-Awesome#1996]
I'd welcome an icon representing direct browser-to-browser interworking (a hot topic at the moment). Implementation suggestion:

2 "icon-user" icons, joined by either icon-ellipsis-horizontal OR (better) icon-resize-horizontal OR (BETTER STILL) icon-exchange.

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/people-arrows?

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, I think so, thanks
