### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by futbotmakecoins** [FortAwesome/Font-Awesome#19961]
Hi, could you create a Discord icon? Thanks

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Discord icon has been added to FontAwesome in version 5.0:
- https://fontawesome.com/icons/discord?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
