### ISSUE TITLE
Bug: On React Installation page

### ISSUE THREAD

**Issue by AdityaRaj0001** [FortAwesome/Font-Awesome#19962]
Steps to See the Bug:
[ visit ](https://fontawesome.com/docs/web/use-with/react/)

In the code snippets provided the code has error it should be :
npm i --save @fontawesome/react-fontawesome@latest

instead of npm i --save @fortawesome/react-fontawesome@latest

Do you see the bug? It's fortawesome.

**Comment by robmadole** [comment]
It's actually correct! Thanks for taking the time to submit though.

**Comment by AdityaRaj0001** [comment]
Thanks for the early clarification Rob.
