### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by Chris360cc** [FortAwesome/Font-Awesome#19977]
Could you please make an icon for Tiktok? Thank you ^^!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon TikTok has been added to FontAwesome in version 5.13.1. Latest version is 6.4.2:
- https://fontawesome.com/icons/tiktok?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
