### ISSUE TITLE
Icon request: icon-name (e.g., Icon request: icon-car)

### ISSUE THREAD

**Issue by 4minutesnl** [FortAwesome/Font-Awesome#19979]
### Use case

Whatsapp channel logo to be used into WP theme and Qode thembuilder

### Example image

https://vectorseek.com/vector_logo/whatsapp-channels-logo-vector/

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Please use a web browser to fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+) for this request

For copyright reasons, it is better that this request is considered a `brand` request

Please also provide an official resource for this icon (from whatsapp's official website)
