### ISSUE TITLE
Icon Request: icon-chair

### ISSUE THREAD

**Issue by debuggertest** [FortAwesome/Font-Awesome#1998]
i can't find a chair icon in font awesome list.
i would to use on this furniture website http://www.mautren.it/ in the menu (sedute item).
The mood of the icon should be the office. 

example
https://cdn3.iconfinder.com/data/icons/glyph/227/Chair_1-128.png
or
http://icons.mysitemyway.com/wp-content/gallery/magic-marker-icons-business/thumbs/thumbs_114940-magic-marker-icon-business-chair5-sc52.png

Thanks in advance.

:+1:

**Comment by mgoldwasser** [comment]
+1

**Comment by tabacha** [comment]
+1

**Comment by FrazzApps** [comment]
+1

**Comment by KoinPlusDev** [comment]
+1

**Comment by lime** [comment]
+1

**Comment by anandchavan** [comment]
+1

**Comment by javator** [comment]
+1

**Comment by Foonz** [comment]
+1

**Comment by pxzin** [comment]
+1

**Comment by smaspe** [comment]
+1

**Comment by ch-herden** [comment]
+1

**Comment by carrymetwo** [comment]
+1

**Comment by bouwaccount** [comment]
+1

**Comment by yangjm** [comment]
+1

**Comment by juancarlosfarah** [comment]
+1

**Comment by ohjames** [comment]
A chair would be...

**Comment by jhmacdon** [comment]
+1

**Comment by steimntz** [comment]
+1

**Comment by RenanOliv** [comment]
+1

**Comment by jasonalex13** [comment]
+1

**Comment by codynguyen1116** [comment]
+1
1

**Comment by marcinmw** [comment]
+1

**Comment by evinkuraga** [comment]
+1

**Comment by harryi3t** [comment]
+1

**Comment by viveknc** [comment]
+1

**Comment by cappern** [comment]
+1

**Comment by hsuallen** [comment]
+1

**Comment by ohjames** [comment]
Thanks for all the +1s, they were great. Too much of a good thing is just making me feel so undeserving though so I'm off. Have a lovely time without me and *power to the chair* :baby_chick:

**Comment by lazystone** [comment]
+1

**Comment by estchuy** [comment]
+1

**Comment by NBillings707** [comment]
+1

**Comment by DraganLibraFire** [comment]
+1

**Comment by ohjames** [comment]
Instead of messaging +1 which sends a message to hundreds of people you're supposed to click the thumbs up icon on the original comment.

**Comment by giladkl** [comment]
+1

**Comment by shturm** [comment]
+1

**Comment by iaK** [comment]
+1

**Comment by rizkiandrianto** [comment]
+1

**Comment by tuomas777** [comment]
+1

**Comment by akovacevic** [comment]
+1

**Comment by 2imahl** [comment]
+1

**Comment by andyiwest** [comment]
Any more news on these?

**Comment by granatdesign** [comment]
+1

**Comment by kaspercools** [comment]
+1

**Comment by pedrovegaonline** [comment]
+1

**Comment by woodcockjosh** [comment]
+1

**Comment by RemekConsulting** [comment]
+1

**Comment by aashiq2006** [comment]
+1

**Comment by ODelibalta** [comment]
So this was opened 4 years ago and still in demand. Any solutions?

**Comment by andresilvasantos** [comment]
+1

**Comment by ApollyonGrim** [comment]
+1

**Comment by carlysmith** [comment]
+1

**Comment by simonalexandergilbert** [comment]
+1

**Comment by mikecabana** [comment]
+1

**Comment by markoj3s** [comment]
+1

**Comment by olek2289** [comment]
+1

**Comment by adrgomser** [comment]
+1

**Comment by watoo** [comment]
+1

**Comment by peterhammer** [comment]
+1

**Comment by Simon-J-N-Reading** [comment]
+1

**Comment by savadodesigns** [comment]
+1

**Comment by anandchavan** [comment]
https://fontawesome.com/icons/loveseat?style=solid

this solves the purpose partially

**Comment by Simon-J-N-Reading** [comment]
@anandchavan : point taken :-) however does not work well with anything "office" or "Seat at the table", "Seat on the board",  anything architectural / work related .... in the same way a deckchair would not equate. : so it still gets my  + (and hopes)

**Comment by sensibleworld** [comment]
We've added a simple chair icon: https://fontawesome.com/icons/chair?style=solid, as well as an office chair icon https://fontawesome.com/icons/chair-office?style=solid

**Comment by Simon-J-N-Reading** [comment]
Yay Hey! - Awesome ;-)
