### ISSUE TITLE
Bug:  fa-regular displays as square

### ISSUE THREAD

**Issue by KaptianM** [FortAwesome/Font-Awesome#19983]
### Bug description

fa-regular displays as square/
When Trying to play with font-weight its look like the icon can display as 900 when the value is 600+.

### Screenshots

![image](https://github.com/FortAwesome/Font-Awesome/assets/149778776/5222318c-32b5-48b6-a40d-f4f14a00c83e)

### Font Awesome version

V6.0.0 free, V5.15.5 pro

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

- Chrome 115, Chrome 117, Windows 10

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can you please provide a reproducible test case?

**Comment by sensibleworld** [comment]
Haven't received a response, so closing.
