### ISSUE TITLE
Bug: Error compiling .less

### ISSUE THREAD

**Issue by dtargaryen** [FortAwesome/Font-Awesome#19994]
### Bug description

Hello there,

I am developing with Font Awesome 6.4.2. When compiling .less, I would get an error

`>> ParseError: Could not parse call arguments or missing ')' in \fontawesome-free-6.4.2-web\_list.less on line 13, column 66:`
`>> 12 .@{fa-css-prefix}-li {`
`>> 13   left: calc(~'var(--@{fa-css-prefix}-li-width, @{fa-li-width})' * -1);`
`>> 14   position: absolute;`

The same error occurs with other .less files like _sizing.less. It looks like this issue was reported and closed before: #18835 and #18867 for Font Awesome version 6.1. Please help!

Thanks.

### Font Awesome version

v6.4.2

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Chrome Version 119.0.6045.124 on Windows
Firefox 119.0 on Windows

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by JesperHerrloff** [comment]
My guess is that you have a early version of less which not has support for the each function. If I recall correct it was introduced in less v3.7 or something like that. As a workaround you can manually add the icons. The places where the each is just maps the css to the var. 

Did it myself today. Copy all icons in .fa-icons in variables Then its just a mark all game and add .fa- where it says @fa--css-prefix and key will be the part before.: in variables file and value the part after. The structure is as below

.@{fa-css-prefix}-@{key}::before { content: @value; } 

And the result when you did your work: 
.fa-0:before { content: @fa-var-0; }

The same applies for the sizes:
.fa--2xs {
    .fa-size(@fa-size-scale-2xs);
}
.fa--xs {
    .fa-size(@fa-size-scale-xs);
}
.fa--sm {
    .fa-size(@fa-size-scale-sm);
}
.fa--lg {
    .fa-size(@fa-size-scale-lg);
}
.fa--2xl {
    .fa-size(@fa-size-scale-2xl);
}

**Comment by dtargaryen** [comment]
Thanks! That makes sense. It sounds doable and I'll give it a try.

Greatly appreciate your help and for taking the time to troubleshoot
my issue.
