### ISSUE TITLE
Icon Request: fa-ellipsis-rotate-right ("in progress")

### ISSUE THREAD

**Issue by Jazzyspoon** [FortAwesome/Font-Awesome#19997]
I am a software developer and I have client feedback that using the 'fa fa spinner' doesn't quite represent 'in progress' properly.  They sent me this clipped image as an example and I can't find anything in your library quite like it.  I tried making one, but I would love if I could just use my fontawesome library instead.  I attached the one I tried making in canva, but it doesn't look right next to your other ones in my software.  Can you help?

the example:
![in_progress_example](https://github.com/FortAwesome/Font-Awesome/assets/77120503/316ac228-dc3f-447a-abec-00b69ef009f8)

my canva mockup:
![in_progress](https://github.com/FortAwesome/Font-Awesome/assets/77120503/303d396a-c1e4-4550-8b95-9b9ca85a33c7)

Anyways, thanks for the awesome icons and I look forward to knowing if this is possible.
-Jason

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

**In a web application** it is possible to create an icon that may work for this use case by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/8kwpvnxt/2/

Please also consider some alternatives to indicate "in progress", like:

- https://fontawesome.com/icons/bars-progress?f=classic&s=solid
- https://fontawesome.com/icons/arrows-spin?f=classic&s=solid
- https://fontawesome.com/icons/rotate?f=classic&s=solid

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer

**Comment by Jazzyspoon** [comment]
Very cool!   Thank you so much for the quick reponse.  I will use the demo and see what I can do with it.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
