### ISSUE TITLE
GOODtime - Bons plans activités et sorties autour de toi

### ISSUE THREAD

**Issue by Robertuo1994** [FortAwesome/Font-Awesome#19999]
https://www.goodtime.com/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If this is a request to add a new icon for a brand, please fill out our [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something
