### ISSUE TITLE
fa-swap and fa-swap-arrows not available without including js

### ISSUE THREAD

**Issue by LennaertDirectAccess** [FortAwesome/Font-Awesome#19998]
The icons .fa-swap and .fa-swap-arrows are not shown without including all.js. Including all.js is swapping everything to an svg. Since I work on a large application and styling is applied on the i-tag-elements (also in librarbies) including the javascript is not an option (it messes up all the styling of icons in the whole application. Desired is support of all icons without the need of javascript.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

`fa-swap` and `fa-swap-arrows` are available in FA Pro, starting from 6.4.1, so I guess this is a bug report for FA Pro 6.4.1

I've just downloaded the css file from https://fontawesome.com/download and the classes are there

I've also checked on my local environment with FA Pro 6.4.2

<img width="509" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/694833cd-4f2e-4723-b258-a88509a467bd">

Please double check your application, make sure that css and webfonts folder are up to date and there are no cache issues

Closing here, but feel free to comment

**Comment by LennaertDirectAccess** [comment]
Hi!

Apologies! I have replicated the isolated case of including all.min.css and did no longer encounter issues. Thus obviously no bug in fontawesome!

The issue I encounter in my application most likely is result of gulp referencing a previous webfont-file (I tried to keep both fa 5 and 6 in the application).
