### ISSUE TITLE
Bug: _animated.less has .scss variable logic and also differ from _animated.scss

### ISSUE THREAD

**Issue by JimKnoxx** [FortAwesome/Font-Awesome#19990]
### Bug description

We are using a self hosted version of the _animated.less file and I noticed, that the bounce animation is not working.  
After looking into the problem I noticed that the _animated.less has a couple of bugs in it.
- the bounce animation-name is not bounce
- it uses .scss variables for the bounce animation keyframes
- the shake animation uses the wrong fallback timing-function (compared to the _animated.scss)

### Font Awesome version

v6.4.2

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Firefox 119.0 (64-bit) Ubuntu

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks

@robmadole 

1. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L14
  -`beat` +`bounce`
3. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L108C1-L111
  replace with less variables
5. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L55
  -`ease-in-out` +`linear`

**Comment by JimKnoxx** [comment]
> Thanks
> 
> @robmadole
> 
>     1. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L14
> 
>     2. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L108C1-L110

3. https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L55

This should be 'linear' as fallback like in the .scss file, this will make the animation less aggressive.

**Comment by bluesweater** [comment]
Thanks to the ticket issuer for finding this bug

@tagliala
re: your comment https://github.com/FortAwesome/Font-Awesome/issues/19990#issuecomment-1798678031 - point 2

in _animated.less, line 111 also has typos and needs fixing

your link https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L108C1-L110 
should be changed to 
https://github.com/FortAwesome/Font-Awesome/blob/f0c25837a3fe0e03783b939559e088abcbfb3c4b/less/_animated.less#L108C1-L111

Pls update comment - thanks in advance

**Comment by robmadole** [comment]
Thanks @JimKnoxx @bluesweater . We've got these fixes in our build ready to go out in the next release.

**Comment by cor3000** [comment]
I just tested with 6.6.0 and the fixes are included and work as expected, thanks for the fix

**RELATED WARNING**: since edge/chrome-beta v129 the syntax errors in font-awesome 6.4.2 (generated from less) cause the CSS parsing to fail in the browser leading to many missing styles (I am not sure whether this is a regression in chrome yet, maybe it gets fixed before release)

I posted the chrome issue https://issues.chromium.org/issues/364443009 

---

**UPDATE 2024-09-05:** it looks like chromium team already fixed the issue in v130 and is planning to backport the fix into v129 before the release of v129 next week (2024-09-11)

**Comment by tagliala** [comment]
Thanks for the heads-up
