### ISSUE TITLE
Icon request: lock-refresh (Reset Password)

### ISSUE THREAD

**Issue by rangelquebit** [FortAwesome/Font-Awesome#20007]
Our wish list includes an icon that can be used for resetting a password.  On other sites, it is commonly seen as an open lock encircled with a refresh symbol.

Thanks,
Reg Angel
QC Analyst
QueBIT Consulting

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Your request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/217/

**Heads-up!** Pro customers can also implement this icon with the [Icon Wizard](https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader)

<img width="1116" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/07ce4f04-24b1-4e67-baba-cd6d4d636dc7">

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

**Comment by rangelquebit** [comment]
Thanks for that information.  I was able to use the icon wizard with our pro account to create fa-kit fa-thin-lock-rotate-right

This is the c# code we are using right now for a password reset icon
<TelerikButton OnClick="() => OnResetPassword(applicationUser)" Icon="@("fa far fa-user-unlock")" Title="Reset Password"></TelerikButton>

How do I code in the customized icon I add to a kit? Can I just call it the same way? Or must I download it and reference it locally?

Thanks,
Reg.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
