### ISSUE TITLE
Brand request: X

### ISSUE THREAD

**Issue by maslfdkj** [FortAwesome/Font-Awesome#20005]
### Description

looks like the twitter logo is still the only option, X isnt an icon

### Official website

https://twitter.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

X icon has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid
- https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
