### ISSUE TITLE
hammer

### ISSUE THREAD

**Issue by cepazzam** [FortAwesome/Font-Awesome#20003]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

hammer icon has been added to FontAwesome in version 5.4.0:
- https://fontawesome.com/icons/hammer?f=classic&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
