### ISSUE TITLE
Bug: PDF icon displaying PNG label

### ISSUE THREAD

**Issue by aaneptune** [FortAwesome/Font-Awesome#20017]
The [file-pdf icon](https://fontawesome.com/icons/file-pdf) is showing a PNG label instead of PDF.
![image](https://github.com/FortAwesome/Font-Awesome/assets/152327160/24e33d2c-1784-4a92-9bfd-082a256f1bd9)

**Comment by sensibleworld** [comment]
Yup. Thanks for the note! We're hoping to get a fix out tomorrow. Sorry about that.

**Comment by Neustradamus** [comment]
@aaneptune: Good catch!

@sensibleworld: There will have one for PNG and one for PDF?

**Comment by sensibleworld** [comment]
@Neustradamus Yup! There will be both `file-pdf` and `file-png` icons.

**Comment by USP-ITweb** [comment]
Is there an ETA on the fix for this?

**Comment by sensibleworld** [comment]
Hoping to get the release out today.

**Comment by sensibleworld** [comment]
This has been fixed in 6.5.1

**Comment by Neustradamus** [comment]
@sensibleworld: Thanks!
- https://fontawesome.com/icons/file-pdf
- https://fontawesome.com/icons/file-png
