### ISSUE TITLE
Icon Request: fa-icon-mastodon

### ISSUE THREAD

**Issue by dbourrion** [FortAwesome/Font-Awesome#20014]
Hi
An Mastodon icon would be nice https://joinmastodon.org/fr

Here's their logo (joined)
![Mastodon](https://github.com/FortAwesome/Font-Awesome/assets/400398/74261bdf-eaf0-4d1e-9b72-7cb009b852a9)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

mastodon icon has been added to FontAwesome in version 5.0.11 and updated in 5.8.0:
- https://fontawesome.com/icons/mastodon?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
