### ISSUE TITLE
The file-pdf icons are PNG

### ISSUE THREAD

**Issue by dlcohengithub** [FortAwesome/Font-Awesome#20021]
Look at the PDF icons. They all have 'PNG' showing, even tho they are file-pdf

**Comment by Bamuel** [comment]
Amazing Typo, Hopefully it gets fixed soon.

https://fontawesome.com/v6/icons/file-pdf?f=classic&s=regular
![image](https://github.com/FortAwesome/Font-Awesome/assets/6744113/a7d26424-8f4c-4cc8-b6a4-d70bb91ffbca)

**Comment by tagliala** [comment]
Thanks for the report, I've assigned @sensibleworld

**Comment by tagliala** [comment]
Duplicate of #20017

**Comment by Neustradamus** [comment]
@sensibleworld: Thanks!
- https://fontawesome.com/icons/file-pdf
- https://fontawesome.com/icons/file-png
