### ISSUE TITLE
Icon request: lab icons: chemical, cell, plasmid

### ISSUE THREAD

**Issue by lyschoening** [FortAwesome/Font-Awesome#2002]
Hi, it would be great if you could add some icons for laboratories, along the lines of what you have done with the medical category. Among the useful lab icons not yet suggested are: `chemical-compound`, `organism` or `cell` for cells/bacteria, and `plasmid` (a circular piece of dna). All of these are very common in genetic labs.

**Comment by blacatena** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by simogrima** [comment]
+1 for this request

**Comment by MVcodeartbr** [comment]
+1

**Comment by ice12192** [comment]
+1

**Comment by gmmarc** [comment]
+1

**Comment by siliond** [comment]
+1

**Comment by luzpaz** [comment]
:+1:

**Comment by arcanoid** [comment]
+1

**Comment by mg1075** [comment]
+1

**Comment by JochLAin** [comment]
+1

**Comment by dridk** [comment]
+1

**Comment by sriadiga** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by labkey-jessim** [comment]
+1

**Comment by sngusti** [comment]
+1

**Comment by kfdg** [comment]
+1

**Comment by blackdrago** [comment]
+1

**Comment by yonist** [comment]
+1

**Comment by andrewcarretta** [comment]
+1

**Comment by knightjdr** [comment]
+1, specifically for the `cell`.

**Comment by m-gallesio** [comment]
Just noticed this on the leaderboard. `cell` is still missing, but in the several years this has been open most of the requested icons have been added to the [medical-health](https://fontawesome.com/icons/categories/medical-health) category.
For reference our application uses `flask` to represent chemicals.

**Comment by Codemaine** [comment]
+1

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=chemical&o=r)
