### ISSUE TITLE
3 brands are marked as "Pro"

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#20024]
> > out of 484 brand icons, signal is now the third pro brand icon
> 
> who are the other two? This should be a bug

Webflow and Shoelace
<img width="430" alt="Screenshot- 2023-11-29 at 09 50 37" src="https://github.com/FortAwesome/Font-Awesome/assets/83089404/65bdf74a-ec37-41fb-9198-e417a5f7254a">

_Originally posted by @scarlachs in https://github.com/FortAwesome/Font-Awesome/issues/7434#issuecomment-1831469039_

**Comment by sensibleworld** [comment]
This has been fixed in 6.5.1
