### ISSUE TITLE
Icon request: wikipedia

### ISSUE THREAD

**Issue by Eejit43** [FortAwesome/Font-Awesome#20020]
Wikipedia is the 10th most popular website in the world, I don't know how there isn't an icon for it already... 

Instead of having the globe logo, I think that the "w" used in the favicon is much more understandable and just as recognizable (seen below)

![image](https://github.com/FortAwesome/Font-Awesome/assets/76887639/94dbb8a4-ff1c-4a4f-b54a-f708f2e90c88)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

wikipedia icon has been added to FontAwesome in version 4.4.0:
- https://fontawesome.com/icons/wikipedia-w?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by Eejit43** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> wikipedia icon has been added to FontAwesome in version 4.4.0:
> 
> * [fontawesome.com/icons/wikipedia-w?f=brands&s=solid](https://fontawesome.com/icons/wikipedia-w?f=brands&s=solid)
> 
> If you have troubles in using or upgrading Font Awesome, please check our documentation
> 
> [fontawesome.com/docs/web/add-icons/how-to](https://fontawesome.com/docs/web/add-icons/how-to)
> 
> Hope it helps
> 
> Closing here, but feel free to comment and provide more information if I didn't get this request

Whoops sorry, not sure how I didn't see that! Thanks!
