### ISSUE TITLE
Bug: go get create zip / cloning repo: case-insensitive file name collision (faTshirt -- faTShirt)

### ISSUE THREAD

**Issue by razonyang** [FortAwesome/Font-Awesome#20023]
### Bug description

Hi, I'm using FontAwesome via Hugo modules, but I found that there is an _case-insensitive file name collision_ issue, which causes download fails. Are the following files are same?

```sh
go get github.com/FortAwesome/Font-Awesome@6.5.0
go: github.com/FortAwesome/Font-Awesome@6.5.0: invalid version: reading https://goproxy.cn/github.com/%21fort%21awesome/%21font-%21awesome/@v/6.5.0.info: 404 Not Found
        server response:
        not found: create zip: free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.d.ts: case-insensitive file name collision: "free/js-packages/@fortawesome/free-solid-svg-icons/faTShirt.d.ts" and "free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.d.ts"
        free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.js: case-insensitive file name collision: "free/js-packages/@fortawesome/free-solid-svg-icons/faTShirt.js" and "free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.js"
```

![image](https://github.com/FortAwesome/Font-Awesome/assets/17720932/65ac5527-e200-45a3-b811-181a6a4639e2)

### Font Awesome version

v6.5.0

### Application and Operating System

- Windows WSL2
- Hugo (Go) Modules

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
I can confirm this issue by cloning the repo on my local machine

macOS reports a diff and unstashable changes:

```
--- a/free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.d.ts
+++ b/free/js-packages/@fortawesome/free-solid-svg-icons/faTshirt.d.ts
@@ -1,6 +1,6 @@
```

**Comment by robmadole** [comment]
Alright, I've got this resolved. I'll update our build system so that we don't duplicate this in the future.
