### ISSUE TITLE
Brand request: Updated Reddit branding

### ISSUE THREAD

**Issue by grantmcconnaughey** [FortAwesome/Font-Awesome#20026]
### Description

A few hours ago, Reddit unveiled their updated branding, including a new Reddit alien logo. This request is to update the `reddit` and `reddit-alien` icons to incorporate this new design.

### Official website

https://reddit.com

### Brand guidelines

https://www.redditinc.com/brand

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads up.

Official svg resources are available at https://reddit.lingoapp.com/s/d9x3n2/?v=18

As far as I can tell,

- reddit: `Reddit_Icon_2Color`
- reddit-alien: `Reddit_Icon_1Color_Silhouette`
- square-reddit: `Reddit_Icon_2Color_FullBleed` (with rounded borders to match all other square icons)

**Comment by sensibleworld** [comment]
Updated in 6.5.1
