### ISSUE TITLE
Icon request: fa-developer-procedure

### ISSUE THREAD

**Issue by jehaw** [FortAwesome/Font-Awesome#20027]
We have an icon for functions, fa-function, but none for its counterpart, procedures.  While the fa-function icon is normally used in math, it can also be used to represent functions for software/database development.

This is especially handy when working with databases (in my case MySQL/Maria) where I would like to indicate an entry as either a procedure or function, but I am sure there are hundreds of other uses out there for development teams.

The name suggested is only because there is a fa-procedures, but that icon has to do with medical procedures, not software development.

Thanks for the consideration.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

In our new [Icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&projects=&template=000_icon_request.yml&title=Icon+request%3A+) we ask for concrete objects and examples, because "developer procedure" is abstract and so it is "hard to implement"

Do you have any example (single color, suitable for 16px icon size) of how a developer procedure should look like?

**Comment by jehaw** [comment]
Hi,

 

Thanks for the reply, attached is an example of what I mean.

 

The bottom line uses something similar to the fa-function icon currently available in the pack.

The top line is what I am proposing. It is similar to the function but has a P instead of an F.

 

Most Relational Databases support the use of stored functions and procedures. While developing interfaces that support database use (normally at admin level), having a procedure icon would help immensely. Currently I have to rely on actual jpgs for the symbols, the fa-function icon works well but without its counterpart, the presentation is off.

 

On the by, I only posted the suggestion in Git where it is at based on the links provided in fontawesome.com:

 

https://fontawesome.com/support#requesting-icons

 

Thanks for sending the link to the actual suggestion page, if you wish I can reapply my request.

 

Have a great day!

 

Jim Hawley  

jeHaw Webdesign

  

Hauptstr. 40

92237 Sulzbach-Rosenberg

  

Tel: +49 (0)9661 879 9020

Fax: +49 (0)9661 879 9011

Impressum:  <https://www.jehaw.de/impressum/> https://www.jehaw.de/impressum/

Datenschutz:  <https://www.jehaw.de/datenschutz/> https://www.jehaw.de/datenschutz/  

  

Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese eMail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

 

Pflichtinformationen gemäß Artikel 13 DSGVO Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z. B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. Details entnehmen Sie unserer Datenschutzerklärung ( <https://www.jehaw.de/datenschutz/> https://www.jehaw.de/datenschutz/).

**Comment by tagliala** [comment]
Please go to https://github.com/FortAwesome/Font-Awesome/issues/20027 and use the website, email attachments don't work

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, we may already have similar icons, or its just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
