### ISSUE TITLE
Icon request: restroom-non-binary 

### ISSUE THREAD

**Issue by jaredg4** [FortAwesome/Font-Awesome#20035]
Would be great to have a version of "restroom" and "restroom-simple" that is non gendered ie. no dress, two people in pants

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/people-pants-simple?f=classic&s=solid
https://fontawesome.com/icons/people-dress-simple?f=classic&s=solid
https://fontawesome.com/icons/people-pants?f=classic&s=solid
https://fontawesome.com/icons/people-dress?f=classic&s=solid
