### ISSUE TITLE
Brand request: nextdoor

### ISSUE THREAD

**Issue by seattledeveloper** [FortAwesome/Font-Awesome#20036]
### Description

I am creating a new request as the title of the current request for a nextdoor icon (#3928) is an Icon Request and I am creating a Brand Request, hoping it gets some action.  It looks like the current request has been around since 2014, with a number of people asking when it will be added.

### Official website

https://nextdoor.com/

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please use #3928, it is a proper request. At the time we didn't have contributing guidelines and templates

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here
