### ISSUE TITLE
Icon request: bluesky

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#20046]
bluesky or bsky.app or fa-bluesky 

brand icon for https://bsky.app/ which is a microblogging social platform and public benefit company. 

(i am **not** affiliated with the brand, i just want to upload their official icon)  

official icon url

https://raw.githubusercontent.com/bluesky-social/social-app/d59340017860c9d2ec9f4927b329a9c14dc6f7f7/assets/icon-android-foreground.png

 github link to official icon
https://github.com/bluesky-social/social-app/commit/d59340017860c9d2ec9f4927b329a9c14dc6f7f7

**Comment by pfrazee** [comment]
svg

![logo-black](https://github.com/FortAwesome/Font-Awesome/assets/1270099/a35da02a-846f-4e12-acfa-b03ea96ec882)

**Comment by stephenyeargin** [comment]
Probably good to add to #19810 as a parent ticket.

**Comment by aethior** [comment]
> Probably good to add to #19810 as a parent ticket.

cc @tagliala

**Comment by tagliala** [comment]
Duplicate of #19810?
