### ISSUE TITLE
Bug: angle-down icon not vertically centered

### ISSUE THREAD

**Issue by corymharper** [FortAwesome/Font-Awesome#20047]
### Bug description

Here are separate Stackblitz apps to see the difference:

[6.2.1](https://stackblitz-starters-cuyzxd.stackblitz.io)  
[6.3.0](https://stackblitz-starters-nwchet.stackblitz.io)  
[6.5.1](https://stackblitz-starters-amjrnx.stackblitz.io)  

It appears that since `6.3.0` the `angle-down` icon has not been vertically centered. I don't think this was a purposeful change, at least it is not mentioned in any changelog, and there is a changelog entry for `6.4.0`:

> Fixed a regression in 6.3.0 where a number of icons weren't centered properly in their viewboxes.

I think this might be left over from that regression, but I can't be sure.

### Reproducible test case

https://stackblitz.com/edit/stackblitz-starters-amjrnx?file=src%2FApp.tsx

### Screenshots

| Before  | After |
| ------------- | ------------- |
| <img width="141" alt="Screenshot 2023-12-14 at 12 57 45 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/42228018/adb27c3d-0239-4719-9c42-7b399d246dca">  | <img width="141" alt="Screenshot 2023-12-14 at 12 58 04 PM" src="https://github.com/FortAwesome/Font-Awesome/assets/42228018/1267e01d-1eb2-4c1f-aec3-84b2fc3c8205"> |

### Font Awesome version

6.3.0+

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

Chrome 120.0.6099.109  
macOS 14.1.2

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by corymharper** [comment]
Hi, just checking up on the status of this issue, if anyone has looked into it just yet?

**Comment by sensibleworld** [comment]
Thanks for the report! I'll get this fixed in the next release.

**Comment by sensibleworld** [comment]
This has been fixed in the 6.5.2 release (neglected to add it to the release notes)
