### ISSUE TITLE
Bug: Cloning this repo throws an 'colliding paths' warning

### ISSUE THREAD

**Issue by evertharmeling** [FortAwesome/Font-Awesome#20040]
### Bug description

When cloning this repo on a Mac throws the following warning/error:

```bash
git clone git@github.com:FortAwesome/Font-Awesome.git
Cloning into 'Font-Awesome'...
remote: Enumerating objects: 82074, done.
remote: Counting objects: 100% (6565/6565), done.
remote: Compressing objects: 100% (1788/1788), done.
remote: Total 82074 (delta 4828), reused 6452 (delta 4773), pack-reused 75509
Receiving objects: 100% (82074/82074), 116.04 MiB | 13.25 MiB/s, done.
Resolving deltas: 100% (60874/60874), done.
Updating files: 100% (9755/9755), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'js-packages/@fortawesome/free-solid-svg-icons/faTShirt.d.ts'
  'js-packages/@fortawesome/free-solid-svg-icons/faTshirt.d.ts'
  'js-packages/@fortawesome/free-solid-svg-icons/faTShirt.js'
  'js-packages/@fortawesome/free-solid-svg-icons/faTshirt.js'
```

[GitHub](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome/free-solid-svg-icons) only display the first 1.000 items online, so it's not viewable online.

> Sorry, we had to truncate this directory to 1,000 files. 2,907 entries were omitted from the list. Latest commit info may be omitted.

On the (macOS) filesystem the only visible files are:
- `faTShirt.d.ts`
- `faTShirt.js`

This is in line with the names of the rest of the icons. 

Probably Git still holds the lowercase version of the files and they should be removed (and any reference to it).

### Font Awesome version

6.x

### Application and Operating System

- Git: `2.43.0`
- macOS: `12.7.1 Monterey`

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Thanks, this has been already reported here: #20023

The title is different but it's the same issue, let's use the other one

**Comment by evertharmeling** [comment]
Right, my bad!
