### ISSUE TITLE
Feature request: sun, sunset and sunrise icons look like a gear wheel and should be adjusted

### ISSUE THREAD

**Issue by andybandy89** [FortAwesome/Font-Awesome#20050]
### Is your feature request related to a problem?

We wanted to use sun, sunset and sunrise icons in an application but they are confusing. They sun looks more like a gear wheel than a sun. 

### Feature description

Would it be possible to adjust these icons so that the sun is more clearly recognizable?

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Thank you for the feedback. We'll take it into consideration as we work through our next version.
