### ISSUE TITLE
Icon request: Brand Venmo, Brand Zelle

### ISSUE THREAD

**Issue by nickpoulos** [FortAwesome/Font-Awesome#20078]
It would be nice to have Venmo and Zelle icons in the FA library.  They are widely used payment processors.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Zelle is a duplicate of #14687, please add a 👍 reaction to that request.
Venmo is a duplicate of #4659, please add a 👍 reaction to that request.

You can [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones. If you searched before, maybe search did not work.

You may also be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

Another useful resource is our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new)

Closing here
