### ISSUE TITLE
Icon Request: icon-helicopter

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2007]
Our agency is developing a registration application for the medical center of the University of Amsterdam. Operations can be executed with an ambulance (http://fortawesome.github.io/Font-Awesome/icon/ambulance/) as well as with a helicopter. Currently the missing icon-helicopter hinders us from switching from Fam Fam Fam to Font Awesome. Attached you can find the helicopter icon we're using at present.

![helicopter_2](https://f.cloud.github.com/assets/3323396/1191140/7f63d2fc-2449-11e3-8d5e-52823fb87de3.png)

**Comment by bfvww2** [comment]
+1

**Comment by tcs-rliess** [comment]
+1

**Comment by xibriz** [comment]
+1

**Comment by timurgen** [comment]
+1

**Comment by Blizzard75** [comment]
+1

**Comment by eebahoo** [comment]
+1
I especially like the idea of top down spinning rotors: http://jsfiddle.net/omd0uk4m/

**Comment by sekatif** [comment]
+1

**Comment by Panchosama** [comment]
+1
I work into a helicopter company, so this icon should be very useful!!

**Comment by gelso1** [comment]
+1
I need icon for new site of helicopter company. 
![elicona](https://cloud.githubusercontent.com/assets/13882486/9377364/94898426-4718-11e5-814f-3fe24a298420.jpg)

**Comment by CitySim** [comment]
+1

**Comment by trietz** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by rafaelveggi** [comment]
+1

**Comment by pimmey** [comment]
+1

**Comment by Nachbarshund** [comment]
+1

**Comment by mpneuried** [comment]
+1

**Comment by exinferis** [comment]
+1

**Comment by shaedrich** [comment]
+ 1

**Comment by killr0x33d** [comment]
+1

**Comment by davherrmann** [comment]
+1

**Comment by a-ivanov81** [comment]
+1

**Comment by tcs-rliess** [comment]
+1

**Comment by echobravo1** [comment]
+1 thanks

**Comment by amrocs** [comment]
+1

**Comment by DaSchTour** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by spydmobile** [comment]
+1

**Comment by Zaanmedia** [comment]
+1

**Comment by syamsulalam** [comment]
+1

**Comment by Dan-Q** [comment]
+1 Side-on looks more instantly-recognisable as a helicopter, to me.

**Comment by guanzo** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by apt763** [comment]
+1 for both

**Comment by federicogodan** [comment]
+1

**Comment by cmdrkeene** [comment]
+1

**Comment by atoohill** [comment]
+1

**Comment by andrewsaad** [comment]
+1

**Comment by rioadrian** [comment]
+1

**Comment by inakineitor** [comment]
+1

**Comment by spydmobile** [comment]
+1 for top down Helicopter, small aircraft and large aircraft

**Comment by richfergus** [comment]
+1, please

**Comment by shaedrich** [comment]
Maybe something like this: https://commons.wikimedia.org/wiki/File:Helico_silhouette.svg

**Comment by normannspost** [comment]
+1, please :-)

Something in the same style as the current "plane icon" but showing a helicopter instead:

![screen shot 2017-09-28 at 10 14 53](https://user-images.githubusercontent.com/6000518/30956588-1b3d2ee0-a438-11e7-9c4e-9f09653f15fd.png)

**Comment by sensibleworld** [comment]
Released! https://fontawesome.com/icons?d=gallery&q=helicopter

**Comment by sensibleworld** [comment]
@spydmobile Original request was for a side-view. Can you open another request for top-down?

**Comment by anarchodin** [comment]
Since plane, fighter-jet and space-shuttle are all top-down, it seems to make sense for the "unadorned" helicopter icon also to be a top-down view.
