### ISSUE TITLE
Icon request: Newtab

### ISSUE THREAD

**Issue by ArfanAtaee** [FortAwesome/Font-Awesome#20089]
Kind of like the Google Chromes Newtab.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Both Chrome and Firefox uses a `plus` to symbolize "New tabs":
<img width="101" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/35e62d1e-e3b9-41be-b16c-27e8e4340dbe"> <img width="67" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/556268/23162ade-50be-4d33-b307-a4676714f5c3">


Do you have something different in mind?

If you have, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and provide an example
