### ISSUE TITLE
Bug: Wrong icon displayed/No icon displayed

### ISSUE THREAD

**Issue by ekaeoq** [FortAwesome/Font-Awesome#20092]
### Bug description

**Case 1: Wrong icon displayed**
```html
        <div className="element_item2">
          <div>
            <button
              className="button_login_logout_app_bar"
              onClick={() => void (async () => await auth?.login())()}
            >
              <span className="button_login_logout_app_bar__text">Login</span>
              <i className="fa-solid fa-user"></i>
            </button>
          </div>
          <div>
            <button
              className="button_login_logout_app_bar"
              onClick={() => void (async () => await auth?.logout?.())()}
            >
              <span className="button_login_logout_app_bar__text">Logout</span>
              <i className="fas fa-sign-out-alt"></i>
            </button>
          </div>
        </div>
```
Talking about these two icons:
```<i className="fas fa-sign-out-alt"></i>```,
```<i className="fas fa-sign-out-alt"></i>```
This code produces this: 
<img width="207" alt="Screenshot 2024-01-30 at 21 10 27" src="https://github.com/FortAwesome/Font-Awesome/assets/46292172/2535aa27-f907-4292-a08b-287de461f818">
and this:
<img width="78" alt="Screenshot 2024-01-30 at 21 10 37" src="https://github.com/FortAwesome/Font-Awesome/assets/46292172/ebcbb069-6401-472d-ae7e-e8dbcda75abc">

**Case 2: No icon displayed**
I've also tried using this icon: ```<i class="fa-solid fa-circle-user"></i>```, but in that case, no icon at all is displayed: 
<img width="210" alt="Screenshot 2024-01-30 at 21 08 33" src="https://github.com/FortAwesome/Font-Awesome/assets/46292172/547cf09c-737b-42ae-b51b-9774346a083d">

### Reproducible test case

https://login.lpm.feri.um.si

### Font Awesome version

5.15.3

### Serving

Kit, Other (as specified in the bug description)

### Implementation

CSS

### Browser and Operating System

-Version 17.0 Safari MacOS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please notice that your application is loading FA 5 but the markup is using FA 6 syntax (`fa-solid`)

Just upgrade to FA 6 or change the syntax accordingly

> I've also tried using this icon: `<i class="fa-solid fa-circle-user"></i>`, but in that case, no icon at all is displayed:

FA5 syntax would be: `<i class="fas fa-user-circle"></i>`

Hope it helps

Closing here but feel free to comment

FA6 Docs: https://fontawesome.com/docs
FA5 Docs: https://fontawesome.com/v5/docs

**Comment by ekaeoq** [comment]
Thank you! Fixed, great response time as well
