### ISSUE TITLE
Icon request: Punch Machine icon ( or ) Attendance

### ISSUE THREAD

**Issue by chellaack** [FortAwesome/Font-Awesome#20094]
### Use case

To record attendance of employee

### Example image

![attendance](https://github.com/FortAwesome/Font-Awesome/assets/101007499/ebd64af3-5321-42c8-9e87-66c50ab3b06f)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Could you please clarify this request?

Is this a request for `calendar-clock`? https://fontawesome.com/icons/calendar-clock?f=classic&s=solid

**Comment by chellaack** [comment]
@tagliala Thanks
