### ISSUE TITLE
Missing comma in the code example

### ISSUE THREAD

**Issue by nmizrahi2** [FortAwesome/Font-Awesome#20096]
Hi, 
The React dynamic pencil icon example has a missing comma [after the `family` attribute]
https://fontawesome.com/icons/pencil?f=classic&s=solid

instead of `<FontAwesomeIcon icon={icon({name: 'pencil', family: 'classic' style: 'solid'})} />`
It should be `<FontAwesomeIcon icon={icon({name: 'pencil', family: 'classic', style: 'solid'})} />`

**Comment by amarjit0786** [comment]
can i work on this issues????

**Comment by tagliala** [comment]
thanks for your willing to help but unfortunately not, it is not possible to work on this issue because the documentation is generated from a private repository

**Comment by amarjit0786** [comment]
> thanks for your willing to help but unfortunately not, it is not possible to work on this issue because the documentation is generated from a private repository

ok sir 😊

**Comment by robmadole** [comment]
We've fixed this by removing the "Dynamic Import" option. That approach is deprecated now.
