### ISSUE TITLE
Icon Request: Rod of Asclepius

### ISSUE THREAD

**Issue by LDigital84** [FortAwesome/Font-Awesome#2009]
The Rod of Asclepius would be great to have in medical icons as it is used as a symbol of medicine and health care. The screenshot below is from Wikipedia and can be cleaned up a lot. Note: The Rod of Asclepius is often confused with the Caduceus which is the sign for commerce. 

![rod_of_asclepius](https://f.cloud.github.com/assets/1938824/1188833/243e4612-23ec-11e3-9685-7f09424faf2e.png)

**Comment by RevanProdigalKnight** [comment]
+1

**Comment by Veritas1000** [comment]
+1

**Comment by Hirbod** [comment]
+1

**Comment by solace** [comment]
+1

**Comment by barlowm** [comment]
+1

**Comment by drtrppr** [comment]
+1

[https://nl.wikipedia.org/wiki/Cholesterol](url)

[https://nl.wikipedia.org/wiki/Cholesterol#/media/File:Esculaap4.svg](url)

**Comment by jsdmind** [comment]
+1

**Comment by Toron-Isil** [comment]
+1 may with different versions like "Bowl of Hygieia", snake and a bowl above.
    Not to be confused with caduceus - the wand or staff of hermes ;)

**Comment by UravityChan** [comment]
![Staff_of_Aesculapius](https://user-images.githubusercontent.com/42383597/92398526-051d9780-f129-11ea-8f8a-ba7c6b067b43.PNG)

It would be also great to have different versions of it, since many people have different associations with it.

**Comment by jfagner** [comment]
+1 I work at a university and would use this icon often for medical links/content

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/staff-aesculapius?s=solid
