### ISSUE TITLE
Missing definitions in the Customize with CSS Custom Properties page

### ISSUE THREAD

**Issue by thekingofspain** [FortAwesome/Font-Awesome#20097]
In the [Customize with CSS Custom Properties](https://fontawesome.com/docs/web/style/custom#customize-with-css-custom-properties) page, not all FontAwesome properties are listed.  In particular there are 14 CSS variables listed in the [Animating Icons](https://fontawesome.com/docs/web/style/animate/) section, but the [Animating Icons](https://fontawesome.com/docs/web/style/animate) page lists 21.  

Note on induvial pages that detail a feature using CSS Variables, the "Accepted Values" are not always specified in the individual CSS Variable definition.  The Customize with CSS Custom Properties page, each CSS Variable definition listed, has an "Accepted Values" definition.  

Thus when trying to a missing CSS Variable with an uncommon HTML property name concept like _--fa-bounce-rebound_, its unclear what types values can be used from the available documentation.

**Comment by VDXD** [comment]
can you please explain it more clearly

**Comment by tagliala** [comment]
I understand that the page at [Customize with CSS Custom Properties](https://fontawesome.com/docs/web/style/custom#customize-with-css-custom-properties) does not contain all CSS variables listed at [Animating Icons](https://fontawesome.com/docs/web/style/animate/), like `--fa-bounce-rebound`

**Comment by robmadole** [comment]
@ej2 is going to look at this and see what needs to be done. Thanks for the report @thekingofspain

**Comment by robmadole** [comment]
I believe we have this resolved now.
