### ISSUE TITLE
Icon-Info-Sign truncated on Chrome/Win7

### ISSUE THREAD

**Issue by kenperkins** [FortAwesome/Font-Awesome#201]
I get the **icon-info-sign** truncated on Win7 + chrome:

 ![Truncated icon-info-sign](http://dl.dropbox.com/u/17340858/icon-info-sign-chrome-windows.png)

Chrome 19.0.1084.46 (latest)

**Comment by kaansoral** [comment]
Sorry for haunting this issue, but I decided to put this piece of information here too, as I found this issue from google as I was trying to solve icon truncation issues

Adding opacity to icons causes them to render in a truncated form in Chrome and webkit browsers, so if anyone else experiences this issue again, opacity might be to blame
