### ISSUE TITLE
Icon request: icon-kids

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2010]
Hi,
We have icon-female and icon-male but no icon-kids in fontawesome.
It could be use for exemple in sites where theres is things for both adults and kids, like books, clothes, articles etc.

Should be something like in the attached image.

Thanks !
![kids-icon](https://f.cloud.github.com/assets/2845245/1190571/4f6fea6a-2438-11e3-83d3-891daa658b1b.png)

**Comment by bruclik** [comment]
+1

**Comment by amlette** [comment]
+1

**Comment by gustavohellwig** [comment]
+1

**Comment by lorenzodetomasi** [comment]
+1

**Comment by SoerenHenning** [comment]
+1

**Comment by tonypee** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/children?s=solid
