### ISSUE TITLE
Bug: Web font fa-toolbox is blurry at 16px

### ISSUE THREAD

**Issue by SuperPat45** [FortAwesome/Font-Awesome#20106]
### Bug description

Web Font icon fa-solid fa-toolbox is blurry at 16px

It appears better at 15px or 17px

Other icons are OK

### Reproducible test case

https://jsfiddle.net/Lx8o9nk0/

### Screenshots

![image](https://github.com/FortAwesome/Font-Awesome/assets/7791600/580f48ea-3412-49ba-9790-ba8d4584aebd)

### Font Awesome version

v6.5.1

### Serving

Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

Firefox 112

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Fixed fiddle: https://jsfiddle.net/tagliala/jog43p9k/1/

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this issue.

Confirmed, it looks blurry on low dpi resolutions:
![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/09707660-e75b-43a6-896c-d2d0e6a18103)


Assigning @sensibleworld

**Comment by sensibleworld** [comment]
This should now be fixed in 6.5.2: https://fontawesome.com/icons/toolbox?f=classic&s=solid
