### ISSUE TITLE
Are there icons missing from the metadata?

### ISSUE THREAD

**Issue by Hedva** [FortAwesome/Font-Awesome#20108]
It seems icons are missing from the metadata:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/metadata/icons.json
https://github.com/FortAwesome/Font-Awesome/tree/6.x/metadata

I can't find:
- sack - f81c
- chart-mixed - f643
- chart-mixed-up-circle-dollar - e5d9
- chart-line-up-down - e5d7

and many more.

Is there a reason some icons do not appear in the metadata files?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Maybe the Pro icons are missing?

**Comment by Hedva** [comment]
I just found out that the online metadata doesn't contain de pro icons, but the json/yml from the personal Kit does contain them.

I got really confused because it didn't occure to me that the GitHub version only contains the free icons.
