### ISSUE TITLE
Custom Icons in Angular Projekt.

### ISSUE THREAD

**Issue by marco-hasler-cyrotech** [FortAwesome/Font-Awesome#20111]
Hello, 

I use font-awesome custom icons together with Angular.

When using it, I have the problem that the custom folder of my project is not exported correctly. 

The following has been tested in a new Angular 17 project.

1. created new project
2. installed @fortawesome/angular-fontawesome
3. added .npmrc file
4. changed to SVG under Settings on the website under Technology.
5. npm install --save @awesome.me/xxxx
6. npm update @awesome.me/xxxx
7. used custom icon in template with <fa-icon [icon]="faCustomIconName"></fa-icon>

This procedure has triggered the following error.

![image](https://github.com/FortAwesome/Font-Awesome/assets/159889152/f5dfe7c6-1841-4809-8b28-79c210d4e90b)
An unhandled exception occurred: Missing "./icons/modules/kit/custom" specifier in "@awesome.me/kit-XXXXXX"

![image](https://github.com/FortAwesome/Font-Awesome/assets/159889152/a0dcec25-f7ed-44bd-a865-1ff363ec512e)

The error disappears when I change the path in the file node_modules/@awesome.me/kit-XXXX/package.json from "./icons/kit/custom" to ""./icons/modules/kit/custom".

Thanks for your great work

Attachments:

**node_modules/@awesome.me/kit-XXXX/package.json**

Not working:
```
"./icons/kit/custom": {
      "types": "./icons/modules/kit/custom.d.ts",
      "import": "./icons/modules/kit/custom.mjs",
      "require": "./icons/modules/kit/custom.js",
      "default": "./icons/modules/kit/custom.js"
    },
``` 
Working:
```
"./icons/modules/kit/custom": {
      "types": "./icons/modules/kit/custom.d.ts",
      "import": "./icons/modules/kit/custom.mjs",
      "require": "./icons/modules/kit/custom.js",
      "default": "./icons/modules/kit/custom.js"
    },
``` 

-------

Package.json

```
{
  "name": "fa-custom-icon-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",
    "@awesome.me/kit-XXXXXXX": "^1.0.16",
    "@fortawesome/angular-fontawesome": "^0.14.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.5",
    "@angular/cli": "^17.0.5",
    "@angular/compiler-cli": "^17.0.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  }
}

```

**Comment by robmadole** [comment]
Hey @marco-hasler-cyrotech. The Kit Package uses the newer `exports` specifier in `package.json` so you'll need to update you tsconfig.json to set `moduleResolution: 'node16'` in order to tell TS to resolve modules using `exports`. Can you give this a try and let me know if that doesn't fix things for you.

**Comment by vandres** [comment]
@marco-hasler-cyrotech Did you get it to work?

**Comment by shinyuna** [comment]
> Hey @marco-hasler-cyrotech. The Kit Package uses the newer `exports` specifier in `package.json` so you'll need to update you tsconfig.json to set `moduleResolution: 'node16'` in order to tell TS to resolve modules using `exports`. Can you give this a try and let me know if that doesn't fix things for you.

For this to be possible, do I need to use TypeScript version 5.4.2 or higher?
