### ISSUE TITLE
New issue Icon request: icon-flatscan

### ISSUE THREAD

**Issue by ullyssess** [FortAwesome/Font-Awesome#2011]
There would be nice to have a flatbed scanner as an icon.
https://www.google.pl/search?q=flatbed+scanner+icon&safe=off&rlz=1C5CHFA_enPL528PL528&tbm=isch&tbo=u&source=univ&sa=X&ei=8RhAUt7cFoLetAaqjIHwAQ&ved=0CC4QsAQ&biw=1344&bih=660&dpr=2

**Comment by tagliala** [comment]
Let's use #5985, it is a duplicate with many more upvotes
