### ISSUE TITLE
Bug: fa-x-twitter doesn't render properly

### ISSUE THREAD

**Issue by ifraixedes** [FortAwesome/Font-Awesome#20139]
### Bug description

I have a website that uses Font Awesome 6.5.1 and at the bottom, I'm using a few brand icons, however, the `fa-x-twitter` doesn't render correctly while the rest does.

The site is hosted on https://siliconguilleries.com and uses the old Twitter logo (i.e. `fa-twitter`). If you open the web developer tools in the browser and change the class from `fa-twitter` to `fa-x-twitter` you should see the same result as the attached screenshot

### Screenshots

![fontawesome-x-twitter](https://github.com/FortAwesome/Font-Awesome/assets/1731633/c92cd4f6-1566-43e2-b4f8-59cb6668c321)

### Font Awesome version

v6.5.1

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Linux
- Brave. Version 1.63.162 Chromium: 122.0.6261.69 (Official Build) (64-bit)
- Firefox 123.0 (64-bit)

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please make sure to upgrade also the `/webfonts` folder together with CSS. It appears that they are still at 6.2.1

https://siliconguilleries.com/webfonts/fa-brands-400.woff2

![image](https://github.com/FortAwesome/Font-Awesome/assets/556268/a65a70dd-7c18-4e57-948c-cc720d301ee3)

Docs: https://fontawesome.com/docs/web/setup/host-yourself/webfonts#set-up-with-web-fonts

Hope it helps

Closing here but feel free to comment

**Comment by ifraixedes** [comment]
Thank you @tagliala and my apologies for not having found that was an issue on my side. I tried for a few hours, but I couldn't understand it :pray:

**Comment by tagliala** [comment]
No problem, glad you solved
