### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by Witcher147** [FortAwesome/Font-Awesome#20136]
Hello we need Cosmetics icons like perfume makeup ...
Cosmetics website
thank you

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and make sure to search before for both existing requests and existing icons
