### ISSUE TITLE
Is proxying private packages through Nexus possible?

### ISSUE THREAD

**Issue by estersz** [FortAwesome/Font-Awesome#20147]
I have a Nexus npm proxy type repository set up to proxy our private fontawesome packages.
However npm proxy serves the packages from a path such as `@awesome.me/kit-00000000/-/kit-0000000.tgz`, removing the version from path, as it is not part of npm convention. This causes multiple versions of the same kit attempted to be served from the same URL.
Is it possible to proxy packages through Sonatype Nexus 3?
Thank you!

**Comment by robmadole** [comment]
Hi @estersz . So if you are referring to the `00000000` part in your example that's not the version but the unique token for the Kit. If that's where Nexus is tripping, you might reach out to them and see if they can help. If I've misunderstood let me know.

**Comment by estersz** [comment]
@robmadole Hello, the issue is really the **lack of** version in the package name. I add an example:
This one proxies well: @fortawesome/fontawesome-svg-core/-/fontawesome-svg-core-**1.2.35**.tgz because the version is in the name of the downloaded file, Nexus can store the multiple versions.
Private kits like: @awesome.me/kit-00000000/-/kit-0000000.tgz doesn't have the version in the filename. Nexus downloading a newer or older version overwrites the file, because the filename is the same.

It is common and customary for npm packages to have the version in the filename, so Nexus reasonably, doesn't expect the opposite. Are you planning to follow the same with the private packages?

**Comment by robmadole** [comment]
@estersz oh! I get it. Thank you. That might be an easy fix then.

I'll get that on the list for the next release and see what we can do.

**Comment by robmadole** [comment]
@estersz we've got this fixed now. Give it a go and see if it works.

**Comment by estersz** [comment]
@robmadole Works as expected. Thank you very much for the quick action, I appreciate it!
