### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by TaHawkz** [FortAwesome/Font-Awesome#20158]
newsletter icon please

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

As per #8277, https://fontawesome.com/icons/envelope-open-text?f=classic&s=solid could represent a newsletter

If you have something different in mind, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and provide an example
