### ISSUE TITLE
Icon request: Circle Question Check

### ISSUE THREAD

**Issue by leetskills** [FortAwesome/Font-Awesome#20152]
### Use case

There is already a [circle-exclamation-check](https://fontawesome.com/icons/circle-exclamation-check?f=classic&s=regular), but no such icon for question. I've created SVGs from the existing FA icons, see attached.

### Example image

![fad-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/dfe122ed-a5cc-4508-a6ea-029047011bb4)
![fal-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/03c21b61-d358-4165-af0e-7d996a644b34)
![far-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/c6ab9424-50c0-4312-bffc-60943f7b7805)
![fas-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/b1f1c718-8935-41a1-811d-3e4cf87f6fa5)
![fat-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/9042ca43-bb14-4758-985d-534215585e3f)
![sfal-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/1cef71c2-0b6c-4529-a079-c67e081cd006)
![sfar-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/6b7ca657-3c60-448e-abe7-db630896ec2b)
![sfas-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/b50a4a47-1785-4130-88c4-099c5cfebb6b)
![sfat-circle-question-check](https://github.com/FortAwesome/Font-Awesome/assets/6179889/3dca94c6-70bb-41e4-816b-1cd520252503)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by bchoubert** [comment]
Hi @leetskills ,
I'm a simple user, but I found this in the wizard:

![image](https://github.com/FortAwesome/Font-Awesome/assets/9991093/6a76425f-c6ad-4501-a099-77e2978e5f50)

I still let the FontAwesome team choose to integrate this or not :D

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
