### ISSUE TITLE
Loging in

### ISSUE THREAD

**Issue by rmleroux** [FortAwesome/Font-Awesome#20161]
Hi,
I have tried to login just now, and the system keeps unaccepting my password, even after I have changed it.
Here is the address under which I am registered on Fontawesome: edited
Thank you for looking into this.
Robert

**Comment by tagliala** [comment]
Hello, are you a Pro customer?

In any case, please send an email to hello@fontawesome.com

I'm going to edit the opening post to remove personal information (the email address)

**Comment by robmadole** [comment]
We're having some service interruption right now. Our team is investigating.

**Comment by rmleroux** [comment]
Hi,

Thanks for your quick reply. And yes, I am a Pro customer.

Best

Robert

Le 20 mars 2024 à 10:46, Geremia Taglialatela ***@***.***> a écrit :



Hello, are you a Pro customer?

In any case, please send an email to ***@***.******@***.***>

I'm going to edit the opening post to remove personal information (the email address)

**Comment by robmadole** [comment]
We'll keep status updates here: https://status.fortawesome.com/

**Comment by rmleroux** [comment]
OK, thanks!

Le 20 mars 2024 à 11:08, Rob Madole ***@***.***> a écrit :



We'll keep status updates here: https://status.fortawesome.com/
