### ISSUE TITLE
Icon request: Please add Pakistani Currency Icon PKR

### ISSUE THREAD

**Issue by mrtx99** [FortAwesome/Font-Awesome#20164]
### Use case

The icon will be very useful for developers including me where we have to show currency icons in our applications instead or write in text format, if text format was enough than there will be no Font-Awesome at all. That means Presenting something with icons is really useful, attractive, most important user experience. 

This is my humble request to please Add new icon for Pakistani Currency.  "PKR"

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We already have this icon: https://fontawesome.com/icons/rupee-sign?f=classic&s=solid

If this is not correct, please follow all the conversation at #16651 and provide feedback with official references to what it should be done

Please notice that we are not adding iso3 currency codes at the moment
