### ISSUE TITLE
Bug: Cannot find module or its corresponding type declarations when importing font awesome pro icons

### ISSUE THREAD

**Issue by DevLaka** [FortAwesome/Font-Awesome#20162]
### Bug description

I'm currently working on a React TypeScript project where I initially used Font Awesome free icons. However, I've realized the need to improve the aesthetics by incorporating Font Awesome Pro icons. Transitioning to Font Awesome Pro might not be as straightforward as I initially thought.

I've set up Font Awesome Pro following the documentation provided here:
[Font Awesome Docs](https://docs.fontawesome.com/web/setup/packages)

Here are the steps I followed:

1. Created a Kit Package:
  ```
Icons: pro
  Technology: SVG
  Subset: Auto-subsetting
  Styles: All styles
  Features: Enable NPM download and Enable compatibility with older versions
```

2. Created a .npmrc file in the folder where package.json exists. .nmprc File Contents:

```
@awesome.me:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

```

3. Installed below packages.
```
npm install --save @awesome.me/kit-KIT_CODE@latest
npm i --save @fortawesome/fontawesome-svg-core
npm i --save @awesome.me/kit-KIT_CODE
npm i --save @fortawesome/react-fontawesome@latest
```

4. Attempted to import icons to a React component using the following code:
```
import { faHouse } from '@awesome.me/kit-KIT_CODE/icons/classic/solid'
```

**However, I'm encountering an error stating: "Module '@awesome.me/kit-code/icons/classic/solid/' or its corresponding type declarations cannot be found.**

Also, I noticed that the index.d.ts file in the @awesome.me node module exports an empty object.

### Font Awesome version

v6

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

- Chrome version 122 on Windows 10

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by DevLaka** [comment]
Add "moduleResoluction": "bundler" within the compilerOptions object in the tsconfig.json file like below.

```
    {
      "compilerOptions": {
        "moduleResolution": "bundler"
      },
    }
```

It's disappointing that this isn't mentioned in any Font Awesome documentation.

**Comment by derWebdesigner** [comment]
I am sorry to pull out this issue again, but what if you can't just change the moduleResolution to bundler? When I update it, FontAwesome is working but then my entire Angular project isn't anymore so it's not a real solution...

**Comment by claudio-destro** [comment]
@derWebdesigner how did you solve it? if you solved it 🙈
In my case the need to use `"moduleResolution": "node"` was related to some sonarqube warnings that I honestly don't remember...

**Comment by derWebdesigner** [comment]
@claudio-destro I actually didn't and had to include the entire font. Since it's an app that's installed locally anyway it's not a big deal but I was quite disappointed that I invested so much time just to realize that this is a full blocker for using the kit version which otherwise would have been perfect.
