### ISSUE TITLE
Icon Request: fa-equal icon

### ISSUE THREAD

**Issue by 190680** [FortAwesome/Font-Awesome#20167]
Dear Awesome, please can you add an equal icon to using Font Awesome, version 4.7

https://fontawesome.com/v4/icons/

For LS Retail Web POS

Could you please create icons for the attached images as payments icons, is it possible?

![MADA ](https://github.com/FortAwesome/Font-Awesome/assets/101178865/ee6dd742-2c76-4dd4-8b32-cd0676ee0931)
![GCC ](https://github.com/FortAwesome/Font-Awesome/assets/101178865/9e997587-ca87-4147-8c74-29260147efd1)
![HS](https://github.com/FortAwesome/Font-Awesome/assets/101178865/dbbb8e2b-bc07-47b7-bf8f-267fa5887ce6)
![qlub](https://github.com/FortAwesome/Font-Awesome/assets/101178865/5e943a12-9803-49f6-a382-4b4a5049dac2)

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Equals icon is already here: https://fontawesome.com/icons/equals?f=classic&s=solid

If you want to request something different, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Closing here, but feel free to comment if I've missed something

**Comment by 190680** [comment]
@tagliala thank you for the quick response but unfortunately, it does not work with ls Retail web POS it should be like this: same icons in version 4.7
 
https://fontawesome.com/v4/icon/plus

please see the attached 
![1](https://github.com/FortAwesome/Font-Awesome/assets/101178865/cfc78a65-11a5-4c02-bcbf-39d20dba6b4e)
![2](https://github.com/FortAwesome/Font-Awesome/assets/101178865/035f7a9c-ec08-44b8-90fe-d1839e3665b4)


Thanks.

**Comment by tagliala** [comment]
Hi, sorry but v4 is in EOL, you need to upgrade to v5 (v6 would be better).

If this is related to a third-party library, please ask the developers

**Comment by 190680** [comment]
@tagliala Cleared thank you
