### ISSUE TITLE
"Server Error" link(https://fontawesome.com/v5/docs/web/use-with/wordpress/install-manually#setup-webfont-with-cdn)

### ISSUE THREAD

**Issue by YaSH-sInngH** [FortAwesome/Font-Awesome#20177]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

Where did you get that link? 

I can see the docs migrated to a new endpoint: https://docs.fontawesome.com/v5/web/use-with/wordpress/, but old urls should still resolve to the new

@robmadole could you please take a look?

**Comment by YaSH-sInngH** [comment]
Hello, I came across this link during React.js course while learning React.

**Comment by robmadole** [comment]
We'll take a look. Thanks for letting us know @YaSH-sInngH

**Comment by robmadole** [comment]
@ej2 can you look at this one?

**Comment by ej2** [comment]
Fixed! This turned out to be a missing env var in production.
