### ISSUE TITLE
Icon Request: fa-piggybank

### ISSUE THREAD

**Issue by SoeThinzarMin** [FortAwesome/Font-Awesome#20176]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

piggybank icon has been added to FontAwesome in version 5.0.9:
- https://fontawesome.com/icons/piggy-bank?f=classic&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
