### ISSUE TITLE
Icon Request: Broom

### ISSUE THREAD

**Issue by claviska** [FortAwesome/Font-Awesome#2017]
Can't seem to find a request for this one. A broom would be helpful for things like cleaning/tidying code.

**Comment by juliomalegria** [comment]
+1

**Comment by leandro-freitas-softdevelop** [comment]
+1

**Comment by leandro-freitas-softdevelop** [comment]
https://github.com/tzusman/custom-font-icons

**Comment by tagliala** [comment]
locking here
