### ISSUE TITLE
Icon request: icon-phone-off

### ISSUE THREAD

**Issue by will-e-yams** [FortAwesome/Font-Awesome#2018]
like the `icon-microphone-off`, it would be useful to have a `icon-phone-off` variant that had a line through it. this would function as a **"end call"** button.

i think as a workaround, i will try rotating the phone icon to face down, as if in the cradle of an old, rotary phone

**Comment by sensibleworld** [comment]
Cleaning up some old issues and wanted to let you know that we now have this icon: https://fontawesome.com/icons/phone-slash?style=solid
