### ISSUE TITLE
Bug: The new Bluesky icon doesn't have the "social" tag that Twitter, Facebook and other social brands have

### ISSUE THREAD

**Issue by somethingSTRANGE** [FortAwesome/Font-Awesome#20189]
### Bug description

When entering "social" on the website icon search field, the Facebook, Twitter and a few other brand icons are shown, however the new Bluesky icon is absent.

### Screenshots

![2024-04-10 11꞉03꞉43 chrome](https://github.com/FortAwesome/Font-Awesome/assets/6905832/b12efafe-4f66-4e58-b0b6-859c366bbdc3)

### Font Awesome version

v6.5.2

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Chrome 123.0.6312.106 (Official Build) (64-bit)
Windows 10

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This should now be fixed. https://fontawesome.com/search?q=social&o=r&f=brands
