### ISSUE TITLE
NPM FORTAWESOME PRO INSTALLATION PROBLEM 

### ISSUE THREAD

**Issue by radhakrishnan005** [FortAwesome/Font-Awesome#20188]
Hello,
I have a problem with installing fortawesome Pro package to my project.
Here's the command that I put in terminal: npm install --save @fortawesome/fontawesome-pro
And here's my output:
$ npm install --save @fortawesome/fontawesome-pro
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in: C:\Users\kaart\AppData\Local\npm-cache\_logs\2024-04-10T10_11_24_785Z-debug-0.log

Does anyone know what is the problem here by any chance? I tried to remove settings related to font awesome in .npmrc, but it didn't help.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please take a look at the documentation and at the troubleshooting guide: https://docs.fontawesome.com/web/setup/packages

If there are still issues, as a Pro Customer, you can get in touch with hello@fontawesome.com and ask for dedicated support

Unfortunately there is not much we can do on the free repo issue tracker for this kind of problems

**Comment by robmadole** [comment]
Yep, just send us an email as @tagliala indicated. We'll be glad to help you out there.
