### ISSUE TITLE
Local development of a page when restricting domain in FA6.

### ISSUE THREAD

**Issue by kellertuer** [FortAwesome/Font-Awesome#20181]
Sorry if this looks more like a support question, but I looked quite a while whether there is an easy point for support questions and was not able to.

I backed you a long time ago (checked: 2016) and have been happily using FontAwesome in my small academic profile since. I actually do have the Fontawewome 5 Pro license, but switched to also having a free 6 plan by now.
In the setting I can restrict the domains that are able to load – but I am unsure I should do that. I do test my pages locally, so that would request the page from localhost / a random IP somewhere in Norway. Is that still possible when restricting to certain domains? Otherwise, activating that would not make much sense for me.

**Comment by robmadole** [comment]
Hi @kellertuer . All you need to do is send a request to hello@fontawesome.com to get support.

To answer your question, we recommend that everyone use the domain restrictions for their Kits.

Just enter the domains that you'd like to use your Kit on and you should be good to go.
