### ISSUE TITLE
Icon Request: fa-diploma

### ISSUE THREAD

**Issue by NC0D3** [FortAwesome/Font-Awesome#20199]
The icon is used in some ed
ucational institutions to have a nice look in to the certified scheme
![DiplomadoIcon](https://github.com/FortAwesome/Font-Awesome/assets/65702184/6564c41d-ce04-4af5-8f9a-6a90cdcd8305)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro as [fa-diploma](https://fontawesome.com/icons/diploma?f=classic&s=solid)
or [file-certificate](https://fontawesome.com/icons/file-certificate?f=classic&s=solid)

There is also a request for a horizontal certificate at: #20196

Closing here, but feel free to comment
