### ISSUE TITLE
Icon request: Fire diamond

### ISSUE THREAD

**Issue by thill-workd** [FortAwesome/Font-Awesome#20195]
### Use case

A fire diamond is the symbol used on semi trucks to indicate risks posed by hazardous materials.

We use Font Awesome to put icons on items on a shopping site (such as Rx, snowflake for refrigerated, weight-hanging for heavy, etc). We previously used the "biohazard" icon, but that wasn't right and made customers feel uneasy about the item. 

### Example image

![image](https://github.com/FortAwesome/Font-Awesome/assets/153845608/f8dd6d08-f688-4e40-8c8b-b089086c0467)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by sensibleworld** [comment]
Thanks for the request. This icon (rotated 45º) might work? https://fontawesome.com/icons/border-all?f=sharp&s=solid&rt=45

**Comment by thill-workd** [comment]
Yep, that looks like exactly what I need.. Sorry I missed that. Thank you!
