### ISSUE TITLE
Bug: unused imports in icon-types.ts in kit (urgent/critical)

### ISSUE THREAD

**Issue by rivaridley** [FortAwesome/Font-Awesome#20193]
### Bug description

Hello, there is [an open ticket](https://github.com/FortAwesome/react-fontawesome/issues/557) for this in the `react-fontawesome` repo, but moving here as there has not been a lot of traction in that repo, and this one is a lot more active. 

My team is migrating to use font-awesome kits, and have installed it according to the docs in our react/typescript/vite project. When we build, which includes running `tsc`, we run into the following error. [Other people](https://github.com/FortAwesome/react-fontawesome/issues/557) are reporting running into this issue too:
![image](https://github.com/FortAwesome/Font-Awesome/assets/99371685/cf71fd1a-f17e-48ce-95e7-d5cd4de391fb)

`tsc` flags an error that all imports in the import declaration on line 2 are unused in this file:

`node_modules/@awesome.me/kit_example/icons/modules/icon-types.ts`

_**Can you please remove you unused imports from icon-types.ts and release a fix for this?**_ 

About a month ago this @robmadole said the FA team would try and get this fixed up in the latest release. This doesnt seem to have made it in last week. Any updates on timelines are appreciated.

**Reproducible test case**
Not needed, you can try this yourself and run tsc with linting rules with a font awesome kit installed and you will see you get this error.
If you are not using imports (unused) please remove them. If companies not have proper linting/tsc setup maybe precommit linting or proper config setup it make break build scripts etc.

**Expected behavior**
We should be able to run tsc without haven broken/unused imports in the generated font awesome kit.

### Font Awesome version

latest

### Serving

Kit

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Its a build issue

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by claudio-destro** [comment]
I fell into this issues recently: it is a real blocker. Hope this will be fixed soon
I am using classic command "tsc && vite build"

**Comment by NinjaJake86** [comment]
Same issue here, any ETA on a fix? Cheers

**Comment by claudio-destro** [comment]
for the sake of my mind (or someone else's mind 😀), just apply a patch to your KIT after `npm install`:

```patch
--- node_modules/@awesome.me/kit-XXX/icons/modules/icon-types.ts.orig	2024-05-01 08:07:09
+++ node_modules/@awesome.me/kit-XXX/icons/modules/icon-types.ts	2024-05-01 08:07:17
@@ -1,5 +1,5 @@
 import type { IconDefinition, IconPack } from '@fortawesome/fontawesome-common-types';
-import type { Icon, IconParams } from '@fortawesome/fontawesome-svg-core'
+// import type { Icon, IconParams } from '@fortawesome/fontawesome-svg-core'
 
 export type IconPrefix = 'fast'|'fass'|'fasr'|'fasl'|'fakd'|'fak'|'fad'|'fat'|'fas'|'far'|'fal'|'fab';
 
```

I know this is **really ugly** and a workaround, but at least it lets me build my final application

**Comment by nathandaly** [comment]
![Uploading Screenshot 2024-05-10 at 14.23.43.png…]()

3 months after reporting and it's still an issue in Vite + TS + React + Kits.

**Comment by nathandaly** [comment]
![Screenshot 2024-05-10 at 14 25 31](https://github.com/FortAwesome/Font-Awesome/assets/33258212/3009c229-e95d-4108-bc9a-a5a512ce2dda)

3 months after reporting and it's still an issue in Vite + TS + React + Kits.

**Comment by nathandaly** [comment]
> for the sake of my mind (or someone else's mind 😀), just apply a patch to your KIT after `npm install`:
> 
> ```diff
> --- node_modules/@awesome.me/kit-XXX/icons/modules/icon-types.ts.orig	2024-05-01 08:07:09
> +++ node_modules/@awesome.me/kit-XXX/icons/modules/icon-types.ts	2024-05-01 08:07:17
> @@ -1,5 +1,5 @@
>  import type { IconDefinition, IconPack } from '@fortawesome/fontawesome-common-types';
> -import type { Icon, IconParams } from '@fortawesome/fontawesome-svg-core'
> +// import type { Icon, IconParams } from '@fortawesome/fontawesome-svg-core'
>  
>  export type IconPrefix = 'fast'|'fass'|'fasr'|'fasl'|'fakd'|'fak'|'fad'|'fat'|'fas'|'far'|'fal'|'fab';
>  
> ```
> 
> I know this is **really ugly** and a workaround, but at least it lets me build my final application

You can fix this error by changing/adding this line to your `tsconfig` file:

```
"noUnusedLocals": false,
```

**Comment by claudio-destro** [comment]
> You can fix this error by changing/adding this line to your `tsconfig` file:
> 
> ```
> "noUnusedLocals": false,
> ```

@nathandaly yep that was an option.

However, I don't want to loosen the constraints and allow unused imports or unused variables.

**Comment by claudio-destro** [comment]
not to mention that kits are not free...

**Comment by robmadole** [comment]
Quick update. We're still working on this. We want to make sure it's actually fixed before we release and TypeScript can be _tricky_.

**Comment by lctech-LeoLioa** [comment]
> Quick update. We're still working on this. We want to make sure it's actually fixed before we release and TypeScript can be _tricky_.

any update about this issue ?

**Comment by stream-jdibling** [comment]
my dudes, lets go please. no way it's THAT hard

**Comment by robmadole** [comment]
@lctech-LeoLioa No update yet. We've ran into a tricky little issue that's going to need more testing. It's still on our radar.

@stream-jdibling it's pretty tricky

**Comment by joey-carlisle4** [comment]
Can we get an ETA on this fix?

**Comment by tatwater** [comment]
Checking back in on this!

**Comment by robmadole** [comment]
We've got our fix done finally and merged in. We're testing it through all the use cases (including some here) that everyone has found to make sure we've got them fixed.

So. We're testing. Feeling pretty good at the moment.

**Comment by robmadole** [comment]
Another quick update. Testing looked great (all the issues we've collected look like they are now resolved.) We'll most likely be deploying this week.

**Comment by robmadole** [comment]
Alright everyone! We've got this released and it's available for testing.

You'll need to go into your Kit and make some kind of change that kicks off a package build and publishing. You can add and then remove an icon, or add then remove a style. Both of those should do it.

Let me know what you find, if it fixes things for you, or if there are more questions.

Sorry this one took so long. We learned a LOT about `.tsconfig` files during this.
