### ISSUE TITLE
Bug: Font-Awesome 404 Error

### ISSUE THREAD

**Issue by pixelmaxxing** [FortAwesome/Font-Awesome#20205]
### Bug description

Are the servers down or what is going on? It throws 404 error, also the docs page cannot be accessed it says 404 page not found, so is the server down or is there an issue on my end? We have been using fontawesome on our live project so this is kinda big deal, what's going on? Never happened before.

### Font Awesome version

v6.0.0

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

Browser, webview app ionic

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by MartinMystikJonas** [comment]
Can confirm. Same problem on our projects.

**Comment by taivu** [comment]
same here. entire domain 404's https://kit.fontawesome.com/

**Comment by USP-ITweb** [comment]
Ditto.

**Comment by MartinMystikJonas** [comment]
Incident already shows at status page: https://status.fortawesome.com/

**Comment by Jonydu05** [comment]
Same here

**Comment by EricPaulson** [comment]
For those who can't wait, you can use their CDN following the instructions here: https://fontawesome.com/account/cdn. I was just able to get all of my sites back up and running.

**Comment by tagliala** [comment]
Hi, I think this has been fixed
