### ISSUE TITLE
Icon request:  spa/hottub

### ISSUE THREAD

**Issue by bmasella** [FortAwesome/Font-Awesome#20201]
### Use case

Property amenities in a guest guidebook.

### Example image

![hot-tub-icon-19](https://github.com/FortAwesome/Font-Awesome/assets/91099432/2aa3c226-19c4-4e6d-bd78-f37da798c985)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon `hot-tub-person` has been added to FontAwesome in version 5.1.0:
- https://fontawesome.com/icons/hot-tub?f=classic&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://docs.fontawesome.com/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
