### ISSUE TITLE
Icon request: EVCharger

### ISSUE THREAD

**Issue by bmasella** [FortAwesome/Font-Awesome#20202]
### Use case

Guest amenities guidebook.  Property webpage

### Example image

![icons8-car-charger-48](https://github.com/FortAwesome/Font-Awesome/assets/91099432/8a000ce9-bcb9-43a7-b9a1-c621cc2e0698)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon charging-station has been added to FontAwesome in version 5.2.0:
- https://fontawesome.com/icons/charging-station?f=classic&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://docs.fontawesome.com/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
