### ISSUE TITLE
Bug: Font Awesome Pro Kits Not Validating & Fonts Broken Everywhere - NOT HAPPY

### ISSUE THREAD

**Issue by amberRey** [FortAwesome/Font-Awesome#20208]
### Bug description

We have a $99-year account with you and are using your fonts with Elementor Pro. We have just tried to validate our font awesome kit ID, but it refuses to validate, and the fonts are broken on a live website! To make matters worse, we are using your icons for user interface design on our main menu system on our websites. We pay $99 a year to use these icons, and now we have angry clients calling us and asking why all the icons are broken on their website. Please fix this fast.

### Screenshots

![screenshot-bug-report](https://github.com/FortAwesome/Font-Awesome/assets/46762201/c20d62c6-bba5-4e05-8179-a66e50ed7da3)

### Font Awesome version

v6.5.2

### Serving

Kit

### Implementation

SVG Sprites, Other (as specified in the bug description)

### Browser and Operating System

-Chrome
-Mozilla
-IOS

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hello, apologies for the inconvenience

It is a known issue, please check the status of the issue and be updated at https://status.fortawesome.com/

**Comment by cklenk** [comment]
Same issue here for us, using the Kit option to deliver our icons.

**Comment by EricPaulson** [comment]
To get back up temporarily, try using their CDN following the instructions here: https://fontawesome.com/account/cdn. I was just able to get all of my sites back up and running. It's an old version, but should work for most icons anyway.

**Comment by amberRey** [comment]
It looks like the kits have been fixed. Thank you!
