### ISSUE TITLE
E-mail verification not sent

### ISSUE THREAD

**Issue by TerriToniAX** [FortAwesome/Font-Awesome#20215]
I'm trying to change the e-mail address of my Font Awesome account, but there is no verification mail from Font Awesome to neither the old nor the new e-mail address. I've double and triple checked the new e-mail address and it is indeed correct. I've tried multiple times to no avail, and also checked the junk e-mail.

**Comment by tagliala** [comment]
Can you please send an email to hello@fontawesome.com?

**Comment by tagliala** [comment]
Closing here, but feel free to comment

**Comment by voxsar** [comment]
Same i cannot get a verification, my existing account is deleted and no reason is given
