### ISSUE TITLE
Icon request: icon-name: abacus icon

### ISSUE THREAD

**Issue by zoleikhaJahangiri** [FortAwesome/Font-Awesome#20226]
hello
There is not any abacus icon in collection. I try to use vertical bars but it's not so good for my intention.
Thanks a lot

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon abacus has been added to FontAwesome Pro in version 5.3.0:
- https://fontawesome.com/icons/abacus?f=classic&s=solid

Even if this is not the specific case of abacus (ref: #6414) we have  a section in our documentation explaining why some icons are not part of the free set: https://fontawesome.com/support#why-are-some-highly-requested-icons-not-available-in-font-awesome-free

Hope it helps, closing here but feel free to comment
