### ISSUE TITLE
react individual import bug

### ISSUE THREAD

**Issue by Dreamofheaven** [FortAwesome/Font-Awesome#20224]
Hello!

Please refer to the image below. 
The two names are the same, so it is not possible to use the regular icon when using it in React. 
How can this be resolved?

![스크린샷 2024-05-21 112451](https://github.com/FortAwesome/Font-Awesome/assets/35605637/0fc16b25-55ae-494d-8465-cae8970cc22d)
![스크린샷 2024-05-21 112500](https://github.com/FortAwesome/Font-Awesome/assets/35605637/b3ce1a9d-9def-4cf2-b85a-2e081337b9cf)

**Comment by robmadole** [comment]
@Dreamofheaven check out these docs, bottom of the page.

https://docs.fontawesome.com/apis/javascript/import-icons/#icon-content-encoded-in-javascript-packages

Does that answer your question?

**Comment by Dreamofheaven** [comment]
wow!!!!!!!!!!!!
I resolved it with your help.
Thank you very much!! 
Have a great day!👍
