### ISSUE TITLE
Bug: Safari / ios custom icons not rendering in js include - version 6 

### ISSUE THREAD

**Issue by beestinger72** [FortAwesome/Font-Awesome#20221]
### Bug description

 Safari / ios custom icons not rendering in js include set in version 6 and webfont its happening across all safari browsers since saving our kit 8 days ago all we did was add a new domain nothing else changed either side for 3 years

![Capture PNGaccsasc](https://github.com/FortAwesome/Font-Awesome/assets/129185409/71f60b04-d91b-4069-a3d6-62b43c1b167f)

### Font Awesome version

v6.00

### Serving

Kit, Font Awesome CDN

### Implementation

CSS

### Browser and Operating System

All safari/ios versions

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hi @beestinger72. Please send a message to hello@fontawesome.com and ask for Rob.

In that message, give me your Kit code that you are using and let me do some investigation. Also, if you have a URL that I can get access to that will help speed things up a lot.

I'm going to close this from public view so we don't leak any sensitive data.

**Comment by VARGA-Peter** [comment]
When I load the fonts with my project URL, Safari doesn't show the fonts. Loading it with this URL works.
According to several posts it looks like the integrity attribute should be added to the link. How do I get the value for my project?
