### ISSUE TITLE
Icon Request: fa-xtwitter

### ISSUE THREAD

**Issue by tactics2** [FortAwesome/Font-Awesome#20222]
Need an icon for Twitter's new name (X) as the old twitter icon is no longer valid. Screenshot of an X icon from a website is shown attached.

![Screenshot 2024-05-17 at 6 40 49 PM](https://github.com/FortAwesome/Font-Awesome/assets/7565818/02496efe-70bd-4d27-a039-750980039e83)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon x-twitter has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
