### ISSUE TITLE
Icon request: cube-outline

### ISSUE THREAD

**Issue by dino-f** [FortAwesome/Font-Awesome#20227]
An icon that represents augmented reality, e.g., in a 3D configurator.
![Cube Outline](https://github.com/FortAwesome/Font-Awesome/assets/19948022/99ba584d-bb33-4199-98d0-54e8ac3f5947)

**Comment by jabronus** [comment]
Thanks for requesting an icon! But this is actually a duplicate of #15129 , so I'm closing this one.
