### ISSUE TITLE
Bug: "faXTwitter" is not included in js-packages

### ISSUE THREAD

**Issue by itTkm** [FortAwesome/Font-Awesome#20234]
### Bug description

I know that the `x-twitter` icon has been released in v6.4.2. But `faXTwitter` isn't included in [js-packages/@fortawesome/free-brands-svg-icons](https://github.com/FortAwesome/Font-Awesome/tree/6.x/js-packages/%40fortawesome/free-brands-svg-icons).

### Font Awesome version

v6.5.2

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

- Chrome 120 on macOS 13.6.3

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I can see it here:
- https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/fontawesome-free/svgs/brands/x-twitter.svg
- https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/free-brands-svg-icons/faXTwitter.js

you mean in the downloaded package? via node package manager? do you have a reproducible test case?

**Comment by itTkm** [comment]
I'm sorry.

GitHub said "Sorry, we had to truncate this directory to 1,000 files. 57 entries were omitted from the list. Latest commit info may be omitted," so I mistakenly thought the files were not included because they didn't appear in the list on GitHub.

Additionally, only the version of the `free-brands-svg-icons` npm package remained outdated in my environment, so I couldn't find the files in my environment either.

This issue is a mistake, so I will close it.

**Comment by tagliala** [comment]
No problem, glad you solved
