### ISSUE TITLE
[bug] Desktop font: file-pdf becomes file-png

### ISSUE THREAD

**Issue by megaroeny** [FortAwesome/Font-Awesome#20236]
Hello!

I found a bug with the desktop font when trying to render `file-pdf`, at least inside Figma. It comes out as `file-png` instead. 😄

- I'm using your Font Awesome component from the Figma Community
- I have a Pro account and have the latest version of the desktop font installed
- When you enter `file-pdf` into the _icon-name_ prop, that is when this happens.

Here you can see an example of this:
<img width="324" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/1559447/f23df9db-47bd-4c16-b32d-f2d7fd05439b">

Thanks for the help!

**Comment by sensibleworld** [comment]
Hi there! This was a bug introduced in version 6.5.0 and fixed in version 6.5.1. You'll want to make sure you've first deleted (with Figma closed) the older typeface, and then installed the newer version.

**Comment by megaroeny** [comment]
> Hi there! This was a bug introduced in version 6.5.0 and fixed in version 6.5.1. You'll want to make sure you've first deleted (with Figma closed) the older typeface, and then installed the newer version.

Ah okay! Let me make sure that I have that version installed too. Thanks!

**Comment by megaroeny** [comment]
Confirmed, the PDF icon is there. Thanks!
