### ISSUE TITLE
Icon request: cursor-drag

### ISSUE THREAD

**Issue by SaroGFX** [FortAwesome/Font-Awesome#20235]
Looking for this drag cursor hand.

![Screenshot 2024-05-28 at 17 31 23](https://github.com/FortAwesome/Font-Awesome/assets/3781800/12f2fc2c-6ecb-462e-8428-4e035637fb0c)

**Comment by jabronus** [comment]
Thanks for requesting an icon! But this is actually a duplicate of #17229, so I'm closing this one.
