### ISSUE TITLE
Bug: Module ‘./icons/modules/classic/regular’ Not Found in Package Exports

### ISSUE THREAD

**Issue by Julius-717** [FortAwesome/Font-Awesome#20243]
### Bug description

Hello,

everytime we try to compile we get a bunche of:
`./src/app/app.module.ts:25:0-401 - Error: Module not found: Error: Package path ./icons/modules/classic/regular is not exported from package C:\Users\mobile\node_modules\@awesome.me\kit(see exports field in C:\Users\mobile\node_modules\@awesome.me\kit\package.json)`
and
`Error: src/app/app.module.ts:48:8 - error TS2307: Cannot find module '@awesome.me/kit/icons/modules/classic/regular' or its corresponding type declarations.

48 } from "@awesome.me/kit/icons/modules/classic/regular"`

We always have to modify the node_module package.json from:
`    "./icons/classic/regular": {
      "types": "./icons/modules/classic/regular.d.ts",
      "import": "./icons/modules/classic/regular.mjs",
      "require": "./icons/modules/classic/regular.js",
      "default": "./icons/modules/classic/regular.js"
    },
`
to
`    "./icons/modules/classic/regular": {
      "types": "./icons/modules/classic/regular.d.ts",
      "import": "./icons/modules/classic/regular.mjs",
      "require": "./icons/modules/classic/regular.js",
      "default": "./icons/modules/classic/regular.js"
    },
`

When will the module package.json be fixed? Or is there a way we can fix that?
Thanks a lot

### Font Awesome version

v6.0.0

### Application and Operating System

Ionic/Capacitor native mobile app

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hey there. Check out the docs here and let us know if you still have issues:

https://docs.fontawesome.com/web/dig-deeper/kit-package-api/#typescript

**Comment by Julius-717** [comment]
I did and we still experienced the same issue

**Comment by robmadole** [comment]
Make sure you remove "modules" from your import paths. Please double-check the syntax for that.
