### ISSUE TITLE
Icon Request: fa-x(twitter)

### ISSUE THREAD

**Issue by abhinav937** [FortAwesome/Font-Awesome#20249]
I will be using this for adding my X (formerly Twitter) link in resumes and in other spaces.
![Screenshot 2024-06-13 134156](https://github.com/FortAwesome/Font-Awesome/assets/79394309/47447b16-2a86-4959-8ded-8448c3bea79a)
![twitter_x_new_logo_square_x_icon_256075](https://github.com/FortAwesome/Font-Awesome/assets/79394309/c66c898c-ce45-4251-a668-126432538f6e)

**Comment by TylerMWise** [comment]
You do know it's out........? https://fontawesome.com/icons/x-twitter

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon x-twitter has been added to FontAwesome in version 6.4.2:
- https://fontawesome.com/icons/x-twitter?f=brands&s=solid
- https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
