### ISSUE TITLE
Icon request: icon-microscope 

### ISSUE THREAD

**Issue by meidiyuwn** [FortAwesome/Font-Awesome#20241]
### Use case

Icon microscopes are very useful for websites/blogs related to medical, laboratory and science. I need this icon to apply to the laboratory equipment blog.

### Example image

![Screenshot_8](https://github.com/FortAwesome/Font-Awesome/assets/72545318/89b0c8cb-7a91-4a7e-a2a8-6521517cef3a)

### Icon request checklist

- [X] The title starts with "Icon request: " and is followed by the requested icon name
- [X] This icon does not represent a brand
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The request is for a concrete object, or I've included an example image
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/new#faqs)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

microscope icon has been added to FontAwesome in version 5.20:
- https://fontawesome.com/icons/microscope?f=classic&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
