### ISSUE TITLE
Icon request: fa-magnifying-glass-book

### ISSUE THREAD

**Issue by annelievrielink** [FortAwesome/Font-Awesome#20258]
Hi,

We are specifically looking for an icon combining a magnifying glass with a book, to indicate that information can be looked up in a book. There is a magnifying-glass-document-icon, but this does not really cover the use cases for a book. 

Here are some examples of what we are looking for:
![magnifying glass book](https://github.com/FortAwesome/Font-Awesome/assets/153507046/699e55a1-c411-4a8b-a4db-c4071fd616f9)

**Comment by jabronus** [comment]
Hi there — we’re closing this issue because this icon can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
