### ISSUE TITLE
Feature request: Don't respect "prefers-reduced-motion" for loading spinners

### ISSUE THREAD

**Issue by garethrpratt** [FortAwesome/Font-Awesome#20254]
### Is your feature request related to a problem?

To me, a loading spinner that does not spin looks like it's frozen/broken.

### Feature description

It would be great if it were possible to add a loading icon that spins even if the user prefers reduced motion. Perhaps just allow the "spin" animation.

My machine had reduced motion set by default (windows 11).

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We would like to preserve this behaviour for users that deliberately enabled that feature for accessibility reasons.

If you want to force the animation, please use a custom css rule

Ref: https://github.com/FortAwesome/Font-Awesome/issues/18713#issuecomment-1044611186

> My machine had reduced motion set by default (windows 11).

Sorry, I also have Windows 11 and I think this is not a default setting. If someone else can confirm

/cc @robmadole 

Closing here, but feel free to comment
