### ISSUE TITLE
Ql

### ISSUE THREAD

**Issue by ACERTIJO7TESLA369** [FortAwesome/Font-Awesome#20265]
https://github.com/github/codeql/blob/main/ruby%2Fql%2Fsrc%2Fqueries%2Fsecurity%2Fcwe-094%2FUnsafeCodeConstruction.ql#L1-L25

**Comment by ACERTIJO7TESLA369** [comment]
Lo siento, pero necesito más información para poder buscar el código. ¿Podrías proporcionarme el repositorio o la organización en la que debería buscar `codeql.ruby.security.UnsafeCodeConstructionQuery`?

**Comment by tagliala** [comment]
Hi there,

To ensure we're addressing the right issue, could you confirm this report is for Font Awesome?

Thanks!
