### ISSUE TITLE
Bug: React FontAwesomeIcon fas caret-right missing

### ISSUE THREAD

**Issue by phazei** [FortAwesome/Font-Awesome#20260]
### Bug description

Trying to use caret-right solid, it's not working

Shows an icon: `<FontAwesomeIcon icon={['fas', 'caret-down']} />`
Shows an icon: `<FontAwesomeIcon icon={['fal', 'caret-right']} />`

Shows NO icon: `<FontAwesomeIcon icon={['fas', 'caret-right']} />`

package.json
```
        "@fortawesome/fontawesome-pro": "^6.5.2",
        "@fortawesome/fontawesome-svg-core": "^6.5.2",
        "@fortawesome/free-brands-svg-icons": "^6.5.2",
        "@fortawesome/pro-light-svg-icons": "^6.5.2",
        "@fortawesome/pro-regular-svg-icons": "^6.5.2",
        "@fortawesome/pro-solid-svg-icons": "^6.5.2",
        "@fortawesome/react-fontawesome": "^0.2.2",
        "@fortawesome/react-native-fontawesome": "^0.3.2",
        "@fortawesome/sharp-light-svg-icons": "^6.5.2",
```

### Font Awesome version

v6.5.2

### Serving

Other (as specified in the bug description)

### Implementation

SVG Sprites

### Browser and Operating System

React 17

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
@phazei how are you importing the icons? I've verified that the icon is present in the package.

**Comment by phazei** [comment]
So, I realized we were importing specific ones in our App.js using the library.add and that the one I wanted wasn't there.  It was implemented by a long gone dev so I didn't realize they were individually being added and thought it was grabbing the ones needed at compile time.
