### ISSUE TITLE
Lo siento, pero necesito más información para poder buscar el código. ¿Podrías proporcionarme el repositorio o la organización en la que debería buscar `codeql.ruby.security.UnsafeCodeConstructionQuery`?

### ISSUE THREAD

**Issue by ACERTIJO7TESLA369** [FortAwesome/Font-Awesome#20266]
Lo siento, pero necesito más información para poder buscar el código. ¿Podrías proporcionarme el repositorio o la organización en la que debería buscar `codeql.ruby.security.UnsafeCodeConstructionQuery`?

_Publicado originalmente por @ACERTIJO7TESLA369 en https://github.com/FortAwesome/Font-Awesome/issues/20265- [ ] #issuecomment-2185254080_[]()@ACERTIJO7TESLA369

**Comment by tagliala** [comment]
Hi there,

To ensure we're addressing the right issue, could you confirm this report is for Font Awesome?

Thanks!
