### ISSUE TITLE
Icon request: trip-advisor

### ISSUE THREAD

**Issue by SpudDesign13** [FortAwesome/Font-Awesome#20269]
I've looked several times over the years for a Trip Advisor icon, and think it would be a great one to add to the brands icon set.  We build a lot of websites for the tourist and travel industry, and review sites like that are big deal for them.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Sorry, but Trip Advisor icon has been removed by request of copyright holder, we can't do this

https://fontawesome.com/changelog#v6-0-0-beta2
