### ISSUE TITLE
Bug: web-awesome is marked as Pro-only although it is available in Font Awesome Free

### ISSUE THREAD

**Issue by randomguy-2650** [FortAwesome/Font-Awesome#20262]
### Bug description

I was browsing the Font Awesome icon library and found the **`web-awesome`** icon (**Brands**, not Classic or Sharp) was marked as Pro-only (with Pro tag next to icon name, SVG code and SVG file download unavailable, etc., although not marked as Pro when viewed from the search results).

### Test case

_(Test case isn't available in this case)_

### Screenshots

![image](https://github.com/FortAwesome/Font-Awesome/assets/150704902/b54c9102-b624-4287-9b16-a65f41ac0dd0)
![image](https://github.com/FortAwesome/Font-Awesome/assets/150704902/6fff093c-ddc0-4ffc-b2eb-7f217332505a)

### Font Awesome version

v6.5.2, may occur in future versions if not fixed

### Application and Operating System

-   No answer that **_makes sense_**

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by fsd-niraj** [comment]
Is this completed or still need to work on? If yes, I can pick it up.

**Comment by robmadole** [comment]
@fsd-niraj this is something we'll have to work on in another system. We're on it!

**Comment by sensibleworld** [comment]
This is now fixed

![CleanShot 2024-07-16 at 13 33 28@2x](https://github.com/user-attachments/assets/4dd020a7-5052-48a6-a595-a29663fc77f4)
