### ISSUE TITLE
Bug: fa-solid does not work with fa-star-sharp

### ISSUE THREAD

**Issue by wisniewski94** [FortAwesome/Font-Awesome#20283]
### Bug description

`.fa-star-sharp` with `.fa-solid` renders as `.fa-regular`

```html
<i class="fa-regular fa-star-sharp"></i>
<i class="fa-solid fa-star-sharp"></i>
<i class="fa-solid fa-star-sharp"></i>
<i class="fa-solid fa-star-sharp"></i>
<i class="fa-solid fa-star-sharp"></i>
```

### Screenshots

<img width="307" alt="image" src="https://github.com/FortAwesome/Font-Awesome/assets/5289996/5b19c971-c300-4edf-bbf6-c55dce395065">

### Font Awesome version

v6.5.2

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

- Chrome Version 126.0.6478.127 (Official Build) (x86_64)
- MacOS Sonoma 14.2.1

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Possible to share a codepen or live example of this? Having trouble reproducing.

**Comment by wisniewski94** [comment]
It turns out to be a problem with project configuration. I messed up, sorry @sensibleworld

**Comment by sensibleworld** [comment]
No worries! Glad it's sorted.
