### ISSUE TITLE
Bug: fa-brands not working

### ISSUE THREAD

**Issue by NafiurSiddiqui** [FortAwesome/Font-Awesome#20282]
### Bug description

I have installed the `@fortawesome/fontawesome-free` package from NPM. Everything else is working other than the brand icons.
I have tried `fa-brands fa-facebook`, `fa-fab fa-facebook` none of them works. I have these installed in my package. 

![image](https://github.com/FortAwesome/Font-Awesome/assets/66395136/32c2bcf3-6986-4e7a-94f0-d6ebcc3f0c64)

I imported the necessary ones in my `app.js`, using `vite` for this laravel 11 project.

![image](https://github.com/FortAwesome/Font-Awesome/assets/66395136/e674be23-c9fe-485b-9f05-6a12ad11bfc9)

From here, when none of the brands work.

### Screenshots

Nothing. Nothing appears. Here is the network tab showing the script is loading fine -

![image](https://github.com/FortAwesome/Font-Awesome/assets/66395136/6fa56b3d-5763-4107-8729-08ef4cb2dfa6)

### Font Awesome version

v6.5.2

### Serving

Other (as specified in the bug description)

### Implementation

SVG+JS

### Browser and Operating System

- MS edge
- Ubuntu@latest

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Hi @NafiurSiddiqui. Try removing `@fortawesome/free-brands-svg-icons` and then add this:

```javascript
import '@fortawesome/fontawesome-free/js/brands'
```

**Comment by NafiurSiddiqui** [comment]
> Hi @NafiurSiddiqui. Try removing `@fortawesome/free-brands-svg-icons` and then add this:
> 
> ```js
> import '@fortawesome/fontawesome-free/js/brands'
> ```

Omg! why didn't I see this!! silly me. Thank you so much for clearing the air. It works perfectly fine. I am the bug here.
