### ISSUE TITLE
Icon Request: fa-flag-uk and fa-flag-au

### ISSUE THREAD

**Issue by mapsmarketing** [FortAwesome/Font-Awesome#20286]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

Having the US flag only and not other countries is quite weird. The world != the US. It would be great to have the UK and AU flag so we can represent the language selections correctly for the given audience. And I do not believe this is a niche request as most people would prefer the relevant flag to be shown. See: https://github.com/FortAwesome/Font-Awesome/issues/4735

### Visual example

<img width="138" alt="image" src="https://github.com/user-attachments/assets/630cdf33-a105-41dd-8286-8fc7f9209457">

**Comment by sensibleworld** [comment]
Thanks for the request! Just a quick note that we're moving all individual country-flag requests to a single open issue: https://github.com/FortAwesome/Font-Awesome/issues/20288
