### ISSUE TITLE
Bug: Misnamed label value in icon-families.json

### ISSUE THREAD

**Issue by euro** [FortAwesome/Font-Awesome#20297]
### Bug description

In the kit served via NPM in the following file:
`/node_modules/@awesome.me/kit-xxxxxxxxxx/icons/metadata/icon-families.json`

The value for `vimeo-v.label` is "Vimeo" and it should be "Vimeo V".

The pattern matches what I would see for another similar icon: `facebook-f`.

The value for `facebook-f.label` is "Facebook F".

### Font Awesome version

v6.6.0

### Serving

NPM served pro kit.

### Implementation

SVG+JS

### Browser and Operating System

NPM served pro kit.

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Thanks @euro . We've got this fixed and it will be corrected in our next version of Font Awesome.
