### ISSUE TITLE
Bug: Replace margin-left/margin-right in favor of direction neutral RTL-friendly margin-inset-start/end

### ISSUE THREAD

**Issue by matsbryntse** [FortAwesome/Font-Awesome#20305]
### Bug description

Seeing a few places which can be modernized:
```
.#{$fa-css-prefix}-ul {
  list-style-type: none;
  margin-left: var(--#{$fa-css-prefix}-li-margin, #{$fa-li-margin});
  margin-inline-start: var(--#{$fa-css-prefix}-li-margin, #{$fa-li-margin});
```

### Font Awesome version

6.6

### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Mac OS Ventura

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by talbs** [comment]
Thanks for letting us know, @matsbryntse! 

We've tackled this modernization as part of our initial efforts on Font Awesome 7. Expect to see it with that release.

Keep the good suggestions/improvements coming!

**Comment by matsbryntse** [comment]
Thanks, and keep up the awesome icon-making!
