### ISSUE TITLE
Bug: square-rss sharp is not sharp

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#20304]
### Bug description

Square RSS icon is not sharp as other sharp square icons

<img width="838" alt="image" src="https://github.com/user-attachments/assets/59b1f5e5-c013-4c21-bcd8-ba691f0910d8">

### Reproducible test case

https://fontawesome.com/icons/square-rss?f=sharp&s=solid

### Screenshots

<img width="548" alt="image" src="https://github.com/user-attachments/assets/c19daf5b-32bd-457b-9cc9-b3670eb94b51">

### Font Awesome version

v6.6.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Serving and implementation do not apply

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

Ref: #6074

**Comment by sensibleworld** [comment]
This is fixed in 6.7.0
