### ISSUE TITLE
Icon request: Pump.Fun & Dexscreener

### ISSUE THREAD

**Issue by IamDevSujith** [FortAwesome/Font-Awesome#20306]
Please create "Pump.Fun" and "Dexscreener.com" websites icon. Many crypto creators need this icons. So please consider this request as soon as possible.
```[tasklist]
### Tasks
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

Please create individual requests, as required by contributing guidelines

Closing here, but feel free to comment if I've missed something
