### ISSUE TITLE
Icon Request: fa-nurses

### ISSUE THREAD

**Issue by himawandh** [FortAwesome/Font-Awesome#20325]
Icon for medical

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Does https://fontawesome.com/icons/user-nurse?f=classic&s=solid fit the use case?

If it doesn't, please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and provide a single color example that suits 16px icon size

Closing here, but feel free to comment if I've missed something
