### ISSUE TITLE
Icon Request: fa-fan

### ISSUE THREAD

**Issue by mdyoshikawa** [FortAwesome/Font-Awesome#20322]
I need a fan icon for a humidity controller project I'm working on.

Thank you!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

If https://fontawesome.com/icons/fan?f=classic&s=solid does not fit this use case, please fill in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and remember to:
- explain why current "fan" does not fit a use case
- provide a single color example suitable for small (16px) icon sizes

Closing here, but feel free to comment if I've missed something
