### ISSUE TITLE
Bug: barcode icon in Duotone is coloured differently than in Sharp Duotone

### ISSUE THREAD

**Issue by randomguy-2650** [FortAwesome/Font-Awesome#20320]
### Bug description

For the `barcode` icon in Duotone, it is coloured as the secondary (translucent) colour for the entire icon, whereas for Sharp Duotone, it is **actually** Duotone, because it includes the main colour (opaque) and the secondary colour (translucent) too, which makes sense.

**Side note: For many Duotone icons including Sharp Duotone has only the secondary colour for the entire icon (example: `star`) whereas Version 5 icon equivalents have them entirely Duotone.**

### Reproducible test case

Compare https://fontawesome.com/icons/barcode?f=duotone&s=solid and https://fontawesome.com/icons/barcode?f=sharp-duotone&s=solid

### Screenshots

https://github.com/user-attachments/assets/3e1d7ce6-24b3-4749-8b1c-00b5dcabc639

### Font Awesome version

v6.0.0 – v6.6.0 (applies for all version 6 releases)

### Serving

Kit, Font Awesome CDN, Self-hosted, Other (as specified in the bug description)

### Implementation

CSS, SVG+JS, SVG Sprites, Other (as specified in the bug description)

### Browser and Operating System

All operating systems on all browsers, issue in Font Awesome's icons

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by randomguy-2650** [comment]
test comment

**Comment by sensibleworld** [comment]
This is fixed in 6.7.0
