### ISSUE TITLE
Bug: Getting 403 error for a certain custom Font-Awesome custom kit

### ISSUE THREAD

**Issue by liviulupei** [FortAwesome/Font-Awesome#20330]
### Bug description

This link started giving us a 403 error 1 hour ago:
https://kit.fontawesome.com/1af65f8dad.js

### Reproducible test case

https://kit.fontawesome.com/1af65f8dad.js

### Screenshots

<img width="444" alt="Screenshot 2024-08-12 at 16 32 32" src="https://github.com/user-attachments/assets/0a3e1202-3df8-4b38-b468-190717191542">

### Font Awesome version

Not sure exactly

### Serving

Font Awesome CDN

### Implementation

SVG+JS

### Browser and Operating System

Chrome 127 on MacOS Big Sur

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by TBLSource** [comment]
We have been having the exact same issue this afternoon at my organisation.

**Comment by tagliala** [comment]
Hi,

as per https://github.com/FortAwesome/Font-Awesome/issues/20324#issuecomment-2277919071, can you double check your pageview usage?

**Comment by liviulupei** [comment]
Hi @tagliala 

I don't have an account on Font-Awesome. That link was added to our code by an external collaborator.

**Comment by tagliala** [comment]
> That link was added to our code by an external collaborator.

Please ask the external collaborator for more information

**Comment by liviulupei** [comment]
> > That link was added to our code by an external collaborator.
> 
> Please ask the external collaborator for more information

Unfortunately, I cannot do that, since he died.
That's why I was looking for an alternative solution.

**Comment by tagliala** [comment]
> That's why I was looking for an alternative solution.

I'm sorry to hear that

Please get in touch with hello@fontawesome.com and add a link to this issue, there is not so much we can do on the free repo for this situation

**Comment by tagliala** [comment]
@TBLSource 


> We have been having the exact same issue this afternoon at my organisation.

Please follow instructions at #20324 and in case post there

Closing here
