### ISSUE TITLE
Icon Request: fa-airbnb

### ISSUE THREAD

**Issue by cartad77** [FortAwesome/Font-Awesome#20333]
![gratis-png-logo-airbnb-portatil-red-grafica-producto-de-la-marca-aire](https://github.com/user-attachments/assets/237fa734-2790-4654-be1e-fc4d4bf4835a)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon airbng has been added to FontAwesome in version 5.8.0:
- https://fontawesome.com/icons/airbnb?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request
