### ISSUE TITLE
Icon Request: pix

### ISSUE THREAD

**Issue by praxedesfilho** [FortAwesome/Font-Awesome#20335]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

to be used in projects

### Visual example

![pix](https://github.com/user-attachments/assets/fa999401-d228-4856-a9c3-55a66cafbd3b)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon `pix` has been added to FontAwesome in version 6.0.0:
- https://fontawesome.com/icons/pix?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

>  This icon does not represent a brand

that icon does represent a brand

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by praxedesfilho** [comment]
thank you very much for taking the time to help me.
