### ISSUE TITLE
ERR_ABORTED 403 (Forbidden)

### ISSUE THREAD

**Issue by prashanthcoe19** [FortAwesome/Font-Awesome#20347]
![image](https://github.com/user-attachments/assets/9b8ecd24-fa27-4248-bc3b-93ac622ddea8)

I have been using this kit. It is a free plan kit. I think it has reached it's limit.
If I upgrade my fontawesome account to pro lite, will the same kit starts working, or do I have to create an another kit?

**Comment by tagliala** [comment]
Hi @prashanthcoe19 , thanks for your interest in FA Pro Lite.

I've moved this question to https://github.com/FortAwesome/Font-Awesome/discussions/20346, it's a better place for this kind of questions

Please wait there for an answer
