### ISSUE TITLE
Icon Request: fa-flag-ma 🇲🇦

### ISSUE THREAD

**Issue by asmachkirida** [FortAwesome/Font-Awesome#20348]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

To be shown next to the country name in one of my school projects

### Visual example

![Capture d’écran 2024-09-06 193846](https://github.com/user-attachments/assets/7e344e38-7067-405b-a0b2-1f0a7c5b047e)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please refer to #20288 for country flags
