### ISSUE TITLE
Icon Request: fa-no-wifi

### ISSUE THREAD

**Issue by copcake91** [FortAwesome/Font-Awesome#20359]
No WiFi Signal
```[tasklist]
### Tasks
```

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro:
- https://fontawesome.com/icons/wifi-slash?f=classic&s=regular
- https://fontawesome.com/icons/wifi-exclamation?f=classic&s=regular

**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/231/

Ref:
- https://fontawesome.com/v6/docs/web/style/power-transform
- https://fontawesome.com/docs/web/style/mask
- https://fontawesome.com/docs/web/style/layer
- https://fontawesome.com/v6/docs/web/add-icons/icon-wizard#contentHeader

If you are wondering why this icon is not available in FA Free, please take a look at https://fontawesome.com/support#why-are-some-highly-requested-icons-not-available-in-font-awesome-free

Hope it helps, closing here
