### ISSUE TITLE
Feature request: support local domain lvh.me

### ISSUE THREAD

**Issue by kaka-ruto** [FortAwesome/Font-Awesome#20360]
### Is your feature request related to a problem?

I mostly use lvh.me for my local Rails app development, I just found out I cannot use font awesome icons on that local testing domain

### Feature description

Font awesome should whitelist all local testing domains like lvh.me and others

### Alternatives

Using localhost works

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I do also use `lvh.me` to test subdomains, it's very convenient

However, as far as I know, `lvh.me` is a privately owned domain, not an official standard. It's subject to change or removal without notice. I would not allowlist that by default. You can do it in your kits

/cc @robmadole

**Comment by robmadole** [comment]
Yeah, we won't allowlist anything that isn't trusted. @tagliala is correct.

What I do is place some domains in my `/etc/hosts` file @kaka-ruto. I have one called `kit-testing-domain.io` that resolved to `127.0.0.1`.

**Comment by tagliala** [comment]
Note: `lvh.me` is useful in contexts where you don't know exactly how many subdomains you may have, so individual entries in `/etc/hosts` may not work or not be possible.

In that case, I suggest to consider other solutions, like allowlisting `*.lvh.me` on a custom kit
