### ISSUE TITLE
Bug: License header is missing in free-solid-svg-icons@6.6.0/index.mjs

### ISSUE THREAD

**Issue by nothrow** [FortAwesome/Font-Awesome#20368]
### Bug description

Readme says that

> Attribution is required by MIT, SIL OLF, and CC BY licenses. Downloaded Font Awesome Free files already contain embedded comments with sufficient attribution, so you shouldn't need to do anything additional when using these files normally.

Which does not work for https://www.npmjs.com/package/@fortawesome/free-solid-svg-icons package.

If CommonJS is used, the index.js has proper heading with `/*!` license.

However, since 6.3.0, when `index.mjs` is also produced, given file does not contain the license, so license is not part of our build output. 

Would it be possible to include license also in `index.mjs` in distributed package for free-solid-svg-icons?

### Reproducible test case

https://github.com/FortAwesome/Font-Awesome/blob/6.x/js-packages/%40fortawesome/free-regular-svg-icons/index.mjs

### Font Awesome version

v6.6.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

packaging issue, OS + browser do not apply

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by yadavshubham01** [comment]
hey @robmadole are you still working on this issue and if not please review this PR #20378

**Comment by tagliala** [comment]
This should have been fixed in 6.7.x, please comment if it is still a problem
