### ISSUE TITLE
Icon Request: fa-cpx

### ISSUE THREAD

**Issue by rafgger** [FortAwesome/Font-Awesome#20374]
I would kindly like to ask for the creation of this icon. Many thanks!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can you please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) or [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+)

And add an inline example of the icon you are requesting?

Having it in an attached pdf may represent a security concern

Closing here
