### ISSUE TITLE
Add Dev.to icon family

### ISSUE THREAD

**Issue by aaiezza** [FortAwesome/Font-Awesome#20372]
Hoping to have icons added for the social developer blogging network [Dev.to](https://dev.to/) added to FontAwesome.

Not sure what the handle would be, but maybe something like `fa-dev-to`?

Thanks.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Isn't this icon already here? https://fontawesome.com/icons/dev?f=brands&s=solid

**Comment by Ashish-CodeJourney** [comment]
> Hi!
> 
> Thanks for being part of the Font Awesome Community.
> 
> Isn't this icon already here? https://fontawesome.com/icons/dev?f=brands&s=solid

Yes it's there, I am using this from few weeks

**Comment by aaiezza** [comment]
Yes, I found it! It's just called `dev`. Just felt rather generic.
I wouldn't mind requesting a second alias to include the `to`, but that's fine. Thanks for the help!
