### ISSUE TITLE
Icon Request: fa-googlecholar

### ISSUE THREAD

**Issue by juneMJ** [FortAwesome/Font-Awesome#20371]
An icon for Google Scholar.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

google-scholar icon has been added to FontAwesome in version 6.5.0:
- https://fontawesome.com/icons/google-scholar?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by juneMJ** [comment]
It's great, thanks!
