### ISSUE TITLE
Icon Request: fa-researchgate

### ISSUE THREAD

**Issue by juneMJ** [FortAwesome/Font-Awesome#20370]
An icon for ResearchGate.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

researchgate icon has been added to FontAwesome in version 5.0.11:
- https://fontawesome.com/icons/researchgate?f=brands&s=solid

If you have troubles in using or upgrading Font Awesome, please check our documentation

https://fontawesome.com/docs/web/add-icons/how-to

Hope it helps

Closing here, but feel free to comment and provide more information if I didn't get this request

**Comment by Intargest** [comment]
CONTRIBUTING.md

**Comment by juneMJ** [comment]
Awesome, thanks!
