### ISSUE TITLE
icon request: icon-flower

### ISSUE THREAD

**Issue by jbgriffith** [FortAwesome/Font-Awesome#2037]
Snowflake which would represent winter. 
Flower which would represent spring.

You already have:
Sun which represents Summer.
Leaf which represents Fall.

**Comment by yguezeldal** [comment]
+1

**Comment by scotteuser** [comment]
+1 Thanks!

**Comment by hebbet** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by ClearEdgeConsulting** [comment]
+1

**Comment by kadmos1** [comment]
+1

**Comment by GwenLoguir** [comment]
+1

**Comment by coffeelady** [comment]
+1

**Comment by solid2core** [comment]
+1

**Comment by tintomatoes** [comment]
+1

**Comment by sgryphon** [comment]
+1

**Comment by ryanaoneil** [comment]
+1 I'm creating a tool for florists. Need this!!

**Comment by lyhil** [comment]
+1

**Comment by hotnuts21** [comment]
+1

**Comment by martinholsten** [comment]
+1

**Comment by Davidiborra** [comment]
+1

**Comment by gomezfx** [comment]
+1

**Comment by brentdeacon** [comment]
+1

**Comment by xabispacebiker** [comment]
+1

**Comment by ryanaoneil** [comment]
+1

**Comment by ryanaoneil** [comment]
For 200 us, David Gandy said they can do a custom flower icon. I'll do $10 of that. Anybody else in? 

@xabispacebiker @brentdeacon @gomezfx @Davidiborra @martinholsten @hotnuts21 @lyhil @sgryphon @tintomatoes @solid2core @coffeelady @GwenLoguir @kadmos1 @ClearEdgeConsulting @G-Driver @hebbet @scotteuser @yguezeldal @tarkant @tarkant @loving1 @jbgriffith @chidg @tomByrer @adamdrake210 @Fania @nmhewitt

**Comment by z2013** [comment]
+1

**Comment by corneliu-serediuc** [comment]
I think it should be a very simple icon. Something like this:

![icon_flower_full](https://cloud.githubusercontent.com/assets/2992106/12846936/0ba7553e-cc10-11e5-93b7-5c247e8a5526.jpg)
![icon_flower_empty](https://cloud.githubusercontent.com/assets/2992106/12846940/0ea842b6-cc10-11e5-9000-f2721dda8c0a.jpg)

Ohh.... and yeah.. +1 (pretty please)

**Comment by pasci84** [comment]
+1

**Comment by jczerew** [comment]
+ 1

**Comment by sakafujn** [comment]
+1

**Comment by okon3** [comment]
+1

**Comment by boiyelove** [comment]
+1

**Comment by Melloyell** [comment]
+1

**Comment by johnnyshields** [comment]
Flower and Rose available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by rvanlaak** [comment]
:+1: on specifically having a tulip for the summer.

**Comment by johnnyshields** [comment]
@rvanlaak check out vesper icons (see above)

![image](https://cloud.githubusercontent.com/assets/27655/17629990/58b9818a-60f8-11e6-9637-abfc56338669.png)

**Comment by Crissov** [comment]
## Flower and blossom Unicode emojis
* [🌱 U+1F331 Seedling](http://emojipedia.org/seedling/)
* [🌷 U+1F337 Tulip](http://emojipedia.org/tulip/)
* [🌸 U+1F338 Cherry Blossom](http://emojipedia.org/cherry-blossom/)
* [🌹 U+1F339 Rose](http://emojipedia.org/rose/)
* [🌺 U+1F33A Hibiscus](http://emojipedia.org/hibiscus/)
* [🌻 U+1F33B Sunflower](http://emojipedia.org/sunflower/)
* [🌼 U+1F33C Blossom](http://emojipedia.org/blossom/)
* [🏵 U+1F3F5 Rosette](http://emojipedia.org/rosette/)
* [💐 U+1F490 Bouquet](http://emojipedia.org/bouquet/)
* [💮 U+1F4AE White Flower](http://emojipedia.org/white-flower/)
* [🥀 U+1F940 Wilted Flower](http://emojipedia.org/wilted-flower/)

## Non-emoji Unicode floral characters
* ⚘ U+2698 Flower – not an emoji (yet)
* ✾ U+273E Six Petalled Black and White Florette
* ✿ U+273F Black Florette
* ❀ U+2740 White Florette
* ❁ U+2741 Eight Petalled Outlined Black Florette

**Comment by melmsie** [comment]
+1

**Comment by bonekost** [comment]
+1

**Comment by colinrcummings** [comment]
+1

**Comment by boiyelove** [comment]
+1

**Comment by eruminski** [comment]
+1

**Comment by VeRychard** [comment]
+1 for the head of flower icon

**Comment by csa12** [comment]
+1 fa-flower, fa-flower-bulb, 
Different categories of flowers;
fa-daffodil (Narcissus), fa-hyacinth (Hyacinthus), fa-tulip (Tulipa), fa-crocus, fa-anemone, fa-amaryllis, fa-colchicum, fa-ranunculus... or perhaps getting too specific...

**Comment by Wingo5315** [comment]
+1

**Comment by simplyjessi** [comment]
+1

PLEAAAAAAAAAAAAAAAAAAAAAASE

**Comment by symball** [comment]
still no flower incorporated?

**Comment by KingDumah** [comment]
+1

**Comment by SaraKoncz** [comment]
+1

**Comment by sensibleworld** [comment]
The latest release of Font Awesome Pro smells fantastic with these new additions:
https://fontawesome.com/icons/flower?style=solid
https://fontawesome.com/icons/flower-tulip?style=solid
https://fontawesome.com/icons/flower-daffodil?style=solid
