### ISSUE TITLE
Bug: Deprecation Warnings on @import and unquote using sass 1.80.xxx

### ISSUE THREAD

**Issue by jmaino** [FortAwesome/Font-Awesome#20389]
### Bug description

As of sass 1.80.xx there are 2 new Deprecation Warnings arising.

The first is from the deprecation of `@import`, which results in Warnings alike:

```
**Deprecation Warning on line 9, column 9 of node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss: 
Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import
  ╷
9 │ @import 'functions';
  │         ^^^^^^^^^^^
  ╵**
```

The 2nd has to do with the deprecation of global built-in functions, and impacts the use of "unquote", which will results in the following

```
Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
8 │   .#{$fa-css-prefix}-#{$name}::before { content: unquote("\"#{ $icon }\""); }
  │                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    node_modules/@fortawesome/fontawesome-free/scss/_icons.scss 8:50  @import
    @fortawesome/fontawesome-free/scss/fontawesome.scss 20:9          @use
```

### Font Awesome version
```
    "@fortawesome/fontawesome-free": "^6.6.0"
```
### Serving

Self-hosted

### Implementation

CSS

### Browser and Operating System

Chrome on Windows11x64

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for the heads-up.

Unfortunately we need to support other implementations of sass. Is there any alternative to `@import`? I'm afraid this will stay this way in FA6

> 8 │ .#{$fa-css-prefix}-#{$name}::before { content: unquote(""#{ $icon }""); }

This is quite unfortunate, for the same reason.

I'm afraid those deprecations should be silenced in FA6, whereas we should be fine in FA7, where we are dropping legacy sass compilers

Ref: https://github.com/twbs/bootstrap/issues/40849#issuecomment-2404503702

/cc @talbs @robmadole

**Comment by jmaino** [comment]
Hi, 

For the first issue, from dart sass' documentation, it looks as-if `@use` is now recommended instead of `@import` - but this has some other limitations such as the `@use` is local, vs `@import` being global.   

For the 2nd issue, it looks adding `@use 'sass:string'` and then replacing all unquote with string.unquote   will resolve this.

I've tried making both of these changes locally, and sass no longer complains about these 2 issues, but is now complaining that some of the expressions are no longer correct, and this is now an Error condition rather than a Warning
```
Error: Undefined operation "2em * fa-divide(5, 4)".
   ╷
38 │ $fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default;
   │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 38:27  @use
  @fortawesome/fontawesome-free/scss/fontawesome.scss 12:1               @use
  app/assets/stylesheets/application.scss 18:1                           root stylesheet
```

So, something more needs to be done on my side to figure out how/why the above 3rd issue arises with the `@use` and string.unquote changes in place.  I know that the fa-divide function itself is known, b/c this appears alone, upstream in _variables.scss and has no problem - there's something about the multiplication of the function that is not to sass' liking w/ my changes in place.

**Comment by tagliala** [comment]
> For the 2nd issue, it looks adding `@use 'sass:string'` and then replacing all unquote with string.unquote will resolve this.

Sorry but we can't do this. `@use 'sass:string'` is dart-sass syntax. FA 6 also supports node-sass, ruby-sass, and other sass compilers

Ref:
- https://github.com/FortAwesome/Font-Awesome/issues/18908#issuecomment-1106315131
- #17940
- (and many others)

**Comment by jmaino** [comment]
thank you, and I understand.
I was not suggesting that those changes be adopted as part of FA6, but was rather documenting what I had tried to see if I could find something to move my own environment forward without having to simply silence the warnings for now.

I appreciate all of the details you've included.
Thanks again for these and any future improvements that are made - I await FA7

**Comment by robmadole** [comment]
@jmaino I think right now silencing the warnings are the only option. We actually just ran into this ourselves with our own test suite.

I'm going to close this. Dart Sass is doing the correct thing with these deprecations and they allow silencing exactly for this reason: so the old stuff continues to work and they can make progress on their library.

**Comment by maalvarado** [comment]
This one works for Webpack:
```
{
    loader: 'sass-loader',
    options: {
      sassOptions: {
        silenceDeprecations: ['mixed-decls', 'color-functions', 'global-builtin', 'import'],
      }
    }
  }
```
