### ISSUE TITLE
Icon request: icon-message-request or request icon

### ISSUE THREAD

**Issue by ShaliniKannan05** [FortAwesome/Font-Awesome#20383]
Need a icon for message request, message share or comment share

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can you please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) and provide a single-color, small size suitable example of the icon you have in mind?

Closing here, but feel free to comment if I've missed something
