### ISSUE TITLE
Bug: fa-bars and fa-bars-sort missing lines in sharp-duotone

### ISSUE THREAD

**Issue by Muenchen-Michi** [FortAwesome/Font-Awesome#20380]
### Bug description

Both icons fa-bars and fa-bars-sort have 3 lines in all styles, but sharp-duotone. Even in duotone the icons have 3 lines.
It seems, the lines with secondary-color are missing in sharp-duotone.

### Reproducible test case

https://fontawesome.com/search?q=bars&o=r&f=duotone%2Csharp-duotone

### Screenshots

![grafik](https://github.com/user-attachments/assets/e4b049c2-8afd-4381-a6be-e3099d2a090b)
![grafik](https://github.com/user-attachments/assets/53508b6f-4a71-41bb-a3a8-3c55a5cbe453)

### Font Awesome version

v6.6.0

### Serving

Other (as specified in the bug description)

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

Tested on Windows and Android with latest versions of Firefox and Chrome.

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
Thanks for reporting. We'll take a look.

**Comment by sensibleworld** [comment]
This was fixed in 6.7.0.
