### ISSUE TITLE
Brand request: Laravel Logo Update

### ISSUE THREAD

**Issue by iamdavidhill** [FortAwesome/Font-Awesome#20385]
### Description

Hi, 

My name is David Hill, I'm Head of Design at Laravel. We've made a small change to our icon to make it a little thicker at smaller sizes. Please could you update the icon in Font Awesome?

![laravel-logo-small](https://github.com/user-attachments/assets/fd14a526-17fb-416d-af66-14bab76cd88d)

### Official website

laravel.com

### Icon request checklist

- [X] The title starts with "Brand request: ", is followed by the requested brand name
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have [understood how requests work](https://fontawesome.com/community/leaderboard/brands#faqs)

**Comment by tagliala** [comment]
Thanks for the heads-up and for the official svg!

**Comment by sensibleworld** [comment]
Thanks, @iamdavidhill! We've got this updated in 6.7.1: https://fontawesome.com/icons/laravel?f=brands&s=solid
