### ISSUE TITLE
Icon Request: icon-houzz

### ISSUE THREAD

**Issue by curthayman** [FortAwesome/Font-Awesome#2039]
I would like to request the houzz icon to be added to your collection. There logo is kinda hard to implement into some websites.

Thanks for such a great product!!!!
![houzz_logo](https://f.cloud.github.com/assets/1430023/1221042/a63b905c-26e4-11e3-88f1-9d030c2dd61c.gif)

**Comment by kaeruranawa** [comment]
+1

**Comment by sebastiansulinski** [comment]
+1

**Comment by kschwarz17** [comment]
+1

**Comment by brighaminteriors** [comment]
+1 

Thanks!

**Comment by ryanschweitzer** [comment]
+1 – this would be great!

**Comment by potat5** [comment]
+1

**Comment by admench** [comment]
+1

**Comment by devinmatte** [comment]
+1

**Comment by chadamski** [comment]
+1

**Comment by bryandugan** [comment]
+1

**Comment by mjmb** [comment]
+1

**Comment by dexterj** [comment]
+1

**Comment by erikhanshagstrom** [comment]
+1

**Comment by cleverapps** [comment]
+1

**Comment by Brandonsmith23** [comment]
+1

**Comment by fly2006** [comment]
+1

**Comment by kirkroberts** [comment]
+1

**Comment by benmacadam** [comment]
+1

**Comment by stephenfjohnson** [comment]
+1

**Comment by JenWillDesign** [comment]
+1

**Comment by jasonbrueckner** [comment]
+1

**Comment by rtpHarry** [comment]
FYI this is currently in the brandico font set:
http://fontello.com/#search=houzz

and also its got a bit buried but @brandoncordell has said further up he has made it into a font aswell:
https://github.com/brandoncordell/houzz-icon-font

**Comment by jasonbrueckner** [comment]
Thank you for commenting here, @rtpHarry ... can you (or anyone else) advise? I'm having issues with the icon showing up on my site: http://www.pure-design-interiors.com.

Thank you!

**Comment by rtpHarry** [comment]
Yeah but this isn't really the place to start a conversation about it. I'll quickly reply here but if you have any follow up questions I would suggest opening an issue over on the https://github.com/brandoncordell/houzz-icon-font repo. Then just give me a link to that here.

The poor crew running the FA issue's have thousands of open issues and we don't want to clutter up their lives any more with unrelated stuff.

Looking in your code you have just copied the usage example verbatim:

    <link rel="stylesheet" href="/path/to/houzz-icon-font.css">

What you should have done is uploaded the files inside the `css` and `font` folders which are [in the repo](https://github.com/brandoncordell/houzz-icon-font) and then changed the `/path/to/` bit so that it pointed at those files.

It looks like you're using WordPress, you are going to need to upload the files using something called `ftp` which you might need to ask your developers / hosts for the information. This will let you create the folders on your webserver so that you can include them in the site.

**Comment by mjaneAnder** [comment]
+1 
![social-media-icons-houzz](https://cloud.githubusercontent.com/assets/11753976/6940849/3d45b6ba-d82f-11e4-8680-0a8fda2147e1.png)

**Comment by whitehat101** [comment]
:+1:

**Comment by jamesgiroux** [comment]
+1 on this.  we see houzz come up a lot with our clients.

**Comment by simonds** [comment]
+1. I have had several new clients in the past few months that are on houzz.

**Comment by dhaupin** [comment]
Houzz is a pretty large social site and marketplace dealing with home and outdoor. There are tons of businesses on it, which means their sites/stores would def utilize the icon. It would be a worthy addition to Font Awesome considering this alone...The massive amount of users, the well rated mobile apps, and the potential for IPO growth are icing on a popular cake.

![Houzz apple touch icon](http://st.houzz.com/static/apple-touch-icon-144x144-precomposed.png)
http://st.houzz.com/static/apple-touch-icon-144x144-precomposed.png

**Comment by cojomojo** [comment]
+1. 4 clients in the last 2 months requesting thiss,,

**Comment by iamjanco** [comment]
+1

**Comment by iamjanco** [comment]
Btw, if it helps, you can add the houzz icon in socicons to a new set you can create at icomoon. It's not that difficult:

![2015-05-16_15-27-10](https://cloud.githubusercontent.com/assets/2249669/7667700/3d37e1d6-fbe1-11e4-940b-b3a2d71a8d5e.jpg)

**Comment by billsmithem** [comment]
Please.
+1

**Comment by SabrinaBrand** [comment]
+1

**Comment by diZturbio** [comment]
and yet another +1

**Comment by markjdesign** [comment]
![houzz_logo](https://cloud.githubusercontent.com/assets/12738396/7972818/812c3028-0a04-11e5-9394-9dc91d289364.jpg)
Can we get this one created please?

**Comment by relish27** [comment]
+1

**Comment by wisebman** [comment]
+1

**Comment by jlr7245** [comment]
+1 I have needed this icon for 20+ clients

**Comment by LordLiverpool** [comment]
+1 please!!!

**Comment by jspenc72** [comment]
+1 Please!!!

**Comment by EricJammin** [comment]
+1 just do it!

**Comment by vipulhadiya** [comment]
Please add houzz icon

**Comment by amwelles** [comment]
+1

**Comment by alephdesignstudio** [comment]
This has to be the most demanded icon!!! 
I don't understand why there is absolutely no response from font-awesome on this issue! 
the request goes back 2 year on this one page alone!!
anyone home????

+1 for this request

**Comment by devinmatte** [comment]
+1

**Comment by jlavoie13** [comment]
+1

**Comment by christologan** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.

**Comment by markjdesign** [comment]
What is 4.4.0 wip branch?

**Comment by tagliala** [comment]
@markjdesign the branch for the next release: https://github.com/FortAwesome/Font-Awesome/tree/4.4.0-wip
