### ISSUE TITLE
Icon request: tripadvisor

### ISSUE THREAD

**Issue by nurispark** [FortAwesome/Font-Awesome#20397]
[TripAdvisor](https://www.tripadvisor.com/) is a leading travel and review site that significantly influences consumer decisions on dining, accommodations, and attractions. Having a dedicated TripAdvisor icon on FontAwesome would enhance credibility for businesses relying on online reputation. This icon allows companies to easily integrate and promote reviews from a trusted platform, helping users make informed choices. Adding the brand’s icon to the FontAwesome brand library would support businesses in promoting their online reputation.
![TripAdvisor](https://github.com/user-attachments/assets/e44b27c2-a607-4d64-996e-6df387352e3c)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

as per issue #18180, Tripadvisor asked to remove the icon and it has been done in version 5.15.4

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md#5154---2021-08-04
