### ISSUE TITLE
Bug: Font Awesome `bluesky` icon is not symmetrical

### ISSUE THREAD

**Issue by marcoroth** [FortAwesome/Font-Awesome#20406]
### Bug description

I noticed (don't ask me how 😅) that the Font Awesome [`bluesky`](https://fontawesome.com/icons/bluesky?f=brands&s=solid) icon is not symmetrical. 

Comparing it to the current icon on [bsky.app](https://bsky.app) it seems like theirs **is** symmetrical, but maybe theirs wasn't either in the past when you introduced the icon in Font Awesome🙈 

<img src="https://github.com/user-attachments/assets/550317b8-c8ad-4034-a5bc-a49fd6df0e68" width="40%">

I'm happy to open a PR to fix the SVG if you are up for it, otherwise feel free to close this issue as I don't think it's really noticeable 😅 

### Font Awesome version

v6.6.0

### Application and Operating System

any

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
This is fixed in 6.7.0

**Comment by marcoroth** [comment]
Thank you, @sensibleworld! 🙏🏼

**Comment by sensibleworld** [comment]
Thanks for letting us know!

**Comment by skywalker023** [comment]
@sensibleworld Can you please add the square version too? 🙏🏻

**Comment by sensibleworld** [comment]
Yup! Stay tuned.

**Comment by sensibleworld** [comment]
We adjusted the size of the icon just a bit, and also released a square version in 6.7.1

https://fontawesome.com/icons/square-bluesky?f=brands&s=solid
https://fontawesome.com/icons/bluesky?f=brands&s=solid
