### ISSUE TITLE
Bug: SCSS Deprecation of unquote(); use string.unquote() instead

### ISSUE THREAD

**Issue by wolfgang-demeter** [FortAwesome/Font-Awesome#20414]
### Bug description

The usage of `unquote()` is deprecated and will be removed in Dart Sass 3.0.0. Please use `string.unquote()` instead. 
https://sass-lang.com/documentation/modules/string/#unquote

Currently the following **warning is thrown** when compiling the SCSS version of Font Awesome Pro 6.6.0:
```
Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.
Use string.unquote instead.

More info and automated migrator: https://sass-lang.com/d/import

97 |             content: unquote("\"#{ $icon }#{ $icon }\"");
```

### Font Awesome version

v6.6.0

### Serving

Self-hosted

### Implementation

Other (as specified in the bug description)

### Browser and Operating System

dart-sass version: 1.80.5 via sass-embedded
https://sass-lang.com/dart-sass/

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for taking the time to report this.

Unfortunately this can't be fixed in FA6 because we support multiple sass compilers. It will be addressed by FA7 by requiring a modern version of dart sass

Closing here as a duplicate #19167
