### ISSUE TITLE
Bug: TypeScript errors in 6.7.0

### ISSUE THREAD

**Issue by joshkel** [FortAwesome/Font-Awesome#20419]
### Bug description

Since upgrading to 6.7.0, trying to add a pro duotone icon to my library throws an error:

```ts
import { library } from '@fortawesome/fontawesome-svg-core';
import { faSignal } from '@fortawesome/pro-duotone-svg-icons/faSignal';
library.add(faSignal);
```

Here's the error:

```
Argument of type '[IconDefinition]' is not assignable to parameter of type 'IconDefinitionOrPack[] | IconDefinitionOrPack[][]'.
  Type '[IconDefinition]' is not assignable to type 'IconDefinitionOrPack[][]'.
    Type 'IconDefinition' is missing the following properties from type 'IconDefinitionOrPack[]': length, pop, push, concat, and 35 more.ts(2345)
```

The error isn't very helpful (most likely because TypeScript is trying to resolve several overloads and alternatives and can't identify the most obvious failure). The failure appears to be caused by an incompatibility in the `IconPrefix` type (which shows up in `IconDefinition.prefix`) - the `@fortawesome/pro-duotone-svg-icons` package lists a different set of supported prefixes than the `@fortawesome/fontawesome-common-types` package that `library.add` uses.

### Font Awesome version

v6.7.0

### Serving

Font Awesome CDN

### Implementation

SVG+JS

### Browser and Operating System

TypeScript 5.6.3 on macOS

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by joshkel** [comment]
I realized this was a mistake on my end - my tools skipped upgrading @fortawesome/pro-duotone-svg-icons for some reason. The type incompatibility was caused by this version conflict.

**Comment by robmadole** [comment]
Yep, easy for that to happen @joshkel . Glad you got it figured out.
