### ISSUE TITLE
Icon Request: fa-babybottle

### ISSUE THREAD

**Issue by jeggino** [FortAwesome/Font-Awesome#20417]
please....I need it for my student project ...please...please...please

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

baby-bottle icon has been added to FontAwesome Pro in version 6.5.2:
- https://fontawesome.com/icons/bottle-baby?f=classic&s=regular

Original request: #12752

A useful answer from FAQs:

> ### Why are some (highly requested) icons not available in Font Awesome Free?
>
> Font Awesome began as a free resource and it's important to us that there will always be a free version of it that is more-than-usable by anyone who needs icons. But we built a team to make sure we continue to add icons, features, and make Font Awesome, well, awesome. That team is full of great people who help make our icons and products - but they're also folks with bills, kids, and dreams of their own that require a salary.

Ref: https://fontawesome.com/support#why-are-some-highly-requested-icons-not-available-in-font-awesome-free

Hope it helps

Closing here

**Comment by jeggino** [comment]
Hi Geremia, thanks for answering! The thing is that fa-babybottle is in a
pro account. I was wondering if could be added at least a version to the
free mode...thanks in advance.

Luigi
