### ISSUE TITLE
Bug: Module not found when using Kit Package

### ISSUE THREAD

**Issue by PimButton** [FortAwesome/Font-Awesome#20413]
### Bug description

We want to use custom icons in our project so we followed the guide over at https://docs.fontawesome.com/web/add-icons/upload-icons and https://docs.fontawesome.com/web/dig-deeper/kit-package-api
We ran into the typescript issue described in the Troubleshooting section, but by changing `moduleResolution` to "nodenext" the typescript issue disappears. 
However, when running the application the module cannot be resolved and we run into the following error: Unable to resolve "@awesome.me/kit-60######/icons/kit/custom" from "src/app/_layout.tsx"
<img width="574" alt="Screenshot 2024-11-13 at 16 22 03" src="https://github.com/user-attachments/assets/a89d2f79-12ef-427c-95f6-e78d0c4fd89c">

Test case (based on default Expo):
`index.tsx:`
```
import { Text, View } from "react-native";

export default function Index() {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Text>Edit app/index.tsx to edit this screen.</Text>
    </View>
  );
}
```

`app/_layout.tsx:`
```
import { Stack } from "expo-router";
import { all } from "@awesome.me/kit-#######/icons";
import { library } from "@fortawesome/fontawesome-svg-core";

library.add(all);

export default function RootLayout() {
  return (
    <Stack>
      <Stack.Screen name="index" />
    </Stack>
  );
}
```

### Font Awesome version

6.6.0

### Application and Operating System

 "react": "18.2.0",
"react-native": "0.74.5",
"react-native-svg": "15.2.0",
"expo": "~51.0.28",

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by robmadole** [comment]
@PimButton do you know if the module resolution in your app is leveraging the `exports` attribute in the package.json?

**Comment by PimButton** [comment]
It was not, apparently React Native still has only experiment support for Package Exports: https://reactnative.dev/blog/2023/06/21/package-exports-support

Setting `config.resolver.unstable_enablePackageExports = true;` in the Metro config solved the issue!
