### ISSUE TITLE
Feature request: Webjar for fontawsome 6.6.0 

### ISSUE THREAD

**Issue by Ashish-CodeJourney** [FortAwesome/Font-Awesome#20411]
### Feature description

According to the Font Awesome website https://fontawesome.com/versions, version 6.6.0 of Font Awesome was released on 7th of July 2024.
As of 12th of November 2024, on https://www.webjars.org/ the latest version available is still 6.5.2.

### Feature request checklist

- [X] The title starts with "Feature request: " and is followed by the requested feature description
- [X] This is a single feature
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm not familiar with WebJar, and I see that there is a deprecation message which links to webjars/webjars#2039

It looks to me that the Font Awesome webjar is a third-party library, probably an issue should be opened at https://github.com/webjars/font-awesome

Anyway, let's ask for confirmation to @robmadole

**Comment by robmadole** [comment]
@tagliala is correct. We don't manage that project or distribution channel.

**Comment by Ashish-CodeJourney** [comment]
> @tagliala is correct. We don't manage that project or distribution channel.

Thanks :)
