### ISSUE TITLE
Bug: Mismatch free-solid-svg-icons and common-types types

### ISSUE THREAD

**Issue by Tsingis** [FortAwesome/Font-Awesome#20427]
### Bug description

Hope this went into correct category. There seems to be mismatch free-solid-svg-icons and common-types `IconPrefix` and `IconName` types starting from v6.7.0.

```
  Type 'IconDefinition' is not assignable to type 'IconLookup'.
    Types of property 'prefix' are incompatible.
      Type 'import("/home/runner/work/app/node_modules/@fortawesome/free-solid-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconPrefix' is not assignable to type 'import("/home/runner/work/app/node_modules/@fortawesome/fontawesome-common-types/index").IconPrefix'.
        Type '"fadr"' is not assignable to type 'IconPrefix'. Did you mean '"far"'?
```

### Font Awesome version

v.6.7.0+

### Application and Operating System

Not applicable

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by Tsingis** [comment]
Dependabot not able to handle all dependencies properly in this case. False alarm!

**Comment by tagliala** [comment]
Hi, you may want to group fontawesome dependencies:

https://github.com/diowa/ruby3-rails7-bootstrap-heroku/blob/237ad76808a41510b46396728f1ad99034794e41/.github/dependabot.yml#L28-L30
