### ISSUE TITLE
Icons failing to load in  Safari browser

### ISSUE THREAD

**Issue by simondipad** [FortAwesome/Font-Awesome#20422]
This issue occuring very suddenly today 19/11/24. Icons display correctly in Chrome.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [bug report template for web applications](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+)

Closing here, but feel free to comment if I've missed something

**Comment by simondipad** [comment]
Apologies  - this was a browser security update issue. Please disregard.
S
