### ISSUE TITLE
Bug: 6.7.0 "ReferenceError: Can't find variable: X" Desktop Safari

### ISSUE THREAD

**Issue by 8bitmatt** [FortAwesome/Font-Awesome#20424]
### Bug description

Seems to affect all versions of Safari before 18

- Error is shown in console "ReferenceError: Can't find variable: X"
  - Line of code throwing the error is in `pro.min.js`  
    ```a=X[e][t];```
- No icons load for that browser

### Reproducible test case

Should be able to use any kit with 6.7.0 and see the error

### Font Awesome version

v6.7.0

### Serving

Kit

### Implementation

CSS

### Browser and Operating System

- Older versions of Desktop Safari (pre v18)

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by johnnorris** [comment]
I'm also having this problem. No icons showing at all for Safari users, on a wide range of versions (13-17 at least). Rollbar is reporting that this is also on iOS. Started on the 18th. I can't see evidence of a release of Font Awesome that might have brought this on - what's going on? [Update] Ah no your website says 11th November, but Github says 18th November, so it's release 6.7.0 for sure.

**Comment by robmadole** [comment]
@johnnorris @8bitmatt can you send an email (ask for Rob) to hello@fontawesome.com with your Kit tokens? I need to see how those are configured because I have a hunch what's going on here.

**Comment by rix1** [comment]
Experienced the same problem. Pinned our version to 6.6.0 in the fontawesome console for now. Let me know if there's anything we can share to help debugging @robmadole 👍

**Comment by vitld** [comment]
Same issue here. But whole page is just blank (probably just implementation), with reported error in console. Pinned to v6.6.0 for, will see if it resolves it.

EDIT: Pinning to 6.6.0 fixed it. So definitely something with v6.7.0 or later.

**Comment by robmadole** [comment]
Update for those interested. It looks like the minifier we are using for some of the JavaScript files went haywire/has a bug. I was able to fix a customer's Kit by switching to the unminified version. I don't have a root cause fix yet but we're working on it.

**Comment by aoxenrider** [comment]
> Update for those interested. It looks like the minifier we are using for some of the JavaScript files went haywire/has a bug. I was able to fix a customer's Kit by switching to the unminified version. I don't have a root cause fix yet but we're working on it.

@robmadole We are also having this issue and I don't see an option for using the unminified version of our kit. Do you have a link to a guide or is there a common naming scheme, etc? Thank you!

**Comment by robmadole** [comment]
@aoxenrider we deployed a workaround yesterday that turns off minification for Kits that could be affected. So you might double-check to see if that's showing up. If it's still broken, send an email to hello@fontawesome.com and ask for me and throw a link to this issue. I'll need your Kit code to take a closer look and we'll keep that private.

**Comment by aoxenrider** [comment]
@robmadole Thank you! Our kit is now functioning properly due to this fix.

**Comment by robmadole** [comment]
Okay folks, we've got the underlying issue fixed as part of 6.7.2. For any Kits that are set to use the latest version of Font Awesome I'm going to re-enable the minification. We don't anticipate any issues from this but I wanted to make sure this thread knew what was happening. I'll be performing this change in the next hour.

**Comment by robmadole** [comment]
This should now be resolved. I've removed the minification. If anyone has any further problems then we'll re-open or create a new issue.
