### ISSUE TITLE
Bug: Carpool Sharp Duotone Solid has round wheels unlike non-Duotone and other styles

### ISSUE THREAD

**Issue by espada-edalex** [FortAwesome/Font-Awesome#20420]
### Bug description

The Solid version of the Carpool Sharp Duotone icon is the only one with rounded wheels.

## Carpool Sharp Duotone (Solid)

![image](https://github.com/user-attachments/assets/23d1904a-cd64-4862-831d-5c7a94ff7374)

## Carpool Sharp Duotone (others)

| Regular | Light | Thin |
| - | - | - |
| ![image](https://github.com/user-attachments/assets/ac73d3c3-3401-4e3b-8c6b-de6eb0581457) |![image](https://github.com/user-attachments/assets/bf4efcfa-e0a2-404f-b352-f62e900ac426) | ![image](https://github.com/user-attachments/assets/c5471642-40a2-4118-9efb-398126e9adc7) |

## Carpool Sharp

| Solid | Regular | Light | Thin |
| - | - | - | - |
| ![image](https://github.com/user-attachments/assets/6b9f1fff-e711-4399-a56d-cadd199ae95c) | ![image](https://github.com/user-attachments/assets/da295fa6-d53d-46dc-8761-cb3df784159c) |![image](https://github.com/user-attachments/assets/2df24b67-6c3c-414d-8c1f-62817228c78a) | ![image](https://github.com/user-attachments/assets/0343b1f4-b976-41f6-89f0-4e5fada686c6) |

### Font Awesome version

v6.7.0

### Serving

Other (as specified in the bug description)

### Implementation

SVG Sprites

### Browser and Operating System

- N/A

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by sensibleworld** [comment]
Thanks for the report! This is fixed in 6.7.1: https://fontawesome.com/icons/carpool?f=sharp-duotone&s=solid
