### ISSUE TITLE
Icon Request: Candy Box Menu

### ISSUE THREAD

**Issue by turingvsclarke** [FortAwesome/Font-Awesome#20428]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

Creating a quick little Google page emulator and see hamburger menu icons for list-based menus, but nothing for grid-based menus, such as Google app selection. 

### Visual example

![image](https://github.com/user-attachments/assets/6f58c894-6057-4257-909e-2b5c5217782d)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

icon grid-round has been added to FontAwesome Pro in version 6.40:
- https://fontawesome.com/icons/grid-round?f=classic&s=solid

In Font Awesome Free, you have an alternative that can suite this use case: https://fontawesome.com/icons/grid?f=classic&s=solid

Original request: #15452

A useful answer from FAQs:

> ### Why are some (highly requested) icons not available in Font Awesome Free?
>
> Font Awesome began as a free resource and it's important to us that there will always be a free version of it that is more-than-usable by anyone who needs icons. But we built a team to make sure we continue to add icons, features, and make Font Awesome, well, awesome. That team is full of great people who help make our icons and products - but they're also folks with bills, kids, and dreams of their own that require a salary.

Hope it helps, closing here but feel free to comment
