### ISSUE TITLE
symbol has already been declared in another package

### ISSUE THREAD

**Issue by dabbabi** [FortAwesome/Font-Awesome#20434]
Dear
Starting from version 6.7.0, I'm getting a compilation error in my angular project using both packages @fortawesome/fontawesome-free version greater than 6.6.0 and package luxon (any version).
Below the error:

X [ERROR] The symbol "s" has already been declared (in package @fortawesome/fontawesome-free)

    angular:script/global:scripts.js:23:1951:
      23 │ ...asdt:"thin","fa-thin":"thin"}},s="classic",Z1={fak:"kit","fa-ki...
         ╵                                   ^

  The symbol "s" was originally declared here (in package luxon):

    angular:script/global:scripts.js:156:2:
      156 │   s = "short",
          ╵   ^

I know that this is an uncommon issue report, but is it possible to change the name of s variable so we may coexist both packages, please?

All the best

**Comment by tagliala** [comment]
I think this is related to #20424 and #20423

**Comment by robmadole** [comment]
This should be fixed now with 6.7.2. @dabbabi if you find out otherwise we'll re-open the ticket.

Thank you for reporting this.
