### ISSUE TITLE
Icon Request: icon-horse

### ISSUE THREAD

**Issue by VetApps** [FortAwesome/Font-Awesome#2049]
Hello.

First of all i want to thank you for this nice work you have made <3 It.

Well here is my request:
- icon-horse (or any domestic animal)
- I'm planning to use it in 2 or 3 apps for veterinaries and Pet owners
- I think its ok just with the face of the animals a few googled images here
  http://www.istockphoto.com/stock-illustration-17927532-farm-animal-icons.php
  and it would be nice if there is a plus, minus and edit or pencil icon for each.

Thank you very much

**Comment by Dromin** [comment]
+1

**Comment by mbequine** [comment]
+1

**Comment by nilsmunch** [comment]
+1 here as well, would even throw coins after it :)

**Comment by mgrenson** [comment]
+1

**Comment by monkeython** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by somethingworks** [comment]
+1

What is the status?
This topic is almost running 5 months...

**Comment by tagliala** [comment]
@somethingworks this is not a popular request.

It doesn't mean that it is going to be ignored or it doesn't have chance of being included in the set but I should advise you to take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#new-icons

**Comment by farukscan** [comment]
+1 animal icons

**Comment by lulango** [comment]
Hi
+1
horse please!

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/280#issue-5075477

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/280#issuecomment-6337310

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/280#issuecomment-70398626

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/280#issuecomment-90258836

**Comment by kesaven** [comment]
+1

**Comment by d3orn** [comment]
+1

**Comment by zumbrunnen** [comment]
+1

**Comment by ninfaj** [comment]
+1 :horse:

**Comment by haslo** [comment]
A horse would be great!

**Comment by highliner** [comment]
+1 :horse:

**Comment by mmhu** [comment]
+1

**Comment by larsvanpoucke** [comment]
+1

**Comment by annaoleksiuk** [comment]
+1

**Comment by jswainosd** [comment]
+1

**Comment by max4kaps** [comment]
+1

**Comment by optimalisatie** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by Baskerville42** [comment]
+1 Very need! =)

**Comment by pppplus** [comment]
+1

**Comment by mshovelt** [comment]
+1

**Comment by ovation22** [comment]
+1

**Comment by vicary** [comment]
+1

**Comment by szabogyula** [comment]
+1

**Comment by daviddrm45** [comment]
+1

**Comment by matheusilario** [comment]
+1

**Comment by Truoris** [comment]
+1

**Comment by jennyanthony** [comment]
+1

**Comment by NBillings707** [comment]
+1

**Comment by hberton** [comment]
+1

**Comment by vlasvlasvlas** [comment]
where's my horse! :)

**Comment by Crissov** [comment]
JFTR, the related Unicode emojis are these:

* 🐎 U+1F40E
* 🐴 U+1F434
* 🏇 U+1F3C7
* 🦄 U+1F984 → #2780

**Comment by saniaja** [comment]
+1

**Comment by Brieg** [comment]
+1

**Comment by tde-banana-odoo** [comment]
+1

**Comment by vlasvlasvlas** [comment]
+1

**Comment by rafanake** [comment]
+1

**Comment by rokinroj** [comment]
+1

**Comment by Cymo-** [comment]
+1

**Comment by StephaneJuban** [comment]
+1

**Comment by Soaku** [comment]
+1 

Would be nice to see a horse icon as a chessman.

**Comment by Soaku** [comment]
By the way, if you want to use a symbol for *animal*, use `fa-paw`.

**Comment by peter-hank** [comment]
+1 for fa-ponies

**Comment by BenoitNorrin** [comment]
+1

**Comment by net-x** [comment]
+1

**Comment by smartens80** [comment]
+1

**Comment by Baroquenz** [comment]
+1
Could we please have a horse some time soon? A few more animals would be nice too especially for those of us making animal related websites

**Comment by enter1010** [comment]
+1

**Comment by dwhaas82** [comment]
+1

**Comment by rogueclown** [comment]
+1 for icon-horse.  i'm using FontAwesome on a site, and my "main" website is all horse racing writing -- making a horse icon a natural fit.  there are a few animals already (and a *lot* of sports icons already!), and i was disappointed to see nothing with a horse, or about horse racing.

thanks!

**Comment by bitedgecom** [comment]
+1

Disappointing there is no horse.

**Comment by Fatbat** [comment]
+1 for generic horse icon. Also specific for horse racing and equestrian.

**Comment by soeren487** [comment]
+1 for generic horse icon. Also specific for horse racing and equestrian.

**Comment by mxzgithub** [comment]
+1

**Comment by stobenski** [comment]
+1

**Comment by StephaneJuban** [comment]
![screen shot 2018-10-03 at 14 58 51](https://user-images.githubusercontent.com/2980518/46411753-dfa5d900-c71c-11e8-8c18-4534cdf0c9f1.png)
Is it really happening after more than 5 years of waiting ???? 😱
Go get the Champagne ready... 🍾

**Comment by onepack** [comment]
Really needed this one. A lot of more animals are needed actually besides horse. Standard farm-animals, standard pets and perhaps Standard zoo animals like, monkey, elephant, lion, tiger and snake.

**Comment by sensibleworld** [comment]
We've finally added a horse! https://fontawesome.com/icons/horse?style=solid

**Comment by StephaneJuban** [comment]
Thanks, great work !

To push the button further again 😇, any chance to have a icon with just the horse head like [this](https://iconscout.com/icon/horse-7) or [this](https://imageog.flaticon.com/icons/png/512/32/32904.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF) ?

**Comment by Baroquenz** [comment]
Fantastic! Thanks so much!

**Comment by Fatbat** [comment]
> Thanks for the feedback!
> 
> @Fatbat A racing horse is slightly different than what was requested. If it's something you need and has support among the community, could you open a new icon request issue?
> 
> @StephaneJuban Same goes for the horse-head icon!
> 
> Would love to add both!

It had been requested mate, in the sports section, along with things like rugby and snooker, but I can't find the posts now. I'll make new ones I guess.

**Comment by dwhaas82** [comment]
Ya, i saw that horse race and rugby were requests as I had also submitted
requests for those.
