### ISSUE TITLE
Documentation: Minor typos in Changelog for 6.7.0

### ISSUE THREAD

**Issue by alexdgs** [FortAwesome/Font-Awesome#20499]
On the [Changelog page](https://fontawesome.com/changelog), in the "Fixed" section for version 6.7.0:
- The 5th entry has a missing "c" for "circle-left".
- The 6th entry has a couple backticks surrounding "fa-duotone fa-solid", but these look a bit off and most likely the surrounded text should render as code but it is not.

![image](https://github.com/user-attachments/assets/d5eb9145-b84a-456d-86a9-8a45050433ee)

_By the way, Happy Holidays for the FA team!_

**Comment by robmadole** [comment]
Thanks @alexdgs ! Happy Holidays to you too. We'll get this fixed with the next release.
