### ISSUE TITLE
Icon Request: Kurdistan flag 

### ISSUE THREAD

**Issue by sardar97** [FortAwesome/Font-Awesome#20505]
### Checklist

- [X] The title of this issue starts with "Icon Request: " and is followed by the new icon name *(ex. "Icon Request: Proton Torpedo")*
- [X] This icon does not represent a brand
- [X] This request is for a single icon or a matched pair *(ex. `lock` and `unlock`)*
- [X] I've already [searched through existing issues](https://github.com/FortAwesome/Font-Awesome/issues), and to the best of my knowledge this request isn't a duplicate
- [X] I understand [how new icon requests work](https://fontawesome.com/support#requesting-icons)

### Request type

✨ New icon

### Use case

can be used for **Kurdish** language.
Kurdistan is a region from Iraq however there are more than 40 million Kurdish people around the world.
Kurdish language = ckb
then so the flag name should be "fa-flag-ckb".

[Kurdistan flag svg](https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Kurdistan.svg)

### Visual example

![Flag_of_Kurdistan svg](https://github.com/user-attachments/assets/475f8912-27ad-44c2-a68c-176fb4db3d4d)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

We are tracking requests for country flags at #20288

Closing here
