### ISSUE TITLE
Bug: Auth token issue Invalid authentication (as an unknown user)

### ISSUE THREAD

**Issue by floviolleau** [FortAwesome/Font-Awesome#20515]
### Bug description

Hi,

We have an issue with Font Awesome Pro, our perpetual auth token does not work anymore since yesterday.

We use yarn 4.5.3 to install and got the following error :

```bash
➤ YN0041: │ @fortawesome/fontawesome-pro@npm:^6.5.0: Invalid authentication (as an unknown user)
```

Tried with npm directly, same issue :

```bash
npm install @fortawesome/fontawesome-pro --registry=https://npm.fontawesome.com/ --auth-token=XXXXXXXX-XXXX-XXXX-XXXX-XXXX

npm ERR! code E401
npm ERR! Incorrect or missing password.
```

Everything was working before yesterday, I didn't see any changes on our side.

Can you check and update ?

Thanks for your help

### Font Awesome version

v6.5.2

### Serving

Kit

### Implementation

SVG+JS

### Browser and Operating System

alpine: 3.20.3
nodejs: 21.7

### Web bug report checklist

- [X] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Did you try to send an email to hello@fontawesome.com? 

Unfortunately on the free repo issue tracker is not the best place for what looks like an authentication issue

**Comment by floviolleau** [comment]
Hi,

Yes I did it as well :wink:.

**Comment by tagliala** [comment]
Thanks, feel free to ping me if you don't receive an answer in a reasonable amount of time

**Comment by floviolleau** [comment]
Thanks.

We've got an answer from support.

Seems that we are missing money on our account.

Take care
