### ISSUE TITLE
Icon Request: fa-icon video editor

### ISSUE THREAD

**Issue by aaddi225** [FortAwesome/Font-Awesome#20511]

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Please fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+), and provide a single color, small size suitable example of the icon you are requesting

Closing here, but feel free to comment if I've missed something
