### ISSUE TITLE
Icon Request: bible icons

### ISSUE THREAD

**Issue by theartofsiku** [FortAwesome/Font-Awesome#2053]
Hiya peeps,
anyone interested in colaborating with me on creating bible icons?
I am an artist-tehologian working with the bible and images. I am the writer/artist of The Manga Bible.

I am interested with working with coders or artists who are interested in creating a comprehensive database of bible icons,schema, patterns and motifs; in particular, conceptual motifs that encapsulate complex thought.

my website; www.thaeartofsiku.com

peace
Siku

**Comment by BrazenlyGeek** [comment]
I would love to see icons for the world's primary religions & worldviews included -- the common various types of crosses/ankh, menorah, Christian fish, star of David, yin yang, star & moon, tulip (Calvinism), upside-down cross (Catholicism), pentagram, baphomet, pansy flower (free-thought), the stylized A for atheism, the humanist "H" icon, and so on.

**Comment by tagliala** [comment]
Sorry, I have to close this request

It does no longer meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by Guestrevu** [comment]
A set of all religions icons will be very useful, I work on a lot of school websites and religion is an important icon especially in a multi cultural society, governmental websites and census websites also use this a lot. In travel websites we sometimes need to indicate if the property have a Muslim prayer room, wedding venue or chapel, or if the food is halal, I often wondered why this was not available long time ago :) You don't need to be religions to see the need for this in a range of industries.

**Comment by Wingo5315** [comment]
+1. This would be very useful for a homework help website I run.
