### ISSUE TITLE
Icon Purchase Request

### ISSUE THREAD

**Issue by michaelamin** [FortAwesome/Font-Awesome#2054]
I would like to purchase unique icons from you for my software. The icons posted on your site do not offer everything i offer. thus i would like to purchase 3-4 new icons. 

Thanks,
Michael

**Comment by sensibleworld** [comment]
Hi @michaelamin. Apologies for missing this old comment. If our current icon offerings at fontawesome.com don't fit the bill, send us a note at hello@fontawesome.com and we can chat details.
