### ISSUE TITLE
Icon request: icon-check-unknown (tristate / indeterminate)

### ISSUE THREAD

**Issue by mar10** [FortAwesome/Font-Awesome#2055]
I would like to have a simple way to implement tri-state checkboxes.

Use cases:
- Indicate partial selection in trees (i.e. parent node is 'partly selected', if only some children are checked)
- In Indicate 'indetermintate' or 'n.a. (does not apply) in check lists

Currently I use a icon-check with icon-muted, but that looks like a hack ;-)

**Comment by yaugenka** [comment]
+1 Here is an example 
![checkbox-partial-36-000000](https://cloud.githubusercontent.com/assets/14937001/11130889/971236e4-8998-11e5-9160-586c9d8db911.png)

**Comment by LitoGoSt** [comment]
+1
Is there a way to achieve this with the current icon set?
An **fa-partial-check** icon like the one @yaugenka shared, would be really useful to me.
I would combine it with fa-check-square-o and fa-square-o like in the example given above.
Thanks

**Comment by kkuhnen** [comment]
+1 
It's possible to achieve this kind of indeterminate checkbox by stacking two icons, i.e.: https://codepen.io/kkuhnen/pen/RBLdpp

**Comment by tagliala** [comment]
FWIW, some browsers use [minus-square](https://fontawesome.com/icons/minus-square?style=solid)

Also bootstrap's custom checkbox uses that icon https://getbootstrap.com/docs/5.0/forms/checks-radios/#indeterminate

**Comment by tagliala** [comment]
Closing here. 

If you need a variant with a square, please +1 #17641
