### ISSUE TITLE
Icon Request: icon-trip-advisor

### ISSUE THREAD

**Issue by MarthSantos** [FortAwesome/Font-Awesome#2061]
I would like to request the Trip Advisor Icon.
http://www.userlogos.org/files/logos/ali.senan/Tripadvisor.png

Use case:
For hotel websites that has Trip Advisor reviews.
Sample site: http://www.marmara-manhattan.com/upper-east-side/index.html

**Comment by ahtaha** [comment]
+1

**Comment by epokos** [comment]
+1

**Comment by tagliala** [comment]
dup of #1366, locking
