### ISSUE TITLE
Icon Request: select-all

### ISSUE THREAD

**Issue by lucasmendonca** [FortAwesome/Font-Awesome#2063]
Icon for select multiple values in the list.

**Comment by SylvainCorlay** [comment]
Or select all text, for text-editor type of features:

![tango_edit_select_all_thumb](https://cloud.githubusercontent.com/assets/2397974/6958031/9272b04e-d8d3-11e4-8a8b-478a5c8e06be.png)

**Comment by gramx** [comment]
I was thinking something along the lines of this, though that may be colser to check all and not select all.
![selectall](https://cloud.githubusercontent.com/assets/6108820/10618651/51732f7a-772e-11e5-9e81-4cfe86955405.png)

**Comment by Giswald** [comment]
Any news on this? :+1:

**Comment by suhuichen** [comment]
+1

**Comment by WACMemphis** [comment]
+1

**Comment by jhenriquemc** [comment]
+1

**Comment by GameCharmer** [comment]
+1

**Comment by akuznetsov-gridgain** [comment]
+1

**Comment by bkd** [comment]
+1

**Comment by shahzad31** [comment]
+1

**Comment by wizkidweb** [comment]
+1

**Comment by chellberg** [comment]
+1

**Comment by glueball** [comment]
+1

**Comment by cdfa** [comment]
+1

**Comment by schowes** [comment]
+1

**Comment by anasdawood** [comment]
+1

**Comment by jakubste** [comment]
+1

**Comment by clabnet** [comment]
+1

**Comment by markmarco16** [comment]
+1

**Comment by yoihito** [comment]
+1

**Comment by janmichaelyu** [comment]
+1

**Comment by ulybu** [comment]
Personally I use this snippet to produce "select all checkbox" :

```html
<div style="height: 1em; width: 1em;">
  <i class="fas fa-square"            style="position: absolute; top: 0px; left: 0px;"/>
  <i class="fas fa-square fa-inverse" style="position: absolute; top: 2px; left: 2px;"/>
  <i class="far fa-check-square"      style="position: absolute; top: 3px; left: 3px;"/>
</div>
```

![image](https://user-images.githubusercontent.com/2479249/37110287-c7cb15f0-223c-11e8-88ca-109ca1f02b6b.png)

**Comment by ulybu** [comment]
For the "check all" (and not "select all"), you can find a snippet in this comment: https://github.com/FortAwesome/Font-Awesome/issues/2104#issuecomment-371238218

**Comment by MichaelTunnell** [comment]
Here is my suggestion of what the Select All icon should be. I used the fa-align-left icon in the center and then dashes for the box like a graphics program select tool.

![select-all-icon-suggestion-fontawesome](https://user-images.githubusercontent.com/1056731/77479503-eb43fe80-6ded-11ea-8e48-2f0a9f4ec1b4.png)
