### ISSUE TITLE
Icon Request: icon-brain

### ISSUE THREAD

**Issue by TysGibbons** [FortAwesome/Font-Awesome#2075]
I would like to request a brain icon.

**Comment by mr-linch** [comment]
+1

**Comment by Caine85** [comment]
+1

**Comment by kruser** [comment]
:+1:

**Comment by G-Driver** [comment]
+1

**Comment by fedepernot** [comment]
+1 Pleaseee!!!
![brain8](https://cloud.githubusercontent.com/assets/11669145/6854189/7492f5de-d3ce-11e4-811a-2bbed6100609.png)

**Comment by Kurosaki87** [comment]
+1 = perfetct

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1306#issue-15568957

**Comment by Kurosaki87** [comment]
+1s

**Comment by Chelen** [comment]
+1

**Comment by kinzdesign** [comment]
+1

**Comment by JuanDelgadillo** [comment]
+1

**Comment by dignati** [comment]
+1

**Comment by dangelion** [comment]
+1

**Comment by allanino** [comment]
+1

**Comment by cravindra** [comment]
+1 for a brain icon

**Comment by tareq-halaby** [comment]
+1 for brain icon

**Comment by tareq-halaby** [comment]
+1

**Comment by bekatama** [comment]
+!

**Comment by AdamForst** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by hayseed** [comment]
+1

**Comment by QueenMerla** [comment]
+1

**Comment by atlantawebco** [comment]
+1

**Comment by qu0te** [comment]
+1

**Comment by ndrewh** [comment]
+1

**Comment by alansferreira** [comment]
+1

**Comment by scheriam** [comment]
+1

**Comment by ekrul** [comment]
+1

**Comment by manureggi** [comment]
+1

**Comment by sureshgururajan** [comment]
+1

**Comment by lucasminissale** [comment]
+1

**Comment by wiebedijkstra** [comment]
+1

**Comment by leotm** [comment]
+1

**Comment by ugurcany** [comment]
+1

**Comment by JMoli** [comment]
+1

**Comment by ranesr** [comment]
+1

**Comment by joshuagruenstein** [comment]
+1

**Comment by Potatopat** [comment]
+1

**Comment by richstrauss** [comment]
+1

**Comment by talski** [comment]
+1

**Comment by chasemcaleese** [comment]
+1

**Comment by inakil** [comment]
+1

**Comment by sindhuh** [comment]
+1

**Comment by Crissov** [comment]
U+1F9E0 in Unicode 10.0 probably #222

http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f9e0

**Comment by younessadmi** [comment]
+1

**Comment by sspsmorrissey** [comment]
+1

**Comment by zwarburg** [comment]
+1

**Comment by monzerhijazi** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by araymoises** [comment]
+1

**Comment by CJKinni** [comment]
+1

**Comment by MZellhofer** [comment]
+1

**Comment by briavicenti** [comment]
+1

**Comment by penkin** [comment]
+1

**Comment by fctucker** [comment]
+1

**Comment by Mylogin-info** [comment]
+1

**Comment by bundgaard** [comment]
+1

**Comment by cedricve** [comment]
+1

**Comment by CouchFrancois** [comment]
+1

**Comment by WaynePhipps** [comment]
+1

**Comment by richmondazarraga** [comment]
+1

**Comment by tanluongann** [comment]
+1

**Comment by Eduardoveras** [comment]
+1

**Comment by Vioner** [comment]
+1

**Comment by crocodoyle** [comment]
+1

**Comment by David-R-Guymon** [comment]
Why is there NO Brain icon in Font Awesome version 4.7.0 ?
There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon! There is not Brain Icon!

**Comment by kimberley-johnston** [comment]
+1

**Comment by shawnps** [comment]
+1

**Comment by sebastianstoll97** [comment]
+1

**Comment by neotrope** [comment]
+1 !

**Comment by Notoncebut2x** [comment]
+1

**Comment by cfeltch537** [comment]
+1

**Comment by adilbo** [comment]
+1

**Comment by gunnar2k** [comment]
+1

**Comment by AbbyJanke** [comment]
Any traction on this? Been a while. +1

**Comment by paulrougieux** [comment]
I think that the brain viewed from above is a more common representation.

![brain](https://user-images.githubusercontent.com/5647397/34994146-e0c24452-fad2-11e7-9afe-6240ba1c2270.png)

([image source](https://commons.wikimedia.org/wiki/File:User-FastFission-brain.gif))

**Comment by stefcab** [comment]
About the request the **fa-brain request**, I propose you a **top and side brain views**:


![brain_top](https://user-images.githubusercontent.com/4100053/38902781-5bf5312e-4278-11e8-802f-94cbb4b7b139.png)
![brain_side](https://user-images.githubusercontent.com/4100053/38902789-6429d4b2-4278-11e8-84b0-1dc75cfb59ef.png)

**Comment by AndreaPappi** [comment]
+1

**Comment by earthcomedy** [comment]
+1

**Comment by Flora140** [comment]
+1 Please need a brain, Zombie took mine

**Comment by JuanDelgadillo** [comment]
I opened a new issue https://github.com/FortAwesome/Font-Awesome/issues/13219 referencing this one to bring attention to this, since it has been requested by many people and this has been open for almost 5 years.

**Comment by Flora140** [comment]
Thanx

Regards,
Flora Makgaba

Contact Details :
Cell : 073 974 9776
Alternative email : mkgflo001@myuct.ac.za
Facebook : https://www.facebook.com/flora.makgaba.5

**Comment by sensibleworld** [comment]
Hey folks! We’re getting back on track with requested icons. You can follow along with progress and recent releases here: https://fontawesome.com/community/leaderboard/released

**Comment by JuanDelgadillo** [comment]
Thank you @sensibleworld for taking this one 👍🏻

**Comment by gatekeeperapps** [comment]
👍🏻

**Comment by martinandrino** [comment]
+1

**Comment by adamkool** [comment]
+1

**Comment by JuanDelgadillo** [comment]
Thanks @sensibleworld for making it happen https://fontawesome.com/icons/brain?style=solid 🎉
