### ISSUE TITLE
Icon Request: icon-new-doc

### ISSUE THREAD

**Issue by texjer** [FortAwesome/Font-Awesome#2081]
I think I've attached an icon that shows what I'm thinking.  I can think of a few use cases, like start a new document, or start a new anything really.  

![screen shot 2013-10-02 at 9 43 28 am](https://f.cloud.github.com/assets/513709/1253634/a5000046-2b68-11e3-86b7-2e997c721e7d.png)

**Comment by aethior** [comment]
Hi @texjer,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/file-circle-plus

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Just noticed it is the original request of #3041

I've commented on #3041 how it is possible to achieve this icon in FA free
