### ISSUE TITLE
Icon Request: icon-cube-o

### ISSUE THREAD

**Issue by texjer** [FortAwesome/Font-Awesome#2082]
Just an isometric cube, I'm going to be using it for "Export 3D Drawing" for architectural uses, but it could also be used for a variety of object-related thoughts.

**Comment by rcrisp** [comment]
+1 for 3d cube (see image reference from closed issue above)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/cube?s=regular
