### ISSUE TITLE
Icon Request: icon-soundwave

### ISSUE THREAD

**Issue by ehutch79** [FortAwesome/Font-Awesome#2084]
Icon to denote music files in a backend for management of a band website. a wave of increasing amplitude would be a good generic icon with more uses than just this one application.

![soundwave-example](https://f.cloud.github.com/assets/802936/1254221/2e9a6c52-2b72-11e3-95b3-e07807cd790e.jpg)

**Comment by brioux** [comment]
+1 

looking for something simple

like this

![image](https://cloud.githubusercontent.com/assets/5202700/7299712/3acaac16-e9e0-11e4-9298-a9226c753ebd.png)

**Comment by AndreLGava** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/waveform-path?style=solid
