### ISSUE TITLE
Icon Request: icon-church

### ISSUE THREAD

**Issue by GermanKiwi** [FortAwesome/Font-Awesome#2088]
I'd love to have a church icon - depicting a church building. This would be very useful for using with the countless church websites that exist.

Something like this would do the trick for me:

![churchicon](https://f.cloud.github.com/assets/1030242/1893005/93831d70-7a65-11e3-9eaa-69444bde5d3b.png)

This one looks really good at all sizes, including when it's small, and it has a nice mix of both black and white, which is similar to many of the other Font Awesome icons.

And I like that the cross doesn't stick up too high above the top of the roof - I've seen some other church icons which have a very tall steeple above the roof, but that makes the church building itself, below the steeple, comparatively smaller which isn't so good. The one I've depicted above allows the church building to take up the majority of the height of the image, with just a small bit of the height taken up by the cross on top. So it's closer in size to the existing "fa-home" icon, in terms of the height of the two buildings.

I would, however, prefer the cross to have square edges rather than rounded edges - I think that would look better. I'd also suggest giving the upper window square edges too, to make its edges more defined especially in smaller sizes.

---

**UPDATE:**

@zuck suggested an alternate style based on the existing Home icon, which I really like. You can follow our discussion in the thread below.

Therefore I'd like to request something like this icon below, rather than my previous suggestion above. I think this one fits much better with the overall style of Font Awesome:

![churches-new](https://cloud.githubusercontent.com/assets/1030242/12766317/8bd83d9a-ca03-11e5-9558-736ae7005f5b.png)

**Comment by maddhatter** [comment]
+1

**Comment by StellaLuc** [comment]
Any movement on this?  I'm working on a church website and this would be perfect.  Let us know.  Thanks.

**Comment by ghadeerrahhal** [comment]
+1

**Comment by sebastienguay** [comment]
+1

**Comment by sealdriver** [comment]
+1

**Comment by yieme** [comment]
+1

**Comment by millerbrother2** [comment]
+1

**Comment by boydspace** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by mirdala** [comment]
+1

**Comment by GwenLoguir** [comment]
+1

**Comment by wildfireheart** [comment]
+1

**Comment by detroitnc** [comment]
+1

**Comment by sykaeh** [comment]
+1

**Comment by faustomorales** [comment]
+1

**Comment by timvanwolfswinkel** [comment]
+1

**Comment by karkkaz** [comment]
+1

**Comment by iAmSimplicit** [comment]
+1

**Comment by andr0man** [comment]
+1

**Comment by didoulr** [comment]
+1

**Comment by jonatascastro12** [comment]
+1

**Comment by Daut** [comment]
+1

**Comment by jsc3582** [comment]
+1

**Comment by jsc3582** [comment]
Need this one!!

**Comment by misterch0c** [comment]
+1

**Comment by imjohnbo** [comment]
@GermanKiwi, where did the church icon you uploaded come from? May it be used under a certain license? By cropping and inverting the colors, it is exactly what I need. Just want to give credit where credit's due.

**Comment by GermanKiwi** [comment]
It's a generic church icon that I found online somewhere, but I'm afraid I don't remember where or whether it was licensed. It was not part of any corporate or trademarked logo though. And I believe it's generic enough that it could be reproduced by Font Awesome (and in any case, Font Awesome already includes many other trademarked icons anyway, like Facebook and Google etc.)

**Comment by imjohnbo** [comment]
Thanks anyway. It's not Font Awesome, but in the meantime...

<img width="472" alt="church icon - black" src="https://cloud.githubusercontent.com/assets/2993937/8800271/b7577b9e-2fb1-11e5-92e3-a96d0a416373.png">
<img width="472" alt="church icon - white" src="https://cloud.githubusercontent.com/assets/2993937/8800272/b77865de-2fb1-11e5-95cf-8bc717db2dd7.png">

**Comment by TechWilk** [comment]
+1

**Comment by lyhil** [comment]
+1 for something more like cathedral
like https://d30y9cdsu7xlg0.cloudfront.net/png/11885-200.png
or  http://comps.canstockphoto.com/can-stock-photo_csp5039356.jpg
you know, with this long low part and towers above it

**Comment by GermanKiwi** [comment]
@lyhil you should create a new issue for that, then, as it's a separate icon from the one being requested here.

**Comment by keithics** [comment]
+1

**Comment by circlecube** [comment]
+1

**Comment by geodeveloper** [comment]
+1

**Comment by roddharris** [comment]
+1

**Comment by heyjoecampbell** [comment]
+1

**Comment by vineethkrishnan** [comment]
+1

**Comment by gecche** [comment]
+1

**Comment by debbing** [comment]
+1

**Comment by jonatascastro12** [comment]
+1

**Comment by Mihailiuc** [comment]
+1 on this one!

Please give a +1 to this one also, is refereed also to Christians
https://github.com/FortAwesome/Font-Awesome/issues/8239  (for doctrinal statement)
https://github.com/FortAwesome/Font-Awesome/issues/8240 (cross)
https://github.com/FortAwesome/Font-Awesome/issues/8123 (bible)

**Comment by CarlosHAraujo** [comment]
+1

**Comment by ewillstudios** [comment]
+1

**Comment by zuck** [comment]
+1 for the request, but IMHO the proposed concept is the wrong way...

![Example1](http://icons.iconarchive.com/icons/icons8/windows-8/128/Holidays-Church-icon.png)
![Example2](http://marriage-wedding.com/material/004.png)
![Example3](https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/church.png)
![Example4](https://cdn0.iconfinder.com/data/icons/black-religious-icons/256/Catholic_church.png)
![Example5](http://thumb9.shutterstock.com/display_pic_with_logo/2680369/309569282/stock-vector-church-icon-silhouette-309569282.jpg)
![Example6](http://www.nowisthetimeny.org/files/icons/Church%20Icon_Gold-01.png)

**Comment by GermanKiwi** [comment]
In what way is it the wrong way? And how is the proposed concept any different, stylistically, to the myriad of images you've posted above? You haven't given any reasoning to support your opinion. Furthermore, many of the images you've posted here will not work very well in very small sizes - they'll be indistinguishable, because they are too tall.

Also, please note that this thread is a request solely for a church icon, and not an icon of a Bible or a priest or a nun or a cross on a hill. Please keep alternate designs on topic, and create new threads for other icons.

**Comment by zuck** [comment]
@GermanKiwi 

First of all, sorry, I didn't cut the multi-image to remove the icons not related to this request, my fault.

By the way, with "wrong way" I mean that in my opinion, instead of an outlined icon like the original proposal, it's better to represent a building like a church with a bold icon (like *fa-building*), with a very evident cross on it and possibly with a bell tower or a style more similar to a cathedral. Clear and simple.

For sure the references I posted are not perfect at all (too tall, still too complicated, etc.). I linked them just a a reference to highlight my suggestion: bold building, bell tower, cross on it.

**Comment by GermanKiwi** [comment]
Yup, valid point. FWIW, my proposal isn't intended to be an actual outlined version (akin to the other outlined icons that Font Awesome already has) - it has a solid roof, and I think the idea was to depict a typical white-coloured lower half. I think it would be tricky to show that middle arch doorway without it being white like that. But I didn't design it myself, I found it online somewhere and I liked it because it represented a fairly stereotypical country church (I personally didn't want a grand cathedral).

My main test, though, when I was searching online for ideas, was to reduce the ones I found down to about 18-20px high or so, and see how distinguishable they looked - did they still look like a church, or just a regular building or house? Was the cross still clear and sharp? In most cases the answer was no, usually because they were too tall and therefore looked minuscule at 18px, but the one I included here came closest to meeting that requirement for me.

Another thing I liked about it was that it wasn't too dissimilar from the fa-home icon, and it would therefore serve nicely as an actual Home icon/button on church websites, eg. on a menu at the top of the page. A cathedral wouldn't work quite so well for that purpose, IMO.

I like the first icon of the examples you've posted - although I dunno how well it will work when it's very small. Perhaps the cross could be removed from on top of the roof, and put in place of the circular window above the door.

However, I think I still prefer the one I posted most of all. :)

**Comment by G-Driver** [comment]
+1

**Comment by voidstate** [comment]
+1

**Comment by voidstate** [comment]
Also, icons for mosque, synagogue, gurdwara, hindu temple, etc.

**Comment by GermanKiwi** [comment]
@voidstate as explained at http://fontawesome.io/community/ "Please make requests for single icons" - in other words, please create your own separate Github issues for the other icons you want to request.

This particular issue/thread is specifically and solely for a church icon, as suggested in the top post. This request is independent and unrelated to any other request for other types of building such as those from other religions.

**Comment by zuck** [comment]
Just to explained better my point, these are the official street signs for churches and parishes in Italy:

![Church1](http://www.vegal.it/upload/fotogallery/00000096/1_p.jpg)
![Church2](https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Chiesa_di_San_Leonardo,_cartello_informativo_(Correzzola).JPG/450px-Chiesa_di_San_Leonardo,_cartello_informativo_(Correzzola).JPG)
![Church3](http://www.movingitalia.it/immagini/italia/sassari/ozieri/3-1414768063.jpg)

For sure the tower is a little bit too high, but with some small changes we can obtain the following one, which is quite coherent with the house icon and, in my opinion, works quite well for both local country churches or big cathedrals:

![church-icon](https://cloud.githubusercontent.com/assets/1370938/12615619/060c2182-c507-11e5-8e03-c23b67782529.jpg)

**Comment by GermanKiwi** [comment]
You know what? I really like that a lot! I mean the one you have at the bottom. Did you create that one yourself?

Do you think you could make a couple of different sizes of it, for comparison? One that is bigger, and one that is smaller - I'd like to see how it looks when it's 24 pixels tall.

Maybe you can make the edges of the roof slightly rounded, just like the roof of the current Home icon. And possibly lower the height of the steeple by a pixel to see what difference that makes - it might help with letting the overall size of the building (excluding the steeple) be a bit bigger in comparison, when the steeple is a fraction shorter?

Then we can ask the developer if he'd consider this one - I think it's nicer and more in line with the overall Font Awesome style, than the one I found! :)

**Comment by zuck** [comment]
![church](https://cloud.githubusercontent.com/assets/1370938/12729827/e9530940-c928-11e5-9994-84dea725d097.png)

**Comment by GermanKiwi** [comment]
That looks pretty good!

I've taken the liberty of making a very small adjustment to what you've created above. I've made the white cross a tiny bit thinner, with the horizontal beam of the cross not quite so wide, so that it's closer to the cross in your original version three comments above - I think that cross has better proportions (a little taller, a little narrower).

I also made the steeple window rectangular. I think it scales better when the edges are at 90° like that.

What do you think of this? The smallest one is 24px tall.

![churches](https://cloud.githubusercontent.com/assets/1030242/12735352/727b2e28-c947-11e5-9946-9a55a04c1119.png)

**Comment by zuck** [comment]
Nice! I started from the home icon too.

I agree regarding the steeple window: rectangular is better.

I also prefer a thinner cross but in my design I tried to make it bolder in order to improve recognition at very small sizes. But maybe I stressed this point too much, so yours should be fine...

Regarding the steeple, in my opinion we should make it just a little bit taller and thicker, more or less like in the version I posted (which itself is lower than the first one I posted). The reason is that it should be _visually different_ from a chimney.

The same for the roof: we can try to find an half-way to make its edges shorter in order to differentiate it from the regular house.

We're almost there... ;)

**Comment by GermanKiwi** [comment]
Yup, I like that! Here's your latest iteration in different sizes. Still looks good at a height of 24px too, which is the height I'm using on my website:

![churches-new](https://cloud.githubusercontent.com/assets/1030242/12766317/8bd83d9a-ca03-11e5-9558-736ae7005f5b.png)

I reckon we're there. Now we just have to hope that our nice and awesome icon developer will like our suggestion and implement it, hopefully in the next version!

What do you say, @tagliala and @davegandy ? Do you like our updated suggestion for a church icon, based on the existing Home icon? I think this one looks much nicer than the one in my original post above, and fits better into the overall style of the FA icons, and I hope you'll find it a worthy addition! :)

**Comment by heyjoecampbell** [comment]
+1

**Comment by machiaveli88** [comment]
+1

**Comment by zuck** [comment]
@GermanKiwi Perfect!

**Comment by tromney** [comment]
+1

**Comment by davidfreels** [comment]
+1

**Comment by akjackson1** [comment]
+1

**Comment by sabatiny** [comment]
+1

**Comment by xd1936** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by man-b-e-a-s-t** [comment]
+1

**Comment by jjbbrr** [comment]
+1

**Comment by jonatascastro12** [comment]
+1

**Comment by jacobbridges** [comment]
+1

**Comment by InnovativeWorks** [comment]
What is the status of this? When will it be available?

**Comment by sandeejackson** [comment]
+1

**Comment by cre8tivediva** [comment]
+1

**Comment by edianogama** [comment]
+1

**Comment by HenryWiersma** [comment]
I am working on a website for a church. I hope that the church icon come available soon :)

**Comment by heyjoecampbell** [comment]
@HenryWiersma a new church website or a redesign? Please share a link if you can :)

**Comment by sbsnet** [comment]
+1

**Comment by robbyfine** [comment]
I'm going to develop a website for our church community from a ready made [church WP theme](http://www.templatemonster.com/category/religious-WordPress-themes/) . Hope, I'll be able to create an effective website to  keep its visitors informed on events, donation, church services and other news.

**Comment by georgeemr** [comment]
+1

**Comment by biwin** [comment]
+1

**Comment by Memaddog** [comment]
+1

**Comment by kylesalone** [comment]
+1

**Comment by ijakic** [comment]
+1

**Comment by ElliotFriend** [comment]
+1

**Comment by blackstile** [comment]
+1

**Comment by topwebs** [comment]
+1

**Comment by mmeinert** [comment]
+1

**Comment by Crissov** [comment]
* [⛪ U+26EA Church](http://emojipedia.org/church-building/)

## Related emojis
* [☦ U+2626 Orthodox Cross](http://emojipedia.org/orthodox-cross/)
* [✝ U+271D Latin Cross](http://emojipedia.org/latin-cross/)
* [🛐 U+1F6D0 Place of Worship](http://emojipedia.org/church-building/)
* [⛩ U+26E9 Shinto Shrine](http://emojipedia.org/shinto-shrine/)
* [🕌 U+1F54C Mosque](http://emojipedia.org/mosque/)
* [🕍 U+1F54D Synagogue](http://emojipedia.org/synagogue/)
* [🕋 U+1F54B Kaaba](http://emojipedia.org/kaaba/)

## Related non-emojis
* ⛬ U+26EC Historic Site

## Christian crosses and symbols
* † U+2020 Dagger ([Ob]long Cross)
* ☓ U+2613 Saltire (St. Andrew’s Cross) – U+1F7A8–E
* ☥ U+2625 Ankh
* ☧ U+2627 Chi Rho (Constantine’s Cross)
* ☨ U+2628 Cross of Lorraine
* ☩ U+2629 Cross of Jerusalem
* ♁ U+2641 Earth
* ♰ U+2670 West Syriac Cross
* ♱ U+2671 East Syriac Cross
* ✚ U+271A Heavy Greek Cross – U+1F7A1–7
* ✠ U+2720 Maltese Cross
* 🕈 U+1F548 Celtic Cross

**Comment by roddharris** [comment]
Love the U+26EA Church emoji shared by @Crissov !  That would be a great icon for fa-church!

**Comment by Crissov** [comment]
@roddharris Unicode emojis depend on the system. I’m seeing the [Emojione](/ranks/emojione/) version for instance.

**Comment by GermanKiwi** [comment]
@Crissov those are emojis, not icons. And the U+26EA emoji you've depicted above is not easily recognisable at such a small size. The example I've posted above fits the bill more suitably, and I believe better matches the Font Awesome style.

Also, this particular thread is only for a church icon. I'm not sure what your point is in posting a long list of buildings and cross variations, but they are not relevant to this discussion. Please keep it on topic.

**Comment by Crissov** [comment]
@GermanKiwi I believe every applicable issue should track relevant Unicode characters to ease  [#222 Support public Unicode codepoints where possible](https://github.com/FortAwesome/Font-Awesome/issues/222).

**Comment by GermanKiwi** [comment]
@Crissov then you should suggest just one unicode character, which you think is the appropriate one, not a whole list of other ones that are irrelevant to this thread. This thread is exclusively for a Christian church icon, so posting a list of emoji for houses of worship from other religions and cross symbols is off-topic here. You should also give an explanation with such a post so that others know why you're posting it - context is important - eg. provide a link to the #222 thread for example.

**Comment by aruljohn** [comment]
+1

**Comment by markusguenther** [comment]
+1

**Comment by roddharris** [comment]
I like this as a church icon from @Crissov 's post of emojis.  I think it does well at small sizes and captures what I was hoping for in an icon.

![church](https://cloud.githubusercontent.com/assets/9284228/22429037/40796378-e6d7-11e6-9a37-326d371dac2c.png)

**Comment by allangood** [comment]
+1

**Comment by erzbistum** [comment]
+1

**Comment by lithiumfrost** [comment]
+1

**Comment by mmaynar1** [comment]
+1

**Comment by zuck** [comment]
@GermanKiwi I don't know exactly how FA handle icon requests, but maybe if you could publish the already designed .SVG it would be easier to see it upstream quicker (I repeat: _maybe_, I'm not sure :wink:)

**Comment by cozzbie** [comment]
+1

**Comment by machadoug** [comment]
+1

**Comment by visualpharm** [comment]
I've started a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The church icon is here](https://icons8.com/icon/23560/church). More church icons [here](https://icons8.com/icon/set/church/all).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), [clean](https://github.com/FortAwesome/Font-Awesome/issues/239#issuecomment-304473340) and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by kylesalone** [comment]
Awesome, thank you!
On May 30, 2017 at 7:41 PM Ivan Braun <notifications@github.com> wrote:I've started a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) compiling all FA and third party icons into a single file.
The church icon is here. More church icons here.
Previous ones were moderator,  discord, coins, Google Play,  thin close, walking man, t-shirt, Xbox, Nintendo Wii U, Nintendo, PlayStation, Facebook messenger, Line, clean and math icons.
Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by wdi-scholz-heiko** [comment]
+1

**Comment by neutralsingh** [comment]
+10

**Comment by jsilvanus** [comment]
+1 this would be really helpful!

**Comment by d3netxer** [comment]
I need an icon representing religion in general

**Comment by jsilvanus** [comment]
That is a very hard icon to create. Maybe something like prayer-icon would be best for that.

**Comment by GermanKiwi** [comment]
@jsilvanus how do you figure that this is a hard icon to create? The requested/suggested icons provided in this thread - especially the one in the OP - work very well as icons, including at very small sizes, and fit nucely with the style of Font Awesome. In fact I'm using that icon on my own church website right now and it looks great.

A prayer icon would not be suitable at all, because prayer ≠ church. They are completely separate things (with regards to icon depiction). This thread is for a church icon.

**Comment by jsilvanus** [comment]
@GermanKiwi the icon is for Christianity, not religion in general. My comment was meant for @d3netxer - sorry for ambiguity.

**Comment by GermanKiwi** [comment]
@jsilvanus okay got it. Thanks for clarifying!

**Comment by internetstyle** [comment]
+1

**Comment by holzee** [comment]
+1 here too

**Comment by ericekidwell** [comment]
+1

**Comment by b3nj4m1kn16ht** [comment]
+1

**Comment by ThatGuySam** [comment]
+1

**Comment by tonywatkins** [comment]
+1

This thread has been going since 2013, and there are related threads. I am rather disappointed that the Font Awesome team haven't recognised that there's a clear need for a set of religious icons including a church.

**Comment by MenesesEvandro** [comment]
We all want it...

Religious icons.

Christianity, Islam, Judaism, Buddhism, Hinduism, Confucianism, Taoism and several others religions that can be added.

**Comment by GermanKiwi** [comment]
@tonywatkins are you aware that the developers have been flat-out working on Font Awesome 5 over the past months? FA5 has been a truly massive undertaking - completely recreating all icons and adding hundreds more, which are in even greater demand than our church icon. And it's still a work in progress - they haven't finished all of the new features that FA5 introduces. This takes them a great deal of time, and our patience is surely appreciated.

Incidentally: have you all purchased a license for FA5? The developers don't work for free, and they don't owe us any favours, least of all if we haven't purchased a license to support their efforts. My suggestion for everyone else here making demands: buy a license, keep your requests polite, and be patient. The developers don't have an anti-religion bias. They're just busy. :)

**Comment by GermanKiwi** [comment]
@sensibleworld: I noticed the recently-created "[home-heart](https://fontawesome.com/icons/home-heart)" icon, which uses the same style as the original "[home](https://fontawesome.com/icons/home)" icon.

IMO, a new church icon should use the same styling as these two icons - just replace the door/heart with a cross, and convert the chimney (on the right-hand side) into a slightly-taller steeple with a little window in it. I think it will look best when it maintains the same style as these existing two icons.

**Comment by tonywatkins** [comment]
@GermanKiwi 
Yes, I’m very aware and appreciative of how hard they have been working. I bought a licence (and later upgraded it) through supporting the Kickstarter campaign as soon as I heard about it. 

It’s very hard for me (or probably anyone outside of the development team) to gauge the relative demands for different types of icon. My comment was merely that there is clearly a high level of demand for _this_ category of icon, which has now been expressed over 5 years, and therefore I felt disappointed that it hadn’t been – as far as I could see – acknowledged. That may simply be a function of the devs not commenting on the threads – or at least on this one. I would just like to know if they’re ever going to come. I am full of admiration for what the FA team has achieved, and I’m eager to see what updates are in the works.

Please note, I did not accuse the devs of having an anti-religious bias.

**Comment by GermanKiwi** [comment]
Awesome, thanks @sensibleworld!

**Comment by aruljohn** [comment]
I just want to say thank you, Jory @sensibleworld!

**Comment by tonywatkins** [comment]
Thank you for taking the time to drop by. We appreciate all the work the team is putting into designing wonderful new icons.

Tony

----
More from me at http://www.tonywatkins.uk
Follow me on Twitter: http://twitter.com/tonywatkins_
Like my Facebook page: http://facebook.com/TonyWatkinsPage

**Comment by sensibleworld** [comment]
After almost five years, this icon has been released! https://fontawesome.com/icons?d=gallery&q=church

**Comment by GermanKiwi** [comment]
@sensibleworld awesome, thanks so much!!

**Comment by sensibleworld** [comment]
@GermanKiwi There's also another icon you might like: https://fontawesome.com/icons/kiwi-bird?style=solid ;)
