### ISSUE TITLE
Icon request: icon-pen

### ISSUE THREAD

**Issue by turiyag** [FortAwesome/Font-Awesome#2094]
Similar to the pencil, the pen represents a writing implement. I would use it in my Whiteboard app that I am generating.
![image](https://f.cloud.github.com/assets/593718/1263305/bf565370-2c4c-11e3-9488-71688a8247e0.png)

**Comment by darrylcousins** [comment]
+1 for ye olde style quill pen.

Thanks in advance,
Darryl

**Comment by chrischristo** [comment]
+1 for quill!!

**Comment by laicosly** [comment]
+1 for quill

**Comment by deven20377** [comment]
+1 
for Fountain Pen

**Comment by PeterShaggyNoble** [comment]
+1 for something along the lines of benbro's suggestion

**Comment by matthew-shaw** [comment]
+1

**Comment by JTFouquier** [comment]
:+1: This would be great :)

**Comment by harshac** [comment]
+ 1

**Comment by harshac** [comment]
+1

**Comment by btorApicea** [comment]
+1

**Comment by yihou** [comment]
+1

**Comment by sensibleworld** [comment]
A few options here: https://fontawesome.com/icons?d=gallery&q=pen&c=design and here: https://fontawesome.com/icons?d=gallery&q=marker&c=design
