### ISSUE TITLE
Icon request: icon-highlighter (icon-marker)

### ISSUE THREAD

**Issue by turiyag** [FortAwesome/Font-Awesome#2095]
A representation of a highlighter, similar to the pencil. I would use this in my Whiteboard app. Could also be named "icon-marker"

![image](https://f.cloud.github.com/assets/593718/1263326/0f8b0fac-2c4d-11e3-919c-6dc2cb60dbaf.png)

**Comment by aethior** [comment]
+1

**Comment by acshef** [comment]
+1

**Comment by flopezg** [comment]
+1

**Comment by shant14** [comment]
+1

**Comment by lorencs** [comment]
+1

**Comment by auge8472** [comment]
+1

**Comment by daprezjer** [comment]
+1

**Comment by chetan-jadhav** [comment]
+1

**Comment by joe-bader** [comment]
+1

**Comment by csarven** [comment]
+1

This icon will compliment HTML's [mark](http://www.w3.org/TR/html5/text-level-semantics.html#the-mark-element) element.

**Comment by drdiv** [comment]
+1

**Comment by gklandes** [comment]
+1

**Comment by bcrigler** [comment]
+1

**Comment by SAHellauer** [comment]
+1

**Comment by matthew-lang** [comment]
+1

**Comment by BobisOnlyBob** [comment]
+1

**Comment by brancasimo** [comment]
+1

**Comment by ejamesc** [comment]
+1

**Comment by jazanne** [comment]
+1

**Comment by ediweissmann** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by circleb** [comment]
+100

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by redapplewithleaves** [comment]
+1

**Comment by hangler** [comment]
+1

**Comment by solidsource** [comment]
+1

**Comment by jason-ellis** [comment]
+1

**Comment by gordonlin89** [comment]
+1

**Comment by ghedwards** [comment]
+1

**Comment by sogen** [comment]
+0/0

**Comment by peder541** [comment]
+1

**Comment by theRanalyst** [comment]
+1

**Comment by villalon** [comment]
+1

**Comment by Jonatino** [comment]
+1

**Comment by csicky** [comment]
+1

**Comment by ruxsoftwerks** [comment]
+1

**Comment by knightq** [comment]
+1

**Comment by raerae13** [comment]
+1

**Comment by anthonygjacob** [comment]
+1

**Comment by ooMICHELAoo** [comment]
+1

**Comment by edercortes81** [comment]
+1

**Comment by Nadeermalangadan** [comment]
+1

**Comment by rt-jar** [comment]
+1

**Comment by turiyag** [comment]
So, like, how many +1s until this becomes an icon? :P

**Comment by SCRIPTILIA** [comment]
It's annoying me... four years have passed!

**Comment by issy123** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks! We’re getting back on track with requested icons. You can follow along with progress and recent releases here: https://fontawesome.com/community/leaderboard/released

**Comment by csarven** [comment]
"getting back on track" ~= 4.5 years without any community engagement?

I don't know if v5 has this icon but it is quite likely that this icon is not going to happen for v4.7. @sensibleworld / FA team, at this point, you might as well mark this issue as WONTFIX for v4.7. For v5, it'd be great if the FA team can provide an ETA within the next 5 years... just for those that might still be interested if not already moved on ;)

**Comment by sensibleworld** [comment]
@csarven You're 100% right that the engagement on the open requests has been poor to non-existent. The best I can do is apologize for that and say that we're are now keeping an active eye on things. Over the past month we've released over 50 of the most-requested icons, and are working hard to continue the pace.

This icon, in particular, is in the process of being designed.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/highlighter?style=solid
