### ISSUE TITLE
Icon request: icon-classroom

### ISSUE THREAD

**Issue by babak4652** [FortAwesome/Font-Awesome#2100]
To be able to represent a class.

**Comment by mrottman** [comment]
+1

**Comment by backstageel** [comment]
+1

**Comment by hsameerc** [comment]
+1

**Comment by martinvivek** [comment]
+1

**Comment by Aryan-mor** [comment]
+1

**Comment by gghhh456** [comment]
+1

**Comment by sensibleworld** [comment]
I think one of these should cover this request:

https://fontawesome.com/icons/chalkboard-teacher?style=solid
https://fontawesome.com/icons/chalkboard?style=solid
https://fontawesome.com/icons/school?style=solid
https://fontawesome.com/icons/user-graduate?style=solid
