### ISSUE TITLE
Icon request: playing-card, deck-of-cards

### ISSUE THREAD

**Issue by kait85** [FortAwesome/Font-Awesome#2101]
These could be useful for numerous sites or applications to suggest games or game related stuff.  I wanted to represent a deck of cards and was finding nothing overly suitable

**Comment by Fatbat** [comment]
+1

**Comment by philipbkemp** [comment]
:+1:

**Comment by dshchupak** [comment]
+1

**Comment by mcbyte-it** [comment]
+1

**Comment by actuallymab** [comment]
+1

**Comment by adamwintle** [comment]
+1 for this

**Comment by TheChrisNxt** [comment]
also the icons for "clubs, spades, diamonds" would be nice to have. The heart is already implemented.

**Comment by hachesilva** [comment]
Duplicate of #606 , that is not solved yet. I sent these icons before when icon submissions were available and they didn't make it to the library.

**Comment by Fatbat** [comment]
Aside from corporate shills, has there ever been a user submitted icon accepted into this library?

**Comment by jmcvety** [comment]
👍

**Comment by bitedgecom** [comment]
+1

General playing card icon, can represent

* Gambling
* Casino
* Poker
* Las Vegas
* Macau

**Comment by pioz** [comment]
+1

**Comment by pioz** [comment]
Also Magic The Gathering cards!

**Comment by NikosEfthias** [comment]
+1

**Comment by bitsboxscott** [comment]
+1

**Comment by sensibleworld** [comment]
Just released: https://fontawesome.com/v6.0/icons?q=playing%20card&s=solid%2Cbrands

**Comment by tooomm** [comment]
@sensibleworld Unfortunately, still no general playing card icon to represent any type of card game.
Or a universal representation of cards in your hand or a stack/deck of cards.

**Comment by pioz** [comment]
Yes, an icon for generic card games that can include MTG, Pokemon, Yugioh would be great. These icons are specific for Poker cards.

**Comment by sensibleworld** [comment]
Just added in some blank cards: https://fontawesome.com/icons/cards-blank?s=solid
