### ISSUE TITLE
Icon-Request: icon-signup

### ISSUE THREAD

**Issue by tomprats** [FortAwesome/Font-Awesome#2103]
There's already a icon-signin but in tons of places there's need for a signup and signin icon side-by-side.

What have other people been using for this?  I looked through and couldn't find any that made sense.

**Comment by davegandy** [comment]
Going to reopen this one and put it in v5.0. I find myself wanting this one too.

**Comment by davegandy** [comment]
Looks like this is a duplicate of #872. Closing here.
