### ISSUE TITLE
Icon Request: icon-buffer

### ISSUE THREAD

**Issue by kyletaylored** [FortAwesome/Font-Awesome#2110]
With the growing use of sharing analytics like ShareThis, AddThis, and BufferApp itself, it might be useful to add the Buffer icon to the library. I actually already created an SVG, just not sure how to submit it.

Thanks!

![buffer](https://f.cloud.github.com/assets/1759794/1277694/0124de00-2ed9-11e3-8a24-414d16698b73.gif)

**Comment by mastermaq** [comment]
+1

**Comment by bobsawyer** [comment]
+1, please.

**Comment by tagliala** [comment]
+1 (#3873)

**Comment by ElliotFriend** [comment]
+1

**Comment by jayshields** [comment]
+1

**Comment by AmgedOsman** [comment]
I use this svg for now https://github.com/bufferapp/buffer-blog-v2/blob/master/wp-content/themes/buffer-v2/images/buffer-logomark.svg?short_path=ad18f60

**Comment by smhmic** [comment]
+1

**Comment by y8hamon** [comment]
+1

**Comment by StephaneJuban** [comment]
+1

**Comment by quickonlinetips** [comment]
+1 Absolutely needed. As useful as the Twitter one.

**Comment by Kavisha-Dev** [comment]
+1 please

**Comment by Gabrielonze** [comment]
+1

**Comment by wpexplorer** [comment]
+1

**Comment by davewarfel** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by geisslercom** [comment]
+1

**Comment by BobbyWibowo** [comment]
+1

**Comment by fraklo** [comment]
+1

**Comment by Ruud68** [comment]
+1

**Comment by darcypeters** [comment]
Hi! It's Darcy from Buffer. We'd love to add it. :) Here are some great versions from [Sebastiano Guerriero of Nucleo](https://dribbble.com/shots/2089345-Nucleo-Free-Social-Icons)

**Comment by lauraulrick** [comment]
+1

**Comment by heshyc** [comment]
+1

**Comment by fezde** [comment]
+1

**Comment by melanieps1** [comment]
+1

**Comment by fmeus** [comment]
+1

**Comment by Crunchify** [comment]
+1.  Any idea on resolution? I would love to see buffer and flipboard icons.

**Comment by dylanfeltus** [comment]
+1

**Comment by rtorralba** [comment]
+1

**Comment by myeclecticself** [comment]
+1

**Comment by anaef** [comment]
+1

**Comment by thanhtruong0315** [comment]
+1

**Comment by MarcSa** [comment]
+1

**Comment by newswim** [comment]
👍 pleeeeeease

**Comment by nathan5x** [comment]
Is it available now in version 4.7.0?

**Comment by inquisitive-stha** [comment]
+1

**Comment by bricemaurin** [comment]
+1

**Comment by JoeCotellese** [comment]
+1

**Comment by monetizedesign** [comment]
+1

**Comment by JayHoltslander** [comment]
Leaving my +1 for all the good it'll apparently do.

**Comment by richard67** [comment]
+1

**Comment by smarteseiten** [comment]
+1

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/buffer

Thanks for the patience and for continuing to vote this up! :smile:

**Comment by Crunchify** [comment]
@talbs - rejoice 👍 

Thank you. Much appreciated. We are releasing new WordPress plugin called **[Crunchy Social Sharing](https://pro.crunchify.com/crunchy-social-sharing/)** tomorrow and this is just in time to add Buffer button into it. I didn't add Buffer just bcoz it wasn't part of FontAwesome.

**Comment by davewarfel** [comment]
Thanks @talbs! Really appreciate everything you do for the community 😃.

**Comment by smarteseiten** [comment]
Thank you! Coming just in the right time,
