### ISSUE TITLE
Icon Request: icon-cloud-alt

### ISSUE THREAD

**Issue by Vilscon** [FortAwesome/Font-Awesome#2115]
Many icons have an icon with an inner color and some don't and rely on the outline. The icon-cloud only has one version, no alt one (with no inner, just the outline).

That's what I'm requesting: A cloud icon with just an outline, like many other icons.

Thanks very much!

**Comment by sensibleworld** [comment]
This is resolved in our latest icon styles :)

<img width="436" alt="Screen Shot 2021-03-30 at 1 32 43 PM" src="https://user-images.githubusercontent.com/529604/113031211-699f5300-915c-11eb-8036-74ca6e1dc511.png">

**Comment by Vilscon** [comment]
I know you closed this, but I gotta ask: how did you keep track of this post and replied after 7 and a half year?!

**Comment by sensibleworld** [comment]
Ha! I'm trying my best to stay on top of requests, so will occasionally spend a little time manually scanning all of our old ones to see if any of the new work I've been doing satisfies existing requests :)
