### ISSUE TITLE
Icon Request: icon-podcast

### ISSUE THREAD

**Issue by sandyrepp** [FortAwesome/Font-Awesome#2125]
My non-profit organization produces a weekly talk radio show and could use an icon on our site that represents when a resource is a podcast, thanks!

**Comment by BenSibley** [comment]
+1

**Comment by xnomeda** [comment]
+1

**Comment by treejanitor** [comment]
+1

**Comment by mohdsam** [comment]
+100

**Comment by pyrographics** [comment]
+1

**Comment by stevedore19** [comment]
+1

**Comment by Twintails** [comment]
+1

**Comment by lostfocus** [comment]
+1

**Comment by Spinball** [comment]
+1  Amazed with all the crap that's in Font Awesome now, there isn't a podcast icon!

**Comment by andresgalante** [comment]
:+1:

**Comment by kwendenarmo** [comment]
+1

**Comment by Rayden** [comment]
+1

**Comment by damirkotoric** [comment]
+1 So many plus once, why isn't this being merged yet?

**Comment by kellyjandrews** [comment]
I'm waiting for the 2-year anniversary.  Getting close!

**Comment by jacobkball** [comment]
Meanwhile, in other news, Microsoft releases a whole new operating system, before FontAwesome can create a Podcast icon....

As someone else said, it's amazing with all of the 'not so common' icons already in there, that they don't have a podcast one.

**Comment by be-next-hotdog** [comment]
+1

**Comment by davblayn** [comment]
+1

**Comment by dan** [comment]
+1 million

**Comment by fdambrosio** [comment]
+1

**Comment by dabaliyan** [comment]
+1 billion

**Comment by topwebs** [comment]
+1 trillion

**Comment by marlex** [comment]
How is going? These icon would be perfect! +1

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313033303234322f313839323939382f32353262376262612d376136352d313165332d396632322d6535353263306337346433652e706e67](https://cloud.githubusercontent.com/assets/1155574/11840492/967cb59c-a3f6-11e5-9f09-e4cfd4bb6ddf.png)

**Comment by jacobkball** [comment]
Over two years now, and still no closer to a podcast icon.

I noticed that in the latest release of new icons, there's one for MODX. Seriously?? MODX more widely used than podcasts? 

How is Rock, Paper, Scissors, Lizard, Spock more relevant to everyday internet usage?

Is anyone from FontAwesome even looking at this thread?

**Comment by treejanitor** [comment]
:boom: Dang, you busted out the rock, paper, scissors reference...  whoa.

I agree. podcasts have become pretty hot in the PR world, and Apple is already a behemoth/juggernaut, so it makes sense to me.  I've been interested in a podcast icon for years, so thanks for keeping the thread alive...  

honestly, I'm not even an apple fanboy - i got major complaints about their OS shenanigans of late :-)

**Comment by Kennric** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by cyberscribe** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by cbratschi** [comment]
+1

**Comment by ThatPascale** [comment]
+1

**Comment by seesmith** [comment]
+1

**Comment by cabplanalp** [comment]
+1

**Comment by serranoabq** [comment]
+1

**Comment by brodydorland** [comment]
+1 Bueller...

**Comment by mateuszjarosz** [comment]
+1

**Comment by singuyen** [comment]
+1

**Comment by DeysonOrtiz** [comment]
+1

**Comment by TheMiXeD** [comment]
+1
@GermanKiwi

**Comment by smurphycp** [comment]
+1

**Comment by ericrovtar** [comment]
+1 for this

**Comment by FerdiAgrio** [comment]
+1

**Comment by pftaylor61** [comment]
Why is no one responding to this thread?

**Comment by mattbrett** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch. Closing.

<img width="730" alt="screenshot 2016-10-11 12 30 11" src="https://cloud.githubusercontent.com/assets/1076721/19279226/90324e32-8fae-11e6-894a-aa13cfe43b74.png">

**Comment by pftaylor61** [comment]
Thank you so much! This is excellent!

Paul Taylor


*Paul Taylor, BSc MEd*
850-450-2310
pftaylor61@gmail.com
Creation Speaker
Author of "Don't Miss the Boat" and "The Six Days of Genesis"

**Comment by kwendenarmo** [comment]
This is now available in Font Awesome 5 beta-2
