### ISSUE TITLE
SASS @extend support?

### ISSUE THREAD

**Issue by msisto** [FortAwesome/Font-Awesome#213]
Maybe I am missing something, but it appears that even with the SASS version, you can't extend an icon into an element?

For example:

``` sass
a.edit-thingie {
  @extend .icon-edit;
  color: blue;
}
```

But `<a href="" class="icon-edit"></a>` on its own, works as expected.

**Comment by lethjakman** [comment]
With newer FontAwesome versions the above mixin does need a little help. I've modified it below just to make it easier for anyone who may need to do this.

@mixin icon($name) {
  &:before {
    font-family: FontAwesome;
    font-weight: normal;
    font-style: normal;
    display: inline-block;
    text-decoration: inherit;
    margin-right: 0.4em;
  }

  @extend .fa-#{$name};
}
