### ISSUE TITLE
Icon request: icon-gclef

### ISSUE THREAD

**Issue by pablog79** [FortAwesome/Font-Awesome#2134]
Hi, I would like to add an icon to the great Font-Awesome list of icons.
It's one of many that I think will be greatly appreciated for the community: Musical icons. 

Attached is the first one: G Clef. But I have also in mind others, like F clef, Crotchet,  Quarter note, Quaver, Eighth note, Forte, etc.
![icon-g-clef](https://f.cloud.github.com/assets/5661358/1312286/2547b44a-322d-11e3-8b42-4a093814b786.jpg)

Here is a complete list: http://en.wikipedia.org/wiki/List_of_musical_symbols
Thank you for your feedback.

**Comment by tagliala** [comment]
Closing in favor of #11614, with more upvotes
