### ISSUE TITLE
 Icon request: icon-eye-open-alt

### ISSUE THREAD

**Issue by mennows** [FortAwesome/Font-Awesome#2139]
Hello,

I would like to reqeust a new icon.

![eye-open](https://f.cloud.github.com/assets/5064719/1314373/6b17aa76-3272-11e3-8320-68ce22309c7c.jpg)

**Comment by sensibleworld** [comment]
We have a few options for "eye" icons in Font Awesome now. https://fontawesome.com/v6.0/icons?q=eye&s=solid%2Cbrands

If none of these work, let me know, and I'll re-open the issue.
