### ISSUE TITLE
Icon Request: battery and progress bar indicators

### ISSUE THREAD

**Issue by HopesOblivion** [FortAwesome/Font-Awesome#2148]
Working on an app that needs to show a user some indication of how much progress they have made. It would be helpful to have both horizontal and vertical progress bar icons with different % complete amounts pre-filled or a base icon with bars that could be stacked to show amount of progress.

In a similar vain, battery status icons would also be helpful.  Sorry I don't have any helpful images to attach, jquery ui has a battery icon that might help as a reference.

Thanks!

**Comment by wmulligan** [comment]
+1

**Comment by onc** [comment]
+1

**Comment by onc** [comment]
+1

**Comment by chprome** [comment]
+1 for battery

**Comment by nkoehring** [comment]
+1 for battery

**Comment by zerophyn** [comment]
+1

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone but I cannot guarantee a whole set of batteries (0%, 25...)

**Comment by G-Driver** [comment]
+1

**Comment by JoabMendes** [comment]
+1

**Comment by bogdanzurac** [comment]
Just needed a battery icon in our current project, under the section "Battery efficiency", as a use case. So indeed, I was surprised as well that no battery icon is present. Could we get one going? Nothing fancy with multiple percentages, just at least a full charged one.

**Comment by norn** [comment]
+1

**Comment by rubenjpmartins** [comment]
1+

**Comment by ianpottier** [comment]
+1

**Comment by gfyrag** [comment]
+1

**Comment by trinityXmontoya** [comment]
+ 1

**Comment by kamaln7** [comment]
:+1:

**Comment by SnakeO** [comment]
battery!!!

**Comment by danielealbano** [comment]
+1

**Comment by rr-** [comment]
+1 for both
I use font awesome in an environment that doesn't have anything to do with web, so there are no CSS progressbars.

**Comment by searchwizard** [comment]
+1

**Comment by nixrod** [comment]
+1

**Comment by guillermo26** [comment]
+1

**Comment by gapipro** [comment]
+1

**Comment by chaitan3** [comment]
+1

**Comment by andrew-cunliffe** [comment]
:+1:

**Comment by StephenBrown2** [comment]
:+1:

**Comment by datarc** [comment]
+1

**Comment by kb100** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by bogdanzurac** [comment]
2 years to get a freaking battery icon. This is getting pathetic. Just switch to Google's Material Design icons guys. Unsubscribing from this thread as it is utterly useless.

**Comment by tagliala** [comment]
Four freaking battery icons added in 4.4.0!

Closing here! :)
