### ISSUE TITLE
Icon Request: icon-laravel

### ISSUE THREAD

**Issue by adamgoose** [FortAwesome/Font-Awesome#2151]
I'd love a Laravel icon! I would use it to represent all links on my blog that reference Laravel.com's documentation.

![Laravel Icon](https://raw.github.com/laravel/art/master/sign-laravel.png)

**Comment by expient** [comment]
+1

**Comment by rephluX** [comment]
+1

**Comment by AaronMcH** [comment]
+1

**Comment by Doomworks** [comment]
+1

**Comment by NDuggan** [comment]
+1

**Comment by Pyjou** [comment]
+1

**Comment by hostianer** [comment]
+1000

**Comment by Ardakilic** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by Lednerb** [comment]
+1

**Comment by Silveraven** [comment]
+1

**Comment by bartclaeys** [comment]
+1

**Comment by royduin** [comment]
For the time being, you can use a additional font: https://github.com/websiddu/technology-icons

**Comment by alvinnguyen** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by nmgwddj** [comment]
+1

**Comment by RobinMalfait** [comment]
I think that +1 is not helping hah

Op ma 23 nov. 2015 om 03:59 schreef 邓佳 <notifications@github.com>:

**Comment by taylorotwell** [comment]
Merge dat

**Comment by mizerydearia** [comment]
+1

**Comment by EmilMoe** [comment]
+1

**Comment by DeeJaVu** [comment]
3 years and still nothing LOL

but found a laravel icon font here http://fizzed.com/oss/font-mfizz and here https://scotch.io/bar-talk/svg-developer-icon-set

**Comment by AndreasHerss** [comment]
+1 for that! 

Would be awesome to have :)

**Comment by ihinckle** [comment]
+1

**Comment by brainscript** [comment]
**+1** I'd love to see this!

**Comment by u01jmg3** [comment]
:+1:

**Comment by vdmeijer** [comment]
+1

**Comment by 50shashwat** [comment]
:+1:

**Comment by craigharman** [comment]
+1

**Comment by jethro1991** [comment]
+1

**Comment by tagliala** [comment]
Available in FA5 🎉 

https://fontawesome.com/icons/laravel?style=brands
