### ISSUE TITLE
Icon request: icon-numbers

### ISSUE THREAD

**Issue by JayHoltslander** [FortAwesome/Font-Awesome#2158]
Re: Issue 563 & 907 Which request the same thing...

Not sure why the request isn't being taken seriously.

Clearly people want to have a class .icon-digit1, .icon-digit2 etc.

davegandy wrote: "Every standard font has these. Use them."

Yeah, and everyone can make .png icons in Photoshop too. That's not the point. 
The point is we're looking for an easy way to use font-awsome for this task. e.g.: (image attached)

I think this is a totally valid request and not something to dismiss away.
![screen shot 2013-10-15 at 6 16 08 pm](https://f.cloud.github.com/assets/2069960/1339321/4fe5aa22-3601-11e3-912c-f7ca0c79aa77.png)

**Comment by KevinVR** [comment]
This icon would be useful.

**Comment by tagliala** [comment]
Closing here and adding the wontfix label
