### ISSUE TITLE
Icon Request: icon-plus-thin

### ISSUE THREAD

**Issue by wmasterj** [FortAwesome/Font-Awesome#2161]
The current plug sign:  icon-plus (&#xf067;)

It is really thick and when used in bigger font sizes it looks really bloated. It would be great with a thinner version that sizes better.

**Comment by ngduc** [comment]
+1 : thin plus is more common than the bold plus

**Comment by Robinson7D** [comment]
:+1:

**Comment by nesrinkalender** [comment]
+1

**Comment by MrFirthy** [comment]
+1

**Comment by barsurfer** [comment]
+1

**Comment by vosnikopa** [comment]
+1

**Comment by berkayk** [comment]
+1

**Comment by hirootkit** [comment]
+1

**Comment by ianrobinsonse** [comment]
+1

**Comment by rikonor** [comment]
+1

**Comment by burakkilic** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by joshuatree** [comment]
+1

**Comment by okua** [comment]
+1

**Comment by Seryal85** [comment]
+1

**Comment by distravantari** [comment]
+1

**Comment by vosnikopa** [comment]
How do I stop the system sending me these useless updates??? Please help me
get out of this...

**Comment by barsurfer** [comment]
@vosnikopa, take a look on the attached screenshot :)

![2016-04-14_10-43-32](https://cloud.githubusercontent.com/assets/11078520/14520573/f1beb352-022d-11e6-9a29-42be54c902ca.png)

**Comment by vosnikopa** [comment]
Thank you for the hint, i have tried that Link it is alway on Subscibe, i
even went so far as to change the settings on my account....

O dam it , i just realized it is a old github account.... sorry my bad....
​

On Thu, Apr 14, 2016 at 5:57 AM, Distra Vantari <notifications@github.com>
wrote:

> +1
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/2161#issuecomment-209749680>
>



-- 

Pavlos

Pavlos Vos (Vosniadis)  |  Web UX & UI designer   |  +49 (0) 151 255 39 333
|  skype: pavlosvos  |  pavlos@vos.gr  |  LinkedIn
<http://www.linkedin.com/in/pavlosvos>

**Comment by berkayk** [comment]
+1

**Comment by MadanBhandari** [comment]
+1

**Comment by erezLieberman** [comment]
+1

**Comment by acascarla** [comment]
+1

**Comment by scriptserv** [comment]
+1 -> Anything new about this?

**Comment by parthshah1991** [comment]
+1

**Comment by multidimensionalinteractive** [comment]
+1 I also need a thin plus. I think I will have to use use a png for now unfortunately.

**Comment by multidimensionalinteractive** [comment]
I figured out a temporary solution. Over a white background if i add .fa-plus {
    -webkit-text-stroke: 2px white !important;
}
It will make the plus sign appear thinner.

**Comment by dvdobrovolskiy** [comment]
+1

**Comment by D-Blazer** [comment]
+1

**Comment by tagliala** [comment]
Hi, this icon is available in the light set of FA 5 Pro

https://fontawesome.com/icons/plus?style=light

Closing here

**Comment by cdecaire** [comment]
"Light" is still too thick when compared to similar elements like chevrons, arrows, etc.

<img width="368" alt="thickboi" src="https://user-images.githubusercontent.com/1142000/56145231-e639c680-5f71-11e9-9fc0-f88843b3e309.png">
