### ISSUE TITLE
Icon Request: dragon

### ISSUE THREAD

**Issue by robclancy** [FortAwesome/Font-Awesome#2163]
Do I even need to explain why??

**Comment by fr0980y** [comment]
+1

**Comment by rhysd** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by naryal2580** [comment]
# +1 for this:
![dragon](https://user-images.githubusercontent.com/34544253/40168067-3860a872-59e0-11e8-9831-5289ee5a11ec.png)

**Comment by sensibleworld** [comment]
This icon lived by the sea and frolicked in a magic land: https://fontawesome.com/icons/dragon?style=solid
