### ISSUE TITLE
Icon request: icon-usb

### ISSUE THREAD

**Issue by thotzl** [FortAwesome/Font-Awesome#2165]
i’ve got three ideas:
![usb](https://f.cloud.github.com/assets/1067907/1351619/d3257448-3729-11e3-95f8-b44586282548.png)
![usb2](https://f.cloud.github.com/assets/1067907/1351620/d62c6db8-3729-11e3-9d35-6e42c341538e.png)
![usb3](https://f.cloud.github.com/assets/1067907/1351621/d97cf550-3729-11e3-8b86-60aeeacd9ad2.png)

**Comment by uchuy77** [comment]
+1

**Comment by magicpat** [comment]
+1

**Comment by technofreaky** [comment]
+1

**Comment by jacky4566** [comment]
+1

**Comment by Skalv** [comment]
+1

**Comment by dougwa** [comment]
+1 (first example above)

**Comment by magoo-pl** [comment]
+1

**Comment by berengar** [comment]
+1

**Comment by julievecchio** [comment]
+1

**Comment by justyns** [comment]
+1

**Comment by timetnoun** [comment]
+1 (Perfect)

**Comment by jkramp** [comment]
+1

**Comment by phelma** [comment]
:+1:

**Comment by mohnstrudel** [comment]
Would really like to see it in FA! +1

**Comment by fandomfilms** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.
