### ISSUE TITLE
Icon request: icon-moderator

### ISSUE THREAD

**Issue by sandeepreddyponagandla** [FortAwesome/Font-Awesome#2172]
Need an icon for marking moderator status for a user, and also for the anchor tag to redirect the user to moderation page in our project.

**Comment by aethior** [comment]
Hi,

You can use several icons:
- https://fontawesome.com/icons/shield
- https://fontawesome.com/icons/badge-sheriff
- https://fontawesome.com/icons/route-highway (in my opinion it can also be used as a police badge)
- https://fontawesome.com/icons/user-shield

Regards.

**Comment by tagliala** [comment]
Considering this closed. Feel free to open a new request by filling out the [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
