### ISSUE TITLE
Icon request: icon-name

### ISSUE THREAD

**Issue by virik** [FortAwesome/Font-Awesome#2173]
Hello guys,

First of all, I love font-awesome. It makes everything so much easier. 

I was wondering if you could add an hourglass icon and/or a stopwatch icon. That would be great.

I could also use the follow suggestions, but that's not vital :)
- A person running
- 2 persons running
- A person hiking
- A person lifting a barbell

Thank you so much, and keep up the good work.

**Comment by tagliala** [comment]
no feedback, closing here
