### ISSUE TITLE
Icon Request: icon-hiker

### ISSUE THREAD

**Issue by kurtdavis** [FortAwesome/Font-Awesome#2178]
A hiker icon of guy with stick and backpack.
similar to http://www.iconpng.com/icon/37708

Would like to use it on a walkthrough help page.
![hiker](https://f.cloud.github.com/assets/211125/1375646/9350a554-3a85-11e3-87f1-c4c12d4c2452.png)

**Comment by Djmill** [comment]
+1

**Comment by HarelM** [comment]
+1

**Comment by courtrd** [comment]
+1

**Comment by martindavid** [comment]
+1

**Comment by Cuervino** [comment]
+1

**Comment by HarelM** [comment]
I have stopped waiting for icons and started to use icomoon.

**Comment by haideritx** [comment]
+1

**Comment by Ajbxyz** [comment]
Really need this

**Comment by ashinzekene** [comment]
+2 :smile:
