### ISSUE TITLE
Icon request: icon-Design

### ISSUE THREAD

**Issue by AdrianB86** [FortAwesome/Font-Awesome#2182]
Hi,

Thanks for the great work. I have 4 icons that if you could create icons out of that would be incredible!

Here is 4
![design-02](https://f.cloud.github.com/assets/5740579/1375733/01c7e7f8-3a87-11e3-929c-edf75b13b0d2.png)
 of 4.

**Comment by sensibleworld** [comment]
We have a lot of design-related icons now! https://fontawesome.com/v6.0/icons?q=design&s=solid
