### ISSUE TITLE
Icon request: icon-awareness-ribbon

### ISSUE THREAD

**Issue by JaredMadden** [FortAwesome/Font-Awesome#2183]
The awareness-ribbon symbol is universally used for all cause based campaigns and to create awareness to certain medical or social issues.

Example:
- RED = HIV & Aids
- YELLOW = Leukaemia / ADHD / Self Injury awareness
- PINK : Breast Cancer
- GREY : Athsma / Brain Cancer

Reasons to create this icon:
- it is a universal icon
- it is currently  used by thousands of campaigns around the world
- it can be used as a menu icon for "issue awareness" or "donations"
- it can be used as a "topic icon" for blogs and as a article signature

How I will use it:
- As part of the menu system
- As an article sign off symbol (for its blog category)

Examples of potential design:
![ribbons](https://f.cloud.github.com/assets/5742143/1377725/c0951cd8-3aae-11e3-910a-67a460641830.png)

**Comment by stephaniewang526** [comment]
+1

**Comment by kinzdesign** [comment]
+1

**Comment by yogiee** [comment]
+1

**Comment by Laxman13** [comment]
+1

**Comment by indrif** [comment]
+1 from me aswell

**Comment by mwatz122** [comment]
+1

**Comment by tylermcginnis** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by aethior** [comment]
The last Monday was the International Day of breast cancer and I would have liked to show this icon on my website. There are also other causes to use this symbol: https://en.wikipedia.org/wiki/List_of_awareness_ribbons

**Comment by angiejones** [comment]
+1

**Comment by marta-** [comment]
+1

**Comment by jromeem** [comment]
+1

**Comment by cobe1972** [comment]
+1
I leave a few that I have made with the fa-sun
![fa-award](https://cloud.githubusercontent.com/assets/16846747/12527806/1a2b2546-c183-11e5-85e0-6c0ff5d77d54.jpg)

**Comment by bennyp123** [comment]
+1

**Comment by lifehome** [comment]
+1 any news on this? I am making a LGBTQI friendly website, and this icon seems necessary on promoting healthy and disease prevention work. Hopefully there is some good news on this issue.

**Comment by cre8tivediva** [comment]
+1 Yes, any update on this. I have an ovarian cancer project I volunteer services for. This would be so "awesome".

**Comment by sandeejackson** [comment]
+1 -- working with nonprofits, this would be a great one to have.

**Comment by lifehome** [comment]
Almost another month... Any news?

**Comment by Crissov** [comment]
Unicode character #222:

- 🎗 [U+1F397 Reminder Ribbon](http://emojipedia.org/reminder-ribbon/)

**Comment by lifehome** [comment]
Good! Great to hear this is finally out!

**Comment by Crissov** [comment]
@lifehome No, this is the Unicode character code that an awareness ribbon should use if it was added to Font Awesome. It’s available there in *other* fonts. Currently, all glyphs are assigned to non-standardized private-use codepoints (“PUA”) only.

**Comment by kimberley-johnston** [comment]
+1

**Comment by lnball** [comment]
How do we go about adding the awareness ribbon icon to the next release?  How can I push this forward?

**Comment by mogoodrich** [comment]
+1

**Comment by meyersbs** [comment]
+1

**Comment by reubenvarghese1** [comment]
+1

**Comment by suthagar23** [comment]
+1

**Comment by cintiadr** [comment]
+1

**Comment by sensibleworld** [comment]
Released in 5.0.9
