### ISSUE TITLE
Icon request: icon-chrome, icon-safari, icon-opera, icon-firefox, icon-internet-explorer

### ISSUE THREAD

**Issue by jrmessias** [FortAwesome/Font-Awesome#219]
Chrome, Firefox, Opera, Internet Explorer, Safari.
Like http://www.softicons.com/free-icons/system-icons/web0.2ama-icons-by-chrfb

**Comment by lenamtl** [comment]
+1

**Comment by dominikgrolimund** [comment]
+1

**Comment by jaCUBE** [comment]
+1

**Comment by henleywc** [comment]
+1

**Comment by veapon** [comment]
+1

**Comment by jtphelan** [comment]
+1

**Comment by JaredCubilla** [comment]
+1

**Comment by dhainautraphael** [comment]
+1 please

**Comment by dellis23** [comment]
+7

**Comment by fyyyyy** [comment]
just saw this request is 2.5 years old :scream:

**Comment by dellis23** [comment]
99% of the people have 1% of the icons!!!

**Comment by ergineroglu** [comment]
+1

**Comment by StudioJunkyard** [comment]
@fyyyyy noticed this as well, yet they add icons that I look at and think how the f**k would want or use that. I started my own, a couple of days ago, LibreICONS (on github too, I'd link too it, but I want to remain fair to FA), not to take the limelight away from this project, I do think they do awesome work, but there's just so many icons that I need, that have been requested that make sense for a web application, and are either being ignored, or taking longer than necessary to be implemented.

**Comment by fyyyyy** [comment]
FA is awesome, but this request is probably going nowhere :smile: I'm looking at their new service now that allows to customize icons on the fly https://fonticons.com

**Comment by StudioJunkyard** [comment]
Yeah, that looks good, but the free version is limited. I'm not sure how the licensing works without delving into it if paid icons are used in FOSS projects.

**Comment by DaAwesomeP** [comment]
I will comment again: @FortAwesome (@davegandy and @tagliala), this is now almost three years old, is the sixth most commented on open issue in this repository, and there have been ten releases since this issue was opened. Most people (like me) on this thread are moochers; we have no way in assisting with the design of the icons. However, as an open source and *extremely* popular project (you should be proud of that), this really ought to get moving.

Services like Fonticons and Fontello do technically solve the problem, but they add an extra step, often add unnecessary total file sizes, make automatic download/build/compile workflows a nightmare, cost money and can even change the implementation of the font (different prefixes or positioning).

Thank you so much for your hard work on this literally awesome project. I really have no way of helping with the actual font, which makes this comment awkward, but some people in this issue have posted links to some other icons. Simply searching [*flat chrome icon* on Google](https://www.google.com/search?q=flat+chrome+icon) brings up a lot of icons that the magic wand tool could easily tackle. The challenge is finding one with the right license. I always jump to Font Awesome for all of my icon needs and I think that adding the major browser icons (Chrome/Chromium, Firefox, Safari, Internet Explorer, and Opera) would really bring Font Awesome to another level.

**Comment by strichter** [comment]
+1

**Comment by MathRobin** [comment]
+1

**Comment by LauritzT** [comment]
+1

**Comment by nounoursheureux** [comment]
+1

**Comment by Izopi4a** [comment]
+1

**Comment by CoWinkKeyDinkInc** [comment]
+1 :+1:

**Comment by visby** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by A----** [comment]
:+1:

**Comment by B4rt0** [comment]
+1

**Comment by HaNdTriX** [comment]
+1

**Comment by DelBianco** [comment]
+1

**Comment by Degochan** [comment]
Icon Request: icon-spartan

**Comment by DaAwesomeP** [comment]
:+1:

**Comment by kukac7** [comment]
:+1:

**Comment by nvdcmptr** [comment]
+1

**Comment by SilverFire** [comment]
:+1:

**Comment by AnOldMan** [comment]
This + OS brands = stats on my site. Only issue I see is single-color limitation.

**Comment by DeBraid** [comment]
+1

**Comment by jbarbede** [comment]
+1

**Comment by message** [comment]
+1

**Comment by larsbo** [comment]
+1

**Comment by haslo** [comment]
+1

**Comment by sherry-kukd** [comment]
+1

**Comment by Flex-WKD** [comment]
+1

**Comment by raghunayyar** [comment]
big big big big :+1:

**Comment by steenbrahe** [comment]
+1

**Comment by Denni007** [comment]
+1

**Comment by okaay** [comment]
+1

**Comment by shawnmann** [comment]
+1

**Comment by simo2409** [comment]
:+1:

**Comment by ziemkowski** [comment]
:+1:

**Comment by runys** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by tojonmz** [comment]
+1 from the Mozilla team here per our [request](https://github.com/FortAwesome/Font-Awesome/issues/6965) above. Please see Issue #6965 above for Mozilla contact information from the Branding team.

**Comment by DavidGarciaCat** [comment]
:+1: please, do it if you can, will be great!

**Comment by thebaer** [comment]
+1

**Comment by radiantnode** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by tuxy** [comment]
+1

**Comment by CRS-ECHO51** [comment]
+1

**Comment by anaflasker** [comment]
+1

**Comment by davegandy** [comment]
@tojonmz Is there an official single color version of the Firefox logo? I'd love to get it in 4.4.0.

**Comment by davegandy** [comment]
Added safari, chrome, firefox, opera, and ie logos to 4.4.0-wip. Closing!

**Comment by CoWinkKeyDinkInc** [comment]
MRW
![alt text](http://img.pandawhale.com/39108-one-sunglass-mother-of-god-6dZY.gif)

But seriously, thanks to everyone who contributed and helped add these heavily requested icons.

**Comment by tojonmz** [comment]
> @tojonmz Is there an official single color version of the Firefox logo? I'd love to get it in 4.4.0.

@davegandy hi thanks for checking, I'm not sure. You can check with Sean Martell listed in my original [issue](https://github.com/FortAwesome/Font-Awesome/issues/6965) to confirm. If you are having difficulty finding him on IRC or by email via his Mozillians link let me know and I'll track him down to comment here. Thank you again :)

**Comment by StudioJunkyard** [comment]
Your welcome to pinch the icon for Firefox that I used in LibreICONS (https://github.com/StudioJunkyard/LibreICONS). You should find it in the source/svg folder.

**Comment by TheChen5** [comment]
Awesome! Just noticed 4.4.0 is out.
Thx for the browser logos!

**Comment by DaAwesomeP** [comment]
This is amazing. I will now finally be able to stop receiving emails solely with the content "+1" for the first time in more than a year. On another note, I get to use the new icons.

**Comment by DaAwesomeP** [comment]
+1

**Comment by jrmessias** [comment]
Thanks

**Comment by frekele** [comment]
Congratulations for this feature. Beautiful work.

We could have the icon 'microsoft edge' also.

![microsoft-edge](https://cloud.githubusercontent.com/assets/2288215/9098556/01850560-3ba1-11e5-957e-a9ffc41066e8.png)

**Comment by BenLeggiero** [comment]
> @tojonmz Is there an official single color version of the Firefox logo? I'd love to get it in 4.4.0.

@davegandy Perhaps one of these will do: http://brandcolors.net?brands=69

**Comment by CoWinkKeyDinkInc** [comment]
@frekele #7059

**Comment by frekele** [comment]
Thanks @CoWinkKeyDinkInc .
