### ISSUE TITLE
Icon Request: vimeo (non-square)

### ISSUE THREAD

**Issue by onury** [FortAwesome/Font-Awesome#2197]
Thanks for fa-vimeo-square in version 4.0. But the "square" version does not fit my designs. Can you provide a non square version? Thanks.

**Comment by scottphc** [comment]
+1

**Comment by iHectoR** [comment]
+1

**Comment by paroxp** [comment]
+1

**Comment by peiche** [comment]
+1

**Comment by LinearRPH** [comment]
So many +1s

+1

**Comment by goddamnyouryan** [comment]
+1

**Comment by wlcx** [comment]
+1

**Comment by sanderlacaeyse** [comment]
+1

**Comment by taylorperrin** [comment]
+1

**Comment by Shipwreck** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by claytongentry** [comment]
+1

**Comment by MaikaiMa** [comment]
+1

**Comment by justintucker** [comment]
I can echo the same sentiments of displaying the logo without a background. 

On the brand guidelines page: https://vimeo.com/about/brand_guidelines
*When used without a background, the icon should have clear space on all sides, in proportion with the prescribed padding. Please ensure that no other elements (text, images, other icons, lasers, etc.) appear within this space.*

So, maybe it's ok with adequate spacing?

**Comment by alx-khramov** [comment]
+1

**Comment by erezLieberman** [comment]
+1

**Comment by jcallery** [comment]
+1

**Comment by mike-jellybean** [comment]
+1

**Comment by bobtiki** [comment]
+1

The [Vimeo icons Zip file](https://f.vimeocdn.com/downloads/vimeo_icons.zip) now includes the lowercase ‘v’ without any border whatsoever. As @justintucker mentioned, the icon no longer demands placement inside a square, but just with prescribed amounts of padding.

Thanks for the great icons!

**Comment by jrmyptrs** [comment]
+1000

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.
