### ISSUE TITLE
Icon Request: icon-top, icon-bottom

### ISSUE THREAD

**Issue by adamturski** [FortAwesome/Font-Awesome#2209]
Missing icons "to the top" and "to the bottom". Icons would look like those in JDownloader for managing queue (arrow with straight line, arrowhead in contact with the line  ).

**Comment by Frikazoid** [comment]
+1
Thick arrows with a bar at the end.

http://www.jolomi.com/webroot/images/global/navigation/icon-top.png

**Comment by aethior** [comment]
Hi,

Currently there are two icons with arrow and line: [down-to-line](https://fontawesome.com/icons/down-to-line) and [up-to-line](https://fontawesome.com/icons/up-to-line)

cc/ @tagliala

**Comment by adamturski** [comment]
Thanks @aethior for letting me know.
