### ISSUE TITLE
Icon Request: fa-home-o

### ISSUE THREAD

**Issue by texnikru** [FortAwesome/Font-Awesome#2210]
For light style outlined version of home icon will be great.

**Comment by Emil-git** [comment]
+1

**Comment by ShaunR** [comment]
+1

**Comment by nicolasnoakes** [comment]
+1 please. something like this perhaps

![3b096e86-638b-11e5-8b71-188517941575](https://cloud.githubusercontent.com/assets/14802452/10962171/b1f2d5b8-839e-11e5-819a-a33ac032ccc4.png)

**Comment by carpogoryanin** [comment]
+1

**Comment by lzinga** [comment]
+1

**Comment by Dsign** [comment]
:+1: 

Same as existing home / house icon but incorporating an outline.

Such as this :
![house icon draft](https://cloud.githubusercontent.com/assets/20301719/16589255/4ea74aea-42a0-11e6-9095-c3fc3ae8b3b7.JPG)

**Comment by digitalseraph** [comment]
+1

**Comment by mwc320** [comment]
+1

**Comment by sensibleworld** [comment]
This is available in FA Pro: https://fontawesome.com/icons/home?style=light
