### ISSUE TITLE
Icon request: color-bucket

### ISSUE THREAD

**Issue by ixox-pl** [FortAwesome/Font-Awesome#2212]
This icon can be used in wysiwyg editor to fill background color.

![color-bucket](https://f.cloud.github.com/assets/2427075/1398391/eac5acf0-3c9f-11e3-8647-01cb67a56eda.jpg)

**Comment by tagliala** [comment]
ffff

there is a more recent duplicate with more +1s, closing here, no need to +1 #3270 I will do it by myself
