### ISSUE TITLE
Icon Request: fa-picture-portrait-o

### ISSUE THREAD

**Issue by tomw42** [FortAwesome/Font-Awesome#2215]
Hi folks, how about adding these two icons in the web-application section to indicate the orientation of displays, templates images and the like. Just to explain what I mean, two examples.

![portrait](https://f.cloud.github.com/assets/2259401/1398909/1d7ea5dc-3cac-11e3-9b78-57980172a334.png)

thanks

**Comment by c01gat3** [comment]
+1
https://github.com/FortAwesome/Font-Awesome/issues/6653

**Comment by ZeroDotNet** [comment]
Hi lovely people!
+1 for this!

**Comment by JimCook57** [comment]
+1

**Comment by cbravo** [comment]
+1

**Comment by jacobg** [comment]
#6653 was closed as a dupe, even though that request was for paper print layout orientation icons. This request is for device or image display. Each one is a distinct use case, and there should be different icons. Please include print page layout icons as well!

**Comment by sensibleworld** [comment]
This icon now exists: https://fontawesome.com/v6.0/icons/image-portrait?s=solid

Happy to re-open if something else is needed.
