### ISSUE TITLE
Icon Request: icon-cable-drum

### ISSUE THREAD

**Issue by greenskyes** [FortAwesome/Font-Awesome#2228]
![kabeltrommel](https://f.cloud.github.com/assets/5730366/1402152/4a545b44-3ce1-11e3-90dc-40e35cd630ac.png)
Hello, I need a new icon for cable drum. I hope this one, what i created, is ok )
I'm waiting on your request.

Greetings,
Katja

**Comment by aethior** [comment]
Currently there is the `fa-reel` (https://fontawesome.com/icons/reel) icon that can be used in the `clothing-fashion` and  `construction` categories.

Regards.

**Comment by tagliala** [comment]
Given that the 3D approach does not fit Font Awesome general style of design, I will consider this fixed by fa-reel
