### ISSUE TITLE
Icon Request: Desserts

### ISSUE THREAD

**Issue by maru-snm** [FortAwesome/Font-Awesome#2254]
Desserts icons are interesting for restaurants and similar sites.
There´s an icon for coffee but no for dessert.

**Comment by aethior** [comment]
Hi @maru-snm,

Currently there are alot icons for desserts.
For example: [fa-custard](https://fontawesome.com/icons/custard), [fa-cupcake](https://fontawesome.com/icons/cupcake), [fa-cake-slice](https://fontawesome.com/icons/cake-slice) or [fa-ice-cream](https://fontawesome.com/icons/ice-cream).

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, closing here as per the news contributing guidelines

If a dessert is missing, feel free to open a new delicious request
