### ISSUE TITLE
Icon Request: fa-archive-o

### ISSUE THREAD

**Issue by chrisoconnell** [FortAwesome/Font-Awesome#2256]
I would like to request an outlined version of the archive icon. 
This could then be used as an "Un-archive" button label.

**Comment by daniel-baumann** [comment]
+1

**Comment by adamtppaw** [comment]
+1

**Comment by DrewForeman** [comment]
+1

**Comment by linanee** [comment]
+1

**Comment by jacklink01** [comment]
+1

**Comment by joelmellon** [comment]
+1

**Comment by kylebamfordpc** [comment]
+1

**Comment by tagliala** [comment]
This icon is available in FA Pro

https://fontawesome.com/icons/archive?style=regular
