### ISSUE TITLE
Icon Request: icon-shovel

### ISSUE THREAD

**Issue by unluckytoe** [FortAwesome/Font-Awesome#2257]
Some basic landscape tools would be nice. I didn't see shovel in the search.

**Comment by filthyslider** [comment]
+1 - a shovel would be nice

**Comment by malinin13** [comment]
+1 request

**Comment by dangnelson** [comment]
+1

**Comment by bugbee** [comment]
+1 yes please!

**Comment by onedotsix** [comment]
+1
It wanted to use a shovel to represent construction projects, as in ground-breaking. Many other possibilities, too.

**Comment by jbonnier** [comment]
+1

**Comment by dhaupin** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by chicagomom** [comment]
+1 construction projects

**Comment by kpingel** [comment]
👍

**Comment by Melloyell** [comment]
+1

**Comment by josegustavo** [comment]
+1

**Comment by gbgb66** [comment]
+1

**Comment by xboxfly15** [comment]
+1

**Comment by norcalfox** [comment]
+1

**Comment by kbav** [comment]
+1 would appreciate this! As well as other construction symbols.

**Comment by dystopianblue** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a shovel icon to Font Awesome Pro: https://fontawesome.com/icons/shovel?style=solid
