### ISSUE TITLE
Reference for previous versions

### ISSUE THREAD

**Issue by joepie91** [FortAwesome/Font-Awesome#2260]
In the new (4.0) version of Font Awesome, all the icon class names have been changed - for some just the prefix changed, for others the actual name changed. However, no reference is available on the Font Awesome site for the previous versions. 

I (and probably other developers that used previous versions) am still using the previous version of Font Awesome in some projects, and I am now unable to look up names for new icons reliably. I also can't drop in the new version as all the icon class names have changed, and I'd have to change all icons (and cross-reference them between versions) first.

Is there any way to access the reference for the previous version - or even better, also a cross-reference table between old and new class names?

**Comment by badihi** [comment]
The link is broken!

**Comment by tagliala** [comment]
4.7.0 docs: https://fontawesome.com/v4.7.0/
3.2.1 docs: https://fontawesome.com/v3.2.1/
