### ISSUE TITLE
Icon Request: icon-child

### ISSUE THREAD

**Issue by moparlakci** [FortAwesome/Font-Awesome#2262]
It would be nice if there were icons for an Adult, Child and ~~Baby~~

Now I am using icon-male as an adult and icon-user as child :D 

~~Need icons for baby~~

**Comment by KestutisIT** [comment]
+1 for adult. I have list of categories of photoshoots (aerial, child, etc.), and adult/nude icon is missing

**Comment by sensibleworld** [comment]
We have a lot of new "people" related icons in version 6: http://fontawesome.com/download

There's also a "child" icon that's been around for a while now.
<img width="775" alt="Screen Shot 2021-03-30 at 1 39 25 PM" src="https://user-images.githubusercontent.com/529604/113032000-58a31180-915d-11eb-88cd-de1110916240.png">
