### ISSUE TITLE
Icon Request: Courthouse

### ISSUE THREAD

**Issue by christhekeele** [FortAwesome/Font-Awesome#2264]
The growing push to see more open-source Governmental projects could benefit from an explicit governmental icon (re: #926), more general than `fa-gavel` and more territorial than `fa-globe`.

I was imagining something like a [courthouse glyph](http://i.imgur.com/ChMeYKl.png) with softer corners. While still technically judicial, it's a good common generic representation of a governmental institution, as opposed to the gavel or a scale, which tend to be more iconic of just judicial agencies.

**Comment by jmdroldan** [comment]
Something like this ![courthouse 1](https://user-images.githubusercontent.com/39493423/40316397-d61640d6-5d50-11e8-9e09-9c5ddb8ac157.png)

**Comment by tagliala** [comment]
I think https://fontawesome.com/icons/university?style=solid does the job
