### ISSUE TITLE
Icon Request: icon-wave

### ISSUE THREAD

**Issue by wcronyn** [FortAwesome/Font-Awesome#2266]
Think of all the surfers and beach fanatics out there. I don't know if the "surfer" or "beach-goer" translates over to web developer/designer, but I am thinking it's a popular image we can all use and appreciate.

**Comment by ivankotev** [comment]
+1. Will highly appreciate if implemented soon (need to show sea surface temperature). Thanks!

**Comment by Mitemd** [comment]
+1 definitely we need this icon! :)

**Comment by skyepn** [comment]
+1 wave please

**Comment by phili76** [comment]
+1 for a wave icon

**Comment by cadrev** [comment]
+1 for a wave icon! :D

**Comment by vestaxpdx** [comment]
+1 For a wave/sea icon

**Comment by M440** [comment]
+1

**Comment by delineated** [comment]
+1 for wave

**Comment by CarlosHAraujo** [comment]
+1 wave

**Comment by vestaxpdx** [comment]
This request was started over 2 years ago now... I don't think it's ever going to get added :(

**Comment by aplamy** [comment]
+1 wave/sea

**Comment by yeomann** [comment]
+1

**Comment by CallumGrimmer** [comment]
+1

I still have hope.

**Comment by vestaxpdx** [comment]
Maybe 2017 is the year... I doubt it haha

**Comment by fewdji** [comment]
+1

**Comment by coderade** [comment]
+1

**Comment by mitchayo** [comment]
+10

**Comment by nhbeachguy** [comment]
+1 Please to a wave!  80% of the earth is covered in water, how can we not have a wave!

**Comment by mmuscato** [comment]
+1

**Comment by SeloSlav** [comment]
Definitely need this! +1

**Comment by natalka01** [comment]
+1 But....
....for the political 'BlueWave'; (in a different year could be red) 

Also useful: to have some animals, including donkey, elephant.

      Selling point: Who knows how many kilowatts of server power this would save globally rather than clunkier, less efficient version.

**Comment by morgzz** [comment]
+1

**Comment by jasirkt** [comment]
+1

**Comment by Rockburner** [comment]
+1. Would be a very useful icon.
I think the best would be 2 actually - a 'fa-waves', or 'fa-'surf' icon which is 'just' the waves (curling over nicely), and a secondary icon: 'fa-surfer' or 'fa-surfing' which depicts someone riding in the curl (or similar).
Here's hoping!

**Comment by vestaxpdx** [comment]
There is now a sea/water icon in font awesome 5. https://fontawesome.com/icons?d=gallery&q=water

But still no wave/surf icon I don't think :(

**Comment by Rockburner** [comment]
> There is now a sea/water icon in font awesome 5. https://fontawesome.com/icons?d=gallery&q=water
> 
> But still no wave/surf icon I don't think :(

Yeah - but it infers open water to me (think sea or lake), rather than coastal surf, or actual surfing, which is what I think most people on this comment thread are looking for. :)

**Comment by vestaxpdx** [comment]
I know initial request was 2013! One day I hope!

**Comment by TimurDela** [comment]
+1
This can also be interesting for showing sea conditions. It would be nice to have several waves from calm sea to tsunami.

**Comment by leonardotrp** [comment]
+1

**Comment by ryanewtaylor** [comment]
My use case for this icon would be to represent natural hazards, like tidal waves.

**Comment by jbnv** [comment]
My proposal for this icon: A simple wave curve like the one in the background on the Rhode Island license plate.

![Rhode Island license plate](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.grayflannelsuit.net%2Fblog%2Fwp-content%2Fuploads%2F2007%2F07%2Flicense-plate_rhode-island.jpg&f=1&nofb=1)

**Comment by Desdeney** [comment]
+1 for them waves

**Comment by Wingo5315** [comment]
+1

**Comment by kimagameryt** [comment]
+1 That's a good idea!

**Comment by Desdeney** [comment]
+1

**Comment by evadyyc** [comment]
+1 for the wave!

**Comment by wiliamjk** [comment]
+1

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🌊 [U+1F30A](https://emojipedia.org/emoji/%F0%9F%8C%8A/) Water Wave
Also known as `Beach`, `Ocean Wave`, `Sea` and `Waves`.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/wave?f=classic&s=solid
