### ISSUE TITLE
Icon Request: fa-google-play

### ISSUE THREAD

**Issue by Vilscon** [FortAwesome/Font-Awesome#2272]
Hey guys,

I'm really surprised there is no Google-play-store icon and neither a request for it at all. So here am I requesting an FontAwesome Google Play Store icon.

See the attachment for the SVG of the Google Play store. ;)

Thanks!

![google_play_logo svg](https://f.cloud.github.com/assets/5602798/1423088/47b9aad4-4005-11e3-9fb2-16922fb81027.png)

**Comment by vbauer** [comment]
:+1:

**Comment by xvik** [comment]
+1

**Comment by Miniguide** [comment]
+1

**Comment by staradayev** [comment]
+1

**Comment by fxck** [comment]
+1

**Comment by christopher-mh** [comment]
+1

**Comment by coreyleedesigns** [comment]
+ 1

**Comment by halgatewood** [comment]
+1

**Comment by hu2008yinxiang** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by ALPIXELMaiki** [comment]
+1

**Comment by Divites** [comment]
+1

**Comment by dragondisastor** [comment]
+1

**Comment by Ruuudi** [comment]
+1

**Comment by titiomm** [comment]
+1

**Comment by RyanMilby** [comment]
+1

**Comment by geordee** [comment]
+1

**Comment by vonte87** [comment]
+1

**Comment by brentoneill** [comment]
+1

**Comment by javiersantos** [comment]
+1

**Comment by robmarston** [comment]
+1

**Comment by jguerrerope** [comment]
+1

**Comment by Deathnerd** [comment]
+1

**Comment by sanjaykarki** [comment]
+1

**Comment by J4G-** [comment]
+1

**Comment by nvpatil123** [comment]
+1

**Comment by ngandhy** [comment]
+1

**Comment by dotmike** [comment]
+1

**Comment by sergiomeza** [comment]
+ 1

**Comment by Rigiytip** [comment]
+1

**Comment by anuragagarwal561994** [comment]
+1

**Comment by vinayprajapati** [comment]
+1

**Comment by johnbwu** [comment]
+1

**Comment by robksawyer** [comment]
+1

**Comment by chester1000** [comment]
+1

**Comment by hishamBakr** [comment]
+1

**Comment by syzzle** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by MadTiago** [comment]
+1

**Comment by slb235** [comment]
+1

**Comment by kostasx** [comment]
+1

**Comment by AdityaAnand1** [comment]
+1

**Comment by JSW888** [comment]
+1

**Comment by timosadchiy** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by aegamesi** [comment]
+1

**Comment by pd1808** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by korra8888** [comment]
+1

**Comment by Hovind** [comment]
+1

**Comment by ALPIXELMaiki** [comment]
+1

**Comment by axelrindle** [comment]
+1

**Comment by farazfazli** [comment]
+1

**Comment by JesusM** [comment]
+1

**Comment by dbo90** [comment]
+1

**Comment by quicksilver24** [comment]
+1

**Comment by circuitmamu** [comment]
hey in which font awsome version google-icon is available becasue I didn't see in the latest version yet.

**Comment by vietnguyen09** [comment]
+1

**Comment by chrismackie28** [comment]
+1

**Comment by farazfazli** [comment]
@circuitmamu That's because it hasn't been released yet.

**Comment by circuitmamu** [comment]
@farazfazli but in which version it will be available and when is to be plan to release the next version

**Comment by r2DoesInc** [comment]
+1

**Comment by farazfazli** [comment]
@circuitmamu it's currently not known..hopefully soon :)

**Comment by circuitmamu** [comment]
-1

**Comment by itsarjunsinh** [comment]
+1

**Comment by circuitmamu** [comment]
why you people marking +1 in this post because google-play is still not added in it.

**Comment by robmarston** [comment]
@circuitmamu the "+1" is a 'bump' to tell the developers that we'd like this feature added. Essentially the more +1s it has the more popular it is and that may impact their decision when it comes time to prioritize new features for their next release.

**Comment by simonfranz** [comment]
+1

**Comment by BluRaf** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by brettshumaker** [comment]
+1

**Comment by akasranjan005** [comment]
+1

**Comment by staff0rd** [comment]
+1

**Comment by doodlleus** [comment]
+1

**Comment by Jantje19** [comment]
+1

**Comment by feldsam** [comment]
+1

**Comment by circuitmamu** [comment]
-200

**Comment by kristiechow** [comment]
+1

**Comment by My1** [comment]
Instead of always just +1 posting you should also use the reaction feat of github. makes it easier to count those comments.

anyway the icon proposal looks seriously nice.

**Comment by RASK901** [comment]
![googleplay](https://cloud.githubusercontent.com/assets/18583587/14710228/cf2fc1bc-07d4-11e6-90c6-5f8b846665fe.png)
[googleplay.zip](https://github.com/FortAwesome/Font-Awesome/files/229959/googleplay.zip) (SVG File)

+1

**Comment by wshurafa** [comment]
+1

**Comment by circuitmamu** [comment]
-1000

**Comment by circuitmamu** [comment]
-2000

**Comment by circuitmamu** [comment]
-3000

**Comment by My1** [comment]
what do you guys have against this?

**Comment by circuitmamu** [comment]
have you seen this google play icon in font-awesome update since this issue is open. People are eagerly waiting for those trending icons and dev doesn't implement icon and they merge same issue with this and asking to +1. So I am against the time pass with +1. If dev doesn't want to give this icons in updates with fontawesome then this is totally waste of time

**Comment by My1** [comment]
well the GPlay isnt the worst problem, look at the handshake.dave wanted to put this "definitely" into 4.3, we know the result, now the stone is on 5. well I am against +1 pushing when we have reactions, but I think unlike a LOT of these brands who are hardly known to many of us both already in fa and in the issues.

The priorities on icons should be generic icons first then larger brands like google/fb/etc stuff and THEN those mini brands nobody knows.

**Comment by chrismackie28** [comment]
Android had 82.8% market share over IOS's 13.9% in 2015 so I don't agree with you saying it is hardly known. Plus Google wallet is probably less known than google play and that icon is included.

**Comment by My1** [comment]
I didnt say that THIS one is hardly known. I asay that a lot of the stuff in FA is hardly known.

**Comment by circuitmamu** [comment]
currently FA has 4.6.2 latest version and in that new icocs like blind people, deafness, snap chat included that is I think not a popular brand icons then Google Play. Because if Google Play will not in the worlds all apps in the android market has been ruined and how can we Google Play.

**Comment by KenMorico** [comment]
+1

**Comment by Abdalsalaam** [comment]
+1

**Comment by rkhayat** [comment]
+1

**Comment by alkaj** [comment]
+1

**Comment by kristiyandobrev** [comment]
+1

**Comment by samkite** [comment]
+1

**Comment by keremciu** [comment]
+1

**Comment by TiagoDeSousa** [comment]
+1

**Comment by vajrala** [comment]
+1

**Comment by cjkm** [comment]
+1

**Comment by rssatnam** [comment]
+1

**Comment by popisms** [comment]
+1

**Comment by Nicolasdu601** [comment]
+1 good

**Comment by enelbus** [comment]
+1

**Comment by KReguieg** [comment]
+1

**Comment by pete-varga** [comment]
+1 - when is this going to added?

**Comment by Caroline-Elisa** [comment]
+1

**Comment by XavierOlland** [comment]
+1
Can't understand it's not there when you have even pied piper...

**Comment by GT3000** [comment]
+1

**Comment by cerw** [comment]
Please +1

**Comment by 5AMsan** [comment]
+1 pretty please.
BTW, the icon should be updated XD

**Comment by pwendland** [comment]
+1

**Comment by jaavid** [comment]
+1

**Comment by SuperPat45** [comment]
+1

**Comment by My1** [comment]
I think this one should be really getting in, because it's a lot more well known that a lot of the other brands listed on fontawesome which i. frankly speaking never even heard of. like viadeo, yoast, shirtsinbulk and whatnot but not google Play? this is a little bit, well...

**Comment by topherod** [comment]
+1

**Comment by phlegx** [comment]
+1

**Comment by raiaman15** [comment]
+1

**Comment by michaelthorne** [comment]
+1

**Comment by natebeck** [comment]
+1

**Comment by kukreja-vikramaditya** [comment]
+1

**Comment by SvyatoslavLynda** [comment]
+1

**Comment by pachocho84** [comment]
+1

**Comment by smakosh** [comment]
+1

**Comment by hasancse91** [comment]
+1

**Comment by AtheethNair** [comment]
+1

**Comment by korn3l** [comment]
+1

**Comment by taranovegor** [comment]
+1

**Comment by robmarston** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md states "At the moment we are not accepting pull requests containing icons" otherwise I would add the SVG @RASK901 created.

**Comment by Albul** [comment]
+1
Please, I need featured link to google play and app store.

**Comment by hiteshsahu** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[Google Play icon is here](https://sleeklogos.design/web-app/32849/google-play)

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones where [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382) and [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574). 

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by ahmadmmughal** [comment]
+1

**Comment by asadtariq96** [comment]
+1

**Comment by lewisdonovan** [comment]
+1

**Comment by abuabdul** [comment]
+1

**Comment by irfan-dahir** [comment]
+1 Pretty please.

Still waiting for this.

**Comment by zeer** [comment]
+1

**Comment by Gosha98** [comment]
+1

**Comment by 22711** [comment]
+1

**Comment by ferparmur** [comment]
+1

**Comment by folgore95** [comment]
+1

**Comment by PierfrancescoSoffritti** [comment]
Why hasn't this icon been added yet? it is a pretty important brand icon.

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by topherod** [comment]
Finally! Four years later...

**Comment by irfan-dahir** [comment]
Finally!

**Comment by nanilab** [comment]
At last
