### ISSUE TITLE
Icon request: fa-exclamation-octagon

### ISSUE THREAD

**Issue by keithburgie** [FortAwesome/Font-Awesome#2277]
I have a project that requires an octagon version of fa-exclamation-circle or fa-exclamation-triangle. ![error](https://f.cloud.github.com/assets/2370738/1423562/20f2d03a-400d-11e3-87d2-41cd0572830b.png)

http://fortawesome.github.io/Font-Awesome/icon/exclamation-circle/
http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/

Would use as an error or serious alert.

**Comment by jklingen** [comment]
+1

**Comment by Dantevg** [comment]
+1

**Comment by My1** [comment]
@davegandy @tagliala any updates on this? we have 4.6 and I dont see it anywhere.

**Comment by davegandy** [comment]
@My1 This was never intended for 4.6, which was focused on accessibility. I'll add it to 5.0, however.

**Comment by My1** [comment]
this may not have been intended for 4.6 but you told half an eternity ago that it would be definitely in 4.1, and then we had 4.2, 4.3, 4.4 and 4.5 (and the 4.6 obviously) which are (taking out 4.6) 4 other versions where this could have been added.

**Comment by tagliala** [comment]
imho `exclamation-circle` and `exclamation-triangle` are fine for most use cases. Since this request is not popular, probably (and fairly) other requests had priority in Dave's plans so this one went down through milestones

**Comment by My1** [comment]
okay makes sense, albeit that it was designated as "definitely", well anyway. the octagon is also used as Stop sign, especially in europe and therefore can be nicely used for Gandalf'ing (430/You shall not pass) users.

**Comment by sensibleworld** [comment]
<img width="760" alt="Screen Shot 2021-03-30 at 1 36 31 PM" src="https://user-images.githubusercontent.com/529604/113031626-f0ecc680-915c-11eb-9d3c-2ad4769cc45d.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
