### ISSUE TITLE
Using fa-* classes in LESS

### ISSUE THREAD

**Issue by mrmuh** [FortAwesome/Font-Awesome#2279]
hi! at first i wanna thank you for the great work on this project!! its really awesome ;)
ok here is my question ...
i want to use the icon classes (fa 4.0.1) in my own less(css) classes like this:
``` 
@import font-awesome.less
...
button.cancel {
  .btn;
  .btn-default;

  i {
    .fa;
    .fa-ban;
  }
}
``` 
but it seems that the .fa and .fa-ban classes are *not defined* at this point. fyi: iam trying to implement class definitions as proposed in this article http://ruby.bvision.com/blog/please-stop-embedding-bootstrap-classes-in-your-html

**Comment by fpedroza** [comment]
This is a very old issue. Is it still a concern? I ask because I can't get it to work.
