### ISSUE TITLE
Icon request: fa-sidebar-left and fa-sidebar-right

### ISSUE THREAD

**Issue by RicoSoe** [FortAwesome/Font-Awesome#2287]
icon-sidebar-left:
![icon-sidebar-left](https://f.cloud.github.com/assets/5518131/1436709/f11d26d8-415d-11e3-83c3-d1d796fa9ffc.png)

icon-sidebar-right:
![icon-sidebar-right](https://f.cloud.github.com/assets/5518131/1436710/f11d9866-415d-11e3-836e-ee97456e5caf.png)

Hi, for collapsing sidebars, I would like to have a different set that represents the functionality more than using the fa-collapse-o, fa-reorder or directional icons.

Greetz,
Ricardo

Font-Awesome = Awesome!

**Comment by ckati** [comment]
+1

**Comment by thibaultdelor** [comment]
+1

**Comment by erikbrannstrom** [comment]
+1

**Comment by Smok07** [comment]
+1

**Comment by JibstaMan** [comment]
I'd personally like to see the fa-th-list with the left side being a single line, like |☰

**Comment by lipegon** [comment]
+1

**Comment by Disane87** [comment]
Something like this would be really neat (and in reversed order)
![image](https://user-images.githubusercontent.com/956158/90234923-c3971680-de20-11ea-9d59-e4a0cfcfe8b3.png)
