### ISSUE TITLE
Icon request: fa-money-bills

### ISSUE THREAD

**Issue by wakaleo** [FortAwesome/Font-Awesome#2293]
Something like: 
![image002](https://f.cloud.github.com/assets/55986/1442719/cc3e9488-41c5-11e3-8d27-1c0bf17f4513.png)

**Comment by IanSd** [comment]
+1

**Comment by sensibleworld** [comment]
<img width="324" alt="Screen Shot 2021-03-30 at 1 38 00 PM" src="https://user-images.githubusercontent.com/529604/113031822-2691af80-915d-11eb-9fec-dd57983014a8.png">

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of version 6: http://fontawesome.com/download
