### ISSUE TITLE
Icon request: icon-timelineview

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2300]
Hi

really like the library! thanks for your work. for a page im working on, i was looking for an icon to change the view from table/grid to timeline view, but could not find one which would be clear to understand. 

something like this would be great. 

![timeline_klein](https://f.cloud.github.com/assets/5811325/1445487/194b1c2c-4222-11e3-856e-1fe126cf67f1.png)

thanks very much in advance

Kele

**Comment by vlipman** [comment]
+1

**Comment by tagliala** [comment]
There is now an icon to represent a timeline in v6 beta

https://fontawesome.com/v6.0/icons/timeline

Feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) if the implemented icon does not work or if you have suggestions
