### ISSUE TITLE
Icon Request: fa-heart-half, fa-heart-half-o

### ISSUE THREAD

**Issue by ben4d85** [FortAwesome/Font-Awesome#2301]
**A combination of the fa-heart and fa-heart-o icons in order to create a heart that is half full (with and without outline).**

I would like the _fa-heart_ series of icons to be expanded, such that it includes:
- fa-heart (already exists)
- _fa-heart-half_
- _fa-heart-half-o_
- fa-heart-o (already exists)

This is similar to the way that the fa-star series of icons works, i.e.
- fa-star (already exists)
- fa-star-half (already exists)
- fa-star-half-o (already exists)
- fa-star-o (already exists)

I assume that this small addition must be fairly simple to create based on the already existing assets. It would be of great help if this could be added to the project. Many thanks! :)

**Comment by jacobkossman** [comment]
+1

**Comment by nadyav** [comment]
+ 1 for fa-heart-half and fa-heart-half-o.

**Comment by CareLuLu-Gabriel** [comment]
+1

**Comment by kdisneur** [comment]
:+1:

**Comment by montecruiseto** [comment]
++1

**Comment by Martii** [comment]
+1 ... definitely please. :)

**Comment by openevocracy** [comment]
+1

**Comment by sagacitysite** [comment]
+1

**Comment by NickMihaiu91** [comment]
+1

**Comment by bbosternak** [comment]
+1

**Comment by Martii** [comment]
@ben4d85 and just about everyone else here...

[![fa-heart-half-o.svg](https://raw.githubusercontent.com/Martii/UserScripts/master/res/fa-heart-half-o.svg "fa-heart-half-o")](https://github.com/Martii/UserScripts/blob/master/res/fa-heart-half-o.svg)
[![fa-heart-half.svg](https://raw.githubusercontent.com/Martii/UserScripts/master/res/fa-heart-half.svg "fa-heart-half")](https://github.com/Martii/UserScripts/blob/master/res/fa-heart-half.svg)

Just want to make sure these graphic representations is what is being requested? 

I'm far from a vector graphics expert but twiddled enough to get this done with the existing hearts and a difference applied in about hour or so.

**Comment by nadyav** [comment]
A half-heart icon is what being requested here. I also have created a workaround by absolutely positioning a full heart icon (pink) above another one (light gray) and displaying only half of it. Easy enough to implement but requires extra markup and styling. Would be so much easier to have an actual icon.

**Comment by Martii** [comment]
There's actually a third possibility... heart-half *(like demo'd above)* with no fill just the outer stroke... although not sure how good that would look and might look beter with closing the stroke instead of just open.

The fa-heart-half-o.svg demo'd above is what our project is looking for as a visual decrease/increase *(flipped with CSS)* in our rating system.

**Comment by meepoSenpai** [comment]
+1 for the half-heart representations above.

**Comment by joebartels** [comment]
+1 
![screen shot 2016-03-09 at 12 38 13 pm](https://cloud.githubusercontent.com/assets/1977709/13644459/e720e344-e5f3-11e5-9361-2183a2ec1e88.png)

would love (pun intended) the top level heart to be half filled

**Comment by alberto175** [comment]
+1

**Comment by nadyav** [comment]
In the meantime, if you need a half-icon, feel free to use this method. It works for any FontAwesome icon. 
``` html
<ul>
  <li class="fa fa-heart pink"></li>
  <li class="fa fa-heart gray"></li>
</ul>
```
``` css
.fa{
    position:absolute;
    font-size:160px;
    color: #aaaaaa;
}
.gray{
    color:#E72D9E;
    overflow:hidden;
    width:80px;
}
```
https://jsfiddle.net/nadyav/614yyf7q/

**Comment by komarnicki** [comment]
+1

Any progress with this one? That icon would be extra handy when doing rating system based on hearts rather than stars where rating like 4.5 / 5.5 is possible...

**Comment by Jdepontbriand13** [comment]
👍🏽

**Comment by Masa-Shin** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks. This is available in the version 6 alpha release: https://fontawesome.com/download
