### ISSUE TITLE
Icon request: fa-wallet

### ISSUE THREAD

**Issue by rachmason** [FortAwesome/Font-Awesome#2317]
Hi,

The font set is fantastic! A wallet icon would be great addition... !

![payment-methods-wallet-icon](https://f.cloud.github.com/assets/5831044/1453638/e65646a2-42f8-11e3-8abe-53af1024fba4.png)

Perhaps one with some cards/cash poking out (but without showing any specific currencies/card issuers).

![basic3-029_wallet_cash_money-256](https://f.cloud.github.com/assets/5831044/1453651/47d72ed2-42f9-11e3-80b4-a422713b0bf0.png)

I'd be using it as an icon for digital wallet, so maybe a wallet with a lock or cloud poking out as opposed to cards/cash?

![casino-e-wallet](https://f.cloud.github.com/assets/5831044/1453659/75c750a6-42f9-11e3-96f0-00120483ff3f.png)

Apologies for my not-so-great examples - it's why I'd love to see one in your set.

Thanks,
R

**Comment by tchoulihan** [comment]
+1

**Comment by tchoulihan** [comment]
+1

**Comment by ivali** [comment]
+1

**Comment by xf-liam** [comment]
+1

I was surprised there wasn't already one :)

**Comment by nightskylark** [comment]
+1

**Comment by janyksteenbeek** [comment]
+1

**Comment by spscream** [comment]
+1

**Comment by 3zcurdia** [comment]
+1

**Comment by DanielCassela** [comment]
+1

**Comment by djkevinf** [comment]
+1

**Comment by elky** [comment]
+1

**Comment by sitranok** [comment]
+1

**Comment by nielhardt** [comment]
+1

**Comment by timavo** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by ankitraturi** [comment]
+1

**Comment by krunalp1993** [comment]
+1

**Comment by Otonomos** [comment]
+1

**Comment by Hemanth089** [comment]
+1

**Comment by ashep** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by kmels** [comment]
+1

**Comment by serhanters** [comment]
+11

**Comment by erlingormar** [comment]
+1

**Comment by brcolow** [comment]
+1

**Comment by mnegi** [comment]
+1

**Comment by devidas7** [comment]
+1

**Comment by nashcheez** [comment]
+1

**Comment by amitmahbubani** [comment]
+1

**Comment by adrianbader** [comment]
+1

**Comment by DenisUA** [comment]
+ 1

**Comment by bounmed** [comment]
+1

**Comment by ytzvan** [comment]
+1

**Comment by smillas-snee** [comment]
+1

**Comment by askello** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-wallet was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by alxhotel** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by sveatlo** [comment]
+1

**Comment by douglasdeodato** [comment]
+1

**Comment by alexdevid** [comment]
+1

**Comment by bzwd** [comment]
+1

**Comment by Gyvastis** [comment]
+1

**Comment by albertjt** [comment]
+1

**Comment by z00m41k** [comment]
+1

**Comment by pilotandy** [comment]
+1

**Comment by lnmunhoz** [comment]
+1

**Comment by hannanstd** [comment]
+1

**Comment by nejra** [comment]
+1

**Comment by irma-abh** [comment]
+1

**Comment by adipr** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode emoji: 👛 [U+1F45B Purse](http://emojipedia.org/purse/) #222

**Comment by jpdejavite** [comment]
:+1:

**Comment by TheAslera** [comment]
+1

**Comment by TheAslera** [comment]
+1

**Comment by MrFahey** [comment]
+1

**Comment by wael101** [comment]
+1

**Comment by solicomo** [comment]
more than 3 yrs ...

**Comment by joaomantovani** [comment]
+1

**Comment by martingg88** [comment]
+1

**Comment by felipecbarelli** [comment]
+1

**Comment by lucajick** [comment]
+1

**Comment by mussulini** [comment]
or this! :)
![wallet](https://user-images.githubusercontent.com/613885/27816168-7d8f0f92-60bc-11e7-8939-3981e7588f3f.png)

**Comment by andhikamaheva** [comment]
+1

**Comment by urbanlegion** [comment]
+1

**Comment by Avuerro** [comment]
+1

**Comment by aagp** [comment]
+1

**Comment by KabataMacharia** [comment]
+1

**Comment by PhPPgAdminBug** [comment]
+1

**Comment by kostasx** [comment]
+1

**Comment by fabiosammy** [comment]
+1

**Comment by RemiGri** [comment]
+1

**Comment by tiberiu-sevio** [comment]
+1

**Comment by elmakong** [comment]
+1

**Comment by hoangnguyen208** [comment]
+1

**Comment by robclancy** [comment]
How does this still not exist lmao

**Comment by diogorsergio** [comment]
+1

**Comment by miwohlge** [comment]
+1

**Comment by antoniocastanheira** [comment]
+1

**Comment by irman** [comment]
2018, 5 years later, with Font-Awesome 5 (even pro). Still doesn't exists lol.

**Comment by jkirkby91-2** [comment]
+1 come one font awsome the suggested top icon is perfect

**Comment by avihai-developer** [comment]
+1

**Comment by dialex** [comment]
+1

**Comment by dialex** [comment]
Also, why does FontAwesome take so much time to include a new, highly voted/demanded icon? Same thing is happening with the store icon #11963  _This is not Awesome at all :(_

**Comment by robclancy** [comment]
Haha it's a good joke really. There are so many useless icons and then some of the obvious ones get ignored for 4 years.

**Comment by hoangnguyen208** [comment]
I'm done with this, and moved to material icons (https://material.io/icons/).

**Comment by gmmarc** [comment]
+1

**Comment by gmmarc** [comment]
In the meantime, I'm using rotated tablet icon. Not perfect, but does the trick:

![image](https://user-images.githubusercontent.com/7556242/36195386-962e2ab2-116d-11e8-82f1-9ab734a4270d.png)

```html
<i class="fas fa-tablet" data-fa-transform="rotate--90"></i>
```
See it in action: https://jsfiddle.net/hoh1hpyt/

**Comment by gmmarc** [comment]
You can also combine square and circle:

![image](https://user-images.githubusercontent.com/7556242/36195882-34205d84-116f-11e8-992a-806a83c4737a.png)

```html
<i class="fas fa-circle" data-fa-transform="shrink-13 right-4.5" data-fa-mask="fas fa-square"></i>
```

See it in action: https://jsfiddle.net/hoh1hpyt/10/

**Comment by diogorsergio** [comment]
Its been a while since I saw a project this badly managed and disregarding the comunity. Comunication is awful.

**Comment by robclancy** [comment]
@hoangnguyen208 yep we were going to move to FA5 but the whole ecosystem and development seems stale and just not very good in general (shame since their new search site is great). Back to icomoon ultimate.

**Comment by brianmcmichael** [comment]
+1

**Comment by diegolucena** [comment]
+1

**Comment by sensibleworld** [comment]
@robclancy @hoangnguyen208 After (years) of letting a lot of these requests stagnate... we're back on track. We're adding new icons all the time... and this one in particular is in the design queue.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/wallet?style=solid

**Comment by viniman** [comment]
wallet with money inside would be a great icon
