### ISSUE TITLE
Request: Overline Icon

### ISSUE THREAD

**Issue by rodrigopandini** [FortAwesome/Font-Awesome#232]
Request for new icon: overline
Like this:
http://cdn1.iconfinder.com/icondetails/45991/16/edit_overline_icon

Regards,

**Comment by yiannisSt** [comment]
+1

**Comment by no1youknowz** [comment]
3 years and no icon?  the time is now surely?

**Comment by no1youknowz** [comment]
Would love to see this in 5.0!

**Comment by katie1348** [comment]
Could this be a Pro icon?

**Comment by sensibleworld** [comment]
We've added an overline icon to Font Awesome Pro: https://fontawesome.com/icons/overline?style=solid
