### ISSUE TITLE
Icon Request: icon-aud (alias)

### ISSUE THREAD

**Issue by subtlelabs** [FortAwesome/Font-Awesome#2320]
Hi,

Thanks for the great work!
Requesting alias for Australian Dollar. The icon would be same as $

This is useful when the currencies are picked from database & the icon is displayed automatically like
<i class="icon-<?php echo $currency; ?>" ></i>

Thanks

**Comment by lukeoliff** [comment]
I managed to do this with some very easy CSS, I've commended on #3028 
https://github.com/FortAwesome/Font-Awesome/issues/3028#issuecomment-117954373

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
