### ISSUE TITLE
Icon Request: new alias for Thumb-tack: 'Pin'

### ISSUE THREAD

**Issue by kait85** [FortAwesome/Font-Awesome#2328]
somewhat difficult to find right now, (if someone is looking for the user story of 'pinning' something).  I think giving it the name pin as well would simplify things

**Comment by alixeb** [comment]
+ 1

**Comment by benkle** [comment]
+1

**Comment by tagliala** [comment]
I'm going to close this because there is a filter 

![image](https://cloud.githubusercontent.com/assets/556268/7533391/569ec35e-f571-11e4-8151-b19d4cd32786.png)
