### ISSUE TITLE
Icon Request: fa-dot-square, fa-dot-square-o and fa-dot-circle

### ISSUE THREAD

**Issue by goodwillcoding** [FortAwesome/Font-Awesome#2332]
Esteemed maintainers,

There is a fa-square-o and fa-dot-circle-o. However there is no fa-dot-square-o and no easy way to stack existing one. There is also no fa-dot-square.

My use cases deals with "fa-square-plus and fa-square-minus" and I find icons like these highly useful.

Respectfully,

Loving FA user

**Comment by dbkirk4211** [comment]
I agree!

**Comment by dbkirk4211** [comment]
Bump

**Comment by tagliala** [comment]
I need this request to be splitted in `fa-dot-square, fa-dot-square-o` and `fa-dot-circle` (as per [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)).

Please also clarify the use case for `fa-dot-square, fa-dot-square-o`
