### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by arcanis** [FortAwesome/Font-Awesome#2352]
Hi,

Is it safe to assume that an icon will always have the same character code, regardless FontAwesome updates (for example, `\f0da` for the arrow) ? It would be very useful for `:before` and `:after` pseudo-classes.

Thanks,

**Comment by sensibleworld** [comment]
I know this is a super late reply, but in general, we try not to change an icon's unicode unless there are extenuating circumstances. And if/when we do, it will always be noted in a new version's changelog.
