### ISSUE TITLE
Icon Request: icon-desktop tower

### ISSUE THREAD

**Issue by tlieaxu** [FortAwesome/Font-Awesome#2361]
I am aware there is a fa-desktop and laptop though for what I am looking for I need a computer tower, not the imac style one that is currently available unless I somehow missed it.

obviously I don't need it to look exactly like this but mainly for the idea.

![haf 912 combat](https://f.cloud.github.com/assets/5873744/1486687/93ec05d6-4727-11e3-8d68-a2415eb298b3.png)

Thanks for your time.

**Comment by Dennis14e** [comment]
+1

**Comment by sheebypanda** [comment]
+1

**Comment by elbel86** [comment]
+1

**Comment by tkfeeny** [comment]
+1

**Comment by gpablod** [comment]
Yes please! +1

**Comment by LoveGal8** [comment]
+1

**Comment by tkaden4** [comment]
+1

**Comment by dannn-o** [comment]
+1

**Comment by sensibleworld** [comment]
Does this new `computer` icon satisfy this request? https://fontawesome.com/icons/computer?s=solid

**Comment by pjotrvdh** [comment]
That is exactly wat I was looking for
