### ISSUE TITLE
Complete Iconset with Icons of Joomla 3.2

### ISSUE THREAD

**Issue by mcom82** [FortAwesome/Font-Awesome#2369]
I would be glad if you can complete the icon list with the icons of Joomla 3.2

(the icon list you find here: http://ndev.nl/jui/index.php/icons)

Most interesting for me are these categories:
- Screens
- Tools (Database, Dashboard..)
- Stats

**Comment by aethior** [comment]
I think this request can be considered solved.

cc/ @tagliala
