### ISSUE TITLE
Icon Request: fa-mouse (PC)

### ISSUE THREAD

**Issue by thotzl** [FortAwesome/Font-Awesome#2376]
fa already have a keyboard-icon but i miss the mouse-icon.

a quick and dirty visualization of my idea:

![mouse](https://f.cloud.github.com/assets/1067907/1499930/ccb9b52a-4867-11e3-871e-65ebcec747c8.png)

**Comment by jaruba** [comment]
+1 for mouse icon

**Comment by jdubsf** [comment]
+1

**Comment by chnwentao** [comment]
+1

**Comment by Bit32** [comment]
+1

**Comment by spoonmuppet** [comment]
+1

**Comment by umutcoskun** [comment]
+1

**Comment by VasilyPolyakov** [comment]
+1

**Comment by undeman** [comment]
+1

**Comment by Entwanderer** [comment]
+1

**Comment by Miniwe** [comment]
+1

**Comment by paneum** [comment]
+1

**Comment by nachumie** [comment]
+1

**Comment by LiamAttClarke** [comment]
+1

**Comment by Daniesy** [comment]
+1

**Comment by mondalaci** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by roushan** [comment]
+1

**Comment by merraysy** [comment]
+1

**Comment by josecaballero** [comment]
+1

**Comment by T1k3-HU** [comment]
+1 **fa-mouse**

![mouse](https://cloud.githubusercontent.com/assets/8018130/14884993/03fd4f9e-0d49-11e6-8b65-c4f04c308af5.png)

**Comment by zedtux** [comment]
+1

**Comment by andrewnmat** [comment]
+1

**Comment by Ionaru** [comment]
+1

**Comment by RodrigoCard** [comment]
I am suprised that there are icons for most PC hardware (Monitor, Keyboard, Gamepads) but there arent for a Mouse! :/

+1 👍

**Comment by QuentinPolantis** [comment]
+1

**Comment by alexpriceco** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by solipsy** [comment]
+1, and it would be very good if there were three - mouse only, and mouse with left button pressed, and another with right button pressed

**Comment by lindstrm** [comment]
+1

**Comment by HimbeersaftLP** [comment]
+1

**Comment by TiesMB** [comment]
+1

like @evgenyCoding's design, left one, but a bit larger corner radius

**Comment by rdmdk** [comment]
+1

**Comment by dasprinzip** [comment]
i would like to see a fa-mouse-click-left; fa-mouse-click-right, fa-mouse-wheel-down, fa-mouse-wheel-up.
the click i like: https://www.flaticon.com/free-icon/mouse-left-button_32041
but i am missing the mousewheel, like here: https://www.shutterstock.com/de/image-vector/computer-mouse-buttons-icon-one-color-470509538
but still missing the direction of mouse-wheel.
with that one it would be possible: https://www.shutterstock.com/de/image-vector/scroll-down-computer-mouse-icon-vector-516390889?src=mMYhb7vW7ZIt5zFpoJOfnw-1-16
but i dont like the style

:)

**Comment by KevynTD** [comment]
> i would like to see a fa-mouse-click-left; fa-mouse-click-right, fa-mouse-wheel-down, fa-mouse-wheel-up.
> the click i like: https://www.flaticon.com/free-icon/mouse-left-button_32041
> but i am missing the mousewheel, like here: https://www.shutterstock.com/de/image-vector/computer-mouse-buttons-icon-one-color-470509538
> but still missing the direction of mouse-wheel.
> with that one it would be possible: https://www.shutterstock.com/de/image-vector/scroll-down-computer-mouse-icon-vector-516390889?src=mMYhb7vW7ZIt5zFpoJOfnw-1-16
> but i dont like the style
> 
> :)

I thinking it need have Left click, Middle click and Right click, more or less in this style:
https://www.vectorstock.com/royalty-free-vector/right-click-mouse-icon-vector-2879365

I will use in my project!

**Comment by gjtyler** [comment]
Anything close to the above would be better than use the "pointer" icon. I can't help but think my actual mouse pointer is there.

**Comment by sekra24** [comment]
+1 for pc mouse icon!

How stupid is this looking 😄 

![fa-mouse](https://user-images.githubusercontent.com/11167542/54071493-667f5480-426d-11e9-950e-9a0e8b311726.JPG)

**Comment by oliversiegel** [comment]
> +1 **fa-mouse**
> 
> ![mouse](https://cloud.githubusercontent.com/assets/8018130/14884993/03fd4f9e-0d49-11e6-8b65-c4f04c308af5.png)

This one is great! Can also add left click, right click, and double click
![Untitled-1](https://user-images.githubusercontent.com/35322693/56687342-e9783500-668a-11e9-8b5d-62058562d5e3.png)

**Comment by BigActual** [comment]
9 years, wow. This one seems like a legit request. Is there a reason this is not a thing? Asking for a friend.

**Comment by spoonmuppet** [comment]
Because 9 years ago nobody was going to be using a mouse any more. Touch screens were starting to be pervasive and the idea that somebody would still be using a mouse as their primary pointing device within the next six months seemed insane. Yet here we are.

Seriously though. It's time now. Can we please have fa-mouse?

**Comment by erichlotto** [comment]
We need this. I'm surprised we still don't have it...

**Comment by JoeHana** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a couple of "mouse" icons to version 5.11:

https://fontawesome.com/icons/mouse?style=solid
https://fontawesome.com/icons/mouse-alt?style=solid
