### ISSUE TITLE
Icon Request: fa-chevron-o-*direction* outline chevron

### ISSUE THREAD

**Issue by blowsie** [FortAwesome/Font-Awesome#2377]
Would be nice to have an outline version of the existing chevron icons

**Comment by laksmipati** [comment]
Me too, please

**Comment by guyvdn** [comment]
I was able to do it like this:
```
<span class="fa-stack">
    <i class="fa fa-circle fa-stack-1x"></i>
    <i class="fa fa-chevron-circle-*direction* fa-inverse fa-stack-1x"></i>
    <i class="fa fa-circle-thin fa-stack-1x"></i>
</span>
```

**Comment by tagliala** [comment]
Hi, I'm sorting out old issues 😅 

Those icons are available in FA 5 Pro:
https://fontawesome.com/icons/chevron-circle-up?style=regular
https://fontawesome.com/icons/chevron-circle-right?style=regular
https://fontawesome.com/icons/chevron-circle-down?style=regular
https://fontawesome.com/icons/chevron-circle-left?style=regular

Of course those could be achieved in FA5 Free with the use of the layering feature

https://fontawesome.com/how-to-use/on-the-web/styling/layering
