### ISSUE TITLE
Icon request: icon-clean (icon-broom / icon-brush)

### ISSUE THREAD

**Issue by rodrigopandini** [FortAwesome/Font-Awesome#239]
Request for new icon: clean 
Something like this:
http://www.iconfinder.com/icondetails/55586/64/clean_icon
http://www.iconfinder.com/icondetails/15273/32/brush_clean_clear_sweep_icon
http://findicons.com/icon/235501/edit_clear?id=348445

**Comment by GaryChen** [comment]
+1

**Comment by DarthCharles** [comment]
+1

**Comment by dangnelson** [comment]
+1 to be used for reprinting cleaning / sanitation services

**Comment by wandersonwhcr** [comment]
+1

**Comment by cvsguimaraes** [comment]
+1

**Comment by sschimmel** [comment]
+1

**Comment by cjroth** [comment]
+1

**Comment by mune83** [comment]
+1

**Comment by amine7592** [comment]
+1

**Comment by nicolasteodosio** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by hazafantasy** [comment]
+1

**Comment by audreyaw** [comment]
+1

**Comment by leandro-freitas-softdevelop** [comment]
+1

**Comment by leandro-freitas-softdevelop** [comment]
https://github.com/tzusman/custom-font-icons

**Comment by SylvainCorlay** [comment]
+1

**Comment by frekele** [comment]
![broom](https://cloud.githubusercontent.com/assets/2288215/7925956/b3023ab6-08a1-11e5-90b9-1f7459400ae6.png)

https://customfonticons.com/ source by 'Dave Gandy' @tzusman, in https://github.com/tzusman/custom-font-icons.
SIL Open Font License (OFL) - http://scripts.sil.org/OFL

**Comment by jeff1326** [comment]
+1!!!!!

**Comment by atstp** [comment]
+1 for an `fa-cleanup`

![fa-cleanup ideas](https://cloud.githubusercontent.com/assets/5891072/8345025/0e16ba40-1a9e-11e5-9408-6d431041aea2.png)

### [here's a gist](https://gist.github.com/atstp/6260f6629d96a73045b5) 

Feel free to fork/share/star/take; fingers crossed more ideas floating around will help this move faster.

**Comment by AliLozano** [comment]
+1

**Comment by frlinw** [comment]
+1

**Comment by stl-winniechan** [comment]
+1

**Comment by peterkle** [comment]
+1

**Comment by cjroth** [comment]
![1375655502_qvoxljvytc2eoazdb581_witch_broomstick](https://cloud.githubusercontent.com/assets/582130/9156061/62e533d2-3e9b-11e5-8c5a-af709f90972e.jpg)

**Comment by silverkorn** [comment]
@cjroth :facepalm: :laughing:

**Comment by makzk** [comment]
This is from 2012... but nothing yet? :cry:

**Comment by jhuang314** [comment]
+1

**Comment by andersonrosilva** [comment]
+1

**Comment by colemanw** [comment]
+1

**Comment by cd10anil** [comment]
+1

**Comment by andregsilv** [comment]
+1

**Comment by loureirorg** [comment]
+1

**Comment by dduft** [comment]
:+1:

**Comment by invot** [comment]
+1 and my partial duplicate request (https://github.com/FortAwesome/Font-Awesome/issues/8178)

**Comment by alexpana** [comment]
+ 1

**Comment by G-Driver** [comment]
+1

**Comment by rdbmax** [comment]
+1

**Comment by isaachinman** [comment]
+1

**Comment by tomascharad** [comment]
+1

**Comment by felipePrandini** [comment]
+1

**Comment by adilsoncarneiro** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by scasic** [comment]
+1

**Comment by navarroaxel** [comment]
+1

**Comment by ChNitz** [comment]
+1

**Comment by cristian-eriomenco** [comment]
+1 since Jun 5, 2012, any updates on this one. I cannot find any fa-clean*....? Am I missing something?

**Comment by seyedmmousavi** [comment]
+1 it is so necessary. I surprised why this issue is created since 2012 and still it is open! Perhaps we can see it until 2020!!!!!!!!
Very ACTIVE team!

**Comment by frekele** [comment]
@tagliala ???

**Comment by colemanw** [comment]
@seyedmmousavi if only sarcasm had the power to write software.

**Comment by esetnik** [comment]
wow +1

**Comment by SylvainCorlay** [comment]
> @seyedmmousavi if only sarcasm had the power to write software.

They should ask for a refund.

**Comment by Anozer** [comment]
+1

**Comment by dominik-beste** [comment]
+1

**Comment by jenzener** [comment]
+1

**Comment by nikitul** [comment]
+1

**Comment by yobre** [comment]
+1

**Comment by etherElric** [comment]
+1

**Comment by kevfulford** [comment]
+1!

**Comment by onantibiotics** [comment]
+1

**Comment by nickbouton** [comment]
+1

**Comment by stefanigustavo** [comment]
+1

**Comment by artemkaint** [comment]
+1

**Comment by yupswing** [comment]
+1

**Comment by uklimaschewski** [comment]
+1

**Comment by TonisOrmisson** [comment]
+1

**Comment by luizphilipi** [comment]
+1

**Comment by Smok07** [comment]
+1

**Comment by nicolasbadia** [comment]
+1

**Comment by spoonzy** [comment]
+1

**Comment by yaelduckwen** [comment]
+1

**Comment by dzh21** [comment]
+1

**Comment by aboglioli** [comment]
+1

**Comment by zunjae** [comment]
+1

**Comment by dedep** [comment]
+1

**Comment by rafamem** [comment]
+1

**Comment by Pierlo1** [comment]
+1

**Comment by jmsegrev** [comment]
+1

**Comment by nicozimmermann94** [comment]
+1

**Comment by frasator** [comment]
+1

**Comment by agaor** [comment]
+1

**Comment by sysiler** [comment]
+1

**Comment by marcelobdsilva** [comment]
+1

**Comment by mastizada** [comment]
+1

**Comment by C-Bouthoorn** [comment]
Let me just +1 this too. Weird that they still didn't notice this. Maybe something for FA5?

**Comment by silverkorn** [comment]
Might be part of the pro version?
OMG! please no!

**Comment by mehmetyildiz94** [comment]
+1

**Comment by scasic** [comment]
+1

**Comment by jaimeokhuysen** [comment]
+1

**Comment by rotheblog** [comment]
+1

**Comment by DGitterman** [comment]
+1

**Comment by dano000** [comment]
+1

**Comment by davidvilla** [comment]
+1

**Comment by blieb** [comment]
+1

**Comment by IsmiKin** [comment]
+1

**Comment by Donaldini** [comment]
+1

**Comment by bmkrocks1** [comment]
+1

**Comment by notridan** [comment]
A need this!!

**Comment by Anecho** [comment]
+1

**Comment by janzankowski** [comment]
+1

**Comment by akhilcb** [comment]
I need this too.

**Comment by visualpharm** [comment]
I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The clean icon is here](https://icons8.com/icon/14160/broom).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by nabab** [comment]
+1

**Comment by programoo** [comment]
+1

**Comment by trenta3** [comment]
+1

**Comment by blissjonathan** [comment]
+1

**Comment by Irostovsky** [comment]
+1

**Comment by akhilcb** [comment]
Any update on this? Looks like people were asking for last 5 years for this, is there any chance at all? Or is it abandoned.

**Comment by KakaCarrotCake** [comment]
+1

**Comment by srycroft** [comment]
+1

**Comment by aboglioli** [comment]
I don't remember why I needed it but I still think it's necessary

**Comment by aanair08** [comment]
+1   clean icon , it's necessary

**Comment by krv** [comment]
+1

**Comment by alouks** [comment]
This issue has been opened since 2012. Is there going to be a decision made?

**Comment by NoCodeMonkey** [comment]
+1

**Comment by karthiknamburu** [comment]
+1

**Comment by luizcarraro** [comment]
+1

**Comment by BrunoAderaldo** [comment]
+1

**Comment by barrycox** [comment]
(y) +1  seem to be a theme since 2012...

**Comment by gerasev-kirill** [comment]
+1

**Comment by anandchakru** [comment]
ahem,. yes pls

**Comment by Kalaijagdai** [comment]
+1

**Comment by efoxbr** [comment]
+1

**Comment by atkawa7** [comment]
+1

**Comment by darwayne** [comment]
+1

**Comment by taramk** [comment]
+1. I'm really surprised this isn't already included. Our use case is a bulk archive tool to "clean up" unused items.

**Comment by deen13** [comment]
+1

**Comment by ragavanrajan** [comment]
+1

**Comment by githubuser1101** [comment]
+1 - was also surprised when I went to look for some sort fo clean icon that nothing like that was available even in version 5.

**Comment by laurentvergnaud** [comment]
+1

**Comment by sergioRicardo1995** [comment]
+1

**Comment by mcnuca** [comment]
+1

**Comment by nshahpazov** [comment]
+1

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by sensibleworld** [comment]
Let's sweep this request away. https://fontawesome.com/icons/broom?style=solid

**Comment by maxisam** [comment]
maybe it is just me, but does anyone feel it looks more like a brush pen than a broom?

**Comment by alouks** [comment]
Yes, but don't complain about it. It took almost 6 years to get it implemented.
