### ISSUE TITLE
Icon request: fa-symfony

### ISSUE THREAD

**Issue by jtwebb** [FortAwesome/Font-Awesome#2392]
The Symfony framework logo as well as other frameworks. I could create several requests or attach them all here.

<s>
Codeigniter
Laravel
FuelPHP
CakePHP
</s>
And a general logo for frameworks; maybe something like a wireframe? I'm no good with illustrator or I'd help make them myself. These would be great for developers. Most of us don't have a very good design sense :) and need all the help we can get in displaying what we do and what we're capable of working on.

![logo_symfony](https://f.cloud.github.com/assets/1922539/1506584/48d6cb24-4936-11e3-8379-2581c05bf310.png)

**Comment by shefik** [comment]
+1

**Comment by Kraim88** [comment]
+1

**Comment by FabianKoestring** [comment]
:+1: What about Zend-Framework?

**Comment by alex-ception** [comment]
+1

**Comment by mgrundkoetter** [comment]
+1 for Symfony

**Comment by adamreyher** [comment]
+1

**Comment by Ravetracer** [comment]
I've just saw this request and see, if I can help out.
Most of the logos can be used, but it's not allowed to create derivate works of the CakePHP logo.
Also the most requested Symfony logo could be a problem. It seems, it's not allowed to remove the "Symfony" text from the main logo: http://symfony.com/trademark

**Comment by Ravetracer** [comment]
Ok, just figured out, that it's not wanted to help out with new icons:

--> Please do not submit new icons.

**Comment by yamiko-ninja** [comment]
@fabpot do you think they can add it without the text?

**Comment by marjolainerival** [comment]
+1

**Comment by fabpot** [comment]
Sure, the icon without the Symfony text looks good to me.

**Comment by ucay** [comment]
+1

**Comment by farizyoga** [comment]
+1 for symfony logo

**Comment by farmer-duck** [comment]
+1

**Comment by thotzl** [comment]
👍 👍 👍 👍  :)

**Comment by thomasbird1984** [comment]
+1

**Comment by Pierstoval** [comment]
👍 too for this logo, not a hard task

**Comment by IndraGunawan** [comment]
+1

**Comment by jmleroy** [comment]
+1

**Comment by Kraddle** [comment]
+1

**Comment by runawaycoin** [comment]
+1

**Comment by ostrolucky** [comment]
👎 , this is slippery slope. Use case of such icon is not common enough.

**Comment by CoalaJoe** [comment]
+1

**Comment by Taminoful** [comment]
+1 I would love to see a Symfony icon in Font Awesome!

**Comment by davidmosna** [comment]
Why is this issues still open and no symfony logo is available yet?

**Comment by SteppingHat** [comment]
+1

**Comment by iiirxs** [comment]
+1

**Comment by martijnhartlief** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by epourail** [comment]
+1

**Comment by mmoreram** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by nea** [comment]
+1

**Comment by androozka** [comment]
+1

**Comment by 5-1** [comment]
+1

**Comment by TheGrimX** [comment]
+1

**Comment by ZFLloyd** [comment]
+1

**Comment by BenFenner** [comment]
We really  could use this for our project. Please implement if possible.

**Comment by alterphp** [comment]
:+1:

**Comment by nicoweb** [comment]
+1

**Comment by Legenyes** [comment]
+1

**Comment by ktherage** [comment]
+1

**Comment by Medhi42** [comment]
+1

**Comment by leon38** [comment]
+1

**Comment by Killium** [comment]
👍

**Comment by matudelatower** [comment]
+1 for Symfony Logo

**Comment by vadim2991** [comment]
+1

**Comment by miniche** [comment]
+1

**Comment by piotrex41** [comment]
+1

**Comment by CarpentierMartin** [comment]
+1

**Comment by peter-gribanov** [comment]
Please stop spamming. Comments are needed for discussion. You always can vote to [this issue](#issue-22385288).

**Comment by wiglesias** [comment]
+1 for symfony logo

**Comment by TBoileau** [comment]
+1

**Comment by emullaraj** [comment]
+1

**Comment by felipsmartins** [comment]
:+1:

**Comment by alexhaker** [comment]
+1

**Comment by Bunkermaster** [comment]
:+1

**Comment by chicaum** [comment]
+1

**Comment by AchillesKal** [comment]
+1

**Comment by aferrandini** [comment]
👍

**Comment by talbs** [comment]
Here you go, gang - https://fontawesome.com/icons/symfony?style=brands
Thanks for the patience and for continuing to vote this up! :smile:

**Comment by Pierstoval** [comment]
Thank you very much ♥♥

**Comment by Kraddle** [comment]
Good job  ! Thank You !

**Comment by thomasbisignani** [comment]
:ok_hand:
