### ISSUE TITLE
Font Awesome Icon PHP Array

### ISSUE THREAD

**Issue by wpexplorer** [FortAwesome/Font-Awesome#240]
Anyone have an array of all the awesome font icons including version 2.0 icons that we can use in PHP?

thanks!

**Comment by Jany-M** [comment]
I tried
`
$pattern = '/\.(fa-(?:\w+(?:-)?)+):before\s+{\s*content:\s*"(.+)";\s+}/';
$subject =  file_get_contents('css/font-awesome.min.css');
preg_match_all($pattern, $subject, $matches, PREG_SET_ORDER);
`
But $matches is empty.
I tried using the script [here](https://regex101.com/r/mX1kT2/1) and it only matches the first occurance.

Am I missing something? :/

**Comment by ryanstockau** [comment]
@Jany-M I added 'g' to the modifiers box to the right of the expression box in your link to make it global, which meant it matched all occurrences. Is that what you're looking for?

**Comment by Jany-M** [comment]
@ryanstockau thank you :)
