### ISSUE TITLE
Icon Request: Middle finger

### ISSUE THREAD

**Issue by JonDum** [FortAwesome/Font-Awesome#2402]
I want an outline of a middle finger for my Privacy Policy that makes certain statements towards certain privacy-invading US government agencies.

**Comment by nkassis** [comment]
+1

**Comment by meggle** [comment]
+1

**Comment by dabaliyan** [comment]
+1   why not

**Comment by Murilirum** [comment]
+1 I need this for a few funny web apps I have in mind.

**Comment by nedstoyanov** [comment]
+1 I need this to indicate a failing build on our build dashboard

**Comment by EnoahNetzach** [comment]
+1

**Comment by codynguyen1116** [comment]
yes please
+1

**Comment by nicolasfeyer** [comment]
+1

**Comment by kolobus** [comment]
+1

**Comment by ReSpawN** [comment]
Definitely +1

**Comment by HawkRytt** [comment]
+1 This needs to be done

**Comment by man-b-e-a-s-t** [comment]
+1 need it for uncooperative browsers

**Comment by tenebroso** [comment]
+1

**Comment by UdoKifferbrehl** [comment]
+1

**Comment by Schokobecher** [comment]
3 years later - is there still hope?

**Comment by AustinPaquette** [comment]
> 3 years later - is there still hope?

**Comment by rvhue** [comment]
+1

**Comment by Zax** [comment]
+1

**Comment by Qonq** [comment]
+1

**Comment by eake** [comment]
+1

**Comment by vinnyamp** [comment]
+1

**Comment by fluffy-samurai** [comment]
+1

**Comment by ernestbuffington** [comment]
+ 1 on that middle finger, I need asap. Thanks for all the hard work...

**Comment by INGCRENGIFO** [comment]
+1

**Comment by Lomzy66** [comment]
@JonDum  A colleague and I were just joking about this(blame the users for this line of thought xD) and I went searching :+1:  

How does this work though? I see there is nobody assigned to the task as of yet. 
Do we get to officially vote apart from the "+1" comments on here?

**Comment by dextermb** [comment]
👍

**Comment by djhype** [comment]
👍

**Comment by StevenKrise** [comment]
:thumbsup:

**Comment by Wingo5315** [comment]
I don't think this would ever get added, but +1.

**Comment by popisms** [comment]
+1

**Comment by ATLAdamL** [comment]
+1

**Comment by JonDum** [comment]
I'm baffled that people are still consistently commenting on this 5 years later.

Can we actually make this happen? 
Maintainers, if I toss you an actual middle finger svg in FA style would you merge?

**Comment by sensibleworld** [comment]
This icon joins the ranks of such esteemed icons as `fa-dumpster-fire` and `fa-poo-storm`:

https://fontawesome.com/icons/hand-middle-finger?style=solid

**Comment by AstiriL** [comment]
I needed it, so I went here, realised it was done 14 days ago and I have a older version. I am so surprised, ty!
