### ISSUE TITLE
Icon request: fa-info-square

### ISSUE THREAD

**Issue by jvanasco** [FortAwesome/Font-Awesome#2403]
It would be great to extend the `fa-info` family ( `fa-info` , `fa-info-circle` ) to have `fa-info-square` ( and even `fa-info-square-o` ).

this would have the same treatment as the `fa-minus` family. 

the `square` style looks more button-like, and is useful as buttons on it's own ( which is how a lot of info icons are used across a variety of sites )

**Comment by aethior** [comment]
Hi @jvanasco,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/square-info

Regards.

cc/ @tagliala
