### ISSUE TITLE
Icon Request: icon-sheaf, icon-sheaf-ban (Wheat / Gluten Free / celiac)

### ISSUE THREAD

**Issue by spacedevin** [FortAwesome/Font-Awesome#2405]
Hey!

Everyone here at crunchbutton loves your icons. But we are in the need for some more food related icons too.

thanks so much!

**Comment by G-Driver** [comment]
+1

**Comment by llaski** [comment]
+1

**Comment by aambr** [comment]
+1

**Comment by oriadam** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by tagliala** [comment]
Also adding the non-banned version of the icon, so we could represent both gluten and gluten free foods

**Comment by webscot** [comment]
+1 See icon suggestions in #8294

**Comment by Luca7993** [comment]
+1

**Comment by tarunaggarwal54** [comment]
+1

**Comment by mikegnagy** [comment]
+1

**Comment by Crissov** [comment]
Related: 🌾 [U+1F33E](http://emojipedia.org/ear-of-rice) Ear of Rice Unicode emoji #222

**Comment by DDuTCH** [comment]
+1

**Comment by reinhochstenbach** [comment]
+1

**Comment by misterbowen** [comment]
+1

**Comment by pbysh** [comment]
+1

**Comment by melojoy** [comment]
+1

**Comment by oriadam** [comment]
+ icon-vegan:
http://images.sasongsmat.nu/vegetarianmark/vegetarian-mark.svg

**Comment by simistern** [comment]
+1

**Comment by ngandhy** [comment]
+1

**Comment by arzynik** [comment]
...and a few years later! this is probably a better GF option


![image](https://user-images.githubusercontent.com/27974/38908091-99a1aa5c-4273-11e8-8e05-e3380363f992.png)

**Comment by mrmaloof** [comment]
+1

**Comment by sensibleworld** [comment]
We now have [`wheat-slash`](https://fontawesome.com/v6.0/icons/wheat-slash?s=solid) and [`wheat-awn-slash`](https://fontawesome.com/v6.0/icons/wheat-awn-slash?s=solid) icons.

Do these work, or is something more specific needed to satisfy this request?

**Comment by sensibleworld** [comment]
In addition to the above, we've just added a `circle-gf` icon: https://fontawesome.com/icons/circle-gf?f=classic&s=solid
