### ISSUE TITLE
Icon Request: LP (vinyl)

### ISSUE THREAD

**Issue by fcgrx** [FortAwesome/Font-Awesome#2406]
Would love to see a CD and an LP, separate icons, for the many band websites I build. The music icon doesn't cut it, as it doesnt distinguish between the formats -- CD and VINYL. the existing cloud icons work fine for digital downloads.

**Comment by joelhdzfdz** [comment]
+1

**Comment by ziomyslaw** [comment]
+1

**Comment by ndoz** [comment]
:+1:

**Comment by markkes** [comment]
+1

**Comment by nagulian** [comment]
+1

**Comment by dr0ptheb0mb** [comment]
+1

**Comment by mkody** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by popisms** [comment]
+1

**Comment by thde** [comment]
+1

**Comment by kynetiv** [comment]
+1

**Comment by mindfailure** [comment]
+1 

I'd also throw in the bag cassette, mini disc and CD-R as these are really useful on discography sites which list entire back catalogues.

**Comment by m-alo** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by iGormilhit** [comment]
:+1:

**Comment by hanshenrik** [comment]
+1

**Comment by LaatR** [comment]
+1

**Comment by michaelfrye** [comment]
+1

**Comment by emaynard04** [comment]
+1

**Comment by rokfresh** [comment]
+1

**Comment by morgyface** [comment]
+1
Was looking for a brand icon for Discogs but a record/vinyl icon would do the trick nicely.

**Comment by cburmeister** [comment]
@morgyface you might want to review our brand guidelines [here](https://www.discogs.com/brand). 😄

**Comment by morgyface** [comment]
@cburmeister Useful and good to know. It'd be rad if the fontawesome crew would add your simplified vinyl mark. Which I would, of course, use in #000 or #333.

**Comment by bonyboy** [comment]
+1

**Comment by antoniu86** [comment]
+1

**Comment by design4music** [comment]
+1 - yes, this would be useful for any music websites. I would call it icon-record (no need in distinguishing CD/LP). A sample image is attached.
![nocoverart](https://cloud.githubusercontent.com/assets/28266309/25586212/0fe24802-2ea7-11e7-8c81-49da87c5eedb.jpg)

**Comment by Petrucheqa** [comment]
+1

**Comment by lxstudio** [comment]
+1

**Comment by herbadis** [comment]
+1

**Comment by underlircs** [comment]
+1

**Comment by BlueB971** [comment]
+1

**Comment by VinnyV88** [comment]
+1

**Comment by jrmessias** [comment]
+1

**Comment by gr8kodr** [comment]
+1

**Comment by seblapz** [comment]
+33 1/3

**Comment by TVitasse** [comment]
+1

**Comment by jmnunezizu** [comment]
+1

**Comment by rradar** [comment]
+2

**Comment by sensibleworld** [comment]
We now have a few options for vinyl in 5.11: https://fontawesome.com/icons?d=gallery&q=vinyl
