### ISSUE TITLE
Icon Tagging

### ISSUE THREAD

**Issue by vheinrich** [FortAwesome/Font-Awesome#2409]
Adding tags to the existing Icons for a possible usage of them would be helpful to find the most suitable icon ... e.g. which icon i "should" use for a contact button

**Comment by jmeyo** [comment]
Always wanted to have tags to have more alternative when searching them. It seems it is now integrated so I guess that enahancement should be closed. But adding some documentation in the readme for that could be handy. Seems src/icons.yml should be the used file, but not sure how to integrate it smoothly.

**Comment by tagliala** [comment]
@jmeyo thanks for pointing this out!
