### ISSUE TITLE
Icon request: fa-car

### ISSUE THREAD

**Issue by bpap** [FortAwesome/Font-Awesome#2413]
Hi Font-Awesome. When you get a chance I would like to see a car icon.

Something on the line of:

![caricon03](https://f.cloud.github.com/assets/3721341/1542579/e77b6f3a-4d48-11e3-8d64-ea39610f8bb1.png)

![car-icon-large](https://f.cloud.github.com/assets/3721341/1542573/dea1bb94-4d48-11e3-9ba7-3e5904896731.png)

Thank you, You're Awesome!

**Comment by ram724** [comment]
+1 for new classic car.
