### ISSUE TITLE
Icon Request: icon-people (or icon-users-2)

### ISSUE THREAD

**Issue by lubelski** [FortAwesome/Font-Awesome#2414]
![people](https://f.cloud.github.com/assets/195878/1543962/fe488038-4d5f-11e3-9b18-86a35aad74b0.png)

The attached image is from Balsamiq.  

The use case for a the middle icon, which they call "people" for my application is indicating a "shared" state on a folder item.   

The fa-users icon is similar, but the inclusion of 3 persons seems to imply a larger number of people.  We already use fa-user for our user profile page and fa-users icon for a contact list, so maybe our need is a bit particular to that.

**Comment by sensibleworld** [comment]
This is listed as `users-friends`: https://fontawesome.com/icons/user-friends?style=solid
