### ISSUE TITLE
Icon request: fa-plus-circle-o and fa-minus-circle-o

### ISSUE THREAD

**Issue by Thomvl** [FortAwesome/Font-Awesome#2417]
As we have fa-plus-square-o and fa-minus-square-o i would like to see the fa-plus-circle and fa-minus-circle in open versions.

I think they cant be missed since we have square versions for it too

**Comment by EvilBMP** [comment]
+1

**Comment by nathraQ** [comment]
+1

**Comment by lee-anne-clarke** [comment]
+1

**Comment by kylejeske** [comment]
+1

**Comment by dlwalsh** [comment]
+1

**Comment by fmquaglia** [comment]
+1

**Comment by rajaraodv** [comment]
+1

**Comment by opicacek** [comment]
+1

**Comment by adampope** [comment]
+1

**Comment by paulleader** [comment]
+1

**Comment by traviswingo** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/3976#issue-38567599

**Comment by tagliala** [comment]
+a https://github.com/FortAwesome/Font-Awesome/issues/3976#issuecomment-50034589

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/3976#issuecomment-51087484

**Comment by Frittoss** [comment]
+1

**Comment by gl03** [comment]
+1

**Comment by joyzhang** [comment]
+1

**Comment by DonaldBerk** [comment]
+1

**Comment by amstec** [comment]
+1 

for both plus-circle-o and minus-circle-o

**Comment by chetanchauhan** [comment]
+1

**Comment by jxtcman** [comment]
+1

**Comment by rockdriven** [comment]
+1

**Comment by leo72** [comment]
+1

**Comment by tiny4penguin** [comment]
+1

**Comment by ionescho** [comment]
+1

**Comment by Kamilius** [comment]
+1

**Comment by alexxandar** [comment]
+1

**Comment by cjlee37** [comment]
+1

**Comment by Valeriu92** [comment]
+1

**Comment by okua** [comment]
+1

**Comment by Simonig** [comment]
+1

**Comment by rturknett** [comment]
+1

**Comment by dentmaged** [comment]
+1

**Comment by johncrumpton** [comment]
Please

**Comment by johncrumpton** [comment]
Using the line thickness of the square-o and the sizing of the plus-circle (it was bigger) I've created both fa-plus-circle-o and fa-minus-circle-o. I hope you can integrate these soon!

[fa-plus-circle-o and fa-minus-circle-o.zip](https://github.com/FortAwesome/Font-Awesome/files/388676/fa-plus-circle-o.and.fa-minus-circle-o.zip)
![fa-minus-circle-o](https://cloud.githubusercontent.com/assets/272776/17217620/ddd28a1a-54dc-11e6-884e-1105698812aa.png)
![fa-plus-circle-o](https://cloud.githubusercontent.com/assets/272776/17217619/ddc91124-54dc-11e6-964c-0af05c809df5.png)

**Comment by Tylerian** [comment]
+1 for fa-plus-circle-o!!

**Comment by langschlaefer** [comment]
+1

**Comment by sherxon** [comment]
+1

**Comment by marianohielpos** [comment]
+1

**Comment by cs0511** [comment]
+1

**Comment by jack-fdrv** [comment]
+1

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by teqoz** [comment]
+1

**Comment by stevenxxiu** [comment]
+1

**Comment by jamiekleiman** [comment]
+1

**Comment by mschnack** [comment]
+1

**Comment by DevCubeHD** [comment]
+1

**Comment by uniibu** [comment]
+1

**Comment by gnapse** [comment]
I wonder why hasn't this be included, given all the IMHO much less needed icons they include with every release.

**Comment by jdmoliner** [comment]
+1 +1

**Comment by spiroski** [comment]
I need this as well. Any official response guys?

**Comment by parthshah1991** [comment]
+1

**Comment by jjhampton** [comment]
+ 1

**Comment by gnapse** [comment]
Can anyone from this repository please say something here? (Before the plus-ones epidemic spreads).

Also people remember that you can "react" with a "thumb-up" to the original issue description, instead of polluting the conversation with `+1` comments.

**Comment by alexisfacques** [comment]
+1

**Comment by nureynisow** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
These are now available in FA5.

https://fontawesome.com/icons/plus-circle?style=regular
https://fontawesome.com/icons/minus-circle?style=regular

**Comment by nureynisow** [comment]
Thanks @PeterShaggyNoble. Haven't read FA5 doc yet but is it possible to have a minor FA4 version integrating this. Or is it risky to upgrade a project FA4 to FA5 ?

**Comment by uniibu** [comment]
Just to clarify, it really is available now on FA5 **PRO** and not on the FA5 free edition. Nothing against the Pro license tho, just wanted to clarify it.

**Comment by davegandy** [comment]
@uniibu Thanks for the clarification. This one is indeed a part of Pro only (was the natural fallout of making sure we had all styles for all icons in FA5).

This was released some months ago. Closing here.

**Comment by davegandy** [comment]
@nureynisow FA4 isn't getting any new feature updates (like icons).
