### ISSUE TITLE
Icon Request: icon-socket

### ISSUE THREAD

**Issue by lickmydesign** [FortAwesome/Font-Awesome#2424]
Not sure how popular this would be... but could be used with regards to websockets, or (as in my case) making an electrician's website?
![fa-icon-socket](https://f.cloud.github.com/assets/1244155/1556312/ab176722-4ec6-11e3-99ba-5af5fc77d0ab.png)

**Comment by phelma** [comment]
### This icon is popular for websockets
![image](https://cloud.githubusercontent.com/assets/4057948/13926088/af36859a-ef82-11e5-8f18-2ba3d6d4894a.png)


### a more general socket icon looks like this
![image](https://cloud.githubusercontent.com/assets/4057948/13926117/cd6fd84a-ef82-11e5-9616-3cbd7f048d2d.png)

**Comment by AlbrechtStriffler** [comment]
Any update on this?

**Comment by shamoons** [comment]
Anything?

**Comment by aethior** [comment]
Hi @lickmydesign,

This icon was added in v5.12.0.
Check https://fontawesome.com/icons/outlet

Regards.

cc/ @tagliala
