### ISSUE TITLE
Icon request: vcs related

### ISSUE THREAD

**Issue by sa2ajj** [FortAwesome/Font-Awesome#243]
Hi,

I wonder if you could add a few icons related to version control systems (vcs):
- add a branch
- [delete a branch]
- make a tag
- merge a branch/tag
- compare/diff a branch/tag/commit to a branch/tag/commit
- clone a repository
- [delete a repository]
## 

Misha

**Comment by sensibleworld** [comment]
<img width="795" alt="Screen Shot 2021-03-30 at 12 07 52 PM" src="https://user-images.githubusercontent.com/529604/113020394-8fbef600-9150-11eb-93c5-ec0d383e11b1.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
