### ISSUE TITLE
Icon request: icon-color-palette (icon-theme / icon-style / icon-color / icon-paintbrush)

### ISSUE THREAD

**Issue by davequested** [FortAwesome/Font-Awesome#244]
Similar to:
http://thenounproject.com/noun/paint-palette/#icon-No1435

**edit by tagliala:**
Simpler version because of https://github.com/FortAwesome/Font-Awesome/issues/244#issuecomment-53224504: https://cdn0.iconfinder.com/data/icons/business-vector-tab-bar-icons/48/painter_palette-512.png 

Thanks

**Comment by nkoren** [comment]
+1

**Comment by remacg** [comment]
+1 for fa-pallete

**Comment by hollyfaber** [comment]
+1

**Comment by talinwind** [comment]
+1 for fa-palette with the "simpler version" of tagliala

new in Font Awesome and really sorry to read the hard discussions about this icon >_>
I try "eyedropper" and "paint-brush" that were pretty good but I still thinking that a palette will be more accurate for my need. I plan to use it for a toggle button for color switch between two panel (red/blue for example)

* happy to see the new milestone added few day before ;-)

**Comment by G-Driver** [comment]
+1 for pallete

**Comment by martindines** [comment]
+1 for palette

**Comment by owlgraphic** [comment]
+1

**Comment by sebastien-fauvel** [comment]
:+1:

**Comment by Denni007** [comment]
+1 for palette

**Comment by caih** [comment]
+1

**Comment by freefony** [comment]
+1 for palette

**Comment by chucklarge** [comment]
+1 for palette!

**Comment by sequethin** [comment]
+1 for palette

**Comment by joe-bader** [comment]
+1 for palette

**Comment by pedromcp90** [comment]
+1 for palette

**Comment by vikspr** [comment]
+1 for palette

**Comment by ivanjaros** [comment]
+1

**Comment by crevete** [comment]
+1 for ```fa-palette``` or ```fa-palette-brush``` (the version with a brush is better for us). Thanks

**Comment by ivanjaros** [comment]
crevete: brush is already there. This is about palette.

**Comment by crevete** [comment]
@ivanjaros No I'm not talking about ```paint-brush```, but an icon with PALETTE + BRUSH, like this :
<img width="64" alt="color_palette" src="https://cloud.githubusercontent.com/assets/6795189/9172859/9425f3c4-3f76-11e5-81c8-3a3660f300ec.png">

**Comment by yoplaboom** [comment]
+1 for `fa-palette-brush`

**Comment by OskarStark** [comment]
+1 for ```fa-palette-brush```

**Comment by ApekshaBhosale** [comment]
+1 for fa-palette

**Comment by stuller** [comment]
:+1:  for fa-palette

**Comment by timm3** [comment]
+1 for fa-palette (no brush)

**Comment by MartinMuzatko** [comment]
+1 for palette without brush. ( https://cdn0.iconfinder.com/data/icons/business-vector-tab-bar-icons/48/painter_palette-512.png )

before this will be implemented, eyedropper does it too meanwhile.

**Comment by PeterShaggyNoble** [comment]
+1 for palette w/o brush

**Comment by avatarium** [comment]
+1 for fa-palette (no brush)

**Comment by denisj07** [comment]
+1

**Comment by nathanayling** [comment]
+1 Like these two.

https://cdn3.iconfinder.com/data/icons/basic-mobile-part-2/512/painter-512.png
http://images.clipartpanda.com/art-palette-icon-Palette-attr-to-James-Fenton.png

**Comment by mikeg0** [comment]
+1 fa-palette-brush

**Comment by thekondrashov** [comment]
+1

**Comment by lukepolo** [comment]
+1

**Comment by jBot-42** [comment]
+1

**Comment by phoebusryan** [comment]
+1

**Comment by albab** [comment]
+1 x 100000000 for fa-palette

**Comment by jBot-42** [comment]
We need some kind of icon for a color picker.

**Comment by chungphuoc** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by cdavid14** [comment]
+1 for fa-palette :+1:

**Comment by ralexrdz** [comment]
+1

**Comment by azharijelek** [comment]
still not here?

**Comment by andre-abissal** [comment]
+1

**Comment by Annyeong** [comment]
+1

**Comment by s43** [comment]
+1

**Comment by Foozor** [comment]
+1

**Comment by darrencornwell** [comment]
+1

**Comment by circleb** [comment]
+1 for fa-palette

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-palete-color was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by gaurabdahal** [comment]
+1 need this

**Comment by esr360** [comment]
Tbh I this would be a good addition as well as paint brush and eye dropper if possible. +1

**Comment by grantwparks** [comment]
4 years.

**Comment by MartinMuzatko** [comment]
Is there a pull request related to this icon?

**Comment by glennkarlsen** [comment]
+1

**Comment by fcpauldiaz** [comment]
+1

**Comment by mxrguspxrt** [comment]
+1

**Comment by robdimarzo** [comment]
+1

**Comment by teckel12** [comment]
Maybe add fa-palette as an alias to fa-paint-brush until a new palette icon is created?  Some of the confusion is doing a search for "palette" with no results (that was my confusion).  fa-paint-brush or fa-eyedropper will work fine in most situations.

**Comment by tonytopper** [comment]
+1 for fa-palette 

One without a brush would be better in my opinion

**Comment by jouanc** [comment]
+1

**Comment by mcwebdev** [comment]
+1 for fa-palette

One without a brush would be better in my opinion

**Comment by Crissov** [comment]
Related Unicode emoji: #222

- [🎨 U+1F3A8](http://emojipedia.org/artist-palette/)

**Comment by ashthespy** [comment]
+1

**Comment by SushantRT** [comment]
+1 for fa-palette
Agree with @tonytopper and @mcwebdev for palette without brush

**Comment by Aligatro** [comment]
+1

**Comment by briceambrosiak** [comment]
+1. 
Since 2012 and still not in? :/

**Comment by korax** [comment]
Palette, and palette with brush please.

**Comment by yolao** [comment]
+1 for fa-palette

**Comment by ramu2514** [comment]
+1 for fa-palette & fa-pallete-brush icons

When are these going to release?

**Comment by alainpannetier** [comment]
:+1:

**Comment by edsonaf** [comment]
+1

**Comment by brainmaniac** [comment]
+1

**Comment by lucaskatayama** [comment]
+1

**Comment by visualpharm** [comment]
I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The color palette icon is here](https://icons8.com/icon/4945/paint-palette).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by balazsnemeth** [comment]
+1

**Comment by johnwc** [comment]
I see everyone adding a +1 comment. Don't the directions say to add a 👍 reaction to the original request, and not comment +1?

**Comment by esr360** [comment]
I guess with requests this popular you're bound to have those who don't read directions.

**Comment by RGBenderKC** [comment]
👍

**Comment by felimartina** [comment]
Oh gosh...can't believe this threat dates from 2012!
Nonetheless... +1

**Comment by c0bra** [comment]
> I see everyone adding a +1 comment. Don't the directions say to add a 👍 reaction to the original request, and not comment +1?

GitHub released reactions in March of 2016. Most of the comments in this thread predate that.

**Comment by ClassicNancy** [comment]
Is this gone or it was never done?

**Comment by FlemmingH** [comment]
+1 for a fa-palette ! Really???... this request is 5 years old now!!!...?

**Comment by teckel12** [comment]
And there's no thumbs up on mobile so +1 is the best I can do. Wait, does this :thumbs-up: work?

**Comment by jrahhali** [comment]
+1

**Comment by onursenture** [comment]
+1

**Comment by Syrok** [comment]
+1

**Comment by cdavid14** [comment]
![84](https://user-images.githubusercontent.com/5961014/36476325-5479718e-16dc-11e8-86c6-9f0f68414314.gif)

**Comment by patrickpissurno** [comment]
+1

**Comment by haferje** [comment]
+1

**Comment by sensibleworld** [comment]
This is coming soon :)

**Comment by rhaymoore** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=palette
