### ISSUE TITLE
Icon request: Government

### ISSUE THREAD

**Issue by davidagnome** [FortAwesome/Font-Awesome#2440]
Uses:
Government is much broader than a gavel (which conjures meanings of auctions/bids or a courthouse). By adding a government structure icon, this will allow us to more accurately convey the meaning: the icon would be used to denote political advocacy (private sector) and government operations (public sector)

![icon-government](https://f.cloud.github.com/assets/5984719/1576851/8aa7a8fa-5162-11e3-9ac6-56e2a82d25e6.jpg)

**Comment by SeanFromIT** [comment]
+1

**Comment by aragonwa** [comment]
+1

**Comment by jdblundell** [comment]
+1 a capitol building of some sort would be great!

**Comment by yukoff** [comment]
+1

**Comment by yukoff** [comment]
Here's another possible variant: https://gist.github.com/yukoff/e10ce54c1369dfd18b88
BTW, @dangnelson, how did you embed svg into comment like in [this one](#issuecomment-62653026)?

**Comment by CoDEmanX** [comment]
@yukoff: you need to host the SVG somehow, e.g. on http://imgh.us, then use the usual syntax for image embedding:

```
![remote-desktop](http://imgh.us/remote-desktop.svg)
```

Result: ![remote-desktop](http://imgh.us/remote-desktop.svg)

**Comment by yukoff** [comment]
Thanks for the hint, @CoDEmanX! I was confused about image links to *.githubusercontent.com storage, so I thought it is someway hosted by github (eg. gist).

Here it is: ![gov](http://imgh.us/government_3.svg)

**Comment by tagliala** [comment]
Does http://fontawesome.io/icon/university/ do the job?

**Comment by kwendenarmo** [comment]
+1

**Comment by caduvieira** [comment]
+1

**Comment by iraklisg** [comment]
+1

**Comment by sensibleworld** [comment]
Our latest release includes a new landmark icon that can be used to denote "government": https://fontawesome.com/icons/landmark-alt?style=solid

As well as various "political" themed icons: https://fontawesome.com/icons?d=gallery&c=political
