### ISSUE TITLE
icon request: cross icon for delete/remove

### ISSUE THREAD

**Issue by bazo** [FortAwesome/Font-Awesome#2446]
FA is missing an icon for delete/remove in cross shape, similar to glyphicons .glyphicon-remove

**Comment by ThomasMahoney1959** [comment]
How about a cross on a angle for Christ?   We can use for churches.

**Comment by tagliala** [comment]
@ThomasMahoney1959 please open a new request for a christian cross

**Comment by atusasire** [comment]
A cross for a church is also missing

**Comment by tagliala** [comment]
@atusasire: #2088
