### ISSUE TITLE
Icon Request: fa-rabbit / fa-turtle (Animal / Media player)

### ISSUE THREAD

**Issue by amundo** [FortAwesome/Font-Awesome#2453]
For media playback interfaces that have adjustable playback speeds, some interfaces use a rabbit and turtle as symbols to indicate the opposite polls of the speed range.

**Comment by octlabs** [comment]
+1

**Comment by petrgrishin** [comment]
+1

**Comment by DsXack** [comment]
:+1:

**Comment by elfelrandcor** [comment]
+1

**Comment by petrgrishin** [comment]
:+1:

**Comment by viet-pham** [comment]
+1

**Comment by jeffvarnam** [comment]
+1

**Comment by G-Driver** [comment]
+1 rabbit
+1 turtle

**Comment by blacatena** [comment]
+1

**Comment by TheChen5** [comment]
+1 :+1:

**Comment by seaster** [comment]
+1

**Comment by chenware** [comment]
I just like turtles.

**Comment by aeksco** [comment]
:+1: for use as speed indicators

Turtle (Slow)
Rabbit (Fast)
Cheetah / Jaguar (Very Fast)

**Comment by thearabbit** [comment]
+1 rabbit

**Comment by jtrienekens** [comment]
+1

**Comment by Crissov** [comment]
Issue #6495 is related, but different.

**Comment by nigelNSF** [comment]
+1

**Comment by keirk** [comment]
+1

**Comment by marketica** [comment]
+1

**Comment by Aethyn** [comment]
+1

**Comment by omnizach** [comment]
+1

**Comment by Crissov** [comment]
## Unicode (emoji) equivalents

🐆 U+1F406 Leopard (no Gepard/[Cheetah/Jaguar](#issuecomment-165502081)) – very fast
🐎 U+1F40E (Racing) Horse – faster
🐰 U+1F430 **Rabbit** Face – fast
🐇 U+1F407 **Rabbit** – fast
🐢 U+1F422 **Turtle** – slow
🐌 U+1F40C Slug – very slow

**Comment by unicod3** [comment]
+1

**Comment by maladeeb** [comment]
+1

**Comment by MagnusBrzenk** [comment]
+1

**Comment by BonBonSlick** [comment]
+1
