### ISSUE TITLE
Icon request: raised hand

### ISSUE THREAD

**Issue by mitchdowney** [FortAwesome/Font-Awesome#2476]
Thanks for the great icons Font Awesome!

I'm working on a civic engagement project and I need a symbol to represent Running for Office or a Candidate. I am thinking a raised open hand would be a haaaandy symbol for that.

Example: http://www.clker.com/clipart-13625.html

What do you think? Does a raised hand have a place in your icon set, or is there another Font Awesome symbol you recommend I use for Running for Office or a Candidate? (I am already using a checkmark symbol for the Vote button)

**Comment by tagliala** [comment]
dup of #1651 , please +1 that request
