### ISSUE TITLE
Icon Request: icon-popup-link (popup window)

### ISSUE THREAD

**Issue by hw-nf** [FortAwesome/Font-Awesome#2478]
Hi

Just like the icon to indicate an external link (http://fontawesome.io/icon/external-link/), could we have an icon to indicate a link in a new window/tab/pop-up? Typically seen as a square overlapping another square, eg, see attachment.

![icon-popup](https://f.cloud.github.com/assets/6040581/1621894/3d21a108-5699-11e3-9ebb-42bdfa5eea63.png)

Thanks

Neil

**Comment by gbhasha** [comment]
+1 
Something similar makes sense for representing 'open in new window' scenario. https://www.iconfinder.com/icons/105291/new_open_out_pop_up_window_icon

**Comment by JoshWeb** [comment]
+1

**Comment by ravikumars** [comment]
+1

**Comment by kevin-at-corista** [comment]
+1

**Comment by msnisha** [comment]
+1

**Comment by doingweb** [comment]
+1

**Comment by Roenok** [comment]
+1

**Comment by cherrador** [comment]
+1
for a while... not perfect, but as a workaround (the styles should be moved to a CSS). I will rather to have the real thing with the proper transparencies and rectangles instead of squares.

![capture](https://cloud.githubusercontent.com/assets/12229855/7895276/7100c7ec-0651-11e5-9a82-0762e43be141.PNG)

```html
<span class="fa-stack">
   <i class="fa fa-square-o" style="position:absolute;left:0;bottom:-12%;font-size:1.7em"></i>
   <i class="fa fa-square fa-inverse" style="position:absolute;right:0;top:-6%;font-size:1.7em"></i>
   <i class="fa fa-external-link-square" style="position:absolute;right:0;top:-6%;font-size:1.7em"></i>
</span>
```

**Comment by Gitoffthelawn** [comment]
+1 for the icon request

**Comment by justifyer** [comment]
+1

**Comment by kirked** [comment]
+1

**Comment by cherrador** [comment]
Alright!!! 4.4 comes with the new icon "fa-clone". It is a very good alternative for this request.

**Comment by akshaybabloo** [comment]
+1

**Comment by f0def** [comment]
+1

**Comment by four-oh-four** [comment]
+1

**Comment by harianus** [comment]
As @cherrador already mentioned, there is a icon quite close to this. And if you mix it with the `fa-flip-horizontal`-class you already are very close to your icon @hw-nf.

<img src="https://cloud.githubusercontent.com/assets/1079135/17097033/eed2890e-5253-11e6-8809-50d2045c6304.png" height="14px">

The html:

```html
<i class="fa fa-clone fa-flip-horizontal" aria-hidden="true"></i>
```

**Comment by lickmydesign** [comment]
+1

**Comment by marathia** [comment]
+1

**Comment by letsspeak** [comment]
+1

**Comment by bohdanzhylavskyi** [comment]
+1

**Comment by rogercoder** [comment]
This (from a competing icon library) gives a better impression of something popping up, IMHO, and less like a copy icon:
![image](https://user-images.githubusercontent.com/2239492/65852030-c58be000-e309-11e9-81d7-e784caaed67f.png)

**Comment by Gitoffthelawn** [comment]
@rogercoder What library is that from?  Do you have a link?

**Comment by rogercoder** [comment]
Fontello / Entypo
![image](https://user-images.githubusercontent.com/2239492/65887515-e593c180-e352-11e9-8945-3c6bbab8389a.png)

**Comment by rogercoder** [comment]
As far as using the Fontawesome "copy" icon, I think vertical flip looks more like a popup then horizontal flip:
![image](https://user-images.githubusercontent.com/2239492/65894184-2a712580-e35e-11e9-9c93-532e7a6acefd.png)

`<i class="fa fa-clone fa-flip-vertical" aria-hidden="true"></i>`

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome! [Take a look at it here.](https://fontawesome.com/icons/clone?f=classic&s=solid)
