### ISSUE TITLE
Spinning Icons not working in Chrome

### ISSUE THREAD

**Issue by winkerVSbecks** [FortAwesome/Font-Awesome#2490]
Spinning icons stopped working in the latest version of Google Chrome. Using Chrome Version `31.0.1650.57` on `Mac OS X 10.9`

**Comment by antonioreyna** [comment]
im having this problem

**Comment by tagliala** [comment]
It is probably because of reduced motion user setting. Ref: #18713

Otherwise, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

**Comment by antonioreyna** [comment]
> It is probably because of reduced motion user setting. Ref: #18713
> 
> Otherwise, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) and provide a reproducible test case

that was it! thank you!!
