### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by AspireRajan** [FortAwesome/Font-Awesome#2494]
Hello sir,
Thank you for "Font Awesome"

plz. Add 3 icon more

1. Color plate
2. Tool Box
3. Pant-Brush

**Comment by aethior** [comment]
- [ ] Color Palette (#244)
- [ ] Tool Box (#4407)
- [x] `fa-paint-brush` (http://fontawesome.io/icon/paint-brush/)

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks

All dups, also please take a look at our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)
