### ISSUE TITLE
Icon Request: icon-code-pull-request

### ISSUE THREAD

**Issue by Kuitsi** [FortAwesome/Font-Awesome#2497]
Pull Request is a basic functionality in services like GitHub and Bitbucket.

Could you add .octicon-git-pull-request (UTF+f009) from Octicons (https://github.com/styleguide/css/7.0)?

Requesting single icons from Octicons font was suggested in issue #191.

**Comment by Morgul** [comment]
:+1: Would really like to see this added.

**Comment by xShay** [comment]
+1

**Comment by JeroenSormani** [comment]
Would really love to see this!
+1

**Comment by JackHasaKeyboard** [comment]
Yeah, at the moment they have the fork icon and nothing else. I certainly don't see why not.

**Comment by sufuf3** [comment]
+1

**Comment by saintasia** [comment]
+1

**Comment by nlyn** [comment]
+1

**Comment by givanse** [comment]
I'm trying to see what was necessary to add the fork icon, so that the same process can be followed for the pull request icon.
original issue: https://github.com/FortAwesome/Font-Awesome/issues/154 but I haven't been able to find the PR.

**Comment by givanse** [comment]
What? An icons toolkit that doesn't accept new icons? There are 1.7k issues with the label "new icon". So, what is going on?

**Comment by givanse** [comment]
In fact, this issue was recently marked as "in progress":
https://github.com/sensibleworld

**Comment by Wingo5315** [comment]
givanse, I think Font Awesome are currently marking ALL religion-related icons as "in progress". Maybe they're working on a religion icon pack...?

**Comment by tagliala** [comment]
@givanse 

> What? An icons toolkit that doesn't accept new icons?

That's right: Font Awesome does not accept PRs including new icons

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

> this issue was recently marked as "in progress"

@Wingo5315 is right. `In progress` means that someone in the Font Awesome team is working on that icon

> Maybe they're working on a religion icon pack...?

Maybe 😜

**Comment by mkonikov** [comment]
+1 for a pull request icon

**Comment by andofcourse** [comment]
is there an ETA on this? Looks like it was marked in progress in 2018?

**Comment by sensibleworld** [comment]
<img width="631" alt="Screen Shot 2021-02-25 at 2 49 40 PM" src="https://user-images.githubusercontent.com/529604/109208735-b1574700-7778-11eb-9b15-f07bc05475e5.png">

These are all coming to v6

**Comment by sensibleworld** [comment]
This is available in the latest alpha release of Font Awesome v6: http://fontawesome.com/download
