### ISSUE TITLE
Icon Request: icon-delete

### ISSUE THREAD

**Issue by martinezalegre** [FortAwesome/Font-Awesome#2508]
An icon with a basket?

**Comment by aethior** [comment]
- [x] `fa-trash` (http://fontawesome.io/icon/trash/)
- [x] `fa-trash-o` (http://fontawesome.io/icon/trash-o/)
- [x] `fa-times` (http://fontawesome.io/icon/times/)

cc @tagliala

**Comment by tagliala** [comment]
Closing here, there are at least three alternatives to represent a delete action
