### ISSUE TITLE
Icon Request: icon-minus-thin

### ISSUE THREAD

**Issue by howlowck** [FortAwesome/Font-Awesome#2519]
The current fa-plus and fa-minus are really fat on large font sizes.  The width of the plus/minus signs on fa-plus and fa-minus are also inconsistent with that of fa-plus-square-o and fa-minus-square-o

![screen shot 2013-12-02 at 5 06 04 pm](https://f.cloud.github.com/assets/338265/1659578/84b678d8-5ba6-11e3-950c-9e7fba2336cd.png) ... ![screen shot 2013-12-02 at 5 07 01 pm](https://f.cloud.github.com/assets/338265/1659582/8de6b198-5ba6-11e3-81ee-ee1ef5fa0e2d.png)

I propose some thinner plus/minus signs that are the same weight as the plus/minus signs in the rounded square icons.

**Comment by tagliala** [comment]
Hi, this icon is available in FA 5.0.0 Pro

https://fontawesome.com/icons/minus?style=light
