### ISSUE TITLE
Shows bad "fa-picture-o" bootstrap btn-sm btn-xs

### ISSUE THREAD

**Issue by lorlev** [FortAwesome/Font-Awesome#2522]
I use : 
button class="btn btn-sm btn-default" >  i class="fa fa-picture-o">

![problem](https://f.cloud.github.com/assets/4301581/1661858/f7779b3c-5bf0-11e3-8709-1996b4ded260.PNG)

**Comment by tagliala** [comment]
Hi, I'm sorting out some old issues 😅 

A lot of things have changed in the last years, both in Bootstrap and in Font Awesome.

The base font size has been changed to 16px in both the libraries and `btn-xs` has been removed from Bootstrap. I've tested this with FA 5.9.0 and BS 4.3.1 in Chrome, Firefox, Edge, IE11 and it is not a problem anymore

https://jsfiddle.net/tagliala/0syz6xhj/2/

Closing here
