### ISSUE TITLE
Why fa-cog isn't centered when it's spinning ?

### ISSUE THREAD

**Issue by Deliaz** [FortAwesome/Font-Awesome#2524]
So, my little question about it: Why .fa-cog isn't centered when it's spinning  (.fa-spin)?
It's floats up-down. 
(tested in chrome and ff)

Bug or feature?)

**Comment by cosmopolit** [comment]
This fa-spin-fix assigned to the parent element minimized the deviation for me.

    .fa-spin-fix .fa-spin {
        -webkit-transform-origin: 50% calc(53% - 0.6px);
        transform-origin: 50% calc(53% - 0.6px);
    }

**Comment by tagliala** [comment]
please discuss about this in #671
