### ISSUE TITLE
Icon Request: icon-user-male / icon-user-female

### ISSUE THREAD

**Issue by ironman1964** [FortAwesome/Font-Awesome#2537]
Hi, I'd like to add these two icons.
We use it on the user settings now, but with the use of a pic

![iconvrouwdonker](https://f.cloud.github.com/assets/688083/1681018/19bc39c4-5d8a-11e3-9bc2-7775032cda19.png)
![iconmannetjedonker](https://f.cloud.github.com/assets/688083/1681017/19bc1a02-5d8a-11e3-9a5a-4ed32d1d6fc6.png)

**Comment by BenElgar** [comment]
+1

**Comment by mujahmad** [comment]
+1

**Comment by lazabazsa** [comment]
+1

**Comment by scottsawyer** [comment]
I was about to file a request for user-female, and for all user-* to contain a female version.  This is different from the male / female icons, should include things like user-md-female, user-graduate-female, etc.  I think it would be quite appropriate and get broad usage.

Thanks!

**Comment by trf000** [comment]
+1

**Comment by tagliala** [comment]
At the moment we have user-with-tie that partially fits this request: https://fontawesome.com/icons/user-tie?style=solid

For the second part, let's use #15766, which explains better why we need a counterpart
