### ISSUE TITLE
Icon Request: fa-arrows-in, fa-arrows-in-alt 

### ISSUE THREAD

**Issue by nciske** [FortAwesome/Font-Awesome#2545]
Or, could be fa-arrows-facing, fa-arrows-facing-alt?

There are lots of facing outwards arrows, but nothing inclusive like these. e.g. putting things into something, coming together, etc.

![fa-arrows-in](https://f.cloud.github.com/assets/974354/1695876/877984be-5eb9-11e3-99dc-5ec5122a2595.png)

Example icon made by Anas Ramadan from Flaticon.com

**Comment by sensibleworld** [comment]
We now have these icons: https://fontawesome.com/v6.0/icons?q=minimize&s=solid%2Cbrands
