### ISSUE TITLE
Icon request: icon-biohazard

### ISSUE THREAD

**Issue by Skaidon** [FortAwesome/Font-Awesome#255]
Have a need for the radiation/nuke icon for system admin tool - using FontAwesome for all other icons presently...

Awesome truly this is ;)

**Comment by MoeBDC** [comment]
+1 Biohazard

**Comment by aarongray** [comment]
+1 for Biohazard

**Comment by incephalon** [comment]
+1 for Biohazard

**Comment by ewr4github** [comment]
+1 for Biohazard!  Please! We desperately need this icon - there's no better symbol for security news.  Thanks!

**Comment by FREEZX** [comment]
+1 radiation

**Comment by timfennis** [comment]
+1 for nuke

**Comment by slushi** [comment]
+1 for biohazard!

**Comment by huntwelch** [comment]
+1

**Comment by iglvzx** [comment]
+1

**Comment by nitmir** [comment]
![quarantine_icon](https://cloud.githubusercontent.com/assets/5030463/13405030/e37f8a2a-df1c-11e5-9c3f-6cd681f8671f.png)
+1

**Comment by nitmir** [comment]
As a lot of this symbols have an unicode sign, It could probably be possible to import the signs for a free unicode font.
# **⚠ ☠ ☢ ☣**

**Comment by acorrow** [comment]
+1

**Comment by CorinnaSch** [comment]
+1

**Comment by glueball** [comment]
+1

**Comment by dnagirl** [comment]
+1

**Comment by mg1075** [comment]
+1

**Comment by mattgarkusha** [comment]
+1

**Comment by GameCharmer** [comment]
+1 could really use these for our medical app

**Comment by Crissov** [comment]
Unicode emoji: #222

- [☣ U+2623](http://emojipedia.org/biohazard-sign/)

**Comment by haoleboy** [comment]
+1

**Comment by djechelon** [comment]
+1

**Comment by cpalenshus** [comment]
+1

**Comment by lenamtl** [comment]
+1 GHS hazard symbols and for biohazard

**Comment by kvisscher** [comment]
+1

**Comment by lubhoekman** [comment]
+1

**Comment by cata92sv** [comment]
+1...but i guess no one will put anything cause it was open in 2012...5 years later and no outcome, this is funny...

**Comment by ilektriksky** [comment]
+1 for sure for GHS hazard symbols.  We will use this in our Safety site.

**Comment by y3n3rrr** [comment]
+!

**Comment by bear-bones** [comment]
+1

**Comment by amielantonio** [comment]
+1

**Comment by draidman** [comment]
+1 to biohazard

**Comment by kfdg** [comment]
+1

**Comment by My1** [comment]
I would totally love some hazard symbols. especially the Radioactive one can be used for super dangerous options (for example wiping an entire site)

**Comment by Titum** [comment]
+1000 thanks!

**Comment by rizkyarlin** [comment]
+1 for this icom

**Comment by sensibleworld** [comment]
Be careful with this icon: 
https://fontawesome.com/icons/biohazard?style=solid

And with these, too:
https://fontawesome.com/icons/radiation?style=solid
https://fontawesome.com/icons/radiation-alt?style=solid
