### ISSUE TITLE
ISO Symbols

### ISSUE THREAD

**Issue by egsystems** [FortAwesome/Font-Awesome#2551]
This is probably a big ask but if you included the complete ISO symbol set in fa then that would be just awesome and hugely useful.

http://www.iso.org/iso/graphical-symbols_booklet.pdf

You have a glyph for code fork (fa-code-fork) but no 'knife and fork' to indicate a restaurant, for example.

**Comment by sensibleworld** [comment]
Looks like this link no longer works. If you have any specific requests, definitely respond here, or open a new issue.
