### ISSUE TITLE
Icon Request: fa-user-with-cog (admin)

### ISSUE THREAD

**Issue by abezafar** [FortAwesome/Font-Awesome#2553]
I would like to have a user icon for an admin user. The attached icon is a user + settings icon to indicate an admin user.
![adminicon](https://f.cloud.github.com/assets/6116901/1701973/50f88a6c-607a-11e3-85f8-76e4608bbbf9.png)

**Comment by tom-lord** [comment]
+1

**Comment by ktasos** [comment]
+1

**Comment by tshafer** [comment]
+1

**Comment by abeniang** [comment]
+1

**Comment by krypsin** [comment]
+1

**Comment by fgarci03** [comment]
+1

**Comment by abeniang** [comment]
+1 Asuquo 

     On Wednesday, January 21, 2015 9:06 PM, Filipe Garcia <notifications@github.com> wrote:
   

 +1—

**Comment by SeanLF** [comment]
+1

**Comment by LouHolsten** [comment]
+1

Just saw the new 4.3 icons and was excited to see that new user icons were added. Sad that user-admin wasn't included though.

**Comment by gtonioli** [comment]
+1

**Comment by Macsch15** [comment]
+1

**Comment by madvas** [comment]
+1

**Comment by rahatkhan786** [comment]
+1

**Comment by gingi** [comment]
+1 :)

**Comment by G-Driver** [comment]
+1

**Comment by kestelle** [comment]
+1

**Comment by colepanike** [comment]
+1

**Comment by sridharspeaks** [comment]
+1

**Comment by sridharspeaks** [comment]
+1

**Comment by designbyadrian** [comment]
+1

Icon example at the top by @gunthercox looks too much like the secret agent icon, maybe something along the lines of the crowned user as in icons8:

https://icons8.com/web-app/for/all/moderator

**Comment by tzusman** [comment]
I just launched [CustomFontIcons.com](https://customfonticons.com/), a place to get crowd-commissioned icons.  I also launched a free font icon set.  An admin user icon is part of that set, if you're interested.

**Comment by lnghost** [comment]
+1

**Comment by taalendigitaal** [comment]
+1

**Comment by zeknox** [comment]
+1

**Comment by tudo75** [comment]
+1

**Comment by paullaros** [comment]
+1

**Comment by tagliala** [comment]
refers to #1181

**Comment by A-Dechorgnat** [comment]
+1

**Comment by Code-Crash** [comment]
+1

**Comment by Owen-Davies** [comment]
+1

**Comment by sepehr1014** [comment]
+ 1

**Comment by migig** [comment]
+1

**Comment by daprezjer** [comment]
:+1:

**Comment by baalthazaar1** [comment]
+1

**Comment by BioPhoton** [comment]
+1

**Comment by Hackmastr** [comment]
Is is going to be implemented anytime?

**Comment by raimo** [comment]
+1

**Comment by thaisonle94** [comment]
+1

**Comment by bevss** [comment]
+1

**Comment by danielgrycman** [comment]
+1

**Comment by clain4u** [comment]
+1 Most wanted ....!!!

**Comment by alias1** [comment]
+1

**Comment by neogermi** [comment]
+1

**Comment by MurWade** [comment]
+1

**Comment by itart-top** [comment]
+1

**Comment by troelsh** [comment]
+1

**Comment by saira3** [comment]
+1

**Comment by randyhoude72** [comment]
+1

**Comment by simbunch** [comment]
It's been 2 years. +1

**Comment by enricou** [comment]
+1

**Comment by Derpolino** [comment]
+1

**Comment by elenasariols** [comment]
+1 :)

**Comment by CaelanStewart** [comment]
+1.

Come on Font Awesome, look at the overwhelming number of "+1" comments on this page. Perhaps that's a sign that your user's are trying to tell you something.

**Comment by markc** [comment]
+1

I guess I'll have to hop on the end of this very long line and wait patiently like everyone else. Removing the silly hat from fa-user-secret would just about do it, and maybe a little more whitespace around the tie.

**Comment by teamyudin** [comment]
+1

**Comment by robinvdijk** [comment]
+1

**Comment by Anecho** [comment]
+1

**Comment by toddjcrane** [comment]
+1

**Comment by IreneIrene** [comment]
+1

**Comment by david-sa** [comment]
+1

**Comment by RishabSwift** [comment]
+1

**Comment by dhanyn10** [comment]
+1

**Comment by robertocontardo** [comment]
+1

**Comment by dentmaged** [comment]
+1

**Comment by CaelanStewart** [comment]
Nearly three years old, nearly 90 +1's, and absolutely zero response.

**Comment by dbr0** [comment]
+1

**Comment by yupswing** [comment]
+1

**Comment by matiboux** [comment]
+

**Comment by davidnguyen2205** [comment]
+1

**Comment by stgisi** [comment]
+1

**Comment by shlomisas** [comment]
+1

**Comment by pdrosos** [comment]
+1

**Comment by loipl** [comment]
+1

**Comment by aarongarciah** [comment]
+1 Would be awesome.

**Comment by fqborges** [comment]
+1

**Comment by ronlut** [comment]
+1

**Comment by klgd** [comment]
+1

**Comment by jacobbroberg** [comment]
+1

**Comment by eterry1388** [comment]
:+1:

**Comment by kaizonaro** [comment]
+1

**Comment by xiezhengfeng** [comment]
+1

**Comment by marcelo-mason** [comment]
+1

**Comment by amawaziny-sphere** [comment]
+1

**Comment by terry90** [comment]
+1

**Comment by galvani** [comment]
+1 , btw? any alternative with same symbolics?

**Comment by CaelanStewart** [comment]
Well, seeing as you've [raised half a million dollars](https://www.kickstarter.com/projects/232193852/font-awesome-5/), do you think you could possible, potentially create this icon, please?

**Comment by teckel12** [comment]
+2, maybe that will speed things up.

**Comment by mbustos-folderit** [comment]
+1

**Comment by trillian74** [comment]
+1

**Comment by manuelph** [comment]
+1

**Comment by ibtrey** [comment]
+1

**Comment by 58a36f** [comment]
+1

**Comment by egemenerd** [comment]
+1

**Comment by dev6james** [comment]
+1

**Comment by zetanove** [comment]
+1

**Comment by KE55ARD** [comment]
+1

**Comment by alainpannetier** [comment]
+1

**Comment by SergiiShcherbak** [comment]
+1

**Comment by lucaszmoraes** [comment]
+1

**Comment by zeeshanu** [comment]
+1

**Comment by deyvisonrocha** [comment]
+1

**Comment by trlorenz** [comment]
+1

**Comment by phoebebright** [comment]
+1

**Comment by KennyVH1** [comment]
+1

**Comment by Fruxio** [comment]
+1

**Comment by visualpharm** [comment]
I feel pain looking at the thread like this, begging for a single icon.

I've shared [some of our icons](https://icons8.com/free-icons/moderator-font-awesome) that may fit. Please feel free to use them for your projects or to create a pull request for FA.

To use them:

- Generate another small font with just the icons you need (you can do it on our website or downloading SVG and using a third party tool)
- Generate a separate SVG set, HTML snippet, or even plain `<img src>`
- Repacking FA with just the icons that you actually need.

Also, if you need a person with a cog, feel free to [create](https://icons8.com/request-icon) a request and we'll do it for free. I mean, few days and it's done.

Anyway, enjoy. Everything on this page is licensed under our [Good Boy License](https://icons8.com/good-boy-license/) and double licensed under MIT.

**Comment by CaelanStewart** [comment]
@visualpharm, to be frank, we shouldn't have to beg for an icon. Any project should listen to and consider the wishes of its customers.

Anyway, it started off as a simple request, but as the years passed and this request received absolutely no attention from the FontAwesome guys, it has turned into begging.

FontAwsome is one of the de facto standard icon fonts in the industry, and it is missing an icon that is commonplace amongst web applications. And the end of the day, it shouldn't have to come to this in the first place.

I'm sure it's just that they've gone quiet while they finish FontAwesome 5.

**Comment by markc** [comment]
If the folks managing FontAwesome are willing to ignore some of their users like this thread indicates then there is no way I will ever give them any money for FA5... and I had intended to do so but ignoring such a strong request after 4 years for slightly modify an already existing icon is a real FU to the community.

**Comment by visualpharm** [comment]
We all adore FA (I do for sure, seriously). 

And yeah, once in a while you need yet another icon that you miss. 

There're thousands of ways to handle it. Everybody who thinks about it for 25 minutes, comes with a voting system, [bounty](https://www.bountysource.com/) for extra icons, paid extended pack, some 3d party plugins, etc.

Still, don't feel locked with it! Material is good and it has 900+ icons nowadays, our [Line Awesome](https://icons8.com/line-awesome) is good (and we add more and more). And there're plenty of [other](https://iconpharm.com/) open source icon packs there.

**Comment by tagliala** [comment]
@visualpharm thanks for sharing 👍

**Comment by r3z0** [comment]
And for those wondering how to generate fonts on the fly, I have found this pretty handy font generator:
https://glyphter.com/

Just drag and drop your icon, export your font, in the css file, check the rule with `[class*='icon-']` in the provided css file as might affect other font library and replace it with `myiconset-icon`

If you have other alternatives, I'd be happy to check them out :)

**Comment by dtvmedia** [comment]
+1

**Comment by sensibleworld** [comment]
This icon is in the queue!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=user%20cog

**Comment by markc** [comment]
Dare I say on behalf of all of us in this issue thread, thank you! It's perfect :+1:

**Comment by vndevil** [comment]
+1
