### ISSUE TITLE
alias fa-circle to fa-record

### ISSUE THREAD

**Issue by abyx** [FortAwesome/Font-Awesome#2555]
Since there's already `fa-play`, `fa-pause` and `fa-stop`, and `fa-circle` is a great looking record button, that alias sounds like the right thing to add, IMO.

**Comment by koulanurag** [comment]
+1

**Comment by jcrawford** [comment]
+1

**Comment by Cherubyx** [comment]
+1

**Comment by ceorcham** [comment]
+1

**Comment by Crissov** [comment]
Unicode emoji: #222

- [⏺ U+23FA](http://emojipedia.org/black-circle-for-record/)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
