### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by Knightling** [FortAwesome/Font-Awesome#2557]
Hello,
Can you please create these icons? That would be awesome! 

•scuba diver
•swimmer
•boat/cruise ship
•passenger airplane 
•snorkel

Thanks so much!
-Kellie
![fins](https://f.cloud.github.com/assets/6157150/1720718/770f1f80-620b-11e3-8cd5-1f369ed000f1.jpeg)
![boat](https://f.cloud.github.com/assets/6157150/1720719/770f67e2-620b-11e3-8529-07db71442de1.jpg)
![scuba](https://f.cloud.github.com/assets/6157150/1720720/770f711a-620b-11e3-8d9d-b5f7c8cf4598.jpeg)
![plane](https://f.cloud.github.com/assets/6157150/1720721/770fcd4a-620b-11e3-9e87-c362b17f903f.png)
![snorkel](https://f.cloud.github.com/assets/6157150/1720722/7710f724-620b-11e3-86f8-cd8f64755c9f.jpg)
![swim-icon](https://f.cloud.github.com/assets/6157150/1720723/771e7534-620b-11e3-9cc9-f5d5bf9c7fcf.jpg)

**Comment by tagliala** [comment]
Hi, this request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Sorry, I have to close this one

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by repat** [comment]
+1 for scuba

**Comment by anthony0030** [comment]
+1
