### ISSUE TITLE
Icon Request: Panoramio

### ISSUE THREAD

**Issue by xiavos** [FortAwesome/Font-Awesome#2562]
Hi,

I'd also love to see an Icon for Panoramio.com.

Thank you.

**Comment by glogloman** [comment]
I also want to use icon of Panoramio on my web to link my photos on google maps. ;)

**Comment by nasospsa** [comment]
Add Panoramio plz

**Comment by aethior** [comment]
Panoramio was closed in 2016 by Google. ([more info](https://en.wikipedia.org/wiki/Panoramio))

Regards.

cc/ @tagliala
