### ISSUE TITLE
Icon Request: Wired Networking

### ISSUE THREAD

**Issue by peelman** [FortAwesome/Font-Awesome#2565]
Ethernet:

![](http://files.peelman.us/ethernet.png)

**Comment by faquino** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/560161/5709166/d1400256-9a97-11e4-8925-cae9922593fc.png)
Awful example, but I see this more 'standard' than the first suggestion, which imho is more 'mac-ish'

**Comment by peelman** [comment]
I'd be fine with this one as well:

![](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/ethernet_on.png)

**Comment by paolofulgoni** [comment]
+1

**Comment by cirosantilli** [comment]
@faquino +1.

**Comment by UpperAvenue** [comment]
+1

**Comment by jwjames83** [comment]
+1

**Comment by rhetr** [comment]
+1

**Comment by miguxbe** [comment]
+1

**Comment by colbroth** [comment]
+1

**Comment by PlasmaPower** [comment]
+1

**Comment by donothingloop** [comment]
+1

**Comment by marksie1988** [comment]
+1

**Comment by dbslusser** [comment]
+1

**Comment by schreiyarai** [comment]
+100

**Comment by baalthazaar1** [comment]
+1

**Comment by boolean-is-null** [comment]
+1
for wired ethernet/lan/rj45
![10271-200](https://cloud.githubusercontent.com/assets/9247235/9474232/ad39951a-4b5f-11e5-8272-8f6b4861539d.png)

**Comment by tgulati** [comment]
+1

**Comment by akiraware** [comment]
+1

**Comment by thewellington** [comment]
+1

**Comment by socialbit-at** [comment]
+1

**Comment by purpleKarrot** [comment]
+1

**Comment by maximvd** [comment]
+1

**Comment by kwinne** [comment]
+1

**Comment by moriartp** [comment]
+1

**Comment by MadTiago** [comment]
+1

**Comment by VladVP** [comment]
+1

**Comment by leesah** [comment]
+1

**Comment by boolean-is-null** [comment]
I use the github logo, because when it's small enough it kiiinda looks like an rj-45 socket.

**Comment by MaienM** [comment]
+1

**Comment by obatiuk** [comment]
+1

**Comment by redzioch** [comment]
+1

**Comment by mustafawm** [comment]
+1

**Comment by MikeyR16** [comment]
+1

**Comment by ACXgit** [comment]
+1

**Comment by cassidyjames** [comment]
+1

**Comment by cassidyjames** [comment]
@elementary has an open source ethernet icon available at https://github.com/elementary/icons/blob/master/status/symbolic/network-wired-symbolic.svg

**Comment by wolfgangmeyers** [comment]
+1

**Comment by kamyarg** [comment]
+1

**Comment by ammarnajjar** [comment]
+1

**Comment by danrl** [comment]
+1

**Comment by TorbenJ** [comment]
+1

**Comment by abjugard** [comment]
+1

**Comment by apinner** [comment]
+1

**Comment by pasci84** [comment]
+1

**Comment by bb-dsa** [comment]
+1

**Comment by XenGi** [comment]
+1

**Comment by milktea02** [comment]
+1

**Comment by jtomara** [comment]
+1

**Comment by smcmurray** [comment]
+1

**Comment by pinkisemils** [comment]
+1

**Comment by driannaude** [comment]
+1

**Comment by tchellomello** [comment]
+1

**Comment by TheFirstAvenger** [comment]
+1

**Comment by zxfrank** [comment]
+1

**Comment by dragomang87** [comment]
+1

**Comment by alexthemitchell** [comment]
+1

**Comment by hallelulius** [comment]
+1

**Comment by maczor** [comment]
+1 come on - over 2 years?

**Comment by Shad0wGeneral** [comment]
+1

**Comment by troyswanson** [comment]
+1, general networking would be awesome

**Comment by tryton-vanmeer** [comment]
+1

**Comment by ThePhoenixRiseth** [comment]
+1

**Comment by tjtoml** [comment]
+1

**Comment by cassidyjames** [comment]
# Please do not `+1` comment on issues
Github has the handy reactions feature where you can put a :+1: on the original issue rather than continuing to flood the comments and everyone's emails.

_...Sorry for bothering anyone who's email-subscribed to this, hopefully it can cut down on noise for the future, though._

**Comment by kuanyen** [comment]
I wonder if this will be added to Font Awesome?

**Comment by tjohnman** [comment]
I'm posting +1 here with the express intention of annoying @cassidyjames because this icon should already be part of Font Awesome after four years.

**Comment by abjugard** [comment]
@tjohnman +1

**Comment by cassidyjames** [comment]
@tjohnman @abjugard I have nothing to do with the FontAwesome project, for what it's worth.

**Comment by Chiggins** [comment]
+1

**Comment by Simbaclaws** [comment]
Still no ethernet port icon?

I suggest something like this:
![eth0](https://user-images.githubusercontent.com/12895506/32960737-5d98d37e-cbc6-11e7-9ea0-585f672986d2.png)

It's literally the first image in google search when typing: ethernet port icon...

**Comment by kirilmaz** [comment]
+1

**Comment by kirilmaz** [comment]
![wired-network](https://user-images.githubusercontent.com/16680133/35193109-c39ba3dc-fea6-11e7-9c2a-17d97f849fa5.png)

**Comment by edward-shen** [comment]
+1

**Comment by cbrightly** [comment]
+1

**Comment by jtomara** [comment]
I'm confident that new fonts have been abandon.

**Comment by crocket** [comment]
Ethernet disconnection icon is useful, too.

**Comment by Bradyok** [comment]
+1

Maybe something like this:
https://icons8.com/icon/789/ethernet-off

I also agree with an on and off, maybe lightning bolt or something to show there's a connection problem or / through it.

**Comment by somospocos** [comment]
While this is still open, which existing icon are you people using for an ethernet wired connection?

I found boxes () in logistics category so far so far

**Comment by Faham** [comment]
So far I'm using '' instead!

**Comment by sensibleworld** [comment]
We added a wired network icon in 5.4: https://fontawesome.com/icons/network-wired?style=solid

**Comment by fuu0** [comment]
This is an Symbol for an bus-based Network. Is it really so hard to add an symbol like kirilmaz or Simbaclaws asked for?!?

**Comment by XenGi** [comment]
@sensibleworld Really? So it took you 5 full years to add the wrong icon. At least you constantly ignored all the good and correct suggestions that were posted in here. Well done..

**Comment by crocket** [comment]
There is no need to complain. nerdfonts has what you want.

On https://nerdfonts.com/#cheat-sheet, find `nf-mdi-ethernet`.
