### ISSUE TITLE
Icon Request : Hg, Bzr, SVN, Darcs, Git

### ISSUE THREAD

**Issue by zaabjuda** [FortAwesome/Font-Awesome#2574]
Could you add the this icons?
This the icons of popular version control systems.

hg - Mercurial http://www.selenic.com/hg-logo/logo-droplets.svg 
bzr - bazaar http://upload.wikimedia.org/wikipedia/en/c/c1/Bazaar_logo_%28software_product%29.svg
svn - SVN http://upload.wikimedia.org/wikipedia/de/3/30/Subversion_logo.svg
darcs - Darcs http://darcs.net/img/logos/logo.svg
git - Git http://git-scm.com/images/logos/downloads/Git-Icon-Black.eps

For example there is a service that shows the source code repository that is hosted on different VCS.

If it helps, I have prepared these icons
https://www.dropbox.com/sh/obmsnnyu57eadpq/kDivL9baGw

**Comment by codiuscube** [comment]
Yes SVN Icon.

**Comment by Garrcomm** [comment]
+1

**Comment by tagliala** [comment]
Sorry, this request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

please open new individual requests having care of searching for duplicate before

**Comment by codiuscube** [comment]
I didn't contribute this. I upvoted it. Doesn't seem very friendly btw.

On Thursday, July 16, 2015, Geremia Taglialatela <notifications@github.com>
wrote:

> Sorry, this request doesn't meet our contributing guidelines:
> https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
>
> please open new individual requests having care of searching for duplicate
> before
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/2574#issuecomment-121931308>
> .
>


-- 
Sent from Mobile
