### ISSUE TITLE
Icon Request: Temperature (Thermometer)

### ISSUE THREAD

**Issue by apinzon** [FortAwesome/Font-Awesome#2586]
Please create an icon that will work to put next to a temperature number.

**Comment by israelhope** [comment]
+1

**Comment by miladmeidanshahi** [comment]
+1

**Comment by danielreispereira** [comment]
+1

**Comment by tagliala** [comment]
@danielreispereira 

http://fontawesome.io/icon/thermometer-full/
http://fontawesome.io/icon/thermometer-empty/
http://fontawesome.io/icon/thermometer-quarter/
http://fontawesome.io/icon/thermometer-half/
http://fontawesome.io/icon/thermometer-three-quarters/
