### ISSUE TITLE
Icon Request: Weather

### ISSUE THREAD

**Issue by apinzon** [FortAwesome/Font-Awesome#2587]
Please create an icon (or an icon set) for displaying general weather information. 

![climacons](https://f.cloud.github.com/assets/6188710/1749894/10719b94-654f-11e3-8e14-4d419e0a4168.gif)

**Comment by tagliala** [comment]
this request doesn't meet our contributing guidelines. I'm keeping this open for reference

**Comment by rivulent** [comment]
+1 for a "weather" icon that includes a cloud with rain, with sun peeking out from behind -- the universally recognized icon for "weather".

**Comment by Souldat** [comment]
+1

**Comment by deepshah1993** [comment]
+1

**Comment by Groman123** [comment]
+1

**Comment by edprince** [comment]
+1

**Comment by tagliala** [comment]
Closing here because it is a duplicate of #155
