### ISSUE TITLE
Icon Request: icon-server

### ISSUE THREAD

**Issue by ScottBeeson** [FortAwesome/Font-Awesome#2596]
This seems obvious to me, but I didn't see anything in a quick search.  There are icons for desktop, laptop, tablet and phone, but I would like to see one for server.

Something like this:
![image](https://cloud.githubusercontent.com/assets/2358206/3157929/66bb831a-eafc-11e3-9495-7f600b4c4cbb.png)
Or 

![image](https://cloud.githubusercontent.com/assets/2358206/3157933/756e1c9c-eafc-11e3-8301-ef421023dced.png)

**Comment by axelfontaine** [comment]
+1

**Comment by aphex13** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.3.0-wip branch. :)

**Comment by tagliala** [comment]
closing here

**Comment by penne12** [comment]
Awesome, thanks!

**Comment by smithandre** [comment]
+1

**Comment by tagliala** [comment]
@smithandre http://fortawesome.github.io/Font-Awesome/icon/server/
