### ISSUE TITLE
Icon Request: icon-octagon, icon-stop-sign

### ISSUE THREAD

**Issue by nickmavros** [FortAwesome/Font-Awesome#2599]
I would like to have either an octagon shape on which I can stack other icons or a stop sign icon to use for an error alert.

![image](https://f.cloud.github.com/assets/1489317/1758372/328440e8-668e-11e3-9c8b-f800041d77a7.png)

![image](https://f.cloud.github.com/assets/1489317/1758374/3dbe64c0-668e-11e3-9a99-adab541e4dbc.png)

**Comment by leblangi** [comment]
+1

**Comment by eshwaralla** [comment]
+1

**Comment by jwmapana** [comment]
+1
