### ISSUE TITLE
icon request: fa-stop-circle

### ISSUE THREAD

**Issue by cambridgemike** [FortAwesome/Font-Awesome#2600]
pause/play/stop make great status icons (especially in table rows). There's already fa-play-circle, so just need the other two to implement this in FA!

Thanks,
Mike

**Comment by lauzierj** [comment]
+1

**Comment by aethior** [comment]
Hi @cambridgemike,

This icon was added in v4.5.0.
Check https://fontawesome.com/icons/circle-stop

Regards.

cc/ @tagliala
