### ISSUE TITLE
Icon Request: Microlancer

### ISSUE THREAD

**Issue by pizza0502** [FortAwesome/Font-Awesome#2601]
Icon Request: Microlancer www.microlancer.com

**Comment by lancesnider** [comment]
Microlancer's name was changed to Envato Studio: https://studio.envato.com. The icon for the logo is just the Envato logo leaf, which is found in this issue (https://github.com/FortAwesome/Font-Awesome/issues/5851) so this can probably be closed.

**Comment by aethior** [comment]
> Microlancer's name was changed to Envato Studio: https://studio.envato.com. The icon for the logo is just the Envato logo leaf, which is found in this issue (#5851) so this can probably be closed.

@tagliala The other request has more upvotes. I think you can close here.
