### ISSUE TITLE
Icon-Request: Check (Money/Bank Check/Cheque)

### ISSUE THREAD

**Issue by AbbyJanke** [FortAwesome/Font-Awesome#2603]
I think that having a check icon for bank check. This will allow for web interfaces such as shopping carts that allow check payment, icon for paychecks, etc..

Examples:
![18-128](https://f.cloud.github.com/assets/487798/1762683/10d6f3d8-66fb-11e3-9f48-b6283b152ddf.png)

![check_money-512](https://f.cloud.github.com/assets/487798/1762685/14ae94e8-66fb-11e3-921a-c0a781439167.png)

**Comment by rafaelb** [comment]
+1

**Comment by bharley** [comment]
+1

**Comment by dallas** [comment]
+1

would prefer a simpler icon design, and one that is currency agnostic might be best

**Comment by dallas** [comment]
I'm thinking something more like this, perhaps?

![cheque icon](https://cloud.githubusercontent.com/assets/5059/5733663/913b7a60-9b63-11e4-87ba-3f33fc26ff56.png)

**Comment by alissonbarison** [comment]
+1

**Comment by stijnvanbael** [comment]
+1

**Comment by jharrisweinberg** [comment]
+1

**Comment by jdehlin** [comment]
+1

**Comment by spscream** [comment]
+1

**Comment by larissaleite** [comment]
+1

**Comment by thetypebeast** [comment]
+1

**Comment by johnnyfreeman** [comment]
+1

**Comment by Discartyptics** [comment]
+1

**Comment by andytyson** [comment]
+1

**Comment by richardtvaughan** [comment]
+1 

18 months and still no joy?

**Comment by JenSwish** [comment]
+1

**Comment by raghav135** [comment]
+1

**Comment by amlette** [comment]
+1

**Comment by iooK** [comment]
+1

**Comment by Monarobase** [comment]
+1

**Comment by digitaldesigndj** [comment]
+1

**Comment by kanyuga** [comment]
+1

**Comment by Paolocargnin** [comment]
+1

**Comment by philippeboyd** [comment]
+1

**Comment by rafaelMangolin** [comment]
+1

**Comment by techmag** [comment]
+1

**Comment by ddiestler** [comment]
+1

**Comment by vramirez122000** [comment]
+1

**Comment by noblecloud** [comment]
+1

**Comment by DanRovito** [comment]
+1

**Comment by Hipp04** [comment]
+1

**Comment by muhammad-naderi** [comment]
+1

**Comment by drewsauce** [comment]
+1

**Comment by bcbrian** [comment]
+1

**Comment by irperez** [comment]
+1

**Comment by ppazos** [comment]
+1

**Comment by bill-brown** [comment]
+1

**Comment by Marjoel** [comment]
Please +1

**Comment by jacksonj04** [comment]
:+1:

**Comment by abram27** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by elbel86** [comment]
+1

**Comment by funnyfrontend** [comment]
+1111111111111111111111111111111111

**Comment by sanek4life** [comment]
+1

**Comment by demiscient** [comment]
+1

**Comment by wassim6** [comment]
+1

**Comment by xophm1** [comment]
+1

**Comment by richardtvaughan** [comment]
Are you ever going to do this? 2.5 years guys.....

**Comment by KnoxArg** [comment]
+1

**Comment by jehrenzweig** [comment]
+1

**Comment by Uniphix** [comment]
+1

**Comment by iiEpixKittai** [comment]
+1 Come on Font Awesome, you guys are supposed to be "awesome"! Please do this!

**Comment by pierrickrouxel** [comment]
+1 I need this too

**Comment by evantobin** [comment]
+1 Maybe after three years they'll actually do it?

**Comment by vreboton** [comment]
+1

**Comment by clone1018** [comment]
+1

**Comment by darkurse** [comment]
+1

**Comment by karpadiem** [comment]
+1

**Comment by rongallant** [comment]
+1  This must happen!!!  :-)

**Comment by InFerYes** [comment]
+1

**Comment by Uniphix** [comment]
+1

**Comment by AshishGupta001** [comment]
+1

**Comment by iiDatKat** [comment]
Maybe this will be in Font Awesome 5?

**Comment by ganninu93** [comment]
+1

**Comment by dbohl** [comment]
+1

**Comment by mrakholiya** [comment]
+1

**Comment by lhoezee** [comment]
I guess it's not a good sign this is 3 years old. I tried searching the Font Awesome community for an answer but I didn't find anything, so I'll ask it here. I'm hoping someone here could comment.

I'm wondering what is the deciding factor to approve a new icon request. Is it based on how many +1 reactions there are? Then once it's approved, how soon does it become available?

**Comment by techmag** [comment]
I'm a font awesome 5 Pro Kickstarter backer and I approve this Icon :)

Doubt that'll make much difference but what the heck eh?

**Comment by kuntur-studio** [comment]
+1

**Comment by wael101** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1

**Comment by pjrebsch** [comment]
+1

**Comment by asaphfernandes** [comment]
+1

**Comment by matiasiglesias** [comment]
+1

**Comment by bfranklin825** [comment]
+100 -- this is the only payment option missing. It is still a valid form of payment.

**Comment by Rigolon** [comment]
+1

**Comment by dmcmillan** [comment]
+1

**Comment by codyparker** [comment]
+1

**Comment by mnb-dade** [comment]
+1

**Comment by ShadowedMists** [comment]
+1

**Comment by LeftPinkie** [comment]
+1

**Comment by zjorge** [comment]
+1

**Comment by NorthPoleLars** [comment]
Working on a card processing app - bank/certified checks seems like a pretty big oversight. Please?

**Comment by chamss19** [comment]
+1

**Comment by anthomaxcool** [comment]
+1
How is this not made yet

**Comment by painhardcore** [comment]
+1!!!

**Comment by RYRDU** [comment]
+1

**Comment by Ti-Bretin** [comment]
+1

**Comment by mat128** [comment]
+1 too, please :)

**Comment by kiminya-raphael** [comment]
+1

**Comment by hbopuri** [comment]
is this ever going to see the light?

**Comment by francescbassas** [comment]
+1

**Comment by atwalsh** [comment]
+1

**Comment by lorencole** [comment]
+1

**Comment by Willjobs94** [comment]
+1

**Comment by ronan-paul** [comment]
+1

**Comment by studioxite** [comment]
+1

**Comment by Divagnz** [comment]
+1

**Comment by venix** [comment]
+1

**Comment by NorthPoleLars** [comment]
Can I +1000? This seems like such a huge oversight...

**Comment by sensibleworld** [comment]
I just "checked" this in to our in-progress queue.

**Comment by sensibleworld** [comment]
"Check" it out! https://fontawesome.com/icons?d=gallery&q=money-check

**Comment by ulrych8** [comment]
+1
