### ISSUE TITLE
Icon Request: fa-female-avatar, fa-male-avatar

### ISSUE THREAD

**Issue by edusmendes** [FortAwesome/Font-Awesome#2606]
- It would be used in login screens apps or sites when we may choose the sex, or to substitute the image in profile page.

![man-woman-user-icons-set-vector-1094620](https://f.cloud.github.com/assets/6207598/1765923/66e8db88-673c-11e3-88eb-3ca4cfdeb777.jpg)
![download](https://f.cloud.github.com/assets/6207598/1765924/66fac53c-673c-11e3-9c31-c389cf70555c.jpg)

**Comment by trf000** [comment]
+1
