### ISSUE TITLE
Icon Request: Dice

### ISSUE THREAD

**Issue by oliverlukedavenport** [FortAwesome/Font-Awesome#2622]
Perhaps there is one and I'm missing it somewhere. If so, forgive me.

But something like this:
http://game-icons.net/icons/delapouite/dice/png/perspective-dice-six-faces-four.png

EDIT:
And perhaps icons for individual faces. Just an idea.
http://image.shutterstock.com/display_pic_with_logo/134128/134128,1269906786,1/stock-photo-gambling-dice-icons-49864312.jpg

**Comment by fyyyyy** [comment]
+1

**Comment by raldred** [comment]
+1

**Comment by Skinney** [comment]
+1

**Comment by the3hm** [comment]
+1

**Comment by sba** [comment]
+1

**Comment by RidleyDeckard** [comment]
:+1:

**Comment by TSMMark** [comment]
:+1: I would die for this icon.

**Comment by H4kor** [comment]
+1 maybe even d4, d8, d10, d12, d20 ...

**Comment by teknohippy** [comment]
+1 and also a fan of d4, d6, d8, d10, d12 and d20 options as well.

**Comment by nicolasmccurdy** [comment]
How about [these dice icons](http://thenounproject.com/howlettstudios/collection/dice/)? They're licensed under CC BY 3.0.

**Comment by ShaneK** [comment]
+1

**Comment by NShewmaker** [comment]
+1

**Comment by simplystardust** [comment]
:+1: d20!!! Please! Gamers will thank you!

**Comment by IMP1** [comment]
+1

**Comment by Francismori7** [comment]
+1.

**Comment by embersdev** [comment]
+1 and also a fan of d4, d6, d8, d10, d12 and d20 options as well.

**Comment by TSMMark** [comment]
Guys don't forget about the d30.

**Comment by jbnv** [comment]
+1 on the general 6-sided die image and on icons for each number of pips (1-9). The pips can be superimposed on the square icon as needed.

**Comment by carris** [comment]
+1 and also a fan of d4, d6, d8, d10, d12 and d20 options as well.

**Comment by Klakurka** [comment]
+1

**Comment by davidrouten** [comment]
+1 vote for d4, d6, d8, d10, d12, d20!!!!

**Comment by tzusman** [comment]
I just launched [CustomFontIcons.com](https://customfonticons.com/), a place to get crowd-commissioned icons.  All commissioned icons are then released as part of a free font icon set.  A dice icon has already been designed and is available in that set.

**Comment by pctux** [comment]
+1

**Comment by Ladeia** [comment]
+1

**Comment by Fatbat** [comment]
+1

**Comment by shimizurei** [comment]
+1

**Comment by philipbkemp** [comment]
:+1:

**Comment by fuxinlei** [comment]
+1

**Comment by Deleplace** [comment]
+1

**Comment by rugor** [comment]
+1

This one's been bangin' around forever and now that rock, paper and scissors are in 4.4, including die faces seems only natural. There are multiple use-cases such as games or to represent randomness - say in a function. I made a [dice font face](https://github.com/rugor/dice-icon-font) for myself using icomoon on a 16px grid that could be a starting point - though I'm sure it's not the only one out there.

**Comment by dshchupak** [comment]
+1

**Comment by DoWhileGeek** [comment]
+1

**Comment by oshields** [comment]
:+1:

**Comment by geeksareforlife** [comment]
:+1:

**Comment by cinhtau** [comment]
:+1:

**Comment by ferpica** [comment]
+1

**Comment by Mattias1** [comment]
+1

**Comment by alxgiraud** [comment]
+1

**Comment by m44rt3np44uw** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by WreckedAvent** [comment]
:+1:

**Comment by tllit** [comment]
+1

**Comment by imfh** [comment]
+1

**Comment by rodymol123** [comment]
+1

**Comment by corycubbage** [comment]
+1

**Comment by superjova** [comment]
+1

**Comment by jeffmdemers** [comment]
+1 forever. Need something like this.

**Comment by simonfranz** [comment]
+1

**Comment by giorgiobeggiora** [comment]
+1 for d4 d6 d8 d10 d12 d20 d100 icons

**Comment by manianiac** [comment]
+1

**Comment by simonwiles** [comment]
+1

**Comment by FBCastelijns** [comment]
+1 for d4 d6 d8 d10 d12 d20 d100 icons

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-dice was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by gturmel** [comment]
+1

**Comment by mudgw2** [comment]
+1

**Comment by nodecode** [comment]
+1

**Comment by xmiao2** [comment]
+1

**Comment by Teranode** [comment]
been 3 years :| ... 3 +1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by marcaum54** [comment]
(y)

**Comment by brandondrew** [comment]
+1

**Comment by zunjae** [comment]
I'm so confused. Why does FontAwesome have icons for Braille, Transgender logo, a Spaceshuttle and even more uninteresting icons but not for a simple dice? I mean, I love your icons as I have it heavily integrated into my app but this is just weird.

**Comment by LionelMeroni** [comment]
+1

**Comment by TomRyder** [comment]
+1 for d4, d6, d8, d10, d12, d20

**Comment by thotzl** [comment]
+1 for d6 (think that’s enough 😉 )

**Comment by szakharchenko** [comment]
+1 for d6 (and possibly, though not that necessary, d20).

**Comment by collabitron** [comment]
+1 for sure

**Comment by giorgiobeggiora** [comment]
+1 for d4, d6, d8, d10, d12, d20 and don't forget d100 (d%)

**Comment by tgrochowski** [comment]
+1

**Comment by Teranode** [comment]
4 years later

**Comment by jtegtmeier** [comment]
+1

**Comment by skcin7** [comment]
+1

**Comment by jeremylights** [comment]
+1

**Comment by jaykon-w** [comment]
+1 d6 and d20

**Comment by EvanZ** [comment]
Still no dice?

**Comment by thotzl** [comment]
+1 d1 ;P

**Comment by njk18** [comment]
+1

**Comment by rderks88** [comment]
just a heads up to everyone here, with the new font-awesome 5 power transform you should be able to create a dice by combining "ellipsis-v" and "square". Will do so in the next weeks, will post here if I don't forget =D

**Comment by top-jonathan** [comment]
+1 for d6

**Comment by marwej** [comment]
+1

**Comment by EvanZ** [comment]
FWIW, there are all 6 dice icons here: https://materialdesignicons.com/

**Comment by gklandes** [comment]
+6

**Comment by markmaruska** [comment]
+1

**Comment by ms-webdev** [comment]
+1

**Comment by sensibleworld** [comment]
These are in progress!

**Comment by tapastwain** [comment]
+1

**Comment by AlbinGrans** [comment]
+1

**Comment by podoco** [comment]
+1

**Comment by labster** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=dice%20
