### ISSUE TITLE
icon-lxw

### ISSUE THREAD

**Issue by alexonbalangue** [FortAwesome/Font-Awesome#2629]
I the creator contributor,
I autorise you create lxw for on font-awesome to css class
to this images ![lxw](https://f.cloud.github.com/assets/6099946/1796546/6df78ba4-6a75-11e3-9ea0-a17cf5b43f0c.png) http://www.lxw.fr/images/logo/lxw.png

**Comment by aethior** [comment]
The `www.lxw.fr` domain is currently for sale.

cc/ @tagliala
