### ISSUE TITLE
Icon Request: icon-line (icon-line-messenger)

### ISSUE THREAD

**Issue by open2** [FortAwesome/Font-Awesome#2631]
http://en.wikipedia.org/wiki/Line_(application)

naver line instant messaging 

![line_logo](https://f.cloud.github.com/assets/2640011/1797171/9d7274dc-6ab3-11e3-80eb-1a8543837431.jpg)

**Comment by nurikabe** [comment]
+1

**Comment by kadishmal** [comment]
:+1: Really need the LINE icon. We are heavily using Font-Awesome and now need an icon for the LINE messenger. Perhaps something like a chat bubble with a "LINE" word in it like in the official [logo](https://www.google.co.kr/search?q=line+messenger&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ei=LTEFVd7ZOYbImwWK7IKQDA&ved=0CAcQ_AUoAQ&biw=1024&bih=1179#rls=en&tbm=isch&q=line+messenger+icon) would suffice.

I also think rather than having the same icon used in smartphone apps, it should look better to just have the bubble and the name without the outer app-icon frame because with small fonts the name would simply disappear.

**Comment by andygmorris** [comment]
LINE is an extremely popular messaging App.

"Line became Japan's largest social network in 2013. In October 2014 Line announced that it had attracted 560 million users worldwide with 170 million active user accounts. In February 2015, it (LINE) announced the 600 million mark had been passed and 700 million were expected by the end of the year."

Yet, LINE is still not represented in FA. Soon, we (all) hope!?

Official Site : http://line.me/
Wikipedia Page : http://en.wikipedia.org/wiki/Line_%28application%29

Dear FA,
We appreciate everything you do with FontAwesome. Can we please get this one put to bed. The request is over 1yr old and much more important to have now than it was then.

**Comment by khajonpot** [comment]
You can try the below code. I use the svg from @haicim as a based to develop this one.

<glyph glyph-name="line" unicode="&#xe800;" d="m530 684c-227 0-411-155-411-346 0-175 153-319 353-343 2-1 4-1 6-2 29-4 33-15 27-44-7-30-20-57-16-68 4-11 20-18 62 9 43 27 217 157 248 182 12 10 21 19 29 27 71 62 114 146 114 239 0 191-184 346-412 346z m-29-235c4 0 7 0 10-2 3-1 5-2 7-4 2-2 4-5 6-8 2-4 4-7 6-11l79-120 0 122c0 7 2 13 5 17 4 4 8 6 14 6 6 0 11-2 14-6 4-4 5-10 5-17l0-162c0-18-7-27-22-27-4 0-7 1-10 2-3 1-6 3-8 5-3 2-5 5-8 8-2 3-4 7-6 10l-77 119 0-120c0-8-2-14-6-18-3-4-8-6-13-6-6 0-11 2-15 7-3 4-5 9-5 17l0 158c0 7 1 12 2 16 2 4 5 8 9 10 4 3 9 4 13 4z m-82 0c7 0 12-2 15-6 4-4 6-10 6-19l0-161c0-9-2-15-6-19-3-4-8-7-15-7-6 0-10 3-14 7-4 4-6 10-6 19l0 161c0 9 2 15 6 19 3 4 8 6 14 6z m-147 0c6 0 11-2 15-6 4-4 6-10 6-19l0-149 61 0c7 0 12-2 16-5 3-3 5-7 5-12 0-5-2-9-5-12-4-3-9-5-16-5l-77 0c-9 0-15 2-19 6-4 4-6 10-6 19l0 158c0 9 2 15 5 19 4 4 9 6 15 6z m429-1l85 0c7 0 12-1 15-4 3-3 5-7 5-12 0-5-2-8-5-11-3-3-8-5-15-5l-70 0 0-50 63 0c6 0 11-1 14-4 3-3 5-7 5-12 0-4-2-8-5-11-3-3-8-4-14-4l-63 0 0-59 73 0c7 0 12-1 15-4 3-3 5-7 5-12 0-5-2-9-5-12-3-3-8-5-15-5l-88 0c-9 0-16 2-20 6-4 4-6 11-6 20l0 154c0 6 1 11 3 14 2 4 4 7 8 9 4 1 9 2 15 2z" horiz-adv-x="1000" />

Note: this code is generated by fontello

**Comment by mylastof** [comment]
over than 1 year -_-
still waiting but .....

**Comment by wintre** [comment]
+1

**Comment by ironmancris** [comment]
+1

**Comment by kamijoutouma** [comment]
+1

**Comment by adhikapelagosa** [comment]
+1

**Comment by ckarea** [comment]
+1

when can we see it?

**Comment by keigofukugaki** [comment]
+1

**Comment by belladict** [comment]
+1

**Comment by uyab** [comment]
+1

**Comment by davidapple** [comment]
+1

**Comment by kamijoutouma** [comment]
Almost 2 years and still no approval D:

**Comment by kechol** [comment]
+1

It would be great if there are both of no-square version(icon-line) and  square version(icon-line-square).

![line_icon_green](https://cloud.githubusercontent.com/assets/625489/9955569/f71795bc-5e2c-11e5-9072-1df94968a493.png)
![line_icon02](https://cloud.githubusercontent.com/assets/625489/9955572/f97e9170-5e2c-11e5-963b-e6177daed1df.png)

**Comment by rippledj** [comment]
please!

**Comment by maninthemirror** [comment]
+1
(´；ω；｀) Please (kneel)

**Comment by luhuiya** [comment]
+1 please ORZ

**Comment by miffyC** [comment]
+1 plz~~~Q_Q

**Comment by billy3321** [comment]
+1

**Comment by natsumiaya** [comment]
+1

**Comment by alex621** [comment]
+1

**Comment by erilin20** [comment]
+1

**Comment by ombwp** [comment]
+1

**Comment by kentislove** [comment]
+1

**Comment by Pseric** [comment]
+1

**Comment by yogoeasy** [comment]
+1

**Comment by zjasonyang** [comment]
+1

**Comment by fuyuanli** [comment]
+1

**Comment by SBJ092190** [comment]
+1

**Comment by FreedomKnight** [comment]
+1

**Comment by tedliou** [comment]
+1

**Comment by georgehu45** [comment]
+1

**Comment by brownsugar** [comment]
+1

**Comment by worrawutp** [comment]
+1

**Comment by esofthard** [comment]
+1

**Comment by zblue89** [comment]
+1

**Comment by ergakandly** [comment]
+1

**Comment by pinglamb** [comment]
+1

**Comment by bhumipat** [comment]
+1

**Comment by sing1234** [comment]
+1

**Comment by toko44a** [comment]
+1

**Comment by prihandoko** [comment]
+1

🙇🙇🙇🙇🙇

**Comment by hardwinder** [comment]
:up: vote

**Comment by irobust** [comment]
+1

**Comment by suabahasa** [comment]
+1

**Comment by pentatonicfunk** [comment]
+1

**Comment by zakyyudha** [comment]
+1

**Comment by twsiyuan** [comment]
+1

**Comment by kei0719** [comment]
+1

**Comment by ssathaporn** [comment]
+1

**Comment by DenisDov** [comment]
+1

**Comment by eiyu** [comment]
+1

**Comment by BobbyWibowo** [comment]
+1

**Comment by ppanuwat** [comment]
+1

**Comment by steve750312** [comment]
+1

**Comment by cjmling** [comment]
+1

**Comment by kei0719** [comment]
hi guys! I made LINE icon with [Fontello.com](http://fontello.com/) and [Simple Icons (icon-libs)](https://simpleicons.org/)
That's not too difficult to make it unless you have proper SVG's LINE icon image.

Just use as temporary by the time coming to font-awesome, if you like!
( or make it yourself)

[github:several-icons (this is mine, but another account)](https://github.com/cupof-github/several-icons)

**Comment by DesktopWebSpecialist** [comment]
Not sure I understand how to get my icon added so I can use it on my
website

**Comment by BobbyWibowo** [comment]
@kei0719 Do I need the other CSS files other than the fontello.css? I suppose that and all of the font files are enough though.

**Comment by kei0719** [comment]
@BobbyWibowo 
You can use it just import 'several-icons/css/fontello.css" in your HTML file.

I think other css are for legacy browser and so. ( like, "fontello-ie7.css", right?)
check it wiki page! [fontello wiki page](https://github.com/fontello/fontello/wiki/Help)

**Comment by eiyu** [comment]
I'm sorry sir, do you considering the terms of use see: http://line.me/en/logo/guideline? 
I don't realy get it

**Comment by viankakrisna** [comment]
+1!

**Comment by freeazy** [comment]
+1

**Comment by derek-tw** [comment]
+1

**Comment by yvonnele** [comment]
+1

**Comment by dean31815** [comment]
+1

**Comment by sahatatekkom** [comment]
+1

**Comment by cwang22** [comment]
+1

**Comment by afgnsu** [comment]
+100

**Comment by yy8678** [comment]
+1

**Comment by 3x14159265** [comment]
+1

**Comment by KannipaB** [comment]
+ 1

**Comment by KazuyoshiTsuchiya** [comment]
+1

**Comment by kiputgalak** [comment]
+1

**Comment by indianazhao** [comment]
+1

**Comment by bjornharvold** [comment]
+1

**Comment by bedeviere** [comment]
+1

**Comment by mcparrish** [comment]
+1

**Comment by shihao316558512** [comment]
+1

**Comment by shihao316558512** [comment]
+1

**Comment by chenyouz** [comment]
+1

**Comment by haimoto** [comment]
+1
http://hu-ten.com/wp-content/uploads/2016/06/linevoip.png

**Comment by pollypan** [comment]
+1 😃

**Comment by Rutashen** [comment]
+1 pleasssssse

**Comment by okazou** [comment]
+1

**Comment by sergeiten** [comment]
+1

**Comment by ayatnos** [comment]
+1 *-*

**Comment by suryawono** [comment]
+1

**Comment by takeruadelbert** [comment]
+2

**Comment by makoxxmako** [comment]
+1

**Comment by ewan777** [comment]
+1

**Comment by gigapixel** [comment]
+1

**Comment by nbilz** [comment]
+9999999

**Comment by somsakkyy** [comment]
+1

**Comment by t2wu** [comment]
+1
Come on guys. It's the fourth most popular mobile messaging app world-wide base on [this](https://www.similarweb.com/blog/worldwide-messaging-apps) and probably take you guys like, what, 10 minutes to make it? :p

**Comment by suebphatt** [comment]
A MUST

**Comment by whereskarlo** [comment]
+1 PLEAAASE add the Line icon! This is the biggest chat app in Asia and is also used extensively for e-commerce and talking to customers. They have all their resources online, including SVG files, black on white, white on black, and colored versions.
![line_icon_white](https://cloud.githubusercontent.com/assets/2850757/17083931/896acc6a-51af-11e6-9fb1-65cdae27786d.png)
![line_icon01](https://cloud.githubusercontent.com/assets/2850757/17083932/896b059a-51af-11e6-90cf-dfcdcd783016.png)
![line_icon_black](https://cloud.githubusercontent.com/assets/2850757/17083933/896b57a2-51af-11e6-8771-3e4c924217f8.png)
![line_icon_green](https://cloud.githubusercontent.com/assets/2850757/17083934/896bd6c8-51af-11e6-9a4c-a5364a892c97.png)

You can download the resources on this link: http://line.me/en/logo

**Comment by sixsckert** [comment]
+1

**Comment by caturprayogo** [comment]
:+1: +1
Asian need this.

**Comment by whereskarlo** [comment]
I ended up making a font of my own with the line icon using Fontastic. If
anyone needs it or wants it let me know.

**Comment by caturprayogo** [comment]
That will be great if you can share with us.
It will be temporary solve our problem. Really appreciate it. :smiley:

**Comment by manmohan-bisht** [comment]
+1
Any idea when we can get this in library?

**Comment by synchro7** [comment]
+1
I would very much appreciate it.

**Comment by whereskarlo** [comment]
Hope you will get it it's attached!

**Comment by whereskarlo** [comment]
[linefont.zip](https://github.com/FortAwesome/Font-Awesome/files/407550/linefont.zip)

The line font is attached!

**Comment by chief725** [comment]
+1

**Comment by TheGermanGuy** [comment]
+1

**Comment by michael-ni** [comment]
+1

**Comment by zsevens** [comment]
+1

**Comment by yehmingchieh** [comment]
+1

**Comment by yong0011** [comment]
+1 hurry up guys

**Comment by alex621** [comment]
Can't believe that it is still not included in the package after all these years

**Comment by Reo7s** [comment]
+1

**Comment by ifeelingz** [comment]
+1

**Comment by slobgame** [comment]
LINE +1

**Comment by chungdvaic** [comment]
+1

**Comment by sn3ka** [comment]
+1

**Comment by azharfauzandz** [comment]
+1

**Comment by boonsanti** [comment]
+1

**Comment by azharfauzandz** [comment]
+1

**Comment by vincentkedison** [comment]
+1

**Comment by fxpian** [comment]
+1

**Comment by tericky** [comment]
+1

**Comment by LionLai** [comment]
+1

**Comment by sarayutpea** [comment]
+1

**Comment by Mopster** [comment]
+1

**Comment by nurikabe** [comment]
+1

**Comment by neatnet** [comment]
+1

**Comment by saiury92** [comment]
+1

**Comment by manhgd94** [comment]
+1

**Comment by pku145** [comment]
+1

**Comment by lloydmeta** [comment]
+1

**Comment by kawin-aur** [comment]
+ 1

**Comment by mahmoodma** [comment]
Wow, quite surprise this lasted such a long time.

+1

**Comment by CanRau** [comment]
+1

**Comment by KopiSusu** [comment]
+1

**Comment by henrylindesign** [comment]
+1

**Comment by korn3l** [comment]
+1

**Comment by slobgame** [comment]
+1

**Comment by bradonomics** [comment]
+1

**Comment by lostllama** [comment]
+1

**Comment by suebphatt** [comment]
guys?
it's been a long time!
you guys have argument with Naver or something? :\

**Comment by maxkub123** [comment]
please add this logo as soon as possible :)

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[Line icon is here](https://sleeklogos.design/web-app/21746/line-me)

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones where [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852)

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by grettely** [comment]
+1 please

**Comment by Indranurawan** [comment]
+1 please.

**Comment by rebornishard** [comment]
dude please 2 years without line icons

**Comment by edwinnnss** [comment]
+1

**Comment by ayoa77** [comment]
+1

**Comment by AzioArv** [comment]
+1

**Comment by kevinraja1001** [comment]
+1

**Comment by andyyou** [comment]
+1 if it could happen

**Comment by NickyLogan** [comment]
+1

**Comment by ersaldyraisha** [comment]
+1

**Comment by maccharkrit** [comment]
+1

**Comment by tngan** [comment]
+1

**Comment by CodeSurfing145** [comment]
+1

**Comment by JSilaban** [comment]
+1

**Comment by chodaict** [comment]
This issue is started at 2013, now is 2017...(my heart is broken💔)

**Comment by nevagency** [comment]
+1

**Comment by luthviar** [comment]
+1

**Comment by yonathansebhastian** [comment]
+1

**Comment by dennislaupman** [comment]
+1

**Comment by sigitgirianto** [comment]
+1

**Comment by phranakornsoft** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by piyuid** [comment]
+1

**Comment by Ratthanarong** [comment]
+1
