### ISSUE TITLE
Icon Request: icon-window-open (house window)

### ISSUE THREAD

**Issue by yglodt** [FortAwesome/Font-Awesome#2633]
Hello,

I am using font-awesome icons in my SmartHome software. Many icons fit my requirements. What I am missing is an icon representing a window. I do not want to use fa-windows ;-)

I could imagine something like in the attached image, e.g. the first one (top-left).

Thanks in advance, with the hope of my request to be useful.

![ve-1553-prev](https://f.cloud.github.com/assets/489599/1798425/a401c430-6b4c-11e3-82f4-76765fda2db4.jpg)

**Comment by sensibleworld** [comment]
We've got a couple options for this now: https://fontawesome.com/icons?d=gallery&q=window%20frame
