### ISSUE TITLE
Icon request: recipe icons

### ISSUE THREAD

**Issue by leelooille** [FortAwesome/Font-Awesome#2634]
Hello, 

It would be great if you could add the icons necessary for a recipe : hoven (for the cooking time), a chef's hat, some food icons for the ingredients, a fork and knife etc. 

The currencies icons with a circle background could be great too! (i'm using euro)

Thanks a lot in advance, regards
Marie

**Comment by tagazok** [comment]
+1.
If anyone konws an icon font cooking/kitchen oriented :)

**Comment by Blizzard75** [comment]
+1 (especially fork and knife)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Please check for duplicates and +1 existing requests or create new individual requests

closing here
