### ISSUE TITLE
Icon Request: fa-cross-square (fa-times-square)

### ISSUE THREAD

**Issue by RichardAlan** [FortAwesome/Font-Awesome#2636]
I have an application that marks a user exam question as correct or incorrect. The icon fa-check-square would be a good one to use for correct but I would also like to have an fa-cross-square with a cross mark inside the square. I think this could have many uses. Hope you will consider adding it. Thanks

**Comment by dmland** [comment]
+1 for complete sets (plain, circle, square, with open and solid versions) for ﹢, ﹣, and ✕. Also, complete sets of ! and ?. [Comment moved from closed item #2985]

**Comment by Fatbat** [comment]
Yup, what they said ^^^ I'll ad the info "i" to that mix. Needed it in a square, but it only comes in a circle.

**Comment by Jomes87** [comment]
Fatbat you can use stacked icons to do that. See Stacked Icons in the examples:

http://fortawesome.github.io/Font-Awesome/examples/

**Comment by Fatbat** [comment]
Jomes87, I am aware of stacked icons, but as far as I can tell they can only be created at double the size of a normal icon. So while I might want to use an "info circle" at 12px, to create the same thing as an "info square", stacking the info i on top of a square, it will turn out to be 24px. I've not been able to figure out how to change this. If you've got an example how, that would be great!

**Comment by Jomes87** [comment]
Hi Fatbat,
I am not 100% sure what you require but hopefully the following helps:

Option 1 - changing overall sizes of stack: 
Changing the font-size of the fa-stack span will change the over all size of the stack as the 2x icon (square or circle) uses em to just the size.

Option 2 changing size of icon within stack:
Changing the font size of the icon  separately to the stack or the 2x icon should allow you to set the info figure independanty to the square. 

If you need any more help with it I maybe able to sort an example

**Comment by Samsinite** [comment]
:+1:

**Comment by YuZA2013** [comment]
Exactly i need  fa-cross-square , fa-cross-circle   +1

**Comment by fabswt** [comment]
+1, especially for a negative variant of check-square-o.

Perfect for a Don'ts and Dos list (or Pros and Cons, etc.)

**Comment by willemwy** [comment]
+1

**Comment by Fatbat** [comment]
It would be nice if this made it into the next update.

**Comment by naldir** [comment]
+1
Needed in form-control section

**Comment by karpadiem** [comment]
+1

**Comment by CedCannes** [comment]
+1

**Comment by mroftalp** [comment]
+1

**Comment by WACMemphis** [comment]
+1

**Comment by mazino** [comment]
+1

**Comment by ZKajzer** [comment]
+1

**Comment by ginere** [comment]
+1

**Comment by coneybeare** [comment]
+1

**Comment by diegocastro** [comment]
+1

**Comment by fredperes** [comment]
+1

**Comment by gquipster** [comment]
+1

**Comment by jrx-vag** [comment]
+1

**Comment by ImDaveead** [comment]
+1

**Comment by zdarovka** [comment]
+1

**Comment by zdarovka** [comment]
Stack is definitely one of the options to do it, but in my case I needed to have the HTML simple as possible, also the stack gave me a little bit styling headache.

My solution is to create "custom" icon of existing one
`.fa-cross-square-o {
        &:before {
            content: "\f096";
        }

        &:after {
            content: "\f00d ";
            font-size: 0.5em;
            position: relative;
            margin-left: -15px;
            top: -5px;
            margin-right: 5px;
        }
    }`

**Comment by tagliala** [comment]
There is a slightly rectangular option: http://fontawesome.io/icon/window-close/

**Comment by Eishfaq** [comment]
You can use 
`fa fa-close`

**Comment by tagliala** [comment]
Oh, this has been implemented in Font Awesome Pro 5.0

https://fontawesome.com/icons/times-square?style=solid

For free users: 

You can easily achieve **almost** the same icon with the SVG framework, by using the masking feature and power transforms:

Demo: https://jsfiddle.net/tagliala/we7gtcvk/32/

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking

Closing here
