### ISSUE TITLE
Academic Icon's

### ISSUE THREAD

**Issue by mawartani** [FortAwesome/Font-Awesome#2649]
Can you please add some Academic Icon's

**Comment by aethior** [comment]
`fa-graduation-cap` (http://fontawesome.io/icon/graduation-cap/) and `fa-university` (http://fontawesome.io/icon/university/) were added in v4.1.

cc @tagliala

**Comment by tagliala** [comment]
Yep, closing here.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
