### ISSUE TITLE
Font-Awesome icons should be smooth edges like Elusive-Icons.

### ISSUE THREAD

**Issue by shyamkushwaha23** [FortAwesome/Font-Awesome#2651]
Font-Awesome icons should be smoth edges like Elusive-Icons. Current icons are very sharp edge, that looks very odd in some icons. Please zoom-in your Font-Awesome webpage and check how icon looks. It is only reason I am not using Font-Awesome icons though it has more icons than Elusive-Icons including inr / rupee icon.

**Comment by capegreg** [comment]
The limitation for me was access to premium glyphs at a yearly cost of $60. Bootstrap icons fell short on smoothness. I went with material icons and very pleased. [https://design.google.com/icons/](https://design.google.com/icons/)
