### ISSUE TITLE
New icon: fa-gamepad - better version please

### ISSUE THREAD

**Issue by Spinball** [FortAwesome/Font-Awesome#2653]
The fa-gamepad icon could be improved IMO.
Is there any chance it could be changed to something better representing a gamepad?
For example:
![gamepad](https://f.cloud.github.com/assets/5878475/1811027/e643cfaa-6e3f-11e3-9d93-08efc4dd28a2.png)
I have the above image as a vector if you want it.
Many thanks.

**Comment by sensibleworld** [comment]
Picking up the thread on some old issues, and wanted to let you know we have a some new gamepads available in FA 5: https://fontawesome.com/icons?d=gallery&q=gamepad
