### ISSUE TITLE
Icon request: globe-frame (globe wireframe internet)

### ISSUE THREAD

**Issue by glaforge** [FortAwesome/Font-Awesome#2655]
I'd like to see a "globe" icon.
We have an earth looking like icon, but I'd want something a bit like that:
http://us.123rf.com/400wm/400/400/prill/prill1110/prill111003199/10917096-brushstroke-and-crayon-sketchy-illustration-of-a-globe-in-white-back.jpg
ie. a globe with the longitude and latitude lines.

**Comment by jaketblank** [comment]
:+1: here too!

**Comment by jbsaige** [comment]
+1

I've found a SVG (and PNG, ICO, and ICNS) version of this at
https://www.iconfinder.com/icons/115770/browser_earth_globe_internet_world_icon
with the license Creative Commons (Attribution 3.0 Unported)

Not certain if that helps.
![1423629078_world-512](https://cloud.githubusercontent.com/assets/8528028/6137889/e36fae0a-b139-11e4-9cd5-38fd50abb183.png)

**Comment by seezee** [comment]
+1 Something like this icon I made could be useful for representing the World Wide Web:
![e80de34a-bccf-11e4-9ccb-2305fdf74305](https://cloud.githubusercontent.com/assets/287836/6493634/a29d0ee6-c281-11e4-9542-f9365d4efeab.png)

**Comment by G-Driver** [comment]
+1

**Comment by JSystemsTech** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by marianoluzza** [comment]
+1

**Comment by osurux** [comment]
+1

**Comment by Markkojak** [comment]
+1

**Comment by MichaelTunnell** [comment]
+1

**Comment by eratek** [comment]
I need the normal internet world icon suggesting name fa-inetworld-n just as the last icon what jbsaige posted on this tophic.

**Comment by Knive** [comment]
+1
To me "fa-globe" does not ring a bell compared to the requested "fa-web" icon to mean an website or else

**Comment by jdahlborg** [comment]
+1 for icon-internet. 
In addition to this great request I would like to have the following two icons to use in an order system; icon-pos (point-of-sale) and icon-phone (which already exists)

**Comment by peterppm** [comment]
+ 1 on a website icon.

**Comment by aethior** [comment]
+1

**Comment by erhughes** [comment]
+1

**Comment by StanfordAlan** [comment]
+1 Here too. To me, the current globe looks more like it's an international company icon or a click-here-to-find-our-locations than a true WWW icon. I've taken to using the mouse pointer icon instead, but that's not quite accurate either.

I can't help but find the humor in that such a great set of icons for web (and other) use is an icon for the web. (Yes, I'm twisted like that.) 

Anyway, thanks for all the work!

**Comment by kldoon** [comment]
+1

**Comment by holaneph** [comment]
+1

**Comment by wjdennen** [comment]
+1 thanks!

**Comment by czhao39** [comment]
+1

**Comment by PC-HelpZA** [comment]
+1

**Comment by djbrown** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by MichaelTunnell** [comment]
### Please use emoji thumbs up feature to support this issue, rather than "+1" an issue. Using the emoji thumbs up is more efficient and more importantly, it doesn't send update notifications just for voting (reducing spam).

Thanks!

**Comment by gloofer** [comment]
Three and a half years later, where is the wire-globe icon? I need it :)

**Comment by Cliffsuss** [comment]
+1 where is it???

**Comment by bramax** [comment]
+1 Please!

**Comment by joao-neves95** [comment]
Hello everyone.

Google has one, check it out at:
[](https://www.w3schools.com/icons/tryit.asp?filename=tryicons_google-language)

**Comment by ergec** [comment]
+1

**Comment by arnovanoordt** [comment]
+1

**Comment by tagliala** [comment]
This icon is now available in FA 5.0.0 Free as `fa-globe`

The old `fa-globe` is not abailable anymore.

By the way, I'm going to keep this open

Ref: #11880

**Comment by redoper1** [comment]
Hello @tagliala,

could you please add the old version of ```fa-globe```
icon as alternative for ex. as a ```fa-globe-alt```
 (I already made request in it's own issue, but you referenced it to this one)?

The old version was better for some application cases than this one.

**Comment by tagliala** [comment]
@redoper1 we can use #281 for your request
