### ISSUE TITLE
Icon Request: Roadway / Civil Engineering

### ISSUE THREAD

**Issue by barowdwngs** [FortAwesome/Font-Awesome#2658]
Roadway / Civil Engineering: Construction (hard hat) or (bulldozer), Structure (bridge) or (Freeway Exit).

![images](https://f.cloud.github.com/assets/1088834/1816982/3cd8e8a0-6f62-11e3-8ba4-af518338d459.jpeg)
![images-1](https://f.cloud.github.com/assets/1088834/1816983/3cd982f6-6f62-11e3-8ff3-b531d4de6d57.jpeg)
![images-2](https://f.cloud.github.com/assets/1088834/1816985/3cd99b38-6f62-11e3-9b14-975955783428.jpeg)
![images-3](https://f.cloud.github.com/assets/1088834/1816984/3cd9a06a-6f62-11e3-827f-7f2ae8880a80.jpeg)

**Comment by vinnyamp** [comment]
+1

**Comment by aethior** [comment]
Hi,

Currently there is a [construction category](https://fontawesome.com/search?c=construction) with differents icons related with civil engineering (e.g. [fa-helmet-safety](https://fontawesome.com/icons/helmet-safety)).
There are also separates issues for [bulldozer](https://github.com/FortAwesome/Font-Awesome/issues/4084), [crane](https://github.com/FortAwesome/Font-Awesome/issues/12499) and [bridge](https://github.com/FortAwesome/Font-Awesome/issues/4053) icons (I think is better use differents issues for each request).

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks @aethior
