### ISSUE TITLE
Icons Request: landmarks

### ISSUE THREAD

**Issue by pisandelli** [FortAwesome/Font-Awesome#2661]
Hey guys! I think fontawesome could be even more awesome with some landmarks icons!
I would be very pleased to see the eiffel tower, christ, liberty statue, pyramids and other beatyful landmarks!

Here there is an examples for landmarks: http://flaticons.net/category.php?c=Landmark

Cheers and have a Happy New year!

**Comment by tymorrow** [comment]
+1

**Comment by tagliala** [comment]
Sorry I need to close this request at this moment, please consider a webfont which is landmark related

Closing here
