### ISSUE TITLE
Icon request: icon-toilet-sign (icon-bathroom icon-washroom)

### ISSUE THREAD

**Issue by srikanthlives** [FortAwesome/Font-Awesome#2670]
Icon that appears on the washroom
![toilets](https://f.cloud.github.com/assets/4170763/1823964/1156e1a2-718b-11e3-8730-7898ae33bdc2.png)
 boards.

**Comment by lenamtl** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by Zmoki** [comment]
+1

**Comment by kplese** [comment]
+1

**Comment by renegadeandy** [comment]
+1

**Comment by ZachMoreno** [comment]
+1

**Comment by rvanhoepen** [comment]
+1 need more hospitality icons

**Comment by laviku** [comment]
+1

**Comment by laviku** [comment]
What about this icon?
https://cdn1.iconfinder.com/data/icons/hotel-and-restaurant-line-icons-vol-2/64/053-128.png

**Comment by mediabeastnz** [comment]
+1

**Comment by csdetschjr** [comment]
+

**Comment by wujitouch** [comment]
+1

**Comment by NeilCresswell** [comment]
+1

**Comment by kafenio** [comment]
+1

**Comment by ashish-chopra** [comment]
+1

**Comment by juancarlosfarah** [comment]
+1

**Comment by eithe** [comment]
+1

**Comment by wujitouch** [comment]
You can create your own font file using IcoMoon. Search for toilet
https://icomoon.io/app

**Comment by skifan** [comment]
+1 for bathroom symbol please

**Comment by Rombecchi** [comment]
+1

**Comment by yjivkov** [comment]
+1

**Comment by roldan** [comment]
+1

**Comment by jbarbede** [comment]
+1

**Comment by wac2007** [comment]
+1

**Comment by iamkhush** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by martineznicolasd** [comment]
+1

**Comment by Aquaj** [comment]
+1

**Comment by prYmea** [comment]
+1

**Comment by kokatev** [comment]
+1

**Comment by genni951** [comment]
+1

**Comment by isaachinman** [comment]
+1

**Comment by jjeroennl** [comment]
+1

**Comment by Robot2906** [comment]
+1

**Comment by matijamatija** [comment]
+1

**Comment by ivanjolic95** [comment]
+1

**Comment by stephenferguson** [comment]
+1

**Comment by MarGraz** [comment]
+1

**Comment by karyen92** [comment]
+1

**Comment by deviousgeek** [comment]
+1

**Comment by shfx** [comment]
+1

**Comment by stalinkay** [comment]
+1

**Comment by Zwaen91** [comment]
+1

**Comment by rjpadula** [comment]
+1

**Comment by MasterJuan** [comment]
+1

**Comment by jezzdk** [comment]
+1

**Comment by lghamie** [comment]
+1

**Comment by ScreamingHawk** [comment]
+1 Oops. Made a duplicate

**Comment by Crissov** [comment]
* [🚻 U+1F6BB Restroom](http://emojipedia.org/restroom/)
* [🚾 U+1F6BE Water Closet (WC)](http://emojipedia.org/water-closet/)
* [🚹 U+1F6B9 Mens Symbol](http://emojipedia.org/mens-symbol/)
* [🚺 U+1F6BA Womens Symbol](http://emojipedia.org/womens-symbol/)
* [🚼 U+1F6BC Baby Symbol](http://emojipedia.org/baby-symbol/)
* [♿️ U+267F Wheelchair Symbol](http://emojipedia.org/wheelchair-symbol/)

## Related Unicode characters (emojis)

* [🚰 U+1F6B0 Potable Water Symbol](http://emojipedia.org/potable-water-symbol/)
* [🚱 U+1F6B1 Non-Potable Water Symbol](http://emojipedia.org/non-potable-water-symbol/)
* [🚽 U+1F6BD Toilet](http://emojipedia.org/toilet/) #10126 
* [🚿 U+1F6BF Shower](http://emojipedia.org/shower/)
* [🛁 U+1F6C1 Bathtub](http://emojipedia.org/bathtub/)
* [🛀 U+1F6C0 Bath](http://emojipedia.org/bath/)

**Comment by PlacesForPeopleWebTeam** [comment]
+1

**Comment by frischnetz** [comment]
as a workaround you can use something like that:
`          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i style="margin-left: -0.35em; " class="fa fa-male fa-stack-1x fa-inverse"></i>
            <i style="margin-left: 0.35em; " class="fa fa-female fa-stack-1x fa-inverse"></i>
          </span>`

**Comment by matheusilario** [comment]
+1

**Comment by AdamDiment** [comment]
+1

**Comment by firulais** [comment]
+1

**Comment by tehsandra** [comment]
+1

**Comment by jamesdb** [comment]
+1

**Comment by AshleyKang** [comment]
+1

**Comment by gitzrulz** [comment]
+1

**Comment by Renrhaf** [comment]
+1

**Comment by Zilvinask** [comment]
+1

**Comment by hcygit** [comment]
+1

**Comment by KevKo1990** [comment]
+1

**Comment by eyp** [comment]
+1

**Comment by MeesCode** [comment]
+1

**Comment by EdanBrooke** [comment]
+1 still need a toilet icon...

**Comment by boudafc** [comment]
+1

**Comment by fendorio** [comment]
+1

**Comment by Wayneio** [comment]
+1

**Comment by xuser87** [comment]
+1

**Comment by hassanshaikley** [comment]
+1

**Comment by ALPIXELMaiki** [comment]
+1

**Comment by Pogrim** [comment]
+1

**Comment by adam-rudd-myob** [comment]
+1

**Comment by markmssd** [comment]
+1

**Comment by paulterje** [comment]
+1

**Comment by shemake** [comment]
+1 for this, and also for an actual toilet symbol

**Comment by studioavanti** [comment]
+1, of course it's a very useful missing icon signaling a must-visit place in public places!

**Comment by killermann** [comment]
Hey @sensibleworld, here's an SVG I made you're welcome to use as a starting place. It's the basis for a sign that's being used all over the place, so it would hopefully be recognizable to folks as a restroom indicator:
[All Gender Restroom Sign Toilet.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/2493725/All.Gender.Restroom.Sign.Toilet.svg.zip)

**Comment by sensibleworld** [comment]
@killermann Looks great! I'll likely need to tweak it a bit to fit with the style of our other icons, but this is a great example.

**Comment by killermann** [comment]
Happy it was helpful, @sensibleworld. Tweak with reckless abandon.

**Comment by sensibleworld** [comment]
We've flushed out a couple of new icons.

https://fontawesome.com/icons/restroom?style=solid
https://fontawesome.com/icons/toilet?style=solid

**Comment by markmssd** [comment]
"Flushed" 🤣 nice choice of word
