### ISSUE TITLE
Icon Request: function

### ISSUE THREAD

**Issue by hakunin** [FortAwesome/Font-Awesome#2675]
![img43](https://f.cloud.github.com/assets/65846/1826940/d6aeb32a-7218-11e3-8083-4f467ddcf606.png)

This is how it could look like. I know I can make it with pure text, but it would be nice to have something that fits into the awesome icon set.

**Comment by ogunlegano** [comment]
+1

**Comment by Eonil** [comment]
+1

**Comment by SylvainCorlay** [comment]
+1, ideally, the style would be close to the one of the computer modern font of LaTeX

**Comment by twasyl** [comment]
+1

**Comment by StevenClontz** [comment]
+1

**Comment by mmacret** [comment]
+1

**Comment by lideen** [comment]
+1

**Comment by Justavian** [comment]
+1

**Comment by toioski** [comment]
+1

**Comment by TheColorRed** [comment]
+1

**Comment by antonpod** [comment]
+1

**Comment by ocherdene** [comment]
+1

**Comment by SoerenHenning** [comment]
+1

**Comment by vdrg** [comment]
+1

**Comment by rwsansom** [comment]
+1

**Comment by anurag143** [comment]
+1

**Comment by anupamN** [comment]
+1

**Comment by jackycute** [comment]
+1

**Comment by sassanh** [comment]
+1

**Comment by alberchou** [comment]
+1

I'd rather a "fx" icon instead of a "f(x)" one in order to simplify. But it would be okay too!

**Comment by eZeeCloudTeam** [comment]
+1

**Comment by ashutoshrishi** [comment]
+1

**Comment by gilhanan** [comment]
+1

**Comment by ogis-cai** [comment]
+1

**Comment by ogis-suzuki** [comment]
+1

**Comment by gilhanan** [comment]
well it's simple to achieve it with pure HTML:
``` html
<i>f<sub>(x)</sub></i>
```

_f<sub>(x)</sub>_

**Comment by Justavian** [comment]
gilhanan - If the goal is just to have a single instance somewhere, that does work fine, of course.  However, if you have a bit of code to generate a series of buttons or something like that, it's nice to be able to assume that the icons are font awesome.  The fewer times i have to put in a special case, the better.

In my case, i ended up just making a custom font with some of the icons i wanted, and then i have a CSS file that makes allowances for some of the icons coming from another font.  That way, i can still have my code process a fa-bolt the same was as a fa-my-custom-icon or whatever, and the CSS takes care of getting the right font.

**Comment by polentino** [comment]
+1

**Comment by zoharshavit** [comment]
+1

**Comment by M-Willett** [comment]
+1

**Comment by jonbarthol** [comment]
+1

**Comment by riggerthegeek** [comment]
+1

**Comment by abhisekpmo** [comment]
+1

**Comment by billytianlan** [comment]
+1

**Comment by wtfdaemon** [comment]
How many +1 do we need to get this in?  :)   

Do I need to organize a campaign here?

**Comment by dflock** [comment]
If you add up all the +1's and the :+1: 's, this has 60 votes - which should put it on the [first page of the icon leaderboard](https://fontawesome.com/community/leaderboard/new) :disappointed:

**Comment by dflock** [comment]
Here's a completed faFunction icon that I made that works with Font-Awesome v5, intended for use with the regular style:

```js
module.exports = { prefix: 'far', iconName: 'function', icon: [512, 512, [], 'f2b9', 'M164.9843 2.95626v.00054c-29.04636 0-52.98096 7.98201-71.356461 24.01881-18.016343 15.68201-29.970306 37.86324-35.902001 66.20357l-3.462424 16.44651h-42.39753L1.0873508 163.519425H43.462906L1.5745557 372.9601H67.747031l41.888349-209.440675h69.65152l10.77853-53.893735h-71.09115l2.26933-10.96988c3.17525-14.28857 8.36839-24.65897 15.33435-31.32207 6.93944-6.6377 16.23006-9.99654 28.40634-9.99654 12.1763 0 22.21505 3.3751 30.50845 10.13268l2.39154 1.94882 27.45069-48.97988-1.79178-1.36514c-7.13778-5.43831-15.9058-9.46554-26.2308-12.13242l-.0107-.003c-9.98104-2.66051-20.75888-3.98179-32.31738-3.98179zm328.6981 204.5643442l-41.69967.00161 1.07892 3.3814886c9.42614 29.5351652 14.1241 58.1800362 14.1241 85.9591942 0 36.635113-6.38104 72.950333-19.16338 108.992363v.004l-.003.004c-12.57379 35.83528-30.48215 68.82414-53.74527 99.00333l-3.21855 4.17633h46.3643l.77664-.91596c22.60061-26.6517 40.27424-58.50503 53.0292-95.49428v-.006c12.75281-37.19578 19.13604-75.06 19.13604-113.549235 0-15.99115-1.49241-32.085758-4.47488-48.276158-2.97892-16.171311-6.81533-30.0528027-11.54659-41.6659183zm-284.68995.00161l-.77663.9159876c-22.60284 26.6542792-40.27535 58.6150382-53.02975 95.8153212l.001-.0043c-12.7542 36.987217-19.13766 74.748067-19.13766 113.237297 0 15.99121 1.49299 32.08524 4.47542 48.27562 2.97892 16.17131 6.81533 30.05282 11.54659 41.66591l.65765 1.61489h41.70129l-1.07892-3.38147c-9.42612-29.53515-14.12412-58.18003-14.12412-85.95921 0-36.63728 6.27611-72.84688 18.84663-108.675603l.003-.008c12.78527-36.047878 30.8001-69.142439 54.06204-99.320076l3.21855-4.1763467zm38.13543 65.8519628l2.17125 3.863328 44.95789 79.994305-87.77134 90.39175h52.83839l53.73186-56.80197 31.31779 56.80197h47.77393l-49.36472-87.03706 83.93322-87.212325h-51.52312l-51.50808 53.654685-29.43329-53.654685z'] }
```

![image](https://user-images.githubusercontent.com/47756/41008691-4051bc00-68e1-11e8-9f2c-5a72a545546e.png)

[faFunction.zip](https://github.com/FortAwesome/Font-Awesome/files/2074347/faFunction.zip) - contains the .js file, as well as various .svg source files.

Hereby released into the public domain, so feel free to use it for whatever.

**Comment by tensorcrow** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by DaeHeeLim** [comment]
+1

**Comment by laclance** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/function?style=solid
