### ISSUE TITLE
Icon-circle + Icon-linkedin ( wrong placement ) 

### ISSUE THREAD

**Issue by notflip** [FortAwesome/Font-Awesome#2679]
Hi, The circle + linkedin in a stack is being placed weird

```
<span class="fa-stack fa-md">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
</span>
```

Looking further it's optical, I think it's placed correctly, but it doesn't look centered because of the dot on the i.
Adding a 

```
margin-top: -1px;
```

To the linkedin icon seems to fix the issue

**Comment by tagliala** [comment]
It looks different in FA5.

I'm going to close this, if there is the need to fine tuning the position, please go with custom css or svg transformations

https://jsfiddle.net/tagliala/fnuuz8cf/5/

Ref:
https://fontawesome.com/how-to-use/svg-with-js#masking
https://fontawesome.com/how-to-use/web-fonts-with-css#additional-styling
