### ISSUE TITLE
Icon Request: icon-flashlight

### ISSUE THREAD

**Issue by mbianchi27** [FortAwesome/Font-Awesome#2687]
A nice complimenting icon would be a flashlight, which would go good with the other icons that are available. 

The image below would represent it, maybe just vertical and without the button on the side of it?

![flashlight-128](https://f.cloud.github.com/assets/6311161/1839397/9a66fa4a-7479-11e3-9ac9-d3a980dda65a.png)

**Comment by JustinDrake** [comment]
+1

**Comment by MissChocoe** [comment]
+1

**Comment by JustinDrake** [comment]
@davegandy I'd like to put a $20 bounty for this icon. (Bounty open for 6 weeks, payable in Bitcoin.)

**Comment by leslietou** [comment]
+1

**Comment by jezzerwebb** [comment]
+1

**Comment by tildemark** [comment]
+1

**Comment by lfrdflmng** [comment]
+1

**Comment by stewiem2000** [comment]
+1

**Comment by DHaylock** [comment]
+1

**Comment by umdstu** [comment]
+1

**Comment by sondnm** [comment]
+1

**Comment by DaGLiMiOuX** [comment]
+1 for both flashlight and flaslight-off/slash

**Comment by Spark3000** [comment]
+1!

**Comment by stevenjoezhang** [comment]
+1 !

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=flashlight
