### ISSUE TITLE
Icon Request: icon-path

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2703]
Looking for an Icon for the Path (https://path.com) Network. This round version (visible at http://blog.path.com) is available at http://s3.amazonaws.com/assets.path.com/blog/pages-path-logo.png
![pages-path-logo](https://f.cloud.github.com/assets/1583597/1859909/ff4d534e-77aa-11e3-96f9-2c6a7a56a0b4.png)

**Comment by itsdaffa** [comment]
+1

**Comment by aethior** [comment]
Path was closed in 2018 by Kakao. ([more info](https://en.wikipedia.org/wiki/Path_(social_network)))

Regards.

cc/ @tagliala
