### ISSUE TITLE
Icon Request: icon-man-with-children (students / parents)

### ISSUE THREAD

**Issue by shilpadalmia** [FortAwesome/Font-Awesome#2704]
Would like an icon that shows a boy & a girl to represent a group of happy children. Use case is for any parenting site where you want to represent children.

**Comment by Abildtoft** [comment]
+1

**Comment by Flickster42490** [comment]
+1

**Comment by dapalmi** [comment]
+1

**Comment by nkamate** [comment]
+1

**Comment by stoem** [comment]
+1 for a parent and a family icon

**Comment by edu2004eu** [comment]
+1

**Comment by radubr** [comment]
+1

**Comment by stoem** [comment]
Just re-iterating the request for a parents icon. It is the last icon we are still using from glyphicons, it would be great to have an equivalent to glyphicons-parents
Thanks!
<img width="43" alt="screen shot 2018-02-20 at 19 42 02" src="https://user-images.githubusercontent.com/1219731/36445421-28b5bcee-1676-11e8-90e3-fd6f7c3c7007.png">

**Comment by tagliala** [comment]
@stoem that looks like another request: #2883

I just want to point out that Facebook is moving away from that direction:

(at the first [they put the woman ahead the man](https://medium.com/facebook-design/how-we-changed-the-facebook-friends-icon-dc8526ea9ea8), now they are [genderless silhouettes](https://user-images.githubusercontent.com/556268/36446348-548a8e98-1681-11e8-8dee-7788dd4fdead.png))

**Comment by stoem** [comment]
Yes the friend icon looks similar, it would work for us.
Our specific requirement is for an icon that represents parents though as we deal with children and their associated guardians in our app. 

Any one of those friends icons would do the job for our use case but the fontawesome users icon is not ideal.

**Comment by redmaneAbe** [comment]
+1 for parent-child icon

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/family?f=classic&s=solid)
