### ISSUE TITLE
Some brand icons do not display in Firefox 26.0

### ISSUE THREAD

**Issue by mrzor** [FortAwesome/Font-Awesome#2705]
Hello!

I'm running Firefox 26.0, this is what I see in the Icons>Brand part of FA's website:

![screenshot from 2014-01-07 23 39 30](https://f.cloud.github.com/assets/54230/1864085/ef0c584e-77ec-11e3-9282-e905833bcce8.png)

The icons fa-twitter fa-youtube fa-facebook and fa-google-plus-square do not display.
I couldn't get them to display on my end, which led me to discover they were not displaying on the website :v:

**Comment by sameerkdarshi** [comment]
use latest version of font awesome.
and use fab for brand (eg:- fab fa-facebook)
and for others fa/fas.
