### ISSUE TITLE
Icon Request: fa-yammer

### ISSUE THREAD

**Issue by bvizureanu** [FortAwesome/Font-Awesome#2707]
Hello,
I would like to suggest the Yammer logo for the brand icons suite.

Here is an example:
![yammer_lrg 1](https://f.cloud.github.com/assets/3786565/1870132/69e321f6-7883-11e3-97a1-b176aa01c8d9.png)

It can also be observed on their website: www.yammer.com :)

Thanks a lot,
Bogdan

**Comment by hobe** [comment]
Here is a PNG:
![yammer](https://cloud.githubusercontent.com/assets/1303889/5610148/e0ae58b4-94b1-11e4-8948-0bf064042d5c.png)

THE SVG can be found here: http://1drv.ms/1vQXb0B

**Comment by martinkearn** [comment]
+1

**Comment by camswords** [comment]
+1

**Comment by aybezz** [comment]
+1

**Comment by griffithmatt** [comment]
+1

**Comment by ChristianMoser** [comment]
+1

**Comment by WiredNC** [comment]
+1

**Comment by marcosavila** [comment]
+1

**Comment by tstarkie** [comment]
+1

**Comment by eshwaric** [comment]
+1

**Comment by ojako** [comment]
+1

**Comment by flyapen** [comment]
+1

**Comment by sevenaces** [comment]
+1

**Comment by pksingh099** [comment]
+1

**Comment by shashank-accesspay** [comment]
+1

**Comment by tommitchell** [comment]
+1 :)

**Comment by dustinmoris** [comment]
+1!

**Comment by johnaau** [comment]
+1

**Comment by filipesf** [comment]
+1

**Comment by ncoquelet** [comment]
Good news,
Microsoft already offers all office 365 icons :-)

http://lab.n8d.at/o365glyph/

**Comment by ncoquelet** [comment]
In my excitement, I don't realized that cdn link are broken !
Instead, you can find them on the office portal , but the url can be broken another time

https://portal.office.com/16.00.0975.010/css/Fabric/0.10.3/fonts/office365icons.eot
https://portal.office.com/16.00.0975.010/css/Fabric/0.10.3/fonts/office365icons.svg
https://portal.office.com/16.00.0975.010/css/Fabric/0.10.3/fonts/office365icons.ttf
https://portal.office.com/16.00.0975.010/css/Fabric/0.10.3/fonts/office365icons.woff

Or take them on one of the OfficeDev repo on github
https://github.com/OfficeDev/Excel-Add-in-JavaScript-CommunicationBetweenAddIns/tree/master/CommunicationBetweenAddInsContentWeb/Fonts

And what is the licence ? 
Sorry, I don't know !!

**Comment by selcukermaya** [comment]
+1

**Comment by D4rkTiger** [comment]
+1

**Comment by Carstairs** [comment]
+1

**Comment by janeck** [comment]
+1

**Comment by birdseyedesign** [comment]
+1

**Comment by mantebridts** [comment]
+1

**Comment by KyorCode** [comment]
+1

**Comment by frankdsm** [comment]
+1

**Comment by stefanpante** [comment]
+1

**Comment by elinewouters** [comment]
+1

**Comment by dustinmoris** [comment]
What the hell? Why are so many ppl +1 in the last 15 minutes? Unsubscribing from this issue now because the notifications are annoying... GitHub desperately needs an upvote and this icon needs to be implemented!

**Comment by mhxbe** [comment]
+1

**Comment by Jan-Bart** [comment]
+1

**Comment by PrinceAnsong** [comment]
+1

**Comment by kliptonize** [comment]
+1

**Comment by kwaelkens** [comment]
+1

**Comment by glennverschooren** [comment]
+1

**Comment by JvJefke** [comment]
+1

**Comment by Brentless** [comment]
+1

**Comment by FabianMeul** [comment]
+1

**Comment by Defoil** [comment]
+1

**Comment by amitpuri** [comment]
+1

**Comment by preritmohan** [comment]
+1

**Comment by designbymichael** [comment]
+1

**Comment by designbymichael** [comment]
I work for a state government agency that uses Font Awesome and Yammer is a commonly used "Facebook" for government type website.  I know a number of us would love to see it included in the list of icons in FontAwesome!  Cheers!

**Comment by Jhonesdg** [comment]
+1

**Comment by emzero** [comment]
+1

**Comment by mlamarque** [comment]
+1

**Comment by rliebl** [comment]
+1

**Comment by boyangwm** [comment]
+1

**Comment by NBajanca** [comment]
+1

**Comment by emzero** [comment]
+1

**Comment by ncoquelet** [comment]
I repeat, yammer icon is already available into office 365 official icon font ;)

http://spo365icons.azurewebsites.net/#/
icon \e064

**Comment by Goddak** [comment]
+1 though I note that this has been of interest for over 2 years.. Come on @davegandy @robmadole @supercodepoet @tagliala @talbs how long is it really going to take you to knock this up?

**Comment by TianqiZhang** [comment]
+1

**Comment by bdegraaf** [comment]
+9000

**Comment by benald** [comment]
+1 need this included please

**Comment by Mycosis** [comment]
+1 for the love of god

**Comment by TrionaFredrik** [comment]
+1

**Comment by hamed-farag** [comment]
+1

**Comment by Sylvain-Kraisin** [comment]
+1

**Comment by netpraxis** [comment]
+1

**Comment by rraulg5** [comment]
+1

**Comment by TianqiZhang** [comment]
+1

**Comment by Vikestart** [comment]
+1

**Comment by n3xus** [comment]
+1

**Comment by pachumon** [comment]
+1

**Comment by Goddak** [comment]
4 years and nothing.. Wow

**Comment by sparkitect** [comment]
Maybe they're having trouble getting permission and/or distinguishing it from other "Y" icons.

But nevertheless:
+1

**Comment by eparizzi** [comment]
+1

**Comment by talbs** [comment]
Here you go, gang. We added this icon as part of version `5.8.0` - https://fontawesome.com/icons/yammer
Thanks for the patience and for continuing to vote this up! :smile:

**Comment by Goddak** [comment]
WOW!!!! @talbs  - About time TY

**Comment by Goddak** [comment]
@talbs - So you know how we gave you loads of abuse about getting this added.. Well not long after the Yammer logo was updated.. Is it likely to be another 5 year wait for the update? :stuck_out_tongue: 

**No dig intended here;** If so I'll sort another solution now.  Asking because a customer has asked me and given me abuse about how slow I was on the uptake :D

**Comment by tagliala** [comment]
@Goddak we are tracking the update request here: #16111
