### ISSUE TITLE
IE8 IFrame Reload Icons Disappear

### ISSUE THREAD

**Issue by sebascomeau** [FortAwesome/Font-Awesome#2717]
I'm using Font-Awesome for my project and it's awesome. But I recently got an issue with iframes. When I trigger an iframe reload in my application, suddenly all icons disappear. It's only happening in IE8.

Can someone help me to fix this?

Check out my screenshots below...

![1](https://f.cloud.github.com/assets/2814465/1879178/ef62797c-7945-11e3-80d0-7df00e4aafc3.png)
![2](https://f.cloud.github.com/assets/2814465/1879179/ef6670ea-7945-11e3-8340-a188d41fa1ec.png)
![3](https://f.cloud.github.com/assets/2814465/1879180/ef670690-7945-11e3-9213-4ae99a6f93ef.png)

**Comment by tagliala** [comment]
Unfortunately we weren't able to fix this random issues with IE8

I'm going to close here because IE8 is not supported by FA6
