### ISSUE TITLE
Icon Request: wordpress post format icons

### ISSUE THREAD

**Issue by Markicc** [FortAwesome/Font-Awesome#2720]
Hi,

first of all, thank you a lot. As a wordpress theme developer, using your icons to make retirna ready themes has never been easier!

Now, wordpress has this functionality called "post formats" (not to be mistaken with "custom post types"). It basically allows users to declare the nature of a post. There are ten different formats: aside, audio, chat, image, gallery, link, quote, status, video and standard. Now, some of the existing icons from your set are simmilar to official wordpress icons (image, audio, chat, quote, link...), but some of them lack similarity (mostly: gallery and aside).

Here are some examples of what am I talking about.
Wordpress has some official flat icons => http://make.wordpress.org/core/files/2013/10/Screen-Shot-2013-10-22-at-8.44.38-PM.png
There are free (for comercial use too) icons to be downloaded => http://www.elmastudio.de/webdesign/freebies/freebie-icon-set-post-formats-icons-fur-wordpress-und-tumblr-blogs/
And this is a really nice (althought licenced) for gallery => https://cdn3.iconfinder.com/data/icons/objects/512/gallery_2-128.png

Wordpress community would be greatful if you could incorporate them (or at least gallery and aside) into you icon set...

And one more thing, one of the most common icons used is a lightbulb (represents ideas). There are several .svg files that can be incorporated easily and, if my understanding is right, are lacking protection (licence) so can be used as a font

This one from clibartsfree.com
http://www.clipartsfree.net/svg/365-light-bulb-minimal-design--vector.html

...and this one from wikipedia
http://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Light_Bulb-Silhouette.svg/200px-Light_Bulb-Silhouette.svg.png

Thanks...

**Comment by abdfahim** [comment]
+1

**Comment by tagliala** [comment]
Closing here because this request does not meet our contributing guidelines anymore:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

gallery: #855
