### ISSUE TITLE
Icon request: icon-fish

### ISSUE THREAD

**Issue by ethanpil** [FortAwesome/Font-Awesome#2722]
Would love icons in places we need to represent common pets or animals, I would this is useful

```
fa-fish
```

**Comment by thekondrashov** [comment]
+1

**Comment by rcrisp** [comment]
+1 for fish icons

**Comment by zacchaeusn7** [comment]
+1

**Comment by sbatschelet** [comment]
+1

**Comment by joris-** [comment]
+ 1

**Comment by MrLockertsen** [comment]
+1

**Comment by ggmacasaet** [comment]
fish please

**Comment by mickmorbitzer** [comment]
+1

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone via #1895 

Note that this could be shifted to a future release

**Comment by G-Driver** [comment]
+1

**Comment by ndeverge** [comment]
+1

Today (April the 1st) would be the perfect day to have a fish.

**Comment by mikaoras** [comment]
+1

**Comment by mikaoras** [comment]
really need a fish

**Comment by ander48** [comment]
+1

**Comment by phili76** [comment]
+1

**Comment by edgolo** [comment]
+1

**Comment by latiosthinh** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by gdoron** [comment]
+1

**Comment by AncientSwordRage** [comment]
:+1:  I could make use of this!

**Comment by newburns** [comment]
+1

**Comment by joris-** [comment]
+1

**Comment by cenan** [comment]
+1

**Comment by channaaah** [comment]
+1

**Comment by millerthegorilla** [comment]
+1

**Comment by ChrisNaylor** [comment]
+1

**Comment by Ry04Mac** [comment]
+1

**Comment by KajoMan** [comment]
+1

**Comment by daltonhance** [comment]
+1, so I can eat for a day

**Comment by raykai** [comment]
+1

**Comment by chopj** [comment]
+1

**Comment by samueljmello** [comment]
+1

**Comment by myrmithron** [comment]
+1 (and aquarium icon if possible) :)

**Comment by mardojai** [comment]
+1

**Comment by dpfem** [comment]
+1 for a fish icon

**Comment by emajen** [comment]
How can I + this?

**Comment by tagliala** [comment]
@emajen by reacting with a 👍  to the first post.

**Comment by johnnyshields** [comment]
Fish is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by emajen** [comment]
This is awesome!!! Thanks!

**Comment by Crissov** [comment]
JFTR, these are the related Unicode 9.0 emojis (fish, seafood, pisces …):

* 🐟 U+1F41F
* 🐠 U+1F420
* 🐡 U+1F421
* 🎣 U+1F3A3
* 🍣 U+1F363
* 🍥 U+1F365
* 🍢 U+1F362
* 🍤 U+1F364
* 🦐U+1F990
* 🦑 U+1F991
* 🐙 U+1F419
* 🦀 U+1F980
* 🐚 U+1F41A
* 🐬 U+1F42C
* 🐳 U+1F433
* 🐋 U+1F40B
* 🎏 U+1F38F
* ♓️ U+2653

**Comment by CarpCharacin** [comment]
Will there be an FA Fish icon?

**Comment by JoeEarly** [comment]
bring the fish!!!

**Comment by ssm1985** [comment]
+1 for the fish

**Comment by eugeniocarmo** [comment]
We need a fish! Please. Simple lines

**Comment by adamaki** [comment]
I work at the Institute of Aquaculture. Font Awesome is no use to me without a fish icon! Please add one!

**Comment by emajen** [comment]
Going on four years since requested. :(

**Comment by adamaki** [comment]
Looks like Font Awesome is not as awesome as it pretends to be...

**Comment by spanglishwebs** [comment]
+1

**Comment by akinbosnak** [comment]
+1

**Comment by Cube42** [comment]
+1

**Comment by Jonibigoud** [comment]
+1

**Comment by YannickNascimento** [comment]
+1

**Comment by maciz84** [comment]
+1

**Comment by chrisGeonet** [comment]
+1

**Comment by earthcomedy** [comment]
+1

**Comment by Wingo5315** [comment]
+1 Could add some more real-world icons!

**Comment by Wingo5315** [comment]
Just checked the FA leaderboard, and this icon is currently "In Progress". Hoorah!

**Comment by pacoweb** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/fish?style=solid
