### ISSUE TITLE
Icon Request: fa-java

### ISSUE THREAD

**Issue by RichardAlan** [FortAwesome/Font-Awesome#2726]
Would love to have available an icon for the Java languge. Something similar to the one here:

https://weblogs.java.net/blog/kcpeppe/archive/2013/12/11/case-study-jvm-hotspot-flags

or 

http://www.oracle.com/us/technologies/java/overview/index.html

**Comment by admix** [comment]
+1

**Comment by TheChen5** [comment]
Dupe of #386 
:mag:before:heavy_plus_sign:
@tagliala this should be closed

**Comment by tagliala** [comment]
closing here as a duplicate of #386

**Comment by rodrigorrch** [comment]
+1
