### ISSUE TITLE
Allow copy icons from the permalink

### ISSUE THREAD

**Issue by oscarotero** [FortAwesome/Font-Awesome#2736]
In the permalink page of each icon (for example: http://fontawesome.io/icon/info-circle/) there is not the possibility to copy the icon character like in the cheatsheet (http://fontawesome.io/cheatsheet/). It would great to have this possibility and also display the unicode html (not only the unicode code 'f05a').

**Comment by rentalhost** [comment]
Please, give attention to this issue.
It's simple to solve and will help a lot!

**Comment by sensibleworld** [comment]
Closing this issue as it relates to an old version of Font Awesome. Let us know with a new issue if you're still experiencing issues. Thanks!
