### ISSUE TITLE
Use Autoprefixer

### ISSUE THREAD

**Issue by ai** [FortAwesome/Font-Awesome#2738]
Font Awesome CSS contains a lot of outdated prefixes. [Autoprefixer](https://github.com/ai/autoprefixer) can clean it.

**Comment by realityking** [comment]
I'd like to take a shot at this. Unfortunately I couldn't figure out where the CSS is generated from the less or sass. Any pointers?

**Comment by tagliala** [comment]
@realityking the build process is something horrible. Here it is: https://github.com/FortAwesome/Font-Awesome/blob/master/src/Makefile

I'm absolutely pro autoprefixer + grunt/gulp based build process #1166 for 5.0.0 but this decision is up to Dave

**Comment by realityking** [comment]
No worries, I can work with that.

**Comment by tagliala** [comment]
Autoprefixer has been finally introduced in FA6's build system, so we expect the new `scss` files to be free of outdated prefixes

**Comment by tagliala** [comment]
FA6 uses autoprefixer to generate css files
