### ISSUE TITLE
update fa-wheelchair to modern version

### ISSUE THREAD

**Issue by ericscheid** [FortAwesome/Font-Awesome#2746]
The current fa-wheelchair icon is the traditional ADA/ISO standard icon, but there is a strong movement afoot (no pun intended) to update the icon to better respect wheelchair users.

![image](https://f.cloud.github.com/assets/2605467/1921739/ab341384-7dfd-11e3-9f42-c5c0ca42a3ec.png)

Read about it here:
http://www.accessibleicon.org/icon.html

**Comment by kegill** [comment]
+1

**Comment by lowercasej** [comment]
+1

**Comment by sthomas1618** [comment]
+1

**Comment by rstrazz** [comment]
+1

**Comment by npriddy** [comment]
+1

**Comment by adamgilzean** [comment]
+1

**Comment by vholcomb78** [comment]
+1

**Comment by plantice** [comment]
+1

**Comment by ferrispc** [comment]
+1

**Comment by apagura** [comment]
+1

**Comment by madmadmak** [comment]
+1

**Comment by hoovenej** [comment]
+1

**Comment by mille704** [comment]
+1

**Comment by KevKoz** [comment]
+1

**Comment by caduvieira** [comment]
+1

**Comment by kangarolf** [comment]
+1

**Comment by TerraceMedia** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by davegandy** [comment]
Adding to 4.5.1 milestone. Going to start hitting these harder.

**Comment by davegandy** [comment]
Added to 4.6.0-wip branch. Closing.

**Comment by chbevers** [comment]
+1

**Comment by chbevers** [comment]
It was added to work in progress branch but it's 3 years later. Where's the icon??

**Comment by ferrispc** [comment]
I believe the icon got released in one of the recent versions. Check it out here. https://fontawesome.com/icons/accessible-icon?style=brands

**Comment by chbevers** [comment]
Yes! Thank you!!
   On Tuesday, March 5, 2019, 1:24:15 PM EST, ferrispc <notifications@github.com> wrote: 
 
 
I believe the icon got released in one of the recent versions. Check it out here. https://fontawesome.com/icons/accessible-icon?style=brands
