### ISSUE TITLE
Icon request: projector (beamer)

### ISSUE THREAD

**Issue by lgoudriaan** [FortAwesome/Font-Awesome#2748]
I would like to see a beamer icon so i can use it on my site.

http://findicons.com/files/icons/770/token_dark/128/projector.png

Thanks in advance!

**Comment by fszeliga** [comment]
+1 for beamer/projector! Thanks!

**Comment by fhoess** [comment]
me too

**Comment by matthiku** [comment]
+1

**Comment by elvenpath** [comment]
+1

**Comment by pushamaku** [comment]
+1

**Comment by lomcarlo** [comment]
me too

**Comment by mcules** [comment]
+1

**Comment by Ethiarpus** [comment]
+1

**Comment by bhubbard** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in both version 5 and version 6. https://fontawesome.com/v6.0/icons/projector?s=solid

<img width="1013" alt="Screen Shot 2021-05-27 at 2 03 08 PM" src="https://user-images.githubusercontent.com/529604/119875005-45f65000-bef4-11eb-8045-6c1e3548828a.png">
