### ISSUE TITLE
Icon Request: icon-applause

### ISSUE THREAD

**Issue by iurikothe** [FortAwesome/Font-Awesome#2749]
Google image example: https://www.google.com/search?q=applause&tbm=isch&tbs=isz:i,ic:gray

Usage:
- As a social button, similar to Like, but in a more intense way. To applause an idea, etc
- As a voting button
- As a recognition... people can congratulate someone by applauding

**Comment by dehbmarques** [comment]
:+1:

**Comment by vlaabra** [comment]
+1

**Comment by serghei-topor** [comment]
+1

**Comment by climentjoan** [comment]
+1

**Comment by aethior** [comment]
Hi @iurikothe,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/hands-clapping.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks
