### ISSUE TITLE
Icon request: directory-tree (folder-tree)

### ISSUE THREAD

**Issue by ckarsan** [FortAwesome/Font-Awesome#2752]
Simple directory tree type icon

Would be generally used for file opening system or other folder/filing systems

Thanks!

![tree-icon](https://f.cloud.github.com/assets/5065485/1940332/7efa1164-7f75-11e3-927d-e3e9b39b3962.jpg)

**Comment by Jemt** [comment]
+1, I too is in great need of icons related to Tree View components.
We have expand/collapse icons, but also need the lines that connect nodes in a tree.
 - Thank you! :)

**Comment by vlipman** [comment]
Would love to have a generic tree view icon (not folders) - something like 
![image](https://cloud.githubusercontent.com/assets/11448869/6630146/dc8f6110-c8d2-11e4-88d8-46cd67e3206f.png)

**Comment by SylvainCorlay** [comment]
+1

**Comment by rayrigam** [comment]
+1

**Comment by thibaultdelor** [comment]
+1

**Comment by DanielGasperoni** [comment]
+1

**Comment by thiazzz** [comment]
+1

**Comment by rdeslonde** [comment]
+1

**Comment by Asparagirl** [comment]
+1

**Comment by namtab00** [comment]
+1

**Comment by vira-lytvyn** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by jemartin80** [comment]
+1

**Comment by genu** [comment]
+1

**Comment by genu** [comment]
Whats been holding this up for 2 years? Is a PR needed?

**Comment by tagliala** [comment]
@genu please consider a custom build, we are not accepting PR including icons

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests

**Comment by stetod11** [comment]
+1

vlipman's idea of generic nodes is a good sone - that way it can represent other relationships, more than just files and folders

**Comment by sklintw** [comment]
+1

**Comment by nate99pitt** [comment]
+1

**Comment by victorbucutea** [comment]
+1

**Comment by klein0r** [comment]
+1

**Comment by sporty** [comment]
+1

**Comment by ShunSakurai** [comment]
+1

**Comment by tatsujb** [comment]
+1 How long is this gonna take?

**Comment by lazaa** [comment]
+1

**Comment by loicsalou** [comment]
+1

**Comment by mshabaan** [comment]
+1

**Comment by hauva007** [comment]
+1

**Comment by renziito** [comment]
+1

**Comment by sirbris** [comment]
+1

**Comment by sroemerJanitza** [comment]
+1

**Comment by leoc** [comment]
+1

**Comment by mikecargal** [comment]
+1

**Comment by dudedigital** [comment]
+1

**Comment by Gizmo091** [comment]
+1

**Comment by mrclrchtr** [comment]
+1

**Comment by krishnadasarin** [comment]
+1
More than 4 years,  still request is in queue..?
if the request not accepted, at-least it should be declined.

**Comment by danny-36** [comment]
+1

**Comment by morph3us-net** [comment]
I derived an icon from the [sitemap](https://fontawesome.com/icons/sitemap?style=solid).
![treeview-solid](https://user-images.githubusercontent.com/43741267/108596296-5c848c80-7384-11eb-9986-9b3897a8997e.jpg)

I'd be happy to share it for a free version!
[treeview-solid.zip](https://github.com/FortAwesome/Font-Awesome/files/6015011/treeview-solid.zip)
