### ISSUE TITLE
Icon Request: fa-mixcloud

### ISSUE THREAD

**Issue by discussor** [FortAwesome/Font-Awesome#2753]
Mixcloud Icon
Usage case: to be used as an icon of a social link for following on Mixcloud website (mixcloud dot com)
Icon could be represented as a cloud with two half-round lines on the right side as shown on the attached icon
![60x60_glossy_w b](https://f.cloud.github.com/assets/6436197/1946799/f5bf083a-8025-11e3-9c5b-829634466430.jpg)

**Comment by idleberg** [comment]
+1

**Comment by picklesau** [comment]
+1

**Comment by zlatko-micic** [comment]
Version 4.3.0 is here. I can't believe that mixcloud icon isn't included.

**Comment by foxx** [comment]
@zlatko-micic I've come to the conclusion that the maintainers are either not very good at open source community interaction, or they don't care lol. Either way, someone should fork and maintain.

**Comment by tagliala** [comment]
"open source community interaction" means that Dave **must** implement this icon as well as all other 2180+ requested icons?

Fontawesome may simply not work for someone, but there are a lot of other options out there and everyone is free to customize the fontawesome core.

Take a look at these awesome online services:
https://fonticons.com/ (by Dave)
http://fontello.com/
http://icomoon.io/app/#/select (My personal favorite)
http://fontastic.me/

Of course forking the repo and hacking with the .otf is another option and it would be useful to many people. Feel free to share the forked repo here (eg: https://github.com/FortAwesome/Font-Awesome/issues/1504#issuecomment-70463452)

**Comment by foxx** [comment]
""open source community interaction" means that Dave must implement this icon as well as all other 2180+ requested icons?". Nope, but some feedback on an issue that's been outstanding for 1 year wouldn't be unreasonable.

**Comment by zlatko-micic** [comment]
Actually that was not bad idea at all!
I've created mixcloud logo in vectors by tracing an image in Adobe Illustrator
exported vectors as SVG file
downloaded and installed BirdFont http://birdfont.org/
edited FontAwesome.otf
added mixcloud.svg
and there I have it! Mixcloud logo under &#xf23b;

Funny thing is that I'm doing this for the first time and it took me less than one hour.
Sorry guys, I would love to put it online but it's copyrighted.

**Comment by zlatko-micic** [comment]
If anyone wants SVG file, here it is
https://mega.co.nz/#!cQJFkJgK!jkD6mKnEqJKyLnY_O-ItPCZWR1GudnENlgywoU42P0Y

**Comment by aleksandar-todorovic** [comment]
+1

We definitely need this one.

**Comment by picklesau** [comment]
I just used the generic cloud icon for the time being because time constraints.

**Comment by aleksandar-todorovic** [comment]
I'm also using generic cloud icon for now, but they're quite a lot different.

**Comment by gioslv** [comment]
Hi guys,

why can't I find this icon at http://fortawesome.github.io/Font-Awesome/icons/ ?

Thanks!

**Comment by aleksandar-todorovic** [comment]
@gioslv Because it is still not a part of the pack. This issue is a proposal to add this icon to the Font Awesome pack.

**Comment by kabren** [comment]
+1

**Comment by sea-wave** [comment]
Contributors - How can we help you to help us by including this icon in the library?

**Comment by G-Driver** [comment]
+1 for mixcloud

**Comment by kvisionphoto** [comment]
+1 mixcloud !! please!!

**Comment by rex** [comment]
At this point it's just pissing into the ocean but I'll throw my +1 in :) :arrow_up:

**Comment by flycoop** [comment]
+1

**Comment by jlad00** [comment]
+1

**Comment by antuanantuan** [comment]
Hi,
I make a provisional solution to use mixcloud icon.
I created a mixcloud logo as svg format (black and white). You can find it here:
Black: https://dl.dropboxusercontent.com/u/32321147/mixcloud-logo-black.svg
White: https://dl.dropboxusercontent.com/u/32321147/mixcloud-logo-white.svg

1. Take it and upload it to your host.  
2. Create a class code before </head> in your website. For example I used this:

.mixcloud-icon{
	width:40px;
	height:22px;
}

3. And then, add this line where you need to place the icon:
<a class='mixcloud-icon' style='background: url(https://yourwebsite/mixcloud-logo-white.svg); background-size:100%; background-repeat: no-repeat;' href='#'/>

It works, at least for me! 
Sorry, I'm not coder, I'm designer. If you believe you can improve the code, go ahead!

**Comment by djntact** [comment]
+1

**Comment by jackincaves** [comment]
+1

**Comment by CraigPearson** [comment]
+1

**Comment by ordinaryAmsel** [comment]
+1

**Comment by GGFM** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by ChewyJetpack** [comment]
+1

**Comment by kricore** [comment]
+1

**Comment by WileC** [comment]
+1

**Comment by danielbreves** [comment]
+1

**Comment by kittikun** [comment]
+1

**Comment by TheMicronaut** [comment]
+1

**Comment by cauerego** [comment]
Probably best thing to do is simply move to a better suited service: http://stackoverflow.com/questions/11426172/add-custom-icons-to-font-awesome

**Comment by slavibg** [comment]
There are almost no music related icons. I've been looking for a pack of icons for soundcloud, mixcloud, beatport etc. It would be really nice if at least this mixcloud one is added.

+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by ChewyJetpack** [comment]
Amazing! Thanks

**Comment by rex** [comment]
@davegandy You. Are. Fantastic. Thank you so much for this! I'm going to paint this town red with Mixcloud icons.
