### ISSUE TITLE
icon request: e-commerce add/remove to/from basket

### ISSUE THREAD

**Issue by martinkearn** [FortAwesome/Font-Awesome#2759]
Icons that signify adding or removing an item from a shopping cart/basket in an eCommerce scenario.

**Comment by ronklaren** [comment]
+1

**Comment by thethomic** [comment]
+1

**Comment by aethior** [comment]
Hi @martinkearn,

Can we consider this issue solved with [fa-cart-plus](https://fontawesome.com/icons/cart-plus) and [fa-cart-minus](https://fontawesome.com/icons/cart-minus) icons?

cc/ @tagliala
