### ISSUE TITLE
Icon request: icon-balance-scale (justice scale)

### ISSUE THREAD

**Issue by tomciopp** [FortAwesome/Font-Awesome#276]
Justice scales, or a heavy weight.

**Comment by dangnelson** [comment]
+1 scales, would use to represent comparison

**Comment by happyloha** [comment]
+1 for justice scales

**Comment by silbar** [comment]
+1 
![imbalanced](https://cloud.githubusercontent.com/assets/10809394/5999658/436bf10e-aad4-11e4-820e-5fcf7d940335.png)

**Comment by djacobs9** [comment]
+1 for justice scales

**Comment by metmajer** [comment]
+1

**Comment by haferje** [comment]
+1

**Comment by mplh** [comment]
+1

**Comment by vol7ron** [comment]
What about a venn-diagram for compare-and-contrast?

**Comment by G-Driver** [comment]
+1

**Comment by aceunreal** [comment]
+1

**Comment by Davletvm** [comment]
+1

**Comment by smartcorestudio** [comment]
+1 for "compare"

**Comment by manicko** [comment]
+1
![dcromakc9](https://cloud.githubusercontent.com/assets/1097057/6998338/0e982be8-dbe7-11e4-80e7-7ae50da9b3ae.jpeg)

this one more stylish

**Comment by juvoni** [comment]
+1

**Comment by keeperhood** [comment]
+1

**Comment by alexbreems** [comment]
+1

**Comment by BironDesbois** [comment]
+1

**Comment by cluny85** [comment]
+1 Thanks!!

**Comment by orbitalthread** [comment]
+1

**Comment by gate8team** [comment]
+!

**Comment by khaschuluu** [comment]
+1

**Comment by ksleyko** [comment]
+1

**Comment by THPubs** [comment]
+1

**Comment by danielpg** [comment]
+1

**Comment by ymoreiratiti** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issue-26544835

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-46815913

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-51830605

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-63707337

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-66230030

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-69165234

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-70053158

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-70364813

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-71930410

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-72995542

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-75331884

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-102802383

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-108003686

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2818#issuecomment-108134323

**Comment by d3ancole1995** [comment]
+1 Please add!

**Comment by andyblount** [comment]
+1

**Comment by nabeelk** [comment]
+1 Add please

**Comment by tomespo** [comment]
+1

**Comment by arzavj** [comment]
+1

**Comment by hayseed** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.

**Comment by jrmessias** [comment]
Thanks

**Comment by SurajShukla** [comment]
Do we have the icon for judgment added?

If not +1.

**Comment by pwcueblocks** [comment]
+1

**Comment by Sander-Toonen** [comment]
This has been implemented. See: http://fortawesome.github.io/Font-Awesome/icon/balance-scale/
