### ISSUE TITLE
Icon Request: fetlife

### ISSUE THREAD

**Issue by ropeartistry** [FortAwesome/Font-Awesome#2761]
![fetlifelogo](https://f.cloud.github.com/assets/6445935/1950908/18f6954e-8160-11e3-8445-3cd8c12fd840.jpg)

Even just the letters are fine! This site is a social networking site which I (and thousands of others) use, and it would be great to add it to my new HTML5 site. I have it on my flash site, but want to move forward.

**Comment by MKTGExperts** [comment]
The heard with horns is a better option. [https://github.com/FortAwesome/Font-Awesome/issues/4410](url)

**Comment by tagliala** [comment]
Closing here in favor of #2761
