### ISSUE TITLE
Chrome Stable: Icons + Fonts randomly unload

### ISSUE THREAD

**Issue by jfroom** [FortAwesome/Font-Awesome#2763]
FYI, I've logged this issue with Chrome team. Replicating here for anyone else noticing it.
https://code.google.com/p/chromium/issues/detail?id=336075

![00000132](https://f.cloud.github.com/assets/943108/1951021/93632818-8167-11e3-9324-bcd2782442c2.png)

Example URL:
http://fontawesome.io/icons/

Steps to reproduce the problem:
1. load site
2. leave site open in a tab, continue surfing during your day
3. occasionally come back to fontawesome tab to inspect

What is the expected behavior?
Fonts and icons remain rendered properly if tab is left open all day.

What went wrong?
Dynamic fonts occasionally are unloaded, and basic fonts are rendering instead. Any font icons are replaced with square. I've also seen that only _some_ font icons are replaced with squares, not all of them.

Also happens here on my site with google fonts and font awesome
http://jfroom.com/blog/cycling-to-brew-in-chicago/

Will be testing with Canary to try and reproduce, but hard to replicate. Will report back if I notice it.

See screen grab of stable chrome exhibiting issue.

Does it occur on multiple sites: Yes

Is it a problem with a plugin? N/A 

Did this work before? Yes i noticed this over the past week...to best of my knowledge

Does this work in other browsers? N/A 

Chrome version: 32.0.1700.77  Channel: stable
OS Version: OS X 10.9.1
Flash Version: Shockwave Flash 12.0 r0

If this is a known issue that has been resolved with a canary build and will make it into stable build, super. I just wanted to log this because I couldn't find a similar issue logged. Thanks.

**Comment by 304NotModified** [comment]
FYI: We are still seeing this issue (yes it's not FA issue). I think it's a memory issue in Chrome/Webkit. This happens randomly and can't be reproduced by us.

**Comment by tagliala** [comment]
please report to chromium issue tracker
