### ISSUE TITLE
icon request: application control icons

### ISSUE THREAD

**Issue by simoami** [FortAwesome/Font-Awesome#2764]
It would be a good idea to expand your selection to an important category "Application Control"

The following icons are often needed for web applications:

Window control icons
- Maximize
- Minimize
- Restore

![screen shot 2014-01-19 at 2 05 47 pm](https://f.cloud.github.com/assets/2038264/1950247/ce4556a2-813c-11e3-8977-1ccbb407e2bf.png)
![screen shot 2014-01-19 at 2 06 00 pm](https://f.cloud.github.com/assets/2038264/1950248/ce470bdc-813c-11e3-9c7c-4707e6a22215.png)
another variation from ExtJs window tool icons:
![icons](http://docs.sencha.com/extjs/4.2.1/extjs-build/resources/ext-theme-gray/images/tools/tool-sprites.gif)
- Expand/Collapse tree
  ![tree](http://p.yusukekamiyamane.com/icons/search/fugue/icons/blue-document-tree.png)
  ![screen shot 2014-01-19 at 8 52 31 pm](https://f.cloud.github.com/assets/2038264/1951266/a64c87fe-8175-11e3-814a-9cd9f1aa4b2d.png)
- expand collapse side-bar 
  ![sidebar](http://p.yusukekamiyamane.com/icons/search/fugue/icons/layout-2.png)

![screen shot 2014-01-19 at 2 12 23 pm](https://f.cloud.github.com/assets/2038264/1950259/b4cc6174-813d-11e3-8ac4-44242c67aadb.png)

**Comment by sanqianpiao** [comment]
+1
