### ISSUE TITLE
Who use Joomla 3.2 the latest

### ISSUE THREAD

**Issue by alexonbalangue** [FortAwesome/Font-Awesome#2771]
![views](https://f.cloud.github.com/assets/6099946/1961655/d0a698e8-8277-11e3-8ac8-d24c487f4476.JPG)

Hi i creat the plugin for user (you) use easier with joomla without competence developper html/css require.

See, Download, Activate, config if you want and adding the source code in your content article.

http://cms.lxw.fr/joomla/68-plg_fontawesome?showall=1&limitstart= (100% Free)
Our docs also available on http://docs.lxw.fr/our-project/bbcodes/font-awesome?showall=1&limitstart=

Thanks to contribute and advance your project for more icons.

**Comment by tagliala** [comment]
Thanks for sharing.

Closing here
