### ISSUE TITLE
Icon Request: Vertical Alignment Icons

### ISSUE THREAD

**Issue by Siyfion** [FortAwesome/Font-Awesome#2772]
Currently we have icons for left, centred, right and justified text alignment. It would be nice to also include three vertical alignment icons, similar to these:

![screen shot 2014-01-21 at 15 56 47](https://f.cloud.github.com/assets/338488/1965009/0272a906-82b5-11e3-9fc3-19fbc940ae44.png)

**Comment by tarzak** [comment]
+1
[Top](https://cdn0.iconfinder.com/data/icons/fatcow/32x32/align_above.png), [middle](https://cdn0.iconfinder.com/data/icons/fatcow/32/align_middle.png), [bottom](https://cdn0.iconfinder.com/data/icons/fatcow/32/align_bellow.png).

**Comment by steveostudios** [comment]
I was super surprised to see that this set wasn't included already! Please add when you you get time!

**Comment by Dxg125** [comment]
Just a Suggestion: Maybe we could use the same Icons like Word, Excel etc. uses. Cause the Enduser know these icons. 

Also it would be great, if you could add them to the Collection of Icons.

Greetings

**Comment by sensibleworld** [comment]
We have a batch of `object-align-` icons in version 6 that could work for this. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=objects-align&s=solid

<img width="1043" alt="Screen Shot 2021-05-27 at 2 01 12 PM" src="https://user-images.githubusercontent.com/529604/119874793-00d21e00-bef4-11eb-819a-4d1dc325a737.png">
