### ISSUE TITLE
Icon request: fa-trophy-o

### ISSUE THREAD

**Issue by gitman12** [FortAwesome/Font-Awesome#2778]
Hi @all,

I need the trophy icon in white-coloured for using on a dark background.
Is this possible?

Thanks in anticipation for support and integrating this icon in font-awesome.

Regards,
Jay

**Comment by AdrienTorris** [comment]
+1

**Comment by tagliala** [comment]
Hi, I'm sorting out some old requests 😅  

This icon is available in FA5 Pro:
- https://fontawesome.com/icons/trophy?style=regular
- https://fontawesome.com/icons/trophy-alt?style=regular

**Comment by AdrienTorris** [comment]
Oh great! Thanks 👍
