### ISSUE TITLE
Icon request: icon-reward / icon-chest

### ISSUE THREAD

**Issue by Miosso** [FortAwesome/Font-Awesome#2787]
I was thinking in something like ... 
"&lt;i class="fa fa-reward"&gt;&lt;/i&gt;Good job, you just got a new functionality!".

We could use this on a notification bar, too.

The image
![chest-lost-shores](https://f.cloud.github.com/assets/4322000/1995299/452e3018-8502-11e3-91e6-45d2a12ee518.png).

If you search "guild wars 2 reward chest" you will get lot more examples.

Thank you!

**Comment by tagliala** [comment]
Closing here in favour of #6319
