### ISSUE TITLE
Icon request: bootprint

### ISSUE THREAD

**Issue by jrmjeff** [FortAwesome/Font-Awesome#2788]
Hi there,

I would like to request an icon representing a boot print.  This would be used to distinguish taking steps or moving forward on something.  It could be used in outdoors or hiking applications as well.

Thanks
![bootprint](https://f.cloud.github.com/assets/6493368/1996599/d6fa6502-8516-11e3-988c-e50b52ed5797.jpg)
![bootprint inuse](https://f.cloud.github.com/assets/6493368/1996600/d6fb04e4-8516-11e3-9055-bdea3f45bd65.jpg)

**Comment by lenamtl** [comment]
+1

**Comment by penpeg** [comment]
+1
and a boot 
![screen shot 2015-02-16 at 19 09 51](https://cloud.githubusercontent.com/assets/11033453/6216986/705f5c50-b60f-11e4-8804-3c4e0f4584e2.png)

**Comment by MECU** [comment]
+1

**Comment by mcfadden** [comment]
:+1:

**Comment by dakur** [comment]
+1

**Comment by aethior** [comment]
Hi @jrmjeff,

`fa-shoe-prints` icon was added in v5.0.13.
Check https://fontawesome.com/icons/shoe-prints

Regards.

cc/ @tagliala
