### ISSUE TITLE
Icon request: icon-comment-squared(-o), icon-comments-squared(-o)

### ISSUE THREAD

**Issue by tekmosis** [FortAwesome/Font-Awesome#2790]
In bootstrap we used to have a squared rounded corner comment icon. The font awesome replacement is more like a speech bubble in a comic rather than a comment. The boostrap one looks more inline with mobile comment styles on iOS/Android, or actual comment styles on sites. The current one looks odd.

**Comment by Debeet** [comment]
:+1: to a squared comment icon

**Comment by steven10172** [comment]
+1

**Comment by MVprobr** [comment]
+1

**Comment by tagliala** [comment]
Comment-squared-o is available for free in version 5: https://fontawesome.com/icons/comments-alt?style=regular

Comments-squared-o is available in FA Pro: https://fontawesome.com/icons/comments-alt?style=regular
