### ISSUE TITLE
Icon Request: Listening, Speaking, Reading, Writing

### ISSUE THREAD

**Issue by bebekar** [FortAwesome/Font-Awesome#2793]
I love your font set. 
We design web application with language learning tools. most of the exercise and they need to be marked with appropriated icons to help identify the activity.
Would love if you could add some for the following 
Reading 
Writing 
Listening 
speaking 
example link: http://www.darrenwhittington.com/oxford-university-press-education-icons-writing-listening-speaking-reading/

**Comment by tagliala** [comment]
Closing here because this icon is missing attachmetns and examples
