### ISSUE TITLE
Icon Request: icon-rank / icon-stats / icon-charts

### ISSUE THREAD

**Issue by mauriblint** [FortAwesome/Font-Awesome#2794]
Three (3) vertical bars of different heights, like fa-bar-chart-o

Congrats for the proyect,
Best Regards!

Mauricio 
@miblint

**Comment by pvljanda** [comment]
+1

**Comment by grssnbchr** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by aethior** [comment]
Hi @mauriblint,

Something like [fa-chart-simple](https://fontawesome.com/icons/chart-simple)?

Regards.

cc/ @tagliala

**Comment by mauriblint** [comment]
> Hi @mauriblint,
> 
> Something like [fa-chart-simple](https://fontawesome.com/icons/chart-simple)?
> 
> Regards.
> 
> cc/ @tagliala

Hi @aethior, yes exactly, but I needed it back in 2014! hehe
