### ISSUE TITLE
Separate icons PNG and SVG build

### ISSUE THREAD

**Issue by Rush** [FortAwesome/Font-Awesome#2795]
I have created a build and a script for building individual SVG and PNG icons at different colors and sizes.

https://github.com/CodeCharmLtd/Font-Awesome-SVG-PNG

Let me know if you want any more credit in my README and if you are getting requests for such thing yourself feel free to link to my repo on your site.

I hope you are OK with such work.

The script works by fetching your svg font file and the `icons.yml` file to extract individual glyphs. Changing paths in your repo would break my generator so I hope they will stay the same. :)

Thanks for making Font-Awesome.

**Comment by tagliala** [comment]
Hi!

I'm squashing some old issues

Font Awesome 5 provides [individual .svg files](https://github.com/FortAwesome/Font-Awesome/tree/master/svgs), so it is easier to convert to png

I'm still referencing your repo to users that need individual .svg from Font Awesome 4

Thanks for the help

Closing here
