### ISSUE TITLE
Icon request: icon-horse

### ISSUE THREAD

**Issue by fertone** [FortAwesome/Font-Awesome#280]
Hey there! Is there a way to get a horse icon in the set? 
Hopefully greets from sweet berlin!

**Comment by mbequine** [comment]
+1

**Comment by somethingworks** [comment]
+1

**Comment by lulango** [comment]
+1

Thank you!

**Comment by timhettler** [comment]
+:horse:

**Comment by tagliala** [comment]
oh ffff

Sorry, but there is a more recent request with more +1s than this one. I will close here. No need to +1 #2049, I will do it by myself
