### ISSUE TITLE
Icon Request: Deezer

### ISSUE THREAD

**Issue by smndhm** [FortAwesome/Font-Awesome#2802]
Logo Illustator files can be download here : http://developers.deezer.com/guidelines/logo

**Comment by omerucel** [comment]
+1

**Comment by gaeld** [comment]
+1

**Comment by hugomn** [comment]
+1

**Comment by WordPresseur** [comment]
+1

**Comment by passkey1510** [comment]
+1

**Comment by KhyamAllami** [comment]
+1

**Comment by sangrita22** [comment]
+1

**Comment by samijnih** [comment]
+1

**Comment by Dennis14e** [comment]
:+1:

**Comment by ChoiZ** [comment]
:+1:

**Comment by nelsonsaldanhaneto** [comment]
+1

**Comment by Toube** [comment]
+1

**Comment by evrenvarol** [comment]
+1 

I had to use `<i class="fa fa-align-left fa-fw fa-rotate-270"></i>` instead as a quick/temporary solution.

**Comment by dvidal49** [comment]
+1
We need Deezer icon please !
It's the second music social network in the world after Spotify;
so it's a very important icon.
Thanks ;)

**Comment by recasanova** [comment]
+1

**Comment by nfu** [comment]
+1

**Comment by fernandocandiani** [comment]
+1

**Comment by julienbornstein** [comment]
+1

**Comment by mydnic** [comment]
:+1:

**Comment by Nyzo** [comment]
+1

**Comment by sanek4life** [comment]
+1 

http://www.deezer.com/ - is very popular service for listen legally music in Europe and World.

This is #2 music service after Spotify.
Deezer available in 180+ countries!!! http://www.deezer.com/company/press

Logo: http://developers.deezer.com/guidelines/logo

https://en.wikipedia.org/wiki/Deezer

**Comment by donostiastudio** [comment]
+1

**Comment by fmarques55** [comment]
+1

**Comment by simondumas** [comment]
+1

**Comment by andtxr** [comment]
+1

**Comment by jgovciyan** [comment]
+1

**Comment by MathieuCh** [comment]
+1 , still no deezer icon after 2 years.....

**Comment by IFours** [comment]
+1, we need this icon :)

**Comment by matleroux** [comment]
+ 1

**Comment by jasonhibbs** [comment]
+1

**Comment by xaccrocheur** [comment]
OMG come on, just do it already, Jesus. Right now we're forced to use custom SVG embeds, it just makes all of us (specially you guys) look bad :|

Oh, and Diaspora* too. Please?

**Comment by BerengerC** [comment]
+1
I'm often creating website for music. When it comes to link to Artist's deezer pages, it's hard. 

I would also suggest to had :
- Google Music
- Google Play
- Apple Music
- itunes

**Comment by al128** [comment]
+1

**Comment by januscoorevits** [comment]
+1

**Comment by madgustoo** [comment]
+1

**Comment by stanfaire** [comment]
+1

**Comment by starkfabricio** [comment]
+1

**Comment by 84pixels** [comment]
+1

**Comment by dervondenbergen** [comment]
+1

**Comment by lewisdonovan** [comment]
Please include this in the new version. We've got a license already and could really do with this. Cheers.

**Comment by jauregui** [comment]
+1
Please include the following too!
Google Music
Google Play
Apple Music
itunes

I develop several pages for musicians and they're often inside these platforms.

**Comment by turb** [comment]
+1

**Comment by cchepelov** [comment]
+1

**Comment by bluepowder** [comment]
+1

**Comment by julienbornstein** [comment]
+1
Still no Deezer icon in the new font awesome 5 :-(

**Comment by RiFi2k** [comment]
+1
I feel like this is a no-brainer!
12 million active users...
Fourth biggest streaming company in the world for paid users behind Spotify, Apple and Amazon

Also we do a bunch of work for Sony and this icon gets added to every single thing we do only I need to always import in a bootlegged svg :(

**Comment by kevin-coelho** [comment]
+1

**Comment by walkintom** [comment]
Just started using Font-Awesome today and this was the only icon I needed that's missing. It would be amazing if this could be added!

**Comment by JulienFontaine** [comment]
+1

**Comment by mrsof** [comment]
+1
Same for Dailymotion plz

**Comment by kaassouffle** [comment]
+1

**Comment by colinhemphill** [comment]
+1
Would love to link to the Deezer distributions on my band site. We have a good percentage of international listeners, and Deezer is a big one overseas.

**Comment by jasonhibbs** [comment]
Four years 😂

**Comment by juRiii** [comment]
why no deezer?

**Comment by juRiii** [comment]
also +1

**Comment by TheXaver** [comment]
+1

**Comment by clowerweb** [comment]
+1

**Comment by saadbruno** [comment]
+1

**Comment by jennifertigner** [comment]
+1

**Comment by cecstar** [comment]
+1

**Comment by MEDIAMACHINE** [comment]
+1

**Comment by prknje** [comment]
+1

**Comment by VincentSoloOfficial** [comment]
+1

**Comment by kprabhut** [comment]
+1

**Comment by JuHiZz** [comment]
+1

**Comment by Gerungofulus** [comment]
+1

**Comment by gfrcsd** [comment]
5 years later and still waiting. Font awesome is so painfully slow at adding new icons (especially brands), I am a paying member not so sure to be renewing.

**Comment by RiFi2k** [comment]
Yeah not gonna lie this is pretty brutal especially when the svg exists and has been added here in 2014.

**Comment by LevFlavien** [comment]
+1

**Comment by benburton** [comment]
Deezer please!

**Comment by DomWint** [comment]
I thought it was just me that found this odd. Deezer icon, please.

**Comment by al1138** [comment]
+1

**Comment by SavaMinic** [comment]
I can't believe it's been 5 years and nothing. Do anyone from FontAwesome reads this?

**Comment by tagliala** [comment]
@SavaMinic yes, I'm reading this as well as all other requests

Please take a look at our [Brand Leaderboard](https://fontawesome.com/community/leaderboard/brands): the [faqs section](https://fontawesome.com/community/leaderboard/brands#faqs) contains a lot of information on how requests work

**Comment by TheXaver** [comment]
+1

**Comment by smndhm** [comment]
5+ years, 85 comments.  

Looks like the brand icon leaderboard is based on the totoal of the comments and reactions on the first comment.

**So it would help if you all add a reaction here:** https://github.com/FortAwesome/Font-Awesome/issues/2802#issue-26325624  
  
Now, Deezer just changed its logo, from what I know they are ok with the monochrome now...
Here is the svg code :  
`<svg width="109" height="72" viewBox="0 0 109 72" fill="none" xmlns="http://www.w3.org/2000/svg"> 
<path d="M108.3 0.699997H84.9V14.4H108.3V0.699997Z" fill="black"/><path d="M108.3 19.7H84.9V33.4H108.3V19.7Z" fill="black"/><path d="M108.3 38.7H84.9V52.4H108.3V38.7Z" fill="black"/><path d="M23.4 57.7H0V71.4H23.4V57.7Z" fill="black"/><path d="M51.7 57.7H28.3V71.4H51.7V57.7Z" fill="black"/><path d="M80 57.7H56.6V71.4H80V57.7Z" fill="black"/>  
<path d="M108.3 57.7H84.9V71.4H108.3V57.7Z" fill="black"/><path d="M80 38.7H56.6V52.4H80V38.7Z" fill="black"/><path d="M51.7 38.7H28.3V52.4H51.7V38.7Z" fill="black"/><path d="M51.7 19.7H28.3V33.4H51.7V19.7Z" fill="black"/></svg>`

**Comment by RiFi2k** [comment]
BTW it only shows thumbs up in the ranks if you do the inital post in this issue, so there is that too. Also it looks like its pretty much the thumbs up on the first post and the number of comments added together.

Let's just get this done people, if you get an alert come thumbs up the first post, we got 80 some comments but only 30 some thumbs.

**Comment by fabiociaf** [comment]
+ 1

**Comment by rodolfodn** [comment]
+1

**Comment by Maddieman** [comment]
+1

**Comment by rodolfodn** [comment]
5 years btw

**Comment by jeromelive33** [comment]
+999

**Comment by Bertbk** [comment]
The logo have changed since this Issue has been launched. More information can be found on [their website](https://deezerbrand.com/d/9wmMErzrRuiH/brand-elements) and logo can be downloaded in PNG or SVG. The new logo looks like this (in B&W)

<img width="89" alt="Mono_Equalizer_Black@2x" src="https://user-images.githubusercontent.com/5602767/65522286-d8a64680-deea-11e9-8adb-c24fa49f2fcf.png">

**Comment by smndhm** [comment]
@Bertbk nice way to share the new brand website :)

**Comment by sanek4life** [comment]
+1

Available in: 180+ countries
14 million monthly active users, and 7 million paid subscribers as of January 2019.

**Comment by smndhm** [comment]
So, I've been looking for month now to the [brand leaderboad](https://fontawesome.com/community/leaderboard/brands) and Deezer stayed in the top 10 but never got in progress, even Dailymotion (rank #17 right now) is in progress right now...

**Comment by Ectalite** [comment]
+1

**Comment by tapastwain** [comment]
+1

**Comment by seadox** [comment]
pls deezer

**Comment by sanek4life** [comment]
@Deezer team @rlods @doky help us! please press 👍 on [this thread](https://github.com/FortAwesome/Font-Awesome/issues/2802) and tell others about it! so it will helps to bring the addition of this icon to the set!

**Comment by AntoineGoblet** [comment]
+1

**Comment by objque** [comment]
Any news?

**Comment by tagliala** [comment]
@objque please take a look at our [Brand Leaderboard FAQs](https://fontawesome.com/community/leaderboard/brands#faqs) they contain a lot of information on how requests work

**Comment by FredDaniel** [comment]
+1

**Comment by makemagik** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by Asenar** [comment]
+1

**Comment by SavaMinic** [comment]
+1

**Comment by bfblackjack** [comment]
+1

**Comment by tagliala** [comment]
Hi,

icon released in 5.13.1

https://fontawesome.com/icons/deezer?style=brands

**Comment by jminguely** [comment]
+1

**Comment by tagliala** [comment]
@jminguely this icon is available, please make sure your application is using FA >= 5.13.1
