### ISSUE TITLE
Icon Request: audit-trail

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2806]
Hi,

Please could you consider adding an icon for an audit trail. I currently use an image for some buttons but it would be nice to have a font-awesome icon for use in menus.
I think it's common to use boot prints as shown.

Thanks!

![audit](https://f.cloud.github.com/assets/6523548/2018075/8473b7f4-8807-11e3-9551-492aae27bcd6.png)
![audit2](https://f.cloud.github.com/assets/6523548/2018076/84742ab8-8807-11e3-9c92-43ef175085c8.png)

**Comment by dakur** [comment]
+1 for some trail/way/path icon.  
Usage: I have trails and I want to symbolize that under a link the visitor can view all trails.

**Comment by grantneufeld** [comment]
@dakur : I think issue #2788 is what you’re looking for. This one is about iconography for audit details (“audit trails”).

**Comment by tagliala** [comment]
let's use #3175 for footsteps, better name
