### ISSUE TITLE
Icon request: Display Ad 

### ISSUE THREAD

**Issue by dirxionkaren** [FortAwesome/Font-Awesome#2808]
We would really appreciate it if a 'display ad' icon could be added to your list. We would be using it on our list product, under any company that has a display ad they want to showcase. Please see screenshot:
![search results](https://f.cloud.github.com/assets/4820216/2020830/f8edef3a-8836-11e3-9a5c-19f855cd12ae.PNG)
You can see the icons we have now - play button, camera, tag. This 'display ad' icon would take the place of the tag. Seems to make more sense and not confuse the user on what they are clicking. If they click on an icon that says 'AD" we think it would be a better experience!

Here is a mock-up:
![display_ad](https://f.cloud.github.com/assets/4820216/2020025/c364a21e-882c-11e3-9032-b87df8678898.png)

Please let me know if this is feasible! Thank you for your time!

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/rectangle-ad?s=solid
