### ISSUE TITLE
fa-fw doesn't play well with fa-stack

### ISSUE THREAD

**Issue by pupeno** [FortAwesome/Font-Awesome#2815]
I'm not sure what would be the proper way to report this, but I tried several permutations of adding fa-fw to stacked icons and they don't play well together. The final width ends up being smaller than that of a 2x fa-fw icon because fa-stack overrides the width.

Am I missing something obvious? I'm just getting started with font awesome.

**Comment by oshields** [comment]
Thanks @tagliala!  Is there any update on this being included or is there another accepted solution?

**Comment by tagliala** [comment]
I've  just noticed that this has been fixed in FA 5.5.0

Demo: http://jsfiddle.net/tagliala/foLe8rx3/
