### ISSUE TITLE
Icon Request: justice-scales

### ISSUE THREAD

**Issue by cwood28** [FortAwesome/Font-Awesome#2818]
Please create a new icon that represents the scales of justice.  Example attached.
![image](https://f.cloud.github.com/assets/6537887/2033187/4d68a2d4-8919-11e3-92ac-23855170b7f0.png)

**Comment by AntoVasanth** [comment]
+1

**Comment by henleywc** [comment]
+1

**Comment by khoshrou** [comment]
+1 but give it a better icon coz this is more related to law concepts

**Comment by happyloha** [comment]
+1

**Comment by mm-habibi** [comment]
+1

**Comment by noedlm** [comment]
+1

**Comment by nd2s** [comment]
+1

**Comment by rwtrwt** [comment]
+1

The mobile website CMS "dudamobile" has an icon for the scales named justice. I wish I could figure a way to add it to my local font awesome folder

source code shows the following div controlled by font-pack.css
HTML
<div class="navIcon dm-icon-justice hasFontIcon" id="dm_navGroup010101882910icon" style=""
::before
</div>

CSS
.dm-icon-justice:before {
  content: "\e6ed"

you can look at my mobile site http://m.danielstaylor.com to see the icon in action (it works in desktop browsers as well)

If anyone could help thanks in advance

**Comment by EddieFromFA** [comment]
+1

**Comment by ksleyko** [comment]
Isn't this a duplicate of https://github.com/FortAwesome/Font-Awesome/issues/276?

**Comment by tagliala** [comment]
@ksleyko thanks

yes it is, but I was thinking that the other one was a weight scale. :\

I should merge +1s

**Comment by ymoreiratiti** [comment]
+1

**Comment by tagliala** [comment]
closing here as a duplicate of #276

**Comment by alexbreems** [comment]
+1

**Comment by tagliala** [comment]
locking here
