### ISSUE TITLE
Icon request: Alien Icon

### ISSUE THREAD

**Issue by Matthew2D** [FortAwesome/Font-Awesome#2839]
I would love it if you could make an alien icon! Thanks!

**Comment by devfeng** [comment]
+1

**Comment by devfeng** [comment]
Look at my avatar!

**Comment by ouschmitz** [comment]
+1

**Comment by Kyootxims** [comment]
+1

**Comment by mf3101** [comment]
+1

**Comment by Xarex** [comment]
Until FontAwesome decides to add this, use the built-in Microsoft font Segoe UI Symbol.

Read more here: http://www.geekchamp.com/icon-explorer/fun-icons/icon?code=1f47d

**Comment by pckz** [comment]
+1

**Comment by AWestermeyer** [comment]
+1
Please add : 
- fa-alien
- fa-roswell
- fa-ufo

**Comment by omegaxnodle** [comment]
+1

**Comment by yaroslavpat** [comment]
+1 on this!

**Comment by kirik** [comment]
+1

**Comment by zhavoronkov** [comment]
++

**Comment by oxozle** [comment]
++

**Comment by desian78** [comment]
@tagliala "fa-ufo" != "fa-alien"... but both worth it...

**Comment by tagliala** [comment]
@desian78 thanks for the heads-up

We have two separate requests for ufo (#4231) and alien (this one). Feel free to upvote both

**Comment by chadwtaylor** [comment]
+1 for ufo
+1 for alien

**Comment by sensibleworld** [comment]
We now have a few alien options: https://fontawesome.com/icons?d=gallery&q=alien&c=science-fiction
