### ISSUE TITLE
Icon Request: icon-treehouse

### ISSUE THREAD

**Issue by whaleen** [FortAwesome/Font-Awesome#2840]
RIght off the bat you'd have many Treehouse members using this in their social link lists on their sites and blogs. More and more I'd expect a Treehouse profile to become what aspiring web designers and developers want to link to or to showcase.

**Comment by sebroeder** [comment]
I would love to see this, too. My use case: I use fontawesome in my CVs created with XeLaTeX.

**Comment by C187** [comment]
+1 This type of icon would be a great inclusion to the social set.

**Comment by Eric-Vandenberg** [comment]
Yes please we can use something like this:  I'll post white bg and transparent bg images
![treehouse-glyph](https://cloud.githubusercontent.com/assets/8475435/6322548/903f69c8-bacb-11e4-88d0-4b75aa9908f6.png)

**Comment by Eric-Vandenberg** [comment]
This one is transparent:

![treehouse-glyph copy](https://cloud.githubusercontent.com/assets/8475435/6322581/417ea550-bacc-11e4-969b-10d4e6dd175d.png)

**Comment by DigiMouse** [comment]
+1 Treehouse and its awesome community is quickly becoming my go to place for answers on the web and I already have font awesome its a shame to need a separate svg file :)

**Comment by NiklasPetersson** [comment]
+1

**Comment by gavmac** [comment]
Please make this happen :)

**Comment by edgilmore** [comment]
+1

**Comment by Velua** [comment]
Yes please!

**Comment by gaballison** [comment]
Bumping this request, I definitely would love a Treehouse icon!

**Comment by andresangelini** [comment]
+1

**Comment by whaleen** [comment]
It's been six years.
