### ISSUE TITLE
Icon Request: fa-squarespace

### ISSUE THREAD

**Issue by centup** [FortAwesome/Font-Awesome#2842]

**Comment by xomisse** [comment]
+1

**Comment by isaacsummers** [comment]
+1

**Comment by stormwarning** [comment]
+1

**Comment by awilbert** [comment]
+1

**Comment by robertevelyn** [comment]
+1

**Comment by Tech-CF** [comment]
+1

**Comment by davidhughesco** [comment]
Could I resurrect this request, please? A Squarespace icon would be very useful. [Here's their mark.](https://static1.squarespace.com/static/5134cbefe4b0c6fb04df8065/t/587fa2fd440243130a3dc983/1499717024235/squarespace-logo-symbol-white.jpg?format=500w)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/squarespace?style=brands
