### ISSUE TITLE
Icon request: Cookie

### ISSUE THREAD

**Issue by lauritzt** [FortAwesome/Font-Awesome#2845]
It would be very useful to have a cookie icon in my cookie message thing (required in EU).

**Comment by irenesu** [comment]
+1!!  This cookie looks a bit like ovaries. Would like to use it on our study website for reproductive health studies in young cancer survivors.  
![chocolate chip cookie 02-02-15](https://cloud.githubusercontent.com/assets/10832698/6023146/19c88508-ab77-11e4-97ee-dab0d2f333c6.png)
![chocolate white cookie 02-02-15](https://cloud.githubusercontent.com/assets/10832698/6023150/21d7696c-ab77-11e4-90fe-749800beb0ce.png)

**Comment by opdrift** [comment]
Would be very useful :+1:

**Comment by ABuche** [comment]
YES!! +1

**Comment by Maffblaster** [comment]
:+1: Cookie is very much needed...but it should be a whole cookie that looks tasty to eat, not one that already has a bite taken out of it!

**Comment by gastongouron** [comment]
![fa-cookie-01](https://cloud.githubusercontent.com/assets/1798822/8376515/7f35951e-1c08-11e5-9127-16b68fe133f4.png)

fa-cookie ?

**Comment by StephanStanisic** [comment]
+1

**Comment by ABuche** [comment]
Yes! This is perfect!

Date: Fri, 26 Jun 2015 04:37:58 -0700

**Comment by ojdon** [comment]
+1

**Comment by ptessier** [comment]
+1

**Comment by lucazpf** [comment]
+1

**Comment by migig** [comment]
+1

**Comment by maximvd** [comment]
+1

**Comment by whitebird** [comment]
![cookie](https://cloud.githubusercontent.com/assets/1058174/10292652/af753868-6bb0-11e5-8576-89b7a5c4b881.png)

I have the source .svg if you want.

**Comment by reedvoid** [comment]
Please consider adding an icon that's the representation of a cookie.

I am developing a snack site that needs a snack-related icon to represent a section of the site that's a collection of snacks the user has eaten before. The closest thing I could find right now in the font-awesome 4.4 library is a birthday cake, which isn't nearly as great at conveying the concept of "snack" as a cookie would.

In addition, the cookie icon could also conceivably be used to represent website cookies as another use case.

The cookie should probably have some kind of a crumbling look to it, since a simple circle or square won't look like a cookie. Maybe it should also have some tiny holes in it like saltines so it looks more like a cookie.

I've attached an image of something pretty close to what I think would be appropriate.

Many thanks for your consideration!!
![059bb6b4-6bb0-11e5-80fd-2f043ae14c55](https://cloud.githubusercontent.com/assets/14979636/10300606/59630d12-6c2b-11e5-9990-84c61b8e32cc.jpg)

**Comment by KevinMeeuwisse** [comment]
+1

**Comment by timavo** [comment]
+1

**Comment by w3b-beweb** [comment]
+1

**Comment by daniel-avatar** [comment]
+1

**Comment by svanegaard** [comment]
+1

**Comment by teomaragakis** [comment]
+1. I would go for a fortune cookie instead.

**Comment by AshCoolman** [comment]
```

$('.comment-body img[src*=githubuser').clone().css({width:'1em', heigh:'1em'}).appendTo($('.js-issue-title'));
$('.js-issue-title img').wrap('<span class="cookie"></span>')
$('.comment-body img[src*=githubuser').clone().css({width:'18px', heigh:'18px'}).appendTo($('.js-issue-title'));
$('body').scrollTop(0)
var style = `
body {
  counter-reset: cookiecounter;
}
.js-issue-title .cookie:before {
  counter-increment: cookiecounter;
  content: counter(cookiecounter);
  display:inline-block;
  font-size: 8px;
  font-color:silver;
}`;
$(`<style type='text/css'> ${style}</style>`).appendTo("head");
```

Paste this to see them all, I'd like to see an inverse 1 and 5.

**Comment by mrsideshowjack** [comment]
+1

**Comment by gulycka** [comment]
+1 could be very useful

**Comment by mairo744** [comment]
+1

**Comment by AnMartini** [comment]
+1

I suggest the bitten cookie, otherwise it isn't clear.

**Comment by whitebird** [comment]
(Made repository with a couple of suggestions)[https://github.com/whitebird/FontAwesome-cookie]

**Comment by samgielis** [comment]
+1, a cookie icon seems like a natural element of a (web-oriented) icon font.

**Comment by aethior** [comment]
+1

**Comment by ptahchiev** [comment]
+1

**Comment by wvffle** [comment]
+1

**Comment by marathia** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by radiovisual** [comment]
+1 👍

**Comment by CharlSteynberg** [comment]
+1

![cookie_icon](https://cloud.githubusercontent.com/assets/8987492/14768035/3ca2aa76-0a36-11e6-90e0-1c8138886ad6.png)

[svg is here on github](https://github.com/CharlSteynberg/glyphs/blob/master/cookie_icon.svg)

**Comment by paya-cz** [comment]
+1

**Comment by timmy14085** [comment]
+1

**Comment by Shadow48402** [comment]
+1

**Comment by zeroasterisk** [comment]
+1 --- and I like the proposal by @CharlSteynberg

**Comment by harboe** [comment]
+1

**Comment by pepperstreet** [comment]
+1 (overdue ;) )

**Comment by JokkeeZ** [comment]
+1

**Comment by RobertDiebels** [comment]
+1 , Would like to add that a perfectly round cookie does not exist. I do get why it would have to be perfectly round since it would fit with the styling of the icons. 

Reason for a cookie icon would be the same as the OP's:

- Website cookie settings.

**Comment by akhodr** [comment]
+1 (way overdue)

**Comment by rgustavsson** [comment]
+1

**Comment by colinrcummings** [comment]
+1

**Comment by hiryu85** [comment]
+1

**Comment by wkille** [comment]
+1

**Comment by garyfullness** [comment]
+1

**Comment by moskoweb** [comment]
+1

**Comment by ilbelon** [comment]
+1

**Comment by Rodot** [comment]
+1

**Comment by mijrs** [comment]
+1

**Comment by thomascorthals** [comment]
+1

**Comment by ts2004** [comment]
+1

**Comment by TimS-** [comment]
+1

**Comment by itd24** [comment]
+1

**Comment by sabvdf** [comment]
+1

**Comment by katelynearl** [comment]
+1

**Comment by Wingo5315** [comment]
+1

**Comment by bloep** [comment]
+1

**Comment by ReGdYN** [comment]
+1

**Comment by adarshmadrecha** [comment]
+1

**Comment by Surbma** [comment]
+1

Can't believe it is still missing...

**Comment by sensibleworld** [comment]
Hey folks! We’re getting back on track with requested icons. You can follow along with progress and recent releases here: https://fontawesome.com/community/leaderboard/released

**Comment by Wingo5315** [comment]
Icon-cookie is "in progress" (according to their leaderboard)

**Comment by andyhausmann** [comment]
+1

**Comment by foghladha** [comment]
+2 With GDPR here this is one that would get used A LOT!

**Comment by Wingo5315** [comment]
Good news, guys! We are on the FA Leaderboard and the cookie icon is "In Progress".

**Comment by sensibleworld** [comment]
It is indeed! The icon has been designed and should be out in our next release.

**Comment by CharlSteynberg** [comment]
Thanks guys, appreciated.

**Comment by alystair** [comment]
@sensibleworld feedback re:released icon - getting some major pareidolia as the chips make it look like a face, or bowling ball. Can't help but see the spirits of the forest from Princess Mononoke either... 
![2a2a3dc21200c6025a7e2f209b818926](https://user-images.githubusercontent.com/159109/41737564-a9fbea08-755d-11e8-8528-c0e6d64f763b.jpg)

![image](https://user-images.githubusercontent.com/159109/41737585-b9b9294c-755d-11e8-9d1d-15a9f51dd7a1.png)

Personally feel the outside edge is a bit too rounded as well.

**Comment by sensibleworld** [comment]
@alystair Yeah, it's tricky at the small size. 5 "chips" felt too crowded, 4 "chips" weren't random enough. The "cookie-bite" icon is meant to be the more official one, but I also wanted to include an intact "cookie".

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=cookie&v=5.1.0
