### ISSUE TITLE
Icon Request: fa-cpanel

### ISSUE THREAD

**Issue by enikmiguelon** [FortAwesome/Font-Awesome#2846]
Hi,

We would like to have an icon in cPanel. It can be used on any hosting control panel to refer to this control panel. 

Thank you very much.

**Comment by mewcrazy** [comment]
+1

**Comment by jbarbede** [comment]
+1

**Comment by hatclub** [comment]
+1 for a "cP" icon

**Comment by truls1502** [comment]
+1

**Comment by lpelgrave** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by ninjagirrl76** [comment]
+1

**Comment by shagoon** [comment]
+1

**Comment by ShaunR** [comment]
+1

http://cpanel.com/cpanel-brand-guide/

**Comment by ShaunR** [comment]
![cp-logo](https://cloud.githubusercontent.com/assets/1671445/10235203/3e9a35e4-684f-11e5-9f48-f2d069916bf2.png)

**Comment by ShaunR** [comment]
Probably should do a WHM Icon too since they kind of go hand in hand.
![whm](https://cloud.githubusercontent.com/assets/1671445/10235242/7dfad586-684f-11e5-82f2-0cbdc58fec88.png)

**Comment by nauvalazhar** [comment]
+1

**Comment by Trax2k** [comment]
+1

**Comment by nizarb** [comment]
+1

**Comment by kurai021** [comment]
WHM too

**Comment by ShaunR** [comment]
and webmail... 

http://cpanel.com/assets/img/logos/webmail.png

**Comment by 3x1l3** [comment]
+1 and WHM too

**Comment by truls1502** [comment]
+1 for this and WHM too!

**Comment by thenocman** [comment]
+1, please add cPanel and WHM

**Comment by eatonphil** [comment]
+1

**Comment by selfpaidinc** [comment]
+1

**Comment by azizmustikaaji** [comment]
**+1**

**Comment by estudiowebmedia** [comment]
+1 Cpanel/WHM

**Comment by estudiowebmedia** [comment]
+1

**Comment by estudiowebmedia** [comment]
+1

**Comment by boutzamat** [comment]
+1

**Comment by shtalinberg** [comment]
+1

**Comment by berzley** [comment]
+1

**Comment by Giladx** [comment]
+1

**Comment by buddizer** [comment]
+1

**Comment by rafaeloliveiraz** [comment]
+1

**Comment by smplejohn** [comment]
+1

**Comment by rihamd2k** [comment]
I also need this.

**Comment by rafihaidari** [comment]
+1 cPanel and WHM

**Comment by Luneya** [comment]
+1 cPanel, DirectAdmin and WHM.

**Comment by aang-naja** [comment]
+1

**Comment by T4U** [comment]
+1

**Comment by TheMongooseBytes** [comment]
any progress on the cPanel and WHM and perhaps HP (brand) icon ?

**Comment by AGraber** [comment]
+1

**Comment by gfserver** [comment]
+1

**Comment by NickRT91** [comment]
+1

**Comment by hithomasmorelli** [comment]
+1

**Comment by hithomasmorelli** [comment]
+1

**Comment by lucabriguglia** [comment]
+1

**Comment by tagliala** [comment]
cPanel is available since 5.0.0

https://fontawesome.com/icons/cpanel?style=brands

**Comment by ShaunR** [comment]
What about the cP, WHM, and Webmail logos?

**Comment by tagliala** [comment]
cp: #13630 
whm: #17010 
webmail: please search before and if you can't find one feel free to open a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
