### ISSUE TITLE
Feature requests: fa-rotate-45

### ISSUE THREAD

**Issue by magoo-pl** [FortAwesome/Font-Awesome#2858]
Yesterday I need to do a close button and I want to use font-awesome to do it. And there was no cross icon or something like that. I simply used plus icon and rotate it 45deg with additional class.

I want to suggest a "fa-rotate-45" class for icons.

**Comment by sarciszewski** [comment]
> IE8/9 really sucks on 45deg rotations:

> IE8/9 really sucks 

FTFY -- is IE 8/9 support going to be revoked in a future version of Font Awesome?

**Comment by shunsukeaida** [comment]
Not sure FA's support policy, but I'm concern it's akin to ask when Windows 7 will die...

**Comment by KerriLea** [comment]
+1 for fa-rotate-45

**Comment by zuhloobie** [comment]
I use this for 45 rotations - just add onto font-awesome.min.css file:

`
.fa-rotate-45 {-webkit-transform:rotate(45deg); -moz-transform:rotate(45deg); -ms-transform:rotate(45deg); -o-transform:rotate(45deg); transform:rotate(45deg);}
`

Then add `fa-rotate-45` to inline span code like `<span class="fa fa-hand-o-right fa-rotate-45"></span>`

**Comment by javiros** [comment]
@zuhloobie thank you!

**Comment by isuvorov** [comment]
+1

**Comment by coeus01** [comment]
**+1**

**Comment by My1** [comment]
@shunsukeaida nah I rather think until vista dies. Win7 got IE Updates and older IE versions than the latest available on a given system are dropped out of MS's support corner.
and the only OS with IE9 as latest is Vista.

**Comment by tagliala** [comment]
Closing here in favour of #8515
