### ISSUE TITLE
OPML Icon

### ISSUE THREAD

**Issue by stefankoegl** [FortAwesome/Font-Awesome#286]
It would be great to have an OPML (https://en.wikipedia.org/wiki/OPML) icon. The icons at http://opmlicons.com/ seem to be widely used, and are distributed as CC-by-SA, so maybe they can be re-used in Font-Awesome.

**Comment by lddurbin** [comment]
Stacking fa-square with fa-dot-circle-o produces something very similar to the OPML icon.
