### ISSUE TITLE
Icon Request: Video Player Icons - shuffle and repeat

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#2864]
Video Player Icons (and so audio player) can have shuffle and repeat icons. now every new html5 audio player includes this buttons

**Comment by Thedimka** [comment]
Please add alias "Shuffle" to the Random icon.

**Comment by tagliala** [comment]
There is a filter, they work in the doc page:

![image](https://cloud.githubusercontent.com/assets/556268/10566694/80baf63c-75ee-11e5-9f93-ac805550a14d.png)
