### ISSUE TITLE
Icon request: Cupcake

### ISSUE THREAD

**Issue by justinab** [FortAwesome/Font-Awesome#2869]
What would internet be without cats... What would we be without cupcakes... World would be way worse without these two, FontAwesome too :D
Baby is just for many moms blogs I help to manage :)

**Comment by MayJow** [comment]
+1

**Comment by MatthiasHertel** [comment]
1+

**Comment by msclar** [comment]
+1

**Comment by mothershedc** [comment]
+1

**Comment by misstiina** [comment]
+1
