### ISSUE TITLE
Icon request: wifi-alt or signal-alt

### ISSUE THREAD

**Issue by mludowise** [FortAwesome/Font-Awesome#2870]
I would like an icon similar to this, please. We plan to use it in our interface to reference the word "signal" in a more abstract sense as opposed to just cell phone signal. I've also seen other icon packs, like glyphicons, use it as wifi-alt.

![image](https://f.cloud.github.com/assets/1626168/2133897/2fd1072c-92d1-11e3-9f94-a71b19d7fe85.png)
Image is from Metro Tech by Aha-Soft:
https://www.iconfinder.com/icons/199593/cell_cell_tower_communication_connection_connections_internet_mobile_network_radio_remote_signal_tower_wifi_wireless_icon#size=128

**Comment by tuxy** [comment]
+1 for fa-signal-tower

**Comment by tagliala** [comment]
dup of #2581, please +1 that request 

closing here

**Comment by tuxy** [comment]
@tagliala, done. Thank You!
