### ISSUE TITLE
Icon request: icon-mute (icon-volume-mute)

### ISSUE THREAD

**Issue by loxal** [FortAwesome/Font-Awesome#288]
As opponent button to icon-headphones or icon-music.

Some inspirations:

https://www.google.com/search?q=mute+button&hl=en&prmd=imvns&source=lnms&tbm=isch&sa=X&ei=sEbfT-3pEKuP4gSYo-S8Cg&ved=0CEgQ_AUoAQ&biw=1919&bih=959

**Comment by plainclothes** [comment]
Such a long thread but no one has gotten to the point!  
You just need a **`volume-slash`**.  
That would be super handy.

**Comment by ivan-tellez** [comment]
+1

**Comment by LetsVape** [comment]
+1

**Comment by rzolin** [comment]
+1

**Comment by Prinzhorn** [comment]
+1

I'd also like to raise another issue related to this: alignment/spacing. I'm not sure if this has been discussed in regards to other icons. I personally think the current `volume-off` and `volume-down` icons need to have spacing to the right build into the glyph itself. Imagine toggling between off state. You'd use `-off` and `-up` as the two states. The icon would then jump inside of the button because of different widths (assuming they'd be centered inside of the button).

To sum it up: all three (or then four) volume icons should have the same width. When stacking them on top of each other the speakers should align.

I don't see any workaround to get this done with CSS, as the the different widths of the glyph are basically magic numbers.

Checkout this demo http://jsbin.com/dirivuseza/1

![screenshot from 2015-03-15 09 00 30](https://cloud.githubusercontent.com/assets/679144/6655164/cda2312a-caf1-11e4-973a-f38d92ca6fd9.png)

Related: https://twitter.com/wiseacre/status/558643124009205763

**Comment by tagliala** [comment]
`text-align: left` should do the job: http://jsbin.com/quyoqukozi/2/edit?html,output

**Comment by Prinzhorn** [comment]
> text-align: left should do the job:

It does for this special case. I'm using this CSS for all kinds of buttons with icons and I want them to be centered.

Anyway, let's not spam this thread as we're notifying tons of people.

**Comment by carlosmacias** [comment]
+1

**Comment by stewartmccoy** [comment]
+1

**Comment by art1351** [comment]
+1 we definitely need an fa-volume-slash or fa-volume-mute! Would be nice if it was slash to match fa-microphone-slash.

**Comment by specialorange** [comment]
+1.   Any update on this?

**Comment by art1351** [comment]
I was able to make a decent muted icon by combining 'volume-off' and 'times'

<span class="alignright"><i class="fa fa-microphone-slash fa-lg"></i><span class="fa-stack"><i class="fa fa-volume-off fa-lg"></i><i class="fa fa-times"></i></span></span>

**Comment by specialorange** [comment]
I just learned you can stack icons: http://fortawesome.github.io/Font-Awesome/examples/#stacked

<div class="fa-stack">
  <i class="fa fa-volume-off fa-stack-1x"></i>
  <i class="fa fa-ban fa-stack-1x"></i>
</div>

**Comment by dayfv95** [comment]
+1

**Comment by rossvz** [comment]
This is still not ideal, even with the stacked ban icon. If you look at the red icon above, it's not clear that its a speaker with a line through it. Needs a slash or very thin "ban" to really be clear. Or, as others have suggested for the past two years, an "x" by the speaker

**Comment by tvirelli** [comment]
+1

**Comment by specialorange** [comment]
@davegandy I noticed you closed this a while back before it was reopened.   Is there a way to get this included in the next update?   I wouldn't mind helping.  PM me if you would like.

**Comment by sergiolepore** [comment]
+1 :smile:

**Comment by carcharodoncarcharias511** [comment]
+1

**Comment by Evanion** [comment]
The fact that this issue have been open for >3 years ...

**Comment by Hagith** [comment]
+100

**Comment by hw-nf** [comment]
+1 (speaker with slash)

**Comment by slasktrat** [comment]
+1

**Comment by dayfv95** [comment]
Has this been created yet?

**Comment by KeitIG** [comment]
+1

**Comment by henriquemaio** [comment]
2012, 2013, 2014, 2015...
2016!

+1

**Comment by dayfv95** [comment]
2017?

**Comment by cherrador** [comment]
I updated my stack sample to include this icon with an X
https://jsfiddle.net/cherrador/jomgLb2h/

**Comment by malard** [comment]
+1

**Comment by nltesown** [comment]
+1

**Comment by leothelocust** [comment]
+1

**Comment by MaxNoe** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by codebucketdev** [comment]
+1 :+1:

**Comment by KeitIG** [comment]
Any chance we'll see it one day ? It's been 4 years...

**Comment by ChrGriffin** [comment]
+1 for a hard mute indicator.

**Comment by sopinon** [comment]
+1 :+1:

**Comment by dayfv95** [comment]
I think i started this thread 4 years ago. its been so long i dont even
remember actually.  maybe one of us should just draw this thing and be done
:)

**Comment by manderson23** [comment]
+1

**Comment by codebucketdev** [comment]
C'mon, even Glyphicons have one in the free version bundled with
Bootstrap 3 :disappointed: 

Am 17.08.2016 23:53, schrieb Mark Anderson:

> +1 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind, oder diese
E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den
Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie
die unbefugte Weitergabe dieser E-Mail ist nicht gestattet. 

-- 

_Diese Mail wurde über eine sichere Verbindung verschickt und wurde vor
Versand auf Viren geprüft._ 

Links:
------
[1]
https://github.com/FortAwesome/Font-Awesome/issues/288#issuecomment-240560888
[2]

**Comment by ggrillone** [comment]
+1

**Comment by Bloodyfool** [comment]
+1

**Comment by kmodoio** [comment]
+1

**Comment by meserlian** [comment]
+1

**Comment by r10o** [comment]
+1

**Comment by reissr** [comment]
+1

**Comment by drstonebraker** [comment]
+1

**Comment by Crissov** [comment]
Unicode emoji: #222

- [🔇 U+1F507](http://emojipedia.org/speaker-with-cancellation-stroke/)
- [🔈 U+1F508](http://emojipedia.org/speaker/)
- [🔉 U+1F509](http://emojipedia.org/speaker-with-one-sound-wave/)
- [🔊 U+1F50A](http://emojipedia.org/speaker-with-three-sound-waves/)

Non-emoji characters:

- [🕨 U+1F568 Right Speaker
- [🕩 U+1F569 Right Speaker with One Sound Wave
- [🕪 U+1F56A Right Speaker with Three Sound Waves

**Comment by oriadam** [comment]
+1

**Comment by brainkim** [comment]
JFC, all I ever wanted was the volume up speaker with a slash through it looks like this, why isn't this happening. Am I just insane? Is this impossible?
<img width="109" alt="screen shot 2017-03-30 at 4 05 05 am" src="https://cloud.githubusercontent.com/assets/2996754/24493828/2bb39242-14fe-11e7-92d4-7834dbfb6fbe.png">

**Comment by dayfv95** [comment]
We will all die before this icon gets created

**Comment by malard** [comment]
my guess is it will be in fa-5

**Comment by vectorloft** [comment]
+ 1 on mute icon

**Comment by steven7mwesigwa** [comment]
2012, 2013, 2014, 2015, 2016, ...
2017 ????

**Comment by dayfv95** [comment]
2046

**Comment by leecollings** [comment]
I agree it would be best to follow with the fa-audio-slash idea, and use a fa-volume-slash.

I currently have three buttons to mute video, audio and microphone.

For the video i'm using the fa-eye-slash, however the angle of the slash is completely different to that of fa-bell-slash and fa-microphone-slash.... Could we have these as a set? (like a Media icon set)

**Comment by AuditeMarlow** [comment]
Please, for the love of god, +1

**Comment by ecly** [comment]
+1

**Comment by dayfv95** [comment]
+never

**Comment by tkanemoto** [comment]
This is probably futile, but +1. I wonder why there's no more reason/statements given. Maybe it because it was closed once already and the matter is considered to be closed as far as they are concerned? In that case, it's quite passive aggressive to not respond at all. Maybe it's worth raising a new ticket.

**Comment by that1communist** [comment]
+1

**Comment by jpezninjo** [comment]
+1

**Comment by fufuninja** [comment]
+1

**Comment by thetland** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
Available in FA5 Pro: https://fontawesome.com/icons/volume-mute

**Comment by 1j01** [comment]
So I have to pay $60 in order to use this icon in my free and open source project? I already *have* a mute icon, I'd just prefer a different one...

> I'm afraid I can't volume-mute that, Dave.

**Comment by that1communist** [comment]
Also there needs to be muted volumes for all the different volume levels.

**Comment by leecollings** [comment]
@that1communist  I don't agree with you. Muting volume is more of a state than an option. When the volume is muted, no sound is outputted so there doesn't need to be any indication of what level the volume is at.

Look at most things, like TVs. The icon will always show a speaker with either a line or cross through it, with nothing referring to what the volume level was set to prior to being muted.

**Comment by that1communist** [comment]
So if I have the half step enabled, the volume icon will show max when I mute? That looks horrible. And there's no disadvantage to allowing it. It should refer to the volume state prior to being muted.

**Comment by leecollings** [comment]
:S no it will have a speaker with a cross next to it ideally, to indicate there's no sound output. It's a pretty global thing, I don't see why it'sso complicated.

**Comment by that1communist** [comment]
I have my percentage next to my volume icon, if I did this, i'd have to remove space between the percentage and the volume icon whenever I muted. It's just convoluted and annoying, when the various icons could just have a \ going through them.

**Comment by David-EU** [comment]
Requested in 2012, closed numberous of time because you didn't undestood that a speaker isn't the same thing as a speaker with a cross/line that indicate that the volume is muted. You denied to everyone, saying that we are false and that we are not using it right.
Then 5 years laters you put it in paid icons, proving by evidence YOU way false, and still let us with no icons. For sure I won't pay for a single BASIC icon, and to not encourage you with this sort of acts.
Thanks budy, great case management !

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/volume-mute?style=solid
https://fontawesome.com/icons?d=gallery&q=volume

**Comment by dayfv95** [comment]
OMG...i cant believe it !!!!! how many years was that you guys think?

**Comment by KeitIG** [comment]
Make a 6 years old request a Pro icon. Well played guys, well played. 

Anyway, thank you I guess?

**Comment by sensibleworld** [comment]
Hey folks! Sorry this icon didn’t make it into Font Awesome Free. We hope you’ll give Pro a try.

**Comment by leecollings** [comment]
@sensibleworld I think at the very least, you could apologise for why this has taken 6 years after the many requests from users that this is needed, and perhaps also explaining why you've decided to then not make it available to everyone?

That's actually quite a nasty thing to do...

**Comment by dayfv95** [comment]
Lmao

**Comment by malard** [comment]
yeah its not a good response. To offer a full set of icons for free sans one unless you buy pro is essentially trialware. But meh.

**Comment by davegandy** [comment]
We don't prioritize based on age, usually number of requests. This particular one never got as many as pops our stack. As a part of work on a new status category for the Kickstarter rewards, we made a bunch of statuses. This was one of them. After going back through old issues, we found this one and let folks know it was added.

**Comment by davegandy** [comment]
@malard We'd never have made this icon if there wasn't a Pro option. Simple as that.

**Comment by leecollings** [comment]
@davegandy How many requests did this icon accumulate?

**Comment by davegandy** [comment]
@malard Also, Font Awesome Free is now twice the size it was precisely because people pay for Pro. Now we can pay salaries and make more icons, both Free and Pro.

**Comment by malard** [comment]
@davegandy Sorry I was not trying to be difficult, it was more a statement of fact, if your adding icons but have perma rulled out the idea of offering this icon in free, then is your policy shifting to once its in Pro its never in Free?

**Comment by KeitIG** [comment]
> Hey folks! Sorry this icon didn’t make it into Font Awesome Free. We hope you’ll give Pro a try.

No lifetime license option, so unfortunately, I won't (and I'd be ready to pay far more than 65$ for it). A discount for open-source project would be awesome too. :/

> Also, Font Awesome Free is now twice the size it was precisely because people pay for Pro.

And this is true, we all thank you for that, the criticism comes for this icon, which is what I would consider a basic one.

**Comment by davegandy** [comment]
@KeitIG Actually, the license is perpetual. The subscription side (which you can turn off) is for updates after a year, services, and actual human tech support. Honestly, we do think it's a fair price for $60.

And fair enough on considering this a basic icon. I can see that perspective. Honestly can. :)

**Comment by davegandy** [comment]
@malard Back in the Kickstarter, we had the option for folks to commission any icon they wanted for $200. Or 6 icons, or a whole category. We could definitely re-consider that option here. So far, once things have been added to Pro we've never added them into Free. But nothing says we couldn't do that.

**Comment by malard** [comment]
@davegandy what would you want to put this icon in free? it just sucks that you have an entire set of icons to make a virtual remote control, sans the mute icon! :)

**Comment by davegandy** [comment]
@malard Couple of ways. First would be if someone sponsored the icon. Second, I'll reconsider whether this should be in Free. We've got 5.4 coming up in another month, and we could make an adjustment if we think it's the right thing. Plenty of good thoughts here and good folks letting us know they disagree. We do hear you.

But right now is NOT a good time for me to make that decision. Folks acting this way this this thread weighs on the team heavily. So it REALLY ticks me off. I'll make the decision when I have a chance to step away and consider.

**Comment by malard** [comment]
@davegandy totally understand :) my profile has my contact details reach out to me via email and we can discuss Sponsorship. 

all the best

**Comment by davegandy** [comment]
> all the best

You as well, @malard. I'll drop you an email.

**Comment by sensibleworld** [comment]
Just to close the loop, the `volume-mute` icon is now available in Font Awesome Free: https://fontawesome.com/icons/volume-mute?style=solid
