### ISSUE TITLE
Icon Request: icon-friend (friend request, two users, facebook like - male female)

### ISSUE THREAD

**Issue by geofili** [FortAwesome/Font-Awesome#2883]
Can you please add an icon that represent a Friend

For example:
Similar the fa-users icon but with 2 people instead of 3.

This would be very popular icon.
Facebook have a similar icon at the top of the page in their navigation bar for Friend-Requests.

A massive thank you for all your excellent work :)

**Comment by florian-j** [comment]
+1 !

**Comment by SimplicityGuy** [comment]
+1 for tekamolo's suggestion!

**Comment by Nutzzz** [comment]
+1

**Comment by ShiftCtrlArt** [comment]
+1
![fortawesome-suggestion-users](https://cloud.githubusercontent.com/assets/12486399/7672448/5b7f4112-fca8-11e4-99c4-88141a7ab480.jpg)

**Comment by cansozeri** [comment]
+1

**Comment by jaybyon22** [comment]
+1 
Thanks for your hard work. I really need this!

**Comment by Hemanth089** [comment]
+1

**Comment by Code-Crash** [comment]
+1

**Comment by 1eddy87** [comment]
+1

**Comment by roberto-paes** [comment]
+1

**Comment by dprensa1** [comment]
+1

**Comment by scottb50** [comment]
+1

**Comment by DavzorD** [comment]
+1

**Comment by jleee** [comment]
+1

**Comment by JHFirestarter** [comment]
+1 funny, @jleee !

**Comment by jbostoen** [comment]
+1

**Comment by JustinMcDonald** [comment]
+1

**Comment by yecstal** [comment]
+1

**Comment by colinrcummings** [comment]
+1

**Comment by erichonkanen** [comment]
+1 please add this

**Comment by C0deZLee** [comment]
+1

**Comment by mayurjadhav** [comment]
+1

**Comment by nstanard** [comment]
+1

**Comment by dmlinaric** [comment]
+1

**Comment by tagliala** [comment]
Facebook updated this icon. Now users don't have human shape anymore
![image](https://user-images.githubusercontent.com/556268/33441948-33bd26ee-d5f4-11e7-9870-093df357d71c.png)

**Comment by erichonkanen** [comment]
@tagliala in a facebook future there are no humans

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=users-friends
