### ISSUE TITLE
Icon Request - Radio Tower

### ISSUE THREAD

**Issue by heatheralvis** [FortAwesome/Font-Awesome#2886]
Icon to represent cell or radio tower with indications of radio 
![cellphone-tower-photo2](https://f.cloud.github.com/assets/5124671/2151961/29572a28-9413-11e3-9dc1-878460c256ef.jpg)
![nyakrom_onetouch_cell_phone_tower_vodaphone](https://f.cloud.github.com/assets/5124671/2151962/295ee3c6-9413-11e3-9fcc-16e4573c8249.jpg)
![11086202-design-of-radio-tower-symbols](https://f.cloud.github.com/assets/5124671/2151963/296f1c0a-9413-11e3-9be8-c11f20aec74b.jpg)

waves.

**Comment by yieme** [comment]
+1

**Comment by gpablod** [comment]
Yes please! +1

**Comment by Lmpessoa** [comment]
+1

**Comment by tagliala** [comment]
This is a duplicate

locking here

🔒
