### ISSUE TITLE
Icon request: icon-user-minus

### ISSUE THREAD

**Issue by sepehrooo** [FortAwesome/Font-Awesome#2893]
Hi, 
It would be great if there was a fa-user icon with a little plus on top of it and another fa-user icon with a minus on top of it for use of following and unfollowing users.

**Comment by bnamestka** [comment]
+1

**Comment by tagliala** [comment]
we have http://fontawesome.io/icon/user-times/, let's rename this as `user-minus`

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-minus?style=solid
