### ISSUE TITLE
Icon Request: fa-sass

### ISSUE THREAD

**Issue by thotzl** [FortAwesome/Font-Awesome#2894]
from getbootstrap.com:
![sass](https://f.cloud.github.com/assets/1067907/2160166/56e719f2-94b4-11e3-88bc-caa79035380a.jpg)

**Comment by grnlightdotnet** [comment]
+1

**Comment by frensuren** [comment]
+1

**Comment by asiahoe** [comment]
+1

**Comment by jalcine** [comment]
+1 (not a fan of +1 but Sassify all of the things!)

**Comment by royduin** [comment]
For the time being, you can use a additional font: https://github.com/websiddu/technology-icons

**Comment by TMMC** [comment]
+1

**Comment by koenvanras** [comment]
+

**Comment by lffg** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
