### ISSUE TITLE
Icon Request: fa-human-resource

### ISSUE THREAD

**Issue by JDL747** [FortAwesome/Font-Awesome#2901]
Hello Font-Awesome Team,

First of all, I would liked to thank you for your great job. Since I have found your work, I keep using it in all my project.

I'm developing a web application and used Font-Awesome icons for the menu. I have a new menu to add but I can't find any icon representing it and actually I'm using an image.

Please find attached an image of the icon I would liked to used as a font.

![hr - icon](https://f.cloud.github.com/assets/3844254/2170602/b64e19f6-9570-11e3-8214-98118406cdd4.jpg)

Thank you very much

David

**Comment by MatthieuArzel** [comment]
I'd like to be able to indicate human ressources too 👍

**Comment by sledeunf** [comment]
same here :)

**Comment by tagliala** [comment]
Let's use #12060
