### ISSUE TITLE
Icon Request: icon-pi

### ISSUE THREAD

**Issue by cvkef** [FortAwesome/Font-Awesome#2922]
It would be nice to have icon for:
1. the Mathematical constant [π](http://en.wikipedia.org/wiki/Pi)

Anyways it would be nice to have more icons for unique letters from alphabets and some math symbols.

Thank you,
CvK

**Comment by ncareau** [comment]
+1

**Comment by lydianeher** [comment]
+1

**Comment by dickeysingh** [comment]
+3.14159265358979323846264338327950288419716939937510
   58209749445923078164062862089986280348253421170679
   82148086513282306647093844609550582231725359408128
   48111745028410270193852110555964462294895493038196
   44288109756659334461284756482337867831652712019091
   45648566923460348610454326648213393607260249141273
   72458700660631558817488152092096282925409171536436
   78925903600113305305488204665213841469519415116094
   33057270365759591953092186117381932611793105118548
   07446237996274956735188575272489122793818301194912
   98336733624406566430860213949463952247371907021798
   60943702770539217176293176752384674818467669405132
   00056812714526356082778577134275778960917363717872
   14684409012249534301465495853710507922796892589235
   42019956112129021960864034418159813629774771309960
   51870721134999999837297804995105973173281609631859
   50244594553469083026425223082533446850352619311881
   71010003137838752886587533208381420617177669147303
   59825349042875546873115956286388235378759375195778
   18577805321712268066130019278766111959092164201989...

**Comment by anderflash** [comment]
+1, and also fa-sigma and fa-integral

**Comment by dennisheinzen** [comment]
+3,14...

**Comment by stephanvierkant** [comment]
See #2828 (Icon Request: greek alphabet).  I suggest to close this request, since this is kind of a duplicate request.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pi?style=solid
