### ISSUE TITLE
Icon Request: icon-omega

### ISSUE THREAD

**Issue by cvkef** [FortAwesome/Font-Awesome#2923]
It would be nice to have icon for:
1. the Greek letter [Omega - Ω](http://en.wikipedia.org/wiki/Omega)

Anyways it would be nice to have more icons for unique letters from alphabets and some math symbols.

Thank you,
CvK

**Comment by lydianeher** [comment]
+1

**Comment by voltaicforge** [comment]
+1

**Comment by Disane87** [comment]
+ 1

**Comment by davidchase** [comment]
+1

**Comment by stephanvierkant** [comment]
See #2828 (Icon Request: greek alphabet)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/omega?style=solid
