### ISSUE TITLE
Icon Request: Plug.dj

### ISSUE THREAD

**Issue by Escendrix** [FortAwesome/Font-Awesome#2932]
I would like to request a social media icon for plug.dj.

Plug.dj is a site where you can take turns playing music (via YouTube and SoundCloud) with your friends. It is a relatively new site, you can read more about it here: http://blog.plug.dj/about/

This is an image of their logo that would be great for an icon:
![plugdjicon](https://f.cloud.github.com/assets/1279064/2214884/d07f9d72-99df-11e3-8ae3-55447dba66fa.png)

If this icon was recreated for Font Awesome, I would use it on my website (currently in development) as a social media icon and link it to my plug.dj room. I know it is not popular at the moment, but it's only going to continue to grow in popularity as time passes, so why not add it now instead of later :smile: 

Thank you for your consideration!

**Comment by tagliala** [comment]
+1 (https://github.com/FortAwesome/Font-Awesome/issues/3587#issue-34671942)

**Comment by Ariuw** [comment]
+1

**Comment by Fiiily** [comment]
Requesting "brand labels" tag.
+1

**Comment by xBytez** [comment]
+1

**Comment by aethior** [comment]
>plug.dj is shutting down. We have run into financial issues that result in plug.dj not being viable to keep running at this time. ([more info](https://twitter.com/plugdj/status/1359210486798114819))

cc/ @tagliala
