### ISSUE TITLE
Icon request: fa-list-check

### ISSUE THREAD

**Issue by wreleven** [FortAwesome/Font-Awesome#2965]
It would nicely complement fa-list, fa-list-ol and fa-list-ul. I would use it as a heading for a form or as an indicator for a series of checkboxes.

![fa-list-check](https://f.cloud.github.com/assets/242793/2253100/e50b8dd0-9db5-11e3-9a54-773a11fef071.png)

**Comment by buzzcloudau** [comment]
+1 - Left and right hand variants of this would be good as well. And fa-list-times.

**Comment by Macsch15** [comment]
+1

**Comment by MonsterKiller** [comment]
+1 This would be a really useful icon to have

**Comment by baalthazaar1** [comment]
+1

**Comment by metzuda** [comment]
+1 looking for exactly this, today!

**Comment by Vioner** [comment]
+1 me too! We need an icon for survey/pool/checklist (same thing as infographic)

**Comment by markmarco16** [comment]
+1

**Comment by joshi1983** [comment]
+1

**Comment by geeksmarter** [comment]
This would be awesome to indicate a survey. I currently use `fa-check-square-o` but a version of this feels more appropriate.

**Comment by sensibleworld** [comment]
This is now available in the latest release of our v6 Alpha for Pro subscribers: https://fontawesome.com/download
