### ISSUE TITLE
Icon Request: icon-scales

### ISSUE THREAD

**Issue by gluleci** [FortAwesome/Font-Awesome#2968]
icon for scales;

![expamlescales](https://f.cloud.github.com/assets/6782727/2257916/069e0ed0-9e21-11e3-8e26-f946499015d2.jpg)

**Comment by swarnamenu** [comment]
hello i have installed 4.4.0 ver but balance-scale icon is not working

**Comment by tagliala** [comment]
@swarnamenu please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Please do not comment here
