### ISSUE TITLE
Icon Request: icon-outbox

### ISSUE THREAD

**Issue by CharlesVien** [FortAwesome/Font-Awesome#2970]
It would be nice if you could make an icon that looks like the fa-inbox one:
http://gyazo.com/ece0f1baaded2af6ba4e1357a6384c93

But it would be for outbox/sent and it would look like this:
http://gyazo.com/af712a79175d513ca54009d1b475daa0

Thanks!

**Comment by MaklaCof** [comment]
+1

**Comment by StepanKuzmin** [comment]
+1

**Comment by boekkooi** [comment]
+1

**Comment by ananthu1987** [comment]
+1

**Comment by neil-morrison44** [comment]
+1

**Comment by dammina** [comment]
+1

**Comment by yarmenteros** [comment]
+1

**Comment by Harry5573** [comment]
:+1:

**Comment by rdehuyss** [comment]
+1

**Comment by yarmenteros** [comment]
+1

**Comment by r0dtaito** [comment]
+1

**Comment by skeets23** [comment]
+1 (why is no one giving a thumbs up to the OP???)

**Comment by fahmidur** [comment]
+1

**Comment by KHBOHM** [comment]
+1

**Comment by 1Map** [comment]
+1

**Comment by Sef1995** [comment]
+1

**Comment by MattiasC86** [comment]
+1

**Comment by btknorr** [comment]
+1 cannot believe it hasn't been added yet

**Comment by eflorit** [comment]
@btknorr It has been added, but it isn't free: https://fontawesome.com/icons?d=gallery&q=inbox-out
Not sure why they called it "inbox-out" instead of "outbox" though, but that's a different story.

**Comment by btknorr** [comment]
Ahhh...I see it now...thanks for the heads up.  Maybe this issue should be closed then?
