### ISSUE TITLE
Icon Request: fa-pause-circle, fa-stop-circle, outlined variants

### ISSUE THREAD

**Issue by sdelaney** [FortAwesome/Font-Awesome#2975]
Similar to the fa-play-circle icon which already exists, we are in need of a pause icon within a circle.  Our application currently uses these two icons to enable/disable an event from triggering. 

We have a few other icons in the same area which are all circular, so using the regular play/pause icons you already have does not really work for our use case.

I also think this could be very useful in other music/video applications as well - giving multiple options for play/pause button icons.

We are currently using something like this, but would really like to replace it with a font-awesome equivalent

![icon-pause](https://f.cloud.github.com/assets/2729239/2284966/4e4646da-9fcf-11e3-863c-9a7b99bd1524.png)

**Comment by fabswt** [comment]
FYI, this request, including mine and similar ones, might not relevant anymore since you can now [stack up icons](http://fortawesome.github.io/Font-Awesome/examples/#stacked) to achieve the desired effect. 

e.g.: http://jsfiddle.net/tsyrak/pce602g6/

It's not always perfect in terms of alignment and look but it's a nice feature to have.

**Comment by sdelaney** [comment]
Yes, but as you said, it s not always perfect in terms of alignment and look, so it is not an ideal solution.  Still hoping to get this in as a seperate icon eventually.

**Comment by sjswoboda** [comment]
+1

**Comment by breisamoralde** [comment]
+1

**Comment by mefernandez** [comment]
:+1:

**Comment by michaelrainerdocumatrix** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.
