### ISSUE TITLE
Support for 3D Transforms?

### ISSUE THREAD

**Issue by piperone** [FortAwesome/Font-Awesome#2977]
There's already support for 2D-transforms (through the use of fa-spin). Why not implement something similar for 3D-transforms? Just throwing it out there...

I made a quick'n'dirty fiddle demonstrating how it could be done here:
http://jsfiddle.net/f29fK/

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of version 6! https://blog.fontawesome.com/font-awesome-6-alpha-3/
