### ISSUE TITLE
Icon request: fa-d20

### ISSUE THREAD

**Issue by jesseflorig** [FortAwesome/Font-Awesome#2978]
This is actually more of an icon category request: Tabletop Icons or Gaming Icons

Polyhedral die - fa-d20, fa-d12, fa-d10, fa-d8, fa-d6, fa-d4
Polyhedral die outlines - fa-d20-o, fa-d12-o, fa-d10-o, fa-d8-o, fa-d6-o, fa-d4-o

I understand this could easily be a stand-alone project, but I thought I'd give it a shot here since I love Font Awesome so much.

Pictured example would be fa-d20-o.

Thank you!

![image](https://f.cloud.github.com/assets/2729384/2287158/b148fee8-9fe9-11e3-8037-255f8cb1e5f4.png)

**Comment by simplystardust** [comment]
:+1:

**Comment by bobbymeyer** [comment]
+1 on D20. Any and all platonic solids would be appreciated.

**Comment by manianiac** [comment]
+1

**Comment by twittv** [comment]
d20 at the very least

**Comment by sensibleworld** [comment]
We've finally added a d20, along with some companions: https://fontawesome.com/icons/dice-d20?style=solid + https://fontawesome.com/icons?c=gaming-tabletop
