### ISSUE TITLE
Icon request: post box.

### ISSUE THREAD

**Issue by friendlyweb** [FortAwesome/Font-Awesome#2984]
First off thank you  so much for the great work you guys are doing! 

I was wondering if you could either direct me to or create a post box icon.

![6778986-silhouette-of-two-post-or-mail-boxes-one-containing-letters-isolated-on-white-background](https://f.cloud.github.com/assets/1646569/2291063/4a0fa440-a032-11e3-966e-5b695e67aeb2.jpg)

Thanks so much for all your work once again!

**Comment by arefm** [comment]
+1

**Comment by ChristofferFurnes** [comment]
+1

**Comment by mabdulqader** [comment]
+1

**Comment by tagliala** [comment]
Sorry, closing here in favor of #2984, which has more +1s
