### ISSUE TITLE
icon request - fa tap

### ISSUE THREAD

**Issue by tonesg** [FortAwesome/Font-Awesome#2995]
I am building a plumbing construction site and have used the font awesome icons that I can included in my skin but need a few others that I will list here singly.  
A dripping tap would be perfect
![dripping tap](https://f.cloud.github.com/assets/6834850/2305941/d978701a-a273-11e3-8ee0-851fe10a2ca7.png)

**Comment by isjns** [comment]
+1

**Comment by swof** [comment]
+1

**Comment by aethior** [comment]
Hi @tonesg,

This icon was added in v5.12.0.
Check https://fontawesome.com/v5/icons/faucet-drip

Regards.

cc/ @tagliala
