### ISSUE TITLE
icon request - fa digger

### ISSUE THREAD

**Issue by tonesg** [FortAwesome/Font-Awesome#2997]
I am building a plumbing construction site at the moment using your icons which are great but only a few are appropriate.  I would love a heavy machinery icon like a digger. 
![diggericon](https://f.cloud.github.com/assets/6834850/2305948/61de28dc-a274-11e3-93f4-662a0f045589.jpg)

**Comment by tagliala** [comment]
Let's use #9380 (more upvotes)
