### ISSUE TITLE
Icon Request: icon-machine

### ISSUE THREAD

**Issue by shhdharmen** [FortAwesome/Font-Awesome#3010]

**Comment by Alplob** [comment]
I suppose that like me, he needed an icon to represent a piece of equipment/machine/asset... I suggest an icon representing a electrical motor like [that one](http://www.ebielectric.com/sites/24400/icons/motor-icon(1).png). I think such kind of icon would be really useful 😃

**Comment by tagliala** [comment]
@Alplob #4175

no feedback, closing here
