### ISSUE TITLE
Icon request: icon-python

### ISSUE THREAD

**Issue by drmuey** [FortAwesome/Font-Awesome#3016]
ditto w/ issue 3015 except change the URLs to http://www.python.org/community/logos/

thanks!

**Comment by SylvainCorlay** [comment]
+1

**Comment by goanpeca** [comment]
+1

**Comment by Carreau** [comment]
+1

**Comment by Carreau** [comment]
I came across [these](http://mfizz.com/oss/font-mfizz) ([on github](https://github.com/fizzed/font-mfizz)) a few years back.

**Comment by ccordoba12** [comment]
+1

**Comment by albop** [comment]
+1

**Comment by takluyver** [comment]
:+1:

**Comment by bollwyvl** [comment]
:snake:

**Comment by jasongrout** [comment]
+1

**Comment by damianavila** [comment]
:+1:

**Comment by jdfreder** [comment]
:+1:

**Comment by sccolbert** [comment]
:+1:

**Comment by ronanpaixao** [comment]
+9

**Comment by ChihChengLiang** [comment]
+1

**Comment by hoviousj** [comment]
+1

**Comment by TonyPythoneer** [comment]
+1

**Comment by christianhujer** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1391#issuecomment-57563643

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1391#issuecomment-47471826

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1391#issuecomment-42745671

**Comment by Macsch15** [comment]
+1

**Comment by 153957** [comment]
+1

**Comment by fernandofreamunde** [comment]
+1

**Comment by Maffblaster** [comment]
+1

**Comment by admix** [comment]
+1

**Comment by M-Padilla** [comment]
+1

**Comment by Benjamin-Lee** [comment]
+1

**Comment by Maffblaster** [comment]
+1

**Comment by vyscond** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by Harrison-G** [comment]
+1

**Comment by boolean-is-null** [comment]
+1

**Comment by jeremyramin** [comment]
+1

**Comment by wolfy1339** [comment]
:+1: 
Here's the svg version of the logo
![Python Logo](https://www.python.org/static/community_logos/python-logo-generic.svg)

**Comment by emboylen** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by HNKNTA** [comment]
+1

**Comment by cjaffar** [comment]
+1

**Comment by willseward** [comment]
:+1:

**Comment by jasonkhanlar** [comment]
+1

**Comment by TMMC** [comment]
+1

**Comment by woozyking** [comment]
:+1:

**Comment by baldwmic** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-python was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by rdab** [comment]
+1

**Comment by emmercm** [comment]
+1

**Comment by seanmhanson** [comment]
+1

**Comment by lukaskollmer** [comment]
+1

**Comment by Sruthik22** [comment]
+1

**Comment by eddy2525** [comment]
+1

**Comment by kbaikov** [comment]
+1

**Comment by wikier** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by chrismullins** [comment]
+1

**Comment by prahladyeri** [comment]
+1

**Comment by sjclayton** [comment]
+1

**Comment by sfischer13** [comment]
+1

**Comment by ssurve** [comment]
+1

**Comment by Onodric** [comment]
👍

**Comment by micahbyte** [comment]
+1

**Comment by micahbyte** [comment]
![python-icon](https://user-images.githubusercontent.com/8687283/28107781-35e1c1c0-66b7-11e7-8be6-9a0226df2e9d.png)

**Comment by snovd** [comment]
+1

**Comment by Abrunacci** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
