### ISSUE TITLE
Selectable icon on icon pages

### ISSUE THREAD

**Issue by psteinweber** [FortAwesome/Font-Awesome#3019]
I use Fontawesome a lot, especially in design tools like Sketch and Photoshop. Therefore I'm in regular need of selecting icons for copy and paste. It would be so great to have this on the icon page (e.g. [here](http://fontawesome.io/icon/btc/)).

I know about the cheatsheet, but why not consolidate usage possibilities on the single icon page?

**Comment by sensibleworld** [comment]
Closing this issue as it relates to an old version of Font Awesome. Let us know with a new issue if you're still experiencing issues. (You can now copy info directly from an icon page, and from the cheatsheet) Thanks!
