### ISSUE TITLE
Icon request: Empty shopping cart

### ISSUE THREAD

**Issue by DanielKulbe** [FortAwesome/Font-Awesome#302]
For online shops it would be useful to have an empty shopping cart

**Comment by flekschas** [comment]
I am wondering why this basic version has never been added? I would use it much more often than a shopping card with a plus or an arrow.

**Comment by WACMemphis** [comment]
+1 for an outlined/empty shopping cart.

**Comment by vanilla-thunder** [comment]
i would appreciate an empty cart icon, too
