### ISSUE TITLE
Icon request: icon-wedding-rings (marriage symbol)

### ISSUE THREAD

**Issue by larsbo** [FortAwesome/Font-Awesome#3025]
an icon with two rings: http://www.fileformat.info/info/unicode/char/26ad/fontsupport.htm

**Comment by blazeworx** [comment]
+1

**Comment by dsnl** [comment]
+1

**Comment by zacherytapp** [comment]
+1

**Comment by MayJow** [comment]
+1

**Comment by Danny-mcc** [comment]
+1

**Comment by shaunrainer** [comment]
+1

**Comment by Filipizaum** [comment]
+1

**Comment by phpniki** [comment]
+11111

**Comment by GwenLoguir** [comment]
+1

**Comment by wildfireheart** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by zarema-khalilova** [comment]
+1

**Comment by laviku** [comment]
+1

**Comment by oddityoverseer13** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by davidetrapani** [comment]
+1

**Comment by lyhil** [comment]
+1

**Comment by kfirba** [comment]
+1
 :D

**Comment by yvesrecour** [comment]
+1

**Comment by karenw993** [comment]
+1

**Comment by jm-code-com** [comment]
+1

**Comment by hCarmitchel** [comment]
+1

**Comment by alp06h** [comment]
+1

**Comment by NBillings707** [comment]
+1

**Comment by ijakic** [comment]
+1

**Comment by karmac2015** [comment]
+1

**Comment by pRob3** [comment]
+1

**Comment by yousifalraheem** [comment]
+!

**Comment by freedude** [comment]
+1

**Comment by favourafolayan** [comment]
+1

**Comment by easaw** [comment]
+1

**Comment by joshua-villing** [comment]
+1

**Comment by Marek00Malik** [comment]
+1, are those suggestions even viewed by fa authors ???

**Comment by lenasimoes** [comment]
+1

**Comment by lenasimoes** [comment]
@larsbo the request is missing some info required in the template for new icons:

### What can it be used for?
For indicating marital status.

### Example image
Single / Married / Divoced / Widowed
![example - quick draw I've made](https://user-images.githubusercontent.com/12610282/40011341-eb6e36b0-577d-11e8-87fe-b5d7bb7f666c.png)

### Icon request checklist
- [x] Icon group
- [x] The title starts with "Icon request: " and is followed by the requested icon name
- [x] I have searched for existing issues
- [x] I have included at least one example image if it could be helpful
- [x] The request is for a concrete object

**Comment by larsbo** [comment]
@lenasimoes the request is 4 years old. I think there was no issue template at that time 😃 
And I guess nobody waited all the time for this icon. But good luck for your work and thank you for your issue improvement. I will update my initial request 👍

**Comment by sensibleworld** [comment]
We've added this icon to the latest release of Font Awesome Pro: 
https://fontawesome.com/icons/rings-wedding?style=solid

**Comment by larsbo** [comment]
and it didn't even take five years! This is font ~~awesome~~ premium! 🙄

**Comment by santoshandrei** [comment]
Before you plan to build your own diamond ring or **[design your own engagement ring](https://www.hellodiamonds.com/blog/how-to-buy-a-diamond-engagement-ring/)**, it is important to have a clear idea about 4C that dominates the market Color, Clarity, Carat and Cut.

**Comment by santoshandrei** [comment]
The **[Engagement Rings](https://www.bendavidjewelers.com/blog/get-best-engagement-ring-for-your-loved-one)** can not only be bought based on their beauty and price, but there are many aspects you should consider before purchasing it.

**Comment by santoshandrei** [comment]
If you are looking for something that can match your taste and style, then you can go for an option to choose your own ring style and **[build your own diamond ring](https://www.hudsonpoole.com/blog/top-3-benefits-of-designing-your-own-engagement-ring/)**.

**Comment by santoshandrei** [comment]
Diamond is the very first choice of every wedding couple. If you are one of them, then you must include **[Diamond Bands](https://www.preferredjewelersinternational.com/blog/make-your-wedding-day-more-special-by-wearing-diamond-wedding-bands/)** in your ornaments list.

**Comment by santoshandrei** [comment]
If you know diamonds are what you’re shopping for, make sure you know where you stand on the 4 Cs. Decide on a budget and a general style direction, and you’ll be ready to get **[Engagement Ring](https://www.romanjewelers.com/blog/engagement-ring-ideas-featuring-gabriel-co-designs/)** shopping!

**Comment by santoshandrei** [comment]
While many men prefer **[diamond wedding bands](https://www.sachsjewelers.com/blog/tips-on-how-to-buy-a-diamond-wedding-band/)** to gold rings, but is it worth to wear. Find how to buy women’s diamond bands and men’s diamond bands.

**Comment by santoshandrei** [comment]
Once you have narrowed down your preference, you can filter the various options available in the market. You can either **[build your own diamond ring](http://www.shopmaharajas.com/blog/how-to-buy-the-right-engagement-ring-for-men/)** or choose your own ring styles.

**Comment by santoshandrei** [comment]
The most popular kind of mother’s jewelry is a **[stackable mothers ring](https://www.slateandtell.com/blog/all-you-need-to-know-about-your-mothers-jewelry/)**. It includes the birthstone of mother and father as well. Some people believe in engraving the children’s names too on the ring.

**Comment by santoshandrei** [comment]
With changing trends, find different varieties of best **[diamond rings for engagement and wedding](https://www.trueromancebridal.com/blog/how-to-buy-diamond-engagement-ring-couples)**. It is so confusing to select just one from all beautiful rings.

**Comment by santoshandrei** [comment]
When you decide to design your own engagement ring or create your wedding ring, you made the perfect choice for a unique handmade wedding band and an **[engagement ring](https://www.vanscoydiamonds.com/blog/top-5-tips-to-create-and-design-your-own-engagement-ring/)**.

**Comment by santoshandrei** [comment]
To choose the right diamond anniversary or **[wedding bands](https://www.warejewelers.com/blog/how-to-choose-an-engagement-ring-that-matches-your-partners-personality/)**, consider what fits well into your spouse’s lifestyle and her personality.
