### ISSUE TITLE
Icon request: Australian Dollar (A$) & New Zealand Dollar (NZ$)

### ISSUE THREAD

**Issue by p2made** [FortAwesome/Font-Awesome#3028]
Being Australian I come with biases...

When working with different currences in one space there is a need to be explicit where multiple countries have currencies of the same name. For the Dollar that means representing the Australian Dollar as `A$` & New Zealand Dollar as `NZ$`. When being so explicit the United States Dollar is `US$` (surprise surprise).

It's nothing to prefix with the letters in text but the result is messy when using icon fonts.

**Comment by lukeoliff** [comment]
I was able to do this with the following;

````
.fa-aud::before {
    font-family: "Montserrat",​Arial,​sans-serif;
    content: "A";
}

.fa-aud::after {
    content: "";
}

.fa-nzd::before {
    font-family: "Montserrat",​Arial,​sans-serif;
    content: "NZ";
}

.fa-nzd::after {
    content: "";
}
````

**Comment by tagliala** [comment]
Please open individual requests for non-symbolic currencies filling out [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

You can also edit this request and open a new one for NZ$
