### ISSUE TITLE
Icon Request: mediablasting, powder coating, Cerakote

### ISSUE THREAD

**Issue by ByrneLogic** [FortAwesome/Font-Awesome#3030]
I am currently building a website and would like to have some custom Font Awesome Icons created. 
Here is the url to my site and work in progress http://new.byrnecoatings.com/powder%20coating/

The icons I would like to be changed are the ones for the categories "Media Blasting" "Powder Coating" "Cerakote" 

For the "Cerakote" Icon I would like to use something similar to this as Cerakote is applied by using a spray gun.

For the "Powder Coating" Icon I would like to maybe create something similar to the attached image gema optiflex2-gun-b (small)[2].jpg

For the "Media Blasting" Icon I would like to also maybe create something similar to the image located here http://graphicriver.net/item/sandblaster-sand-blaster-woodcut-retro/5894358.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I was waiting for feedback from the community here but the request didn't get traction.

I'm going to close here

You can still open new individual request, but please make sure that they follow our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
