### ISSUE TITLE
Icon Request: Star of Life

### ISSUE THREAD

**Issue by peelman** [FortAwesome/Font-Awesome#3036]
New issue as requested in #2593 

Star of life:

![](http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Star_of_life.svg/100px-Star_of_life.svg.png)

**Comment by patsplat** [comment]
SVG versions of this icon:
- https://commons.wikimedia.org/wiki/File:Star_of_life.svg
- https://en.wikipedia.org/wiki/File:Star_of_life2.svg
