### ISSUE TITLE
Icon Request: urbanspoon

### ISSUE THREAD

**Issue by adamPyburn** [FortAwesome/Font-Awesome#3039]
hey, i'm making some restaurant sites and have a request for an urbanspoon icon to add to social media links. if you can fit this into your font awesome catalogue it would be awesome!
many thanks,
Adam

![urban spoon](https://f.cloud.github.com/assets/6378893/2361118/76b7abcc-a62d-11e3-9099-fdbd1fa6cd82.png)

**Comment by zlorenz** [comment]
Agreed! I've had 3 website clients in the restaurant/food industry that want to send traffic to their Urbanspoon account via an icon link.

Adding this would be much appreciated!

**Comment by aethior** [comment]
>Zomato discontinued the Urbanspoon website on June 1, 2015, redirecting Urbanspoon traffic to Zomato servers; at the same time, Urbanspoon's logo was incorporated into a new Zomato logo. ([more info](https://en.wikipedia.org/wiki/Urbanspoon))

cc/ @tagliala
