### ISSUE TITLE
Icon Request: Add file

### ISSUE THREAD

**Issue by NinjaDev06** [FortAwesome/Font-Awesome#3041]
I need an icon representing the addition of a file.

This is what I made by the combinaison of "fa-file-o" and "fa-plus-circle".

![addfileicon](https://f.cloud.github.com/assets/1877413/2363293/ca0ca2d8-a64a-11e3-922c-432773cdf67b.png)

**Comment by aethior** [comment]
Hi @NinjaDev06,

This icon was added in v6.0.0.
Check https://fontawesome.com/icons/file-circle-plus

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to Font Awesome pro

Free users, **in a web application**, can achieve this icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/31/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
