### ISSUE TITLE
Icon Request: (Brand Icon) fa-wikipedia

### ISSUE THREAD

**Issue by thediveo** [FortAwesome/Font-Awesome#3057]
I regularily link to Wikipedia articles for definitions and explanations of the terms I use in my TiddlyWikis and other hypertext documents. I would like to provide a visual clue with these links so that readers immediately know that the link would take them to Wikipedia. For this, I would consider a Wikipedia brand icon "W" to be useful, also of broader usage outside my documents.

The brand icon should follow the well-known "VV" style of the Wikipedia W brand. In addition, making it a circled icon would probably make it better recognizable as not being a plain "W" but a Wikipedia W.

![wpedia icon](https://f.cloud.github.com/assets/6920158/2386910/001b8e14-a931-11e3-90e3-fa19abb9773f.png)

**Comment by xandr91** [comment]
+1
