### ISSUE TITLE
Icon Request: paper-cup

### ISSUE THREAD

**Issue by chryton** [FortAwesome/Font-Awesome#3068]
Uses:
- Where the shorter coffee cup icon would not be aesthetically pleasing and a more vertical icon would fit better
- Coffee shops, cafes, beverage service, catering
- Iconographic signage
- More synonymous with coffee than the coffee cup (which can be construed to be a tea cup; though both you can have tea in...)
- To show a "To Go" or on the move culture/feeling that a cup and saucer don't convey
- Could be rolled into https://github.com/FortAwesome/Font-Awesome/issues/1895

Examples:
- http://lbultman.files.wordpress.com/2010/11/6088paper_coffee_cup.jpg
- http://www.blogadilla.com/wp-content/uploads/2008/06/not-paper-cup.jpg

**Comment by chryton** [comment]
@sensibleworld Thanks for releasing this; I had forgotten that I had made the issue! Disappointing they are all pro since this request has been around for so long; I'd have thought the solid one would have at least been in the free release. Any plans to make that happen?

**Comment by sensibleworld** [comment]
@chryton We're always open to re-considering what goes in Free v. Pro. But we typically prioritize new Free icons by number of requests and interactions.
