### ISSUE TITLE
Icon request: icon-mozilla-persona

### ISSUE THREAD

**Issue by Xion** [FortAwesome/Font-Awesome#307]
Browser ID (http://www.browserid.org) is an authentication provider launched and maintained by Mozilla. For pages that support it, it would be great to have a custom icon for it, just like we have Facebook, Twitter and Google icons.

As for how it should look like, I think the pentagonal "ID" badge would be simplest, and best.

**Comment by zudov** [comment]
+1

**Comment by LauritzT** [comment]
+1
![Persona Logo Orange](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAMzUlEQVR4nO3df4xlZ13H8TE2SLA2SywRZKXVVOVH1YDFrjvP9+wpxYpmVTCtNoKkTapgYXHa+zzPzFajV2uoWkmDEDbpBqtW3ULVqjSsoTRglljrD1pocKEbHGDueZ7prO2Ca6hk0PGP3Umq7XZn5p5zPs+d+34ln//3fJ7PPZ3O3HvPzAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANvKKNY7l7yrSZkZxXqneiPYZlaur8/NwQ6kYMdTsDVSdBZXQv1C9WawTSz73RenYIsFDJtsMDlUD6xcX5+r3g4mXBrsviBFu1c9aLKlHDi279Lz1BvCBGu8GxYwZLLluFvUG8IEy7H6sH7EZIx8LXmbU+8IEypFO1nAiMl4WV3yrlZvCROogPGSFpKDfSoF9zr1njBh1MMlrd4E7k9x9hL1pjBB1KMlbaf6YF6oL1TvChNCP1jSQd63MuQ9AtiAAsZKuki031RvCxNAPlTS1Q3gyeTdO9T7QuHkQyWdpfFulHz1c+qNoWDqkZKubwL2cArVFeqdoVDqgZIebgLBPpqCvUq9NRRIPU7S203grifm3UvUe0Nh1MMk/SUH995lf8U3qzeHgqhHSXq+CcRqqN4cCqIeJOk9X83R3q7eHQpRwCBJ//nS8rxdrd4eClDAGIki0T7ZDGZ/RL0/iMmHSISpPtLcWL1SvUEI6UdIpIl2ZG1Yn6PeIUTkA+x/8CdTsDtHA7ty2e++OA3q89e7GMV6Z4qzl6Rg16Vg96Vgq/J/bz+5U7lBCBUwvr5yYhTtrYvD+rkb7mZQn5+i3TYNN4LGu2GHM0Op1MPrIznaoXEepHHqp4LqIfV1dB5vb2pzW5gA8tF1m/9KofrVVnoavOaCHKr3F3BNXeYLTah+to2+MCEKGF1X+Y8cLbTZ1anfEdjtBVxbd4n2z6Nol7fZGwomH1xHaULlu+hrbVifk079glB+jd3FHV2cq3d00R8Kox9bFy9+uyMNf/B5XXWWo/1QCvag+jo7vgn86b//ymte3FWHKIR+aK3nwRTrzr8aO3l7UxPsRAHX21189e61fT/2TV13CSH5yFrOKNg1fXWXg92hvt7u+2znl6golHpgLecTeb+9oK/uctxzWdr2PwXYyRzsl/rqFD2TD6zF5FgN+u6vmYKfAlKwxRzcVX13ix4UMK62cmIz7/Jrrb+BcwVcex/JSzfUF/XdLzpWwLBaSRPdBxT9PT689LwU7LPq6+8ph5e8fb+iZ3SkgFG1cwMIFmUdevtj9fX3mDu/FGe/XdU1WlbAoFqJ8t1rOdrb1dffa6Ld9pnhK56j6hstko+pnawqO1z2uy8uoIOeUy0oO0dL9ENqI+6ossMvzNmLUrCv63voNV8ZDeytyt7RggKG1EY+VkCPXyygh77z+dHArlR3jzEUMKKxk6MdUvfYhOoBdQ+iPJi9q9X9Y4sKGND4N4BgtxbQ4z3qHnRxR1eur89VnwG2QD+esfNEDrZH3WMe2JUFdCFLDtUfjfOtSxBRD6eF3KPucF2e3v8NWM9B9RlgkwoYzVhpvJtXd7guB/t9dR8F5Cb1OWATChjMWCnpEVc5VF7dRwE5kaL7RfVZYIMKGMx4idUb1R2uS8FukvdRQHK0YylWP60+D2yAeizjx92s7nBdDnaXvo9i8g9pvqrUZ4KzKGAo48Xb3eoOZ2ZmZj4zfMVzUrB/lfdRUrzdmwf2cvXZ4FnIRzJ+jpfwN+hRnN1VQBcl5jDPHixYAQMZOznY7yg7PH6TvSiH6m/UPZQb93sfvOqqb1SeEc5AP45W8rjyl07Zu18voIPCw6cHi6QfRmsDe0jRX16oL0xT8PDQFrKaor1ecUZ4FgUMo7U03r229/6i7Vdf96SkCfboY9wEyqIeRauJ9k5Bf4fl1z1BycH+PoVZ6/uccAbqQbScpT67G8V6ZwHXPIGpHinhLzeY2XY3gLXc45OBUqx+S329k5oc7Q/6fIgLzkA9hA5y+Ni+S8/rurel+er70vR8HXgnydF+d21m5hu6Pis8C/UIOsp1XfeWYzUs4DonPiV9mnMqqQfQTdzRLp8SlBfqC1O0k/rr3BZZHQW3t6uzwlkUMIBO0tW7Axfn6h2Nt0Pq69tm+Wzj7ae6OC+cRQGH31VWR3F2V9t9NXzmv6No3sg19fQH32GiHWmCzbbVVePdtclbkl/Xtos72sTqJ9s6J2yC/vC7TQ721ylWLxu3pzxf/Uz2dkx9PdswKzm6a9vYMraggAF0nhztPWP3xC/9Osko8nQhKfUA+kgOdkcLPZ1QX8f2i7uljQ1jDPoRdB9uAAUm2u1fXnDPb2PDGIN8CD2EG0Bpqf5yKVTf3cZ+MSb9GLoPN4CC4u3vuvjzLLZIPoge0tINgC/9GDfRTqZB/dI2douWyEfR7eA+18RqeHy/+55xexrF2ctSsANNsCfk1zWZyTm4N7exWbSogGG0nSdTsPuaUPkuHlaZBvVLl4O7OYXqnwq41klK5x/QwhYUMIw2cjwFOzgKbm+fXzSxEuoXNt6uTsEOnv43qHsoNPy5r1j6cWw5J1Kwg0ve1SV87/zasD5nFNzeHO3udOqnEHU/RSTHMh7cgjNQD2TTgwrVA423q7v8uO+40qA+/9SHhqpH1H1JE+0IX/1VOPlINvrCj3Zo2e++WN3XZo3i7K4U7Yi6P8F5HevidzBomXooZx9S9eHGl/MI8K1YHNbPTb56Sw7VA+o++0gT7FNLwb1O3Ts2QD2Ws+RgCf9/35bFuXrHFPw0sLrkXa3uGhtUwGDOlD9buuGHX6zup215sOfVKdjHC+i3izyZvHuHumNsQgGjeVpysPtTsFepu+nKcnB7m234jcJNsN9Qd4tNUo/mmTINP0Imb3PqnlvOnepOsQUFDOf/5x51J31Y9tV3Nt4eLqDvsZOjHUrz7iXqTrEF6vE8bUyhmpr3i2+Px4pXH2lurF6p7hJbpB/QU1/89tHHe3iqTylGN7ofSMH+Td37GPkXxROZ0aICRvTU/5osqPvoW44T+4yB1TRwTt0fxlTAkJ56A7hC3UffUqh+Wd/7pvOfObrr1d2hBQWMaT2Lo/2Xf6u6j76lQVUV0P2m0gT7NXVvaIl6TE/Jn6u7UFgZ1uc2wR4toP+NxVfvXrym3A9iYZPkg1pPtP3qLlRysLvk/W8sf7Id35051QoY1VoK0/HmnzNpvJuAR427o4tz9Q51V2iZfli2loL9z9IN9UXqLlRSrN5YwBk8W/4xxz2XqXtCBwoY11qK9jl1D0qjOLtLfgZnzudztCvVHaEjBQxsLUe7V92DUt5nL0jBvqI+h2fIl5Ov3qLuBx0qYGStPLxz0qXgjqrP4emZvjdmTR39yGytCdXb1D2oJW93q8/h/yTau7bTl7HgDORDC7aWBvaj6h7Usq9+W34Op5Oj/eFjN13+bepO0AP52IJ9/bEF913qHtSSt19Qn8Xp8/hQHtjL1X2gJ+rBpWBZ3UEJCvlLQB7Feqe6C/RIPrpof6vuoARpsPuCJHwAaRPs0eTdG9Q9oGfqG0AOdkDdQSlSsCw6h9UU7fXq64eA+gaQgp04/QSd+3KwO3KwW0+/Nfa6xtvVS97VS97VaeBcXqgvXE/JT5xZnKt3rP87l26oL1q/hsa7146CXZO8zTXeDXOwAznYh1KoHkrBFpPqJwBvc+rOIFLADaCtLJ1+ESkysQ8G5T0YU049QCJ88Yfq/WlQn6/eIITUIySy/FUTZ79XvT+IFTBE0neiHXlsvtqt3h4KIB8j6TfeHV2e3/MT6t2hEPJBkj6z0nh3rXpzKEgBoyS9xP13Eyqv3hsKox8m6ekGcIt6ayiQfpik80S7/YsL7vnqraFA8nGSbuPdX0zz9y3iLOQDJV3m48veXareGApWwEhJB8mheiSH6sfV+0Lh1EMlHbz4o6UU3c+rt4UJoB4raT1fS5FP92GDChgsaTHLwd2s3hQmiHqwpL3kYO87Hme/Rb0pTBD1aElLiXZkcchTe7FJKdin5eMlY6UJdn+Ks5eot4QJ1EzOo6nJM734vT3McxWwZaPg9qpHTLac1Wl+rDpakry9q4Axk83lq02wfertYBtobqy+I3l7Zwp2ooBhkw0kx2qo3g22mVGc3ZWD3ZqCHU7BPkYKTbTb1FsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABl+F8wHCsqde9o9QAAAABJRU5ErkJggg==)

**Comment by skddc** [comment]
@LauritzT Look at my submission. You can import that to your font in e.g. the IcoMoon app.

https://github.com/FortAwesome/Font-Awesome/issues/307#issuecomment-13609700

**Comment by LauritzT** [comment]
@skddc But if you don't wan't to use IcoMoon it's the best alternative we've got.

**Comment by skddc** [comment]
It's just a vector graphic. You can use any tool you want to import it or turn it into an SVG.

**Comment by aethior** [comment]
>It was launched in July 2011, but after failing to achieve traction, Mozilla announced in January 2016 plans to decommission the service by the end of the year. ([more info](https://en.wikipedia.org/wiki/Mozilla_Persona))

cc/ @tagliala
