### ISSUE TITLE
Icon Request: icon-electricity

### ISSUE THREAD

**Issue by MatPreuter** [FortAwesome/Font-Awesome#3072]
I work for serveral energy company's and would like thie realy awosome fonts.

**Comment by goetzc** [comment]
The bold icon could be useful for high voltage related things, but what about switches, sockets and (audio) plugs?

**Comment by tagliala** [comment]
no feedback, closing here

@goetzc if you want to request an icon, please open a new request following our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
