### ISSUE TITLE
Icon Request: shopping-basket

### ISSUE THREAD

**Issue by andymb** [FortAwesome/Font-Awesome#3074]
In the UK we don't use shopping carts, we call them trolleys and to a number of people that distinction matters.  So on e-commerce sites, we tend to have "Your basket" rather than "your cart."

It would be great for font-awesome to support that choice by offering a basket icon.

This sort of thing: (these particular 2 icon files are Linkware, with a backlink to http://www.visualpharm.com required - I have no affiliation, they are just the first that came up when I googled for "basket icon")

![shopping-basket-512](https://f.cloud.github.com/assets/6523473/2420108/60e05e42-ab6a-11e3-93fb-f9065a0a1c19.png)
![ecommerce-shoping-basket-icon](https://f.cloud.github.com/assets/6523473/2420109/68aa513c-ab6a-11e3-845c-ddaf17439bbd.png)

Why don't e-commerce sites just use "trolley?"  I think it's because physical trolleys have an association with supermarket shopping: Almost all other shops use baskets.  An unscientific poll of a few friends came up with 2 associations for "trolley."  "Supermarkets" and "they never work properly." [Paraphrased to keep the conversation polite.]

**Comment by gertruda88** [comment]
+1

**Comment by jakubhrdy** [comment]
+1
