### ISSUE TITLE
Icon Request: icon-rock

### ISSUE THREAD

**Issue by todoconk** [FortAwesome/Font-Awesome#3077]
![genre-128](https://f.cloud.github.com/assets/2256091/2425740/0fa68722-abba-11e3-8631-17b7cd80f25f.png)
I'll use on button like FacebookLike but this means Rock!
This represents as the best

**Comment by javenosa** [comment]
+1 on this!
You can use your "fa-hand-spock-o" with a slight modification to achieve the idea.

**Comment by aethior** [comment]
Hi @todoconk,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/hand-horns

Regards.

cc/ @tagliala
