### ISSUE TITLE
Icon request: radar chart

### ISSUE THREAD

**Issue by disinformatique** [FortAwesome/Font-Awesome#3101]
I would like to request an icon for the Radar Chart. I am designing a new UI for the company I work for and have used FontAwesome for the icons in the UI. 

Here is a small example of what I am requesting. For copyright reasons I cannot upload the new UI but I am posting a graphic from the developer's point of view. 
![radar](https://f.cloud.github.com/assets/1703687/2457197/db02c790-af30-11e3-93b5-284aecdb2978.jpg)

Please add new icon , web application icon label to this issue please.

**Comment by evanlemke** [comment]
+1

**Comment by kkirsche** [comment]
+1

**Comment by kneeki** [comment]
Sorry for the resurrection, but was this (or a similar) icon ever implemented?

**Comment by tagliala** [comment]
@kneeki unfortunately no, it isn't :\

**Comment by kneeki** [comment]
Awe, bummer. :(

**Comment by waitingkuo** [comment]
+1

**Comment by davidhantson** [comment]
+1

**Comment by tomprats** [comment]
+1 Similar to https://github.com/FortAwesome/Font-Awesome/issues/4269 but I like the icon in this issue

**Comment by gjavi1** [comment]
:+1:

**Comment by JMBratten** [comment]
+1

**Comment by Krevo** [comment]
+1

**Comment by kevinbalicot** [comment]
+1

**Comment by Niafron** [comment]
+1

**Comment by jubianchi** [comment]
+1

**Comment by leonardodelfino** [comment]
+1

**Comment by JackMstry** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by elyesjrad** [comment]
+1

**Comment by tagliala** [comment]
There is a chart radar icon in FA6 Pro: https://fontawesome.com/v6.0/icons/chart-radar?s=solid
