### ISSUE TITLE
Icon Request: flower

### ISSUE THREAD

**Issue by daisylady** [FortAwesome/Font-Awesome#3103]
I would like to request the addition of a daisy flower. My website daisyparadise is entirely dedicated to daisy flowers and the icons currently available lack sufficient icons for horticultural websites, apart from the icon called leaf. There are a lot of gardening websites and gardening related icons would be helpful, such as watering can, spade, seedling, greenhouse, shovel, hose pipe, etc. Thank you!

**Comment by tagliala** [comment]
duplicate of #2037, please +1 that request
