### ISSUE TITLE
Icon request: icon-child-female

### ISSUE THREAD

**Issue by connecteev** [FortAwesome/Font-Awesome#3106]
Similar to
http://fontawesome.io/icon/male/
http://fontawesome.io/icon/female/

except for baby boy and baby girl
http://www.dafont.com/boy-characters.font
http://www.dafont.com/girl-characters.font

**Comment by urmaul** [comment]
How about this?
![children](http://thumb10.shutterstock.com/photos/thumb_large/235588/235588,1221241754,16.jpg)

There's already a "child" icon good enough for a boy. You can add a dress to make it a girl - same difference as in male/female icons.

**Comment by tagliala** [comment]
I suppose we have a child icon: https://fontawesome.com/icons/child?style=solid

Let's rename this  to child-female

**Comment by aethior** [comment]
Hi connecteev,

This icon has been added in v6.1.1.
Check https://fontawesome.com/icons/child-dress

Regards.

cc/ @tagliala
