### ISSUE TITLE
Icon Request: USA states/territories

### ISSUE THREAD

**Issue by iamkevinjohnson** [FortAwesome/Font-Awesome#3108]
Minimalist, but recognizable, renderings of each state/territory of the United States would be very useful.  Thanks

**Comment by wael101** [comment]
what about generic icon like #9225

**Comment by tagliala** [comment]
Don't know why it is open. 

Closing here because of #3992.

Please use https://github.com/FortAwesome/Font-Awesome/issues/3108#issuecomment-39349234
