### ISSUE TITLE
Icon Request: icon-quantity, icon-scale

### ISSUE THREAD

**Issue by alansferreira** [FortAwesome/Font-Awesome#3113]
icon-[quantity, amount...]
icon-[scale, measure...]

thank you... and congratulations this css is awesome

**Comment by kenderson** [comment]
+1 - Example of what seems to be standard for quantity: http://www.shutterstock.com/pic-186320855/stock-vector-exposure-photo-camera-sign-icon-quantity-of-light-settings-rounded-squares-buttons-vector.html?src=wfQHMx2ps_whulA8PJRrTA-1-1&ws=0

**Comment by sensibleworld** [comment]
Going to close this, as I think we have a number of icons (certainly in version 6) that fit this description. Let me know if we don't have still don't have suitable icons though.
