### ISSUE TITLE
Icon Request: Circle Navigation Icons

### ISSUE THREAD

**Issue by madhusharma** [FortAwesome/Font-Awesome#312]
Font Awesome has an excellent icon-play-circle icon.

It would be nice if there were icons like this which had up/down/left/right arrows to use as navigation icons. (e.g. if the  icon-play-circle icon was rotated 90, so the arrow was pointing downwards, it could be used for a drop down menu.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&c=arrows
