### ISSUE TITLE
requesting for icons

### ISSUE THREAD

**Issue by Almajority** [FortAwesome/Font-Awesome#3120]
here a must have list icons:

1- icon-car
2- icon-tree
3- icon-gun / icon-pistol
4- icon-shopping-cart-empty / icon-shopping-cart-full
5- icon-motorbike
6- icon-wheel
7- icon-pcb (printed circuit board)
8- icon-processor
9- icon-gadget

thanks

**Comment by rosihan16** [comment]
+1 for icon-gadget (combination of phone, tablet ,and laptop icons )
