### ISSUE TITLE
Icon request: clapperboard / clapboard

### ISSUE THREAD

**Issue by alerom84** [FortAwesome/Font-Awesome#3130]
Hi!
I think it would be great if you can add the clapperboard icon in Font Awesome.
It can be used to suggest film direction, video production or other issues related to filmmaking.
Something like this:

![photo-video-clapperboard-icon](https://f.cloud.github.com/assets/7048736/2501234/2c9a4e24-b36a-11e3-8fd1-f0617895c82a.png)

Thanks a lot!

**Comment by joms** [comment]
+

**Comment by ajhalls** [comment]
Yes please, it is a great idea to tie into animation sequences, video, and so on.

**Comment by d70rr3s** [comment]
+1

**Comment by dieulinh** [comment]
+

**Comment by dieulinh** [comment]
+1

**Comment by kaihuchen** [comment]
this is great for indicating that a video is live.

**Comment by kaihuchen** [comment]
+1 this is great for indicating that a video stream is live

**Comment by andreaslarssen** [comment]
+1

**Comment by timosadchiy** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by gyetvan-andras** [comment]
+1

**Comment by moviesound** [comment]
+1

**Comment by jami-do** [comment]
+1  Have been waiting for this icon a long time! Hopefully we'll see it soon.

**Comment by andritanuarto** [comment]
+1

**Comment by Getterac7** [comment]
+1

**Comment by d-mouse** [comment]
+1 would use it for "Scenarios"

**Comment by mrwunderbar666** [comment]
+1

**Comment by kappaknight** [comment]
+1

**Comment by Dhana-plantsight3d** [comment]
is this icon already added? if so ,name please.

**Comment by SuperPat45** [comment]
+1

**Comment by ddubthekid** [comment]
+1

**Comment by danielfowler** [comment]
+1

**Comment by brandbrilliance** [comment]
+1

**Comment by fabswt** [comment]
+1, a classic!

**Comment by fpstidston** [comment]
This used to be absolute staple of multimedia icons

**Comment by TroyDota** [comment]
why isnt this added yet?

**Comment by sensibleworld** [comment]
This has been designed and will be in the next alpha release of Font Awesome 6.

**Comment by shaedrich** [comment]
This one is closer to what is actually used (board with something table-ish):
![image](https://user-images.githubusercontent.com/11225821/103483961-51cd6280-4deb-11eb-99a8-ea216d68653a.png)

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
