### ISSUE TITLE
Icon request: icon-tripadvisor

### ISSUE THREAD

**Issue by dalmanoemi** [FortAwesome/Font-Awesome#3145]
I would like to request a tripadvisor icon for a webproject I am currently working on. I would include it as a social icon.

Thanks in advance!

![tripadvisor](https://f.cloud.github.com/assets/7071002/2526068/4aa7dd04-b4f6-11e3-9a20-24a16ef5d886.jpeg)

**Comment by crissrocca** [comment]
brilliant!
