### ISSUE TITLE
Icon request: icon-milestone

### ISSUE THREAD

**Issue by Subbu033** [FortAwesome/Font-Awesome#3151]
It would be great if Font-Awesome have icon for my Milestone image! Please see my image below.

![milestone](https://cloud.githubusercontent.com/assets/7078175/2534245/3a99be24-b577-11e3-8541-e8729102adac.png)

**Comment by ahmerkureishi** [comment]
+1 for fa-milestone, @tagliala

**Comment by vpratti** [comment]
+1 this would be really helpful

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/sign-post?f=classic&s=solid
