### ISSUE TITLE
icon request: Donate us icon

### ISSUE THREAD

**Issue by santhoshjack** [FortAwesome/Font-Awesome#3157]
Box has hole at centre with hand putting a dollar into that box

**Comment by sensibleworld** [comment]
Released in 5.0.9

**Comment by tagliala** [comment]
International versions of "donate"

https://fontawesome.com/icons/hand-holding?style=solid
https://fontawesome.com/icons/hand-holding-heart?style=solid
https://fontawesome.com/icons/hands?style=solid
