### ISSUE TITLE
Icon Request: pagebreak

### ISSUE THREAD

**Issue by brandonkelly** [FortAwesome/Font-Awesome#3161]
Hey Dave,

I humbly request that you add a new “pagebreak” icon to go along with FA's wonderful set of text editor icons.

Here's what they generally look like:

![screen shot 2014-03-28 at 6 05 32 am](https://cloud.githubusercontent.com/assets/47792/2549669/bc0738a8-b679-11e3-991e-b5be646f6a89.png)

Thanks for everything!

-Brandon

**Comment by marvc1** [comment]
+1

**Comment by tagliala** [comment]
sorry, closing here in favour of #5153 which has more +1s
