### ISSUE TITLE
Icon Request: icon-footsteps (shoe prints)

### ISSUE THREAD

**Issue by HuMarts** [FortAwesome/Font-Awesome#3175]
Hello!
I would be very pleased to be able to use an icon that fits the category "Walking"
To me a simple drawing of footsteps would be perfect. Or, as an alternative, a walking person should be fine too!.
Best regards,
Huub Martens.

**Comment by tomay** [comment]
+1

**Comment by zdila** [comment]
+1

**Comment by sebastian301082** [comment]
+1

**Comment by stevenyhof** [comment]
+1

**Comment by grantneufeld** [comment]
+1(ish). The audit-trail request got merged into this request. If this ends up serving the function of an icon to represent an audit-trail, then I’m a +1.

An example use case: I have a system that has workflows for a financial institution. Auditors (and managers) need to be able to review the actions taken, who took them, and when. So, when viewing something in the system, I need to link to the “audit trail” for that thing. In coding terms, the audit trail is sort of like the version history for a project.

**Comment by warrenma65** [comment]
Any progress with this? I'd really like to see a footsteps or feet icon!

**Comment by wlievens** [comment]
+1

**Comment by XtheOne** [comment]
+1

**Comment by AbdAllahBoda** [comment]
+1

**Comment by jamesjieye** [comment]
+1

**Comment by manuelph** [comment]
+1

**Comment by mccrearyk** [comment]
+1

**Comment by aethior** [comment]
Duplicate of #2788.

cc/ @tagliala

**Comment by tagliala** [comment]
~Sorry, reopening here. I think this is about footprints rather than shoeprints. Editing the title~

My bad. Footprints is here #13650
