### ISSUE TITLE
Icon request: icon-transcript, icon-audiodescription

### ISSUE THREAD

**Issue by nfreear** [FortAwesome/Font-Awesome#3176]
Hi,
This relates to #894 (icon-wheelchair) and #614 (icon-accessibility)...

Please can you consider complementing the [audio/video player icons](http://fortawesome.github.io/Font-Awesome/icons/#video-player) with three more:

* __icon-transcript__: [YouTube](https://youtube.com/watch?v=NaBBk-kpmL4) uses an icon a little like a text document, with a line highlighted - the symbol between "Add to" and the graph. Other players, for example, [OU Media Player](http://mediaplayer.open.edu/), use a "T" symbol.

* __icon-captions__: Captions/ closed captions for the hard of hearing. In the UK/England this is AKA/mis-named as subtitles (Alias? __icon-subtitles__). An internationally recognised symbol is "CC" or ["CC in a TV" - closed captions](https://en.wikipedia.org/wiki/Closed_captioning) (needs differentiating from "Creative Commons"). A UK recognized symbol is "S" - see [BBC iPlayer](http://www.bbc.co.uk/iplayer/).

* __icon-audiodescription__: [Audio description (video description)](https://en.wikipedia.org/wiki/Audio_description) is an additional audio track for the blind. A well-recognized [symbol combines "AD" with a loud-speaker symbol](http://wpclipart.com/signs_symbol/handicap/hearing/audio_description.png.html) (Alias? __icon-audiodescribed__)

Thank you,

Nick

(Disclaimer: I develop [OU Media Player](http://mediaplayer.open.edu/).)

**Comment by davegandy** [comment]
Added `fa-audio-description` into version 4.6.0-wip branch. Closing.
