### ISSUE TITLE
Icon Request: dropr

### ISSUE THREAD

**Issue by rtargosz** [FortAwesome/Font-Awesome#3204]
Hi,

Could you please create a new icon for dropr, the portfolio-sharing web site that looks like this: http://www.bentvector.com/img/dropr.png ? I want to add this to my page just like the LinkedIn, YouTube, Facebook and other font icons.

Thanks SO much for Font Awesome!
- Rob

**Comment by aethior** [comment]
Hi,

Dropr was closed in 2019. ([more info](https://twitter.com/dropr/status/1205261580914565122))

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks.

Appreciate this effort for brand icons

As a matter of fact, there should also be dead brands inside the core. Some of them have been preserved for historical reasons at the moment
