### ISSUE TITLE
Icon Request: fa-pulse

### ISSUE THREAD

**Issue by joelsaupe** [FortAwesome/Font-Awesome#3206]
<strike>To go along with the other medical icons it would be really helpful to have a heart beat (pulse). This could be used not only in the medical field but this symbol could be widely used in other fields as well to represent current status or activity.</strike> Github's Pulse section is a fine example of how this icon could be used and what it might look like.

---

edit by tagliala: 

![image](https://user-images.githubusercontent.com/556268/36790446-2c77398c-1c95-11e8-87f7-90003750b1ca.png)

**Comment by quozd** [comment]
+1

**Comment by chmanteli** [comment]
+1

**Comment by tagliala** [comment]
there is an heartbeat icon in 4.3.0

**Comment by smartcorestudio** [comment]
I think it can be closed now

**Comment by eckig** [comment]
@smartcorestudio not really, since the new icon (I like it) is a pulse inside a heart. This proposal is about a single pulse.

**Comment by tagliala** [comment]
I agree with @eckig

Maybe for some use cases of fa-pulse, heartbeat is ok for other it isn't

**Comment by nsimeonov** [comment]
the "standalone" pulse can be used as oscilloscope somewhere, but not if it's inside a heart

**Comment by AlexeyKosov** [comment]
This new icon is much less useful than a single pulse icon would be.

**Comment by sebastian301082** [comment]
+1

**Comment by bluebilt** [comment]
agreed, not what I had in mind when I +1'ed this request

**Comment by dmland** [comment]
Still waiting for a simple "pulse", as in an impulse event, not a heartbeat, please, as pictured in @joelsaupe's image above.

**Comment by zallek** [comment]
+1

**Comment by jbteague** [comment]
+1

**Comment by jjosephs** [comment]
+1 for a simple pulse icon

**Comment by pareeohnos** [comment]
+1

**Comment by james8aus** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by iigorr** [comment]
+1

**Comment by enekogb** [comment]
:+1: 

Plex Media Server has this icon in its web App (see the first image at https://support.plex.tv/hc/en-us/articles/200289408-Plex-Web-App-Settings)

**Comment by mg1075** [comment]
+1

**Comment by sensibleworld** [comment]
Font Awesome 5.0.7 contains a heartbeat icon! https://fontawesome.com/icons?d=gallery&q=heartbeat&c=medical

**Comment by eckig** [comment]
The heartbeat icon is neither new (since 4.3) nor is it the one we requested here?

**Comment by sensibleworld** [comment]
@eckig Good call. Re-opening.

**Comment by tagliala** [comment]
Right, this is a generic pulse.

The opening post is misleading, since it mentions "have a heart beat (pulse)"

I'm going to edit the first post and add there the example

**Comment by alystair** [comment]
Would be good to give it the synonym "ping" when you eventually toss it into Algolia :)
