### ISSUE TITLE
Icon Request: icon-air-conditioning

### ISSUE THREAD

**Issue by deyacol** [FortAwesome/Font-Awesome#3211]
I am making an application for a hotel, I need more icons. Could I develop? How do I do?

**Comment by aquerrec** [comment]
+1

**Comment by MarGraz** [comment]
+1

**Comment by coleby210** [comment]
+1

**Comment by tagliala** [comment]
is this a duplicate of #1739 ?

If not, could you please provide a single color example?

**Comment by CreativeNative** [comment]
+1

**Comment by sensibleworld** [comment]
We have few options to keep up cool now: https://fontawesome.com/search?q=air%20%20conditioner&s=solid%2Cbrands
