### ISSUE TITLE
Icon Request: fa-triangle / fa-triangle-o

### ISSUE THREAD

**Issue by pedrovieirasilva** [FortAwesome/Font-Awesome#3216]
There should be fonts for all simple geometric shapes. There already fonts for square and circle, but other like rectangle, triangle, pentagon, hexagon.

So please create at least:
fa-rectangle/ fa-rectangle-o
fa-triangle / fa-triangle-o
fa-pentagon / fa-pentagon-o
fa-hexagon / fa-hexagon-o

Having this would greatly improve the ability to use these as graphical legends.

Thank you

**Comment by gquipster** [comment]
+1 for triangle

**Comment by chiccorosso** [comment]
+1 for triangle, hexagon, pentagon

**Comment by albertmatyi** [comment]
+1

**Comment by G-Driver** [comment]
+1 triangle

**Comment by gdespaux** [comment]
+1 triangle, hexagon, etc. (basic shapes)

**Comment by vernelindner** [comment]
+1 for triangle

**Comment by StanleyMlha** [comment]
+1 for all

**Comment by campingrider** [comment]
+1 for basic shapes

**Comment by pedrovieiraslva** [comment]
@tagliala any idea if this is going to be considered?
This are basic geometric shapes that are missing from font-awesome. Other requests mentioned do not adress whats requested here.
Thanks!

**Comment by tagliala** [comment]
@pedrovieiraslva all requests are being considered :)

But meanwhile you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by Denni007** [comment]
+1

**Comment by ElliotChong** [comment]
+1

**Comment by tomatau** [comment]
:+1: any news on this?

**Comment by JacopoGobbi** [comment]
+1

**Comment by dacunni1** [comment]
+1

**Comment by monkviper** [comment]
+1

**Comment by Casper-O** [comment]
+1

**Comment by marbin** [comment]
+1

**Comment by anyssa** [comment]
+1 for basic shapes

**Comment by bradbernard** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by thesumo** [comment]
+1

**Comment by mpiru** [comment]
+1

**Comment by shihao316558512** [comment]
+1  triangle-o

**Comment by may17** [comment]
+1 for triangle

**Comment by northscope** [comment]
+1

**Comment by YamiOdymel** [comment]
+1

**Comment by jbeckton** [comment]
well, it's been 2 years so i guess that means NO!

**Comment by SwapnaliShrikhande** [comment]
+1 for triangle

**Comment by tomatau** [comment]
Can people please support this with emoji reactions? Don't want to turn off notifications in-case this happens but seeing notifications for +1 every month is getting a little old! :)

**Comment by henryarousell** [comment]
fa-triangle !!!

**Comment by galkamax** [comment]
+1

**Comment by schowes** [comment]
+1 - specifically for the triangle. Very useful for "warnings" in UIs.

**Comment by CG0323** [comment]
+1

**Comment by Dmitra** [comment]
&triangle; can be used instead

**Comment by Casper-O** [comment]
@Dmitra i tested what you suggested with triangle - Not a good result, but i guess it is due to the limitations of the size?

test Results can be seen here...

https://jsfiddle.net/ogj0Lgg4/

**Comment by brevilo** [comment]
Also, the triangle used should match the style of similar existing icons like square and circle, such that they can be used together harmonically.

**Comment by Dmitra** [comment]
you may want to adjust the font size too. There is a separate symbol for big triangle. While it may still play bad in fa-stack, at least you have triangle on its own.
See the reference for other symbols along with many basic shapes which will go in harmoby with each other.
https://dev.w3.org/html5/html-author/charref

**Comment by jbregar** [comment]
+1

**Comment by Nelinho** [comment]
+1

**Comment by Soaku** [comment]
When is this going to be added? All the figures would be useful.

**Comment by sensibleworld** [comment]
Closing this issue, as shapes available in multiple styles now: https://fontawesome.com/icons?d=gallery&c=shapes
