### ISSUE TITLE
Rename fa-search-* to fa-magnify-*

### ISSUE THREAD

**Issue by bigfoot90** [FortAwesome/Font-Awesome#3222]
Would be useful to have
`fa-magnify` as alias for `fa-search`
`fa-magnify-plus` as alias for `fa-search-plus`
`fa-magnify-minus` as alias for `fa-search-minus`

**Comment by sensibleworld** [comment]
We've updated our naming conventions as part of version 6, and have also included the ability to have aliases. In the case of the search icon, the new base name is now `fa-magnifying-glass`, though `fa-search` still works as an alias.
