### ISSUE TITLE
Icon Request:fa-info-circle-o

### ISSUE THREAD

**Issue by jwaala** [FortAwesome/Font-Awesome#3224]

**Comment by Eonil** [comment]
+1

**Comment by Tibfib** [comment]
+1

**Comment by grgcombs** [comment]
+1

**Comment by TheCrow1213** [comment]
+1

**Comment by tompazourek** [comment]
+1

**Comment by kevinyuliawan** [comment]
+1

**Comment by elimisteve** [comment]
+1

**Comment by hakunin** [comment]
Can everyone upvote this with the 👍  on the issue so this might get prioritized if the author uses 👍  stats?

**Comment by zhurin** [comment]
Looking forward to getting this icon added as an accompaniment to the filled version that's already available. Upvoted.

**Comment by Pypoli** [comment]
Would love to get this too.

**Comment by zhurin** [comment]
Ah, I see that this has been added in 5.0, but only in the Pro version. https://fontawesome.com/icons?d=gallery&q=info-circle

**Comment by ahmednawazbutt** [comment]
+1

**Comment by tagliala** [comment]
Closing here, it is available in the Pro version starting from Font Awesome 5
