### ISSUE TITLE
Icon Request: fa-cart-minus

### ISSUE THREAD

**Issue by jenmeyercheck** [FortAwesome/Font-Awesome#3234]
So there's an icon of a shopping cart, but it would be rad if that was extended to add a couple more with a minus and a plus sign over them, so you're adding items to your cart, or removing items to your cart. That would be the application there. Right now I'm going for the plus and minus FA icons, which I think will work nicely and be very clean, but it might be cool to have some other options. :)

**Comment by tagliala** [comment]
there is an add-to-cart icon in 4.3.0

**Comment by vartagg** [comment]
@kisuka It's cool. Thanks for your tip, didn't know about this powerful feature =)

**Comment by aethior** [comment]
Hi @jenmeyercheck,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/cart-minus

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
FA6 users, **in a web application**, can achieve a similar icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/34/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
