### ISSUE TITLE
Icon request: fa-line-height

### ISSUE THREAD

**Issue by TuurDutoit** [FortAwesome/Font-Awesome#3235]
A line height icon, which could be used for text editors, for example (that's what I need it for)
Design: like fa-align-justify, but with a double arrow running along (vertically):
![writer-line-height-icon](https://cloud.githubusercontent.com/assets/4077287/2681710/799cee46-c190-11e3-9b60-ebb0c5210c82.png)
(Sorry for the crappy image)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/line-height?style=solid
