### ISSUE TITLE
Icon Request: icon-memory (icon-ram)

### ISSUE THREAD

**Issue by qzao22** [FortAwesome/Font-Awesome#3239]

**Comment by uraimo** [comment]
+1 too.

**Comment by Forge-Media** [comment]
+1 too.

**Comment by vlipman** [comment]
+1

**Comment by RamzyVirani** [comment]
+1

**Comment by cameroncoats** [comment]
+1

**Comment by ScriptorNY** [comment]
+1

**Comment by dave-irvine** [comment]
+1

**Comment by tomuench** [comment]
+1

**Comment by PlasmaPower** [comment]
+1

**Comment by SirCmpwn** [comment]
+1

**Comment by vivi168** [comment]
+1

**Comment by suavelizard** [comment]
+1

**Comment by uok** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by asdrubalsantander** [comment]
+1

**Comment by capitantrueno** [comment]
+1

**Comment by tetsi** [comment]
+1

**Comment by metamet** [comment]
+1

**Comment by 06chaynes** [comment]
+1

**Comment by tomdcc** [comment]
+1

**Comment by mmequignon** [comment]
+1

**Comment by taufique71** [comment]
+1

**Comment by wedens** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by tabakisp** [comment]
+1

**Comment by armorking5** [comment]
+1

**Comment by RoryDungan** [comment]
+1

**Comment by Carusu** [comment]
+1

**Comment by IWRichard** [comment]
+1

**Comment by WhyKickAmooCow** [comment]
+1

**Comment by gimiki** [comment]
+1

**Comment by ttchopper** [comment]
+1

**Comment by rkhitin** [comment]
+1

**Comment by jpotier** [comment]
+1

**Comment by deejayy** [comment]
+1

**Comment by n-kolodziej** [comment]
+1

**Comment by andszk** [comment]
+1

**Comment by seyedmmousavi** [comment]
+1 for both outline and fill version

**Comment by kmbriedis** [comment]
+1

**Comment by kpillis** [comment]
+1

**Comment by filipegoncalves** [comment]
+1

**Comment by redzioch** [comment]
+1

**Comment by graipher** [comment]
+1

**Comment by johnrivelt** [comment]
+1

**Comment by teatwig** [comment]
+1

**Comment by ashishpatel1992** [comment]
+1

**Comment by arturmamedov** [comment]
+1

**Comment by vansoest** [comment]
+1

**Comment by iboshkov** [comment]
+1

**Comment by xPathin** [comment]
+1

**Comment by neoteknic** [comment]
+1

**Comment by drawm** [comment]
+1

**Comment by JohnyR** [comment]
+1

**Comment by Cannonb4ll** [comment]
+1

**Comment by williamtdr** [comment]
+1

**Comment by duffydack** [comment]
+1 (though I don't know why this a day 1 thought)

**Comment by ezwebcraft** [comment]
+1 I think would help engineer sites

**Comment by abkds** [comment]
+1

**Comment by ErkanMDR** [comment]
+1

**Comment by huiyiqun** [comment]
+1

**Comment by gunlee01** [comment]
+1

**Comment by joaolrpaulo** [comment]
+1

**Comment by shuvo-paul** [comment]
+1

**Comment by nicolasbeauvais** [comment]
+1

**Comment by eryshev** [comment]
+

**Comment by glowGrape** [comment]
+1

**Comment by jkomyno** [comment]
+1

**Comment by dignityinside** [comment]
+1

**Comment by leothelocust** [comment]
+1

**Comment by jhorchler** [comment]
+1

**Comment by HanshuLin** [comment]
+1

**Comment by oombadness** [comment]
+1

**Comment by AdGalesso** [comment]
+1

**Comment by NerdsvilleCEO** [comment]
+1

**Comment by semanta** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by rvolosatovs** [comment]
+1

**Comment by bryanhamon** [comment]
+1

**Comment by Bharat-B** [comment]
+1

**Comment by ezalenski** [comment]
+1

**Comment by philcryer** [comment]
+1

**Comment by tsypa** [comment]
+1

**Comment by siftra** [comment]
+1

**Comment by bokub** [comment]
+1

**Comment by SysVoid** [comment]
+1 why is this still not a thing

**Comment by gekkey** [comment]
+1

**Comment by janhieber** [comment]
+1

**Comment by jkomyno** [comment]
Guys, I've just discovered that since v4.7 Font-Awesome now supports an icon which can be used as ram.
Here it is: http://fontawesome.io/icon/microchip/
IMHO this issue should be closed after an alias ```fa-ram``` will be put aside to ```fa-microchip```.

**Comment by ezalenski** [comment]
fa-microchip was for #1840, I voted for this to be a separate icon for fa-ram to distinguish between the two.

**Comment by danlars** [comment]
+1

**Comment by cpassos** [comment]
+1

**Comment by ArenM** [comment]
+1

**Comment by CodeSurfing145** [comment]
+1

**Comment by rdpse** [comment]
+1

**Comment by lorenzo-biava** [comment]
+1

**Comment by chitralverma** [comment]
+1

**Comment by MartianH** [comment]
+1

**Comment by kswr** [comment]
+1

**Comment by NikhilMTomy** [comment]
+1

**Comment by Inuun** [comment]
+1

**Comment by Inuun** [comment]
+1

**Comment by 5haffl** [comment]
+1

**Comment by johnp** [comment]
+1

**Comment by MarcoAnastasio** [comment]
+1

**Comment by LarsHaalck** [comment]
+1

**Comment by moige** [comment]
+1

**Comment by NikhilMTomy** [comment]
+1

**Comment by hroost** [comment]
+1

**Comment by visualpharm** [comment]
I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

[The memory icon is here](https://icons8.com/icon/14232/memory-slot).

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830), [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534), [clean](https://icons8.com/icon/14160/broom) and [math](https://github.com/FortAwesome/Font-Awesome/issues/1133#issuecomment-304470923) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by 132ikl** [comment]
+1

**Comment by vando** [comment]
+1

**Comment by lodi-g** [comment]
+1

**Comment by faridcboy** [comment]
+1

**Comment by DDoSolitary** [comment]
+1

**Comment by janemba** [comment]
+1

**Comment by Savanta** [comment]
+1

**Comment by d-ryzhikov** [comment]
+1

**Comment by edubart** [comment]
+1

**Comment by sistematico** [comment]
+1

**Comment by maciejvel** [comment]
+1

**Comment by olibanjoli** [comment]
+1

**Comment by Bradyok** [comment]
+1  Do they ever actually do requests?

**Comment by koxu1996** [comment]
+1

**Comment by ledek89** [comment]
+1

**Comment by iamdual** [comment]
+1

**Comment by Ziggeh** [comment]
+1

**Comment by fwalloe** [comment]
+1

**Comment by ottagono** [comment]
+1

**Comment by MatthieuArzel** [comment]
+1 :)

**Comment by pidov** [comment]
+1

**Comment by sensibleworld** [comment]
I forgot what we were talking about: https://fontawesome.com/icons?d=gallery&q=memory
