### ISSUE TITLE
Icon Request: exclamation-circle-o

### ISSUE THREAD

**Issue by haggen** [FortAwesome/Font-Awesome#3243]
Like the `check-circle-o` and others i.e. without the circle filling.

**Comment by dacunni1** [comment]
+1  Hey!  Just like the one next to all of the open issues! (green exclamation-circle-o)

**Comment by Vallenain** [comment]
+1

**Comment by rtroncoso** [comment]
+1

**Comment by JeanGamain** [comment]
+1

**Comment by jodikuehn** [comment]
+1

**Comment by pristinesource** [comment]
+1

**Comment by anestik** [comment]
+1

**Comment by LionelClaudon** [comment]
+1

**Comment by albertvazquezm** [comment]
+1

**Comment by gualopezb** [comment]
+1

**Comment by tagliala** [comment]
This icon is available in FA Pro 5.0.0

https://fontawesome.com/icons/exclamation-circle?style=regular
