### ISSUE TITLE
Icon request: fa-work-in-progress

### ISSUE THREAD

**Issue by jcoufal** [FortAwesome/Font-Awesome#3246]
Hi all,

I wanted to ask, if there is some way how you could include "work in progress" icon. It is very often used icon, for maintenance actions, expressing status, etc.

Examples:
- state of your issue - work in progress
- get your machine into maintenance state
- this page is under reconstruction

I was actually thinking about having 2 different icons, each of them are suitable for different use cases:
- fa-maintenance: http://www.theapartmentgallery.com/images/services_icon_full_bw.jpg
- fa-work-in-progress: http://i.stack.imgur.com/kmfPT.png

Thank you for your help
-- Jarda

**Comment by LBreda** [comment]
:thumbsup:

**Comment by masciugo** [comment]
(yes)

**Comment by harshavardhana** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by Krokit** [comment]
:+1:

**Comment by kyriiherman** [comment]
:+1:

**Comment by rlafranchi** [comment]
:+1:

**Comment by edotassi** [comment]
+1

**Comment by xplode** [comment]
+1

**Comment by jeremk** [comment]
+1 :)

**Comment by andyanderso** [comment]
+1

**Comment by Garo263** [comment]
:+1:

**Comment by sherylj** [comment]
👍

**Comment by cyberwani** [comment]
👍

**Comment by akkee** [comment]
👍

**Comment by krv** [comment]
👍

**Comment by DrSensor** [comment]
+1 for fa-work-in-progress

**Comment by mojtaba-ramezani** [comment]
🙄

**Comment by aless80** [comment]
+1

**Comment by turbolego** [comment]
👍

**Comment by KasperSkytte** [comment]
:+1:

**Comment by Berkmann18** [comment]
+1

**Comment by lizzbrazen** [comment]
+1

**Comment by vbbalaji** [comment]
👍 +1

**Comment by sensibleworld** [comment]
These two icons are available in FA Pro!

https://fontawesome.com/icons/construction?style=solid
https://fontawesome.com/icons/digging?style=solid
