### ISSUE TITLE
Font Awesome LESS not working when compiled with Grunt

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#3247]
I am using Bower to pull in the latest Font Awesome-package (which is placed in bower_components) and use the LESS version that is compiled with Grunt to minifed CSS (stored in public/assets/css). The problem is that the icons are not displaying in the browser. There seems to be a problem with the relative path. That's why I tried to define an absolute path like so:

```
@fa-font-path: "http://localhost/testing/bower_components/font-awesome/fonts";
```

However, I am getting a 404 error:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.ttf?v=4.0.3
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.svg?v=4.0.3#fontawesomeregular
```

I tried the suggested [bug fix](https://github.com/FortAwesome/Font-Awesome/pull/3138/files) by taglilia and still get the error messages, however, the icons display in Chromium and Firefox. In Chrome only empty squares display.

I also tried the suggested 4.0.4 wp-branch and keep getting the errors:

```
GET http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.4 404 (Not Found) frontend.min.js:1
GET http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.ttf?v=4.0.4 404 (Not Found) /testing/bower_components/font-awesome/fonts/fontawesome-webfont.ttf?v=4.0.4:1
GET http://localhost/testing/bower_components/font-awesome/fonts/fontawesome-webfont.svg?v=4.0.4 404 (Not Found) 
```

Could this be a Chrome bug?

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
