### ISSUE TITLE
Icon request: sport icons

### ISSUE THREAD

**Issue by piotered** [FortAwesome/Font-Awesome#325]
Hi, 
Could be great to have some sport icons (balls, fans).

Thx,
Piotered

**Comment by nce** [comment]
+1 ski snowboard mountainbike

**Comment by sloga** [comment]
+1
and
icon-aquatics or
icon-swim
![1206571762111003144johnny_automatic_nps_map_pictographs_part_89 svg hi](https://cloud.githubusercontent.com/assets/1276945/6050987/12dedf0a-ac79-11e4-8a97-7e9a2d25cbe0.png)

**Comment by alyssabraun** [comment]
+1 for swim
+1 for run

**Comment by ChrisLegg** [comment]
+1 for swim

**Comment by BrockBeldham** [comment]
+1 

it would be great to have icons for major North American Sports Leagues (not the league's logos, but icons that could be associated to each sport):

hockey (NHL)
![](http://cdn.flaticon.com/png/256/37932.png)
baseball (MLB)
![](http://www.iconexperience.com/_img/i_collection_png/512x512/plain/baseball.png)
basketball (NBA)
![](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/basketball.png)
football (NFL)
![](https://cdn0.iconfinder.com/data/icons/rcons-basic/16/football_sport-512.png)
golf (PGA)
![](http://cdn.vectorstock.com/i/composite/33,87/golf-icon-vector-203387.jpg)
tennis
![](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/tennis.png)

**Comment by mkacik** [comment]
+1

**Comment by sidongithub** [comment]
+1

**Comment by leyamcir** [comment]
+1

**Comment by Fatbat** [comment]
+1

**Comment by nunomazer** [comment]
+1

**Comment by pctux** [comment]
+1

**Comment by wstow** [comment]
+1

**Comment by austinarchibald** [comment]
:+1:

**Comment by oriadam** [comment]
+1
Also: Rollerblading and E-bike

**Comment by khart-pixsym** [comment]
+1

**Comment by jessenia** [comment]
+1

**Comment by jessenia** [comment]
barbells, crossfit, weights

**Comment by vtorres1976** [comment]
+1

**Comment by SteveHarlington** [comment]
+1

**Comment by obruchez** [comment]
+1

**Comment by ankitraturi** [comment]
+1

**Comment by JaoNoctus** [comment]
+1

**Comment by JaoNoctus** [comment]
- Skateboard

**Comment by jpurpleman** [comment]
+1

**Comment by vintagerock07** [comment]
+1

**Comment by vintagerock07** [comment]
+1

**Comment by SergeyBaboriko** [comment]
+1

**Comment by kevbodavidson** [comment]
+1

**Comment by stefanpl** [comment]
+1

**Comment by rafaelms87** [comment]
+1 
Sports, Gym

**Comment by maziak** [comment]
+1

**Comment by Buceador** [comment]
+1

**Comment by shashank2907** [comment]
+1

**Comment by lancejones** [comment]
+1... wait no... +2

**Comment by solstice43** [comment]
Swim, Bike, Run please!

**Comment by piotered** [comment]
Greatness of the Web + Patience. It rocks. Thanks.
