### ISSUE TITLE
Icon request: fa-patreon

### ISSUE THREAD

**Issue by JamesWhitman** [FortAwesome/Font-Awesome#3257]
Hi guys

I'd love to be able to icon up links to my Patreon page. Patreon and blogs seem to go hand in hand, so I imagine there'll be a lot of appetite for this icon when Patreon is more widely used.

Here's an example of the icon:

![f28e1fbc510abe5d2cb2bdff8c5a64e5_bigger](https://cloud.githubusercontent.com/assets/7312328/2717653/f34f26d0-c543-11e3-8539-21c1c92ea5fb.png)

Thanks!

**Comment by delusioninabox** [comment]
Yes please!! +1

**Comment by bsmjlm** [comment]
Yes Pleeeease! +1 with a cup of coffee ^_^

**Comment by KillerKonceptz** [comment]
Please and thank you +! (we really need this option... we'd like to integrate this more easily into Simple Social Icons plugin, and we need to add in Patreon).

**Comment by dan** [comment]
+1

**Comment by joelkesler** [comment]
+1

**Comment by bjorn** [comment]
+1

**Comment by bjorn** [comment]
+1 (posted a $15 bounty at https://www.bountysource.com/issues/1688862-icon-request-fa-patreon)

**Comment by seiyria** [comment]
+1

**Comment by LauritzT** [comment]
+1

**Comment by swizzlekiss** [comment]
+1

**Comment by macinchick** [comment]
+1

**Comment by benthinkin** [comment]
+1

**Comment by lostfocus** [comment]
+1

**Comment by zoombear** [comment]
+1

**Comment by Epwna** [comment]
+1

**Comment by Deevad** [comment]
+1

**Comment by Shipwreck** [comment]
+1

**Comment by jaredallard** [comment]
:+1:

**Comment by LynnCo** [comment]
+1

**Comment by tethlah** [comment]
+1

**Comment by armorproof** [comment]
+1

**Comment by bartmika** [comment]
+1

**Comment by bjorn** [comment]
What's with all the +1? Why not provide a real incentive for whoever puts in the effort for this by increasing the [bug bounty at BountySource](https://www.bountysource.com/issues/1688862-icon-request-fa-patreon)?

**Comment by soycode** [comment]
I would also suggest a -square version (the icon would fit easily enough in a square).

**Comment by CoWinkKeyDinkInc** [comment]
:+1: Please add this.

**Comment by ExileDev** [comment]
Please add this icon I really want it for my site it would be very helpful.

**Comment by virtualpain** [comment]
:+1:

**Comment by juan0tron** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by sr-ix** [comment]
+1

**Comment by BenSibley** [comment]
+1

**Comment by bjorn** [comment]
So many +1 but nobody wants to increase the bounty? :-|

**Comment by Staticpast** [comment]
+1

**Comment by georgebonnr** [comment]
Hey everyone!
From what I can tell they're [not accepting](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests) pull requests containing new icons.
Here's a space-efficient square svg version if someone wants to use as-is or make a fork and take this the rest of the way:
```
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 8 8"
     width="32px"
     height="32px"
     fill="#000">
    <path d="M2.32081783.3678855c.869042-.40526652 1.88661925-.47774603 2.80665096-.20727372.80652418.2346745 1.53190822.73363407 2.0426921 1.3983242.5050198.6523156.79854318 1.4641745.82647667 2.28752405.0354711.8511923-.21060967 1.71122356-.6952336 2.4134793-.71030882 1.0518368-1.9482503 1.72713368-3.22254963 1.73950823-.63803645.0008839-1.2760729.00044195-1.91366597 0 .00532067-1.34042898.0004434-2.68085797.00310373-4.0217289.00221694-.50647268.23011877-1.00499028.60921618-1.34131288.36180524-.3279256.85973083-.5002854 1.3474585-.46404565.50457642.03093638.98831357.2859405 1.30267622.68015833.3232304.3968695.46422805.93295272.38131434 1.4376576-.08114014.53122177-.41368172 1.01603898-.87790977 1.2882791-.5373872.3252739-1.2406018.3345548-1.7935076.04021728.00044338.43487706-.0008868.86975412.00044338 1.30463118.4934917.14407512 1.02201113.16838228 1.52392723.0539177.7431196-.16219502 1.4144102-.6174017 1.8444973-1.24187455.40969124-.5855814.59946164-1.31788962.52851943-2.02810043-.06030086-.6514317-.34052257-1.27944013-.78302457-1.7620476-.41013462-.4507872-.95860653-.77561914-1.55363427-.913507-.6837055-.162195-1.42372137-.07866678-2.05200326.23600036C1.64553673 1.7542771.962718 2.8206982.95207668 3.932198.95030312 5.2876532.95163328 6.6435504.9511899 7.99944755c-.3165796.0008839-.63360256.00044195-.95062554.00044195-.0004434-1.32584468.0004434-2.65168938-.0004434-3.97709212-.00443387-.56569374.11306415-1.13227137.3440697-1.6493508C.73215587 1.49662128 1.44778534.7691745 2.32081784.3678855z" />
</svg>
```
:beers:

**Comment by pjf** [comment]
+1

Also, thank you @georgebonnr , the svg works great!

**Comment by svenluijten** [comment]
+1

**Comment by pahimar** [comment]
+1

**Comment by jamierocks** [comment]
+1

**Comment by ekv88** [comment]
+1 plx guys, more and more ppl are using patreon its well known now.

**Comment by sunnyandblue** [comment]
+1 pretty please with sugar on top!

**Comment by Speedysnail6** [comment]
+1 I would definately benefit from this

**Comment by kode29** [comment]
+1 Would really like this

**Comment by unrau** [comment]
+1 Pretty please?

**Comment by Celti** [comment]
A definite +1 here. Trying to build a new template for a buddy's Patreon-funded site and ran smack into the lack of this icon.

Patreon is at least as popular as sites that have recently received brand icons like Scribd and Product Hunt, and serves as a vital social and funding network for the growth of the creative web. I cannot urge enough the addition of this icon to Font Awesome and hope other people step up and contribute to the bounty for this.

**Comment by tomboruta** [comment]
+1 I was actually surprised this wasn't already in font awesome

**Comment by rodhilton** [comment]
+1

**Comment by MrLewk** [comment]
**+1** so much for this

**Comment by adamwintle** [comment]
+1

**Comment by maxlefou** [comment]
+1

**Comment by fiftywalrus** [comment]
Yes please!

**Comment by yuk75** [comment]
Really badly need this!!

**Comment by seanVonDrake** [comment]
+1

**Comment by jwiwe** [comment]
+1

**Comment by lewislepton** [comment]
+1
+1
+1
+1
+1
+1

yes please ;)

**Comment by ravi-ojha** [comment]
Arggh, [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) says they are not accepting pull request containing new icons at the moment :(

**Comment by AppoPro** [comment]
+1

**Comment by Guichaguri** [comment]
+1

**Comment by seanVonDrake** [comment]
that's a pity, this set is really useful but can become quickly useless and
obsolete if they don't add new icons

"sono un servitore del Fuoco segreto, e reggo la Fiamma di Anor"
www.fabiomosti.it - www.extremumgdr.it - www.colonnagaribaldi.org -
www.doveandiamoacena.it

2016-04-25 18:14 GMT+02:00 Guichaguri <notifications@github.com>:

**Comment by yuk75** [comment]
I don't understand why this is still being debated.

**Comment by Celti** [comment]
Do you really think anyone's "debating" anything here? Font-Awesome has over *three thousand* icon requests open — and that's on GitHub alone, when presumably some have come in over other channels. FA have simply made the choice *not* to prioritise brand icons, and I can hardly blame them for that.

**Comment by maxlefou** [comment]
I thought the choosing of the icons was based on popularity and/or the potential of use, I didn't know the icons were chosen arbitrary.......

**Comment by MattDemers** [comment]
+1

**Comment by pappabj0rn** [comment]
+1

**Comment by laserlemon** [comment]
+1

**Comment by logological** [comment]
:+1:

**Comment by Bitzz** [comment]
+1

**Comment by MrDnomaid** [comment]
+1

**Comment by Destru** [comment]
👍

**Comment by mrmcpowned** [comment]
+1

**Comment by feriancek** [comment]
+1

**Comment by vickifarmer** [comment]
+1

**Comment by northscope** [comment]
+1

**Comment by luchaos** [comment]
+1

**Comment by PeaceLightsPGH** [comment]
+1

**Comment by jaredallard** [comment]
Please don't +1, we have Github reactions now :). Go :+1: on the first post!

**Comment by nanilab** [comment]
👍

**Comment by nanilab** [comment]
When will this be done?

**Comment by CoWinkKeyDinkInc** [comment]
@nanilab We would probably have to wait until Font Awesome 5 is released.

**Comment by bradj** [comment]
+1

**Comment by spekz88** [comment]
@bradj please use github reaction :+1:  button instead of +1

**Comment by stormyqq** [comment]
+∞

**Comment by RheaAyase** [comment]
April 2014... Almost april 2017... All hope lost for the team behind FA. RIP

**Comment by tchncs** [comment]
What is blocking this? Patreon is so popular! o.O

**Comment by RheaAyase** [comment]
Nothing is blocking it, they merely want to make it a paid thing and sell all these icons that people want so bad. Nothing against doing that, but stalling for three years is not okay, just freakin do whatever you want to do.

**Comment by CoWinkKeyDinkInc** [comment]
Exactly what I was thinking

**Comment by lewislepton** [comment]
yeah. think im just gonna make my own. voted years ago. shame as i think they are good in the department of icons, but this is long in the tooth, actually past the tooth & to the airport

**Comment by laserlemon** [comment]
Making content for people is hard. For years, these folks have kept me in free, high quality icons. **Thank you** for that!

**Comment by lewislepton** [comment]
aye dont get me wrong @laserlemon - i do love what they do. think its great etc etc blah blah.
just saying im gonna make my own icons that are missing right now. & more than likely will come back once things are sorted icon wise ;)

**Comment by JoshWobbles** [comment]
This is literally absurd that this still hasn't been added.

**Comment by ChaosPower** [comment]
+1

**Comment by toby3d** [comment]
Hello from 2017. Where is patreon icon?

**Comment by JoshWobbles** [comment]
Not going to happen, FA got greedy and want $200 for it, even though it only takes about 10 minutes. Just do what I did and make your own Font/Icon library.

**Comment by Guichaguri** [comment]
There's also a bunch of alternatives, I personally really like [Material Design Icons](https://materialdesignicons.com/), but there's also [SleekLogos](https://sleeklogos.design/) which has a huge amount of icons, each one with different styles. Although they both don't have a patreon icon, they accept suggestions (and actually do them)

**Comment by TheFatBastid** [comment]
+1

**Comment by Lite5h4dow** [comment]
Patreon Logo has Changed to ![New patreon logo](https://c5.patreon.com/external/logo/downloads_logomark_color_on_white@2x.png)

**Comment by lewislepton** [comment]
ive moved off & went for some other choices.

ciao ;)

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
