### ISSUE TITLE
Icon request: icon-van

### ISSUE THREAD

**Issue by raulquintana** [FortAwesome/Font-Awesome#3260]
I plan use it to identify a fleet of common vehicles.

Fireworks PNG
![vehicles fw](https://cloud.githubusercontent.com/assets/7313791/2719115/341ec564-c55b-11e3-8b69-529f5e2579e5.png)

**Comment by nikkiroylance** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/van-shuttle?s=solid
