### ISSUE TITLE
Icon Request: icon-spray-can

### ISSUE THREAD

**Issue by clearlights** [FortAwesome/Font-Awesome#3265]
Spray Can symbol

**Comment by kanisie** [comment]
Could you please add this icon-spray-can? Thanks in advance!!

**Comment by kanisie** [comment]
+1

**Comment by tagliala** [comment]
Reopening for tracking purposes

If you don't want notification please unsubscribe

**Comment by kanisie** [comment]
Please, anybody support me! I really need this icon for a website about street art/urban art culture! Not many icons about art here at all. 
Thanks in advance.

**Comment by tagliala** [comment]
@kanisie the best advice I can give you is to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by numediaweb** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/spray-can?style=solid
