### ISSUE TITLE
Icon request: icon-paint-bucket

### ISSUE THREAD

**Issue by mauriblint** [FortAwesome/Font-Awesome#3270]
Similar to:

http://help.adobe.com/es_ES/illustrator/cs/using/images/Cursor_PaintBucket_Region.png

Thanks!

**Comment by barathank** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by jasonauk** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/2212#issue-21516881

**Comment by sylphersurfer** [comment]
+1

**Comment by vikspr** [comment]
+1

**Comment by ApekshaBhosale** [comment]
+1

**Comment by Loilo** [comment]
+1

**Comment by krivaten** [comment]
+1

**Comment by peredin** [comment]
+1

**Comment by LRPalacios** [comment]
+1

**Comment by html5andblog** [comment]
+1

**Comment by LuckDragon7** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by clarkedesign** [comment]
+1

**Comment by NMcCloud** [comment]
+1

**Comment by L1l1AnA** [comment]
+1

**Comment by solilokiam** [comment]
+1

**Comment by finalgamer** [comment]
+1

**Comment by kevinresol** [comment]
+1

**Comment by bklava** [comment]
+1

**Comment by sunry81914** [comment]
+1

**Comment by kieferhagin** [comment]
Couldn't believe this doesn't exist yet! +1

**Comment by JohnsonJPJ** [comment]
+1

**Comment by rickkuilman** [comment]
+1 👍

**Comment by EridianApple** [comment]
+1!

**Comment by woptima** [comment]
+1

**Comment by sunu** [comment]
+1

**Comment by Killerbear** [comment]
+1

**Comment by ocornut** [comment]
+1

**Comment by brainmaniac** [comment]
+ 1

**Comment by axis7818** [comment]
+1

**Comment by joshoconnor89** [comment]
+1

**Comment by akadebnath** [comment]
+1
So many requests since April 2014 still not added!

**Comment by mauriblint** [comment]
@akadebnath yes! and now in 2017 I'm still need it!

**Comment by ocornut** [comment]
@akadebnath People don't work for free, if you are expecting the kind maintainers of FontAwesome to satisfy all your requests in a timely manner maybe you ought to create your own font? 
The kickstarter was an amazing idea allowing the project to actually be given some proper work, I'm glad there is a V5 in the work.

**Comment by Displee** [comment]
+1

**Comment by outofthisworld** [comment]
+1

**Comment by patrickpissurno** [comment]
+1

**Comment by winterbuild7074** [comment]
+1
I’m wondering why this still hasn’t been added yet!

**Comment by ocornut** [comment]
@winterbuild7074 
> I’m wondering why this still hasn’t been added yet!

Because there are twenty million other topics of this kind and everyone wants different things? :)

**Comment by SorenSaket** [comment]
+1

**Comment by SorenSaket** [comment]
It has now been added in 5.1.0 fa-fill and fa-fill-drip

**Comment by sensibleworld** [comment]
Just added!
https://fontawesome.com/icons/fill?style=solid
https://fontawesome.com/icons/fill-drip?style=solid
