### ISSUE TITLE
Icon Request: registered-trademark

### ISSUE THREAD

**Issue by lbrean** [FortAwesome/Font-Awesome#3276]
Font-Awesome a registered trademark symbol. 

http://www.clker.com/clipart-registered-trademark-black-transparent-fixed.html

**Comment by zeebe** [comment]
+! have to agree, since they have the copyright symbol, this should also be added.

**Comment by caban13** [comment]
+1, just for consistency!

**Comment by tagliala** [comment]
added in 4.4.0

Closing here :)

**Comment by assouan** [comment]
noo
