### ISSUE TITLE
Icon request: icon-family

### ISSUE THREAD

**Issue by respectyoda** [FortAwesome/Font-Awesome#3277]
It'd be nice to have an icon of a family which can be used for many purposes such as medical, photography, biography, and so on. 

Here are some examples of how the icon may look like:
![family-icon](https://cloud.githubusercontent.com/assets/3604751/2745282/a4f7d7ba-c733-11e3-8de2-7080149c1caf.png)
![family-icon-1](https://cloud.githubusercontent.com/assets/3604751/2745283/a522e216-c733-11e3-8f35-4bca3d9d863a.png)

**Comment by larz91** [comment]
+1

**Comment by juliomalegria** [comment]
+1

**Comment by Asparagirl** [comment]
+1

**Comment by ngheungyu** [comment]
+1

**Comment by jerearaujo03** [comment]
+1

**Comment by ambseguros** [comment]
+1

**Comment by ambseguros** [comment]
+1

**Comment by sairam2188** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by npomfret** [comment]
+1

**Comment by seblh** [comment]
+1

**Comment by Robin-Hoodie** [comment]
+1

**Comment by awais-granjur** [comment]
+1

**Comment by shawndalton** [comment]
+1

**Comment by m3hari** [comment]
+1

**Comment by MartinPerrie** [comment]
+1

**Comment by phinor** [comment]
https://maxcdn.icons8.com/app/uploads/2017/01/Family-Icon-1.png

**Comment by inyoka** [comment]
+1

**Comment by jonpasquier** [comment]
Here is another example, gender neutral

![image](https://user-images.githubusercontent.com/4568003/42443128-ef877fca-836c-11e8-8a1a-a83c9e266e96.png)

**Comment by VesterDe** [comment]
+1

**Comment by scrobbleme** [comment]
+1

**Comment by AlessandroVecchi** [comment]
+1

**Comment by hwa-rang** [comment]
It's been asking since 2014... can we please get an icon like that ? :(

**Comment by melnik0v-me** [comment]
+1

**Comment by chuchiperriman** [comment]
+1

**Comment by jaguileram** [comment]
+1!

**Comment by kevinelliott** [comment]
+1

**Comment by sbamniya** [comment]
+1

**Comment by gosman** [comment]
+1

**Comment by cxspxr** [comment]
+ 1

**Comment by blocher** [comment]
+1

**Comment by MichalRemis** [comment]
+1

**Comment by od-git** [comment]
+1

**Comment by jbnv** [comment]
Please keep it gender-neutral. The Unicode emoji set is a total cluster trying to accommodate every possible combination.

**Comment by mbomb007** [comment]
I think a good use-case for the icon would be to represent a symbol similar to what could be used on a "family" restroom. Like the fact that it can be used for male, female, and children at the same time.

While I agree that there shouldn't be a huge number of icons to represent "every possible combination", I think having a male, female, and child in the icon is important in representing a family and making the icon more easily recognizable as such.

**Comment by mbomb007** [comment]
An existing example of something that is similar is fa-restroom (though it has no child in the icon): https://fontawesome.com/icons/restroom

**Comment by GavOutdoors** [comment]
+1

**Comment by caugner** [comment]
@sensibleworld Please consider making the family icon inclusive. There are many families that don't include a female and male parent, e.g. families with just one parent as well as families with two female or two male parents. Gender-neutral representations of two parents might be a good compromise, even though it doesn't include single-parent families.

**Comment by sensibleworld** [comment]
<img width="1039" alt="Screen Shot 2021-03-23 at 7 55 31 AM" src="https://user-images.githubusercontent.com/529604/112142607-2f0e4700-8bad-11eb-93a4-d6e6311230bf.png">

@caugner These are the current icons going into v6... but I have plans to add more variations, as well.

**Comment by caugner** [comment]
@sensibleworld Thanks, looking good! Maybe one parent with two children would be an interesting variation. If the children are on either side, the parent shape might be neutral as a side-effect.

**Comment by jbnv** [comment]
Just FYI: Expansively "inclusive" emoji and icon sets are making emoji and icon sets very hard to use, particular for people with visual disabilities.

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of version 6: http://fontawesome.com/download

**Comment by cwrea** [comment]
@sensibleworld The new icons look great! I created a new issue for [single parent family variations](https://github.com/FortAwesome/Font-Awesome/issues/17984) as there's a concrete use case in the domain of health insurance.
