### ISSUE TITLE
Icon Request: pool (swimming pool)

### ISSUE THREAD

**Issue by thvibe** [FortAwesome/Font-Awesome#3285]
needed for travel site. could use a nice set of "amenities" icons

**Comment by dangnelson** [comment]
+1

**Comment by SJNBham** [comment]
Would like to see a swimming icon as well. Something like this: 

![2015-03-09 09_53_44-swimming-symbol-520x491 png 520x491](https://cloud.githubusercontent.com/assets/11393597/6559742/36ef41ae-c642-11e4-8298-d08bfafe6b53.png)

**Comment by thvibe** [comment]
+1

**Comment by JaredCubilla** [comment]
+1

**Comment by lukefrake** [comment]
:+1:

**Comment by MCooke** [comment]
+1

**Comment by mcfee1979** [comment]
+1

**Comment by Tzvook** [comment]
+1

**Comment by M440** [comment]
+1 for swim

**Comment by warmwhisky** [comment]
+1 for pool and swimming

**Comment by nbutcher-rms** [comment]
+1 for pool

**Comment by jeronimonunes** [comment]
+1

**Comment by JeroenCollier** [comment]
+1

**Comment by Reyeh** [comment]
+1

**Comment by SreerajRajappan** [comment]
+1

**Comment by kevinhusson1** [comment]
+1

**Comment by gioid** [comment]
+1

**Comment by pedrocarmona** [comment]
+1

**Comment by joao-gsneto** [comment]
+1

**Comment by joao-gsneto** [comment]
For hotels / reservation sites.
swimming pool, hollidays.

**Comment by imperat0r** [comment]
+1

**Comment by PvUtrix** [comment]
+1

**Comment by rockerest** [comment]
+1 to this, building a swimming-related website and I'd love to be able to use this throughout.

An example pool image:
![31853](https://cloud.githubusercontent.com/assets/277023/18572111/6bc38a04-7b75-11e6-8dc3-cebbcaa5f7aa.png)

Another example that's probably not good for a generic pool and only really brings to mind "hot tub":
![38-512](https://cloud.githubusercontent.com/assets/277023/18572126/98398476-7b75-11e6-84db-0e9f0653e4e1.png)

**Comment by Zahra-Khan** [comment]
+1 for pool and swimming

**Comment by Sollaar** [comment]
+1 for hotels / reservation sites:

air conditioning (icon-air)
sauna (icon-sauna)
swimming pool (icon-swimmingpool)

related:
mountain view (icon-mountain)
beach proximity (icon-beach)
horse riding (icon-horse)
tennis court (icon-tennis)

**Comment by nassimdonald** [comment]
+1

**Comment by Carlao93** [comment]
+1

**Comment by giupenni** [comment]
+1

**Comment by skartman** [comment]
+1

**Comment by caleiste** [comment]
+1

**Comment by Dinacea** [comment]
+1

**Comment by umadumdi** [comment]
+1

**Comment by jask84** [comment]
+1

**Comment by MarcioChen** [comment]
+1

**Comment by AzeredoGabriel** [comment]
+1

**Comment by aaronbeaton** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/swimming-pool?style=solid
https://fontawesome.com/icons/swimmer?style=solid
