### ISSUE TITLE
Icon Request: ipod

### ISSUE THREAD

**Issue by gmetzker** [FortAwesome/Font-Awesome#3296]
I would like to have an ipod or mp3 player icon.  Something that pairs well with the fa-mobile-phone or fa-tablet.  Something like the original Ipod with the scroll wheel or an iphone nano type icon.

Thanks

**Comment by citrusui** [comment]
+1, however, I think fa-ipod should be a different icon from fa-ipod-touch

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mp3-player?s=solid
