### ISSUE TITLE
Icon Request: knowledge

### ISSUE THREAD

**Issue by johndekroon** [FortAwesome/Font-Awesome#3297]
Would be nice to have a knowledge icon. 

Usage:
- I personally want it for a network event
- Also useable for e-learning / education sites or intranets

It will look like something with brains (?). I attached a file with the idea.
![gng_icon_knowledge](https://cloud.githubusercontent.com/assets/3469454/2775825/b905aa94-caca-11e3-96e7-e34bf3c734b3.jpg)

**Comment by jeevaeastpoint** [comment]
me too

**Comment by aethior** [comment]
Hi @johndekroon,

This icon was added in v5.7.0.
Check https://fontawesome.com/icons/head-side-brain

Regards.

cc/ @tagliala
