### ISSUE TITLE
Bower + Compass add_import_path sets up for conflicts with common partial references

### ISSUE THREAD

**Issue by stephenr85** [FortAwesome/Font-Awesome#3299]
For a typical Bower and Compass implementation, you'd reference the project and have an add_import_path "bower_components/fontawesome/scss". 

It's preferrable that the partial scss files be placed in a sub directory, like /scss/font-awesome/_core.scss, so they can be referenced individually. 

As it is, @import "variables", @import "mixins", etc conflict with a local project with files of the same name, which are pretty standard.

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
