### ISSUE TITLE
Icon request: icon-play-loop

### ISSUE THREAD

**Issue by weepy** [FortAwesome/Font-Awesome#33]
Suggestion for a repeat/loop icon in a similar style to the icon-play / icon-pause etc

**Comment by G-Driver** [comment]
I think this one is somewhat better in this situation

<img src="http://uxrepo.com/static/icon-sets/ionicons/svg/loop.svg">

**Comment by Crissov** [comment]
I think some of the suggestions to this [Stack Exchange question](http://ux.stackexchange.com/questions/89744/) may be relevant. Also related are issues #1916 and #1917 (`repeat-all` indefinitely or once).

**Comment by rsopp** [comment]
I think these icons should have a common style with the already existing fa-random icon. I would like to use them altogether as control buttons for a music player.

There are some nice icons on androidicons.com:

![android icons developer icons 2 icon font open source](https://cloud.githubusercontent.com/assets/7279749/13089536/718e2ca8-d4f1-11e5-88b6-deb05612a864.png)
![android icons developer icons 2 icon font open source2](https://cloud.githubusercontent.com/assets/7279749/13089537/7191c64c-d4f1-11e5-9bcd-682d9d02cd44.png)

**Comment by surjithctly** [comment]
+1 

![](https://camo.githubusercontent.com/9e415324bf3986b89caa23d59e5ca45c016ff066/687474703a2f2f696d6167653030352e666c617469636f6e2e636f6d2f312f7376672f312f313538342e737667)

**Comment by Crissov** [comment]
- U+1F501 🔁
- U+1F502 🔂
- U+21AA(+FE0F) ↪️
- U+1F504 🔄
- U+1F503 🔃

**Comment by sensibleworld** [comment]
Cleaning up some older issues, and wanted to note that we have `repeat` and `repeat-1` icons in version 5. https://fontawesome.com/icons?d=gallery&q=repeat&s=solid
