### ISSUE TITLE
Icon request: Spotify

### ISSUE THREAD

**Issue by codebryo** [FortAwesome/Font-Awesome#330]
I'd love to see the Spotify Icon in the icon set. It can be used for linking to a special playlist I created or something. Does it make sense to you ? Or do you not want to start puting different services as icons into the font. 
BTW: I love this project.

**Comment by djmoiz** [comment]
i would like to get it too :)

**Comment by tagliala** [comment]
@djmoiz http://fontawesome.io/icon/spotify/
