### ISSUE TITLE
Icon request: fa-dusk

### ISSUE THREAD

**Issue by Estiathla** [FortAwesome/Font-Awesome#3302]
I'm making a mobile weather application for my college project, and I notice that you don't have any dusk and dawn icon on your repository. I need it for a page that contains information about the time of the dusk and the dawn. If you cold create something like that: https://cdn3.iconfinder.com/data/icons/weather-icons-2/64/Sunset-128.png.  I appreciate.

**Comment by sensibleworld** [comment]
We've added a sunset and sunrise icon to Font Awesome Pro:

https://fontawesome.com/icons/sunset?style=solid
https://fontawesome.com/icons/sunrise?style=solid
