### ISSUE TITLE
The hands of the clock in fa-clock-o are not horizontally centered

### ISSUE THREAD

**Issue by MrAlexLau** [FortAwesome/Font-Awesome#3303]
The hands of the clock on the fa-clock-o icon are not horizontally centered.
![screen_shot_2014-04-24_at_11_59_53_am](https://cloud.githubusercontent.com/assets/75554/2792423/3c0a7c6e-cbd2-11e3-825d-757e3b2683b7.png)

**Comment by tagliala** [comment]
@luxzg about spinning issues, please refer to #671

**Comment by tagliala** [comment]
I think this has been fixed in version 5.0
