### ISSUE TITLE
icon request: blackboard

### ISSUE THREAD

**Issue by tlu74** [FortAwesome/Font-Awesome#3308]
Hello,
i am working on a medical app, so i would need some new icons. 
- teaching (for example a blackboard, http://www.flaticon.com/search/blackboard) 
  thanks in advance
  thanks for the great work
  tom

**Comment by pisanofab** [comment]
+1

**Comment by WastedCharlie** [comment]
+1 for blackboard / easel icon.

**Comment by MVcodeartbr** [comment]
+1 releted to #8004

**Comment by pypetey** [comment]
+1

**Comment by lomcarlo** [comment]
+1

**Comment by aidan-fitz** [comment]
+1 for blackboard icon

**Comment by mrwunderbar666** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=blackboard
