### ISSUE TITLE
icon request: fa-truck-o

### ISSUE THREAD

**Issue by arzynik** [FortAwesome/Font-Awesome#3311]
![image](https://cloud.githubusercontent.com/assets/27974/2806091/a9f09ab0-ccc2-11e3-9dfb-7b7092051809.png)

**Comment by G-Driver** [comment]
+1

**Comment by NinjaCodeVixen** [comment]
+1

**Comment by mike6ds** [comment]
+1

**Comment by jarvisjohnson** [comment]
+1

**Comment by tagliala** [comment]
Hi,

I'm going to close here because this icon is Available in FA5 Pro.

Feel free to keep upvoting this request
