### ISSUE TITLE
Icon Request: icon-strava

### ISSUE THREAD

**Issue by joshuabarney** [FortAwesome/Font-Awesome#3313]
Simply, we are a mountain bike manufacture and we would like to encourage customers/ riders to join our cycling community/ team on strava.com and the plugin we use to link up to various social media outlets uses Font Awesome to congregate icons.

![strava-32](https://cloud.githubusercontent.com/assets/7409853/2806520/4b00d25a-cccb-11e3-9e35-71effe34e54a.png)
![strava-16](https://cloud.githubusercontent.com/assets/7409853/2806522/4f50aeca-cccb-11e3-8224-9aa99146dc82.png)
![strava_logo-229x300](https://cloud.githubusercontent.com/assets/7409853/2806523/511f2b1e-cccb-11e3-96f9-44931f213d88.png)

**Comment by GreenImp** [comment]
I'd definitely like to see this added.

**Comment by internetcasualty** [comment]
+1 
adding my support to this

**Comment by nniiicc** [comment]
+ 1

**Comment by helmet91** [comment]
+1

**Comment by selaias** [comment]
+1

**Comment by sfdye** [comment]
+1

**Comment by amourreux** [comment]
+1

**Comment by kublaios** [comment]
+1

**Comment by Drmakneeo** [comment]
+1

**Comment by iamstuartwilson** [comment]
+1

**Comment by benedict-w** [comment]
+1

**Comment by ryanfb** [comment]
+1

**Comment by jordanschau** [comment]
+1

**Comment by krohn** [comment]
+1

**Comment by welcomebrand** [comment]
+1

**Comment by shoemaker** [comment]
+1

**Comment by lexusburn** [comment]
+1

**Comment by vrinceanuv** [comment]
+1

**Comment by gooch** [comment]
+1

**Comment by tallada** [comment]
+1

**Comment by st3v3nhunt** [comment]
+1

**Comment by iferrer** [comment]
+1

**Comment by fossil12** [comment]
+1

**Comment by digitalcake** [comment]
+1

**Comment by Tafkas** [comment]
+1

**Comment by adamtaylor** [comment]
+1 - it would be great to have it so it could be added to http://lipis.github.io/bootstrap-social/

**Comment by crundberg** [comment]
:+1:

**Comment by romram13** [comment]
I am developing a CMS dedicated for cycling, trails and triathlon races. That icon would be really usefull. (and for my cycling team website too :stuck_out_tongue:)

**Comment by kylemanna** [comment]
+1

**Comment by nathandavies91** [comment]
+1

**Comment by intuitionofmind** [comment]
+1

**Comment by edipdincer** [comment]
+1

**Comment by craigvl** [comment]
+1

**Comment by ianrobrien** [comment]
+1

**Comment by tatianepires** [comment]
+1
I really need this icon! Please.

**Comment by tatianepires** [comment]
Is there an easy guide on how to create a Font Awesome icon?

**Comment by vrinceanuv** [comment]
@tatianepires You can use icomoon to create your custom font. Never imported font awesome to icomoon, might be possible. If you import it to icomoon, you can simple add strava svg icon in the font and then you will have your custom font awesome with strava icon.

**Comment by stuka** [comment]
+ 1

**Comment by davidwells33** [comment]
+1.  Please add Strava

**Comment by codyn329** [comment]
+1

**Comment by MichaelGradek** [comment]
+1

**Comment by zzh8829** [comment]
:+1:

**Comment by spickermann** [comment]
+1

**Comment by bradfordlynch** [comment]
+1

**Comment by caalberts** [comment]
:+1:

**Comment by orome** [comment]
+1

**Comment by dalanzg** [comment]
+1

**Comment by petedavis** [comment]
+1

**Comment by fourstar04** [comment]
+1

**Comment by ka3media** [comment]
+1

**Comment by maxmetcalfe** [comment]
+ 1

**Comment by plod** [comment]
+1

**Comment by clayew** [comment]
+1

**Comment by matallo** [comment]
+1

**Comment by ianmclaughlin** [comment]
+1 
for "Sign in with Strava" OAUTH button

**Comment by dembede** [comment]
+1

**Comment by gurde** [comment]
+1

**Comment by alecjtaylor** [comment]
+1

**Comment by joanllenas** [comment]
+1

**Comment by alwaysbrightblue** [comment]
+1

**Comment by tylerqford** [comment]
+1

**Comment by emre-yilmaz** [comment]
+1

**Comment by asilbalaban** [comment]
+1

**Comment by astarkey** [comment]
+1

**Comment by Oddcity** [comment]
+1

**Comment by ezefranca** [comment]
+1

**Comment by euri10** [comment]
+1

**Comment by diegourban** [comment]
+1

**Comment by leingang** [comment]
+1

**Comment by jocelynkerbourch** [comment]
+1

**Comment by pdohmen91** [comment]
+1 Please add this icon!

**Comment by dynamicsites** [comment]
+1 for the Strava icon, useful for Cycling Teams & Clubs, Bike Shops a.o. 👍

**Comment by andyreid51** [comment]
+1

**Comment by pprucia** [comment]
+1

**Comment by ties585** [comment]
+1

**Comment by jim-ftw** [comment]
+1

**Comment by andrescruz** [comment]
+1

**Comment by andyreagan** [comment]
since it's been over two years, here's what you can do in the meantime.

the attached zip has the strava icons in SVG, unzip this in your fonts directory alongside font awesome. then include it like this (here, unzipped into folder "custom"):
`<img height="18" src="fonts/custom/icon-strava-blue.svg" class="fa-fw fa-lg">`
(also a black svg in the zip, and of course you could set the color using CSS).

here's an example of these being used:
[http://compstorylab.org/share/papers/dodds2014a/team.html](http://compstorylab.org/share/papers/dodds2014a/team.html)

svgs (provided by strava):
[strava-icons.zip](https://github.com/FortAwesome/Font-Awesome/files/439781/strava-icons.zip)

**Comment by stvhwrd** [comment]
+1

**Comment by stvhwrd** [comment]
+1

**Comment by leseb** [comment]
+1

**Comment by Krevo** [comment]
+1

**Comment by justinrummel** [comment]
+1

**Comment by chmouel** [comment]
+1

**Comment by jonbev** [comment]
+1

**Comment by cdobson** [comment]
+1

**Comment by jd** [comment]
+1

**Comment by charliecooper45** [comment]
+1 please

**Comment by kevinbalicot** [comment]
+1

**Comment by flokli** [comment]
@tagliala: Is there anything that helps in bringing this further? I think, sufficient people added their :+1: rection to this issue…

**Comment by dynamicsites** [comment]
@flokli hopefully, we only need to wait until the release of the next FA version. This thread started two and a half years ago, but more than half of the "thumbs up" reactions were given during 2016.

@tagliala

**Comment by cdobson** [comment]
As an alternative to what @andyreagan kindly provided a couple of months ago, I've made this SVG:

[strava.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/524063/strava.svg.zip)

.. It's the logo without the shield, which I think looks a bit better if your icon is going to be tiny. The background colour is white because I'm using it for bootstrap-social, but you can edit this in the SVG.

**Comment by mfillon** [comment]
:+1:

**Comment by gchenuet** [comment]
+1

**Comment by guiferrpereira** [comment]
+1

**Comment by mshiner** [comment]
+1

**Comment by cloudwales** [comment]
+1

**Comment by mymagicalpants** [comment]
+1

**Comment by kylemanna** [comment]
Could try getting some Strava people to notice and suppor the Kickstarter: https://twitter.com/2bluesc/status/798346685403394048

**Comment by simonech** [comment]
+1

**Comment by jverdeyen** [comment]
+1

**Comment by scottgrayson** [comment]
+1

**Comment by przemek207** [comment]
+1

**Comment by beol** [comment]
+1

**Comment by erwinrietveld** [comment]
+1

**Comment by JoeFoxJr** [comment]
+1

**Comment by SuperAtic** [comment]
+1

**Comment by udos** [comment]
+1

**Comment by doodsz** [comment]
+1

**Comment by simashin** [comment]
+1

**Comment by danielmarkavis** [comment]
+1

**Comment by flokli** [comment]
@tagliala : Apart from everybody adding +1 below this issue, is there anything that can be done to get this in?

**Comment by tagliala** [comment]
@flokli yes, you could [customize font awesome](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) fork the repo, add the missing icon and share your fork here

**Comment by flokli** [comment]
@tagliala Yes, this could help in discussion about shapes and forms etc. I'll try to come up with a font containing all fontawesome icons, and the strava icon on top.

But what is the right way to build a pull request to get this in? Most likely, I'd need a full-blown font editor to add it to the font files (without potentially discarding some information), right?

**Comment by tagliala** [comment]
> But what is the right way to build a pull request to get this in?

Problem is that we are not accepting PR containing new icons, mostly (but not entirely) because of the binary nature of the `.otf` file used by dave for development.

> Most likely, I'd need a full-blown font editor to add it to the font files (without potentially discarding some information), right?

Yes, if you fork the repo and edit the `.otf` file, you would need a font editor. Sorry but I can't answer about the loss of information because I'm not a font developer. AFAIK Dave uses Illustrator and the .otf file but I may be completely wrong 🙌

**Comment by bessone** [comment]
As a founder, I made the request in the appropriate thread on brand icons for Font Awesome 5

**Comment by flokli** [comment]
I created a font including the strava icon, in case somebody wants to [take a look](https://mega.nz/#!F4hDkaAZ!77osNKBIXWMKYtzkL7_TtvlobKvY-8rDipGFO44EFw0).
SVG can be found [here](https://mega.nz/#!ZtQmyYqC!W7uotPgM-gCI5cC0zH5F76h9VWejHU1lYL9k8K4FU18).

**Comment by KentFack** [comment]
I'll add a +1 here. I see there have been several workarounds presented in the thread above, but speaking as an entry-mid level coder/developer, I'd much rather have the icon added to the official FA set. Just my .02

**Comment by bigbash** [comment]
+1

**Comment by haackr** [comment]
+1

**Comment by jacola** [comment]
+1

**Comment by nicole-brewer** [comment]
+1

**Comment by mgmart** [comment]
+1

**Comment by babalucas** [comment]
+ 1

**Comment by arrancurran** [comment]
still waiting :/

**Comment by j-d-b** [comment]
I'll add my +1 here; would be great.

**Comment by mkrohmann** [comment]
+1

**Comment by yaaki** [comment]
+1

**Comment by dkjaer** [comment]
+1

**Comment by bpowley** [comment]
+1

**Comment by teesche** [comment]
+1

**Comment by steventlee** [comment]
any status on this? +1

**Comment by sbuscher** [comment]
+1

**Comment by mcjimbob** [comment]
+1

**Comment by bdlangton** [comment]
+1

**Comment by aligg** [comment]
+1!

**Comment by jgonsior** [comment]
+1

**Comment by sircodesalittle** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by yhzgirl** [comment]
+1

**Comment by jeremiaspereira** [comment]
+1

**Comment by simonech** [comment]
I can't believe the icon released in FA5 is the wrong one 
it's just the name strava, not the logo

**Comment by tagliala** [comment]
@simonech hi,

I think this is the reason of the choice: https://strava.github.io/api/v3/guidelines/

**Comment by tagliala** [comment]
Sorry for the double post

@simonech thanks for opening a new request, it makes more sense.

Let's discuss about the current implementation of Strava logo here: #11866

(please do not +1 #11866, it doesn't help)

**Comment by cdobson** [comment]
@tagliala I don't think the API brand guidelines are relevant in every use case - you may simply be using the Stava icon to link to someone's profile.. Either way it looks like Strava has ditched the condensed icon for everything other than their favicon, which may be why FA elected to use the longhand version.

Just a reminder to everyone of the following alternative solutions:

https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-242795145
https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-253169719
https://github.com/FortAwesome/Font-Awesome/issues/3313#issuecomment-279815447

**Comment by tagliala** [comment]
@cdobson thanks. Please add your comment to #11866.

Please also let us know if there an official strava monochrome svg logo and brand guidelines

Sorry, I'm going to lock here to avoid spamming +1ers but we can keep discussion on #11866

🔒
