### ISSUE TITLE
Icon request: ravelry

### ISSUE THREAD

**Issue by amberweinberg** [FortAwesome/Font-Awesome#3314]
Social media icon for www.ravelry.com - plan on using it everywhere :P

![search](https://cloud.githubusercontent.com/assets/891995/2806550/0dcd55e2-cccc-11e3-96ca-67e12c48ce0f.jpg)

**Comment by bitterpurl** [comment]
+1

**Comment by franhaselden** [comment]
+1 though I think the Ravelry "ball" would be great too

**Comment by iambrianna** [comment]
+1

**Comment by tagliala** [comment]
+1 (https://github.com/FortAwesome/Font-Awesome/issues/1623#issue-17009121)

**Comment by tagliala** [comment]
+1 (https://github.com/FortAwesome/Font-Awesome/issues/2712#issue-25268179)

**Comment by wspeir** [comment]
+1

**Comment by julia-r** [comment]
+1

**Comment by juliabode** [comment]
+1

**Comment by arielbl** [comment]
+1

**Comment by pennys** [comment]
+1

**Comment by titusfortner** [comment]
+1

**Comment by caseyf** [comment]
In case it helps, here is a svg/webfont for the little 'r'

http://skitch2.ravelrycache.com/ravelry-webfont-20150903.zip

**Comment by amberweinberg** [comment]
@caseyf That helps, would just be nice to keep everything in one icon file!

**Comment by amberweinberg** [comment]
+1 for ravelry ball idea too - though not sure what that would look like in one color.

**Comment by caseyf** [comment]
The 'r' is just a plain Gill Sans 'r' so I'm not positive that it is ok to use. 

The ball might not be very recognizable at small sizes in one color but I could play with it.

**Comment by mstmarie1** [comment]
socicon has the ball implemented, would be great to get it added here as well.
+1

**Comment by fhannip** [comment]
+1

**Comment by pklapperich** [comment]
There's a direct open-source clone of gill sans in medium weight called Sans Guilt. If medium weight is ok, one could install sans guilt and use that to make the r for the vector graphic and avoid any legal issues with Gill Sans. Though this might not even be necessary.

According to Wikipedia, Gill Sans went out of copyright in the parts of the world where it was copyrightable in 2011, but the name "Gill Sans" remains a registered trademark, so open source clone fonts have to have a different name. That is, the shape of the r isn't protected, but just the name "Gill Sans". Font-Awesome isn't going to use that language when describing this icon, so it might all be moot.

**Comment by jessicajohannesen** [comment]
+1

**Comment by jessicajohannesen** [comment]
I'd prefer the r over the ball.

**Comment by tertiaryidentifier** [comment]
+1

**Comment by xtina** [comment]
+1

**Comment by linuscorin** [comment]
+1
Don't mind whether it's the 'r' or the 'ball'

**Comment by ilumire** [comment]
+1
I'd prefer the ball. Any news on the status of this?

**Comment by Annaleria** [comment]
+1
Yes please for this icon

**Comment by davegandy** [comment]
Added to 4.7.0 release. Should be forthcoming shortly!

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch. @talbs love him some yarn.

**Comment by talbs** [comment]
More accurately, my lady loves her some yarn. Glad to show Ravelry and knitters a little bit of love. 😄
