### ISSUE TITLE
Icon Request: Docker [will be available in Font Awesome 5]

### ISSUE THREAD

**Issue by ubermuda** [FortAwesome/Font-Awesome#3316]
Docker (http://docker.io) is all the rage right now in the Devops world. Font-Awesome needs to have an icon for it.

![Docker](https://www.docker.io/static/img/homepage-docker-logo.png)

**Comment by pbelmann** [comment]
+1

**Comment by jgkamat** [comment]
@muuki88 that icon looks amazing!

**Comment by muuki88** [comment]
Thanks xD, but I just found it. All credits to @wesbos

**Comment by Ranjandas** [comment]
Thank you @wesbos

**Comment by stapelberg** [comment]
+1

**Comment by plaperdr** [comment]
+1

**Comment by sonata82** [comment]
+1

**Comment by tduchateau** [comment]
+1

**Comment by declension** [comment]
:+1:

**Comment by muuki88** [comment]
are there any legal issues? @wesbos and docker must agree, right?

**Comment by vania-pooh** [comment]
+1

**Comment by wesbos** [comment]
@muuki88 probably - but Docker shared it on their twitter so I'm pretty sure they are okay with it

**Comment by muuki88** [comment]
Nice. And you are also fine :)

**Comment by fxdgear** [comment]
@wesbos why don't you make a PR

**Comment by wesbos** [comment]
@fxdgear they aren't currently taking PRs

**Comment by fxdgear** [comment]
@wesbos boo!! :-1:

**Comment by qenchi** [comment]
+1

**Comment by Galmido** [comment]
+1

**Comment by janeczku** [comment]
+1

**Comment by bubbl** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by jeje-50** [comment]
+1

**Comment by donovansolms** [comment]
+1

**Comment by demarant** [comment]
+1 
needed for improving https://github.com/rancher/rancher/issues/2766

**Comment by verkkoberg** [comment]
+1

**Comment by winsento** [comment]
+1

**Comment by hainesr** [comment]
+1

**Comment by davegandy** [comment]
More discussion here: https://github.com/docker/docker/issues/18264

**Comment by Dev-Crea** [comment]
+1

**Comment by gbolo** [comment]
+1

**Comment by joschuck** [comment]
+1

**Comment by pcgeek86** [comment]
+1

**Comment by rosiecakes** [comment]
+1

**Comment by gcuisinier** [comment]
+1

**Comment by nicholasdille** [comment]
+1

**Comment by ben-st** [comment]
+1

**Comment by zhujinhe** [comment]
+1

**Comment by oarrabi** [comment]
+1

**Comment by migarol** [comment]
+1

**Comment by andrey-borue** [comment]
+1

**Comment by vicary** [comment]
+1

**Comment by ColonelPanicks** [comment]
+1

**Comment by zhujinhe** [comment]
This issue was opened on Apr 26 2014. 
Is anyone dealing with this issue?

**Comment by davegandy** [comment]
We've not been dealing with this issue, as it was not our issue. Please read full details here: https://github.com/moby/moby/issues/18264

However, at some point since that discussion, the [Docker Brand Guidelines](https://www.docker.com/brand-guidelines) have been updated. There's an approved appropriate version now, so this is going into 5.0.

**Comment by dodjango** [comment]
+1

**Comment by hardikgw** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
