### ISSUE TITLE
Icon Request: fa-nuclear

### ISSUE THREAD

**Issue by jbx1** [FortAwesome/Font-Awesome#3325]
An icon to be used to indicate nuclear energy
To be used for energy related applications / websites etc.

**Comment by cserpell** [comment]
+1

**Comment by otherholli** [comment]
+1

**Comment by amrocs** [comment]
+1

**Comment by meyersbs** [comment]
+1

**Comment by ColKlink** [comment]
+1

**Comment by sensibleworld** [comment]
Do any of these work for this request? https://fontawesome.com/icons?d=gallery&q=nuclear
