### ISSUE TITLE
Icon Request: fa-solar-panel

### ISSUE THREAD

**Issue by jbx1** [FortAwesome/Font-Awesome#3326]
An icon to indicate solar energy through solar panels.
To be used for energy related applications / websites etc.

**Comment by cnordin** [comment]
+1

**Comment by caduvieira** [comment]
+1

**Comment by Flofre** [comment]
+1

**Comment by amrocs** [comment]
+1

**Comment by 13** [comment]
+1

**Comment by EESAdmin** [comment]
+1

**Comment by pablotr87** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by aliebold** [comment]
+1

**Comment by facug91** [comment]
+1

**Comment by edisonsalazatr** [comment]
Hi, I create my own icon, but how I put it in my custom.css... I create 
.fa-solarPanel:before{
	content:url("../img/panel50px.png");
}
and I used like that:
<i class="fa fa-4x fa-solarPanel text-green mb-3 sr-icons">
It shows my icon but not like a fa native icon...
What I have to do?

**Comment by Leapness** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/solar-panel?style=solid
