### ISSUE TITLE
Icon Request: Strength

### ISSUE THREAD

**Issue by notman** [FortAwesome/Font-Awesome#3345]
I could really use an icon to represent the strength of a result/prediction. I think this is also an icon that many others would find useful too.

As an example, I found this image:
![icon_feats-of-strength](https://cloud.githubusercontent.com/assets/7469737/2867003/cd7eaf2c-d22f-11e3-9a2b-9ec69a07ba64.png)

**Comment by GKolmerer** [comment]
+1

**Comment by jhartling** [comment]
+1

**Comment by christoval** [comment]
+1

**Comment by bull-xu-stride** [comment]
+ 1

**Comment by kimimilawinyan** [comment]
PLEASE!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #2076, please add a 👍  reaction to that request.

Please make sure you [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
