### ISSUE TITLE
Icon Request: icon-badge-percent

### ISSUE THREAD

**Issue by oneoman** [FortAwesome/Font-Awesome#3348]
![flaticon_17800 4](https://cloud.githubusercontent.com/assets/7470268/2868031/65ffc4a2-d23f-11e3-9378-5610cd4e53dc.png)

A promotion icon like this if possible please ?

**Comment by AminurRouf** [comment]
I would like this icon also.

**Comment by aethior** [comment]
Hi @oneoman,

This icon was added in v5.3.0.
Check https://fontawesome.com/icons/badge-percent

Regards.

cc/ @tagliala
