### ISSUE TITLE
Icon Request: fa-text-marker

### ISSUE THREAD

**Issue by benbro** [FortAwesome/Font-Awesome#3352]
A text marker and pen icons are useful for text editors and painting apps.
Examples:

fa-text-marker
![flaticon_33711](https://cloud.githubusercontent.com/assets/75841/2870404/6233b4d4-d2c4-11e3-9740-7918f92a1956.png)
from
http://www.flaticon.com/free-icon/marker-in-slanting-position_33711

fa-pen
![pen](https://cloud.githubusercontent.com/assets/75841/2870401/dc084d66-d2c3-11e3-99cd-b7d6f2cafb9b.png)
from http://www.brankic1979.com/icons/

It will be great if it's possible to have the icons in several colors.
The marker should only color the tip and the main body.
The pen should color the cap, main body and tip.

Thanks

**Comment by tagliala** [comment]
icon marker is a duolicate of #2095
