### ISSUE TITLE
Icon Request: mustache / moustache

### ISSUE THREAD

**Issue by simmel-z** [FortAwesome/Font-Awesome#3356]
I would love to see a mustache icon.
something like below

![bildschirmfoto 2014-05-04 um 15 22 51](https://cloud.githubusercontent.com/assets/6171309/2873076/388cdcac-d38f-11e3-9d53-e5ea222a7b30.png)

**Comment by calebhailey** [comment]
:+1:

**Comment by amdprophet** [comment]
+1

**Comment by bradherman** [comment]
:+1:

**Comment by shefik** [comment]
+1

**Comment by bristophocles** [comment]
+1

**Comment by psimonov** [comment]
+1

**Comment by cthiebaud** [comment]
+1

**Comment by BobbyJohansen** [comment]
+1

**Comment by lcolombx** [comment]
+1

**Comment by maturski** [comment]
+1

**Comment by rychardguedes** [comment]
would be perfect for no shave november

**Comment by pingunaut** [comment]
+1

**Comment by NachoColl** [comment]
+1

**Comment by patito** [comment]
+1

**Comment by lemikeone** [comment]
+1

**Comment by TheoC0m** [comment]
+1

**Comment by tarnap** [comment]
+1

**Comment by rickhub** [comment]
+1

**Comment by loganjahnke** [comment]
+1

**Comment by JoFleming-Mo** [comment]
+1

**Comment by HZooly** [comment]
+1

**Comment by dejvidko** [comment]
+1

**Comment by Pyvonix** [comment]
+1

Solid version:
![image](https://user-images.githubusercontent.com/18658299/194807276-f4de7f06-bbd8-44ac-96a9-0e3af18e486c.png)

Light version:
![image](https://user-images.githubusercontent.com/18658299/194807497-14f7aae7-96ae-4bcb-8646-86444e8bf4b4.png)

**Comment by Noichiboy** [comment]
+1

**Comment by sensibleworld** [comment]
We've got this in the works, and it should be in our next release!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mustache?s=solid&f=classic
