### ISSUE TITLE
Icon Request: Retro Video Games

### ISSUE THREAD

**Issue by Zakuska** [FortAwesome/Font-Awesome#3364]
Retro Video Games Section
-PacMan
-Ghost
-Dot
-Cherries
-PowerUp
-Qbert
-Mario
etc.

**Comment by SaphuA** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/circle-three-quarters?s=solid
https://fontawesome.com/icons/ghost?s=solid
https://fontawesome.com/icons/circle-three-quarters?s=solid
https://fontawesome.com/icons/circle-small?s=solid
https://fontawesome.com/icons/cherries?s=solid

https://fontawesome.com/icons/block-question?s=solid
https://fontawesome.com/icons/coin-vertical?s=solid
