### ISSUE TITLE
JSON or XML feed

### ISSUE THREAD

**Issue by charl-kruger** [FortAwesome/Font-Awesome#3366]
Hi, could you not get a json or xml link up as yaml requires pecl for php :(
the yml feed: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/src/icons.yml

Would be awesome as we want to check for updates and what new fonts are available since our last stable transport.

Let me know and thanks for an awesome product

**Comment by james2doyle** [comment]
I made one here for Font Awesome 4.5.0 https://gist.github.com/james2doyle/3d7ad018e6b6abed7957

**Comment by ju1ius** [comment]
Even more awesome would be to include this JSON file in the npm package !
:pray:

**Comment by mlazowik** [comment]
Related: #8852

**Comment by tagliala** [comment]
I think this has been implemented a while ago with the JSON icon file

It's available in the metadata folder: https://github.com/FortAwesome/Font-Awesome/tree/6.x/metadata
