### ISSUE TITLE
Mac Safari 7.0.2+ font-family on .fa class

### ISSUE THREAD

**Issue by briananderson1222** [FortAwesome/Font-Awesome#3368]
I ran into an issue that existed only on Mac versions of Safari where the font was not getting loaded most of the time. I would create a jsFiddle but the way that jsFiddle runs the page it does not seem to be reproducible in this context. The fix I have used for now is to put quotes around the font-family declaration in the .fa class. 

I am quite puzzled that I have not seen anyone else post anything about this issue and it makes me wonder the validity of this catch. It seems quite obvious that we should have quotes around the font-face that was defined but at the same time it seems to work fine in Chrome, IE, Firefox, and even in Safari.. but Safari was only working in specific situations. I would love some insight into why this is happening but for now this fix seems to do the trick for me.

Changing the following line seems to fix this issue:

OLD
.fa {
font-family: FontAwesome
}

NEW
.fa {
font-family: 'FontAwesome'
}

**Comment by hellifiknow** [comment]
I have been running into this very issue with Safari for a web app I'm working on. 
@tagliala - the issue will not present itself unless cache is enabled. From what I have seen it happens when the Safari cache gets stale. When this happens Safari won't load the font file referenced in the css. 

Here is how I fixed it for my situation. Include this javascript in your page: 

	function addDeclaration(css){
	    if (document.createStyleSheet){
	        var st = document.createStyleSheet();
	        st.cssText = css;
	    } else {
	        var st = document.createElement('style');
	        st.textContent = css;
	        document.getElementsByTagName('head')[0].appendChild(st);    
	    }
	    
	};		

	var css = '@font-face {'+
	'    font-family: \'FontAwesome\';'+
	'    src: url(\'//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?v=4.2.0\');'+
	'    src: url(\'//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts//fontawesome-webfont.eot?#iefix&v=4.2.0\') format(\'embedded-opentype\'), url(\'//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0\') format(\'woff\'), url(\'.//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.ttf?v=4.2.0\')'+
	'format(\'truetype\'), url(\'//netdna.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular\') format(\'svg\');'+
	'    font-weight: normal;'+
	'    font-style: normal'+
	'}'+
	'.fa {'+
	'    display: inline-block;'+
	'    font: normal normal normal 14px/1 FontAwesome;'+
	'    font-size: inherit;'+
	'    text-rendering: auto;'+
	'    -webkit-font-smoothing: antialiased;'+
	'    -moz-osx-font-smoothing: grayscale'+
	'}';


 
Add this line to end of your document.ready: 
	`addDeclaration(css);`

This will cause Safari to load the font file and the icons will display correctly.

**Comment by tagliala** [comment]
@hellifiknow thanks. so this is a safari issue unrelated to fontawesome?

**Comment by hellifiknow** [comment]
@tagliala Yes, from what I have seen it is a specific issue with Safari caching when a site does an immediate redirect from one page to another and unrelated to fontawesome.

**Comment by tagliala** [comment]
time for a new label :)

**Comment by tagliala** [comment]
closing here

**Comment by renholm** [comment]
@hellifiknow We've seen the same behaviour on our site. Icons work very well the first day or two, on later visits it is replaced by squares. Do you know if this is a known bug tracked somewhere?

@tagliala Not sure this is completely unrelated to fontawesome, we have another font kit and that shows up fine.

![image](https://cloud.githubusercontent.com/assets/60491/7560511/34bd8aea-f7c4-11e4-9cec-d9ba23e0bb90.png)
