### ISSUE TITLE
Firefox fa-spin - Mac Os Maveric 90% CPU

### ISSUE THREAD

**Issue by wordica** [FortAwesome/Font-Awesome#3369]
Hello,

I see problem with spin icons on firefox. When i put it on site - my firefox CPU usage goes to 90%: firefox 70% ,ruby 60% . When i delete spin class - everything back to normal usage.

**Comment by viebel** [comment]
It seems that this bug doesn't occur on Chrome 46 MacOs.
What fixed the issue?

**Comment by wordica** [comment]
I just try to not spin icons. Who knows what the problem is ... in time when I develop flash games, every vector animation increase CPU load as on every change it was "rewriten" ... soo in Actionscript we had an option to cacheAsBitmap or something similar ... it was soo many years ago ... maybe something similars is in here.

**Comment by viebel** [comment]
Do you think it's related to fontawesome upgrade or to chrome upgrade?

**Comment by wordica** [comment]
Chrome ... Authors of Font can't do nothing with it, it just browser "bug" - on FireFox my CPU on macbook pro all the time "boils" :)
