### ISSUE TITLE
Icon Request: MailChimp

### ISSUE THREAD

**Issue by james2doyle** [FortAwesome/Font-Awesome#3379]
They have their brand assets in vector format.

I am thinking the freddie face, in the same style as the bitbucket icon (standalone, in square).

![freddie face](http://static.mailchimp.com/web/brand-assets/Freddie_OG.png)

http://mailchimp.com/about/brand-assets/

**Comment by better-studio** [comment]
+1

**Comment by frensuren** [comment]
+1

**Comment by infn8** [comment]
I've taken the EPS from MailChimp and just converted all colors to black white or transparent.

![mailchimp_freddie_og](https://cloud.githubusercontent.com/assets/2447686/6756622/8476d622-cf01-11e4-9392-80db0defd54d.png)

I have the SVG if anyone wants it only one or two shapes were removed but because the were fill AND stroke transparent

**Comment by james2doyle** [comment]
I have to say I like the @infn8 version best

**Comment by infn8** [comment]
I Fixed up a couple of glitches by the ear and removed the white BG 

![mailchimp_freddie_og](https://cloud.githubusercontent.com/assets/2447686/6756761/6b093418-cf02-11e4-8831-39000f295404.png)
[SVG on Dropbox here](https://dl.dropboxusercontent.com/u/24636493/Mailchimp%20Icon/MailChimp_Freddie_OG.svg)

**Comment by infn8** [comment]
This will likely need to have all strokes converted to fills and then have all white removed before going in the font.  The white reliefs are currently overlapped stroke which will not work in a font vector.

**Comment by infn8** [comment]
Ok All Strokes converted.  black only.

![mailchimp_freddie_alt](https://cloud.githubusercontent.com/assets/2447686/6758539/531d539a-cf0f-11e4-90e3-b7183cf0f363.png)
[Vector on dropbox](https://dl.dropboxusercontent.com/u/24636493/Mailchimp%20Icon/MailChimp_Freddie_ALT.svg)

**Comment by cuttingedgehobbies** [comment]
:+1:

**Comment by infn8** [comment]
Any word on this?  I can volunteer to add the icon if you like.  let me know and I'll make a pull request.

**Comment by tagliala** [comment]
@infn8 sorry, [we do not accept PR containing icons](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#pull-requests) but you are free to fork FontAwesome, add this icon and share your fork are

**Comment by infn8** [comment]
Thanks for the clarification @tagliala.  What is the process for approving icon requests like this one.  can we expect the core font awesome team to integrate this icon in the future?

**Comment by tagliala** [comment]
@infn8 the decision is influenced on popularity but it's up to Dave.

This request is not so popular.

Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by infn8** [comment]
@tagliala I understand.  But that list isn't really sorted by popularity but by comment count.

**Comment by infn8** [comment]
I

**Comment by infn8** [comment]
Guess

**Comment by infn8** [comment]
I'll

**Comment by infn8** [comment]
Have

**Comment by infn8** [comment]
To

**Comment by infn8** [comment]
Wait

**Comment by infn8** [comment]
for

**Comment by infn8** [comment]
more

**Comment by infn8** [comment]
comments

**Comment by infn8** [comment]
Joking (sort of) :wink:

**Comment by renanmedina** [comment]
+1

**Comment by infn8** [comment]
All jokes aside, thanks @tagliala for the great info.  I have Added this to FontAwesome using [IcoMoon](http://icomoon.io) 

* [Here is the IcoMoon Project on Dropbox](https://dl.dropboxusercontent.com/u/24636493/Mailchimp%20Icon/Font%20Awesome%20%2B%20Mailchimp.json)
* You can load that project [here](https://icomoon.io/app/#/projects)
    * Just choose import project and toss in that json file.  Mailchimp will be the last icon in the set. and called 'mailchimp'
* you can then press generate font at the bottom.

Done!

[![Boom Jamie Boom](http://media.giphy.com/media/3oEduG02C3ZO4D1lIs/giphy.gif)](https://www.youtube.com/watch?v=HJSn43DtnB4)

**Comment by TJohnson93** [comment]
+1

**Comment by ecksteing** [comment]
+1

**Comment by rabrowne85** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by marqu3z** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by domoconnell** [comment]
+1

**Comment by davesouthey** [comment]
+1

**Comment by feeling4design** [comment]
+1

**Comment by RensTillmann** [comment]
+1

**Comment by Darep** [comment]
+1

**Comment by atomical** [comment]
+1

**Comment by kublermdk** [comment]
For an AI file, SVG or PNG version you can also try :
https://github.com/FlikD/mailchimpicon

![Mailchimp Icon Flik Design](https://github.com/FlikD/mailchimpicon/blob/master/icon-mailchimp.2x.png?raw=true)

**Comment by runmael** [comment]
+1

**Comment by jorgevrgs** [comment]
+1

**Comment by nsemak** [comment]
+1

**Comment by sburkett** [comment]
+1

**Comment by mbejda** [comment]
+1

**Comment by bdthemes** [comment]
+1

**Comment by infn8** [comment]
I actually have made a repo for this.  It has MailChimp in Font Awesome.

https://github.com/infn8/Font-Awesome-Plus-Mailchimp

Hopefully that helps

**Comment by ycocatrix** [comment]
+1

**Comment by andrewnmat** [comment]
+1

**Comment by filoveg** [comment]
+2

**Comment by douloh** [comment]
+1

**Comment by jonton11** [comment]
+1

**Comment by juandamz** [comment]
@infn8 Thanks for the icomoon version

**Comment by Enchiridion** [comment]
+1

**Comment by Joaommo1991** [comment]
+1

**Comment by manishth** [comment]
+1

**Comment by tjcrowley** [comment]
+1

**Comment by atomical** [comment]
No longer using MailChimp. I would like to -1 this now. 😄

**Comment by sirber** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mailchimp?style=brands
