### ISSUE TITLE
Icon Request: icon-tapiture

### ISSUE THREAD

**Issue by metasynchronic** [FortAwesome/Font-Awesome#3381]
Good morning all you lovely Font-Awesome people! 
Can we please have a Tapiture icon, in both the basic as well as squared? I am building a site for a brand that uses Tapiture as part of their identity promotion, and would love to have a matching icon for the social links area. I currently use and love many of your other icons and the plug-in for building out social links. 
The link: http://tapiture.com/

Thank you! You are wonderful!!

**Comment by aethior** [comment]
Hi

Tapiture was closed in 2015. ([more info](https://en.wikipedia.org/wiki/Leo_Resig#Tapiture))
The domain corrently redirect to the Playboy webstore.

cc/ @tagliala
