### ISSUE TITLE
Icon request: icon-database

### ISSUE THREAD

**Issue by adelawalla** [FortAwesome/Font-Awesome#3384]
Hi, I was wondering if it would be possible to add a database icon. I was thinking something along the lines of this: https://cdn1.iconfinder.com/data/icons/database/PNG/512/Database_1.png. Thanks!

**Comment by rpsmedia** [comment]
+1

**Comment by tagliala** [comment]
@rpsmedia a database icon is already here: http://fontawesome.io/icon/database/
