### ISSUE TITLE
Icon request: fa-user-with-tie (manager, admin)

### ISSUE THREAD

**Issue by PaulSenkel** [FortAwesome/Font-Awesome#3397]
Like the fa-user, but with a tie.
Can be used in any hierarchy situations (HR manager > employee, Customer account manager > customer, Bank account manager > account holder, etc.).

Thanks a lot in advance !!

PS: Yes, it's awesome !!

**Comment by picitujeromanov** [comment]
+1

**Comment by kevinbarone** [comment]
+1

**Comment by Grimdari** [comment]
I could definitely use this in my sites.  +1

**Comment by migig** [comment]
+1

**Comment by daprezjer** [comment]
:+1:

**Comment by katie1348** [comment]
This would be more useful.

**Comment by Dan-Brantze** [comment]
+1

**Comment by stijnvanbael** [comment]
+1

**Comment by hainguyen81** [comment]
+1

**Comment by MartinsThiago** [comment]
+1

**Comment by BadChoice** [comment]
+1

**Comment by BorzdeG** [comment]
+1

**Comment by Fran4vila** [comment]
+1,  some company icons (manager, chair, ...) will be appreciated!

**Comment by saira3** [comment]
+1

**Comment by beliys** [comment]
+1 need for level access - admin, manager, user

**Comment by jfoo** [comment]
+1

**Comment by allenluce** [comment]
+1

**Comment by jancel** [comment]
+1

**Comment by mathshane** [comment]
+1

**Comment by ellenhutchings** [comment]
+1

**Comment by Stormcloud** [comment]
+1

**Comment by YashKumarVerma** [comment]
+1

**Comment by rclakmal** [comment]
+1

**Comment by toddjcrane** [comment]
+1

**Comment by hw-nf** [comment]
+1

**Comment by kevnk** [comment]
+1

**Comment by yurijmi** [comment]
+1

**Comment by suleimanmahmoud** [comment]
+1

**Comment by DelightRun** [comment]
+1

**Comment by ronlut** [comment]
+1

**Comment by carauzs** [comment]
+1

**Comment by caioc** [comment]
+1

**Comment by MartinsThiago** [comment]
Hey people... why don't you use svg instead? it's fairly well supported.

One of the biggest advantages in my opinion is we can bundle together only the icons in use, then our users waste less bandwidth

**Comment by tehseentechlogix** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

Here are two icons of a user with a tie: [Administrator Male](https://icons8.com/icon/3707/administrator-male) and [Businessman](https://icons8.com/icon/502/businessman).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by khalilst** [comment]
@visualpharm I think this is preface of a history book called **The Fall Of Font-Awesome Empire **

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-tie?style=solid

**Comment by JoeMurray** [comment]
Any suggestions for what fontawesome icon to use for a manager or supervisor that is gender neutral. Wouldn't want to push idea that more senior roles are exclusively or predominantly for men. Especially in my use case where they are mainly women.

**Comment by tagliala** [comment]
@JoeMurray maybe [user-shield](https://fontawesome.com/icons/user-shield?style=solid) or [custom user star](https://jsfiddle.net/tagliala/e1bfz6gc/7/) ?

**Comment by Samerkassem** [comment]
> Any suggestions for what fontawesome icon to use for a manager or supervisor that is gender neutral?Wouldn't want to push idea that more senior roles are exclusively or predominantly for men. Especially in my use case where they are mainly women.

Women wear ties too.
