### ISSUE TITLE
Icon Request: icon-party-balloon

### ISSUE THREAD

**Issue by djtechonline** [FortAwesome/Font-Awesome#3398]
A party balloon icon would be great for party titles in event planning, etc.
This should not be the same as the hot-air ballon you could ride in.

Variation: maybe 2 or 3 balloons behind each other with the icon-party-balloons (plural)

![th](https://cloud.githubusercontent.com/assets/7561947/2949437/e41257b6-da0e-11e3-81ad-1ad0b3e2cf8c.jpeg)

**Comment by felipefrancisco** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by oscar-b** [comment]
+1

**Comment by patchee500** [comment]
+1

**Comment by mths0x5f** [comment]
+1

**Comment by jimmyrleung** [comment]
+1

**Comment by Partyistadominique** [comment]
is there already a balloon icon which I can use???? I can't find anything.....

**Comment by michaelpaps** [comment]
+1

**Comment by doggiephotographer** [comment]
+1

**Comment by bellenot** [comment]
+1

**Comment by danielcongrove** [comment]
+1

**Comment by panniru** [comment]
+1

**Comment by iMylene** [comment]
+1

**Comment by mvr320** [comment]
+1

**Comment by 0xJoey** [comment]
+1

**Comment by nebojisa** [comment]
+1

**Comment by thijskh** [comment]
@djtechonline Judging from the responses there is still significant interest in 🎈. I’m not sure why you closed it, but would be nice if it could be kept open.

**Comment by sensibleworld** [comment]
<img width="714" alt="Screen Shot 2021-03-30 at 12 12 53 PM" src="https://user-images.githubusercontent.com/529604/113021137-428f5400-9151-11eb-90cc-03a627876b1f.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
