### ISSUE TITLE
Icon Request: Miro

### ISSUE THREAD

**Issue by gaplauche** [FortAwesome/Font-Awesome#3404]
It's a popular podcast podcast directory and podcatcher and music and video player.

http://www.getmiro.com/

http://www.miroguide.com/

![](http://1.bp.blogspot.com/-yJ77GKPYQYg/T6Jp9nUeZcI/AAAAAAAAEJA/ElVpzh8ZYTs/s1600/Miro+5.0+Free+Download.png)

![](http://upload.wikimedia.org/wikipedia/commons/c/cb/Miro_icon.png)

**Comment by tagliala** [comment]
Closing here because of:

> The Participatory Culture Foundation no longer develops Miro.[[4]](https://en.wikipedia.org/wiki/Miro_(video_software)#cite_note-4) The last version (6.0) was released in 2013 and is no longer functioning correctly because of changes to the YouTube API.[[citation needed](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)]

Ref: https://en.wikipedia.org/wiki/Miro_(video_software)
