### ISSUE TITLE
Icon Request: accomodation

### ISSUE THREAD

**Issue by knezdusan** [FortAwesome/Font-Awesome#3409]
Hi,

I realy appreciate your effort to provide awesome and comprehensive incon font set. I would suggest to add some travel and accomodation icons like:
WiFi
Lift
Air conditioning
Washing m.
Kitchen implements
Balcony
Heating
Dryer
Toaster
Private terrace
Oven
Blender
Microwaves
Iron
TV
Fridge
Towels
Swimming pool
TV satellite
Freezer
Bed linen
Private car park
DVD
Dishwasher
Jacuzzi
Stereo
Coffee maker
Hair dryer
Safe box
Kettle
Fans
Baby cot

Those amenities are not only for traveling purpose but may be use for many general purposes as wll, so I think may be a great additional section to your existing list.

Thank you for consideration and keep doing a great job!

**Comment by piergi74** [comment]
+1 for baby-cot

**Comment by tagliala** [comment]
@piergi74 please open a new request

**Comment by manojsa** [comment]
> Hi,
> 
> please split this request in single requests, following these rules: [Requesting New Icons](https://github.com/FortAwesome/Font-Awesome/blob/4.1.1-wip/CONTRIBUTING.md#requesting-new-icons)
> 
> Thanks
> 
> Closing here

The above link to create new request is broken/expired. Here is new request for [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
