### ISSUE TITLE
Icon request: icon-drop-percent (humidity)

### ISSUE THREAD

**Issue by Roger-Waters** [FortAwesome/Font-Awesome#3417]
An icon to denote relative humidity would be a great addition

**Comment by jimbo72** [comment]
Same as Roger, an icon to denote relative humidity (drop + percent sign) would be great.
Moreover all needed icon in home automation: water, gas, electricity power, lamp on, lamp off, plug on, plug off, pressure, noise etc etc

**Comment by iweindesmedt** [comment]
+1

**Comment by hkasera** [comment]
+1

**Comment by tchellomello** [comment]
+1

**Comment by angelarucci** [comment]
+1

**Comment by jimmykane** [comment]
+1

**Comment by strelniece** [comment]
+1

**Comment by tagliala** [comment]
Renamed to `Icon request: icon-drop-percent` to follow contributing guidelines

**Comment by keitetran** [comment]
+1

**Comment by prgsavi** [comment]
+1

**Comment by sensibleworld** [comment]
We introduced these in 5.5 

https://fontawesome.com/icons/humidity?style=solid
https://fontawesome.com/icons/dewpoint?style=solid
