### ISSUE TITLE
fa-text-width, fa-text-height, fa-font could be improved

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#3418]
http://fontawesome.io/icon/text-height/
http://fontawesome.io/icon/text-width/

fa-text-width and fa-text-height icons are better than before but there is margin of improvement. "T"s are asymmetric and seem handwritten

![image](https://cloud.githubusercontent.com/assets/556268/2983407/83021436-dc23-11e3-8228-c551cf01b5e6.png)

They also are poorly aligned to the grid at small font sizes (text-width in particular)

`fa-font` has similar issues
![image](https://cloud.githubusercontent.com/assets/556268/2995118/4e567d0c-dcd8-11e3-973f-2debe2872cce.png)

**Comment by sensibleworld** [comment]
@tagliala Closing this, as we're unlikely to make any changes to version 4 at this point :)

**Comment by tagliala** [comment]
Actually, this has been definitely fixed in FA 5.0.0
