### ISSUE TITLE
fa-code-fork is really a merge

### ISSUE THREAD

**Issue by jdsundberg** [FortAwesome/Font-Awesome#3431]
fa-code-fork actually looks like a merge.

fa-code-fork seems like it should be taking a "single" and convert to a "double".

Seems as if there should be both:

fa-code-fork
fa-code-merge

and they could pretty much be the reflection of each other.

**Comment by eggleton** [comment]
As a temporary fix, you can flip the current `fa-code-fork` icon to look like a merge:

    <i class="fa fa-code-fork fa-flip-vertical"></i>

![code-fork normal and flipped vertically](https://cloud.githubusercontent.com/assets/5169887/8842089/1b93c31e-3139-11e5-8951-3f90b3d5c5f3.png)

**Comment by jdsundberg** [comment]
Perfect - thanks.

-John


On Wed, Jul 22, 2015 at 9:50 PM, David Eggleton <notifications@github.com>
wrote:

> As a temporary fix, you can flip the current fa-code-fork icon to look
> like a merge:
>
> <i class="fa fa-code-fork fa-flip-vertical"></i>
>
> [image: code-fork normal and flipped vertically]
> <https://cloud.githubusercontent.com/assets/5169887/8842089/1b93c31e-3139-11e5-8951-3f90b3d5c5f3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/3431#issuecomment-123940923>
> .
>



-- 

*John Sundberg*
Kinetic Data, Inc.
"Your business. Your process."

651-556-0930 I john.sundberg@kineticdata.com
www.kineticdata.com I community.kineticdata.com

**Comment by tagliala** [comment]
In 5.0.0 we have branch and merge

https://fontawesome.com/icons/code-merge?style=solid
https://fontawesome.com/icons/code-branch?style=solid

If code-branch doesn't represent a fork, please open a new issue, provide a single color example and explain why there is the need of a new icon

Closing here
