### ISSUE TITLE
Icon Request: fa-shield-full / fa-shield-full-o

### ISSUE THREAD

**Issue by cuhsat** [FortAwesome/Font-Awesome#3443]
It would be really nice to have two additional fa-shield icons. The current one ist mixed 50/50, so one with a full shield and one with only the shield outline would be great for background purposes.

**Comment by frankeymen** [comment]
+1, got a temporary fix using:

<i class="fa fa-shield fa-shield-full"></i>

adding the following css:

.fa-shield-full:after {
	margin-left:-51%;
	display:inline-block;
  	content: "\f132";
	filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1);
  	-webkit-transform: scale(-1, 1);
  	-ms-transform: scale(-1, 1);
  	transform: scale(-1, 1);
}

**Comment by troyswanson** [comment]
:+1: Some additional options for this icon would be awesome.

**Comment by codenamekt** [comment]
+1

**Comment by sensibleworld** [comment]
We now have a few options for shield icons: https://fontawesome.com/v6.0/icons?q=shield
