### ISSUE TITLE
Icon request: elance

### ISSUE THREAD

**Issue by tapuleo** [FortAwesome/Font-Awesome#3445]
Please make an Elance icon similar to this: 
![elance](https://cloud.githubusercontent.com/assets/5233065/2998914/872a3212-dd10-11e3-89c1-b80c3ec6cbab.jpg)

Elance has public profiles for contractors. People need to link to those public profiles with an icon, like we do for twitter, facebook, and linked-in.

**Comment by abbynucup** [comment]
+1

Requesting this since you already included some of the common social media icons such as facebook, twiiter and google+. The icons will be beneficial to developers and designers whose working in Elance and it is very important for freelancers like us.

Thanks a lot! Cheers.

**Comment by thatamazingprogrammer** [comment]
+1

**Comment by tapuleo** [comment]
Well, now Elance is going away after the merge with O-Desk. The new entity is called Upwork, with a "Up" logo.
