### ISSUE TITLE
Icon request: icon-craftsman

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#3463]
Hello to everyone!
I need to have an icon like this -> 
![righello-e-matita-croce--ios-7-simbolo-interfaccia_318-35491](https://cloud.githubusercontent.com/assets/7620920/3007724/15e1b798-de9a-11e3-9f02-f3908b9603bb.jpg)
I think that this one is useful when you want to list of jobs
thank you!

**Comment by tagliala** [comment]
Oh this has been implemented in FA 5.1.0

Ref: #9604

https://fontawesome.com/icons/pencil-ruler?style=solid
