### ISSUE TITLE
Icon Request: icon-comix

### ISSUE THREAD

**Issue by Mxater** [FortAwesome/Font-Awesome#3466]
Hello, I wanna a icon for manga or comics for my website, I will use in the menu for show a galery of comics or mangas.

![manga](https://cloud.githubusercontent.com/assets/4630666/3007951/279eeac0-dea7-11e3-97b1-9137244b56d1.png)

**Comment by popisms** [comment]
+1

**Comment by aethior** [comment]
Hi @Mxater,

The porpoused icon was added in v5.7.0.
Check https://fontawesome.com/icons/book-user

Regards.

cc/ @tagliala
