### ISSUE TITLE
Icon Request: icon-worm

### ISSUE THREAD

**Issue by Rebecca50** [FortAwesome/Font-Awesome#3468]
Hello, 

I'd like to request a fa-worm icon, please. Whole lot of book worms coming over to digital so beyond my personal need for a fun page-turning icon/link for a site intended to get people composting it could be useful for the growing community. Here's a google image that illustrates my thinking. But flipped to face right. Of course, I'll be happy with whatever you might come up with.

http://slg.naturalstrategies.com.au/media/news_images/worm_happy_cartoon.jpe

Thanks for listening.

**Comment by rpmeir** [comment]
I also need this icon

**Comment by skylord123** [comment]
I would actually love a worm icon. I just went looking for it and I am surprised it hasn't been added.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/worm?s=solid
