### ISSUE TITLE
icon request: icon-forklift

### ISSUE THREAD

**Issue by ivanlori** [FortAwesome/Font-Awesome#3472]
Hello,
this icon -> 
![13-128](https://cloud.githubusercontent.com/assets/7620920/3012293/0a4d8116-df38-11e3-9f3d-c2f3c238bb28.png)
would be useful to symbolize warehouse, I need it for my website to list buildings.
thank you!

**Comment by raufaamir** [comment]
I also required something like this for warehouse.

**Comment by alinearielo** [comment]
Or some kind of boxes!

**Comment by tagliala** [comment]
Renamed as `icon-forklift`

**Comment by tagliala** [comment]
...which is a duplicate of #692, please +1 that request

**Comment by jbwl** [comment]
+1
