### ISSUE TITLE
graduation-cap/mortar-board icon is not displayed

### ISSUE THREAD

**Issue by adaniello** [FortAwesome/Font-Awesome#3485]
Strange issue: with last version 4.1 i can see all new icons except graduation-cap / mortar-board.
No caching problem. Tested with Chrome, Firefox and Safari on Mac OsX.
I used http://fontawesome.io/assets/font-awesome-4.1.0.zip.
Thanks for help

**Comment by andrevanberlo** [comment]
@adaniello could you tell me your fix? I'm having the same issue on my site. can display all icons except mortar-board / graduation-cap

**Comment by tagliala** [comment]
@andrevanberlo take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by manicode24** [comment]
Hi i am also tried, but not working below code pls share solutions


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>School Project</title>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
	
	<link rel="stylesheet" type="text/css" href="css/style.css">
	
    <link rel="stylesheet" type="text/css" href="css/fontawesome.css">
</head>
<body>
	<div class="banner">
		<header>
			<div class="hat">
				<h1><i class="fa fa-graduation-cap" aria-hidden="true"></i><span class="title-color">versed</span></h1>
			</div>
		</header>
	</div>


<script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>
</body>
</html>

**Comment by tagliala** [comment]
@manicode24 take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
