### ISSUE TITLE
Icon request: Double chevrons

### ISSUE THREAD

**Issue by mahemoff** [FortAwesome/Font-Awesome#349]
Double chevrons in all 4 directions. Especially vertical for slide-up/slide-down controls, but also for expanding horizontally and acting as a "better raquo" for hierarchies. (Since raquo is usually rendered too short.)

**Comment by FezVrasta** [comment]
Any chance to have chevron-double-* icons along with the existing angle-double-* ones?

**Comment by lisivets** [comment]
+1
