### ISSUE TITLE
Icon Request: icon-download-folder

### ISSUE THREAD

**Issue by burito1043** [FortAwesome/Font-Awesome#3490]
We are in need of a 'basket' type of icon that is not shopping related and were hoping to to use Font-Awesome.  This one here from the Noun Project is what we're looking for.  
http://thenounproject.com/term/download-folder/15240/

Please let us know if this, or one similar is possible.

Respectfully,

Steve

**Comment by tomasantonj** [comment]
+1

Even though it is available in Icomoon, we have made the decision to work with FA due to it's awesomeness and all that jazz.

**Comment by sensibleworld** [comment]
We have a few icons that might work for this now.

https://fontawesome.com/icons/download?s=solid
https://fontawesome.com/icons/folder-arrow-down?s=solid
https://fontawesome.com/icons/laptop-arrow-down?s=solid
https://fontawesome.com/icons/inbox-in?s=solid
