### ISSUE TITLE
[Icon request] A cart icon that renders better

### ISSUE THREAD

**Issue by carolineschnapp** [FortAwesome/Font-Awesome#3491]
I know this to be subjective, but I don't like the cart icon used in Font awesome. I would love it to be replaced by another one, or to be offered an alternate option.

I find that the one used now has lines that are too fine, those don't work well for any icon, and the oblique line does not render well in many browsers.

Here are ideas that would work better, because thicker and straighter lines:

![Alt text](https://monosnap.com/image/CS2v6Ne52TeVt8sarP2eP4AukmF6AT.png)

![Alt text](https://monosnap.com/image/ifxaUErKrW2jdb6uQnDTylJvgQfaLb.png)

I would love to get a bag icon too, one with very simple artwork like this:

![Alt text](https://monosnap.com/image/ty4m8SdC8ZxAjtjg3cOOjPKTRTSGPa.png)

**Comment by sensibleworld** [comment]
Closing here, as we've made changes to both the v5 and v6 icon.
