### ISSUE TITLE
Idea: make Font-Awesome available via Google WebFonts

### ISSUE THREAD

**Issue by andreimoment** [FortAwesome/Font-Awesome#35]
http://www.google.com/webfonts have a wide selection but miss a pictogram font. They also highlight Kickstart projects for fonts to be included in their library ($3k on average). 

Including Font-Awesome in Google WebFonts would make it available to many, and possibly result in it becoming a de-facto standard on the web.

**Comment by macmladen** [comment]
The reluctance Google may have could be connected with their own [Material Design Icon](http://google.github.io/material-design-icons/)

Also copyright issue could be a big one considering that not seldom some person pops out claiming his/her share of something that is released to free use therefore forcing many projects to change (and that is an issue with or without GWF). That would mean that FA should check on origin on current glyphs and all future submitted glyphs **not** to contain any copyright protected sign or design that could spell problems.
