### ISSUE TITLE
Icon request: Media players

### ISSUE THREAD

**Issue by confact** [FortAwesome/Font-Awesome#351]
Would love to have some icons for iTunes, Windows Media player and Winamp to use to my social site for music lovers.

**Comment by xnomeda** [comment]
+1

**Comment by tagliala** [comment]
itunes is here: #919 , please +1 that request

I'm sorry but I need to close this request bcause it doesn't meet contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

@xnomeda if you want to request winamp or windows media player please open new individual request (and search before)

closing here
