### ISSUE TITLE
icon request: peace sign

### ISSUE THREAD

**Issue by johnsonsaga** [FortAwesome/Font-Awesome#3515]
Simple circle with peace sign.
![image](https://cloud.githubusercontent.com/assets/7674071/3061306/a13b1f10-e204-11e3-8272-2ecd096a2f2b.png)

**Comment by 12lamat** [comment]
+1

**Comment by ayush** [comment]
Yes. Please.

**Comment by kieferhagin** [comment]
+1

**Comment by nelsonmau** [comment]
+1 yes please :)

**Comment by ionescu77** [comment]
+1

**Comment by Emalton** [comment]
+1

**Comment by dustinmoore** [comment]
+1

**Comment by KerryJones** [comment]
+1

**Comment by kieferhagin** [comment]
+1

**Comment by rowedonalde** [comment]
+1

**Comment by Wasabis** [comment]
+1

**Comment by aethior** [comment]
Hi @johnsonsaga,

This icon was added in v5.3.0.
Check https://fontawesome.com/icons/peace

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here. :)
