### ISSUE TITLE
Icon Request: icon-om

### ISSUE THREAD

**Issue by ernilambar** [FortAwesome/Font-Awesome#3522]
It would be great if this icon is available.
![om-icon](https://cloud.githubusercontent.com/assets/2098823/3064893/69c4a4c4-e25a-11e3-8366-d83eee8b03c0.png)

It is a symbol representing a mantra in Sanskrit. It is used in religious books and othet stuffs. It would be very helpful in developing religious website.

**Comment by Wingo5315** [comment]
+1
Could also be used for homework help/reference/Hindu-specialist sites. Until then, I'm having to use SVGs from Wikipedia, which is REALLY ANNOYING as they come with so... many... bugs.

**Comment by aethior** [comment]
Hi @ernilambar,

This icon was added in v5.3.0.
Check https://fontawesome.com/icons/om

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
@aethior thanks as usual, really appreciate

**Comment by aethior** [comment]
@tagliala you can close here. ;)
