### ISSUE TITLE
Icon Request: icon-flowchart

### ISSUE THREAD

**Issue by edercortes81** [FortAwesome/Font-Awesome#3525]
Use case: editing or viewing of a flow diagram.
![download](https://cloud.githubusercontent.com/assets/5366443/3066808/e213806a-e27a-11e3-847d-c0f6688e7c0b.jpg)

**Comment by dflock** [comment]
Sitemap doesn't really cover the flowchart use case, unfortunately. It's just a tree, no branching or decisions in the graph.

Something like these are what's needed for fa-flowchart:

- https://thenounproject.com/term/flow-chart/38636/
- https://thenounproject.com/term/flow-chart/44681/
- https://thenounproject.com/term/process/193962/

![image](https://user-images.githubusercontent.com/47756/41003310-4bc8fb7c-68cb-11e8-9174-d9b50cf0346d.png)
