### ISSUE TITLE
Icon request: icon-count

### ISSUE THREAD

**Issue by modipeluri** [FortAwesome/Font-Awesome#3528]
Hello and thank you for creating font awesome. It makes my daily life as a web developer just so much more convenient.

I think a count/amount -icon would make a great addition to font awesome.

Possible usecases:
- Filtering (select by count)

![icon-amount](https://cloud.githubusercontent.com/assets/2727074/3068009/232b5736-e289-11e3-8683-2859cdb2bf39.png)

**Comment by Khrysller** [comment]
This, +1

**Comment by pieterjandesmedt** [comment]
Interested it this as well. I'm attaching .png and .psd files.

![counter](https://cloud.githubusercontent.com/assets/9006284/18780227/c7dd0db2-817c-11e6-962a-a2eb6c18f5df.png)
[counter.psd.zip](https://github.com/FortAwesome/Font-Awesome/files/489231/counter.psd.zip)

**Comment by crh225** [comment]
another idea:
![image](https://cloud.githubusercontent.com/assets/19475195/19573772/1f679ea2-96cd-11e6-83d7-6fec34fa13df.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/tally?style=solid
https://fontawesome.com/icons/abacus?style=solid
