### ISSUE TITLE
Icon Request: Resume/CV

### ISSUE THREAD

**Issue by naveenippili** [FortAwesome/Font-Awesome#3533]
Hi,

It would be great if we can have a resume icon. 

Some ideas: 
http://robjepson.files.wordpress.com/2013/04/resume-icon.jpg
http://st.depositphotos.com/1589661/2352/v/450/depositphotos_23527747-CV---Curriculum-vitae-resume-vector-icons-set.jpg

Thanks,
Naveen

**Comment by cyrilschumacher** [comment]
+1

**Comment by muhammedabuali** [comment]
any updates ?

**Comment by tagliala** [comment]
@muhammedabuali this request is not so popular, take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by ThePCDguy** [comment]
+1

 Something like this:

https://cdn0.iconfinder.com/data/icons/thin-files-documents/57/thin-083_file_document_cv_curriculum_vitae_profile_id-128.png

**Comment by jonathanhammond** [comment]
http://www.flaticon.com/free-icon/professional-profile-with-image_31625

**Comment by Peteychuk** [comment]
+1

**Comment by jrgdiz** [comment]
Adding my support for an icon in the shape of what @ThePCDguy or @jonathanhammond suggest.

**Comment by VisheshSood** [comment]
Were we able to add this icon?

**Comment by aaronsky** [comment]
+1, fa-file-text is inadequate for communicating a link to a CV

**Comment by obruchez** [comment]
+1

**Comment by simonhollingshead** [comment]
+1.  I'm a big fan of the icon examples provided in this issue report - a document that looks personal rather than just text-based.

**Comment by baldwmic** [comment]
+1

**Comment by huzhifeng** [comment]
+1. it would be great to have a dedicated icon for resume

**Comment by craibuc** [comment]
+1

**Comment by RobJepson** [comment]
Hello, my name's Rob. I actually designed the first icon that was posted on this thread for a school project! I'd love to help develop something more useful if there's a need.

**Comment by r-ichard** [comment]
+1

**Comment by murtin** [comment]
+1

**Comment by siggioa** [comment]
+1

**Comment by AlexBroadbent** [comment]
+1

**Comment by sammytech** [comment]
+1

**Comment by mayrund** [comment]
+1 Would be great!

**Comment by hzhu** [comment]
+1 looking for a resume icon 👍

**Comment by soberowy** [comment]
+1

**Comment by Efesto** [comment]
+1

**Comment by Xercoy** [comment]
+1

**Comment by dipu-bd** [comment]
+1

**Comment by nmanske** [comment]
+1

**Comment by ivanempire** [comment]
+1

**Comment by adriancast** [comment]
+1

**Comment by aabiddanda** [comment]
+1

**Comment by devgg** [comment]
+1

**Comment by mpvasilis** [comment]
+1

**Comment by 56th** [comment]
+1

**Comment by dvro** [comment]
+1

**Comment by chrisjimenez** [comment]
+1

**Comment by ZacharyJacobCollins** [comment]
+1

**Comment by GianPaoloBuffo** [comment]
+1

**Comment by dongchirua** [comment]
+1

**Comment by MG2R** [comment]
+1

**Comment by ellioman** [comment]
+1

**Comment by cabellicar123** [comment]
+1

**Comment by opensorceror** [comment]
+1

**Comment by dgeorge668** [comment]
+1

**Comment by shaheen-rasheed** [comment]
good

**Comment by arnomoonens** [comment]
+1

**Comment by dmonay** [comment]
+1

**Comment by sharbeldahlan** [comment]
+1

**Comment by dyspop** [comment]
+1

**Comment by TheRabid** [comment]
+1

**Comment by megraf** [comment]
+1

**Comment by ManuelRiveraC** [comment]
+10

**Comment by divayprakash** [comment]
+1

**Comment by catvajiac** [comment]
+1

**Comment by iamdevlinph** [comment]
+1 Will use `fa-file-text` for now

**Comment by mouadelmerchi** [comment]
For those who want an alternative, here is one:

Download the free version of IcoMoon icons pack from [https://icomoon.io/#icons-icomoon](url)

- Include the file "Font/IcoMoon-Free.ttf" in your site

- Use the following css rules in order to use IcoMoon fonts:

`@font-face {
    font-family: 'IcoMoon-Free';
    src: url('Font/IcoMoon-Free.ttf') format('truetype'); /* Change url to where you placed the ttf file */
    font-weight: normal;
    font-style: normal;
}`

`.icon {
    /* use !important to prevent issues with browser extensions that change fonts */
    font-family: 'IcoMoon-Free', sans-serif !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    letter-spacing: 0;
    -webkit-font-feature-settings: "liga";
    -moz-font-feature-settings: "liga=1";
    -moz-font-feature-settings: "liga";
    -o-font-feature-settings: "liga";
    font-feature-settings: "liga";
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}`

- To use "resume" icon, add the following css rule:

`.icon-resume:before {
    content: "\e923";
}`

- Here's a usage example:

`<a href="#" class="btn btn-lg btn-outline" data-toggle="modal">
        <i class="icon icon-resume" aria-hidden="true"></i> Curriculum Vitae
</a>`

**Comment by ddavidtran** [comment]
+1

**Comment by jacsmith21** [comment]
+1

**Comment by trenta3** [comment]
+1

**Comment by litalboa** [comment]
+1

**Comment by lrdegeest** [comment]
+1

**Comment by fomox** [comment]
+1

**Comment by rowansharman** [comment]
![image](https://user-images.githubusercontent.com/23462352/35028634-7ca0c5bc-fb03-11e7-98e2-26ea04e72817.png)
I got something OK-looking by overlaying fa-file-text with fa-user and throwing three white shadows  to form a separation. I modified the code from [#3640](https://github.com/FortAwesome/Font-Awesome/issues/3640):
Add to your fa CSS:
```
.fa-sub {
   position: relative;
   left: -.5em;
   width: .2em;
   vertical-align: -.25em;
   text-shadow: -1px -1px 0px white, -1px 1px 0px white, -1px 0px 0px white; // optional contrast
 }
```
Then display the icon with:
```
<span>
   <i class="fa fa-file-text"></i>
   <i class="fa fa-sub fa-user"></i>
</span>
```
If you add ```fa-lg``` to the ```fa-file-text``` icon you get something more like this:
![image](https://user-images.githubusercontent.com/23462352/35029068-8cae486a-fb05-11e7-8a23-6a72a4b8c134.png)

Of course a real icon would be much better but until then...

**Comment by maxibor** [comment]
+1

**Comment by semperphoenix** [comment]
+1

**Comment by staticninja** [comment]
+1

**Comment by Kathy145** [comment]
+1 looking for a resume icon 👍

**Comment by tmiecz** [comment]
+1

**Comment by MarioEME** [comment]
+1

**Comment by vitormv** [comment]
+1

**Comment by rebz** [comment]
+1

**Comment by alishdipani** [comment]
+1

**Comment by alexisteleco** [comment]
+1

**Comment by whebbworks** [comment]
+1

**Comment by asi14** [comment]
+1

**Comment by Wingo5315** [comment]
+1
You could just have an existing document icon with the letters "CV" somewhere (top left, top right)

**Comment by rmcrowley2000** [comment]
+1

**Comment by sensibleworld** [comment]
This is the version we came up with: https://fontawesome.com/icons/file-user?style=solid. Could also use: https://fontawesome.com/icons/file-certificate?style=solid

**Comment by andreariveros** [comment]
+1

**Comment by FriendlyUser** [comment]
+1

**Comment by VarunAgw** [comment]
+1

**Comment by dannycastonguay** [comment]
+1

**Comment by tagliala** [comment]
Please notice that this icon is available in FA Pro:
- https://fontawesome.com/icons/file-user?style=solid

If you have something different in mind, feel free to start a new request by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by CodeMeKathy** [comment]
Thank you!   Can one hope for a free version on the horizon for those looking for development positions?

**Comment by AlejandraMoralesB** [comment]
Thank!!!✨🙌

**Comment by zhanghang1989** [comment]
+1
