### ISSUE TITLE
Icon Request: icon-chilodesign

### ISSUE THREAD

**Issue by chilodesign** [FortAwesome/Font-Awesome#3546]
![chilo-icon](https://cloud.githubusercontent.com/assets/7704322/3084415/349710c2-e4f6-11e3-9ad1-164e0cbc432e.png)

**Comment by aethior** [comment]
@tagliala 'Chilo Design' was an Ecuadorian web design company. Currently the domain is for sale (http://www.chilodesign.com/) and twitter/facebook accounts without activity (https://www.facebook.com/ChiloDesign.ec/, https://twitter.com/chilodesign_ec).

**Comment by tagliala** [comment]
@aethior thanks

I'm going to close this one
