### ISSUE TITLE
Icon request: fa-bdt (fa-taka - Bangladeshi Currency)

### ISSUE THREAD

**Issue by mayeenulislam** [FortAwesome/Font-Awesome#3552]
The Bangladeshi Currency simbol, in Unicode is known as BENGALI RUPEE SIGN (U+09F3).
Can we request to include that into Font Awesome?

Source: http://www.fileformat.info/info/unicode/char/9f3/index.htm

**Comment by Anupfpi** [comment]
Bangladeshi Taka Symbol font .zip…]()
