### ISSUE TITLE
fa-square and fa-square-o should have the same size

### ISSUE THREAD

**Issue by tuffff** [FortAwesome/Font-Awesome#3566]
I would like to use font-awesome icons as slideshow-image-indicators. 
While that is no problem with fa-circle and fa-circle-o, the filled square is little bit larger than the empty one, which makes switching between the two look untidy even with fa-fw.

fiddle: http://jsfiddle.net/9pDaC/

If there is any reason for the different size (e.g. percieved size), would it maybe be possible to create an smaller filled square as alternative?

I could get pretty close to the same size and position by using font-size: 14 for fa-square-o and fa-square with font-size 13 and top - 1, but it’s not perfect.

**Comment by dregad** [comment]
@sensibleworld it would be nice to have a short explanation as to why this is being closed. Thanks for your consideration.

**Comment by tagliala** [comment]
@dregad 

@sensibleworld is shutting down old requests that have been solved or that do not apply anymore.

This does not apply anymore (FA4 is in EOL) **and** the issue has being fixed in Font Awesome 5.0.0, since `fas fa-square` and `far fa-square` have the same size

Please take a look at the updated fiddle: http://jsfiddle.net/tagliala/1tnvLu9s/1/

Hope it helps

Feel free to keep commenting if you need more information

**Comment by dregad** [comment]
@tagliala Many thanks for the prompt reply. Nice to read that this has been addressed, I'll look into updating my code for FA5 then.

For the record, I have no problem at all with issues being closed (even as "won't fix"), but I was somewhat annoyed by the lack of comment.

Anyway, thanks again.

**Comment by tagliala** [comment]
@dregad you're welcome!

> I have no problem at all with issues being closed (even as "won't fix"), but I was somewhat annoyed by the lack of comment.

Sorry about that and thanks for the heads-up.

Anyway, I'm double checking closed issues, I've forgot to add the 5.0.0 milestone to this. Also, if someone still experience the issue closed I'm available to check and reopen 👍

**Comment by sensibleworld** [comment]
@dregad Apologies for the poor communication! What @tagliala said is correct, but I should have mentioned in a comment prior to closing.
