### ISSUE TITLE
Some glyphs are broken in PowerPoint and MS-Word

### ISSUE THREAD

**Issue by gongdo** [FortAwesome/Font-Awesome#3567]
I installed both FontAwesome-webfont.ttf and FontAwesome.otf on my Windows box, and used in MS-Office. As you can see bellow, It works perfect with Excel but don't with PowerPoint and Word.

![font-awesome 4 1 0](https://cloud.githubusercontent.com/assets/5451328/3103864/235b9422-e65e-11e3-8789-8ebce770d030.JPG)
Is it a known issue? Or, is there anything I'm missing?

**Comment by slt-uxd** [comment]
Apparently this is still an issue. I was using FA (4.4) in Powerpoint Windows and on Mac, after installing both the TTF and OTF version, some glyphs are missing. Real bummer. Also, apparently the TTF version of FA doesn't embed in Powerpoint 2013 on Windows. Double bummer. Going to look for another icon font without these two issues.

**Comment by tagliala** [comment]
Hi, this should not be an issue anymore in FA5

Please check that you have installed fonts under the folder `use_on_desktop`
