### ISSUE TITLE
Icon Request: icon-verified

### ISSUE THREAD

**Issue by lucascolin** [FortAwesome/Font-Awesome#3569]
Hi Font Awesome! 

I have been working on some Twitter display widgets and would love it if you could add the verified icon badge.  You can see an example of it on twitter or in my screen shot attached.  

Thanks a bunch!
Luke

![screen shot 2014-05-28 at 4 19 27 pm](https://cloud.githubusercontent.com/assets/2091887/3111826/2d78c3aa-e6b6-11e3-8de9-f89b87a5bf1d.png)

**Comment by sensibleworld** [comment]
We now have a `badge-check` icon that should work for this: https://fontawesome.com/v6.0/icons/badge-check?s=solid
