### ISSUE TITLE
Icon request: icon-refresh-exclamation

### ISSUE THREAD

**Issue by joshjhall** [FortAwesome/Font-Awesome#357]
Same as the current refresh, but with a dot in the middle to indicate a sync/refresh is necessary.

**Comment by My1** [comment]
maybe not the dot but something else, like an exclamation mark, since a dot in the middle is hardly any indication...

**Comment by sensibleworld** [comment]
<img width="588" alt="Screen Shot 2021-03-30 at 1 29 20 PM" src="https://user-images.githubusercontent.com/529604/113030775-f0076500-915b-11eb-87ca-78f6eddd2cb0.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
