### ISSUE TITLE
Icon Request: icon-workflow

### ISSUE THREAD

**Issue by suseu** [FortAwesome/Font-Awesome#3576]
I am building a system that manages business workflows.
I need an icon to put on buttons opening workflow cases and also workflow definitions.
I haven't got particular idea in my mind besides that it should be a variation on arrows / lines, like arrows pointing to blocks or lines connecting blocks.

**Comment by nadeermalangadan** [comment]
+1

**Comment by hennott** [comment]
I´m also looking for an icon-workflow. But the sitemap is nothing like a workflow. Maybe this is an example? I´m inspired by a statemaschine.

 
![icon-workflow](https://user-images.githubusercontent.com/10630756/35912449-e7b18468-0bfc-11e8-97c7-7300b33eb4a2.png)

**Comment by tagliala** [comment]
@hennott thanks for your example

Please open a new request but please use a different title: it should indicate what the icon exactly represent. Workflow is quite abstract. Is that is a state machine, please use state machine.

Closing here
