### ISSUE TITLE
Improve Icon fire

### ISSUE THREAD

**Issue by bigfoot90** [FortAwesome/Font-Awesome#3577]
I think the current icon `fa-fire` should be renamed to `fa-flame`.
And make an icon like `fire` from glyficons for `fa-fire` 
![image](https://cloud.githubusercontent.com/assets/4598274/3118476/cdc42260-e73c-11e3-9c48-acb412d901d8.png)

**Comment by benoitr** [comment]
+1

**Comment by jennvee** [comment]
+1

**Comment by frensuren** [comment]
+1

**Comment by OpenMenu** [comment]
+1

**Comment by TPXP** [comment]
+1, the third one would be so much useful to highlight popular content!

**Comment by thehavknots** [comment]
+1

**Comment by Casper-O** [comment]
+1

**Comment by shaynasymons** [comment]
+1

**Comment by M440** [comment]
+1 for fire

**Comment by lvv83** [comment]
+1 here

**Comment by esatk** [comment]
+1 for improved fire icon

**Comment by TheChen5** [comment]
+1

**Comment by albert-tse** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by MrZach** [comment]
+100

**Comment by thotzl** [comment]
:+1:

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/11779186/ccb6b598-a259-11e5-881b-4f0e4ade16d5.png)

New trending icon on YouTube

**Comment by johannbotha** [comment]
+1

**Comment by galichvitaliy** [comment]
+100500

**Comment by jonnyshocko** [comment]
+1

**Comment by jonnyshocko** [comment]
@tagliala Possible update soon? :smile:

**Comment by jonnyshocko** [comment]
Right now we have to use the raindrop which is a little ironic

**Comment by drivevelocity** [comment]
+1

**Comment by refftronics** [comment]
+1

**Comment by mattrick16** [comment]
+1

**Comment by Mati365** [comment]
+1

**Comment by catherinek** [comment]
+1

**Comment by My1** [comment]
+1

**Comment by moselaymd** [comment]
+1

you can also hit the :+1: button under the issue [up there](https://github.com/FortAwesome/Font-Awesome/issues/3577#issue-34558640)

**Comment by dpfem** [comment]
+1

**Comment by chiulam** [comment]
+1

**Comment by Servuc** [comment]
+1

**Comment by captainswain** [comment]
+1

**Comment by khashabawy** [comment]
+11111

**Comment by krienow** [comment]
+1

**Comment by frensuren** [comment]
+

**Comment by gursahibexp** [comment]
+1

**Comment by Arjunpxl** [comment]
+1

**Comment by Arjunpxl** [comment]
I love the flame which was used in the free code camp icon (fa-free-code-camp).

Here's the png and svg if you wanna use 👍 

![flame](https://cloud.githubusercontent.com/assets/17943377/22960711/01ab6a88-f366-11e6-9d77-6ad4bc718def.png)
[Flame.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/776052/Flame.svg.zip)

**Comment by secelite** [comment]
+1

**Comment by enriquesoto** [comment]
+1

**Comment by nenofite** [comment]
+1 for third option

**Comment by tagliala** [comment]
Hi, this should be solved in FA5

![image](https://user-images.githubusercontent.com/556268/32232747-056bbe0c-be59-11e7-8c3f-c9cafac842e1.png)

Maybe there is room for improvement for the FA5 icon too, but let's postpone this 👍
