### ISSUE TITLE
Icon Request: icon-window (computing)

### ISSUE THREAD

**Issue by dbsima** [FortAwesome/Font-Awesome#3585]
Something like https://www.iconfinder.com/icons/185037/browser_streamline_window_icon#size=128

Thank you,
Dragos.

**Comment by jtphelan** [comment]
+1

**Comment by elliot100** [comment]
+1

**Comment by hex0gen** [comment]
+1

here an another example http://iconshow.me/browser.

**Comment by freeatnet** [comment]
+1

**Comment by jarrodbell** [comment]
+1

**Comment by jakul** [comment]
+1

**Comment by exetico** [comment]
+1

**Comment by tuzzmaniandevil** [comment]
:+1:

**Comment by juancalero** [comment]
+1

**Comment by memsenpai** [comment]
+1

**Comment by tagliala** [comment]
Hi everyone!

Thanks for being part of the Font Awesome Community.

This icon is available in FA Pro: https://fontawesome.com/icons/browser?style=solid

Closing here
