### ISSUE TITLE
Icon request: icon-equals

### ISSUE THREAD

**Issue by mcuznz** [FortAwesome/Font-Awesome#3588]
While I realize that an Equals sign already exists in the Unicode character set, having one in FontAwesome that stylistically matches the plus, minus and times icons would be very beneficial.

Use cases: anywhere the icon-plus, icon-minus, and icon-times icons are being used in their mathematical representations (calculator buttons or number-value-change forms, for example).

**Comment by nbunney** [comment]
+1

**Comment by nitmir** [comment]
+1

**Comment by RobertoJBM** [comment]
+1

**Comment by tagliala** [comment]
this is a duplicate

:lock:
