### ISSUE TITLE
Icon Request: icon-kiss

### ISSUE THREAD

**Issue by Christian-Schiffer** [FortAwesome/Font-Awesome#3592]
I'd like a icon shaped as kissing lips for my datingsite.

**Comment by neiluJ** [comment]
+1

**Comment by stevschmid** [comment]
+1

**Comment by GwenLoguir** [comment]
+inf (for all women)

**Comment by echobobby** [comment]
+1

**Comment by davemackintosh** [comment]
+1

**Comment by lyhil** [comment]
+1

**Comment by r0dSiMpLy** [comment]
+1

**Comment by alex21** [comment]
+1

**Comment by j2studio** [comment]
+1

**Comment by gestudio** [comment]
+1

**Comment by Stormcloud** [comment]
+1

**Comment by Scobee** [comment]
+1

**Comment by Scobee** [comment]
![adobestock_74799090](https://cloud.githubusercontent.com/assets/5129107/15178067/2ea8fa30-177c-11e6-9eb1-67dd3123b937.png)

**Comment by whoacowboy** [comment]
+1

**Comment by sitchi** [comment]
+1

**Comment by Christian-Schiffer** [comment]
Scooby, I like most of your lips :) But if only one is implemented I would prefer one that is gender neutral. Best of course would be fa-lips-female and fa-lips-male.

**Comment by geshub** [comment]
Would love to see a kiss icon too !

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/lips?style=solid
https://fontawesome.com/icons/kiss?style=solid
https://fontawesome.com/icons/kiss-wink-heart?style=solid
https://fontawesome.com/icons/kiss-beam?style=solid
