### ISSUE TITLE
Icon Request: fa-users-cog

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#3607]
Similar to user-cog (https://github.com/FortAwesome/Font-Awesome/issues/3606). The 'fa-users' + 'fa-cog'.

It should describe user-group settings.

**Comment by weibangtuo** [comment]
+1

and  'fa-users' + 'fa-plus'
It should describe adding user-group.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/users-cog?style=solid

**Comment by Lythimus** [comment]
It's probably too late to mention this, but a cog is a tooth on a gear. So this should probably be named users-cogs, users-gear, or users-cogwheel. This is a common misusage though, so you should be in the clear. I imagine the dictionary definition will be updated in the near future to subsume the colloquialism.

**Comment by sensibleworld** [comment]
@Lythimus Gah! Thanks for the heads-up. We'll look into it.

**Comment by Vasimovic** [comment]
+1
