### ISSUE TITLE
Icon request: fa-calendar-day, fa-calendar-week, fa-calendar-month

### ISSUE THREAD

**Issue by Anubiso** [FortAwesome/Font-Awesome#3609]
Different Calendar-Modes would be great!
Like a symbol for a day-mode, a symbol for week-mode and a symbol for month-mode (current calender icon)

Some illustrations:
![calendarmodes](https://cloud.githubusercontent.com/assets/7769367/3149641/3bc9ec62-ea6d-11e3-92c8-a2363e18210e.png)

This is how outlooks handles it:
![outlookcalmodes](https://cloud.githubusercontent.com/assets/7769367/3149645/43946de6-ea6d-11e3-8f04-32dbbb029e24.png)

Another, more outlookish-approach:
![fontawesomeoutlookish](https://cloud.githubusercontent.com/assets/7769367/3149649/4f35d7fc-ea6d-11e3-851e-a3f73deac730.png)

**Comment by direvus** [comment]
+1

**Comment by triggerdesign** [comment]
+1

**Comment by runar** [comment]
+1

**Comment by dfabreguette-ap** [comment]
+1

**Comment by FuturLane** [comment]
+1

for "more outlookish-approach".
It will be very useful.

These links:
* **icon request: fa-calendar-week; fa-calendar-day; fa-calendar-month** #4117
* **icons for html5 input types** #4140
* **Icon Request: fa-today or fa-calendar-today** #4169

not solve this problem.

Another version of the **fa-calendar-month** look like as in outlook differed to **fa-calendar**:

![calendar-month](https://cloud.githubusercontent.com/assets/11652568/6842179/cfe118ae-d3a5-11e4-8b54-211979770673.png)

**Comment by GwenLoguir** [comment]
+1!

**Comment by extravagangsta** [comment]
+1 We all need these icons! Please add. Can't believe <i class="fa fa-ship"></i> from 4.3 release is more wanted than calendar icons.

**Comment by tagliala** [comment]
@extravagangsta you should believe: #1323 :)

**Comment by auge8472** [comment]
![](https://cloud.githubusercontent.com/assets/11652568/6842179/cfe118ae-d3a5-11e4-8b54-211979770673.png)
An additional alias: `fa-monstershowingitslasttwolonesometeeth`. A **perfect** load speed optimisation! ;-)

One question, effective *for all* the shown examples. How will they look with the base font size of 16px? Fuzzy? Itsy-bitsy? Most of them has IMHO to much details.

**Comment by Jivings** [comment]
+1

**Comment by sunburntkamel** [comment]
+1

**Comment by chrispadfield** [comment]
+1

**Comment by johanwilfer** [comment]
+1

**Comment by peter-at-angeltrax** [comment]
+1

**Comment by phlegx** [comment]
+1

**Comment by lyhil** [comment]
+1 it would be great help!

**Comment by gitawego** [comment]
+1

**Comment by Anubiso** [comment]
@auge8472 
Here are some examples with different sizes:

calendar-modes:
![calendar-modes](https://cloud.githubusercontent.com/assets/7769367/9085357/4eae6fea-3b7c-11e5-8061-a01ed5753d59.png)

calendar-modes-o
![calendar-modes-o](https://cloud.githubusercontent.com/assets/7769367/9085358/4ecbcb1c-3b7c-11e5-91cb-b062bccee3b5.png)

**Comment by auge8472** [comment]
@Anubiso

> Here are some examples with different sizes:

Thank you for the show cases. The smallest icons have a smaller font size than 16px? They look **very** itsy-bitsy.

**Comment by Anubiso** [comment]
Smallest one have a font size of 14px. Took a screenshot of http://fortawesome.github.io/Font-Awesome/icon/calendar/ and edited it.

**Comment by auge8472** [comment]
@Anubiso Ok, I read it again. The basic font size is `14px` and not `16px`. At least the so called calendar-modes (without `-o`) are IMHO to fuzzy.

**Comment by gvespucci** [comment]
+1

**Comment by weednation12** [comment]
Need them right now +1

**Comment by jonnsn** [comment]
+1

**Comment by ronifabio** [comment]
+1

**Comment by NonoCC** [comment]
+1

**Comment by dotnetwise** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by chrispadfield** [comment]
+1

**Comment by jarrodbell** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by mipapo** [comment]
+1

**Comment by luber** [comment]
+1

**Comment by Struan1303** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by jbnv** [comment]
+1, and please see my related request #8880.

**Comment by sanek4life** [comment]
+1

**Comment by michalbe** [comment]
+1

**Comment by wojtekw92** [comment]
+1

**Comment by Wasiak** [comment]
+1

**Comment by mpowroznik** [comment]
+1

**Comment by karol-f** [comment]
+1

**Comment by end3r** [comment]
+1

**Comment by mattgreen110** [comment]
+1

**Comment by tophsic** [comment]
+1

**Comment by gquipster** [comment]
+1

**Comment by pramsden** [comment]
An alternative could be a calendar icon containing the number of days. i.e. [1], [7], [31]

I assume that 31 would be understood to mean a complete month even for months having fewer days.

**Comment by mdbesoain** [comment]
+1

**Comment by Ricky-G** [comment]
+1

**Comment by titansoftime** [comment]
+1,000,000,000

**Comment by everything-it** [comment]
why the hell does it say I'm not receiving notifications from this thread, but yet they FILL UP my inbox every day??????

**Comment by trondhuso** [comment]
As I also suggest in my post, was that you could also add numbers in the calendar as well, like 26 for the day of the month. Could be handy as well... And also the name of the month, but then you might end up in language versions...

**Comment by kwagdy** [comment]
Wow! this is old! I suggest the month icon would be more indicative of a month, maybe something like this?
![image](https://user-images.githubusercontent.com/15840617/32354774-f58743f8-c033-11e7-95ca-bea985940da2.png)

**Comment by kwagdy** [comment]
I just found this font awesome blog article on how to do that 💯  👍  :)
http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by TheNaderio** [comment]
+1
That would be a great relief

**Comment by venkat0033** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by jrmessias** [comment]
> Different Calendar-Modes would be great!
> Like a symbol for a day-mode, a symbol for week-mode and a symbol for month-mode (current calender icon)
> 
> Some illustrations:
> ![calendarmodes](https://cloud.githubusercontent.com/assets/7769367/3149641/3bc9ec62-ea6d-11e3-92c8-a2363e18210e.png)
> 
> This is how outlooks handles it:
> ![outlookcalmodes](https://cloud.githubusercontent.com/assets/7769367/3149645/43946de6-ea6d-11e3-8f04-32dbbb029e24.png)
> 
> Another, more outlookish-approach:
> ![fontawesomeoutlookish](https://cloud.githubusercontent.com/assets/7769367/3149649/4f35d7fc-ea6d-11e3-851e-a3f73deac730.png)

+1

**Comment by jrmessias** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/calendar-alt?style=solid
https://fontawesome.com/icons/calendar-day?style=solid
https://fontawesome.com/icons/calendar-week?style=solid

**Comment by Crissov** [comment]
Related Unicode emojis #222:

- [📆](https://emojipedia.org/tear-off-calendar/) U+1F4C6 TEAR-OFF CALENDAR
- [📅](https://emojipedia.org/calendar/) U+1F4C5 CALENDAR
- [🗓](https://emojipedia.org/spiral-calendar-pad/) U+1F5D3 SPIRAL CALENDAR PAD
