### ISSUE TITLE
Icon Request: yammer

### ISSUE THREAD

**Issue by urms** [FortAwesome/Font-Awesome#3611]
Hi,

I would like to ask if you could create a Yammer-icon, if time permits. 

The 'Y' with three 'shouting' indicators to the right.

https://www.yammer.com

Thanks for fa anyway. It's so wonderful to use :)

Cheers,
Ulf

**Comment by hobe** [comment]
duplicate of https://github.com/FortAwesome/Font-Awesome/issues/2707

**Comment by tagliala** [comment]
@hobe thanks
