### ISSUE TITLE
Icon Request: icon-wine-glass-full

### ISSUE THREAD

**Issue by singlewhitepixel** [FortAwesome/Font-Awesome#3614]
I recently required a wine glass icon, two versions one full and one empty. I used an image but you may want to consider it and other glass shapes as I often need alcoholic beverage related icons for bars, liquor retailers and restaurant related websites and I'm sure other web designers would too.

**Comment by G-Driver** [comment]
+1 for wine

**Comment by jaoustin** [comment]
+1

**Comment by phillq** [comment]
+1

**Comment by G-Driver** [comment]
See also corkscrew request https://github.com/FortAwesome/Font-Awesome/issues/5835

**Comment by kewh** [comment]
+1

**Comment by awhare** [comment]
+1

**Comment by jkfoto** [comment]
+1

**Comment by bigsea** [comment]
+1

**Comment by willythekid1979** [comment]
+1

**Comment by playcodestudio** [comment]
+1

**Comment by Crissov** [comment]
🍷 [U+1F377](http://emojipedia.org/wine-glass/) Unicode emoji #222

**Comment by clabnet** [comment]
+1

**Comment by vshvedov** [comment]
+1

**Comment by tzeller** [comment]
i have created this icon - no copy or so - which can be straight used. i need as well some more for the food industry which i will attach
[fa-wine.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364626/fa-wine.pdf)

**Comment by tzeller** [comment]
wine glass 14 px and 32px
![fa-wine_14px](https://user-images.githubusercontent.com/859700/31308528-7afbf32e-ab78-11e7-8bb1-9fc7b3447585.png)
![fa-wine_32px](https://user-images.githubusercontent.com/859700/31308531-7d9d6ba8-ab78-11e7-8825-735fc156fbe9.png)

**Comment by carterdesign** [comment]
+1

**Comment by Monster695** [comment]
+1

**Comment by sensibleworld** [comment]
We have a few options for this (with the inclusion of Font Awesome Pro):

https://fontawesome.com/icons/wine-glass?style=solid
https://fontawesome.com/icons/wine-glass-alt?style=solid
https://fontawesome.com/icons/wine-glass?style=regular
