### ISSUE TITLE
Octagonal Warning Icon 

### ISSUE THREAD

**Issue by JNJefferyDesign** [FortAwesome/Font-Awesome#3620]
An octagonal version of the current triangle shaped warning icon.  Like a stop sign with an exclamation point inside it.

**Comment by grapho** [comment]
+1 for this, actually just the octagon itself would be nice.

**Comment by jklingen** [comment]
Seems to be a duplicate of #2277

**Comment by tagliala** [comment]
@jklingen thanks!

closing here
