### ISSUE TITLE
Icon Request: Klout

### ISSUE THREAD

**Issue by visumate** [FortAwesome/Font-Awesome#3623]
A Klout icon would be nice!

http://klout.com/

**Comment by acki** [comment]
+1

**Comment by MattFryer** [comment]
+1

**Comment by jeremyhaile** [comment]
:+1:

**Comment by joaopmagalhaes** [comment]
![image](https://cloud.githubusercontent.com/assets/8606173/7373882/fe28073c-edc6-11e4-906b-8ad053e3a9fb.png)

**Comment by sodevious** [comment]
:+1:

**Comment by calebdel** [comment]
+1

**Comment by GGFM** [comment]
+1

**Comment by adelriosantiago** [comment]
+1 YES! We want a Klout icon!

**Comment by markpjohnson** [comment]
+1

**Comment by vbanuelos** [comment]
+1

**Comment by gbuisson** [comment]
+1

**Comment by MiguelMike** [comment]
-1

**Comment by hashwin** [comment]
+1

**Comment by plinsky** [comment]
👍

**Comment by nivhanin** [comment]
+1

**Comment by MiguelMike** [comment]
Klout has been acquired by [Lithium](https://www.lithium.com/products/klout) and is no longer developed.

> Effective, May 25, 2018, Lithium has sunset the Klout service. 
The Klout acquisition provided Lithium with valuable artificial intelligence (AI) and machine learning capabilities, but Klout as a standalone service is not aligned with our long-term business strategy. We appreciate the loyal Klouters out there who stuck with us all these years – keep influencing! For our enterprise customers, please know that Lithium is committed to providing you with innovative technology and services to differentiate your customers’ experience, and we’re excited to share our new capabilities with you!

It doesn't seem to make much sense to still request Klout icon being added to Font Awesome.

**Comment by aethior** [comment]
@tagliala check here please.
