### ISSUE TITLE
Icon Request: icon-heading 1 and 2

### ISSUE THREAD

**Issue by galsanov** [FortAwesome/Font-Awesome#3625]
I love your icons! But our editor needed heading icons 1 and 2, I had to add them yourself through Fontella.com, it did not work out very nicely. Though you have already added an icon heading, it's cool. Really want to see a division title and subtitle for your icons set. Thanks!

**Comment by Alsciende** [comment]
Seconding the need for different header icons, H1, H2, H3, etc.

**Comment by sensibleworld** [comment]
Following up on a few old issues, and wanted to note that version 5 has H1, H2, and H3 icons: https://fontawesome.com/icons?d=gallery&q=heading
