### ISSUE TITLE
Icon Request: icon-game-card, icon-game-cards

### ISSUE THREAD

**Issue by axessweb** [FortAwesome/Font-Awesome#3626]
Hi,

it is possible to add an icon card games?

One card and three cards ? 

And colors of cards : spades, hearts, diamonds, clubs

Thx

**Comment by Ash-Crow** [comment]
+1

**Comment by DragonGun** [comment]
+1

**Comment by DerMudder** [comment]
+1

**Comment by sensibleworld** [comment]
We have a few options for these now: https://fontawesome.com/icons/cards-blank?s=solid
