### ISSUE TITLE
Android 4.0 : no font displayed with local files

### ISSUE THREAD

**Issue by cobaltians** [FortAwesome/Font-Awesome#3632]
I'm having a weird bug on Android 4.0.x devices using font-awesome embedded in a Cordova WebView.

* When using CDN link, font is displayed.
* When using latest release zip files font is not displayed.
* No trouble with Android 4.1, 4.2, 4.3 or 4.4 with local files. iOs works great too.

Any idea ?

Here is my sample code :

I just downloaded the latest release files, put them into a css folder and renammed it "font-awesome-4.1.0" to avoid uppercases.

    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
        
        <link rel="stylesheet" type="text/css" href="css/font-awesome-4.1.0/css/font-awesome.min.css" >
    </head>
    <body>
        <h1>this should work, right ?</h1>
        <p><i class="fa fa-camera-retro"></i> fa-camera-retro</p>
    </body>
    </html>

commented line works great. local files don't. I need local files to allow my app to have icons offline.

**Comment by jonmaim** [comment]
@cobaltians I had a similar problem with font-awesome 4.2 in a cordova webview for windows phone 8. The problem only occurs when the FA files are loaded locally. In my case the solution was to remove all occurrences of `?v=4.2.0` from the `@font-face` property in the `font-awesome.css` file. 

Maybe the problem you have on Android 4.0 is simlilar to this one? Let me know.

**Comment by tagliala** [comment]
let us know

**Comment by cobaltians** [comment]
Hi,
It works for Android 4.0.4 with local files too !! thanks a lot @jonmaim !

@tagliala : Any risk of removing these ?v=4.2.0 from the stylesheet ? Do you known the purpose of it?

**Comment by tagliala** [comment]
@cobaltians cache stuff from the old days, but now they are more harming than useful. Take a look at #3286 

I should advise Dave to consider it for 5.0.0

PS: could you please edit our  troubleshooting wiki and point to this thread? https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by jonmaim** [comment]
Just added a section `Fonts not showing up in Phonegap application (Android and Windows Phone)` at the end of the wiki page https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by tagliala** [comment]
thanks!

**Comment by tagliala** [comment]
Maybe we need an index

**Comment by azachar** [comment]
Hello All, 

I have a similar issue, removing anything behind ? did not work. The path to the font is correct.
I am using Samsung Galaxy J5 with Android 5.1.1, any idea why it doens't work?

Thank you!

**Comment by tagliala** [comment]
@azachar https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#fonts-not-showing-up-in-phonegap-application-android-and-windows-phone

**Comment by azachar** [comment]
Thanks @tagliala, I tried that but it doesn't work neither.
