### ISSUE TITLE
Icon request: icon-research-gate

### ISSUE THREAD

**Issue by egarpor** [FortAwesome/Font-Awesome#3634]
I think it will be very useful for people working on the academia to have a icon for the Research Gate scientific network, so you can link to your publications on that site.

Here are two images based on the favicon:
http://www.researchgate.net/favicon.ico (lower quality)
http://www.txhughes.com/images/button-researchgate.png (better quality) 

As suggested by @juliohm:
# If you like this issue, please press the :+1: button. Do not comment with +1 to save other's mailbox from noise.

**Comment by darcyabjones** [comment]
+1 Yes Please

**Comment by dardin88** [comment]
+1

**Comment by bretthman** [comment]
+1

**Comment by isomerase** [comment]
+1

**Comment by isomerase** [comment]
+1

**Comment by clement-moulin-frier** [comment]
+1

**Comment by StZiza** [comment]
+1

**Comment by SIBeckers** [comment]
+1

**Comment by mraveri** [comment]
+1

**Comment by hayzenbairg** [comment]
+1

**Comment by vdaniuk** [comment]
+1

**Comment by robibi78** [comment]
+1 thks

**Comment by clement-moulin-frier** [comment]
A solution here: https://github.com/jpswalsh/academicons

**Comment by RemiMattheyDoret** [comment]
+1

**Comment by FerreroJeremy** [comment]
+1

**Comment by edcasey** [comment]
+1

**Comment by uhlitz** [comment]
+1

**Comment by pablocobelli** [comment]
+1

**Comment by cmarinos** [comment]
+1

**Comment by BramVanroy** [comment]
+1

**Comment by PCQ** [comment]
+1

**Comment by teamrat** [comment]
+1

**Comment by chunyaoyang** [comment]
+1

**Comment by ducsatthu** [comment]
+1

**Comment by JacobD10** [comment]
+1

**Comment by cchng** [comment]
+1

**Comment by FerreroJeremy** [comment]
@BramVanroy Exactly !
why not implement academicons (https://github.com/jpswalsh/academicons) in FA ?

**Comment by bcipolli** [comment]
:+1:

**Comment by hueyke** [comment]
+1

**Comment by ashiklom** [comment]
+1

**Comment by mvictoras** [comment]
+1

**Comment by kellertuer** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by stefanlorenz85** [comment]
+1

**Comment by benjaminjillich** [comment]
+1

**Comment by TKosch** [comment]
+1

**Comment by nomnom** [comment]
+1

**Comment by sebastianhilsbos** [comment]
+1

**Comment by swaldman3** [comment]
+1

**Comment by pkaroly** [comment]
+1

**Comment by agos** [comment]
:+1:

**Comment by stsio** [comment]
+1

**Comment by albertobeta** [comment]
+1

**Comment by Ellyster** [comment]
+1

**Comment by dmykr** [comment]
+1

**Comment by nathanmusoke** [comment]
Those following this thread may be interested to know that Font Awesome is currently doing a survey about future features, etc.
Link: http://fontawesome.io/survey/?utm_source=font_awesome_homepage&utm_medium=display&utm_content=ad_survey&utm_campaign=promo_4.5_update

**Comment by aosavi** [comment]
+1

**Comment by dbmagers** [comment]
+1

**Comment by ericbardou** [comment]
+1

**Comment by marcosci** [comment]
+1

**Comment by palandh** [comment]
+1 

maybe helpful: https://www.researchgate.net/aboutus.AboutUsPress.downloadFile.html?name=rg_logos.zip

**Comment by jennygrist** [comment]
+1

**Comment by jennygrist** [comment]
ooo https://jpswalsh.github.io/academicons/

**Comment by alishakiba** [comment]
+1

**Comment by jennygrist** [comment]
hi there, is this any help? http://gristock.net/neurotech/2016/06/17/social-icons-for-academics/

**Comment by dennisbauer** [comment]
+1 ResearchGate would improve FontAwesome a lot for usage in academia/research-related applications

**Comment by cyrf0006** [comment]
+1

**Comment by heyfaraday** [comment]
+1

**Comment by ezwebcraft** [comment]
+1

**Comment by CarloNicolini** [comment]
+1

**Comment by benlindsay** [comment]
+1

**Comment by mack6121** [comment]
+1

**Comment by rredan** [comment]
+1

**Comment by pascalschulthess** [comment]
+1

**Comment by 56th** [comment]
+1

**Comment by jasonjb82** [comment]
+1

**Comment by xurxodiz** [comment]
+1

**Comment by thecenteno** [comment]
+1

**Comment by PyrApple** [comment]
+1

**Comment by youngmook** [comment]
+1

**Comment by LechMadeyski** [comment]
+1

**Comment by forethoughtde** [comment]
+1

**Comment by cpraveen** [comment]
+1

**Comment by cako** [comment]
+1

**Comment by lcarnevale** [comment]
+1

**Comment by JosephRyanPeterson** [comment]
+1

**Comment by diegourban** [comment]
+1

**Comment by byrdnick** [comment]
👍 +1

**Comment by juliohm** [comment]
I sent an email to ResearchGate support, they said someone from their design team will take care of it.

**Comment by normcyr** [comment]
+1

**Comment by oyonboyon** [comment]
Hi... Please add this icon.... Right now I am using Academicons (https://jpswalsh.github.io/academicons/) to add Researchgate and Google scholar icons to my website... But I really wish FA provided them so that I would have more control over how they look.... Thanks for considering our requests... :)

**Comment by carldelfin** [comment]
+1

**Comment by stur86** [comment]
+1

**Comment by juliohm** [comment]
Please use the "like" button instead of commenting with "+1".

**Comment by Fleece3Design** [comment]
+1

**Comment by paytongoodrich** [comment]
+1

**Comment by colourinfusion** [comment]
Me too!

**Comment by carlosjoserg** [comment]
+1000

**Comment by zyrikby** [comment]
+1

**Comment by juliohm** [comment]
@egarpor given the popularity of this issue, could you please edit your initial text and add a **bold** paragraph at the top asking for people to press the :+1: button instead of commenting with +1?

You can highlight it with markdown syntax:

```markdown
## If you like this issue, please press the :+1: button. Do not comment with +1 to save other's mailbox from noise.
```

Result:

## If you like this issue, please press the :+1: button. Save other's mailbox from noise, do not comment with +1.

**Comment by qubotong** [comment]
+1

**Comment by LifeWorks** [comment]
+1

**Comment by sutscong** [comment]
+1

**Comment by dhruvdcoder** [comment]
+1

**Comment by talbs** [comment]
https://fontawesome.com/icons/researchgate

**Comment by klebermagno** [comment]
+1

**Comment by sahraoui17** [comment]
+1

**Comment by tagliala** [comment]
@sahraoui17 https://fontawesome.com/icons/researchgate

**Comment by stephanmg** [comment]
Hey, how can I use this icon? 

Do I need to use the following: 
`
https://maxcdn.bootstrapcdn.com/font-awesome/5.0.11/css/font-awesome.min.css
`
?

**Comment by tagliala** [comment]
@stephanmg nope, maxcdn does not host FA 5

Here you can find the suggested ways of using font awesome https://fontawesome.com/start

If you want to use a third party cdn, please check https://www.jsdelivr.com/package/npm/@fortawesome/fontawesome-free

Please notice that we do not provide support for third parties

**Comment by stephanmg** [comment]
Thank you @tagliala for answering. I am sorry to post my question here but I couldn't find a better place to use.

**Comment by tagliala** [comment]
No problem for the question, you're welcome. It is just a clarification about third-party CDNs
