### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by simondbevan** [FortAwesome/Font-Awesome#3635]
It would be great if you could make this SVG accessible as an icon.

It's an 8 sunburst and it is to be our new logo

I would really appreciate it

Cheers

![asterix](https://cloud.githubusercontent.com/assets/7807422/3190390/fe8c1a6a-eccd-11e3-9cc8-be553ee1f19e.png)

**Comment by tagliala** [comment]
No feedback, closing here
