### ISSUE TITLE
Icon Request: icon-fix

### ISSUE THREAD

**Issue by javi1065** [FortAwesome/Font-Awesome#3638]
I plan on using this icon for stating a bug fix or a improvement.
Thanks in advance

![fix](https://cloud.githubusercontent.com/assets/6719419/3192837/d9335068-ecea-11e3-8602-1b9dd3f09790.png)

**Comment by aethior** [comment]
@tagliala Duplicate of #736. The attached image is a png with a white image (impossible to see correctly).

![image](https://cloud.githubusercontent.com/assets/1769227/15836286/5f5b4db4-2c34-11e6-8b6a-264a456d44bb.png)

**Comment by tagliala** [comment]
Ah, got it

Closing here
