### ISSUE TITLE
Icon Request: fa-rectangle & fa-rectangle-o

### ISSUE THREAD

**Issue by gandalfx** [FortAwesome/Font-Awesome#3639]
We already have `fa-square` and `fa-square-o` but I miss rectangles, mostly as a frame/background. The frame of `fa-picture-o` should do just fine, plus a filled version.

Appart from using them as a background/frame you can also potentially use them as parts of more complex composite icons.
For example I have a scenario in mind where I want to symbolize various multi-screen setups. While I could use the `fa-desktop` or `fa-laptop` for horizontal layouts, they will look very weird when rotated to symbolize portrait monitors.
While this is obviously a very specific usage I am sure that there are tons and tons of other uses that creative people will come up with.

Another point of view is to say that a single rectangle would be a logical continuation of `fa-th` » `fa-th-large`.

I appologize if this has been suggested before, there are a _lot_ of issues and afaik no search function for them.
In any case great work so far, really appreciate it. Cheers!

**Comment by hilarudeens** [comment]
+1

**Comment by tagliala** [comment]
A wide range of rectangles are available in FA5 Pro:
- https://fontawesome.com/icons/rectangle-wide
- https://fontawesome.com/icons/rectangle-portrait
- https://fontawesome.com/icons/rectangle-landscape

**Comment by seolgongchan** [comment]
Hello, why is fa-rectangle a PRO icon?

**Comment by tagliala** [comment]
> Hello, why is fa-rectangle a PRO icon?

Hi,

This may answer this question: https://fontawesome.com/support#why-are-some-highly-requested-icons-not-available-in-font-awesome-free
