### ISSUE TITLE
Icon Request: oil-rig

### ISSUE THREAD

**Issue by rstokke** [FortAwesome/Font-Awesome#3644]
Dear Font Awesome. 

would it be possible to add a oil-rig icon (like the one on the second attachment)
at the moment I am using the global for an icon on our homepage(like the screenshot), but it do not make much sens. We are a start up company selling clean water unit to purify water.
we would like to keep this consistent in our brand. 
If it would be possible to get the icon looking like this? 

I truly appreciate all your work, and hope you hear from you soon!

![oilicon](https://cloud.githubusercontent.com/assets/7817524/3203219/4a4d1e4c-ed99-11e3-957e-db30e4297844.png)

![screen shot 2014-06-06 at 6 36 50 pm](https://cloud.githubusercontent.com/assets/7817524/3203173/ca331400-ed98-11e3-8ff4-14fe7675a11e.png)
![oilwater2](https://cloud.githubusercontent.com/assets/7817524/3203178/d7a84600-ed98-11e3-8dc9-05ee5b243355.png)

**Comment by Sjark** [comment]
I would also find it useful.

**Comment by olefredrik** [comment]
+1

**Comment by AsemRadhwi** [comment]
+1

**Comment by Browne** [comment]
+1

**Comment by ahops** [comment]
+1

**Comment by bdegraaf** [comment]
+1

**Comment by PaulGiletich** [comment]
+1

**Comment by wiranoid** [comment]
+1

**Comment by StavroMueller** [comment]
+1, though I'd like to be probably a bit too pedantic and say that's a derrick, not an oil rig - an oil rig is the giant offshore platform :) (Which would be a cool icon as well!)

**Comment by burger1992** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by cseymour** [comment]
+1

**Comment by JaiDoubleU** [comment]
+1

**Comment by JaiDoubleU** [comment]
+1

**Comment by asangster** [comment]
+1

**Comment by xmuskrat** [comment]
+1

**Comment by Oliver-Saer** [comment]
Anyone think it's a little bit too sexually suggestive?  Perhaps something like the below examples might be better (or perhaps in addition, as this has been pointed out to be a different piece of equipment which is merely associated with oil drilling anyway):

![oil-rig-icon-platform-vector-260nw-1261470166](https://user-images.githubusercontent.com/42766020/151179688-54e5c207-b097-4b98-a7fc-1b79281e502f.jpeg)
![download](https://user-images.githubusercontent.com/42766020/151179708-d5a4ebb2-3888-45af-a8cc-ef2b9aca9861.png)

**Comment by sensibleworld** [comment]
We do have this icon now: https://fontawesome.com/icons/oil-well?s=solid

**Comment by sensibleworld** [comment]
For folks following this thread, does the newly added `oil-well` icon satisfy the request? Or is an icon that more closely resembles the design in the initial post needed?

**Comment by cseymour** [comment]
It was perfect for our needs. Thank you!

**Comment by sensibleworld** [comment]
Cool. I'm going to close this issue.

**Comment by cseymour** [comment]
Hi Jory, sorry to come back to you so late but I got feedback from the
office and they say the icon needs a Rod that comes down from the head, as
they are diffferent types of wells. I've included a screenshot for
reference. Thank you!

[image: image.png]

**Comment by Oliver-Saer** [comment]
@cseymour 
> (...) the icon needs a Rod that comes down from the head, as they are diffferent types of wells.

You are able to produce your own variants of icons, either by compositing together multiple FontAwesome icons or uploading one of your own design.

It's not very likely that FontAwesome will produce such a small variation on their icon based solely upon a technical difference between oil wells.  Remember that their objective is to expand their library of icons, not to be your company's personal graphic designer.

**Comment by sensibleworld** [comment]
@cseymour Is the icon we added technically wrong, or is there a variation needed on it?
