### ISSUE TITLE
Icon Request: icon-tooth

### ISSUE THREAD

**Issue by antoineprefontaine** [FortAwesome/Font-Awesome#3645]
Hi!
Could you please add a tooth or teeth icon. I'am actually designing a new Website for a denturist, and unfortunately, I just can't find anything that could fit the needs of my customer. Thank you very much for your help. Please find enclosed a sample tooth icon. Of course, you could design whatever you want. Please appologize for my bad english, since it is my second language.
Thanks again, and best regards,  Antoine ;-)

![tooth](https://cloud.githubusercontent.com/assets/7818337/3204516/fab63934-eda9-11e3-88d7-611e0510fe63.jpg)

**Comment by gonzunigad** [comment]
+1

**Comment by ankitraturi** [comment]
+1

**Comment by jestintab** [comment]
+1

**Comment by seysoosey** [comment]
+1

**Comment by tagliala** [comment]
locking here, this is a duplicate

:lock:
