### ISSUE TITLE
Icon Request: shelfari

### ISSUE THREAD

**Issue by marcbertone** [FortAwesome/Font-Awesome#3647]
This would be very helpful for a library software application I am working on.  Thanks in advance!

http://www.shelfari.com/

**Comment by nickigreenwood** [comment]
+1 for a Shelfari icon!

**Comment by tagliala** [comment]
Shelfari eventually merged with goodreads in 2016

https://fontawesome.com/icons/goodreads-g?style=brands
https://fontawesome.com/icons/goodreads?style=brands
