### ISSUE TITLE
Icon request: fa-ruby

### ISSUE THREAD

**Issue by murtra** [FortAwesome/Font-Awesome#3654]
Hi!
As I'm a RoR developer, miss an icon with a ruby. 
Programmers could use them in our websites -as well as jewelers, of course!

![captura de pantalla 2014-06-07 a la s 18 40 11](https://cloud.githubusercontent.com/assets/1818725/3209246/cd0fff10-ee62-11e3-9ad2-0ca86e91bdfb.png)

**Comment by jarno83** [comment]
+1

**Comment by TonyPythoneer** [comment]
+1

**Comment by christianhujer** [comment]
+1

**Comment by hoviousj** [comment]
+1

**Comment by titusfortner** [comment]
+1

**Comment by hallison** [comment]
+1

**Comment by mgrachev** [comment]
:+1:

**Comment by Dev-Crea** [comment]
+1

**Comment by takebackfr** [comment]
+1 @averagegrod

**Comment by murtra** [comment]
It's done: http://fortawesome.github.io/Font-Awesome/icon/diamond/

:-)

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-ruby and fa-ruby-o was an icon that i used. If there are any problem please create an issue on the GitHub project
