### ISSUE TITLE
Icon Request: fa-soldier-helmet

### ISSUE THREAD

**Issue by JoseteLuisete** [FortAwesome/Font-Awesome#3657]
I'd like you to include in the future an icon with the shape of a soldier's helmet.
I intend to use it in a very simple game where the user should have to choose a weapon.
Thanks a lot!
![helmet](https://cloud.githubusercontent.com/assets/7236449/3210816/c0def3d2-eee8-11e3-99a8-4d66e894e338.PNG)

**Comment by mbalmaceda** [comment]
A helmet looks like this
http://cdn.fullsource.com/images/items/a/raw/P2ARW02A.jpg .

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🪖 [U+1FA96](https://emojipedia.org/emoji/%F0%9F%AA%96/) Military Helmet

**Comment by tagliala** [comment]
Since this request has not been fulfilled, I'm going to reopen this request

@JoseteLuisete if this is a problem of notifications, you can Unsubscribe

If the opener closes this issue again, I will not reopen it
