### ISSUE TITLE
Icon Request: fa-warship

### ISSUE THREAD

**Issue by JoseteLuisete** [FortAwesome/Font-Awesome#3658]
![warship](https://cloud.githubusercontent.com/assets/7236449/3210813/937503fa-eee8-11e3-9681-c768870b4a23.PNG)
I'd like you to include in the future an icon with the shape of a warship.
I intend to use it in a very simple game where the user should have to choose a weapon.
Thanks a lot

**Comment by mika76** [comment]
http://govicons.io/ has a ship icon
