### ISSUE TITLE
Icon request: icon-polaroid (card)

### ISSUE THREAD

**Issue by mjcampagna** [FortAwesome/Font-Awesome#367]
I'd love to see a Polaroid photograph icon.

**Comment by martinsnajdr** [comment]
+1

**Comment by richardtallent** [comment]
I failed on GitHub searching for some reason and just basically duplicated this request -- #8189. Sorry about that!

**Comment by richardtallent** [comment]
+1 for Knack's first (fully filled) version, which is more appropriate for card views of photo-driven social posts.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=polaroid
