### ISSUE TITLE
Icon request: icon-tv

### ISSUE THREAD

**Issue by lizrice** [FortAwesome/Font-Awesome#368]
We'd love to have a TV icon (to distinguish TV from movies).  

Love these by the way! 

Thanks,
Liz

**Comment by moazam1** [comment]
+1 

It's 2015 any chance we can have tv icon please?

Cheers!

**Comment by SebastianMucke** [comment]
+1

**Comment by Dromin** [comment]
+1

**Comment by 0syntrax0** [comment]
+2

**Comment by cvsguimaraes** [comment]
+1

**Comment by abixalmon** [comment]
+1

**Comment by Fatbat** [comment]
Why's this one not getting any attention? 4.3 saw a bunch of icons that barely had any requests and these ones with close to 100 or more seem like they're being ignored. What's up with that?

**Comment by lakario** [comment]
This is perhaps the most absurd intentional avoidance of a highly requested product feature I've ever seen. This thread has been active for 2.5 years and has (now) 94 replies. There is literally no good reason to ignore this request.

Why are you ignoring it?

**Comment by Fatbat** [comment]
^^ I wish there was a like feature for posts.

**Comment by xtrujano** [comment]
They think it's a lot more important to have a Weibo icon than a TV icon. Really guys?

**Comment by rawmaterials** [comment]
+1

**Comment by rawmaterials** [comment]
+2

**Comment by rawmaterials** [comment]
+3

**Comment by rawmaterials** [comment]
+4

**Comment by rawmaterials** [comment]
+5

**Comment by rawmaterials** [comment]
+6

**Comment by inthesauce** [comment]
+1 
We Need a TV Icon!
Please! :)

**Comment by daMupfel** [comment]
+1

**Comment by batphil** [comment]
+ 1

**Comment by tsileo** [comment]
+1

**Comment by dovydaskukalis** [comment]
I keep getting notifications to email regarding this topic, can't believe it's still not included :D I even forgot why I needed this icon...

**Comment by mziescha** [comment]
+1

**Comment by spoonmuppet** [comment]
+1 please. TV doesn't just mean old-fashioned broadcast TV, but IPTV, Video on Demand, Subscription services like NetFlix. TV isn't going away - it's evolving to be even more exciting and it needs a FontAwesome icon. Please!    (Oh and a radio one too!)

**Comment by GetGeeks** [comment]
+1

**Comment by haferje** [comment]
+1

**Comment by Stretchious** [comment]
+1

**Comment by yurenju** [comment]
+1

**Comment by timlinde** [comment]
+1

**Comment by Yaboe** [comment]
+1

**Comment by petterhj** [comment]
+1

**Comment by KirstenMeeuwis** [comment]
+1

**Comment by mcolley73** [comment]
+1 Please!

**Comment by G-Driver** [comment]
+1

**Comment by silverkorn** [comment]
@tagliala 
> -1 for old style tv

+2 to readjust.
Honestly, for an icon, I don't see how you can do a new style TV without thinking it might also be a PC monitor...
You know, I might be generalizing but I'd say that __everyone__ still use the floppy disk as icon for data recording since it would be extremely confusing putting a DVD (burning), hardisk (complicated as an icon) or the common record button (sound/music).

I know it's now in the milestone but it just wanted to clarify this. :wink:

**Comment by lfagundes** [comment]
+1

**Comment by klein141** [comment]
+1

**Comment by nlsbln** [comment]
+1

**Comment by traviswingo** [comment]
+1

**Comment by lichtamberg** [comment]
+100

**Comment by mediabeastnz** [comment]
+1

By next week maybe? ;)

**Comment by pajter** [comment]
+1

**Comment by Cartman34** [comment]
+1 It may be really useful !

**Comment by MultiTricker** [comment]
+1

**Comment by beeurd** [comment]
+1
I had a plan, and a TV set icon was the only thing I was missing! :(

**Comment by janvandijk96** [comment]
+1

**Comment by Fatbat** [comment]
+1... why can't we have a TV icon once and for all?

**Comment by littlestoatie** [comment]
+1  this is essential

**Comment by popisms** [comment]
+1

**Comment by creativereason** [comment]
+1 still needed

**Comment by maxdonetsk** [comment]
+100500

**Comment by WarFox** [comment]
Look's like @davegandy doesn't like TV. Probably he is more into Netflix and Youtube.

**Comment by mwlang** [comment]
He's just hoping the TV will die and go the way of the dodo bird before adding a TV to the collection.

**Comment by bondezbond** [comment]
any chance we can get this tv-icon?

**Comment by jacquesdancona** [comment]
+1

**Comment by techkid6** [comment]
This request is so old it didn't even use the new naming convention yet.

**Comment by tagliala** [comment]
this is one of the most requested icons, I'm pretty sure it will be part of the 5.0.0 version.

Unfortunately I don't know when it will be released, sorry

**Comment by nevenduranec** [comment]
+1

**Comment by tuxy** [comment]
+1 for fa-tv or fa-old-tv, I agree, this image bellow is the best choice for the default TV. Because its very easy to see that this is in fact "TV" even if its 16x16 pixels small. See examples bellow.

256x256 size:
![TV 256px](http://i.imgur.com/ICrVmSU.png)

64x64 size:
![TV 64px](http://i.imgur.com/0d0LdYp.png)

32x32 size:
![TV 32px](http://i.imgur.com/3XYw0L7.png)

16x16 size:
[TV 16px](http://i.imgur.com/s5AZ2MI.png)

I've requested fa-hdtv seperately at https://github.com/FortAwesome/Font-Awesome/issues/7010

**Comment by JordanTBHTechnologies** [comment]
+1

**Comment by davegandy** [comment]
Added television icon to 4.4.0-wip branch. Closing.

**Comment by lakario** [comment]
Holy hell, the epic is over! 

2 days short of 3 years in-the-making! I love you @tuxy .

**Comment by mwlang** [comment]
Those little knobs and antennas took some serious skills to draw so precisely that it's unmistakably a TV.  Plus, the extra time was needed to embed the subliminal message from "The Outer Limits" TV show.  Don't blink or you'll miss it!

**Comment by unlimited-collaborators** [comment]
about time, 3 days back i added tv png in css , and now this.
Thanks a lot Font Awesome team, keep it up.

**Comment by prcastro** [comment]
holy cow

**Comment by creativereason** [comment]
Well done. Thanks.

**Comment by unlimited-collaborators** [comment]
i appreciate your work guys , but i was not expecting TV as http://fontawesome.io/icon/television/
but more of what  tuxy suggested above. so i am am gonna stick to http://modmyi.com/attachments/forums/iphone-5-new-skins-themes-launches/674614d1406083089-lion-d-tv.png

Thanks

**Comment by tagliala** [comment]
@unlimited-collaborators please start a new request

**Comment by Samoht-fr** [comment]
+1

**Comment by lizrice** [comment]
+1 for @tuxy's version, that's just what I was hoping for!
