### ISSUE TITLE
Icon Request: Letterboxd

### ISSUE THREAD

**Issue by natedillon** [FortAwesome/Font-Awesome#3680]
[Letterboxd](http://letterboxd.com/) is a social network for sharing your taste in film.

They have a [media kit](http://letterboxd.com/about/media-kit/) with the logo available in various formats.

![image](https://cloud.githubusercontent.com/assets/487121/3234370/aa55bd54-f0c7-11e3-8672-17044ef62b54.png)

![image](https://cloud.githubusercontent.com/assets/487121/3234360/a40fdefc-f0c7-11e3-8a4d-93dbc08ff59a.png)

**Comment by saviomd** [comment]
+ 1

**Comment by sivaram2** [comment]
+100

**Comment by PeteCrighton** [comment]
+1

**Comment by Rumcleay** [comment]
+1

**Comment by ameswarb** [comment]
:+1:

**Comment by zackrabie** [comment]
+1

**Comment by zanetaylor** [comment]
+1

**Comment by robdukes** [comment]
+1

**Comment by Maradonna90** [comment]
+1 although i would love the three dots

**Comment by MattJackWilson** [comment]
+1111111111111111111111111111111111111111111111111111111111111111111111111111

**Comment by AguedaBinpar** [comment]
+1

Please!

https://letterboxd.com/about/logos/

**Comment by sjdvda** [comment]
+1

**Comment by plisker** [comment]
+1

**Comment by DarkHorseDumpling** [comment]
+1

**Comment by mi-lad** [comment]
+1

**Comment by dogtownboy** [comment]
+1 Since there is an offical vector graphic it should be a quick job? Would be so nice, thx!

**Comment by tylerjbainbridge** [comment]
+1

**Comment by fahdikrie** [comment]
+1 yes please!

**Comment by Rear-Window** [comment]
+1

**Comment by sangeet259** [comment]
+1

**Comment by TheFlow95** [comment]
+1 please!!

**Comment by 3mrdev** [comment]
+1 weeeee neeeeed it

**Comment by coderIlluminatus** [comment]
+1 Please

**Comment by qubist** [comment]
+1!

**Comment by matthewbuchanan** [comment]
Our brand has been updated since this request was lodged. We have two options for social decals, [available for download in SVG format here](https://letterboxd.com/about/brand/#social) and shown below.

<img width="340" alt="Screen Shot 2020-08-26 at 4 55 48 PM" src="https://user-images.githubusercontent.com/531516/91257026-f942e480-e7bc-11ea-81b5-dd215f6eade4.png">

**Comment by earthbound42** [comment]
+1

**Comment by bdjessup** [comment]
+1

**Comment by crunchprank** [comment]
Stop commenting with `+1`. It contributes nothing. This is an issue tracker. If you agree with the feature request, then add the appropriate reaction to the original post.

**Comment by vickylim** [comment]
Yes! The three dots one, please!

**Comment by jithpaul** [comment]
+1

**Comment by sensibleworld** [comment]
Added! 
https://fontawesome.com/icons/letterboxd?f=brands&s=solid
https://fontawesome.com/icons/square-letterboxd?f=brands&s=solid

**Comment by matthewbuchanan** [comment]
@sensibleworld Thanks Jory!

**Comment by sensibleworld** [comment]
@matthewbuchanan Sorry it took so long!

**Comment by matthewbuchanan** [comment]
@sensibleworld We’ve _finally_ made it, but good things take time. 😄

**Comment by AguedaGamez** [comment]
Thanks!!!!
