### ISSUE TITLE
Icon-Request: fa-slash

### ISSUE THREAD

**Issue by st-keller** [FortAwesome/Font-Awesome#3691]
I would like to have a simple slash-icon.

A slash is already used in "fa-eye-slash" and "fa-microphone-slash".

If i had a "slash" i could build "slashed" -versions of all Icons using the awesome "Stacked Icons"-Feature. This would be cool!

**Comment by bwross** [comment]
+1

**Comment by tiandavis** [comment]
+1

**Comment by jp26jp** [comment]
+1

**Comment by tagliala** [comment]
Take a look at this project: https://github.com/nyon/fontawesome-actions

https://github.com/FortAwesome/Font-Awesome/issues/1181#issuecomment-87315812

**Comment by caBBAlainB** [comment]
+1

**Comment by rpkilby** [comment]
+1

**Comment by abdelrahman-elkady** [comment]
+1

**Comment by skylord123** [comment]
+1

**Comment by Vallenain** [comment]
+1 !

**Comment by Krevo** [comment]
+1

**Comment by jabarnes** [comment]
+1

**Comment by lyhil** [comment]
+1 totally agree

**Comment by ellisthedev** [comment]
+1

**Comment by sevisilex** [comment]
+1

**Comment by ckeryakes** [comment]
+1

**Comment by damiankaplewski** [comment]
+1

**Comment by vfportero** [comment]
+

**Comment by ragivi** [comment]
+1

**Comment by MSbitani** [comment]
+1

**Comment by changbenny** [comment]
+1

**Comment by circleb** [comment]
+1

**Comment by forecastly** [comment]
+1

**Comment by mleczakm** [comment]
+1

**Comment by hassan-tariq** [comment]
+1

**Comment by dmland** [comment]
Still a bit of a work in progress, but I have had success simulating the slash with the following style (and by adding the class `fa-slash` to items that want a slash):

```
i.fa.fa-slash::after {
  content: '\2571';
  font-weight: bold;
  text-shadow: 0.75px 0px 0px white;
  position: absolute;
  left: 1px;
  transform: scale(3,0.7) translate(0.5px, 1px) skewX(41deg);
}
```

I call it a work in progress because it requires tweaking the `transform` parameters to position and size the slash to accommodate various FontAwesome characters.

As a preview, the style above almost exactly emulates the slash on fa-eye:

<img width="419" alt="screenshot 2016-08-23 16 37 32" src="https://cloud.githubusercontent.com/assets/1907073/17913615/3f4f3414-6950-11e6-97a8-1ca15da6a6f6.png">

**Comment by pytlus93** [comment]
+1

**Comment by trackor** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by annasimoniaine** [comment]
+1

**Comment by djechelon** [comment]
+1

**Comment by joshbg2k** [comment]
+1

**Comment by Soaku** [comment]
Yes, that would be great! Why create *-slash icons, when there are stacked ones already? :D

**Comment by xS1ngh** [comment]
+1

**Comment by iamericanartist** [comment]
Do it For Christmas... DO IT FOR THE CHILDREN... 🎅 👶

**Comment by tagliala** [comment]
I think that the SVG framework layering and masking feature will benefit of such an icon

**Comment by Wildhammer** [comment]
+1

**Comment by ttkaine** [comment]
+1

**Comment by chasepeeler** [comment]
+1 I've got so many places where I could use this. I made this request on twitter before I was aware of the proper way to make requests. This one icon gives you 2,790 new icons!

It would lend itself to a brand new category of "overlays" - icons that are mainly designed to be stacked on other icons.

**Comment by amilabandara** [comment]
I was wondering why they didn't make it yet. It's almost 4 years after the initial request.
Guys it's highly appreciated if you can give us forward slash.
Thanks for the awesome work. I'm a big fan and using FA for all of my projects :) BIG HUG

**Comment by SDekkers** [comment]
+1

**Comment by sensibleworld** [comment]
Per @chasepeeler's comment, we've just added thousands of new icons with this single addition: https://fontawesome.com/icons/slash?style=solid

(We'll be posting some demos soon of how to use layering to match our negative space styling on `-slash` icons.)

**Comment by trackor** [comment]
Great news ... Thank you!

**Comment by chasepeeler** [comment]
@sensibleworld Did those demos of how to layer to match the negative space styling ever get posted?

**Comment by LeoJweda** [comment]
@sensibleworld Where can we see the demos for matching the negative space style? I can't find it anywhere in the docs.

**Comment by tagliala** [comment]
Hi!

Waiting for some documentation, please take a look at this example: https://jsfiddle.net/tagliala/raz41dLh/9/

```html
<div class="abs fa-layers fa-fw fa-5x">
  <span class="fas fa-slash" data-fa-mask="fas fa-user" data-fa-transform="down-2.5"></span>
  <span class="fas fa-slash"></span>
</div>
```

I don't know what @sensibleworld has in mind for the documentation, but with `data-fa-transform="down-2.5"` you can match the negative space in a lot of use cases

**Comment by code-alt** [comment]
yes

i would love microphone-slash

**Comment by code-alt** [comment]
+1

+1000 IQ

**Comment by AlonsoK28** [comment]
### angular version

```html
<fa-layers>
     <fa-icon [icon]="faSlash" [mask]="faShirt" transform="down-2"></fa-icon>
     <fa-icon [icon]="faSlash"></fa-icon>
</fa-layers>
```
