### ISSUE TITLE
Icon Request: passport

### ISSUE THREAD

**Issue by owendismuke** [FortAwesome/Font-Awesome#3695]
I want to use it in an existing project where I ask if they need to clear customs.
EDIT: JSFiddle with SVG versions: http://jsfiddle.net/6V3vh/1/
![passport](https://cloud.githubusercontent.com/assets/1171432/3263173/d7789524-f26e-11e3-9c76-6d73a404f99a.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/passport?style=solid
