### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by anandrajana** [FortAwesome/Font-Awesome#3698]
Icon-request: icon-live-stream
Use case: 
While displaying a live streaming player. The live stream broadcast icon is used.
Icon:
https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&docid=8yAKdOSCdmFqtM&tbnid=Hi0wk43yOpaY2M:&ved=0CAUQjRw&url=http%3A%2F%2Fwww.eastvillageradio.com%2Fmobile%2F&ei=CZSaU5KjDIfIkQWL6oHICQ&bvm=bv.68911936,d.dGI&psig=AFQjCNFTOzk23Ri4pPZyuGJbwVobDIvq1g&ust=1402725735654441

**Comment by aethior** [comment]
@tagliala Duplicate? #5530

**Comment by tagliala** [comment]
I really can't tell. Closing here because of missing feedback
