### ISSUE TITLE
Icon request: icon-water-glass, icon-wine-glass, icon-whisky-glass

### ISSUE THREAD

**Issue by SweVictor** [FortAwesome/Font-Awesome#370]
Hi,
Right now there is a very nice drink glass icon (icon-glass). It would be very nice if there were some other glasses as well (water, wine, whisky)

Thanks for a great project!
/Victor

**Comment by emilklindt** [comment]
+1 on water

**Comment by G-Driver** [comment]
+1

<img src="http://static.vecteezy.com/system/resources/previews/000/044/420/original/wine%20glass%20symbol.jpg">

**Comment by phillq** [comment]
+1

**Comment by kewh** [comment]
+1

**Comment by w5d** [comment]
+1

**Comment by shanetheboland** [comment]
+1

**Comment by bigsea** [comment]
+1 wineglass!!

**Comment by lori** [comment]
+1 wine glass

**Comment by kaiazeekee** [comment]
+1 for glassware that isn't necessarily alcohol related (working with charity events)

Possibly ice tea class with a lemon? (also from the south)

**Comment by santinoalbert** [comment]
+1 for wine icons!

**Comment by JJ69** [comment]
+1 for wineglass icon

**Comment by willythekid1979** [comment]
+1

**Comment by revweb** [comment]
+1

**Comment by nbunney** [comment]
+1 for all three

**Comment by nathancouch** [comment]
Any update on wine glass and bottle icons?

**Comment by carolaclavo** [comment]
+1

**Comment by Melloyell** [comment]
+1

**Comment by Crissov** [comment]
## Unicode Glass Emojis
#222 

- 🍺 [U+1F37A](http://emojipedia.org/beer-mug/) and 🍻 [U+1F37B](http://emojipedia.org/clinking-beer-mugs/) Beer Mugs
- 🍷 [U+1F377](http://emojipedia.org/wine-galss/) Wine Glass
- 🍸 [U+1F378](http://emojipedia.org/cocktail-glass/) Cocktail Glass
- 🍹 [U+1F379](http://emojipedia.org/tropical-drink/) Tropical Drink 
- 🍾 [U+1F37E](http://emojipedia.org/bottle-with-popping-cork/) Champagne Bottle
- 🍼 [U+1F37C](http://emojipedia.org/baby-bottle/) Baby Bottle
- 🥃 [U+1F943](http://emojipedia.org/tumbler-glass/) Tumbler/Whiskey Glass
- 🥂 [U+1F942](http://emojipedia.org/clinking-glasses/) Champagne Glasses
- 🥛 [U+1F95B](http://emojipedia.org/glass-of-milk/) Milk Glass
- &#x1F964; [U+1F964](http://emojipedia.org/cup-with-straw/) Cup with Straw / Soft Drink *probably* in [Unicode 10.0](http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f964). → #6122

**Comment by stgoos** [comment]
+1 for the Glencairn whisky glass as it's one of the most used and iconic glasses for tasting (and of course enjoying) whisky

https://moorewilsons.co.nz/media/catalog/product/cache/1/image/800x/602f0fa2c1f0d1ba5e241f914e856ff9/g/l/glencairn-whisky-glass/glencairn-whisky-tasting-glass-30.jpg
http://www.glencairnwhiskyglass.com/

**Comment by jamiefutscher** [comment]
+1 for as many glasses as you can!

**Comment by 4briang** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by labregowski** [comment]
+1 for wine glass, dear Sir :D

**Comment by carterdesign** [comment]
+1

**Comment by Monster695** [comment]
+1

**Comment by vmorreel** [comment]
Issue opened in 2012, nothing in 2017 ... plz +1 for glass icons

**Comment by demelvin** [comment]
+1

**Comment by pesama** [comment]
+1

**Comment by shemake** [comment]
+1 for neutral water glass.  Would be nice to have a non alcohol/caffeine related drink icon, to use in fitness apps.  Could also double as juice/milk/generic drink when colored.

**Comment by mengzy2018** [comment]
#1828 That's already there

**Comment by sensibleworld** [comment]
We've added a simple `glass` icon to Font Awesome: https://fontawesome.com/icons/glass?style=solid
