### ISSUE TITLE
New Icon : Delivery & Logistics

### ISSUE THREAD

**Issue by archyj** [FortAwesome/Font-Awesome#3700]
Hi Team! 

At the outset, thank you very much for building such a great project! I cannot appreciate you enough.

All this while I had not found a single icon that was not available on Font Awesome. However, I need a few delivery and reverse delivery related icons. I plan to use them in powerpoint presentations to show up as part of an animation. 

I am attaching a few that I have use for almost immediately. 

Thank you very much! 
Oh! Did I mention? You guys are AWESOME :100: 

![delivery](https://cloud.githubusercontent.com/assets/7878067/3267428/5bcf5bc0-f2cc-11e3-8996-83ad02dc7d43.jpg)
![return](https://cloud.githubusercontent.com/assets/7878067/3267435/9e032d50-f2cc-11e3-9598-991d78815e0f.jpg)

**Comment by MVcodeartbr** [comment]
+1

sugestion:
![88f4f2b685bbc66325770e7c340cfe61](https://cloud.githubusercontent.com/assets/3662026/11433009/28d49f52-949f-11e5-87b8-57517f68c318.jpg)
![depositphotos_15752021-delivery-man-postman-courier-post-stick-figure-pictogram-icon](https://cloud.githubusercontent.com/assets/3662026/11433010/28d88d4c-949f-11e5-82fb-4528e6247831.jpg)
![images](https://cloud.githubusercontent.com/assets/3662026/11433011/28f7c4dc-949f-11e5-95b5-b9d5d049e2b2.jpg)
![logistic-warehouse-delivery-icon-22112276](https://cloud.githubusercontent.com/assets/3662026/11433012/28fad938-949f-11e5-8128-8bf1da464f06.jpg)
![shipping-delivery-vector-icons-set-gray-icon-grey-background-eps-file-available-33973031](https://cloud.githubusercontent.com/assets/3662026/11433013/2903e5b4-949f-11e5-93a0-6ae81302db30.jpg)

**Comment by tagliala** [comment]
Sorry but I can't keep this open, this request doesn't meet our contributing guidelines anymore

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
