### ISSUE TITLE
Icon request: fa-incoming-call, fa-outgoing-call, fa-missed-call, fa-total-call

### ISSUE THREAD

**Issue by moimael** [FortAwesome/Font-Awesome#3701]
Hi,

I'm a big fan of font awesome, used it a lot in personal projects (thanks for the truely amazing work btw !), and I'm currently using it for a big web administration panel, used to control business telephony.

Usually, I can found almost everything in fa icons, but this time, I would need these icon, if you think they may also be useful for other people as well if you have some free time !

Something along those : 

Outgoing call:
![Alt Text](http://www.flaticon.com/png/256/17826.png)

Incoming call:
![Alt Text](http://www.flaticon.com/png/256/17217.png)

Missed call: 
![Alt Text](http://icons.iconarchive.com/icons/visualpharm/icons8-metro-style/512/Phones-Missed-call-icon.png)

And no idea for total call...

Also (I don't know if it's possible) add the possibility to rotate icon to an arbitrary angle (like 66°) may help in some case.

Thanks !

**Comment by vdemin** [comment]
+1

**Comment by alexphelps** [comment]
+1

**Comment by matak** [comment]
+1

and phone trasnfered, phone conference call, phone callback call, all incoming, outgoing and busy, answered, notanswered variants, but busy, ans, not ans should be only different colors

**Comment by fme-samuelbirk** [comment]
+1

**Comment by dimkasta** [comment]
+1

**Comment by rabrowne85** [comment]
+1

**Comment by defaultwinner** [comment]
+1

**Comment by vigneshprakasam33** [comment]
+1

**Comment by kiddy2910** [comment]
+1

**Comment by valentinLecorps** [comment]
+1

**Comment by AlexandreFournier** [comment]
+1

**Comment by kargpfen** [comment]
+1

**Comment by danilosetubal** [comment]
+1

**Comment by hassanalami** [comment]
this should absolutely figure in the 5.0.0 milestone :(

**Comment by Aurontwist** [comment]
+1

**Comment by apivaral** [comment]
+1

**Comment by midi9x** [comment]
+1

**Comment by buzzb0x** [comment]
+1

**Comment by yolao** [comment]
1+

**Comment by canbax** [comment]
+1

**Comment by ichirkin** [comment]
+1

**Comment by philljones** [comment]
+ 1

**Comment by Dalf91x** [comment]
+1

**Comment by gordonzero** [comment]
+1

**Comment by gordonzero** [comment]
Also a Call Recording icon would be nice. Phone with the round recording symbol in the bottom right hand corner.

**Comment by anonrig** [comment]
+1

**Comment by ghenry** [comment]
One day?

**Comment by data-handler** [comment]
Also, Internal Call

**Comment by icyz** [comment]
any news?

**Comment by endo64** [comment]
Here are some other possible icons:

- incoming
- outgoing
- internal
- forward
- transfer
- pickup
- busy
- no answer
- conference
- recording
- IVR
- SIP

Here some information: [Cisco Reason Codes](https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cucm/service/11_5_1/cdrdef/cucm_b_cucm-cdr-administration-guide-1151/cucm_b_cucm-cdr-administration-guide-1151_chapter_0110.html)

**Comment by PinkMeNow** [comment]
+1

**Comment by linadmax** [comment]
+1

**Comment by codyreed** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks. This is available in the version 6 alpha release: https://fontawesome.com/download

**Comment by tajangi** [comment]
+1
