### ISSUE TITLE
Icon-request: grabby-hand

### ISSUE THREAD

**Issue by conryf** [FortAwesome/Font-Awesome#3716]
I would like to use a grabby hand for map panning like the one you use in acrobat reader. 
![screen shot 2014-06-15 at 2 27 26 pm](https://cloud.githubusercontent.com/assets/1693638/3281929/a9fc50ea-f4cb-11e3-9fec-6bafc910182b.png)

**Comment by alex-pl** [comment]
+1

**Comment by hdachev** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.
