### ISSUE TITLE
Icon-request: Ear icon

### ISSUE THREAD

**Issue by jweaver60** [FortAwesome/Font-Awesome#3726]
It would be great to have an ear icon like this:
![1f442-ear 100](https://cloud.githubusercontent.com/assets/1394712/3287957/34c7c136-f55e-11e3-85ee-daf49bf25217.png)

**Comment by lwanu** [comment]
+1

**Comment by coreyleedesigns** [comment]
+ 1 on this

**Comment by oriadam** [comment]
+1

**Comment by oriadam** [comment]
+1

**Comment by gitnowlegal** [comment]
+1

**Comment by jackg0h** [comment]
+1

**Comment by tahpot** [comment]
+1

**Comment by Dewsworld** [comment]
+1

**Comment by pedrosalpr** [comment]
+1

**Comment by marven89** [comment]
+1

**Comment by apinner** [comment]
+1

**Comment by canonex** [comment]
+1

**Comment by kixe** [comment]
+1

**Comment by amarewgs** [comment]
is this not included in the current version??

**Comment by tagliala** [comment]
@amarewgs no, it isn't

**Comment by Esty12** [comment]
+1

**Comment by phoebebright** [comment]
+1

**Comment by rajrsingh** [comment]
+1 good alternative fa-blind with positive connotation instead of focusing on the disability. My app needs to indicate that the UX is optimized for hearing rather than sight

**Comment by bradreeder** [comment]
+ 1

(p.s. why +1 when github allows you to thumb the original post >_>)

**Comment by Canubiz** [comment]
+1

Really wondering how this is an open issue for 3,5+ years, while there already is an ear icon with a strike through. Maybe we could just get an adapted version of that?

**Comment by seezee** [comment]
+1

**Comment by sensibleworld** [comment]
This icon was added to Font Awesome Pro in version 5.2.0: https://fontawesome.com/icons/ear?style=solid

**Comment by jaffeelu** [comment]
+1
