### ISSUE TITLE
Icon Request: fa-code-merge

### ISSUE THREAD

**Issue by SamHatoum** [FortAwesome/Font-Awesome#3743]
In the web application icons, there is an [fa-code-fork](http://fortawesome.github.io/Font-Awesome/icon/code-fork/). I would love to also have a code-merge, like [here on Github](https://github.com/search?q=merge&ref=cmdform&type=Issues).

I would like to use this in my app, where I'm creating a github connector and I therefore not have to load the octicon.wiff font from git.

**Comment by phecho** [comment]
+1
