### ISSUE TITLE
Bug: fa-pencil-square not working

### ISSUE THREAD

**Issue by Chet3x16** [FortAwesome/Font-Awesome#3746]
Hi, Font Awesome is great!

fa-pencil-square [&#xf14b;] doesn't work... I added this to my html
<i class="fa fa-pencil-square"></i>

I even went into CSS and added this
.fa-pencil-square:after { content: "\f14b"; font-family: "FontAwesome"; }

i'm using version 4.1.0 on Ruby on Rails

Thanks!

**Comment by abdulqadir7780** [comment]
I have the same issue it's working, I have tried different CDNs results are same. :-(
