### ISSUE TITLE
Icon Request: fa-ranking-ribbon

### ISSUE THREAD

**Issue by shanehoban** [FortAwesome/Font-Awesome#3747]
It'd be really nice to have a ribbon; like a first place ribbon for example.

My inspiration for this is that I have a ranking list, and would like the top to have a ribbon. The rest have the same. Maybe even 1st, 2nd, and 3rd medal icons even.

I envision the ribbon to look something similar to <a href="http://fortawesome.github.io/Font-Awesome/icon/bookmark-o/" target="_blank">fa-bookmark-o</a>, that is a really nice icon.

![ribbon with star](https://cloud.githubusercontent.com/assets/1383797/3338347/586ae4e8-f85a-11e3-815c-7dd51e1d2d85.png)

Anyway, thanks for the unbelievably good work!
Shane

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🎖️ [[U+1F396, U+FE0F]](https://emojipedia.org/emoji/%F0%9F%8E%96/) Military Medal

Also known as `Medal`, `Medallion` and `Military Decoration`.
