### ISSUE TITLE
Icon Request: fa-phone-o

### ISSUE THREAD

**Issue by StephenBrownski** [FortAwesome/Font-Awesome#3750]
Pretty simple. Just an outline phone variant, like [fa-bookmark-o](http://fortawesome.github.io/Font-Awesome/icon/bookmark-o/).

An outline variant was used in a site redesign I received, and I was a little surprised to see that there did not exist a fa-phone-o.

**Comment by vdemin** [comment]
+1

**Comment by tenderloin420** [comment]
+24

**Comment by kiral6** [comment]
+20
![icon_phone](https://cloud.githubusercontent.com/assets/5805003/12141603/e581cba8-b4ab-11e5-89bf-1405a5c2d192.png)

**Comment by nicolasandrieux** [comment]
+ over 9000

but can't wait so

here is the same svg icon in outline
https://www.onlinewebfonts.com/icon/367571
and here is a tools to build your on font using that svg
https://glyphter.com/

cheers

**Comment by zipper** [comment]
+1

**Comment by sensibleworld** [comment]
This icon was added to Font Awesome Pro! https://fontawesome.com/icons/phone?style=regular
