### ISSUE TITLE
Icon request: fa-folder-new

### ISSUE THREAD

**Issue by taplar** [FortAwesome/Font-Awesome#3752]
Icon signifies a new folder.  Use case is a site editor in which the clicking of the fa-folder-new icon would initiate the logic to create a new directory.

For what it would look like, I imagine either:
1) fa-folder-open-o with fa-folder-o situated inside it
2) fa-folder-o with a plus sign or astrix to signify add/new

**Comment by samkelly** [comment]
I also need this

**Comment by Chinthyyy** [comment]
+1

**Comment by Josh-Burgess** [comment]
:+1:

**Comment by marcelmoosbrugger** [comment]
:+1:

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/folder-plus?style=solid
