### ISSUE TITLE
icon-request: fa-award

### ISSUE THREAD

**Issue by crgibbons** [FortAwesome/Font-Awesome#3753]
Looking for a small "award" icon.  (Would greatly appreciate any "academia" flavored icons, too. fa-dissertation? fa-book? fa-advisor? etc!)

**Comment by cobe1972** [comment]
I need a fa-award icon too. I leave a few that I have made with the fa-sun
![fa-award](https://cloud.githubusercontent.com/assets/16846747/12527806/1a2b2546-c183-11e5-85e0-6c0ff5d77d54.jpg)

**Comment by tagliala** [comment]
Closing here in favour of #4246
