### ISSUE TITLE
Icon Request: Patient

### ISSUE THREAD

**Issue by petcurfew** [FortAwesome/Font-Awesome#3780]
An icon representing a Patient (medical context/fa-user-patient):

![image](https://cloud.githubusercontent.com/assets/1471600/3391238/26d2fc48-fca8-11e3-9155-682a7aac2716.png)

To be used in a Patient Scheduling Portal, and to complement the fa-user-md icon.

**Comment by niteshp** [comment]
@tagliala I see mine was a dupe of this one.  Would you know if this is still on the anvil (this request was opened ~ 2yrs back) ?  If so, when might it be released ?

**Comment by seysoosey** [comment]
+1

**Comment by im-jdamb89** [comment]
+2

To be used in medical app for doctors seeing patients. Agreed, would be good complement to fa-user-md.

**Comment by kimberley-johnston** [comment]
+1

**Comment by gomes2191** [comment]
In my opinion, it would be better to have a generic icon that works for a dental clinic patient and for a medical clinic

**Comment by aethior** [comment]
Hi @petcurfew,

This icon was added in v5.4.0.
Check https://fontawesome.com/icons/user-injured

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here. :)
