### ISSUE TITLE
Icon request: palm-tree-island

### ISSUE THREAD

**Issue by dijitaltrix** [FortAwesome/Font-Awesome#3786]
Hi,

Firstly thanks for the icon set!

I'd like to see in icon of a single palm tree on an island, it would be great to represent holiday/vacation destinations.

Thanks,
Ian

**Comment by thomasvnl** [comment]
+1

**Comment by SanthoshMR** [comment]
+1

**Comment by EppO** [comment]
+1

**Comment by sba** [comment]
+1

**Comment by DR-Kay** [comment]
+1

**Comment by orcastu** [comment]
+1

**Comment by jsertx** [comment]
+1 for a palm tree

**Comment by mrthan** [comment]
+1 We are looking for the same - something to represent "holiday"

**Comment by jmann-ts** [comment]
+1 Palm Tree/Island

**Comment by gotdibbs** [comment]
+1 for Palm Tree

**Comment by Harti** [comment]
@gotdibbs definitely worth a shot, I don't see anything speaking against that!

**Comment by gotdibbs** [comment]
#6950 was closed. I'm not sure if they're planning on adding their own icon, but it seems like they don't plan on exposing the icon already existing in the unicode Miscellaneous Symbols and Pictographs block.

If you need to use a palm tree icon (&#x1f334;) for now you can add your own class to expose the icon. Example class below would be used the same way as any other Font Awesome icon class like `class="fa fa-palm-tree"`.

```css
.fa-palm-tree:before {
    content: "\1f334";
}
```

Special thanks to [this site](http://www.fileformat.info/info/unicode/char/1f334/index.htm) for pointing me to the existence of the icon.

**Comment by tagliala** [comment]
@gotdibbs thanks!

**Comment by orcastu** [comment]
Nice work around @gotdibbs Thanks

**Comment by aroniotis** [comment]
+1

**Comment by khoanguyen123** [comment]
+1 for palm tree on island

**Comment by shmaster** [comment]
+1

**Comment by jqrsd** [comment]
+1
palm or anything else representing holiday

**Comment by CagedEcho** [comment]
+1
Island / palm tree

**Comment by ChristophAnastasiades** [comment]
+1

**Comment by StephanHinkel** [comment]
+1

**Comment by 23tux** [comment]
+1

**Comment by maxmadknight** [comment]
+1

**Comment by mansa-dev** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode emojis: #222

- **[🏝 U+1F3DD](http://emojipedia.org/desert-island/)**
- [🏖 U+1F3D6](http://emojipedia.org/beach-with-umbrella/)
- [🌴 U+1F334](http://emojipedia.org/palm-tree/)

**Comment by bmanke22** [comment]
+1

**Comment by Jamonzito** [comment]
+1

**Comment by WaynePhipps** [comment]
+1

**Comment by Golddragon152** [comment]
+1

**Comment by spaky08** [comment]
+1

**Comment by sanderbakker** [comment]
+1

**Comment by armen115** [comment]
+1

**Comment by andreeag3191** [comment]
+1

**Comment by Rainson12** [comment]
+1

**Comment by llann** [comment]
+1

**Comment by deyvisonrocha** [comment]
+1

**Comment by 301gene** [comment]
+1

**Comment by sensibleworld** [comment]
It's below freezing, and these icons are looking mighty good to me right now:

https://fontawesome.com/icons/tree-palm?style=solid
https://fontawesome.com/icons/island-tropical?style=solid
