### ISSUE TITLE
Icon Request: fa-nuke

### ISSUE THREAD

**Issue by eurochriskelly** [FortAwesome/Font-Awesome#3788]
Hi,

I was looking for a icon for launching a program and someone suggested a mushroom cloud symbol.  While searching for an alternative I tried radiation which I couldn't find. This got me thinking that a few safety icons such as biological hazard, radiation zone and the like could be useful and so I decided to suggest them. 

Thanks,
Chris

**Comment by tagliala** [comment]
I'm cleaning up old issues

Duplicate of #1967
