### ISSUE TITLE
Icon HTML Form Tag

### ISSUE THREAD

**Issue by PhucPM** [FortAwesome/Font-Awesome#3794]
Hi you! So far I have not seen the icons for the HTML Form tag example: Text Input, Input number, Checkbox, Radio Button Submit ... You can add icons to the font that is not awesome? Thank you much

**Comment by Orlando-iSam** [comment]
I second ^

**Comment by tagliala** [comment]
Sorry, can't keep this open

These requests are hard to maintain and to implement

We recently updated our contributing guidelines to deal with requests like this one: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
