### ISSUE TITLE
barcode is too fine

### ISSUE THREAD

**Issue by tablatronix** [FortAwesome/Font-Awesome#3797]
Its cool that the barcode is real and scan-able.

But it seems very fine at normal size, so fine that the lines are barely discernable at 1em and instead i get a rainbow moir effect.

**Comment by sensibleworld** [comment]
This is still an issue in FA 5.0, but we do now have a few alternate versions: https://fontawesome.com/icons?d=gallery&q=barcode.

**Comment by tablatronix** [comment]
lol wow

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download

**Comment by tablatronix** [comment]
Sweet lol
