### ISSUE TITLE
Redo icon

### ISSUE THREAD

**Issue by ream88** [FortAwesome/Font-Awesome#381]
I can find an `undo` icon, but the `redo` seems to be missing. Any chance to get it included?

**Comment by anevaude** [comment]
Just updating to let people know this is still a thing in 2018. I tried using fa-redo and it did not work. fa-repeat, however, works. Good luck!

**Comment by tagliala** [comment]
Hi, this icon has been introduced in 1.0 as `icon-repeat`: https://fontawesome.com/v4.7.0/icon/repeat/

In FA5 has been renamed to redo.

![image](https://user-images.githubusercontent.com/556268/36024347-cae3f17e-0d8f-11e8-865d-275a3fdbc667.png)
