### ISSUE TITLE
Icon Request: fa-plant

### ISSUE THREAD

**Issue by TajinValorian** [FortAwesome/Font-Awesome#3810]
A plant-icon, possibly similar to the one seen in Wall-E.
https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSJP88HEnMgCAm1u87CME0cCYhRB2by2gpNkiXjWO1E-iO5hlb5pw

**Comment by G-Driver** [comment]
+1 for plant

**Comment by sensibleworld** [comment]
Released in 5.0.9

**Comment by tagliala** [comment]
@sensibleworld what is the 5.0.9 name for this icon?

**Comment by sensibleworld** [comment]
@tagliala Icons are here: https://fontawesome.com/icons?d=gallery&q=seedling

**Comment by tagliala** [comment]
thanks!
