### ISSUE TITLE
Icon request: Pile of Poo

### ISSUE THREAD

**Issue by spitz-dan-l** [FortAwesome/Font-Awesome#3812]
Hello, in my professional work as a real developer I have repeatedly come across the need for a **Pile of Poo FontAwesome icon**. It would make my working life much easier and would increase public adoption of FontAwesome. It should be in the style of the **pile-of-poo emoji**. ROI way up maxed out.

Thank you!

**Comment by romaluca** [comment]
+1!

**Comment by momentmaker** [comment]
:hankey: :+1:

**Comment by nextlevelshit** [comment]
+1

**Comment by SpencerCDixon** [comment]
+1

**Comment by cmoses8626** [comment]
I need this. Please make it happen.

**Comment by johhny13** [comment]
+1

**Comment by VilleKoo** [comment]
+1

**Comment by aadamyan** [comment]
+1

**Comment by dbwest** [comment]
+1

**Comment by patrick-evolabs** [comment]
+1

**Comment by killnine** [comment]
+1

**Comment by brainscript** [comment]
**+1** Would love to see this! :hankey:

**Comment by santafebound** [comment]
Please add pile of poo!

**Comment by adrisons** [comment]
💩 +1

**Comment by Crissov** [comment]
* [💩 U+1F4A9 Pile of Poo](http://emojipedia.org/pile-of-poo/)

Is there any issue tracking coverage of the Unicode emoji set?

**Comment by vinnyamp** [comment]
+1

**Comment by fertone** [comment]
+1

**Comment by santafebound** [comment]
I have an upcoming project that has a serious need for the pile of poo font. Is this in the pipeline?

**Comment by ccamacho** [comment]
"Serious need" xD

**Comment by santafebound** [comment]
Lol I know it sounds ridiculous but I'm not joking. I'd rather call Pile of Poo from FontAwesome than serve a lame static image file.

**Comment by InvisibleMan1306** [comment]
+1

**Comment by santafebound** [comment]
Thanks guys! Pile of poo looks fantastic: `<i className="fa fax-pile-of-poo fa-md"></i>`

**Comment by JakeVestal** [comment]
?what's the deal?  I too have a "serious need" for this icon... but i can't find it in the Font Awesome list!  What a crappy situation ;)

**Comment by NikhilMTomy** [comment]
+1

**Comment by mkelley82** [comment]
💩 +1

**Comment by Linaida** [comment]
💩 +1

**Comment by maleeeeza** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/poo?style=solid
https://fontawesome.com/icons/poop?style=solid
