### ISSUE TITLE
Icon Requests: Developer Icons

### ISSUE THREAD

**Issue by haydenbleasel** [FortAwesome/Font-Awesome#3822]
I think these icons would be really valuable for developers, to go along with ones like [fa-sass](https://github.com/FortAwesome/Font-Awesome/issues/2894) and [fa-less](https://github.com/FortAwesome/Font-Awesome/issues/2567). I find myself wanting these icons all the time so I usually have to go and hack a rasterised logo apart in Photoshop. I didn't see any similar issues so sorry if I've duplicated. Also open to suggestions to add.
- [fa-bower](http://bower.io/img/bower-logo.png)
- [fa-grunt](http://gruntjs.com/img/grunt-logo.png)
- [fa-gulp](https://raw2.github.com/gulpjs/artwork/master/gulp-2x.png)
- [fa-npm](https://www.npmjs.org/static/img/npm.png)

**Comment by cyberkatze** [comment]
+100500

**Comment by tagliala** [comment]
Locking here, please read why in the above comments :lock:
