### ISSUE TITLE
Make version inclusion a conditional

### ISSUE THREAD

**Issue by ssured** [FortAwesome/Font-Awesome#3823]
Currently in `_path` source files, `?v=#{$fa-version}` is appended to all urls. I understand this is a really nice default for automatic caching scenarios. In my scenario though it's a pain, as we have versioning arranged in an html5 appcache manifest. We automatically build the appcache from filenames where there is no way to know which version is used causing the browser to not find the font file in its cache.

I'd love to have a directive `$fa-append-version = true/false` which toggles appending the version:

```
$fa-append-version defaults to true

@font-face {
  font-family: 'FontAwesome';
  @if $fa-append-version {
    src: url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
  } @else {
    src: url('#{$fa-font-path}/fontawesome-webfont.eot');
  }
}
```

Thanks!

**Comment by mkurz** [comment]
+1

**Comment by tagliala** [comment]
I'm going to close this because static strings will be removed in 5.0.0

Ref: #3286
