### ISSUE TITLE
Icon Request: Bower

### ISSUE THREAD

**Issue by haydenbleasel** [FortAwesome/Font-Awesome#3825]
Re: #3822, I think this icon would be really valuable for developers, to go along with ones like [fa-sass](https://github.com/FortAwesome/Font-Awesome/issues/2894) and [fa-less](https://github.com/FortAwesome/Font-Awesome/issues/2567). I find myself wanting it all the time so I usually have to go and hack a rasterised logo apart in Photoshop. Giant Bower bird for good measure:

![fa-bower](http://bower.io/img/bower-logo.png)

**Comment by glnster** [comment]
+1

**Comment by Imaginaerum** [comment]
+1
