### ISSUE TITLE
Icon Request: Grunt [will be available in Font Awesome 5]

### ISSUE THREAD

**Issue by haydenbleasel** [FortAwesome/Font-Awesome#3827]
Re: #3822, I think this icon would be really valuable for developers, to go along with ones like [fa-sass](https://github.com/FortAwesome/Font-Awesome/issues/2894) and [fa-less](https://github.com/FortAwesome/Font-Awesome/issues/2567). I find myself wanting it all the time so I usually have to go and hack a rasterised logo apart in Photoshop. Giant Grunt warthog or whatever for good measure:

![fa-grunt](http://gruntjs.com/img/grunt-logo.png)

**Comment by TMMC** [comment]
+1

**Comment by cameronjonesweb** [comment]
+1

**Comment by koenvanras** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
