### ISSUE TITLE
Icon Request: icon-browser

### ISSUE THREAD

**Issue by MarekZielinski** [FortAwesome/Font-Awesome#3834]
Hi

I would like to request new icon. I really need this for my project. 
![browser-cion50](https://cloud.githubusercontent.com/assets/8051886/3462274/c8f80a30-022b-11e4-942d-b52ed58c59df.png)

![browser-cion](https://cloud.githubusercontent.com/assets/8051886/3462255/99a79886-022b-11e4-93ef-777f2aef864f.png)

Best Regards

**Comment by juancalero** [comment]
+1
