### ISSUE TITLE
fa-pencil-square-o is misaligned

### ISSUE THREAD

**Issue by fplanque** [FortAwesome/Font-Awesome#3846]
pencil-square-o is too high and doesn't properly align (vertically) with the text that comes after it. 

This is visible here:
http://fortawesome.github.io/Font-Awesome/icon/pencil-square-o/

Contrast this with its non "-o" sibling which is properly aligned (vertically):
http://fortawesome.github.io/Font-Awesome/icon/pencil-square/

**Comment by marcucio** [comment]
+1

**Comment by mattchue** [comment]
+1

**Comment by ahjorth** [comment]
Still, please +1
