### ISSUE TITLE
Icon request: icon-user-remove

### ISSUE THREAD

**Issue by desduvauchelle** [FortAwesome/Font-Awesome#3847]
Amazing work with Font Awesome! Thanks! :+1: 
Would be awesome if you could add icons for add/remove users. I'm sure it would be really helpful for the whole community and since it's based on an icon you already have, should be pretty fast :) 

Name: fa-user-remove / fa-user-add
Examples of usage: Add user to your network, invite someone to the site, add a follower, ...and then the reverse for remove...

![screen shot 2014-07-03 at 12 15 55](https://cloud.githubusercontent.com/assets/1172911/3468209/1172599a-029b-11e4-96df-c0fa3a485933.png)

Looking forward to hearing from you.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-plus?style=solid
https://fontawesome.com/icons/user-minus?style=solid
