### ISSUE TITLE
Google Scholar Icon

### ISSUE THREAD

**Issue by perror** [FortAwesome/Font-Awesome#3851]
I think it would be convenient to have a GoogleScholar Icon... It is quite easy to do based on the original google symbol (I had to do mine for my website). And, a lot of academics might need it.

![googlescholar](https://cloud.githubusercontent.com/assets/1612326/3472454/f1f2a18e-02cb-11e4-9f89-1d98c471cade.png)

**Comment by sahraoui17** [comment]
+1
