### ISSUE TITLE
Icon request: icon-java

### ISSUE THREAD

**Issue by marcohu** [FortAwesome/Font-Awesome#386]
Thanks a bunch for your great work! Awesome project!

It would be nice to have a representation for the Java logo, the coffee cup icon as shown below:

http://commons.wikimedia.org/wiki/File:Java_logo_and_wordmark.svg

**Comment by langley-agm** [comment]
+1

**Comment by christianhujer** [comment]
+1

**Comment by akapa** [comment]
+1

**Comment by ab-test** [comment]
+1

**Comment by ab-test** [comment]
+1 for a java icon - Isn't Java one of the most used languages in the world and no icon for it :-(

**Comment by otisg** [comment]
+1!

**Comment by stijnvanbael** [comment]
+1

**Comment by bartbutenaers** [comment]
+1

**Comment by ngaini** [comment]
+1

**Comment by team-core** [comment]
+1

**Comment by Bejasc3D** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-java was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by rkstarnerd** [comment]
+1

**Comment by darwiin** [comment]
Please don't comment with a +1 but use the thumb up on the first comment.

**Comment by Fabryprog** [comment]
+1

**Comment by Sparkenstein** [comment]
year 2018, we have Javascript, python, php icons now, but still no sign of Java

**Comment by s1awa** [comment]
@marcohu 6 years later it finally happened

Font-Awesome 5.0.10
 * New java brand icon
![java](https://user-images.githubusercontent.com/20663500/38591695-8e84298c-3d6a-11e8-8f84-71113c79c336.png)
`<i class="fab fa-java" aria-hidden="true"></i>`

**Comment by robmadole** [comment]
We're working on em!
