### ISSUE TITLE
Icon request: expanded view

### ISSUE THREAD

**Issue by 1eddy87** [FortAwesome/Font-Awesome#3861]
I would like to make a request for a new icon. The icon called expanded view will be used to show various view within a website for example: full text view without pictures, or a picture with text view. 

The color could be the same as all the other icon on the fontawesome site.
The icon could look like this ![screen shot 2014-07-06 at 3 56 43 am](https://cloud.githubusercontent.com/assets/3904952/3487220/c469bd58-046d-11e4-8c97-b94191f8937a.png).

Kind regards

**Comment by sensibleworld** [comment]
We have a lot of new icons in Font Awesome 5 that could work for this. Check them out here: https://fontawesome.com/icons?d=gallery&s=solid

If we're still missing an icon that fist your needs, could you open a new request? Thanks!
