### ISSUE TITLE
More Icon Suggestions: OS/Platforms

### ISSUE THREAD

**Issue by zakbell** [FortAwesome/Font-Awesome#387]
Great project, nice work!

I know you get a ton of these, but here's a few more icon suggestions for a future release:

OS/Platforms:
- Apple (Apple with bite logo)
- Mac OS X (OS X "X")
- Windows (Windows logo silhouette)
- Linux (Penguin logo silhouette)
- Android (Android robot logo)
- iOS ("iOS" logotype)
- Java (Java cup logo)

Also, a few generic ideas:
- Lightbulb
- Grad cap

**Comment by langley-agm** [comment]
+1

**Comment by tagliala** [comment]
:lock:
