### ISSUE TITLE
Icon Request: icon-bufferapp

### ISSUE THREAD

**Issue by phillips-jon** [FortAwesome/Font-Awesome#3873]
It would be great to have a new icon for Buffer App: https://bufferapp.com/

Use case: use this icon alongside other sharing icons like twitter, facebook, etc...

![buffer](https://cloud.githubusercontent.com/assets/2441967/3510884/bf19c048-06aa-11e4-85ef-4a164b5cdf93.png)

**Comment by bobsawyer** [comment]
+1

**Comment by tagliala** [comment]
just found out thanks to @bobsawyer that this is a duplicate of #2110 which has more +1s

Closing here

**Comment by bobsawyer** [comment]
Glad to be of service! :-)
