### ISSUE TITLE
Icon request: icon-wikipedia, icon-wikimedia

### ISSUE THREAD

**Issue by fatmuemoo** [FortAwesome/Font-Awesome#388]
Love the project. I would like suggest adding the Wikimedia and Wikipedia icons. Thanks.

**Comment by kernc** [comment]
:+1:

**Comment by Luntegg** [comment]
+1

**Comment by drewsbrew** [comment]
+1 for the W used in the Wikipedia favicon.

**Comment by shamalroy** [comment]
+1

**Comment by iaincollins** [comment]
:+1:

**Comment by bekroogle** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">

**Comment by xerardoo** [comment]
+1

**Comment by JaredCubilla** [comment]
+1

**Comment by katyhuff** [comment]
+1

**Comment by oriadam** [comment]
+1

**Comment by sba** [comment]
+1

**Comment by NikolasKuJi** [comment]
+1

**Comment by cassidyjames** [comment]
:+1: I've seen this requested a few times, most recently here https://github.com/elementary/mvp/issues/334

**Comment by batisteo** [comment]
:+1:

**Comment by ronaldbradford** [comment]
+1

For Brand Icon
See http://commons.wikimedia.org/wiki/File:Wikipedia-W-bold-in-square.svg for image

**Comment by fabn** [comment]
+1

**Comment by 19kestier** [comment]
+5

**Comment by jarvelov** [comment]
+1

**Comment by user501254** [comment]
+1

**Comment by CRS-ECHO51** [comment]
:+1:

**Comment by thesysem** [comment]
+1

**Comment by michaschwab** [comment]
+1... its been 2.5 years, it shouldnt be that hard?

**Comment by kevinelliott** [comment]
Seriously, and look at all the +1s.

**Comment by MrLockertsen** [comment]
+1

**Comment by fuckinator** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by dzoladz** [comment]
+1

**Comment by oriadam** [comment]
+1

**Comment by lucazpf** [comment]
+1

**Comment by lucks** [comment]
+1 , plz , plz, plz, Do it!

**Comment by mayinx** [comment]
+1

**Comment by blmoore** [comment]
+1

**Comment by dandelea** [comment]
+1

**Comment by runcom** [comment]
+1

**Comment by perminder-klair** [comment]
+1

**Comment by Exey** [comment]
+1 please add wiki

**Comment by levabd** [comment]
+1

**Comment by ApfelUser** [comment]
+1

**Comment by SergeantJack** [comment]
+1...it's been 3 years now :/ Please please please!

**Comment by tagliala** [comment]
@SergeantJack sorry... this icon should be included in 5.0.0 but I don't know any release date.

**Comment by SergeantJack** [comment]
@tagliala That's great to hear! Thanks!

**Comment by oriadam** [comment]
Here's something that may work -- note that letter-spacing should be changed according to font size
http://jsfiddle.net/fLktadyn/6/

**Comment by kernc** [comment]
@oriadam, no. We said we want [the logo](http://en.wikipedia.org/wiki/Logo_of_Wikipedia), not the favicon.

**Comment by SergeantJack** [comment]
@oriadam Unfortunately, as @kernc mentioned, the actual logo itself might be a better fit. It might just be me, but I think the Wikipedia "W" is somewhat ambiguous (it's just a "W", it could mean many things i.e., Wordpress, etc.). But thanks for the effort!

**Comment by zarino** [comment]
+1

**Comment by ErikBjare** [comment]
+1
I'm actually going to use it in-context (no risk of confusion) so I'm going to use @oriadam solution for now, looks great!

**Comment by rbole** [comment]
+1

**Comment by WispProxy** [comment]
+1

**Comment by haslo** [comment]
+1

**Comment by ComedyTomedy** [comment]
+1

**Comment by tchoulihan** [comment]
+1

**Comment by KobaKhit** [comment]
+1

**Comment by jtouza** [comment]
+1

**Comment by jorisroovers** [comment]
+1

**Comment by nvamaheshkumar** [comment]
+1

**Comment by biwin** [comment]
+1

**Comment by teleuko** [comment]
+1

**Comment by davegandy** [comment]
The puzzle logo is far too complex for a 14px icon set. The W however, is not.

**Comment by davegandy** [comment]
Added Wikipedia W logo into 4.4.0-wip branch. Closing.
