### ISSUE TITLE
Icon Request: gun

### ISSUE THREAD

**Issue by ngadelia** [FortAwesome/Font-Awesome#3888]
something like this http://icons.iconarchive.com/icons/visualpharm/icons8-metro-style/512/Military-Gun-icon.png

**Comment by ocsd** [comment]
+1 http://www.iconarchive.com/show/windows-8-icons-by-icons8/Military-Gun-icon.html

**Comment by JeffShaffer** [comment]
+1

**Comment by renatodinhani** [comment]
+1

**Comment by MuhsinunCool** [comment]
+1

**Comment by huntingtown** [comment]
+1

**Comment by fedotyk** [comment]
+1

**Comment by A-David** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by starf** [comment]
+1

**Comment by aj1322001** [comment]
+1

**Comment by Rachine** [comment]
+1

**Comment by siruguri** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by noah** [comment]
+1

**Comment by dorathoto** [comment]
+10

**Comment by Shyzer** [comment]
+1

**Comment by onlinekeystore** [comment]
+1

**Comment by AmazeNose** [comment]
+1

**Comment by atyutrin** [comment]
+1

**Comment by SuperWomble** [comment]
+1

Is there a philosophical/political objection to including basic symbols for weapons in FA? It does seem rather weird that there are so many options for a category like "Gender", and there is a jet fighter icon, but no icons to represent the basic tools used by millions of police, security guards, soldiers around the world, every day. There isn't even Apple's ludicrously politically-correct water-pistol.

Please consider adding a pistol and rifle. Thank you. Let users make their own philosophical/political choices as to how these icons are used.

**Comment by noah** [comment]
> Please consider adding a pistol and rifle. Thank you.

And may your pistols be both polymer- and steel-framed; your rifles AK and AR variants.  Amen.

**Comment by KristopherWagner** [comment]
+1

**Comment by alwye** [comment]
+1 (pistol)

**Comment by another-guy** [comment]
+1

**Comment by Rzeszow** [comment]
+1

**Comment by mika76** [comment]
+1,000,000

Please add this - almost every game has some sort of weapon in it so any site for any game related thing is going to require this to some extent. A gun, rifle, maybe knife or sword - pretty much any weapon related icon - a variety would be useful.

Plus there are so many +1 comments here it's looking a but strange as to why there is no resolution. If you won't add it at least tell us out right.

**Comment by mika76** [comment]
For anyone looking - I found this - http://govicons.io/ - font awesome style icons which include some weapons...

**Comment by robeyl** [comment]
FA5 is out, and still no gun... sad Robey is sad... :(

**Comment by Zyniker13** [comment]
Almost *four* years with no response or progress. Always nice when virtue signalling trumps the end user experience and the usability of a project.

**Comment by huyder** [comment]
+1

**Comment by JosephWeaver** [comment]
+1

**Comment by VirtusB** [comment]
+1

**Comment by JosephWeaver** [comment]
Guess it’s time to stop using Font Awesome. 😎👏🏼

**Comment by VirtusB** [comment]
@JosephWeaver Don't be mean, they probably don't want to give the gang members (who all use Font Awesome) any good ideas. Think about it, that icon could be used to rob someone!

**Comment by tinwe** [comment]
How can this still be an issue? What possibly is the reason to avoid having a simple gun or pistol icon?
We are currently stuck trying to symbolize what content is prohibited from shipping, but font awesome doesn't even have a basic symbol for guns. And since there hasn't even been an official reply on this thread for FIVE years, it makes me wonder how much they really care.

**Comment by JosephWeaver** [comment]
**Hint:** They don't care.

**Comment by danielcongrove** [comment]
+1

**Comment by another-guy** [comment]
@JosephWeaver yes. No response whatsoever for almost 5 years. Font ?Awesome?

**Comment by rbirmann** [comment]
+1

**Comment by iamvinny** [comment]
+1

**Comment by iamvinny** [comment]
I think they're against icons that "stimulate" violence...

**Comment by tomae** [comment]
...and yet there are icons for swords ... and fighter jets

**Comment by siruguri** [comment]
https://www.flaticon.com/free-icons/rifle

**Comment by mr21** [comment]
Here the gun icon on facebook:

![fb-gun-icon](https://user-images.githubusercontent.com/850754/62839783-da47e200-bc8f-11e9-8dd7-2ff819fb9eb1.png)

FontAwesome could do the same, add a toy to `fa-gun` and then takedown this issue...

**Comment by butlermj** [comment]
Need a handgun icon for an enterprise application. How about some kind of answer?

**Comment by VirtusB** [comment]
@butlermj How about you get a designer to make them, since it's for an "enterprise application"?

**Comment by JosephWeaver** [comment]
FontAwesome is no longer relevant anyway. Switched a while ago, because they no longer update anything but fake gender icons and corporate logos. Unsubscribing from this thread. ¯\_(ツ)_/¯

**Comment by mr21** [comment]
Awww there is too much gender icons for you to compute
And aww not enough big gun icons for you right?

:sad_emoji:

**Comment by JosephWeaver** [comment]
Well, there are 52 gender icons and 0 gun icons, by my count.

So, yes, I guess that’s both more than necessary, and not necessarily enough, respectively.

And also, respectfully, I’ve already done “the google” and taken my business elsewhere. I’m sure FA doesn’t need my business anyway.

**Comment by SuperWomble** [comment]
> Awww there is too much gender icons for you to compute
> And aww not enough big gun icons for you right?
> 
> :sad_emoji:
> 
> Take a deep breath, everything is okay, go on google image and write "ak47" normally you should be better XD

Your trolling is not appreciated. This is supposed to be a professional site. Please act like it, and show some tolerance for other people's views on this matter.

**Comment by mr21** [comment]
A professionnal website with people who say "fake genders"?
Give me a break :D

I can feel the **alt-right** in this issue...

And the dude is sadly misinterpreting shapes with genders icon, he probably doesn't understand that the triangle is not a gender lol

**Comment by VirtusB** [comment]
@mr21 Did you just make the best argument for the alt-right? Sure, the alt-right sucks, but it sounds like you're calling everyone who isn't alt-right deranged. Luckily you don't have to be alt-right to know something about biology. And regarding your last point - there will be trianglegender at some point, if there isn't already.

Here is some reading material for you:
Abimegender
Absorgender
Adamasgender- 
Adeptogender
Aerogender
evaisgender
Aesthetgender
videgender
Aethergender
Affectugender
Agender
Agenderfluid
cancegender
Agenderflux
librafluid
Alexigender
Aliusgender
Ambigender
Amaregender- 
Ambonec
Amicagender
Amogender
flirtgender
Amorgender
Androgyne
Anesigender
Angeligender
Angenital
Anogender
Anongender
Antegender
Antigender
ungender
Anxiegender
Anvisgender
apagender
Apagender
lethargender, inersgender 
 anvisgender.
Apconsugender
Apogender
Apollogender
Aporagender
Aptugender
Aquarigender
genderflow.
Archaigender
Arifluid
arigender
Arigender
arifluid
Arithmagender
Argogender
Astergender
Astralgender
Atmosgender
Autigender-
Autogender
Axigender
Batgender
nocturnalgender
Bigender
Bigenderfluid
Biogender
Blizzgender
wintegender
Boggender
swampgender
Bordergender/Borderfluid
Boyflux
Brevigender
Burstgender
spikegender
Cadensgender
Cadogender
Caedogender
Caelgender
Cancegender
agenderfluid
Canisgender
Caprigender
Carmigender
Cassflux
Cassgender
Caveagender
Cavusgender
Cendgender
Cennedgender
Ceterofluid
ceterogender
Ceterogender
Chaosgender
Cheiragender
Circgender
Cloudgender
Cocoongender
Cogitofluid
Cogitogender
Coigender
Collgender
Colorgender
Comgender
Commogender-
Condigender- 
Contigender
Corugender
Cosmicgender- 
Cryptogender
Crystagender
Cyclogender
Daimogender
Deaboy
Delphigender
Demifluid/flux
Demigender
Digigender
Diurnalgender
flowergender
Domgender- 
Drakefluid
Dryagender
Dulcigender
Duragender
Eafluid
enbyfluid
Earthgender
Egender
exgender
Ectogender
Effreu
effrille.
effron
Egogender
(name)gender
Ekragender
Eldrigender
Elegender
Elementgender
Elissogender
Enbyfluid
eafluid
Endogender
femfluid,
mascfluid, nobifluid 
genderfluid, genderflux, horogender
Energender
Entheogender
Entrogender
Equigender
Espigender
Evaisgender
aerogender, locugender.
Exgender
egender.
Exiccogender
Existigender
Expecgender-
pivotgender
Explorogender
Faegender
Fascigender
Faunagender
Fawngender
Felisgender
Femfluid
venufluid
Femgender
femme
Firegender
Fissgender
Flirtgender
amogender
genderamas
Flowergender
diurnalgender
Fluidflux
Foggender
Frostgender
freezegender
Fuzzgender
Gemelgender
Gemigender
Geminigender
Genderale
Genderamas
flirtgender
Genderblank
Genderblur
Gendercosm
gendervoid
Genderdormant
Gendereaux
Genderflora
Genderflight
Genderflow
aquarigender
Genderfluid
Genderflux
Genderfuzz
Gendermaverick
Gendernegative
Gender-Neutral
Genderplasma
Genderpositive
Genderpunk
Genderqueer
Gendersea
Genderstrange
Gendervague
Gendervex
 gyragender
Gendervoid
voidgender
Genderwitched
Gendfleur
Girlflux
Glassgender
Glimragender
Glitchgender
Gossagender
Greengender
Greygender
Gyraboy
Gyragender
gendervex
Gyragirl
Healegender
Heliogender
Hemigender
Horogender
Hydrogender
Hypogender
Illusogender
Impediogender- 
Imperigender
Inersgender
apagender
Intergender
Invisigender
Iragender
Jupitergender
Juxera
Kingender
Kynigender
Lamingender
Leogender
Lethargender
apagender
Leukogender
Levigender
Liberique
Libragender
libramasculine
librafeminine
Librafluid
agenderflux.
Lichtgender- 
Lipsigender
Locugender
evaisgender
Lovegender
Ludogender
Lysigender
Magigender
Maringender
nubilagender
Marfluid
mascfluid
Mascfluid
marfluid
Mascugender
Maverique
Medeigender
Melogender
Mirrorgender
Molligender
Moongender
nocturnalgender
Mosaigender- 
portiogender
Musicgender
Mutaregender
Mutogender
Mystigender
Nanogender
nan0gender
Narkissigender
Necrogender
Nesciogender
Neurogender
Neutrois
Nobifluid
Nocturnalgender
batgender
owlgender
moongender
Non-binary
Novigender
Nubilagender
maringender.
Nullgender
Nyctogender
Obruogender
Offgender
Omnigay
Orbgender
Owlgender
nocturnalgender
Paragender
Pendogender
Perigender
Perogender
Personagender
Perospike
Pictogender- 
Pixelgender
Polygender
Polygenderflux
Portiogender
mosaigender
Praegender
Preciogender
Preterbinary
Primusgender
Privagender
Proxvir
Quivergender
Quoigender
Salugender
Schrodigender
Scorigender
Scorpifluid
Scorpigender
Seagender
Selenogender
monagender
monegender.
Sequigender
Shellgender
Skygender
Spesgender
Spikegender
burstgender
Stargender
Staticgender
Stratogender
Subgender
Subfluid
Surgender
Swampgender
boggender
Sychnogender
Systemfluid
Systemgender
Tachigender
Tangender
Tauragender
Technogender
Telegender
Tempgender
Temporagender
Tenuigender
Tragender
Traumatgender
Trigender
Turbogender
Ungender
antigender
Vaguefluid
Vagueflux
Vaguegender
Vapogender
Vectorgender
Veloxigender
Venngender
Venufluid
femfluid
Verangender
Vestigender
Vibragender
Videgender
aesthetgender
Videogender
Virgegender
Vocigender
Voidfluid
Voidgender
gendervoid
Witchgender
Xenogender
Xirl
Xoy
Xumgender
Zodiacgender

**Comment by mr21** [comment]
Reading is difficult, i understand this with you XD
For an unknown reason you have imagined an "NOT" or a negation somewhere in my comment.

I said i can feel the alt-right here because some guy said "stop gay shit... we want guns"
And now you (VirtusB lol) said that i'm making no-alt-right guy deranged?
Are you assuming no-hetero people (the people which like to be represented with all those "fake" gender icons) are deranged people?

This is such a **dirty** issue, i'm so amused that RANDOMLY it concern guns...

Do you think in a parallel universe all those debate are for the "fork" icon?

**Comment by Zyniker13** [comment]
As this issue is going increasingly off the rails, it would be useful to have someone from the project itself comment (and possibly moderate).

@davegandy @supercodepoet @robmadole @talbs

**Comment by BrianLeishman** [comment]
+1 (2020 bump)

**Comment by mr21** [comment]
There is the raygun now like i predicted it three msg before..
https://fontawesome.com/icons/raygun?style=duotone

So move along, nothing to see anymore here :)

**Comment by placidseven** [comment]
> Reading is difficult, i understand this with you XD
> For an unknown reason you have imagined an "NOT" or a negation somewhere in my comment.
> 
> I said i can feel the alt-right here because somebody is starting to say something close to "stop gay shit... we want guns"
> And now you said that i'm making no-alt-right guys deranged?
> Are you assuming no-hetero people (the people which would like to be represented with all those "fake" gender icons) are deranged people?
> 
> This is such a **dirty** issue, and it concerns guns what's the odd...
> Do you think in a parallel universe all this debate would stand for the "fork" icon?

So this is about your feelings and consigning motives? I don't think it's unreasonable to point out the obvious pandering by fa dev team.

**Comment by robmadole** [comment]
I've blocked the user `mr21` who is not abiding by our [Code of Conduct](https://github.com/FortAwesome/Font-Awesome/blob/master/CODE_OF_CONDUCT.md)

This request is currently #1 on our leaderboard. This is our voting system and it heavily influences what icons we add.

Feel free to poke at us for not adding this yet, for being slow, or for our lack of communication; we can own and be responsible for all of those.

However, disrespecting another human being in this thread will not be tolerated. I trust everyone else here can rally behind that? 🙂

**Comment by cloewen8** [comment]
@ngadelia It appears the example image no longer exists. To make sure we are on the same page, could you describe characteristics this icon would have?

**Comment by butlermj** [comment]
Hello. How about something like this?

https://www.bing.com/images/search?view=detailV2&ccid=jFTE8pRi&id=0D6C3F34B5F0B6CA65914E4B6AB001114CA58CFE&thid=OIP.jFTE8pRiH9crprUVotTtkwAAAA&mediaurl=https%3a%2f%2fwww.iconsdb.com%2ficons%2fpreview%2fblack%2fgun-5-xxl.png&exph=256&expw=256&q=handgun+icon&simid=608048844771888044&selectedIndex=0&ajaxhist=0

**Comment by ddenure** [comment]
+1

**Comment by benbabics** [comment]
+1

**Comment by asianmemeboi** [comment]
Wow it finally is in progress

**Comment by gansky-alexander** [comment]
do you have any updates ?

**Comment by sensibleworld** [comment]
We’re adding this in a batch of work that will be released with Font Awesome 6.

**Comment by sensibleworld** [comment]
This is now available in the latest release of the v6 Alpha for Pro subscribers: https://fontawesome.com/download

**Comment by sensibleworld** [comment]
And here's a direct link: https://fontawesome.com/v6.0/icons/gun?s=solid
