### ISSUE TITLE
New Icon Request: Suits, Ties, Bow Ties

### ISSUE THREAD

**Issue by GMaster479** [FortAwesome/Font-Awesome#3896]
Hi guys. Maybe some more men's fashion icons would be cool. I actually kind of want filled in and outline bow ties for one site I use in particular but I figure if you do that you might as well do more along the same line. Thanks for all your great work.

**Comment by MVcodeartbr** [comment]
could you provide some exemple?

**Comment by aethior** [comment]
- `fa-tie` (#6189)
- `fa-bow-tie` (#4786)

**Comment by tagliala** [comment]
Closing here because of new contributing guidelines and newer duplicates

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
