### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by khoaakt** [FortAwesome/Font-Awesome#3900]
Icon request: browser

**Comment by khoaakt** [comment]
Sorry, i lost my account :P. Something like this:
![1430527551_theworld](https://cloud.githubusercontent.com/assets/6000592/7436208/69626ef6-f075-11e4-9bbc-691060d39efc.png)
![1430527601_world-128](https://cloud.githubusercontent.com/assets/6000592/7436214/7a3b9270-f075-11e4-83de-e91c2efcacbf.png)

**Comment by tagliala** [comment]
globe is already here: http://fontawesome.io/icon/globe/
for a globe-frame, please +1 #2655 

closing here
