### ISSUE TITLE
Icon Request: cents

### ISSUE THREAD

**Issue by jjannetty** [FortAwesome/Font-Awesome#3904]
Hey, I recently was/am in need of a ¢ icon and I love using font-awesome, so I thought I would make a request to see if y'all would be down to add one to the currency section.

**Comment by karthik-rp** [comment]
+1

**Comment by vhenri** [comment]
+ 1

**Comment by tagliala** [comment]
fff

This is a duplicate of #1602, let's use that one

**Comment by harshvardhan-shah** [comment]
can you make "C" look more like  ₿  ?
