### ISSUE TITLE
Icon Request tuenti

### ISSUE THREAD

**Issue by cyrbroker** [FortAwesome/Font-Awesome#3905]
I find this the Spanish social network. that of my staff told me to look
here, but I find nothing. Deputy image url of the social network: https://www.tuenti.com/?m=Login
![tuenti](https://cloud.githubusercontent.com/assets/8163397/3578732/de85d584-0baf-11e4-8a2c-aeb1ad77e6b8.jpg)

**Comment by aethior** [comment]
Tuenti is a Mobile Virtual Network Operator now and the social network will be closed.

New logo:
![logo_negro](https://cloud.githubusercontent.com/assets/1769227/13030975/3c2b1dd2-d2bc-11e5-816e-db3adeeab1e0.jpg)
![t_negro-01](https://cloud.githubusercontent.com/assets/1769227/13030976/3d859c5c-d2bc-11e5-8ec9-8e067fb4c63b.jpg)

**Comment by aethior** [comment]
Tuenti is a Mobile Virtual Network Operator now and the social network is closed.

@tagliala I think you can close here. ;)
