### ISSUE TITLE
FontAwesome TTF/OTF missing symbols in Word for Mac 2011

### ISSUE THREAD

**Issue by nikosantis** [FortAwesome/Font-Awesome#3908]
hi

I need use Font-Awesome (otf) for something in my mac, but not all icons work, for example, the icon "code" using the font, is showing "(", i don't know what is happend.

**Comment by jocojr** [comment]
Is there any update on this?  Its still a bug for many symbols!!

**Comment by tagliala** [comment]
@jocojr sorry, can't help here

**Comment by spoonmuppet** [comment]
+1 for this issue.

**Comment by tagliala** [comment]
please do not +1

**Comment by latech** [comment]
Hey guys. I am having the same issue. I desperately need to use this font to do some mockups in PowerPoint for Mac 2011 and I just can't get it to work. I'll admit I'm no coder, but I have installed and uninstalled this font several times. Until I found this thread, I thought it was just me. 

I will install the font and look for it in the font list in PowerPoint. It's not there. However I can search for the font and select it in the list. Once that's done, I expect the text I selected to change into FA symbols but instead the text just changes slightly (gets sharper and stouter).

If this is a Font Awesome issue, can someone from FA comment?
If it's a Microsoft issue, what are the chances of it getting fixed? (most likely low, so I'd like to see FA come up with a work around for this)

**Comment by tagliala** [comment]
@latech sorry, I can't help

**Comment by robbbush** [comment]
@faxg did you ever find a solution for FontAwesome in Office docs? Thx for tip to confirm in TextEdit and Keynote - that font actually displays correctly - just not in Office 2011

**Comment by sistanoman** [comment]
Having the same issue with a PowerPoint presentation. Mac 2011 on Yosemite. Some characters display fine, others are missing/replaced. :/

I found a work-around, which in all honesty, worked out better than originally planned. I have used the IcoMoon App before for web projects and thought I'd try it again. I created a new set with Font Awesome (and a couple others sets) and created my own custom font. Works great and I have thousands of icons to choose from. Not to mention I can upload my own icon designs and it's free.

**Comment by tagliala** [comment]
@sistanoman thanks for sharing your solution!

**Comment by tagliala** [comment]
This issue should be solved in Office for Mac 2016, as per https://github.com/FortAwesome/Font-Awesome/issues/7205#issuecomment-131164500

Closing here

**Comment by ekkis** [comment]
@sistanoman your solution didn't work for me :( I created a font set with the icomoon app, installed the font but bloody Office just won't show the symbols.  hate office.  such garbage
