### ISSUE TITLE
Icon Request: gantt chart (pertt chart / timeline / roadmap)

### ISSUE THREAD

**Issue by radeksvarz** [FortAwesome/Font-Awesome#3915]
Use case: showing there is a plan / roadmap in the software development / product

related images: https://www.google.cz/search?q=plan&safe=off&es_sm=93&source=lnms&tbm=isch&sa=X&ei=JwXHU6OBL6HNygP4uoCwDg&ved=0CAgQ_AUoAQ&biw=1295&bih=683#q=roadmap+software&safe=off&tbas=0&tbm=isch

Icon task is currently quite similar.

**Comment by natsu90** [comment]
+1
http://cdn.flaticon.com/png/256/31970.png

**Comment by eschreiner** [comment]
+1

**Comment by radeksvarz** [comment]
another one I found for timeline: 
http://cdn.flaticon.com/png/256/1407.png

**Comment by radeksvarz** [comment]
After some discussion in the project management community I propose to split the title into:

1. gantt chart (or project plan)
gant chart is indeed for project planning (de facto symbol to recognise)
http://en.wikipedia.org/wiki/Gantt_chart
good icon draft was provided by natsu90 https://github.com/FortAwesome/Font-Awesome/issues/3915#issuecomment-72991820

2. roadmap 
roadmap has way different meaning - on the more strategical level or for product development, where timeline icon could be more relevant: http://cdn.flaticon.com/png/256/1407.png
visualisation example: https://roadmunk.com/images/features-timeline.png

**Comment by Khrysller** [comment]
I am looking for a way to represent Google Timeline Chart, and could no find it. Maybe, as a suggestion:

![timeline](https://cloud.githubusercontent.com/assets/5774516/6443707/7d350236-c0d7-11e4-9f59-9901d4a27727.png)

@tagliala

**Comment by zhendong590** [comment]
+1

**Comment by vlipman** [comment]
+1 - Khrysller's suggestion would be great...

**Comment by fjanon** [comment]
+1

**Comment by fguillot** [comment]
+1

**Comment by Rvanlaak** [comment]
:+1:  on timeline related icons like the following ones 

![timeline-carre-schema-bouton-arrondi_318-25301](https://cloud.githubusercontent.com/assets/2707563/9680034/29161514-52f4-11e5-8a53-1d2f62a75c97.jpg)
![timeline-list-grid-timeline-icon](https://cloud.githubusercontent.com/assets/2707563/9680035/292eab24-52f4-11e5-85ee-7313cc3f5951.png)
![11-512](https://cloud.githubusercontent.com/assets/2707563/9680036/293302c8-52f4-11e5-8bf7-8647b084c1d1.png)

**Comment by navido** [comment]
+1

**Comment by radeksvarz** [comment]
+1 on this one
![](https://cloud.githubusercontent.com/assets/2707563/9680036/293302c8-52f4-11e5-8bf7-8647b084c1d1.png)

**Comment by mrsideshowjack** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by haylo** [comment]
+1

**Comment by Bukati** [comment]
+1

**Comment by McQuinTrix** [comment]
+1

**Comment by diegopiriz** [comment]
+1

**Comment by Guillotine17** [comment]
+1

**Comment by gabrieleciech** [comment]
+1

**Comment by kostaldavid8** [comment]
+1

**Comment by dandohotaru** [comment]
+1

**Comment by FabricioFeliciano** [comment]
+1
[Like this](https://cdn4.iconfinder.com/data/icons/business-money-icons/32/Board_Chart-512.png)

**Comment by Nighthawk22** [comment]
+1

**Comment by aliencrash** [comment]
+1
any decision on this?

**Comment by aalbagarcia** [comment]
+1

**Comment by verhelsttroy** [comment]
+1

**Comment by jeroen8087** [comment]
+1

**Comment by Szymaniuk** [comment]
+1

**Comment by tabdiggy** [comment]
+1

**Comment by MGouaillier** [comment]
+1

**Comment by cutec-chris** [comment]
+1

**Comment by eldy** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by stiffroy** [comment]
+1

**Comment by DavidMernin** [comment]
+1

**Comment by williamscs** [comment]
+1

**Comment by amoralico** [comment]
+1

**Comment by justlevine** [comment]
+1

**Comment by lisadesouza89** [comment]
+1

**Comment by rohitmarneni** [comment]
+1

**Comment by Khrysller** [comment]
+1 again :/

**Comment by mctunes** [comment]
+1

Five years and still no gantt chart icon? Hilarious! Khrysller's suggestion from 2015 would be perfect:

https://github.com/FortAwesome/Font-Awesome/issues/3915#issuecomment-76731529

**Comment by robotu** [comment]
+1

**Comment by Khrysller** [comment]
2020 and I am still looking for it >)

**Comment by EBKH** [comment]
This would be really really helpful!

**Comment by cutec-chris** [comment]
> 2020 and I am still looking for it >)

Yeah, looks loke the awesome fome-awesome is an 0.01 man project

**Comment by barucAlmaguer** [comment]
+1

**Comment by EBKH** [comment]
+1

**Comment by EBKH** [comment]
Would be really useful!!
Some good suggestion had been made :)

**Comment by sensibleworld** [comment]
Hey folks... there's now a chart-gantt icon in the alpha of Font Awesome 6, along with some other new chart icons.

**Comment by sensibleworld** [comment]
https://fontawesome.com/download

**Comment by fjanon** [comment]
URL please? Because I can't find it. Thanks.

**Comment by sensibleworld** [comment]
It's available as part of our v6 alpha release, which can be accessed by Pro subscribers here: https://fontawesome.com/download
