### ISSUE TITLE
Icon Request: service-call (bell-call desk-bell)

### ISSUE THREAD

**Issue by rida48** [FortAwesome/Font-Awesome#3919]
icon representing request (call) 
![request-512](https://cloud.githubusercontent.com/assets/8190483/3611988/891c67b6-0da3-11e4-83be-a7bef0bd2bd8.png)

**Comment by tuxy** [comment]
+1, fa-service-call

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/concierge-bell?style=solid
