### ISSUE TITLE
Icon Request: globe-frame / globe-frame-30

### ISSUE THREAD

**Issue by Okewood** [FortAwesome/Font-Awesome#3931]
Two framework style globes: one like the attached and one similar but canted onto a 30 degree axis would be good to have as an alternative to the current globe icon.  For my purposes, would be used as a "global" (or "all", or "everything") option, as opposed to "local" or "filtered".
![imgres](https://cloud.githubusercontent.com/assets/4942610/3625602/d8959134-0e6e-11e4-9307-30cdd0f02796.jpg)

**Comment by tagliala** [comment]
No feedback, closing here
