### ISSUE TITLE
Icon Request: Post Letter (snail mail)

### ISSUE THREAD

**Issue by EnigmaJohn** [FortAwesome/Font-Awesome#3939]
I need an icon to represent sending a letter.  The envelope is associated with email.
I think a postage stamp would be best.  Or possibly a London style Royal Mail box.

How often are new icons approved and released and how long does it take?

**Comment by Hozey** [comment]
Since font awesome doesn't have the obvious, I used <span>@#64;</span> for eMail and fa-envelope for snail mail and/or postal code.
