### ISSUE TITLE
Icon Request: icon-onedrive

### ISSUE THREAD

**Issue by Katun** [FortAwesome/Font-Awesome#3942]
That will be awesome if you create some cloud storage icons. Like: One Drive. What do you think guys? I've created a little sketch for the Logo.
![onedrive](https://cloud.githubusercontent.com/assets/8213868/3636965/531d542c-0fec-11e4-8ce9-a531feae0e8d.jpg)

**Comment by TheChen5** [comment]
@tagliala It's a dupe!
This should be closed.
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks
