### ISSUE TITLE
Small fa-reddit is sad

### ISSUE THREAD

**Issue by jankazemier** [FortAwesome/Font-Awesome#3959]
All reddit icons are smileys, except the smallest, which is sad Snoo. I'd rather have the smallest one smiling too, even when he is the smallest..

See: http://fontawesome.io/icon/reddit/

**Comment by davegandy** [comment]
It's tricky because there's a decent bit going on in that logo. I've made it a tad larger in 4.3.0-wip branch and it's about all I can do.

Closing.

**Comment by tagliala** [comment]
now it looks "meh" :neutral_face: :)
