### ISSUE TITLE
Icon Request: icon-FriendFeed

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#3965]
Looking for an Icon for the FriendFeed (http://friendfeed.com) Network. The shortcut icon would make a good fit with the FontAwesome icons. This icon is visible, in the address bar, when you visit the website, but I can't locate it anywhere else. I have found it on several other icon services though.

**Comment by jenlampton** [comment]
Looks like this is now part of blogger? I can't find their old logo anywhere...

**Comment by aethior** [comment]
Hi,

FriendFeed was closed in 2015. ([more info](https://en.wikipedia.org/wiki/FriendFeed))

Regards.

cc/ @tagliala
