### ISSUE TITLE
Icon Request: fa-lari (fa-gel currency)

### ISSUE THREAD

**Issue by Stichoza** [FortAwesome/Font-Awesome#3973]
Hello :yum: Please add **Georgian Lari** to currency icons.

The **ISO 4217** code of Georgian Lari is **GEL**, but the icon name `fa-lari` would be better. I mean _gel_ has other meaning in English.
#### Resources:

[Georgian lari - Wikipedia](http://en.wikipedia.org/wiki/Georgian_lari)
#### Official logo/icon:

![Image from Wikipedia](http://upload.wikimedia.org/wikipedia/commons/2/22/Sign_of_Georgian_Lari_%285%29.png)

**Comment by chacha-shota** [comment]
:thumbsup:

**Comment by Stichoza** [comment]
@davegandy @tagliala In case you haven't got any vector source of this icon, you can get it from [font-larisome](https://github.com/Stichoza/font-larisome) font files.

**Comment by tagliala** [comment]
@Stichoza thanks for sharing

**Comment by MichaelSamteladze** [comment]
:thumbsup:

**Comment by Landish** [comment]
:+1:

**Comment by vdanelia** [comment]
+1

**Comment by vdanelia** [comment]
:+1:

**Comment by Nutsaria** [comment]
+1

**Comment by mjaniko** [comment]
+1

**Comment by salvationws** [comment]
+1

**Comment by sitchi** [comment]
:+1:

**Comment by safareli** [comment]
Now we could just do > 👍 < on actual issue and don't post useless comments.

**Comment by Stichoza** [comment]
Still nothing about this. Even in `v5` 😠

**Comment by Giiorgii** [comment]
Like

**Comment by Giiorgii** [comment]
👍

**Comment by gsiradze** [comment]
![image](https://user-images.githubusercontent.com/6205690/55430334-e06dd980-559e-11e9-97e5-a79f17cd0cd5.png)

**Comment by sitchi** [comment]
👍

**Comment by front-end-jeko** [comment]
<y>

**Comment by front-end-jeko** [comment]
👍

**Comment by Mr-giorgi** [comment]
+1

**Comment by radjke** [comment]
👍

**Comment by MariamTalakhadze** [comment]
👍

**Comment by RK55** [comment]
👍

**Comment by NokaK** [comment]
👍

**Comment by guramijibladze** [comment]
👍

**Comment by nikushaweb** [comment]
👍

**Comment by vdanelia** [comment]
👍

**Comment by salvationws** [comment]
:( why is this still open?

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
