### ISSUE TITLE
Icon Request: fa-doublecheck (fa read)

### ISSUE THREAD

**Issue by ddcovery** [FortAwesome/Font-Awesome#3975]
The WhatsApp double check icon.  It's  the "facto" standard to tell something has been checked/received by the destination. 

I actually use this...:

``` xml
<span class="fa-stack fa-lg text-success">
    <i class="fa fa-check fa-stack-1x" style="margin-left:4px"></i>
    <i class="fa fa-check fa-inverse fa-stack-1x" style="margin-left:-3px;"></i>
    <i class="fa fa-check  fa-stack-1x" style="margin-left:-4px"></i>
</span>
```

**Comment by tuia** [comment]
+1

**Comment by cleydsonjr** [comment]
+1

**Comment by dmsherazi** [comment]
+1

**Comment by dmsherazi** [comment]
Thanks for the workarround but it would be great if we have this icon added to font-awesome...

**Comment by Sufi-Al-Hussaini** [comment]
+1

**Comment by Ferixz** [comment]
+1

**Comment by wmariusso** [comment]
+1

**Comment by carloser** [comment]
+1

**Comment by rogeriomgatto** [comment]
+1

**Comment by garak** [comment]
:+1:

**Comment by yakubbaev** [comment]
+1

**Comment by SukanyaSampathkumar** [comment]
+1

**Comment by prettycode** [comment]
+`

**Comment by huseyinalp** [comment]
+1

**Comment by Parithi** [comment]
+1

**Comment by UlrichRechberg** [comment]
+1

**Comment by bloArribas** [comment]
+50

**Comment by jeff1985** [comment]
+1

**Comment by marcelovsantos** [comment]
+1

**Comment by lpsBetty** [comment]
+1

**Comment by david-vasquez** [comment]
+1

The workaround is good when used as a message, but not working well when using within a button (btn btn-xs) since the button gets bigger and thus not uniform to the other buttons located side by side :(

Could you please let me know if there is a definition about when (milestone) it will be included? You answer will be much appreciated

**Comment by remq** [comment]
+1

**Comment by ferparmur** [comment]
+1

**Comment by adrianoluis** [comment]
+1

**Comment by RafaelLeonhardt** [comment]
+1

**Comment by mauriciocarnieletto** [comment]
+1

**Comment by ddcovery** [comment]
Two years and a month :-)

**Comment by r13-eng** [comment]
Thanks for the workarround but it would be great if we have this icon added to font-awesome... [2]

**Comment by josotoru** [comment]
+1

**Comment by good2best123** [comment]
+1

**Comment by wirabdillah** [comment]
+1

**Comment by janhenk** [comment]
+1

**Comment by valmirjunior** [comment]
+1

**Comment by abou7mied** [comment]
+1

**Comment by encsolutions** [comment]
+1

**Comment by rizorko** [comment]
+1

**Comment by matteogalletti** [comment]
+1

**Comment by flgarrid** [comment]
+1

**Comment by askanhan** [comment]
+01

**Comment by siemya** [comment]
+1

**Comment by letalumil** [comment]
+1

**Comment by Smiley01987** [comment]
+1

**Comment by nmathurbkn** [comment]
not looking good :(

**Comment by Smiley01987** [comment]
+1

**Comment by nmathurbkn** [comment]
but thanks a lot  .. I managed with this

> <span class="fa-stack fa-lg text-success">
>     <i class="fa fa-check fa-stack-1x" style="margin-left:4px"></i>
>     <i class="fa fa-check  fa-stack-1x" style="margin-left:-4px"></i>
> </span>

**Comment by ebosantos** [comment]
+1

**Comment by berkaygure** [comment]
+1

**Comment by ivannugo** [comment]
+1

**Comment by zecompadre** [comment]
+1

**Comment by Sonivaibhav26** [comment]
+1

**Comment by d0x7** [comment]
+1

**Comment by glueball** [comment]
+1

**Comment by 0xc0d3r** [comment]
+1

**Comment by tatsujb** [comment]
+1

**Comment by tatsujb** [comment]
three years... people I think it's time to dislodge font awesome as the norm.

**Comment by ddcovery** [comment]
Hi @tatsujb. One of the problems with this request, is that there is only 23 👍 reactions and about 50 "+1" as a comments.
Other requests have a lot of more positive reactions,  like "icon-discord" #7574 with 474.

In any case, in my opinion, fa-double check (fa-read) should be a must on any app icon set.

**Comment by Frisbeetarian** [comment]
+1

**Comment by etrupja** [comment]
+1

**Comment by Shagoyka** [comment]
+1

**Comment by VlooMan** [comment]
+1 - please also add 👍 on the original request

**Comment by ronlaniado** [comment]
+1

**Comment by EvgenyVetrov** [comment]
+1

**Comment by n0ne** [comment]
+1

**Comment by JimSangwine** [comment]
+1

**Comment by cavalos0086** [comment]
+1

**Comment by juanjoseortizalbornoz** [comment]
I have improved like whatsapp adding color ✌️  
<span class=\"fa-stack fa-lg text-success\">
    <i class=\"fa fa-check fa-stack-1x\" style=\"margin-left:4px;color:#33FFFF\"  title=\"VISTO Y REVISADO\"></i>
    <i class=\"fa fa-check fa-inverse fa-stack-1x\" style=\"margin-left:-3px;color:#33FFFF\" title=\"VISTO Y REVISADO\"></i>
    <i class=\"fa fa-check  fa-stack-1x\" style=\"margin-left:-4px;color:#33FFFF\" title=\"VISTO Y REVISADO\"></i>
</span>
thanks for sharing

**Comment by simongcc** [comment]
+1

**Comment by gabogth** [comment]
+1

**Comment by bobper** [comment]
+10000000000000000000000000000000

**Comment by gnehs** [comment]
+1

**Comment by russtee** [comment]
+1

**Comment by narutoo9x** [comment]
+1

**Comment by dyaa** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/check-double?style=solid
