### ISSUE TITLE
Icon Request: fa-plus-circle-o

### ISSUE THREAD

**Issue by simiid** [FortAwesome/Font-Awesome#3976]
There is -o for square but none for circle.
Black circle / black plus / white background

Thanks

**Comment by tagliala** [comment]
fff...

let's say they are strictly related.

Dup of #2417, no need to +1 that request I will do it

**Comment by leo72** [comment]
+1

**Comment by gaetanhauray** [comment]
+1

**Comment by tagliala** [comment]
Dup of #2417 🔒
