### ISSUE TITLE
Icon Fix: fa-times-circle-o

### ISSUE THREAD

**Issue by simiid** [FortAwesome/Font-Awesome#3978]
fa-times-circle-o looks kinda too bold and not so good

Thanks

**Comment by tagliala** [comment]
Hi, I'm sorting out old issues 😅 

I think this has been fixed:

https://fontawesome.com/v4.7.0/icon/times-circle-o ▶️  https://fontawesome.com/icons/times-circle?style=regular

If the 5.0 version of fa-times-circle does not fit your needs feel free to start a new request
