### ISSUE TITLE
Icon request: icon-office-chair (wheelie chair)

### ISSUE THREAD

**Issue by TKreutzfeld** [FortAwesome/Font-Awesome#3984]
I am building a new website for our shared office space in Copenhagen, Denmark and I am using a WordPress theme that enables your wonderfull icons! 
What I would really love is an icon representing a seat in our office space, either a desk or a chair for instance.

Thank you very much in advance for considering

Best regards 
Tanja Kreutzfeld

**Comment by casman300** [comment]
+1

**Comment by sensibleworld** [comment]
Available now in FA Pro! https://fontawesome.com/icons/chair-office?style=solid
