### ISSUE TITLE
icon-phone

### ISSUE THREAD

**Issue by sanford** [FortAwesome/Font-Awesome#4]
First, thank you, most awesome!

Would love a phone icon like an old style handset:  perhaps something like this? http://www.clker.com/clipart-12243.html

**Comment by shrikantjadhav49** [comment]
Do you have any desk phone icon. I gone through fontawesome icons but not getting any icon. So cn you please help me ASAP.

**Comment by tagliala** [comment]
@shrikantjadhav49 please open a new request as described in our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

If you are in hurry, you should consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
