### ISSUE TITLE
icon request: tasteful death icon

### ISSUE THREAD

**Issue by dmdesimone** [FortAwesome/Font-Awesome#4015]
I apologize if this has already been requested.  We have a need in our medical application for a "tasteful" death icon.  I've seen that a skull-and-crossbones icon has already been requested.  This will not work in our case.  We are looking for something a little more "gentler".  Not sure if anyone out there can think of the the type of icon that would work for this.  We also want to avoid gravestones or christian symbolism in the icon.

**Comment by vishnoor** [comment]
Well I came up with two choices . 1) fa-star-o (to indicate we are all part of stars) OR 2) fa-universal-access (as in when we die we become one with the Universe and thus Universal Access )
