### ISSUE TITLE
Icon Request: Picnic Bench

### ISSUE THREAD

**Issue by RustyIngles** [FortAwesome/Font-Awesome#4019]
I would like to request that a picnic bench/pub garden bench is added as an icon. 

Something like this:

![picnic_bench](https://cloud.githubusercontent.com/assets/403302/3750766/d42b87e6-17f8-11e4-87e3-3b062662dcaa.jpg)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/table-picnic?s=solid
