### ISSUE TITLE
Icon Request: Qzone

### ISSUE THREAD

**Issue by codepiano** [FortAwesome/Font-Awesome#4025]
Qzone (Chinese: QQ空间) is a social networking website, which was created by Tencent in 2005. As of November 2013, it already had 623.3 million users.

[Wiki/Qzone](http://en.wikipedia.org/wiki/Qzone)

![image](https://cloud.githubusercontent.com/assets/2015631/3760214/b9d56e46-1872-11e4-9f34-60ceab030f2f.png)

**Comment by thEdmond** [comment]
+1. Waiting for the qzone icon
