### ISSUE TITLE
Icon Request: icon-bridge

### ISSUE THREAD

**Issue by bhadrajith** [FortAwesome/Font-Awesome#4053]
Hi,
Thank you for the nice work.

I'm building a site for bridge management system, So, i need some icons like 
-->bridge,
-->Construction activities
Please try to include some icons for construction activities (civil engineering) 

Example for a bridge icon:- 
![image](https://cloud.githubusercontent.com/assets/8245816/3790500/1715fdb8-1b08-11e4-8b3a-ef10b1716d55.png)

(image url:- http://www.iconsdownload.net/icons/512/5364-vincent-thomas-bridge-vector.png)

Thank You.

**Comment by ander48** [comment]
+1

**Comment by mandashafer** [comment]
+1   But simpler bridge

**Comment by cmeassociates** [comment]
+1

**Comment by sn0opy** [comment]
+1

**Comment by kirandasika** [comment]
+1

**Comment by jjeroennl** [comment]
+1

**Comment by Wineliva** [comment]
+1

**Comment by timint** [comment]
+1
http://www.iconshock.com/img_vista/IPHONE/transportation/jpg/bridge_icon.jpg

**Comment by jbender0** [comment]
+1

**Comment by geekazoid-at** [comment]
+1

**Comment by sharunspi** [comment]
+1

**Comment by Bernoulli-IT** [comment]
Must have!

**Comment by Sunhat** [comment]
STILL OPEN - Would be great if you guys implemented features the community wants as opposed to make it harder to install and use fontawesome

**Comment by CryptorClub** [comment]
`fas fa-archway` if for someone it can be helpful

Anyway still open

**Comment by lanceplaine** [comment]
+1 Definitely need this one to represent "Bridging assets" in crypto

**Comment by lanceplaine** [comment]
We just commissioned this icon so hopefully it should be added soon :) 🌁  🌉

**Comment by sensibleworld** [comment]
We have a few bridge icons now: https://fontawesome.com/search?q=bridge&s=solid%2Cbrands
