### ISSUE TITLE
Icon Request: icon-sheriff-star

### ISSUE THREAD

**Issue by RemiRodrigues** [FortAwesome/Font-Awesome#4056]
Like a badge of a sherif

https://www.google.fr/search?q=badge+of+a+sheriff&es_sm=91&tbm=isch&tbo=u&source=univ&sa=X&ei=LlffU_-BGOXb0QWDq4HYDQ&ved=0CCQQsAQ&biw=1920&bih=985

Thanks you !

**Comment by kmacris** [comment]
+!

**Comment by thekondrashov** [comment]
+1

**Comment by maszd** [comment]
+1

**Comment by weijyewang** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in version 5 and version 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=sheriff&s=solid
