### ISSUE TITLE
Icon Request: fa-wunderlist

### ISSUE THREAD

**Issue by barsi** [FortAwesome/Font-Awesome#4059]
can be added in brands group.
wunderlist getting popular as a social bookmarking and to-do sharing tool.

more info: https://www.wunderlist.com/
Thanks & Regards.

**Comment by aethior** [comment]
>On December 6, 2019, Microsoft announced that it would shut down Wunderlist on May 6, 2020. After this date, the application would no longer sync but users could still import their content into Microsoft To Do

cc/ @tagliala
