### ISSUE TITLE
Icon Request: fa-candle

### ISSUE THREAD

**Issue by Silver0023** [FortAwesome/Font-Awesome#4065]
![12647](https://cloud.githubusercontent.com/assets/8360081/3807932/992bfb50-1c6f-11e4-9522-ed0a34ed6ff7.png)

Dear Awesome font team, Could you please create this icon for a webshop

**Comment by priyankajanak** [comment]
+1

**Comment by dmlinaric** [comment]
+1

**Comment by anpatell** [comment]
+1

**Comment by jephchristoff** [comment]
+1

**Comment by kanalumaddela** [comment]
+1 and they could just take the candle used on fa-birthday-cake

**Comment by kozzmen** [comment]
**+1**

**Comment by KoMiToRaY** [comment]
+1 ...

**Comment by Anorwyn** [comment]
+1

**Comment by adammoisa** [comment]
+1

**Comment by reniervermaak** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/candle-holder?s=solid
