### ISSUE TITLE
icons for accessibility / disabilities / Impairments

### ISSUE THREAD

**Issue by romainlange** [FortAwesome/Font-Awesome#4068]
Hi, 

the french minister for culture issued images to represent specific accessibilities
http://www.culturecommunication.gouv.fr/Politiques-ministerielles/Developpement-culturel/Culture-et-handicap2/Informations-pratiques/Pictogrammes/Pictogrammes

I think that they are quite universal, more and more efforts are done for accessibility and it would be usefull to have Font-Awesome equivalent.

Thanks!

**Comment by caduvieira** [comment]
+1

**Comment by oriadam** [comment]
+1

**Comment by rinaldo-ferreira** [comment]
+1

**Comment by TerraceMedia** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by tagliala** [comment]
Hi, we added an accessibility category and does include some icons requested here

https://fontawesome.com/icons?d=gallery&c=accessibility&m=free

Feel free to open new requests by filling out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

**Comment by tagliala** [comment]
@romainlange please open a new single request
