### ISSUE TITLE
Icon Request: backround-color

### ISSUE THREAD

**Issue by robertleeplummerjr** [FortAwesome/Font-Awesome#4072]
Will be used in a spreadsheet/text editor.
![background-color](https://cloud.githubusercontent.com/assets/679099/3811934/eea8e34c-1ca4-11e4-9694-78b30610da87.png)

**Comment by aethior** [comment]
Duplicate of #3270.

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks. I wasn't able at that time to find the original request

Duplicate of #3270, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
