### ISSUE TITLE
Icon request: fa-instructor (teacher)

### ISSUE THREAD

**Issue by gunthercox** [FortAwesome/Font-Awesome#4079]
I'm looking for a teacher / instructor icon. This would basically be the same as `fa-male` or `fa-female` only one arm would be crooked and holding a pointer.
Similar to:
![fa-instructor](http://www.toronto.ca/budget2014/ataglance/images/icons/teach_128.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by vdvleon** [comment]
+1

**Comment by valentinacarlone** [comment]
+1

**Comment by QueenMerla** [comment]
+1 this would also work for demonstrations

**Comment by shenlong** [comment]
+1

**Comment by gjb2048** [comment]
+1

**Comment by hendrismit** [comment]
+1

**Comment by cherrador** [comment]
+1...

I tried using stacks but I cannot get any acceptable results, this the best:
![05](https://cloud.githubusercontent.com/assets/12229855/13385874/d267c58a-de73-11e5-8ca2-16a1b4281b09.png)
I stacked tv, minus and user icons. The arm does look good.

**Comment by cherrador** [comment]
The old version of Adobe Presenter is a good start sample. Shortened to the torso will be better. No need for the stick, but if it's there, bonus.
![th](https://cloud.githubusercontent.com/assets/12229855/13386126/fa876478-de76-11e5-8fe1-0e600533086c.jpg)

**Comment by obsidienne** [comment]
+1

**Comment by ralexrdz** [comment]
+1

**Comment by ferjani-khadija** [comment]
+1

**Comment by davidmathlogic** [comment]
+1

**Comment by Crissov** [comment]
Emoji ZWJ sequences (without skin tone modifier or variation selector):

👨‍🏫 U+1F468-200D-1F3EB
👩‍🏫 U+1F469-200D-1F3EB

#222

**Comment by tdak** [comment]
+1

**Comment by anisotton** [comment]
+1

**Comment by AwaisKazi** [comment]
+1

**Comment by kaelifa** [comment]
+1

**Comment by tanvirstreet** [comment]
+1

**Comment by Nadeermalangadan** [comment]
+1

**Comment by stern-shawn** [comment]
+1

**Comment by erikaalonso** [comment]
+1

**Comment by pedanticdev** [comment]
+1

**Comment by OmriAharon** [comment]
+1

**Comment by mizejewski** [comment]
+1

**Comment by radubr** [comment]
+1

**Comment by toddedison** [comment]
+1

**Comment by adminazhar** [comment]
+1

**Comment by Chaitali1223** [comment]
+1

**Comment by saman222** [comment]
+1

**Comment by mizejewski** [comment]
+1

**Comment by agent95** [comment]
+1

**Comment by cboland123** [comment]
+1

**Comment by gilcreque** [comment]
👍

**Comment by AjanthUthaya** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=teacher
