### ISSUE TITLE
Icon Request: bulldozer

### ISSUE THREAD

**Issue by jigarius** [FortAwesome/Font-Awesome#4084]
An icon to go with "Under Construction" stuff. Might come in handy.

**Comment by G-Driver** [comment]
+1

Some examples

1.
<img src="http://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/bulldozer.png">

2.
<img src="https://cdn0.iconfinder.com/data/icons/construction-2/512/dozer.png">

3.
<img src="https://cdn3.iconfinder.com/data/icons/glyph/227/Crane-truck-512.png">

**Comment by ander48** [comment]
+1

**Comment by usernamenotused** [comment]
+1

**Comment by jbonnier** [comment]
+1

**Comment by aspcanada** [comment]
+1

**Comment by vinnyamp** [comment]
+1 it'd be useful or crawling sites

**Comment by dot1q** [comment]
It would be nice to have an icons that has this, or something like a dude shoveling dirt, like the on road signs. I use font awesome icons for a web app that has a page representing when construction work orders come in, and I am currently using something like a map icon.

**Comment by myrmecia** [comment]
+1 for a digger

**Comment by mntwinsfan** [comment]
+1

**Comment by tpeelstand** [comment]
+1

**Comment by tpeelstand** [comment]
So, I made this icon. It would work pretty well as a font-awesome icon. something like fa-construction.

White version (larger):
(https://cloud.githubusercontent.com/assets/9253504/17408721/fc142ba0-5a31-11e6-8f77-53dd550acfdc.png)

Black version (small):
![skidsteer-and-excavator-icon-sm-invert](https://cloud.githubusercontent.com/assets/9253504/17408722/fc15c5c8-5a31-11e6-9a4d-43c849beddfe.png)

**Comment by Sheyk** [comment]
+1

**Comment by schowes** [comment]
+1

**Comment by Tajel** [comment]
+1

**Comment by Astriel** [comment]
+1

**Comment by YlloNieR** [comment]
+1

**Comment by pnjeffries** [comment]
This would be very useful.  As a stop-gap I've made a quick edit of the truck-plow icon, but I'm sure this could be improved upon:

![icon-bulldozer](https://user-images.githubusercontent.com/20382942/71547214-f45f3400-2994-11ea-8f87-f161ace310bd.png)

**Comment by aethior** [comment]
Hi,

The current [fa-snowplow](https://fontawesome.com/icons/snowplow) icon is not also a `bulldozer` icon?
For me [fa-snowplow](https://fontawesome.com/icons/snowplow)  is a `bulldozer` and [fa-truck-snow](https://fontawesome.com/icons/truck-plow) is a `snowplow` (perphaps is a cultural thing).
Maybe is better rename this issue to `excavator (bulldozer)`?

**Comment by aethior** [comment]
Hi,

Is not the current [fa-snowplow](https://fontawesome.com/icons/snowplow) icon also a `bulldozer` icon (continuos track and frontal blade)?
For me [fa-snowplow](https://fontawesome.com/icons/snowplow)  is a `bulldozer` and [fa-truck-snow](https://fontawesome.com/icons/truck-plow) is a `snowplow` (perphaps is a cultural thing).
Maybe is better rename this issue to `excavator (bulldozer)`?

**Comment by aethior** [comment]
@tagliala `construction (category)` and `transportation (category)` labels for this request?

**Comment by manattweb** [comment]
+1 more construction equipment is needed.

**Comment by sensibleworld** [comment]
Added! https://fontawesome.com/icons/bulldozer?f=classic&s=solid
