### ISSUE TITLE
Icon Request: un-trash

### ISSUE THREAD

**Issue by skfriese** [FortAwesome/Font-Awesome#4090]
It would be great to have an "un-trash" icon for use with undelete operations. We have soft-delete scenarios where users will have the ability to bring records back from deletion. This would be the inverse of and similar to the existing "trash" icon - included for comparison against some quick mocks.

![fa-untrash-icon](https://cloud.githubusercontent.com/assets/1682113/3845064/cb878c3c-1e4e-11e4-9427-5b791538fe97.png)

**Comment by mshiltonj** [comment]
+1 also looking for this.

**Comment by rapmue** [comment]
+1 i'd go for restore as alias. and some arrow coming out of the trashcan.

**Comment by moein7tl** [comment]
+1 looking for same thing too.

**Comment by G-Driver** [comment]
+1

**Comment by baranok** [comment]
Would be nice, +1

**Comment by lyhil** [comment]
+1

**Comment by Francismori7** [comment]
+1

**Comment by vikas-b** [comment]
@skfriese Yes right, Thanks for help. Can I get link or css class name for above images.

**Comment by skfriese** [comment]
@vikas-b - To what are you referring to? Do folks typically fork and do the work and issue a PR or offer a link to the commit?

**Comment by Zaanmedia** [comment]
+1

**Comment by My1** [comment]
good Idea.

**Comment by bradlis7** [comment]
I'd like a related "unarchive" icon.

**Comment by mazing** [comment]
+1

**Comment by SamBrishes** [comment]
+1

**Comment by thatguyyoulove** [comment]
+1, I'm partial to the look of that last icon myself.

**Comment by gonguinguen** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by farorm** [comment]
+1

**Comment by mupty** [comment]
+1

**Comment by billybraga** [comment]
+1

**Comment by nickbouton** [comment]
+1

**Comment by MConrotte** [comment]
+1

**Comment by srirampoondichinappa** [comment]
+1

**Comment by mgmoritzdev** [comment]
+1

**Comment by edditor** [comment]
+1

**Comment by TechCanuck** [comment]
+1

**Comment by japgolly** [comment]
Plus One

**Comment by ethmz** [comment]
+1 pls

**Comment by fr0z3nfyr** [comment]
+1

**Comment by AndrewCranston** [comment]
+1

**Comment by omer-sds** [comment]
+1

**Comment by centaure** [comment]
+1

**Comment by ansarisufiyan777** [comment]
+1

**Comment by eternalwaves** [comment]
+1

**Comment by fkranenburg** [comment]
+1

**Comment by jononu** [comment]
+2

**Comment by damonmaneice** [comment]
+1

**Comment by INGCRENGIFO** [comment]
+1

**Comment by mikerockett** [comment]
+1

**Comment by teppokoivula** [comment]
+1

**Comment by adrianbj** [comment]
+1

**Comment by matjazpotocnik** [comment]
+1

**Comment by jacmaes** [comment]
+1

**Comment by redskywebsites** [comment]
+1

**Comment by gregveres** [comment]
+1 but I like this example of undelete much better:
https://www.iconfinder.com/icons/1472894/restore_trash_undelete_icon

**Comment by fxmountain** [comment]
+1

**Comment by fxmountain** [comment]
Works with fa-stack: https://codepen.io/fxmt/pen/vdvdKy

**Comment by horst-n** [comment]
+1

**Comment by AndreaPappi** [comment]
+1

**Comment by yurirnascimento** [comment]
+1

**Comment by lukaslabryszewski** [comment]
+1

**Comment by morgzz** [comment]
+1 for restore

**Comment by sensibleworld** [comment]
We now have a couple of options for this: 
https://fontawesome.com/icons/trash-restore?style=solid
https://fontawesome.com/icons/trash-restore-alt?style=solid

**Comment by sensibleworld** [comment]
@gregveres Thanks for the feedback! I'll bring this up with the team, and we'll certainly consider adjusting this icon, or adding an alternate version.

**Comment by fr0z3nfyr** [comment]
I agree 100% with @gregveres. Thanks for considering the suggestion and reopening the issue (and of course, for putting it back into work/in-progress as promised)

**Comment by sensibleworld** [comment]
Working on the update now! Should be out in our next release.

**Comment by sensibleworld** [comment]
Alrighty then! We've added an alternate version of the "trash undo" with a different arrow.

https://fontawesome.com/icons/trash-undo-alt?style=solid
https://fontawesome.com/icons/trash-undo?style=solid

**Comment by gregveres** [comment]
thank you
