### ISSUE TITLE
Icon Request: icon-marker

### ISSUE THREAD

**Issue by unheardpictures** [FortAwesome/Font-Awesome#4094]
Hi there guys,
first of: i love the work you are doing. You make my life much easier on many projects. So: THANK YOU!

I'd love to have a marker/highlight icon like this: https://cdn1.iconfinder.com/data/icons/streamline-design/60/cell-8-0-480.png 
or this: http://www2.psd100.com/ppp/2013/09/2601/chisel-tip-marker-icon-0926020027.png

I'd need it to highlight certain data or text in large sets of data. Rather then seaching for it and searchin all data it only highlights what is shown on the current screen and helps scanning and finding certain data. So in that sense it is different from the search icon. I though about using the eye though i have been using this on already in another context. 

Love to hear back from you and stay awesome! :)

Love,
Lena

**Comment by tagliala** [comment]
dup of #2095, please +1 that request

closing here
