### ISSUE TITLE
Icon Request: fa-keybase

### ISSUE THREAD

**Issue by Synesso** [FortAwesome/Font-Awesome#4095]
I would like an icon for https://keybase.io/

Thank you.

**Comment by kellengrayfox** [comment]
+1

**Comment by Fale** [comment]
+1

**Comment by p8952** [comment]
+1

**Comment by Mystler** [comment]
+1

**Comment by computerwizjared** [comment]
+1

**Comment by markkuit** [comment]
+1

**Comment by kylekthompson** [comment]
+1

**Comment by RainbowDashDC** [comment]
+1

**Comment by dfkt** [comment]
+1

**Comment by fabianlischka** [comment]
+1

**Comment by kirelagin** [comment]
:+1:

**Comment by JacobRYoung** [comment]
:+1:

**Comment by pklink** [comment]
+1

**Comment by lixiaoyan** [comment]
+1

**Comment by kirelagin** [comment]
I gave it another thought and, well… maybe there is no reason to have this icon… Keybase.io itself uses Font Awesome and, in particular, the use `fa-key` to show the user’s public key in the profile. I feel that `fa-key` is a pretty good fit in this case and right now I use it on my website next to a link to my Keybase profile and it gives visitors a hint that this has something to do with keys. While their logo (strange animal with sunglasses) says nothing to those who see it.

**Comment by JacobRYoung** [comment]
That's definitely a fair assessment, maybe keep this open incase they go through a brand makeover and it can be redone so it's not a strange animal anymore and more recognizable.

**Comment by Synesso** [comment]
As the OP, I agree. I think brand logos are OK when they are widely
recognised (e.g. octocat) but the keybase mole (?) is too obscure. I've
been using fa-key & will happily continue to do so until something better
comes.

**Comment by robbyoconnor** [comment]
+1

**Comment by ryanfittoneclipse** [comment]
+1

**Comment by sebie** [comment]
Sadly, I would have to agree with @kirelagin and @Synesso on the fact that the *current* brand and logo doesn't not fit, that well. And that `fa-key` is a very useble alternative.

:+1: +1 Anyhow.

**Comment by Baker** [comment]
+1

**Comment by daurnimator** [comment]
+1

**Comment by martinbjeldbak** [comment]
+1

**Comment by jatindhankhar** [comment]
+1

**Comment by vszakats** [comment]
+1

**Comment by Sarabveer** [comment]
+1

**Comment by fer** [comment]
+1

**Comment by jczimm** [comment]
+1

**Comment by rohithpr** [comment]
+1

**Comment by nwinant** [comment]
+1

**Comment by Kiloreux** [comment]
Yeah that could be awesome if we could have one +1 .

**Comment by ArgonCode** [comment]
+1

**Comment by chester1000** [comment]
+1

**Comment by kennell** [comment]
+1

**Comment by Sarabveer** [comment]
+1

**Comment by ageis** [comment]
+1

**Comment by altsalt** [comment]
+1

**Comment by prashcr** [comment]
+1

**Comment by farazfazli** [comment]
+1

**Comment by anowlcalledjosh** [comment]
+1, although...

>An update on this: we've begun working on mobile and desktop apps that do some pretty neat stuff, and in a few months when we start shifting to the graphic design / branding aspect of it (which really has to come last), there's a good chance we'll be changing our logo.

>So I'm hesitant now to push for any official social icon for us. What we design will be sensitive to that use case. We'd love for something recognizable to work for font awes.

>— the referenced Keybase issue (June 2015)

**Comment by spickermann** [comment]
+1

**Comment by ThurnisH41ey** [comment]
+1

**Comment by kolobus** [comment]
+1

**Comment by sprybear** [comment]
+1

**Comment by josephwandile** [comment]
+1

**Comment by marcobompani** [comment]
+1

**Comment by joekir** [comment]
+1

**Comment by libeclipse** [comment]
https://fortawesome.github.io/Font-Awesome/icon/key/

is a viable alternative.

**Comment by JaymesKeller** [comment]
Personally, it would be easier to understand if we used the Keybase logo. I can understand the point of keeping it as slim as we can, but if you ask me, going with the logo can keep things well organised.

**Comment by WangQiru** [comment]
+1

**Comment by libeclipse** [comment]
Please use the thumbs up to show agreement. Everyone just got a useless
email with your comment.

**Comment by martyanov** [comment]
When guys? More than two years have passed!

**Comment by anowlcalledjosh** [comment]
@martyanov - please don't ask for ETAs, especially not on threads with as many subscribers as this one. Keybase still haven't released a new logo, and `fa-key` is much more easily recognisable than their current mole(?) - if a new Keybase logo gets made, I'm sure there'll be an icon for it, but there's really no way to have a monochrome icon that looks anything like the current Keybase logo and fits with the rest of the FA icons, and very few people would recognise it anyway.

**Comment by martyanov** [comment]
@anowlcalledjosh - great thanks for the clarifications!

I'm sorry, but the people are subscribed for a reason. If there is no room for discussions then what is the purpose of the issues tracker? Is there a better place where we can get status updates, like the one you have provided?

P.S. `fa-key`, IMO, looks ugly.

**Comment by anowlcalledjosh** [comment]
@martyanov - there's plenty of room for discussion. What there isn't room for, and what people are not subscribed for, is email notifications to over 50 people about the fact that you, along with said 50 other people, would like an icon to be made - it won't make anything happen any faster, especially when [the bottleneck is Keybase][0].

The purpose of the issue tracker is to track ["icon requests, bug reports, or feature requests"][1]. I assume that if any progress is made on the icon, someone'll comment on this issue.

[0]: https://github.com/keybase/keybase-issues/issues/973#issuecomment-108486090
[1]: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by php-require** [comment]
+1

**Comment by sjug** [comment]
+1

**Comment by Sarabveer** [comment]
@sjug 
> Please use the thumbs up to show agreement. Everyone just got a useless
email with your comment.

**Comment by REPTILEHAUS** [comment]
+1

**Comment by spences10** [comment]
:+1: 
Now I have thought about it though @kirelagin is probably right, the [keybase.io](https://keybase.io/) mole is pretty obscure so think I'll just use ```fa-key``` too

**Comment by hilnu** [comment]
+1

**Comment by tonypartridge** [comment]
+1

**Comment by cultivatedops** [comment]
I've created an issue for this in Font Awesome 5 / Pro as well: https://github.com/FortAwesome/Font-Awesome-Pro/issues/203

**Comment by bkimminich** [comment]
+1

**Comment by valaxin** [comment]
+1

**Comment by dougmorin** [comment]
+1

**Comment by AJMaxwell** [comment]
+1

**Comment by LunarTwilight** [comment]
+1

**Comment by junderw** [comment]
The new icon actually looks pretty nice, and would make a good addition to fa

![image](https://user-images.githubusercontent.com/11246316/26965893-d38c510e-4d32-11e7-90f9-c8e7633e9b40.png)

**Comment by oxguy3** [comment]
The new logo is out, and can be found in a vector format over here: https://github.com/keybase/client/blob/master/media/logos/keybase_logo_official.ai

**Comment by junderw** [comment]
https://bitbank.cc/

We've actually gone ahead and implemented the silhouette on our site next to the twitter and facebook social icons.

It definitely looks nice. :-D

Had to make our own svg and use CSS to make it turn green just like the FB and twitter icons.

**Comment by leagueherald** [comment]
+1 please add.... request for over 2 yrs now...

**Comment by macskay** [comment]
+1

**Comment by jaredchu** [comment]
+1

**Comment by Atyansh** [comment]
+1

**Comment by anowlcalledjosh** [comment]
Repeating this, since it's been buried:

Please use the thumbs up to show agreement. Everyone just got a useless
email with your comment.

**Comment by amadeobrands** [comment]
+1 would be awsome if added

**Comment by chrisbergeron** [comment]
Another vote for keybase.io icon.  How hard could it be to add?  There are hundreds of replies in here.

Repeating this, since it's been buried:

Also - Please use the thumbs up to show agreement. Everyone just got a useless
email with your comment.

**Comment by YNedderhoff** [comment]
+1

**Comment by stantyan** [comment]
+1

**Comment by kleinsasserm** [comment]
+1

**Comment by thekeele** [comment]
+1

**Comment by jbddc** [comment]
+1

**Comment by tarpdalton** [comment]
@dabura667 Made a vector graphic of the icon: https://github.com/keybase/keybase-issues/issues/973#issuecomment-307547386
![image](https://user-images.githubusercontent.com/5264856/33144432-d919876a-cf71-11e7-94a4-b5af960fcf03.png)


```svg
<?xml version="1.0" encoding="utf-8"?><svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 71 76.3" style="enable-background:new 0 0 71 76.3;" xml:space="preserve"><style type="text/css">.st0{fill:#999999;}</style><g transform="translate(-241.11756,-377.8123)"><path class="st0" d="M247.8,451.8c-0.6-1.3-1.4-3.1-1.8-4l-0.6-1.7l-2,2.2l-2,2.2 l-0.2-4.2c-0.3-6,0.2-12.2,1.2-16.6c2.3-9.8,9.5-18.7,18.8-23.4l2.1-1l-0.5-1.5c-0.3-0.8-0.6-2.5-0.7-3.6l-0.2-2.1l-2.1-0.2 c-3.2-0.3-4.9-1.2-6-3.5c-0.6-1.2-0.6-1.4-0.4-4.6c0.2-4.2,0.5-5.1,1.8-6.5c1.6-1.8,2.7-2.1,6.7-1.9c2.9,0.2,3.5,0.3,4.8,0.9 c0.8,0.4,1.5,0.8,1.6,0.8c0.1,0,1-1.1,2.1-2.6l1.9-2.7l1.2,0.7c0.7,0.4,1.5,0.9,1.9,1.1l0.7,0.4l-0.6,1.5c-0.3,0.8-0.7,2.2-0.8,2.9 l-0.2,1.4l1.7,0.2c6.1,0.6,10.7,4.3,12.4,9.9c0.5,1.8,0.5,5.3,0,7c-0.5,1.6-0.5,1.7-0.1,1.7c0.7,0,5.4,2.3,7.3,3.5 c3.7,2.4,8,6.6,10.4,10.2c4.5,6.7,6.4,14,5.6,22c-0.4,4.8-1.3,8.6-2.9,12.3l-0.6,1.4l-2.5,0l-2.5,0l1.2-2.4 c1.3-2.6,2.3-6.2,2.8-9.4c0.3-2.2,0.4-8.2,0.1-9.3l-0.2-0.7l-1.3,1.4c-3.2,3.5-7.9,4.5-14.2,2.8c-5.4-1.4-7.6-1.7-12.7-1.7 c-3.9,0-5.2,0.1-7.3,0.6c-5.8,1.3-9.9,3.2-15.6,7.3c-2.1,1.5-3.8,2.7-3.9,2.7c-0.1,0,0.2-1,0.6-2.3c0.4-1.3,1.1-3.4,1.5-4.8 l0.8-2.5l-0.9,0.9c-0.5,0.5-1.9,1.9-3.1,3.2l-2.1,2.3l0.5,1.9c0.6,2.5,2,5.6,3.5,7.9c0.6,1,1.1,1.8,1.1,1.9s-1.2,0.1-2.6,0.1h-2.6 L247.8,451.8L247.8,451.8z M256.6,427.6c4.8-5.1,8.7-9.2,8.8-9.2c0.1,0.1-0.4,1.6-0.9,3.3c-3.3,10.4-4,12.4-3.9,12.5 c0,0,1.2-0.4,2.5-0.9c8.5-3.7,18.4-4.2,28.9-1.4c4.7,1.2,6.5,1.2,8.8,0c1.3-0.7,1.8-1.1,2.4-2.1c1.1-1.7,1.2-4.1,0.5-6.3 c-1.7-4.8-8.3-11-14.5-13.7c-3.2-1.4-3.4-1.4-4.1-0.7l-0.6,0.6l2.6,3.2c1.4,1.7,2.9,3.6,3.1,4.1c0.6,1.2,0.7,3.1,0.1,4.3 c-0.8,1.7-3.2,2.9-5.1,2.5c-0.8-0.2-1.1-0.1-1.9,0.5c-2.2,1.6-4.6,1.2-6.6-1.2c-1.6-1.8-2-2.7-2.1-4.5c0-0.9-0.3-2-0.5-2.4 c-0.3-0.6-0.4-1.3-0.4-2.2l0.1-1.4l-1.3-0.3c-1.8-0.5-3.9-1.5-5.1-2.4c-0.6-0.4-1.1-0.8-1.3-0.8s-1.5,0.6-2.9,1.3 c-9.7,5-16,14.3-17,24.8c-0.1,1-0.2,2.3-0.3,2.8l-0.1,0.9l1.1-1.1C247.4,437.3,251.8,432.7,256.6,427.6L256.6,427.6z M282.5,420.2 c0.9-0.7,1.7-1.3,1.9-1.3c0.1,0,0.4,0.3,0.7,0.7c0.5,0.8,1.4,0.8,1.8,0.1c0.3-0.5,0.3-0.6-5.6-7.8c-3.5-4.3-4.2-5-4.7-5 c-1.2,0.1-0.9,1,1,3.3l1.8,2.2l-1,0.8c-1.1,1-1.2,1.2-0.5,1.8c0.5,0.5,0.6,0.4,1.6-0.3l1.1-0.7l0.7,0.6c0.4,0.3,0.6,0.8,0.6,0.9 c0,0.2-0.8,0.9-1.7,1.7c-0.9,0.7-1.6,1.5-1.6,1.7c0,0.3,0.5,1.1,1.4,2.2C280.3,421.7,280.8,421.5,282.5,420.2L282.5,420.2z  M272.2,406c0.6-1.8,2.6-3.2,4.6-3.2c1.1,0,2.7,0.9,3.8,2.1l1,1.2l0.9-1.1c2.5-2.8,2.8-6.7,0.8-10.1c-1.5-2.5-4.3-4-8.2-4.4 c-2.1-0.2-2.6-0.4-3.7-1.5l-0.8-0.8l-0.4,0.6c-0.8,1.2-2.5,5.1-3,6.6c-0.7,2.3-0.4,5.9,0.5,7.7c0.9,1.7,3.3,4,4,3.7 C271.8,406.9,272,406.5,272.2,406L272.2,406z M263.3,392.4c0.2-0.5,0.7-1.8,1.2-2.8c0.5-1,0.9-2,0.9-2.3c0-0.9-1-1.3-3.7-1.5 c-2.4-0.2-2.6-0.1-3.1,0.4c-0.4,0.4-0.6,0.9-0.6,1.6c0,0.6-0.1,1.7-0.2,2.6c-0.2,2.1,0.1,2.5,2.2,2.8 C263.1,393.4,263,393.4,263.3,392.4z M260.2,390c0-1.7,0.2-1.9,1.6-1.9h1.3v1.4v1.4h-1.4h-1.4V390z M266.5,448.3 c-0.6-0.6-0.8-1-0.8-2c0-1.9,1.1-3,2.9-3c1.7,0,2.9,1.2,2.9,2.9c0,1.8-1.1,2.8-3,2.9C267.5,449.1,267.1,448.9,266.5,448.3 L266.5,448.3z M285.8,448.6c-2.3-1.8-1.1-5.3,1.8-5.3c1.8,0,2.8,1.1,2.9,3c0,1.1-0.1,1.4-0.8,2s-1,0.8-2,0.8 C286.8,449.1,286.2,448.9,285.8,448.6L285.8,448.6z"/></g></svg>
```

@junderw do you have to source for your icon?

**Comment by Ghostboy-287** [comment]
+1

**Comment by junderw** [comment]
@tarpdalton I used that same SVG from dabura667.

**Comment by gunnarbac** [comment]
+1

**Comment by mortenkjarulff** [comment]
+1

**Comment by songgao** [comment]
I was gonna put together a PR, but saw this in [CONTRIBUTING.md](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md):

> At the moment we are not accepting pull requests containing icons

Is that still the case? @davegandy

**Comment by xuv** [comment]
For those interested, the Keybase icon has been added to [this fork](/ForkAwesome/Fork-Awesome).
You can see it in action [here](https://forkawesome.github.io/Fork-Awesome/icon/keybase/)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/keybase
