### ISSUE TITLE
Icon request: fa-fashion or fa-style

### ISSUE THREAD

**Issue by abreusky** [FortAwesome/Font-Awesome#4101]
Hi,

I would like to suggest the inclusion of an icon representing fashion or "style".

I don't know how could it be like :(

Thank you!

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-dress was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by DSwissK** [comment]
+1

**Comment by aethior** [comment]
Hi abreusky,

There is currently a [Clothing + Fashion](https://fontawesome.com/search?c=clothing-fashion) category.

Regards.

cc/ @tagliala
