### ISSUE TITLE
Icon Request : fa-mountain

### ISSUE THREAD

**Issue by mac1qc** [FortAwesome/Font-Awesome#4109]
I actually working on a ski station website and I think a mountain logo would be interesting for people making website on ski station, but on trekking website our anything else about mountain.

exemple : 
![blue-mountain-hi](https://cloud.githubusercontent.com/assets/8006554/3875571/42c01bd2-2153-11e4-9c69-e5abd9f08e92.png)
![stock-vector-mountain-range-154266137](https://cloud.githubusercontent.com/assets/8006554/3875572/42c1921e-2153-11e4-8e07-abc87589317a.jpg)

**Comment by IcedLime** [comment]
+1 but I would rather more simple like this : 
![mountain-512](https://cloud.githubusercontent.com/assets/6083617/5596617/5aa81e3c-9293-11e4-8c64-08e95e683668.png)

**Comment by nce** [comment]
+1

**Comment by andreav** [comment]
+1

**Comment by barbieswimcrew** [comment]
something like this:

![mountain icon](http://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mountain-Icon.svg/128px-Mountain-Icon.svg.png)

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/5451#issue-55215001

**Comment by Web-Helpers** [comment]
+1 barbieswimcrew

**Comment by jkfoto** [comment]
+1

**Comment by JoshuaLewis** [comment]
Would love to see this added to Font Awesome! :-D

**Comment by Tibo-R** [comment]
+1

**Comment by blomdahldaniel** [comment]
+1

**Comment by timburgess** [comment]
++

**Comment by chicobico** [comment]
+1

**Comment by juancolacelli** [comment]
+1

**Comment by thebrightestday** [comment]
+1

**Comment by Daniel0524** [comment]
+1

**Comment by kjdion84** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by austinkurtti** [comment]
+1

**Comment by jakthom** [comment]
+1

**Comment by omfgtora** [comment]
+1

**Comment by densenator** [comment]
+1

**Comment by AzaZPPL** [comment]
+1

**Comment by jlblcc** [comment]
:+1:

**Comment by vlree** [comment]
+1

**Comment by levu42** [comment]
+1

**Comment by rus-ik** [comment]
+1

**Comment by christianmendoza** [comment]
+1

**Comment by jeremyroelfs** [comment]
Both would be awesome. +1 for IcedLime mountain and barbieswimcrew

**Comment by Autophagy** [comment]
+1!

**Comment by Tito1337** [comment]
Well... +1

**Comment by jckb188** [comment]
+1

**Comment by icemullaj** [comment]
+1

**Comment by carlosromanxyz** [comment]
+1

**Comment by Amomo** [comment]
+1

**Comment by WaynePhipps** [comment]
+1

**Comment by derodi** [comment]
+1

**Comment by merabi777** [comment]
+1

**Comment by gabrielwr** [comment]
+1

**Comment by alea12** [comment]
+1

**Comment by arthurbarros** [comment]
+1

**Comment by gfarias** [comment]
+1

**Comment by MarkerDave** [comment]
+1

**Comment by peldax** [comment]
+1

**Comment by f4exb** [comment]
+1

**Comment by Displee** [comment]
+1

**Comment by nikopartanen** [comment]
+1

**Comment by aaronbeaton** [comment]
+1

**Comment by mrwunderbar666** [comment]
+1

**Comment by gregoryalary** [comment]
+1

**Comment by photogsy** [comment]
+1

**Comment by davepe** [comment]
+1

**Comment by lancebendo** [comment]
+1

**Comment by earthcomedy** [comment]
+1

**Comment by MichelMoser** [comment]
+1

**Comment by kurmann** [comment]
+1

**Comment by shaedrich** [comment]
+1

**Comment by webilicious** [comment]
+1

**Comment by Elaniobro** [comment]
+1

**Comment by mikermcneil** [comment]
+1

**Comment by btissot25** [comment]
+1

**Comment by sensibleworld** [comment]
Get your climbing boots on! We've added a mountain to version 5.4 (https://fontawesome.com/icons/mountain?style=solid) along with a pair of them to Pro (https://fontawesome.com/icons/mountains?style=solid).
