### ISSUE TITLE
Icon request: icon-promotion, icon-coupon

### ISSUE THREAD

**Issue by cbfrank** [FortAwesome/Font-Awesome#411]
Thank you!

**Comment by lichtamberg** [comment]
promotion and coupon +1

**Comment by akosgei** [comment]
promotion and coupon +1

**Comment by kalenjordan** [comment]
+1

**Comment by Petru80** [comment]
promotion and coupon +1

**Comment by elmogallen** [comment]
promotion and coupon +1

**Comment by ersefuril** [comment]
+1

**Comment by joslinjaso** [comment]
+1

**Comment by ravishakya** [comment]
+1

**Comment by lichtamberg** [comment]
+1

**Comment by ccvo** [comment]
+1

**Comment by tagliala** [comment]
Hi, I'm going to close this in favor of #2760 or #8692, unless you provide an example which is different from both

Please +1 the proper request

Closing here
