### ISSUE TITLE
Icon Request: fa-law

### ISSUE THREAD

**Issue by katekuratsu** [FortAwesome/Font-Awesome#4111]
As the public web presence for the Federal Judiciary, we work to ensure our site is user-friendly. We are currently redesigning our website, uscourts.gov to enhance the site so it is responsive, accessible, and makes better use of current best practices. As we attempt to incorporate these changes, we've opted to use web fonts and font awesome icons for our icon imaging. We would like to offer font awesome to the rest of the United States Federal Judiciary as a good option for their sites, but find a need for several very important icons which currently don't exist as part of your library. We hope you will consider adding these images. 

Please note: The original vector files of each of these icons were downloaded from Shutterstock. 

![images to add to font awesome](https://cloud.githubusercontent.com/assets/739247/3882052/bb6e72c8-2193-11e4-8200-82bef715b92a.png)

**Comment by OpTicCamo** [comment]
+1 I love the idea
