### ISSUE TITLE
Icon request: fa-dartboard

### ISSUE THREAD

**Issue by alexweissman** [FortAwesome/Font-Awesome#4116]
![dartboard](https://cloud.githubusercontent.com/assets/5004534/3892222/a08cc6ce-2230-11e4-860f-8e04587b42bc.png)

Indicates meeting goals, completed tasks, (im)precision, (in)accuracy, practice, games.  Would be useful in conjunction with https://fortawesome.github.io/Font-Awesome/icon/bullseye/ as a "before and after" pair.

**Comment by aethior** [comment]
Hi @alexweissman,

This icon was added in v5.3.0.
Check https://fontawesome.com/icons/bullseye-arrow

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here.
