### ISSUE TITLE
Icon Request: Microsoft Lync Icon

### ISSUE THREAD

**Issue by retrospct** [FortAwesome/Font-Awesome#4118]
I absolutely love Font Awesome! I use it all the time for personal projects and at work on our intranet pages. Our company like many other enterprise companies use Microsoft products and specifically Lync for communication. I've had to use images instead of the awesome vector icons in places where I needed the Lync icon. I would love if we had this available.

Thank you for your hard work!
![lync trans](https://cloud.githubusercontent.com/assets/1510356/3893965/94811984-223f-11e4-8c11-1f374c88caad.png)

**Comment by sisham** [comment]
+1

**Comment by ValidP** [comment]
+1

**Comment by tagliala** [comment]
is this the same of #2563 ?

**Comment by tagliala** [comment]
Closing here because of [Lync Online is becoming Skype for Business](https://technet.microsoft.com/en-us/library/dn913785.aspx)
