### ISSUE TITLE
Icon request: icon-tripadvisor

### ISSUE THREAD

**Issue by mgkz** [FortAwesome/Font-Awesome#412]
Most hotel websites need a link to their page on TripAdvisor

**Comment by hecerv** [comment]
+1 Hope this can be added soon

**Comment by chefnelone** [comment]
+1. This a must!

**Comment by fealaer** [comment]
+1

**Comment by YankoPetroff** [comment]
+1

**Comment by nathanmarks** [comment]
+1

**Comment by ruvenss** [comment]
:+1:

**Comment by senlin** [comment]
:+1:

**Comment by markwaddle** [comment]
+1

**Comment by TERdesign** [comment]
+1

**Comment by BenSibley** [comment]
+1

**Comment by apokyro** [comment]
:+1:  . Almost 3 years has past but still nothing! :(

**Comment by remino** [comment]
Maybe we need to sign a petition?

https://www.change.org/p/font-awesome-please-add-the-tripadvisor-icon-to-your-font

Or maybe I'm doing this wrong.

2015年1月22日木曜日、apokyro<notifications@github.com>さんは書きました:

> [image: :+1:] . Almost 3 years has past but still nothing! :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/412#issuecomment-71019052>
> .
>


-- 
Rémi

RÉMINO
https://remino.net/

**Comment by tagliala** [comment]
@remino petitions are not needed :)

If you need this icon, please consider a custom build of fontawesome.

You are plenty of options:
https://fonticons.com/ (by Dave)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/
[Fork the repository](https://github.com/FortAwesome/Font-Awesome/fork) and [hack with the .otf](https://github.com/blog/1135-the-making-of-octicons)

**Comment by remino** [comment]
They're not? Aw. And here I was, proud to finally be a human with a cause.

Actually, I have made a custom font with Icomoon using a set of icons from
Font Awesome and some custom icons.

I thought that would settle it until I realised I'll still need those
utility classes (2x, etc.) from Font Awesome, and several icons were lined
up differently in Icomoon than the stock font from Font Awesome.

I'm not certain what would be a clean and reusable way to deal with this,
but this is probably not the topic of this issue here.

>

-- 
Rémi

RÉMINO
https://remino.net/

**Comment by tagliala** [comment]
> I thought that would settle it until I realised I'll still need those
utility classes (2x, etc.) from Font Awesome, and several icons were lined
up differently in Icomoon than the stock font from Font Awesome.

Fontawesome provides .less and .scss versions, so you could bring in the mixins and helpers you need

**Comment by davegandy** [comment]
Fonticons.com should have better alignment, and you'll get all the Font Awesome convenience classes, too. :)

**Comment by remino** [comment]
I ended up using the Sass mixins, as suggested above.

But it looks I'll use Fonticons.com next time.

That said, it's getting to a point there are so many icons, we will
eventually have to pick our own set of icons every time. I've already
started doing that for a few projects, and frankly, I was happy here with
the SVG code someone posted above.

2015年1月23日金曜日、Dave Gandy<notifications@github.com>さんは書きました:

> Fonticons.com should have better alignment, and you'll get all the Font
> Awesome convenience classes, too. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/412#issuecomment-71076247>
> .
>


-- 
Rémi

RÉMINO
https://remino.net/

**Comment by tagliala** [comment]
(I signed the petition, btw)

**Comment by magamelix** [comment]
+1

**Comment by derek90** [comment]
+1

**Comment by Oceanswave** [comment]
+1, this would be a great vector, victor.

**Comment by farazg** [comment]
+1!!

**Comment by ActionScripted** [comment]
+1

The docs say that pull requests for icons aren't being accepted but I've added this icon previously to other font icon libraries and I'd be happy to contribute if it'll be accepted.

**Comment by tagliala** [comment]
@ActionScripted feel free to fork the repository, add the icon, recompile and share here

**Comment by kristoffPotgieter** [comment]
+1

**Comment by tsanren89** [comment]
+1
Definitely want this icon.

**Comment by moneal** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by gaviriar** [comment]
+1

**Comment by krstffr** [comment]
+1

**Comment by michalutko** [comment]
+1

**Comment by hthrnnclrk** [comment]
+1

**Comment by sebvita** [comment]
+1

**Comment by Wanted33** [comment]
Good idea :+1:

**Comment by groupthinklabs** [comment]
+ 1

**Comment by leepettijohn** [comment]
+1

**Comment by Realetive** [comment]
+1

**Comment by aguatye** [comment]
+1

**Comment by stephenvicino** [comment]
+1

**Comment by ann-ie** [comment]
+1

**Comment by jorgejams88** [comment]
+1

**Comment by jorwesflow** [comment]
+1

**Comment by albertmatyi** [comment]
+1

**Comment by Robodashy** [comment]
@tagliala just wondering if there's an update on whether or not this icon will be added to the next release? This thread was started almost 3 years ago with plenty of +1s. Is this incoming or are we better off just doing it ourselves? Also...

+1

**Comment by tagliala** [comment]
@Robodashy this icon is planned for 5.0.0, but I don't know when 5.0.0 will be ready

**Comment by ikoniqoz** [comment]
Many thanks for the news on this.

 

At least we now know it is planned.

**Comment by gatmachine** [comment]
+1

**Comment by coffeeontie** [comment]
+1

**Comment by oMikR0n** [comment]
+1

**Comment by laviku** [comment]
+1

**Comment by jaymz9mm** [comment]
+1

**Comment by calebdel** [comment]
+1

**Comment by nicomaro** [comment]
+1

**Comment by martindefatte** [comment]
+1. I just signed up for an account so I could do that.

**Comment by zandergrin** [comment]
+1 - its coming up to 3 years of requesting this - make it so!

**Comment by davidrsim** [comment]
+1 !

**Comment by naturellecomm** [comment]
+1 !!! Since 2 years ...

**Comment by protasisimone** [comment]
+1

**Comment by ohiawins** [comment]
+1 (million)


I am a web developer in a really awesome marketing team called Liquid Spark. I make sites, emails, etc for ADVENTURE VACATION companies around the globe. Many of our clients rely on TripAdvisor for some of their success. TA reaches 315 million unique monthly visitors yet is never included in themes and sadly it is not included here at FA.

Wondering if you might do all the travelers and hosts in the world a solid and add the TripAdvisor logo to your Brand section.

Muchísimo Gracias
~ohia

**Comment by a9un9hari** [comment]
+1

**Comment by nasospsa** [comment]
+1

**Comment by ki11ua** [comment]
+1

**Comment by MisterRich** [comment]
+1

**Comment by OanaBouraoui** [comment]
+1

**Comment by fredericopdg** [comment]
+1

**Comment by teligoma** [comment]
+1

**Comment by SparrowSquire** [comment]
+1 wow cant believe this is still going!

**Comment by chefnelone** [comment]
Give Icomoon a try. http://stackoverflow.com/questions/11426172/add-custom-icons-to-font-awesome

**Comment by WordPresseur** [comment]
+1

**Comment by briancrocker81** [comment]
+1

**Comment by nilafter** [comment]
+1

**Comment by gsvavarsson** [comment]
+1

**Comment by tehlivi** [comment]
+1

**Comment by alisonschmidty** [comment]
+1

**Comment by JoseFaeti** [comment]
+1, damn!

**Comment by Sanabria** [comment]
+1, for the love of god!

**Comment by tonyedwardspz** [comment]
+1

**Comment by dharward** [comment]
+1

**Comment by vittorio82** [comment]
+1

**Comment by yususs** [comment]
+1

**Comment by venty** [comment]
+1

**Comment by ParadiseCircus** [comment]
+1

**Comment by ElMatella** [comment]
+1

**Comment by rj-45** [comment]
+2

**Comment by mmizwicki** [comment]
+3

**Comment by winemonkey** [comment]
+1

**Comment by danylomotyka** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.0-wip branch. Closing.

**Comment by wesleymacente** [comment]
+1

**Comment by matheusjardimb** [comment]
Isn't it missing the square version of it?

**Comment by tagliala** [comment]
@matheusjardimb please open a new request

**Comment by matheusjardimb** [comment]
@tagliala  #8823 done!
