### ISSUE TITLE
Icon Request: Compare type icons

### ISSUE THREAD

**Issue by sainisatnam52** [FortAwesome/Font-Awesome#4124]
It would be glad to see icon which will  symbolize Compare or Compare Icon.

![download](https://cloud.githubusercontent.com/assets/8435640/3902176/3191c492-22ba-11e4-9020-3f4c76e0bb0a.jpg)
![images 1](https://cloud.githubusercontent.com/assets/8435640/3902177/32d7bdac-22ba-11e4-9a23-4687f897ae3c.jpg)

**Comment by vol7ron** [comment]
What about a venn-diagram for compare-and-contrast?
