### ISSUE TITLE
Icon Request: fa-mushroom and fa-toadstool (2 icons)

### ISSUE THREAD

**Issue by omnidan** [FortAwesome/Font-Awesome#4127]
I think it would be cool to have one as an icon in font awesome. There are icons for leaves, trees, why not fungi?

![mushroom](https://cdn4.iconfinder.com/data/icons/outline-2/64/mushroom-128.png)

**Comment by raysuelzer** [comment]
+1 would use it

**Comment by deltaWhiskey** [comment]
+1

**Comment by meganeggan** [comment]
+1

**Comment by DSwissK** [comment]
+1

**Comment by lithxe** [comment]
+1

**Comment by SdeGeata** [comment]
Bump +1

**Comment by kpull1** [comment]
Yeah fa-mushroom and fa-mushroom-alt with and without dots.
![image](https://user-images.githubusercontent.com/3501026/108254644-90309e00-715b-11eb-863e-4eb0447594eb.png)
Easy to do it in duo-tone too!

**Comment by feralfriend** [comment]
👍 yes, please!

**Comment by eno-yna** [comment]
bumping, made an account just to ask for this.

**Comment by sensibleworld** [comment]
We now have a `mushroom` icon. Would it be helpful to have a version without the dots? https://fontawesome.com/v6.0/icons/mushroom?s=duotone
