### ISSUE TITLE
Icon Request: fa-coffee-bean

### ISSUE THREAD

**Issue by omnidan** [FortAwesome/Font-Awesome#4128]
Additionally to the fa-coffee icon, a coffee bean would be nice.

![coffee bean](https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/015_Coffee_Bean-128.png)

**Comment by corelgott** [comment]
+1

**Comment by clj0020** [comment]
+1

**Comment by luisfrias** [comment]
+1

**Comment by mstr-x** [comment]
+1

**Comment by njaen** [comment]
+1
actually, I really need it rigth now :P

**Comment by skrajnish** [comment]
Even I need this Icon, why is it not available?.

**Comment by Null78** [comment]
how many years does it take ?

**Comment by sensibleworld** [comment]
These are now available in versions 6! https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=coffee&s=solid

<img width="344" alt="Screen Shot 2021-05-27 at 2 02 12 PM" src="https://user-images.githubusercontent.com/529604/119874909-23fccd80-bef4-11eb-83ba-38e8ce3e029c.png">
