### ISSUE TITLE
Icon request: icon-diaspora

### ISSUE THREAD

**Issue by ziege** [FortAwesome/Font-Awesome#414]
I suggest a Diaspora icon as an addition to G+, Twitter and the other networks.

**Comment by sycom** [comment]
:+1:

**Comment by Thor77** [comment]
:+1:

**Comment by alis0nc** [comment]
:+1:

**Comment by davidak** [comment]
+1

**Comment by Thor77** [comment]
:+1:

**Comment by psylok** [comment]
+1

**Comment by xuv** [comment]
:+1:

**Comment by MaxNeuron** [comment]
+1

**Comment by lfzawacki** [comment]
+1

**Comment by thelinuxfr** [comment]
+1

**Comment by thelinuxfr** [comment]
![Diaspora logo](https://wiki.diasporafoundation.org/images/b/b3/Asterisk.png)

More : https://wiki.diasporafoundation.org/Branding

**Comment by numahell** [comment]
:+1:

**Comment by nIQnutn** [comment]
+1

**Comment by Petrouchka** [comment]
+1

**Comment by bertenvdb** [comment]
+1

**Comment by darkroast** [comment]
+1!

**Comment by englbauer** [comment]
+1

**Comment by lupa18** [comment]
hello !! will be great !! 

+1

**Comment by annando** [comment]
:+1:

**Comment by braegel** [comment]
+1 sorry for dublet

**Comment by rysiekpl** [comment]
+1, please!

**Comment by theodotos** [comment]
+1

**Comment by qwertygc** [comment]
:+1:

**Comment by frague59** [comment]
:+1:

**Comment by teromene** [comment]
:+1:

**Comment by davidak** [comment]
Can you please +1 the original Feature Request and not spam everyone with comments here?

**Comment by lupa18** [comment]
Hi @davidak ... where is the "original Feature Request"? 

As I understand is here :smile:

**Comment by davidak** [comment]
I mean the first "post" here: https://github.com/FortAwesome/Font-Awesome/issues/414#issue-6370779

**Comment by jpfox** [comment]
:+1:

**Comment by Flaburgan** [comment]
Yay, want it to!

**Comment by Champi57** [comment]
+1

**Comment by taophp** [comment]
:+1:

**Comment by neriki** [comment]
+1

**Comment by unixfox** [comment]
:+1:

**Comment by UdoKifferbrehl** [comment]
+1

**Comment by logological** [comment]
:+1:

**Comment by vinber** [comment]
+1

**Comment by ro0kie4** [comment]
+1

**Comment by Elm7** [comment]
+1
Thanks !

**Comment by UgoM** [comment]
+1
Thanks !

**Comment by labiloute** [comment]
+1 !

**Comment by MattMattV** [comment]
+1 ! 
Thanks a lot !

**Comment by niconil** [comment]
+1

**Comment by Angristan** [comment]
+1

**Comment by Bakaniko** [comment]
+1, please.

**Comment by tchncs** [comment]
+1 !

**Comment by simplon-davidt** [comment]
+1

**Comment by lupa18** [comment]
4 years and dozens of votes and nothing. This project don't want to collaborate with decentralized networks.. any idea to fix this mess ?

**Comment by Petrouchka** [comment]
Same problem with all icons related to free software.
Should find an alternative or do a fork.
http://fontello.com ?

**Comment by xuv** [comment]
@lupa18 & @Petrouchka I'm thinking about the same thing. Before forking, I think we should do the pull request. For a while, I thought they were not accepting them. But it seems now they accept PR again. So if one of us wants to take the time to do a nice one, then it might solve this problem. If that doesn't work, it will be time then to investigate other measures.

**Comment by lupa18** [comment]
Thanks @xuv ! I think it's good roadmap.

I'm not sure how can do that PR... but I would love this one: https://github.com/FortAwesome/Font-Awesome/issues/414#issuecomment-131236188

And the same apply to GnuSocial #6212 (and others?).

**Comment by xuv** [comment]
@lupa18 Well, let's solve one thing at a time. I'll see if I can do a pull request for the D* logo first.

**Comment by regisburin** [comment]
Hi all.

Thanks to @Petrouchka I discover Fonthello, and I've found a webfont with an icon "Asterisk" wich can be used for a D* icon.

Here: https://github.com/aristath/elusive-iconfont

Project seems to be dead (no commit for 1 year, web site is dead), and there's not enough icons to fit everything I want, but I keep it in my bookmarks...

**Comment by xuv** [comment]
@regisburin There is also an [asterisk](http://fontawesome.io/icon/asterisk/) in fontawesome that could be used temporarly as a D* icon.

**Comment by Petrouchka** [comment]
No, asterisk and diapora starts don't have the same number of branches.

**Comment by regisburin** [comment]
+1 @Petrouchka

FontAwesome asterisk has 6 branches, D* one has five (as keyboards one, as any asterisk in sans-serif fonts).

Anyway, i use the FA one in a current project, waiting for another solution.

**Comment by darkroast** [comment]
@regisburin  I'm using this as a workaround:
```
.icon-diaspora::before {
	content: "*";
	font-family: 'Roboto', 'Helvetica', 'Arial', sans-serif;
	font-weight: bold;
}
```

+ some extra styling for size and positioning, so it matches the FA social media icons.

Makes it appear good for most users. But I would prefer it if I could use FA, like for the other icons.

**Comment by Elm7** [comment]
+1
I would like to find in font awsome the diaspora icon too.

**Comment by regisburin** [comment]
@darkroast Thx!

**Comment by juliangilbey** [comment]
And the icon should be called diaspora-square, to make it fit with the other social media icons.

**Comment by ROYALBEFF** [comment]
+1

**Comment by Petrouchka** [comment]
They made it !
https://forkawesome.github.io/Fork-Awesome/

**Comment by talbs** [comment]
Added in version 5.6.0 - https://fontawesome.com/icons/diaspora! 😄
