### ISSUE TITLE
Compatibility Mode gets triggered in IE8

### ISSUE THREAD

**Issue by mstorus** [FortAwesome/Font-Awesome#4144]
This is a tough issue to reproduce consistently, but FontAwesome will often cause IE8 to fall into Compatibility Mode.

I can reproduce by visiting http://fortawesome.github.io/Font-Awesome/icons/ in IE8 and then hard-refreshing the page. Sometimes clicking on a font and then hitting the back button will trigger it too.

I have also seen this IE8 compatibility mode issue with a custom font that is also using the Unicode Private Use Area (PUA), so I suspect it might have something to do with the unicode mapping of the glyphs.

Here are a couple articles that discuss the issue that might be useful. 
http://adactio.com/journal/6555/
http://www.clockwork.net/blog/2013/10/08/657/how_to_avoid_forced_compatibility_mode_in_ie8_and_keep_your_custom_fonts

However, I'm not convinced that the Latin range fix will work, because in my testing with a custom font, it didn't solve the issue for me.

**Comment by simon-online** [comment]
The proposed solution for this on the Troubleshooting page didn't fix the issue for me with FA v4.4.

Here's a solution I've posted on SO which completely fixes this issue for me:
http://stackoverflow.com/a/33162245/4387229

**Comment by mstorus** [comment]
The root of the problem seemed to be the use of the PUA plane in IE8.
The only solutions that always work for me are to choose a different unicode range to assign the glyphs to.
I wrote this answer http://stackoverflow.com/a/29441642/598093
After a lot of experimentation, I found that the Low Surrogates Range appears to work without issues in IE8.
