### ISSUE TITLE
Icon request: fa-restaurant-chair/seat

### ISSUE THREAD

**Issue by jaaksarv** [FortAwesome/Font-Awesome#4150]
I'm using Font Awesome for Restaurant Point-of-Sale System (http://speedpos.com). I missing an icon to use for restaurant seats/chairs.
Few ideas how it should look like: 
http://www.posios.com/wp-content/uploads/2013/04/posios-icon-customizable-floor-plan.jpg
https://d13yacurqjgara.cloudfront.net/users/17115/screenshots/1401290/chair_1x.png
http://cdn.vectorstock.com/i/composite/44,33/chair-icons-vector-794433.jpg
https://cdn1.iconfinder.com/data/icons/kitchen-furniture-and-accessories/256/table-512.png
Choose the one that best fits Font Awesome style. Thank you:)

**Comment by ypawany** [comment]
+1

**Comment by eberkund** [comment]
+1

**Comment by ashikcse20** [comment]
+1
