### ISSUE TITLE
Icon Request: fa-monkey

### ISSUE THREAD

**Issue by Macsch15** [FortAwesome/Font-Awesome#4158]
![monkey-1-hi](https://cloud.githubusercontent.com/assets/1592053/3938838/f5e39676-24be-11e4-8ae1-1a1681ac70f4.png)

Thanks.

**Comment by lepinay** [comment]
+1

**Comment by sycom** [comment]
+1

**Comment by natizlp** [comment]
+1

**Comment by sleepy-monkey** [comment]
+1

**Comment by Beej126** [comment]
+1

**Comment by sensibleworld** [comment]
A monkey is now available in Font Awesome Pro: https://fontawesome.com/icons/monkey?style=solid
