### ISSUE TITLE
 Icon Request: fa-bintray

### ISSUE THREAD

**Issue by jbaruch** [FortAwesome/Font-Awesome#4160]
![Bintray Logo](https://bintray.com/static/ihrcJqAnsPwTxfcfcHH2VHMjCPR7qohVFNoc3X0YaE3.gif)
Thanks!

**Comment by budjb** [comment]
Bintray would certainly be nice!

**Comment by char16t** [comment]
### What can it be used for?

Link to bintray profile

### Example image (optional)

![OeT5g-YC_400x400](https://user-images.githubusercontent.com/5310476/56275352-39924d00-6109-11e9-8978-a0da9a114d63.jpg)

Source: https://twitter.com/bintray

### Comment

Probably tag "brand icons" should be changed to "brand icon"

**Comment by aethior** [comment]
>On May 1, 2021, the sunset will impact all existing Bintray users. Bintray users will be blocked and will no longer be able to use the Bintray service. This includes existing software distribution, account administrative access, UI access, and the REST API. ([more info](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/))

cc/ @tagliala
