### ISSUE TITLE
Icon Request: icon-cow

### ISSUE THREAD

**Issue by philippspeck** [FortAwesome/Font-Awesome#4166]
I request an icon pictureing a cow. I want to use it as an indicator for recipes with or without meat.

That would be great! :)

**Comment by JarnoP** [comment]
+1

**Comment by dynamind** [comment]
+1 (for dairy/beef business)

**Comment by G-Driver** [comment]
+1

**Comment by EngelsR** [comment]
+1

**Comment by ojacquemart** [comment]
+1

**Comment by Krevo** [comment]
+1

**Comment by VincentVARESANO** [comment]
+1 :+1:  

something like this :

![noun_67741_cc](https://cloud.githubusercontent.com/assets/18234791/15062450/7517b62c-1340-11e6-861f-db56b10e04bc.png)

**Comment by jennyanthony** [comment]
+1

**Comment by johnnyshields** [comment]
This is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by marcelomarziotte** [comment]
Good Job!!

**Comment by saniaja** [comment]
+1

**Comment by Crissov** [comment]
- 🐮 [U+1F42E](http://emojipedia.org/cow-face/) Cow Face / Cattle / Beef
- 🐄 [U+1F404](http://emojipedia.org/cow/) Cow 
- 🐂 [U+1F402](http://emojipedia.org/ox/) Ox / Bull → #1122
- 🐃 [U+1F403](http://emojipedia.org/water-buffalo/) Aurox / Water Buffalo
- 🍖 [U+1F356](http://emojipedia.org/meat-on-bone/) Meat Unicode emoji #222
- 🍗 [U+1F357](http://emojipedia.org/poultry-leg/) Poultry
- &#x1f969; [U+1F969](http://emojipedia.org/cut-of-meat/) Meat / Steak / Chop, probably in [Unicode 10.0](http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f969)

**Comment by VincentVARESANO** [comment]
You're right Crissov, I missed this.

But the problem with Unicode is the the lack of consistency between each platform.

Something are "unreadable" when too little, some are just ugly, some don't meet the constrast ratio of your interface (for accessibility concerns), .....

So I +1 and -1 at same time ! 🐮

Thanks anyway.

**Comment by Crissov** [comment]
Oh, I failed to mention #222 in my comment. If a cow was added to FA, it should also be available as one of the code points listed above, not just in PUA.

**Comment by Wingo5315** [comment]
+1

**Comment by TrinasaurusRex** [comment]
+1

**Comment by moritzgloeckl** [comment]
+1

**Comment by sensibleworld** [comment]
Moooooo! A cow just found it's way into Font Awesome Pro: https://fontawesome.com/icons/cow?style=solid
