### ISSUE TITLE
Icon request: thinner arrows

### ISSUE THREAD

**Issue by tbba** [FortAwesome/Font-Awesome#4173]
the arrows are not elegant if used for links, i.m.h.o. 

Thinner arrows (shape of arrows, thickness of longarrows) would be very appreciated.

**Comment by elijahmurray** [comment]
+1 But understand the limitations. Possible to have more angular arrows that aren't as rounded?

**Comment by sensibleworld** [comment]
We now have a lot more options for arrows, including thinner variants in our alternate styles: https://fontawesome.com/v6.0/icons?c=arrows
