### ISSUE TITLE
Icon Request: fa-engine (Check Engine Light)

### ISSUE THREAD

**Issue by jwawi** [FortAwesome/Font-Awesome#4175]
A "Check Engine Light" icon would be super helpful. Working on an automotive app where problems could be indicated w/ a "Check Engine Light". 

More automotive icons in general would be super helpful. I've seen a lot of automotive icon sets available as psd's, svg's, etc, but icon font sets I've found only include a handful of auto icons - usually a car, tachometer, truck and that's about it.

**Comment by josespinal** [comment]
+1

**Comment by siNSTR** [comment]
+1

**Comment by Fritch94** [comment]
+1

**Comment by rschief** [comment]
Could use fa-engine Icon request:fa-engine #8802 to represent a generator as well. Thanks.

**Comment by ugniuslt** [comment]
+1

**Comment by jeekwong** [comment]
+1

**Comment by burgerautomotive** [comment]
+1

**Comment by lazosweb** [comment]
+1

**Comment by schowes** [comment]
+1 - an engine would be very helpful.

**Comment by Indepent** [comment]
+1

**Comment by yovantichrist** [comment]
+1

**Comment by xmuskrat** [comment]
![image](https://user-images.githubusercontent.com/59917/57978432-be9bab00-79c2-11e9-98ef-134407438f5d.png)

**Comment by danielcongrove** [comment]
+1

**Comment by IrishGitty** [comment]
+1

**Comment by smebberson** [comment]
+1, an engine icon would be great.

**Comment by austintraver** [comment]
+1, especially with the new icons released for technology, let's see some love for automotive tech

**Comment by marceloverdijk** [comment]
+1

**Comment by sensibleworld** [comment]
Hey folks! This is now available as part of the alpha release of Font Awesome 6: https://fontawesome.com/download
