### ISSUE TITLE
a separator is needed 

### ISSUE THREAD

**Issue by dieulinh** [FortAwesome/Font-Awesome#4185]
It would be great if we have a separator in FA. 
http://m.img.brothersoft.com/android/23/23a3679b4a0047b9ff2311aff0bd1416_icon.png

**Comment by dieulinh** [comment]
sorry for the very long time not read your reply,
it for separating between some icons, in toolbar both horizontal and vertical

**Comment by sensibleworld** [comment]
This could work: https://fontawesome.com/v6.0/icons/pipe?s=solid or this: https://fontawesome.com/v6.0/icons/horizontal-rule?s=solid
