### ISSUE TITLE
Icon request: vehicles

### ISSUE THREAD

**Issue by lucasbento** [FortAwesome/Font-Awesome#4187]
I'm currently working on a project which uses Font-Awesome Icons on Google Maps as markers, It would be awesome if we could extend Font-Awesome's vehicles icons.

Examples:
http://image.shutterstock.com/display_pic_with_logo/878521/129773828/stock-vector-heavy-duty-machines-gray-yellow-icon-set-129773828.jpg
http://image.shutterstock.com/display_pic_with_logo/1097510/148386566/stock-vector-minimal-transportation-vector-icons-148386566.jpg

Thanks!

**Comment by tagliala** [comment]
We have a vehicles category

https://fontawesome.com/icons?d=gallery&c=vehicles&m=free

If you want to request a specific vehicle, please open a new request making sure to [search for existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before

Closing here
