### ISSUE TITLE
Icon Request: some food/drink icons

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4199]
It would be nice if we had some food/drink icons, like:

Hamburger
Coke/Cola
Coffee
Apple
Banana
Tomato
Croissant
Sanwich
Hotdog
Cheese
Cocktail
Beer with cream
Chicken wing icon
Fork
Knife
Spoon
Carrot
Pizza cut
Meat
Donut
Fish
Crab

Some examples you can find here: http://image.shutterstock.com/display_pic_with_logo/339688/339688,1267910177,2/stock-vector--food-drink-signs-vector-48093202.jpg

**Comment by johnnyshields** [comment]
Some of these are available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by tagliala** [comment]
@johnnyshields thanks for sharing

**Comment by johnnyshields** [comment]
No problem. I'm fine if FontAwesome wants to take any of my icon designs by the way.
