### ISSUE TITLE
Icon Request: updated QR code

### ISSUE THREAD

**Issue by likdaboo** [FortAwesome/Font-Awesome#4200]
my website uses nice looking icons, font awesome's... i really want to put a qr code on but the one available doesn't look like a qr code :/

![temp](https://cloud.githubusercontent.com/assets/8523391/4010969/cbab3398-29fd-11e4-9bda-75cda2a303a4.jpg)

**Comment by tagliala** [comment]
Still an issue, but I still think that the simplified QR code makes sense at 16px
