### ISSUE TITLE
W3C validation

### ISSUE THREAD

**Issue by Trudill** [FortAwesome/Font-Awesome#4207]
Hy, on the latest version (font-awesome-4.1.0), I noticed there are mistakes on http://jigsaw.w3.org in the css of font-awesome.min.css

Have a nice day and thanck you for this amazing work !

**Comment by cykerway** [comment]
I think the problem also appears in recent version 4.5.0. To name a few:

    4 	.fa-rotate-90 	attempt to find a semi-colon before the property name. add it
    4 	.fa-rotate-90 	Property progid doesn't exist : DXImageTransform
    4 	.fa-rotate-90 	Parse Error DXImageTransform.Microsoft.BasicImage(rotation=1); 

These are some of the errors shown in W3C CSS validation.

**Comment by tagliala** [comment]
@cykerway since we are still supporting IE8 we cannot remove the offending lines. If you don't need IE8 support feel free to customize css and remove those `filter` properties

**Comment by cykerway** [comment]
Any hope you provide a base template and let users choose the toppings? My limited knowledge about CSS is that browser-specific settings are usually additive to the W3C standard and shouldn't affect its core functionality if removed.
