### ISSUE TITLE
Icon Request: ello

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4208]
I think that the icon for [ello.co](http://ello.co) would be a useful addition, and not be incredibly complicated - it's only a curved line in a circle really.

Here's their logo:
![aikawa_grabs 2014-08-23 at 17 37 00](https://cloud.githubusercontent.com/assets/4227040/4021156/baa77ac0-2ae3-11e4-90cc-09a059364393.png)

**Comment by moebis** [comment]
+1

**Comment by beamju** [comment]
+1

**Comment by jeditransistor** [comment]
+1

**Comment by RossWright** [comment]
+1

**Comment by nilshg** [comment]
+1

**Comment by aiwass666** [comment]
+1

**Comment by cacheflowe** [comment]
+1 :raised_hands:

**Comment by cacheflowe** [comment]
Ello logo in svg can be found here: https://ello.co/downloads/Ello.Logos.Package.zip

**Comment by larquin** [comment]
+1

**Comment by NICKVALENTINO** [comment]
Almost 6 months worth of "+1" replies without even an acknowledgement from.  About time to give up.

@cacheflowe Thanks

**Comment by jayzes** [comment]
:+1:

**Comment by jejacks0n** [comment]
:+1:

**Comment by the-oem** [comment]
:+1:

**Comment by javierodom** [comment]
+1

**Comment by nedpals** [comment]
+1

**Comment by wwccrecords** [comment]
I think we all need a 'smile' like Ello within our on-line projects, don't we?

**Comment by danielyijyun** [comment]
+1

**Comment by nicroto** [comment]
+1

**Comment by IndiAsh** [comment]
+1

**Comment by sebie** [comment]
Yup :+1:.

**Comment by nedpals** [comment]
Please for Font Awesome v5 +1!

**Comment by gillesvaneeden** [comment]
+1

**Comment by AngusMeek** [comment]
+1

**Comment by AngusMeek** [comment]
+1

**Comment by JRCDyer** [comment]
+1 :grin:

**Comment by MrDanielBell** [comment]
+1

**Comment by MrDanielBell** [comment]
Is this the best we can do??

fa-chevron-circle-down

**Comment by nedpals** [comment]
50th comment and make it part of v5!

**Comment by MrDanielBell** [comment]
Email me for the Fontello files.

Using it on www.WebSight.co along side the usual Fontawesome social media.

**Comment by alibabzo** [comment]
I think this is a good idea. Please can you add? Thanks.

**Comment by LilaVert** [comment]
+1

**Comment by damianfok** [comment]
+1

**Comment by Runfromrobots** [comment]
+1

**Comment by qvadrato** [comment]
+1

**Comment by robotrick** [comment]
+1

**Comment by SMARoovers** [comment]
+1

**Comment by erikaalonso** [comment]
+1

**Comment by Azenha** [comment]
+1

**Comment by jayaregalinada** [comment]
+1

**Comment by fooness** [comment]
+1

**Comment by GGFM** [comment]
+1

**Comment by casman300** [comment]
+1

**Comment by wetzel** [comment]
+1

**Comment by AlexHamstra** [comment]
+1

**Comment by zimtimgetriebe** [comment]
There is quite a need for this.
+1

**Comment by mkonia** [comment]
It seems that they are not listening to us?!
Please 
![adore](https://cloud.githubusercontent.com/assets/15304151/10713033/9f8f50bc-7aad-11e5-8382-ad4b48af8109.gif)

**Comment by MrDanielBell** [comment]
Fontello files

**Comment by mkonia** [comment]
Thanks for the hint. I suppose you are talking about [Fontello - icon fonts generator](http://fontello.com)
Never heard of this Web site bevor. However, no idea how this service can be used to create an Ello icon font.

**Comment by MrDanielBell** [comment]
I have the files available. Email me john.mrdaniel.bell@googlemail.com

www.Websight.co is an example of usage.

**Comment by ericsozone** [comment]
+1

**Comment by RamChilla** [comment]
+1

**Comment by caseydoran** [comment]
@tagliala are you still not accepting new icons? we'd love to help get the Ello logo in there!

**Comment by caseydoran** [comment]
@tagliala any thoughts?

**Comment by jayzes** [comment]
It's obviously not the same thing as being a native Font Awesome icon, but in case anyone on this thread is looking for another way to get an Ello logo in place for a badge, we just put together an SVG button widget that might be helpful: https://ello.co/wtf/resources/ello-button/

**Comment by ericsozone** [comment]
Hey that is awesome @jayzes! Thank you and the ello staff for working hard on this community.

**Comment by ericsozone** [comment]
@jayzes, is there a way to get this iframe / image combo to go smaller? Was trying it on my tumblr (eric-dyer.tumblr.com) and am only able to resize the iframe, cropping the ello icon.

**Comment by caseydoran** [comment]
@ericsozone at the moment you can choose 18x18, 24x24, or 40x40 right underneath where you enter your username. That will also update the iframe size to something appropriate for the button size.  cc/ @jayzes

**Comment by ericsozone** [comment]
@caseydoran I see that, which is awesome! It doesn't fix my particular issue, but hopefully there will be a lot of people that can use this until a native Font Awesome icon is added.

I guess the current way around this for me would be to host my own icon that's smaller than the one hosted by Ello. I guess also another fix would be to make the current icons I have slightly larger.

**Comment by caseydoran** [comment]
@ericsozone yeah, we didn't make it fully editable as we'd have issues is someone made a 1mmX1mm version out of the svg :) 

Here's a good source for logo files: https://ello.co/wtf/resources/logos/

**Comment by ericsozone** [comment]
Thanks @caseydoran! Keep making Ello awesome.

**Comment by MBybee** [comment]
I see the last nag was Feb 10 - so here's another one. Please add ello! :+1:

**Comment by sublines** [comment]
+1

**Comment by luisfavila** [comment]
+1

**Comment by bolgerandbattle** [comment]
+1
Ello just launched their own social button, so it would be nice to get the icon included in FA.

**Comment by markgelband** [comment]
+1 

Feels as though adding the Ello logo in FA is long overdue!

**Comment by steam** [comment]
👍

**Comment by caseydoran** [comment]
+1

**Comment by ailadi** [comment]
+1

**Comment by jasonhibbs** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by sandraslab** [comment]
+1

**Comment by amazingBastard** [comment]
+1

**Comment by davisonio** [comment]
GitHub now has [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) so please add your +1 reactions to the top post so we all don't have to be notified :)

**Comment by nowag** [comment]
We as creators often use [Ello](ello.co) as a social network. I wanted to show in my footer that I am also on Ello but unfortunately there is no such icon for Ello.

Here is the Ello Icon as a *.png file:
![ellomark svgbox](https://cloud.githubusercontent.com/assets/6610554/17642913/a22395c6-61ad-11e6-9c75-e0a1ce1bd339.png)

Because the logo above is a *.png file I will also attach the *.svg file. But because you unfortunately are not allowed to attach plain *.svg files, I packed it into the *.zip file below.
[fa-ello.zip](https://github.com/FortAwesome/Font-Awesome/files/416530/fa-ello.zip)

A few pull requests were already made and it is time to add the icon. :+1: 
[#4628](https://github.com/FortAwesome/Font-Awesome/issues/4628)
[#8970](https://github.com/FortAwesome/Font-Awesome/issues/8970)

**Comment by jnki** [comment]
+1 👍 
is there any actual plan of adding this?

**Comment by daveliao** [comment]
How can we help get this get prioritized for the next FontAwesome release? 😄

**Comment by HorlogeSkynet** [comment]
Hello there !

Sorry for the ~75 notifications sent, but why this still has not been added, 3 years later ?

Thanks 👋

**Comment by invisiblesushi** [comment]
+1

**Comment by dlocutor** [comment]
+1

**Comment by eolsen** [comment]
YES PLS +1

**Comment by eolsen** [comment]
Dude!


Eric Olsen
eric@perfectdaymedia.com <mailto:eric@perfectdaymedia.com>
802.735.2115

**Comment by davegandy** [comment]
https://fontawesome.com/icons/ello?style=brands

Hey folks! Just a reminder that the top brand icons. If we added every requested brand icon, the set would be far larger than it already even is. We're trying to balance it and put the most requested ones in only. It took 3 years because that's how long it took for folks to comment on the thread and +1 it to the point where it was the top of the [leaderboard](https://fontawesome.com/community/leaderboard/new).

We really do see the reactions and comments. It's how we choose to add new ones. (It's not based on how old the request is.)

As always, thanks for adding to the community. You folks are awesome. 👍
