### ISSUE TITLE
Icon Request: Balloon(s)

### ISSUE THREAD

**Issue by Gnate** [FortAwesome/Font-Awesome#4211]
For, you know, parties.  One, Two, Three would be nice.

**Comment by felipefrancisco** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by MVcodeartbr** [comment]
releted or dupe of #3398 ?

**Comment by tagliala** [comment]
@MVcodeartbr thanks

Closing here as a duplicate of #3398
