### ISSUE TITLE
Icon request: icon-queue

### ISSUE THREAD

**Issue by Dariusch** [FortAwesome/Font-Awesome#4214]
Hello Guys, I am looking for an icon which shows some kind of queue.

It could be something like this using your fa-user icon
http://www.designofsignage.com/application/symbol/hospital/image/600x600/gents-que.jpg

**Comment by receptuna** [comment]
+1

**Comment by nachokb** [comment]
+1

**Comment by mosaic141688** [comment]
+1

**Comment by dhaalves-uel** [comment]
+1

**Comment by brianrt** [comment]
Could always try to make something out of nothing with font-awesome's stacking icons feature.

**Comment by NathanBWaters** [comment]
+1

**Comment by edwinyzh** [comment]
+1
