### ISSUE TITLE
Icon Request: icon-slow-forward

### ISSUE THREAD

**Issue by ziroby** [FortAwesome/Font-Awesome#4215]
I'd really like an icon for "slow forward".  This would be for an audio or video, and it would slow down the audio/video -- put it in slow motion.

I think the icon would look like this:

![icon-slow](https://cloud.githubusercontent.com/assets/321166/4026106/6d077910-2c0e-11e4-9ec6-e57ed3353e90.png)

**Comment by Crissov** [comment]
The proposed symbol is in use for other functions as well, e.g. ‘single frame forward’, ‘replay selection’, [‘play from beginning’](http://ux.stackexchange.com/questions/89744/), ‘resume playing’, ‘play/pause toggle’.

As for rotating `fa-eject`, it uses the thicker bar from `fa-pause`, not `fa-fast-backward`/`fa-fast-forward`, and the narrower triangle from `fa-*backward`/`fa-*forward`, not `fa-play`. A dedicated icon might look differently.

Issue #6495 is semantically related, but graphically different.

**Comment by nknotts** [comment]
+1

**Comment by tagliala** [comment]
Closing here in favor of #6495
