### ISSUE TITLE
Icon request: Survey smilies: icon-angry

### ISSUE THREAD

**Issue by Derpette** [FortAwesome/Font-Awesome#4217]
Hello awesome people at FontAwesome,

I'd like to request extra smilies.
I plan on using this for feedback forms like on http://www.kcmsurvey.nl/ (press feedback tab), so people can choose their feedback from unhappy to very happy.
Edit: It would be great to have the missing 'very happy' and 'very unhappy/angry' smileys.
Thanks for taking the time to read this - I hope you'll take this into consideration.

![feedback](https://cloud.githubusercontent.com/assets/7605479/4027885/f6ab292e-2c35-11e4-9671-ceaabbfae0f4.jpg)

**Comment by Daijobou** [comment]
Thanks tagliala. I also had not found it. ;)

**Comment by tagliala** [comment]
let's use #1417 for grin

**Comment by SamFraser2007** [comment]
+1 a 1-5 scale would be great, currently we have 1-3:
fa-frown
fa-meh
fa-smile

be nice to have angry and very happy

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&c=emoji
