### ISSUE TITLE
Problem preparing an upgrade for use with LaTeX

### ISSUE THREAD

**Issue by Alfonsib** [FortAwesome/Font-Awesome#4218]
Hi,
I'm preparing an upgrade to the ‘fontawesome’ LaTeX package – the present package is based on version 3.1.1 of the font. Everything ran smoothly,except for one alias: fa-unsorted, which is the same as fa-sort. 
I had to write the definition of the alias this way, in order to make it usable by LaTex:

\expandafter\def\csname faicon@unsorted\endcsname           {\faUnsorted}     \def\faUnsorted          {\faSort}

Normally, this should let me use this icon in the form of this LaTeX command: \faUnsorted, or \faicon{unsorted}, that can be used instead of \faSort or \faicon{sort}. Now I get this  error message from the compiler:

‘use of \faSort doesn't match its definition’

It's the only alias that delivers this error message. Moreover: 1) I can use \faSort itself without a problem;  2) replacing fancifully \faSort with, say, \faTry in the definition of \faUnsorted works perfectly.

So I began suspecting there might be a problem in the glyph itself, or in the definition of the alias (I mean when used from within the font itself, not with LaTeX).

Any help help would be greatly appreciated. I thank you in advance.

Best regards,

B. Alfonsi

**Comment by tagliala** [comment]
Closing here

If this is still an issue, fill free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
