### ISSUE TITLE
Icon Request: fa-phone-support

### ISSUE THREAD

**Issue by btoconnor** [FortAwesome/Font-Awesome#4227]
Hi,

I was hoping for an icon to represent phone support.  A use case would be a site that advertises the fact that they have phone support available.  Something along the lines of a person with a headset on.  A site I frequent has something like this, but it would be nice if there was something similar in font awesome.

Example:
http://i.imgur.com/ZOlcO8A.png

**Comment by G-Driver** [comment]
@tagliala @btoconnor 

Isn't this the https://github.com/FortAwesome/Font-Awesome/issues/1146 original request?

**Comment by tagliala** [comment]
@G-Driver thanks.

let's say dup of #1146  or the more recent #5586 (which has more +1s)

closing here
