### ISSUE TITLE
Better indication of versions within the cheatsheet

### ISSUE THREAD

**Issue by pulzaar** [FortAwesome/Font-Awesome#4230]
Repost from issue #4191:

@tagliala Right, my bad, I was using 4.1.0, updating to 4.2.0 solved the problem. Thanks.

(Icons remained Minion Pro squares even after specifying them as FontAwesome...irrelevant now.)

As for feedback, it would be nice to indicate "new" icons in the cheatsheet. As a designer I use 99% of the time only the cheatsheet as a direct source for Photoshop. I don't check other pages of the site and I would guess other designers do not either. It didn't struck me that I need to update to a new version of the font because I didn't notice there is a new version. From a UX point of view and my perspective of using the site, having two separate pages Icons and Cheatsheet seems a bit redundant, imho.

**Comment by davidsilvasmith** [comment]
I had the missing icon problem where I need a new version a week or two ago.

I fixed it by ensuring I always have latest like this:

`<link href="//maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">`

**Comment by sensibleworld** [comment]
Closing this issue as it relates to an old version of Font Awesome. We've made a bunch of updates to our individual icon pages (including reference to when an icon was released). You can also now search by version number.
