### ISSUE TITLE
Icon Request: fa-ufo

### ISSUE THREAD

**Issue by pleiadian-starseed** [FortAwesome/Font-Awesome#4231]
please make ufo icon

thanks love & peace

**Comment by devfeng** [comment]
+1

**Comment by devfeng** [comment]
Look at my avatar!

**Comment by tuxy** [comment]
+1

![img](https://camo.githubusercontent.com/b48f3b76cf9377f369a28c60900080f7e29a126d/687474703a2f2f692e696d6775722e636f6d2f344f30443761702e706e67)

**Comment by ouschmitz** [comment]
+1

**Comment by Wineliva** [comment]
+1

**Comment by Kyootxims** [comment]
+1

**Comment by pckz** [comment]
+1

**Comment by yaroslavpat** [comment]
+1 on this, please!

**Comment by kirik** [comment]
+1!

**Comment by zhavoronkov** [comment]
+++

**Comment by oxozle** [comment]
+1

**Comment by andrewbrntt** [comment]
+9000

**Comment by chadwtaylor** [comment]
+1

**Comment by sensibleworld** [comment]
Just be careful with any probes. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=ufo&s=solid

<img width="357" alt="Screen Shot 2021-05-27 at 2 11 11 PM" src="https://user-images.githubusercontent.com/529604/119876002-65da4380-bef5-11eb-8a42-5490bac32b5b.png">
