### ISSUE TITLE
Medical & Dental specialities icons

### ISSUE THREAD

**Issue by igoralves1** [FortAwesome/Font-Awesome#4235]
Good morning folks,

I am working in a medical project where would be nice to have medical and dental specialties icons.
Does someone know if there is any project that is going in this direction?

thanks

Igor

**Comment by sensibleworld** [comment]
Cleaning up some old issues, and wanted to let you know we have a bunch of medical icons in Font Awesome 5: https://fontawesome.com/icons?d=gallery&c=medical
