### ISSUE TITLE
Icon Request: fa-insert-row , fa-insert-rows

### ISSUE THREAD

**Issue by paulber91** [FortAwesome/Font-Awesome#4237]
Hello. I searched a few with no results and i decided to ask you , if it's possible to make two icons, fa-record and fa-records. I'm planning to use them at tables. First it will mean add a new record(row) , and second it will mean add multiple records(more rows at a time , i select from a pop-up the number of rows  ). For adding a single record (new record) i can use fa-plus. But If i need to add more new records on the same table.. i really can't find a good icon for that. Thank you very much !

**Comment by tagliala** [comment]
closing here in favour of #4552
