### ISSUE TITLE
Icon request: fa-glasses or fa-eyeglasses

### ISSUE THREAD

**Issue by omnimint** [FortAwesome/Font-Awesome#4238]
Possible usage:
- medical: eye care
- adapt application for visual impairment
- optics store

Examples:

http://findicons.com/files/icons/2770/ios_7_icons/128/glasses.png
https://cdn3.iconfinder.com/data/icons/education/512/glass_B-512.png
http://www.clker.com/cliparts/C/X/t/J/x/q/nerd-glasses-a-md.png

**Comment by GetGeeks** [comment]
where are these glasses its been years?!?

**Comment by Spark3000** [comment]
YEARS
