### ISSUE TITLE
Icon Request: fa-boxing-glove / fa-fist

### ISSUE THREAD

**Issue by werlend** [FortAwesome/Font-Awesome#4245]
Could you add icons for a fight/match? Like a boxing glove or a fist.

**Comment by stanimirtt** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by wgmueller1** [comment]
+1

**Comment by sensibleworld** [comment]
We've just added a raised fist icon, and a boxing glove was added back in 5.0.5

https://fontawesome.com/icons/fist-raised?style=solid
https://fontawesome.com/icons/boxing-glove?style=solid
