### ISSUE TITLE
Icon request: fa-ribbon (fa-seal fa-badge fa-certificate-alt)

### ISSUE THREAD

**Issue by cdmo** [FortAwesome/Font-Awesome#4246]
Something along these lines would be cool:
![blue-ribbon](https://cloud.githubusercontent.com/assets/523381/4076425/09db4c6e-2eba-11e4-93a8-aec3a4d3c079.jpg)

Image found at http://www.ishaweb.com/ESW/Images/blue-ribbon.jpg

The color doesn't matter, of course, I just needed to differentiate from #2183

The use case I'm interested in is to signify awards attributed to a project.  Trophy isn't quite appropriate because it is the wrong tone for academic projects that receive awards from professional organizations.  I'm currently using the certificate icon, but that's not quite on the mark.  

Thanks for considering.

**Comment by skielbasa** [comment]
![image of ribbon icon](http://imgh.us/Untitled-1-02.svg)
An attempt at making it, needed it for a client site. Link is in .svg

**Comment by SteaveAshmore** [comment]
+1

**Comment by oraculus** [comment]
+1

**Comment by hmharter** [comment]
+1

**Comment by nahk** [comment]
:+1:  :3

**Comment by tadhghamill** [comment]
+1

**Comment by guyfawkes85** [comment]
+1

**Comment by indrif** [comment]
+1

**Comment by rx4hvn** [comment]
+1

**Comment by akshatpaul** [comment]
+1

**Comment by katiebeee** [comment]
+1

**Comment by adityasaxena** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1182#issue-14771972

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/1182#issuecomment-121431818

**Comment by larach** [comment]
+1 

Hello, 
I need an icon that represent an award/badge, something more like this : https://cdn2.iconfinder.com/data/icons/awards-and-seals-2/500/Award_certificate_medal_seal_badge_collection-512.png

I want to use it on a website using font awesome icons with a country showing that the company has 20 years of experience and more - something to feel proud of.

I hope you can add it - Many many thanks :)

Lara

**Comment by maximvd** [comment]
+1

**Comment by askrenes** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by CinchJim** [comment]
+1

**Comment by geoff-ellison** [comment]
+1

**Comment by romapad** [comment]
+1

**Comment by ConstantinStan** [comment]
+1

**Comment by cherrador** [comment]
My two cents... I have created a CSS stack extension that could create something like this. I added this request case with one tail on this jsfiddle. (I will update if I'm able to create two tails).

https://jsfiddle.net/cherrador/jomgLb2h/

Other thing I think a proper name for this icon should be fa-rosette
https://www.google.ca/search?q=rosette&biw=1687&bih=863&tbm=isch

**Comment by cobe1972** [comment]
+1
but I think a better name would be "fa-award" (fa-award icon:request [#3753](https://github.com/FortAwesome/Font-Awesome/issues/3753))
I leave a few that I have made with the fa-sun
![fa-award](https://cloud.githubusercontent.com/assets/16846747/12527806/1a2b2546-c183-11e5-85e0-6c0ff5d77d54.jpg)

**Comment by jasonmorehead** [comment]
+1

**Comment by idoadiv** [comment]
+1

**Comment by tiltsoftware** [comment]
+1

**Comment by tynorton** [comment]
+1

**Comment by pepalan** [comment]
+1

**Comment by luchomolina** [comment]
+1

**Comment by syamsulalam** [comment]
+1

**Comment by beardage** [comment]
+1

**Comment by darkndream** [comment]
+1

**Comment by nodecode** [comment]
+1

**Comment by wasbaiti** [comment]
+1

**Comment by shubhamoy** [comment]
+1

**Comment by beta3designs** [comment]
+1

**Comment by jensgeffken** [comment]
good idea

**Comment by edwardmcconville** [comment]
+1 please

**Comment by bensonwong** [comment]
+1

**Comment by jamesandsuch** [comment]
+1

**Comment by Crissov** [comment]
Related Unicode characters #222:

Emoji
------

- 🎀 **[U+1F380 Ribbon](http://emojipedia.org/ribbon/)** #3747?
- 🎗 [U+1F397 Reminder Ribbon](http://emojipedia.org/reminder-ribbon/) #2183
- 🏆 [U+1F3C6 Trophy](http://emojipedia.org/trophy/) #2778, `fa-trophy`
- 🏅 [U+1F3C5 Sports Medal](http://emojipedia.org/sports-medal/) #1898 
- 🥇 [U+1F947 First Place Medal (gold)](http://emojipedia.org/first-place-medal/) #1750 
- 🥈 [U+1F948 Second Place Medal (silver)](http://emojipedia.org/second-place-medal/)  #1750
- 🥉 [U+1F949 Third Place Medal (bronze)](http://emojipedia.org/third-place-medal/) #1750
- 🎖 [U+1F396 Military Medal](http://emojipedia.org/military-medal/) #3641
- 💮 [U+1F4AE White Flower](http://emojipedia.org/white-flower/)
- 🏵 **[U+1F3F5 Rosette](http://emojipedia.org/rosette/)**

Non-Emoji
----------

- ✾ U+273E Six Petalled Black and White Florette
- ✿ U+273F Black Florette
- ❀ U+2740 White Florette
- ❁ U+2741 Eight Petalled Outlined Black Florette

**Comment by PanuWeb** [comment]
+1

**Comment by mahi13c** [comment]
+1

**Comment by terraelise** [comment]
+1

**Comment by gpatry** [comment]
+1

**Comment by weibangtuo** [comment]
+1

**Comment by anija** [comment]
+1

**Comment by astu9880** [comment]
+1

**Comment by labmorales** [comment]
+1

**Comment by jdk339** [comment]
+1

**Comment by p9-metis** [comment]
+1

**Comment by demon101** [comment]
+1

**Comment by tomatillodesign** [comment]
+1

**Comment by artemkaint** [comment]
+1

**Comment by IvanPrat** [comment]
+1

**Comment by smgjreinieren** [comment]
+1

**Comment by tomatillodesign** [comment]
Here's a great example from Ionicons: 
![screen shot 2017-11-06 at 2 23 40 pm](https://user-images.githubusercontent.com/11273281/32459591-34f15ca0-c2fe-11e7-8f3c-5c675a79e65a.jpg)

**Comment by jakob-dena** [comment]
+1

**Comment by joshjGCB** [comment]
+1

**Comment by BillyZafack** [comment]
+1

**Comment by withintheruins14** [comment]
+1

**Comment by BonBonSlick** [comment]
+1

**Comment by tagliala** [comment]
@BonBonSlick this icon has been introduced in Font Awesome 5.2.0

Please make sure you are using a version of Font Awesome greater or equal to 5.2.0 (latest version at the moment I'm writing: 5.9.0)

Ref:
- https://fontawesome.com/start
- https://fontawesome.com/icons/award?style=solid

**Comment by jdk339** [comment]
It only took 5 years 😆

**Comment by sensibleworld** [comment]
@jdk339 Good things come to those who wait 😉

**Comment by cdmo** [comment]
I feel like y'all deserve a ribbon, or maybe a 🏆. Thank you.
