### ISSUE TITLE
Icon Request: fa-tie, fa-bowtie, fa-tuxedo

### ISSUE THREAD

**Issue by thenichanigroup** [FortAwesome/Font-Awesome#4248]
These fashion icons would be great for fashion websites that want to you the AWESOME Font Awesome Icons!

![bowtie](https://cloud.githubusercontent.com/assets/8581494/4078319/c440e70c-2eca-11e4-86c2-d05c8e07d652.png)
![tie collar](https://cloud.githubusercontent.com/assets/8581494/4078321/c65ff028-2eca-11e4-9840-0d8abfd9bde7.PNG)

**Comment by aethior** [comment]
Duplicate of #3896.

cc @tagliala

**Comment by tagliala** [comment]
No feedback, closing here
