### ISSUE TITLE
Icon request: fa-trust, fa-authority

### ISSUE THREAD

**Issue by JonnyHardwick** [FortAwesome/Font-Awesome#4249]
I'd like to see some FontAwesome icons based around trust and authority. I'm talking about trust in terms of trusted websites, but they could also be used for many other purposes to represent trust. Examples could be badges, emblems, shields etc.

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
