### ISSUE TITLE
"fa-times-circle-o" multiply sign is not centered on debian 7 / firefox

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4250]
Here is the obligatory screenshot:

![ss_20140829](https://cloud.githubusercontent.com/assets/363870/4089049/30e3267c-2f66-11e4-8155-155c3c086449.png)

**Comment by tagliala** [comment]
This is not an issue anymore in FA5.

It was still present on FA 4.7.0

Tested on Firefox 52 ESR on Debian 9.3.0

![image](https://user-images.githubusercontent.com/556268/36452227-f74ddb8c-1693-11e8-801b-6664829c74b0.png)

![image](https://user-images.githubusercontent.com/556268/36452263-1fabcd3c-1694-11e8-97d3-76e6cf26adb5.png)
