### ISSUE TITLE
Icon Request: fa-quick-top

### ISSUE THREAD

**Issue by BriniaSona** [FortAwesome/Font-Awesome#4256]
This is my submission for a quick to top icon.
![thstheatdhaedr](https://cloud.githubusercontent.com/assets/8593518/4094879/1439dd3a-2fad-11e4-8c46-aaaccc3de881.png)

**Comment by aethior** [comment]
Hi @BriniaSona,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/arrow-up-to-line

Regards.

cc/ @tagliala
