### ISSUE TITLE
Icon Request: fa-numeric-field

### ISSUE THREAD

**Issue by rhalaly** [FortAwesome/Font-Awesome#4258]
It would be great to create icon for numeric fields.

Thanks! Font-Awesome is the best!

**Comment by tagliala** [comment]
I'm going to consider this closed by https://fontawesome.com/icons/input-numeric?s=solid&f=classic

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=new+icon&template=000_icon_request.yml&title=Icon+request%3A+) if the above icons does not fit this use case.

Please also clarify why the actual icon does not fit the use case, why a different design is needed, and provide an example
