### ISSUE TITLE
Add Woff2 format.

### ISSUE THREAD

**Issue by vanesyan** [FortAwesome/Font-Awesome#4261]
Please, add woff2 format, it's supported by Chrome since 36.
Gist (from ttf -> woff2): https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a
W3C spec: http://www.w3.org/TR/WOFF2/

**Comment by davegandy** [comment]
Given the sheer amount of testing I'd want to put into this, I'm going to save it for 5.0.

**Comment by davegandy** [comment]
Changed my mind and got all the testing in. Woff2 format is now in 4.3.0-wip branch.

**Comment by tagliala** [comment]
:+1:

**Comment by realityking** [comment]
Awesome. Thank you.
