### ISSUE TITLE
Icon Request: fa-polar-chart

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4269]
For example http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/256/Actions-office-chart-polar-stacked-icon.png

<img src="http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/256/Actions-office-chart-polar-stacked-icon.png">

**Comment by mjizadi** [comment]
+1

**Comment by tomprats** [comment]
+1

**Comment by M3nace** [comment]
+1

**Comment by 8cells** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by aethior** [comment]
Hi @G-Driver,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/chart-radar

Regards.

cc/ @tagliala
