### ISSUE TITLE
Icon request: activities & photography

### ISSUE THREAD

**Issue by michelevescovi** [FortAwesome/Font-Awesome#427]
Some icons for representing predefined configurations in photography could be useful. Like e.g.:
- action (subject in movement)
- portrait
- night
- fireworks
- sun
- cloudy
  ...and many other almost already existing.
  Then weather icons (rain, cloud+thunder, snow, ...) and activities (running, sports, compass, ...) could be nice too.

**Comment by sensibleworld** [comment]
Doing my best to update some old issues, and wanted to note that we have a lot of new icons in version 5+ that should cover the requests above :) If not, please open a new request for any missing icons.

Thanks for being a part of the Font Awesome community!
