### ISSUE TITLE
Icon Request: fa-duplicate

### ISSUE THREAD

**Issue by numediaweb** [FortAwesome/Font-Awesome#4290]
This is found basicly in UI editors like; [Adobe Ideas](http://a3.mzstatic.com/us/r30/Purple6/v4/49/37/be/4937bed6-5665-94cc-84d3-3d158b55a8ea/screen568x568.jpeg), etc.
It suggests that the current element can be duplicated; I basicly needed it to allow duplicate DIV elements on a WYSIWYG app.

![duplicate](https://cloud.githubusercontent.com/assets/288614/4119213/e422eb24-32a8-11e4-88bb-cb31324c2704.png)

**Comment by aethior** [comment]
`fa-clone`was added in v4.4.

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks for checking the "waiting for feedback" label :)

Closing here
