### ISSUE TITLE
Icon Request: fa-hotdog

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4291]
A hotdog

<img src="http://cdn.flaticon.com/png/256/18482.png">

**Comment by richardrobinsonx** [comment]
This icon is great. Pls add.

**Comment by Crissov** [comment]
🌭 [U+1F32D](http://emojipedia.org/hot-dog/) Unicode emoji #222

**Comment by mrStenvik** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/hotdog?style=solid
