### ISSUE TITLE
Icon for Boys & Girls Club 

### ISSUE THREAD

**Issue by vrojas** [FortAwesome/Font-Awesome#4293]
We are wonder if you guys can create a logo for the Boys & Girls Club. and also more icons related to education and sports.
Thank you

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
