### ISSUE TITLE
Icon Request: fa-bandaid (icon-patch, icon band-aid)

### ISSUE THREAD

**Issue by JensNielsen81** [FortAwesome/Font-Awesome#4298]
Something like this would be nice :)

![band_aid](https://cloud.githubusercontent.com/assets/8639459/4131278/63771418-3344-11e4-9cca-c16c23b11409.png)
![33866](https://cloud.githubusercontent.com/assets/8639459/4131279/66a98b52-3344-11e4-81d0-4b8a14055409.png)

**Comment by jbteague** [comment]
+1

**Comment by Heinerion** [comment]
+1

**Comment by htbasaran** [comment]
+1

**Comment by legrego** [comment]
+1

**Comment by andreschabur** [comment]
+1

**Comment by Jinukurian7** [comment]
+1

**Comment by sensibleworld** [comment]
This icon is included in the latest 5.0.7 release of Font Awesome! The solid style is in Font Awesome 5 Free, with the regular and light styles included in Font Awesome 5 Pro. https://fontawesome.com/icons?d=gallery&q=bandaid
