### ISSUE TITLE
Icon Request: fa-expanse

### ISSUE THREAD

**Issue by equerambug** [FortAwesome/Font-Awesome#4303]
![money_finance_coins_economy_gold_cash_withdraw_expenses-128](https://cloud.githubusercontent.com/assets/5886168/4132854/95901f1e-3356-11e4-9199-714435afcd1c.png)

hi, i am using most of font icon but on few places i am having issue there for i need this icon as a expanse... if there is any way you could let me know i can do some thing about it..

**Comment by sensibleworld** [comment]
We now have a `coins` icon. If you need something different, please open a new request: https://fontawesome.com/icons/coins?style=solid
