### ISSUE TITLE
Icon Request: fa-trumpet / fa-bugle

### ISSUE THREAD

**Issue by babsonmatt** [FortAwesome/Font-Awesome#4314]
An icon of a trumpet or a bugle.

![image](https://cloud.githubusercontent.com/assets/853220/4138302/cd3f9d34-338f-11e4-9ecb-7266cb2c4345.png)

![image](https://cloud.githubusercontent.com/assets/853220/4138323/fc8776d4-338f-11e4-8691-c81806db49df.png)

**Comment by peiche** [comment]
+1

**Comment by doctorworm** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/trumpet?style=duotone
