### ISSUE TITLE
Need help turning FontAwesome classes into mixins

### ISSUE THREAD

**Issue by svallory** [FortAwesome/Font-Awesome#432]
Hi. I'm trying to turn FontAwesome into a mixin's library. I prefer to be able to define the icons from my less file. Check the gist https://gist.github.com/3522214 to see how far I got and where the problem is.

The objective is to make the entire css applicable through mixins. Most of the time this will make the final css smaller (since we'll have 348 lines less). But more importantly, makes your layout more easy to maitain. There is one part I couldn't transform. It's marked with comments on the file. For now, you need to use the class "icon-large" and manually set width for icons on "li" tags.

Example:

**.html**

``` html
<a href="#" class="btn linkbutton">Link button with icon</a>
```

**.less**

``` less
.linkbutton {
    .icon-upload;
}
```

**Comment by felixfbecker** [comment]
@digitalvapor this doesn work for me
```less
@import 'font-awesome/less/font-awesome';

.projects-locked-button {
  &:extend(.fa.fa-lock);
}

.projects-locked-button:hover {
  &:extend(.fa.fa-lock-alt);
}
```
any idea?

**Comment by tagliala** [comment]
@felixfbecker please consider stackoverflow for generic less questions
