### ISSUE TITLE
Icon request: icon-caduceus

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#4325]
Splitted from #150

**Comment by jbteague** [comment]
+1

**Comment by uGhz** [comment]
+1

**Comment by derek-schaefer** [comment]
+1

**Comment by Veritas1000** [comment]
+1

**Comment by Heinerion** [comment]
+1

**Comment by estrux** [comment]
+1

**Comment by pattersont** [comment]
+1
icon-caduceus
https://en.wikipedia.org/wiki/Caduceus
https://en.wikipedia.org/wiki/Caduceus_as_a_symbol_of_medicine
![caduceus-1](https://cloud.githubusercontent.com/assets/19173564/15613807/46e557d6-23ea-11e6-8010-b4afd6b8c52f.jpg)
![caduceus-2](https://cloud.githubusercontent.com/assets/19173564/15613817/4cf8eed0-23ea-11e6-8420-470d3c3cb1c0.jpg)

**Comment by raymassie** [comment]
Rod of Asclepius

**Comment by pattersont** [comment]
Learned something new!
http://drblayney.com/Asclepius.html

**Comment by raymassie** [comment]
"This usage is erroneous, popularised largely as a result of the adoption of the caduceus as its insignia by the U.S. Army Medical Corps in 1902 at the insistence of a single officer"

https://en.wikipedia.org/wiki/Caduceus

**Comment by pranavgawri** [comment]
+1

**Comment by benoror** [comment]
+1

**Comment by andreschabur** [comment]
+1

**Comment by brandonmcconnell** [comment]
+1

**Comment by mheidebrecht** [comment]
+1

**Comment by jfagner** [comment]
+1 
I work for a university and would make use of a caduceus icon frequently for medical links/content.

**Comment by JacobDB** [comment]
Genuinely surprised this hasn't been added yet, would love to see it in a future update.

**Comment by bysontin** [comment]
+1
Same here ! would love to see this icon added.

**Comment by sensibleworld** [comment]
We don't yet have a caduceus, but we did just release this: https://fontawesome.com/icons/staff-aesculapius?s=solid

**Comment by alancnet** [comment]
+1

**Comment by jfagner** [comment]
Jory,
This is great. Thanks so much for the follow up.

Sincerely,
J.

J. Fagner
Assistant Creative Director,
Digital Marketing Operations
Division of Marketing and Communications
One Bear Place #97024
Waco, TX 76798-7024
t: (254) 710-4795 | baylor.edu<http://baylor.edu>


***@***.***



On Mar 16, 2022, at 12:25 PM, Jory Raphael ***@***.******@***.***>> wrote:



We don't yet have a caduceus, but we did just release this: https://fontawesome.com/icons/staff-aesculapius?s=solid<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffontawesome.com%2Ficons%2Fstaff-aesculapius%3Fs%3Dsolid&data=04%7C01%7Cj_fagner%40baylor.edu%7C46d0f4ec13d74298994808da0771fe8b%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637830483426316641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hXDzbHy%2B3u0WmkpBD5zmD1twJ02ppqstIAQfPhAEYvw%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFortAwesome%2FFont-Awesome%2Fissues%2F4325%23issuecomment-1069380644&data=04%7C01%7Cj_fagner%40baylor.edu%7C46d0f4ec13d74298994808da0771fe8b%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637830483426316641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WE%2FiFLi7rwjNuTrjYgQWeBoLyYgU8%2BdEqYTh%2BG%2FgozU%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGT75DUZONA42JZLUCQ2XF3VAIKRJANCNFSM4ATZYVFA&data=04%7C01%7Cj_fagner%40baylor.edu%7C46d0f4ec13d74298994808da0771fe8b%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637830483426316641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l6EHxFVHJsC70f4kNsVSNs7ILAXNNWOjLDBw%2BRWuhqk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cj_fagner%40baylor.edu%7C46d0f4ec13d74298994808da0771fe8b%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637830483426316641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JG53DGpHe6CSyEAksnQQX4K5uVbg6mn03PUrngk%2Bh1g%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cj_fagner%40baylor.edu%7C46d0f4ec13d74298994808da0771fe8b%7C22d2fb35256a459bbcf4dc23d42dc0a4%7C0%7C0%7C637830483426316641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JJj4Rx8fBNJB6qLknwPv9lJkz42PCJaAe7MrA932vXk%3D&reserved=0>.

**Comment by sensibleworld** [comment]
We've finally added a caduceus: https://fontawesome.com/icons/caduceus?f=classic&s=solid

**Comment by jfagner** [comment]
Fantastic! Looks great. Thanks so much!

J.

J. Fagner
Associate Creative Director,
Digital Marketing Operations
Division of Marketing and Communications
One Bear Place #97024
Waco, TX 76798-7024
t: (254) 710-4795 | baylor.edu


[image001.png]



On Apr 3, 2024, at 5:11 AM, Jory Raphael ***@***.***> wrote:



We've finally added a caduceus: https://fontawesome.com/icons/caduceus?f=classic&s=solid
