### ISSUE TITLE
Icon Request: fa-nurse-silhouette

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4326]
<img src="http://sr.photos3.fotosearch.com/bthumb/CSP/CSP350/k3505915.jpg">

**Comment by nsimeonov** [comment]
great image for icon, aethior

**Comment by phasjim** [comment]
+1 for nurse icon, but would love if it was kept asexual like the doctor (fa-user-md) icon

![image](https://cloud.githubusercontent.com/assets/1915171/7825455/ec6bfd30-03c1-11e5-9707-22e3965bbfef.png)

**Comment by ringner** [comment]
+1, preferably gender-neutral.

**Comment by ivanwangtw** [comment]
aethior's icon is better.

**Comment by bhupendrachopra** [comment]
any timelines for any of these icons ?

**Comment by tagliala** [comment]
@bhupendrachopra please consider a custom build if you need this icon

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by kimberley-johnston** [comment]
+1

**Comment by mkeuschn** [comment]
++

**Comment by andreschabur** [comment]
+1

**Comment by mchapman** [comment]
If it is possible to have a care assistant alternative (in the first two examples you could remove the +) that would be great for in-home care as well

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-nurse?style=solid
