### ISSUE TITLE
Icon Request: icon-save-all

### ISSUE THREAD

**Issue by sesteel** [FortAwesome/Font-Awesome#433]
I am creating a text editor and would like to have a save all icon.

**Comment by paolofulgoni** [comment]
+1

**Comment by gandaldf** [comment]
+1
I think we really need a "save all" icon as @KarstenB pointed out... for now I'm using @stuartaylward solution.

**Comment by DaeHeeLim** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by Cynicszm** [comment]
Looking for the same icons, using font awesome light, would like to see save-as, save-all, close, close-all

**Comment by MMesich** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a few new "save" related icons to the v6 Alpha release: https://fontawesome.com/download

(And updated the naming to "floppy-disk")
