### ISSUE TITLE
Icon Request: fa-ideal

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4330]
The biggest online payment method in the Netherlands
<img src="https://www.ideal.nl/img/statisch/mobiel/iDEAL_512x512.gif">

**Comment by codevider** [comment]
+1

**Comment by JerVoo** [comment]
+1

**Comment by hcrobin** [comment]
+1

**Comment by pixelive** [comment]
+1

**Comment by RobinBrons** [comment]
+1

**Comment by hpk94** [comment]
+1

**Comment by henkvalk** [comment]
+1

**Comment by hpk94** [comment]
+1

**Comment by itscassa** [comment]
Another +1 here!

**Comment by cwosinga** [comment]
+1

**Comment by JerVoo** [comment]
+1

**Comment by Bas978** [comment]
+1

**Comment by QualityWorks** [comment]
+1

**Comment by martijnhartlief** [comment]
+1

**Comment by firstred** [comment]
+1

**Comment by markioooo** [comment]
+1

**Comment by moleculezz** [comment]
+1

**Comment by stephlow** [comment]
+1

**Comment by studiobovenkamer** [comment]
+1

**Comment by fruitl00p** [comment]
+1 and a link to the official logo: ![Image of iDeal logo](https://www.ideal.nl/img/statisch/iDEAL-groot.gif)

and the square versions available here: https://www.ideal.nl/ontvangen/logos-banners/mobiel/

Thanks!

**Comment by Milannv** [comment]
+1

**Comment by LauLaman** [comment]
+1000

**Comment by berry807** [comment]
+1

**Comment by maartenbrakkee** [comment]
SVG version:

https://dl.dropboxusercontent.com/u/58414180/iDEAL.svg

**Comment by G-Driver** [comment]
@maartenbrakkee give this thread a +1 ;)

**Comment by markioooo** [comment]
This issue was opened on Sep 4, 2014.

I'm beginning to wonder if this is the best place for this request ...

And another :+1: of course!

**Comment by s3ned** [comment]
+1

**Comment by KormaIT** [comment]
+1

**Comment by LauLaman** [comment]
What's the big hold-up?

**Comment by tjebbeke** [comment]
+1

**Comment by marcuskaptein** [comment]
+1

**Comment by G-Driver** [comment]
@LauLaman we need more +1 's, that's all

**Comment by marcuskaptein** [comment]
@G-Driver how much more +1's do you need for this?

**Comment by Bas978** [comment]
+234

**Comment by hslatman** [comment]
+:one:

**Comment by larsvdd** [comment]
+1 pleeeeeeaaaase

We Dutchies would really appriciate it! All 17 million of us! :+1:

**Comment by sevvlor** [comment]
+1

**Comment by arjehouw01** [comment]
+1

**Comment by CROSSYCROSSY** [comment]
+1

**Comment by G-Driver** [comment]
@marcuskaptein more then 100's of +1's :+1:

**Comment by MonkNL** [comment]
+1

**Comment by ParadoxNL** [comment]
+1

**Comment by nedpets** [comment]
+1

**Comment by jtrienekens** [comment]
+1

**Comment by darkroast** [comment]
+1

**Comment by vHeemstra** [comment]
+1

**Comment by Cannonb4ll** [comment]
+1

**Comment by sanderbongers** [comment]
+1

**Comment by tverheijen** [comment]
Still waiting on this fa-ideal :+1:

**Comment by tverheijen** [comment]
+1

**Comment by de-raaf-media** [comment]
I don't want it anymore. -1 ;)

**Comment by AuditeMarlow** [comment]
+1

**Comment by pvstempvoort** [comment]
+1!!

**Comment by maantje** [comment]
+1

**Comment by baaskoen** [comment]
+1

**Comment by fruitl00p** [comment]
ahum.. enough with the +1 galore, just vote on the initial request.. All these comments are just polluting the issue... 

thanks!

**Comment by Hoolite** [comment]
+1

**Comment by bronboek** [comment]
+1

**Comment by richardvdb88** [comment]
+1

**Comment by jwissels** [comment]
+1

**Comment by azachar** [comment]
+1

**Comment by casdr** [comment]
# Please add a 👍  reaction on the initial issue message instead of posting a +1 comment

**Comment by MaxClasener** [comment]
+100 i need it so BAD :D :D :D 
could you make it in this form:
fa fa-cc-visa
fa fa-cc-mastercard
fa fa-cc-paypal
for example:
fa fa-cc-ideal

**Comment by QualityWorks** [comment]
actually, isn't "cc" credit card? ideal isn't a cc. There is also an fa-paypal and fa-google-wallet. so it should be fa-ideal

**Comment by MaxClasener** [comment]
sorry my mistake,

i need to be like this:
http://fontawesome.io/icon/cc-paypal/
fa-cc-PayPal
so it will be
fa-cc-ideal

**Comment by marcoboers94** [comment]
I agree with QualityWorks, it isn't a credit card so it should be fa-ideal just like fa-google-wallet http://fontawesome.io/icon/google-wallet/.

**Comment by pvstempvoort** [comment]
Hi

Since fontawesome still doesn't support fa-ideal I've implemented a different payment icon font which I came across some time ago: https://paymentfont.com/ and which includes the iDeal icon.
Perhaps this is if some help?

Cheers,
Pieter

**Comment by marcoboers94** [comment]
@pvstempvoort thanks! Looks really nice!

**Comment by e-mkb** [comment]
+1

**Comment by jkwakman** [comment]
+1

**Comment by mdeboer** [comment]
@jkwakman @e-mkb Use the thumbs up reaction instead of posting +1! See: https://github.com/FortAwesome/Font-Awesome/issues/4330#issuecomment-292465754

**Comment by Kopertje** [comment]
+1

**Comment by JaccoVeldscholten** [comment]
+1

**Comment by erikjandelange** [comment]
+1

**Comment by berry807** [comment]
+1

**Comment by aloisdg** [comment]
Still useful. Any news?

**Comment by hostingwalk** [comment]
After 5 years any update ?   iDeal is the biggest payment method in The Netherlands.

**Comment by MightyFo0l** [comment]
+1

**Comment by pgroot91** [comment]
1+

**Comment by berry807** [comment]
+1

**Comment by erawebnl** [comment]
+1

**Comment by erikjandelange** [comment]
I see it had been released in 5.12.0 https://github.com/FortAwesome/Font-Awesome/commit/d8db3d032d22e7a5e21f3b40905b7867be19bb02

**Comment by erawebnl** [comment]
@sensibleworld: Not to nag, but the logo officialy had two colors, so: Can you also make an duotone version of it?

**Comment by sensibleworld** [comment]
@erawebnl Unfortunately, our brand icons are all currently limited to a single color. Though I agree that duotone versions could be a nice addition!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/ideal?style=brands

**Comment by aloisdg** [comment]
@sensibleworld thank you for the good work! Do you plan to add more payment systems?
