### ISSUE TITLE
Icon request: icon-push-box (icon-share-box)

### ISSUE THREAD

**Issue by Manbearpixel** [FortAwesome/Font-Awesome#4335]
Simple share/push box minimal icon. 

See attachment..

![fa-push-box](https://cloud.githubusercontent.com/assets/6686750/4157447/c7c2b32e-347e-11e4-978d-2693dc7bbe4e.jpg)

**Comment by Waylon87** [comment]
+1 

I've been wanting this one for a while now. Would be a nice update to the current share options.

**Comment by Manbearpixel** [comment]
Yeah I was surprised more people didn't find this useful. Was hoping to see it in 4.3 :/

But I mean there's not much you can do if more people want pizza icons. I'm still using a non-vector form of it on my current site haha

**Comment by tagliala** [comment]
reopening for tracking purposes

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/arrow-up-from-square?

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, I think this may fit the use case
