### ISSUE TITLE
Feature Request: Integrate popular web fonts as face?

### ISSUE THREAD

**Issue by hitchhiker** [FortAwesome/Font-Awesome#4339]
Hi,

I'm no font expert, so apologies if this is impractical or impossible. Would it be possible to create versions with something like 'open-sans' or some of the other popular web-fonts as the fa font-face?

This would enable us to reduce asset load times, for instance I currently need to load open-sans + fa, using only the fa icons, but not the face.

Thanks for the amazing work you've done, you've saved so many people so much time!!

Cheers,
Frank.

**Comment by iegik** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki/Merge-FontAwesome-with-any-other-font

**Comment by hitchhiker** [comment]
Fantastic :) thanks

**Comment by tagliala** [comment]
Closing here, there is also a wiki to implement this functionality

It is worth to mention that now Font Awesome has its own font :)
