### ISSUE TITLE
Icon Request: fa-sofort

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4342]
A German payment method/handler
<img src="http://www.miasallergievrijeshop.nl/images/Sofort.gif"> 

Edit: only the logo not the letters

**Comment by G-Driver** [comment]
@CoDEmanX awsome :+1:

**Comment by thelamborghinistory** [comment]
though @CoDEmanX css solution is pretty neat I also would still love to see this included in fa. +1

**Comment by kevinhartmann1** [comment]
+1

**Comment by Batacus** [comment]
Would love to have SOFORT as an Icon in the fontawesome family

**Comment by tagliala** [comment]
Hi, could someone clarify the differences between sofort and klarna? 

Ref: #4340

**Comment by mxmzb** [comment]
> Hi, could someone clarify the differences between sofort and klarna?
> 
> Ref: #4340

Sofort was a company from Germany which streamlined the payment process for bank transfers. It got acquired by Klarna in 2013, a Swedish fintech that allows you to buy stuff and then repay afterward over rates.

Sofort is still widely offered on many German websites as a payment option and has its own logo, although nowadays it's just part of Klarnas product line.

**Comment by tagliala** [comment]
As per https://github.com/FortAwesome/Font-Awesome/issues/14986#issuecomment-822813018, I'm going to close here in favor of #4340 

Please upvote #4340
