### ISSUE TITLE
Icon Request: fa-emergency-medical-cross (fa-staroflife)

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#4345]
<img src="http://www.clker.com/cliparts/p/p/W/T/9/W/emergency-medical-cross-md.png">

**Comment by DarrenPaulWright** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by sensibleworld** [comment]
We added a simplified version of this in 5.2.0: https://fontawesome.com/icons/star-of-life?style=solid
