### ISSUE TITLE
Icon Request: fa-coin

### ISSUE THREAD

**Issue by radupb** [FortAwesome/Font-Awesome#4350]
Dear developer,

Thank you for your work. It is greatly appreciated.

I would like to request a coin icon, to represent money in general. The banknote could be used but I feel that a coin would stand out a little bit more.

Thank you once more and have a nice day.
Radu

**Comment by trybowski** [comment]
+1

**Comment by SkyBadPT** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by iamwillow** [comment]
+1 
Design Ideas:

Coin:
![coin](https://cloud.githubusercontent.com/assets/3923914/17199109/6c1a69f0-54b5-11e6-994d-3daab862f784.jpg)

Coins:
![coins](https://cloud.githubusercontent.com/assets/3923914/17199114/70ae506c-54b5-11e6-83fd-b88c169d38b7.png)

**Comment by JefMari** [comment]
+1

**Comment by TheAliAbbasi** [comment]
+1

**Comment by B1QB0SS** [comment]
+1

**Comment by TheAslera** [comment]
+1

**Comment by bakaibalazs** [comment]
+1

**Comment by BenMorel** [comment]
+1. Love @iamwillow's [second proposal](https://github.com/FortAwesome/Font-Awesome/issues/4350#issuecomment-235782852).

**Comment by bausshf** [comment]
What's the status on this?

**Comment by NickKaramoff** [comment]
+1

**Comment by fernandobonfimandrade** [comment]
+1

**Comment by Groman123** [comment]
+1

**Comment by flkc** [comment]
+1

**Comment by abrvlk** [comment]
+1

I was very surprised when I did not find fa-icons (the stack of coins). In my opinion this is a very popular icon for e-commerce.

**Comment by Wingo5315** [comment]
+1

**Comment by mark-barrett** [comment]
+1

**Comment by JFSF** [comment]
+1

**Comment by sensibleworld** [comment]
Font Awesome Pro now has a coin icon: https://fontawesome.com/icons/coin?style=solid
