### ISSUE TITLE
Warning about alias in documentation

### ISSUE THREAD

**Issue by Jakobud** [FortAwesome/Font-Awesome#4355]
Look at this fiddle:

http://jsfiddle.net/8t75nk01/

It's loading FA 4.1.0.  How come the `fa-bar-chart` and `fa-area-chart` don't show up?

**Comment by tagliala** [comment]
I'm going to close this issue

There are shims for backward compatibility, alias were take down in FA5 and are back in FA6

If someone is experiencing issues with aliases and documentation, please open a new issue
