### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4359]
GoodReads is the largest online book recommendations library. More about them: http://www.goodreads.com/about/us. This is their famous “g” icon: http://www.iconfinder.com/icons/287723/goodreads_icon#size=128 (it is brown on their page). I was thinking of using it for my Tumblr blog (http://howheseesit.tumblr.com). A number of Tumblr themes actually use Font-Awesome and for the many Tumblr users, who also have a GoodReads account (Tumblr and GoodReads have an enormous shared user-base) it would be great to be able to have their libraries as a social icon.

Thank you for your attention.

**Comment by carrieloves** [comment]
+1
