### ISSUE TITLE
Icon request: household, activities

### ISSUE THREAD

**Issue by juanfranblanco** [FortAwesome/Font-Awesome#436]
- bed
- washer
- fridge
- satellite
- microwave
- oven
- bathroom
- swimming pool
- beach
- golf

Many thanks!!! You are the best time saver for any application.

**Comment by souledge0** [comment]
+1 for Satellite

**Comment by berkeleybob** [comment]
+1

**Comment by mediabeastnz** [comment]
+1

Sorry i just submitted a couple requests that are similar to a few of these

**Comment by m-r-h-n** [comment]
+1

**Comment by soccer99** [comment]
+1

**Comment by sensibleworld** [comment]
We just added a bunch of new household-related icons to version 5.12: https://fontawesome.com/icons?d=gallery&c=household
