### ISSUE TITLE
Icon Issue: bar-chart

### ISSUE THREAD

**Issue by MMHossaini** [FortAwesome/Font-Awesome#4364]
This is actually a column chart. please rename to column-chart

**Comment by kkirsche** [comment]
I would argue to use column chart as opposed to bar chart. Powerpoint for example correctly notes this difference. If they can, I see no reason we shouldn't as well.

![screen shot 2015-01-23 at 2 50 53 pm](https://cloud.githubusercontent.com/assets/947110/5881502/44e7d0d8-a30f-11e4-9573-61a882413379.png)

**Comment by diegopiriz** [comment]
+1

**Comment by dereklin** [comment]
I am also looking for the real bar chart font: http://www.highcharts.com/demo/bar-basic

The current one is really the column chart: http://www.highcharts.com/docs/chart-and-series-types/column-chart

**Comment by sensibleworld** [comment]
We've got this fixed in the latest alpha release of version 6: http://fontawesome.com/download
