### ISSUE TITLE
Icon Request: fa-youku

### ISSUE THREAD

**Issue by dawey** [FortAwesome/Font-Awesome#4365]
There is a Chinese video platform called - 
www.youku.com 
and i would highly appreciate - if you could integrate that one. 

thank you
david

**Comment by mcarv63** [comment]
+1 want it

**Comment by Aspirinwang** [comment]
+1

**Comment by brajeshjadiya** [comment]
I am also request for add "fa-youku" on your font list. Thank's

**Comment by tagliala** [comment]
duplicate of #3487, please +1 that request

closing here
