### ISSUE TITLE
Icon Request: fa-waze

### ISSUE THREAD

**Issue by arielk** [FortAwesome/Font-Awesome#4367]
Waze it's a cool mobile application for navigation and maps (currently powered by Google).

Website: [Waze.com](https://www.waze.com)
Press kit (officially): [Google Drive](https://drive.google.com/folderview?id=0BznE1vHdT0kcVlZjRFZmRktDZnM&usp=sharing)

Full Logo:
![presskit_waze-logo-tagline-monochrome-positive](https://cloud.githubusercontent.com/assets/1778512/4185502/981ce67c-3757-11e4-8e41-f1749795f557.png)

Icon:
![waze](https://cloud.githubusercontent.com/assets/1778512/4185501/98168070-3757-11e4-859b-8f8777c0f13e.png)

SVG Version:
https://gist.github.com/KingYes/c69ee198ea45eb6560d6

**Comment by erezLieberman** [comment]
+1

**Comment by scottrouse** [comment]
+1

**Comment by heyallan** [comment]
+1

**Comment by ruthnis** [comment]
+1

**Comment by rzrz** [comment]
+1

**Comment by hexplus** [comment]
+1

**Comment by weiliank** [comment]
+1

**Comment by meirlo** [comment]
+1

**Comment by aldofunes** [comment]
+1, would be awesome to have this. It is an ever-growing network

**Comment by monsteronfire** [comment]
+1

**Comment by jarodxxx** [comment]
+1

**Comment by terryago11** [comment]
+1

**Comment by lucachaco** [comment]
+1

**Comment by gust0o** [comment]
+1

**Comment by mikio1** [comment]
+1

**Comment by shalomda** [comment]
+1

**Comment by einavsh** [comment]
+1

**Comment by diegofpb** [comment]
+1

**Comment by cobicarmel** [comment]
+1

**Comment by KevinMalo** [comment]
+1

**Comment by mperazac** [comment]
+1

**Comment by asanti82** [comment]
+1

**Comment by wassem** [comment]
+1

**Comment by einavsh** [comment]
+1

**Comment by hAtul89** [comment]
+1

**Comment by ezani92** [comment]
+1

**Comment by danstramer** [comment]
+1

**Comment by BSCrea** [comment]
+1

**Comment by LeonBeilis** [comment]
+1

**Comment by ncamaa** [comment]
+1

**Comment by alaniha** [comment]
+1

**Comment by dbrrt** [comment]
+1

**Comment by DossieDockett** [comment]
Definitely!

**Comment by daha76** [comment]
+1

**Comment by LeonBeilis** [comment]
4 years still waiting btw

**Comment by esisrael** [comment]
its almost 2019 and still waiting.

**Comment by goldola** [comment]
Its now 2019 and still waiting

**Comment by mohsennj** [comment]
Why don't you add popular app icons? please add waze.

**Comment by rafaelsorto** [comment]
+1

**Comment by heerenjasper** [comment]
+1

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/waze

Thanks for the patience and for continuing to vote this up! Oh, and remember to share your drive with your mother when you're on your way to see her. :smile:
