### ISSUE TITLE
Icon request: signal empty -> signal full

### ISSUE THREAD

**Issue by mayinhosa** [FortAwesome/Font-Awesome#437]
additional 5 icons for signal empty to signal full - each symbol with a new bar added or filled for example.

**Comment by xdumaine** [comment]
+1

**Comment by lookapanda** [comment]
+1

**Comment by Vilsepi** [comment]
+1

**Comment by topikito** [comment]
+1

**Comment by lgm42** [comment]
+1

**Comment by cnelissen** [comment]
+1

**Comment by skasten** [comment]
+1

**Comment by humancopy** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
@tagliala, should this one be closed in favour of [#1870](https://github.com/FortAwesome/Font-Awesome/issues/1870), which has more activity and example use cases?

**Comment by tagliala** [comment]
This one is older, I should also copy & paste +1s from here to there.

Thanks for reporting this, let's use #1870
