### ISSUE TITLE
Icon request: fa-align-elements

### ISSUE THREAD

**Issue by marcuslind90** [FortAwesome/Font-Awesome#4390]
I'm missing an align element icon like when you want to align layers in Photoshop centered to eachother. See example here: ![](http://www.cupcard.com/template/bootstrap3/img/editor-icons-sprite.png).

Currently you only have the fa-align-center icon which is for centering text and have a complete different meaning to the users.

**Comment by Half-timber** [comment]
Adding my 2 cents years later... I too would like to see this.

**Comment by e-anka** [comment]
I need it very much!

**Comment by sensibleworld** [comment]
<img width="512" alt="Screen Shot 2021-03-30 at 12 47 13 PM" src="https://user-images.githubusercontent.com/529604/113025542-0f02f880-9156-11eb-83e9-999702edc344.png">
 Do these work?

**Comment by e-anka** [comment]
Well, those are for text. I need something like this: https://www.canstockphoto.com/align-icons-collection-set-of-simple-49999363.html - but anyway I managed and made some myself...

**Comment by sensibleworld** [comment]
Ah, yes! I'll get those added to a future release.

**Comment by sensibleworld** [comment]
We've got a batch of these icons added to version 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=distribute&s=solid
