### ISSUE TITLE
Icon Request: fa-login & fa-logout

### ISSUE THREAD

**Issue by ShaunR** [FortAwesome/Font-Awesome#4400]
I would like to see login and logout icons.

https://cdn1.iconfinder.com/data/icons/windows-8-metro-style/512/login.png
https://cdn1.iconfinder.com/data/icons/windows-8-metro-style/512/logout.png

Search google images for login icon or logout icon and you'll see many examples.

**Comment by jplehmann** [comment]
Recommend adding an alias with word 'login'.

**Comment by tagliala** [comment]
@jplehmann added log in and login filters via https://github.com/FortAwesome/Font-Awesome/commit/3a793741b520da09576662a247186b8b4c1c02c8, thanks for your suggestion

**Comment by jplehmann** [comment]
Nice job!

---
