### ISSUE TITLE
Icon Request: fa-tugrik

### ISSUE THREAD

**Issue by miiga** [FortAwesome/Font-Awesome#4402]
Tugrik is official currency of Mongolia.  In unicode, the tugrik sign is U+20AE ₮.
I'd used Font-Awesome in commercial web application. I wanna display tugrik and dollar icon in application. 
Please add :) 
Thank you  
![untitled-1](https://cloud.githubusercontent.com/assets/2462839/4229834/ac939942-3979-11e4-9019-4b081e703c47.png)

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
