### ISSUE TITLE
Icon Request: fa-shopping-bag-o

### ISSUE THREAD

**Issue by rajeshkhatri13** [FortAwesome/Font-Awesome#4404]
Need icon font for attached image, it will be useful for everyone in the future..

![shopping-bag](https://cloud.githubusercontent.com/assets/2714117/4231290/4681df72-398f-11e4-9f6d-bd9ca68fad6c.png)

**Comment by ffxsam** [comment]
:+1:

**Comment by emilstahl** [comment]
+1

**Comment by sickrandir** [comment]
+1

**Comment by GP-Snippets** [comment]
👍
