### ISSUE TITLE
Icon request: toolbox

### ISSUE THREAD

**Issue by jpslaga** [FortAwesome/Font-Awesome#4407]
Looking for a small toolbox icon 

Here are a couple of icon's that I found on a web search
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsB3tPzJ3sOGVh-CHRPbtWNVLmwySOIZBprMyrasrY-i1KCDOr

http://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&docid=1AGP1VDWUr1YvM&tbnid=s1M_HvmJtTnB_M:&ved=0CAcQjRw&url=http%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Ftoolbox_31353&ei=brERVL3AJ8jSiwLjx4DwAQ&bvm=bv.75097201,d.cGE&psig=AFQjCNF2gw1R8BZq5Sb25jXBcEFWB8IpHg&ust=1410531861572637

**Comment by tromney** [comment]
+1

**Comment by meyersbs** [comment]
+1

**Comment by bstolle** [comment]
+1

**Comment by willianribeiro** [comment]
+1

**Comment by JoshWeb** [comment]
+1

**Comment by dockrize** [comment]
+1

**Comment by sergiodlopes** [comment]
+1

**Comment by WChangson** [comment]
+1

**Comment by sensibleworld** [comment]
Time to fix things up! https://fontawesome.com/icons?d=gallery&q=toolbox
