### ISSUE TITLE
Change request: fa-money icon from 1 to 5

### ISSUE THREAD

**Issue by notapatch** [FortAwesome/Font-Awesome#4418]
Very few countries have a 1 currency banknote - so I would like the cash icon to be changed to 5.

I looked at the [top 15 traded currencies](http://en.wikipedia.org/wiki/Currency) and threw in a few big population countries (India and Brazil). These currencies miss a 1 note:  [Dollar - Australian](http://en.wikipedia.org/wiki/Australian_dollar), [Dollar - Canadian](http://en.wikipedia.org/wiki/Canadian_dollar), [Dollar - New Zealand](http://en.wikipedia.org/wiki/New_Zealand_dollar), [Dollar - Singapore](http://en.wikipedia.org/wiki/Singapore_dollar), [Euro - Europe](http://en.wikipedia.org/wiki/Euro), [Lira - Turkey](http://en.wikipedia.org/wiki/Turkish_lira),[ Pound - Britain](http://en.wikipedia.org/wiki/Pound_sterling), [Real - Brazil](http://en.wikipedia.org/wiki/Brazilian_real), [Rupee - Indian](http://en.wikipedia.org/wiki/Indian_rupee),  [Rubel - Russia](http://en.wikipedia.org/wiki/Russian_ruble).

All these countries do however have a 5 currency banknote (Russia uses the 5 Ruble note rarely). 
No better or worse: [Dollar - US which has both](http://en.wikipedia.org/wiki/United_States_dollar), [Yen - Japan works in 1000's](http://en.wikipedia.org/wiki/Japanese_yen),  [Swiss Franc starts at 10](http://en.wikipedia.org/wiki/Swiss_franc), [Peso - Mexico starts at 20](http://en.wikipedia.org/wiki/Mexican_peso), [Krona - Sweden starts at 20](http://en.wikipedia.org/wiki/Swedish_krona), [Hong Kong Dollar doesn't have 1 or 5](http://en.wikipedia.org/wiki/Hong_Kong_dollar) and, [China has both a 1 and a 5 banknote](http://en.wikipedia.org/wiki/Renminbi).

Given the space limitation I think a 5 would be more understandable to a much larger percentage of the world's population. I have not found a country that issues 1 currency banknotes and not 5 - though I'm sure there must be some!

**Comment by TheChen5** [comment]
+1

**Comment by My1** [comment]
@RichardWigley no, Japan works in the hundreds. 
5000 yen is like 44 dollars.

**Comment by nofxx** [comment]
Japan money is only Integer, that's very cool. =D

Sorry if I hurt anyone feelings, but money icon deserves a restyle, just give it a fair look...
It doesn't fit. It's the ugly duck.

**Comment by frederickjh** [comment]
I think that issue #9509 "Icon Request: fa-money-empty is a headed toward a better solution to this issue. If the 1 can be remove from current empty money icon and there is enough space to allow 2 digits then anyone could stack the icons to create an icon with a number that would best fit with their home currency.

This would also allow stacking the currency symbol icons. So for example for the Japanese Yen that uses thousands on their bills, there is currently an icon for the Yen. It would be possible to stack the Yen icon with the empty money icon for use in Japan.

**Comment by sensibleworld** [comment]
We have a bunch go alternates now: https://fontawesome.com/v6.0/icons?q=money&s=solid%2Cbrands
