### ISSUE TITLE
Icon Request: fa-microsoft

### ISSUE THREAD

**Issue by FabienLavocat** [FortAwesome/Font-Awesome#4419]
Hi!
I'd like to see the official Microsoft logo.
Microsoft Logo Guidelines: http://www.microsoft.com/en-us/legal/IntellectualProperty/Trademarks/Usage/Logo.aspx

![imgthree](https://cloud.githubusercontent.com/assets/4154532/4254807/e4f4e21a-3aae-11e4-82e6-5f93f9a933c4.jpg)

The logo "fa-th-large" is very similar, but not square.

Thanks!

**Comment by ricardopolo** [comment]
:+1:

**Comment by vinniejames** [comment]
:+1:

**Comment by graymatter00** [comment]
👍

**Comment by codyn329** [comment]
+1

**Comment by madmunsterdaddy** [comment]
+1. This would be a big help for me.

**Comment by ThomasPe** [comment]
+1

**Comment by popisms** [comment]
Since this is still open, I thought I would point out that "fa-windows" exists. It's angled like the Windows 8/10 logo rather than square though.

**Comment by vinniejames** [comment]
@popisms Microsoft's brand guidelines require this logo for certain uses

**Comment by CarpCharacin** [comment]
+1

**Comment by athix** [comment]
+1

**Comment by pwill2** [comment]
I gave a Thumbs up but would like it as well

**Comment by Montoya** [comment]
+1

Will use the Windows logo for now but there are a bunch of non-Windows Microsoft products that could use the main MS logo instead.

**Comment by My1** [comment]
but @vinniejames wouldnt an FA based MS logo be invalid as it's single color? I meansure it would be nice but these guidelines are imo way too annoying from time to time.

**Comment by timtjtim** [comment]
“A one color logo is only acceptable when media reproduction is limited. In these cases, the logo may be reversed to white on a background that provides suitable contrast. A black logo is allowed when media reproduction is black only."

**Comment by My1** [comment]
well exactly and in the web (the obviously most used place for iconfonts like FA) you have all the rgb colors available.

**Comment by punitganshani** [comment]
+1

**Comment by My1** [comment]
https://fontawesome.com/icons/microsoft?style=brands

**Comment by carlin-q-scott** [comment]
How is this closed if the icon is still only available in black and white?

**Comment by My1** [comment]
Because fontawesome in the end is still a font.
