### ISSUE TITLE
Icon Request: fa-certificate-ca

### ISSUE THREAD

**Issue by pbcomanche** [FortAwesome/Font-Awesome#4420]
Please add Digital Signature Certificate:
![diploma-128](https://cloud.githubusercontent.com/assets/8757127/4259642/1f2e303a-3b04-11e4-975f-4c51450496c2.png)

**Comment by terraelise** [comment]
+1 or issue 1182

**Comment by andreasvad** [comment]
+1

**Comment by nemequ** [comment]
+1

**Comment by dibgraversen** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by anahitas72** [comment]
I did request a patent icon. This seems pretty similar but not exactly.

**Comment by anahitas72** [comment]
+1

**Comment by romapad** [comment]
+1

**Comment by marksa** [comment]
+1

**Comment by wagneramaral** [comment]
+1

**Comment by matthiasballreich** [comment]
+1 from me, too. I would have an icon for a digital certificate, too. But i want one in portrait format like this: http://www.flaticon.com/free-icon/diploma_149350

**Comment by finlay-liu** [comment]
+1

**Comment by Alex-Golovin** [comment]
+1

**Comment by weibangtuo** [comment]
+1

**Comment by deyvisonsouto** [comment]
+1

**Comment by MarcosFerrao** [comment]
+1

**Comment by H3ld3rM3** [comment]
+1

**Comment by demon101** [comment]
+1

**Comment by kwendenarmo** [comment]
This is now available in Font Awesome 5 beta-2 but it doesn't look like this request

**Comment by tagliala** [comment]
@kwendenarmo please note that FA5 beta 2 is not the free version of Font Awesome

**Comment by demon101** [comment]
@kwendenarmo I can't find it in fontawesome-5.0.0-beta3
How it's named?

**Comment by MehdiGol** [comment]
+1

**Comment by wloaiza** [comment]
+1

**Comment by AlessandroVecchi** [comment]
https://www.iconfinder.com/icons/274313/approved_certified_diploma_document_file_license_page_paper_quality_text_icon#size=256

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-certificate?style=solid
