### ISSUE TITLE
Icon Request: fa-snapchat

### ISSUE THREAD

**Issue by johnjlocke** [FortAwesome/Font-Awesome#4421]
It's likely someone else has suggested this already, but an icon for Snapchat would be cool. Thanks!

**Comment by jackvial** [comment]
+1

**Comment by heog0519** [comment]
+1

**Comment by G-Driver** [comment]
@heog0519 please +1 https://github.com/FortAwesome/Font-Awesome/issues/3906

@tagliala can you check the closed agaian?

**Comment by tagliala** [comment]
locking here
