### ISSUE TITLE
Icon Request: fa-bath

### ISSUE THREAD

**Issue by simonmilz** [FortAwesome/Font-Awesome#4426]
This should be a great icon for travel / vacantion rental / hotel websites.

**Comment by shams-144** [comment]
fa-bath icon is not showing while fa-bed is showing. I'm using latest 4.7.0 css file.Any help??

**Comment by tagliala** [comment]
@shams-144 `fa-bed` was introduced in version 4.3, `fa-bath` in 4.7. Please double check that you are using the 4.7.0. Note that other plugins or libraries may load an older version and that might have precedence. https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
