### ISSUE TITLE
Icon request: icon-tire icon-tire-flat

### ISSUE THREAD

**Issue by spmasterman** [FortAwesome/Font-Awesome#4430]
Want: Car (or other generic) tire, and matching flat tire similar to the "dashboard warning light" for a flat tire on vehicles with tire pressure monitoring

Use case (es):
1: To indicate mechanical status - something is running, or broken (probably combined with fa-warning)
2: To indicate a failure to 'inflate' an object

Something like these: http://www.dunloptires.com/assets/dunlop/en-US/img/service-icons/flat-tire-136x136.png

I searched there was one previous request for a car tire, that got closed because the requester didn't provide use cases or respond to requests for feedback - apologies if I should have resurrected that request instead of a new one.

**Comment by jobbogamer** [comment]
:+1:

**Comment by iatek** [comment]
+1

**Comment by DigitalBella** [comment]
+1

**Comment by MacGWik** [comment]
+1.

I need this. Please make it Font Awesome !

**Comment by MacGWik** [comment]
+1

**Comment by MacGWik** [comment]
+1

**Comment by MacGWik** [comment]
+1

**Comment by MacGWik** [comment]
+1

**Comment by Dov1s** [comment]
1

**Comment by martinnigel** [comment]
+1

**Comment by malikmalhan** [comment]
+1

**Comment by improvisio** [comment]
+1

**Comment by Bas978** [comment]
+1

**Comment by nguyen-tran** [comment]
+1

**Comment by erandros** [comment]
+1

**Comment by mokry** [comment]
+1

**Comment by maxegghead** [comment]
+1

**Comment by burgerautomotive** [comment]
+1

**Comment by thomasreiser** [comment]
+1

**Comment by kennetvu** [comment]
+1

**Comment by SewHappy58** [comment]
This would sure be nice.  Especially for car parts web sites.

**Comment by schowes** [comment]
+1

**Comment by AdamasFR** [comment]
+1

**Comment by dagi12** [comment]
+1

**Comment by tbonz** [comment]
+1

**Comment by prgsavi** [comment]
+1

**Comment by JayEnaR** [comment]
+1

**Comment by tbonz** [comment]
+1

**Comment by jeffreyvdhondel** [comment]
+1

**Comment by edwinboon** [comment]
+1

**Comment by gerardimmeker** [comment]
+1

**Comment by kacedali** [comment]
+1

**Comment by Jinukurian7** [comment]
+1

**Comment by csabafarkas** [comment]
+1

**Comment by ibrahimyilmaz7** [comment]
+1

**Comment by shahnawazrao** [comment]
+1

**Comment by tagliala** [comment]
This icon is already available in Font Awesome Pro

https://fontawesome.com/icons/tire-flat?style=solid

For more information, please read [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), "Why are some (highly requested) icons not available in Font Awesome Free?"

(This is not a highly requested icons btw)
