### ISSUE TITLE
Icon Request: fa-fingerprint

### ISSUE THREAD

**Issue by twistedpixel** [FortAwesome/Font-Awesome#4431]
I'd love to see a fingerprint icon.

Could be useful for denoting a touch button on a mobile device.

Something similar in style to Apple's Touch ID (simply a round area of a fingerprint).

![screen shot 2014-09-14 at 6 12 34 pm](https://cloud.githubusercontent.com/assets/1885273/4264766/7ab0c6dc-3c32-11e4-9d67-4730d8e0ab78.png)

**Comment by mikri** [comment]
+1

**Comment by mooseywilson** [comment]
+1

**Comment by qopel** [comment]
I like it!

**Comment by ddeakes** [comment]
+1

**Comment by plaperdr** [comment]
+1

**Comment by g3x0** [comment]
+1

**Comment by G-Driver** [comment]
+1 definitely

**Comment by Escendrix** [comment]
+1 would love a fingerprint icon to represent "branding", on a services page

**Comment by designomx** [comment]
+1 Yes

**Comment by MattSnowOregonGov** [comment]
+1 Yes. We have a background check and fingerpring requirement in an application. This would be useful.

**Comment by JideLambo** [comment]
+1 fingerprint icon would do alot of help for me right now.

**Comment by aethior** [comment]
+1

**Comment by marketica** [comment]
+1

**Comment by hgenru** [comment]
+1

**Comment by arielleguizamon** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by refo** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by luisfontes19** [comment]
+1

**Comment by darrencornwell** [comment]
+ 1

**Comment by AndreLGava** [comment]
+1

**Comment by 0x1ad2** [comment]
Why isn't this icon implemented yet? A lot of people seem to want it (since sep '14).

**Comment by G-Driver** [comment]
@0x1ad2 just give this thread a +1

**Comment by AndreLGava** [comment]
Could I design this icon and submit to be added to the font? how do I suppose to do this? It can be submited as a .ai vector?

**Comment by G-Driver** [comment]
@AndreLGava probably @davegandy could give you the right answer ;)

**Comment by AndreLGava** [comment]
@G-Driver  thank you, i'm waiting, it would be awesome to design some icons to help the project

**Comment by AndreLGava** [comment]
I guess that is a pattern to follow to develop the icons like lines, strokes, height weight, curves, angles, spaces and others. I didn't find this anywhere. If I have this I'd could colaborate designing something that could be usefull. @davegandy could I design it? Is there a documentation about it?

**Comment by thekondrashov** [comment]
+1

**Comment by kafenio** [comment]
+1

**Comment by aerciofilho** [comment]
+1

**Comment by jbzdawka** [comment]
+1

**Comment by 80leaves** [comment]
+1

**Comment by CagedEcho** [comment]
+1 ... the **fa-500px** is very close to a fingerprint... it just needs some tweaks to remove the 90 degree corners.

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so i decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-fingerprint was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by gigocabrera** [comment]
+1 
I would love to see this implemented, but after 2 years of requests this item may be dead (sad face)

**Comment by Escendrix** [comment]
@gigocabrera https://www.youtube.com/watch?v=lEOOZDbMrgE

**Comment by elbel86** [comment]
+1

**Comment by douglasdeodato** [comment]
+1

**Comment by gigocabrera** [comment]
Sad to admit... but I think this is dead  :cry:

**Comment by CagedEcho** [comment]
I hate to plug another tool, but I started using [Material Design Icon web font](https://design.google.com/icons/) from Google in addition to FA... it's got a [fingerprint icon](https://design.google.com/icons/#ic_fingerprint) and works similarly to FA... I had to make a few tweaks to the CSS to make it work like FA, so now I can use class="mdi mdi-fingerprint".

**Comment by gigocabrera** [comment]
@CagedEcho That's awesome :+1: 

>  I had to make a few tweaks to the CSS to make it work like FA, so now I can use class="mdi mdi-fingerprint".

What kind of tweaks? Can you share/

**Comment by se** [comment]
+1

**Comment by xaviergxf** [comment]
+1

**Comment by grafa** [comment]
+1

**Comment by bibinbalakrishnan** [comment]
+1

**Comment by dericeira** [comment]
+1

**Comment by cgpro** [comment]
+1

**Comment by CZechBoY** [comment]
+1

**Comment by jeantimex** [comment]
+1

**Comment by faviomob** [comment]
+1

**Comment by code4jhon** [comment]
+1

**Comment by yaim** [comment]
+1

**Comment by TomoyaShibata** [comment]
+1

**Comment by imranali123** [comment]
+1

**Comment by mr3k** [comment]
+1

**Comment by DutrowLLC** [comment]
+1

**Comment by fraxool** [comment]
+1

**Comment by GrexAut** [comment]
+1

**Comment by shaikansaar** [comment]
+1

**Comment by grafa** [comment]
I don't think our "+1" will change anything. Authors probably don't give a sh*t about one of the most needed icon nowadays. No offense just a fact.

**Comment by KristopherWagner** [comment]
any update on this?

**Comment by hellsing71** [comment]
+1

**Comment by nguyenchanhnghia** [comment]
+1

**Comment by cxammar** [comment]
+1

**Comment by chapeljuice** [comment]
+1

**Comment by colindeanfr** [comment]
+1

**Comment by quantissimo** [comment]
+10

**Comment by geoherna** [comment]
+1 Use font awesome in iOS apps. Would be nice for Touch-ID requests.

**Comment by yalmuhaidib** [comment]
+1

**Comment by yuranevmer** [comment]
+1

**Comment by scriptmonster** [comment]
+1

**Comment by felipefv** [comment]
+1

**Comment by Reverbe** [comment]
+1

**Comment by ahmed997** [comment]
+1

**Comment by jbagaresgaray** [comment]
+1

**Comment by noonii** [comment]
+1

**Comment by kirilmaz** [comment]
+1

**Comment by nayyaung** [comment]
+1

**Comment by LordOkami** [comment]
+1

**Comment by gavin2812** [comment]
+1 as this gets more useful and required for mobile devices. Thank you!

**Comment by Kilowhisky** [comment]
+1

**Comment by esdebon** [comment]
+1

**Comment by syamlal** [comment]
+1

**Comment by syamlal** [comment]
+1

**Comment by AnandChowdhary** [comment]
+1

**Comment by henrydeclety** [comment]
+1

**Comment by Avto9711** [comment]
+1

**Comment by pamelacfelipe** [comment]
+1

**Comment by uanthwal** [comment]
+1

**Comment by fenaconcd** [comment]
+1

**Comment by Bryght7** [comment]
+1

**Comment by fmaylinch** [comment]
+1

**Comment by fuadajip** [comment]
+1

**Comment by gberthia** [comment]
+1

**Comment by Mactory** [comment]
+1

**Comment by laurensnl** [comment]
+1

**Comment by mrwunderbar666** [comment]
+1

**Comment by ReGdYN** [comment]
+1

**Comment by rruffer** [comment]
+1
I'm doing an online capture system and I need this icon for yesterday. pleeeeaasssee !!!

**Comment by dii-mbaker** [comment]
+1 ... what does this now add up to??

we could use it for background check processing

**Comment by sensibleworld** [comment]
This icon has been designed and should make it out the door with our next release (coming in the next week or so).

**Comment by twistedpixel** [comment]
OP is happy.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/fingerprint?style=solid

**Comment by lhunath** [comment]
FYI, we really need to augment this with a FaceID / facial recognition icon; since print-based biometrics have long been replaced with facial on iOS and other devices.  A generic "biometric" icon might not be a crazy idea though I've no idea how one would do that.

I'd appreciate votes on https://github.com/FortAwesome/Font-Awesome/issues/8244 from any interested parties.

**Comment by sensibleworld** [comment]
@lhunath Agreed. We're definitely missing some sort of facial recognition icon. It's on my to-do list :)
