### ISSUE TITLE
Icon request: icon-zhihu

### ISSUE THREAD

**Issue by coneycode** [FortAwesome/Font-Awesome#4439]
thanks for your share. now I want a icon www.zhihu.com,
fa-zhihu
Could help me?
thanks.

**Comment by quxiaofeng** [comment]
+1 to zhihu icon.

**Comment by hrwhisper** [comment]
+1 to zhihu icon.

**Comment by lan2720** [comment]
+1

**Comment by tearsofphoenix** [comment]
+1

**Comment by fonzieyang** [comment]
+1

**Comment by haoyun** [comment]
+1

**Comment by mysqto** [comment]
+1

**Comment by mysqto** [comment]
Plus the icon of Zhihu
![zhihu](https://cloud.githubusercontent.com/assets/2177831/8560979/bd95e92a-2550-11e5-9e47-771c194f85f2.png)

**Comment by zhengxiaopeng** [comment]
+1

**Comment by TKdroid** [comment]
+1

**Comment by elvestar** [comment]
+1 fa-zhihu

**Comment by codynguyen1116** [comment]
+1

**Comment by qianzui** [comment]
+1 to zhihu icon.

**Comment by drinking** [comment]
+1

**Comment by vincgao** [comment]
+1

**Comment by TKdroid** [comment]
How popular is [zhihu.com](https://www.zhihu.com) : Global Rank: 202; Rank in China: 33 - [Alexa's data](http://www.alexa.com/siteinfo/zhihu.com)

**Comment by plantvsbirds** [comment]
+1

**Comment by microstudent** [comment]
+1

**Comment by microstudent** [comment]
zhihu and Quora is a similar site, and it has a lot of users in China, so I look forward to have a zhihu's icon, thanks! :)

**Comment by plough** [comment]
+1

**Comment by wangpengfei15975** [comment]
+1

**Comment by wangpengfei15975** [comment]
@plough 哈哈，我看了你的博客然后直奔去看你的知乎icon

**Comment by egrcc** [comment]
+1

**Comment by consen** [comment]
+1

**Comment by DaphneChang** [comment]
+1
How popular is zhihu.com : **Global Rank: 165**; Rank in China: 31 - Alexa's data

Here are some single color versions of "zhihu".

![zhihu_1](https://cloud.githubusercontent.com/assets/10896406/14494527/cf872da2-01bd-11e6-8647-537cd166bb33.png)
![zhihu_2](https://cloud.githubusercontent.com/assets/10896406/14494531/cf90d460-01bd-11e6-92e4-b7060feee298.png)
![zhihu_3](https://cloud.githubusercontent.com/assets/10896406/14494528/cf8e8a20-01bd-11e6-99b5-4cb5f713ffe0.png)
![zhihu_4](https://cloud.githubusercontent.com/assets/10896406/14494530/cf8faa9a-01bd-11e6-9da6-7fdecd587a42.png)
![zhihu_5](https://cloud.githubusercontent.com/assets/10896406/14494529/cf8f15da-01bd-11e6-959e-c83e81c85d44.png)
![zhihu_6](https://cloud.githubusercontent.com/assets/10896406/14494532/cfb4d46e-01bd-11e6-9ac3-d666c0d667d0.png)

**Comment by Joysr** [comment]
+1

**Comment by oodavy41** [comment]
+1

**Comment by keenmisty** [comment]
+1

**Comment by DaphneChang** [comment]
Some brief introduction about "Zhihu" : 
Zhihu is a Chinese website like Quora. More than twenty million users ask questions and get high-quality answers there.

How popular is zhihu.com : **Global Rank: 139** ; Rank in China: 30 - Alexa's data

**Comment by haoyun** [comment]
even Quora icon is not there.

**Comment by Menci** [comment]
+1

**Comment by yl1991** [comment]
+1

**Comment by djyde** [comment]
+1

**Comment by shls** [comment]
+1

**Comment by lhzbxx** [comment]
+1

**Comment by AzureRong** [comment]
+1

**Comment by coneycode** [comment]
+1

**Comment by yinwoods** [comment]
+1

**Comment by changkun** [comment]
it's been two years, why still an open issue for this icon?

**Comment by mcfloundinho** [comment]
+1

**Comment by yixiaoyuan** [comment]
+1

**Comment by blademainer** [comment]
+1

**Comment by AlexLove77** [comment]
+1

**Comment by Maples7** [comment]
+1

**Comment by vinc96** [comment]
+1

**Comment by maajor** [comment]
+1

**Comment by zhangqifan** [comment]
+1

**Comment by JSW5297** [comment]
+1

**Comment by Superbeet** [comment]
+1

**Comment by wukongcode** [comment]
+1

**Comment by stanNo1** [comment]
+1

**Comment by lightning-li** [comment]
+1

**Comment by pthtc** [comment]
+1

**Comment by danaive** [comment]
+1

**Comment by zjcwill** [comment]
+1

**Comment by ZengShuai1996** [comment]
+1

**Comment by fuyufjh** [comment]
+1

**Comment by FakeHank** [comment]
+1

**Comment by erain** [comment]
+1

**Comment by PegasusWang** [comment]
+1

**Comment by yezizp2012** [comment]
+1

**Comment by dreamingo** [comment]
+1

**Comment by gudabai** [comment]
+1

**Comment by yusmile** [comment]
+1

**Comment by zhengguanji** [comment]
+1

**Comment by loveky** [comment]
+1

**Comment by HtHuanChen** [comment]
+1 && +10086

**Comment by zhanghang1989** [comment]
+1

**Comment by Reasno** [comment]
+1

**Comment by hellozjf** [comment]
+1

**Comment by dyz2102** [comment]
+1

**Comment by thisisbeam** [comment]
+1

**Comment by ylq167** [comment]
+1 thx

**Comment by starkshaw** [comment]
+1. We need icons for Zhihu.

**Comment by deeptimhe** [comment]
+1

**Comment by YuliangXiu** [comment]
+10086

**Comment by biezhi** [comment]
+1

**Comment by secretwiki** [comment]
+1

**Comment by toryzen** [comment]
+1

**Comment by MrEasonYang** [comment]
+1

**Comment by nobodyzxc** [comment]
+1

**Comment by kkren** [comment]
+1want zhihu icon

**Comment by IlKilalI** [comment]
+1

**Comment by alex2young** [comment]
+1

**Comment by gxz1989611** [comment]
+1

**Comment by svenhsia** [comment]
+1

**Comment by herowzz** [comment]
+1

**Comment by ApolloZhu** [comment]
+1 for @zhihu

**Comment by Voleking** [comment]
+1

**Comment by Lt-grint** [comment]
+1

**Comment by joeyac** [comment]
+1

**Comment by yzyDavid** [comment]
+1

**Comment by dong4j** [comment]
+1

**Comment by wolegechu** [comment]
+1

**Comment by pennbay** [comment]
This icon can be find here http://www.iconfont.cn/search/index?q=zhihu. There is many good icons, please add this icon. If you need any help, I'd like help.  @tagliala @davegandy @zhihu

**Comment by pennbay** [comment]
This icon also can be find at [iconfinder](https://www.iconfinder.com/icons/214732/china_chinese_zhihu_icon#size=128), there is various size and formart version icons of zhihu. @tagliala @davegandy

**Comment by liziwl** [comment]
I need it too! please add it.

**Comment by RogersCj** [comment]
+1

**Comment by fanpancn** [comment]
+1

**Comment by HaoyWang** [comment]
+1
Zhihu is a important website in China now.Many people want to use the icon of Zhihu.
So,could you please make a icon of it?
Thanks.

**Comment by edwardzjl** [comment]
+1

**Comment by DaphneChang** [comment]
Very very very disappointed at your team.
It's been three years, why still an open issue for this icon? @tagliala

**Comment by dyz2102** [comment]
Zhihu: #24 site in China and #131 globally according to [alexa](https://www.alexa.com/siteinfo/zhihu.com). Beats at least 50% of the sites that have font-awesome icons I presume.

**Comment by xinyuwufei** [comment]
+1

**Comment by bihuchao** [comment]
+1

**Comment by y-wan** [comment]
+1

**Comment by aBlueMouse** [comment]
+1

**Comment by MissMin** [comment]
+1

**Comment by hoseahsu** [comment]
+1

**Comment by Ray-Eldath** [comment]
+1

**Comment by zixuanweeei** [comment]
+1

**Comment by BosenY** [comment]
+1

**Comment by KokeCacao** [comment]
+1

**Comment by yzyDavid** [comment]
+1

**Comment by SuperMarcus** [comment]
+1

**Comment by yannxia** [comment]
+1

**Comment by qijianjun** [comment]
+1

**Comment by WH-2099** [comment]
+1

**Comment by superwyh** [comment]
+1

**Comment by skylee03** [comment]
+1

**Comment by gaohanghang** [comment]
+1

**Comment by DaphneChang** [comment]
兄弟们，别等更新了，从2014年到现在，要重视早更新了。
明显因为不是他们本国网站，所以根本不在意。
咱程序员的脾气也真是太好了，官方不给更就在这耐心得"+1"一条条回。
失望之极……

——来自一个从2016年就关注此issue，并不时来看看进展的程序员
！！（╯' - ')╯︵ ┻━┻ （掀桌子） 
┬─┬ ノ( ' - 'ノ) {摆好摆好）
 (╯°Д°)╯︵ ┻━┻(再他妈的掀一次）

**Comment by schen57** [comment]
我去。。。也能这样直接歧视吗

**Comment by WaitingDJ** [comment]
+1

**Comment by PegasusWang** [comment]
https://fontawesome.com/icons/zhihu?style=brands

**Comment by cirosantilli** [comment]
做得好
