### ISSUE TITLE
Icon Request: fa-cc-cartebleue

### ISSUE THREAD

**Issue by GeorgesLeYeti** [FortAwesome/Font-Awesome#4440]
Hi,

I'm french and in France we have a wildly use icon for paiement which is "cartebleue". It s like mastercard or visa.
Actualy it might be a very simple icon to do. It is just a C and a B with a specific font inside a card just like the visa icon. Here the logo (the logo is white so just set the background-color: #000):

http://www.cartes-bancaires.com/design/src/img/common/logo.png

**Comment by viebel** [comment]
I'd be happy to have cartebleue in font awesome!

**Comment by aloisdg** [comment]
The link is dead. Here is the logo:

![image](https://user-images.githubusercontent.com/3449303/162696665-90dba5a7-f090-47f0-ae31-d4877b19a633.png)

![image](https://user-images.githubusercontent.com/3449303/162696527-08d6c51b-a6b3-446c-9531-02dab8c20e0a.png)

**Comment by aethior** [comment]
>In 2010, the Carte Bleue brand was phased out in favour of Visa; however, the term carte bleue continues to be used as a generic term for EFT-based payment cards, including debit and credit cards. ([more info](https://en.wikipedia.org/wiki/Carte_Bleue))

cc/ @tagliala
