### ISSUE TITLE
Icon request: icon-fruit/icon-vegetables

### ISSUE THREAD

**Issue by iznogud** [FortAwesome/Font-Awesome#4443]
Hello,

Please make an icon that would symbolilze fruits. I am a nutritionist who is runnning a blog and using your great icon set. I am really missing to use more food icons. First icon or an icon set to make this request and I believe many new users happy would be a fruit icon. As a global and easily understandable symbol, that could be a grape. As it's counterpart in the food world, a vegetable icon could be represented by a carrot. 
As a further development, cow could go for meat and wheat grain for the cereals... you see were I am going at. As a another proposition, an apple would be alternative to the grape.
To conclude
fa-grape grapes, three rows with pyramid berries, and a semi vine leaf on top
fa-carrot tuber with dashed body with a cut stalks on top
fa-apple not bitten like the computer manufactuer logo, but with a short stalk, oval heart shaped

Thank you good people and I hope that you like this idea.. 
Iz.

**Comment by tagliala** [comment]
No feedback, closing here
