### ISSUE TITLE
Icon Request: fa-package; fa-parcel

### ISSUE THREAD

**Issue by danielflippance** [FortAwesome/Font-Awesome#4446]
Thanks for all the great icons guys! Love them.
I'd like an icon for e-commerce that shows a package/parcel you'd receive in the mail. eg:
http://www.linuxstudent.com/wp-content/uploads/2012/07/Mail.jpg

**Comment by rodnem** [comment]
+1
a cardbox eg: http://thenounproject.com/search/?q=parcel

**Comment by ppp999** [comment]
+1

**Comment by tagliala** [comment]
locking here
