### ISSUE TITLE
Icon Request: fa-oil

### ISSUE THREAD

**Issue by stevegoossens** [FortAwesome/Font-Awesome#4448]
Purpose: engine oil check/change at garage
Alternative name: fa-engine-oil

![18uzfltmranadjpg](https://cloud.githubusercontent.com/assets/2405344/4289125/39383692-3db1-11e4-924f-67d6d8595518.jpg)

**Comment by marcoslhc** [comment]
👍🏼

**Comment by schowes** [comment]
+1

**Comment by nikghelani** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by alicecoleman** [comment]
+1 please
