### ISSUE TITLE
Update Facebook & Pinterest logos

### ISSUE THREAD

**Issue by tylertrotter** [FortAwesome/Font-Awesome#4463]
In the attached image I've set a Font Awesome Facebook icon (left) next to one I pulled from Facebook's website (right). You can see that the rounded corners and proportions of the square are both off.

![facebook-icons](https://cloud.githubusercontent.com/assets/4097146/4303179/04d6c7da-3e63-11e4-8e3a-394a597b282f.png)

**Comment by davegandy** [comment]
Updated in 4.3.0-wip.

- `fa-facebook` now points to facebook official
- `fa-facebook-f` has been added as an icon
- `fa-pinterest-p` has been added as an icon

Closing.

**Comment by tagliala** [comment]
@davegandy this breaks backward compatibility.

We should not do this in 4.3 and delay to 5.0.0

my suggestion

* alias fa-facebook with fa-facebook-f
* add fa-facebook-official

when 5.0.0 will be released, we can rename fa-facebook-alias to fa-facebook

**Comment by westin** [comment]
Great work @athyuttamre!!!! YOU SAVED THE DAY
