### ISSUE TITLE
Icon Request: fa-sports-podium 

### ISSUE THREAD

**Issue by jdvivar** [FortAwesome/Font-Awesome#4467]
![image](https://cloud.githubusercontent.com/assets/690017/4317652/8946bb80-3f15-11e4-8b1b-961d47232979.png)

Something like it. It could be used for representing many things related with games or web apps where you as a user has a rank, improvements won, etc.

I was wondering if numbers (1,2,3) could help identify the icon, or just the 1 on below the top.

What do you think?

**Comment by rockerest** [comment]
+1, definitely useful to designate a "ranking" or "final ordering" (which would be discrete from `fa-sort-*`).

I think I would much prefer an icon with all three numbers a la: ![Basic, but has perspective shift](http://image.shutterstock.com/display_pic_with_logo/52861/52861,1226884029,8/stock-vector-a-three-tier-award-podium-for-winners-with-platforms-for-first-second-and-third-place-20642641.jpg)

Some more examples:
![Essentially the same as the shutterstock image](http://previews.123rf.com/images/michaeldb/michaeldb0811/michaeldb081100039/3936419-People-get-gold-silver-bronze-medals-on-three-tier-award-podium-platforms-for-first-second-third-pla-Stock-Vector.jpg)

![Simple but nice looking, probably too detailed to make sense in an icon](http://en.share-gate.com/2nd-anniversary/images/podium.png)

**Comment by jeremierichard** [comment]
+1

**Comment by AlexeyKosov** [comment]
+2

**Comment by lsmpascal** [comment]
+1

**Comment by dyorgio** [comment]
+1

**Comment by dasprinzip** [comment]
without (podium) or
with --2-1-3-- (podium-numbered) to describe a competition/challenge

with only --1-- (podium-won) in the middle to describe the won competition/challenge

with highlight 
--[2]-1-3-- (podium-place2), 
--2-[1]-3-- (podium-place1), 
--2-1-[3]-- (podium-place3)

**Comment by pmarsilio** [comment]
+1

**Comment by Khrysller** [comment]
+1

**Comment by DaniDonaire** [comment]
+1

**Comment by sethwalker1** [comment]
+1

**Comment by busheikin** [comment]
+1

**Comment by nunoturbina** [comment]
+1

**Comment by smamet** [comment]
+1

**Comment by 0528Makoto** [comment]
+1

**Comment by jdvivar** [comment]
Wow! I opened this 6 years ago... I was a very junior dev then. I feel I could contribute now, but Font Awesome is not open for code contributions. They allow icon request issues (like this one) but not code requests that contain new icons, as put out in their [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md), so we cannot contribute. It makes sense, since I guess they need to maintain and strongly control a design look and feel.

Looking at icon request issues, this one is at page 7 😩, so I guess it will never be implemented. However **if someone lands here, please +1 with 👍  on the first message**, which I think is the best way to measure what to implement for the core dev team from Font Awesome.

Thank you!

**Comment by NovaRagnarok** [comment]
I'm frankly surprised this isn't available. This seems like such a no-brainer.

**Comment by Volen99** [comment]
+1

**Comment by andreaskasper** [comment]
Example I designed for my project - in the style of FontAwesome:
![Placement](https://scoring.dance/skins/grey/images/icon/placement_000000.svg)

**Comment by StephaneBour** [comment]
+1

**Comment by fromi** [comment]
I would love to have this icon for Game Park board games!

**Comment by Volen99** [comment]
+1

**Comment by sensibleworld** [comment]
Does this work? https://fontawesome.com/icons/ranking-star?s=solid

**Comment by andreaskasper** [comment]
> Does this work? https://fontawesome.com/icons/ranking-star?s=solid

It's not the olympic thing many expect but for my projects this would work :-)
Thanks haven't seen that icon yet :-)

**Comment by fromi** [comment]
> 

Ranking Star is exactly the icon I need!
However I installed this node dependency: `"@fortawesome/free-solid-svg-icons": "6.1.0"` and the icon is not inside, whereas on the website it is indicated as free and v6.1.0 😭

**Comment by jdvivar** [comment]
8 years! Thanks @sensibleworld
