### ISSUE TITLE
Icon Request: icon-radiation (icon-radioactive)

### ISSUE THREAD

**Issue by tagliala** [FortAwesome/Font-Awesome#4470]
Splitted out from #255

![image](https://cloud.githubusercontent.com/assets/556268/13035821/af33a08c-d358-11e5-8f8e-6adaa0f9f97b.png)

**Comment by huntwelch** [comment]
+1

**Comment by j-s-v** [comment]
+1

**Comment by webscot** [comment]
+1

**Comment by dariuszkusz** [comment]
+1

**Comment by IdolwSzutrab7** [comment]
+1

**Comment by Legiew** [comment]
+1

**Comment by DarkTatka** [comment]
+1 it would help a lot

**Comment by Barroba** [comment]
+1

**Comment by Quezler** [comment]
+1

**Comment by gracerx** [comment]
So wait, there's a gravity icon but not a nuclear one? really?

**Comment by DEQWeb** [comment]
+1

**Comment by javierluz** [comment]
+1

**Comment by vbbalaji** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/radiation?style=solid
https://fontawesome.com/icons/radiation-alt?style=solid
