### ISSUE TITLE
Icon Request: fa-piano

### ISSUE THREAD

**Issue by ruzannah** [FortAwesome/Font-Awesome#4472]
![piano](https://cloud.githubusercontent.com/assets/8828525/4330758/79cc9c60-3fb5-11e4-8d75-5f56413fab10.jpg)

**Comment by waleythefrog** [comment]
It would be really cool to have a piano icon and also one for voice and guitar!

**Comment by tagliala** [comment]
Please use #5054

**Comment by peteremiljensen** [comment]
+1
