### ISSUE TITLE
Issue: fa-chevron-right not aligned properly when stacked on top of fa-circle-thin

### ISSUE THREAD

**Issue by begedin** [FortAwesome/Font-Awesome#4479]
As it says in the title, the fa-chevron-right icon does not align properly when stacked on top of fa-circle-thin.

Here's the html:

```
<span class="fa-stack">
  <i class="fa fa-circle-thin fa-stack-2x"></i>
  <i class="fa fa-chevron-right fa-stack-1x"></i>
</span>
<span class="fa-stack">
  <i class="fa fa-circle-thin fa-stack-2x"></i>
  <i class="fa fa-chevron-left fa-stack-1x"></i>
</span>
<span class="fa-stack">
  <i class="fa fa-circle-thin fa-stack-2x"></i>
  <i class="fa fa-chevron-up fa-stack-1x"></i>
</span>
<span class="fa-stack">
  <i class="fa fa-circle-thin fa-stack-2x"></i>
  <i class="fa fa-chevron-down fa-stack-1x"></i>
</span>
```

And here's a pen reproducing the issue: http://codepen.io/anon/pen/jAIrG

UPDATE: As @taglia mentioned, apparently, the same thing is going on with the other chevron-x icons. I've updated the above pen and snippet to include the other 3.

**Comment by jhned** [comment]
Checking back in on this-- stacking chevrons and angles with circle-thin is causing misalignment also. Looks like the circle icon doesn't take up as much space as it should, and the chevrons and angles are not aligned horizontally as well.

**Comment by cherrador** [comment]
The fa-chevron-up has problem, the rest looks OK. I do not think is a CSS problem, it is how the icon has been aligned on the height of the line. Here is another sample showing the problem.

https://jsfiddle.net/cherrador/jomgLb2h/10/

**Comment by tagliala** [comment]
This is not css, don't know why I labeled this issue that way. Thanks for reporting this

**Comment by sensibleworld** [comment]
At this point, we're pretty much leaving Font Awesome 4 as-is. I'm going to close this issue. If it's still something that needs fixing in FA 5, can you open a new issue? Thanks!
