### ISSUE TITLE
Icon Request: fa-pizza

### ISSUE THREAD

**Issue by mattiamez** [FortAwesome/Font-Awesome#4493]
Hi guys.. i need a pizza icon (it's important to distinguish between "cutlery" and "pizza")
![meanicons_28-512](https://cloud.githubusercontent.com/assets/8844166/4345873/6d2041ee-40e4-11e4-8ded-764e3ed03b85.png)

**Comment by pizzaicon** [comment]
+1

**Comment by pizzaicon** [comment]
i see a lot of plus one but nobody on the community can do that.. is there a scheduling of requests?
i would like to help but im not expert in graphics.. please help us guys!

**Comment by tagliala** [comment]
@pizzaicon sorry but this is still far from being a popular request and is a rather "new" one.

I should suggest you to consider a custom build of fontawesome. You don't need graphic skills

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

**Comment by WaSa42** [comment]
+1

**Comment by jaypatel512** [comment]
+1 please :) Pretty please.

**Comment by RyanDansie** [comment]
+1

**Comment by joomlolo** [comment]
+1

**Comment by tagliala** [comment]
Adding to 5.0.0 milestone via #1895 
:pizza: 
Note that this could be shifted to a future release

**Comment by G-Driver** [comment]
+1

**Comment by pufanalexandru** [comment]
+1

**Comment by abidin13** [comment]
+1

**Comment by Max-Krieg666** [comment]
+++++

**Comment by gnistdesign** [comment]
+

**Comment by boolean-is-null** [comment]
+1

**Comment by jakeyjdavis** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by luckyagarwal3247** [comment]
+1

**Comment by Derpette** [comment]
+1

**Comment by End18Zone** [comment]
+1

**Comment by Chikanz** [comment]
+1

**Comment by Crissov** [comment]
🍕 [U+1F355](http://emojipedia.org/pizza-slice/) Unicode emoji #2201

**Comment by wellington1993** [comment]
+1

**Comment by paulomcnally** [comment]
+1

**Comment by aaron-hanson** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by kirillmore** [comment]
+1

**Comment by sensibleworld** [comment]
An icon so delicious, we made two versions of it:

https://fontawesome.com/icons/pizza-slice?style=solid
https://fontawesome.com/icons/pizza?style=solid
