### ISSUE TITLE
Icon Request: fa-service

### ISSUE THREAD

**Issue by abdennour** [FortAwesome/Font-Awesome#4498]
Context : Service catalog in IT company (Mail service, Network service, print service ,Hardware service, software service, ... so on)

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
