### ISSUE TITLE
Add drawing Icons

### ISSUE THREAD

**Issue by deepakpol** [FortAwesome/Font-Awesome#450]
It would be good to have drawing icons eg. for different shapes.

**Comment by janvogt** [comment]
Why is this closed? An icon for a bezier curve tool would be very awesome...

**Comment by tagliala** [comment]
Please open a new request following contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
