### ISSUE TITLE
Icon Request: Camera settings

### ISSUE THREAD

**Issue by ontelo** [FortAwesome/Font-Awesome#4508]
It would cool to have camera -setting icons as:
- ISO (just plain ISO text)
- Aperture (Like closing camera lens)
- Focal length (mm text)
- Shutter speed / exposure (Like sun, where timer is in the middle of it)
- Resolution (Like rectangle where lies some dotted diagonal line)
- Zoom (same as above but factor in the middle like 1.2x)

**Comment by flyinliamryan** [comment]
+1

**Comment by metinsenturk** [comment]
+!

**Comment by jabarihunt** [comment]
+! Especially for a shutter!

**Comment by BlackSkorpio** [comment]
Got to say I was surprised that these is not already included in Font Awesome!
Would love to have:

- fa-exif-lens
- fa-exif-aperture
- fa-exif-exposure
- fa-exif-iso
- fa-exif-focallength
- fa-exif-flash
These are the absolute basic and I'm pretty sure that the guys over at Koken.me would love you guys if you could include these...

Me and my friend is actually right now creating the above, and some more, in SVG
If anyone is interested I can include theme here for you to use?

**Comment by nioc** [comment]
+1, I'm interested in these icons too.

**Comment by Mansourali** [comment]
+1

**Comment by tagliala** [comment]
Sorry, I'm going to close this one.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

**Comment by nioc** [comment]
I am not sure that photography is a more specific field than medical :stuck_out_tongue:

**Comment by BlackSkorpio** [comment]
My exact thoughts to, or is it that you want us/me to create a issue for each of the proposed icons?

**Comment by tagliala** [comment]
@BlackSkorpio yes please, having care of +1 existing requests, like #1033

**Comment by tagliala** [comment]
@nioc #150 is closed from the very same reason

https://github.com/FortAwesome/Font-Awesome/issues/150#issuecomment-54458423

**Comment by purzlbaum** [comment]
@tagliala are you considering to reopen this issue? Would be nice to illustrate images with the camera settings.
