### ISSUE TITLE
Icon request: fa-flag-[country name]

### ISSUE THREAD

**Issue by xaoseric** [FortAwesome/Font-Awesome#4516]
Please create a set of flags that can be used as a way to show users what site they are on. 

Ex: a user on example.ca might see a flag of fa-flag-ca, where as a user on example.com would see fa-flag-us which can be used to indicate country specific sites where a user clicks a flag, and they are redirected to a country specific site.

I have found two icon sets, all they would need is the css.

https://github.com/gosquared/flags
http://www.famfamfam.com/lab/icons/flags/

**Comment by erayaydin** [comment]
Hey guys, fontawesome doesn't use png files for show icons. I think using image file is bad think. Please close this issue...

**Comment by tagliala** [comment]
@erayaydin this issue is closed :+1:

**Comment by erayaydin** [comment]
Oh so sorry :smile: How can I miss that, I see `Open` text on #4895 issue and I forget that. So sorry :smiley: 

Thank you again for this **lovely** awesome repo :+1:

**Comment by tagliala** [comment]
Please consider svg based solutions, as http://lipis.github.io/flag-icon-css/

**Comment by rstuart85** [comment]
Has the stance on this changes now that font-awesome has an SVG implementation?
