### ISSUE TITLE
Icon request: icon-firewall

### ISSUE THREAD

**Issue by chad-abizeid** [FortAwesome/Font-Awesome#4519]
Firewall for hosting / technology site

Example:

![3](https://cloud.githubusercontent.com/assets/8635771/4373268/62925034-432b-11e4-8171-33560e163e09.PNG)

**Comment by MatyCZ** [comment]
+1

**Comment by andres314** [comment]
+1

**Comment by ragingprodigy** [comment]
+1

**Comment by asaif** [comment]
+1

**Comment by bartbutenaers** [comment]
+1

**Comment by turtles2** [comment]
1+

**Comment by kelvien** [comment]
+1

**Comment by ThomasSonck** [comment]
+1

**Comment by javieracrich** [comment]
+1

**Comment by adpande** [comment]
+1

**Comment by nkamate** [comment]
+1

**Comment by KingJP** [comment]
+1

**Comment by smyogesh** [comment]
+1

**Comment by ponm** [comment]
+1

**Comment by mmgeo** [comment]
+1

**Comment by dtouzeau** [comment]
+1

**Comment by tdimmig** [comment]
+1
Why the heck is there still not a firewall icon, 5 years after this has been requested?  How did this need requesting in the first place?

**Comment by ekrichbaum** [comment]
+1 still?

**Comment by ilogus** [comment]
+1

**Comment by kobalteule** [comment]
+1
I cannot believe there is no firewall icon yet!

**Comment by defaultsecurity** [comment]
+1

**Comment by mindflayah** [comment]
+1

**Comment by MiloCasagrande** [comment]
+1

**Comment by tommywxd** [comment]
+1

**Comment by KrithinJP** [comment]
+1

**Comment by KondorB** [comment]
I'd like to see a firewall icon too. Hard to believe there isn't one.

**Comment by mpittas** [comment]
+1

**Comment by sensibleworld** [comment]
Just added to the latest v6 beta: https://fontawesome.com/v6.0/icons/block-brick-fire?s=solid

**Comment by ukrainecmk** [comment]
Thread was created on September 23, 2014, - 7 years ago, and I set here +1 on same year, in November. Now I changed a whole carier, moved to another niche of software development. This was a time when my daughter was just learning to talk and walk. Now she already in 3rd grade. And icon is ready! Really nice to get such notifications, keep it going friends from Font Awesome ;)
