### ISSUE TITLE
Icon Request: coderbits

### ISSUE THREAD

**Issue by crumpled** [FortAwesome/Font-Awesome#4530]
Use case: links to profiles on coderbits.com 
![coderbits 20face 20b 26w](https://cloud.githubusercontent.com/assets/1931514/4377299/6e75ed6c-434d-11e4-9338-320d25c34674.png)
I can provide vector art soon. I'm about to shim it into my page using fontello.

**Comment by jucrouzet** [comment]
+1

**Comment by T-Alex** [comment]
+1

**Comment by yangyer** [comment]
+1

**Comment by aethior** [comment]
Coderbits service was discontinued since 2015. (check [domain](https://coderbits.com/) and [twitter account](https://twitter.com/coderbits))

Regards.

cc/ @tagliala
