### ISSUE TITLE
Icon request: fa-ghost

### ISSUE THREAD

**Issue by sparklette** [FortAwesome/Font-Awesome#4533]
icon-ghost can be used for the following:
- Halloween
- Spooky/creepy/mystery genre
- May also represent games if it looks like the iconic Pacman ghost

See attached sample.

![image](https://cloud.githubusercontent.com/assets/7431095/4384644/b4faa3ec-43b9-11e4-9a3a-55e646e561d6.png)

**Comment by stefankutko** [comment]
+1

**Comment by SaphuA** [comment]
+1

**Comment by afloyd** [comment]
+1

**Comment by iJungleboy** [comment]
+1

**Comment by epoberezkin** [comment]
+1

**Comment by JasonBristol** [comment]
+1

**Comment by sensibleworld** [comment]
Boo! https://fontawesome.com/icons/ghost?style=solid
