### ISSUE TITLE
Icon Request: fa-users-coop

### ISSUE THREAD

**Issue by lonerunner** [FortAwesome/Font-Awesome#4541]
I am working on some gaming website and i noticed that there is no icon such as 2 people side by side, it would be good for use as and example as co-op icon or multiplayer icon.

Thanks.

**Comment by tagliala** [comment]
> I added new title, i don't know how better to name it, i tried to match it's purpose.
> 
> Here's an example of what i have in mind
> 
> http://store.akamai.steamstatic.com/public/images/v6/ico/ico_coop.png

This icon is available as `user-friends` starting from FA 5.0.11
https://fontawesome.com/icons/user-friends?style=solid
