### ISSUE TITLE
Icon request: icon-pause-circle-o

### ISSUE THREAD

**Issue by microfuga** [FortAwesome/Font-Awesome#4545]
You already have the fa-play-circle-o, would it be possible to have the pause?

eg bellow:
![screen shot 2014-09-25 at 12 41 57](https://cloud.githubusercontent.com/assets/8639708/4403258/9b5df88e-44a0-11e4-88ef-d377d791988d.png)

We are using these icons for an applicant tracking desktop app where we are now changing from our icons to your font but there is a few that we need and currently they aren't in your collection.

**Comment by tagliala** [comment]
Available in FA5!

https://fontawesome.com/icons/pause-circle?style=regular
