### ISSUE TITLE
Icon request: icon-circle-euro

### ISSUE THREAD

**Issue by microfuga** [FortAwesome/Font-Awesome#4546]
Like the e.g. bellow but instead of dollar symbol, with euro.
![screen shot 2014-09-25 at 12 48 53](https://cloud.githubusercontent.com/assets/8639708/4403341/915b2ef0-44a1-11e4-9978-c7bb1bfc77b4.png)

**Comment by bertoost** [comment]
Please try the Euro sign stacked on a circel.. It's ugly! Not aligned well hehe.

**Comment by tagliala** [comment]
This request is legit, but please keep in mind that **in a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/173/

Ref:

https://fontawesome.com/v6/docs/web/style/power-transform
https://fontawesome.com/docs/web/style/mask
https://fontawesome.com/docs/web/style/layer

**Comment by sensibleworld** [comment]
This icon now exists: https://fontawesome.com/icons/circle-euro?f=classic&s=solid
