### ISSUE TITLE
Icon Request: fa-hryvnia

### ISSUE THREAD

**Issue by brain2dump** [FortAwesome/Font-Awesome#4549]
Hryvnia is official currency of Ukrain. In unicode, the hryvnia sign is U+20B4 ₴.

![196px-hryvnia_symbol svg](https://cloud.githubusercontent.com/assets/3993503/4403837/35b99728-44a9-11e4-838f-a7412779a73b.png)
# Resources:

[https://en.wikipedia.org/wiki/Hryvnia_sign](https://en.wikipedia.org/wiki/Hryvnia_sign)
[http://unicode-table.com/ru/20B4/](http://unicode-table.com/ru/20B4/)

Please add!!
Make love, not war!

**Comment by vadym-rud** [comment]
Please add!!

**Comment by VitaliiCh** [comment]
+1

**Comment by premgrem** [comment]
pls add!!!

**Comment by tagliala** [comment]
locking here, this is a duplicate of #1451
