### ISSUE TITLE
Icon request: icon-blog

### ISSUE THREAD

**Issue by andrefs** [FortAwesome/Font-Awesome#455]
It would be nice to have a icon-blog in font-awesome. I think that the main problem is the lack of a standard blog icon; however, there are some suggestions (http://theblogicon.com/ and http://goo.gl/jtJT3) which could be used.

**Comment by bigegodesign** [comment]
+1 this one is rather pressing i would think .. pls ?

**Comment by damion117** [comment]
+1 - was surprised to find that this isn't in there already

**Comment by haferje** [comment]
+1

**Comment by mayinx** [comment]
+1

**Comment by nealfennimore** [comment]
+1

**Comment by jcbadger** [comment]
+1

**Comment by xuv** [comment]
:+1:

**Comment by M-Zuber** [comment]
:+1:

**Comment by N1ghteyes** [comment]
+1 for this

https://cloud.githubusercontent.com/assets/6233847/7477695/c1d3059c-f312-11e4-9642-fc536cf7c9ba.png
![image](https://cloud.githubusercontent.com/assets/5121074/8497795/05badcb0-2178-11e5-8a7a-fd17473ff422.png)

**Comment by SammyHerring** [comment]
+1

**Comment by earthgirlllc** [comment]
+1 ~ more & more ecommerce platforms use a built-in blog and a quick visual reference would be <3ed

**Comment by GonzoRibbons** [comment]
+1

**Comment by zarfmouse** [comment]
+1

**Comment by Kiloreux** [comment]
+1

**Comment by webappdesigner** [comment]
+1000... 

One of the most important aspects of the internet, yet no blog icon... 

?????

**Comment by N8Solutions** [comment]
+1  Would love to have this as an icon choice!

**Comment by wizzofoz** [comment]
+1

**Comment by Imperial777** [comment]
+1

**Comment by jpswade** [comment]
@tagliala surely there's been enough feedback on this now?

**Comment by tagliala** [comment]
@jpswade sorry but I'm not in charge of implementing icons :(

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome you will find a link to the most popular requests. This request is on the fourth page

**Comment by lukemcd** [comment]
+1

**Comment by jleee** [comment]
+1

**Comment by burrellramone** [comment]
+1

**Comment by Mouro001** [comment]
+1

**Comment by onrea** [comment]
+1

**Comment by briansanchez** [comment]
+1

**Comment by RolfVeinoeSorensen** [comment]
+1

**Comment by 0xcrypto** [comment]
+1

**Comment by loorlab** [comment]
+1

**Comment by mohamedhafezqo** [comment]
+1

**Comment by vg** [comment]
+1

**Comment by jungheelee** [comment]
+1

**Comment by wudongyuan** [comment]
+1

**Comment by pjazdzewski1990** [comment]
+1
Any progress on this one?

**Comment by tillifywebb** [comment]
+1

**Comment by davecthomas** [comment]
+1

**Comment by erezLieberman** [comment]
+1

**Comment by jtosey** [comment]
+1

**Comment by joshferrara** [comment]
+1

**Comment by Sea-n** [comment]
+1

**Comment by revandyr** [comment]
+1

The icon suggested by brainscript on Sep 11, 2014 would be perfect!

**Comment by jharmn** [comment]
:shipit: :+1:

**Comment by jarekbb** [comment]
:+1:

**Comment by wiiiiilllllll** [comment]
:+1:

**Comment by saradbowman** [comment]
+1

**Comment by Eduruiz** [comment]
:+1:

**Comment by amygatt** [comment]
+1

**Comment by mfortin** [comment]
+1

**Comment by VarunBatraIT** [comment]
+1

**Comment by markwooff** [comment]
+1

**Comment by sjdaniell** [comment]
+1

**Comment by elric-dev** [comment]
+1

**Comment by nobreferreira** [comment]
+1

**Comment by naturtrunken** [comment]
+1

**Comment by ston3o** [comment]
+1

**Comment by drobyshev** [comment]
+1

**Comment by konradhojda** [comment]
+1

**Comment by briansanchez** [comment]
+1

**Comment by aditya-a-patil** [comment]
+1

**Comment by leighennelevi** [comment]
+

**Comment by joakimlustig** [comment]
+1

**Comment by antuki** [comment]
+1

**Comment by toubou91** [comment]
Could we somehow prioritize this?
I can help if you want.

**Comment by N8Solutions** [comment]
As was mentioned above @theblogicon would be perfect for this!
https://twitter.com/theblogicon

Brendan Mitchell registered TheBlogIcon at Creative Commons as Attribution-ShareAlike
https://twitter.com/brendanmitchell/status/491980914281705472

Not much more work needs to be done to integrate this in to the icons. I think it would be a perfect addition!

**Comment by Wingo5315** [comment]
+1

**Comment by BonBonSlick** [comment]
+1

**Comment by hjalves** [comment]
+1

**Comment by gameFace22** [comment]
+1
is this icon getting pushed?

**Comment by Kokil** [comment]
+1

**Comment by djanym** [comment]
+1

**Comment by nonlefthanded** [comment]
+1

**Comment by oxguy3** [comment]
The Attribution-ShareAlike license on the blog icon is incompatible with the Attribution license that Font Awesome uses.

**Comment by LeonAppDev** [comment]
+1, please

**Comment by barabadam** [comment]
+1 blog icon for sure

**Comment by AmberJune** [comment]
+1
A generic blog icon for self-hosted blogs would be great.

**Comment by sensibleworld** [comment]
Finally, something to write about: 
https://fontawesome.com/icons/blog?style=solid
