### ISSUE TITLE
Icon Request : fa-warehouse

### ISSUE THREAD

**Issue by dexter143d** [FortAwesome/Font-Awesome#4560]
![warehouse-512 1](https://cloud.githubusercontent.com/assets/5464257/4416275/5bf514f4-453e-11e4-9991-e52b7d22f90d.png)

I would really like to see "warehouse icon" in font awesome because currently only fa-home icon is there which is designed well to represent home.. but we can't use as stock or warehouse icon.

**Comment by stijnvanbael** [comment]
+1

**Comment by escribanoruben** [comment]
+1

**Comment by buerogummi** [comment]
+1

**Comment by weedget** [comment]
+1

**Comment by psonic** [comment]
+1

**Comment by jgodoi** [comment]
+1

**Comment by JoseDguez** [comment]
+1

**Comment by jbwl** [comment]
+1

**Comment by blinkibill** [comment]
+1

**Comment by luktomczuk** [comment]
+1

**Comment by Xeronel** [comment]
+1

**Comment by sourire123** [comment]
+1

**Comment by adduss** [comment]
+1

**Comment by zeespogeira** [comment]
+1

**Comment by hCarmitchel** [comment]
+1

**Comment by chowdarybobby** [comment]
+1

**Comment by warwick-schaffer** [comment]
+1 This would be a good icon but if you wanted to make a more generic icon that could be used for warehouse stock situations a pile of boxes would also work. This could be used more easily up and down the supply chain to signify stock status. 
<img width="53" alt="screen shot 2017-08-25 at 9 01 56 am" src="https://user-images.githubusercontent.com/1037535/29688508-244b8010-8974-11e7-8147-5c09d4e35b15.png">

**Comment by lalabili** [comment]
+1

**Comment by amirzaghari** [comment]
+1

**Comment by FranciscoHanna** [comment]
+1

**Comment by alpsaral** [comment]
+1

**Comment by sensibleworld** [comment]
This is included in our 5.0.7 release: https://fontawesome.com/icons?d=gallery&q=warehouse
