### ISSUE TITLE
Icon Request: fa-origin fa-uplay fa-desura fa-psnetwork

### ISSUE THREAD

**Issue by lonerunner** [FortAwesome/Font-Awesome#4569]
So far i found only fa-steam icon added to the fonts, but it would ne great if other networks also can be added to the list like 

Origin
Uplay
Desura
Playstation network

There is also
Xbox network but i have seen a request for that already

And 
Games for windows live but they are shutting down so i think no point in adding this.

Thanks.

**Comment by mcbyte-it** [comment]
+1 for fa-desura
+1 for fa-origin

**Comment by dalfaand** [comment]
stiil waiting for this icons 👍 
and fa-xbox
