### ISSUE TITLE
Icon Request: fa-bebo

### ISSUE THREAD

**Issue by ThePixelPixie** [FortAwesome/Font-Awesome#4570]
I've not found a previous request for this icon, so I hope I didn't miss it somewhere.  In any case, I'd like to have this icon available.

bebo.com

**Comment by aethior** [comment]
>We tried our best to resurrect Bebo. To create something new and fresh. But perhaps it wasn't new or fresh enough. This has been a fun project built during the pandemic, but sadly it must be sunsetted. We are grateful to everyone who joined us on this journey. Your support is greatly appreciated. Will Bebo rise again? Who knows. It has now lived four times, been sold twice. Hmm. It's been emotional. _Michael Birch_ ([source](https://bebo.com/))

cc/ @tagliala
