### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by rhmukul** [FortAwesome/Font-Awesome#4575]
Please add new icon for sell as fa-sell ,buy as fa-buy (it should be a shopping bag), medal as fa-medal (it should be gold,silver,bronze)

Thank you
Md. Rokibul Hossain

**Comment by khoshrou** [comment]
+1
also add fa-pay for the concept of a payment.
fa-sell
fa-buy
fa-pay
very good for a shopping center app.

**Comment by tagliala** [comment]
closing here. no feedback, request doesn't meet contributing guidelines
