### ISSUE TITLE
Icon Request: fa-fullscreen (youtube style) (expand-wide)

### ISSUE THREAD

**Issue by aakash-cr7** [FortAwesome/Font-Awesome#4576]
Please add icons for full screen mode in Video Player Icons as fa-fullscreen 

![fullscreenmode](https://cloud.githubusercontent.com/assets/7534680/4435684/768834ca-4752-11e4-85e1-3da271c21c1a.jpg)

**Comment by jzelez** [comment]
+1

**Comment by rakeshok** [comment]
+1

**Comment by welligton1993** [comment]
+1

**Comment by bjtalbot1** [comment]
+1 for the YouTube style

**Comment by briandegenhart** [comment]
+1

**Comment by helderburato** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by cedrikv** [comment]
+1

**Comment by mahendra-alladi** [comment]
+1

**Comment by droplab** [comment]
+1

**Comment by atilkan** [comment]
+1. And name it full-screen. arrows-alt is irrelevant.

**Comment by webspas** [comment]
+1!!!

**Comment by hitchhiker** [comment]
Is this happening or?

**Comment by Elephant-Vessel** [comment]
+1, and one corresponding one to disable full-screen as well of course.

**Comment by Stadler76** [comment]
+1, and what Elephant-Vessel said :-)

**Comment by kutlik-cr-consult** [comment]
+1

**Comment by trikadin** [comment]
+1

**Comment by FuzzySockets** [comment]
+1

**Comment by shurub3l** [comment]
+1

**Comment by RandomDude777** [comment]
+!

**Comment by pkoretic** [comment]
+1

**Comment by fraserr** [comment]
+1

**Comment by Tigralt** [comment]
+1

**Comment by CharlyJazz** [comment]
1+

**Comment by XAMelleOH** [comment]
+1

**Comment by ydogus** [comment]
+1
I think this one should be added after all those recent icons

**Comment by MrFahey** [comment]
+1

**Comment by shaikansaar** [comment]
+1

**Comment by fabioricali** [comment]
+1

**Comment by dsalunga** [comment]
+1

**Comment by amrocs** [comment]
+1

**Comment by ndri** [comment]
+1 how is this not a thing yet

**Comment by Llorx** [comment]
+1 and what @ndri said xD

**Comment by Vohidjon** [comment]
+1

**Comment by brambo48** [comment]
+1

**Comment by justingolden21** [comment]
+1

**Comment by pedro-valentim** [comment]
+1

**Comment by NicksonYap** [comment]
+1

**Comment by NeckersBOX** [comment]
+1

**Comment by rfxdev** [comment]
+1

**Comment by williamswgb** [comment]
+1

**Comment by ergonomicus** [comment]
+1 (I just couldn't resist :)

**Comment by landowskitomasz** [comment]
+1

**Comment by Filip9696** [comment]
+1
(wow this thread is like 2 years old)
[this looks similar tho](https://fontawesome.com/icons/expand?style=solid)

**Comment by rfxdev** [comment]
Good spot, this is new in version 5. There is also [Expand Wide](https://fontawesome.com/icons/expand-wide?style=regular) as part of the pro set

**Comment by tagliala** [comment]
Hi, I'm going to close here because this icon is available in the Pro set

**Comment by RandomDude777** [comment]
We win!

**Comment by tnethers** [comment]
Maybe I'm missing something, but I see fa-arrows-alt but no such thing as the youtube kind that looks like the edges of a box, not the pointing arrows. What is the fa-name for the youtube version? I don't think the issue is closed correctly. @tagliala
