### ISSUE TITLE
Font icons don't show in IE8 via HTTPS

### ISSUE THREAD

**Issue by RickyJiao** [FortAwesome/Font-Awesome#4580]
I have a project A needs to reference font-awesome on other server. We already setup everything(CSS file, font location, CORS header). Everything works fine in IE8 via HTTP. However, when we switch to HTTPS, the icons are gone. Nothing is shown. I checked the style via F12 tool and fiddler, everything is loaded. 

Previously, I think this issue may be caused by cross domain, and then I copy the style/font to project A machine. The issue still happen. I googled and find this stackoverlfow link has the same issue with me: http://stackoverflow.com/questions/22670026/font-awesome-with-https

I followed the link, no matter I remove the cache header or not, the issue still happen. Also, I access the font-awesome site by IE8 via HTTP/HTTPS. Everything is OK for HTTP, but for HTTPS, no icon is shown. Below are screen shots:

![http-ie8](https://cloud.githubusercontent.com/assets/2752033/4437316/091d6798-4793-11e4-9d74-63d99ebfd78f.PNG)
![https-ie8](https://cloud.githubusercontent.com/assets/2752033/4437317/091e0a5e-4793-11e4-8701-50ff111a08dc.PNG)

The virtual machine I used is: Win Server 2003 and IE8. And the font-awesome I used is: 4.1.0

**Comment by tagliala** [comment]
I'm going to close here.

As far as we know, this could be caused by a configuration option in pragma header

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up
