### ISSUE TITLE
Icon Request: fa-IMDb

### ISSUE THREAD

**Issue by rohitgaur** [FortAwesome/Font-Awesome#4591]
Dear fantastic team, 

I would like to request you to create a icon for imdb.com. It is popular among film industry. 

I am using a template named BRIDGE, from themeforest. They told me they can't create the icon, because they use yours. So it will only be available if you add it to your new icon database.

Thank you for your consideration,

cheers,
![imdb_logo](https://cloud.githubusercontent.com/assets/8959270/4442413/ff1af0ca-47de-11e4-88da-
![imdb_icon]%28https://cloud.githubusercontent.com/assets/8959270/4442416/05632704-47df-11e4-87f5-389155d44df7.gif%29
e61c35427658.jpg)

**Comment by pozharlab** [comment]
+1
