### ISSUE TITLE
Icon request: fa-billboard

### ISSUE THREAD

**Issue by vegasls** [FortAwesome/Font-Awesome#4599]
Hi,

Is it possible to create this billboard icon??

![billboard-512](https://cloud.githubusercontent.com/assets/8967986/4453842/22ce5058-4865-11e4-90f3-47bf68b18b3b.png)

![icon-billboard](https://cloud.githubusercontent.com/assets/8967986/4453792/4dfa0566-4864-11e4-8b92-4bfe5a230587.png)

Thanks!!

**Comment by iftikharuddin** [comment]
Thanks for suggesting, please add it @fontawesome

**Comment by brunoslalmeida** [comment]
+1 . Was looking for this also.

**Comment by oriadam** [comment]
The presentation icon with a single leg can do the trick:

![image](https://user-images.githubusercontent.com/2786617/133931502-a83f58b7-97a6-4cdf-941b-d1d42cec96ce.png)
or
![image](https://user-images.githubusercontent.com/2786617/133931563-7a353da1-ec82-487a-92a9-7f49ad959a5c.png)

**Comment by dejavoodooo** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/billboard?f=classic&s=solid
