### ISSUE TITLE
Icon Request: fa-cc-taobao

### ISSUE THREAD

**Issue by jacksonwj** [FortAwesome/Font-Awesome#4600]
Single color logo like this:
![2014-09-30_181607](https://cloud.githubusercontent.com/assets/61455/4456719/9768f9a4-488d-11e4-8b5c-2588ed1e31f1.png)

Thanks

**Comment by weihongyu12** [comment]
#3856

**Comment by tagliala** [comment]
@weihongyu12 are #3856 and #4600 the same request?

AFAIK, this a request for a credit card form factor icon

**Comment by weihongyu12** [comment]
@tagliala Yes, this is the same brand. #4600 is the full name, #3856 is the first word is the abbreviation, we often use the abbreviation when making icons, the official APP does the same.

**Comment by tagliala** [comment]
@weihongyu12 thanks for the clarification. Closing here in favour of #3856
