### ISSUE TITLE
Icon Request: fa-american-football

### ISSUE THREAD

**Issue by aakash-cr7** [FortAwesome/Font-Awesome#4602]
Icon for american football.

![american-football-ball-icon](https://cloud.githubusercontent.com/assets/7534680/4458818/4da410d8-48a6-11e4-98f8-b5c6db85b779.png)

**Comment by maziak** [comment]
+1

**Comment by kevbodavidson** [comment]
+1

**Comment by Buceador** [comment]
+1

**Comment by r5smith** [comment]
+1

**Comment by lickmydesign** [comment]
+1

**Comment by davegandy** [comment]
We've added `fa-football-ball` to 5.0.5 in 3 different styles. The Solid style is a part of FA Free:
https://fontawesome.com/icons/football-ball?style=solid

For naming consistency and guessability, we're naming with a US-centric consistency. Not my favorite approach, but it seems the best as each country has such different connotations and complexities we won't understand. We get the US well enough, so we're going with that perspective.

(`fa-futbol` will be renamed in a future release to `fa-soccer` to keep up with this consistency. Again, not my favorite way to do things, but I don't see a better way that's consistent and guessable.)
