### ISSUE TITLE
Icon Request: fa-soccer-pitch

### ISSUE THREAD

**Issue by aakash-cr7** [FortAwesome/Font-Awesome#4607]
![sport-football-pitch-icon](https://cloud.githubusercontent.com/assets/7534680/4464052/683cadf4-48d0-11e4-90ec-b73a1b1a4213.png)

**Comment by aethior** [comment]
Duplicate of #1415.

cc/ @tagliala

**Comment by tagliala** [comment]
Good catch, thanks
