### ISSUE TITLE
Icon request: icon-fullscreen needs an inverse

### ISSUE THREAD

**Issue by mblase75** [FortAwesome/Font-Awesome#461]
We have four arrows expanding from the center to four corners (that's icon-fullscreen), and we have two arrows from opposite corners to the center (that's icon-resize-small), but we should also have something like "icon-inverse-fullscreen", four arrows from the corners to the center.

**Comment by tagliala** [comment]
fff

closing this in favour of #1468 which has more +1s

No need to +1 that request, I will do it for you

**Comment by sieira** [comment]
See this https://github.com/FortAwesome/Font-Awesome/issues/1468
