### ISSUE TITLE
Icon Request: icon-card (icon-rectangle-v)

### ISSUE THREAD

**Issue by aakashtyg** [FortAwesome/Font-Awesome#4621]
![footballcard](https://cloud.githubusercontent.com/assets/7534680/4478561/8e5ced76-4986-11e4-91d1-18cb7d2dfe7f.jpg)
## 

edit by @tagliala

This is about a simple card, without the hand

**Comment by micheleangioni** [comment]
:+1: for cards and soccer cards!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cards?f=classic&s=solid
https://fontawesome.com/icons/cards-blank?f=classic&s=solid
https://fontawesome.com/icons/rectangle-vertical?f=classic&s=solid
