### ISSUE TITLE
Icon request: icon for payment in cash

### ISSUE THREAD

**Issue by xp24** [FortAwesome/Font-Awesome#4633]
fa-cc-cash

**Comment by 4bdulll4** [comment]
i think fa-money does not look so good. plus, it doesn't fit for so many stuff. like, i want to represent saving money or something cheap.

**Comment by tagliala** [comment]
represent saving money: -> #1413

**Comment by CSD-studio** [comment]
![get-money2](https://cloud.githubusercontent.com/assets/14673343/10088440/7f59d5c0-6323-11e5-8290-9d2d4012d50a.png)

**Comment by sensibleworld** [comment]
We have a lot of new options for "money" icons: https://fontawesome.com/search?q=money&o=r&s=solid&f=classic
