### ISSUE TITLE
Icon request: icon-umbraco

### ISSUE THREAD

**Issue by WoutK** [FortAwesome/Font-Awesome#4637]
I would love to see the Umbraco logo added.
As a webdesigner we often use the umbraco CMS system. With this icon we would be able to show the user and possible clients what CMS system was used to create the website.

![image](https://cloud.githubusercontent.com/assets/8511499/4492628/dda7ac6a-4a42-11e4-9ad0-0ae7005fa470.png)

I hope this is enough information and i hope this is possible to add to the awesome font list of icons already available.

**Comment by dannykelly86** [comment]
Think this would be handy as use font awesome a lot and the only downside that I can see so far is that it is missing the umbraco one :)

**Comment by jacklawry** [comment]
+1 Yes please add this icon - Umbraco is great and so is Font Awesome!

**Comment by alikazai** [comment]
Would Love for this to happen.

**Comment by johnseto** [comment]
this would be great especially with the popularity of Umbraco and it's an open source product

**Comment by tom-ingeniuus** [comment]
+1

**Comment by nielslyngsoe** [comment]
Hi everyone, to help get this icon approved we need to get as many likes on this issue as possible, so please help us gather as many possible.
Thanks

**Comment by readingdancer** [comment]
@nielslyngsoe I've tweeted this ( https://twitter.com/readingdancer/status/1144249123547361284 ) and added it to the public Umbraco group on Facebook, hopefully that will help a little https://www.facebook.com/groups/202933450108554/

**Comment by zBestData** [comment]
We are voting Yes! We are FontAwesome Pro Subscribers and use  Umbraco as a part of our Real Estate Platform.

**Comment by jezmaghuyop** [comment]
+1

**Comment by OwainWilliams** [comment]
+1

**Comment by redmorello** [comment]
Another vote from me !!

**Comment by karlrsk** [comment]
+1

**Comment by emmagarland** [comment]
+1 also

**Comment by fresh-caffeine** [comment]
+1

**Comment by sumeshkp18** [comment]
We love Umbraco.... 😍

+1

**Comment by kristianschneider** [comment]
+1

**Comment by spideywebdesign** [comment]
+1

**Comment by nathanwoulfe** [comment]
+1

**Comment by clauskrist** [comment]
+1

**Comment by Matthew-Wise** [comment]
+3

**Comment by prjseal** [comment]
+1

**Comment by UnitStack** [comment]
+100

**Comment by larsskjoldiversen** [comment]
This would be awesome!
+1000

**Comment by ravimotha** [comment]
Consider this an upvote +1

**Comment by alikazai** [comment]
+1

**Comment by SemanticMikeG** [comment]
Yes please! +1

**Comment by nwahlberg** [comment]
Definitely +1 for this request. Umbraco deserves representation in these icon packs. It's an open source project and popularity is growing fast!

**Comment by rhealefever** [comment]
+1

**Comment by lssweatherhead** [comment]
+1 from me

@nielslyngsoe are we aiming for a particular number of likes?

**Comment by OptimisticCoder** [comment]
+1

**Comment by nielslyngsoe** [comment]
@lssweatherhead I do not know — As far as I understand it's a question of attention compared to the other Icon PRs.

**Comment by SjorsHartwijk** [comment]
+1

**Comment by sensibleworld** [comment]
This icon is now available in 5.11: https://fontawesome.com/icons/umbraco?style=brands
