### ISSUE TITLE
fa-square and fa-square-o do not have the same dimensions

### ISSUE THREAD

**Issue by acshef** [FortAwesome/Font-Awesome#4649]
Is there a reason that the `fa-square` (and its variants like `fa-plus-square` and `fa-minus-square`) has slightly different dimensions from `fa-square-o` (and its variants)?

See http://jsfiddle.net/45h2g1os/3/ for a quick and dirty example. This difference means one cannot simply "switch out" the characters for certain visual feedback, (like when hovering over a button, switching from the outline version to the solid version) without a noticeable change in dimension.

Or perhaps is there a better method of using the `fa-square` family?

**Comment by shehi** [comment]
+1

**Comment by shehi** [comment]
May I ask why this bug should remain in 4.* line and be carried to 5.0 milestone, whereas it could be fixed with one simple PR? Are you guys afraid of BC complications?

**Comment by tagliala** [comment]
> whereas it could be fixed with one simple PR?

Dave made a design choice of implementing all icons by himself, so there could not be PRs implementing new icons / fixing existing icons

> Are you guys afraid of BC complications?

In this specific case yes, I'm considering this a breaking change

**Comment by tagliala** [comment]
Hi,

I've checked all non-brands square icons and they have all the same shape, except of `share-square`, which is pretty different in design and it should have a different name, IMHO

Anyway, I'm going to close this, it's fixed to me!
