### ISSUE TITLE
Icon Request: tree-deciduous

### ISSUE THREAD

**Issue by squarefootllc** [FortAwesome/Font-Awesome#4670]
It would be really nice to have a deciduous tree to go along with the pine tree you already have. Could use it for several projects. Thanks for considering.

**Comment by skydiva** [comment]
I'm having problems accessing the fa-tree file in both the font-awesome.css / font-awesome.min files. Any help would be appreciated. Supposedly there is a fa-tree @http://fontawesome.io/icon/tree/ but I can't pull it up through the css.
Thanks for any help!

**Comment by aethior** [comment]
Hi @squarefootllc,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/tree-deciduous

Regards.

**Comment by aethior** [comment]
Hi @squarefootllc,

This icon was added in v5.0.0.
Check https://fontawesome.com/icons/tree-deciduous

Regards.

cc/ @tagliala
