### ISSUE TITLE
Icon request: icon-cheque

### ISSUE THREAD

**Issue by ronnieoverby** [FortAwesome/Font-Awesome#468]
You have a credit card. How about a cheque (those old paper things that people used to use to transfer money) icon?

Thanks!

**Comment by natan88** [comment]
+1

**Comment by sensibleworld** [comment]
Available in FA 5: https://fontawesome.com/icons?d=gallery&q=money-check
And some alternates coming soon: <img width="492" alt="Screen Shot 2019-03-20 at 3 33 49 PM" src="https://user-images.githubusercontent.com/529604/54713680-90663000-4b25-11e9-9c17-91bac81b53b6.png">
