### ISSUE TITLE
Missing "http:" in BootstrapCDN under Getting Started

### ISSUE THREAD

**Issue by judyn** [FortAwesome/Font-Awesome#4686]
Hi there! I'm new to GitHub (and web dev/design in general), so I apologize if this has already been mentioned or isn't even an issue. 

The BootstrapCDN under the "EASIEST" section doesn't work locally unless "http:" is added before the link to maxcdn. I know it's added automatically online, but it seems like it would be easier to include "http:" for those who want to use your icons locally.

Getting Started link: http://fortawesome.github.io/Font-Awesome/get-started/

Hope that makes sense. Thanks!

**Comment by davegandy** [comment]
Yep. We'll update this in the next version. We were using a protocol relative URL (http://www.paulirish.com/2010/the-protocol-relative-url/), but there's not much reason to skip HTTPS (but there definitely is sometimes).

**Comment by tagliala** [comment]
closing because of #6955

I would use `https://`, then if someone has special needs could switch back to `//`
