### ISSUE TITLE
icon request: fa-contacts

### ISSUE THREAD

**Issue by tekamolo** [FortAwesome/Font-Awesome#4692]
It would be useful to use an icon contact such as the one in facebook, but initially made popular by messenger:

![msn_messenger_7 0 2-425263-1292555719](https://cloud.githubusercontent.com/assets/1892789/4559349/14d32f00-4eeb-11e4-847c-bf75deeeb5a2.jpg)

note that the one on facebook has the big head on the left.

There is already the fa-users or the fa-group(alias) that represents something similar but this one would be used for groups instead of contacts which is quite different.

A lot of social networks are going to use this if that makes sense.

Thanks a lot for the good work

**Comment by moumitan3** [comment]
Hi this is moumita. My mail id is moumitan3@gmail.com. I would like to know the price for making new custom icons. Please drop me a mail for the details
