### ISSUE TITLE
Icon Request: fa-level-right

### ISSUE THREAD

**Issue by Perchpole** [FortAwesome/Font-Awesome#4693]
I'd like to request a "level-down-right" icon. It could join the family of the existing "level-down" and "level-up" icons.

It would look like the mirror of the return key on a keyboard...
![fa-level-down-right](https://cloud.githubusercontent.com/assets/9081262/4559727/c0e97a58-4eee-11e4-8756-4d002333b371.png)
This icon would be perfect for showing sub-items or sub-categores in a list or nested menu.

**Comment by COConsulting** [comment]
Ditto on this request. 

I love the list of directional icons you currently have, but there are a few others that would be very helpful. Searching for images in Google, I found this group of images that would be great. http://png.clipart.me/graphics/previews/194/thin-line-arrow-icons-set_194967380.jpg

Of course some of these are already available, and others would not need the circle included as we could use "fa-circle" to create the same result. But, I am in the same boat as Perchpole and QuantumSuicide070 here and could really use a fa-level-right in a current project I am working on. 

Thanks you guys for your huge help. These icons are invaluable with designing flat, responsive and fast loading web designs.

**Comment by COConsulting** [comment]
Ditto on this request. 

I love the list of directional icons you currently have, but there are a few others that would be very helpful. Searching for images in Google, I found this group of images that would be great. http://png.clipart.me/graphics/previews/194/thin-line-arrow-icons-set_194967380.jpg

Of course some of these are already available, and others would not need the circle included as we could use "fa-circle" to create the same result. But, I am in the same boat as @Perchpole and @QuantumSuicide070 here and could really use a fa-level-right in a current project I am working on. 

Thanks you guys for your huge help. These icons are invaluable with designing flat, responsive and fast loading web designs.

**Comment by maladeeb** [comment]
+1

**Comment by aethior** [comment]
Hi @Perchpole,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/turn-down-right

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to the Pro set.

**In a web application** it is possible to create the requested icon by rotating `fa-turn-up`

Demo: https://jsfiddle.net/tagliala/bfa6uhse/104/

Ref:
https://fontawesome.com/docs/web/style/rotate
