### ISSUE TITLE
Icon request: icon-bathroom

### ISSUE THREAD

**Issue by valentinzaraf** [FortAwesome/Font-Awesome#4698]

**Comment by antonvanhooydonk** [comment]
+1 for this request
Icon Name: icon-bathroom
Look: bathtub with a showerhead
Use cases: real estate, hotel

Please and thank you!

**Comment by SamerX** [comment]
+1

**Comment by laviku** [comment]
What would be the difference between toilet and bathroom? 

https://cdn1.iconfinder.com/data/icons/hotel-and-restaurant-line-icons-vol-2/64/053-128.png

**Comment by tagliala** [comment]
Sorry I still don't get this request.

It may be a water closet as pointed out by @laviku , it could be a toilet sign (in this case, duplicate of: #2670)

I'm going to close this one. Feel free to open a new request with an example
