### ISSUE TITLE
Suggestion for Node / Browserify

### ISSUE THREAD

**Issue by mattdesl** [FortAwesome/Font-Awesome#4700]
It would be pretty cool if we could require the font-awesome css as a string for use in Node / Browserify. For example, in Node it might be useful to [parse the css](https://github.com/reworkcss/css-parse) or use it in some other fashion offline/server-side. For browserify, it would be ideal for something like `insert-css`. So your browserify code could look like this:  

``` js
var fontcss = require('font-awesome')
require('insert-css')(fontcss)

//.. now run app ..//
```

**Comment by tagliala** [comment]
I think this is done, there are official npm packages  :)
