### ISSUE TITLE
Icon Request: fa-file-vector

### ISSUE THREAD

**Issue by zlatko-micic** [FortAwesome/Font-Awesome#4702]
It would be nice to have for 2D or 3D vector graphics files, such as those listed here http://en.wikipedia.org/wiki/Image_file_formats#Other_2D_vector_formats

**Comment by rvanhaalen** [comment]
Hello, 
There is no 3d file icon yet that would be very nice as slatko-micic is also mentioning

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-vector?f=classic&s=solid
