### ISSUE TITLE
Request: List of Icons Added Between Versions 3.2.1 and 4.2.0

### ISSUE THREAD

**Issue by diegocanal** [FortAwesome/Font-Awesome#4703]
Hi,
Although I've searched thoroughly I can not find a list or lists of the new icons added between [version 3.2.1](http://fortawesome.github.io/Font-Awesome/3.2.1/icons/#new) and [version 4.2.0](http://fortawesome.github.io/Font-Awesome/icons/#new)

Best Regards
Diego

**Comment by cssjidi** [comment]
+1
