### ISSUE TITLE
Icon Request: fa-cassette-tape

### ISSUE THREAD

**Issue by sixty8** [FortAwesome/Font-Awesome#4704]
Icons Request: fa-cassette-tape for the new kaseta.co site
we need the fa-cassette-edit (fa-cassette-create), fa-cassette-explore, fa-cassette-recent, fa-cassette-design, fa-cassette-top,fa-cassette-views, fa-cassette-playing, fa-cassette-recommended... ;-)

**Comment by olya-gary** [comment]
+1
