### ISSUE TITLE
Icon Request: fa-pledgie

### ISSUE THREAD

**Issue by nicklleite** [FortAwesome/Font-Awesome#4709]
Would be great

**Comment by cvsguimaraes** [comment]
+1

**Comment by aethior** [comment]
>Pledgie was a donation website created by Mark Daggett and Garry Dolley that ran on the Ruby on Rails web application framework. (...) The website has been discontinued in January 2018. ([more info](https://en.wikipedia.org/wiki/Pledgie))

cc/ @tagliala
