### ISSUE TITLE
Icon request - Cartoon Robot

### ISSUE THREAD

**Issue by danieldrave** [FortAwesome/Font-Awesome#4715]
Hi there,

It would be really cool if we could get an icon that's like a fun robot or robot's head.

Very much like the robot Google uses for it's 404 pages. That sort of cartoony style. 

http://www.google.co.uk/imaeges 

Would really love one of those, keep up the good work I love Font Awesome! :)

**Comment by justintconroy** [comment]
+1

**Comment by tagliala** [comment]
Could this be considered a duplicate of #519 ?

**Comment by tagliala** [comment]
Closing here, considering this a duplicate of #519.
