### ISSUE TITLE
fa-history is not showing as a class

### ISSUE THREAD

**Issue by Aloel** [FortAwesome/Font-Awesome#4719]
Using HTML 5
tried i class="fa fa-history" inside an href tag. the broken fi 08 box shows instead
"fa-paper-plane" nor  "fa-paper-plane-o" work either

Other fa classes, so far, work as expected

**Comment by episodeyang** [comment]
I encountered the same bug all the way up to 4.0.3

However, the bug is fixed with the 4.2.0 release on bower. 

Thanks @Aloel , your issue at least made me aware that I am not a lone:)
