### ISSUE TITLE
Icon request: icon-speaker-podium

### ISSUE THREAD

**Issue by Mab879** [FortAwesome/Font-Awesome#472]
icon-podium

**Comment by jpsantos7** [comment]
+1

**Comment by monika-aashe** [comment]
+1 
Here is an image if it helps
![podium-512](https://cloud.githubusercontent.com/assets/15214797/12305061/d72c292c-ba00-11e5-86cc-51cb35283a93.png)

**Comment by leesmith** [comment]
![apple-keynote](https://user-images.githubusercontent.com/90055/42842204-243b5956-89d2-11e8-8ffc-9cf277019427.png)

Speaker, presenter, podium, etc.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/podium?style=solid
https://fontawesome.com/icons/keynote?style=solid
