### ISSUE TITLE
Icon request: fa-duck

### ISSUE THREAD

**Issue by bmorse** [FortAwesome/Font-Awesome#4721]
I am developing a website for a public library system and would like to have some category classifications icons for programs.

Bottom Left icon

http://www.thinkstockphotos.in/image/stock-illustration-basic-baby-icons/162238509

**Comment by cvuorinen** [comment]
+1

**Comment by ramsey** [comment]
:+1:

**Comment by nounoursheureux** [comment]
+1

**Comment by demidovsky** [comment]
+1

**Comment by mredman** [comment]
+1 just trying to get my ducks in a row, but have no ducks

quack

**Comment by MonsieurV** [comment]
+1 Would be so great!

**Comment by HoffmannP** [comment]
+1

**Comment by pavlovskyarto** [comment]
+12

**Comment by geraldhiller** [comment]
+13

**Comment by rodolfobubb** [comment]
+14

**Comment by angelali** [comment]
+15

**Comment by kmacnamara** [comment]
+16

**Comment by lakefield** [comment]
+1

**Comment by thclark** [comment]
+1

**Comment by sensibleworld** [comment]
A duck just quacked it's way into Font Awesome Pro: https://fontawesome.com/icons/duck?style=solid
