### ISSUE TITLE
Icon request: Apple Pay

### ISSUE THREAD

**Issue by epistrephein** [FortAwesome/Font-Awesome#4729]
Since Apple Pay is about to be deployed, an icon for this service would be great.

**Comment by rlmckenney** [comment]
This is the Apple Pay logo ... 

![Image of Apple Pay logo]
(https://www.apple.com/v/apple-pay/b/images/apple_pay_logo_large.png)

And with the Stripe API supporting Apple Pay, it would be really handy to be able to have fa-apple-pay for use in promoting payment options.

**Comment by LegoStormtroopr** [comment]
The apple site seems to be pretty specific on the logo and it is literally just the apple logo with the word pay next to it in a thin serif font (Myriad Set Pro). The border isn't a part of the logo as shown on their official merchant supplies page. Either way this would be much, much wider than any other icon.

* http://www.apple.com/apple-pay/
* https://www.applepaysupplies.com/applepaykit.html

In the interim, here is a single file github project that replicates it in plain CSS: https://github.com/LegoStormtroopr/font-awesome-apple-pay

![image](https://cloud.githubusercontent.com/assets/2173174/7383541/b09cbbf4-ee64-11e4-8283-d53e47875c5f.png)

**Comment by stucare** [comment]
Very much a + 1 on this one

**Comment by chocochipz** [comment]
+1 👍

**Comment by jakeyeaton** [comment]
+1

**Comment by kasnol** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
