### ISSUE TITLE
Icon request: Add to shopping-cart

### ISSUE THREAD

**Issue by jonastg** [FortAwesome/Font-Awesome#473]
For online shops it would be useful to have an add shopping cart (like shopping cart icon with add symbol '+' over the cart). This would help to differentiate cart states, as an empty cart, as well as an empty cart (https://github.com/FortAwesome/Font-Awesome/issues/302).

**Comment by WACMemphis** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cart-plus?style=solid
