### ISSUE TITLE
Icon Request: fa-finger-print

### ISSUE THREAD

**Issue by JulianoCruzJlle** [FortAwesome/Font-Awesome#4732]
It should be nice an icon to be used representing biometrical functions. I thought something like a fingerprint to represent the idea. I'm send you a image (it's not mine) to show you the idea.
![fingerprint](https://cloud.githubusercontent.com/assets/9198497/4615194/2ed8af28-52e8-11e4-8005-5ab6ac3270ae.png)

**Comment by smuwanga** [comment]
Has the icon-fingerprint been integrated? I would like to use it.

**Comment by tagliala** [comment]
@smuwanga unfortunately it isn't.

#4431

**Comment by jbagaresgaray** [comment]
+1

**Comment by noonii** [comment]
+1

**Comment by baziex** [comment]
+1

**Comment by tagliala** [comment]
Duplicate of #4431

🔒
