### ISSUE TITLE
Icon Request: fa-building-company

### ISSUE THREAD

**Issue by JulianoCruzJlle** [FortAwesome/Font-Awesome#4733]
It should be nice a new icon to represent companies, or shops, stores, etc..
The actual one isn't a good representation for that, many people think it was a calculator.

![building](https://cloud.githubusercontent.com/assets/9198497/4615362/bf243c72-52e9-11e4-9aef-17740e185599.png)

**Comment by syamsulalam** [comment]
+1

**Comment by sensibleworld** [comment]
We have a lot more building options now: https://fontawesome.com/search?o=r&c=buildings&s=solid&f=classic
