### ISSUE TITLE
Issue with <i class="fa fa-newspaper-o"></i>

### ISSUE THREAD

**Issue by whoaloic** [FortAwesome/Font-Awesome#4739]
Hi,
I use wordpress with font awesome.
I have added 4.2 version in my website.
wp_register_style('fontawesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', array(), '4.2.0'  );
wp_enqueue_style( 'fontawesome' );

When I try to put <i class="fa fa-newspaper-o"></i>, I don't see the icon.
But I've tried other new icons (since 4.2 version) like <i class="fa fa-paint-brush"></i>, <i class="fa fa-cc-visa"></i> or <i class="fa fa-bus"></i>. And these ones are working.

Could someone please check if all new icons are working?
Cheers.

**Comment by MiguelCTorres** [comment]
Another plugin that affect this is "Simple Author Box". But in Setting --> Miscellaneous Option switch to Yes the following option:

Disable Font Awesome stylesheet:
Switch to "Yes" to prevent Font Awesome from loading its stylesheet, ONLY if your theme or another plugin already does.

![image](https://cloud.githubusercontent.com/assets/11237854/7805570/0c82d1ec-034b-11e5-9109-4cb0a838d97e.png)
