### ISSUE TITLE
Icon request - 

### ISSUE THREAD

**Issue by matthieut69** [FortAwesome/Font-Awesome#4740]
Dear all, 

I would need for a project the following icons : 
- Bouquet of flowers 
![screenhunter_02 oct 14 12 16](https://cloud.githubusercontent.com/assets/9209642/4627440/3c33bbd8-538b-11e4-9f04-758dbf9fb69b.gif)
- A Best choice icon
![screenhunter_01 oct 14 12 03](https://cloud.githubusercontent.com/assets/9209642/4627448/4c8855d4-538b-11e4-8083-6383d4cde1e8.gif)
- An oak leaf
![screenhunter_03 oct 14 12 18](https://cloud.githubusercontent.com/assets/9209642/4627460/693a6834-538b-11e4-9a16-4f0e8801dd3b.gif)
- A sofa
![screenhunter_04 oct 14 12 18](https://cloud.githubusercontent.com/assets/9209642/4627465/7742d5ba-538b-11e4-9d42-211b3f91c7c4.gif)

Thanks a lot in advance and many thanks for the good work

**Comment by ssoulless** [comment]
the sofa is a duplicated request https://github.com/FortAwesome/Font-Awesome/issues/759

**Comment by tagliala** [comment]
thanks @ssoulless .

btw closing here because of contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

I don't know why I wrote "If I well remember this request is a duplicate but I need time to find the original one."

Closing here
