### ISSUE TITLE
Icon Request: fa-dog

### ISSUE THREAD

**Issue by J0N353Y** [FortAwesome/Font-Awesome#4755]
Icon of a dog 

http://thumb9.shutterstock.com/display_pic_with_logo/125638/125638,1313633567,2/stock-vector-icons-set-animals-83533261.jpg

for use in pet-related design (petvault.co.uk for example)

**Comment by kellybj** [comment]
Concur!  I'd love an icon for dog and cat!

**Comment by somethingworks** [comment]
Whats' the status on this?
I would love a horse as well.... 

+1

**Comment by jbarber1981** [comment]
+1 agreed that more animals would be great especially the common domestic and farm type animals

**Comment by tagliala** [comment]
Sorry, I missed this one

Duplicate of #1317, please +1 that request

closing here

**Comment by samhk222** [comment]
+1
