### ISSUE TITLE
Mathematics: fa-math-summation, fa-math-lamda, fa-math-omega, fa-math-squareroot, fa-math-qubedroot

### ISSUE THREAD

**Issue by derricksimpson** [FortAwesome/Font-Awesome#4767]
Issue #1350 #2922 already details the icon-pi and icon-equation.

I'd love to see Mathematics icons, such as: fa-math-summation, fa-math-lamda, fa-math-omega, fa-math-squareroot, fa-math-qubedroot, fa-math-limit, fa-math-integral, fa-math-interval, fa-math-infinity

**Comment by AndrewFreemantle** [comment]
+1 for **fa-infinity** here's a snippet from iconfactory for the sort of thing I'm thinking of..
 
![image](https://cloud.githubusercontent.com/assets/1304992/5996598/03c4a5ea-aaad-11e4-8a11-fda8862ece05.png)

**Comment by SylvainCorlay** [comment]
Would be nice to be close to the LaTeX symbol for infinity.

**Comment by nthnmldr** [comment]
+1 I'm specifically looking for fa-math-summation but a collection of math symbols would be great

**Comment by anderflash** [comment]
+1, and also fa-sigma and fa-integral

**Comment by tagliala** [comment]
Closing here.

This request contains duplicates (#2923, #4834)

Please open new individual requests (it is fine to have fa-math-squareroot, fa-math-cuberoot in a single request) as per [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)
