### ISSUE TITLE
Icon request: icon-invoice (icon-receipt)

### ISSUE THREAD

**Issue by danpayne17** [FortAwesome/Font-Awesome#477]
An icon for an invoice

**Comment by kristifrisch** [comment]
+1

**Comment by areyling** [comment]
+1

**Comment by steffenbrem** [comment]
+100

**Comment by stijnvanbael** [comment]
+1

**Comment by Majstr** [comment]
+1

**Comment by vivienleonard** [comment]
+1

**Comment by wwjamieson3** [comment]
+1

**Comment by wmira** [comment]
+1

**Comment by benn0r** [comment]
+1

**Comment by imarrero** [comment]
+1

**Comment by petejank** [comment]
+1

**Comment by G-Driver** [comment]
+1

<img src="https://cdn3.iconfinder.com/data/icons/pictofoundry-pro-vector-set/512/Receipt-512.png">
<img src="https://cdn0.iconfinder.com/data/icons/e-commerce-mini-icons/32/Commerce_Mini_Icons-21-512.png">

**Comment by tagliala** [comment]
my invoices look like http://fontawesome.io/icon/file-text-o/ :)

**Comment by Sitrane** [comment]
+1; Really like the bottom icon that G-Driver submitted

**Comment by dngunraj** [comment]
+1

**Comment by sanz0** [comment]
the torn off looks like a toilet paper .. please.. propose a better one... +1

**Comment by petejank** [comment]
Taxes are strictly related to invoices, and we all know that they're a piece of cra*. These icons just represent the reality

**Comment by MODUS-IT** [comment]
Any chances for those icons?

**Comment by G-Driver** [comment]
@MODUS-IT just give it a +1

**Comment by MODUS-IT** [comment]
By comment or ....? 
+1

**Comment by jklingen** [comment]
+1

Dirty workaround: stack a smaller currency symbol of your choice onto ```fa-file-text-o```. Needs quite some tweaking of size and position to look acceptable, though.

**Comment by secelite** [comment]
+1

**Comment by rabrowne85** [comment]
+1

**Comment by dougrawson** [comment]
+1

**Comment by koren88** [comment]
+1

**Comment by l0ft13** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by anacesponda** [comment]
+1

**Comment by hpolthof** [comment]
+1

**Comment by larsbo** [comment]
+1

**Comment by kevinbarone** [comment]
+1

**Comment by martinsifra** [comment]
+1

**Comment by npalikuca** [comment]
+1

**Comment by Multiplxd** [comment]
+1

**Comment by stefanhaan** [comment]
+1

**Comment by miradnan** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by Kitcat711** [comment]
+1

**Comment by naferoozi** [comment]
+1

**Comment by drinovc** [comment]
+1

**Comment by hpvd** [comment]
if needed, please also vote for complementing icon-requests of
- delivery https://github.com/FortAwesome/Font-Awesome/issues/6041
- quote https://github.com/FortAwesome/Font-Awesome/issues/8329

**Comment by greggoodman** [comment]
+1

**Comment by jbnv** [comment]
Is there a reason why this one has't been done yet? This request was opened 3 years ago. There have been multiple issues requesting the same or similar things. Meanwhile, FA is getting into the realm of the absurd with some recent additions, and adding brands that people have never heard of.

**Comment by G-Driver** [comment]
@jbnv we need more +1 's

**Comment by jbnv** [comment]
45 isn't enough?

**Comment by nickbouton** [comment]
+2?

**Comment by G-Driver** [comment]
@jbnv no we need more than 100 +1's

**Comment by nicolasbeauvais** [comment]
+1

**Comment by shaneneuerburg** [comment]
+1

**Comment by Helixon** [comment]
+1

**Comment by dotnetchris** [comment]
:+1:

**Comment by DutrowLLC** [comment]
+1

**Comment by thijsdemaa** [comment]
+1

**Comment by FrankHouweling** [comment]
+1

**Comment by iYalovoy** [comment]
+1

**Comment by sathibabu-nyros** [comment]
+1

**Comment by dicarlosystems** [comment]
+1

**Comment by mleczakm** [comment]
+1

**Comment by doncadavona** [comment]
+1

**Comment by markcrocombe** [comment]
+1

**Comment by 30nqnv8n39nf** [comment]
+1

**Comment by mmm197zabcm83hegr** [comment]
+1

**Comment by johnnylarren38** [comment]
+1

**Comment by wakeduckwake** [comment]
+1

**Comment by imperialdevops** [comment]
+1

**Comment by questionisnottheanswer** [comment]
+1

**Comment by muchcodesuchcool** [comment]
+1

**Comment by lesayle** [comment]
+1

**Comment by BBauer42** [comment]
+1

**Comment by goncalogoncalves** [comment]
+1

**Comment by Bc7UkIBfh7Nn0ui** [comment]
+1

**Comment by LMaiPbOzVumjdul** [comment]
+1

**Comment by Xm20B345etdOccg** [comment]
+1

**Comment by uoIyq6Suo9RcsW8** [comment]
+1

**Comment by uoIyq6Suo9RcsW8** [comment]
+1

**Comment by jbnv** [comment]
I hope that the number of +1's coming from spam accounts doesn't keep this from getting done.

**Comment by highskill-lasts** [comment]
+1

**Comment by dronezz** [comment]
+1

**Comment by issues-out** [comment]
+1

**Comment by OnlyAlphaa** [comment]
+1

**Comment by Preneable** [comment]
+1

**Comment by DevOnSOCKS** [comment]
+1

**Comment by entPr** [comment]
+1

**Comment by fishingforcode** [comment]
+1

**Comment by fishingforcode** [comment]
+1

**Comment by laolala** [comment]
+1

**Comment by dalink** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by remizemust** [comment]
+1

**Comment by dukebrown** [comment]
+1

**Comment by davegudge** [comment]
+1

**Comment by cristian-sima** [comment]
+1

**Comment by tamodaleko** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by lcaffarri** [comment]
+1

**Comment by christensson** [comment]
+1

**Comment by jjbang** [comment]
+1

**Comment by atorresg** [comment]
+1

**Comment by nikolaradivojevic** [comment]
+1

**Comment by trevnetmedia** [comment]
+1 Yes please!!!

**Comment by 0xApp** [comment]
+1 !!!!!

**Comment by douglasdeodato** [comment]
+1

**Comment by edusferreira** [comment]
+1 please

**Comment by Piernas** [comment]
+1

**Comment by RaimisErvit** [comment]
+1

**Comment by docksteaderluke** [comment]
+1

**Comment by douglasdeodato** [comment]
@G-Driver  do you have these invoices icons in AI or SVG? or someone here?

**Comment by shurub3l** [comment]
+1

**Comment by martindevnow** [comment]
+1

**Comment by Louis-LBA** [comment]
+1

**Comment by brhutch** [comment]
+1

**Comment by simple-designs** [comment]
+1

**Comment by garrensweet** [comment]
+1

**Comment by pendet** [comment]
+1

**Comment by jshow** [comment]
+1

**Comment by duleorlovic** [comment]
:+1:

**Comment by matiasiglesias** [comment]
+1

**Comment by caseyohara** [comment]
👍

**Comment by klaydze** [comment]
+1

**Comment by garthmason** [comment]
+1

**Comment by OlympicLarry** [comment]
+1

**Comment by stefanholzapfel** [comment]
+1

**Comment by atshaas** [comment]
+1

**Comment by dmaf87** [comment]
+1

**Comment by donslattery** [comment]
+1

**Comment by yugalbagul** [comment]
+1

**Comment by jethoraz** [comment]
+1

**Comment by arVahedi** [comment]
+1

**Comment by dperconti** [comment]
+1

**Comment by tagliala** [comment]
Is there any example of invoice icon which doesn't involve the currency symbol?

**Comment by alagos** [comment]
+1

**Comment by roymj88** [comment]
+1

**Comment by DOBss** [comment]
+1

**Comment by albertomario** [comment]
+1

**Comment by spo** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[The invoice icon is here](https://icons8.com/icon/16406/invoice).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Xbox](https://icons8.com/icon/12473/xbox), [Nintendo Wii U](https://icons8.com/icon/16297/nintendo-wii-u), [Nintendo](https://icons8.com/icon/16294/nintendo), [PlayStation](https://icons8.com/icon/12461/playstation), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by codebazz** [comment]
+1

**Comment by wavoe** [comment]
+1

**Comment by ahmad19** [comment]
+1

**Comment by marcioferreirap** [comment]
+1

**Comment by akachinonyerem** [comment]
+1

**Comment by joseareland** [comment]
+1

**Comment by MamatmurodovA** [comment]
+1

**Comment by Breadleyg** [comment]
+1

**Comment by vitortkr** [comment]
+1

**Comment by Boboss74** [comment]
open since 2012, in the top 25 of the oldest opened issue \o/

**Comment by hakanerdal** [comment]
+1

**Comment by iamdual** [comment]
+1

**Comment by MisterProg** [comment]
+1

**Comment by tarantuli** [comment]
+1

**Comment by copostic** [comment]
+1

**Comment by aheadlabs** [comment]
+1

**Comment by miclub** [comment]
+1

**Comment by henrik** [comment]
I could see this being implemented as a `file-dollar-sign`. Just like we have `file-audio` for a file with a speaker on it, this could be a file with a dollar sign on it. Seems like it should work well in different sizes, and it could be versatile, used for all sorts of money documents.

**Comment by stefanholzapfel** [comment]
I personally would prefer a more generic/international solution, e.g. a file with a note or coins as symbol instead of US currency.

**Comment by henrik** [comment]
@stefanholzapfel I agree in principle, but I feel that the current note icon doesn't work very well in small sizes. Maybe a coin or coins would work. A "$" could work as generic, though I guess that depends on your markets – if you have invoices in both "$" and "€" I guess putting a "$" on there would be weird.

**Comment by sensibleworld** [comment]
We've just added a "receipt" icon: https://fontawesome.com/icons?d=gallery&q=receipt. Will also be adding an "invoice" icon soon.

**Comment by kevinbarone** [comment]
@sensibleworld Glad to see you are doing both receipt and invoice. Invoices and receipts are fundamentally different. Personally, I funded the invoice request and not a scrolling receipt.

**Comment by sensibleworld** [comment]
A few options here: https://fontawesome.com/icons?d=gallery&q=invoice
