### ISSUE TITLE
Icon request: pig

### ISSUE THREAD

**Issue by stevierar** [FortAwesome/Font-Awesome#4772]
Hi, I've been using FontAwesome extensively on my current project. It's fantastic and I appreciate the amount of work that has gone into it.

For the project, I required an icon to represent a 'savings account'. I've seen many pigs but haven't seen any icons that satisfied me. I've designed this:

![pig](https://cloud.githubusercontent.com/assets/7798266/4676611/38a93ebc-55dd-11e4-86f7-e99920fe3262.png)

I'm unsure if it's too complicated, I find it's okay at smaller font sizes. I thought I would share this with the project as I've been using it so much!

Here is the SVG if it would be useful: https://mega.co.nz/#!ZZwFULiK!F_vWKE12T0VhYlso5k9OVXN8Rf114DinYL9Qzwcl3_U

**Comment by ElielBarone** [comment]
+1

**Comment by johnnyshields** [comment]
Pig is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.
