### ISSUE TITLE
Icon Request: fa-disconnect 

### ISSUE THREAD

**Issue by inextable** [FortAwesome/Font-Awesome#4777]
I think this one could be nice as alternative of fa-logout. It indicates "close", "log out", "unplug", disconnect"... 
![cerrar](https://cloud.githubusercontent.com/assets/5345240/4677865/bfb585ae-55ed-11e4-9ab3-2876eed09e33.png)

**Comment by jorgemarcondes** [comment]
power-off do not resolve my problem. What icon can i use to show server is disconnected?

**Comment by Soetens** [comment]
@jorgemarcondes  I suggest the use of the circle adding the color red/green/gray depending on the status. This should be more visible then different icons.

Personal I even prefer light green (opacity) and bright red to make it even more clear.
