### ISSUE TITLE
fa-beer-o

### ISSUE THREAD

**Issue by gtraxx** [FortAwesome/Font-Awesome#4778]
Hi, 
I use the icon fa-beer but is it possible to have too fa-beer-o ?
Thanks, good work ;)

**Comment by G-Driver** [comment]
+1

**Comment by dawadam** [comment]
+1

**Comment by sensibleworld** [comment]
Hey there! This was added to Font Awesome Pro: https://fontawesome.com/icons/beer?style=regular
