### ISSUE TITLE
Icon Request: fa-emergency-exit

### ISSUE THREAD

**Issue by koder217** [FortAwesome/Font-Awesome#4785]
Would be great to have this as an icon. A real-world icon for exit

![1561250-right_emergency_exit_sign_s_5568 gif](https://cloud.githubusercontent.com/assets/5275780/4688886/308f8ab2-5699-11e4-9f6e-1281c99bd7a3.jpeg)

**Comment by kwendenarmo** [comment]
+1

**Comment by iandoug** [comment]
+1, Possibly in the real world they use both left and right versions depending on which way you have to run.

**Comment by sombra1507** [comment]
+1

**Comment by george3447** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by showplans** [comment]
+1

**Comment by rjpadula** [comment]
+1

**Comment by HuwSy** [comment]
+1

**Comment by henksandoval** [comment]
+1

**Comment by MrConorAE** [comment]
I agree! This icon would be very useful. +1

**Comment by aethior** [comment]
Hi @koder217,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/person-to-door

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
@aethior thanks. Actually there may be an issue in this icon. ~As a sponsored icon, it should be part of the free set~ that was true for the kickstarter campaign

I will keep this open until the next release of FA
