### ISSUE TITLE
Letter with diacritics request: ř, č

### ISSUE THREAD

**Issue by bakua** [FortAwesome/Font-Awesome#4795]
Hello, 
I use external library for Android to use Font Awesome. It finds icon names in text label and converts them to icons. Rest of the text is unchanged, but with typeface from FontAwesome. Would it be possible to add letters ř, č (lowercase), Ř, Č (uppercase) to font? These are missing for Czech language.

Thanks :)

**Comment by tagliala** [comment]
Just cleaning up old issues.

I'm going to close here, considering this as a special case of #5019
