### ISSUE TITLE
Icon Request: fa-gis-layers, fa-gis-buffer, fa-gis-difference, fa-gis-intersect, fa-gis-polygon, fa-gis-polyline, fa-gis-point, fa-gis-freehandpolygon, fa-gis-freehandpolyline, fa-gis-project, fa-gis-service

### ISSUE THREAD

**Issue by larswise** [FortAwesome/Font-Awesome#4799]
Would be awesome if someone would add some icons for use in modern mapping applications (GIS).

**Comment by vtforester** [comment]
+1

**Comment by joaoponceleao** [comment]
+ 1
A sub-collection (i.e. fa-gis-xxx, or fa-geo-xxx) would be helpful for those of us using any kind of mapping / geographic libraries, though it would not need so many icons to start with.
On a related note, reorganising font-awesome with sub-collections (either by renaming / adding aliases to existing icons, or even better, using extra packages) would make navigating the increasing number of icons much easier.

**Comment by pconnell99** [comment]
+1 especially for  fa-gis-layers - That's a useful icon to have, really thought it was in the current fontset.

**Comment by tagliala** [comment]
Hi, 

I have to close this one because we had to update our contributing guidelines to deal with requests like this: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

@joaoponceleao a very limited sub collection could be considered if proper requests will be opened. By the way I should suggest you to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by joaoponceleao** [comment]
@tagliala 
Completely agree with closing this. FontAwesome is becoming too bloated in my view: sub-collections that can be added to custom builds would be how I would vote for this sort of thing. Would allow Font-awesome to concentrate on core functionality (like providing a service such as fontello/fonticons), and on curating a list of sub-collections (the problem with those custom builds is that there is too much duplication/options of icons).

Thanks for the link. That is how I decided to go forward with custom icons a while ago (after realising that svg icons are too hard to maintain) - did not realise that it was officially sanctioned by FontAwesome.
