### ISSUE TITLE
Icon Request: fa-teamup

### ISSUE THREAD

**Issue by kimmo3** [FortAwesome/Font-Awesome#4806]
FontAwesome is such a great project! I would really appreciate if you could include an icon for TeamUp, The Fansite for Sports, Music, and the Arts (www.tmup.co). There are a lot of bloggers who would like to use fontawesome to as a social icon to point to their own TeamUp profile, in a similar way as they point to other social networks.

Here's a suggestion how it could look like:
![icon-black](https://cloud.githubusercontent.com/assets/9356861/4743140/e8ff4978-5a24-11e4-93b1-fec475407b4a.png)

**Comment by aethior** [comment]
The domain ([link](http://www.tmup.co/)) is currently down and the social networks are inactive since 2017 ([twitter](https://twitter.com/tmupco) and [instagram](https://www.instagram.com/tmupco/)).

cc/ @tagliala
