### ISSUE TITLE
Icon request: fa-reader

### ISSUE THREAD

**Issue by Contrafibularity** [FortAwesome/Font-Awesome#4808]
An icon that represents 'reading and writing' or just 'reading' such as the following: 

http://www.sodafish.com/wp-content/uploads/2014/05/journal-international-icon-design.png

I imagine this to be a nearly identical version of #176 (open book), with the sole addition of (part of) a person's head. 

There are more elaborate icons around on the web that wouldn't be appropriate (e.g. http://www.wpclipart.com/education/reading/reading_3/reading_icon_2.png). 

Related: 
#1043 (reading glasses)
#2793 (reading, writing)

**Comment by liptonbeer** [comment]
+1

**Comment by 21cdb** [comment]
+1

**Comment by xerc** [comment]
+1 also for #6911

**Comment by manukieli** [comment]
+1
