### ISSUE TITLE
Icon request: fa-firehydrant

### ISSUE THREAD

**Issue by Drel** [FortAwesome/Font-Awesome#4810]
Please consider adding a fire hydrant to the icon set.  We could really use a series of icons that relate to the Fire Service / EMS.  I'm creating individual new icon requests for several others too.

**Comment by rinaldo-ferreira** [comment]
+1

**Comment by AlexanderPilhar** [comment]
+1

**Comment by DarrenPaulWright** [comment]
+1

**Comment by redenfire** [comment]
+1

**Comment by RossFenrisD** [comment]
+1

**Comment by jrajba** [comment]
+1

**Comment by niki-waggle** [comment]
![city-fire-hydrant-icon](https://user-images.githubusercontent.com/32939084/43281587-1471b666-90e2-11e8-94b5-4064967b2810.png)

**Comment by peteralbanese** [comment]
this was never completed?

**Comment by jessetechno** [comment]
+1 PLEASE!!!!

**Comment by sensibleworld** [comment]
Just please keep the dogs away from it: https://fontawesome.com/v6.0/icons/fire-hydrant?s=solid

<img width="992" alt="Screen Shot 2021-05-27 at 2 09 44 PM" src="https://user-images.githubusercontent.com/529604/119875806-30cdf100-bef5-11eb-848c-3b789e0c6ad9.png">
