### ISSUE TITLE
Icon request: fa-laddertruck (firetruck, fire truck)

### ISSUE THREAD

**Issue by Drel** [FortAwesome/Font-Awesome#4813]
Part of a series of requests for fire service icons.  Please note that I am requesting a separate icon for a fire engine.  The easiest distinguishing feature is that a ladder truck (aka fire truck) will typically be equipped with an aerial ladder.  See here -- https://www.portlandoregon.gov/fire/article/275933.

**Comment by AlexanderPilhar** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by lostinroom** [comment]
+1

**Comment by andreygolubkow** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🚒 [U+1F692](https://emojipedia.org/emoji/%F0%9F%9A%92/) Fire Engine
Also known as `Fire Department` and `Fire Truck`.

Related:
`fireengine`: #4812
`laddertruck`: #4813

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/truck-fire?f=classic&s=solid
