### ISSUE TITLE
Icon Request: fa-couple

### ISSUE THREAD

**Issue by vecerek** [FortAwesome/Font-Awesome#4825]
I've needed couple of times an icon, that would represent partnership between man and woman. To avoid any discrimination there could be 3 icons representing every combination (man-man, woman-woman, man-woman).
Use cases: services offering couple therapy, and other guidance services for couples

![man-woman-holding-hands-icon](https://cloud.githubusercontent.com/assets/5737996/4752083/c118874e-5aa6-11e4-9ec7-31214fa5f0fc.jpg)

**Comment by mewcrazy** [comment]
+1

**Comment by udaypatil** [comment]
+1

**Comment by Robin-Hoodie** [comment]
+1

**Comment by asarican** [comment]
Hi,
Define new css rule like this:
.fa-couple:before {
content: "\f182\f183";
}
it prints female&male next to each other. You can name your icon name anything you want or modify existing which you didn't use. You can use 2 or more icons next to each other using content css rule.

**Comment by Wingo5315** [comment]
+1

**Comment by aethior** [comment]
Hi @vecerek,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/people

> To avoid any discrimination there could be 3 icons representing every combination (man-man, woman-woman, man-woman).

Now there are [fa-people](https://fontawesome.com/icons/people), [fa-people-dress](https://fontawesome.com/icons/people-dress) and [fa-people-pants](https://fontawesome.com/icons/people-pants) icons.

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.

**Comment by tagliala** [comment]
Thanks

Wanted to add that FA Free users **in a web application** can create this icon by layering and stacking `fa-person` and `fa-person-dress`
