### ISSUE TITLE
Icon request: fa-uber [will be available in FA5]

### ISSUE THREAD

**Issue by rachelchorney** [FortAwesome/Font-Awesome#4826]
I would like to request an icon for the uber logo. I would be using the icon on http://vaccinefinder.org/. Right now I am using a small square shaped uber logo and I would like to replace it with a font awesome version so it matches the rest of the icons used on the site. The icon would look like this image here:
https://vaccinefinder.org/img/uber.jpg

**Comment by joshuaNathaniel** [comment]
:+1:

**Comment by 4khil** [comment]
+1

**Comment by mikejoyceio** [comment]
+1

**Comment by pinderh** [comment]
+1

**Comment by alaingilbert** [comment]
+1

**Comment by Khodl** [comment]
+1

**Comment by slsmag** [comment]
+1

**Comment by omrimor1** [comment]
+1

**Comment by trein** [comment]
+1

**Comment by BrianKTran** [comment]
Have you recieved the fa-uber icon or heard back from them yet??

**Comment by AleksBeer** [comment]
+1

**Comment by mvnrsa** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
