### ISSUE TITLE
Icon Request: fa-sage

### ISSUE THREAD

**Issue by Azaret** [FortAwesome/Font-Awesome#4827]
Hi,
Not sure if it's ok to use it tho, but I could use an icon for Sage!
This icon is over there http://www.zoom.fr/phpBB2//images/topics/gesco.bmp (Yes it's a bitmap, Sage is a old piece of software)

I would be perfect just as two plain shape, the icon between Sage modules is just about changing the color of the logo, so with using FA it would be neat.

Thanks :)

**Comment by SylvainCorlay** [comment]
+1

**Comment by tagliala** [comment]
Closing here in favour of #15955
