### ISSUE TITLE
Icon request: shapes / category icon (fa-shapes)

### ISSUE THREAD

**Issue by SylvainCorlay** [FortAwesome/Font-Awesome#4830]
I need an icon that could represent the notion of category / type or the choice between different types.  

An heterogeneous group of clearly distinct shapes would do the job (square, circle, triangle), like this:

![shapes](https://cloud.githubusercontent.com/assets/2397974/4765031/c6dc68e4-5b32-11e4-9862-48e551d2d0b2.png)

**Comment by Denni007** [comment]
:+1:

**Comment by sensibleworld** [comment]
This is available in version 5 and version 6: https://fontawesome.com/v6.0/icons/shapes?s=solid
