### ISSUE TITLE
Icon-Request: Bits

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#484]
Icon symbolizing programming.
0100100
0001000
1100001

Thanks
Jose

**Comment by Kondou-ger** [comment]
@davegandy I'd suggest reopening this feature request. Here's a quick 14px image that's well readable and resembling bits: ![bits](https://cloud.githubusercontent.com/assets/1410802/9292911/6393d0e6-4412-11e5-8fde-e08072e76ad0.png)

**Comment by tagliala** [comment]
@Kondou-ger please +1 #6812
