### ISSUE TITLE
Icon Request: fa-text-select

### ISSUE THREAD

**Issue by SpoonSnacker** [FortAwesome/Font-Awesome#4842]
I noticed there wasn't a request for a text-selector icon so I thought I'd post it.
Something along the lines of ![image](http://i.gyazo.com/10971d9b1d8d302984c0025241168466.png).

**Comment by SylvainCorlay** [comment]
+1, with a distinction
![select-all](https://cloud.githubusercontent.com/assets/2397974/6958173/40d47346-d8d6-11e4-8b48-02746ce93638.png) `fa-select-all`
![select-text](https://cloud.githubusercontent.com/assets/2397974/6958174/4415776c-d8d6-11e4-9a77-b7f9c697cf07.png) `fa-select-text`

**Comment by goanpeca** [comment]
Seems like a good idea :+1:

**Comment by MightyFo0l** [comment]
+1

I use this Mac icon in my own system now. This is a compact and clear solution imo:
![preview_text_tool_icon 1](https://cloud.githubusercontent.com/assets/16845714/13843117/1ff61a42-ec32-11e5-8834-d17b2d5d2dc7.png)

**Comment by sensibleworld** [comment]
I think this fits the bill: https://fontawesome.com/icons/i-cursor?style=solid
