### ISSUE TITLE
Icon Request: fa-mailbox

### ISSUE THREAD

**Issue by deepakrout** [FortAwesome/Font-Awesome#4849]
Hi, 

Our application uses FA icons.  We have a requirement to show contact type icon. There are fa icons like fa-phone for phone, fa-fax for fax, fa-envelope mostly used for e-mails but no  icons specifically can identify postal mail. For that reason,  fa-postman  or fa-mailbox or  fa-delivery or fa-courier  would be very useful. I am sure lot of developers would be wishing for that. 

![mailbox_icon](https://cloud.githubusercontent.com/assets/7481986/4802832/81d33c06-5e4c-11e4-8d11-24b22bbc4e9d.png)

**Comment by saas786** [comment]
+1

**Comment by lizshinn** [comment]
+1

**Comment by danieljrobles** [comment]
+1

**Comment by Pau1fitz** [comment]
+1

**Comment by EddyCwdry** [comment]
+1

**Comment by ContactEstablished** [comment]
+1

**Comment by shannon-linn** [comment]
+1

**Comment by Uelb** [comment]
+1

**Comment by sara-mansouri** [comment]
+1

**Comment by SudoPlz** [comment]
+1

**Comment by YelloW22** [comment]
+1

**Comment by 19eighties** [comment]
+1

**Comment by gael-wogenstahl** [comment]
+1

**Comment by FedeOmoto** [comment]
+1

**Comment by ella-autobrain** [comment]
+1

**Comment by shane9** [comment]
+1

**Comment by funkyphenix** [comment]
+1

**Comment by hotsax** [comment]
+1

**Comment by kasianchuk** [comment]
+1

**Comment by elarson** [comment]
+1

**Comment by bcnichols3** [comment]
+1

**Comment by leightonb** [comment]
+1

**Comment by 19eighties** [comment]
+1

**Comment by voorthuijsen** [comment]
+100!!

**Comment by descendingleaves** [comment]
+1

**Comment by robadmin** [comment]
+1

**Comment by michaelpaps** [comment]
+1

**Comment by djm204** [comment]
+1

**Comment by boazbk** [comment]
+1

**Comment by TantumLabs** [comment]
+1

**Comment by DamianoSilverhand** [comment]
+1

**Comment by michaelpaps** [comment]
Hi @tagliala, any progress on this icon? It's been a few years now and still in need in nearly all our projects. Thanks!

**Comment by sarahk** [comment]
Adding a comment with the keyword LETTERBOX so that people searching can find this suggestion
Never heard of them being referred to as a mailbox before.

**Comment by scolby33** [comment]
+1

**Comment by sensibleworld** [comment]
All of those `fa-envelope`s finally have a home: https://fontawesome.com/icons/mailbox?style=solid
