### ISSUE TITLE
Icon request: icon-single-slider

### ISSUE THREAD

**Issue by sanbornhilland** [FortAwesome/Font-Awesome#4850]
The fa-sliders icon is great except it doesn't fit every situation where you might want to indicator sliders. Particularly if you are indicating a single slider or a range input an icon with just a single slider would be quite useful.

Cheers, and thanks for all your hard work.

**Comment by aethior** [comment]
Hi @sanbornhilland,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/slider

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please. :)
