### ISSUE TITLE
Please include icons.yml file somewhere in the ZIP file that's downloaded

### ISSUE THREAD

**Issue by chockenberry** [FortAwesome/Font-Awesome#4851]
I'm working on a new feature in [xScope](http://xScopeApp.com) that supports Font Awesome in the Text tool. The feature requires getting a list of the current icons into an internal database, and this can be done easily by importing icons.yml.

The hard part for designers will be to find and download the icons.yml file in the GitHub repository. They'll have to download the entire repository and then dig a single file out of the src folder.

It would be much easier for these users if you added the file to an "info" folder along with the "css", "fonts", "less" and "scss" folders.

**Comment by dominykas** [comment]
Including `icons.yml` in zip or whatever other distribution would also be beneficial for projects like https://github.com/CodeCharmLtd/Font-Awesome-SVG-PNG - they could just depend on the `font-awesome` published in `npm`, without having to explicitly fetch it from github, as described https://github.com/FortAwesome/Font-Awesome/issues/2795

**Comment by dotherightthing** [comment]
I just purchased XScope, but https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/src/icons.yml is 404. Where is icons.yml now?

**Comment by tagliala** [comment]
@dotherightthing here: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/metadata/icons.yml

**Comment by tagliala** [comment]
Done. Zip archive contains the `icons.yml` file in the `/metadata` subfolder
