### ISSUE TITLE
Icon Request: fa-hierarchy+connections

### ISSUE THREAD

**Issue by landwire** [FortAwesome/Font-Awesome#4857]
Hi there,
this is a request for a few related items grouped as: hierarchy & connections

See a few examples of the type of icons I mean:

https://www.iconfinder.com/icons/233907/bussiness_hierarchy_line_network_web_icon
https://www.iconfinder.com/icons/230476/chart_charts_connections_diagram_graph_graphs_hierarchy_internet_network_relations_structure_web_icon
http://www.iconsdownload.net/education/1046-hierarchy-levels-icon
https://www.iconfinder.com/icons/216231/connections_icon#size=128
https://www.iconfinder.com/icons/215271/chart_charts_diagram_graph_relations_social_graph_statistics_icon#size=128
https://www.iconfinder.com/icons/216861/analytics_chart_connection_connections_graph_network_relations_structure_icon#size=128
https://www.iconfinder.com/icons/263757/analogy_association_connection_interconnection_interdependence_network_node_organic_relation_icon#size=128
https://www.iconfinder.com/icons/292392/associate_association_communication_connect_connection_connections_link_net_network_networking_relate_relation_share_system_web_icon#size=128

**Comment by landwire** [comment]
Ok, not sure if it needs to be a group. So maybe just do individiual icons that you think are useful.
I tried to give some use cases....


fa-hierarchy
useful to represent a hierarchy
![image](https://cloud.githubusercontent.com/assets/1001202/10799848/4b886dd2-7daf-11e5-820b-cbbaf0e635f9.png)

fa-one-to-many
useful to represent a one-to-many connection
![image](https://cloud.githubusercontent.com/assets/1001202/10799918/a27d855a-7daf-11e5-9dd9-0c8cded55cc1.png)

fa-one-to-many-alternative
used to express one-to-many connections that can be improved
![image](https://cloud.githubusercontent.com/assets/1001202/10800063/537d8ff8-7db0-11e5-8c12-b15ef684f483.png)

fa-connection
useful to express many to many connection
![image](https://cloud.githubusercontent.com/assets/1001202/10799995/0e004f7e-7db0-11e5-8cf8-a305632cc7d6.png)

fa-connection-alternative
just an alternative style of above
![image](https://cloud.githubusercontent.com/assets/1001202/10800022/2872a1ea-7db0-11e5-9ce5-e95f280c4479.png)

Let me know if that is enough like that....

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()

**Comment by tagliala** [comment]
@sensibleworld The link is missing, I guess this is an icon related to networks: https://fontawesome.com/search?q=network&o=r
