### ISSUE TITLE
Icon request: jewelery-ring, jewelery-dimond, jewelery-gold-brick, jewelery-bracelets, jewelery-pendant

### ISSUE THREAD

**Issue by mb-bayrak** [FortAwesome/Font-Awesome#4859]
Thank you very much

**Comment by sensibleworld** [comment]
We have a few options now:

https://fontawesome.com/icons/rings-wedding?s=solid&f=classic
https://fontawesome.com/icons/ring-diamond?s=solid&f=classic
https://fontawesome.com/icons/ring?s=solid&f=classic
