### ISSUE TITLE
Icon request: icon-crown

### ISSUE THREAD

**Issue by drsii** [FortAwesome/Font-Awesome#486]
I like Crowns, not  to be confused with clowns, i hate clowns.

**Comment by cvsguimaraes** [comment]
+1

**Comment by ppollono** [comment]
+1

**Comment by joshuaruesweg** [comment]
+1

**Comment by mistrg** [comment]
+1

**Comment by skyepn** [comment]
+one

**Comment by rubenprins** [comment]
+1

**Comment by pvljanda** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by groupnet** [comment]
+1

**Comment by realityking** [comment]
+1

**Comment by sba** [comment]
+1

**Comment by jkahrs** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by Chrisissorry** [comment]
+1

**Comment by KaiserVito** [comment]
+1

**Comment by bejayoharen** [comment]
+1. here's a very simple crown our designer made:
![badge_featured 3x](https://cloud.githubusercontent.com/assets/1331948/8440543/cc675c92-1f40-11e5-876d-4e81d60ce3a2.png)

**Comment by joeystandrew** [comment]
+1 Any updates on this? We really need a crown icon too, I really like bejayoharen's icon.

**Comment by Tical0** [comment]
+1

**Comment by DamianPrg** [comment]
+1

**Comment by viktorsheep** [comment]
+1

**Comment by mefernandez** [comment]
+1

**Comment by mokujin90** [comment]
+1

**Comment by guilhermedecampo** [comment]
+1!

**Comment by whosvinny** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by NikosEfthias** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by mitchfizz05** [comment]
+1

**Comment by JimCook57** [comment]
+1

**Comment by liamjohnston** [comment]
+1

**Comment by nukos** [comment]
+1

**Comment by jbnv** [comment]
+1

**Comment by smite107** [comment]
need!!!!

**Comment by RobNL** [comment]
+1

**Comment by michelevirgilio** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by joshtronic** [comment]
:+1:

**Comment by TomFranssen** [comment]
+1

**Comment by Stoward94** [comment]
+1

**Comment by khasky** [comment]
+1

**Comment by charlieholder** [comment]
+1

**Comment by scfl** [comment]
+1

**Comment by mskasal** [comment]
+1

**Comment by dydric** [comment]
+1

**Comment by Daijobou** [comment]
+1
same request https://github.com/FortAwesome/Font-Awesome/issues/1903

**Comment by rwsansom** [comment]
+1

**Comment by 00F100** [comment]
+1

**Comment by carlostelles-deliverit** [comment]
+1

**Comment by juampi** [comment]
+1

**Comment by 87racer** [comment]
+1

**Comment by dlussky** [comment]
+1

**Comment by dlussky** [comment]
+1

**Comment by atru** [comment]
+1

**Comment by Arvraepe** [comment]
+1

**Comment by 00F100** [comment]
+1

**Comment by nibelune** [comment]
+1

**Comment by timmyrs** [comment]
+1

**Comment by philXeven** [comment]
+1

**Comment by Brieg** [comment]
+1

**Comment by Aloqsin** [comment]
👍

**Comment by ryankekos** [comment]
+1

**Comment by anandsg063** [comment]
+1

**Comment by bdauton** [comment]
+1

**Comment by mynameiskyle** [comment]
+1 I think it should be even simpler than the other suggestions with only 3 tines (points) and no extra bits.

![Crown Icon](http://i.imgur.com/8AQGSfU.png)

**Comment by masteradhoc** [comment]
+1

**Comment by JochLAin** [comment]
+1

**Comment by joaokamun** [comment]
+1

**Comment by salvatorecapolupo** [comment]
+1

**Comment by Hypernation** [comment]
+1

**Comment by jubayerarefin** [comment]
+1

**Comment by sander5** [comment]
+1

**Comment by 58a36f** [comment]
+1

**Comment by Liightman** [comment]
+1

**Comment by felippeDev** [comment]
+1

**Comment by Domiii** [comment]
+1

**Comment by sefaYavuz** [comment]
+1

**Comment by Lederzwerg** [comment]
+1

**Comment by azarus** [comment]
+1

**Comment by titan-rmiller** [comment]
+1

**Comment by 00F100** [comment]
+1

**Comment by wlievens** [comment]
People, this actually works as is
```
.fa-crown:before {
  content: "\1f451";
}
```
Maybe fontawesome is based on an existing fonts, which has basic letters, numbers and emoji? Or is this just my browser doing fallback?

**Comment by tagliala** [comment]
> Maybe fontawesome is based on an existing fonts, which has basic letters, numbers and emoji? Or is this just my browser doing fallback?

That is the unicode point for the crown emoji, that is just the browser doing fallback. Chrome on Windows 10 renders it as an emoji on my machine

Maybe the standard unicode points [`\2654`](http://www.fileformat.info/info/unicode/char/2654/browsertest.htm) and [`\2655`](http://www.fileformat.info/info/unicode/char/2654/browsertest.htm) have a wider support

**Comment by wlievens** [comment]
Actually you can append the VS15 symbol \FE0F to render it in black and white style instead of colored emoji. The resulting icon is surprisingly consistent with FA style, in Chrome and FF at least.

**Comment by MaLKaVeS** [comment]
+1

**Comment by eyforia** [comment]
+1

**Comment by irfan-dahir** [comment]
+1

**Comment by cobafan** [comment]
+1

**Comment by skcin7** [comment]
+1

FONT AWESOME NEEDS A CROWN. MULTIPLE OCCASIONS THAT A CROWN ICON HAS BEEN NEEDED.
Ok thanks love fontawesome thank you for all you do bye.

**Comment by ExillustX** [comment]
+1

**Comment by ttkaine** [comment]
+1

**Comment by mohamedabkd** [comment]
+1

**Comment by velvetomatoe** [comment]
+1

Loving FA 5 btw, so easy to use and so many options in pro! Great work!

**Comment by sensibleworld** [comment]
Hey folks! Happy to announce that this will be included in our 5.1 release!
