### ISSUE TITLE
Icon Request: fa-tilesview

### ISSUE THREAD

**Issue by mattercss** [FortAwesome/Font-Awesome#4864]
First, thank you for taking the time to create such a fantastic library that I use on all my sites. I do have a lot of web applications that show different ways to views data - sort of like how you can change the view of files inside of a folder on Windows. I was wondering if you could create a fa-tilesview and a fa-detailsview icon to the library.

Thanks, 

Eric

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
