### ISSUE TITLE
Icon Request: data types

### ISSUE THREAD

**Issue by marcselman** [FortAwesome/Font-Awesome#4867]
It would be great if icons for different data types could be added.
For example:
String, integer, decimal, date-time, boolean, enum etc.

String could be something like the font icon.
Integer could be 0...1
Decimal could be 1.95
Datetime could be a calendar with a clock or something like that
Boolean can use one of the existing checkbox icons
Enum could use the existing fa-caret-square-o-down icon

There are a lot of applications where a user can choose a datatype for a field for example.

Thank you.

**Comment by orshee** [comment]
Its been 2 years since the request, has anything like that been implemented? 
I am unable to find any useful replacements within FA

**Comment by tagliala** [comment]
@orshee please open new, individual requests following our icon request template
