### ISSUE TITLE
Icon Request: fa-intercom

### ISSUE THREAD

**Issue by duellsy** [FortAwesome/Font-Awesome#4873]
Would love to be able to display an icon for [intercom](https://www.intercom.io/) for people to click on to open the intercom messages module on our site.

I'm assuming that in the case of an existing saas logo, I don't need to attach an image for what "i'm going for" as it's an existing logo.

**Comment by mtthwhggns** [comment]
+1 
I'm working on an internal app where linking to Intercom would be useful.

**Comment by duellsy** [comment]
Also. for reference, their logo can be found here https://www.intercom.io/press

**Comment by proserve** [comment]
+1

**Comment by albertmw** [comment]
+1

**Comment by duranmla** [comment]
Yes, it would be cool

**Comment by amirghafouri** [comment]
+1

**Comment by NirBenya** [comment]
+1

**Comment by JustinHatchett** [comment]
+1

**Comment by mredman** [comment]
+1

**Comment by samuelroxo** [comment]
+1

**Comment by jsanchezs** [comment]
+1

**Comment by SirRawlins** [comment]
+1

**Comment by marinhero** [comment]
+1

**Comment by talbs** [comment]
Added in version 5.6.0 - https://fontawesome.com/icons/intercom. 😄

**Comment by alfonsoperez** [comment]
![screen shot 2019-01-03 at 5 06 06 pm](https://user-images.githubusercontent.com/3578008/50669398-e50ffb00-0f79-11e9-98d9-26c5e8af2e93.png)

![](https://media.giphy.com/media/l2JdVRfJozpjq70SA/giphy.gif)
