### ISSUE TITLE
Icon Request: fa-whatsapp

### ISSUE THREAD

**Issue by fedehartman** [FortAwesome/Font-Awesome#4890]
An icon for whatsapp: http://www.whatsapp.com/
:)

**Comment by GeorginaCh** [comment]
How i can got the code of whatsapp icon ?

**Comment by tagliala** [comment]
please make sure you are using 4.3.0 version

**Comment by GeorginaCh** [comment]
no i'm using the 4.2.0 how i can add the whatsapp only ?

On Fri, Feb 6, 2015 at 5:04 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> please make sure you are using 4.3.0 version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/4890#issuecomment-73249646>
> .
>



-- 
*Georgina Chedid*
*Graphic/WEB Designer - Front end developer.*
* 70 633924 - **www.picleb.com <http://www.picleb.com>*

**Comment by tagliala** [comment]
@GeorginaCh you can't, you should customize the font or update. I do not advise to use both only for .whatsapp. Btw moving to 4.3.0 should not break backward compatibility

**Comment by GeorginaCh** [comment]
I downloaded the latest version of font awesome but still having an issue
with the whatsapp icon

On Fri, Feb 6, 2015 at 6:30 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> @GeorginaCh <https://github.com/GeorginaCh> you can't, you should
> customize the font or update. I do not advise to use both only for
> .whatsapp. Btw moving to 4.3.0 should not break backward compatibility
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/4890#issuecomment-73264845>
> .
>



-- 
*Georgina Chedid*
*Graphic/WEB Designer - Front end developer.*
* 70 633924 - **www.picleb.com <http://www.picleb.com>*

**Comment by tagliala** [comment]
@GeorginaCh please check that there are no conflicts

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
