### ISSUE TITLE
Icon request: fa-thumb-tack-o

### ISSUE THREAD

**Issue by monchoz** [FortAwesome/Font-Awesome#4899]
Hi! I would like a fa-thumb-tack-o icon. I've been looking for it in font awesome but I think it doesn't exist. I name it "fa-thumb-tack-o" because some of existing icons which have a -o suffix are the equivalent of an "off". Like existing fa-star and its "off" icon: fa-star-o

I need this new icon because i'm developing an app using icon fonts (font awsome in this case). The functionality is that users can "tack on" objects like Pinterest "pin" feature. So in order to determine if the object is not "tacked" I need the oposite of existing fa-thumb-tack icon. 

Thanks! 
I really hope this request comes reality :) 

Example attached
![thumb-tack](https://cloud.githubusercontent.com/assets/3931413/4906632/86cadbf6-645a-11e4-9910-27b0c5d073f2.png)

**Comment by alixeb** [comment]
I think it would be better if the pin icon have the same kind of style use in inbox.google.com

![pin-example](https://cloud.githubusercontent.com/assets/382022/6866789/ae19073a-d473-11e4-80ed-45443456c0fe.png)

**Comment by alixeb** [comment]
Actually this is implemented already :)

http://fontawesome.io/icon/thumb-tack/

This issue should be closed.

**Comment by aliquis** [comment]
@alixeb It's great that you can [convey information using colors](http://webaim.org/articles/visual/colorblind) in your projects, but there are projects where this is not possible.

The tack you're linking to is the only one available in Font Awesome. This issue requests a second tack, which is arguably not implemented yet.

**Comment by baunfire** [comment]
+1

**Comment by eatoncw** [comment]
I can see this request has been there for a long time, but I'd also really like a thumb-tack-o icon for the app I'm developing (so just the outline of the thumb-tack is there). The app is visual collaboration platform that enables discussions around particular areas of an image, like a photograph. The thumb-tack would indicate where on the image that particular discussion is about. A thumb-tack outline with transparent interior would look much better than the solid one for my purposes (drawn crudely here!). Thanks
![thumb-tack-o](https://cloud.githubusercontent.com/assets/17256462/14127126/7eb82c54-f5ca-11e5-95b0-f5123618c234.jpg)

**Comment by acareaga** [comment]
+1

**Comment by behzad888** [comment]
+1

**Comment by adamdonahue** [comment]
+1
