### ISSUE TITLE
icon request: icon-pencil-slash (read only)

### ISSUE THREAD

**Issue by jovpet** [FortAwesome/Font-Awesome#4906]
It would be nice to have an icon that shows read only mode. as fa-pencil icon be used to show some editable feature, crossed pencil like this one 
![image](https://cloud.githubusercontent.com/assets/6247120/4921741/6de9da80-650c-11e4-83b7-349bbc6995f4.png)
could be useful for read only mode

**Comment by tagliala** [comment]
Take a look at this project: https://github.com/nyon/fontawesome-actions

https://github.com/FortAwesome/Font-Awesome/issues/1181#issuecomment-87315812

**Comment by rliebi** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/calendar-plus?s=solid
