### ISSUE TITLE
Prefix partial LESS source files with underscore

### ISSUE THREAD

**Issue by Eonasdan** [FortAwesome/Font-Awesome#4907]
To mirror and quote [this Bootstrap issue](https://github.com/twbs/bootstrap/issues/12902), please rename all imported/sub LESS files with an underscore so that those files don't get compiled into CSS.

> To prevent library files from being compiled individually (and to produce CSS files), many LESS compilers have implemented skipping of partial source files that are prefixed with the underscore (_) character, for example: _variables.less.
> 
> Definition of a partial (from http://docs.mixture.io/preprocessors):
> 
> > A partial is denoated by an underscore at the beginning eg _myfile.less.
> 
> See also:
> 
> https://webessentials.uservoice.com/forums/140520-general/suggestions/3319359-don-t-compile-nested-less-files
> http://docs.mixture.io/preprocessors
> http://www.playframework.com/documentation/2.0/AssetsLess

**Comment by tagliala** [comment]
This has been done in FA5!

Forgot to close this one

/cc @talbs
