### ISSUE TITLE
Icon request: icon-donate, Icon request: icon-donation

### ISSUE THREAD

**Issue by michelleortner** [FortAwesome/Font-Awesome#4908]
I would love to be able to have a "donate" or "donation" icon to use for some of our sites. These mostly include non-profit organizations or special events. I am thinking that the icon could be a donation box, piggy bank, or hand giving money, similar to the ones I have included.

http://dccadv.org/img/fck/image/donate-icon.gif
http://hemja.org/images/donate.png
https://cdn1.iconfinder.com/data/icons/money-currency-extras/512/Hand_Holding_Coin-128.png
https://cdn3.iconfinder.com/data/icons/finance-and-money-1/512/piggy_bank_savings_money_flat_icon-128.png
https://cdn3.iconfinder.com/data/icons/e-commerce-and-sales/512/coin_pay_money_payment_investment_banking_flat_icon-128.png

Thanks!

**Comment by tagliala** [comment]
piggibank: #1413 
donation: #2224
