### ISSUE TITLE
Icon request: icon-brazilian-real (R$)

### ISSUE THREAD

**Issue by 4n0n1mo** [FortAwesome/Font-Awesome#4916]
Icon: R$
It's the brazillian currency symbol.
Thanks for your time!

**Comment by rjuniod** [comment]
I'm also looking for this icon

**Comment by garcia-jj** [comment]
+1

**Comment by paulocastellano** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by policarpoquintao** [comment]
+1

**Comment by alexrusenhack** [comment]
+1

**Comment by marcioc0sta** [comment]
+1

**Comment by nofxx** [comment]
+1 

I know our current socialist/comunist corrupt (redudant) goverment managed to get us from 6th economy of the world to 9th and droping as you read.
But we're soon getting rid of the "workers (that never worked) party" and be respected again.
We're a rich economy, and it's a easy icon =D

**Comment by dfvascao** [comment]
Hello!

Already have this icon created or has provision for creation?

**Comment by dgateles** [comment]
+1

**Comment by DmonteiroD** [comment]
+1

**Comment by PaulaSimiqueli** [comment]
+1

**Comment by RenathoAzevedo** [comment]
+1

**Comment by fabiosammy** [comment]
:+1:

**Comment by DKSoftwares** [comment]
+1

**Comment by rgielow** [comment]
+1

**Comment by nenodias** [comment]
+1

**Comment by diegoptc** [comment]
+1

**Comment by ChristHA** [comment]
+1

**Comment by wiliamjk** [comment]
+1

**Comment by WillianID** [comment]
👍

**Comment by dfvascao** [comment]
👍

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/brazilian-real-sign?s=solid
