### ISSUE TITLE
Icon Request: fa-hurricane

### ISSUE THREAD

**Issue by mmohon1** [FortAwesome/Font-Awesome#4931]
Looking for a hurricane symbol, reference:
https://www.google.com/search?q=hurricane+symbol&client=firefox-a&hs=wJb&rls=org.mozilla:en-US:official&channel=sb&tbm=isch&tbo=u&source=univ&sa=X&ei=OAphVOSWOomtyATZ94DIBw&ved=0CB8QsAQ&biw=1920&bih=981

**Comment by roy46** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a hurricane icon to Font Awesome Pro: https://fontawesome.com/icons/hurricane?style=solid
