### ISSUE TITLE
Icon Request: fa-group, fa-ungroup

### ISSUE THREAD

**Issue by briwardster** [FortAwesome/Font-Awesome#4951]
Need icon to indicate grouping of items and ungrouping of items (pictures, related text, etc.).
![group](https://cloud.githubusercontent.com/assets/3504615/4998660/2893d5a8-698f-11e4-8876-3fad8f565d61.png)

The png attached is *not* my own. :)

**Comment by bertoost** [comment]
+1

**Comment by netrevisanto** [comment]
Please id love to use it as my group by button!

**Comment by Denni007** [comment]
+1

**Comment by zfor** [comment]
+1

**Comment by tagliala** [comment]
Added in 4.4.0

Closing here! :)
