### ISSUE TITLE
Icon request: fa-firefox-os 

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [FortAwesome/Font-Awesome#4952]
Would love a Firefox OS mobile os logo:

Firefox OS: https://assets.mozilla.org/Brands-Logos/Firefox%20OS/wordmark-only/firefox-os_wordmark-only_RGB.png

**Comment by tagliala** [comment]
> In December 2015, Mozilla announced it would stop development of new Firefox OS smartphones,[[10]](https://en.wikipedia.org/wiki/Firefox_OS#cite_note-10) and in September 2016 announced the end of development

Closing here
