### ISSUE TITLE
Icon request: fa-s60

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [FortAwesome/Font-Awesome#4955]
Would love a s60 mobile os logo:

S60: http://www.webitpr.com/writeitfiles/Community_CMYK.jpg

**Comment by aethior** [comment]
>The S60 Platform (formerly Series 60 User Interface) is a software platform for smartphones that runs on top of the Symbian operating system. It was created by Nokia based on the 'Pearl' user interface from Symbian Ltd. ([more info](https://en.wikipedia.org/wiki/S60_(software_platform)))

>Nokia terminated its support of software development and maintenance for Symbian with effect from 1 January 2014, thereafter refusing to publish new or changed Symbian applications or content in the Nokia Store and terminating its 'Symbian Signed' program for software certification. ([more info](https://en.wikipedia.org/wiki/Symbian))

cc/ @tagliala

**Comment by tagliala** [comment]
😢
