### ISSUE TITLE
Icon request: fa-symbian

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [FortAwesome/Font-Awesome#4956]
Would love a Symbian mobile os logo:

Symbian: http://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Symbian_logo.svg/730px-Symbian_logo.svg.png

**Comment by aethior** [comment]
>Nokia terminated its support of software development and maintenance for Symbian with effect from 1 January 2014, thereafter refusing to publish new or changed Symbian applications or content in the Nokia Store and terminating its 'Symbian Signed' program for software certification. ([more info](https://en.wikipedia.org/wiki/Symbian))

cc/ @tagliala
