### ISSUE TITLE
Icon request: fa-meego

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [FortAwesome/Font-Awesome#4957]
Would love a MeeGo mobile os logo:

MeeGo: http://www.smartdroid.de/wp-content/uploads/2012/07/meego-logo.png

**Comment by aethior** [comment]
>The Linux Foundation canceled MeeGo in September 2011 in favor of [Tizen](https://en.wikipedia.org/wiki/Tizen). ([more info](https://en.wikipedia.org/wiki/MeeGo))

- https://github.com/FortAwesome/Font-Awesome/issues/4958

cc/ @tagliala
