### ISSUE TITLE
Icon Request: fa-ban-thin

### ISSUE THREAD

**Issue by w3l** [FortAwesome/Font-Awesome#4960]
Would love to see a version of fa-ban in the same thickness as circle-thin. Stacked fa-ban hides to much of the original icon imo.

Use cases:

![github](https://cloud.githubusercontent.com/assets/2707757/5008960/0cc97066-6a62-11e4-93ef-04688b7543ba.png)

^^ Would be nice to stack fa-circle and fa-ban with the same thin thickness.

**Comment by itcig** [comment]
+1

**Comment by mfrejnik** [comment]
:+1:

**Comment by ebrost** [comment]
+1

**Comment by teemuremes** [comment]
+1

**Comment by mflayhart** [comment]
+1

**Comment by ShawnOakley** [comment]
+1
