### ISSUE TITLE
Icon does not display inside ReactJS component after re-render on Safari (desktop & mobile)

### ISSUE THREAD

**Issue by harborhoffer** [FortAwesome/Font-Awesome#4961]
This is an odd issue that I can duplicate on both safari for mac and IOS8. I am rendering a FA icon inside a React component just fine. When I update the state of my component that triggers a different icon rendered, the icon is not displayed. I can see in the safari web inspector that the class name does change. In my case, fa-play -> fa-stop. However the stop icon does not appear; it's just empty. On chrome, things work as expected.

**Comment by juanparadox** [comment]
I am coming across the same issue on Chrome using React.

If I conditionally render an icon say:
```
{ foo
  ? <i className="fa fa-plus"></i>
  : <i className="fa fa-minus"></i>
}
```
It will render the first icon which equates to true, but will not render any other icon after that. If I wrap each icon in a div and give them their own classes, I can see the classes change on rerender, but the icons stay the same.

**Comment by gilnetoglartek** [comment]
I still have the same issue.
Any news regarding this?

**Comment by tagliala** [comment]
there is a react component: https://fontawesome.com/how-to-use/js-component-packages#react
