### ISSUE TITLE
Icon Request: fa-engagement-ring

### ISSUE THREAD

**Issue by JWTechSolutions** [FortAwesome/Font-Awesome#4963]
I would like engagement and/or wedding rings. If possible it would be nice to have a stand alone ring like the first picture and a set of rings like the second picture.

![engagement-ring](https://cloud.githubusercontent.com/assets/9329531/5016485/84b44580-6a5b-11e4-9e7d-9b3d1f9c968a.jpg)

![wedding_10c](https://cloud.githubusercontent.com/assets/9329531/5016506/9d4c470a-6a5b-11e4-8c91-7d1958fa85e2.jpg)

**Comment by Danny-mcc** [comment]
+1

**Comment by shaunrainer** [comment]
+1

**Comment by GwenLoguir** [comment]
+1

**Comment by wildfireheart** [comment]
+1

**Comment by lyhil** [comment]
+1

**Comment by jm-code-com** [comment]
+1

**Comment by khasky** [comment]
+1

**Comment by schalkjoubert** [comment]
+1

**Comment by shmendo** [comment]
+1

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
💍 [U+1F48D](https://emojipedia.org/emoji/%F0%9F%92%8D/) Ring
Also known as `Diamond Ring` ans `Engagement Ring`.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/ring-diamond?s=solid
https://fontawesome.com/icons/rings-wedding?s=solid
