### ISSUE TITLE
Icon Request: fa-towtruck

### ISSUE THREAD

**Issue by ProtossSolutions** [FortAwesome/Font-Awesome#4972]
Hello, 

I would greatly appreciate if you could upload a tow truck icon. 
It would be great for tow truck companies. 
You can find an example below: 
www.gopixpic.com/306/tow-truck-icon-in-9-colors-royalty-free-stock-vector-art-illustration/http:||i*istockimg*com|file_thumbview_approve|4039706|2|stock-illustration-4039706-tow-truck-icon-in-9-colors*jpg/

Regards,

**Comment by luansilas** [comment]
+1

**Comment by djheffer** [comment]
+1

**Comment by PeterRangelov** [comment]
+111111

**Comment by spmarco** [comment]
+11111111

**Comment by G-Driver** [comment]
+1

**Comment by deefees** [comment]
+1

**Comment by jnegron357** [comment]
+1

**Comment by jpsantos7** [comment]
+1

**Comment by ktonder** [comment]
I have modified the fa-truck to be more like a towtruck, dont know if its useful for anyone here :) 

![fa-towtruck](https://cloud.githubusercontent.com/assets/3051153/14460305/247a5d5e-00bd-11e6-9ed2-abc1f3716782.png)

Would be nice to have this in the package too.

**Comment by madcowke** [comment]
+111111

**Comment by jennyanthony** [comment]
+1

**Comment by cesar128** [comment]
Bump, +1

**Comment by broot02** [comment]
+1

**Comment by kiag0** [comment]
+1 for real!!

**Comment by augea22** [comment]
+1

**Comment by broot02** [comment]
It appears that the icon initially proposed is no longer available, I am assuming we would move forward with the icon provided by @ktonder?

**Comment by RahlForge** [comment]
+1

**Comment by dschweitzer** [comment]
+1

**Comment by ppectol** [comment]
2013 to 2019... Any word on if this will be available anytime soon?

**Comment by richardkeller411** [comment]
Bump..   Lots of closed references..   Is this implemented?

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
