### ISSUE TITLE
Icon Request: fa-sushi-roll

### ISSUE THREAD

**Issue by newmesiss** [FortAwesome/Font-Awesome#4985]
I am creating categories and one of them got one for sushi, and for that I would like an icon of a rolls

![GitHub Logo](http://i.imgur.com/O1ieSsG.png)

**Comment by stevensacks** [comment]
I would use singular “sushi-roll” for this one.

**Comment by sensibleworld** [comment]
This has been added to v6: https://fontawesome.com/v6.0/icons/sushi-roll?s=duotone
