### ISSUE TITLE
Icon request:fa-ns-CHF, fa-ns-USD, fa-ns-HKD ...  Non symbolic currencies

### ISSUE THREAD

**Issue by RobStevnson** [FortAwesome/Font-Awesome#4986]
As a program I'd love to see just text currency symbols in particular "US$" instead of just "$" or "CHF" for Switzerland or "HK$" for Hongkong dollar.
REASON:
To list currency symbols we need to look up a table if an icon is there and otherwise write the letters. It always looks ugly. It would be so cool having a text based icon for everything, all same size... Meaning even the letters CHF or US$ are iconized.

fa-ns-XXX - ns for "nonsymbolic" - I know its awkward - asking to create an icon for text but if you code financial apps this would be really really cool :) 

Here is the whole enchilada
http://symbologic.info/currency.htm

Thanks a lot for considering it. If we can help doing it - more than happy to help.

Rob

**Comment by tagliala** [comment]
Please open individual requests for non-symbolic currencies filling out [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
