### ISSUE TITLE
Icon Request: fa-user-with-graduation-cap (graduate, teacher)

### ISSUE THREAD

**Issue by skystudiostv** [FortAwesome/Font-Awesome#4987]
I love font awesome, thanks so much for this amazing tool and we want to use it in a website project for a large university. 

It  would be awesome if there is an Icon of a Graduate person. 
I think many schools and universities will be able to use this...

This will basically be a mix of these two icons:

(fa-user)  with  (fa-graduation-cap)  on (fa-user)'s head... along with some slight tweaking so that it looks like the person is wearing a graduands gown, as well as changing the white section of the graduates cap slightly so you see the bottom profile of the pointy cap.

I have made a sample for you below - using the two icons and tweaking it a bit.

![image](https://cloud.githubusercontent.com/assets/9770041/5058526/3d612e24-6cfd-11e4-820f-fd88b07f7841.png)

Many Thanks! Hope this Icon request finds favour!

**Comment by Abildtoft** [comment]
+1

**Comment by taalendigitaal** [comment]
+1

**Comment by andrevanberlo** [comment]
+1

**Comment by valentinacarlone** [comment]
+1

**Comment by hendrismit** [comment]
+1

**Comment by thegreatrazz** [comment]
+1

**Comment by cherrador** [comment]
Using stacks I'm able to create this:
![05](https://cloud.githubusercontent.com/assets/12229855/13385452/d5fa26de-de6e-11e5-9316-e5d122aba761.png)
Check my jsfiddle to see how it's done:
https://jsfiddle.net/cherrador/jomgLb2h/

**Comment by DelightRun** [comment]
+1

**Comment by ppp999** [comment]
+1

**Comment by nkamate** [comment]
+1

**Comment by stoem** [comment]
+1

**Comment by anisotton** [comment]
+1

**Comment by C0deZLee** [comment]
+1

**Comment by sensibleworld** [comment]
You're welcome!

https://fontawesome.com/icons?d=gallery&q=user-graduate
