### ISSUE TITLE
Icon Request: fa-backpack

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4992]
A casual backpack icon, which could also server as a camping icon.

**Comment by rdmccann** [comment]
+1

**Comment by MikeStardust** [comment]
+1

**Comment by mbrileyica** [comment]
+1

**Comment by helloroughton** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by rpetitto** [comment]
+1 fa-backpack 
![2551-200](https://cloud.githubusercontent.com/assets/16416100/11983152/ed198332-a976-11e5-899b-c3d4d59410a3.png)

**Comment by kennyeicher** [comment]
+1

**Comment by paulgrever** [comment]
+1

**Comment by marklanhamhc** [comment]
+1

**Comment by notflip** [comment]
+1

**Comment by tagliala** [comment]
Available in FA >= 5.2.0 Pro 

https://fontawesome.com/v6.0/icons/backpack
