### ISSUE TITLE
Icon Request: Thick up/down arrow

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#4996]
Hi all.,
i am big fan of Font Awesome, and using it in my projects .

There are various arrow icons already e.g. long and regular but 
but what it lacks is thick up/down arrow icons like these , these are two icons

![njmg009](https://cloud.githubusercontent.com/assets/6097059/5066308/64b7f6fa-6e57-11e4-9509-3ad559cdb41c.png)

for that i am currently using 
<span class="glyphicon glyphicon-arrow-up"></span>
<span class="glyphicon glyphicon-arrow-down"></span>
bootstrap's glyphicons .

Thanks for your time.

or is there any other way i can make already available icons thick ?

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/up?s=solid
https://fontawesome.com/v6.0/icons/down?s=solid
