### ISSUE TITLE
Icon request: icon-new-file

### ISSUE THREAD

**Issue by cirosantilli** [FortAwesome/Font-Awesome#4998]
Useful on many text editor apps. My particular use case is for gitlab, which currently uses a cryptic `+` sign to create a new file, much like GitHub's.

The first thing that comes to my mind is a file like http://fortawesome.github.io/Font-Awesome/icon/file-o/ with a `+` sign on the top or bottom right something like:

![](http://www.dannyadam.com/blog/wp-content/uploads/2011/10/new-empty-file-here.png)

**Comment by gamov** [comment]
+1

**Comment by tiagobuffon** [comment]
+1 #7053

**Comment by jabarnes** [comment]
+1

**Comment by cirosantilli** [comment]
@jabarnes please use the new +1 button feature to avoid notifying people ;-)

**Comment by aethior** [comment]
Hi @cirosantilli,

This has been added in v6.0.0.
https://fontawesome.com/icons/file-circle-plus

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
Hi @cirosantilli,

This icon has been added in v6.0.0.
https://fontawesome.com/icons/file-circle-plus

Regards.

cc/ @tagliala

**Comment by cirosantilli** [comment]
Thanks for the info.

**Comment by tagliala** [comment]
Didn't notice this was a duplicate of #3041

More information are available there
