### ISSUE TITLE
Icon request: icon-ipintoo

### ISSUE THREAD

**Issue by ritipatel** [FortAwesome/Font-Awesome#5002]
To display iPintoo profile on various websites.
![member_logo1](https://cloud.githubusercontent.com/assets/2300618/5082571/b1e3c1f8-6eb0-11e4-9af6-a8c96adbfd38.png)

![ipintoo_logo20](https://cloud.githubusercontent.com/assets/2300618/5082603/d76de998-6eb1-11e4-87f4-51325330d543.png)

**Comment by aethior** [comment]
I cant to find any information about this brand.
The `www.ipintoo.com` domain is down and I can't to find their social networks.

cc/ @tagliala
