### ISSUE TITLE
Icon request: icon-hellocoton

### ISSUE THREAD

**Issue by EmilieMHY** [FortAwesome/Font-Awesome#5008]
Hello guys!!

I'm building my first blog about Yoga on wordpress and I'm working on the social icons.
HelloCoton is a very famous social plateform for blogs and that would be sooooo great to be able to have an nice icon to add it through the social icon plugin in Wordpress.
![hellocoton_logo](https://cloud.githubusercontent.com/assets/9845879/5108077/6c15f51c-7007-11e4-9d82-4be1059a0e9d.png)

http://www.hellocoton.fr/

I put an example attached. I hope it'll help!

Please let me know if you have any question.

Many thanks for your help!

**Comment by helloblogzine** [comment]
Hello ! I have a same problem, I would love to have an Hello Coton icon as well for my lifestyle blog. My them only works with font awesome so there is no other way I can get this icon ;-)

Many thanks !

Ann

**Comment by justmona** [comment]
Hello,
I have the same problem. Hello Coton is a really famous social network in France that helps to generate traffic to your blog. So I'll be so thankful if you could add it.

Thanks for your help !

**Comment by Joane27** [comment]
Hello,

I would like to know if these requests are still open because there's no icon for Hellocoton network in your icons database right now. Is it possible to create it please ?
I need it too and I can see that anybody replied to previous requests.

Thank you :)

**Comment by AinaBe** [comment]
Hello, I'm doing a blog too, and I'll need this icon too. Here's one I've just done in a vector EPS file : https://www.dropbox.com/s/4xflbc697fwiqiw/hellocoton.eps?dl=0, if it can help to be implemented rapidly :) Thanks !

**Comment by lauretteflechette** [comment]
Hello ! 
The same juste here ! Please could you add the icon ? It's a very famous social network in France ! Thanks for us !

**Comment by loislecorre** [comment]
Hey ! 
Has it been uploaded? Still can't find it, and it would be perfect to have the Hellocoton icon !

**Comment by AntoineSoetewey** [comment]
Anyone can help on this issue?

**Comment by Sarah1777** [comment]
I still don't see it as available since 2014. Do you know if anybody is working on it?

**Comment by aethior** [comment]
Hellocoton was closed in 2019. ([more info](https://fr.wikipedia.org/wiki/Hellocoton))

Regards.

cc/ @tagliala
