### ISSUE TITLE
Icon Request: Car wash

### ISSUE THREAD

**Issue by lenamtl** [FortAwesome/Font-Awesome#5009]
Icon Request: Car wash 

example:
http://www.shutterstock.com/pic-126182819/stock-vector-car-wash-icons-set-vector.html?src=pp-same_artist-130861793-RhKKZqLFaqO3YMGDajrZ4w-2

**Comment by lenamtl** [comment]
+1

**Comment by linoystephen** [comment]
+1

**Comment by WaynePhipps** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/car-wash?style=solid
