### ISSUE TITLE
Icon Request: icon-tripadvisor

### ISSUE THREAD

**Issue by seanpatrick** [FortAwesome/Font-Awesome#5013]
We use Font Awesome on all of our templates for clients now and even on some custom websites. We work in the hospitality industry so TripAdvisor is very common. It's even now more common with restaurants and just about any business you can review. We would LOVE to have this as an icon since it's basically a social network now. 

Thanks!

TripAdvisor Logo: http://www.iconsdb.com/icons/preview/black/tripadvisor-xxl.png

**Comment by smoore0509** [comment]
+1 here! I have two customers who need this.

**Comment by CNK001** [comment]
+1
