### ISSUE TITLE
Icon request: fa-file-csv-o

### ISSUE THREAD

**Issue by Christilut** [FortAwesome/Font-Awesome#5015]
For CSV and XML files it would be nice to be able to represent those as an icon.

Personally I need these two but other cases come to mind such as JSON and YAML that might also be worth creating.

**Comment by rajdsouza** [comment]
+1

**Comment by cuttingedgehobbies** [comment]
+1

**Comment by wbartley** [comment]
+1

**Comment by eporral1** [comment]
+1

**Comment by jphellemons** [comment]
+1

**Comment by bamblack** [comment]
+1

**Comment by ejohansson** [comment]
+1

**Comment by nurikabe** [comment]
+1

**Comment by zpef** [comment]
+1

**Comment by epwinchell** [comment]
+1

**Comment by busuttil** [comment]
+1

**Comment by devbnz** [comment]
+1

**Comment by anestik** [comment]
+1

**Comment by dev-admin-switcher-ie** [comment]
:+1:

**Comment by mmorava** [comment]
:+1:

**Comment by Naddiseo** [comment]
+1

**Comment by jchicks** [comment]
+1

**Comment by openbrian** [comment]
+1

**Comment by elite123** [comment]
+1

**Comment by amirazizian** [comment]
+1

**Comment by ev4debug** [comment]
+1

**Comment by Mi-La** [comment]
+1

**Comment by patrick-gill** [comment]
+1

**Comment by gherkins** [comment]
👍

**Comment by hrodrigues1984** [comment]
+1

**Comment by loona70** [comment]
+1

**Comment by FlickTheManual** [comment]
+1

**Comment by Ishangidwani** [comment]
+1

**Comment by Ishangidwani** [comment]
+1

**Comment by jhiver** [comment]
+1

**Comment by vishak-kavalur** [comment]
+1

**Comment by FlickTheManual** [comment]
+1

**Comment by klandell** [comment]
+1

**Comment by poyrazus** [comment]
+1000

**Comment by Enrique199413** [comment]
+1

**Comment by rAugustos** [comment]
+1

**Comment by mikebotazzo** [comment]
+1

**Comment by brutto** [comment]
+1

**Comment by t9toqwerty** [comment]
+1

**Comment by sheikhfaisalanwar** [comment]
+1

**Comment by bkahraman** [comment]
+1

**Comment by dtagdev1** [comment]
+1

**Comment by glemmal** [comment]
+1

**Comment by 2KNole** [comment]
+1

**Comment by josephtheberge** [comment]
+1

**Comment by donovanclarke** [comment]
+1

**Comment by xuancanpro** [comment]
why i can't display fa fa-file-csv-o or fa fa-file-xml-o?

**Comment by JHFirestarter** [comment]
+1 (just duplicate fa-file-excel-o and replace "x" with smaller "csv")

**Comment by gustavomatheus** [comment]
+1

**Comment by galorpaz** [comment]
+1

**Comment by pedrojsn96** [comment]
+1

**Comment by bahrinka** [comment]
+1

**Comment by nicktobolski** [comment]
+1

**Comment by robsilva** [comment]
+1

**Comment by karimcambridge** [comment]
+1 .. please

**Comment by goudacode** [comment]
+1, this would be nice, do you guys accept pull requests?

**Comment by Fukotaku** [comment]
+1

**Comment by kiakaku** [comment]
+1

**Comment by edisonia** [comment]
+1

**Comment by bidossessi** [comment]
+1

**Comment by mjedwabn** [comment]
+1

**Comment by silvanthoma** [comment]
+1

**Comment by KonstantinSchubert** [comment]
:+1:

**Comment by gaurang90** [comment]
+1

**Comment by p51i** [comment]
+1

**Comment by sagarkul** [comment]
+1

**Comment by AlexDovgan** [comment]
+1

**Comment by gabsoftware** [comment]
I cannot believe this does not exist in Fontawesome 5. Please add!

**Comment by rogeralbinoi** [comment]
+1

**Comment by gabrielrigon** [comment]
+1

**Comment by DjameleddineBourahla** [comment]
+1

**Comment by wdehaes** [comment]
+1

**Comment by rosnaib11** [comment]
+1

**Comment by eiko8** [comment]
+1

**Comment by thomascorthals** [comment]
+1

**Comment by vishak-kavalur** [comment]
Dude. Seriously. Stop commenting!!

**Comment by kshitijmehta** [comment]
1) Using Font-Awesome-5 
2) class='fas fa-file-csv-o'

3) Cannot see the icon  

4) What's wrong ?

5) Your Answer please

**Comment by sensibleworld** [comment]
@kshitijmehta This is an open icon request, and does not yet exist in Font Awesome. But we're hoping to get to it soon: https://fontawesome.com/community/leaderboard/new

**Comment by arubiogfi** [comment]
+1

**Comment by ArtixZ** [comment]
+1

**Comment by LucaAnzaldo** [comment]
+1

**Comment by marcoiai** [comment]
+1

**Comment by mortenbirkelund** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by Oxicode** [comment]
+1

**Comment by emilyfennell** [comment]
+1

**Comment by eternal-freedom** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-spreadsheet?style=solid

**Comment by gabsoftware** [comment]
@sensibleworld: Thanks, but how does the file-spreadsheet icon address the original issue, missing CSV icon?

CSV is a data format, not a spreadsheet.

We need a true CSV icon with "CSV" on it so that it is easily recognized by users.

**Comment by sensibleworld** [comment]
Thanks for the feedback, @gabsoftware. We've been trying to avoid adding icons that have text overlaid on them as much as possible, especially because this can be accomplished using our layering: https://fontawesome.com/how-to-use/on-the-web/styling/layering (and https://codepen.io/fontawesome/pen/aKNXmp).

That said... we can see the value in a select few (CSV, XML, etc), and will certainly consider it. I'll re-open this issue for now.

**Comment by gabsoftware** [comment]
Thanks, that kind of icon will be used for CSV export and users need to know in which format they export their data.

**Comment by Chris-KCIT** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-csv?style=solid
