### ISSUE TITLE
Icon Request: fa-playerme

### ISSUE THREAD

**Issue by Kyzriel** [FortAwesome/Font-Awesome#5020]
Player.me is a social media site directed towards gamers, so the icon would be used used similarly to how the Facebook or Twitter icons are used.

Logo (250px)
![Player.me Logo](https://player.me/logo-250.png)

Officially released brand assets (for alternate versions?): [playerdotme-brand.zip](https://player.me/playerdotme-brand.zip)

Thanks for your time and effort.

**Comment by CRS-ECHO51** [comment]
:up:

**Comment by faeldray** [comment]
:+1:

**Comment by willowen100** [comment]
Any update on this?

**Comment by aethior** [comment]
>Unfortunately Player.me will be shutting down on the 11th April 2022 but we recommend you check out Gamecaster if you're looking for streaming and overlays, or Guilded if you're looking for gaming community tools. Thanks for all your support! ([source](https://player.me/))

cc/ @tagliala
