### ISSUE TITLE
Icon request: icon-e-guitar

### ISSUE THREAD

**Issue by juergenlink** [FortAwesome/Font-Awesome#5031]
I am currently looking for icons for a band's equipment.
As I'm already Font Awesome it would be nice if these icons would be available.

At least one or maybe two versions of electric guitar icons would be nice :)

**Comment by mike-stumpf** [comment]
+1

**Comment by ralphonz** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=guitar
