### ISSUE TITLE
icon requests out of control

### ISSUE THREAD

**Issue by KOTRET** [FortAwesome/Font-Awesome#5039]
seriously: while browsing through all issues there are more and more upcoming brand requests and all done in the same manner:
"Hey, the icon of [brand] needs to be included, its a famous [language here] [community|market|shop|whatever]"

In most cases: **it's not**!
Please dump that request and focus on the real ones. The icon font will get bloatet and there are not many contributors for this _crap_.

People have to think about the use of this font: **is my icon a general one or a specific use-case** (like many brands). Is there any other icon font for my weather- / dj- / file- / whatever-icons - in most cases there are. Following these thoughts approximately 85% of all issues could be closed.

my 2 Cents

**Comment by mizerydearia** [comment]
I am interested to contribute to design some icons. Where do I look to find out how to contribute?
