### ISSUE TITLE
Icon Request: fa-pulse

### ISSUE THREAD

**Issue by eashancode** [FortAwesome/Font-Awesome#5040]
I need an icon for a reflect pulse symbol

Thanks Team!

**Comment by eashancode** [comment]
Hi Team!
Extremely sorry for the delay from my side. This is the suggestion for the fa-pulse icon.

Thanks!
Eashan code
![pulse_icon_fa_pulse](https://cloud.githubusercontent.com/assets/9126937/7718482/9d079378-fece-11e4-8506-fecdda8b81a5.png)

**Comment by tagliala** [comment]
duplicate of #3206 , please +1 that request

closing here
