### ISSUE TITLE
Icon Request: fa-grid (fa-th-o)

### ISSUE THREAD

**Issue by hzxie** [FortAwesome/Font-Awesome#5045]
I want a icon like ![icon-grid](http://demo.samuli.me/wp/smartstart/wp-content/themes/smartstart/images/icon-grid.png)

I want to used in the [page](http://demo.samuli.me/wp/smartstart/portfolio-item/altered/)

Please look at the right side of the "All Projects"

**Comment by Joeao** [comment]
Hi fellas,

I was also hoping for a more grid-like icon. Though was thinking of something more like a naughts and crosses type grid: Without an outer border - http://www.dangerspot.co.uk/images/naughtsandcrosses.jpg. 
The purpose of which is to resemble moving objects around on a grid, e.g: http://codepen.io/briangonzalez/pen/274f06f80ad088eb8ce09f020d88f848

For now, fa-th is very suitable, maybe even fa-table or a hashtag in a certain font.

**Comment by Charuru** [comment]
Grid is pretty vital for mobile.

**Comment by amstec** [comment]
How about a th-small that is a 4x4 to add to the 3x3 th and 2x2 th-large. Also a th-xsmall 5x5 would also be great. Thank you!

**Comment by saas786** [comment]
+1

**Comment by Cyral** [comment]
:+1: +1:

**Comment by Jhawins** [comment]
Still needs this

**Comment by Chinese1904** [comment]
Really would love to see this as well!

2x2 th large
3x3 th
4x4 th small

I think this would be a great addition considering. Somewhat like Themify does:

<img width="641" alt="screen shot 2017-02-04 at 8 30 29 pm" src="https://cloud.githubusercontent.com/assets/6228425/22623714/df7d5fa2-eb18-11e6-920a-9f091f05d5c8.png">

**Comment by tagliala** [comment]
This icon is available in FA5 Pro

- https://fontawesome.com/icons/th?style=regular

https://fontawesome.com/icons/border-all?style=regular may also fit the use case
