### ISSUE TITLE
Icon Request:fa-crying-face

### ISSUE THREAD

**Issue by magnuskjellen** [FortAwesome/Font-Awesome#5049]
Use as the "sadest" alternative in a five grade scale (see #5048).

I imagine it would look like fa-frown-o, but with an little tear below the right eye.

**Comment by aethior** [comment]
Hi @magnuskjellen,

This icon was added in v5.1.0.
Check https://fontawesome.com/icons/face-sad-cry

Regards.

cc/ @tagliala
