### ISSUE TITLE
Icon request: fa-milk-bottle

### ISSUE THREAD

**Issue by privatemiao** [FortAwesome/Font-Awesome#5051]
hi
i need a coup of icon about baby track
fa-milk-bottle
fa-diaper
fa-Cradle when baby sleep

thanks

**Comment by G-Driver** [comment]
+1

**Comment by flaviomiranda7** [comment]
Hi, I need icons for a shop I'm developing to selling grocery products. I need icons: milk, meat, rice, cereal, juice, frozen, soap, bottle, toilet paper, cheese, seasoning, dog, candy, cookies, among others.
How can I get?

**Comment by phishyatl** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-milk-bottle was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by tagliala** [comment]
Milk: #3663
