### ISSUE TITLE
Icon Request: fa-piano

### ISSUE THREAD

**Issue by ruvenss** [FortAwesome/Font-Awesome#5054]
There are basically no instruments for music sites so please make the basic orchestra instruments :+1: 
Drums, Guitars, Piano, Violin  harpsichord, and organ, electric guitar, ondes Martenot,  bagpipes, vihuelas, hurdy-gurdies, saxo, etc...

![instrumnets](https://cloud.githubusercontent.com/assets/3003888/5200858/a2797620-756a-11e4-9447-2cc0e97206d0.png)

**Comment by ichec2** [comment]
+1

**Comment by hetzijzo** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by henoliv** [comment]
+1

**Comment by peteremiljensen** [comment]
+1

**Comment by peteremiljensen** [comment]
+1

**Comment by tuxzz** [comment]
+1

**Comment by MuBaseJannik** [comment]
+1

**Comment by craigallyn** [comment]
+1

**Comment by tscole** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by biancanev** [comment]
+1

**Comment by Kamaropoulos** [comment]
That would be a nice one to have! +1

**Comment by Kamaropoulos** [comment]
Also, this one was opened 4 years ago 😛 
Does it always take too long to add new icons?

**Comment by fretzMX** [comment]
+1

**Comment by stijnfrishert** [comment]
+1

**Comment by MillerMedia** [comment]
+1

**Comment by EssKegar** [comment]
I was looking for a piano icon and couldn't find one. +1 to this request!

**Comment by EssKegar** [comment]
> Also, this one was opened 4 years ago 😛
> Does it always take so long to add new icons?

Only when they don't care lol

**Comment by sensibleworld** [comment]
Font Awesome 5.11 is out with a couple of new piano icons: https://fontawesome.com/icons?d=gallery&q=piano
