### ISSUE TITLE
Icon Request: fa-violin

### ISSUE THREAD

**Issue by ruvenss** [FortAwesome/Font-Awesome#5055]
There are basically no instruments for music sites so please make the basic orchestra instruments :+1: 
Drums, Guitars, Piano, Violin  harpsichord, and organ, electric guitar, ondes Martenot,  bagpipes, vihuelas, hurdy-gurdies, saxo, etc...

![instrumnets](https://cloud.githubusercontent.com/assets/3003888/5200858/a2797620-756a-11e4-9447-2cc0e97206d0.png)

**Comment by ichec2** [comment]
+1

**Comment by hetzijzo** [comment]
+1

**Comment by oBrad77** [comment]
+1

**Comment by tc7200** [comment]
+1

**Comment by DrewNull** [comment]
+1

**Comment by kiyoonko** [comment]
+1

**Comment by jcleneveu-geny** [comment]
+1

**Comment by calderJamNet** [comment]
+1

**Comment by tazmwebsolutions** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by sensibleworld** [comment]
We've got a whole bunch of instruments now: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=instrument&s=solid

<img width="1043" alt="Screen Shot 2021-05-27 at 2 09 05 PM" src="https://user-images.githubusercontent.com/529604/119875739-198f0380-bef5-11eb-99cb-b092d813a5f9.png">
