### ISSUE TITLE
Icon Request: fa-drum

### ISSUE THREAD

**Issue by ruvenss** [FortAwesome/Font-Awesome#5056]
There are basically no instruments for music sites so please make the basic orchestra instruments :+1: 
Drums, Guitars, Piano, Violin  harpsichord, and organ, electric guitar, ondes Martenot,  bagpipes, vihuelas, hurdy-gurdies, saxo, etc...

![instrumnets](https://cloud.githubusercontent.com/assets/3003888/5200858/a2797620-756a-11e4-9447-2cc0e97206d0.png)

**Comment by ichec2** [comment]
+1

**Comment by hetzijzo** [comment]
+1

**Comment by mike-stumpf** [comment]
+1

**Comment by damusix** [comment]
+1

**Comment by parag-datar** [comment]
+1

**Comment by Raphoka** [comment]
+1

**Comment by chiccorosso** [comment]
+1

**Comment by maximerafaillac** [comment]
+1

**Comment by cbcoutinho** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by sensibleworld** [comment]
Currently working on some other music-related icons, but wanted to close this particular issue because we added `fa-drum` back in 5.1.0: https://fontawesome.com/icons/drum?style=solid
