### ISSUE TITLE
Icon Request: fa-saxo

### ISSUE THREAD

**Issue by ruvenss** [FortAwesome/Font-Awesome#5058]
There are basically no instruments for music sites so please make the basic orchestra instruments :+1: 
Drums, Guitars, Piano, Violin  harpsichord, and organ, electric guitar, ondes Martenot,  bagpipes, vihuelas, hurdy-gurdies, saxo, etc...

![instrumnets](https://cloud.githubusercontent.com/assets/3003888/5200858/a2797620-756a-11e4-9447-2cc0e97206d0.png)

**Comment by ichec2** [comment]
+1

**Comment by hetzijzo** [comment]
+1

**Comment by tjferry14** [comment]
+1

**Comment by damusix** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=sax
