### ISSUE TITLE
Icon Request: fa-guitar

### ISSUE THREAD

**Issue by ruvenss** [FortAwesome/Font-Awesome#5059]
There are basically no instruments for music sites so please make the basic orchestra instruments :+1: 
Drums, Guitars, Piano, Violin  harpsichord, and organ, electric guitar, ondes Martenot,  bagpipes, vihuelas, hurdy-gurdies, saxo, etc...

![instrumnets](https://cloud.githubusercontent.com/assets/3003888/5200858/a2797620-756a-11e4-9447-2cc0e97206d0.png)

**Comment by ichec2** [comment]
+1

**Comment by ruvenss** [comment]
:+1:

**Comment by hetzijzo** [comment]
+1

**Comment by bertoost** [comment]
+1 for multiple music instruments :-)

**Comment by PageZoso** [comment]
+1 guitar ... and any additional instruments

**Comment by domtronn** [comment]
+1

**Comment by Elorfin** [comment]
+1

**Comment by p0l16r4f** [comment]
+1 for guitar !

**Comment by thombuchi** [comment]
+1

**Comment by sdanan** [comment]
+1

**Comment by xbitres** [comment]
+1

**Comment by ryankane** [comment]
# Example Vectors...

## fa-guitar-acoustic-o

![fa-guitar-acoustic-o](http://i.imgur.com/4rNOknH.png)

## fa-guitar-acoustic

![fa-guitar-acoustic](http://i.imgur.com/XxnLc3M.png)

## fa-guitar-electric-o

![fa-guitar-electric-o](http://i.imgur.com/6eCnvQe.png)

## fa-guitar-electric

![fa-guitar-electric](http://i.imgur.com/4XbaFCX.png)

**Comment by mike-stumpf** [comment]
+1

**Comment by mike-stumpf** [comment]
+1

**Comment by Raphoka** [comment]
+1

**Comment by mgrachev** [comment]
:+1:

**Comment by bistory** [comment]
+1

**Comment by jeekwong** [comment]
+1 for guitar

**Comment by jbnv** [comment]
+1 for guitar, keyboard and saxophone.

**Comment by honzyck** [comment]
+1

**Comment by Sogl** [comment]
+1 for guitar!

**Comment by lpalliyaguru** [comment]
+1 for guitar!

**Comment by AdrienTorris** [comment]
Waiting the integration of musical instrument icons in Font Awesome, there is a good free icon pack on [smashing magazine](https://www.smashingmagazine.com/2016/05/freebie-music-instrument-icons-39-icons-png-svg/)

**Comment by prtkgoswami** [comment]
+1 for guitar

**Comment by Woloszyn** [comment]
+1 for guitar

**Comment by trevorteusc** [comment]
I absolutely agree with all of the above!!!

**Comment by ManuAlvarado22** [comment]
I laughed with your definition of a basic orchestra, but i absolutely agree.

**Comment by drehimself** [comment]
Guitar + other instrument icons would be awesome!

**Comment by yagogak** [comment]
+1

**Comment by ralphonz** [comment]
+1

**Comment by SorenSaket** [comment]
+1

**Comment by miguelbaldi** [comment]
+1

**Comment by lucaszmoraes** [comment]
+1

**Comment by tomav** [comment]
At least:
* guitar
* bass
* drums (event if there's already something)
* microphone

**Comment by sensibleworld** [comment]
We'll be getting to musical instruments soon. In the meantime, we do now have a mandolin icon: https://fontawesome.com/icons/mandolin?style=solid

**Comment by KungFuJosh** [comment]
I dunno. It looks more like a "Clean Stream Bag" than a mandolin.

**Comment by sensibleworld** [comment]
@KungFuJosh Well, there you go... it's a dual-purpose icon.

**Comment by ralphonz** [comment]
> @ralphonz It was part of our recent Table Top Gaming category. I just wanted to mention it in this thread, in case it was useful to anyone waiting on guitar icon.

Not even going to ask what a mandolin has to do with table top gaming!

**Comment by sensibleworld** [comment]
@ralphonz It's a common icon to represent "bards". And sometimes you just need to rock out to Greensleeves while rolling dice.

Anyway, sorry to hijack the guitar thread!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=guitar

**Comment by marleyiam** [comment]
Such a long time and I'm still waiting so bad.

**Comment by sensibleworld** [comment]
@marleyiam We released a guitar icon back in December :) https://fontawesome.com/icons?d=gallery&q=guitar

**Comment by marleyiam** [comment]
that's great news, thank you @sensibleworld !
