### ISSUE TITLE
Icon Request: fa-pauseplay

### ISSUE THREAD

**Issue by mikethrussell** [FortAwesome/Font-Awesome#5065]
Pause/Play icon - for music and video players with a toggle.

Like this: https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/media-play-pause-resume.png

**Comment by Crissov** [comment]
So not U+23EF ⏯, but more like a rotated Eject symbol U+23CF ⏏ [`fa-eject`](http://fontawesome.io/icon/eject/) or juxtaposed Step Forward [`fa-step-forward`](http://fontawesome.io/icon/step-forward/)? This is similar to some variants of Slow Play #6495, Slow Forward #4215 and (Re-)Play from Start.

**Comment by orassayag** [comment]
I need a playpause icon.
https://www.iconfinder.com/icons/2337855/media_controls_pause_pauseplay_play_play_pause_play_pause_button_icon

**Comment by lfernandes** [comment]
> I need a playpause icon.
> https://www.iconfinder.com/icons/2337855/media_controls_pause_pauseplay_play_play_pause_play_pause_button_icon

I still believing that an play-pause icon in FontAwesome will be very useful in many cases. But just if someone else is looking for it and might didn't realised that, you can try to add one icon after another.

On CSS, would be something like:

`<i class="fa fa-play"></i> <i class="fa fa-pause"></i>`

Hope that will be useful to someone. _Sometimes we are too focused in something that we don't see simple solutions like this_ 😉.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/play-pause?s=solid
