### ISSUE TITLE
Icon Request: fa-fitenes

### ISSUE THREAD

**Issue by zamoroka** [FortAwesome/Font-Awesome#5067]
![fitenes_health_icon](https://cloud.githubusercontent.com/assets/9164112/5207145/3fe69c2c-75b0-11e4-81d6-77077642d62f.png)

**Comment by aethior** [comment]
- https://fontawesome.com/icons/weight-scale
- https://fontawesome.com/icons/dumbbell
- https://fontawesome.com/icons/person-running
- https://github.com/FortAwesome/Font-Awesome/issues/8437 

cc/ @tagliala
