### ISSUE TITLE
Icon request: Radar

### ISSUE THREAD

**Issue by sethdeckard** [FortAwesome/Font-Awesome#507]
Ignore this if you think it's stupid but I think would be nice to have a radar icon.  To see what I mean use this google image search: https://www.google.com/search?q=radar+icon&hl=en&tbo=d&prmd=imvns&source=lnms&tbm=isch&sa=X&ei=E_B2UJb9LaTK2AWqtoHQBQ&ved=0CAcQ_AUoAA&biw=1246&bih=1032

**Comment by bbibeault-lifesize** [comment]
I'd like to see this added; please re-open. Specifically along the lines of: http://i.imgur.com/dHKZn8B.png

**Comment by sethdeckard** [comment]
Forgot I even opened this. I was thinking something more along the lines of weather radar, like this: http://a2.mzstatic.com/us/r30/Purple/v4/b7/5e/f6/b75ef603-78dd-aefc-8f7d-66a60e1f9627/RadarIconPro.175x175-75.png

Or even something a bit more generic like this: http://simpleicon.com/wp-content/uploads/radar-31.png

**Comment by bbibeault-lifesize** [comment]
OK, I'll open a new request for a "radar-dish"

**Comment by LauritzT** [comment]
+1

**Comment by texduc** [comment]
Did this ever get built? I would like to see a radar icon stylized similar to an old WWII navy radar; combine this with the spin feature so only the radar needle spins if possible and display the blips on every rotation... would be very font awesome!

**Comment by texduc** [comment]
> 
> 
> I'd like to see this added; please re-open. Specifically along the lines of: http://i.imgur.com/dHKZn8B.png

Dude that is not a radar; it's a satellite dish.
