### ISSUE TITLE
Icon Request: fa-arrow-updown

### ISSUE THREAD

**Issue by sanderdekkers** [FortAwesome/Font-Awesome#5074]
A arrow that shows up and down as in the attached image, this can be used to show the total upload and download traffic
Preferably the current icons fa-arrow-up and fa-arrow-down combined.

![arrow-up-down-2-512](https://cloud.githubusercontent.com/assets/4777954/5214994/32de2de2-7623-11e4-9445-bfcea7fd62bb.png)
![arrow-updown-icon](https://cloud.githubusercontent.com/assets/4777954/5214978/195254ca-7623-11e4-9cf9-de5551ee884d.png)

**Comment by mervinva** [comment]
+1

**Comment by tagliala** [comment]
Available in FA6 Pro https://fontawesome.com/v6.0/icons/arrow-up-arrow-down?s=solid
