### ISSUE TITLE
Icon request: icon-dinghy (fa-sailing-ship, sailboat)

### ISSUE THREAD

**Issue by lburgalassi** [FortAwesome/Font-Awesome#5079]
this icon can be used on all website concerning sea sports and activities (sailing centers, resorts, regattas,...) 

I need to describe a sailing center services including dinghy class.

![dinghy](https://cloud.githubusercontent.com/assets/1389625/5215836/a92c517e-762b-11e4-9e0d-e5fa8398ca34.png)

**Comment by vito52** [comment]
yes and... I'd like one that keeps with the over-all look and feel of the rest of the icons. This is pretty nice but I think too detailed to work as a black/white

**Comment by james-lavery** [comment]
+1

**Comment by wolvyreen** [comment]
+1

**Comment by beamaria** [comment]
Same request here: see attached icon (facebook) ⛵️⛵️

**Comment by rlefevere** [comment]
Same request. Looking to use this as an icon for leisure boat products. For this the existing 'ship' icon is not suitable. The emoji mentioned by beamaria would be a great base for the icon. Thanks in advance! Thumbs up.

**Comment by drudv** [comment]
Another voice requesting `fa-sailboat` icon.

**Comment by beamaria** [comment]
just had a look at the new sets in FontAwesome 5, but still no sign of a sailing boat icon... very disappointing    :-(

**Comment by pjsmits** [comment]
+1

**Comment by steveneal** [comment]
+1

**Comment by laflier** [comment]
+1 on the sailboat icon

**Comment by xmuskrat** [comment]
+1

**Comment by lewilewilewi** [comment]
+1 yes please!

**Comment by danielcongrove** [comment]
+1. I would like to see a fa-boat-side or fa-ship-side (like they have for car-side).

**Comment by iphilgoodtahiti** [comment]
+1 fa-speed-boat fa-sail-boat

**Comment by mshovelt** [comment]
+1 for a selection of sailing-related icons

**Comment by FreakyBytes** [comment]
+1 sailing vessel icon

**Comment by jrosseel** [comment]
+1

**Comment by kbsali** [comment]
+1

**Comment by GavOutdoors** [comment]
+1

**Comment by mnemocron** [comment]
+1

**Comment by mnemocron** [comment]
+1 why is it closed? i cannot find it in the font awesome search

**Comment by tagliala** [comment]
> +1 why is it closed? 

This is not closed, it contains a reference to a closed (duplicate) issue that may be misleading

**Comment by sensibleworld** [comment]
Only took us seven years 😅 https://fontawesome.com/v6.0/icons/sailboat?s=solid
