### ISSUE TITLE
Icon request: fa-hanger

### ISSUE THREAD

**Issue by sebasTuxPouliot** [FortAwesome/Font-Awesome#5083]
Would use them on many, many pages including this one :
http://dev.tablechampenoise.com/portfolio-items/sapiniere/?portfolioID=52

We use an anchor symbol to represent the place where the customer can leave their jacket but a hangar or a clockroom would be better.

![image](https://cloud.githubusercontent.com/assets/6369471/5218226/635c1412-7618-11e4-9d3c-b526cc031545.png)

Thanks guys,

**Comment by timtjtim** [comment]
Well, nothing's replaced it yet - 3 years later!
