### ISSUE TITLE
Icon request: fa-air conditioning

### ISSUE THREAD

**Issue by sebasTuxPouliot** [FortAwesome/Font-Awesome#5084]
Hi guys,

Icon request that would be use on many many pages including this one : 
http://dev.tablechampenoise.com/portfolio-items/sapiniere/?portfolioID=52

In french its "Climatisé" and we use the both way arrows.

This icon represent the fact that the room as an air conditioning system.

Below an image of what I have in mind :

![image](https://cloud.githubusercontent.com/assets/6369471/5218243/a17287c2-7618-11e4-8522-0ee857342687.png)

**Comment by ipro-ollie** [comment]
+1 AirCon

**Comment by MasterJuan** [comment]
+1 AirCon

**Comment by Haseeb717** [comment]
+1
