### ISSUE TITLE
Icon request: icon-megaphone

### ISSUE THREAD

**Issue by kubasub** [FortAwesome/Font-Awesome#5085]
**Use Cases**
- As an "alert"-type icon
- To inform users of promotions (events, sales, etc.)

**Samples**
![Megaphone 1](http://www.speechpower.ph/images/megaphone.png)
![Megaphone 2](https://cdn3.iconfinder.com/data/icons/advertising-icons/89/Advertising_icons-10-512.png)

**Comment by gktowle** [comment]
I'd like to request that this be reopened and that a request for a alternate style of bullhorn be considered. Maybe I'm splitting hairs, but the bullhorn that is currently available looks like something that would be used by police or at a political rally, whereas the bullhorn below (longer, thinner, with simple handle) is more representative of a sporting match (i.e. collegiate, American football). Thank you!

![bullhorn-icon](https://cloud.githubusercontent.com/assets/2250105/10087528/3912c6bc-62c9-11e5-9cbf-54969c182beb.png)

**Comment by tagliala** [comment]
@gktowle please open a new request with a proper title
