### ISSUE TITLE
Icon Request: fa-tap

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5091]
Hello, it would be great if you could add new icon called "fa-tap" which looks like this:

http://i.imgur.com/mzJryEn.png
![faucet-309209_640](https://cloud.githubusercontent.com/assets/8902575/5234332/d0d3629e-77bb-11e4-8842-999821fe9b27.png)

**Comment by aethior** [comment]
Duplicate of #10092.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks
