### ISSUE TITLE
Icon request: fa-pixiv

### ISSUE THREAD

**Issue by NABLACK** [FortAwesome/Font-Awesome#5093]
Would you please add a icon for pixiv.net just like this? I wanted to add my link to pixiv.net by this icon. Thanks a lot! 
![baiduhi_2014-11-30_19-14-35](https://cloud.githubusercontent.com/assets/10008301/5237429/1e89a588-78c6-11e4-92d4-aa57cb66957a.jpg)

**Comment by nasxgeek** [comment]
I need this!

**Comment by winterfuyu** [comment]
Please!!

**Comment by touka1037** [comment]
I need this!

**Comment by xcorpion77** [comment]
Hi, I need, please.

**Comment by SnO2WMaN** [comment]
+1

**Comment by l7u7ch** [comment]
+1

**Comment by winterfuyu** [comment]
Two years have past and still want it. 🤞

**Comment by crse** [comment]
Pixiv might be not a popular art site in the Western, but it is everywhere in Eastern art communities.
Alexa rank on Pixiv: 284
https://en.wikipedia.org/wiki/Pixiv

**Comment by OnikurYH** [comment]
Really want it, hope this could include in FontAwesome (O.O)

**Comment by segurvita** [comment]
+1 need it for a site

**Comment by adriculous** [comment]
As a digital artist who is a regular on DeviantArt, I hope to expand more of my art on different art community platforms, and Pixiv has become my favorite. Hoping we'd get this on FontAwesome soon!

**Comment by shuuji3** [comment]
The design of the icon was updated at some time. You can view the latest one here: https://www.pixiv.co.jp/news/press-kit/

**Comment by ChristianHinkle** [comment]
I need this too!

I am creating my personal website now and want to add a Pixiv icon for a social media link.

I am currently using this SVG from VeryIcon but it looks like it is very unoptimized for the web: https://www.veryicon.com/icons/internet--web/common-social-site-icons-for-the-web/pixiv.html.

**Comment by leonidboykov** [comment]
I'm not sure if there is any reason not to support the Pixiv icon in the FontAwesome, but you may use the one from the Simple Icons pack: https://simpleicons.org/?q=pixiv.

**Comment by kpossibles** [comment]
This has been open since 2014 so almost 10 years. Can this icon be added?

**Comment by sensibleworld** [comment]
This'll be in our next release!

**Comment by sensibleworld** [comment]
Added! https://fontawesome.com/icons/pixiv?f=brands&s=solid
