### ISSUE TITLE
fa-trash is not working in OSX

### ISSUE THREAD

**Issue by dandaka** [FortAwesome/Font-Awesome#5096]
0. OSX Yosemite 10.10.1 (14B25) / MBP retina 2013
1. Download font-awesome-4.2.0.zip
2. Unzip
3. Delete all previous versions of Font Awesome
4. Install latest in Font Book
5. Copy fa-trash symbol from http://fortawesome.github.io/Font-Awesome/cheatsheet/ ()
6. Paste into Font Book Font Awesome item
7. Doesn't work http://take.ms/l1t6E
8. Same in Illustrator CC
(other icons work fine)

**Comment by tagliala** [comment]
closing here, maybe this is related to #6288
