### ISSUE TITLE
Icon Request: fa-books

### ISSUE THREAD

**Issue by Jatin1212** [FortAwesome/Font-Awesome#5098]
![library](https://cloud.githubusercontent.com/assets/10024588/5244200/d9d7d7a4-7972-11e4-9fcc-6f207933c769.png)

**Comment by samuelbradshaw** [comment]
+1 
![books](https://cloud.githubusercontent.com/assets/7323052/13034410/e3285e1c-d2f1-11e5-9aab-53e55015406e.png)

**Comment by cpx-daniel** [comment]
+1

**Comment by pnacelli** [comment]
+1

**Comment by monteiroiale** [comment]
+1

**Comment by dumptyd** [comment]
+2

**Comment by shaedrich** [comment]
+1
![books](https://cloud.githubusercontent.com/assets/11225821/26488056/42ff02e8-4202-11e7-9acd-530f4361a047.png)

**Comment by lionelster** [comment]
![books-gray](https://user-images.githubusercontent.com/1300917/29855088-1125275a-8d7c-11e7-8efb-4a6712295b6e.png)
As simple as possible. +1

**Comment by shaedrich** [comment]
alias: fa-library

**Comment by maladeeb** [comment]
+1

**Comment by effipub** [comment]
Please make something very simple. All other versions are related to the cultural environment.
[linde_books.pdf](https://github.com/FortAwesome/Font-Awesome/files/2062574/linde_books.pdf)
.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/books?style=solid

**Comment by effipub** [comment]
I‘m sorry to Tell you, that this is the worst icon in the whole collection. We were waiting for this and now we have to stay with our self made work around font. 

The Icon is - unliebsame all others - by far too detailed and does not even look like books. There are good examples for simple solutions e.g. In the Firefox browser. Why didn‘t take something similar?

Best
Matthias



Von meinem iPhone gesendet

**Comment by davegandy** [comment]
> The Icon is - unliebsame all others - by far too detailed and does not even look like books. There are good examples for simple solutions e.g. In the Firefox browser. Why didn‘t take something similar?

Good feedback. We'll take a look.


> I‘m sorry to Tell you, that this is the worst icon in the whole collection.

While we take constructive criticism quite well (we quite appreciate it), this is unacceptable (and objectively incorrect. I've personally designed many that are worse). You're being blocked from the repo. Please learn how to play well with others.

**Comment by sensibleworld** [comment]
@effipub We're always open to feedback, and are happy to consider icon revisions (or to create `alt` versions of icons). But please understand that calling something "the worst icon in the whole collection" isn't the best way to get the results you're after.
