### ISSUE TITLE
Icon request: icon-rail

### ISSUE THREAD

**Issue by jewkesy** [FortAwesome/Font-Awesome#5099]
Hi everyone,

Can I request a rail-based icon please?   The purpose of this is for a project whereby icons represent different methods of travel within my application.

I'm imagining this style - http://the-eggs.co.uk/images/rail.gif - where the tracks start from the bottom and disappear into the horizon and the sleepers are distinctive

Thanks
Daryl

**Comment by busolp** [comment]
We need the same but the link is sadly not working. But I guess it looked similar to the existing road icon but with two rails going from bottom to top and horizontal sleepers.
I would suggest a more distinctive name for the icon like rail-track.

**Comment by Fonant** [comment]
Something like this would work for me:

![](https://cdn0.iconfinder.com/data/icons/city-space-1/512/railway-128.png)

Perhaps with some perspective created by tapering the icon from wide bottom to narrower top.

**Comment by Fonant** [comment]
A name of rail-track would work better, agreed.

**Comment by aethior** [comment]
Hi @jewkesy,

This icon has been added in v6.0.0.
Check https://fontawesome.com/icons/train-track

Regards.

cc/ @tagliala
