### ISSUE TITLE
Icon request: icon-quora

### ISSUE THREAD

**Issue by jrf0110** [FortAwesome/Font-Awesome#510]
Just thought I'd throw my suggestion into the pool. Can I get a +1?

[edit] fixed drunk spelling errors

**Comment by jatindhankhar** [comment]
+1

**Comment by prateeekmehta** [comment]
+1

**Comment by piperchester** [comment]
+1

**Comment by JohnKurlak** [comment]
+1

**Comment by harshavardhana** [comment]
+1

**Comment by JaredCubilla** [comment]
+1

**Comment by bhargavgolla** [comment]
+1

**Comment by RedDevil07** [comment]
+1

**Comment by ankitnandwani** [comment]
+1

**Comment by shoyer** [comment]
+1

**Comment by royels** [comment]
+1

**Comment by lamba** [comment]
+1

**Comment by purezen** [comment]
+1

**Comment by aviralg** [comment]
+∞

**Comment by abr71310** [comment]
+1... how is this request been ignored for more than two years?

**Comment by tusharmakkar08** [comment]
+1  yeah .. It is much required.

**Comment by joginder89** [comment]
+1

**Comment by leegabriel** [comment]
+1

**Comment by markcjeffrey** [comment]
+1

**Comment by jeremyhaile** [comment]
:+1:

**Comment by DanielCaspers** [comment]
+1

**Comment by gokhanakkurt** [comment]
:+1:

**Comment by tusharmakkar08** [comment]
+1

**Comment by GeorgySerga** [comment]
+1

**Comment by BoboTiG** [comment]
:+1:

**Comment by ErikBjare** [comment]
+1

**Comment by craftworkgames** [comment]
+1

**Comment by thisisfranciswu** [comment]
+1

**Comment by GeorgySerga** [comment]
As a quick solution you can use (jade code):
i.fa.fa-square
        span.quora Q

Where .quora has:
  color: #fff;
  margin: 0 0 0 -11px;
  font-size: 13px;
  position: absolute;

Of course margin and font-size are individual. The result is:
![quora.ico](https://cloud.githubusercontent.com/assets/9346874/7457716/6ae87706-f297-11e4-9659-9febdac21df7.png)

**Comment by craftworkgames** [comment]
Thanks @GeorgySerga 

If it helps, there's an SVG (vector) logo here.
http://commons.wikimedia.org/wiki/File:Quora_logo.svg

There's also a great answer on Quora about the custom designed font used in the logo.
http://www.quora.com/What-font-is-used-for-Quoras-logo

Lastly, I tried throwing the image into WhatTheFont but none of the Q's came close.
https://www.myfonts.com/WhatTheFont/

**Comment by GeorgySerga** [comment]
Thank you @craftworkgames .
Well, we can go forward and if someone do really need 100% similarity:
There is "Q" svg here: https://github.com/samcollins/css-social-buttons/blob/master/src/quora.svg .
Then you can use http://fontcustom.com/ , and add compiled files to your project.

**Comment by craftworkgames** [comment]
@GeorgySerga I'm more interested in getting this added to the official font awesome library. 
Would the Font Custom tool output what is required for Font Awesome?
I'm a programmer, but when it comes to this kind of css web stuff I'm not very experienced. Wouldn't it be possible to fork font awesome, add the icon and issue a pull request? I mean, there's at least 50 people here that want it.

**Comment by xasos** [comment]
+1 Would love to have this. This also carries over to LaTeX, where people want to use it in their CVs.

**Comment by nextroy** [comment]
+1

**Comment by tracyalison11** [comment]
+1

**Comment by saurav12** [comment]
My issue was closed, that is why <b>[+1]</b>. Also I would suggest something like this <b>(fa-quora & fa-quora-square)</b>,

![fa-quora-square](https://cloud.githubusercontent.com/assets/4298450/8447485/29e36ed8-1fd7-11e5-887b-170f1698f1bf.png)
fa-quora-square
![fa-quora](https://cloud.githubusercontent.com/assets/4298450/8447486/29e41a68-1fd7-11e5-8516-f2681820f8e3.png)
fa-quora

**Comment by julien-garrigue** [comment]
+1

**Comment by fludeb** [comment]
+1

**Comment by akhilpo** [comment]
+1

**Comment by adrian-scoica** [comment]
+1

**Comment by xasos** [comment]
Is there anything blocking this from happening? Over 2 years have passed since the request to get the Quora icon added to the library. @tagliala @davegandy

**Comment by TJohnson93** [comment]
+1

**Comment by go2shibu** [comment]
+1

**Comment by marksilvis** [comment]
+1

**Comment by lnalex** [comment]
+1, always waiting for

**Comment by anexasnivihs** [comment]
+1

**Comment by KannarKK** [comment]
+1

**Comment by ferdianap** [comment]
+1

**Comment by sergeydgr8** [comment]
+1, please add this. This issue was open three years ago.

**Comment by JDevlieghere** [comment]
+1

**Comment by JDevlieghere** [comment]
+1

**Comment by mustafawm** [comment]
+ 1

**Comment by lengerfulluse** [comment]
+1
keep waiting online.....

**Comment by jamesjohnmcguire** [comment]
+1 !!

**Comment by mandekisd** [comment]
+1

**Comment by smoens** [comment]
+1

**Comment by vaibhavgeek** [comment]
+1

**Comment by fgandiya** [comment]
+1

**Comment by mDibyo** [comment]
+1

**Comment by valizada** [comment]
+1

**Comment by edwinksl** [comment]
+1

**Comment by shashankbalaji** [comment]
+1
[There should be a way to show total number of +1's]

**Comment by anshuraj** [comment]
+1

**Comment by LyngeP** [comment]
+1

**Comment by ksashikumar** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by thevaleriemack** [comment]
+1

**Comment by noczesc** [comment]
+infinity :c

**Comment by RCMainak** [comment]
3 years and 125 comments later all I'm going to to say is +1 please...

I wonder why no one is paying attention o this request. We need a fucking Q... :(

**Comment by googlegovind** [comment]
+1

**Comment by HelgeSverre** [comment]
+1

**Comment by abaric** [comment]
+1

**Comment by karanbir88** [comment]
+1

**Comment by gomezjdaniel** [comment]
+1

**Comment by freckletonj** [comment]
+1 give us a Q!!!

**Comment by marauderlabs** [comment]
:+1:

**Comment by 4evermaat** [comment]
+1
I will reference my post #8881 and add the logo link here
![quora_q](https://cloud.githubusercontent.com/assets/830306/14222866/82c5b478-f8a0-11e5-8f7e-d89a109f0cc3.png)

**Comment by Ninja1729** [comment]
+1

**Comment by vaxo** [comment]
+1

**Comment by YangVincent** [comment]
+1

**Comment by Sayan98** [comment]
+1
Wth it's like 4 years and yet no icon for quora?

**Comment by bonyboy** [comment]
+1

**Comment by kincaider** [comment]
+1

**Comment by sudoankit** [comment]
+1

**Comment by tiggerypum** [comment]
+1
seems this is being requested, any chance it will happen?

**Comment by djm-rs** [comment]
+1

**Comment by DollarAkshay** [comment]
+1

**Comment by arjitsrivastava** [comment]
+1

**Comment by prajaybasu** [comment]
+1

**Comment by vrudikov** [comment]
+1

**Comment by bntzio** [comment]
+1

**Comment by theantonioalmeida** [comment]
+1

**Comment by vaghawan** [comment]
+1 Need this badly awesome!!!

**Comment by piyushkhemka** [comment]
+1

**Comment by sourabhdattawad** [comment]
+1

**Comment by jordancclive** [comment]
+1

**Comment by amazingBastard** [comment]
+1

**Comment by LeNPaul** [comment]
+1

**Comment by YannicBonenberger** [comment]
+1

**Comment by shantanoo-desai** [comment]
:+1:

**Comment by hoang-tran** [comment]
+1

**Comment by crowezie** [comment]
+1

**Comment by clarmso** [comment]
+1

**Comment by huy-nguyen** [comment]
+1

**Comment by Joshi-Harsh** [comment]
+1

**Comment by dvro** [comment]
+1

**Comment by MulleOne** [comment]
+1

**Comment by yogeshchellappa** [comment]
+1

**Comment by Spatika** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch. Closing.

**Comment by fhoces** [comment]
+1

**Comment by tagliala** [comment]
@fhoces http://fontawesome.io/icon/quora/
