### ISSUE TITLE
icon center aligning in container not pixel perfect

### ISSUE THREAD

**Issue by attenzione** [FortAwesome/Font-Awesome#5100]
Tested in
Browser: Chrome
OS: MacOS Yosemite and Windows 8

I understand problem of aligning icons in pixel grid, but i want to know if there is any solution or workaround to avoid it
http://jsfiddle.net/attenzione/1wpt4pdg/

this is my result
![screen shot 2014-12-01 at 12 59 03](https://cloud.githubusercontent.com/assets/284987/5244631/f39b15d4-7959-11e4-88d4-60116e616308.png)

**Comment by tagliala** [comment]
Closing here because the solution depends on use case and the above still applies
