### ISSUE TITLE
icon request: ATM / Deposit / Withdrawal

### ISSUE THREAD

**Issue by igormelnick** [FortAwesome/Font-Awesome#5103]
Would really love to see the icons for ATM/Deposit/withdrawal
https://www.iconfinder.com/search/?q=withdrawal (these look more like ATMs :) )
https://www.iconfinder.com/search/?q=atm (and these look both like ATMs ans withdrawal icons)

Thanks,
Igor

**Comment by haferje** [comment]
+1

**Comment by TonGarcia** [comment]
+1

**Comment by themnd** [comment]
+1

**Comment by Manuel83** [comment]
+1

**Comment by csindhu** [comment]
+1

**Comment by SouLWings** [comment]
+1

**Comment by KZeni** [comment]
+1

**Comment by tbolt256** [comment]
+1

**Comment by christinammiyar** [comment]
+1

**Comment by joaonzangoII** [comment]
+1

**Comment by trustmub** [comment]
+1

**Comment by unlavab** [comment]
+1

**Comment by Aries0d0f** [comment]
+1

**Comment by nshahpazov** [comment]
+1

**Comment by fegorodscy** [comment]
+1

**Comment by ronnie-isurina** [comment]
+1

**Comment by Mitka20** [comment]
+1

**Comment by marcoiai** [comment]
+1

**Comment by ajoneschick** [comment]
+1

**Comment by saidsoualhi** [comment]
+1

**Comment by DaveSenn** [comment]
+1

**Comment by m1k3p** [comment]
+1

**Comment by josevite** [comment]
+1

**Comment by Mayzz03** [comment]
+1

**Comment by sensibleworld** [comment]
<img width="716" alt="Screen Shot 2021-03-30 at 12 18 13 PM" src="https://user-images.githubusercontent.com/529604/113021861-014b7400-9152-11eb-9d99-5fb7856afa68.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download

**Comment by igormelnick** [comment]
Yeah!

**Comment by christinammiyar** [comment]
> Yeah!

I waited years for this and tbh I'm not disappointed lol

**Comment by sensibleworld** [comment]
@christinammiyar The best things come to those who wait 😆 (And sorry for the massive delay! Hoping to pick up the pace on new icons added.)
