### ISSUE TITLE
Icon request: icon-product-hunt

### ISSUE THREAD

**Issue by dominikgrolimund** [FortAwesome/Font-Awesome#5108]
![screen shot 2014-12-02 at 11 27 57](https://cloud.githubusercontent.com/assets/762371/5261113/4fdc7a74-7a16-11e4-8406-1eaa56d8e0dd.png)

**Comment by contraultra** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.
