### ISSUE TITLE
Icon request: Multiple chef-hat icons

### ISSUE THREAD

**Issue by saurav12** [FortAwesome/Font-Awesome#5113]
I want the chef's hat or cap to be used on my website to show there ratings same as we do with the stars, etc. Such as for 5 star using 5 stars, Similarly for chef's rating the chef's hat would be displayed.
![chef_icon_request](https://cloud.githubusercontent.com/assets/4298450/5449931/e13042f4-8523-11e4-89e9-30eb9cb63cd4.png)

I hope you understand what I meant to say... Thanks!

**Comment by TayloredKris** [comment]
+1

**Comment by shurub3l** [comment]
+1

**Comment by raulillana** [comment]
+1

**Comment by glossyweb** [comment]
+

**Comment by glossyweb** [comment]
+1

**Comment by digitaloutback** [comment]
+1

**Comment by lucacerretani** [comment]
+1

**Comment by madivad** [comment]
Why is there no +1 like for this issue/request? (read, I'm a +1 also)

**Comment by sensibleworld** [comment]
Hey folks! Closing this issue, as we have already have a [chef's hat icon](https://github.com/FortAwesome/Font-Awesome/issues/2598) in the works. Once that's released, you can accomplish the above by using our SVG/JS implementation and our alternate styles: https://codepen.io/fontawesome/pen/WWjKoz
