### ISSUE TITLE
Icon Request: no internet signal

### ISSUE THREAD

**Issue by slzrafael** [FortAwesome/Font-Awesome#5114]
Like this:

http://www.clker.com/cliparts/F/j/3/t/Z/8/disconnect-hi.png

**Comment by mafrazz** [comment]
+1 You can't stack icons in fonts.

**Comment by Xatenev** [comment]
@mafrazz Did you even read the link @oxguy3 suggested? It explains how to stack icons.

**Comment by mafrazz** [comment]
When using the vectors as individual icons like the link explain, yes, you can stack whatever you want. But when using as a font in texts (outside a browser), you don't have this freedom.

**Comment by herbert-van-Vliet** [comment]
The link no longer explains how to stack icons.
https://fontawesome.com/docs/web/style/stack does (for now).

Stacking does work but a question mark with a circle does exist - shouldn't that be stacked too, to be consistent?

**Comment by sensibleworld** [comment]
We have this icon now, if it helps: https://fontawesome.com/icons/wifi-exclamation?s=solid&f=classic and https://fontawesome.com/icons/wifi-slash?s=solid&f=classic
