### ISSUE TITLE
Icon request: icon-floppy-with-pencil (icon-save-as)

### ISSUE THREAD

**Issue by bensjones** [FortAwesome/Font-Awesome#512]
I would like to request a save as icon which looks like the save icon, but also has a pencil on it. This google search shows a couple of examples - [Google Search Save As Icon](https://www.google.com/search?q=save+as+icon&hl=en&rlz=1C1LENP_enUS492US492&prmd=imvns&source=lnms&tbm=isch&sa=X&ei=v0p8UOLJEMHc2QXVv4DQCA&ved=0CAsQ_AUoAQ&biw=1920&bih=1019#q=save+as+icon&hl=en&rlz=1C1LENP_enUS492US492&tbs=isz:i,ic:specific,isc:gray&tbm=isch&prmd=imvns&source=lnt&sa=X&ei=00p8UN-LKvTAyQGG5IDoAw&ved=0CDUQpwU&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.&fp=d25851f9385d5164&bpcl=35277026&biw=1920&bih=1019).

PS - This is an awesome project. Thank you so much for doing what you do!

**Comment by melodi24** [comment]
+1

**Comment by fszeliga** [comment]
+1

**Comment by ozgursahin** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by gcbeltramini** [comment]
+1

**Comment by RenatoMattos** [comment]
I've attached an option for "save" and "save as" using SVG format, I hope this will help!

[Archive.zip](https://github.com/FortAwesome/Font-Awesome/files/150658/Archive.zip)

**Comment by paolofulgoni** [comment]
+1

**Comment by lexoyo** [comment]
+1

**Comment by cmattick** [comment]
+1

**Comment by mmaraz** [comment]
+1

**Comment by skynetv** [comment]
+1

**Comment by xileras** [comment]
+1

**Comment by naveen4854** [comment]
+1

**Comment by robk410** [comment]
Still waiting +1

**Comment by KungPhoo** [comment]
Seriously? 8 years and no response? It's so easy to create. Disk+Pen, done.

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
