### ISSUE TITLE
 Alias Request: fa-angle-collapse-left, fa-angle-collapse-right 

### ISSUE THREAD

**Issue by mojtabakaviani** [FortAwesome/Font-Awesome#5122]
![fa-angle-collapse](https://cloud.githubusercontent.com/assets/1667525/5281293/d8316d58-7b10-11e4-9691-8e58c9b310f0.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
