### ISSUE TITLE
Alias Request: fa-caret-collapse-left, fa-caret-collapse-right 

### ISSUE THREAD

**Issue by mojtabakaviani** [FortAwesome/Font-Awesome#5124]
![fa-caret-collapse](https://cloud.githubusercontent.com/assets/1667525/5281352/831b74ac-7b11-11e4-9f8e-b7a627c211e7.png)

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Aliases have been dropped in FA5, so this issue does not apply anymore

https://fontawesome.com/how-to-use/upgrading-from-4#icon-name-changes

Closing here
