### ISSUE TITLE
Icon Request: fa-zillow

### ISSUE THREAD

**Issue by kg777** [FortAwesome/Font-Awesome#5125]
Hello,
I am a web designer working mostly for Real Estate companies.  I really love Font-Awesome and I use it for all of the icons in my designs.  However, there is one brand icon that's missing and was hoping you guys would be so kind to add.  It's the Zillow brand icon.  I have attached an image of the icon for reference.  
Thank you so much.  You guys are truly awesome.
Happy holidays!
![zillow](https://cloud.githubusercontent.com/assets/10062828/5282831/68b20458-7abe-11e4-84ef-e375ac2f434a.jpg)

**Comment by indybond1** [comment]
@tagliala Zillow is hardly a minor brand
