### ISSUE TITLE
Icon Request: New DeviantART Logo

### ISSUE THREAD

**Issue by LabLayers** [FortAwesome/Font-Awesome#5137]
![screen shot 2014-12-04 at 6 55 46 pm](https://cloud.githubusercontent.com/assets/607807/5308641/365f2664-7be7-11e4-9ae2-94659ac32008.png)

Here's a (white) SVG of their new logo icon:

http://www.da-files.com/artnetwork/new-da/boldy-facing-the-future/img-deviated_a.svg?1

**Comment by bsmjlm** [comment]
+1

**Comment by JayHoltslander** [comment]
+1 for their updated logo

**Comment by davegandy** [comment]
Updated in 4.3.0-wip branch. Closing.
