### ISSUE TITLE
Icon request: icon-webhook

### ISSUE THREAD

**Issue by jarrodbell** [FortAwesome/Font-Awesome#5139]
Icon to symbolise a webhook:
![image](https://cloud.githubusercontent.com/assets/746014/5310500/57001634-7c88-11e4-9f18-6eaea5b76ad7.png)

https://github.com/logo/webhooks/blob/master/images/logo-black.svg

**Comment by simonmorley** [comment]
:+1:

**Comment by nobitagit** [comment]
+1 :+1:

**Comment by stevepeak** [comment]
:+1: Thanks!

**Comment by parterburn** [comment]
+1

**Comment by andrefrcastro** [comment]
+1

**Comment by jspri3** [comment]
:+1:

**Comment by kjdion84** [comment]
+1

**Comment by jpbernius** [comment]
:+1:

**Comment by brodock** [comment]
:+1:

**Comment by rafaelp** [comment]
+1

**Comment by danielsantiago** [comment]
👍

**Comment by heikobornholdt** [comment]
👍

**Comment by mstrouhal** [comment]
👍

**Comment by TapanBala** [comment]
:+1:

**Comment by kagansari** [comment]
+1

**Comment by toobulkeh** [comment]
👍

**Comment by davequested** [comment]
+1

**Comment by hangsucho** [comment]
:+1:

**Comment by anbykov** [comment]
+1

**Comment by mattermack** [comment]
+1

**Comment by ximik777** [comment]
+1

**Comment by franceindia** [comment]
+1

**Comment by claudioalmeiida** [comment]
+1

**Comment by rodrigoSyscop** [comment]
+1

**Comment by JonasNeves** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by ademirvida** [comment]
+1

**Comment by richardjohansson** [comment]
+1

**Comment by jasonmorehead** [comment]
+1

**Comment by instabot42** [comment]
+1 It's been over 4 years now - is there a legal reason this hasn't been added?

**Comment by reganjohnson** [comment]
Would love to see this bad boy added! Seems pretty straight forward - must be a permission issue from the mark owner.

**Comment by jengel-rackner** [comment]
+1

**Comment by jspeedz** [comment]
+1

**Comment by jicahernandez** [comment]
+1

**Comment by vitinhohnz** [comment]
+1

**Comment by caiobubb** [comment]
+1

**Comment by Henrique-Bubb** [comment]
+1

**Comment by eitorBubb** [comment]
+1

**Comment by AlersonYampi** [comment]
+1

**Comment by danielbaylis** [comment]
+1

**Comment by internalfx** [comment]
+1

**Comment by johnmorais** [comment]
+1

**Comment by selmansener** [comment]
+1

**Comment by emrekeskinmac** [comment]
+1

**Comment by agtt** [comment]
+1

**Comment by iDiegoNL** [comment]
+1

**Comment by iDiegoNL** [comment]
+1

**Comment by redeeze** [comment]
+1

**Comment by mattroche** [comment]
This is really needed.  If you can't get the one that was proposed, maybe time to make one up.  FontAwesome is weak around underlying tech (API, SFTP, WebHooks, ...) relative to "brands".

**Comment by bastiaansenglenn** [comment]
+1

**Comment by mattroche** [comment]
You guys should really respond when there is a popular request that you can't or won't do.  It just seems dismissive that this has been out there for 4 years and is just waving in the breeze.

+1

**Comment by mattroche** [comment]
52 comments so far...

**Comment by yaalaa** [comment]
+1 * 2019

**Comment by stonjohnsson** [comment]
+1 - I need this! :-)

**Comment by jdelaune** [comment]
+1

**Comment by nothingrandom** [comment]
Yes please!

**Comment by Los302** [comment]
This would be great! Thanks.

**Comment by claudioalmeiida** [comment]
+1

**Comment by lobovkin** [comment]
You can add webhook icon manually:

`const faWebhook = {
  prefix: 'fac',
  iconName: 'webhook',
  icon: [130, 121, [], 'e001', 'M60.467 50.345C55.1 59.367 49.958 68.104 44.709 76.775C43.361 79.001 42.694 80.814 43.771 83.644C46.744 91.461 42.55 99.068 34.667 101.133C27.233 103.081 19.99 98.195 18.515 90.236C17.208 83.191 22.675 76.285 30.442 75.184C31.093 75.091 31.757 75.08 32.851 74.998C36.657 68.616 40.556 62.079 44.666 55.186C37.235 47.797 32.812 39.159 33.791 28.456C34.483 20.89 37.458 14.352 42.896 8.99301C53.311 -1.26899 69.2 -2.93099 81.463 4.94601C93.241 12.512 98.635 27.25 94.037 39.864C90.57 38.924 87.079 37.976 83.241 36.935C84.685 29.922 83.617 23.624 78.887 18.229C75.762 14.667 71.752 12.8 67.192 12.112C58.051 10.731 49.076 16.604 46.413 25.576C43.39 35.759 47.965 44.077 60.467 50.345Z M75.794 39.676C79.575 46.346 83.414 53.117 87.219 59.826C106.451 53.876 120.951 64.522 126.153 75.92C132.436 89.688 128.141 105.995 115.801 114.489C103.135 123.209 87.117 121.719 75.895 110.518C78.755 108.124 81.629 105.719 84.7 103.15C95.784 110.329 105.478 109.991 112.675 101.49C118.812 94.238 118.679 83.425 112.364 76.325C105.076 68.132 95.314 67.882 83.514 75.747C78.619 67.063 73.639 58.448 68.899 49.701C67.301 46.753 65.536 45.043 61.934 44.419C55.918 43.376 52.034 38.21 51.801 32.422C51.572 26.698 54.944 21.524 60.215 19.508C65.436 17.511 71.563 19.123 75.075 23.562C77.945 27.189 78.857 31.271 77.347 35.744C76.927 36.991 76.383 38.198 75.794 39.676Z M84.831 94.204C77.226 94.204 69.593 94.204 61.679 94.204C59.46 103.331 54.667 110.7 46.408 115.386C39.988 119.028 33.068 120.263 25.703 119.074C12.143 116.887 1.055 104.68 0.0790008 90.934C-1.026 75.363 9.677 61.522 23.943 58.413C24.928 61.99 25.923 65.601 26.908 69.169C13.819 75.847 9.289 84.261 12.952 94.782C16.177 104.041 25.337 109.116 35.283 107.153C45.44 105.149 50.561 96.708 49.936 83.161C59.565 83.161 69.202 83.061 78.832 83.21C82.592 83.269 85.495 82.879 88.328 79.564C92.992 74.109 101.576 74.601 106.599 79.753C111.732 85.018 111.486 93.49 106.054 98.533C100.813 103.399 92.533 103.139 87.63 97.896C86.622 96.815 85.828 95.532 84.831 94.204Z']
}

FontAwesome.library.add(faWebhook);

Usage: <span class="fac fa-webhook"></span>`

**Comment by ryanlynch717** [comment]
+1

**Comment by szynszyliszys** [comment]
+1 🙏

**Comment by bartes** [comment]
+1

**Comment by deejax** [comment]
+1

**Comment by mmirold** [comment]
This is not a brand icon. Maybe this mislabeling is the reason why you seem not to prioritize this icon higher. See https://en.wikipedia.org/wiki/Webhook for a description what this is about. Nowadays, almost every SaaS application needs to provide or handle webhooks, so you should reconsider the importance of this issue.

**Comment by lobovkin** [comment]
> This is not a brand icon. Maybe this mislabeling is the reason why you seem not to prioritize this icon higher. See https://en.wikipedia.org/wiki/Webhook for a description what this is about. Nowadays, almost every SaaS application needs to provide or handle webhooks, so you should reconsider the importance of this issue.

You can easily add this icon by yourself, just add few lines to your code: https://github.com/FortAwesome/Font-Awesome/issues/5139#issuecomment-629844984

**Comment by robclancy** [comment]
> You guys should really respond when there is a popular request that you can't or won't do. It just seems dismissive that this has been out there for 4 years and is just waving in the breeze.
> 
> This is a software development icon, btw.
> +1

LOL they added the dragon icon I suggested as a joke and don't have a webhook icon? An icon basically every single SaaS uses? Wonder if they have a wallet icon yet, the previous one that was confusing seems to be missing.

**Comment by fdevans** [comment]
+1 Could definitely use a Webhook icon built in

**Comment by tomm24** [comment]
+1

**Comment by spagu** [comment]
+1

**Comment by samuelbaute** [comment]
👍

**Comment by gerardpeters** [comment]
+1

**Comment by Karadox** [comment]
+1

**Comment by uuouter** [comment]
+1

**Comment by handotdev** [comment]
+1

**Comment by TerryDieckmann** [comment]
+1

**Comment by yarinsa** [comment]
+1

**Comment by shaktiDDM** [comment]
+1

**Comment by giveabl-st** [comment]
+1

**Comment by th-m** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in 6.3 Pro: https://fontawesome.com/icons/webhook?s=solid&f=classic
