### ISSUE TITLE
Icon Request: fa-cctv (surveillance camera)

### ISSUE THREAD

**Issue by greguarr** [FortAwesome/Font-Awesome#5140]
It will be nice to see this icon in F-A :-)
I'm working on a project for a ski area. I'm using Font-Awesome. All icons are from FA, but this one is missing and now i have to use png for this one.

![camera-cctv](https://cloud.githubusercontent.com/assets/15262/5312622/95e90f5c-7c5d-11e4-8276-fd9679731fe8.png)

**Comment by bertoost** [comment]
+1

**Comment by gigantech** [comment]
+1

**Comment by alxhotel** [comment]
+1

**Comment by GiveMeGimmicks** [comment]
+1

**Comment by Scrunshes** [comment]
+1

**Comment by kjensenxz** [comment]
+1

**Comment by S4MD33** [comment]
+1

**Comment by imadeddine01** [comment]
+1

**Comment by goinfrabr** [comment]
+1

**Comment by ausaleh** [comment]
+1

**Comment by Braquec** [comment]
+1

**Comment by arthuralmanzor** [comment]
+1

**Comment by nemo0905** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by AbdulRehman3** [comment]
+1

**Comment by weijyewang** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cctv?style=solid

**Comment by AbdulRehman3** [comment]
Sorry Its not so awesome. 
I suggest the following design as suggested by @greguarr 

> ![camera-cctv](https://cloud.githubusercontent.com/assets/15262/5312622/95e90f5c-7c5d-11e4-8276-fd9679731fe8.png)

**Comment by sensibleworld** [comment]
@AbdulRehman3 That design doesn't fit with styling of our other icons, nor could we use it, as it looks to be auto-traced from another icon set.
