### ISSUE TITLE
Icon Request: fa-mosque

### ISSUE THREAD

**Issue by humblehumanbeing** [FortAwesome/Font-Awesome#5146]
Mosque is the place in which Muslims pray/worship

**Comment by mewsoft** [comment]
+1
add also Church, etc.

**Comment by redayoub** [comment]
+1

**Comment by jandosul** [comment]
+1

**Comment by hakan42** [comment]
+1 :smile:

**Comment by gezzeg** [comment]
+1

**Comment by Crissov** [comment]
[🕌 U+1F54C Mosque](http://emojipedia.org/mosque/) – Unicode emoji

**Comment by AnasTHH** [comment]
+1

**Comment by ahmedfouzan** [comment]
+1

**Comment by jsilvanus** [comment]
+1 would be very nice :)

**Comment by Wingo5315** [comment]
+1
Could also add the Christian Cross, the Star of David and other religious icons.

**Comment by hasan-r0ny** [comment]
+1

This would be great, please add this.

**Comment by kls803** [comment]
+1

**Comment by brandonmcconnell** [comment]
+1 @Wingo5315 There should be a symbol icon for every major religion as well as a church icon for that religion, so there would be

- fa-christianity & fa-cross/fa-christianity-cross
- fa-judaism & fa-temple/fa-judaism-temple
- fa-islam & fa-mosque/fa-islam-mosque

Other religious symbols would be very helpful too, like fa-ichthys, fa-chi-rho, and fa-baptism for Christianity, and maybe fa-salah and fa-mecca for Islam, fa-buddha for Buddhism, and so on.

@sensibleworld

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mosque?style=solid
