### ISSUE TITLE
Icon request: icon-microscope

### ISSUE THREAD

**Issue by mistagoodwin** [FortAwesome/Font-Awesome#515]
More medical icons.  I work for a company that does medical software.  Here are some specific requests:
- microscope
- vial
- syringe
- drug bottle

**Comment by nsimeonov** [comment]
+1 for all of them 

I would prefer one or multiple pill/tablette icons instead of the bottle but if bottle can be simple enough would be great too

**Comment by DanTheColoradan** [comment]
+1

**Comment by jbteague** [comment]
+1

**Comment by mehditaly** [comment]
Hello,
I need microscope icon please 
Best regards

**Comment by mehditaly** [comment]
+1
I need one similar to this one thank you 
http://www.demo.webolabo.com/images/microscope_icon.png

**Comment by foobarable** [comment]
+1
I'd love to see one microscope icon in fa! 
Best regards

**Comment by MattMadden** [comment]
+1

**Comment by rwmpelstilzchen** [comment]
+1

[This one](https://openclipart.org/detail/192466/microscope-icon) is quite nice and is released into the public domain, so it can be used, after modification (such as monochromization + shrinking the white gap around the joint). On [CONTRIBUTING.md](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) they say they don’t accept new pull requests containing icons, so I will not make one…

**Comment by foobarable** [comment]
So, is it likely something happens here or should I just not use fa for this specific icon?

**Comment by cap1** [comment]
+1

**Comment by webolabo** [comment]
+1
I need one similar to this one thank you
http://www.demo.webolabo.com/images/microscope_icon.png

**Comment by benedikt-wegmann** [comment]
+1

**Comment by luigilabel** [comment]
+1

**Comment by mfiume** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by theosherman** [comment]
+1

**Comment by monika-aashe** [comment]
+1 for microscope

**Comment by tbeitter** [comment]
+1

**Comment by G-Driver** [comment]
+1 

<img src="https://cdn2.iconfinder.com/data/icons/science-solid-icons-vol-2/48/083-512.png">

**Comment by foobarable** [comment]
This really looks good!

**Comment by TonyValenti** [comment]
+1

**Comment by webolabo** [comment]
+1

**Comment by elquid** [comment]
+1 for microscope

**Comment by mtdinnyc** [comment]
+1 for microscope

**Comment by sargonpiraev** [comment]
+

**Comment by sergiohidalgo-duoc** [comment]
+1

**Comment by mietcls** [comment]
+1

**Comment by saffabook** [comment]
+1

**Comment by tagliala** [comment]
reopening here

**Comment by sergiohidalgo** [comment]
+1

**Comment by emilie-purr** [comment]
I need microscope too

**Comment by ranesr** [comment]
+1

**Comment by felixzuo** [comment]
+1

**Comment by pepperstreet** [comment]
+1

**Comment by maslennikov-yv** [comment]
+1

**Comment by jacob-appeagle** [comment]
+1

**Comment by aggo** [comment]
+1

**Comment by Kemelite** [comment]
Any hope on the microscope icon?

**Comment by marco86to** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by ozgunlu** [comment]
+1

**Comment by ccamel** [comment]
Looks good! I'm waiting for it too :smile:

**Comment by andreschabur** [comment]
+1

**Comment by zerochka** [comment]
+1

**Comment by dexterlib** [comment]
Would love a microscope!
+1

**Comment by maladeeb** [comment]
+1

**Comment by Fever905** [comment]
+1

**Comment by Wingo5315** [comment]
We're in progress.
