### ISSUE TITLE
Icon request: icon-page-break

### ISSUE THREAD

**Issue by agibsen** [FortAwesome/Font-Awesome#5153]
A page break icon would be nice. 

![screen shot 2014-03-28 at 6 05 32 am](https://cloud.githubusercontent.com/assets/47792/2549669/bc0738a8-b679-11e3-991e-b5be646f6a89.png)

**Comment by nathraQ** [comment]
+1

**Comment by jbajou** [comment]
+1

**Comment by marvc1** [comment]
+1

**Comment by agibsen** [comment]
What's the status on this?

**Comment by Identity-labs** [comment]
+1

**Comment by cabda** [comment]
+1

**Comment by TerdyTheTerd** [comment]
+1

**Comment by epistemery** [comment]
+1

**Comment by Gnapstar** [comment]
+1

**Comment by Tabgyn** [comment]
+1

**Comment by seandelaney** [comment]
+1

**Comment by uwaeae** [comment]
+1

**Comment by Abhisheksharma01** [comment]
+1

**Comment by PimentelM** [comment]
+1 ( Please! )

**Comment by alucidwolf** [comment]
+1

**Comment by sabisg** [comment]
+1

**Comment by mentor2k1** [comment]
+1

**Comment by xjunior** [comment]
Is this ever happening?

**Comment by tagliala** [comment]
@xjunior the [in progress](https://github.com/FortAwesome/Font-Awesome/labels/in%20progress) label says yes, it will 😉 

Anyway, our [icon leaderboard](https://fontawesome.com/community/leaderboard/new#faqs) contains a lot of information on how requests work

**Comment by sensibleworld** [comment]
We've just added the `page-break` icon to Font Awesome Pro: https://fontawesome.com/icons/page-break?style=solid
