### ISSUE TITLE
Form icons inconsistency

### ISSUE THREAD

**Issue by designermonkey** [FortAwesome/Font-Awesome#5156]
- [ ] `fa-square-o` and `fa-circle-o` and their `check` equivalents should really have the same border thickness.
- [ ] `fa-square-o` not be the same size as `fa-square` as they can be used to create a checkbox. (#6238)
- [ ] `fa-check-square-o` does not meet `fa-square-o` design (#3595)

It's very odd to provide icons to do the same thing and vary the thickness.
## 

edit by @tagliala
Demo fiddle: http://jsfiddle.net/tagliala/77re29ct/295/

**Comment by talinwind** [comment]
+1 
same problem with fa-caret-square-o-down/up/left/right and fa-square-o
will be useful to notice that child have no children without break the alignment

fork fiddle to add examples: http://jsfiddle.net/wdf6gw7j/2/

**Comment by tagliala** [comment]
@talinwind please open a new request, thanks!

**Comment by jahudka** [comment]
Not only the border thickness is different, the icons are also different in overall size. If I want to replace a native checkbox with fa-square-o and when checked with either fa-check-square or fa-check-square-o, the surrounding content will shift a pixel here or there because the icons are inconsistent in size.

**Comment by gpresland** [comment]
For anyone stuck on this, my method of solving the alignment was the following:

**HTML**:
```html
<span class="wrapper">
  <span class="fa fa-fw fa-square-o checkbox-o"></span>
</span>
```

**CSS**:
```css
.wrapper {
  display: inline-block;
  width: 1.5rem;
}

.wrapper .fa {
  text-align: left;
  transform: translateX(50%);
}
```

**Example**:
https://jsfiddle.net/mwmng8p2/

**Comment by tagliala** [comment]
Fixed

Solid: https://jsfiddle.net/tagliala/tgzouajm/35/
Regular: https://jsfiddle.net/tagliala/tgzouajm/36/
