### ISSUE TITLE
Icon request: icon-tree

### ISSUE THREAD

**Issue by Dolfst** [FortAwesome/Font-Awesome#5165]
Hello. Please can you paste this icon on your site for tree?

![black](https://cloud.githubusercontent.com/assets/8330263/5360077/07959ab2-7fd3-11e4-875e-055f78bd3fdc.png)

Thanks! Dima from Belarus.

**Comment by G-Driver** [comment]
+1

**Comment by crypticman** [comment]
+1

**Comment by tagliala** [comment]
http://fontawesome.io/icon/tree/

Use case for a different tree?

**Comment by sensibleworld** [comment]
We have a few tree icons now: https://fontawesome.com/icons?d=gallery&q=tree
