### ISSUE TITLE
Icon Request: fa-thin-arrow (-right, etc.)

### ISSUE THREAD

**Issue by nltesown** [FortAwesome/Font-Awesome#5166]
The four directional arrows (fa-arrow-right, etc.) are a too fat to look nice when integrated in a line of text (a possibly frequent use, IMO). An fa-thin-arrow could be thinner and with a smaller head. Your thoughts?

**Comment by satbirkira** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by PhilippeRoy** [comment]
+1

**Comment by tiffanywei** [comment]
+1

**Comment by glenwith1n** [comment]
+1 - same as tiffanywei angle with a tail - I would use this religiously

**Comment by on-d-mand** [comment]
+1

**Comment by MartinsThiago** [comment]
+1

**Comment by thisboyperforms** [comment]
+

**Comment by vzrandom** [comment]
+1

**Comment by surjithctly** [comment]
+1

**Comment by ryanweber88** [comment]
+1

**Comment by JonBaron78** [comment]
+1

**Comment by kinjalik** [comment]
+1

**Comment by dancrowe** [comment]
+1

**Comment by sensibleworld** [comment]
Version 6 has a few different weights (even in the solid style): https://fontawesome.com/v6.0/icons?d=gallery&p=1&s=solid&c=arrows
