### ISSUE TITLE
Icon Request: fa-unchecked-square

### ISSUE THREAD

**Issue by amraei** [FortAwesome/Font-Awesome#5173]
Please add an unchecked icon like what I attached to this issue. The second one is a square with a cross inside it.
![squares](https://cloud.githubusercontent.com/assets/3328211/5372590/882444a2-8060-11e4-8d07-2a73deaa1496.jpg)

**Comment by aethior** [comment]
Hi @amraei,

`fa-square`: https://fontawesome.com/icons/square
`fa-square-check`: https://fontawesome.com/icons/square-check
`fa-square-xmark`: https://fontawesome.com/icons/square-xmark

Regards.

cc/ @tagliala
