### ISSUE TITLE
Icon request: icon-blackberry 

### ISSUE THREAD

**Issue by RamanJeetSingh** [FortAwesome/Font-Awesome#5174]

**Comment by efixdent** [comment]
we need fontawesome to provide blackberry icon, thank you very much.

**Comment by daveliao** [comment]
Hey there Font Awesome bug reviewer(s), I recommend closing this issue since it's a duplicate of issue #1537 .

**Comment by tagliala** [comment]
@daveliao thanks, didn't see this one
