### ISSUE TITLE
Icon request: icon-hd, icon-sd

### ISSUE THREAD

**Issue by sorahn** [FortAwesome/Font-Awesome#518]
I'm not entirely sure how much more could be put into this other than a nicely kerned HD and SD, but It would be good for using for buttons to download different types of videos.

Thanks :)

**Comment by odera89** [comment]
+1

**Comment by ferpica** [comment]
+1

**Comment by kousha-icracked** [comment]
+1, also retina display icon would be nice

**Comment by mistertest** [comment]
Yes, surprise me in not here yet, and mores : bluray, divx etc..
It's more usefull for link video, players etc...
+1

**Comment by komlew** [comment]
+1

**Comment by riderodd** [comment]
+1

**Comment by codefocus** [comment]
+1, would love this

**Comment by Crissov** [comment]
Unicode has inherited these from ARIB Std B24:

- &#x1F14A; U+1F14A Squared HV 
- &#x1F14C; U+1F14C Squared SD

**Comment by bertofer** [comment]
+1

**Comment by crash83k** [comment]
+1

**Comment by Torchify** [comment]
+1 ...Unicode is not a crossbrowser solution.

**Comment by AoEmaster** [comment]
+1

**Comment by morgzz** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
