### ISSUE TITLE
Icon Request: fa-map-horizontal, fa-map-vertical

### ISSUE THREAD

**Issue by bdbch** [FortAwesome/Font-Awesome#5184]
Hello people!

I'm still missing a few map icons. Since there is only a map marker, we could really use some good map icons for Font Awesomes next version.

Here are examples for the classes:

**.fa-map-horizontal**
http://simpleicon.com/wp-content/uploads/map-8.png
https://cdn3.iconfinder.com/data/icons/pyconic-icons-1-2/512/location-map-512.png

**.fa-map-vertical**
https://cdn0.iconfinder.com/data/icons/elite-vehicle-navigation/512/map-location-2-512.png
http://i.imgur.com/fjBJQtf.png

Goodbye and have a nice day!

**Comment by badulesia** [comment]
+1

**Comment by dominikbiedebach** [comment]
No feedback yet?

**Comment by badulesia** [comment]
Le 14/02/2015 11:15, Dominik Biedebach a écrit :
> No feedback yet?
>
> —
Hello.

It's probably because they don't have considered the proposal as 
interesting. I'm in need for such icon myself, that's why I set +1.

Regards.

**Comment by dominikbiedebach** [comment]
Well to bad because those map icons would be really fitting into the general style of font-awesome.

**Comment by tagliala** [comment]
why 2 different icons? map horizontal is a dup of #1023

**Comment by badulesia** [comment]
Le 14/02/2015 14:02, Geremia Taglialatela a écrit :
> why 2 different icons? map horizontal is a dup of #1023
> <https://github.com/FortAwesome/Font-Awesome/issues/1023>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/5184#issuecomment-74374174>.
>
Hello.
I just need the horizontal one. Before creating a new issue, I browsed 
previous ones and find #5184, so I +1. #1023 suits me too. :)

**Comment by GMartigny** [comment]
The second .fa-map-vertical is what I was looking for. +1 then
