### ISSUE TITLE
Facebook and Twitter Square no longer same line height.

### ISSUE THREAD

**Issue by renaobrien** [FortAwesome/Font-Awesome#5191]
Font sizes are the same , however the icons themselves are no longer the same size. Causing issues with sizing. Thanks FA!!

**Comment by renaobrien** [comment]
Hey @tagliala , nope. Still different. 
![screen shot 2015-01-10 at 10 57 00 pm](https://cloud.githubusercontent.com/assets/6835087/5694302/0621bc26-991c-11e4-9d74-0d3ab11b21be.png)

**Comment by tagliala** [comment]
Could you please try at 14px or multiples?

**Comment by tagliala** [comment]
Make also sure you are using FA 4.2.0

**Comment by tagliala** [comment]
No feedback, closing here
