### ISSUE TITLE
Icon Request: fa-weight

### ISSUE THREAD

**Issue by vikkylynn** [FortAwesome/Font-Awesome#5199]
I would like icons to represent weight, weigh loss and work out such as a dumbbell, weight, measuring tape and scale. Examples attached. 

Thank you.
![weight_loss](https://cloud.githubusercontent.com/assets/10168981/5416451/7dcb51e6-81e4-11e4-9b09-6b0f15ff63b1.jpg)

**Comment by haferje** [comment]
+1
fitness icons

**Comment by tagliala** [comment]
locking here

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
