### ISSUE TITLE
Icon request: fa-sunset , fa-sunrise

### ISSUE THREAD

**Issue by kjohannessen** [FortAwesome/Font-Awesome#5200]
to be used when displaying sunset / sunrise times

**Comment by nathraQ** [comment]
+1

**Comment by jkandasa** [comment]
+1

**Comment by nihonjinrxs** [comment]
+1

**Comment by DistantParadox** [comment]
+1, for use with PaleMoon Browser

**Comment by irish** [comment]
+1

**Comment by ovisopa** [comment]
+1

**Comment by sjacq** [comment]
+1

**Comment by sensibleworld** [comment]
This is available in version 5 and 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=sun&s=solid

<img width="352" alt="Screen Shot 2021-05-27 at 2 05 29 PM" src="https://user-images.githubusercontent.com/529604/119875293-98d00780-bef4-11eb-8920-e7d0f14b40f3.png">
