### ISSUE TITLE
Graduation

### ISSUE THREAD

**Issue by on3eighteen** [FortAwesome/Font-Awesome#5206]
For some reason the fa-graduation-cap font comes out pretty rough on the diagonal lines.  I have never noticed a problem w/ any other character.  Just mentioning as an FYI...I absolutely love these fonts so I wanted to chip in w/ something I noticed in case there's a fa-bug.

**Comment by davegandy** [comment]
This is particularly tricky, as the angle isn't on a 45° angle. Adding to 5.0 milestone.

**Comment by on3eighteen** [comment]
Is there any date for milestone 5...even a rough one?  Just curious b/c I love that icon!

**Comment by sensibleworld** [comment]
Closing this as we've moved on to version 5 and now version 6
