### ISSUE TITLE
Icon request: fa-bdt

### ISSUE THREAD

**Issue by mdminhazulhaque** [FortAwesome/Font-Awesome#5211]
I am requesting `fa-bdt` which is a currency icon for Bangladeshi Taka. It can be added to `Currency Icons` category.

The icon can be used at eCommerce websites as there are many local online shops in Bangladesh. It can be placed in product description table, or in banners like the following image.

![demo](https://cloud.githubusercontent.com/assets/1847242/5427646/3a5e52d4-83d1-11e4-8813-4bce362e0743.png)

Unicode reference of the BDT symbol is `U+09F3`. The symbol can be found in unicode fonts like Droid Sans, SolaimanLipi etc. More details on BDT can be found on [Wikipedia](http://en.wikipedia.org/wiki/Bangladeshi_taka). And the SVG of BDT symbol can be found [here](http://upload.wikimedia.org/wikipedia/commons/6/62/Taka_%28Bengali_letter%29.svg)

**Comment by akehsanz** [comment]
thanks for this contribution
