### ISSUE TITLE
Icon request: icon-drillrig

### ISSUE THREAD

**Issue by peterwarman** [FortAwesome/Font-Awesome#5216]
Hi,
I would be very grateful for a drill rig icon.  We do environmental monitoring for the gas industry and a drill rig would be ideal on our website.
I had something like this in mind:
![drill rig1](https://cloud.githubusercontent.com/assets/10195469/5436042/b4aceed2-8459-11e4-8bb5-c391ccd33098.jpg)
![drill rig2](https://cloud.githubusercontent.com/assets/10195469/5436046/babdcabc-8459-11e4-8f46-a52278dc6a47.jpg)
Thanks in advance.

**Comment by xmuskrat** [comment]
+1

**Comment by tagliala** [comment]
I think that https://fontawesome.com/icons/oil-well?s=solid fits this use case

Feel free to open a new request if it doesn't
