### ISSUE TITLE
Icon Request: fa-myblog

### ISSUE THREAD

**Issue by ethnicland** [FortAwesome/Font-Awesome#5224]
Hi all of you and thank you for all your work which resaults in obviously increasing community.
I´d like to separate my blog-comunity from  all others on my site, meaning I´d like to have one icon leading to different layout than the rest of my site.
If I´m right then no icon has been made for not-branding community or social or the personal blog-section of a site?
Happy staying alive, creating exciting things!
ethnicland

**Comment by aethior** [comment]
@tagliala I think you can close here.
