### ISSUE TITLE
Icon Request: fa-videoconsole

### ISSUE THREAD

**Issue by CarlosUrda** [FortAwesome/Font-Awesome#5227]
Could you develop a videoconsole icon?

¿Podríais implementar un icono que representase una videoconsola?

**Comment by tagliala** [comment]
Hi,

I'm squashing some old issues

We have a retro gamepad now: https://fontawesome.com/icons/gamepad?style=solid

If you are still interested in a retro console, fill free to open a new request by filling out our [new request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example

Please do not ask for material copyrighted by Nintendo (ref: #12428)
