### ISSUE TITLE
Ability to disable query-string versioning

### ISSUE THREAD

**Issue by zeppelin** [FortAwesome/Font-Awesome#5231]
When using an asset fingerprinting solution like [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev):
- File types are detected by the file extension, which essentially will be something like `.svg?v=0.4.2` - something these libs won't recoginze.
- These libraries make query-string versioning unnecessary, since assets are served with an MD5 hash in the filname.

A variable like `$fa-query-string-version: true`/`@fa-query-string-version: true` would be a good addition to have for Font Awesome to be a better citizen in these (not that exotic) environments.

**Comment by chrishol** [comment]
+1 for this.

**Comment by tagliala** [comment]
Refers to #3286

**Comment by shemani** [comment]
+1

This will also stop Google Page Speed to stop complaining about query parameters (related to caching).

**Comment by tagliala** [comment]
Adding to milestone 5.0.0 and assigning to Dave, so he will eventually take a look. I would completely disable the query string and add the version in the file name, as suggested elsewhere

**Comment by tagliala** [comment]
@shemani @chrishol @zeppelin is it fine to completely remove the query string and include the version number in the fontname itself?

**Comment by chrishol** [comment]
Yes, I think that would be fine.

**Comment by shemani** [comment]
Yes query string to fetch a string is discouraged to get static resources
so that would be fine.

Thanks!!

On Tuesday, February 10, 2015, Chris Hollindale <notifications@github.com>
wrote:

> Yes, I think that would be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/5231#issuecomment-73815417>
> .
>


-- 
Salman Hemani

**Comment by mriehema** [comment]
+1

**Comment by CounsellingHub** [comment]
+1

**Comment by iwinux** [comment]
+1

**Comment by mkurz** [comment]
+1
So you are going to add the version in the file name itself. Nice.
However please also make an option to NOT include the version at all - so we have just the "plain" file name.
Thanks!

**Comment by tagliala** [comment]
No more query-string
