### ISSUE TITLE
Icon Request: fa-badge

### ISSUE THREAD

**Issue by DanielLemes** [FortAwesome/Font-Awesome#5234]
Hi! Would be great to have a badge icon, something like this one from Glyphish pack.
Very useful for: review sites, indicate premium products or members, etc.

http://www.memoriabit.com.br/wp-content/themes/origin/images/glyphish/108-badge.png

**Comment by grantneufeld** [comment]
I would call that image a “medal” rather than a “badge".

**Comment by tagliala** [comment]
icon medal is #1898... this is a little bit different.

Is there a better name for this in English? military-badge?

**Comment by grantneufeld** [comment]
Maybe “icon-medal-star”?

**Comment by Lynda333** [comment]
+1

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
