### ISSUE TITLE
Icon request: fa-walker

### ISSUE THREAD

**Issue by peterkerk** [FortAwesome/Font-Awesome#5236]
I'd love to see more medical/heathcare related symbols. The ones right now are quite limited.

**Comment by kimberley-johnston** [comment]
+1

**Comment by shaedrich** [comment]
What about something like this?
![image](https://user-images.githubusercontent.com/11225821/48665096-4bd26700-ea55-11e8-91ea-4949b5cb9f4f.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/walker?style=solid
