### ISSUE TITLE
Icon request: fa-crutches

### ISSUE THREAD

**Issue by peterkerk** [FortAwesome/Font-Awesome#5238]
I'd love to see more medical/heathcare related symbols. The ones right now are quite limited.

**Comment by phpforfree** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by ppietruszewskisprosoft** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/crutches?style=solid
https://fontawesome.com/icons/crutch?style=solid
