### ISSUE TITLE
Icon request: icon-separator

### ISSUE THREAD

**Issue by scandeiro** [FortAwesome/Font-Awesome#5247]
This icon will help my team to elaborate separators much more fast.
And I think that will help a lot of developers around the world, what have got this in project.

**Comment by sensibleworld** [comment]
<img width="777" alt="Screen Shot 2021-03-30 at 1 00 29 PM" src="https://user-images.githubusercontent.com/529604/113027299-e845c180-9157-11eb-9435-e7ca90385ebb.png">

We have a `pipe` icon that could fit this use-case in version 6

**Comment by scandeiro** [comment]
> @S4lomao attachments via email don't work, please add an example on the github repository

Hey, @tagliala and @sensibleworld, sorry for the gigantic delay in responding and thank you for having responded to this request. 

It's been a long time and I don't even remember why this was required, but, I know a lot of people needed it.

I hope that you are well and that it will remain so, for all of us, in these difficult times.

Big hug to all of you!
