### ISSUE TITLE
Icon request: icon-nursing

### ISSUE THREAD

**Issue by lauramor8** [FortAwesome/Font-Awesome#5248]
Hello! 

First of all thank you so much for all your Awesome work! 

I would like to request a new icon for nursing for the "Medical Icons", I'm working right now on a moodle project for Nursing Training and it would be really helpful to have the international symbol for nursing: a Lamp. 

https://www.dropbox.com/s/pevaf1eggrc8ysr/lampara.jpg?dl=0
http://pixgood.com/nursing-symbol-lamp.html

**Comment by tagliala** [comment]
dup of #4326, please +1 that request and post there your thoughts
