### ISSUE TITLE
Icon Request: fa-bloglovin

### ISSUE THREAD

**Issue by xifelix** [FortAwesome/Font-Awesome#5252]
Hey dear FA-Team,

first of all you did an amazing job and your project really helps a lot brining better and faster websites with awesome icons. It would be great if you could add some more company icons in the fashion business. This is like the site of https://www.bloglovin.com I would love to have their Icon in your font. 
Thanks for your help in advance. 
Best Felix

**Comment by shaneGirish** [comment]
+1
