### ISSUE TITLE
Spinning animation stops if element becomes hidden (Chrome)

### ISSUE THREAD

**Issue by denchen** [FortAwesome/Font-Awesome#5258]
The spinning animation will stop if the element or parent element becomes hidden.

Example:
http://jsfiddle.net/64ezvkvm/

I've seen this occur only on Chrome on Windows (using version 39.0.2171.95 m). On FireFox, the animation is unaffected by visibility. Also, this behavior is the same on Font Awesome 3.2.1 & 4.2.0.

**Comment by tagliala** [comment]
I'm going to close here, it was a css/browser issue and Font Awesome was not related.

At the moment I cannot make spin an element inside a ::before pseudoelement even when it is visible
