### ISSUE TITLE
Icon request: icon-poland

### ISSUE THREAD

**Issue by uNqblade** [FortAwesome/Font-Awesome#5261]
I management a popular site of haxball's league (PL-HB.NET if u want have a look)
Honestly I would get overall 17 icons but the most important is below.

![mapa](https://cloud.githubusercontent.com/assets/10248723/5512930/7b1dc536-87e4-11e4-922d-3ceeb4f8c120.png)

**Comment by tagliala** [comment]
Sorry I have to close this one because there are too many countries and those silhouettes have a lot of points which will noticeably increase the font size.

I should suggest you to consider an SVG solution

Please refer to this comment: #281 (comment) for further information
