### ISSUE TITLE
Icon Request: fa-racket

### ISSUE THREAD

**Issue by cpg** [FortAwesome/Font-Awesome#5263]
I was looking for a tennis racket icon. Something [like this racket icon](https://dl.dropboxusercontent.com/u/364883/Images/example-tennis-racket.png).

Possible variation: a thinner/taller one that would represent better badminton/squash.

The suggestion would be to make it at 45 degree, to use space better and to make it more easily recognizable.

![racket icon](https://dl.dropboxusercontent.com/u/364883/Images/example-tennis-racket.png)

**Comment by roelvanlisdonk** [comment]
I was looking for the same tennis racket icon, I would really appreciate it, if this icon was added to FontAwesome.

**Comment by seidlr** [comment]
This would be a really great icon. I was looking for exactly this icon.

**Comment by seolgongchan** [comment]
UP!

**Comment by tagliala** [comment]
I think this has been implemented a while ago in Font Awesome Pro

https://fontawesome.com/icons/racquet?style=solid
