### ISSUE TITLE
Icon request: icon-circle-half

### ISSUE THREAD

**Issue by Brog33** [FortAwesome/Font-Awesome#528]
I am in need for some simple icons: Filled circle, empty circle, half-full circle.
And also icon of a car tyre.
That would be most helpful.
Thanks.

**Comment by alsahh** [comment]
+1

**Comment by amussey** [comment]
Just a heads up for those looking for a half filled circle, check out [`fa-adjust`](http://fortawesome.github.io/Font-Awesome/icon/adjust/).  Here it is next to `fa-circle-o` and `fa-circle`:

![](https://cloud.githubusercontent.com/assets/3020738/6977940/51ceac32-d996-11e4-9c82-1bde75270abf.png)

**Comment by tagliala** [comment]
@amussey thanks!

**Comment by tagliala** [comment]
but it should be flipped...

**Comment by alsahh** [comment]
Use css ;)

**Comment by tagliala** [comment]
@alsahh just imaging possible reactions of adding `icon-circle-half` alias to `icon-adjust` :)

**Comment by bartclaeys** [comment]
+1 for a flipped version of fa-adjust

**Comment by parisiam** [comment]
+1

**Comment by primac-rabia** [comment]
+1

**Comment by primac-rabia** [comment]
+1

**Comment by jbnv** [comment]
+1 for icon-circle-half, icon-circle-one-quarter and icon-circle-three-quarters.

**Comment by miyconst** [comment]
+1

**Comment by Fiachna** [comment]
The issue with adjust in terms of using it as the half filled circle is that if it needs to display the mirrored version through css scale or rotate it breaks z-order as per the [specification](https://drafts.csswg.org/css-transforms/#transform-rendering)

**Comment by Garconis** [comment]
Similar to the half-star icon, it could be used for "half" of a circle, for ratings, pies, charts, etc. Could also be considered half-moon.

**Example image (optional)**
![768px-U+25D6 svg](https://user-images.githubusercontent.com/8608632/92008983-d1500580-ed15-11ea-9cdd-5e46129936f9.png)


Ideally there would be 4 versions of this:

1. circle-half-top
1. cirle-half-right
1. circle-half-bottom
1. circle-half-left

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download
