### ISSUE TITLE
Icon Request: fa-plus-circle-o, fa-minus-circle-o

### ISSUE THREAD

**Issue by joyzhang** [FortAwesome/Font-Awesome#5286]
![screen shot 2014-12-24 at 5 03 28 pm](https://cloud.githubusercontent.com/assets/72001/5547146/d795fc2c-8b8e-11e4-94a0-db2c208ed767.png)

**Comment by fschaeffer** [comment]
+1, would be also good to use them for stacking on other icons

**Comment by EvilBMP** [comment]
Already requested - see https://github.com/FortAwesome/Font-Awesome/issues/2417

**Comment by tagliala** [comment]
@EvilBMP thanks I missed this one

Closing here
