### ISSUE TITLE
fa-rotate icons not rendered in chrome (chromium issue #445080)

### ISSUE THREAD

**Issue by vedam** [FortAwesome/Font-Awesome#5288]
I stumbled upon it while playing with fa and trying to rotate icons.
In safari and firefox everything is working and ok.
In chrome canary [Version 41.0.2258.2 canary (64-bit)] rotated icons are not rendered.
btw those on the fa-site are not shown too.

hmm: tried to paste in a screenshot but doesn't work. Sorry.

**Comment by tagliala** [comment]
Reopening and waiting for a solution from chromium dev team. The issue was assigned

**Comment by vedam** [comment]
Seems to be solved. Working here on both of my Retina-systems:
Version 41.0.2272.2 canary (64-bit)
OSX 10.10.1
macbook pro Retina
iMac 5k Retina

**Comment by tagliala** [comment]
Thanks for the heads-up and for reporting this, I was following the issue on the chromium tracker :+1:
