### ISSUE TITLE
Icon Request: icon-request fa-christmas

### ISSUE THREAD

**Issue by LegoStormtroopr** [FortAwesome/Font-Awesome#5290]
Merry Christmas Font Awesome team!

**Comment by MVcodeartbr** [comment]
@tagliala

**Comment by tagliala** [comment]
Don't know if this is a request  for a :christmas_tree: or :santa:

**Comment by MVcodeartbr** [comment]
@tagliala maybe close and refers mine topics

**Comment by tagliala** [comment]
Santa: #8019 
Christmas tree: #8030

**Comment by codyn329** [comment]
+1
