### ISSUE TITLE
Icon Request: fa-aws, fa-s3, fa-iam, fa-ec2, etc...

### ISSUE THREAD

**Issue by sgenzer** [FortAwesome/Font-Awesome#5292]
Convert all the AWS SVG files to fa.  I'd be happy to help do this using AI if you can tell me what you need.  They're all here: http://aws.amazon.com/architecture/icons/

**Comment by LauritzT** [comment]
You could use one of these services:

**Comment by tagliala** [comment]
Sorry, I can't keep this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

>  Please do not request comprehensive sets of icons related to a very specific field.

There are some duplicates here and there, #3400 , #4209, feel free to search and +1 existing requests
