### ISSUE TITLE
Icon Request: fa-cc-jcb

### ISSUE THREAD

**Issue by pelian** [FortAwesome/Font-Awesome#5295]
Japan Credit Bureau

I think it's fair to add all six members of [EMVco] (http://www.emvco.com/):
American Express, Discover, JCB, MasterCard, UnionPay, and Visa

Currently only the following exist:
fa-cc-amex
fa-cc-discover 
fa-cc-mastercard
fa-cc-visa

Missing:
fa-cc-unionpay (missing - requested #4561 : naming should be consistent)
fa-cc-jcb (missing Thanks @KenLewis )

Color:
![jcb_cards](https://cloud.githubusercontent.com/assets/2032430/5554660/b4886ffa-8ca4-11e4-965d-c04f4ce089bb.png)

Single:
![jcb_cards_bw](https://cloud.githubusercontent.com/assets/2032430/5554678/6bfa8564-8ca6-11e4-9a07-9ae74b9bfe68.png)

**Comment by kkuchta** [comment]
+1

**Comment by nnattawat** [comment]
+1

**Comment by LauritzT** [comment]
+1

**Comment by clayzermk1** [comment]
+1

**Comment by rwyland** [comment]
+1

**Comment by davidsmejia** [comment]
+1

**Comment by KenLewis** [comment]
+1

**Comment by pelian** [comment]
@KenLewis Yeup, typo!

**Comment by clichedmoog** [comment]
+1

**Comment by no81no** [comment]
+1

**Comment by moosilauke18** [comment]
+1

**Comment by tagliala** [comment]
Added in 4.4.0

Closing here!
