### ISSUE TITLE
Icon Request: broken heart

### ISSUE THREAD

**Issue by MelOcho** [FortAwesome/Font-Awesome#5301]
Hi,
Looking for a broken heart icon to go with the fa-heart icon. 

Cheers :-)

**Comment by davidklebanoff** [comment]
This appears to be a duplicate of #751.

**Comment by tagliala** [comment]
@davidklebanoff thanks

closing here, please +1 #751 and post there examples, workarounds

**Comment by UAEpro** [comment]
@LegoStormtroopr i have transform: scaled the bolt to the end of the heart,
http://jsfiddle.net/kaowm9dq/28/
css:
`.fa-bolt {
    top:0%;
    left:2%;
    font-size:70%;
    transform: scale(0.8, 1.25);
}`

**Comment by msgoussi** [comment]
How to include it in the the flexdaasboard valueBox function  
valueBox(value = 1000,  caption = "Death Cases",  icon = "fas fa-heart-broken", color = "red")

**Comment by tagliala** [comment]
Hi @msgoussi 

> How to include it in the the flexdaasboard valueBox function

Sorry, we do not provide support for third-party software

**Comment by msgoussi** [comment]
@tagliala FYI, other icons are working fine, except this icon
