### ISSUE TITLE
Icon Request: fa-patreon

### ISSUE THREAD

**Issue by IotaSpencer** [FortAwesome/Font-Awesome#5303]
I was wondering if a Patreon icon could be made, I plan on using it as a link with the WP theme Make and wanted to be able to use it on my header, let me know if you guys can do it :)

**Comment by YlloNieR** [comment]
+1

**Comment by tagliala** [comment]
@YlloNieR please upgrade to 5.0.8: https://fontawesome.com/icons/patreon?style=brands

**Comment by tagliala** [comment]
Locking here 🔒 

This icon is available

https://fontawesome.com/icons/patreon?style=brands
