### ISSUE TITLE
Icon Request: fa-egg

### ISSUE THREAD

**Issue by Foragers** [FortAwesome/Font-Awesome#5304]
Hello,  I hope you will consider adding an egg image to Font Awesome.  I am currently revamping a website for our small farm business (http://foragersfoods.co.uk/2015-dev2/index.html) and would like to use Font Awesome icons to represent the products we will sell.  Many icons are already available in the existing menu but no eggs!  

I have drawn an egg silhouette in Adobe Illustrator (happy to send you the .ai files too).  A variation of an outline egg may also be useful (fa-egg-o).  I think that an egg icon will be of general use to the wider community in a variety of scenarios e.g. food, easter, nature, birds etc.

Many thanks,
Gary

![egg](https://cloud.githubusercontent.com/assets/10341408/5570757/987248cc-8f7e-11e4-8d2f-9e2ee7309585.jpg)
![egg-o](https://cloud.githubusercontent.com/assets/10341408/5570758/a03d2248-8f7e-11e4-84a8-b4309306dba9.jpg)

**Comment by G-Driver** [comment]
+1
Some other example for inspiration

<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/091_BoiledEgg-512.png">

**Comment by martinlindhe** [comment]
+1

**Comment by Foragers** [comment]
+1

**Comment by Foragers** [comment]
@G-Driver great work!  Does this mean that the egg cup icon is available now?  Sorry not really understanding how this all works.  does +1 mean you are expressing a "vote" for this icon to be included?

**Comment by martinlindhe** [comment]
@Foragers: +1 is a vote for this, yes. Read more here: http://fontawesome.io/community/#requesting-new-icons

**Comment by Foragers** [comment]
@martinlindhe thanks for this.  Doesn't look like we'll get more food icons any time soon :-(

**Comment by willythekid1979** [comment]
+1 for hollow egg

**Comment by mbenegas** [comment]
+1

**Comment by douglasdeodato** [comment]
+!

**Comment by leotm** [comment]
+1

**Comment by saniaja** [comment]
+1

**Comment by saniaja** [comment]
+1

**Comment by Crissov** [comment]
🥚 [U+1F95A](http://emojipedia.org/egg/) Unicode emoji #222

**Comment by s1im05** [comment]
Up +1

**Comment by mikhaildrozdov** [comment]
+1

**Comment by tzeller** [comment]
i have created an egg icon which you can straight use. no copy or so
[fa-breakfast.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364629/fa-breakfast.pdf)

**Comment by Wingo5315** [comment]
+1
Could look something like this:
![image](https://user-images.githubusercontent.com/25369857/41478424-812a2204-70bf-11e8-9987-5d356d16b4be.png)
I made it myself in Illustrator.

**Comment by sensibleworld** [comment]
Which came first? The chicken or the `fa-egg`? 
https://fontawesome.com/icons/egg?style=solid

Either way, this one is going to end up in my belly: 
https://fontawesome.com/icons/egg-fried?style=solid

**Comment by leotm** [comment]
@sensibleworld could we do poached and scrambled too? 😁
