### ISSUE TITLE
Icon Request: fa-excavator (mechanical-shovel, digger)

### ISSUE THREAD

**Issue by joshmlewis** [FortAwesome/Font-Awesome#5305]
Would eventually like a whole family of heavy equipment but this would be good for now to use as a heading icon and even smaller.

These things are awkward so best view is probably from the side like this: 
http://thumbs.dreamstime.com/z/excavator-15419104.jpg
http://www.excavatorrepairparts.com/wp-content/uploads/2011/09/hydraulic_excavator_parts.jpg

**Comment by jca79** [comment]
+1

**Comment by YlloNieR** [comment]
+1

**Comment by JosiahRooney** [comment]
+1

**Comment by waveminded** [comment]
yes please +1

**Comment by maartenmg** [comment]
+1

**Comment by cyberrep** [comment]
I really need this! gosh 7 years!!! ;-)

**Comment by aethior** [comment]
@tagliala `construction (category)` and `transportation (category)` labels for this request?

**Comment by aethior** [comment]
What are the diferences between these requests? Are related or duplicate?
- https://github.com/FortAwesome/Font-Awesome/issues/4084
- https://github.com/FortAwesome/Font-Awesome/issues/5305
- https://github.com/FortAwesome/Font-Awesome/issues/9380

**Comment by tagliala** [comment]
https://en.wikipedia.org/wiki/Excavator

> Excavators are also called diggers, JCBs[[4]](https://en.wikipedia.org/wiki/Excavator#cite_note-4) (a proprietary name, in an example of a [generic trademark](https://en.wikipedia.org/wiki/Generic_trademark)), mechanical shovels, or 360-degree excavators (sometimes abbreviated simply to "360"). Tracked excavators are sometimes called "trackhoes" by analogy to the [backhoe](https://en.wikipedia.org/wiki/Backhoe).[[5]](https://en.wikipedia.org/wiki/Excavator#cite_note-5) In the [UK](https://en.wikipedia.org/wiki/UK) and Ireland, wheeled excavators are sometimes known as "rubber ducks".[[6]](https://en.wikipedia.org/wiki/Excavator#cite_note-6)

So Excavator = digger = mechanical showel. Will leave the one with most upvotes open and close the other as duplicates

**Comment by cyberrep** [comment]
Any news about this icon? theres a way to import to fontawesome

**Comment by tagliala** [comment]
> Any news about this icon? 

You may be interested in taking a look at our [Requesting Icons FAQs](https://fontawesome.com/support#requesting-icons), they contain a lot of information about how requests work

> Theres a way to import to fontawesome

Via customization. There are both paid and free approaches, Pro Kits allow easy custom icon upload

Otherwise: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
Added! https://fontawesome.com/icons/excavator?f=classic&s=solid

**Comment by cyberrep** [comment]
thanks a lot!!!!
