### ISSUE TITLE
Icon Request: fa-filter-slash

### ISSUE THREAD

**Issue by spencerflagg** [FortAwesome/Font-Awesome#5309]
icon for removing the filter. (a la eye slash and bell slash)

**Comment by wertzui** [comment]
I need this one too

**Comment by tagliala** [comment]
Take a look at this project: https://github.com/nyon/fontawesome-actions

https://github.com/FortAwesome/Font-Awesome/issues/1181#issuecomment-87315812

**Comment by matheusramos** [comment]
I'd lime this one too :)

https://github.com/nyon/fontawesome-actions project is very interesting though

**Comment by SebastianMucke** [comment]
+1

Perhaps something like this...
http://icons.iconarchive.com/icons/icons8/windows-8/256/Data-Clear-Filters-icon.png

**Comment by tagliala** [comment]
Strongly related to #650

**Comment by Jamie-Vangeysel** [comment]
So is this coming or what?

**Comment by tagliala** [comment]
@Jamie-Vangeysel please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), you will find a lot of information on how requests work

Also, you can achieve this icon with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/81/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by jrdesignch** [comment]
+1

**Comment by sensibleworld** [comment]
Thanks for the request! This icon is part of version 6: https://fontawesome.com/v6.0/icons/filter-slash?s=solid

<img width="1040" alt="Screen Shot 2021-05-27 at 2 00 11 PM" src="https://user-images.githubusercontent.com/529604/119874661-daac7e00-bef3-11eb-87c5-b5bd549fe6ab.png">

**Comment by cyonder** [comment]
Could this be in the free version? At least the solid one.
