### ISSUE TITLE
fa-mobile size too small

### ISSUE THREAD

**Issue by omrie** [FortAwesome/Font-Awesome#5311]
fa-mobile and fa-mobile-phone looks too small when placed beside other icons.
While using it (a lot) I always hack a special CSS treatment. Thanks!

![image](https://cloud.githubusercontent.com/assets/7118470/5591898/b1bb7040-91a1-11e4-919f-82bef1baebab.png)

**Comment by tagliala** [comment]
duplicate of #928 .

This is intended by design but you could share your thoughts in the above thread and maybe dave will reconsider

closing here

**Comment by gorio** [comment]
use fa-tablet instead fa-mobile
