### ISSUE TITLE
Icon request: fa-integrated-circuit

### ISSUE THREAD

**Issue by kyakan** [FortAwesome/Font-Awesome#5319]
IC = Integrated Circuit

Useful for hardware representation, like this:
http://www.iconsdb.com/icons/download/black/integrated-circuit-256.png

**Comment by tagliala** [comment]
maybe a duplicate of #1840

**Comment by hightekjonathan** [comment]
+1

**Comment by stijnvanbael** [comment]
+1

**Comment by tagliala** [comment]
Let's use #5319

**Comment by tagliala** [comment]
Let's use #16820
