### ISSUE TITLE
Behance icon

### ISSUE THREAD

**Issue by dimitrisdk** [FortAwesome/Font-Awesome#5322]
Hello,

the behance icon is not working.

Can you check that please?

**Comment by tagliala** [comment]
@dimitrisdk of course I can't confirm: http://jsfiddle.net/tagliala/77re29ct/42/

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Probably you are using an old version of fontawesome

Closing here but feel free to comment
