### ISSUE TITLE
icon request: fa-pirate & fa-handshake & fa-hacker

### ISSUE THREAD

**Issue by BarisJKaraali** [FortAwesome/Font-Awesome#5323]
would you add these to FA project...
http://www.kurtz-bros.com/wp-content/uploads/handshake-icon.jpg
http://upload.wikimedia.org/wikipedia/commons/4/4a/Pirate_icon.gif
https://cdn0.iconfinder.com/data/icons/large-glossy-icons/512/Spy.png

**Comment by tagliala** [comment]
fa-handshake: #878 , please +1 that request
spy: #1759, please +1 that request
pirate: #918, please +1 that request

all dups, closing here.

Please also search before opening new request and if a duplicate is not found, open individual requests, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
