### ISSUE TITLE
Icon request: icon-active and icon-inactive

### ISSUE THREAD

**Issue by jacobp100** [FortAwesome/Font-Awesome#5324]
Two icons that represent active and inactive, without being able to be mistaken for success and error (tick and cross).

**Comment by tagliala** [comment]
sorry could you please provide examples?

**Comment by tagliala** [comment]
Take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by InnerSpark** [comment]
an active icon could be as simple as a figure running.
