### ISSUE TITLE
Icon Request: fa-lightbox

### ISSUE THREAD

**Issue by mikethedj4** [FortAwesome/Font-Awesome#5329]
![lightbox-icon](https://cloud.githubusercontent.com/assets/2473707/5603908/a99d953a-9360-11e4-92f6-fe07a2a3da1e.png)

I'm working on a web design application for touch users. I love using Font-Awesome for my apps and I noticed when it comes to html element components there's only a few to choose from and some elements like buttons, select element, textbox's, textarea's are not available. I also plan on adding moduals so users can add their twitter feed, lightbox, slider/fotorama, email, etc:

In this case I've already designed the icon for a lightbox modual (.svg & .png). Because I enjoy using Font-Awesome I thought I'd come here and request it.

**Comment by tagliala** [comment]
hmmm. Impossible to fit in 14x14 icon size. Refers to #855
