### ISSUE TITLE
Icon Request: fa-aparat

### ISSUE THREAD

**Issue by masudafsar** [FortAwesome/Font-Awesome#5331]
Aparat.com is a video sharing service like youtube for perisan.
LOGO file is here: http://www.aparat.com/logo

**Comment by masudafsar** [comment]
add this logo:
![](http://static.aparat.com/public/images/logo/aparat_logo_color_black_64.png)

**Comment by mikethedj4** [comment]
After reading a few of the icon requests on here I know Dave is not accepting pull requests containing icons.

If you need this icon, you should consider a custom build of fontawesome

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select (My personal favorite)
http://fontastic.me/

**Comment by tagliala** [comment]
duplicate of #5204, please +1 that request

closing here

@mikethedj4 thanks

**Comment by keshvarifar** [comment]
@tagliala : hi dear
You close this request and we have open request in #5204 , please done our req.
thanks

**Comment by tagliala** [comment]
@keshvarifar please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by se7en-team** [comment]
add this logo please
http://www.aparat.com/logo
fab fa-aparat

**Comment by MahdiAhazan** [comment]
add please!

**Comment by abbasEbadian** [comment]
Add please!
