### ISSUE TITLE
Icon Request: fa-select-element

### ISSUE THREAD

**Issue by mikethedj4** [FortAwesome/Font-Awesome#5332]
![select-icon](https://cloud.githubusercontent.com/assets/2473707/5603940/c46223e8-9362-11e4-9cda-529b3ae39916.png)

I'm working on a web design application for touch users. I love using Font-Awesome for my apps and I noticed when it comes to html element components there's only a few to choose from and some elements like buttons, select element, textbox's, textarea's are not available. I also plan on adding moduals so users can add their twitter feed, lightbox, slider/fotorama, email, etc:

In this case I've already designed the icon for a select element (.svg & .png). Because I enjoy using Font-Awesome I thought I'd come here and request it.

**Comment by tagliala** [comment]
Seems impossible to fit in 14x14 icon size

**Comment by mikethedj4** [comment]
![select-dropdown](https://cloud.githubusercontent.com/assets/2473707/5607380/faf19260-941e-11e4-996c-73000ba11eab.png)

I recently learned fa-stack stack so I made a smaller one here using stack :) - http://jsfiddle.net/krd2o8xo/
