### ISSUE TITLE
Icon Request: fa-store

### ISSUE THREAD

**Issue by umassthrower** [FortAwesome/Font-Awesome#5337]
Consensus on the internet seems to suggest an appropriate icon for a store is a short building with an awning like so: 
![store-front](https://cloud.githubusercontent.com/assets/308849/5606418/a9af3500-93fc-11e4-8f36-3f13ad1cd8fd.png)

**Comment by Jeppeskovsgaard** [comment]
A store icon like this would be great. That's exactly what I need as well.

**Comment by tagliala** [comment]
If I well remember, this is a duplicate

**Comment by umassthrower** [comment]
Hmm, ok.  I scanned down the top commented ones looking for a dupe of fa-store but didn't see one.  I"ll look again and see if we should +1 instead.

**Comment by umassthrower** [comment]
A search of this repo for the word "store" does not bring up an issue, there is fa-app-store and fa-google-play, but not fa-store.  Can you think of another term someone might have used besides "store"?

**Comment by tagliala** [comment]
here it is: #1958, please +1 that request and post there your example

closing here. 

Editing #1958 to add store in the title

**Comment by umassthrower** [comment]
Will do, thanks for finding it.

**Comment by redayoub** [comment]
+1

**Comment by farazfazli** [comment]
+1

**Comment by tagliala** [comment]
locking here. this is a duplicate, please check out my comment above :lock:
