### ISSUE TITLE
Icon Request: icon-douban

### ISSUE THREAD

**Issue by YuyingWu** [FortAwesome/Font-Awesome#5339]
![douban](https://cloud.githubusercontent.com/assets/7309680/5609079/908a4ada-94d1-11e4-88b7-bbf56c7a467e.png)

[Douban](http://www.douban.com) is a Chinese SNS website, which has 1 billion registered users.

This is [Douban's wiki](http://en.wikipedia.org/wiki/Douban).

I love fontAwesome, it has icons of Chinese SNS website, like icon-weibo and icon-weixin, I really want icon-douban as well, thank you ：）

I've already prepared a icon, if it's not perfect, please see [developer of douban](http://developers.douban.com/wiki/?title=resource).

**Comment by tagliala** [comment]
duplicate of #1841 , please +1 that request

closing here

**Comment by cssjidi** [comment]
+1

**Comment by lanegg** [comment]
+1

**Comment by tagliala** [comment]
locking this duplicate
