### ISSUE TITLE
Icon request: icon-day-01

### ISSUE THREAD

**Issue by GForest** [FortAwesome/Font-Awesome#5340]
I think it would be awesome if you guys had an icon for each day of the month so it goes from 1 to 31.

e.g.
![01](https://cloud.githubusercontent.com/assets/10400359/5612769/0e62fd26-94d2-11e4-8911-6a5ab3c581e3.png)
![31](https://cloud.githubusercontent.com/assets/10400359/5612770/0e65498c-94d2-11e4-99b4-02e43125d42d.png)

**Comment by tagliala** [comment]
@GForest you should consider to use plain css to get this.

There are proposals on this matter: #1140

Take also a look here: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by GForest** [comment]
@tagliala oh yes, i'm sorry, i did a quick research and i didn't found anything that's why i posted it, ty so much, someone lock this please

**Comment by tagliala** [comment]
no problem, glad to help :+1:
