### ISSUE TITLE
In example, use <link href=... rel=...>

### ISSUE THREAD

**Issue by fulldecent** [FortAwesome/Font-Awesome#5341]
On

http://fontawesome.io/get-started/

Please update 

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

To

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

Everyone else (for citation [click here]) does it the other way. For consistency and readability after copy/paste, please use the more popular way.

**Comment by tagliala** [comment]
Can't confirm that anyone else does this: http://www.bootstrapcdn.com/

I'm also pretty sure that slim and haml template engines alphabetically sort attributes by default in their output html.

By the way specs say that you should put rel before href. Is there any parsing issue with any supported browser?

**Comment by fulldecent** [comment]
The main example is http://getbootstrap.com/getting-started/ Since I always use these together, the difference is noticable.

This does not affect rendering in any case I've seen. Simply a low-profile fix for consistency.

**Comment by tagliala** [comment]
@fulldecent You are right. I checked bootstrap and was writing the same thing but I didn't press "comment" 

I'm editing the doc just now, it will be done in 4.3.0

**Comment by fulldecent** [comment]
Cool, than you and rock on

**Comment by davegandy** [comment]
This has been checked into 4.3.0-wip branch. Closing.
