### ISSUE TITLE
ASP.NET 5 font path

### ISSUE THREAD

**Issue by SergeySypalo** [FortAwesome/Font-Awesome#5342]
Hello,

I'm using Visual Studio 2015 Ultimate Preview and ASP.NET 5 Starter Web project
I've installed Font Awesome using bower by adding "font-awesome": "~4.2.0" into dependencies section in bower.json
When I've tried to use social icons in the view, it was not rendered properly. After googling and doing some research I found that issue caused by incorrect path to fonts in:
wwwroot/lib/font-awesome/font-awesome.css

Default (incorrect/not working):

src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff?v=4.2.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.2.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');

Fixed (working):

src: url('fontawesome-webfont.eot?v=4.2.0');
  src: url('fontawesome-webfont.eot?#iefix&v=4.2.0') format('embedded-opentype'), url('fontawesome-webfont.woff?v=4.2.0') format('woff'), url('fontawesome-webfont.ttf?v=4.2.0') format('truetype'), url('fontawesome-webfont.svg?v=4.2.0#fontawesomeregular') format('svg');

Best regards, Sergey

**Comment by tagliala** [comment]
don't know how to deal this with bower. Feedback is welcome

**Comment by SergeySypalo** [comment]
bower just helps to manage clied-side libraries, so it's just saves time on instllation. Without it I need to manually download FontAwesome and copy to some folder in website, so problem with path to font. Maybe make sense to use "./fontawesome-webfont.eot?v=4.2.0", which means current folder and use the same pattern for second string (src: url...) ?

**Comment by tagliala** [comment]
Probably you need to ovverride this variable: https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L4

**Comment by SergeySypalo** [comment]
Yep, it will work, thx
