### ISSUE TITLE
Requesting application icons like mysql,msssql,vmware,exchange,hyperv

### ISSUE THREAD

**Issue by suriya227** [FortAwesome/Font-Awesome#5346]
Its better if you add application icons like as MySQL , MSSQL,VMware , MS exchange ,Hyper-V  for the next release

**Comment by tagliala** [comment]
sorry can't keep this open, this issue doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please search for duplicates and +1 existing requests, then please open individual requests

I also suggest you to take a look at this technology related fontawesome extension: http://mfizz.com/oss/font-mfizz

**Comment by tagliala** [comment]
closing here
