### ISSUE TITLE
Icon request: icon-golf

### ISSUE THREAD

**Issue by Arachneworks** [FortAwesome/Font-Awesome#5348]
Hi, Is it possible to add a new icon to those used by Font Awesome: Icon Class = icon-golf.
I am currently using icon-pencil which I am hoping can be replaced by new icon-golf: see http://vredeselfcatering.co.za/vsc/?offer=golf
I include a basic graphic that signifies the golf concept.
Please advise if this is possible?
Regards, T
![icon-golf-mod](https://cloud.githubusercontent.com/assets/1038602/5628103/186d1fca-95ab-11e4-8389-d23c361541c7.png)
ony

**Comment by nikkiroylance** [comment]
+1

**Comment by berkeleybob** [comment]
+1

**Comment by nusserstudios** [comment]
+1

**Comment by roblawford** [comment]
+1

**Comment by RinghoferJS** [comment]
+1

**Comment by SteveHarlington** [comment]
+1

**Comment by Wineliva** [comment]
+1

**Comment by romanxts** [comment]
+1

**Comment by Cengiz25** [comment]
+1

**Comment by dkaplan88** [comment]
+1

**Comment by mkapnick** [comment]
+1

**Comment by stefbozic** [comment]
+1

**Comment by shashank2907** [comment]
+1

**Comment by hannesdmz** [comment]
+1

**Comment by AlphaNerd** [comment]
+1

**Comment by sensibleworld** [comment]
We have a few golf icons now. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=golf&s=solid

<img width="526" alt="Screen Shot 2021-05-27 at 2 13 07 PM" src="https://user-images.githubusercontent.com/529604/119876225-aafe7580-bef5-11eb-9dd8-fa381dc6bcbe.png">
