### ISSUE TITLE
Icon Request: fa-viadeo

### ISSUE THREAD

**Issue by poutsjr** [FortAwesome/Font-Awesome#5350]
Can you add Viadeo Logo (http://www.viadeo.com/) please
It's a business-oriented social networking service (like LinkedIn)

![viadeo-4096-black](https://cloud.githubusercontent.com/assets/2722370/5643111/6e874274-9654-11e4-899c-b61dfff1a604.png)

Thanks

**Comment by tagliala** [comment]
duplicate of #886 , please +1 that request

closing here
