### ISSUE TITLE
Icon request: icon-dict

### ISSUE THREAD

**Issue by caBBAlainB** [FortAwesome/Font-Awesome#5356]
Hi,
I'm suprised such icon hasn't been requested already for Text Editor icons.
I could be convenient to include a Spellcheck button to use Javascript SpellCheck tool for example

Such design, based on your checkmark, could be suitable:

![fa-dict](https://cloud.githubusercontent.com/assets/9322571/5661529/31d3cf4e-972d-11e4-8379-edb84d105acf.png)

**Comment by lenamtl** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1373, please +1 that request

closing here
