### ISSUE TITLE
Icon Request: fa-accomodations

### ISSUE THREAD

**Issue by pittster** [FortAwesome/Font-Awesome#5357]
Without the question mark obviously
Use case:  Motel, accomodations, hotel, sleep
![image](https://cloud.githubusercontent.com/assets/10453752/5668200/3e281874-9744-11e4-8677-ed6c7cb0e443.png)

**Comment by sveralex** [comment]
+1

**Comment by astuanax** [comment]
Please have a look at https://github.com/astuanax/rental-font
We have a bed icon: http://astuanax.github.io/rental-font/demo.html

**Comment by tagliala** [comment]
sorry, can't leave this open, this doesn't follow our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

bed will be included into FA 4.3.0

@astuanax thanks for sharing this! there are other issues related to accomodation, feel free to share your work there too
