### ISSUE TITLE
Icon Request: fa-construction

### ISSUE THREAD

**Issue by d9988** [FortAwesome/Font-Awesome#5359]
Would be nice to have an icon to use to indicate "under construction" or something similar. This will mean that something is in progress (website enhancement, project underway, etc.)

![bulldozer2](https://cloud.githubusercontent.com/assets/10455638/5671354/033b1674-973c-11e4-8811-be1ec8c37d9c.png)
![worker5](https://cloud.githubusercontent.com/assets/10455638/5671357/08f51d1c-973c-11e4-9560-2a6c2dc2c6a4.png)
![toolbox3](https://cloud.githubusercontent.com/assets/10455638/5671362/0f91c8fa-973c-11e4-8b5c-f417e8a5435e.png)
![cone](https://cloud.githubusercontent.com/assets/10455638/5671428/ab5c3a5e-973c-11e4-9dff-a2b95baa493f.jpg)
![images](https://cloud.githubusercontent.com/assets/10455638/5671430/adccec7a-973c-11e4-8265-a1342c34f150.jpg)

**Comment by studiobaroncelli** [comment]
How do I change the icon?

**Comment by d9988** [comment]
This icon doesn't exist yet, I requested it to be added.

**Comment by kwendenarmo** [comment]
+1

**Comment by tagliala** [comment]
closing here, 

sorry but this request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please open new individual requests with proper title, example and use case. Please also check for  duplicates

cone is also a dup of #4485

**Comment by myrmecia** [comment]
+1
