### ISSUE TITLE
Icon Request: fa-bird

### ISSUE THREAD

**Issue by PUSLogger** [FortAwesome/Font-Awesome#5363]
As I am working on a project where the goal is to feed birds regularly each day (to see if they come back) and using a motion sensor to detect if a bird comes by, I would love having a bird icon for my project. Similar to twitter!

![light-orange-twitter-bird-icon-hi](https://cloud.githubusercontent.com/assets/8005527/5681642/880e4054-981a-11e4-87cb-def17d796dc1.png)

**Comment by ander48** [comment]
+1

**Comment by danlewis** [comment]
+1

**Comment by barthsm** [comment]
+1

**Comment by sayitfast** [comment]
+1

**Comment by barthsm** [comment]
+1

**Comment by sergiosalfer** [comment]
+1

**Comment by aethior** [comment]
Hi @PUSLogger,

This icon has been added in v6.0.0-BETA3.
Check https://fontawesome.com/icons/bird

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here.

**Comment by barthsm** [comment]
Thank you!

 

Sue Barth

Mobile:  716-474-3657

Website:   <http://www.nsytes.com/> http://www.nSytes.com
