### ISSUE TITLE
icon request (major request of all year): football teams icon

### ISSUE THREAD

**Issue by leandroruel** [FortAwesome/Font-Awesome#5364]
would be great if you add a new category for this particular group of icons, soccer teams: like, icon-barcelona, icon-realmadrid. (will be hard, i know), but when we need of a icon like this, i need make my own.

another thing is: have several teams across the globe, so, you need separate by country too.

**Comment by tagliala** [comment]
Sorry but I can't keep this open.

This request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

You are free to open new multiple request, one for each football team you need, but I should suggest you to consider another solution
