### ISSUE TITLE
Icon Request: fa-diamond

### ISSUE THREAD

**Issue by akonsu** [FortAwesome/Font-Awesome#5368]
I am looking for a diamond shape icon. A square rotated 45 degrees.

**Comment by tagliala** [comment]
we need a better title for this shape because diamond #1248 will be part of 4.3.0

**Comment by bronielsen** [comment]
I support this request. I need it to represent a milestone event.

**Comment by HorseFly** [comment]
I also wish to request a diamond shape for a Milestone task.

**Comment by adambaker888** [comment]
+1. Milestone/diamond. Basically square rotated 45 degrees as 45 degree rotation isn't supported in old IE.

**Comment by dwyer14** [comment]
+1, for both line & fill versions. Regarding naming conflict, I would recommend **fa-rhombus**. Thanks!

**Comment by madmanblues** [comment]
+1 to include **fa-rhombus** in both versions as suggested by dwyer14. 
Thanks!

**Comment by adambaker888** [comment]
Any update on this? Only icon in web-app not using FA now.

**Comment by MikelArnaiz** [comment]
+1 fa-rhombus

**Comment by sensibleworld** [comment]
Hey there! This was added to Font Awesome Pro in version 5: https://fontawesome.com/icons/diamond?style=solid
