### ISSUE TITLE
Icon request: jQuery UI parity

### ISSUE THREAD

**Issue by heygrady** [FortAwesome/Font-Awesome#537]
http://codepen.io/heygrady/pen/ofyje

I was looking into replacing the jQuery UI icons with FontAwesome. Some of the jQuery UI icons have no place in Font Awesome, however comparing the two reveals a number of important omissions. I created the pen above to make it more obvious what the differences are. I might not have found all of the matches, but it should be close.

Some that would be useful:
- ui-icon-carat-2-n-s
- ui-icon-carat-2-e-w
- ui-icon-triangle-2-e-w
- ui-icon-newwin
- ui-icon-transferthick-e-w
- ui-icon-mail-open
- ui-icon-lightbulb
- ui-icon-bullet
- ui-icon-radio-on
- ui-icon-radio-off
- ui-icon-battery-0
- ui-icon-battery-1
- ui-icon-battery-2
- ui-icon-battery-3
- ui-icon-grip-dotted-vertical
- ui-icon-grip-dotted-horizontal
- ui-icon-grip-solid-vertical
- ui-icon-grip-solid-horizontal
- ui-icon-grip-diagonal-se

I don't know what to think about all of the icons like `ui-icon-carat-1-ne`, `ui-icon-carat-1-se`, etc. It seems like covering 8 directions is a little overkill. And the icons like `ui-icon-arrowreturnthick-1-w` seem lazy that they're simply rotated.

**Comment by TLJens** [comment]
+1 - specifically the battery icon and newwin. The grips would be great, but those are covered in another request.

**Comment by pope1ni** [comment]
In case anyone finds it useful to compare: http://codepen.io/anon/pen/YpJWyE?editors=1100

**Comment by sensibleworld** [comment]
Hey folks, in an effort to clean-up our outstanding issues, I wanted to touch base on this one. I believe with the release of version 6, most of these icons have already been added. https://fontawesome.com/v6.0/icons

Let me know if there are any I'm missing, and I can re-open this. Thanks!
