### ISSUE TITLE
Update MIME type for woff 

### ISSUE THREAD

**Issue by vishsid73** [FortAwesome/Font-Awesome#5372]
Hi,

I am getting this issue 

Resource interpreted as Font but transferred with MIME type application/x-woff: "https://netdna.bootstrapcdn.com/font-awesome/3.0.2/font/fontawesome-webfont.woff?v=3.0.2"

I am getting Content-Type →application/x-woff

Please resolve for 3.0.2 version.

**Comment by tagliala** [comment]
@vishsid73 could you please submit this to https://github.com/MaxCDN/bootstrap-cdn ? Then please link this issue. 

Leaving this open

**Comment by tagliala** [comment]
closing here
