### ISSUE TITLE
Icon Request: fa-*browser*

### ISSUE THREAD

**Issue by jaCUBE** [FortAwesome/Font-Awesome#5373]
Hi,
is there any chance for adding icons like **fa-firefox**, **fa-chrome**, **fa-opera**, **fa-safari**... ?

Something like these:
http://www.iconsdb.com/icons/preview/gray/firefox-xxl.png
http://www2.psd100.com/ppp/2013/11/0601/google-chrome-logo-icon-1106000918.png

I would like to have user agent indicator on user profile on my webpage and using FontAwesome (which I use for everything else) would by neat. :)

Thanks.

- jaCUBE

**Comment by tagliala** [comment]
duplicate of #219 , please +1 that request

closing here
