### ISSUE TITLE
Request For New icons

### ISSUE THREAD

**Issue by Gajendrasinh** [FortAwesome/Font-Awesome#5376]
Hi ... I need to use usb icon if possible then release one usb icons

**Comment by tagliala** [comment]
duplicate of #2165 , please +1 that request

closing here

**Comment by zebulon888** [comment]
How about new ICONS for:
GAB (https://gab.com)
DISSENTER (https://dissenter.com)
MINDS (https://www.minds.com/)
STEEMIT (https://steemit.com/)
BITCHUTE (https://www.bitchute.com)
DTUBE (https://d.tube/)
