### ISSUE TITLE
Icon Request: fa-genders (symbols)

### ISSUE THREAD

**Issue by Kowts** [FortAwesome/Font-Awesome#5378]
Hi, is it possible to add a new icon on Font Awesome: fa-genders (symbols).
I am currently in need(9x) of a icon that representing the two genders (masculine and feminine ) in a single icon. There's only two icon that represents gender but they are separate(fa-male and fa-female).
Please advise if this is possible?

exemple: http://i.imgur.com/2WbcJrp.png?1

Regards, Koowts

**Comment by tagliala** [comment]
refers to #1539 , don't know if I can consider this a duplicate

**Comment by Kowts** [comment]
ok... i think is the same thing. My request is a icon like in the image. To be used when asked the gender of a user.

Image: 
![s8h36av](https://cloud.githubusercontent.com/assets/10500335/5708978/2b79b8ba-9a85-11e4-980c-cd015cebea30.png)

**Comment by technofreaky** [comment]
+1

**Comment by pomke** [comment]
Gender is not binary, just sayin'
