### ISSUE TITLE
Icon Request: fa-taxes

### ISSUE THREAD

**Issue by huyvandnc** [FortAwesome/Font-Awesome#5382]
Hi,
Im need icon for Taxes but i can found it on Font-Awesome.
I think it like img attach:

![tax_percent_1-128](https://cloud.githubusercontent.com/assets/5999873/5715888/17b6ec50-9b14-11e4-9780-96e5058defbc.png)
![tax_percent_2-128](https://cloud.githubusercontent.com/assets/5999873/5715889/17b77fee-9b14-11e4-91ed-3f5194291517.png)

Can help me include it. Thank!

**Comment by technofreaky** [comment]
+1

**Comment by imarrero** [comment]
+1

**Comment by TonGarcia** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1292 , please +1 that request

closing here

**Comment by tkontogi** [comment]
I reopen the case to give an idea. I found the following which is proprietary.

Just food for thoughts...

![image](https://cloud.githubusercontent.com/assets/15005048/18547100/4b0411d8-7b4a-11e6-9a7c-87e8718c05f7.png)

Thank you

**Comment by TheBuzzer67** [comment]
Still not in??

**Comment by tagliala** [comment]
this is is as icon-percent http://fontawesome.io/icon/percent/
