### ISSUE TITLE
Icon Request: fa-trend-up fa-trend-down

### ISSUE THREAD

**Issue by kraminpouds** [FortAwesome/Font-Awesome#5384]
fa-trend-up  ![fa-trend-up](https://ssl.gstatic.com/analytics/20150112/web/arrow-trend-up-h.png)
fa-trend-down  ![fa-trend-down](https://ssl.gstatic.com/analytics/20150112/web/arrow-trend-down-h.png)

**Comment by tagliala** [comment]
duplicate of #4397 , please +1 that request

You can use fa-arrow-up, fa-arrow-down for your purpose

Closing here

**Comment by kraminpouds** [comment]
Thank you !
