### ISSUE TITLE
Icon Request: interaction icons

### ISSUE THREAD

**Issue by srkennedy** [FortAwesome/Font-Awesome#5385]
Would love to see an icon for mouse and page interactions. Here are some inspiration images:

**fa-pointer**
![arrows__cursor__move__pointer_icon___icon_search_engine](https://cloud.githubusercontent.com/assets/7066996/5727619/4e7c7b42-9b19-11e4-9863-9c45c7290661.png)

**fa-highlight**
![cursor__font__highlight__select__type_icon___icon_search_engine](https://cloud.githubusercontent.com/assets/7066996/5727557/d4dc9696-9b18-11e4-8d69-087ff3ea6c92.png)

**fa-click**
![click__cpc__target_icon___icon_search_engine](https://cloud.githubusercontent.com/assets/7066996/5727581/fd56cf60-9b18-11e4-8b8b-0440efc16799.png)

**fa-touch**
![adsence__advertising__business__click__cursor__finger__finger_touch__gesture__gestureworks__hand__internet_advertising__make_money__monetization__money__pay_per_click__pay-per-click__point__ppc__select__seo__tap__touch__touchscreen_icon___i](https://cloud.githubusercontent.com/assets/7066996/5727591/1193e666-9b19-11e4-9500-f2b5a60b4d4a.png)

**Comment by tagliala** [comment]
sorry, can't leave this open, please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

pointer is a dup of #1095 

please open individual requests with proper titles for other icons

closing here
