### ISSUE TITLE
Case change on package name

### ISSUE THREAD

**Issue by kenkopelson** [FortAwesome/Font-Awesome#5390]
Hello,

I'm having an ongoing problem with version 4.2.x because you changed the case of the package name.  This may not be a problem on Linux, but it causes untold grief on Mac OSX because OSX is case-insensitive/case-preserving, as it has always been since the first version.  Now, whenever Bower or NPM pulls down new versions of Font-Awesome (or font-awesome) whichever one gets downloaded last ends up overwriting the other one (so you can't have both 3.1.x and 4.2.x in the same directory).  Since these are major point releases, they are obviously not compatible, so it randomly breaks builds.

Whoever thought to rename the package using capital letters not only violated the standard way of naming javascript packages (all lower letters plus dashes), but there was an unintentional problem caused on all Mac (and Windows) machines.  I'm not sure how to fix this, short of you going back to using just small-case letters (as every other package does).  Could you please do something, since I really like using your library, and would really regret having to abandon it because of something like this.  I can't even download other packages that rely on Font-Awesome, since Bower encounters invalid characters in the 4.1.0 bower.json script (which you fixed in 4.2.0), but once it hits the invalid file, it just bombs out, not completing the download.

Please do something about this :)  I can't believe I'm the only one experiencing this pain.

Cheers,
Ken

**Comment by tagliala** [comment]
@kenkopelson could you please point out the offending source code ?

**Comment by TimothyGu** [comment]
I don't think we can do anything about this. He was complaining about the **change** and not the current status.

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
