### ISSUE TITLE
Icon request: fa-door OR fa-room

### ISSUE THREAD

**Issue by sweisgerber** [FortAwesome/Font-Awesome#5394]
I think an icon representing a door or a room would be very helpful for everyone trying to represent an address with the help of your pictographs.
The door pictograph could be used to represent a room (number).

I have no problem finding icons for street, building, mail, phone, etc, but an icon for a room number is missing.

i would propose using an open door icon.

Something like:

![Doors examples](http://us.123rf.com/450wm/skarintut/skarintut1401/skarintut140100045/25143102-vector-black-door-icons-set-on-white-background.jpg)
Copyright Watermark is in the example image. (123rf.com)

would do the trick.

**Comment by xcode12** [comment]
i'm looking for this icon too. :+1:

**Comment by elwadi** [comment]
me too

**Comment by Vioner** [comment]
+1 please add this. It's good for neighbour hood forums f.e. an icon next to the number of entrance to the block building.

**Comment by LucasSubli** [comment]
+1

**Comment by tmo256** [comment]
+1

**Comment by mattaze** [comment]
+1, surprised not added in already.

**Comment by tagliala** [comment]
Duplicate of #2921, please +1 that request

closing here
