### ISSUE TITLE
Icon request: fa-chevron-thin-*

### ISSUE THREAD

**Issue by 24creative** [FortAwesome/Font-Awesome#5397]
Hi there,

I'd like to request thinner chevrons. The current chevrons are quite thick, would be nice if there is a second chevron design (for all directions) that is thinner than the current. Perhaps with rounded "endings" instead of the current square ones.

I'm sure more people would love this? Hoping this will be implemented, thanks!

**Comment by Alex360hd** [comment]
+1 for font awesome 5 pro. Lots of webdesign like to use very thin chevron and it's quite annoying to use images instead of font each time.
