### ISSUE TITLE
Icon request - fa-cooking-knife, fa-swiss-knife, fa-folding-knife, fa-razor

### ISSUE THREAD

**Issue by gagna** [FortAwesome/Font-Awesome#5398]
Hi all, I work at a cutlery and it would be great if you create some knife icon, something like this:

Cooking
![cooking knife icon](https://cdn1.iconfinder.com/data/icons/dining-and-food/32/food-knife-512.png)

Swiss
![swiss knife](https://cdn3.iconfinder.com/data/icons/outdoor-and-camping-icons/512/Army_Knife-512.png)

Folding
![folding knife](http://www.couteaux-berthier.com/boutique_us/images_produits/pmconsigliZXB19.jpg)

Razor
![razor](http://cdn.flaticon.com/png/256/40648.png)

**Comment by ryanhar** [comment]
Where would you use this?

**Comment by kentros** [comment]
+1 to fa-swiss-knife -- where wouldn't you use it?

**Comment by gagna** [comment]
You can use it to represent a set of tools

**Comment by ryanhar** [comment]
I don't see them being very handy, but fa-swiss-knife could be of use

**Comment by tagliala** [comment]
As per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

please open individual requests

Closing here
