### ISSUE TITLE
Display icons on print outs?

### ISSUE THREAD

**Issue by dbsqn** [FortAwesome/Font-Awesome#5399]
How do I get Font Awesome icons to appear on a print out? I'm developing an internal QC system which requires reports to be printed out however only some icons appear whilst the most important icons don't appear, any idea why?

Many thanks in advance.

**Comment by dbsqn** [comment]
Can anyone help?

**Comment by tagliala** [comment]
Sorry, can't understand this issue

**Comment by dbsqn** [comment]
![image3](https://cloud.githubusercontent.com/assets/10546118/5798738/514d931c-9fc2-11e4-9344-dab70f3d5e16.jpg)
Here's an image of the issue, the left is the web page and the right is the print out

**Comment by dbsqn** [comment]
Can no one help?

**Comment by tagliala** [comment]
I cannot confirm that there are issues printing icons.

Please provide us as many information as you can.

A working demo would be great

https://github.com/FortAwesome/Font-Awesome/issues/3228#issuecomment-54297260

**Comment by dbsqn** [comment]
I solved the issue, found I had a different font with !important tagged in my print.css - crisis adverted!

**Comment by tagliala** [comment]
:+1:
