### ISSUE TITLE
 Icon request: fa-motor-cycle

### ISSUE THREAD

**Issue by filipecoelho** [FortAwesome/Font-Awesome#5402]
Dear, I would like to request the inclusion of a new motorcycle courier icon because I will need to use in a project.

![icon3a](https://cloud.githubusercontent.com/assets/1401898/5761602/9ba1205c-9cc3-11e4-80ce-b37d3f6048c3.png)

**Comment by tagliala** [comment]
duplicate #1953, please +1 that request

closing here
