### ISSUE TITLE
Icon request: fa-circle-thin-check

### ISSUE THREAD

**Issue by bobber205** [FortAwesome/Font-Awesome#5405]
The thicker circle has a couple options for checked versions.
When using the thin circle icon, there's no corresponding "checked" version, making it awkward to do a circle checkbox. Is this hard to add? :)

**Comment by homerjam** [comment]
:+1: 

Love font awesome but it'd be great to have `-thin` alternatives of a few icons...

**Comment by sensibleworld** [comment]
We have a whole Thin style now! https://fontawesome.com/search?o=r&s=thin
