### ISSUE TITLE
fa-plus-square-o does not display horizontal line of +-sign on font size 10px

### ISSUE THREAD

**Issue by wertzui** [FortAwesome/Font-Awesome#5408]
When using the icon fa-plus-square-o somewhere in combinition with font-size: 10px, the horizontal line of the +-sign disappears.
The icons fa-plus and fa-plus-square are fine.

**Comment by tagliala** [comment]
@wertzui unfortunately pixel perfection is not guaranteed at non-standard icon size

Sorry but I have to close this one
