### ISSUE TITLE
How to stack icon of the same (almost same) size ?

### ISSUE THREAD

**Issue by Nuzzler** [FortAwesome/Font-Awesome#5410]
hi ! 

I'd like to stack icon of the smallest size : the circle-thin with the <-> cross to symbolise the diameter.

How can i do ?

**Comment by moxtosm** [comment]
You can try stacking elements using position relative on parent and position absolute for the icons you want to stack.

**Comment by tagliala** [comment]
Sorry I didn't get the other icon you want to stack

**Comment by tagliala** [comment]
fa-circle-thin + ?

**Comment by Nuzzler** [comment]
Yea its this one. My question is just to know if we can stack iANY con of the same size

**Comment by tagliala** [comment]
http://jsfiddle.net/77re29ct/69/

hope it helps

closing here
