### ISSUE TITLE
Font awesome

### ISSUE THREAD

**Issue by webkayn** [FortAwesome/Font-Awesome#5416]
Hello,
I want to use the icons in a ebay auction template. So there is not htaccess file allowed or something else. Because of this it doesn´t work in firefox. I´ve search but nothing found. Can someone help me? 

regards,
webkayn

**Comment by tagliala** [comment]
Sorry but I don't know how ebay auction templates work.

Fontawesome requires a css to be loaded and CORS enabled.

If you can load css in those templates you should be fine, otherwise please consider using stackoverflow because this is a support request.

Closing here but feel free to comment
