### ISSUE TITLE
Icon Request: Frameworks

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5418]
Icons for most popular frameworks. This can be used with "Powered by"

+ fa-laravel
+ fa-symfony
+ fa-silex
+ fa-slim
+ fa-phalcon
+ fa-codeigniter

**Comment by Pyjou** [comment]
+1

**Comment by tagliala** [comment]
Sorry, can't keep this open, as per [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Please search and +1 existing requests eg. #2151 #2392 and open new individual requests for other brands

Closing here
