### ISSUE TITLE
Icon Request: fa-digitalocean

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#5419]
Icon for DigitalOcean.com hosting. Can be used with "Hosted by"

**Comment by kirkbeard** [comment]
:thumbsup:

Digital Ocean logos are available here: https://www.digitalocean.com/company/logos-and-badges/

**Comment by matriphe** [comment]
:+1: yeah!

**Comment by riot26** [comment]
👍

**Comment by fix** [comment]
:+1:

**Comment by chadaracine** [comment]
:thumbsup:

**Comment by darkshell** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by dmyers** [comment]
This would be a great addition! :+1:

**Comment by JayHoltslander** [comment]
+1

**Comment by riot26** [comment]
Digitalocean recently updated logo. It's simpler now and i think it fits perfectly to fontawesome kit :blush:

![DigitalOcean logo](https://www.digitalocean.com/assets/images/logos-badges/DO_Logo_vertical_black-79202407.png)
https://www.digitalocean.com/company/logos-and-badges/

**Comment by NoobTW** [comment]
+1

**Comment by jcalifa** [comment]
Hey, I saw FA isn't accepting PRs with icons, so I'm not entirely sure what the process is to actually get the logo in, but here's the svg in case that helps. Let me know what else I can do to help facilitate this.

[DO_Logo_icon_black.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/634343/DO_Logo_icon_black.svg.zip)

**Comment by iatpatelishan** [comment]
(Y)

**Comment by jpmck** [comment]
👍

**Comment by phrfpeixoto** [comment]
👍

**Comment by Solid2FATesting** [comment]
👍

**Comment by timtjtim** [comment]
![](https://www.digitalocean.com/assets/media/logos-badges/DO_Logo_icon_black-1d88cfb9.png) looks perfect. Any news on this (perhaps 5.0.0 milestone?)

**Comment by fermin-silva** [comment]
👍

**Comment by andrewsomething** [comment]
:tada: Looks like this actually landed at some point! https://fontawesome.com/icons/digital-ocean?style=brands

**Comment by timtjtim** [comment]
@taglila can be closed!?

**Comment by aethior** [comment]
> 🎉 Looks like this actually landed at some point! https://fontawesome.com/icons/digital-ocean?style=brands

@tagliala You can close here. :)
