### ISSUE TITLE
Icon Request: location-arrow-o

### ISSUE THREAD

**Issue by spacedevin** [FortAwesome/Font-Awesome#5425]
Similar to location-arrow

![image](https://cloud.githubusercontent.com/assets/27974/5804794/d4936788-9fbd-11e4-88ec-358323ac2839.png)

used in certain design cases

<3

**Comment by ryanhar** [comment]
This is more of a share looking icon. But it could be handy

**Comment by sfeakes** [comment]
Please sign me up for this request as well.
Usecase would be similar to that of the location icon on iOS & Android devices, ie 3 modes (location found & following(active) / location found & not following(inactive) / Off)
location found & active = current icon (fa-location-arrow)
location found & not active = this request icon (fa-location-arrow-o)
off = (blank)

**Comment by aethior** [comment]
Hi @spacedevin,

Is this request solved using the [solid version](https://fontawesome.com/icons/location-arrow?s=solid) and the [regular version](https://fontawesome.com/icons/location-arrow?s=regular)?

Regards.

cc/ @tagliala

**Comment by sensibleworld** [comment]
With our light and thing styles, this should be covered.
