### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by gorliya** [FortAwesome/Font-Awesome#5426]
Computer:Dimension 9200
System:windows xp
The browser:safari
Problem:Cause a blue screen(if i use the font)
Technical information:[stop:0x000000E3(0x87D5AD40,0x88254DA0,0x00000000,0x00000002)]

**Comment by tagliala** [comment]
Hi,

windows xp and safari for windows are no longer supported by microsoft and apple from a long time. Keeping this open but I will not check into this issue
