### ISSUE TITLE
Icon Request: football / soccer match actions icons

### ISSUE THREAD

**Issue by PixelT** [FortAwesome/Font-Awesome#5428]
Please add icons representing football / soccer match actions:
- goal
- not considered goal
- substitution
- offside
- card (globally or individually yellow / red card)
- penalty
- corner
- (referee) whistle
- injury
- added time
- start / break / end - half / match

Examples / inspirations
http://www.titanui.com/wp-content/uploads/2013/08/30/Soccer-Icon-Set-PSD.jpg
http://thumb1.shutterstock.com/display_pic_with_logo/602602/184516700/stock-vector-soccer-icons-set-illustration-eps-184516700.jpg
http://www.lucversleijen.nl/wp-content/uploads/icons2.jpg

**Comment by volcaniceberg** [comment]
+1. I heavily second this, particularly the cards. I can make do using fa-square and stacking two together but it's not ideal. To be honest, you could just do fa-rectangle and that would be perfect... and be of multiple use

**Comment by tagliala** [comment]
@volcaniceberg sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here
