### ISSUE TITLE
Icon Request: icon-caravan

### ISSUE THREAD

**Issue by Izopi4a** [FortAwesome/Font-Awesome#5429]
I am making a webside for car sales, and I have cars, caravans / motorhomes, motors and trucks

so I see there are both car and trucks, but i would love to have the other 2 :-)

Cheers for the lovely work you guys are doing :+1: 

ex. caravan : https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQN3QU9ictavgjVpGGCEmCJx84bIsYlsJf-8OQvDrY0Yt9nt-XmWPjy9RM

ex. morotbike: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRw5_3telblAFhsCuFrO-piUriXmcrhPHDndQXFekSXRobCG7risxX4WQ

**Comment by tagliala** [comment]
motorbike is a dup of #1953, please +1 that request

renaming as icon-caravan

**Comment by G-Driver** [comment]
+1

**Comment by powermax** [comment]
+1

**Comment by warnkeTV** [comment]
+1

**Comment by CameronHall** [comment]
+1

**Comment by enr00ted** [comment]
+1 !

**Comment by codyn329** [comment]
+1

**Comment by Wouter-M** [comment]
+1

**Comment by stefankellens** [comment]
+1

**Comment by cherrador** [comment]
@tagliala Does this and #7369 are related?

**Comment by stefankellens** [comment]
Hello



A caravan and a trailer are not the same



Caravan = [https://cloud.githubusercontent.com/assets/7613487/9643124/4e6e5676-51c0-11e5-8998-b84acdd029a0.png]



Trailer = [https://cloud.githubusercontent.com/assets/7613487/9643123/4e6da870-51c0-11e5-8b52-064927a4e2af.png]



Greetings



Stefan Kellens
Analyst BRIO4YOU
stefan.kellens@portima.com




[cid:image5c8ad4.BMP@6b2c80bf.4b81620c]

[cid:image32146e.BMP@5871beac.419c1245]             portima cvba/scrl
             terhulpsesteenweg 150          T 02 661 44 11
            150 chaussée de la hulpe       F 02 661 44 00
                                                     1170 brussel/bruxelles           www.portima.com<http://www.portima.com/>

 Disclaimer: www.portima.com/disclaimer.aspx<http://www.portima.com/disclaimer.aspx>



________________________________
Van: cherrador [notifications@github.com]
Verzonden: zaterdag 30 januari 2016 0:47
Aan: FortAwesome/Font-Awesome
CC: Stefan.Kellens
Onderwerp: Re: [Font-Awesome] Icon Request: icon-caravan (#5429)


@tagliala<https://github.com/tagliala> Does this and #7369<https://github.com/FortAwesome/Font-Awesome/issues/7369> are related?

**Comment by campkids** [comment]
I requested a camper and tent icon and they were deleted for being duplicates.  I now see here they were requested already.  Will this page be updated if request is accepted?  Trying to understand the process. Thank you.

**Comment by 4theluvOcheesse** [comment]
caravan +1

**Comment by nikkiroylance** [comment]
Campervan +1

**Comment by danivek** [comment]
+1

**Comment by levelnis** [comment]
caravan +1

**Comment by tomjramsden** [comment]
+1

**Comment by BookingForce** [comment]
fa-caravan +1

**Comment by Crissov** [comment]
Unicode emoji 🚙 [U+1F699 Recreational Vehicle](http://emojipedia.org/recreational-vehicle/) is sometimes displayed like a sports-utility vehicle #6509, but sometimes as a caravan. #222

**Comment by tassoman** [comment]
fa-rv ?

**Comment by eddeh** [comment]
+1

**Comment by camaubs** [comment]
+1 for Caravan

**Comment by rlefevere** [comment]
Thumbs up! Looking for this caravan icon as well

**Comment by unarmedwombat** [comment]
+1 Here's what I am using:
![image](https://user-images.githubusercontent.com/3594641/38921799-83c53d22-42ee-11e8-9170-543754fb8a47.png)
![image](https://user-images.githubusercontent.com/3594641/38921811-8af18a10-42ee-11e8-94d5-970a76ffbd9a.png)

**Comment by unarmedwombat** [comment]
Also, I need a motorhome (RV) as well. Here's my (poor) attempt:

![image](https://user-images.githubusercontent.com/3594641/38922020-1bb5b756-42ef-11e8-9714-58bf490b415b.png)
![image](https://user-images.githubusercontent.com/3594641/38922027-2010afe0-42ef-11e8-8837-4877c7d0ce44.png)

**Comment by eli-mybanker** [comment]
+1

**Comment by centarjun** [comment]
+1

**Comment by eastcoastjac** [comment]
Any idea when these will be added? We could do with more camping/travel icons in general :)

**Comment by Ghotrek** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=caravan
