### ISSUE TITLE
Icon request: icon-truck-flatbed

### ISSUE THREAD

**Issue by daniebruwer** [FortAwesome/Font-Awesome#543]
I would love to see a Flatbed version of "icon-truck" the easiest might simply be to cut off a square at back.

Here's another example of a flatbed.

lorry_flatbed.png

http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png

![lorry_flatbed](https://f.cloud.github.com/assets/890364/2038309/a9bce456-898b-11e3-9071-434c6e208c7d.png)

http://www.wpclipart.com/transportation/car/icons_BW/flatbed_truck_BW_icon_T.png

**Comment by leonkunert** [comment]
+1

**Comment by sensibleworld** [comment]
@daniebruwer Would this icon work (with the container removed?): https://fontawesome.com/icons/truck-container?style=solid

**Comment by lizzbrazen** [comment]
+1 very important for shipping and logistics industries

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
