### ISSUE TITLE
Icon Request: fa-chevron-circle-down-o, fa-chevron-circle-left-o, fa-chevron-circle-right-o, fa-chevron-circle-up-o

### ISSUE THREAD

**Issue by jasonfenton** [FortAwesome/Font-Awesome#5433]
It would be excellent if you could make an outline version of the "fa-chevron-circle" icons.
For example a combination of "fa-circle-thin" and "fa-chevron-right" and/or "fa-chevron-left".

We use this style for navigational elements such as carousel next/previous and also in call to action links and it in a-lot of cases it is difficult to use without making the combination into an image for use.

If you can create this it would be greatly appreciated :)))

Thanks in advance and also for all your excellent work.

**Comment by grgcombs** [comment]
++++1

**Comment by pavestru** [comment]
+1
I tried [stacking](https://jsfiddle.net/4gq3jcLg/), but it won't do the trick.

**Comment by matthodkinson** [comment]
++++++++1

**Comment by hanish-singla** [comment]
Hey guys. . . Does anyone know status of this thread. I really need this icon. Currently doing trick using "fa fa-circle-o" and "fa-chevron-right". But its just awe-full. Kindly let me know if anyone has leads.

**Comment by davidgebbett** [comment]
+++1 

Any update on when/if this icons are being added?

**Comment by tagliala** [comment]
They are available in FA 5 Pro

https://fontawesome.com/icons/circle-chevron-up?s=regular
https://fontawesome.com/icons/circle-chevron-right?s=regular
https://fontawesome.com/icons/circle-chevron-down?s=regular
https://fontawesome.com/icons/circle-chevron-left?s=regular
