### ISSUE TITLE
Icon Request: fa-tea

### ISSUE THREAD

**Issue by JoySR** [FortAwesome/Font-Awesome#5436]
Uses:
Tea shops, cafes, tea culture
Iconographic signage
More synonymous with tea than the existing fa-coffee icon
Could be rolled into #1895

Examples:
![unknown](https://cloud.githubusercontent.com/assets/6264998/5835985/332fe566-a16f-11e4-9969-fa2c1e1a53a6.jpeg)
![unknown](https://cloud.githubusercontent.com/assets/6264998/5835986/38e74a3a-a16f-11e4-985d-fd27e43a7c95.png)

**Comment by cloudhi** [comment]
+1

**Comment by nathraQ** [comment]
+1

**Comment by bertoost** [comment]
+1
fa-coffee / fa-tea?

**Comment by FreddieV4** [comment]
+1

**Comment by tkm-kj** [comment]
+1

**Comment by Konspaul** [comment]
+1 you can try fa-leaf aswell

**Comment by aouakki** [comment]
+1

**Comment by superflycrazy** [comment]
+1

**Comment by sensibleworld** [comment]
Anyone fancy a good strong cuppa? https://fontawesome.com/icons/mug-tea?style=solid
