### ISSUE TITLE
Icon Request: fa-panoramio

### ISSUE THREAD

**Issue by glogloman** [FortAwesome/Font-Awesome#5437]
Hi there, please, can you add Panoramio icon to your Font-Awesome icon set? I would like to use it in header of my personal webpage, where I already have Facebook, YouTube and RSS icons.. Panoramio is great service for placing photos to Google maps. ;) Big thanks in advanced.

**Comment by tagliala** [comment]
duplicate of #2562, please +1 that request

closing here
