### ISSUE TITLE
Icon request: Creative Commons symbols

### ISSUE THREAD

**Issue by jeffreycrow** [FortAwesome/Font-Awesome#544]
The circular CC symbols, available here: http://creativecommons.org/about/downloads

They're available as images but having them as a web font would really increase the versatility, allowing for hover effects and the like.

**Comment by AnMartini** [comment]
+1

**Comment by weshysell** [comment]
+1

**Comment by janyksteenbeek** [comment]
+1

**Comment by Nancarrow** [comment]
+1

**Comment by perre** [comment]
+1
// pls scan comments before suggesting that these icons are already available elsewhere. Just about every person +1'ing this already knows that Creative Commons offers its own 6KB TTF featuring all their icons. The reason this is requested here, and has so many +1s and duplicate requests on GitHub, is that we'd like the to serve to our users a single icon font set with a single script/syntax to reference any of Font Awesome's icons or Creative Commons' icons.

**Comment by joaosaragossa** [comment]
+1

**Comment by jezza323** [comment]
+1

**Comment by designiq** [comment]
+1

**Comment by frax75** [comment]
+1

**Comment by pymarco** [comment]
+1

**Comment by ryanknutson** [comment]
+1

**Comment by k80** [comment]
+1

**Comment by tasmo** [comment]
Going to use [cc-icons](/cc-icons/cc-icons) like [recommended](https://github.com/FortAwesome/Font-Awesome/issues/544#issuecomment-55477490) from @richardba.

**Comment by masolino** [comment]
+1

**Comment by iamjessklein** [comment]
:+1:  Agree to this thread. Ironically I confused the credit card icon with the cc icon. Ideally we would have all of the different icons represented in the [licenses](http://creativecommons.org/licenses/) so that you can specify different kinds of attribution.

Is there anyway to help to push this forward? 


![screen shot 2015-03-05 at 6 04 28 pm](https://cloud.githubusercontent.com/assets/535012/6516706/30788cdc-c362-11e4-9f26-bac57b55597f.png)

**Comment by mattl** [comment]
Let me know if there's anything we can do to help this along :)

@mattl, Tech Lead at CC.

**Comment by Aurielle** [comment]
:+1:

**Comment by richardba** [comment]
@mattl could you please check https://github.com/cc-icons/cc-icons out?

**Comment by G-Driver** [comment]
+1

**Comment by richardba** [comment]
Check out cc-icons at github

**Comment by iamjessklein** [comment]
@richardba - these are great - I just wish that they were integrated into this frequently used font. :+1:

**Comment by dirtyhenry** [comment]
+1

**Comment by richardba** [comment]
@tagliala could you please close this issue?

**Comment by G-Driver** [comment]
@richardba for what?

**Comment by grantneufeld** [comment]
@richardba The Creative Commons icons are not yet including in FontAwesome, so the issue should not be closed. Just because you have another font with the icons does not address what other people are asking for here.

**Comment by 153957** [comment]
+1

**Comment by JonathanReeve** [comment]
+1

**Comment by tagliala** [comment]
@richardba is not wrong, but I can't close this request

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

I understand that you this request contains 11 icons

**Comment by grantneufeld** [comment]
@tagliala I would argue that the Creative Commons icons are not really “a very specific field” as they have a wide-ranging use both on and off the internet (science, visual arts, media arts, politics, discussion forums, engineering, journalism, software, academia, design,…).

That said, if you would like us to break up this request into the individual icons, please let us know.

One might also distinguish between the 5 “core” license icons (CC, BY, NC, ND, SA) and the other 6 icons distributed by the Creative Commons group.

**Comment by iamjessklein** [comment]
I agree with @grantneufeld 's suggestion. These are individual types of licenses that all were designed by the same organization with the same philosophy in mind, however are different and distinct icons. The mere fact that this thread is so heated and long is indicative that these are widely used icons, particularly for those of us who create web-based content.

**Comment by hamishcampbell** [comment]
They're definitely not related to a 'very specific field'. Some examples:

  * Wikipedia and StackExchange[<sup>1</sup>](http://blog.stackoverflow.com/2009/06/attribution-required/)
  * New Zealand Government[<sup>2</sup>](https://www.ict.govt.nz/guidance-and-resources/open-government/new-zealand-government-open-access-and-licensing-nzgoal-framework/)
  * Wired.com photo archive[<sup>2</sup>](http://creativecommons.org/weblog/entry/30274)
  * OpenStreetMap Cartography[<sup>3</sup>](http://www.openstreetmap.org/copyright)
  * The FontAwesome documentation!

I think it's fair to say that these are *very* high-value icons.

**Comment by manujarvinen** [comment]
Also some blogging platforms like [getgrav.org](http://www.getgrav.org) have a built-in FontAwesome support and newbie users can include the FontAwesome icons not only to their blog posts but even to the [navigation menu headers](http://getgrav.org/forum#!/theme-development:how-to-use-font-awesome-ico) of their blog. 

Sometimes bloggers use Creative Commons licenses in their posts and using an icon to illustrate that would be just a perfect thing.

**Comment by TheSeg** [comment]
> Please do not request comprehensive sets of icons related to a very specific field.

I have to agree with the rest of the crowd that CC icons aren't a narrow focus.

To me, an example of narrow focus are game controller button icons. A series of icons representing the buttons of all gamepad controllers would be very specific. Only video game sites that illustrating specific commands would need the approved icon for Left Bumper or "Option" button. Very narrow in focus and application.

Creative Commons on the other hand applies to a large amount of media in a large amount of contexts. Just as ™ or ® can be applied to any work, Creative Commons licenses have the same scope.

**Comment by jmcastagnetto** [comment]
A request 2 years, 4 months, 18 days open and counting. It is high time to decide if this is going to be implemented at all.

**Comment by tagliala** [comment]
@jmcastagnetto please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by jmcastagnetto** [comment]
@tagliala been doing something along those lines for quite some time now, using http://cc-icons.github.io/ -- that still does not solve the issue here. A final decision will make it simpler, if there will be no support planned and everyone that needs to use CC icons has to look elsewhere or do their own customization, it should be documented and this issue closed for good.

**Comment by oluc** [comment]
+1

To sum it up, with the intention to move things forward:

Following the [rules for requesting icons](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

- Rule 2, "!specific":
  - CC icons are widely used in many fields, as @hamishcampbell (and others) explained with examples. See https://github.com/FortAwesome/Font-Awesome/issues/544#issuecomment-87462057

- Rule 3, "+1":
  - searching the page for "+1" gives 57 matches
  - it is the [12th most commented issue](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aissue+is%3Aopen+sort%3Acomments-desc) out of 2.469 open ones

- Rule 4, "single icon":
  - this is a request for several icons, however CC icons are used together, side by side, to form a single "complex" icon, depending on the license variation. See http://creativecommons.org/about/downloads
  - if it would really help, this request can easily be split into several requests

- Rule 5: 
  - CC icons are already created, provided by the CC organization, as a [TTF font](http://mirrors.creativecommons.org/presskit/cc-icons.ttf)
  - so there is no design nor font forging work to do.
  - In addition, @mattl offered help as Tech Lead at CC, see https://github.com/FortAwesome/Font-Awesome/issues/544#issuecomment-77567911.

## Next step
My understanding is that the next step is a "go" or "no go" decision from the Font Awesome project leaders.

In case of positive answer, then would come the integration work.

**Comment by brucellino** [comment]
I'm very surprised there is no fontawesome cc icon yet. I would +1000 if  could, but I can't so I'll just +1.

**Comment by sirajea** [comment]
+1

**Comment by jordanlewin** [comment]
+1

**Comment by Bitbored** [comment]
+1

**Comment by ryan-p-randall** [comment]
+1 

To help show that this isn't a request with a limited or narrow focus, here's a [WordPress Support Page about including Creative Commons license on any blog](https://en.support.wordpress.com/creative-commons/). Certainly WordPress appeals to users beyond a limited or narrow scope.

**Comment by ComedyTomedy** [comment]
+1
More evidence against narrow focus: YouTube includes CC licensing, and Google Search filters for it. That's the 3rd and 1st biggest websites worldwide (in addition to Wikipedia, #6)

**Comment by AndreasWelch** [comment]
+1

**Comment by KRinnNet** [comment]
+1

**Comment by 153957** [comment]
Any day now...

**Comment by kinzdesign** [comment]
+1

**Comment by cbaatz** [comment]
+1

**Comment by dawnmercurio** [comment]
+1

**Comment by 153957** [comment]
The main CC symbol (#5276) has been added and will be available in v4.4:
https://github.com/FortAwesome/Font-Awesome/commit/a2ce7371c0b149a61bb9581c59289ec0f8901b65#diff-1cbc4a03735344662ee8620509c7859fR1920

So this issue remains for the BY NC ND SA (and Public Domain?) icons.

**Comment by grantneufeld** [comment]
I concur with user 153957, and reaffirm my +1 for those remaining Creative Commons symbols.

And thanks to the FontAwesome team for adding the CC icon!

**Comment by perre** [comment]
Fantastic. Thanks for implementing the (cc) icon, FontAwesome team!

**Comment by togis** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by fubarhouse** [comment]
Very nice, it's about time! Thanking you!

**Comment by codyn329** [comment]
+1

**Comment by aethior** [comment]
+1

Example:
![cc](https://cloud.githubusercontent.com/assets/1769227/11531735/48a1ae56-98ff-11e5-89b6-c00d884661bd.png)

**Comment by purpleKarrot** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by nuno-agostinho** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by danniranderis** [comment]
+1

**Comment by caduvieira** [comment]
+1

**Comment by Guichaguri** [comment]
+1

**Comment by triketora** [comment]
+1

**Comment by nickbouton** [comment]
+1

**Comment by mattl** [comment]
CC license buttons are available in a pretty nice, programmatic way from https://licensebuttons.net/i/ which may solve some use cases for now.

**Comment by grantneufeld** [comment]
@mattl There have been a couple similar suggestions above for non-fontawesome sources of the icons (including the CreativeCommons site itself). This request remains focused on having the set of CC icons included in FontAwesome so we can have easy, consistent, access to them along with all the other icons we use in it, and so that we do not have to have our users downloading multiple files.

**Comment by jaw-sh** [comment]
+1. Far more important than more branding icon bullshit.

**Comment by mattl** [comment]
@grantneufeld Are there other trademarks represented in FontAwesome?

**Comment by TheSeg** [comment]
@mattl Both [copyright](http://fontawesome.io/icon/copyright) and [trademark](http://fontawesome.io/icon/trademark) already included. Both of which could be done with `&copy;` (&copy;) and `&trade;` (&trade;), but are unique FontAwesome icons.

**Comment by mattl** [comment]
@TheSeg I mean trademarks of companies and organizations. For example, Microsoft and Apple logos.

**Comment by grantneufeld** [comment]
@mattl I’m not sure why you’re asking about trademarks? This is about the Creative Commons symbols. And, yes, there are loads of trademark icons in the font—the biggest bunch of which are found in the "[Brand Icons](http://fontawesome.io/icons/#brand)” section of the FontAwesome icon list.

**Comment by alsoknownasdrew** [comment]
+1

**Comment by vinc** [comment]
+1

**Comment by ferparmur** [comment]
+1

**Comment by mattl** [comment]
@grantneufeld Creative Commons symbols are trademarks of Creative Commons.

> Our registered trademarks and other trademarks include CREATIVE COMMONS (regardless of stylization, capitalization, translation, or other presentation), CC (including the CC in a circle logo (the “CC Logo”) and CC standing alone), CC+ (within a circle or standing alone), CC0, all of the Creative Commons license and public domain buttons and icons, and any combination of the foregoing, whether integrated into a larger whole or standing alone.

https://creativecommons.org/policies#trademark

**Comment by kwendenarmo** [comment]
CC logo is now available in Font Awesome 5 beta-2

**Comment by deutrino** [comment]
So, an up or down vote was requested, with all the bases covered, 2.5 years ago.

**Comment by dpauli** [comment]
+1

**Comment by sensibleworld** [comment]
Available here: https://fontawesome.com/icons/creative-commons?style=brands

**Comment by cveneziani** [comment]
What about the different symbols: paternity, share alike, non commercial, etc. ?

**Comment by sensibleworld** [comment]
Oops. Sorry... was rushing through some requests. Re-opening.

**Comment by ucffool** [comment]
Here's my current solution to CC: BY-NC-SA
```html
<i class='fab fa-creative-commons fa-fw'></i>
<span class='fa-layers fa-fw'>
  <i class='far fa-circle'></i>
  <i class='fas fa-male' data-fa-transform="shrink-5"></i>
</span>
<span class='fa-layers fa-fw'>
  <i class='far fa-ban'></i>
  <i class='fas fa-dollar-sign' data-fa-transform="shrink-5"></i>
</span>
<span class='fa-layers fa-fw'>
  <i class='far fa-circle'></i>
  <i class='fas fa-undo' data-fa-transform="shrink-7"></i>
</span>
```

**Comment by sensibleworld** [comment]
We've got these all prepped and ready to go. Should be available in the next release or so.

**Comment by robmadole** [comment]
:boom: 5.0.11

**Comment by talbs** [comment]
https://fontawesome.com/icons?d=gallery&q=creative%20commons&s=brands.

**Comment by andrewtweber** [comment]
You guys are doing awesome knocking these out, but I have a complaint about this one - why is the CC so off-centered?

Font Awesome version:

![cc](https://user-images.githubusercontent.com/2760420/39893303-f264610a-5468-11e8-9c08-67ecbf97ee12.png)

vs. official logo:

![2000px-cc logo circle svg](https://user-images.githubusercontent.com/2760420/39893310-f92d0b68-5468-11e8-8110-bd7875d95a23.png)

**Comment by sensibleworld** [comment]
@andrewtweber Thanks for the comment! Something must have gotten lost in translation. We'll look into it.
