### ISSUE TITLE
Icon Request: target-icon (bullseye-arrow)

### ISSUE THREAD

**Issue by lucasluismgomes** [FortAwesome/Font-Awesome#5444]
What about a target icon? It could be used in bussiness aplications, representing goals or missions. I believe it's a good adition

![target-icon_large](https://cloud.githubusercontent.com/assets/10214069/5855583/18dd78ec-a221-11e4-96c0-60dca3c36e09.png)

![thfa9qwf00](https://cloud.githubusercontent.com/assets/10214069/5859294/7f39b88e-a240-11e4-9e17-15487d51416c.jpg)

edit: added new image.

**Comment by tagliala** [comment]
I suppose this one is not doing the job, right? 

http://fontawesome.io/icon/bullseye/

**Comment by lucasluismgomes** [comment]
Hadn't seen this one. I'll surely use it, though I still think that a variation with an arrow would be a great adition for the collection.

**Comment by tagliala** [comment]
your request is legit and I will keep it open, but you should consider a custom build or `bullseye` if you need this icon at the moment

**Comment by lucasluismgomes** [comment]
Thanks for the response. I'm using `bullseye` at the moment. Next time I'll take a closer look at the icons before making a request. Thanks again!

**Comment by xtiggerk** [comment]
+1 ;)
The bullseye don't do the job for me ... it would be great to have a target ! 
Usefull in business app. and to represent goal !

Thanks !

**Comment by 0x1ad2** [comment]
+1 the arrow will add more value to the icon.
Maybe a fa-bullseye and a fa-target or fa-bullseye-hit

**Comment by kuatsure** [comment]
I also :+1: this ... :) could be the preposed icon or crosshairs ( or both )

**Comment by miradnan** [comment]
+1

**Comment by mashruravi** [comment]
+1

**Comment by sallouh** [comment]
+1

**Comment by rafalkasa** [comment]
+1

**Comment by ekkans** [comment]
+1

**Comment by tscizzle** [comment]
+1

**Comment by ahsomchoi** [comment]
+1

**Comment by jeanlamy** [comment]
+1

**Comment by ckshekhar73** [comment]
Bullseye with an arrow would be more helpful in business application to show goal or target.

**Comment by radicalnerds** [comment]
Thoughts? I am bad at sketch fyi.

![bullseye-arrow](https://cloud.githubusercontent.com/assets/25675133/25462826/93eaca3e-2aa6-11e7-8fd9-8e31889dafb0.png)
[bullseye-arrow.zip](https://github.com/FortAwesome/Font-Awesome/files/960112/bullseye-arrow.zip)

**Comment by jdwholmes** [comment]
+1

**Comment by orthlieb** [comment]
+1

**Comment by dalter35** [comment]
+1

**Comment by BjH14** [comment]
+1

**Comment by devou33** [comment]
+1 - Here is the modified version of target I created for my apps:
<img width="509" alt="screen shot 2018-03-28 at 11 44 04 am" src="https://user-images.githubusercontent.com/7987602/38043753-99619cd8-327d-11e8-86d8-1ce5252573f4.png">

[bullseye-arrow.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1856877/bullseye-arrow.svg.zip)

**Comment by manuelph** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/bullseye-arrow?style=solid
