### ISSUE TITLE
Icon Request: fa-bed

### ISSUE THREAD

**Issue by PabloArty** [FortAwesome/Font-Awesome#5445]
Hi! I was looking for a bed icon. I'm developing a website for an architecture office. And in the description of the houses that they are selling they want to use a bed to represent the rooms that the house have. This icon could be useful for hotel/hostal website, architecture, maybe for institutions. I leave here a use and example of the icon.
![bed-icon](https://cloud.githubusercontent.com/assets/6517199/5859514/6fe810f8-a220-11e4-81d0-a0d9981105c5.jpg)
![captura de pantalla 2015-01-22 a las 10 20 59](https://cloud.githubusercontent.com/assets/6517199/5859515/727278a4-a220-11e4-988d-6f9d8a1b743b.png)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/bed/ <-- just released!

**Comment by PabloArty** [comment]
thank you! :D



2015-01-22 13:29 GMT-06:00 Geremia Taglialatela <notifications@github.com>:
