### ISSUE TITLE
Icon Request: icon-drone

### ISSUE THREAD

**Issue by ggoyard** [FortAwesome/Font-Awesome#5446]
Hi everyone, 

I'm setting up my new "personal branding" site. Under my "hobbies", I would very much like to use a Drone Icon to tell the world I can do aerial videos for your touristic business.

Please find an example attached.

Cheers;)

![drone](https://cloud.githubusercontent.com/assets/10657575/5861121/b585d7e4-a266-11e4-8b5a-c030749c225f.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by Bjornftw** [comment]
+1

**Comment by DanielGasperoni** [comment]
+1

**Comment by dtomlinsonweb** [comment]
+1

**Comment by 4dtechsolutions** [comment]
+1

**Comment by mxbstudios** [comment]
+1

**Comment by sarahmaginness** [comment]
+1

**Comment by JonnyMurton** [comment]
+1

**Comment by tezma90** [comment]
+1

**Comment by Hoegbo** [comment]
+1

**Comment by DaSchTour** [comment]
+1

**Comment by webrunner74** [comment]
+1

**Comment by bricker0** [comment]
any progress? I would love to use this icon too!

**Comment by mcxnet** [comment]
+1

**Comment by pitus** [comment]
+1 for our Farming support site where they'll use Drones to do scouting

**Comment by Zai** [comment]
+1

**Comment by marc71** [comment]
+1

**Comment by arturmamedov** [comment]
+1

**Comment by orismology** [comment]
+1

**Comment by douglasdeodato** [comment]
+1 , what about this?

![drone-128](https://cloud.githubusercontent.com/assets/993318/16267618/a8fa2b2a-3882-11e6-8aa0-d2b4610fb811.png)

**Comment by Dunky13** [comment]
+1

**Comment by serjy** [comment]
+1

**Comment by thomasbird1984** [comment]
I like this a bit more 
![135744899](https://cloud.githubusercontent.com/assets/1638025/24186951/275c9854-0eb1-11e7-9788-1151df104181.jpg)

**Comment by thomasbird1984** [comment]
+1

**Comment by CarSiMir** [comment]
+1

**Comment by yebo29** [comment]
+1

**Comment by yadavricha1288** [comment]
+1 Need drone icon from my application, It would be great if can be added

**Comment by Reflex14** [comment]
+1

**Comment by AJ-Acevedo** [comment]
Here is an example of a drone that looks like it would fit inline with the font awesome style.

![hotprops](https://user-images.githubusercontent.com/953092/29843069-c5f416ae-8cd8-11e7-829b-2a0f807e375c.png)

**Comment by MoritzBru** [comment]
+1
I would also love to see a drone icon in FA5.
I personally prefere a top-down look like the "hotprops" but to be more generic a frontal view might be better?

**Comment by danialcala94** [comment]
+1

**Comment by Newabi** [comment]
+1

**Comment by mrchrisjoy** [comment]
+1

**Comment by derDeno** [comment]
+1

**Comment by AJ-Acevedo** [comment]
Here are two great options:

![drone icon](https://user-images.githubusercontent.com/953092/35781661-f452950c-09ba-11e8-98b9-87a3852de1a2.jpg)

![drone 2](https://user-images.githubusercontent.com/953092/35781662-f7501158-09ba-11e8-9962-31380d150bac.jpg)

**Comment by chrisbeach** [comment]
+1

**Comment by SehgalDivij** [comment]
so many +1s. Still can't find the icon, though.

**Comment by sscots** [comment]
+1

**Comment by nckinsella** [comment]
+1

**Comment by prashantfulara** [comment]
+1
any update by when it will be available ?

**Comment by AJ-Acevedo** [comment]
Here's a +1 for your +1

**Comment by rabbishuki** [comment]
+1

**Comment by kevin-appelt** [comment]
+1
An info regarding the status of this icon would be great.

**Comment by Matt-Lane** [comment]
+1

**Comment by tedbergeron** [comment]
We really need a drone icon. Especially before flying cars become a thing.

**Comment by ocdsoft** [comment]
Yes, please!

**Comment by dlkulp** [comment]
+1

**Comment by maximeDore** [comment]
+1

**Comment by pakastin** [comment]
+1

**Comment by ebatsin** [comment]
+1

**Comment by eti-nne** [comment]
+1

**Comment by ZENUAV** [comment]
Drones are a hot topic! A range of related icons is a must!!

**Comment by nicomputer** [comment]
+1 really need that urgently. Please add at least some icons on the fontawesome pro.
Thank you in advance
Best Regards
Nico

**Comment by sensibleworld** [comment]
@nicomputer It's in progress and should be out in our next full release. Hopefully version 5.9.

**Comment by DaBozUK** [comment]
Any approximate timeline for 5.9?

**Comment by austinhal** [comment]
+1

**Comment by sensibleworld** [comment]
Hey there! We've added a couple of drone icons to Font Awesome Pro:

- https://fontawesome.com/icons/drone?style=solid
- https://fontawesome.com/icons/drone-alt?style=solid
