### ISSUE TITLE
new icon request

### ISSUE THREAD

**Issue by weibangtuo** [FortAwesome/Font-Awesome#5452]
I want some icons.
* Host
* VM(Virtual Machine)
* Client or Agent
* Monitor or Report

**Comment by tagliala** [comment]
hi,

sorry but I can't keep this open, this doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

You should make individual requests and search before opening new ones. You should also provide examples and use proper titles.

E.g: host is quite abstract, as well as client/agent

VM: #5134, please +1 that request
Monitor: #1059 , please +1 that request (if you are looking for this kind of monitor)
