### ISSUE TITLE
Icon request: icon-battery

### ISSUE THREAD

**Issue by ianclegg22** [FortAwesome/Font-Awesome#5455]
This will be used to:
 - Get battery level reported of cell phone
 - Get battery level of hardware being reported

As this is part of a menu item, only a single icon is required.  Here is some possibilities with color,  but making a single one like the rest of your icons
![battery_charged](https://cloud.githubusercontent.com/assets/7119463/5872489/e0c3cb08-a2f4-11e4-9b11-f1a8f66e8620.png)
 will be awesome:

**Comment by tagliala** [comment]
I'm going to consider this a dup of #2148, please +1 that request and post there your example

closing here
