### ISSUE TITLE
Icon request: icon-table-simple

### ISSUE THREAD

**Issue by vd-roset** [FortAwesome/Font-Awesome#5457]
Hi.
We are currently developing system for viewing cadastral data and we have lots and lots of definition tables. We also use your awesome icons, but the table icon is quite complex and does not really suit the overall view of our app. Could you please include simplified table icon?
It could be named as simple or definition table.

![table](https://cloud.githubusercontent.com/assets/10669932/5874839/95ff3686-a306-11e4-9373-c82b40c2c71c.png)

We would really much appreciate it.

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/table-list?

cc/ @tagliala

**Comment by tagliala** [comment]
Yes, thanks

I think that the redesign done in 6.0 made this possible
