### ISSUE TITLE
Most recent version (4.3.0) not published to npm

### ISSUE THREAD

**Issue by feross** [FortAwesome/Font-Awesome#5461]
Please run `npm publish`!

**Comment by tagliala** [comment]
@davegandy ?

Relates to #2664

Thanks again @feross

**Comment by A----** [comment]
Yes please :+1:

**Comment by vanthome** [comment]
+1

**Comment by tagliala** [comment]
I should be done

https://www.npmjs.com/package/font-awesome <--juliankrispel juliankrispel published 2 hours ago

tnx @juliankrispel
