### ISSUE TITLE
Icon request: icon-poll

### ISSUE THREAD

**Issue by sjorstimmer** [FortAwesome/Font-Awesome#547]
Could look a lot like the bar chart icon rotated 90degrees

**Comment by Simonn-** [comment]
+1

**Comment by ohru** [comment]
+1 
Something like `fa-bar-chart`, but without axes.

**Comment by pclinger** [comment]
+1, exactly what @ohru said. fa-bar-chart with no lines

**Comment by boynet** [comment]
+1

**Comment by gNesh01** [comment]
+1

**Comment by sepehrr** [comment]
+1

**Comment by bomale** [comment]
+1

**Comment by dev1337** [comment]
+1

**Comment by trf000** [comment]
+1

**Comment by aaxc** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/poll?style=solid
https://fontawesome.com/icons/poll-h?style=solid
