### ISSUE TITLE
Icon Request: fa-firefox

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5470]
Mozilla Firefox web browser (logo) icon. I would like to use this icon when I'm notifying users that their browser version is too old.

fa-firefox
fa-chrome
fa-internet-explorer
fa-safari

<img src="http://people.mozilla.org/~faaborg/files/shiretoko/firefoxIcon/firefox-128.png" border="0" />

**Comment by tagliala** [comment]
#219
