### ISSUE TITLE
Icon Request: fa-chrome

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5471]
Google Chrome web browser (logo) icon. I would like to use this icon when I'm notifying users that their browser version is too old.

fa-firefox
fa-chrome
fa-internet-explorer
fa-safari

<img src="http://www.sparepartsplace.com/tl_files/Bilder/Allgemein/chrome128x128.png" border="0" />

**Comment by tagliala** [comment]
#219
