### ISSUE TITLE
Icon Request: fa-internet-explorer

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5472]
Microsoft Internet Explorer web browser (logo) icon. I would like to use this icon when I'm notifying users that their browser version is too old.

fa-firefox
fa-chrome
fa-internet-explorer
fa-safari

<img src="http://wiki.openwebanalytics.com/extensions/owa/modules/base/i/browsers/128x128/ie4.png" border="0" />

**Comment by tagliala** [comment]
#219
