### ISSUE TITLE
Icon Request: fa-safari

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5473]
Apple Safari web browser (logo) icon. I would like to use this icon when I'm notifying users that their browser version is too old.

fa-firefox
fa-chrome
fa-internet-explorer
fa-safari

<img src="http://wiki.openwebanalytics.com/extensions/owa/modules/base/i/browsers/128x128/safari.png" border="0" />

**Comment by tagliala** [comment]
@LateWiksi thanks for making individual requests, but there is a very old and popular request containing all major browsers.

Please +1 #219 , closing here

I will also close other requests for the same reason
