### ISSUE TITLE
Icon Request: fa-globe-europe

### ISSUE THREAD

**Issue by LateWiksi** [FortAwesome/Font-Awesome#5475]
The same icon as the fa-globe, but the map of Europe. Would be nice with the map of Asia too.

Here's the idea:
<img src="http://png.clipart.me/graphics/thumbs/124/globe-earth-icon-set-vector-design-elements_124979642.jpg" border="0" />

**Comment by hebbet** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #281, please +1 that request and please also read comments because it is explained why they are not included
