### ISSUE TITLE
Icon Request: fa-idea

### ISSUE THREAD

**Issue by nizamalfian** [FortAwesome/Font-Awesome#5477]
I think the icon is still not created. Idea icon in the form of a lamp which generally describe an inspiration. And I hope you can accept my request. Thank you.

**Comment by oBlissing** [comment]
[fa-lightbulb-o](http://fortawesome.github.io/Font-Awesome/icon/lightbulb-o/)

**Comment by tagliala** [comment]
@oBlissing thanks

closing here
