### ISSUE TITLE
Rendering Issue: Fonts no longer smoothed in Firefox (works under 3.2)

### ISSUE THREAD

**Issue by DaguMW** [FortAwesome/Font-Awesome#5481]
Today I migrated our companys project from Font Awesome 3.2 to 4.3. Unfortunately all Icons smaller than 21px became edged in Firefox.

I checked the following sites and was able to reproduce the issue:
http://fortawesome.github.io/Font-Awesome/3.2.1/icon/compass/
http://fortawesome.github.io/Font-Awesome/icon/compass/

If I manipulate the smallest icon with firebug to style="font-size:20px" I get a smooth Icon with 3.2:
![2015-01-26 17_25_35-icon-compass_ font awesome icons](https://cloud.githubusercontent.com/assets/10711439/5903427/e51a1f38-a581-11e4-964f-60597acd60dd.png)

 and an edged one with 4.3:
![2015-01-26 17_25_21-fa-compass_ font awesome icons](https://cloud.githubusercontent.com/assets/10711439/5903426/e51714be-a581-11e4-9af6-2ae640b2e152.png)

I searched the existing issues but only found one issue with spinning icons so I hope creating a new issue for this problem ist ok.

Firefox is Version 35 under Win 7.

kind regards
Martin

**Comment by tagliala** [comment]
> If I manipulate the smallest icon with firebug to style="font-size:20px" I get a smooth Icon with 3.2:

Pixel perfection is not guaranteed for brands and for non-standard icon size. you should pick up multiples of 14px. 21px is much better pf 20px

**Comment by DaguMW** [comment]
I understand that you cant give any guarantees, but it affects all curved Icons and it worked flawless under 3.2 so shouldnt there be a manageable reason for this? For me it looks like something prevents firefox from smoothing the font under 4.x..

**Comment by DaguMW** [comment]
Sorry for pushing this up again, but I'd really like to understand this behavior and use the new (and upcoming) versions of FontAwesome without loosing display quality :-(

Is there anything I can do on my side?

**Comment by tagliala** [comment]
Use 14px icon size. If you need 16px icon and still need pixel perfection, you consider another font set.

Metrics in 4.* version changed for some reasons (eg: #3683) 

Saying that... @davegandy could you please check if there is an offending export parameter that prevents firefox to antialias icons at <> 14px sizes?

**Comment by LauritzT** [comment]
I don't have this issue in Firefox 37.0a2 (2015-02-12) on Windows.
