### ISSUE TITLE
Safari Sharpness / Blury

### ISSUE THREAD

**Issue by Isengo1989** [FortAwesome/Font-Awesome#5482]
Hello Folks,
I am just trying my hp on different browsers, and in safari my font awesome seem to be very "not sharp" :-/ See here http://www.bilder-upload.eu/show.php?file=07623e-1422293017.png

Screen Solution is the same, and shouldnt be a problem, since its a font, right..

**Comment by tagliala** [comment]
As I could tell, your safari is not antialiasing fonts at all.

![image](https://cloud.githubusercontent.com/assets/556268/5904889/482bc82e-a58c-11e4-923d-5c685e9002d1.png)

Is that safari 5.0 for windows?

Closing here

**Comment by Isengo1989** [comment]
Well I guess it does not, but adding this in my template.css won´t change a thing

html{
-webkit-font-smoothing: antialiased;}
