### ISSUE TITLE
Icon request: icon-wimp

### ISSUE THREAD

**Issue by jonasbj** [FortAwesome/Font-Awesome#5487]
Same as fa-spotify, just a smaller company.

![wimp](https://cloud.githubusercontent.com/assets/372674/5912198/3f2b1380-a5d0-11e4-8ea3-618772c3ea51.png)

**Comment by aethior** [comment]
> WiMP was a music streaming service available on mobiles, tablets, network players and computers. Music in WiMP was streamed using the AAC+ file format in a bitrate of 96 kbit/s or the AAC file format in a bitrate of 320 kbit/s if the high quality streaming option is selected. WiMP also offered a HiFi-product with FLAC/ALAC. **WiMP has since been merged into Tidal**. ([source](https://en.wikipedia.org/wiki/WiMP))

cc/ @tagliala
