### ISSUE TITLE
I wants to add 4 Icon 

### ISSUE THREAD

**Issue by bita147** [FortAwesome/Font-Awesome#5488]
I have 4 Icons
![opc](https://cloud.githubusercontent.com/assets/10580103/5915364/fac1e574-a62a-11e4-957e-8942fa083073.png)
![open](https://cloud.githubusercontent.com/assets/10580103/5915365/fac51582-a62a-11e4-817b-13de35f0ef79.png)
![shared](https://cloud.githubusercontent.com/assets/10580103/5915363/fac10b5e-a62a-11e4-8db8-c8444b3c242b.png)
![unnamed](https://cloud.githubusercontent.com/assets/10580103/5915366/fac66978-a62a-11e4-88cf-492152fd7e98.png)

If it is possible plz add it....

**Comment by tagliala** [comment]
hi @bita147 you should provide a proper title and make individual requests, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

In this case, you could make only two requests, one for "logo-paragraph, logo-paragraph-square" and another one for the cube. Note that there is already a request for a 3d cube. Please use proper titles

You should also include use cases and why these logos are important to the community

If they represent a brand that is not going mainstream, you should consider a custom build of fontawesome

Take a look here:
https://fonticons.com/ (by Dave)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

Closing here
