### ISSUE TITLE
Icon Request: fa-squirrel

### ISSUE THREAD

**Issue by hakaes** [FortAwesome/Font-Awesome#5491]
I really need a squirrel icon for a project, my customer is nuts and he needs for his squirrel feed machines web-site a squirrel font-awesome. 

Something like that would be perfect. 

Thank you!

![squirrel_draft](https://cloud.githubusercontent.com/assets/10711774/5916393/f6519486-a610-11e4-84bd-2f8176d2c025.png)

**Comment by nathraQ** [comment]
as stupid as it may sound I like the idea of animal icons

**Comment by James1x0** [comment]
@nathraQ Same

**Comment by benwo** [comment]
@hakaes A bit of a late reply, but Github's Octicons have a squirrel icon you can use! https://octicons.github.com/icon/squirrel/

![image](https://cloud.githubusercontent.com/assets/1531689/6795563/0f47a8c6-d236-11e4-8a91-36cb0f48b5e4.png)

**Comment by aethior** [comment]
Hi @hakaes,

This icon was added in v5.4.0.
Check https://fontawesome.com/icons/squirrel

Regards.

cc/ @tagliala
