### ISSUE TITLE
Icon Request: icon-cube-outline

### ISSUE THREAD

**Issue by bita147** [FortAwesome/Font-Awesome#5495]
![cube_outline](https://cloud.githubusercontent.com/assets/10580103/5918160/7c73b578-a64b-11e4-8588-b22182ee6877.png)

It is Simply Box type / Folder Type for Categorized Directories.

**Comment by tagliala** [comment]
is this a logo?

**Comment by bita147** [comment]
No

**Comment by tagliala** [comment]
Law paragraph is here: #1706

The proper name for this request should be `icon-paragraph-hexagon` but I will still miss the use case of this particular version

**Comment by bita147** [comment]
Use Case Outline - 

![device-2015-01-27-131736](https://cloud.githubusercontent.com/assets/10580103/5954485/f164ee56-a7bd-11e4-9290-426f86b71562.png)

For All 4 icons

**Comment by bita147** [comment]
Please add Cube icon and Hexagon with/without sign (§)

**Comment by tagliala** [comment]
Closing here
