### ISSUE TITLE
Plant or Flower icon

### ISSUE THREAD

**Issue by marieneig** [FortAwesome/Font-Awesome#5500]
To represent vegetation, environment, ecology, agriculture, florist, etc

**Comment by tagliala** [comment]
there is already a leaf: http://fontawesome.io/icon/leaf/ and a tree http://fontawesome.io/icon/tree/

let me know if those fits your needs

**Comment by tagliala** [comment]
btw flower is a duplicate of #2037

**Comment by marieneig** [comment]
perfect thanks I didn't find it through the searches you can delete this
