### ISSUE TITLE
Icon Request: Trademark

### ISSUE THREAD

**Issue by theSEOeffect** [FortAwesome/Font-Awesome#5504]
I have run into this several times working with attorneys and companies who are very proud of their shiny little trademark and want the TM symbol, similar to how the Copyright symbol already exists.

**Comment by zeebe** [comment]
+1 this is needed

**Comment by Wasabis** [comment]
+1 need this as well

**Comment by kwendenarmo** [comment]
+1

**Comment by LauritzT** [comment]
I don't really see what's wrong with a normal ™ or © symbol..?

**Comment by theSEOeffect** [comment]
@LauritzT  FontAwesome icons are used in a lot of cool interesting ways with special CSS classes and animations. Adding actual icons for ®, ©, ™ would be appropriate in a wide variety of use cases. For instance, my agency is managing a bunch of lawyer websites and we are using icons next to their service descriptions. That is one use case where these icons would come in handy. My agency is also managing websites for a number of start-ups that have proprietary technologies and would like to list their intellectual property among their assets on investor pages. That is another example of a viable use case. The list goes on.

**Comment by simoneduca** [comment]
Agree, +1

**Comment by tagliala** [comment]
Added in 4.4.0

Closing here :)
