### ISSUE TITLE
Implement PaymentFont

### ISSUE THREAD

**Issue by purzlbaum** [FortAwesome/Font-Awesome#5510]
Maybe Font-Awesome should implement the PaymentFont:

http://paymentfont.io/

**Comment by tagliala** [comment]
do you mean include all icons from this set?

**Comment by purzlbaum** [comment]
@tagliala why not, if it's possible?

**Comment by tagliala** [comment]
the whole paymentfont set is larger than Font Awesome itself

If you want, you can strip out payment icons from font awesome and only use paymentfont for that, or make a custom set with both. Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I'm going to close this one, please load that set as a separate asset.

Closing here
