### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by corradam** [FortAwesome/Font-Awesome#5511]
Hi,

I've recently installed a template that includes the Font-Awesome icons. I installed this on a test site which ran fine with all icons loading. Now I have moved it over the real site the icons don't work. I've reuploaded the FA files, added the pieces of code to the <head> to make sure they are there.

The site domain name is https://www.corrchilled.co.uk

Has anyone got any ideas about why it is not working?

**Comment by DanLew** [comment]
Looks like youve got it fixed :+1:

**Comment by corradam** [comment]
Yeah, not a clue how. I think it was because they were looking for the font files in /fonts/fontawesome-webfont.eot but they were in catalog/view/template/fonts/fontawesome-webfont.eot

**Comment by tagliala** [comment]
@corradam glad you solved, closing here
