### ISSUE TITLE
Icon Request: fa-pencil-circle

### ISSUE THREAD

**Issue by Samsinite** [FortAwesome/Font-Awesome#5512]
These would both look the same as their counterparts (fa-pencil-square and fa-times-circle). Would help for completeness, going to use these as edit/delete buttons. Currently, the only complete set is fa-pencile and fa-times.

**Comment by Samsinite** [comment]
Looks like fa-times-square is a dup of #2636, but didn't find any for fa-pencil-circle.

**Comment by geoff-ellison** [comment]
Overlays can be easily done directly in FA: 
https://codepen.io/geebz/pen/PLEMOL

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pen-circle?s=solid

**Comment by tagliala** [comment]
This icon has been added to the Pro set

In a web application it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/83/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
