### ISSUE TITLE
Icon Request: fa-Long Island

### ISSUE THREAD

**Issue by qopel** [FortAwesome/Font-Awesome#5517]
![libw](https://cloud.githubusercontent.com/assets/8602426/5947493/8c626b26-a70b-11e4-8650-82abe8b55755.jpg)
There are 3 million people on Long Island.
Would be nice to have an icon for them
![long island](https://cloud.githubusercontent.com/assets/8602426/5947190/472cdca0-a709-11e4-9196-3dd04d476935.png)

**Comment by tagliala** [comment]
I fear of other 6.997.000.000 :)

Sorry, just kidding. The problem with this kind of icons is that they have a lot of points and they will negatively impact on the file size. Take a look at #281, #1403, #1243, #1403

I'm going to close this one.

I suggest you to look for a svg based solution

**Comment by qopel** [comment]
It doesn't have to be geographically perfect. Just the recognizable "fish" outline.
![li](https://cloud.githubusercontent.com/assets/8602426/6089465/ff863246-ae30-11e4-93d6-444085f454e2.jpg)

**Comment by tagliala** [comment]
@qopel sorry... at the moment I'm closing all country silhouettes related requests
