### ISSUE TITLE
Icon Request: fa-artists

### ISSUE THREAD

**Issue by neerajgdtpl** [FortAwesome/Font-Awesome#5519]
Hi Developers,

Before I say about my requirement, I want to thank you guys for providing us the iconic icons which is easy to use and consumes very less memory and loads easily on the browsers. You guys have done and doing a great job!

I'm happy that you have kept this functionality, so that people can write to you guys about their requests. Thanks for being kind!

So here's my below plan and request - 
I'm building a website which will be repository of variety of artist. Their categories are as below - 

1. Bands 
2. Singers 
3. Instrumentalists  
4. DJs 
5. Anchors/Emcees  
6. Comic Artists  
7. Magicians & Illusionists 
8.  Photographers  
9. Makeup Artists 
 10. Dancers  
11. Appearances  
12. Speakers 
13.  Variety Artists 
14.  Rentals  
15. Packages 
16. Other Services 

And I was wondering if I can get Font-Awesome icons for those artist categories.

(I hope all those categories are self-descriptive)

Hoping to hear from you guys!

Cheers,
Neeraj

**Comment by neerajgdtpl** [comment]
Hi,
Please reply if the above requirement can be done?

Thanks in advance
Neeraj

**Comment by tagliala** [comment]
@neerajgdtpl sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Some of your icons are fine for a broader audience (eg: #1080), others are already here (you can use a fa-camera for photographers) but the most aren't

Feel free to contact Dave privately if you need a custom solution

Closing here

**Comment by neerajgdtpl** [comment]
@tagliala  Thanks for the reply!

I will check with Dave :-)
