### ISSUE TITLE
Icon-Request: (New/Add/Delete)

### ISSUE THREAD

**Issue by StuartHemming** [FortAwesome/Font-Awesome#5521]
Before you ignore this thinking "the twit isn't trying", please read the idea.

I know that there is a plus, minus and asterisk but what I'm talking about is a smaller, version of each that is offset to the top-right hand corner so that it can be easily stacked on top of other icons.

ideally, there would be a solid and an open version of each.

**Comment by tagliala** [comment]
@StuartHemming this is a duplicate of #1181.

There are css workarounds here but at the moment the desired result is not possible to achieve
