### ISSUE TITLE
Icon Request: fa-human

### ISSUE THREAD

**Issue by jmgithub2014** [FortAwesome/Font-Awesome#5523]
Hi Guys,

First i want to thank you for your marvellous works with fa-fonts

So, I'm building a website in which i need to speak about  -

- Brain
- Body
- 5 Senses
- mental
- psychology
- homeostasis (balance)
- Emotions/Emotional
- Relations/Relational

I would like to know if you are able to create such fonts.

I think it would be great if you add biology/medical font as intestine, heart, brain,
 skull, bones, cells ...

Thanks you for your work.

Have a nice day.
John Michael

**Comment by tagliala** [comment]
@jmgithub2014  sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here
