### ISSUE TITLE
Icons.yml has a few unexpected values in the 'created' field 

### ISSUE THREAD

**Issue by mniebling** [FortAwesome/Font-Awesome#5524]
When messing around with the icons.yml data recently, I noticed that there are some instances where an icon appears to have some `filter` values misplaced in the `created` field, causing some unexpected results in places like this:

![image](https://cloud.githubusercontent.com/assets/319534/5961799/c1f29a1a-a7a4-11e4-8fd0-4051af1e5311.png)

Here are the 3 icons I found that exhibit this:

ban:
https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L965

envelope:
https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L2152

windows:
https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L3604

**Comment by tagliala** [comment]
thanks for reporting this.

I don't think a 4.3.1 release is needed for this issue, @davegandy ?
