### ISSUE TITLE
Icon request: icon-open-box

### ISSUE THREAD

**Issue by SewHappy58** [FortAwesome/Font-Awesome#5529]
This would be great to have two boxes, one open and one sealed.  This would help those of us working in shipping to indicated package is now ready for shipping, or getting ready to be shipped.
Thank you so much and awesome job.

![icon_8433](https://cloud.githubusercontent.com/assets/7072324/5968394/a77237da-a7dc-11e4-8498-e67c36f6c8f9.png)
![10164-box-closed](https://cloud.githubusercontent.com/assets/7072324/5968398/b00b730c-a7dc-11e4-95e5-625b58345310.png)

**Comment by andreaslangsays** [comment]
**+1** especially the closed Box would be great!

![](https://cloud.githubusercontent.com/assets/7072324/5968398/b00b730c-a7dc-11e4-95e5-625b58345310.png)

**Comment by KaduAmaral** [comment]
+1 closed box

**Comment by lindows-xx** [comment]
+1 for closed box

**Comment by thehavknots** [comment]
+1 closed and open

**Comment by rkyrychuk** [comment]
+1

**Comment by tagliala** [comment]
Box: https://fontawesome.com/icons/box?style=solid

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/box-open?style=solid
https://fontawesome.com/icons/box-full?style=solid
https://fontawesome.com/icons/box-alt?style=solid
