### ISSUE TITLE
 Icon request: icon-food-fruit-banana

### ISSUE THREAD

**Issue by delfo** [FortAwesome/Font-Awesome#5531]
Hi! this is a wonderful project :)
I'm working on a website to collect recipes and as i would really like it to become a 2.0 one my target would be to make it more 'visual'

In general icons related to food (fruit - vegetables - fish - meat) could be useful in tons of use cases
as well as for icons related to tools 
- icon-food-tools-pot
![icon-food-example](https://cloud.githubusercontent.com/assets/1186553/5974191/b99b34bc-a871-11e4-8c6f-534a62a0679e.png)

**Comment by delfo** [comment]
i'm willing to help! :)

**Comment by tagliala** [comment]
@delfo sorry I didn't get you request. Do you need a banana icon or a comprehensive food set?

**Comment by delfo** [comment]
hi Geremia

The idea is to setup a whole food set

**Comment by tagliala** [comment]
Sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here
