### ISSUE TITLE
font-awesome with bower-installer

### ISSUE THREAD

**Issue by over64** [FortAwesome/Font-Awesome#5532]
This section in your bower.json
```javascript
"main": [
    "./css/font-awesome.css",
    "./fonts/*"
  ]
```

provides these files 
-rw-r--r-- 1 over over  28747 янв 30 16:10 font-awesome.css
-rw-r--r-- 1 over over  93888 янв 30 16:10 FontAwesome.otf
-rw-r--r-- 1 over over  60767 янв 30 16:10 fontawesome-webfont.eot
-rw-r--r-- 1 over over 313398 янв 30 16:10 fontawesome-webfont.svg
-rw-r--r-- 1 over over 122092 янв 30 16:10 fontawesome-webfont.ttf
-rw-r--r-- 1 over over  71508 янв 30 16:10 fontawesome-webfont.woff
-rw-r--r-- 1 over over  56780 янв 30 16:10 fontawesome-webfont.woff2

with bower-installer
but font-awesome.css contains this path
```css
src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.3.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.3.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.3.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.3.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular') format('svg');
```
I have 404 for all fonts in result( It's so sadly

**Comment by tagliala** [comment]
don't know how to help here, this may require a 4.3.1 version. PR are welcome

**Comment by over64** [comment]
Now I have some workaround on backend(Spring) :) Ok I'll wait for next version. Thanks for reply

**Comment by tagliala** [comment]
@over64 any hint would be accepted. e.g.: how bootstrap or other fraweworks solve this issue?

**Comment by tagliala** [comment]
@over64 since we probably need a 4.3.1 version, is there something we can do?

**Comment by gamegenius86** [comment]
@over64 (@tagliala) I don't know too much about `bower-installer` but after taking a look at its github page and some of the issues.  I believe the issue isn't with `Font-Awesome`, but with how you have `bower-installer` configured.  

As you see the Font-Awesome.css is looking for the fonts in the path `../fonts/fontawesome-webfont` which doesn't match the structure that your `bower-installer` paths is setup.  You have everything being installed in the one directory and not in its specific subfolders.  Looking at the docs, you probably want something for paths like the following:

```json
"install" : {
    "path" : {
      "css": "src/css",
      "js": "src/js",
      "eot": "src/fonts",
      "svg": "src/fonts",
      "ttf": "src/fonts",
      "woff": "src/fonts",
      "woff2": "src/fonts",
      "/[sc|le]ss$/": "src/css"
    },
    "sources" : {
      ...
    }
}
```

From what i can tell from `bower-installer` is that one of the major issues is that the file paths defined by the bower component must match the same file structure that you store the files in.  You cant "flatten" the component and toss everything into a single folder as those files will have no idea how to reference each other.  

I would say that if you are still having issues with this that you should probably create an issue for `bower-installer`. The file structure for `Font-Awesome` appears to be the correct (or rather most commonly used) structure.

**Comment by over64** [comment]
I have read bower-installer source. And now I see that bower-installer it's strange thing( Yes, bower-installer makes flat files structure( Twitter Bootstrap has the same issue. It seems that it's unfixable with bower-installer. Now I have work around at server side. But in future I will replace bower-installer with bower/grunt pipeline. Thanks for reply

**Comment by tagliala** [comment]
thanks guys. I'm going to leaving this close and remove the 4.3.1 milestone. Feel free to comment if you have news

**Comment by PerfectCarl** [comment]
I'm having this issue with `grunt` and `bower` and `grunt-bower-task`.

I installed the font via `bower install fontawesome --save` and have a grunt-bower-task defined to cpy bower deps to my `build/` folder. 
```javascript
    bower: {
      install: {
        options: {
          targetDir: './build/vendor'
        }
      }
    },
```

What should I do? File an issue with `bower` or `grunt-bower-task` ?
Or use a different "source" when running `bower install fontawesome --save`?

Is there a workaround ?

**Comment by tagliala** [comment]
@PerfectCarl https://github.com/FortAwesome/Font-Awesome/issues/5532#issuecomment-74118679 <-- this doesn't help?

**Comment by PerfectCarl** [comment]
Why is this issue closed?

**Comment by tagliala** [comment]
@PerfectCarl because of https://github.com/FortAwesome/Font-Awesome/issues/5532#issuecomment-74118679 and https://github.com/FortAwesome/Font-Awesome/issues/5532#issuecomment-74217589


> I have read bower-installer source. And now I see that bower-installer it's strange thing( Yes, bower-installer makes flat files structure( Twitter Bootstrap has the same issue. It seems that it's unfixable with bower-installer. Now I have work around at server side. But in future I will replace bower-installer with bower/grunt pipeline. Thanks for reply

If you have a solution we are listening. I'm not using bower installer

**Comment by over64** [comment]
Look at http://yeoman.io
I have tried generator for angular with bootstrap. It works, but copying css/fonts to dist handled manually with grunt(not bower). Bower used only for downloading dependencies to local bower_components

**Comment by gamegenius86** [comment]
@PerfectCarl this issue is closed because the issue was solved.  however your issue and this issue are not similar at all, as you're not using `bower-installer` which is a separate tool for installing `bower` repositories.  You're just using `bower` to do so.  

I would say that if you're doing a `bower install` on font-awesome and it works, aka it downloads all of the files to its specified location, then the issue isn't with `font-awesome` but most likely an issue with `grunt-bower-task` (probably how you have it configured)

**Comment by PerfectCarl** [comment]
@gamegenius86 Thanks for your help.
This is much clearer for me now.

Thanks guys for all your replies (and patience) :)

**Comment by o0110o** [comment]
@over64

I recently had a similar problem with the font paths in 'font-awesome.css'. My solution was to invoke the 'grunt-string-replace' module inside of 'gruntfile.js' in order to update the paths.

First, install the required module:

    npm install grunt-string-replace --save-dev

Next, add the following snippet to 'gruntfile.js', update the options to suit your needs, register the task, and call it when you need to:

    'string-replace': {
        // Edit the file inline
        inline: {
            // Source and destination paths for 'font-awesome.css'
            files: {
                '_vendor/font-awesome/': '_vendor/font-awesome/**',
            },
            options: {
                replacements: [{
                    // Replacement pattern
                    pattern: /\.\.\/fonts/g,
                    // New font path
                    replacement: 'design/fonts'
                }]
            }
        }
    },
