### ISSUE TITLE
[Bug] The package for Meteor is outdated at 4.2.0_2

### ISSUE THREAD

**Issue by msamoylov** [FortAwesome/Font-Awesome#5533]
It's not possible to upgrade to 4.3.0 from https://atmospherejs.com/fortawesome/fontawesome

**Comment by tagliala** [comment]
#5062

**Comment by dandv** [comment]
@splendido is on it!

**Comment by splendido** [comment]
Ok, I''l try to see what I can do.

@tagliala would you accept a PR which adds only a `package.js` file to the other PM files already present?

In case you'll feel comfortable with this, the only other changes we'd need would be to make the version field appearing inside the `package.js` files updated when you make new builds.
In case, could you give some pointer about your building process? I'm not seeing grunt or gulp files...

Tnx,
Luca

**Comment by tagliala** [comment]
@splendido 
I would like to include official meteor support in 5.0.0 version, but these decisions are up to Dave.

Please send your PR against the `5.0.0-wip` branch

> In case, could you give some pointer about your building process? I'm not seeing grunt or gulp files...

It's still jekyll based. I mean that jekyll is also responsible of creating `.less` and `.srcc` dist files. Very ugly but it does the job. There is a proposal to change the build process ( #1166 ) but this is entirely up to Dave

So: `bundle install` and `jekyll build` should be enough: https://github.com/FortAwesome/Font-Awesome#hacking-on-font-awesome

> Update: it wouldn't be bad to have also a tests.js file specifically for meteor tests to be put where you prefer.

Put it where you think it is best

**Comment by splendido** [comment]
Thanks for your availability @tagliala!

Just to confirm: PM files are updated by hands outside of the `jekyll build' right? See latest [version updates](https://github.com/FortAwesome/Font-Awesome/commit/b590472694c07fb9a188b7fef94d9f6daee46c1e)

**Comment by tagliala** [comment]
hmmm not all of them. I don't know if we need to add others to the list (package.js, components.js). I'm doing that manually at the moment

**Comment by splendido** [comment]
I'd say using `gulp` to automatize the build process would be the best option.
It's getting more and more reliable and it's actually taking over on `grunt`!

...to tell you just one example, Jack from SemanticUI is heavily using it (he's refactoring the whole building process right now actually...)

Ideally, all PM files should be automatically generated from the build process picking up the latest package's information from the `package.json`, so that you won't have to modify them by hands anymore.

But this choice is up to you, surely not up to me. Just my two cents.

Btw, I'll prepare another (leaner) proposal for the meteor integration by means of a PR on the `5.0.0-wip` branch.

Tnx!

**Comment by tagliala** [comment]
> But this choice is up to you, surely not up to me. Just my two cents.

I want a better build process, the choice is up to Dave. Don't know his priorities for 5.0.0 :)

**Comment by splendido** [comment]
Yeah, sorry, with *you* I meant you package maintainers. Dave is obviously involved ;-)

**Comment by splendido** [comment]
Done, See #5543!

**Comment by serkandurusoy** [comment]
Hi there, the package on Meteor is still 4.2.0_2 :(

**Comment by splendido** [comment]
Were still waiting for #5543 to be merged to get automatic updates...
Before that @dandv can manually update it.

**Comment by ErikAbele** [comment]
Would be really nice to get this fixed now and for all times… TIA!

**Comment by splendido** [comment]
@dandv could you make another version bump by hands?

**Comment by ErikAbele** [comment]
Ping?

**Comment by dandv** [comment]
[Fixed!](https://forums.meteor.com/t/who-maintains-the-fortawesome-fontawesome-package-on-atmosphere/2120/15?u=dandv)

**Comment by splendido** [comment]
now at version 4.4.0: [see it on atmoshpere](https://atmospherejs.com/fortawesome/fontawesome)
I guess this issue can be closed now...

**Comment by tagliala** [comment]
@splendido thanks!

closing here
