### ISSUE TITLE
Icon request: icon-perspective, icon-scale

### ISSUE THREAD

**Issue by krk** [FortAwesome/Font-Awesome#5534]
For buttons in an image editing application, to activate the perspective transformation tool and scale tool.

icon-perspective: 
![artrage_4_manua-181](https://cloud.githubusercontent.com/assets/1447853/5975892/c8eb367e-a88f-11e4-9d9f-ff87dc024762.png)

icon-scale:
![scale](https://cloud.githubusercontent.com/assets/1447853/5975905/049c2232-a890-11e4-9dde-38d8f201a9b2.jpg)

**Comment by tagliala** [comment]
please split this request in two individual request, thanks!

**Comment by krk** [comment]
Split into #5895 and #5896
