### ISSUE TITLE
hyperlink Stack is flickerting

### ISSUE THREAD

**Issue by avarndell** [FortAwesome/Font-Awesome#5536]
I have a stacked icons that are flickering when going from outside circle to inner

![flicker](https://cloud.githubusercontent.com/assets/7513911/5979161/43325808-a873-11e4-8798-7dca3b75b962.png)

**Comment by tagliala** [comment]
could you please create a fiddle? you could start with this one: http://jsfiddle.net/tagliala/e9yfxsfj/
