### ISSUE TITLE
href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" doesn`t work

### ISSUE THREAD

**Issue by helloncanella** [FortAwesome/Font-Awesome#5539]
I'm trying to use the link above, but it isn't working.

I have had to use this one (given in the stackoverflow) : http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css

**Comment by zudomc** [comment]
Shouldn't this be on the MaxCDN/bootstrap-cdn issues page?

**Comment by tagliala** [comment]
@helloncanella I confirm they work. They are protocol relative urls, so if you are testing your webapp locally (`file://`) they will not work unless you add http: at the front

Closing here

**Comment by helloncanella** [comment]
@tagliala Thanks. Dumb newbie error. Thank you for the patience to respond this post.

**Comment by tagliala** [comment]
@helloncanella no problem :+1:
