### ISSUE TITLE
Font-Awesome isn't working locally  

### ISSUE THREAD

**Issue by helloncanella** [FortAwesome/Font-Awesome#5540]
I've downloaded the package, retrieved the font-awesome.min.css to a custom css folder, but it didn't work.

**Comment by helloncanella** [comment]
Solved problem

**Comment by acshef** [comment]
For future reference, would you mind posting the solution that worked for you, or a link to the solution? Thanks!

**Comment by tagliala** [comment]
@acshef : https://github.com/FortAwesome/Font-Awesome/issues/5539#issuecomment-72314217

I'm going to edit the troubleshooting guide

**Comment by helloncanella** [comment]
The problem was I wasn't referencing the location of font-awesome.min.css correctly.

Instead of use 'paht/to/font-awesome-4.3.0/css/font-awesome.min.css', I was using a copy of font-awesome.min.css retrieved from the original source that 'I've put in my css folder
