### ISSUE TITLE
Icon request fa-laundry

### ISSUE THREAD

**Issue by encodia** [FortAwesome/Font-Awesome#5542]
Need an icon (or better a set maybe?) to manage a laundry hotel application.

Thank you for your great work.

**Comment by lenamtl** [comment]
+1

**Comment by tagliala** [comment]
any example?

**Comment by tagliala** [comment]
a washing machine?

**Comment by encodia** [comment]
Ciao,

I can give you 2 examples:

http://thumbs.dreamstime.com/z/icon-set-laundry-symbols-vector-illustration-34266160.jpg

or more generic

http://us.123rf.com/450wm/greyjj/greyjj1404/greyjj140400021/27426067-vector-laundry-icons-set.jpg

**Comment by lenamtl** [comment]
I'm looking for the more generic one, like the first link.
The laundry symbol (second link) was requested already I think.

**Comment by tagliala** [comment]
Sorry can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
