### ISSUE TITLE
Icon Request: fa-biking

### ISSUE THREAD

**Issue by grzeg1** [FortAwesome/Font-Awesome#5544]
Main use: open source training diary. Project at:
https://github.com/Runalyze/Runalyze
Currently finishing restyled v2.0 with Atari-like sports icons ;) 

Three main sports composing triathlon are crucial. Cycling the least, as it probably could be replaced by fa-bicycle for starters.
Other possible uses: other sports-related projects.
We'd be grateful if you could help.

**Comment by gettala** [comment]
+1

**Comment by jmcopeland** [comment]
+1

**Comment by Azinheiro** [comment]
+ 1 for swimming. that s a great idea.

**Comment by ChrisLegg** [comment]
+1

**Comment by millsy** [comment]
+1

**Comment by tagliala** [comment]
swimming: #5771 
running: #1156 

leaving this open as icon-biking

**Comment by tbarnes** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by Fatbat** [comment]
+1 for a cycling icon.

**Comment by sensibleworld** [comment]
It's finally nice enough outside to break out these new `biking` icons: https://fontawesome.com/icons?d=gallery&q=biking&s=solid&v=5.9.0
