### ISSUE TITLE
Icon Request: icon-Polyvore

### ISSUE THREAD

**Issue by andreahud** [FortAwesome/Font-Awesome#5545]
I am a user of Polyvore and would love to have an icon to use in my social networking icons. I think the users of polyvore would love it, as well. Thank you.
![polyvore](https://cloud.githubusercontent.com/assets/10791697/5990431/8d5f85f2-a97e-11e4-9627-2046c50697f9.jpg)

**Comment by aethior** [comment]
>On April 5, 2018, Polyvore announced that it had been acquired by SSENSE and would cease operations immediately. Users wishing to save their account data were directed to a request form on the Polyvore blog. ([more info](https://en.wikipedia.org/wiki/Polyvore))

cc/ @tagliala
