### ISSUE TITLE
Icon Request: fa-contents

### ISSUE THREAD

**Issue by shemani** [FortAwesome/Font-Awesome#5548]
Use Case: Table of contents icon
![toc_icon](https://cloud.githubusercontent.com/assets/5160083/5990732/47aff7ca-a98e-11e4-9e35-7854b8d68efd.png)

**Comment by tagliala** [comment]
Contents is quite abstract

I would go for http://fontawesome.io/icon/list/ or http://fontawesome.io/icon/align-left/

**Comment by shemani** [comment]
I did think about those, but the list is already being used and will create confusion and the align-left will be used later at some point. Both these will create conflict. icon attached does illustrate table of contents more effectively.

**Comment by sensibleworld** [comment]
We have these icons now, which may work:

https://fontawesome.com/icons/bars-staggered?s=solid&f=classic
https://fontawesome.com/icons/list-tree?s=solid&f=classic
