### ISSUE TITLE
Icon modification : compass

### ISSUE THREAD

**Issue by badulesia** [FortAwesome/Font-Awesome#5551]
Hello.
I would like to suggest a modification of the compass icon. Keep the actual global design of the icon but :
- shrink the thickness of the outer circle. Take the circle of the copyright icon as example.
- increase the size of the inner needle.

I think the whole icon would be more obvious. Thank you.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/compass?s=solid
