### ISSUE TITLE
Icon Request: Separate icon for male and female users

### ISSUE THREAD

**Issue by muditmalpani** [FortAwesome/Font-Awesome#5558]
The icon for user(fa-user) is very useful, but it would be good to have separate icons for male and female users.

**Comment by tagliala** [comment]
Probably 5.0.0 will give user icons some love. Added to 5.0.0 milestone so Dave will eventually take a look at this one

**Comment by glundgren** [comment]
+1 to more user icon options and associated icons, like a user with a tick in the bottom right (representing user checked or confirmed)

**Comment by buzzcloudau** [comment]
+1 for user-check, also users-check, users-plus and users-times would be pretty useful.

**Comment by AndreLGava** [comment]
There is the fa-male and fa-female that you can use as a icon user for defined sex

**Comment by hpvd** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by nunomazer** [comment]
+1

**Comment by tagliala** [comment]
Just noticed that this is a duplicate of the older and #2537, please use that one
