### ISSUE TITLE
woff2?v=4.3.0 Failed to load resource

### ISSUE THREAD

**Issue by stefanahman** [FortAwesome/Font-Awesome#5559]
Getting this error when loading application homepage. Using `rails-assets-fontawesome-4.3.0`:
http://localhost:3000/fonts/fontawesome/fonts/fontawesome-webfont.woff2?v=4.3.0 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by tagliala** [comment]
Hi, that gem is not related to fontawesome

Maybe they forgot to include the new .woff2 file

Closing here

**Comment by stefanahman** [comment]
@tagliala Ok thanks! Do you know where I should post?

**Comment by tagliala** [comment]
what is the exact name of the gem?

**Comment by stefanahman** [comment]
This is a part of my `Gemfile`:
``` ruby
source 'https://rails-assets.org' do
  ...
  gem 'rails-assets-fontawesome'
  ...
end
```

**Comment by stefanahman** [comment]
This could be a duplicate of #5532

**Comment by tagliala** [comment]
@stefanahman ok got it.

Sorry but I don't know how to help. Let's talk in #5532 

I still don't know this "rails-assets-*" stuff. I should check bootstrap to understand what they do to deal with this case but I really have no time in these days

**Comment by tagCincy** [comment]
PR #5655 should correct this.  woff2 declaration was left off component.json.

**Comment by gamegenius86** [comment]
@tagliala I was running into the exact same issue where the `rails-assets` basically the `woff2` file wasn't being pulled in.  After looking at how Rails Assets worked and how your source code is setup, it appears that you are missing the include of the woff2 file in the `component.json` file when you updated it to 4.3.0, which happens to be where Rails Assets to pulling this from.  My coworker @tagCincy and I forked and updated to verify this fixed the issue and it does!  Woot!  PR Made :D

**Comment by tagliala** [comment]
@gamegenius86 thanks. So we need a 4.3.1 version

**Comment by tagliala** [comment]
Closed via #5657

**Comment by YovavGad** [comment]
Had the same issue. this is how I solved it:
Make sure the woff2 MIME type is being recognized by the web server... dahhh...
In my case - updating Web.config

  <system.webServer>
    <staticContent>
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
    </staticContent>
</system.webServer>

**Comment by lepipele** [comment]
@YovavGad answer did it for me... here is text version of what he posted for those who'd like to copy-paste:

      <staticContent>
        <remove fileExtension=".woff" />
        <remove fileExtension=".woff2" />
        <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
        <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
      </staticContent>

**Comment by erikmartinessanches** [comment]
@YovavGad answer solved this for me.

**Comment by Kurama-X** [comment]
Thanks @YovavGad Was able to get rid of this error with your answer

**Comment by elsep2003** [comment]
@YovavGad, That solution was perfect.  Thank you.

**Comment by bertrandjc** [comment]
Thank you, @YovavGad.  Its now fixed.

**Comment by santosh-k1** [comment]
Yes Thanks @YovavGad it working

**Comment by gptA** [comment]
@YovavGad 在哪加那段代码了，我用的是tomcat服务器

**Comment by shikhapathak** [comment]
where is web.config locate in yii2
