### ISSUE TITLE
Icon Request: fa-couple

### ISSUE THREAD

**Issue by shammai** [FortAwesome/Font-Awesome#5560]
Thanks for the great icons.
I would really like to have an icon that symbolizes a couple (i.e. husband and wife).
It would look like the person icon, but instead of 1 person it would have 2.  
It would be similar to the fa-users icon but instead of 3 people it would be 2.  I think having them overlap a little will indicate that they are one icon.
A male/female couple would be ideal.

Thanks so much for considering this addition.

**Comment by laviku** [comment]
+1 
I was thinking something like this
https://cdn4.iconfinder.com/data/icons/eldorado-navigation/40/couple_2-128.png

**Comment by tagliala** [comment]
oddly similar to #2670, it's almost a duplicate :grin: 

There are also: #3025

**Comment by laviku** [comment]
hmm you're right, the wedding rings would be good as well.

**Comment by shammai** [comment]
I was thinking about something more along the lines of:
http://www.anchorgreenpri.moe.edu.sg/qql/slot/u530/quicklinks/parent_icon.png
Obviously in just one solid color.  But the idea is a mother and father
together.

**Comment by oddityoverseer13** [comment]
+1

**Comment by lyhil** [comment]
+1

**Comment by caduvieira** [comment]
Other examples:
http://unicode-table.com/en/#1F46B
http://unicode-table.com/en/#1F46C
http://unicode-table.com/en/#1F46D

**Comment by dkniffin** [comment]
Yes @caduvieira! we should have all three of these icons added.

**Comment by mewcrazy** [comment]
+1

**Comment by tagliala** [comment]
Closing here as a duplicate of #4825

**Comment by aRBemo58** [comment]
disappointed there have been request for three years and still no toilet! trying to use unicode U+1F6BD

**Comment by asarican** [comment]
Hi,
Define new icon with css like this:
.fa-couple:before {
	content: "\f183\f182";
}
it prints male&female next to each other. You can name your icon name anything you want or modify existing which you didn't use.
