### ISSUE TITLE
Icon Request: fa-muffin or fa-cupcake

### ISSUE THREAD

**Issue by rabraganca** [FortAwesome/Font-Awesome#5561]
Thanks for all the icons! They are really wonderful. I need a icon that looks like a muffin.

Something like the image:
![cupcake-icon](https://cloud.githubusercontent.com/assets/8811450/6002403/1e0b0bc4-aada-11e4-8825-00c122a2390f.png)

Thanks so much for considering this addition.

**Comment by EinSteein** [comment]
+1

**Comment by peiche** [comment]
+1

**Comment by jarrodfreeman** [comment]
+1

**Comment by Choco31415** [comment]
+1

**Comment by tzeller** [comment]
i have created a dessert icon which can be used
[fa-dessert.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364632/fa-dessert.pdf)

**Comment by rabraganca** [comment]
Thank you so much!  =)

**Comment by GhitaB** [comment]
+1

So sad, it' 2021 and we still don't have the muffin. :)

**Comment by sensibleworld** [comment]
We have a cupcake icon now. Does this satisfy this request? Or is a more specific "muffin" icon also needed?

https://fontawesome.com/v6.0/icons/cupcake?s=solid

**Comment by GhitaB** [comment]
Ok for me, thank you! :)

**Comment by rabraganca** [comment]
ownt... so cute!
Thank you so much... I loved it!

**Comment by sensibleworld** [comment]
Sorry it took half a decade! 😅
