### ISSUE TITLE
Icon request: icon-lung

### ISSUE THREAD

**Issue by bikeforbreath** [FortAwesome/Font-Awesome#5562]
Hey there - I am new to FontAwesome, but it is certainly living up to it's name. I am involved with events at the New Brunswick Lung Association, and it would be great to have a lung icon for use on our pages. There are already other medical icons, especially for heart, but nothing for lungs! I would appreciate any help in a new design...after all,

"When you can't breathe, nothing else matters."

![lungs](https://cloud.githubusercontent.com/assets/10812617/6002700/01a6af0a-aacc-11e4-9195-dd5038cb8bb1.jpg)
![lungs-128](https://cloud.githubusercontent.com/assets/10812617/6002701/01abbb94-aacc-11e4-9d81-083c6f8b1f3d.png)

**Comment by G-Driver** [comment]
+1

**Comment by sgryphon** [comment]
+1

**Comment by mustmodify** [comment]
another example: http://www.flaticon.com/free-icon/lungs_119086

**Comment by kimberley-johnston** [comment]
+1
