### ISSUE TITLE
Icon Request: icon-lighthouse

### ISSUE THREAD

**Issue by Mitemd** [FortAwesome/Font-Awesome#5579]
Hey guys,

I'm living on the coast where many lighthouses stands. Now I have a website which represent a local shop, so a lighthouse stands for mentality. I also believe that a lighthouse stands for many other things like guiding someone.

I would appreciate if you could implement such an icon :+1:

You rock! :)

**Comment by Mitemd** [comment]
Something like that, made it quick and dirty ;)

![lighthouse](https://cloud.githubusercontent.com/assets/10838282/6052017/fd5bf370-accd-11e4-8a7a-99e9ce9fd83d.png)

**Comment by wolffe** [comment]
+1

**Comment by thebeeber** [comment]
+1

**Comment by bubbsUK** [comment]
Any movement on this?
I do not see fa-lighthouse in the icon. am i missing something?

many thanks in advance!

**Comment by pjsmits** [comment]
+1

**Comment by jerome-benoit-jayb** [comment]
+1

**Comment by darkenedsky** [comment]
I need this badly. +1.

**Comment by wvandenborne608** [comment]
+1

**Comment by pjsmits** [comment]
![icon-lighthouse](https://user-images.githubusercontent.com/25504359/50270355-93238d00-0431-11e9-9786-97a43c82e16d.png)
or like this ;)

**Comment by leovogel** [comment]
I'd love to see this released as a duotone icon.

**Comment by artifex-media** [comment]
+1

**Comment by oscarvoigt** [comment]
I have a few more mockups for consideration. 

![Watchman-Monitoring-logomark-1-color-square](https://user-images.githubusercontent.com/66705837/89699161-c6f34500-d8ea-11ea-9b2e-9911d4bf8678.png)
![Watchman-Monitoring-logomark-1-color-dark-circle](https://user-images.githubusercontent.com/66705837/89699162-c78bdb80-d8ea-11ea-8b38-bf7b96348172.png)
![Watchman-Monitoring-logomark-1-color-dark-square](https://user-images.githubusercontent.com/66705837/89699164-c78bdb80-d8ea-11ea-9a0e-3b4fe5e74d81.png)


 to be considered.

**Comment by velocitysystems** [comment]
+1

**Comment by oscarvoigt** [comment]
Hello. We at Watchman Monitoring have sponsored a light house. Please note this is our logo but does provide a good looking lighthouse. https://fontawesome.com/icons/watchman-monitoring

**Comment by sensibleworld** [comment]
This has been added: https://fontawesome.com/icons/lighthouse?f=classic&s=solid
