### ISSUE TITLE
Icon Request: fa-bitshares

### ISSUE THREAD

**Issue by sidhujag** [FortAwesome/Font-Awesome#5580]
Bitshares.org... Similar to viacoin which you have already added in 4.3... Bigger userbase.

See faucet.bitshares.org for the svg graphic for bitshares logo.

http://faucet.bitshares.org/users/sign_in

I have integrated bitshares payment gateway to many shopping cart packages which use fontawesome

See my github: github.com/sidhujag

**Comment by jcalfee** [comment]
![](https://avatars3.githubusercontent.com/u/6914094?v=3&s=200)
