### ISSUE TITLE
Icon Request: user-with-headset

### ISSUE THREAD

**Issue by jgornick** [FortAwesome/Font-Awesome#5586]
Similar to custom user icons (user-md), it would be nice to have an icon that combines a [user](http://fortawesome.github.io/Font-Awesome/icon/user/) and a headset. This could represent one of the following aliases:
- customer-service
- customer-support
- call-center-agent

Example:

[The Noun Project: Customer-Service by Agarunov Oktay-Abraham](http://thenounproject.com/term/customer-service/36358)

![noun_36358_cc](https://cloud.githubusercontent.com/assets/8788/6046451/e8984d6e-ac67-11e4-9c92-2267b9188427.png)

**Comment by jgornick** [comment]
Meh, nevermind, duplicated at #1146

**Comment by jgornick** [comment]
Closed originally as a duplicate, but this is applying a headset to a user.

**Comment by tagliala** [comment]
so renaming to user-with-headset

**Comment by jgornick** [comment]
@tagliala I like the new name. Thanks!

**Comment by LauritzT** [comment]
+1

**Comment by thisispiers** [comment]
+1

**Comment by julionc** [comment]
+1

**Comment by scgm11** [comment]
+1

**Comment by saguiitay** [comment]
+1

**Comment by julionc** [comment]
cc @davegandy

**Comment by dngunraj** [comment]
+1

**Comment by caih** [comment]
+1

**Comment by caih** [comment]
I think it's a dup: https://github.com/FortAwesome/Font-Awesome/issues/1146

**Comment by tagliala** [comment]
@caih this one is an user with a headset, the other one could be only a headset. I'm keeping both opened

**Comment by PiaV** [comment]
+1

**Comment by hectorpalmatellez** [comment]
+1

**Comment by arrayown** [comment]
Hell, +1 since it seems to be a fad around here! :dancer:

**Comment by zhekaus** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by bgodkin** [comment]
+1

**Comment by wedocodeuk** [comment]
+1

**Comment by ali4533** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by Stormcloud** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by TerraPrime** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by davidetwc** [comment]
+1

**Comment by shmaster** [comment]
+1

**Comment by meister-d** [comment]
+1

**Comment by tbaragao** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by Emalton** [comment]
+1

**Comment by zeNtaKKK** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by BorzdeG** [comment]
+1

**Comment by pineladsn** [comment]
+1

**Comment by daniyalahmadk** [comment]
+1

**Comment by dakt** [comment]
+1

**Comment by ronskyi** [comment]
+1

**Comment by louman** [comment]
+1

**Comment by hingram** [comment]
+1

**Comment by ACvijic** [comment]
+1

**Comment by mahdi4187** [comment]
+1

**Comment by bramax** [comment]
+1

**Comment by torkelrogstad** [comment]
+1

**Comment by DaGLiMiOuX** [comment]
+1

**Comment by gangesh** [comment]
+1

**Comment by robabel** [comment]
+1

**Comment by webtaculars** [comment]
+1

**Comment by omeraplak** [comment]
+1

**Comment by jefferson-silva** [comment]
+1

**Comment by chippison** [comment]
+1

**Comment by NeogDesigner** [comment]
+1

**Comment by SkyNetRU** [comment]
+1

**Comment by jefferson-silva** [comment]
How many **years** and "+1"s until this icon gets added to the library?

**Comment by mmuff93** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by sensibleworld** [comment]
We've added this icon to our latest Font Awesome Pro release: https://fontawesome.com/icons/user-headset?style=solid
