### ISSUE TITLE
Sync Icon

### ISSUE THREAD

**Issue by jrm1987** [FortAwesome/Font-Awesome#5588]
Need an icon for *synchronization*. We have a refresh, but I presume Sync icon looks different. Also, one might need an icon for denoting a *transfer*, usually denoted as half a right pointing arrow on top and half a left pointing arrow under it.

**Comment by tagliala** [comment]
Sync looks exactly like refresh in android:

I'm going to close this one. I will consider reopening with a proper example and title

http://cdn.redmondpie.com/wp-content/uploads/2012/04/TogglePanel-splash.png
http://fontawesome.io/icon/refresh/

**Comment by acshef** [comment]
@jrm1987 might I suggest using `fa-repeat` http://fontawesome.io/icon/repeat/ as a possibility for refresh (looks exactly like Chrome's, Internet Explorer's, and Firefox's "refresh" buttons) that way you can use `fa-refresh` as your synchronize icon?

**Comment by jrm1987** [comment]
Actually I have already used refresh as the sync icon even before posting
my suggestion on github. I thought that since Font Awesome has most popular
icons, there should be one denoting "give and take" or "transfer" which can
also be used for sync.

Example: google.com/#q=transfer+icon

**Comment by tagliala** [comment]
http://fontawesome.io/icon/exchange/

**Comment by jrm1987** [comment]
Oops ): Sorry. I did try looking for it though. I looked in the arrows,
searched for "transfer", etc. But missed the word "exchange". Thank you.

**Comment by tagliala** [comment]
@jrm1987 don't worry. I will add a filter for that icon (transfer, round trip). Don't know whi it is not listed in directions, I will also add exchange to that category
