### ISSUE TITLE
Font-awesome icons don't work at all

### ISSUE THREAD

**Issue by nZeus** [FortAwesome/Font-Awesome#5591]
I have a user on my site. He doesn't see any icons.
![Screen](http://i57.tinypic.com/25ksp4k.jpg)

Sorry for the quality, that's all what I have.

**Comment by tagliala** [comment]
Your browser is not loading webfonts. Don't know if it is an extension like noscript or adblick or is an admin restriction on your IE installation.

Please take a look at how "40 New Icons" look like:
![image](https://cloud.githubusercontent.com/assets/556268/6061180/ba4bbce6-ad45-11e4-8c7f-644080333c5a.png)

Closing here but feel free to comment
