### ISSUE TITLE
Icon request: icon-blood

### ISSUE THREAD

**Issue by ildragocom** [FortAwesome/Font-Awesome#5596]
A blood drop to visualize medical information about blood type.

![Image of a blood drop](http://fc08.deviantart.net/fs71/i/2010/179/d/5/Black_Moon_by_redman45.jpg)

If is it possibile to create an empty version, it could become a drop for different use
(eg. icon-drop-o)
Thanks

**Comment by tagliala** [comment]
http://fontawesome.io/icon/tint/

If you want to request an outlined version, please rename to tint-o

**Comment by ildragocom** [comment]
Damn! I was looking but didn't see it... please don't consider my request

**Comment by tagliala** [comment]
:+1: closing here, hope it helped
