### ISSUE TITLE
Icon request: Home automation set

### ISSUE THREAD

**Issue by gbourgneuf** [FortAwesome/Font-Awesome#5597]
Hi,

I'm looking for an icon-font including some icons related to home automation (like you can see on this animation: https://dribbble.com/shots/1704031-Home-Guard-02?list=users&offset=5).
So, it would be great if you add some icons related to : outlets, lights, doors, windows, alarm, ....

Thank you

**Comment by dima117** [comment]
+1

**Comment by tagliala** [comment]
Sorry but I have to close this request, as per our new contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution and please take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
