### ISSUE TITLE
New icon request: icon-gps (geolocation symbol)

### ISSUE THREAD

**Issue by smsgrafica** [FortAwesome/Font-Awesome#560]
I'd love to have a geolocation symbol.

Thank you very much for your great work!

**Comment by tomchambers2** [comment]
+1

**Comment by DavidSpriggs** [comment]
+1 Needs to look like the lower right icon in google maps app (ios):
![image](https://cloud.githubusercontent.com/assets/661156/6020044/ffa8be9a-abb7-11e4-948d-a5feddebeeec.png)
See here for more examples:
http://www.google.com/mobile/maps/

**Comment by ganarajpr** [comment]
:+1:

**Comment by CinimoDY** [comment]
+1 up :+1:

**Comment by ianpottier** [comment]
+1 up :+1:

**Comment by ashleypdx** [comment]
+1

**Comment by TheSisb** [comment]
+2

**Comment by bkingg** [comment]
+1 up

**Comment by srgstm** [comment]
+1. So many useless extremely specialized icons but essential one is missing.

**Comment by amnesia7** [comment]
+1 Any sign of this icon being added any time soon?

**Comment by moiAK** [comment]
+1

**Comment by slead** [comment]
+1 yes please

**Comment by graphnode** [comment]
:+1:

**Comment by raykendo** [comment]
+1 Yes please

**Comment by caycek** [comment]
+1

**Comment by btfou** [comment]
+1

**Comment by jkoudys** [comment]
+1

**Comment by zallek** [comment]
+1

**Comment by cedrikv** [comment]
+1

**Comment by vladdancer** [comment]
+1

**Comment by siebertm** [comment]
+1

**Comment by jkoudys** [comment]
If anyone's looking for a similar icon to use as a substitute, the crosshairs come pretty close. It's not exact, but at 12px in the corner of a map, it does a serviceable job.

http://fontawesome.io/icon/crosshairs/

**Comment by onokazu** [comment]
Pretty disappointed this did not make into version 4.4.0. This icon is definitely needed for any mobile application nowadays.

**Comment by Rajprabhu14** [comment]
+1  :+1:

**Comment by almone** [comment]
+1 :point_up:

**Comment by Tomicapo** [comment]
+1 Any news on this?

**Comment by webdevninja** [comment]
+1

**Comment by webdevninja** [comment]
+1

**Comment by RShackleton** [comment]
+1

**Comment by goyote** [comment]
Why is a stupid icon like fa-hand-spock-o implemented, but not this one? :)

**Comment by stekhn** [comment]
+1

**Comment by hamxabaig** [comment]
+1 please.

**Comment by jawade** [comment]
+1

**Comment by dgandini** [comment]
A lot of closed requests and the icon still hasn't been implemented yet. I really can't understand. This icon is very useful to geolocation and mobile apps.

**Comment by dgandini** [comment]
+1

**Comment by caycek** [comment]
I'm thinking they are avoiding it because most maps have a marker that is based on their own structures.


Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by johndubya** [comment]
@caycek, it would be nice if they would at least confirm that, if that truly is the case. Otherwise, it seems the desire for this icon is pretty strong.

**Comment by caycek** [comment]
Tbh I just looked back at when I first +1 this and it has been 9 months of watching random emails. I'm fairly surprised there has been no mention that I'm aware of since. I don't know if there is someone who can make a statement at this point either.


Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by netgis** [comment]
+1

**Comment by FriendlyWP** [comment]
+1

**Comment by sepehr1014** [comment]
+1

**Comment by s4msung** [comment]
+1

**Comment by JumpLink** [comment]
+1

**Comment by thegreatrazz** [comment]
+1

**Comment by ch4rlie** [comment]
+1

**Comment by Mnemik** [comment]
+1

**Comment by wouter2203** [comment]
+1

**Comment by mdmullinax** [comment]
+1

**Comment by wouter2203** [comment]
+1

**Comment by FriendlyWP** [comment]
+1

**Comment by pratham2003** [comment]
http://fontawesome.io/icon/crosshairs/

or maybe stack it with 
http://fontawesome.io/icon/circle/

**Comment by wouter2203** [comment]
@pratham2003 That is not really the icon we're looking for, the lines of the crosshair shouldn't be inside the circle.

It also isn't that easy to stack those two icons to make them pixel perfect, you would need custom css for the font sizes..

I still prefer a real extra icon like:
![image](https://cloud.githubusercontent.com/assets/8761962/20485083/50c68d1e-affa-11e6-893d-69f7504b82dd.png)

**Comment by pratham2003** [comment]
Yup, +1 for that

**Comment by richimax** [comment]
+1

**Comment by vaishaks** [comment]
+1

**Comment by vaishaks** [comment]
+1

**Comment by hedyharto** [comment]
+1

**Comment by victory7** [comment]
+1

**Comment by aalbagarcia** [comment]
+1

**Comment by joshualibrarian** [comment]
I want this icon too!

**Comment by lubojr** [comment]
I would love this icon!

**Comment by samupl** [comment]
Quite a while since this issue was opened. It would come in very handy.

**Comment by cccruzr** [comment]
+1   Seems like a lot of people like me needs this icon, guys!

**Comment by pepitogithub** [comment]
+1

**Comment by aragonwa** [comment]
+1

**Comment by K-Lovelace** [comment]
+1

**Comment by byronigoe** [comment]
+1

**Comment by mspanadgoo** [comment]
+1

**Comment by JavierM42** [comment]
+1

**Comment by alaindm** [comment]
+1

**Comment by JuanMa06** [comment]
+1

**Comment by haydenhuang** [comment]
+1

**Comment by dedo1911** [comment]
+1

**Comment by cailenmusselman** [comment]
+1

**Comment by nanangarsyad** [comment]
+1

**Comment by skydevelopers** [comment]
+1

**Comment by drkohlipk** [comment]
+1

**Comment by psyke089** [comment]
+1

**Comment by rjbathgate** [comment]
+1 would be awesome

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/location?style=solid
