### ISSUE TITLE
Icon Request: fa-tripadvisor

### ISSUE THREAD

**Issue by tsanren89** [FortAwesome/Font-Awesome#5601]
Hi Font-Awesome,

I really love this awesome icons.

Would like to request tripadvisor icon.

You got Facebook, Google Plus, Twitter, etc... but no TripAdvisor :(

If you can make it, user going to love it.

Thank you.

**Comment by tagliala** [comment]
duplicate of #412 , please +1 that request and you can also sign this petition: https://www.change.org/p/font-awesome-please-add-the-tripadvisor-icon-to-your-font

Closing here
