### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by Trackhe** [FortAwesome/Font-Awesome#5608]
![js](https://cloud.githubusercontent.com/assets/1494328/6088011/6c7e42c8-ae52-11e4-8cb4-284aee5cd062.png)
This is the perfect complement to html5 and css3

**Comment by tagliala** [comment]
duplicate of #1711 , please +1 that request

closing here

**Comment by Trackhe** [comment]
but this is not an exact desired icon.

**Comment by tagliala** [comment]
post your example there, but afaik there is no official javascript logo

**Comment by Trackhe** [comment]
wikipedia.org/wiki/JavaScript almost official

**Comment by tagliala** [comment]
it's the same logo in the first post of #1711

**Comment by Trackhe** [comment]
yes that nice :D

**Comment by tagliala** [comment]
@Trackhe take a look at this fontawesome extension: http://fizzed.com/oss/font-mfizz

**Comment by Trackhe** [comment]
http://de.wikipedia.org/wiki/JavaScript
