### ISSUE TITLE
Icon request: icon-shopify

### ISSUE THREAD

**Issue by garethallen** [FortAwesome/Font-Awesome#5618]
Brand Icon for Shopify. Thought there would be one already.
Have attached a tower banner with black/white logo in it.
Will be used as a brand icon on websites.
Thanks in advance.
![160x600-dark](https://cloud.githubusercontent.com/assets/10911058/6097566/ad196c68-afba-11e4-9282-a4be5bab7b0f.jpg)

**Comment by tagliala** [comment]
dup of #3850 , please +1 that request

closing here
