### ISSUE TITLE
Support GAS and ATM icon

### ISSUE THREAD

**Issue by pvtai** [FortAwesome/Font-Awesome#5619]
I found on cheatsheet but I don't see icon for ATM(ATM bios) and GAS(OIL).
It mean 
![map_marker_icon_ _nicolas_mollet_ _atm_ _offices_ _white](https://cloud.githubusercontent.com/assets/4888072/6097815/3ace0cfc-affd-11e4-9035-fcfbdb161f7e.png)

Please help me define some icon above.
Thanks

**Comment by tagliala** [comment]
please +1 #1676  and #5103

closing here

**Comment by pvtai** [comment]
Yes, thanks
