### ISSUE TITLE
Icon request: icon-500px

### ISSUE THREAD

**Issue by teroa** [FortAwesome/Font-Awesome#5620]
Hi,
there is a growing community for photos: 500px
It would be nice to reffer to this site via a font-awsome icon.

![Logo 500px](http://ww1.prweb.com/prfiles/2012/04/19/9421977/gI_122365_500px_logo_250.png)

**Comment by matheusagcosta** [comment]
:100:

**Comment by tagliala** [comment]
duplicate of #599 , please +1 that request

closing here
