### ISSUE TITLE
Icon request: fa-toothbrush

### ISSUE THREAD

**Issue by James1x0** [FortAwesome/Font-Awesome#5623]
It would be nice to have a tooth & toothbrush icon to refer to dentistry & dental applications. Healthcare icons are great, but these would be a good addition.

---

![toothbrush-512](https://cloud.githubusercontent.com/assets/6146261/6111926/cb70a296-b049-11e4-85f2-4aafd4eabf34.png)

**Comment by tagliala** [comment]
tooth is  a duplicate of #1289 , please +1 that request

leaving this open as tootbrush

**Comment by James1x0** [comment]
@tagliala Will do, thanks.

**Comment by G-Driver** [comment]
+1

**Comment by dvorapa** [comment]
+1

**Comment by jamiegiles** [comment]
+1

**Comment by cgarveyie** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/toothbrush?style=solid
