### ISSUE TITLE
How to color icons

### ISSUE THREAD

**Issue by VinayKumarSarda** [FortAwesome/Font-Awesome#5627]
Hi,
I want to fill color for icons say fa-smile-o, i have implemented using stacked icons (by adding fa-circle) concept but it works only for round shape icons .I have my icons dynamic so there can be any combination of icons.  How to fix it for all type of icons irrespective of shape of icon.

**Comment by tagliala** [comment]
Hi, you can't do  this, but there is a hack for this case: https://github.com/FortAwesome/Font-Awesome/issues/5284#issuecomment-68070417

closing here

**Comment by tagliala** [comment]
feel free to comment if you need more tips

**Comment by VinayKumarSarda** [comment]
Hi, Thanks for the reply. 
In the above link there you need to hard code the color in CSS, but my color is also dynamic and will be different for different icons.

**Comment by tagliala** [comment]
hi,

Dinyamic coloring fontawesome is like dynamic coloring any other text you have in your database.

I'm thinking about a couple of approaches. I will use a simpler example and slim templates

1. Obtrusive style (don't like this one)

```slim
span.fa class=icon style="color: #{icon.color}"
```

2. Predefined classes (so you can't have the whole range of colors but you need mapping, e.g: `.color-emerald { color: #2ecc71; }`

```slim
span.fa class=[icon, icon.color_class].join(' ')
```
