### ISSUE TITLE
Icon request - Icon parking

### ISSUE THREAD

**Issue by karmen1087** [FortAwesome/Font-Awesome#5648]
Hello,
I would like to use a parking icon.
I am working in a wp template that use this font and I would like to use this icon in the description of the parking.
![parking](https://cloud.githubusercontent.com/assets/10958731/6147034/749fc284-b1f3-11e4-8a5d-037d18ce97c2.png)

How frecuently do you update the font?
Thanks!! :)

**Comment by nikkiroylance** [comment]
+1

**Comment by Alticaro** [comment]
+1
I made the same request here https://github.com/FortAwesome/Font-Awesome/issues/5647 ;)

**Comment by tagliala** [comment]
duplicate of #1559 , please +1 that request

closing here
