### ISSUE TITLE
Icon requests: icon-text

### ISSUE THREAD

**Issue by HansRue** [FortAwesome/Font-Awesome#565]
Hello,

first I'd like to thank everybody involved for this great icon collection.

Two icon suggestions:

<ul>
    <li>inverted <b>round @ icon</b>?
    <li>A <b>"T" icon</b> as in the style of the "icon-font" icon.<br> Similar to the "icon-text-height" icon only without the arrows.
</ul>

Would be great to have them both.

Greetings!

**Comment by eduardo-matos** [comment]
+1 for *@* icon.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/text?style=solid
