### ISSUE TITLE
Yelp icon no longer working

### ISSUE THREAD

**Issue by onetoncreative** [FortAwesome/Font-Awesome#5650]
I installed font awesome into my site (http://192.185.145.70/~jakescar/) back in Nov/Dec of 2014 and the Yelp icon was working fine. As of this month it is no longer working. The icon is located in the footer next to the other social icons as well as on the review's page next to the google+ icon. I have tried re-installing the font with no luck. Please help!

**Comment by LauritzT** [comment]
Works fine here in Firefox 37.0a2 (2015-02-11) on Windows.
What browser are you using, and do you have any ad-blockers installed?
![Screenshot](https://cloud.githubusercontent.com/assets/6600597/6161266/addbc1da-b26e-11e4-8d50-debdafccce0b.png)

**Comment by tagliala** [comment]
Can't confirm, closing here.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
