### ISSUE TITLE
Icon-request:icon-roadworks (fa-under-construction)

### ISSUE THREAD

**Issue by nikkimassie** [FortAwesome/Font-Awesome#5653]
![download](https://cloud.githubusercontent.com/assets/10463362/6169052/aa784708-b2c2-11e4-8b9d-63a0213b69c8.png)

**Comment by LauritzT** [comment]
+1
Maybe fa-roadworks and fa-roadworks-triangle?

**Comment by bertoost** [comment]
+1
fa-under-construction :+1:

**Comment by rogergros** [comment]
+1
:smiley:

**Comment by DriesVandermeulen** [comment]
+1

**Comment by maryargarine** [comment]
+1

**Comment by stefaneg** [comment]
+1

**Comment by cardimajs** [comment]
+1

**Comment by zuhloobie** [comment]
+1

**Comment by vparecsb** [comment]
+1

**Comment by ruanmartinelli** [comment]
+1

**Comment by jbonnier** [comment]
+1

**Comment by matgargano** [comment]
+1

**Comment by mballinas** [comment]
+1

**Comment by mbaas2** [comment]
+1

**Comment by gpini** [comment]
+1

**Comment by jmccannster** [comment]
+1

**Comment by GavinPalmer1984** [comment]
circle version is nice too:
https://commons.wikimedia.org/wiki/File:Commons-emblem-Under_construction-green.svg

**Comment by leotm** [comment]
+1

**Comment by andyanderso** [comment]
+1

**Comment by moshfeu** [comment]
+1

**Comment by TurboTim** [comment]
+1

**Comment by guzinski** [comment]
+1

**Comment by joaocmfcm** [comment]
+1 We need this one 💪

**Comment by kisdaniel** [comment]
Triangle should be separated like this:

```
<span class="fa-stack fa-lg">
  <i class="fa fa-roadworks fa-stack-1x"></i>
  <i class="fa fa-triangle fa-stack-2x text-danger"></i>
</span>
```

**Comment by maherAshori** [comment]
+1

**Comment by danield-hyprbrands** [comment]
+1

**Comment by anhquande** [comment]
+1

**Comment by fmorriso** [comment]
+1

**Comment by otienoanyango** [comment]
+1

**Comment by agilma** [comment]
+1

**Comment by BiancaAlves** [comment]
+1

**Comment by stefan505** [comment]
+1

**Comment by MisterProg** [comment]
+1

**Comment by fmorriso** [comment]
It has been over three years since this issue was first opened and still no icon. 

Folks, the plain, simple truth is that if it has not happened by now, it will probably NEVER happen.

**Comment by melksedeque** [comment]
+1

**Comment by TristanBunyan** [comment]
+1

**Comment by BristolITDave** [comment]
Just bought FontAwesomePro today. Can't believe this isn't an icon yet! There is nothing relating to maintenance!

**Comment by rodolfodsousa** [comment]
+1

**Comment by jlabeit** [comment]
+1

**Comment by fmorriso** [comment]
Update to my comment of Feb 18, 2018 : it's now over four years since the original request was made and still no under construction icon, so I reiterate what I said a year ago: it will never happen.

**Comment by DiemenDesign** [comment]
I have seen a lot of these requests over the years that would make great additions not being added or simply ignored. Granted they can't add everything, and some design elements would be difficult to do or lose meaning due to size, but still, a lot could be added. And that is why I created my own library of Icons, all SVG and ARIA compliant and minified. I'm not going to link the repository here, as I don't want to take away the good work that Dave Gandy and his team have done, and continue to do, just pointing out that it's an option for others to do the same as it's not that hard to do.

**Comment by tagliala** [comment]
@DiemenDesign thanks for your kind words and feel free to share your repository here if it contains this icon and could help others

**Comment by DiemenDesign** [comment]
All good, I'm sure people are resourceful enough to find the repo on their own, lol.

**Comment by rodolfodsousa** [comment]
It'a nor possible others continue their work, since they may not be interested any more?

**Comment by sensibleworld** [comment]
Hey folks! We've added a couple of options for this in Font Awesome Pro:

- https://fontawesome.com/icons/construction?style=solid
- https://fontawesome.com/icons/digging?style=solid

**Comment by BristolITDave** [comment]
> Hey folks! We've added a couple of options for this in Font Awesome Pro:
> 
> * https://fontawesome.com/icons/construction?style=solid
> * https://fontawesome.com/icons/digging?style=solid

Hurray! Thank you so much :)

**Comment by manuelph** [comment]
+1
