### ISSUE TITLE
Icon Request: fa-airplane-seat

### ISSUE THREAD

**Issue by thealex87** [FortAwesome/Font-Awesome#5658]
![fa-seat](https://cloud.githubusercontent.com/assets/10980271/6173483/961827e4-b2cf-11e4-834b-67cb47315b71.png)

**Comment by tagliala** [comment]
I probably should consider this a duplicate of #2903

**Comment by thealex87** [comment]
Ok. Thanks!

**Comment by tagliala** [comment]
@thealex87 maybe the use case is different... is this related to transportation?

**Comment by thealex87** [comment]
@tagliala yes. Marking airplane seats.

**Comment by dpfem** [comment]
+1 showing a seatbelt would also be good

**Comment by leonardo1024** [comment]
+ I need also

**Comment by laurensnl** [comment]
Another example:

![icons8-flight-seat-100](https://user-images.githubusercontent.com/4354382/72681467-3c6d0480-3ac4-11ea-8f65-efe0f035dfe1.png)

Preferably without the window. I would also opt for an alternative icon that shows the seat from the front.

**Comment by sensibleworld** [comment]
We've added these to version 6. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=seat&s=solid

<img width="535" alt="Screen Shot 2021-05-27 at 2 05 58 PM" src="https://user-images.githubusercontent.com/529604/119875359-ab4a4100-bef4-11eb-93ca-2621f0518f6a.png">

**Comment by SchweizerSchoggi** [comment]
Cool, thank you very much!

Jory Raphael ***@***.***> schrieb am Do., 27. Mai 2021, 20:06:

**Comment by laurensnl** [comment]
Awesome! Thanks! Installing the beta now!

**Comment by thealex87** [comment]
TKS 😁
