### ISSUE TITLE
Icon request: icon-radar-dish

### ISSUE THREAD

**Issue by bbibeault-lifesize** [FortAwesome/Font-Awesome#5659]
I'd like to see a radar dish icon added; please re-open. Specifically along the lines of: http://i.imgur.com/dHKZn8B.png

This would be useful for weather (and other mapping) applications that want to show radar locations and/or use such an icon on buttons and the like.

This is distinct from a 'radar screen' icon as requested in https://github.com/FortAwesome/Font-Awesome/issues/507#issuecomment-74136404

**Comment by bertoost** [comment]
+1

**Comment by ryankane** [comment]
Inline preview of the requested icon. (Scaled image -75%)

![Satellite Dish](http://i.imgur.com/nusRfis.png?1)

**Comment by baalthazaar1** [comment]
+1

**Comment by natanaelrw** [comment]
+1

**Comment by hailthemelody** [comment]
+1

**Comment by dumboxp** [comment]
+1 a radar symbol like "hailthemelody" posted would be very useful. A spinning version would be great too.

**Comment by KurtJacobson** [comment]
+1 It seems like there are quite a few long standing requests for a radar icon. I would love to see an icon added like that posted by @ryankane.

**Comment by nicolasvahidzein** [comment]
+1

**Comment by sensibleworld** [comment]
Thanks for the request! We now have this icon.

https://fontawesome.com/v6.0/icons/satellite-dish?s=solid

<img width="1014" alt="Screen Shot 2021-05-27 at 1 56 02 PM" src="https://user-images.githubusercontent.com/529604/119874110-46dab200-bef3-11eb-87c4-9c20a2e8a7a5.png">
