### ISSUE TITLE
Icon Request: icon-signature

### ISSUE THREAD

**Issue by Louis-Demers** [FortAwesome/Font-Awesome#5663]
Hi,
looking for a symbol that indicates that a signature is required.. like the unicode symbol E2 9C 8D or U+270D
![icon-signature](https://cloud.githubusercontent.com/assets/10984250/6178690/68d32936-b2df-11e4-9cdb-01097d5a1162.png)

**Comment by LauritzT** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by mightymt** [comment]
+1

**Comment by bertoost** [comment]
+1

**Comment by kevinbarone** [comment]
+1 Definitely! LOVE fontawesome!

**Comment by danMontague** [comment]
+1

**Comment by athirah30** [comment]
+1

**Comment by jaketoolson** [comment]
+1 this would be handy.

**Comment by twoowar0** [comment]
+1

**Comment by steveQuadros** [comment]
+1

**Comment by DaleMckeown** [comment]
+1

**Comment by beliys** [comment]
+1

**Comment by andrey-gr** [comment]
+1

**Comment by reyx** [comment]
+1

**Comment by miguelramosfdz** [comment]
+1

**Comment by OlafAndreas** [comment]
+1

**Comment by darrencornwell** [comment]
+1

**Comment by pandamouse** [comment]
+1

**Comment by GrgDmr** [comment]
+1

**Comment by simonhoss** [comment]
+1

**Comment by culov** [comment]
+1

**Comment by abrowne2** [comment]
+1

**Comment by zongap** [comment]
+100

**Comment by mhshakouri** [comment]
+1000

**Comment by waveminded** [comment]
+1

**Comment by FedeOmoto** [comment]
+1

**Comment by charluemm** [comment]
+1

**Comment by yaim** [comment]
+1

**Comment by anhquande** [comment]
+1

**Comment by emerikusz** [comment]
+1

**Comment by tan784147** [comment]
+1

**Comment by danMontague** [comment]
+1

**Comment by simasbu** [comment]
+1

**Comment by trane294** [comment]
+1

**Comment by codeurge** [comment]
+1

**Comment by vlaux** [comment]
+1

**Comment by guillaumesoul** [comment]
+1

**Comment by djechelon** [comment]
+1

**Comment by abhishek-murali** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by gegillam** [comment]
+1

**Comment by kiminya-raphael** [comment]
+1

**Comment by emanuelmaha** [comment]
+ 1 pleasseeeee

**Comment by cetindogu** [comment]
+1

**Comment by anhquande** [comment]
+1

**Comment by JimmyNi** [comment]
+1

**Comment by AlessandroVecchi** [comment]
i would like a file icon with signature: https://github.com/FortAwesome/Font-Awesome/issues/12764

**Comment by gasparez15** [comment]
+1

**Comment by zolt** [comment]
+1

**Comment by mtraut** [comment]
+1

**Comment by hgcode** [comment]
+1

**Comment by allor** [comment]
+1 In such a way we can combine a document + signature = contract

**Comment by jcrisp88** [comment]
+1

**Comment by bjtb** [comment]
+1 We need icons for customer signature and employee signature in our app

**Comment by ansonhoyt** [comment]
Noticed 5.1.0 was released and includes several [signature icons](https://fontawesome.com/icons?d=gallery&q=signature). I'm concerned the squiggle looks too much like the [heartbeat icons](https://fontawesome.com/icons?d=gallery&q=heartbeat), and it could be confused.

I do like the idea of a squiggle. Perhaps change it so the signature doesn't have a line leading in that matches up with the line closing it out. This would keep it from looking like an EKG line. Also, signatures are typically/often cursive and the lead-in is suggestive of the squiggle continuing from another bit of text...but a signature stands alone.

**Comment by emma-tuna** [comment]
I thought the new signature icon looked like a heartbeat too.

**Comment by sensibleworld** [comment]
Thanks for the feedback, @ansonhoyt and @emma-tuna! The style/look of the current one was pulled from the smaller versions in the `file-signature` and `file-contract` icons, but I agree that it could use some tweaking.

**Comment by ChristanM** [comment]
Hi, 
I’m designing a new web application, and I should use a Signature icon. 
But the Icon “signature” and “file-signature” present in the current set may be complex to read with small dimensions.  
For this reason for my project I created a new signature icon:  

![icon_signature-approve](https://user-images.githubusercontent.com/43337797/45619305-1622f900-ba79-11e8-94ec-5e24b7438c82.png)

Could you evaluate if is possible add this icon or similar in the set?

Thank you!

**Comment by shaedrich** [comment]
@ChristanM This might be named "fa-signature-circle".

**Comment by ChristanM** [comment]
@shaedrich yes, right, there's no a signature. 
Could be considered an "Edit" variation?

**Comment by shaedrich** [comment]
I would consider it as  "fa-edit-circle".

**Comment by ChristanM** [comment]
I'm a pro member, it is possible to create also the far- fal- and fas version?

**Comment by sensibleworld** [comment]
@ChristanM You can open a new icon request here: https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md

And you might consider using an icon like this in the meantime: https://fontawesome.com/icons/pen-square?style=solid

**Comment by ChristanM** [comment]
ok, @sensibleworld Thank you!

**Comment by r-man** [comment]
+1

**Comment by sensibleworld** [comment]
Our signature icon looks a bit more like a signature now, and less like a heartbeat: 
https://fontawesome.com/icons/signature?style=solid
