### ISSUE TITLE
Icon Request: fa-jollyroger

### ISSUE THREAD

**Issue by bruceclothier** [FortAwesome/Font-Awesome#5669]
A few uses including icon for blacklisted/toxic accounts on a CRM

![jollyroger](https://cloud.githubusercontent.com/assets/4464317/6186388/44392b64-b381-11e4-856e-299f16d3062a.png)

**Comment by tagliala** [comment]
is this a brand? relates to #918

**Comment by bruceclothier** [comment]
Not a brand just giving a suggestion about what it could look like. Skull and crossbones, jolly roger, whatever you call it. Would be very useful.

**Comment by tagliala** [comment]
thanks for the clarification. Closing this in favor of #918, please +1 that request and post there your example
