### ISSUE TITLE
Icon Request: fa-cube-empty

### ISSUE THREAD

**Issue by rcrisp** [FortAwesome/Font-Awesome#5672]
An icon representing an empty cube, or 3-dimensional box.  Unfortunately the current cube having one side filled in black makes it not make sense for my needed usage.  This would be a great alternative for many different purposes.

![fa-cube](https://cloud.githubusercontent.com/assets/7253818/6194166/9622b572-b38f-11e4-965f-d13edcf91777.jpeg)

**Comment by tagliala** [comment]
duplicate of #2082, please +1 that request

closing here
