### ISSUE TITLE
Icon request: icon-tooltip

### ISSUE THREAD

**Issue by warthogweb** [FortAwesome/Font-Awesome#5675]
![icon-tooltip](https://cloud.githubusercontent.com/assets/11003656/6199055/f82ac742-b433-11e4-81c0-9ea749800552.png)

**Comment by tagliala** [comment]
could you please post an example that would fit 14px icon size?

**Comment by sensibleworld** [comment]
Perhaps this can work: https://fontawesome.com/icons/message-middle-top?s=solid&f=classic
