### ISSUE TITLE
Icon request: internet of things icons

### ISSUE THREAD

**Issue by crapthings** [FortAwesome/Font-Awesome#5678]
fa already have some iot icons like

lightbulb
mobile-phone
wifi
plug
dashboard
etc

maybe we can have some iot icons group

tv, remote, sensor, switch, socket, light, chip, etc ...

somethings like this ?

![image](https://cloud.githubusercontent.com/assets/1147704/6202615/7c987a36-b530-11e4-9db6-087a6e2ff7b6.png)

**Comment by crapthings** [comment]
![image](https://cloud.githubusercontent.com/assets/1147704/6202625/2568e8a8-b531-11e4-985b-741bd06304e5.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please open new individual requests and search for duplicates before

eg: washing machine #washing
