### ISSUE TITLE
Icon request: researchgate

### ISSUE THREAD

**Issue by mansourweb** [FortAwesome/Font-Awesome#5683]
![rg](https://cloud.githubusercontent.com/assets/10654684/6204302/3c0858ae-b546-11e4-852c-6c747bbdc3f3.png)

ResearchGate is a social networking site for scientists and researchers to share papers, ask and answer questions, and find collaborators.

Thanks.

**Comment by tagliala** [comment]
duplicate of #3634, please +1 that request

closing here
