### ISSUE TITLE
Icon Request: Snow Utilities (fa-snow, fa-snowblower, etc)

### ISSUE THREAD

**Issue by pimatrix314** [FortAwesome/Font-Awesome#5684]
Snow utilities such as a plow, snow, etc.

**Comment by nikkiroylance** [comment]
+1

**Comment by tagliala** [comment]
Sorry, can't keep this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

snow: #1739 

If you need specific icons, please open a new proper request

closing here
