### ISSUE TITLE
Icon Request: fa-mountain

### ISSUE THREAD

**Issue by HavingFunAlready** [FortAwesome/Font-Awesome#5685]
How about a mountain icon? I am developing travel themed website, and a mountain icon would be great! (I cant seem to drag and drop; if you google "mountain icon", there are tons of them....)

Thank you!

**Comment by HavingFunAlready** [comment]
How about a hiker icon? I am developing travel themed website, and a hiker icon would be great! (I cant seem to drag and drop; if you google "hiker icon", there are tons of them....)

Thank you!

**Comment by Tibo-R** [comment]
+1 for the mountain icon

**Comment by barbieswimcrew** [comment]
+1 for mountain icon! Would be great to have something like this:

![Mountain Icon](http://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mountain-Icon.svg/128px-Mountain-Icon.svg.png)

**Comment by tagliala** [comment]
dup of #4109 , please +1 that request

closing here
