### ISSUE TITLE
Icon request: icon-screwdriver

### ISSUE THREAD

**Issue by annemonet** [FortAwesome/Font-Awesome#5687]
I'm hoping for a screwdriver icon :)  please :) 
![srewdriver](https://cloud.githubusercontent.com/assets/11029383/6212313/0102faf4-b5e4-11e4-99f5-6daf33847992.JPG)

Kind regards Anne

**Comment by maimouzaki** [comment]
This is definitely a good idea!

**Comment by G-Driver** [comment]
+1

**Comment by ChickenSniper** [comment]
+1 (and other tools found in a toolbox!!!)

**Comment by dhaupin** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by Gab0o777** [comment]
+1 we really need this!

**Comment by bstolle** [comment]
+1

**Comment by kwiens** [comment]
+1

**Comment by schowes** [comment]
+1

**Comment by serveit-ca** [comment]
+1

**Comment by negste** [comment]
+1

**Comment by ElijahBrandyberry** [comment]
+1

**Comment by klb-rodriguez** [comment]
+1

**Comment by plasmadancom** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=screwdriver

**Comment by kwiens** [comment]
Awesome thank you!
