### ISSUE TITLE
Icon Request: `icon-walking`

### ISSUE THREAD

**Issue by designermonkey** [FortAwesome/Font-Awesome#5689]
A bit of a weird use case, but could an icon be created for walking in the transport section?

Two feet on a diagonal, one in front of the other...

All forms of transport are accounted for apart from walking.

**Comment by kkirsche** [comment]
Per [CONTRIBUTING.md](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) — Please title your new issue Icon request: `icon-name` (e.g., Icon request: `icon-car`).

**Comment by jmcopeland** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #844 , please +1 that request

@kkirsche thanks

**Comment by kkirsche** [comment]
Yep. Thanks for the project.
