### ISSUE TITLE
Icon Request: fa-google-apps

### ISSUE THREAD

**Issue by ricardopolo** [FortAwesome/Font-Awesome#5693]

**Comment by tagliala** [comment]
any example of the logo?

**Comment by m1dst** [comment]
![plainicon com-50227-32px-20c](https://cloud.githubusercontent.com/assets/958968/11556214/2159b96c-999d-11e5-84e6-064b89d06ede.png)

http://plainicon.com/dl.php?pid=50227&tem=svg&con=download-icon is a svg version

**Comment by codyn329** [comment]
+1

**Comment by tagliala** [comment]
This request was not clear.

Feel free to open a [new brand request template](https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=brand+icon&template=001_brand_request.yml&title=Brand+request%3A+) if it is the case
