### ISSUE TITLE
Icon Request: fa-bid | fa-auction 

### ISSUE THREAD

**Issue by rmalinowski** [FortAwesome/Font-Awesome#5699]
simple hammer icon :) 
image.google.com -> 'auction icon' and there will be a lot of examples.

![32274](https://cloud.githubusercontent.com/assets/199527/6228730/d3975e12-b6af-11e4-90e1-b635555c5914.png)

**Comment by lenamtl** [comment]
there is one already see fa-gavel

**Comment by aethior** [comment]
There is `fa-gavel` (http://fontawesome.io/icon/gavel/) icon.

@tagliala I think you can close here.
