### ISSUE TITLE
Icon request: icon-moon, icon-sun (filled)

### ISSUE THREAD

**Issue by szegheo** [FortAwesome/Font-Awesome#5700]
The pack already has "moon-o" and "sun-o" but misses the normal versions (fa-sun, fa-moon).
These are very common icons, I think they deserve the default filled pairs, like fa-heart has.
In my current case I have some icons in a menubar but only moon is outlined so it breaks harmony:

![icons](https://cloud.githubusercontent.com/assets/625056/6229009/d8cf3988-b6b2-11e4-9ce2-343f832612a2.png)

Please consider adding them.
Thank you for all the work on this project and letting us to use it for free!

**Comment by olliecook** [comment]
See also #837

**Comment by sdhp** [comment]
Agree, same thoughts here - plus one...

**Comment by Twanneman** [comment]
plus one :+1:

**Comment by ccmedialab** [comment]
plus one

**Comment by nextriot** [comment]
+1

**Comment by toddlevy** [comment]
+1

**Comment by kevinyuliawan** [comment]
+1

**Comment by DistantParadox** [comment]
+1, specifically for the PaleMoon browser

**Comment by lvv83** [comment]
+1

**Comment by Piedalu** [comment]
+1

**Comment by anthonyvalera** [comment]
+1

**Comment by Aflexon** [comment]
+1

**Comment by nmertaugh** [comment]
+1

**Comment by chapeljuice** [comment]
+1

**Comment by jennyhaines** [comment]
+1
