### ISSUE TITLE
Request: Add class for modify speed of spinner icons

### ISSUE THREAD

**Issue by edteke** [FortAwesome/Font-Awesome#5701]
fa-spin-2x would spin the icons twice as fast.

**Comment by ac04** [comment]
You could just make your own custom class for this?

.fa-spin-2x {
  -webkit-animation: fa-spin 1s infinite linear;
  animation: fa-spin 1s infinite linear;
}

**Comment by jbw91** [comment]
+1 on @ac04's comment

**Comment by ElVisPL** [comment]
+1
Why not add it to source?

About adding it by ourselves - yeah as well we could add .fa-2x or .fa-3x , but hey... they are already there!

**Comment by sensibleworld** [comment]
You can control this if you add some inline CSS:
`<i class="fa-solid fa-gear fa-spin" style="--fa-animation-duration: 1s;"></i>`
