### ISSUE TITLE
Icon request: fa-horse + fa-dog + fa-cat

### ISSUE THREAD

**Issue by somethingworks** [FortAwesome/Font-Awesome#5703]
Hey all,

a few icons for (domestic) animals would be great.
Dog, cat, horse, bird etc.

I know there are a few topics requesting this but not much seems to happen there.
So therefor this new topic.

Please +1
or
Let me know how to make them myself ;-)

I am using Ninja Kick: Sliding Panel which uses Font Awesome and no custom pictures...
Hope you guys can help.

Thanx!!!

**Comment by ryanknutson** [comment]
+1

**Comment by amybroman** [comment]
+1

**Comment by farukscan** [comment]
+1 domestic animals

**Comment by tagliala** [comment]
Closing here

horse: #280 
dog: #4755 
cat: #2226
