### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by abhishek2409** [FortAwesome/Font-Awesome#5704]
Please make some icon from cricket

**Comment by tagliala** [comment]
hi,

I have to close this request. #5706 is fine, but I can't keep this one open

As per our [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons), at the moment we are not accepting requests for comprehensive set of icons dealing with a very specific field

**Comment by abhishek2409** [comment]
ok 
 

     On Sunday, 22 February 2015 6:00 AM, Geremia Taglialatela <notifications@github.com> wrote:
   

 hi,I have to close this request. #5706 is fine, but I can't keep this one openAs per our contributing guidelines, at the moment we are not accepting requests for comprehensive set of icons dealing with a very specific field—
