### ISSUE TITLE
Some icons work, others don't

### ISSUE THREAD

**Issue by kentkanada** [FortAwesome/Font-Awesome#5705]
Some icons like apple or shopping work fine. In my case spotify doesn't. Any ideas why? Implemented them exactly the same way. http://geilescheiben.de/lard-the-last-temptation-of-reid/
![bildschirmfoto 2015-02-18 um 09 33 30](https://cloud.githubusercontent.com/assets/3015688/6244288/9eb784f4-b751-11e4-8b7a-16a53f1979d3.png)

**Comment by vipbird12** [comment]
It seems like you are using an old version of Font Awesome, v4.0.3, however the spotify icon was introduced in v4.1, as it says [here](https://fortawesome.github.io/Font-Awesome/icon/spotify/).  
Change line 111 from  
```html
<link rel='stylesheet' id='font-awesome-css'  href='http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css?ver=4.1' type='text/css' media='all' />
```
to the newest version, as detailed [here](https://fortawesome.github.io/Font-Awesome/get-started/):
```html
<link rel="stylesheet" id="font-awesome-css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" type="text/css" media="all">
```
and everything should work fine!  
![image](https://cloud.githubusercontent.com/assets/1476338/6244892/c657d550-b750-11e4-8077-26cd846304ba.png)

**Comment by kentkanada** [comment]
Great Support.
Works fine.

Best regards.
Tim



---

Tim Kowalewski
Creative /

t.kowalewski@lgtm.de <mailto:t.kowalewski@lgtm.de>
www.lgtm.de <http://www.lgtm.de/>

**Comment by tagliala** [comment]
@vipbird12 thanks
