### ISSUE TITLE
fa-header icon doesn't show

### ISSUE THREAD

**Issue by lial** [FortAwesome/Font-Awesome#5707]
I use Imperavi redactor with you Awesome 4.0.3 css minified file to add some icons on toolbar
When I try any other icons, they are shows, but fa-header not - just empty place, so button is invisible

**Comment by Dennis14e** [comment]
Font Awesome 4.0.3? fa-header was added with version 4.1.
See http://fontawesome.io/icon/header/ (Created: v4.1)

**Comment by lial** [comment]
Sorry it was typo , I'm using last version 4.3.0
And Header and I found paragraph looks incorrect too.
Look pls on screenshot: first button has fa-paragraph, second is fa-header
![screenshot 2015-02-19 15 40 01](https://cloud.githubusercontent.com/assets/853588/6264427/c2b648e6-b845-11e4-9f29-6a07c6460f2a.png)

**Comment by LauritzT** [comment]
Fiddle? (http://jsfiddle.net)

**Comment by tagliala** [comment]
maybe there is another plugin loading an older version of fontawesome or there are conflicts.

It's quite hard to say, and I can't confirm this issue.

I'm going to close this one but feel free to comment

**Comment by gulhakan** [comment]
fa-heading works
