### ISSUE TITLE
Icon Request: fa-shield 

### ISSUE THREAD

**Issue by bnussman** [FortAwesome/Font-Awesome#5709]
Seeing a Shield would be super useful for a VPN icon. I just kinda need a way to symbolize a VPN in any way!  

Something Like This:
![image](http://i.imgur.com/mjlL4Qc.png)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/shield/

**Comment by bnussman** [comment]
Thanks so much! @tagliala

**Comment by tagliala** [comment]
@bnussman is that fine for your needs?

**Comment by bnussman** [comment]
Oh yeah! Its perfect! keep up your amazing work! @tagliala

**Comment by tagliala** [comment]
@bnussman thanks!

closing here
