### ISSUE TITLE
Icon Request: fa-open-book

### ISSUE THREAD

**Issue by TLJens** [FortAwesome/Font-Awesome#5712]
I would love an open-book icon to coincide with fa-book. It would work nicely in my tree navigation depicting what chapter you've navigated to within help docs. I use the open and closed folders for tree navigation as you search through files. It would be great if I could mirror that open/closed concept in the help files chapter-tree!

**Comment by tagliala** [comment]
Duplicate of #176, please +1 that request

closing here
