### ISSUE TITLE
Icon request: icon-drill

### ISSUE THREAD

**Issue by 1mihkel** [FortAwesome/Font-Awesome#5715]
Drill icon is quite universal and can represent all power tools or building company etc. I need it for new B2B company (for equipment tracking module).

Something like this would be perfect:
![screen shot 2015-02-19 at 9 56 29](https://cloud.githubusercontent.com/assets/11071387/6263282/9fd92d5c-b81d-11e4-8619-f4d2e20a275b.png)

**Comment by dhaupin** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by tagliala** [comment]
Duplicate of #3139, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by tenznhok** [comment]
Is the drill-icon done? I cant find it

**Comment by tagliala** [comment]
@tenznhok nope, #3139 is a request

**Comment by shanipreempt** [comment]
+1
