### ISSUE TITLE
Quote icons shows incorrect

### ISSUE THREAD

**Issue by lial** [FortAwesome/Font-Awesome#5716]
I'm using fa-quote-right in my project, but it shows with two quotes like on screenshot
![screenshot 2015-02-19 16 04 58](https://cloud.githubusercontent.com/assets/853588/6264791/ddd41a1a-b848-11e4-9858-8509343077b0.png)

**Comment by tagliala** [comment]
could you please provide a fiddle showing the issue?

the quote left icon does not come from fontawesome

**Comment by tagliala** [comment]
You can use this one as a base: http://jsfiddle.net/tagliala/e9yfxsfj/

**Comment by lial** [comment]
Thanks for your reply, but don't worry it is not problem with awesome fonts, problem is with Imperavi redactor that used it. I found the reason: if button name on toolbar contains in fa-* - so they start shows as on screenshot. also I found link button problem
![screenshot 2015-02-20 18 30 18](https://cloud.githubusercontent.com/assets/853588/6286668/01eaa598-b92c-11e4-9f09-d8764d063952.png)

**Comment by tagliala** [comment]
:+1: , closing here
