### ISSUE TITLE
Icon request: fa-jump-in 

### ISSUE THREAD

**Issue by pixsrv** [FortAwesome/Font-Awesome#5719]
![image](https://cloud.githubusercontent.com/assets/10224591/6265820/b8a8271a-b832-11e4-9a1c-6d371e222e54.png)

**Comment by tagliala** [comment]
any use case?

**Comment by pixsrv** [comment]
explanation for fa-jump-in/fa-jump-out
well it means get-into/get-out-of
it's more precise than forward/backward or (forward/reply)

it can be similar to sign-in/sign-out

it can be also enter-here/quit
there is a lack of such icon which means enter

i offtem meet a need to signal such action in narrow tables
where there is no room to write any word (just to set an icons)

i hope such explanation and alternative names are enough :)
