### ISSUE TITLE
Icon request: fa-jump-out

### ISSUE THREAD

**Issue by pixsrv** [FortAwesome/Font-Awesome#5720]
![image](https://cloud.githubusercontent.com/assets/10224591/6265839/dcdc8432-b832-11e4-87cf-07b88fc196aa.png)

**Comment by tagliala** [comment]
any use case?

**Comment by pixsrv** [comment]
explanation for fa-jump-in/fa-jump-out
well it means get-into/get-out-of
it's more precise than forward/backward or (forward/reply)

it can be similar to sign-in/sign-out

it can be also enter-here/quit
there is a lack of such icon which means enter

i offtem meet a need to signal such action in narrow tables
where there is no room to write any word (just to set an icons)

i hope such explanation and alternative names are enough :)

**Comment by sensibleworld** [comment]
Perhaps these can work:

https://fontawesome.com/icons/arrow-up-from-arc?s=solid&f=classic
https://fontawesome.com/icons/arrow-down-to-arc?s=solid&f=classic
