### ISSUE TITLE
Icon request: icon-cfl (compact fluorescent lamp)

### ISSUE THREAD

**Issue by robertegnacheski** [FortAwesome/Font-Awesome#5721]
I work in the lighting industry as a web designer and it would be nice to have CFL and LED icons besides the original light bulb design. Thanks!

**Comment by tagliala** [comment]
any example?

**Comment by veronikerr** [comment]
+1
Example CFL
![icon_cfl_positiveonly-crop](https://cloud.githubusercontent.com/assets/11213838/6395660/abc153da-bda7-11e4-81fd-f4a6e78adb96.png)

Example LED 1
![screen shot 2015-02-26 at 11 08 35 am](https://cloud.githubusercontent.com/assets/11213838/6395695/d5cc211e-bda7-11e4-8060-e32a92d95de2.png)


Example LED 2
![industry-led-diode-icon](https://cloud.githubusercontent.com/assets/11213838/6395686/c61ba83e-bda7-11e4-8bd2-620c1d08b7d3.png)

**Comment by LauritzT** [comment]
+1

**Comment by tagliala** [comment]
Renaming as `icon-cfl` (bulb)

Please +1 #5759 for icon-led

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/lightbulb-cfl?f=classic&s=solid
