### ISSUE TITLE
Icon Request: fa-reply-o

### ISSUE THREAD

**Issue by MaklaCof** [FortAwesome/Font-Awesome#5724]
Circle has circle-o, comment has comment-o, envelope has envelope-o, heart has heart-o ...
(It would be nice to have reply filled with nothing. Only border.)

I am using reply icon for navigation (back), but I would rather use empty arrow then full.

**Comment by ttamas7** [comment]
+1

**Comment by ttamas7** [comment]
we would also need an empty replied icon?
I mean if someone has not replied yet the icon would not be filled.
thanks

**Comment by tagliala** [comment]
Available in FA5 Pro
https://fontawesome.com/icons/reply?style=regular
