### ISSUE TITLE
Icon Request: fa-employer (business man)

### ISSUE THREAD

**Issue by yordy** [FortAwesome/Font-Awesome#5731]
Some icon that would illustrate an employer, business man like person.

Made it myself in fa style but could be done better...

![fa-businessman](https://cloud.githubusercontent.com/assets/5030326/6283268/44cb600e-b8e2-11e4-9e3b-3ba81e3b4a77.png)

**Comment by kevinvanvliet** [comment]
Hello Yordy,

We are seriously concidering to add this icon to our collection.

Nice input man!!

Yours sincerely,

Kevin from FontAwesome - its AWESOME

**Comment by tagliala** [comment]
duplicate of #3397 , please +1 that request

closing here

**Comment by jancel** [comment]
+1 (We closed both this and #3397 ?) Can we leave one open or is this in next release?
