### ISSUE TITLE
WIFI Icon Not sharp or clear - Chrome 

### ISSUE THREAD

**Issue by dukesanj** [FortAwesome/Font-Awesome#5735]
Hi,
Icons are not appearing sharp, please see image.
OS: Win 7 64 bit
Font Awesome 4.3.0
Font size 12px
Browser: Chrome - Version 40.0.2214.115 m

Could someone let me know what the issue is please?

Thanks...
Sanj

![wifi](https://cloud.githubusercontent.com/assets/6709553/6311231/13c2869e-b960-11e4-950d-286415713be1.png)

**Comment by acshef** [comment]
FontAwesome is designed for 14px (and multiples of 14). Using 12px will obviously degrade quality.

**Comment by tagliala** [comment]
ah yes @acshef is right

we can't guarantee pixel perfection at any icon size, closing here
