### ISSUE TITLE
Icon Request: fa-turntable

### ISSUE THREAD

**Issue by sofodj** [FortAwesome/Font-Awesome#5737]
Please create a turntable character which could be used to symbolize DJs, recorded music, etc. This could be used as an icon, button, place holder, play control, etc.

For example (but it should be inverted, no background): 
![turntable](https://cloud.githubusercontent.com/assets/11130803/6312775/c14aadd4-b954-11e4-8998-37513b7d2072.png)

Thank you for your consideration!

**Comment by tagliala** [comment]
Refers to #1080

**Comment by cstyan** [comment]
+1, even just a LP record icon would be helpful.

**Comment by nagulian** [comment]
+1

**Comment by tcbmedia** [comment]
+1

**Comment by m-alo** [comment]
+1

**Comment by antoniu86** [comment]
+1

**Comment by doctsf** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/turntable?style=solid
