### ISSUE TITLE
Icon Request: fa-firetruck

### ISSUE THREAD

**Issue by brechmos** [FortAwesome/Font-Awesome#5738]
I would love to see a fire truck character.  I think it could be based off of the fa-truck.  Maybe just a little longer and then above the cab maybe some lines coming up diagonally as if it was lights. 

Thanks for any potential consideration!

**Comment by tomhrose** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by devfunkd** [comment]
+1

**Comment by LionelMeroni** [comment]
+1

**Comment by andreygolubkow** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by allor** [comment]
+1 need for emergency services application

**Comment by dutchie027** [comment]
+1

**Comment by xTey** [comment]
+1

**Comment by tagliala** [comment]
Sorry, this is a duplicate of #5738. I'm going to add `firetruck` to that title
