### ISSUE TITLE
Icon Request: fa-mixcloud

### ISSUE THREAD

**Issue by gioslv** [FortAwesome/Font-Awesome#5741]
Hi,

I wrote few minutes ago about the creation of an icon for the site reverbernation.
I'm writing now for the same request, but for the site mixcloud.

Example image:
![mcloud_example](https://cloud.githubusercontent.com/assets/11137390/6315256/1a6508f8-b9fd-11e4-8cfd-05c2aa57db1e.png)

Thanks again!

**Comment by tagliala** [comment]
duplicate of #2753 , please +1 that request

closing here
