### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by Dimetriya** [FortAwesome/Font-Awesome#5748]
Need two icons on social networks vk.ru and ok.ru

**Comment by Dimetriya** [comment]
Sorry, found the icon vk.ru, but no icons ok.ru

**Comment by tagliala** [comment]
@Dimetriya about ok.ru, please +1 #1685 

Please also take a look at the last comment in the above thread because there is a fork of fontawesome that might interest you

closing here
