### ISSUE TITLE
Icon request: fa-braille

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [FortAwesome/Font-Awesome#5753]
I think this icon can be used to distinguish that a site may be easy to read/navigate with a screen reader, resources for the blind, transcripts for visually impaired, etc.
![alt text](http://fontmeme.com/images/Braille-Alphabet-550x466.png "Braille")
Because they are simply two different sized circles, I don't think it'd be too hard to add in.

The Nemeth code at the bottom is for explaining mathematical and scientific symbols in Braille.

**Comment by tagliala** [comment]
sorry but I didn't get this one. Could you pleae clarify?

How many icons you are requesting?

**Comment by CoWinkKeyDinkInc** [comment]
Just a few that would be needed to indicate to many that it is braille.  I think that you should keep the hollow circles to make it easier, or make having them an option.

**Comment by tagliala** [comment]
sory, I still need more information. Could you please post examples of what you exactly need?

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by CoWinkKeyDinkInc** [comment]
Since I'm just using them as an icon, and not to spell out things, I specifically want the letters M, N, O, P, R and S.  So I'd be like `fa-braille-m` and so on.  I think that these letters are easy to figure out what they are.  The entire alphabet would be a bonus if you have the time.

**Comment by caduvieira** [comment]
To indicate the braille alphabet there is this icon:
![braill-p](https://cloud.githubusercontent.com/assets/3831408/11442995/c00c960c-9500-11e5-9966-5838a62958c7.jpg)

https://www.graphicartistsguild.org/tools_resources/downloadable-disability-access-symbols

**Comment by MVcodeartbr** [comment]
+1

**Comment by tagliala** [comment]
Closing here in favour of #8013 

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

If we have an official logo or universally accepted logo, it would be better. I will use @caduvieira 's example

**Comment by CoWinkKeyDinkInc** [comment]
Okay, then use that one.

**Comment by davegandy** [comment]
We'll add fa-braille as a part of a new accessibility category.

**Comment by caduvieira** [comment]
Could this issue be reopened?
Em 5 de abr de 2016 2:05 PM, "Dave Gandy" <notifications@github.com>
escreveu:

**Comment by davegandy** [comment]
@caduvieira It was reopened yesterday.

**Comment by davegandy** [comment]
Braille icon added to 4.6.0-wip branch. Closing.

**Comment by CoWinkKeyDinkInc** [comment]
Thanks dude!

**Comment by jjthom87** [comment]
Totally awesome. I have a cousin that is blind that would love this.
