### ISSUE TITLE
Icon request: fa-subtitles

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [FortAwesome/Font-Awesome#5754]
This icon should be added to distinguish between closed captions for the hearing impaired and text for people who don't understand the language of a video.

**Comment by tagliala** [comment]
any example?

**Comment by CoWinkKeyDinkInc** [comment]
I was thinking of something similar to the `fa-cc` box, but I can't think of how to shorten the words so it will be easily understandable.  Most apps use a speech bubble with lines in them, something like this.

http://www.iconsfind.com/wp-content/uploads/2014/02/Apps-gnome-subtitles-icon.png

**Comment by yannickl** [comment]
+1

**Comment by supertassu** [comment]
+1

**Comment by reneedenham** [comment]
I would also like a subtitles icon, but in addition (and I'm writing this here because it's directly related -  if you'd rather I create a new post let me know) can we also have a closed captions icon? 

Closed captions also includes descriptions of other sounds (eg laughter) rather then just subtitles. 

There is a standard look for closed captions:

https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Closed_captioning_symbol.svg/2000px-Closed_captioning_symbol.svg.png

This would also fall under the new accessibility iconset.

**Comment by Kikidy-cam** [comment]
I also want this icon, however, I want just the letters 'SUB' in a black square like cc-visa, but that is only because I also want DUB #10255.

**Comment by collettezq7** [comment]
![screen shot 2017-03-16 at 5 13 37 pm](https://cloud.githubusercontent.com/assets/10457606/24022418/ef9c8cb0-0a6b-11e7-9c19-977bf8d4a7ee.png)

Or something similar to this; Something that is distinctly different from the comment icon and that doesn't require English as a primary language?

**Comment by CoWinkKeyDinkInc** [comment]
Yes, something like @collettezq7 suggested is what I would like.

**Comment by reneedenham** [comment]
I like this suggestion too



Kind Regards,

*Renée Denham*
Educational Designer
Griffith Online
​Academic Provost​
Logan Campus, University Drive
MEADOWBROOK QLD 4131

*Phone **|* 07 3382 1433
*Mobile |* 04 2499 1076

**Comment by cellcortex** [comment]
+1

**Comment by peppeg85** [comment]
+1 

hello, it could be like the youtube icon: 

![baseline_subtitles_black_18dp](https://user-images.githubusercontent.com/25436763/40432159-4aa9381e-5ea9-11e8-9184-0b06e00561fa.png)

**Comment by hamiltongabriel** [comment]
+1

**Comment by alexgorski** [comment]
+1

**Comment by jkohlin** [comment]
How about mdi:subtitles? That one is pretty standard I think. iOS has a similar icon in its ui as well.
![image](https://user-images.githubusercontent.com/4112881/134132766-4d5367eb-a9d1-4237-afe1-665e0ddf715e.png)

**Comment by sensibleworld** [comment]
Does this icon work: https://fontawesome.com/v6.0/icons/message-captions?s=solid (though may need an update to be less face-like)

**Comment by alexgorski** [comment]
Can you do an Open Caption icon? (Like fa-closed-captioning but with OC vs
CC)?

**Comment by jkohlin** [comment]
> Does this icon work: https://fontawesome.com/v6.0/icons/message-captions?s=solid (though may need an update to be less face-like)

Well, if we loose the speech bubble tail at the bottom. 
It should be used as a toolbar icon to activate subtitles in different languages on a video. (not closed caption)
I can't for my life understand why this hasn't been implemented yet. 😊

**Comment by sensibleworld** [comment]
This has been added: https://fontawesome.com/search?q=subtitles&o=r
