### ISSUE TITLE
Icon request: pellettruck icon

### ISSUE THREAD

**Issue by mjra** [FortAwesome/Font-Awesome#5757]
I would like a Icon of a pellettruck for my actual webseite project.
![pallettruck](https://cloud.githubusercontent.com/assets/9435976/6325436/d86a33d2-bb47-11e4-9251-30fb27d67b35.jpg)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons?q=flatbed&s=solid%2Cbrands%2Clight
https://fontawesome.com/v6.0/icons?q=dolly&s=solid%2Cbrands%2Clight
