### ISSUE TITLE
Icon Request: fa-viadeo

### ISSUE THREAD

**Issue by SideWeb** [FortAwesome/Font-Awesome#5758]
I'd like to request a viadeo icon. I have a need for it in a website. It's very important for me !

I've attached an example of the Viadeo icon.

Best regards,

Cedric

![image-viadeo](https://cloud.githubusercontent.com/assets/11157148/6325498/8a94a6fa-bb48-11e4-987e-0f599509012d.png)

**Comment by tagliala** [comment]
duplicate of #886 , please +1 that request

closing here
