### ISSUE TITLE
Icon Request: fa-shrimp

### ISSUE THREAD

**Issue by jorisre** [FortAwesome/Font-Awesome#5764]
Thanks for the amazing work, would like to see a shrimp icon

fa-shrimp

**Comment by bbreakerandroid** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by Crissov** [comment]
JFTR, there are two related Unicode 9.0 emojis:

- 🦐U+1F990 alive
- 🍤 U+1F364 fried

Also see #2722 for fish and other seafood.

**Comment by guestonlineVR** [comment]
+1

**Comment by Nephilim72** [comment]
I was looking for fa-shrimp icon to display food-allergy icons in my app.
fish is too general IMHO.

**Comment by sensibleworld** [comment]
We've just added a shrimp icon! https://fontawesome.com/v6.0/icons/shrimp?s=solid
