### ISSUE TITLE
Icon Request: fa-fiscality

### ISSUE THREAD

**Issue by leonardstalder** [FortAwesome/Font-Awesome#5766]

**Comment by tagliala** [comment]
any example?

**Comment by leonardstalder** [comment]
![tax](https://cloud.githubusercontent.com/assets/5653981/6393475/9f8eaaa4-bdca-11e4-8343-7076b46c8347.png)

**Comment by sensibleworld** [comment]
These might work: https://fontawesome.com/search?q=sack&o=r&s=solid&f=classic
