### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by mPemba** [FortAwesome/Font-Awesome#5768]
Would love some icons for wine glasses, wine bottles, and grapes.

Animal icons would be killer as well. 

You guys rock though I love Font Awesome! 

Thank you!

**Comment by tagliala** [comment]
hi,

grapes is a dup of #5691 , please +1 that request
wine bottle is a dup of #1762 , please +1 that request
wine glass is a dup of #3614 , please +1 that request

all dups, closing here
