### ISSUE TITLE
Icon request: icon-signal-none

### ISSUE THREAD

**Issue by goloroden** [FortAwesome/Font-Awesome#577]
Could be a striked-through version of `icon-signal` or something such as two connectors which are disconnected.

**Comment by nurettin** [comment]
Just needed this in our pi project

**Comment by johnhargrove** [comment]
This would be a useful addition!

**Comment by sensibleworld** [comment]
We added this to Font Awesome Pro in our last release. Check it out here: https://fontawesome.com/icons/signal-slash?style=solid
