### ISSUE TITLE
Icon Request: Atlassian products

### ISSUE THREAD

**Issue by stygiansabyss** [FortAwesome/Font-Awesome#5772]
One thing that would seem to be nice would be the atlassian products (Jira, Bamboo, Stash,/Bitbucket, Confluence, etc).  Since these icons are fairly common in development, being able to use them with font-awesome would be amazing.

**Comment by JeffreyHyer** [comment]
:+1

**Comment by mhemmings** [comment]
+1

**Comment by cuttingedgehobbies** [comment]
:+1:

**Comment by tagliala** [comment]
jira: please +1 #2724 

I should ask you to open new individual request for other brands, because this request does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Closing here
