### ISSUE TITLE
Icon Request - fa-images

### ISSUE THREAD

**Issue by krishna19** [FortAwesome/Font-Awesome#5780]
There is no icon to represent multiple images. Please add a icon like this
![screen shot 2015-02-25 at 3 13 02 pm](https://cloud.githubusercontent.com/assets/4782674/6368272/2cfdda74-bd01-11e4-9128-aa7e21119214.png)

**Comment by PunktSonstNichts** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #855 , please +1 that request

closing here
