### ISSUE TITLE
Icon Request: fa-campfire

### ISSUE THREAD

**Issue by sgenzer** [FortAwesome/Font-Awesome#5783]
I made a campfire icon for FA if you want - took the fire icon and added logs.  :)  Let me know if you want the vector file.
![camp fire](https://cloud.githubusercontent.com/assets/10297265/6373996/0393a2b0-bcdc-11e4-9356-795c5753f68a.png)

**Comment by JeffreyHyer** [comment]
:+1

**Comment by sgenzer** [comment]
Scott Genzer
Scott@GenzerConsulting.com <mailto:scott@genzerconsulting.com>
 

               www.GenzerConsulting.com <https://genzerconsulting.com/>

**Comment by lenamtl** [comment]
+1

**Comment by sgenzer** [comment]
cool!  Thx.

**Comment by MrZach** [comment]
+1

**Comment by Clyx** [comment]
Need this :+1:

**Comment by limitstudios** [comment]
+1 

![icon_fire](https://cloud.githubusercontent.com/assets/8024370/21258097/641ef50e-c373-11e6-8997-ceddcc0ed998.png)

**Comment by raybradley** [comment]
+1

![campfire](https://user-images.githubusercontent.com/622725/41182959-01b8e3d0-6b46-11e8-8130-5d4b7cbffbc3.jpg)

**Comment by aethior** [comment]
@tagliala I'm confused. Is this a brand icon? Sure? (check label)

**Comment by tagliala** [comment]
@aethior probably an error on my side

https://fontawesome.com/icons/campfire?s=solid

Added in 6.0 Pro

**Comment by tagliala** [comment]
@aethior confirming that it is a mistake, 

actually Campfire was the old name of Basecamp, and there was an old request for this brand

Ref: 
- https://basecamp.com/retired/campfire
- #292
