### ISSUE TITLE
Icon Request: fa-grademaxx

### ISSUE THREAD

**Issue by mktalucomaxx** [FortAwesome/Font-Awesome#5784]
Hello , I am beginner User Bootstrap CDN , I am developing a GRADEMAXX.com.br site and have some icons you would like to use , I'll be very grateful , thank you for your attention.

![cercamovel](https://cloud.githubusercontent.com/assets/11196045/6374614/cba40538-bcf0-11e4-9622-750415653378.jpg)
![cet](https://cloud.githubusercontent.com/assets/11196045/6374613/cba31614-bcf0-11e4-8a2e-71d52dffbd7d.jpg)
![gradilpark](https://cloud.githubusercontent.com/assets/11196045/6374611/cba272ea-bcf0-11e4-8877-f267f705372e.jpg)
![kitgrade](https://cloud.githubusercontent.com/assets/11196045/6374612/cba2db68-bcf0-11e4-9216-2b23ec4b01b7.jpg)
![orsodil](https://cloud.githubusercontent.com/assets/11196045/6374615/cba6d740-bcf0-11e4-8c77-4a48a0f31a52.jpg)
![orsograd](https://cloud.githubusercontent.com/assets/11196045/6374616/cba85c0a-bcf0-11e4-9d9d-ba9559acad6a.jpg)
![orsorod](https://cloud.githubusercontent.com/assets/11196045/6374619/cbbc29e2-bcf0-11e4-8f12-821d776e6526.jpg)
![orsoseg](https://cloud.githubusercontent.com/assets/11196045/6374617/cbbb3280-bcf0-11e4-87a4-cb645fd23c24.jpg)
![pisograd](https://cloud.githubusercontent.com/assets/11196045/6374618/cbbbc614-bcf0-11e4-9b5c-5a90abd1cc46.jpg)
![portoes](https://cloud.githubusercontent.com/assets/11196045/6374620/cbbfef46-bcf0-11e4-94e9-7e5aed0f0803.jpg)

**Comment by mktalucomaxx** [comment]
Olá, eu sou novato Usuário Bootstrap CDN, estou desenvolvendo um site GRADEMAXX.com.br e tem alguns ícones que você gostaria de usar, eu vou ser muito grato, muito obrigado pela sua atenção.

**Comment by tagliala** [comment]
Hi,

sorry but I didn't get this request :\

Do you need all these icons? Are they brand? What is their general use case?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
