### ISSUE TITLE
Icon request: icon-massage (Wellness / Spa)

### ISSUE THREAD

**Issue by DR-Kay** [FortAwesome/Font-Awesome#5789]
Hi,

It would be very nice to introduce a icon for Wellness / spa.
something like a massage; http://s21.postimg.org/xmkkxv7tv/screenshot_408.png

**Comment by dimoned** [comment]
+1 I need it too http://www.housesaobento.pt/images/icon33.jpg

**Comment by rmithun** [comment]
+1 We need it too

**Comment by KalaniTed** [comment]
me too

**Comment by ankitraturi** [comment]
+1

**Comment by bummelbux** [comment]
+1 also looking for icon-spa or icon-wellness

**Comment by ekizo** [comment]
+1 icon-spa

**Comment by luzpaz** [comment]
👍

**Comment by Hydroxi** [comment]
+1

**Comment by gluleci** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/spa?style=solid
