### ISSUE TITLE
Icon Request: fa-hardhat (construction helmet)

### ISSUE THREAD

**Issue by spc197** [FortAwesome/Font-Awesome#5790]
Please can we have an icon for a hard hat as used in construction

**Comment by rmtweb** [comment]
+1

**Comment by groovy21** [comment]
+1 really needed

**Comment by CountZachula** [comment]
+1.

Sorry for the duplicate (#6704).

**Comment by jlr7245** [comment]
+1 would love this icon. Something like this 
![image](https://cloud.githubusercontent.com/assets/12768542/8092760/276b4c6e-0f8a-11e5-9ac8-2bd3afd79a56.png)

**Comment by JuliaShier** [comment]
+1 Please

**Comment by workmaster2n** [comment]
+1 would love this

**Comment by cmeassociates** [comment]
+1

**Comment by uducharm** [comment]
+1

**Comment by jbonnier** [comment]
+1

**Comment by forestmarie** [comment]
+1

**Comment by caduvieira** [comment]
dupe of #3934 ?

**Comment by ianbale** [comment]
+1

**Comment by NinjaWaffles** [comment]
+1

**Comment by Row-Z** [comment]
+1

**Comment by ChanceDriven** [comment]
+1

**Comment by chicagomom** [comment]
+1

**Comment by vinnyamp** [comment]
+1

**Comment by bulljustin** [comment]
+1

**Comment by somereality** [comment]
+1

**Comment by ffuentes** [comment]
+1

**Comment by Melloyell** [comment]
+1

**Comment by johnclittle** [comment]
+1

**Comment by pewtel** [comment]
+1

**Comment by iLovebooks100per** [comment]
+1

**Comment by debaugh** [comment]
+1

**Comment by MackieeE** [comment]
+1 for weight :)

**Comment by progietheus** [comment]
+1 we need this!

**Comment by Crissov** [comment]
Perhaps U+26D1 ⛑ in Unicode #222, not U+1F477 👷

**Comment by vsajja** [comment]
+1,000,000,000

**Comment by samc449** [comment]
+1

**Comment by HexDT** [comment]
+1

**Comment by schowes** [comment]
+1

**Comment by thomasbjorndahl** [comment]
+1

**Comment by ksddearing** [comment]
+1

**Comment by vheimpel** [comment]
+1

**Comment by grafikat** [comment]
+1

**Comment by grafikat** [comment]
Here are a couple I drew up.

![constructionfa1](https://user-images.githubusercontent.com/8459555/29466756-584bd9ba-83fb-11e7-9be7-1b7083bcfddf.png)
![constructionfa2](https://user-images.githubusercontent.com/8459555/29466757-585083d4-83fb-11e7-95a2-e6219baab5d6.png)
![hardhaticonfa](https://user-images.githubusercontent.com/8459555/29466758-58537c88-83fb-11e7-8e07-63101d7a1c10.png)

**Comment by challe** [comment]
+1

**Comment by admincotecnologias** [comment]
+1

**Comment by xNicoPaz** [comment]
+1

**Comment by ionutab** [comment]
+1

**Comment by callkeeper** [comment]
+1

**Comment by klb-rodriguez** [comment]
+1

**Comment by zilhont** [comment]
+1

**Comment by medez** [comment]
+1

**Comment by yanfrank** [comment]
+1

**Comment by parooninmaenmoukari** [comment]
+1

**Comment by norcalfox** [comment]
+1

**Comment by melksedeque** [comment]
+1

**Comment by ilyankou** [comment]
+1

**Comment by RocketMan777** [comment]
+3

**Comment by deepjaisia** [comment]
+1

**Comment by charlygut** [comment]
+1 !!!

**Comment by castoldi** [comment]
+1

**Comment by dgonzalezn** [comment]
+1

**Comment by RabidPuffin** [comment]
Oh man, for sure this.

**Comment by ATLAdamL** [comment]
+1

**Comment by sensibleworld** [comment]
We've added `hard-hat` to Font Awesome Free: https://fontawesome.com/icons/hard-hat?style=solid
And `user-hard-hat` to Font Awesome Pro: https://fontawesome.com/icons/user-hard-hat?style=solid

**Comment by pieterdb4477** [comment]
+1

**Comment by tagliala** [comment]
@pieterdb4477 https://fontawesome.com/icons/hard-hat?style=solid

Just make sure you are using Font Awesome >= 5.7.0
