### ISSUE TITLE
Icon request: icon-money-bag

### ISSUE THREAD

**Issue by naisam** [FortAwesome/Font-Awesome#5791]
please give me an idea for creating money bag icon in font awesome

**Comment by tagliala** [comment]
duplicate of #1414, please +1 that request

edited #1414 to include money-bag in the title

closing here

**Comment by tagliala** [comment]
ah sorry...

@naisam please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
