### ISSUE TITLE
fa-record

### ISSUE THREAD

**Issue by suraj-arya** [FortAwesome/Font-Awesome#5799]
PLease create an icon for audio/video record. An fa-circle in a square box.

**Comment by LauritzT** [comment]
Why not just use fa-circle in a stack? http://fontawesome.io/examples/#stacked

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Record: https://fontawesome.com/icons/circle?style=solid

If you need a square around the circle, please use the stacking feature: https://fontawesome.com/how-to-use/svg-with-js#layering

Closing here
