### ISSUE TITLE
Icons on <button> and <input> elements, such as form submit buttons.

### ISSUE THREAD

**Issue by localjo** [FortAwesome/Font-Awesome#580]
Forgive me if I'm missing something obvious, but it doesn't seem that there is a way to use Font-Awesome icons on <button> elements or input elements such as a true submit button. Of course, using a tags when possible is one solution, but the CMS I am using requires inputs to submit the form. Since Font-Awesome adds the icons via pseudo elements, icons won't work on an input. I thought about figuring out which unicode character maps to which icon, and then just setting the button font to Font-Awesome, but I need text on the button as well.

Is there a solution to this?

**Comment by dperrymorrow** [comment]
well using a button to submit a form is not supported in any version of IE
http://caniuse.com/#search=button
is there any work around?

**Comment by KOTRET** [comment]
@dperrymorrow: of course IE supports a button as submit element. You are talking about the form-attribute (which could be used to place a submit button outside the `<from>` — this has nothing to do with this 3 year old issue. Stop waking up zombies :grin:
