### ISSUE TITLE
Icon request: fa-scroll

### ISSUE THREAD

**Issue by schell** [FortAwesome/Font-Awesome#5805]
The files* icons are great. It would also be great to have document-like icons to represent things that aren't necessarily files or ops on files like "view logs" or "list ingredients". I think a scroll icon would be awesome for this. It's "squishier" than a file and could also be great for fantasy games.

Here are some examples:
<img src="https://cdn0.iconfinder.com/data/icons/16x16-free-toolbar-icons/16/62.png" />
<img src="https://cdn2.iconfinder.com/data/icons/crystalproject/Open-Office-Icons/lc_starshapes.horizontal-scroll.png" />
<img src="https://cdn2.iconfinder.com/data/icons/iconza/iconza_32x32_000000/script.png" />

**Comment by schell** [comment]
And thanks for making fontawesome! :+1:

**Comment by tuxy** [comment]
+1, here is another example

![ico](https://camo.githubusercontent.com/e0f15b5b8f03b3c5cbe4a923aeddb540f67e2e9b/687474703a2f2f692e696d6775722e636f6d2f486179674179502e706e67)

**Comment by zverevalexei** [comment]
+1

**Comment by tagliala** [comment]
sorry, this is a duplicate of #1173 


Closing here
