### ISSUE TITLE
<i class="icon-home"></i> new code is not  working your old code is <i class="fa fa-home"></i>

### ISSUE THREAD

**Issue by Waseem-Jutt** [FortAwesome/Font-Awesome#5808]
<i class="icon-home"></i> new code is not working your old code is <i class="fa fa-home"></i> is working fine I'm useing your live link. Please check or change this code i waste my 30 min on this code <i class="icon-home"></i>

**Comment by tagliala** [comment]
sorry I didn't get this one

**Comment by Waseem-Jutt** [comment]
Now this is okay.. :)

**Comment by tagliala** [comment]
closing here
