### ISSUE TITLE
fa-server not appearing on my website

### ISSUE THREAD

**Issue by rileylloyd24** [FortAwesome/Font-Awesome#5809]
When implementing `<i class="fa fa-server"></i>` in my website the icon does not appear. Every other Icon from Font-Awesome works however. Is this broken for anyone else or just me?

**Comment by LauritzT** [comment]
What version are you using? ```fa-server``` was implemented in FontAwesome 4.3.
You'll need to upgrade if you have a lower version.

**Comment by rileylloyd24** [comment]
Therein lies the problem.... what a rookie error. Assumed the version I had been using was still current.

**Comment by EduardoSaverin** [comment]
Still not working in version 4.7.

**Comment by tagliala** [comment]
@EduardoSaverin 
Please check our Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
