### ISSUE TITLE
Icon request: fa-project, fa-goal, fa-milestone, fa-task, fa-issue, fa-deadline

### ISSUE THREAD

**Issue by ahmerkureishi** [FortAwesome/Font-Awesome#5810]
May I request a bunch of icons to represent project management concepts - call them web application icons. Some of these have been already requested singly and most can be hacked from existing icons via stacking, but nothing really beats a cohesive set done from the ground up. 

In parting, kudos all around for this truly awesome project.

**Comment by CompVert** [comment]
Agree: Using these a lot in my web application prototypes, but not available in fontawesome.

for example:

fa-milestone
![milestones](https://cloud.githubusercontent.com/assets/11308995/6479613/d4b6c13c-c250-11e4-8e18-83194e2be24b.png)

**Comment by tagliala** [comment]
sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field

please +1 #3151 for milestone

closing here

**Comment by ahmerkureishi** [comment]
Fair enough - guess I failed to realize that would apply to it.
