### ISSUE TITLE
Icon request: Outline versions of arrow-left, arrow-right, ...

### ISSUE THREAD

**Issue by jkufner** [FortAwesome/Font-Awesome#5813]
```
Icon request: arrow-left-o
Icon request: arrow-right-o
Icon request: arrow-up-o
Icon request: arrow-down-o
```

Good morning,
please add outline versions of simple arrows `arrow-left`, `arrow-right`, `arrow-up` and `arrow-down`. Sometimes the current filled versions are too heavy for a page design. Outline versions will also allow nice hover effect when combined with filled version.

The outline arrow should have exactly the same shape as filled version, only without filling. Just like `comment` and `comment-o`, or `bell` and `bell-o` do.

Thank you!

**Comment by JoyaZhou** [comment]
Same request. And please also add outline versions of following icons too
Icon request: caret-left-o
Icon request: caret-right-o
Icon request: caret-up-o
Icon request: caret-down-o,
Thanks!

**Comment by jlreymendez** [comment]
:+1:

**Comment by fedemoretti** [comment]
+1

**Comment by volpejoaquin** [comment]
+1

**Comment by sensibleworld** [comment]
I believe this request is covered with our `regular` and `light` styles in Font Awesome Pro.
