### ISSUE TITLE
Icon Request: fa-hand-pointer

### ISSUE THREAD

**Issue by LukasDadej** [FortAwesome/Font-Awesome#5816]
![hand-pointer](https://cloud.githubusercontent.com/assets/2370041/6427034/35dbab6a-bf74-11e4-9bd0-7856229b54c0.jpg)

Hello everyone.

Many thanks to all of you for a such great tool as the Font-awesome!

We would like to add a classic hand pointer icon from Windows and used it in Photoshop to enhance the clickable area.

Thank you for your response, Lukas Dadej - CEO of JoomLabs s.r.o.

**Comment by tagliala** [comment]
Added in 4.4.0 

Closing here :)
