### ISSUE TITLE
Icon Request: Music Off / Sound Off (with slash) / Sound Off (with X)

### ISSUE THREAD

**Issue by Stexe** [FortAwesome/Font-Awesome#5817]
Looking for two icons that match the ones already in the set for Music and Sound. But specifically versions of those with either a slash going through them (to indicate off) or a circle and slash ("no" symbol). Also, a "sound off" icon with an "X" coming out instead of waves that matches the same size would be great too.

**Comment by tagliala** [comment]
duplicate of #288, please +1 that request

closing here

**Comment by Stexe** [comment]
Only one of the requests is a duplicate of #288 Shouldn't the others still be fine?
