### ISSUE TITLE
Icon request: 360 view / panoramic view

### ISSUE THREAD

**Issue by NickNZ01** [FortAwesome/Font-Awesome#5820]
Looking for a 360 view / panoramic view icon. Has been by requested her before by someone, unfortuante after the one post its gone cold. Someone wants to help me out? 

I have attached two excamples, the 360 view excample is my preferred one as it includes 'view'...

![360 view](https://cloud.githubusercontent.com/assets/7350375/6429311/12459b74-c02e-11e4-9b47-2fc0f23ea9ce.jpg)
![360 icon](https://cloud.githubusercontent.com/assets/7350375/6429312/13bb0994-c02e-11e4-93da-862e8c8d4cd5.jpg)

**Comment by LauritzT** [comment]
```fa-street-view``` is a pretty good alternative.

**Comment by Souldat** [comment]
+1

**Comment by web-style** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by XmlmXmlmX** [comment]
+1

**Comment by ccharlton** [comment]
+1

**Comment by UXDesignerNL** [comment]
+1

But without the 360º text in it

**Comment by Krxon** [comment]
+1

**Comment by gmtju52** [comment]
360 view is different to a panorama view
i like to have any like this:
https://goo.gl/images/hpaCgi
or try https://www.google.de/search?q=panorama+icon

**Comment by weinde** [comment]
So still no 360° icon... this is just sad FA team... :(

**Comment by majestica** [comment]
+

**Comment by Krxon** [comment]
+100

**Comment by ChriStef** [comment]
So to be clear on this does it plain to do it?

**Comment by XmlmXmlmX** [comment]
> opened this issue on 1 Mar 2015

🤣

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This request is a duplicate of #772, please add a 👍  reaction to that request.

Please make sure you [search existing requests](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new ones

Closing here

**Comment by elimartin** [comment]
+1
