### ISSUE TITLE
RSS ICON for Blogger

### ISSUE THREAD

**Issue by ctnei** [FortAwesome/Font-Awesome#5821]
First, let me say thanks so much for that enormous and amazing work that you are doing. 

My suggest is about adding a new icon to the list, that may be included for users of Blogger social network. 
![social_icon_blogger_48x48](https://cloud.githubusercontent.com/assets/11260202/6432509/71dc5bc4-c054-11e4-8b9a-cd10eb249020.png)

**Comment by tagliala** [comment]
duplicate of #1088 , please +1 that request

closing here
