### ISSUE TITLE
Icon Request: fa-keybase

### ISSUE THREAD

**Issue by dnno** [FortAwesome/Font-Awesome#5822]
I'd like to use the keybase.io favicon to link to my keybase profile on my webpage, would be great if you could add it!

![keybase-io](https://cloud.githubusercontent.com/assets/2003552/6433305/887b3618-c06b-11e4-9d87-54446de5195f.png)

**Comment by kirelagin** [comment]
#4095

**Comment by tagliala** [comment]
@kirelagin thanks

closing here
