### ISSUE TITLE
Icon request: Aperture

### ISSUE THREAD

**Issue by hhiru** [FortAwesome/Font-Awesome#5824]
I noticed a lack of photography icons in the archive of FontAwesome. What I was looking for it's an Aperture icon similar to the Picasa logo. Something like this: <img src="http://cdn.shopify.com/s/files/1/0080/8372/products/tattly_jason_santa_maria_aperture_web_design_01_large.jpg">.
I think that it would help who wants to include Exif data with a nice look or who simply wants a nice Picasa icon!

**Comment by tagliala** [comment]
duplicate of #1033, please +1 that request and post there your example

closing here

**Comment by lucaskatayama** [comment]
+1
