### ISSUE TITLE
Icon request: icon-needle

### ISSUE THREAD

**Issue by Vivalldi** [FortAwesome/Font-Awesome#5825]
![thread-needle](https://cdn0.iconfinder.com/data/icons/sewing-and-taylor/78/sewing_taylor-15-128.png) I was hoping to use implement a sewing needle and thread icon in a quilting website I am making for a client. The color scheme is very close to the [Deliver site](http://demo.getgrav.org/deliver-skeleton/) which already incorporates Font Awesome icons.

**Comment by G-Driver** [comment]
+1

**Comment by Vivalldi** [comment]
I have an svg if needed.

**Comment by xtina** [comment]
+1

**Comment by chelseywilson** [comment]
👍

**Comment by richrawlings** [comment]
👍

**Comment by Mativve** [comment]
+1

**Comment by ryanburnett** [comment]
👍

**Comment by hamzadiaz** [comment]
+1

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🪡 [U+1FAA1](https://emojipedia.org/emoji/%F0%9F%AA%A1/) Sewing Needle
