### ISSUE TITLE
Icon request: gym or exercise

### ISSUE THREAD

**Issue by mubassirhayat** [FortAwesome/Font-Awesome#5826]
I am developing this new website for a gym and i need this icon if you can create one.

![](http://images.all-free-download.com/images/graphiclarge/hotel_icon_has_gym_115729.jpg)

**Comment by tagliala** [comment]
does #1500 fit your needs?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/dumbbell?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
