### ISSUE TITLE
Icon Request: fa-EU

### ISSUE THREAD

**Issue by xterr** [FortAwesome/Font-Awesome#5831]
http://europa.eu/about-eu/basic-information/symbols/images/flag_yellow_high.jpg

Thank you

**Comment by G-Driver** [comment]
+1

**Comment by timint** [comment]
+1

**Comment by timint** [comment]
SVG
[eu stars.zip](https://github.com/FortAwesome/Font-Awesome/files/105454/eu.stars.zip)

**Comment by G-Driver** [comment]
@timint tnx nice one

**Comment by timint** [comment]
You can open the SVG with Inkscape if you need to edit it.

**Comment by leribol** [comment]
+1

**Comment by tagliala** [comment]
Closing here for the same reason of #1336
