### ISSUE TITLE
Icon Request: fa-icecream + other food icons

### ISSUE THREAD

**Issue by thomps** [FortAwesome/Font-Awesome#5832]
Putting in a request for what seems to be a forgotten icon set.  I went searching for a couple in particular (ice cream cones, chocolate / candy bars, etc.) and was completely stumped.  Looking to use this for a chocolate factory site I'm currently working on, but have had a need in the past for things like fruits, bread, loafs and slices etc.  

Just a thought, not expecting much from this but maybe if there is enough interest something might happen.

Cheers!

**Comment by tagliala** [comment]
ice-cream is a dup of #1988 , please +1 that request

about other food icons i need to close this request, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

More info here: https://github.com/FortAwesome/Font-Awesome/issues/966#issuecomment-72334759
