### ISSUE TITLE
Icon request: fa-reject

### ISSUE THREAD

**Issue by CompVert** [FortAwesome/Font-Awesome#5838]
It would be nice to have a reject/uncheck button.

![rejectred](https://cloud.githubusercontent.com/assets/11308995/6479568/f5cda346-c24f-11e4-9cf2-18cd76eb2a8e.png)

This would be a nice icon to uncheck/cancel.

**Comment by jeroenkruis** [comment]
Does [times](http://fortawesome.github.io/Font-Awesome/icon/times-circle/) not suit your needs?

**Comment by CompVert** [comment]
Ohh boy, totally overlooked that one :)

**Comment by victorraji** [comment]
<b-icon icon="times" type="is-danger"></b-icon> deosn't seem to work @jeroenkruis @CompVert
