### ISSUE TITLE
Icon request: Slot Machines

### ISSUE THREAD

**Issue by mika76** [FortAwesome/Font-Awesome#5839]
Please could you make an icon (or a couple of variations) of slot machines.

I'd like to use them as base images with overlays on - like add slot machine to db, remove, etc.. also slot machine responding, not responding.

Something like this maybe 
![](https://cdn3.iconfinder.com/data/icons/casino-and-gambling/80/Casino_and_gambling_icons-16-512.png) 

but could also be like a bunch of 7's like 
![](http://previews.123rf.com/images/smarques27/smarques271401/smarques27140100006/25280468-Slot-Machine-Vector-Illustration-Stock-Vector.jpg) 
(although I think the first one is better)

A couple of variations would be absolutely awesome, and maybe one with a door open (can't seem to find other icon of this but a picture follows) 
![](https://uwaterloo.ca/gambling-research-lab/sites/ca.gambling-research-lab/files/uploads/images/march-2009-slot-machine-002-225x300.jpg)

This would be an ideal variation on the standard slot icon.

**Comment by tapastwain** [comment]
+1

**Comment by dcy** [comment]
I want this icon too.

**Comment by MaorBenAmi** [comment]
+1
Any news?

**Comment by aethior** [comment]
Hi @mika76,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/slot-machine

Regards.

cc/ @tagliala

**Comment by mika76** [comment]
Oh Awesome! Thanks a lot!
