### ISSUE TITLE
request icons for each area of a house.

### ISSUE THREAD

**Issue by Yaboe** [FortAwesome/Font-Awesome#5844]
Bathroom - Shower, bath or toilet?
Basement - T.V. & a Couch?
Sunroom or Addition - have a small room attached to the house icon?
Renovations - House with a hammer?

I'm already using these icons. 
Kitchen - there's a fork and knife icon.
Bedroom - there's a person sleeping in bed icon

I'm working on a property management website and I'm sure there isn't a large demad for the specific icons I'm looking for. But the ones I've requested can be used for property management and real estate.

**Comment by tagliala** [comment]
bathroom: please +1 #708 
basement: please +1 #368  or #759 or both :)
renovations: you could +1 #736 

sunroom or addition... could you please provide an example suitable for 14px icon size?

**Comment by Yaboe** [comment]
First, thanks for the amount of awesome icons you've already created AND for always having such quick response time.   

Here is an image I made for Home Additions.
![home-addition](https://cloud.githubusercontent.com/assets/11296543/6509254/27fe564e-c32c-11e4-960e-354d0e9d17ea.jpg)

I just started working on a renovation site and here is where I'll be using the icons. http://cornerstonecustomrenovations.com/?page_id=91
Might give you a better idea of what I'm asking for.  Also I did add +1 to the links you gave me in the previous message.  Thanks for the direction.

**Comment by mariomeyrelles** [comment]
+1

**Comment by tagliala** [comment]
The example will hardly fit 14px icon size.

We need also a better title for this request... "home addition" is quite abstract

Btw since those icons are related to a very specific field, I should suggest you tu customize fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Maybe there are other icon sets out there specific to your field

**Comment by laviku** [comment]
+1 for bathroom

**Comment by tagliala** [comment]
Sorry, I need to close this one

bathroom: please +1 #708 
basement: please +1 #368 or #759 or both :)
renovations: you could +1 #736

if there are other icons, please open new individual requests

I know they all count for your use case but comprehensive requests does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
