### ISSUE TITLE
Icon Request: fa-tripadvisor

### ISSUE THREAD

**Issue by dnadesignstudio** [FortAwesome/Font-Awesome#5845]
Hello, first THANK YOU for Font Awesome is a super great project!! It saves a lot of time and the results are awesome! 

I don´t want to bug too much, but i want to know if you can add in a future update the tripAdvisor logo..  I think will be a great icon for hotels, hospitality and restaurant websites around the world.

Im attaching the png and also i found the SVG file here:
https://www.iconfinder.com/icons/415887/brand_tripadvisor_icon#size=128

Thank you in advance, Congratulations for your awesome work from Argentina.

Cristian 

![tripadvisor](https://cloud.githubusercontent.com/assets/8169445/6487409/c42c4e08-c26f-11e4-8f8f-3a1ba81c57ba.png)

**Comment by dnadesignstudio** [comment]
Sorry, it was already created.

**Comment by tagliala** [comment]
don't worry. trip advisor is planned for 5.0.0 but I can't guarantee it will be implemented

**Comment by dnadesignstudio** [comment]
Tante grazie Tagliala!!!

**Comment by jorwesflow** [comment]
+1
