### ISSUE TITLE
Facebook icon aren't rendering on Firefox

### ISSUE THREAD

**Issue by helloncanella** [FortAwesome/Font-Awesome#5846]
I'm trying to rendering fa-facebook-square and fa-facebook.

Both doesn't work on Firefox. This trouble doesn't occur in the Google chrome.

It is important to add that others icons in the latter browser are rendering perfectly.

**Comment by helloncanella** [comment]
Solved problem. Conflict with adblock plus.

**Comment by tagliala** [comment]
:+1:
