### ISSUE TITLE
icon request: star-*-sharp

### ISSUE THREAD

**Issue by creativeautomaton** [FortAwesome/Font-Awesome#5848]

**Comment by tagliala** [comment]
the request is valid. Could you please provide a use case different from star?

**Comment by creativeautomaton** [comment]
I want a star that just uses a sharper edge without bending at the points so that the effect is more a stern look rather than a flying Disney escapade. Thoughts?

**Comment by tagliala** [comment]
Thanks, Fair**y** enough. Labeling as enhanchement and new-icon

In any case, I should suggest you to take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/star-sharp?s=solid
