### ISSUE TITLE
Icon request: icon-stopwatch

### ISSUE THREAD

**Issue by jasonhibbs** [FortAwesome/Font-Awesome#585]
Clocks are useful, but sometimes you just want to talk about speed rather than time.

**Comment by jaznz** [comment]
Second this: clock suggests setting a time or time to finish - stopwatch to indicate setting a countdown/timer

**Comment by numediaweb** [comment]
this is related to this issue; https://github.com/FortAwesome/Font-Awesome/issues/1340

**Comment by tagliala** [comment]
closing this one in favour of #1340 which has more +1s

No need to +1 #1340
