### ISSUE TITLE
Newbie here

### ISSUE THREAD

**Issue by Tim43** [FortAwesome/Font-Awesome#5853]
How do I place this code <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
in my Wordpress CSS. I have found CSS and placed it in there and nothing happens. Any help would be appreciated. Just want to replace the icons on the template.

**Comment by tagliala** [comment]
Hi,

you should consider stackoverflow for support request

Sorry, I need to close this one but anyone is free to keep commenting
