### ISSUE TITLE
Icon request: icon-a1, icon-a2, icon-a, icon-b, icon-c (driving licenses)

### ISSUE THREAD

**Issue by catrgna** [FortAwesome/Font-Awesome#5855]
Hello,

I need the following char/char&digit combination as icon. It is related to driving license categories:
A1
A2
A
B
C1
C

or if you can explain me how to make them (because it is actually just digits and chars)?

Thanks in advance

**Comment by tagliala** [comment]
take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

hope it helps

**Comment by catrgna** [comment]
Hi,

I checked them all. They're pure symbols.

I just needs icons that are made as an combination of letter and digit. I.e. A1, A2, A, B, C

**Comment by tagliala** [comment]
if you only need  A1, A2, A, B, C, please rename this thread to icon-a1, icon-a2, icon-a, icon-b, icon-c giving use cases (why those icons are important?) and I will reopen this request

thanks!

**Comment by catrgna** [comment]
Hi,

These icons I will use for driving school categories. I could just create picture i.e. A1 but fontawesome icons look way better.

I need the following 5 icons (A1, A2, A, B and C). Below is short explanation for each icon. You can also create icons for all driving licence categories (picture https://assets.digital.cabinet-office.gov.uk/government/uploads/system/uploads/image_data/file/1155/Card_02_960x640_02.jpg)
It would be useful for everyone.

icon_a1 => A1 
(this category defines light motorbike with an engine size up to 125cc)
icon_a2 => A2
(this category defines motorbike with power output up to 35kW)
icon_A => A
(this category defines motorbike with a power output more than 35kW)
icon_B => B
(we all know what it this :dancer: )
icon_C => C
(this category defines large vehicles over 3,500kg (with a trailer up to 750kg))

**Comment by tagliala** [comment]
Much clearer now, thanks!

Reopening

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
