### ISSUE TITLE
Icon request: fa-application

### ISSUE THREAD

**Issue by elliot100** [FortAwesome/Font-Awesome#5857]
It struck me that while there are quite a few icons for particular applications, there is no icon to represent a generic application.

Perhaps something like this:
![image](https://cloud.githubusercontent.com/assets/3186037/6513525/8cf84a0e-c373-11e4-882b-f3a929411c44.png).

**Comment by tagliala** [comment]
dup of #3585, please +1 that request

**Comment by elliot100** [comment]
Sorry for taking your time, I should have found that.

**Comment by tagliala** [comment]
don't worry, I'm here to help
