### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by jmpellizzer** [FortAwesome/Font-Awesome#5858]
Hi everyone,

I want to do a icon (as a font-awesome icon) with this image, how can i proceed?
This icon i want to use in my website.

(https://cloud.githubusercontent.com/assets/8460590/6514369/da49578e-c379-11e4-8048-8ce08636e3df.png)

**Comment by tagliala** [comment]
Hi, you need a proper .svg file. Then take a look at this wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by aethior** [comment]
Hi @jmpellizzer,

This icon was added in v5.4.0.
Check https://fontawesome.com/icons/pig

Regards.

**Comment by tagliala** [comment]
Thanks, but I'm closing here because properly titled and labeled requests are available at #14057 #13404
