### ISSUE TITLE
Icon Request: icon-chat

### ISSUE THREAD

**Issue by TraicionCraft** [FortAwesome/Font-Awesome#5863]
Add a icon chat!
![](https://lh3.googleusercontent.com/-twnar3yX1zA/AAAAAAAAAAI/AAAAAAAAAA0/8Nsc4Txh4kI/photo.jpg)

**Comment by tagliala** [comment]
hmmm... I think http://fontawesome.io/icon/comment/ http://fontawesome.io/icon/comments/ http://fontawesome.io/icon/comment-o/ http://fontawesome.io/icon/comments-o/ are enough to represent a chat

Moreover, there is a request for a "subtitle" that is almost identical to this request #5754 

I'm going to close this one, but I could reconsider it later
