### ISSUE TITLE
Mobility icon set suggestion

### ISSUE THREAD

**Issue by princeofnaxos** [FortAwesome/Font-Awesome#5868]
I would like people to vote for a "Mobility" icon set. In the set, I would like to see icons that have to do with transportation, such as:

- different means of transportation (car, train, bus, bicycle, motorcycle, walking, hiking, etc.)
- icons for passenger, such as seat, 'passenger in a seat' (with/without seat belt), suitcase, etc.
- icons for restaurant, gas station, airport, rail road crossing, shopping mall, etc.

Any other suggestions are welcome!

Edwin

**Comment by tagliala** [comment]
Sorry but I can't keep this open

As per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Some icons you are asking for are already here (car, train, bus, suitcase and others), others are duplicates of existing requests (e.g.: #5658 , #1676 )

If you want to request individual icons it's fine for us, but please search for duplicates before and provide an example where needed (airport? shopping mall?)

Closing here
