### ISSUE TITLE
Icon Request: fa-ups

### ISSUE THREAD

**Issue by tarranjones** [FortAwesome/Font-Awesome#5870]
fa-ups : dark shield 
fa-ups-o : light logo
fa-ups-official : defaults with UPS color:#hex !important;

use case : Used on eCommerce sites to show which couriers are available
js use case :  when selected change form fa-ups-o to fa-ups-official 

or 
fa-courier-ups . . .

 If other couriers are added the I think they should be prefixed with fa-courier-
e.g. ( fa-courier-ups, fa-courier-fedex, fa-courier-tnt, fa-courier-dhl, fa-courier-yodal, fa-courier-apc, fa-courier-dpd)
You can only request one icon/strictly related icons at a time so this is for  ups only

**Comment by tagliala** [comment]
subset of #1502

**Comment by moeiscool** [comment]
over +9000

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/ups?style=brands
