### ISSUE TITLE
Icon request: icon-visual-studio

### ISSUE THREAD

**Issue by ChintsBilly** [FortAwesome/Font-Awesome#5871]
![flurry_ios_visual_studio_2012_replacement_icon_by_flakshack-d5nnelp 1](https://cloud.githubusercontent.com/assets/11349572/6525174/5ea0773e-c428-11e4-8111-0e39e67dc135.png)
Icon is related to Microsoft technologies for building apps.  Named is Microsoft Visual Studio.

I am a web developer and I need to show icon of the same to display my users that we are developing apps on this technology.

Please make it. Thanks in advance :)

**Comment by tagliala** [comment]
duplicate of #1940, please +1 that request

closing here
