### ISSUE TITLE
Icon request volume-medium

### ISSUE THREAD

**Issue by SGr33n** [FortAwesome/Font-Awesome#5872]
Hi,

FontAwesome are awesome :) As I can se would be useful to have a volume-medium icon. The 3 volume icons are:
1) without bars (mute);
2) with just one bar (volume down);
3) with three bars (volume up)

What do you think about adding a medium one with two bars?

Thank you in advance :)

**Comment by tagliala** [comment]
duplicate of #1341, please +1 that request

closing here
