### ISSUE TITLE
Icon Request: fa-web

### ISSUE THREAD

**Issue by dianahall** [FortAwesome/Font-Awesome#5874]
Hi All,

I work at an app development studio. We develop both native and web apps and often times have to explain the difference to customers. It would be nice to have a "web" icon on Font Awesome to use on our site.

![webicon](https://cloud.githubusercontent.com/assets/5247079/6535241/14e57730-c409-11e4-99d1-b27322294b73.png)

**Comment by tagliala** [comment]
duplicate of #2655 , please +1 that request

closing here
