### ISSUE TITLE
Icon Request: fa-play-circle-o-thin

### ISSUE THREAD

**Issue by seadroe** [FortAwesome/Font-Awesome#5876]
Would love to have a play icon to match fa-circle-thin. The current fa-play-circle-o is just a little chunky for some of my designs. A thin version would work much better combined with the thin chevrons (fa-angle-right, etc.) In fact, it would be great to have a thin version of all icons with -circle-o. Thank you, love the font set!

**Comment by nickturrietta** [comment]
I second this!

**Comment by tagliala** [comment]
I'm sorting out some old requests.

Since circle thin has been aliased to circle, I think this icon is available:
- https://fontawesome.com/icons/play-circle?style=regular

We also have a light style in FA Pro:
- https://fontawesome.com/icons/play-circle?style=light
