### ISSUE TITLE
Deviantart icon not working in 4.3.0

### ISSUE THREAD

**Issue by lillereven** [FortAwesome/Font-Awesome#5879]
Works fine in 4.2.0

4.2.0 shows:
![fa420](https://cloud.githubusercontent.com/assets/4401070/6541889/90d21a42-c4a4-11e4-9c79-712ce0a2ddeb.png)

4.3.0 shows:
![fa430](https://cloud.githubusercontent.com/assets/4401070/6541887/90d09dfc-c4a4-11e4-9d46-0bb842744a79.png)

Same markup. CSS served from MaxCDN.

**Comment by Jonno** [comment]
Same with fa-linkedin

**Comment by Techokami** [comment]
4.3.0 updated the deviantArt icon to show the new official dA logo. As ugly, abstract, and broken as it looks, that is rendering correctly. Perhaps the old dA icon could be preserved as deviantart-old?

**Comment by lillereven** [comment]
It would appear that you are indeed correct. My apologies. Please close this issue.

**Comment by tagliala** [comment]
@Techokami thanks

Refers to #5137

Closing here

@Jonno please open another issue and explain what's wrong with linkedin, thanks
