### ISSUE TITLE
Fuzzier Icons Now

### ISSUE THREAD

**Issue by lhealey77** [FortAwesome/Font-Awesome#5880]
I've noticed that a least several icons, like refresh & eye are not nearly as sharp as they were in earlier versions. I've switched back to 4.1 from 4.3 because of this.
I'm using the hosted version...
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css">
Is it me?

**Comment by tagliala** [comment]
it may not be you. Metrics in 4.3 changed. Please provide more information, or better, a fiddle showing this issue:

You can use the following ones as base
4.3.0: -> http://jsfiddle.net/tagliala/e9yfxsfj/
4.1.0: -> http://jsfiddle.net/tagliala/1eerp46s/7/

**Comment by lhealey77** [comment]
I have posted both in your fiddles...

 

I notice that the fuzzy effect is more noticeable with smaller font sizes

**Comment by tagliala** [comment]
sorry could you please provide link to your updated fiddles?

PS: note that pixel perfection is guaranteed only at 14px icon size and multiples. We cannot guarantee pixel perfection at 16px, 12px, 10px etc.

**Comment by lhealey77** [comment]
I just updated the fiddles you sent

 

You can use the following ones as base
4.3.0: -> http://jsfiddle.net/tagliala/e9yfxsfj/
4.1.0: -> http://jsfiddle.net/tagliala/1eerp46s/7/

**Comment by tagliala** [comment]
@lhealey77 

please after clicking on "update" copy & paste the new link. It will add a number. The above fiddles are pointing to my versions

**Comment by lhealey77** [comment]
Got it, sorry 


4.3.0: -> http://jsfiddle.net/e9yfxsfj/5/


4.1.0: -> http://jsfiddle.net/1eerp46s/8/

**Comment by tagliala** [comment]
Which browser and os are giving you this issue?

No problems here (OSX 10.10.2 - Firefox/Chrome/Safari - 4.3.0 renders better on firefox)

**Comment by lhealey77** [comment]
I might add that most of the icons seem to render fine, but the circular ones like fa-refresh appear to be the worst

 

Mainly use FF v36.0.1

Chrome                41.0.2272.76

Win 7 

 

Just noticed that the fiddle of 4.3 viewed in Chrome looks much better than it does views in FF.

 

Also here's a page, not a fiddle but when viewed in Chrome still doesn't look a sharp as it did in 4.1.

 

toptexasprospects.com/testpages/fontawesome-fuzzy-icons.html

**Comment by tagliala** [comment]
Please add `font-size: 14px` to your stylesheets, as I said pixel perfection is not guaranteed at any size

**Comment by tagliala** [comment]
Closing here but feel free to comment

**Comment by tagliala** [comment]
Note that if 4.1.0 renders better at your font size, you can still use 4.1.0
