### ISSUE TITLE
Icon Request: fa-stairs

### ISSUE THREAD

**Issue by spectrumcommerce** [FortAwesome/Font-Awesome#5881]
I have needed a set of stairs, either with a person or without.  Another option would be fa-ascending and fa-descending  Thanks for the awesome icons!

**Comment by G-Driver** [comment]
+1

<img src="http://images.clipartpanda.com/stair-clipart-stair-up-hi.png">

**Comment by LeoMagee** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by wstow** [comment]
+1

**Comment by grumbleman** [comment]
+1

**Comment by richnicholls404** [comment]
+1

**Comment by cornflowerdesign** [comment]
+1

**Comment by showplans** [comment]
+1

**Comment by aethior** [comment]
I suggest to use ISO graphical symbols.

![pictograms](https://cloud.githubusercontent.com/assets/1769227/11912260/74102aa2-a635-11e5-9268-dab92fac3770.png)

`fa-stairs`
`fa-escalators`
`fa-stairs-ascending`*
`fa-stairs-descending`*
`fa-escalators-ascending`*
`fa-escalators-descending`*

*Maybe it's not necessary create ascending and descending icons using icon overlays #1181.

**Comment by wscribner** [comment]
+1

**Comment by thangbn** [comment]
+1

**Comment by Kaizeras** [comment]
+1

**Comment by rjpadula** [comment]
+1

**Comment by ImanimalXI** [comment]
+1

**Comment by J00nz** [comment]
+1

**Comment by pickerflicker** [comment]
+1

**Comment by djmj** [comment]
+1

**Comment by mistajolly** [comment]
+1 Stairs/escalator (And also fa-door!)

**Comment by gitzrulz** [comment]
+1

**Comment by alekbless** [comment]
+1

**Comment by suaterenler** [comment]
+1

**Comment by phchung** [comment]
+1

**Comment by vulong23** [comment]
+1

**Comment by sarahtotally** [comment]
+1

**Comment by ef32** [comment]
any update on this?

**Comment by edwinharly** [comment]
+1

**Comment by gabrielemaffoni** [comment]
+1

**Comment by mardoqueo** [comment]
+1

**Comment by cwarrenmitchell** [comment]
Yes, please!

**Comment by josefdebnar7** [comment]
+1

**Comment by ZesteDesign** [comment]
++1

**Comment by pesta** [comment]
+1

**Comment by liudas-stonys** [comment]
4 years already. Does anyone give a fuck? :D

**Comment by tagliala** [comment]
@liudas-stonys we do!

Please take a look at our [New Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), there is a lot of information on how requests work

> ### Why are icons requests from 2013 still open?
> Up until a year and a half ago or so, Font Awesome was a labor of love that was done during the free time of mostly one person, our co-founder Dave. While Dave was able to bring Font Awesome to include hundreds of icons, he also had commitments like a full-time job and family that meant he couldn’t tackle everything.
> 
> Since the team has grown and we’ve released Font Awesome Version 5, we’ve picked up the pace. Not only have we added two unique styles, but in 2018 alone, we added over 2,500 new icons.
> 
> If a request seems old, dusty, and not addressed, it’s because it hasn’t fit into our roadmap of categories and subjects to include nor has it gathered enough community enthusiasm and votes to warrant it to be added yet. You can help with that by getting more reactions and 👍 !

PS: I've edited your comment

**Comment by codyreed** [comment]
+1

**Comment by Ocean97Li** [comment]
+1

**Comment by tedaldisarce** [comment]
+1

**Comment by vegardonproperty** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in the latest alpha release of v6: https://fontawesome.com/download
