### ISSUE TITLE
Yaml Feed not in valid format?

### ISSUE THREAD

**Issue by ajbrun** [FortAwesome/Font-Awesome#5887]
Hey,

I've seen requests for a json feed to allow us to do our own searches for icons, but I see you have yaml feed, so I'm using that instead. The only small problem I have with it is the feed doesn't appear to be 100% correct in some places:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/src/icons.yml

If you search for ban (f05e), envelope (f0e0) or windows (f17a), you can see that although they appear to have filters, they don't have a filter heading in the yaml. The effect of this (in my implementation at least) is the created field gets deserialized as "1.0 - delete - remove - trash - hide - block - stop", so rather than storing it as a double as I'd prefer, I'm forced into using a string. This would obviously limit my ability to do my own filters against the icon set for these three instances.

Additionally, I think this may be having the same limitation on the main bootstrap search (assuming it uses the same yml file). For example, if I search for one of the filters assigned to check-circle-o, the icon appears in the search, but if I search for "delete", which is a filter for ban, the ban icon does not appear. The same behaviour is seen for the other two icons that appear to be missing the filter title in the yml.

**Comment by tagliala** [comment]
@ajbrun this is fixed in 4.3.1 branch

If you need to add more filters, please push against 4.3.1 wip branch

sorry for this inconvenience
