### ISSUE TITLE
Cannot use icons for weixin, tencent weibo, qq

### ISSUE THREAD

**Issue by ivyyyyy** [FortAwesome/Font-Awesome#5888]
http://fortawesome.github.io/Font-Awesome/icon/tencent-weibo/
http://fortawesome.github.io/Font-Awesome/icon/qq/
http://fortawesome.github.io/Font-Awesome/icon/weixin/

None of them works. How do I fix it??

**Comment by ivyyyyy** [comment]
http://fortawesome.github.io/Font-Awesome/icon/facebook-square/
http://fortawesome.github.io/Font-Awesome/icon/newspaper-o/
These also don't work.

**Comment by zcxkkk** [comment]
check your font-awesome version. works fine here.

**Comment by zcxkkk** [comment]
![qq photo20150309102853](https://cloud.githubusercontent.com/assets/4636524/6549065/1a667e1c-c647-11e4-9fef-e048283b407e.jpg)

**Comment by zcxkkk** [comment]
btw, Adblock Plus can remove Font Awesome brand icons with their "Remove Social Media Buttons" setting.  check your adblock settings.

**Comment by tagliala** [comment]
can't confirm.

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting and to this issue #1799

**Comment by tagliala** [comment]
closing here but feel free to comment
