### ISSUE TITLE
suggestion: add GSUB rules for universal substitutions

### ISSUE THREAD

**Issue by Pomax** [FortAwesome/Font-Awesome#589]
I'd like to suggest adding GSUB rules for all the entities in your font, so that typing the word "icon-flickr-sign", for instance, is substituted with the icon for it from the private use area by intelligent font engines. That way the font can be deployed in a much wider context, and you don't have to write PUA codepoints yourself, the font will make sure the right thing happens.

**Comment by samrayner** [comment]
Great to hear this is planned for 5.0!

In the meantime, I was able to use the pretty awesome https://icomoon.io/app/ to create a FontAwesome TTF file with ligature support that works like Symbolset.

I just selected all of the FA icons (available as a preset library in the app) and ran this JS in the Inspector to apply the names as ligatures:

```
inputs = document.querySelectorAll('input[placeholder="ligature1, ligature2"]')
changeEvent = new Event('change')
for(var i = 0; i < inputs.length; i++) {
  name = inputs[i].closest('.glyph').querySelector('.glyphName').innerHTML
  inputs[i].value = name
  inputs[i].dispatchEvent(changeEvent)
}
```

Using the generated TTF (included in the attached ZIP) I can type `home` or `file-text-o` and the words get switched out for the associated icon. It makes designing with the font in Photoshop much easier than copy-pasting from the cheatsheet.

@davegandy Icomoon also generated CSS and web-fonts with the ligatures applied (included in the ZIP). I haven't tried out any of the files except the TTF font (as Photoshop was the use case I was interested in) but it might be worth seeing how @Keyamoon has handle ligature support.

[Font-Awesome-Liga.zip](https://github.com/FortAwesome/Font-Awesome/files/56631/Font-Awesome-Liga.zip)

**Comment by Keyamoon** [comment]
@samrayner You could have pressed the "reset" button in the toolbar to set all the ligatures.

For better browser support, IcoMoon generates a script that you could use. If the font fails to load for any reason, the browser would show the name/tag assigned to the icon. See the note here: https://icomoon.io/#docs/ligatures

**Comment by Nektro** [comment]
If you're looking for anymore examples on how this would be used, Material Icons does this with ease. You still import a single css sheet and then use a single class

`<span class="material-icons">build</span>` gives you a 🔧 glyph

**Comment by Arkkimaagi** [comment]
One potential problem with this approach is language support.

**Comment by Pomax** [comment]
@Arkkimaagi go on? font-awesome uses characters from the Latin unicode block for its class names, why would those interfere with any sort of language support?

**Comment by Arkkimaagi** [comment]
It's a minor thing but this is what I'm thinking:

```html
Hide element by clicking the <i class="fontawesome-icon">closed eye</i> icon.
```
If I were to translate this to Finnish, I could not use the direct translation:
```html
Piilota elementti klikkaamalla <i class="fontawesome-icon">suljettu silmä</i> ikonia.
```
Because the icon would not work. I'd have to use something like:
```html
Piilota elementti klikkaamalla <i class="fontawesome-icon">closed eye</i> ikonia.
```
But that would work poorly with VoiceOver as the english text would be read with finnish pronounciation. Neither finnish or english speaker would understand it.

I have not tested this, but like I said, it's a potential problem.

**Comment by Arkkimaagi** [comment]
Also, adding `lang="en"` to the icon would not help much as people usually get really confused if you swap pronounciation mid sentence.

**Comment by Pomax** [comment]
While true, this is not a request to *replace* the current `fa-...` classes, it's a request to *add* GSUB rules. The worst implementation would be to add GSUB rules and then ditch the icon classes, that would make no sense.

So in this case you'd still have the option to just go `Piilota elementti klikkaamalla <span class="icon-only fa-closed-eye">suljettu silmä</span> ikonia.`

I know font-awesome likes to use the `<i>` element, but if you want to do proper content, don't; you're not writing italicised text. Using real sematic markup helps address the issue that screen readers will run into (especially if accompanied by the appropriate ARIA role).

**Comment by Nektro** [comment]
Well as long as people were able to properly correlate the glyphs to the words they needed to produce them, then why would there be a problem with translations?

For example, you cannot go `<span class="fa fa-suljettu-silmä"></span>` as it stands now and still get the closed eye icon.

**Comment by Pomax** [comment]
No, but for screen readers, used by a surprisingly large number of people on the web as a whole, it matters a lot, so if your site has a non-trivial number of users with accessibility needs, you need take @Arkkimaagi's objection into account: using full word substitution is not a good idea there, whereas `<span class="fa fa-closed-eye ghost-text">suljettu-silmä</span>` works perfectly fine, reading out the icon's description in a native language but using CSS to visually hide it on the page.

**Comment by Nektro** [comment]
Well, unless the font fails to load for some unseen network reason, then the replaced text will never be shown to the end user anyways. So the developer is the only one that needs to know the icon replacement ligatures.

**Comment by Arkkimaagi** [comment]
@nektro even if some content is rendered visually differently by some font, the machine text-to-speech program that VoiceOver is sees it as original text just like @pomax said. No matter if the font loads or not.

Font awesome just sent out an email explaining how theyre focusing on usability. The "objection" or more like "observation" I made about the substitution relates to the non-english VoiceOver users. If your site has no translations, it does not apply to your development. 

Just in case this problem should be explained in the documentation if GSUB support is implemented. Its good to hear that the support is considered as an extra feature and not a replacement of the current approach.

**Comment by Arkkimaagi** [comment]
Oh btw, as @nektro mentioned the font loading, wont we get a flash of unformatted text when the icon font is loading? If the icon is inline with text and width is not forced, wont that make the page text jump around quite a bit?

**Comment by Pomax** [comment]
Most certainly, but not moreso than other text that relies on ligatures (which is quite a lot of text that's styled with good webfonts via Typekit etc.)

**Comment by PeterShaggyNoble** [comment]
Another problem I can see with implementing this is when there are variants of an icon.

One example is Facebook, there are currently 3 different icons for that, so people would need some way of specifying which one is used without having to add "non-semantic" text, i.e. the only text that should be contained in the tag is "facebook", without "-official" or "-square".

**Comment by Pomax** [comment]
Why? If you need the right icon, you want precision. In the same way you'd need something like `fa-facebook-square` right now, you would use "facebook-square" and done?

Remember: we're dealing with icons, so the absolute first question you need to ask is "which markup am I using, based on the role this icon plays". If the icon is eye candy only, then it doesn't matter in the slightest what the text is, because no one is going to see that text (only the subtituted icon) and screen readers should absolutely not read them out (for instance, a facebook icon next to a link to a facebook article should not exist as far as a screen reader is concerned. It contributes nothing).

On the other hand, if your icon is heavily semantic, you need to stop and ask yourself why you're using an icon at all. If the text would matter to readers, why are you removing that text and replacing it with a picture that not everyone is going to be able to easily understand, or make out?

By asking the right question before using Font-Awesome, but really *any* icon solution, you won't run into this problem. It's a symptom of a premature implementation.

**Comment by Pomax** [comment]
Closing this issue: I filed this in 2012 - I have no idea whether it's been fixed in the mean time but this issue's been hanging out in my "issues/mentioned" list for years now and with FAv4 I assume full OpenType was taken advantage of.
