### ISSUE TITLE
Icon request: Icon-codeacademy

### ISSUE THREAD

**Issue by codyn329** [FortAwesome/Font-Awesome#5892]
* http://cdn-production.codecademy.com/favicon.ico
* https://d1qb2nb5cznatu.cloudfront.net/startups/i/57028-75249c08760cc9b8331013724066c538-medium_jpg.jpg

**Comment by kwendenarmo** [comment]
+1

**Comment by TheChen5** [comment]
Dupe of #3320
+1 that
:mag:before:heavy_plus_sign:
@tagliala This should be closed

**Comment by tagliala** [comment]
@TheChen5 thanks
