### ISSUE TITLE
Icon Request: fa-fa_version

### ISSUE THREAD

**Issue by markhazlewood** [FortAwesome/Font-Awesome#5897]
Requesting a new glyph that would represent the current version of FontAwesome, being updated in the set with each new release. This would allow a user to paste a single character and immediately know which version they are on.

Use Case(s):
Designer Dave has the FA cheat sheet open for a newer version that doesn't match what he currently has installed (but both have the fa-fa_version icon). Not realizing this, he tries pasting in a glyph from the cheat sheet but gets the placeholder instead. He then finds the version glyph, copies and pastes that in, and realizes he's not on the current version.

![fa-fa_version](https://cloud.githubusercontent.com/assets/11296862/6555632/e3dea35a-c63d-11e4-97da-80c3216f3fd7.png)

**Comment by tagliala** [comment]
refers to #4230 .

I'm against this approach, I would go for a warning

**Comment by markhazlewood** [comment]
Yeah it's kind of related, but I'm not asking for an update to the cheatsheet formatting. To simplify: There's no way to easily see which version of FA I've got installed on my system (that I can see). Typing this self-referencing character would give that info immediately. I'm unclear how a warning could serve this same purpose, except to direct users go through a reinstall process every time they are unsure.

**Comment by kwendenarmo** [comment]
I agree. This actually happened to me and I had to reinstall for not being sure which version was installed.

**Comment by tagliala** [comment]
Font Awesome version number can now be identified from the operating system native applications / control panel

I'm going to close here
