### ISSUE TITLE
Icon request: Half-star-o-alt

### ISSUE THREAD

**Issue by LazyAardvark** [FortAwesome/Font-Awesome#5900]
A half star open alternate icon to the current half star open would be helpful for star rating systems where 1/2 stars are an option and earned vs unearned stars need to be visually distinct. This is beneficial for visually impaired users who may not be able to see a difference in color but can see difference in shapes.
![half-star-o-alt](https://cloud.githubusercontent.com/assets/5081650/6557515/f4fa08c4-c64b-11e4-9baa-6ae479daf9bc.png)

This would be especially beneficial when stacks are used and the half-star and half-star-o-alt icon could be layered on top of the unearned rating icon, such as a circle.
![half-star-o-alt-circle](https://cloud.githubusercontent.com/assets/5081650/6557463/9029f594-c64b-11e4-88ce-7b4a17c838eb.png)

**Comment by yonasrobi** [comment]
:+1:

**Comment by mnsteel** [comment]
:+1:

**Comment by funmibi** [comment]
:+1:

**Comment by ezee0501** [comment]
:+1:

**Comment by sensibleworld** [comment]
We have a couple of options for this now:

https://fontawesome.com/icons/star-half-alt?style=solid
https://fontawesome.com/icons/star-half?style=solid
