### ISSUE TITLE
Icon request: Icon-lego (brand)

### ISSUE THREAD

**Issue by SamanthaNguyen** [FortAwesome/Font-Awesome#5902]
- Image - https://a248.e.akamai.net/cache.lego.com/r/www/r/globalnavigationservices/content/globalnavigation/images/lego-logo.svg
- Usage - To be used on the Brickimedia network / wikifarm (https://brickimedia.org)

**Comment by tagliala** [comment]
refers to #3596

**Comment by SamanthaNguyen** [comment]
Closing as #3596 supersedes this ticket
