### ISSUE TITLE
Icon request: icon-AppStore

### ISSUE THREAD

**Issue by Chempo009** [FortAwesome/Font-Awesome#5904]
I would like to link my developer profile on Apple Appstore so people can see all my apps when they visit my site. Would be cool if in squared version and just 'a' icon. 

![a](https://cloud.githubusercontent.com/assets/4152115/6564151/b29c716e-c6a6-11e4-9660-0ecfcd2bb287.png)

**Comment by tagliala** [comment]
duplicate of #919 , please +1 that request

closing here
