### ISSUE TITLE
Icon request: fa-basketball

### ISSUE THREAD

**Issue by SamanthaNguyen** [FortAwesome/Font-Awesome#5906]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT59_C75T3F7AoO-JRLS3GaT-2XYPrmeiW9-Z4EX1hRCrW9slwKVZjSBw Something like this would be nice, like how there is fa-soccer

**Comment by tagliala** [comment]
#714 is planned for 5.0.0

Please +1 that request but leaving this open

**Comment by SamanthaNguyen** [comment]
Closing as that supersedes this ticket
