### ISSUE TITLE
Icon request: icon-beam

### ISSUE THREAD

**Issue by dmynerd78** [FortAwesome/Font-Awesome#5907]
There's a new live streaming site known as [Beam](https://twitter.com/WatchBeam) that is almost like Twitch. A lot of people I know have been going over to Beam since it has a smaller delay plus they are extremely organized. They plan to add a lot to their API and all around seems like a very good livestreaming site. I'm requesting to add their icon (can be found [here](https://github.com/MCProHosting/beam-resource-kit) so it is easy to implement in their website as well as mine)

**Comment by MCProhosting-Matt** [comment]
+1, thanks for opening this for us. :)

**Comment by dminer78** [comment]
Here's another example of the logo. I'd imagine this should be fairly easy to vectorize:
![beamlogo](https://cloud.githubusercontent.com/assets/7948941/7082421/c083c8f2-df08-11e4-8398-5cfa49074be7.png)

**Comment by njb-said** [comment]
+1, https://github.com/MCProHosting/beam-resource-kit has an official logo pack

**Comment by LukeT** [comment]
+1, beam is awesome.

**Comment by ProfoundGames** [comment]
+1, I really want to use Font Awesome for beam! :+1:

**Comment by noahp78** [comment]
+1 need it for a site

**Comment by 2Cubed** [comment]
+1, would love to see this added. :+1:

**Comment by account3r2** [comment]
+1 (Use: Social media icon links)

**Comment by TheBaconSpace** [comment]
+1 Would Love it to

**Comment by TheBaconSpace** [comment]
if u havent notice @MCProhosting-Matt is Founder of Beam

**Comment by xCausxn** [comment]
+1 This would be useful and much appreciated :D

**Comment by alfw** [comment]
+1 Will this ever be added?

**Comment by EnZedBob** [comment]
+1

**Comment by ChrisVollink** [comment]
Adding another +1. Would love to see

**Comment by KnoxVegas** [comment]
+1 I would love to see this added! Thanks

**Comment by outcast** [comment]
+1

**Comment by HIAviator** [comment]
+1 We need this!

**Comment by drawanew** [comment]
Yes this is needed. I am regularly streaming on beam!

**Comment by mattj456** [comment]
Just a note that Beam is now "Mixer" and correct logos can be found here as of 9/9/2017: https://github.com/mixer/branding-kit

the old "Beam" logos are now obsolete and aren't necessary in FontAwesome

**Comment by sinfuljosh** [comment]
Recommend merging this into #11242

**Comment by tagliala** [comment]
@sinfuljosh are they the same brand or strictly related?

**Comment by matt-t-jones** [comment]
@tagliala they are the same company. Beam was purchased by Microsoft and rebranded as Mixer.

**Comment by sinfuljosh** [comment]
@tagliala Correct and the Beam Logo is no longer used. They use the Mixer logo now.

**Comment by tagliala** [comment]
Ok, thanks for the clarification

Closing here in favour of #11242

Sorry, cannot merge upvotes, please 👍 #11242
