### ISSUE TITLE
Please release 4.3.1

### ISSUE THREAD

**Issue by murnieza** [FortAwesome/Font-Awesome#5910]
4.3.1 contains some important bugfixes. As milestone is already completed can we expect 4.3.1 to be released?

**Comment by tagliala** [comment]
@murnieza your main concern is #5559 ?

**Comment by murnieza** [comment]
@tagliala yes

**Comment by aethior** [comment]
Fixed in v4.4.0.

cc @tagliala.

**Comment by tagliala** [comment]
thanks
