### ISSUE TITLE
icon request-pdf-icon

### ISSUE THREAD

**Issue by atul001** [FortAwesome/Font-Awesome#5911]
hi, i am using font-awesome but PDF icon is not working when i try to add this cheat code in font-awesome.css even then it doesn't works so can you please tell me that how can i do this...

Thanx & Regards:
Atul Pandit

**Comment by tagliala** [comment]
http://fontawesome.io/icon/file-pdf-o/ <-- are you looking for this one?

**Comment by atul001** [comment]
yes i am looking for this, but it is not working the code is also in fontawesome.css but it doesn't show the icon..

**Comment by tagliala** [comment]
@atul001 ok you are probably using an older version of fontawesome

please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

closing here but feel free to comment
