### ISSUE TITLE
Icon request: icon-washing-machine

### ISSUE THREAD

**Issue by donaldating** [FortAwesome/Font-Awesome#5914]

**Comment by G-Driver** [comment]
+1

**Comment by lopezb** [comment]
+1

**Comment by gEndelf** [comment]
+1

**Comment by NKCSS** [comment]
+1

**Comment by dzambuto** [comment]
+1

**Comment by gEndelf** [comment]
+1

**Comment by kimrei** [comment]
+1

**Comment by MarGraz** [comment]
+1

**Comment by AlbertoAbruzzo** [comment]
+1

**Comment by mitchelb** [comment]
+1

**Comment by JooStrappin** [comment]
+1

**Comment by brada1703** [comment]
+1

**Comment by discdiver** [comment]
+1

**Comment by EvgenyVetrov** [comment]
+1

**Comment by wassimbkd** [comment]
+1

**Comment by boodleboutique** [comment]
I would love a set of washing instruction symbols - temperature, no-iron, no tumble-dry, dishwasher safe, dry clean only etc. e.g. http://www.textileaffairs.com/c-common.htm - maybe not all of them, but at least the most common. Linked to issue #9577

**Comment by cyrilfr** [comment]
+1

**Comment by 1ringtorulethemall** [comment]
+1

**Comment by nicdesjardins** [comment]
+1

**Comment by en-geeki** [comment]
+1

**Comment by CheeseStick** [comment]
+1

**Comment by leolandotan** [comment]
+1

**Comment by Irenead** [comment]
+1

**Comment by gietema** [comment]
+1

**Comment by AlaaMJaddou** [comment]
+1

then where is the icon ?!

**Comment by just-webdesign** [comment]
+1

**Comment by CreativeNative** [comment]
+1

**Comment by stefan-meier** [comment]
+1

**Comment by artuso0matteo** [comment]
+1

**Comment by ilyankou** [comment]
+1

**Comment by hackrat** [comment]
+1

**Comment by sensibleworld** [comment]
We've finally realized that wearing the same pair of socks every day was kind of gross, so we decided to do something about it. Font Awesome now includes a few laundry-related icons.

https://fontawesome.com/icons/washer?style=solid
https://fontawesome.com/icons/dryer?style=solid
https://fontawesome.com/icons/dryer-alt?style=solid

**Comment by NKCSS** [comment]
Haha, awesome, only took 4 years :)
