### ISSUE TITLE
Icon Request: fa-meeting

### ISSUE THREAD

**Issue by MMokhtari** [FortAwesome/Font-Awesome#5921]

**Comment by tagliala** [comment]
hmmm [fa-group](http://fontawesome.io/icon/users/) could easily represent a meeting (or [mickey mouse](https://github.com/FortAwesome/Font-Awesome/issues/1241#issuecomment-22863017), your call)

closing here. If you post an example I could reconsider reopening

**Comment by MMokhtari** [comment]
meeting usually comes with table like this : 
![34-512](https://cloud.githubusercontent.com/assets/9805952/6675845/cf4cf180-cc23-11e4-93e3-9723f58a3edd.png)

**Comment by dngunraj** [comment]
+1

**Comment by ghermans** [comment]
+1

**Comment by tagliala** [comment]
the above icon is not suitable for 14px icon size, still closed. If you provide a better example I will consider reopening :)

**Comment by MVcodeartbr** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by ghermans** [comment]
+1

**Comment by brownmestizo** [comment]
+1

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/5921#issuecomment-78358186

:lock:
