### ISSUE TITLE
Icon Request: fa-hand

### ISSUE THREAD

**Issue by MMokhtari** [FortAwesome/Font-Awesome#5922]

**Comment by tagliala** [comment]
Could you please provide an example?

**Comment by MMokhtari** [comment]
Here is one : 
![hand_cursor](https://cloud.githubusercontent.com/assets/9805952/6675801/877a3066-cc23-11e4-9c5c-0a023b4877b9.png)

**Comment by tagliala** [comment]
duplicate of #1651 , please +1 that request

closing here

**Comment by tagliala** [comment]
please also post there your example
