### ISSUE TITLE
Icon Request: fa-work

### ISSUE THREAD

**Issue by moussa-mokhtari** [FortAwesome/Font-Awesome#5925]

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by MMokhtari** [comment]
This icon need to represent some one who is looking for job maybe like this : 
![job_vacancy_work_oppotunity-512](https://cloud.githubusercontent.com/assets/9805952/6676094/9a4bc086-cc25-11e4-86aa-06e7282619f2.png)

**Comment by dngunraj** [comment]
+1

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
