### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by webburn** [FortAwesome/Font-Awesome#5928]
a-pie-chart is missing

**Comment by tagliala** [comment]
No, it isn't: http://fontawesome.io/icon/pie-chart/ :grin: 

Closing here, but feel free to comment if you are asking for another icon

**Comment by webburn** [comment]
Page is there but when I placed that icon it didn't work.  Not sure.

Thanks for the quick response.


*J.D. Huckstep*

Graphic / Web Designer

LuckyLime Media

Web: LuckyLime Media <http://www.luckylimemedia.com/>

Email: jhuckstep@luckylimemedia.com <mailto:jhuckstep@luckylimemedia.com>

Cell: 573.645.0142

Office: 573.636.LIME (5463)

**Comment by tagliala** [comment]
@webburn please make sure you are using the latest version of your software

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
