### ISSUE TITLE
Icon-request: Help icon

### ISSUE THREAD

**Issue by 26medias** [FortAwesome/Font-Awesome#5930]
There are no icons to point to a help page or the helpdesk.

It would be great to have.

**Comment by tagliala** [comment]
any example?

**Comment by jodibean** [comment]
I use fa-question-circle or fa-question for help pages

**Comment by aethior** [comment]
- [x] `fa-question` http://fontawesome.io/icon/question/
- [x] `fa-question-circle` http://fontawesome.io/icon/question-circle/
- [x] `fa-info` http://fontawesome.io/icon/info/
- [x] `fa-info-circle` http://fontawesome.io/icon/info-circle/
- [ ] `fa-headset` #1146 (planned for v5.0)

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks, really appreciate

Closing here.

Also: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
