### ISSUE TITLE
Duplicated Icon

### ISSUE THREAD

**Issue by atilkan** [FortAwesome/Font-Awesome#5931]
fa-graduation-cap
fa-mortar-board
They are the same icons or wrong icons displayed on the home page.

**Comment by tagliala** [comment]
mortar-board is an alias for graduation-cap

we have several aliases (like `icon-close`, `icon-times`) which where needed when we didn't have filters

hope it helps

closing here

**Comment by atilkan** [comment]
Thanks for enlightening.
