### ISSUE TITLE
Icon request: icon-Sharepoint

### ISSUE THREAD

**Issue by ulrikkeakerbak** [FortAwesome/Font-Awesome#5935]
Hello. 
We love Font Awesome at Skill AS in Norway! :D We are a Microsoft house and icons we use all the time are the logo's for SharePoint, Dynamics CRM, Yammer, LYNC (soon to be Skype), OneNote, OneDrive, Office  and so on. It would be super cool if we could use Font Awesome for these icons instead of images all the time.
Thank you so much!
![lync](https://cloud.githubusercontent.com/assets/11438199/6615146/886a8e2e-c8a1-11e4-8ff4-3ec5c4e169f7.jpg)
![onenote](https://cloud.githubusercontent.com/assets/11438199/6615145/8868c2f6-c8a1-11e4-893d-f2484a7f9e2d.jpg)
![sharepoint](https://cloud.githubusercontent.com/assets/11438199/6615144/8868b16c-c8a1-11e4-981c-66354310982f.jpg)
![yammer](https://cloud.githubusercontent.com/assets/11438199/6615147/8898b704-c8a1-11e4-8089-d82e491e413b.jpg)

**Comment by tagliala** [comment]
sharepoint is a dup of #2396 , please +1 that request

if you want to request multiple brands, please open individual requests and search for duplicates before, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

closing here
