### ISSUE TITLE
Rebel icon but now imperial?

### ISSUE THREAD

**Issue by Teralios** [FortAwesome/Font-Awesome#5936]
Hey, i like the rebel icon, but why no imperial icon too?

Please, make a imperial icon in the future.

**Comment by tagliala** [comment]
http://fontawesome.io/icon/empire/ <-- this one?

**Comment by Teralios** [comment]
Shit, i hate languages... I think to often in german. Thanks. :D

**Comment by tagliala** [comment]
you're welcome
