### ISSUE TITLE
Get Started - EASIEST: BootstrapCDN example does not work

### ISSUE THREAD

**Issue by davidnewcomb** [FortAwesome/Font-Awesome#5937]
The BootStrap CND example doesn't work (not a network problem!). Tried on Firefox 36.0.1 and Chrome 41.0.2272.89.
```
<html>
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
<i class="fa fa-chevron-left"></i>
</body>
</html>
```

If you download the Font Awesome and follow the instructions for "EASY: Default CSS" replacing the above code to:
```
<html>
<head>
<link rel="stylesheet" href="fa/css/font-awesome.min.css">
</head>
<body>
<i class="fa fa-chevron-left"></i>
</body>
</html>
```
Then it works just fine.

**Comment by tagliala** [comment]
of course I can't confirm --> http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-developing-my-web-app-locally-file-and-icons-from-cdn-dont-show-up

Closing here but feel free to comment
