### ISSUE TITLE
Is it possible to create an icon

### ISSUE THREAD

**Issue by medvedkun** [FortAwesome/Font-Awesome#5939]
tried to draw through Illustrator CC, but I have nothing to not work, here's an instance name of PT
![pt](https://cloud.githubusercontent.com/assets/11442425/6619895/555fed02-c8de-11e4-9e97-d309529d3a6a.jpg)

**Comment by tagliala** [comment]
@medvedkun let me know if this helps: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
