### ISSUE TITLE
Documentation for remove icon is incorect

### ISSUE THREAD

**Issue by adamsch1** [FortAwesome/Font-Awesome#5940]
http://fortawesome.github.io/Font-Awesome/3.2.1/icon/remove/

...
<i class="icon-remove"></i> icon-remove
...

The page indicates the class type is icon-remove which is not in th css file however fa-close is [as are it's aliases].  This appears to be a documentation issue.

**Comment by tagliala** [comment]
Sorry, I can't confirm: http://jsfiddle.net/tagliala/veL8gdxx/

Please note that your are looking to FA **3.2.1** docs while the current version is 4.3.0

Closing here but feel free to comment

**Comment by adamsch1** [comment]
My bad, didn't see that I was on the wrong set of docs.

For what it's worth I installed fontawesome using bower.

 "version": "4.3.0",

I still don't see icon-remove in any fa* css but I'll assume it's something to do with my setup of angular/bootstrap/shitty-knowledge-of-css causing a problem.

**Comment by tagliala** [comment]
thanks @adamsch1 and you're welcome!
