### ISSUE TITLE
Icon request: fa-arrow-top-right fa-arrow-bottom-right

### ISSUE THREAD

**Issue by sakurazaki** [FortAwesome/Font-Awesome#5941]
Hi!

I'd like to request all 4 possible diagonal arrows:
- Top Right
- Bottom Right
- Top Left
- Bottom Left

There are some places where I'd like to use, for example:
- Priority helper icon, like top: critical top-right = high and so on
- Create a clickable pad of buttons to move an element in screen (used in games for example)

Here is an image example, borrowed from a font site:
http://txt.static.1001fonts.net/txt/dHRmLjcyLjAwMDAwMC5Ra1pLVG1KbWFtNVNVMVIyZDNnLC4w/pizzadude-pointers.regular.png

Thanks for the great fonts and keep up the good work!

**Comment by dngunraj** [comment]
+1

**Comment by m80her** [comment]
+1

Unless I'm missing it somewhere in the cheatsheet, another use-case is the "glyphicon glyphicon-export" icon that comes with TWBS:

http://getbootstrap.com/components/#glyphicons-glyphs

Thanks for the great work so far :)

**Comment by jbnv** [comment]
+1

**Comment by BertelBB** [comment]
+1

**Comment by howdu** [comment]
You can achieve this simple by rotating the icon using css `transform: rotate(-45deg);`

http://stackoverflow.com/questions/22747193/statically-rotate-font-awesome-icons

**Comment by Remist0** [comment]
Is there any chance to get those icons in future?

**Comment by lanceplaine** [comment]
I need this as well!

**Comment by sensibleworld** [comment]
A little late to this thread, but we have some options now: https://fontawesome.com/search?q=arrow%20diagonal&o=r
