### ISSUE TITLE
Icon Request: fa-podcast

### ISSUE THREAD

**Issue by priestap** [FortAwesome/Font-Awesome#5942]
I've needed this one in LOTS of projects. :)  Something like the one iTunes uses would be perfect.

**Comment by kwendenarmo** [comment]
It is quite similar to RSS icon. It could be:
![podcast icon](http://ccis.ucsd.edu/wp-content/uploads/2009/10/podcast-icon.gif)

**Comment by tagliala** [comment]
duplicate of #2125, please +1 that request

closing here
