### ISSUE TITLE
Icon Request: fa-broadcast

### ISSUE THREAD

**Issue by priestap** [FortAwesome/Font-Awesome#5943]
Having an icon showing a radio tower signal or something would be great. Like this: http://cl.ly/image/2W0A411T2a01

**Comment by kwendenarmo** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #2581 , please +1 that request

closing here

**Comment by nshaibu** [comment]
+1
