### ISSUE TITLE
Icon Request: fa-network-graph

### ISSUE THREAD

**Issue by nadirabid** [FortAwesome/Font-Awesome#5944]
I'd like to see a generic graph icon similar to the image below. I expect it to have multiple use cases ranging from metaphorical/symbolic to literal. However, can't really hone in on what a good generic symbol for it would be. 

![](https://cloud.githubusercontent.com/assets/1309249/4648244/a41e9330-5480-11e4-830c-aaa8f5ffb9c4.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by awalkerca** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by miromarchi** [comment]
+1

**Comment by alindsay55661** [comment]
+1

**Comment by tvirelli** [comment]
+1

**Comment by anderflash** [comment]
+1

**Comment by Aluriak** [comment]
+1

**Comment by McGiogen** [comment]
+1

**Comment by foresttoney** [comment]
+1

**Comment by WACMemphis** [comment]
+1

**Comment by MartinBohman** [comment]
+1

**Comment by ludviglejon** [comment]
+1

**Comment by abrueck** [comment]
+1

**Comment by tagliala** [comment]
I need a better title for this request

**Comment by miromarchi** [comment]
network-graph is perfect!

**Comment by Aluriak** [comment]
I have only one remark, on a ridiculous detail: the current icon shows a star motif, a single node linked to all others.

It could be more accurate to have an edge linking two nodes that are not the central one, or linking a node to another out of field of view, just to represent the fact it is a graph, not just a hierarchical/linear structure.

**Comment by Jacquelin** [comment]
+1

**Comment by tagliala** [comment]
@Aluriak feel free to post an example

**Comment by Aluriak** [comment]
Ok, here is an idea of adaptation of the initial icon.

![a41e9330-5480-11e4-830c-aaa8f5ffb9c4](https://cloud.githubusercontent.com/assets/1257159/15578891/9b201ddc-2362-11e6-878e-d85505f46c5b.png)

It's obviously the first time i use a drawing software, but anyone with drawing skills have now an idea of what i tried to say.

**Comment by argonautical** [comment]
+1

**Comment by zakjan** [comment]
@tagliala What is the problem with the name `fa-graph`? I think it is a precise name, if this icon should represent a graph by its math/CS meaning as a set of nodes and edges.

I like the first icon, it is clear enough for me and it looks great.

**Comment by bwmerkl** [comment]
+1

**Comment by jasperblues** [comment]
+1

**Comment by mattlevan** [comment]
A graph icon is NECESSARY!

**Comment by nadirabid** [comment]
This request was for a generic graph icon, simply conveying nodes and edges, as apposed to a specific type of graph. I don't at all mind the name change but thought I'd my initial request clear.

**Comment by jacquibo** [comment]
+1

**Comment by nigelsmall** [comment]
+1

**Comment by freethejazz** [comment]
A lot of data visualization tools I've built have multiple view modes, including a graph representation. It would be great to be able to use `fa` for all of the icons used for toggling between view modes.

**Comment by crichey** [comment]
totally love to have a graph icon!

**Comment by dcolebatch** [comment]
+1 

👍x 💯

**Comment by prees1** [comment]
+1

**Comment by DaTebe** [comment]
+1

**Comment by deonclem** [comment]
Any update on this ? It's been 2 years now and one would think enough people have shown their interest in this request :thinking:

**Comment by Greatshock** [comment]
+1

**Comment by devou33** [comment]
+1 - Here is the custom icon that I created fro our app from light. Not sure if this is the same as this request or something different.
<img width="509" alt="screen shot 2018-03-30 at 9 22 53 am" src="https://user-images.githubusercontent.com/7987602/38141019-0a0504be-33fc-11e8-8402-fd0254b518c0.png">

[network.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1863822/network.svg.zip)

**Comment by tapastwain** [comment]
+1

**Comment by slattery** [comment]
+1

**Comment by systo** [comment]
+1

**Comment by outlawpractice** [comment]
+1

This could also be used as a "relationship" icon.

**Comment by jrmessias** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/chart-network?style=solid
