### ISSUE TITLE
Icon Request: fa-heart-plus fa-heart-minus

### ISSUE THREAD

**Issue by gabriel-cardoso** [FortAwesome/Font-Awesome#5947]
On the model of [fa-user-plus](http://fortawesome.github.io/Font-Awesome/icon/user-plus/)
Useful for add/remove to/from favorites

**Comment by gabriel-cardoso** [comment]
`fa-heart-times` could do the job too ! I just figured out that `fa-user-times` could be used for "user remove" indeed. That being said, `fa-user-minus` could also be added to FontAwesome.

**Comment by mrickett62** [comment]
fa-user-minus to go with fa-user-plus

**Comment by gabriel-cardoso** [comment]
:+1:

**Comment by nyon** [comment]
Added fa-heart-* and fa-heart-o-* to fontawesome-actions.

https://github.com/nyon/fontawesome-actions/

![selection_011](https://cloud.githubusercontent.com/assets/3247445/7022571/9385505a-dd2d-11e4-8a2c-ba6fdd6bb7d1.png)
![selection_012](https://cloud.githubusercontent.com/assets/3247445/7022572/950a6988-dd2d-11e4-8f14-7d1db0f61ad4.png)

**Comment by sensibleworld** [comment]
We have some more "heart" options now:

https://fontawesome.com/icons/heart-circle-plus?s=solid&f=classic
https://fontawesome.com/icons/heart-circle-minus?s=solid&f=classic
