### ISSUE TITLE
local machine loses fonts

### ISSUE THREAD

**Issue by bucksci** [FortAwesome/Font-Awesome#5948]
Hello, can someone help me with this:

I have been trying to get fontawesome to display and the code seems to work see http://codepen.io/anon/pen/LEgMXR

I can get it to look like this when the font and css files are located on my local machine, but as soon as I use the bootstrapcdn link it looks more like this: http://codepen.io/anon/pen/myzavq

I have put in the whole page html into codepen and it seems to display as expected.

**Comment by tagliala** [comment]
@bucksci https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-developing-my-web-app-locally-file-and-icons-from-cdn-dont-show-up
