### ISSUE TITLE
Icon request: user-edit

### ISSUE THREAD

**Issue by w3bninja** [FortAwesome/Font-Awesome#5951]
The use case is:

I needed an icon that represented reassigning a document from one user to another user (Edit this  documents user). 
![image](https://cloud.githubusercontent.com/assets/5608781/6641236/99b97a5e-c96a-11e4-99be-24062c2ed2f4.png)

**Comment by tagliala** [comment]
refers to #1181

**Comment by G-Driver** [comment]
+1

**Comment by dandanknight** [comment]
+1

**Comment by tdolph** [comment]
+1

Also, user profile icon should be different from edit user or plain user icon.

**Comment by malafreniere** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-tie?style=solid
