### ISSUE TITLE
Icon Request: fa-receipt

### ISSUE THREAD

**Issue by sanz0** [FortAwesome/Font-Awesome#5954]
an icon to represent receipt

**Comment by tagliala** [comment]
please provide a single color example suitable for 14px icon size, thanks!

**Comment by G-Driver** [comment]
how about this one 

<img src="https://cdn3.iconfinder.com/data/icons/pictofoundry-pro-vector-set/512/Receipt-512.png">

**Comment by tagliala** [comment]
closing as dup of #477

**Comment by dngunraj** [comment]
+1

**Comment by G-Driver** [comment]
@dngunraj could you give your vote in this topic https://github.com/FortAwesome/Font-Awesome/issues/477

**Comment by tagliala** [comment]
:lock:
