### ISSUE TITLE
Icon Request: fa-letter

### ISSUE THREAD

**Issue by sanz0** [FortAwesome/Font-Awesome#5955]
an icon to represent letters not the email icon

**Comment by tagliala** [comment]
please provide a single color example suitable for 14px icon size.

This one could work: http://fontawesome.io/icon/file-text-o/

**Comment by matrixdevuk** [comment]
fa-envelope?

**Comment by dngunraj** [comment]
+1

**Comment by GwenLoguir** [comment]
+1 pergamen

**Comment by tagliala** [comment]
Closing here, please use `fa-file-text` or `fa-envelope`

If they do not fit your use case, feel free to fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and provide an example
