### ISSUE TITLE
Icon Request: fa-speech

### ISSUE THREAD

**Issue by alvordr** [FortAwesome/Font-Awesome#5956]
I noticed there isn't really a speech icon. There's a mega-phone, a group icon, a two-way arrow, but none really say speech.  I work as a web designer and IT support specialist for a non-profit health care organization, at which we have some counselors that speak multiple languages.  Having an icon that looks like a person's head (mouth) with audible signs emitting from the mouth would be helpful.

An example of what I'm talking about is this draft I created:

http://screenpresso.com/=xQWIg

**Comment by dngunraj** [comment]
+1

**Comment by gestudio** [comment]
+1

**Comment by tagliala** [comment]
Duplicate of #2096, please +1 that request

if you find an open duplicate, please mention me

closing here
