### ISSUE TITLE
new issue Icon request: icon-magnifying-glass

### ISSUE THREAD

**Issue by rmochinski** [FortAwesome/Font-Awesome#5958]
I see one with a plus (+) sign in it. How 'bout one without:
https://cdn0.iconfinder.com/data/icons/large-black-icons/512/Zoom_search_find_magnifying_glass.png

**Comment by tommyj1112** [comment]
There already is the fa-search, does that one meet your needs?

**Comment by tagliala** [comment]
@tommyj1112 thanks

http://fontawesome.io/icon/search/

closing here
