### ISSUE TITLE
fa-user narrower?

### ISSUE THREAD

**Issue by appshore** [FortAwesome/Font-Awesome#5960]
Hi,

I have this strange case where the icon fa-user looks smaller than others. Tried different combinations, same same.

Inspect reports a 15px by 14px for the span element with fa-user and 19px by 14px for the other icons

![screen shot 2015-03-14 at 08 18 12](https://cloud.githubusercontent.com/assets/6088221/6649345/e793bed4-ca22-11e4-9e76-dec6c8273897.png)

Here the piece of code

        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-user fa-lg icon-grey"></span>
            </span>
            <input id="fullNameInput" type="text" class="form-control" placeholder="Full Name">
        </div>
        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-envelope-o fa-lg icon-grey"></span>
            </span>
            <input id="emailInput" type="text" class="form-control" placeholder="Email">
        </div>        
        <div class="form-group input-group">
            <span class="input-group-addon">
                <span class="fa fa-key fa-lg icon-grey"></span>
            </span>
            <input id="passwordInput" type="password" class="form-control" placeholder="Password">
        </div>

**Comment by tagliala** [comment]
icons in FA are not of the same size by design choice.

please add `fa-fw`
