### ISSUE TITLE
Icon Request: fa-meetup

### ISSUE THREAD

**Issue by tigusigalpa** [FortAwesome/Font-Awesome#5963]
It will be great to make icon of meetup.com social service!

**Comment by mankintong** [comment]
+1

**Comment by 972creative** [comment]
+1

**Comment by gugaalves** [comment]
+1

**Comment by rojoko** [comment]
+1

**Comment by tagliala** [comment]
Sorry, missed this one

Duplicate of #1588, please +1 that request

If you find a duplicate request, please do not +1 both but notify me, thanks

Closing here
