### ISSUE TITLE
Work In Progress 

### ISSUE THREAD

**Issue by citizen1984** [FortAwesome/Font-Awesome#5965]
Font Awesome has a spinning cog icon but no cogwheel with an anti-clockwise spin, so the Font Awesome cogs icon is static and only approximates the standard work-in-progress  animation.

Font Awesome includes open and closed locks, but doesn't animate unlocking and locking operations.

Should I make animated GIFs?

**Comment by tagliala** [comment]
I don't think the lock/unlock animation is doable with icon fonts.

You should consider an .svg based animation

Hope it helps, closing here

**Comment by citizen1984** [comment]
Thanks for getting back to me. Don't close this issue yet. What about the main question: Font Awesome has a spinning cog but no cogwheel with an anti-clockwise spin, so the static cogs icon only approximates the standard work-in-progress animation. What are the prospects for a cogwheel with an anti-clockwise spin which, combined with the existing spinning cog, would provide the industry standard work-in-progress animation?

**Comment by tagliala** [comment]
@citizen1984 a counter-clockwise animation is requested here #688

I have to keep this closed because create animations involving more than 1 icon is out of the scope of this project, sorry

Moreover, we can't create an individual icon and apply to it multiple animations because it is a limitation of font icons

**Comment by citizen1984** [comment]
tagliala,

A counter-clockwise animation was already requested? Great news! I agree that combining icons is outside the scope of your project. Users can do that themselves. So my only remaining request is a cogwheel in addition to the existing cog. Thanks for your help.
