### ISSUE TITLE
Icon Request: fa-viber

### ISSUE THREAD

**Issue by mohammadghane** [FortAwesome/Font-Awesome#5966]
I need viber icon and line icon for using in my project. please help me!

**Comment by kadishmal** [comment]
:+1: for LINE messenger icon.

**Comment by G-Driver** [comment]
dup of https://github.com/FortAwesome/Font-Awesome/issues/3554

**Comment by sohrabtaee** [comment]
+1

**Comment by tagliala** [comment]
@G-Driver thanks

closing here as a dup of #3554

**Comment by xikarx** [comment]
+1
