### ISSUE TITLE
Icon Request: fa-line or fa-line-messenger

### ISSUE THREAD

**Issue by kadishmal** [FortAwesome/Font-Awesome#5967]
We are heavily using Font-Awesome and now need an icon for the LINE messenger. Perhaps something like a chat bubble with a "LINE" word in it like in the official [logo](https://www.google.co.kr/search?q=line+messenger&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ei=LTEFVd7ZOYbImwWK7IKQDA&ved=0CAcQ_AUoAQ&biw=1024&bih=1179#rls=en&tbm=isch&q=line+messenger+icon) would suffice.

**Comment by tagliala** [comment]
Duplicate of #2631, please +1 that request

edited #2631 to include line-messenger in the title

**Comment by afgnsu** [comment]
+100
