### ISSUE TITLE
Icon request: icon-aries

### ISSUE THREAD

**Issue by gemmaweirs** [FortAwesome/Font-Awesome#5968]
This is really a group of birth sign icons that I'm requesting, i.e. Aries, Taurus, Virgo, Sagittarius, etc.

These would be used in personal profiles, but I guess other use cases would be astrology websites or other alternative websites.

Thanks.

**Comment by tagliala** [comment]
please +1  #2831 

closing here

**Comment by Fazime** [comment]
+1

**Comment by leecollings** [comment]
Why was this request closed if we're allowed to request individual Zodiac icons...?

Please re-open, and process the request.

**Comment by leecollings** [comment]
I'll ask this be opened again, before I start requesting each individual icon. You're not even replying anymore, despite several people wanting a set of icons that you cannot provide a valid reason not to include. Way to treat the people who use your product.

**Comment by winterka123** [comment]
Great icons
