### ISSUE TITLE
Icon Request: fa-question-circle-o

### ISSUE THREAD

**Issue by danstanhope** [FortAwesome/Font-Awesome#5972]
Would be great to add this one. Similar to check-square and check-square-o.

Thanks! Amazing icon set.

**Comment by shivammalhotra** [comment]
also would be great to have fa-question-circle-o & fa-info-circle-o

Thanks! Great Job

**Comment by shivammalhotra** [comment]
I have the same request. Also fa-info-circle-o 
Use Case - It will complete the o set (time, check, question and info)

Thanks! Great Job

**Comment by SamanthaAdrichem** [comment]
Don't know how to upvote, but +1

**Comment by davegandy** [comment]
Added to 4.6.0-wip branch. Closing.

**Comment by tompazourek** [comment]
Related: #3224
