### ISSUE TITLE
Icon Request: fa-sports

### ISSUE THREAD

**Issue by cdiazr** [FortAwesome/Font-Awesome#5974]
I'm building a site for betting sports using a bootstrap admin template and I will like to get any kind of icons about sports, icon-basketball, icon-tennis, icon-football, icon-boxing, etc. Icons about players such as icon-tennis-player, icon-football-player, icon-beisball-player etc... and I think is important too, get some icons to represents icon-games-tennis icon-football-macth, icon-football-court, icon-tennis-court, icon-basketball-tournaments, sporting trophies maybe, scores and icons about sporting brands like NBA, ATP, FIFA, etc... I know is too much icons but I think can be a really great collection!!!

Have a great day!
best regards

Carlos Diaz

**Comment by tagliala** [comment]
Sorry, I have to close this request, as per our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
> * Please search to see if your icon request already exists. If a request is found, please +1 that one.
> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here
