### ISSUE TITLE
Icon Request: fa-php-fusion

### ISSUE THREAD

**Issue by FrederickChan** [FortAwesome/Font-Awesome#5975]
Hello everyone, I'm the acting lead developer of PHP-Fusion Open Source CMS and currently we are using Font-Awesome officially in our next version release. We wish for an icon be represented in your unique collection. PHP-Fusion currently have about 35k+ registered members (mainly developer members) in our main site and approx 20+ national support sites. 

We want an icon representing the software in the distribution if possible so our users can use it in their add on development. It will be more than Awesome if your team can help us include/do it.

The following is our icon image attached. 

![php-fusion-icon-bw](https://cloud.githubusercontent.com/assets/4078041/6662941/2f6f8154-cbfc-11e4-9c10-422523db70b6.png)

![php-fusion-icon](https://cloud.githubusercontent.com/assets/4078041/6662942/2f7b8314-cbfc-11e4-9c63-601ca3783c25.png)

Thank you!

**Comment by dngunraj** [comment]
+1

**Comment by hien-** [comment]
How do I do this? Do I create a new glyph icon myself and submit a pull request? 

Our CMS is using Font Awesome as the main css icon library.

**Comment by tagliala** [comment]
@hien- a simple custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by FrederickChan** [comment]
Thank you. I will push once I'm done with a sample.
