### ISSUE TITLE
WIKI icon request is ignored for 3 years now

### ISSUE THREAD

**Issue by oriadam** [FortAwesome/Font-Awesome#5980]
GitHub, Wordpress, Facebook and Twitter has icons, why are Wikipedia and Wikimedia left out?
The issue has tons of +1s since 2012:
https://github.com/FortAwesome/Font-Awesome/issues/388
Please triage this issue - Create the icon, or reject the issue.

**Comment by mayinx** [comment]
+1

**Comment by tagliala** [comment]
Locking here. :lock: 

Please be nice. Meanwhile, I will try to prove that "X is here, why Y isn't" will work for every X,Y where X is included in FA and Y isn't :)
