### ISSUE TITLE
Icon Request: Market Stall

### ISSUE THREAD

**Issue by woisme** [FortAwesome/Font-Awesome#5981]
Creating a festival site. Would love a market stall. Would also be good for business sites.

**Comment by dngunraj** [comment]
+1

**Comment by wael101** [comment]
+1

**Comment by rwb196884** [comment]
+1

e.g.,
![market](https://user-images.githubusercontent.com/12090617/28162531-5063b338-67bf-11e7-86b7-f32607c3752d.PNG)

**Comment by aethior** [comment]
Hi @woisme,

This icon was added in v5.0.13.
Check https://fontawesome.com/icons/store

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Ok thanks, this was a duplicate of #1958
