### ISSUE TITLE
Icon Request: Scanner device

### ISSUE THREAD

**Issue by pclaeys** [FortAwesome/Font-Awesome#5985]
Dear,

An icon representing a flatbed scanner would be useful for us.
We want to show that some of our documents are digitalized using a scanner: 'a scanned document'.

Thx
![naamloos](https://cloud.githubusercontent.com/assets/11522216/6689099/6719f7a8-ccb8-11e4-9021-616801a94f0c.png)

Petra Claeys

**Comment by kwendenarmo** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by shahzadvu** [comment]
+1

**Comment by dfcamara** [comment]
+1 (dup of #2011)

**Comment by slimmtl** [comment]
+1

**Comment by enoshixi** [comment]
+1

**Comment by rabbal** [comment]
+1

**Comment by nickxbs** [comment]
+1

**Comment by gitfer** [comment]
+1

**Comment by bvossler** [comment]
+1

**Comment by mirkomaggioni** [comment]
+1

**Comment by niklaskallander** [comment]
+1

**Comment by Shoaneb** [comment]
+1

**Comment by gunnsth** [comment]
+1

**Comment by rschwab** [comment]
+1

**Comment by trych** [comment]
+1

**Comment by HackToday** [comment]
When will this be accepted ?

**Comment by BOHEAS** [comment]
+1

**Comment by aelbatal** [comment]
+1

**Comment by mccivelek** [comment]
+1

**Comment by ftena** [comment]
+50

**Comment by andreixk** [comment]
+1

**Comment by ChrisGeohring** [comment]
+99999999

**Comment by Welchen** [comment]
+1   This is a long time request, any way of making this happen?

**Comment by JamesBrining** [comment]
+1

**Comment by samdkershaw** [comment]
+1

**Comment by gr8kodr** [comment]
> 
> ![scanner](https://cloud.githubusercontent.com/assets/5799588/13373290/1dcc0d16-dd29-11e5-8efa-2ea75a3fee17.png)

This one looks more like an SD card case to me, the first example looks like an eye shadow compact though

+1 for the idea though

**Comment by james1301** [comment]
Just like the standard Microsoft one will do:

![image](https://user-images.githubusercontent.com/17780517/56946695-c2a27e80-6b22-11e9-841d-09a375adaead.png)

**Comment by sensibleworld** [comment]
We added a new scanner icon in 5.11: https://fontawesome.com/icons/scanner-image?style=solid

**Comment by AnupriyaGola** [comment]
+1
