### ISSUE TITLE
FontAwesome line height bug

### ISSUE THREAD

**Issue by ichim-david** [FortAwesome/Font-Awesome#5990]
I am attaching a jsfiddle when I am demonstrating what I consider to be a bug:
http://jsfiddle.net/jv51360t/3/

If I have a container with a specified line-height and I float the fontawesome icon then 
the default style:
.fa{
 font: normal normal normal 14px/1 FontAwesome;
 ...
}
is setting the line-height 1 which is responsible for the wrong placement of the link.

I would remove the line-height entirely or set it to inherit instead of setting it to 1
but I might be wrong about this.

**Comment by qimingweng** [comment]
I am experiencing this problem too, but it wasn't always like this, so I'm confused what changed in my environment to cause this

**Comment by tagliala** [comment]
As per this comment by dave: https://github.com/FortAwesome/Font-Awesome/issues/5128#issuecomment-70882874

I would say that you need that extra css line to make fontawesome work with your use case

Leaving this open for tracking purposes

**Comment by tagliala** [comment]
Closing here, let's use #5128
