### ISSUE TITLE
BUG: "fa-cart-arrow-down" symbol contain a gap

### ISSUE THREAD

**Issue by alexbreems** [FortAwesome/Font-Awesome#5991]
Hi

I found that "fa-cart-arrow-down" symbol contain a gap

See example
http://jsfiddle.net/tagliala/4nXLZ/81/

Best regards,
Alex

**Comment by tagliala** [comment]
Confirmed!

Fixed fiddle: http://jsfiddle.net/tagliala/4nXLZ/81/

**Comment by tagliala** [comment]
http://fontawesome.io/icon/cart-plus/
http://fontawesome.io/icon/cart-arrow-down/

The bug is also noticeable in the documentation (swipe between pages)

**Comment by davegandy** [comment]
Fixed in 4.4.0-wip branch. Closing.
