### ISSUE TITLE
Icon request: icon-crossroads

### ISSUE THREAD

**Issue by Jaspio** [FortAwesome/Font-Awesome#5992]
An icon to represent crossroads or junction (signpost with 2 preferably 3 or more signs pointing in different directions at different angles).

See example below:
![](https://cdn2.iconfinder.com/data/icons/travel-set-2/512/35-512.png)

**Comment by G-Driver** [comment]
+1 nice idea

**Comment by tagliala** [comment]
maybe a duplicate, but I'm unable to find the original one so... keeping this open

**Comment by jodibean** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by GwenLoguir** [comment]
+1 cute

**Comment by Jaspio** [comment]
Could I get a status update on this request?

**Comment by pRob3** [comment]
+1 awesome!

**Comment by tagliala** [comment]
https://fontawesome.com/icons/signs-post?s=solid
