### ISSUE TITLE
Icon request: fa-file-r

### ISSUE THREAD

**Issue by lfkrebs** [FortAwesome/Font-Awesome#5995]
R is an open-source statistical programming language that has become very prominent in data science. There is an increasing number of pages in both science and business context offering data and R code for download. Moreover, R can be used to create dynamic web pages visually displaying data or offering interactive analysis tools using the R-based Shiny web application frame work (see http://shiny.rstudio.com/).

Since the Shiny web application does not have a logo itself and is tied directly to the R language, I propose either a "file type" or "brand name" logo for R.

The following two use cases come to mind:
1. Scientific or business data repositories that want to indicate that code files are downloadable in R format. Both the file-type and brand-name logo would work. Examples include the Harvard DataVerse (https://thedata.harvard.edu/dvn/) offering both data and R/Stata/SAS/SPSS code, scientific journals, online courses offering classes in R (https://www.datacamp.com/, http://flowingdata.com/, http://www.dataschool.io/), etc.
2. Indicate that the page/analysis/visualization was conducted using R. Here, a brand-name icon "fa-r" would seem more applicable. Examples include displays analysis posted to places like https://rpubs.com/ or http://shiny.rstudio.com/

A knock-on effect would be the potential to use either kind of icon in the file-icon package for Github's Atom editor to represent R code. 

The icon could be based on the normal R logo:
![rlogo-5](https://cloud.githubusercontent.com/assets/11545382/6720428/1d65fd1c-cdc3-11e4-89c7-3a13e87801fe.png)

A black and white version like this should be recognizable enough:

![rlogo bw](https://cloud.githubusercontent.com/assets/11545382/6720518/de8e09da-cdc3-11e4-84a7-77e6c162f64a.png)

SVG versions of the R Logo are available at http://developer.r-project.org/Logo/ as a starting point, in case this request is approved.

Many thanks for even considering this addition to FontAwesome. It's appreciated!

**Comment by tagliala** [comment]
@lfkrebs thanks for this well explained request

`r` is a duplicate of #3862, please +1 that one

As you can see, there is no much request for this brand, so I advise you to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Renamed as `icon-file-r` and keeping this open

**Comment by lfkrebs** [comment]
@tagliala Many thanks for the advice, indeed, a custom build would solve this for. Sorry for overlooking the previous request — I searched for it to +1 but must clearly have overlooked this. Will add my vote there!

Thanks again!

**Comment by tagliala** [comment]
@lfkrebs do not worry about the duplicate :+1:

**Comment by lfkrebs** [comment]
I'm closing this old request of mine since `r-project` has been created since then

**Comment by lfkrebs** [comment]
I'm closing this old request of mine since `r-project` has been created since then
