### ISSUE TITLE
Icon request: bold empty square-o

### ISSUE THREAD

**Issue by mhebrard** [FortAwesome/Font-Awesome#5996]
Hello.
I notice that there is an `fa-square-o` associate with `fa-minus-square-o` and `fa-plus-square-o`
but no empty square bold associate with `fa-caret-square-o-` set (up|down|left|right)

It will be useful to notice
- in hierarchy: that one child have no children without break the alignment
- in cross: to add a center button

suggestions: empty bold square or bold square with a bold "." in

fiddle to show examples: http://jsfiddle.net/tdrvqj43/1/

**Comment by tagliala** [comment]
refers to ##5156

**Comment by tagliala** [comment]
Fixed

Solid: https://jsfiddle.net/tagliala/tgzouajm/28/
Regular: https://jsfiddle.net/tagliala/tgzouajm/29/
