### ISSUE TITLE
Icon request: fa-google-play, fa-itunes, fa-appstore, fa-amazon and fa-vevo

### ISSUE THREAD

**Issue by Rebex90** [FortAwesome/Font-Awesome#5997]
Hi to everyone,

I'm a programmer, a musicist and a label manager and i think these icons should be very usefull. Everytime I need to insert manually these icons when I distribute a new music release, when I edit our website services or when I distribute a new App.

Thanks in advance.

**Comment by tagliala** [comment]
google-play: #2272 
appstore and itunes: #919 
amazon: #471 
vevo: #3428

please +1 the above requests

all dups, closing here!
