### ISSUE TITLE
Icon Request: fa-gopher

### ISSUE THREAD

**Issue by 9nut** [FortAwesome/Font-Awesome#6001]
Please consider adding Go language's Gopher mascot to the collection.  There are two on the Go language site that might be suitable:

https://golang.org/doc/gopher/gopherbw.png
https://golang.org/doc/gopher/frontpage.png

**Comment by geoffgarside** [comment]
:+1:

**Comment by siddharthlatest** [comment]
:+1:

**Comment by verandaguy** [comment]
:+1:

**Comment by BugDiver** [comment]
+1

**Comment by YamiOdymel** [comment]
This relates to https://github.com/FortAwesome/Font-Awesome/issues/9431 and https://github.com/FortAwesome/Font-Awesome/issues/10507 .

**Comment by fubarhouse** [comment]
+1 👍

**Comment by tagliala** [comment]
Sorry guys, there is a more recent duplicate, #9431 which has more 👍 reactions

Please add a 👍 to that request. I will add `gopher` to #9431 's title

Closing here

**Comment by behoof4mind** [comment]
+1 👍
