### ISSUE TITLE
Icon request: pear

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6012]
<img src="https://cdn4.iconfinder.com/data/icons/simplus-food-and-drink-icon-set/169/Layer_14-01-512.png">

**Comment by Crissov** [comment]
🍐 [U+1F350](http://emojipedia.org/pear/) Unicode emoji #222

**Comment by sensibleworld** [comment]
We now have a pear icon https://fontawesome.com/v6.0/icons/pear?s=solid
