### ISSUE TITLE
Icon request: lemon

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6013]
Some examples:

<img src="https://cdn4.iconfinder.com/data/icons/gambling-and-slot-machine/83/Gambling_and_slot_machine_icons-13-512.png"> 

<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/33483-200.png">

**Comment by tagliala** [comment]
a lemon is already here: http://fontawesome.io/icon/lemon-o/

**Comment by G-Driver** [comment]
ok my bad closing this one

**Comment by G-Driver** [comment]
Updating, I see that one is lemon-o , reopening this one as fa-lemon

**Comment by Crissov** [comment]
🍋 [U+1F34B](http://emojipedia.org/lemon/) Unicode emoji #222

**Comment by tagliala** [comment]
Lemon solid has been added in FA 5.0.0 https://fontawesome.com/icons/lemon?style=solid
