### ISSUE TITLE
Icon request: fastfood

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6014]
<img src="http://cdn.flaticon.com/png/256/26393.png">

**Comment by Crissov** [comment]
Related: &#x1F964; Soft Drink #1961 and 🍔 Hamburger #6122

**Comment by sensibleworld** [comment]
There are a few options for this now: https://fontawesome.com/v6.0/icons?q=fast%20food and https://fontawesome.com/v6.0/icons?q=soda
