### ISSUE TITLE
Icon request: candy

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6015]
<img src="https://cdn0.iconfinder.com/data/icons/elite-food/512/candy-512.png">

**Comment by Crissov** [comment]
- 🍬 [U+1F36C](http://emojipedia.org/candy/) Candy Unicode emoji #222 

## Related
- 🍭 [U+1F36D](http://emojipedia.org/lollipop/) Lollipop
- 🍡 [U+1F361](http://emojipedia.org/dango/) Dango (Mochi Balls on Skewer)
- 🍪 [U+1F36A](http://emojipedia.org/cookie/) Cookie Unicode emoji #222

**Comment by iamsfs** [comment]
Plz see attached., 
![screenshot 2017-12-07 20 16 19](https://user-images.githubusercontent.com/3155371/33722360-8aad453c-db8b-11e7-8087-8d2c32613969.png)

**Comment by tagliala** [comment]
@iamsfs this is a request to add a candy icon,

Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome if you need this icon in a short while

**Comment by fu-raz** [comment]
I would love to have a candy in a wrapper like this as well. +1

**Comment by sensibleworld** [comment]
We have a few options for candy now!

https://fontawesome.com/v6.0/icons?q=candy&c=food-beverage&s=solid%2Cbrands
