### ISSUE TITLE
Icon request: bread-slice

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6016]
<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/051_Toast-512.png">

**Comment by wswilliams67** [comment]
please one with no dots.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/bread-slice?style=solid
https://fontawesome.com/icons/bread-loaf?style=solid
