### ISSUE TITLE
Icon request: chocolate

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6017]
<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/072_ChocolateBar-512.png">

**Comment by A1fus** [comment]
+1

**Comment by Crissov** [comment]
🍫 [U+1F36B](http://emojipedia.org/chocolate-bar/) Unicode emoji #222

**Comment by sensibleworld** [comment]
We now have a candy-bar icon: https://fontawesome.com/v6.0/icons/candy-bar?s=solid
