### ISSUE TITLE
Icon request: french-fries (pommes-frites)

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6018]
<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/065_Fries-512.png">

**Comment by dngunraj** [comment]
+1

**Comment by Crissov** [comment]
🍟 [U+1F35F](http://emojipedia.org/french-fries/) Unicode emoji #222

**Comment by exebossu** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/french-fries?style=solid
