### ISSUE TITLE
Icon request: fried-egg

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6019]
<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/062_FriedEgg-512.png">

**Comment by Foragers** [comment]
+1

**Comment by willythekid1979** [comment]
+1 Marvelous

**Comment by Crissov** [comment]
🍳 [U+1F373](http://emojipedia.org/cooking/) Unicode emoji #222

**Comment by sensibleworld** [comment]
This icon is in version 5 and 6 now! https://fontawesome.com/v6.0/icons/egg-fried?s=solid
