### ISSUE TITLE
Icon request: icon-tooth,  Icon request: icon-teeth

### ISSUE THREAD

**Issue by IzzyG** [FortAwesome/Font-Awesome#6021]
I would like to request icons for dental industry

**Comment by IzzyG** [comment]
![tooth](https://cloud.githubusercontent.com/assets/1019575/6751817/0779f194-cedf-11e4-97ea-8e8abe70ad58.png)

**Comment by G-Driver** [comment]
@IzzyG this is a dup of https://github.com/FortAwesome/Font-Awesome/issues/1289

**Comment by tagliala** [comment]
@G-Driver thanks

closing here
