### ISSUE TITLE
Icon request: icon-caduceus

### ISSUE THREAD

**Issue by IzzyG** [FortAwesome/Font-Awesome#6022]
we would like to request a new medical industry icon called the caduceus.

**Comment by IzzyG** [comment]
![caduceus](https://cloud.githubusercontent.com/assets/1019575/6751816/f855b4a0-cede-11e4-88ea-05b7f8797efb.png)

**Comment by G-Driver** [comment]
@IzzyG this is a dup of https://github.com/FortAwesome/Font-Awesome/issues/4325

**Comment by tagliala** [comment]
@G-Driver thanks, really appreciate

Closing here
