### ISSUE TITLE
Icon request: icon-blackberry

### ISSUE THREAD

**Issue by tc7200** [FortAwesome/Font-Awesome#6024]
![blackberry](https://cloud.githubusercontent.com/assets/6575836/6754680/6edf3c1c-cef4-11e4-892f-bc44c0ef51d2.png)

**Comment by tagliala** [comment]
duplicate of #1537 , please +1 that request

**Comment by tc7200** [comment]
Sorry i forgot to add details of what the icon will be used for.  I'm building a section of my corporate IT intranet site that references all the devices that staff can request.

**Comment by tc7200** [comment]
I work for the City of Toronto and we love your fonts.
