### ISSUE TITLE
Icon request: icon-modem (icon-router)

### ISSUE THREAD

**Issue by tc7200** [FortAwesome/Font-Awesome#6025]
![modem](https://cloud.githubusercontent.com/assets/6575836/6754892/e6ec12c4-cef5-11e4-90b0-f0f8bfbb7049.png)

I work in an IT division and we're using Font Awesome icons to visually define our services on our intranet to rest of our corporation.

**Comment by kwendenarmo** [comment]
Uhmm that's not a modem! It is more like a router + ap? or a gateway.
At the time of modems there was no domestic wireless communications!

However, I think any network element could be OK

**Comment by G-Driver** [comment]
How about this one
<img src="https://openclipart.org/image/800px/svg_to_png/198001/mono-modem.png">

**Comment by marksie1988** [comment]
+1

**Comment by andremleblanc** [comment]
:+1:

**Comment by tuxy** [comment]
:+1:

**Comment by schreiyarai** [comment]
+1
I work on an internet provider. This would be useful for out intranet and public site too

**Comment by MadTiago** [comment]
+1

**Comment by szabogyula** [comment]
+1

**Comment by nkamate** [comment]
+1

**Comment by heruan** [comment]
I think a set of networking icons would be very useful (router, switch, access point and so on) but I also know it will take years for the number of existing requests. Do anyone know an icon framework with networking icons to be used along side FA?

**Comment by mariusl-a** [comment]
+1

**Comment by jfreymann** [comment]
+1

**Comment by MichelleDiniz** [comment]
+1

**Comment by donalod** [comment]
Industry standard is more like a Cisco icon i.e. fat disc with "X" or arrows extending to circumference. Home router image belies a whole industry below and keeping web tech afloat :) E.g. http://packetlife.net/blog/2010/sep/2/free-visio-icons-vsd-grafx/ and https://www.lucidchart.com/pages/lucidu/network-diagram/network-diagram-icons-and-symbols

**Comment by cstrat** [comment]
👍

**Comment by dognoir** [comment]
+1  

any idea i where this is in the plan?

**Comment by oqhadev** [comment]
+1

**Comment by krstl2017** [comment]
+1

**Comment by yusuke50** [comment]
+1

**Comment by jcdacampo** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/router?style=solid
