### ISSUE TITLE
Icon Request: fa-mobile-basic

### ISSUE THREAD

**Issue by tc7200** [FortAwesome/Font-Awesome#6027]
![mobile-basic](https://cloud.githubusercontent.com/assets/6575836/6757060/82806646-cf04-11e4-8f63-1df76005d762.png)

I'm creating a corporate mobile device request site.  I need icons for various mobile devices.

**Comment by aethior** [comment]
Duplicate of #6027.

cc/ @tagliala

**Comment by tagliala** [comment]
Duplicate of #1670
