### ISSUE TITLE
rename utility classes pull-left/pull-right

### ISSUE THREAD

**Issue by jvanasco** [FortAwesome/Font-Awesome#6028]
the utility classes should be renamed into the fa-namespace:

* `pull-left` &raquo; `fa-pull_left`
* `pull-right` &raquo; `fa-pull_right`

These are common names for floating behavior, and user (or 3rd party) css sheets may define styles other than just a float -- which could conflict with fa styles.

i suggest using an underscore for utility classes, because the dashes are used for icons.

**Comment by tagliala** [comment]
right, these classes should be renamed

Planning for 5.0.0 because this is a breaking change

**Comment by jvanasco** [comment]
I'd suggest fixing now, but with a supporting as a deprecated feature until 5.x

new class names, relevant docs and a migration warning could be added in 4.x;
old names can be supported in 4.x, and then removed in 5.x

that would allow the changes to happen in 4.x; and not have a large impact on 5.x

**Comment by tagliala** [comment]
> I'd suggest fixing now, but with a supporting as a deprecated feature until 5.x

Right! Deprecated `pull-right` and `pull-left`, add `fa-pull-right` and `fa-pull-left`

> i suggest using an underscore for utility classes, because the dashes are used for icons.

I do agree, but things will change in 5.0.0... So `.fa-pull-*` and `pull-*` should both disappear

btw fixed via https://github.com/FortAwesome/Font-Awesome/commit/3b96e3490deca5a59307853d32273f973139ea2f
