### ISSUE TITLE
Icon request: banana

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6030]
for those who love bananas

<img src="https://cdn3.iconfinder.com/data/icons/yummicon-pro/100/020_Banana-512.png">

or 

<img src="http://image.shutterstock.com/display_pic_with_logo/144271/187405253/stock-vector-vector-black-banana-icon-on-white-background-187405253.jpg">

**Comment by anathebanana** [comment]
+1

**Comment by Crissov** [comment]
🍌 [U+1F34C](http://emojipedia.org/banana/) Unicode emoji #222

**Comment by YLAG** [comment]
not with that middle line.. just full..

but +1 yes

http://www.clker.com/cliparts/A/d/l/d/8/K/banana-wireframe-hi.png

**Comment by stifoo** [comment]
+1 but don't stop at banana!!! All animals and fruit!!!

**Comment by AdrienLZ** [comment]
@stifoo agree

**Comment by andersstaleker** [comment]
+1

**Comment by bgolyoo** [comment]
+1

**Comment by ps1337** [comment]
+1

**Comment by bohdan-didukh** [comment]
Font-Awesome has a monkey. Monkey needs a banana!

**Comment by sensibleworld** [comment]
<img width="644" alt="Screen Shot 2021-03-30 at 12 11 42 PM" src="https://user-images.githubusercontent.com/529604/113020945-17a50000-9151-11eb-8720-34612d517ad9.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
