### ISSUE TITLE
Icon Request: fa-franko

### ISSUE THREAD

**Issue by chrisfranko** [FortAwesome/Font-Awesome#6033]
A Franko is a similar currency unit to a Bitcoin.

Franko adopted the old currency symbol that was the Franc which is

₣

Examples of it being used http://frankos.org/assets/images/other_images/logo.png

See my github: github.com/franko-org/franko.git

**Comment by tagliala** [comment]
This is now available: https://fontawesome.com/v6.0/icons/franc-sign
