### ISSUE TITLE
Icon Request: fa-operator

### ISSUE THREAD

**Issue by thehavknots** [FortAwesome/Font-Awesome#6036]
for customer service bullet,

**Comment by tagliala** [comment]
could you please post an example?

**Comment by thehavknots** [comment]
![operator2](https://cloud.githubusercontent.com/assets/11593748/6771026/ebe26800-d0a8-11e4-826f-f837b0fc98a9.jpg)
![05_operator](https://cloud.githubusercontent.com/assets/11593748/6771027/ebe9767c-d0a8-11e4-908b-6046ca578623.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by seanfrasure** [comment]
+1

**Comment by ericfmatos** [comment]
+1

**Comment by tagliala** [comment]
closing as a duplicate of #5586
