### ISSUE TITLE
Icon Request: fa-fastshipping

### ISSUE THREAD

**Issue by thehavknots** [FortAwesome/Font-Awesome#6038]
fast envelope shipping icon, packages, delivery

**Comment by tagliala** [comment]
could you please post an example?

**Comment by thehavknots** [comment]
![envelope](https://cloud.githubusercontent.com/assets/11593748/6771058/debd69bc-d0a9-11e4-80f1-56976bdda78f.jpg)

![envelope1](https://cloud.githubusercontent.com/assets/11593748/6771064/1f55926a-d0aa-11e4-913f-201ae73a1766.png)

**Comment by G-Driver** [comment]
+1 cool idea, here another examples:

<img src="https://cdn0.iconfinder.com/data/icons/logistic-2/450/fast-512.png">
<img src="https://cdn2.iconfinder.com/data/icons/picons-basic-3/57/basic3-022_delivery_van_24h-512.png">

**Comment by dngunraj** [comment]
+1

**Comment by kkurt** [comment]
+1

**Comment by mattw3003** [comment]
+1

**Comment by trancegaffer** [comment]
+1

**Comment by aethior** [comment]
Related: #9936

**Comment by sensibleworld** [comment]
There are a few options for this in the new logistics category in 5.0.7: https://fontawesome.com/icons?d=gallery&c=logistics
