### ISSUE TITLE
PayPal icons are outdated.

### ISSUE THREAD

**Issue by rrs120486** [FortAwesome/Font-Awesome#6039]
fa-paypal and fa-cc-paypal shows the old PayPal logo. Request you to please update that.

Thanks!

**Comment by tagliala** [comment]
https://www.paypal.com/us/webapps/mpp/logos-buttons

@davegandy you probably need to edit the logo for single color rendering :\

(top: unedited, bottom: edited)
![image](https://cloud.githubusercontent.com/assets/556268/6769329/5d2bf736-d097-11e4-9eac-008ea6c93ea3.png)

**Comment by rrs120486** [comment]
Below are some grayscale and black logos for PayPal. Please let me know if you need eps file for these.
Horizontal black:
![pp_h_black](https://cloud.githubusercontent.com/assets/5557037/6880531/c927da80-d55c-11e4-8806-bc7e1bda61ea.png)
Horizontal Gray Scale:
![pp_h_grey](https://cloud.githubusercontent.com/assets/5557037/6880532/d9c72044-d55c-11e4-804d-cac65aeec8d8.png)

Vertical GrayScale:
![pp_v_grey](https://cloud.githubusercontent.com/assets/5557037/6880542/10932618-d55d-11e4-829f-87dd80448f74.png)
Vertical Black:
![pp_v_black](https://cloud.githubusercontent.com/assets/5557037/6880544/1f65f8be-d55d-11e4-8fa8-5afc16ed03de.png)

Monogram Grayscale:
![pp_m_grey](https://cloud.githubusercontent.com/assets/5557037/6880546/307d5f70-d55d-11e4-8224-b1ec94005ce8.png)

Monogram Black:
![pp_m_black](https://cloud.githubusercontent.com/assets/5557037/6880549/3bb7a7e2-d55d-11e4-8c80-185eb3b8ab8c.png)

**Comment by jaypatel512** [comment]
Hey Guys, Any update on this. I work for PayPal, and could help you get the correct assets if these are not sufficient. Can you please help update this.

**Comment by tagliala** [comment]
Hi @jaypatel512 thanks for your willingnes to help but at the moment dave is not accepting PR containing icons.

I also think he's having a really busy time

Btw I suppose that a gist containing an official asset in svg format could speed up his work

**Comment by jaypatel512** [comment]
Oh ok. I will definitely be able to provide some svgs. Let me get to the marketing team, and get hold of those.

**Comment by davegandy** [comment]
Yep, SVG would be awesome! I'll get these updated in 4.4 if we can get them ASAP!

**Comment by davegandy** [comment]
What's wrong with fa-cc-paypal, btw? Looks like the same text to me...

**Comment by davegandy** [comment]
Oh, I see it. The 'a's are different. :)

**Comment by davegandy** [comment]
Okay, updated and checked into 4.4.0-wip. Wish vector versions of those logos were more easily accessible. :)
