### ISSUE TITLE
 new issue Icon request: fa-gnu

### ISSUE THREAD

**Issue by christian-momon** [FortAwesome/Font-Awesome#6040]
As fa-linux is already there, the fa-gnu is required too. :yellow_heart: 

Linux is often used to express the GNU/Linux operating system and the open-source software idea. The GNU logo express:
- the GNU/Linux operating system
- the GNU project (with so many used tools)
- the free/libre software idea.

It would be great to have the choice. :smile: 

This is a SVG format, so easy to use. :heart_eyes: 

![GNU Logo](https://www.gnu.org/graphics/empowered-by-gnu.svg)

Source file: https://www.gnu.org/graphics/empowered-by-gnu.svg
Source page: http://www.gnu.org/graphics/heckert_gnu.html
License : GFDL 1.3, the Free Art License, or under CC-BY-SA 2.0

**Comment by tagliala** [comment]
@christian-momon sorry but I can't leave this open. You should add a comment to #2665

thanks
