### ISSUE TITLE
Icon Request: fa-delivery

### ISSUE THREAD

**Issue by heavyromulo** [FortAwesome/Font-Awesome#6041]
please make an icon of reference to delivery, as in the example. thank you very much.

![delivery-icon](https://cloud.githubusercontent.com/assets/11599785/6770296/b2b986b6-d09a-11e4-8c18-b1d6422a1f39.png)

**Comment by thehavknots** [comment]
+1
![fastdelivery](https://cloud.githubusercontent.com/assets/11593748/6771103/40ccb170-d0ab-11e4-9f26-808d5fcaef11.png)
but i wanna see something like this

**Comment by heavyromulo** [comment]
hi, anyone?

**Comment by MVcodeartbr** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by rickdoesburg** [comment]
https://fortawesome.github.io/Font-Awesome/icon/truck/ ?

**Comment by hpvd** [comment]
if needed, please also vote for complementing icon-requests of
- quote https://github.com/FortAwesome/Font-Awesome/issues/8329
- invoice https://github.com/FortAwesome/Font-Awesome/issues/477

**Comment by jbnv** [comment]
+1 if it's just a simple delivery truck. The streaks are just cutesy, and I don't see any reason to make it more complicated than just a delivery truck.

**Comment by dotnetchris** [comment]
:+1:

**Comment by pslcbs** [comment]
+1

**Comment by mattw3003** [comment]
+1 for fast delivery truck

**Comment by mike6ds** [comment]
+1

**Comment by shurub3l** [comment]
+1
![shipping](https://cloud.githubusercontent.com/assets/4004313/17401288/902b86f8-5a55-11e6-8cd3-5b0b68a452ca.png)

**Comment by andreicostin** [comment]
+1

**Comment by tagliala** [comment]
package #908

**Comment by lalabili** [comment]
+1

**Comment by tadan** [comment]
+1

**Comment by sensibleworld** [comment]
Available in latest release: https://fontawesome.com/icons?d=gallery&q=shipping%20fast
