### ISSUE TITLE
Icon Request: fa-user-tie and fa-notes

### ISSUE THREAD

**Issue by mify702** [FortAwesome/Font-Awesome#6045]
hi, can you please make an icon user-tie and notes. please see attached sample. thanks so much.

**Comment by tagliala** [comment]
user-tie: #3397

notes is a duplicate of #773  or #1986 (it depends on what you need)

Please +1 the above requests, closing here

If notes in not one of the above, feel free to comment and provide an example

**Comment by mify702** [comment]
thank you so much for the quick reply :)

**Comment by hainguyen81** [comment]
+1
