### ISSUE TITLE
Icon request: fa-elevator (fa-lift)

### ISSUE THREAD

**Issue by theskystalker** [FortAwesome/Font-Awesome#6047]
Hi, it would be nice to have an Icon for elevators. For example to display elevators on interactive OpenStreetmap maps.

https://commons.wikimedia.org/wiki/File:Elevator_(Madrid_Metro).svg
https://commons.wikimedia.org/wiki/File:Aiga_elevator_inv.svg

BR

**Comment by G-Driver** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by theskystalker** [comment]
Hi, here is another variant for an elevator symbol. Taken on a trainstation, maybe this symbol is more international or some standard.
![Uploading IMG_20150324_100611.jpg . . .]()

**Comment by theskystalker** [comment]
Ooops, wrong Button, there is the picture ;D

![img_20150324_100611](https://cloud.githubusercontent.com/assets/3897395/6800484/31b13ee8-d21f-11e4-8f24-11ff5ae25cf8.jpg)

**Comment by dngunraj** [comment]
+1

**Comment by LeoMagee** [comment]
+1

**Comment by danniejpt** [comment]
+ 1

**Comment by knoppys** [comment]
+1

**Comment by shubnigg** [comment]
+1
Elevator with arrow up 
Elevator with arrow down
Elevator with arrow up and down
Elevator without arrows

![iso_elevator](https://cloud.githubusercontent.com/assets/12882710/8158101/4c4824b6-135a-11e5-8218-18bdc3588b71.jpg)

**Comment by richnicholls404** [comment]
+1

**Comment by cjduffett** [comment]
+1

**Comment by MVcodeartbr** [comment]
some inspiration
![stock-vector-icon-of-the-elevator-passengers-and-up-and-down-arrows-vector-minimal-outline-332851058](https://cloud.githubusercontent.com/assets/3662026/11432902/f4f079fa-949d-11e5-9159-fed9b57396f1.jpg)
![stock-vector-elevator-single-icon-series-vol-266881121](https://cloud.githubusercontent.com/assets/3662026/11432903/f4f3533c-949d-11e5-971e-103bd727d5d9.jpg)
![elevator_icon](https://cloud.githubusercontent.com/assets/3662026/11432887/c52a1e7e-949d-11e5-8dd3-486703a684ba.png)
![elevator-icons-set-colorful-retro-elevators-32783178](https://cloud.githubusercontent.com/assets/3662026/11432888/c549faf0-949d-11e5-9f8f-cdb88d5f5b48.jpg)
![elevator-ride-icon-image-abstract-people-riding-up-down-50303131](https://cloud.githubusercontent.com/assets/3662026/11432890/c55b86a8-949d-11e5-94be-5d1d538ddb9a.jpg)
![icon175x175](https://cloud.githubusercontent.com/assets/3662026/11432889/c55b499a-949d-11e5-901e-111daca5e8d9.jpeg)
![icon175x175](https://cloud.githubusercontent.com/assets/3662026/11432891/c56043dc-949d-11e5-98fe-40996a76812a.png)
![images](https://cloud.githubusercontent.com/assets/3662026/11432892/c5631508-949d-11e5-88f4-f7ec67a4d3db.png)

+1

**Comment by showplans** [comment]
+1

**Comment by highsource** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/6707996/12109555/3edce7fc-b383-11e5-97c9-2bba9f88b178.png)

[aufzug.zip](https://github.com/FortAwesome/Font-Awesome/files/78092/aufzug.zip)

**Comment by stefankellens** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by cnrblm** [comment]
+1

**Comment by lovePizza** [comment]
+1

**Comment by lurchy86** [comment]
+1

**Comment by m-aciek** [comment]
+1

**Comment by amirasaran** [comment]
+1

**Comment by ds160384** [comment]
+1

**Comment by rjpadula** [comment]
+1

**Comment by fbarletta** [comment]
+1

Any update/status on this?

**Comment by GKMelbo** [comment]
+1

**Comment by kucherenkovova** [comment]
+1

**Comment by poldixd** [comment]
+1

**Comment by simeonackermann** [comment]
+1 like in [foundation icon](http://zurb.com/playground/foundation-icon-fonts-3#elevator)

**Comment by pashute** [comment]
+1

**Comment by nimmyy** [comment]
+1

**Comment by zuruckzugehen** [comment]
+1

**Comment by am2222** [comment]
+1

**Comment by eifersucht** [comment]
+1

**Comment by Jiish** [comment]
+ 1

**Comment by MiVvlt** [comment]
+1

**Comment by ximex** [comment]
+1

**Comment by pludi** [comment]
+q

**Comment by betasa** [comment]
+1

**Comment by SirLamer** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by godler** [comment]
+1

**Comment by voland10557** [comment]
+1

**Comment by TheGrimX** [comment]
😊😊😊

**Comment by studioavanti** [comment]
+1 ;-)
![240_F_3347793_C6Ch5JqrEkc0NtldW2unAg3QwKqDEF](https://user-images.githubusercontent.com/8690161/55010040-d3237e80-4fe3-11e9-886f-4ce33fb4171d.jpg)

**Comment by ScottAgirs** [comment]
+1 - any updates?

**Comment by annie-kr** [comment]
+1 please

**Comment by MartinGerritsen** [comment]
+1 here too, thanks!

**Comment by pesta** [comment]
+1

**Comment by jessie-rauch** [comment]
+1

**Comment by pennetta-be** [comment]
Still waiting for an elevator icon.

It would be great even to just have the caret up + down icons together, as they can seem like the elevator buttons...

**Comment by Benjaminhu** [comment]
+1

**Comment by codyreed** [comment]
+1

**Comment by MadDevl** [comment]
+1

**Comment by MadDevl** [comment]
+1

**Comment by wirespecter** [comment]
+1

**Comment by YusukeOba** [comment]
+1

**Comment by entttom** [comment]
+1

**Comment by ryanespin** [comment]
![image](https://user-images.githubusercontent.com/3648402/102921667-bf2bdb80-445a-11eb-8eb2-2e6bbdf9beff.png)
I was able to group arrow-up, arrow-down, male, and female to create this elevator icon, but doesn't look so great in smaller sizes.  Good enough for what I need it for though :)

**Comment by sensibleworld** [comment]
We've added a new elevator (and escalator!) icon to our latest alpha release of version 6: https://fontawesome.com/download
