### ISSUE TITLE
fa fa vaccine

### ISSUE THREAD

**Issue by rotakeo** [FortAwesome/Font-Awesome#6048]
Please is it possible a icon related to vaccine?

**Comment by afrome** [comment]
+1

**Comment by tagliala** [comment]
any example?

**Comment by afrome** [comment]
http://thenounproject.com/term/vaccine/4329/ ?

**Comment by tagliala** [comment]
may this be considered a duplicate of #1779 ?

**Comment by afrome** [comment]
Yes, for me #1779 would satisfy the vaccine requirement. Thanks!

**Comment by tagliala** [comment]
So I should ask you and @rotakeo  to +1 #1779 because there will be more chances of being included.

But I should also advise to consider a custom build of FA: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
