### ISSUE TITLE
Icon request: icon-wire-transfer

### ISSUE THREAD

**Issue by tobyberster** [FortAwesome/Font-Awesome#605]
it would be great to have icons for business applications.
- wire transfer

and im sure there are some more available.

**Comment by nightskylark** [comment]
+1 Wallet

**Comment by fire2** [comment]
+1 Wallet
+1 Wire transfer

**Comment by deMonest** [comment]
+1 Wallet

**Comment by johnspostsalotfishing** [comment]
+1 Wallet

**Comment by tagliala** [comment]
Check: please 👍  #2603
Wallet: please 👍  #2317

Didn't get feedback here. I need a single color, 16px icon size suitable example

If you want to require a "wire transfer" icon, please open a new request  that follows our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

🔒
