### ISSUE TITLE
Icon request: icon-php

### ISSUE THREAD

**Issue by messmaker** [FortAwesome/Font-Awesome#6051]
Hello and thanks for all the work you've done so far!
It would be great if you could include the php elephant ;)

**Comment by tagliala** [comment]
duplicate of #1420 , please +1 that request

please also take a look here: http://fizzed.com/oss/font-mfizz

**Comment by messmaker** [comment]
Sorry I didn't saw it ..

**Comment by tagliala** [comment]
no problem
