### ISSUE TITLE
Icon Request: fa-user-check

### ISSUE THREAD

**Issue by jeancarlos** [FortAwesome/Font-Awesome#6053]
A combination of fa-user and fa-check. 

Something like this: 

![fa-user-check.](http://jeansouza.info/img/fa-user-check.png)

**Comment by tagliala** [comment]
Refers to #1181

**Comment by nyon** [comment]
I've added fa-user-check and others to fontawesome-actions here: http://github.com/nyon/fontawesome-actions

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-check?style=solid
