### ISSUE TITLE
Icon Request: agile development

### ISSUE THREAD

**Issue by epistrephein** [FortAwesome/Font-Awesome#6054]
I propose an icon for Agile Development.

Examples:

![agile-icon](https://cloud.githubusercontent.com/assets/4941334/6805175/e7fca58a-d241-11e4-89de-4e9d4b0e0d65.png)
![640px-agile_project_management_by_planbox](https://cloud.githubusercontent.com/assets/4941334/6805177/eca1cf70-d241-11e4-8ccf-dec277c92854.png)

**Comment by ludobourgoin** [comment]
Yes, that'd be awesome. Thanks in advance for taking this request into consideration.

**Comment by Saylrman64** [comment]
+1
I need an Agile icon.
Here is a simple representation I use (until you create one!)
Thanks for the Awesome Fonts!

![agile](https://user-images.githubusercontent.com/4205992/42720881-e428af70-86fd-11e8-8b79-41e337fe9685.png)

**Comment by hamzawii** [comment]
+1 still waiting for this icon, 

Thanks :)

**Comment by PaddyThorne** [comment]
+1

**Comment by LeChatP** [comment]
+1

**Comment by Almnga** [comment]
Aaa

**Comment by SailorMan64** [comment]
Bump!
