### ISSUE TITLE
Icon request: icon-sack-truck

### ISSUE THREAD

**Issue by mattSchulz** [FortAwesome/Font-Awesome#6059]
fa-sack-truck

Sometimes a complete truck feels too heavy handed for what our suppliers are providing (digital goods).

I made this sack truck icon. It would be good if there was something similar in font-awesome.
![suppliers_icon](https://cloud.githubusercontent.com/assets/8831153/6837851/727aa06c-d3a1-11e4-8e7b-f5507e142cb4.png)

[here's my icon in some other formats](https://www.dropbox.com/sh/vza0e73zcpai342/AACha96CUPt-45m81h0dQSSSa?lst=)

**Comment by dngunraj** [comment]
+1

**Comment by aethior** [comment]
Hi @mattSchulz,

This icon was added in v5.0.7.
Check https://fontawesome.com/icons/dolly

Regards.

cc/ @tagliala
