### ISSUE TITLE
Icon request: icon-suit-spades, icon-suit-clubs, icon-suit-diamonds, icon-suit-hearts (alias) - Card Suits

### ISSUE THREAD

**Issue by aponxi** [FortAwesome/Font-Awesome#606]
It would mean the world to me if you would add a badass spade!

**Comment by PaulLinton** [comment]
+1
Solid and outline versions would be good.  Sometimes Spades/Clubs can be difficult to tell apart when they are small.  Some folks use Blue or Green for the Club symbol (Bridge Base Online, I think) and others use an outline for clubs and diamonds so they have an extra difference from spades and hearts (the minor suits versus the major suits, if you play bridge)

**Comment by AlexWerz** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by nolansa** [comment]
+1

**Comment by jmz-b** [comment]
+1

**Comment by jkclose** [comment]
+1

**Comment by griser** [comment]
+1

**Comment by nullvariable** [comment]
FWiW, these symbols are available in Unicode and should work in any browser that supports Unicode characters: http://en.wikipedia.org/wiki/Playing_cards_in_Unicode
```
♠
♥
♦
♣
```

**Comment by Fatbat** [comment]
^^ Yeah, but they aren't in the same style as the rest of these icons.

+1

**Comment by Ash-Crow** [comment]
+1

**Comment by misbeliever** [comment]
+1

**Comment by christophelassus** [comment]
+1 unicode symbol may be replaced with emoji icons by some browsers and you cannot change the color. I don't understand why it's an issue to add this very useful set of icons

**Comment by adamwintle** [comment]
+1 for this

**Comment by zgabievi** [comment]
+1

**Comment by pepevc** [comment]
+1

**Comment by vtange** [comment]
+1

**Comment by SymphonyRed** [comment]
+1

**Comment by joaoguilhermee** [comment]
+ 1

**Comment by langbakk** [comment]
+ 1

**Comment by battlemoose** [comment]
👍

**Comment by rundef** [comment]
:+1:

**Comment by VioletPadfoot** [comment]
👍

**Comment by murelain** [comment]
+1

**Comment by sinkalex31** [comment]
+1

**Comment by Somesite** [comment]
+1

**Comment by jeremyrwross** [comment]
+1

**Comment by BrendaEgeland** [comment]
+1, would use on sites I'm building for playing card games.

**Comment by ThiagoAugustoSM** [comment]
+1, i really would like to see some of these suit icons

**Comment by alystair** [comment]
@sensibleworld  should closed since it's released :+1:

**Comment by sensibleworld** [comment]
@alystair Thanks! Missed this one.

**Comment by bitedgecom** [comment]
+1 also a general playing card icon.

**Comment by aponxi** [comment]
Yay! 👍 Thanks!

**Comment by Some-T** [comment]
I can't find the symbol for jack in relation to playing cards in latest font awesome pro?
