### ISSUE TITLE
Icon Request: icon- shopping bag

### ISSUE THREAD

**Issue by cpar917** [FortAwesome/Font-Awesome#6060]
![shopping bag](https://cloud.githubusercontent.com/assets/11656337/6838197/1f8bfaa8-d31b-11e4-976d-a68bde38b0ee.jpg)
Hi there! 
I love all your icons they are awesome! I was interested in requesting a shopping bag. Currently we use the shopping cart, but for a women's retail store we think a little shopping bag would be more fitting for a check out option. The bag would be another way for retailers to say to to bag instead of a traditional grocery cart. 
Just a plain little black bag would be great. 
Thanks for your hard work!

Cheers!
-Chloe

**Comment by dngunraj** [comment]
+1

**Comment by epistrephein** [comment]
+1

**Comment by GwenLoguir** [comment]
+1

**Comment by lucidstudios** [comment]
+1

**Comment by tagliala** [comment]
dup of #829 , please +1 that request

closing here
