### ISSUE TITLE
Icon Request: Movie Genre

### ISSUE THREAD

**Issue by RobinSchenk** [FortAwesome/Font-Awesome#6061]
Hello.

I think it would be a cool idea to have icons from multiple movie genres. I can amagine that there are a lot of uses for icons like these. For example im building a movie library at this moment and i could use those kind of icons very much.

**Comment by tagliala** [comment]
sorry, can't leave this open, it doesn't follow our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Please and thank you if you include the following:
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Attach a single color image or two that represent the idea you're going for.
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
