### ISSUE TITLE
Icon Request: fa-business

### ISSUE THREAD

**Issue by saguiitay** [FortAwesome/Font-Awesome#6063]
Useful for representing Business plans (in a pricing page)

Perhaps something along the lines of:
  * https://cdn0.iconfinder.com/data/icons/corporative-business/512/meeting-128.png
  * https://cdn3.iconfinder.com/data/icons/business-analytics/512/handshake-128.png

**Comment by dngunraj** [comment]
+1 desperately

**Comment by tagliala** [comment]
duplicate of #878 , please +1 that request

closing here
