### ISSUE TITLE
Icon request: icon-itchio

### ISSUE THREAD

**Issue by Darkhogg** [FortAwesome/Font-Awesome#6065]
[itch.io](http://itch.io) is an online game store. The following is the monochrome logo present on their blog:
![](http://static.tumblr.com/9cee8481aec0fb519d74d209abdb1750/7cv5azk/hJHmvv1p8/tumblr_static_itchio-black.png)

My particular use case is for linking to my profile on my website and for individual games links. Anyone with games there might benefit from being able to introduce links using the logo.

**Comment by Rumpelcita** [comment]
I would really like this too.

**Comment by gersande** [comment]
Yes please!!!!

**Comment by TheMorfeus** [comment]
+1

**Comment by TomasDuda** [comment]
I'd love this. itch is becoming more and more relevant in digital game stores, so why not?

**Comment by quyse** [comment]
There's textless vector version of logo in itch.io's github repo: https://github.com/itchio/itch/blob/master/appsrc/static/images/logos/itchio-textless-black.svg

**Comment by dotjersh** [comment]
+1

**Comment by nolanmanning703** [comment]
Agreed, I would love to see this icon added!

**Comment by jparse** [comment]
+1

**Comment by yadurajiv** [comment]
I was just looking for this ^_^ 👍

**Comment by CatLover91** [comment]
I suggest the text-less logo, as it is commonly used as a part of the link-button to a user's store.

A live example of a possible usecase: https://eev.ee/

![Image of white itch image](https://raw.githubusercontent.com/eevee/eev.ee/master/theme/static/images/logo-itch.png)

The background of the image is white so it may be hard to see here. On eevee's blog you can see a typical usecase for such an icon roughly halfway down the home splash page. 

![image](https://user-images.githubusercontent.com/7215827/28795276-492acef2-7607-11e7-8b54-c40cfe771c32.png)

You can visit itch's github organization @itchio to give context with the request, and within the organization are several active open-source projects. The website largely caters to indie game developers who actively create personal websites to network with, so utilization of an icon for this would be very helpful.

**Comment by Darkhogg** [comment]
@CatLover91 The [Contribution Guide](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md) states that issues should contain `icon-whatever`, not `fa-whatever`, so I won't edit the title unless the guidelines change.

**Comment by BluShine** [comment]
Was updating my site today and surprised this icon isn't already in!

**Comment by Elendow** [comment]
+1

**Comment by edcasillas** [comment]
+1

**Comment by pavle-goloskokovic** [comment]
+1

**Comment by pavle-goloskokovic** [comment]
Here's a svg you can use instead of `<i>` tag:
``` html
<svg class="svg-inline--fa" aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 177 177">
   <path fill="currentColor" d="M23 0L0 27v7.7c0 9.8 9 18.4 17 18.4 9.9 0 18-8.3 18-18 0 9.7 7.9 18 17.6 18S70 44.8 70 35c0 9.7 8.4 18 18.1 18C98 53 106 44.8 106 35a18 18 0 0 0 17.7 18c9.7 0 17.3-8.3 17.3-18 0 9.7 8.4 18 18.2 18A18 18 0 0 0 177 35v-8L152 0C108.4-.1 23 0 23 0z" fill-rule="evenodd"/>
   <path fill="currentColor" d="M35 48.6c-1 1.6-2.2 3-3.6 4.4-3.6 3.6-8.7 5.9-14.3 5.9-1.4 0-5-.8-5-.8v100h154V57.5c-2.4.9-4.3 1.4-7 1.4a20.3 20.3 0 0 1-17.7-10.4 20.6 20.6 0 0 1-17.7 10.4 20.3 20.3 0 0 1-17.8-10.4 20.4 20.4 0 0 1-35.5 0A20.4 20.4 0 0 1 38.3 53a19.5 19.5 0 0 1-3.3-4.4zM57.2 67c6.7 0 11.5 4.4 13.1 11h37.2c1.7-6.6 6.4-11 13.1-11 10.7 0 22.4 11 26 24.4l8.8 32c3.7 13.3-2 24.3-12.7 24.3-9.4 0-19.6-8.5-24.4-19.6H59.5c-4.9 11.1-15 19.6-24.4 19.6-10.7 0-16.4-11-12.8-24.4l8.8-32C34.8 78 46.5 67 57 67z"/>
   <path fill="currentColor" d="M75.7 95.4l-12.5 13.4h12.4v13.9h24.6v-13.9h13.2l-12.6-13.4-12.5-13.5z"/>
</svg>
```

**Comment by rorlork** [comment]
@pavle-goloskokovic I'd suggest that the style for that include `max-width:1em; vertical-align:middle;`

**Comment by ZavixDragon** [comment]
+1

**Comment by foxnoodles** [comment]
lol how long does it take to add a fucking icon... this is hilarious.

**Comment by Xirion11** [comment]
+1

**Comment by s00172994** [comment]
+1

**Comment by BoraxKid** [comment]
Would love that icon too
+1

**Comment by Democide** [comment]
Absolutely! I'd love this!

**Comment by fasterthanlime** [comment]
The logos linked at the top of this issue are outdated, the most up-to-date can be found here: https://itch.io/press-kit

**Comment by Democide** [comment]
Oh, it's gotten a bit fatter? Also much cuter! <3

I wasn't even aware of the change!

**Comment by talbs** [comment]
Here you go, gang. We added this icon as part of version `5.8.0` - https://fontawesome.com/icons/itch-io?style=brands
Thanks for the patience and for continuing to vote this up! :smile:

**Comment by edcasillas** [comment]
You did it!!! Thanks!!!!

**Comment by Democide** [comment]
Yes!

**Comment by kawaiidesune** [comment]
Huzzah!
