### ISSUE TITLE
Icon request: fa-houzz

### ISSUE THREAD

**Issue by kerbasaurus** [FortAwesome/Font-Awesome#6066]
Could y'all do us a solid and add an icon for Houzz pretty pretty please?  Just the icon portion.  Thank you!

![Image of Houzz](http://www.houzz.com/pic/footer_houzz_logo.png)

I'll be using these on a very high end lighting company website.

**Comment by rtpHarry** [comment]
FYI this is in the brandico fontset already
http://fontello.com/#search=houzz

**Comment by tagliala** [comment]
Closing as a duplicate of #2039

**Comment by markream** [comment]
+1
