### ISSUE TITLE
Push 4.3.0 to Nuget

### ISSUE THREAD

**Issue by kestelle** [FortAwesome/Font-Awesome#6067]
Nuget has not yet been updated with version 4.3.0: https://www.nuget.org/packages/FontAwesome/

Could this please be updated?

Thanks

**Comment by tagliala** [comment]
I don't have control on that repo, please take a look here: https://github.com/JustLikeIcarus/Font-Awesome-NuGet/issues/4

**Comment by janstadt** [comment]
+1 on this. I pinged @kazimanzurrashid who looks to own the nuget repo but he hasnt responded to me with any updates.

**Comment by tagliala** [comment]
Sorry, we don't have an official nuget repository.

Please consider to upvote #7213
