### ISSUE TITLE
Icon Request: fa-viadeo 

### ISSUE THREAD

**Issue by jeremyatia** [FortAwesome/Font-Awesome#6070]
Hello,

I was wondering if it is possible to add this icon please ?
I plan to use it on my own website.

Thank you in advance !

![viadeo](https://cloud.githubusercontent.com/assets/6185394/6852365/888d17ac-d3e4-11e4-8482-73880deeeaf3.png)

Jérémy ATIA.

**Comment by tagliala** [comment]
duplicate of #886 , please +1 that request

closing here
