### ISSUE TITLE
Icon Request: fa-kaggle

### ISSUE THREAD

**Issue by jeremyatia** [FortAwesome/Font-Awesome#6071]
Hello,

Is it possible to create this icon as well ? :) 
I plan to use it on my own website.

Thank you very much for your time,

Jérémy ATIA
![kaggle](https://cloud.githubusercontent.com/assets/6185394/6852526/739d9406-d3e5-11e4-9d04-fc2b6acb7e8e.png)

**Comment by tagliala** [comment]
dup of #4363, please +1 that request

I should advise you to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by mrandrewandrade** [comment]
+1

**Comment by navoshta** [comment]
+1

**Comment by virilo** [comment]
+1

**Comment by zackthoutt** [comment]
+1

**Comment by ajanac** [comment]
+1

**Comment by timtjtim** [comment]
As stated above this is a duplicate of #4363, please 👍 that one.

**Comment by lswh** [comment]
+1!!

**Comment by levkovalenko** [comment]
+1

**Comment by dA505819** [comment]
Is it ready?
