### ISSUE TITLE
Icon Request: icon-footwear, Icon Request: icon-clothing, Icon Request: icon-food

### ISSUE THREAD

**Issue by patelbhavesh3603** [FortAwesome/Font-Awesome#6075]
Hello,

We can not found some icons in The Font Awesome. We need to icon for footwear, clothing and foods to our wordpress category.

Please give us to that icons.

Thanks in Advanced

Thanks & Regards,
Bhavesh Patel

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
