### ISSUE TITLE
Icon request: bottle

### ISSUE THREAD

**Issue by Max-Krieg666** [FortAwesome/Font-Awesome#6083]
pls add bottle

**Comment by tagliala** [comment]
duplicate of #1762 ?

**Comment by Max-Krieg666** [comment]
as like as http://img.carpati.org/users/mi/mike/mike/editor/09/5.4.jpg

**Comment by jesseflorig** [comment]
@tagliala seems like a yes to me.

**Comment by tagliala** [comment]
no feedback, closing here
