### ISSUE TITLE
Icon request: hammer-and-pick

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6087]
<img src="http://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Schlaegel_und_Eisen_nach_DIN_21800.svg/354px-Schlaegel_und_Eisen_nach_DIN_21800.svg.png">

**Comment by G-Driver** [comment]
@tagliala .... so whats the question? ;)

**Comment by tagliala** [comment]
I don't know if I can consider this a duplicate of #736

**Comment by G-Driver** [comment]
That one is different its a screwdriver with a wrench the only thing they have commin it's they're crossed.

Hammer and pick is a common symbol for mining

**Comment by tagliala** [comment]
closing as a duplicate of #2442, please +1 that request and post there your example

Renaming #2442 to hammer-and-pick

**Comment by G-Driver** [comment]
;) tnx didn't find that one

**Comment by tagliala** [comment]
:+1:
