### ISSUE TITLE
Instructionfix: CDN

### ISSUE THREAD

**Issue by mu5tach3** [FortAwesome/Font-Awesome#6088]
"<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">" 
the "http:" is missing at the "Get Started with…"-page

**Comment by tagliala** [comment]
@mu5tach3 that is not an error: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-developing-my-web-app-locally-file-and-icons-from-cdn-dont-show-up
