### ISSUE TITLE
centos can't display

### ISSUE THREAD

**Issue by Sunyson** [FortAwesome/Font-Awesome#6089]
anybody konw that?help me

**Comment by tagliala** [comment]
do you mean that FA doesn't work on CentOS? which version? which browser? which browser version? Does http://fontawesome.io/ work?

**Comment by Sunyson** [comment]
in centos 6.5,I deployment  a nodejs  application,use fa.  In windows , everything is  ok. Did I should setting something?

**Comment by tagliala** [comment]
sorry... I need also this answer: Does http://fontawesome.io/ work?

**Comment by Sunyson** [comment]
it's work . the only different is run in windows or centos6.5 .can u understand ？      😔发自网易邮箱大师
            在2015年03月29日 19:22，Geremia Taglialatela 写道:sorry... I need also this answer: Does http://fontawesome.io/ work?

**Comment by tagliala** [comment]
@Sunyson if fontawesome.io works then the issue is with your application so this is a support request, and you have to use stackoverflow.

Closing here, but feel free to comment

**Comment by Sunyson** [comment]
ok,thank u发自网易邮箱大师
            在2015年03月29日 20:11，Geremia Taglialatela 写道:@Sunyson if fontawesome.io works then the issue is with your application so this is a support request, and you have to use stackoverflow.

Closing here, but feel free to comment
