### ISSUE TITLE
Icon Request: icon-number-circle (numbers from 0 to 9)

### ISSUE THREAD

**Issue by Good4m** [FortAwesome/Font-Awesome#6099]
Would be nice to have 10 circular icons with each number inside. Perfect for numbered lists!

**Comment by kevinp8192** [comment]
+1  I just signed in to request this exact thing. Perfect for lists, and guiding users through card-based steps.  Thank you!

**Comment by jesseflorig** [comment]
@Good4m, @kevinp8192 - FWIW, you can do this with pure CSS: http://codepen.io/jesseflorig/pen/WbWwVK

Bonus: With a little tweaking, it'll work beyond 10 items.

**Comment by tagliala** [comment]
@jesseflorig thanks 

Probably the best solution

**Comment by kevinp8192** [comment]
@jesseflorig, @tagliala, thanks so much for posting. Actually, I was hoping to get a black and white number with a hollow circle around it that matched the rest of the FA paradigm. The bootcards only accepts image files for the "photocolumn" attribute. Here is a photo of the card stacks with the icon supplied. The numbers would allow to make the card stacks a step-by-step process, and each a card a numbered step.   
![image](https://cloud.githubusercontent.com/assets/11742601/6957823/ad11411a-d8c7-11e4-924f-dcd9b1212502.png)

**Comment by jesseflorig** [comment]
@kevinp8192 - I updated the pen to reflect the black and white outline style: http://codepen.io/jesseflorig/pen/WbWwVK 

As far as needing an image for the bootcard photocolumn, however you plan to convert Font Awesome's icon font into an image could be applied to the result of the code pen.

**Comment by kevinp8192** [comment]
@jesseflorig You are right...I wasn't thinking. In that instance I posted, I would require an image file, not the fa classes--I'll need to make those images myself quickly in illustrator, or find them elsewhere. I don't know what I was thinking.  :-)  Thank you for taking the time to show how it can be achieved with a custom CSS.  I did not know how to do it.

**Comment by MichelleGlauser** [comment]
I think having numbers all the way up to 100 would be great. 

I would be open to just using CSS, but all of the other items in a template I'm working on have font awesome icons assigned to them that automatically render on the page as the items are pulled from the database, so I'd have to re-write the whole thing with hard-coded icons to get just one of them to have an icon rendered with CSS instead of font awesome.

**Comment by jesseflorig** [comment]
@MichelleGlauser - This most certainly could be accomplished without rewriting the whole thing. If your content is database driven you could easily read a property to determine wether or not to use a font awesome class or generate a custom class for styling as you wish. If you insisted on font awesome classes you could even stack text on something like fa-circle or fa-square.

The biggest issues with what you're requesting is there is quite a bit of overhead for adding 100 new icons that are redundant to what could easily be done with HTML/CSS (not to mention there would need to be multiple sets of 100 for circle/square/outline/any other shape/style).

**Comment by byybora** [comment]
+1

**Comment by mmikowski** [comment]
+1 

At least then numbers 0-9, as CSS hacks won't work when translucency is required.  At present, I need these, and will probably create them myself.  How might I allocate font code?

**Comment by mmikowski** [comment]
**I created the svg icons and submitted a pull request.**  

If you need the icons now, you can find the SVG font file [here](https://raw.githubusercontent.com/mmikowski/Font-Awesome/master/fonts/circle-numbers.svg).
Grab the content and append the glyphs to the `fonts/fontawesome-webfont.svg` file and then proceed to convert it using an **svg-font-to-other-format** found on the web.  I am quite pleased with `http://www.fontconverter.org/`, although beware that `*.eot` files are not compressed like they are for official release.  The `woff` format conversion, though, is excellent.

**Comment by tagliala** [comment]
closing here and labeling as wontfix
