### ISSUE TITLE
Icon Request: fa-page-layout (or website layout)

### ISSUE THREAD

**Issue by stijnvanbael** [FortAwesome/Font-Awesome#6100]
Something like this

![layout-sidebar-at-left-icon](https://cloud.githubusercontent.com/assets/1050148/6892477/ac755ec6-d6c4-11e4-8c99-0f57ee4b9133.jpg)

**Comment by piernik** [comment]
I need it too. Here are some good examples: https://www.google.pl/search?q=layout+icon&client=opera&hs=es0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwlvLo4tHhAhVOlYsKHXeyAEEQ_AUIDigB&biw=1818&bih=979#imgrc=WSoZmMDNQ0HCPM:

**Comment by bartclaeys** [comment]
I would not call this `layout` but `grid` which would refer to [CSS grids](https://www.w3schools.com/css/css_grid.asp).

**Comment by aethior** [comment]
Hi @stijnvanbael,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/table-layout

Regards.

cc/ @tagliala
