### ISSUE TITLE
namespace all variables

### ISSUE THREAD

**Issue by ifahrentholz** [FortAwesome/Font-Awesome#6103]
please namespace all variables since the could easily be overwritten by mistake.

For example:

```
$phone: "\f095";
```

could be overwritten by a breakpoint variable called 

```
$phone: 468
```

**Comment by tagliala** [comment]
Hi,

all variables should be prefixed: https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss

Are you using an old version of FA?
