### ISSUE TITLE
Icon Request: fa-viadeo

### ISSUE THREAD

**Issue by Micht69** [FortAwesome/Font-Awesome#6105]
Hi,

It would be nice to have the Viadeo brand icon to complete social media icons.

For now, I use this kind of icon :
![viadeo](https://cloud.githubusercontent.com/assets/2040345/6898061/f969e6ba-d6f7-11e4-99e5-b081fc89c859.png)

Thanks for your work.

**Comment by tagliala** [comment]
dup of #886 , please +1 that request

closing here

**Comment by Micht69** [comment]
Strange, I searched for viadeo into the issues ...
Thanks.
