### ISSUE TITLE
Icon Request: Seene

### ISSUE THREAD

**Issue by kevinahuber** [FortAwesome/Font-Awesome#6106]
An icon for the 3d lens blur sharing app, Seene.

**Comment by aethior** [comment]
Seene was adquired by Snapchat in 2016 ([source](https://techcrunch.com/2016/06/03/snapchat-secretly-acquires-seene-a-computer-vision-startup-that-lets-mobile-users-make-3d-selfies/)). The app is not avaible on Google Play ([link](https://play.google.com/store/apps/details?id=com.obviousengine.seene.android.core)).

cc/ @tagliala
