### ISSUE TITLE
Icon Request: fa-stack-chart

### ISSUE THREAD

**Issue by sulemanmirza** [FortAwesome/Font-Awesome#6108]
Hi, 

It would be awesome if font-Awesome had more icons in the charts category, in this age of data visualization many people would find those icons useful to add in their dashboards, analytics applications, graphboards etc.

The one I am requesting is a stacked bar chart icon it may look anything like the one below, or if you have a better idea in mind. Please let me know how long would it take for that icon to be made.? 

![chart_column_stacked](https://cloud.githubusercontent.com/assets/1385300/6902227/bced88ae-d6cf-11e4-967c-68b1c284d51f.jpg)

**Comment by G-Driver** [comment]
+1

**Comment by jesseflorig** [comment]
:+1:

**Comment by diegopiriz** [comment]
+1

**Comment by nachomaro** [comment]
+1

**Comment by peluprvi** [comment]
Duplicated with #4271
Refers to #171

**Comment by rsiebeling** [comment]
+1

**Comment by aethior** [comment]
> Duplicated with #4271
Refers to #171

You're right.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.
