### ISSUE TITLE
Configurable @font-face { font-family: $fa-font-family }

### ISSUE THREAD

**Issue by chrisdpeters** [FortAwesome/Font-Awesome#6113]
I am building an HTML interface that must be mixed in with customers' HTML interfaces. Customers could end up including their own version of Font Awesome, thus clashing with my own. I'd like to be able to namespace the `font-family` within the `@font-face` declaration so that the version of Font Awesome I'm using doesn't clash with my customers'.

I'd be willing to figure out how to do this and submit a pull request, and soon. Do you find this to be a sensible variable to add to the Less and Sass versions? If so, which branch would you prefer that I push this to?

**Comment by tagliala** [comment]
Hi, 

Sorry, but this is a wontfix at the moment.

If you need to change the name of the font, you can use your own `_core.scss`/`_core.less`

Closing here
