### ISSUE TITLE
Icons are not working on Opera Mini browser

### ISSUE THREAD

**Issue by samihu** [FortAwesome/Font-Awesome#6116]
hi guys,

Its a great pleasure to use Font Awesome Icons on our website www.medplusmart.com. 
But i found issue on Opera Mini browser, icons are not displaying properly..

Can any one have solution for this issue.

![image](https://cloud.githubusercontent.com/assets/371737/6913439/d8854c86-d79d-11e4-9f9d-c792e2d696d1.jpg)

thanks
regards
SAM

**Comment by tagliala** [comment]
Hi, Opera mini doesn't support font face at allo so there is nothing we can do.

http://caniuse.com/#feat=fontface

Closing here

**Comment by tagliala** [comment]
If you must support opera mini, take a look here: https://github.com/encharm/Font-Awesome-SVG-PNG
