### ISSUE TITLE
Icon request: icon-folder-plus 

### ISSUE THREAD

**Issue by schepeev** [FortAwesome/Font-Awesome#6119]
I'm looking for a combination of the icons folder-o and plus-circle.
Usage: add a new folder to a tree structure 

Example:
![ouuee](https://cloud.githubusercontent.com/assets/11737672/6919976/ac113f3e-d7bb-11e4-9e63-7afcbb5f6fba.png)

**Comment by tagliala** [comment]
dup of #1525, please +1 that request

closing here
