### ISSUE TITLE
Icon request: icon-file-plus

### ISSUE THREAD

**Issue by schepeev** [FortAwesome/Font-Awesome#6120]
I'm looking for a combination of the icons file-text-o and plus-circle.
Usage: add a new item to a folder in a tree structure 

Example:
![x1ged](https://cloud.githubusercontent.com/assets/11737672/6920072/74a4b4d0-d7bc-11e4-8801-32ca06ea6284.png)

**Comment by tagliala** [comment]
dup of #1525, please +1 that request

closing here
