### ISSUE TITLE
Icon Request: fa-paper-cup-with-straw

### ISSUE THREAD

**Issue by rightarrowkeytim** [FortAwesome/Font-Awesome#6122]
we have a shopping cart we're using FA for [it's awesome btw!] and we have a need for a "water" or "soft drink", so something simple like a cup, can, drink or glass? thanks!

examples:
![cola_2-512](https://cloud.githubusercontent.com/assets/91199/6922503/3866d816-d791-11e4-8246-7ff94a7a5e6a.png)
![snack_time-14-512](https://cloud.githubusercontent.com/assets/91199/6922507/410fc414-d791-11e4-8ff2-6fd820352ac1.png)

**Comment by jbnv** [comment]
+1.

**Comment by gustafsons** [comment]
+1

**Comment by Crissov** [comment]
Will probably become [U+1F964](http://emojipedia.org/cup-with-straw/) in [Unicode 10.0](http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f964) #222

**Comment by tzeller** [comment]
i have created a softdrink icon which can be used
[fa-softdrinks.pdf](https://github.com/FortAwesome/Font-Awesome/files/1364633/fa-softdrinks.pdf)

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/cup-straw?s=solid
