### ISSUE TITLE
Icon Request: fa-vsco

### ISSUE THREAD

**Issue by rafamds** [FortAwesome/Font-Awesome#6123]
Hello everyone, how are you guys?
I wanted to make a request on this Social Network icon, I need it to a project I'm currently developing, and I'm sure many more users needed it before. So, I'll be glad if you could make this, its not very complicated, please please *.*

http://vsco.co/ - This is the networks website. 

Thanks in advance. Have a sunny day. :)

**Comment by soyo2** [comment]
+1

**Comment by tagliala** [comment]
dup of #2280, please +1 that request

closing here
