### ISSUE TITLE
Icon request: fa-stroller

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6124]
<img src="https://cdn3.iconfinder.com/data/icons/glyph/227/Stroller-1-512.png">

**Comment by jbnv** [comment]
+1.

**Comment by aethior** [comment]
Hi @G-Driver,

This icon was added in v5.6.0.
Check https://fontawesome.com/v6/icons/baby-carriage

Regards.

cc/ @tagliala
