### ISSUE TITLE
Icon Request: fa-cloud-synchronize

### ISSUE THREAD

**Issue by Sinedia** [FortAwesome/Font-Awesome#6129]
We already have fa-cloud, fa-cloud-upload and fa-cloud-download. But we miss one for synchronization. Adding that one would be great and much appreciated.

It could be used for applications that synchronize with cloud applications. The first two can be used for downloading and uploading to and from cloud providers, but you usually just wat to stay synchronized.

By the way i noticed a request for fa-cloud-o. I have no idea what was meant with that one, so if they mean the same thing these requests should be merged.

**Comment by nyon** [comment]
![selection_009](https://cloud.githubusercontent.com/assets/3247445/6964155/cc3e1de0-d946-11e4-9f32-f842e6956be5.png)

Like this? Added it to nyon/fontawesome-actions v0.3.0

fa-cloud-o coming soon

**Comment by Sinedia** [comment]
yeah, indeed like that. Except with a cloud in stead of a text balloon off course.

**Comment by nyon** [comment]
oh sorry, copied wrong icon, `fa-cloud-refresh` is now available in my repo

**Comment by Sinedia** [comment]
Can't find the icon, but it sounds like the fa-cloud icon with the sync on top of it and that's exactly what I meant. I can only say: I understand why you call it FontAwesone... because it's awesome how fast this is done :)

Thanks

**Comment by nyon** [comment]
I'm not the author of FontAwesome, I just created a superset of it here:

https://github.com/nyon/fontawesome-actions

You can download the new package directly on this page:

https://github.com/nyon/fontawesome-actions/releases

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it can already be made with the new Font Awesome Wizard! [Take a look at how it works.](https://blog.fontawesome.com/icon-wizard/)
