### ISSUE TITLE
fa-diamond is broken

### ISSUE THREAD

**Issue by ICON** [FortAwesome/Font-Awesome#6134]
FYI, fa-diamond is broken. that is all.

**Comment by tagliala** [comment]
Of course I can't confirm: http://jsfiddle.net/tagliala/wvquLyo9/3/

Please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here but feel free to comment
