### ISSUE TITLE
fa-beer faces wrong direction

### ISSUE THREAD

**Issue by opensourceame** [FortAwesome/Font-Awesome#6139]
Almost 90% of people are right handed. That means they pick up a beer with the handle on the right side. I think the icon would be more recognisable to the majority of folks if it was flipped horizontally by default.

**Comment by auge8472** [comment]
You can rotate and flip icons … and so you can flip the beer glas. See the point "rotated & flipped" at the [examples page](http://fontawesome.io/examples/), especially the class `fa-flip-horizontal`.

**Comment by tagliala** [comment]
hmmm @opensourceame is probably *right*, the icon should be horizontally flipped by default.

Adding to 4.3.1 milestone and assigning to @davegandy

**Comment by davegandy** [comment]
Since this would be a breaking change, I'll put it in 5.0.

**Comment by Bodge-IT** [comment]
+1 Yes this is much more useful than a basket icon.

**Comment by tagliala** [comment]
Fixed
