### ISSUE TITLE
Icon request: fa-universal-access

### ISSUE THREAD

**Issue by ndarville** [FortAwesome/Font-Awesome#614]
I am trying to move from Glyphish to Font Awesome, but I think Font Awesome needs some more icons to be competitive with Glyphish.

There has to be some official icon for those to toggle display settings, and the wheelchair icon seems too extreme.

I love [Apple’s](http://www.google.com/imgres?hl=en&safe=off&sa=X&tbo=d&tbm=isch&tbnid=__rXUH7SEA5HdM:&imgrefurl=http://community.wikia.com/wiki/User_blog:Sarah_Manley/Improving_Accessibility_on_Wikia&docid=Dr2Ee2CPddeenM&imgurl=http://images1.wikia.nocookie.net/__cb20101014211334/central/images/0/0b/Mac_accessability_icon.png&w=247&h=248&ei=Fc3kUN1mzoviBLDMgMAN&zoom=1&iact=hc&vpx=537&vpy=98&dur=1621&hovh=198&hovw=197&tx=72&ty=111&sig=108763388586863353628&page=1&tbnh=149&tbnw=148&start=0&ndsp=26&ved=1t:429,r:4,s:0,i:102&biw=944&bih=919), but they probably patented the hell out of it. Then again, it looks like GNU has [a similar icon](http://commons.wikimedia.org/wiki/File:Gnome-preferences-desktop-accessibility.svg). So maybe it’s fair game after all.

![Apple’s accessibility icon](http://i.imgur.com/4WmbE.png)

For now, I just use whatever eye icons are available—for dyslexia support—but it’s not too intuitive.

**Comment by davegandy** [comment]
Changed my mind. I really like this icon. Adding to 4.5.1, which is coming very soon.

**Comment by tagliala** [comment]
should be 4.6.0 if it contains new icons

**Comment by davegandy** [comment]
@tagliala There are very few new icons going in, and the ones going in are really focused around fixing a couple of issues (accessibility) that seems like a patch release, not a full release. What if we say a patch release can include a handful of new icons?

**Comment by davegandy** [comment]
Added to 4.6.0-wip branch. Closing.
