### ISSUE TITLE
Nuget FontAwesome.less problem

### ISSUE THREAD

**Issue by dimabutenko** [FortAwesome/Font-Awesome#6140]
I took NuGet package https://www.nuget.org/packages/FontAwesome.less/4.3.0

Source in package from NuGet.org
![Source in package from NuGet.org](https://cloud.githubusercontent.com/assets/6714627/6967381/8e53b834-d967-11e4-9667-12720a4abc55.png)

Source from github
![Source from github](https://cloud.githubusercontent.com/assets/6714627/6967397/aa1b20e8-d967-11e4-9cb7-d9900d604e22.png)

Can you please update NuGet package?

**Comment by janiukjf** [comment]
I noticed this a few days ago. I'll have to revert back to a previous version. There's other issues in some of the other files too. Variables that don't exist and what not. I think something happened with the compile to push this out to nuget.

**Comment by tagliala** [comment]
Hi, please take a look here: https://github.com/FortAwesome/Font-Awesome/issues/6067#issuecomment-86665985

**Comment by janstadt** [comment]
+1 on this. I pinged @kazimanzurrashid who looks to own the nuget repo but he hasnt responded to me with any updates.

**Comment by tagliala** [comment]
sorry but I don't have control on that repo
