### ISSUE TITLE
Icon request: pause-circle and stop-circle

### ISSUE THREAD

**Issue by 1tel** [FortAwesome/Font-Awesome#6141]
category: Video Player Icons. With a stop-circle it would be possible to bind a click event on a play-circle icon and replace the play-circle icon with the stop-circle icon. Look at my fiddle example and click on the play btn you will understand what I mean.
https://jsfiddle.net/frankroger/cqdkw9qo/4/

**Comment by aethior** [comment]
Hi @1tel,

[**fa-circle-pause**](https://fontawesome.com/icons/circle-pause) and [**fa-circle-stop**](https://fontawesome.com/icons/circle-stop) icons were added in v4.5.0.

Regards.

cc/ @tagliala
