### ISSUE TITLE
translate(0,0) breaks Visual Composer

### ISSUE THREAD

**Issue by MickeyKay** [FortAwesome/Font-Awesome#6142]
Not sure why you added the `translate(0,0);` CSS, but it is causing things to break in Visual Composer (and possibly elsewhere). Specifically, this breaks the icon layout for the Message Box component in Visual Composer.

Here's what things look like without the most recent version of Font Awesome CSS included:
![image](https://cloud.githubusercontent.com/assets/3189678/6970278/50581946-d929-11e4-908d-644df3c9d90b.png)

And here's what it looks like with your CSS from v4.3.0 included:
![image](https://cloud.githubusercontent.com/assets/3189678/6970269/3db89d10-d929-11e4-9421-366e36bfc99c.png)

Visual Composer includes the following rule: `transform: translate(-50%, -50%);`

However this is being overruled by your `translate(0, 0);` rule. Again, not sure why this rule is in there, but it seems kinda generic. Can you clarify why this is in there?

**Comment by tagliala** [comment]
@MickeyKay it improves rendering in firefox, but it will be removed because of #6023 

closing here but feel free to comment here or on #6023
