### ISSUE TITLE
Icon request: fa-package

### ISSUE THREAD

**Issue by leandroruel** [FortAwesome/Font-Awesome#6143]
would be great if you add an icon like this:
![](http://thehuntingtonian.com/wp-content/uploads/2014/12/package_pic.jpg)
 a package, is very useful to represent any deliver of a product, or something else related with shopping or delivery

```html
<i class='fa fa-package'></i>
```

**Comment by tagliala** [comment]
duplicate of #908 , please +1 that request

closing here
