### ISSUE TITLE
Icon request: user-search

### ISSUE THREAD

**Issue by mak0t0san** [FortAwesome/Font-Awesome#6144]
This icon would essentially be a combination of user and search.  It would have the user icon with a magnifying glass on/next to it.

This icon would be used to search for people/users.

**Comment by benjwgarner** [comment]
+1

**Comment by tagliala** [comment]
Refers to #1181 

Please take in consideration https://github.com/nyon/fontawesome-actions

**Comment by nyon** [comment]
Added search operator, and thus user-search, to fontawesome-actions

![selection_010](https://cloud.githubusercontent.com/assets/3247445/7020341/8826e062-dd18-11e4-80d6-e21e1b9951a2.png)

**Comment by tagliala** [comment]
@nyon thanks!

**Comment by mak0t0san** [comment]
Thanks! Much appreciated.
