### ISSUE TITLE
Icon Request: Moutain_Bike

### ISSUE THREAD

**Issue by AnthoT** [FortAwesome/Font-Awesome#6148]
Hi,
We have a cycling company who organizes cycling trip around the word.
We already use the Bicycle icon for our road bike trip, but we also have moutain bike trips and we would represent the difference with an icon.
![icon_mtb](https://cloud.githubusercontent.com/assets/11787634/6984772/6e602ca4-d9fa-11e4-8434-edc58470c791.png)

Thank you :-)

**Comment by aethior** [comment]
@tagliala `transportation (category)` label for this request?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/person-biking-mountain?f=classic&s=solid
