### ISSUE TITLE
Icon request: icon-collection

### ISSUE THREAD

**Issue by ndarville** [FortAwesome/Font-Awesome#615]
I am trying to move from Glyphish to Font Awesome, but I think Font Awesome needs some more icons to be competitive with Glyphish.

When I say collection, I mean something to represent collections of bookmarks, subscriptions, saves, saves, a feed (of updates), etc.

I currently two Glyphish icons for this: [this one](https://github.com/ndarville/pony-forum/blob/master/forum/static/glyphish/44-shoebox.png): a full full inbox icon, which will probably cut it fine: ![Glyphish icons](https://raw.github.com/ndarville/pony-forum/master/forum/static/glyphish/44-shoebox.png).

This would mean that `icon-inbox` should change to `icon-inbox-empty`, however, if that is any complication.

Another one I use is Glyphish’s [own collection icon](https://github.com/ndarville/pony-forum/blob/master/forum/static/glyphish/191-collection.png): ![Glyphish icon](https://github.com/ndarville/pony-forum/raw/master/forum/static/glyphish/191-collection.png).

---

To get an idea of what I'm trying to do, here is a demo link to my project using the default Glyphish image icons in the navigation bar I intend to migrate from to Font Awesome: https://fontawesome-darville.dotcloud.com. `admin//password`.

I might need some more icons first, though.

**Comment by sensibleworld** [comment]
<img width="290" alt="Screen Shot 2021-03-30 at 1 28 34 PM" src="https://user-images.githubusercontent.com/529604/113030645-d49c5a00-915b-11eb-9004-fdbc97e7210f.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download

<img width="265" alt="Screen Shot 2021-03-30 at 1 28 59 PM" src="https://user-images.githubusercontent.com/529604/113030720-e4b43980-915b-11eb-964b-f7fd4d88222f.png">
