### ISSUE TITLE
Icon request: square brackets [ ]

### ISSUE THREAD

**Issue by ali-smith** [FortAwesome/Font-Awesome#6151]
icon brackets would help simplify styling/spacing issues that regular keyboard-generated brackets have.  For example, I'd love to make these brackets justified.  It's a headache.  With icons, it would be simple!
![screen shot 2015-04-04 at 11 06 30 am](https://cloud.githubusercontent.com/assets/9098728/6993932/b54f3734-daba-11e4-8d50-5a8011069e7f.png)

**Comment by tagliala** [comment]
font icons are text :)

http://jsfiddle.net/tagliala/e9yfxsfj/12/

**Comment by alipsmith** [comment]
Very cool.  Thank you!  

However, I'd still love to have them as straight-forward icons. Just sayin'.
