### ISSUE TITLE
Icon Request: fa-feet

### ISSUE THREAD

**Issue by skoslitz** [FortAwesome/Font-Awesome#6152]
We at [IfL](https://github.com/IfL-VK) are currently writing a web-based guide about german landscapes and using Font-Awesome intensely (thanks by the way for your great work!). For our usage we need a vector icon about foot or feet. Some possible use cases could be:
- Tell about an excursion on foot
- Communicate something within foot distance 

The icon should have an unisex character. I've found nice examples on the NounProject [1](https://thenounproject.com/term/footprint/5101/), [2](https://thenounproject.com/term/boot/44523/) 

Yours truly
skoslitz

**Comment by moshevds** [comment]
:thumbsup:

I would like fa-feet for a similar reason.

**Comment by peiche** [comment]
+1

**Comment by tagliala** [comment]
is this a duplicate of #3175?

**Comment by tagliala** [comment]
No feedback, closing here
