### ISSUE TITLE
Icon Request: fa-window-closed (house window)

### ISSUE THREAD

**Issue by knowthelist** [FortAwesome/Font-Awesome#6153]
We need for our Home Automation UI two new icons to show the window state:

https://github.com/knowthelist/fhem-tablet-ui

**Comment by luusb** [comment]
Hello, also a tilted version of the window would be nice if you have a three state sensor.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=window-frame
