### ISSUE TITLE
Icon Request: fa-factory

### ISSUE THREAD

**Issue by NickolasAcosta** [FortAwesome/Font-Awesome#6154]
I am building a website for electricians and had the idea that having icons for "Residential", "Commercial" or "Industrial" would be a good idea. Many contractors like to show they offer services in all three areas.  

I consider the fa-home to be good for residential, and fa-building to be good for commercial, but couldn't find a suitable icon for Industrial.

I was thinking it could be another building icon but with more of a factory look, maybe an exhaust pipe coming out the top indicate it was some type of factory.

RCI!

**Comment by tagliala** [comment]
dup of #1330 , please +1 that request

closing here
