### ISSUE TITLE
Icon request:icon-balance

### ISSUE THREAD

**Issue by manicko** [FortAwesome/Font-Awesome#6156]
It would be nice to have this kind of image for the cases than person have an opportunity to compare products. For lots of sites you can see the compare button thus the scale or balance icon is a good option.
Here is an example:
![dcromakc9](https://cloud.githubusercontent.com/assets/1097057/6996371/00d6e97c-db8d-11e4-95a4-8decc27de9fb.jpeg)

**Comment by tagliala** [comment]
dup of #276 , please +1 that request

closing here
