### ISSUE TITLE
Icon request: icon-tv or icon-flatscreen

### ISSUE THREAD

**Issue by AlessioPellegrini** [FortAwesome/Font-Awesome#6157]
![](https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/widescreen_tv.png)

![](http://cdn3.freepik.com/image/th/318-33015.png)

**Comment by auge8472** [comment]
What's wrong with [fa-desktop](http://fontawesome.io/icon/desktop/)?

**Comment by tagliala** [comment]
thanks @auge8472 

Closing here

please +1 #368 if you are interested in an old style tv
