### ISSUE TITLE
Use of font-awesome icons in desktop applications / Standard Icon naming

### ISSUE THREAD

**Issue by SylvainCorlay** [FortAwesome/Font-Awesome#6159]
Opening an issue here in case someone is interested in using Font Awesome icons in desktop applications, they might want to have a look at [qtawesome](https://github.com/spyder-ide/qtawesome), which allows to use font awesome glyphs as standard QIcons in PyQt and PySide applications. 

```python
import qtawesome as qta
fa_icon = qta.icon('fa.flag')
fa_button = QtGui.QPushButton(fa_icon, 'Font Awesome!')
```
We support styling, stacking icons, and animations. Our primary motivation is to use Font Awesome for the icon set of the [Spyder IDE](https://github.com/spyder-ide/spyder) (Spyder is a desktop IDE for the Python programming language). 
As we are working on the transition to font-awesome, we naturally missed a few icons, and I create a short list of glyphs to fill the gap. I know that you don't take PRs with icons, but I would be glad to contribute them, should you be interested.

Regarding the naming of icons, it could be interesting in the context of using font-awesome for desktop applications to either create aliases following the naming conventions from the [FreeDesktop specifications](http://freedesktop.org/wiki/Specifications/icon-naming-spec) or to create mapping to names following the freedesktop specifications. This could help defining creating standard themes for Qt / KDE based on Font Awesome.

**Comment by soroush** [comment]
:+1:  
I'm working on an auto-generated Qt resources file that uses font-awsome SVG icons. My script also generates an index.theme file. Together with resources, these can be used as a regular theme for desktop applications in Qt.
The only problem is standard naming that you already mentioned. There is no mapping from FA naming to FreeDesktop standard icon names.
I am going to make and maintain a list of such mapping. These names can be used as aliases (in Qt resource file) over original FA names:

```
<!DOCTYPE RCC>
<RCC version="1.0">
<qresource prefix="/ui/images">
    <file alias="edit-copy">regular/copy.svg</file>
</qresource>
</RCC>

```

**Comment by tagliala** [comment]
Hi @soroush thanks for your effort. Feel free to open a wiki page with the list of aliases

**Comment by adrelino** [comment]
> I'm working on an auto-generated Qt resources file that uses font-awsome SVG icons. My script also generates an index.theme file. Together with resources, these can be used as a regular theme for desktop applications in Qt.
> The only problem is standard naming that you already mentioned. There is no mapping from FA naming to FreeDesktop standard icon names.
> I am going to make and maintain a list of such mapping. These names can be used as aliases (in Qt resource file) over original FA names:
> 
> ```
> <!DOCTYPE RCC>
> <RCC version="1.0">
> <qresource prefix="/ui/images">
>     <file alias="edit-copy">regular/copy.svg</file>
> </qresource>
> </RCC>
> ```

@soroush where can I find the mapping from FA naming to FreeDesktop standard icon names?
