### ISSUE TITLE
Icon request: registration

### ISSUE THREAD

**Issue by ndarville** [FortAwesome/Font-Awesome#616]
I am trying to move from Glyphish to Font Awesome, but I think Font Awesome needs some more icons to be competitive with Glyphish.

A regular user icon with a plus sign to the right will suffice: ![Glyphish icon](https://github.com/ndarville/pony-forum/raw/master/forum/static/glyphish/111-user.png)+

---

To get an idea of what I'm trying to do, here is a demo link to my project using the default Glyphish image icons in the navigation bar I intend to migrate from to Font Awesome: https://fontawesome-darville.dotcloud.com. `admin//password`.

I might need some more icons first, though.

**Comment by asssagar** [comment]
Try user-plus 
http://fortawesome.github.io/Font-Awesome/icon/user-plus/
