### ISSUE TITLE
Icon Request: icon-ltc

### ISSUE THREAD

**Issue by AKnightWhoSaysNi** [FortAwesome/Font-Awesome#6162]
Using for a Lite Coin faucet.
![litecoin](https://cloud.githubusercontent.com/assets/5151984/7001301/0615c742-dbeb-11e4-89d3-3314d83f1990.png)

**Comment by AKnightWhoSaysNi** [comment]
Found a better example: https://thenounproject.com/term/litecoin/90366/

**Comment by tagliala** [comment]
dup of #1768, please +1 that request

closing here
