### ISSUE TITLE
Icon Request: fa-credit

### ISSUE THREAD

**Issue by kmanizoro** [FortAwesome/Font-Awesome#6163]
Hi team!,
               please add new Icon likes..
1) some files in progress
2)some files submitted
3)some files finished
4)add some new bank related icons like( loan,credits & some etc.. )

**Comment by tagliala** [comment]
hi,

I need to close this request because it does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please take a read and open proper requests, having care of searching for duplicates before
