### ISSUE TITLE
Icon request: icon-chef

### ISSUE THREAD

**Issue by rscampanero** [FortAwesome/Font-Awesome#6164]
![cook_cooking_food_kitchen_chef_hat_restaurant-128](https://cloud.githubusercontent.com/assets/11813981/7003010/4d7341dc-dc86-11e4-8333-2a0f3855df10.png)

![chef_hat-256](https://cloud.githubusercontent.com/assets/11813981/7003006/431e8d04-dc86-11e4-9759-9517c46ac3a8.png)

Hi im currently designing a culinary website but i cannot find a "Chef Hat" icon from the list of our icons. 
Hope you can design this one.

**Comment by tagliala** [comment]
dup of #2598 , please +1 that request

closing here
