### ISSUE TITLE
Icon Request: fa-led

### ISSUE THREAD

**Issue by KermadecI** [FortAwesome/Font-Awesome#6165]
Hi
need an icon led illumination.
I attach a image done by me.
Thanks for the help, may you write an email when done?
Regards
Matteo Andreatta
![led](https://cloud.githubusercontent.com/assets/11716776/7003024/3f92f7f6-dc54-11e4-959c-a09250c1eb0d.jpg)

**Comment by tagliala** [comment]
Duplicate of #5759, please +1 that request and post there your example

closing here
