### ISSUE TITLE
Add spanner filter to icon-wrench

### ISSUE THREAD

**Issue by dancingmongoose** [FortAwesome/Font-Awesome#6173]
Would simply be an alias for the existing wrench icon. 

In some countries such as my own we call them spanners and I've never heard anyone refer to it as a wrench

**Comment by Khrysller** [comment]
In my country is "chave de boca".

A wrench (also called a spanner)
http://en.wikipedia.org/wiki/Wrench

**Comment by aethior** [comment]
> A wrench (or spanner outside of North America) is a tool used to provide grip and mechanical advantage in applying torque to turn objects—usually rotary fasteners, such as nuts and bolts—or keep them from turning.

(source: [en.wikipedia.org/wiki/Wrench](https://en.wikipedia.org/wiki/Wrench))

cc @tagliala
