### ISSUE TITLE
Icon request: fa-tooth and fa-tooth-o

### ISSUE THREAD

**Issue by ximreh** [FortAwesome/Font-Awesome#6175]
Please include in the medical icons section
![fa-tooth](https://cloud.githubusercontent.com/assets/7629142/7021459/6f9bbb5a-dd2a-11e4-9021-04d47e2cbb3a.png)
![fa-tooth-o](https://cloud.githubusercontent.com/assets/7629142/7021460/73960378-dd2a-11e4-9df4-7f5db3d0a5e6.png)
Will be used in software made for dentists.

**Comment by G-Driver** [comment]
@tagliala / @ximreh  a dup of https://github.com/FortAwesome/Font-Awesome/issues/1289

**Comment by tagliala** [comment]
@G-Driver thanks, really appreciate

closing here

**Comment by bo33b** [comment]
+1
