### ISSUE TITLE
Icon request: fa-teeth

### ISSUE THREAD

**Issue by ximreh** [FortAwesome/Font-Awesome#6176]
Please include in the medical icons section

![fa-teeth](https://cloud.githubusercontent.com/assets/7629142/7021602/17d9818e-dd2c-11e4-896c-1ca028390da8.png)

**Comment by tagliala** [comment]
what could be a different use case from #1289 ?

**Comment by HLFH** [comment]
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/1289.

Please close. @tagliala
