### ISSUE TITLE
Icon request: icon-user-profile

### ISSUE THREAD

**Issue by ndarville** [FortAwesome/Font-Awesome#618]
I am trying to move from Glyphish to Font Awesome, but I think Font Awesome needs some more icons to be competitive with Glyphish.

[Here](https://github.com/ndarville/pony-forum/blob/master/forum/static/glyphish/123-id-card.png) is the one I currently use with Glyphish ![Glyphish icon](https://github.com/ndarville/pony-forum/raw/master/forum/static/glyphish/123-id-card.png).

* * *

To get an idea of what I'm trying to do, here is a demo link to my project using the default Glyphish image icons in the navigation bar I intend to migrate from to Font Awesome: https://fontawesome-darville.dotcloud.com. `admin//password`.

**Comment by henleywc** [comment]
+1

**Comment by corydoras** [comment]
@tagliala Any chance this one could get some love?

**Comment by tagliala** [comment]
@ndarville

Sorry but I just noticed that there is a more recent duplicate #825 which has more +1s than this one. I'm going to close this one in favour of #825

@corydoras

Sorry but icons are up to Dave, I don't know his plans at all. I'm just taking care of issues, minor css stuff and bugs. Anyway, #825 is quite popular, it may have chances of being included.

If you need this icon please consider a custom build of fontawesome.

Take a look at:
https://fonticons.com/ (by Dave - adding custom icons is not possible in the free tier)
http://fontello.com/
http://icomoon.io/app/#/select
http://fontastic.me/

Closing here

**Comment by tagliala** [comment]
No need to +1 #825, I will do it by myself

**Comment by saeed-m** [comment]
+1

**Comment by SMHFandA** [comment]
+1
