### ISSUE TITLE
Icon request: Itunes and Bandcamp

### ISSUE THREAD

**Issue by trixbengel** [FortAwesome/Font-Awesome#6181]
For people like me who build webpages for artists and bands in wordpress, it would be great to have icons for itunes  http://www.itunes.com and Bandcamp, https://bandcamp.com . Also Tidal http://www.tidal.com would be good. All of these are services used by most musical artists, and would be great to have as icons along others like facebook etc..

**Comment by tagliala** [comment]
please +1 the following requests:

itunes #919, bandcamp: #1725 

closing here
