### ISSUE TITLE
Icon request: fa-disc

### ISSUE THREAD

**Issue by Vaxent** [FortAwesome/Font-Awesome#6182]
Hi, a disc icon would be usefull, even if optical discs are not so used anymore.

In my app, I could use that icon to bring out elements of a collection which still need a CD.

Thanks :)

**Comment by shaedrich** [comment]
+1

**Comment by G-Driver** [comment]
@tagliala / @Vaxent / @shaedrich I think this is a dup of https://github.com/FortAwesome/Font-Awesome/issues/702

**Comment by tagliala** [comment]
@G-Driver thanks, it is

closing here
