### ISSUE TITLE
Icon Request: fa-battery

### ISSUE THREAD

**Issue by francis202** [FortAwesome/Font-Awesome#6183]
![battery-icon-1](https://cloud.githubusercontent.com/assets/11854742/7046670/beb14eca-de07-11e4-9ec1-08198bb51067.png)
![battery-icon-2](https://cloud.githubusercontent.com/assets/11854742/7046672/c0fc58aa-de07-11e4-9883-dc190dfe3dd1.png)

**Comment by tagliala** [comment]
dup of #2148 , please +1 that request

closing here
