### ISSUE TITLE
Bower exclude src

### ISSUE THREAD

**Issue by drissamri** [FortAwesome/Font-Awesome#6184]
When using font awesome with bower, it downloads all the source files. 

In the bower.json there's an exclude on src, but shouldn't this include a wildcard or something to avoid a couple of hundred src files?

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json#L14 <-- isn't this enough?

**Comment by drissamri** [comment]
My bad, we are working on the 4.0.3 branch where there is no bower.json yet... :-)

**Comment by tagliala** [comment]
@drissamri glad you solved :+1:
