### ISSUE TITLE
Icon Request: fa-bath & fa-living

### ISSUE THREAD

**Issue by twinshen** [FortAwesome/Font-Awesome#6185]
Thank you for adding the bed icon in the 4.3 version. Would it be possible to add another two icons (bathroom and living room) to the next version? This would be really helpful for people that work with properties and letting agencies.

Example:
Bathroom icon: https://cdn2.iconfinder.com/data/icons/cosmo-furniture/40/bath-128.png
Living room icon: https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/256/sofa.png

Thank you

**Comment by tagliala** [comment]
@twinshen you have nice examples

Please post your bathroom example here: #708 and your sofa here #759 

Closing here
