### ISSUE TITLE
Icon request: fa-file-search-o (icon-document-viewer)

### ISSUE THREAD

**Issue by Akhilospro** [FortAwesome/Font-Awesome#6190]
![view](https://cloud.githubusercontent.com/assets/11870984/7066760/5d47acec-dee3-11e4-803b-9e2ebdd30e14.png)

Please provide an icon for document viewer like the above.
Thanks

**Comment by magoo-pl** [comment]
+1

**Comment by liptonbeer** [comment]
+1

**Comment by ajones4** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/file-magnifying-glass?f=classic&s=solid
