### ISSUE TITLE
Icon Request: icon-crawler icon-spider

### ISSUE THREAD

**Issue by sw0o0sh** [FortAwesome/Font-Awesome#6191]
For programs that scrape, crawl, spin, etc., I think this would be a useful icon. Certainly not too narrow of a use-case? I would be so appreciative :), as I love your guys work!!

![spider](https://cloud.githubusercontent.com/assets/1929422/7079105/7c927e3c-deee-11e4-973a-96f14b6f3c1c.png)

**Comment by tagliala** [comment]
dup of #828  , please +1 that request

closing here

**Comment by Esysteme** [comment]
+1

**Comment by vndevil** [comment]
+1

**Comment by dkokkinos** [comment]
+1
