### ISSUE TITLE
Icon request: icon-flag-uk (Union Jack)

### ISSUE THREAD

**Issue by geozei** [FortAwesome/Font-Awesome#6193]
Hello i think it would be good idea if flags are added to your repository

ex  icon-gr
icon-uk

https://d30y9cdsu7xlg0.cloudfront.net/png/26056-84.png
https://d30y9cdsu7xlg0.cloudfront.net/png/16671-200.png

Thank you!

**Comment by jakubstrama** [comment]
how would you display Poland or Germany in B&W?

**Comment by tagliala** [comment]
As pointed out by @jakubstrama  you can't represent most flags in single color

@geozei you should consider an .svg based solution like http://lipis.github.io/flag-icon-css/

BTW a request for the union jack is fine, renaming as `Icon request: icon-flag-uk (Union Jack)`

**Comment by tagliala** [comment]
Additional note: a comprehensive set of flags is out of the scope of Font Awesome

**Comment by auge8472** [comment]
I think, it's better to use a SVG graphic (with all the needed colours for every single flag) instead.

**Comment by tagliala** [comment]
@auge8472 I do agree that it is the best choice

I'm leaving this open for tracking purposes

**Comment by tagliala** [comment]
Sorry, I need to close this one
