### ISSUE TITLE
Icon Request: fa-fragrance

### ISSUE THREAD

**Issue by nepa** [FortAwesome/Font-Awesome#6194]
I'm in need of an icon that depicts a perfume sprayer. I suppose a classical, rather 'female bottle' with huge bellows would fit best. However, I'd also appreciate a more 'masculine' sprayer (e.g. upper left corner of second example).

Use cases:
- Category icon in a web shop or personal blog.
- Icon for a beauty store on a map.

Examples:
http://beauty-healthcare.org/material/064.png

Bottle in upper right corner:
http://cdn.vectorstock.com/i/composite/57,91/perfume-icon-vector-1825791.jpg

**Comment by tagliala** [comment]
dup of #5717, please +1 that request and post there your example

Renaming #5717 to add fragrance in the title
