### ISSUE TITLE
Icon Request: fa-matryoshka

### ISSUE THREAD

**Issue by nepa** [FortAwesome/Font-Awesome#6195]
I'm in need of a Matryoshka icon (Russian nesting doll).

Use cases:
- Category icon in a web shop.
- Represent Russia on a travel blog or web site.
- Represent things being nested.
- Toy doll for kids.

Examples:
![babuschka](https://cloud.githubusercontent.com/assets/772192/7086898/5307fe50-df86-11e4-81d1-68914e933c47.jpg)

**Comment by G-Driver** [comment]
+1

**Comment by vlsoprun** [comment]
+1

**Comment by scherre** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by ksn135** [comment]
👍

**Comment by AndrewCodeman** [comment]
+1

**Comment by tagliala** [comment]
Available in FA6 Pro: https://fontawesome.com/v6.0/icons/nesting-dolls?s=solid
