### ISSUE TITLE
 Icon request: icon-store

### ISSUE THREAD

**Issue by shurub3l** [FortAwesome/Font-Awesome#6196]
I need an icon that represents a store or a shop.
It can be used next to the address of your local store/shop, or where you present a list of stores.

![fa-shop](https://cloud.githubusercontent.com/assets/4004313/7087582/81986412-df95-11e4-9516-eab032376b86.jpg)

**Comment by tagliala** [comment]
dup of #1958 , please +1 that request

closing here
