### ISSUE TITLE
Icon Request: icon-opensource

### ISSUE THREAD

**Issue by cedricve** [FortAwesome/Font-Awesome#6200]
https://www.google.be/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=open%20source%20icon

**Comment by sekjal** [comment]
Would be good for comparing different software solutions in a list.  +1

**Comment by caduvieira** [comment]
+1

**Comment by Grimdari** [comment]
Definitely a +1.

**Comment by abbynucup** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1283, please +1 that request

closing here
