### ISSUE TITLE
Icon Request: fa-reset

### ISSUE THREAD

**Issue by SteveTheTechie** [FortAwesome/Font-Awesome#6203]
I request a FontAwesome icon for a reset.  I have several buttons for resetting settings to defaults, and it would be nice to have a corresponding icon for those buttons.  I have looked on the internet, and there are icons that have been created for this elsewhere.

Here are a couple of examples that I think could be used as a starting place:
http://i.stack.imgur.com/AMqfI.png
http://www.iconsdownload.net/icons/256/13082-reset-arrow-icon.png

**Comment by tagliala** [comment]
Hmmm... undo should fit your use case: http://fontawesome.io/icon/undo/

**Comment by dosaki** [comment]
If you have an undo button using `fa-undo` icon and you want a reset option, you should not use the same icon.
Some applications use icons similar to this: http://i.stack.imgur.com/zR6qq.jpg as well

**Comment by tagliala** [comment]
it almost looks like an undo action. Looking for a reset icon on google image, I see that most of the icons are like undo. IMHO `fa-undo` and the proposed `fa-reset` side by side are confusing

https://www.google.it/search?q=reset+icon&espv=2&biw=1273&bih=717&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMItPSYmK68xwIVA30aCh0xag0_

**Comment by tagliala** [comment]
Maybe #239 ?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

**In a web application** it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/81/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
