### ISSUE TITLE
Icon Request: icon-butterfly or icon-bttrfly (brand)

### ISSUE THREAD

**Issue by polaris340** [FortAwesome/Font-Awesome#6205]
Can you make a butterfly icon with this image?
This is an existing app's icon, so it can be a brand icon.
![Image for Butterfly icon](http://bttrfly.co/static/res/img/icon.png)

**Comment by coffeelady** [comment]
+1 Different Butterflies were great... ^_^

**Comment by remypar5** [comment]
+1

**Comment by diomed** [comment]
+1 for fa-butterfly

**Comment by WebVantage** [comment]
+1

**Comment by jonnitto** [comment]
In the list of animals, the butterfly is definitely a missing one

**Comment by tagliala** [comment]
> This is an existing app's icon, so it can be a brand icon.

Please note that this is a request for a brand, not for a butterfly

Also, example doesn't work anymore and I cannot find information about this brand

If you want to request a butterfly, feel free to start a new request

**Comment by tagliala** [comment]
@polaris340 could you please provide more information about this brand and fix the example in the OP?

**Comment by tagliala** [comment]
Closing here

**Comment by diomed** [comment]
@tagliala why did you close this???

this could serve as request for normal butterfly icon.
it wasn't specified in first posts at all.

**Comment by tagliala** [comment]
@diomed please +1 #15399 for a butterfly, this request was about a brand that apparently is not available anymore, I didn't get feedback from the author and the number of upvotes is not enough to keep this open
