### ISSUE TITLE
Showing empty square in Chrome

### ISSUE THREAD

**Issue by paaljoachim** [FortAwesome/Font-Awesome#6206]
Hey

I use WordPress and have added into the code to the child theme functions file and the icons to the CSS.
The result is a grey outlined square in Chrome.
Opera for a moment shows the same outlined squares before jumping onward to the correct icons.
Firefox shows the correct icons right away.

What should I do to fix this?

Have a great day!

**Comment by tagliala** [comment]
Hi, you should check your development console and make sure that you are loading the proper version of fontawesome and that you are not using javascript files that could interfer with rendering of `:before` pseudo elements

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

pay attention to point 4.

Closing here but feel free to comment

**Comment by paaljoachim** [comment]
Hey tagliala!

Thank you! A simple problem of forgetting to update the maxcdn link to the newest.

**Comment by tagliala** [comment]
@paaljoachim you're welcome, glad you solved :+1:

**Comment by Namwanza** [comment]
Make sure to  close your 

> <link />

 in your `<head></head>`

for example;
```
<head>
    <link rel="stylesheet" href="../css/font-awesome.css" />
    <link rel="stylesheet" href="../css/font-awesome.min.css" />
</head>
```
This solved my problem.
