### ISSUE TITLE
Underline on Font Awesome

### ISSUE THREAD

**Issue by ezequias** [FortAwesome/Font-Awesome#6208]
Hello everyone

I am in trouble to remove a hyperlink underline in a page using a fontawesome icon.

I tried use the css configuration like

*HTML
	<li> <a href="http://www.apple.com"> <span class="icon fa-play-circle-o major style3"><span class="style3">Dolor</span></span></li>
*CSS
	a:link, a:visited { 
			text-decoration: none;
			cursor: auto;
	}

I am attaching an image that shows the problem on my site. When I hover the mouse the underline link disappears but not when the mouse is not hovering.

![iconsfa](https://cloud.githubusercontent.com/assets/539561/7107162/cb1fdfe6-e131-11e4-8003-95c4453495c1.png)

**Comment by tagliala** [comment]
Hi @ezequias , since this is a support request I'm going to close this one, but as I said I can help you so feel free to keep commenting.

It seems that the default behaviour is to not underline icon: http://jsfiddle.net/tagliala/wvquLyo9/4/

Please provide me a fiddle or inspect your development console to find the offending css rule

**Comment by ezequias** [comment]
@tagliala 

Would be better if you have the html and css as I have here?

You can download the page on: http://html5up.net/spectral/download

Best regards
Ezequias Rocha

**Comment by tagliala** [comment]
@ezequias a working example is better. a fiddle like the above one with the minimum amount of code showing your issue would be perfect

**Comment by ezequias** [comment]
@tagliala 

My big problem is the size of my css file, anyway I could generate the error.

See the fiddler I generated: https://jsfiddle.net/tagliala/wvquLyo9/4/

Thanks in advance.

Regards
Ezequias

**Comment by tagliala** [comment]
@ezequias I'm still seeing my fiddle. Please remember to push the "update" button and give me the new link

**Comment by ezequias** [comment]
Sorry and thank you @tagliala - here is the correct link: https://jsfiddle.net/wvquLyo9/5/

**Comment by tagliala** [comment]
this rule `border-bottom: dotted 1px;` in the `a` tag is creating your issue. You should remove it or override it, someting like:  https://jsfiddle.net/tagliala/wvquLyo9/6/

**Comment by ezequias** [comment]
Thank you very much for your time @tagliala you are right.

**Comment by tagliala** [comment]
you're welcome :+1:

**Comment by ahmedhamodi** [comment]
Almost 7 years later and I had this same issue. Everyone online suggestion to do `text-decoration: none`, which works on normal links but not with font awesome icons and links. `border: none` worked. Thanks! You deserve more thumbs up on that comment - surprised not many people ran into this issue.
