### ISSUE TITLE
Icon Request: Rupee Symbol

### ISSUE THREAD

**Issue by vin-ai** [FortAwesome/Font-Awesome#621]
It would be great if you add Rupee (₹) symbol. If you can't please tell me how can I do it.

![](http://thezerolife.com/kobnaghar/wp-content/uploads/Indian_Rupee_Symbol_Foradian_Version2.0and3.0TheZeroLife.Com_thumb.jpg)

[Read about ₹](http://thezerolife.com/460/indian-currency-symbol-how-to-implement-historical-memory-collection)

**Comment by coolwidgets** [comment]
Use <i class="fa fa-rupee"></i>
