### ISSUE TITLE
Icon Request: fa-guarantee

### ISSUE THREAD

**Issue by orbitalthread** [FortAwesome/Font-Awesome#6210]
A guarantee icon that could represent a guarantee for a product or service (example: Money back guaranteed).

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by orbitalthread** [comment]
here a couple of examples: 
https://goo.gl/310dnm
https://goo.gl/KPNaOL
https://goo.gl/WLCJZI

**Comment by tagliala** [comment]
ok, dup of #1182, please +1 that request

closing here
