### ISSUE TITLE
Icon Request: fa-envelope-open / fa-envelope-o-open / fa-envelope-square-open

### ISSUE THREAD

**Issue by carlosmacias** [FortAwesome/Font-Awesome#6219]
I think it's a good idea to have this three icons to complement the closed icons.

**Comment by magoo-pl** [comment]
+1

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by tagliala** [comment]
dup #897, please +1 that request

closing here.

Please also mention me if there are duplicates I didn't notice
