### ISSUE TITLE
Chopp Mug

### ISSUE THREAD

**Issue by ezequias** [FortAwesome/Font-Awesome#6228]
Hi

I am planning to produce a website with a pub thematic and I see FA has not much elements for this theme.

I would like to suggest this mug here.

![beer](https://cloud.githubusercontent.com/assets/539561/7151396/ce3697b8-e2ff-11e4-97f8-0eb1cba4c286.png)
ps: I have the svg file if you might have. I have no idea of how you produce this images as fonts.

Best regards
Ezequias Rocha

**Comment by tagliala** [comment]
Is this a brand? Do you need a beer icon exactly like that?

**Comment by ezequias** [comment]
I am using an image and I think someone would need this element in some other page. It will compound my logo, it's no my logo. I will use it in a website that promotes informal conversation like in a pub. I am planning to talk about innovation and entrepreneurship informal place.

**Comment by tagliala** [comment]
There is already `fa-beer` if this is not a logo: http://fontawesome.io/icon/beer/

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
