### ISSUE TITLE
Chopp Mug

### ISSUE THREAD

**Issue by ezequias** [FortAwesome/Font-Awesome#6229]
Hi

I am planning to produce a website with a pub thematic and I see FA has not much elements for this theme.

I would like to suggest this mug here.

![beer](https://cloud.githubusercontent.com/assets/539561/7151396/ce3697b8-e2ff-11e4-97f8-0eb1cba4c286.png)

ps: I have the svg file if you might have. I have no idea of how you produce this images as fonts.

Best regards
Ezequias Rocha

**Comment by tagliala** [comment]
dup #6228
