### ISSUE TITLE
Icon Request: fa-usb

### ISSUE THREAD

**Issue by etee** [FortAwesome/Font-Awesome#6231]
Will be using it in menu as hardware display tokens. :)
![images](https://cloud.githubusercontent.com/assets/4270415/7154334/7e74e78e-e372-11e4-9dd9-bc0f2179c1f1.jpg)

**Comment by nepa** [comment]
USB logo is typically this:

![usb logo](https://cloud.githubusercontent.com/assets/772192/7159167/98ce8988-e380-11e4-8886-b2eaa5b8aaac.png)

**Comment by magoo-pl** [comment]
+1

**Comment by josephyee** [comment]
+1

**Comment by fancyfanta** [comment]
+1 but what about usb 3.0 and 2.0 ...

**Comment by G-Driver** [comment]
@etee @magoo-pl @josephyee @fancyfanta @tagliala this is dup request of https://github.com/FortAwesome/Font-Awesome/issues/2165 please give that request a +1

**Comment by tagliala** [comment]
Hmmm... not sure it is a duplicate.

#2165 is about usb logo, this one seems about a usb device. @etee could you please  confirm?

**Comment by berengar** [comment]
+99999999999

**Comment by etee** [comment]
Hi, I requested an icon for display hardware token.
+1 for usb, but its not what I needed.
Anyways my issue is resolved I found the other icon to suit my requirement.

**Comment by tagliala** [comment]
Closing here, usb: #2165  if someone needs an usb dongle please open a new request with a proper title
