### ISSUE TITLE
Icon request: fa-food, fa-dinner

### ISSUE THREAD

**Issue by werlend** [FortAwesome/Font-Awesome#6233]
I would like an icon indicating food or dinner. It could be different foods like pizza, cake etc.
But most important i'd like an icon of a knife and fork or a plate.

Example: http://img.gfx.no/1535/1535369/dish2.png

**Comment by tagliala** [comment]
probably it is already here: http://fontawesome.io/icon/cutlery/

closing here

**Comment by NishanthKabra** [comment]
For a food app, i want to categorize main course, snacks etc. generic fa-cutlery is the only thing we have, if am not wrong.

**Comment by hubertgitter** [comment]
Me too looking for cutlery crossed.
It is very important, cause it is a streetsign in Germany.
http://www.strassenschilder.de/richtzeichen/autobahngasthaus/
