### ISSUE TITLE
Fontawesome + Bootstrap 3 fonts not sharp in buttons

### ISSUE THREAD

**Issue by ricksonchew** [FortAwesome/Font-Awesome#6236]
I notice that when I am using fontawesome + bootstrap 3 in buttons, fontawesome fonts are not sharp. It is very noticeable when using large buttons. It tends to be a little blurry.

**Comment by tagliala** [comment]
@ricksonchew unfortunately we cannot guarantee pixel perfection at any size. You should use 14px or multiple of 14px. Please note that, in example, 21px could look much better than 20px or 22px. `btn-lg` uses 18px font size

Hope it helps
