### ISSUE TITLE
Icon request: fa-users-o fa-user-o

### ISSUE THREAD

**Issue by tquiroga** [FortAwesome/Font-Awesome#6240]
Hi,

It would be really great to have fa-users with the -o suffix because the icon is very plain. If you use many icons with the -o suffix and have to use fa-users, you will have one very plain icon killing your design 

Many Thanks

**Comment by tagliala** [comment]
refers to #1241

**Comment by peredin** [comment]
+1

**Comment by tagliala** [comment]
let's use #3671
