### ISSUE TITLE
Icon Request: IMDb

### ISSUE THREAD

**Issue by shefik** [FortAwesome/Font-Awesome#6245]
Please add an icon for IMDb - `fa-imdb`.

http://www.imdb.com/

**Comment by SergeantJack** [comment]
+1 Yes please!

**Comment by G-Driver** [comment]
@shefik @SergeantJack @tagliala this is a dup of https://github.com/FortAwesome/Font-Awesome/issues/998 please give that request a +1

**Comment by tagliala** [comment]
@G-Driver thanks, as usual :)

closing here
