### ISSUE TITLE
Icon Request: vsco grid

### ISSUE THREAD

**Issue by soyo2** [FortAwesome/Font-Awesome#6258]
![vscoicon](https://cloud.githubusercontent.com/assets/12008870/7216099/4c6283ec-e62d-11e4-873f-7cf721e8fb84.png)

**Comment by tagliala** [comment]
@soyo2 is this different from #6123 ?

**Comment by tagliala** [comment]
hmmm it should be a dup of #2280, please +1 that request

closing here
