### ISSUE TITLE
Icon Request: fa-beam

### ISSUE THREAD

**Issue by MattUnderscore** [FortAwesome/Font-Awesome#6263]
WatchBeam is a rising live streaming service.

Logo example: 
![beam-icon](https://cloud.githubusercontent.com/assets/11934593/7218842/83d0bdda-e637-11e4-8e4d-2b65bbe7d8b2.png)

**Comment by njb-said** [comment]
For icon creators: There is a resource pack available [here](https://github.com/MCProHosting/beam-resource-kit).
(I hope this icon gets added :+1:)

**Comment by tagliala** [comment]
dup of #5907, please +1 that request

closing here
