### ISSUE TITLE
Icon request: icon-paint-roller

### ISSUE THREAD

**Issue by kanisie** [FortAwesome/Font-Awesome#6265]
For the websites about street art, graffiti, art, murals, art in public places, interior design, reconstruction, materials etc...
![paint-roll-icon](https://cloud.githubusercontent.com/assets/12024556/7221833/d0038312-e6c9-11e4-9186-72f9e2237567.png)

**Comment by vincentsarago** [comment]
+1

**Comment by aencaster** [comment]
+1

**Comment by woptima** [comment]
+1

**Comment by ccpat** [comment]
+1

**Comment by KerstinBB** [comment]
+1 needed for "apply format/style" as common in text editing software

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/paint-roller?style=solid

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/paint-roller?style=solid
