### ISSUE TITLE
Icon Request: fa-teacher, fa-parent

### ISSUE THREAD

**Issue by Abildtoft** [FortAwesome/Font-Awesome#6269]
I'm currently involved in the creation of an app that uses your lovely icon set, in the development of which we face the need to be able to distinguish between two different user types: Teacher and parent. Graphical design is not my strong suit, but an idea would be that the teacher icon could be similar to the user icon but with a stylized square academic cap, whereas the parent icon could be a combination of the child and user icons.

Regardless of whether or not these are icons you'd like to add, I'd just like to say thank you for an amazing product (I've had to stop myself twice now from writing 'awesome') :)

**Comment by tagliala** [comment]
Hi, 

thanks for your kind words

teacher is a dup of  #4987, please +1 that request
parent is a dup of  #2704, please +1 that request

I'm going to rename the above requests for tracking purposes

Closing here

**Comment by mahuamun** [comment]
I don't know how is it use? plz help me
