### ISSUE TITLE
fa-fw monospace font?

### ISSUE THREAD

**Issue by octref** [FortAwesome/Font-Awesome#6273]
I really want to use FA in my terminal.
Is a monospaced ttf possible?

**Comment by tagliala** [comment]
hi,

FontAwesome glyphs have different width by design choice

**Comment by octref** [comment]
I understand, but is it possible to make them same width by scaling & padding some whitespaces?

**Comment by alessandro-pezzato** [comment]
For anybody coming here looking for a fa good for terminal, just look at https://github.com/ryanoasis/nerd-fonts

**Comment by octref** [comment]
@alessandro-pezzato 
Exactly what I need. Thanks!

**Comment by tagliala** [comment]
@alessandro-pezzato thanks for sharing this!
