### ISSUE TITLE
Icon request: fa-task

### ISSUE THREAD

**Issue by MojoDK** [FortAwesome/Font-Awesome#6277]
Like the "task" icon in Outlook :)

**Comment by tagliala** [comment]
could you please provide an example? I'm not using outlook

**Comment by aethior** [comment]
Duplicate/related of #1230, #773 or #896.

cc @tagliala.

![image](https://cloud.githubusercontent.com/assets/1769227/15895455/b6796f1a-2d8b-11e6-8d9e-cb6b9da4b23e.png)

**Comment by tagliala** [comment]
no feedback, closing here

**Comment by tagliala** [comment]
maybe also this one: http://fontawesome.io/icon/calendar-check-o/
