### ISSUE TITLE
Icon Request: fa-server

### ISSUE THREAD

**Issue by sergenboss** [FortAwesome/Font-Awesome#6279]
Hey. 
I tried to use the new Server Icon but it doesnt work at my site.

**Comment by tagliala** [comment]
Hi,

please make sure you are using the latest version of fontawesome. Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here, but feel free to comment
