### ISSUE TITLE
Icon Request: share-this

### ISSUE THREAD

**Issue by torque01** [FortAwesome/Font-Awesome#6280]
The nearly ubiquitous share-this icon, boxed and un-, please.

![share-this](https://cloud.githubusercontent.com/assets/12058258/7263997/99f556f6-e83b-11e4-904e-fe82b535784a.png)
![share-this-box](https://cloud.githubusercontent.com/assets/12058258/7264000/9ebcd628-e83b-11e4-9be8-fc8f5c779cbc.png)

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/share-alt/ http://fontawesome.io/icon/share-alt-square/

PS: apparently google is moving to http://fontawesome.io/icon/share/ (take a look to youtube on android)
