### ISSUE TITLE
Icon Request: fa-sublime-text

### ISSUE THREAD

**Issue by cuttingedgehobbies** [FortAwesome/Font-Awesome#6284]
I use this for some code editing.

![screen shot 2015-04-21 at 10 47 22 pm](https://cloud.githubusercontent.com/assets/11955259/7266493/689983ce-e878-11e4-8b9f-3ed4592b80ed.png)

http://www.sublimetext.com/

**Comment by tagliala** [comment]
dup of #4082, please +1 that request

closing here
