### ISSUE TITLE
Icon Request: fa-pet

### ISSUE THREAD

**Issue by iBrander** [FortAwesome/Font-Awesome#6285]
Hello,

I'm new here and I want to ask about 2 types of icons which I can't find. It's fa-pet and fa-clothes (fa-cloth, fa-boot, fa-cap, etc). There is no icons about pets (cat, dog, mouse, etc.) jus one I found it's fa-bug and no one icon with clothes (cap, shirt, belt, t-shirts, boots, etc.). Can anyone make them or when it will be additionally on icons? Thank you in advance.

Regards,

Darius

**Comment by tagliala** [comment]
Hi,

there is an icon about pets: http://fontawesome.io/icon/paw/

Just added a filter in 4.3.1 to improve search

Hope it helps

Closing here, but feel free to comment

**Comment by ralexrdz** [comment]
+1 clothes
