### ISSUE TITLE
Icon Request: icon-lab

### ISSUE THREAD

**Issue by Nomaximum** [FortAwesome/Font-Awesome#6289]
Hello,
I need a symbol for a lab / experiment in form of a test tube, please see attached pic.
Thank you for considering!

![lab-beaker-icon-614x460](https://cloud.githubusercontent.com/assets/12068141/7274785/234b3f96-e900-11e4-8a4d-8b4b5b311ebf.png)

**Comment by tagliala** [comment]
Already here: http://fontawesome.io/icon/flask/

There are also some filters so when you search for "lab" at http://fontawesome.io/icons/ the above icon will appear

https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L1867

Closing here
