### ISSUE TITLE
Icon Request: fa-jetski

### ISSUE THREAD

**Issue by YSavanier** [FortAwesome/Font-Awesome#6290]
Hello

Could you please consider adding a jetskiicon to the transport icons please ?
For example : 

![vacation_32-128](https://cloud.githubusercontent.com/assets/7136668/7276628/35b36dc4-e90b-11e4-86db-8103aeb3a46f.png)

Regards

Yannick

**Comment by tagliala** [comment]
dup of #5714, please +1 that request

closing here
