### ISSUE TITLE
Icon request: fa-forkandknive

### ISSUE THREAD

**Issue by kayvanbree** [FortAwesome/Font-Awesome#6292]
I would like to see an icon like this:
![image](https://cloud.githubusercontent.com/assets/11921540/7281138/e3324940-e927-11e4-9d85-c786d95a845a.png)
(only the fork and knive off course)

This would be nice for a food themed website.

**Comment by tagliala** [comment]
Here it is: http://fontawesome.io/icon/cutlery/

Closing here
