### ISSUE TITLE
Icon request: fa-bbq (barbecue)

### ISSUE THREAD

**Issue by kayvanbree** [FortAwesome/Font-Awesome#6293]
I would like to see some bbq logo's inspired by these:

fa-bbq:
![image](https://cloud.githubusercontent.com/assets/11921540/7281191/3f247e1c-e928-11e4-8c1c-39e68fbd6092.png)

fa-bbq2:
![image](https://cloud.githubusercontent.com/assets/11921540/7281232/7d42e256-e928-11e4-8360-e7710f9cef19.png)

I would like to use these for a bbq / food themed website.

**Comment by nbutcher-rms** [comment]
:+1:

**Comment by limitstudios** [comment]
+1 this style is nice

![icon_bbq](https://cloud.githubusercontent.com/assets/8024370/21258054/25c82c30-c373-11e6-8839-4bd9ea2a8d4a.png)

**Comment by kseyedmehdi** [comment]
👍

**Comment by stefan-meier** [comment]
+1

**Comment by dj-beynon** [comment]
Agreed, a bbq or a grill would be a very nice addition, especially for real estate websites. 

Here are a few others for inspiration 

![barbecue](https://user-images.githubusercontent.com/63674182/82063095-0e29bb00-9699-11ea-9f61-06376b067c6c.png)
![bbq-2](https://user-images.githubusercontent.com/63674182/82063097-0ec25180-9699-11ea-824c-1e70c2459d43.png)
![bbq](https://user-images.githubusercontent.com/63674182/82063098-0ec25180-9699-11ea-94d2-e6f0a02365d5.png)

**Comment by ddacosta79** [comment]
👍

**Comment by HelenD-BID** [comment]
> ![bbq-2](https://user-images.githubusercontent.com/63674182/82063097-0ec25180-9699-11ea-824c-1e70c2459d43.png)

+1 for this style

**Comment by aethior** [comment]
@tagliala `household (category)` and `camping (category)` labels for this request?

**Comment by MDaigleEpsilon** [comment]
👍

**Comment by jottone** [comment]
So this dates back to 2015, and there is obviously people wanting it, as there have been multiple threads and many users gave it a thumbs up. Are you guys going to add a couple of grill icons or what???

**Comment by sensibleworld** [comment]
We are indeed. They're actually (bb)queued up for our next release.

**Comment by jottone** [comment]
Its funny. I have done the same search sooo many times, looking for a fontawesome grill icon, and have always end up here, but have never commented on the post. I am so glad fontawesome finally decided to join the cookout...

**Comment by sensibleworld** [comment]
Here they are!

https://fontawesome.com/icons/grill?s=solid
https://fontawesome.com/icons/grill-hot?s=solid
https://fontawesome.com/icons/grill-fire?s=solid

**Comment by jottone** [comment]
Well, I like them... Thanks for following through on this one.
