### ISSUE TITLE
Icon request: fa-chickenleg

### ISSUE THREAD

**Issue by kayvanbree** [FortAwesome/Font-Awesome#6294]
I would like to see a logo featuring a chickenleg:

![image](https://cloud.githubusercontent.com/assets/11921540/7281281/ed2a99ce-e928-11e4-9869-b4a2e6078a1c.png)

I am working on a food related website and this could come in handy.

**Comment by Rosa-Leeke** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/drumstick?style=solid
