### ISSUE TITLE
[request] Custom CSS as bootstrap

### ISSUE THREAD

**Issue by tofanelli** [FortAwesome/Font-Awesome#6295]
Hey guys!

I had an idea to enhance FA. Today I only need 3 icons to my project. So, it will be nice if I could select some from checkbox as I can do on Twitter Bootstrap - http://getbootstrap.com/customize/ -. So I can decrease my CSS file and loads ways faster.

Is there an update like this one to implement already?

Cheers =)

**Comment by tagliala** [comment]
Hi, 

There are unofficial options and a request here: #1773

Take a look at: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Hope it helps, closing here
