### ISSUE TITLE
Icon Request : fa-infinity

### ISSUE THREAD

**Issue by jasvvinder** [FortAwesome/Font-Awesome#6297]
hello,
I was searching infinity icon on Font Awesome but couldn't find. So requesting that please upload this icon. This icon is important to have in collection of Font-Awesome icons.

Example
![569-128](https://cloud.githubusercontent.com/assets/12081077/7293245/a15a7882-e9c0-11e4-950d-f3712e9e0471.png)

**Comment by tagliala** [comment]
dup of #1647 , please +1 that request

closing here

**Comment by jasvvinder** [comment]
I was not known about this opened issue. Thanks for closing.
