### ISSUE TITLE
Permission to re-distribute as Keynote file

### ISSUE THREAD

**Issue by fgnass** [FortAwesome/Font-Awesome#6300]
Hi, I create lots of UI mockups in Keynote and almost always use Font Awesome Icons. To make my life a little easier I converted all the 519 icons into Keynote shapes and put them into a single file. I'd like to put that `awesome.key` file on GitHub and wanted to ask you if such kind of re-packaging / re-distribution is okay with you. Here's a preview of what it looks like:

![screen shot 2015-04-23 at 15 23 12](https://cloud.githubusercontent.com/assets/89450/7297966/b539df94-e9cc-11e4-9697-2d9e8013d3a5.png)

**Comment by tagliala** [comment]
Hi,

thanks for sharing this. Given the FA license, I think there should be no problems but I need feedback from @davegandy about this one

**Comment by fgnass** [comment]
@davegandy did you have a chance to take a look at this? I'd love to share the keynote file in our next UX meetup if that's okay with you. Thanks in advance for your feedback!

**Comment by tagliala** [comment]
I think this has been fixed

Please fill out a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) if this is still an issue
