### ISSUE TITLE
Icon request: Gitlab

### ISSUE THREAD

**Issue by PaulBGD** [FortAwesome/Font-Awesome#6306]
I don't work for them, but I've been using their oauth2 integration and I think they deserve an icon for buttons and such.

![](https://gitlab.com/assets/logo-white-0b53cd4ea06811d79b3acd486384e047.png)

**Comment by jastreich** [comment]
+1

**Comment by davidxd33** [comment]
Dupe #1530

**Comment by tagliala** [comment]
@davidxd33 thanks

closing here
