### ISSUE TITLE
Icon-request: icon-patreon

### ISSUE THREAD

**Issue by negritosuave** [FortAwesome/Font-Awesome#6307]
Basically to use on my website in a few places.  
![eer0i_patreon_logo_flat](https://cloud.githubusercontent.com/assets/10988834/7312236/09fd233a-ea16-11e4-8ae1-31e7f713f252.png)

Something like this? Except white and transparent like other branding assets in the Font-Awesome stable. I think if the orange would be white and the white would be transparent, it would look best that way. But having an inverse as well would give it the most flexibility.

Thanks in advance!

**Comment by jastreich** [comment]
+1

**Comment by tagliala** [comment]
dup of #3257, please +1 that request

closing here
