### ISSUE TITLE
Icon request: icon-equal-housing 

### ISSUE THREAD

**Issue by krsbrn** [FortAwesome/Font-Awesome#6312]
This is used for all real estate websites, and we do a lot of them. I think it would be a nice addition.
![house_lender_icon-300x220](https://cloud.githubusercontent.com/assets/3780558/7326646/f66fda04-ea7b-11e4-81e2-0aed217e640e.jpg)

**Comment by tagliala** [comment]
dup of #3574, please +1 that request

closing here
