### ISSUE TITLE
The "Medium" Icon is not rendering (stays blank)

### ISSUE THREAD

**Issue by msutyak** [FortAwesome/Font-Awesome#6313]
I am trying to use the Medium icon using the following: <i class="fa fa-medium fa-lg"></i>

It's not rendering on the page.  All the others icons I'm using are working fine.  Thank you for your attention!

**Comment by tagliala** [comment]
Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here, but feel free to comment
