### ISSUE TITLE
Icon request: icon-kitchen-stove (cooker)

### ISSUE THREAD

**Issue by mediabeastnz** [FortAwesome/Font-Awesome#6314]
This would be really handy for sites like motorhomes or motels etc.
I have a couple more requests are well but i separate them out .e.g. fridge. dvd. tv. shower.

Stove example:
![icon_stove_bw](https://cloud.githubusercontent.com/assets/909749/7330690/675d01bc-eb47-11e4-8849-f1b8e46f1328.png)

**Comment by Samoht-fr** [comment]
+1

**Comment by soccer99** [comment]
+1

**Comment by aethior** [comment]
Hi @mediabeastnz,

`fa-oven` was added in v5.12.0.
Check https://fontawesome.com/icons/oven

I am not sure if this is the requested icon.

cc/ @tagliala

**Comment by tagliala** [comment]
Nope, I should change the title to `stove` probably, but stove also indicates #11666

**Comment by sensibleworld** [comment]
We have this, too: https://fontawesome.com/icons/fire-burner?f=classic&s=solid
