### ISSUE TITLE
Icon Request: icon-fridge

### ISSUE THREAD

**Issue by mediabeastnz** [FortAwesome/Font-Awesome#6315]
Fridge icon for motorhomes or motels.

Example:
![fridge_refrigerator-512](https://cloud.githubusercontent.com/assets/909749/7330702/d1bef0c4-eb47-11e4-9f7c-6a372c64ccb5.png)

**Comment by Samoht-fr** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by soccer99** [comment]
+1

**Comment by aethior** [comment]
Hi @mediabeastnz,

This icon was added in v5.12.0.
Check https://fontawesome.com/icons/refrigerator

Regards.

cc/ @tagliala
