### ISSUE TITLE
Icon request: icon-dvd-player

### ISSUE THREAD

**Issue by mediabeastnz** [FortAwesome/Font-Awesome#6316]
Great for rental sites e.g. motorhomes or motels.

Examples - depends on what suits FA's style and is more recognisable at small size.

<img src="https://cloud.githubusercontent.com/assets/909749/7330789/8279d1bc-eb49-11e4-8170-6f80a06d0215.jpg" width="100px" height="100px"> 
OR
<img src="https://cloud.githubusercontent.com/assets/909749/7330790/82c7aa22-eb49-11e4-890b-ea027932fc3a.png" width="100px" height="100px">

**Comment by scherre** [comment]
check out #702, it's quite a similar request.

**Comment by sensibleworld** [comment]
<img width="279" alt="Screen Shot 2021-03-30 at 12 56 32 PM" src="https://user-images.githubusercontent.com/529604/113026716-5b026d00-9157-11eb-84f5-a86fae4a4b14.png">
