### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by sunmo1995** [FortAwesome/Font-Awesome#6317]
icon-code 
![2015-04-25_121912](https://cloud.githubusercontent.com/assets/8917179/7331527/95bda586-eb45-11e4-83a5-b8fd8c1db382.png)

icon-times
![2015-04-25_121936](https://cloud.githubusercontent.com/assets/8917179/7331529/a34454e8-eb45-11e4-8471-cbb34f0710cb.png)

icon-chain-broken

icon-smile-o

icon-html5
![2015-04-25_121923](https://cloud.githubusercontent.com/assets/8917179/7331530/d6943a52-eb45-11e4-861d-f106a1a1a023.png)

Thank you!

**Comment by tagliala** [comment]
Sorry, didn't get this issue. Could you please clarify?

**Comment by sunmo1995** [comment]
I want some icons.
First: like this, ![](https://cloud.githubusercontent.com/assets/8917179/7331527/95bda586-eb45-11e4-83a5-b8fd8c1db382.png), represent  a section of code.
Second: like this,![](https://cloud.githubusercontent.com/assets/8917179/7331529/a34454e8-eb45-11e4-8471-cbb34f0710cb.png), represent choose a font color.
Third: like a broken chain, I didn't find a symbol,
Four: like smile, I didn't find a symbol, too.
Five,like this, ![](https://cloud.githubusercontent.com/assets/8917179/7331530/d6943a52-eb45-11e4-861d-f106a1a1a023.png), represent html5.

Thank you.

**Comment by tagliala** [comment]
Hi,

they are already here:
code: http://fontawesome.io/icon/code/
broken chain: http://fontawesome.io/icon/chain-broken/
smile: http://fontawesome.io/icon/smile-o/
html5: http://fontawesome.io/icon/html5/

except for font color, but you can obtain it with a couple of lines of css (border-bottom)
font: http://fontawesome.io/icon/font/

**Comment by sunmo1995** [comment]
Sorry, I didn't find them before.
Thank you very much.

**Comment by tagliala** [comment]
No problem, closing here
