### ISSUE TITLE
Icon request: icon-treasurechest

### ISSUE THREAD

**Issue by faro0007** [FortAwesome/Font-Awesome#6319]
It would be great to have a treasure chest. I would like to use it on a website explaining the features of a software. One target of this software is to DISCOVER something. A chest (like those of pirates) conveys discovery, adventure and a treasure.

**Comment by scherre** [comment]
+1

**Comment by thomas-seres** [comment]
+1

**Comment by learningdesignlabs** [comment]
+1

**Comment by Fededark** [comment]
+1

**Comment by sensibleworld** [comment]
It took a while, but we finally dug up a treasure chest and added it to Font Awesome Pro: https://fontawesome.com/icons/treasure-chest?style=solid
