### ISSUE TITLE
Icon Request: fa-sound, fa-sound-mute, fa-sound-low

### ISSUE THREAD

**Issue by carlosmacias** [FortAwesome/Font-Awesome#6320]
Something like fa-file-sound (icon inside file icon) in diferent status.

fa-sound -> http://iconshow.me/volume-medium-icon
fa-sound-mute -> http://iconshow.me/volume-mute-icon
fa-sound-low -> http://iconshow.me/volume-low-icon

**Comment by tagliala** [comment]
off: http://fontawesome.io/icon/volume-off/
down: http://fontawesome.io/icon/volume-down/
up: http://fontawesome.io/icon/volume-up/

request for icon-mute is here: #288 if you are interested please +1 that request

closing here!

**Comment by carlosmacias** [comment]
Ok, sorry :)

**Comment by tagliala** [comment]
@carlosmacias no problem
