### ISSUE TITLE
Icon Request: fa-stock-market-*

### ISSUE THREAD

**Issue by matthijs110** [FortAwesome/Font-Awesome#6328]
I'm making a small application which shows the current stock market data. I want to finish the design with some nice icons. Like so:
- If the stock-market go's up, show a arrow going up like so: 
  ![Image of arrow up](http://puu.sh/hsq3G/5886005dcc.png)
- If the stock-market does not change (is equal to the data of yesterday), show a equivalent symbol like so:
  ![Image of equivalent symbol](http://puu.sh/hsqkW/8450508960.png)
- If the stock-market go's down, show a arrow going down like so:
  ![Image of arrow down](http://puu.sh/hsq8c/bacff611d1.png)
##### The attached images above are used at a Dutch television channel about the stock market. It's just there as example.

It would also be nice to add raw materials icons for:
- Gold (fa-gold)
- Silver (fa-silver)
- Oil (fa-oil)
- Sugar (fa-sugar)
- Wheat (fa-wheat)

**Comment by jasonhibbs** [comment]
I can see the case for fa-arrow-up-right, fa-arrow-down-right, fa-arrow-up-left, and fa-arrow-down-left, although currently you could rotate an existing arrow. Further, having “fa-stock-market”, or specifically using diagonal arrows for stock markets seems highly subjective; especially given the broader use of straight-up and straight-down chevrons: fa-chevron-up, fa-chevron-down.

+1 for **fa-equals** though!

**Comment by sensibleworld** [comment]
We have a number of icons now that should satisfy this request: https://fontawesome.com/search?q=trend&o=r&f=classic
