### ISSUE TITLE
Icon Request: endomondo

### ISSUE THREAD

**Issue by yankki** [FortAwesome/Font-Awesome#6333]
Hi there! 
I just want to let you know about Endomondo... Popular sports tracker. It will be great widget which you can add to page. For example it's a wonderful opportunity to share your sports results with other participants. Please think about it :)

![endomondo](https://cloud.githubusercontent.com/assets/12141511/7354468/f7afda0c-ed1b-11e4-9b71-35632eab42b5.png)

Greetings!
Maciej

**Comment by Cigaras** [comment]
+1

**Comment by TkTzLabs** [comment]
+1 ? so when ?

**Comment by aethior** [comment]
>The app will cease to exist on December 31, 2020 and will be removed from the stores. The company even says it will be rendered inoperative, but it's unclear whether it will simply stop syncing or entirely refuse to track your workouts. All Premium memberships will also be canceled at the end of November 2020, but the benefits will continue to apply until the end of the year. ([source](https://www.androidpolice.com/2020/11/08/endomondo-is-shutting-down-at-the-end-of-the-year/))

cc/ @tagliala
