### ISSUE TITLE
Icon Request: Astrological and Zodiac symbols

### ISSUE THREAD

**Issue by Magidragon-Sapph** [FortAwesome/Font-Awesome#6338]
Could we have icons for celestial bodies and zodiacs? Could be helpful. Only Mars and Venus have symbols thus far.

**Comment by scherre** [comment]
There is already a request for planetary symbols: #4860 but having the zodiac ones as well would be very cool.

**Comment by tagliala** [comment]
and zodiac signs are there: #2831 

both dups, closing here, please +1 the other requests
