### ISSUE TITLE
Icon Request: fa-dumbell

### ISSUE THREAD

**Issue by qforgues** [FortAwesome/Font-Awesome#6340]
how about a dumbell?

**Comment by tagliala** [comment]
dup of #1500 , please +1 that request

closing here

**Comment by qforgues** [comment]
How many does it take, seems like there are a lot of requests for that one..

On Tue, Apr 28, 2015 at 9:54 AM, Geremia Taglialatela <
notifications@github.com> wrote:

> Closed #6340 <https://github.com/FortAwesome/Font-Awesome/issues/6340>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/6340#event-291994077>.
>



-- 
 Quentin Forgues <http://www.qforgues.com>

**Comment by tagliala** [comment]
@qforgues sorry, I don't know. Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
