### ISSUE TITLE
Icon Request: fa-equal-opportunity-housing

### ISSUE THREAD

**Issue by edrickclark** [FortAwesome/Font-Awesome#6341]
Requesting equal opportunity housing logo be added for use in housing and real estate marketing apps and websites. Thank you!

![equal-opportunity-housing](https://cloud.githubusercontent.com/assets/854522/7359900/6014dd40-ecf9-11e4-9c75-7f9142958738.gif)

**Comment by tagliala** [comment]
dup of #3574 , please +1 that request

closing here
