### ISSUE TITLE
Icon Request: fa-presentation

### ISSUE THREAD

**Issue by jiwankow** [FortAwesome/Font-Awesome#6343]
Use cases for this icon:
-lectures
-classes
-presentations
-conferences
-meetings

![live-course](https://cloud.githubusercontent.com/assets/2650528/7361046/8a170e48-ed20-11e4-867b-bcd0bd275fc4.png)

The intention of this image is to be an instructor/teacher standing at a lectern before a class learners.

**Comment by tagliala** [comment]
hmmm... this one is not suitable for basic icon size of 14px. I prefer #866 

Closing here. If you want to request this specific icon, we need to find a better title
