### ISSUE TITLE
[bug] fa-circle-o-notch poorly renders when fa-spin applied

### ISSUE THREAD

**Issue by scottyantipa** [FortAwesome/Font-Awesome#6348]
The fa-circle-o-notch icon renders with a flattened, non-circular edge on the opposite side of the notch.  The screenshot below is on https://fortawesome.github.io/Font-Awesome/icon/circle-o-notch/ with a .fa-spin class applied.

![screen shot 2015-04-28 at 10 05 14 am](https://cloud.githubusercontent.com/assets/3643611/7375613/bfb5835e-ed8e-11e4-9304-64e765ba2186.png)

**Comment by tagliala** [comment]
Unfortunately we know but we are still not able to fix this.

Refers to #671 , please share your thoughts there

Closing here

**Comment by adarrra** [comment]
Hi, sorry for posting to closed issue, but for those who maybe comes here from google (like me),  some hacky fix :
`outline 1px solid transparent`

**Comment by juanvillegas** [comment]
Another quick fix is to upgrade to 4.5
