### ISSUE TITLE
Icon request: icon-experiment

### ISSUE THREAD

**Issue by studio4** [FortAwesome/Font-Awesome#6353]
Hello,

It would be great to have a potion/beaker/test-tube icon to signify some sort of experiment. Something like the attached image.

This would be useful when denoting an experiment or way of choosing options, user interaction etc. Similar to the gears and magic wand icons but perhaps a little more 'experimental' in connotation. 

Many thanks
![potion-capture](https://cloud.githubusercontent.com/assets/4395458/7394971/eecfedf4-ee8e-11e4-820f-2c753673dc22.JPG)

**Comment by tagliala** [comment]
`fa-flask` should suit your needs: http://fontawesome.io/icon/flask/

closing here
