### ISSUE TITLE
Vimeo icon is incorrect (v shape is slightly different)

### ISSUE THREAD

**Issue by bdougherty** [FortAwesome/Font-Awesome#6354]
Font Awesome:

![screenshot 2015-04-29 12 29 05](https://cloud.githubusercontent.com/assets/15747/7395940/8303c848-ee6b-11e4-87c6-3f5d44ae7d7c.png)

Correct:

![screenshot 2015-04-29 12 30 42](https://cloud.githubusercontent.com/assets/15747/7395956/91a4a1ba-ee6b-11e4-8529-85d0a47cbe24.png)

**Comment by tagliala** [comment]
Hi, thanks for pointing this out.

So we also need a `vimeo-official` version

**Comment by bdougherty** [comment]
What exactly do you mean by `vimeo-official` version? It is totally acceptable to put it in a rounded box (or square box, or no box), as long as the `v` has the correct path and spacing (both are off in the font awesome version).

**Comment by tagliala** [comment]
https://vimeo.com/about/brand_guidelines

**Comment by RevanProdigalKnight** [comment]
> ![capture](https://cloud.githubusercontent.com/assets/5728037/7865576/c3e6fcee-0537-11e5-96dc-3acc2ffa1b34.PNG)

Note that the favicon on the [brand guidelines](https://vimeo.com/about/brand_guidelines) page has rounded corners, meaning either that the current icon is okay as it is or they don't follow their own guidelines.

**Comment by bdougherty** [comment]
There's nothing in the guidelines that prohibits rounded corners. The current version is ok except for the shape of the `v`, which is what I was trying to point out.

**Comment by tagliala** [comment]
@bdougherty you are right, v shape is slightly different. I didn't notice before, I was thinking about rounded corners

**Comment by davegandy** [comment]
Okay, that's weird. I'll get it fixed right up.

**Comment by davegandy** [comment]
Fixed in 4.4.0-wip branch. Closing.
