### ISSUE TITLE
Icon Request: fa-rows

### ISSUE THREAD

**Issue by pevas** [FortAwesome/Font-Awesome#6359]
Could I please request a complement to the fa-columns icon, which would be the same, but split horizontally, rather than vertically? Many thanks!

**Comment by varemenos** [comment]
:+1: This would be great for describing screen-splitting [horizontal (rows) or vertical (columns)] actions

**Comment by DennaGherlyn** [comment]
+1

**Comment by jls2933** [comment]
+1

**Comment by ryanlin1986** [comment]
+1

**Comment by y-a-r-g** [comment]
+1 
Mostly useful as split icon

**Comment by petejkim** [comment]
+1

**Comment by mean-cj** [comment]
+1

**Comment by heck4** [comment]
+1

Workaround: While not perfect, I used the columns icon and rotated it to look like rows:

`<i class="fa fa-columns fa-rotate-270"></i>`

**Comment by pierremarieB** [comment]
+1 Would be very useful for many situations.

**Comment by joshxyzhimself** [comment]
+1 come on

**Comment by ryanlin1986** [comment]
dead of the project, just use another one instead of fontawesome

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/table-rows?s=solid
https://fontawesome.com/icons/table-columns?s=solid

**Comment by joshxyzhimself** [comment]
After five years lol thank you! Haha
