### ISSUE TITLE
Icon request - Coins icon

### ISSUE THREAD

**Issue by DumboJetEngine** [FortAwesome/Font-Awesome#6363]
I know that you have a `money` icon (plus some currency icons), but might be good to have a `coins` icon too (e.g. https://www.google.com/search?q=coins+icon).
I don't quite understand immediately that this : http://fortawesome.github.io/Font-Awesome/icon/money/
...is a bill although a green color might help Americans figure it out.

But I am not a graphics guy, so perhaps two coins will be harder to recognize.
So, it's up to you.
I only wanted to throw the idea.

----

Also, I was always wondering if there is a way to pick and choose which icons will be included in your production server to reduce the bandwidth. Certainly this could be done with CSS files manually, but I don't know if it is possible with all of the `image` data for the icons.
If it is possible, let me know. :)
(The format of the EOT/WOFF/TTF/etc files looks quite frightening to decode at first glance...)
I might make an EXE that scans a directory's files to find all used `fa-*`s and build a reduced in size FA library.

I think that would be cool.
I guess that the fact that your library has so many icons can be both a good thing (in terms of choices) and a bad (in terms of performance). This process might be great to get rid of all the bad things. :)

A quick search looks promising: http://stackoverflow.com/questions/4628247/c-sharp-lib-for-processing-font-files-ttf-truetype-others

**Comment by tagliala** [comment]
> I know that you have a money icon (plus some currency icons), but might be good to have a coins icon too (e.g. https://www.google.com/search?q=coins+icon).

Please +1 #1400 

> Also, I was always wondering if there is a way to pick and choose which icons will be included in your production server to reduce the bandwidth. Certainly this could be done with CSS files manually, but I don't know if it is possible with all of the image data for the icons.
If it is possible, let me know. :)

Yes, it is definitely possible, take a look at: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> I guess that the fact that your library has so many icons can be both a good thing (in terms of choices) and a bad (in terms of performance). This process might be great to get rid of all the bad things. :)

You can take advance of the CDN: http://www.bootstrapcdn.com/

Hope it helps, closing here

**Comment by DumboJetEngine** [comment]
Really useful information!
Thanks. :)
That wiki page is AWESOME! :+1: 

(I wonder how I've missed the fact that there was already another request for a "coins" icon... Anyway...)
