### ISSUE TITLE
W3C CSS Validator results

### ISSUE THREAD

**Issue by niksmac** [FortAwesome/Font-Awesome#6365]
There are multiple errors when validating. Is there a solution? 
![screen shot 2015-05-02 at 12 32 59 pm](https://cloud.githubusercontent.com/assets/124470/7440255/6ade9d84-f0c7-11e4-8ee7-b59676baabe8.png)

**Comment by tagliala** [comment]
@niksmac customize fontawesome.

You will lose support for some browsers, and some visual enhancements ([text-rendering](http://caniuse.com/#search=text-rendering) is unofficial. Sorry we can't fix

Hope it helps, closing here
