### ISSUE TITLE
Icon Request: fa-file-chart-o (report)

### ISSUE THREAD

**Issue by ntfox** [FortAwesome/Font-Awesome#6366]
hi
please add report icon

**Comment by tagliala** [comment]
could you pleae provide a single color example suitable for 14px icon size?

**Comment by ntfox** [comment]
https://www.iconfinder.com/icons/217123/analytics_bar_chart_diagram_document_file_graph_internet_marketing_optimization_page_paper_pie_presentation_report_statistics_icon

**Comment by ntfox** [comment]
![image](https://cloud.githubusercontent.com/assets/3767882/7603572/08032496-f94b-11e4-8aa7-f3ab45f230cc.png)

**Comment by EddieFromFA** [comment]
+1

**Comment by fsworld009** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by tagliala** [comment]
closing here as a duplicate of #1076
