### ISSUE TITLE
Icon request: icon-ribnicek

### ISSUE THREAD

**Issue by Klavdija** [FortAwesome/Font-Awesome#6370]
The requested icon will be used to represent our preeschool programme on web and other online documents such as emails, etc. Cheers!
![ribnicek](https://cloud.githubusercontent.com/assets/12213053/7442446/8748cd78-f112-11e4-8b9a-87444bdf0ed7.jpg)

**Comment by tagliala** [comment]
Hi, is this a brand you are developing?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
