### ISSUE TITLE
Icon Request: fa-tripadvisor

### ISSUE THREAD

**Issue by ohiawins** [FortAwesome/Font-Awesome#6372]
I am a web developer in a really awesome marketing team called Liquid Spark. I make sites, emails, etc for ADVENTURE VACATION companies around the globe. Many of our clients rely on TripAdvisor for some of their success. TA reaches 315 million unique monthly visitors yet is never included in themes and sadly it is not included here at FA. 

Wondering if you might do all the travelers and hosts in the world a solid and add the TripAdvisor logo to your Brand section.

Muchísimo Gracias
~ohia

**Comment by tagliala** [comment]
dup of #412 , please +1 that request

closing here
