### ISSUE TITLE
Icon request: patch icon 

### ISSUE THREAD

**Issue by Dret42** [FortAwesome/Font-Awesome#6378]
A simple or double patch icon

here a couple of examples:

![patch-128](https://cloud.githubusercontent.com/assets/4984481/7449761/e8d06df0-f23c-11e4-938a-07db5e0ac7fa.png)

![patch_2-128](https://cloud.githubusercontent.com/assets/4984481/7449763/f068f85c-f23c-11e4-978b-64a1e75879b0.png)

Thanks!

**Comment by tagliala** [comment]
Dup of #4298, please +1 that request

Editing #4298 to include patch in the title

closing here
