### ISSUE TITLE
Icon Request: Silicon Power Firma F80 (Thumb Drive)

### ISSUE THREAD

**Issue by Hellion1982** [FortAwesome/Font-Awesome#6384]
Hi, can someone please create an icon from an image I've uploaded? I just bought this thumb drive, and thought it would make a cool icon. I've tried free tools, but the icon looks like a square, just like the source pic, which I'd rather avoid. :-)
Here's the source pic: I'd like just the thumb drive portion converted to an icon. If that's too difficult, please feel free to use the second or third images, whichever is convenient.

![01 first choice - silicon_power_firma_f80](https://cloud.githubusercontent.com/assets/12242905/7464227/153c6b4e-f28f-11e4-84a4-3ca0f2787c99.jpg)
![02 second choice - silicon_power_firma_f80](https://cloud.githubusercontent.com/assets/12242905/7464228/153c7f12-f28f-11e4-83ab-31af88560129.jpg)
![03 third choice - silicon_power_firma_f80](https://cloud.githubusercontent.com/assets/12242905/7464226/153c3a0c-f28f-11e4-8c04-02d5c03af024.png)

Thanks.

**Comment by tagliala** [comment]
Hi, please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

hope it helps

**Comment by tagliala** [comment]
for a generic usb dongle, please open a new request
