### ISSUE TITLE
icon-ohsmiley

### ISSUE THREAD

**Issue by Tomgroot** [FortAwesome/Font-Awesome#6389]
![image](https://cloud.githubusercontent.com/assets/4732713/7470420/39be2988-f31d-11e4-9b88-bb76306d9eb1.png)

I want to use the smiley for a category that contains beautiful content. With this smiley I can easily project what I mean with the category.

:O <-- too beautiful for me

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/surprise?style=solid
