### ISSUE TITLE
Icon request: icon-playlist

### ISSUE THREAD

**Issue by madd512** [FortAwesome/Font-Awesome#639]
I'm making a music player.

http://imgur.com/JVIXg

Using folder icons for playlists looks a little silly. How about a playlist icon? Maybe a smart playlist icon too?

**Comment by melissanoelle** [comment]
+1 for note with lines.  Here's a screencap of Google Play Music's icon:

![screen shot 2015-03-22 at 10 33 45 pm](https://cloud.githubusercontent.com/assets/992688/6774801/90533c36-d0e3-11e4-8fb8-9737afc8edfb.png)

**Comment by melissanoelle** [comment]
Is there anything I can do to help gain any traction on this?

**Comment by devTristan** [comment]
It's been over two years since I made this issue. I still want it.

@melissanoelle I find that funny and relevant gifs can often help spur development. Like this one, which accurately summarizes my desire to have a playlist icon:

![grabbyhands](https://cloud.githubusercontent.com/assets/216009/6853137/9f1cc398-d3bf-11e4-8b50-fc888fa6a36f.gif)

@davegandy

**Comment by melissanoelle** [comment]
Right now in lieu of using a playlist icon, I'm using `fa-bug`. It's a bug that this icon isn't there yet. ;)

**Comment by pitrackster** [comment]
:+1:

**Comment by JustinAiken** [comment]
Yeaah a lil' music note with lines is what we need!

But not like the google one exactly, it looks too google-playish, but same general idea...

**Comment by polysics** [comment]
My life is not complete without a playlist icon.

**Comment by watsonbox** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by melissanoelle** [comment]
@davegandy: If someone wanted to make this icon to integrate into FontAwesome, what guidelines would they use? Do you accept those kinds of submissions? I couldn't find anything about it in the contributing docs.

Thanks!

**Comment by nitmir** [comment]
+1

**Comment by DoomDesign** [comment]
+1 - very useful for media player applications!

**Comment by surjithctly** [comment]
+1

![](https://camo.githubusercontent.com/97731d32adf2a443bc768fef169b8ffec8af4eb3/687474703a2f2f696d6167653030352e666c617469636f6e2e636f6d2f312f7376672f3130392f3130393231312e737667)

**Comment by melissanoelle** [comment]
Yes!

**Comment by JustinAiken** [comment]
Yes!

**Comment by mayeaux** [comment]
+1

**Comment by neoassyrian** [comment]
+1 for the list with note

**Comment by michaelGregoire** [comment]
+999 ...because +1000 would be ridiculous.... but yes, please. Pretty please?

**Comment by surjithctly** [comment]
This icon is first requested 5 years ago. So don't keep a hope on this icon. they are never going to make this.

Find your alternatives instead :)

**Comment by michaelGregoire** [comment]
@surjithctly I hope they pay attention to Pro user requests. I should request this in the Pro repo, if it hasn't already.

**Comment by VirtusB** [comment]
+1

**Comment by Alynva** [comment]
I think that these grouped icons can help: https://codepen.io/Alynva/pen/ZmayNG

**Comment by sensibleworld** [comment]
Version 5.11 is out with a new music-list icon: https://fontawesome.com/icons/list-music?style=solid
