### ISSUE TITLE
icon-XDsmiley

### ISSUE THREAD

**Issue by Tomgroot** [FortAwesome/Font-Awesome#6390]
![image](https://cloud.githubusercontent.com/assets/4732713/7470484/c0a8a18a-f31d-11e4-9066-5dad2c98380a.png)

I want to make a category called humor with this icon representing the category. 
I really love your font Awesome! 

Thanks for reading! Hope you like my idea.

**Comment by MVcodeartbr** [comment]
emoji icons is hard to provide..

**Comment by aethior** [comment]
Hi @Tomgroot,

This icon was added in v5.1.0.
Check https://fontawesome.com/icons/face-grin-squint

Regards.

cc/ @tagliala
