### ISSUE TITLE
Icon request: Camera shutter

### ISSUE THREAD

**Issue by JasonJay1111** [FortAwesome/Font-Awesome#6392]
Useful to have a camera shutter 

![image](https://cloud.githubusercontent.com/assets/8591464/7475173/eac70c02-f33d-11e4-9fee-856bba56a6f3.png)

**Comment by kwendenarmo** [comment]
+1

**Comment by JasonJay1111** [comment]
Hi - does this mean its created? sorry to be a pain..

J

**Comment by tagliala** [comment]
@JasonJay1111 sorry, no this icon was not created. Please take a look here if you need this icon in a short while: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I'm going to reopen this one but If i well remember this is a duplicate.

Refers to #4508

**Comment by jabarihunt** [comment]
+1

**Comment by nioc** [comment]
+1

**Comment by achillesrasquinha** [comment]
+1

**Comment by haufe** [comment]
if +1 means, i need it:
+1
usefull in many ways (mechanic, focus, semi-symetric, select, ...), good looking, sharp, crisp, james bond
- also for people who think we need animated icons in the future (like mouse-over-gets-underlined)

**Comment by nioc** [comment]
@haufe it won't be on this repo, but I proposed it on this fork ForkAwesome/Fork-Awesome#66

**Comment by sensibleworld** [comment]
Thanks for the request! We have this icon now in version 6. https://fontawesome.com/v6.0/icons/aperture?s=solid

<img width="1012" alt="Screen Shot 2021-05-27 at 1 59 02 PM" src="https://user-images.githubusercontent.com/529604/119874528-b2248400-bef3-11eb-853e-f806206ac6ce.png">
