### ISSUE TITLE
Gender icons are not equal in percieved size

### ISSUE THREAD

**Issue by johan-ludvigsson-stratsys** [FortAwesome/Font-Awesome#6394]
![image](https://cloud.githubusercontent.com/assets/1914547/7479874/cd44adfc-f364-11e4-86ac-07266c523d40.png)

(Example taken from the cheatsheet, font-size 14px)

We are using gender icons to differentiate some data in tables, and there is a rather noticeable difference between, especially if they are stacked vertically. For these type of symbols, the rings should always be the same size when they are the same font size.

**Comment by tagliala** [comment]
I suppose the problems are in `mars` and `mars-stroke`, right?

**Comment by johan-ludvigsson-stratsys** [comment]
![image](https://cloud.githubusercontent.com/assets/1914547/7489148/c35eb5b6-f3d3-11e4-801f-8446bed6d82c.png)

Most of them seem to be a 9x9 1px stroke circle. The ones that are bigger are: 
mars, mars-stroke, mars-stroke-h (barely) and genderless (this one is an alias, might wanna consider a separate icon for it).

**Comment by davegandy** [comment]
I'll take care of this in 4.4 Thanks for noticing and thanks for the heads up. :)

**Comment by davegandy** [comment]
@johan-ludvigsson-stratsys Thanks for the analysis. Very helpful. :)

**Comment by davegandy** [comment]
Finished in 4.4.0-wip branch. Closing!

**Comment by johan-ludvigsson-stratsys** [comment]
You're welcome!
