### ISSUE TITLE
Icon request: icon-bath

### ISSUE THREAD

**Issue by sherbertspain** [FortAwesome/Font-Awesome#6400]
Hi,

I work in a real estate agency and it would be really useful to have a bath icon if possible please?
I have included an example.

![bath](https://cloud.githubusercontent.com/assets/11046879/7491314/b597202a-f3e8-11e4-996d-5aa915163776.png)

**Comment by tagliala** [comment]
dup of #708. Renaming #708 to include bath

Please +1 that request

Closing here
