### ISSUE TITLE
Icon request: icon-size

### ISSUE THREAD

**Issue by sherbertspain** [FortAwesome/Font-Awesome#6401]
Hi,

I work in a real estate agency and it would be really useful to have a measurement icon if possible please?

I have included an example.
![icon-size](https://cloud.githubusercontent.com/assets/11046879/7491751/e745846e-f3ec-11e4-8fcf-14c66d30e65a.png)

**Comment by tagliala** [comment]
dup of #1096 , please +1 that request

closing here
