### ISSUE TITLE
Icon request:New icons for Specifics departments

### ISSUE THREAD

**Issue by Bracque** [FortAwesome/Font-Awesome#6402]
Hello,
we are making new enterprise's web and we have specifics icons for each area. Is it possible to put new icon in the library?
If we need icons files I can send you a zip with all files.
Thanks a lot .
Olivier.

![picto 1](https://cloud.githubusercontent.com/assets/8986949/7493262/77b79f16-f3ff-11e4-9fac-65be3fe6ee05.jpg)
![picto 2](https://cloud.githubusercontent.com/assets/8986949/7493263/77bc2d9c-f3ff-11e4-8140-d80a25d45e65.jpg)
![picto 3](https://cloud.githubusercontent.com/assets/8986949/7493267/77c79c36-f3ff-11e4-8155-9311458d102d.jpg)
![picto 4](https://cloud.githubusercontent.com/assets/8986949/7493265/77c16596-f3ff-11e4-85ba-8c73d4dd8824.jpg)
![picto 5](https://cloud.githubusercontent.com/assets/8986949/7493264/77c08356-f3ff-11e4-98b0-c52f379b5154.jpg)
![picto 6](https://cloud.githubusercontent.com/assets/8986949/7493266/77c58158-f3ff-11e4-9c80-114abe2a2dce.jpg)
![picto 7](https://cloud.githubusercontent.com/assets/8986949/7493268/77cd6580-f3ff-11e4-9435-9a7d40dc79ce.jpg)
![picto 8](https://cloud.githubusercontent.com/assets/8986949/7493271/77e9129e-f3ff-11e4-9917-b7de45707dd8.jpg)
![picto 9](https://cloud.githubusercontent.com/assets/8986949/7493270/77e83e96-f3ff-11e4-9e95-c8fada4df2e4.jpg)
![picto formacio blau](https://cloud.githubusercontent.com/assets/8986949/7493269/77e77510-f3ff-11e4-87f7-6f8808b22e42.jpg)

**Comment by tagliala** [comment]
Hi,

I have to close this request because it doesn't meet our contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Include a few use cases for your requested icon. How do you plan on using it?
> Attach a single color image or two that represent the idea you're going for.
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

In your case, if you exactly need the above icons, you should consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
