### ISSUE TITLE
some icons are corrupted under Firefox

### ISSUE THREAD

**Issue by m4dz** [FortAwesome/Font-Awesome#6403]
Hi there!

Seems that since the 4.3.0, the following icons are corrupted under Firefox (37.0.2 here):
- rss
- rss-square
- share-alt
- share-square-o
- facebook
- facebook-square
- flickr
- google
- google-plus
- google-plus-square
- instagram
- linkedin
- linkedin-square
- reddit
- reddit-square
- soundcloud
- tumblr
- tumblr-square
- twitter
- twitter-square
- vine
- youtube
- youtube-play
- youtube-square

The [demo page](http://fontawesome.io/icons/) greatly show the issue. No problem using Chrome btw.

**Comment by m4dz** [comment]
Ok, nevermind, the issue is related to µblock / adblock that `display:none` those icons… Sorry for the noise.

**Comment by tagliala** [comment]
no problem. Refers to #1799 and mentioned in the troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#are-youyour-customers-using-adblock-plus

closing here
