### ISSUE TITLE
Icon request: stoplight

### ISSUE THREAD

**Issue by Jrizzi1** [FortAwesome/Font-Awesome#6405]

**Comment by tagliala** [comment]
any example?

**Comment by sp-csmithhill** [comment]
This one is good-
https://cdn0.iconfinder.com/data/icons/cars-and-delivery/512/red_traffic_light-512.png
A bit more rounded-
http://cliparts.co/cliparts/Aib/KeB/AibKeBqzT.png

I would find this useful as an icon for the Workflow section of our application. Our Workflow is based on a "Warnings/Errors" (Yellow light/Red light) system so this would be perfect.

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons?q=traffic-light&s=solid%2Cbrands

**Comment by tagliala** [comment]
Duplicate of #2456
