### ISSUE TITLE
Icon Request: fa-idea

### ISSUE THREAD

**Issue by Yashwa** [FortAwesome/Font-Awesome#6411]
![idea](https://cloud.githubusercontent.com/assets/6202938/7509709/fd726386-f4b1-11e4-8ae8-e956a9b28288.png)

**Comment by tagliala** [comment]
there is already a lightbulb: http://fontawesome.io/icon/lightbulb-o/

a request for an active lightbulb/idea is here: #2817, please +1 that request and post there your example

closing here
