### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by rones01** [FortAwesome/Font-Awesome#6413]
Hi, can you create new icon?

**Comment by tagliala** [comment]
sorry, I didn't get this request

could you please clarify?

Take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by rones01** [comment]
Hello, 

I need to create a new record font icon , but I do not know how to do it . I
do not have much experience with Adobe Illustrator and SVG files . In Annex 
sending the message that you would need to include font icons.



Thank you for answer
-- 
S pozdravem

Petr Roneš
email: rones01@seznam.cz


---------- Původní zpráva ----------
Od: Geremia Taglialatela <notifications@github.com>
Komu: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com>
Datum: 9. 5. 2015 10:59:55
Předmět: Re: [Font-Awesome] New Icon (#6413)

"

sorry, I didn't get this request

could you please clarify?

Take a look at our contributing guidelines: https://github.com/FortAwesome/
Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
(https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

—
Reply to this email directly or view it on GitHub
(https://github.com/FortAwesome/Font-Awesome/issues/6413#issuecomment-100453107)
. 





"=

**Comment by tagliala** [comment]
Hi, please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
