### ISSUE TITLE
Icon request: abacus / counting-frame

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#6414]
<img src="https://www.dhpa.nl/assets/images/icon_telraam.png">

**Comment by tagliala** [comment]
If I well remember this is a duplicate

**Comment by G-Driver** [comment]
I've alredy searched for it, but couldn't find a dup, so if you can find it we can close this one.

**Comment by tomgendron** [comment]
+1

**Comment by ellenhutchings** [comment]
+1

**Comment by rexfordkelly** [comment]
+1
I actually need this right now, for an accounting app.

**Comment by TerryDieckmann** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/abacus?style=solid
