### ISSUE TITLE
Icon Request: fa-highlighter

### ISSUE THREAD

**Issue by chetan-jadhav** [FortAwesome/Font-Awesome#6415]
I am working on white-boarding functionality, and I am using font awesome icons for building toolbar. Thanks for providing such a clean icons.

For toolbar I got pen, eraser, rotate, pan, zoom. But I am struggling with highligher Icon. Can you please help me with that. Attaching one sample image.  Hope that I made am clear with my requirement. 

Thanks in advance!

https://www.iconfinder.com/icons/393683/highlighter_icon#size=128

![highlighter](https://cloud.githubusercontent.com/assets/276935/7515092/7a57c466-f4e1-11e4-9adc-f8d4e7d84621.png)

**Comment by tomgendron** [comment]
+1

**Comment by tagliala** [comment]
dup of #2095 , please +1 that request

closing here
