### ISSUE TITLE
Icon request: icon-blogspot, icon-mailchimp

### ISSUE THREAD

**Issue by timhannifan** [FortAwesome/Font-Awesome#6417]
Please please!

**Comment by tagliala** [comment]
blogspot = #1088 ?
mailchimp: #3379 

probably all dups, closing here. feel free to comment if blogspot is something different from #1088

**Comment by datelligence** [comment]
Can you please explain us why the blogger icon is missing?  Not awesome at all,  due to a simple omission,  indeed there has been many requests,  since 2 years ago.
