### ISSUE TITLE
Icon Request: icon-sofa

### ISSUE THREAD

**Issue by Tiffwillson** [FortAwesome/Font-Awesome#6420]
Hey, Thank you fa-fa awesome is amazing. 

Building a platform for interior design. Need an icon to symbolize a bathroom.  

https://www.iconfinder.com/icons/504792/bath_tub_bath_tub_and_shower_claw_tub_with_shower_clawfoot_tub_jacuzzi_tub_icon#size=128

**Comment by tagliala** [comment]
Just saw your +1 on the proper request #759 , closing here as a duplicate
