### ISSUE TITLE
Icon Request: Feather

### ISSUE THREAD

**Issue by stevenmw** [FortAwesome/Font-Awesome#6421]
In 2013 I submitted a request for a feather icon. I intended to use it to represent Apache, but ever since people have commented wanting a feather in general.

It was requested a new thread be started to request a feather icon, but users kept adding to mine. I have closed my thread and opened this one for those wanting a feather icon. Whether it is to represent a quill / feather pin, Apache, whatever.

My old request was issue #1639 

Thanks.

**Comment by gquipster** [comment]
+1

**Comment by tagliala** [comment]
@stevenmw closing this one and reopening #1639 because it has more +1s.

Renaming #1639 to include feather in the title
