### ISSUE TITLE
Icon Request: Envato Stores Icons

### ISSUE THREAD

**Issue by abbynucup** [FortAwesome/Font-Awesome#6424]
I hope you can include the following icons in Font Awesome:

fa-envato [Envato: http://market.envato.com]
![Logo of Envato](http://i.stack.imgur.com/wNbCx.jpg)

fa-themeforest [ThemeForest: http://themeforest.net/]
![Logo of ThemeForest](http://i.stack.imgur.com/dmPCn.jpg)

fa-codecanyon [CodeCanyon: http://codecanyon.net/]
![Logo of CodeCanyon](http://i.stack.imgur.com/kG55D.jpg)

fa-videohive [VideoHive: http://videohive.net]
![Logo of VideoHive](http://i.stack.imgur.com/CAcxb.jpg)

fa-audiojungle [AudioJungle: http://audiojungle.net]
![Logo of AudioJungle](http://i.stack.imgur.com/LqQiX.jpg)

fa-graphicriver [GraphicRiver: http://graphicriver.net]
![Logo of GraphicRiver](http://i.stack.imgur.com/22hUl.jpg)

fa-photodune [PhotoDune: http://photodune.net]
![Logo of PhotoDune](http://i.stack.imgur.com/gGsEN.jpg)

fa-3docean [3DOcean: http://3docean.net]
![Logo of 3DOcean](http://i.stack.imgur.com/5LXcW.jpg)

fa-activeden [ActiveDen: http://activeden.net]
![Logo of ActiveDen](http://i.stack.imgur.com/zW5O2.jpg)

I requested this since you already included some of the common social media icons such as facebook, twiiter and google+. The icons will be beneficial to developers and designers whose selling their work in Envato Market (http://market.envato.com) and it is very important for freelancers like us.

Thanks a lot! Cheers.

**Comment by xpeeder** [comment]
wow Great job mate :+1:

**Comment by maimairel** [comment]
+1

**Comment by atticthemes** [comment]
This would indeed be a nice addition.

**Comment by tagliala** [comment]
Sorry, can't leave this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Theme Forest is here: #2937

**Comment by magentapose** [comment]
+1000

**Comment by anteksiler** [comment]
+1 but only for Envato logo, not sub sites.

**Comment by abbynucup** [comment]
Noted, I did searched for the existing requests and dome supporting:

Icon Request: fa-envato #5851
Icon Request: Themeforest #2937
Icon Request: Graphicriver #2938

I created a separate requests for the following icons too (to meet the requirements)

Icon Request: CodeCanyon (fa-codecanyon) #6467
Icon Request: VideoHive (fa-videohive) #6468
Icon Request: AudioJungle (fa-audiojungle) #6469
Icon Request: PhotoDune (fa-photodune) #6471
Icon Request: 3DOcean (fa-3docean) #6472
Icon Request: ActiveDen (fa-activeden) #6473

For those who supported this request, please support the updated requests.

**Comment by tagliala** [comment]
@abbynucup thanks!

**Comment by ummahusla** [comment]
Actually it would be quite useful.

**Comment by jakeyeaton** [comment]
Yeah they would be amazing

**Comment by TiagoDeSousa** [comment]
+1 - It's pretty obvious these icons should be included. Common FontAwesome!!

**Comment by no81no** [comment]
+1

**Comment by ervind** [comment]
+1

**Comment by TiagoDeSousa** [comment]
+1

**Comment by DifferThemes** [comment]
+1
