### ISSUE TITLE
Icon Request: Elance.com Icon

### ISSUE THREAD

**Issue by abbynucup** [FortAwesome/Font-Awesome#6427]
I hope you can include the plain version of the Elance.com Icon in Font Awesome:

![Logo of Elance](http://i.stack.imgur.com/KklpL.jpg)

I requested this since you already included some of the common social media icons such as facebook, twiiter and google+. The icons will be beneficial to developers and designers whose working in Freelancer and it is very important for freelancers like us.

Thanks a lot! Cheers.

**Comment by tagliala** [comment]
dup of #3445, please +1 that request

closing here
