### ISSUE TITLE
Icon Request: fa-contract (paper and pen)

### ISSUE THREAD

**Issue by kevinbarone** [FortAwesome/Font-Awesome#6430]
![contract-512](https://cloud.githubusercontent.com/assets/1945885/7555582/a1b16c36-f71d-11e4-9502-a95591eca03a.png)
Would love to see a contract icon. Thanks for the great work! - Kevin

**Comment by tomgendron** [comment]
+1

**Comment by tagliala** [comment]
Maybe #5663 could also represent a contract

**Comment by sebastienbarre** [comment]
This is good, +1

**Comment by jlevesqu** [comment]
HO Yeah !  +++++11111

**Comment by arielfischer** [comment]
+1 Agreed!

**Comment by yardensachs** [comment]
+1

**Comment by kptranum** [comment]
+1

**Comment by fassem** [comment]
love it! +1

**Comment by yalg** [comment]
+1 :)

**Comment by Szyp** [comment]
+1

**Comment by Franekkk** [comment]
+1

**Comment by yaim** [comment]
+1

**Comment by devxone** [comment]
+1

**Comment by baumgardc** [comment]
Any update on this?

**Comment by Lesha17** [comment]
+1

**Comment by iYsood** [comment]
+1

**Comment by simasbu** [comment]
+1

**Comment by kiminya-raphael** [comment]
+1

**Comment by kuya1284** [comment]
+1

**Comment by fxmountain** [comment]
+1

**Comment by kakakhang** [comment]
+1

**Comment by chinkan** [comment]
+1

**Comment by fshafique** [comment]
+1
(I already gave it a thumbs up, but like the rest of the sheep I'm also giving it a "+1")

**Comment by darshan-serpent** [comment]
:+1:  +1 For Sure!!!!!!!!

What is the Progress on this? Is it added?

If not, then do we have any similar near Icon to use temporarily, thanks!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=signature

**Comment by sudhir-erpharbor** [comment]
Is it available now?

**Comment by sensibleworld** [comment]
@sudhir-erpharbor Yup.
