### ISSUE TITLE
Icon Request: Polygon

### ISSUE THREAD

**Issue by bpajer** [FortAwesome/Font-Awesome#6433]
Hi,

can you please create a new icon showing a polygon a shape like https://cdn0.iconfinder.com/data/icons/mobile-development-icons/256/Hatch_polygon.png

thanks

**Comment by tagliala** [comment]
what is the use case? it needs to be exactly like that?

**Comment by bpajer** [comment]
hi use case is to create a polygon geofence on google maps custom map implementation. that link describes it very nicely. thx

**Comment by dbauszus** [comment]
I would use something like this. I am doing exclusively web mapping interfaces and like to use FontAwesome. I just did a request myself for drawing a line feature.

**Comment by ZSREINER** [comment]
+1

**Comment by tagliala** [comment]
Is there any better title for this request? Polygon is way too generic, it could be confused with #1302

**Comment by c1droid** [comment]
Icon Request Map Maker Polygon.

**Comment by shahzadns** [comment]
+1
@tagliala May be "boundary" is a better title instead of polygon.
thanks.

**Comment by maydemirx** [comment]
+1

**Comment by erjiang** [comment]
Hi, I think this is related to #3558 which seems to belong in a larger set of drawing-tool icons (e.g. draw polygon, draw geofence, lasso selection could all be represented by this).

**Comment by tagliala** [comment]
Hi,

https://fontawesome.com/icons/draw-polygon?style=solid

If that does not fit the use case, Please 👍  #14305
