### ISSUE TITLE
Icon request: fa-jumbucks

### ISSUE THREAD

**Issue by iquidus** [FortAwesome/Font-Awesome#6434]
Hi,

I'm one of the developers of Jumbucks (http://getjumbucks.com), we would find a lot of use having a Jumbucks icon as part of font-awesome. Currently we use font-awesome in a number of our projects, e.g http://explorer.getjumbucks.com , https://twitter.com/getjumbucks/status/597318556246614016 . This icon would mostly be used in bootstrap navbars and menus, by both the dev team, and our dedicated community.

![jumbucks](https://cloud.githubusercontent.com/assets/1858594/7556884/400efd0c-f7d8-11e4-9289-5b8b1d9da4d1.png)

Note: I'm happy to provide svg (github doesnt want to let me attach)

Thanks,

**Comment by ElevenXi** [comment]
+1

**Comment by jyap808** [comment]
+1

**Comment by abuckle** [comment]
+1

**Comment by thekashkings** [comment]
+1

**Comment by Silverstacker** [comment]
+1

**Comment by Killerclown69** [comment]
+1

**Comment by gambitconfirm** [comment]
+1

**Comment by collinlahay** [comment]
+1

**Comment by OKtoshi** [comment]
+1

**Comment by iquidus** [comment]
I see this didn't make it into 4.4.0, is there anything I can to do assist with the addition of this icon in the next release?

**Comment by jyap808** [comment]
I approve this message.

**Comment by aethior** [comment]
`getjumbucks.com` is currently a parked domain.

cc/ @tagliala
