### ISSUE TITLE
Icon Request: fa-excel

### ISSUE THREAD

**Issue by giordanolima** [FortAwesome/Font-Awesome#6435]
Use in buttons like "Export to Excel"
![excel-icon](https://cloud.githubusercontent.com/assets/8314190/7564702/cd78900e-f7bf-11e4-8f04-6f6070c1bbc5.png)

**Comment by tomgendron** [comment]
+1

**Comment by tagliala** [comment]
I think http://fontawesome.io/icon/file-excel-o/ will do the job

Otherwise, please +1 #4152
