### ISSUE TITLE
Filter request: fa-learn for fa-graduation-cap

### ISSUE THREAD

**Issue by JeroenSormani** [FortAwesome/Font-Awesome#6436]
A general 'learn' icon. This would look awesome

![image](https://cloud.githubusercontent.com/assets/5774447/7564759/26a9ec02-f7ea-11e4-8964-25663f291628.png)

This can be used for tons of things, my personal use case would be `Want to learn more about this plugin?` kind of case.

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/graduation-cap/

Leaving this open and renaming, I will add a learning filter

**Comment by JeroenSormani** [comment]
Ah thnx! Totally missed that one, searched for a bunch of things, but not that :wink:

**Comment by tagliala** [comment]
added `learning`, `school` and `student` filters
