### ISSUE TITLE
Icon Request: fa-hockey

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6440]
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by tagliala** [comment]
any example?

**Comment by dmandave** [comment]
+1 please- skates, hockey sticks, gloves, nets would be awesome

**Comment by lickmydesign** [comment]
+1

**Comment by sensibleworld** [comment]
We now have a few hockey-related icons: https://fontawesome.com/icons?d=gallery&q=hockey
