### ISSUE TITLE
Icon Request: fa-basketball

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6441]
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by tagliala** [comment]
any example?

You can use the dribbble logo http://fontawesome.io/icon/dribbble/

**Comment by BrianHuang** [comment]
Maybe it's a good idea to add a new category for sports icons!

**Comment by funkytaco** [comment]
I'd like to see this as well.

**Comment by lickmydesign** [comment]
+1

**Comment by davegandy** [comment]
We've added `fa-basketball-ball` to 5.0.5 in 3 different styles. The solid style is a part of FA Free:
https://fontawesome.com/icons/basketball-ball?style=solid

We've also added `fa-basketball-hoop` in 3 different styles as a part of Pro:
https://fontawesome.com/icons/basketball-hoop?style=solid
