### ISSUE TITLE
Icon Request: fa-squash

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6442]
The sport, not the food!
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by tagliala** [comment]
any example?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/racquet?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
