### ISSUE TITLE
Icon Request: fa-fishing (fish with hook)

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6445]
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by tagliala** [comment]
any example? a fish could be enough?

**Comment by paulvanderhoeven** [comment]
I was thinking of a fishing rod, but perhaps a fish would be more
multi-purpose. Or why not both, as two distinct icons.

**Comment by smaspe** [comment]
most icons representing fishing consist of a fish, plus a line and a hook next to its mouth, possibly a rod if the image is large enough

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by SeanLF** [comment]
:+1:

**Comment by Ry04Mac** [comment]
+1

**Comment by KajoMan** [comment]
+1

**Comment by dpfem** [comment]
+1

**Comment by josephlimb** [comment]
+1

**Comment by snds** [comment]
Two, maybe 3 icons would be a good solution. A hook and line for something specifically for "fishing", a fish for "seafood", and a hook for "phishing." Depending on use, any and all could be used for nearly all scenarios, but would allow the use case to determine the need.

**Comment by ssm1985** [comment]
+1

**Comment by pacoweb** [comment]
+1

**Comment by nicolasmarengo** [comment]
+1

**Comment by bruntrd** [comment]
+1

**Comment by IFIAdmin** [comment]
+1 +1 +1
There is scope to recognise the sport of fishing through a set of related icons

- Icon request: fishing hook
- Icon request: fishing bobber
- Icon request: fishing lure
- Icon request: fishing rod
- Icon request: fishing fly
- Icon request: worm

**Comment by sensibleworld** [comment]
Just aded to version 6: https://fontawesome.com/v6.0/icons/fishing-rod?s=solid

<img width="1011" alt="Screen Shot 2021-05-27 at 2 12 29 PM" src="https://user-images.githubusercontent.com/529604/119876155-9326f180-bef5-11eb-99a7-2349007417a9.png">
