### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by paulvanderhoeven** [FortAwesome/Font-Awesome#6449]
The world is a better place with font-awesome!
Thanks for considering this.

**Comment by simonfranz** [comment]
This is simlar to #3614

**Comment by tagliala** [comment]
@simonfranz thanks

This is a duplicate of one of those three

grapes is a dup of #5691 , please +1 that request
wine bottle is a dup of #1762 , please +1 that request
wine glass is a dup of #3614 , please +1 that request
