### ISSUE TITLE
Add stacked plus and minus icons

### ISSUE THREAD

**Issue by Radnen** [FortAwesome/Font-Awesome#6450]
Add miniature plus and minus icons that reside to the lower right to Font Awesome.

The issue: there exists user-plus and cart-plus and though the plus icons are in different positions, most things can get by with a smaller plus icon to the lower-right. There are many icons without a plus associated with it. There are no minus icons for them (we could stack on the ban icon, but it may mean a different thing depending on context).

Now, It is possible to do this with css tricks, but I think scaling and rotation would be much easier and cleaner if these icons were developed in the same size as everything else that's stackable, but made smaller and pushed to the lower-right.

It has the benefit of being styled and colored so we can do green pluses and red minuses, etc. I think many web apps will definitely benefit from this kind of modularity.

It also has the benefit that if you keep them to one quadrant you can rotate them to get the other 4 positions. This saves you from creating a new quadrant for each plus and minus.

They could be called fa-mini-plus and fa-mini-minus.

**Comment by tagliala** [comment]
Hi,

please take a look here: #1181 and here https://github.com/nyon/fontawesome-actions

Closing here
