### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by msgliniewicz** [FortAwesome/Font-Awesome#6451]
Hi, 

Seeking a host of icons or the developmental disability community. This includes the  top level categories like Autism or Wounded Warrior but actual services themselves. 

Like: 
Adaptive Sports
![adaptive sports 3](https://cloud.githubusercontent.com/assets/11395933/7568728/91d62b68-f7c1-11e4-8814-c0eb7bfd539b.jpeg)
![adaptive sports 2](https://cloud.githubusercontent.com/assets/11395933/7568729/91def0c2-f7c1-11e4-9db3-f9d7cb7903a0.jpeg)
![adaptive sports](https://cloud.githubusercontent.com/assets/11395933/7568731/9411fb00-f7c1-11e4-89b5-50a098008696.png)

Horse Therapy
![horse therapy 2](https://cloud.githubusercontent.com/assets/11395933/7568597/e32b5f7a-f7c0-11e4-862e-171be5378ab4.jpg)
![horse therapy](https://cloud.githubusercontent.com/assets/11395933/7568600/e590d8a8-f7c0-11e4-8739-a7c3c242745f.jpg)
![aba photo](https://cloud.githubusercontent.com/assets/11395933/7568640/1009315c-f7c1-11e4-9fe3-9ea83f230046.jpg)

ABA
![aba photo](https://cloud.githubusercontent.com/assets/11395933/7568733/9b851534-f7c1-11e4-8a84-b40e791525e4.jpg)
In home care

![home-care-700x505](https://cloud.githubusercontent.com/assets/11395933/7568882/8e421952-f7c2-11e4-93e3-d2d0a835557c.jpg)

CNS Support
![cna-1](https://cloud.githubusercontent.com/assets/11395933/7568852/60620c9a-f7c2-11e4-9ed7-130ba1b30cf2.jpg)
![cna-1](https://cloud.githubusercontent.com/assets/11395933/7568769/e23ff4da-f7c1-11e4-8425-c46da0e55dff.jpg)

Physical Therapy
![why-physical-therapy](https://cloud.githubusercontent.com/assets/11395933/7568845/593b7546-f7c2-11e4-99e0-fbd228b09c01.jpg)

Speech Therapy
![speech-therapy](https://cloud.githubusercontent.com/assets/11395933/7568833/4b625408-f7c2-11e4-9881-82296084d7c0.png)

behavior therapy 
![behavior therapy 3](https://cloud.githubusercontent.com/assets/11395933/7568830/493ece18-f7c2-11e4-89e8-da68c9570928.jpeg)
![cognitive-behavioral-therapy-techniques-300x225](https://cloud.githubusercontent.com/assets/11395933/7568831/494869b4-f7c2-11e4-86b9-39e4556061af.jpg)

Autism would use basic ribbon or puzzle piece
![puzzle-piece-5-hi](https://cloud.githubusercontent.com/assets/11395933/7568495/5a91a71e-f7c0-11e4-94f8-cef0eaecd87e.png)
![autism-awareness](https://cloud.githubusercontent.com/assets/11395933/7568498/5e273c2c-f7c0-11e4-9245-ad238170f36c.jpg)

Wounded Warrior
![wounded warrior](https://cloud.githubusercontent.com/assets/11395933/7568743/aacf38bc-f7c1-11e4-8985-85ef15262df5.png)
I am sure there is a Copy right attached, just like using FB, twitter, linkedin etc. it would only be used to ID companies who support the Wounded Warrior population. 

My this my 1st ever request, if I am missing any info, please let me know.

Oh, this will be used on Geodirectory theme. 

Thanks

**Comment by tagliala** [comment]
Sorry but I really have to close this request because it doesn't meet our contributing guidelines.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

a puzzle piece is already here: http://fontawesome.io/icon/puzzle-piece/
some icons are not suitable for 14px icon size
I suppose #280 could work to represent equite therapy

Please split this request in individual requests. I know that you need all of them in your use case but this request is hard to manage

Closing here and thanks for your understanding
