### ISSUE TITLE
Icon Request: fa-creativecommons

### ISSUE THREAD

**Issue by how-i-roll** [FortAwesome/Font-Awesome#6452]
I think the creative commons symbol, "cc" inside a circle, would be very useful to discreetly provide copyright attribution for an image. Here's the link so you can see what I'm talking about: http://creativecommons.org/licenses/by-sa/3.0/

**Comment by tiesont** [comment]
Seems worth noting that there is already a CC-specific font you can use: http://cc-icons.github.io/

**Comment by tagliala** [comment]
dup of #544  or #5276 , please +1 the proper request

closing here
