### ISSUE TITLE
Icon Request: fa-amazon, fa-ebay, fa-reverbnation

### ISSUE THREAD

**Issue by tamardesign** [FortAwesome/Font-Awesome#6455]
Hey there. Would love to include Amazon, Ebay and ReverbNation in my list of social icons. I realize Amazon and Ebay aren't exactly social networks, but they are just as important to link to as itunes, facebook, etc. Any chance?
![reverbnation-icon](https://cloud.githubusercontent.com/assets/12402394/7577219/dc3961a0-f7fa-11e4-98dd-ab30135ae513.png)
![ebay](https://cloud.githubusercontent.com/assets/12402394/7577220/dc4acc42-f7fa-11e4-8969-ad8f217d6efb.jpg)
![amazon](https://cloud.githubusercontent.com/assets/12402394/7577221/dc698038-f7fa-11e4-9f83-66d7137144f8.jpg)

**Comment by tagliala** [comment]
amazon #471 
ebay: #1783 
reverbnation: #2632

please +1 the above requests

all dups, closing here!
