### ISSUE TITLE
Icon Request: fa-bee

### ISSUE THREAD

**Issue by emn8or** [FortAwesome/Font-Awesome#6456]
please make an icon symbolizing a bee with wings. I know there is a bee at fa-forumbee but it has no wings. :(

thanks in advance

**Comment by tagliala** [comment]
(forumbee looks like a strawberry cream lollipop to me)

**Comment by depruett** [comment]
I would like to second this request. Please create a bee icon.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by Legionc** [comment]
+1
No stinger please!
Bees have four wings btw...

**Comment by tabame** [comment]
+1

**Comment by ntercity** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by YaegerDesign** [comment]
@JoostDB has given a great example here: [Icon Request: fa-bee #8130](https://github.com/FortAwesome/Font-Awesome/issues/8130)
![7aeb5254-9e7c-11e5-8a9d-84a07faa4e3b 1](https://cloud.githubusercontent.com/assets/4699897/23315923/4c03bcca-fa96-11e6-96f1-f5c80977fd49.png)

**Comment by barskuk** [comment]
+1

**Comment by approximatenumber** [comment]
+1

**Comment by muster-mark** [comment]
+1 Was just going to request this myself.

**Comment by anthony0030** [comment]
+1

**Comment by anthonyDrury** [comment]
+1

**Comment by spacetourist** [comment]
+1 bump! :bee: buzzin about this idea

**Comment by bradwarwick** [comment]
+1

**Comment by bohdan-didukh** [comment]
+1

**Comment by khzouroussama** [comment]
+1

**Comment by anthonyDrury** [comment]
> @joostdb has given a great example here: [Icon Request: fa-bee #8130](https://github.com/FortAwesome/Font-Awesome/issues/8130)
> ![7aeb5254-9e7c-11e5-8a9d-84a07faa4e3b 1](https://cloud.githubusercontent.com/assets/4699897/23315923/4c03bcca-fa96-11e6-96f1-f5c80977fd49.png)

Bees have four wings.

**Comment by MartinCron** [comment]
+1

**Comment by TheGoldenCactus11** [comment]
+1, I would love a side-on view, and a view from above, both including the wings!

**Comment by Wingo5315** [comment]
+1

**Comment by sensibleworld** [comment]
We have this now in version 6: https://fontawesome.com/v6.0/icons/bee?s=solid

<img width="1013" alt="Screen Shot 2021-05-27 at 2 18 39 PM" src="https://user-images.githubusercontent.com/529604/119876945-6fb07680-bef6-11eb-8397-d1f7901dc23b.png">
