### ISSUE TITLE
Icon request: fa-datatype-

### ISSUE THREAD

**Issue by ataft** [FortAwesome/Font-Awesome#6460]
Data Type icons group with the following:

text or string - represent with "Abc"
numeric - link to heavily requested hashtag icon with "#", or "123"
decimal - "1.25"
percent - "%"
date - link to existing fa-calendar icon
yesno - "Y/N"
boolean - "0/1"

**Comment by hudsonb** [comment]
+1

**Comment by tagliala** [comment]
sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

there are duplicates hashtag: #1123, percent: #1292 

date is already here

Please split this request in individual requests

Closing here
