### ISSUE TITLE
Icon request: fa-cutlery-fork

### ISSUE THREAD

**Issue by hectorsegarra** [FortAwesome/Font-Awesome#6464]
Hi, 
This comunity have cutlery and sopoon icons, but maybe we need (i need) a fork-alone or similars.
I search, but no results T__T.

icon-name: icon-cutlery-fork
use cases for your requested icon: restaurants web, bar web, other webs about food.
Attach a single color image: https://www.iconfinder.com/icons/364641/cutlery_fork_kitchen_tableware_icon#size=128

Thank

**Comment by G-Driver** [comment]
+1

**Comment by Inttegrum** [comment]
+1

**Comment by sensibleworld** [comment]
We've got these now! https://fontawesome.com/v6.0/icons?q=cutlery
