### ISSUE TITLE
Icon Request: Please Add GEL (Georgian Lari) Currency Symbol

### ISSUE THREAD

**Issue by vdanelia** [FortAwesome/Font-Awesome#6465]
Thousends of developers and designers're using Font-Awesome in our country and please add Georgian Lari Currency Symbol, here is the official link from wikipedia

http://en.wikipedia.org/wiki/Georgian_lari#/media/File:Sign_of_Georgian_Lari.svg
http://en.wikipedia.org/wiki/Georgian_lari

Thank you in advanced

**Comment by tagliala** [comment]
dup of #3973, please +1 that request

closing here

**Comment by vdanelia** [comment]
+1

**Comment by vdanelia** [comment]
I did and thanks :)
