### ISSUE TITLE
Icon request: icon-yin-yang

### ISSUE THREAD

**Issue by papalozarou** [FortAwesome/Font-Awesome#647]
Loving the work. FIrst time I've used it in a project and it's saving me a shed load of time.

Purely selfish, but any chance of a yin/yang icon?

**Comment by G-Driver** [comment]
+1

**Comment by renanyoy** [comment]
+1  a nice icon for blending operations

**Comment by aykayen** [comment]
+1

**Comment by ooscarr** [comment]
There's an emoji for that ☯ but it doesn't work everywhere and it's different, in OS X it looks like the PEPSI logo.

**Comment by renanyoy** [comment]
yup, but it doesn't match FA metrics...

**Comment by Code-Name-Debian** [comment]
Yes please.

**Comment by vipulism** [comment]
+1

**Comment by vomLeben** [comment]
+1 would love to use this Icon on my german blog about better living

**Comment by ssalve** [comment]
Yes. Been googling this. Would be "awesome"!

**Comment by fabiograsso** [comment]
+1

**Comment by sharpless512** [comment]
+1

**Comment by Shulin** [comment]
+1

**Comment by luolong** [comment]
+1

**Comment by gebeer** [comment]
+1

**Comment by oarashi** [comment]
+1

**Comment by sparkcom** [comment]
+ 1

**Comment by bdube83** [comment]
+1

**Comment by luolong** [comment]
Guys, lets not spam the issue with tons of "+1" comments -- use the new reactions feature and add our +1 reactions to the main issue post instead ... Thanks :)

**Comment by khasky** [comment]
+1

**Comment by warsaw** [comment]
There should also be a white-on-left-black-on-right version.  See my GH icon. :)

**Comment by tung81tn** [comment]
yes

**Comment by bnspired** [comment]
This has my vote!

**Comment by dmjio** [comment]
+1

**Comment by JackyHan** [comment]
+1

**Comment by shkbahmad** [comment]
+1

**Comment by diomed** [comment]
+1 can't believe this doesn't exist.
we should riot!

**Comment by dustcrawler** [comment]
+1

**Comment by webnanny** [comment]
First requested nearly 4 years ago, but still no Yin Yang icon. Pretty please?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/yin-yang?style=solid

**Comment by BonesyWonesy** [comment]
Thank you!
