### ISSUE TITLE
Icon Request: fa-bolt-ban

### ISSUE THREAD

**Issue by mahendra-alladi** [FortAwesome/Font-Awesome#6474]
It would be great to have an icon to represent variant of bolt icon to indicate "not". I use "bolt" to indicate executable condition and need something to represent non-executable condition. Any other ideas would be great.

Thanks in advance
--Mahendra

**Comment by tagliala** [comment]
your request is legit, but please consider icon stacking

**Comment by mahendra-alladi** [comment]
Thanks. That works!
