### ISSUE TITLE
icon request: fa-badge, fa-badge-double

### ISSUE THREAD

**Issue by lucastoledo** [FortAwesome/Font-Awesome#6475]
Dear Font Awesome team,
Could you include the following two badge icons, please?

I intend to use the badges on my web application. Since I already use Font Awesome, I thought it would be good to use them within the framework.

Thank you in advance,
Lucas

![badge_icons](https://cloud.githubusercontent.com/assets/1292257/7628887/108277ae-fa20-11e4-8f9c-3b9bf34ae7d1.PNG)

**Comment by ramon86** [comment]
+1

**Comment by tagliala** [comment]
we have both a request for a medal #1898  and a badge #5234

There are examples in medal exactly like the above one

Could you please explain why there is the need of two icons? I do not see different use cases

**Comment by lucastoledo** [comment]
Hi Tagliala,
I am sorry for the late reply. I was away on holiday and I did not have access to my emails.

The use case would be for the following scenario:

The above badges would be used in a web application, inside a drop down list, to differentiate between two items, in the same category, but different from each other.

That's is why I chose to include two icons in a single request. 

I would be more than happy to create a separate request for each icon, if you think that is the best course of action.

The medals you have mentioned above differ from the suggested icons in this request since a medal and a star medal would imply an achievement or recognition for something that is more important. 

This is, of course, subjective to one's own perception.

The above badge imply something less important than a medal, but that still needs differentiation or highlighting. In addition to that, the badges are more generic.  Since one has one ribbon and the other one has two, it is a way to differentiate them nicely.

I hope this answers your question and do not hesitate to contact me again, please.

Thanks, once more,
Lucas

**Comment by sensibleworld** [comment]
We now have a few options that could work for this. Please open a new request if we're still missing what you need.

https://fontawesome.com/icons?d=gallery&q=award
