### ISSUE TITLE
Icon Request: fa-hitbox

### ISSUE THREAD

**Issue by monster010** [FortAwesome/Font-Awesome#6481]
I hope you can include the following icon in Font Awesome:

fa-hitbox [Hitbox: http://hitbox.tv]

<img src="https://f0110c7213101bcee475e2cfb011949a1eccf2aa.googledrive.com/host/0Bwsi49UsCzV7YjZmaFlDTkdMM2c/logo_black/hitbox-logo-v1_icon_b.png" />

I requested this since you already included some of the common brand icons such as youtube, twitch and google+.

Thanks. =)

**Comment by tagliala** [comment]
dup of #6481, please +1 that request

closing here
