### ISSUE TITLE
Icon Request: icon-do-not-enter

### ISSUE THREAD

**Issue by dmland** [FortAwesome/Font-Awesome#6482]
Although it is possible to construct a passable "Do Not Enter" symbol by creating my own ".fa-do-not-enter" CSS rule involving ::before and ::after pseudo-elements and some tweaky transforms and positioning, I would much prefer a professional and concenient FontAwesome official version of the familiar do not enter sign:

![do-not-enter](https://cloud.githubusercontent.com/assets/1907073/7643673/5f67c4d4-fa50-11e4-9ce8-c6357accfa4a.gif)

Here are the official specs for the sign, because I know you work hard to make your icons accurate and gorgeous: http://www.dot.ca.gov/hq/traffops/engineering/control-devices/specs/R11.pdf

**Comment by tagliala** [comment]
it is mostly like http://fontawesome.io/icon/minus-circle/

I know it is not the same thing, proportions matter in this case. There is also a ban sign: http://fontawesome.io/icon/ban/

Given that your request is legit, let me know if one of the above could fit your needs

**Comment by dmland** [comment]
For my purposes, my own cobbled-together .fa-do-not-enter does the trick.

For others, who are not as insanely particular as I am, the appearance of .fa-minus-circle is probably close enough, and the "message" of .fa-ban probably also could serve.
