### ISSUE TITLE
google insight

### ISSUE THREAD

**Issue by fabienegot** [FortAwesome/Font-Awesome#6486]
Hello,
I have an error message from google insight saying "Eliminate render-blocking CSS in above-the-fold content". I have then follow their instruction to embed css with js, but I only have the code for embedding 1 stylesheet. To embed FA, I then used @import url("//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css/"); on my existing stylesheet but the icons are not displayed anymore. Do you have any trick to embed FA with the @import rule or could you please tell me if you know a js where I can embed multiple css within html ? thank you.

**Comment by tagliala** [comment]
Hi, this is a generic support request not related to fontawesome (it could be related to any other css out there) 

I have to close this one, please consider using  stackoverflow

Take also a look here: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

You should not use that import rule, you could try to add the fontawesome stylesheet at the bottom of the page but you also should consider something like

```
<html>
  <head>
    <style>
      .fa {
        display: none;
      }
    </style>
    </head>
  <body>
    <div class="blue">
      Hello, world!
    </div>
  </body>
</html>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
```

closing here but let me know if that helps
