### ISSUE TITLE
Icon Request - icon-border*

### ISSUE THREAD

**Issue by JLTInteractive** [FortAwesome/Font-Awesome#6487]
Icons for border customization:

![image](https://cloud.githubusercontent.com/assets/7664624/7664686/5e0f4be0-fbc5-11e4-8048-8ed54fdbba53.png)

**Comment by tagliala** [comment]
I'm going to close this one in favour of #1927, which is a subset

There are 12 icons, they are strictly related so it makes sense to have them in a single request..

But those also are a set of ["comprehensive icons related to a very specific field"](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

I will keep #1927 open, I don't know Dave's plans
