### ISSUE TITLE
Icon Request: icon-bandcamp

### ISSUE THREAD

**Issue by ItsHamty** [FortAwesome/Font-Awesome#6488]
Hello, could you please add the bandcamp icon? It's really simple and i dont think would be hard to add. <3

It's just a square bent on the right side, it looks like this:

![image](https://cloud.githubusercontent.com/assets/12470865/7665469/f83afac0-fbc0-11e4-9ec8-1960614d3d7c.png)

Thanks in advance :3

**Comment by tagliala** [comment]
dup of #1725 , please +1 that request

closing here
