### ISSUE TITLE
Icon request: icon-wikipedia

### ISSUE THREAD

**Issue by bshowy2k** [FortAwesome/Font-Awesome#6492]
The wikipedia icon is missing, we have a web app that points to Wikipedia :)

thanks,
MLO

![wikipedia](https://cloud.githubusercontent.com/assets/5844238/7667695/322fbafe-fbd0-11e4-92b4-82d524741552.png)

**Comment by tagliala** [comment]
dup of #388 , please +1 that request

closing here
