### ISSUE TITLE
Icon Request: icon-slow-backward, icon-slow-forward

### ISSUE THREAD

**Issue by gregwillits** [FortAwesome/Font-Awesome#6495]
These would be a single triangle version of the fa-backward and fa-forward. So, maybe you'd call them "slow" or whatever.

Actually what I want to use them for is record navigation using four icons for
first/prev/next/last like `|<   <   >   >|` for which I would use fa-step-backward, fa-slow-backward, fa-slow-forward, fa-step-forward.

The double-triangle versions are just too heavy for my purposes.

Although I prefer the appearance of the Video Player icons, you may also want to consider fa-chevron-first and fa-chevron-last versions in the Directional set as well.

THX!

**Comment by Crissov** [comment]
So basically you want a narrow version of `fa-play`and a version thereof pointing in the opposite direction?

Note that there are also other customs for representing _slow_ playback, e.g.: 

[![IEC 60417-2124B](https://www.iso.org/iobp/graphics/grs/ISO263283_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5124B)

**Comment by TomFoyster** [comment]
Any update on these? I have the same issue with `<<` and `>>` being to heavy for prev/next in pagination.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](lighter styles)

**Comment by tagliala** [comment]
I guess this is a request for

https://fontawesome.com/search?q=forward-step&o=r
https://fontawesome.com/search?q=backward-step&o=r

in thin or light style
