### ISSUE TITLE
Icon Request: fa-hourglass

### ISSUE THREAD

**Issue by rajakhurramjaved** [FortAwesome/Font-Awesome#6499]
Hi, 
First of all i must say this is the great work, which you people are doing, stay blessed.

I had seen Time icon, but if we could add "hourglass" traditional sand timer. "http://en.wikipedia.org/wiki/Hourglass".

This is multi-purpose icon, which will be used for time passed, time passing,  time lapse, or time is running out, countdown etc.
![hourglass](https://cloud.githubusercontent.com/assets/12495027/7679503/b74c0fce-fd76-11e4-9299-964413b284f8.jpg)

**Comment by tagliala** [comment]
dup of #492 , planned for 5.0.0 release

closing here
