### ISSUE TITLE
Icon request: icon-filter-times (clear filter)

### ISSUE THREAD

**Issue by jelmqvist** [FortAwesome/Font-Awesome#650]
An icon to clear a previous filter would be much appreciated. 
Something like:

![filter-clear](https://f.cloud.github.com/assets/3216542/50335/136ed462-59a0-11e2-9f50-ba2fb76b7551.png)

or with ban circle instead of the 'x'.

**Comment by wandersonwhcr** [comment]
:+1:

**Comment by thomasbertet** [comment]
:+1:

**Comment by tagliala** [comment]
Reopening for tracking purposes

Refers to #1181

**Comment by nyon** [comment]
I've added fa-filter-remove, fa-filter-times-circle and others to fontawesome-actions here: http://github.com/nyon/fontawesome-actions

**Comment by voltechs** [comment]
Was hoping for something a little more like this... 
![filter-slash](https://cloud.githubusercontent.com/assets/1700514/10294252/4e2ec018-6b76-11e5-941b-4d16a282cc9f.png)

**Comment by kalifa17** [comment]
+1

**Comment by andrejkosyak** [comment]
+1

**Comment by sedrakpc** [comment]
+1

**Comment by mazing** [comment]
+1

**Comment by kingsloi** [comment]
+1

**Comment by aito0077** [comment]
+1

**Comment by mkalpana** [comment]
+1

**Comment by brandonmcconnell** [comment]
+1

**Comment by truetug** [comment]
+1

**Comment by estwanick** [comment]
+1

**Comment by SebastianMucke** [comment]
+1

**Comment by birfincankafein** [comment]
+1

**Comment by Matthew-Bonner** [comment]
+1 just had to create my own version of this icon and add it to a custom glyph font.

**Comment by mikeengland** [comment]
+1

**Comment by abartolo** [comment]
+1

**Comment by cassioscofield** [comment]
+1

**Comment by segreyg** [comment]
+1

**Comment by juncalguinea** [comment]
+1

**Comment by oswaldofreitas** [comment]
+1

**Comment by oswaldofreitas** [comment]
workahound:
<span class="fa-stack">
    <i class="fa fa-filter fa-stack-1x"></i>
    <i class="fa fa-ban fa-stack-2x"></i>
</span>

**Comment by nessroman** [comment]
+1 Need the disable filter icon !

**Comment by ManuelHaas** [comment]
+1 for disable filter icon!
have a look at the **glyphicons-filter-remove** icon it looks much better than a stacked icon IMO

**Comment by DamianoPantani** [comment]
It's been almost 5 years now and nothing happened? BUMP!

**Comment by IceSentry** [comment]
It's now 2018 and still no new icon... It feels like such a basic icon to have.

**Comment by nyon** [comment]
If you desperately need it you can still use fontawesome-actions. See: https://github.com/FortAwesome/Font-Awesome/issues/650#issuecomment-87376652

**Comment by rordi** [comment]
+1, please

**Comment by multinerd** [comment]
I'm starting to feel like this will never be made.

**Comment by Chellie-SC** [comment]
I'd like this icon. "Filters-Off" seems more appropriate.

**Comment by tagliala** [comment]
Hi everyone!

Please note that you can achieve those icons with the power transforms, masking, and layering feature of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/56/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by gbjbaanb** [comment]
As has been said, sometimes you need a single icon for DOM manipulation, and a "filter on, filter off" pair seems to be just one of those cases. 

Its also the most highly up-thumbed icon request in the backlog!

**Comment by Arkellys** [comment]
+1

**Comment by gbjbaanb** [comment]
7 years later... more effort has been spent telling us that we're wrong to want it than ever could have been spent adding the icon!

**Comment by LQuam** [comment]
+1.   Advanced Search algorithms & broad marketplaces in which users can filter on many criteria make a "Clear Filter" icon more needed than ever!

**Comment by rbudnar** [comment]
SVGs don't seem to be a great option for mobile applications. I ended up combining the filter and the times SVGs in the way I wanted (basically what the original author posted) and then converted it to a ttf file using an online converter (icomoon has features for this).

**Comment by jrdesignch** [comment]
++2

**Comment by Dunnenj** [comment]
> An icon to clear a previous filter would be much appreciated.
> Something like:
> 
> ![filter-clear](https://camo.githubusercontent.com/8d8b594e6ca3485d715d51959de1df67f173e6eb/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333231363534322f35303333352f31333665643436322d353961302d313165322d396635302d6261326662373662373535312e706e67)
> 
> or with ban circle instead of the 'x'.

Or an icon like this.  Could be easily made from the filter icon with dollar.

![image](https://user-images.githubusercontent.com/67200790/85207033-63a35880-b326-11ea-913c-4c5c395d297e.png)

**Comment by kristianharmer** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
