### ISSUE TITLE
Icon Request fa-phone-o

### ISSUE THREAD

**Issue by knwilson** [FortAwesome/Font-Awesome#6503]
![telephone31](https://cloud.githubusercontent.com/assets/12503649/7691921/693ae7b8-fd73-11e4-891c-6a6af1159d20.png)

Will like to have a icone of the telephone with just the outline of it please. This will be great to go with the outline of the envelope that you already have.

Thanks in advance!

**Comment by aethior** [comment]
Duplicate of #3750.

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks.

Done via https://github.com/FortAwesome/Font-Awesome/commit/b7ab34b29a39bc4013999aad8cb87d85f03e1f2f
