### ISSUE TITLE
Icon Request: icon-crossed-swords

### ISSUE THREAD

**Issue by 1ns** [FortAwesome/Font-Awesome#6504]
Is possible to include an icon like this? http://www.lolesports.com.br/images/sprites/icon-swords-24e602639268f4f1796a7487bcf8908f.png

This icon represent battles(Rly?). More info can be find here http://en.wikipedia.org/wiki/Versus

**Comment by Insone** [comment]
Thank you, @tagliala , and sorry for the title.

**Comment by tagliala** [comment]
no problem :+1:

**Comment by aethior** [comment]
Hi @1ns,

This icon was added in v5.4.0.
Check https://fontawesome.com/v6/icons/swords

Regards.

cc/ @tagliala
