### ISSUE TITLE
Icon Request: fa-brain

### ISSUE THREAD

**Issue by jpbaltra** [FortAwesome/Font-Awesome#6505]
Hello! I would like to request a icon, I need to illustrate "knowledge" in a services page for an engineering company and a brain would be perfect, I'm attaching the icon idea. Thanks!

![image](https://cloud.githubusercontent.com/assets/12505472/7694227/cbe39c62-fdb3-11e4-9e04-f108f143abab.png)

**Comment by tagliala** [comment]
dup of #2075, please +1 that request and post there your example

closing here

**Comment by WolfgangFahl** [comment]
this icon is better than the one in #2075

**Comment by gunnar2k** [comment]
+1
