### ISSUE TITLE
Icon Request: fa-balance

### ISSUE THREAD

**Issue by jpbaltra** [FortAwesome/Font-Awesome#6506]
Hello! I would like to request a icon, I need to illustrate "balance" in a services page for an engineering company , I'm attaching the icon idea. Thanks!

![image](https://cloud.githubusercontent.com/assets/12505472/7694253/232c3880-fdb4-11e4-95c7-51daf19cba99.png)

**Comment by tagliala** [comment]
dup of #2818 , please +1 that request

closing here
