### ISSUE TITLE
Icon Request: fa-series (cards, deck)

### ISSUE THREAD

**Issue by toonvandeputte** [FortAwesome/Font-Awesome#6507]
The existing icons that communicate a 'series' concept, all don't quite fit my use cases. Either they are visually too similar to a hamburger icon, or they are more specific for a list or grid.
So I designed this icon, which I've added to my custom fonticons pack and which I think might be a useful addition to the default set.
![series-01](https://cloud.githubusercontent.com/assets/6859906/7696928/f8edada2-fe02-11e4-92db-2d895c274882.png)

**Comment by tagliala** [comment]
I don't remember if this is a duplicate, but we need a better title

**Comment by toonvandeputte** [comment]
Some suggestions:
* sequence
* set
* group
* collection

Furthermore, there is a subtle but sometimes important difference between a true sequence, where ordering is important, and an unordered collection of related items.

**Comment by z38** [comment]
+1

**Comment by brunoaugusto** [comment]
I'd support that.

Such icon could represent cards (as a deck), pile of papers, clipboard or even general collections.

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/cards?s=solid
https://fontawesome.com/icons/clone?s=solid
https://fontawesome.com/icons/rectangle-history?s=solid
https://fontawesome.com/icons/rectangle-vertical-history?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
