### ISSUE TITLE
Icon Request: fa-meat

### ISSUE THREAD

**Issue by latiosthinh** [FortAwesome/Font-Awesome#6510]
I'm working on a restaurant website project.
And i am really really impressed with you guys on this Font.
Thank you so much!
![hot56](https://cloud.githubusercontent.com/assets/7105120/7704013/ebaf73a6-fe65-11e4-8749-6c730ce5a025.png)
![meat27](https://cloud.githubusercontent.com/assets/7105120/7704039/15e19744-fe66-11e4-99d4-0c1b57cb9e93.png)
![fish52](https://cloud.githubusercontent.com/assets/7105120/7704040/15e7cb5a-fe66-11e4-8800-d4150265ee62.png)
![coke](https://cloud.githubusercontent.com/assets/7105120/7704041/15eebc76-fe66-11e4-808f-ce707eb8ecca.png)

**Comment by tagliala** [comment]
Renaming this as icon-meat

fish: #2722 
milk: #5051 

Please open a new request for soup

**Comment by tagliala** [comment]
ops that was not a milk bottle... drink : #1762  or #6449  ?

**Comment by latiosthinh** [comment]
that would be like a coke bottle

**Comment by simonfranz** [comment]
+1

**Comment by dfyx** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by vincentp** [comment]
+1

**Comment by haseeb-basil-pl** [comment]
+1

**Comment by Rosa-Leeke** [comment]
+1

**Comment by sensibleworld** [comment]
We have a bunch of options now for carnivores:

https://fontawesome.com/icons?d=gallery&q=meat
https://fontawesome.com/icons/steak?style=solid
https://fontawesome.com/icons/bacon?style=solid
https://fontawesome.com/icons/turkey?style=solid
https://fontawesome.com/icons/drumstick-bite?style=solid
https://fontawesome.com/icons/drumstick?style=solid
https://fontawesome.com/icons/shish-kebab?style=solid
https://fontawesome.com/icons/brain?style=solid
