### ISSUE TITLE
Icon Request: fa-Hair-GhKh

### ISSUE THREAD

**Issue by LineCenter** [FortAwesome/Font-Awesome#6512]
![layer_12-01-512](https://cloud.githubusercontent.com/assets/12513910/7705228/ad81a35c-fe4b-11e4-87a9-76498e3949ce.png)

**Comment by tagliala** [comment]
sorry, could you please post a single color example suitable for 14px icon size and clarify what GhKh stands for?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
