### ISSUE TITLE
Icon request: icon-inbox (Gmail Inbox)

### ISSUE THREAD

**Issue by Rheisen** [FortAwesome/Font-Awesome#6516]
Not sure if these have been requested, but the closest thing I can find to any of them is an envelope icon for google mail / inbox.

**Comment by tagliala** [comment]
drive: #835 
gmail: #4655

Leaving this open as icon-inbox

**Comment by D4rkTiger** [comment]
The google drive icon is not the same as google mail ? Ok for Inbox and Gmail +1.

**Comment by chegarr** [comment]
+1

**Comment by PAdamB** [comment]
+1

**Comment by chief93** [comment]
+1

**Comment by kohweiteck** [comment]
+1 for GMail

**Comment by pmjcreations** [comment]
Google closed Inbox by Gmail in  March 2019.

https://www.blog.google/products/gmail/inbox-signing-find-your-favorite-features-new-gmail/

This request may be closed now.

**Comment by tagliala** [comment]
@pmjcreations thanks for the heads-up

Closing here
