### ISSUE TITLE
New search query: 'Currency'

### ISSUE THREAD

**Issue by codynguyen1116** [FortAwesome/Font-Awesome#6517]
When searching up 'currency', all the currency symbols / icons should pull up.

**Comment by tagliala** [comment]
there is a category... http://fontawesome.io/icons/#currency

is not that enough?

**Comment by vdanelia** [comment]
Please add Georgian Currency Icon, Thanks

**Comment by tagliala** [comment]
@vdanelia please +1 #3973

**Comment by vdanelia** [comment]
I already voted there ;)

**Comment by tagliala** [comment]
perfect, this request is about something else

**Comment by vdanelia** [comment]
tagliala please add, because many of us have to use other - additional fonts for that symbol..
I'm using FA and would be very delighted to find that symbol in yoyr font...
Thanks

**Comment by tagliala** [comment]
@vdanelia sorry but I can't help. If you need that symbol, you should consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment]
also please do not hijack this thread
