### ISSUE TITLE
Icon Request: fa-cross-death

### ISSUE THREAD

**Issue by sovya** [FortAwesome/Font-Awesome#6518]
Hi - I am in need for a symbol that indicates that a person in a list is deceased. I am thinking a simple cross. I have searched, but not been able to find one in the FontAwesome library, and I was hoping someone out there should be of assistance. Many thanks,
  
  .sov

**Comment by tagliala** [comment]
dup of #1611, please +1 that request

closing here

also consider using te standard unicode point

```css
.fa-cross:before { content: "†"; }
```

**Comment by sovya** [comment]
Ahh, ok, of course :) Thanks.
