### ISSUE TITLE
Icon request: icon-houzz

### ISSUE THREAD

**Issue by billsmithem** [FortAwesome/Font-Awesome#6521]
We'd love a houzz icon included in font awesome (which is already awesome.) would add more awsomeness. Homebuilders, interior decorators and home design and architects all use houzz as their primary social media channel. houzz buttons and badges are located: http://www.houzz.com/buttonsAndBadges

**Comment by tagliala** [comment]
dup of #2039 , please +1 that request

closing here

**Comment by markream** [comment]
+ 1
