### ISSUE TITLE
Icon Request: fa-facebook

### ISSUE THREAD

**Issue by saturndeng** [FortAwesome/Font-Awesome#6523]

**Comment by tagliala** [comment]
there are three versions of the facebook icon :)

http://fontawesome.io/icon/facebook-square/
http://fontawesome.io/icon/facebook/
http://fontawesome.io/icon/facebook-official/

closing here

**Comment by s1xtec** [comment]
review

**Comment by s1xtec** [comment]
Only Facebook-official are working

**Comment by tagliala** [comment]
of course I can't confirm. Maybe this is an adblock-related issue: #1799
