### ISSUE TITLE
Can FontAwesome icons be used in a logo?

### ISSUE THREAD

**Issue by magentapose** [FortAwesome/Font-Awesome#6524]
Can I use a non-brand icon in a logo design?

**Comment by magentapose** [comment]
any idea?

**Comment by tagliala** [comment]
@magentapose sorry I need feedback from dave for this one to be 100% sure.

**Comment by magentapose** [comment]
@tagliala okay, thanks for your help, awaiting the verdict. :)

**Comment by magentapose** [comment]
bump

**Comment by tagliala** [comment]
@magentapose no feedback, maybe aliens got Dave :alien: :)

You could tale a look at the SIL license and try to figure it out by yourself

**Comment by magentapose** [comment]
Hi @tagliala ,

I found this page online: http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=FontFAQ_use

And in one of the comments, the user (Carlos) asks...

"I want to use the fonts for commercial use in logos, brochures, posters, etc.. I will not sell or distribute, or modify fonts."

And the reply from 'martinpk' is:

"Yes, these are all permitted uses. Go ahead and use them in commercial publications. All the best!"

.... So I guess I can use the icons (non-brand icons) in my logo!

Thanks!

**Comment by tagliala** [comment]
@magentapose you're welcome, glad you solved. thanks for asking btw :+1: 

closing here
