### ISSUE TITLE
Icon Request: fa-dong (fa-vnd)

### ISSUE THREAD

**Issue by huuphat** [FortAwesome/Font-Awesome#6526]
Here is the currency of Vietnam: "Dong" or "Đồng" in Vietnamese.
I hope you will add it to Font-Awesome.
fa-dong
Alias: fa-vnd
Symbol: ₫
Usage: 100₫
![image](https://cloud.githubusercontent.com/assets/2727217/7741442/0e562b04-ffa9-11e4-9bfd-c79af2abe5ab.png)

**Comment by philiparthurmoore** [comment]
Huge +1 for this. I very much need it for a lot of the projects I work on.

**Comment by armandino** [comment]
+1

**Comment by sensibleworld** [comment]
This is available as part of the v6 alpha release: https://fontawesome.com/download

**Comment by SherwinVN** [comment]
i not found fa-vnd in FAS? 
Can you help me?

**Comment by sensibleworld** [comment]
It's in our v6 beta: https://fontawesome.com/v6.0/icons/dong-sign?s=solid

**Comment by SherwinVN** [comment]
Thanks you so much!
