### ISSUE TITLE
Icon request: icon-shuffle

### ISSUE THREAD

**Issue by bboerendans** [FortAwesome/Font-Awesome#6528]
Would love to see an extra Video Player Icon. 

Something like this:
![main-qimg-7f0e76488329eb117bc11603eeabb3f9](https://cloud.githubusercontent.com/assets/4182238/7751815/2cebb114-ffdc-11e4-84bc-855afbd82ede.jpg)

**Comment by jarodxxx** [comment]
+1

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/random/

Added to video-player icons and also added a `shuffle` filter, hope this helps

closing here
