### ISSUE TITLE
Icon Request: fa-500px

### ISSUE THREAD

**Issue by techdesignlab** [FortAwesome/Font-Awesome#6530]
Hello!
I would like to add the icon http://500px.com site .
I need it in a project .
I hope to add.

Regards,
Marian Tofoleanu, TechDesignLab

**Comment by JHGitty** [comment]
:-1: -1
This site is not widely used (in comparison with Facebook, Twitter, ..).

**Comment by danielbierstedt** [comment]
I disagree and it's not even important if the site is widely used or not. I use it and I'm missing the icon, too.

**Comment by tagliala** [comment]
duplicate of #599, please +1 that request

500px is a popular request and it was added to 5.0.0 milestone

closing here
