### ISSUE TITLE
Hey FA - Do you need/want help designing more icons?

### ISSUE THREAD

**Issue by kp-rob** [FortAwesome/Font-Awesome#6531]
Hey Font-Awesome gang, 

I use your icons all over my websites, and there are some simple ones that seem to be missing. I'd love to help design new ones. Pro in Illustrator & font creation. Reach out to me if interested, I'd love to help the community grow (and thus, my web icon choices).

**Comment by tagliala** [comment]
@kp-rob thanks for your willing to help! We should hear from @davegandy if he changed his mind about this topic

At the moment it is a design choice to not accept pull requests containing icons

**Comment by kp-rob** [comment]
Hey Geremia,

Thanks for the reply. 

If I can help, I'm interested. I know there are aesthetics and styles to uphold and processes to manage. 

I'm actually interested in being a design contributor, if possible. No pay necessary or anything, as using the icons in a free, open source, lightweight way is all I want to do. I've created dozens of icons that are just sitting in a folder in my computer.  

If it doesn't work out, no problem. Thanks!

--
Rob
