### ISSUE TITLE
Icon request: icon-gitter

### ISSUE THREAD

**Issue by Dobbelsteen** [FortAwesome/Font-Awesome#6535]
Hey, I think it would be awesome to add a Font-Awesome icon for [Gitter](https://gitter.im/).
For those who don't know Gitter, it's a communication network for developers, kind of like an IRC chatroom, but based on Github.

It would be nice to have this icon to be able to link to the Gitter-chatrooms of some of our projects on the project's website (kind of like social media icon branding)

Here are 2 PNG versions of the icon in question:
![gitter2](https://cloud.githubusercontent.com/assets/6047822/7768134/731dfa10-0078-11e5-90b3-e99f55e8ae27.png)
![gitter1](https://cloud.githubusercontent.com/assets/6047822/7768135/732881d8-0078-11e5-8dfb-6f95f4676e4e.png)

Here are links to SVG files of the same icons:
[icon-gitter-square](http://san.rocks/fa/gitter1.svg)
[icon-gitter](http://san.rocks/fa/gitter2.svg)

Kind regards
Dobbelsteen

**Comment by harshavardhana** [comment]
+1

**Comment by tduchateau** [comment]
+1

**Comment by RaghuAllTheTime** [comment]
+1

**Comment by danielwegener** [comment]
+1

**Comment by danieldietrich** [comment]
+1

**Comment by danieldietrich** [comment]
@Dobbelsteen Great idea! The links to the SVG files are outdated/broken. Thx!

**Comment by Frucht** [comment]
+1

**Comment by kcyeu** [comment]
+1

**Comment by philkunz** [comment]
+1

**Comment by Linkaan** [comment]
+1

**Comment by Dobbelsteen** [comment]
@danieldietrich Updated the SVG links, thanks for mentioning it.

**Comment by kcyeu** [comment]
@tagliala: as @Dobbelsteen updated the SVG links, it's time to move on.

**Comment by onlineth** [comment]
+1

**Comment by Soullivaneuh** [comment]
+1

**Comment by RobertDiebels** [comment]
+1

**Comment by KelSolaar** [comment]
That would be great indeed!

+1

**Comment by Luceos** [comment]
+1

**Comment by coni2k** [comment]
+1

**Comment by cube5** [comment]
+1

**Comment by sabgaby** [comment]
+1

**Comment by denysdovhan** [comment]
+1

**Comment by jenssaade** [comment]
+1

**Comment by marceloverdijk** [comment]
+1

**Comment by Tinixi** [comment]
+1

**Comment by mason9msw** [comment]
+1

**Comment by openwms** [comment]
+1

**Comment by DerekTBrown** [comment]
+1

**Comment by jfsagasti** [comment]
+1

**Comment by arun1595** [comment]
+1

**Comment by brainscript** [comment]
+1

**Comment by Joter85** [comment]
+1

**Comment by perak** [comment]
+1

**Comment by louiscklaw** [comment]
+1

**Comment by hamzahik** [comment]
+1

**Comment by gornostal** [comment]
+1

**Comment by jessicaelle** [comment]
+1

**Comment by izhangzhihao** [comment]
+10086

**Comment by zquintana** [comment]
+1

**Comment by amihaiemil** [comment]
+1

**Comment by amihaiemil** [comment]
I managed to add the gitter svg with fontello.com, though it will eat a lot of RAM when you upload the font-awesome svg files. Steps are in this order (do a backup first!):

1) add the font-awesome.svg to custom icons sections
2) in the same section but LAST, add the gitter svg
3) download the webfont zip
4) open the .svg file, search for the gitter glypsh element and copy it in your font-awesome.svg
5) add the class fa-gitter:befre {content:"\[generated_unicode]"} in font-awesome.min.css
6) also in font-awesome.min.css you may have to remove the ?v=... query attribute from the import strings.

**Comment by kuboosoft** [comment]
Hey please add gitter!!!

**Comment by obcode** [comment]
+1

**Comment by myshoeshurt** [comment]
+1

**Comment by geekbrother** [comment]
+1

**Comment by angilent** [comment]
+1

**Comment by KennethanCeyer** [comment]
+1

**Comment by ryanio** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon is available in Font Awesome 5 Free. 🎉

https://fontawesome.com/icons/gitter?style=brands
