### ISSUE TITLE
Icon request: icon-upwork

### ISSUE THREAD

**Issue by jrbedard** [FortAwesome/Font-Awesome#6537]
https://www.upwork.com/ formerly odesk/elance

**Comment by tagliala** [comment]
so #3445 and #4876 are duplicates of this one? Can I "merge" the three requests?

**Comment by Joshuacru** [comment]
+1

**Comment by olehpratsko** [comment]
+1

**Comment by GBarkhatov** [comment]
+1

**Comment by Jordantcarlisle** [comment]
+1

**Comment by Axiom-shuvo** [comment]
+1

**Comment by joyns** [comment]
+1

**Comment by tagliala** [comment]
Please answer my question: https://github.com/FortAwesome/Font-Awesome/issues/6537#issuecomment-105486787

**Comment by olehpratsko** [comment]
Upwork is rebranding of Elance-oDesk. So, yes, you can merge these requests.

**Comment by AnBat** [comment]
+1

**Comment by Blackening999** [comment]
+1

**Comment by islamx** [comment]
+1

**Comment by hmbashar** [comment]
+1

**Comment by WebLead** [comment]
+1

**Comment by kidager** [comment]
+1

**Comment by ummahusla** [comment]
+1

**Comment by benedicksahagun** [comment]
+1

**Comment by UbuntuElphie** [comment]
+1

**Comment by glamfather** [comment]
+1

**Comment by beloglazov91** [comment]
+1

**Comment by Sogl** [comment]
+1

**Comment by rudiaj** [comment]
+1

**Comment by mjt60** [comment]
+1

**Comment by ovr** [comment]
+1

**Comment by InnHunter** [comment]
+1

**Comment by denis-it** [comment]
+1

**Comment by pavelshulaev** [comment]
+1

**Comment by iambipinpaul** [comment]
+1

**Comment by medinpiranej** [comment]
+1

**Comment by mahmudsg** [comment]
+1

**Comment by Sogl** [comment]
@tagliala @davegandy Any changes on this? First oDesk (previous Upwork name) issue dated 1 November 2014!
Maybe we need to reach +1 count goal? :smile:

**Comment by klubov** [comment]
+1

**Comment by tazmon95** [comment]
+1 This has been open for 2 years 

Here is a free version of the Upwork logo in SVG https://www.shareicon.net/upwork-879425

**Comment by evanre** [comment]
+1

**Comment by peixotorms** [comment]
+1

**Comment by thakurpunk** [comment]
+1

**Comment by bocharsky-bw** [comment]
+1

**Comment by Dugnist** [comment]
+1

**Comment by spencerimp** [comment]
+1

**Comment by plumbn** [comment]
+1

**Comment by narnikgamarnikus** [comment]
+1

**Comment by bocharsky-bw** [comment]
Here's the solution :)
https://twitter.com/bocharsky_bw/status/879213785554321408

**Comment by GabbasovDinar** [comment]
+1

**Comment by preese13** [comment]
+1

**Comment by hikmat30ce** [comment]
+1

**Comment by wsierradev** [comment]
+1

**Comment by Shazbot89** [comment]
-1

**Comment by darashkevich** [comment]
+1

**Comment by kocharli** [comment]
+1

**Comment by Sumeet21** [comment]
+1

**Comment by oualidouazrou** [comment]
+1

**Comment by madlobz** [comment]
+1

**Comment by kamuz** [comment]
+1

**Comment by Ancyker** [comment]
+1

**Comment by blueatabey** [comment]
+1

**Comment by Markus872** [comment]
+1 but theyre not doing it

**Comment by arslansarwar** [comment]
+1 Need it

**Comment by andamasov** [comment]
+1

**Comment by ashfahan** [comment]
+1

**Comment by jakkrobbit** [comment]
+1. I was about to add this icon to my site, until I realized it doesn't exist.

**Comment by flamecrow** [comment]
+1

**Comment by Uysim** [comment]
+1

**Comment by andrewlundy** [comment]
+1

**Comment by invshakil** [comment]
+1

**Comment by danieldanielecki** [comment]
+1

**Comment by umershaikh** [comment]
+1

**Comment by Sharl212** [comment]
+1

**Comment by Sharl212** [comment]
not sure if im allowed to type here (if not, please tell me where to move this so people can benefit from it). but i made a temporary solution for the Upwork icon. 
https://codepen.io/sharlsherif/pen/MRXQPG

**Comment by tagliala** [comment]
@Sharl212 feel free to share here all your workarounds

PS: at the moment your solution don't work for me

![image](https://user-images.githubusercontent.com/556268/56468041-15937c00-6427-11e9-8caa-c0d92c1ad917.png)

**Comment by Sharl212** [comment]
![image](https://user-images.githubusercontent.com/29375572/56468496-a2d9cf00-642d-11e9-9f7e-f52c4e5c06e5.png)
the image loads for me, might be a browser thing. im hosting it on imgur here : https://i.imgur.com/TLpZ1jf.png

**Comment by mmcguff** [comment]
![image](https://user-images.githubusercontent.com/10658437/57294921-c5efba00-708e-11e9-9fac-c680648ea0f0.png)

This one looks better.  Include this on also:  https://www.iconfinder.com/icons/1929180/upwork_icon

**Comment by SharlSherif** [comment]
@mmcguff 
it doesn't match the look of other Fontawesome icons which is the main goal for most people. in my example, i had to cut out the white "Up" off the original Upwork logo.

**Comment by RedhatPH8** [comment]
**What can it be used for?**
This request was originally made May 22, 2015. Since it's creation, it has had approximately 80 reactions, but doesn't appear to have had any of the required checklist items. 
Developers and Freelancers using the UpWork platform would be able to more readily display the FontAwesome UpLink character on portfolio sites. 

**Example image (optional)**
Example Images embedded from previous comments

![upwork_icon](https://user-images.githubusercontent.com/20482362/59642556-814a4a80-9133-11e9-9e21-d702e8d19a04.png)

![upwork](https://user-images.githubusercontent.com/20482362/59642552-7b546980-9133-11e9-8723-fa630323d1a5.png)

**Icon request checklist**
- [X] This is a single icon or matched pair (Ex: `lock` / `unlock`)
- [X] The title starts with "Icon request: " and is followed by the requested icon name (Ex: `Icon request: magical-unicorn`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate
- [X] I have included at least one example image if it could be helpful (optional)
- [X] The request is for a concrete object (it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺)

**Comment by aromn** [comment]
Hello everyone, today I was looking for the upwork logo on fontawesome, unfortunately, I could not find it, so I created my own repo where I included the upwork logotype, check it out, and help improving the project if you want. 
I do not know if it is correct to comment here, if not let me know, besides, let me know what is wrong with the project since I am new with git and github, for sure I have many errors.

Check the project, hope it works for you.
https://github.com/aromn/fontchido

**Comment by jnickgo** [comment]
+1

**Comment by jessuppi** [comment]
5 years later, the most popular freelance community online still has no FA icon, srsly folks?

**Comment by chopada** [comment]
+1

**Comment by Cosmiam** [comment]
+1

**Comment by lcsvcn** [comment]
+1

**Comment by vagueLima** [comment]
+1

**Comment by jp9573** [comment]
+1

**Comment by Riadz** [comment]
+1

**Comment by IonDigital** [comment]
+1

**Comment by AtulKumarDTU** [comment]
+1

**Comment by zangrandi** [comment]
+1

**Comment by COBNETCKNN** [comment]
Should be added by now tbh

**Comment by theoctober19th** [comment]
Still waiting for this to be added. Any updates?

**Comment by mrth2** [comment]
Give it a push?

**Comment by apavelm** [comment]
+1

**Comment by vladstarikov88** [comment]
+1

**Comment by Faiizii** [comment]
+1

**Comment by stevenfokoua** [comment]
+1

**Comment by Mauricio-Urrego** [comment]
I took the time to make the svg icon exactly to font-awesome's specs if it is any help on getting this closed soon:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56.7 56.7"><!--! Font Awesome Free 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc. --><path d="M0 0v56.7h56.7V0H0zm20.3 14.6h5.6a48.4 48.4 0 0 0 5.6 12.1c1.6-5.5 5.6-9 10.9-9a11.3 11.3 0 0 1 0 22.5 14 14 0 0 1-7.7-2.2l-2.4 11.9h-5.7l3.5-16.3a51.5 51.5 0 0 1-4-6.7v2.5a10.9 10.9 0 0 1-21.8 0V14.7h5.4v14.6a5.3 5.3 0 1 0 10.6 0V14.6zm22.2 8.8c-4.1 0-5.4 4-5.8 6.4v.1l-.6 2.2a10.2 10.2 0 0 0 6.3 2.5 5.9 5.9 0 0 0 5.7-5.6 5.6 5.6 0 0 0-5.6-5.6z"/></svg>`

It has it all in one path and with the same comment as the other SVGs I've seen. Path has also been cut out of background like @SharlSherif has mentioned it needs.

**Comment by villamga** [comment]
Try this link
https://icon-sets.iconify.design/simple-icons/upwork/

**Comment by GeminiDev1** [comment]
How is this still not included..

**Comment by arfathyahiya** [comment]
Oh man seriously it's still not here I read through this thread just to know it's not yet added......

**Comment by Madhavkabra** [comment]
Add it please

**Comment by sayeemabdullah** [comment]
+1

**Comment by david-mbugua** [comment]
Did anyone manage to get this icon?

**Comment by Markus872** [comment]
please add it

**Comment by sensibleworld** [comment]
Added! https://fontawesome.com/icons/upwork?f=brands&s=solid

**Comment by jessuppi** [comment]
After 8 years of waiting, I'm glad this icon was finally added. However, why is there a box around it, ala styling from a decade ago? I humbly suggest this should be changed, the icon should not have a background square.

It should look like Upwork's mobile icon, e.g.

https://icon-icons.com/id/icon/upwork-logo/170310

**Comment by tagliala** [comment]
I think that the logo has been taken from upwork's brand guidelines:

https://www.upwork.com/about/brand/downloads#symbol
