### ISSUE TITLE
Icon Request: fa-calendar-day, fa-calendar-week

### ISSUE THREAD

**Issue by Yipida-team** [FortAwesome/Font-Awesome#6540]
Icon request: icon-calendar-day
Icon request: icon-calendar-week
Icon request: icon-calendar-month (already available)

simply google "icon day week month" to have an idea. we are trying to show an icon that represents daily/weekly/monthly reports.

**Comment by tagliala** [comment]
dup of #3609 , please +1 that request

closing here
