### ISSUE TITLE
Icon Request: Houzz

### ISSUE THREAD

**Issue by SabrinaBrand** [FortAwesome/Font-Awesome#6548]
Hi,

could you plz add
http://st.houzz.com/static_fr-FR/badge20_20.png
and
http://st.houzz.com/static_fr-FR/badge36_36.png

Tank you,
Sabrina Brand
brand-conception.com

**Comment by tagliala** [comment]
duplicate of #2039 , please +1 that request

closing here

**Comment by markream** [comment]
+ 1 for a houzz icon
