### ISSUE TITLE
Icon Request: fa-bucket-fill

### ISSUE THREAD

**Issue by sylphersurfer** [FortAwesome/Font-Awesome#6550]
As fa-paint-brush exists, I'd like this icon to join the font awesome family for my web appllication.
It's a painting application and I'd like a bucket to represent the fill action as in paint or photoshop.
Example: https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/paint_bucket.png

**Comment by tagliala** [comment]
dup of #3270, please +1 that request

closing here
