### ISSUE TITLE
Icon request: icon-flowchart

### ISSUE THREAD

**Issue by laurenmacam** [FortAwesome/Font-Awesome#6555]
Missing an important chart type as follows:

https://cdn4.iconfinder.com/data/icons/seo-glyph-black/2048/Sitemap-128.png

**Comment by joewhitsitt** [comment]
looks like a duplicate to me: http://fontawesome.io/icon/sitemap/

**Comment by tagliala** [comment]
@joewhitsitt thanks, I missed this request

@laurenmacam does `sitemap` fit your needs?

**Comment by laurenmacam** [comment]
Yes, this is what I need! =D
Sorry, i was looking into chart group.

Thanks
