### ISSUE TITLE
eot url error

### ISSUE THREAD

**Issue by ucavus** [FortAwesome/Font-Awesome#6556]
Noticed that one URL for the EOT type is `../fonts/fontawesome-webfont.eot?#iefix&v=4.3.0`  
Shouldn't it be `../fonts/fontawesome-webfont.eot?v=4.3.0#iefix` so the cache-busting query is utilised?

**Comment by tagliala** [comment]
the proper definition was causing issues

refers to #2345, https://github.com/FortAwesome/Font-Awesome/issues/2324#issuecomment-27739718

hope it helps, closing here

I'm in favour of removing query string at all: #3286
