### ISSUE TITLE
fa class and font smoothing

### ISSUE THREAD

**Issue by widoz** [FortAwesome/Font-Awesome#6557]
The attribute for the .fa class create smoothing even of other elements inside the tag. For example: 

< a href="#" name="at_my_list_print" class="at-btn red fa fa-print">Print List< /a>

This make my text Print List even smooth, I don't know if it is correct or not but I think that would be better to leave to the dev the decision.

I changed it to 

.fa:before {
    -webkit-font-smoothing  : antialiased;
    -moz-osx-font-smoothing : grayscale;
}

**Comment by tagliala** [comment]
Could you please fix the example?

http://jsfiddle.net/tagliala/e9yfxsfj/

**Comment by widoz** [comment]
Here the fix 

http://jsfiddle.net/e9yfxsfj/15/

**Comment by tagliala** [comment]
This is not how fontawesome is supposed to work.

Of course you can use it in this way if you need but you should consider a customization. At the moment we will keep css rules in the `.fa` class

Refers to https://github.com/FortAwesome/Font-Awesome/issues/5082#issuecomment-66043325 #2695 #1729

Closing here, hope it helps.

This may change in the future

**Comment by leoyli** [comment]
I also want to address this in #11670.  Even I use FA as suggested, I also don't expect that FA overwrite the style in `<i class="fa-li fa fa-check-square"></I>`.  Because it should only rule the icon, not anything else.
