### ISSUE TITLE
Trash icons is blurry/ gray

### ISSUE THREAD

**Issue by nathraQ** [FortAwesome/Font-Awesome#6558]
If read a lot of issues and comments about this lately. 
I use font awesome version 4.3.0 with chrome 43.0.x (safari almost the same) on a mac with OSX 10.10.3. I use the fa-trash icon like so `<i class="fa fa-trash"></i>`.

Now here is the problem. When I look at the trash-icon (especially, but in general many icons look blurry) it is cristal sharp on a retina display. On a non-retina display it's getting a little bit unsharp and depending on the window size the trash fills with gray. If i disable `-webkit-font-smoothing`it stops, but the icons now look bulky on the retina display.

Feel free to ask for further information if something is unclear.
I think what would help, but be a hell of work is enabling and disabling smoothing based on the media query. Didn't test this idea but sounds like a way possible solution to me

**Comment by tagliala** [comment]
Hi, some settings changed in 4.3.0 because of #3683

Could you please provide an example? http://jsfiddle.net/tagliala/e9yfxsfj/
