### ISSUE TITLE
Icon request: icon-registered-mark

### ISSUE THREAD

**Issue by ezmana** [FortAwesome/Font-Awesome#6563]
can you add "registered trademark" icon?

text: ®

image preview: https://www.enterprisenation.com/system/images/W1siZiIsIjIwMTMvMTEvMTcvMjMvNTIvMDIvMzI3L3JlZ2lzdGVyZWRfdHJhZGVtYXJrMi5qcGciXV0/registered-trademark2.jpg

**Comment by tagliala** [comment]
duplicate of #3276, please +1 that request

closing here
