### ISSUE TITLE
icon-request: speakerdeck

### ISSUE THREAD

**Issue by tugberkugurlu** [FortAwesome/Font-Awesome#6568]
https://speakerdeck.com/

**Comment by quarterback** [comment]
+1

**Comment by FerPerales** [comment]
:+1:

**Comment by gatespace** [comment]
+1

**Comment by vg** [comment]
+1

**Comment by stkent** [comment]
Dupe of https://github.com/FortAwesome/Font-Awesome/issues/1688?

**Comment by nmicht** [comment]
There is already an issue opened for this since 2013
https://github.com/FortAwesome/Font-Awesome/issues/1688

**Comment by tagliala** [comment]
@nmicht thanks

Let's use #1688
