### ISSUE TITLE
Icon Request sailing- and/or motorboat, yacht

### ISSUE THREAD

**Issue by yachtmakler** [FortAwesome/Font-Awesome#6569]
For a new project I need icons for a yacht club. Like Sailing Boat, Motor Boat aso.
![9751347d-1507-429b-92f6-665980fe7ffb](https://cloud.githubusercontent.com/assets/12271392/7836314/92d1c12e-047f-11e5-8598-26a6f93812b6.jpg)
or
![9f5b9e99-3903-4601-bd19-79857c8d0cb9](https://cloud.githubusercontent.com/assets/12271392/7836326/a68b3218-047f-11e5-929d-92c6e96e9abb.jpg)

I hope you can realize it. Thank you.

**Comment by tagliala** [comment]
could you please spilt this request in individual requests, with only one example and a proper title?

thanks!

btw we have a ship: http://fontawesome.io/icon/ship/
