### ISSUE TITLE
Icon Request: fa-factory, fa-contract, fa-compare

### ISSUE THREAD

**Issue by athirah30** [FortAwesome/Font-Awesome#6575]
Hi, can you help me to create 3 icons something like these:

![factory-plant](https://cloud.githubusercontent.com/assets/12637982/7856466/e4ffe0f2-055b-11e5-99ad-f0434f70860c.png)
![searching35](https://cloud.githubusercontent.com/assets/12637982/7856471/f144468c-055b-11e5-8558-a75847274e70.png)
![sign20](https://cloud.githubusercontent.com/assets/12637982/7856472/f14dacb8-055b-11e5-8fa3-75652d7684a3.png)

Really appreciate if you can help me with this

Thank You!

**Comment by tagliala** [comment]
factory: #1689 , please +1 that request
please split the other two requests in files-search-o (compare) and file-edit (contract)
you can use this request for one of the two

Refers to #1181 

you may also be interested in +1: #5663

**Comment by cema93** [comment]
-1

**Comment by syamsulalam** [comment]
somebody should really working on these work related icon asap. :D i'd be so happy i'd eat my cereal.........

**Comment by tagliala** [comment]
No feedback, closing here
