### ISSUE TITLE
Placeholders are randomly shown instead of icons (Firefox, Chrome, IE8)

### ISSUE THREAD

**Issue by afriC84** [FortAwesome/Font-Awesome#6585]
Hi everybody. I know webfonts are a tricky thing. My problem is: I visited the Font Awesome site with Firefox, Chrome and IE8 and all the icons were replaced by placeholders. Right now and weeks before my test it works perfectly fine.
What do you think? What can be responsible for that behaviour? 

I first thought about browser configuration, but that does not seem to be the point, because the issue comes up randomly.

I thought about some proxy or firewall magic, but our infrastructure told me there is no problem.

When my test failed, it did not only on one machine with three browsers... it also failed on my private laptop (but over the company's wlan).

Any ideas? Thanks in advance! Regards!

**Comment by afriC84** [comment]
Wow... same error right now... IE8 randomly displays the fonts, but shows placeholders after a refresh, or it does not show them right from the beginning (clearing the cache does not change anything).

The IE throws the following errors (I translate it from german and hope to find the right words):
```
Identifier, string or number expected
site.js: line 5, char 7
Code: 0
URI: http://fortawesome.github.io/Font-Awesome/assets/js/site.js
```

Original with some other errors: 
```
Details zum Fehler auf der Webseite

Benutzer-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Zeitstempel: Fri, 29 May 2015 09:50:55 UTC

Meldung: Bezeichner, Zeichenfolge oder Zahl erwartet
Zeile: 5
Zeichen: 7
Code: 0
URI: http://fortawesome.github.io/Font-Awesome/assets/js/site.js

Meldung: Script error
Zeile: 0
Zeichen: 0
Code: 0
URI: https://load.sumome.com/

Meldung: Script error
Zeile: 0
Zeichen: 0
Code: 0
URI: https://load.sumome.com/

Meldung: Script error
Zeile: 0
Zeichen: 0
Code: 0
URI: https://load.sumome.com/
```

Hope someone has an answer...
Regards!

**Comment by afriC84** [comment]
One more thing: I have just downloaded the current version of Font Awesome and setup an html file with one single icon that is served via XAMPP on my windows machine. It looks great on Chrome and Firefox.

**But when I open localhost/font-test on the virtual machine in IE8, it works only _randomly_.**
Each time I hit F5 the icon either shows up few times in a row or it does not.

**Comment by tagliala** [comment]
IE8 has random issues we can't fix: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#internet-explorer-8-caveats

**Comment by afriC84** [comment]
Okay, sad but IE8 should not exist anymore anyway ;-) Thank you!
