### ISSUE TITLE
Icon request: icon-vr (for Google Cardboard and other VR enabled content and apps)

### ISSUE THREAD

**Issue by PixelPartner** [FortAwesome/Font-Awesome#6590]
To mark VR (virtual reality) enabled apps and WebVR enabled web sites and Cordova Apps it would be helpfull to use an icon with the catchy Google Cardboard logo but with a more general name
https://developers.google.com/cardboard/
i.e. /site-assets/logo-cardboard-white.svg

**Comment by davidneat** [comment]
+1

**Comment by AndrewHazelden** [comment]
+1

**Comment by markmooibroek** [comment]
+1

**Comment by adamsar** [comment]
+1

**Comment by RogueSheep-nl** [comment]
+1

**Comment by pseudozach** [comment]
+1

**Comment by Sneagan** [comment]
Anything clearly a headset would work. If there's some copyright issue with using something that looks too close to a Google Cardboard we could use something more generic, though I admit that it's hard to get more generic than the cardboard icon. ;)

**Comment by b0bbyriggs** [comment]
+1

**Comment by developius** [comment]
+1

**Comment by syumai** [comment]
+1

**Comment by SamRohn** [comment]
+1

**Comment by sgenzer** [comment]
+1

**Comment by jazzyjester** [comment]
+1

**Comment by jasonrgd** [comment]
+1

**Comment by umbreak** [comment]
+1

**Comment by georgereason** [comment]
+1

**Comment by blq** [comment]
+1

**Comment by Youkho** [comment]
+1

**Comment by rafaeleiki** [comment]
+1

**Comment by otaviowillow** [comment]
+1

**Comment by kldoon** [comment]
+1

**Comment by teleyinex** [comment]
+1

**Comment by Patrick-Wheeler** [comment]
+1

**Comment by bknill** [comment]
+1

**Comment by dbradleyfl** [comment]
+1

**Comment by lin00** [comment]
+1

**Comment by robmerki** [comment]
+ 1

**Comment by babysharny** [comment]
+1

**Comment by JordanMajd** [comment]
+1

**Comment by BitcoinSolution** [comment]
+1

**Comment by costellos2010** [comment]
+1. This really needs to be a thing.

**Comment by SNeilson** [comment]
+1

**Comment by bjorn-ali-goransson** [comment]
Don't forget that simple logos of real trademarks are sometimes public domain, like the [Microsoft logo](https://commons.wikimedia.org/wiki/File:Microsoft_logo.svg). But I like a-frame's icon more, like here: https://aframe.io/examples/showcase/helloworld/

Already in SVG format ...

**Comment by AnnelVenter** [comment]
+1

**Comment by ccharlton** [comment]
+1

**Comment by calvintps** [comment]
+1

**Comment by simonevitale** [comment]
+1

**Comment by tagliala** [comment]
Let's use this for a generic VR icon (examples would be appreciated), please 👍 #9785  for Google Cardboard

**Comment by NicklasBenRasmussen** [comment]
+1

**Comment by inthesauce** [comment]
+1 

In the meantime, I am using fa-simplybuilt [&#xf215;] 
Just flipped vertically  :)

**Comment by arapl3y** [comment]
+1

**Comment by slmnm** [comment]
+1

**Comment by jordonrupp** [comment]
+1

**Comment by tadasstra** [comment]
+1

**Comment by ccharlton** [comment]
Virtual +1 :)

**Comment by garynobles** [comment]
I'm looking for this kind of icon for a university project, very much needed for academia as well as for more generic VR +1

**Comment by hperrin** [comment]
+1

**Comment by bhalial** [comment]
+1

**Comment by gamereat** [comment]
+1

**Comment by tgunz** [comment]
For what it's worth, rotating the simply built icon 180deg works pretty well:
http://fontawesome.io/icon/simplybuilt/

**Comment by sabinedijt** [comment]
+1

**Comment by aph-vsn** [comment]
+1

**Comment by HAZARDU5** [comment]
This would be really useful! I'm prototyping a bunch of WebVR demos using font-awesome / bootstrap for 2D UI so having an icon like this bundled in would be great :-) 👍

**Comment by MikelArnaiz** [comment]
+1 for a generic VR headset

**Comment by SamRohn** [comment]
+1 for google cardboard VR icon

**Comment by ableslayer** [comment]
+1 for google cardboard VR icon

**Comment by Bagmaz** [comment]
+1

**Comment by hhassan1230** [comment]
+1 for Oculus/GearVR, HTC Vive & Google Cardboard/Daydream

**Comment by Disorrder** [comment]
+1 for webvr

**Comment by Candie** [comment]
+1 for generic one maybe with VR in the middle.

**Comment by dbodesign** [comment]
It's not the best alternative, but...: http://fontawesome.io/icon/simplybuilt/

**Comment by ebuntario** [comment]
+1 but is there any progress on this? this ticket has been open for some time now.

**Comment by m4d3** [comment]
+1

**Comment by modusops** [comment]
+1

**Comment by ccharlton** [comment]
In the meantime, I feel like this guy: http://fontawesome.io/icon/grav/

**Comment by elipeters** [comment]
+1

**Comment by satopy** [comment]
+1

**Comment by Itee** [comment]
+1

**Comment by tamasturcsanyi** [comment]
+1

**Comment by Hunter-Bobeck** [comment]
+1

**Comment by jochemstoel** [comment]
+1
Cardboard / VR icon very much appreciated. 
![cardboard](http://kamerawerk.at/kamerawerk/wp-content/uploads/CardboardIcon-Kopie.png)

**Comment by adamhhhh** [comment]
+1

**Comment by jfarmersp** [comment]
+1

**Comment by alystair** [comment]
I hope that we are able to have a more generic, universally identifiable icon for VR, I'm currently using the "cube" icon to represent 3D-ness. Thanks @sensibleworld :)

**Comment by ajmaurya99** [comment]
+1

I am looking for an AR and VR icon

**Comment by come2thecabaret** [comment]
+1

**Comment by ccharlton** [comment]
Is this now a dupe of https://github.com/FortAwesome/Font-Awesome/issues/772 ?

**Comment by ccharlton** [comment]
+1000

**Comment by equinox2k** [comment]
Maybe a icon representing to enter vr and one to exit vr

**Comment by sensibleworld** [comment]
This was added in 5.4: https://fontawesome.com/icons/vr-cardboard?style=solid (along with an alternate version: https://fontawesome.com/icons/head-vr?style=solid)

It's currently available in Font Awesome Pro, but will be added to Free in the next release. (Meant to do so in this release, but it slipped through the cracks).

**Comment by equinox2k** [comment]
@sensibleworld would be great to add to alternate version where the headset is off or being raised up to represent exiting vr

**Comment by sensibleworld** [comment]
@equinox2k We've also added a `head-side` icon the matches the `head-vr` icon: https://fontawesome.com/icons/head-side?style=solid
