### ISSUE TITLE
Icon Request: fa-teamviewer

### ISSUE THREAD

**Issue by Brilbroeder** [FortAwesome/Font-Awesome#6593]
An icon representing a flat version of the teamviewer logo.

https://www.teamviewer.com/

**Comment by iuwan** [comment]
+1, that would be awesome!

**Comment by tagliala** [comment]
duplicate of ##5383, please +1 that request

closing here

**Comment by mennows** [comment]
+1

**Comment by meggink** [comment]
+1 That would be awesome

**Comment by tagliala** [comment]
locking, this is a duplicate
