### ISSUE TITLE
Icon Request: fa-ravelry

### ISSUE THREAD

**Issue by mstmarie1** [FortAwesome/Font-Awesome#6597]
Social media site for the Knitting and Crochet community. Should be helpful for anyone building a website for a store that sell yarn, knitting classes and hosts events having to do with knitting.
![ravelry-logo-81r-300x](https://cloud.githubusercontent.com/assets/12664310/7891434/388126a8-0612-11e5-8b77-4b3efc7a5664.png)

**Comment by tagliala** [comment]
ravelry is a dup of #3314, please +1 that request

closing here
