### ISSUE TITLE
Icon request: icon customer & icon managment & icon supervisors :)

### ISSUE THREAD

**Issue by fhedayat** [FortAwesome/Font-Awesome#6600]
hi
thanks for your good job
my suggestion is to add this icons
management &
customer & 
supervisors .
:)
![test](https://cloud.githubusercontent.com/assets/6542982/7897124/d35a5a72-06e5-11e5-82cf-b5d9c67ca346.png)

**Comment by tagliala** [comment]
management is a dup of #3397, please +1 that request

please split the other request in two individual request with a proper title (customer is abstract, user-inside-shop is better) . supervisor is abstract too but I don't have a suggestion

You can edit this one

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
