### ISSUE TITLE
Icon Request: fa-letter W (Capital for Wholesale) & R (Capital for Retail) 

### ISSUE THREAD

**Issue by import-man44** [FortAwesome/Font-Awesome#6604]
I plan to use it to letter Wholesale or retail customer know where to sign in at.

**Comment by tagliala** [comment]
hmmm. I do not know how to deal with this request

It would open to all the alphabet letters, both uppercase and downcase.

I'm going to consider this as a subset of #5019, but I think that you should consider a custom css solution, that's very easy: http://jsfiddle.net/tagliala/77re29ct/24/

Closing here
