### ISSUE TITLE
Icon request : fa-washing-machine

### ISSUE THREAD

**Issue by bencagri** [FortAwesome/Font-Awesome#6605]
Everything is ok but those three...

![autocaravanas_servicios-01](https://cloud.githubusercontent.com/assets/823521/7902373/a78dc1a0-07c0-11e5-855b-eef5235bdc3b.jpg)

**Comment by tagliala** [comment]
shower/bath is a duplicate of #708 

wc is a duplicate of #2670 

leaving this open as washing-machine

**Comment by tagliala** [comment]
nope :grin: 

washing machine is a dup of #5914, please +1 that request

all dups, closing here

**Comment by alexptbg** [comment]
+1
