### ISSUE TITLE
Some Icon not show up with FontAwesome 4.3.0

### ISSUE THREAD

**Issue by semplon** [FortAwesome/Font-Awesome#6608]
I got error showing two icon with FontAwesome 4.3.0 from http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css 

the style sheet is exist but the icon is not showing. 
![image](https://cloud.githubusercontent.com/assets/3163608/7906049/a52d08a2-084d-11e5-992e-9506013cc5a8.png)

the icons are 
![image](https://cloud.githubusercontent.com/assets/3163608/7906060/bf504ed8-084d-11e5-9375-4b75ff6cd4eb.png)

It work fine on Firefox 38.1

I'm using Chrome 43.0.2357.81 m
This is the error at the chrome console. 
![image](https://cloud.githubusercontent.com/assets/3163608/7907376/d1aa8f5c-0862-11e5-99ec-26240e05141e.png)

I'm curious it's just mine or others had similar problem with me ?

**Comment by tagliala** [comment]
Please follow our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Pay attention to point 4

closing here but feel free to comment
