### ISSUE TITLE
downloadable font: rejected by sanitizer - In Firefox Browser

### ISSUE THREAD

**Issue by sankukatti** [FortAwesome/Font-Awesome#6610]
downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: http://doorda.io/fonts/fontawesome-webfont.woff2?v=4.3.0

**Comment by tagliala** [comment]
This webpage is not available

ERR_NAME_NOT_RESOLVED

Could you also please be more specific on this bug?

**Comment by Liondance** [comment]
Geremia,
I see this is old and likely well understood by many.
I am studying these other links to figure out my best option:

FortAwesome/Font-Awesome#8078
https://support.mozilla.org/en-US/questions/913498
https://stackoverflow.com/questions/57835543/how-to-fix-downloadable-font-rejected-by-sanitizer

**Comment by tagliala** [comment]
@Liondance I'm going to close here. Feel free to open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)

Please provide detailed information about how fonts are used. I think this is related to CSS and self-hosting fonts.

Please also provide details of the host server
