### ISSUE TITLE
Icon Request: fa-etsy

### ISSUE THREAD

**Issue by RobineSavert** [FortAwesome/Font-Awesome#6611]
I would love to see an Etsy icon added to the Font Awesome library, since many webshops also have Etsy account :)

![etsy-icon](https://cloud.githubusercontent.com/assets/9988362/7913142/9b685018-086d-11e5-8fdb-d6e8e9a5c688.png)
![31-etsy-logo](https://cloud.githubusercontent.com/assets/9988362/7913141/9b2a25e0-086d-11e5-8272-994deb45d027.png)

**Comment by tagliala** [comment]
dup of #1962 , please +1 that request

closing here
