### ISSUE TITLE
Icon Request: fa-angle-measurement

### ISSUE THREAD

**Issue by richterdennis** [FortAwesome/Font-Awesome#6612]
e. g. rotate objects

**Comment by tagliala** [comment]
any example?

**Comment by tagliala** [comment]
http://fontawesome.io/icon/undo/ and http://fontawesome.io/icon/repeat/ should fit your needs. I'm going to close this one. Please provide an example and a use case if you need another icon

**Comment by Denni007** [comment]
Undo and repeat are used for undo and redo actions. Simple square with an round arrow underneath are nice or an angle symbol or so

**Comment by tagliala** [comment]
could you please provide an example so I can adjust the title?

**Comment by Denni007** [comment]
Tomorrow, ok?

**Comment by tagliala** [comment]
yes, sure!

**Comment by Denni007** [comment]
I mean something like this:
https://www.iconfinder.com/icons/429560/acute_angle_arris_geometry_icon#size=512

or this:
https://www.iconfinder.com/icons/356750/angle_measurement_icon#size=256

**Comment by tagliala** [comment]
Reopening as `angle-measurement`

**Comment by styler2go** [comment]
+1

**Comment by sensibleworld** [comment]
We now have this icon: https://fontawesome.com/icons/angle?s=solid
