### ISSUE TITLE
Icon Request: fa-iframe

### ISSUE THREAD

**Issue by Denni007** [FortAwesome/Font-Awesome#6615]
To show an iframe or external webpage

**Comment by tagliala** [comment]
any example?

**Comment by Denni007** [comment]
Something like 
![icon-iframe](https://cloud.githubusercontent.com/assets/6861243/7929963/1b779ade-0904-11e5-8174-1b1f7cb1d2d9.png)

**Comment by Denni007** [comment]
https://www.iconfinder.com/icons/413478/webpage_icon#size=512

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
so this is a duplicate of #3585, please +1 that request

closing here
