### ISSUE TITLE
Icon Request: icon-kendama and icon-kendamastripe

### ISSUE THREAD

**Issue by flowkendamasbo** [FortAwesome/Font-Awesome#6616]
We are a US based business that manufacturers and sells kendamas. The most immediate use for the icon would be on our website. flowkendamas.com has a number of places that we could use the icon to integrate the product image into our web marketing. Here is an image of what a kendama is. We would like one solid icon, and one with a horizontal stripe through the ball as shown in the second picture. Kendamas have become a very big business worldwide. I'm sure there are a number of businesses that could use this icon. Thanks for your consideration.

![kendama-natural](https://cloud.githubusercontent.com/assets/12699172/7917326/c9c6568e-0846-11e5-9cab-dc49caa1e7d6.jpg)

![kendama stripe](https://cloud.githubusercontent.com/assets/12699172/7917369/18673574-0847-11e5-87fc-e5c69b1a41b7.jpg)

**Comment by lampside** [comment]
Ah so that's what those things are called. I love them. I too think it'd be a nice icon. It'd be cool to have one at an angle that looks like the ball is in mid-air about to land in one of the cup things on the side.

**Comment by flowkendamasbo** [comment]
Great idea @lampside. We could call it icon-kendamaplay. Make sure to like/star/whatever this issue so we can get it pushed through. Thanks.

**Comment by lampside** [comment]
@flowkendamasbo How do I do that? I see where I can star the FA project, but not this issue in particular. (I'm actually kindof a github noob when it comes to being outside of my own projects).

**Comment by flowkendamasbo** [comment]
Not sure. I'm a Font Awesome and Github Noob as well. I thought I had seen
something on font awesome's site that said you can vote up their issues to
get them pushed through faster. Maybe I read it wrong. No worries. Thanks
though.

**Comment by aethior** [comment]
@tagliala `gaming (category)` label for this request?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
