### ISSUE TITLE
Icon Request: fa-webpage

### ISSUE THREAD

**Issue by lampside** [FortAwesome/Font-Awesome#6617]
I'd really like to have a simple icon that looks something like <a href="http://michelemazzucco.it/img/icon/svg/web-design.svg">this one</a>. It's supposed to represent a browser window with caption buttons on the left (just three boxes to represent X, minimize, and maximize) and then a rudimentary content layout (a box and a few lines of text).

It'd be very useful for a lot of purposes, but the purpose I'd use it for specifically would be to represent my capabilities as a web designer on my website. So I'd have this, but also your mobile phone icon for app development, etc., etc.

**Comment by Denni007** [comment]
:+1:

https://github.com/FortAwesome/Font-Awesome/issues/6615
Your icon example is nicer

**Comment by lampside** [comment]
Ah, glad to see something like this has already been requested. I should note that I didn't create the icon, but I found it. <a href="http://michelemazzucco.it/">Michele Mazzucco</a> created it.

Thanks for your response, @Denni007 !

**Comment by tagliala** [comment]
The example is not available anymore, anyway a browser icon is available in FA5 Pro
https://fontawesome.com/icons/browser?style=solid
