### ISSUE TITLE
user-plus is broken in Firefox

### ISSUE THREAD

**Issue by RoSk0** [FortAwesome/Font-Awesome#6628]
On FF 38.0 Ubuntu, including latest FF dev version 40.0a2 (2015-06-02).
Also checked on windows.
Chrome doesn't have any issues on both platforms.
IE 8 works fine.

**Comment by tagliala** [comment]
does this happen on http://fontawesome.io/ ?

**Comment by RoSk0** [comment]
No, it displays correctly.
Can you help in troubleshooting this?

**Comment by tagliala** [comment]
Sure, it should be point 4 here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting but please take a look at other points as well

**Comment by RoSk0** [comment]
@tagliala Thanks!
Indeed I had an old version installed.
