### ISSUE TITLE
icon-request: emergency exit (aka international Running Man symbol)

### ISSUE THREAD

**Issue by iandoug** [FortAwesome/Font-Awesome#6630]
Hi
This is NOT a sports logo of a running man .. it's the international emergency exit version, as attached.
![publicinformationsymbol_emergencyexit svg](https://cloud.githubusercontent.com/assets/12673886/7944670/71f7b8ae-096c-11e5-9804-e55d08a732f9.png)

I did find a wingding font (travesia tfb) with it in, but it's mapped to the letter b and that does not play nice with Firefox.
thanks :-)

**Comment by kwendenarmo** [comment]
+1

**Comment by tagliala** [comment]
dup of #4785, please +1 that request

the example in #4785 is oddly horizontally flipped. What is the standard?

**Comment by iandoug** [comment]
On Wednesday 03 June 2015 13:52:51 Geremia Taglialatela wrote:

> dup of #4785, please +1 that request
> 
> the example in #4785 is oddly horizontally flipped. What is the standard?

The sample I provided comes from Wikipedia and is correct.

Thanks, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273
