### ISSUE TITLE
Icon Request: video

### ISSUE THREAD

**Issue by polinac** [FortAwesome/Font-Awesome#6632]
![capture](https://cloud.githubusercontent.com/assets/12117128/7948257/75a38f94-0937-11e5-992f-d4278c3979c6.PNG)

Thank you!!!

**Comment by tagliala** [comment]
already here:

http://fontawesome.io/icon/play-circle-o/
http://fontawesome.io/icon/play-circle/
http://fontawesome.io/icon/youtube-play/

**Comment by polinac** [comment]
Thank you very much!!!



Polina



*From:* Geremia Taglialatela [mailto:notifications@github.com]
*Sent:* Sunday, June 7, 2015 5:31 AM
*To:* FortAwesome/Font-Awesome
*Cc:* polinac
*Subject:* Re: [Font-Awesome] Icon Request: video (#6632)



already here:

http://fontawesome.io/icon/play-circle-o/
http://fontawesome.io/icon/play-circle/
http://fontawesome.io/icon/youtube-play/

—
Reply to this email directly or view it on GitHub
<https://github.com/FortAwesome/Font-Awesome/issues/6632#issuecomment-109747719>
.
