### ISSUE TITLE
Icon Request: fa-productHunt

### ISSUE THREAD

**Issue by SwarnaKishore** [FortAwesome/Font-Awesome#6633]
I would like to add my productHunt profile to my portfolio website. It would be great, if there is an icon representing the productHunt.

Here is my productHunt profile - http://www.producthunt.com/@swarnakishoree

Thank you.

![product-hunt-logo-orange-240](https://cloud.githubusercontent.com/assets/7230788/7948464/c2422376-0949-11e5-9b9a-e16995d65221.jpg)

**Comment by tagliala** [comment]
duplicate of #4502, please +1 that request

closing here
