### ISSUE TITLE
Icon Request: fa-financial-recovery

### ISSUE THREAD

**Issue by EddieFromFA** [FortAwesome/Font-Awesome#6636]
An icon to be shown as an attribute of a record related to financial recovery. Please see a sample image below:

![recoverysample](https://cloud.githubusercontent.com/assets/12718588/7949827/12eeffb8-0947-11e5-9bf8-523e0868f226.PNG)

**Comment by tagliala** [comment]
The stack feature does not play well in this case: http://jsfiddle.net/tagliala/e9yfxsfj/18/

I'm going to rename to `financial-recovery` 

This request is legid but I should advise you to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by EddieFromFA** [comment]
Hi, I'm new to this and thank you for your help! 

The icon you shared in http://jsfiddle.net/tagliala/e9yfxsfj/18/ looks pretty good already, But I'll try the custom build option as you suggested. The renaming makes perfect sense as well.

Question: Will a stacked icon still retain the normal functionalities (i.e. color/size change) when you hover the icon?

Thanks!

**Comment by tagliala** [comment]
You're welcome. Yes, it does: http://jsfiddle.net/tagliala/e9yfxsfj/19/

**Comment by EddieFromFA** [comment]
Perfect, thanks!
