### ISSUE TITLE
Doesn't play nice with bower, fonts folder not deployed

### ISSUE THREAD

**Issue by ffxsam** [FortAwesome/Font-Awesome#6637]
When installing via bower, the Gruntfile.js is not modified in a way that publishes the font folder when doing a `grunt` (build to "dist" folder).

**Comment by tagliala** [comment]
Any suggestion on how to fix?

**Comment by ffxsam** [comment]
Not currently. I'll mess around a bit when I get some spare time and if I come up with a fix, I'll do a PR. Feel free to close this ticket.

**Comment by tagliala** [comment]
let's leave this open for tracking purposes

**Comment by ffxsam** [comment]
OK. I'll post again here when I have something solid.

**Comment by tagliala** [comment]
We dropped bower support in Font Awesome 5, closing here
