### ISSUE TITLE
Icon request: icon-atom

### ISSUE THREAD

**Issue by briancwelch** [FortAwesome/Font-Awesome#664]
I would love an atom icon, and possibly other science related icons as well.  I feel it would fit in real well with already in-place icons such as the beaker, etc. :)

**Comment by A1fus** [comment]
+1

**Comment by phumphries83** [comment]
+1

**Comment by duetosymmetry** [comment]
Bump

**Comment by rightfold** [comment]
+1

**Comment by chilblane** [comment]
+1

**Comment by Jayin** [comment]
+1

**Comment by gibsjose** [comment]
+1

**Comment by herrherrmann** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by jjgleim** [comment]
+1

**Comment by AndreLGava** [comment]
+1

**Comment by zingale** [comment]
+1

**Comment by cebecifaruk** [comment]
+1

**Comment by damienwebdev** [comment]
+1

**Comment by tmo256** [comment]
+1

And/or a molecule, something of this nature

![stock-vector-molecule-icon-isolated-on-white-background-188540507](https://cloud.githubusercontent.com/assets/174757/15151085/c42544cc-169d-11e6-8558-2fb9238caa72.jpg)

**Comment by luickdav** [comment]
+1

**Comment by ranesr** [comment]
+1

**Comment by magamine** [comment]
+1

**Comment by stefanoborini** [comment]
+1

**Comment by stefanoborini** [comment]
@tmo256 I think that molecule should be a water ball-and-stick. It's a recognisable molecule by pretty much everybody, and it's very simple.

**Comment by jpdavy** [comment]
+1

**Comment by draevin** [comment]
+1 

As a side note:
@stefanoborini I'm not sure that a ball-and-stick model of a water molecule would be best, as it looks incredibly similar to the sharing icon used in Google's Material design language and various other mobile apps. A discussion has also already been held on the idea of a molecule in #5190

**Comment by KostasKrv** [comment]
+1

**Comment by stefanoborini** [comment]
@draevin very true, but not many other molecules are easy to recognise. caffeine is too complex. ethanol can be confused for a dog. All that's left is benzene. Easy to recognise, provided that it's not ball and stick (it could be thought as a polygon selection/draw)

**Comment by s3nsitivity** [comment]
+1

**Comment by shukryz** [comment]
+1

**Comment by cbalotescu** [comment]
+1

**Comment by trenta3** [comment]
+1

**Comment by briancwelch** [comment]
5 years after my request, I'm going to have to imagine this will never get added.

**Comment by tagliala** [comment]
@briancwelch sorry.

Since this request has 12 👍, 31 💬 , several duplicates and there is still the need of an atom icon (see req #12646), I will reopen this.

Please unsubscribe if you don't want notifications.

If you are not ok with my decision, please close again and I will find another solution

**Comment by PCJinUY** [comment]
Thank You!

**Comment by ajainphysx** [comment]
+1

**Comment by javierluz** [comment]
+1
