### ISSUE TITLE
fa-wordpress does not show in firefox

### ISSUE THREAD

**Issue by NetanelBasal** [FortAwesome/Font-Awesome#6640]
I am using Font Awesome 4.3.0 and firefox 38 and all the others icons are showing but the icon fa-wordpress is not showing, what is wrong?

**Comment by tagliala** [comment]
Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by tagliala** [comment]
Closing here, but feel free to comment
