### ISSUE TITLE
New icon: unicode Escape symbol

### ISSUE THREAD

**Issue by iandoug** [FortAwesome/Font-Awesome#6641]
Hi
Can you please add unicode Esc symbol, the ones in fonts don't play nice.
The one here is nice: http://www.dafont.com/forum/read/11587/esc-logo-font
Others in fonts: http://www.fontspace.com/unicode/char/238B
thanks :-)

**Comment by jasonhibbs** [comment]
It may be useful to consider the set as usage of arrows in and out of circles appears to be on the up. Arrow in circle can mean "now", arrows in inward or outward can also mean inbound or outbound, import or export. I’m looking for an icon similar to _escape_, but pointing to the right.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/arrow-up-left-from-circle?f=classic&s=solid

**Comment by iandoug** [comment]
Thanks :-)
