### ISSUE TITLE
Icon request: icon-diving

### ISSUE THREAD

**Issue by Dupindupin** [FortAwesome/Font-Awesome#6644]
Icon request: icon-diving_silhouett 
![diving_silhouette_64](https://cloud.githubusercontent.com/assets/12727135/7955356/636aba1a-09e0-11e5-93f3-9f07ec95028d.png)

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by repat** [comment]
+1

**Comment by nj167252** [comment]
+1

Something like the NCAA diving logo would be great
![untitled_1](https://user-images.githubusercontent.com/16868815/48414432-65bd3280-e753-11e8-969d-27fadd901130.jpg)

**Comment by repat** [comment]
Is this not a request for _scuba_ diving?

**Comment by nj167252** [comment]
Oh, sorry about that. Thanks for pointing that out @repat

**Comment by sebastian-estudiob** [comment]
+1

**Comment by sebastian-estudiob** [comment]
![captura de pantalla 2018-12-18 a la s 13 43 14](https://user-images.githubusercontent.com/14235651/50168780-f9da6680-02ca-11e9-9dcb-95056e9bcf15.png)


like this.

**Comment by Dupindupin** [comment]
Yes very nice

**Comment by aethior** [comment]
Duplicate of #6448.

cc/ @tagliala

**Comment by tagliala** [comment]
Let's use #6448. It has more upvotes. Will change the title by adding synonyms
