### ISSUE TITLE
Icon Request: fa-online

### ISSUE THREAD

**Issue by TypischJelle** [FortAwesome/Font-Awesome#6647]
Make something that preview's someone is online

**Comment by tagliala** [comment]
any example?

**Comment by tagliala** [comment]
dup of #1386, please +1 that request

closing here

**Comment by vardars** [comment]
maybe use http://fortawesome.github.io/Font-Awesome/icon/circle/ with green color. just an oppinion. color is more important for that purpose imho.

**Comment by xitude** [comment]
I agree with @vardars color would be preferred with a circle over a "online icon"

**Comment by sebie** [comment]
Couldn't you just set a color for the class / div using CSS?

Like TravisCI does?

![http://puu.sh/iy9yt/3af7d02651.png](Travis Status)

**Comment by tagliala** [comment]
I'm going to close this one

**Comment by sebie** [comment]
Thanks @tagliala .
