### ISSUE TITLE
Icon request: bread

### ISSUE THREAD

**Issue by lbruschi** [FortAwesome/Font-Awesome#6648]
Hi,
I'm a new user so please forget my error :-)
I'm developing a site for an organic bakery and i'm looking for an icon 'bread' . I would use it for the "product" page. 
Here attached two examples.

Thanks in advance!
BR
Laura

![breadjpg](https://cloud.githubusercontent.com/assets/12730925/7959872/b57390fe-09fc-11e5-845e-b11e5d71f0f8.jpg)
![bread](https://cloud.githubusercontent.com/assets/12730925/7959874/b828308e-09fc-11e5-97ae-ee06ecda2f00.png)

**Comment by tagliala** [comment]
dup of #1386, please +1 that request

closing here

**Comment by lbruschi** [comment]
done

thank you!!!

2015-06-03 16:35 GMT+02:00 Geremia Taglialatela <notifications@github.com>:
