### ISSUE TITLE
Icon requests: icon-drilling-rig, icon-control-panel, icon-radio-controls, icon-worker

### ISSUE THREAD

**Issue by Chocolate63** [FortAwesome/Font-Awesome#6650]
I would be the happiest person alive if I could get an icons relating to oilfield services.  I am developing websites for several companies in the oilfield industry and these icon would be very useful. 

![controlpanel-icon](https://cloud.githubusercontent.com/assets/12733298/7963798/2b8f1510-09da-11e5-8628-b5a4c2a58ebb.png)
![control-panel-icon](https://cloud.githubusercontent.com/assets/12733298/7963803/2b945728-09da-11e5-82c9-b48a23258560.png)
![oilrig](https://cloud.githubusercontent.com/assets/12733298/7963799/2b8fe742-09da-11e5-8352-361f8dd5258f.png)
![oilrig2](https://cloud.githubusercontent.com/assets/12733298/7963800/2b90946c-09da-11e5-8caf-e1bee1c83dde.png)
![radiocontrol-icon](https://cloud.githubusercontent.com/assets/12733298/7963801/2b9119d2-09da-11e5-8b6e-de4fbe5036e9.png)
![worker](https://cloud.githubusercontent.com/assets/12733298/7963802/2b91c102-09da-11e5-9583-f04401548dce.png)

I would be so GRATEFUL!! I've tried to do them on my own with no luck! Help would be appreciated.
Thanks, Lynn

**Comment by Grimdari** [comment]
Some of the images linked could be modified to be a bit more vanilla and used for more than just Oilfield services.

**Comment by Chocolate63** [comment]
Grimdari, if someone could actually make these icons it would be awesome! I know some could be used for several industries :)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
