### ISSUE TITLE
Mapbox CDN: downloadable font: download failed, cross-site access not allowed

### ISSUE THREAD

**Issue by int-ua** [FortAwesome/Font-Awesome#6651]
It's not loading in Firefox from the Mapbox CDN:

> downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/fonts/fontawesome-webfont.woff?v=4.3.0

Reproducible on the example:
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/

**Comment by tagliala** [comment]
as far as I can tell, there is nothing we can do on our side
