### ISSUE TITLE
Icon Request: fa-portrait

### ISSUE THREAD

**Issue by c01gat3** [FortAwesome/Font-Awesome#6653]
I have an option where the user can select the paper orientation of either portrait or landscape.

Landscape can be represented by fa-picture-o but I need an icon for portrait... something like fa-user in a rectangle.

**Comment by tagliala** [comment]
dup of #2215, please +1 that request

closing here

**Comment by jacobg** [comment]
Not really a dupe. This request is for paper print layout. #2215 is for device or image display. Each one is a distinct use case, and there should be different icons.

**Comment by tagliala** [comment]
Hi @jacobg 

> This request is for paper print layout.

Yes, but the description in the OP is:

> something like fa-user in a rectangle.

which is available here: https://fontawesome.com/icons/portrait?style=solid

Anyway, feel free to open a new issue with an example if neither portrait nor https://fontawesome.com/icons/file-alt?style=regular fit your use case
