### ISSUE TITLE
Site Change Request

### ISSUE THREAD

**Issue by jesyka91** [FortAwesome/Font-Awesome#6659]
I wish there were an input box on the site where you could type an icon to request. Also, this is probably intentional however I wanted to say it anyway, there is no way to submit a contact form from the site and theres email to contact from the site. That would be nice which would be nice, at least for a user, for you guys it could be a mess. 

Anyway thanks for being so (font)Awesome! 
I'd like a tent icon. It would be great! and awesome. Thanks!!

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

This should not be an issue anymore
