### ISSUE TITLE
Icon Issue: Transgender

### ISSUE THREAD

**Issue by ShaunGillies** [FortAwesome/Font-Awesome#6664]
The current icon named transgender isn't reflective of the meaning of the word. Perhaps a change of name to "bi-gender" would be more applicable. The inclusion of non-binary gender representation in Font Awesome is fantastic, but the actual symbol is not a "transgender" symbol.

**Comment by tagliala** [comment]
gender symbols are taken from here: http://en.wikipedia.org/wiki/Gender_symbol.

If there are any issue please discuss on wikipedia then let us know

Leaving this open

**Comment by ShaunGillies** [comment]
Hey there,

Thanks for responding. A quick research shows that the symbol is more representative of an intersex group? Looking at the wikimedia page here: http://www.wikigender.org/index.php/Gender_symbols_gallery the groups are more obviously segmented.

Perhaps I should open an icon request for the symbol ⚧ to replace the current transgender icon, and the symbol ⚥ to be added as an intersex icon?

**Comment by tagliala** [comment]
> Perhaps I should open an icon request for the symbol ⚧ to replace the current transgender icon, and the symbol ⚥ to be added as an intersex icon?

⚧ is already here: http://fontawesome.io/icon/transgender-alt/

We can add an `fa-intersex` alias to ⚥ without breaking backward compatibility. Let me know if this would help

Anyway if you think that transgender must not be used for ⚥, please discuss this issue on wikipedia and then let me know if they fix their pages

**Comment by ShaunGillies** [comment]
Okay, awesome. Thanks for that.

**Comment by tagliala** [comment]
added intersex alias

Closing here. If you have news about the wiki page feel free to comment
