### ISSUE TITLE
Icon Request: fa-industry

### ISSUE THREAD

**Issue by onclick-enterprises** [FortAwesome/Font-Awesome#6667]
I need industry or a factory icon for an industry based website
![factory-512](https://cloud.githubusercontent.com/assets/12759324/8001699/c1ff3ece-0b85-11e5-935f-3883def6e7c7.png)
![factory](https://cloud.githubusercontent.com/assets/12759324/8001709/d9d89fea-0b85-11e5-9e9d-9ca021487897.png)

**Comment by tagliala** [comment]
dup of #1330 , please +1 that request

closing here
