### ISSUE TITLE
Icon Request: fa-javascript

### ISSUE THREAD

**Issue by bmiddha99** [FortAwesome/Font-Awesome#6671]
I would really like you you guys added icons for web technologies like javascript,php,jquery,mysql,and others.
Thanks for the awesome vector icons.
Love them.

**Comment by bomb-on** [comment]
+1!!
[There is something similar already](http://fizzed.com/oss/font-mfizz), although it is not maintained anymore... Nevertheless, it would be AWESOME to have them all in one package, rather than including few more other CSS...

**Comment by tagliala** [comment]
duplicate of #1711 , please +1 that request

please also consider using mfizz for technology icons

Closing here

**Comment by bmiddha99** [comment]
Thanks
