### ISSUE TITLE
Icon Request: fa-responsive

### ISSUE THREAD

**Issue by yocmen** [FortAwesome/Font-Awesome#6673]
I will use in features block for example, or in a select platform section, this will be nice, i work with this features and i will love that icon, a nice example :http://atlaschirosys.com/apps_intro/img/app_icons/responsive_icon.png very thanksssss for your great job!!!!!!!!!! keep doing it!!!!!

**Comment by tagliala** [comment]
duplicate of #1446 , please +1 that request

closing here
