### ISSUE TITLE
Icon Request: icon- food building icon 

### ISSUE THREAD

**Issue by abidin13** [FortAwesome/Font-Awesome#6677]
hi fontawesome,
please create a new icon like a food building icon or burger, pizza icon.
beacause this icon is a very identic for a web about food event or food place

i really hope this be done, for better fontawesome
thanks

**Comment by tagliala** [comment]
refers to #1895 

pizza is a duplicate of #4493, please +1 that request
hamburger is a duplicate of #1961 , please +1 that request

closing here
