### ISSUE TITLE
Area chart not missing

### ISSUE THREAD

**Issue by socialblogsite** [FortAwesome/Font-Awesome#6678]
I installed the font in OSX Mavericks, and the character "Area Chart" is missing.
If I copy it from the Cheat Sheet and paste it in Illustrator, it shows a crossed square.

The version in my FontBook (the font manager in Mac) shows 4.3.0 2015, same as the CheatSheet I'm copying the icon from. 

All points to the CheatSheet showing an icon that is not there anymore.

Any other character is there fine.

**Comment by tagliala** [comment]
There are similar issues about random missing icons, like #6288

Closing here in favour of #6288 

Could you please try the .otf file?

**Comment by socialblogsite** [comment]
.otf is the font I have installed in illustrator. No dice.
