### ISSUE TITLE
Icon Request: fa-clock

### ISSUE THREAD

**Issue by CupOfTea696** [FortAwesome/Font-Awesome#6688]
Currently there is no `fa-clock` icon, only a [fa-clock-o](http://fortawesome.github.io/Font-Awesome/icon/clock-o/) icon. It'd be great if there was a solid one as well.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by doughb-umich** [comment]
+1

**Comment by tagliala** [comment]
I think this has been addressed a while ago in FA5: https://fontawesome.com/v5.15/icons/clock?style=solid
