### ISSUE TITLE
Icon request: File-plus

### ISSUE THREAD

**Issue by josef-brink** [FortAwesome/Font-Awesome#6689]
The icon would look like this: http://fortawesome.github.io/Font-Awesome/icon/file/ but with a "plus" icon next to it, like this one: http://fortawesome.github.io/Font-Awesome/icon/user-plus/ .
I would use it to my mini-CMS as an icon when i want to crate a new page, but i guess you can use it for a variety of different things. Create new post, blog, news etc.

**Comment by tagliala** [comment]
refers to #1181 

subset of #1525, please +1 that request

closing here
