### ISSUE TITLE
Icon Request: fa-sanitation

### ISSUE THREAD

**Issue by Milaap** [FortAwesome/Font-Awesome#6690]
We are trying to use font-awesome icons to represent various social causes we support. Sanitation is one such cause. Here is one idea for the icon:

![image](https://cloud.githubusercontent.com/assets/417503/8054289/3413ada6-0eb5-11e5-9e34-6efe0b264ae9.png)

It will be great if font-awesome can provide an icon for this.

Thanks!

**Comment by aethior** [comment]
Hi @Milaap,

This icon was added in v5.6.0.
Check https://fontawesome.com/icons/toilet

Regards.

cc/ @tagliala
