### ISSUE TITLE
Icon Request: fa-weight and fa-box

### ISSUE THREAD

**Issue by xewl** [FortAwesome/Font-Awesome#6692]
Sadly I'm missing a few icons in FA, user scenario is a fulfilment application.

For box I can use `fa-dropbox`, but there's nothing to accomodate for a real "parcel"-box.

Another icon I'd like to see is "weight".
As an example (maybe a non-outlined one) from another (paid) set:
http://www.iconexperience.com/i_collection/icons/?icon=weight2

**Comment by eggleton** [comment]
What about `fa-cube` for parcel?

**Comment by tagliala** [comment]
box: #6221
weight: #2735

please +1 the above requests

all dups, closing here!

**Comment by xewl** [comment]
Will +1, thanks for the suggestion, eggleton :)
