### ISSUE TITLE
Icon request: fa-ruby

### ISSUE THREAD

**Issue by andela-bojengwa** [FortAwesome/Font-Awesome#6694]
We are looking for an icon of the various programming languages. As programmers, we always work with different languages or might need to sort projects according to language, etc. I think having an icon that represents that will be an awesome idea. Here is one idea for the icon:

![Ryby Icon One] (http://vignette4.wikia.nocookie.net/battlefordreamisland/images/5/5e/Ruby_Icon.png)

It will be great if we can provide an icon for this as well as for other major programming languages.

Thanks!
:)

**Comment by tagliala** [comment]
duplicate of #3654, please +1 that request

closing here
