### ISSUE TITLE
Icon request: fa-nodejs

### ISSUE THREAD

**Issue by andela-bojengwa** [FortAwesome/Font-Awesome#6695]
We are looking for an icon of the various programming languages. As programmers, we always work with different languages or might need to sort projects according to language, etc. I think having an icon that represents that will be an awesome idea. Here is one idea for the icon:

![NodeJS Icon One] (http://www.flintdeveloper.co.uk/media/icons/node-js.png)

or 

![NodeJS Icon Two] (http://nodejs-cloud.com/img/128px/nodejs.png)

or 

![NodeJS Icon Three] (http://code-maven.com/img/node.png)

It will be great if we can provide an icon for this as well as for other major programming languages.

Thanks!
:)

**Comment by chrisvdp** [comment]
Dup? https://github.com/FortAwesome/Font-Awesome/issues/2584

**Comment by tagliala** [comment]
@chrisvdp thanks

closing here
