### ISSUE TITLE
Icon request: swift (programming language)

### ISSUE THREAD

**Issue by benjiwheeler** [FortAwesome/Font-Awesome#6702]
you can see an example at:

http://www.carlosicaza.com/wp-content/uploads/2014/07/Swift-logo.png

**Comment by dickeysingh** [comment]
+1

**Comment by abellao** [comment]
+1

**Comment by oarrabi** [comment]
+1

**Comment by nicolinden** [comment]
+1

**Comment by calebrwells** [comment]
👍

**Comment by RixD** [comment]
👍

**Comment by fbronner** [comment]
+1

**Comment by heidihelen** [comment]
👍

**Comment by DXZDB** [comment]
👍

**Comment by Malauch** [comment]
+1

**Comment by monk4june** [comment]
👍

**Comment by joeNeale** [comment]
👍🏻

**Comment by ccjensen** [comment]
👍🏻

**Comment by chriswilson1982** [comment]
👍🏼

**Comment by alloyapple** [comment]
+1

**Comment by fordee** [comment]
👍

**Comment by ShawnBaek** [comment]
👍

**Comment by adjusting** [comment]
👍

**Comment by lordmooch** [comment]
👍🏻

**Comment by fblondiau** [comment]
👍🏼

**Comment by JulesMoorhouse** [comment]
👍

**Comment by an-jorge** [comment]
Beautiful

**Comment by tagliala** [comment]
Hi guys, please use the 👍 to upvote this request.

It counts just like a comment, please refer to: https://fontawesome.com/community/leaderboard/brands

**Comment by iyleveeranna** [comment]
👍

**Comment by kai7win** [comment]
+1

**Comment by tagliala** [comment]
Hi again, please use the 👍 to upvote this request.

Please do not comment with +1s, since comments are going to make unnecessary noise (notifications and emails)

If there is a page asking for coming here and add a +1 comment, please change that.

Thanks

**Comment by jeaes87** [comment]
👍🏽

**Comment by tagliala** [comment]
Temporary locking here, as per https://github.com/FortAwesome/Font-Awesome/issues/6702#issuecomment-523898603 and https://github.com/FortAwesome/Font-Awesome/issues/6702#issuecomment-523816667

**Comment by swiftymaxx** [comment]
👍🏼

**Comment by jchrisjackson** [comment]
👍

**Comment by timmitra** [comment]
+1

**Comment by skylerbellwood** [comment]
👍

**Comment by tagliala** [comment]
Hi again,

this request is now at the top of our [Brand Leaderboard](https://fontawesome.com/community/leaderboard/brands), congrats!

As per my previous comments, https://github.com/FortAwesome/Font-Awesome/issues/6702#issuecomment-523898603, https://github.com/FortAwesome/Font-Awesome/issues/6702#issuecomment-523816667, https://github.com/FortAwesome/Font-Awesome/issues/6702#issuecomment-523959941 

I'm going to lock here again to avoid unnecessary notifications

**Comment by sensibleworld** [comment]
Love seeing this much support for an icon! I’ve added it to our production queue.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/swift?style=brands
