### ISSUE TITLE
Icon request: icon-bag

### ISSUE THREAD

**Issue by ruchiccio** [FortAwesome/Font-Awesome#6705]
This is a request for a shopping bag icon. Now lots of sites are using "bag" instead of "cart" for retail sites. Font Awesome only has a cart as of yet. These can be used on websites in the navigation bar, as well as on buttons for "add to bag". 
![bag](https://cloud.githubusercontent.com/assets/12818209/8066050/6c4530ca-0eb3-11e5-8ff9-41fd291cb8dc.jpg)

**Comment by CandiceB** [comment]
+1 would love this

**Comment by rubengc** [comment]
I want this icon too

**Comment by tagliala** [comment]
duplicate of #829 , please +1 that request

closing here
