### ISSUE TITLE
Icon-request: fingerprint-indexfinger-left/fingerprint-indexfinger-right/fingerprint-4fingers-left/fingerprint-4fingers-right/fingerprint-thumb-left/fingerprint-thumb-right

### ISSUE THREAD

**Issue by La8pv** [FortAwesome/Font-Awesome#6707]
Icons for Fingerprint capture, two finger (1-1) index fingers and ten fingers (4-4-2). Ref. ISO/IEC standard CD 24779-2 and 24779-1

**Comment by sensibleworld** [comment]
We now have a fingerprint icon: https://fontawesome.com/icons/fingerprint?s=solid&f=classic
