### ISSUE TITLE
Icon Request: fa-folderssss

### ISSUE THREAD

**Issue by emalcdo** [FortAwesome/Font-Awesome#6708]
fa-folder-add fa-folder-add-o
fa-folder-delete fa-folder-delete-o
fa-folder-move fa-folder-move-o
fa-folder-rename fa-folder-rename-o
fa-folder-info fa-folder-info-o
fa-folder-pictures fa-folder-pictures-o
fa-folder-videos fa-folder-videos-o
fa-folder-music fa-folder-music-o
fa-folder-text fa-folder-text-o

and many more folder icons!!!!

I'm designing a custom CMS with asset management (of course with toolbars and icons) and I don't want to export a single icon into image (in short i'm lazy)

yeah, you get the idea
https://www.iconfinder.com/search/?q=folder&maximum=16&style=glyph

thanks guys more power, love ya

**Comment by tagliala** [comment]
Sorry, I can't leave this open

It doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Please take a look at #1181, you will find a solution
