### ISSUE TITLE
Icon request: fa-triangle, fa-triangle-o

### ISSUE THREAD

**Issue by mokraemer** [FortAwesome/Font-Awesome#6710]
basic forms should be available before specific forms created, stacking basic forms allows you to create the complex ones by yourself.

**Comment by TheChen5** [comment]
Dupe of #3216 .
+1 that.
*Search before creating.*

**Comment by tagliala** [comment]
I don't like #3216 because that request contains 8 icons and an improper title

btw... closing here as a duplicate

**Comment by brevilo** [comment]
Well, most comments on #3216 do actually refer to the title give +1's for the triangle...
