### ISSUE TITLE
Icon request: fa-arrow-down-right

### ISSUE THREAD

**Issue by rbruckheimer** [FortAwesome/Font-Awesome#6714]
Hi,
I'm looking for something similar to unicode x2937, an arrow pointing down then right, to illustrate something descended from something else.
For example,

AAAA
    x    BBBB

Where x is the icon showing BBBB descends from AAAA.

Thanks!

**Comment by tagliala** [comment]
http://www.fileformat.info/info/unicode/char/2937/index.htm

**Comment by tagliala** [comment]
you could rotate http://fontawesome.io/icon/level-up/ by 90 degrees

http://jsfiddle.net/tagliala/e9yfxsfj/20/

**Comment by hubgit** [comment]
> you could rotate http://fontawesome.io/icon/level-up/ by 90 degrees

```html
<i class="fa fa-level-up fa-rotate-90"></i>
```

works for me - good idea!

**Comment by aethior** [comment]
Hi @rbruckheimer,

Currently there are [fa-turn-down-right](https://fontawesome.com/icons/turn-down-right) and [fa-arrow-turn-down-right](https://fontawesome.com/icons/arrow-turn-down-right) icons.
Regards.

cc/ @tagliala
