### ISSUE TITLE
Icon Request: fa-xmpp & fa-infinity

### ISSUE THREAD

**Issue by daniel-hyuuga** [FortAwesome/Font-Awesome#6727]
XMPP / Jabber is quite popular open source messaging service and for fa-infinity can be used by webhosts and etc. that provides something "unlimited"

fa-xmpp: http://medicine.ucsf.edu/domit/images/xmpp-logo-100.png (without "XMPP" word)
fa-infinity: https://yaalli.files.wordpress.com/2014/07/the-destination.png?w=141

**Comment by Baker** [comment]
+1

**Comment by TheChen5** [comment]
fa-infinity seems to be a dupe of #1647

**Comment by tagliala** [comment]
and fa-xmpp is here #549 

all dups, closing here
