### ISSUE TITLE
Icon Request: fa-horse

### ISSUE THREAD

**Issue by No1Name1** [FortAwesome/Font-Awesome#6729]
Hi,
I need an icon with the silhouette of a horse head.
It would be nice, if you can add it with the next update :)

No1Name1

![horse1](https://cloud.githubusercontent.com/assets/3400260/8114861/c8933ed8-1077-11e5-9bea-e4ed97f38188.jpg)
![horse2](https://cloud.githubusercontent.com/assets/3400260/8114862/c8988258-1077-11e5-98aa-6cd5c54091a4.png)

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #2049 , please +1 that request

closing here

**Comment by vlasvlasvlas** [comment]
yea but still no horse.
