### ISSUE TITLE
Icon Request: fa-burger

### ISSUE THREAD

**Issue by nicho90** [FortAwesome/Font-Awesome#6738]

**Comment by nicho90** [comment]
Hey it would be awesome if you would provide a fast-food-icon, e.g. a burger and a drink.

**Comment by kwaaui** [comment]
+1
![burger](https://cloud.githubusercontent.com/assets/484470/8322165/55e95ae8-1a31-11e5-907b-5d0e34d15621.png)

**Comment by tagliala** [comment]
duplicate of #1961 , please +1 that request

closing here

**Comment by nicho90** [comment]
Great thank you!! I haven't seen, that it was already a created.
