### ISSUE TITLE
@ fa-at style should suit the family

### ISSUE THREAD

**Issue by atilkan** [FortAwesome/Font-Awesome#6740]
fa-at @ icon style is not cool. And it does not suit the rest of font-awesome. Like it is put there to stop the request coming from fans/people. Sorry i say it. It is ugly. Please consider before going mad.

Thanks.

**Comment by tagliala** [comment]
could you please provide a better example?

**Comment by atilkan** [comment]
It should be just bolder like example. I have no experience on making fonts.
https://www.iconfinder.com/icons/211625/at_icon#size=16

**Comment by tagliala** [comment]
Fixed in FA5

https://jsfiddle.net/tagliala/yxqqchjs/5/
