### ISSUE TITLE
Icon request: fa-textilecare-*

### ISSUE THREAD

**Issue by flummer** [FortAwesome/Font-Awesome#6742]
This is an idea for a series of icons, all related to textile care (washing, ironing, bleaching, dry cleaning, etc.). It's like all the little icons that is used on clothes, but they could also be very relevant on websites selling clothes, to indicate how a product should be treated or in other online documentation.

https://www.google.com/search?q=textile+care+icons (image search) gives a pretty good general idea on how they should look.

Naming could be like:
`fa-textilecare-iron`
`fa-textilecare-iron-low`
`fa-textilecare-iron-mid`
`fa-textilecare-iron-high`
`fa-textilecare-iron-no`

or maybe simply:
`fa-iron`
`fa-iron-low`
`fa-iron-mid`
`fa-iron-high`
`fa-iron-no`

Main categories would be:
- washing
- ironing
- drying
- bleaching
- clothing size

**Comment by tagliala** [comment]
Sorry, I can't keep this open

It does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

press iron is here: #5915
washing machine: #6605 
clothing size maybe: #6529 

You can of course open individual requests for missing icons

If you need all those icons my advice is to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
