### ISSUE TITLE
arrow-circle-down is read out by JAWS screen reader

### ISSUE THREAD

**Issue by rhulse** [FortAwesome/Font-Awesome#6745]
I have been doing a bunch of testing on my site and I have also checked on the font awsome site - this is the case there also.

JAWS reads out the unicode for arrow-circle-down. I wonder if this is a bug in JAWS though, as the unicode is well within the range of the PUA??

**Comment by tagliala** [comment]
@rhulse only that icon?

**Comment by tagliala** [comment]
Refers to #6133

**Comment by rhulse** [comment]
I did try many others on the demo page and they were fine, but I did not try them all.

In the end I did try a different browser. Turns out that Chrome reads out that font, IE does not.

I'll log a bug with Chrome.

**Comment by tagliala** [comment]
thanks!

Let us know

**Comment by tagliala** [comment]
Hi!

We have worked a lot on accessibility https://fontawesome.com/docs/web/dig-deeper/accessibility#contentHeader

I'm closing here for inactivity, but if there are accessibility issues, feel free to fill out a [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)?
