### ISSUE TITLE
Icon Request: fa-shoe

### ISSUE THREAD

**Issue by hasandogu** [FortAwesome/Font-Awesome#6746]
It would be awesome to have some icons related with fashion.

fa-shoe, fa-hanger, fa-dress, fa-hat

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
shoe: running #3704 woman #3473
hat: maybe #6670
hanger #1659
dress #3852

please +1 the proper requests

all dups, closing here

**Comment by jonathancbatista** [comment]
+1 for that
