### ISSUE TITLE
Icon Request: fa-opensource-o

### ISSUE THREAD

**Issue by jesseflorig** [FortAwesome/Font-Awesome#6756]
I'd like to request icons for the open source logo as seen here: 
![open source logo](http://opensource.org/files/garland_logo.png)

It would be great to use in open source projects as a pixel-perfect badge of openness!

I searched the Issues for this submission since I assumed it would have been requested already, but to my surprise I couldn't find anything. my apologies in advance if I  missed it.

Cheers!

**Comment by hebbet** [comment]
Duplicate of #6200

**Comment by tagliala** [comment]
which is a duplicate of #1283

Leaving this open as open-source-o

**Comment by tagliala** [comment]
Can't remember why I left this open...

BTW this is a duplicate of #1283 and icon-osi is available on FA5 https://fontawesome.com/icons/osi?style=brands
