### ISSUE TITLE
Icon Request: fa-lotus

### ISSUE THREAD

**Issue by tintomatoes** [FortAwesome/Font-Awesome#6757]
The lotus flower is a powerful symbol of nature and harmony. It's universally recognised, beautiful to look at and can be used in many different situations.

It can be used to represent nature, seasons, wilderness, harmony, unity, beauty, yoga, divinity, purity, Hinduism, Buddhism, Egyptology, creation, expansion, rebirth, enlightenment, rarity.

According to Wikipedia, the lotus is "an ancient and polyvalent symbol in Asian culture."

![images](https://cloud.githubusercontent.com/assets/12890968/8154809/98f743a4-135b-11e5-8120-65c89ba727df.jpg)
![lotus-logo-28375320](https://cloud.githubusercontent.com/assets/12890968/8154816/9ee45b80-135b-11e5-8eeb-3f3ae2910410.jpg)
![person-icon-lotus-flower](https://cloud.githubusercontent.com/assets/12890968/8154817/9f20da74-135b-11e5-946b-9834a37c6ee6.png)

**Comment by sgryphon** [comment]
+1

**Comment by abbynucup** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by OSamkova** [comment]
+1

**Comment by sakafujn** [comment]
+1

**Comment by pierm8** [comment]
+1

**Comment by solucoes-tm** [comment]
como faço para fazer download

**Comment by tagliala** [comment]
This is available in FA 5.1 as `fa-spa`

https://fontawesome.com/icons/spa?style=solid
