### ISSUE TITLE
Icon Request: fa-play-mode-shuffle, fa-play-mode-order, fa-play-mode-repeat-all, fa-play-mode-repeat-once

### ISSUE THREAD

**Issue by kanbekotori** [FortAwesome/Font-Awesome#6759]
Hello, i want a set of music play mode like shuffle, order, repeat-all, repeat-once, thanks!

**Comment by tagliala** [comment]
Sorry, can't keep this open.

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Shuffle is already here: http://fontawesome.io/icon/random/
for the Repeat you can use retweet
