### ISSUE TITLE
Icon request: user-search

### ISSUE THREAD

**Issue by robinv3001** [FortAwesome/Font-Awesome#6760]
Hi :)
I thought it would be nice if there was an icon that could be used when looking up a person/user.
It consists of the usual user icon in combination with a magnifying glass, as can be seen in the image I attached.

Hope it will be added in a future version!
![userbtn_suggestion](https://cloud.githubusercontent.com/assets/12894887/8159641/f3c5ba88-1368-11e5-8d92-4bec8aeef2bc.png)

Robin

**Comment by robinv3001** [comment]
Never mind, same as https://github.com/FortAwesome/Font-Awesome/issues/6144

**Comment by tuxy** [comment]
+1, for fa-user-search

**Comment by micdech** [comment]
+1, for fa-user-search

**Comment by tagliala** [comment]
locking here, this is a duplicate
