### ISSUE TITLE
Icon request: fa-envelopes, fa-envelopes-o

### ISSUE THREAD

**Issue by devniel93** [FortAwesome/Font-Awesome#6767]
Please I need icon like fa-envelope. 
For example: http://www.graphicmail.com/site/images/bulksms-icon%20copy.png 
Thank you..

**Comment by amlette** [comment]
@danielolanoburga 
What's wrong with **fa-envelope**, **fa-envelope-o** and **fa-envelope-square** ?

**Comment by tagliala** [comment]
probably he needs `fa-envelopes`

**Comment by danielolanoburga** [comment]
@tagliala yes! , i need fa-envelopes or something like that.

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by pk-fr** [comment]
+1

**Comment by tonatiuh** [comment]
+1

**Comment by MartinHlavna** [comment]
+1

**Comment by sensibleworld** [comment]
Thanks for the request. We've have a few icons that might work for this now. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=envelopes&s=solid

<img width="548" alt="Screen Shot 2021-05-27 at 1 54 16 PM" src="https://user-images.githubusercontent.com/529604/119873884-0844f780-bef3-11eb-92d3-c65b50a3cdbf.png">
