### ISSUE TITLE
Icon Request: fa-strava

### ISSUE THREAD

**Issue by lexusburn** [FortAwesome/Font-Awesome#6768]
I would like to use a strava (https://www.strava.com/) icon on a profile page, like twitter or instagram icons.

![Strava Icon](https://cloud.githubusercontent.com/assets/659847/8200637/3ad9efd8-14c8-11e5-8267-230dee72597e.png)

**Comment by tagliala** [comment]
duplicate of #3313, please +1 that request

closing here
