### ISSUE TITLE
Icon Request: fa-heart-half, fa-heart-half-o

### ISSUE THREAD

**Issue by danielpattiasina** [FortAwesome/Font-Awesome#6769]
First of all, keep up the good stuff! I love FontAwesome :)

My request is basically a star rating with hearts. The half-heart icon is missing and i think it fits right in with the current icon-set. I also think it won't be difficult to create since you've already have the standard heart- and open heart icon.

Hopefully you can include these 2 in the next version.

Good luck and thanks!

**Comment by montecruiseto** [comment]
++1

**Comment by tagliala** [comment]
dup of #2301, please +1 that request

closing here
