### ISSUE TITLE
Icon request: for medical use

### ISSUE THREAD

**Issue by Ghaby** [FortAwesome/Font-Awesome#6771]
Hi!

sorry to bother you! I love Awesome Fonts Icons, and I need some new icons for my new web. It's about natural medicine and I'm going to organize ingredients by its application.
So, I've made some new icons and I was wondering if it was possible to get them transformed into awesome icons?

Names are in files attached.

Thank you in advance! 

p.s. I know there's a lot.. if it's not possible don't worry. I'll love awesome icons anyway.! xp

![caffeine](https://cloud.githubusercontent.com/assets/12911350/8203914/70d026d0-14e5-11e5-8181-2a27e60716b5.png)
![candy](https://cloud.githubusercontent.com/assets/12911350/8203917/70fd3b70-14e5-11e5-9e67-50944f397baa.png)
![dumbbell](https://cloud.githubusercontent.com/assets/12911350/8203920/710377d8-14e5-11e5-8717-91bcc5632062.png)
![energetic](https://cloud.githubusercontent.com/assets/12911350/8203918/70ff4c08-14e5-11e5-9967-26ba99657953.png)
![female-reprod-system](https://cloud.githubusercontent.com/assets/12911350/8203916/70fd0ccc-14e5-11e5-900d-41e3d517c0ce.png)
![fruits](https://cloud.githubusercontent.com/assets/12911350/8203919/71009d1a-14e5-11e5-8007-c7af35d9171f.png)
![intestine](https://cloud.githubusercontent.com/assets/12911350/8203915/70ede1c0-14e5-11e5-87e5-acd7302878fe.png)
![joints](https://cloud.githubusercontent.com/assets/12911350/8203921/711039be-14e5-11e5-9f9d-6410d3460f71.png)
![seaweed](https://cloud.githubusercontent.com/assets/12911350/8203922/7116b6cc-14e5-11e5-85c7-50639367bb22.png)
![skin](https://cloud.githubusercontent.com/assets/12911350/8203923/7117c2b0-14e5-11e5-8d5c-413d9fb0783a.png)
![test-tube](https://cloud.githubusercontent.com/assets/12911350/8203924/711e31fe-14e5-11e5-9126-761285cb8324.png)
![urinary-system](https://cloud.githubusercontent.com/assets/12911350/8203925/711ebc78-14e5-11e5-87d5-ff79e15552f2.png)
![weight-control](https://cloud.githubusercontent.com/assets/12911350/8203926/71204c28-14e5-11e5-94a8-3cbc6a187a25.png)
![yoga](https://cloud.githubusercontent.com/assets/12911350/8203927/7132f616-14e5-11e5-8ad1-317346915cdc.png)

**Comment by tagliala** [comment]
Sorry, I can't leave this open because it does not meet our contributing guidelines

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

There are some duplicates you can +1, such as #1500 , #6770 , #6825 , #6015
