### ISSUE TITLE
fa-upload does not line up with fa-download

### ISSUE THREAD

**Issue by lexilass** [FortAwesome/Font-Awesome#6772]
When displayed next to each other the bottom of the fa-upload icon does not line up with the bottom of the fa-download icon:
![image](https://cloud.githubusercontent.com/assets/1678495/8204603/bad15a50-14e1-11e5-9154-189750dd2f74.png)

Additionally, the rounding on the corners of the server are different and the length of the arrows are different.

**Comment by tagliala** [comment]
Thanks for reporting this

This issue is confirmed and reported here: #1624
