### ISSUE TITLE
We need a Photoshop icon!

### ISSUE THREAD

**Issue by BamiGorengo** [FortAwesome/Font-Awesome#6778]
Hey,

Sorry when i post this request to the wrong area. its my first time on github...
I realy needed allready alot of times a Photoshop icon. You guys want to implement it soo? ;)

best regards!

**Comment by sha-2** [comment]
Duplication of #1970

**Comment by tagliala** [comment]
@sha-2 thanks

actually I don't know what to do with #1970 because it doesn't meet our contributing guidelines anymore

But I will still consider this a duplicate... so, closing here
