### ISSUE TITLE
Icon Request: Expand All / Collapse All

### ISSUE THREAD

**Issue by edwardsdesign** [FortAwesome/Font-Awesome#678]
These icons would be useful to represent expand or collapse all items that have been grouped by parent or in an accordion.

**Comment by josdejong** [comment]
I'm looking around for icons 'Expand all" and "Collapse all" to expand/collapse all items in an hierarchic tree (like a document structure) but can't find anything that comes close. 

This is what I'm currently using, which is self made, but I would love to use font-awesome instead:

![image](https://user-images.githubusercontent.com/568626/31434014-738e202a-ae7b-11e7-8a15-d7ae7439f5dd.png)

Any suggestions?
