### ISSUE TITLE
Feature Request: Add font-awesome.scss to bower.json

### ISSUE THREAD

**Issue by mike-jellybean** [FortAwesome/Font-Awesome#6780]
I'm always working with wiredep throughout .scss files. 
To make it automatically include I suggest to do the following change:

```
"main": [
  "./scss/font-awesome.scss",
  "./css/font-awesome.css",
  "./fonts/*"
],
```

so adding the font-awesome.scss file to main in the bower.json file.

**Comment by tagliala** [comment]
Refers to #6227

**Comment by tagliala** [comment]
Closed via https://github.com/FortAwesome/Font-Awesome/commit/11884523464c05869d4b6e5484d538c049654bbe

thanks!

**Comment by benbruscella** [comment]
I think this breaks main-bower-files with gulp?

**Comment by tagliala** [comment]
@benbruscella please open a new issue explaining the problem
