### ISSUE TITLE
Icon Request - ETZY

### ISSUE THREAD

**Issue by MarcButeau** [FortAwesome/Font-Awesome#6781]
I could use this on the website I'm creating.
I currently have in the footer Facebook, Twitter, Instagram, Deviantart, Pinterest.

I would like to add ETZY (etzy.com) to my footer to direct browsers to my ETZY account.

Thanks.

**Comment by tagliala** [comment]
etzy is not etsy?

**Comment by RRorg** [comment]
He means etsy.

**Comment by Garrcomm** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1962 , please +1 that request

closing here
