### ISSUE TITLE
Icon Request: fa-pokemon (pokeball)

### ISSUE THREAD

**Issue by eliasthompson** [FortAwesome/Font-Awesome#6799]
It'd be a Poké Ball which would represent the Pokémon franchise. Mostly a brand thing.

Ex:
![](http://ih0.redbubble.net/image.46821384.7393/fc,550x550,white.jpg)

**Comment by ImSanctuary** [comment]
I was actually thinking about suggesting this a few days ago, glad I'm not the only one who thinks this would be a nice addition.
I strongly agree with this.

**Comment by Dan-Brantze** [comment]
+1

**Comment by eliasthompson** [comment]
Ended up using a couple of other things to make this happen, but if this is still under consideration, here is the SVG I came up with. https://dl.dropboxusercontent.com/u/33575887/poke-ball.svg

**Comment by saturnaut** [comment]
+1, would love this icon.

**Comment by bedeviere** [comment]
+1

**Comment by hugmanrique** [comment]
+1

**Comment by unknown0perator** [comment]
+1

**Comment by eliasthompson** [comment]
Ended up making my own SVG for my project which I was able to convert to a glyph. Here's the SVG: https://dl.dropboxusercontent.com/u/33575887/poke-ball.svg

**Comment by ryankane** [comment]
Here are three raster images that I exported from vectors that were created based on the Pokémon GO game files. I copied these over from Issue #9685.

Enjoy. :smile: 

# fa-pokeball

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokeball-16][] | ![fa-pokeball-32][] | ![fa-pokeball-64][] | ![fa-pokeball-128][]
| 16px | 32px | 64px | 128px |

![fa-pokeball][]

## Source

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="11.3778in" height="11.3778in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-teamless"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 512.00,96.80
           C 304.28,96.94 132.17,249.33 101.24,448.41
             101.24,448.41 312.51,448.80 312.51,448.80
             339.50,364.37 418.60,303.25 512.00,303.20
             605.25,303.31 684.24,364.33 711.33,448.61
             711.33,448.61 922.53,448.80 922.53,448.80
             891.82,249.60 719.75,97.06 512.00,96.80
             512.00,96.80 512.00,96.80 512.00,96.80 Z
           M 512.00,376.80
           C 436.89,376.80 376.00,437.69 376.00,512.80
             376.00,587.91 436.89,648.80 512.00,648.80
             512.00,648.80 512.00,648.80 512.00,648.80
             587.11,648.80 648.00,587.91 648.00,512.80
             648.00,512.80 648.00,512.80 648.00,512.80
             648.00,437.69 587.11,376.80 512.00,376.80
             512.00,376.80 512.00,376.80 512.00,376.80
             512.00,376.80 512.00,376.80 512.00,376.80 Z
           M 101.47,576.80
           C 132.18,776.00 304.25,928.54 512.00,928.80
             719.72,928.66 891.83,776.27 922.76,577.19
             922.76,577.19 711.49,576.80 711.49,576.80
             684.50,661.23 605.40,722.35 512.00,722.40
             418.75,722.29 339.76,661.27 312.67,576.99
             312.67,576.99 101.47,576.80 101.47,576.80
             101.47,576.80 101.47,576.80 101.47,576.80 Z" />
</svg>
```

---

The following icon was created from the Gym Arena Glass image from Pokemon GO.

![t_gym_arena_glass][]

# fa-pokemon-arena

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokemon-gym-16][] | ![fa-pokemon-gym-32][] | ![fa-pokemon-gym-64][] | ![fa-pokemon-gym-128][]
| 16px | 32px | 64px | 128px |

![fa-pokemon-gym][]

## Source

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="14.2222in" height="14.2222in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-gym-arena"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 373.34,561.43
           C 393.65,618.40 448.06,659.18 512.00,659.18
             575.94,659.18 630.35,618.40 650.66,561.43
             650.66,561.43 908.38,561.43 908.38,561.43
             883.46,761.46 713.58,911.69 512.00,911.94
             310.37,911.76 140.41,761.51 115.49,561.43
             115.49,561.43 373.34,561.43 373.34,561.43 Z
           M 512.00,414.48
           C 458.14,414.48 414.48,458.14 414.48,512.00
             414.48,565.86 458.14,609.52 512.00,609.52
             565.86,609.52 609.52,565.86 609.52,512.00
             609.52,458.14 565.86,414.48 512.00,414.48 Z
           M 486.44,112.89
           C 486.44,112.89 486.44,138.55 486.44,138.55
             329.08,149.43 194.17,258.38 151.62,412.17
             151.62,412.17 125.03,412.17 125.03,412.17
             168.39,243.93 314.96,123.93 486.44,112.89
             486.44,112.89 486.44,112.89 486.44,112.89 Z
           M 898.77,412.17
           C 898.77,412.17 872.77,412.17 872.77,412.17
             830.18,258.24 695.07,149.25 537.56,138.53
             537.56,138.53 537.56,112.90 537.56,112.90
             708.96,124.02 855.42,244.00 898.77,412.17 Z
           M 680.32,473.71
           C 680.32,473.71 909.81,473.71 909.81,473.71
             910.65,482.09 911.24,490.56 911.54,499.09
             911.54,499.09 658.54,499.37 658.54,499.37
             651.99,423.30 588.35,364.87 512.00,364.82
             435.64,364.87 372.01,423.30 365.45,499.37
             365.45,499.37 112.65,499.02 112.65,499.02
             112.80,490.42 113.23,481.89 113.92,473.71
             113.92,473.71 343.53,473.71 343.53,473.71
             361.07,396.20 430.27,339.23 512.00,339.23
             593.67,339.30 662.79,396.25 680.32,473.71 Z" />
</svg>
```
---

I created this from scratch referencing the menu icon in the game.

# fa-pokeball-alt

| Small  | Medium | Large | X-Large |
| :---: | :---: | :---: | :---: |
| ![fa-pokeball-alt-16][] | ![fa-pokeball-alt-32][] | ![fa-pokeball-alt-64][] | ![fa-pokeball-alt-128][]
| 16px | 32px | 64px | 128px |

![fa-pokeball-alt][]

## Source

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg"
     width="14.2222in" height="14.2222in"
     viewBox="0 0 1024 1024">
  <path id="pkmn-go-menu"
        fill="#000000" stroke="none" stroke-width="1"
        d="M 512.00,359.18
           C 512.00,359.18 512.00,359.18 512.00,359.18
             596.40,359.18 664.81,427.60 664.82,512.00
             664.82,512.00 664.82,512.00 664.82,512.00
             664.82,596.40 596.40,664.81 512.00,664.82
             512.00,664.82 512.00,664.82 512.00,664.82
             427.60,664.82 359.19,596.40 359.18,512.00
             359.18,512.00 359.18,512.00 359.18,512.00
             359.18,427.60 427.60,359.18 512.00,359.18
             512.00,359.18 512.00,359.18 512.00,359.18
             512.00,359.18 512.00,359.18 512.00,359.18 Z
           M 512.00,410.12
           C 455.73,410.12 410.12,455.73 410.12,512.00
             410.12,568.27 455.73,613.88 512.00,613.88
             568.27,613.88 613.88,568.27 613.88,512.00
             613.88,455.73 568.27,410.12 512.00,410.12
             512.00,410.12 512.00,410.12 512.00,410.12 Z
           M 806.16,217.84
           C 884.17,295.86 928.00,401.67 928.00,512.00
             928.00,622.33 884.17,728.14 806.16,806.16
             728.14,884.17 622.33,928.00 512.00,928.00
             401.67,928.00 295.86,884.17 217.84,806.16
             139.83,728.14 96.00,622.33 96.00,512.00
             96.00,401.67 139.83,295.86 217.84,217.84
             295.86,139.83 401.67,96.00 512.00,96.00
             622.33,96.00 728.14,139.83 806.16,217.84 Z
           M 332.02,512.00
           C 332.02,512.00 138.45,512.00 138.45,512.00
             138.45,611.07 177.81,706.09 247.86,776.14
             317.91,846.19 412.93,885.55 512.00,885.55
             611.07,885.55 706.09,846.19 776.14,776.14
             846.19,706.09 885.55,611.07 885.55,512.00
             885.55,512.00 885.55,512.00 885.55,512.00
             885.55,512.00 691.98,512.00 691.98,512.00
             691.98,412.60 611.40,332.02 512.00,332.02
             412.60,332.02 332.02,412.60 332.02,512.00 Z" />
</svg>
```

  [fa-pokeball-16]: https://cloud.githubusercontent.com/assets/1094151/17297178/9f25803a-57d2-11e6-8746-0bea27561007.png
  [fa-pokeball-32]: https://cloud.githubusercontent.com/assets/1094151/17297180/9f2950ca-57d2-11e6-9bd3-d3f15ae7aeb7.png
  [fa-pokeball-64]: https://cloud.githubusercontent.com/assets/1094151/17297177/9f256f96-57d2-11e6-86fc-6eef2ba19fee.png
  [fa-pokeball-128]: https://cloud.githubusercontent.com/assets/1094151/17293412/1d222a2a-57be-11e6-9055-87e4e9aed96d.png
  [fa-pokeball]: https://cloud.githubusercontent.com/assets/1094151/17297269/f3cd3ec0-57d2-11e6-99de-5c630cd7425e.png

  [fa-pokemon-gym-16]: https://cloud.githubusercontent.com/assets/1094151/17312517/434135a8-5821-11e6-9256-d944a94d1d68.png
  [fa-pokemon-gym-32]: https://cloud.githubusercontent.com/assets/1094151/17312516/433f8604-5821-11e6-9711-5753d70d73fa.png
  [fa-pokemon-gym-64]: https://cloud.githubusercontent.com/assets/1094151/17312515/433f31ea-5821-11e6-9308-59f0e41d2a23.png
  [fa-pokemon-gym-128]: https://cloud.githubusercontent.com/assets/1094151/17312513/43364ca6-5821-11e6-8f8b-2bf9991a9032.png
  [fa-pokemon-gym]: https://cloud.githubusercontent.com/assets/1094151/17312514/433d9830-5821-11e6-9ac6-dcdf1c93b799.png

  [fa-pokeball-alt-16]: https://cloud.githubusercontent.com/assets/1094151/17295231/1f9863ae-57c9-11e6-9250-d4cbfe806c0e.png
  [fa-pokeball-alt-32]: https://cloud.githubusercontent.com/assets/1094151/17295233/2106553e-57c9-11e6-8af5-01f25baa3276.png
  [fa-pokeball-alt-64]: https://cloud.githubusercontent.com/assets/1094151/17295235/2447ef96-57c9-11e6-98b0-b6284f65abed.png
  [fa-pokeball-alt-128]: https://cloud.githubusercontent.com/assets/1094151/17295239/25b8fd02-57c9-11e6-9f5a-8791d3428e7b.png
  [fa-pokeball-alt]: https://cloud.githubusercontent.com/assets/1094151/17295242/2748a582-57c9-11e6-9fa7-91a8c8956645.png

  [t_gym_arena_glass]: https://cloud.githubusercontent.com/assets/1094151/17598069/c82961bc-5fc6-11e6-874f-dd37ca517870.png

**Comment by Manbearpixel** [comment]
+1 Would also like to see Pokemon Go Teams (Instinct, Mystic, and Valor)

**Comment by rvdz** [comment]
+1

**Comment by romzie** [comment]
+1

**Comment by dospunk** [comment]
+1

**Comment by wardhache** [comment]
+1

**Comment by pgroot91** [comment]
+1

**Comment by Ulilop** [comment]
+1

**Comment by rock112293** [comment]
yeah slight.

**Comment by fundor333** [comment]
+1

**Comment by jrgleason** [comment]
Anyone able to link me to where I would put this in my project? Would the XML just be an SVG file? How would I add it to font awesome so I could use it with the icon attribute?

**Comment by tagliala** [comment]
Hi, I think I have to close this request because as far as I can understand, pokemon is a trademark of Nintendo

https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#582-to-590
