### ISSUE TITLE
Icon Request: fa-knight

### ISSUE THREAD

**Issue by faeb187** [FortAwesome/Font-Awesome#6801]
World needs chess icons:

fa-rook
fa-knight
fa-bishop
fa-queen
fa-king
fa-pawn

**Comment by Garrcomm** [comment]
:+1:

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1815 , please +1 that request

closing here

**Comment by fellowgeek** [comment]
+1000000
