### ISSUE TITLE
Icon Request: fa-hourglass

### ISSUE THREAD

**Issue by arthurpereira** [FortAwesome/Font-Awesome#6804]
Please, make a hourglass icon :-)

![hourglass-512](https://cloud.githubusercontent.com/assets/5242013/8285675/3c02032a-18db-11e5-86b3-9cd9cdceeb6d.png)

**Comment by kwaaui** [comment]
There is already an Icon request: icon-hourglass set #492
You should probably +1 that one

**Comment by OlenDavis** [comment]
Have you checked out https://github.com/FortAwesome/Font-Awesome/issues/492 lately? You should probably count the total +1's (and +10's) over there...oh wait, you can't **'cause it's been asked for so embarrassingly frequently**.

**Comment by tagliala** [comment]
Confirm this is a duplicate #492 

#492 is currently the most requested icon, it is scheduled for 5.0.0 release and I'm pretty sure it will be part of the set

Closing here, please +1 that request
