### ISSUE TITLE
Icon Request: fa-playslow 

### ISSUE THREAD

**Issue by donm258** [FortAwesome/Font-Awesome#6806]
I would like to have a playback button (icon) for "Play Slow".  Enclosed is a screenshot image that I combine two icons (fa-pause and fa-play). It is not pretty, and out of proportion. This image shows "two bars" on the left side and triangle-arrow on the right side.  

For new icon, I would like to have "one bar" on the left side and triangle-arrow on the right side.  Please let me know about it. Thanks.

![screenshot-play-slow](https://cloud.githubusercontent.com/assets/13006665/8292178/24360950-18fc-11e5-863a-4e39c314533d.jpg)

**Comment by tagliala** [comment]
If I remember this is a duplicate but I'm unable to find the original request at the moment

Leaving this open

**Comment by tagliala** [comment]
let's use #13490
