### ISSUE TITLE
Detecting once fonts have been loaded

### ISSUE THREAD

**Issue by aymanar** [FortAwesome/Font-Awesome#6809]
Now that the css is something like this:

@font-face{
    font-family:fontawesome;src:url(../fonts/fontawesome-webfont.eot);
    src:url(../fonts/fontawesome-webfont.eot) format('embedded-opentype'),
    url(../fonts/fontawesome-webfont.woff) format('woff'),
    url(../fonts/fontawesome-webfont.ttf) format('truetype'),
    url(../fonts/fontawesome-webfont.svg) format('svg');
    font-weight:400;font-style:normal
}

Is there a way to trigger whenever the font has been loaded? I hate the fact that the fonts are substituted by empty squares until the font has loaded, and so I want to hide them till then.

Thank you

**Comment by KOTRET** [comment]
you have to do this via javascript. Follow up this post on Stackoverflow: http://stackoverflow.com/questions/12312323/how-to-know-if-a-font-font-face-has-already-been-loaded.
_imho_ bad practice

**Comment by tagliala** [comment]
Take also a look at this one: https://github.com/typekit/webfontloader

**Comment by aymanar** [comment]
Well I ended up doing it via Javascript. I applied this rule
.fa {
    font-family: "fontawesome","Comic Sans MS","Comic Sans";
}
and with a setInterval I check the offsetWidth of a character to see once it changes.

Thanks
