### ISSUE TITLE
Icon request: icon-x-ray

### ISSUE THREAD

**Issue by gsmethells** [FortAwesome/Font-Awesome#681]
How about an icon for an X-ray film (an icon of an X-ray of a hip, for example).

**Comment by thekondrashov** [comment]
+1

**Comment by nsimeonov** [comment]
This one is great: 
![45847](https://cloud.githubusercontent.com/assets/1587815/6310848/d817b7b4-b963-11e4-876c-0e651ab57ed8.png)

**Comment by nsimeonov** [comment]
This one too: 
![image](https://cloud.githubusercontent.com/assets/1587815/6310926/7ace7cc2-b964-11e4-9c37-d196af08b2b4.png)

**Comment by sebastian301082** [comment]
+1

**Comment by gsmethells** [comment]
I like @nsimeonov's suggestion on Feb 20 with the lateral view of a knee.

**Comment by jbteague** [comment]
+1

**Comment by gsmethells** [comment]
Another option: use a Caduceus with a rectangle border and a dog-eared page corner.

![caduceus](https://cloud.githubusercontent.com/assets/3286666/9387944/88728b28-4728-11e5-90a5-df64a8f96042.jpg)

**Comment by gsmethells** [comment]
Or use a Staff of Asclepius symbol instead of a Caduceus symbol. Actually, either of those symbols would be great without a border, too, since they are medical and very general.

**Comment by Heinerion** [comment]
+1

**Comment by nxtdesigns** [comment]
+1

**Comment by gsmethells** [comment]
@davegandy here's hoping this is the year! :)

**Comment by Uniphix** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by gsmethells** [comment]
This is the year!

**Comment by seysoosey** [comment]
+1

**Comment by reastwood** [comment]
+1

**Comment by wesly--** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by andreschabur** [comment]
+1

**Comment by fariasfrancisco** [comment]
+1

**Comment by seezee** [comment]
I used the new combining feature to overlay the × and film alt icons (fa-times and fa-film-alt) to represent x-ray film. This is probably a lot more legible than the complicated designs proposed so far. If we ever get a 'bone' icon, you could use the same technique to roll your own.

**Comment by sensibleworld** [comment]
An x-ray icon is included in the latest 5.0.7 release of Font Awesome Pro: https://fontawesome.com/icons?d=gallery&q=x-ray
