### ISSUE TITLE
Getting 404 on woff2 after upgrading to 4.3.0 /w bower

### ISSUE THREAD

**Issue by robertdunaway** [FortAwesome/Font-Awesome#6811]
I was using 4.2.0 which I manually added to my project.  I'm changing over to bower.

After I added FontAwesome with bower and switch my links over to it I began getting a 404 on just one of the files.  Everything else seems to work.

I'm using Chrome in case that matters.

fontawesome-webfont.woff2?v=4.3.0     GET     404

Request URL:http://localhost:50001/dist/core/lib/bower/fontawesome/fonts/fontawesome-webfont.woff2?v=4.3.0
Request Method:GET
Status Code:404 Not Found

Thanks,
Bob

**Comment by tagliala** [comment]
I'm sorry, this should a known issue fixed in 4.3.1. I don't have a deadline for 4.3.1

This should be fixed with #5657

Let me know if this is the same issue

**Comment by robertdunaway** [comment]
That's cool.  I don't think it's actually causing a problem right now.  I look forward to 4.3.1  :)

**Comment by santina** [comment]
Thanks for asking this. I'm also having the same problem.

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
