### ISSUE TITLE
Icon Request: fa-binary (fa-bits)

### ISSUE THREAD

**Issue by jbnv** [FortAwesome/Font-Awesome#6812]
An icon with zeros and ones to represent a binary stream or file. Would look like this:

010
101

**Comment by Garrcomm** [comment]
If you mean a fa-file-binary, you get my +1 ;)

**Comment by jbnv** [comment]
No, I did not mean a binary file. This icon could be stacked on the file-o icon.

**Comment by FabianCernota** [comment]
+1

**Comment by tagliala** [comment]
I need to check old requests if there is a duplicate

**Comment by sebastiansipos90** [comment]
+1

**Comment by Bretto** [comment]
+1

**Comment by gronono** [comment]
:+1: this will be awesome

**Comment by Kondou-ger** [comment]
:+1: Here's a small 14px mockup: ![bits](https://cloud.githubusercontent.com/assets/1410802/9292911/6393d0e6-4412-11e5-8fde-e08072e76ad0.png)

**Comment by sebastiansipos90** [comment]
Nice. I think it would look better in a monospaced font. https://www.iconfinder.com/icons/298769/binary_file_icon#size=128

**Comment by baalthazaar1** [comment]
+1

**Comment by ravishivt** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by Defcon0** [comment]
+1

**Comment by shauntru** [comment]
+1

**Comment by patdunlavey** [comment]
+1

**Comment by artch** [comment]
+1

**Comment by mbaas2** [comment]
+1

**Comment by GrischaK** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by sensibleworld** [comment]
We have a few options for this in version 6: https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=binary&s=solid

<img width="871" alt="Screen Shot 2021-05-27 at 2 17 51 PM" src="https://user-images.githubusercontent.com/529604/119876854-53acd500-bef6-11eb-95fc-e1565f756559.png">
