### ISSUE TITLE
Icon request: fa-skull and cross bones

### ISSUE THREAD

**Issue by ckisker** [FortAwesome/Font-Awesome#6813]
I would love to have the skull and cross bones icon to represent a section of our site that deals with chemical cleaning and spilled material clean up.  Thank you!

![220px-skull_and_crossbones](https://cloud.githubusercontent.com/assets/13021444/8313177/2dd832fe-19af-11e5-8267-db1756174709.png)

**Comment by kwaaui** [comment]
+1
It would be a nice pirate icon.
single fa-skull and fa-bone would be nice too

**Comment by tagliala** [comment]
duplicate of #918, please +1 that request

closing here
