### ISSUE TITLE
Icon request: icon-theater

### ISSUE THREAD

**Issue by Vicnovais** [FortAwesome/Font-Awesome#6814]
Use case: this icon would be used by portfolio sites that includes jobs with theater plays or musicals. My idea is based on theater masks or curtains, as shown by the images.
![curtain](https://cloud.githubusercontent.com/assets/7889190/8315472/65850f0c-19c7-11e5-8f76-08e4c05a34c9.jpg)
![maks](https://cloud.githubusercontent.com/assets/7889190/8315473/67d46bfe-19c7-11e5-9045-df2afe21925a.png)

**Comment by kwaaui** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1270 , please +1 that request

closing here
