### ISSUE TITLE
Icon Request: Columns Grid Size

### ISSUE THREAD

**Issue by shivapoudel** [FortAwesome/Font-Awesome#6819]
Add support for the columns grid size.

![capture](https://cloud.githubusercontent.com/assets/3774827/8323602/62d5bd16-1a66-11e5-902d-64e030aa36ba.PNG)

- one-full
- one-half
- one-third
- two-third
- one-fourth
- three-fourth
- one-fifth
- two-fifth
- three-fifth
- four-fifth

**Comment by tagliala** [comment]
Sorry, but I need to close this request because it does not meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by jbethke** [comment]
+1 (Despite closed)
