### ISSUE TITLE
Icon Request: fa-testtube

### ISSUE THREAD

**Issue by Brilbroeder** [FortAwesome/Font-Awesome#6825]
a test-tube

**Comment by lekhnath** [comment]
testtube needed please

**Comment by rodryquintero** [comment]
Yes, we need test tubes: empty, half filled.

**Comment by trumbitta** [comment]
:+1: 

![](http://www.cheval-energy.com/1019-large_default/venosafe-tube-a-prelevement-terumo.jpg)

**Comment by ice12192** [comment]
+1

**Comment by amarewgs** [comment]
may laboratory icons are also important please

**Comment by rodryquintero** [comment]
+1

**Comment by kimberley-johnston** [comment]
+1

**Comment by aethior** [comment]
Hi @Brilbroeder,

[fa-vial](https://fontawesome.com/icons/vial) and [fa-vials](https://fontawesome.com/icons/vials) icons were added in v5.0.7.

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
I'm tagging as 5.13 because I do not remember if they were part of the free set in older versions of FA
