### ISSUE TITLE
Icon Request: fa-Freelancer, Elance, Upwork, Toptal, Guru, Crew, Fiverr

### ISSUE THREAD

**Issue by cnisbet13** [FortAwesome/Font-Awesome#6833]
Was wondering if icons could be made for freelancing websites: Elance.com, Freelancer.com, Upwork, Toptal, Guru, Crew, Fiverr.

**Comment by thatamazingprogrammer** [comment]
+1 for all even though you're supposed to only request one at a time.

You might want to read the "Requesting New Icons" section.

http://fontawesome.io/community/

**Comment by tagliala** [comment]
@thatamazingprogrammer thanks for pointing this out

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

there are also duplicates, elance: #3445, freelance: #6426 

closing here

**Comment by cnisbet13** [comment]
Oh shoot, I should have read through the guidelines first. Thanks for letting me know :)
