### ISSUE TITLE
Icon Request: fa-iTunes-U

### ISSUE THREAD

**Issue by SammyHerring** [FortAwesome/Font-Awesome#6834]
Dear Font-Awesome,

I would really appreciate to see the iTunes U icon appear on font awesome!

Here is the app link: https://itunes.apple.com/gb/app/itunes-u/id490217893?mt=8

Thank you in advance,

Sam

**Comment by caweyant** [comment]
Wondering what the status of this is. Any chance of making this and other iTunes icons awesome anytime soon?

**Comment by aethior** [comment]
>On June 10, 2020, Apple formally announced that iTunes U will be discontinued from the end of 2021. ([source](https://en.wikipedia.org/wiki/ITunes#iTunes_U))

cc/ @tagliala
