### ISSUE TITLE
Icon Request: fa-subway-...

### ISSUE THREAD

**Issue by Lonelind** [FortAwesome/Font-Awesome#6837]
Hi!

Today I've faced a problem, that I need to use an icon for nearest subway station on my page to let people know not only a street but station — in huge cities this is more useful than just a street mention.

I live in Moscow and recently local design studio that's working for city government to make entire city design (street plates through company signs on buildings and city transport) made a standard logo for Moscow subway (Metro as we call it). So, I thought if you could make icons for known subway logos such as London Underground, Paris Metro and Moscow Metro?

Here is a link to the download page (it is in Russian, but you could use Google Translate :) The particular logo for devices and uses in small size is available in eps format)

http://www.artlebedev.ru/everything/metro/logo/vector/

Thank you for the titanic work you made on this icon pack!

With regards,
Alex

**Comment by sha-2** [comment]
Duplication of #4038

**Comment by tagliala** [comment]
@sha-2 thanks again :)
