### ISSUE TITLE
Icon Request: fa-info-square

### ISSUE THREAD

**Issue by simondesignstudio23** [FortAwesome/Font-Awesome#6845]
Great to have an information ' i ' icon with a square background

**Comment by funkymonk91** [comment]
You can create this already with font-awesome by stacking fa-info on top of fa-square

       <span class="fa-stack fa-lg">
          <i class="fa fa-square fa-stack-2x"></i>
          <i class="fa fa-info fa-stack-1x fa-inverse"></i>
        </span>

**Comment by tagliala** [comment]
duplicate of #2403
