### ISSUE TITLE
Icon Request: fa-ebay, fa-amazon, fa-magento

### ISSUE THREAD

**Issue by wortexx** [FortAwesome/Font-Awesome#6847]
Please extend your set of the brand icons with eBay, Amazon and Magento.

Thank you in advance. Let me know if I can help you with this.

**Comment by sha-2** [comment]
Duplication of #1783 (eBay)
Duplication of #471 (Amazon)
Duplication of #1754 (Magento)

**Comment by tagliala** [comment]
@sha-2 thanks, really appreciate

closing here
