### ISSUE TITLE
Windows crashes when trying to preview 'FontAwesome.otf'

### ISSUE THREAD

**Issue by GameplayJDK** [FortAwesome/Font-Awesome#6848]
I discovered this when I tried to install FontAwesome as a font on my computer and accidentally double clicked the `.otf` file instead of using the more direct way of right clicking and choosing install.

Windows froze instantly, so I had to use the reset to restart the computer.

(I'm running Windows 8.1 Pro)

This is seems to be a issue with the preview of windows thought and I don't know if this can be reproduced on other OS' or even on other Windows systems.

**Comment by Garrcomm** [comment]
Tested opening the .otf file on two systems I currently have access to:
- Windows 7 Professional x64: no crash
- Windows 8.1 Pro x64: no crash

**Comment by tagliala** [comment]
@Garrcomm thanks for your feedback

**Comment by GameplayJDK** [comment]
@Garrcomm I though so. I didn't have the same issue with my other PC. Since I didn't find any hint on what is causing this crash, I just put it here.

**Comment by tagliala** [comment]
Closing here because of inactivity

If this is still an issue, feel free to fill out a new [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
