### ISSUE TITLE
Icon request: diameter

### ISSUE THREAD

**Issue by lennartvdd** [FortAwesome/Font-Awesome#6861]
There are some usable size icons in fa (vertical/horizontal arrows), but i'm missing a diameter icon.

**Comment by tagliala** [comment]
any example?

**Comment by lennartvdd** [comment]
![diameter](http://www.i2symbol.com/images/symbols/technical/diameter_sign_u2300_icon_128x128.png)

**Comment by tagliala** [comment]
duplicate of #5852, please +1 that request

You will also find a workaround

closing here
