### ISSUE TITLE
space necessary after <i class="fa"></i>?

### ISSUE THREAD

**Issue by Soelen** [FortAwesome/Font-Awesome#6862]
hello, I'm not sure where to ask this question, please excuse me if I posted this question on the wrong place.

how far is it necessary to add a space after you use a font awesome class inside an i element? Technically I could simply add a margin to the right in order to create a gap between the i element and the text, right? Or

**Comment by tagliala** [comment]
Hi,

you don't need to add a space but if you need some spacing between the icon and some text you can add a space (`<i class="fa fa-icon"></i> Icon Label</i>`) or add some margin in the css if you are dealing with minimized html or generated content (`<i class="fa fa-icon my-class-with-margin"></i>Icon Label</i>`), according to your needs

Hope it helps

Closing here but feel free to comment
