### ISSUE TITLE
Icon request: icon-usb

### ISSUE THREAD

**Issue by julievecchio** [FortAwesome/Font-Awesome#6863]
We would love to be able to use USB/flash drive icons on pages about file storage and transfer!

Thank you so much for your consideration (and the awesomeness of fontawesome!)!

**Comment by cojomojo** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #2165 or #6304, please +1 the proper request

if you want to request a usb dongle please let me know and I will reopen

closing here
