### ISSUE TITLE
Internal network vs. external network

### ISSUE THREAD

**Issue by littledude** [FortAwesome/Font-Awesome#6864]
Hi currently I host a testing site outside our company's network. when I review the web page at home, the Awesome fonts/icons do show up. However, when reviewing the web page at work, the fonts/icons don't show up for certain reason. Also if I test the page on my local machine at work, the fonts/icons work just fine. Once I upload the same page to the server, the fonts/icons disappear. This issue strangely only happens to IE 11 browser. I did try to turn off compatibility but still it didn't work. I suspect this is something to do with the network or firewall. However, is there something I can do at my end? Please help.

Thank you!
Kevin

**Comment by tagliala** [comment]
Hi, since this is a support request you should consider stackoverflow and provide more details (if you are using a cdn or self-hosted fonts, if there are any restrictions, if there are any error in the ie console...).

Closing here
