### ISSUE TITLE
Icon Request: ownership history or provenance

### ISSUE THREAD

**Issue by kuhooe** [FortAwesome/Font-Awesome#6866]
Can we have an icon that shows the history of something - like if something was copied from an original. i was thinking of 3 squares with arrows (left to right) between them
![image](https://cloud.githubusercontent.com/assets/13167260/8500898/6eda077a-216e-11e5-9906-65737d356000.png)

**Comment by tagliala** [comment]
I'm going to consider this closed by https://fontawesome.com/icons/clock-rotate-left?s=solid

Font Awesome Pro also has https://fontawesome.com/icons/rectangle-history?s=solid

I'm closing here for inactivity, but feel free to fill out our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
