### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by charleshbateman** [FortAwesome/Font-Awesome#6867]
How about a travel advisor icon?

**Comment by tagliala** [comment]
travel advisor = tripadvisor?

**Comment by aethior** [comment]
@tagliala I think you can close here. In all case `fa-tripadvisor` (http://fontawesome.io/icon/tripadvisor/) icon already exists.

**Comment by tagliala** [comment]
@aethior thansk for checking out all this stuff
