### ISSUE TITLE
Icon Request: fa-lowercase, fa-uppercase

### ISSUE THREAD

**Issue by SylvainCorlay** [FortAwesome/Font-Awesome#6870]
![lowercase](https://cloud.githubusercontent.com/assets/2397974/8505042/8b0afd82-21aa-11e5-8602-8c300ec312c7.png)

Two versions of the icon, one with a caret-up and and one with a caret down could make the distinction between the two.

**Comment by matthewmorrone1** [comment]
bump

**Comment by jabronus** [comment]
Thanks for requesting an icon! But this is very similar to #7887 , so I'm closing this one.
