### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by OJFord** [FortAwesome/Font-Awesome#6875]
Icon for [Goodreads](https://www.goodreads.com/), something like:

![lower-case 'g'](https://cdn4.iconfinder.com/data/icons/miu-black-social-2/60/goodreads-128.png)

Would be used in linking to profile on Goodreads.

**Comment by tagliala** [comment]
duplicate of #1715 , please +1 that request

closing here

**Comment by OJFord** [comment]
Whoops, sorry I searched for "fa-goodreads", and so missed the other one ("icon-goodreads").
