### ISSUE TITLE
Workflow issue with photoshop

### ISSUE THREAD

**Issue by nicobrinkkemper** [FortAwesome/Font-Awesome#6876]
When designing a website I find that it's sometimes easier to paste the icon inside a photoshop textbox and set font awesome as font. That way, the icon in your photoshop document will be a good representation of what it would look like in a browser (and which font-size it should get in css)

Right now my workflow is to copy paste the unicode in google and most of the times something like this shows up first: http://www.utf8icons.com/character/61441/UTF-8-character. Wouldn't it be a better workflow if such a char could be copy/pasted straight from font-awesome/fonticons. It would also be a good hint for designers!

**Comment by tagliala** [comment]
I'm not sure I got this issue... Do you need a cheatsheet like this: http://fontawesome.io/cheatsheet/ ?

**Comment by nicobrinkkemper** [comment]
I guess I was hoping for a "copy to clipboard" feature on the detail page (like here http://fontawesome.io/icon/pinterest-p/)

But this will do just fine! Thanks!

**Comment by tagliala** [comment]
got it, so it should be a duplicate of #1034
