### ISSUE TITLE
Icon Request: fa-Golf

### ISSUE THREAD

**Issue by tamisandoval** [FortAwesome/Font-Awesome#6877]
Hi! thanks for let us ask for new icons... im building my web with Hotel Master Theme and i noticed there are not so many "hotel, resort" icons. For example a need to indicate that my hotel is close to a golf course and a ski resort, would you help me? Thanks! Greetings from Argentina.

Tami

**Comment by tagliala** [comment]
duplicate of #5348, please +1 that request

closing here
