### ISSUE TITLE
Icon Request: fa-ski

### ISSUE THREAD

**Issue by tamisandoval** [FortAwesome/Font-Awesome#6878]
Hi! thanks for let us ask for new icons... im building my web with Hotel Master Theme and i noticed there are not so many "hotel, resort" icons. For example a need to indicate that my hotel is close to a ski resort, would you help me? I was thinking that a Ski icon would be just right! or something with snow, even a Snowflake or a snowy mountain. Thanks! Greetings from Argentina.

Tami

**Comment by blomdahldaniel** [comment]
+1

**Comment by Marc-pi** [comment]
+ 1
we have in FA icons for rockets for the moon, why not snow transportation icons ! 
Would be a nice addition to have those :
* chair lift, 
* ski lift, 
* snowmobile, 
* cabel car
* ski
* snowboard
* snowshoeing

**Comment by MVcodeartbr** [comment]
+1

**Comment by Gabriel82** [comment]
+1

**Comment by twohumans** [comment]
+1

**Comment by hubertron** [comment]
+1

**Comment by francescos123** [comment]
+1

**Comment by atyutrin** [comment]
+1

**Comment by swissalexx** [comment]
Afree 100% with Marc-pi, snow/winter resort transportation icons would be a very nice addition to Font Awasome :)

    chair lift,
    ski lift,
    cabel car
    skier
    snowboarder

**Comment by hannesdmz** [comment]
+1

**Comment by Robin-Hoodie** [comment]
+1

**Comment by zettvs** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by Jacqbus** [comment]
+1

**Comment by futureweb** [comment]
+1

we would also desperately need this ... 3 years since it was requested and still nothing ... 👎

**Comment by aaronbeaton** [comment]
+1

**Comment by futureweb** [comment]
Already contacted Font Awesome because of this ... didn't sound like they are going to add such an Icon anytime soon ...

> Hi there,
> We'll add icons as we have time to get to them and by priority. Unfortunately we can't make any promises regarding when they will be done.
> -- Rob and the FA Team

**Comment by davepe** [comment]
+1

**Comment by tienvooracht** [comment]
+1

**Comment by tommygaessler** [comment]
+1

**Comment by sensibleworld** [comment]
We have a few options for this now: https://fontawesome.com/icons?d=gallery&q=ski
