### ISSUE TITLE
Icons Request: fa-heart-circle and fa-heart-circle-o

### ISSUE THREAD

**Issue by DOBss** [FortAwesome/Font-Awesome#6880]
Hi!

Please can you add icons like fa-times-circle and fa-times-circle-o but with the hearth icon inside? I am working on the second template where there is an icon like http://prntscr.com/7p5ops and I have to use svg background.

Thank you =]

**Comment by aethior** [comment]
Hi @DOBss,

This icon was added in v5.0.9.
Check https://fontawesome.com/v6/icons/circle-heart

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to FA Pro

FA Free users, **in a web application**, can create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/58/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
