### ISSUE TITLE
Icon Request: fa-bar-line-chart

### ISSUE THREAD

**Issue by DOBss** [FortAwesome/Font-Awesome#6881]
Hi!

Please can you add this icon?
![bar-line-chart](http://i.imgur.com/qJNF6sV.png)

And it would be also fine to make icons like fa-area-chart, fa-bar-chart and fa-line-chart but each WITHOUT the x and y axis (lines on left and bottom) just like my requested icon.

Thank you =]

**Comment by edpichler** [comment]
This already exists.
http://fortawesome.github.io/Font-Awesome/icon/line-chart/
http://fortawesome.github.io/Font-Awesome/icon/bar-chart/

**Comment by DOBss** [comment]
@edpichler not at all. I mentioned these icons in the request - I would like to have these two you mentioned without the axis... and the requested icon on the image is the combination of line and bar chart and the bar part is going up linear.

**Comment by tagliala** [comment]
You request is legit, but if you need this exact icon you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by edpichler** [comment]
@DOBss ok got it.

**Comment by G-Driver** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by sensibleworld** [comment]
Thanks for the request! This icon now exists. 
 
 https://fontawesome.com/v6.0/icons/chart-mixed?s=solid
 
 <img width="1005" alt="Screen Shot 2021-05-27 at 1 42 11 PM" src="https://user-images.githubusercontent.com/529604/119872330-5822bf00-bef1-11eb-8787-6413753e6470.png">
