### ISSUE TITLE
New icon request fa:industry or fa:factory

### ISSUE THREAD

**Issue by edpichler** [FortAwesome/Font-Awesome#6882]
I need an icon that represents the factory/industry idea:

![captura_de_tela_070615_095605_am](https://cloud.githubusercontent.com/assets/358696/8522510/38e414ea-23c5-11e5-93cc-9d80f52f3398.jpg)

**Comment by mattjacobsen** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1330 , please +1 that request

closing here
