### ISSUE TITLE
Icon Request: fa-plus-minus

### ISSUE THREAD

**Issue by jcarenza** [FortAwesome/Font-Awesome#6885]
I'd like to request a new icon, **fa-plus-minus**. The icon itself would look like this: **+/-**

_Use Case:_ I have a screen where users manage lists of items. Currently, I use an 'edit' icon (fa-pencil) that changes the UI so that the user can manage that list (add items or remove items). I've found from a lot of user feedback that the 'edit' icon is somewhat confusing. For whatever reason they believe the 'edit' icon is for renaming things and not for adding/removing things. I think this new icon would be much clearer for uses like this.

**Comment by ameesme** [comment]
+1

**Comment by aerichmond** [comment]
+1

**Comment by maverick42** [comment]
+1

**Comment by Ishangidwani** [comment]
+1

**Comment by j3rm** [comment]
+1

**Comment by konuch** [comment]
+1

**Comment by susanmoulton** [comment]
+1

**Comment by m3mo89** [comment]
+1

**Comment by kincaider** [comment]
+1

**Comment by fmouth** [comment]
+1

**Comment by SergoQA** [comment]
+1

**Comment by mariovelandia** [comment]
+1

**Comment by Blindsyde** [comment]
+1

**Comment by Nicobile** [comment]
+1

**Comment by MEChasle** [comment]
+1

**Comment by gangstead** [comment]
± 1

**Comment by abaar** [comment]
+1

**Comment by jonrz** [comment]
+1

**Comment by flopibaka** [comment]
+1

**Comment by PinkMeNow** [comment]
+1

**Comment by skbly7** [comment]
+1

**Comment by sowenjub** [comment]
This can be achieved using the new power transforms + stacks

```
<span class="fa-stack fa-2x">
    <i class="fas fa-plus fa-stack-1x" data-fa-transform="shrink-8 up-3"></i>
    <i class="fas fa-minus fa-stack-1x" data-fa-transform="shrink-8 down-3"></i>
</span>
```

**Comment by MEChasle** [comment]
@sowenjub, thanks for the tip.

With your solution, I get 
![before](https://user-images.githubusercontent.com/14162408/77046574-86d70880-69c3-11ea-8c02-7c2af4228af8.png)

With [documentation](https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons) and few adaptations, I get
![after](https://user-images.githubusercontent.com/14162408/77046746-d289b200-69c3-11ea-9aa0-a5d1790560c6.png)

```
<span class="fa-stack" style="font-size: 0.5em;">
    <i class="fas fa-plus fa-stack-1x" data-fa-transform="grow-5 up-7"></i>
    <i class="fas fa-minus fa-stack-1x" data-fa-transform="grow-5 down-10"></i>
</span>
```

**Comment by sowenjub** [comment]
@MEChasle This is probably better. I got the same issue but didn't investigate because I changed my mind and used text instead. Glad the tip helped :)

**Comment by Azbesciak** [comment]
Maybe +/- also?

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
