### ISSUE TITLE
Icon Request: icon-zhihu

### ISSUE THREAD

**Issue by Voyga** [FortAwesome/Font-Awesome#6886]
[Zhihu](http://www.zhihu.com/) is like Quora in China, the brand icon is very demanding.
![snip20150707_10](https://cloud.githubusercontent.com/assets/9929523/8537313/e3a63406-248f-11e5-88e2-04cebd34cb8a.png)

**Comment by tagliala** [comment]
dup of #4439, please +1 that request

closing here

**Comment by Joysr** [comment]
+1
