### ISSUE TITLE
Icons are not smooth in Chrome but in IE and Firefox they look well

### ISSUE THREAD

**Issue by ingwarz** [FortAwesome/Font-Awesome#6893]
Hello, I use font-awesome icons on my website but for some reason not all of them look smooth. I have attached 2 images showing them on Chrome and on IE. I would like to know if it is possible to fix. Thank you. 

Google Chrome:
![image](https://cloud.githubusercontent.com/assets/13223300/8551638/8a8e9e20-24e0-11e5-816b-4b4f2422f604.png)

Internet Explorer: 
![image](https://cloud.githubusercontent.com/assets/13223300/8551654/9d5e6f94-24e0-11e5-9198-a842629a4a2d.png)

**Comment by tagliala** [comment]
cannot confirm. OS? browser version? fontawesome version? font-size? could you please provide a fiddle showing the issue? You can use this one as a base:  http://jsfiddle.net/tagliala/e9yfxsfj/
