### ISSUE TITLE
Icon Request: fa-MassRoots

### ISSUE THREAD

**Issue by mworster11** [FortAwesome/Font-Awesome#6894]
I would like to use this MassRoots icon with other "square" social media icons in the header and footer of my site. 

<img width="216" alt="massrootsicon" src="https://cloud.githubusercontent.com/assets/8197941/8552472/8707e0c2-249a-11e5-853d-b33dbaeb0679.png">

**Comment by tagliala** [comment]
duplicate of #6581, please +1 that request

closing here
