### ISSUE TITLE
Request: icons indicating the measure of weights, lengths

### ISSUE THREAD

**Issue by Splik** [FortAwesome/Font-Awesome#6895]
Please add some icons indicating the measure of weights, lengths. Look like a barbell, dumbbell kettlebell, weight, fishing sinker, weighing scale, ruler, tape measure

**Comment by tagliala** [comment]
ruler: #1096 , please +1 that request
dumbbell: #1500 , please +1 that request

If you want to request other icons, please open new requests following contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

closing here
