### ISSUE TITLE
Icon Request: fa-cluster

### ISSUE THREAD

**Issue by danhalligan** [FortAwesome/Font-Awesome#6896]
Hi,

Firstly thanks for the (awesome) font-awesome icons. If possible I'd like to request a "cluster" or "network" icon. Some similar examples / inspiration:
the iGraph icon: http://igraph.org/
glyphicons-cluster here: http://glyphicons.com/

Many thanks,
Dan

**Comment by tagliala** [comment]
This may be considered a duplicate of #4523

**Comment by danhalligan** [comment]
I'm hoping to use the icon for a link to a network graph, such as this: http://bl.ocks.org/mbostock/4062045
whereas this icon: http://fontawesome.io/icon/sitemap/ suggests a hierarchical network of e.g. computers / hosts. Perhaps the distinction is somewhat subtle, but I would add a vote for a better network graph icon. Some of the icons suggested in the comments for issue #4523 do fit this bill. As such this can be considered a duplicate, and for that reason, I've added a +1 to issue #4523. Thanks for pointing this out!
