### ISSUE TITLE
Icon Request: icon-hand-rock, icon-hand-paper, icon-hand-scissor

### ISSUE THREAD

**Issue by ajunior** [FortAwesome/Font-Awesome#6899]
https://en.wikipedia.org/wiki/Rock-paper-scissors

An icon for each shape of rock-paper-scissor hand game.
https://en.wikipedia.org/wiki/File:Rock-paper-scissors.svg

**Comment by tagliala** [comment]
Added in 4.4.0

Closing here :)

**Comment by richardtallent** [comment]
Kudos for adding Spock and Lizard as well! ;)
