### ISSUE TITLE
Icon request: icon-deposit

### ISSUE THREAD

**Issue by darshanj** [FortAwesome/Font-Awesome#6901]
I would like to use this icon for deposit money from bank.

**Comment by tagliala** [comment]
any example?

**Comment by darshanj** [comment]
like https://www.iconfinder.com/icons/337251/deposit_gain_income_money_payment_percent_profit_icon#size=128
or First image in http://www.thinkstockphotos.ca/image/stock-illustration-set-of-money-finance-banking-icons/520941849

**Comment by sensibleworld** [comment]
We have a handful of icons that might work for this now: https://fontawesome.com/search?q=money&o=r&s=solid&f=classic
