### ISSUE TITLE
Icon request: icon-google-play

### ISSUE THREAD

**Issue by robmarston** [FortAwesome/Font-Awesome#6903]
I'd like to request a Google Play icon. I would use the icon as a hyperlink to downloadable content at http://play.google.com. The icon would most likely be a flat, single-color vector representing the signature triangle/play symbol seen here:

![Image of Google Play logo](https://www.gstatic.com/android/market_images/web/play_logo_x2.png)

**Comment by tagliala** [comment]
duplicate of #2272 , please +1 that request

closing here

**Comment by baixiongmao** [comment]
nice +1
