### ISSUE TITLE
Icon request: icon-baby

### ISSUE THREAD

**Issue by danaspiegel** [FortAwesome/Font-Awesome#691]
Similar to the person silhouette, but of a child or baby

**Comment by stevehobbsPB** [comment]
+1

**Comment by danbettles** [comment]
+1

**Comment by rosieks** [comment]
+1

**Comment by annachu** [comment]
+1 Thanks!

**Comment by desix75** [comment]
+1

**Comment by Leopoldishe** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by laemol** [comment]
+1

**Comment by Vmadmax** [comment]
![1](https://icomoon.io/icons2316/0/297.png)
![2](https://icomoon.io/icons2316/0/298.png)
![3](https://icomoon.io/icons2316/0/299.png)
![4](https://icomoon.io/icons2316/0/300.png)
Or something else
+1

**Comment by G-Driver** [comment]
@Vmadmax there's already a request for the baby milk bottle https://github.com/FortAwesome/Font-Awesome/issues/5051

**Comment by nikkiroylance** [comment]
+1

**Comment by oddityoverseer13** [comment]
+1 I like the one @respectyoda included a year ago.

**Comment by AntonRand** [comment]
+1

**Comment by Willswain** [comment]
Absolutely +1

**Comment by jpsantos7** [comment]
+1

**Comment by rolandkal** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by dwisetiyadi** [comment]
+1

**Comment by reneseses** [comment]
+1

**Comment by jbnv** [comment]
+1

**Comment by jacqueskang** [comment]
+1

**Comment by accnops** [comment]
+1

**Comment by pitkiwi** [comment]
+1

**Comment by serkanalgl** [comment]
+1 and +1

**Comment by yurik94** [comment]
+1

**Comment by Kharkin** [comment]
![image](https://cloud.githubusercontent.com/assets/20013630/16170997/49c5107e-356d-11e6-94c8-88a043a02537.png)
+1 
Thank you in advance :-)

**Comment by fusion27** [comment]
:+1:

**Comment by mcbeelen** [comment]
+1

**Comment by candioto** [comment]
+1

**Comment by eliland** [comment]
+1

**Comment by laurentiuc** [comment]
+1

**Comment by SOFTWORK** [comment]
+1

**Comment by mohammadmojrian** [comment]
+1

**Comment by tseshevsky** [comment]
+1

**Comment by Brieg** [comment]
+`1

**Comment by KnutHelland** [comment]
+1

**Comment by svyoung** [comment]
+ 1

**Comment by jtm235** [comment]
+1

**Comment by reinchek** [comment]
+1

**Comment by dyetube** [comment]
+1

**Comment by eranbaazov** [comment]
+1

**Comment by johntrandall** [comment]
+1

**Comment by zelll** [comment]
+1

**Comment by leonardo1024** [comment]
I also need baby icon

**Comment by vpont** [comment]
+1

**Comment by Oneilos** [comment]
+1

**Comment by stefkes** [comment]
+1

**Comment by Ride2Fullstack** [comment]
+1

**Comment by EttinCon** [comment]
+100

I'm making maps of venues for our events and there's a baby change station!

**Comment by ckosmowski** [comment]
+1

**Comment by jensens** [comment]
:+1:

**Comment by mbrod90** [comment]
Can there be an icon for a baby carriage? something like this 
https://www.google.com/search?q=baby+carriage+vector&source=lnms&tbm=isch&sa=X&ved=0ahUKEwirwK779sjYAhVNNd8KHQo9DP8Q_AUICigB&biw=1680&bih=801#imgdii=4ND3yHXq6OOLEM:&imgrc=V2PXTUJEHlndMM:

**Comment by UlrichFrancomme** [comment]
👍

**Comment by einavsh** [comment]
+1 for baby, 
+1 for baby stroller/carriage

**Comment by MrRod** [comment]
+ 1!

**Comment by bigbadwoolfe** [comment]
+1

![image](https://user-images.githubusercontent.com/1448465/42256296-74fedad4-7f1e-11e8-92bb-d0a0595a7bbb.png)

**Comment by imaqma** [comment]
+1

**Comment by hippiechik521** [comment]
+1

**Comment by timwills123** [comment]
+1

**Comment by kirancheema** [comment]
![01-nhs109_icon set_white_260917_a_neonatal support](https://user-images.githubusercontent.com/9959732/45231561-3fe35f80-b2c4-11e8-8c6e-6bce9f7d71ed.png)

**Comment by pystucki** [comment]
+1

![baby-icon](https://cloud.githubusercontent.com/assets/3604751/2745408/bff7703c-c735-11e3-89ae-40fa21be9434.png)

**Comment by shaedrich** [comment]
Maybe something like this:
![image](https://user-images.githubusercontent.com/11225821/48665155-301b9080-ea56-11e8-9378-fc2d441c3995.png)

**Comment by Crissov** [comment]
Related Unicode emojis #222:

- [👶](https://emojipedia.org/baby/)  U+1F476 BABY
- [🚼](https://emojipedia.org/baby-symbol/) U+1F6BC BABY SYMBOL
