### ISSUE TITLE
Icon request: fa-facebook-messenger

### ISSUE THREAD

**Issue by sebastialonso** [FortAwesome/Font-Awesome#6912]
I'd like to use the [Facebook Messenger](https://play.google.com/store/apps/details?id=com.facebook.orca&hl=en) icon, since my app is sharing content through it and I'm counting the stats :)

**Comment by romaricdrigon** [comment]
+1, would really be useful since Fb is pushing a lot for Messenger usage!

**Comment by maxamaxim** [comment]
+1

**Comment by davidapple** [comment]
+1

**Comment by endor** [comment]
+1

**Comment by odimodugno** [comment]
Same here :+1:

**Comment by AndreiEzhov** [comment]
+1

**Comment by avves** [comment]
+1

**Comment by alfiedawes** [comment]
+1, this would be good. I think we're going to start to see a lot more messenger buttons across the web.

**Comment by codyn329** [comment]
+1

**Comment by dmland** [comment]
+1 Went looking for this icon in the latest FA, assuming it would be there, because FB is trying to make Messenger the "dial tone" of social support.

**Comment by oliverviljamaa** [comment]
+1

**Comment by chr1s1** [comment]
+1

**Comment by guns2410** [comment]
+1

**Comment by rique1302** [comment]
+1

**Comment by huuphat** [comment]
+1

**Comment by wasniowski** [comment]
+1

**Comment by soly2014** [comment]
me too

**Comment by mpbuijs** [comment]
+1

**Comment by GermanKiwi** [comment]
+1 for me.

Facebook now gives FB Page owners a special "Messaging Link" in the format of http://fb.me/msg/abcdef (where abcdef is your Page profile name), which you can stick on your website - it lets your site visitors get direct access to sending a message to your FB Page via Messenger. This would go perfectly with a Messenger icon from Font Awesome! :)

**Comment by 3x14159265** [comment]
+1

**Comment by jcurtinca** [comment]
+1

**Comment by mebibou** [comment]
+1

**Comment by robertbastian** [comment]
+1

**Comment by alexdlaird** [comment]
+1

**Comment by isfak** [comment]
+1

**Comment by mpociot** [comment]
+1

**Comment by martynjt** [comment]
+1

**Comment by mendrik** [comment]
+1

**Comment by snowbreeze** [comment]
+1

**Comment by radosdaniel** [comment]
+1

**Comment by DiMaNacho** [comment]
+1

**Comment by GermanKiwi** [comment]
+1

**Comment by shawneric** [comment]
Why the heck isn't this done yet? OBVIOUSLY people want it, and with the new facebook messenger bots coming out, you should have done this ages ago. Seriously you could do this in like five minutes >_>

**Comment by jslee1301** [comment]
+1

**Comment by mcparrish** [comment]
+1

**Comment by vinch** [comment]
+1

**Comment by Maxxb12** [comment]
+1 Need this asap

**Comment by ArmyArmyCz** [comment]
+1

**Comment by huangdun** [comment]
+1

**Comment by akash-d** [comment]
+1

**Comment by serradino** [comment]
+1

**Comment by Rafass** [comment]
+1388

**Comment by Rafass** [comment]
This is the SVG icon: https://worldvectorlogo.com/logo/facebook-messenger

**Comment by mahasneh** [comment]
+1

**Comment by devchakraborty** [comment]
+1

**Comment by otech47** [comment]
+1

**Comment by JonGiamp** [comment]
+1

**Comment by andrewqtran** [comment]
+1

there's even a shorter link for individual user:
m.me/username

**Comment by huntg** [comment]
+1

**Comment by simonefalcini** [comment]
+1

**Comment by enron92** [comment]
+1

**Comment by dougkillmer** [comment]
+1

**Comment by ShavidzeT** [comment]
+1 We need a messenger icon ))

**Comment by chrisdeeming** [comment]
+1

**Comment by thiagocatarse** [comment]
+1

**Comment by luisofribeiro** [comment]
+1

**Comment by arekssu** [comment]
+1000

**Comment by titounet** [comment]
+1

**Comment by hhhonzik** [comment]
+1

**Comment by castroalves** [comment]
+1

**Comment by ivokys** [comment]
+1

**Comment by LoisBritto** [comment]
+1

**Comment by hankfdh** [comment]
+1

**Comment by matrush** [comment]
👍

**Comment by aneeshjajodia** [comment]
+1

**Comment by ViktorSml** [comment]
+1

**Comment by siestetix** [comment]
+1

**Comment by 98edoardo** [comment]
+1

**Comment by anikets** [comment]
+1

**Comment by dankerizer** [comment]
+1

**Comment by seedprod** [comment]
+1

**Comment by adamjace** [comment]
+1

**Comment by pierrebrocart** [comment]
+1

**Comment by justinbasile** [comment]
+1

**Comment by iamjosaguiar** [comment]
+1

**Comment by oecsike366** [comment]
+1

**Comment by vicenteguerra** [comment]
+1

**Comment by Ruud68** [comment]
+1

**Comment by tabalinas** [comment]
+1

**Comment by JGoillot** [comment]
+1

**Comment by aaronjpitts** [comment]
+1

**Comment by JohnSZas** [comment]
+1

**Comment by adrienfr** [comment]
+1

**Comment by pittkost** [comment]
+1

**Comment by skylarkcob** [comment]
+1

**Comment by zeroby0** [comment]
+1

**Comment by TrillCyborg** [comment]
+1

**Comment by IMM0rtalis** [comment]
+1

**Comment by hazio** [comment]
+1

**Comment by kintendo** [comment]
+1

**Comment by tcbmedia** [comment]
+1

**Comment by paslit** [comment]
+1

**Comment by kiarov** [comment]
+1

**Comment by noahspoke** [comment]
+1

**Comment by AnantharamanG2** [comment]
+1

**Comment by antwortzeit** [comment]
+1

**Comment by luisreyes** [comment]
+1 Why haven't you guys added this already!?

**Comment by TrillCyborg** [comment]
@luisreyes https://www.kickstarter.com/projects/232193852/font-awesome-5

**Comment by Zaanmedia** [comment]
+1

**Comment by rossbg** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by finestpixels** [comment]
+1

**Comment by rbraband** [comment]
+1

**Comment by sh-guti** [comment]
+1

**Comment by sh-guti** [comment]
+1

**Comment by SamuelMoraesF** [comment]
+1

**Comment by jpmaligne** [comment]
+1

**Comment by kylebebak** [comment]
+1

**Comment by tigusigalpa** [comment]
+1

**Comment by Noc2** [comment]
+1

**Comment by milworm** [comment]
Hey, so is there any update on this issue?

**Comment by SoulArcangel77** [comment]
Hello,
why the messenger icon has not been added yet? (sorry for my english!) :P

**Comment by positiveflat** [comment]
+1

**Comment by doliG** [comment]
+1

**Comment by Subhash-Balla** [comment]
+ 1

**Comment by Subhash-Balla** [comment]
+1

**Comment by lodi-g** [comment]
+1

**Comment by pratik0809** [comment]
+1

**Comment by sanddevil** [comment]
+1

**Comment by datarc** [comment]
+1

**Comment by csiviter** [comment]
+1

**Comment by georgeportillo** [comment]
+1

**Comment by enochN** [comment]
+1

**Comment by rudolfschmidt** [comment]
+1

**Comment by amaboura** [comment]
+1, Seriously guys! this is a no brainer.

**Comment by mo2men1** [comment]
+1

**Comment by vinch** [comment]
I'm wondering how many +1s they will need to make a move.
I know this is open source, I know this is free, but at some point (after almost 2 years), maybe it's time to listen to the users. That doesn't make me want to $40 for Font Awesome 5 Pro.

**Comment by luisreyes** [comment]
I've given up on this whole library. "Make your own" is what I'd say. Icomoon or svgs...

**Comment by rtravessini** [comment]
+1

**Comment by syakasyaka** [comment]
+1

**Comment by dmland** [comment]
Rather than waiting, I have been locally extending FontAwesome. It's burdensome, but at least the work gets done:

1. Obtain a copy of the logo you want … for example, this one:

**Comment by dmland** [comment]
In the meanwhile, you can use the following CSS, adjusting the background color (which colors the icon itself, via `background-blend-mode: color-dodge;`) and the width and height (which, if you use rem units in your project, should be set to the desired font-size).

_Note that the font-awesome-styled classname is_ `fa-temp-messenger` _to avoid colliding with the final version when it comes around:_

```
i.fa.fa-temp-messenger::before {
  content: "";
  display: inline-block;
  width: 1.0rem; /* Set to your font-size */
  height: 1.0rem; /* Set to your font-size */
  position: relative;
  top: 1px;
  background-blend-mode: color-dodge;
  background: rgb(114, 144, 201) /* set to your font color */ url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABBCAYAAABhNaJ7AAAACXBIWXMAABcSAAAXEgFnn9JSAAAJM0lEQVR4nNxbZ2hUWRR+MbFFWcsKsaDgDxdBdP2h+GujEURYXWzLxqgoKEqCHctaYkmwZ38osYFYgm0VFdG1NzD6R2zY0NUkRuy9dz0733XP87w79828mXmTMV44mcl99953zrmn3zvWp0+fCO3z588KZMMz7uPnXv+X7fnz53Tz5k26dPEi7dm7l5YsWUKjR42i+nXrUt0f6tCowHf07dmzhy4GxmAs5uhNri3fx3i64a+DbJafDOD2+vVrKi0tpX927qS5c+bQoEGDKNWqSZZleYaBAwfSnMDcnYE1SktK1Zo6MyqcAeEYcuPGDdq8eTPl5OS4EJZEVapUcSVaPUtKMj7Lzs5Ra98oLw/CKSYG6ASZuBxqx/GSS5cu0fz586lxo0YOpKtWrRrRrptAX6NhWhrNmzdPvVPfPDf848IAtJKSEiWmEsEaNWrETLQb6GvPnj2brl275sBX//RdBdBevHhB69evpzp16tjIVKtWLW6E6yDfVTPwfd26dQonSbzEP5SBtliH3EDX/cuXL9OQIUMqZMcjkYjBgwcr3ORmSvzd7IHl9kBOZG4eOHCAatWqpV6YWis1pEGrKAAOjBNg//79DpzDMcFyI16K/IcPH6ioqOir2NWMzKVVBEic1qxZo3AOZQc8SQATjyDFpH/fGkjcFhcWemKCqw1A+/jxIy1btsxeNCUlJeFEhgOJIzYONOjBkmcV2LhxY6UiniE5Odn+Dm8VVgJMfv5Y8TF7kaqViHjThh09etQ2ikY3qBu969ev089t2qjJ1atXTzgx0QLj3qpVKyorKzPagyAj+PbtW/pz4kQ1MTU1NeFExApMw/jx4xVtOhMcKoC2N5CuYkJycuUTezfgfGL37t1B0aIl9f7hw4fUpUsXNThFGJLKDmwUO3fuTA8ePHBIgSXdHlv970H0dWCa4BWkFNgqgN0HhxKNaLyhU6dOthQ4GIByFAZ8i2GuX8C07dq1y5YCiy0/6nJ4mORSkfnWQeLtRgP3jxgxQtGsGABOoH4XbwT1eKJ27dq+rS1tVr169TzNQTFHqQD+bN++XXXGK9GR66LIydIWKxNqinpA5h+ZNC03l+qHYQDjsm3btq8MyMvLi9vOy5oecnW0e/fu0YABA1SfzOWjYWijhg3p74D3OnPmDPXt21f1eVHjGTNmfFGBx48fU69eveJCvIzHd+zY4XA/t27dot/79ImICXpChkIszhAe3L8fMUN79OhBjx49Igtxf7yJ37RpkzHhKi8vp65du6oxoWIPVH2kdxo3bhydP39erfHkyRN17hCNNCnaT548aeRuLCDTUVRnQtXnr1y5Qh3T041MSNL6+vfrR8XFxfTu3Tub+OHDh3+ZGyDeqwdjWk+cOEHW5sDuqJf55P4k8ShIvH//Pij+ltKAduHCBWrfvr2awzstC54IXqBC8rgM3ydPnmzPiQZ/RIXWgoAe+bXzEFXm7oIFC+jNmzcKWVlV1hnA/TBiLVu2dKzXuHFjWrVqFd0P6Lhsr169UmcCGAP3Gm1xdg7WGDNmjG/E865Nnz6dXr58aSTUJAH8CZFkC4/TH8QncjwaxH/hwoVfpC3A7Fgq07179yaLdSgWgPixro4dO5aePXvmQFoSb/ou+8CEU6dOOao3/Bz1vRUrVjiYHgveGZ0yyJo1a1bMxLP1HTp0qHIt+g6joV9PRfWDF505OuAEiN+b7EO6Dkm1itYUxbQIE98vK8vWVanzsAOHDh2ibr92oz4Bv3/37l1XAt08BdrWrVt9JR6wcuVKso4fPx71okz8b9270+3bt4PE9fTp06SrGHw2Um83+2DqQyWH5/vhrplWFEutaBMh1vmMjAy6/n/BkdvVf69Sfl6+PRaGDYgzw4YNG6Z8uElVdAZAengdP47bJSAhsiC2ICKSieyr27VrpwIZbnfu3KHly5Y7xkqkpb1AQqQbS50hx459Lc37naj9Egi+kJNYENVJkyZ5nsiursVPP9nh6NOnT2nLli3UoUOHoHE6wHKz9EyYMMHhLuUnItQmTZqocfEozaPyjaMzlQ2uXbtWdYbTLyaqUVqaClywwOHDh7/4U001QoGMGZCJ8v0fGRm2bds2JCOjBaYRh71oigG4bhJuIhuONq1b05EjR+jcuXM0auRIB+GR+GWM5TURjXLUiBsfHTt2VP3xLM/hNppiALiO2xWcToYDXIn5q6DA/h86Hq1llp5n6dKlyp707NnTsyRFC/0CSRXnFfYdoQ0bNoQVuWbNmlGLFi3s//0wTJIJiP3xGU2RxAswbQioWOXsqjCuuDVt2tQTon6fFMu1q8X5LDItYL9Qh+DmOBhZtGiRGvQ9lsZ595FISYPrOBpDhYTFMOkbQNpvaPBjg6BT4qDDUb4L9D0djzEtq1evJr1ZeiaGEJWLlYm8AucXMA2IVVAA1sNtS6akLA1IYngBvzKvRIDEHTUGnXjjFRlu7Bbh6irjcRlsGIfQ0u0FqYBbDo5iJt8DjpdfjicwzqgdysKsUQLcrskhWsLVksrGBMYV5weccYa8KmtSAf6OUhYXTiON9ysa5LXZ0aNHB5XnjCoQ7rY4e4apU6faL/K7MOEHSJymTJkSVHBxZUC4mhwzASnr4sWLE06oCWTkWlhYaKfX+gVpk6pbpsqsXrVlziH/Rzkr0QQzpIhzgebNm9O+fftULZJ33tNt8Uh/MOHXQUosIKtKAFS0TIconn8woYuHSQIA4C5fbkgEILCpLqJTRHcomvJhqY5vKOm2JUDusM4hvS8RDEAQptcEMzMz1U0T1CJ1Q2fC35MEuBnASCXArVYQSQ3BNBY6PnPmTFUplqfEpp/2uOFvYoRvDNAvMSCAKigoUOWnaHc/KytLHZIePHhQ3QTRzwtNhs4LA+T8mFVAHowC+vfv77jEADFFnQFlbpTO4UpxtSU/P5+mTZtGubm5lJ+Xp/rwDGMwFnNYxHWc3MQ7EhWIygvoDJDpcnp6urptZvrNr1uTYXe4cRIPiW+0vxz1TQLSGjRQh4w4ZXGbp784VAu1W27jIpEAXxkwd+5cKtP8r9uLwiGXMAZEqgKIBLOzs+ns2bPG3+5K48PPwl2RiYUBkaqAPt/zL0cByKthoPgURxIXzhqb1vMCkY434WFiEn//DwAA//8DAD4L78gJpxWiAAAAAElFTkSuQmCC') no-repeat scroll center center/100%;
}
```

The image encoded above is the following. Note that it has a white background, not transparent: otherwise, the background color used to colorize the icon will bleed through.

![image](https://cloud.githubusercontent.com/assets/1907073/24316695/76863c84-10ad-11e7-83da-cf6805808217.png)

**Comment by joseleperez** [comment]
+1

**Comment by molavec** [comment]
+1

**Comment by zhorn** [comment]
+1

**Comment by jjtfsalgado** [comment]
+2

**Comment by littleindianboy** [comment]
+3

**Comment by lasuax** [comment]
it's been 2 years that people are demaning an icon for this application

**Comment by v3shevchenko** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[The Facebook messenger icon is here.](https://icons8.com/icon/20202/facebook-messenger)

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by sakerrr** [comment]
+1

**Comment by Klyner007** [comment]
+1

**Comment by pietro909** [comment]
Looks like a joke XD can't believe it's still open

**Comment by jamesmthornton** [comment]
The kickstarter for fontawesome 5 generated over $1 million, I don't know why they can't put an intern on this kind of stuff a few hours a month.

@dmland may be a better method here for vector background url:

`background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 54.83 55.1"><path class="cls-1" style="fill:#437bbd" d="M0,26.27q0-.76,0-1.52c0-.2.07-.39.1-.59.2-1.38.28-2.79.6-4.14A24.73,24.73,0,0,1,11,5.08a28.26,28.26,0,0,1,19.18-5,27.59,27.59,0,0,1,5.84,1.15A26.92,26.92,0,0,1,49.35,10.2,23.86,23.86,0,0,1,54.8,26.85a22.48,22.48,0,0,1-.66,4.44,24.86,24.86,0,0,1-9.42,14A28.17,28.17,0,0,1,25.66,51a29.58,29.58,0,0,1-5.77-.91.9.9,0,0,0-.6.07C17,51.41,14.63,52.7,12.3,54l-2,1.12v-.44c0-3,0-5.91,0-8.87a.7.7,0,0,0-.31-.63,25.67,25.67,0,0,1-6.07-6.6A23.77,23.77,0,0,1,.09,26.78,4,4,0,0,0,0,26.27Zm45-7.76L45,18.44l-.32.15-12.6,7a.43.43,0,0,1-.63-.08q-2.89-3.06-5.8-6.09c-.36-.37-.74-.71-1.14-1.09L9.65,34.22l.07.09.72-.38q6.19-3.4,12.37-6.81a.44.44,0,0,1,.66.12c.41.47.84.91,1.26,1.36q2.59,2.79,5.18,5.58c.2.22.32.21.5,0s.6-.65.9-1l13.13-14C44.66,19,44.85,18.73,45,18.51Z"/></svg>') no-repeat;`

**Comment by achitena** [comment]
+1

**Comment by fabiograsso** [comment]
+1

**Comment by truls1502** [comment]
+1

**Comment by jrlmontejo** [comment]
In 6 days, we will celebrate the 2nd anniversary of this icon request.

**Comment by Alirezaies** [comment]
+1

**Comment by Dudisek** [comment]
+1

**Comment by orionisman** [comment]
+1

**Comment by haidner** [comment]
+1

**Comment by FrancoMeriles** [comment]
+1

**Comment by ferparmur** [comment]
+1

**Comment by ry168** [comment]
+1

**Comment by purvik7373** [comment]
+1

**Comment by Senegal** [comment]
+1

**Comment by hawflau** [comment]
+1

**Comment by ahmadalfy** [comment]
+1

**Comment by aze3ma** [comment]
+1

**Comment by yojona** [comment]
+1

**Comment by huypn** [comment]
+1

**Comment by alexanderdejong** [comment]
+1

**Comment by bhaskarvgurram** [comment]
+1

**Comment by adronitis** [comment]
+1

**Comment by oecsike366** [comment]
i wrote here almost a year before. im done with this BS.

**Comment by nagra** [comment]
So we've gone past the **3rd anniversary** for this icon request 😬.
You've got the Pied Piper logo, but not the one that is actually useful for your users? 🤔

**Comment by manuelsongokuh** [comment]
+1

**Comment by albertgudlaugsson** [comment]
+1

**Comment by yundlmn** [comment]
+1

**Comment by hedyharto** [comment]
+1

**Comment by sushantshekhar20** [comment]
+1

**Comment by JacquelinClement** [comment]
+1

**Comment by unpapelito** [comment]
+1

**Comment by marcel-silva** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by parfilov** [comment]
+1

**Comment by velikovmartin** [comment]
+1

**Comment by tagliala** [comment]
@velikovmartin https://fontawesome.com/icons/facebook-messenger?style=brands

**Comment by velikovmartin** [comment]
@tagliala  Thank you, I already found it.

**Comment by atMaarten** [comment]
+1 for Facebook Messenger.
Please also add it to the share widget!

**Comment by tagliala** [comment]
@atMaarten  https://fontawesome.com/icons/facebook-messenger?style=brands
