### ISSUE TITLE
pie-chart is not working

### ISSUE THREAD

**Issue by lpribyl** [FortAwesome/Font-Awesome#6915]
I am trying to insert the fa-pie-chart into my webpage. I had 4.2.0, so I just installed font awesome 4.3.0 and placed it into my site. It is taking up space on the page but it will not show up. I have other icons displaying, so I tried replacing the name with pie-chart and it still isn't showing up. Do you know if there is a bug with this icon? Thank you for your time.

**Comment by tagliala** [comment]
Can't confirm

Please take a look at our trobuleshooting wiki: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
