### ISSUE TITLE
Icon request: icon-react

### ISSUE THREAD

**Issue by eliagrady** [FortAwesome/Font-Awesome#6920]
A Facebook react logo, like the blue atom logo here: https://facebook.github.io/react/index.html
Like: https://cdn.auth0.com/blog/react-js/react.png

**Comment by ozluy** [comment]
+1

**Comment by MayeuldP** [comment]
+1 !

**Comment by cimfalab** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
