### ISSUE TITLE
Icon Request: map-marker-slash

### ISSUE THREAD

**Issue by soletan** [FortAwesome/Font-Awesome#6931]
I intend to use map-marker for indicating whether current user's location is available or not. Actually I'm missing a counterpart like microphone and microphone-slash for indicating either having access on user's location or not. I'd rather use a similar pair of icons instead of working with opacity, colours, combined icons or stuff like that.

**Comment by tagliala** [comment]
refers to #1181

**Comment by soletan** [comment]
So do bell-slash, bell-slash-o, eye-slash and microphone-slash, right!? I basically agree in that this is possible by stacking several icons and letters from other fonts, though having an integral styling for either case might be preferrable. Indeed, one might ask for related stackings of quite every icon in fontawesome. 

My con: requiring fontawesome already takes some time to load. If I design an icon using opportunities provided by fontawesome I'm interested in building a predictable look. My further website probably might require loading another web font for matching a given corporate design. But what if that font isn't containing suitable version of slash to achieve the common look of slashing icon map-marker? Take a third web font? Rely on user providing proper font I'm expecting to use here? Why not stick with rendering whole icon say in SVG or as a PNG then? 

I basically consider map-marker being a commonly useful icon for any kind of web application supporting geo tagging and thus being interested in visually remarking if geolocation is available or not.

**Comment by tagliala** [comment]
Your request to add `map-marker-slash` to Font Awesome is legit and this request was properly labeled and leaved open for upvoting

**Comment by soletan** [comment]
No problem, everything's fine ;) ... I just wanted to argue in more detail.
