### ISSUE TITLE
Homepage: icon search + https not working

### ISSUE THREAD

**Issue by jbreitbart** [FortAwesome/Font-Awesome#6932]
The search on https://fortawesome.github.io/Font-Awesome/icons/ is not working unless I reload parts of the homepage over http.

**Comment by tagliala** [comment]
Thanks for reporting this. There is a CORS  issue.

Mixed Content: The page at 'https://fortawesome.github.io/Font-Awesome/icons/' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js'. This request has been blocked; the content must be served over HTTPS.
site.js:2 Uncaught TypeError: $(...).validate is not a function

**Comment by tagliala** [comment]
This should be fixed after @davegandy rebuilds docs
