### ISSUE TITLE
Icon request: barbecue

### ISSUE THREAD

**Issue by Samoht-fr** [FortAwesome/Font-Awesome#6933]
As developing a website for renting flats, I need some icons do describe amenities. Hence I'll submit several issues, thanks for your help.

Fire ring or babecue:
https://www.iconfinder.com/icons/185115/barbecue_food_streamline_icon#size=128

**Comment by AndreiEzhov** [comment]
Dupe? #6293

**Comment by tagliala** [comment]
@AndreiEzhov thanks

closing here
