### ISSUE TITLE
Icon request: tv-set

### ISSUE THREAD

**Issue by Samoht-fr** [FortAwesome/Font-Awesome#6934]
Surprisingly, I didn't find TV set icon :)

For example, although I don't really like the play symbol in the middle: https://www.iconfinder.com/icons/290126/monitor_screen_television_tv_video_icon#size=128

**Comment by tagliala** [comment]
maybe a dup of #368 ?

**Comment by Samoht-fr** [comment]
yes. I plused 1 #368

**Comment by tagliala** [comment]
#368 is here: http://fontawesome.io/icon/television/
