### ISSUE TITLE
Icon request: fa-microwave-oven

### ISSUE THREAD

**Issue by tpeyrard** [FortAwesome/Font-Awesome#6937]
An icon that represent an oven, like:
https://www.iconfinder.com/icons/381604/microwave_oven_icon#size=128

**Comment by Krevo** [comment]
http://www.iconarchive.com/show/ios7-icons-by-icons8/Household-Microwave-icon.html

**Comment by Samoht-fr** [comment]
Yes, good icon. Thanks

**Comment by tvirelli** [comment]
@Krevo I like your example. Maybe 2 icons for this?

Your example could be fa-microwave-oven-on and there could be a fa-microwave-oven-off that doesn't have the waves in the window.

**Comment by aethior** [comment]
Hi @tpeyrard,

This icon was added in v5.12.0.
Check https://fontawesome.com/icons/microwave

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here.
