### ISSUE TITLE
Icon request: fa-iron

### ISSUE THREAD

**Issue by Samoht-fr** [FortAwesome/Font-Awesome#6938]
An icon that represent ironing:

https://www.iconfinder.com/icons/175266/iron_icon#size=128

**Comment by tagliala** [comment]
dup of #1171, please +1 that request

closing here

**Comment by szczemp** [comment]
I just make this icon for hotel service.
https://u.lkn.pl/png/ZOelazko_jsBL.png
It is a modification of free fontawesome beer icon.
