### ISSUE TITLE
Icon request: icon-cart-arrow-up

### ISSUE THREAD

**Issue by mrdungx** [FortAwesome/Font-Awesome#6941]
..as we already have cart-arrow-down and cart-plus.

Thanks! Font Awesome is awesome :)

**Comment by peiche** [comment]
+1

**Comment by kazarenko** [comment]
+1

**Comment by lowerends** [comment]
+1

**Comment by isyed2k** [comment]
I need a car-arrow-up icon

**Comment by Clearnine** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by tonimoeckel** [comment]
+1

**Comment by itkin** [comment]
+1

**Comment by gquipster** [comment]
+1

**Comment by AlexVanDamn** [comment]
+1

**Comment by borconi** [comment]
2019 and cart-minus still doesn't exists 👎  😞

**Comment by tagliala** [comment]
Cart minus: #3234

**Comment by aethior** [comment]
Hi @mrdungx,

This icon has been added in v6.0.0-BETA2.
Check https://fontawesome.com/icons/cart-arrow-up

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon is part of the Pro set

**in a web application**, free user can create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/73/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
