### ISSUE TITLE
Icon request: environmental (nature) icons

### ISSUE THREAD

**Issue by crypticman** [FortAwesome/Font-Awesome#6949]
I noticed that there are very few icons to represent  nature. I would like more nature related icons: different types of trees, tree logs, wildlife.

Thanks

**Comment by tagliala** [comment]
Sorry can't keep this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
