### ISSUE TITLE
Icon Request: fa-safeway, fa-costco, fa-walmart

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#6960]
I don't know if I will use this icon but maybe I will.
There are no store brands in Font Awesome.
What it should look like: 
https://cbssacramento.files.wordpress.com/2013/06/safeway-logo.jpg?w=420
http://logonoid.com/images/costco-logo.png
http://logok.org/wp-content/uploads/2014/05/Walmart-Logo.png

**Comment by tagliala** [comment]
Sorry, can't leave this open

You should open three individual requests

#walmart
