### ISSUE TITLE
Icon Request: fa-guidenote

### ISSUE THREAD

**Issue by uppulakranthi** [FortAwesome/Font-Awesome#6963]
Need below type of icon... please provide...
![image](https://cloud.githubusercontent.com/assets/7829058/8722523/263a672e-2be3-11e5-951f-993f40cc67ca.png)

**Comment by tagliala** [comment]
Is this a brand?

**Comment by uppulakranthi** [comment]
No, I wanted to show guide note for a question..... Actually whenever i click on that icon i will show guide note in a popup.

**Comment by tagliala** [comment]
I'm going to consider this closed by https://fontawesome.com/icons/circle-g?s=solid

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
