### ISSUE TITLE
Icon Request: fa-turn-right, fa-turn-left

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#6966]
It would be great for directions.
fa-turn-right: http://etc.usf.edu/clipart/68200/68205/68205_487_w1-1_s_sm.gif
fa-turn-left: http://etc.usf.edu/clipart/68000/68017/68017_119_w1-1_s_sm.gif

**Comment by sublines** [comment]
you could use fa-reply and fa-share

**Comment by aethior** [comment]
@tagliala `arrows (category)` label for this request?

**Comment by tagliala** [comment]
I think that they are here

https://fontawesome.com/icons/diamond-turn-right?s=solid&f=classic

the opposite can be achieved with a CSS class or an SVG transform
