### ISSUE TITLE
Icon request: Groups

### ISSUE THREAD

**Issue by eliv3n** [FortAwesome/Font-Awesome#6968]
Hello,
we have icons for Users, but not for Groups

**Comment by tagliala** [comment]
any example?

**Comment by eliv3n** [comment]
Below image is  an example.
I believe we need different font icons for People, Users and Groups.

**Comment by tagliala** [comment]
you should post your example here: https://github.com/FortAwesome/Font-Awesome/issues/6968, email attachments don't work

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
