### ISSUE TITLE
Increase size of icon-home

### ISSUE THREAD

**Issue by vonavi** [FortAwesome/Font-Awesome#697]
Hey!
Starting from FA 3.0, **icon-home** looks a bit smaller than other icons. It's checked for Chrome, Firefox and Opera. As a result, I have to use the size of `20px` for this icon, and the size of `19px` for the rest of icons. I'm not sure neither other broken sizes exist or not.
Cheers.

**Comment by tagliala** [comment]
I think this has been fixed 

https://jsfiddle.net/tagliala/tgzouajm/41/
