### ISSUE TITLE
Rename FontAwesome.otf to font-awesome-webfont.otf?

### ISSUE THREAD

**Issue by evilebottnawi** [FortAwesome/Font-Awesome#6971]

**Comment by tagliala** [comment]
FontAwesome.otf is used to develop the font and it is not a webfont. `-webfont` files are generated from the .otf via fontsquirrel

Is there any particular reason to rename the .otf file?

**Comment by evilebottnawi** [comment]
@tagliala i have task on gulp and collect all svg fonts in array, when generate from svg -> ttf, woff, woff2 and etc, but awesome have another name.
