### ISSUE TITLE
Please make oval in fa-money more like a circle

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#6977]
Can you please make the oval in fa-money more like a circle and maybe make it smaller?
That will make it look better. (To me, at least)

**Comment by tagliala** [comment]
refers to #4418

**Comment by tagliala** [comment]
Is this still an issue?

https://jsfiddle.net/tagliala/yxqqchjs/3/

**Comment by sensibleworld** [comment]
https://fontawesome.com/v6.0/icons/money-bill
