### ISSUE TITLE
Icon request : add transfer filter to fa-exchange

### ISSUE THREAD

**Issue by ankit-maverick** [FortAwesome/Font-Awesome#6982]
Transfer icon along these lines https://www.google.co.in/search?q=transfer+icon&client=ubuntu&hs=zx7&channel=fs&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMIo53U6PXmxgIVzSOOCh14Dw14&biw=1366&bih=673

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/exchange/

Leaving this open, we should add a filter

**Comment by tagliala** [comment]
there already is a transfer filter, it will be available in the next release

closing here
