### ISSUE TITLE
Icon Request: fa-health-fitness

### ISSUE THREAD

**Issue by EBonar** [FortAwesome/Font-Awesome#6992]
I would like to use this on a clients "Industries Served" page, http://dev.colormixgraphics.com/industries-served/
![healthandfitness-grey](https://cloud.githubusercontent.com/assets/11934450/8782189/7040b79e-2ed9-11e5-8322-30e5e46946f6.png)

**Comment by tuxy** [comment]
alternative fa-health-fitness, fa-fitness or even fa-runner icon:

![Alt Health Fitness](http://i.imgur.com/qvyU1vc.png)
Source: http://www.flaticon.com/free-icon/runer-silhouette-running-fast_55240

**Comment by tagliala** [comment]
@EBonar do you need an icon exactly like that?

**Comment by EBonar** [comment]
@tuxy Thank you!
@tagliala It doesn't have to be exactly like that, but the closer the better.

**Comment by SteveHarlington** [comment]
A running icon would be fantastic.

**Comment by drewstephensdesigns** [comment]
+1 love font awesome and could use this icon for a current client!

**Comment by BoBao77** [comment]
I'm building a fitness app, and currently use fa in my apps and love it. The fitness space is pretty big it be great to have a set of fitness icons. +1 for this request and will be +1ing the dumbbell request also.

**Comment by mbrod90** [comment]
+1 me too!

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/running?style=solid
