### ISSUE TITLE
Icon Request: fa-golf 

### ISSUE THREAD

**Issue by sdh100shaun** [FortAwesome/Font-Awesome#6995]
golf tee flag representative to be used to represent a golf course

**Comment by tuxy** [comment]
fa-golf-course icon:

![Golf Course](http://i.imgur.com/7kDNqXS.png)
Source: http://www.flaticon.com/free-icon/golf-hole-and-flag_55568

fa-golf-player icon:

![Golf Player](http://i.imgur.com/BMZfyNg.png)
Source: http://www.flaticon.com/free-icon/golf-player_39675

**Comment by tagliala** [comment]
duplicate of #5348, please +1 that request

closing here

**Comment by tuxy** [comment]
@tagliala, the #5348 is wrong because this request is for fa-golf-player and fa-golf-course and NOT for golf ball or golf club.

**Comment by tagliala** [comment]
I can say that #5348 is an icon that represents golf. I don't know how dave will implement that, maybe a golf ball, maybe a tee flag... If you want to request a specific icon, please open a new request with a proper title (eg: icon-golf-player)

**Comment by amosvanhorn** [comment]
+1

**Comment by Cengiz25** [comment]
+1

**Comment by kimarudg** [comment]
+1

**Comment by stefbozic** [comment]
+1

**Comment by AngerLiss** [comment]
+1

**Comment by duy205711** [comment]
+1
