### ISSUE TITLE
Icon request: Study

### ISSUE THREAD

**Issue by braewood** [FortAwesome/Font-Awesome#6996]
I would like a study icon for a home builder website. Maybe a desk or computer image?

**Comment by tuxy** [comment]
+1 for fa-study

fa-study icon:
![Study Icon](http://i.imgur.com/CCHxW82.png)
Source: https://www.iconfinder.com/icons/115795/study_icon#size=128

**Comment by tagliala** [comment]
Maybe I didn't get this request

A graduation cap is already here: http://fontawesome.io/icon/graduation-cap/
There is also a desktop: http://fontawesome.io/icon/desktop/

Closing here but let me know if you are requesting something else

**Comment by tuxy** [comment]
@tagliala, yep perfect. This will work! Thank You!
