### ISSUE TITLE
Icon request: Ruler

### ISSUE THREAD

**Issue by braewood** [FortAwesome/Font-Awesome#6997]
I would like a Ruler icon for a building/realestate website to indicate the size of a house

**Comment by MonkeyData** [comment]
Ditto that.  I am trying to find items for a (street) mapping toolbar.  "fa-measure" would be nice

![image](https://cloud.githubusercontent.com/assets/3502679/8835802/af686a68-308a-11e5-8983-db170e2303c7.png)

**Comment by tuxy** [comment]
+1 for fa-measure.

define: ruler; One, such as a monarch or dictator, that rules or governs.
Source: https://www.wordnik.com/words/ruler

**Comment by tagliala** [comment]
duplicate of #1096 , please +1 that request

closing here

**Comment by tuxy** [comment]
@tagliala, done. Thank You!
