### ISSUE TITLE
PDF icon unicode doesn't work

### ISSUE THREAD

**Issue by hsteel** [FortAwesome/Font-Awesome#6998]
Hi, there seems to be a bug with the PDF icon - http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/ - where it renders as a box rather than an icon.

The exact code below, when used with a different unicode, works fine, but with the PDF unicode of "f1c1" only the box appears. I can't show a page example sorry as our dev environment is locked down but here is a screenshot:

![capture](https://cloud.githubusercontent.com/assets/6777629/8791319/896e0c94-2f9c-11e5-9f75-9702939529e8.JPG)

To replicate:

Create a dt list, e.g.

```
<dl class="standoutList">
  <dt>Monday, April 13, 2015 at 5:30 PM (Standing Committee)</dt>
  <dd>
    <ul>
      <li><a href="#">Agenda - Standing Committee Meeting - Monday 13 April 2015</a></li>
    </ul>
  </dd>
</dl>
```

Apply the SCSS:

```
dl.standoutList {
  dt {
    line-height: 1.35em;
    font-size: 90%;
  }
  dd {
    ul {
      li {
        line-height: 1.25em;
        list-style: none;
        margin: 0.5em 0 0.75em !important;
        font-size: 80%;
        a {
          &:before {    
            font-family: FontAwesome;
            content: "\f1c1";
            margin: 0 0 0 -15px;
            color: $aqua-medium;
            font-size: 125%;
            padding: 0 0.5em 0 0;
          }
        }
      }
    }
  }
}
```

If you now replace content: "\f1c1"; with another unicode like "\f114" it will work, e.g.

![capture2](https://cloud.githubusercontent.com/assets/6777629/8791506/2567a78e-2f9f-11e5-971b-6dc4db918d5e.JPG)

Thanks
Harmony

**Comment by tagliala** [comment]
Please check that you are using the last version of Font Awesome

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by tagliala** [comment]
No feedback, closing here
