### ISSUE TITLE
Icon Request: fa-jianshu

### ISSUE THREAD

**Issue by oopsrudder** [FortAwesome/Font-Awesome#6999]
Hi, i want request new icon - "Jianshu" 

http://jianshu.com/

Thanks

![image](https://cloud.githubusercontent.com/assets/2977659/6724391/170efdaa-ce32-11e4-87eb-065b5c76aa9c.png)

https://drive.google.com/file/d/0B75gSUbD7L2RcUFMT1hZY2lQbmc/view?usp=sharing

**Comment by larryzhao** [comment]
Awesome, this is great.

**Comment by LostAbaddon** [comment]
Great!
+1

**Comment by tagliala** [comment]
reopening #5999
