### ISSUE TITLE
Icon Request: fa-full-screen

### ISSUE THREAD

**Issue by mahendra-alladi** [FortAwesome/Font-Awesome#7000]
Request for icons for "full screen" and "exit full screen"

Thanks
Mahendra

**Comment by sanderdekkers** [comment]
isn't http://fontawesome.io/icon/arrows-alt/ a valid full-screen icon ?
exit full screen could be a new one, with arrows pointing inwards

**Comment by mahendra-alladi** [comment]
Sure, but when I used it on a draggable modal, this icon looks very close to drag pointer. Thanks for considering the request.

Regards

Mahendra

**Comment by tagliala** [comment]
maybe a duplicate of #4576 ?

**Comment by mahendra-alladi** [comment]
Yes, thank you

**Comment by tagliala** [comment]
you're welcome. please +1 #4576 

closing here
