### ISSUE TITLE
New Icon request

### ISSUE THREAD

**Issue by benosey** [FortAwesome/Font-Awesome#7002]
old style tv, Radio,  brightness, weather cloud icons would be amazing.......!!  I cant find them anywhere in font awesome....  but be really handy if they were made available.....  also Sign up Login Logout  (i know there are sign in and sign out,   

![radio](https://cloud.githubusercontent.com/assets/2742094/8805710/af94d848-2fca-11e5-910a-da1c604e2660.png)
![weather](https://cloud.githubusercontent.com/assets/2742094/8805711/af977bb6-2fca-11e5-88e1-63368b287bbe.png)
![music](https://cloud.githubusercontent.com/assets/2742094/8805712/af9848f2-2fca-11e5-9960-44ebeb5f2cce.png)
![tv](https://cloud.githubusercontent.com/assets/2742094/8805716/b2d14a28-2fca-11e5-9328-347ae5a5dcdd.png)

![led_brightness](https://cloud.githubusercontent.com/assets/2742094/8805686/8ef4645a-2fca-11e5-9ef2-fab449c9316b.png)

**Comment by tuxy** [comment]
+1 for fa-radio, fa-headphones, fa-tv

**Comment by tagliala** [comment]
Sorry, can't leave this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Closing here

**Comment by tuxy** [comment]
@tagliala, which rule are you refering to ?

2. Please do not request comprehensive sets of icons related to a very specific field. ?

A reference to specifc rule would help next time :) Thanks.

**Comment by tagliala** [comment]
Sure!

Eg of comprehensive set:

> 
**Icon request: Weather icons**
I'm making a forecast web application, I need icon-cloudy, icon-thunderstorm, icon-fog, icon-light-snow, icon-snow, icon-mostly-sunny, etc.

If you have such a need, you should consider a custom build or use fontawesome together with another set
