### ISSUE TITLE
Icon Request: fa-pallete

### ISSUE THREAD

**Issue by matizar** [FortAwesome/Font-Awesome#7003]
I like to use an icon pallete (I have seen in "Core Fonts used by Kentico CSM") and I think that's highly usable.
<img width="64" alt="colorpalette" src="https://cloud.githubusercontent.com/assets/9940737/8806586/f6f31458-2f9c-11e5-872a-8298c0f41f5b.png">

**Comment by tagliala** [comment]
duplicate of #244 , please +1 that request

closing here
