### ISSUE TITLE
Icon Request: fa-user-search

### ISSUE THREAD

**Issue by micdech** [FortAwesome/Font-Awesome#7005]
Can be useful to have a new icon relate to user with a small search icon into.

Useful to inficate a button or input to search user in your site/app

**Comment by tuxy** [comment]
+1 User Search Icon:

Male User Search Outline:
![Male User Search](http://i.imgur.com/zj3rGSG.png)
Source: http://www.iconarchive.com/show/silky-line-user-icons-by-custom-icon-design/user-man-search-icon.html

Female User Search Outline:
![Female User Search](http://i.imgur.com/vPaJVNl.png)
Source: http://www.iconarchive.com/show/silky-line-user-icons-by-custom-icon-design/user-woman-search-icon.html

**Comment by micdech** [comment]
Many thanks for your plus tuxy. Unfrotunately, your icon advice are not following with the graphic of other icons fa. 

We need to wait for other suggest... :D

**Comment by tagliala** [comment]
duplicate of #6760 , please +1 that request

#1181 provides a solution for this

**Comment by tuxy** [comment]
@ tagliala, done. Thank You!
