### ISSUE TITLE
Icon Request: fa-houzz

### ISSUE THREAD

**Issue by jlavoie13** [FortAwesome/Font-Awesome#7008]
http://www.houzz.com/

![amifv94vq_ahuta-fkzof8tvucsbjaoxgutww_xqgpiudere7mn0byryiysi84nf0po1gcq66_r63gs8pgs9gydzm46pqi9y57xtgmajcewapsvawz8xrh4ox2vpgqxccdpia0jxlgrc](https://cloud.githubusercontent.com/assets/4210773/8835297/967806f6-3087-11e5-9584-14b1f6b6e0da.png)

May be difficult with the multi-color, but can do something like this below, minus the circle.

![houzz](https://cloud.githubusercontent.com/assets/4210773/8835385/277c7ee8-3088-11e5-8d66-bd7a289ff1cd.jpg)

Thanks

**Comment by tagliala** [comment]
duplicate of #2039 , please +1 that request

closing here
