### ISSUE TITLE
fa-train doesn't display

### ISSUE THREAD

**Issue by csgrp** [FortAwesome/Font-Awesome#7009]
First, I want to thank you for creating such an awesome, well-done and well supported tool with FontAwesome!
It rocks! And the community as well. 

It’s working beautifully on our site, except for the train icon.
The code I’m using is

 [font icon=fa-train color=#000000 border-color=none] 

Also tested it in other colors... no "luv" either tee-hee!
[font icon=fa-train color=#ffffff border-color=none] 

 but I don’t think that’s the problem, as the same code calling any of the other icons we’ve tested with works fine.  I can see the border of the round disk, but there's no picture that displays. 

Just looks like probably a small typo or something on your end? With so many hundreds of icons available now, that sort of thing is easy to miss. So no worries. Would just love to see it working 

Would deeply appreciate your looking into that when you get a chance.
In advance, thank you!

Cath White
P.S. - Wasn’t sure whether it’s better for you to open a GitHub ticket or just email you, so I did both. Hope that was ok?
First attachment is a screenshot of the fa-train icon issue. 2nd attachment is showing how the same code that just calls different icons works fine.  Again, thanks for all your efforts!
![fa-train_doesntdiplayproperly](https://cloud.githubusercontent.com/assets/13458179/8837965/fcbb854e-308e-11e5-9228-db02498b5de4.png)
![fa-train_examplesofothericonsthatdo_samecodeused](https://cloud.githubusercontent.com/assets/13458179/8837969/026da954-308f-11e5-9c6a-3b375348379c.png)

**Comment by tuxy** [comment]
+1 Train Icon:

Train Outline:
![Train Outline](http://i.imgur.com/XV4sdeb.png)
Source: http://www.iconarchive.com/show/ios7-icons-by-icons8/Transport-Train-icon.html

Train Regular:
![Train Regular](http://i.imgur.com/5VOzeo2.png)
Source: http://www.iconarchive.com/show/windows-8-icons-by-icons8/Transport-Train-icon.html

**Comment by tagliala** [comment]
@csgrp please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

@tuxy http://fontawesome.io/icon/train/

**Comment by tuxy** [comment]
@tagliala, this will work. Thank You!

**Comment by bartclaeys** [comment]
It does not work, see this bootply:

http://www.bootply.com/HTFC35Muhd

**Comment by bartclaeys** [comment]
Correction, it does work, but only in 4.3.0.
