### ISSUE TITLE
Spinner uses 50% CPU

### ISSUE THREAD

**Issue by nevf** [FortAwesome/Font-Awesome#701]
I've just upgraded to V3 and made use of the new icon-spinner class and am seeing CPU use sit at around 50% in Google Chrome when the spinner is active. I'm seeing similar high CPU use when I open the FontAwesome website. Other CSS spinners I've checked don't have this problem.

Update: I've looked into this a bit further and have tested it on 3pcs and only (older) PC is exhibiting the issue. So it may be related to the video card or driver or some such and not an issue with your spinner as such. It is still interesting that other spinners are ok. I assume it has something to do with the specific css being used.

A good article on HTML Performance including CSS animation is: http://www.html5rocks.com/en/tutorials/speed/html5/  And this [SO post](http://stackoverflow.com/questions/8400075/are-css3-properties-like-animate-too-cpu-intensive) is interesting. ie. "use translate3d, scale3d, rotate3d as they are hardware accelerated"

**Comment by programmin1** [comment]
This one doesn't use excessive CPU on my Firefox, and it seems to be related to the steps(number) in animation css. http://lea.verou.me/2013/11/cleanest-css-spinner-ever/

**Comment by NET4ORCE** [comment]
I've found that font-smoothing has a minor (~ <10% reduction) CPU load effect,  so I apply :

`-webkit-font-smoothing: none;` to the `@{fa-css-prefix}-spin` mixin

**Comment by danielbonnell** [comment]
This is still a problem when applying the `fa-spin` class to an icon. I'm using v4.6.3.0 and notice that a single instance of `fa-spin` on the page results in a CPU usage spike of 8-10%. It's not 50%, but it's certainly noticeable. My solution was simply to use Angular/jQuery to hide the element when not in use.

**Comment by programmin1** [comment]
@danielbonnell Are you sure that 8-10% wasn't half of one processor? Depends on what cpu meter you are using. steps(n) is a good way to reduce it if it looks ok.

**Comment by danielbonnell** [comment]
@programmin1 That was based off the Chrome Task Manager reporting that the tab in question was idling at 8-10% vs 0% when no instances of `fa-spin` are visible in the DOM. I agree it's not an exact measurement, but the hit is noticeable even without looking at the CPU meter. I'm running this on a 2009 MacBook Pro, 2.26GHz Core 2 Duo, 8GB RAM, and an SSD. Definitely an older machine, but it performs fine for most of the development I do.
