### ISSUE TITLE
Icon Request: fa-satelite

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7011]
fa-satelite icon:

![Satelite](http://i.imgur.com/sv2cAmA.png)
Source: https://www.iconfinder.com/icons/322495/satelite_icon#size=128

**Comment by tagliala** [comment]
duplicate of #2404 , please +1 that request and post there your example

closing here

**Comment by tuxy** [comment]
@tagliala, done. Thank You!

**Comment by khanabuzaid** [comment]
hi,
how to use this fa-satelite in awesome font.
which version in provide this icon.
