### ISSUE TITLE
Icon Request: fa-repair

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7013]
fa-repair icon:

![Repair](http://i.imgur.com/JG818nK.png)
Source: http://www.flaticon.com/free-icon/double-wrench-tool-and-hammer-forming-a-cross-of-outlines_25718

**Comment by tagliala** [comment]
duplicate of #736 , please +1 that request

closing here

**Comment by tuxy** [comment]
@tagliala, done. Thank You!
