### ISSUE TITLE
Icon Request: fa-health

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7014]
fa-health icon:

![Health](http://i.imgur.com/mnKipD0.png)
Source: https://www.iconfinder.com/icons/111046/health_medicine_icon#size=128

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/medkit/

added a health filter to the above icon

closing here

**Comment by tuxy** [comment]
@tagliala, my bad, missed this :-) Thank You!
