### ISSUE TITLE
Icon Request: fa-firefox and fa-chrome

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7015]
Request for most popular browser icons.

fa-firefox icon:

![Firefox](http://i.imgur.com/iD2kDKr.png)
Source: http://plainicon.com/download-icon/50215/firefox

fa-chrome icon:
![Chrome](http://i.imgur.com/F3J92fw.png)
Source: http://findicons.com/icon/80504/chrome

**Comment by tagliala** [comment]
duplicate of #219 , please +1 that request

closing here

**Comment by tuxy** [comment]
@tagliala, done. Thank You!
