### ISSUE TITLE
Icon Request: fa-lang-{here}

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7018]
Most popular programming languages icons.

Good examples of this;
https://vorillaz.github.io/devicons/#/cheat
http://devicon.fr/

fa-lang-php icon:
Site: http://php.net/
http://www.flaticon.com/free-icon/php-file-rounded-rectangular-outlined-interface-symbol_55601#
and outline; http://www.flaticon.com/free-icon/php-file-rounded-rectangular-outlined-interface-symbol_55601#

fa-lang-python icon:
Site: https://www.python.org/
http://www.flaticon.com/free-icon/python-language-logotype_2181

fa-lang-ruby icon:
Site: https://www.ruby-lang.org/en/
Icon: https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/200px-Ruby_logo.svg.png

fa-lang-go icon:
Site: http://golang.org/
Icon: https://lh6.googleusercontent.com/-8Ocph_buarI/AAAAAAAAAAI/AAAAAAAAAAQ/EtfJIfJe1Eo/photo.jpg

fa-lang-rust icon:
Site: http://www.rust-lang.org/
Icon: http://www.rust-lang.org/logos/rust-logo-blk.svg

fa-lang-nim icon:
Site: http://nim-lang.org/
Icon: https://avatars3.githubusercontent.com/u/603863?v=3&s=200

fa-lang-perl icon:
Site: https://www.perl.org/
Icon: http://xahlee.info/UnixResource_dir/gki/perl_camel.svg

fa-lang-bash icon:
Site: http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO.html
Icon: http://www.veryicon.com/icon/png/System/Icons%20for%20Developers/terminal.png

**Comment by tagliala** [comment]
Sorry, can't leave this open because it doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

There are several duplicates, you should +1 instead.

Please take also a look at mfizz: http://fizzed.com/oss/font-mfizz

**Comment by tuxy** [comment]
@tagliala, actually font-mfizz or devicons will work too. Just wanted to see something like this in Font-Awesome instead ;-) Thanks.

**Comment by tagliala** [comment]
you're welcome

devicons = http://vorillaz.github.io/devicons/#/main ?

**Comment by dimitrieh** [comment]
I was wondering if a merger between devicons and font awesome would be possible? @tagliala

**Comment by tagliala** [comment]
@dimitrieh you can customize fontawesome and merge another set: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
