### ISSUE TITLE
Icon Request: fa-facebook-loading-indicator

### ISSUE THREAD

**Issue by bebertz93** [FortAwesome/Font-Awesome#7019]
Hi,

Good day!
This icon is like the facebook loading indicator. It is animated.
I hope you consider making this one.

Thanks,

Albert

**Comment by tagliala** [comment]
Sorry but this

![spinner](http://www.askanews.it/img/ajax-loader.gif)

 is not possible with an icon font. You should consider a pure css or an SVG based solution

**Comment by bebertz93** [comment]
Ok. No problem. Thanks anyway!
