### ISSUE TITLE
Icon Request: Compact Disc (icon-cd icon-dvd icon-bluray)

### ISSUE THREAD

**Issue by ewollesen** [FortAwesome/Font-Awesome#702]
…it would be a nice complement to the video player icons. Perhaps a section of film would be cool too, if that hasn't already been suggested.

**Comment by CromonMS** [comment]
+1, would love to see media icons, CD, LP, Cassette, etc.

**Comment by eKatsarski** [comment]
+1

**Comment by jesusr** [comment]
+1

**Comment by riscphree** [comment]
definitely a +1 here. I don't see it happening. between this and the amazon logo, aint gonna happen if it hasn't happened yet.

**Comment by Einkoro** [comment]
+1 optical media icons

**Comment by kdeckr** [comment]
+1. Currently categorizing music from different media (TV, Film, Album, etc) and this would really help.

**Comment by jacobvalenta** [comment]
+1 Icon for the DVD version of content. (Its been 2 years?)

**Comment by nissicreative** [comment]
+1. Usage: film studio/ticketing website. Already using fa-film, fa-ticket, etc. Need a way to differentiate DVD media availability.

**Comment by TPXP** [comment]
+1

**Comment by miles75** [comment]
+1 to media icons, CD, LP, Cassette, etc.

**Comment by Elorfin** [comment]
+1. Help for Artist/Album/Song categories in media management.

**Comment by folini** [comment]
+1 to a DVD icon

**Comment by G-Driver** [comment]
+1 

<img src="https://cdn2.iconfinder.com/data/icons/simplus-music-and-sound/146/Layer_2-01-512.png">

**Comment by gubi** [comment]
+1

**Comment by nitmir** [comment]
+1

**Comment by NyaChan** [comment]
+1

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by therese-william** [comment]
+1

**Comment by Maelstrome26** [comment]
+1

**Comment by Seb33300** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by jmsche** [comment]
+1

**Comment by zorgbargle** [comment]
+1 I think the existence of both floppy-o and hdd-o justifies the requirement for an optical disc icon.

**Comment by DoomDesign** [comment]
+1 , really could use this! :)

**Comment by popisms** [comment]
+1

**Comment by Entwanderer** [comment]
+1

**Comment by nonide** [comment]
+1

**Comment by dtrunk90** [comment]
+1

**Comment by lordvlad** [comment]
+1

**Comment by Maelstrome26** [comment]
Any update to the integration of this?

**Comment by olya-gary** [comment]
+1

**Comment by DerKnob** [comment]
+1

**Comment by nicmare** [comment]
+1

**Comment by nitmir** [comment]
Note there is a glyphicon-cd in http://getbootstrap.com/components/

**Comment by nicmare** [comment]
glyphicon is deprecated in bs4 !

**Comment by G-Driver** [comment]
+1

**Comment by idleberg** [comment]
+1

as an explanation, i would like to use this for downloadable iso images

**Comment by Crush3rX** [comment]
+1

**Comment by gfauredumont** [comment]
+1

**Comment by MakeWeirdMusic** [comment]
+1 Any sort of disc image would be great... vinyl, cd, dvd, whatever!

**Comment by Darrelk** [comment]
+1 for CD / DVD

**Comment by allanth4** [comment]
+1 for LP Record / CD / cassette tape

**Comment by ricardofrias** [comment]
+1 for CD / DVD

**Comment by jbnv** [comment]
+1, preferably for one that looks like a traditional record.

**Comment by Bruno7kp** [comment]
+1

**Comment by hypnoboutique** [comment]
+1

**Comment by sanek4life** [comment]
+1 CD/DVD/Blu-Ray/Vinyl

**Comment by hypnoboutique** [comment]
It's far from perfect, but I found the **[dot-circle-o](http://fortawesome.github.io/Font-Awesome/icon/dot-circle-o/)** was a passable cd. 

The **[bullseye](http://fortawesome.github.io/Font-Awesome/icon/bullseye/)** could be a vinyl, at a push...

**Comment by tifa** [comment]
+1

**Comment by AaronX** [comment]
+1 DVD/Blu-ray icons/logos

**Comment by vincentvermeer** [comment]
+1

**Comment by AaronX** [comment]
+1

**Comment by Testato** [comment]
+1

**Comment by Iulius90** [comment]
+1

**Comment by seabass** [comment]
+1

**Comment by mardojai** [comment]
+1

**Comment by mardojai** [comment]
+1

**Comment by Crissov** [comment]
JFTR, related Unicode codepoints:

- U+1F39E Film Strip 🎞 
- U+1F4BD Mini Disc 💽
- U+1F4BE Floppy Disc, 9cm (3½") 💾
- U+1F4BF Optical Disc  💿
- U+1F4C0 DVD 📀
- U+1F4FC VCR Tape 📼
- U+1F5AA Black Hard Shell Floppy Disk 🖪&#x1F5AA;
- U+1F5AB White Hard Shell Floppy Disk 🖫&#x1F5AB;
- U+1F5AC Soft Shell Floppy Disk 🖬&#x1F5AC;
- U+1F5AD Tape Cartridge 🖭&#x1F5AD;
- U+1F5B4 Hard Disk 🖴&#x1F5B4;
- U+1F5B8 Optical Disc Icon 🖸&#x1F5B8;

**Comment by Francesko90** [comment]
+1

**Comment by kleuter** [comment]
+1

**Comment by waspeer** [comment]
+1

**Comment by sun2rise** [comment]
+1

**Comment by ZudoMC** [comment]
+1

**Comment by javenosa** [comment]
+1

**Comment by mathiscode** [comment]
+1
Four years and not added, so it looks like they're not interested.

**Comment by pendaresh** [comment]
+1

**Comment by johannsig** [comment]
+1 Need it to represent original content by artist as opposed to covers

**Comment by Caine85** [comment]
+1

**Comment by prestonw** [comment]
Looked for htis today shame it's still missing.

**Comment by littlebirdweb** [comment]
+1

**Comment by mathiscode** [comment]
@davegandy - This has been requested for years. Any hope of it ever getting added?

**Comment by bigweld86** [comment]
+1 It's been like 4 years

**Comment by rene-springmann** [comment]
+1

**Comment by emocibob** [comment]
+1

**Comment by rickmurdock** [comment]
+1

**Comment by underlircs** [comment]
+1

**Comment by mayoalexander** [comment]
+1

**Comment by PieterjanDeClippel** [comment]
Actually there is a unicode character for a cd-rom (229a). There may be even multiple.
just add following custom css:
`.fa-cd:before{content: "\229a";}`
and use the class:
`<i class="fa fa-cd"></i>`

**Comment by EddFigueiredo** [comment]
+1000 I'd really appreciate a compact disc / CD-ROM icon

**Comment by NikolaDeveloper** [comment]
+1

**Comment by gilliek** [comment]
+1

> What's the semantic use you're looking for?

@davegandy  ISO file, DVD, Blueray, etc. Semantic seems pretty obvious to me and apparently to many people. I was very surprise not to find this icon in Font-Awesome. Especially when I find an icon of a [shower](http://fontawesome.io/icon/shower/) or a [bath](http://fontawesome.io/icon/bath/) in the latest release ;) I don't understand what is the problem of adding a simple CD.

**Comment by kirilmaz** [comment]
+1

**Comment by sselman0** [comment]
+1 
why is it not there?

**Comment by timtjtim** [comment]
A lot of icons can now be "assembled" with the layering and masking features in FA5. I've managed to make a pretty reasonable facsimile of a CD Album:

```
    <span class="fa-layers fa-fw" style="font-size:20px">
      <i class="fas fa-square-full"></i>
      <i class="fas fa-square-full fa-inverse" data-fa-transform="shrink-3"></i>
      <i class="fas fa-circle" data-fa-transform="shrink-4"></i>
      <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-20"></i>
    </span>
```

**Comment by sensibleworld** [comment]
Hey folks! Happy to announce that this will be included in our 5.1 release!

**Comment by sensibleworld** [comment]
I'm not sure these exist anymore ;P https://fontawesome.com/icons?d=gallery&q=compact

**Comment by gr8kodr** [comment]
> I'm not sure these exist anymore ;P https://fontawesome.com/icons?d=gallery&q=compact

fa-compact-disc ( unicode = f51f ) icons exist in solid, regular and light sets in fa v5.8

fa-compact-disc would suffice for a data disc icon, but it would be nice to have a combination icon to use for music/video ... possibly fa-cd-music and fa-cd-movie

the combo icons having the basic compact disc icon, with the contained media type as an overlay, would be handy in the case of media collections

**Comment by sensibleworld** [comment]
@gr8kodr I was joking that CDs no longer exist :)

But yes, combo icons would be nice!
