### ISSUE TITLE
Icon Request: fa-shoes

### ISSUE THREAD

**Issue by cooliyev** [FortAwesome/Font-Awesome#7020]
:+1: 

Hello I felt in love to your Font at first sight. For my website i need 3 concret object asap please.
1. shoes
2. cosmetics or pomade
3. lingerie

**Comment by tagliala** [comment]
Hi,

if you need the above icons in a short while you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

there are already requests for shoes: #3704 #3473
cosmetics: maybe #4844
lingerie: maybe #4964

I'm going to close this one. if you want to request other icons, please open individual requests: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
