### ISSUE TITLE
Icon Request: fa-houzz

### ISSUE THREAD

**Issue by MikeAyerTDS** [FortAwesome/Font-Awesome#7024]
Hello-

I would love a houzz icon to utilize on sites. Can you guys create one?

http://www.houzz.com/

Thanks,
Mike Ayer

**Comment by TheChen5** [comment]
Dupe of #2039 .
Go " +1 " that one.
*Search before creating issue.*

**Comment by tagliala** [comment]
@TheChen5 thanks
