### ISSUE TITLE
Icon request: fa-quiz, fa-quiz-plus

### ISSUE THREAD

**Issue by caih** [FortAwesome/Font-Awesome#7030]
Hello! Recently I was creating a quiz project, and of course I need a quiz icon. Some examples:
![image](https://cloud.githubusercontent.com/assets/12991459/8864067/7727c440-31d0-11e5-91c3-9ad3662babc2.png)
![image](https://cloud.githubusercontent.com/assets/12991459/8864092/a93eefe4-31d0-11e5-9ccd-8dbf4b95b4c3.png)
![image](https://cloud.githubusercontent.com/assets/12991459/8864097/ba6ada9e-31d0-11e5-80e0-9dc0faaa6bfa.png)

**Comment by Arjunpxl** [comment]
This icons looks more like a check list. 
Instead i suggest to put something like this

![image](https://cloud.githubusercontent.com/assets/17943377/24689670/b1b8a382-19e5-11e7-8209-a551bfda73d3.png)

**Comment by AurelianSpodarec** [comment]
Arjunpxl - that reminds me of 'About Page' - and I used it for about page. I agree with caih.

**Comment by JcbPrn** [comment]
did you find any nice icons?

**Comment by tagliala** [comment]
I'm going to consider this request closed by [ballot-check](https://fontawesome.com/icons/ballot-check?s=solid ), available in FA Pro
