### ISSUE TITLE
Icon request: numeric and decimal (19 and 1.9)

### ISSUE THREAD

**Issue by rbatllet** [FortAwesome/Font-Awesome#7032]
Please add numeric and decimal icons. They're very basic icons !

**Comment by tagliala** [comment]
sorry, I didn't get this request

could you please clarify?

**Comment by rbatllet** [comment]
An icon that represents a numerical value, and another icon that represents a decimal value.

**Comment by tagliala** [comment]
could you please post examples?

could the numerical value be represented by a hashtag? #1123

**Comment by rbatllet** [comment]
For example:   

An icon that represents the text value "19" for numeric values 
Another icon that represents the text value 1.9 for decimal value

could the digits be showed in a little different position?

Without a hashtag, I think...

**Comment by tvirelli** [comment]
Here is a solution:
http://jsfiddle.net/5wfzz46y/

Also, one right from the fontawesome blog! http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by tagliala** [comment]
I'm still not convinced about the use case and the title, I would like an example but the request itself is fine

**Comment by tagliala** [comment]
just found this one: #1347

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
