### ISSUE TITLE
Icon request: fa-shop

### ISSUE THREAD

**Issue by stijnvanbael** [FortAwesome/Font-Awesome#7034]
For representing physical shop locations. Example: 

![](http://simpleicon.com/wp-content/uploads/shop-4.png)

**Comment by donjajo** [comment]
Exactly looking for this too!

**Comment by TheChen5** [comment]
Dupe of #1958 .
"+1" that one.
*Search before creating.*

**Comment by tagliala** [comment]
@TheChen5 thanks

**Comment by pmarsilio** [comment]
+1
