### ISSUE TITLE
New Icon Request

### ISSUE THREAD

**Issue by bwilbourne** [FortAwesome/Font-Awesome#7035]
Please create the following icons:

Ballet shoe
Tap shoe
Jazz shoe

Would like to use them for my dance website.

Thx!

**Comment by tagliala** [comment]
Sorry, can't leave this open

You should split this request in individual requests providing example and proper titles

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
