### ISSUE TITLE
Icon Request: fa-fattypocket

### ISSUE THREAD

**Issue by smashyou** [FortAwesome/Font-Awesome#7038]
my company logo and I am trying to use it on my personal website. Thank you!

http://fattypocket.com/new/img/FP_Logo_R_Bubble.png

**Comment by TheChen5** [comment]
As tagliala recommends (from issue #4014), if your company isn't mainstream you should consider a custom build w/ fontello.com, icomoon.io, fontastic.me .

**Comment by TheChen5** [comment]
I don't think this will ever make it.
It is too big of a logo to fit into a small space.
There are too much detail.

**Comment by tagliala** [comment]
I have to agree with @TheChen5, but leaving this open because it is a valid request
