### ISSUE TITLE
Current fa-compass is off-center, and won't spin cleanly

### ISSUE THREAD

**Issue by spiderr** [FortAwesome/Font-Awesome#7046]
Here is a code example that shows the issue:

    <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-compass fa-inverse fa-spin fa-stack-2x"></i>
    </span>

Thanks! Love the icons as does most of humanity < fa-smile-o >

**Comment by tagliala** [comment]
I cannot confirm. There are spinning issue with stacked icons and `fa-compass` as well as with many other icons, but it should not depend on the centering

Open the following links in two tabs and switch between them
http://fontawesome.io/icon/compass/
http://fontawesome.io/icon/circle-o/

If you want, you can provide a fiddle showing the issue. You can use this one as a base: http://jsfiddle.net/tagliala/e9yfxsfj/

I'm going to close this one in favour of #671 but feel free to comment here if you find something else

**Comment by spiderr** [comment]
Here is a fiddle that shows how it is just slightly off center

http://jsfiddle.net/Lpur9ek1/1/
