### ISSUE TITLE
Icon Request: fa-left-shark

### ISSUE THREAD

**Issue by arshiya-singh** [FortAwesome/Font-Awesome#7050]
I've been trying to make one on my own but I ran into a lot of CSS issues when its font wasn't Font Awesome

**Comment by tagliala** [comment]
sorry, I didn't get this request

what is a left shark?

**Comment by Fatbat** [comment]
Left shark was the name bestowed on the costumed dancer that couldn't dance in the Katy Perry Super Bowl halftime show. Just Google it and you'll see. It was a bit of a viral meme but, IMO, it's pretty obscure subject matter as far as this icon set goes.

**Comment by tvirelli** [comment]
Yeah, not really something I think needs to be in FA, as this will only be a cultural fad. On the other hand, they did add Pied Piper!

**Comment by tagliala** [comment]
https://images.indiegogo.com/file_attachments/1202830/files/20150207003244-my-edit2.jpg?1423297964

This one?

Don't know how to label it... This is not a brand, am I right?

**Comment by TheChen5** [comment]
I don't think it should be a brand
People do earn money based off this
And Katy Perry tried to trademark it but failed
I don't think think it should be a FA icon too

**Comment by tagliala** [comment]
Closing here because of inactivity

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
