### ISSUE TITLE
Nuget Version

### ISSUE THREAD

**Issue by maherAshori** [FortAwesome/Font-Awesome#7051]
Hi
please update the Nuget version
nuget version is 4.2.0
[https://www.nuget.org/packages/FontAwesome/]

tnx

**Comment by tagliala** [comment]
sorry, the nuget package is not managed by us

**Comment by maherAshori** [comment]
ops! tnx to u

**Comment by tiesont** [comment]
There's quite a few packages. I've updated mine: https://www.nuget.org/packages/Font.Awesome/

**Comment by maherAshori** [comment]
Tnx to u [ :+1: ]

**Comment by tagliala** [comment]
Closing here
