### ISSUE TITLE
Icon Request: Digital Signature

### ISSUE THREAD

**Issue by andreasvad** [FortAwesome/Font-Awesome#7052]
Hi

I am making af a web application where the end user should digital sign a contract. (A digital signature). The contract that should be signed i digital PDF document. I have look through you cool icon libary and not find any that fit that purpose. I would be really nice if you could make an icon. ;-)

Icon could something like the flowing pictures:
![icon-adobe-cds](https://cloud.githubusercontent.com/assets/13522194/8907569/286f6796-3477-11e5-87fc-d7a88e9b77b2.gif)
![download](https://cloud.githubusercontent.com/assets/13522194/8907588/49787dba-3477-11e5-971a-02fe2a18d938.png)
![download 1](https://cloud.githubusercontent.com/assets/13522194/8907601/645bc2d6-3477-11e5-8d15-62e8b2bc6d03.png)

I hope you can help.

Best regards, Andreas Vad

**Comment by tagliala** [comment]
maybe a duplicate of #4420 or #1182

**Comment by andreasvad** [comment]
That is correct.

**Comment by demon101** [comment]
+1
