### ISSUE TITLE
Icon Request: fa-file-new

### ISSUE THREAD

**Issue by tiagobuffon** [FortAwesome/Font-Awesome#7053]
Something like this:

![](https://cdn2.iconfinder.com/data/icons/designers-and-developers-icon-set/32/add_file-256.png)

![](https://cdn1.iconfinder.com/data/icons/files-3/24/Add-File-256.png)

**Comment by TheChen5** [comment]
Dupe of issue #4998 .
+1 that.

**Comment by tagliala** [comment]
@TheChen5 thanks
