### ISSUE TITLE
Font does not show up on Apple Pages for Mac font selection pulldown on the sidebar

### ISSUE THREAD

**Issue by pozix604** [FortAwesome/Font-Awesome#7056]
After installing the OTF version of FontAwesome on a Mac, it is not possible to select the font using the Format sidebar font selection pulldown in *Pages* because the font does not show up in the list at all.

If text already formatted using the FontAwesome font is insert into a *Pages* document and a cursor is placed on that text, the font pulldown shows an empty font name. Clicking on that pulldown makes the font "jump" to default to the first font sorted alphabetically.

The same problem does not happen on *Word for Mac*. The font shows up properly.

The same problem does not happen if using the OS font dialog box. The font shows up properly.

Although this may be a *Pages* problem, it is possible that some setting in the font is making it not show properly. Fixing this would make the font much more accessible to users using *Pages*.

A screenshot of the empty font pulldown when FontAwesome text is selected is as follows:

![Screenshow of problem](http://i.imgur.com/hOjawzc.png)

**Comment by tagliala** [comment]
I think I can confirm this

**Comment by ramsey** [comment]
I can confirm the same issue is occurring for me in Apple Pages, but I have a work-around: If you choose Format > Font > Show Fonts, a separate Fonts window opens, giving you access to select "FontAwesome" from the "All Fonts" list. You may also open this window with ⌘T.

**Comment by tagliala** [comment]
Sorry but I don't know how to help. Adding to 5.0.0 milestone so Dave will take a look

**Comment by phil-travelbytes** [comment]
+1  font awesome is available for me in Photoshop, but when I search thru the fonts in pages its not there...

**Comment by maxbrodie** [comment]
For some reason, it **does** show up in the Format --> Font --> Show Fonts menu:

![screen shot 2015-11-06 at 3 41 35 pm](https://cloud.githubusercontent.com/assets/566357/11008213/0cf2e67a-849d-11e5-8b3c-27dd4e270468.png)

Fontawesome works fine in Pages if I choose it from this menu.

**Comment by davegandy** [comment]
The same is true in Keynote. This isn't something I can fix, so I'm going to close. @maxbrodie has the right solution.

**Comment by fu-raz** [comment]
@ramsey You are my hero

**Comment by joshangehr** [comment]
Perhaps this is because by default, Pages displays fonts from the English collection? I'm not sure if this is the case, but that's what it seemed like when I made the adjustments.

**Comment by Crissov** [comment]
Would this issue be solved by implementing #222?

**Comment by tagliala** [comment]
This is solved for me.

macOS 10.13.3, Pages 6.3.1

![image](https://user-images.githubusercontent.com/556268/36357983-bfb59bd0-1506-11e8-865a-94b9902e68d4.png)

**Comment by doliG** [comment]
Hello guys, sorry for commenting an old issue, but I have a weird problem: when I copy/paste an icon from the cheatsheet, Pages didn't display it correctly.

I have a square with a question mark inside.

Of cours, I have selected Font awesome as my font...

Any idea ?

**Comment by tagliala** [comment]
@doliG if https://fontawesome.com/how-to-use/on-the-desktop/other-topics/troubleshooting doesn't help, please open a new issue by filling out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug-report.md)

Please make sure to provide all the information you can
