### ISSUE TITLE
Icon Request: Microsoft Edge/Project Sparta

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [FortAwesome/Font-Awesome#7059]
I'm not sure if this has been recently added along with the regular IE icon, but since this browser is coming out soon, I think this should be added.  Here's what it looks like.

![example](http://cdn.winbeta.org/sites/default/files/news/edgelogo.jpg)

**Comment by tagliala** [comment]
the example is broken

**Comment by CoWinkKeyDinkInc** [comment]
I fixed it now, @tagliala

**Comment by tagliala** [comment]
thanks

**Comment by DennaGherlyn** [comment]
+1
Equal rights for all browsers. (Although the "new" logo doesn't look that different from the IE...)

**Comment by peiche** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1 since Robert McLaws asked so nicely and is such an awesome guy:
https://twitter.com/robertmclaws/status/626830080988200960

**Comment by CoWinkKeyDinkInc** [comment]
Thanks Dave!

**Comment by frekele** [comment]
I consider the icon IE != EDGE.
+1

**Comment by G-Driver** [comment]
+1

**Comment by nadirabid** [comment]
+1

**Comment by vebbo2** [comment]
+1

**Comment by yconoclast** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by G-Driver** [comment]
wohooo tnx dave
