### ISSUE TITLE
Icon Request: fa-buddha

### ISSUE THREAD

**Issue by Hansjoerg2** [FortAwesome/Font-Awesome#7060]
Hi, 

it would be cool to have an icon for zendesk or a buddha

thank you so much

**Comment by tagliala** [comment]
zendesk: #5652

**Comment by tagliala** [comment]
could you please post an example?

**Comment by truls1502** [comment]
My example is @tagliala 

a) Zendesk: https://www.zendesk.com/company/brand-assets/#logo (it is great to have both "icon + zendesk" and only "icon") which is referring to #5652 

b) Buddha (for Zendesk): https://www.zendesk.com/company/brand-assets/#mentor

**Comment by aethior** [comment]
Buddha was the initial logo of Zendesk.
In 2016 the brand was completely redesigned.

More info:
1. https://medium.com/@WebdesignerDepot/zendesk-releases-a-new-logo-74d1e35b860e
2. https://www.fastcompany.com/3064874/zendesk-unveils-a-dynamic-new-brand-inspired-by-classic-danish-design

@tagliala I think you can close here.
