### ISSUE TITLE
Icon Request: fa-radar (monitor)

### ISSUE THREAD

**Issue by heruan** [FortAwesome/Font-Awesome#7068]
A "radar" monitoring icon could be useful to represent network monitoring menu items or buttons.
For example:
<img src="https://cloud.githubusercontent.com/assets/851745/8951650/d689c8a4-35cf-11e5-8779-bc9d034a37e4.png" alt="radar1" width="128">
<img src="https://cloud.githubusercontent.com/assets/851745/8951656/da3453a2-35cf-11e5-82e9-070b8f96f3f1.png" alt="radar2" width="128">
<img src="https://cloud.githubusercontent.com/assets/851745/8951658/dd017006-35cf-11e5-83dd-4bcf37e720f6.png" alt="radar3" width="128">

**Comment by tagliala** [comment]
duplicate of #5659, please +1 that request

closing here

**Comment by heruan** [comment]
It's not a duplicate, see the image link in #5659: that's a satellite dish, not a radar monitor.

**Comment by tagliala** [comment]
Sorry, reopening as radar monitor

**Comment by tvirelli** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by maximvd** [comment]
+1

**Comment by kwinne** [comment]
+1

**Comment by apinner** [comment]
+1

**Comment by Pasha49** [comment]
+1

**Comment by HambroRoofing** [comment]
+1

**Comment by JoranBeaufort** [comment]
+1 Any word on progress? Awesome would be radar + radar-spinner where only the scan line spins :)

**Comment by SynchroM** [comment]
+1

**Comment by jarrodbell** [comment]
+1

**Comment by besharp** [comment]
+1

**Comment by danbernier** [comment]
+1

**Comment by dumboxp** [comment]
+1   A radar-icon would be great and very useful (the first example is great) A spinning version e.g. to visualise a "scanning"-tasks would be perfect as well.

**Comment by poblabs** [comment]
+1

**Comment by benmccallum** [comment]
+1

**Comment by sedrakpc** [comment]
+1

**Comment by geri777** [comment]
+1

**Comment by KurtJacobson** [comment]
+1

**Comment by lichtamberg** [comment]
+1

**Comment by DaniloOliveira28** [comment]
+1

**Comment by inakuhn** [comment]
+1

**Comment by reneseses** [comment]
+1

**Comment by erijonhson** [comment]
+1

**Comment by fdamore-xnoova** [comment]
+1

**Comment by venarius** [comment]
+1

**Comment by HarpunDK** [comment]
+1

**Comment by NickJorens** [comment]
A spinning one would be awesome :wink:

**Comment by DavydeVries** [comment]
+1

**Comment by inakuhn** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/radar?style=duotone
