### ISSUE TITLE
Icon Request: fa-mouse-pointer-o

### ISSUE THREAD

**Issue by MaxArt2501** [FortAwesome/Font-Awesome#7070]
The newly added mouse pointer icon (#1095) is the classic, black Mac OS X pointer.
But Linux and Windows (above all) default to a _white_ pointer.

(Also, the gloved hand pointer is too reminiscent of Mac OS X. But that's another issue.)

**Comment by tvirelli** [comment]
+1

**Comment by gjb2048** [comment]
+1

**Comment by byelims** [comment]
+1

**Comment by tagliala** [comment]
This icon is available in Font Awesome Pro

https://fontawesome.com/icons/mouse-pointer?style=regular
