### ISSUE TITLE
Icon Request: fa-flower

### ISSUE THREAD

**Issue by pfrankowski** [FortAwesome/Font-Awesome#7071]
Simple shape like trees and pagelines from current collection, 
similar to:
http://icons.iconarchive.com/icons/fasticon/nature/256/Red-Flower-icon.png

**Comment by tagliala** [comment]
duplicate of #2037 , please +1 that request and post there your example

closing here

**Comment by johnnyshields** [comment]
Flower is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.
