### ISSUE TITLE
Icon Request: fa-tooth, fa-door, fa-bus, fa-palm, fa-sea + read more

### ISSUE THREAD

**Issue by alex21** [FortAwesome/Font-Awesome#7073]
I need:
tooth icon
door icon
windows icon (clasic windows not MS windows)
Bus icon
palm icon
sea icon
drug icon
wine icon
candle icon

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please split this request in individual requests, having care of searching for duplicates before

There are several duplicates and a bus is already here

closing here
