### ISSUE TITLE
Publish 4.4 to npm

### ISSUE THREAD

**Issue by btd** [FortAwesome/Font-Awesome#7075]
Hello.
At npm current version is 4.3. Could you pls do `npm publish`?

**Comment by tagliala** [comment]
@juliankrispel

**Comment by juliankrispel** [comment]
you know your job @tagliala

**Comment by juliankrispel** [comment]
@btd @tagliala done

**Comment by btd** [comment]
Thanks

**Comment by tagliala** [comment]
@juliankrispel thansk, really appreciate!
