### ISSUE TITLE
Icon Request: fa-metronome

### ISSUE THREAD

**Issue by maxsennin** [FortAwesome/Font-Awesome#7076]
Hi,

I'd like an icon of metronome!

Something like this : ![metronome](https://cloud.githubusercontent.com/assets/13066669/8963435/5f97175a-3620-11e5-8460-9ee2373f6789.png)

Thanks a lot!

**Comment by TheChen5** [comment]
Dupe of #6232
+1 that
:mag_right: before:heavy_plus_sign:

**Comment by maxsennin** [comment]
Oups

**Comment by tagliala** [comment]
@TheChen5 thanks

closing here
