### ISSUE TITLE
Combine /cheatsheet/ and /icons/ together

### ISSUE THREAD

**Issue by llahnoraa** [FortAwesome/Font-Awesome#7078]
I have noticed the confusion when it comes to `/cheatsheet/` page vs `/icons/` page. Why not merge them together and make it easier for people to copy the icon right away and paste it in app such as Sketch or Photoshop? Just a thought.

Keep up the good work!

**Comment by sensibleworld** [comment]
Lots of improvements to our icon search over the years!

https://fontawesome.com/search
