### ISSUE TITLE
Icon request: icon-shower, icon-bath

### ISSUE THREAD

**Issue by bhubbard** [FortAwesome/Font-Awesome#708]
Hey guys,

Was wondering if someone could work on some real estate icons. <s>(Bed, Bath, House, etc).
Maybe use the black ones found here: http://www.studiopress.com/graphics/real-estate-icons</s>

**Comment by liamcreative** [comment]
+1 icon-shower
+1 icon-bath

**Comment by charly-housl** [comment]
+1 fa-shower
+1 fa-bath

**Comment by thmsmtylr** [comment]
+1 fa-shower
+1 fa-bath

**Comment by danniejpt** [comment]
+1 fa-shower
+1 fa-bath

**Comment by ivan206** [comment]
+1 fa-shower
+1 fa-bath

**Comment by jcglp** [comment]
+1 icon-shower
+1 icon-bath

**Comment by dezertdezine** [comment]
+1 fa-shower
+1 fa-bath

**Comment by suberimakuri** [comment]
+1 fa-shower
+1 fa-bath

Thank you for recently release fa-bed.

**Comment by tegola** [comment]
+1 for bath and/or shower. It's only icon missing for real estate project I'm working on.

**Comment by heliobentes** [comment]
+1

**Comment by owahab** [comment]
+1 fa-shower
+1 fa-bath

**Comment by dangnelson** [comment]
+1 fa-shower
+1 fa-bath

**Comment by joshyws** [comment]
+1 fa-shower
+1 fa-bath

**Comment by basnan** [comment]
+1 fa-shower
+1 fa-bath

**Comment by luchopintado** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-fan
+1 fa-cold-water
+1 fa-hot-water
+1 fa-thermometer
+1 fa-thermo
+1 fa-bathtub

for hotel features...

**Comment by Yaboe** [comment]
+1 Shower
+1 Bath
+1 Basement (T.V. & a Couch maybe?)
+1 Sunroom or Addition
I think most people in this thread are looking for shower and bath only.  I'm looking for an icon for each section of the house.

**Comment by tagliala** [comment]
this request is only about *icon-shower*

**Comment by Yaboe** [comment]
+1

**Comment by twinshen** [comment]
+1 it is really necessary.

It could be something like this: https://cdn2.iconfinder.com/data/icons/cosmo-furniture/40/bath-128.png

**Comment by nodoze** [comment]
+1 bath
+1 shower

**Comment by tomasswood** [comment]
+1 Shower/Bath

**Comment by laviku** [comment]
+1

**Comment by jmc167** [comment]
+1 fa-shower
+1 fa-bath

**Comment by mediabeastnz** [comment]
+1 great for rental sites.

![suihku](https://cloud.githubusercontent.com/assets/909749/7330732/4c4300a6-eb48-11e4-9232-b29ab2fad800.jpg =100x100)

**Comment by aeronauth** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-fan
+1 fa-thermometer

**Comment by xoomboom** [comment]
+1

**Comment by seven7seven** [comment]
+1 fa-shower
+1 fa-bath

**Comment by guihatano** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-bed

**Comment by leocaseiro** [comment]
For bedroom you can use:
http://fortawesome.github.io/Font-Awesome/icon/bed/

Parking, Garage you can use:
http://fortawesome.github.io/Font-Awesome/icon/car/

The only one which is missing still is the bathroom

**Comment by leocaseiro** [comment]
Reference from Glyphicons 
![screen shot 2015-05-01 at 5 02 06 pm](https://cloud.githubusercontent.com/assets/940070/7427654/bf4c6792-f023-11e4-8fa5-3c6b7aed4a22.png)

**Comment by dscafati** [comment]
+1

**Comment by tzusman** [comment]
I just launched [CustomFontIcons.com](https://customfonticons.com/), a place to get crowd-commissioned icons.  I also launched a free font icon set.  A shower icon is part of that set, if you're interested.

**Comment by nbankzy** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-tap

**Comment by leocaseiro** [comment]
For the main time, I'm using this SVG, be free to use it: https://gist.github.com/leocaseiro/9e41ef60ee452756fde5

Using CSS, you can change the colours and size. Enjoy it

**Comment by FastEddie8888** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-tap
+1 fa-toilet

**Comment by solmstead25** [comment]
+1

**Comment by roborich** [comment]
+1

**Comment by ChaosPower** [comment]
+1

**Comment by LukeStanbery89** [comment]
+1

**Comment by endguy** [comment]
+1

**Comment by jahka** [comment]
+1 fa-bath

**Comment by sketchybear** [comment]
+1 fa-bath
+1 fa-shower

**Comment by christhesoul** [comment]
+1 fa-bath
+1 fa-shower

**Comment by rustamli** [comment]
+1 fa-bath
+1 fa-shower
+1 fa-sofa (or fa-chair) to indicate number of receptions - smth like this: ![chair] (https://cdn3.iconfinder.com/data/icons/glypho-free/64/sofa-chair-16.png) [src](https://www.iconfinder.com/icons/353396/chair_furniture_living_sofa_icon#size=16)

**Comment by nacayoda** [comment]
+1 fa-bath
+1 fa-shower

Thanks for the great work folks. Hope these additions make it in soon.

**Comment by djwave28** [comment]
+1 fa-bath
+1 fa-shower

Definitely +1 for fa-shower
Wonderful icon library, but missing shower or more a house/hotel  set .

**Comment by braewood** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon

**Comment by josewilsoncc** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon

**Comment by martinlindhe** [comment]
+1

**Comment by husayt** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon

**Comment by alexshnur** [comment]
+1 icon-shower

**Comment by brendanmcoffey** [comment]
+1 icon-shower

**Comment by mactedder** [comment]
+1 icon-shower
+1 icon-bath
+1 icon-toilet

**Comment by pixelscienceNZ** [comment]
+1 icon-shower
+1 icon-bath
+1 icon-toilet

**Comment by johnmcclumpha** [comment]
+1 icon-shower
+1 icon-bath

**Comment by mitchellj4** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon

This thread has been around a while, is there any progress on it's completion.  It looks like these additional icons are needed by a multitude!

**Comment by fahad86** [comment]
+1 fa-shower
+1 fa-triangular-ruler

**Comment by ivobenedito** [comment]
+1 icon-shower
+1 icon-bath

**Comment by antongorodezkiy** [comment]
+1 bath

**Comment by michaelthorne** [comment]
+1 fa-bath
+1 fa-shower

**Comment by PaulStevensLM** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-tap
+1 fa-toilet

**Comment by williambyrd80** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-toilet

**Comment by jtgweeks** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-toilet

**Comment by Rombecchi** [comment]
+1 icon-shower
+1 icon-bath
+1 icon-toilet

**Comment by yaratrump** [comment]
+1 fa-bath

**Comment by eastcoastjac** [comment]
+1 shower
+1 bath
+1 toilet

In fact, there's a whole range of "hotel" icons that would be most useful, eg:
Fan
Fireplace
Heater
Towels
TV, Satellite TV
Lock-up Safe
No Smoking
fuel station

This seems to be a popular request, wondering why you guys haven't gotten to it yet :-)
I'm currently using a battery to represent bath, and an upside down funnel for the shower, but its not really ideal.
Take a look: http://lydenburgmanorhouse.co.za/rooms.html#luxury


Thanks in anticipation :-)

**Comment by thibahilpert** [comment]
+1

**Comment by williamxsp** [comment]
+1 <3

**Comment by jaqueventurim** [comment]
+1

**Comment by marciocleberbrazil** [comment]
+1

**Comment by wviveiro** [comment]
+1

**Comment by tyroga** [comment]
**+1** would be great to have these as options for real estate sites.

**Comment by sheebypanda** [comment]
+1

**Comment by freemind-** [comment]
+1

**Comment by jbarbede** [comment]
+1

**Comment by ksoldau** [comment]
+1

**Comment by ryanstockau** [comment]
+1 for bath and shower! The others would be nice too, but these two are probably the most urgent ones.

**Comment by novalore** [comment]
+1 fa-bath
+1 fa-shower
+1 fa-sofa (or fa-chair)

**Comment by prasadgupte** [comment]
+1 fa-bath
+1 fa-shower

**Comment by guayom** [comment]
+1

**Comment by zivc** [comment]
+1

**Comment by luncht1me** [comment]
+1 fa-bath or fa-shower

**Comment by petriadrian** [comment]
+1 fa-bath or fa-shower

**Comment by jk-1001** [comment]
+1 fa-bath or fa-shower

**Comment by G-Driver** [comment]
+1 icon-shower
+1 icon-bath

**Comment by angelinazooma** [comment]
+1 icon-shower
+1 icon-bath

**Comment by kafenio** [comment]
+1 fa-shower
+1 fa-bath

**Comment by thingNumber1** [comment]
+1 fa-bath

**Comment by gianfaye** [comment]
+1 fa-shower
+1 fa-bath

**Comment by mrmrsmall81** [comment]
+1 fa-bath
+1 fa-shower

**Comment by krypsin** [comment]
+1 fa-bath
+1 fa-shower

**Comment by Samda** [comment]
+1

**Comment by kirkberryman** [comment]
+1 fa-bath
+1 fa-shower

**Comment by barrycrous** [comment]
+1 fa-bath
+1 fa-shower

**Comment by robofop** [comment]
+1 fa-bath
+1 fa-shower

**Comment by Grantwayword** [comment]
+1 fa-bath
+1 fa-shower

**Comment by genni951** [comment]
+1

**Comment by nstiac** [comment]
+1+1+1+1+1+1+1 

 !!! there's tons of people requesting this since 2013 ... what's the hold?

**Comment by laliev** [comment]
+1 icon-shower
+1 icon-bath

**Comment by laliev** [comment]
+1 icon-shower
+1 icon-bath

**Comment by laliev** [comment]
+1 icon-shower
+1 icon-bath

**Comment by giupenni** [comment]
+1 icon-shower
+1 icon-bath

**Comment by BillyBowyer** [comment]
+1 icon-shower
+1 icon-bath

I thought this would have been one of the first ever icons made, seems strange its not available already.

**Comment by amelholic** [comment]
+1 icon-shower
+1 icon-bath

**Comment by robertholf** [comment]
+1 icon-shower
+1 icon-bath

**Comment by chisangu** [comment]
+1 icon-shower
+1 icon-bath

**Comment by jjeroennl** [comment]
+1

**Comment by Robot2906** [comment]
+1

**Comment by aussiDavid** [comment]
+1

**Comment by BillyBowyer** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by alexpechkarev** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-bed
+1 fa-living-room

**Comment by kubik101** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon

**Comment by fazedesigns** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon

We are almost there! There is Car and Bed but no Bathroom icons... I have had to use another icon set for 3 realestate sites now :(   sad times..

**Comment by ACXgit** [comment]
+1

**Comment by mikeantonelli** [comment]
+1 fa-shower
+1 fa-bath

**Comment by lovePizza** [comment]
+1

**Comment by frotherDoc** [comment]
+1

**Comment by MarGraz** [comment]
+1

**Comment by bjmoon** [comment]
+1

**Comment by dave4jr** [comment]
+1

**Comment by Rombecchi** [comment]
+1 shower
+1 bath
+1 toilet

**Comment by wolvyreen** [comment]
+1 shower
+1 bath
+1 toilet

sheesh!  this request has been going since January 2013 and still these icons arent available.  You guys do awesome work but really now,  cant you guys get with the program by now??

**Comment by CrashyBang** [comment]
+1

**Comment by steiha** [comment]
+ diaper changing table
+ baby
+ shower
+ toilet
+ bath
+ lavatory

**Comment by granitibrahimi** [comment]
+1

**Comment by Hani79** [comment]
+1 shower
+1 bathtub
+1 toilet

**Comment by ashburystudios** [comment]
+1 fa-shower

**Comment by syanaputra** [comment]
+1

**Comment by mcmatthew** [comment]
+1

**Comment by naveed-ahmad** [comment]
+1 for IMDB as well

**Comment by simonmilz** [comment]
+1 any news on this request? Already +1 it in 2014...

**Comment by alxzndr** [comment]
another +1 for shower and bath icons

**Comment by mikeantonelli** [comment]
Many issues have been closed referencing this one, going back to 2013. The issue description calls out shower and bath specifically and although there are mention of many others, my count is ~140 +1's for fa-shower and fa-bath.

@leocaseiro provided a bath sample:
* https://gist.github.com/leocaseiro/9e41ef60ee452756fde5

@mediabeastnz provided a shower sample:
* https://cloud.githubusercontent.com/assets/909749/7330732/4c4300a6-eb48-11e4-9232-b29ab2fad800.jpg

Tagging a few recent contributors: @davegandy @tagliala -- any tips/advice on getting this closed?

**Comment by giupenni** [comment]
+1 Mike Antonelli

info@giuseppepennisi.com
hangout: giupennis78@gmail.com
skype: giuseppe.pennisi.78
Phone: +39 347 992 9052

2016-06-29 5:58 GMT+02:00 Mike Antonelli <notifications@github.com>:

**Comment by jelmersmid** [comment]
+1 for fa-bath and fa-shower, alias fa-bathroom
Thanks!

**Comment by armandino** [comment]
+1 shower icon
+1 bath icon
+1 toilet icon
+1 garage icon
+1 fa-sofa (or fa-chair)

**Comment by IanSimpson** [comment]
Adding the 292nd "+1" to this page.

**Comment by icreatesolutions** [comment]
+1

**Comment by MasterJuan** [comment]
+1

**Comment by asaletnik** [comment]
+1

**Comment by jlmbaka** [comment]
+1

**Comment by webbed88** [comment]
+1 fa-shower
+1 fa-bath

**Comment by umanga907** [comment]
+1 fa-shower
+1 fa-bath

**Comment by babaa** [comment]
+1 fa-shower
+1 fa-bath

**Comment by vannkorn** [comment]
+1 fa-shower
+1 fa-bath
+1 fa-surface

**Comment by davegandy** [comment]
Added bath and shower to 4.7.0-wip branch. Closing.

**Comment by davegandy** [comment]
Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!

**Comment by zivc** [comment]
🙌  winners! 🙌

**Comment by suberimakuri** [comment]
Thank you Dave and Linode!
Much appreciated.

**Comment by leocaseiro** [comment]
So happy: http://fontawesome.io/icon/bath/

Uhuulll!!!!
