### ISSUE TITLE
Can't Use FontAwesome in HTML Select on Mac

### ISSUE THREAD

**Issue by bsohlml** [FortAwesome/Font-Awesome#7080]
![screen shot 2015-07-29 at 11 34 48 am](https://cloud.githubusercontent.com/assets/12800996/8968416/dd624eae-35f1-11e5-84af-149b7f2f78fc.png)
![screen shot 2015-07-29 at 11 34 53 am](https://cloud.githubusercontent.com/assets/12800996/8968417/dd633cd8-35f1-11e5-9e99-77b98193a6d3.png)

Using the unicode 'cheat codes' for Font Awesome in HTML select option drop-downs does not work on the Mac (10.10, Chrome or Safari). Windows is fine. The icons in the dropdown option list show with the broken icon seen above. Once an item is selected however, the correct icon does appear in the select control itself. Is this a known issue?

**Comment by tagliala** [comment]
please use the proper thread #996

**Comment by gestudio** [comment]
I am stuck with the exact same problem.

**Comment by davidpatters0n** [comment]
Likewise also encountering the same issue

**Comment by tagliala** [comment]
please continue on #996
