### ISSUE TITLE
Broken PDF printout

### ISSUE THREAD

**Issue by ad-m** [FortAwesome/Font-Awesome#7082]
Hello,

I am would like broken print-out at http://fortawesome.github.io/Font-Awesome/cheatsheet/ .

I don't think it is good idea to put ads in printout:
>  Want clean, minimalist icons? Check out Black Tie, the new multi-weight icon font from the maker of Font Awesome. 

I attach printout from my browser: http://files.jawne.info.pl/private_html/2015_07_25da60f8717128a5b78fc432c73cb0400732454e
This ads are very big.

Greetings,

**Comment by tagliala** [comment]
I do agree. Perhaps there is a missing `hidden-print` class but I need feedback from @davegandy

**Comment by tagliala** [comment]
Fixed, thanks!

**Comment by tagliala** [comment]
We still need to rebuild the docs
