### ISSUE TITLE
Please add webhook to packagist.org

### ISSUE THREAD

**Issue by martinlindhe** [FortAwesome/Font-Awesome#7088]
Hello

The https://packagist.org/packages/fortawesome/font-awesome  is not updated with the 4.4.0 release.
Could you perhaps add a webhook to packagist so it will be automatically updated in the future?

Thanks!

/m

**Comment by tagliala** [comment]
This package is not managed by us

Let's try to mention @theoreticaLee

**Comment by martinlindhe** [comment]
Ah, too bad :( Thanks!

**Comment by tagliala** [comment]
let's close this in favour of #1834
