### ISSUE TITLE
Icon Request: icon-diver

### ISSUE THREAD

**Issue by nbouquet** [FortAwesome/Font-Awesome#7091]
I would be nice to have a diver icon. A simple character with oxygen bottles.

Maybe other characters/jobs could be added. A worker, a lawyer, etc.

**Comment by tagliala** [comment]
If I well remember, this is a duplicate

Is there any synonym of diver that I can look for?

**Comment by tvirelli** [comment]
@tagliala scuba?

**Comment by tagliala** [comment]
@tvirelli thanks

Dup of #6448, please +1 that request

edited #6448 to include diver in the title

Closing here
