### ISSUE TITLE
Icon Request: fa-fit-to-screen

### ISSUE THREAD

**Issue by amuzalevskiy** [FortAwesome/Font-Awesome#7092]
Please include "Fit to screen" icon. We need it for zoom controls
Sample: http://prntscr.com/7yv8il

It will be also good to have icon "1/1" (means "zoom to 100%")

(close to https://github.com/FortAwesome/Font-Awesome/issues/1443)

**Comment by tagliala** [comment]
Is this the same of #4576  ?

**Comment by tvirelli** [comment]
@tagliala I think that they could be used interchangeably. I personally prefer the [#4576](https://github.com/FortAwesome/Font-Awesome/issues/4576) example.
