### ISSUE TITLE
Add reddit alien

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#7099]
Now that we're including the official reddit logo (alien with circle behind it) as the default reddit, we need to add the reddit alien.

**Comment by astropelusa** [comment]
+1  Please. In my site I have been using a solid alien face (a png) http://kobol.caltech.edu/palomar/stylesnscripts/lightbox/img/reddit.png
but probably the proper icon is outlined rather than solid. 
https://www.reddit.com/about/alien/

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.
