### ISSUE TITLE
Icon Request: Codecademy

### ISSUE THREAD

**Issue by KyroChi** [FortAwesome/Font-Awesome#7101]
![](https://pbs.twimg.com/profile_images/499697083398381568/ih2vOpDt.png)

**Comment by TheChen5** [comment]
Dupe of #3320
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks

**Comment by KyroChi** [comment]
It's been a year since #3320 was opened... also, this icon was not suggested previously by any issues in this repository. While a logo for this company had been requested (and not created for over a year) this particular logo has never been suggested and as codecademy gains popularity I think this is an essential icon to have. I will fork and attempt to add this myself tomorrow.
