### ISSUE TITLE
add PHP icon

### ISSUE THREAD

**Issue by jolx** [FortAwesome/Font-Awesome#7105]
Hello Font awesome team.

i wanna see the icon from PHP logo.

But why not add the Programming Languages logos like: JAVA, jQuery, .NET and others.

**Comment by TheChen5** [comment]
PHP dupe #1420 
Java dupe #386
There are other language icon requests
+1 those
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks!
