### ISSUE TITLE
Icon Request: Devpost

### ISSUE THREAD

**Issue by nealrs** [FortAwesome/Font-Awesome#7107]
Hola! [Devpost](http://www.devpost.com) (formerly ChallengePost) is a social network for developers & the biggest hackthon platform in the world. Would love to get our social icon into FA.

**[svg](https://gist.githubusercontent.com/nealrs/868af1e0ff6d60b7d638/raw/9500aac7536bd3a4652e63617aaf418d8cfa0a08/devpost-icon-black.svg)**  

**png**
![devpost-icon-black-rgb](https://cloud.githubusercontent.com/assets/1568188/9013761/015a9a50-378c-11e5-92b5-ca6cacf63e26.png)

**Comment by tagliala** [comment]
this should replace #5003 ?

**Comment by nealrs** [comment]
@tagliala yep!!

**Comment by tagliala** [comment]
let's use #5003, there are some +1s

I will edit the first post
