### ISSUE TITLE
[Request] Add new icon

### ISSUE THREAD

**Issue by sebbio** [FortAwesome/Font-Awesome#7108]
For brand:
ICQ, Viber, Telegram
Social network:
vkontakte, odnoklassniki
For service:
sms, mms, iMessage

**Comment by tagliala** [comment]
icq: #1272
viber: #3554 
telegram: #3034 
vkontakte: http://fontawesome.io/icon/vk/
ok: http://fontawesome.io/icon/odnoklassniki/ http://fontawesome.io/icon/odnoklassniki-square/
sms: #1440 

please +1 the above requests

imessage and mms: please open new individual requests and provide an example. take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

closing here
