### ISSUE TITLE
Icon Request: fa-arrow-bottom

### ISSUE THREAD

**Issue by kopeboy** [FortAwesome/Font-Awesome#7116]
I was surprised the search wouldn't return good results for "drop" or "upload".
An icon to mark an upload file button or area is needed!
Here is an example: https://thenounproject.com/search/?q=dropbox&i=169430
it may be accompanied by a text like "drop files here to upload" .. or click to browse.

Thanks in advance! :sweat_smile:

**Comment by Nektro** [comment]
There is an fa-download that is very similar to what you linked.
http://fortawesome.github.io/Font-Awesome/icon/download/

However, fa-dropbox could be added as something like this:
https://thenounproject.com/search/?q=dropbox&i=52383

**Comment by tagliala** [comment]
https://fontawesome.com/icons/download?style=solid

FA Pro also have
https://fontawesome.com/icons/arrow-to-bottom?style=solid
https://fontawesome.com/icons/arrow-alt-to-bottom?style=solid
