### ISSUE TITLE
fa-balance-scale

### ISSUE THREAD

**Issue by tsm91** [FortAwesome/Font-Awesome#7122]
[fa-balance-scale](http://fortawesome.github.io/Font-Awesome/icon/balance-scale/) is not working, i am using the newest 4.4 version

**Comment by tagliala** [comment]
I cannot confirm.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here, but feel free to comment

**Comment by tsm91** [comment]
It was cached in a .tmp folder by the gulp boilerplate i use, sorry for that.

**Comment by tagliala** [comment]
no problem, glad you solved :+1:

**Comment by swarnamenu** [comment]
Hello Mr.Tagliala,
I am using balance-scale icon but it's not shown..blannk place is shown on there.Please reply me.

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
