### ISSUE TITLE
Icon Request: fa-octocat

### ISSUE THREAD

**Issue by jayonit** [FortAwesome/Font-Awesome#7127]
Thanks for fontawesome.io. Awesome job!
We all used the former github logo like this:
![Octocat](http://a.36krcnd.com/photo/d063160d8374c53de163e8d287fc0d9d.jpeg)
But for some reason,sometimes I need to use only the github cat (Octocat) to make it which makes these be in sync.
So could you please make one without the black circle?
Just let the cat alone.
Thanks!!!

**Comment by tagliala** [comment]
This request is legit but I need a better title because there is a github logo with an "octocat" filter

**Comment by jayonit** [comment]
OK, what abou the title"fa-github-cat"?

**Comment by sensibleworld** [comment]
Cleaning up some older requests :) This icon has already been added: https://fontawesome.com/icons?d=gallery&q=github&s=brands
