### ISSUE TITLE
Icon request: icon-garage

### ISSUE THREAD

**Issue by CallumSmith** [FortAwesome/Font-Awesome#713]
Icons for rooms such as garage (car), shower, bedrooms (bed), and other real estate related icons would be great!

**Comment by rogersmj** [comment]
+1 !

**Comment by xJMV** [comment]
:+1:

**Comment by seraasch** [comment]
+1

**Comment by juliettesilven** [comment]
+1

**Comment by ahmadsafar** [comment]
+1

**Comment by MikePearson** [comment]
+1 garage

**Comment by BasicSoft** [comment]
+1
![garage-256](https://user-images.githubusercontent.com/25501553/38352922-12d71182-38b5-11e8-8c15-b58062c7ed01.png)

**Comment by Siege36** [comment]
+1 - Garage open, garage closed, garage alert. See matericaldesignicons.com

**Comment by sensibleworld** [comment]
We now have a garage icon: https://fontawesome.com/icons/car-garage?style=solid
And a warehouse icon that could work as well: https://fontawesome.com/icons/warehouse?style=solid
