### ISSUE TITLE
Icon Request: fa-star-circle

### ISSUE THREAD

**Issue by winemonkey** [FortAwesome/Font-Awesome#7130]
![screen shot 2015-07-31 at 1 54 18 pm](https://cloud.githubusercontent.com/assets/13473370/9047892/c9366a36-39e9-11e5-8b73-f6c69e79e5cf.png)
 For general use. Please.

**Comment by saitergun** [comment]
http://jsfiddle.net/saitergun/8rbw57ro/

**Comment by tuxy** [comment]
@saitergun Yeah making a circle or a square we can use pure css for that, no need to have a seperate icon that looks like that.

**Comment by tvirelli** [comment]
Yep agreed. This could be closed. There is multiple ways to do this. Either the way that @saitergun showed, our using Stacked Icons from fontawesome as documented here: http://fontawesome.io/examples/#stacked

**Comment by winemonkey** [comment]
Noted. Thank you.

Eric Blouin
WineMonkey Media Inc.
604 902 0617  |  eric@winemonkeymedia.com

Design. Brand. Engage.

**Comment by tuxy** [comment]
@williamboman What is up with the spam ?

**Comment by williamboman** [comment]
@tuxy Sorry, what?

**Comment by tuxy** [comment]
@williamboman Sorry ^_^ I mean't to say this to >> winemonkey

**Comment by williamboman** [comment]
@tuxy I was suspecting that :smile:, has happened a couple time before.

Regarding the spam, I assume you refer to the signature? Since @winemonkey commented on this issue via email, his mail application automatically appended his signature, which includes those contact details.

**Comment by tuxy** [comment]
Oh okay, this makes sense, but here it looks like spam.

**Comment by MelSumner** [comment]
Can I +1 this? I know it can be css'd but then again so could any of them in a circle. I'd like one in a circle for consistency with the others that have the -circle version. Thank you for considering!

**Comment by aethior** [comment]
Hi @winemonkey,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/circle-star

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon is part of the Pro set

**in a web application**, free user can create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/53/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by aethior** [comment]
@tagliala I think you can close here. :)
