### ISSUE TITLE
Icon Request: fa-fotolia

### ISSUE THREAD

**Issue by m-ristau** [FortAwesome/Font-Awesome#7134]
Requesting an icon for [fotolia](http://fotolia.com).
An example can be found [here](https://de.wikipedia.org/wiki/Fotolia#/media/File:Logo_Fotolia.svg).

**Comment by anija** [comment]
+1

**Comment by aethior** [comment]
>Adobe (Nasdaq:ADBE) today announced that it has entered into a definitive agreement to acquire privately-held Fotolia, a leading marketplace for royalty-free photos, images, graphics and HD video, for approximately $800 million in cash. Fotolia will be integrated into Adobe Creative Cloud, providing current and future Creative Cloud members with the ability to access and purchase over 34 million images and videos, significantly simplifying and accelerating the design process. ([source](https://www.businesswire.com/news/home/20141211006335/en/Adobe-Acquire-Fotolia-Adds-Stock-Content-Marketplace#.VIoJ4VXF_85))

cc/ @tagliala

**Comment by tagliala** [comment]
As an Adobe brand, we can't include this in FA

Ref: https://github.com/FortAwesome/Font-Awesome/blob/5.x/CHANGELOG.md#5140---2020-07-15
