### ISSUE TITLE
Icon request: Sports Balls (football - baseball - soccer - volleyball - basketball...)

### ISSUE THREAD

**Issue by marceloverdijk** [FortAwesome/Font-Awesome#714]
and maybe some other ball sports icons like american football ball etc.
- basketball ball
- football ball
- rugby ball
- baseball ball
- tennis ball
- volleyball ball
- water polo ball
- hockey puck
- handball ball
- <s>soccer ball</s> (fa-futbol-o added in 4.2)

**Comment by ravenblackhart** [comment]
+1 all the different balls would be great (volleyball/netball is my bigger concern...)

**Comment by bverhallen** [comment]
+1

**Comment by manuelfc1** [comment]
+1 for tennis

**Comment by rsingla92** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by albertlyu** [comment]
:+1:

**Comment by intrepidws** [comment]
+1

**Comment by jamesreimer** [comment]
:+1:

**Comment by eliaskosunen** [comment]
+1
Definitely this one

**Comment by Thijs5** [comment]
+1

**Comment by kwaaui** [comment]
+1

**Comment by epetruncio** [comment]
2.5 years ago and still nothing?

**Comment by Fatbat** [comment]
+1

**Comment by acegilz** [comment]
why nothing yet???

**Comment by DraftDuels** [comment]
2 years to make sport icons seems alittle extreme.

**Comment by dnavarrojr** [comment]
+1 * 1000

**Comment by nwalters512** [comment]
Can anyone from FA comment on why icons like these have not been added yet?

**Comment by bduff9** [comment]
+1, especially for NFL related icons (football, goal posts, etc.)  Would be amazing for my site

**Comment by GFargo** [comment]
:+1: , would love to see this! Working on a sports site right now and I don't want to move away from FontAwesome :crying_cat_face:

**Comment by kruser** [comment]
:+1: for baseball

**Comment by lienvdsteen** [comment]
:+1: for softball

**Comment by AlzerD** [comment]
:+1: for rugby

**Comment by acegilz** [comment]
in more than 2 years, how could this still be undone ? pls someone

**Comment by jlee4113** [comment]
What is the status on this? It would be extremely useful to have access to these icons. Are there any other icon libraries that anyone is aware of that has a comprehensive sports icon library?

**Comment by GFargo** [comment]
Feel like we are going to need to start releasing customized builds of Font-Awesome as the library is getting pretty big.  Don't want to start bloating our pages with a plethora of icons we don't actually use, however the need for diversity within an Icon library is **real**.

Wonder if Font-Awesome will offer anything like this through `Grunt` or `Gulp` or a similar build tool?

**Comment by tagliala** [comment]
@GFargo #1322 

At the moment there is not an official solution, please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by GFargo** [comment]
Awesome, thanks @tagliala! :beers: great Issue to keep on my radar!  :eyes:

**Comment by mattruma** [comment]
+1

**Comment by IngeFromHolland** [comment]
For a football, maybe something like this? 
[football.pdf](https://github.com/FortAwesome/Font-Awesome/files/67336/football.pdf)

Font Awesome rocks!! =D

**Comment by xtrinch** [comment]
+1

**Comment by maziak** [comment]
+1

**Comment by DHainzl** [comment]
+1!

**Comment by Kraignos** [comment]
I was about to ask for the same thing.

Definitely +1

**Comment by martolini** [comment]
+1

**Comment by agrison** [comment]
+1

**Comment by daudmabena** [comment]
`<i class="fa fa-futbol-o"></i>` from [http://fortawesome.github.io/Font-Awesome/icon/futbol-o/](url)

**Comment by Joysr** [comment]
for baseball and others :)

**Comment by TawabG** [comment]
+1

**Comment by budik21** [comment]
+1

**Comment by scotself** [comment]
+1  for our tennis client, who's using FA all over the site!

**Comment by YuningChou** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1 for rugby ball

**Comment by akyrey** [comment]
+1

**Comment by LRPalacios** [comment]
+1

**Comment by lawrence-velasquez** [comment]
+1 and also for the pool balls

**Comment by ealco9** [comment]
+1

**Comment by khowardui** [comment]
+1

**Comment by nunomazer** [comment]
+1

**Comment by kevbodavidson** [comment]
+1

**Comment by Binapick** [comment]
+1

**Comment by SquallX** [comment]
Agree

**Comment by francadaval** [comment]
+1

**Comment by greenbigfrog** [comment]
Over 3 years and still no reaction?

**Comment by ybonillo** [comment]
+1 ( especially rugby )

**Comment by ElTalPilon** [comment]
+1 (rugby would be great)

**Comment by greenbigfrog** [comment]
@davegandy how long will you let people wait?

**Comment by davidwkaiser** [comment]
+1

**Comment by WyldPhyr** [comment]
# Yes please!
+1

**Comment by maziak** [comment]
+1

**Comment by vsajja** [comment]
+1,000,000,000

**Comment by Buceador** [comment]
+1

**Comment by pierm8** [comment]
+1

**Comment by kevbodavidson** [comment]
give the people what they want

**Comment by baykorhan** [comment]
+1

**Comment by baumant** [comment]
+1

**Comment by ranjeethpt** [comment]
+1

**Comment by SierraLima** [comment]
Check this out [www.glyphsporticons.com ](https://glyphsporticons.com). We are looking for nice project (free font) in sport. Leave feedbacks and suggestions👍

**Comment by davegandy** [comment]
We've added our first set of sports icons to Font Awesome in 5.0.6. Here's the full set: https://fontawesome.com/icons?d=gallery&c=sports. 11 of those are a part of Free, and 70 as a part of Pro. Most of the original request here has even been added to Free. 😃 

Soon we'll be tackling a massive Olympic Sports category. So stay tuned for those. Closing here.

**Comment by greenbigfrog** [comment]
About exactly 5 years... That's what I call speed!

**Comment by davegandy** [comment]
@greenbigfrog Hah. True enough. Now that it's not just me making icons, we can move a lot faster. And keep in mind 10,000 other folks requested icons last year. We can't get to them all, but hopefully a lot more soon.

**Comment by intrepidws** [comment]
Thanks @davegandy much appreciated.

**Comment by dwhaas82** [comment]
+1 for Rugby
