### ISSUE TITLE
fa-*-chart without axes

### ISSUE THREAD

**Issue by grssnbchr** [FortAwesome/Font-Awesome#7140]
I really like the chart icons, e.g. http://fortawesome.github.io/Font-Awesome/icon/bar-chart/

But I think they should also be available without axes as they add (imho) unnecessary visual clutter.

**Comment by tagliala** [comment]
This should be a duplicate of #2794, please +1 that request

closing here

**Comment by grssnbchr** [comment]
You think so? Well ok. Thanks!
