### ISSUE TITLE
Icon request: icon-glasses

### ISSUE THREAD

**Issue by vimamica** [FortAwesome/Font-Awesome#7142]
I request the icon of glasses, for personal use, for the corporate opticien website of my sister and brother-in-law.

![glasses](https://cloud.githubusercontent.com/assets/13658140/9083409/59c13bf4-3b6a-11e5-940d-48c8517b6478.png)
![hipster-glasses-icon2-001](https://cloud.githubusercontent.com/assets/13658140/9083410/59dc88a0-3b6a-11e5-985f-74eac6d01f7e.jpg)
![hipster-glasses-icon](https://cloud.githubusercontent.com/assets/13658140/9083458/a4e9d5aa-3b6a-11e5-91ea-62a8a26ae587.png)

**Comment by tuxy** [comment]
+1, the first fa-glasses :-)

**Comment by tvirelli** [comment]
+1

**Comment by ristaumedia** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1043, please +1 that request and post there your example

closing here
