### ISSUE TITLE
Icon request: fa-pictures

### ISSUE THREAD

**Issue by stein189** [FortAwesome/Font-Awesome#7148]
Same as the current  ` fa fa-picture-o ` but 2 or 3 stacked on each other

![example](https://cloud.githubusercontent.com/assets/6512894/9089185/281adf18-3b94-11e5-95ff-cc349501a23f.png)

Useful for photo gallery

**Comment by simonfranz** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #855 , please +1 that request

closing here
