### ISSUE TITLE
Icon request: icon-t-shirt

### ISSUE THREAD

**Issue by marceloverdijk** [FortAwesome/Font-Awesome#715]
Indicating a sports teams

**Comment by squeral** [comment]
+1

**Comment by WispProxy** [comment]
+1 =)

**Comment by user11001** [comment]
+1

**Comment by jlouazel** [comment]
+1 Neeeeed !

**Comment by KoinPlusDev** [comment]
+1

**Comment by pezastic** [comment]
+1

**Comment by ty221** [comment]
+1

**Comment by manu29d** [comment]
+1

**Comment by arnklint** [comment]
+1

**Comment by boneyao** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by Elias87** [comment]
+1

**Comment by gwydionismyhero** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by faviouz** [comment]
+1

**Comment by kiessan** [comment]
+1

**Comment by jbaron30** [comment]
+1

**Comment by thehavknots** [comment]
+1

**Comment by thehavknots** [comment]
+1

**Comment by tortuetorche** [comment]
+1

**Comment by lichtamberg** [comment]
+1

**Comment by xxRockOnxx** [comment]
+ 1

**Comment by JoshWeb** [comment]
+1

**Comment by Discartyptics** [comment]
+1

**Comment by todddickerson** [comment]
+1

**Comment by hfcandeias** [comment]
+1

**Comment by andrewhowdencom** [comment]
+1

**Comment by bkuhl** [comment]
:+1:

**Comment by darkenedsky** [comment]
+1

**Comment by Haddicus** [comment]
+1

**Comment by LeungEnterprises** [comment]
+1, would be awesome!

**Comment by redayoub** [comment]
+1

**Comment by farizluqman** [comment]
+1

**Comment by tymorrow** [comment]
+1

**Comment by coderguy** [comment]
+1

**Comment by Cuuuurzel** [comment]
+1

**Comment by thanhson1085** [comment]
+1

**Comment by rlech** [comment]
+1

**Comment by Maxxamillion** [comment]
how is this not made already, all these +1
+1

**Comment by G-Driver** [comment]
+1

**Comment by andegre** [comment]
+100

**Comment by bartoleo** [comment]
+1

**Comment by shawncothran** [comment]
+1

**Comment by YGcorp** [comment]
+1

**Comment by gitChang** [comment]
+1. I really need this.

**Comment by EdnaldoNeimeg** [comment]
+1

**Comment by cczona** [comment]
+1

**Comment by Anaeria** [comment]
+1

**Comment by vsemecky** [comment]
+1

**Comment by uchuy77** [comment]
+1

**Comment by JFachetti** [comment]
+1

**Comment by ralexrdz** [comment]
+1

**Comment by TonyValenti** [comment]
+1

**Comment by uchuy77** [comment]
+1

**Comment by mdurkee** [comment]
+1 - Need this!

**Comment by bmedwards** [comment]
+1

**Comment by WilliWonka1** [comment]
+1

**Comment by Dr3am3rz** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by merlinpatt** [comment]
+1 it's been 3 years

**Comment by merlinpatt** [comment]
@davegandy @taglialia can we get some transparency on this and similar issues?

I fail to understand why this has yet to be done and why no statement has ever been made about why it isn't being done.

Multiple issues have been opened, commented on that it's a duplicate, and subsequently closed. But no other comments have ever been made about why this seems to be ignored

**Comment by shmaster** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by RSWilli** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-shirt was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by brunont** [comment]
+1

**Comment by karlambsilva** [comment]
+1

**Comment by dydx** [comment]
Sooo this has been on open for over three years. Any headway on getting an icon like this?

**Comment by wesleyholiveira** [comment]
+1

**Comment by obaratch** [comment]
+1

**Comment by WernerBuchert** [comment]
+1

**Comment by streamerthreads** [comment]
+1

**Comment by mardojai** [comment]
+1

**Comment by mdurkee** [comment]
How many +1 do we need in order to get 'er done?

**Comment by marieneig** [comment]
+1

**Comment by Marcel0024** [comment]
+1

**Comment by ryankane** [comment]
Here are my suggestions. Also, :+1: 

# fa-tshirt

## Stright

![fa-tshirt][1]

## Wavy

![fa-tshirt][2]

  [1]: https://cloud.githubusercontent.com/assets/1094151/16521530/6b1c9c0e-3f65-11e6-9a7f-ab682c00b63b.png
  [2]: https://cloud.githubusercontent.com/assets/1094151/16521728/d12ab6ce-3f66-11e6-913c-c2547a557385.png

**Comment by ibrokemycomputer** [comment]
+1

**Comment by MrDziobak** [comment]
+1

**Comment by alelnro1** [comment]
+1

**Comment by alsoknownasdrew** [comment]
+1

**Comment by vitalibr** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by nunomazer** [comment]
+1

**Comment by MortensenC** [comment]
+1

**Comment by benjamin234** [comment]
+1

**Comment by JorricksTU** [comment]
+1

**Comment by Crissov** [comment]
- 👕 [U+1F455](http://emojipedia.org/t-shirt/) Unicode emoji #222 
- 👚 [U+1F45A](http://emojipedia.org/womans-clothes/) (blouse)

**Comment by kungfupingu** [comment]
+1

**Comment by alex-felix** [comment]
+1

**Comment by ayausaspirit** [comment]
+1

**Comment by grosssmutttr** [comment]
+1

**Comment by majamaki** [comment]
+1

**Comment by HugCoder** [comment]
+1, how can this not be in yet?

**Comment by Youmoo** [comment]
Any progress on this ?

**Comment by lloyd678** [comment]
+1

**Comment by jcgsville** [comment]
+1

**Comment by arafathnihar** [comment]
+1

**Comment by JoaoAntonioMaruti** [comment]
+1

**Comment by jverdeyen** [comment]
+1

**Comment by LittleBigThingUK** [comment]
Why the hell is it so difficult to make such simple thing? How many years you need to add just a few icons??? I guess Dave Gandy don't give a damn about us users, who made him famous, by using his stupid project. I think it's time to leave Font Awesome behind and start using something else like glyphicons for example. At least they listen to their users. I'm sick of waiting few years for just a few damn icons.
Dont Awesome, you're dead for me.

**Comment by totalard** [comment]
++++1

**Comment by Avery246813579** [comment]
+1

**Comment by psonic** [comment]
+1

**Comment by neatnet** [comment]
+1

**Comment by biguero** [comment]
+1

**Comment by patmir** [comment]
+1

**Comment by kampiamodikuesto** [comment]
+1

**Comment by jborza** [comment]
+1

**Comment by johnwmcarneiro** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

Here are the [t-shirt icon](https://icons8.com/icon/1170/t-shirt) and the [player t-shirt icon](https://icons8.com/icon/31029/player-shirt).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by alexanderdejong** [comment]
+1

**Comment by nvuhung** [comment]
+1

**Comment by jholloway** [comment]
+1, FWIW, I like @ryankane's examples above

**Comment by tsantos84** [comment]
+1

**Comment by archergod** [comment]
+1

**Comment by cinqlair** [comment]
+1

**Comment by san-developer** [comment]
+1

Hi! Will you add this icons? Should we wait?  Thanks!

**Comment by franalt** [comment]
+1+1+1+1

**Comment by Sogl** [comment]
+100500

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by Portulinas** [comment]
+1

**Comment by nahue086** [comment]
+1

**Comment by danrichards** [comment]
+1

**Comment by universalathletic** [comment]
+1

**Comment by sensibleworld** [comment]
Hey look! It's a shirt! https://fontawesome.com/icons/tshirt?style=solid
