### ISSUE TITLE
Icon Request: fa-clip / fa-attachment

### ISSUE THREAD

**Issue by kwaaui** [FortAwesome/Font-Awesome#7150]
that would be nice

![iu](https://cloud.githubusercontent.com/assets/484470/9092009/d249edb2-3ba3-11e5-869e-21bf94d53e11.png)

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/paperclip/

**Comment by kwaaui** [comment]
Great, sorry. Thanks
 
∵ 
kwaaui.com
alessio@kwaaui.com
VoIP, IM: kwaaui
+39 338 2216104
