### ISSUE TITLE
Please, help me

### ISSUE THREAD

**Issue by shorenaa** [FortAwesome/Font-Awesome#7151]
Hello. I use your css for my site gartoba.mobi but most of my users using mobile opera, cannot see icons, they just see cubes. what is the reason? Thank you, dear friends.

**Comment by tagliala** [comment]
Hi, opera mini does not support font face, so you can't use fontawesome

http://caniuse.com/fontface

Hope it helps

Closing here but feel free to comment

**Comment by tagliala** [comment]
AFAIK, Opera mobile does support font face, the problem is opera mini
