### ISSUE TITLE
Icon Request: fa-membership

### ISSUE THREAD

**Issue by jkarr** [FortAwesome/Font-Awesome#7152]
I will use fa-users for now, but having a membership icon would be great.  Unfortunately, I have no ideas for how this would look.

My use for this would be more of like an organizational membership.

**Comment by jkarr** [comment]
Actually, fa-sitemap is a pretty good illustration.

**Comment by simonfranz** [comment]
-1

**Comment by tvirelli** [comment]
You might want to check out [#6968](https://github.com/FortAwesome/Font-Awesome/issues/6968) . I think you guys might be looking for the same idea of an icon. May you can work with user @eliv3n to narrow down exactly what you are looking for. We should try and keep similar ideas together. It makes collaboration easier and allows the +1 count to grow faster.

**Comment by tagliala** [comment]
closing here in favour of #6968
