### ISSUE TITLE
Icon Request: fa-gym

### ISSUE THREAD

**Issue by rehanahmed38** [FortAwesome/Font-Awesome#7154]
Well I am about to create website for gym and I am using Awesome fonts pack for the website icon but I can not find any gym related icons that I can use in website. Kindly include gym related icons so the look and feel of icon is more similar to the website theme.

Thanks

**Comment by TheChen5** [comment]
Dupe of #5826
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
thanks, but please do not +1 #5826 

I still think #1500 is a better representation

**Comment by JoaoMarcosSampaio** [comment]
+1
