### ISSUE TITLE
Icon Request: folder/file icons with plus/cross (add/delete)

### ISSUE THREAD

**Issue by LaurentFl** [FortAwesome/Font-Awesome#7155]
Hi,

I'd like to add a add folder icon in my application, like user-plus.
Can you add it in Font Awesome?

Thank you!
Laurent.

**Comment by tagliala** [comment]
duplicate of #1525 , please +1 that request

refers to #1181

**Comment by LaurentFl** [comment]
Hi,

Thank you for your advise.
I use FontAwesone in a Java application so I cannot use css with overlay but I test it with a StackPane and it's working fine!

Thx.
