### ISSUE TITLE
Icon request: icon-presentation-card / icon-business-card

### ISSUE THREAD

**Issue by topikito** [FortAwesome/Font-Awesome#7157]
I'd like to suggest the creation of a presentation card (or business card) icon

**Comment by tagliala** [comment]
http://fontawesome.io/icon/address-card/
http://fontawesome.io/icon/address-card-o/

If you have something different in mind, please provide an example and I will consider reopening

**Comment by topikito** [comment]
Thanks for responding @tagliala .

I was thinking more something like this:
![image](https://cloud.githubusercontent.com/assets/694244/21184227/634fbfa8-c203-11e6-9cb8-366ec91d5ad2.png)

(Excuse the quality, made it fast in 2 minutes - I'm no designer)

The idea behind this is to have an identifier to "Business details" as per "Upload your business card". Composition should be "Logo" + "Text" (or other way around)

Rather than using the v-card, I'd say http://fontawesome.io/icon/id-card/ suits better, but its still not what I'd use. My request may be to specific, but thought worth sharing.
