### ISSUE TITLE
Icon request: fa-wristwatch

### ISSUE THREAD

**Issue by jab** [FortAwesome/Font-Awesome#7158]
Any interest in adding something like http://emojipedia.org/watch/?

Thanks for considering and for the great work on Font Awesome!

**Comment by tagliala** [comment]
http://fontawesome.io/icon/clock-o/ isn't this suitable for your use case?

**Comment by jab** [comment]
Nope, I specifically opened this ticket because I need an icon that's
unmistakably a wristwatch, not a wall clock.

Actually, I also need icons for wallet and purse. Before I open issues for
those though I figured I'll ask here if there is interest.

**Comment by tagliala** [comment]
for a wallet, please +1 #2317 
for a purse, please open a new request

**Comment by jab** [comment]
Thanks for the pointer to #2317, just subscribed (rather than +1'd so as not to spam all the other subscribers).

New issue for purse in #7176.

**Comment by yanjunzhou-ca** [comment]
+1

**Comment by linuws** [comment]
+1 for wristwatch / smartwatch - great way to show that you have a watch app or similar.

**Comment by jongpau** [comment]
+1 for wristwatch / smartwatch

**Comment by mfishma** [comment]
Yes, need them for smartwatch or wearables

**Comment by etweb37** [comment]
need wearable, willing to draw :)

**Comment by leolux** [comment]
I need one as well :)

**Comment by sensibleworld** [comment]
We now have a few options for these. https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=watch&s=solid

<img width="857" alt="Screen Shot 2021-05-27 at 2 07 49 PM" src="https://user-images.githubusercontent.com/529604/119875592-ed738280-bef4-11eb-8ddf-220ade2c7874.png">
