### ISSUE TITLE
Icon request: dumptruck - equipment

### ISSUE THREAD

**Issue by awillness** [FortAwesome/Font-Awesome#7161]
I am looking for a dump truck icon. Is there one created?

**Comment by tagliala** [comment]
could this be considered a dup of #4084 ?

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by Harry-Lees** [comment]
I'd like to put in a (very) late +1 on this, I don't think any of the icons introduced in #4084 covered this and it would be quite useful to have this icon. Nothing I can see in the construction category seems to cover it.

Something like the following:

<p align="left">
<img src="https://github.com/user-attachments/assets/c8f38440-3d4d-4c6f-9eb9-caee4f4de8cc" width="200">
<img src="https://github.com/user-attachments/assets/32d51770-dd40-4b53-a515-44df29fe617b" width="150">
</p>

image sources:
* https://www.cat.com/en_GB/products/new/equipment/off-highway-trucks.html
* https://www.flaticon.com/free-icon/dump-truck_9236356

There has been some other interest for this icon, a dumptruck, or some variation has been requested in:
* https://github.com/FortAwesome/Font-Awesome/issues/4084#issuecomment-66516258
* https://github.com/FortAwesome/Font-Awesome/issues/13623#issue-344543108
* https://github.com/FortAwesome/Font-Awesome/issues/7815
