### ISSUE TITLE
 fa-copyright showing magnifying glass

### ISSUE THREAD

**Issue by Steztric** [FortAwesome/Font-Awesome#7165]
I was trying to use the copyright symbol for some WPF UI controls, but when I use the code for  fa-copyright &#xf1f9 it comes up as a magnifying glass.

![2015-08-07 10_56-satview - microsoft visual studio](https://cloud.githubusercontent.com/assets/13692795/9133394/314f117a-3cf3-11e5-8cb4-4896345a2d32.png)

**Comment by tagliala** [comment]
Don't know how to help

Here it works: http://jsfiddle.net/tagliala/4ya23yjL/1/

**Comment by Steztric** [comment]
OK. Maybe it is the version we have. I will try including the latest version and see if it still has the problem.

**Comment by tagliala** [comment]
let me know

**Comment by tagliala** [comment]
Closing here because of inactivity

If this is still an issue, feel free to fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
