### ISSUE TITLE
Icon Request: fa-area, fa-beach

### ISSUE THREAD

**Issue by alexshnur** [FortAwesome/Font-Awesome#7172]
Use on the websites of real estate

![icon-area](https://cloud.githubusercontent.com/assets/6603999/9147777/81371742-3d74-11e5-9379-bc5d70ffba81.png)
![icon-beach](https://cloud.githubusercontent.com/assets/6603999/9147779/89d5e072-3d74-11e5-93ed-27c143d053c2.png)

**Comment by TheChen5** [comment]
Beach dupe of #1145
+1 that
:mag:!

**Comment by tagliala** [comment]
closing here

**Comment by tagliala** [comment]
reopening as fa-area.
