### ISSUE TITLE
Icon request: hospitality

### ISSUE THREAD

**Issue by selvik90** [FortAwesome/Font-Awesome#7175]
Would like icons related to hotel, holiday home ect. 
Like the ones you see on air bnb for kitchen, bathroom, beds, map, dryer, refrigerator etc.

![hotelicon](https://cloud.githubusercontent.com/assets/13707241/9150608/45d79d5c-3de2-11e5-853c-f86a4080f9cd.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

If you need a comprehensive set of icons about hotel, you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment]
btw there are some duplicates you can +1, #726 , #6937 , #708 , #1559 and some others (please use the search feature)

**Comment by peterppm** [comment]
plus 1
