### ISSUE TITLE
Icon Request: fa-dice

### ISSUE THREAD

**Issue by hudson5** [FortAwesome/Font-Awesome#7177]
I'd like a die/dice icon. I'm gonna use it in a board game bar website in the section "Our games".
Something like the attached image.

Thank you so much

![die-icon](https://cloud.githubusercontent.com/assets/5827098/9151418/1f05be7a-3dd8-11e5-8182-574ea75026c1.png)

**Comment by TheChen5** [comment]
Dupe of #2622 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
thanks

closing here
