### ISSUE TITLE
Bower Include References SCSS and LESS file instead of built css files

### ISSUE THREAD

**Issue by jancel** [FortAwesome/Font-Awesome#7178]
In 4.2 & 4.3  injections included the proper *.css file(s). In 4.4, it includes the SCSS and LESS files.  Is this an intended behavior?  Sort of broke the inject system I'm using (which relies on bower.json -> main)

Edit: Added that 4.3 acts the same way as 4.2.

**Comment by tagliala** [comment]
> . Is this an intended behavior? Sort of broke the inject system I'm using (which relies on bower.json -> main)

Yes, because of the new bower specifications. Sorry for the breaking change. Please use `overrides`

Refers to #6227
