### ISSUE TITLE
Icon Request: fa-battery-charging

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#7179]
An icon for a battery that is charging
Something like this:
![image](https://cloud.githubusercontent.com/assets/13356474/9152752/ede146ae-3de9-11e5-8a57-fead48848ac0.png)

**Comment by DennaGherlyn** [comment]
+1

**Comment by slowkot** [comment]
+1

**Comment by leesah** [comment]
+1 but this icon doesn't align with the style of the existing battery icons.

**Comment by perler** [comment]
+1

**Comment by StephenBrown2** [comment]
:+1:

**Comment by onc** [comment]
+1

**Comment by burakkilic** [comment]
+1

**Comment by XorFish** [comment]
+1

**Comment by Sorebit** [comment]
+1

**Comment by ALFminecraft** [comment]
+1

**Comment by ruhatch** [comment]
+1, and preferably one for each charging level

**Comment by dylanaraps** [comment]
+1

**Comment by pyros2097** [comment]
+1

**Comment by mihib** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by MaJerle** [comment]
+1

**Comment by RoyalHAM** [comment]
I really like this idea... I also need a charging battery indicator. This image I took uses two CSS layers and places a fa-bolt icon over a fa-battery-0 icon.
![chargingbattery](https://cloud.githubusercontent.com/assets/12650256/17817933/01168c86-660f-11e6-96cf-d326048dab01.png)

**Comment by waterdrinker** [comment]
+1

**Comment by killinski** [comment]
This was fairly easy to achieve by combining the bolt icon along with battery icons as above using fa-stack and invert on the bottom image (in case anyone is in desperate need), and the bolt needs a little padding left to fit centrally (at the time of writing).

Anyway, here's what I ended up with:

![screenshot 2016-10-05 21 14 23](https://cloud.githubusercontent.com/assets/16122207/19140372/63562738-8b41-11e6-9270-c58dc92bfdb1.png)

fa-battery-charging feels like it would fit really well with what is already present.

**Comment by Custodia** [comment]
+1

Thinking of using font-awesome for my linux bar setup. Unfortunately the workarounds don't there since I need the unicode values directly.

**Comment by killinski** [comment]
@Custodia not sure what you're talking about because I'm dumb, but maybe this will help?

http://fontawesome.io/cheatsheet/

**Comment by Custodia** [comment]
@killinski Thanks, I know I can get the unciode values from there.

The problem is that I'm using these fonts in a bash script so I can't stack or invert icons.

**Comment by codextremist** [comment]
+1

**Comment by dannycolin** [comment]
> The problem is that I'm using these fonts in a bash script so I can't stack or invert icons.

I have the same problem with i3wm and polybar. it isn't possible to stack icons in the config file. 

Help me @davegandy you're my only hope. 😃

**Comment by sensibleworld** [comment]
Hey there! We added `fa-battery-bolt` in version 5. It's available in our Pro offering. https://fontawesome.com/icons/battery-bolt?style=solid
