### ISSUE TITLE
Icon Request: fa-Web

### ISSUE THREAD

**Issue by DingJunyao** [FortAwesome/Font-Awesome#7181]
I searched the icons but I coudn't find an icon to describe the Web. An icon similar to this meaning is fa-internet-explorer, but it may cause misunderstanding if I use it to describe the Web, e.g.: some people may think that it means "This website can only run in IE.".

**Comment by tagliala** [comment]
there is fa-globe http://fortawesome.github.io/Font-Awesome/icon/globe/, but you could +1 #2655

closing here
