### ISSUE TITLE
Icon Request: icon-old-person (elderly)

### ISSUE THREAD

**Issue by rgrptr** [FortAwesome/Font-Awesome#7183]
Hi

I think I can ask for new icons here. My request is about an icon for OLD PEOPLE.

Thank you very much. Good job!

**Comment by tagliala** [comment]
any example?

**Comment by rgrptr** [comment]
I found this example, it’s not the clean line I like but it’s the concept. The first one is for old people (I think their legs and the stick must be vertical, only the body inclined). Some other may be interesting (pregnant woman, injured leg, mother and child…)

Thanks!
> any example?
>

**Comment by tagliala** [comment]
email attachment do not work, please post your example on github: https://github.com/FortAwesome/Font-Awesome/issues/7183

**Comment by rgrptr** [comment]
![can-stock-photo_csp6488149](https://cloud.githubusercontent.com/assets/13719580/9171159/8f41fb1c-3f69-11e5-891a-380297489c6e.jpg)

**Comment by MVcodeartbr** [comment]
+1

**Comment by MVcodeartbr** [comment]
in #8008 i introduce some inspiration

**Comment by MVcodeartbr** [comment]
attending nielsen heuristics

![32836597-elder-black-graphic-symbol-vector-illustration-stock-vector-icon](https://cloud.githubusercontent.com/assets/3662026/11446895/23795f12-9525-11e5-866e-19320b863d69.jpg)
![elderly-512](https://cloud.githubusercontent.com/assets/3662026/11446897/237cae7e-9525-11e5-91c9-0fb62d369e9b.png)
![elderly-people-294088](https://cloud.githubusercontent.com/assets/3662026/11446896/237ca028-9525-11e5-8b20-1d2a65800a8f.png)


@tagliala this is accessibility, could you label as

**Comment by shaedrich** [comment]
Maybe something like this:
![image](https://user-images.githubusercontent.com/11225821/40580715-f79faf5a-60f0-11e8-88b5-da99813517cc.png)

![image](https://user-images.githubusercontent.com/11225821/40580712-edf1a8fa-60f0-11e8-8b67-a8248545d85f.png)

**Comment by 3liee** [comment]
The first one would be awesome! 
From my point of view the second one reminds a bit of a tea-cart.

**Comment by rgrptr** [comment]
hahahahahaha

awesome, great work!

**Comment by Pablo-Araya** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/person-cane?s=solid
