### ISSUE TITLE
Icon Request: icon-drama

### ISSUE THREAD

**Issue by bansaghi** [FortAwesome/Font-Awesome#7193]
Please, can you add the Greek comedy and tragedy masks (the theatre masks with happy and sad faces)

https://en.wikipedia.org/wiki/Drama

**Comment by TheChen5** [comment]
Dupe of #1270 
+1 that
:mag:before:heavy_plus_sign:

**Comment by bansaghi** [comment]
Blind me. Thanks

**Comment by tagliala** [comment]
thanks :)
