### ISSUE TITLE
Icon request: Ravelry

### ISSUE THREAD

**Issue by Webdeern** [FortAwesome/Font-Awesome#7197]
Ravelry is a social network.

http://www.ravelry.com

I want to use their icon in the header of a website where FB-, twitter-,Flickr-Icons etc. are listed 

Some wordpress themes offer to output social media icons and there Ravelry should be included as well. Apex from competethemes.com for example.

![Social Media in Apex Theme t](https://www.competethemes.com/wp-content/themes/compete-themes-neue/assets/images/apex/new_large_1.jpg)

**Comment by TheChen5** [comment]
Dupe of #3314
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks

closing here
