### ISSUE TITLE
Icon Request: fa-cricket-bat

### ISSUE THREAD

**Issue by Jeyanthinath** [FortAwesome/Font-Awesome#7199]
![bat](https://cloud.githubusercontent.com/assets/2253649/9196365/41be1ca6-4048-11e5-86ad-ad49145a54aa.jpg)

**Comment by TheChen5** [comment]
Dupe of #5706
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks

closing here
