### ISSUE TITLE
Icon Request: fa-credit-card-o (fa-credit-should be fa-credit-card-o)

### ISSUE THREAD

**Issue by brentdodell** [FortAwesome/Font-Awesome#7202]
The current `fa-credit-card` feels like it should be `fa-credit-card-o`. Would love to see an inverted (dark) `fa-credit-card`

**Comment by tvirelli** [comment]
+1

**Comment by tagliala** [comment]
Labeling as `bug`, assigning to @davegandy for milestone 5.0.0

Editing the title

**Comment by tagliala** [comment]
I don't know if the solution is to change name or implement a new icon. I mean, `fa-desktop` is also a `fa-desktop-o`

btw Dave should take a look at this.

**Comment by brentdodell** [comment]
> I don't know if the solution is to change name or implement a new icon.

Sorry, the name of the issue may have been incorrect. I wasn't so worried about the name as much as I was expressing that I would like to see a dark version.

Thanks!

**Comment by tagliala** [comment]
I think this has been fixed in FA 5.0

https://fontawesome.com/icons/credit-card?style=solid
https://fontawesome.com/icons/credit-card?style=regular
