### ISSUE TITLE
Icon Request: ember.js

### ISSUE THREAD

**Issue by saygun** [FortAwesome/Font-Awesome#7203]
![ember js_logo_and_mascot](https://cloud.githubusercontent.com/assets/4534914/9203958/e5a392a0-4062-11e5-9efa-f08532611e42.png)

**Comment by danilovaz** [comment]
+ 1

**Comment by danilovaz** [comment]
+1 :+1:

**Comment by tagliala** [comment]
Ember is available in FA5: https://fontawesome.com/icons/ember?style=brands
