### ISSUE TITLE
Font Awesome TTF/OTF missing characters

### ISSUE THREAD

**Issue by indiedotkim** [FortAwesome/Font-Awesome#7205]
Hi!

I am using Font Awesome primarily on my business web-site, but also started including it in presentations now. I downloaded the TTF/OTF fonts and installed them on OS X Yosemite (OS 10.10).

All is well, except that some characters are missing. For example, `fa-cogs`/`fa-gears` are not showing a character at all in Powerpoint. I am using images for missing characters as a workaround, but characters from the TTF/OTF look much sharper/crispier.

It would be cool if missing characters could be added to the TTF/OTF in future versions of Font Awesome.

Thanks,

Kim

**Comment by tagliala** [comment]
I'm pretty confident the glyphs are here

.ttf file is generated by the .otf file via fontsquirrel, as well as other webfonts.

Maybe this is a duplicate of #3908

**Comment by acshef** [comment]
![image](https://cloud.githubusercontent.com/assets/9013284/9231986/6bc008d4-40e8-11e5-9dcb-552395a7f724.png)
At least on Windows, the TTF has it

![image](https://cloud.githubusercontent.com/assets/9013284/9232029/9a997456-40e8-11e5-9f9e-2e385a78a046.png)
And the OTF has it as well. Have you checked with OSX's character viewer?

**Comment by indiedotkim** [comment]
Okay, the TTF/OTF are fine indeed! If I show all characters in Font Book and copy/paste from there, then it works. But, if I copy/paste from the [cheatsheet](http://fortawesome.github.io/Font-Awesome/cheatsheet/), then some characters are missing.

So, basically I should have not relied on a method described by someone somewhere on the internets, but instead, used the proper tools to start with!

Thanks everyone!

**Comment by tagliala** [comment]
> So, basically I should have not relied on a method described by someone somewhere on the internets, but instead, used the proper tools to start with!

So it is a copy & paste issue from the cheatsheet?

**Comment by indiedotkim** [comment]
@tagliala At least for me with with Chrome (version Version 44.0) and Firefox (version 40.0). Both on OS X Yosemite (version 10.10). I do not understand *why* that would be the case though.

**Comment by indiedotkim** [comment]
Ugh. Even worse: I can copy/past from Font Book into Photoshop and all is well. It does not work with Powerpoint (Mac 2011) though. Maybe the recently released newer version of Powerpoint fixes this.

**Comment by tagliala** [comment]
so the solution for Office is to copy glyphs from Font Book?

**Comment by indiedotkim** [comment]
@tagliala No, that's how it works for Photoshop. For office, I have found no other solution than using images yet.

**Comment by indiedotkim** [comment]
@tagliala Problem is fixed in Office 2016 for Mac. I **can** copy/paste from Font Book into Powerpoint 2016.

**Comment by tagliala** [comment]
@indiedotkim thanks for the head ups.

Do you think I can close #3908 explaining that the issue is solved in the new office version?

**Comment by indiedotkim** [comment]
@tagliala Just tested it: it works! Copy/pasting from Font Book into Word/Powerpoint in Office 2016 is all well! Might be nice to have others on different systems confirm it, but from my point-of-view this issue is resolved.

**Comment by tagliala** [comment]
does the cheatsheet work on office 2016?

**Comment by indiedotkim** [comment]
@tagliala Ah, gotcha!

Yes, but only if you copy/paste from the cheatsheet as "Unformatted Text" and then change the font to "FontAwesome". Works in Word and Powerpoint 2016 on Mac.
