### ISSUE TITLE
Icon Request: fa-hug

### ISSUE THREAD

**Issue by dabaliyan** [FortAwesome/Font-Awesome#7211]
It would be nice to have a HUG symbol, which can be used for Sympathizing or as a sign of "It's OK".
As apposed to many usual reactions 
e.g- ThumbsUp[Praise], Heart[Love], UpVote[Support], Favourite[Fondness] 
there is no symbol to encourage Sad Person 
e.g- Hug[Emotional Support]

Possible Usage:
- alternative to LIKE
- It's OK
- How lovely (but not that I love it)
- Close to heart (but not inside)
- I need it for my social network

or maybe something like that. 

![download](https://cloud.githubusercontent.com/assets/7037944/9226103/bd6ba75a-412a-11e5-99c1-c544ce38e52c.jpg)
![images](https://cloud.githubusercontent.com/assets/7037944/9226102/bd6b992c-412a-11e5-8d5d-8d3688195581.jpg)
![images](https://cloud.githubusercontent.com/assets/7037944/9226105/be2d6048-412a-11e5-96e1-0f571e876f00.png)

**Comment by tagliala** [comment]
almost impossible to fit in a 14px icon size

**Comment by tagliala** [comment]
may refer to #2159

**Comment by dabaliyan** [comment]
It's related but not similar. Friendship is an emotional relation and it's representation is a symbol, 
while a HUG is a reaction to emotions, which can be offered to someone (just like a HEART) 
firstly I thought that it belongs only with emoticons ,but it's not an emotion So I suggested.

Or let me put it this way, we use certain body-parts to react in daily life without speaking
e.g:  fa-smile(Face)  ,  fa-thumbs-up(Fingers) , fa-heart(Heart)
one thing missing is fa-hug(Hands&Chest)

I'll also update the usecase for the icon issue.

**Comment by dabaliyan** [comment]
And for the size concerns , I think the last image is pretty small
It gives us some some hope over impossibility. Maybe

**Comment by dabaliyan** [comment]
hey @tagliala what about fa-child-upper and fa-child-upper-o ??

**Comment by aethior** [comment]
*Related Unicode Emoji* #222
🤗 [U+1F917](https://emojipedia.org/es/emoji/%F0%9F%A4%97/) Smiling Face with Open Hands

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/face-smiling-hands?f=classic&s=solid)
