### ISSUE TITLE
Icon request: holiday / accommodation icons.

### ISSUE THREAD

**Issue by mactedder** [FortAwesome/Font-Awesome#7212]
I am developing a holiday booking website and I am surprised there is not a theme for Holiday / Accommodation icons. I would use the icons to help symbolise what features a property/location has:

Bathrooms, ensuite, shower, toilets, swimming pool, games-room, Tennis courts, local shops, beach/sea, DVD player,  Music player, 

Also icons for pets: dogs allowed etc

**Comment by tvirelli** [comment]
This is a very specific use case. Could I have done what you are doing for a real estate website. I used the checkbox icons with text next to them to describe the features. Here is aN example of what I did:
```html
<ul class="fa-ul">
    <li><i class="fa-li fa fa-check-square"></i>Bathrooms</li>
    <li><i class="fa-li fa fa-check-square"></i>Ensuite</li>
    <li><i class="fa-li fa fa-check-square"></i>Shower</li>
    <li><i class="fa-li fa fa-check-square"></i>Toilets</li>
    <li><i class="fa-li fa fa-check-square"></i>Swimming Pool</li>
    <li><i class="fa-li fa fa-check-square"></i>Games-room</li>
    <li><i class="fa-li fa fa-check-square"></i>Tennis Courts</li>
    <li><i class="fa-li fa fa-check-square"></i>Local Shops</li>
    <li><i class="fa-li fa fa-check-square"></i>Beach/Sea</li>
    <li><i class="fa-li fa fa-check-square"></i>DVD Player</li>
    <li><i class="fa-li fa fa-check-square"></i>Music Player,</li>
</ul>
```

**Comment by mactedder** [comment]
I see what you're saying, but in the instance I was going to used them I was going to just have the icons inline ununder the listings. Once on the product the details can then be given.

Also so that it helps with any language barriers as an image is universal.

I just feel a vacation / accommodation category would be a strong asset to an already great set of icons.

**Comment by tagliala** [comment]
Sorry, I need to close this one.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
