### ISSUE TITLE
Vintage Phone Icon

### ISSUE THREAD

**Issue by jrm1987** [FortAwesome/Font-Awesome#7221]
It would be great if we could have an icon like the traditional phones we used to have. Example:
http://kidsbizmasters.com/wp-content/uploads/2014/02/telephone.jpg

**Comment by user-e** [comment]
Image (if people want to see the image on this page):
![Image](http://kidsbizmasters.com/wp-content/uploads/2014/02/telephone.jpg)
(http://kidsbizmasters.com/wp-content/uploads/2014/02/telephone.jpg)

**Comment by tagliala** [comment]
duplicate of #1578, please +1 that request

closing here
