### ISSUE TITLE
Icon request: fa-united-nations-accessibility

### ISSUE THREAD

**Issue by caduvieira** [FortAwesome/Font-Awesome#7224]
Would be nice to have the new UN Accessibility icon:

http://www.un.org/webaccessibility/logo.shtml

**Comment by tagliala** [comment]
is this related to #2746 ?

**Comment by caduvieira** [comment]
Yes. But this is another way to represent accessibility.

On the site:
"The Accessibility logo was created for use on printed and electronic public information products to raise awareness about disability related issues, and can be used to symbolize products, places and anything that is ‘disability-friendly’ or Accessible."

**Comment by davegandy** [comment]
I like the spirit behind this request, but that icon is sadly... not aesthetically pleasing. Closing.
