### ISSUE TITLE
Icon Request: fa-flipchart, fa-teacher

### ISSUE THREAD

**Issue by jofran73** [FortAwesome/Font-Awesome#7226]
Thanks for this great project.
I would be happy if there would be icons for a category "education", i.e.
- an icon representing a seminar or course (my idea would be a flipchart)
- an icon representing a teacher / trainer / instructor / mentor (my idea would be a person pointing to a chalkboard)

Joerg

**Comment by caduvieira** [comment]
partially duplicate #4987 and #4079

**Comment by tagliala** [comment]
flipchart should be a duplicate of #866

**Comment by kristingreen** [comment]
+1 for this request.

It would be great if there were a section of icons devoted to education platforms. Systems like this typically track students, teachers, parents, lessons, classes/programs (i.e. Science, Music, Biology, etc...), report cards, administrative staff, etc...

**Comment by tagliala** [comment]
Closing here in favor of #4079
