### ISSUE TITLE
Icon Request: fa-line-chart without the axis

### ISSUE THREAD

**Issue by aronduby** [FortAwesome/Font-Awesome#7228]
I would love if there was [fa-line-chart](http://fortawesome.github.io/Font-Awesome/icon/line-chart/) but without the axis so it was just the line with the arrow, like a spark line. Up and down would be sweet, but if we had up a css-tweak could get us down pretty easily.

**Comment by caduvieira** [comment]
To something similar you could rotate http://fontawesome.io/icon/level-up/

http://jsfiddle.net/vdc3p97a/1/

**Comment by caduvieira** [comment]
Dupe #6160?

**Comment by aronduby** [comment]
shoot, not sure how I missed that one, my bad.

**Comment by rsiebeling** [comment]
+1
