### ISSUE TITLE
Houzz icon not working?

### ISSUE THREAD

**Issue by captivia** [FortAwesome/Font-Awesome#7231]
I am trying to add the Houzz logo in a circle and for some reason - I can't get it to work.

Here's what i'm using:
<li><a href="https://www.houzz.com"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-houzz fa-stack-1x fa-inverse"></i></span></a></li>

Can anyone help?

**Comment by captivia** [comment]
<li><a href="#"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x fa-inverse"></i></span></a></li>

**Comment by captivia** [comment]
![capture d ecran 2015-08-13 a 11 10 45 pm](https://cloud.githubusercontent.com/assets/13790558/9265919/9c818bae-4210-11e5-8b1a-e2ed187946ff.png)

**Comment by TheChen5** [comment]
Here:
&lt;i class="fa fa-houzz fa-stack-1x fa-inverse"></i>

*fa-inverse*!!!

**Comment by tagliala** [comment]
I need to close this one, but feel free to comment

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
