### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by buruguduy** [FortAwesome/Font-Awesome#7232]
Icon request: icon-bus
Icon request: icon-mrt
Icon request: icon-train

**Comment by Max-Krieg666** [comment]
bus: fontawesome.io/icon/bus
train: http://fontawesome.io/icon/train/

what is 'mrt'?

**Comment by caduvieira** [comment]
I think is Mass Rapid Transit. The same icon as train:  http://fontawesome.io/icon/train/ 
In that case train could be something like a locomotive: https://commons.wikimedia.org/wiki/File:BSicon_MBAHN.svg

**Comment by tagliala** [comment]
So we already have all the above icons?

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by buruguduy** [comment]
Thanks guys!
