### ISSUE TITLE
Add a list of the content:before markup to the documentation. 

### ISSUE THREAD

**Issue by ajlaporte** [FortAwesome/Font-Awesome#7236]
Would be possible to add a list of the markup for the content:before tags? I looked on the site and couldn't find it, but i did find this listing so it may help to add this in:

http://astronautweb.co/snippet/font-awesome/

**Comment by tagliala** [comment]
I probably didn't get this...

You are not forced to use `<i>`, you can (and should) use `<span>`

Markup: https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L14
Content: http://fortawesome.github.io/Font-Awesome/cheatsheet/

**Comment by ajlaporte** [comment]
Thank you for this @tagliala this listing is exactly what I was looking for. I would normally use a `<span>` but the template the client has makes use of the `<i>` tag and something got messed up during upgrade that caused the stylesheet to remove these. 

Thanks again!

**Comment by tagliala** [comment]
you're welcome, glad you solved
