### ISSUE TITLE
Icons request: stats & icq

### ISSUE THREAD

**Issue by Andrei2016** [FortAwesome/Font-Awesome#7243]
I think that should be a good idea if you can add a stats icon like this example: http://uxrepo.com/static/icon-sets/ionicons/svg/stats-bars.svg

I mean bar-chart without this "L border".

Another icon that is a must, in my opinion, is the social ICQ icon.

Thank you.

**Comment by tagliala** [comment]
icq: please +1 #1272
stats: please +1 #2794 

all dups, closing here
