### ISSUE TITLE
Icon request: align-top, align-middle, align-bottom

### ISSUE THREAD

**Issue by tarzak** [FortAwesome/Font-Awesome#7252]
Hello. Would be awesome if such icons were exist, which will provide illustrating of vertical aligning. ![Top](https://cdn0.iconfinder.com/data/icons/fatcow/32x32/align_above.png), ![middle](https://cdn0.iconfinder.com/data/icons/fatcow/32/align_middle.png), ![bottom](https://cdn0.iconfinder.com/data/icons/fatcow/32/align_bellow.png).

For example if you are doing something kind of text editor with simple tables, you could place these icons on text aligning buttons.
Thanks :)

**Comment by caduvieira** [comment]
dupe #2772

**Comment by tarzak** [comment]
Sorry, tried to search similar, but have not found.
