### ISSUE TITLE
Icon request: icon-unity, icon-nintendo, icon-playstation, icon-xbox, icon-Oculus, icon-unrealengine, icon-Vive

### ISSUE THREAD

**Issue by QFGlenn** [FortAwesome/Font-Awesome#7256]
Hi. I want to display icons to represent each of the platforms my company can develop for.

Unity, Unreal Engine, Nintendo, Playstation, Xbox, OculusVR, HTC Vive are the first few. Maybe it will help others, as well?

**Comment by TheChen5** [comment]
First of all, I think this violates Font Awesome rules to not request a set of icons at once.
I think there are quite a few dupes in this one.
Please :mag: and for those which are not dupes, create separate requests.

**Comment by TheChen5** [comment]
Oculus #4874

**Comment by tagliala** [comment]
Hi,

@TheChen5 is right, please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

main game consoles: #1006

**Comment by QFGlenn** [comment]
Please be nice. Font Awesome is a happy place.
