### ISSUE TITLE
Icon Request: fa-viadeo

### ISSUE THREAD

**Issue by Cailrorn** [FortAwesome/Font-Awesome#7258]
Viadeo is like linkedin

![Logo viadeo](https://cloud.githubusercontent.com/assets/6215266/9353446/a8145ce2-4668-11e5-8dff-1ce23dce1720.png)

**Comment by caduvieira** [comment]
dupe #886

**Comment by TheChen5** [comment]
+1 that one
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
thanks

closing here
