### ISSUE TITLE
Icon request: icon-smoking, icon-no-smoking (icon-cigarette)

### ISSUE THREAD

**Issue by t3chn0r** [FortAwesome/Font-Awesome#726]
A "no smoking" sign and a "smoking" counterpart... Something like [this](http://img.rfclipart.com/image/big/c5-7f-82/generic-no-smoking-sign-Download-Royalty-free-Vector-File-EPS-2680.jpg?v3)...

**Comment by apexskier** [comment]
+1

**Comment by idezine** [comment]
+1

**Comment by vektrom** [comment]
+1

**Comment by mchantraine** [comment]
+1,   "no-smoking" icon would be very helpful

**Comment by G-Driver** [comment]
+1

**Comment by andymai** [comment]
+1

**Comment by farukscan** [comment]
+1

**Comment by MakeNowJust** [comment]
+1

**Comment by chimalli** [comment]
+1

**Comment by timseverien** [comment]
+1 Seriously, why is this issue still open?

**Comment by jacksonfm** [comment]
+1

**Comment by iamrohan14** [comment]
+1

**Comment by iamrohan14** [comment]
+1

**Comment by XenRevo** [comment]
+1

**Comment by johnnyshields** [comment]
For those interested I've released smoking icons here in my own icon font which is compatible with FontAwesome: https://github.com/kkvesper/vesper-icons

.vs-smoking
.vs-smoking-alt
.vs-no-smoking-alt

(Documentation is still a work in progress.)

**Comment by martinlindhe** [comment]
+1

**Comment by jfoucry** [comment]
+1 really need this king of icons

**Comment by danielmcoelho** [comment]
+1

**Comment by Xusifob** [comment]
+1

**Comment by jonazu** [comment]
+1

**Comment by pinta83** [comment]
+1

**Comment by BunnyHolder** [comment]
+1

**Comment by G-Driver** [comment]
+1 for a fontawsome version 

Unicode icons for smoking and no smoking
🚬 (U+1F6AC) and 🚭 (U+1F6AD)

**Comment by honzyck** [comment]
+1

**Comment by jbarbede** [comment]
+1

**Comment by aethior** [comment]
+1

**Comment by kingonoverall** [comment]
Use the UTF Codes
smoking <i class="fa fa-2x">&#128684;</i>
non-smoking <i class="fa fa-2x">&#128685;</i>

**Comment by isaachinman** [comment]
+1

**Comment by roninbz** [comment]
+1

**Comment by AlexCezarMihai** [comment]
+1

**Comment by Reyeh** [comment]
+1

**Comment by Disane87** [comment]
+1

**Comment by andreipa** [comment]
+1

**Comment by mokipedia** [comment]
+1

**Comment by hrpc** [comment]
+1

**Comment by ivanshum** [comment]
+1

**Comment by kamranahmedse** [comment]
🚬  Wondering, how many +1s are required

**Comment by Fruchuxs** [comment]
Three years later: what is the reason why this icon is not added?

**Comment by Disane87** [comment]
this is so essential imho :/

**Comment by johnnyshields** [comment]
check out  https://github.com/kkvesper/vesper-icons

**Comment by gitouttatown** [comment]
+1

**Comment by reastwood** [comment]
+1

**Comment by wizzar** [comment]
+1
Why hasn't this been added yet?

**Comment by Disane87** [comment]
"opened this issue on 1 Feb 2013", wow, at least 4 years.

**Comment by pinta83** [comment]
And to be even worse - proposition vectors are already in this thread :(

**Comment by patmir** [comment]
+1

**Comment by simonmilz** [comment]
+1

**Comment by tumenor** [comment]
+1

**Comment by AlexCezarMihai** [comment]
+1

**Comment by MarenGr** [comment]
+1

**Comment by lastrebel** [comment]
how can I use this  icons on my web? if I use "fa-cigarette" it doesn't load anything, its kept blank. Any advice? I import font awesome library via command which i include in my stylesheet. Thanks for any typ.

**Comment by gezzeg** [comment]
+1

**Comment by SteveKennedy** [comment]
+1

**Comment by getjams21** [comment]
+1

**Comment by tjad** [comment]
@davegandy  bump - would like some update/feedback from font-awesome team on acceptance/implementation plan, we as part of the community have given ours , (repeatedly as seen by the closed issues).

I don't even smoke, I just know it's a social factor of today's world, hence it would be nice to include only 1 set of icons into my applications.

**Comment by vinyguedess** [comment]
+1

**Comment by alexitaylor** [comment]
+1

**Comment by sensibleworld** [comment]
A smoking icon is included in the 5.0.7 Font Awesome release: https://fontawesome.com/icons?d=gallery&q=smoking

No-smoking is coming soon!

**Comment by fizzgig314** [comment]
+1

**Comment by jmbarnardgh** [comment]
+1

**Comment by jmbarnardgh** [comment]
also, the "circle with the diagonal slash" by itself (without the smoke inside) would be nice to have - does that exist in FA?

e.g. `fa-circle-diagonal-slash`

**Comment by sensibleworld** [comment]
@jmbarnardgh Yup! https://fontawesome.com/icons/ban?style=solid

**Comment by OptikWebCreative** [comment]
Also maybe a similar one for vaping (e-cig)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=smoking

**Comment by mikermcneil** [comment]
Sort of related (putting this here for people that land on this issue when looking for the same thing I was in google search): https://gist.github.com/mikermcneil/ba5c54776d6ffb51aa7bc01953d08774
