### ISSUE TITLE
Icon Request: fa-scoopit

### ISSUE THREAD

**Issue by siandw** [FortAwesome/Font-Awesome#7269]
Hello, 

A client has requested to have the 'Scoop.it' social icon added to his website. Any chance there is a possibility of adding icon to your master list?

Here is a link to their website: http://www.scoop.it/
Otherwise I've attached a png. 

Thanks!

Sian
![scoop4](https://cloud.githubusercontent.com/assets/13889364/9387384/44a1a69e-472e-11e5-82f7-65173455893e.png)

**Comment by tagliala** [comment]
duplicate of #1603 , please +1 that request

closing here
