### ISSUE TITLE
Icon request: icon-salad

### ISSUE THREAD

**Issue by nightops** [FortAwesome/Font-Awesome#7272]
I like to request 3 food-based icons: salad, drink, and burger

Salad might be something akin to: 
![image](https://cloud.githubusercontent.com/assets/1412649/9392312/024ab9e0-474a-11e5-9d38-ec226e3a7ac3.png)

Drink would be something like: 
![image](https://cloud.githubusercontent.com/assets/1412649/9392325/178e7fc6-474a-11e5-815b-ffafa7f9b091.png)

And burger would be something like: 
![image](https://cloud.githubusercontent.com/assets/1412649/9392381/4e364f86-474a-11e5-9a16-03b09e5a73be.png)

Fantastic job so far guys, I love to look through all the new icons you add in.  I've told countless other devs about your set, and I haven't found a person that doesn't immediately fall in love with the simplicity and relatively small filesize.  Thanks sooooo much!!!

**Comment by TheChen5** [comment]
Drink dupe  #6122 & #370 
Burger #1961
+1 those
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
renaming as icon-salad, removing duplicates

**Comment by tagliala** [comment]
refers to #1895

**Comment by nightops** [comment]
Thanks for the heads up about the dupes.  I did a search, but evidently it wasn't comprehensive enough ;)

**Comment by Crissov** [comment]
🥗 [U+1F957](http://emojipedia.org/green-salad) Unicode emoji #222

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/salad?style=solid
