### ISSUE TITLE
academia.edu icon

### ISSUE THREAD

**Issue by olgavenetsianou** [FortAwesome/Font-Awesome#7273]
Hello, I'm making a site using "Make: A WordPress template by The Theme Foundry". The academia.edu icon is not available in the social network links, is it possible to make one? 

Thank you

**Comment by tagliala** [comment]
duplicate of #2751 , please +1 that request

closing here

**Comment by olgavenetsianou** [comment]
So, how do I actually place it in the menu?

**Comment by tagliala** [comment]
hi, #2751 is a request, it is not an actual icon.

If you need this icon in a short while, you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
