### ISSUE TITLE
Icon request: fa-circle-slash

### ISSUE THREAD

**Issue by gerrydirigo** [FortAwesome/Font-Awesome#7276]
Never mind.  I found it.  

![circle-slash](https://cloud.githubusercontent.com/assets/12087951/9409112/ec9e4188-47e5-11e5-9f4c-8299be83c500.jpg)

**Comment by TheChen5** [comment]
close this issue?

**Comment by TheChen5** [comment]
fa-ban

**Comment by tagliala** [comment]
:+1:

**Comment by mikermcneil** [comment]
As @TheChen5 mentioned, this is `fa-ban` - see also https://gist.github.com/mikermcneil/ba5c54776d6ffb51aa7bc01953d08774

(Leaving this note to help w/ google search -- e.g. https://www.google.com/search?q=font+awesome+circle+slash and https://www.google.com/search?q=font+awesome+no+smoking)

**Comment by ffxsam** [comment]
IMO, this icon isn't named well. Many of the other icons are named in a descriptive manner (e.g. "fa-chevron-down"). "fa-ban" doesn't mean anything, and I think "fa-circle-slash" would be a better name.

I realize just changing it would be a breaking change, but maybe a search alias would be warranted here, in the same way searching for "door" shows "fa-wreath" as a result.

**Comment by tagliala** [comment]
Hi @ffxsam, thanks for the suggestion

I would add search aliases and I agree that ban is not the best name we can find

I do not agree that this symbol could be called `circle-slash`, because `circle-slash` would look like something like this: https://jsfiddle.net/tagliala/L17f528g/441/

@talbs any thought?

**Comment by ffxsam** [comment]
Ahh, that's true. I think at least having a search alias would be perfect.

**Comment by laflier** [comment]
Well, not so fast on nixing "fa-circle-slash"... There's already "parking-circle-slash" which is basically "fa-ban" with a "P"...

But I can relate the the search problem. I had to do a Google search to find the FA icon I was looking for ("fa-ban"). And I'm apparently not the only one.

Perhaps "fa-no", which is then made more specific by adding another hyphen as in "fa-no-smoking" or "fa-no-parking". Another common use of the symbol, which was the one I was looking for, was a menu icon for blocking spam.

Maybe, as @ffxsam suggested, at least a search alias for one or more of these terms.
