### ISSUE TITLE
Icon Request: fa-apps-menu

### ISSUE THREAD

**Issue by airomero** [FortAwesome/Font-Awesome#7278]
An icon that represents apps tiles like you have in win8 or app menu like an android smartphone:

![image](https://cloud.githubusercontent.com/assets/1215578/9411732/16f18036-47fe-11e5-876d-a084aea94422.png)

Thanks!

**Comment by connois** [comment]
This already exists... This is : fa-th

**Comment by airomero** [comment]
I'm really sorry, i didn't see it at all. Thanks
