### ISSUE TITLE
Request: fa-equal

### ISSUE THREAD

**Issue by johnnyshields** [FortAwesome/Font-Awesome#7279]
We have plus, minus, times, no equals, and no division.

**Comment by TheChen5** [comment]
All dupes of #1133 
+1 that
:mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
closing here

**Comment by tagliala** [comment]
@TheChen5 could you please add a "please" before the :mag: ?

I mean
> All dupes of #1133 
> +1 that
> **Please** :mag:before:heavy_plus_sign:

thanks

**Comment by rubenscd** [comment]
+1

**Comment by TheChen5** [comment]
@rubenscd 
Please do not +1 duplicates.
Instead, +1 #1133 .
