### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by V1cHu** [FortAwesome/Font-Awesome#7281]
I recently came across Font Awesome and damn!! They are really awesome as they say :) The list of icons are really nice. But one thing that I couldn't find were the icons for various programming languages such as Java, Python, C, C# , even AngularJS, Node.js , MongoDB. They all have their own logos and it would be nice to have them as icons.

This is not an urgent issue. But would make a nice addition to the collection :)

**Comment by TheChen5** [comment]
Dupes:
Java #3863
Agular #2027 
Node #2584 
MongoDB #2725
Python #3016 
there might be more
:mag:before:heavy_plus_sign:

**Comment by V1cHu** [comment]
Oops. Sry. Why can't I find them in the website? I can only see HTML5 and CSS3?

**Comment by TheChen5** [comment]
On the left side, go to "Issues", not Code.

**Comment by tagliala** [comment]
Take also a look at http://fizzed.com/oss/font-mfizz and custom builds, which is the suggested approach in these cases: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
