### ISSUE TITLE
Icon Request: fa-casestudy, fa-whitepaper

### ISSUE THREAD

**Issue by basuaninda** [FortAwesome/Font-Awesome#7284]
Icon Request: fa-casestudy, fa-whitepaper,  fa-cms, ,  fa-erp

**Comment by TheChen5** [comment]
What type of CMS?
There seems to be quite a few.

**Comment by basuaninda** [comment]
Content Management System

**Comment by TheChen5** [comment]
CMS dupe #1485
+1 that
please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
could you please provide examples for casestudy or whitepaper?

**Comment by ron-watt** [comment]
Different than  fa fa-file-text-o  <i class="fa fa-file-text-o"></i>
Different than  fa fa-book  <i class="fa fa-book"></i>

**Comment by basuaninda** [comment]
Case Study is more of a Success Story Document.
And White Paper is meant to help readers understand an issue, solve a problem, or make a decision of an industry.

**Comment by basuaninda** [comment]
example below but can be better i guess...
The reason i asked for these two cause both of these are very commonly used terms in corporate world and "file icon" or "pdf icon" does not do justice for these two words...

https://s-media-cache-ak0.pinimg.com/236x/99/ee/3c/99ee3c4c0762daab8a9bd5f55e89d0da.jpg

http://cdn.slidesharecdn.com/ss_thumbnails/whitepaper-enterprisemashupsintheinsurancesector-121116101446-phpapp01-thumbnail-2.jpg

**Comment by basuaninda** [comment]
Regarding CMS more of in general rather than specific apps like drupal or wordpress but more as a subject. Maybe something like a browser icon with a pencil in it....

**Comment by tagliala** [comment]
sorry but I need a single color example suitable for 14px icon size

**Comment by venkatesh8** [comment]
Any update so far? I need these icons(whitepaper, Casestudy).

**Comment by tagliala** [comment]
@venkatesh8 please open new individual requests with single color examples suitable for 16px icon size
