### ISSUE TITLE
html side icons not working

### ISSUE THREAD

**Issue by arvinmetal** [FortAwesome/Font-Awesome#7289]
Hi,
I've been using Font Awesome for a while now, and I love it. But just recently I figured that my icons that are html based don't load. They show themselves as a square. Can you please help me. I've also written down the code right below:

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<li  class="icon1"><a href="#"><i class="fa fa-facebook fa-lg icon small-margin"></i><span>facebook</span></a></li>
<li  class="icon2"><a href="#"><i class="fa fa-twitter fa-lg icon small-margin"></i><span>twitter</span></a></li>
<li  class="icon3"><a href="#"><i class="fa fa-rss fa-lg icon small-margin"></i><span>Blog</span></a></li>

**Comment by tagliala** [comment]
Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here but feel free to comment
