### ISSUE TITLE
why not add some icon  about  	programming language? eg:java,node,redis,c..and so on.

### ISSUE THREAD

**Issue by felayman** [FortAwesome/Font-Awesome#7291]
why not add some icon  about  	programming language? eg:java,node,redis,c..and so on.

**Comment by TheChen5** [comment]
There are lots of requests about other programming languages.
Java #386 
+1 those
For ones that are not mentioned yet please create separate requests.
Programming language icons at http://fizzed.com/oss/font-mfizz .
Please :mag:before:heavy_plus_sign:

**Comment by TheChen5** [comment]
node #2584

**Comment by tagliala** [comment]
Closing here
