### ISSUE TITLE
Icon request: fa-basket

### ISSUE THREAD

**Issue by mlk83** [FortAwesome/Font-Awesome#7306]
For e-commerce - something different than shopping cart, basket would be awesome.

**Comment by TheChen5** [comment]
Dupe #962 
+1 that 
Please :mag:before:heavy_plus_sign:

**Comment by mellocapinpin** [comment]
+1

**Comment by TheChen5** [comment]
@mellocapinpin 
Please go +1 #962 , which this request is a dupe of.
There are way more +1s there. 99% chance this will be closed soon.
