### ISSUE TITLE
Icon Update: Rename Pinterest-p to Pinterest-o

### ISSUE THREAD

**Issue by 099io** [FortAwesome/Font-Awesome#7308]
It isn't a _big issue_ but I would like to see `pinterest-p` renamed to `pinterest-o` as it always seems to confuse me whenever I go to just get the "p" for Pinterest but it is `p` rather than `o`.

A similar _issue_ could be noted for `wikipedia-w`, it is the only wikipedia icon so why does it have `-w` after it?

**Comment by My1** [comment]
the o is probably for outline, while in case of wiki/pintrest it is just the more or less iconic first letter which is why the use the letter and not the "outline-o"

**Comment by tagliala** [comment]
Refers to #1966, please read that thread

closing here
