### ISSUE TITLE
Icon request: fa-iwatch

### ISSUE THREAD

**Issue by mukulkalra** [FortAwesome/Font-Awesome#7316]
i will be very greatful to you guys if you add icon for iWatch or hand watch
need ASAP
Thanks in advance

**Comment by asirgado** [comment]
+1

**Comment by linuws** [comment]
+1

**Comment by tagliala** [comment]
could you please provide an example? don't know if it is a brand

**Comment by ikellenberger** [comment]
I guess @mukulkalra is thinking of "**Apple Watch**" http://www.apple.com/watch/
(Apple first wanted to get the trademark for **iWatch** but got into trouble in some countries:
https://en.wikipedia.org/wiki/Apple_Watch#Release )
I would go for fa-smartwatch

**Comment by marcopalma123** [comment]
+1

**Comment by My1** [comment]
stupid question. how do you want to differentiate between a "normal" watch and a smartwatch, especially if only monochrome (opaque and transparent)

**Comment by tagliala** [comment]
I have classified this as "brand icons" but this is not a brand and there is not an official icon. We need to differentiate an iWatch between a generic smartwatch.

**Comment by My1** [comment]
well yeah that makes it even more extreme. how to differentiate between those (in a way that it is actually visible even on the chibi font used on fontawesome's pages)
my opinion is that we shouldnt do a specific Apple Watch/iWatch or whatever (or the next one asks for a moto 360 or whatever) but just a normal watch and if possible, a GENERIC smartwatch.

**Comment by mukulkalra** [comment]
By the way https://github.com/My1 I want SmartPhone Icon (which is not available right now) but to make easy for team font awesome i added apple iWatch

**Comment by My1** [comment]
@mukulkalra there is fa-mobile (which may look like an iphone but at least it isnt called that way and in small sizes it's as generic as it can be.

**Comment by mukulkalra** [comment]
@my1 do u know the difference between smartphone and smartwatch ???

**Comment by My1** [comment]
you were the one asking for a "smartphone" icon right now.

**Comment by douglasdeodato** [comment]
I think @tagliala  can be something similar to this: 

![apple-watch1-128](https://cloud.githubusercontent.com/assets/993318/16267556/4e9629ea-3882-11e6-94d6-1864027fc117.png)

**Comment by no1youknowz** [comment]
These are better I found:  

![iwatch](http://i.imgur.com/ZweoOhS.png)

**Comment by sensibleworld** [comment]
<img width="611" alt="Screen Shot 2021-03-30 at 12 40 52 PM" src="https://user-images.githubusercontent.com/529604/113024806-2beafc00-9155-11eb-9e58-f91d0aca23a7.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download
