### ISSUE TITLE
Icon Request: fa-icon-cup-cake

### ISSUE THREAD

**Issue by janiani** [FortAwesome/Font-Awesome#7317]
Hi - I don't know if it's possible but I was looking to use an icon called icon-cup-cake in the context of bullet points for a page I'm creating, I'm a health and weight loss coach. 

A friend recommended your site and I just love it.  I've attached a google image (I've 'borrowed') for the purpose :) and it would be shaped like this (if it's feasible)...

![cup-cake-font-awesome](https://cloud.githubusercontent.com/assets/13997512/9519297/4da2e60e-4cb5-11e5-8e71-55c46cdabc89.jpg)

It would be absolutely amazing if you can and many thanks for taking the request. Jane

**Comment by caduvieira** [comment]
Dupe for #2869
+1 that issue
