### ISSUE TITLE
Icon request: icon-aviary

### ISSUE THREAD

**Issue by DaGLiMiOuX** [FortAwesome/Font-Awesome#7318]
I did not found any icon related to aviary icon like the "A" from Aviary logo. It would be great since I need it for a button related to that image editor.

Regards.

**Comment by tagliala** [comment]
aviary = https://www.aviary.com/ ?

**Comment by DaGLiMiOuX** [comment]
Yes

**Comment by DaGLiMiOuX** [comment]
![aviary-logo](https://cloud.githubusercontent.com/assets/1701519/16837189/13988e7c-49c2-11e6-9fc2-c0f583fc309d.png)

**Comment by aethior** [comment]
>In December 2018, Adobe announced that they would remove Aviary from download stores and end support for the product. ([more info](https://en.wikipedia.org/wiki/Aviary_(image_editor)))

Regards.

cc/ @tagliala
