### ISSUE TITLE
Icon request: protection-shield

### ISSUE THREAD

**Issue by moerphie** [FortAwesome/Font-Awesome#7319]
Better icon for user-protection than [fa-shield](http://fontawesome.io/icon/shield/)

Example: 
![security-icon](https://cloud.githubusercontent.com/assets/12500071/9521397/f5777a84-4cce-11e5-9d3a-0871ee6c9d04.jpg)
![minicons2-63-512](https://cloud.githubusercontent.com/assets/12500071/9521396/f572392a-4cce-11e5-989f-538177fc34b8.png)

**Comment by huntingtown** [comment]
+1

**Comment by tagliala** [comment]
hmmmm I would consider this an enhancement of the current shield icon

**Comment by Seabizkit** [comment]
would be nice to just have a plain shield and the checked one with both 0 versions

**Comment by tagliala** [comment]
Closing here, we have both

- https://fontawesome.com/v6/icons/shield?s=solid
- https://fontawesome.com/v6/icons/shield-blank?s=solid

`shield-quartered` should also be available soon
