### ISSUE TITLE
Icon Request: fa-infine

### ISSUE THREAD

**Issue by wviana** [FortAwesome/Font-Awesome#7323]
math infinite symbol.

**Comment by TheChen5** [comment]
Dupe #1647 
+1 that
Plz :mag:before:heavy_plus_sign:

**Comment by kkprince1998** [comment]
:+1: 
but dupe

**Comment by TheChen5** [comment]
I see that you have +1'd #1647 .
Can you please close this issue?

**Comment by wviana** [comment]
@TheChen5 oh sure, I'll close it right now. Thank you for attention.

**Comment by TheChen5** [comment]
Thx.
