### ISSUE TITLE
#2726 is dupe of #386

### ISSUE THREAD

**Issue by TheChen5** [FortAwesome/Font-Awesome#7324]
Hello
just reminding @tagliala that request #2726 is a dupe of #386 
Maybe close that?

**Comment by wolfy1339** [comment]
There is no need to make an issue to say that an issue is a duplicate, just post it on the duplicate issue/pr

**Comment by TheChen5** [comment]
I already did that but it wasn't closed...
It's been there for a while.

**Comment by tagliala** [comment]
thanks, I didn't notice
