### ISSUE TITLE
Icon Request: fa-paint-brush-o

### ISSUE THREAD

**Issue by MariaWat** [FortAwesome/Font-Awesome#7327]
Hello, I'm using several of the "o" fa graphics and would love to have an open artist paint brush like the solid one you offer. I've created what I'd like it to look like, see attached. Thanks so much!
![paint-brush-o](https://cloud.githubusercontent.com/assets/14012421/9542102/e4c55f40-4d3b-11e5-8d61-62b62479693f.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=paintbrush
