### ISSUE TITLE
Icon request: theatre

### ISSUE THREAD

**Issue by somenxavier** [FortAwesome/Font-Awesome#7334]
Is it possible to put threatic (plays)

**Comment by caduvieira** [comment]
dupe of #1987 ?

**Comment by tagliala** [comment]
any example?

**Comment by somenxavier** [comment]
Yes, It could be like this: https://pixabay.com/es/etapa-teatro-mostrar-158366/

**Comment by tagliala** [comment]
Ok, duplicate of #1987. Closing here. Add theatre in #1987 title
