### ISSUE TITLE
icon request: fa-rank-pte fa-rank-cpl fa-rank-sgt fa-rank-lt fa-rank-cpt

### ISSUE THREAD

**Issue by tylerecouture** [FortAwesome/Font-Awesome#7335]
A set of icons indicate levels or ranks.  The most universal I could think of were military rank symbols, something like:

fa-rank-pte: a single chevron (use existing chevron or fa-angle-)
fa-rank-cpl: two chevrons (could use fa-angle-double-)
fa-rank-sgt: three chevrons/angles
fa-rank-lt: a thick vertical bar
fa-rank-cpt: two thick vertical bars
fa-rank-maj: three vertical bars or star
etc.

although, any sort of progression based rank/level icon set would be awesome.

Similar to this but much more simple/universal
https://github.com/weklund/Military-Rank-Web-Font-Icons

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Please open new individual requests or consider a custom build, merging fontawesome with a specific military rank set of icons: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
