### ISSUE TITLE
Icon Request: fa-toast, fa-toast-o

### ISSUE THREAD

**Issue by wswilliams67** [FortAwesome/Font-Awesome#7339]
Both Outline and Glyph. Just a slice of bread icon from front angle. Thanks!

**Comment by caduvieira** [comment]
dupe of #6016

**Comment by wswilliams67** [comment]
Mmmm nope, need a solid glyph and just an outline.. no dots please.

**Comment by tagliala** [comment]
Hi, I'm sorting out some old requests 😅 

> Mmmm nope, need a solid glyph and just an outline.. no dots please.

Here it is, no dots at all!
https://fontawesome.com/icons/bread-slice?style=solid

Regular (outline) version is available in FA Pro
https://fontawesome.com/icons/bread-slice?style=regular

Since the design is the same, closing here as a duplicate of #6016
