### ISSUE TITLE
Icon Request: fa-quora

### ISSUE THREAD

**Issue by anexasnivihs** [FortAwesome/Font-Awesome#7344]
I was hoping to see an icon for Quora. I would imagine that users would want to use this icon to link to their Quora profiles on their personal websites, much like other social media platforms such as Facebook, Twitter etc. At least that's how I wish to use it on my personal portfolio page as I'm a heavy Quora user. Thanks!

**Comment by TheChen5** [comment]
Dupe #510 
+1 that
Please :mag:before:heavy_plus_sign:
