### ISSUE TITLE
Icon request: fa-starbucks

### ISSUE THREAD

**Issue by OrigodStudios** [FortAwesome/Font-Awesome#7345]
I would love to see a starbucks logo in fa :D
![starbucks](https://cloud.githubusercontent.com/assets/14044825/9569357/990ee7d6-4f68-11e5-843c-1c5dbb8b3c3c.png)

**Comment by TheChen5** [comment]
Dupe #4683
+1 that
Please :mag:before:heavy_plus_sign:
