### ISSUE TITLE
Icon Request: Please add Google Blogger

### ISSUE THREAD

**Issue by vinayprajapati** [FortAwesome/Font-Awesome#7349]
I find WordPress icon and others too but missing Google Blogger icon please add this asap.

**Comment by Mohika** [comment]
I got surprised its not in there as well. I need it too :-) Realized this 30 minutes ago .. coincidence if you believe it :-)

**Comment by TheChen5** [comment]
Dupe #1088 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by jclarkcds** [comment]
PLEASE ADD!!

**Comment by TheChen5** [comment]
@jclarkcds 
This is a duplicate of request #1088 .
There are way more support there.
Please go +1 that issue.

**Comment by tagliala** [comment]
closing here as a duplicate
