### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by bhavyanarula** [FortAwesome/Font-Awesome#7350]
Hi,

I have embedded Font-Awesome Icons in my JSP page (Using Struts 2 tags). I am trying to call my struts 2 action with the link on the icon:
Link-1:     <a href="<s:url action='editProfile' />" ><i class="fa fa-edit fa-2x"></i></a>
The above link is not performing anything.

whereas the below link performs absolutely correct:
Link-2:     <a href="<s:url action='editProfile' />" >try </a>

Also the link-1 works correctly if I open the link in the new tab by right clicking over it. 

Can you please try and check if some kind of problem arise because of Font-Awesome Icon in such a case? O if you see some other mistake in my code then let me know.

Thanks for your efforts towards the Cyber Society.

**Comment by bhavyanarula** [comment]
Hey, I don't know how any one of you is using these icons if the anchor tag around them is not working. Nevertheless, I was trying to debug this whole day and found the below segment in the jquery.toolbar.css:

 populateContent: function() {
            var self = this;
            var location = self.toolbar.find('.tool-items');
            var content = $(self.options.content).clone( true ).find('a').addClass('tool-item');
            location.html(content);
            location.find('.tool-item').on('click', function(event) {
            	event.preventDefault();
                self.$elem.trigger('toolbarItemClick', this);
            });
        },

Please explain me why this event.preventDefault(); is called everywhere in this jquery, its preventing the default behavior of anchor tag to navigate to the given link.

I simply commented out this line of code and now my icon link is performing as expected. 

I hope I have not altered any other functionality of the toolbar (doesn't seem like)

Thank you for your support.

**Comment by tagliala** [comment]
There is no javascript involved in Font Awesome, or maybe I didn't get your request

Could you please clarify?

**Comment by tagliala** [comment]
No feedback, closing here
