### ISSUE TITLE
Icon Request: fa-Hubspot

### ISSUE THREAD

**Issue by ModedawebDesign** [FortAwesome/Font-Awesome#7355]
I would like an icon of the Hubspot logo to put into our website, as we are a Hubspot agency partner. It's this logo: 

![](http://www.modedaweb.co.uk/wp-content/uploads/2015/07/hubspot-marketing-and-COS-development-services-at-Modedaweb-small.png)

**Comment by PWard1987** [comment]
:+1:

**Comment by sgwcollins** [comment]
any news on this?

**Comment by tagliala** [comment]
Hi,

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by lummerland** [comment]
Hi,
I got the information that the hubspot logo got a redesign last year. What would be the best way to update the logo in FA? Create a new request and add the svg-files?
Thanks & kind regards

**Comment by tagliala** [comment]
Hi @lummerland , please open a new request
