### ISSUE TITLE
Icon Request: fa-barcode-scanner

### ISSUE THREAD

**Issue by sainzrow** [FortAwesome/Font-Awesome#7356]
I'll use it to reppresent an action that is going to start a barcode scanner activity
![barcodescanner](https://cloud.githubusercontent.com/assets/7038182/9602713/01ba3b6c-50ab-11e5-8399-d9ff2c713dfa.png)
Thanks for the support

**Comment by hellsing71** [comment]
+1, but w/o colors this blue line would be black (and would mean 'no barcode' or the like) so instead I would use stg. like this (with a heavier barcode):

![barcode_scanner-512](https://cloud.githubusercontent.com/assets/8152173/9638705/6953599a-51a8-11e5-919c-57e59da39b57.png)

**Comment by sensibleworld** [comment]
There are a few options for this in the logistics category: https://fontawesome.com/icons?d=gallery&c=logistics
