### ISSUE TITLE
Update: fa-google-wallet

### ISSUE THREAD

**Issue by conwayanderson** [FortAwesome/Font-Awesome#7357]
*edit by tagliala*

lock reason: Dave will certainly update Google icons in the next release, no need to +1

--

Google has updated their logo. This should affect all of the icons which use the Google "g". 

![image](https://cloud.githubusercontent.com/assets/1882439/9611010/0848d1b4-5092-11e5-9b54-1e3d365071c3.png)

**Comment by ekerazha** [comment]
+1

**Comment by carasmo** [comment]
+1

**Comment by jackennils** [comment]
+1 

We definitely need an update on these.

**Comment by dannote** [comment]
+1

**Comment by cyberbit** [comment]
+1

**Comment by wolfy1339** [comment]
:+1:

**Comment by AdamForst** [comment]
+1

**Comment by klombomb** [comment]
+1

**Comment by meije702** [comment]
+1

**Comment by pixxies** [comment]
+1

**Comment by Duke3D** [comment]
+1 - already have a client asking about how soon they can display it  ...

**Comment by vinayprajapati** [comment]
+1

**Comment by iferrer** [comment]
+1

**Comment by typoagrafka** [comment]
+1

**Comment by AnMartini** [comment]
+1

**Comment by jflavan** [comment]
+1

**Comment by astropelusa** [comment]
+1

**Comment by starkshaw** [comment]
+1

**Comment by aery** [comment]
+1

**Comment by CoalaJoe** [comment]
+1

**Comment by DanielNetoP** [comment]
+1

**Comment by bbuchalter** [comment]
:+1:

**Comment by AvionixCh** [comment]
+1

**Comment by CantonBolo** [comment]
+1

**Comment by FSElias** [comment]
+1

**Comment by msbtterswrth** [comment]
+1

**Comment by sunsys0** [comment]
+1

**Comment by MardonHH** [comment]
+1

**Comment by glombek** [comment]
+1

**Comment by jezmck** [comment]
+1

**Comment by vic3685** [comment]
+1

**Comment by SpyMaster356** [comment]
+1

**Comment by dragnsteph** [comment]
+1

**Comment by cougrimes** [comment]
+1

**Comment by codyn329** [comment]
+1

**Comment by tagliala** [comment]
Imho there is no need to +1 this request

Labeled as bug, assigned to @davegandy

**Comment by bertoul** [comment]
+1

**Comment by kshkonan** [comment]
+1

**Comment by marcobrizi** [comment]
+1

**Comment by tijuak** [comment]
+1
Really need this ! I can help if needed

**Comment by redbmk** [comment]
They also updated the Google Wallet icon to have less rounded edges.

![googleplus-logo](https://cloud.githubusercontent.com/assets/83964/10008294/e525e032-6081-11e5-9730-b56ac50ff59d.png)

**Comment by tagliala** [comment]
@redbmk thanks, title updated

@ others: please **do not** +1, but if you have thoughts feel free to share

**Comment by ekerazha** [comment]
@tagliala is there an ETA?

**Comment by EcoGit** [comment]
+1

**Comment by Aemstel** [comment]
@davegandy has not contributed for nearly a month. We look pretty silly showing the old Google logo still. Maybe assign to someone else? Any update on this at least?

**Comment by jackennils** [comment]
Good idea. Please don't let us wait so long.

**Comment by fniephaus** [comment]
+1

**Comment by d9n** [comment]
+1

**Comment by tagliala** [comment]
Please do not +1, Dave will certainly update Google icons.

If you are in hurry, please customize or fork the repo and share your work here

**Comment by davidstosik** [comment]
I wish there was a way to block all those "+1"... People, 's a "subscribe" button on the right, that will alert you of new content on this thread as well as if you commented, so please avoid waking every participant up with a useless comment.
[I made my own SVG version of Google's new G icon, which you can find on my Dropbox](https://www.dropbox.com/s/drcserlihsk6p32/Google_Logo.svg?dl=0) ([original file is Public Domain on Wikimedia](https://commons.wikimedia.org/wiki/Category:Google_g_logo#/media/File:Google_%22G%22_Logo.svg)). I imported it in a Fontastic font (the site I'm working on already uses one, so it's not a big deal), as a temporary fix waiting for FontAwesome to be fixed.

**Comment by BastiaanDeHart** [comment]
+1

**Comment by jezmck** [comment]
+1s are used to indicate importance / desirability by the community. 

This ticket has been open for a surprisingly long time.

**Comment by EcoGit** [comment]
+1

░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░

**Comment by cougrimes** [comment]
Just a note that there ARE official SVGs for the Google G/Google+ logos:

https://developers.google.com/site-assets/logo-google-g.svg
https://developers.google.com/site-assets/logo-google-plus-white.svg

Unfortunately no official Wallet SVG at this time.

**Comment by d9n** [comment]
@davidstosik FYI, +1'ing existing issues is font awesome's official instruction - http://fontawesome.io/community/#requesting-new-icons

This particular issue's title has a request not to +1 it but I missed noticing it myself.

**Comment by davidstosik** [comment]
@d9n Oh! The more you learn... ;)
Thanks for the pointer.

**Comment by CoWinkKeyDinkInc** [comment]
+1

**Comment by cloderic** [comment]
:+1:

**Comment by tagliala** [comment]
temporarily locking here: https://github.com/FortAwesome/Font-Awesome/issues/7357#issuecomment-143690740

**Comment by tagliala** [comment]
Unlocking here

@davegandy

**Comment by davegandy** [comment]
Anyone know where I can get a vector version of the Google Wallet logo? Preferably single color?

**Comment by davegandy** [comment]
Updated Google, Google+, and Google+ square in 4.4.1-wip branch.

Going to hold off on updating Google Wallet logo. Looks like it'll be called Android Pay (unless I'm missing something).

Keeping this issue open, updating title, and assigning to 5.0.0.

**Comment by wallenstone** [comment]
@davegandy Google Wallet will continue to exist. Android Pay is a separate service that was born out of Wallet.  Google has updated the Wallet logo according to their new design standards.

Hope that helps.

**Comment by davegandy** [comment]
Anyone have an SVG of the new Google Wallet logo? For the life of me, I cannot find a vector. And I really don't want to have to make one.

**Comment by tagliala** [comment]
I'm not able to find it

**Comment by davegandy** [comment]
If we can't get a vector in time for this release, I'm punting it to 5.0.

**Comment by davegandy** [comment]
Updated in 4.6.0-wip branch. Closing.

**Comment by dylmye** [comment]
I've contacted Google Brand Guidance for a copy. They ask for up to 2 weeks to reply. If I get a positive response I'll link you.
(I have correctly stated that it is for FontAwesome, not personal/other commerical use)

**Comment by tagliala** [comment]
@dylmye thanks

**Comment by dylmye** [comment]
@tagliala @davegandy Bad news. 
"Unfortunately, we cannot approve your request. Please understand we typically do not allow third party use of our logo or brand features [hmmm... sure!] If you are working with someone at Google, please connect with them directly to facilitate your request".
Anyone willing to use their contacts?
