### ISSUE TITLE
Icon request: icon-trailer

### ISSUE THREAD

**Issue by DigiLive** [FortAwesome/Font-Awesome#7369]
I'm planning to use it for categories about transportation.
IMHO it's a nice addition to the already existing "transportation" icons.

My English isn't perfect so here are two examples of trailers I would like very much to be added, (although the second one is called a caravan maybe?):
![icon_transport_trailor](https://cloud.githubusercontent.com/assets/7613487/9643123/4e6da870-51c0-11e5-8b52-064927a4e2af.png)
![trailer-64](https://cloud.githubusercontent.com/assets/7613487/9643124/4e6e5676-51c0-11e5-8998-b84acdd029a0.png)

**Comment by Zaanmedia** [comment]
+1

**Comment by paeddy** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by rodgauge** [comment]
+1
for the trailer to represent tracking a non motorized mobile asset

**Comment by myxor** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by jcdosmann** [comment]
+1

**Comment by stefankellens** [comment]
+1

**Comment by stefankellens** [comment]
Hello

A caravan and a trailer are not the same
Caravan = https://cloud.githubusercontent.com/assets/7613487/9643124/4e6e5676-51c0-11e5-8998-b84acdd029a0.png
Trailer = https://cloud.githubusercontent.com/assets/7613487/9643123/4e6da870-51c0-11e5-8b52-064927a4e2af.png

Greetings

**Comment by rginnow** [comment]
+1 Would also like to use this in my web app for a transport company.

**Comment by a-ivanov81** [comment]
+1

**Comment by markus-hsk** [comment]
+1

**Comment by smithandre** [comment]
+1

**Comment by jvdhelder** [comment]
+1 I really want the trailer icon for displaying that we are using car, truck and trailer in the company.

**Comment by Pumizo** [comment]
+1 pleas add-it :)

**Comment by fcools** [comment]
I don't think it will ever happen. I requested it over a year ago. Seeing the 4000 issues and 50 pull requests, I think this project is pretty much death.

**Comment by jvdhelder** [comment]
Maybe if we keep the conversation active and share this issue with other people... :)

**Comment by IlyaDiallo** [comment]
+1 for trailer

**Comment by annacrombie** [comment]
+2

**Comment by rebruCH** [comment]
+1 for Trailer

**Comment by kippyieh** [comment]
+1

**Comment by lalabili** [comment]
+1

**Comment by spring1975** [comment]
+1

**Comment by krislinus** [comment]
+1

**Comment by rlefevere** [comment]
Looking for a caravan icon. Hope this one makes it!

**Comment by kalinchuk** [comment]
3 years and still no trailer icon? +1

**Comment by snow2k9** [comment]
Would love to see a trailer

**Comment by jvdhelder** [comment]
@robmadole  could you please add the trailer icon? We are waiting for so long. ;)

**Comment by aagrossman** [comment]
Working with a trailer distributor and would love the trailer (more than caravan)

**Comment by Waro1234** [comment]
I would absolutely love to see a trailer ico implemented!

**Comment by chrysler5798** [comment]
+1 it would be userful for transport field.

**Comment by igorlino** [comment]
+1

**Comment by wtczk** [comment]
+1

**Comment by Xulita78** [comment]
+1

**Comment by Xulita78** [comment]
+1

**Comment by sciupinski** [comment]
+1

**Comment by danielpox** [comment]
👍🏻

**Comment by aoverholtzer** [comment]
+1

**Comment by zeroreality** [comment]
+1

**Comment by AlexLein** [comment]
+1

**Comment by sithembisos** [comment]
+1

**Comment by Zwelibanzi** [comment]
:+1:

**Comment by 9tails1** [comment]
+1

**Comment by skyflo** [comment]
+1

**Comment by floranberthaud** [comment]
+1

**Comment by TLWebdesign** [comment]
+1

**Comment by MagicMarvMan** [comment]
+1

**Comment by stefanpejcic** [comment]
+1

**Comment by jguboico** [comment]
+1

**Comment by weijyewang** [comment]
+1

**Comment by ShawnCZek** [comment]
+1, just want to highlight this comment: https://github.com/FortAwesome/Font-Awesome/issues/7369#issuecomment-177162703

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=trailer
