### ISSUE TITLE
Icon request: icon-car-side

### ISSUE THREAD

**Issue by DigiLive** [FortAwesome/Font-Awesome#7370]
It's actually in addition of issue #7369 
If a trailer would exist, a cars side-view would be nice also.

I'm planning to use it for categories about transportation.
IMHO it's a nice addition to the already existing "transportation" icons.

(Depending on the  trailer icons (of #7369 ), it would be great if the car points to the same direction as the trailers would be represented.)

![car-64](https://cloud.githubusercontent.com/assets/7613487/9643240/0c4a6522-51c1-11e5-854d-ec2be13ead3b.png)

**Comment by Zaanmedia** [comment]
+1

**Comment by Melloyell** [comment]
+1

**Comment by Crissov** [comment]
🚗 [U+1F697](http://emojipedia.org/car/) Unicode emoji #222

**Comment by krislinus** [comment]
+1

**Comment by sensibleworld** [comment]
We added a car-side icon in version 5.2 https://fontawesome.com/icons/car-side?style=solid
