### ISSUE TITLE
Icon Request: fa-patreon

### ISSUE THREAD

**Issue by mysticvisions** [FortAwesome/Font-Awesome#7371]
Please include an icon for the brand Patreon (social media crowd-funding). https://www.patreon.com
![patreon_navigation_logo_mini_orange](https://cloud.githubusercontent.com/assets/14099890/9645305/91445478-517f-11e5-952b-39bcf5dd81f8.png)

**Comment by TheChen5** [comment]
Dupe #3257 
+1 that
Please :mag:before:heavy_plus_sign:
