### ISSUE TITLE
Icon request: old windows version

### ISSUE THREAD

**Issue by sboub95** [FortAwesome/Font-Awesome#7372]
I would like a old version icon of Windows (XP, 2000). Because in the latest version 4.4.0, it's new icon of Windows (8, 10).

http://www.icone-png.com/png/37/36612.png

Thanks

**Comment by TheChen5** [comment]
Dupe #7180
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by sboub95** [comment]
I'm sorry, I'm forget that windows7 icon is older than windows8 
Thx for "duplicate" ;)
