### ISSUE TITLE
Issue with Internet Explorer 11 or IE11 when you have large number of icons on HTML page

### ISSUE THREAD

**Issue by stephenmangion** [FortAwesome/Font-Awesome#7376]
Hi,

This issue occurs only on IE 11
------------------------------------------

I have encountered an issue where I am using a large number font-awesome icons in a table and the browser becomes unresponsive. Scrolling of the page is very slow and the interactions on the page are almost impossible. I have been trying to diagnose this issue by replacing the actual markup of the icons from using i tags to span tags and also tried replacing the table to divs but it didn't work. PLEASE HELP. I believe this is not a IE issue but rather a Font-Awesome one!!

**Comment by My1** [comment]
one issue is enough.

Duplicate of #7375 .
