### ISSUE TITLE
Icon Request: fa-waterdrop

### ISSUE THREAD

**Issue by TheFrenchCommander** [FortAwesome/Font-Awesome#7381]
An icon of a water droplet would be nice.

I am making a small game (just for the fun of it) and I feel like having a small water drop icon with a red color would be a nice way to represent my health bar. I believe it could also be useful in more projects like a restaurant, an environmental blog, a website holding a water-consumption section and more.

As I am aware that such icon exist with other fonts, I still think it would be a nice addition to your icons list.

Thank you for your time.

**Comment by TheChen5** [comment]
Maybe icon tint ?
http://fortawesome.github.io/Font-Awesome/icon/tint/

**Comment by TheFrenchCommander** [comment]
Oh! I guess I didn'T found it before. Yes. Kinda like it. Thank you. :)

Date: Thu, 3 Sep 2015 15:29:52 -0700

**Comment by My1** [comment]
then how about an alias? since it is a drop.

**Comment by TheFrenchCommander** [comment]
Sure. :)

Date: Fri, 4 Sep 2015 05:04:46 -0700

**Comment by deNULL** [comment]
"fa-tint" is a very confusing name for such icon, I agree.

Some aliases like "fa-drop", "fa-droplet", "fa-waterdrop" or even "fa-teardrop" would be much more suitable.

**Comment by tagliala** [comment]
done!
