### ISSUE TITLE
Icon Request: fa-donkey, fa-elephant (replublican, democrat)

### ISSUE THREAD

**Issue by awise882** [FortAwesome/Font-Awesome#7382]
With the upcoming presidential election in 2016, it would make sense to have an icon for the two main political parties in the United States..elephant and a donkey.  A sample image is: https://about.infogr.am/wp-content/uploads/2015/06/Democrat-Republican.jpg  but anything in the elephant/donkey family would work.

**Comment by pvspencer22** [comment]
This would be great going into the election season!

**Comment by Yanchek99** [comment]
+1

**Comment by SeanFromIT** [comment]
+1. See also: #2440

**Comment by alexfilatov** [comment]
+1

**Comment by jgarib** [comment]
+1

**Comment by dsartain18** [comment]
+1

**Comment by HarrisJT** [comment]
+1

**Comment by natalka01** [comment]
+1; & wave here: [https://github.com/FortAwesome/Font-Awesome/issues/2266](https://github.com/FortAwesome/Font-Awesome/issues/2266)

**Comment by Wingo5315** [comment]
+1

**Comment by tagliala** [comment]
Here there are!

https://fontawesome.com/icons/democrat?style=solid
https://fontawesome.com/icons/republican?style=solid
