### ISSUE TITLE
New Google Logo

### ISSUE THREAD

**Issue by ferkennedy** [FortAwesome/Font-Awesome#7384]
Please change de g+ icon for the new one.

**Comment by TheChen5** [comment]
Dupe #7357 
+1 that
Please  :mag:before:heavy_plus_sign:

**Comment by astropelusa** [comment]
+1 please!

**Comment by meebwolf** [comment]
+1 as well!

**Comment by FSElias** [comment]
+1

**Comment by tagliala** [comment]
closing here, duplicate of #7357
