### ISSUE TITLE
Icon request: icon-highheel

### ISSUE THREAD

**Issue by Haegar2001** [FortAwesome/Font-Awesome#7393]
Dear Community,
I am searching for an icon that represent a high heel shoe. I have a shoestore and cannot find an adequate icon for my website. 
Is there someone who can help me out?
<img width="327" alt="bildschirmfoto 2015-09-05 um 16 03 28" src="https://cloud.githubusercontent.com/assets/14139022/9699558/b1ebad60-53e7-11e5-8527-35ac202b71b0.png">
<img width="354" alt="bildschirmfoto 2015-09-05 um 16 03 04" src="https://cloud.githubusercontent.com/assets/14139022/9699559/b20d5870-53e7-11e5-94c2-c9d512debd5a.png">

**Comment by TheChen5** [comment]
Dupe #3473
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by attiquer** [comment]
+1 that

**Comment by jonathancbatista** [comment]
+1 for that

**Comment by kubaizi** [comment]
+1
