### ISSUE TITLE
Icon Requests: iTunes and Google Play Music

### ISSUE THREAD

**Issue by matchboxhero** [FortAwesome/Font-Awesome#7396]
Icons for iTunes and Google Play Music would be useful to use alongside spotify.

Cheers,
Ste.

**Comment by TheChen5** [comment]
iTunes dupe #919 
Google Play dupe #2272 
+1 those
Please :mag:before:heavy_plus_sign:

**Comment by Cat5TV** [comment]
Google Play Music is NOT the same as Google Play Store. +1 for Google Play Music.
