### ISSUE TITLE
icon-request: IMDB

### ISSUE THREAD

**Issue by ericpatriq** [FortAwesome/Font-Awesome#7401]
Any, or all of these icons would be fantastic, if you have the bandwidth to create these.
Keep up the great work!!!
![cinema-imdb-icon](https://cloud.githubusercontent.com/assets/5140104/9704023/736093c6-544b-11e5-8441-940189fa6234.png)
<img width="256" alt="imdb-icon" src="https://cloud.githubusercontent.com/assets/5140104/9704024/736176a6-544b-11e5-81b2-f14c6a39a7ab.png">
<img width="362" alt="screen shot 2015-09-06 at 4 01 25 am" src="https://cloud.githubusercontent.com/assets/5140104/9704031/fbd12c7a-544b-11e5-9f6f-cabecab8c8cd.png">

**Comment by TheChen5** [comment]
Dupe #998 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by bennobo** [comment]
The title of this issue makes me nuts: please change it to IMDB. ;)

**Comment by tagliala** [comment]
closing as a duplicate
