### ISSUE TITLE
Update google, google-plus, google-plus-square icons.

### ISSUE THREAD

**Issue by ChALkeR** [FortAwesome/Font-Awesome#7402]
Hi. Google has updated branding, and that also includes google-plus.
I guess that `google`, `google-plus`, and `google-plus-square` icons should be updated in the next version.

**Comment by TheChen5** [comment]
Dupe #7357 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by ChALkeR** [comment]
No idea how I missed that. Sorry. I checked only the few latest issues, expecting this to be somewhere near the top.
