### ISSUE TITLE
Alias Request: times -> cross

### ISSUE THREAD

**Issue by ConnorMcF** [FortAwesome/Font-Awesome#7404]
The X symbol is also called a cross and I'm always mixing this up.

**Comment by tagliala** [comment]
added as a filter, it should be available in the next docs build

https://github.com/FortAwesome/Font-Awesome/commit/729766fd3968585c384837b10614c3f6f9b096b4

**Comment by tagliala** [comment]
If you need an alias, please consider a custom css rule

**Comment by ConnorMcF** [comment]
It's mainly because when I'm looking it up I type cross straight away.
