### ISSUE TITLE
Icon request: icon-gym-weight or icon-fitness

### ISSUE THREAD

**Issue by hashif** [FortAwesome/Font-Awesome#7408]
![weightlifting4](https://cloud.githubusercontent.com/assets/4726449/9714031/fab560dc-555d-11e5-9dc9-dddd16cc33e2.png)

**Comment by TheChen5** [comment]
Dupe #1500 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
closing here
