### ISSUE TITLE
Icon request: icon-arastta

### ISSUE THREAD

**Issue by burakcakirel** [FortAwesome/Font-Awesome#7410]
I'd like to see Arastta icon in Font-Awesome. Arastta is an Open Source eCommerce software.
http://arastta.org/logo
http://arastta.org/images/logo/arastta-logo.pdf
http://arastta.org/images/logo/arastta-logo.svg

Thank you :)

**Comment by feather0148** [comment]
+1

**Comment by osworx** [comment]
+1

**Comment by sunsys0** [comment]
+1

**Comment by user-e** [comment]
![The image](http://arastta.org/images/logo/arastta-logo.svg)

**Comment by OptimumTheme** [comment]
+1 for Arastta

**Comment by EnesErtugrul** [comment]
+1

**Comment by syntaxerror** [comment]
+1

**Comment by cuneytsenturk** [comment]
+1
