### ISSUE TITLE
Icon Request: fa-lock-open

### ISSUE THREAD

**Issue by mariegithub** [FortAwesome/Font-Awesome#7412]
make an icon lock open, 
to represent usage rights.
Thanks.

**Comment by aethior** [comment]
Hi,

Maybe you want these icons?

http://fortawesome.github.io/Font-Awesome/icon/unlock/ 
http://fortawesome.github.io/Font-Awesome/icon/unlock-alt/

**Comment by mariegithub** [comment]
Hi @aethior,
sorry, by typing "lock" into the search bar in fa website that does not have to offer me the opposite ... thank you!

**Comment by aethior** [comment]
Hi @mariegithub,

You are right, the search experience is not very good in this case. When you search "**lock**", the search results doesn't offer results for "un**lock**". (cc @tagliala)

regards :)

**Comment by kjodle** [comment]
That's a browser issue. In Chrome, searching for "lock" also leads to "clock" and "unlock".

**Comment by aethior** [comment]
Hi @kjodle,

My results using Google Chrome '45.0.2454.85 m'.
![example](https://cloud.githubusercontent.com/assets/1769227/9768587/e49c1ade-5724-11e5-8cb2-7ffe6a5583ca.png)

**Comment by kjodle** [comment]
I just used ctrl+f.

**Comment by tagliala** [comment]
Just added a lock filter to unlock icon. This should help, we will find in the next docs build

**Comment by My1** [comment]
well I still dont find the unlock stuff in FF41 and I think the lock-open/lock-open-alt aliases should be in place I mean a lot of stuff has aliases (like cog/gear or similar stuff) and I usually use a class depending on the usage of an icon, meaning I'd rather use lock-open in a lot of cases where I am not going to unlock something.

**Comment by tagliala** [comment]
@My1 

Maybe Dave didn't rebuild the docs yet

btw filters came after aliases. Aliases "pollute" the css. I'm to drop all aliases in favour of filters

**Comment by My1** [comment]
but filters are only for search, you cannot actually use them, can you?
