### ISSUE TITLE
Bug add fontawesome by bower

### ISSUE THREAD

**Issue by tenaz3** [FortAwesome/Font-Awesome#7421]
Hi, I just use fontawesome and grunt couldn't inject css in my index.html. So I check bower.json file. 
The name change for some thing like
"font-awesome"
My old version:    "fontawesome": "~4.3.0" works.
Maybe this can be a typo or problem in bower, but I suppose to be in the new name

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
