### ISSUE TITLE
Icon Request: icon-van

### ISSUE THREAD

**Issue by Ashbo** [FortAwesome/Font-Awesome#7424]
Hi,

I'd like to request a Van icon to be added. The company I work for build automotive websites, and use a lot of vehicle related iconography. We're looking at the optimisation of pages, and considering font awesome, and this is something we'd need.

Stupidly I challenged my boss to find an icon we'd need, but isn't there already. He beat me with the van. Now I need to show him that we can request icons, and hopefully, this one can get added in.

Truck is close, but is clearly a truck and not a van. I see a van similar to truck, but instead of a square body, it's more curvy - maybe something as simple as: http://cdns2.freepik.com/free-photo/_318-9252.jpg

Feel free to ask if you need anything else!

Cheers,
Ash

**Comment by TheChen5** [comment]
Dupe #3260
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
closing here
