### ISSUE TITLE
Icon request: Authorea

### ISSUE THREAD

**Issue by smaret** [FortAwesome/Font-Awesome#7428]
It would be great to have a Font-Awesome icon for [Authorea](http://www.authorea.com). This would allows me to add a  button on my blog page that points to articles I'm writing on Authorea. I'm sure that many other Authorea users would find this useful as well.

The Authorea icon is attached.
![authorea](https://cloud.githubusercontent.com/assets/95471/9769753/54c81f86-572c-11e5-936e-d390283483d4.png)

Note that I am not affiliated with Authorea.

**Comment by smaret** [comment]
This may interest you @apepe.

**Comment by TheChen5** [comment]
Dupe #5616
+1 that
Please :mag:before:heavy_plus_sign:
