### ISSUE TITLE
Icon Request: fa-fa-history

### ISSUE THREAD

**Issue by prashobkthamban** [FortAwesome/Font-Awesome#7431]

**Comment by prashobkthamban** [comment]
![history](https://cloud.githubusercontent.com/assets/13463173/9782044/5bf450c8-57b7-11e5-91d4-fddd0c10c26f.png)

**Comment by tagliala** [comment]
dup of #3175, please +1 that request

btw we already have an icon to represent history: http://fontawesome.io/icon/history/
