### ISSUE TITLE
Icon request: icon-signal-messenger [+ fork with iOS icon]

### ISSUE THREAD

**Issue by patcon** [FortAwesome/Font-Awesome#7434]
Work done here:
https://github.com/f41c0r/Font-Awesome

cc: @f41c0r

**Comment by tagliala** [comment]
Sorry, I didn't get this request

could you please clarify?

**Comment by user-e** [comment]
@patcon 
**I am not part of this conversation or this request**,
but I noticed the *waiting for feedback* tag and that
*Tagliala* is waiting for feedback.

**Comment by tagliala** [comment]
It should be the same of the other request, but I need an example of signal

**Comment by f41c0r** [comment]
https://github.com/WhisperSystems/Signal-iOS/blob/fd3e75b51ddf77ccab8493efe5c3a1def01d4e7d/Signal/Images.xcassets/AppIcon.appiconset/spotlight-icon@3x-1.png

**Comment by f41c0r** [comment]
see also https://lists.riseup.net/www/arc/whispersystems/2015-09/msg00015.html

**Comment by pascalschulthess** [comment]
+1

**Comment by freeboson** [comment]
@tagliala The [iOS](https://itunes.apple.com/us/app/signal-private-messenger/id874139669?mt=8)/[Android](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en)/[Chrome](https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en) icons have converged, and they're now the same speech bubble with dashed outline. (It used to be a keyhole on Android.)

**Comment by iamcryptoki** [comment]
+1

**Comment by ousiadigital** [comment]
how come that no one else needs that or that it wasn't introduced already?
with my contact list at least half of it has Signal ... and they are getting more and more

**Comment by berensp** [comment]
Hi Folks. It's the right time to build [this one](https://signal.org/)). They're now legit with ">10M downloads on Android (+ another 40% of the app's users are on iOS."

**Comment by aldaw** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/16600

**Comment by aldaw** [comment]
Hey in Germany the parliament is not allowed to use WA only Signal, it is like standard now.
We need that icon pleaaseee

**Comment by Darneas** [comment]
+1

**Comment by matt1tk** [comment]
+2

**Comment by hexandcube** [comment]
Signal is the most secure messenger that exists right now. It really deserves an icon.

**Comment by bermanboris** [comment]
Bump

**Comment by hexandcube** [comment]
A lot of people joined Signal recently

**Comment by AUTIMEDIA** [comment]
Do you need a designer?

**Comment by maximilianofried** [comment]
any news about the icon?

**Comment by pascalscr** [comment]
This ain't the icon I submitted, have you even read my submission?

**Comment by pascalscr** [comment]
That signal messenger icon is outdated and doesn't suite the current app icon @tagliala

**Comment by tagliala** [comment]
> That signal messenger icon is outdated and doesn't suite the current app icon @tagliala

Not a problem, we take the latest official logo available from the brand guidelines

**Comment by ttmx** [comment]
Are there any news on this issue? Has been a while since anyone replied to it.

**Comment by Meteor0id** [comment]
@tagliala there are no brand guidelines published by Signal but you can contact them on Twitter Signalapp or email support@signal.org

I think it is not necessary to contact them though, their logo is the same everywhere. Here it is

Svg:
https://github.com/signalapp/Signal-Desktop/blob/87d6a55ce87a3f09e34da1dbc9e69f400ac7e32d/images/signal-logo.svg

Png:
https://github.com/signalapp/Signal-iOS/blob/02bd1f02bc7b7cae251dd2e816c8ce7114b50326/Signal/Images.xcassets/AppIcon.appiconset/app-store-1024.png

Others sizes
https://github.com/signalapp/Signal-iOS/tree/02bd1f02bc7b7cae251dd2e816c8ce7114b50326/Signal/Images.xcassets/AppIcon.appiconset

The title of this issue speaks of a fork for iOS not sure what that is about, the icon is the same on all platforms.

Anything else you need or is this enough to introduce the icon to font awesome?

**Comment by mpe85** [comment]
@tagliala Any news on this?

**Comment by 1emc** [comment]
Any news on this? I would really love to see Signal in future version. Would help me a lot on different projects.

**Comment by mwllgr** [comment]
+1 from me too. If WhatsApp is in FontAwesome, Signal should be too ^^

**Comment by mendibox** [comment]
Just dropping my thumbs up to reques the Signal icon

**Comment by c-seeger** [comment]
+1 for Signal icon

**Comment by Jack-Toulouse** [comment]
+1 for Signal icon 
👍

**Comment by laidbackindustries** [comment]
+1

**Comment by mendibox** [comment]
Really weird this issue is still open and no response after 8 years.

**Comment by laidbackindustries** [comment]
> Really weird this issue is still open and no response after 8 years.

Yes, indeed! Signal has **more than 100 million downloads** in the Google Play store alone now.  
![grafik](https://github.com/FortAwesome/Font-Awesome/assets/15227261/cf8c09ca-095f-4d34-944a-9a46b234cbc9)

It is used or recommended by the **European Commission, U.S. Senate, governments, organisations and companies around the world, MI6, the New York Times, Washington Post, CNN, Elon Musk, Edward Snowden, Jack Dorsey, Mark Zuckerberg**,... you name it and has been featured in House of Cards, Mr. Robot and other prominent TV shows (see for a long list https://gist.github.com/signalde/628bcb04ee89be4f8137b03234f9535a). 

Its Signal protocol is a gold-standard of encryption and used by WhatsApp, Google, Microsoft and many other (https://en.wikipedia.org/wiki/Signal_Protocol). Plus it's run by a non-profit foundation and donation-based.

@tagliala and @sensibleworld let us know if you need anything else (the links to the official logo as single-color SVG have been posted above by @Meteor0id). I can also find a style guide if needed.

**Comment by MJNL** [comment]
+1 for Signal in fontawesome!

**Comment by jenskeiner** [comment]
+1 for adding Signal to fontawesome.

**Comment by moortaube** [comment]
+1 This icon is realy missing!

**Comment by cherti** [comment]
I think inclusion of Signal into FontAwesome would be quite awesome!

**Comment by sensibleworld** [comment]
Added https://fontawesome.com/icons/signal-messenger?f=brands&s=solid

**Comment by Meteor0id** [comment]
in the pro version, even though Signal is such a widely used non-profit messenger. Sad.

**Comment by hexandcube** [comment]
Why is a brand icon a part of the overpriced pro icon set?

**Comment by berensp** [comment]
> Added https://fontawesome.com/icons/signal-messenger?f=brands&s=solid

Friends, this has been a great eight-year thread. Now it comes to an end thanks to the excellent work of @sensibleworld—thanks, Sir!

**Comment by berensp** [comment]
> Why is a brand icon a part of the overpriced pro icon set?

one step at a time. hopefully it's around a long time — at least longer than [this one](https://fontawesome.com/icons/threads?f=brands&s=solid) 😁

**Comment by scarlachs** [comment]
out of 484 brand icons, signal is now the third pro brand icon

**Comment by sensibleworld** [comment]
Doh! No... this is a mistake. All brand icons should be marked as free. We'll get it fixed.

**Comment by ousiadigital** [comment]
![3420055606_74296b5ffc_c](https://github.com/FortAwesome/Font-Awesome/assets/57712584/4d26e5e4-ac55-46f0-a65b-29a5dee868d1)

not using fontawesome any more.... I'm just here for the action ;P

**Comment by tagliala** [comment]
> out of 484 brand icons, signal is now the third pro brand icon

who are the other two? This should be a bug

**Comment by scarlachs** [comment]
> > out of 484 brand icons, signal is now the third pro brand icon
> 
> who are the other two? This should be a bug

Webflow and Shoelace
<img width="430" alt="Screenshot- 2023-11-29 at 09 50 37" src="https://github.com/FortAwesome/Font-Awesome/assets/83089404/65bdf74a-ec37-41fb-9198-e417a5f7254a">

**Comment by tagliala** [comment]
Closing here, this should have been fixed in 6.5.1
