### ISSUE TITLE
Icon Request: fa-product, fa-inventory ,fa-user-admin,fa-user-manager,fa-user-staff

### ISSUE THREAD

**Issue by vivekdoshi2** [FortAwesome/Font-Awesome#7436]
fa-product, fa-inventory
Icon for products
Like : Bottle/Shirt/Pant.... 

fa-user-admin,fa-user-manager,fa-user-staff
Icon to show the user's post,
Like from direct icon user can understand the post of user,
like if user is admin,manager or staff
Manager : user with suit
Staff : user with engineer cap,or funky cap
Something like that

**Comment by tagliala** [comment]
Sorry, can't keep this open

Take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

There are some duplicates you could +1: like #2553 #3397. Please use the search bar

Thanks
