### ISSUE TITLE
Icon request: snowflake

### ISSUE THREAD

**Issue by thasneem077** [FortAwesome/Font-Awesome#7441]
Icon request: snowflake 

http://www.thermodial.ie/wp-content/uploads/2012/07/air-conditioning-symbol_small.png

**Comment by user-e** [comment]
Here is the icon shown in this page:
![Image for the icon](http://www.thermodial.ie/wp-content/uploads/2012/07/air-conditioning-symbol_small.png)

**Comment by user-e** [comment]
@thasneem077 
+1 Nice idea, a very commonplace icon that I
think a huge range of people could potentially benefit from.

**Comment by TheChen5** [comment]
Dupe #1739 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
dupe, closing here
