### ISSUE TITLE
BootstrapCDN by MaxCDN without font file (.ttf .otf)?

### ISSUE THREAD

**Issue by TrangDinhVan** [FortAwesome/Font-Awesome#7447]
In "Get started" section, it is said that the easiest way to have font awesome is to use the cdn
I wonder if I need the font files in my project folder, because I find the link just reference the .css only.

**Comment by tagliala** [comment]
the css has references to font files in the font face declaration

https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L9

then the browser picks up the most appropriate file (eg: chrome -> woff2, ie -> otf)

Hope it helps
