### ISSUE TITLE
Icon Request: fa-pdf

### ISSUE THREAD

**Issue by umairrazzaq** [FortAwesome/Font-Awesome#7452]
Hi, I love font-awesome. You guys did amazing and i used it on many of my projects with Bootstrap. I got all icons that are commonly used in a web projects. But i noticed today during converting PSD to html template. Actually i want pdf icon as resume download. I checked all icons and found fa-file-pdf-o icon but it has border like page-file and i want just pdf icon. I hope its clear to you.

Also i hope it will be released soon.

**Comment by umairrazzaq** [comment]
![pdf-icon-example](https://cloud.githubusercontent.com/assets/5692632/9863877/81d65ea4-5b5d-11e5-989b-094ca2fdc75d.png)

**Comment by TheChen5** [comment]
This looks very similar:
http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/

**Comment by tagliala** [comment]
Duplicate of #1911?

**Comment by ShamanFromSiberia** [comment]
tagliala, seems to be.

Anyway, +1

**Comment by tagliala** [comment]
closing here as a duplicate
