### ISSUE TITLE
New Icon Request for Medical Category

### ISSUE THREAD

**Issue by Ikramd** [FortAwesome/Font-Awesome#7455]
Hi Support,

I am looking for below icons plz provide ASAP
1- Capsule
2- Patient 
3- Prescription 
4- Pharmacy

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please split this request into individual requests, having care of searching for duplicates and providing examples where needed.

Duplicates: capsule #1778 , pharmacy: #2009
