### ISSUE TITLE
Icon request: about autocad

### ISSUE THREAD

**Issue by kimsonggook** [FortAwesome/Font-Awesome#7456]
I need similar to AUTOCAD icon, for example，line，quadrangle，circle

**Comment by tagliala** [comment]
sorry, I didn't get this request

could you please clarify?

**Comment by tagliala** [comment]
Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by aethior** [comment]
@tagliala I think you can close here.
