### ISSUE TITLE
Icon Request: fa-scoopit

### ISSUE THREAD

**Issue by romainmenard** [FortAwesome/Font-Awesome#7457]
Hi,

I request the icon for the social media "Scoop It". I would use it for the websites of the university where i'm working. I use Font Awesome to make links towards social networks, and somebody asked me to add a Scoop It icon.

Could you do it ? That wold be great.

Thank you for your great work,

Romain
Web Developer
University of Poitiers (France)

![scoopit](https://cloud.githubusercontent.com/assets/8914624/9877090/04cd57a6-5bbb-11e5-9873-13de84eea592.png)

**Comment by tagliala** [comment]
duplicate of #1603, please +1 that request

closing here
