### ISSUE TITLE
Icon Request: fa-old-pen

### ISSUE THREAD

**Issue by LakshmanKatragadda** [FortAwesome/Font-Awesome#7459]
![1364576541_skills](https://cloud.githubusercontent.com/assets/1289975/9896894/7a7674b6-5c5f-11e5-8422-71e04cf564ee.png)

Hi Geeks
There is no any icon for Old Pen  which we can show. If it is available with different name then please let me know if not Please provide. I have attached a icon image .Please find attached file.

Regards,
Laxman.K

**Comment by ShamanFromSiberia** [comment]
+1

**Comment by cherrador** [comment]
+1

Why? Pencil icon is normally associated with edit. Instead old-pen or ink-pen is associated with signature. I have an application that accept signatures and I have been using pencil. Most users complain that the icon is not intuitive.

**Comment by laxman1223** [comment]
Hey How Much Time is take for add to Milestone  because i want use it ASP

**Comment by tagliala** [comment]
@laxman1223 if you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by victorpre** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pen-nib?style=solid
https://fontawesome.com/icons/pen-fancy?style=solid
