### ISSUE TITLE
Icon Request: fa-pyramid

### ISSUE THREAD

**Issue by amayd** [FortAwesome/Font-Awesome#7460]
Hi Team,
There is no any icon for Pyramid Chart which we can show. If it is available with different name then please let me know if not Please provide. I have attached a icon which i found on another website. Please find attached file.

Regards,
Ameya D.
![1442398999_pyramid](https://cloud.githubusercontent.com/assets/5735968/9897022/2e57d99c-5c61-11e5-8003-0cc71f6c1a23.png)

**Comment by amayd** [comment]
@tagliala Is there any updates for the same

**Comment by tagliala** [comment]
please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by aethior** [comment]
Hi @amayd,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/chart-pyramid

Regards.

cc/ @tagliala
