### ISSUE TITLE
Icon Request: fa-angularjs

### ISSUE THREAD

**Issue by shool70045** [FortAwesome/Font-Awesome#7469]
Request to add angularjs icon.
![angularjs-large](https://cloud.githubusercontent.com/assets/4208384/9924372/6d547842-5d1c-11e5-8890-2676b884b382.png)

**Comment by TheChen5** [comment]
Dupe #2027 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by Patrick-W-McMahon** [comment]
Just the A on a shield should be enough for this icon.
