### ISSUE TITLE
Icon request: icon-Kevin

### ISSUE THREAD

**Issue by eyalwass** [FortAwesome/Font-Awesome#7470]
Hello, Kevin is our brand icon, please help me and create this icon.

**Comment by eyalwass** [comment]
![kev_1-02](https://cloud.githubusercontent.com/assets/14326640/9927457/4eff9c5e-5d27-11e5-9670-f5d56a9db8ff.png)

**Comment by sensibleworld** [comment]
Hey @eyalwass. Apologies for missing this issue. If you're interested in purchasing a brand icon for inclusion in Font Awesome, please reach out to us at hello@fontawesome.com
