### ISSUE TITLE
problem upgrading to 4.4 using base64 from woff

### ISSUE THREAD

**Issue by tobibeer** [FortAwesome/Font-Awesome#7472]
I am making FontAwesome available as a font-plugin to TiddlyWiki. Trying to upgrade the font from 4.3 to 4.4 I am experiencing an oddity in the form of all icons up to 4.3 working just fine, but not any of the new ones.

Here's a [test wiki](http://tobibeer.github.io/tw/fa/4.4.html).

Clicking on the 4.4 tagpill allows you to open three example icons from v4.4... none of which render properly. I'm a bit at loss why the new ones won't render at all.

What I did was to base64 encode the woff from the distribution and then use it in a stylesheet... which worked flawlessly before as you can see here...

http://tobibeer.github.io/tw/fa

**Comment by tagliala** [comment]
What I'm supposed to see?

Chrome / Firefox / Safari, OSX 10.10.5

![screen shot 2015-09-17 at 11 51 41](https://cloud.githubusercontent.com/assets/556268/9930223/7eca7a0c-5d32-11e5-8769-416f475a1b42.png)

**Comment by tagliala** [comment]
no feedback, closing here
