### ISSUE TITLE
Icon Request: fa fa-oscommerce

### ISSUE THREAD

**Issue by Narayan1214** [FortAwesome/Font-Awesome#7477]
hello,
i need a oscommerce icon to add it in my website

**Comment by caduvieira** [comment]
dupe of #4885 ?

**Comment by Googlecloud12** [comment]
http://www.magentocommerce.com/

**Comment by Narayan1214** [comment]
what you mean by dupe of #4885 ??

**Comment by Googlecloud12** [comment]
Not yet Still has to know wht is this ??

**Comment by caduvieira** [comment]
Is it the same request of #4885 ?

**Comment by Narayan1214** [comment]
this is the same request of #4885 so what i do??
i need this icon so give me correct solution

**Comment by caduvieira** [comment]
+1 that issue and wait for it to be done or customize FontAwesome

Read more in:
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment]
@Narayan1214 please +1 #4885

Closing here

**Comment by tagliala** [comment]
@caduvieira thanks
