### ISSUE TITLE
Icon Request: fa fa-prestashop

### ISSUE THREAD

**Issue by Narayan1214** [FortAwesome/Font-Awesome#7479]
Hello,
I need prestashop icon to add it in my website.

Thanx

**Comment by ShamanFromSiberia** [comment]
Taking into account that the OpenCart icon aready exists in FontAwesome, it would be fair to have Prestashop and other free ecommerse engines icons here.

+1

**Comment by loorlab** [comment]
+1 Please

**Comment by team-core** [comment]
+1

**Comment by tagliala** [comment]
closing here as a dup of #2080
