### ISSUE TITLE
Icon Request: icon-roundface

### ISSUE THREAD

**Issue by Sandra85** [FortAwesome/Font-Awesome#7481]
Dear GitHub Community,
I'm working on a shop right now, which works with your awesome font. As much as I love the Font, there are often used and much liked round icons missing. In my case, the round circle is even part of the Logo and a round facebook icon would do a lot for the design. Would you please consider including a round Facebook and rss feed icon into the font?

Please see my page for getting the idea:
http://workspace.schlaegel.info/herzklopfen/

Attached you'll find the PNG file and an example on how I imagine the end result. Please feel free to contact me, if any questions. I have the icons as a vectorized EPS as well.

Thank you tons and all the best,
Sandra
![willow_bearb](https://cloud.githubusercontent.com/assets/14337120/9944868/408a2f96-5d8a-11e5-90a9-918cf1c96050.jpg)

![facebook](https://cloud.githubusercontent.com/assets/14337120/9944921/8ab04d30-5d8a-11e5-8760-f408a4812515.gif)

**Comment by caduvieira** [comment]
You could use stack for this. Example:
http://jsfiddle.net/tohd4o9f/

**Comment by tagliala** [comment]
At the moment, please consider stacking http://fontawesome.io/examples/#stacked or plain css: http://jsfiddle.net/tagliala/4ya23yjL/5/

I'm going to close this one

**Comment by Sandra85** [comment]
Thanks for the help!


-------------------------------
Sandra Beck
Weinstrasse 50
67480 Edenkoben

Ich freue mich auch auf Telefonanrufe auf 01573/1985055



-------- Ursprüngliche Nachricht --------
Von: Geremia Taglialatela <notifications@github.com> 
Datum:19.09.2015  11:08  (GMT+01:00) 
An: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com> 
Cc: Sandra85 <Sandra.Beck@gmx.net> 
Betreff: Re: [Font-Awesome] Icon Request: icon-roundface (#7481) 

At the moment, please consider stacking http://fontawesome.io/examples/#stacked or plain css: http://jsfiddle.net/tagliala/4ya23yjL/5/

I'm going to close this one
