### ISSUE TITLE
Icon Request: icon-roundrss

### ISSUE THREAD

**Issue by Sandra85** [FortAwesome/Font-Awesome#7482]
Message 2/2 :)

Dear GitHub Admin,
I'm working on a shop right now, that works with your awesome font. As much as I love the Font, there are often used and much liked round icons missing. In my case, the round circle is even part of the Logo and a round facebook icon would do a lot for the design. Would you please consider including a round Facebook and rss feed icon into the font?

Please see my page for getting the idea:
http://workspace.schlaegel.info/herzklopfen/

Attached you'll find the PNG file and an example on how I imagine the end result. Please feel free to contact me, if any questions. I have the icons as a vectorized EPS as well.

Thank you tons and all the best,
Sandra
![willow_bearb](https://cloud.githubusercontent.com/assets/14337120/9944868/408a2f96-5d8a-11e5-90a9-918cf1c96050.jpg)

![icon-rss](https://cloud.githubusercontent.com/assets/14337120/9944963/ca863b54-5d8a-11e5-9d22-ebb88dc81937.png)

**Comment by caduvieira** [comment]
You could use stack for this. Example here:
http://jsfiddle.net/Lj7Lw41w/

**Comment by tagliala** [comment]
At the moment, please consider stacking http://fontawesome.io/examples/#stacked or plain css: http://jsfiddle.net/tagliala/4ya23yjL/5/

I'm going to close this one
