### ISSUE TITLE
error fa-tripadvisor and fa-opera

### ISSUE THREAD

**Issue by flmuse** [FortAwesome/Font-Awesome#7484]
Hi,

These fonts are working, appearing as a rectangle box (refer to attached screen shot).

Pls kindly resolve and advise of the update file.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6317397/9950562/778158e4-5dee-11e5-99ce-6ca056ded411.png)

Cheers,
Brad

**Comment by TheChen5** [comment]
TripAdvisor & Opera are new in 4.4
Have you upgraded yet?
Code in HTML:
``` <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">```

**Comment by tagliala** [comment]
Hi, please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
