### ISSUE TITLE
Icon request: fa-line fa-line-square

### ISSUE THREAD

**Issue by kechol** [FortAwesome/Font-Awesome#7485]
Hi,

Thank you for this "awesome" font library.
Would you like to add "LINE" icon to the icon list?

LINE is one of the most popular messenger app in Japan. I would like to use this logo when sharing text or images via LINE.

![line_icon_green](https://cloud.githubusercontent.com/assets/625489/9955569/f71795bc-5e2c-11e5-9072-1df94968a493.png)
![line_icon02](https://cloud.githubusercontent.com/assets/625489/9955572/f97e9170-5e2c-11e5-963b-e6177daed1df.png)

Please refer the guideline for the logo.
http://line.me/logo/guideline/en

Thanks in advance,
kechol

**Comment by tagliala** [comment]
dup of #2631 , please +1 that request

closing here

**Comment by kechol** [comment]
Thanks for the comment. I commented to the first issue.

**Comment by suabahasa** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/2631
