### ISSUE TITLE
Icon Request: fa-promote-ads

### ISSUE THREAD

**Issue by albertonaperijr** [FortAwesome/Font-Awesome#7486]
Good day!

Can I request for a promote-ads icon like the image below?

![promote-ads](https://cdn3.iconfinder.com/data/icons/gray-toolbar-2/512/megaphone_advertising_promote-512.png)

Many thanks,

Alberto Naperi Jr.

**Comment by tagliala** [comment]
already here: http://fontawesome.io/icon/bullhorn/
