### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by CharityJantzen** [FortAwesome/Font-Awesome#7487]
Request for Oil Rig icon.  Would be used throughout the big oil industry for various projects 
![115076-magic-marker-icon-business-oil-well](https://cloud.githubusercontent.com/assets/6976512/9959700/9ba760a0-5ddb-11e5-8c67-fe725f2499bc.png)

**Comment by tagliala** [comment]
duplicate of #3644, please +1 that request

closing here
