### ISSUE TITLE
Icon Request: fa-wine

### ISSUE THREAD

**Issue by santinoalbert** [FortAwesome/Font-Awesome#7492]
It would be useful for websites or online marketing related with wine, for graphic design in the wine sector, etc.
![wine-glass-symbol](https://cloud.githubusercontent.com/assets/14359200/9975786/63a50cea-5ec9-11e5-9709-e5b208125f52.jpg)

Thanks.

**Comment by tagliala** [comment]
duplicate of #370, please +1 that request

closing here

**Comment by santinoalbert** [comment]
+1


Thanks!
