### ISSUE TITLE
New icons request

### ISSUE THREAD

**Issue by baqwasmail** [FortAwesome/Font-Awesome#7495]
Hi,

Thanks for your great work. Please add these icons to font awesome. I am attaching an image with this issue.

Thanks
![font-awesome-request](https://cloud.githubusercontent.com/assets/14363849/9977763/fd054a32-5f12-11e5-9116-e826694afac5.png)

**Comment by TheChen5** [comment]
Sofa #759 
Stroller #6124
Bike #5544
Handshake #878 
Quite a few cloth requests #715 #3197
Looks like all of these are dupes except probably clothes
+1 those
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks, really appreciate

closing here

**Comment by baqwasmail** [comment]
@tagliala @TheChen5 
But how to use these icons. I can't locate them here http://fontawesome.io/icons/
I can use other icons without any problem but can't figure out that icons you referred.

**Comment by tagliala** [comment]
@baqwasmail those are requests. If you need these icons in a short while, you should consider a custom building: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by ralexrdz** [comment]
+1 clothes +1 handshake
