### ISSUE TITLE
Icon request: icon-society6

### ISSUE THREAD

**Issue by anabelLeva** [FortAwesome/Font-Awesome#7498]
I would use this icon to link to my Society6 store from my online portfolio.

![ef95a4_3720bc88383d42eda6274846c09ac4e5](https://cloud.githubusercontent.com/assets/12593040/9982894/3ae36144-5fb9-11e5-866a-18f574819611.jpeg)

**Comment by TheChen5** [comment]
Dupe #4773
+1 that
Please :mag:before:heavy_plus_sign:
