### ISSUE TITLE
ameblo icon url request 

### ISSUE THREAD

**Issue by jimjam12321** [FortAwesome/Font-Awesome#7499]
i'd like the icon for ameblo.co.jp please thanks

**Comment by TheChen5** [comment]
Dupe #5441
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by jimjam12321** [comment]
i did see that but idont understand the website can you help?? i couldnt findthe url on the 5441#

**Comment by tagliala** [comment]
@jimjam12321 #5441 is a request

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by jimjam12321** [comment]
i still dont have the logo??

On Monday, September 21, 2015, Geremia Taglialatela <
notifications@github.com> wrote:
> @jimjam12321 #5441 is a request
>
> Please take a look here:
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/xxF1QjH5vL8GQtW2RWwGNes7DQs5i63c3S_vn09_YziZuEk3XJFCQzM6Ntyq5AiqG9Hy60rrZnTn4VmNrAHDqHTGlhX7i8V4zJwTddr7PtsKmc9SGNLtbclWwws-wELiy375niFlX0ht5GZcgwR6W-l2e6nB9Q=s0-d-e1-ft#https://github.com/notifications/beacon/ANynRg2Ee9MnJe9M-rbXIeo9UaQb2EFwks5oz8bEgaJpZM4GAlfl.gif
>

**Comment by tagliala** [comment]
Yes, ameblo icon is not available in Font Awesome. You should consider a custom build if you need this icon in a short while
