### ISSUE TITLE
Adding fontawesome.css to the array of main files in bower.json

### ISSUE THREAD

**Issue by maisnamraju** [FortAwesome/Font-Awesome#7500]
I was using bower-main-files plugin that gets all the packages based on the list of main files mentioned in the bower.json and the css files are not listed there in the main section of the list, Can the bower.json be modified to add the following piece of code so that it works well with this particular plugin and others that rely on the bower.json file.

```
"main": [
    "less/font-awesome.less",
    "scss/font-awesome.scss",
    "css/font-awesome.css",
    "fonts/FontAwesome.otf",
    "fonts/fontawesome-webfont.eot",
    "fonts/fontawesome-webfont.svg",
    "fonts/fontawesome-webfont.ttf",
    "fonts/fontawesome-webfont.woff",
    "fonts/fontawesome-webfont.woff2"
  ],
```

**Comment by tagliala** [comment]
sorry but bower specs changed and we are following specs

Please use overrides

Refers to #6227
