### ISSUE TITLE
Icon request: any time of the day clock icons

### ISSUE THREAD

**Issue by DerKobe** [FortAwesome/Font-Awesome#7505]
Hey Dave! I'm really happy you like the "setting the clock" idea. And here it is:

Adding Icons for a clock without hands, and separate icons for the little/big hand. 
Now with stacking those icons and rotating the hands via CSS it's possible to create icons showing any time of the day.

Maybe even different watch-faces and hands?

Another gimmick: with two different "fa-spin"-like classes (different transformation times) one could create an icon that looks like the old OS-X Timemachine-in-action icon: a fast running clock.

**Comment by Lynda333** [comment]
+1

**Comment by tagliala** [comment]
Landed in 6.0 Pro https://fontawesome.com/search?q=clock&c=time&s=solid

**Comment by tagliala** [comment]
Sorry, reopening
