### ISSUE TITLE
Icon request: fa-snapchat

### ISSUE THREAD

**Issue by martinlindhe** [FortAwesome/Font-Awesome#7506]
![snapchat](https://cloud.githubusercontent.com/assets/181531/10004067/067c355a-60b0-11e5-9b22-2420e2abed9f.jpeg)

**Comment by TheChen5** [comment]
Dupe #3906 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by martinlindhe** [comment]
Thanks. Couldnt find one
