### ISSUE TITLE
Icon Request: fa-disconnect

### ISSUE THREAD

**Issue by wfssantos** [FortAwesome/Font-Awesome#7514]
without connection with 3g, wifi or lan

**Comment by tagliala** [comment]
any example?

**Comment by ckeryakes** [comment]
![image](https://cloud.githubusercontent.com/assets/11856569/10258870/412878a2-6930-11e5-94c3-563d2dc328bd.png)
![image](https://cloud.githubusercontent.com/assets/11856569/10258886/5bce067c-6930-11e5-9c63-33cb1f2c5ed3.png)

**Comment by ckeryakes** [comment]
Personally I like the first one (from Spotify, Offline indicator). I think the plug thing is a little overused, but essentially I would want to see something obviously broken. A bar, lightning bolt, or jagged horizontal line, split by a line. Just my 2 cents.

**Comment by Googlecloud12** [comment]
+1

**Comment by tagliala** [comment]
Duplicate of #5555, please +1 that request

closing here

**Comment by denkan** [comment]
+1

**Comment by VitalyPankin** [comment]
+1
