### ISSUE TITLE
Icon Request: fa-telephone-old

### ISSUE THREAD

**Issue by KHBOHM** [FortAwesome/Font-Awesome#7516]
A icon with the figure of a old telephone.
Is a nice detail for contacts forms.

Thanks, Great job
![fa-phone-old](https://cloud.githubusercontent.com/assets/14790134/10023540/07aa5b36-6129-11e5-8e13-4f6fbd6c27af.png)

**Comment by TheChen5** [comment]
Dupe #1578 
+1 that
Please :mag:before:heavy_plus_sign:
