### ISSUE TITLE
Icon Request: fa-alarm-bell

### ISSUE THREAD

**Issue by DesignSwitcher** [FortAwesome/Font-Awesome#7518]
Hi Github Team,

Thanks for providing the list of icons, and these are very useful to our project. 

Currently, I need a new icon which resembles the "alarm bell". Check the attached image for reference.
Please help in getting this icon in font awesome.

Regards,
Harish.

![alarm bell](https://cloud.githubusercontent.com/assets/14793851/10030243/515ffaa2-613c-11e5-8060-0ab5e95b251f.png)

**Comment by caduvieira** [comment]
http://fontawesome.io/icon/bell/ ?

**Comment by tagliala** [comment]
alarm: #1926

**Comment by DesignSwitcher** [comment]
Thanks for help guys.

@caduvieira, the link which you mentioned seems to direct me to the regular bell icon. But the icon which i am trying to get is having two arcs at the top of the bell. For reference, pls check the image in my initial post.

**Comment by tagliala** [comment]
I can't leave this open as `fa-bell` because there already is an `fa-bell` and also I can't leave this open as `fa-alarm` because there is already a request for alarm

so I will rename to `fa-alarm-bell`

**Comment by ITPrism** [comment]
+1

**Comment by tagliala** [comment]
I think this has been addressed in FA6 Pro: https://fontawesome.com/v6.0/icons/bell-on?s=solid
