### ISSUE TITLE
icon Request: fa-analytics

### ISSUE THREAD

**Issue by Mayurdoshi** [FortAwesome/Font-Awesome#7523]
Hi can you please provide analytic icon. similar to these.
![ana_small](https://cloud.githubusercontent.com/assets/7879573/10046734/28fcccf6-6228-11e5-98c6-1786844d9bdd.png)

**Comment by caduvieira** [comment]
related to #1560

**Comment by tagliala** [comment]
I would like to see a better name for this icon

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/analytics?style=solid
