### ISSUE TITLE
Icon Request: fa fa-ibeacon

### ISSUE THREAD

**Issue by nico66** [FortAwesome/Font-Awesome#7526]

**Comment by TheChen5** [comment]
Dupe #6375 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by nico66** [comment]
Sorry! J

 

Da: TheChen5 [mailto:notifications@github.com] 
Inviato: giovedì 24 settembre 2015 05:39
A: FortAwesome/Font-Awesome
Cc: nico66
Oggetto: Re: [Font-Awesome] Icon Request: fa fa-ibeacon (#7526)

 

Dupe #6375 <https://github.com/FortAwesome/Font-Awesome/issues/6375>  
+1 that
Please  :mag: <https://assets-cdn.github.com/images/icons/emoji/unicode/1f50d.png> before :heavy_plus_sign: <https://assets-cdn.github.com/images/icons/emoji/unicode/2795.png> 

—
Reply to this email directly or view it on GitHub <https://github.com/FortAwesome/Font-Awesome/issues/7526#issuecomment-142799019> .  <https://github.com/notifications/beacon/AEGFC3ZNEULZDfxJ7io_Y24J2xzhOGtmks5o02fhgaJpZM4GCrVK.gif> 

  _____  

No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.6140 / Virus Database: 4419/10688 - Release Date: 09/23/15
