### ISSUE TITLE
Icon-Set Request: common hardware

### ISSUE THREAD

**Issue by Entwanderer** [FortAwesome/Font-Awesome#7527]
I want to request a set of common hardware icons, currently there are only a few of them like keyboard or server.

I think most of them describe theirselves. If not, i put some additional text next to them.

##### In a first sprint I'm thinking about the following icons:

fa-mouse => computer mouse
fa-network-card=> network card, alias: fa-nic
fa-ram => memory bar
fa-cpu => prozessor chip, alias: fa-processor
fa-fan => computer ventilator
fa-speaker => a single (computer) speaker
fa-joystick
fa-beamer
fa-webcam
fa-usb-stick

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Attach a single color image or two that represent the idea you're going for.
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
