### ISSUE TITLE
Icon request: fa-telegram

### ISSUE THREAD

**Issue by m52go** [FortAwesome/Font-Awesome#7528]
Usage: contact button on site, just like fa-envelope, fa-whatsapp, etc.

Millions of individuals and organizations use Telegram now to communicate, so I think it's significant enough.

![image](https://cloud.githubusercontent.com/assets/735155/10079830/40fa68b2-62ba-11e5-9c8d-b2733f7bd028.png)

**Comment by m52go** [comment]
Oops, this already exists...and has for quite a while (!). What's the deal?

**Comment by aboulfazl950** [comment]
fa-paper-plane
