### ISSUE TITLE
Icon request: fa-usb-stick

### ISSUE THREAD

**Issue by magynhard** [FortAwesome/Font-Awesome#7532]
I request a symbol for an usb-stick.

I think about a stick without cap, so you see the stick and the usb contact.

**Comment by caduvieira** [comment]
dupe of https://github.com/FortAwesome/Font-Awesome/issues/2165 ?

**Comment by thomasfoster96** [comment]
@caduvieira I think #2165 is referring to the USb logo, this issue is for an USB stick icon.

**Comment by MKTGExperts** [comment]
How does one contribute to art work?

![flash](https://cloud.githubusercontent.com/assets/2774503/10105733/2ea83bf2-6365-11e5-9f02-3528badbb9cd.png)
![fa-flash](https://cloud.githubusercontent.com/assets/2774503/10105732/2ea6f896-6365-11e5-8485-d28e3804ab2c.png)

**Comment by phelma** [comment]
+1
I would prefer without the text (perhaps usb Icon)
and vertical/horizontal (not diagonal)

**Comment by aethior** [comment]
+1

**Comment by aethior** [comment]
Hi @magynhard,

This icon was added in v5.11.0.
Check https://fontawesome.com/icons/usb-drive

Regards.

cc/ @tagliala
