### ISSUE TITLE
Icon Request: fa-cc-maestro

### ISSUE THREAD

**Issue by webpeople** [FortAwesome/Font-Awesome#7537]
I think this icon is urgently needed in addition to Visa, MasterCard and Amex.

![index](https://cloud.githubusercontent.com/assets/14832580/10094124/2c408f3a-635c-11e5-9b9d-ffffc69716e9.jpg)

**Comment by tagliala** [comment]
refers to #4266

**Comment by aplaceforallmystuff** [comment]
+1

**Comment by Hoolite** [comment]
+1

**Comment by dynamicsites** [comment]
+1

**Comment by tagliala** [comment]
fff

Duplicate of #4266, please 👍 that request

**Comment by mrjamiebowman** [comment]
+1
