### ISSUE TITLE
Icon request: fa-market

### ISSUE THREAD

**Issue by Mohmdthabet** [FortAwesome/Font-Awesome#7540]
Would be nice if you include this icon. Anyway, thanks for the awesome library!!
![market](https://cloud.githubusercontent.com/assets/9333195/10102871/3ad85dc6-63a1-11e5-90b6-56cd0db2ef1f.png)

**Comment by tagliala** [comment]
sorry, is this a brand? what does the icon represent?

**Comment by the-specialist2005** [comment]
it just refers to a "market" symbol not a brand

**Comment by the-specialist2005** [comment]
it represents women shopping bag

**Comment by aethior** [comment]
There is `fa-shopping-bag` (http://fontawesome.io/icon/shopping-bag/) icon.

@tagliala I think you can close here.

**Comment by fabianneve** [comment]
I'm missing such an icon too. Something like that: 
![stall-icon-18](https://user-images.githubusercontent.com/32954607/35210271-d61c3476-ff51-11e7-80f0-4cc75714848a.jpeg)

**Comment by tagliala** [comment]
@fabianneve please 👍 #1958

**Comment by Bossy-B** [comment]
@fabianneve @tagliala this would be a really great addition for advertising street food/market food stalls for festivals and events alike.

**Comment by Bossy-B** [comment]
@fabianneve @Mohmdthabet I found this under fas fa-store

**Comment by tagliala** [comment]
Thanks for the heads-up

No feedback, closing here
