### ISSUE TITLE
Icon Request: fa-Weather

### ISSUE THREAD

**Issue by Talier** [FortAwesome/Font-Awesome#7543]
Icon Request: fa-...
http://demo.amitjakhu.com/dripicons-weather/

**Comment by Talier** [comment]
very severely lacking weather icons for the different

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

and here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.
