### ISSUE TITLE
Icon Request: user-with-tag

### ISSUE THREAD

**Issue by katsup-sauce** [FortAwesome/Font-Awesome#7547]
I'd like to request an icon that represents a username. Basically this would be a combination of two already-existing icons: "user" and "tag." "tag" would be small and would appear over the lower half of "user."

An alternative would be a miniature of one of those "Hello, my name is ___" badges, but I think the above would be more recognizable.

**Comment by tagliala** [comment]
Refers to #1181 . You will find a solution in #1181

**Comment by nyon** [comment]
I added an icon to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559 that could fit your purpose:

    fa-user-tag

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-tag?style=solid
