### ISSUE TITLE
Icon Request: fa-khukuri

### ISSUE THREAD

**Issue by slayerzinks** [FortAwesome/Font-Awesome#7550]

**Comment by tagliala** [comment]
Could you please clarify? Is this a brand? Use case?

**Comment by slayerzinks** [comment]
yes its a brand...GORKHALI khukuri...and use case too...thank you...

On Mon, Sep 28, 2015 at 5:35 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> Could you please clarify? Is this a brand? Use case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7550#issuecomment-143722190>
> .
>



-- 
Prabin Simkhada

**Comment by tagliala** [comment]
Could you please post a website, or a logo of this brand?

**Comment by slayerzinks** [comment]
please visit this link - http://lifeinthamel.com/

please search for KHUKURI SHOP category in homepage by scrolling down...
we want this icon for our category...
image is attached...

we are having some other problems with other category's icons...
could you help me with that...


On Wed, Sep 30, 2015 at 4:05 PM, Geremia Taglialatela <
notifications@github.com> wrote:

> Could you please post a website, or a logo of this brand?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7550#issuecomment-144347836>
> .
>



-- 
Prabin Simkhada

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
