### ISSUE TITLE
fa-film-add

### ISSUE THREAD

**Issue by n-rocher** [FortAwesome/Font-Awesome#7552]
Hi!
Fisrt : Thanks for you VERY BIG job !
This perfect !
But for my project I need a logo for add video so can you add it ?
I'm thinking about camera plus a plus or the camera retro or videocamera plus a plus !
Thanks bye !

**Comment by tagliala** [comment]
I'm not sure I got this request.

Do you need a camera with a + sign in the corner?

refers to #1181

**Comment by thenathan30** [comment]
Yes ! But i'm very bad using graphic :/

**Comment by tagliala** [comment]
@thenathan30 your request is valid, but I should advise you to consider a custom solution

#1181 does not require graphic skills but you need other skills as explained here: https://github.com/nyon/fontawesome-actions#customize

**Comment by nyon** [comment]
I added an icon to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559 that could fit your purpose:

    fa-camera-plus
