### ISSUE TITLE
Adding Tick to the alias names for Checks

### ISSUE THREAD

**Issue by sarahk** [FortAwesome/Font-Awesome#7553]
Love the icons but couldn't believe you didn't have a tick, seemed to be the most standard of icons. Blame my Anglicized world - Americans call them checks which is absolutely fine but it might help to a have "tick" as an alias.

**Comment by TheChen5** [comment]
#6117

**Comment by tagliala** [comment]
@davegandy could you please rebuild docs?

**Comment by tagliala** [comment]
Leaving this open for tracking purposes

**Comment by sensibleworld** [comment]
`tick` is listed as a search term for `check` now, so it'll pop up in icon search.

https://fontawesome.com/v6.0/icons?q=tick&s=solid
