### ISSUE TITLE
Icon request: icon-locker

### ISSUE THREAD

**Issue by Paulvdwaal** [FortAwesome/Font-Awesome#7554]
Apologies posted accidentally before I had completed the request. Icon request: icon-locker. 
This will be used to indicate an eCommerce locker where customers can collect their online orders. 
Example attached. 
![image](https://cloud.githubusercontent.com/assets/14867877/10129482/87cff75a-65be-11e5-912e-559c5f0cf548.png)

**Comment by tagliala** [comment]
any 14px sutable single color example?

**Comment by Paulvdwaal** [comment]
Hi Geremia

Thanks so much for the incredibly quick response!
I have attached an icon that we have been using from a different font before we changed to Font-Awesome.
I hope this is what you are looking for.

Thanks again


Paul van de Waal
eCommerce Executive
Makro SA
A division of MASSMART Holdings Limited
P/Bag X4│Sunninghill  2157│South Africa
Massmart House│21 Peltier Drive│Sunninghill 2157│Sandton│South Africa
Tel: +27 (011) 797-0663│Fax: +27 (086) 685 3071 │Cell: +27 (082) 781 5005
Email: mailto:paul.vandewaal@makro.co.za Web: http://www.makro.co.za<http://www.makro.co.za/>

**Comment by tagliala** [comment]
Hi, you're welcome

please do not use email attachments, they don't work. Post your example directly on github

**Comment by Paulvdwaal** [comment]
Will do thanks

**Comment by Paulvdwaal** [comment]
Hi Geremia
I have attached a png example

Thanks again

![locker icon](https://cloud.githubusercontent.com/assets/14867877/10144653/01721c36-661f-11e5-9caa-489b8f1115c5.png)

**Comment by Paulvdwaal** [comment]
Hi
Is there any update on this request?
Thanks

**Comment by Paulvdwaal** [comment]
Hi Geremia

Do you have an update on this request?

**Comment by tagliala** [comment]
@Paulvdwaal please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
