### ISSUE TITLE
Icon Request: fa-tournament

### ISSUE THREAD

**Issue by doormalena** [FortAwesome/Font-Awesome#7558]
Use case: indicating a hierarchy (e.g. orgchart, tournament etc.)

![images duckduckgo com](https://cloud.githubusercontent.com/assets/8328876/10142607/07a41e98-6614-11e5-9642-d983371b6ef1.png)

**Comment by doormalena** [comment]
![tournament](https://cloud.githubusercontent.com/assets/8328876/10142558/c4dd93c8-6613-11e5-925c-6bd1ac4251a2.png)

**Comment by tagliala** [comment]
:+1:
