### ISSUE TITLE
Icon Request: fa-fish

### ISSUE THREAD

**Issue by jcarpenterdesign** [FortAwesome/Font-Awesome#7559]
I would like to suggest an icon in the shape of a fish - like a "goldfish cracker."

I maintain a website for a company that has adopted the "Fish Philosophy" and I would like a way to use this iconography throughout the website alongside the many other icons I use from Font Awesome.

For others, I could see this icon being useful in aquatic or pet-related motifs.

Thanks for your consideration!

**Comment by caduvieira** [comment]
dupe of #2722
