### ISSUE TITLE
Browser cant find woff2

### ISSUE THREAD

**Issue by warrendodsworth** [FortAwesome/Font-Awesome#7561]
I'm using an asp.net 4.5 mvc project. 

The browsers constantly throw up this 404 error.

![image](https://cloud.githubusercontent.com/assets/1066996/10152765/f83b101c-6698-11e5-8da7-8002174268df.png)

I've tried modding the web.config 
It has no issues finding the other font files.

`url('/fonts/fontawesome-webfont.woff2?v=4.4.0') format('woff2')`

Any ideas?

**Comment by tagliala** [comment]
Sorry, can't help

**Comment by VitorLuizC** [comment]
The same is happening here.
![image](https://cloud.githubusercontent.com/assets/9027363/10223854/97013200-6831-11e5-83f5-406f0ddbdd24.png)

**Comment by mariegithub** [comment]
![image](https://cloud.githubusercontent.com/assets/1519412/11368423/021d6290-92ba-11e5-86bd-7a9bb7a939e0.png)

I have the same

**Comment by rahilwazir** [comment]
Same here.

@tagliala What do you mean by

> can't help

**Comment by tagliala** [comment]
I can't help with this issue. I don't know this technology, I don't know how FA is used in those projects, there isn't a reproducible case

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues

> * Create an isolated and reproducible test case. Be sure the problem exists in Font Awesome's code with a reduced test case that should be included in each bug report.
* Include a live example. Make use of jsFiddle, jsBin, or Codepen to share your isolated test cases.
* Share as much information as possible. Include operating system and version, browser and version, version of Font Awesome, etc. where appropriate. Also include steps to reproduce the bug.

**Comment by RogueDGA** [comment]
Experiencing this Issue on my site now, the file is there for some reason it cant find woff2, everything else works and all the files are there

**Comment by VitorLuizC** [comment]
Woff2 must be declared as valid mimetype in your applications.
I've fixed it setting the code below in mine **web.config**
```xml
<system.webServer>
  <staticContent>
    <remove fileExtension=".woff2" />
    <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
  </staticContent>
</system.webServer>
```

**Comment by tagliala** [comment]
@VitorLuizC thanks

This case is also covered in our troubleshooting guide, but lacking of details didn't allow me to provide a solution

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

> I'm hosting fonts on my server and icons don't show up
> * You properly configured server's MIME types (Ref: #5559);

Closing here
