### ISSUE TITLE
Icon Request: fa-video-camera-slash

### ISSUE THREAD

**Issue by XAMelleOH** [FortAwesome/Font-Awesome#7567]
The same as fa-microphone and fa-microphone-slash it'll be good to have fa-video-camera-slash. It can be used when developing RTC web applications for making online audio/video calls.

**Comment by caduvieira** [comment]
dupe of #3765

**Comment by kisai** [comment]
#3765 is deleted or at least github returns 404 page. Or are you giving priority to #3691 ?

**Comment by tagliala** [comment]
??? contacting github

**Comment by tagliala** [comment]
page restored
