### ISSUE TITLE
icon (set) request: fa-report

### ISSUE THREAD

**Issue by paneum** [FortAwesome/Font-Awesome#7569]
I need a combination of some of the existing icons. 
I used several of them to create the examples for those i need. 
The base icon is the "fa-file" and i need it with some add-ons as you can see on the example. 

Although the two on the far right are from a different set, they are also needed. 
These icons are required on an intranet UI design. 

Let me know if you can create them or not. If it helps i can create a vector file (illustrator?) of the icons. 
Thanks in advance.

![request_icons_references](https://cloud.githubusercontent.com/assets/7547975/10170789/99fd3f58-66ce-11e5-907d-141fe387788e.png)

**Comment by TheChen5** [comment]
Please do not request a set of icons.
Also, a vector file is not needed. A simple image is fine.

**Comment by paneum** [comment]
Sorry, but it was said that, if related (first 6 are, 2 on the end aren't) we should pack them together.

**Comment by tagliala** [comment]
@paneum , you can request strictly related icons but I suggest you to take a look at #1181 . You will find a solution there.
