### ISSUE TITLE
icon request: specific icons for a soccer club website and intranet

### ISSUE THREAD

**Issue by paneum** [FortAwesome/Font-Awesome#7570]
Hello
I'm working on the redesign of an intranet frontend and the website of a soccer club. 

Since we're using bootstrap and your fantastic fontAwesome, we came across some specific elements that were not on your icons list. So we would need to have these "transformed" into your fontAwesome icons. Since they are a bit specific and i don't know the work involved by your part to create them, i've built what i need in vectors (i have an illustrator file with all of the 8). I can send you the file if you can create them and if it helps in the process. 

Please let me know :
Kind regards and thanks in advance. 

![screen shot 2015-09-29 at 17 32 39](https://cloud.githubusercontent.com/assets/7547975/10171115/4cd66590-66d0-11e5-8a28-7c6271cc39b7.png)

**Comment by TheChen5** [comment]
Whistle #984
Stopwatch #1340 
Mouse #2376 
Rest of icons please separate into separate requests.
Please do not request a set of icons. In this case, the requests are not exactly in one topic. For example, mouse and soccerfield are not really related. 
Also, Please :mag:before:heavy_plus_sign:

**Comment by paneum** [comment]
Thanks for the head's up. I really did a search, but on the icons database, not on the requests. 
Sorry for that.
I'll separate them accordingly.

**Comment by tagliala** [comment]
@paneum do not worry

Please also take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

If you need a comprehensive set of icons for a soccer-related web app, I should advise you to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here, feel free to open new individual requests
