### ISSUE TITLE
Icon request: fa-water-drop

### ISSUE THREAD

**Issue by vstokarev** [FortAwesome/Font-Awesome#7575]
Hi!

I think it would be great if you add a simple water drop icon to your awesome set. I was not able to find it either in current set or among other icons requests.

Thank you!

**Comment by TheChen5** [comment]
I have seen this issue before.
Highly recommend icon tint.
http://fortawesome.github.io/Font-Awesome/icon/tint/

**Comment by vstokarev** [comment]
Great, this is exactly what I was looking for! Sorry I could not find it before. Probably add aliases like 'drop' or 'water'?
Thank you.

**Comment by tagliala** [comment]
a drop and water(drop) filters should be available when @davegandy rebuild the docs
