### ISSUE TITLE
Icon Request: fa-finance-save (fa-finance-piggy)

### ISSUE THREAD

**Issue by ITPrism** [FortAwesome/Font-Awesome#7582]
Hi friends,
Thank you very much for the great icons. They are really useful for me.
I would like to ask you to include an icon that presents saving ( a small pig ).

![piggy](https://cloud.githubusercontent.com/assets/1272206/10215688/650e56b0-682c-11e5-9f32-4908c47988d3.png)

Thank you in advance,
Todor

P.S.
It could be part of set with [financial icons] (https://www.iconfinder.com/iconsets/finance-16) that we can use in crowdfunding applications or other financial applications.

**Comment by caduvieira** [comment]
dupe of #1413
+1 that request

**Comment by ElielBarone** [comment]
+1

**Comment by Webinsane** [comment]
+1

**Comment by fr1ts** [comment]
+1 :-)
