### ISSUE TITLE
Icon Request: fa-sail-boat

### ISSUE THREAD

**Issue by developius** [FortAwesome/Font-Awesome#7583]
Firstly, thank you for such an awesome job with FA!
Would it be possible to have a sailing boat like icon?
Something like this but `Awesome`!
![image](https://cloud.githubusercontent.com/assets/5836587/10220048/1640d426-683c-11e5-82b0-1e29501f7638.png)
Credit http://images.clipartpanda.com/sailboat-silhouette-sailboatlarge-500x500.jpg

**Comment by caduvieira** [comment]
dupe of #5079?

**Comment by developius** [comment]
Sorry, didn't see that one @caduvieira
