### ISSUE TITLE
Icon request: chart-candlestick

### ISSUE THREAD

**Issue by maurix70** [FortAwesome/Font-Awesome#7584]
It would be nice, add to other chart icons, a chart-candlestick icon.
![candlestick](https://cloud.githubusercontent.com/assets/14925724/10222774/0ed700f6-6856-11e5-8c21-8b2c7a063f1c.png)

**Comment by ITPrism** [comment]
+1

**Comment by WastedCharlie** [comment]
+1

**Comment by GinoStrada** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by stakemura** [comment]
+1

**Comment by diegopiriz** [comment]
+1

**Comment by cicciopaciuffo** [comment]
+1

**Comment by tdeenes** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by paddibr** [comment]
+1

**Comment by sensibleworld** [comment]
This was just added to version 6: https://fontawesome.com/v6.0/icons/chart-candlestick?s=solid
<img width="1043" alt="Screen Shot 2021-05-27 at 2 06 59 PM" src="https://user-images.githubusercontent.com/529604/119875494-ce74f080-bef4-11eb-886f-4b5825515e58.png">
