### ISSUE TITLE
Icon request: icon-sofa (icon-couch)

### ISSUE THREAD

**Issue by designbyadrian** [FortAwesome/Font-Awesome#759]
a small one-seat sofa, similar to http://www.madebysofa.com

:)

**Comment by Yaboe** [comment]
+1

**Comment by ssoulless** [comment]
any update on this one?

**Comment by twinshen** [comment]
+1 I think this icon is really needed.

It could be something like this: https://cdn2.iconfinder.com/data/icons/cosmo-furniture/40/bath-128.png

**Comment by laviku** [comment]
+1

**Comment by Tiffwillson** [comment]
+1

**Comment by pxzin** [comment]
+1

**Comment by McSullivan** [comment]
+1 to this one

**Comment by dimoned** [comment]
+ 1 to sofa or couch

**Comment by simnare** [comment]
+1

**Comment by rickhadfield83** [comment]
+1

**Comment by DavidH1904** [comment]
still nothing new?

**Comment by souzadevinicius** [comment]
+1

**Comment by mu5tach3** [comment]
What's about this one?

![g4144](https://cloud.githubusercontent.com/assets/1735007/10400057/d81ebe5c-6eb6-11e5-8a24-c17b8d0bc189.png)

(I vectorized  and changed "https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/256/sofa.png")

**Comment by superbarne** [comment]
+1 for @mu5tach3

**Comment by paishin** [comment]
+1

![image](https://cloud.githubusercontent.com/assets/410381/10429436/376e0c68-7101-11e5-9c3a-b93d380d2012.png)

**Comment by evinkuraga** [comment]
+1

**Comment by egorvinogradov** [comment]
+1

**Comment by redayoub** [comment]
+1

**Comment by neetocode** [comment]
+1

**Comment by johnnyshields** [comment]
A sofa icon is available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by bclair85** [comment]
+1  Need a sofa, couch.  Thanks

**Comment by xavigarcia** [comment]
+1, but I'd prefer a not so classical sofa.

**Comment by knightq** [comment]
+1

**Comment by icreatesolutions** [comment]
+1

**Comment by P1Rebo** [comment]
+1

**Comment by Nokhal** [comment]
+1

**Comment by andresilvasantos** [comment]
+1

**Comment by hananint** [comment]
+1

**Comment by simonalexandergilbert** [comment]
+1

**Comment by jvdmeij** [comment]
Not even in FA 5 😢

**Comment by BasicSoft** [comment]
+1

**Comment by jvdmeij** [comment]
If you guys are still interested, vote for the icon at https://fontawesome.com/community/leaderboard/new

**Comment by ssoulless** [comment]
I couldn't find it

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/couch?style=solid
https://fontawesome.com/icons/loveseat?style=solid
