### ISSUE TITLE
Icon request: icon-ice

### ISSUE THREAD

**Issue by iselena** [FortAwesome/Font-Awesome#7590]
Hi
i need a ice icon. I personal need it for a hotel website into service page for conditioned air.
Please check the attached.
Thank you
Isabella
![weather_icons_-_sn](https://cloud.githubusercontent.com/assets/14939421/10245090/b754ba08-6904-11e5-9991-b9eecaf7c9d4.jpg)

**Comment by caduvieira** [comment]
dupe of #1739 
+1 that one

**Comment by tagliala** [comment]
@caduvieira thanks as usual, really appreciate

if you could add "Please" before +1 that one would be better

**Comment by caduvieira** [comment]
OK

**Comment by tagliala** [comment]
thanks!
