### ISSUE TITLE
Icon request: icon-cloakroom

### ISSUE THREAD

**Issue by showplans** [FortAwesome/Font-Awesome#7591]
Hi,

I'm requesting a hanger symbol to represent cloakrooms. These are very useful within maps, especially venues, it's an icon that we would use on a regular basis for floorplan design.

The below image shows an example.

![coatcheck_6703](https://cloud.githubusercontent.com/assets/11443984/10245467/aacf6896-68ff-11e5-91ce-26b8ac242f4a.jpg)

Many thanks,

Showplans

**Comment by caduvieira** [comment]
dupe of #1659
+1 that request
