### ISSUE TITLE
Icon Request: icon-cars

### ISSUE THREAD

**Issue by vibaro** [FortAwesome/Font-Awesome#7596]
Hi,
I need one more transportation icon, one for multiple cars :)
![icon-cars](https://cloud.githubusercontent.com/assets/13410729/10255743/cbb48582-6922-11e5-9b42-e872657effa0.png)

**Comment by flaviohlm** [comment]
+1

**Comment by aethior** [comment]
Hi @vibaro,

This icon was added in v5.9.0.
Check https://fontawesome.com/icons/cars

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here.
