### ISSUE TITLE
Icon Request: Not replied

### ISSUE THREAD

**Issue by ttamas7** [FortAwesome/Font-Awesome#7601]
Hello Awesome team,
would it be possible to include a Not empty replied icon?
I mean if someone has not replied yet the icon would not be filled.
See our bitmap
![ico_notreplied](https://cloud.githubusercontent.com/assets/14953866/10263269/f90372ee-69e7-11e5-81c9-06d3c61d8a6d.png)

Thanks,
Teodor

**Comment by caduvieira** [comment]
dupe of #5724
Please +1 that one
