### ISSUE TITLE
Icon Request: fa-modx

### ISSUE THREAD

**Issue by mishantrop** [FortAwesome/Font-Awesome#7604]
It would be nice to have an icon for MODX. 
MODX is a free, open source content management system and web application framework.
![MODX Logo](http://cdn.modx.com/assets/i/logos/v5/modx-stacked-black-solid.png)
SVG: http://cdn.modx.com/assets/i/logos/v5/svgs/modx-stacked-black-solid.svg

**Comment by TheChen5** [comment]
Dupe #3455 
+1 that
Please :mag:before:heavy_plus_sign:
