### ISSUE TITLE
Icon Request: fa-spanner

### ISSUE THREAD

**Issue by pbowler** [FortAwesome/Font-Awesome#7605]

**Comment by caduvieira** [comment]
dupe of #6173 ?

**Comment by tagliala** [comment]
@pbowler could you please clarify this request?

http://fontawesome.io/icon/wrench/ ?

**Comment by aethior** [comment]
@tagliala I think you can close here and `spanner` alias for `fa-wrench` icon (check: #6173). 

> A wrench (or spanner outside of North America) is a tool used to provide grip and mechanical advantage in applying torque to turn objects—usually rotary fasteners, such as nuts and bolts—or keep them from turning.

(source: [en.wikipedia.org/wiki/Wrench](https://en.wikipedia.org/wiki/Wrench))
