### ISSUE TITLE
Icon request: Icon-engine

### ISSUE THREAD

**Issue by Fritch94** [FortAwesome/Font-Awesome#7612]
![image](https://cloud.githubusercontent.com/assets/14979784/10282879/f651fcd0-6b74-11e5-8f8a-64399c356fbd.png)

Please could we get a engine icon, i would like to use on a website I'm creating for a Mechanic as a page icon. and some links.

Thanks.

**Comment by tagliala** [comment]
duplicate of #4175, please +1 that request

closing here
