### ISSUE TITLE
issue for font-awesome.

### ISSUE THREAD

**Issue by jayabal90** [FortAwesome/Font-Awesome#7615]
fa-incoming-call,fa-outgoing-call,fa-missed-call  not working in our browser,pls help me sir.

**Comment by TheChen5** [comment]
Important thing to specify is browser name & version, and maybe OS name and version.

**Comment by TheChen5** [comment]
According to the Font Awesome icons page (http://fortawesome.github.io/Font-Awesome/icons/), the icons you specified are not Font Awesome icons.

**Comment by tagliala** [comment]
There is a request for the above icons #3701, please +1 that request

If you need this icon in a short while, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
