### ISSUE TITLE
Icon Request: fa-compare

### ISSUE THREAD

**Issue by arunprabhus** [FortAwesome/Font-Awesome#7616]
need a icon for compare 2 items

**Comment by tagliala** [comment]
any example?

**Comment by samhe** [comment]
+1

how about this ?

![Compare icon](http://www.bigschedules.com/core/images/compare.pn)

**Comment by mdolberg** [comment]
need one too! good

**Comment by Rodrigo54** [comment]
+1

**Comment by Bana0615** [comment]
+1

**Comment by devcorrelator** [comment]
+1

**Comment by Garric15** [comment]
+1

**Comment by mbigatti** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by z38** [comment]
+1

**Comment by WRedMedia** [comment]
+1

**Comment by soemo** [comment]
+1

**Comment by nqtuan164** [comment]
Good idea, I need it too... +1

**Comment by nikiwnichols** [comment]
+1

**Comment by liborbus** [comment]
+1

**Comment by salmanshariati** [comment]
+1

**Comment by KateDobrilko** [comment]
+1

**Comment by jiteshgolecha** [comment]
+1

**Comment by ramakrishnapittu** [comment]
+1

**Comment by tagliala** [comment]
I just want to point out that the example is not available anymore.

Please provide another example, because "compare" is an abstract concept and this does not meet our contributing guidelines

Do not +1 this request until a new example is available

Thanks

**Comment by matthew-b-payne** [comment]
Looking for compare as well.  Using fa-balance-scale as a fallback

**Comment by kbloor1** [comment]
+1

**Comment by photoman** [comment]
+100!  For my use, looking for something to compare two lists of information.. It could look similar to this  https://thenounproject.com/term/compare/71604/

**Comment by tagliala** [comment]
@photoman http://fontawesome.io/icon/exchange/ is very similar to your example

**Comment by ImtiazChowdhury** [comment]
+1

**Comment by azharmalik3** [comment]
+1

Sample compare icon:

![compare](https://user-images.githubusercontent.com/6176136/34939878-4c0092b0-fa0f-11e7-9f0a-3748c659a2ef.png)

**Comment by balajibathula99945** [comment]
+1

**Comment by ashwin-vine** [comment]
+1

**Comment by zeevkatz** [comment]
+1

**Comment by sulmanpucit** [comment]
+1

**Comment by seagullmouse** [comment]
+1

**Comment by Dawqss** [comment]
+1

**Comment by Janatbek** [comment]
any decisions yet?

**Comment by Janatbek** [comment]
https://fontawesome.com/icons/bezier-curve?style=solid

**Comment by devcorrelator** [comment]
I agree with @Janatbek

**Comment by Janatbek** [comment]
To use it you have to  upgrade to version [5.2.0](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers)

**Comment by nick-vfip** [comment]
I use `fa-clone` as the compare icon

**Comment by pierznj** [comment]
+1

**Comment by twwwt** [comment]
> +100! For my use, looking for something to compare two lists of information.. It could look similar to this https://thenounproject.com/term/compare/71604/

Another use case I would need such an icon is diffing two files. The icon proposed would fit, IMHO.

**Comment by gpapaiko** [comment]
+100 I agree this is a needed option, I ahd tried to stack two icons although they looked Ok they would not align to the rest of the   menu options.
 I as looking for something like this https://thenounproject.com/term/compare/62588/

![Screenshot 2020-09-22 185023](https://user-images.githubusercontent.com/21032399/93861877-90d81c00-fd04-11ea-8954-4469a62d8feb.png)
 Thanks.

**Comment by ggondim** [comment]
Couldn't it be achieved with a layer of [`arrow-left`](https://fontawesome.com/icons/arrow-left?style=solid) and [`arrow-right`](https://fontawesome.com/icons/arrow-right?style=solid) inside two [`file`](https://fontawesome.com/icons/file?style=regular)?

**Comment by gpapaiko** [comment]
Hi ,

No I had, had a look at that and it looks like this:
![image](https://user-images.githubusercontent.com/21032399/98455514-c73efd00-21c5-11eb-8850-7dc93a0a548a.png)

code is this , not to elegant:
`
<div class="fa-stack fa-2x " >
							  	
							  	<i class="fad fa-file-alt" data-fa-transform="up-4 right-12 " ></i>
							  	<i class="far fa-file-alt" data-fa-transform="left-12"  ></i>
							  	<i class="fas fa-arrow-alt-right"  data-fa-transform="shrink-6 left-20 down-3" style="color:black;"></i>
							  	<i class="fas fa-arrow-alt-left"  data-fa-transform="shrink-6 left-40 down-8" style="color:grey;" ></i>
							  </div>
`

**Comment by tagliala** [comment]
The original image example is not available anymore

I would like to improve the title of this request, but I do not recall the original intention of the OP

Can we assume that this is about a `file-compare` (as file with exchange arrows?)

**Comment by gpapaiko** [comment]
Hi,

The exhange-alt icon doe's not really do it.
need something like this:  https://thenounproject.com/term/compare/62588/

![image](https://user-images.githubusercontent.com/21032399/98496647-384de580-2296-11eb-95b7-8a8264ee1b7f.png)

I tried to create it by stacking icons but doe snot look as elegant.

This is what I created with stacking:
![image](https://user-images.githubusercontent.com/21032399/98496721-659a9380-2296-11eb-93b3-0f75c1e929e2.png)

code is this :

```
<div class="fa-stack fa-2x " >
   <i class="fad fa-file-alt" data-fa-transform="up-4 right-12 " ></i>
   <i class="far fa-file-alt" data-fa-transform="left-12"  ></i>
   <i class="fas fa-arrow-alt-right"  data-fa-transform="shrink-6 left-20 down-3" style="color:black;"></i>
   <i class="fas fa-arrow-alt-left"  data-fa-transform="shrink-6 left-40 down-8" style="color:grey;" ></i>
</div>
```

**Comment by ggondim** [comment]
And what about the arrows INSIDE the files? Using the blank file icon?

**Comment by gpapaiko** [comment]
Hi @ggondim ,

Tried that and it looks like this (ignore color);
![image](https://user-images.githubusercontent.com/21032399/98637297-5f7ee280-237c-11eb-8839-110a8a3d3658.png)

Not too elegant.
Code:
 ```
 <div class="fa-stack fa-2x " >
	<i class="far fa-file"  ></i>
	<i class="fas fa-arrow-alt-right"  data-fa-transform="shrink-8 left-16 up-1" style="color:black;"></i>
	<i class="fas fa-arrow-alt-left"  data-fa-transform="shrink-8 left-10 up-20" style="color:grey;" ></i>
</div>
```
This does not align the text correctly.

Also tried this:
![image](https://user-images.githubusercontent.com/21032399/98638463-b76a1900-237d-11eb-8b01-b61724bd1aff.png)

Code:
```
<div class="fa-stack fa-2x " >
	<i class="fad fa-file" data-fa-transform="up-4 right-20 " ></i>
	<i class="far fa-file"  ></i>
	<i class="fas fa-arrow-alt-right"  data-fa-transform="shrink-8 up-33 right-18" style="color:black;" ></i>
	<i class="fas fa-arrow-alt-left"  data-fa-transform="shrink-8 up-28 left-2" style="color:grey;"  ></i>
</div>
```

**Comment by ggondim** [comment]
I came to a solution (at least for myself) using a layer of `far-file`, `fas-file` and `fas-exchange`. 

![image](https://user-images.githubusercontent.com/2074685/98750770-88639f80-239d-11eb-9ecc-5baffc25451a.png)

The main problem is the top-most file icon need to be filled with a white background, but it was not possible. So I inverted the logic and placed a solid file icon above a regular one.

Then I used the `exchange` icon instead two arrows, white colored.

However, for small sizes it is near illegible, so in those cases I will use only `fas-exchange`.

Here's the code I used (it's for Vue library, but it's not hard to understand and convert it to vanilla/HTML FontAwesome):

```html
<font-awesome-layers class="fa-lg">
  <font-awesome-icon
    :icon="['far', 'file']"
    transform="up-5 right-4"
  />
  <font-awesome-icon
    :icon="['fas', 'file']"
  />
  <font-awesome-icon
    :icon="['fas', 'exchange']"
    transform="shrink-8 down-2"
    style="color: white"
  />
</font-awesome-layers>
```

**Comment by gpapaiko** [comment]
Hi @ggondim ,

The code is easy to convert, but that is not an issue.
That mean I need to use div tags, and svg with java to do that stacking and sizing which through out all other icon configurations and alignments.

If I did that then I would have to edit about another 10 web pages to get the fa icons to resize and align correctly.

At the moment I am just using the copy icon, might switch to the exchange icon, if I do go with the stacking method then I will need to edit a whole of other page, so i guess I need to make a choice.

But overall if there was a single compare icon that would be great, iI am sure others are looking for something similar.

Tried your suggestion and it looks like this.
![image](https://user-images.githubusercontent.com/21032399/98770098-8cdb9700-2435-11eb-82b2-048d528b9800.png)

For some unknown reason my far-file seems to be on top of the fas-file, even if I change the order the results is the same.
I used fa-inverse to change the color of the exchange arrows.
Code is this if anyone want to use it:
```
<div class="fa-stack fa-2x " >
  <i class="fas fa-file"  ></i>				  
  <i class="far fa-file" data-fa-transform="up-4 left-13 " ></i>
  <i class="fas fa-exchange  fa-inverse"  data-fa-transform="shrink-8 up-20 left-8"  ></i>
</div>
```

This is an alternative code that does not use the svg or java:
```
<span class="fa-stack fa-2x fa-fw" style="
                                    padding: 0;                                    
                                    height: 35px;
                                    margin-top: -10px;
                                    margin-bottom: 10px;
                                ">
  <i class="fad fa-file fa-fw" style="margin-left: 25px;margin-top: 7px;"></i>
  <i class="far fa-file fa-stack-1x fa-fw"></i>
  <i class="fas fa-arrow-alt-right fa-stack-1x fa-fw" style="color:black;font-size: .5em;margin-left: 17px;"></i>
  <i class="fas fa-arrow-alt-left fa-stack-1x fa-fw" style="color:grey;font-size: 0.5em;margin-top: 10px;margin-left: 17px;"></i>
</span>
```



Thanks for your suggestions.

**Comment by ggondim** [comment]
In your code you used `fad` instead `far`

**Comment by gpapaiko** [comment]
HI,

That is OK I did that used the fad so as it matches the rest of the icons, I am using a dual-tone  icons.
This approach is nor ideal but it is acceptable, and will do for a now.

**Comment by KTBsomen** [comment]
![image](https://user-images.githubusercontent.com/53004533/209376828-68149bd2-0bf6-4778-bf22-828ba0e49014.png)
How about this

**Comment by gpapaiko** [comment]
> ![image](https://user-images.githubusercontent.com/53004533/209376828-68149bd2-0bf6-4778-bf22-828ba0e49014.png) How about this
 Hi,

That is an alternative, did not really think of that one.
But that looks more like weight/scales.
Not ideal, but if there is nothing else it might have to do.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/icons/code-compare?f=classic&s=solid)

**Comment by fr3nch13** [comment]
Wow, this one had been open for a while. :-p
I didn't know it existed, but i like it!
