### ISSUE TITLE
Restore previous icon search

### ISSUE THREAD

**Issue by suseu** [FortAwesome/Font-Awesome#7617]
Algolia does not work. It says it can't connect to search API

**Comment by tagliala** [comment]
Could you please take a look now? It's ok for me

**Comment by suseu** [comment]
Now it works. Thanks you! :)

**Comment by tagliala** [comment]
@suseu you're welcome but I did nothing :)

It probably was a temporary failure

**Comment by suseu** [comment]
It's not working again. That's console's message:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://m19dxw5x0q-dsn.algolia.net/1/indexes/*/queries?x-algolia-api-key=c79b2e61519372a99fa5890db070064c&x-algolia-application-id=M19DXW5X0Q&x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.8.1. (Reason: CORS request failed).

r: Cannot connect to the AlgoliaSearch API. Send an email to support@algolia.com to report and resolve the issue. Application id was: M19DXW5X0Q

**Comment by tagliala** [comment]
I'm unable to replicate, tried
* https://fortawesome.github.io/Font-Awesome/icons/
* http://fortawesome.github.io/Font-Awesome/icons/
* http://fontawesome.io/icons/

btw Dave was informed of this failure

**Comment by suseu** [comment]
I think this may be proxy related issue.
9 paź 2015 12:37 PM "Geremia Taglialatela" <notifications@github.com>
napisał(a):

**Comment by aethior** [comment]
@tagliala I think you can close here.
