### ISSUE TITLE
Icon Request: icon-desk+lamp

### ISSUE THREAD

**Issue by om64** [FortAwesome/Font-Awesome#7618]
I'd like to have an icon representing a lamp on a desk. I'd like to use it for the Claroline Connect LMS (see: www.claroline.net). It's meant for the learner to go to his "space of activities".

![desk lamp](https://cloud.githubusercontent.com/assets/14308826/10306294/2c7b61fa-6c26-11e5-919f-8384048edad4.jpg)

Thanks a lot in advance.

**Comment by tagliala** [comment]
I think https://fontawesome.com/icons/lamp-desk?style=solid does the job (available in FA Pro) ref #8206
