### ISSUE TITLE
Icon request: icon-Adobe

### ISSUE THREAD

**Issue by cresspd** [FortAwesome/Font-Awesome#7621]
I plan to use this icon the same way that other Brand Icons within Font Awesome are used, to represent the brand. 

The big A by itself without the ADOBE text would be perfect. 
![adobe_standard_logo_rgb](https://cloud.githubusercontent.com/assets/14784031/10322450/c81a8f3a-6c4b-11e5-81dd-afab2bd46fb1.png)

**Comment by ptkdev** [comment]
+1

**Comment by talbs** [comment]
Released in version 5.6.0 - https://fontawesome.com/icons/adobe. 😄
