### ISSUE TITLE
Icon request: icon-tick, icon-cross

### ISSUE THREAD

**Issue by bjtaylor1** [FortAwesome/Font-Awesome#7624]
Would be nice to have a 'tick' icon, to represent an operation that succeeded, and a cross to represent an operation that didn't suceed.

Would be nice to be fairly sculpted/tapered, i.e. more like this:
<img width="40px" src="https://cloud.githubusercontent.com/assets/4470107/10335670/58e52b8a-6cea-11e5-8afd-60fc4c7be002.png"/>
than 'blocky', like this:
<img width="40px" src="https://cloud.githubusercontent.com/assets/4470107/10335719/b25ae63c-6cea-11e5-83e7-4eb18903d6a3.png"/>

**Comment by caduvieira** [comment]
http://fontawesome.io/icon/times/

and 

http://fontawesome.io/icon/check/

**Comment by bjtaylor1** [comment]
Excellent. Cheers :)

**Comment by SaifurRahmanMohsin** [comment]
Hmm. It’s still a blocky one. Never got fixed, eh?
