### ISSUE TITLE
Icon request: ms-office-365

### ISSUE THREAD

**Issue by moriartp** [FortAwesome/Font-Awesome#7626]
I see icons for specific ms office file types, but it would be helpful to have a general ms office 365 icon, as attached

![office-icon](https://cloud.githubusercontent.com/assets/13931458/10342729/7d2c21a8-6ce8-11e5-8b98-0052b48acbc3.png)

**Comment by tagliala** [comment]
duplicate of #1333 , please +1 that request

please also search before opening new requests: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

closing here
