### ISSUE TITLE
Icon request: adobe-creative-cloud

### ISSUE THREAD

**Issue by moriartp** [FortAwesome/Font-Awesome#7627]
icon resembling: 

<img width="64" alt="adobe_creative_cloud_logo" src="https://cloud.githubusercontent.com/assets/13931458/10342784/c5b1b7ee-6ce8-11e5-99b7-eb72d924432a.png">

**Comment by tagliala** [comment]
subset of #1970

**Comment by tagliala** [comment]
Sorry, closing this and labeling as cantfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150
