### ISSUE TITLE
Icon request: presentation-instructor

### ISSUE THREAD

**Issue by moriartp** [FortAwesome/Font-Awesome#7630]
icon for presentation/lecture/teacher/lecture

![user-presentation-chart-man-256](https://cloud.githubusercontent.com/assets/13931458/10342977/b2d0d870-6ce9-11e5-98aa-dd53700f172b.png)

![peper-presentation](https://cloud.githubusercontent.com/assets/13931458/10342981/b53ad00c-6ce9-11e5-9de8-d27a0c043a2e.png)

![presentation](https://cloud.githubusercontent.com/assets/13931458/10342987/bbb107b2-6ce9-11e5-998f-ad089dcd420d.png)

**Comment by tagliala** [comment]
this is a duplicate, could you please try the search feature having care of looking for synonyms too?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/person-chalkboard?s=solid&f=classic
