### ISSUE TITLE
Icon request: bell-curve

### ISSUE THREAD

**Issue by moriartp** [FortAwesome/Font-Awesome#7631]
![bell-curve-example](https://cloud.githubusercontent.com/assets/13931458/10343143/6f0f8630-6cea-11e5-950a-fa9428f58bb0.jpg)

**Comment by stevem** [comment]
Duplicate of https://github.com/FortAwesome/Font-Awesome/issues/4063

**Comment by tagliala** [comment]
@stevem thanks
