### ISSUE TITLE
Icon request: Pager

### ISSUE THREAD

**Issue by nanoxd** [FortAwesome/Font-Awesome#7636]
Thanks for the great icon set! I've enjoyed using them. Currently, I am using icons to illustrate the kind of contact type (home, office, mobile, and fax). We also have a pager field but were unable to find an icon for that. We were looking for something along the lines of the following:

![](https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/pager.png)

**Comment by aethior** [comment]
Hi @nanoxd,

This icon was added in v5.7.0.
Check https://fontawesome.com/icons/pager

Regards.

cc/ @tagliala
