### ISSUE TITLE
About adding animal icons

### ISSUE THREAD

**Issue by marsberrys** [FortAwesome/Font-Awesome#7637]
Will Awesome add some common animals in ?

**Comment by rockerest** [comment]
[dog](https://github.com/FortAwesome/Font-Awesome/issues/1317)
[horse](https://github.com/FortAwesome/Font-Awesome/issues/2049)
[fish](https://github.com/FortAwesome/Font-Awesome/issues/2722)
[squirrel](https://github.com/FortAwesome/Font-Awesome/issues/5491)
[shrimp](https://github.com/FortAwesome/Font-Awesome/issues/5764)(!)
[rabbit/turtle](https://github.com/FortAwesome/Font-Awesome/issues/2453)
[cat](https://github.com/FortAwesome/Font-Awesome/issues/2226)

**Comment by tagliala** [comment]
@rockerest thanks!

Closing here
