### ISSUE TITLE
Icon Request: fa-palm-tree

### ISSUE THREAD

**Issue by commandantp** [FortAwesome/Font-Awesome#7640]
If we could have a little plam tree that would be perfect! 

Thanks for the great work!

**Comment by mfrntic** [comment]
+1

**Comment by EppO** [comment]
dup of #3786

**Comment by tagliala** [comment]
@EppO thanks

Please +1 #3786

**Comment by tagliala** [comment]
Reopening here, because this is a request only for a palm tree, without an island

**Comment by 301gene** [comment]
+1

**Comment by sensibleworld** [comment]
We have a couple options for this now: 
https://fontawesome.com/icons/tree-palm?style=solid and 
https://fontawesome.com/icons/island-tropical?style=solid
