### ISSUE TITLE
icon request: Thai Baht

### ISSUE THREAD

**Issue by davidapple** [FortAwesome/Font-Awesome#7641]
Request for the Thai Baht currency symbol. It looks a lot like the Bitcoin one so should be very quick to develop.

**Comment by rockerest** [comment]
Here is the Baht symbol from Wikipedia: ฿
It's unicode codepoint [0E3F](U+0E3F).
Here's an image of it from a DuckDuckGo search:  

![baht](http://www.decodeunicode.org/en/u%2B0e3f/data/glyph/196x196/0E3F.gif)

(As an aside to @davidapple, can you just use the unicode character? I know sometimes It's convenient to have the icon, but this seems like something that can be solved right now for your particular - whatever it may be - use case)

**Comment by TheChen5** [comment]
Dupe #1431
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by davidapple** [comment]
Thanks, @rockerest I didn't realize there was a unicode character.
