### ISSUE TITLE
Icon request: icon-file-user

### ISSUE THREAD

**Issue by hundra** [FortAwesome/Font-Awesome#7645]
Would be awsome with an file icon with a user. 

Could be used for:
- User files
- Cv / Personal letter
- Applications
- My profile page

![icon-user](https://cloud.githubusercontent.com/assets/127680/10388430/2ddb9592-6e6a-11e5-80c6-1f848a3d1beb.png)

**Comment by caduvieira** [comment]
dupe of https://github.com/FortAwesome/Font-Awesome/issues/3533 ?

**Comment by tagliala** [comment]
Same use case, similar design.

IMHO it is a duplicate,

please +1 #3533 

closing here
