### ISSUE TITLE
Icon Request: fa-workflow

### ISSUE THREAD

**Issue by thiazzz** [FortAwesome/Font-Awesome#7646]
Useful for indicating a workflow in a website or app

**Comment by caduvieira** [comment]
Dupe of #3576 ?

**Comment by thiazzz** [comment]
I was thinking of something like this:
http://www.cdevworkflow.com/wp-content/uploads/2011/06/workflow-1.png?d7ea3f

Or
https://mglearns.wikispaces.com/file/view/workflow.jpg/423368716/workflow.jpg

**Comment by tagliala** [comment]
duplicate of #3576, please +1 that request and post there your examples

please also consider using sitemap: http://fortawesome.github.io/Font-Awesome/icon/sitemap/
