### ISSUE TITLE
Icon request: icon-airbnb

### ISSUE THREAD

**Issue by perticaroli-c** [FortAwesome/Font-Awesome#7650]
Airbnb is a reliable portal where people can publish , discover, and book unique accommodations around the world
![air-bnb-logo](https://cloud.githubusercontent.com/assets/7511172/10400715/9f336fee-6eba-11e5-93ed-06bcf9de24a1.png)

**Comment by perticaroli-c** [comment]
Airbnb is a reliable portal where people can publish , discover, and book unique accommodations around the world

**Comment by altsalt** [comment]
+1

**Comment by mondo989** [comment]
+ 1

**Comment by TJProgrammer** [comment]
+1

**Comment by vulcan25** [comment]
Would be cool to have this one added :+1:

**Comment by akerd** [comment]
+1 it would be helpful to have this one

**Comment by shoichiaizawa** [comment]
+1 I was also looking for fa-airbnb 🔍

**Comment by maxime-kouemo** [comment]
+1. Finally? Was it added?

**Comment by mactedder** [comment]
+1  Big player in the market, should definitely be added.

**Comment by nkndy** [comment]
+1

**Comment by DamianFox** [comment]
+1

**Comment by boryn** [comment]
+1, as well for booking.com :) 
Thank you community!

**Comment by peterppm** [comment]
+ 1

**Comment by kagansari** [comment]
+1

**Comment by aviadhahami** [comment]
Well, @tagliala[ just closed the PR for that](https://github.com/FortAwesome/Font-Awesome/pull/8771#event-961046696) (without any comment. thanks), so I guess we wont see this coming soon

**Comment by Jbithell** [comment]
+1

**Comment by parce141** [comment]
👍

**Comment by ameliafly** [comment]
+1

**Comment by acidtone** [comment]
+1

**Comment by mircsicz** [comment]
+1

**Comment by KevinMalo** [comment]
+1 Airbnb is very important.

Thanks

**Comment by tammy-txt** [comment]
So how's going with airbnb icon...

**Comment by levbian** [comment]
please. +1 for airbnb. thank you.

**Comment by hugo-elliott** [comment]
+1

**Comment by klajmajk** [comment]
+1

**Comment by markconcept** [comment]
+1

**Comment by UNIT-CEO** [comment]
+1

**Comment by marikoo** [comment]
+1

**Comment by SeanFmcdonnell** [comment]
👍 +1 please and thank you.

**Comment by andreataglia** [comment]
+1

**Comment by ericvt** [comment]
Indeed that one would be super useful and used

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/airbnb

Thanks for the patience and for continuing to vote this up! :smile:
