### ISSUE TITLE
Icon request: Full screen / Expand

### ISSUE THREAD

**Issue by ThomasBird1984** [FortAwesome/Font-Awesome#7651]
<img width="36" alt="screen shot 2015-10-09 at 1 43 18 pm" src="https://cloud.githubusercontent.com/assets/1638025/10401276/ed039994-6e8b-11e5-8cc4-5e1b4acd5fc6.png">

Fullscreen icon or expand icon

**Comment by caduvieira** [comment]
http://fontawesome.io/icon/arrows-alt/ ?

related https://github.com/FortAwesome/Font-Awesome/issues/1468

**Comment by ThomasBird1984** [comment]
@caduvieira I feel like #1468 is a bit different than what I am looking for so I would like to keep this open and continue this request. They are similar but I think this icon would be better suited for screens as it is more expressive of a screen than just expanding any generic item.

**Comment by tagliala** [comment]
duplicate of #4576?

**Comment by tagliala** [comment]
no feedback, closing here
