### ISSUE TITLE
Icon Request: fa-american-football

### ISSUE THREAD

**Issue by dashatitlebaum** [FortAwesome/Font-Awesome#7652]
Icon request: icon-american-football
Great for american football season from September to February.

![3521aa81013e5d53cc792a98673c5587](https://cloud.githubusercontent.com/assets/3833331/10405083/50e7e0fe-6e9c-11e5-932e-8f8556d01e2a.jpg)
![1368296348666168335american-football-ball-icon-hi](https://cloud.githubusercontent.com/assets/3833331/10405084/50e7fe04-6e9c-11e5-9406-aaedb430c623.png)

**Comment by TheChen5** [comment]
Dupe #4602
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by kevbodavidson** [comment]
+1
