### ISSUE TITLE
Icon request: fa-signal-level-X

### ISSUE THREAD

**Issue by ntvsx193** [FortAwesome/Font-Awesome#7658]
![Low signal](http://monosnap.zanozahost.ru/2015-10-12_01_3212d8.png) ![Half signal](http://monosnap.zanozahost.ru/2015-10-12_01_cdf556.png) ![Full signal](http://monosnap.zanozahost.ru/2015-10-12_01_c821d8.png)

**Comment by tagliala** [comment]
duplicate of #1870 , please +1 that request

closing here

**Comment by DanielGrozdev** [comment]
+1
That would make a lot of developers happy ;]
