### ISSUE TITLE
fa-medium with new Medium logo

### ISSUE THREAD

**Issue by taxigy** [FortAwesome/Font-Awesome#7661]
Medium [has introduced the new logo](https://medium.com/the-story/the-story-behind-medium-s-new-logo-4cd3e143dfcf) so I believe everybody desperately needs one to get updated in Font Awesome.

**Comment by tagliala** [comment]
Thanks for reporting this. Labeling as bug and adding to 4.4.1 milestone.

I'm a little bit concerned because they haven't a single color representation of their logo

**Comment by taxigy** [comment]
I believe [one of these](https://cdn-images-1.medium.com/max/800/1*vDePQoiXJtOL1bbCAX5mZA.png) should suffice, for example, the fourth one. Or take a look at the seventh, green one. It doesn't look easily recognizable right now but I think it will do in few months.

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

Hate it when there's no single color version. Did the best I could, and would LOVE to replace this with something official.

I miss the old logo.
