### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by enzozhong** [FortAwesome/Font-Awesome#7666]
DHL,FedEx,TNT,UPS,WETERN UNION,MSN

**Comment by enzozhong** [comment]
>###### dhl
![dhl](https://cloud.githubusercontent.com/assets/993544/10448437/770375a2-71bf-11e5-848d-f1614a40436d.png)

**Comment by caduvieira** [comment]
related #1502

**Comment by tagliala** [comment]
I can consider this a subset of #1502.

Even if this request should be better because it is a single brand, I still think that #1502 makes sense (few closely related brands). 

So... closing here, please +1 #1502
