### ISSUE TITLE
Icon Request: fa-send-box

### ISSUE THREAD

**Issue by tatof** [FortAwesome/Font-Awesome#7667]
A simple carton box with open flaps for a "send pakkage" symbol.

**Comment by tagliala** [comment]
duplicate of #908 ?

**Comment by tatof** [comment]
Jup and I mis an shopping basket icon. But I found out how to add icons to
awesome font so don't really need it anymore.

Thank you
Op 31 okt. 2015 21:35 schreef "Geremia Taglialatela" <
notifications@github.com>:

**Comment by tagliala** [comment]
Please +1 #908 and #962 

Closing here
