### ISSUE TITLE
Icon request: sports stuff

### ISSUE THREAD

**Issue by cliffordp** [FortAwesome/Font-Awesome#767]
I think these would be some good icons to have:
football
baseball
soccer ball
field goal posts
football field
soccer field
basketball hoop
disc golf hoop
golf club
golf flag/pin/hole
etc.

There's a football/rugby ball and some other good icons at http://www.brankic1979.com/icons/

**Comment by frague59** [comment]
+1

**Comment by nce** [comment]
+1 ski snowboard mountainbike

**Comment by AhmedOsama** [comment]
+1 for all sports

**Comment by asorokoumov** [comment]
+1

**Comment by Elmister** [comment]
+1 (soccer mainly :) ) but :+1:  for all sports :D

**Comment by vishak-incture** [comment]
+1 for all sports

**Comment by garak** [comment]
:+1:

**Comment by sullrich84** [comment]
+1 for sports :)

**Comment by guilhermegeek** [comment]
+1

**Comment by kabus202** [comment]
+3

**Comment by jamesadevine** [comment]
I've compiled some different sports icons and turned it into a font as i couldn't find the ones i need from FA! :( 

https://github.com/jamesadevine/sportsfont

**Comment by jamesadevine** [comment]
Hi all,

Sorry to repost this message! I deleted it last time so I could add a couple of things.

I made a font with a whole host of sports icons in it:

https://github.com/jamesadevine/sportsfont

Should tide you over!

**Comment by Abundnce10** [comment]
Thanks, @jamesadevine!!

**Comment by tagliala** [comment]
@jamesadevine thanks for sharing!

**Comment by overforkover77** [comment]
+1

**Comment by butterkaffee** [comment]
+1

**Comment by lamarant** [comment]
+1 (golf especially)

**Comment by kss160992** [comment]
Hi Guys any updates on this?

**Comment by Fatbat** [comment]
+1

**Comment by themsaid** [comment]
+++1

**Comment by patrickmcd** [comment]
+1

**Comment by austinarchibald** [comment]
:+1:

**Comment by butterkaffee** [comment]
+1 jiu-jitsu blackbelt

**Comment by roblawford** [comment]
+1

**Comment by leoguillen** [comment]
+1

**Comment by MariaNicolosi** [comment]
+1

**Comment by marher86** [comment]
+1

**Comment by RinghoferJS** [comment]
+1

**Comment by ClifG** [comment]
+1

**Comment by Emadello** [comment]
+1

**Comment by martolini** [comment]
+1

**Comment by PIPONCHOV** [comment]
+1

**Comment by danbergman** [comment]
+1

**Comment by JaoNoctus** [comment]
+1

**Comment by JaoNoctus** [comment]
- Skateboard

**Comment by pauloschiavon** [comment]
+1 Tennis Ball

**Comment by ses** [comment]
+1

**Comment by Wineliva** [comment]
+1

**Comment by geethpw** [comment]
+1

**Comment by jeraldpunx** [comment]
+1

**Comment by goyote** [comment]
+1

**Comment by duribreux** [comment]
+1

**Comment by stefanpl** [comment]
+1

**Comment by oz6269** [comment]
+1

**Comment by Rolarne** [comment]
+1

**Comment by fheider** [comment]
:+1:

**Comment by tagliala** [comment]
Hi,

I should have done this before. This is my entire fault, I'm sorry.

This request doesn't meet our [Contributing Guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

> Please do not request comprehensive sets of icons related to a very specific field.

Also, there are duplicates of an older request, #714, which is planned for 5.0.0 (9 new icons).
It *should* include: basketball, football, rugby, baseball, tennis, volleyball. water polo, hockey, handball. Please note that I don't know if Dave will implement all of them

If you need all kind of sport and multiple icons for the same sport, please consider a [custom version](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome):

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (**e.g., a set of weather icons to build a forecast application**) our suggestion is to customize Font Awesome.

If you need more sports, please open new individual requests having care of searching before

Golf: #5348
Swimming: #5771 
Running: #1156
(and there should be others)

Please also consider to use @jamesadevine's solution: https://github.com/jamesadevine/sportsfont

Closing here

**Comment by Henry-Cullen** [comment]
after 3 years?

**Comment by Fatbat** [comment]
LoL. Wouldn't want to have a comprehensive set of icons for one of mankind's most popular pastimes, sports, noooo.

**Comment by amosvanhorn** [comment]
+1 for golf icon

**Comment by Cengiz25** [comment]
+1 for golf icon

**Comment by wermetal** [comment]
+1

**Comment by carlosatta** [comment]
+1

**Comment by tagliala** [comment]
locking here 🔒 

https://github.com/FortAwesome/Font-Awesome/issues/767#issuecomment-245315079
