### ISSUE TITLE
Icon request: icon-school

### ISSUE THREAD

**Issue by Yannick86** [FortAwesome/Font-Awesome#7671]
Hey there,

I was hoping it would be possible to add an icon which resembles a school.
An example would be;

http://homecut.info/wp-content/uploads/2015/06/school-building-icon-jti7shuuw.png

But I'm sure you can make it much better :)

Kind regards,

Yannick

**Comment by jeremieweldin** [comment]
+1

**Comment by Yannick86** [comment]
Is this planned any time soon by any chance?

**Comment by rpetitto** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by Rachine** [comment]
+1

**Comment by urielzen** [comment]
+1

**Comment by gaaamii** [comment]
+1

**Comment by jbennett999** [comment]
+1

**Comment by sensibleworld** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Schoolhouse Icon](https://trello.com/c/gG17ZDcA/17-schoolhouse-icon)

**Comment by jeremieweldin** [comment]
Why was this closed? Is it completed or not going to be completed?

**Comment by sensibleworld** [comment]
Snuck this icon in before school's out for summer: https://fontawesome.com/icons/school?style=solid
