### ISSUE TITLE
Icon Request: fa-map-marker-sharp

### ISSUE THREAD

**Issue by pieterjandesmedt** [FortAwesome/Font-Awesome#7672]
First of all, thank you for this great set! I use it in a lot of projects.

The current map marker icon has a **rounded point**, which gives an impression of fuzziness and imprecision.
![fuzzy](https://cloud.githubusercontent.com/assets/9006284/10483970/95fde122-7282-11e5-9e17-c8636e1aa17f.png)

It would be good to have an alternative with a **'precise', sharp point**, like these:
![sharp](http://icons.iconarchive.com/icons/paomedia/small-n-flat/256/map-marker-icon.png)
![sharp](https://www.briarcliff.edu/media/394037/marker.png)

Thanks for considering!

**Comment by tagliala** [comment]
It makes sense. Adding this to milestone 5.0.0, so Dave will eventually take a look

**Comment by tagliala** [comment]
Seems fixed in FA 5.0.0
https://jsfiddle.net/tagliala/yxqqchjs/2/
