### ISSUE TITLE
Icon Request: fa-clover

### ISSUE THREAD

**Issue by DMONAHAN** [FortAwesome/Font-Awesome#7675]
Hello, 
I need an icon that represent my client branding and could benefit for others who looking for a clover feel. 
See artwork: http://pasteboard.co/1n9KV4mQ.svg+xml

I want to use it on a website using font awesome icons as you can see here that I would like to replace the leaf with the clover on the homepage. www.cleartouchmassage.com/newsite/

I hope you can add it - Many many thanks :)

**Comment by TheChen5** [comment]
Dupe [#1593](https://github.com/FortAwesome/Font-Awesome/issues/1593)
+1 that
Please :mag:before:heavy_plus_sign:
