### ISSUE TITLE
Icon request: google plus update

### ISSUE THREAD

**Issue by kacyb6** [FortAwesome/Font-Awesome#7677]
when can we expect a google plus icon update?

**Comment by abelini** [comment]
+1

**Comment by TheChen5** [comment]
Dupe #7357 
Do *not* +1 that (you can't do it anyways)
Please :mag:before:heavy_plus_sign:

**Comment by theoellis** [comment]
+1

**Comment by tagliala** [comment]
Please refer to #7357
