### ISSUE TITLE
Icon request: icon-syringe

### ISSUE THREAD

**Issue by kacper81** [FortAwesome/Font-Awesome#7684]
![syringe](https://cloud.githubusercontent.com/assets/10129418/10513879/cd4c0082-734a-11e5-8c4c-34be6f51ab5a.png)

We need this icon for Our medical system.
Thanks for add.

**Comment by TheChen5** [comment]
Dupe #1779 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks, as always

closing here
