### ISSUE TITLE
Icon Request: fa-money-bag

### ISSUE THREAD

**Issue by lossantis** [FortAwesome/Font-Awesome#7686]
Hello.  

What do they think about moneybag to representate 'business' and 'finances'?

Nice job ;) :)

![cell-4-2-480 1](https://cloud.githubusercontent.com/assets/10433344/10520837/dfd26910-7342-11e5-8cea-99a14dae6182.png)

![28294506-dollar-money-icon-with-bag-on-white-background-vector-illustration--stock-vector 1](https://cloud.githubusercontent.com/assets/10433344/10520880/21ba17ce-7343-11e5-8eb9-f50d4f69b36d.jpg)

**Comment by TheChen5** [comment]
Dupe #1414 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by lossantis** [comment]
Sorry about that. I'm newbie :smile:

**Comment by TheChen5** [comment]
It's okay. I have made somewhat of this kind of mistake before.
I see that you have +1'd that request. Can you please close this one?

**Comment by lossantis** [comment]
Ok. Thanks!
