### ISSUE TITLE
Icon request: icon-patent (certificate vertical)

### ISSUE THREAD

**Issue by anahitas72** [FortAwesome/Font-Awesome#7687]
It would be great if you could create an icon for a patent, with the stamp and all. I work at the USPTO and we use font-awesome throughout our application but we have no way of representing a patent icon. 

Thank you very much. Examples below.

![office-45-512](https://cloud.githubusercontent.com/assets/1155572/10522863/7ea36196-7345-11e5-94c2-6b4c403ea073.png)
![pic-patent-certificate](https://cloud.githubusercontent.com/assets/1155572/10522947/dbb31fd4-7345-11e5-8ac4-adad9204e95a.jpg)

**Comment by tagliala** [comment]
duplicate of #4420 , please +1 that request

closing here

**Comment by anahitas72** [comment]
This is different from a patent icon. 



Thank you,

Anahita Shafa

iPhone. iTypos. iApologize.

**Comment by tagliala** [comment]
I can reopen this as certificate vertical

**Comment by anahitas72** [comment]
Thank you. +1

**Comment by schoutenzekerheid** [comment]
Could also be used as another official document, like an insurance policy. +1

**Comment by wagneramaral** [comment]
+1

**Comment by iraklisg** [comment]
+1

**Comment by ulger** [comment]
I join the request for a vertical certificate.

**Comment by tagliala** [comment]
I think this is available in FA Pro as [fa-file-certificate](https://fontawesome.com/icons/file-certificate?style=solid)

**Comment by aethior** [comment]
> I think this is available in FA Pro as [fa-file-certificate](https://fontawesome.com/icons/file-certificate?style=solid)

I think so.
