### ISSUE TITLE
Icon-request: currency-uah

### ISSUE THREAD

**Issue by Vitalii2103** [FortAwesome/Font-Awesome#7690]
I will wery thankful if you could create UAH (hryvnia) currency icon.

![Hryvnia icon](http://www.myiconfinder.com/uploads/iconsets/128-128-d8462f7f1edd49cf77242377f1f82595.png)

**Comment by TheChen5** [comment]
Dupe #1451
Please +1 that

**Comment by tagliala** [comment]
closing here
