### ISSUE TITLE
Icon Request: fa-disabled

### ISSUE THREAD

**Issue by kestelle** [FortAwesome/Font-Awesome#7691]
![disabled](https://cloud.githubusercontent.com/assets/5758182/10549819/6bdb9692-7411-11e5-9c59-755dae6e1130.png)

A disabled icon would be great. You can use fa-times to convey the same idea but I think one of these icons would be more clear.

**Comment by TheChen5** [comment]
That icon inside it looks like icon-ban (http://fortawesome.github.io/Font-Awesome/icon/ban/).
You could stack icon-ban & icon-circle (see http://fortawesome.github.io/Font-Awesome/examples/#stacked).

**Comment by kestelle** [comment]
Thanks, I missed that.

**Comment by markkolich** [comment]
In case anyone else finds this, the FA magic would be:

```html
<span class="fa-stack">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-ban fa-stack-1x fa-inverse"></i>
</span>
```

Which results in:

![image](https://cloud.githubusercontent.com/assets/1202420/16178959/2163704a-360c-11e6-9cc5-62a7b203e116.png)
