### ISSUE TITLE
Icon Request: fa-basketball

### ISSUE THREAD

**Issue by adamwedlake** [FortAwesome/Font-Awesome#7695]
Hey there - looking to see if a basketball icon could be added to your collection.  I plan to use it to on a new website I am building.

Looking forward to seeing it added! 

Thanks!

Adam

![image](https://cloud.githubusercontent.com/assets/15165659/10556034/224b7686-743f-11e5-84b7-b0e0ffd35d69.png)

![image](https://cloud.githubusercontent.com/assets/15165659/10556036/34705034-743f-11e5-8014-85963cb26dab.png)

![image](https://cloud.githubusercontent.com/assets/15165659/10556038/3c77f6b0-743f-11e5-9019-47f46d86380f.png)

![image](https://cloud.githubusercontent.com/assets/15165659/10556039/4caff1cc-743f-11e5-917e-ec8a5fd5af0b.png)

**Comment by aethior** [comment]
Hi @adamwedlake, maybe you can use `fa-dribbble` icon: http://fontawesome.io/icon/dribbble/

**Comment by adamwedlake** [comment]
Wow - that's great!  I was searching for basketball, hoop, ball, etc references but not that one!  MANY THANKS!!!
