### ISSUE TITLE
Charset not set in font-awesome.scss

### ISSUE THREAD

**Issue by asambeka** [FortAwesome/Font-Awesome#7696]
Charset (@charset "UTF-8";)  is missing in the font-awesome.scss. I faced issue while working with ionic and fontawasome on Ubuntu 14. Bower install followed by ionic setup sass generates files with unreadable characters. See Stackoverflow [issue](http://stackoverflow.com/questions/27901023/sass-compass-font-awesome-issues-displaying-odd-glyphs-instead-of-icons) for more details.

Adding @charset "UTF-8"; to the top of the font-awesome.scss resolves the issue.

**Comment by gregbown** [comment]
When compiling scss with gulp-sass AND outputStyle:'compressed' flag the compiler will not handle the characters properly.
To correct it add the gulp-sass-unicode plugin and the required method to your gulp file and the output is correct and the font is awesome again!

**Comment by asambeka** [comment]
Thanks!
