### ISSUE TITLE
FA 4.4 TTF doesn't embed in Powerpoint 2013 on Windows

### ISSUE THREAD

**Issue by slt-uxd** [FortAwesome/Font-Awesome#7697]
Just FYI in case anyone is hoping to use FA in PPT on windows, and export to PDF hoping to embed the fonts. It won't embed.

 Also, some glyphs won't translate over between PPT windows and mac (see https://github.com/FortAwesome/Font-Awesome/issues/3567).

I really hope these two issues will be fixed as FA has been great - but now I'm having to look for another icon font without these issues.

**Comment by tagliala** [comment]
Please use #3567

Closing here as a duplicate
