### ISSUE TITLE
Icon request: icon-pixie

### ISSUE THREAD

**Issue by ianmennie** [FortAwesome/Font-Awesome#7698]
Hi there

Pixie is the fastest growing online community marketplace for people to explore, discover and experience communities and independent businesses. https://www.pixieme.org/

I’d use the icon to sit with other icons at the bottom of a website. Like this: http://themes.cubalicious.net/morpheus/demo2/

Would be great to have the icon added to the collection.

(The pixie icon may not scale down well. The 'P' icon may therefore be more suitable.)

![pixielogo_pixie](https://cloud.githubusercontent.com/assets/15170999/10558938/5e2b3e88-74db-11e5-877e-9bf533f6bbf8.png)
![pixielogo_p](https://cloud.githubusercontent.com/assets/15170999/10558941/6a4c54a4-74db-11e5-9bde-f4d2b547c5fb.png)

**Comment by aethior** [comment]
`pixieme.org` is currently a parked domain.

cc/ @tagliala
