### ISSUE TITLE
Icon Request: sort by first character

### ISSUE THREAD

**Issue by Bill168** [FortAwesome/Font-Awesome#7705]
Hello,we like awesome fonts very much, but we need one more icon, names sorted by first character in the contacts list. Icon like this:
![sort](https://cloud.githubusercontent.com/assets/15178068/10562615/a473f382-7597-11e5-8387-15a1574b44dd.png)

**Comment by Bill168** [comment]
Will you help us? thanks!

**Comment by Googlecloud12** [comment]
+1

**Comment by aethior** [comment]
Hi @Bill168, maybe you want this icon: http://fortawesome.github.io/Font-Awesome/icon/sort-alpha-asc/

**Comment by tagliala** [comment]
closing here

thanks @aethior
