### ISSUE TITLE
Icon Request: fa-lacrosse

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#7714]
Icon request: icon-name (e.g., Icon request: icon-car
# ICON REQUEST :

icon-lacrosse 
I am creating a lacrosse website called iLax and I would like to use a Font Awesome style icons to use. It would look like a black and white lacrosse stick with grey mesh. Here is a photo:
![full_19528_front](https://cloud.githubusercontent.com/assets/15062261/10573629/11b83f3e-7651-11e5-9f22-673440dbffeb.jpg)

**Comment by Animalejourbano** [comment]
Something like this would be enough for me.
![fa-lacrosse-01](https://user-images.githubusercontent.com/5756418/35739465-71dea922-0810-11e8-9e0e-df4e1588edcd.jpg)

**Comment by adamdjbrett** [comment]
Personally I a font awesome lacrosse stick option would be incredibly helpful for me and many folks I work with. It would be great if there were 2 options. 1. a traditional wooden lacrosse stick and 2. an font awesome version of the official lacrosse emoji.

**Comment by jds580s** [comment]
I would like to add support for this icon as well to help build out the sports selection.

**Comment by adamdjbrett** [comment]
> I would like to add support for this icon as well to help build out the sports selection.

agreed. It would be super helpful

**Comment by aethior** [comment]
Hi @ghost,

[fa-lacrosse-stick](https://fontawesome.com/icons/lacrosse-stick) and [lacrosse-stick-ball](https://fontawesome.com/icons/lacrosse-stick-ball) icons have been added in v6.0.0-BETA1.

Regards.

cc/ @tagliala
