### ISSUE TITLE
Icon request: fa-disco

### ISSUE THREAD

**Issue by RichardSimo** [FortAwesome/Font-Awesome#7715]
Hello.
I was wondering if you could create a disco ball icon. I have an app themed in clubs, disco and dancing. It will be a tab header text.
Something like this: http://image.shutterstock.com/display_pic_with_logo/66274/66274,1251858526,4/stock-photo-disco-ball-isolated-on-white-background-36328126.jpg
Thanks in advance.

Please help quite urgent

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/7717#issuecomment-149893590
