### ISSUE TITLE
Bower and grunt for font-awesome

### ISSUE THREAD

**Issue by furyscript** [FortAwesome/Font-Awesome#7716]
I've load font-awesome in vendor folder with bower.

```
-src
-vendor
-assets
-build
```

I build my project into build folder with Grunt.
The problem is that the vendor file isn't touch so by default when bower download font-awesome, the path of it's font is `"../fonts"` and I need to change it manually with `"/assets"` (I build the font-awesome font into assets)
My question is: How can I download correctly font-awesome??
If bower not work I'm forced to move font-awesome folder into assets so remove the bower package manager for this.. But I prefer not..

**Comment by tagliala** [comment]
I suppose you need some overrides, we are following bower specs:

https://github.com/bower/spec/blob/master/json.md

* Do not include assets files like images, fonts, audio, or video

**Comment by furyscript** [comment]
I think not...
When I build projects, I copy fontawesome's font into assets, so I need to change manually the default path of fontawesome's css..
How can I pass `path` during download with bower?

**Comment by ag3ng** [comment]
Hi All,
I just want to share what I have done before when facing problem in deploy using JHipster and some module need font-awesome.  During grunt process, configuration under index.html to load font-awesome.css are gone. so what I did is:
bower install --save font-awesome
(--save is to generate automatically configuration is used by font-awesome working fine)
go to bower.json and do some modification like below:
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    },
	"font-awesome": {
	  "main": [
		"css/font-awesome.css"
	  ]
	}
  }

After that run Grunt and working like what I want.

**Comment by tagliala** [comment]
I'm searching for old issues about bower.

We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
