### ISSUE TITLE
Icon Request: icon-panorama (360 rotation)

### ISSUE THREAD

**Issue by AshleyWright** [FortAwesome/Font-Awesome#772]
To indicate a panoramic image

**Comment by mpryc** [comment]
Hi,

I'd like to see icon that can be used as generic 360* panorama icon.

Examples of usage:
 - overlay on maps that has panoramic view
 - 360* presentation of the items in the shop
 - embedded on the page panoramic photographs
 - virtual tours

Example icon:

http://www.csi360.net/images/red-camera360-icon.png

**Comment by kps1ny** [comment]
Would love to see this one made; example above with the camera in the middle of swiping arrows is good.

**Comment by MartinW2** [comment]
I would also like to see this. It cannot be compared to icon-refresh or similar, as these are clearly associated with -well- refresh of course.
As 360° panoramas are become more and more popular, i hope fontAwesome will reflect this with an appropriate icon soon - thanks!

**Comment by airaromina** [comment]
![360](https://cloud.githubusercontent.com/assets/28759289/26165960/3b41ad22-3b08-11e7-9db4-5e61c54fd7bb.png)
![pano](https://cloud.githubusercontent.com/assets/28759289/26165961/3b424246-3b08-11e7-848c-0408ff3cd8ec.png)

examples!

**Comment by MartinW2** [comment]
I like the 2nd example!
Be aware that not every panorama is a full 360° (though my intention would be 360° as well).

**Comment by erezLieberman** [comment]
+1

**Comment by jjinkxy** [comment]
+1

**Comment by ccharlton** [comment]
+1000!

**Comment by AppLover69** [comment]
+1
@airaromina's 2nd suggested icon is the best

**Comment by lynetcha** [comment]
![image](https://user-images.githubusercontent.com/11138935/45062775-5c329280-b05f-11e8-8cef-9a957a66ff8b.png)

**Comment by MartinW2** [comment]
The new one from lynetcha is really great!
Please let's finally add this!

**Comment by lastCzarnian** [comment]
Though I understand the reason for the camera in center of the icon, I think that to cover more options with this icon, using something similar to lynetcha's image would be best.  It could be used for camera panorama, 360 degree integration (as with software), rotation ability, full range of movement, etc.

**Comment by pgroot91** [comment]
Also needing a 360 degree icon! Like the first example in #15260 👍

**Comment by simplenotezy** [comment]
We need it too!

**Comment by dolibarr95** [comment]
+1

**Comment by KingDumah** [comment]
+1

**Comment by MartinW2** [comment]
This is going on for 6 years now - is there any process to decide regarding such requests? Any follow-up? I think many people have expressed interest in this, and it has been referenced a couple of times (duplicates etc.) So, who would usually bring this forward, if it's accepted? Is this still the right place for a request?

**Comment by MalyshevDmitry** [comment]
+1

**Comment by pinkminds** [comment]
+1

**Comment by MartinW2** [comment]
Is anyone able to create a pull request, e.g. using the 
beautiful example from @lynetcha as svg or whatever is required?
I just saw the statement on the right side saying:
_Linked pull requests
Successfully merging a pull request may close this issue.
None yet_

**Comment by tagliala** [comment]
Hi @MartinW2 

At the moment we do not accept pull requests containing icons, but anyone is free to fork Font Awesome, including this icon, and share here the link to the github repo

**Comment by MartinW2** [comment]
Hi @tagliala ,
this would only be a temporary (ugly) workaround, which most of us requestors probably have done already: using a local icon, which is not distributed officially.
So, how can this request, which is about 7 years old and still being requested, finally get solved?
Thank you for providing a path to this.
Martin

**Comment by drooog** [comment]
Come on. This icons a no-brainer

**Comment by tagliala** [comment]
Hi @MartinW2 , sorry for the late reply

> So, how can this request, which is about 7 years old and still being requested, finally get solved?

This icon is actually at the 21st in our Leaderboard, it is actually an excellent position for being considered!

Please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work

**Comment by drooog** [comment]
I've used globe icon with a '360°' next to it for the meantime. Happy a more accurate icon in in the works 👍

**Comment by sensibleworld** [comment]
<img width="723" alt="Screen Shot 2021-03-30 at 12 17 50 PM" src="https://user-images.githubusercontent.com/529604/113021806-f395ee80-9151-11eb-90c5-74f5f44cfb2d.png">

This is now available in the latest alpha release of version 6: http://fontawesome.com/download

**Comment by MartinW2** [comment]
Well, late is better than never - especially for those who will need it in the future. So thanks for that!
I hope it will find a way to the free icon sets some day (to be used in open/free CMS like wordpress etc).

**Comment by sensibleworld** [comment]
@MartinW2 The `panorama` icon will be included in v6 of Font Awesome Free, though the `360` icon will be pro-only.
