### ISSUE TITLE
Icon Request: icon-advanced-search

### ISSUE THREAD

**Issue by tritone11** [FortAwesome/Font-Awesome#7724]
The search icon with a viewfinder for advanced search

**Comment by tagliala** [comment]
any example?

**Comment by tritone11** [comment]
![search1](https://cloud.githubusercontent.com/assets/12704485/10865947/4005e9f6-801d-11e5-9a0c-195db6ddee87.png)
![search2](https://cloud.githubusercontent.com/assets/12704485/10865948/401bd6c6-801d-11e5-9a0f-85622f0444a3.png)
![search3](https://cloud.githubusercontent.com/assets/12704485/10865949/4021b780-801d-11e5-80b2-d98b6baff13b.png)

**Comment by PlassJ** [comment]
+2

**Comment by tritone11** [comment]
Solved with search-plus https://fontawesome.com/icons/search-plus?style=solid
