### ISSUE TITLE
Icon Not Shows in Browser 

### ISSUE THREAD

**Issue by tejashri51** [FortAwesome/Font-Awesome#7727]
I am using fa-cube and fa-cubes class but it is not showing in brwoser. Kindly Check the issue

**Comment by TheChen5** [comment]
Can you please provide any code?
Is there ```<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">``` or something like that in your heading? Is the version updated?

**Comment by tejashri51** [comment]
The issue has been solved. Actually version of my css and fonts are old one. Thanks to Revert back.

**Comment by TheChen5** [comment]
Great! Glad to help. Maybe close this issue?

**Comment by tejashri51** [comment]
Yes. :)

On Wed, Oct 21, 2015 at 11:56 AM, TheChen5 <notifications@github.com> wrote:

> Great! Glad to help. Maybe close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7727#issuecomment-149794320>
> .
>



-- 
*TEJASHRI SURESH JAMBURE.*
*Email-Id :* tejashri38@gmail.com


LOVE your environment and

                                       LOVE this planet

**Comment by tagliala** [comment]
Closing :)

@TheChen5 thanks, really appreciate, I'm having a busy time
