### ISSUE TITLE
Icon Request: fa-500px new logo

### ISSUE THREAD

**Issue by holmmedia** [FortAwesome/Font-Awesome#7728]
Hello

500px.com has changed there logo, do You update it?

https://500px.com/

Best Regards
René

**Comment by tagliala** [comment]
Thanks for reporting this. Added to milestone 4.4.1 and assigned to @davegandy

**Comment by Yago** [comment]
:+1:

**Comment by astorije** [comment]
@tagliala and @davegandy, do you have an ETA for this and v4.4.1? :)

**Comment by tagliala** [comment]
@astorije unfortunately I don't know, sorry :(

**Comment by davegandy** [comment]
Updating this one today. Hopefully releasing 4.4.1 today as well.

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by astorije** [comment]
@davegandy, thanks a lot! Are you still planning on releasing 4.4.1 soon?
