### ISSUE TITLE
Icon request: icon-clipboard-notes (checklist, todo list)

### ISSUE THREAD

**Issue by webdevwilson** [FortAwesome/Font-Awesome#773]
A patient chart could be represented by a clipboard, perhaps with checks.  This could also be a todo list, or simply a clipboard (without checks).

**Comment by mightymt** [comment]
+1 for a blank clipboard

**Comment by G-Driver** [comment]
+1

**Comment by mannyblum** [comment]
+1

**Comment by MiguelAngelDiaz** [comment]
+1

**Comment by ericscheid** [comment]
+1 .. could also be named icon-survey

**Comment by SoAmerican** [comment]
+1

**Comment by Bean0B** [comment]
+1

**Comment by zipper** [comment]
+1

**Comment by kpingel** [comment]
+1

**Comment by hadimhd** [comment]
+1

**Comment by AirEssY** [comment]
+1

**Comment by devneutz** [comment]
4 years later, still hoping this gets implemented.. +1

**Comment by vlessard** [comment]
Need something like the attached.  We are currently using fa-clipboard but continuing to get feedback that it doesn't look like a clipboard.  Looks like a lot of others need this one too!

![clipboard-icon](https://user-images.githubusercontent.com/33039656/31909940-d6d04630-b809-11e7-8ebe-24b07ebb5aa8.jpg)
