### ISSUE TITLE
Icons blurring at certain window sizes

### ISSUE THREAD

**Issue by ktross** [FortAwesome/Font-Awesome#7734]
Smaller icons (14px) become blurry at certain window sizes. 
- Navigate to http://fortawesome.github.io/Font-Awesome/icon/trash-o/
- Increase or reduce window width until the smallest icon becomes blurry. This happens for me at window.innerWidth 1427 in addition to other widths.

This is happening on Chrome under both Mac OS X 10.11 as well as Windows 10. I'm currently running Chrome Version 46.0.2490.71 (64-bit) on Mac. I haven't tested it in any other browsers.

Here is a video that I recorded which shows the issue: https://www.youtube.com/watch?v=5qFNNJe3-DE&feature=youtu.be . You'll probably need to set it to 1080p and fullscreen to be able to see it properly.

**Comment by tagliala** [comment]
I can confirm this problem exist but I don't know if there is something we can do

**Comment by tagliala** [comment]
E.g.: this windows,

Chrome 46 / Win 10

![image](https://cloud.githubusercontent.com/assets/556268/10638139/9dcfd5c2-7809-11e5-92a6-971f06ea25ad.png)

200%
![image](https://cloud.githubusercontent.com/assets/556268/10638149/a524f776-7809-11e5-9a02-c932a2da22d0.png)
