### ISSUE TITLE
Icon Request: Shop Icon

### ISSUE THREAD

**Issue by mikiamit** [FortAwesome/Font-Awesome#7736]
Hi There,

Really happy to have font-awasome in my day to day life :)

Would love to have a shop icon, one that describes a business selling goods.

Best,
Michael

**Comment by webappdesigner** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #1958 ? If yes, please +1 that request and close this one. If not, please clarify with an example

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/store?style=solid
https://fontawesome.com/icons/store-alt?style=solid
