### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by merovingio77** [FortAwesome/Font-Awesome#7756]
Hi, I am using your wonderful Fonts, but unfortunately I get these accessibility issues after a check with achecker.ca

1.4 Distinguishable: Make it easier for users to see and hear content including separating foreground from background.

Success Criteria 1.4.4 Resize text (AA)

Check 117: i (italic) element used.
Repair: Replace your i elements with em or strong.
Error Line 264, Column 15:
<i class="fa  fa-bullhorn"
                  style="color: #FFFFFF;
                        font-siz ...
Error Line 303, Column 15:
<i class="fa fa-university"
                  style="color: #FFFFFF;
                        font-si ...
Error Line 342, Column 15:
<i class="fa  fa-folder-open-o"
                  style="color: #FFFFFF;
                        fon ...
Error Line 381, Column 15:
<i class="fa  fa-picture-o"
                  style="color: #FFFFFF;
                        font-si ...
Error Line 420, Column 15:
<i class="fa  fa-file-text-o"
                  style="color: #FFFFFF;
                        font- ...
Error Line 459, Column 15:
<i class="fa  fa-paper-plane-o"
                  style="color: #FFFFFF;
                        fon ..

Can you help me to fix it?

Regards,

Pietro Campanile

**Comment by tagliala** [comment]
Try to switch from `<i>` to `<span>`

Please also remember to provide a screen reader only alternative for icons, if you are not using them with a proper label, refers to #6133

**Comment by tagliala** [comment]
We changed a lot of things about accessibility in those years, 

I'm going to close here because we have documented that [`<span>` tag is more semantically correct](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use) and a we also have a section about accessibility in our documentation: https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility
