### ISSUE TITLE
Icon Request: fa-keyboard-... set

### ISSUE THREAD

**Issue by itsChimpanzee** [FortAwesome/Font-Awesome#7757]
When using Font Awesome in things like user documentation, it would be great to have a set of icons to represent commonly-used keyboard keys. 

I've seen some requests on here for specific keys but I think it would be even better to have a whole set. For example,

* fa-keyboard-return
* fa-keyboard-shift
* fa-keyboard-capslock
* fa-keyboard-alt
* fa-keyboard-ctrl
* fa-keyboard-windows
* fa-keyboard-command
* fa-keyboard-fn
* fa-keyboard-tab

Perhaps there could even be two versions of each; one with just the symbol and one with the symbol inside a coloured box to represent the physical key.

**Comment by tagliala** [comment]
Sorry but I can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

The best choice in this case is to consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
