### ISSUE TITLE
Icon Request: Blank credit card that is the same size as fa-cc-* icons

### ISSUE THREAD

**Issue by mrjonliu** [FortAwesome/Font-Awesome#7759]
The fa-credit-card icon is not the same size as the main set of credit card icons (fa-cc-visa, fa-cc-amex, etc).  A new credit card icon that is the same design but matching the size of the credit card icons would make it easier to create consistently designed applications.  It could just be fa-cc-blank.

Visual example:
http://jsfiddle.net/mrjonliu/ff7ac0g9/

![screen shot 2015-10-26 at 1 21 53 pm](https://cloud.githubusercontent.com/assets/1877342/10739853/91c62022-7be4-11e5-8f07-de5ed0114937.png)

**Comment by ellenhutchings** [comment]
+1

**Comment by tagliala** [comment]
Seems legit. Adding to 4.4.1 milestone, so @davegandy will eventually take a look here

**Comment by MVcodeartbr** [comment]
+1

**Comment by davegandy** [comment]
Added credit-card-alt to 4.4.1-wip to address this problem. It's also a solid version, which should match the rest of the payment icons.

Closing.

**Comment by mrjonliu** [comment]
Thanks a lot everyone, looks great!
