### ISSUE TITLE
Icon request: icon-image-align-left, image-align-right, image-align-center

### ISSUE THREAD

**Issue by Oviglo** [FortAwesome/Font-Awesome#7761]
Hi, 
It's will be very good to implement 3 new icons for positioning image in a text:
- image-align-left
- image-align-default
- image-align-right

Like this:
https://cldup.com/UE91fYi2Un.png

thanks.

**Comment by Crote** [comment]
+1

**Comment by mindplay-dk** [comment]
Not exactly what you were looking for, but here's `float-left` and `float-right` icons, which I was able to load up in Fontello and compile to a custom webfont.

https://drive.google.com/folderview?id=0B_rcnsO82kI5YWVjZzBxWWZDX0E&usp=sharing

These aren't super compact and clean files, they seem to have some InkScape metadata cruft - I'm not an SVG expert at all, I just made these in InkScape pretty quickly with no real prior knowledge...

**Comment by mindplay-dk** [comment]
Added a bunch more - link above is to the folder containing all variations.

![image](https://cloud.githubusercontent.com/assets/103348/16446961/85e793b2-3dea-11e6-8503-7c43ff2e2d77.png)

I'm concerned that these have to work well at very small sizes - not sure which ones work best, I think personally I like the ones with the larger image, although that doesn't seem to work as well for the centered ones.

I've starred the ones that work best for me.

**Comment by mindplay-dk** [comment]
By the way, looking through the resulting `config.json` file generated by Fontello, it completely strips out all the InkScape metadata - only the path is actually stored, so this works out nicely.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.]()
