### ISSUE TITLE
Icon request: NFC

### ISSUE THREAD

**Issue by raugaral** [FortAwesome/Font-Awesome#7773]
Something like:
http://icons.iconarchive.com/icons/icons8/windows-8/256/Mobile-Nfc-Logo-icon.png

**Comment by tagliala** [comment]
Duplicate of #1695? Related to #1692?

**Comment by picoundici** [comment]
+1
It would be very useful. 
I think the best choice is 1 icon for both nfc and rfid. The google material icon "nfc" would be ok.
https://design.google.com/icons/#ic_nfc

**Comment by tagliala** [comment]
No feedback, closing here
