### ISSUE TITLE
Icon Request: fa-teamspeak

### ISSUE THREAD

**Issue by Skinny1001** [FortAwesome/Font-Awesome#7776]
Teamspeak is a communication system. It's a VoIP software designed with security in mind, featuring crystal clear voice quality, endless customization options, and scalabilty up to thousands of simultaneous users.

Can be used in gamers sites.
Se some examples:
![teamspeak-icon](https://cloud.githubusercontent.com/assets/10225244/10801826/21eea228-7d98-11e5-8475-4a74bc12378a.png)
![top teamspeak](https://cloud.githubusercontent.com/assets/10225244/10801827/21f1a478-7d98-11e5-8269-204b0dd03b05.png)
![contact-icons teamspeak](https://cloud.githubusercontent.com/assets/10225244/10801828/21f2fe86-7d98-11e5-8a38-f1d3486e59f8.png)

Thank you so much! :)

**Comment by TheChen5** [comment]
Dupe #1474 
+1 that
Please :mag:before:heavy_plus_sign:
