### ISSUE TITLE
website usability issue - search/subscribe input

### ISSUE THREAD

**Issue by verybigelephants** [FortAwesome/Font-Awesome#7777]
i cannot count how many times, when i google for fontawesome and want to look a specific icon, i get to the font awesome webpage  https://fortawesome.github.io/Font-Awesome/ and start typing the icon name into the "subscribe" input. then when the website starts telling me that it's an incorrect e-mail address i realize that's not what i want.

then spend countless seconds (truly precious in web browsing) locating webpage that has the icon search in the navigation and only then finding the search input underneath another terrible subscribe input

this is truly a usability fail

**Comment by tagliala** [comment]
same here :)

**Comment by kristopolous** [comment]
Hi, in the ticket #8457, I suggested treating user-input that looks nowhere close to an email address as a search query.

Essentially it would be something like 

    if input.match(/[\.\/,1-3!@#]/) === null) {
       // assume this is a search
    }

So under these constraints, if someone types in 

 * a valid email address, it will be used
 * a poorly-formed by probably valid email address, it will be used
 * something that looks nothing like an email address, search will be used

For instance, this list of poorly typed emails would be flagged as bad email:

 * some email@gmail,com
 * someemail2gmailcom
 * some email#gmailcom

While this list of words would be flagged as search:

 * chevron
 * hourglass
 * home

... etc ...

**Comment by tagliala** [comment]
This should be fixed now

**Comment by verybigelephants** [comment]
hooray
