### ISSUE TITLE
Icon request: fa-clapper

### ISSUE THREAD

**Issue by andreaslarssen** [FortAwesome/Font-Awesome#7778]
Examples:
https://cdn3.iconfinder.com/data/icons/line/36/film_clapper-512.png
http://www.piercingpurpose.com/files/clapper.png

**Comment by TheChen5** [comment]
Dupe #3130
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by andreaslarssen** [comment]
Sorry, my bad. Did search, did not find.

**Comment by Johnbols** [comment]
I'm sure when available people will see it's popularity!

Thanks for responding Tagliala  ;)

**Comment by Johnbols** [comment]
Maybe you can use this design

![composite](https://cloud.githubusercontent.com/assets/15878127/11194933/56e50758-8caf-11e5-8d74-a262e2b29e0d.png)

**Comment by bartbutenaers** [comment]
+1

**Comment by Johnbols** [comment]
Still no clapper guys?

**Comment by hubertguillemain** [comment]
+1
