### ISSUE TITLE
Icon request: icon-food

### ISSUE THREAD

**Issue by olematon** [FortAwesome/Font-Awesome#7779]
To express shipment includes food and requires a special vehicle suitable for food transport.

**Comment by tagliala** [comment]
Could you please post an example?

**Comment by sensibleworld** [comment]
We now have a bunch of food-related icons: https://fontawesome.com/icons?d=gallery&c=food

And also some fast shipping icons: 
- https://fontawesome.com/icons/shipping-fast?style=solid
- https://fontawesome.com/icons/shipping-timed?style=solid
