### ISSUE TITLE
A hand-sign-i-love-u

### ISSUE THREAD

**Issue by cnavigato** [FortAwesome/Font-Awesome#7781]
![i-love-u-hand-sign](https://cloud.githubusercontent.com/assets/518536/10822183/5706c9ce-7e13-11e5-959b-b6765475e89c.png)

**Comment by aethior** [comment]
Hi @cnavigato,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/hand-love

Regards.

cc/ @tagliala
