### ISSUE TITLE
Icon Request: fa-directions

### ISSUE THREAD

**Issue by theill** [FortAwesome/Font-Awesome#7785]
I would love to see the "directions" icon from Google Maps. It's a diamond with a right-arrow inside like this

![diamond with a right-arrow inside](http://d.pr/i/1kc36+)

**Comment by TheChen5** [comment]
Dupe #1563 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by theill** [comment]
Ups, sorry about that. I did search but surely not good enough. I'll +1 that instead, thanks.
