### ISSUE TITLE
Icon Request: fa-fragile

### ISSUE THREAD

**Issue by gklandes** [FortAwesome/Font-Awesome#7786]
Looking for an icon to indicate an item is fragile. Most directly this would be product related in an e-commerce setting. It could foreseeably have further extension conveying 'caution', 'breakable' (phyical or abstract) or easily harmed.

The icon could be a modification of the current fa-glass or something like this image:

![ecommerce-fragile-icon](https://cloud.githubusercontent.com/assets/11524581/10856453/d95e4002-7f15-11e5-9873-dae590d1a313.png)
image src:
http://www.iconarchive.com/show/windows-8-icons-by-icons8/Ecommerce-Fragile-icon.html
http://icons8.com/license/

**Comment by MVcodeartbr** [comment]
+1

**Comment by xelaxam** [comment]
+1 maybe just be closer as the font awesome look but it can be cool

**Comment by PlassJ** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=fragile
