### ISSUE TITLE
balance-scale icon not shown correctly

### ISSUE THREAD

**Issue by sanazaidi** [FortAwesome/Font-Awesome#7787]
balance-scale icon not shown any icon on website

**Comment by tagliala** [comment]
do you mean here: http://fontawesome.io/icon/balance-scale/ or on your own website?

In the latter case, I suggest you to take a look at the troubleshooting guidelines: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by Krevo** [comment]
@sanazaidi : Are you using the version 4.4  of font-awesome ?

**Comment by tagliala** [comment]
No feedback, closing here
