### ISSUE TITLE
Icon Request: fa-fan / fa-propellor

### ISSUE THREAD

**Issue by haydenkibble** [FortAwesome/Font-Awesome#7794]
This would be great for fan speed indicators in apps.
I currently want it for a home automation app that turns on an extractor fan

p.s. I'm a huge *fan* of Font Awesome, keep up the good work! Ho ho ho

**Comment by tagliala** [comment]
Duplicate of #3684?

**Comment by haydenkibble** [comment]
Yes was a duplicate. Thanks
