### ISSUE TITLE
Icon Request: fa-gps

### ISSUE THREAD

**Issue by mikael1000** [FortAwesome/Font-Awesome#7795]
Often I write the gps-coordinates people can use on websites. Now I use the car icon and it's not bad. However there should be a gps-icon?

**Comment by TheChen5** [comment]
Dupe #560 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by mikael1000** [comment]
Well I found that post and I would say that it's not a dupe. That thread is more about a geolocation-symbol. I ask for a symbol that looks like a GPS-device. I don't say how important it is, I just bring it up.

So I did search before

**Comment by tagliala** [comment]
Could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by AndreLGava** [comment]
You culd use this as a GPS device, even its not a GPS, this devices have this function: 
http://fontawesome.io/icon/mobile/
http://fontawesome.io/icon/tablet/

you could use this to setting a position:
http://fontawesome.io/icon/map-marker/
http://fontawesome.io/icon/thumb-tack/

and this to direct to location:
http://fontawesome.io/icon/location-arrow/
http://fontawesome.io/icon/compass/

or in general cases, you could use this to anywhere:
http://fontawesome.io/icon/globe/

I'd use this icons, I guess that I could use this for anything related to GPS, location, position and related

**Comment by tagliala** [comment]
no feedback, closing here
