### ISSUE TITLE
Icon Request: fa-weight-scale

### ISSUE THREAD

**Issue by loving1** [FortAwesome/Font-Awesome#7797]
Hi there! 

It would be awesome to have something that would look like a scale (other than the tachometer) for use in the health world. 

Thank you!

**Comment by tagliala** [comment]
We already have a scale, I suppose this is a request for a weight scale

**Comment by JeroenCollier** [comment]
+1

**Comment by TonyValenti** [comment]
+1 for something like this:
https://www.iconexperience.com/i_collection/icons/?icon=body_scale

**Comment by tellnes** [comment]
+1

**Comment by platdesign** [comment]
+1

**Comment by newmangreen** [comment]
+1

**Comment by sensibleworld** [comment]
Included in the 5.0.7 release! https://fontawesome.com/icons?d=gallery&q=weight%20scale
