### ISSUE TITLE
Icon request: Toilet sign for gents and ladies

### ISSUE THREAD

**Issue by ashish-chopra** [FortAwesome/Font-Awesome#7807]
This is a basic sign used on google maps. Develop the same in font awesome library to use generically. Also single lady and gents sign can also be used in games being developed in web technologies.

http://www.aiga.org/uploadedImages/AIGA/Content/Tools_and_Resources/14_toilets.gif

Cheers
Ashish Chopra
From India

**Comment by caduvieira** [comment]
Dupe of #2670
please +1 that one

**Comment by ashish-chopra** [comment]
I +1 #2670 So closing this issue request.
