### ISSUE TITLE
Icon Request: fa-line

### ISSUE THREAD

**Issue by erilin20** [FortAwesome/Font-Awesome#7810]
Hello there, 

In Taiwan, and I believe in Korea too. "LINE" is a very popular mobile messaging APP, similar as "Whatsapp". Almost all my friends are using LINE right now, even more than FB Mesanger. Please see this article for reference:
https://en.wikipedia.org/wiki/Line_%28application%29

So, if possible, I wish this "LINE" icon can be added:)
Please see/download their official logo from this page: http://line.me/logo/en

As for use cases, I think it will be treated like other social app icons, like Facebook, Twitter, etc.
For example: http://demo.qodeinteractive.com/bridge21/contact/ 
On this sample page, if you scrolled down, there are some icons under Our Office section. I would like to add one more here. I use this LINE icon a lot for my clients' websites. It's inconvenient that I always need to create a special image for this item. I would really appreciate if you can add this icon to your library.

Thank you very much again! And Font awesome is indeed really awesome!

Erin

**Comment by TheChen5** [comment]
Dupe #2631 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by ombwp** [comment]
+1

**Comment by TheChen5** [comment]
Please **do not** +1 this request as it is a duplicate.
Instead, +1 #2631

**Comment by yogoeasy** [comment]
Great, I need this as well.

**Comment by TheChen5** [comment]
@yogoeasy Please +1 #2631

**Comment by suabahasa** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/2631
