### ISSUE TITLE
Icon request: icon-periscope

### ISSUE THREAD

**Issue by srdavidsilva** [FortAwesome/Font-Awesome#7812]
The periscope is a kind of social network that is being widely used for both business and personal life.
Thus, several companies and self-employed professionals are already referencing the system on their websites, one icon of Periscope would be very useful in these cases.

https://www.periscope.tv/

**Comment by TheChen5** [comment]
Dupe #6463 
+1 that
Please Please :mag:before:heavy_plus_sign:

**Comment by voltechs** [comment]
Why do these remain open if there is an obvious duplicate?
