### ISSUE TITLE
Icon Request: fa-tv-y, fa-tv-y7, fa-tv-g, fa-tv-pg, fa-tv-14, fa-tv-ma

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7816]
Request for [TV Parental Guidelines icons](https://en.wikipedia.org/wiki/TV_Parental_Guidelines).

#### fa-tv-y
This program is designed to be appropriate for all children.

![TV-Y](https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/TV-Y_icon.svg/100px-TV-Y_icon.svg.png)

#### fa-tv-y7
This program is designed for children age 7 and above.

![TV-Y7](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/TV-Y7_icon.svg/100px-TV-Y7_icon.svg.png)

#### fa-tv-g
Most parents would find this program suitable for all ages.

![TV-G](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/TV-G_icon.svg/100px-TV-G_icon.svg.png)

#### fa-tv-pg
This program contains material that parents may find unsuitable for younger children.

![TV-PG](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/TV-PG_icon.svg/100px-TV-PG_icon.svg.png)

#### fa-tv-14
This program contains some material that many parents would find unsuitable for children under 14 years of age.

![TV-14](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/TV-14_icon.svg/100px-TV-14_icon.svg.png)

#### fa-tv-ma
This program is specifically designed to be viewed by adults and therefore may be unsuitable for children under 17.

![TV-MA](https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/TV-MA_icon.svg/100px-TV-MA_icon.svg.png)

**Comment by PeterShaggyNoble** [comment]
-1 from me, I'm afraid; too regional.

**Comment by Rodrigo54** [comment]
-1

**Comment by TheChen5** [comment]
Some are duplicates of #6239, #6951.
Please +1 those and remove the ones which are dupes.
ALSO: You can stack icons to make these. http://jsfiddle.net/pd5xv6sc/
Remember, please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
Closing here in favour of #6951, please post there so we can integrate missing icons for this set.

Please also consider a custom build 

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.
