### ISSUE TITLE
fa-square-o/fa-check-square-o size issue

### ISSUE THREAD

**Issue by okonomiyaki3000** [FortAwesome/Font-Awesome#7819]
It would seem an obvious use for `fa-square-o` and `fa-check-square-o` would be as interactive checkboxes. The user clicks, one swaps with the other and shows that the box is either checked or not. However, their widths are different so simply swapping them causes some unwanted shifting of adjacent elements. It would be best if they were the same width.

**Comment by EgonSpengler** [comment]
+1

**Comment by tagliala** [comment]
dup #6238

**Comment by okonomiyaki3000** [comment]
dup #5156

The issue is almost a year old.
