### ISSUE TITLE
Icon Request: fa-trowel

### ISSUE THREAD

**Issue by mdolberg** [FortAwesome/Font-Awesome#7820]
First of all - thank you for everything! 

An icon of a trowel would come in handy as I am planning to use it 
when ordering new construction tools in my web app.

![masonry_trowel__ss 1](https://cloud.githubusercontent.com/assets/11992836/10965288/a929c638-83b4-11e5-8a68-71beb0a191b5.gif)

**Comment by MVcodeartbr** [comment]
ugly

**Comment by tagliala** [comment]
@MVcodeartbr this is just an example, I'm pretty sure that if this icon will be implemented Dave will use something better :)

**Comment by smithandre** [comment]
+1

**Comment by dhaupin** [comment]
+1

**Comment by nickm4162** [comment]
very interested.

**Comment by madsrolsen** [comment]
Very interested!!! 
![trowel](https://user-images.githubusercontent.com/32387588/31010703-0c9b0022-a50c-11e7-86de-c8ee153e7aea.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/trowel?s=solid
