### ISSUE TITLE
Icon Request: fa-tractor

### ISSUE THREAD

**Issue by mdolberg** [FortAwesome/Font-Awesome#7821]
I am planning to use it as a way to express really big and heavy vehicle. Truck is not enough for me because I'm using it already for another context of shipping....

![tractor](https://cloud.githubusercontent.com/assets/11992836/10965016/eee539fc-83b2-11e5-9cc8-66efea48dc5a.jpg)

**Comment by TheChen5** [comment]
Dupe #5052
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by mdolberg** [comment]
Sorry about that.
12 months ago is a long time... Does it mean it wont happen?

**Comment by TheChen5** [comment]
That's fine.

12 months... That isn't long for an icon request. The battery progress icons were made 2 years after the request was opened. It took 3 years for the browser icons request to become a reality. 

Yes, it is possible that it may never happen. It needs to gain enough support. There are other icon requests that have way more support than this one, so the chance of a tractor getting in Font Awesome is pretty minimal.

Also, can you please close this issue?

**Comment by TheChen5** [comment]
Also, you want to go to the tractor request #5052 and +1 it. That means you are showing support for it.
