### ISSUE TITLE
Icon Request: fa-driver-wheel

### ISSUE THREAD

**Issue by mdolberg** [FortAwesome/Font-Awesome#7824]
I am planning to use it as a way to express transportation in another way (I am already using road, car and truck)

![wheel](https://cloud.githubusercontent.com/assets/11992836/10965261/6f495852-83b4-11e5-9164-2e33913f9d2c.jpg)

**Comment by TheChen5** [comment]
Dupe #3581 
+1 that
Please :mag:before:heavy_plus_sign:
