### ISSUE TITLE
Icon request: fa-geoloc

### ISSUE THREAD

**Issue by dgosset** [FortAwesome/Font-Awesome#7826]
An icon like "target" to trigger a new geoloc, like the browser do/show in the nav bar
example: https://www.neustar.biz/base/img/icon-target-big-gry.png

**Comment by aethior** [comment]
Hi @dgosset,

Check `fa-crosshairs` icon: http://fontawesome.io/icon/crosshairs/

**Comment by dgosset** [comment]
perfect, I had not seen
