### ISSUE TITLE
Icon Request: fa-chart-trend

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#7832]
Very useful to use with charts.

![image](https://cloud.githubusercontent.com/assets/1769227/10986973/150edf08-842f-11e5-9b51-9a84027a67f2.jpg)

Example:
![example](https://cloud.githubusercontent.com/assets/1769227/10987057/d413b680-842f-11e5-9e84-fa0f01ac2991.jpg)

**Comment by dennym** [comment]
+1

**Comment by tagliala** [comment]
Duplicate of #4397 , please +1 that request

closing here
