### ISSUE TITLE
GYm icon 

### ISSUE THREAD

**Issue by awatasoftsys** [FortAwesome/Font-Awesome#7833]
I want gym icon

**Comment by BTVincent** [comment]
Could you be more precise and/or give an example for the developpers ?

**Comment by voltechs** [comment]
Maybe like, free-weights?

**Comment by tagliala** [comment]
considering this as a duplicate of #1500 , in you have something different in mind please provide an example

Please also take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
