### ISSUE TITLE
Icon Request: fa-user-check

### ISSUE THREAD

**Issue by dennym** [FortAwesome/Font-Awesome#7836]
Pretty straight forward...
like fa-user-times and fa-user-plus there should be an fa-user with a check symbol

**Comment by tagliala** [comment]
Refers to #1181 , you will find a solution there

**Comment by nyon** [comment]
I created a superset of FontAwesome icons which is also hyperlinked in the issue @tagliala pointed out. See nyon/fontawesome-actions for ```fa-user-check-circle```.

**Comment by tagliala** [comment]
dup of #6053
