### ISSUE TITLE
Icon Request: fa-plumbing-pipe

### ISSUE THREAD

**Issue by redfellow** [FortAwesome/Font-Awesome#7837]
The icon fa-pipe would resemble a plumbing pipe.

**Comment by xmuskrat** [comment]
![image](https://user-images.githubusercontent.com/59917/57534739-8c6cb800-72f5-11e9-98da-26c86e97ca5c.png)

**Comment by xmuskrat** [comment]
![image](https://user-images.githubusercontent.com/59917/57534764-9989a700-72f5-11e9-8b9b-2efaee0d4bd0.png)

**Comment by xmuskrat** [comment]
+1

**Comment by MrFevs** [comment]
👍

**Comment by aethior** [comment]
Hi,

[fa-pipe-section](https://fontawesome.com/icons/pipe-section) and [fa-pipe-valve](https://fontawesome.com/icons/pipe-valve) were added in v6.0.0-BETA2.

Regards.

cc/ @tagliala
