### ISSUE TITLE
Icon Request: fa-vote

### ISSUE THREAD

**Issue by mayuicon** [FortAwesome/Font-Awesome#7839]
icon of vote 
![votes](https://cloud.githubusercontent.com/assets/15690079/10998779/f90a5252-8469-11e5-9d94-7a56281dd50c.png)

**Comment by salarmehr** [comment]
+100

**Comment by aethior** [comment]
I think a more simple icon is better. My suggestion:

![sobre-36](https://cloud.githubusercontent.com/assets/1769227/11084419/3838b124-883b-11e5-9fed-c179b2539b8d.png)

**Comment by sodevious** [comment]
+1

**Comment by Brachamul** [comment]
+1

**Comment by mtdinnyc** [comment]
+1

**Comment by charlex** [comment]
+1

**Comment by Lioness612** [comment]
Very similar to the submit icon I requested (#9619).

I think having an envelope makes it look more like posting a letter? Maybe a plain document has wider application?

**Comment by EdnaldoNeimeg** [comment]
+1

**Comment by emanuelschuetze** [comment]
I think, the original suggested icon "paper into ballot box" is to complex.
Suggestion: Make the vote icon more simply and show the "vote action" only (circle with big X = voted), e.g.:
![200px-vote_icon svg](https://cloud.githubusercontent.com/assets/2075427/19106096/da0d9296-8ae5-11e6-9116-d8153bc3116f.png)
Use a circle instead of a square - it's more harmonious. 
Important: the X has to bigger than the circle (otherwise it would be to similar as icon 'fa-times-circle')

I hope this helps to solve this icon request.

**Comment by getaasciesh** [comment]
@emanuelschuetze Original "ballot into box" is simpler to draw, conceive and interpret than your suggestion. I can interpret your suggestion as cancel, close, item done etc. And, with that many curves and dents it is harder to draw too.

**Comment by Lioness612** [comment]
My suggestion was simpler than the 3D box and clearer than the x in a box. and I believe it shows voting or submitting - even posting if you like. See #9619.
X doesn't mean voting to those of us who live in places with a preferential voting system.
And an X in a box doesn't mean submitting - which is what I was looking for.

**Comment by emanuelschuetze** [comment]
Another draft of my icon suggestion: Use a circle with a (simple) "hand-drawn" cross. The two lines of the cross have to be longer than the diameter of circle. Then it is clearly identifiable as voting cross of a ballot. Opinions?
![voteicon](https://cloud.githubusercontent.com/assets/2075427/22324052/1aa9fdfc-e3a7-11e6-99a9-58ec2a200eba.jpg)

**Comment by Brachamul** [comment]
As a foreigner, I've never had to cross a circle to vote. We only use the little envelopes. They might be more universal.

**Comment by emanuelschuetze** [comment]
But you have to vote for somebody (candidate) or something (yes/no/abstain) on a ballot paper which you put into the envelope, right? - So I explain the vote action with the pencil on paper. You explain the insert action of vote envelope into the ballot box. Right?

**Comment by getaasciesh** [comment]
@emanuelschuetze I can interpret your suggestion in too many different ways. Simply doesn't work. And, not all countries use "cross on a box" system. For example, in my country it is "Swastika stamp on a box" (Swastika existed 1000 years before Nazis, so no connection whatsoever with them. In our culture swastika is a sign of good fortune).  Action of dropping ballot into a box explains voting perfectly.

**Comment by Brachamul** [comment]
@emanuelschuetze we have a ballot paper for each option. For example a paper with "YES" and a paper with "NO". We don't write anything or check anything.

**Comment by emanuelschuetze** [comment]
> Action of dropping ballot into a box explains voting perfectly.

@getaasciesh @Brachamul Ok, then let us use this suggestion as icon for voting. I can accept it. - Maybe later we can add my suggestion (circel + cross) as additional icon for special use cases.

**Comment by Ala2dz** [comment]
is it added ? +1

**Comment by Mojtaba-Reyhani** [comment]
+1

**Comment by Mojtaba-Reyhani** [comment]
my suggestion:
![elections](https://user-images.githubusercontent.com/19150538/30935827-c52e35b6-a3de-11e7-95c7-67f9332f938f.png)
![elections 1](https://user-images.githubusercontent.com/19150538/30935835-caa470f0-a3de-11e7-93d8-250186bac4a3.png)

**Comment by kincaider** [comment]
+1

**Comment by janzankowski** [comment]
+1

**Comment by choonggg** [comment]
+1

**Comment by mukundindianic** [comment]
![1519218808](https://user-images.githubusercontent.com/12658498/36534176-cc0031b0-17eb-11e8-9121-ce38edb9081b.png)

**Comment by trkaplan** [comment]
![image](https://user-images.githubusercontent.com/992897/39867724-eca79188-545e-11e8-866a-b943fcdcc6e2.png)

[Source](https://www.flaticon.com/free-icon/voting_95375#term=election&page=1&position=11)

**Comment by sensibleworld** [comment]
Our latest release has a few options for this: https://fontawesome.com/icons?d=gallery&q=vote&c=political
