### ISSUE TITLE
Icon request: Language

### ISSUE THREAD

**Issue by raduluchian** [FortAwesome/Font-Awesome#784]
I think a great addition to the set would be a language icon. Perhaps something similar to <a href="http://thenounproject.com/noun/speech/#icon-No1202">this icon</a>.

**Comment by aethior** [comment]
I can't considerate duplicate of #2096 because the title is different but the requested icon is the same.
The other request has more upvotes.

@tagliala What do you think?

**Comment by tagliala** [comment]
Yes, thanks, let's use #2096
