### ISSUE TITLE
Icon Request: fa-waves

### ISSUE THREAD

**Issue by roarytubbs** [FortAwesome/Font-Awesome#7840]
Would love to see an icon for water

**Comment by TheChen5** [comment]
Would icon-tint work?
http://fortawesome.github.io/Font-Awesome/icon/tint/

**Comment by roarytubbs** [comment]
I'm thinking something more like the waves icon on this site - http://fontello.com/

**Comment by tagliala** [comment]
So let's rename this

**Comment by jckb188** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by tagliala** [comment]
I'm going to consider this as a duplicate of #2266, which has more +1s and it's older
