### ISSUE TITLE
Icon Request: fa-blab, fa-blab-square

### ISSUE THREAD

**Issue by SLIcoreDesign** [FortAwesome/Font-Awesome#7841]
HI! So there's this thing called Blab and some folks in my network are hearing big things. In the interest on stayin ahead of a wave, if there will be one, I'd like to put in a request for the Video conversation platform now.

This would be, to my mind, how a fa-blab and fa-blab-square icon might work:
![blablogorequest](https://cloud.githubusercontent.com/assets/14189281/11011021/47c874e6-84a1-11e5-963c-2131fefa0f4f.jpg)

First and foremost, this request is for a client who is staying ahead of social media trends and I wanted to feature many of these platforms (new ones especially) as icons to save her some http calls.

Thanks for your time!

SLIcore

**Comment by aethior** [comment]
>Blab is dead…long live Blab.
Today is the last day of Blab. We’re shutting down the website and app, and focusing 100% on our new project. ([source](https://shaanvp.medium.com/blab-is-dead-long-live-blab-d2f72449ddb8))

cc/ @tagliala
