### ISSUE TITLE
Icon Request: fa-google

### ISSUE THREAD

**Issue by aicragellebasi** [FortAwesome/Font-Awesome#7842]
Hi,
I guess I am not the first one in asking you this... the new google icon...
Do you guys plan to include it soon?
Thanks for your amazing work!

**Comment by aethior** [comment]
Hi @aicragellebasi,

The Google icons will be updated in the next release: https://github.com/FortAwesome/Font-Awesome/issues/7357

Regards.

**Comment by tagliala** [comment]
I can confirm, but I haven't a deadline, sorry. This is up to Dave
