### ISSUE TITLE
Icon Request: fa-hierarchy

### ISSUE THREAD

**Issue by mendrik** [FortAwesome/Font-Awesome#7844]
one icon that represents a tree of items.

![Demo1](https://cdn3.iconfinder.com/data/icons/software-office-tools/33/tree-128.png)
or
![Demo1](https://cdn0.iconfinder.com/data/icons/folder-line/512/folder_tree-128.png)

**Comment by mdolberg** [comment]
Try using this one for now...
http://fortawesome.github.io/Font-Awesome/icon/sitemap/

![org](https://cloud.githubusercontent.com/assets/11992836/11019480/123b53e4-8603-11e5-9083-4f2a8c285ae4.JPG)

**Comment by tagliala** [comment]
folder tree: #2752
