### ISSUE TITLE
Icon request: icon-viadeo

### ISSUE THREAD

**Issue by Wefeedthetroll** [FortAwesome/Font-Awesome#7845]
Hello guys, 

It would be nice if we could get a viadeo fontawesome icon. 
Viadeo is quite a big social network in France and i'm sure lots of us would be more than glad if you'd make one ! 

Thanking you in advance, 

![viadeo](https://cloud.githubusercontent.com/assets/5000534/11018033/4f53946e-861a-11e5-8153-383aa6a78d7b.png)

**Comment by TheChen5** [comment]
Dupe #886 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by renanCaraujo** [comment]
+1
