### ISSUE TITLE
Icon Request: fa-strategy

### ISSUE THREAD

**Issue by uxitten** [FortAwesome/Font-Awesome#7847]
i designing strategy icon
![strategy](https://cloud.githubusercontent.com/assets/1549069/11019546/f668e8dc-85f5-11e5-984d-984da3b872de.jpg)

**Comment by tagliala** [comment]
Don't like this title either

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

I'm going to considet this a subset of #937, please +1 that request
