### ISSUE TITLE
 Icon request: icon-office-phone

### ISSUE THREAD

**Issue by JeffreyArts** [FortAwesome/Font-Awesome#7849]
Hi,

I'm looking for an icon like this:

![Office phone](http://cdn.flaticon.com/png/256/1724.png)

Which is similair to "fa-fax", with a display instead of paper. I can hardly believe that it isn't there already but searching for "phone"  results in "fa-phone", "fa-square-phone" & "fa-mobile". Searching "office" or "desk" don't give proper results neither.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/phone-office?style=solid
