### ISSUE TITLE
Icon Request: fa-weight

### ISSUE THREAD

**Issue by uxitten** [FortAwesome/Font-Awesome#7850]
weight
![weight](https://cloud.githubusercontent.com/assets/1549069/11019996/b7ba640e-8608-11e5-94c4-0bc9e1a32541.jpg)

**Comment by caduvieira** [comment]
dupe of #2735
please +1 that one

**Comment by smigh** [comment]
Just suggesting [this one](http://fortawesome.github.io/Font-Awesome/icon/balance-scale/), which is closer to your example than the new weight icon on the new issue.
