### ISSUE TITLE
Icon Request: fa-laurel-leaf 

### ISSUE THREAD

**Issue by pvsrivathsa** [FortAwesome/Font-Awesome#7855]
Laurel leaf icon

![image](https://cloud.githubusercontent.com/assets/9319229/11022520/faf437d0-8686-11e5-9014-6ea4680098d1.png)

**Use Cases**
- Awards
- Peace

**Comment by harangue** [comment]
+1

**Comment by Editandrew** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by 1GR3** [comment]
+1

**Comment by Laurab-io** [comment]
+1

**Comment by only-andy** [comment]
+1

**Comment by phantomhand** [comment]
+1

**Comment by festhome** [comment]
+1

**Comment by diegocatalao** [comment]
+1

**Comment by romain-garby** [comment]
+1
Could be good if it also exists with a "%" inside (for win ratio).

**Comment by allendoerfer** [comment]
+1

**Comment by Nisutec** [comment]
+1

**Comment by aethior** [comment]
Hi @pvsrivathsa,

This icon has been added in v6.3.0.
Check https://fontawesome.com/icons/wreath-laurel

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Thanks!
