### ISSUE TITLE
Icon Request: fa-wifi-0, fa-wifi-1, fa-wifi-2

### ISSUE THREAD

**Issue by EgonSpengler** [FortAwesome/Font-Awesome#7856]
Akin to the battery levels and volume levels, different wifi quality symbols would be handy for use in toolbars of tiling window managers (i.e. I want to use this in my own WM config!).

Something along these lines for signal strength:
![wifi quality](http://i.istockimg.com/file_thumbview_approve/75135173/5/stock-illustration-75135173-wifi-signal-symbol-icon.jpg)

**Comment by leesah** [comment]
+1

**Comment by vsemecky** [comment]
+1

**Comment by nkuma** [comment]
+1

**Comment by MrZach** [comment]
+1

**Comment by eiriktj** [comment]
+1

**Comment by zestyr** [comment]
+1

**Comment by AdamNiederer** [comment]
+1

**Comment by zup1** [comment]
+1

**Comment by elvarsteinn** [comment]
+1

**Comment by majaesch** [comment]
+1

**Comment by cnelissen** [comment]
+1

**Comment by leothelocust** [comment]
+1

**Comment by purpleKarrot** [comment]
+1

**Comment by williampayne23** [comment]
+1

**Comment by truls1502** [comment]
+1

**Comment by humancopy** [comment]
+1

**Comment by graipher** [comment]
+1

**Comment by goattea** [comment]
+1

**Comment by Foolson** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by miko007** [comment]
+1

**Comment by CamWright** [comment]
+1

**Comment by eriksape** [comment]
+1

**Comment by cellsheet** [comment]
+1

**Comment by r10o** [comment]
+1

**Comment by brunodles** [comment]
+1

**Comment by ektidey** [comment]
+1

**Comment by siftra** [comment]
+1

**Comment by dratis** [comment]
+1

**Comment by marcosaug** [comment]
+1

**Comment by paynecs** [comment]
+1

**Comment by shifenghu** [comment]
+1

**Comment by dialuplama** [comment]
+1

**Comment by ptandler** [comment]
+1 I really like the suggested icons!

**Comment by krismundorff** [comment]
+1

**Comment by agui75** [comment]
+1

**Comment by balinabbb** [comment]
+1

**Comment by UnicodeAlt255** [comment]
+1

**Comment by ylhan** [comment]
+1 please

**Comment by yousifm** [comment]
+1

**Comment by ardeaf** [comment]
+1

**Comment by dcousens** [comment]
+1 - until this is added,  I'm using the [following based on Material Icons](https://github.com/dcousens/material-wifi-icons).

![](https://camo.githubusercontent.com/7887a0ec1958fcc7de9cb5ec868506e709b166f5/687474703a2f2f692e696d6775722e636f6d2f793674304539752e706e67)

**Comment by anisimovsergey** [comment]
+1 - the suggested icons are exactly what I need!

**Comment by lobachevzky** [comment]
@dcousens, how do you actually use those icons from the material-wifi-icons library? I guess I'm just used to copying and pasting he icons :/

**Comment by dcousens** [comment]
@lobachevzky `echo -e "\ue905\ue903\ue901\ue900"`

**Comment by lobachevzky** [comment]
Got it. Thanks!

**Comment by lobachevzky** [comment]
So, I have material-wifi installed:
```
❯ fc-list | ag wifi
/usr/share/fonts/TTF/material-wifi.ttf: material\-wifi:style=Regular
```
but `fc-match` is just not working:
```
❯ fc-match material\-wifi                        
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

```
❯ fc-match material-wifi                        
DejaVuSans.ttf: "DejaVu Sans" "Book"
```
Did you have to modify one of your config files somehow?

**Comment by dcousens** [comment]
@lobachevzky this is not the right place to be asking this.
This is `Font-Awesome`,  open an issue at [material-wifi](https://github.com/dcousens/material-wifi-icons/issues).

**Comment by lobachevzky** [comment]
You got it.

**Comment by gb78** [comment]
+1, this would be a nice fit for one of my projetcts, alongside the fa-signal variants too.

**Comment by Uniphix** [comment]
+1

**Comment by zkhil1** [comment]
+1

**Comment by maciejgodek** [comment]
echo -e "\ue905\ue903\ue901\ue900"

**Comment by lwenkin** [comment]
+1

**Comment by jetibest** [comment]
And would also like this one for the fa-signal, because they have different semantics.

**Comment by RobinWeymans** [comment]
+1

**Comment by rotemy9** [comment]
+1

**Comment by cellsheet** [comment]
+1

**Comment by Wingo5315** [comment]
+1

**Comment by cs** [comment]
+1

**Comment by bsurai** [comment]
+1

**Comment by bssb** [comment]
+1

**Comment by nuri-engin** [comment]
+1

**Comment by dantemple** [comment]
+1

**Comment by blaadje** [comment]
+1

**Comment by 4lex-gs** [comment]
+1

**Comment by Flutterwondershy** [comment]
+1

**Comment by nathanchere** [comment]
Approaching the 3-year anniversary of this request... what a perfect time it would be to implement :smile:

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=wifi&v=5.3.0,5.3.1

**Comment by iSpaceGitHub** [comment]
Great that the icon is already there, but I wouldn't have found it because I was searching for an "echo" icon. Perhaps add it twice, with different names?

**Comment by sensibleworld** [comment]
Oh, interesting. I could add `echo` as a search term?

**Comment by iSpaceGitHub** [comment]
> Oh, interesting. I could add `echo` as a search term?

Is that possible? That would be great!
