### ISSUE TITLE
Icon Request: fa-nodejs

### ISSUE THREAD

**Issue by joshua-golub** [FortAwesome/Font-Awesome#7858]
(1) This would be a **brand** icon for [Node.js](https://nodejs.org/en/)

(2) It would look like some part of [Node's branding](https://www.google.com/search?hl=en&site=imghp&tbm=isch&source=hp&biw=1600&bih=778&q=node.js+logo)

**Comment by TheChen5** [comment]
Dupe #2584
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by joshua-golub** [comment]
Sorry about that. I did do a search but was distracted by the 373 matches in the source code.
