### ISSUE TITLE
CSS validation

### ISSUE THREAD

**Issue by oschusler** [FortAwesome/Font-Awesome#7860]
When you try to validate the css of your webpage, after including the CDN version of FontAwesome, the validator reports 18 errors. This also holds with the current master of this font.

This non-validity triggers no immediate errors on the webpages, but since I try to keep my websites as valid as possible I hoped that you could fix these errors.

An example of these errors could currently be found on: http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fhugo.schuslerproductions.nl%2F

**Comment by wolfy1339** [comment]
Because there are some IE hacks to maintain compatibility

**Comment by tagliala** [comment]
Refers to #5043

If you don't need IE8 support, please consider a custom build

Closing here
