### ISSUE TITLE
Icons not showing on iOS Safari

### ISSUE THREAD

**Issue by anquinn** [FortAwesome/Font-Awesome#7861]
Yet another squares issue, but I've tried self hosting, the CDN and the Sass gem. They display fine on all other browsers but iOS continues to display squares. Even the iOS simulator shows squares.

Icons display fine in all other browsers.

**Comment by tagliala** [comment]
as you know, this is a duplicate of #7770

**Comment by wendelsodres** [comment]
Utilize onde conter a font aplicada.
text-rendering: optimizeLegibility;

ex: 
.icone a:before{
		font-family: 'FontAwesome';
		content: '\f0c9';
		margin-right: 10px;
		font-size: 1.2rem;
		font-weight: 600;
		**text-rendering: optimizeLegibility;**
	}
