### ISSUE TITLE
Icon Request: fa-personal-accident

### ISSUE THREAD

**Issue by nvuhung** [FortAwesome/Font-Awesome#7862]
![download](https://cloud.githubusercontent.com/assets/11483168/11051215/e756cbe4-877f-11e5-887e-4abc773a3e38.png)

**Comment by JeansReal** [comment]
+1

**Comment by aethior** [comment]
Hi @nvuhung,

This icon has been added in v6.1.0.
Check https://fontawesome.com/icons/person-falling

Regards.

cc/ @tagliala
