### ISSUE TITLE
Icon request: fa-lofar

### ISSUE THREAD

**Issue by RedGalaxySW** [FortAwesome/Font-Awesome#7869]
Please add an icon that looks like this:

![lofar](https://cloud.githubusercontent.com/assets/11669132/11075401/59836c3e-87f5-11e5-942f-4e5deda7575e.png)

![lofar](https://www.astron.nl/~heald/test/LOFAR.png)

**Comment by TiXSystem** [comment]
![](https://www.astron.nl/~heald/test/LOFAR.png)

**Comment by TiXSystem** [comment]
![](https://www.astron.nl/~heald/test/LOFAR.png)

**Comment by EgonSpengler** [comment]
Dupe #6741
