### ISSUE TITLE
Icon request: fa-map-marker-o

### ISSUE THREAD

**Issue by cspanring** [FortAwesome/Font-Awesome#7870]
An outlined version of the existing marker would benefit readability of maps with many overlapping markers. Overlapping filled markers are hard to distinguish for users.

Thanks!

**Comment by nureynisow** [comment]
+1

**Comment by tagliala** [comment]
Hi, don't know if you are FA Pro backer, but this icon is available in the commercial version of Font Awesome:

https://fontawesome.com/icons/map-marker-alt?style=regular
https://fontawesome.com/icons/map-marker?style=regular

**Comment by tagliala** [comment]
@cspanring I'm going to reopen this for tracking purposes (the icon is still not part of font awesome free).

If you are not interested anymore in this request, please unsubscribe or close this issue again and I will lock it.

**Comment by cspanring** [comment]
@tagliala sounds good. I'm a FA pro backer and my need is solved with the new icon in the pro release.

**Comment by sensibleworld** [comment]
Closing this as it's available in FA Pro.
