### ISSUE TITLE
Opera Browser Logo Updated

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [FortAwesome/Font-Awesome#7871]
![opera](http://www.underconsideration.com/brandnew/archives/opera_browser_2015_logo_detail.png)

**Comment by tagliala** [comment]
do they have a single color version ?

**Comment by aethior** [comment]
Hi @tagliala,

I have found this logo in two colours: (source: https://www.microsoft.com/es-es/store/apps/opera-mini/9wzdncrdmtk6)

![apps 51715 9007199266462999 89bd62c3-b606-47c3-932b-3c5ea9df6717](https://cloud.githubusercontent.com/assets/1769227/11166569/7c8bcfcc-8b39-11e5-85fa-509460362c20.png)

**Comment by SamBrishes** [comment]
+1

**Comment by davegandy** [comment]
Dug up the company's press kit. Putting something together now.

**Comment by davegandy** [comment]
Updated in 4.4.1-wip branch. Closing.
