### ISSUE TITLE
Icon request: thumbs-middle

### ISSUE THREAD

**Issue by mcp84** [FortAwesome/Font-Awesome#7876]
Hi,

I would like to have an Icon between the two existing thumgs-up and thumbs-down called thumbs-middle ![thumbs-middle](https://cloud.githubusercontent.com/assets/12746364/11117769/dac48eca-893c-11e5-99c5-5b03df9a170d.png)

When something or someone was not good enough to get a thumbs-up but even so not bad enough to get a thumbs-down.

Regards

**Comment by benwa** [comment]
You can add the `fa-rotate-270` class to the `fa-thumbs-down` icon to achieve what you're looking for at this moment.  See http://fortawesome.github.io/Font-Awesome/examples/#rotated-flipped for more.

![image](https://cloud.githubusercontent.com/assets/1351571/11146725/c64e4632-89de-11e5-836c-0712711fe775.png)

**Comment by mcp84** [comment]
Didn't know that this was possible. This will do the trick. Thank you.
