### ISSUE TITLE
Golden plus

### ISSUE THREAD

**Issue by MatthewGreg** [FortAwesome/Font-Awesome#7878]
A simple plus like this one: http://www.gamepointsnow.com/blog/wp-content/uploads/2013/06/ps_0.gif.jpg, there are a couple of pluses (what a pun :D), and i don't know if changing color is possible, but if it is, that would be enough, if not, i would appreciate this one. :)

**Comment by tagliala** [comment]
could you please post a single color example of this icon?

**Comment by MatthewGreg** [comment]
It will be fine in a bright yellow color. :)

**Comment by tagliala** [comment]
sorry I still don't get this request

You can change the color of any icon via css, like normal text

**Comment by MatthewGreg** [comment]
Oh, and how do i do that? :)

**Comment by memetolsen** [comment]
You can change the color of font awesome icons in the same way as you change the font color; with the color property. It can be used as a font which explains the "font" and "awesome" part of Font-Awesome.

**Comment by tagliala** [comment]
@MatthewGreg 

Here it is an example fiddle:  http://jsfiddle.net/tagliala/4ya23yjL/17/

**Comment by MatthewGreg** [comment]
How do i do that?

**Comment by SamBrishes** [comment]
Other Example: http://jsfiddle.net/9dhjg8tn/3/ :D 

Only tested in the latest Chrome and Firefox Browser (Win7). Result should look like this:
![psn](https://cloud.githubusercontent.com/assets/10143149/11155460/eb74a674-8a45-11e5-8a01-7ec244e78cd7.png)

\- Sam

**Comment by MatthewGreg** [comment]
Thanks, but to be honest, i have no idea as to what to do with the code or
any of it. :D

2015-11-13 20:36 GMT+01:00 SamBrishes <notifications@github.com>:

> Other Example: http://jsfiddle.net/9dhjg8tn/3/ :D
>
> Only tested in the latest Chrome and Firefox Browser (Win7). Result should
> look like this:
> [image: psn]
> <https://cloud.githubusercontent.com/assets/10143149/11155460/eb74a674-8a45-11e5-8a01-7ec244e78cd7.png>
>
> - Sam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/7878#issuecomment-156536751>
> .
>



-- 
S pozdravom,
Matúš
http://www.psworld.sk/

**Comment by MatthewGreg** [comment]
I have no idea about how to work with those codes so i need detailed instructions or an icon like every other on Font Awesome. :)

**Comment by tagliala** [comment]
@MatthewGreg the fiddle shows exactly which HTML and CSS you need to achieve that result.

Since this is a support request, I should close this one.

Please consider using stackoverflow if you need HTML/CSS support
