### ISSUE TITLE
Icon request: icon-bucket

### ISSUE THREAD

**Issue by nesv** [FortAwesome/Font-Awesome#788]
Not as a logo for anything like Bitbucket, but just a regular bucket.

**Comment by smorecraft** [comment]
+1

**Comment by dwong** [comment]
+1

**Comment by jstockdale** [comment]
+1

**Comment by tryton-vanmeer** [comment]
+1

**Comment by mutale** [comment]
+1

**Comment by timobehrens** [comment]
+1

**Comment by TiesMB** [comment]
I also would like a bucket icon, something like this: 
![image](https://cloud.githubusercontent.com/assets/27425457/26097670/ac44ba70-3a25-11e7-914b-058884fbdbc4.png)

also, does it matter what people would use it for? Multiple people ask for it...

+1

**Comment by rawsh** [comment]
+1

**Comment by MatiasFMolinari** [comment]
+1

**Comment by tracedog** [comment]
+1

**Comment by jharrisweinberg** [comment]
I use the term in my app about sorting leads into "buckets".  How many leads in this bucket or that bucket, for example.

**Comment by charles121212** [comment]
kfc bucket can make it

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/bucket?s=solid
