### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Hemasiri** [FortAwesome/Font-Awesome#7881]
Hi,
    I want the font awesome icons for event schedule, event sponsors, contact us,faq, registration form

**Comment by tagliala** [comment]
Hi,

please post some examples and try the search feature here: http://fontawesome.io/icons/

Maybe we need more filters, like "event" and "schedule" for the calendar icons. If you want to suggest some filters feel free

![image](https://cloud.githubusercontent.com/assets/556268/11143367/e1e040b0-89f4-11e5-83b0-35b55152760a.png)

contact us: http://fontawesome.io/icon/envelope/
faq: http://fontawesome.io/icon/question-circle/
registration form: http://fontawesome.io/icon/user-plus/


Please also take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by gurisko** [comment]
@Hemasiri 
For others you could probably use:
"contact us": http://fortawesome.github.io/Font-Awesome/icon/envelope-o/
"faq": http://fortawesome.github.io/Font-Awesome/icon/question/
"registration form": http://fontawesome.io/icon/user-plus/
I don't know what to imagine under "event sponsors" tho

**Comment by aethior** [comment]
@tagliala I think you can close here.
