### ISSUE TITLE
Icon Request: fa-kettlebell

### ISSUE THREAD

**Issue by jeffreydrussell** [FortAwesome/Font-Awesome#7883]
I would love a kettlebell icon to represent something for workouts in our fitness app. Thanks for everything you do!

![27389-200](https://cloud.githubusercontent.com/assets/1117729/11152083/cc1b8f5c-89ed-11e5-951e-286898c80ff1.png)

**Comment by tagliala** [comment]
Duplicate of #3845, please +1 that request and post there your example
