### ISSUE TITLE
Recomendation: which icon for about us page?

### ISSUE THREAD

**Issue by kenerly** [FortAwesome/Font-Awesome#7888]
What FA Icon would be good for a About Us page?

Thanks

**Comment by tagliala** [comment]
Maybe:
http://fontawesome.io/icon/info-circle/
http://fontawesome.io/icon/building/
http://fontawesome.io/icon/users/

**Comment by kenerly** [comment]
Thank you, the info-circle will work perfect.

**Comment by tagliala** [comment]
you're welcome, closing here
