### ISSUE TITLE
Icon request: icon-key-modern (icon-cut-key)

### ISSUE THREAD

**Issue by pale2hall** [FortAwesome/Font-Awesome#789]
It would be awesome if there were a more modern looking key.  While I really like the key included, I didn't instantly recognize it, and I think it may be that way for many younger generations.

**Comment by tomhv** [comment]
+1

**Comment by ksega** [comment]
+1

**Comment by cmtatro85** [comment]
+1

**Comment by pkoenders** [comment]
+1

**Comment by TPXP** [comment]
+1 , FontAwesome is great, but the key does not render as nicely as the one included in Black Tie (for example) would !

**Comment by TimS-** [comment]
+1   They key sucks. Tried flipping and rotating out of desperation but sill looks out of place sat next to text and doesn't really represent what people commonly use as a key in day-to-day life

**Comment by TommyTheBlackbird** [comment]
+1 for a modern key icon for password inputs

**Comment by koup** [comment]
+1

**Comment by skrivanos** [comment]
+1

**Comment by ArthurHoaro** [comment]
+1

**Comment by cherrador** [comment]
+1

**Comment by brantwedel** [comment]
+1000

**Comment by javierquevedo** [comment]
+1

**Comment by akalongman** [comment]
+1000

**Comment by michaeljberry** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by vHeemstra** [comment]
+1

**Comment by Dokioki** [comment]
+1

**Comment by Crissov** [comment]
- 🔑 [U+1F511](http://emojipedia.org/key/) Unicode emoji #222 
- 🗝 [U+1F5DD](http://emojipedia.org/old-key/)
- 🔐 [U+1F510](http://emojipedia.org/closed-lock-with-key/)

**Comment by MacGros** [comment]
+1
https://camo.githubusercontent.com/68cfb3317a69ec8385274675c55195437be5d7fb/687474703a2f2f7777772e7761727769636b73686972652d73656375726974792e636f6d2f696d616765732f6b65792e706e67

**Comment by fjeddy** [comment]
I use a skeleton key every single day @pale2hall, that you've chosen to secure your belongings with digital hackable keys, does not mean the majority has and will.

The fact is that more people use a skeleton key then people who don't, it's like a black suit. If you don't recognize the key in FontAwesome as a key, then it's you there is something seriously wrong with, not the icon.

**Comment by pale2hall** [comment]
@fjeddy I didn't even use the phrase Skeleton Key in my original post.  
This was the key when I proposed this change.
![image](https://user-images.githubusercontent.com/1081058/43401208-879a00fa-93dd-11e8-9ce3-8f943196dada.png)

That is an antique key.

Since then it's been changed:
![image](https://user-images.githubusercontent.com/1081058/43401295-c68b241a-93dd-11e8-8ae1-ac2f47f4dfe2.png)

This issue should be locked anyway. (pun slightly intended)

**Comment by DSwissK** [comment]
@davegandy close the thread ?

**Comment by tagliala** [comment]
@DSwissK thanks for the heads-up, closing here
