### ISSUE TITLE
Release notes date

### ISSUE THREAD

**Issue by migig** [FortAwesome/Font-Awesome#7891]
I often visit the site, and visit the release notes to see what's new. I'd like to know when the the latest release was released, to decide whether to upgrade.

All there is is a version number - there should also be a date.

(Yes, there are automated ways to do this, but the date should be there. My build environment is not the issue here.)

**Comment by tagliala** [comment]
Take a look here: https://github.com/FortAwesome/Font-Awesome/releases

**Comment by migig** [comment]
Okay that's a good idea, I didn't think of that. I always visited the project release page and checked there.

Good enough I guess! :smiley:
