### ISSUE TITLE
Icon Request: fa-laser-beam

### ISSUE THREAD

**Issue by sijpesteijn** [FortAwesome/Font-Awesome#7894]
![laserbeam](https://cloud.githubusercontent.com/assets/1381915/11193680/54959aa0-8ca8-11e5-93c1-8ac195f865ac.png)

I'm writing a laser animation program. I really dig font awesome and I only like to include your set.

regards, Gijs

**Comment by sijpesteijn** [comment]
Hi, I was wondering when this icon would be available in a release?

**Comment by sijpesteijn** [comment]
Still curious.....:)

**Comment by sijpesteijn** [comment]
Any news. It has been over a year now. Please let me know if I can expect it soon or not at all. Thank you

**Comment by davidkuhta** [comment]
+1

**Comment by RafaelDeJongh** [comment]
Why hasn't this been included yet, there's no close to any icon resembling laser or cutting (or laser cutting) so it's quite a shame... currently using Strike Through but that doesn't really make sense out of context.

**Comment by sijpesteijn** [comment]
Yeah why not?

**Comment by danrichards** [comment]
I would also like this. My team is currently using an SVG graphic we made ourselves to annotate laser engraved products. It could be improved upon.

![laser-icon-transparent](https://user-images.githubusercontent.com/470255/44430364-6be2af00-a568-11e8-9fde-a2a169d942b0.png)

**Comment by danrichards** [comment]
+1

**Comment by Warl0rd30** [comment]
2019 and still no icon. Why???

**Comment by danrichards** [comment]
https://imgur.com/gallery/1fJ5t

We'll get icons with frickin' laser beams, just like Dr. Evil eventually did.

**Comment by marinetg** [comment]
+1 for this. Really need it for a new client website.

**Comment by loicland** [comment]
+1 from 2024

**Comment by loicland** [comment]
For those in need:

```
\newcommand{\faLaser}
{\begin{tikzpicture}[scale=0.1]
    \foreach \angle in {0, 30, ..., 360}
        \draw[black, thick] (0,0) -- (\angle:1.2);
    \draw[black, thick] (0,0) -- (2.5,0);
\end{tikzpicture}}
```

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it’s a duplicate of, or shares too much similarity, with [this request](https://github.com/FortAwesome/Font-Awesome/issues/9890).
