### ISSUE TITLE
fa-minus-circle cut off

### ISSUE THREAD

**Issue by kevel** [FortAwesome/Font-Awesome#7897]
Hi,
Icon fa-minus-circle cut off at bottom.
Browsers: IE11 and Firefox 42.0
Font size: 20px.

http://plnkr.co/edit/JhOIfg5fyFdbDAmUl99t?p=preview

Thanks.

**Comment by tagliala** [comment]
I cannot confirm on Win10 IE11/FF42, OSX 10.11 FF42

Please note that pixel perfection is guaranteed for non-brand icons at 14px icon size and multiples (14, 28). You should try 21 and check if there is an improvement

I'm going to close this one but feel free to comment

**Comment by kevel** [comment]
Thank you for clarification about pixel perfection.
