### ISSUE TITLE
Icon request: hot-beverage ☕

### ISSUE THREAD

**Issue by G-Driver** [FortAwesome/Font-Awesome#7898]
Example of unicode ☕ (U+2615)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/coffee/ ?

**Comment by G-Driver** [comment]
It's not the same, as you can see the cofee icon doesn't have the 'hot / flames' air above it.

**Comment by MVcodeartbr** [comment]
a alt version +1

**Comment by Bana0615** [comment]
+1

**Comment by yoepus** [comment]
+1 'hot flames' are fun

**Comment by wrunkel** [comment]
Hi guys,

i am new to open source projekts and dont really get the whole PR thing so far so please dont flame me to hard if i am doing something wrong hear.
I saw that a lot of guy's posted icon icon designs in the comment section so i thought i'am going to do the same.

So i drew a quick design for a hot beverage with 'hot flames' ...

![coffe_mug](https://user-images.githubusercontent.com/29057144/36345842-f3ed0610-1432-11e8-8dc3-7f79144c9baa.png)

So what do you think?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/mug-hot?style=solid
