### ISSUE TITLE
Icon Request: Icon-china Icon-Russia Icon-US Icon-UK

### ISSUE THREAD

**Issue by VonCruz** [FortAwesome/Font-Awesome#7899]
Requesting icons for monochromatic flags of countries, organizations, etc.
I'm in need of China, Russia, US, UK flag icons.

Any idea if going to be available and when?

Cheers!
M.

**Comment by tagliala** [comment]
Sorry, I need to close this one

UK: #4735
USA: #1336

please consider an svg alternative at the moment
