### ISSUE TITLE
Icon Request: fa-pharmacy

### ISSUE THREAD

**Issue by MadsCastle** [FortAwesome/Font-Awesome#7901]
I work in a hospital and need a graphic to request prescriptions for the pharmacy Department. The international symbol for a pharmacy would be useful
![pharmacy](https://cloud.githubusercontent.com/assets/15893535/11217504/8a839cf2-8d48-11e5-96e2-a484aa951468.gif)

**Comment by tagliala** [comment]
hmm...

I don't know what is the exact international symbol, but I have: #768, #6410 and #2009.

https://en.wikipedia.org/wiki/Pharmacy#Symbols

**Comment by sensibleworld** [comment]
We now have a pharmacy category: https://fontawesome.com/icons?d=gallery&c=pharmacy
