### ISSUE TITLE
Icon Request: fa-directions

### ISSUE THREAD

**Issue by andraskende** [FortAwesome/Font-Awesome#7906]
Would like to request a driving directions icon, something like:

![ic_directions_black_24dp_2x](https://cloud.githubusercontent.com/assets/23754/11223454/d3f4cf10-8d24-11e5-8d96-147cf604ce03.png)
https://www.google.com/design/icons/#ic_directions

Thank you,
Andras

**Comment by tagliala** [comment]
Leaving this open, but I think there is a duplicate

**Comment by bradgenereux** [comment]
+1

**Comment by Souldat** [comment]
+1

**Comment by aethior** [comment]
Hi @andraskende,

This icon was added in v5.2.0.
Check https://fontawesome.com/icons/diamond-turn-right

Regards.

cc/ @tagliala
