### ISSUE TITLE
Improve Release notes (proper changelog)

### ISSUE THREAD

**Issue by knotmeg** [FortAwesome/Font-Awesome#7908]
We recently updated from `4.2.0` to `4.4.0` and we didn't know there was a file extension change to `*.woff2` and it wreaked some havoc with CORS issues. We didn't know that was going to happen and we had to scramble last minute and found out after the fact.

Just wondering if detailed changes can be made in the release notes?

**Comment by Psykoral** [comment]
:+1: agreed!

**Comment by tagliala** [comment]
Hi,

https://github.com/FortAwesome/Font-Awesome#changelog

Take a look at the 4.3.0 milestone

Hope it helps

**Comment by knotmeg** [comment]
That helps, but I'm looking for a more of a summarized bullet list of what exactly is changed rather than a Git issues list that I have to comb through to find out what happened. 

CanJS has a good example:
https://github.com/canjs/canjs/blob/master/changelog.md

**Comment by tagliala** [comment]
Labeling as a doc feature for 5.0.0

**Comment by alecpl** [comment]
Any chance to see changelog for 5.x releases?

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md
