### ISSUE TITLE
Unable To View Font In IE

### ISSUE THREAD

**Issue by longo12** [FortAwesome/Font-Awesome#7911]
Hi, I have a website using Font Awesome, the font is fine when viewed with Chrome, Firefox, Edge etc but when viewed using any form of IE the font is not displayed, not even the square boxes.
I initially thought I had an issue with my site so headed over to the Font Awesome site and it was the same.

Screenshot below viewed with IE

![untitled](https://cloud.githubusercontent.com/assets/15906472/11239422/ca399888-8de3-11e5-8151-c84b58d8f422.png)

Screenshot below viewed with Edge

![untitled2](https://cloud.githubusercontent.com/assets/15906472/11242496/f9a0b7da-8df9-11e5-9b3b-23ffca286cde.png)

The IE console is showing these errors

![untitled1](https://cloud.githubusercontent.com/assets/15906472/11240929/67a1601a-8dee-11e5-95b6-baba50f7290a.png)

I'm guessing this may be a local IE setting? Any thoughts would be appreciated

**Comment by longo12** [comment]
![untitled1](https://cloud.githubusercontent.com/assets/15906472/11239518/71f589e2-8de4-11e5-8d1f-34f9c5329f5a.png)

Any thoughts would be appreciated.

**Comment by caduvieira** [comment]
Can you try this? http://stackoverflow.com/questions/16157028/css3111-font-face-encountered-unknown-error-from-web-server-works-normally

**Comment by longo12** [comment]
Thanks for the reply but I don't think you quite understand the issue, I have no control over Font Awesome's website so can't change their CSS.

**Comment by caduvieira** [comment]
You could use Developer Tools and change the CSS

**Comment by longo12** [comment]
Hmm, not sure if you're genuinely missing the point or you're trying to be funny, either way please stop leaving unhelpful comments.

**Comment by caduvieira** [comment]
[How to use F12 Developer Tools to Debug your Webpages](https://msdn.microsoft.com/en-us/library/gg589507(v=vs.85).aspx)

**Comment by tagliala** [comment]
I cannot confirm, everything is fine here with IE8/IE9/IE11/Edge

Please check your local machine

Closing here

**Comment by longo12** [comment]
What a strange forum this is, I'm assuming you missed the last sentence in my post

"I'm guessing this may be a local IE setting? Any thoughts would be appreciated"

Which means any help on settings within IE or any thoughts in general on this issue would be helpful as I've no clue. 
Do not dismiss and close my thread with a "Please check your local machine" as this is neither helpful or appreciated.

**Comment by longo12** [comment]
While you were busy closing my thread, no doubt bursting with your own self importance, it clearly didn't occur to you that while you were unable to help others reading this may have been able to.
FYI I tried Stackoverflow and they were about as helpful as you've been here.

**Comment by shranac** [comment]
The answer caduvieira gave solved the problem for my own website.
