### ISSUE TITLE
Icon request: icon-calendar-pencil or icon-calendar-pencil-o

### ISSUE THREAD

**Issue by sloga** [FortAwesome/Font-Awesome#7912]
I would like a "Reserve" or "Reservation" icon using pencil over calendar.

calendar-reserve-o

Thanks!

**Comment by tagliala** [comment]
Refers to #1181 , you will find a solution there

**Comment by tagliala** [comment]
Hi, I'm sorting out old issues 😅 

This icon is available in FA 5 Pro:
https://fontawesome.com/icons/calendar-edit?style=solid

It can also be achieved with transparency and all the goodness by taking advantage of the masking and power transforms features of the SVG Framework.

Demo: https://jsfiddle.net/tagliala/L17f528g/13/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
