### ISSUE TITLE
Icon Request: fa-drone

### ISSUE THREAD

**Issue by surferjsmc** [FortAwesome/Font-Awesome#7915]
Hi ppl! i will be really thankful if someone can make this icon for me, i need it for a web site project.
here are some examples.
best regards and thx in advance!

![drone2-128](https://cloud.githubusercontent.com/assets/15914174/11258136/0638794e-8e57-11e5-8f1d-efab13f9c91f.png)
![flying_drone-512](https://cloud.githubusercontent.com/assets/15914174/11258139/0f678df2-8e57-11e5-9bfc-049646ba6d73.png)
![quad-icon](https://cloud.githubusercontent.com/assets/15914174/11258142/18e41882-8e57-11e5-9bc3-2b984741cee3.jpg)

**Comment by TheChen5** [comment]
Dupe #5446 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
Please also post there your examples

**Comment by surferjsmc** [comment]
another examples
![0a567923d519fc904ecd209f880c0631](https://cloud.githubusercontent.com/assets/15914174/11279841/34387898-8ef3-11e5-9e55-497b2b1fbe8a.jpg)
![1559d41cc2ab0ce2943efdc893a7c158](https://cloud.githubusercontent.com/assets/15914174/11279887/76f82746-8ef3-11e5-89eb-b965242fe738.jpg)

**Comment by nicomputer** [comment]
+1 really need that urgently. Please add at least some icons on the fontawesome pro.
Thank you in advance
Best Regards
Nico
