### ISSUE TITLE
Add grid filter to icon-th

### ISSUE THREAD

**Issue by harobed** [FortAwesome/Font-Awesome#7927]
Icon Request : Apps (grid 3x3 square)

**Comment by harobed** [comment]
Like : http://www.englewoodschools.net/cms/lib8/CO01900647/Centricity/Domain/1009/GoogleAppsIcon.png

**Comment by tagliala** [comment]
Does this one suit your use case? http://fontawesome.io/icon/th/

**Comment by harobed** [comment]
@tagliala yes ! I didn't see it in « Text Editor Icons » list. Thanks

**Comment by tagliala** [comment]
I can provide a "grid" filter for this icon

**Comment by tuxy** [comment]
+1 for ![fa-grid](http://www.englewoodschools.net/cms/lib8/CO01900647/Centricity/Domain/1009/GoogleAppsIcon.png)

It should be called **fa-grid**

**Comment by tagliala** [comment]
@tuxy this request is about a doc filter.

**Comment by gurisko** [comment]
@tagliala I suppose we can close this issue.
