### ISSUE TITLE
Icon Request: fa-handshake

### ISSUE THREAD

**Issue by littletoun** [FortAwesome/Font-Awesome#7928]
![agreement2](https://cloud.githubusercontent.com/assets/15932151/11284164/17d22726-8f11-11e5-923b-9eac55ae7b08.png)

I am going to use it as a symbol of an accredited mediator.
Thank you very much.

**Comment by aethior** [comment]
Hi @littletoun,

This suggestion is duplicate of #878. Please +1 that.

Regards.

**Comment by tagliala** [comment]
@aethior thanks
