### ISSUE TITLE
Icon requests: icon-lang-(language abbreviation here)

### ISSUE THREAD

**Issue by vietqhoang** [FortAwesome/Font-Awesome#7931]
**Include a few use cases for your requested icon. How do you plan on using it?**
An example would be sites which have multiple localizations. Having icons with a visual consistency to represent these languages would be nice.

For example, Japanese is commonly referred with あ as an icon (icon-lang-ja; going with the proposed naming scheme). Other languages are often represented with an equivalent character. A square and non-square form in FA would be great.

**Attach a single color image or two that represent the idea you're going for.**
For [Japanese](http://www.localizingjapan.com/blog/wp-content/uploads/2013/04/mac-osx-108-6.png).

You can refer to any IME (my case the default OS X input sources) to see what icon is used for each language.

**Comment by MVcodeartbr** [comment]
give us some exemples..

**Comment by tagliala** [comment]
Sorry, I have to close this request

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

I suppose this request contains at least 20 icons (> 1%)

https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
