### ISSUE TITLE
Icon Request: fa-section-sign

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#7940]
Request for fa-section as in (Unicode U+00A7) ``&sect;``

![fa-section-sign](http://i.imgur.com/Jlvj6ve.png)

Wikipedia: https://en.wikipedia.org/wiki/Section_sign

**Comment by tagliala** [comment]
duplicate of #1706 , please +1 that request

editing #1706 to include section in the title

closing here

**Comment by Syr3L** [comment]
any chance this will be added?
