### ISSUE TITLE
font awesome not found for blogger

### ISSUE THREAD

**Issue by rahulkumar191988** [FortAwesome/Font-Awesome#7944]
Hello Team,

We also need to icon of blogger on sites , so please also make a icon for blogger.

I am so happy with your work. Keep it up.

Hope to hear you soon!

Thanks in advance,

Rahul Kumar
skype : rahultechsaga
ph no.: +91-9540840140

**Comment by caduvieira** [comment]
dupe of #1088
please +1 that one
