### ISSUE TITLE
Icon Request: fa-docs

### ISSUE THREAD

**Issue by gambetto** [FortAwesome/Font-Awesome#7946]
![image](https://cloud.githubusercontent.com/assets/7262110/11300833/6d8c1632-8f92-11e5-8315-2de5b206575a.png)

**Comment by tagliala** [comment]
Does http://fontawesome.io/icon/files-o/ fit your needs?

**Comment by MVcodeartbr** [comment]
+1 @tagliala this is nice but the required is nice too..
