### ISSUE TITLE
Font Awesmome Icons showing as square boxes after upgrading to 4.4.0

### ISSUE THREAD

**Issue by anandrikka** [FortAwesome/Font-Awesome#7947]
Dear All,

Our project upgraded to fontawesome 4.4.0. All new icons included in the version are displaying as check boxes.

I'm using chrome v46, Firefox v41

I'm trying to display fa-clone icon

**Comment by tagliala** [comment]
take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by anandrikka** [comment]
Replacing older fonts in project fonts folder with fontawesome fonts does the trick.

Thank you very much !!
