### ISSUE TITLE
Icon Request: Converge most Form Control Icon to the same general size.

### ISSUE THREAD

**Issue by RicardoJCMarques** [FortAwesome/Font-Awesome#7950]
I'm using [this nifty CSS trick](http://codepen.io/jamesbarnett/pen/yILjk/) to customize a few checkbox icons.
For my design the combination of checked/unchecked icons that feel more natural is [fa-square-o](http://fortawesome.github.io/Font-Awesome/icon/square-o/) and [fa-check-square](http://fortawesome.github.io/Font-Awesome/icon/check-square/); the problem is when clicked, as the width is slightly off you can see the label shift.

The CSS trick actually already has a small margin we can use for similar situations but I think the problem might be in the sub pixel scale so while removing 1px on the letter-spacing from 10px to 9px helps it doesn't fully correct the effect.

It would be awesome if you guys could redesign them to give more freedom to recombine icons.

Regarding [fa-check-square-o](http://fortawesome.github.io/Font-Awesome/icon/check-square-o/) there isn't much to do and while I don't care much about it at the moment if the width delta to the others was a natural number it would be easy to hide by adjusting the letter-spacing.

Let me know if you guys need anything.

**Comment by acshef** [comment]
Can you not set all the `:before` pseudo-elements to the same width? http://codepen.io/anon/pen/MaRmvm

**Comment by RicardoJCMarques** [comment]
[Holy crap... how did i not think of that -_-](http://imgur.com/jFMsRGE)

**Comment by RicardoJCMarques** [comment]
I reopened it because if I try to use acshef suggestion while the label shifting is gone you can still notice the before and after icons don't really match as the checked is bigger.
http://codepen.io/anon/pen/KdYmYv
In the mean time acshefs suggestion is better but it's not a real solution unfortunately... It really only works with that particular icon pair.

**Comment by tagliala** [comment]
Dup of #6238

**Comment by RicardoJCMarques** [comment]
Whoops, sorry bout that. Should have searched less hastily.
