### ISSUE TITLE
Icon Request: fa-smile

### ISSUE THREAD

**Issue by Gonzalez74** [FortAwesome/Font-Awesome#7953]
Icon request: icon-smile

Why is there the icon-smile-o and there isn't the icon-smile? (black circle with eye and mouth in white)
Thank you.

**Comment by TheChen5** [comment]
Dupe #1681
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by Gonzalez74** [comment]
Sorry, but i don't understand. How can i use that icon? fa fa-smile-alt??

**Comment by TheChen5** [comment]
That is only the name that was given to the request by the user who created it.
It will likely be called `fa fa-smile`.

**Comment by Gonzalez74** [comment]
Sorry, but with that name don´t work!

I have "fa fa-smile-o" and change that to "fa fa-smile" and don't show nothing!
Can you help me?
Thank you.

**Comment by tagliala** [comment]
@Gonzalez74 #1681 is a request like yours :)

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please search to see if your icon request already exists. If a request is found, please +1 that one.

**Comment by TheChen5** [comment]
@Gonzalez74 I think what you mean is that you think `fa fa-smile` is already an icon.
Sadly, it isn't.
That is only a *request* for the icon.
It does not mean that it exists.
