### ISSUE TITLE
Icon request: icon-politics-democrat and icon-politics-gop

### ISSUE THREAD

**Issue by iamlenox** [FortAwesome/Font-Awesome#7954]
Would like to request us political party (democrats and republican aka gop) icons be added to FontAwesome Icons.  I'm a democratic political consultant and we always have a need for political icons for our work and we're not the only consultants / firms that would love to have these added.

![donkey fw](https://cloud.githubusercontent.com/assets/4774401/11322189/de9d8290-90ad-11e5-88eb-534fe712593a.png)

**Comment by TheChen5** [comment]
Dupe #7382 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by dbrighton** [comment]
Me also... tooo..
