### ISSUE TITLE
firefox doesn't display fonts

### ISSUE THREAD

**Issue by partnuz** [FortAwesome/Font-Awesome#7955]
I use newest 4.4.0 fa. Firefox 42 and win7 64bit
I get this message

https://dl.dropboxusercontent.com/u/22284917/Untitled-1.png

**Comment by tagliala** [comment]
Please take a look at our troubleshooting guidelines:

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay attention to https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-developing-my-web-app-locally-file-and-icons-from-cdn-dont-show-up
