### ISSUE TITLE
Icon Request: fa-align-middle-left, fa-align-middle-centre,  fa-align-middle-right, 

### ISSUE THREAD

**Issue by scagood** [FortAwesome/Font-Awesome#7958]
I've had a brief look around for an icon that I can use to specify text align middle centre and middle left I've seen #7252 and #2772 but neither are quite right for this.

fa-align-middle-left: 
![alignmiddleleft](https://cloud.githubusercontent.com/assets/2230835/11328790/3906ab18-9189-11e5-8093-94273f718f69.png)

fa-align-middle-right (or fa-align-middle-left fa-flip-horizontal):
![alignmiddleright](https://cloud.githubusercontent.com/assets/2230835/11328798/53fe998a-9189-11e5-9fc5-910039c008f1.png)

fa-align-middle-centre:
![alignmiddlecenter](https://cloud.githubusercontent.com/assets/2230835/11328800/5b9909d2-9189-11e5-9ed4-097e20aaf86d.png)

The effect I am trying for with my really badly made icons in place:
![170e2554f2fdc6df489e99cca17d5e2a](https://cloud.githubusercontent.com/assets/2230835/11328805/71a145fa-9189-11e5-830b-2d6d1418ec37.png)

**Comment by tagliala** [comment]
Is there any text editor actually using the above icons to represent those alignments?

**Comment by scagood** [comment]
I cant think of somewhere that uses the align middle left/right like that but Excel uses the align middle icon:
![](https://i.gyazo.com/53f75f6b69bbfd8d1a534160d8dd40dd.png)

Also the align middle left/right could just be an alt align left/right (disregarding vertical alignment)

**Comment by jlawton2** [comment]
:thumbsup:
