### ISSUE TITLE
Update Google plus icon

### ISSUE THREAD

**Issue by ekerazha** [FortAwesome/Font-Awesome#7966]
The official Google Plus badge is a circle.
See: https://developers.google.com/%2B/web/badge/#static-badge

**Comment by TheChen5** [comment]
If you want it for a website, you can stack the google-plus and circle icons.
http://fortawesome.github.io/Font-Awesome/examples/#stacked

**Comment by tagliala** [comment]
@ekerazha is right, the official logo should be implemented

(but even with the official logo things will not change, someone will ask for a non official logo e.g.: #1966)

**Comment by ekerazha** [comment]
@tagliala @davegandy Is there a reason why this issue hasn't been worked on for the latest releases?

**Comment by tagliala** [comment]
@ekerazha yes, there is: I forgot of this issue and I didn't reassing it to 4.5.0/4.6.0 milestone, sorry

**Comment by davegandy** [comment]
Added to milestone wip branch. Closing.
