### ISSUE TITLE
Icon Request: Staff person/employee and tech support

### ISSUE THREAD

**Issue by aensley** [FortAwesome/Font-Awesome#797]
Would be good to have an icon for a staff person or employee. Maybe something like `icon-user`, but with a tie to signify an office worker. Other ideas to identify as an employee: name tag, uniform, suit, hat.

Another useful icon would be a tech support person. Maybe the `icon-user` wearing a headset.

**Comment by aslabs** [comment]
+1

What about something like:
https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/worker.png
?

**Comment by sridharspeaks** [comment]
@adrianschmidt +1

**Comment by tagliala** [comment]
please +1 #3397 for a user with tie
