### ISSUE TITLE
v4.5.0 not showing in Packagist

### ISSUE THREAD

**Issue by PHLAK** [FortAwesome/Font-Awesome#7972]
The `fortawesome/font-awesome` package is stuck at v4.4.0 on [Packagist](https://packagist.org/packages/fortawesome/font-awesome).

**Comment by LKay** [comment]
I suppose `package.json`, `component.json` and bower file need to bump the version up.

**Comment by ackernaut** [comment]
Yeah, I was not able to upgrade to 4.5.0 using npm.

**Comment by tagliala** [comment]
I suppose this is caused by #7971

I'm trying to address this asap

**Comment by tagliala** [comment]
Sorry, reopening here

**Comment by tagliala** [comment]
Closing here, let me know if it was fixed

**Comment by thedevsaddam** [comment]
After version 4.4.0 the fonts are not showing, what's the problem in fa-4.5.0?
