### ISSUE TITLE
Icon request: icon-handshake

### ISSUE THREAD

**Issue by lyho** [FortAwesome/Font-Awesome#7975]
Use cases:
_ To show 2 entities is having relationship
_ To show the contract has been signed
_ To show agreement has been agreed

Sample icon: https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/handshake.png

**Comment by coclav** [comment]
+1

**Comment by aethior** [comment]
Hi @lyho,

This suggestion is duplicate of #878. Please +1 that.

Regards.

**Comment by tagliala** [comment]
thanks

closing here
