### ISSUE TITLE
Icon Request: fa-money-alt

### ISSUE THREAD

**Issue by ikruglik** [FortAwesome/Font-Awesome#7977]
Hello,

Previously I was using fa-money with fa-credit-card. In the 4.5.0 release new fa-credit-card-alt icon appeared that I decided to use, however the proportions\size of the new fa-credit-card-alt icon is different from fa-money and they do not look good when placed nearby. Is it possible to add an alternative fa-money-alt icon that has the same shape as fa-credit-card-alt?

![money-card-icons](https://cloud.githubusercontent.com/assets/10399068/11394760/2b5b9050-9378-11e5-8237-a5546bc988ab.png)

Thank you,
Ilya.

**Comment by tagliala** [comment]
Refers to #4418
