### ISSUE TITLE
Icon Request: fa-user-profile

### ISSUE THREAD

**Issue by tdolph** [FortAwesome/Font-Awesome#7978]
It would be "awesome" if next version would include user profile icon.

**Comment by tagliala** [comment]
dup of #5951 , please +1 that request and read throughout comments there

**Comment by tagliala** [comment]
If you have something else in mind please provide an example.

I think http://fontawesome.io/icon/user/ could also represent a profile

**Comment by tdolph** [comment]
It could, but only when user icon is not used anywhere else.

**Comment by tagliala** [comment]
please provide an example
