### ISSUE TITLE
Icon Request: fa-user-register

### ISSUE THREAD

**Issue by tdolph** [FortAwesome/Font-Awesome#7979]
It would be "awesome" if next version would include icon for register buttons and such. Thank you.

**Comment by tagliala** [comment]
Already here: http://fontawesome.io/icon/user-plus/

If you have something else in mind please post an example and I will consider reopening

**Comment by bilalkhan891** [comment]
> Already here: http://fontawesome.io/icon/user-plus/
> 
> If you have something else in mind please post an example and I will consider reopening

user-plus can't be used for register as it is more like to add a user (add as a friend). which of course does not match with register or sign up buttons

**Comment by tagliala** [comment]
@bilalkhan891 if you have something different in mind, please provide an example
