### ISSUE TITLE
Icon request: icon-propeller.

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#798]
I'd like to see an icon screw-propeller. It will be good to use it with icon-spin

**Comment by jonragnarsson** [comment]
I was going to suggest this. Either one general or boat/airplane variants

**Comment by bjornte** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by extrablind** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/fan?style=solid
