### ISSUE TITLE
Icons Request: fa-[item]-thin

### ISSUE THREAD

**Issue by xtiaan3** [FortAwesome/Font-Awesome#7982]
It would be great to see a series of 'thin' icons like the 'times', 'plus', 'check' etc. This would be more consistent with current, modern interface design. Thanks :) 
![thin](https://cloud.githubusercontent.com/assets/16021630/11405986/1b84ae0e-9360-11e5-9912-774ace25145c.jpg)

**Comment by tagliala** [comment]
Sorry but I need to close this request

Please take a look at #1540 #3874 

If you need specific icons in a thin style please open new individual requests or make sure that icons are strictly related

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by xtiaan3** [comment]
Sorry - pretty new to this. Seems like there is a lot of interest in this concept tho. Any plans to produce them?

**Comment by tagliala** [comment]
@xtiaan3 I'm pretty confident that `icon-thin-close` could be considered in the future

I'm not confident in a whole set of ultralight icons, it will require a complete redesign of the font library (refers to #1733)

If your webiste looks better with thin icons, I would consider another set or a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Take also a look at fontawesome black tie: http://blacktie.io/products/light

(note: fontawesome black tie is a commercial font set and I'm not involved in fontawesome black tie)

**Comment by xtiaan3** [comment]
Thanks for the info… :)
