### ISSUE TITLE
Icon Request: fa-boltcm

### ISSUE THREAD

**Issue by PhillippOhlandt** [FortAwesome/Font-Awesome#7983]
Hello,

it would be nice if the [bolt.cm](https://bolt.cm/) logo would be added to font-awesome.

**Comment by tagliala** [comment]
Duplicate of #4845

Please +1 that request

Closing here

**Comment by PhillippOhlandt** [comment]
Ah thanks @tagliala . Not seen that. Will the icons be choosen, based on the +1 ?

**Comment by tagliala** [comment]
@PhillippOhlandt they matters, but they do not guarantee that an icon will be included

Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
