### ISSUE TITLE
fa-amazon

### ISSUE THREAD

**Issue by legalalien37** [FortAwesome/Font-Awesome#7985]
The fa-amazon icon isn't working with my Wordpress theme. The other icons I'm using (Facebook, Twitter, Pinterest, Instagram) are working fine, so I don't think the theme is the issue. This problem seems to occur in all browsers. Website: http://kivrinwilson.com/

**Comment by TheChen5** [comment]
It looks like you need to update `wp-content/themes/zarja/css/font-awesome.css`.

**Comment by legalalien37** [comment]
Thanks. That seems to have brought me one step closer, as it's not just a blank box anymore, but instead of the icon it's showing the icon number. I updated the /fonts folder as well. Not sure what to try next? Is there something else I need to do to update to the newest version? My theme seems to only include the CSS file and the /fonts folder, nothing else.

**Comment by TheChen5** [comment]
On my device, the Amazon icon is showing up.
Windows 8.1 - Google Chrome 47.0.2526.69 beta-m

**Comment by tagliala** [comment]
Closing here

Please check our troubleshooting guide https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting (pay particular attention to point 4)

or consider stackoverflow for support requests

PS: I can see the amazon icon
