### ISSUE TITLE
Icon Request fa-xbox & fa-playstation

### ISSUE THREAD

**Issue by Anarchy396** [FortAwesome/Font-Awesome#7986]
I use FA icons on my forum and I am in need of an Xbox and Playstation icon can you please add these it will be greatly appreciated. 

They should be fairly simple icons to add since they aren't extensive or complicated, examples: http://imgur.com/a/RGv1D

Thanks.

**Comment by TheChen5** [comment]
Dupe #1006 
+1 that
Please :mag:before:heavy_plus_sign:
