### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by zouina** [FortAwesome/Font-Awesome#7991]
Hi 

I have already used your icons on my template for an inventory management application, so I need more icons that are not exist in your list; 

Can you please creat these icons about:
Category
Product
Departement
Store

Thanks for you cooperation

**Comment by tagliala** [comment]
Sorry but I need to close this one

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Attach a single color image or two that represent the idea you're going for.
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

How can we represent a product, a category or a department?

store: (maybe) #1958
