### ISSUE TITLE
Ban user or Block user icon not available

### ISSUE THREAD

**Issue by sahilmanchal** [FortAwesome/Font-Awesome#7993]

**Comment by tagliala** [comment]
sorry, I didn't get this request

could you please clarify?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

**Comment by darrondriver** [comment]
@sahilmanchal Could you use [stacked icons](https://fortawesome.github.io/Font-Awesome/examples/) for this?
```html
<span class="fa-stack fa-lg">
	<i class="fa fa-user fa-stack-1x"></i>
	<i class="fa fa-ban fa-stack-2x"></i>
</span>
```
