### ISSUE TITLE
 icon-[input-output]

### ISSUE THREAD

**Issue by zouina** [FortAwesome/Font-Awesome#7994]
Hi 
Thanks for your answer,
Can you customize this icon [<i class="icon-list-alt"></i> icon-list-alt] to indicate the input and an another to indicate output of articles.

Best regards

**Comment by tagliala** [comment]
could you please provide examples?

**Comment by PeterShaggyNoble** [comment]
Would these suit your needs?
http://fortawesome.github.io/Font-Awesome/icon/indent/
http://fortawesome.github.io/Font-Awesome/icon/outdent/

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
