### ISSUE TITLE
allow to combine two icons turning into one [DO NOT +1 - Idea for a new project]

### ISSUE THREAD

**Issue by mbrenzan** [FortAwesome/Font-Awesome#7996]
Have an editor which allows to combine two existing icons in the gallery, being possible to change the sizes individually (ex: a smaller bar code under greater magnifying glass). In the end this union will become an icon. No need to store custom icons.

**Comment by MVcodeartbr** [comment]
+1

**Comment by tagliala** [comment]
@mbrenzan 
Sorry I didn't get this request, could you please clarify?

**Comment by mbrenzan** [comment]
provide a tool which will use two gallery of predefined icons to create a new icon . you might have a graphic area where she can create your own icon by adding the image of other existing icons .
This custom icon need not be stored in the gallery , just available to the user that created it uses it .
In short, it would be a graphical aera as a simple image editor, which would have access to the gallery of icons to combine them and create a new icon in the way that you see fit.

**Comment by tagliala** [comment]
@mbrenzan thanks, got it

This option was investigated here: #1181

Anyone that would start this project is free to share here.

Leaving this open but do not +1

**Comment by tagliala** [comment]
Rethink. Let's use #1181

**Comment by mbrenzan** [comment]
OK! I had not seen this demand.
thank you
