### ISSUE TITLE
Icon Request: icon-gift-box

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#7998]
too lazy to write something long, needed a gift box.

tks team of fontawsome for awsomes icons.

inspiration: 
![gift-box-icon](https://cloud.githubusercontent.com/assets/3662026/11433076/b6fbd728-949f-11e5-93a4-ba4081738a16.png)
![gift-512](https://cloud.githubusercontent.com/assets/3662026/11433078/b7022182-949f-11e5-8b87-5ad2241fcaf3.png)
![depositphotos_21756913-gift-box-icons](https://cloud.githubusercontent.com/assets/3662026/11433077/b7015aa4-949f-11e5-8a20-4abf9c1bdf7d.jpg)

**Comment by tagliala** [comment]
Already here: http://fontawesome.io/icon/gift/

**Comment by MVcodeartbr** [comment]
May a alt?? fa-gift-alt?

**Comment by tagliala** [comment]
Given that every icon, even icons with alt could have an alternative version, what is the use case?

If you don't like the actual design I can change this request to "enhancement" or `fa-gift-o` (outlined version)
