### ISSUE TITLE
icon request: Help Lib for Nilsen's Heuristics

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#7999]
Could i help? i'm designer..

inspiration:
![emergency-exit-98585_960_720](https://cloud.githubusercontent.com/assets/3662026/11433495/02da002a-94a5-11e5-81c3-76c5d23ac808.png)
![13](https://cloud.githubusercontent.com/assets/3662026/11433494/02d9b0ca-94a5-11e5-8998-fb0e1b4ac7e1.png)
![15-512](https://cloud.githubusercontent.com/assets/3662026/11433496/02dc5f28-94a5-11e5-85ee-740c9d03333d.png)
![240_f_56469296_msay0q8kegqbtty75qnd8ye0gc8ghast](https://cloud.githubusercontent.com/assets/3662026/11433497/02deba5c-94a5-11e5-9b36-d8cf1f1989ff.jpg)
![256-256-0d4b4c3b1288008d5795655e2f96a33f-sitemap](https://cloud.githubusercontent.com/assets/3662026/11433498/02df546c-94a5-11e5-800b-bcdba9cbba77.png)
![44224-200](https://cloud.githubusercontent.com/assets/3662026/11433499/02e30ad0-94a5-11e5-921c-edf2471a2a02.png)
![1395826613845](https://cloud.githubusercontent.com/assets/3662026/11433500/02f7b818-94a5-11e5-836f-c4fece27a403.png)
![exit](https://cloud.githubusercontent.com/assets/3662026/11433501/02faa1ea-94a5-11e5-8f95-052c0211db01.png)
![icon-learn-pdf-3-ways-training-300px](https://cloud.githubusercontent.com/assets/3662026/11433503/02ffa88e-94a5-11e5-907e-795710d67142.png)
![icon-learn-pdf-onsite-training-300px](https://cloud.githubusercontent.com/assets/3662026/11433502/02fddf68-94a5-11e5-9865-666dc3366709.png)
![man349](https://cloud.githubusercontent.com/assets/3662026/11433505/0307fc96-94a5-11e5-9924-89dab62f2b2d.png)
![minicons2-93-128](https://cloud.githubusercontent.com/assets/3662026/11433504/03046c5c-94a5-11e5-86a4-94fa084d2d80.png)
![online-teaching_318-11635](https://cloud.githubusercontent.com/assets/3662026/11433506/03159da6-94a5-11e5-8d29-5700f82a94ba.jpg)
![publicinformationsymbol_emergencyexit svg](https://cloud.githubusercontent.com/assets/3662026/11433507/03165278-94a5-11e5-9daa-56b7aa6a712f.png)
![riaa88gmt](https://cloud.githubusercontent.com/assets/3662026/11433508/031b74e2-94a5-11e5-9566-7b1091e4ac9e.png)
![ring_buoy](https://cloud.githubusercontent.com/assets/3662026/11433509/031e6576-94a5-11e5-805a-7522f0b63b37.png)
![support](https://cloud.githubusercontent.com/assets/3662026/11433510/0322945c-94a5-11e5-8b10-a554aed42971.png)
![training2](https://cloud.githubusercontent.com/assets/3662026/11433511/0326e08e-94a5-11e5-8bd8-150e064336c5.png)
![user-exit-512](https://cloud.githubusercontent.com/assets/3662026/11433512/03316b80-94a5-11e5-8408-f42d2125eef5.png)
![zvfh1](https://cloud.githubusercontent.com/assets/3662026/11433513/0333ac7e-94a5-11e5-9f72-2d8b6a18205e.jpg)

sorry for bad english

**Comment by TheChen5** [comment]
This is too much icons in one request.
Please break them up into separate requests.

**Comment by tagliala** [comment]
and... there are duplicates or icons already implemented

sitemap: http://fontawesome.io/icon/sitemap/

emergency exit: #4785
user with headset: #5586 

Unfortunately you cannot contribute to FA with new icons but you can customize your set: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
