### ISSUE TITLE
icon-save : what's a floppy ?

### ISSUE THREAD

**Issue by kapouer** [FortAwesome/Font-Awesome#800]
I know usb key, hard drive...
CD are used to scare birds in the garden...
What's a floppy ? Do you really "save" things on such a media ?

**Comment by romainbessugesmeusy** [comment]
"Floppy disks are like Jesus. They died to become the icon of saving."
— https://twitter.com/davidnoob/status/321773872682774528

**Comment by sensibleworld** [comment]
In version 6, we've renamed the old `save` icon to be more descriptive as just `floppy-disk` as we don't want to be prescriptive about how an icon is used.
