### ISSUE TITLE
Icon Request: fa-django

### ISSUE THREAD

**Issue by rudyvalencia** [FortAwesome/Font-Awesome#8001]
Hi,

Please consider adding the Django web framework logo to FontAwesome. I have included an image as a suggestion for styling.

As for use cases, one might want to put "Powered by [fa-django-square/fa-django] Django" at the bottom of their Web sites.

Thank you for your consideration.

---------
Rudy Valencia
Humanocentric.

![fa-django](https://cloud.githubusercontent.com/assets/1392728/11438069/888bbede-94af-11e5-8e6d-002b88d94a0d.png)

**Comment by tagliala** [comment]
We have #3805 which is closed and labeled as "wontfix" is this an official logo of django?

**Comment by 153957** [comment]
There does not seem to be an official squarish logo, only the full name 'django'.
More info on the official page: https://www.djangoproject.com/community/logos/

**Comment by rudyvalencia** [comment]
The Web site's favicon is shortened to just "dj".

**Comment by tagliala** [comment]
Don't know what to do. @davegandy ?

**Comment by team-core** [comment]
+1

**Comment by tagliala** [comment]
Closing and locking here, please refer to #3805
