### ISSUE TITLE
icon request: fa-talk-ballons

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8005]
for chat

inspiration
![240_f_56469296_msay0q8kegqbtty75qnd8ye0gc8ghast](https://cloud.githubusercontent.com/assets/3662026/11433497/02deba5c-94a5-11e5-9b36-d8cf1f1989ff.jpg)
![riaa88gmt](https://cloud.githubusercontent.com/assets/3662026/11433508/031b74e2-94a5-11e5-9566-7b1091e4ac9e.png)

**Comment by caduvieira** [comment]
http://fontawesome.io/icon/comments/ ?

**Comment by MVcodeartbr** [comment]
releted but could be a alt version

**Comment by tagliala** [comment]
Sorry, closing here. I need a different use case to justify the alternate version

Closely related to #2790
