### ISSUE TITLE
icon request: accessibility hearing problem

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8009]
inspiration:

![stock-vector-disability-pictogram-flat-icon-mute-isolated-on-white-background-276738353](https://cloud.githubusercontent.com/assets/3662026/11442589/bd07f45e-94fd-11e5-930e-f72e768c4d2d.jpg)

**Comment by caduvieira** [comment]
dupe of #5409
please +1 that one

**Comment by MVcodeartbr** [comment]
sorry
