### ISSUE TITLE
icon request: sign language

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8010]
![sign-p](https://cloud.githubusercontent.com/assets/3662026/11442611/e92a9f1e-94fd-11e5-9d02-1a5250d52949.gif)

**Comment by caduvieira** [comment]
dupe of #2026
please +1 that issue

**Comment by MVcodeartbr** [comment]
whats going on, i'm trying use search in github put isnt showing topics.

sorry
