### ISSUE TITLE
icon request: accessibility pregnant

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8012]
![download](https://cloud.githubusercontent.com/assets/3662026/11442649/4e4baf32-94fe-11e5-8ef2-0f393022ea03.png)
![screenshot 98](https://cloud.githubusercontent.com/assets/3662026/11442662/5c6e66ae-94fe-11e5-8795-8bfce2822f7e.jpg)

**Comment by caduvieira** [comment]
dupe of #1819
please +1 that one
