### ISSUE TITLE
icon request: fa-shoping-backpack

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8014]
inspiration:
![stock-vector-backpack-15837802](https://cloud.githubusercontent.com/assets/3662026/11442784/44f2e1e8-94ff-11e5-881a-d480ee831ec7.jpg)
![stock-vector-backpack-icon-192091580](https://cloud.githubusercontent.com/assets/3662026/11442783/44f29ab2-94ff-11e5-8118-f608c780d0e0.jpg)
![stock-vector-backpack-icon-322610051](https://cloud.githubusercontent.com/assets/3662026/11442785/44f8aede-94ff-11e5-8c3f-73fb8df0d5af.jpg)

**Comment by tagliala** [comment]
dup of #4992 , please +1 that request

closing here
