### ISSUE TITLE
icon request: fa-mailchimp-monkey

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8015]
![freddie-opengraph](https://cloud.githubusercontent.com/assets/3662026/11442942/731c8500-9500-11e5-9d80-c3007918d871.png)

**Comment by caduvieira** [comment]
dupe of #3379
please +1 that one

**Comment by MVcodeartbr** [comment]
whats going on? the search cant find things.

**Comment by tagliala** [comment]
sometimes searching is hard, try here: https://github.com/FortAwesome/Font-Awesome/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mailchimp
