### ISSUE TITLE
icon request: star wars

### ISSUE THREAD

**Issue by MVcodeartbr** [FortAwesome/Font-Awesome#8016]
![starwars-700x525](https://cloud.githubusercontent.com/assets/3662026/11443173/dab80b52-9501-11e5-92b0-a48c3417733d.png)

**Comment by MVcodeartbr** [comment]
related #3772

**Comment by tagliala** [comment]
Sorry, closing here

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by AndreLGava** [comment]
https://github.com/AndreLGava/star-wars-font
