### ISSUE TITLE
Icon Request: fa-gel

### ISSUE THREAD

**Issue by georgedaqu** [FortAwesome/Font-Awesome#8036]
Hello,

I am a Georgian web designer and I often have trouble with Georgian currency new symbol. It has already been accepted by Unicode and Microsoft added it to Segoe UI font (please see screenshot attachment) but other fonts don't have yet.

ISO 4217 code: GEL

Please add Georgian Lari currency symbol to Font Awesome. I always use Font Awesome creating websites.

Here is a link on Wikipedia and you can take SVG vector version from it https://goo.gl/DUXdZC

Best Regards

![segoe-ui-gel](https://cloud.githubusercontent.com/assets/16066718/11456171/2154b374-9699-11e5-9ecf-61cdc54dc29a.png)

**Comment by tagliala** [comment]
Dup of #3973, please +1 that request

closing here
