### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by TheColorRed** [FortAwesome/Font-Awesome#8039]
![dribbble_icon_fs2](https://cloud.githubusercontent.com/assets/1571806/11460142/bc64f622-96ac-11e5-866e-d4898979f117.jpg)

![funct](https://cloud.githubusercontent.com/assets/1571806/11460145/c19230e2-96ac-11e5-950f-6c0794ab723d.png)

**Comment by MVcodeartbr** [comment]
+1

**Comment by MVcodeartbr** [comment]
releted #2675 tou could close and say +1 there
