### ISSUE TITLE
Icon request: icon-question-circle

### ISSUE THREAD

**Issue by AaronTraas** [FortAwesome/Font-Awesome#804]
I'd like to request the creation of icon-question-circle as a complement to icon-question-sign, similar to that of icon-ok-sign and icon-ok-circle.

**Comment by lizzzp1** [comment]
@davegandy is this available as an svg?

**Comment by tagliala** [comment]
@lizzzp1 it is available in both regular and solid style at https://fontawesome.com/icons/question-circle?style=solid

If you need the individual svg file, please click on the download button

![image](https://user-images.githubusercontent.com/556268/50650693-7e8edb00-0f81-11e9-8387-ef632f584060.png)

**Comment by lizzzp1** [comment]
@tagliala thank you! I'm using the pro repo and didn't see this available.

**Comment by lizzzp1** [comment]
@tagliala Oh wow. Didn't know you could do that 🙃
I see it now, thanks again!
