### ISSUE TITLE
Icon Request: fa-minecraft

### ISSUE THREAD

**Issue by DoraKlikOpDora** [FortAwesome/Font-Awesome#8049]
![Image of Minecraft](http://images.wikia.com/yogbox/images/d/dd/Minecraft_Block.svg)

**Comment by tagliala** [comment]
dup of #1776 , please +1 that request

closing here

**Comment by frispete** [comment]
I cannot find the icons mentioned in #1776, may I ask, what's the license state of this one?

**Comment by tagliala** [comment]
@frispete please take a look at our [Icon Leaderboard FAQs](https://fontawesome.com/community/leaderboard/new#faqs), they contain a lot of information about how requests work
