### ISSUE TITLE
Icon request: icon-pencil-circle

### ISSUE THREAD

**Issue by patrick70Hex** [FortAwesome/Font-Awesome#8051]
Hello and thank for those fonts.
I'd need the pencil circle font. I'm using it in a multitude of datagrids/listboxes in conjunction with add-circle (to add an element), times-circle (to delete an element) and the pencil to edit an element.
Thank you in advance
Patrick

**Comment by tagliala** [comment]
dup of #5512, please +1 that request

please also consider stacking: http://fontawesome.io/examples/#stacked or custom css: #1553
