### ISSUE TITLE
Icon request: icon-dropshots

### ISSUE THREAD

**Issue by djanesch** [FortAwesome/Font-Awesome#8058]
an icon which represenst the websites identity: http://dropshots.com/
would advice to use an icon like the faveicon on the site.
![dropshots_dark_over](https://cloud.githubusercontent.com/assets/16105473/11511214/16b4f8a4-9868-11e5-97c5-2edfbe04d1de.jpg)

thanks for your work by the way :-)

**Comment by aethior** [comment]
>Dropshots shut down as of December 31, 2020
Shutting Dropshots down was a difficult decision but the market dynamics in the photo sharing space made it impossible to compete against the much larger sites. We truly appreciate your patronage over the years and hope to see you again somewhere else on the web. ([more info](https://www.dropshots.com/))

cc/ @tagliala
