### ISSUE TITLE
Icon request: icon-patreon

### ISSUE THREAD

**Issue by pahimar** [FortAwesome/Font-Awesome#8065]
An icon which represents the websites identity: https://www.patreon.com/
Would be used as an icon for social links on websites
Link to svg for the logo: https://commons.wikimedia.org/wiki/File:Patreon_logo.svg

![patreon_navigation_logo_mini_orange](https://cloud.githubusercontent.com/assets/1450090/11539585/cf519d62-98f5-11e5-857c-dcfb38069f2b.png)

Thank you in advance!

**Comment by tagliala** [comment]
Duplicate of #3257, please +1 that request

closing here

**Comment by pahimar** [comment]
My bad! My mistake for not checking before creating - will do!
