### ISSUE TITLE
Icon requests - Holiday Icons

### ISSUE THREAD

**Issue by xiaoerge** [FortAwesome/Font-Awesome#8068]
Add icons for common holiday characters like Santa, Easter Rabbit, etc.

**Comment by TheChen5** [comment]
Santa dupe #8019 
Rabbit dupe #6085
+1 those
Please :mag:before:heavy_plus_sign:

This is a broad request.
Please break this up into specific requests.

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
