### ISSUE TITLE
Icon requests: Motion picture rating icons

### ISSUE THREAD

**Issue by mester93** [FortAwesome/Font-Awesome#8071]
Hi! :)
Please add this motion picture rating icons to the library. Must be kept in color. This are used to classification of the films, and tv shows. Thank you! :)

![32px-16_icon_tv_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555188/080b77e8-99a7-11e5-8e21-ff62039e8d39.png)
![32px-18_icon_tv_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555189/080ccd00-99a7-11e5-9f86-5f4c6bb75a43.png)
![32px-6_icon_tv_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555191/08158bfc-99a7-11e5-9e31-7c948d0e2493.png)
![32px-12_icon_tv_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555190/080f7ea6-99a7-11e5-9ddd-2f67856cd6af.png)
![kn_icon_b_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555250/8b31a4ee-99a7-11e5-9e08-f32187e7b229.png)
![x_icon_b_ hungary svg](https://cloud.githubusercontent.com/assets/8291390/11555251/8b348506-99a7-11e5-870c-f3e30d55c57e.png)

**Comment by ryankane** [comment]
Fonts cannot contain multiple colors...

> * Attach a single color image or two that represent the idea you're going for.

See: [Requesting new icons][1]

  [1]: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by aethior** [comment]
You only need to use `fa-circle-o` icon and text. Example: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by tagliala** [comment]
Closely related to #6951

**Comment by mester93** [comment]
But this icons has two colors...

The problem is that this icons are law based, and it musn't be used in other modified ways. If it can be a future option, please include in updates because it could be helpfull.

**Comment by tagliala** [comment]
@mester93 font icons are constrained to single color*, if you need multiple color icons you can:

* Go for SVG
* Use the stack feature, as suggested by @aethior 

_________
* I know about this: http://pixelambacht.nl/2014/multicolor-fonts

**Comment by ryankane** [comment]
@mester93 You can simple stack them: http://jsfiddle.net/MrPolywhirl/25bfvxgo/

```html
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle-thin fa-stack-2x yellow"></i>
  <i class="fa fa-stack-1x text">16</i>
</span>
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle-thin fa-stack-2x red"></i>
  <i class="fa fa-stack-1x text">18</i>
</span>
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle-thin fa-stack-2x yellow"></i>
  <i class="fa fa-stack-1x text">6</i>
</span>
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle-thin fa-stack-2x yellow"></i>
  <i class="fa fa-stack-1x text">12</i>
</span>
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle fa-stack-2x green"></i>
  <i class="fa fa-circle-thin fa-stack-15x"></i>
</span>
<span class="icon fa-stack fa-2x">
  <i class="fa fa-circle fa-stack-2x red"></i>
  <i class="fa fa-circle-thin fa-stack-15x"></i>
  <i class="fa fa-stack-1x text">&#x2715;</i>
</span>
```

```css
.text {
  font-family: arial;
  font-weight: bold;
}
.yellow {
  color: #F7ED21;
}
.green {
  color: #80FF00;
}
.red {
  color: #EC3C4A;
}
.fa-stack-15x {
  font-size: 1.6em;
  line-height: 1.25em;
  position: absolute;
  left: 0;
  width: 100%;
  text-align: center;
}
```

**Comment by mester93** [comment]
Great! Thank you! :)

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
