### ISSUE TITLE
music instruments icon

### ISSUE THREAD

**Issue by bioplus** [FortAwesome/Font-Awesome#8073]
can you provide Music instilment like iPod kind of icon it will be helpful..

**Comment by tagliala** [comment]
ipod: duplicate of #3296, please +1 that request

About comprehensive sets of icon like "musical instruments": https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

closing here
