### ISSUE TITLE
Icon request: sports/leisure(group)

### ISSUE THREAD

**Issue by nippy58** [FortAwesome/Font-Awesome#8074]
Hi 
Would be really useful if you could include some icons that are sports related
fa-sport-swimmer
fa-sport-racket
fa-sport-football
fa-sport-rugbyball
fa-sport-soccerball
fa-sport-runner
fa-sport-sneakers
Other than that - brilliant work guys!

**Comment by tagliala** [comment]
Sorry, can't keep this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
