### ISSUE TITLE
Icon request: icon-segmentfault

### ISSUE THREAD

**Issue by Integ** [FortAwesome/Font-Awesome#8075]
[SegmentFault](http://sf.gg) is the biggest developer's Q&A community in China.
Many SegmentFault users want to use this icon in their own blogs.
With this icon they can easily link to their information at Segmentfault.

![256](https://cloud.githubusercontent.com/assets/1772687/11560700/497bcf06-99fd-11e5-90c4-50c7621bded3.png)

**Comment by fenbox** [comment]
here is the svg file 
[256.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/53439/256.svg.zip)
