### ISSUE TITLE
Update fa-jsfiddle

### ISSUE THREAD

**Issue by PeterShaggyNoble** [FortAwesome/Font-Awesome#8076]
JSFiddle has a new logo: http://jsfiddle.net/img/logo.png

~~As they still use the old one in places themselves (e.g., favicon), I'd suggest the creation of a new icon featuring the new logo rather than an overwrite of the existing one.~~

**Comment by ryankane** [comment]
# fa-jsfiddle-o

Here's a rough outline...

![Uploading image.png…](http://i.imgur.com/GH3PEKM.png)

**Comment by PeterShaggyNoble** [comment]
Update: They've now replaced their favicon as well so this should replace fa-jsfiddle.

The old icon could be "archived" as fa-jsfiddle-alt.

**Comment by tagliala** [comment]
Apparently we need a 4.6.1, let's check if Dave could do this

**Comment by tagliala** [comment]
Cannot find a proper .svg logo

This is the old one: http://doc.jsfiddle.net/meta/downloads.html#logos

**Comment by davegandy** [comment]
It looks like this has not been officially updated yet, otherwise we would put it in. Holding off to 5.0.0.

**Comment by tagliala** [comment]
waiting for feedback from jsfiddle

**Comment by ryankane** [comment]
I updated [my previous comment][1] with a vector that I created from the official Twitter page for JSFiddle. It is as close as you can get.

  [1]: https://github.com/FortAwesome/Font-Awesome/issues/8076#issuecomment-161973507

**Comment by tagliala** [comment]
still no official logo, I will not assign this to 4.7.0.

@ryankane thanks for your vector, but AFAIK Dave prefers to import logos as they are

Also, they didn't answer my email sent on April, 26th

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes
