### ISSUE TITLE
Icon Request: fa-guitar

### ISSUE THREAD

**Issue by br-renatolima** [FortAwesome/Font-Awesome#8077]
Please, make an acoustic and eletric guitar icon, as well every instrument.
Lot of thanks!

**Comment by TheChen5** [comment]
Dupe #5059
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by ryankane** [comment]
@br-renatolima Here, I whipped these up...

# fa-guitar-acoustic-o

![fa-guitar-acoustic-o](http://i.imgur.com/4rNOknH.png)

# fa-guitar-acoustic

![fa-guitar-acoustic](http://i.imgur.com/XxnLc3M.png)

# fa-guitar-electric-o

![fa-guitar-electric-o](http://i.imgur.com/6eCnvQe.png)

# fa-guitar-electric

![fa-guitar-electric](http://i.imgur.com/4XbaFCX.png)

**Comment by TheChen5** [comment]
@ryankane As this request is a duplicate of #5059, please post your example there.

**Comment by ryankane** [comment]
@TheChen5 OK, thanks.
