### ISSUE TITLE
downloadable font: rejected by sanitizer 

### ISSUE THREAD

**Issue by africanw** [FortAwesome/Font-Awesome#8078]
Hi,

Been using the fonts for a while but yesterday I upgraded from 4.2 to 4.5 and noticed in firefoxs console an error appears which did not before. If I put 4.2 back the error does not show in firefox.

error:
downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: https://reports3.wagtailanalytics.com/css/foaw4.5/fonts/fontawesome-webfont.woff2
	

@font-face {
  font-family: "FontAwesome";
  font-style: normal;
  font-weight: ...

	
font-aw...min.css (line 4, col 14)

**Comment by ryankane** [comment]
Apparently you get this issue in Firefox is you run out of memory.

> ## Mozilla Support

> ### [Error: downloadable font: rejected by sanitizer](https://support.mozilla.org/en-US/questions/913498)

> #### Chosen Solution

> You get this error if you run out of memory when loading the fontfile or if there is something wrong with the layout (contents) of the fontfile. This is a protection against bad or malicious font files. It is probably possible to disable the sanitizer by setting the pref gfx.downloadable_fonts.sanitize to false in about:config but then you are no longer protected. Use at your own risk. Do not blame Mozilla if you are infected with malware.

## Side note...

You can embed code like so...

```sh
 | ```css
 | @font-face {
 |     font-family: "FontAwesome";
 |     font-style: normal;
 |     font-weight: ...
 | }
 | ```
```

<sub>_**Note:** Ignore the `|` (pipes) in the markdown..._</sub>

---

Which results in:

```css
@font-face {
    font-family: "FontAwesome";
    font-style: normal;
    font-weight: ...
}
```

**Comment by africanw** [comment]
but don't get the error if I use 4.2. I also upgraded Firefox to the latest version and restart it and same error exists.

**Comment by ryankane** [comment]
Have you checked out:

http://stackoverflow.com/questions/11072655/firefox-font-face-fail-with-fontawesome

Your font paths may be single-quotes as one of the answers in that post suggests.

What does your url look like for the src of your font face?

**Comment by tagliala** [comment]
Sorry, cannot confirm.

> Been using the fonts for a while but yesterday I upgraded from 4.2 to 4.5 and noticed in firefoxs console an error appears which did not before. If I put 4.2 back the error does not show in firefox.

Self hosting? CDN? 4.2.0 didn't support woff2, which was introduced in 4.3.0. maybe there is something to do with mime types #4261

Feel free to discuss this issue but I'm going to close this one

**Comment by africanw** [comment]
Ah ok I got it, your comment about woff2 got me looking into mime types and the webserver was setup for woff only so added woff2 and all good now.

Thanks

**Comment by tagliala** [comment]
you're welcome, glad you solved
