### ISSUE TITLE
Icon request: icon-stack

### ISSUE THREAD

**Issue by rokuehne** [FortAwesome/Font-Awesome#8086]
An icon which represents a stack would be nice:
e.g. https://cdn3.iconfinder.com/data/icons/glypho-generic-icons/64/layers-512.png

or a icon-paper-stack:
e.g. https://cdn3.iconfinder.com/data/icons/print-icons/512/Stack_of_Paper-512.png

**Comment by ryankane** [comment]
Embedded images...

![](https://cdn3.iconfinder.com/data/icons/glypho-generic-icons/64/layers-512.png)

![fa-paper-stack](https://cdn3.iconfinder.com/data/icons/print-icons/512/Stack_of_Paper-512.png)

**Comment by tagliala** [comment]
Duplicate of #1179, please +1 that request

closing here
