### ISSUE TITLE
Icon request: codeigniter

### ISSUE THREAD

**Issue by jim-parry** [FortAwesome/Font-Awesome#8087]
CodeIgniter is an open source PHP web framework.
The CodeIgniter logo is a registered trademark owned by the British Columbia Institute of Technology, and made available to developers under the MIT license for use in their projects.
A font-awesome icon would make it easier to use.
![ci-logo-big](https://cloud.githubusercontent.com/assets/3203951/11592764/587f5dc6-9a55-11e5-8b4d-d64457e0c00a.png)
![ci-logo](https://cloud.githubusercontent.com/assets/3203951/11592768/5f46bec4-9a55-11e5-925f-1179b1268b7d.png)

**Comment by tagliala** [comment]
duplicate of #4316, please +1 that request

closing here

**Comment by InsiteFX** [comment]
I have made a request for the new FontAwesome icon on their site.

**Comment by riwakawebsitedesigns** [comment]
+1 

Much need icon

fa fa-codeigniter I would think better name.

**Comment by SunDi3yansyah** [comment]
+1

**Comment by wh04mi** [comment]
+1

**Comment by InsiteFX** [comment]
Yes I think it should be fa-codeigniter to be consistent.

**Comment by tagliala** [comment]
duplicate of #4316 :lock:
