### ISSUE TITLE
Infinity Symbole

### ISSUE THREAD

**Issue by graphicforever** [FortAwesome/Font-Awesome#809]
Hello, 

I hope can get icon of infinity symbol 
I have the vector file ready 

![Picture 1](https://f.cloud.github.com/assets/3724408/204314/78c77b24-816f-11e2-87ac-7b20a7671f23.png)

**Comment by Francismori7** [comment]
Because the sizing doesn't match?

**Comment by AprilG** [comment]
It would still be nice to have the infinity symbol in font awesome because Balsamiq Mockups has now replaced their icons with font awesome icons, in which this is lacking. This causes me to have to look elsewhere for the icon, then screenshot it and place it in my mockup.

**Comment by tagliala** [comment]
Please +1 #1647

**Comment by burzum** [comment]
+1

**Comment by tagliala** [comment]
locking here, please use #1647 :lock:
