### ISSUE TITLE
Icon Request: fa-codeigniter

### ISSUE THREAD

**Issue by InsiteFX** [FortAwesome/Font-Awesome#8091]
The CodeIgniter Commuity would like to request an icon for the CodeIgniter Framework.

You can see the CodeIgniter logo icon here:

https://github.com/FortAwesome/Font-Awesome/issues/8087

Thank you
InsiteFX

**Comment by tagliala** [comment]
Duplicate of #4316 , please +1 that request

closing here

**Comment by riwakawebsitedesigns** [comment]
+1

**Comment by tagliala** [comment]
duplicate of #4316, :lock:
