### ISSUE TITLE
Icon request: icon-sale-off, icon-deal, icon-contact, icon-discount, icon-promotion

### ISSUE THREAD

**Issue by thugianmotti** [FortAwesome/Font-Awesome#8095]
Please add new these new icon into your database: sale off, deal sale, sale discount, promotion, thanks for listen to me.

**Comment by tagliala** [comment]
Sorry, can't keep this open.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
