### ISSUE TITLE
Bower - create `dist/` directory

### ISSUE THREAD

**Issue by jnovack** [FortAwesome/Font-Awesome#8096]
Bower lightly hints at separating out final package distributables as a `dist/` directory for files to be published without any of the package cruft or only publishing the files required.

Of the top bower packages, Bootstrap and JQuery use this standard, Angular and lodash only publish the `dist/` directory. Font-Awesome is the only holdout in the Top 5.

The advantage of doing this is to assist in streamlining the build process so that src and build files are not web-accessible by a share of a single directory.  The source less and scss files are helpful, which is why I'm suggesting publishing the final `css/` and `fonts/` into a `dist/` directory

Developers can just easily copy (or link) out the bower_components/<package_name>/dist/ directory (e.g. within express, as `app.use('font-awesome', express.static('bower_components/font-awesome/dist/'));)` rather than cherry-picking each distributable or folder within bower packages.

**Comment by tagliala** [comment]
`css` and `fonts` were both excluded from main because of bower specs: https://github.com/bower/spec/blob/master/json.md#main

we don't have js files, so I don't know what to do here.

Font Awesome's `bower.json` looks like bootstrap's one

Refers to #6227

Relevant bower commit: https://github.com/bower/spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99

**Comment by jnovack** [comment]
It's not a change for the bower process, it's a change for the build process.  The build has to put them in `dist/`.  This is not a simple change, in fact, it should be heavily weighted because it changes directories of files in the repo, not just the bower compile.

**Comment by tagliala** [comment]
@jnovack ah sorry, got it

This should be addressed at least in 5.0.0 because it is a breaking change

**Comment by tagliala** [comment]
We dropped bower support in Font Awesome 5, this issue does not apply anymore

Closing here
