### ISSUE TITLE
Icon Request: fa-guitar

### ISSUE THREAD

**Issue by mitulpatel320** [FortAwesome/Font-Awesome#8098]
![guitar-64](https://cloud.githubusercontent.com/assets/16184601/11619909/fe1835f8-9cd2-11e5-96cb-187327a1d06f.jpg)

**Comment by TheChen5** [comment]
Dupe #5059 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by ryankane** [comment]
@mitulpatel320 There is already a request for that... Please use the search feature of GitHub next time.

https://github.com/FortAwesome/Font-Awesome/search?q=guitar&type=Issues&utf8=✓

**Comment by tagliala** [comment]
thanks, closing here
