### ISSUE TITLE
Icon Request: fa-switch

### ISSUE THREAD

**Issue by beradrian** [FortAwesome/Font-Awesome#8099]
What do you think about having an icon that will represent switching between different items, like tasks, screens etc.
In my case I have a video chat and this will represent an action of switching between the local video and the remote one.
Is there another alternative icon already present there?
![switch](https://cloud.githubusercontent.com/assets/3028579/11628224/feffc50a-9cf8-11e5-8773-fc227c6fef64.png)

**Comment by tagliala** [comment]
maybe this one? http://fontawesome.io/icon/exchange/

**Comment by cyberjared** [comment]
I think it would be awesome if the two arrows crossed. Sort of like the / icon here: http://icons.marekventur.com/

**Comment by tagliala** [comment]
No feedback, closing here
