### ISSUE TITLE
Icon request: POI map icons

### ISSUE THREAD

**Issue by nikhildaga** [FortAwesome/Font-Awesome#810]
Can you please add various point of interest icons like http://mapbox.com/maki/ 
Thanks. :)

**Comment by dpfem** [comment]
+1

**Comment by tagliala** [comment]
Hi, since this is a request for a set, I'm going to close here

Also, during these years, we add a lot of icons from that page

**Comment by tagliala** [comment]
Check out our Maps category: https://fontawesome.com/icons?c=maps
