### ISSUE TITLE
Icon request: fa-smile-" "

### ISSUE THREAD

**Issue by LeadGuitarMx** [FortAwesome/Font-Awesome#8103]
Why not more smiles?
like 
fa-smile-o (the only one we have)
fa-smile-wink (requested before)
fa-smile-sad
fa-smile-cool
fa-smile-lol
fa-smile-cry
etc...

That would be great.. : )

**Comment by ryankane** [comment]
@LeadGuitarMx 

> fa-smile-sad

Isn't there already `fa-frown-o`? There is also `fa-meh-o`.

You can search for inspiration on other icons here: http://glyphsearch.com/?query=face

**Comment by LeadGuitarMx** [comment]
OK, so we have 3 icons.. that's good : )
Maybe in next versions can add more?

I want not use another icon font for add faces.

Thanks : )

**Comment by tagliala** [comment]
Sorry, I have to close this one

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
Please search to see if your icon request already exists. If a request is found, please +1 that one.
Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
