### ISSUE TITLE
Icon Request: fa-blackberry

### ISSUE THREAD

**Issue by hstanleycrow** [FortAwesome/Font-Awesome#8105]
the icon for operating system from RIM. It can be used on the tech blogs, pages, stores, etc that needs to show the icon with android, windows, etc

**Comment by ryankane** [comment]
Just the Blackberry logo? or the comination of RIM and Blackberry?

![blackberry.png][1]

  [1]: https://usahakreatifmuslim.files.wordpress.com/2013/01/blackberry.png

**Comment by tagliala** [comment]
dup of #1537 , please +1 that request

closing here
