### ISSUE TITLE
Icon Request: fa-timeline

### ISSUE THREAD

**Issue by camilapiovesana** [FortAwesome/Font-Awesome#8107]
![timeline](https://cloud.githubusercontent.com/assets/16197047/11639179/fbfdf212-9d09-11e5-96cc-12dd479bd90c.png)

**Comment by SteelBlue** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by haylo** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by farorm** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by ColdrickSotK** [comment]
+1

**Comment by juliagiannella** [comment]
+1

**Comment by ArunaBalavijay** [comment]
+1

**Comment by lesio** [comment]
+1

**Comment by stavlevy** [comment]
+1

**Comment by kangame** [comment]
+1

**Comment by eboujlal** [comment]
+1

**Comment by kreafox** [comment]
+1

**Comment by datishans** [comment]
+1

**Comment by ptlola** [comment]
+1

**Comment by Clem-D** [comment]
+1

**Comment by uzielweb** [comment]
+1

**Comment by adekock11** [comment]
+1

**Comment by amoralico** [comment]
+1

**Comment by dhananjayve** [comment]
+1

**Comment by jaredwiener** [comment]
+1

**Comment by pierreavinain** [comment]
+1

**Comment by shaedrich** [comment]
What about (based on fa-list-ul):
![method-draw-image](https://user-images.githubusercontent.com/11225821/69537501-8c29c680-0f80-11ea-81b7-db9aaa789c70.png)

**Comment by ssokolow** [comment]
That looks a little too much like a bulleted list for me.

When I think "timeline", what comes to mind is horizontal stuff like the direction people are going in  #3915 (especially [this one](https://github.com/FortAwesome/Font-Awesome/issues/3915#issuecomment-76731529)).

**Comment by Clem-D** [comment]
> That looks a little too much like a bulleted list for me... possibly with tree-style expander/collapser nodes.
> 
> When I think "timeline", what comes to mind is horizontal stuff like the direction people are going in #3915 (especially [this one](https://github.com/FortAwesome/Font-Awesome/issues/3915#issuecomment-76731529)).

I agree.
In my opinion I prefer this one https://github.com/FortAwesome/Font-Awesome/issues/3915#issuecomment-137683620 (the second and the third)
or this one https://github.com/FortAwesome/Font-Awesome/issues/8107#issue-120863441

**Comment by ssokolow** [comment]
Actually, I was referring to both of the examples here. I just don't associate timelines with a column of dots with blocks beside them. That, to me, says "[greeked](https://en.wikipedia.org/wiki/Greeking) representation of a list".

As for the other one you linked to, I'm not overly enthused by any of those.

While I recognize the project management software visualization that the first one evokes, it does *not* look like the general conception of a timeline.

As for the other two, having the timelines running through the boxes makes them look too much like stylized representations of abacuses.

The three things I intuitively associate with timelines as iconographic abstracts are:

1. Time is the horizontal axis.
2. The events are rectangles
3. If they have lines, they're vertical lines, associating them with specific instants on the timeline along the bottom.

... like how these timelines do it:

* https://timeline.knightlab.com/
* https://visjs.github.io/vis-timeline/examples/timeline/
* https://web.archive.org/web/20150312115622/http://mattbango.com/demos/pure-css-timeline/

Even the example Gantt charts on [the Wikipedia article](https://en.wikipedia.org/wiki/Gantt_chart) look more like that.

**Comment by shaedrich** [comment]
Then it's fa-timeline-h and what we are looking for would be something like this
![image](https://user-images.githubusercontent.com/11225821/80085349-636e2300-8558-11ea-9180-d1c7afa610f7.png)
or that
![image](https://user-images.githubusercontent.com/11225821/80085370-69640400-8558-11ea-8e8f-e868c0cde14d.png)

**Comment by dsentker** [comment]
+1

**Comment by sensibleworld** [comment]
We've added a few "timeline" icons to the latest v6 Alpha release: https://fontawesome.com/download
