### ISSUE TITLE
Icon Request: fa-battlenet

### ISSUE THREAD

**Issue by Kuldas** [FortAwesome/Font-Awesome#8110]
Social gaming network from blizzard. It can be used on gaming blogs ang magazines. Many players show where they play!

Steam, Twitch etc. - icons are included in Font-Awesome

**Comment by ryankane** [comment]
@Kuldas :+1: 

![fa-battlenet](http://i.imgur.com/gwpHaJ3.png)

# References

* http://wowwiki.wikia.com/wiki/File:Bneticon.png

**Comment by hayseed** [comment]
+1

**Comment by Kuldas** [comment]
You create this icon?

**Comment by ryankane** [comment]
I traced the icon, it was difficult. I still have an XFC (Gimp) file. I can probably link it in Dropbox at a later time.

**Comment by Annyeong** [comment]
+1 Benet Icon would be great, also a one for Hearthstone would be nice.

![hearthstone-t-shirts](https://cloud.githubusercontent.com/assets/17310919/13137561/c1928ace-d5ef-11e5-83b6-90dcca97eeec.png)

**Comment by Drewm4n** [comment]
+1 For BNet icon. Especially since the service provides Oauth2 authentication. Would make a lot of sense to have one to decorate those "Log in with Battle.NET" buttons.

**Comment by AmiLionel** [comment]
+1 for BNet icon

**Comment by TheWolfA2** [comment]
+1 For Bnet, along with a potential request for each of Blizzards games (WoW, D3, Overwatch, etc.)

**Comment by Seanathon** [comment]
+1

**Comment by unbolt** [comment]
+1 for bnet icon

**Comment by pepper-jk** [comment]
+1

**Comment by timeba** [comment]
I would like to see this so i can use it for the OAuth2 Authentication.

**Comment by pnobbe** [comment]
+1

**Comment by whatdoesdfoxsay** [comment]
+1

**Comment by vmwinckler** [comment]
+1

**Comment by danielblazquez** [comment]
+1

**Comment by EternalPhane** [comment]
+1

**Comment by gexiaowei** [comment]
+1

**Comment by geraldhiller** [comment]
+1

**Comment by InventivetalentDev** [comment]
+1

**Comment by dalfaand** [comment]
stiil waiting for this icon 👍

**Comment by grandmanitou** [comment]
+1

**Comment by fith** [comment]
+1

**Comment by astrikov-d** [comment]
+1

**Comment by NateShoffner** [comment]
+1

**Comment by Quidmy** [comment]
+1

**Comment by gexiaowei** [comment]
Battle net is no long use this icon and change it's name to Blizzard app
and see [https://us.battle.net/forums/en/bnet/topic/20753925203](https://us.battle.net/forums/en/bnet/topic/20753925203)

**Comment by ryankane** [comment]
@gexiaowei This is wrong, they decided to keep the name.

> https://news.blizzard.com/en-us/world-of-warcraft/20972461/blizzard-battle-net-update

They are now referred to as: _"Blizzard Battle.net,"_ as of two weeks ago.

**Comment by gexiaowei** [comment]
@ryankane are they mentioned the logo will be change or use for other app?

**Comment by Philword** [comment]
+1

**Comment by Quintenps** [comment]
+1

**Comment by MunkhdelgerMorhous** [comment]
+1

**Comment by sniffingpickles** [comment]
+1

**Comment by Kearsan** [comment]
+1

**Comment by fengthedroid** [comment]
+1

**Comment by iAxel** [comment]
We need this icon +1

**Comment by EmberQuill** [comment]
Building a web application that logs into Battle.Net with the Oauth2 API and I really want to put this icon on the login button. +1

**Comment by sniffingpickles** [comment]
For the time being, here's something to fiddle with that's used on my sites.

```
.bnet{
    background-image: url('https://i.imgur.com/XiGrmJk.png');
    background-position: 5px 5px;
    background-repeat: no-repeat;
    padding-left: 28px !important;
    margin: 5px 5px;
    vertical-align: top;
}
```

**Comment by Alainy** [comment]
+1

**Comment by JinAirsOs** [comment]
+1

**Comment by nmsmith22389** [comment]
+1

**Comment by bedeviere** [comment]
+1

**Comment by Machigatta** [comment]
Supporting this idea... am really want to use this icon on my application

**Comment by talbs** [comment]
Here you go, folks. We added this icon as part of [Version 5.8.0](https://fontawesome.com/changelog/latest) - https://fontawesome.com/icons/battle-net
Thanks for the patience and for continuing to vote this up! :smile:

**Comment by GoblinTimes** [comment]
+1

**Comment by tagliala** [comment]
Hi @GoblinTimes, `fa-battle-net` has been introduced in Font Awesome 5.8.0 

https://fontawesome.com/icons/battle-net?style=brands

Please make sure that you are using FA >= 5.8.0

**Comment by Quintenps** [comment]
Took 3 years, worth the wait I guess.
