### ISSUE TITLE
Icon Request: fa-takecare, fa-lookafter

### ISSUE THREAD

**Issue by duyson19802003** [FortAwesome/Font-Awesome#8113]
I want have icon about take care, like as the mother and the child. Please see attach file for more detail.
![takecare](https://cloud.githubusercontent.com/assets/6958598/11650626/49191a96-9dbd-11e5-8cc0-5a860d9ddec6.png)

**Comment by tagliala** [comment]
Is that a brand?

**Comment by duyson19802003** [comment]
No, that only icon. My situation is: I want to click into this icon and it redirect to the website about customer care. So, I want have the icon which describle content about "customer care". Just need 2 people with same shape as above, no need background and inner empty.

**Comment by tagliala** [comment]
maybe #5586 fit your needs?

**Comment by duyson19802003** [comment]
Oh, I was use user-headset for the contact center. So #5586 did not satisfied my requirement.

**Comment by invot** [comment]
That seems like a very specific user case and that particular icon might not make sense to use within a font. I do see how #5586 represents "support" more than "care"... but there are some medical-themes icons that might suit you to relate the idea of "care"

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
