### ISSUE TITLE
Replace default size of fa-times

### ISSUE THREAD

**Issue by alexander-anosov-sb** [FortAwesome/Font-Awesome#8116]
Can you please replace the icon fa-times so that it would be the same size as fa-repeat, fa-search, etc.
As in one line they look ugly:

![122](https://cloud.githubusercontent.com/assets/12207873/11655871/18d60a6a-9dc2-11e5-8537-b530372b6c31.jpg)

**Comment by tagliala** [comment]
I agree there is lack of consistency here and there.

Closely related to #1540

Leaving this open and adding to milestone 5.0.0, so Dave will eventually take a look and decide

**Comment by ryankane** [comment]
:+1:

**Comment by tagliala** [comment]
This is still an issue: https://jsfiddle.net/tagliala/tgzouajm/31/

**Comment by sensibleworld** [comment]
We now have a few different options for "times" including `xmark` and `xmark-large` https://fontawesome.com/search?q=xmark&o=r&f=classic
