### ISSUE TITLE
fa-television icon not working

### ISSUE THREAD

**Issue by wesdean** [FortAwesome/Font-Awesome#8117]
The fa-television icon is not working for me.

I am using Font Awesome version 4.5.
I have tried it on
OS X - Chrome
OS X - FireFox
Windows 8 - IE
Windows 10 - IE

Other icons are working fine. So far, I have only had trouble with fa-television.

**Comment by tagliala** [comment]
Please make sure you are using the latest version of FA. Take a look at our troubleshooting guidelines:

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Closing here but feel free to comment

**Comment by wesdean** [comment]
4.5 is the version available on the http://fontawesome.io home page and it's the version in the master branch of the repo. All my files are up-to-date.

**Comment by tagliala** [comment]
Do you see the icon on this page: http://fontawesome.io/icon/television/ ?

**Comment by wesdean** [comment]
The icons are showing up now. Something may have not copied to my server correctly, even though I tried several times. Thanks for your help.

**Comment by tagliala** [comment]
check the troubleshooting guide above

**Comment by giuliolastra** [comment]
Same problem, i see a square instead of fa-television (others are fine).

**Comment by tagliala** [comment]
check the troubleshooting guide https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by kennuard** [comment]
Have the same problem. Troubleshooting wont help.
