### ISSUE TITLE
Suggestion: Identify logos better

### ISSUE THREAD

**Issue by crairdin** [FortAwesome/Font-Awesome#8120]
I sometimes find myself discovering an icon I'd like to use based on the fact that it is suggestive of the function I want to use it for, only to discover that it is a company logo that I don't recognize. I don't want to accidentally signal something to a user who recognizes a logo that I don't. And since I have run into some of those, it makes me question all of them -- for example, I have to research whether fa-product-hunt is just a P in a circle, whether it's an emerging de-facto standard for "product search" function on websites, or if it belongs to someone. (Oops, it's a website I've never heard of.) It would be nice if trademarks/logos were identified as such on the cheatsheet on the website or somewhere like that.

**Comment by ryankane** [comment]
:+1: 

Another example: [`fa-delicious`](http://fontawesome.io/icon/delicious/). No prior knowledge of who this company is or how to look them up... until I hit Google.

Maybe an some sort of attribution section should be at the bottom of each brand icon's page. To have a link to their website/wikipedia.

**Comment by tagliala** [comment]
Got it. It should highlight brands if they are not in the brands section, like in "new icons"

Request for delicious: #372

http://fontawesome.io/icons/#brand

> * All brand icons are trademarks of their respective owners.
* The use of these trademarks does not indicate endorsement of the trademark holder by Font Awesome, nor vice versa.
* Brand icons should only be used to represent the company or product to which they refer.

**Comment by tagliala** [comment]
Closing here. Reopened #7693
