### ISSUE TITLE
Icon Request: fa-cross

### ISSUE THREAD

**Issue by gustavohellwig** [FortAwesome/Font-Awesome#8122]
Please, many christians will be happy to use a icon like the cross, like this: <img src="https://camo.githubusercontent.com/0b5e633889e0daa33a6df10f3de66c7b03f345a9/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333430323730372f3832373939342f32303436383737302d663061392d313165322d393761392d6539376533663939373233322e706e67">

**Comment by TheChen5** [comment]
Dupe #1611 
+1 that
Please :mag:before:heavy_plus_sign:
