### ISSUE TITLE
Icon Request: fa-bible

### ISSUE THREAD

**Issue by gustavohellwig** [FortAwesome/Font-Awesome#8123]
Please, many christians will be happy to use a icon like the Bible, like this: <img src="http://www.wheatonbible.org/Content/10713/Icons/chapters-icon.png" width="24" height="24"> or <img src="https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/holy_bible.png" width="24" height="24"> or <img src="https://cdn3.iconfinder.com/data/icons/bible-books-1/154/simple-bible-cover-cross-128.png" width="24" height="24">

**Comment by MrZach** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
-1 to any religious iconography.

**Comment by peiche** [comment]
+1

**Comment by Guestrevu** [comment]
+1

**Comment by D4rkTiger** [comment]
-1  as said @PeterShaggyNoble

**Comment by tagliala** [comment]
please do not downvote issues

**Comment by PeterShaggyNoble** [comment]
Sorry, Tagliala, I assumed voting was cumulative; I'll refrain from downvoting in the future.

**Comment by tagliala** [comment]
@PeterDaveHello no problems :+1:

**Comment by PeterDaveHello** [comment]
@tagliala I think you wanna tag @PeterShaggyNoble not me.

**Comment by tagliala** [comment]
@PeterDaveHello sure, sorry :)

**Comment by PeterDaveHello** [comment]
no problem.

**Comment by Pauldic** [comment]
+10

**Comment by webcaetano** [comment]
+1

Maybe the best idea is start with the 3 biggest religions symbols. 
* Christianity
* Islam
* Hinduism

Emoji don't have cross or bible but they have an church :church:

The cross could be also useful for lifetime dates (born and die)

**Comment by tagliala** [comment]
church #2088 cross: #1611

**Comment by webcaetano** [comment]
@tagliala thanks

**Comment by Mihailiuc** [comment]
+1 for this one!

Please give a +1 to this one also, is refereed also for Christians
https://github.com/FortAwesome/Font-Awesome/issues/8239  (for doctrinal statement)
https://github.com/FortAwesome/Font-Awesome/issues/8240

**Comment by GermanKiwi** [comment]
Note that we already have a book icon which could serve well as a Bible. I'm not sure we need to have a separate icon for a Bible.
http://fontawesome.io/icon/book/

**Comment by Mihailiuc** [comment]
Yes, we know. But it need to be very clear it is a bible. Because on the website we point bible very often.

In the bible is God's message. This mean it is different book and it have a very powerful message.

It is the most read and studied book in the world, it deserve a icon :)

Until that we can use it but it will be great to have unique icon.

**Comment by geodeveloper** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by ewillstudios** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by sandeejackson** [comment]
+ 1 on this!

**Comment by cre8tivediva** [comment]
+1

**Comment by sbsnet** [comment]
+1

**Comment by biwin** [comment]
+1

**Comment by gustavohellwig** [comment]
How many more is necessary ?

**Comment by meirinaldojunior** [comment]
tank you!

**Comment by scalway** [comment]
+1

**Comment by hvtuongpixa** [comment]
+1

**Comment by oviliz** [comment]
+1

**Comment by Wingo5315** [comment]
+1
In terms of the bible icon, you could just edit the current book icon so it has a cross in the middle instead of two lines.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/bible?style=solid

**Comment by GermanKiwi** [comment]
@sensibleworld thanks so much for making all these new religious icons - they're awesome, and greatly appreciated! :)
