### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by premier69** [FortAwesome/Font-Awesome#8126]
hello

for my footer payment option for my new webshite I would like a PayPal icon, something that will scale down nicely and be visible at like 10px size.
you will see what I mean if you check my footer at www.blomist.se

**Comment by PeterShaggyNoble** [comment]
There are already 2 PayPal options available in FA; what exactly are you requesting here?

**Comment by tagliala** [comment]
> something that will scale down nicely and be visible at like 10px size.

http://fontawesome.io/icon/paypal/

Please note that we cannot guarantee pixel perfection at every font size and we cannot guarantee pixel perfection at all for brand icons.

I should advise you to consider a custom version of fontawesome with a custom 10px version of PayPal icon.

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
How to implement a pixel perfect icon: https://github.com/blog/1135-the-making-of-octicons

Closing here but feel free to comment
