### ISSUE TITLE
Icon request: fa-exit

### ISSUE THREAD

**Issue by ciscoop** [FortAwesome/Font-Awesome#8134]
An icon useful in several context is the "exit" icon.
Normally the metaphor is rendered like this:
![exit](https://cloud.githubusercontent.com/assets/605624/11711381/3f63db2a-9f26-11e5-8574-e8dabf0d4ca7.png)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/sign-out/

you could search for `exit` here: http://fontawesome.io/icons/ and the sign-out icon will appear
