### ISSUE TITLE
Icon request: fa-viadeo

### ISSUE THREAD

**Issue by D4rkTiger** [FortAwesome/Font-Awesome#8138]
Like a lot of other guy requests, could you please consider adding Viadeo, business social network in the list of your social icons.

Do you need I provide icon or anything else to help you or to convince you ?

You have a nice image that you can use : http://gagnezdesclients.com/wp-content/uploads/2013/06/Viadeo_favicon_300dpi_RGB.jpg

**Comment by tagliala** [comment]
duplicate #886

**Comment by yana147** [comment]
2 years !

**Comment by tagliala** [comment]
let's celebrate on #886 :birthday:  :smile:
