### ISSUE TITLE
Icon Request: fa-gold

### ISSUE THREAD

**Issue by dchara01** [FortAwesome/Font-Awesome#8141]
It will be useful for financial websites.
![gold-128](https://cloud.githubusercontent.com/assets/10142016/11732064/5a789012-9fa9-11e5-93e1-7c12195cf034.png)
![gold-129](https://cloud.githubusercontent.com/assets/10142016/11732065/5a81ebc6-9fa9-11e5-86ac-21739d754efc.png)

**Comment by tagliala** [comment]
duplicate of #7729 , please +1 that request

closing here

**Comment by dchara01** [comment]
sorry to bother, but how do i 1+ it?

**Comment by tagliala** [comment]
@dchara01 simply leave a comment there :)

**Comment by dchara01** [comment]
thank you :)

**Comment by butchero** [comment]
I need it also for an exchange rates website. + 1 also :)

**Comment by irsh5** [comment]
Please Add this in your library...

**Comment by khasky** [comment]
+1

**Comment by tagliala** [comment]
locking here because this is a duplicate of #7729
