### ISSUE TITLE
Icon Request: fa-oil-drum

### ISSUE THREAD

**Issue by dscharalampidis** [FortAwesome/Font-Awesome#8142]
It will be useful for financial websites.
![oil-256](https://cloud.githubusercontent.com/assets/10142016/11732082/88d68c98-9fa9-11e5-8f19-4071442e1e2f.png)

**Comment by MrZach** [comment]
+1

Could also be used on oil and fuel related websites.

**Comment by tagliala** [comment]
Is there a better title for this?

**Comment by dchara01** [comment]
probably fa-crude-oil ?

**Comment by richardtallent** [comment]
I would suggest expanding the scope of this slightly to being simply a so-called ISO drum (ISO 15750-1/2, aka "55 gallon drum"). It would simplify the design and open it up to some additional use cases, including transportation.

https://en.wikipedia.org/wiki/Drum_(container)

Crude as a commodity is priced using 42-gallon "barrel" units, but wouldn't be transported in them. However, petroleum-based products (other than crude) are often shipped in 55 gallon / 200 liter drums, so it's a reasonable enough icon to use for crude.

**Comment by tagliala** [comment]
@richardtallent should I rename to icon-oil-drum ?

**Comment by richardtallent** [comment]
Since they are rarely used to store crude oil, maybe `fa-drum-container` or `fa-iso-drum` would be better?

**Comment by kjacob76** [comment]
+1

**Comment by otitov** [comment]
+1

**Comment by lalabili** [comment]
+1

**Comment by tagliala** [comment]
Is this a duplicate of #4318 ?

**Comment by JaiDoubleU** [comment]
+1

**Comment by dawaltconley** [comment]
+1, looking for something to represent barrels of oil. would vote for a plain barrel icon (minus the droplet) since that can be added with fa-tint and it makes it more flexible. could also add fa-biohazard or something to represent waste, etc.

or all the above? (:

**Comment by tagliala** [comment]
Is this a duplicate of #4318 ?

**Comment by aethior** [comment]
> Is there a better title for this?

🛢 [U+1F6E2](https://emojipedia.org/emoji/%F0%9F%9B%A2/) Oil Drum

**Comment by aethior** [comment]
> Is this a duplicate of #4318 ?

I think so. What do you think about closing the other request and changing this to `fa-oil-drum (barrel)` (to avoid duplicate votes)?

**Comment by tagliala** [comment]
Let's use #4318
