### ISSUE TITLE
Icon request: icon-laravel, icon-angular, icon-backbone, icon-codeigniter, icon-magento etc...

### ISSUE THREAD

**Issue by chrismackie28** [FortAwesome/Font-Awesome#8146]
Would be great for web developers to showcase technologies/frameworks they use.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Please search and +1 the proper requests (eg: #2151 #2027 ...)

Please also consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
