### ISSUE TITLE
Icon Request: fa-triangle, fa-triangle-o

### ISSUE THREAD

**Issue by thesumo** [FortAwesome/Font-Awesome#8147]
Hey guys!
Triangles.  I know they are not the most popular thing now, the pointedness being dangerous for children and all.  But lets just take off our safety helmets for a second and consider this basic geometric shape.  As Pythagoras once said, "A triangle is ballin', yo. They're good for symbology on websites n' stuff.  Word."  Can we find it in our hearts to reconsider our three pointed friend?  I hope so.

Thanks,
Jacob "Triangle Boss" Yeager

**Comment by TheChen5** [comment]
Dupe #3216 
+1 that
Please :mag:before:heavy_plus_sign:
