### ISSUE TITLE
Icon Request: Blogger powered by Google

### ISSUE THREAD

**Issue by engrajonahmed** [FortAwesome/Font-Awesome#8148]
Please add the brand icon of Blogger....that we can use it on our clients business website to indicate their blog powered by Blogger or we can use it on the footer of the Blogger powered blog as "Powered by Blogger"
![blogger-logo_318-76488 png](https://cloud.githubusercontent.com/assets/13585264/11757851/f7b8d9dc-a08e-11e5-83e2-50bb76a74009.jpg)

**Comment by TheChen5** [comment]
Dupe #1088 
+1 that
Please :mag:before:heavy_plus_sign:

**Comment by Arshad1480** [comment]
•	I really enjoyed reading your blog, you have lots of great content. I look forward to reading more posts from you.
https://www.rebelmouse.com/mothersladla/trust-flow-1570727175.html
