### ISSUE TITLE
Icon Request fa-inventory, fa-accounts, fa-crm, fa-hrm, fa-project, fa-service

### ISSUE THREAD

**Issue by sunilsoftkochi** [FortAwesome/Font-Awesome#8150]
Icons Relating to Inventory, Accounts, CRM, HRM, Project and Service

**Comment by TheChen5** [comment]
CRM dupe #2130
Project dupe #7852 
If those requests does not satisfy you, please create separate requests.
In the future, please do not request for sets of icons. https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
Also, to avoid duplicates, please :mag:before:heavy_plus_sign:

**Comment by tagliala** [comment]
@TheChen5 thanks

closing here
