### ISSUE TITLE
Icon request: icon-fa-edge 

### ISSUE THREAD

**Issue by tejashri-vsplc** [FortAwesome/Font-Awesome#8153]
I am planning to use this icon in my site. 
e.g Site name:expressHR
I need to use this icon for Home menu .
So please do the needful.
Thanks in advance.
![edge](https://cloud.githubusercontent.com/assets/16285449/11775281/751f7c34-a263-11e5-85c6-36e4cda3bd3f.png)

**Comment by tagliala** [comment]
could you please clarify?

We are not talking about Microsoft Edge, right?

**Comment by tejashri-vsplc** [comment]
Yes. We are not talking about Microsoft Edge.
There is a 20 new icons and in them there is one "fa-edge (|<i class="fa 
fa-edge"></i>)|" icon.
I need this icon.

-Tejashri

**Comment by tagliala** [comment]
Could you please provide a single color example of the icon you need on github? (email attachments don't work)

https://github.com/FortAwesome/Font-Awesome/issues/8153

**Comment by tejashri-vsplc** [comment]
PFA. 
I want it as it is.
![edgeicon](https://cloud.githubusercontent.com/assets/16285449/11778242/32be84e6-a279-11e5-82aa-d77e6036e83c.png)

**Comment by tagliala** [comment]
You may not have updated to latest version of Fontawesome

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Moreover, you should not use this icon to represent something that is not related to Microsoft Edge

http://fontawesome.io/icons/#brand

> * All brand icons are trademarks of their respective owners.
* The use of these trademarks does not indicate endorsement of the trademark holder by Font Awesome, nor vice versa.
* **Brand icons should only be used to represent the company or product to which they refer.**

Closing here
