### ISSUE TITLE
Icon Request: fa-cake

### ISSUE THREAD

**Issue by dibakarjana** [FortAwesome/Font-Awesome#8154]
Need for online bakery web & mobiles apps, all type of cakes.

Idea:
![fa-general-cake](https://cloud.githubusercontent.com/assets/2016303/11784722/f0b572a0-a2a3-11e5-8570-7dd168711286.jpg)

**Comment by sensibleworld** [comment]
Does our `cake-candles` icon work for this? https://fontawesome.com/v6.0/icons?q=cake

If not, I'll re-open.
