### ISSUE TITLE
Font Display Problem

### ISSUE THREAD

**Issue by kusius** [FortAwesome/Font-Awesome#8156]
Hello ! 

I'm running a fresh install of Netrunner (Kubuntu based) 
I installed the .ttf fonts (version 4.5.0) in ~/.fonts and ran fc-cache -f .
The problem is that some fonts do not display correctly ( weird gibberish glyphs) . Uppon closer inspection and cross referencing with the cheatsheet I concluded that icons below versions 4.4 can not be diplayed. That is only icons from v4.4.0 and v4.5.0 are diplaying correctly.

Any guidelines appreciated!

**Comment by tagliala** [comment]
Did you came out with a solution?

**Comment by kusius** [comment]
Yes sorry for not posting . But i wanted to make sure what was going on. 
So the problem was specific to i3 i guess. I was trying to display the icons on the i3 bar and had not set the fonts to FontsAwesome explicitly in the configuration file. 

That fixed the problem for me!
