### ISSUE TITLE
Icon Request: fa-calendar-clock (datetime)

### ISSUE THREAD

**Issue by amlynn18** [FortAwesome/Font-Awesome#8158]
I'm working on a pattern that could benefit from an icon that combines both date and time. For example, a calendar with a clock in the bottom right corner.

**Comment by tagliala** [comment]
slightly refers to #1181

**Comment by amlynn18** [comment]
This is a good example of what we would need: 
http://www.shutterstock.com/pic-341245148/stock-vector-day-time-vector-icon-with-additional-date-and-time-management-pictograms-style-is-flat-symbols.html

**Comment by PlassJ** [comment]
+1

**Comment by nyon** [comment]
I added an to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559 that could fit your purpose. It is not quite looking like the image you posted, but perhaps it is nevertheless useful for you.

    fa-calendar-clock-o

**Comment by zuck** [comment]
+1

**Comment by cherrador** [comment]
While this icon is added, alternative it can be done by extending the stack CSS. Added a sample here:

https://jsfiddle.net/cherrador/jomgLb2h/

**Comment by pitus** [comment]
+1

**Comment by WaynePhipps** [comment]
+1

**Comment by wilmer737** [comment]
+1

**Comment by tagliala** [comment]
This icon could be achieved with the SVG Framework

Example by @InsanityMeetsHH: https://codepen.io/anon/pen/KrzaeP

**Comment by davequested** [comment]
+1

**Comment by tagliala** [comment]
Updating the example, the codepen does not seem to work anymore 

Demo: https://jsfiddle.net/tagliala/L17f528g/472/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by rarich01** [comment]
+1 Here is an example: 
https://materialdesignicons.com/icon/calendar-clock

**Comment by aethior** [comment]
Hi @amlynn18,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/calendar-clock

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This icon has been added to FA Pro

**in a web application** it is possible to create the requested icon with FA Free by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/57/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
