### ISSUE TITLE
Icon Request: fa-split

### ISSUE THREAD

**Issue by frejnorling** [FortAwesome/Font-Awesome#8161]
A icon to indicate two possible directions, or the separation of a single entity into two entities.

Example: 

![split-128 1](https://cloud.githubusercontent.com/assets/524827/11843070/c06e945e-a407-11e5-89c3-a5157591951d.png)

**Comment by tagliala** [comment]
http://fontawesome.io/icon/code-fork/ ?

**Comment by frejnorling** [comment]
I know about fa-fork, but as I see it, fork represents one main entity and another splits of from that.

For example, I want to represent a different possible outcomes from an event. It can be either one or the other.

**Comment by SatanicGeek** [comment]
+1

**Comment by caduvieira** [comment]
Will be in 5.0.0 https://github.com/FortAwesome/Font-Awesome/issues/188#issuecomment-53061550

**Comment by frejnorling** [comment]
@caduvieira Awesome!

**Comment by tagliala** [comment]
this icon is being postponed since 3.1.0.

I'm not 100% sure it will be part of 5.0.0

**Comment by asj693** [comment]
Could really use this split icon!!

**Comment by orielsy** [comment]
It's 2020. Ver 5.0 has been out for some time.

+1
