### ISSUE TITLE
Icon Request: fa-pullrequest or fa-mergerequest

### ISSUE THREAD

**Issue by lianguan** [FortAwesome/Font-Awesome#8164]
![image](https://cloud.githubusercontent.com/assets/15666864/11865411/d7fc2708-a4de-11e5-9c2e-1d86ebbd0e89.png)

**Comment by phecho** [comment]
Is there anyone who supports my request?

**Comment by SatanicGeek** [comment]
+1

**Comment by caduvieira** [comment]
dupe of https://github.com/FortAwesome/Font-Awesome/issues/3743

please +1 that issue

**Comment by aethior** [comment]
Hi @lianguan,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/code-pull-request

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
Duplicate of #3743
