### ISSUE TITLE
Icon Request: fa-container

### ISSUE THREAD

**Issue by alvarotrigo** [FortAwesome/Font-Awesome#8165]
A container icon would be ideal for the [Transportation Icons section](http://fontawesome.io/icons/#transportation). 

My company, and I suspect many others transport related ones, need to use of transporting containers for their icons, which is usually related with the provided `fa-ship`, `fa-train` and `fa-truck`.

Some ideas:
[\- Container 1](https://cdn4.iconfinder.com/data/icons/logistic-delivery-solid-icons-vol-3/72/104-128.png)
[\- Container 2](https://cdn0.iconfinder.com/data/icons/logistic-2/450/container-512.png)
[\- Container 3](https://d30y9cdsu7xlg0.cloudfront.net/png/107091-200.png)

[Image of the real object](http://www.dekkergroep.com/images/public/popup/containertransport.jpg)

**Comment by SatanicGeek** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by rintzzy** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by zuck** [comment]
+1

**Comment by hctsang** [comment]
+1

**Comment by ni8mr** [comment]
+1

**Comment by kwendenarmo** [comment]
+1

**Comment by syamsulalam** [comment]
+1

**Comment by mike6ds** [comment]
+1

**Comment by ccorlatti** [comment]
+100000

**Comment by dixonj** [comment]
+1

**Comment by gbolo** [comment]
+1

**Comment by alanis2000** [comment]
+1
please add this icon!!

**Comment by lalabili** [comment]
+1 
it is important for logistics field

**Comment by GerritP** [comment]
+1
I agree - many icons in the logistics field are needed

**Comment by prgsavi** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/container-storage?style=solid
https://fontawesome.com/icons/truck-container?style=solid
