### ISSUE TITLE
Icon request: icon-magazine

### ISSUE THREAD

**Issue by bethmdx** [FortAwesome/Font-Awesome#8166]
Something like this :+1: 
![screen shot 2015-12-17 at 14 44 20](https://cloud.githubusercontent.com/assets/16337995/11872264/55ae09fe-a4cc-11e5-82ff-7d918498422f.png)

**Comment by aethior** [comment]
Hi @bethmdx,

This suggestion is duplicate of #2503. Please +1 that.

Regards.
