### ISSUE TITLE
Icon Request: fa-ipad

### ISSUE THREAD

**Issue by morganmsk** [FortAwesome/Font-Awesome#8167]
Now in font awesome  we can find iphone icon and desktop. ipad icon will be very useful for the Landing pages, where you have to show adaptability to different devices. you can take as a basis the style icons Iphone and finalize it.

**Comment by Xety** [comment]
There's already a `tablet` icon :
`Tablet` (iPhone is you prefer) : http://fortawesome.github.io/Font-Awesome/icon/tablet/
`Mobile` (iPad if you prefer) : http://fortawesome.github.io/Font-Awesome/icon/mobile/
`Desktop` (iMac if you prefer) : http://fortawesome.github.io/Font-Awesome/icon/desktop/

**Comment by tagliala** [comment]
Closing here
