### ISSUE TITLE
Icon request: fa-cart-check

### ISSUE THREAD

**Issue by Clearnine** [FortAwesome/Font-Awesome#8168]
An icon used to update a cart after changing quantity.  Suggest check mark over cart like the plus sign.

**Comment by PlippiePlop** [comment]
Can't you use  the Stacked Icons option to to this?

**Comment by caduvieira** [comment]
http://fontawesome.io/icon/cart-plus/ ?

or something like https://github.com/FortAwesome/Font-Awesome/issues/3234#issuecomment-40293524 ?

**Comment by tagliala** [comment]
refers to #1181

**Comment by nyon** [comment]
I added icons that could fit your purpose to nyon/fontawesome-actions@d142fa3a38e07d0b95977e9ef5e86a495e3a5559

    fa-shopping-cart-plus
    fa-shopping-cart-times
    fa-shopping-cart-*

You can also use ```fa-shopping-bag-*``` and ```fa-shopping-basket-*```

**Comment by tagliala** [comment]
https://fontawesome.com/icons/cart-circle-check?s=solid

This icon has been added to the Pro set

In a web application it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo:https://jsfiddle.net/tagliala/bfa6uhse/70/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
