### ISSUE TITLE
Icon request: military-icons

### ISSUE THREAD

**Issue by SatanicGeek** [FortAwesome/Font-Awesome#8169]
Hello.

I work on a project for an Airsoft team and I just had an idea for new icons.

There are no icons for an assault rifle, a sniper, a bazooka, a tank, etc ...

Here is a list of icons that could be created and used by all :

- Assault rifle
- Sniper Rifle
- Shotgun
- Handgun (M9 , M1911 , etc ...)
- Knife
- Grenade
- Rocket launcher
- Military Vehicles
- Helicopter
- Different rank insignia

I am very bad graphic designer and I would not be able to give examples but ask me if you want more details.

I think it is something missing in Font- Awesome ...

**Comment by tagliala** [comment]
Sorry, can't keep this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please do not request comprehensive sets of icons related to a very specific field.

My advice is to consider a custom build :https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
