### ISSUE TITLE
Icon Request: fa-myspace

### ISSUE THREAD

**Issue by therockers** [FortAwesome/Font-Awesome#8171]
I believe MySpace deserves to be on Font Awesome's icon list. Here are the recent MySpace logos straight from the MySpace website.

![icon1](https://cloud.githubusercontent.com/assets/2050490/11894740/d169db64-a53e-11e5-8164-42fbcab0b3ba.png)
![icon2](https://cloud.githubusercontent.com/assets/2050490/11894741/d177ddae-a53e-11e5-9054-01b767fb5f86.png)

**Comment by aethior** [comment]
Hi @therockers,

This suggestion is duplicate of #831. Please +1 that.

Regards.

**Comment by ahmeddabak** [comment]
+1
