### ISSUE TITLE
Icon request: fa-bars with square corners

### ISSUE THREAD

**Issue by anaabrantes** [FortAwesome/Font-Awesome#8176]
Can you please add another fa-bar with square corners?

I attached an image representing the bars that I want.
![menu_burger](https://cloud.githubusercontent.com/assets/16351133/11899538/8b647152-a597-11e5-88ed-14258853d469.png)

**Comment by tagliala** [comment]
I'm going to close this one

Given that Font Awesome's visual consistency is not extremely accurate, the design you are proposing doesn't play well with almost every other icon in the set

Please consider a css based solution, take a look at bootstrap's one: https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_navbar.scss#L193

@davegandy ?
