### ISSUE TITLE
Icon request: fa-search with square corner

### ISSUE THREAD

**Issue by anaabrantes** [FortAwesome/Font-Awesome#8177]
Can you please add another fa-search icon with square corners?

I attached an image representing the icon that I want.
![search](https://cloud.githubusercontent.com/assets/16351133/11899724/fa62ccb0-a598-11e5-83a1-b29073c4a060.png)

**Comment by tagliala** [comment]
Sorry, I'm going to close this one too

Given that Font Awesome's visual consistency is not extremely accurate, the design you are proposing doesn't play well with almost every other icon in the set

@davegandy ?
