### ISSUE TITLE
Icon request: fa-tardis

### ISSUE THREAD

**Issue by juzraai** [FortAwesome/Font-Awesome#8187]
Hello!

I think a TARDIS icon would be really appreciated by the whovian community out there! ;)
(I'm surprised that none of 8K requests is about this thing. :))

I would use it on my about page where I list my favourite things, besides Doctor Who.

Something like this:
![image](https://cloud.githubusercontent.com/assets/3587670/11915831/79096572-a6b8-11e5-9966-308b11c27dff.png)

or this:
![image](https://cloud.githubusercontent.com/assets/3587670/11915843/de00e2ac-a6b8-11e5-8eac-8cb49be1d1f0.png)

I hope you guys will make this, and thanks for Font Awesome, it's really awesome!

Thanks,
Zsolt

**Comment by ON3YH** [comment]
Tried to sonic FontAwesome, didn't work...
So a simple +1 :+1:  it is

**Comment by tagliala** [comment]
This icon is too complex to fit 14px icon size

**Comment by juzraai** [comment]
I used my sonic to shrink it down to 14px, I got this (with a bonus dalek):
![image](https://cloud.githubusercontent.com/assets/3587670/11917733/22debbd2-a714-11e5-9a74-4af2c6e1a401.png)

:)

**Comment by toddjcrane** [comment]
+1 and a +1 for dalek

**Comment by pault84** [comment]
Tardis looks like a chinese lantern in that version

**Comment by juzraai** [comment]
If you say so, but it's more than nothing. Can you do it better in 14px? :)

**Comment by vytska** [comment]
+1

**Comment by aethior** [comment]
Hi Whovians!

I think the [**fa-police-box**](https://fontawesome.com/icons/police-box) icon should also be considered as a `transportation` category icon. 😉
In any case `fa-police-box` was added in v5.12.0.

Regards.

cc/ @tagliala
