### ISSUE TITLE
Icon request: fa-invader (arcade)

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#8190]
There are two recognizable icons to represent arcade video games: invader (Space Invaders) and ghost #4533 (Pac-Man).

![invader_1-128](https://cloud.githubusercontent.com/assets/1769227/11917162/db334b62-a6fb-11e5-8c74-d925309aafaf.png)

**Comment by ryankane** [comment]
:+1:

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by Kam3leoN** [comment]
+1

**Comment by AndreLGava** [comment]
+1

**Comment by Pezhvak** [comment]
+1

**Comment by yovantichrist** [comment]
+1

**Comment by aethior** [comment]
This icon was adden in v5.12.0.
Check: https://fontawesome.com/v5.15/icons/alien-monster

cc/ @tagliala

**Comment by tagliala** [comment]
@aethior thanks!

**Comment by aethior** [comment]
@tagliala I think you can close here. ;)
