### ISSUE TITLE
Icon Request: icon-fa-mining

### ISSUE THREAD

**Issue by j-s-v** [FortAwesome/Font-Awesome#8192]
Hey,

I'm looking to use a web application icon in Rapidweaver for a company website I'm putting up but can't find anything suitable: I'm looking for a mining icon. Here's a couple examples:

https://commons.wikimedia.org/wiki/File:Schlaegel_und_Eisen_nach_DIN_21800.svg
http://icons.greenmap.org/gallery/details.php?image_id=548&sid=12811c8b45d8b59970eb7fc2c5e1081f

Cheers,
Jouni

**Comment by tagliala** [comment]
Please search for duplicates before opening new request:

mining: #2442, please +1 that request

closing here
