### ISSUE TITLE
Icon Request: icon-fa-nuclear

### ISSUE THREAD

**Issue by j-s-v** [FortAwesome/Font-Awesome#8193]
Hey,

I'm looking to use a web application icon in Rapidweaver for a company website I'm putting up but can't find anything suitable: I'm looking for an icon related to nuclear waste disposal, something along the lines of e.g. a barrel with a nuclear symbol on it in black and white, such as the one I found from Shutterstock:

http://www.shutterstock.com/s/radioactive+waste/search.html

Cheers,
Jouni

**Comment by tagliala** [comment]
Please search for duplicates before opening new request:

radioactive: #4470, please +1 that request

closing here
