### ISSUE TITLE
Icon Request: fa-homephone

### ISSUE THREAD

**Issue by bryne78** [FortAwesome/Font-Awesome#8194]
Hey guys. I will very appreciate if you can make home phone icon. Something like that one
http://www.clipartbest.com/cliparts/RiA/L5z/RiAL5zdiL.jpeg
It will very help me because the phone icon you have not really looks nice for our web.
If need i can definitely pay for the job.
Thank you

**Comment by tagliala** [comment]
duplicate of #1578, please +1 that request

closing here
