### ISSUE TITLE
Icon Request: fa-dsm

### ISSUE THREAD

**Issue by Dunkelherz** [FortAwesome/Font-Awesome#8195]
![dsm](https://cloud.githubusercontent.com/assets/16374875/11920020/372c933a-a763-11e5-8256-70c52b28c9c2.png)

**Comment by tagliala** [comment]
is this a brand?

**Comment by holtkamp** [comment]
might be this [Dutch multi-national](http://www.dsm.com), deserves some explanation from @Dunkelherz  would say...

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
