### ISSUE TITLE
Icon Request: fa-deezer

### ISSUE THREAD

**Issue by Toube** [FortAwesome/Font-Awesome#8196]
All my users can't use spotify but some of the can use deezer, another music service.

Keep up fontawesome, best plugin ever

![ogdeezer](https://cloud.githubusercontent.com/assets/1337216/11920048/a6aaa0fc-a764-11e5-9bb5-a6e241677b5c.jpg)

**Comment by tagliala** [comment]
dup of #2802, please +1 that request

closing here
