### ISSUE TITLE
Do we have fa-spin-vertical

### ISSUE THREAD

**Issue by pgangwani** [FortAwesome/Font-Awesome#8197]
Hello Team,
I would like to use icon to spin on vertical axis ( just like fa-flip-horizontal but continuous animation same as in fa-spin )

Can we do that ??
refer this :
![image](https://cloud.githubusercontent.com/assets/14316332/11920661/aa4fc71e-a79b-11e5-9ebc-160fe9a2eaf9.png)

**Comment by tagliala** [comment]
go for a plain css 3d animation

https://jsfiddle.net/tagliala/syduuue9/2/

Browser support: http://caniuse.com/#feat=transforms3d

hope it helps
