### ISSUE TITLE
IconRequest: fa-bathroom

### ISSUE THREAD

**Issue by darkfire56j** [FortAwesome/Font-Awesome#8204]
Hi,
it would be nice to add some extra room like bathroom:

http://www.realdealbathrooms.com/wp-content/uploads/2013/12/Accommodation-Hot-tube-icon.png

And also extend with alias "fa-bedroom" the already existing "fa-bed"

**Comment by caduvieira** [comment]
related to #708

**Comment by tagliala** [comment]
duplicate of #708
