### ISSUE TITLE
Icon Request: fa-repair

### ISSUE THREAD

**Issue by mzeyrek** [FortAwesome/Font-Awesome#8205]
Need a repair icon either with Hammer & Wrench combination or Screwdriver & Wrench 
Thanks
![depositphotos_35237763-vector-repair-icon](https://cloud.githubusercontent.com/assets/8410706/11976162/352feb14-a97e-11e5-985d-d8d95f7d94b5.jpg)
![download](https://cloud.githubusercontent.com/assets/8410706/11976163/36db2e60-a97e-11e5-9d16-283a9c437697.png)

**Comment by tagliala** [comment]
dup of #736 , please +1 that request

closing here
