### ISSUE TITLE
Icon Request: icon-desklamp

### ISSUE THREAD

**Issue by jj-quintin** [FortAwesome/Font-Awesome#8206]
In can improve it of course. We need it in claroline.net (an open source learning environment, https://github.com/claroline/Claroline) to represent the access to the personal desk of the user

![desk-lamp-black](https://cloud.githubusercontent.com/assets/16414632/11977615/8e2a8ca0-a984-11e5-8bc5-3eec6c85357d.png)

**Comment by tagliala** [comment]
This is available in FA 5.14.0 Pro: https://fontawesome.com/icons/lamp-desk?style=solid
