### ISSUE TITLE
Icon request: icon-file-table-o

### ISSUE THREAD

**Issue by jklingen** [FortAwesome/Font-Awesome#8207]
![fa-file-table-o](https://cloud.githubusercontent.com/assets/5475899/11977662/0c08c7cc-a985-11e5-99fa-823d2a74917f.png)

To be used for tabular document downloads, as a more generic (and meaningful, IMO) alternative to fa-file-excel-o. Depending on their technical background, many users don't care whether it's XSL\* or CSV, as long as it opens up in their default application for table documents.

**Comment by AndreLGava** [comment]
+1

**Comment by aethior** [comment]
Hi @jklingen,

This icon was added in v5.3.0.
Check https://fontawesome.com/icons/file-spreadsheet

Regards.

cc/ @tagliala
