### ISSUE TITLE
Icon Request: Backpack and other school related icons

### ISSUE THREAD

**Issue by rpetitto** [FortAwesome/Font-Awesome#8208]
Backpack icon to compliment briefcase...educational type icons would go a long way for school websites.

**Comment by tagliala** [comment]
backpack is a duplicate of #backpack, please +1 that request

I can't leave this open, it doesn't meet our contributing guidelines:
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
