### ISSUE TITLE
Why goodreads is not yet included?

### ISSUE THREAD

**Issue by LavenderMeadows** [FortAwesome/Font-Awesome#8210]
I was going to put in a request for a new icon representing Goodreads, but I followed your instructions and searched to make sure nobody else had already made the same request.  Apparently just off the top, people have been requesting an icon for goodreads for at least the last two years and yet you have not created one.  My question is why?  I recently purchased a premium theme to use for wordpress to redesign my author website and your icons were included in the package, when I asked them about getting a goodreads, they indicated you did not offer one?  Again, I wonder why?  Since obviously so many people are wanting one for goodreads, is there a particular reason why you are not offering one?

**Comment by tagliala** [comment]
Hi,

There is no specific reason

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> Recently purchased a premium theme to use for wordpress to redesign my author website and your icons were included in the package, when I asked them about getting a goodreads, they indicated you did not offer one?

Please note that Font Awesome is free and open source.

Anyway, you should be able to edit your theme and use a custom build of fontawesome or include another set of brand icons

Hope it helps

Closing here but feel free to comment

**Comment by Lasoulane** [comment]
I make sites for authors and they ALL request a Goodreads icon. Because there is no fa-goodreads, I don't use Font Awesome icons for social media at all.

**Comment by LavenderMeadows** [comment]
unfortunately, they came with the premium template I purchased...checking now into using others since the authors of font awesome obviously do not care about the needs of the people since this icon has been requested repeatedly for over two years now
