### ISSUE TITLE
font awesome not working in LG3 mobile Device

### ISSUE THREAD

**Issue by pankaj0191** [FortAwesome/Font-Awesome#8213]
I have issue font awesome icon does not appear in mobile.Instead of icon square box show.
Currently I am using   4.5.0  Version of Font Awesome.  in this website (https://heidi.co.il/) 

I have Attached a screen short of issues in LG3 Device
![in-lg3-device](https://cloud.githubusercontent.com/assets/16426801/11994345/a48cc1e6-aa62-11e5-9435-593e56b9212e.png)

This is the screen short for IPhone in this device icon file But i am not sure in another Devices icons are fine or not .
![in-other-phone](https://cloud.githubusercontent.com/assets/16426801/11994346/a48edbc0-aa62-11e5-8f7b-7ef00d51348b.png)

**Comment by tagliala** [comment]
Please note that you are loading (at least) two versions of fontawesome,

here:
```css
<link rel='stylesheet' id='yith-wcwl-font-awesome-css'  href='https://heidi.co.il/wp-content/plugins/yith-woocommerce-wishlist/assets/css/font-awesome.min.css?ver=4.3.1' type='text/css' media='all' />
```

and here:
```css
<link rel='stylesheet' id='theme-font-awesome-css'  href='https://heidi.co.il/wp-content/themes/marvel/css/font-awesome.min.css?ver=1.0.3' type='text/css' media='all' />
```

this could bring to unexpected results

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Fix the above issue then check again.

Closing here but feel free to comment
