### ISSUE TITLE
Icon Request: fa-amplifier

### ISSUE THREAD

**Issue by mike-stumpf** [FortAwesome/Font-Awesome#8215]
It would be awesome to have a electric guitar/instrument amplifier icon.  I was thinking of something like this: 
![stock-vector-amplifier-icon-206459488](https://cloud.githubusercontent.com/assets/5053873/11996885/f65ccb4a-aa32-11e5-8758-b129131226f7.jpg)

**Comment by damusix** [comment]
+1

**Comment by CarlosHAraujo** [comment]
+1

**Comment by KungFuJosh** [comment]
👍+10000

**Comment by aethior** [comment]
Hi @mike-stumpf,

This icon was added in v5.11.0.
Check https://fontawesome.com/icons/amp-guitar

Regards.

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala I think you can close here.
