### ISSUE TITLE
Music, Instruments, Music software icons

### ISSUE THREAD

**Issue by damusix** [FortAwesome/Font-Awesome#8216]
Much music! Many icons!

I did some research on requests for music icons. There's a lot, and I'm going to reference the ones I came across. I'm currently working for a music festival, for which we have 3 different websites (and more coming), all of them using FontAwesome. But I'm also a musician and would like to make apps / websites for musicians / about music, etc. Would be sweet if we had music icons. I think it would benefit sites on musicians, bands, DJs, producers, events, festivals, studios, audio software, music web apps, etc.

## What I had in mind:

Live:
* **fa-band**
* **fa-dj**
* **fa-party** or **fa-crowd**
* **fa-{instrument}** [#5059](https://github.com/FortAwesome/Font-Awesome/issues/5059) This is sweet. violin, conga, piano, saxaphone, tumpet, harp.. But don't forget: Guitar, bass, drums and other live instruments.

Electronic:
* **fa-sound-board** (an oldschool SSL)
* **fa-drum-machine**
* **fa-metronome** [#6232](https://github.com/FortAwesome/Font-Awesome/issues/6232)
**fa-turntable**
[#5737](https://github.com/FortAwesome/Font-Awesome/issues/5737)
* **fa-media-{media}** [#943](https://github.com/FortAwesome/Font-Awesome/issues/943) "CDs/discs, cassettes, 8track, reel to reel. A solid microphone, RCA 44 style. Not that typical mic icon everywhere.
On Air sign."  LP icon would also be nice [#2406](https://github.com/FortAwesome/Font-Awesome/issues/2406)
* **fa-amp** [#8215](https://github.com/FortAwesome/Font-Awesome/issues/8215) Specifically: bass-amp, guitar-amp
* **fa-soundwave** [#2084](https://github.com/FortAwesome/Font-Awesome/issues/2084)
* **fa-cable-{cable}** [#1590](https://github.com/FortAwesome/Font-Awesome/issues/1590) For cable types. For example (XLR)[http://image.dhgate.com/desc_279750929_00.jpg], (1/8 inch audio jack)[http://comps.canstockphoto.com/can-stock-photo_csp29311358.jpg], (1/4 audio jack)[http://png.clipart.me/graphics/previews/117/vector-audio-jack-connector-black-symbols_117934807.jpg], [cinch / aux ](https://d30y9cdsu7xlg0.cloudfront.net/png/49985-200.png)

Sheet music:
* **fa-clef-g**
* **fa-clef-f**
* **fa-clef-c**
* **fa-music-staff**
**fa-rest-{rest}** [#7217](https://github.com/FortAwesome/Font-Awesome/issues/7217) And other relevant rests
**fa-note-{note}** [#7186](https://github.com/FortAwesome/Font-Awesome/issues/7186) And other relevant notes

Music-math:
* **fa-wave-sine**
* **fa-wave-square**
* **fa-wave-saw**

Software logos:
* **fa-daw-flstudio**
* **fa-daw-reason**
* **fa-daw-protools**
* **fa-daw-ableton**
* **fa-daw-logic**

This may be too much. I just had a lot of ideas and wanted to get them all in one. It may be a better fit to have a separate suite of icons specifically for music / music software.

**Comment by tagliala** [comment]
> This may be too much.

Yes, unfortunately it is. We had to update our contributing guidelines to deal with requests like this: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

> It may be a better fit to have a separate suite of icons specifically for music / music software.

That would be better. My advice is to consider a custom solution: you could merge Font Awesome with a music related icon set. Take a look here

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.

Sorry, closing here

Feel free to open individual requests
