### ISSUE TITLE
Improve fa-microphone-slash

### ISSUE THREAD

**Issue by aethior** [FortAwesome/Font-Awesome#8218]
Maybe is a stupid detail...

`fa-slash` #3691 icon is planned for 5.0.0 milestone, and after checked the examples used on #1181 issue, I suppose the correct slash is the used in `fa-bell-slash-o` icon (black slash with white shadow below).

![example](https://cloud.githubusercontent.com/assets/1769227/11999063/fa27e830-aab5-11e5-905c-a0daf3a6c5be.png)

**Comment by tagliala** [comment]
Thanks!

Labeled as bug/enhancement, added to 5.0.0 milestone and assigned to @davegandy , so he will eventually take a look

**Comment by aethior** [comment]
**Note:** It is also important to change the direction of the slash #1721.

**Comment by tagliala** [comment]
True

- [] bell-slash-o
- [] bell-slash
- [] microphone-slash
- [] eye-slash

**Comment by sensibleworld** [comment]
Closing this, as it's referenced elsewhere (and mostly fixed!)
