### ISSUE TITLE
Icon request: icon-snowmobile

### ISSUE THREAD

**Issue by Gabriel82** [FortAwesome/Font-Awesome#8219]
I wish the icon on the snowmobile that I can use on my websites on snowmobiles.
![snowmobile](https://cloud.githubusercontent.com/assets/16438424/12004028/8402a1fc-ab39-11e5-83cd-aacca8b9a06f.jpg)

Like this.

Thanks

**Comment by aethior** [comment]
@tagliala `transportation (category)` label for this request?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/person-snowmobiling?f=classic&s=solid
