### ISSUE TITLE
Icon Request: fa-no-smoking

### ISSUE THREAD

**Issue by frenkees** [FortAwesome/Font-Awesome#8224]
It would be awesome to have a icon of "no smoking" - or just cigarette icon and we can stack fa-ban with this cigarette icon.

![image](https://cloud.githubusercontent.com/assets/16444726/12006694/50b89cae-abe1-11e5-97a9-032a779ec475.png)

![image](https://cloud.githubusercontent.com/assets/16444726/12006693/3a788224-abe1-11e5-8848-a2450c6a7e25.png)

**Comment by aethior** [comment]
Hi @frenkees,

This suggestion is duplicate of #726. Please +1 that.

Regards.

**Comment by tagliala** [comment]
closing here

**Comment by mikermcneil** [comment]
For people (and err me in the future) landing here from google:  If you're looking for just the circle without the cigarette, see https://github.com/FortAwesome/Font-Awesome/issues/7276
