### ISSUE TITLE
Icon Request: fa-fancy

### ISSUE THREAD

**Issue by tommygebru** [FortAwesome/Font-Awesome#8231]
Please consider making an icon for Fancy, many thanks!

**Comment by tommygebru** [comment]
Also one for Gitter!

**Comment by aethior** [comment]
Hi @tommygebru,

`fa-fancy` is duplicate of #2955 and `fa-gitter` is duplicate of #6535.

Regards.

**Comment by tagliala** [comment]
@aethior thanks
