### ISSUE TITLE
I need Marketplace icons

### ISSUE THREAD

**Issue by hmbashar** [FortAwesome/Font-Awesome#8235]
Hi i need marketplace icons, example: upwork, fiverr, freelacer, pph, etc.. can you do this? Please.

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

**Comment by tagliala** [comment]
You could consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
