### ISSUE TITLE
Icon Request: fa-blackberry-messenger

### ISSUE THREAD

**Issue by codedroids** [FortAwesome/Font-Awesome#8236]
Hi, i'm requesting BlackBerry Messenger icon. I need it for Contacts Page in my online store. because I also receive contacts / messages via blackberry messenger. 

The color of the BlackBerry Messenger icon is black

Thanks before.
I'm waiting for the icon :)

**Comment by aethior** [comment]
Hi @codedroids,

This suggestion is duplicate of #2189. Please +1 that.

Regards.
