### ISSUE TITLE
Icon Request: fa-meter

### ISSUE THREAD

**Issue by abdujuk** [FortAwesome/Font-Awesome#8237]
hi,

i want a meter measurement ico

thnx

**Comment by tagliala** [comment]
duplicate of #1096 , please +1 that request

closing here

**Comment by pitus** [comment]
+1 Actually, it's NOT a duplicate of #1096 as we need an actual Meter as in a Voltmeter or similar, not a Ruler / tape measure... from #1096 so please keep this one separate

**Comment by tagliala** [comment]
@pitus please provide an example and a better title

please also take a look at http://fortawesome.github.io/Font-Awesome/icon/tachometer/
