### ISSUE TITLE
Icon Request: fa-sound-wave

### ISSUE THREAD

**Issue by AndreLGava** [FortAwesome/Font-Awesome#8243]
A sound wave icon as this
http://static1.squarespace.com/static/5006e57c84ae2a41e73b4416/t/5069e52384ae2e32baf96ee6/1349117220192/iconmonstr-sound-wave-4-icon.png

**Comment by aethior** [comment]
Duplicate of #2084. Please +1 that.

You can propose your example there.

**Comment by AndreLGava** [comment]
thanks
