### ISSUE TITLE
Icon Request: fa-face-recognition

### ISSUE THREAD

**Issue by AndreLZGava** [FortAwesome/Font-Awesome#8244]
a icon to ilustrate something complex like this
http://resources2.news.com.au/images/2010/06/03/1225874/822850-face-recognition.jpg

**Comment by tagliala** [comment]
The example is very hard to fit in a 14px icon

**Comment by AndreLGava** [comment]
![icon-facial-recognition3](https://cloud.githubusercontent.com/assets/11870561/12069635/f1ae421c-b023-11e5-91c3-d81e06257aae.png)
![icon-facial-recognitiond](https://cloud.githubusercontent.com/assets/11870561/12069636/f6c7def2-b023-11e5-87f6-5f3571f8b2ed.jpg)


Maybe something like this?

**Comment by x43x61x69** [comment]
@AndreLZGava I think that's a bit confusing and too complicate for its purpose, also not gender friendly. If it's a facial recognition "icon", it's better be more simple and focusing on the face pattern like Apple did on the iPhone X.

I use `fa-smile` for now, but it has no nose to differentiate from an normal emoji smiley.

**Comment by lhunath** [comment]
This is very useful for action buttons that are supposed to trigger biometric authentication through face recognition such as FaceID.

[](https://static.thenounproject.com/png/1280817-200.png)
[](https://cdn3.iconfinder.com/data/icons/new-apple-product-solid/24/face_recognition-512.png)
[](https://cdn.iconscout.com/icon/premium/png-256-thumb/biometric-faceid-501498.png)

**Comment by sensibleworld** [comment]
<img width="680" alt="Screen Shot 2021-03-30 at 12 33 58 PM" src="https://user-images.githubusercontent.com/529604/113023957-33f66c00-9154-11eb-9981-93ea88137185.png">

A simplified version of this is now available in the latest alpha release of version 6: http://fontawesome.com/download
