### ISSUE TITLE
Icon Request: fa-molecule

### ISSUE THREAD

**Issue by AndreLGava** [FortAwesome/Font-Awesome#8246]
an icon to ilustrate molecules like this
http://previews.123rf.com/images/molekuul/molekuul1402/molekuul140200031/25767675-Propylparaben-paraben-preservative-molecule-flat-icon-style-Oxygen-and-carbon-atoms-shown-as-circles-Stock-Vector.jpg

**Comment by aethior** [comment]
Duplicate of #5190. Please +1 that.

**Comment by AndreLGava** [comment]
thanks
