### ISSUE TITLE
Icon Request: icon-id-card (icon-name-card/icon-name-tag/icon-contact)

### ISSUE THREAD

**Issue by masteroleary** [FortAwesome/Font-Awesome#825]
Based off credit card icon except with a square on the left and some lines on the right of that square representing a picture id.

**Comment by jpdonaghy** [comment]
+1

**Comment by cjdenterprises** [comment]
+1

**Comment by olore** [comment]
+1

**Comment by k80** [comment]
Was looking for a vCard icon

**Comment by BugHunter2k** [comment]
+1

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-69638974

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-44058835

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-35040875

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-35037839

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-25543080

**Comment by tagliala** [comment]
+1 https://github.com/FortAwesome/Font-Awesome/issues/618#issuecomment-18439361

**Comment by benjmiller86** [comment]
+1

**Comment by pburke** [comment]
+1

**Comment by cyrilschumacher** [comment]
+1

**Comment by seht** [comment]
+1

**Comment by NanoThemes** [comment]
+1

**Comment by grantneufeld** [comment]
+1, vCard-themed

**Comment by sanz0** [comment]
+1?

**Comment by billdami** [comment]
+1

**Comment by spfoos** [comment]
+1

**Comment by ninapavlich** [comment]
+1

**Comment by rumgbis** [comment]
+1

**Comment by xande** [comment]
+1

**Comment by bart1990** [comment]
+1

**Comment by robgolbeck** [comment]
+1
A lot of the sites I build have bio pages with links to download the person's vCard. Would love an icon for it.

**Comment by AustinWinstanley** [comment]
+1

**Comment by s-melanson** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by shyper-ideler** [comment]
+1

**Comment by nlsbln** [comment]
+1

**Comment by richafur** [comment]
+1

**Comment by dineiar** [comment]
+1

**Comment by Nutzzz** [comment]
+1

**Comment by erikzrekz** [comment]
+1

**Comment by jarnovanrhijn** [comment]
+1

**Comment by Ralphiuss** [comment]
+1

**Comment by xxinfinityxx** [comment]
+1

**Comment by taalendigitaal** [comment]
+1

**Comment by jbenner-radham** [comment]
+1

**Comment by BryanSaxon** [comment]
+1

**Comment by licatajustin** [comment]
+1

**Comment by EclipseOrigins** [comment]
+1

**Comment by joeuttaro** [comment]
+1

**Comment by JBValo** [comment]
+1

**Comment by funkymonk91** [comment]
+1

**Comment by liptonbeer** [comment]
+1

**Comment by danielsantiago** [comment]
+1

**Comment by marcdegeus** [comment]
+1

**Comment by rabrowne85** [comment]
+1

**Comment by fannar** [comment]
+1

**Comment by andrewchernow** [comment]
+1

**Comment by masteroleary** [comment]
I don't mean to come off bad, I love font-awesome and appreciate being able to use it for free. I get +1 emails all the time. Its obviously something many people want. When will we see this icon added to the font?

**Comment by tagliala** [comment]
@masteroleary this icon is scheduled for 5.0.0

If you are bothered by all notifications, there is a button on the right

![image](https://cloud.githubusercontent.com/assets/556268/9139359/1dc70fb8-3d2a-11e5-8497-b104fa2bb827.png)

**Comment by masteroleary** [comment]
Nope, not bothered. Thanks for the quick reply!

**Comment by jphellemons** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by Elorfin** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by tsilbermann** [comment]
+1

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by cjhannon84** [comment]
+1

**Comment by carrymetwo** [comment]
+1

**Comment by Ralphiuss** [comment]
+9001

**Comment by ethan-agencyQ** [comment]
+1

**Comment by machang** [comment]
+1

**Comment by JayHoltslander** [comment]
+2 (Me plus coworker)

**Comment by Googlecloud12** [comment]
+2 (Me Plus Coworker )

**Comment by raehalme** [comment]
+1

**Comment by coryisakson** [comment]
+1

**Comment by katili** [comment]
+1

**Comment by Mariana-Moreno** [comment]
+1

**Comment by RogerCD** [comment]
+1

**Comment by iamjon** [comment]
+1

**Comment by steiha** [comment]
+1

**Comment by EARNEST** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by ergener** [comment]
+1 meanwhile you can use something like this

https://jsfiddle.net/ddo3wx75/

**Comment by ninapavlich** [comment]
Thanks @ergener! That's a smart work-around!

**Comment by G-Driver** [comment]
@ergener cool, great work-around solution

**Comment by JayHoltslander** [comment]
@ergener Nice!

**Comment by pitus** [comment]
+1

**Comment by jreljac** [comment]
+1

**Comment by stefankellens** [comment]
+1

**Comment by stefankellens** [comment]
+1

**Comment by SouleDesigns** [comment]
+1

**Comment by kingsloi** [comment]
+1

**Comment by bcosca** [comment]
+1

**Comment by acjbizar** [comment]
+1 very much.

Also, suggested aliases: fa-rolodex-card, fa-vcard, fa-contact-card.

**Comment by mokrinsky** [comment]
+1

**Comment by bierik** [comment]
+1

**Comment by jaime-franco** [comment]
+1

**Comment by schoutenzekerheid** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-id-card was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by KngHawkon** [comment]
+1

**Comment by toddjcrane** [comment]
+1

**Comment by spoonerWeb** [comment]
+1

**Comment by ijando** [comment]
+1

**Comment by faytekin** [comment]
+1

**Comment by enco164** [comment]
+1

**Comment by mshovelt** [comment]
+1

**Comment by Jefftopia** [comment]
+2

**Comment by KingDaddy** [comment]
+1

**Comment by chiwanpark** [comment]
+1

**Comment by w3soto** [comment]
+1

**Comment by injaon** [comment]
+1

**Comment by leotm** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by argonautical** [comment]
+1

**Comment by DarkSmile92** [comment]
+1

**Comment by hannan-azam** [comment]
+1 So many people have already requested it and this ticket is open since Mar 2013. Still it hasn't been added to the library. :-1:

**Comment by roxanajula** [comment]
+ 1

**Comment by YourBrainEatsYou** [comment]
+1

**Comment by laromicas** [comment]
+1 I like this one
http://www.dangnelson.com/svg/vcard.svg

**Comment by omer414** [comment]
+1 to laromicas

**Comment by sergiodlopes** [comment]
+1

**Comment by nickbouton** [comment]
+1 for something like an index card (one for people, one for text):

![image](https://cloud.githubusercontent.com/assets/169988/16630780/b89a954e-4370-11e6-8456-b900ad9718e0.png)

![image](https://cloud.githubusercontent.com/assets/169988/16630841/ee191010-4370-11e6-9939-c8f923c7c13c.png)

**Comment by soFFe** [comment]
+1

**Comment by enco164** [comment]
+1

**Comment by harmjanluth** [comment]
+1

**Comment by andrewnetherton** [comment]
Another +1 here... 

Even if it's not called a vCard icon, a contact icon, index card icon, anything... please?

**Comment by JamesJGarner** [comment]
+1

**Comment by aNinjaMonk** [comment]
+1

**Comment by igordelorenzi** [comment]
+1

**Comment by aznxfrost** [comment]
+1

**Comment by chrisjmccrum** [comment]
+1

**Comment by oucil** [comment]
+1

**Comment by marketica** [comment]
+1

**Comment by wietsedevries** [comment]
+1

**Comment by alobakov** [comment]
+1

**Comment by Killerbear** [comment]
+1

**Comment by davegandy** [comment]
Adding lots of new icons to 4.7.0-wip branch, including address-book, address-book-o, address-card, address-card-o. ID Card is in progress. Stay tuned.

**Comment by davegandy** [comment]
Added id-badge, id-card, and id-card-o to 4.7.0-wip branch. Closing.

**Comment by davegandy** [comment]
Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!
