### ISSUE TITLE
Icon request: fa-monero

### ISSUE THREAD

**Issue by sammy007** [FortAwesome/Font-Awesome#8258]
Hello, Dave. Would be very cool to see [Monero](https://getmonero.org) icon added to font-awesome.

> Monero is a secure, private, untraceable currency. It is open-source and freely available to all.
> Monero provides a place where your financial activities are private. Monero is one of the leading cryptocurrencies in the post-Bitcoin world, and it is built on principles of privacy, decentralization, and scalability.

About: https://getmonero.org/knowledge-base/about

Monero's branding package https://downloads.getmonero.org/resources/branding.zip already has logo in several formats and even in .ai (Adobe Illustrator) format.

![monero-logo](https://cloud.githubusercontent.com/assets/7374093/12072328/512ba9e6-b0fb-11e5-9adc-ca45bf762b3d.png)

Increasing user base and adoption definitely requires an icon in the FontAwesome package which is de-facto standard in a modern website design so far. Thanks in advance.

**Comment by PsychicCat** [comment]
I would also love to see the Monero icon added!

**Comment by fluffypony** [comment]
Thirded!

**Comment by wpalczynski** [comment]
Fourthed!!

**Comment by wpalczynski** [comment]
Fourthed!!

**Comment by polkovnikov-ph** [comment]
There are [6874872](http://trends.builtwith.com/widgets/Font-Awesome) websites with Font Awesome. Is Monero that popular that millions of their users should get their own copy of the icon?

**Comment by fluffypony** [comment]
@polkovnikov-ph how do you measure popularity? There are lots of brands that have Font Awesome icons that are not massively well-known or widely popular (eg. modx, viacoin, ioxhost, odnoklassniki, skyatlas). I'd argue that usefulness trumps popularity, and since a web designer may want to use a Font Awesome icon to indicate that the site accepts Monero payments there is a degree of usefulness to adding the icon.

**Comment by polkovnikov-ph** [comment]
@fluffypony Odnoklassniki has several million visitors daily. Modx has 700 stars on github. Monero has just 109.

To help web designers there should be a branding page with an SVG icon. It's not a big deal to compile own font with extra icons. Though, the vice versa also applies. If one doesn't need extra icons and cares for page load times (I doubt there's a project that needs a third of them simultaneously) he could easily strip the font too.

I'm just unsure if it's right to ask people to help advertising the cryptocurrency project for free.

**Comment by wpalczynski** [comment]
Out of curiosity how did viacoin get in there?  Surely monero is more useful than viacoin and likely much more popular.

**Comment by fluffypony** [comment]
@polkovnikov-ph you're picking and choosing two examples. I could equally argue that modx is significantly older (Monero has only existed for 20 months), so the "stars" are irrelevant. I could similarly argue that Viacoin only has 35 stars (https://github.com/viacoin/viacoin), which means Monero is more than qualified. I could similarly argue that [ioxhost is ranked the 9.48 millionth](http://www.alexa.com/siteinfo/iox.host) most popular site in the world, whereas [getmonero.org is the 631717th most popular site](http://www.alexa.com/siteinfo/getmonero.org). Or how about [Sky Atlas with their 88 Twitter followers](https://twitter.com/skyatlascom) vs. [Monero's 1231 Twitter followers](https://twitter.com/monerocurrency)?

It would be unconscionable for these others to exist and then try and argue that Monero is somehow not worthy of consideration.

We have [a branding pack](https://downloads.getmonero.org/resources/branding.zip) available, but given that compiling one's own web font is no trivial task for the amateur web developer (and Font Awesome is widely available on popular CDNs) it stands to reason that the FA route would be more appealing.

I also can't agree with your argument that a Font Awesome icon is "advertising". Monero isn't a for-profit company that would benefit from having an icon. I doubt having a Font Awesome icon will make any difference at all. But regardless, Monero *is* a free, fair, open-source project with screeds of users all over the planet, and there is a very practical case to be made for a Font Awesome icon.

**Comment by BesrourMS** [comment]
+1

**Comment by Alex-Fortin** [comment]
+1

**Comment by 4lm** [comment]
+1 make Monero awesome!

**Comment by 4lm** [comment]
Actually, Monero is already awesome, so just include the icon :)

**Comment by MalMen** [comment]
I think it makes sense to add it as many people are starting to acept monero as a form of payment

**Comment by aminorex** [comment]
+1 support for this issue

**Comment by woodser** [comment]
I support this issue.  Thanks.

**Comment by danvctr** [comment]
+1!

**Comment by gsee** [comment]
+1

**Comment by Ashaman-** [comment]
+1

**Comment by ibrightly** [comment]
+1

**Comment by recodesign** [comment]
+1 would be extremely useful.

**Comment by jbrukh** [comment]
+1

**Comment by jakobstrauch** [comment]
+1

**Comment by JoshLambda** [comment]
+1

**Comment by ParsifalX** [comment]
As a web developer, i think it would be a nice addition

**Comment by amoebatron** [comment]
Please add this!

**Comment by antanst** [comment]
+1

**Comment by athanclark** [comment]
+9001

**Comment by kenshi84** [comment]
+1

**Comment by flyasapegasus** [comment]
+1 <3

**Comment by JohnHanks** [comment]
yes

**Comment by stefioan** [comment]
Awesome! +1!

**Comment by devinjdawson** [comment]
i think Monero should add Font Awesome

**Comment by allienworks** [comment]
Or just take the initiative and do it the other way around: [Cryptocoins Icon Pack](http://labs.allienworks.net/icons/cryptocoins/) (Yes, Monero included as well as other ~100 coins)

**Comment by dot3bumpmap** [comment]
Definitely!

**Comment by palexande** [comment]
Please add Monero to Font Awesome.

**Comment by paulshapiro** [comment]
+1!

**Comment by moneroj** [comment]
its time.

**Comment by xmr-eric** [comment]
I also agree. Monero should have its own!

**Comment by hendi** [comment]
:+1:

**Comment by papaLazzarou** [comment]
I need it!

**Comment by GalerasVolcano** [comment]
Please add Monero!.

**Comment by xionicgrift** [comment]
+11111

**Comment by maitscha** [comment]
+1

**Comment by lizaSB** [comment]
I am also developing a website right now and would love to indicate that Monero is welcome as a payment platform on my website. Having this included in FA would make this trivial!

**Comment by jason5515** [comment]
+1

**Comment by furball514** [comment]
Was just going to request a Monero icon. It would be very useful indeed.
+1

**Comment by oyvkva** [comment]
+1 Yep, would be great

**Comment by janowitz** [comment]
Would be really great!

**Comment by snirp** [comment]
We still don't have this? Make it happen!

**Comment by Jaqueeee** [comment]
+1

**Comment by jwinterm** [comment]
+me +1

**Comment by Cryptojo3** [comment]
YAAAASSSSS

**Comment by stoffu** [comment]
+1

**Comment by maitscha** [comment]
+1 -- I need it

**Comment by luijoy** [comment]
1+

**Comment by keledoro** [comment]
+1

**Comment by M5M400** [comment]
This is missing badly on my monero related websites!

**Comment by erciccione** [comment]
Add Monero Please

**Comment by QuickBASIC** [comment]
Definitely would be awesome. I agree with what @Fluffypony said; stars on a project aren't necessarily a good indicator of adoption, especially for a private untraceable cryptocurrency. 

Currently the /r/Monero subreddit has 11685 subscribers. Just last month Monero has 84193 transactions. It's #10 in cryptocurrencies by market cap.

**Comment by systemroot** [comment]
+1

**Comment by rubysown** [comment]
+1

**Comment by sammy007** [comment]
https://twitter.com/fluffypony/status/903232636537196545

Thank you @davegandy.

**Comment by William2030** [comment]
+1
