### ISSUE TITLE
Icon Request: fa-power-*

### ISSUE THREAD

**Issue by ghflp** [FortAwesome/Font-Awesome#8260]
Completing fa-power-off icon I sometimes need a Power complete set of power symbol as IEC / IEEE description:
https://en.wikipedia.org/wiki/Power_symbol

IEC 5007 fa-power-on
IEC 5008 fa-power-off-o
IEC 5009 fa-power-off fa-power-standby
IEC 5010 fa-power-on-off
IEEE 1621 fa-power-sleep

**Comment by aethior** [comment]
Hi,

- [X] IEC 5007 `fa-power-on` (http://fontawesome.io/icon/minus/ rotated `fa-rotate-90`)
- [X] IEC 5008 `fa-power-off` (http://fontawesome.io/icon/circle-o/)
- [X] IEC 5009 `fa-power-standby` (http://fontawesome.io/icon/power-off/)
- [ ] IEC 5010 `fa-power-on-off` (Maybe create `fa-minus-circle-o`?)
- [ ] IEEE 1621 `fa-power-sleep` (Maybe create `fa-moon`?)

Regards.

**Comment by ghflp** [comment]
Ok.
fa-minus-circle-o with fa-rotate-90 and fa-moon seems that solves the system.

Thanks Aethior.

**Comment by caduvieira** [comment]
fa-moon #5700
fa-minus-circle-o #2417

**Comment by tagliala** [comment]
@caduvieira thanks

closing here

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
