### ISSUE TITLE
Icon Request: fa-goodreads

### ISSUE THREAD

**Issue by SonadoraCompulsiva** [FortAwesome/Font-Awesome#8261]
I want to use this new icon in my Blog, I need it because I am using the Twitter and Instagram icon and I wan to have something in that line. So I have that social network so I want to put it in the Blog.

Thanl you, you are amazing

**Comment by aethior** [comment]
Hi @SonadoraCompulsiva,

This suggestion is duplicate of #1715. Please +1 that.

Regards.
