### ISSUE TITLE
Icon Request: fa-affimity

### ISSUE THREAD

**Issue by magnetz** [FortAwesome/Font-Awesome#8265]
New Social Network: https://affimity.com
Very simple icon ;)

Thanks guys!
Preview:
![a4jygpfd](https://cloud.githubusercontent.com/assets/7317873/12088999/693b2af2-b2e0-11e5-8f01-a48940276c6f.png)

**Comment by aethior** [comment]
`affimity.com` domain is for sale and social networks have not activy since 2016 ([twitter](https://twitter.com/affimity) and [instagram](https://www.instagram.com/affimity/)).

cc/ @tagliala
