### ISSUE TITLE
Icon font update: Google, Google +

### ISSUE THREAD

**Issue by asmosis** [FortAwesome/Font-Awesome#8267]
On the cheatsheet the Google, Google Plus, and Google Plus Square are all displayed as the new icon. But, when I copy/paste them from the cheatsheet page they paste as the old icon – the lower case serif g instead of the new uppercase sans-serif G. I've downloaded the latest zip file today and re-installed the latest font files. Still happening.
<img width="893" alt="screen shot 2016-01-04 at 1 55 31 pm" src="https://cloud.githubusercontent.com/assets/16546312/12098997/3bc79226-b2eb-11e5-9042-9020c180b836.png">
![screen shot 2016-01-04 at 1 58 17 pm](https://cloud.githubusercontent.com/assets/16546312/12098996/3bc779b2-b2eb-11e5-9895-de6d4d00c5a4.png)

**Comment by tagliala** [comment]
Hi, you should update the font file installed in your system

Leaving this open, let me know

**Comment by AndreLGava** [comment]
maybe its on your cache memory, please update your server cache and in your pc ctrl + f5

**Comment by heymagruder** [comment]
+1 I'm seeing the new icon on the font awesome site but when I add in <i class="fa fa-google-plus-square"></i> i see the old logo. 
<img width="362" alt="screen shot 2016-01-11 at 4 58 11 pm" src="https://cloud.githubusercontent.com/assets/5545077/12250490/886e4770-b884-11e5-8007-5dfe0b77e049.png">
<img width="758" alt="screen shot 2016-01-11 at 4 58 04 pm" src="https://cloud.githubusercontent.com/assets/5545077/12250489/88372d58-b884-11e5-8ec3-0aff1301a91f.png">

**Comment by heymagruder** [comment]
check that, I was using an old version of the build. Rookie mistake. Please disregard.

**Comment by asmosis** [comment]
I did update the font installed on my system and was still getting the old icon. That's why I posted this issue. But after a restart of my Mac, it started displaying the new icon. Seems good to go.

**Comment by tagliala** [comment]
:+1:

**Comment by angeladesign** [comment]
Hello, 
I'm having a google plus icon issue too... this site (http://test.nowitconnects.com) is displaying the old icon after moving it into a wordpress install!? It **was** displaying the new icon before the move! Thoughts?

**Comment by tagliala** [comment]
@angeladesign please check that a plugin is not using an outdated version of font awesome

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by angeladesign** [comment]
Thank You! Problem solved!
