### ISSUE TITLE
Icon Request: fa-arrow

### ISSUE THREAD

**Issue by MohitHasmukh** [FortAwesome/Font-Awesome#8269]
Hey,

Could you please create me this icon. I will be using it for one of my sidebars on my website. 
Thank you :)

![rightarrow](https://cloud.githubusercontent.com/assets/12733522/12113245/6c5d5c5a-b399-11e5-881b-a2221eaca951.jpg)

**Comment by tagliala** [comment]
Hi, please use http://fontawesome.io/icon/chevron-right/ or http://fontawesome.io/icon/angle-right/

closing here
