### ISSUE TITLE
Emotions

### ISSUE THREAD

**Issue by Roshinjose167** [FortAwesome/Font-Awesome#8275]
We need smiley
Smile, Sad Big smile, Geek, Cool, Surprised icons

**Comment by tagliala** [comment]
Sorry, I need to close this request

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

There are other requests about emoticons, like #1968
