### ISSUE TITLE
Icon request: icon-newsletter

### ISSUE THREAD

**Issue by carminka** [FortAwesome/Font-Awesome#8277]
Hi,
I would like an icon like the newspaper icon,except that it should be for subscribing to our newsletter. COuld you please add one like this? (see attached png)
<img width="311" alt="newsletter-icon" src="https://cloud.githubusercontent.com/assets/16577390/12144948/5c51bbb0-b48b-11e5-82c7-7a87bc36a399.png">
THANKS for your great icons!
peace,
carmin

**Comment by pitus** [comment]
+1 for a generic Newsletter icon - for subscription

**Comment by caduvieira** [comment]
Very similar to http://fortawesome.github.io/Font-Awesome/icon/newspaper-o/

**Comment by tagliala** [comment]
This request has a poor title: the object does not represent a newsletter, also because newsletter is something abstract

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

I would rename this fa-newspaper-unfolded-o, but I would expect a rectangular icon. This is similar to #6613 (which also has a poor title)

**Comment by quadrifolia** [comment]
just build one light newsletter icon for myself. maybe this works for others as well…

![newsletter](https://user-images.githubusercontent.com/630635/43643245-f3eeadf0-972a-11e8-84e3-10b7be907bcf.png)

[newsletter.svg.txt](https://github.com/FortAwesome/Font-Awesome/files/2257360/newsletter.svg.txt)

**Comment by Dashue** [comment]
Bit late to the party but could also use a newsletter icon.
@quadrifolia how would one use the one you've attached?

**Comment by tagliala** [comment]
Closing here, we can use https://fontawesome.com/icons/envelope-open-text?style=solid to represent a newsletter

Feel free to provide a new example so I can reopen
