### ISSUE TITLE
Icon request: icon-factory

### ISSUE THREAD

**Issue by enovision** [FortAwesome/Font-Awesome#8279]
![sh_014786](https://cloud.githubusercontent.com/assets/1536241/12157164/289156ba-b4d0-11e5-9b46-b25844833192.jpg)

**Comment by aethior** [comment]
Hi @enovision,

There is a 'fa-industry' (http://fontawesome.io/icon/industry/) icon.

@gtagliala maybe is good idea add factory as synonym for industry icon.

Regards.

**Comment by websiteduck** [comment]
Having a few windows would be nice, similar to fa-building.

**Comment by tagliala** [comment]
Done, thanks. It will be available after next doc build, that are up to Dave

Added as a filter, so `fa-industry` should appear inside docs when searching for `factory`

**Comment by enovision** [comment]
Great, this is just what I hoped for. Thank you very much.

**Comment by giampaolo1986** [comment]
Hi all, thanks for this community.

I try to add fa-industry but the icon doesn't show nothing... whats wrong? The other icon are showed correctly. Someone have the same problem?

Thank You.
