### ISSUE TITLE
Icon request: icon-spider

### ISSUE THREAD

**Issue by VanGTO** [FortAwesome/Font-Awesome#828]
Hey buddy, would love some additional icons. Here are a few examples of what im looking for:
~~A set of scales~~
~~A cigarette and/or a no smoking icon~~
~~A syringe~~
~~A soccer ball and last but not least...~~
A spider!

Much appreciated, your work is awesome!

**Comment by nicolasteodosio** [comment]
+1

**Comment by BjBlazkowicz** [comment]
+1 
Use case: webcrawler

**Comment by j0ney3** [comment]
+1

**Comment by sw0o0sh** [comment]
+1

**Comment by pkrysiak** [comment]
+1

**Comment by Squidies** [comment]
+1

**Comment by wolfgangmeyers** [comment]
+1

**Comment by ecology-rocks** [comment]
+1!

**Comment by jwnip** [comment]
+1

**Comment by Esysteme** [comment]
+1

Spider (engine of MySQL)

**Comment by kirandasika** [comment]
+1

**Comment by senseysensor** [comment]
+1

**Comment by Esysteme** [comment]
Can you add this (i made in SVG) : 

[spider-icon_vector.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/375862/spider-icon_vector.svg.zip)

**Comment by gigi** [comment]
+1

**Comment by OmathiasO** [comment]
+1

I need this icon for a webcrawler application, too!

**Comment by Esysteme** [comment]
can you include spider icon i made in SVG ?

**Comment by hworm4** [comment]
+1

**Comment by o8e** [comment]
+1

**Comment by Esysteme** [comment]
can you add my spider ? (put this in GNU/GPL v3) look my zipfile

the work is done can you tell me where is the problem to integrate it to FA ?

**Comment by Esysteme** [comment]
Finally !!!!!!!!!!!!!


thx you a lot !
