### ISSUE TITLE
Icon request: icon-typewriter

### ISSUE THREAD

**Issue by vimamica** [FortAwesome/Font-Awesome#8281]
Is it possible to add a typewriter like this?
![1966-200](https://cloud.githubusercontent.com/assets/13658140/12164594/1d2128c2-b517-11e5-9458-473c067cfe6e.png)

**Comment by polkovnikov-ph** [comment]
What should it stand for?

**Comment by RoughdraftDC** [comment]
I think it should stand for writing. I need a nice icon to emphasize that I can help my clients with editing and creating their content.

**Comment by nickbe** [comment]
I second this. The typewriter would stand for "Authoring". In my view a much better way to express the action of writing for a blog.

**Comment by seezee** [comment]
+1

**Comment by sarahfriedlander** [comment]
+1

**Comment by Cooperwd01** [comment]
+1 would love this - again to signal writing

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/typewriter?style=solid
