### ISSUE TITLE
Icon Request : TextBox

### ISSUE THREAD

**Issue by ryanlin1986** [FortAwesome/Font-Awesome#8285]

**Comment by AndreLGava** [comment]
You can use this icon http://fontawesome.io/icon/list-alt/ as a textbox depending on your pourpose

**Comment by ryanlin1986** [comment]
Thanks for the reply, but I not suited well for my scenario, I need something like this:
![qq 20160108181225](https://cloud.githubusercontent.com/assets/11850439/12195606/6451ae52-b633-11e5-9a32-f02e62327493.png)

**Comment by tagliala** [comment]
could you please post an example?

**Comment by polkovnikov-ph** [comment]
For GUI editors like [Glade](https://glade.gnome.org/images/glade-main-page.png) or [VB Form Designer](http://www.vbtutor.net/vb_book/images/figure2.1.jpg) a textbox icon would be very useful.

**Comment by tagliala** [comment]
It seems a duplicate of #1810

**Comment by polkovnikov-ph** [comment]
A template image there seems not very much related to me, but I think you're right.

**Comment by sensibleworld** [comment]
We have a few options that might work for this now:

https://fontawesome.com/icons/pen-field?s=solid&f=classic
https://fontawesome.com/search?q=input%20&o=r
