### ISSUE TITLE
Icon Request: fa-rounded-arrow-top / fa-rounded-arrow-right / fa-rounded-arrow-down /  fa-rounded-arrow-left / 

### ISSUE THREAD

**Issue by takumaterasu** [FortAwesome/Font-Awesome#8287]

**Comment by takumaterasu** [comment]
[Uploading rounded-arrow-down.pdf…]()
[Uploading rounded-arrow-left.pdf…]()
[Uploading rounded-arrow-right.pdf…]()
[Uploading rounded-arrow-up.pdf…]()

**Comment by tagliala** [comment]
Please also consider custom css: https://jsfiddle.net/tagliala/syduuue9/12/

**Comment by aethior** [comment]
Hi @takumaterasu,

These icon were added in v3.1.0.

`fa-circle-chevron-up`: https://fontawesome.com/icons/circle-chevron-up
`fa-circle-chevron-down`: https://fontawesome.com/icons/circle-chevron-down
`fa-circle-chevron-left`: https://fontawesome.com/icons/circle-chevron-left
`fa-circle-chevron-right`: https://fontawesome.com/icons/circle-chevron-right

Regards.

cc/ @tagliala
