### ISSUE TITLE
Icon request: icon-shopping-bag

### ISSUE THREAD

**Issue by soravengeur** [FortAwesome/Font-Awesome#829]
Hello, thanks a lot for your hard work, this is really amazing.

Should it be possible to add a shopping bag, like the one of glyphicons ?

Thanks a lot !

**Comment by KjellDaSensei** [comment]
+1

**Comment by stevewyzli** [comment]
Any word on this? It seems really high demand and pretty simple, no!!!?? :D
thx

Steve Avery
CEO & Co-Founder
wyzli.com
<http://t.signaledue.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs7dKWm-N8qlTpjRJ9h0W8qSyyn56dQ-Qf1T0DJg02?t=http%3A%2F%2Fwyzli.com%2F&si=5301772418547712&pi=0c9330d8-26b1-42d9-c3a2-52e8d2b056f5>
| steve@wyzli.com | +972-52-4652446

**Comment by pixelchutes** [comment]
I bet we'll see this in either the premium Fonticons service: https://fonticons.com/ or from the BlackTie kickstarter: https://www.kickstarter.com/projects/232193852/font-awesome-black-tie

Otherwise, someone from the community would probably need to submit a PR and hope it gets merged into FontAwesome at this point...

**Comment by k80** [comment]
+1, prefer straight vertical sides rather than slanted, so it doesn't look too much like a purse.

**Comment by Gabidimartino** [comment]
+1 CMON ON !!!!!

**Comment by designiq** [comment]
+1

**Comment by raphaelpetrini** [comment]
+1

**Comment by killinit** [comment]
+1

**Comment by rmtweb** [comment]
+1

**Comment by HandyAndyShortStack** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by shturm** [comment]
+1

**Comment by sjaakdg** [comment]
+1

**Comment by cpar917** [comment]
+1

**Comment by dngunraj** [comment]
+1

**Comment by meetshawn** [comment]
+1

**Comment by igarcez** [comment]
+1

**Comment by saas786** [comment]
+1

**Comment by jjsanz** [comment]
+1

**Comment by chekiesco** [comment]
+1

**Comment by stevenchu** [comment]
+1

**Comment by AndrewEastwood** [comment]
+1

**Comment by ron-ardesign** [comment]
+1

**Comment by larsbo** [comment]
+1

**Comment by danabrey** [comment]
+1

**Comment by sandywoodruff** [comment]
+1
Please :+1:

**Comment by bogowicz** [comment]
+1

Dear Fort Awesome Team,

If there is such a possibility 
I really need a shopping bag icon, 
for boutique-type eshop site.

Smaller companies need suitable, 
seemly cart icon than the metal basket 
which is associated with a larger malls.

![sb](https://cloud.githubusercontent.com/assets/3184941/8003293/7ee5da1c-0b76-11e5-88b4-2ddcf6a38f32.jpg)

**Comment by Khaleel** [comment]
+1

**Comment by jonasskafte** [comment]
+1

**Comment by mcfee1979** [comment]
+1

**Comment by Australhawk** [comment]
+1 omg 2 years

**Comment by mutuku** [comment]
+1

**Comment by demartini** [comment]
+1

**Comment by rubengc** [comment]
+1

**Comment by josangarcia** [comment]
+1

**Comment by CandiceB** [comment]
+1

**Comment by Saluev** [comment]
+1

**Comment by andrewhowdencom** [comment]
+1

**Comment by EBonar** [comment]
+1
Here's another idea for the style
![shoppingicon-grey](https://cloud.githubusercontent.com/assets/11934450/8783497/c73ca6cc-2ee1-11e5-9404-58a4442ad149.png)

**Comment by wpexia** [comment]
+1

**Comment by shaimanor** [comment]
I didn't see this in fontawesome so why is it a closed issue?

**Comment by tagliala** [comment]
@shaimanor this issue is not closed

**Comment by simonfranz** [comment]
+1

**Comment by lyhil** [comment]
+1

**Comment by jfenig** [comment]
+1
Thank you!

**Comment by leoquijano** [comment]
+1 
Thanks!

**Comment by rowby** [comment]
I would also like a shopping bag icon.  Here's an example,   

![shopping-bag2](https://cloud.githubusercontent.com/assets/3315955/9157278/ae97b118-3eac-11e5-9411-e2d60fb7b2a3.png)
  
Is this even the correct place to make this request?  Is anyone at Fontawesome looking at these requests.  The original request I see here was in 2013.

Just want to be sure this is where we make these requests?

Best

Rowby Goren

**Comment by marjoriebennington** [comment]
+1 
Thanks!

**Comment by haddigan** [comment]
+1

**Comment by jizambrana** [comment]
+1

**Comment by jmnsf** [comment]
+1

**Comment by Medeka** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by ffxsam** [comment]
:+1: 

Really surprised this isn't part of the collection still. It was first mentioned a year ago.

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by RobertDeniszczyc** [comment]
+1

**Comment by emilstahl** [comment]
+1

**Comment by bangerkuwranger** [comment]
+1

**Comment by herrherrmann** [comment]
+1

**Comment by cutemachine** [comment]
+1

**Comment by NathanGiesbrecht** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by marcoantani** [comment]
+1
Please add it. Thank you very much.

**Comment by FDMadeira** [comment]
+1

since 5 march 2013 a lots of people are asking for this.

Isn't that enough?

**Comment by alex-seedcms** [comment]
+1

**Comment by juhaelee** [comment]
+1

**Comment by martingg88** [comment]
+1 please

**Comment by kwaaui** [comment]
+1

**Comment by SerzhSharapa** [comment]
+1

**Comment by Kalpeshk9967016292** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by leetskills** [comment]
+1

**Comment by davegandy** [comment]
Sorry it took so long! Added to 4.4.1-wip branch. Closing.

**Comment by AngerLiss** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
@AngerLiss, it's already available: http://fontawesome.io/icon/shopping-bag/.

**Comment by AngerLiss** [comment]
@PeterShaggyNoble kinda looks like a purse, do you know if with the new sets, they're going to be doing more within this category?
