### ISSUE TITLE
Icon Request: Primitive shape

### ISSUE THREAD

**Issue by ryanlin1986** [FortAwesome/Font-Awesome#8298]
Line, Rectangle, Ellipse, Path, Polygon, Polyline etc.

**Comment by tagliala** [comment]
sorry, can't leave this open

there are a couple of duplicates, please use the search function

then take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
