### ISSUE TITLE
Github search not working.

### ISSUE THREAD

**Issue by webscot** [FortAwesome/Font-Awesome#8301]
Every time I search an icon name such as "radiation" in the repository search bar at the top of the page, I get nothing. Yet, there are already entries. Any suggestions or resolutions so I'm not duplicating?

**Comment by tagliala** [comment]
Do you mean here on the github repository?

I'm actually getting 7 issues. We have not control of the search feature here, you should get in touch with github if you are experiencing issues

Partial screenshot:
![image](https://cloud.githubusercontent.com/assets/556268/12212541/d879bfda-b66b-11e5-980d-ef0c2871a1ba.png)

Please try again. Closing here but feel free to comment
