### ISSUE TITLE
Icon request: forgot-password

### ISSUE THREAD

**Issue by mattgrannary** [FortAwesome/Font-Awesome#8305]
It would be great if there were an icon for a forgot password link. I like the idea of using icons instead of copy for header nav links (more universal) and FA seems to be missing one to describe 'password recover' or similar.

Here's an example:

![forgot_password](https://cloud.githubusercontent.com/assets/1192044/12219258/c92595ce-b709-11e5-9815-d23e789cdd4a.png)

Thanks for the great icon set!

**Comment by mizerydearia** [comment]
+1

additional examples at google images: https://www.google.com/search?tbm=isch&q=forgot%20password%20icon&tbs=imgo:1

**Comment by tagliala** [comment]
let's use  #8424 which have a better title
