### ISSUE TITLE
Icon request: fish

### ISSUE THREAD

**Issue by channaaah** [FortAwesome/Font-Awesome#8307]
![fishes7](https://cloud.githubusercontent.com/assets/16646180/12231250/6842c63e-b856-11e5-8a9b-7d02da9fbce7.png)

I would love to see a fish icon so I can use it for my categories!

**Comment by AndreLGava** [comment]
This is related to 
https://github.com/FortAwesome/Font-Awesome/issues/2722
plese +1 on that

**Comment by tagliala** [comment]
@AndreLGava thanks

closing here as a duplicate of #2722

**Comment by tagliala** [comment]
I suspect this could be a request for a tropical fish. In this case, feel free to change the request title and comment and I will reopen

**Comment by channaaah** [comment]
Any fish will do the job, I don't want to be difficult, haha! Thanks
