### ISSUE TITLE
Icon Request: fa-ancestry

### ISSUE THREAD

**Issue by anth-3** [FortAwesome/Font-Awesome#8311]
An Ancestry.com icon as part of the Brand Icons would be a great addition, and would be used as a way to link to Family Trees on Genealogy pages alongside Facebook and Twitter, etc. icons.

Example:
![fa-ancestry-example](https://cloud.githubusercontent.com/assets/1031024/12254372/578986b4-b8ad-11e5-997e-01a905591bf4.png)

**Comment by codynguyen1116** [comment]
+1

**Comment by tagliala** [comment]
dup of #5442, please +1 that request

closing here
