### ISSUE TITLE
Some icons are broken on Firefox

### ISSUE THREAD

**Issue by Simanas** [FortAwesome/Font-Awesome#8313]
Feels like I have searched entire interned, but nothing really solves my problem. Some of font-awesome icons are broken on Firefox (40.0) on my current project like this:

![screenshot from 2016-01-12 15 39 13](https://cloud.githubusercontent.com/assets/2435008/12264946/cc76b88a-b942-11e5-97a2-7feb1e8b962a.png)

While on google chrome they are all fine:
![chrome](https://cloud.githubusercontent.com/assets/2435008/12265012/2d95ae78-b943-11e5-903c-1841c4eae3fa.png)

I am on Linux Mint 17 Qiana OS.

**Comment by tagliala** [comment]
Please check that your application is not loading multiple version of fontawesome

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Ref  #1546

Leaving this open, let me know

**Comment by Simanas** [comment]
No, that's not the case. Cleared Firefox cache a few times. Removed my font awesome tag. All icons disappears, added the same link back, icons are back, but some are broken on Firefox.

**Comment by tagliala** [comment]
could you please provide a link to your website or create a fiddle showing the issue?

You can start with this one: https://jsfiddle.net/tagliala/syduuue9/

**Comment by Simanas** [comment]
Sorry can't give you a link. It's a closed system. 

Obviously looks there is some problem with my code as icons renders fine on jsfiddle and on fonts-awesome home page... Hmmm... Please leave this open, I will figure this out one way or an other and post here what was wrong in my case.

**Comment by Simanas** [comment]
I ended up serving font-awesome from CDN. I guess I should do more work with MIMES or CORS on my end to make it work from my server.
