### ISSUE TITLE
Bug: Percent

### ISSUE THREAD

**Issue by larsvansche** [FortAwesome/Font-Awesome#8317]
Hello, 

The fa-percent icon is not working. Me and a friend tried it, and it doesn't work for either one of us. I have tried it on different sizes, too, and I have even copied and pasted the <i> tag from the font awesome website. 

I hope this can be fixed. 

Regards, 
Lars

**Comment by tagliala** [comment]
Sorry, cannot confirm.

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay particular attention to point 2, 3, 4
