### ISSUE TITLE
Icon Request: fa-marketing

### ISSUE THREAD

**Issue by kevspadilla** [FortAwesome/Font-Awesome#8319]
Hi all, may request for an icon which will be used for navigation for marketing links.

Heres a sample image: 
http://hourglass-studios.com/wp-content/uploads/2014/04/VisualMarketing_Icon.png

Thanks!

**Comment by JeroenCollier** [comment]
+1

**Comment by scottux** [comment]
looks a lot like http://fontawesome.io/icon/line-chart/

**Comment by kevspadilla** [comment]
yeah @scottux, but maybe its better to have the bar graph. :smile:

**Comment by scottux** [comment]
i wonder what they look like stacked, maybe a tweak or two and the line
graph stacked on the bar graph could provide this appearance.

**Comment by kevspadilla** [comment]
oh thanks! let me try.. :+1:

**Comment by tagliala** [comment]
we need a better title for this request and a single color example

**Comment by tagliala** [comment]
duplicate of #6881, please +1 that request

closing here
