### ISSUE TITLE
Icon request: icon-biohazard

### ISSUE THREAD

**Issue by pblanchardie** [FortAwesome/Font-Awesome#832]
It would be great to have the BioHazard logo!
http://www.just-biohazard.pp.ua/newss/biohazard.gif

**Comment by Dygear** [comment]
+1

**Comment by nitmir** [comment]
![quarantine_icon](https://cloud.githubusercontent.com/assets/5030463/13405010/d33e89c2-df1c-11e5-89c3-44d65750656e.png)

+1

**Comment by tagliala** [comment]
closing here 

#255
