### ISSUE TITLE
Icon Request: fa-report

### ISSUE THREAD

**Issue by kevspadilla** [FortAwesome/Font-Awesome#8320]
Hi all, may request for an icon which will be used for navigation for marketing links.

Heres a sample image: 
https://cdn0.iconfinder.com/data/icons/simple-seo-and-internet-icons/512/analytics-512.png

Thanks!

**Comment by JeroenCollier** [comment]
+1

**Comment by tagliala** [comment]
dup of #1076 (and maybe another one related to analytics that I'm not able to find at the moment)

please +1 that request

closing here

**Comment by kevspadilla** [comment]
thanks!
