### ISSUE TITLE
This selected tick is creating an issue on safari. Can anyone help me?

### ISSUE THREAD

**Issue by PrajwolMaharjan** [FortAwesome/Font-Awesome#8321]
![issue](https://cloud.githubusercontent.com/assets/14937279/12288031/d46ae3f2-b9f8-11e5-8cb5-c21f43e20374.jpg)

**Comment by tagliala** [comment]
could you please provide a fiddle showing the issue?

**Comment by PrajwolMaharjan** [comment]
@tagliala I have updated on jsfiddle. link: http://jsfiddle.net/PrajwolM/syduuue9/14/

The issue is just on Mac. Preview attached.
![option](https://cloud.githubusercontent.com/assets/14937279/12316194/1351f2b4-baac-11e5-9383-c17012bcbd8a.png)

I just want is to disable default tick on safari.

Hope you understand.

**Comment by tagliala** [comment]
Sorry, this tracker is only for issues related to fontawesome

No fontawesome here: https://jsfiddle.net/tagliala/66rok2et/

Please consider using stackoverflow.

Closing here

Please also take a look at #996
