### ISSUE TITLE
Icon request: Allergies - Alergens

### ISSUE THREAD

**Issue by JeroenCollier** [FortAwesome/Font-Awesome#8324]
Please provide icons to show allergen information. This can be used on food products and on menu-cards and so on. Also the allergens which one can encounter in once house can be very useful to use on information flyers about allergies and so forth.

![schermafbeelding 2016-01-13 om 09 14 53](https://cloud.githubusercontent.com/assets/16594261/12288779/76632556-b9d7-11e5-887c-d2d7c2a5b7a5.png)

**Comment by tagliala** [comment]
sorry but I need to close this request.

Dup of #5228, closed because it doesn't meet contributing guidelines 

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

**Comment by holtkamp** [comment]
@JeroenCollier if you can contribute, please see https://github.com/FortAwesome/Font-Awesome/issues/5228#issuecomment-280304750
