### ISSUE TITLE
Icon request: Diet

### ISSUE THREAD

**Issue by JeroenCollier** [FortAwesome/Font-Awesome#8325]
Please provide an icon for 'diet'. Maybe someone can make a better suggestion then the one I provided, but this is the best I could find. This is only suitable for females, dieting is not limited to females only.

![schermafbeelding 2016-01-13 om 09 12 52](https://cloud.githubusercontent.com/assets/16594261/12288811/c1f01d6c-b9d7-11e5-9e3e-186b0d1c57d7.png)

**Comment by KOTRET** [comment]
maybe you can provide any suggestions how to make this gender-independent? Otherwise i hear feminists crying that there is only an icon for females or males :grin:

**Comment by tagliala** [comment]
you could +1 #7797 for a weight scale

**Comment by JeroenCollier** [comment]
That is a valid remark. Therefore my request if anyone can give a good suggestion on how to make it gender-independent. But the icon 'diet' itself would be very useful. A balance just won't cut it.

**Comment by KOTRET** [comment]
maybe sth. like [this](http://de.freepik.com/freie-ikonen/mabband_814943.htm) or [this](http://de.freepik.com/vektoren-kostenlos/diat-konzept_796375.htm)

**Comment by JeroenCollier** [comment]
![diat-konzept_23-2147514435](https://cloud.githubusercontent.com/assets/16594261/12506710/417dc528-c0f1-11e5-9d12-148a33205de1.jpg)

**Comment by tagliala** [comment]
please provide single color examples suitable for 14px icon size.

I would rename this `tape-measure`

**Comment by tagliala** [comment]
closing here in favour of #8437
