### ISSUE TITLE
Icon request: days of the week

### ISSUE THREAD

**Issue by JeroenCollier** [FortAwesome/Font-Awesome#8326]
Can you please provide days-of-the-week icons, based upon the calender icon already present in FontAwesome. These are very useful to mark the days of the week in program folders and so on.

![schermafbeelding 2016-01-13 om 09 16 41](https://cloud.githubusercontent.com/assets/16594261/12288872/33bab56a-b9d8-11e5-8aa8-b90d6fac6453.png)

**Comment by aethior** [comment]
Hi @JeroenCollier,

You can use text and font awesome icons: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/.

Example: http://codepen.io/anon/pen/wMqoEW

**Comment by tagliala** [comment]
I'm going to close this request, please use stacks as advised by @aethior

**Comment by JeroenCollier** [comment]
I actually do not agree with this decision, as stacking only works for digital applications. If one wishes to use these in print design, then one has not the option to use CSS to solve this. Off-course one can just use illustrator to fix this, but that overrules the need of an icon set altogether, and definitely denies the benefit of consistency one gets if one works with a fixed pictogram set.

Please do not close this request, and take my point/reasoning into consideration. Thank you.

**Comment by aethior** [comment]
Font Awesome is used internationally. You can't use words in English (or other languages). The pictograms should be nonlinguistic images.

**Comment by tagliala** [comment]
> Font Awesome is used internationally. You can't use words in English (or other languages). The pictograms should be nonlinguistic images.

That should be one the point

Others:
* icons will not fit 14px icon size
* Font family will not match application's one

**Comment by JeroenCollier** [comment]
Ok, point taken.
