### ISSUE TITLE
MOMP services

### ISSUE THREAD

**Issue by Raid-RK** [FortAwesome/Font-Awesome#8328]
Please provide icon for image of (citizen & business)
![business_icon](https://cloud.githubusercontent.com/assets/16681878/12290328/913a11d2-b9fa-11e5-9c2c-41e330c674c3.png)
![cetizen_icon](https://cloud.githubusercontent.com/assets/16681878/12290329/913b8c1a-b9fa-11e5-9062-c4633bd1ba32.png)

**Comment by tagliala** [comment]
Sorry but I didn't get this request

we have http://fontawesome.io/icon/users/ and http://fontawesome.io/icon/building/

Are the above brands? what is the use case?

Please take another look at contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by Raid-RK** [comment]
Thank you for your interest,that icon for our organization portal website 
Frist one is business services 
Second one is citizens services

Regards
Raid


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Geremia Taglialatela <notifications@github.com> </div><div>Date:13/01/2016  6:31 PM  (GMT+04:00) </div><div>To: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com> </div><div>Cc: Raid-RK <raidalkiyumi@gmail.com> </div><div>Subject: Re: [Font-Awesome] MOMP services (#8328) </div><div>
</div>Sorry but I didn't get this request

we have http://fontawesome.io/icon/users/ and http://fontawesome.io/icon/building/

Are the above brands? what is the use case?

Please take another look at contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment]
Frist one is business services : you could use `fa-building`
Second one is citizens services: you could use `fa-users`

**Comment by Raid-RK** [comment]
Could you convert the image to icon font? 


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Geremia Taglialatela <notifications@github.com> </div><div>Date:13/01/2016  7:48 PM  (GMT+04:00) </div><div>To: FortAwesome/Font-Awesome <Font-Awesome@noreply.github.com> </div><div>Cc: Raid-RK <raidalkiyumi@gmail.com> </div><div>Subject: Re: [Font-Awesome] MOMP services (#8328) </div><div>
</div>Frist one is business services : you could use fa-building
Second one is citizens services: you could use fa-users

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
