### ISSUE TITLE
 Icon request: icon-popcorn

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8331]
Hi, It will be useful for the food activities.
Thank you
![popcorn6](https://cloud.githubusercontent.com/assets/6671049/12297132/f6665e4c-ba0b-11e5-860e-de630106ab69.png)

**Comment by aethior** [comment]
Hi @isifun,

This suggestion is duplicate of #6879. Please +1 that.

Regards.

**Comment by tagliala** [comment]
please also post there your example

closing here
