### ISSUE TITLE
Icon request: icon-amusement-park

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8332]
Hi, It could be interesting to add a park icon.
Thank to all
![fairground](https://cloud.githubusercontent.com/assets/6671049/12297213/5f25ef92-ba0c-11e5-9210-ee966898dfdf.png)

**Comment by aethior** [comment]
Hi @isifun,

`fa-roller-coaster` icon was added in v6.0.0.
Check https://fontawesome.com/icons/roller-coaster

Regards.

**Comment by tagliala** [comment]
Ref: #17073
