### ISSUE TITLE
Icon request: icon-lion

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8334]
Hi, it will be amazing to have some animals icon like dog, cat, giraffe, lion ...
Thanks to all
![lion7](https://cloud.githubusercontent.com/assets/6671049/12297570/19706052-ba0e-11e5-8db1-bb3f6f6acbba.png)

**Comment by lmget** [comment]
Agreed!

**Comment by Crissov** [comment]
Probable duplicate of #5403.

**Comment by tagliala** [comment]
Sorry, I've missed this one. 

Duplicate of #5403
