### ISSUE TITLE
Icon request: icon-ski

### ISSUE THREAD

**Issue by isifun** [FortAwesome/Font-Awesome#8335]
Hi all, What do you think about this icon for for winter activities ? 
Thank you
![sport22](https://cloud.githubusercontent.com/assets/6671049/12297663/78681f64-ba0e-11e5-9c84-7afcf8ab397f.png)

**Comment by aethior** [comment]
Duplicate of #6878. Please +1 that.

Regards.

**Comment by andyanderso** [comment]
+1

**Comment by futureweb** [comment]
+1
