### ISSUE TITLE
Icon request: icon-%currency% [PLN, UAH, VND...]

### ISSUE THREAD

**Issue by iakin** [FortAwesome/Font-Awesome#8341]
Hello,

First of all thank you for your excellent work ! :-)

You've already incorporate some symbols of currencies but could you integrate the following list :

* **CRC**: **₡**, // Costa Rican Colón
* **NGN**: **₦**, // Nigerian Naira
* **PHP**: **₱**, // Philippine Peso
* **PLN**: **zł**, // Polish Zloty
* **PYG**: **₲**, // Paraguayan Guarani
* **THB**: **฿**, // Thai Baht
* **UAH**: **₴**, // Ukrainian Hryvnia
* **VND**: **₫**, // Vietnamese Dong

Use case : my website manage currencies conversions

Thanks
iakin

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Please +1 existing requests (like #1267 #1451 and maybe others) and open new individual requests for missing currencies
