### ISSUE TITLE
Icon Request: fa-bull-horns

### ISSUE THREAD

**Issue by rkroeber** [FortAwesome/Font-Awesome#8342]
It would be great to have an icon for a bull or cowboy boot or hat that we could use on our website for events that have western, cowboy or rodeo themes.

**Comment by thill0822** [comment]
I'm often in need of cowboy, horse, or rodeo themes too

**Comment by rshimshock** [comment]
Would like to add a request for a cowboy hat. This is something we could really use.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/skull-cow?style=solid
https://fontawesome.com/icons?d=gallery&q=cowboy
