### ISSUE TITLE
Icon Request: fa-contact

### ISSUE THREAD

**Issue by JasonMe** [FortAwesome/Font-Awesome#8345]

**Comment by AndreLGava** [comment]
Maybe this is related to this? https://github.com/FortAwesome/Font-Awesome/issues/825
if yes please close this issue and mark a +1 on that one.

Thanks

**Comment by tagliala** [comment]
@AndreLGava thanks

Considering this a duplicate of #825

**Comment by JasonMe** [comment]
just like phone book

**Comment by tagliala** [comment]
@JasonMe #898
