### ISSUE TITLE
fa-windows fa-1 bug: no horizontal line

### ISSUE THREAD

**Issue by polkovnikov-ph** [FortAwesome/Font-Awesome#8348]
![image](https://cloud.githubusercontent.com/assets/2983969/12351843/decca7aa-bb78-11e5-9ab5-7feeb7cebb97.png)
While I would expect something like [this](http://jsbin.com/zihodabiki/2/edit?html,output):
![image](https://cloud.githubusercontent.com/assets/2983969/12352245/1e2fd86a-bb7c-11e5-8a5e-56420b177629.png)

**Comment by tagliala** [comment]
Brand icons are imported as they are

Similar issue of #1254, I'm going to close this and label the same way

Please use a different size for this icon

**Comment by polkovnikov-ph** [comment]
Thanks for quick reply! I haven't thought it's impossible to modify brand icons for legal reasons.
