### ISSUE TITLE
Icon request: fa-text

### ISSUE THREAD

**Issue by PennyFace** [FortAwesome/Font-Awesome#8349]
Hi,
There are two icons text (text height and text width), but not just text. It's the same T as text height and text width but without an arrow

We want to use this in our application to specify a data type: text.

Greetings,

**Comment by marathia** [comment]
+1

**Comment by dotnetchris** [comment]
:+1:

**Comment by dnavarrojr** [comment]
+1

**Comment by MightyFo0l** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by fschaeffer** [comment]
+1

**Comment by aethior** [comment]
Duplicate of #8839?

cc @tagliala

**Comment by aethior** [comment]
Hi @PennyFace,

This icon was added in v5.9.0.
Check https://fontawesome.com/icons/text

Regards.

cc/ @tagliala
