### ISSUE TITLE
Icon request: icon-google-drive

### ISSUE THREAD

**Issue by davequested** [FortAwesome/Font-Awesome#835]

**Comment by legshooter** [comment]
+1

**Comment by bionik** [comment]
+1

**Comment by toter** [comment]
+1

**Comment by JeremyVriens** [comment]
+1

**Comment by PresidentNick** [comment]
+1

**Comment by k1ng440** [comment]
+10000000

**Comment by justinrob** [comment]
+1

**Comment by chrisseto** [comment]
+1

**Comment by ricktank** [comment]
+1

**Comment by ecentinela** [comment]
+1

**Comment by Jrizzi1** [comment]
+1

**Comment by Casara** [comment]
+1

**Comment by jorgealda** [comment]
+1

**Comment by ashwinpathak** [comment]
+1

**Comment by Contagious06** [comment]
+1

**Comment by danniranderis** [comment]
+1

**Comment by amastaneh** [comment]
+1

**Comment by BlockNinja** [comment]
+1

**Comment by MicheleV** [comment]
+1

**Comment by ediweissmann** [comment]
+1

**Comment by steenbrahe** [comment]
+1

**Comment by LeifurSE** [comment]
+1

**Comment by wackamole** [comment]
+1

**Comment by damon-e-drake** [comment]
+1

**Comment by TheChen5** [comment]
+1

**Comment by stevelippert** [comment]
+1

**Comment by Jeel-Shah** [comment]
+1

**Comment by Cocottier** [comment]
+1

**Comment by tulu** [comment]
+1

**Comment by dFayet** [comment]
+1

**Comment by pandemonia** [comment]
+1

**Comment by aschepis** [comment]
+1

**Comment by jjgleim** [comment]
+1

**Comment by iampliny** [comment]
+1

**Comment by Loilo** [comment]
+1 :)

**Comment by garralab** [comment]
+1

**Comment by matejkramny** [comment]
+1 hmm. its awkward having dropbox on, but not gdrive

**Comment by sezertunca** [comment]
+1

**Comment by DaAwesomeP** [comment]
:+1:

**Comment by mariorodriguespt** [comment]
+1

**Comment by DaSchTour** [comment]
+1

**Comment by markokoleznik** [comment]
+1

**Comment by vanbergcamp** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by r4m** [comment]
+1

**Comment by zsozso** [comment]
+1

**Comment by meletis** [comment]
+1

**Comment by vlapo** [comment]
+1

**Comment by sabgaby** [comment]
+1

**Comment by twasyl** [comment]
+1

**Comment by eli007** [comment]
+1

**Comment by barrd** [comment]
+1

**Comment by jackeo** [comment]
+∞

**Comment by dcgs-sbu** [comment]
+1, thanks.

**Comment by astorije** [comment]
+1
FYI, this is where the Google Drive icons are officially documented by Google: https://developers.google.com/drive/v3/web/branding#using_the_google_drive_brand.

Monochromatic Google Drive icon is:

![image](https://cloud.githubusercontent.com/assets/113730/14153524/1c392f58-f686-11e5-9926-30771bc6f13d.png)

In terms of smaller FA website sizes, it gives:

<img src="https://cloud.githubusercontent.com/assets/113730/14153524/1c392f58-f686-11e5-9926-30771bc6f13d.png" width=28> <img src="https://cloud.githubusercontent.com/assets/113730/14153524/1c392f58-f686-11e5-9926-30771bc6f13d.png" width=14>

**Comment by CB-Shantikumar** [comment]
+1

**Comment by xenomarz** [comment]
+1

**Comment by thomasridd** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-google-drive was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by Hgcam** [comment]
+1

**Comment by leochoi** [comment]
+1

**Comment by scwood** [comment]
+1

**Comment by pzp1997** [comment]
+1

**Comment by chegarr** [comment]
+1

**Comment by RicardoASP** [comment]
+1

**Comment by charliehavak** [comment]
+1

**Comment by NEALON** [comment]
+1

**Comment by cepster** [comment]
+1

**Comment by rowex105** [comment]
+1

**Comment by justinrassier** [comment]
+1

**Comment by clayjars** [comment]
+1

**Comment by jhuebel** [comment]
+1

**Comment by debuggin** [comment]
+1

**Comment by axyr** [comment]
+1

**Comment by minmay** [comment]
+1

**Comment by tquiroga** [comment]
+1

**Comment by knightbenax** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by unixzilla** [comment]
+1

**Comment by astorije** [comment]
Please, people, stop +1-ing that thread, it won't lead you anywhere and it's spam for everyone here who want to be updated with actual info if there is anything changing. Best way to get an issue locked...
Instead, use the 👍 feature on the original message by the author and click "Subscribe" to get notifications:

<img width="293" alt="screen shot 2016-11-30 at 00 37 59" src="https://cloud.githubusercontent.com/assets/113730/20740997/632dcb92-b695-11e6-90de-6202096d270f.png">

Thanks!

**Comment by DaAwesomeP** [comment]
@astorije In fact this issue has already been marked for v5, so adding more +1s won't necessarily change anything.

**Comment by evanschris** [comment]
+1

**Comment by danpezzin-social** [comment]
+1

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[The Google Drive icon is here](https://icons8.com/icon/3464/google-drive).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by ferparmur** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
