### ISSUE TITLE
"Get Started" CDN URL - Different GooglePlus icon

### ISSUE THREAD

**Issue by emilsgulbis** [FortAwesome/Font-Awesome#8369]
Hi!

*Get started* url - https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
contains different GooglePlus icon than shown here http://fontawesome.io/icon/google-plus/

Thanks!

**Comment by tagliala** [comment]
Cannot confirm.

https://jsfiddle.net/tagliala/syduuue9/16/

Please check our troubleshooting guide https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
