### ISSUE TITLE
Icon request: icon-sunrise, icon-sun, icon-night

### ISSUE THREAD

**Issue by astanley86** [FortAwesome/Font-Awesome#837]
sunrise = sun over the horizon
full sun = day
crecent moon = night

This would be really cool to convey if an event is happening in the morning, during the day, or in the evening.

**Comment by maryargarine** [comment]
+1 for the sun over the horizon, or a half sun to represent morning.

**Comment by seanmhanson** [comment]
+1 for sun over horizon / half sun / equivalent icons so we can separate into **morning**, **day**, **evening**, and **night**

**Comment by astanley86** [comment]
I see some recent activity on this request.  I'm the original requester and still would love to see these icons.  Are these being worked on for a future release?  Thank you!

**Comment by bertoost** [comment]
+1

**Comment by nihonjinrxs** [comment]
+1
Also seems related to #5200.

**Comment by DistantParadox** [comment]
+1, specifically for the PaleMoon browser

**Comment by zamora-eric** [comment]
+1, I like the 4 icon request that seanmhanson describes

**Comment by RichardStyles** [comment]
+ 1

**Comment by sensibleworld** [comment]
We've added a sunset and sunrise icon to Font Awesome Pro:

https://fontawesome.com/icons/sunset?style=solid
https://fontawesome.com/icons/sunrise?style=solid

As well as a bunch of other weather icons to Font Awesome Free: https://fontawesome.com/icons?d=gallery&c=weather
