### ISSUE TITLE
Icon request: icon-flag-country-name

### ISSUE THREAD

**Issue by rubenslopes** [FortAwesome/Font-Awesome#8370]
Would be very nice to have some countries flags. ;)
For globalization/localization purposes.

**Comment by tagliala** [comment]
Sorry, it will not happen

Closing here

Refers to #4516

**Comment by colinkzmedia** [comment]
Hello 

Any chance to reconsider adding the country flags from for globalization?

**Comment by tagliala** [comment]
I've started to allow individual requests for flags

e.g.: #4735 #9520 #14541
