### ISSUE TITLE
Firefox stops printing number input boxes with Font-Awesome

### ISSUE THREAD

**Issue by danpeig** [FortAwesome/Font-Awesome#8372]
That's weird but try to print (with Firefox Print menu) this input form with Font-Awesome enabled. I tried the latest Font-Awesome fonts (4.5.0) and the the latest Firefox version (42, Windows) but it was not working with previous versions also.

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Test Font-Awesome rendering bug in Firefox</title>
<link rel="stylesheet" href="css/font-awesome.min.css" type="text/css" />
</head>
<body>
You should see an icon here: <i class="fa fa-fort-awesome"></i>
<BR>
And here, the input number should appear in the print preview:<input type="number" value="12345">
</body>
</html>
```

**Comment by KOTRET** [comment]
latest FF? there is 43.0.4. Anyway: i cannot reproduce this, please check this fiddle
https://jsfiddle.net/thav3bto/
![prev](https://cloud.githubusercontent.com/assets/1357504/12491514/d1df431a-c07b-11e5-8617-972d61ce5c50.jpg)

**Comment by danpeig** [comment]
Within the fiddle it works. That´s strange.
Here's my printout...

              

Daniel Brooke Peig
E-mail: danpeig@brookepeig.com
Home Page: http://www.danbp.org
Mobile: (+ 55 11) 994273974


Date: Thu, 21 Jan 2016 11:17:22 -0800

**Comment by danpeig** [comment]
Working with Firefox on that... It seems it's related to fonts.
https://bugzilla.mozilla.org/show_bug.cgi?id=1199229

**Comment by KOTRET** [comment]
you can dump your standalone test-code to reproduce this issue?

**Comment by danpeig** [comment]
This was a Firefox issue. It was fixed for the future release (45).
We can close the issue now. Thank you for the support.

**Comment by tagliala** [comment]
@danpeig thanks
