### ISSUE TITLE
Icon Request: fa-yubico fa-yubikey fa-yubikey-nano fa-yubikey-neo

### ISSUE THREAD

**Issue by divdax** [FortAwesome/Font-Awesome#8377]
Hey!

Would be great to have a yubico/yubikey icon.

Yubico:
![yubico](https://demo.yubico.com/favicon.ico)

Yubikey: (only the stick)
![key](http://www.collectivesoftware.com/images/design/solutions/glyph_authlite.png)

There are different sticks available:
https://www.yubico.com/products/yubikey-hardware/

**Comment by tagliala** [comment]
dup of #5751, please +1 that request

closing here

**Comment by tagliala** [comment]
hmm... maybe there is a different icon

could you please clarify and edit your post?
