### ISSUE TITLE
Icon Request: fa-discord

### ISSUE THREAD

**Issue by hxcl** [FortAwesome/Font-Awesome#8378]
Discord is awesome and it needs a super cool icon. I would love an icon like the picture attached without the outside box, just the controller thing in the middle. Thanks!
More Detailed Images and PressKit: https://discordapp.com/branding
![discord-logo-black](https://cloud.githubusercontent.com/assets/13984226/12456214/9855b404-bf53-11e5-8f45-02f15af1bea6.png)

**Comment by hedgehog1029** [comment]
An issue already exists for this, [here.](https://github.com/FortAwesome/Font-Awesome/issues/7574)
