### ISSUE TITLE
Icon request: icon-drone

### ISSUE THREAD

**Issue by JamesOrlowski** [FortAwesome/Font-Awesome#8379]
How about something like this? 

https://d30y9cdsu7xlg0.cloudfront.net/png/103844-200.png

**Comment by aethior** [comment]
Hi @JamesOrlowski,

This suggestion is duplicate of #5446. Please +1 that.

Regards.

**Comment by pitus** [comment]
+1 for our Farming support site where they'll use Drones to do scouting
