### ISSUE TITLE
Icon request: Crown

### ISSUE THREAD

**Issue by nukos** [FortAwesome/Font-Awesome#8383]
I want to crown icon.

inspiration:
https://www.google.co.jp/search?q=crown&espv=2&biw=1761&bih=1110&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiC0p642bnKAhXElZQKHRCECtUQ_AUIBigB#tbm=isch&tbs=rimg%3ACUm0W_1dRYkdVIjirB8RCSKpgmDeBiCs-dAMkAbhwTWVetfj2DswzFmyFmaD9loJU_1HQDmn21dlu5YKEpHPmo-xak5CoSCasHxEJIqmCYEd5iBmqqS13dKhIJN4GIKz50AyQR_1PCq7t4tfGIqEgkBuHBNZV61-BECUL9NOfCDsioSCfYOzDMWbIWZESc4MonoEnOHKhIJoP2WglT8dAMRomwwkW1tt3oqEgmafbV2W7lgoRHXq3SPbxpR3SoSCSkc-aj7FqTkESJVbUw9okCc&q=crown

**Comment by aethior** [comment]
Hi @nukos,

This suggestion is duplicate of #486. Please +1 that.

Regards.

**Comment by nukos** [comment]
Sorry.

Thank you for letting me know .
