### ISSUE TITLE
Icon request: icon-calendar with dates

### ISSUE THREAD

**Issue by mlserafin** [FortAwesome/Font-Awesome#8385]
Hello there! 

I am trying to use icons as calendar dates for marketing purposes on my website www.dsp-nurho.com/recruitment. We love your work btw! (It's all over our website, seriously.) We love your calendar icons but was wondering if could have some that put dates on the calendar. 

Specifically, we were hoping for: Feb 1 - Feb 5
(Yes, so like an individual icon for each day)

Please let me know if this is possible! (or if you need any more info) You rock!

**Comment by tagliala** [comment]
please take a look here: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Also, for other ways of stacking numbers on calendar: #1140

I'm going to close this one, please use the stacking feature
