### ISSUE TITLE
where is a wordpress plugin for font-awesome 4.4?

### ISSUE THREAD

**Issue by aldwen** [FortAwesome/Font-Awesome#8398]
I want to use Font-awesome in wordpress, but I  have little skills on web design.  I found a wordpress-plugin named “Font Awesome Icons”, but it just support 3.2.1. there is no QQ, no wechat,no weibo....
I would know where or when will be a new wordpress-plugin?
or how to use font-awesome in wordpress, where is a tutorial?
---------------
似乎您是中国人：
我想在wordpress中使用awesome，但是我不太会网页设计。我找到了一个wordpress插件：“Font Awesome Icons”，但是他只支持3.2.1。没有微博、QQ等图标
我想知道，你们会制作wordpress的插件吗？
或者，我要怎么在wordpress里使用awesome？有没有针对新手的教程？“复制整个 font-awesome 文件夹到您的项目中。” 这句话已经难倒我了，我不知道应当拷贝到哪里

**Comment by tagliala** [comment]
Sorry, I have to close this one

You should use stackoverflow for suppor requests
