### ISSUE TITLE
Icon Request: fa-Telegram Messenger

### ISSUE THREAD

**Issue by h-alizadeh** [FortAwesome/Font-Awesome#8410]
telegram is one of most popular messanger that have creat channel and share your post in this messneger  
if can add telegram messenger icon to font awesome 
thanks

**Comment by AndreLGava** [comment]
Would you like to use something like this: http://fontawesome.io/icon/paper-plane/ ?

**Comment by tagliala** [comment]
duplicate of #5474 , please +1 that request

even if paper-plane could do the job, brand icons should be imported as-is, so paper plane cannot be aliased to telegram and vice versa
