### ISSUE TITLE
Icon request: toolbox

### ISSUE THREAD

**Issue by Furburger** [FortAwesome/Font-Awesome#8421]
Hi

I think a toolbox icon would be very useful.

![toolbox64](https://cloud.githubusercontent.com/assets/5500245/12605014/752ad6aa-c4c9-11e5-88b2-4d7da5302726.png)

**Comment by tab13tab13** [comment]
Agreed. If not generic toolbox, then hammer or screwdriver, etc.

**Comment by tagliala** [comment]
duplicate of #4407, please +1 that request

closing here

**Comment by tromney** [comment]
+1
