### ISSUE TITLE
New Icon - Download as PDF

### ISSUE THREAD

**Issue by shanky1706** [FortAwesome/Font-Awesome#8428]
...and other download-as- icons for various file types like doc, ppt etc.

**Comment by tagliala** [comment]
sorry, didn't get this request

http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
