### ISSUE TITLE
Icon Request(s) - House Icons

### ISSUE THREAD

**Issue by ptmuldoon** [FortAwesome/Font-Awesome#8431]
Apologies if this has been asked already but could not come across it asked already.

Is there any way in future releases to create a Home 'Collection'?  Icons of a House and everyday things you find in them like Light Switches, Fans, Ceiling Fan, Windows and Door (open and shut), Bedroom items, Bath items, TV, oven, etc?

**Comment by tagliala** [comment]
sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
