### ISSUE TITLE
How to add Custom icons in Font-Awesome Plugins 

### ISSUE THREAD

**Issue by santosh-k1** [FortAwesome/Font-Awesome#8434]
Hi can you let me know that How to add Custom icons in Font-Awesome Plugins and what could be format of those icons can be possible to use PNG or gif..

**Comment by tagliala** [comment]
fontawesome does not use images, please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

If you need png sprites, please take a look here: https://github.com/encharm/Font-Awesome-SVG-PNG or here: http://fa2png.io/

hope it helps

closing here

**Comment by santosh-k1** [comment]
@tagliala i am talking about how to add my custom icons inside Font-Awesome Plugins ...

**Comment by tagliala** [comment]
what is Font-Awesome Plugins?

**Comment by santosh-k1** [comment]
for your understanding here is link of Font-Awesome (https://github.com/FortAwesome/Font-Awesome) and i wanted to add some custom icons for my project..  icons  it menace logo of project, some icons etc.

**Comment by tagliala** [comment]
ok, so my answer was right. Please take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
