### ISSUE TITLE
Icon Request: icon-google-hangout

### ISSUE THREAD

**Issue by ryalsche** [FortAwesome/Font-Awesome#8439]
Hi again!

Could you add the Google Hangouts icon to Awesome Font? Something like this [http://www.androidpolice.com/wp-content/uploads/2013/05/nexusae0_Hangouts-Logo.png]

Thank you!

**Comment by AndreLGava** [comment]
This is duplicated from https://github.com/FortAwesome/Font-Awesome/issues/4045 please mark +1 there and close this issue please
