### ISSUE TITLE
Icon request: icon-walk (man walking)

### ISSUE THREAD

**Issue by roysbailey** [FortAwesome/Font-Awesome#844]
I am particularly in need of a "car" icon, but feel a set of icons around "mode of transport" would be widely beneficial.

**Comment by geradt** [comment]
+1 for walk icon

**Comment by ggiakas** [comment]
+1

**Comment by mapocosm** [comment]
+1 for walking icon

**Comment by sherinkurian** [comment]
+1

**Comment by oliverkane** [comment]
+1 for walking icon.

**Comment by nwpan** [comment]
+1 for walking icon

**Comment by nikolauskrismer** [comment]
+1 for walking icon

**Comment by tonifisler** [comment]
+1 for walk icon :+1:

**Comment by mhowell2** [comment]
+1 for walk icon

**Comment by alyssabraun** [comment]
+1 for walk icon

**Comment by philgn** [comment]
+1 for walk icon

**Comment by chueneke** [comment]
+1 for walk icon

**Comment by JenniferKoenig** [comment]
+1 for walk icon

**Comment by arathje** [comment]
+1 for walk icon

**Comment by mpreziuso** [comment]
:+1: walk icon

**Comment by rjotadesign** [comment]
+1 for walk icon
would work great together witdh a hand-stop-sign like mentioned in #1872 (just the hand, though) or fa-male for traffic light icons under the Transportation Icons category!

**Comment by rda-dev** [comment]
+1 for walk icon :+1:

**Comment by oliverkane** [comment]
To all those who've had problems here. I found a new set of icons which is compatable with FA, and has the walking icon. 
http://zavoloklom.github.io/material-design-iconic-font/icons.html

Use class="md md-directions-walk"

**Comment by marchile** [comment]
@oliverkane great, thanks!

**Comment by robibi78** [comment]
+1 thks

**Comment by ruvenss** [comment]
:+1:

**Comment by ebanders** [comment]
+1 for walk icon

**Comment by lintmachine** [comment]
+1

**Comment by edgeman** [comment]
+1

**Comment by G-Driver** [comment]
+1 

example as said above https://thenounproject.com/term/pedestrian/35166/

**Comment by cubesun** [comment]
+1

**Comment by mcamis** [comment]
+1 this would really round out the transportation icon set.

**Comment by margarethogg** [comment]
+1

**Comment by mcamis** [comment]
hehe

On Fri, May 8, 2015 at 1:57 PM, margarethogg <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-100327687>
> .
>



-- 
*Adam McAmisI'm on the internet.*

**Comment by 110chang** [comment]
+1 walk icon

**Comment by danivek** [comment]
+1

**Comment by ltcanuck** [comment]
+1

**Comment by klaus-stabil-it** [comment]
+1

**Comment by SolveSoul** [comment]
+1

**Comment by buzzswarbrick** [comment]
+1

**Comment by Manoj-nathwani** [comment]
+1

**Comment by probins** [comment]
+1

**Comment by adaro** [comment]
+1

**Comment by Streemo** [comment]
+1 for walk icon

**Comment by aptly-io** [comment]
+1 for walking man/female/kid

**Comment by aydnbhdr** [comment]
+1

**Comment by andr0man** [comment]
+1

**Comment by subnauez** [comment]
+1

**Comment by Lacus-** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by richnicholls404** [comment]
+1 for walk icon

**Comment by sambooth74** [comment]
+1

**Comment by measureddesigns** [comment]
+1 for walk icon

**Comment by fr0980y** [comment]
+1
Might as well easily add Run to the set by drawing a few horizontal lines behind the walking person.

**Comment by rahulbats** [comment]
+1 for walking icon

**Comment by nikkiroylance** [comment]
+1 icon-walk

**Comment by seteen** [comment]
+1

**Comment by lexusburn** [comment]
+1

**Comment by Wintermute79** [comment]
+1

**Comment by MSiliunas** [comment]
+1 for walking person icon

**Comment by SteGriff** [comment]
:+1: for walking person

**Comment by aroniotis** [comment]
+1

**Comment by worthlutz** [comment]
+1

**Comment by notian** [comment]
+1 this is long overdue.

**Comment by ohryan** [comment]
+1 for now i'll just use hand-lizard

**Comment by aroniotis** [comment]
+1

**Comment by zoldello** [comment]
How many +1 is +1 too many at this point?

**Comment by G-Driver** [comment]
+1 for pedestrian

**Comment by edumucelli** [comment]
+1

**Comment by mahill** [comment]
+1 for walk icon

**Comment by darrondriver** [comment]
+1

**Comment by ngheungyu** [comment]
+1 for walk

**Comment by pravin-d** [comment]
+1 for walk

**Comment by swapzone** [comment]
+1 for walk

**Comment by patlux** [comment]
+1

**Comment by marvoh** [comment]
+1 long overdue

**Comment by akw123** [comment]
+1 for mode of transportation set

**Comment by collegeman** [comment]
+1

**Comment by rcrisp** [comment]
+1 - Transportation is great but missing walking man.

**Comment by lihue** [comment]
+1

**Comment by Wirwing** [comment]
+1

**Comment by lucachaco** [comment]
+1

**Comment by kcivey** [comment]
:+1:

**Comment by nashella** [comment]
+1 for walk icon

**Comment by shmaster** [comment]
+1 for walk icon

**Comment by jkoudys** [comment]
+1 for walk icon

**Comment by cfukai** [comment]
+1 for walking icon

**Comment by kn4rfy** [comment]
+1 for walking icon

**Comment by michal-szelag** [comment]
+1 for walking icon

**Comment by JancoBH** [comment]
+1 for walking icon please

**Comment by Dokioki** [comment]
+1 for walking icon please.

**Comment by dpfem** [comment]
+1 for walking icon please

**Comment by ShaunR** [comment]
+1

**Comment by AndreNDarcie** [comment]
+1 for walking icon

**Comment by wimvanhorenbeeck** [comment]
+1 for walking icon

**Comment by uhenninger** [comment]
+1 for walking icon

**Comment by Tomsgu** [comment]
+1 for walking icon

**Comment by pshoeg** [comment]
+1
Could the fa-blind icon without the cane be used?
![skaermbillede 2016-05-27 kl 08 44 39](https://cloud.githubusercontent.com/assets/485099/15599953/4b355f32-23e7-11e6-9a58-6acf37b145aa.png)

**Comment by thurairaj92** [comment]
+1 for walking

**Comment by bryanwayb** [comment]
+1

**Comment by nicwinn** [comment]
+1

**Comment by gnomii** [comment]
+1

**Comment by tobiasjungnickel** [comment]
+1

**Comment by stefanmintert** [comment]
+1 thanks

**Comment by Herteby** [comment]
+1 for walking man!

**Comment by ariansobczak** [comment]
+1 please

**Comment by alxhotel** [comment]
+1

**Comment by pdespouy** [comment]
+ 1 for walk icon

**Comment by glasnoster** [comment]
👍

**Comment by zooillogica** [comment]
+1 for walk, pedestrian icon

**Comment by GJordan904** [comment]
+1

**Comment by hardcodet** [comment]
+1

**Comment by twelvetrains** [comment]
+1 for walk icon. Please.

**Comment by Crissov** [comment]
🚶 [U+1F6B6](http://emojipedia.org/pedestrian/) Unicode emoji #222

**Comment by Pau1fitz** [comment]
+1

**Comment by votanlean** [comment]
+1

**Comment by jeffschuler** [comment]
+1

**Comment by lingxiaoyang** [comment]
+1 for walk icon. Thank you.

**Comment by indianazhao** [comment]
+1

**Comment by ChristianLJ** [comment]
+1

**Comment by screen-bee** [comment]
+ a walking female
![fa-female-walking](https://cloud.githubusercontent.com/assets/26275896/23703135/acc0a50c-03fe-11e7-9bd9-7175af0cf488.JPG)
It' International Women's Day :-)

**Comment by Crissov** [comment]
@screen-bee Nobody was proposing a Walking Male glyph. You’d make the gender-less stick figure appear male by only introducing a Walking Female. That means, you either need a single abstract graphic or three discernable ones – just two will always lead to problems.

**Comment by jbvazquez** [comment]
+1

**Comment by 8BitSigdom** [comment]
+1 walk icon

**Comment by chikama** [comment]
+1

**Comment by einavsh** [comment]
+1 walking icon

**Comment by aharonhillel** [comment]
+1 for walking

**Comment by milandebuck** [comment]
+1

**Comment by jdeboer-geoplan** [comment]
+1

**Comment by marikoo** [comment]
+1 
Why, oh why this is so difficult? Four years....

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[The walking icon is here](https://icons8.com/icon/3931/walking).

I'm beginning a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close icon](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icon.

Please let me know if you want me keep going these icon requests, or compile some upgrade file, or how should we do it?

**Comment by c0debreaker** [comment]
I'm extremely shocked to see the long thread! I was writing a home automation control panel using ReactJS. I'm now coding the motion sensor component and I needed a walk icon. To my surprise, FontAwesome doesn't provide it. Looking at the whole thread, I guess it's time to find another library.

**Comment by Crissov** [comment]
Fontawesome 5 is due to be released soon. It's possible this icon is included in one of the expansion packs (though perhaps only in the paid Pro version). As far as I can see that's impossible to know for non-backers, so the Fortawesome team should probably tag all applicable icon request issues with the 5.0 milestone or a dedicated label.

**Comment by raph-tr** [comment]
+1 please !!!

**Comment by andreynovikov** [comment]
More then four years? Cool! +1

**Comment by Wintermute79** [comment]
booooo!

**Comment by tnargib** [comment]
2 177 icons in version 5 and not even a simple stickfigure walking ? after 4 years ? Ah come ooooon !

**Comment by miketubby** [comment]
+1 for walking icon - need it already ;-)

**Comment by c6410** [comment]
this is unbeleivable. whats wrong with font awesome ? some changes in management or being sold in flippa ?

**Comment by achardes** [comment]
+1   :)

**Comment by ebbishop** [comment]
+1 for pedestrian

**Comment by harrisbones** [comment]
+1

**Comment by adw0rd** [comment]
+1

**Comment by einavsh** [comment]
Shall we celebrate the 5th (!) anniversary to this icon request? 😕 
This is the third most commented icon request, and we've seen the release of version 5 come and go, and still no walking icon.
Looks like no one from FontAweosome even bothers to read the comments here...  👎

**Comment by tnargib** [comment]
I got bored... maybe I have to much time to waste...

```html
<span class="fa-layers fa-fw">
  <i class="fas fa-circle" data-fa-transform="shrink-12.8 up-5"></i>
  <!-- Body -->
  <i class="fa fa-minus" data-fa-transform="rotate--85 left-0.4 up-0.3 shrink-10"></i>
  <i class="fa fa-minus" data-fa-transform="rotate--85 left-0.6 down-2 shrink-10"></i>
  <!-- Left arm -->
  <i class="fa fa-minus" data-fa-transform="rotate--50 left-1.7 up-0.95 shrink-11"></i>
  <i class="fa fa-minus" data-fa-transform="rotate--85 left-3.1 down-2.4 shrink-11"></i>
  <!-- Right arm -->
  <i class="fa fa-minus" data-fa-transform="rotate--120 right-1 up-0.7 shrink-11"></i>
  <i class="fa fa-minus" data-fa-transform="rotate--140 right-3.45 down-2.2 shrink-11"></i>
  <!-- Left leg -->
  <i class="fa fa-minus" data-fa-transform="rotate--85 left-1.05 down-5.5 shrink-11"></i>
  <i class="fa fa-minus" data-fa-transform="rotate--60 left-2.15 down-9 shrink-11"></i>
  <!-- Right leg -->
  <i class="fa fa-minus" data-fa-transform="rotate--120 right-0.5 down-6 shrink-11"></i>
  <i class="fa fa-minus" data-fa-transform="rotate--120 right-2.25 down-9 shrink-11"></i>
</span>
```

![image](https://user-images.githubusercontent.com/14888725/37597558-0bbc0c78-2b80-11e8-8ada-e41caad3fb63.png)

**Comment by sensibleworld** [comment]
👋 This icon is coming soon!

**Comment by sensibleworld** [comment]
It's time for a stroll. https://fontawesome.com/icons/walking?style=solid
