### ISSUE TITLE
Icon Request: fa-family

### ISSUE THREAD

**Issue by ambseguros** [FortAwesome/Font-Awesome#8442]
I request a new family icon. I'll use it for medicine and psychology. eg

![image](https://cloud.githubusercontent.com/assets/16941149/12650352/88eaba7e-c5b0-11e5-8439-7871380bd267.png)
![image](https://cloud.githubusercontent.com/assets/16941149/12650364/8f2110d2-c5b0-11e5-9817-18a817fb711e.png)

Thanks.

**Comment by tagliala** [comment]
duplicate of #3277 , please +1 that request

closing here
