### ISSUE TITLE
Icon Request: icon-head-with-brain

### ISSUE THREAD

**Issue by ariadnehealthify** [FortAwesome/Font-Awesome#8443]
Hi there. I work for an app that organizes social service resources. We organize our taxonomy by category and currently put Mental Health under our Health category. Seeing as there are already so many medical services, we'd like to add a separate Mental Health category. I can't seem to find an icon that represents it well. I was wondering if you could provide me with a new icon representing mental health. I think one showing someone's brain would be a real easy and effective icon. Here are a few examples. This would be used around therapy, counseling, psychiatry, etc. 

Thanks!
![icon_6728](https://cloud.githubusercontent.com/assets/13786179/12653735/db98ac32-c5be-11e5-9a8b-09fd46dbabce.gif)

![mental-health-icon-e1452576482162](https://cloud.githubusercontent.com/assets/13786179/12653744/e1e5758e-c5be-11e5-87cf-9905edc97496.png)

**Comment by tagliala** [comment]
refers to #2075 

Could a brain suit your needs?

**Comment by ariadnehealthify** [comment]
I'd rather it have someone's head, we try to keep all images in our app centered on a human perspective rather than an objectified perspective. Meaning, we want the person to be well, not the brain to be fixed. Thoughts?

**Comment by ariadnehealthify** [comment]
If a head and brain is too complex then even just a person's head profile would do

**Comment by ariadnehealthify** [comment]
Hey there, any updates on this?

**Comment by klambacher** [comment]
+1 

Also commented in head with gears request https://github.com/FortAwesome/Font-Awesome/issues/8675. Either head with gears or head with +, for mental health and addictions use. Use case is the same as above (social services classification).

**Comment by kimberley-johnston** [comment]
+1

**Comment by frague59** [comment]
+1

**Comment by PhilemonBouzy** [comment]
+1

**Comment by celinenicolas** [comment]
+1

**Comment by joaovsoares** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/head-side-brain?style=solid
