### ISSUE TITLE
Missing content for some icons 

### ISSUE THREAD

**Issue by AdamPerkins** [FortAwesome/Font-Awesome#8445]
In the _icons.scss file I miss for different icons the content.

For ex. gears
.#{$fa-css-prefix}-gear:before { content: $fa-var-gear; }
.#{$fa-css-prefix}-gears:before { content: $fa-var-gears; }

Is there any reason for that? After replacing the correct value it was working for me.

**Comment by tagliala** [comment]
gear and gears are aliases for cog and cogs

https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L227
https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml#L1365

hope it helps

closing here
