### ISSUE TITLE
Icon request: icon-hr

### ISSUE THREAD

**Issue by SamSaffron** [FortAwesome/Font-Awesome#845]
I have just ported our markdown editor at discourse ( http://discourse.org ) to font awesome. 

It used to look like this:

<img src="http://cdn.discourse.org/uploads/meta_discourse/520/a613abb18e04e707.png" width="402" height="37">

and now it looks like this: 

<img src="http://cdn.discourse.org/uploads/meta_discourse/521/284683d704ac7711.png" width="400" height="33">

Trouble is, I was unable to find parity for:

Horizontal rule, Heading and Code Block. 

( you can see the old icons at http://stackoverflow.com/questions/ask )

would be mighty awesome to have this included in font awesome 3.1 

Thanks for the awesome project.

**Comment by mightymt** [comment]
+1 for hr icon

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/horizontal-rule?style=solid
