### ISSUE TITLE
Icon Request: fa-youtube-play-square

### ISSUE THREAD

**Issue by veritoanimus** [FortAwesome/Font-Awesome#8452]
The YouTube play icon is always problematic if you want to use it with a group of squared social icons.  You should also offer a YouTube play with square encapsulation to match sizing for the other icons as allowed per YouTube's logo usage policies: https://www.youtube.com/yt/brand/using-logo.html

**Comment by dnavarrojr** [comment]
+1

**Comment by TheEssemCraft** [comment]
I made a mockup SVG, what do you think?
[youtube-play-square.zip](https://github.com/FortAwesome/Font-Awesome/files/945737/youtube-play-square.zip)

**Comment by tagliala** [comment]
Sorry but this is a duplicate of #7238 and I didn't notice
