### ISSUE TITLE
Icon Request: fa-orange (fruit)

### ISSUE THREAD

**Issue by Natalee999** [FortAwesome/Font-Awesome#8456]
Citrus. I am requesting a orange aweome icon.

Thank you!

**Comment by pauloafernandes-82** [comment]
Seconded. I think a collection of fruit icons in general would be very useful. I need orange in particular, but I digress.

**Comment by sensibleworld** [comment]
We have a whole bunch of fruit icons now, including a [`citrus`](https://fontawesome.com/v6.0/icons/citrus?s=solid) icon and a [`citrus-slice`](https://fontawesome.com/v6.0/icons/citrus-slice?s=solid) icon.

https://fontawesome.com/v6.0/icons?c=fruits-vegetables
