### ISSUE TITLE
Icon request: icon-tractor

### ISSUE THREAD

**Issue by Varnisc** [FortAwesome/Font-Awesome#8458]
Hey guys

I am building a website for automotive spare parts and I am looking for a tractor icon, like the one in the image, to go along with the farm equipment category. 

![tractor-](https://cloud.githubusercontent.com/assets/16969169/12693822/aa016a54-c70f-11e5-9d8b-d2bedcdaa48a.png)

Thank you 
Varnis

**Comment by stringsanbu** [comment]
+1.

**Comment by tagliala** [comment]
dup of #5052
