### ISSUE TITLE
Icons request: pet adoption set

### ISSUE THREAD

**Issue by petpal** [FortAwesome/Font-Awesome#8459]
Well actually my request is for adding a couple of new icons, I'm building a non profit pet adoption site and I found this font really awesome (font-awesome, haha) but besides of the paw icon there's strictly nothing I can use which is pet related :(

So my ideas are:
* A kennel icon - should be something like the house one just with a paw draw on it.
* A cat inside dog icon - something like this one: http://veterinariosolidario.es/wp-content/uploads/2015/04/boton-adopcion-veterinariosolidario.png
* Lost & Found icon for pets (so far I don't think font awesome has any icon that can be used for lost & found in general) - perheps a dog laying down feeling lost or so...
* NGOs icon - something like this http://nyccamp.org/sites/default/files/styles/icon_-_header/public/nycc-icon-nonProfit-NGO.png?itok=jrmMW42T just with a paw instead of that earth icon in the middle.

The above are most important ones for me, rest could be optional as you see fit :)
* Articles icon - a book with a paw inside? ;)
* Videos icon - a screen with dog/cat/paw inside.
* Contact us icon - a letter with a paw stamp on it.
* About us - dog and cat looking directly at screen, something like so.. http://i.ebayimg.com/00/s/MTYwMFgxMjc0/z/ulcAAOxy9eVROz2Z/$T2eC16R,!zUE9s38+HeRBROz2Yj1s!~~60_35.JPG
* Forum icon - the well known 3 persons icon just with a dog in the middle instead of the middle person - https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQXoSYcf6g10F43ROI7-pQFcLgfPzM6NDwJPBWEySW5pnyjvEK-WA

Hope I didn't ask for so much (joke, I know I did) but am really looking forward for such an icon set which will make my website look lot more proffesional :)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

You should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here
