### ISSUE TITLE
Icon request: fa-waffle and fa-waffle-square

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#8466]
Can you please include [Waffle](https://waffle.io/)'s logo? Please also make a square one. I plan on using it in a website for a project which uses GitHub for source code hosting and Waffle for project management...

**Comment by leosa83** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
Duplicate of #4319.

**Comment by aethior** [comment]
> Duplicate of #4319.

You're right. In all case the project seems discontinued.

cc/ @tagliala
