### ISSUE TITLE
Icon request: fa-openoffice

### ISSUE THREAD

**Issue by F0urchette** [FortAwesome/Font-Awesome#8467]
Can you please include OpenOffice's logo ? I plan using it on my resume on Internet. Here is an image of the logo.
![orb](https://cloud.githubusercontent.com/assets/16985364/12701940/228d2bfc-c819-11e5-91a8-48146db1b347.jpg)

**Comment by tagliala** [comment]
duplicate of #3661, please +1 that request

closing here

**Comment by aethior** [comment]
Hi @tagliala,

I think this suggestion is a brand icon request `fa-openoffice` and #3661 is a file type request `fa-file-odt-o`.

**Comment by tagliala** [comment]
@aethior thanks.

title and example didn't match

let's use #3661 for the brand and #4000 for odt
