### ISSUE TITLE
BLACKBERRY

### ISSUE THREAD

**Issue by kazuser** [FortAwesome/Font-Awesome#8470]
Please, give us the f*****g [BLACKBERRY](https://github.com/FortAwesome/Font-Awesome/issues/1537)!!!!!11 See how many people want it!!! Look how long we want it (almost 2,5 years!)!!! Are you a blind there?! Someone of us even gived to you a ready SVG-file - only you would have accelerated!!! So what are you waiting for???

**Comment by tagliala** [comment]
If you need the blackberry icon, please consider a custom version: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Please also be nice

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
