### ISSUE TITLE
Icon Request: icon-insurance

### ISSUE THREAD

**Issue by bettyorganero** [FortAwesome/Font-Awesome#8473]
![insurance](https://cloud.githubusercontent.com/assets/250286/12721743/8f21efd0-c901-11e5-851f-65e3cc1b9deb.png)

**Comment by Patrick-W-McMahon** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
If this were added, there would need to be multiple versions, accommodating each currency icon.

**Comment by bettyorganero** [comment]
don't worry I found other solution 
;) thanks

**Comment by tausi0661** [comment]
@bettyorganero may we know what your solution is? :P

**Comment by tagliala** [comment]
A shield without currency could represent an insurance: https://fontawesome.com/icons/shield-alt?style=solid

Pro users also have a shield with check

**Comment by Vasimovic** [comment]
How about an umbrella or a hand with users under it?

![image](https://user-images.githubusercontent.com/2503098/43206190-f6b73e60-8fd9-11e8-91ec-0770e98dcf44.png)

![image](https://user-images.githubusercontent.com/2503098/43206204-020d2428-8fda-11e8-99f7-8a2e23a87a00.png)
