### ISSUE TITLE
Icon Request: icon-bank-percent

### ISSUE THREAD

**Issue by bettyorganero** [FortAwesome/Font-Awesome#8474]
![bank-percent](https://cloud.githubusercontent.com/assets/250286/12721819/ed3035be-c901-11e5-8c0f-5409316db6f2.png)

**Comment by caduvieira** [comment]
Related to #1181

**Comment by tagliala** [comment]
I need a better title for this one.

bank: http://fontawesome.io/icon/university/
building: http://fontawesome.io/icon/building/ 

what does represent the object behind the percent?

**Comment by sensibleworld** [comment]
We have a few icons for "percent" now: https://fontawesome.com/icons?d=gallery&q=percent

If these don't work, please open another request following our current guidelines: https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md
