### ISSUE TITLE
Icon Request: fa-void

### ISSUE THREAD

**Issue by brianmains** [FortAwesome/Font-Awesome#8476]
I'd like to request an icon similar to the cc-visa icon.  It's simply an icon with the text VOID, maybe with a border around it.  I'm working on a accounting ledger feature in an application and will use this icon to apply to payments that were voided.  I couldn't really find anything that clearly indicated that.  Thanks!

**Comment by tagliala** [comment]
so this is not a payment icon, it represents the status of a payment operation?

It is also language dependent

**Comment by brianmains** [comment]
That is correct, it's not a payment icon.  It is a status.  I mentioned that only as a reference point.  I would agree that it is language dependent.  I'm not sure how other cultures indicate void...

**Comment by PeterShaggyNoble** [comment]
Have you considered layering fa-ban over the relevant payment icon(s)?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
