### ISSUE TITLE
Icon Request: fa-chilli

### ISSUE THREAD

**Issue by Emaitch** [FortAwesome/Font-Awesome#8479]
I'm working on a restaurant menu, for both printing and website. Could we have a pepper/chilli icon please? Even a thermometer could be useful for heat warning references. Keep up the great work!

**Comment by Patrick-W-McMahon** [comment]
fa-thermometer-0
fa-thermometer-1
fa-thermometer-2
fa-thermometer-3
and have it with different amount filled. much like the battery icon
+1

**Comment by tagliala** [comment]
thermometer: #720 
chilli: #1684 

Please +1 the proper requests

closing here
