### ISSUE TITLE
Icon Request: dice and coin

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [FortAwesome/Font-Awesome#8481]
a full set of dice for example coin-h, coin-t, d4-1, d4-2, d4-3,d4-4,d6-1,d6-2,d6-3,....

1. coin would have heads or tails
2. all dice sizes with all sides D4, D6, D12, D20, D100
3. all sides of every die

fa-coin-h
fa-coin-t
fa-d6-1
fa-d6-2
fa-d6-3
fa-d6-4
fa-d6-5
fa-d6-6
and so on

**Comment by dnavarrojr** [comment]
+1 to the coin

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.

**Comment by Patrick-W-McMahon** [comment]
I'm a bit lost as to how this would be a comprehensive set of icons related to a very specific field. I can see many uses for dice and coin icons for many projects and many websites. They could also be used for many online web adventure games. There very general in its use and so can be used in many places.

**Comment by Patrick-W-McMahon** [comment]
Or this could be part of an extended font awesome pack. like a 2nd file that is included for extra icons.
