### ISSUE TITLE
Icon Request: fa-pac-man fa-pac-woman fa-pac-ghost

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [FortAwesome/Font-Awesome#8482]
pac man, pac woman and the ghosts from the original game.

also possible animated states for each. for example 
fa-pac-man-0
fa-pac-man-1
fa-pac-man-3
different stages of the pac man mouth open and closed.

**Comment by tagliala** [comment]
I think this request is out of scope.

Leaving this open for the moment

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

**Comment by sensibleworld** [comment]
You can hack something together with:

https://fontawesome.com/icons/circle?s=solid&f=classic
https://fontawesome.com/icons/circle-three-quarters?s=solid&f=classic (rotated 45º)
and https://fontawesome.com/icons/ghost?s=solid&f=classic
