### ISSUE TITLE
Icon Request: fa-bottle

### ISSUE THREAD

**Issue by N4Design** [FortAwesome/Font-Awesome#8483]
I use Font Awesome a lot on a hospitality site I built.  I would like a couple of extras: fa-bottle (wine bottle (& glass) and fa-dome (serving dome).  Examples attached...
[Bottle & Glass.pdf](https://github.com/FortAwesome/Font-Awesome/files/114887/Bottle.Glass.pdf)
[Serving Dome.pdf](https://github.com/FortAwesome/Font-Awesome/files/114888/Serving.Dome.pdf)

**Comment by tagliala** [comment]
Duplicate of #1762 , please +1 that request

closing here
