### ISSUE TITLE
Icon Request: fa-search-thin

### ISSUE THREAD

**Issue by elloPropello** [FortAwesome/Font-Awesome#8486]
hey, it would be cool if there was a lighter version of the search-icon.
just like the current one but with thin lines.

thx, ello

**Comment by tagliala** [comment]
refers to #1733

**Comment by rpedela** [comment]
+1

**Comment by aethior** [comment]
I think this issue is solved with the current `THIN` version.
Check https://fontawesome.com/icons/magnifying-glass?s=thin

Regards.

cc/ @tagliala
