### ISSUE TITLE
Icon Request: fa-foundbite

### ISSUE THREAD

**Issue by tim99-1977** [FortAwesome/Font-Awesome#8489]
Brand Icon: [https://foundbite.co/user7791046910](https://foundbite.co/user7791046910)
Example: `<a href="https://foundbite.co"><i class="fa fa-foundbite"> Foundbite Profile</i></a>`

![unbenannt2](https://cloud.githubusercontent.com/assets/7683226/12802993/4f6a548a-cae7-11e5-8a03-c827dcf8fbb3.PNG)

**Comment by aethior** [comment]
>Sadly Foundbite shut down on the 31st March 2017. You can read more about the reasons for us closing the service [here](https://blog.foundbite.co/thanks-for-the-memories-3b9afc512dec). Thanks to everyone who used the app, helped us out along the way and shared our vision to allow people to share their memories and experiences from around the world using sound. ([more info](https://foundbite.co/))

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please. :)
