### ISSUE TITLE
Icon request: fa-steps-up and fa-steps-down

### ISSUE THREAD

**Issue by rickb777** [FortAwesome/Font-Awesome#8490]
This would be a simple variant of fa-navicon / fa-reorder, but with shorter lines.

There would be three short lines arranged like steps to indicate an ascending sequence of steps.

The second variant would be similar but be arranged like a descending sequence of steps.

**Comment by tagliala** [comment]
do http://fontawesome.io/icon/sort-amount-asc/ and http://fontawesome.io/icon/sort-amount-desc/ suit your needs?

**Comment by oreynaldocl** [comment]
About these icons, in v4.7 the *fa-sort-amount-asc* and *fa-sort-amount-desc* they show the information better. The bigger block in correct position. But in v5 the the bigger block keeps in same way.
In v5 what is used for ascending order? 
![image](https://user-images.githubusercontent.com/1781538/43416889-80bbbba0-9407-11e8-82d4-e3c41ac42512.png)

**Comment by tagliala** [comment]
@oreynaldocl thanks for pointing this out

There are definitely issues with those icons, please follow up https://github.com/FortAwesome/Font-Awesome/issues/9464#issuecomment-228602405

Workaround: https://github.com/FortAwesome/Font-Awesome/issues/9464#issuecomment-380686471

**Comment by sensibleworld** [comment]
This has been fixed in version 6.
