### ISSUE TITLE
Icon request: icon-readers-legacy

### ISSUE THREAD

**Issue by AlchemyNow** [FortAwesome/Font-Awesome#8495]
There's a new social community site that can basically be summed up as "Facebook for book nerds, authors, and publishers."   [https://www.readerslegacy.com/me/aaron](https://www.readerslegacy.com/me/aaron)  There's just over 10K users currently.

Having the icon would be integrated with the site as well as some WordPress themes.

Sorry  https://www.readerslegacy.com/

**Comment by aethior** [comment]
`redeadslegacy.com` domain is shut down.
The instagram account not have activity since 2016 ([link](https://www.instagram.com/readerslegacy/)).

cc/ @tagliala
