### ISSUE TITLE
Icon Request: fa-<:x>percent

### ISSUE THREAD

**Issue by prvinuch** [FortAwesome/Font-Awesome#8496]
Hi,

Can we have Icons for each Percentage value say, if I give 
<i class='fa fa-10percent'><i>  this can return an awesome icon for 10% or any damn value which we provide (limited to integers only) at run time, even 43.

Regards
Praveen Agarwal

**Comment by tagliala** [comment]
sorry, i need to close this one

Please consider an .svg or css based solution

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
