### ISSUE TITLE
Icon request: icon-Dealer Analytic

### ISSUE THREAD

**Issue by jgbalaji** [FortAwesome/Font-Awesome#8497]
We have an use case to represent a critical module in a parent application where the critical module has a data analytics information based on the dealer performance. So would like to have a new icon defined to represent "Dealer Analytics". Basically, the current icons in analytics defined just the chart, which is not more attractive or communicating the intended functionality just by looking at the icon. So it would be good if we get some form of icon that clearly represents "Dealer Analytics"

**Comment by tagliala** [comment]
sorry, could you please post an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
