### ISSUE TITLE
Bad explanation

### ISSUE THREAD

**Issue by YagoLopez** [FortAwesome/Font-Awesome#8499]
I regret to say this but the explanation of the "easy" way to install font-awesome is very poor. I had to investigate my html to realize that, besides to have the font awesome css file, I must have a directory at the same level of css directory, called 'fonts', with the *.eot files, etc. The explanation maybe is valid for a blank project, but it is incomplete for an existent project.

**Comment by wolfy1339** [comment]
You can change the font URL in the CSS to point to the font awesome CDN instead.
You would just need to remove the `..` that is prepended and then prepend `https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/` before the URL

**Comment by tagliala** [comment]
Hi,

> I must have a directory at the same level of css directory, called 'fonts', with the *.eot files, etc. The explanation maybe is valid for a blank project, but it is incomplete for an existent project.

Step 1. of "Easy" setup is:

> 1. Copy the entire font-awesome directory into your project.

If you do that, you will have a `fonts` folder at the same level of `css`

IMHO instructions are fine, anyway feel free to suggest a change

**Comment by YagoLopez** [comment]
Thanks, @wolfy1339. I know it. The question is I have to waste time to discover it. With a couple of lines of explanation in the web I could have avoided that.

@tagliala, I preferred not to copy the entire directory in my existing project. I chose to do a manual installation. I think it is a reasonable election. I have never used Fontawesome before, and thought initially you just have to copy the *.css files. Now I know it is needed the font directory. Anyway I just wanted to avoid this situation to anyone who want to use Fontawesome for first time in the future.
