### ISSUE TITLE
Houzz Icon not working on my wordpress theme

### ISSUE THREAD

**Issue by saltflatstudios** [FortAwesome/Font-Awesome#8501]
Hi -
You have the Houzz icon (fa-houzz) created, however it's not available as part of the social icons list for the wordpress Make theme. Is there any way to get this added?
Thanks!
Natalie

**Comment by tagliala** [comment]
Please check that your theme is using a recent version of fontawesome

Houzz was introduced in version 4.4

If you are using FA < 4.4.0, you can edit your theme or contact the developer

Hope it helps,

closing here
