### ISSUE TITLE
Icon Request: fa-comprehensive

### ISSUE THREAD

**Issue by Pezhvak** [FortAwesome/Font-Awesome#8504]
Hi, i think it would be nice to include a 'comprehensive' icon.
it will be useful for web introduction. like:
"Comprehensive Online & Mobile Management"
![ico_comprehensive](https://cloud.githubusercontent.com/assets/3134479/12874212/b0729a12-cde4-11e5-9881-8951ca4c2327.png)

**Comment by tagliala** [comment]
sorry but I need to close this request

Please +1 #1446 for multi platform / responsive icon
