### ISSUE TITLE
Icon request: fa-united-states

### ISSUE THREAD

**Issue by grandprix321** [FortAwesome/Font-Awesome#8507]
This is a multiple request, but I hope it makes sense. I am looking for all 50 United States icons.

I was looking for something like a simple silhouette of the outline of the state such as seen in the file attached.
![alaska](https://cloud.githubusercontent.com/assets/12488471/12888452/383510f2-ce48-11e5-9483-941d02405ec1.gif)

I was planning on using it alongside the states name for a navigational bar.

**Comment by tagliala** [comment]
Hi, unfortunately I have to close this one

Please take a look at #3992 if you want more details on this choice

Please consider an .svg based solution
