### ISSUE TITLE
fa-soccer-card

### ISSUE THREAD

**Issue by iwarner** [FortAwesome/Font-Awesome#8509]
Card can be coloured Red or Yellow or Green for the the three types

something similar to, but in FA style would be great
http://www.flaticon.com/free-icon/soccer-yellow-or-red-card-in-a-hand_53209

**Comment by tagliala** [comment]
duplicate of #4621, only for a rectangle

Please note that icon fonts are limited to one color, so also the hand would be red or yellow

Closing here
