### ISSUE TITLE
Icon Request: icon-name

### ISSUE THREAD

**Issue by hemka007** [FortAwesome/Font-Awesome#8514]
I want to add these icons into my website which are not available yet.
icon-wheat
icon-maize
icon-rice
icon-pulses
icon-jute
icon-sugarcane

**Comment by tagliala** [comment]
Sorry,

can't leave this open

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
