### ISSUE TITLE
Icon Request: fa-couchdb

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [FortAwesome/Font-Awesome#8524]
Hello,

Thank you for your great contribution and for sharing with us.
I would kindly ask you to include an icon for CouchDB logo. This is an open source project: https://github.com/apache/couchdb and we would like to use Font-Awesome in our couch applications.

I attached some official logo samples in svg format.
Thank you in advance,
Dragos
[CouchDB_Logo_SVG.zip](https://github.com/FortAwesome/Font-Awesome/files/124902/CouchDB_Logo_SVG.zip)

**Comment by dragos-constantin-stoica** [comment]
Hello,

CouchDB changed their logo for version 2.0.
All files are stored at: https://github.com/apache/couchdb-www/tree/asf-site/CouchDB-visual-identity/logo

You may use the following files:
https://github.com/apache/couchdb-www/blob/asf-site/CouchDB-visual-identity/logo/CouchDB-couch-symbol.ai
https://github.com/apache/couchdb-www/blob/asf-site/CouchDB-visual-identity/logo/CouchDB-couch-symbol.eps
https://github.com/apache/couchdb-www/blob/asf-site/CouchDB-visual-identity/logo/CouchDB-couch-symbol.pdf
https://github.com/apache/couchdb-www/blob/asf-site/CouchDB-visual-identity/logo/CouchDB-couch-symbol.png

Thank you in advance,
Dragoş

**Comment by tagliala** [comment]
Thanks for the heads up 👍

**Comment by dragos-constantin-stoica** [comment]
I can use the couch icon. Thank you!
