### ISSUE TITLE
icon request: e-commerce products icon

### ISSUE THREAD

**Issue by alexmorbo** [FortAwesome/Font-Awesome#8525]
Hi!

It will be great to add products catalog icon for admin area.

**Comment by tagliala** [comment]
could you please provide a single color example suitable for 14px icon size?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by alexmorbo** [comment]
[http://www.mirakstellar.com/Images/box.png](url)

**Comment by tagliala** [comment]
maybe a duplicate of #908 or #6221

**Comment by alexmorbo** [comment]
yes, agree
