### ISSUE TITLE
Icon request: icon-lyft

### ISSUE THREAD

**Issue by slsmag** [FortAwesome/Font-Awesome#8526]
Icon request: 
icon-lyft

Icons used for easy indentification of topics in bulletin boards, forums, etc. related to the those organizations
![](https://cloud.githubusercontent.com/assets/10437313/12951113/bedd5fa0-cfde-11e5-8be3-b0357675d5bd.gif)

**Comment by tagliala** [comment]
uber is a duplicate of #4826, please +1 that request

leaving this open as fa-lyft

**Comment by vinniejames** [comment]
:+1:

**Comment by dan-0** [comment]
:+1:

**Comment by tagliala** [comment]
Hi, thanks for your reactions to this request!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
