### ISSUE TITLE
incorrect offset when exporting to individual SVG

### ISSUE THREAD

**Issue by myGitPersonae** [FortAwesome/Font-Awesome#8530]
I am trying to use the individual icons as SVG
When exported via Fontforge from the ttf font, the icons are cropped at the bottom. 
the lateral offset is not the same, but the vertical offset seems the same
for a few files, the exported SVG is empty

the following workaround for offset works
`fontforge -lang=ff -c 'Open($1); SelectWorthOutputting(); foreach Move(128,256); Export("svg"); endloop;' awesomefont.ttf`
[_382_FontAwesome.zip](https://github.com/FortAwesome/Font-Awesome/files/125124/_382_FontAwesome.zip)
[collapse_alt_FontAwesome.zip](https://github.com/FortAwesome/Font-Awesome/files/125147/collapse_alt_FontAwesome.zip)

[_329_FontAwesome.zip](https://github.com/FortAwesome/Font-Awesome/files/125122/_329_FontAwesome.zip)

**Comment by tagliala** [comment]
.svg and .ttf formats are generated from the `.otf` file via fontsquirrel's webfont generator: http://www.fontsquirrel.com/tools/webfont-generator
