### ISSUE TITLE
google-plus updated on fa site not in reference

### ISSUE THREAD

**Issue by richbannon** [FortAwesome/Font-Awesome#8533]
I see a lot of people requesting the new google plus logo but I am assuming those are old posts, the font awesome site icons page shows the new logo for google and google-plus but when using it were still seeing the old logo, am using the latest version reference - https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css but still see the old logo. 

Thanks

**Comment by tagliala** [comment]
Please check that you are not loading an old version of the font

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay particular attention to point 4

Hope it helps, closing here
