### ISSUE TITLE
fa-diamond is not working

### ISSUE THREAD

**Issue by topleague** [FortAwesome/Font-Awesome#8536]
I tried to use fa-diamond on my website but it's not working while icons are working perfectly fine. It's showing a x mark. I've also seen the same issue for some other icons as well but I can't remember them right now. Will raise an issue as soon as I encounter issue again. 

Appreciate any advice!

**Comment by tagliala** [comment]
can't confirm. Please make sure you are using FA >= 4.3.0

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay particular attention to point 4, closing here

**Comment by topleague** [comment]
Thanks a lot! I didn't realize that. Just went to my functions.php file and updated the version from 4.1.0 to 4.3.0! Silly me! :)

**Comment by tagliala** [comment]
@topleague you're welcome, glad you solved :+1:
