### ISSUE TITLE
Problem with version file: font-awesome.css

### ISSUE THREAD

**Issue by juan790** [FortAwesome/Font-Awesome#8539]
hello, I understand my problem:
when I insert the file: font-awesome.css in /fonts, the file version changes from 4.5.0 to 4.1.0. So I do not have the amazon icon.

is a theme of my problem?

**Comment by tagliala** [comment]
Have you a live example of the issue?

**Comment by juan790** [comment]
Instead, in css folder the file is correct (4.5.0). I copy this file in the folder /fonts and this will change to 4.1.0

here is the file in the folder /fonts: http://recensioneprodotto.altervista.org/wp-content/themes/anew/fonts/font-awesome.min.css

The icons in 4.1.0 version, work! (es. facebook)

**Comment by tagliala** [comment]
if your theme is using an older version of FA you have to edit your theme or contact the author

hope it helps,

closing here
