### ISSUE TITLE
Icon Requests: network devices

### ISSUE THREAD

**Issue by wojti** [FortAwesome/Font-Awesome#854]
Hi,

It would be great to have following network device icons: 
- router,
- switch,
- hub,
- firewall,
- terminal server
- wifi connection
- wire connection
- serial connection
- radio wave device
- terminal (console)

regards,
w.

**Comment by hightekjonathan** [comment]
+1

**Comment by tagliala** [comment]
This request is closed and does not meet contributing guidelines.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Locking here :lock:
