### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by bluex2** [FortAwesome/Font-Awesome#8540]
Hi Guys

Love all your icons. Am looking for a Safe Box icon. Security safe that is in some rooms. Would be a great addition.

Cheers
Tony

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by bluex2** [comment]
Hi Guys

If you look at King Suite here http://ravistheme.com/yoona/wp/ and click on details you will see an icon for room security. We'd happy with this?

There is also this icon TV in room - would you be able to do one with a cross over that says no TV in room?

Cheers
Tony

**Comment by tagliala** [comment]
could you please post here a single color example of the icon you need?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Attach a single color image or two that represent the idea you're going for.
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by bluex2** [comment]
Hi Guys

The same colour as on this site http://ravistheme.com/yoona/wp/ and click on details you will see an icon for room security. 

There is also this icon TV in room - would you be able to do one with a cross over that says no TV in room?

**Comment by tagliala** [comment]
@bluex2 please get the image by yourself and post it here or search on google images

**Comment by krahamath** [comment]
@bluex2 the icon is available with FontAwesome already. Check http://fortawesome.github.io/Font-Awesome/icon/unlock-alt/

**Comment by bluex2** [comment]
Hi Guys

Here is an icon I wold like added to your list. It's a No TV icon for rooms in hotels thaat don't have televisions.

Would you be able to add this please. I have attached it.
Cheers
Tony
![no-tv](https://cloud.githubusercontent.com/assets/11304393/14526586/79792f00-0244-11e6-85c8-1373de7dd1ad.jpg)

**Comment by PeterShaggyNoble** [comment]
@bluex2, you should create a new issue for a new, unrelated request.

However, in this case, you can achieve what you want by [stacking](http://fortawesome.github.io/Font-Awesome/examples/#stacked) (fa-ban)[http://fortawesome.github.io/Font-Awesome/icon/ban/) on (fa-television)[http://fortawesome.github.io/Font-Awesome/icon/television/].

**Comment by tagliala** [comment]
Sorry, I'm going to close this one

Please make sure you read our contributing guidelines before opening new requests

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
