### ISSUE TITLE
Request TeamSpeak and AskFM Logo

### ISSUE THREAD

**Issue by NoHacks** [FortAwesome/Font-Awesome#8542]
Jah community!
I really like FontAwesome and i use it a long time.
But 2 icons from big communitys are not there!
That would TeamSpeak and AskFM.
I hope you will add this icons..

Thanks for this projekt,
NoHacks

**Comment by tagliala** [comment]
teamspeak: #1474 
ask-fm: #3762

please +1 the above requests

closing here
