### ISSUE TITLE
Icon request: icon-eye-of-providence

### ISSUE THREAD

**Issue by esotericast** [FortAwesome/Font-Awesome#8546]
Would be cool to get this symbol made into an icon!

![eye of providence](https://cloud.githubusercontent.com/assets/12773556/12999169/2e96360a-d11a-11e5-8b2d-119e39392cc1.png)

**Comment by tagliala** [comment]
is this a duplicate of #5713?

**Comment by ktoump** [comment]
nope
https://en.wikipedia.org/wiki/Eye_of_Providence
https://en.wikipedia.org/wiki/Eye_of_Horus
