### ISSUE TITLE
icon for home N personal things

### ISSUE THREAD

**Issue by krahamath** [FortAwesome/Font-Awesome#8547]
I need icons for home things such as table, chair, sofa and bed and for personal dress, shorts, top, shoe and accessories.

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

There are duplicates: #759 #4149 #1998 and more
