### ISSUE TITLE
Ravelry Icon

### ISSUE THREAD

**Issue by jessicajohannesen** [FortAwesome/Font-Awesome#8550]
I would really like to see an icon for Ravelry.com added to font awesome. 
![49061-ravelry-logo-icon-vector-icon-vector-eps](https://cloud.githubusercontent.com/assets/6635174/13011024/d4640dca-d172-11e5-9564-e2c009c2050e.png)

**Comment by tagliala** [comment]
Duplicate of #3314, please +1 that request

closing here
