### ISSUE TITLE
Icon request: fa-draw-line

### ISSUE THREAD

**Issue by MightyFo0l** [FortAwesome/Font-Awesome#8552]
For use in drawing applications and other stuff. You already have a pencil and paint brush icon. But no icon that represents drawing lines. I plan to use it in mine.

![line2p 1](https://cloud.githubusercontent.com/assets/16845714/13011556/9bad808a-d1a7-11e5-9245-08a993453917.png)

Made this myself (already using it in my app)
![untitled-1](https://cloud.githubusercontent.com/assets/16845714/13011598/ccc7676c-d1a7-11e5-84d0-7d440cdb018b.png)

**Comment by MightyFo0l** [comment]
I was wondering why this still isn't labeled?
@tagliala

**Comment by tagliala** [comment]
Because it is a duplicate and sometimes I miss requests.

Please +1 #3557 and post there your example

closing here
