### ISSUE TITLE
fa-balance-scale not working, no :before content, v4.5.0

### ISSUE THREAD

**Issue by GarrettML** [FortAwesome/Font-Awesome#8553]
The title sums up the issue. The icon does not display because this class is not listed, and so 
it has no before content listed in the css (either version). I am using the most recent version: v4.5.0. Please fix.

**Comment by tagliala** [comment]
Of course I cannot confirm: https://jsfiddle.net/tagliala/syduuue9/18/

Please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by nicolasbadia** [comment]
For the record, I'm also having this issue but only in my app and in Safari. The [fiddle](https://jsfiddle.net/tagliala/syduuue9/18/) works in Safari and my app works in Chrome or Firefox too.
Same weirdness for the percent icon: https://github.com/FortAwesome/Font-Awesome/issues/8317
Other icons works fine.

**Comment by tagliala** [comment]
Please check the troubleshooting guidelines checklist

**Comment by nicolasbadia** [comment]
I already checked them. I'm using the latest font awesome version (not cached), with the latest safari (which has no extension installed)...
But after digging a bit more, I found out that it is the woff2 version of the font which fail for theses icons. the woff version works fine.
