### ISSUE TITLE
Request for a gas icon

### ISSUE THREAD

**Issue by rlam3** [FortAwesome/Font-Awesome#8554]
Request for a gas icon

http://www.printpack.com/wp-content/uploads/2014/08/123rf_24164135_greenhouse-gas-icon.png

http://www.rolls-royce.com/~/media/Images/R/Rolls-Royce/icons/kpi-icons/kpi-item/icons/greenhouse-gas-emissions.png?h=155&la=en&w=218

**Comment by tagliala** [comment]
We need a better title for this request

**Comment by sensibleworld** [comment]
Hey @rlam3. I'm closing this issue, as it doesn't fit our current request guidelines. If this icon is still needed, feel free to open another icon request. https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md
