### ISSUE TITLE
Icon request: Icon- Bedford City Seal

### ISSUE THREAD

**Issue by DesktopWebSpecialist** [FortAwesome/Font-Awesome#8555]
![bedfordcityseal](https://cloud.githubusercontent.com/assets/17209046/13022784/8ab43134-d1b1-11e5-8b1d-e169c4b2d367.png)

![bedfordcityseal](https://cloud.githubusercontent.com/assets/17209046/13022794/90c91e86-d1b1-11e5-98ca-192771112ef0.png)

**Comment by tagliala** [comment]
Sorry, I'm going to temporarily close this one.

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by tagliala** [comment]
Confirm: city seals are out of scope

**Comment by DesktopWebSpecialist** [comment]
It's not our City Seal. It was re-imaged for this purpose. I can send our
seal.

**Comment by davegandy** [comment]
Yep. Definitely out of scope. Give Fort Awesome a shot to customize your own Font Awesome build.

**Comment by DesktopWebSpecialist** [comment]
Interesting, this is not out City Seal- it was rendered for our Open Data website. Its under creative Commons- we created it to be shared etc.

**Comment by DesktopWebSpecialist** [comment]
How do I go about getting it in?

**Comment by tagliala** [comment]
@DesktopWebSpecialist  https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by DesktopWebSpecialist** [comment]
The custom way is almost instantaneous? I need this is like by Wednesday of
next week.

**Comment by tagliala** [comment]
@DesktopWebSpecialist did you read the wiki? could you please take a deeper look at the wiki page and tell me if something is not clear?

**Comment by DesktopWebSpecialist** [comment]
I did, read it multiple times 😳 just getting clarification. 🤔

**Comment by tagliala** [comment]
As soon as you update a well formed .svg file of the icon you need in the online tool of your choice (let's say icomoon), the download is instantaneous

**Comment by DesktopWebSpecialist** [comment]
Super! Thanks for your help & consideration. I considered doing this first
but that "submission " may have been both more reliable & quicker. Again
Thank You! ☺️

**Comment by tagliala** [comment]
You're welcome. Feel free to post if you need more info
