### ISSUE TITLE
Icon request: icon-virus

### ISSUE THREAD

**Issue by thw1st** [FortAwesome/Font-Awesome#8557]
Right now there is only a bug-icon. And although a virus-icon in many might be used similar like the bug-icon, a little virus-icon means something else to me. And a virus-icon would really complete the existing set of medical-icons. And you could perfectly stack it with the already existing fa-ban-icon. And i'am sure there are also other good reasons.

So? What do you think? It's super hard to make - right? Cause it's usually that small. But let's be honest: You already made such great icons, i am sure you can make my request come true ;) thank a lot so far!

**Comment by nitmir** [comment]
+1

**Comment by tagliala** [comment]
could you please post a single color example suitable for 14px icon size?

**Comment by sensibleworld** [comment]
Here's a current icon that might fit the bill: https://fontawesome.com/icons/disease?style=solid
