### ISSUE TITLE
Icon request: Uranium

### ISSUE THREAD

**Issue by BartHimitsu** [FortAwesome/Font-Awesome#8564]
Evrybody knows that yellow logo representing uranium, like some of this: https://www.google.co.uk/search?q=uran+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjlvvSB9_bKAhWKtRQKHbz6CSoQ_AUIBygB&biw=1366&bih=635

**Comment by tagliala** [comment]
what is uranium? website? brand? product? could you please provide more information?

**Comment by IdolwSzutrab7** [comment]
Uranium? Element of uranium? Uran? I don't know how to explain it. Everybody knows that biohazard symbol.

**Comment by tagliala** [comment]
a proper image would explain better than 1000 words :)

is this a duplicate of #4470 ?

**Comment by IdolwSzutrab7** [comment]
Yes.

**Comment by giuseb** [comment]
That is NOT a symbol for uranium. Rather, it warns about *any* type of radioactivity.

**Comment by tagliala** [comment]
> Yes.

Duplicate of #4470
