### ISSUE TITLE
fa fa-think-cloud

### ISSUE THREAD

**Issue by kklaase** [FortAwesome/Font-Awesome#8567]
I can't seem to find any icons to show thinking. I would like to use a think cloud. Anyone else?

**Comment by kyleish** [comment]
Could you not just stack the comment and cloud icons?

``<span class="fa-stack fa-lg">
  <i class="fa fa-comment fa-stack-2x"></i>
  <i class="fa fa-cloud fa-stack-2x"></i>
</span>``

**Comment by aethior** [comment]
Hiu @kklaase,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/thought-bubble

Regards.

cc/ @tagliala
