### ISSUE TITLE
FontAwesome.otf Problems

### ISSUE THREAD

**Issue by manattweb** [FortAwesome/Font-Awesome#8569]
The 4.5.0 version of the OTF desktop font could not be installed and when checked with Font Book, it states there are serious issues with the font and recommends not to use. The 4.4.0 version installs fine without issues.

**Comment by tagliala** [comment]
4.6.3 on macOS Sierra installs and validates just fine but we are having other issues.

![image](https://cloud.githubusercontent.com/assets/556268/19398930/37c21054-924f-11e6-88ca-e0af4cbc3ad6.png)
