### ISSUE TITLE
Icon request: icon-namic

### ISSUE THREAD

**Issue by Namic-Clothing** [FortAwesome/Font-Awesome#8579]
Would like to use this icon for our website.
![n logo](https://cloud.githubusercontent.com/assets/17251412/13049425/c3c92aa8-d3e4-11e5-9da6-11055e916ce4.png)

**Comment by tagliala** [comment]
is this a brand? Could you please provide more information?

**Comment by Namic-Clothing** [comment]
Hi Geremia

We are a clothing brand recently starting out, we use font awesome on our website and would like to include our logo for ease of use.

Regards,

Namic

**Comment by tagliala** [comment]
Hi,

I hope you will succeed with your clothing brand but you should use a custom build if you need your logo at the moment: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
