### ISSUE TITLE
Icon Request: fa-skype

### ISSUE THREAD

**Issue by wgp3000** [FortAwesome/Font-Awesome#8582]

**Comment by carmona** [comment]
http://fontawesome.io/icon/skype/ it's there since v3.2, make sure you are using an updated version of the lib or describe your request if it's something else.

**Comment by tagliala** [comment]
@carmona thanks

closing here

Troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
