### ISSUE TITLE
Icon request: icon-clean

### ISSUE THREAD

**Issue by felipePrandini** [FortAwesome/Font-Awesome#8583]
I plan using it on a button of a webiste that cleans a searching filter. An icon of a broom or something like that.
![vassoura2](https://cloud.githubusercontent.com/assets/17257688/13058065/a53faea4-d407-11e5-8815-18146bdddc92.png)
![vassoura](https://cloud.githubusercontent.com/assets/17257688/13058064/a53f64da-d407-11e5-98a7-66367cf546bd.png)

**Comment by tagliala** [comment]
duplicate of #239 , please +1 that request

closing here
