### ISSUE TITLE
Icon request: icon-exchange-v

### ISSUE THREAD

**Issue by abdlkrmdlgr** [FortAwesome/Font-Awesome#8586]
hi, anybody see vertical exchange icons? i saw only one exchange icon. its horizontal.

**Comment by tagliala** [comment]
Keep in mind that you can use `fa-rotate-90` https://jsfiddle.net/tagliala/syduuue9/19/

**Comment by abdlkrmdlgr** [comment]
very nice!, but my project is vaadin project on java. Vaadin's font awesome plugin does not support rotate :(

**Comment by tagliala** [comment]
This icon has been implemented as [fa-sort-alt](https://fontawesome.com/v5.15/icons/sort-alt?style=solid) and is available in FA Pro
