### ISSUE TITLE
Bug: reddit-alien icon is in the font files

### ISSUE THREAD

**Issue by KyorCode** [FortAwesome/Font-Awesome#8589]
After numerous attempts to use the fa-reddit-alien icon, I started looking into the font files and notices it just isn't there.

I'm on version 4.5.

Kind regards.

**Comment by tagliala** [comment]
Sorry, I didn't get this issue.

reddit-alien has no issues: https://jsfiddle.net/tagliala/syduuue9/20/

Please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
