### ISSUE TITLE
Icon request: icon-offer

### ISSUE THREAD

**Issue by bgilman** [FortAwesome/Font-Awesome#859]
looking for something like an open hand, as in 'offering up something', similar to:
http://findicons.com/icon/470623/hand_share?id=476026

**Comment by railsfactory-kumaresan** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
+1

**Comment by aethior** [comment]
Hi @bgilman!

This icon was added in v5.0.9.
Check https://fontawesome.com/v5.15/icons/hand-holding

cc/ @tagliala

**Comment by aethior** [comment]
@tagliala check here please.

**Comment by aethior** [comment]
@tagliala I think you can close here. :)

**Comment by aethior** [comment]
@tagliala I think you can close here. :)
