### ISSUE TITLE
Webpack bug building font awesome scss incorrectly

### ISSUE THREAD

**Issue by PeteJodo** [FortAwesome/Font-Awesome#8590]
I posted an issue in the webpack repo [here](https://github.com/webpack/webpack/issues/2037) but I figured I'd leave this here so everyone knows about it

Below is a copy of the bug I filed so you don't have to click through
## 

This may actually be a bug for uglifyjs but I figured I'd post the issue first because I'm not sure.

We're loading styles into our js files (so `require('some-scss.scss')`) and within a scss file we use a font-awesome mixin that's defined [here](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_mixins.scss#L6). What ends up being compiled looks like `font:normal normal normal 14px/\ 1 FontAwesome;` which is incorrect syntax obviously. I tracked it down to our call to `webpack.optimize.UglifyJsPlugin` that's causing it. It only appeared somewhat recently (within the last 2 months).

Here are the options I pass into the plugin:

``` javascript
{
    compress: {
        drop_console: true, // eslint-disable-line
        drop_debugger: true, // eslint-disable-line
        warnings: false
    },
    mangle: false
}
```

Any ideas?

**Comment by tagliala** [comment]
Hi!

Apologies for the "late" reply 😅 

In those 4 years a lot of things have changed, and we have official node packages that should improve integration with JS module bundlers like webpack

I suppose this has been fixed, but feel free to open new issues
