### ISSUE TITLE
 Icon request: icon-elephant, icon-gorilla and icon-big-cat

### ISSUE THREAD

**Issue by palmernet** [FortAwesome/Font-Awesome#8591]
Hi

We are exploring using Font-Awesome for icons in an applications used widely by the conservation community.  We'd need a few additional icons created - can someone assist with creating 3 icons for key endangered species/species groups: elephant, gorilla and big cats?

**Comment by tagliala** [comment]
Hi,

please split this request in three separate requests

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by palmernet** [comment]
Separated into 3 requests

**Comment by tagliala** [comment]
thanks
