### ISSUE TITLE
Icon request: icon-vacuum

### ISSUE THREAD

**Issue by Roland80** [FortAwesome/Font-Awesome#8597]
I needed a vacuum cleaner icon for "cleaning up", but couldn't find one, so I made one. The file I made (AI) works for now, but I'd like to see a vacuum cleaner (and maybe some other related objects) added to FontAwesome...
![vacuum-cleaner](https://cloud.githubusercontent.com/assets/17293711/13110309/7bc1a4b4-d57f-11e5-99fd-121aa88aed47.jpg)

**Comment by ryankane** [comment]
Most icons, that I have seen, portray a broom to represent the act of "cleaning up."

## fa-clean

![fa-clean](http://i.imgur.com/HelhtAx.png)

**Comment by tagliala** [comment]
fa clean: #239

**Comment by alouks** [comment]
This issue should be closed.

**Comment by timtjtim** [comment]
This suggestion sucks...

**Comment by alouks** [comment]
@timtjtim Its a duplicate. There is already a long running issue: Issue #239

**Comment by timtjtim** [comment]
I was actually making a joke. But it’s not a duplicate, this one is asking for a vacuum cleaner. Not a generic clean icon.

**Comment by RafeSacks** [comment]
This should be reopened. I was looking for something like this for "cleaning equipment". Brooms aren't "equipment enough" for that.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=vacuum
