### ISSUE TITLE
Icon Request: fa-sum (Greek uc sigma)

### ISSUE THREAD

**Issue by ufoczek** [FortAwesome/Font-Awesome#8598]
It would be great to have a new icon. Use cases: sum everything (tables, etc).

https://en.wikipedia.org/wiki/File:Greek_uc_sigma.svg

**Comment by tagliala** [comment]
duplicate of #4834 , please +1 that request

closing here

**Comment by peterdeak** [comment]
.fa-sum:before {
    content: "\03a3";
    font-family: sans-serif;
}

**Comment by canperk** [comment]
i agree with @peterdeak
