### ISSUE TITLE
fa-calendar-plus-o is not working

### ISSUE THREAD

**Issue by RecycQuebec** [FortAwesome/Font-Awesome#8604]
Hi,
fa-calendar-plus-o is not working in 4.5.0 FA version.
Firefox last update
Chrome last update
IE 11

**Comment by tagliala** [comment]
of course I can't confirm

https://jsfiddle.net/tagliala/syduuue9/31/

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Closing here
