### ISSUE TITLE
fa-usb not working...

### ISSUE THREAD

**Issue by CasaTechMitch** [FortAwesome/Font-Awesome#8607]
Was trying to use the fa-usb icon but was unable to get it to show up. Do I need to define a class for it specifically?

**Comment by tagliala** [comment]
Of course I can't confirm: https://jsfiddle.net/tagliala/syduuue9/32/

Please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
