### ISSUE TITLE
Icon Request: Brazilian NFe

### ISSUE THREAD

**Issue by cleciusjm** [FortAwesome/Font-Awesome#8608]
Hi all, 
In Brazil we've some fiscal requirements as eletronic documents, the icons of this eletronic documents are
NFe - Nota Fiscal Eletrônica - fa-nfe
![nf-icon](https://cloud.githubusercontent.com/assets/3534690/13164622/d748db8a-d69d-11e5-84d6-c68aff25c4c8.png)
NFCe - Nota Fiscal de Consumidor Eletrônica - fa-nfce
![nfc-icon](https://cloud.githubusercontent.com/assets/3534690/13164613/be801e56-d69d-11e5-8c76-4e094357e84b.png)
CT-e - Conhecimento de Transporte Eletrônico - fa-cte
![cte-icon](https://cloud.githubusercontent.com/assets/3534690/13164640/f3adf8c8-d69d-11e5-92c8-f895647bb16f.png)
CC-e - Carta de Correção Eletrônica - fa-cce
![cc-e](https://cloud.githubusercontent.com/assets/3534690/13164645/ffc09cec-d69d-11e5-8498-d54e4d92ace9.jpg)

**Comment by israelandrade** [comment]
+1

**Comment by andreluiz1013** [comment]
+1

**Comment by tagliala** [comment]
Sorry, I have to close this request, those icons are out of scope

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
