### ISSUE TITLE
Icon Request: icon-quora

### ISSUE THREAD

**Issue by alexandruserbu** [FortAwesome/Font-Awesome#8609]
Hi, I would like an icon for quora. 

I need it for my blog.

Thank you.
![1455879014_q-1](https://cloud.githubusercontent.com/assets/17329340/13166823/2ebdcc4a-d6d5-11e5-9c16-4eab818b73c2.png)

**Comment by tagliala** [comment]
duplicate of #510 , please +1 that request

closing here
