### ISSUE TITLE
Icon Request: update fa-odnoklassniki and fa-odnoklassniki-square

### ISSUE THREAD

**Issue by fromanywhere** [FortAwesome/Font-Awesome#8610]
Hello, current logo version (https://github.com/FortAwesome/Font-Awesome/issues/1685) is incorrect — "thin" variant is implemented. Correct version placed at https://v.ok.ru/logo.html. You can detect difference between logos in attachment:
![odnoklassniki_0](https://cloud.githubusercontent.com/assets/1042969/13176712/4a992356-d725-11e5-95d5-b7c85787a5cd.jpg)
![ok_logo_sign_white 2x](https://cloud.githubusercontent.com/assets/1042969/13176715/4f0fdab0-d725-11e5-8653-f8bebfbd5685.jpg)

Please, update our logo according company guideline :)

**Comment by DmitryMakhnev** [comment]
+

**Comment by mishcherin** [comment]
it's high time :+1:

**Comment by tagliala** [comment]
Looks fixed to me
