### ISSUE TITLE
icon request: star-half-reverse

### ISSUE THREAD

**Issue by luckyleohd** [FortAwesome/Font-Awesome#8611]
I think it would be useful to cover some text in 5 stars, having two and a half star on the left side and a reversed half star plus two stars on the right side.

**Comment by tagliala** [comment]
Please consider using `fa-flip-horizontal`
https://jsfiddle.net/tagliala/syduuue9/34/

**Comment by luckyleohd** [comment]
But I don't want to use it in HTML, but in Javascript. Is that possible? I didn't find anything on the internet.

**Comment by luckyleohd** [comment]
I am using the app 'Droidscript', if that is important.
