### ISSUE TITLE
Facebook's official icon

### ISSUE THREAD

**Issue by jaxgarry** [FortAwesome/Font-Awesome#8613]
Hello, 
 When trying to use http://fontawesome.io/icon/facebook-official/ as <i class="fa fa-facebook-official"></i> shown on the website, I only get a blank space where the icon is trying to load but fails. However, if I use <i class="fa fa-facebook-square"></i> or <i class="fa fa-facebookl"></i> those icons appear as they should. Problem being is design is requesting that I use <i class="fa fa-facebook-official"></i>. Is this a glitch or is there something special I need to include when using this specific icon? Thank you in advance! 

Jax

**Comment by tagliala** [comment]
Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay attention to all points, in particular pay attention to point 4
