### ISSUE TITLE
Icon request: fa-contactless-symbol & fa-contactless-indicator

### ISSUE THREAD

**Issue by vHeemstra** [FortAwesome/Font-Awesome#8617]
As described at: [http://www.emvco.com/best_practices.aspx?id=117](http://www.emvco.com/best_practices.aspx?id=117)

The indicator is for use on tokens, cards, etc that use NFC (or only a subset of it), the symbol is used on the physical place where these tokens,cards, etc are meant to be held in order to read them.

EDIT: According to [http://www.gsma.com/digitalcommerce/news-information-resources/nfc-contactless-marks](http://www.gsma.com/digitalcommerce/news-information-resources/nfc-contactless-marks), the symbol is only used when contactless payment is concerned, otherwise the indicator is used.

**Comment by 2ndGAB** [comment]
I think this [one](https://www.brandsoftheworld.com/logo/nfc-6) is better

**Comment by tagliala** [comment]
let's use #9887
