### ISSUE TITLE
Icon request: icon-whm

### ISSUE THREAD

**Issue by tufu9441** [FortAwesome/Font-Awesome#8619]
I am requesting this new icon for the usage of some brands or people's names which include the letter W, H and M. Such as [WebHost Manager](https://documentation.cpanel.net/display/ALD/WHM+Home+Interface), [WHM TV](http://www.whm-tv.com) and [White House Marketing](http://whitehousemarketinginc.com).

![logo_s](https://cloud.githubusercontent.com/assets/6790361/13201662/6dc1f2e4-d8b6-11e5-9ca6-5eabc78b89a3.png)

Here is a download link of the .svg file: https://www.dropbox.com/s/e014j8voybfzv9n/icon-whm.svg?dl=0

**Comment by tagliala** [comment]
Sorry, I didn't get this request

There are three brands using the same logo? Could you please clarify?

I can't see that logo in any of the three websites

**Comment by tufu9441** [comment]
I am so sorry to confuse you, actually I desgined this icon by myself and mainly
want to use it on a personal purpose.

On 周日, 2月 21, 2016 at 23:18, Geremia Taglialatela <notifications@github.com>
wrote:
Sorry, I didn't get this request

There are three brands using the same logo? Could you please clarify?

I can't see that logo in any of the three websites

—
Reply to this email directly or view it on GitHub
[https://github.com/FortAwesome/Font-Awesome/issues/8619#issuecomment-186842010] .[https://github.com/notifications/beacon/AGec2Y83v4RjN0vOH_DVIS7fvU1hXJfrks5pmcy9gaJpZM4He5Bf.gif]

**Comment by tagliala** [comment]
> I am so sorry to confuse you, actually I desgined this icon by myself and mainly
want to use it on a personal purpose.

No problem.

Sorry, I haev to close this request. Please consider a custom build of fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
