### ISSUE TITLE
Icon inside <h1> does not work on default Android browser

### ISSUE THREAD

**Issue by Cervajz** [FortAwesome/Font-Awesome#862]
Hi :o)

I just noticed that FontAwesome used inside H1 does not work on the default Android browser. There is just empty space instead of image. Other browsers like Chrome or Safari on iOS works well. See pictures

Code I used:

``` HTML
<h1><i class="icon-th-large"></i></h1>
```

Default browser:

![android_default](https://f.cloud.github.com/assets/344227/272561/b080c678-9007-11e2-8641-b0f8dcd5e175.png)

Chrome:

![android_chrome](https://f.cloud.github.com/assets/344227/272562/b3ee033e-9007-11e2-9087-90914a841b17.png)

My configuration:

Android JellyBean 4.2.2
Tested on ICS - behaves same

**Comment by keyneosoft** [comment]
Bug non reproduit, j'ai peut être trouvé une solution mais je ne peux pas tester le correctif
