### ISSUE TITLE
Strange bug with the Google+ Font

### ISSUE THREAD

**Issue by TheHungryGeek** [FortAwesome/Font-Awesome#8620]
So my site has been using FontAwesome's Google+ fonts for months with no problems.

Suddenly, the G+ font gets replaced with the small caps version of the font (included CSS from dev tools):

![3](https://cloud.githubusercontent.com/assets/16078559/13204280/fc39026a-d906-11e5-847c-a8f4df405e18.png)

Any idea what happened? I did not recall changing anything that should affect this. The original Font is supposed to be the capital G+.

**Comment by tagliala** [comment]
Please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Pay particular attention to point 4

closing here

**Comment by TheHungryGeek** [comment]
Cheers, thanks for the quick response. Dequeued the offending stylesheet :)
