### ISSUE TITLE
icon request: icon-clammr

### ISSUE THREAD

**Issue by Clammr14** [FortAwesome/Font-Awesome#8621]
Hi, we one of our the users of our audio sharing service, Clammr, requested that our icon be made available for Font Awesome so that she can use it on her web site (in order to link to hear Clammr profile page) and have a consistent look with other icons she has on her site (which are from Font Awesome). We'd love to support her request. Would you please consider creating a Font Awesome icon of our logo? Attached is our current icon + our logo.

![clammrsquarevector](https://cloud.githubusercontent.com/assets/6887499/13207538/9d99dae6-d8dd-11e5-8006-06b7d3f0d49f.png)
![clammrvector](https://cloud.githubusercontent.com/assets/6887499/13207539/9d9a17fe-d8dd-11e5-9df1-73fdee4771a5.png)

**Comment by ThatPascale** [comment]
yes yes yes please.

**Comment by aethior** [comment]
>**Clammr Shut-Down Notice**
It’s time for our team to move on to new adventures. We write to inform you that we will be shutting down the Clammr service at 11:59pm ET on 2 July 2017. ([more info](https://medium.com/@ClammrApp/clammr-shut-down-notice-66516381a28a))

cc/ @tagliala
