### ISSUE TITLE
Icon Request: fa-hoaxit

### ISSUE THREAD

**Issue by hoaxit** [FortAwesome/Font-Awesome#8625]
![tmp_6060-viva_bufala1559254579](https://cloud.githubusercontent.com/assets/17406740/13217832/adca4ae4-d965-11e5-8dc4-9ad0dc47426d.jpg)

Thank You ;-)

**Comment by tagliala** [comment]
Could you please post a single color example suitable for 14px icon size and use case?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
