### ISSUE TITLE
Wrong Horizontal centering / Unneeded side space

### ISSUE THREAD

**Issue by sergiu-radu** [FortAwesome/Font-Awesome#8628]
Hello,
Some icons are not centered horizontally right, is there a way to fix that?
![fa-balance-scale__font_awesome_icons](https://cloud.githubusercontent.com/assets/8998558/13225653/6681f520-d996-11e5-9a30-b8df44b636f1.png)

**Comment by tagliala** [comment]
I think there is an issue with this specific icon

may refer to #5991

**Comment by Creative-Dreams** [comment]
@tagliala I noticed this problem with "space" on the left not only for this icon...
Is there a way to fix them all from one shot?

**Comment by tagliala** [comment]
please help me identifying all icons that might have this issue.

I think this also affects:
* bank
* bluetooth
* calendar-*-o https://jsfiddle.net/tagliala/syduuue9/35/
* hand-paper-o
* hand-pointer-o
* hand-spock-o
* television

**Comment by Creative-Dreams** [comment]
So, I found ~161 bugs with unneeded space so far.
Some icons have to much space on the left or right sides some of them on both.
- 20 icons with space on left side
- 75 icons with space on right side
- 76 icons with space on both sides

Here I made a [demo](http://creativethemes.com/playground/fa/index.html) with all icons, I increased the icon size and gave a `background-color` to the `:before` element so you could see the space better.

Also I assigned an indicator to those icons that should be fixed.

**Comment by Creative-Dreams** [comment]
@tagliala any updates on this?

**Comment by tagliala** [comment]
@Creative-Dreams added this issue to 5.0.0 milestone so Dave will eventually take a look before releasing a new version. Sorry but I can't tell anything else

**Comment by Creative-Dreams** [comment]
@tagliala if you want I can help you with editing each icon to speed up things.
I also found that there are some icons with unneeded space on top and bottom...

**Comment by tagliala** [comment]
@Creative-Dreams thanks but I'm not in charge of making icons and afaik PR containing edits to the otf file will not be merged. You could try to get in touch with @davegandy

**Comment by Creative-Dreams** [comment]
@tagliala thanks for letting me know.
@davegandy what do you think about this?

**Comment by tagliala** [comment]
@sergiu-radu sorry for the extremely late reply but there were no updates until a few days ago, when FA5 has been released.

Most of these issues have been addressed in FA 5.0.0 but there are still icons suffering from unneeded spaces (~ 16 out of 2177).

We are going to fix that internally and use #11912 as a new reference for spacing issues

Thanks for your patience

**Comment by sergiu-radu** [comment]
Hey @tagliala, great news! Thanks!
