### ISSUE TITLE
fa-television: Adjust placement when stacked

### ISSUE THREAD

**Issue by syeo66** [FortAwesome/Font-Awesome#8631]
It seems fa-television is a bit off center when stacked.
![screenshot](https://cloud.githubusercontent.com/assets/1178021/13245051/a64f61dc-da0a-11e5-8a7a-a6e15dcb886b.png)

**Comment by syeo66** [comment]
Oh, I just realized this has been mentioned in #8628

**Comment by tagliala** [comment]
let's continue on #8626 

closing here

**Comment by syeo66** [comment]
#8626 ? Typo, I guess

**Comment by tagliala** [comment]
@syeo66 sure, fixed. #8628
