### ISSUE TITLE
Icon request: icon - bloglovin

### ISSUE THREAD

**Issue by kristinmaz** [FortAwesome/Font-Awesome#8632]
I would like to add the bloglovin social media icon to the navigation menu of my wordpress blog

![bloglovin](https://cloud.githubusercontent.com/assets/17430102/13251872/b97a4d42-da2a-11e5-9cb5-fc9f6eb18c99.JPG)

**Comment by tagliala** [comment]
Duplicate of #2334, please +1 that request

closing here
