### ISSUE TITLE
Icon Request: fa-lamp

### ISSUE THREAD

**Issue by elprincipe9** [FortAwesome/Font-Awesome#8635]
Hello! Great job on all these FaFonts! They are great!!!
I'm a webmaster and I often need a lamp font awesome to convey furniture or light, etc.I use the lightbulb which I really like because it has the little reflection of light on the top (very nice touch) but now I am currently building a website for a lampshade manufacturer so I REALLY would like to see a fa-lamp

anyways.. enough compliments for one email... :)

thanks for you time!!

Diego
<img width="235" alt="fa-fa-lamp" src="https://cloud.githubusercontent.com/assets/17434215/13257986/24802c4e-da1f-11e5-973a-abb2fd18fea7.png">

**Comment by kpingel** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/lamp?style=solid
