### ISSUE TITLE
Icon request: fa-coin, fa-coins

### ISSUE THREAD

**Issue by Cow258** [FortAwesome/Font-Awesome#8636]
fa-coin -> single coin
fa-coins -> many coins

![image](https://cloud.githubusercontent.com/assets/14261588/13260574/0ef6f218-da97-11e5-9ba0-d9da01616fea.png)
![image](https://cloud.githubusercontent.com/assets/14261588/13260580/1446e50c-da97-11e5-8832-315a8cbff148.png)
![image](https://cloud.githubusercontent.com/assets/14261588/13260592/20947bbc-da97-11e5-97a5-4871da4279fc.png)
![image](https://cloud.githubusercontent.com/assets/14261588/13260597/262236e6-da97-11e5-8ec5-60c7ee625409.png)
![image](https://cloud.githubusercontent.com/assets/14261588/13260608/2e09900c-da97-11e5-81bb-927997be6b3d.png)

**Comment by tagliala** [comment]
coins: #1400 
coin: #4350

please +1 the above requests

**Comment by fernandobonfimandrade** [comment]
+1
