### ISSUE TITLE
Icon request: fa-firehose

### ISSUE THREAD

**Issue by rinaldo-ferreira** [FortAwesome/Font-Awesome#8637]
I would like to request an icon for a fire hose.

Thanks

**Comment by AlexanderPilhar** [comment]
+1

**Comment by aethior** [comment]
Hi @rinaldo-ferreira,

[**fa-hose**](https://fontawesome.com/icons/hose) and [**fa-hose-reel**](https://fontawesome.com/icons/hose-reel) icons were added in v6.0.0.

Regards.

cc/ @tagliala
