### ISSUE TITLE
Icon Request: icon-kitware, icon-paraview, icon-paraviewweb

### ISSUE THREAD

**Issue by SteveJordanKW** [FortAwesome/Font-Awesome#8645]
We've been using Font-Awesome for quite some time within our OpenSource scientific tools. While building web applications for scientific simulation and visualization (ParaViewWeb, ArcticViewer, HPCCloud...) we sometime run short in type of icons that could match our needs.

Hence today, we thought we should try to contribute those we commonly use within our application. 

On our open source applications we tend to mention where the technology comes from.
![kitware](https://cloud.githubusercontent.com/assets/1433903/13269101/14924058-da54-11e5-86c9-3c783e067b0d.png)
![paraview](https://cloud.githubusercontent.com/assets/1433903/13269103/14928be4-da54-11e5-9309-6d31b31f6a8f.png)
![paraviewweb](https://cloud.githubusercontent.com/assets/1433903/13269102/1492af98-da54-11e5-8a41-a7c5330b22e0.png)

**Comment by tagliala** [comment]
Please split this request into two/three individual requests. You can also edit this one

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Please also add more information about those logos (like website)

**Comment by jourdain** [comment]
I've split it into #8653 and #8652

**Comment by tagliala** [comment]
@jourdain thanks
