### ISSUE TITLE
Icon request: gotop

### ISSUE THREAD

**Issue by Heming1way** [FortAwesome/Font-Awesome#8655]
I apologize if this issue has already been opened by someone else and I failed to find out about it. In fact I was very surprised when searching about twenty or thirty issue pages and NOT finding it. After all, most websites display some go-top arrow or whatever, and I was surprised that FA's choice is a little narrow for this purpose.
At the moment I'm using chevron-up, but what I find much more appropriate and self-evident is the icon that comes up on [http://www.jqueryscript.net/](http://www.jqueryscript.net/). Thank you for your great work!

**Comment by tagliala** [comment]
That arrow does not match style of other arrows available in the set

You could consider: http://fontawesome.io/icon/arrow-circle-up/ or http://fontawesome.io/icon/arrow-up/

or just a couple of line of custom css if you want the top line: https://jsfiddle.net/tagliala/syduuue9/37/

I'm going to close here

**Comment by Heming1way** [comment]
Hi and thank you so much for your personal response.
Your css lines provide me with exactly what I was looking for but would never have been able to create myself.
THANK YOU!

Am 26.02.2016 um 11:07 schrieb Geremia Taglialatela:

**Comment by Heming1way** [comment]
Ho sparato troppo presto ... il tuo nome mi ha spinto di ricercare un po', e così ho trovato che sei veramente italiano e inoltre abiti nella nostra zona preferita - Napoli e il sud.
Perciò potrebbe interessarti che il sito a cui (allo quale??) hai contribuito è anche dedicato alla letteratura italiana. Mia moglie ed io scriviamo recensioni di libri e film con un accento sulla cultura italiana. Purtroppo le case editrici italiane e gli agenzie letterarie sono inaccessibili come fortezze ...

Ecco un'introduzione al nostro sito in lingua italiana:
     http://www.buecherrezensionen.org/italienisch.htm
Ecco un elenco di libri da leggere quando si viaggia nel sud:
     http://www.buecherrezensionen.org/tipps-buecher-sueditalien.htm
Ed ecco il sito: http://www.buecherrezensionen.org/
Il gotop arrow ci sarà stasera ...

Cari saluti, e grazie di nuovo per il tuo buon lavoro
Alex


Am 26.02.2016 um 11:07 schrieb Geremia Taglialatela:

**Comment by tagliala** [comment]
Ciao, scrivimi pure a tagliala.dev@gmail.com

I will soon delete the above posts because they are off topic :)
