### ISSUE TITLE
Icon request: icon-loop and icon-playlist

### ISSUE THREAD

**Issue by surjithctly** [FortAwesome/Font-Awesome#8659]
Please add these icons related to Audio Player.

`icon-loop` and  `icon-playlist`

**Comment by surjithctly** [comment]
Reference:

Loop Icon | Playlist Icon
------------ | -------------
![Loop Icon](http://image005.flaticon.com/1/svg/1/1584.svg)  | ![Playlist Icon](http://image005.flaticon.com/1/svg/109/109211.svg)

**Comment by tagliala** [comment]
loop: http://fontawesome.io/icon/retweet/ or +1 #33
playlist: #639 or #7740, please +1 those requests

all dups

closing here

**Comment by surjithctly** [comment]
Thanks.. I did a search, but didn't work.

However, Any plans to really make those icons? I can see that its already mentioned in 2015, and one year gone, no update?

Will this really going to happen?

Thanks a lot

~Surjith
