### ISSUE TITLE
Icon request: hipchat

### ISSUE THREAD

**Issue by Jameskmonger** [FortAwesome/Font-Awesome#8660]
It would be good to have an icon `hipchat` for the [Atlassian HipChat IM application](http://hipchat.com/) included with Font Awesome.

**Comment by AceMedia** [comment]
Seconded. This would be fantastic. :)

**Comment by martinalderson** [comment]
+1

**Comment by mikepultz** [comment]
+1

**Comment by amalfra** [comment]
+1

**Comment by justshiv** [comment]
+1 please!

**Comment by adelriosantiago** [comment]
+1 yes please!

**Comment by CmdrSharp** [comment]
+1 - quite curious that this wasn't added when Slack is!

**Comment by Dgigiu** [comment]
+1. This would be great! 

svg code for the icon :P sort of joking, but I can help with that if you need! 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 164.48 153.67"><defs><style>.a{fill:#205081;}</style></defs><title>hipchat_rgb_blue</title><path class="a" d="M139.81,183.55a3.28,3.28,0,0,0-3.27-3.27,3.22,3.22,0,0,0-2.17.83c-8.28,7.44-22.38,14-39.44,14.07H94.86a62.68,62.68,0,0,1-39.44-14.07,4.08,4.08,0,0,0-2.24-.77A3.33,3.33,0,0,0,50,184c0,1.46,1,2.68,1.87,4,4.89,7.34,20.05,19.8,42.87,19.8h0.36c22.82,0,38-12.46,42.87-19.8C138.78,186.65,139.81,185,139.81,183.55Z" transform="translate(-12.65 -96.75)"/><path class="a" d="M162.49,240.75a30.19,30.19,0,0,1-13.85-16.57,3,3,0,0,1,1.1-3.61c16.81-13,27.38-31.86,27.38-52.87,0-39.18-36.82-70.94-82.23-70.94S12.65,128.52,12.65,167.7s36.82,71,82.24,71a95.17,95.17,0,0,0,17.3-1.57,4.65,4.65,0,0,1,3.39.63c11.26,6.91,28,12.7,42.71,12.7,4.74,0,6.56-3,6.56-5.74A4.44,4.44,0,0,0,162.49,240.75Zm-22-6.9a1.58,1.58,0,0,1,.4,1,0.91,0.91,0,0,1-1,.8c-4.12,0-16.81-6.84-23.5-12.48a4.43,4.43,0,0,0-4-.66,82,82,0,0,1-17.46,1.87c-37.8,0-68.45-25.3-68.45-56.52s30.65-56.5,68.45-56.5,68.45,25.3,68.45,56.5c0,18.63-10.91,35.15-27.75,45.45a4.49,4.49,0,0,0-2.32,3.6C133.27,220.19,136.39,228.42,140.48,233.85Z" transform="translate(-12.65 -96.75)"/></svg>`

**Comment by diogofcosta** [comment]
+1 please!

**Comment by aethior** [comment]
>In July 2018 announcement, Atlassian announced a partnership with Slack under which Slack would acquire the codebase and related IP assets of HipChat and Stride from Atlassian. Following this, HipChat and Stride customers were migrated to the Slack group collaboration platform in a transition that was completed by February 2019. ([more info](https://en.wikipedia.org/wiki/HipChat))

cc/ @tagliala
