### ISSUE TITLE
Icon request: Ustream.tv

### ISSUE THREAD

**Issue by xyfantis** [FortAwesome/Font-Awesome#8661]
A nice addition to the social section

http://www.ustream.tv/

IMHO

**Comment by kevinmcmilian** [comment]
Seconded!

**Comment by aethior** [comment]
Ustream was adquired by IBM in 2016 and now is know as IBM Cloud Video.

>IBM today announced it has acquired Ustream, Inc., a provider of cloud-based live video streaming services. The move will extend the IBM Cloud platform to help enterprise clients unlock the value of video, a rapidly-evolving digital media and data asset. Financial terms were not disclosed. ([more info](https://www.ibm.com/blogs/cloud-archive/2016/01/ibm-acquires-ustream/))

**Comment by aethior** [comment]
Ustream was adquired by IBM in 2016 and now is known as IBM Cloud Video.

>IBM today announced it has acquired Ustream, Inc., a provider of cloud-based live video streaming services. The move will extend the IBM Cloud platform to help enterprise clients unlock the value of video, a rapidly-evolving digital media and data asset. Financial terms were not disclosed. ([more info](https://www.ibm.com/blogs/cloud-archive/2016/01/ibm-acquires-ustream/))

cc/ @tagliala
