### ISSUE TITLE
con request: icon-gitlab

### ISSUE THREAD

**Issue by l0ner** [FortAwesome/Font-Awesome#8663]
Gitlab is an alternative to github. It would be nice to have icons (normal and square) for this service.
link: [gitlab.com](https://about.gitlab.com/)

**Comment by tagliala** [comment]
duplicate of #1530, please +1 that request

closing here

**Comment by l0ner** [comment]
Sorry, couldn't find it before.

**Comment by tagliala** [comment]
@l0ner don't worry, I'm here to help :+1:
