### ISSUE TITLE
Font-Awesome Version 4.x/5.x

### ISSUE THREAD

**Issue by tuxy** [FortAwesome/Font-Awesome#8666]
When will we see the new version update ? The last version 4.5 update was on Nov 30, 2015. Are you working toward version 5.0 now ? Thanks.

**Comment by tagliala** [comment]
Sorry, I don't have a deadline

Please take a look at the [5.0.0 milestone page](https://github.com/FortAwesome/Font-Awesome/milestones), usally Dave adds there a due date
