### ISSUE TITLE
Icon Request: fa-hands-heart

### ISSUE THREAD

**Issue by LivelyDesigns** [FortAwesome/Font-Awesome#8667]
Hands holding heart

![services-hands](https://cloud.githubusercontent.com/assets/3137322/13381400/462d3a90-de29-11e5-83c4-a3845aaf9f9f.png)

**Comment by caduvieira** [comment]
Dupe of #6991?

**Comment by tagliala** [comment]
@caduvieira thanks

Duplicate of #6991, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
