### ISSUE TITLE
Icon Request: fa-responsive

### ISSUE THREAD

**Issue by simona6** [FortAwesome/Font-Awesome#8669]
I am trying to create buttons so people can request a Shop website or a simple Responsive website.

The Cart icons are great for the shop, but there is nothing I can use for responsive normal site.  So looking through the forum here, many have asked for such a thing.

So I'd like to post this as a new fresh request for a 'Responsive/Adaptive/Multi-device' icon please.

**Comment by cherrador** [comment]
#1446 ?

**Comment by tagliala** [comment]
@cherrador thanks
