### ISSUE TITLE
Icon Request: fa-talepal

### ISSUE THREAD

**Issue by haedurr** [FortAwesome/Font-Awesome#8670]
Hello, Font-Awesome team

Good mornin'.. I'm a newbie using github. And I'd like to request a single new icon (with lining version, if it's ok?), to be used for a fun site name, 'talepal'.. it's a startup site for talers or wannabe writers. Currently, building a site for it. And hoping to have a resizable font-awesome version too like seen at fortawesome.github.io/Font-Awesome/  and on "Black Tie Regular", which is neat by the way.

Here's an attachment of the icon to be converted to font-awesome:
https://cloud.githubusercontent.com/assets/17537377/13384986/7547ff74-ded6-11e5-8102-e37d35d55b7f.jpg

Looking forward for your great work. :)

— Hae

**Comment by tagliala** [comment]
@haedurr If I have understood correctly, this brand is about a website you are launching.

At the moment you should consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Closing here for now, I will reopen if there will be demand for this brand

**Comment by haedurr** [comment]
@tagliala i see... i think, that's what i need, a custom build icon. Thanks for redirecting me there. :)
