### ISSUE TITLE
Icons request: some new development related icons

### ISSUE THREAD

**Issue by TMMC** [FortAwesome/Font-Awesome#8674]
I've forgotten to write about it while going through a poll on FA website. 
It would be nice to have these: icon-jquery, icon-php, icon-mysql, icon-node, icon-grunt (would love to see this one), icon-python, icon-js, icon-less, icon-rwd, icon-bootstrap (or icon-framework - could be used for any framework in any other case).
Those listed above could be greatly used in portfolios and development websites instead whole labels/names, especially on smaller devices via media queries.
![new-icons-use](https://cloud.githubusercontent.com/assets/300390/13400666/0c4375ca-df09-11e5-8bc8-4dadf89c569c.png)
)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

> https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

There are duplicates like #8406 #1711 #1828 

Please also take a look at http://fizzed.com/oss/font-mfizz

**Comment by TMMC** [comment]
OK, I get it. mfizz seem to be quite enough for what I ment. The weak point is yet another fonts-set in project, but it's not this particular problem. Thanx for the link anyway.
