### ISSUE TITLE
[ICON REQUEST] Design architecture

### ISSUE THREAD

**Issue by taniagan** [FortAwesome/Font-Awesome#8676]
![measure design](https://cloud.githubusercontent.com/assets/16391934/13406136/e5716814-df47-11e5-880d-842fb02e501f.jpg)

Items 1,1
2,2
3,3

**Comment by tagliala** [comment]
Sorry, can't leave this open:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md

> Please do not request comprehensive sets of icons related to a very specific field.
