### ISSUE TITLE
No icons for fiverr, poepleperhour and bootstrap

### ISSUE THREAD

**Issue by salmandrupak** [FortAwesome/Font-Awesome#8680]
Please make icons for fiverr, peopleperhour and bootstrap

**Comment by tagliala** [comment]
Fiverr: #5970, bootstrap: #1828 , peopleperhour: #6373

All dups, please +1 the above requests

closing here

**Comment by isalmanhaider** [comment]
Still no icons for fiverr and bootstrap, while fontawesome site itself is built in bootstrap
