### ISSUE TITLE
Icon Request: fa-user-with-crown (admin)

### ISSUE THREAD

**Issue by MightyFo0l** [FortAwesome/Font-Awesome#8681]
Similar to #2553 but with a crown instead of a cog. I don't think a cog really describes an admin well. That's why I propose an user with a crown. Could also be used to visualize popular users or premium users.

Example:
![king_crown_royal_user_privilege_competitive_trophy_medal_winning_popularity_glory_high_awards_winners_badge_hero_victory_hit_proud_honor_leadership_competition_prize_premium_-512 1](https://cloud.githubusercontent.com/assets/16845714/13423279/33df505e-df9a-11e5-973a-e85ba3436b5e.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/user-crown?style=solid
