### ISSUE TITLE
Organize Icons

### ISSUE THREAD

**Issue by Whip** [FortAwesome/Font-Awesome#8682]
It's not a "issue" issue, rather a usability issue. I use your icons page to find the right icon for the situation - I'm sure everyone does - but lately the "Web Application" section which presumably your general category, is getting pretty large. It takes a considerable amount of time to sift through all of them.

I would request you to organize them more into sub categories like your text editor and currency categories. Talking about categories, for starters you can just remove the icons from Web Application that have been included in the categories below it. That would lessen the numbers and make them easier to find.

**Comment by danniranderis** [comment]
+1

**Comment by sensibleworld** [comment]
Our site search has been updated!

Version 6: https://fontawesome.com/v6.0/icons?s=solid%2Cbrands
Version 5: https://fontawesome.com/v5.15/icons
