### ISSUE TITLE
sign-out should point to the opposite direction of fa-sign-in

### ISSUE THREAD

**Issue by kissgyorgy** [FortAwesome/Font-Awesome#8684]
When placed a lot of these two icons close to each other, or there are many on the same page, they cannot be distinguished very fast, because they are very similar. I couldn't find an icon which is more suitable for entry and exit, so I used these, but because of the above reason I might change to something else, because they are unusable.

**Comment by tagliala** [comment]
Just to make sure... are you requesting the following change?

https://jsfiddle.net/tagliala/syduuue9/42/

**Comment by kissgyorgy** [comment]
Ouch. Sorry. Yes, exactly. It's funny because I remembered something like that might be possible and I was searching for it in the documentation, but obviously failed. Should have made one more click LOL
