### ISSUE TITLE
Icon Request: fa-tower (landmark)

### ISSUE THREAD

**Issue by yardensachs** [FortAwesome/Font-Awesome#8686]
So a tower would be good to describe an airport or a watch tower or a high structure.
![3946-200](https://cloud.githubusercontent.com/assets/2768400/13491625/27f7cbba-e13c-11e5-800d-6c2d5634691a.png)

**Comment by tagliala** [comment]
Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Include a few use cases for your requested icon. How do you plan on using it?
> Attach a single color image or two that represent the idea you're going for.

**Comment by yardensachs** [comment]
added to original

**Comment by tagliala** [comment]
so this is the same request as #8687 ?

**Comment by yardensachs** [comment]
yes and no, up to you. il be glad to have either
