### ISSUE TITLE
Icon Request: fa-control-tower

### ISSUE THREAD

**Issue by yardensachs** [FortAwesome/Font-Awesome#8687]

**Comment by tagliala** [comment]
any example?

**Comment by aethior** [comment]
I think it's easy to represent the airport using ´fa-plane´ and ´fa-square-o´.
Example: http://codepen.io/anon/pen/JXdNYG

**Comment by yardensachs** [comment]
![33-256](https://cloud.githubusercontent.com/assets/2768400/13491667/5b4f7c92-e13c-11e5-99e4-7e4f8149b60a.png)

Need to describe an airport

**Comment by tagliala** [comment]
That icon represents a `control-tower`, please fix the title

**Comment by lucastheisen** [comment]
@yardensachs , is the image provided free for usage, or is there a license fee?  (i would like to manually include in my project)

**Comment by Smirksta** [comment]
+ 1
