### ISSUE TITLE
Icon request: gift card

### ISSUE THREAD

**Issue by andrejs-uibo** [FortAwesome/Font-Awesome#8692]
For inspiration (can be without currency sign):
![Image of Giftcard](http://thumb7.shutterstock.com/display_pic_with_logo/2577385/367879685/stock-vector-black-gift-card-icon-with-shadow-concept-of-xmas-promo-saving-currency-mobile-app-valentine-367879685.jpg)
![Image of Giftcard](http://thumb9.shutterstock.com/display_pic_with_logo/845203/234295072/stock-vector-simple-icon-of-gift-made-with-credit-card-shadow-and-white-background-234295072.jpg)

**Comment by shmaster** [comment]
+1

**Comment by BillyBowyer** [comment]
+1

**Comment by toddjcrane** [comment]
+1

**Comment by ptahchiev** [comment]
+1 this icon is also known as voucher or coupon.

**Comment by ishwarpohani** [comment]
+1

**Comment by dtrybula** [comment]
+1

**Comment by smallersign** [comment]
Is this implemented in fa5?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/gift-card?style=solid
