### ISSUE TITLE
fa fa-filtered

### ISSUE THREAD

**Issue by amayd** [FortAwesome/Font-Awesome#8693]
Hi Team,

We are having filter icon right now. but i am not able to find filtered icon. Please consider.

Regards,
Ameya D.

**Comment by tagliala** [comment]
Could you please provide an example?

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
