### ISSUE TITLE
Icon Request: fa-tshirt

### ISSUE THREAD

**Issue by diegocarreira** [FortAwesome/Font-Awesome#8694]
Hi, this icon (T_SHIRT) will be very useful to represent "products" in the fashion cases of sites and software.
Example: [t-shirt icon image](https://image.freepik.com/free-icon/simple-t-shirt_318-10090.jpg)
Thank you so much! :)

**Comment by aethior** [comment]
Hi @diegocarreira,

This request is duplicate of #715. Please +1 that.

Regards.

**Comment by tagliala** [comment]
@aethior thanks as usual
