### ISSUE TITLE
Alias request: fa-commenting

### ISSUE THREAD

**Issue by jmglastetter** [FortAwesome/Font-Awesome#8696]
Issue: I was searching for an icon on your site to represent “Texting” or “SMS”.  I wasn’t having any luck until I stumbled upon the “Commenting” icon, which I think represents texting/SMS very well.
 
Solution:  Adding an alias to the Commenting icons, such as “Texting” and/or “SMS” would benefit many folks.

**Comment by tagliala** [comment]
Added as filters, thanks.

They should be available after the next doc build
