### ISSUE TITLE
Icon request: scopes

### ISSUE THREAD

**Issue by Cenute** [FortAwesome/Font-Awesome#8697]
![06-reticles-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509672/e572d7b6-e18c-11e5-922a-9fb08ef1c1ed.PNG)
![01-br-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509671/e5725688-e18c-11e5-9692-c34007a1ef2e.PNG)
![02-lr-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509669/e56fcabc-e18c-11e5-9fa0-bdba8dc00135.PNG)
![03-sfp-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509673/e57403fc-e18c-11e5-810a-43ef11070335.PNG)
![04-ffp-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509674/e5769fea-e18c-11e5-9758-9ca4d4f030d6.PNG)
![05-hunting-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13509670/e571d140-e18c-11e5-8fb5-87b53343d094.PNG)

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Include a few use cases for your requested icon. How do you plan on using it?
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺


bullseye: http://fortawesome.github.io/Font-Awesome/icon/bullseye/
