### ISSUE TITLE
Icon Request: fa-safety cone

### ISSUE THREAD

**Issue by CorinnaSch** [FortAwesome/Font-Awesome#8698]
Hi!
I'm looking for an Icon representing safety issues. A safety cone or something like that would be great.
![safety 20cone](https://cloud.githubusercontent.com/assets/17637117/13520727/1a397580-e1e3-11e5-88be-4ebbfb9132a6.jpg)

**Comment by tagliala** [comment]
duplicate of #4485 , please +1 that request

closing here
