### ISSUE TITLE
fa-circle-thin not working 

### ISSUE THREAD

**Issue by bibliofille** [FortAwesome/Font-Awesome#8703]
I'm trying to stack social media icons (twitter, facebook, instagram) each inside a circle thin icon, but the circle thin icon doesn't show up. I tried it with the regular circle, and it worked, but the regular circle is a bit harsh-looking. 

Is there a way to "thin" the regular circle? Also, how can I get more padding between the social icon and the circle?

Here's my code: 
`<ul class="social-menu">
	<li><a href="www.twitter.com">
		<span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span></a></li>
	<li><a href="www.facebook.com"><span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x fa-3x"></i>
  <i class="fa fa-facebook fa-stack-1x"></i>
</span></a></li>
	<li><a href="www.instagram.com"><span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-instagram fa-stack-1x"></i>
</span></a></li>
	<li><a href="www.youtube.com"><span class="fa-stack fa-lg">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-youtube fa-stack-1x" ></i>
</span></a></li>
	</ul>`

**Comment by tagliala** [comment]
Hi

> I'm trying to stack social media icons (twitter, facebook, instagram) each inside a circle thin icon, but the circle thin icon doesn't show up. I tried it with the regular circle, and it worked, but the regular circle is a bit harsh-looking.

circle-thin is fine: https://jsfiddle.net/tagliala/syduuue9/43/

Please make sure you are using FA >= 4.1.0 

Take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

> Also, how can I get more padding between the social icon and the circle?

If the default stack feature doesn't fit your needs, you can go for custom css.

Hope it helps, closing here
