### ISSUE TITLE
Icon Request: fa-philippines/fa-ph

### ISSUE THREAD

**Issue by jaydee9296** [FortAwesome/Font-Awesome#8706]

**Comment by tagliala** [comment]
could you please clarify?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by jaydee9296** [comment]
Sample image sir :)

![flag_of_the_philippines svg](https://cloud.githubusercontent.com/assets/8472952/13547506/1bcf8c0c-e311-11e5-94f1-0d02d1cb8943.png)

**Comment by tagliala** [comment]
Thanks

Sorry, flags are out of scope. Please consider an .svg based solution

Refers to #4516
