### ISSUE TITLE
Icon request: fa-public-domain

### ISSUE THREAD

**Issue by glueball** [FortAwesome/Font-Awesome#8707]
Icon to denote that a content or file is in the public domain (ie, that has no right reserved). Note that this is different from copyleft (which is already requested), and the already existing creative commons icon. 

There are a couple of common icons for this concept. The guys and gals at creativecommons.com have this icon, which is something like a stroked-through 0:

https://licensebuttons.net/p/zero/1.0/88x31.png

Perhaps more a more common icon (which I personally like more) is based on the copyright icon. I've been using this by stacking the ban and copyright icon, but the result is far from perfect:

http://creationwiki.org/pool/images/thumb/e/eb/Public_domain.png/200px-Public_domain.png

**Comment by kwendenarmo** [comment]
Really this isn't exist already as request? then +1

**Comment by glueball** [comment]
This is already implemented in fa5 ;)

creative-commons-zero
creative-commons-pd
