### ISSUE TITLE
Language not working

### ISSUE THREAD

**Issue by Jordane20** [FortAwesome/Font-Awesome#8712]
I have tried these and they are not working...

<i class="fa fa-language"></i>

<i class="fa fa-area-chart"></i>

<i class="fa fa-pie-chart"></i>

**Comment by tagliala** [comment]
Hi, could you please clarify?

Do you mean that http://fontawesome.io/icon/language/ is not working on your website?

**Comment by Jordane20** [comment]
Yes, I have tried to use that one and a couple of others and they dont seem
to work. Though there are several others that i am using that work. Not
sure why?




Warm Regards,

Jordan Erickson


<http://www.conceptualizeddesign.com/>

www.ConceptualizedDesign.com
P.O. Box 651
Manhattan, KS 66505
1.785.236.1777



Notice: This e-mail is covered under the Electronic Communications Privacy
Act, 18 USC 2510-2521, and is legally privileged. The information contained
in this e-mail is intended only for use of the individual or entity named
above. If the reader of this message is not the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone at the
above number and permanently delete all copies of the original message.

**Comment by tagliala** [comment]
Please check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

I suppose you are using an outdated version of FA (< 4.1)

Closing here but feel free to keep commenting
