### ISSUE TITLE
Icon Request: fa-reticle

### ISSUE THREAD

**Issue by Cenute** [FortAwesome/Font-Awesome#8717]
for inspiration:

![06-reticles-pozitiv](https://cloud.githubusercontent.com/assets/10871569/13583248/90fdab30-e4b0-11e5-9321-8dd59148a035.PNG)

**Comment by aethior** [comment]
Hi @Cenute,

Something like https://fontawesome.com/icons/crosshairs?

Regards.

**Comment by tagliala** [comment]
I'm going to close here for the moment
