### ISSUE TITLE
Icon Request: fa-skip-previous, fa-skip-next

### ISSUE THREAD

**Issue by urmilparikh** [FortAwesome/Font-Awesome#8727]
These icons are to be used with media player application to skip to previous or next tracks / titles / chapters.

These icons can also be used for scrolling / pagination.

![fa-skip](https://cloud.githubusercontent.com/assets/10322815/13660544/0ae9792c-e6b1-11e5-808d-d51b9c03f495.png)

NOTE: These are different from fa-fast-backward / fa-fast-forward, since fast-backward / fast-forward buttons have different operations on click and long-click.

**Comment by tagliala** [comment]
http://fontawesome.io/icon/step-forward/
http://fontawesome.io/icon/step-backward/

Closing here
