### ISSUE TITLE
Icon-Request

### ISSUE THREAD

**Issue by kronikles** [FortAwesome/Font-Awesome#8731]
I have created 3 icons here. Can you add it to font-awesome?
remote access![remote access](https://cloud.githubusercontent.com/assets/17491778/13666484/bcf26652-e6ec-11e5-8fde-e9183495f113.png)
software![software](https://cloud.githubusercontent.com/assets/17491778/13666485/bcf4778a-e6ec-11e5-8ff5-32e461cd85d7.png)
vmwareaccount![vmwareaccount](https://cloud.githubusercontent.com/assets/17491778/13666486/bcf5f8d0-e6ec-11e5-9d99-15f065ce9936.png)

Please? and Thank you

**Comment by caduvieira** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
