### ISSUE TITLE
Icon Request: fa-ubuntu

### ISSUE THREAD

**Issue by sanik90** [FortAwesome/Font-Awesome#8734]
add for Brand Icon, Ubuntu

<img src="http://assets.ubuntu.com/v1/49a1a858-favicon-32x32.png">

and svg can be find <a href="http://design.ubuntu.com/downloads?search=logo&submit=" target="_blank">here</a>

**Comment by aethior** [comment]
Hi @sanik90,

This request is duplicate of #980. Please +1 that.

Regards.

**Comment by tagliala** [comment]
Closed thanks

OT: Oh, there are upvotes now?

**Comment by sanik90** [comment]
@aethior sorry, my bad, requested since 2013 eh? long due haha
