### ISSUE TITLE
Icon Request: icon-crustacean

### ISSUE THREAD

**Issue by forclaz** [FortAwesome/Font-Awesome#8736]
Hi,
Could to do allergens icons?. In EU is mandatory to inform to allergens on Restaurants, Bars, coffe-shop, etc. I´m  going to develop an application and  I´ll like to use on it.

There´re 14 allergens, this email start  with "crustacean"  ,  in my next email i request  rest of them.

Also, you can to take an idea about this icons on this page (sorry to take the liberty  on show you):
http://www.shutterstock.com/pic-247939057/stock-vector-allergen-icons.html 

Thank you in advance!!
Eduardo

**Comment by tagliala** [comment]
Refers to #5228

This request is fine, but if you need all allergens the above advice is still valid.

Please consider a custom build and merge FontAwesome with a food-related icon font: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by holtkamp** [comment]
@forclaz if you can contribute, please see https://github.com/FortAwesome/Font-Awesome/issues/5228#issuecomment-280304750

**Comment by sensibleworld** [comment]
We have the following icons now:

https://fontawesome.com/v6.0/icons/crab?s=solid
https://fontawesome.com/v6.0/icons/lobster?s=solid
https://fontawesome.com/v6.0/icons/shrimp?s=solid

**Comment by tagliala** [comment]
@sensibleworld any chance to add just one of the three icons in the free set for the allergens use case?

**Comment by sensibleworld** [comment]
@tagliala Yup! I'll add `shrimp` to free.

**Comment by forclaz** [comment]
Cool, Well done!. 
Thnks!
