### ISSUE TITLE
Can font-awesome.css.map be ignored in bower.json?

### ISSUE THREAD

**Issue by jywarren** [FortAwesome/Font-Awesome#8741]
It causes Sass to choke in Rails 3.2 and 4 (#6820) -- and while I know that's not exactly FA's problem, it doesn't seem that this source map is totally necessary, at least in the bower included version of the library. I don't see any reference to it, and it seems to have been added in an unrelated commit.

A viable option for me was to disable the sass-rails gem. But obviously this is not easy for everyone. So I just wanted to check that the file itself is actually necessary for a) being in the repository at all, and b) being included in the bower-packaged version. The file is:

https://github.com/FortAwesome/Font-Awesome/commits/master/css/font-awesome.css.map

I don't see reference to it in its original commit, or in any issue or other part of the codebase. Perhaps it could be ignored in a bower.json directive?

**Comment by tagliala** [comment]
How are you including fontawesome in your rails project?

Have bootstrap (not `bootstrap-sass`) the same issue? It seems they also include a .map file

**Comment by jywarren** [comment]
Using a bower.json directive, into the public/lib/ directory. I did see
that but I'm not sure why bootstrap's is not throwing the same error. But
aren't source maps for development only? Are they useful for folks using it
via bower in production?

I had guessed that the .map was being included by sass-rails based on its
file extension. But I'm not sure, and wasn't able to find documentation on
which extensions sass-rails grabs or how to configure that. I left some
notes in the issue I linked to above.

**Comment by tagliala** [comment]
The directory structure is slightly different, bootstrap uses `/dist`. May be related to #8096?

**Comment by jywarren** [comment]
We found a solution for our Rails-specific issue here: https://github.com/FortAwesome/Font-Awesome/issues/6820#issuecomment-195950693

If it's not a problem for anyone else, feel free to close this issue, or tell me and I can. But if the .map files are not needed, it could still be a good idea to omit them as it does take a little extra configuration if people are running sass in rails without the additional configuration. It took us by surprise. 

Thanks!

**Comment by tagliala** [comment]
I'm using sass in rails but I think this is sass+rails+bower

There is also this gem: https://github.com/FortAwesome/font-awesome-sass that should not soffer from this issue

**Comment by tagliala** [comment]
Closing here
