### ISSUE TITLE
missing icons - validate, verify

### ISSUE THREAD

**Issue by sabarishrl** [FortAwesome/Font-Awesome#8752]
You have very good collection, but, can you add icons for verify, validate or test action? The check icon is "tick mark" which for me it means correct, but i want to do validate to ascertain is it the values are valid or invalid values provided by user. 

Thanks

**Comment by tagliala** [comment]
could you please provide a single color example suitable for 14px icon size? You can use google images

**Comment by heberda** [comment]
I am also keen for this sort of icon. It is a tricky one. Here are some examples:

https://cdn2.iconfinder.com/data/icons/security-2-1/512/valid_shield-512.png
http://validationcenter.com/wp-content/uploads/2015/03/valcenter_icon-checklist.gif
https://cdn0.iconfinder.com/data/icons/material-design-ii-glyph/614/3013_-_Verified_User-512.png

**Comment by aethior** [comment]
Hi,

Currently there are some icons (e.g. [fa-circle-check](https://fontawesome.com/icons/circle-check), [fa-badge-check](https://fontawesome.com/icons/badge-check) and [fa-shield-check](https://fontawesome.com/icons/shield-check)) that can represent validation or verification.

Regards.

cc/ @tagliala
