### ISSUE TITLE
Icon Request: icon-ethereum

### ISSUE THREAD

**Issue by c055** [FortAwesome/Font-Awesome#8754]
## Ethereum Icon

![Ethereum Logo Icon](https://cloud.githubusercontent.com/assets/1474978/15791708/cd4dd980-298d-11e6-8f00-d500fbc7e5ff.png)

@kumavis do you have an .svg version of the ETH logo? would be great for easier integration …

There are many use cases : there is a completely new market popping up-- Decentralized Applications (DApps).  I predict a massive demand to be able to easily use this icon in future.
- IoT
- DApps
- Sites
- UI/UX
  
  build on `<i class="fa-icon-ethereum"></i>`

just a few examples ..
### unicode symbol

`Ξ`

https://ethereum.org/

**Comment by liorsaar1** [comment]
+1

**Comment by kumavis** [comment]
👍 
http://coinmarketcap.com/

Ethereum is the 2nd largest crypto currency by market cap at ~1 billion usd
Likely larger than some of the companies who have logos in Font-Awesome

**Comment by kumavis** [comment]
I think the logo would be more recognizeable than the unicode gliph `Ξ`

![image](https://cloud.githubusercontent.com/assets/1474978/15791708/cd4dd980-298d-11e6-8f00-d500fbc7e5ff.png)

**Comment by flyswatter** [comment]
I had +1'd the original post thinking it had meant the diamond logo posted above.  I think it's much more broadly recognized as the actual Ethereum symbol. @cassiopaia would you agree that the Ether logo would be a good fontawesome addition, or should we file a separate issue for that?

**Comment by cassiopaia** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/8754#issuecomment-223683986

sure i meant to use the logo .. the unicode gliph was just as an addition to get a feeling about the brand .. go ahead .. no need to seperate it :) thx for asking

**Comment by flyswatter** [comment]
Would you mind adding an image of it to the original post then, to avoid ambiguity?

Thanks, @cassiopaia  :)

**Comment by cassiopaia** [comment]
@flyswatter :) done

**Comment by kumavis** [comment]
we will need a black-and-white version of the logo

**Comment by mariodian** [comment]
+1

**Comment by BesrourMS** [comment]
+1

**Comment by LefterisJP** [comment]
+1

**Comment by maypo** [comment]
+1

**Comment by czepluch** [comment]
+1

**Comment by sofiabravo103** [comment]
+1

**Comment by miguelmota** [comment]
It's been over a year, any progress update on this?

**Comment by C1n** [comment]
+1

**Comment by ruivalentemaia** [comment]
+1

**Comment by xtoff** [comment]
+1

**Comment by nicohabets** [comment]
+1

**Comment by arrrbeee** [comment]
+1

**Comment by liorsaar1** [comment]
+1

**Comment by jjz4689** [comment]
Hope this might help a little 😃

I've made a Black & White SVG version of the Ethereum logo, but can't upload to here through GitHub.

I've uploaded it to the web: http://gjdev.uk/downloads/fa-icon-ethereum.svg

Would it be useful for making the icon for Font Awesome?

**Comment by 409H** [comment]
I also have an SVG version of the graphic: https://codepen.io/409/pen/GErLwJ

**Comment by sneurlax** [comment]
+1 :)

**Comment by BealyBeal** [comment]
+1

**Comment by jjz4689** [comment]
@409H - Very nice codepen, that's awesome!

The only downside that comes to mind is that it's in colour, and Font Awesome icons are black and white - not even grayscale 😞 - which is the issue I faced.

I started with a similar SVG and that's how I eventually ended up with the B+W version I did.
Although, admittedly, mine isn't too amazing at the moment and could do with a lot more work to get it to the right spec to conform with other icons - mainly the rounded edges  - in my defence I spent a cheeky hour whilst at work designing it 😆.

**Comment by andregomesdepaiva** [comment]
+1

**Comment by blmalone** [comment]
+1

**Comment by ReactiioN1337** [comment]
+1

**Comment by MeesCode** [comment]
+1

**Comment by keesfani** [comment]
+1

**Comment by tgerring** [comment]
+1

**Comment by Cygnusfear** [comment]
+1

**Comment by kivo360** [comment]
+1

**Comment by clowestab** [comment]
+1

**Comment by hongalex** [comment]
+1

**Comment by judezhu** [comment]
+1

**Comment by haydencarlson** [comment]
+1

**Comment by JohnAllen** [comment]
+1

**Comment by fgallaire** [comment]
+1

**Comment by estebandelaf** [comment]
+1

**Comment by alexanderbelko** [comment]
+1

**Comment by nguyenhoaibao** [comment]
+1

**Comment by reinierkors** [comment]
+1

**Comment by ivanursul** [comment]
+1

**Comment by larryg123** [comment]
+1

**Comment by sekelje** [comment]
+1

**Comment by JohnRichards4** [comment]
+1

**Comment by FleurA** [comment]
+1

**Comment by William2030** [comment]
+1  :+1:

**Comment by William2030** [comment]
@c055   I updated your png to make it look more pyramidal but still black with "edges" below:
![eth 1](https://user-images.githubusercontent.com/31596855/32476065-1cd4ae2a-c343-11e7-8f4c-1ab1b5bf5499.png)

**Comment by Luka188** [comment]
+1

**Comment by CallMeGwei** [comment]
@William2030 Great Ethereum logo for inclusion here. 

Thank you all for helping the community get this icon included in FontAwesome.

**Comment by thombirch** [comment]
+1

**Comment by haydenfree** [comment]
+1

**Comment by Jkettler** [comment]
+1

**Comment by ianaz** [comment]
+1

**Comment by nielsengit** [comment]
+1

**Comment by naturalistic** [comment]
+1

**Comment by neeeeeeext** [comment]
+1

**Comment by Loktho** [comment]
+ 1

**Comment by lucbas** [comment]
+1

**Comment by NigelHeylen** [comment]
+1

**Comment by alexfriant** [comment]
+1

**Comment by Kninen** [comment]
+1

**Comment by AkashDaryanani** [comment]
+1

**Comment by jdourlens** [comment]
+1

**Comment by derblub** [comment]
+1

**Comment by phleemac** [comment]
+1

**Comment by Boydbueno** [comment]
+1

**Comment by albertsgrc** [comment]
+1

**Comment by avinash-oza** [comment]
+1

**Comment by davemandy** [comment]
+1

**Comment by freeatnet** [comment]
+1

**Comment by timbeiko** [comment]
+1

**Comment by josephfoulds** [comment]
+1

**Comment by leoz2007** [comment]
+1

**Comment by arnehendriksen** [comment]
+1

**Comment by NickLewanowicz** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
Well, this definitely isn't a suspicious amount of activity for a single day! 😆

To save spamming people's notifications with an issue just to add your `+1`, give the original post a 👍, instead.

**Comment by shyblugs** [comment]
+1

**Comment by NickSet** [comment]
+1

**Comment by lostick** [comment]
+1

**Comment by franckl** [comment]
+1

**Comment by kleprevost** [comment]
+1

**Comment by patel66** [comment]
+1

**Comment by michaelasper** [comment]
+1

**Comment by timojarv** [comment]
+1

**Comment by miguelmota** [comment]
@davegandy @tagliala

**Comment by bobbyschultz** [comment]
+1

**Comment by ethorse** [comment]
+1

**Comment by wlemahieu** [comment]
+1

**Comment by davegandy** [comment]
Will be in 5.0.2 coming out in a few days.

**Comment by CallMeGwei** [comment]
Awesome! Thank you all for the support and implementation!

**Comment by Sssalerious** [comment]
Nice!

**Comment by haydencarlson** [comment]
Yay

**Comment by ethorse** [comment]
Awesome!

**Comment by davidp94** [comment]
Super!

**Comment by tagliala** [comment]
https://fontawesome.com/icons/ethereum?style=brands
