### ISSUE TITLE
Icon request: bug-o

### ISSUE THREAD

**Issue by kazarenko** [FortAwesome/Font-Awesome#8758]
It would be great to have a bug-o icon. Then this could be used in conjunction with the bug icon, so that the icon can be used to add a bug and also indicate if any bugs are present

**Comment by tagliala** [comment]
Font Awesome 5 Pro provides an outlined bug icon: https://fontawesome.com/icons/bug?style=regular

Anyway, regular and solid icons are not mean to be exchangeable in every case.

You can switch from circle solid to circle regular, square solid to square regular, star solid to star regular, etc... But the design of locks is different

I would suggesto to use something else to indicate a state without bugs

Closing here
