### ISSUE TITLE
Icon Request: Backordered

### ISSUE THREAD

**Issue by spidre409** [FortAwesome/Font-Awesome#8759]
![backorder-icon](https://cloud.githubusercontent.com/assets/6836015/13781918/fe800080-ea92-11e5-9bd0-bc9f7b708316.png)

For ecommerce sites/apps would be good to be able to flag items backordered.  Currently using an PNG like this, considered using a FLAG, but that is a bit too generic.

Thanks,

M

**Comment by tagliala** [comment]
http://fontawesome.io/icon/history/ should do the job

**Comment by spidre409** [comment]
As a PNG it works, great, but a scalable, vector icon in the lib would be even better, could also represent history as well.
