### ISSUE TITLE
facebook reaction icons

### ISSUE THREAD

**Issue by kync** [FortAwesome/Font-Awesome#8764]
So all of us know facebook have changed like button by adding new reactions. In orderly the new reactions are love, haha, wow,sad,angry. I can use sad and love in this time via font awesome. But haha, wow and agry as i know they don't exist. do you have a chance to add these icons to fontawesome ?

**Comment by tagliala** [comment]
Refers to #1417 and #1418.

So we need "wow-o" and "angry-o", right?

* [x] Like: `thumbs-up-o`
* [x]  Love: `heart-o`
* [x] Haha: `smile-o`
* [ ] Wow:
* [x] Sad: `sad-o`
* [ ] Angry:

**Comment by alikoyuncu** [comment]
Yes, we do.

**Comment by dougkillmer** [comment]
Yes, then what do we do with "thankful"?
https://developers.facebook.com/docs/graph-api/reference/post/reactions

**Comment by mrzorn** [comment]
Any movement on this? looking for the wow icon

**Comment by prionkor** [comment]
Any update on this?

**Comment by tagliala** [comment]
@prionkor I think we have all of them

wow: https://fontawesome.com/icons/surprise?style=solid
angry: https://fontawesome.com/icons/angry?style=solid
