### ISSUE TITLE
Icon Request: fa-ssl

### ISSUE THREAD

**Issue by tverheijen** [FortAwesome/Font-Awesome#8765]
SSL font with closed and open slot would be nice

**Comment by tagliala** [comment]
Could you please post single color examples suitable for 14px icon size?

**Comment by tverheijen** [comment]
> https://cdn2.iconfinder.com/data/icons/e-business-helper/240/627115-lock-128.png
> https://login.dcalling.de/fileadmin/www/images/icon_ssl.png

look @ the links for details.

**Comment by tagliala** [comment]
a lock is already available: http://fontawesome.io/icon/lock/

**Comment by tverheijen** [comment]
ow my bad, looked completly over it :)

**Comment by tagliala** [comment]
no problem :+1:
