### ISSUE TITLE
Possible to use font awesome on the css's cursor property?

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#877]
Is it possible to use font awesome on the css's cursor property?
I'd like to have icon-text-height when hovered on a textarea or input box.
or, having spining loading icon when doin ajax.

Thanks

**Comment by cauerego** [comment]
It's sure possible: https://jwarby.github.io/jquery-awesome-cursor/

Although I'd wish not needing a plugin: http://stackoverflow.com/questions/24093263/set-font-awesome-icons-as-cursor-is-this-possible
