### ISSUE TITLE
Add privacy filter to user-secret

### ISSUE THREAD

**Issue by tohansen** [FortAwesome/Font-Awesome#8775]
Please add a privacy icon (maybe a mask)

**Comment by tagliala** [comment]
Like  this one? http://fontawesome.io/icon/user-secret/

**Comment by tohansen** [comment]
Yes, like that one! thank you... could be a good idea to "mask" and "privacy" to the search terms for that icon. :+1:

**Comment by tagliala** [comment]
will do it with a `privacy` filter
