### ISSUE TITLE
Icon-request: Map with Marker

### ISSUE THREAD

**Issue by djmj** [FortAwesome/Font-Awesome#8779]
Related to this issue: https://github.com/FortAwesome/Font-Awesome/issues/1023 

I find map+marker maybe more suitable for a specific address then just map or marker alone.

like: http://simpleicon.com/wp-content/uploads/map-8.png

**Comment by rjbathgate** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=map-marked&v=5.1.0
