### ISSUE TITLE
Icon request: 360 (Brand)

### ISSUE THREAD

**Issue by cjrams** [FortAwesome/Font-Awesome#8782]
http://www.360.com/
Icon sample: http://p3.qhimg.com/t01b7cb83f41d31a8bf.png

**Comment by ccharlton** [comment]
Ref: #5820

**Comment by wolfy1339** [comment]
Why did you close this request?

**Comment by tagliala** [comment]
@wolfy1339 the request has been closed by its author and it has all the rights to do that

Since this issue has not upvotes, please open a new request if you are interested in the 360 Brand
