### ISSUE TITLE
Icon Request: fa-telegram

### ISSUE THREAD

**Issue by iamale** [FortAwesome/Font-Awesome#8783]
An icon for a Telegram messenger, which is quite popular here in Russia. For a reference, here's the official icon and an alternative logo used in the webapp:

![Telegram logo](https://cloud.githubusercontent.com/assets/1298948/13875249/31aabd76-ed16-11e5-8441-1ac2359692b6.png) ![Alternative logo](https://cloud.githubusercontent.com/assets/1298948/13875479/8899a452-ed17-11e5-8739-3438e48b2942.png)

(SVG: [1](https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg), [2](https://upload.wikimedia.org/wikipedia/commons/d/dd/Telegram_alternative_logo.svg))

One major use case would be to include it with the other social links on personal and brand websites. For example, here's the social links block on [Meduza (ru)](https://meduza.io):

![Meduza screenshot](https://cloud.githubusercontent.com/assets/1298948/13875397/10ab44dc-ed17-11e5-902d-9adc28165794.png)

**Comment by aethior** [comment]
Hi @iamale,

This request is duplicate of #3034. Please +1 that.

Regards.

**Comment by iamale** [comment]
Oh, I'm sorry then. Thanks for pointing this out!
