### ISSUE TITLE
NFC Icon

### ISSUE THREAD

**Issue by MGKVWeb** [FortAwesome/Font-Awesome#8785]
I think Font-Awesome need also a NFC Icon

https://en.wikipedia.org/wiki/Near_field_communication

https://en.wikipedia.org/wiki/Near_field_communication#/media/File:NFC-N-Mark-Logo.png

**Comment by aethior** [comment]
Hi @MGKVWeb,

This request is duplicate of #1695. Please +1 that.

Regards.
