### ISSUE TITLE
Icon Request: fa-newsvine

### ISSUE THREAD

**Issue by EdyHinzen** [FortAwesome/Font-Awesome#8786]
newsvine.com is social media service
Please see https://commons.wikimedia.org/wiki/File:Newsvine.svg for SVG icon source

By the way: Thanks for your great work, so far :)

**Comment by aethior** [comment]
>On October 1, 2017; NBCNEWS closed Newsvine and redirected the Newsvine website to the NBCNEWS web page. Other than a notice on Newsvine; very little coverage indicated the shutdown. ([more info](https://en.wikipedia.org/wiki/Newsvine))

Regards.

cc/ @tagliala
