### ISSUE TITLE
Icon request: fa-responsive

### ISSUE THREAD

**Issue by FrancescoMussi** [FortAwesome/Font-Awesome#8792]
Hello guys!
It could be 'awesome' to have the typical responsive icon.
That is: pc - tablet - phone (with the pc in the background).

It could be very useful for portfolio websites.

Thank you for the attention.

**Comment by tagliala** [comment]
duplicate of #1446 , please +1 that request

closing here

**Comment by FrancescoMussi** [comment]
Ok done, thanks
