### ISSUE TITLE
Icon Request: fa-arrows-i

### ISSUE THREAD

**Issue by AmitMY** [FortAwesome/Font-Awesome#8793]
When creating fullscreenable things (like modals, or windows) it is commin to use the "expand" icon - or fa-arrows-alt - to go to fullscreen, and some sort of implode icon to minimize back to normal screen,
It does not seem you have this icon.
![image](https://cloud.githubusercontent.com/assets/5757359/13903502/cd262a6c-ee86-11e5-8662-43278f6c7be9.png)
![image](https://cloud.githubusercontent.com/assets/5757359/13903503/d09db08e-ee86-11e5-8ea6-773ad55f0c7f.png)

**Comment by tagliala** [comment]
Duplicate of #1468, please +1 that request

closing here
