### ISSUE TITLE
Intersection icon

### ISSUE THREAD

**Issue by Aliuken** [FortAwesome/Font-Awesome#8798]
Could you add an icon of a circle intersecting with another circle? Like this:
https://en.wikipedia.org/wiki/Intersection_%28set_theory%29#/media/File:Venn0001.svg

Thanks.

**Comment by tagliala** [comment]
Duplicate of #1544, please +1 that request

closing here

**Comment by tagliala** [comment]
duplicate of #2164, please +1 that request

closing here

**Comment by Aliuken** [comment]
I don't know how to do a +1

**Comment by tagliala** [comment]
leave a comment with "+1" :)
