### ISSUE TITLE
Icon request:fa-engine

### ISSUE THREAD

**Issue by jrgleason** [FortAwesome/Font-Awesome#8802]
This is a need for my project. Possible examples exist here...

https://www.google.com/search?q=engine+icon&safe=active&espv=2&biw=1298&bih=681&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwigrqakwtTLAhWKRSYKHenVCJMQsAQIGw#imgrc=GNPtaNZy2rv4cM%3A

**Comment by tagliala** [comment]
Duplicate of #4175, please +1 that request

closing here
