### ISSUE TITLE
Icon request: fa-xero

### ISSUE THREAD

**Issue by ls009** [FortAwesome/Font-Awesome#8803]
Xero has been requested already a bunch of times: [4574](https://github.com/FortAwesome/Font-Awesome/issues/4574)

I'd like to submit with my limited skills:
[fa-xero.zip](https://github.com/FortAwesome/Font-Awesome/files/184348/fa-xero.zip)

**Comment by tagliala** [comment]
Sorry, since you have already +1'd #4574, the best you can do is to consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by ls009** [comment]
I actually built the icon that people want and instead of reviewing it you closed it? Why did you just disregard someone trying to contribute to the icons?

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#the-hard-way

> 1. Fork the repository. You need a properly configured development environment
2. Hack with the .otf file. Here it is a guide you can follow: The making of Octicons
3. Share with the Font Awesome community. Check for open issues that are related to your fork and share your repository

I will repeat "your fork" hoping that it would be clearer
