### ISSUE TITLE
Icon request: signal-messenger

### ISSUE THREAD

**Issue by CharlesSchaack** [FortAwesome/Font-Awesome#8806]
I am creating a website and wanted to provide a Signal messenger finger print as an alternative way to get in contact with me. I was hoping an icon could be created for Open Whisper's signal messaging service.

The actually messaging app uses the following for it's icon (the app used to be called text-secure):
https://p5.zdassets.com/hc/settings_assets/841909/200174937/VdKIdtUfrabuBQ93724BBQ-TextSecure.png

That icon is rather bland/generic though so I am wondering if maybe the Open Whisper's icon would be better suited:
https://avatars3.githubusercontent.com/u/702459?v=3&s=200

Open Whisper's website:
https://whispersystems.org/

Thanks in advance!

**Comment by tagliala** [comment]
Probably a dup of #7434, not sure, both are not clear requests :\

**Comment by CharlesSchaack** [comment]
I apologize for not seeing that issue. I did a search but that result did not come up. On the issue of clarity is there anything I can do to clarify this request further?

**Comment by tagliala** [comment]
this application has different logos for ios and android. Still don't know what to do

**Comment by CharlesSchaack** [comment]
Yeah, they for sure haven't been the best at branding a clear image. Not sure what would be best. I see your dilemma though. It might actually make more sense to just wait, I would assume they are planning on creating one clear image at some point.

**Comment by tagliala** [comment]
I'm going to close this one in favour of  #7434, please open a new request if you want to request an icon for whispersystems
