### ISSUE TITLE
icon request: arrowheads 4 directions

### ISSUE THREAD

**Issue by hpvd** [FortAwesome/Font-Awesome#8810]
icon request: arrowheads 4 directions
e.g.
for "more details" unfold and refold
![2016-03-23_16h22_09](https://cloud.githubusercontent.com/assets/5681880/13990513/f6951404-f114-11e5-9212-3c9143c191bb.png)
PS: if math "greater than" would become available
see https://github.com/FortAwesome/Font-Awesome/issues/1133
this could be used as a work around together with rotating function

=> if you like /need it: vote for this and the math one!!

**Comment by hpvd** [comment]
just found something similar could be done with
angle-right or chevron-right
and
angle-down or chevron-down

**Comment by tagliala** [comment]
I'm closing here because you can use `angle-*`, `caret-*` and `chevron-*` for this use case

**Comment by hpvd** [comment]
that's fine! thanks for pointing to all three possibilities (just found only 2)
