### ISSUE TITLE
Icon Request: fa-digital-signal

### ISSUE THREAD

**Issue by drathnow** [FortAwesome/Font-Awesome#8815]
I have a need for an digital signal icon. Our app has the ability to configure digital input sensors and I would like to include this icon beside the title on the menubar. 

![digital](https://cloud.githubusercontent.com/assets/1458259/14001383/2edea29e-f10b-11e5-8e88-de1ab7ea405c.png)

**Comment by ddavidebor** [comment]
That's not an analog signal...

**Comment by drathnow** [comment]
Ooops! ;(  Sorry, I meant digital.  Cut-and-paste error.

**Comment by nofxx** [comment]
Actually sine and square waves might be just the carrier... for analog or digital.
But anyways, both are nice, great addition.
Another approach I like is sony VAIO, VA for sine wave 10 for digital.

**Comment by poposhka** [comment]
this would be awesome

**Comment by BSTomack** [comment]
I could really use this one and a sine wave

**Comment by tagliala** [comment]
Released in 5.8.0

https://fontawesome.com/icons/wave-square?style=solid
