### ISSUE TITLE
Icon request: pending or waiting status

### ISSUE THREAD

**Issue by oddb** [FortAwesome/Font-Awesome#8816]
Wonderful work, guys! 
We need an icon for our learning management system that signals that a lesson or meeting status is 'pending' or 'awaiting'. For example, a webinar session is scheduled to start another day, or an elearning lesson you have not yet started. It is fairly easy to use fa-check to signal that the lesson/meeting is completed, but not so intuitive to do the opposite. Suggestions?

**Comment by tagliala** [comment]
Results for `warning`:

http://fontawesome.io/icon/exclamation-triangle/
http://fontawesome.io/icon/exclamation/
http://fontawesome.io/icon/exclamation-circle/

I think those are enough to do the job, if you have something different in mind please post a single color example

**Comment by s-mohapatra** [comment]
I need  icons for pending  and reject files.

**Comment by ChrisLang** [comment]
I really dont think the exclamation is the right icon to use for pending

I mean just do a google and see what it suggests;

![image](https://github.com/FortAwesome/Font-Awesome/assets/2931581/70dcd034-fdc7-4006-ae83-1738af0eda2f)
