### ISSUE TITLE
Icon request: fa-car-accident

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8817]
Hi all,

We need an icon for an accident or damage, like:
![image](https://cloud.githubusercontent.com/assets/17614935/14013738/77467e32-f1ae-11e5-855e-add48b83e79e.png) or 
![image](https://cloud.githubusercontent.com/assets/17614935/14013795/d82f8c7a-f1ae-11e5-9bb8-fe5da33c1a9a.png)

**Comment by dpfem** [comment]
+1

**Comment by kukko** [comment]
+1
But the icons would be better.

**Comment by JeansReal** [comment]
+1

**Comment by jschouwstra** [comment]
+1

**Comment by MarcoSpoenemann** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/car-crash?style=solid
