### ISSUE TITLE
Icon request: fa-invoice-euro

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8819]
Hi all,

We need an icon for Euro-invoices like:
![image](https://cloud.githubusercontent.com/assets/17614935/14014781/f5294ac2-f1b4-11e5-8345-b164c2298aeb.png)

**Comment by iwarner** [comment]
Cant you use the icon stacking to achieve this ?

**Comment by tagliala** [comment]
Sorry, I'm going to close this one for the moment because we should need `icon-fie-currency-*`

Please take a look at this blogpost http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/
