### ISSUE TITLE
Icon request: fa-customer-details

### ISSUE THREAD

**Issue by schoutenzekerheid** [FortAwesome/Font-Awesome#8820]
Hi all,

We need an icon for Customer or User Details, like:
![image](https://cloud.githubusercontent.com/assets/17614935/14014841/640726d0-f1b5-11e5-94c4-8afe88aec478.png)

Thnx in advance!

**Comment by tagliala** [comment]
duplicate of #825 , please +1 that request

closing here

**Comment by bcosca** [comment]
Why close both #8820 and #825 when they cross-reference each other and both issues are not addressed?
