### ISSUE TITLE
Icon request: icon-tripadvisor-square

### ISSUE THREAD

**Issue by matheusjardimb** [FortAwesome/Font-Awesome#8823]
Tripadvisor needs a square version. 
When placing multiple social media logos alongside it looks not good by now.

![image](https://cloud.githubusercontent.com/assets/468794/14016104/ad57effe-f19c-11e5-9046-fc2fcf3dcbda.png)

**Comment by PitaKebab** [comment]
+1

**Comment by stephenyeargin** [comment]
Per #18180, this can be closed off as the company asked for it to be removed entirely.

**Comment by tagliala** [comment]
@stephenyeargin yes, thanks
