### ISSUE TITLE
Icon Request: fa-referee

### ISSUE THREAD

**Issue by ucu13** [FortAwesome/Font-Awesome#8829]
Hello,

Is possible to add a group of new icons? I want to use them in football(soccer) web page.
This page is more for referee.

![cm1-o](https://cloud.githubusercontent.com/assets/6666206/14045968/c46a4dee-f2a6-11e5-9325-b17f74cc682f.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

You should consider a custom build and merge Font Awesome with a football/soccer related set: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

Refers to #5428

Closing here
