### ISSUE TITLE
Icon request: fa-user-check

### ISSUE THREAD

**Issue by palatineon** [FortAwesome/Font-Awesome#8837]
It would be nice to have icons for confirmed or approved items.
![person_confirmed](https://cloud.githubusercontent.com/assets/5436359/14065116/f1b6a1d6-f41c-11e5-924b-965afacf6871.jpg)

**Comment by tagliala** [comment]
dup of #6053, refersto #1181 . In #1181 you will find a solution

**Comment by palatineon** [comment]
Hello,
I'm coming from SAP web Uis. Due to be very close to business objects like orders, requests, confirmations, approvals, workflow items etc. , SAP has decided to have differen icons for each. In my example, the proposed solution from your side with a clipboard and checklist reminds me to an order (oveview of checked orders for example) rather than user required confirmations and requests in a queue. Therefore my suggestion#8837,  #8842, #8843 in order to have one homogenous group of icons in addition to remove user, add user etc.. I also need an icon for "manager" and "HR position"...

**Comment by tagliala** [comment]
@palatineon thanks for your clarification

Font Awesome is supposed to work for a generic web application. Of course a small subset of user related icons is fine to have and all individual requests asking for a specific user icon are legit.

A comprehensive set of icons dealing with users is a request that is hard to implement for Dave and to manage for me.

I advise a couple of options, both related to #1181:
* Overlay with plain css (approach 3)
* Use [fontawesome-actions](https://github.com/nyon/fontawesome-actions) to build a set of user related icons and merge them with fontawesome: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome (approach 2)
