### ISSUE TITLE
Icon request: fa-user-approval

### ISSUE THREAD

**Issue by palatineon** [FortAwesome/Font-Awesome#8838]
It would be nice to have an icon for required approvals or approvals in general.

![person_approval](https://cloud.githubusercontent.com/assets/5436359/14065130/5167620a-f41d-11e5-92ff-17c42de2daa0.jpg)

Could be a version of icon request #8837 (fa-user-check) in order to differ between single confirmation and multi confirmation.

**Comment by tagliala** [comment]
I'm not convinced of this request.

It looks like #8842, "icon for required approvals" vs " list of requests to be approved"

I would go for `fa-user-list-o` if you need something looking almost like that. You could also +1 #1230 . If we are talking about "pending requests", an action which requires attention, I would go for `fa-user-exclamation` 

I'm going to close this one at the moment

Refers to #1181
