### ISSUE TITLE
Icon request: icon-napster

### ISSUE THREAD

**Issue by p33k** [FortAwesome/Font-Awesome#8840]
Napster logo would be nice

**Comment by DaAwesomeP** [comment]
Napster isn't a thing anymore. It's now this: http://www.rhapsody.com/napster

**Comment by tagliala** [comment]
@DaAwesomeP thanks

Closing here

**Comment by shinyidol** [comment]
@tagliala Could this be revisited as Rhapsody has now become Napster globally. https://www.engadget.com/2016/06/14/goodbye-rhapsody-hello-napster/

**Comment by shinyidol** [comment]
Added the PNG and SVG(in zip) of the Napster logo.
![napster-head-black-icon](https://cloud.githubusercontent.com/assets/1386146/17682691/1367ed86-6302-11e6-9c7c-69ea4c494a3c.png)

[Napster-head-b:w-logo.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/419154/Napster-head-b.w-logo.svg.zip)
