### ISSUE TITLE
Icon Request: fa-football/fa-basketball/fa-icehockey

### ISSUE THREAD

**Issue by budik21** [FortAwesome/Font-Awesome#8841]
I would like to ask you for creating a set of sport's icon. I will really appreciate icons for football/basketball/icehockey as a picture of football ball/basketball ball/ice hockey puck.

Thanks for your effort.
Radek Budař

**Comment by tagliala** [comment]
I'm going to consider this a duplicate of #714 , please +1 that request

closing here
