### ISSUE TITLE
Icon request: fa-user-requests

### ISSUE THREAD

**Issue by palatineon** [FortAwesome/Font-Awesome#8842]
I'm looking for an icon to be used for outstanding approvals (e.g. list of requests to be approved).
![user_confirmationlist](https://cloud.githubusercontent.com/assets/5436359/14073874/c73e8cc4-f4cc-11e5-9c1c-1d923b9608a4.jpg)

**Comment by tagliala** [comment]
I'm not convinced of this request.

I would go for `fa-user-files-o` if you need something looking almost like that. If we are talking about "pending requests", an action which requires attention, I would go for `fa-user-exclamation` 

I'm going to close this one at the moment

Refers to #1181

**Comment by palatineon** [comment]
Please check my comments on #8837.
