### ISSUE TITLE
Icon request: fa-user-with-clock

### ISSUE THREAD

**Issue by palatineon** [FortAwesome/Font-Awesome#8843]
Hello,

I'm looking for an icon to indicate waiting for an user action / confirmation (like outstanding requests).
![user_waiting](https://cloud.githubusercontent.com/assets/5436359/14073931/516f3998-f4cd-11e5-9d80-49439dad4ff2.jpg)

This icon could be done in conjunction with #8842 (fa-user-requests).

**Comment by tagliala** [comment]
Refers to #1181 . I strongly advise to consider #1181 for all these requests

**Comment by palatineon** [comment]
I agree if we decide to go with an overlay technique for add, remove, wait etc.., the clock is only one additional usage.

**Comment by tagliala** [comment]
@palatineon you will find overlay techniques in #1181

**Comment by tagliala** [comment]
I'm going to close this and fix #1407, that is the same request
