### ISSUE TITLE
Icon request: fa-user-sitemap

### ISSUE THREAD

**Issue by palatineon** [FortAwesome/Font-Awesome#8854]
In addition to #8853, I like to have an icon for HR position assignment.
Required for example in HR / user authorization related applications for position based assignments.

![user_position](https://cloud.githubusercontent.com/assets/5436359/14125453/968c03aa-f60b-11e5-92b6-a32a38f05106.jpg)

**Comment by tagliala** [comment]
Related to #1181

**Comment by tagliala** [comment]
Let's use #12060
