### ISSUE TITLE
Icon request: icon-street light

### ISSUE THREAD

**Issue by angelaz87** [FortAwesome/Font-Awesome#8857]
I would love a street light silhouette please. 
![streetlight1](https://cloud.githubusercontent.com/assets/18169532/14145462/994eb7ec-f659-11e5-9820-674bf337917a.jpg)
![ntexggkgc](https://cloud.githubusercontent.com/assets/18169532/14145465/9ad0ddca-f659-11e5-9129-51157610cea6.png)

**Comment by aethior** [comment]
Duplicate or related #16479.

cc/ @tagliala
