### ISSUE TITLE
Required Some Font-Awesome Icons

### ISSUE THREAD

**Issue by rpatil** [FortAwesome/Font-Awesome#8861]
1. Sale
2. Fashion
3. Recharge
4. Travel
5. Exclusive
6. Food
7. Electronics
8. Groceries

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
> Include a few use cases for your requested icon. How do you plan on using it?
> Attach a single color image or two that represent the idea you're going for.
> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
