### ISSUE TITLE
Icon request: icon-tracking

### ISSUE THREAD

**Issue by stevenyhof** [FortAwesome/Font-Awesome#8866]
I used to create an image for feet for "tracking report" for marketers. Things like tracking email opens or clicks, or when a user clicks on something in a CRM a number of times, etc. The icon will tell users this is where you locate tracking information

![fee1](https://cloud.githubusercontent.com/assets/668786/14177418/319e3840-f724-11e5-8d2f-841a46a52e35.jpg)
![feet2](https://cloud.githubusercontent.com/assets/668786/14177419/319e8d68-f724-11e5-9c12-7c6d3bcd9567.jpg)

**Comment by tagliala** [comment]
footsteps is a dup of #3175, please +1 that request 

closing here
