### ISSUE TITLE
Icon request: fa-activate - fa-deactivate

### ISSUE THREAD

**Issue by ArabCoders** [FortAwesome/Font-Awesome#8868]
Hello,

we could use an extra two icons to indicate enabling or disabling of an item, you could take cue from these open source icons

https://www.iconfinder.com/icons/763446/circle_forbidden_no_outline_icon#size=128
https://www.iconfinder.com/icons/646195/done_ok_right_success_tick_valid_yes_icon#size=128

**Comment by tagliala** [comment]
I think

http://fontawesome.io/icon/check-circle-o/ and http://fontawesome.io/icon/times-circle-o/ do the job

closing here

**Comment by gitkumarhub** [comment]
Based on your suggestion, I prefer "fa-check" and "fa-times". Thanks tagliala.
