### ISSUE TITLE
Icon request: icon-anobii

### ISSUE THREAD

**Issue by amowu** [FortAwesome/Font-Awesome#887]
http://www.anobii.com/

a book share website, thanks!

**Comment by gellina** [comment]
i need it too!

**Comment by hou26** [comment]
Anobii is a social site about books. It's popular in Taiwan, Hong Kong, and Italy.
![logo_app](https://cloud.githubusercontent.com/assets/13068436/11993050/d1cfa312-aa67-11e5-81bb-fe3a2b42902d.png)
Please add it~
