### ISSUE TITLE
Icon request: icon-yoga1, icon-yoga2, icon-yoga3, icon-yoga4, icon-yoga5, icon-yoga6

### ISSUE THREAD

**Issue by y-o-ga** [FortAwesome/Font-Awesome#8885]
I have made a yoga website and need 6 icons related to yoga positions.
Any icons would be very much appreciated.

**Comment by tagliala** [comment]
hi,

unfortunately I have to close this one. It is fine to have a single icon representing yoga (#6032) but a comprehensive set of icons related to yoga is out of scope: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
