### ISSUE TITLE
Icon Request: fa-

### ISSUE THREAD

**Issue by gumboeater1** [FortAwesome/Font-Awesome#8890]
Hi,
I need your help. Can you create a series of sports related icons? Specifically for boys and girls sports? Even more specifically for youth soccer and basketball?

Right now i am using technical icons (cogs and spirals) to represent each heading, which looks really odd, but currently nothing remotely exists with the exception of a male/female gender icons.

http://www.lamorindabasketballacademy.com

Thanks for your consideration.
lawrence

**Comment by tagliala** [comment]
Hi,

as per [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

> Please do not request comprehensive sets of icons related to a very specific field.

Please consider a custom build, merging Font Awesome with a sport-related font: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by gumboeater1** [comment]
Why is this request a problem.?..you make icons...I bought a Wordpress template that forces me to use ONLY your icons....I thought with so many icons they must have some sports related ...but no. 

Can you suggest an icon work around for my template problem?

Regards,
Lawrence 
Owner/Creative Director
mckendell design
Www.mckendelldesign.com
