### ISSUE TITLE
icons not showing up on some pages

### ISSUE THREAD

**Issue by generic8** [FortAwesome/Font-Awesome#8896]
hello
i have an issue with icons not showing up on some pages. 
they're in the text (html) of my header widget and no plugin installed. it's working in general, but on three pages there's no icon in the header. 
my page is www.mueller-broker.ch
icons are not showing up on www.mueller-broker.ch/netzwerk, www.mueller-broker.ch/impressum and www.mueller-broker.ch/datenschutz

i would really appreciate your help on this!
thanks

**Comment by My1** [comment]
if you mean the phone and envelope icons I dont see a problem.

**Comment by tagliala** [comment]
Not having issues here, please notiche that a plugin is loading an outdated version of Font Awesome

```
http://www.mueller-broker.ch/wp-content/plugins/font-awesome/assets/css/font-awesome.min.css?ver=3.2.1
```

**Comment by My1** [comment]
small question btw, why does the CSS file get a GET parameter? CSS is iirc plaintext with no room for that stuff...
