### ISSUE TITLE
Icon Request: fa-restore

### ISSUE THREAD

**Issue by smileysoums** [FortAwesome/Font-Awesome#8897]
I would like a 'restore' icon that has a bit more significance than the 'undo' icon.  For example, we are using the refresh icon and need a restore icon next to it.  Using just the 'undo' appears to be very confusing.  So an icon with a bit more 'character' and uniqueness might help.  I'm attaching one i found online for reference.

Thank you!
![restore](https://cloud.githubusercontent.com/assets/18298557/14304144/287515dc-fb65-11e5-882b-13acc16a4787.png)

**Comment by tagliala** [comment]
Already here: http://fontawesome.io/icon/history/
