### ISSUE TITLE
Certain characters are being replaced when using FontAwesome together with other fonts

### ISSUE THREAD

**Issue by katemihalikova** [FortAwesome/Font-Awesome#8899]
I'm using `font-family: FontAwesome, OtherFonts, sans-serif;` to allow having icons inside any text, FontAwesome is put first to fix problems with some fonts that define their own characters in PUA, i.e. ligatures. When using this setup, I'm experiencing that certain characters are being replaced by spaces, that come from FontAwesome font file.

These characters include most importantly `U+00A8 ¨`, `U+00A9 ©`, `U+00AE ®`, `U+00B4 ´`, `U+00C6 Æ`, `U+2122 ™`, `U+221E ∞`, `U+2260 ≠` and also few space characters. Their definition can be found in svg font [here](https://github.com/FortAwesome/Font-Awesome/blob/master/fonts/fontawesome-webfont.svg?short_path=d05688e#L12).

Working example on [codepen](http://codepen.io/katemihalikova/pen/yOPwgQ?editors=1000) in the `Broken characters` column.

Possible fixes:
- remove all characters outside PUA from font files
- use [`unicode-range`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range) property of `@font-face` in css to limit the font to PUA

**Comment by tagliala** [comment]
I don't know if this should be a supported use-case, maybe a custom build is a better choice

About unicode-range, it seems to not be widely supported: http://caniuse.com/#feat=font-unicode-range

@davegandy ?

**Comment by davegandy** [comment]
Not a supported use case, and I don't expect it to be in version 4.
