### ISSUE TITLE
Icon Request: fa-onedrive and fa-googledrive

### ISSUE THREAD

**Issue by xenomarz** [FortAwesome/Font-Awesome#8904]
It would be great if you could add an icon for Microsoft's 'OneDrive' and Google's 'Google Drive'.

Thanks!

**Comment by tagliala** [comment]
Duplicate of #835 and #2887, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by danpezzin-social** [comment]
+1

**Comment by danpezzin-social** [comment]
+1
