### ISSUE TITLE
Icon request: ResearchGate

### ISSUE THREAD

**Issue by catarinavp** [FortAwesome/Font-Awesome#8907]
Hi,

I would love to have the icon of ResearchGate (https://www.researchgate.net) in your awesome font! They have a fairly plain logo that fits the style of your font.

Thanks heaps!

**Comment by tagliala** [comment]
Duplicate of #3634 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
