### ISSUE TITLE
Icon request: icon-viewfinder

### ISSUE THREAD

**Issue by Varkal** [FortAwesome/Font-Awesome#8914]
Hello, 

I look for an icon like this one : https://cdn0.iconfinder.com/data/icons/crime-story/128/target_shield_viewfinder_pinnule_dative-512.png

This can be useful in web video games for example

**Comment by PeterShaggyNoble** [comment]
Would http://fortawesome.github.io/Font-Awesome/icon/crosshairs/ do the job for you?

**Comment by Varkal** [comment]
Sorry, I hadn't seen this one... Of course, this one do the job 

Thanks !

**Comment by tagliala** [comment]
Closing here
