### ISSUE TITLE
Icon request: Glide

### ISSUE THREAD

**Issue by truls1502** [FortAwesome/Font-Awesome#8917]
Hi,

It is app called Glide. It is an useful "live video messaging"-app, especially it is now very popular for deaf or sign language community or anyone who want to send video message. It would be great to add this on near contact form or similar where anyone or the clients can contact through to send a video message.

Check out [Glide resources](http://www.glide.me/resources) for logo. :)

**Comment by truls1502** [comment]
Hi @tagliala could you add this request to Brand icons? @davegandy, is it possible to add on 4.6 version?

**Comment by davegandy** [comment]
@truls1502 You've been extremely helpful this release. Of course I'll add it. :)

**Comment by davegandy** [comment]
Added to 4.6.0-wip branch. Closing.
