### ISSUE TITLE
Icon request: icon-radio

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#892]
Splitting out from #10.

**Comment by G-Driver** [comment]
+1

**Comment by spoonmuppet** [comment]
+1 please.

**Comment by eevfae** [comment]
+1

**Comment by nlsbln** [comment]
+1

**Comment by rampmaster** [comment]
+1

**Comment by RouHim** [comment]
+1

**Comment by Yethroy** [comment]
+1

**Comment by subzerokangaroo** [comment]
+1

**Comment by awise882** [comment]
+1

**Comment by awise882** [comment]
Having some icons for media & marketing would be amazingly helpful.  TV - Broadcast, TV - Cable, TV - Radio for advertising would be an awesome addition.

**Comment by bistory** [comment]
+1

**Comment by Kunal-Vyas** [comment]
+1

**Comment by AaronX** [comment]
+1

**Comment by Rad77** [comment]
+1

**Comment by erkanyildiz** [comment]
+1

It's been 5 years, and still no radio icon. Unbelievable.

**Comment by shulcsm** [comment]
+1

**Comment by elmer-t** [comment]
+1

**Comment by matematik7** [comment]
+1

**Comment by sensibleworld** [comment]
We now have a couple of radio icons: https://fontawesome.com/icons/radio?style=solid and https://fontawesome.com/icons/radio-alt?style=solid
