### ISSUE TITLE
New icon request :p

### ISSUE THREAD

**Issue by Rebsiont** [FortAwesome/Font-Awesome#8923]
Hey guys

I would love it if you guys could make some more icons for my local website (a website to link to all my synology nas programs)
i really would like it if you could make the following icons (if possible ofcourse)
- Sonarr logo icon
- Couch potato logo icon
- Transmission logo icon
- Synology Photostation
- Plex media server logo icon
- Synocommunity Headphones logo icon
- Synology Dsm logo icon

really would be nice , but no pressure at all guys :D lol

**Comment by tagliala** [comment]
Sorry, I need to close this request.

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by Rebsiont** [comment]
ok no problem :)

was just a friendly request [&#X1f603]

________________________________
Van: Geremia Taglialatela <notifications@github.com>
Verzonden: vrijdag 8 april 2016 16:02
Aan: FortAwesome/Font-Awesome
CC: Robbert Braeken
Onderwerp: Re: [FortAwesome/Font-Awesome] New icon request :p (#8923)


Sorry, I need to close this request.

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

  *   Please do not request comprehensive sets of icons related to a very specific field.
  *   Please search to see if your icon request already exists. If a request is found, please +1 that one.
  *   Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
  *   Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
  *   Attach a single color image or two that represent the idea you're going for.
  *   Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. :)

-
