### ISSUE TITLE
Icon Request: snazzy-arrow

### ISSUE THREAD

**Issue by tb9jen** [FortAwesome/Font-Awesome#8926]
![snazzy-arrow](https://cloud.githubusercontent.com/assets/2207103/14389816/4ef2012e-fd82-11e5-859c-9efea5b65103.jpg)
I was using these in a project and hoped to find them in Font Awesome but alas they are not yet. I can send you svg if you want to add them. I wasn't sure what to call them, so I called it snazzy-arrow but of course feel free to rename them.

**Comment by aethior** [comment]
@tagliala `arrows (category)` label for this request?

**Comment by tagliala** [comment]
Given that:
- We have a lot of new arrows https://fontawesome.com/search?q=arrow&s=solid%2Cbrands
- There are no upvotes
- The use case for this request is not clear

I prefer to close this request

Feel free to fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md) and clarify why that different style is needed

A good better fontawesome-ish name could be `location-arrow-up, location-arrow-down` as per https://fontawesome.com/icons/location-arrow?s=solid
