### ISSUE TITLE
Icon request: icon-brightness-up, icon-brightness-down

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#893]
Splitting out from #10.

**Comment by G-Driver** [comment]
+1

**Comment by valos** [comment]
+2 for contrast and brightness

**Comment by nilsschmidthamburg** [comment]
+1

**Comment by ukmoose** [comment]
+1

**Comment by gioce90** [comment]
+1

**Comment by cyberseraphic** [comment]
+1

Would like both separate brightness up/down and contrast up/down
AND
Brightness/Contrast up/down combined, e.g. 
![image-contrast-icon-75334](https://cloud.githubusercontent.com/assets/16676197/18978667/450c8a98-8708-11e6-970e-07c9f71f95a3.png)

**Comment by affitz** [comment]
+1

**Comment by stasoft91** [comment]
+1
