### ISSUE TITLE
Font-Awesome Icon as part of a Logo

### ISSUE THREAD

**Issue by LoyalBen** [FortAwesome/Font-Awesome#8931]
Hello!
First at all let me say that i love the Font Awesome Icons and i work a lot with them in different projects. Thank you for creating them! :+1: 
My question is: Can I use a Icon as Part of a own Logo? Is there any law against it?
Thank you! 

Best,
Benjamin

**Comment by truls1502** [comment]
Check out [Fort Awesome](http://www.fortawesome.com), there you can upload your own logo or whatever your own custom icons you want to use on your website(s). :)

**Comment by PeterShaggyNoble** [comment]
I think what @LoyalBen is asking is can he use one or more FontAwesome icons in the design of a logo.

If that is indeed what you're asking, Ben, then have a look at the FA [licensing documents](http://fortawesome.github.io/Font-Awesome/license/).

**Comment by truls1502** [comment]
@PeterShaggyNoble You have right.
@LoyalBen just look away from my post, I just misunderstood it.

**Comment by tagliala** [comment]
Apparently it is permitted by SIL: http://scripts.sil.org/FontFAQ_use

Search for "logo" in that page

Closing here, hope it helps

**Comment by davegandy** [comment]
Heck, I don't mind if folks use Font Awesome icons as their logos. Go for it. :)

**Comment by LoyalBen** [comment]
Thank you all for answering! Font-Awesome is just awesome! ;)

**Comment by serbixote** [comment]
Hey guys, is this still the case?

**Comment by phenomlab** [comment]
> Hey guys, is this still the case?

If @davegandy himself says it's ok, then it is (unless he changed his mind of course) - he's the creator of Font Awesome 👍
