### ISSUE TITLE
Doubble life-bouy on the icon page

### ISSUE THREAD

**Issue by jensz12** [FortAwesome/Font-Awesome#8937]
![screenshot_20160410-140240](https://cloud.githubusercontent.com/assets/1682377/14410059/0c532916-ff25-11e5-9aa1-be6dc8c55a2c.png)

**Comment by jensz12** [comment]
Ohhh i did not see that it was spelled different!

**Comment by tagliala** [comment]
@jensz12 life-bouy is a typo and it will be removed in 5.0.0
