### ISSUE TITLE
Compatibility for HTML Mail

### ISSUE THREAD

**Issue by thib1235** [FortAwesome/Font-Awesome#8939]
I hope this is the right place to ask...

I am trying to write HTML **mail template** using font awesome beautiful icons. However, Thunderbird does not show any icons.

I am including the font awesome icons using:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">`

Then using them with:
`<ul class="fa-ul">
    <li><i class="fa-li fa fa-user fa-fw leftAligned"></i>My name</li>
</ul>`

What is the problem?

**Comment by dbarlett** [comment]
font-awesome.css uses `@font-face`, but Thunderbird [only supports `@import`](https://www.campaignmonitor.com/dev-resources/will-it-work/webfonts/).

**Comment by tagliala** [comment]
@dbarlett thanks

Just find a list of clients that support `@font-face`: https://www.campaignmonitor.com/dev-resources/will-it-work/webfonts/

Closing here

**Comment by dlgrigore** [comment]
Hello,
I need to integrate font awesome 5 in email HTML code. Is there any hint that could fix the problem and to work nice in Thunderbird? 
Thank you.

**Comment by gdvalderrama** [comment]
@dlgrigore as far as I've read the recommendation is to convert your icons to images. For example with http://fa2png.io/r/font-awesome/
