### ISSUE TITLE
request new icon- fa building

### ISSUE THREAD

**Issue by yellodrover** [FortAwesome/Font-Awesome#8941]
Hi, could you create an awesome icon for the construction/property development site I'm creating for a local business? I'm thinking something like this - (this is from istock)
![land development](https://cloud.githubusercontent.com/assets/18386862/14414456/8ba2ed6c-ffd6-11e5-8536-5c1b96be4f2d.png)

Thankyou!

**Comment by tagliala** [comment]
we already have a `fa-building`: http://fontawesome.io/icon/building/

**Comment by sensibleworld** [comment]
We have a few options that might work for this: https://fontawesome.com/icons?d=gallery&c=buildings
