### ISSUE TITLE
Icon request: icon-Motion_Picture_Camera

### ISSUE THREAD

**Issue by JohnDrew2** [FortAwesome/Font-Awesome#8947]
FA has lots of media devices, but none of the following:

Motion Picture Camera
Motion Picture Film Reel
Clapper Board
Professional-looking Video Camera, not the current consumer version
Analogue VU meter

![motion_picture_camera](https://cloud.githubusercontent.com/assets/17677781/14436273/e599210c-ffe9-11e5-8676-756b29fa4d4e.png)

![motion picture film reel](https://cloud.githubusercontent.com/assets/17677781/14436287/f00d6968-ffe9-11e5-9a05-86b2cd8dc080.png)

![clap board](https://cloud.githubusercontent.com/assets/17677781/14436418/983e3662-ffea-11e5-91a7-87db06a8a086.png)

![vu meter](https://cloud.githubusercontent.com/assets/17677781/14436423/9fac9006-ffea-11e5-93f0-67f000388045.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please +1 that one.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
> Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

clapper board: #3130 
motion picture camera: #990

please open new individual requests for missing icons and please specify why film reel should be implemented alongside http://fontawesome.io/icon/film/
