### ISSUE TITLE
v4.6: Invalid US-ASCII character "\xC3"

### ISSUE THREAD

**Issue by srk289** [FortAwesome/Font-Awesome#8953]
Our app just updated to 4.6 from 4.5 and since SASS is throwing the below issue
Error: Invalid US-ASCII character "\xC3"
       on line 29 of src/main/webapp/static/bower_components/font-awesome/scss/_mixins.scss
       from line 7 of src/main/webapp/static/bower_components/font-awesome/scss/font-awesome.scss

Any one else see the same issue?

**Comment by tagliala** [comment]
```css
// Only display content to screen readers. À la Bootstrap 4.
```

:neutral_face:

**Comment by lawrencepn** [comment]
yep, same issues here on OSX. investigating.

**Comment by tagliala** [comment]
@lawrencepn i'm pretty sure it is the `À`. Try to change that character

**Comment by davegandy** [comment]
Oh my goodness. When I typed that, I was worried something might barf. Goodness.

Fixing.

**Comment by tagliala** [comment]
@srk289 @chrism-dp @lawrencepn please give a try to the `4.6.1-wip` branch. Let me know

**Comment by davegandy** [comment]
Should be good to go on the 4.6.1-wip branch. Closing for now, let me know if this doesn't get it!
