### ISSUE TITLE
Icon request: Set of icons for Gambling Industry

### ISSUE THREAD

**Issue by Zhastreaus** [FortAwesome/Font-Awesome#8954]
I would like to request for set of icons in the gambling industry.
Samples of these icons are Dice(which issue #2622 requested), Chips, and Cards.

I'm planning to use it on my work.

![](http://thumbs.dreamstime.com/z/casino-gambling-icons-image-illustration-can-be-scaled-to-any-size-loss-resolution-37496154.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Dice: the issue you found
Chip:  #1004

Please check this: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting
