### ISSUE TITLE
Icon request: icon-trailer

### ISSUE THREAD

**Issue by willemste** [FortAwesome/Font-Awesome#8956]
Hi

I will appreciate it if it is possible to make a icon of a trailer.
I have made something, see picture below. I'm making my own website and would like to use it.
This is all new to me. 
![trailer](https://cloud.githubusercontent.com/assets/18417455/14456385/ee60b5be-00a4-11e6-8875-7f81773001b6.png)

**Comment by tagliala** [comment]
Duplicate of #7369  please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by willemste** [comment]
I cant find trailer,
the other one is "caravan"  it is not the same as a trailer

**Comment by tagliala** [comment]
caravan: #5429
trailer: #7369

**Comment by willemste** [comment]
I cant find it in this list: http://fontawesome.io/icons/

If I use other code than in this list the icon does not work in my website

**Comment by tagliala** [comment]
@willemste this is a duplicate request, so this icon is not yet implemented

**Comment by willemste** [comment]
@tagliala how do I get it implemented?

**Comment by tagliala** [comment]
take a look at https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
