### ISSUE TITLE
icon-request: icon-telegram

### ISSUE THREAD

**Issue by mbsmt** [FortAwesome/Font-Awesome#8957]
Hi. As you know, Telegram is a a fast growing communication mobile app these days. But there is not any made icon in font-awesome.
Please add it to your valuable collection.

This is its icon :
https://telegram.org/img/t_logo.png

Thank you.

**Comment by PeterShaggyNoble** [comment]
Dupe of [#3034](https://github.com/FortAwesome/Font-Awesome/issues/3034)
