### ISSUE TITLE
Icon Request: all sports category

### ISSUE THREAD

**Issue by baykorhan** [FortAwesome/Font-Awesome#8959]
Hi,

font awesome is very nice but some categories are very poor.

for example; all sports categories..

football, basketball, volleyball, baseball, rugby, tennis, hockey, bowling, billiards etc.

Thank you.

**Comment by PeterShaggyNoble** [comment]
There have been many requests for different sports icons in the past, you should search for those and +1 them.

**Comment by tagliala** [comment]
as @PeterShaggyNoble pointed out, there are many requests for sports.

I would suggest you to +1 #714 , but #714 is  a poor request against our contributing guidelines.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

However, it is an old request with a lot of +1s and I don't feel confident to close that one.
