### ISSUE TITLE
fa-blind cane not always visible

### ISSUE THREAD

**Issue by PeterShaggyNoble** [FortAwesome/Font-Awesome#8965]
The cane on fa-blind may need to be made thicker as, at smaller sizes (e.g., the smallest icon on [here](http://fortawesome.github.io/Font-Awesome/icon/blind/), it's very difficult to see so it just looks like a guy walking.

**Comment by tagliala** [comment]
seems fixed to me

https://jsfiddle.net/tagliala/yxqqchjs/1/
