### ISSUE TITLE
Icon: Reading Glasses. 

### ISSUE THREAD

**Issue by Spark3000** [FortAwesome/Font-Awesome#8967]
It's a crucial omission. Useful for:
• Blog article
• Read this
• View post
• Long form text
• Just plain glasses

**Comment by tagliala** [comment]
Duplicate of #1043 , scheduled for 5.0.0, but please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by Spark3000** [comment]
Sure. And I am there. The issue just  needed a bump. It's 3 years old and was meant to be included in 3.2 https://github.com/FortAwesome/Font-Awesome/issues/1043#issuecomment-17752038

Thanks
