### ISSUE TITLE
Update Packagist package

### ISSUE THREAD

**Issue by mirko-pagliai** [FortAwesome/Font-Awesome#8968]
Hi guys,

I just wanted to tell you that on Packagist the package is stopped to 4.5.0 release.

**Comment by shehi** [comment]
Why would someone need a front-end package inside a back-end package repo?!

**Comment by mirko-pagliai** [comment]
Perhaps because it is convenient for someone like that?
Why else font-awesome has been added on Packagist?

Since it was added on Packagist, I am pointing out that it is not updated.

Moreover, you can set it so that it automatically update.

What is the use of your answer?

**Comment by shehi** [comment]
@mirko-pagliai , my answer doesn't have to have a use - I am not package maintainer :) Font-awesome is also added to Bower, yet no mention of it in readme. The same goes for Packagist. But that wasn't my question actually, I just wondered why one would use some package from totally unrelated source.

**Comment by mirko-pagliai** [comment]
I still do not understand your question.
What do you mean with "some package from totally unrelated source"?

I have some software in php that use different libraries, including font-awesome. With composer, I do the upgrade.

**Comment by shehi** [comment]
Forget it :) Have a good day!

**Comment by tagliala** [comment]
as far as I can tell, the package at this website: https://packagist.org/packages/fortawesome/font-awesome is not officially maintained by Font Awesome

**Comment by mirko-pagliai** [comment]
I was referring to this and this is the official package
https://packagist.org/packages/fortawesome/font-awesome

It has just been updated. I do not know why. Anyway thanks.
