### ISSUE TITLE
Icon request: icon-envelope-open, icon-envelope-open-o

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#897]
Splitting out from #16.

**Comment by killface** [comment]
+1 ... how does this still not exist?

**Comment by gtonioli** [comment]
+1

**Comment by Ediiik** [comment]
+1

**Comment by ppdeassis** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by timvoet** [comment]
+1

**Comment by Nyaskpi** [comment]
+1

**Comment by leoncottell** [comment]
+1

**Comment by rafaela-bernardelli** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by azianfr** [comment]
+1

**Comment by sygn** [comment]
+1

**Comment by RobbyCowell** [comment]
+1 please add this!

**Comment by mb324-unikent** [comment]
+1

**Comment by vivaladan** [comment]
+1

how has this been open so long without being added?

**Comment by G-Driver** [comment]
@vivaladan maby cuz this request doesnt have enough votes ?

**Comment by wang-changhong** [comment]
+1

**Comment by miksh7** [comment]
+1

**Comment by ka7eh** [comment]
+1

**Comment by marc1n** [comment]
+1

**Comment by weibangtuo** [comment]
+1

**Comment by paulste** [comment]
+1

**Comment by four-oh-four** [comment]
+1

**Comment by Kyttias** [comment]
+1 

For now I suppose I'll have to add a class that'll make my read messages dimmer than my unread ones. A separate icon would be appreciated still, however!

**Comment by rogertheshrubber** [comment]
+1

**Comment by oletok** [comment]
+1

**Comment by sytong** [comment]
+1

**Comment by justin-nguyen** [comment]
+1

**Comment by uxtx** [comment]
+1

**Comment by giorrrgio** [comment]
:+1:

**Comment by elbartostrikesagain** [comment]
over 2 years... this must be a sick joke. +1

**Comment by adrianscott83** [comment]
+1

**Comment by jheadley** [comment]
+1

**Comment by hoblin** [comment]
+1

**Comment by ivankukobko** [comment]
+1

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by carlosmacias** [comment]
+1

**Comment by kelvio** [comment]
+1

**Comment by IMP1** [comment]
+1

**Comment by ardeearam** [comment]
+1

**Comment by flashinnl** [comment]
+1

**Comment by cakemasher2** [comment]
+1

**Comment by RodolpheGohard** [comment]
+1

**Comment by francescopitzalis** [comment]
+1

**Comment by c1moore** [comment]
+1

**Comment by lizzzzard** [comment]
+1

**Comment by simonfranz** [comment]
+1

**Comment by mageroya** [comment]
+1
how is this most basic thing not in there yet? I installed fa in hope of exactly this icon, because bootstrap does not have one either!

**Comment by dara0418** [comment]
+1

**Comment by felpsPnd** [comment]
+1

**Comment by clopezcapo** [comment]
+1!!!!

**Comment by rishitank** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by ArnaudDelafosse** [comment]
Definitely +1

**Comment by G-Driver** [comment]
+1

**Comment by JSoon** [comment]
+1 ~~~~~~~~~~~~~~~~~

**Comment by JSoon** [comment]
BTW, I'm surprised that this issue hasn't been resolved since 2013. !O!

**Comment by nIQnutn** [comment]
+1

**Comment by Kledal** [comment]
+1

**Comment by hellsing71** [comment]
+10000

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by jabarnes** [comment]
139th request
+1

**Comment by mariuszgaller** [comment]
+1

**Comment by mrReiha** [comment]
Absolutely +1

**Comment by herrherrmann** [comment]
+1

**Comment by phlegx** [comment]
:+1:

**Comment by olix21** [comment]
+1

**Comment by adis-me** [comment]
+1

**Comment by netiul** [comment]
+1

**Comment by ttamas7** [comment]
+1

**Comment by dedallus** [comment]
+1!!!!!

**Comment by Mattias1** [comment]
+1

**Comment by levanaalouche** [comment]
+1

**Comment by cuongnm53** [comment]
+ 1

**Comment by egivandor** [comment]
+1

**Comment by bahmany** [comment]
+1

**Comment by redayoub** [comment]
+1

**Comment by gusreyes01** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by kimras** [comment]
+1

**Comment by sancospi** [comment]
+1

**Comment by tmdude9586** [comment]
+ 1 this would be AWESOME (like font awesome awesome)

**Comment by georgethecoder** [comment]
+1

**Comment by ld33zy** [comment]
+1

**Comment by regepan** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by PeterMozesMerl** [comment]
+1

**Comment by zjwhitehead** [comment]
+1

**Comment by ScottSpittle** [comment]
+1

**Comment by gh0c** [comment]
+1

**Comment by lancetharper** [comment]
+1

**Comment by MVcodeartbr** [comment]
+1

**Comment by mwils** [comment]
+1

**Comment by bassarisse** [comment]
+1

**Comment by salarmehr** [comment]
+1

any feadback?

**Comment by alessandro1997** [comment]
+1

**Comment by victorlabigar** [comment]
+1

**Comment by estabij** [comment]
+1

**Comment by wrparra** [comment]
+1

**Comment by Macfresno** [comment]
+1.000.000

**Comment by yuridesnaijer** [comment]
+2

**Comment by abdlkrmdlgr** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by Externaluse** [comment]
+1, you'd make me a happy person.

**Comment by me-shaon** [comment]
+1

**Comment by giosoftware** [comment]
+1

**Comment by bahmany** [comment]
+1

**Comment by bahmany** [comment]
+1 how care ??

**Comment by drumichael611** [comment]
+1

**Comment by 2601-Srl** [comment]
+1

**Comment by mb324-unikent** [comment]
+1

**Comment by jordan-wright** [comment]
+1

**Comment by almssp** [comment]
+1

**Comment by jasel-lewis** [comment]
Proposal:

![fa-envelope-opened_proposal](https://cloud.githubusercontent.com/assets/2246068/12740475/8a180c14-c941-11e5-8986-8f3ede60661a.png)

![fa-envelope-opened-o_proposal](https://cloud.githubusercontent.com/assets/2246068/12740480/8f3387a0-c941-11e5-8677-9861f4b547e3.png)


Thank you!

**Comment by coje4** [comment]
+1

**Comment by lamellon** [comment]
+1

**Comment by dnavarrojr** [comment]
+1

**Comment by fahmidur** [comment]
+1

**Comment by alanmbyrne** [comment]
+1

**Comment by szada92** [comment]
+1

**Comment by rafaela-bernardelli** [comment]
Definitely +1

**Comment by 666netz** [comment]
+1

**Comment by felipeoriani** [comment]
+1 for the icon and the request made in Mar/2013!

**Comment by rodrigosendin** [comment]
+1

**Comment by olgashavrina** [comment]
+1

**Comment by mrmashal** [comment]
+1

**Comment by dmz006** [comment]
I'd also +1 this but it seems that almost 3 years in that the folks who make font-awesome have no desire to add this icon.

Anyone graphically inclined up for making a fork of Font-Awesome? I'm sure we've got several hundred developers here who would rather use that fork than the primary site just for that one icon.

**Comment by harmjanluth** [comment]
+2!!

**Comment by wahmal** [comment]
+1 please !!!

**Comment by cherrador** [comment]
+1

**Comment by dcsava** [comment]
+1 must be a reason to not have made one in all this time a reply would be appreciated I'm sure!

**Comment by Tylney** [comment]
+1 - reason for non-response might be that the icon is a vital icon that allows to distinguish between opened and unopened emails - maybe the developers don't open their emails.  Also we could try and get more upvotes by using social media sharing

**Comment by ellyjonez** [comment]
+1 !! still need this years later

**Comment by thj-dk** [comment]
+1

**Comment by zombieJ** [comment]
+1

**Comment by hpvd** [comment]
+1

**Comment by mjbeller** [comment]
+1

**Comment by renevanpelt** [comment]
+1

**Comment by baker42** [comment]
+1

**Comment by fr-ser** [comment]
+1

**Comment by ngouy** [comment]
rlly ? +1

plz ...

**Comment by ahardin** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by uli-weltersbach** [comment]
+1

**Comment by AndreLGava** [comment]
Hello guys

I love font awesome, but some icons that we need take a lot of time to be added to font awesome, so I decided to create an extenssion to make it easy , if you would like to use them , you can download this at https://github.com/AndreLGava/font-awesome-extenssion. fa-enveloper-open and fa-envelope-open-o was an icon that i used. If there are any problem please create an issue on the GitHub project

**Comment by M-Shahbaz** [comment]
+1

**Comment by othyn** [comment]
+1

**Comment by My1** [comment]
+1

**Comment by RoumedG** [comment]
+1

**Comment by othyn** [comment]
Same style, but with the letter flap open and a document half pulled out perhaps? Some thing like this, obviously following the more rounded FA style.

![example icon](https://cdn1.iconfinder.com/data/icons/hawcons/32/698362-icon-2-mail-envelope-open-128.png)

**Comment by isma0611** [comment]
+1

**Comment by dmz006** [comment]
I got notified about this link (https://github.com/AndreLGava/font-awesome-extension) on this thread but don't see it here. This may help some people here until FA decides to merge it.

**Comment by vincentkoeswanto** [comment]
+1

**Comment by carlosbutler** [comment]
+1

**Comment by kimras** [comment]
Nice... You should offer them to the Original FA project.
Thanks

On Sat, Apr 16, 2016 at 3:33 PM, André Luiz Gava <notifications@github.com>
wrote:

> Hello guys
>
> I love font awesome, but some icons that we need take a lot of time to be
> added to font awesome, so I decided to create an extenssion to make it easy
> , if you would like to use them , you can download this at
> https://github.com/AndreLGava/font-awesome-extenssion. fa-enveloper-open
> and fa-envelope-open-o was an icon that i used. If there are any problem
> please create an issue on the GitHub project
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/FortAwesome/Font-Awesome/issues/897#issuecomment-210815857>
>



-- 
Kim Rasmussen
geoQuestor IVS
Tel: +45 30500110

http://www.geoQuestor.com

**Comment by dmz006** [comment]
He should do a pull, update and submit it back. Actually anyone could probably do that now that he's got it put together.

**Comment by DanKing123** [comment]
Has anyone managed to get that extension to work?

I'm trying to convert it to sass, but am having trouble understanding how it works as an extension.
The css seems to just override the fa- classes, _replacing_ font awesome with font-awesome-extension (rather than extending it).

**Comment by julienfromentc** [comment]
+1

**Comment by Moykn** [comment]
+1

**Comment by mellat** [comment]
+10000

**Comment by RoumedG** [comment]
+1

**Comment by Roumed** [comment]
+1

**Comment by aadamsx** [comment]
Why hasn't this simple (yet important) icon been added in all this time?

**Comment by My1** [comment]
and it's a better choice than all the brands that nobody even knows

**Comment by chechsp** [comment]
+1

**Comment by Seelengrab** [comment]
+1

**Comment by devou33** [comment]
+1

**Comment by nadios** [comment]
+1

**Comment by devou33** [comment]
fa-envelope-open and fa-envelope-open-o
<img width="715" alt="screen shot 2016-06-29 at 9 25 51 am" src="https://cloud.githubusercontent.com/assets/7987602/16455956/c30e727e-3ddb-11e6-9226-b1235249e338.png">

---
From my request/proposal yesterday: fa-invitation and fa-invitation-o
<img width="703" alt="screen shot 2016-06-29 at 9 25 44 am" src="https://cloud.githubusercontent.com/assets/7987602/16455996/ef16eb26-3ddb-11e6-8b96-19986395b01f.png">

**Comment by aadamsx** [comment]
Reposting here, just in case:

@devou33 I don't have the existing closed envelope icon in front of me, do these matched the existing closed envelope icon?

What I'm looking for is simply: closed envelope if the message is not read, and open if it is read -- but they must match to look right.

Unfortunately, for much-too-long and for apparently no-good-reason, we've only had the closed envelope, so I've had to use color (dark/light) to represent read and unread messages.

**Comment by dukebrown** [comment]
+1

**Comment by kviktor** [comment]
+1

**Comment by mdrose** [comment]
+1

**Comment by thomasvnl** [comment]
+1

Would be a good addition to the Web Application Icons!

**Comment by juyod** [comment]
+1

**Comment by infernobass7** [comment]
+1

Could really use this one.

**Comment by raamtg** [comment]
+1

I have currently removed the entire function of "marking as read" just because I am missing this icon :(

**Comment by marcschneider123** [comment]
+1

**Comment by ddecs** [comment]
+1

**Comment by erikdaniel** [comment]
+1

**Comment by alsoknownasdrew** [comment]
+1

**Comment by iamkoby** [comment]
+1

**Comment by youlyst** [comment]
+1

**Comment by MitchTalmadge** [comment]
+1

**Comment by Szymod** [comment]
+1

**Comment by alexirwin** [comment]
+1

**Comment by computerichy** [comment]
+1

**Comment by Baudin999** [comment]
+1

**Comment by stavrianosy** [comment]
+1

**Comment by master-bob** [comment]
+1

**Comment by keesdewit82** [comment]
+1

Please add this icon

**Comment by dedess4242** [comment]
one more

**Comment by tillifywebb** [comment]
+1

**Comment by ChristophAnastasiades** [comment]
+1
Same here, need this for a "mark as read" feature. 😁

**Comment by korhan1** [comment]
+1

**Comment by felixjackson** [comment]
+1

**Comment by keesdewit82** [comment]
So many upvotes for years and years. We need this icon ;)

**Comment by davegandy** [comment]
These have been checked into the 4.7.0-wip branch:
<img width="822" alt="screenshot 2016-10-04 12 13 43" src="https://cloud.githubusercontent.com/assets/1076721/19082416/0fe8e51a-8a2c-11e6-9486-6adc27e1d6f9.png">
<img width="793" alt="screenshot 2016-10-04 11 57 34" src="https://cloud.githubusercontent.com/assets/1076721/19082421/15f593b8-8a2c-11e6-8345-c3388847d1c2.png">

Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!

**Comment by carlosbutler** [comment]
Thanks!

**Comment by olgashavrina** [comment]
Thank you so much! You are the best!

**Comment by keesdewit82** [comment]
Thats so awesome! Your the best.

**Comment by kirara** [comment]
I can't believe it, all hail Linode.

**Comment by cherrador** [comment]
Awesome!!! Thanks... That means Dave is back...

**Comment by Tylney** [comment]
Font AWESOME!

only took 3.5 years.  Sold the website by now, but cool its now available! :)

**Comment by aadamsx** [comment]
When will 4.7 be released?

**Comment by davegandy** [comment]
It's coming soon! Still working on open issues. You can see the milestone here: 
https://github.com/FortAwesome/Font-Awesome/issues?q=milestone%3A4.7.0+is%3Aclosed

**Comment by davegandy** [comment]
Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!

**Comment by davegandy** [comment]
Huge thanks to Linode for sponsoring the top 5 most requested icons being added to Font Awesome!

**Comment by dara0418** [comment]
Thanks very much.

**Comment by othyn** [comment]
Thank you so much for this! :+1:

**Comment by ngouy** [comment]
4 years later, finally ❤️
