### ISSUE TITLE
Icon Request: icon-digit

### ISSUE THREAD

**Issue by Yvan781** [FortAwesome/Font-Awesome#8978]
Hi,

Could you release digits from 0 to 9 please ?
If possible also from 00 to 99.

It would be useful in case we want to point to a specific server or a team, or maybe a day/month... :)

Thank you!

**Comment by tagliala** [comment]
Please use the stacking feature for this use case: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Refers to #5019 #2158 #6099
