### ISSUE TITLE
Icon request: icon-address-book

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#898]
Splitting out from #16 for better tracking.

**Comment by cyrilschumacher** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by FrancisVonGerven** [comment]
+1 Address Book (ring-binder icon)

**Comment by grantneufeld** [comment]
The vCard (.vcf) portion of this request overlaps with Icon Request #825

**Comment by reyx** [comment]
+1

**Comment by Nutzzz** [comment]
+1

**Comment by xintellion** [comment]
+1 Address Book
+1 vCard

**Comment by dangnelson** [comment]
+1 Address Book
+1 vCard

**Comment by pixelforscher** [comment]
+1 Address Book
+1 vCard

**Comment by rabrowne85** [comment]
+1 Address Book
+1 vCard

**Comment by pixelforscher** [comment]
this is … just awesome guys! Thanks a lot.

**Comment by beliys** [comment]
+1 Address book

**Comment by ericfirth** [comment]
+1 Address Book/Contacts

**Comment by barefootdeveloper** [comment]
I agree address book + vcard would be outstanding.

Plus thanks so much for your work on font-awesome!

**Comment by gwin003** [comment]
+1 for vCard

**Comment by Fishuu** [comment]
+1 for vCard, thanks!

**Comment by aWuttig** [comment]
+ 1 for vCard

**Comment by roddharris** [comment]
+1 for vCard.

**Comment by sanek4life** [comment]
+1

**Comment by iamchriswick** [comment]
Why does this keep getting closed? We need a vCard and/or address book icon

**Comment by pixelforscher** [comment]
Yes, Thank you. Needed. Please implement it soon.
Thank you very much.
Jürg

-- 
Sent from a mobile device, please excuse the shortness.

**Comment by fmp777** [comment]
+1

**Comment by sensibleworld** [comment]
These are available in FA5
https://fontawesome.com/icons/address-book?style=solid
https://fontawesome.com/icons/address-card?style=solid
