### ISSUE TITLE
Icon Request: fa-novelty

### ISSUE THREAD

**Issue by densenator** [FortAwesome/Font-Awesome#8981]
Its great to see icon novelty like this
![stock-vector-novelty-web-icon-vector-design-377401837](https://cloud.githubusercontent.com/assets/18443709/14526015/ce23c910-0240-11e6-8990-900dd2feb043.jpg)

**Comment by PeterShaggyNoble** [comment]
Would http://fortawesome.github.io/Font-Awesome/icon/certificate/ suit your needs or are you specifically requesting an icon with that wording on it?

**Comment by densenator** [comment]
Yes, i need this word on icon, maybe in another design.
http://cdn.xl.thumbs.canstockphoto.com/canstock6016049.jpg

**Comment by tagliala** [comment]
I'm pretty sure this is a duplicate but I'm not able to find the original request

**Comment by PeterShaggyNoble** [comment]
I had a look as well, @tagliala and couldn't find it; too many issues containing the word "new"! :laughing:

**Comment by tagliala** [comment]
found it: #1331
