### ISSUE TITLE
Icon request: icon-digibyte

### ISSUE THREAD

**Issue by nubojica** [FortAwesome/Font-Awesome#8988]
as seen at [here](http://www.digibyte.co/) it would be cool to have digibyte icon.

DigiByte is growing in popularity and so having an icon for it would be nice.

**Comment by aethior** [comment]
>Welcome to digibyte.co
This domain is parked free of charge with NameSilo.com. NameSilo offers the cheapest domains on the Internet as well as (...) ([more info](http://www.digibyte.co/))

cc/ @tagliala
