### ISSUE TITLE
Icon request: icon-tyre

### ISSUE THREAD

**Issue by NikkiC123x** [FortAwesome/Font-Awesome#8990]
I'm currently creating an automotive website, and would love a tyre / tire icon, please!  Something like this would be cool!
![tire-128](https://cloud.githubusercontent.com/assets/18484814/14563054/d6da44ee-0317-11e6-9dce-2ade5f68729a.png)

Thank you :-)

**Comment by PeterShaggyNoble** [comment]
Possible dupe of [#4430](https://github.com/FortAwesome/Font-Awesome/issues/4430), you should +1 that one instead.

**Comment by tagliala** [comment]
@PeterShaggyNoble thanks

**Comment by SewHappy58** [comment]
+1
