### ISSUE TITLE
fa-wheelchair-alt Category

### ISSUE THREAD

**Issue by PeterShaggyNoble** [FortAwesome/Font-Awesome#8992]
[fa-wheelchair-alt](http://fortawesome.github.io/Font-Awesome/icon/wheelchair-alt/) needs to be added to the [medical icons category](http://fortawesome.github.io/Font-Awesome/icons/#medical).

**Comment by aethior** [comment]
@tagliala check this please.

`fa-wheelchair` Web Application Icons, Medical Icons, Transportation Icons, Accessibility Icons.
`fa-wheelchair-alt` Web Application Icons, Accessibility Icons.

**Comment by tagliala** [comment]
thanks
