### ISSUE TITLE
Need text file of font names

### ISSUE THREAD

**Issue by mjs1138** [FortAwesome/Font-Awesome#8993]
I'm looking for a source (presumably a text file) that I can programmatically read and compare with icon fonts I find in a drupal database.  Does such a thing exist?

**Comment by PeterShaggyNoble** [comment]
Would the [icons.yml](https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml) file be any use to you?

**Comment by mjs1138** [comment]
Yeah, that works.  Thanks.

**Comment by PeterShaggyNoble** [comment]
You're welcome.

**Comment by tagliala** [comment]
Thanks, closing here
