### ISSUE TITLE
new icons don't display properly using local files

### ISSUE THREAD

**Issue by N6REJ** [FortAwesome/Font-Awesome#9001]
I've updated all the css and font files to master and when I try to use ( for example ) fa fa-blind it shows a [] instead of the blind man walking.. if I use the cdn it works fine.
as you can see cog works fine..
![image](https://cloud.githubusercontent.com/assets/1850089/14582925/19d4bfca-03d8-11e6-990a-5a8b357d0334.png)
but fa fa-blind does not.
![image](https://cloud.githubusercontent.com/assets/1850089/14582926/334ae59c-03d8-11e6-99f5-b10c8e5b7509.png)

**Comment by tagliala** [comment]
please check your browser cache and make sure that you are loading 4.6.0 version of font files

**Comment by N6REJ** [comment]
issue had several local issues.
