### ISSUE TITLE
Icon Request: fa-EU

### ISSUE THREAD

**Issue by leribol** [FortAwesome/Font-Awesome#9006]
I would like to request "European Union" flag. 

I will use it on EU button on my website to navigate user to EU related pages.

Best regards,

![eu](https://cloud.githubusercontent.com/assets/18526989/14598378/94880096-055a-11e6-9ae6-6ad8f50c539b.jpg)

**Comment by jeremyVignelles** [comment]
isn't this the same as #5831 ?

**Comment by tagliala** [comment]
@jeremyVignelles thanks!

Duplicate of #5831, please +1 that request

closing here
