### ISSUE TITLE
Requesting a new Icon : pie-chart with fully roundup as circle

### ISSUE THREAD

**Issue by thiru53** [FortAwesome/Font-Awesome#9007]
I would like to request "pie-chart" Icon with fully roundup as circle
![pie-chart](https://cloud.githubusercontent.com/assets/1137535/14601486/d8ebeaf2-057f-11e6-9e57-958bea01c0e1.png)

I will use it on my project Label to navigate user to display data in pie chart  related pages.

Best regards,
Thiru

**Comment by tagliala** [comment]
Isn't your use case covered by http://fontawesome.io/icon/pie-chart/ ?

**Comment by aethior** [comment]
@tagliala After several months without feedback I think you can close here.
