### ISSUE TITLE
Icon req: Open Source license icons!

### ISSUE THREAD

**Issue by kodapaio** [FortAwesome/Font-Awesome#9013]
Tried to do a search for them on the archive but no one is available.
Is there any chance to fix this?

Would be nice to have: MIT, Apache 2.0, GPLv3 and the rest of the GNU licenses that is available.

I can only find CC, but we need the rest also.

**Comment by tagliala** [comment]
Sorry, can't leave this open or maybe I didn't get this request

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please search to see if your icon request already exists. If a request is found, please +1 that one.

Is there any official icon for MIT license?
