### ISSUE TITLE
Icon request: icon-user-add

### ISSUE THREAD

**Issue by davegandy** [FortAwesome/Font-Awesome#902]
Splitting out from #124 for better tracking.

**Comment by davegandy** [comment]
Added to 4.3.0-wip branch. Also added a user-delete icon.

**Comment by tagliala** [comment]
updated the title to reflect the change

**Comment by Cysioland** [comment]
:+1:

**Comment by AjiMIde** [comment]
A very perfect project,Thanks for your hard word my author,But i want the color picker,would it offer?

**Comment by tagliala** [comment]
@AjiMIde please +1 #1794 or #244

**Comment by lyhil** [comment]
@dario-centrella +1

**Comment by Marchrius** [comment]
Still need the icon but for the moemnt thanks to @gabel +1

**Comment by hungnq1989** [comment]
:+1:

**Comment by tagliala** [comment]
The icons are here

http://fontawesome.io/icon/user-times/
http://fontawesome.io/icon/user-plus/

**Comment by tagliala** [comment]
:lock:
