### ISSUE TITLE
Icon Request: fa-opentable

### ISSUE THREAD

**Issue by rachelpan525** [FortAwesome/Font-Awesome#9023]
I'd like to request to have the OpenTable icon. I've been working on some restaurant projects and Yelp and OpenTable icon are necessary on websites. Hopefully, I could get the OpenTable icon soon.
Thanks!

**Comment by PeterShaggyNoble** [comment]
Dupe of [#792](https://github.com/FortAwesome/Font-Awesome/issues/792). You should +1 that one instead.
