### ISSUE TITLE
Icon Request: fa-flower or fa-rose

### ISSUE THREAD

**Issue by sakafujn** [FortAwesome/Font-Awesome#9024]
![flower](https://cloud.githubusercontent.com/assets/18563980/14660698/5dcbe114-065c-11e6-9216-75bf9000d10d.png)
![rose](https://cloud.githubusercontent.com/assets/18563980/14660699/5ddc5896-065c-11e6-86ee-4b34b6bce305.png)
![rose2](https://cloud.githubusercontent.com/assets/18563980/14660700/5df1c0aa-065c-11e6-8bd1-c81ae58e73ce.png)
I think it would be great to have these as decorations for possible sites. I have a project or 2 I'd love them for.

**Comment by PeterShaggyNoble** [comment]
Flower: [#2037](https://github.com/FortAwesome/Font-Awesome/issues/2037)
Lotus:[#6757](https://github.com/FortAwesome/Font-Awesome/issues/6757)
Rose:[#4666](https://github.com/FortAwesome/Font-Awesome/issues/4666)

You should +1 those requests instead.

**Comment by johnnyshields** [comment]
Flower and Rose available at https://github.com/kkvesper/vesper-icons which is designed to be fully compatible with FontAwesome.

**Comment by ricardoaraujo330** [comment]
Yes please! Font awesome bouquet also needed!
