### ISSUE TITLE
Icon Request: fa-animatedarrow

### ISSUE THREAD

**Issue by hsl1** [FortAwesome/Font-Awesome#9026]
i would like to request you to implement and arrow icon with custom text and when it hover the element the arrow and text desapear like here https://revolution.themepunch.com/fullscreen-hero-slider/ (orange section) .

You can see when you hover white horse element the arrow disappears

**Comment by tagliala** [comment]
Hi,

you should use custom css to obtain that effect.

Also, that arrow (![image](https://cloud.githubusercontent.com/assets/556268/14692491/d79057ea-0757-11e6-9b27-688440ce7e97.png)) is hard to fit in 14px icon size and does not match Font Awesome's style

Sorry, but I'm going to close this request
