### ISSUE TITLE
'fa-square' larger than 'fa-square-o'

### ISSUE THREAD

**Issue by DuckThom** [FortAwesome/Font-Awesome#9030]
I noticed that the filled square icon is taller than the empty one.

Live example: [https://jsfiddle.net/zbmLcn4b](https://jsfiddle.net/zbmLcn4b)
This is also happening outside the browser if I use the font in my system panel on Linux.

OS: Arch Linux
Browser: Chromium

**Comment by PeterShaggyNoble** [comment]
This is already covered in [#5156](https://github.com/FortAwesome/Font-Awesome/issues/5156).

**Comment by DuckThom** [comment]
Oh, ok, sorry. I couldn't find a similar issue.
