### ISSUE TITLE
Visual bug on the website

### ISSUE THREAD

**Issue by Sopamo** [FortAwesome/Font-Awesome#9031]
I noticed a visual bug on the website when hovering over the left / right icons on the icon slider:
![image](https://cloud.githubusercontent.com/assets/1202596/14713707/6dce62a8-07e2-11e6-97f8-276c5de17893.png)

Occurs on Safari 9 and Chrome 49 on OSX.

**Comment by tagliala** [comment]
Confirmed, on large screen (> 1200px)

**Comment by tagliala** [comment]
Should be fixed in the next docs build, but I'm getting a different effect on my development machine. Maybe there is a stylesheet only loaded in the production environment

/cc @davegandy @talbs
