### ISSUE TITLE
FA icons not showing in Chrome

### ISSUE THREAD

**Issue by kjc9901** [FortAwesome/Font-Awesome#9033]
I use font awesome icons on my Wordpress site (using Avada theme). I just updated to the new Wordpress and noticed that the FA icons are not showing up on my site (they show up as empty boxes/squares).

The FA icons are not even showing up on their site (https://fortawesome.github.io/Font-Awesome/) when I view it on Chrome. 

FYI...The FA icons look fine in all other browsers. Please help ASAP. Thanks!!!

**Comment by tagliala** [comment]
please take a look at our [troubleshooting guide](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting), then if you are not able to solve post a url to your website
