### ISSUE TITLE
Firefox Does Not Display Social Media Icons

### ISSUE THREAD

**Issue by artforlife** [FortAwesome/Font-Awesome#9035]
I have the following code that displays in Google but not in Firefox ( I have not tried other browsers).

`<a href="" target="_blank" style="color: #3b5998;padding-right:20px"><i class="fa fa-facebook-square fa-5x" aria-hidden="true"></i></a>
<a href="" target="_blank" style="color: #1dcaff; padding-right: 20px; "><i class="fa fa-twitter-square fa-5x" aria-hidden="true"></i></i></a>    
<a href="" target="_blank" style="color: #e52d27; padding-right : 20px;"><i class="fa fa-youtube-square fa-5x" aria-hidden="true"></i></a>
<a href="" target="_blank" style="color: #e52d27"><i class="fa fa-instagram fa-5x" aria-hidden="true"></i></a>`

HAving looked around for a fix, I saw that people suggested adding the following to .htaccess or httpd.conf. When I do that, my Apache will not longer start. I am using AMPPS stack on Win 7.

`<FilesMatch "\.(ttf|otf|eot|woff)$">
  <IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
  </IfModule>
</FilesMatch>`

Initially, I was using Font-awesome 4.2 but since tried 4.6 with the same result.

**Comment by tagliala** [comment]
Adblock? #1799

**Comment by tagliala** [comment]
No feedback, closing here

**Comment by artforlife** [comment]
No Adblock. No feedback?

**Comment by artforlife** [comment]
I shall retest tomorrow to be sure. Will also check in Safari.
