### ISSUE TITLE
fa-tree

### ISSUE THREAD

**Issue by skydiva** [FortAwesome/Font-Awesome#9039]
I'm having problems accessing the fa-tree file in both the font-awesome.css / font-awesome.min.css files. Any help would be appreciated. Supposedly there is a fa-tree @http://fontawesome.io/icon/tree/ but I can't pull it up through the css.
Thanks for any help!

**Comment by My1** [comment]
do you maybe have an old version? fa-tree was made 4.1.

**Comment by tagliala** [comment]
please take a look at our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

closing here
