### ISSUE TITLE
Icon request: icon-language

### ISSUE THREAD

**Issue by aensley** [FortAwesome/Font-Awesome#904]
And you don't even have to design it! Here it is:

![langiconclassic_r9_c22](https://f.cloud.github.com/assets/95717/318522/dbb13d1e-989a-11e2-8310-3d5f6f36a5c3.png)

There's already [an initiative to standardize this image as a language icon](http://www.languageicon.org/).

[SVG source](http://www.languageicon.org/languageicon.svg).

It is [free to use](http://www.languageicon.org/whythisiconfaq.php).

Of course, the icon in FontAwesome would just have to be the square (i.e. the white part only). The containing, rounded-corner, shape could be accomplished by placing the icon in a styled div (for example). This is already how I use most of the icons in Font Awesome, so this seems like a great fit.

**Comment by jace** [comment]
The current language icon is unusually wide, compared to the square profile on other icons. This makes it stick out in a menu of vertical `icon Label` items. Could it be redesigned?
