### ISSUE TITLE
no-Symbol/No-circle

### ISSUE THREAD

**Issue by qck1** [FortAwesome/Font-Awesome#9044]
The no-Symbol is a circle with a slash used to indicate that something is not permissible. This should be included because is can be used with other symbols to show forbidden.

https://en.wikipedia.org/wiki/No_symbol
![no-symbol](https://cloud.githubusercontent.com/assets/11397635/14756600/7ba6ba8e-089f-11e6-82b4-b43bec063c17.png)

**Comment by tagliala** [comment]
already implemented ad `fa-ban`: http://fontawesome.io/icon/ban/

it will be fixed (horizontally flipped) in 5.0.0: #1721
