### ISSUE TITLE
Icon Request: fa-maid

### ISSUE THREAD

**Issue by 888Plugin8COM** [FortAwesome/Font-Awesome#9045]
![1485756-0-maidicon](https://cloud.githubusercontent.com/assets/18630685/14761718/63134592-092f-11e6-969e-446be25f9253.png)

image for personal use at website at www.ecospiritcleaners.com

Thank you in advance

**Comment by tagliala** [comment]
Duplicate of #8719, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by 888Plugin8COM** [comment]
im sorry and thank you sir

**Comment by tagliala** [comment]
@888Plugin8COM don't worry 👍
