### ISSUE TITLE
Icon Request: fa-saturn

### ISSUE THREAD

**Issue by moodleboy** [FortAwesome/Font-Awesome#9053]
Saturn is a universal symbol for, well, the universe!  This can be used for anything dealing with planets, space, or anything "out of this world"

![saturn](https://cloud.githubusercontent.com/assets/5356272/14771555/371596c8-0a5d-11e6-9c51-fd00eb72094b.png)

**Comment by phuyem** [comment]
I really like this icon. Please make it in the core

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/planet-ringed?style=solid
