### ISSUE TITLE
IE11 on windows 10, icons are not appearing 

### ISSUE THREAD

**Issue by rathoregee** [FortAwesome/Font-Awesome#9058]
I am using asp.net MVC project, on IE 11 icons are not appearing.
even it is not showing on
https://fortawesome.github.io/Font-Awesome/icons/
using IE11.

help please for IE11

**Comment by tagliala** [comment]
Sorry, can't confirm.

Please take a look at: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#fonts-not-rendering-properly-running-windows-10

Please also provide a screenshot of the page causing issues

**Comment by rathoregee** [comment]
it worked after tutoiral.
if u suppose 5000 clients this is not good solution, provide any other easy one.
thanks,

**Comment by tagliala** [comment]
@rathoregee Font Awesome is essentially a web font, so it requires [@font-face support](http://caniuse.com/#feat=fontface).

If you have customers behind enterprise group policy which forbids font-face, unfortunately you can't use Font Awesome (as well as other webfonts).

You could go for .svg or .png sprites, please give a look at this project: https://github.com/encharm/Font-Awesome-SVG-PNG
