### ISSUE TITLE
Icon request: icon-Roger 

### ISSUE THREAD

**Issue by yushu94** [FortAwesome/Font-Awesome#9059]
Users have been asking to have our Roger icon on Font-awesome 👍  Would be great to have our icon here! 
![roger-1024](https://cloud.githubusercontent.com/assets/18128532/14796945/0adf6b32-0afe-11e6-8fde-87abce47f7c2.png)

**Comment by aethior** [comment]
@tagliala It's a brand icon: https://rogertalk.com/

**Comment by aethior** [comment]
>Inspired by the response from early users, we’ve decided to sunset Roger and focus all of our efforts on Fika. Effective March 15, 2017, Roger will be removed from the App and Play stores, and messages will no longer be transmitted. It’s the end of one journey, but more importantly it’s the start of another one. ([more info](https://medium.com/roger-talk/what-weve-been-up-to-project-fika-79e4ee3d44f8))

cc/ @tagliala
