### ISSUE TITLE
Icon-request: icon-category

### ISSUE THREAD

**Issue by jorame22** [FortAwesome/Font-Awesome#906]
How about adding an icon that represents a category/ries? This will be awesome when building WP pages.

**Comment by SirAiedail** [comment]
+1 for the first image

**Comment by tagliala** [comment]
@SirAiedail  there is a sitemap icon: http://fontawesome.io/icon/sitemap/

Otherwise there is a better request for that icon: #1343 

Closing here

**Comment by fandomfilms** [comment]
+1 sitemap doesn't work in this context
