### ISSUE TITLE
Icon Request: fa-envelope-open & fa-envelope-open-o

### ISSUE THREAD

**Issue by othyn** [FortAwesome/Font-Awesome#9062]
Would be nice to have an 'open' or 'read' variant of the envelope icons, [fa-envelope](http://fontawesome.io/icon/envelope/) and [fa-envelope-o](http://fontawesome.io/icon/envelope-o/) - possibly called fa-envelope-open and fa-envelope-open-o respectively.

Same style, but with the letter flap open and a document half pulled out perhaps? Some thing like this, obviously following the more rounded FA style.

![example icon](https://cdn1.iconfinder.com/data/icons/hawcons/32/698362-icon-2-mail-envelope-open-128.png)

Edit: could a contributor please add the `new icon` and `web application icons` labels to my issue please, thanks! :)

Edit: duplicate of #897

**Comment by ByScripts** [comment]
#897

**Comment by othyn** [comment]
Yeh, I just +1'd that, I was in the process of removing / updating this one to reflect that.

**Comment by RoumedG** [comment]
+1

**Comment by tagliala** [comment]
@othyn I'm going to close this one, you could post your example at #897

That icon is scheduled for 5.0.0 and is one of the most popular request. I'm pretty confident that dave will implement it in the next major release

Closing here
