### ISSUE TITLE
Icon request: fa-star-half-o needs to be corrected

### ISSUE THREAD

**Issue by trespas** [FortAwesome/Font-Awesome#9063]
Right now it is half filled just like fa-star-half-empty & fa-star-half-full
If we use outlined stars fa-star-o as 1 star, we need a half "just outline" star for the half rating. Like this-

![hvjaprn](https://cloud.githubusercontent.com/assets/16062063/14818258/cb0d6d9c-0bd9-11e6-9de0-3e9687c54f7e.png)

Usage-
![jec3neq](https://cloud.githubusercontent.com/assets/16062063/14818329/23ab406e-0bda-11e6-910c-5550d899eb4a.png)

**Comment by sensibleworld** [comment]
We have a few options for this now: https://fontawesome.com/search?q=star-half&o=r
