### ISSUE TITLE
Icon request: user-caregiver

### ISSUE THREAD

**Issue by niteshp** [FortAwesome/Font-Awesome#9067]
A caregiver user icon would be a great addition to medical icons.  Could we please have an icon for users, such as family/friends of a patient, that would be providing care for patients.

Something like this (below) perhaps ?

![](http://thumb1.shutterstock.com/display_pic_with_logo/1291156/378231688/stock-vector-man-helps-elderly-patient-icon-illustration-378231688.jpg)

**Comment by MatthijsMali** [comment]
I think your suggestion is a good direction. However caregivers can take their role not only with elderly, but with many people. I think the current icon is too much focussed on elderly.

My suggestion would be to keep two people, but to make it less focussed on a certain 'patiënt-type'.

**Comment by tagliala** [comment]
We need a better title

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by sensibleworld** [comment]
We now have a few icons that could work for this:
- https://fontawesome.com/icons/hands-heart?style=solid
- https://fontawesome.com/icons/hand-heart?style=solid
- https://fontawesome.com/icons/hand-holding-heart?style=solid
