### ISSUE TITLE
Icon request: icon-lasso

### ISSUE THREAD

**Issue by mineshpatel1** [FortAwesome/Font-Awesome#9069]
Lasso icon representing a freehand selection.
- [Example 1](https://d30y9cdsu7xlg0.cloudfront.net/png/177503-200.png.)
- [Example 2](https://cdn4.iconfinder.com/data/icons/design-tools/128/Graphic_Design_Tools_lasso-128.png)

Useful for drawing applications. My specific use case is a button to allow freehand selection of points on a map.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/lasso?style=light
