### ISSUE TITLE
Cross origin error from cdn dependency when attempting to search. 

### ISSUE THREAD

**Issue by crodriguez1a** [FortAwesome/Font-Awesome#9071]
Looks like a blocking error potentially since paired with ReferenceError _Backbone is not defined_ from search.js

**Comment by tagliala** [comment]
Cannot confirm on Chrome 50 / Win 10, Firefox 46 / Win 10.

Got the above error on firefox while noscript was enabled for a couple of domains

**Comment by crodriguez1a** [comment]
@tagliala I'm also only experiencing in Firefox now.

**Comment by tagliala** [comment]
@crodriguez1a were you able to solve this?
