### ISSUE TITLE
Icon request: icon-package (crate)

### ISSUE THREAD

**Issue by jjlharrison** [FortAwesome/Font-Awesome#908]
Package icon for installers or to indicate stock levels.

http://www.filecluster.com/reviews/wp-content/uploads/2008/11/mac_os_package.jpg

**Comment by d1820** [comment]
+1

**Comment by decima** [comment]
:+1: +1 :-)

**Comment by stijnvanbael** [comment]
+1

**Comment by rodnem** [comment]
+1

**Comment by timint** [comment]
+1

**Comment by iambray** [comment]
+1

**Comment by msalahz** [comment]
+1

**Comment by stijnvanbael** [comment]
+1

**Comment by leandroruel** [comment]
+1

**Comment by diwave** [comment]
+1

**Comment by iamandrebulatov** [comment]
+1

**Comment by amarok2** [comment]
Yes, it could be very interesting to add some variations to font-awesome, like fa-package-o, fa-package-full, fa-pakage-empty and so.

![box](https://cloud.githubusercontent.com/assets/12201634/9967318/5725614a-5e42-11e5-8e81-1edae7ee42d3.png)

+1 by the way :-)

**Comment by ext** [comment]
+1 I am also interested in this, much similar to other commenters I need it to represent a "container" (e.g. parcel, box, package, etc).

**Comment by alexmorbo** [comment]
+1

**Comment by rickymetz** [comment]
+1

**Comment by ppp999** [comment]
+1

**Comment by incoder1** [comment]
+1

**Comment by markmarco16** [comment]
+1

**Comment by RickatRITE** [comment]
1+

**Comment by danielflippance** [comment]
Until there is an fa-package, GitHub has a nice icon in it's Octicons: 
https://octicons.github.com/icon/package/

**Comment by dgpokl** [comment]
+1

**Comment by brendonofficial** [comment]
+1
I've been using 'fa-archive' for the time being, but it's really not suited in many cases.

**Comment by petyappetrov** [comment]
+1

**Comment by sn0opy** [comment]
+1

**Comment by miko007** [comment]
+1

**Comment by ashwanikumarindian** [comment]
+1

**Comment by lalabili** [comment]
+1

**Comment by abuckles** [comment]
+1 for open/closed versions as well

**Comment by PhilipLardi** [comment]
+1 open & closed

**Comment by AntjeReichenberger** [comment]
+1 is this in the works?

**Comment by carauzs** [comment]
+1

**Comment by sensibleworld** [comment]
There are a few options for this in the Logistics category: https://fontawesome.com/icons?d=gallery&c=logistics

**Comment by RickatRITE** [comment]
Nice - great solution
