### ISSUE TITLE
SVG font glyph names?

### ISSUE THREAD

**Issue by keremciu** [FortAwesome/Font-Awesome#9080]
I've developed a plugin which is containing font-awesome but I've a problem with your svg iconfont :(

My plugin is parsing svg fonts and glyph-name property is really important to use it. can you add it? 

I have related issue here
https://github.com/keremciu/sketch-iconfont/issues/48

**Comment by tagliala** [comment]
The `.svg` version of Font Awesome is generated via [Font Squirrel Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator) from the `.otf` file.

If there is a feature to include the glyph name let us know

Closing here

**Comment by keremciu** [comment]
can you use fontello to generate icon font files? I think it should be right solution for iconfont. font squirrel doesn't care the icon font solutions...
