### ISSUE TITLE
Icon Request: fa-vk-new

### ISSUE THREAD

**Issue by zerochka** [FortAwesome/Font-Awesome#9081]
vk.com (social) have new icon - 
it is like fa-behance without e

**Comment by tagliala** [comment]
Still seeing the old one (http://fontawesome.io/icon/vk/) on http://vk.com

![image](https://cloud.githubusercontent.com/assets/556268/14913855/59ab1a12-0e06-11e6-81bb-bc2063c285fc.png)

If you are referring to the russian variant, please +1 #3031

Closing here

**Comment by zerochka** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#newwindow=1&q=icon%20vk

**Comment by tagliala** [comment]
There is a request for:

![image](https://cloud.githubusercontent.com/assets/556268/14914062/698692da-0e07-11e6-90fe-7f31fada8301.png)

here: #3031

**Comment by sanek4life** [comment]
https://new.vk.com/blog

only logo "VK" now for all languages.

**Comment by tagliala** [comment]
@sanek4life so can I close #3031 and label as wontfix?

**Comment by sanek4life** [comment]
@tagliala yes. close this thread. no longer actual logo.
