### ISSUE TITLE
Icon Request: fa-feather

### ISSUE THREAD

**Issue by TakitIsy** [FortAwesome/Font-Awesome#9082]
Hello there,

I'd love to see a feather icon in the font. I think this would be a great addition.

I know there is already a topic for "fa-feather" but subtitled "fa-apache".
I don't intend to use it as an apache icon, so I'm creating this new topic.

That kind of icon would be nice : 
<img src="http://ntakit.com/.inc/NTak/Mngr/icons/Default/sys/Feather.png" />

What use for that feather ?

It could be usefull to stylize ( depending on the icon rotation ) :
- "Handwriting"
- "Signature"
- "Lightweight"
- …

**Comment by WACMemphis** [comment]
+1

**Comment by jcroucher** [comment]
+1

**Comment by tagliala** [comment]
Ref: #1639

**Comment by ryankane** [comment]
The current apache logo is this:

![logo][1]

I used the [HQ version here][2] to make the following image. You could flip/rotate this image to make it lay however you wish.

# fa-apache

![fa-apache][3]

  [1]: http://www.apache.org/img/asf_logo.png
  [2]: http://www.apache.org/img/asf_logo.png
  [3]: http://i.imgur.com/CJFiMNB.png

**Comment by barthsm** [comment]
+1

**Comment by arguiot** [comment]
+1

**Comment by crhairr** [comment]
+1: fa-feather or fa-quill would be a great addition!

**Comment by malikmalhan** [comment]
+1

**Comment by csphere** [comment]
+1

**Comment by ValdasVabolis** [comment]
+1

**Comment by narcisusse** [comment]
+1

**Comment by TheOneWhoMade** [comment]
+q

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/feather?style=solid

**Comment by NTakit** [comment]
Oh yay! Thanks guys!
Stay awesome.

**Comment by MustangChris04** [comment]
Looks more like a leaf than a feather...

**Comment by barthsm** [comment]
I appreciate the effort but yes, this looks more like a leaf  :(  Looking forward to the next attempt!  Thanks!

 

Sue Barth

Mobile:  716-474-3657

Website:   <http://www.nsytes.com/> http://www.nSytes.com

Professional Profile:   <http://www.linkedin.com/in/suebarth> http://www.linkedin.com/in/suebarth

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/feather?style=solid
https://fontawesome.com/icons/feather-alt?style=solid

Made a few tweaks.

**Comment by barthsm** [comment]
So much better – perfect!  Thank you!

 

Sue Barth

Mobile:  716-474-3657

Website:   <http://www.nsytes.com/> http://www.nSytes.com

Professional Profile:   <http://www.linkedin.com/in/suebarth> http://www.linkedin.com/in/suebarth
