### ISSUE TITLE
 Icon request: major open source apps

### ISSUE THREAD

**Issue by mixmastamyk** [FortAwesome/Font-Awesome#9085]
Hi, would appreciate a few, such as:

- Python
- Nginx
- PostgreSQL
- Java

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Python: #3016 
Nginx: #1507 
PostgreSQL: #6672
Java: #386 

Take also a look at mfizz: http://fizzed.com/oss/font-mfizz

**Comment by mixmastamyk** [comment]
Danke!
