### ISSUE TITLE
Universal Access Icon not working

### ISSUE THREAD

**Issue by Zlerp** [FortAwesome/Font-Awesome#9086]
<i class="fa fa-universal-access" aria-hidden="true"></i>

using this icon doesn't seem to work, all the other icons are fine on my page though.

**Comment by tagliala** [comment]
Please make sure you are using the latest version of Font Awesome (4.6.0)

Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up
