### ISSUE TITLE
Icon Request: fa-ts3

### ISSUE THREAD

**Issue by Mars073** [FortAwesome/Font-Awesome#9092]
Hello,
Can you add the icons: TeamSpeak3, mumble and virus? Thanks

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please search to see if your icon request already exists. If a request is found, please +1 that one.

Teamspeak: #1474 

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
