### ISSUE TITLE
Icon Request: fa-messages or fa-articles

### ISSUE THREAD

**Issue by DmitrijOkeanij** [FortAwesome/Font-Awesome#9095]
Thomething like fa-sticky-note or fa-text-file-o but with 2 items.

**Comment by aethior** [comment]
- https://fontawesome.com/icons/notes has been added in v6.0.0.
- https://github.com/FortAwesome/Font-Awesome/issues/9940 plural request for `fa-text-file-o` icon.

cc/ @tagliala

**Comment by tagliala** [comment]
> **Something like fa-sticky-note** or fa-text-file-o but **with 2 items**.

Considering this closed. Feel free to open a new request for `files-lines`
