### ISSUE TITLE
icon-request: all popular programming languages

### ISSUE THREAD

**Issue by marcamillion** [FortAwesome/Font-Awesome#9099]
Hi,
   I love Font-Awesome. I have been using it forever, in all of my projects. 

Is it possible for you guys to do an icon for all the popular programming languages.

I wasn't sure if I should make an issue for every single language, or just list them all here in this one issue. Either way I can do, so let me know.

But for starters, here are some:

- icon-ruby
- icon-php
- icon-javascript
- icon-c
- icon-python
- icon-cofeescript

Here is a complete list of all the icons and some images that represent them: https://glot.io/

I can't say with 100% certainty that every image is the original artwork for each language, but especially for the ones listed above, they seem to be a good representation.

Thanks!

P.S. I know there is a 'ruby-on-rails' icon-request, but that's not an actual language...but a framework. Ruby is the language. So that's why I created this issue.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Please also consider mfizz: http://fizzed.com/oss/font-mfizz
