### ISSUE TITLE
Copy to Clipboard Icon

### ISSUE THREAD

**Issue by n8carrier** [FortAwesome/Font-Awesome#910]

**Comment by billystalnaker** [comment]
I woudl li ke to see this one

**Comment by willdayble** [comment]
Yep +1 vote for this, preferably similar to the favicon from clipboardjs.com :)

**Comment by qdequippe** [comment]
+1 also to have this icon

**Comment by tagliala** [comment]
Hi @qdequippe , this icon is available as https://fontawesome.com/icons/paste and we also have https://fontawesome.com/icons/clipboard?style=solid

If you think there is a need for another icon, please provide an example by filling in our [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)

e.g.: `Icon request: clipboard-arrow-in (github style copy to clipboard)`
