### ISSUE TITLE
Icon Request:  fa-free or fa-freebie

### ISSUE THREAD

**Issue by UncloudedStudio** [FortAwesome/Font-Awesome#9101]
An icon to represent free products is missing.

**Comment by tagliala** [comment]
could you please provide an example?

**Comment by UncloudedStudio** [comment]
I have absolutely no idea what to use so i thought maybe somebody here could come up with a great example/idea. Do not know if this is the right place to ask for such a thing? You could use the gift icon because a gift is always free.

**Comment by tagliala** [comment]
closing here in favour of #9221
