### ISSUE TITLE
it is hard to see the icon

### ISSUE THREAD

**Issue by mike8625** [FortAwesome/Font-Awesome#9109]
i don't have git and nodejs and i don't want to install them.
i want to download the zip file in the page, and dblclick html in the zip, then the all icon display in the page. but it didn't work. the html in the zip display {% include jumbotron-carousel.html %}  i can't see the all icon in the page.
can you make it easily?

**Comment by liushaofeng89** [comment]
that's a good idea.

**Comment by tagliala** [comment]
@mike8625 so you need an offline HTML page with all icons? Use case? Can't you print the [cheatsheet](https://fortawesome.github.io/Font-Awesome/cheatsheet/) to pdf?

**Comment by mike8625** [comment]
@tagliala  thank you, this is what i want. cheatsheet is good!

**Comment by tagliala** [comment]
@mike8625 can I close this one?

**Comment by mike8625** [comment]
@tagliala  ok, thank you
