### ISSUE TITLE
What class replaces the icon-class from v 3.2.1

### ISSUE THREAD

**Issue by hectornado** [FortAwesome/Font-Awesome#9110]
Hi there. I'm quite a newbie som bare with me!
I have been using v 3.2.1 on previous sites and in that version there was a class like this 
`<i class="icon-phone"></i>`
This made the icon inherit the size of the current text. (The icon height was the same as text height.)
But now with 4.6.1 this class will not be supported it seems. And when using 
`<i class="fa fa-camera-retro" aria-hidden="true"></i>`
the icon is much larger than text which messes upp line height and so on.

*_So my question is *_
How do I make the icons the same height as the text? (inherit the text font-size) in 4.6.1 ? What class in the <i> do I need?

Thank u very much
/ Johan

**Comment by tagliala** [comment]
> This made the icon inherit the size of the current text.

the new shortened font definition in FA 4 sets a default font size. You should provide a fiddle showing your issue, you can start with this one: https://jsfiddle.net/tagliala/72fd5vcr/

**Comment by hectornado** [comment]
Hi there.. this shows the problem i guess: https://jsfiddle.net/c1ceLyp7/4/
As you can see the icon i slightly larger than the text and if changing text size the icon size remains.
This was not the case with the earlier "icon" class since it inherited the size.

Sure I can manipulate the .fa css I guess. But would be nice if this where standard as before I guess.

**Comment by sensibleworld** [comment]
Cleaning up some older issues. Please open a new request if this is still a problem in Font Awesome 5. Thanks!
