### ISSUE TITLE
Icon Request: icon-tfl-roundel

### ISSUE THREAD

**Issue by richietheg** [FortAwesome/Font-Awesome#9113]
As with my previous request for the BR logo, I realise that this too is fairly specific to Great Britain.

It is the Transport for London (TfL) logo, used on the London Underground network and other forms of transport in London (buses, DLR, Overground). As with the BR logo, it would be useful on UK-centred websites for denoting railway stations, either on maps or in the body of text (eg "Nearest tube station to our business is Lambeth North").

Attached is a really quick mock-up of what I'm requesting.

![fa-tfl-roundel](https://cloud.githubusercontent.com/assets/4976230/15010709/56f5fade-11e5-11e6-9ecd-4403293eb572.png)

**Comment by tagliala** [comment]
subset of #4038?

**Comment by richietheg** [comment]
Ah yes, it is. Didn't come up when I searched, but was probably searching the wrong thing! (Hopefully this is a better image to use as a template than the photograph in the other thread!)

**Comment by sensibleworld** [comment]
Closing because of existing issue: https://github.com/FortAwesome/Font-Awesome/issues/4038
