### ISSUE TITLE
Fix: Ship (fa-ship)

### ISSUE THREAD

**Issue by onebeatconsumer** [FortAwesome/Font-Awesome#9119]
The top of the ship (`fa-ship`) icon is jagged and not easily interpreted. The water might suffice, but the boat 'canopy' needs revision:

Examples:
- https://image.freepik.com/free-icon/boat-from-front-view_318-61851.png
- https://cdn0.iconfinder.com/data/icons/ecommerce-glyph-icons/512/shipment_delivery_boat_transport_travel-512.png
- http://thumb101.shutterstock.com/display_pic_with_logo/2936740/287208293/stock-vector-ship-boat-icon-287208293.jpg
- http://www.iconshock.com/img_vista/IPHONE/transportation/jpg/rescue_boat_icon.jpg

**Comment by Woensdag** [comment]
A side of a boat like the fa-truck would be a perfect solution I think.

**Comment by ptraverse** [comment]
I'm looking around for a sailboat icon right now. Motorboat would be nice too. 
Anything like 
https://www.google.ca/search?q=sailboat+icon&safe=off&espv=2&biw=1440&bih=799&tbm=isch&imgil=GsfTWuaxwaXviM%253A%253BFrL0NmJ81ipX0M%253Bhttp%25253A%25252F%25252Fwww.freeiconspng.com%25252Ffree-images%25252Fsailing-icon-14107&source=iu&pf=m&fir=GsfTWuaxwaXviM%253A%252CFrL0NmJ81ipX0M%252C_&usg=__hcMFI3ULesmvhQHQDF-5tnjitx8%3D&dpr=1&ved=0ahUKEwjz8sntsKvQAhXjrVQKHVuXAkkQyjcIOg&ei=o1IrWLOVC-Pb0gLbrorIBA#safe=off&tbm=isch&q=sailboat+vector&imgrc=_

**Comment by tagliala** [comment]
we have a new design in FA 5.0

https://fontawesome.com/icons/ship?style=solid

I'm going to close here, but if there is more room for improvement please open a new issue
