### ISSUE TITLE
android 5.1.1 Font-Awesome is Thai

### ISSUE THREAD

**Issue by iTaster** [FortAwesome/Font-Awesome#9122]
In android 4.0 and ios are normal, but it appears as Thai android5.1.1

**Comment by tagliala** [comment]
sorry, but I really cannot confirm. Are you talking about native apps? Fontawesome.io? Your website?

**Comment by iTaster** [comment]
是这样的，我用Fontawesome写的app端网页的时候，在我Android 5.1.1上显示的iconFont是泰文，在其他手机上测试都是正常的。
Is this, I use Fontawesome  of the app web page, in my phone（Android  5.1.1） is displayed on the Thai text, the test is normal on other mobile phones.

访问Fontawesome.io官方网站，我手机浏览器上可以正常显示icon。
Visit Fontawesome.io official website, my mobile browser can normally display icon.

然后我从github上下载了最新的字体和css样式在本地测试，icon显示的还是泰文。之后我把css的样式引入方式改为<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">发现还是泰文。
Then I downloaded the latest fonts and css style in a local from github test, icon display still is Thai text . After  I changed the style of CSS to the <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css"> found also Thai text.

我想这应该跟手机系统有关吧。
I think this should be the bar with the phone system.

我的手机：
about My phone：

型号：Samsung Galaxy Note edge （SM-N915S）
Model: Samsung  Galaxy Note edge (SM-N915S)

系统版本：Android 5.1.1
System Version: Android 5.1.1

支持语言：多国语言
Supported languages: multiple languages

我使用的语言环境：中文
I use locales: Chinese

**Comment by tagliala** [comment]
could you please provide a link to your website?

**Comment by iTaster** [comment]
This is a development application in order to maintain the user can display properly, we have taken a conservative approach, use of pictures. I'm sorry I can not offer website, our test is the internal network, non-extranet.

**Comment by iTaster** [comment]
code：
`                <div>       test 1
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                </div>
                <div>       test 2
                    <i class="fa fa-chevron-circle-right"></i>
                    <i class="fa fa-signal" aria-hidden="true"></i>
                </div>
                <div>       test 3
                    <i class="fa fa-chevron-circle-right" aria-hidden="true">&#xf138</i>
                    <i class="fa fa-gear" aria-hidden="true"></i>
                    <i class="fa fa-ambulance" aria-hidden="true"></i>
                </div>`

photo：
[https://goo.gl/photos/zgfH6Cz8g5UCuDMt9](url)

**Comment by tagliala** [comment]
Please check if the following fiddle works on your mobile: https://jsfiddle.net/tagliala/72fd5vcr/8/

Please also remove `&#xf138` from your code

**Comment by tagliala** [comment]
Closing here. If this is still an issue, please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md)
