### ISSUE TITLE
Font Awesome CDN: Publish second Embed Code does not complete

### ISSUE THREAD

**Issue by ITZAP** [FortAwesome/Font-Awesome#9123]
Thanks for creating the new Font Awesome CDN with Embed Code JS. Great idea !
Created my first Embed Code and set both Options, no problem, all loads fine.
Then created a second Embed Code with different Options.  But the "Publishing" message for that remains displayed, never completes.  BETA glitch I guess ?

**Comment by davegandy** [comment]
Drop me an email at dave@fontawesome.com? We want to take a look and don't want to discuss account stuff here. :)
