### ISSUE TITLE
Icon Request: fa-vhs

### ISSUE THREAD

**Issue by qlooney** [FortAwesome/Font-Awesome#9127]
Hello

Please add a vhs icon, maybe represented by a video tape to represent things like for example: home video

Thanks

![vhs](https://cloud.githubusercontent.com/assets/19205317/15043112/f9b514da-12f3-11e6-875c-b40e982bbaba.png)

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=vhs
