### ISSUE TITLE
Icon Request: fa-like, fa-dislike

### ISSUE THREAD

**Issue by thedeivi** [FortAwesome/Font-Awesome#9129]
Typical icons used for example in facebook, youtube...

**Comment by tagliala** [comment]
http://fontawesome.io/icon/thumbs-down/
http://fontawesome.io/icon/thumbs-up/
http://fontawesome.io/icon/thumbs-o-up/
http://fontawesome.io/icon/thumbs-o-down/

?

**Comment by thedeivi** [comment]
Wow perfect!! =)

**Comment by tagliala** [comment]
there is also a filter for like at http://fontawesome.io/icons/

![image](https://cloud.githubusercontent.com/assets/556268/15047379/fcdda9f6-12e4-11e6-9173-23bf54a7833a.png)
