### ISSUE TITLE
Icon Request: fa-voucher

### ISSUE THREAD

**Issue by ptahchiev** [FortAwesome/Font-Awesome#9130]
Something in the likes of:

https://cdn0.iconfinder.com/data/icons/everyday-objects-line-art-1/128/gift-card-128.png

**Comment by tagliala** [comment]
Duplicate of #8692 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by ptahchiev** [comment]
Sorry.. I searched for voucher and coupon.
