### ISSUE TITLE
Icon request: icon-wine

### ISSUE THREAD

**Issue by laxdragon** [FortAwesome/Font-Awesome#9134]
WineHQ Logo for the Wine project (https://www.winehq.org)

We use this logo on https://www.codeweavers.com for things like links to WineHQ Bugzilla.

![wine_logo](https://cloud.githubusercontent.com/assets/1074320/15055972/fc64a1ba-12d4-11e6-8513-878fa480dbe9.png)

**Comment by aethior** [comment]
Hi @laxdragon,

This request is duplicate of #8769. Please +1 that.

Regards.

**Comment by laxdragon** [comment]
Will do @aethior
