### ISSUE TITLE
FontAwesome Fonts - OS X EL Capitan - Validation Errors & MS Products

### ISSUE THREAD

**Issue by kalmdown** [FortAwesome/Font-Awesome#9137]
I am trying to use the FA 4.6.2 font on an El Capitan Mac but having a number of issues:
- Font Book gives validation errors and say "Do not use" for both TTF and OTF formats. 
- If I do drop either format into the ~/Library/Fonts folder:
  - The font appears in Omnigraffle's font menus and can be selected but object's with it often revert to .LastResort
  - It appears in Illustrator but is not selectable.
  - It doesn't appear in MS Word.

Any ideas why it doesn't validate and whether that issue is the cause of issues in the programs?

**Comment by jtbonhomme** [comment]
Same problem on Mac Os Sierra (10.12)

**Comment by tagliala** [comment]
@davegandy please take a look here

**Comment by tagliala** [comment]
I'm not seeing validation issues in Sierra, but the font

* Still does not appear on Pages (as per #7056)
* Shows [?] chars in fontbook (as per #10068)
* Can't test on Illustrator/MS Word

![image](https://cloud.githubusercontent.com/assets/556268/19398930/37c21054-924f-11e6-88ca-e0af4cbc3ad6.png)

![image](https://cloud.githubusercontent.com/assets/556268/19398983/7cc0b64c-924f-11e6-8a81-0fd52bd02929.png)

**Comment by tagliala** [comment]
Hi!

I'm on High Sierra 10.13.3 and there are:

- no more validation errors ✅ 
- no more "?" in FontBook ✅ 
- works in Pages 6.3.1 ✅

I'm closing this, please open a new issue if you are still having troubles with Microsoft Products under macOS
