### ISSUE TITLE
Icon request - fa-australia - fa-aus

### ISSUE THREAD

**Issue by Shad0wGeneral** [FortAwesome/Font-Awesome#9148]
Just looking to get a simple icon of Australia added. would be a great addition to a website im designing. Thanks! [http://www.embassyenglish.com/-/media/Embassy/Images/Countries/australia_map.png](url)

**Comment by tagliala** [comment]
Sorry, can't leave this open, maps are out of scope

Ref: https://github.com/FortAwesome/Font-Awesome/issues/3992#issuecomment-73022665
