### ISSUE TITLE
Icon Request: fa-face and faces

### ISSUE THREAD

**Issue by kellycorder** [FortAwesome/Font-Awesome#9154]
The idea is to provide a user and group representation. Face would be a single person profile.  maybe a fa-group or fa-faces for multiple stacked faces.

![person](https://cloud.githubusercontent.com/assets/19270564/15120647/875fb1a8-15cb-11e6-8763-73a44622f506.gif)
![group2](https://cloud.githubusercontent.com/assets/19270564/15124926/366f0f82-15df-11e6-9536-7894a05110fd.gif)
![person2](https://cloud.githubusercontent.com/assets/19270564/15124927/3678d8aa-15df-11e6-91b5-a9b6eb8fb1d8.gif)

**Comment by tagliala** [comment]
Since we already have: [fa-user](http://fontawesome.io/icon/user/) and [fa-users](http://fontawesome.io/icon/users/) (and also a request to improve those icons #1241) for that use case, could you please provide extra information on why face and faces are important and should be added in the core?

**Comment by kellycorder** [comment]
Thank you for that question, The fa-users icon to me does not work well as it's hard to distinguish that it is indeed users.  Most people seem to think it's a spider or dumbbells or something.  If the smaller two persons could be shaded lighter then I think that he existing users would work.  The face would give you more options for its use when needing a different icon to represent another type of person entity.


My problem is that I have an application that uses the entities: students, instructors and staff.  The students are indicated by the existing user icon.  I wanted instructors to be represented by the existing group icon, but that doesn't work well since the symbol is not quite working.

Maybe another version of group that looks like this:
![users2](https://cloud.githubusercontent.com/assets/19270564/15128285/be4cb26e-15ef-11e6-94ae-54910358d484.gif)

Or change the existing users icon so that the two smaller persons are outlined and not solid.

**Comment by tagliala** [comment]
There is a request for changing the user icons in #1241, also there is a request  for two users at #2883

**Comment by kellycorder** [comment]
Two users in the existing shape would be very useful and could be made to work in my situation.  The group icon though could still be modified so the smaller persons are either outlined, have more separation or are smaller than they are now.

I think font-awesome is well named - its awesome.
