### ISSUE TITLE
Casino icons

### ISSUE THREAD

**Issue by mika76** [FortAwesome/Font-Awesome#916]
I'd love a set of casino based icons. A couple of slot machines, some different table types as well as coins, chips and money notes icons. (Related to #818)

**Comment by Vahanerevan** [comment]
+1

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by clintnetwork** [comment]
+1 it's very important to add this kind of icons
