### ISSUE TITLE
icon request: icon-filing-cabinet

### ISSUE THREAD

**Issue by briana8191** [FortAwesome/Font-Awesome#9164]
Hello, 

I am requesting a filing cabinet icon. I saw other requests for changing the archive box to a filing cabinet. We use the archive icon for archiving which but have a separate need for a filing cabinet. 

> A filing cabinet and Archive serve separate functions. A Filing cabinet is where you keep information and documents that are important and that you need at that point in time. When that information is old and no longer needs to live within that filing cabinet and take up that space but is important enough to keep, you then archive it so it is accessible but not taking up space within your cabinet.

Thank you!

**Comment by tagliala** [comment]
Could you please provide a different use case from [archive](http://fontawesome.io/icon/archive/)?

Why is it important to have both in the core?

**Comment by tagliala** [comment]
no feedback, closing here

**Comment by briana8191** [comment]
Request to reopen - A filing cabinet and Archive serve separate functions. A Filing cabinet is where you keep information and documents that are important and that you need at that point in time. When that information is old and no longer needs to live within that filing cabinet and take up that space but is important enough to keep, you then archive it so it is accessible but not taking up space within your cabinet.

**Comment by briana8191** [comment]
Request to reopen - A filing cabinet and Archive serve separate functions. A Filing cabinet is where you keep information and documents that are important and that you need at that point in time. When that information is old and no longer needs to live within that filing cabinet and take up that space but is important enough to keep, you then archive it so it is accessible but not taking up space within your cabinet.

**Comment by crashuniverse** [comment]
[fa-inbox](https://fontawesome.com/icons/inbox?style=solid) looks like a filing cabinet to me.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/cabinet-filing?style=solid
