### ISSUE TITLE
Icon Request - Sports

### ISSUE THREAD

**Issue by petervejrumterp** [FortAwesome/Font-Awesome#9173]
Hi

I know I should only request one icon at a time, but I would love if there were some Sport Icons. Like http://all-free-download.com/free-vector/download/sports_icons_311781.html 

Examples 
fa-golf 
fa-running
fa-swimming
fa-tennis
fa-badminton 

I love what you do - it is a really great collection that you already have :-)

Cheers
Peter

**Comment by joshlopes** [comment]
+1 there is a futbol but not much.

**Comment by tagliala** [comment]
Hi!

I've missed this request

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Also, this is related to #714
