### ISSUE TITLE
Icon Request: fa-bank-check

### ISSUE THREAD

**Issue by kevinfaguiar** [FortAwesome/Font-Awesome#9174]
I want a Bank Check icon, like one of these: https://cdn0.iconfinder.com/data/icons/huge-business-icons/512/Cheque.png
https://cdn4.iconfinder.com/data/icons/shopping-set-1/512/12-512.png
It would be utilized for indicating a paying method in a tab, or menu item.

**Comment by tagliala** [comment]
Duplicate of #2603 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
