### ISSUE TITLE
Update Request: fa-instagram

### ISSUE THREAD

**Issue by jakuuub** [FortAwesome/Font-Awesome#9175]
Instagram just updated their app and all app icons:

http://blog.instagram.com/post/144198429587/160511-a-new-look

It would be great if you could update this really soon

**Comment by tagliala** [comment]
No need to +1, this will be done in the next release

**Comment by NoelBroda** [comment]
Not a bug

**Comment by davegandy** [comment]
Added to milestone wip branch. Closing.
