### ISSUE TITLE
Icon request: icon-skull (icon-poison)

### ISSUE THREAD

**Issue by MicKri** [FortAwesome/Font-Awesome#918]
I'm working with information about edible and poisonous mushrooms. A skull-icon would make my day!

**Comment by BarisJKaraali** [comment]
+1

**Comment by rmurdoch** [comment]
+1

**Comment by SharpNoiZy** [comment]
+1

**Comment by cdjackson** [comment]
+1

**Comment by thekondrashov** [comment]
+1

**Comment by maxkueng** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by danielquinn** [comment]
+1

**Comment by DamienR** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by MartinVandersteen** [comment]
+1

**Comment by li-xinyang** [comment]
+1

**Comment by nostalgiaz** [comment]
+1

**Comment by oddityoverseer13** [comment]
+1

**Comment by ckisker** [comment]
+1

**Comment by danielemery** [comment]
+1

**Comment by partnuz** [comment]
+1

**Comment by martinlindhe** [comment]
+1

**Comment by Colin-R** [comment]
+1

**Comment by huntingtown** [comment]
+1

**Comment by jrswenson** [comment]
+1

**Comment by golovnin** [comment]
+1

**Comment by caspii** [comment]
+1

**Comment by gsnunes** [comment]
+1

**Comment by isabellerichard** [comment]
+1

**Comment by nbevans** [comment]
+1

**Comment by MadLittleMods** [comment]
:+1:

**Comment by ElFuturero** [comment]
+1

**Comment by tuxy** [comment]
+1 for ☠

**Comment by G-Driver** [comment]
+1

**Comment by skcin7** [comment]
+1 !!!!

I want a Skull & Crossbones to show up as an icon that admins can click to visit the administration page.    I think it's funny that it's a Skull & Crossbones to visit the admin page ... inspired by 1995's crappy movie 'The Net'. :)

**Comment by Uniphix** [comment]
+1

**Comment by shawnam** [comment]
+1

**Comment by abellina** [comment]
:+1:

**Comment by ecegeek** [comment]
+1

**Comment by MicKri** [comment]
Seriously... What can I do to make this icon become a reality in this awesome font awesome project? I've been dreaming about this icon for almost 3 years now.. And I still have a need for it more than ever.. Does it have a price? I'm willing to go Kickstarter on this request so just let me know how I can help kick in..

**Comment by nbevans** [comment]
It seems the maintainers are more interested in adding corporate and "here-today-gone-tomorrow startup" branding icons. Mostly for brands nobody has ever heard of! That's just my observation/opinion though.

**Comment by sgates** [comment]
+1

**Comment by jbnv** [comment]
Apparently you have to get 100 people to +1 on an icon request for them to do it. 

+1 on skull and crossbones.

**Comment by skcin7** [comment]
I need this also, but have been using the character ☠ (Entity number &#9760;) to get the job done.

Although yeah it would be nice if there were a font-awesome icon.

**Comment by cyberwombat** [comment]
+1

**Comment by gholol** [comment]
C'mon, maintaners!

+1

**Comment by SuperHenkie** [comment]
+1 for this!

Another two suggestions for this:

![Image of skull-n-bones](http://i.imgur.com/b9rVhCB.png)

![Image of skull-n-bones](http://i.imgur.com/uLdQfkE.png)

**Comment by n8isjack** [comment]
+1

Useful to stress the danger of a next step. Just that much more emphasis to ensure they think about what they are doing before pushing the button.

**Comment by coleby210** [comment]
Totally +1

**Comment by DamienR** [comment]
-1 for taking 3 years to petition something that hasn't even been looked
at...  Wingdings development moves faster

**Comment by MicKri** [comment]
Don't give up. We can do IT! +1 Up Vote now so we can GTD! Just do IT! :-)

**Comment by SuperHenkie** [comment]
Even though my +1 is already up there, I'd like to vote _again_ for this, also for the purpose of a "piracy" icon.

And another example suggestion:

![](http://i.imgur.com/N92l7Kq.png)

**Comment by acorrow** [comment]
+1

**Comment by rub1e** [comment]
+1

**Comment by Lokua** [comment]
+1

**Comment by jayelkaake** [comment]
+1

**Comment by mattcw13** [comment]
+1 - looks like every other web-font is catching up on this one; except for FontAwesome. Starting to think none of the developers even look at these..

**Comment by jessijean** [comment]
+1, would love to see this pretty please.

**Comment by jaketblank** [comment]
+1

**Comment by Dobbler** [comment]
+1

**Comment by Postremus** [comment]
+1

**Comment by rahulkshinde** [comment]
+1

**Comment by jhiver** [comment]
+1

**Comment by baslr** [comment]
https://de.wikipedia.org/wiki/Datei:Skull_and_crossbones.svg
![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Skull_and_crossbones.svg/500px-Skull_and_crossbones.svg.png)

**Comment by nickbouton** [comment]
+1

**Comment by gholol** [comment]
Do we really want to add a "poison skull" symbol? (the one with bones) No, just stop.

**Comment by nickbouton** [comment]
https://en.wikipedia.org/wiki/Jolly_Roger

**Comment by schueppi89** [comment]
+1

**Comment by mattw3003** [comment]
+1

**Comment by pschroen** [comment]
+1

**Comment by fctucker** [comment]
+1

**Comment by iNilo** [comment]
+1

**Comment by freddinator** [comment]
+1

**Comment by KWierso** [comment]
+1

**Comment by gleroi** [comment]
+1

**Comment by lephleg** [comment]
+1

**Comment by figaw** [comment]
+1

**Comment by hchaase** [comment]
+1

**Comment by stefanct** [comment]
+1

**Comment by anujsharma9196** [comment]
+1

**Comment by carvalhorafael** [comment]
+1

**Comment by leonardosnt** [comment]
+1

**Comment by misthero** [comment]
+1

**Comment by TimothySnayers** [comment]
+1

**Comment by djechelon** [comment]
+1

**Comment by sendorf** [comment]
+1

**Comment by wstaeblein** [comment]
+1

**Comment by TTATPuOT** [comment]
+1

**Comment by Zekalo** [comment]
+1 give us a skull damn it!

**Comment by visualpharm** [comment]
Guys, it's painful to watch it, bunch of people asking for a single icon for year. It's 30 min of work after all.

Let's say they're licensed under [Good Boy License](https://icons8.com/good-boy-license/). If you're enterprise and your lawyers hate broad terms, let's double-license it under MIT.

[The skull icon is here](https://icons8.com/icon/4009/skull) and [the poison icon is here](https://icons8.com/icon/2012/poison).

I've begun a campaign, giving away the top requests for FA icons for free, open source. You can incorporate them in a number of ways: generating another icon font, svg set, or (my preference) [compiling](https://iconpharm.com) all FA and third party icons into a single file.

Previous ones were [moderator](https://github.com/FortAwesome/Font-Awesome/issues/2553#issuecomment-289439382),  [discord](https://github.com/FortAwesome/Font-Awesome/issues/7574#issuecomment-289875669), [coins](https://github.com/FortAwesome/Font-Awesome/issues/1400#issuecomment-292190852), [Google Play](https://github.com/FortAwesome/Font-Awesome/issues/2272#issuecomment-290106280),  [thin Close](https://github.com/FortAwesome/Font-Awesome/issues/1540#issuecomment-302573662), [walking man](https://github.com/FortAwesome/Font-Awesome/issues/844#issuecomment-302574446), [t-shirt](https://github.com/FortAwesome/Font-Awesome/issues/715), [Facebook messenger](https://github.com/FortAwesome/Font-Awesome/issues/6912#issuecomment-302864830) and [Line](https://github.com/FortAwesome/Font-Awesome/issues/2631#issuecomment-292290534) icons.

Please let me know if you want me keep going these icon requests, or compile some upgrade file.

**Comment by seltix5** [comment]
+1

**Comment by themazim** [comment]
+1

**Comment by robgwinprn** [comment]
+1

**Comment by turnbuga** [comment]
+1 (not in 5 yet)

**Comment by DevCubeHD** [comment]
+1

**Comment by bmarchbank** [comment]
+1

**Comment by premierpools** [comment]
+1

**Comment by kee-work** [comment]
+1

**Comment by fatmuemoo** [comment]
+1

**Comment by pgtips** [comment]
+1

**Comment by maheshwarishivam** [comment]
+1

**Comment by kincaider** [comment]
+1

**Comment by sliiser** [comment]
+1

**Comment by Moshem123** [comment]
+1

**Comment by OleAlbers** [comment]
+1

**Comment by draidman** [comment]
+1

**Comment by ttkaine** [comment]
+1

**Comment by imseandavis** [comment]
+1 in case this actually gets done.

**Comment by seezee** [comment]
+1; hopefully now that FA5 is out it makes it into the Pro pack.

**Comment by 4077** [comment]
+1 this will change the reality to the perfect state

**Comment by himurajutsu** [comment]
+1

**Comment by mika76** [comment]
FYI http://govicons.io/ has a biohazard and radioactive icon - in case this can be used instead...

**Comment by hookdump** [comment]
+1

**Comment by epot** [comment]
+1

**Comment by shadoath** [comment]
How soon? Thar be pirates waiting!

**Comment by argamanza** [comment]
+1

**Comment by sensibleworld** [comment]
Alas, poor Yorick... https://fontawesome.com/icons/skull?style=solid
