### ISSUE TITLE
Icon request: fa-tram

### ISSUE THREAD

**Issue by denisbondar** [FortAwesome/Font-Awesome#9181]
Icon need to indicate the type of public transport. You have already great icons that show transport. Suffice it to finish some missing elements.

<img src="http://blog.denisbondar.com/wp-content/uploads/2016/05/tram.png" />

**Comment by brainscript** [comment]
+1

**Comment by rootingrobin** [comment]
+1

**Comment by vfridkin** [comment]
+1

**Comment by kaendalian** [comment]
+1

**Comment by martyn3510** [comment]
+1

**Comment by lalabili** [comment]
+1

**Comment by ErikBooij** [comment]
+1

**Comment by betasa** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by tjdeurvorst** [comment]
+1

**Comment by choffa** [comment]
+1

**Comment by DaSchTour** [comment]
And as stated in pro repo the current fa-tram icon needs renaming https://github.com/FortAwesome/Font-Awesome-Pro/issues/1378

**Comment by psancis** [comment]
+1

**Comment by psancis** [comment]
the current fa-tram icon needs renaming

**Comment by Hanashi** [comment]
+1

**Comment by sensibleworld** [comment]
This is now available in the latest release of our version 6 Alpha, which can be downloaded by Pro subscribers (and the naming has been fixed, as well).

http://fontawesome.com/download
