### ISSUE TITLE
Icon request : fa-symfony

### ISSUE THREAD

**Issue by SSGhost63** [FortAwesome/Font-Awesome#9184]
Used to display Symfony logo
![logosf_positif_03_icon](https://cloud.githubusercontent.com/assets/2691392/15208769/b0a9be28-182d-11e6-9e2f-dccb3209d738.png)

**Comment by tagliala** [comment]
Duplicate of #2392 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
