### ISSUE TITLE
Icon request: icon-app-store icon-itunes-store [will be available in Font Awesome 5]

### ISSUE THREAD

**Issue by akashivskyy** [FortAwesome/Font-Awesome#919]
What about an App Store and iTunes Store icon? Something like this:

![](http://f.cl.ly/items/2K3l0c0g0v3Z393v2Y35/app_store_icon.png) ![](http://f.cl.ly/items/1i3b1I0r231q3m3c1n0h/itunes_store_icon.png)

**Comment by BenSibley** [comment]
+1

**Comment by LukeLambert** [comment]
+1

**Comment by xnomeda** [comment]
+1

**Comment by Miniguide** [comment]
+1

**Comment by foomep** [comment]
+1

**Comment by JessPace** [comment]
+1

**Comment by stevedore19** [comment]
+1 for iTunes

**Comment by malinin13** [comment]
+1 for app store no border

**Comment by Twintails** [comment]
+1
also https://github.com/FortAwesome/Font-Awesome/issues/2125

**Comment by matts2cant** [comment]
+1

**Comment by Rebex90** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by sidewalkdriver** [comment]
+1 for iTunes

**Comment by Divites** [comment]
+1

**Comment by eljacko** [comment]
+1

**Comment by titiomm** [comment]
+1 for App Store / Play Store and other mobiles' stores icons

**Comment by powlow** [comment]
+1

**Comment by trixbengel** [comment]
+1

**Comment by andresgalante** [comment]
:+1:

**Comment by terrybolontine** [comment]
+1

**Comment by WordPresseur** [comment]
+1

**Comment by galengidman** [comment]
+1

**Comment by Bartuzz** [comment]
+1

**Comment by bradleygauthier** [comment]
Yes, please! +1 * many of my sites

**Comment by sangrita22** [comment]
+1 please

**Comment by tengyifei** [comment]
+1

**Comment by jimeh** [comment]
:+1:

**Comment by christophelimpalair** [comment]
+1

**Comment by Cutcopy** [comment]
+1

**Comment by Tuckie** [comment]
+1 for app store.

**Comment by pingyen** [comment]
+1

**Comment by bsohlml** [comment]
+1 please!!! there must be a way to create one without any copyright issues.

**Comment by WileC** [comment]
+1 itunes

**Comment by korra8888** [comment]
+1

**Comment by ci2014** [comment]
+1

**Comment by pxaviad** [comment]
+1

**Comment by Kennric** [comment]
+1

**Comment by chekle** [comment]
+1

**Comment by breadadams** [comment]
+1

**Comment by kofdog** [comment]
+1

**Comment by rusln** [comment]
+1

**Comment by michaelpanik92** [comment]
+1 PLEASE! Perfect for podcasts hosted on iTunes

**Comment by pote** [comment]
+1, same podcast hosted on iTunes use-case.

**Comment by joaovarandas** [comment]
+1

**Comment by jay7134** [comment]
+1

**Comment by p33k** [comment]
+1

**Comment by sanek4life** [comment]
+1

**Comment by RASK901** [comment]
![itunes](https://cloud.githubusercontent.com/assets/18583587/14710267/fcdeceb4-07d4-11e6-998e-201fda6b5ddd.png)
[itunes.zip](https://github.com/FortAwesome/Font-Awesome/files/229962/itunes.zip) (SVG File)

+1

**Comment by mattstratton** [comment]
+1

**Comment by hasusuf** [comment]
+1

**Comment by jeffmoran** [comment]
Much needed.

**Comment by thejwalker** [comment]
+1

**Comment by samkite** [comment]
+1

**Comment by amoedoamorim** [comment]
+1

this won't really every be done, will it? :(

**Comment by enelbus** [comment]
+1

**Comment by mgjobber** [comment]
For the App store, this would have to be the icon shown on the Apple marketing guidelines page -- it's the A shown above by OP, white on solid background, in a white circle within a rounded box.
https://developer.apple.com/app-store/marketing/guidelines/#appstore

**Comment by BenSibley** [comment]
+1

**Comment by julia-patterson** [comment]
+1

**Comment by pachocho84** [comment]
+1

**Comment by mrtn** [comment]
+1

**Comment by efeconirulez** [comment]
+1

**Comment by emanuelmutschlechner** [comment]
+1

**Comment by stanfaire** [comment]
+1

**Comment by mollikka** [comment]
+1

**Comment by joshholly** [comment]
As a web developer in the music industry, please! 

+1

**Comment by gizmolet** [comment]
+1

**Comment by gathrlabs** [comment]
+1

**Comment by 69** [comment]
+1

**Comment by tagliala** [comment]
Hi, thanks for all your reactions to this request!

These icons will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards

**Comment by chinsyo** [comment]
+1
