### ISSUE TITLE
Icon request:Hongbao

### ISSUE THREAD

**Issue by qinyating** [FortAwesome/Font-Awesome#9196]
Hongbao,you know,like this:
![Uploading hongbao.jpg…]()

I don't know why that that represent the idea of mine dose not upload succeful.

**Comment by tagliala** [comment]
could you please clarify this request?

**Comment by qinyating** [comment]
Wechat has this icon:

![4](https://cloud.githubusercontent.com/assets/15796459/15244610/8d3966ac-1934-11e6-83ed-bd50e99d8d4e.png)

**Comment by tagliala** [comment]
Sorry, still didn't get it.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Include a few use cases for your requested icon. How do you plan on using it?
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by qinyating** [comment]
I'm sorry about that you  still didn't got it.I'm a chinese,my English is very poor.

Hongbao is a chinese vocabulary that means red pager containing money as a gift.

there's some explanation from Wikipedia：
A red envelope or red packet is a monetary gift which is given in Chinese society. The name comes from the red envelope in which the money is contained.
Red envelopes are often presented on social and family occasions such as a wedding reception or a holiday.

**Comment by tagliala** [comment]
@qinyating I like your new request, I'm going to close this one.
