### ISSUE TITLE
Browser tries to load webfontloader.js from file:// even though https:// is specified in local html file

### ISSUE THREAD

**Issue by TomHarrop** [FortAwesome/Font-Awesome#9205]
I'm developing a site locally. When I open the html file in a browser, it tries to load `webfontloader.js` from `file:///webfontloader/1.6.24/webfontloader.js` even though I'm including `https://` in the CDN link.

Here's an example:
```{html}
<!DOCTYPE html>
<html>
<head>
  <script src="https://use.fontawesome.com/[my_key].js"></script>
</head>
<body>
  <i class="fa fa-github fa-3" aria-hidden="true"></i>
</body>
</html>
```
In this case the `fa-github` icon won't load because the browser can't find `webfontloader.js`. I can get around this by modifying the `<head>` as follows:
```{html}
<head>
  <script src="https://use.fontawesome.com/[my_key].js"></script>
  <script src="https://use.fontawesome.com/webfontloader/1.6.24/webfontloader.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/[my_key].css">
</head>
```
I don't know if this is the expected behaviour, but if so, how can I develop a site locally and test it in my browser?

**Comment by robmadole** [comment]
hey @TomHarrop thanks for submitting. I think I know what's going on. I'll look at this and talk to @davegandy about how we can fix this.

**Comment by robmadole** [comment]
ok, we've got an idea how to fix it. we'll let you know in this ticket when you can try a fix for this @TomHarrop.

**Comment by robmadole** [comment]
Hey @TomHarrop I think we have this fixed. Can you give it a try?

**Comment by TomHarrop** [comment]
Yep, now it loads `webfontloader.js` from `https://use.fontawesome.com/webfontloader/1.6.24/webfontloader.js` without the extra lines in `<head>` when I'm developing offline. Thanks!

**Comment by hereonpurpose** [comment]
@TomHarrop What changed for you for this to work? I'm building a page locally and had the same setup and issue that you originally had. Even when I tried your work-around I was unable to get the files to load from `https://use.fontawesome.com/...`.

**Comment by robmadole** [comment]
@hereonpurpose can you try creating a new embed code and see if that fixes things up for you?

**Comment by hereonpurpose** [comment]
@robmadole Works like a dream! Thank you.
