### ISSUE TITLE
Preview Links to Font Awesome Icons

### ISSUE THREAD

**Issue by holland1286** [FortAwesome/Font-Awesome#9206]
Not a bug but something I thought would be a major improvement.

A friend and I were comparing ideas for a font-awesome icon for a label and we both pasted links to your site to differing icons in our slack conversation. The preview would be a lot nicer with the actual icon.

![image](https://cloud.githubusercontent.com/assets/9467713/15263744/a822d4ca-193a-11e6-8239-ff83d5518253.png)

Below is an example where it shows a preview image and with FA it could be the actual icon :+1: 
![image](https://cloud.githubusercontent.com/assets/9467713/15263813/48547110-193b-11e6-9fb4-90800f70d0e4.png)

**Comment by tagliala** [comment]
This requires every single icon to be converted to png format. It is nice, but I don't know if it is worthy.

Build scripts from https://github.com/encharm/Font-Awesome-SVG-PNG may help

**Comment by sensibleworld** [comment]
This has been implemented on our site, finally!

<img width="698" alt="CleanShot 2023-01-06 at 13 44 27@2x" src="https://user-images.githubusercontent.com/529604/211078128-d09c5fff-2c70-4d2f-9d07-b50382d75755.png">
