### ISSUE TITLE
Icon Request: fa-dairy-product

### ISSUE THREAD

**Issue by tarunaggarwal54** [FortAwesome/Font-Awesome#9215]
I am developing a online grocery store in which I need icons related to grocery.
![dairy_product](https://cloud.githubusercontent.com/assets/19358761/15267432/8c6f546a-19df-11e6-865d-999dd9b81c41.png)

**Comment by tagliala** [comment]
Duplicate of #3663, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
