### ISSUE TITLE
Icon Request: fa-medical icons

### ISSUE THREAD

**Issue by dricon** [FortAwesome/Font-Awesome#9218]
Hello, 
Great icons. I want to request more medical icons and in this case body parts and others. 

- Head: http://image005.flaticon.com/1/svg/30/30609.svg
- Brain: https://commons.wikimedia.org/wiki/File:Human_Brain_sketch_with_eyes_and_cerebrellum.svg
- Bone: https://upload.wikimedia.org/wikipedia/commons/f/f9/Femur_front.png
- Other: lungs, ears, nose, abdomen, liver, kidney, intestine, skin, scalpel, microbe/bacterium/virus, hand, thyroid gland, blood (blood drops), syringe, needle, vessels, urinary bladder/prostate, baby, drug/pill.

These can be used on many medical sites/forums. 

Regards, 
drIcon

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

Duplicates: #2075
