### ISSUE TITLE
Icon request: fa-outstretched-hand-with-money

### ISSUE THREAD

**Issue by aakash9820** [FortAwesome/Font-Awesome#9222]
Need an icon which show the Income/Money saving/protection Icon. the new Icon should has a hand symbol with money (maybe coins ) in hand .

**Comment by aakash9820** [comment]
Like this one, but money in hand....
![](https://cdn0.iconfinder.com/data/icons/financial-3/500/Financial_change-512.png)

**Comment by tagliala** [comment]
Related to #2224

**Comment by sensibleworld** [comment]
Released in 5.0.9

**Comment by tagliala** [comment]
Please use https://fontawesome.com/icons/hand-holding?style=solid and layering / stacks for other currencies
