### ISSUE TITLE
Icon Request: fa-twitter-t

### ISSUE THREAD

**Issue by kpfries** [FortAwesome/Font-Awesome#9224]
An alternative twitter logo. Similar to how you have fa-pinterest and fa-pinterest-p.  Something like this [this](http://iconizer.net/files/Helveticons_Social/orig/twitter.png)

**Comment by aethior** [comment]
Hi @kpfries,

The current Twitter logo is the famous blue bird and the [brand guidelines](https://about.twitter.com/company/brand-assets) says:

> Don’t: Use older versions of the logo, previous logos, or any marks that may be confused with the brand.

**Comment by kpfries** [comment]
Thanks for looking into it! I didn't actually look over their guidelines.  Guess I'll talk to the designer about that.

**Comment by MokkeMeguru** [comment]
How did you do after that about guideline? I think any update has not been applied.
