### ISSUE TITLE
Icon request: map-region

### ISSUE THREAD

**Issue by wael101** [FortAwesome/Font-Awesome#9225]
Thank you!

![region](https://cloud.githubusercontent.com/assets/12619028/15309899/e635f582-1b9f-11e6-955d-37ef139b33d3.png)

**Comment by liushaofeng89** [comment]
what's this?

**Comment by tagliala** [comment]
@wael101 could you please clarify this request?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by wael101** [comment]
Sorry I didn't make this clear, I am thinking to replace the address labels with an icons, plz see below:

![2016-05-18_14-53-20](https://cloud.githubusercontent.com/assets/12619028/15376204/62320554-1d08-11e6-8bee-bc4c2c15cbd6.jpg)
