### ISSUE TITLE
Font Request

### ISSUE THREAD

**Issue by bijoos** [FortAwesome/Font-Awesome#9226]
Please add icons for kids and youth

**Comment by tagliala** [comment]
Sorry, I didn't get this request

child: http://fontawesome.io/icon/child/

If you are requesting something else, please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Closing here
