### ISSUE TITLE
Font Awesome CDN - Parked Domain Blocked

### ISSUE THREAD

**Issue by dougkillmer** [FortAwesome/Font-Awesome#9229]
Our content filter (Websense) was blocking access to the CDN because the js file is being hosted on a "parked domain".  The browser console displayed an error and fonts were not rendered.

![image](https://cloud.githubusercontent.com/assets/11560014/15331010/1b7aa8b8-1c14-11e6-8b5a-b5e3b0135c9b.png)
![image](https://cloud.githubusercontent.com/assets/11560014/15331071/6131b8ce-1c14-11e6-88b5-8d3fee567fff.png)

White-listing this domain fixed the issue for me internally, but external visitors of our site could face the same issue if they use content filters for this category.

**Comment by davegandy** [comment]
This is quite strange. This is most certainly not a parked domain. I wonder if Websense just hasn't updated their filters? The domain was likely parked until several months ago.

**Comment by dougkillmer** [comment]
Their database still shows it as parked, but I did suggest a change to their classification.  When my ticket with them is updated I can post an update.

http://aceinsight.websense.com/

![image](https://cloud.githubusercontent.com/assets/11560014/15336643/605f9ec6-1c2c-11e6-92b7-2654e52ba0ee.png)
![image](https://cloud.githubusercontent.com/assets/11560014/15336671/86de2fea-1c2c-11e6-8d23-7ee29dc3d611.png)

**Comment by dougkillmer** [comment]
It looks like Websense will be fixing this on their end.

![image](https://cloud.githubusercontent.com/assets/11560014/15337075/9d38a34a-1c2e-11e6-8ee0-f82c8faaec23.png)
