### ISSUE TITLE
Icon request: Apache Software components

### ISSUE THREAD

**Issue by hittu123** [FortAwesome/Font-Awesome#9236]
These images  are frequently being used in many websites, icons would be very helpful. Example:
Apache Kafka
Apache Hadoop
Apache Zeppelin
Apache Hive

Similarly:
AWS Components

**Comment by simPod** [comment]
Related https://github.com/FortAwesome/Font-Awesome/issues/12040

**Comment by scouvreur** [comment]
+1

Also if possible it would be very helpful to include:
Apache Spark
Apache Flink

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

I'm cleaning up some old requests and I've run into this one.

For management purposes, please split this request into individual ones (eg: kafka #12040)
