### ISSUE TITLE
Icon Request: fa-software-applications

### ISSUE THREAD

**Issue by matriawan** [FortAwesome/Font-Awesome#9243]
hope full, font awesome will be have icons like this site: http://fizzed.com/oss/font-mfizz

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
