### ISSUE TITLE
Icon Request: fa-contactcard

### ISSUE THREAD

**Issue by nagel85** [FortAwesome/Font-Awesome#9244]
I would like to request an icon for a representative. The fa-user icon could be used in a different color, but I have a user who struggles with color blindness (so this is not the best alternative). The best alternative is a contact card with a smaller user icon in it. This would be a generic icon which can be used for different purposes.

**Comment by tagliala** [comment]
Duplicate of #825 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
