### ISSUE TITLE
Missing CDN option in Get Started

### ISSUE THREAD

**Issue by uok** [FortAwesome/Font-Awesome#9245]
Hello,

Is it still possible to use a single line CSS without javascript like before?
e.g. https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

Thanks!

**Comment by tagliala** [comment]
Sorry, I didn't get this one.

Font Awesome does not require javascript. Font Awesome CDN with javascript option does

**Comment by uok** [comment]
before v4.6.3 there were the following options on [get started](http://fontawesome.io/get-started/)

1) Easiest: Paste the following code into the <head> section of your site's HTML.
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">`
2) Easy: default css (download files to own server)
3) Easy: use SASS/LESS

now there are

1) insert email for CDN with javascript
2) default css (download files to own server)
3) use SASS/LESS

I'm looking for option 1) for v4.6.3

**Comment by tagliala** [comment]
Got it.

**Comment by tagliala** [comment]
meanwhile, here it is the link to Font Awesome @ BootstrapCDN

https://www.bootstrapcdn.com/fontawesome/

**Comment by spdustin** [comment]
It wasn't exactly fair to close #9332 - it was a more descriptive post, clearly defining the "issue" and the desire for resolution. But I'll play along, and re-post my comment here:

> This feels like a really dirty trick, getting rid of the CSS-only version. There's no reason users should run arbitrary JavaScript just for some CSS, but you're almost forcing them to by making less-experienced developers go down the path of using JavaScript to use Font Awesome. And let's be honest here - it's not to serve the users, it's to associate e-mail addresses with web sites, that's what you get when you generate unique embed codes and require an e-mail address to do so.
> 
> The original CSS should be the first option. THEN the "custom build" JS option. Maybe. But that option feels like a dirty, dirty trick to me, and you just lost my trust by dropping the change with no fanfare and a hand-wavy "hey buddy, this is better".

**Comment by fahmilatib** [comment]
I agree with @spdustin regarding #9332 . Thing that was originally _easiest_ and _straight forward_ to implement is now replaced with one confusing method.

**Comment by yuv** [comment]
Completely agree with @spdustin on #9332. There is no benefit to run arbitrary JavaScript just to include a font vs. using the CSS-only version, and there are a lot of drawbacks.  Have you considered the effect on **your reputation**?

To me, it **looks** like you are trying to pry on my website's user the same way Google tries to pry on my website's users with google-analytics.  Spyware. Consequence: I do not use it.

To me, the unnecessary collection of email address **looks** like somebody will be spamming me. Not cool. Consequence: I become more adverse and look for alternatives or forks.

I understand you are commercially minded and driven.  I don't think that pushing users around with what looks and feels like dirty tricks will help you money-wise. Not in the long term.

**Comment by tagliala** [comment]
I'm still waiting for feedback from Dave on this topic.

I personally agree with you

**Comment by spdustin** [comment]
Any updates?

**Comment by spdustin** [comment]
@davegandy Can you provide feedback on this issue?

**Comment by tagliala** [comment]
There is also a broken link here: https://github.com/FortAwesome/Font-Awesome/blob/master/src/_includes/thanks-to.html#L22

**Comment by davegandy** [comment]
Okay, it looks like we're not being clear in how we do things. You can still use CSS for Font Awesome CDN. It's just not the default. If you log in, you can change to the CSS option and still get easy upgradability without pushing code. No JS.

And let's be clear, if someone is NOT asking for your email address to use a service, you can be sure they're almost certainly making money in another way.

**Comment by talbs** [comment]
One other note on @davegandy's comment - Font Awesome CDN's JavaScript isn't arbitrary. There are real features that we've added to help with accessibility and performance (async loading of icons) that are JS-based.

Hope that helps shed some light on why we thought JS was a useful option.
