### ISSUE TITLE
Icon Request: fa-outlook

### ISSUE THREAD

**Issue by SashaRudolf** [FortAwesome/Font-Awesome#9247]
The outlook icon.

**Comment by ADoebeling** [comment]
Are you sure that non of these meets your requirements?

![image](https://cloud.githubusercontent.com/assets/10674780/15808718/3ae266f8-2b7f-11e6-840a-5fdd3fd16c61.png)

If not we probably need icons for

* Outlook
* Thunderbird
* Mac Mail

**Comment by tagliala** [comment]
I'm going to consider this a duplicate of #2884, please add a 👍  reaction to that request

Closing here
