### ISSUE TITLE
Icon Request: fa-wattpad

### ISSUE THREAD

**Issue by GaelleLaurier** [FortAwesome/Font-Awesome#9248]
Hello, it's a community of writers. 
Thanks a lot :)

![wattpad](https://cloud.githubusercontent.com/assets/19509639/15450806/3fc07e0a-1fa7-11e6-9bad-911a7d345f98.png)

**Comment by tagliala** [comment]
Duplicate of #3402, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
