### ISSUE TITLE
Icon-request: fa-exchange-vertical

### ISSUE THREAD

**Issue by thismahbub** [FortAwesome/Font-Awesome#9253]
Please add new icon called fa-exchange-vertical which will 90deg rotated icon of fa-exchange

**Comment by tagliala** [comment]
Duplicate of #8586, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please not that you can add `fa-rotate-90` to rotate icons by 90 deg

Closing here
