### ISSUE TITLE
Requirejs error using cdn.fontawesome.com embed js

### ISSUE THREAD

**Issue by kevintweber** [FortAwesome/Font-Awesome#9257]
I use requirejs in my application.  Today, I included your cdn.fontawesome.com embed js and immediately got the a require js error.  I removed your embed code js and the error went away.

(As an aside, I was using asynchronous loading but not the accessibility option.)

Here is the error reported in Chrome:

require.min.js:1 Uncaught Error: Mismatched anonymous define() module: function (){return Z}
http://requirejs.org/docs/errors.html#mismatchmakeError
@ require.min.js:1intakeDefines
@ require.min.js:1(anonymous function)
@ require.min.js:1

**Comment by robmadole** [comment]
@kevintweber did you have a local copy of the embed JS that you had on your file system?

**Comment by kevintweber** [comment]
I used the js file on the cdn.  I have redownloaded it below.  (I hope this is what you're looking for.)

Sincerely, Kevin

-----

window.FontAwesomeConfig = {
  asyncEnabled: true,
  autoAccessibility: false,
  useUrl: "use.fontawesome.com",
  code: "\<code removed\>",
  webFontLoaderVersion: "1.6.24"
};
window.FontAwesome||(window.FontAwesome={}),function(){function a(a){this.el=a;for(var b=a.className.replace(/^\s+|\s+$/g,"").split(/\s+/),c=0;c<b.length;c++)d.call(this,b[c])}function b(a,b,c){Object.defineProperty?Object.defineProperty(a,b,{get:c}):a.\_\_defineGetter\_\_(b,c)}if(!("undefined"==typeof window.Element||"classList"in document.documentElement)){var c=Array.prototype,d=c.push,e=c.splice,f=c.join;a.prototype={add:function(a){this.contains(a)||(d.call(this,a),this.el.className=this.toString())},contains:function(a){return-1!=this.el.className.indexOf(a)},item:function(a){return this[a]||null},remove:function(a){if(this.contains(a)){for(var b=0;b<this.length&&this[b]!=a;b++);e.call(this,b,1),this.el.className=this.toString()}},toString:function(){return f.call(this," ")},toggle:function(a){return this.contains(a)?this.remove(a):this.add(a),this.contains(a)}},window.DOMTokenList=a,b(Element.prototype,"classList",function(){return new a(this)})}}(),function(a,b,c){function d(a){var c,d=[],e=b,f=e.documentElement.doScroll,g="DOMContentLoaded",h=(f?/^loaded|^c/:/^loaded|^i|^c/).test(e.readyState);h||e.addEventListener(g,c=function(){for(e.removeEventListener(g,c),h=1;c=d.shift();)c()}),h?setTimeout(a,0):d.push(a)}function e(){var a,c,d,e=b.querySelectorAll(".fa");Array.prototype.forEach.call(e,function(e){a=e.getAttribute("title"),e.setAttribute("aria-hidden","true"),c=e.nextElementSibling?!e.nextElementSibling.classList.contains("sr-only"):!0,a&&c&&(d=b.createElement("span"),d.innerHTML=a,d.classList.add("sr-only"),e.parentNode.insertBefore(d,e.nextSibling))})}function f(a){"undefined"!=typeof MutationObserver&&new MutationObserver(a).observe(b,{childList:!0,subtree:!0})}function g(){var a=b.createElement("link");a.href="https://"+l+"/"+m+".css",a.media="all",a.rel="stylesheet",b.getElementsByTagName("head")[0].appendChild(a)}function h(){var c=b.createElement("script"),d={};s=b.scripts[0],a.WebFontConfig||(a.WebFontConfig={}),d=a.WebFontConfig,d.custom||(d.custom={}),d.custom.families||(d.custom.families=[]),d.custom.urls||(d.custom.urls=[]),d.custom.families.push("FontAwesome"),d.custom.urls.push("https://"+l+"/"+m+".css"),c.src="https://"+l+"/webfontloader/"+n+"/webfontloader.js",s.parentNode.insertBefore(c,s)}function i(){return k&&(d(e),f(e)),j?h():g()}var j=a.FontAwesomeConfig.asyncEnabled,k=a.FontAwesomeConfig.autoAccessibility,l=a.FontAwesomeConfig.useUrl,m=a.FontAwesomeConfig.code,n=a.FontAwesomeConfig.webFontLoaderVersion;a.FontAwesome.load=i}(this,document);try{window.FontAwesome.load()}catch(e){}

**Comment by robmadole** [comment]
yep @kevintweber that's what I was curious about. thanks, I'll take a look at this and see if we can get it fixed for ya.

**Comment by teeterc** [comment]
Is there a workaround?

**Comment by robmadole** [comment]
Not currently @teeterc. This is a hairy one and I'll have to dig into requirejs to figure it out. You can switch your embed code to be CSS instead of JS.

**Comment by robmadole** [comment]
We are going to eventually create specific specific packages that will allow tools like RequireJS to work. This will take a re-architecting of how the CDN works and we aim to do this work in Font Awesome 5. I'm going to close this as we aren't going to invest any more energy in this regard to CDN.

**Comment by pre2612** [comment]
@robmadole is this added to Font-awesome 5. Trying to load a Font-awesome Kit but it doesn't work with require js. Removing require helps load fonts. Any help how to load a kit with require?
