### ISSUE TITLE
Icon Request: fa-issuu

### ISSUE THREAD

**Issue by Keveal** [FortAwesome/Font-Awesome#9260]
I see you have many social networks icons but I would like pusierais the deISSUU icon because it is a brand that is not.

![3bc07aa0-2c9e-11e5-8589-2b83d78716e6](https://cloud.githubusercontent.com/assets/19528218/15464717/2dc62f94-20d1-11e6-9e63-584ac901a519.png)

**Comment by tagliala** [comment]
Duplicate of #1993 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
