### ISSUE TITLE
Icon Request : fa-aparat

### ISSUE THREAD

**Issue by MehdiPiAr** [FortAwesome/Font-Awesome#9261]
hi
this is a popular site's icon  and if u add it's icon to your collection , I'll be thankful
http://www.aparat.com/public/public/images/logo/v2/aparat_icon_color_black_1024.png

**Comment by aethior** [comment]
@tagliala It's a brand icon: https://en.wikipedia.org/wiki/Aparat

**Comment by tagliala** [comment]
Duplicate of #5204, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
