### ISSUE TITLE
Bicycle and Microphone not working

### ISSUE THREAD

**Issue by libsmit** [FortAwesome/Font-Awesome#9263]
Hi,

I have 2 icons on my site that aren't showing... fa-microphone and fa-bicycle.  Please view libbyolson.com to see the issue.

Thanks,
Libby

**Comment by tagliala** [comment]
> fa-microphone and fa-bicycle. 

The actual code shows that you are using `fa-question-circle`

Also please note that you are loading fontawesome 2 times:

```html
<link rel='stylesheet' id='font-awesome_pms-css'  href='http://libbyolson.com/wp-content/themes/stormday/css/font-awesome.css' type='text/css' media='all' />
```

This is the 4.1.0 version but `bike` was added in 4.2.0 so maybe you will not see it the same if the browser loads first the 4.1.0 version. Take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

Closing here, hope it helps
