### ISSUE TITLE
Development or simply customize F-A on windows ?

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#9265]
I tried the "Hacking on Font Awesome" but got stuck at "bundle install". It passed after  removing therubyracer but bundle exec jekyll build doesn't work.

Have anyone here tried F-A development on windows ?

**Comment by tagliala** [comment]
@davegandy do we support development on Windows?

**Comment by tagliala** [comment]
Closing here because of inactivity
