### ISSUE TITLE
Icon request: currency-idr

### ISSUE THREAD

**Issue by timpamungkas** [FortAwesome/Font-Awesome#9268]
Can you please add icon for Indonesian Rupiah (IDR)?
This will be used for e-commerce cash payment icons. Also maybe for other site that requires indonesian currency

IDR logo is basically consists of 2 letters : **Rp**
No special character or image required, only capital "R" and smallcap "p" joined together

Thank you

**Comment by tagliala** [comment]
Duplicate of #1683, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
