### ISSUE TITLE
Icon request: Electric components icons

### ISSUE THREAD

**Issue by darklilium** [FortAwesome/Font-Awesome#9272]
Hello, im developing apps for an Electric Bussiness company and i would like to have some icons related to objects and buildings like:

- Substations,
- Meters,
- Electricity Network,
- Circuits,
- Power outage,
- Street Lights, etc.
- 

Thanks in advice!

![luminaria](https://cloud.githubusercontent.com/assets/8507515/15521241/b24e456e-21d8-11e6-96fe-003505bce2a2.jpg)
![tramo](https://cloud.githubusercontent.com/assets/8507515/15521255/c28522ea-21d8-11e6-90de-721fb3c7bce2.png)
![interrupciones](https://cloud.githubusercontent.com/assets/8507515/15521283/e340aca2-21d8-11e6-8f2a-e88e091d5455.png)

**Comment by Roumed** [comment]
+1

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.
*  Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Street light: #8857
