### ISSUE TITLE
?v=4.6.3 in css file creating trouble in firefox 

### ISSUE THREAD

**Issue by amitshahc** [FortAwesome/Font-Awesome#9273]
> downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: http://192.168.1.254/theme/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 http://192.168.1.254/theme/font-awesome/css/font-awesome.min.css Line 4

I was keep getting above error. and i tried lots of stuff found on the internet. (hosting the fonts on own server)

- CORS issue
- Mime type header config in web server

Other combinations of HTTP headers and Mime types everything that can resolve the issue but nothing solved it.

Solution:

Remove the "?v=4.6.3" and remaining tail from this block (font-awesome.css / font-awesome.min.css).

```
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'), 
  url('../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'),
  url('../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'),
  url('../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'), 
  url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');
  font-weight: normal;
```

Updated to:

```
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot');
  src: url('../fonts/fontawesome-webfont.eot') format('embedded-opentype'), 
  url('../fonts/fontawesome-webfont.woff2') format('woff2'), 
  url('../fonts/fontawesome-webfont.woff') format('woff'), 
  url('../fonts/fontawesome-webfont.ttf') format('truetype'), 
  url('../fonts/fontawesome-webfont.svg') format('svg');
  font-weight: normal;
  font-style: normal;
}
  font-style: normal;
}
```

[SOLVED]

**Comment by tagliala** [comment]
Thanks.  I would get rid of those version query strings, but we should wait for 5.0.0 and Dave should authorize this.

I'm going to close this one, let's refer to #3286

**Comment by jocar6562** [comment]
src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
src: url('../fonts/fontawesome-webfont.eot') ;
took out the ?v=4.6.3 not sure what that was for but could see no difference after testing
This worked fine it was the last thing I needed to do now I have speeded up landing page to 625 mil sec johnc
