### ISSUE TITLE
are there anyways to reverse the icons and text

### ISSUE THREAD

**Issue by pprevalon** [FortAwesome/Font-Awesome#9274]
for example have the icon before the text on a button

**Comment by tagliala** [comment]
sorry, could you please clarify?

https://jsfiddle.net/tagliala/sjugj891/1/

**Comment by pprevalon** [comment]
the my icons are on the right, and the button texts are on the left i 
want to reverse it where the icons are on the left and button texts are 
on the right.

**Comment by tagliala** [comment]
sorry, I don't get it.

fontawesome is like plain text in a `<span>` tag, you can do whatever you can do with plain text via css, see my above example

Closing here

**Comment by pprevalon** [comment]
Im sorry my question was for swift Programming
