### ISSUE TITLE
Icon Request: fa-archive

### ISSUE THREAD

**Issue by matjasw** [FortAwesome/Font-Awesome#9276]
dear,

Is it possible to create an icon to enter an archive?
like in the example?
![archive](https://cloud.githubusercontent.com/assets/19588593/15571018/28da1efe-2339-11e6-8248-1c63b5d9ee46.png)

Kind regards,

M.

**Comment by tagliala** [comment]
We already have an archive icon: http://fontawesome.io/icon/archive/

There is also a request to improve that icon: #1765 

If you think we need another archive icon, please provide an use case and explain why it is important to have both designs

**Comment by matjasw** [comment]
Yes I saw it but it's more like a box and not a closet.

M.

**Comment by aethior** [comment]
@tagliala check #9164. Related? Duplicate? I think are the same icon.

**Comment by tagliala** [comment]
@aethior yes, they look the same, thanks
