### ISSUE TITLE
Icon request: icon-folders

### ISSUE THREAD

**Issue by matjasw** [FortAwesome/Font-Awesome#9278]
dear,

Is it possible to create folder icons for indicate that the user can create, view that it's protected or not, ...
![folder-4](https://cloud.githubusercontent.com/assets/19588593/15571193/cb73bd32-2339-11e6-9d29-fe850cdb15ac.png)
![folder](https://cloud.githubusercontent.com/assets/19588593/15571192/cb73b418-2339-11e6-9acd-feca4ce55546.png)
![folder-1](https://cloud.githubusercontent.com/assets/19588593/15571196/cb78a82e-2339-11e6-927c-3c36dd1eebc8.png)
![folder-2](https://cloud.githubusercontent.com/assets/19588593/15571195/cb75ec74-2339-11e6-808e-c1c55a99f2ed.png)
![folder-3](https://cloud.githubusercontent.com/assets/19588593/15571194/cb75e17a-2339-11e6-84e4-519930e8f606.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

If you want to request `folder-add`, `folder-with-lock` and `folders, folders-o`, please open three new individual requests. Please also take a look here: #1181
