### ISSUE TITLE
Icon mobile-phone is smaller than others

### ISSUE THREAD

**Issue by realtebo** [FortAwesome/Font-Awesome#928]
I notice that mobile phone icon is 'smaller' that others . If you see it side-by-side with, for example, icon-user, it looks like disappearing. Probably due to transparent/too large display.

It's just an opinion

**Comment by henleywc** [comment]
+1

**Comment by omrie** [comment]
+1

**Comment by coltonbrugger** [comment]
+1

**Comment by gtaranti** [comment]
+1

**Comment by PuKoren** [comment]
+1

**Comment by internalfx** [comment]
Hey @davegandy,

Any thoughts on this? The votes seem to roll in at a steady pace.

It's been 2 years, Is there any possibility of a decision?

Whether Yes or No, I'd just like to know.

**Comment by ryanvanderpol** [comment]
Another +1 here.  When put next to the envelope icon (symbolizing email and SMS) the mobile icon looks ridiculously small.

**Comment by dara0418** [comment]
+1, mobile icon looks quite different from others, tablet icon can't really present a mobile phone in most situations.

**Comment by BrendanPC** [comment]
+1, the Mobile icon looks incredibly silly as it is tiny next to any other icon.

**Comment by elgrazo** [comment]
+1 totally agree

**Comment by coderguy** [comment]
+1
at least add one as fa-mobile-big to maintain compatibility

**Comment by pjfsilva** [comment]
+1 for all icons the same height.

icomoon follow a philosophy of laying out all icons on a grid to generate crisp, pixel perfect results and I believe that's the thing to follow.

I actually hate how icon-mobile looks next to icon-desktop and I had to increase font-size. The problem being, increasing font-size from 14px doesn't guarantee pixel perfect results so you always get a blurred mobile icon...

**Comment by sbarre** [comment]
Yet another +1 to make all icons the same size, or provide an alternative version that is.

In a CMS or dynamic page context where I have to set up CSS without knowing what icon I'm using, having some icons be tiny is un-workable.

**Comment by samsullivan** [comment]
I'll throw in my +1. The tablet could be made in landscape () and still appear much larger than a phone. I'd also agree with the one argument that this design decision seems to have been made to solve an edge case, and the +1's in this thread highlight that this isn't an edge case. More often or not a phone icon is going to be used with many other non-tablet icons and it'll be visually jarring and "use fa-tablet" isn't a logical move (in fact, I just looked in my code and wondered why I was using tablet, switched it to mobile, and then stumbled across this).

**Comment by newmanw** [comment]
+1

**Comment by jacob-hutchings** [comment]
+1

**Comment by jotiheranbnach** [comment]
+1

**Comment by tagliala** [comment]
I'm going to reopen this because of

1. Other +1s
2. Font Awesome Black Tie platform icons have the same height

![screen shot 2016-04-23 at 16 48 09 1](https://cloud.githubusercontent.com/assets/556268/14762127/357654aa-0973-11e6-9463-10a314b24abd.png)

Maybe Dave changed his mind

**Comment by MohammadDayeh** [comment]
+1
Icon mobile-phone is too small, it is hard to see with a small font-size < 20px

**Comment by mw90** [comment]
+1
Icons should have a uniform size.

**Comment by yamiko-ninja** [comment]
+1

**Comment by CROSP** [comment]
+1, Why this problem has not been solved yet ? More than two years. 
I don't want to use another icon set because of only one icon.

**Comment by tagliala** [comment]
@CROSP https://github.com/FortAwesome/Font-Awesome/issues/928#issuecomment-15955601

**Comment by opensourceame** [comment]
+1. Icons are symbols, not anatomical representations of things. The logic behind this means the man icon should be taller than the woman icon. Doesn't make any kind of sense.

**Comment by jamesfiala** [comment]
+1. The reasoning for #928 is not good- you want it to look good in that one use case, instead of having it look good and be uniform with the rest of the icon set. Maybe you should make it look uniform and then people who need to show it next to a desktop icon (which I bet are in the minority) can style it to make it look smaller if they so choose.

**Comment by CROSP** [comment]
Possible solution is to use Font generator like https://icomoon.io/ and select all needed icons. This solution possible in case of static icons. And by the way it will save font size and makes page loading a bit faster

**Comment by banagale** [comment]
I realize this is closed but this icon is too small and requires custom CSS to match other icons.

**Comment by tagliala** [comment]
Font Awesome 5 should address issues like this, providing better consistency throughout the icon set

> Every icon on new grid system for consistency throughout the set 
>
> *Source: https://www.kickstarter.com/projects/232193852/font-awesome-5*

**Comment by banagale** [comment]
I see. Thanks for the link. Onward, then chaps. Wot-wot.

**Comment by motin** [comment]
3.5 years of discussion and not a single CSS workaround in the thread? :) Anyone has a drop-in workaround until font-awesome 5 is released?

**Comment by jamesfiala** [comment]
Yeah just override the font-size for the icon you need... you may have to
add some margin or whatnot to get it looking good, but it's pretty easy.

**Comment by lxmfly123** [comment]
That's a really ridiculous reason for making a smaller icon.

**Comment by motin** [comment]
> I had to create 17 individual CSS rules just to fix the mobile phone icon size

@andreszs Care to share your CSS rules in a gist? Thanks

**Comment by wassereimer86** [comment]
+1

**Comment by svmarek** [comment]
+1

**Comment by tagliala** [comment]
**Heads-up!**

As I mentioned before, this has been fixed in Font Awesome 5

https://jsfiddle.net/tagliala/wks0e6pa/52/

🔒
