### ISSUE TITLE
Icon Request: fa-icon-team

### ISSUE THREAD

**Issue by saurabh-vijay004** [FortAwesome/Font-Awesome#9280]
Hi,
Can anyone help in creating a font awesome icon for a team. :)
![team-icon](https://cloud.githubusercontent.com/assets/18412979/15572434/35fc9c36-235e-11e6-9132-0f8ec139b731.png)
Need this icon to show we are a team in my application

**Comment by tagliala** [comment]
Can't you use http://fontawesome.io/icon/users/ ?

**Comment by aethior** [comment]
@tagliala I think you can close here.
