### ISSUE TITLE
Icon request: Bootstrap icon

### ISSUE THREAD

**Issue by MajkelD** [FortAwesome/Font-Awesome#9293]
Hello,
I think it'd be useful to get Bootstrap icon in Font Awesome :)
Please consider this

Many thanks,
Michał Droździk

**Comment by tagliala** [comment]
Duplicate of #1828 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
