### ISSUE TITLE
Icon request: icon-disqus

### ISSUE THREAD

**Issue by UncaughtTypeError** [FortAwesome/Font-Awesome#9296]
![disqus-icon](https://cloud.githubusercontent.com/assets/19621089/15634818/f782e8da-25cd-11e6-9959-ab4ac42385b1.png)

**Comment by tagliala** [comment]
Duplicate of #2690 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by UncaughtTypeError** [comment]
Will do so in future, thank you.
