### ISSUE TITLE
Icon Request: Maki MapBox Icons

### ISSUE THREAD

**Issue by baskinomics** [FortAwesome/Font-Awesome#930]
Is it possible for you to replicate the Maki MapBox icon set as a font set instead of a set of SVG/PNGS? That would be super awesome.

http://mapbox.com/maki/

**Comment by tagliala** [comment]
Hi, since this is a request for a set, I'm going to close here

**Comment by tagliala** [comment]
Check out our Maps category: https://fontawesome.com/icons?c=maps
