### ISSUE TITLE
Icon Request: Knit, crochet & yarn

### ISSUE THREAD

**Issue by Sknitters** [FortAwesome/Font-Awesome#9300]
I would really appreciate icons for **knitting** (knitting needles) and **crocheting** (crochet hook). Also icons for **yarn** or **wool** would be great!
Need this for my knitting blog :)

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please +1 that one.

#7969

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.

**Comment by sivamurugan03** [comment]
+1

**Comment by RinskeBosma** [comment]
+1

An icon for crochet please! 

Maybe something like: 
![images](https://user-images.githubusercontent.com/33757397/51558003-af767780-1e7e-11e9-8324-13629f518179.png)
Or
![haaknaaldmetbol](https://user-images.githubusercontent.com/33757397/51558062-cd43dc80-1e7e-11e9-8df9-b2f62a465064.png)
