### ISSUE TITLE
Icon request: icon-user-thin

### ISSUE THREAD

**Issue by Gregouz** [FortAwesome/Font-Awesome#9301]
The fa-user icon is not professional enough

This kind would be more appropriate :

![user_male2-512](https://cloud.githubusercontent.com/assets/15652906/15646734/b81aa42a-265f-11e6-9a91-8ef8646855bb.jpg)

![user-male-silhouette_318-55563](https://cloud.githubusercontent.com/assets/15652906/15646738/bc849bb0-265f-11e6-96a8-3efc3e82927b.png)

**Comment by tagliala** [comment]
There is a request for changing the user icon to human shape #1241

This is planned for 5.0.0 milestone

I'm going to consider this a duplicate

Closing here

**Comment by Gregouz** [comment]
Tks
