### ISSUE TITLE
Icon Request: fa-door

### ISSUE THREAD

**Issue by seraasch** [FortAwesome/Font-Awesome#9303]
This font is used by the openhab control-panel  https://github.com/HomeAutomationForGeeks/openhab-controlpanel
which used used to provide a nice control panel for home automation use

This could really use a font that looks like a door

**Comment by tagliala** [comment]
Duplicate of #2921, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
