### ISSUE TITLE
Icon Request: fa-garagedoor

### ISSUE THREAD

**Issue by seraasch** [FortAwesome/Font-Awesome#9304]
This font is used by the openhab control-panel  https://github.com/HomeAutomationForGeeks/openhab-controlpanel
which used used to provide a nice control panel for home automation use

This could really use a font that looks like a garage door

**Comment by tagliala** [comment]
I'm going to consider this a duplicate of #713, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
