### ISSUE TITLE
Icon Request: fa-discount

### ISSUE THREAD

**Issue by maverickpravin** [FortAwesome/Font-Awesome#9309]
kindly create a new icon for discount

**Comment by tagliala** [comment]
could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Include a few use cases for your requested icon. How do you plan on using it?
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by tagliala** [comment]
Closing here in favor of #10238
