### ISSUE TITLE
Icon-request: icon-customerservice; icon- deliveryandpackaging; icon-qualitycontrol

### ISSUE THREAD

**Issue by Creepy-Cat** [FortAwesome/Font-Awesome#9311]
I have made three icons for my website, but my website's IT support team directed me here. I can't find any icon related to the three I have created and would like to share it here so that this hub has 3 more new icons, and also to get the coding for the icon's I have. 

Any e-mail address that I can give the icons to you?

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Any e-mail address that I can give the icons to you?

Please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome
