### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by ssollety90** [FortAwesome/Font-Awesome#9313]
![moneytransferv2](https://cloud.githubusercontent.com/assets/17132453/15708409/4a4c0812-27b3-11e6-8057-caaf3656b878.png)
![pcpv2](https://cloud.githubusercontent.com/assets/17132453/15708410/4a4d5d16-27b3-11e6-8616-93e34455eb3d.png)
![receiverv2](https://cloud.githubusercontent.com/assets/17132453/15708411/4a6a847c-27b3-11e6-9e5e-cd083055a2c2.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Also, there are already user add and user delete:
http://fontawesome.io/icon/user-plus/
http://fontawesome.io/icon/user-times/
