### ISSUE TITLE
Icon request:fa-share-o

### ISSUE THREAD

**Issue by dougkillmer** [FortAwesome/Font-Awesome#9314]
Need an open share icon.  The following styles represent what I'm looking for, but won't be supported in non-webkit browsers.

-webkit-text-fill-color: transparent; 
-webkit-text-stroke-width: 1px;
-webkit-text-stroke-color: #333;

![image](https://cloud.githubusercontent.com/assets/11560014/15717685/ea3a3852-27dc-11e6-9364-f829f87a7457.png)

**Comment by Celti** [comment]
You can fake text-stroke in non-webkit browsers using text-shadow, though I haven't tried it with Font Awesome... however, throwing it into a [CodePen](https://codepen.io/Celti/pen/yJYVjV) seems to work in the several I have at hand!

**Comment by dougkillmer** [comment]
Thanks, that does work, but the points don't look as sharp as they could.  

![image](https://cloud.githubusercontent.com/assets/11560014/16667494/9969f8be-4441-11e6-8fd1-f4dee114335c.png)

**Comment by tagliala** [comment]
Available in FA 5 Pro
https://fontawesome.com/icons/share?style=regular
