### ISSUE TITLE
Icon Request: fa-islamic

### ISSUE THREAD

**Issue by lorosukmo** [FortAwesome/Font-Awesome#9315]
can I request font awesome for islamic edition?
I'll post for Ramadan edition on my website.
example:
![image](https://cloud.githubusercontent.com/assets/4507180/15723617/765c11da-286d-11e6-92f1-782a7abb4d85.png)

**Comment by MSalehi** [comment]
yeah i have same request too... :+1:

**Comment by tagliala** [comment]
Sorry, I can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

It's ok to have an icon or a couple of icons to represent the islamic religion but I need proper requests

> * Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by nihatokur** [comment]
can I request font awesome for islamic edition?

![hadj](https://cloud.githubusercontent.com/assets/19815529/15893942/92632d8c-2d8b-11e6-9cc4-81d689176128.png)

Thanx for help

**Comment by tagliala** [comment]
@nihatokur please take a look at my above comment https://github.com/FortAwesome/Font-Awesome/issues/9315#issuecomment-224570159

**Comment by tagliala** [comment]
kaaba: #9371
