### ISSUE TITLE
Icon request:fa-kakaotalk

### ISSUE THREAD

**Issue by seoulnc** [FortAwesome/Font-Awesome#9316]
'kakao talk' icon needs.......
![kakako03](https://cloud.githubusercontent.com/assets/19699632/15731384/af9bf784-28af-11e6-9f9b-33bf35f4fe71.png)

**Comment by tagliala** [comment]
Duplicate of #3688 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
