### ISSUE TITLE
Icon request:fa-flickr-i

### ISSUE THREAD

**Issue by HaydnTrigg** [FortAwesome/Font-Awesome#9317]
Flickr icon but only the inside two circles

**Comment by tagliala** [comment]
Duplicate of #9317, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by HaydnTrigg** [comment]
This is issue #9317 ...?!?!?

**Comment by tagliala** [comment]
sorry, #4018
