### ISSUE TITLE
Access-Control-Allow-Origin on https://use.fontawesome.com

### ISSUE THREAD

**Issue by rflorence** [FortAwesome/Font-Awesome#9322]
I'm getting this error in Chrome today. I was not getting it yesterday, so were there any recent changes to the server headers?

>
Font from origin 'https://use.fontawesome.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:9000' is therefore not allowed access.
>

I have the following inside my `<head>` tag:

```
<script src="https://use.fontawesome.com/f9ef4ac2e4.js"></script>
```

**Comment by rflorence** [comment]
Possibly related to https://github.com/FortAwesome/Font-Awesome/issues/9310

**Comment by tagliala** [comment]
Let's use #9310
