### ISSUE TITLE
Icon Request: fa-Context-menu-vertical / fa-Context-menu-vertical 

### ISSUE THREAD

**Issue by ShwetaKhedkar** [FortAwesome/Font-Awesome#9323]
Need to use these new icons - three vertical dots inside a circle & three horizontal dots inside a circle to indicate context menu appearing on a row inside a table. This context menu will have additional action items pertaining to selected individual row. 
![contextmenu_horizontal](https://cloud.githubusercontent.com/assets/19713954/15753129/71b8cc2a-28bf-11e6-8d2e-9646b9d4fbf8.png)
![contextmenu_vertical](https://cloud.githubusercontent.com/assets/19713954/15753128/71b879e6-28bf-11e6-9d5e-461af9682a9d.png)

**Comment by tagliala** [comment]
Please use

http://fontawesome.io/icon/ellipsis-v/
http://fontawesome.io/icon/ellipsis-h/

with the [stacking feature](http://fontawesome.io/examples/#stacked) or [custom css](http://jsfiddle.net/tagliala/4Lcpvhoo/1/)

closing here
