### ISSUE TITLE
Icon request: fa-artstation (ArtStation)

### ISSUE THREAD

**Issue by leonardteo** [FortAwesome/Font-Awesome#9325]
Hi,

I was wondering if it's appropriate to request for an `fa-artstation` icon to be added, for people to add icons/links to their [ArtStation](https://www.artstation.com) accounts. ArtStation has gotten very big as a social network for professional artists and is now ranked 3500 on Alexa.

Their logo is available here: https://www.artstation.com/about/logo

Thanks!

Leo

**Comment by tagliala** [comment]
Duplicate of #5354, please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by leonardteo** [comment]
My bad sorry! Thanks
