### ISSUE TITLE
Shopping-bag issue

### ISSUE THREAD

**Issue by lebadapetru** [FortAwesome/Font-Awesome#9329]
There is a problem with one of your icons which i really need to use(unicode: f290 aka shopping-bag)

This is the way i'm using this icon:

.carticon::after{
	font: normal 2vw 'FontAwesome';
	content: "\f290";
}

It shows only a square , and i don't know why because the others are working just fine.

**Comment by tagliala** [comment]
> There is a problem with one of your icons

Sorry, cannot confirm. Also, this seems not a problem with Font Awesome itself, it looks more like an issue generated by your customization.

Could you please provide a fiddle showing the issue? You can use this one as a base: https://jsfiddle.net/tagliala/4Lcpvhoo/2/

Meanwhile, closing here

**Comment by tagliala** [comment]
Please also make sure that you are using Font Awesome >= 4.5.0 because `shopping-bag` was introduced in 4.5.0

http://fontawesome.io/icon/shopping-bag/

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting

**Comment by lebadapetru** [comment]
That was the problem, i had an older version,Thank you

**Comment by tagliala** [comment]
you're welcome, glad you solved
