### ISSUE TITLE
Icon request: itinerary (on a map)

### ISSUE THREAD

**Issue by namezero** [FortAwesome/Font-Awesome#933]
is it possible to add an icon for an "itinerary" 
<s>also an icon for "GPS" (gps on and gps off)</s>
that would be awesome ;) 

edit by @tagliala
Example: 
![image](https://user-images.githubusercontent.com/556268/28458607-a443e5d0-6e0a-11e7-964b-9ab42103d291.png)

**Comment by ralberts** [comment]
+1

**Comment by namezero** [comment]
https://cdn2.iconfinder.com/data/icons/navigation-location/512/route_pin_gps_locate_location_map_marker_navigate_navigation_plan_road_-512.png
here an example of icon-itinerary

**Comment by Nanakii** [comment]
+1 for this one

**Comment by arnevn** [comment]
+1

**Comment by ccloquet** [comment]
+1

**Comment by PlassJ** [comment]
+1

**Comment by lenamtl** [comment]
+1 for icon-itinerary 

What I'm looking for is if possible 2 different icons
-origin icon
-destination icon

**Comment by dheil** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/route?style=solid
