### ISSUE TITLE
Icon Request: icon-wwd

### ISSUE THREAD

**Issue by apsaraaruna** [FortAwesome/Font-Awesome#9330]
I want to request new brand icon for our company logo. company is "WrightWay Digital" 
http://wrightwaydigital.com/
here the png and PSD

[wwd.zip](https://github.com/FortAwesome/Font-Awesome/files/297498/wwd.zip)

![wwd](https://cloud.githubusercontent.com/assets/567196/15777857/1f22fcc8-29b0-11e6-8a65-f01044937560.png)

**Comment by apsaraaruna** [comment]
is this possible to add this logo icon..??

**Comment by tagliala** [comment]
@apsaraaruna please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by apsaraaruna** [comment]
Thank you ...

**Comment by apsaraaruna** [comment]
can anyone tell how to use this icon now? i download the font-awesome-master files and use it like this.. not working <i class="fa icon-wwd" aria-hidden="true"></i>

**Comment by tagliala** [comment]
@apsaraaruna this is an icon request. The [wiki page](https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome) I gave you before says:

> Font Awesome receives dozens of new requests every day. Some of them will eventually be included, others will not. [Popularity](https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+sort%3Acomments-desc) is one of the factors taken into account, but it is not the only one.

This is a list of brand requests sorted by decreasing popularity: https://github.com/FortAwesome/Font-Awesome/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+icon%22+sort%3Acomments-desc+label%3A%22brand+icons%22

**Comment by apsaraaruna** [comment]
OK. thank you...
