### ISSUE TITLE
Icon request: icon-swimming-ppol

### ISSUE THREAD

**Issue by bobjohnston2000** [FortAwesome/Font-Awesome#9334]
I would like a swimming pool icon for my rental/property sale website...

like this (see image file)

![pool](https://cloud.githubusercontent.com/assets/19742059/15797544/889af4b2-2a46-11e6-9c00-54284f976f94.JPG)

**Comment by aethior** [comment]
Hi @bobjohnston2000,

This request is duplicate of #3295. Please +1 that.

Regards.

**Comment by imperat0r** [comment]
+1
