### ISSUE TITLE
Question about the use of +1 method

### ISSUE THREAD

**Issue by GizMecano** [FortAwesome/Font-Awesome#9337]
Having noticed that issues can now by sorted by "reaction", a [quite recent feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) implemented by GitHub, I wonder if this new ability could fully replace the `+1` "method", [recommended in the contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons), in order to reduce length of issues and, more particularly, of icon requests.

**Comment by tagliala** [comment]
I wish there it was a simple way to convert +1s to reactions.

At the moment I don't know what to do, I'm opened to ideas.

I think I will sort requests both by number comments *and* reactions to check the most popular ones when a new release is round the corner

**Comment by GizMecano** [comment]
> I wish there it was a simple way to convert +1s to reactions.

Indeed, I understand the problem: I don't know if GitHub staff has thought to this possibility.

> At the moment I don't know what to do, I'm opened to ideas.

For futur issues (and notably icon requests), I suppose that _reactions_ could advantageously replace the current method. What about revise `CONTRIBUTING.md`, by replacing: "_If a request is found, please +1 that one_" by something like "_If a request is found, please add a reaction :+1: to that one_" for example?

**Comment by tagliala** [comment]
@GizMecano for the moment, I've updated contributing guidelines and docs (the change will be live when Dave will rebuild the docs). I will try to contact github staff to check if they can make some kind of automatic conversion from comments to reactions. Thanks for the heads-up

**Comment by tagliala** [comment]
Unfortunately there is no way to convert "👍"s  and "+1"s to reactions
