### ISSUE TITLE
Icon Request: fa-telegram

### ISSUE THREAD

**Issue by MSalehi** [FortAwesome/Font-Awesome#9338]
Hi
Please add the telegram brand to fontawesome icons.
![telegram_alternative_logo svg_](https://cloud.githubusercontent.com/assets/5165298/15801923/382232d4-2ab9-11e6-8ed4-1114ccc57efa.png)

**Comment by tagliala** [comment]
Duplicate of #3034 , please +1 that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
