### ISSUE TITLE
Icon request: fa-package

### ISSUE THREAD

**Issue by Cartman34** [FortAwesome/Font-Awesome#9341]
Hi,

Could we have a package icon ?
Not a post package, not a box, a programming package one, like the eclipse/java one.

![package_obj](https://cloud.githubusercontent.com/assets/375425/15804664/118cd928-2b11-11e6-9d08-28d9ebc7e781.png)

**Comment by tagliala** [comment]
The provided example doesn't look like a package.

We need a better title and also a use case because #908 has the same title and a similar case of this one (mac osx package)

**Comment by Cartman34** [comment]
This is really a representation of programming package, this is used in Eclipse, this is only an example for Font-Awesome.
Here an use case in Eclipse.
![image](https://cloud.githubusercontent.com/assets/375425/15804751/ec450d7c-2b13-11e6-81b6-d35ea7fe6a3a.png)
Other IDE may have other representation but i like this one, this is really diffentiating package from folder as programming package, not an archive.

**Comment by tagliala** [comment]
Sorry but I cannot leave this open because I can't have two `icon-package` requests.
