### ISSUE TITLE
Icon Request: icon-boat

### ISSUE THREAD

**Issue by Woensdag** [FortAwesome/Font-Awesome#9346]
There is ship, great but when it's small it is hard to see.

We do have truck, a nice to see sideview icon.

icon-boat can be a sideview of a boat. 
In this case shipping (why not trucking??) will be done by boat and not truck.
Or used to indicate drop-shipment.

**Comment by tagliala** [comment]
I'm going to consider this a duplicate of #9119 , please add a 👍  reaction to that request

closing here
