### ISSUE TITLE
Include `icons.yml` in bower package

### ISSUE THREAD

**Issue by mburtscher** [FortAwesome/Font-Awesome#9347]
It'd be very positive for applications using Font Awesome if the `icons.yml` file would be included in the bower package.

For instance we'd like to give Administrators the option to choose from Font Awesome icons. For this we parse the `icons.yml` and show all icons the the user. Since it's not included in the bower package we have to add it to our source manually.

**Comment by tagliala** [comment]
Sorry but icons.yml is not supposed to be in `bower.json`, we are following [its specs](https://github.com/bower/spec/blob/master/json.md)

Please use overrides:
```json
  "overrides": {
    "font-awesome": {
      "main": [
        "./src/icons.yml"
      ]
    }
  }
```

Hope it helps, closing here

Ref: #6227

**Comment by kincaider** [comment]
Add
