### ISSUE TITLE
Icon request: icon-sf

### ISSUE THREAD

**Issue by ili-codes** [FortAwesome/Font-Awesome#9348]
Brand Icons: SourceForge

model after:
![sf](http://ili-codes.github.io/assets/css/images/sf_icon.png)
http://ili-codes.github.io/assets/css/images/sf_icon.png

**Comment by aethior** [comment]
Hi @ili-codes,

This request is duplicate of #1178. Please +1 that.

Regards.

**Comment by ili-codes** [comment]
No problem.

**Comment by tagliala** [comment]
closing here
