### ISSUE TITLE
Icon Request: fa-stomach

### ISSUE THREAD

**Issue by Bleene** [FortAwesome/Font-Awesome#9357]
![screen shot 2016-06-07 at 10 56 53 pm](https://cloud.githubusercontent.com/assets/19799274/15858307/2c94857e-2d03-11e6-9da2-330ea811f70a.png)
Please!

**Comment by tagliala** [comment]
@Bleene all your requests are valid, but please consider using a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, **or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome**.
