### ISSUE TITLE
Icon Request: icon-ruble

### ISSUE THREAD

**Issue by pvkovalev** [FortAwesome/Font-Awesome#9366]
Hi there! 
Please add more currencies i.e. [Russian ruble ](https://en.wikipedia.org/wiki/Russian_ruble)
It is useful to to have those icons to specify things like price, etc. in different websites and apps (especially for internal market)

https://en.wikipedia.org/wiki/Russian_ruble#/media/File:Ruble_sign_PT_Sans.png

![image](https://cloud.githubusercontent.com/assets/3504204/15884808/ae96dfa0-2d07-11e6-839d-26714fc51d41.png)

Thank you!

**Comment by tagliala** [comment]
http://fontawesome.io/icon/rub/

Closing here

**Comment by pvkovalev** [comment]
![image](https://cloud.githubusercontent.com/assets/3504204/15886850/ffb49dc6-2d13-11e6-8dbe-2c1df581aea6.png)

 Thank you! 👍
