### ISSUE TITLE
fa-qq icon update

### ISSUE THREAD

**Issue by CantonBolo** [FortAwesome/Font-Awesome#9368]
QQ icon has update recently.
The new icon:
![fa-qq-new](http://a1.mzstatic.com/us/r30/Purple30/v4/05/a8/8f/05a88f68-b541-2023-6154-502b157631b4/icon175x175.png)
The old icon:
![fa-qq-old](https://lh3.ggpht.com/mL6sQwRKT24FMVm8cJaQ672HlNtuMiGfgQ00o62u_kSl236y9OuE4SC6PJBZdXgAZro=w300)

**Comment by tagliala** [comment]
Font Awesome is limited to single color

http://fontawesome.io/icon/qq/

Is there any single color example of the qq logo?

**Comment by CantonBolo** [comment]
Here:
![fa-qq-new](http://sqimg.qq.com/qq_product_operations/im/mac/4.2.5/vinfo.png)
This is white color
![fa-qq-new](http://file.digitaling.com/eImg/uimages/20160503/1462246889633526.jpg)
The right one is new.

**Comment by tagliala** [comment]
@davegandy please take a look at this

**Comment by davegandy** [comment]
Honestly, I cannot find a single vector version of this new logo anywhere at all. Unless we find one before 4.7. is released, we'll punt to 5.0.

**Comment by 907544030** [comment]
There is a QQ brandbook in [ISUX](https://isux.tencent.com/book),ISUX is a UX design team of Tencent.You can get the vector logo from the [pdf file](http://isux-10000718.cos.myqcloud.com/QQ_brandbook.pdf).:)

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes
