### ISSUE TITLE
Icon request: icon-postgres

### ISSUE THREAD

**Issue by asheshv** [FortAwesome/Font-Awesome#9369]
Hi,

Can you please create a brand icon for open source community project for PostgreSQL?
Please take a look at this - https://wiki.postgresql.org/wiki/Logo.

Thanks.

**Comment by tagliala** [comment]
Please consider using mfizz for technology icons

https://github.com/fizzed/font-mfizz

**Comment by asheshv** [comment]
Thanks for the suggestions.

We're already using font-mfizz for the same purpose.
But - it does not make sense to use a separate font for one icon.

**Comment by axelfontaine** [comment]
Duplicate of #6672

**Comment by aethior** [comment]
> Duplicate of #6672

@tagliala check here please.
