### ISSUE TITLE
icon request: fa-arrow-ne, fa-arrow-nw fa-arrow-se, fa-arrow-sw

### ISSUE THREAD

**Issue by lamarant** [FortAwesome/Font-Awesome#937]
Love this font/icon set. Would love to see diagonal direction arrows. You currently have NSEW...would love NE, SE, NW, SW to complete the set.

**Comment by stone776** [comment]
Still nothing here?

+1

**Comment by MNessa** [comment]
+1

**Comment by revof11** [comment]
+1

**Comment by weightyfoe** [comment]
+1 also possible to add aliases for all wind directions? N, NNE, NE, ENE, E etc etc?

**Comment by felimartina** [comment]
+1 Also would love to have NW, NE, SW and SE arrows

**Comment by maenthoven** [comment]
+1

**Comment by r-man** [comment]
+1

**Comment by Sotapanna** [comment]
I too,  this seems really basic and OLD to not be implemented. (please??)
I'd prefer it for all styles of arrows,  
plain, Circle-o,  circle-inverted, and long arrows...      I want to use them as legends on a map.

**Comment by TimGonnet** [comment]
+1

**Comment by justinh00k** [comment]
why is this still not in

**Comment by lucasjohnston** [comment]
really don't understand why diagonal arrows aren't in fa? seems like such a basic thing to be missing 😬

**Comment by justinh00k** [comment]
A work around is that you can rotate the icons (say 45 degrees) to get them
to be diagonal.

**Comment by sensibleworld** [comment]
This is now available in the v6 Alpha release: https://fontawesome.com/download
