### ISSUE TITLE
Icon Request: fa-hadj

### ISSUE THREAD

**Issue by nihatokur** [FortAwesome/Font-Awesome#9370]
Hi.
I need hadj icon (Kaaba) or muslim religion icon.
Thanx for help.

![stock-illustration-59992584-islamic-icon](https://cloud.githubusercontent.com/assets/19815529/15887829/045e1916-2d6d-11e6-855e-26b1465c5d5e.jpg)

**Comment by tagliala** [comment]
Duplicate of #9315 , please take a look there
