### ISSUE TITLE
Icon request: thought-bubble

### ISSUE THREAD

**Issue by sodiumlights** [FortAwesome/Font-Awesome#9375]
To compliment the comment / speech bubble icon, can we have a thought bubble icon?

Personally I'd use it for "I've got a suggestion to make" icon.

**Comment by tagliala** [comment]
Duplicate of #1863, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
