### ISSUE TITLE
Icon request:empty-checkbox

### ISSUE THREAD

**Issue by sodiumlights** [FortAwesome/Font-Awesome#9376]
To compliment fa-check-square-o and fa-edit, can we have the square by itself?

Usage example : use the empty box as a checkbox replacement with fa-check-square-o as the checked state.

**Comment by tagliala** [comment]
Sorry, didn't get this one

Are you requesting http://fontawesome.io/icon/square-o/  ?

**Comment by sodiumlights** [comment]
I'm an idiot. Ignore. Searched the cheatsheet many times and somehow never saw it.

**Comment by tagliala** [comment]
no problem 👍
