### ISSUE TITLE
Icon request: fa-box and fa-box-open

### ISSUE THREAD

**Issue by bkielbasa** [FortAwesome/Font-Awesome#9377]
It would be cool to have a parcel/package icon to represent for example the way how you want to send items to the customer. Some ideas how it could look like: https://cdn0.iconfinder.com/data/icons/business-mix/512/cargo-512.png or https://cdn4.iconfinder.com/data/icons/unigrid-finance/58/014_product_crate_package_box_parcel_shipping_bundle_cargo_5-512.png

**Comment by tagliala** [comment]
Duplicate of #908 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
