### ISSUE TITLE
Icon request: icon-artstation

### ISSUE THREAD

**Issue by bilski** [FortAwesome/Font-Awesome#9379]
Hi,

Would it be possible for somebody to add an artstation icon to the set please?
I use it to link to my artstation page.

Cheers,

Bilski

Example:

![artstation](https://cloud.githubusercontent.com/assets/19836761/15928340/ac006f1c-2e89-11e6-8e5e-97dba172a008.png)

**Comment by tagliala** [comment]
Duplicate of #5354 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
