### ISSUE TITLE
Icon Request: fa-mechanical-shovel (digger)

### ISSUE THREAD

**Issue by luchi20** [FortAwesome/Font-Awesome#9380]
Hello,
Could you add an icon for a mechanical shovel?something like a machine construction.  It is very util for everyone.
Could be: fa-shovel-construction
Something like:

![construccion](https://cloud.githubusercontent.com/assets/19836484/15928552/e99aa9c6-2e1d-11e6-84fa-96cf6807a8e9.png)

Thank you very much

**Comment by tagliala** [comment]
Strictly related to #4084

**Comment by tpeelstand** [comment]
So, I made this icon. It would work pretty well as a font-awesome icon. something like fa-construction.

White version is a bit difficult to see, if you drag it to you desktop you can look at it better. Looks the same as the black version.

White version (larger):
skidsteer-and-excavator-icon

Black version (small):
skidsteer-and-excavator-icon-sm-invert

**Comment by maartenmg** [comment]
+1

**Comment by aethior** [comment]
> Strictly related to #4084

And related or duplicated of #2997?

**Comment by tagliala** [comment]
Ah, yes. Let's use this one (more upvotes)

**Comment by tagliala** [comment]
Duplicate of #5305
