### ISSUE TITLE
Icon Request: fa-user-with-construction-helmet

### ISSUE THREAD

**Issue by luchi20** [FortAwesome/Font-Awesome#9381]
Hello,
Could you add an icon for worker? worker for construction.  It is very util for everyone.
Could be: fa-worker  or fa-user-worker
Something like:
![obrero](https://cloud.githubusercontent.com/assets/19836484/15928174/bf7912c4-2e1b-11e6-9f05-caa9dbb1cdad.png)

Thank you very much

**Comment by tagliala** [comment]
Related to #3934

**Comment by tagliala** [comment]
This icon is available in FA Pro: https://fontawesome.com/icons/user-hard-hat?style=solid
