### ISSUE TITLE
Icon request fa-kayaking; fa-swimming; fa-trekking;

### ISSUE THREAD

**Issue by haongz** [FortAwesome/Font-Awesome#9384]
please, make new icon for activities, same as: kayaking, trekking, swimming, ..etc

thanks

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

swimming: #5771

please open new individual request for other activities , having care of searching before
