### ISSUE TITLE
Icon Request: icon-furniture

### ISSUE THREAD

**Issue by comparekar** [FortAwesome/Font-Awesome#9391]
Hi 
Please add more icons related to online shoping cattegories like footwear,clothing,furniture,decoration etc. I occasionally checked your website but dint found these type of icons from long time and people are also posting these icons request so its again a request from me.
thnks

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
