### ISSUE TITLE
Icon Request: Instagram

### ISSUE THREAD

**Issue by paper9oll** [FortAwesome/Font-Awesome#9393]
Hi Developer,

Please release a inverse `fa-instagram` icon as the new instagram logo does not goes well with `:hover` styles

Thanks You.

**Comment by tagliala** [comment]
Duplicate of #9223, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by paper9oll** [comment]
I actually searched but don't understand what is "squared" hence opening a new issue/request.

Anyway thanks you

**Comment by tagliala** [comment]
It is like [facebook-square](http://fontawesome.io/icon/facebook-square/), [twitter-square](http://fontawesome.io/icon/twitter-square/)...
