### ISSUE TITLE
Help with overriding icons

### ISSUE THREAD

**Issue by designermonkey** [FortAwesome/Font-Awesome#9394]
I have a design to implement that has stipulated specific icons to replace those in font awesome (which is irritating).

I know how I can easily override specific icons in the font using the classes and `content` css property, and all is working ok in the implementation. Apart from...

None of the icons I have in the font I have generated line up with the font awesome set. Some of the glyphs I have to implement are wider than the fa set, all of them float to the top of the font compared to the fa set which are all aligned properly.

I know it's asking a lot, but could you guys give me any advice on things like what the canvas size is for your glyphs? Any special tools you use to generate the fonts?

**Comment by tagliala** [comment]
please take a look here

https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

hope it helps
