### ISSUE TITLE
Icon Request: Animal Icons

### ISSUE THREAD

**Issue by danfiscus** [FortAwesome/Font-Awesome#9395]
I feel that a major missing set of icons is animal icons. There should be a number of icons, one for each fairly common animal. This would make the icon font extra useful.

**Comment by PeckySF** [comment]
Oh that would be Awesome !!! :+1:

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

cat: #2226 
dog: #1317 
horse: #2049
and many others
