### ISSUE TITLE
CDN outdated CSS

### ISSUE THREAD

**Issue by sanjeshsodha** [FortAwesome/Font-Awesome#9400]
The following icons and unicodes do not render the icon because they are missing on the CDN version.

.fa-shopping-bag:before {
  content: "\f290";
}
.fa-shopping-basket:before {
  content: "\f291";
}

**Comment by tagliala** [comment]
could you please provide more details?

**Comment by sanjeshsodha** [comment]
Seems to be working again, problem solved :+1:
