### ISSUE TITLE
Icon request: fa-resp

### ISSUE THREAD

**Issue by mustafapiynirci** [FortAwesome/Font-Awesome#9402]
Icon that represents responsive with mobile, tablet and desktop screen sizes.

https://gyazo.com/8337b7da1d109f2142c0621c0d5810a3

**Comment by tagliala** [comment]
Duplicate of #1446, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by mustafapiynirci** [comment]
Yes im sorry, thankyou

**Comment by tagliala** [comment]
no problem :+1:
