### ISSUE TITLE
Icon Request: Running, Movie Clapboard, Writing board

### ISSUE THREAD

**Issue by andritanuarto** [FortAwesome/Font-Awesome#9403]
Hi there I'm wondering if it's possible to make.

Running Icon - like https://www.google.ca/search?q=running+icon&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj6ioGR0KXNAhUG6YMKHX6EDLgQ_AUICCgB&biw=1440&bih=801

Clapboard - like https://www.google.ca/search?espv=2&biw=1440&bih=801&tbm=isch&sa=1&q=clapboard+icon&oq=clapboard+icon&gs_l=img.3..0l2j0i5i30.14177.17690.0.17871.18.13.3.2.2.0.160.1082.8j3.11.0....0...1c.1.64.img..3.15.983.m6x4qQwxh0k

Writing Board- like https://www.google.ca/search?espv=2&biw=1440&bih=801&tbm=isch&sa=1&q=writing+board+icon&oq=writing+board+icon&gs_l=img.3...21100.22807.0.22924.13.13.0.0.0.0.189.1356.8j5.13.0....0...1c.1.64.img..3.7.760...0j0i7i30j0i7i10i30.1sNvCJCEXy8

Cheers,
Andri

**Comment by tagliala** [comment]
https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).

clapboard: #3130
running: #1156 
writing board: #3308

All duplicates, closing here
