### ISSUE TITLE
Icon Request: fa-cloud-check

### ISSUE THREAD

**Issue by daneren2005** [FortAwesome/Font-Awesome#9404]
Use case: Showing that everything is synced up (as opposed to cloud download/upload which imply there is an action to take/being taken

![389435](https://cloud.githubusercontent.com/assets/414653/16025824/bf31a31a-317e-11e6-90ca-efce142d38e2.png)
)

**Comment by scrobbleme** [comment]
You don't need an icon for this. You can just use Font Awesomes stacking mechanims:

- http://fontawesome.io/examples/#stacked
- Examples: https://jsfiddle.net/jzffm3ep/1/

**Comment by spencerwmiles** [comment]
Was going to request this icon.. but @scrobbleme has tought me something new. I guess I'm one of today's lucky 10,000. 

[Ten Thousand](https://xkcd.com/1053/)

**Comment by tagliala** [comment]
Hi, 

updated version with the SVG framework and masking feature: https://jsfiddle.net/tagliala/8oqL3b5p/2/

**Comment by aethior** [comment]
Hi @daneren2005,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/cloud-check

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This is available in FA Pro

**In a web application**, it is possible to create the requested icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/36/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
