### ISSUE TITLE
Icon request: icon-xray

### ISSUE THREAD

**Issue by tesnep** [FortAwesome/Font-Awesome#9406]
Can we have an xray icon with radioactive symbol? This can go under the category "medical".

**Comment by tagliala** [comment]
maybe this is a duplicate.

Did you try to [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before using different keywords ?

Could you please provide an example?

**Comment by aethior** [comment]
Duplicate of #681 and planned for v5.0. ;)

cc @tagliala

**Comment by tagliala** [comment]
@aethior thanks. I wasn't able to find the original request
