### ISSUE TITLE
Icon Request: fa-naira

### ISSUE THREAD

**Issue by Sammyskills** [FortAwesome/Font-Awesome#9412]
Hi,

I would love to have an icon for the Nigerian Naira symbol. 
I'm a web developer, and I will love to have an icon to represent local currencies in applications that I build. Currently, I use images, or ₦ or the html equivalent &#8358.

I believe it will help other web developers and designers too.
I've attached the image below
![naira__nigeria](https://cloud.githubusercontent.com/assets/8720569/16114505/84489fd2-33b9-11e6-9add-6c0cf5f919cf.jpg)

**Comment by JohnnyDevv** [comment]
use this: &#8358;

**Comment by JohnnyDevv** [comment]
which is "&#8358;"

**Comment by tagliala** [comment]
@kusaasira this has been closed by the author.

I'm going to reopen ##1291 and locking here

**Comment by tagliala** [comment]
Use #11291

🔒
