### ISSUE TITLE
Icon Request: icon-baruch-hashem

### ISSUE THREAD

**Issue by matthewmack** [FortAwesome/Font-Awesome#9413]
Hi. I realize this is an unusual request, however there are hundreds of site owners who would love to use this as a FontAwesome icon. It's used on all documents and websites that are used by the Chabad community as well as other Jewish institutions. The reason that an icon would be helpful is because in hebrew text is used, lots of people will only see rectangles. The alternative is a .png or .jpg which is schleppy. It would be much appreciated to see this as well as other helpful religious icons available. I've attached a .png. Thanks in advance for your consideration.
![bh](https://cloud.githubusercontent.com/assets/2850324/16141247/6d049e20-340e-11e6-8643-8fcda44546c2.png)

**Comment by McMalloc** [comment]
Would it be possible to include a font which can display hebrew characters so users do not see the placeholder-rectangle? If the user's browser does not support custom fonts they would also not be able to see FontAwesome icons.

**Comment by tagliala** [comment]
what does BH stand for?

**Comment by matthewmack** [comment]
@tagliala Hi. B"H (or BH) is an acronym for the Hebrew words Baruch Hashem , which means, Blessed be God . Traditionally, Jewish people begin letters and emails with this acronym, to contextualize what's most important, and also to remind us that all comes from Baruch Hashem

**Comment by matthewmack** [comment]
@McMalloc That's a good point but I'm only supporting modern browsers. I wasn't embedding a Hebrew font, just using a .png because I didn't want to slow down loads with a font. However, most sites I do in the Jewish Community are already using FontAwesome wherever I can justify throwing them in (I love them) so if it's already being loaded anyway, it would be great to just throw in another <i>

**Comment by yosefromano** [comment]
I second @matthewmack's request. We deal with many Jewish institutions and we also use font awesome. This icon would be very useful to us

**Comment by JohnMarsing** [comment]
I would like a set of icons made up of the 22 Hebrew letters including the 5 _sofits_ (ending) letters, and the 4 letters that don't have a _dagesh_ (dot).

Here's a useful page that has more details...
https://myhebrewbiblecore.azurewebsites.net/Hebrew

maybe base if off of the [David Hebrew font](https://docs.microsoft.com/en-us/typography/font-list/david).

Thanks

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
