### ISSUE TITLE
Icon request: icon-imzy

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#9415]
New social network **Imzy** is growing and will soon be out of beta!

If you have an Imzy account, more information on branding can be found at https://www.imzy.com/imzysaurus.

The below image is quite large, so I'll just add a link:
https://d11wijp10hj976.cloudfront.net/public/imzysaurus-head.svg (Head mascot)

Thank-you :)

**Comment by jalehafshar** [comment]
For reference, here is Imzy's official mascot set up for a single-color icon (.AI and .EPS)
[imzy vector icons.zip](https://github.com/FortAwesome/Font-Awesome/files/473550/imzy.vector.icons.zip)

Mockup:
![fa](https://cloud.githubusercontent.com/assets/1437283/18531819/7de1ff12-7a95-11e6-8e3b-56c41096bf13.jpg)

**Comment by krypt-ix** [comment]
This would be helpful for my site as I have a group setup in imzy for it.

**Comment by chaosbunker** [comment]
i would like to see this as well

**Comment by aethior** [comment]
>On 24 May 2017, Imzy announced that the site was shutting down as they had failed to "find [their] place in the market. ([source](https://en.wikipedia.org/wiki/Imzy))

cc/ @tagliala
