### ISSUE TITLE
Icon request: sort-other-asc & sort-other-desc (sort-shapes-asc & sort-shapes-desc)

### ISSUE THREAD

**Issue by Jacco-V** [FortAwesome/Font-Awesome#9419]
There are two sort up/down icons with matching style<sup>1</sup>:
- [`sort-numeric-asc`](http://fontawesome.io/icon/sort-numeric-asc/) & [`sort-numeric-desc`](http://fontawesome.io/icon/sort-numeric-desc/)
- [`sort-alpha-asc`](http://fontawesome.io/icon/sort-alpha-asc/) & [`sort-alpha-desc`](http://fontawesome.io/icon/sort-alpha-desc/)

And then there is:
- [`sort-amount-asc`](http://fontawesome.io/icon/sort-amount-asc/) & [`sort-amount-desc`](http://fontawesome.io/icon/sort-amount-desc/)

But this last one is visually quite different: the bars are a lot stronger than the numbers/letters in the ones mentioned first.

I would like to request two new icons:
`sort-other-asc` & `sort-other-desc`

![sort-other-asc](https://cloud.githubusercontent.com/assets/19333579/16179150/bca74ba2-365d-11e6-9705-30457f8bfbf4.png)![sort-other-desc](https://cloud.githubusercontent.com/assets/19333579/16179151/bcac19ac-365d-11e6-9a14-13c5034f969b.png)

Or something else that is visually similar to [`sort-numeric`](http://fontawesome.io/icon/sort-numeric-asc/) & [`sort-alpha`](http://fontawesome.io/icon/sort-alpha-asc/), but has abstract 'other' shapes instead (maybe triangles instead of squares, whatever works best).

<br>
<sup>1</sup>I'm aware that there are even more sort icons, but they are not visually related to the ones mentioned here.

**Comment by vjacquet** [comment]
They look nice but I do not understand what order they represents. For alpha, numeric and amount it is obivious but with these two, I am not able to differientiate asc from desc because shapes have no natural ordering.
Also, isn't "other" reprensented by sort-asc and sort-desc?

**Comment by Jacco-V** [comment]
I proposed these exactly because some data does not have any obvious natural sorting order, yet I can sort my table columns on them.
I would like by sort icons to visually have the same style, so, in a table that uses 
    [`sort-numeric`](http://fontawesome.io/icon/sort-numeric-asc/) for number data and [`sort-alpha`](http://fontawesome.io/icon/sort-alpha-asc/) for textual data, I would like to be able to use a third, visually related, icon to sort non-number, non-textual data (for example, a list of avatars).

[`sort-asc`](http://fontawesome.io/icon/sort-asc/) & [`sort-desc`](http://fontawesome.io/icon/sort-desc/) have a completely different visual style.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons?d=gallery&q=sort-shapes&s=solid
