### ISSUE TITLE
-webkit-overflow-scrolling: touch

### ISSUE THREAD

**Issue by matteomenapace** [FortAwesome/Font-Awesome#942]
When using _-webkit-overflow-scrolling: touch_ to enable "momentum scrolling" in WebKit-based mobile browsers, the browser renders only the visible portion of the scrollable element within its container, the rest appears blank. 
This behaviour doesn't appear when Font-Awesome is not in use.  

Examples (try them on a mobile browser, eg on iPhone):
-  without Font-Awesome http://jsbin.com/ecoxec/9/
- with Font-Awesome http://jsbin.com/ecoxec/7/

You'll see how the circles in Line 1 for March or April 2013 won't have a rendered icon, which instead appears on February..

**Comment by sensibleworld** [comment]
Doing some repo clean-up, so closing potentially outdated issues. We can re-open if this is still an issue.
