### ISSUE TITLE
Icon request: fa-instagram-square

### ISSUE THREAD

**Issue by chaseschweitzer** [FortAwesome/Font-Awesome#9420]
An Instagram logo in the same style as the fa-facebook-square, fa-twitter-square and fa-linkedin-square would be super useful for design continuity. (I know stacking is always an option, but transparency isn't supported.) Thanks!

**Comment by tagliala** [comment]
Duplicate of #9223 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
