### ISSUE TITLE
Icon Request: fa-ebay and fa-alibaba

### ISSUE THREAD

**Issue by johnmadox** [FortAwesome/Font-Awesome#9429]
Hi,
I need some icons of the following online selling and buying website: ebay and alibaba. I would appreciate it alot if these icons could get added on fontawesome.
Thank you very much
John

**Comment by aethior** [comment]
Hi @johnmadox,

`fa-ebay`is duplicate of #1783 and `fa-alibaba`duplicate of #3855. Please :+1: these requests.

**Comment by johnmadox** [comment]
But sir, the icons are still not available? were can we find them on the site?

**Comment by aethior** [comment]
Hi @johnmadox,

The icons aren't available. You have to :+1: the requests and maybe in the future will be available.
