### ISSUE TITLE
icon request: Media types

### ISSUE THREAD

**Issue by skookie000** [FortAwesome/Font-Awesome#943]
CDs/discs, cassettes, 8track, reel to reel.
A solid microphone, RCA 44 style.  Not that typical mic icon everywhere.
On Air sign.

...or anything, I'm so geeked-out on this project.

**Comment by ffxsam** [comment]
I second this! Especially a reel, e.g:
![15702-200](https://cloud.githubusercontent.com/assets/12532733/9461091/5b26cab2-4ac0-11e5-88e2-8377db1c9f04.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open. Please open new individual requests or +1 existing ones

eg: disc #702 
tape: #1736

**Comment by olya-gary** [comment]
+1
