### ISSUE TITLE
need new icon:fa-qzone

### ISSUE THREAD

**Issue by Amazing-Z** [FortAwesome/Font-Awesome#9441]
it's a personality space by tencent like facebook.  So it's also used to share something in china. thx.

**Comment by Amazing-Z** [comment]
it's a personality space by tencent like facebook. So it's also used to share something in china. thx.

**Comment by tagliala** [comment]
Duplicate of #3993, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
