### ISSUE TITLE
Icon request:fa-qzone

### ISSUE THREAD

**Issue by Amazing-Z** [FortAwesome/Font-Awesome#9442]
it's a personality space by tencent like facebook.  So it's also used to share something in china. thx.[http://qzone.qq.com/](url)

**Comment by tagliala** [comment]
Duplicate of #3993, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by Amazing-Z** [comment]
@tagliala fine,thx.
