### ISSUE TITLE
Icon Request: fa-wireless

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9443]
Hello,

Use case: mobile development, android, iphone, smartphones , tablets.
That Icon will be very helpful for mobile development and for create wireframes.

![21-512](https://cloud.githubusercontent.com/assets/993318/16264893/26f7339c-3874-11e6-9bb5-6f9a19a193c0.png)

thank you.

**Comment by remq** [comment]
Wouldn't http://fontawesome.io/icon/wifi/ suffice?

**Comment by douglasdeodato** [comment]
@remq  yeah but why not use this the real wifi icon? : https://github.com/FortAwesome/Font-Awesome/issues/9450

**Comment by tagliala** [comment]
I'm going to close here.

Is there any official wifi icon?
