### ISSUE TITLE
Icon Request: fa-truck-moving

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9445]
Hello,

you have already : http://fontawesome.io/icon/truck/

but will be nice have a truck simulation a movement, likes the image. 

Use case: Cargo, delivery, shipment, shipping, tracking.

![sh3-128](https://cloud.githubusercontent.com/assets/993318/16265237/0a00000a-3876-11e6-89f7-790e4ccdd7b5.png)

**Comment by GerritP** [comment]
+1

**Comment by sensibleworld** [comment]
Available in latest release: https://fontawesome.com/icons?d=gallery&q=shipping%20fast
