### ISSUE TITLE
Icon Request: fa-wallet

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9449]
Hello,

Use case: Cash, money, pay, wallet icon

![wallet-2-128](https://cloud.githubusercontent.com/assets/993318/16265507/a4e5cff4-3877-11e6-8a5b-ca82429d089a.png)

**Comment by tagliala** [comment]
Duplicate of #7056 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by douglasdeodato** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/2317

**Comment by ilyago** [comment]
+1
