### ISSUE TITLE
Icon Request: fa-egg-fried

### ISSUE THREAD

**Issue by douglasdeodato** [FortAwesome/Font-Awesome#9452]
Fried egg 

![egg-fried-128](https://cloud.githubusercontent.com/assets/993318/16270235/89ff68d8-388d-11e6-85f0-35d46ac29d93.png)

![fried_egg-128](https://cloud.githubusercontent.com/assets/993318/16270304/b4b94670-388d-11e6-8911-3d84cf5f2cc4.png)

**Comment by PaluMacil** [comment]
I'm not sure if this would be a priority for Font Awesome, but perhaps consider submitting this to Vesper Icons since they are totally compatible with FA yet are restaurant focused: https://github.com/kkvesper/vesper-icons

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/egg-fried?style=solid
