### ISSUE TITLE
Icon request: fa-route

### ISSUE THREAD

**Issue by g-schmitz** [FortAwesome/Font-Awesome#9457]
something like this:
![image](https://cloud.githubusercontent.com/assets/11434036/16280439/bf685dd6-38bf-11e6-9067-82e2575af09f.png)

some icons for different means of transportation would be cool, too. eg  fa-car, fa-walk, fa-bicycle
Thanks!

**Comment by tagliala** [comment]
> some icons for different means of transportation would be cool, too. eg fa-car, fa-walk, fa-bicycle

car and bicycle are already here. walk: #844 

Note that yor example will not fit the 14px icon size

**Comment by Roumed** [comment]
+1

**Comment by carolinelindstrom** [comment]
+1

**Comment by prophe05** [comment]
+1

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/route?style=solid
