### ISSUE TITLE
Icon Request: fa-importexport

### ISSUE THREAD

**Issue by GaryWongCoins** [FortAwesome/Font-Awesome#9461]
it will be good if we have a icon to show import and export in one logo

**Comment by tagliala** [comment]
could you please provide an example?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by danielone** [comment]
I would actually like one for import and one for export

Something like this for export
https://www.iconfinder.com/icons/979791/arrow_direction_exit_go_move_out_right_icon#size=128

import (similar to above but arrow points in)
https://www.iconfinder.com/icons/979790/arrow_go_in_left_icon#size=128

**Comment by tagliala** [comment]
Duplicate of #1020 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by danielone** [comment]
Sorry about that. Will do moving forward
