### ISSUE TITLE
Icon request: Readability

### ISSUE THREAD

**Issue by sublines** [FortAwesome/Font-Awesome#9463]
Hi, I think this would be very useful since many blogs use plugins to offer readability (read later) service.
![Readability Icon](https://cdn1.iconfinder.com/data/icons/simple-icons/4096/readability-4096-black.png)

**Comment by tagliala** [comment]
what does that icon represent? a couch/sofa? an armchair?

**Comment by sublines** [comment]
It's a logo that represents a couch. 
[Readability ](https://www.readability.com/) is a tool that is available for [Chrome](https://chrome.google.com/webstore/detail/readability/oknpjjbmpnndlpmnhmekjpocelpnlfdi), [Firefox](https://addons.mozilla.org/en-US/mobile/addon/readability-47136/), [IE, Safari](https://readability.com/bookmarklets); [Opera](https://addons.opera.com/en/extensions/details/readability-2/), [Android](https://play.google.com/store/apps/details?id=com.readability), [iOS](https://itunes.apple.com/de/app/readability/id460156587?mt=8), [Wordpress](https://wordpress.org/plugins/readability-buttons/), [Drupal ](https://www.drupal.org/project/readability_button) and [many more](https://www.readability.com/apps). 

More info on [Wikipedia](https://en.wikipedia.org/wiki/Readability_(service))

**Comment by sublines** [comment]
It is widely used across the web. Apple's Safari 5 browser the Amazon Kindle and popular iPad applications like Flipboard and Reeder use this service as well.

**Comment by tagliala** [comment]
ok thanks, got it

**Comment by aethior** [comment]
>After more than five years of operation, the Readability article bookmarking/read-it-later service will be shutting down after September 30, 2016. ([more info](https://medium.com/@readability/the-readability-bookmarking-service-will-shut-down-on-september-30-2016-1641cc18e02b#.z1pr8fhdx))

cc/ @tagliala
