### ISSUE TITLE
Icon Request: fa-tiffin fa-mainteinance

### ISSUE THREAD

**Issue by dinumarathe** [FortAwesome/Font-Awesome#9465]
If you add these icons it will very helpful for my handyman projects.

thank you.

**Comment by tagliala** [comment]
Could you please clarify this request?

Please take a look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by zxfrank** [comment]
@dinumarathe do you mean something like that https://thenounproject.com/term/maintenance/5531/ ?

**Comment by dinumarathe** [comment]
Thank you so much sir...

**Comment by tagliala** [comment]
duplicate of #5653 ?

**Comment by dinumarathe** [comment]
Yes it is ?

**Comment by tagliala** [comment]
@dinumarathe please add a :+1: reaction to that request
