### ISSUE TITLE
Icon request: icon-school and other college icons

### ISSUE THREAD

**Issue by themarcba** [FortAwesome/Font-Awesome#947]
I am working on a software for a university, and it would be nice to have some icons like "Grades", "Student", "Teacher", "Graduation", ...

**Comment by valentinacarlone** [comment]
+1

**Comment by andrevanberlo** [comment]
+1

**Comment by tagliala** [comment]
locking here, please read https://github.com/FortAwesome/Font-Awesome/issues/947#issuecomment-61948562

:lock:
