### ISSUE TITLE
Icon request: icon-research-gate

### ISSUE THREAD

**Issue by yangyangoceanographer** [FortAwesome/Font-Awesome#9475]
Hi Dave,

I'm a fan of Font-awesome. This is one of my favorite projects. I wonder if it is possible that you can kindly add the 'research gate' icon in your upcoming updates. The research gate is the world's biggest social networking site for scientists and researchers. Nearly every colleague around me is using research gate. I'm looking forward to see an icon appear in Font-awesome. Many thanks.

**Comment by juliohm** [comment]
Please close this issue, there is already an issue opened for this: https://github.com/FortAwesome/Font-Awesome/issues/3634

**Comment by tagliala** [comment]
@juliohm thanks, I've missed this one
