### ISSUE TITLE
Icon Request: fa-line-chart-plain

### ISSUE THREAD

**Issue by thetrancefan** [FortAwesome/Font-Awesome#9482]
The current line-chart icon contains an upward-pointing arrow at the end. This is what all cartoons of business meetings use. But in the real world, line charts _never_ have an upward pointing arrow at the end, even if profits really _do_ look like that. My request is for the exact same icon, but without the arrow on the chart line.

Keep up the fantastic work. Thank you!

-Bryan Ressler
http://anthrolume.com

**Comment by labkey-jessim** [comment]
+1

**Comment by mntwinsfan** [comment]
+1

**Comment by tina-lai** [comment]
+1
Having this icon would be really useful!

**Comment by PhillUpNorth** [comment]
+1

**Comment by cuzub** [comment]
+1

**Comment by reneseses** [comment]
+1

**Comment by mjaragon** [comment]
+1

**Comment by rsiebeling** [comment]
+1

**Comment by aethior** [comment]
Hi @thetrancefan,

The [fa-chart-line](https://fontawesome.com/icons/chart-line) icon has been updated in v6.0.0-BETA3 without arrow.
There are now two new icons [fa-chart-line-up](https://fontawesome.com/icons/chart-line-up) and [fa-chart-line-down](https://fontawesome.com/icons/chart-line-down) with arrows.

Regards.

cc/ @tagliala
