### ISSUE TITLE
Icon request: icon-undelete

### ISSUE THREAD

**Issue by srirampoondichinappa** [FortAwesome/Font-Awesome#9483]
Hi, 
I found few requests for undelete icon. It would be better if you can add this one to the other similar icons.
Thanks 

![undelete-thumbnail](https://cloud.githubusercontent.com/assets/3191934/16396730/09db6382-3c75-11e6-89b2-2fb08a301bd3.png)

**Comment by aethior** [comment]
Duplicate of #4090. Please comment the original request (#4090) adding your example to avoid duplicate requests.
