### ISSUE TITLE
Icon Request: fa-calendar-week

### ISSUE THREAD

**Issue by imjaypatel** [FortAwesome/Font-Awesome#9484]
Open this [link](http://i.stack.imgur.com/2HN7V.png), view the first icon. That icon represent calendar display in weekly (week wise).

Same as Icon Request following:
fa-calendar-month : represent calendar display in monthly.
fa-calendar-one : represent calendar display only today date.

Thanks

**Comment by aethior** [comment]
Duplicate of #3609. Please comment the original request (#3609) adding your example to avoid duplicate requests.
