### ISSUE TITLE
Icon Request: fa-sofort

### ISSUE THREAD

**Issue by seb-lpx** [FortAwesome/Font-Awesome#9487]
Please create a new icon for the popular payment method sofortüberweisung.
https://www.sofort.com/eng-DE/kaeufer/su/online-zahlen-mit-sofort-ueberweisung/

![sofort-ueberweisung_productnavigation](https://cloud.githubusercontent.com/assets/20184044/16410738/370e1c8c-3d24-11e6-8e56-667f95b2c05d.png)

Thanx!

**Comment by seb-lpx** [comment]
![sofort](https://cloud.githubusercontent.com/assets/20184044/16411762/02716e0c-3d29-11e6-850d-f8e8c7c16a52.png)

**Comment by JakeKydd** [comment]
Any news on this?

**Comment by WEBixx** [comment]
+1

**Comment by krsriq** [comment]
+1

**Comment by Chriz74** [comment]
+1

**Comment by KaiSchniggendiller** [comment]
+1

**Comment by flohaun** [comment]
+1

**Comment by tagliala** [comment]
Ops... this is a duplicate of #4342 and I didn't notice

Please +1 that request, closing here
