### ISSUE TITLE
Icon Request: fa-redmine

### ISSUE THREAD

**Issue by maicoamachado** [FortAwesome/Font-Awesome#9488]
Hello, I have a suggestion to create an icon in Redmine format. :)

http://www.redmine.org/projects/redmine/wiki/Logo

**Comment by tagliala** [comment]
Duplicate of #1787, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
