### ISSUE TITLE
Icon Request: fa-envelope-text and fa-envelope-text-o

### ISSUE THREAD

**Issue by devou33** [FortAwesome/Font-Awesome#9489]
<img width="1137" alt="screen shot 2016-06-28 at 3 04 09 pm" src="https://cloud.githubusercontent.com/assets/7987602/16430563/da11a8f0-3d41-11e6-9dbe-6bc88f0fb825.png">
An open envelope with letter poking out, matching existing fa-envelope and fa-envelope-o

Uses could be wedding or dating related websites. In my case, it would be for b2b communications.

**Comment by aethior** [comment]
Related: #897

**Comment by devou33** [comment]
An empty/open envelope can have different connotations than one with something in it. While it is related to 897 (and someone did suggest this as an option), it is a different request.

**Comment by tagliala** [comment]
I'm not convinced of the name, invitation is quite abstract.

Something like `fa-envelope-text` would be better

**Comment by formspoint** [comment]
Who cares what they're called, can we please get them into source?

**Comment by aadamsx** [comment]
Who cares what they're called, can we please get them into source?

**Comment by tagliala** [comment]
> Who cares what they're called, can we please get them into source?
 
I need a better title for tracking purposes.

Contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

**Comment by devou33** [comment]
If you do a Google Search for [Invitation Icon](https://www.google.com/search?q=invitation+icon), is it really that abstract?

I renamed my request per your suggestion, but would suggest fa-invitation as an alternative.

**Comment by aadamsx** [comment]
@devou33 I don't have the existing closed envelope icon in front of me, do these matched the existing closed envelope icon?  

What I'm looking for is simply: closed envelope if the message is not read, and open if it is read -- but they must match to look right.

**Comment by aadamsx** [comment]
@tagliala, so what about these icons do not meet the contribution guidelines?  When are we going to get a open envelope for gosh-sakes?

**Comment by devou33** [comment]
@aadamsx, this is a rough cut just to get the idea across. My vectors aren't exact or official... however, I think it does a pretty good job of staying true. I assumed that Dave or whoever makes the final files would put their own spin on the concepts.

<img width="300" alt="screen shot 2016-06-29 at 4 47 42 pm" src="https://cloud.githubusercontent.com/assets/7987602/16469987/68be7c54-3e19-11e6-96da-6b751b2d5c40.png">

**Comment by aadamsx** [comment]
@devou33 these look just fine (great) to me!  Will you (if you haven't already) submit all these new icons to the repository using their guidelines (so there's no excuses on their part) and cc Dave while you're at it?

**Comment by aadamsx** [comment]
Then tell me @tagliala, how do we affect change in this repo?  How do we get a much-needed icon that is clearly missing if not a PR?  Should we just keep begging and hope for the best?

**Comment by tagliala** [comment]
@aadamsx please take a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by aadamsx** [comment]
@tagliala from the link you just provided:

> Popularity is one of the factors taken into account, but it is not the only one.

We all know that this icon is popular and requested years back, and even still, has not been added to the main branch.  If you will be so open, in this case, what other "factors" have been taken into account that have kept this icon from us?

If the answer is, some icons we'll never see in this repo because they're behind a pay-wall (restricted to paid version-sets or spinoffs of this free-repo) then that's a valid answer -- just be upfront about it so we can move on.

**Comment by tagliala** [comment]
> We all know that this icon is popular  

which icon?

> that other "factors" have been taken into account that have kept this icon from us?

focusing on accessibility, in example, as 4.6 version which included some requests for that category, even if they were not popular

**Comment by aadamsx** [comment]
> which icon?

This request for: fa-envelope-text and fa-envelope-text-o #9489 is related to: 

The envelope-open & envelope-open-o: #897 (which is where I came from).  #897 was opened on Mar 28, 2013 and has 245 comments (most up-votes).

> focusing on accessibility

I get that, but now might be a good time to add much needed additions (including this icon request).

**Comment by devou33** [comment]
While related to #897, it's in addition to and would be used totally differently in my current application.

**Comment by aadamsx** [comment]
@devou33 indeed, #897 is only closely-related to this icon request.

**Comment by aethior** [comment]
It's a personal project, open and free for all, but a personal project. I understand that Dave wants to design each icon and have the control of the project. We can to propose new icons, but Dave is free to include or not include these icons (factors? personal motivation, the project approach, feedback...). But on the other hand, We are free to fork the project and include our icons.

[There are nearly 100 new icons and enhancements](https://github.com/FortAwesome/Font-Awesome/milestones/5.0.0) planned for the next version (5.0)... This request is new (two days) and the related request (#897) is planned for the next version (5.0).

**Comment by aadamsx** [comment]
> related request (#897) is planned for the next version (5.0)

This is exactly the feedback I was looking for.  

Thank you @aethior

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/envelope-open-text?style=solid
