### ISSUE TITLE
Icon request: icon-megaphone

### ISSUE THREAD

**Issue by RasterVector** [FortAwesome/Font-Awesome#9490]
A megaphone to designate: Announcements. :loudspeaker:

**Comment by aethior** [comment]
Hi @RasterVector,

Check the `fa-bullhorn` (http://fontawesome.io/icon/bullhorn/) icon. ;)

**Comment by tagliala** [comment]
@aethior perhaps @davegandy didn't rebuild docs yet. Sorry but I can't fix that

**Comment by tagliala** [comment]
Ref: #9459 , already implemented and waiting for Dave to rebuild docs, closing here
