### ISSUE TITLE
Icon Request: keybase

### ISSUE THREAD

**Issue by jamespedwards42** [FortAwesome/Font-Awesome#9491]
[Keybase](https://keybase.io/) is a service/app that makes PGP easy and is a good way to publicly verify all of your accounts.  I would like to be able to link to my account along with a standard icon, just as I would something like twitter.

![image](https://cloud.githubusercontent.com/assets/5894272/16442955/bbee6d10-3d8a-11e6-9727-ddbf11b7ae49.png)

**Comment by tagliala** [comment]
Duplicate of #4095, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
