### ISSUE TITLE
Icon Request: fa-sort-circle-o

### ISSUE THREAD

**Issue by travisdmathis** [FortAwesome/Font-Awesome#9494]

**Comment by travisdmathis** [comment]
it would be great to get fa-sort icon available in circle and circle-o

Thanks for everything.

**Comment by ryankane** [comment]
@travisdmathis You can stack them. In order to get the regular circle to work, I had to use some jQuery plugins that I wrote to set the foreground font color to match the nearest; valid background color.

Of course, you can just add `style="color:{{background of container div}}"` to the foreground icon. This way you do not need to use JavaScript. But you will have to update this color value if you decide to change the background color of the container later on.

Here's a link to the [***JSFiddle***][1].

## Image

![screenshot][2]

## HTML

```html
<span class="fa-stack fa-5x">
  <i class="fa fa-circle-o fa-stack-2x"></i>
  <i class="fa fa-sort fa-stack-1x"></i>
</span>

<span class="fa-stack fa-5x">
  <i class="fa fa-circle fa-stack-2x"></i>
  <i class="fa fa-sort fa-stack-1x masked"></i>
</span>
```

## JavaScript

```javascript
(function($) {
  $.fn.getParentBackgroundColor = function() {
    var color = 'rgba(0, 0, 0, 0)';
    var parent = $(this).parent();
    while (parent != null) {
      var color = parent.getIntBackgroundColor();
      if (color > 0) {
        color = parent.css('background-color');
        break;
      }
      parent = parent.parent();
    }
    return color;
  }
  $.fn.getIntBackgroundColor = function() {
    return parseInt(this.getHexBackgroundColor().substr(1), 16);
  }
  $.fn.getHexBackgroundColor = function() {
    var rgb = $(this).css('background-color');
    if (!rgb) return '#FFFFFF';
    var hex_rgb = rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/); 
    function hex(x) {return ("0" + parseInt(x).toString(16)).slice(-2);}
    if (hex_rgb) return "#" + hex(hex_rgb[1]) + hex(hex_rgb[2]) + hex(hex_rgb[3]);
    else return rgb;
  }
}(jQuery));

$(function() {
  $('.masked').each(function() {
    $(this).css('color', $(this).getParentBackgroundColor());
  });
})
```

  [1]: https://jsfiddle.net/fhun0tx7/
  [2]: http://i.imgur.com/eK4XTRS.png

**Comment by tagliala** [comment]
leaving this open, but please consider stacking

**Comment by travisdmathis** [comment]
yea, I'm aware of stacking them, but having the circle-o versions is always nice. stacked circle-o's don't match the size of a font icon that has a circle-o version due to the circle-o needing to be 2x.

**Comment by ryankane** [comment]
@travisdmathis You can always add you own class to the icon or override the `.fa-sort` class to change the `font-size` rule using `{floating-point-value}em` as the value.

**Comment by aethior** [comment]
Hi @travisdmathis,

This icon was added in v5.12.0.
Check https://fontawesome.com/icons/circle-sort

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
This is available in FA Pro

**In a web application**, it is possible to create a similar icon by using power transforms, masking, and layering features of the JS+SVG Framework.

Demo: https://jsfiddle.net/tagliala/bfa6uhse/41/

Ref:

https://fontawesome.com/how-to-use/on-the-web/styling/power-transform
https://fontawesome.com/how-to-use/on-the-web/styling/masking
https://fontawesome.com/how-to-use/on-the-web/styling/layering
