### ISSUE TITLE
Search box does not giving all results

### ISSUE THREAD

**Issue by astralspark** [FortAwesome/Font-Awesome#9498]
Hi,
When i search "bulb" there is no "lightbulb-o" in the results. When I search "idea", there is "lightbulb".

**Comment by astralspark** [comment]
Also searching for case do not gives suitcase.

**Comment by Kruga** [comment]
Looks like you can't search for the ending of a word. Another example is searching for 'chair' does not give 'wheelchair'.
A different, but related issue I've found, is that the search is limited to 20 results, and simply leaves out the rest with no indication that there are more.

**Comment by tagliala** [comment]
There should be something wrong with Algolia

**Comment by Haroenv** [comment]
This is fixed in the new version @tagliala 👍

**Comment by tagliala** [comment]
@Haroenv thanks
