### ISSUE TITLE
Need more food realted icons

### ISSUE THREAD

**Issue by NishanthKabra** [FortAwesome/Font-Awesome#9500]
For a food app, i want to categorize main course, snacks etc. generic fa-cutlery is the only thing we have, if am not wrong.

**Comment by shameen** [comment]
theres quite a few requests for [food based icons](https://github.com/FortAwesome/Font-Awesome/labels/food%20icons) and most have links to https://github.com/kkvesper/vesper-icons

**Comment by tagliala** [comment]
Sorry, can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.

related: #1895
