### ISSUE TITLE
search funtion on website (probably in the navbar)

### ISSUE THREAD

**Issue by forabetterjob** [FortAwesome/Font-Awesome#9505]
Hi, I love font-awesome icons. I google and land on your page to look for exact class name of the icon. Right now, I have to go to "ICONS" tab to search for icons. It will be great if you can put a search function in your navbar itself. 

I believe this will help lot of people.

**Comment by tagliala** [comment]
Hi, documentation changed a lot in these 6 years

There isn't a search bar, but there is a magnification glass that should address this use case

Closing here, but feel free to comment if this is still an issue
