### ISSUE TITLE
 Icon request: 11 Database Icons for database application

### ISSUE THREAD

**Issue by Dirkster99** [FortAwesome/Font-Awesome#9507]
[Database Icons.pdf](https://github.com/FortAwesome/Font-Awesome/files/342983/Database.Icons.pdf)
[IconDetails.zip](https://github.com/FortAwesome/Font-Awesome/files/342984/IconDetails.zip)

I would like to use the awesome font in a web based application that can be used to document a relational database System (eg.: SQL Server database). In such a database there certain types of objects that should visible though consistent and useful Icons. This requests asks to add 11 Icons that are specific to the database category.

I have attached a PDF file that contains the list of requested Icon titles and their description along with a black and White Suggestion. The suggestion was taken from a Microsoft icon library that can freely be used in open source Projects: https://msdn.microsoft.com/en-us/library/ms246582.aspx

These means the suggested icons are also available in a vectorized form which is attached in the zip file.

This request is for a couple related Icons so I am requesting this in 1 isssue. Please let me know if you feel that I should use 11 seperate issues instead -or if there any questions left to answer.

Thank for your great font :-)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.

Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

> So, if you need a new icon in a short while, or you need a comprehensive set of icons (e.g., a set of weather icons to build a forecast application) our suggestion is to customize Font Awesome.
