### ISSUE TITLE
Icon Request: fa-money-empty

### ISSUE THREAD

**Issue by rmkane** [FortAwesome/Font-Awesome#9509]
I used this [image](http://st.depositphotos.com/1331616/2558/v/950/depositphotos_25588717-Dollar-bill-icon-set.jpg) as a reference for the curve of the bank note. You can use this to stack with [all available currency symbols](https://en.wikipedia.org/wiki/Currency_symbol#List_of_presently-circulating_currency_symbols).
# fa-bank-note

![fa-bank-note](http://i.imgur.com/GjlSs4r.png)
## SVG Source

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   version="1.1"
   id="svg2"
   viewBox="0 0 500 499.99995"
   height="500"
   width="500">
  <defs id="defs4" />
  <metadata id="metadata7">
    <rdf:RDF>
      <cc:Work rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     transform="translate(26.646032,268.40496)"
     style="opacity:1"
     id="layer1">
    <path
       id="rect4147"
       d="m 41.2829,-108.93764 c 118.04605,68.213519 241.74419,-67.67544 366.67448,-0.35459 l 35.2426,176.181166 C 281.895,-13.497501 168.44249,149.162 3.3880438,68.816066 Z"
       style="opacity:1;fill:none;fill-opacity:1;fill-rule:nonzero;stroke:#000000;stroke-width:15;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
  </g>
</svg>
```

**Comment by tagliala** [comment]
Don't know how to deal with this. There is already a banknote ([fa-money](http://fontawesome.io/icon/money/)) and a request to improve that icon #4418 .

The above example doesn't match current design, we could go for an empty money icon

**Comment by ryankane** [comment]
This will offer the ability to overlay text or a currency symbol on top of it. I thought a generic; template-like image would serve better than a full-fledged; specific denomination/value.

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because we think it might be too niche, or just not a good fit for Font Awesome.

But if you feel really strongly about it, feel free to make your case by submitting a new issue.
