### ISSUE TITLE
Icon Request: fa-gaming

### ISSUE THREAD

**Issue by FXTe1Y** [FortAwesome/Font-Awesome#9512]
Hi, my request is about make a few icons about gaming 
For example 
fa-samp
fa-cs16
fa-csgo
fa-cssource
fa-mtasa
fa-minecraft
fa-muonline
fa-rust
it would be great if these icons would show for gaming projekts :)

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car)
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

minecraft: #1776
