### ISSUE TITLE
Icon Request: fa-instagram

### ISSUE THREAD

**Issue by elisa15** [FortAwesome/Font-Awesome#9514]
hi fontawesome!

Im really fan of you! you're really cool!!

but I need the new instagram font for my website meetpatty.com.au

please!

Thank you in advance!

**Comment by tagliala** [comment]
@elisa15 your website is using Font Awesome 4.1.0 (in style.css). Update that to 4.6.3 and you will see [the new instagram icon](http://fontawesome.io/icon/instagram/)

Hope it helps, closing here
