### ISSUE TITLE
Icon Request: lock-o

### ISSUE THREAD

**Issue by PatrickKoehlerEClinical** [FortAwesome/Font-Awesome#9515]
In our projects  we use the icon ("fa-lock") to indicate a folder that _is locked_.

We'd like to use an outlined version ("fa-lock-o") to indicate a folder that _contains locked entities_ but is not itself locked.

**Comment by tagliala** [comment]
Font Awesome 5 Pro provides an outlined lock icon: https://fontawesome.com/icons/lock?style=solid

Anyway, regular and solid icons are not mean to be exchangeable in every case.

You can switch from circle solid to circle regular, square solid to square regular, star solid to star regular, etc... But the design of locks is different

I would suggesto to use 
- https://fontawesome.com/icons/unlock?style=solid
- https://fontawesome.com/icons/unlock-alt?style=solid

both available in FA 5 Free to represent the unlocked state

Closing here
