### ISSUE TITLE
font for compare products

### ISSUE THREAD

**Issue by nilusngh** [FortAwesome/Font-Awesome#9517]
no icons for compare product...

**Comment by tagliala** [comment]
Could you please conform to contributing guidelines?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
