### ISSUE TITLE
Icon request: Remove filter

### ISSUE THREAD

**Issue by OsniNeto** [FortAwesome/Font-Awesome#9529]
A sugestion for a new icon...

A mix of fa-filter and fa-times

![filter](https://cloud.githubusercontent.com/assets/17650353/16635021/bd81a256-43a6-11e6-819e-2eb8ba67d715.png)

**Comment by tagliala** [comment]
Duplicate of #650 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
