### ISSUE TITLE
Icon request: icon-number1

### ISSUE THREAD

**Issue by fabiomn** [FortAwesome/Font-Awesome#9532]
It would be extremely helpful and certainly everyone would agree in icons that could have numbers and letters. As for example 1, 2, 3 or A, B, C.

I do not know if it was possible, this new icon to use Google Fonts.

![icons](https://cloud.githubusercontent.com/assets/20340390/16657017/3a0ebd32-4437-11e6-91d7-42fe2b354c58.JPG)

**Comment by tagliala** [comment]
Please use plain css or icon stacking, this is out of scope at the moment

http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Ref: #6099

http://codepen.io/jesseflorig/pen/WbWwVK
