### ISSUE TITLE
Icon request: camping/hotel (set)

### ISSUE THREAD

**Issue by Makreig** [FortAwesome/Font-Awesome#9534]
As can be seen in the image below, i am currently working on a site that will be listing a number of campsite, bunkhouses and B&B's in the local area. I am using icons to show what facilities each location has, however i can't find a suitable icon for every facility i need to portray. 

![hotel-camping-icons](https://cloud.githubusercontent.com/assets/6011781/16659636/e814a77c-4462-11e6-8291-b65402d8c04d.png)
(note: i've used images as replacements for icons that are not available)

This clearly shows a number of new icons that would be useful, both for sites like the one i'm working on and any map-like program. 
Examples of new icons from this map would include:
- Camping: a tent or campfire
- Drying: a shape emitting lines much like that seen on car heating or hand dryers
- Shower: similar to the image i have used in the picture above
- Bunkhouse: a set of bunkbeds
- Toilets: either both a male and a female or the side profile of a toilet
- Water: a side on view of a tap
It would also be useful to have an icon depicting an ensuite, though i have no ideas on how this could be portrayed

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺

Camping: #3859 
shower: #708
