### ISSUE TITLE
Icon Request: fa-data-processing-*

### ISSUE THREAD

**Issue by taarimalta** [FortAwesome/Font-Awesome#9539]
Please add Data Processing Related Icons

Such as Source, Sink, Tap, Tail, Flow, Filter, Scrub, Extract, Transform, Load, Dump, DirtyData, Aggregate, Split, Scrape, Crawl etc

Thank you so much. Love your icons

**Comment by tagliala** [comment]
Sorry, can't leave this open.

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.


Please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome or open new, individual request with proper title and example
