### ISSUE TITLE
Icon Request: fa-taingle

### ISSUE THREAD

**Issue by vitasfan** [FortAwesome/Font-Awesome#9545]
![taingle](https://cloud.githubusercontent.com/assets/20376941/16711339/00f3727e-4624-11e6-92dc-417a2988bfb4.jpg)

New social app coming soon. See: https://www.facebook.com/TaingleApp/

**Comment by aethior** [comment]
The domain ([link](http://www.taingle.com/)) is currently down and the social networks are inactive since 2018 ([twitter](https://twitter.com/app_taingle) and [facebook](https://www.facebook.com/TaingleApp/)).

cc/ @tagliala
