### ISSUE TITLE
Icon Request: fa-traffic-light-

### ISSUE THREAD

**Issue by uruloke** [FortAwesome/Font-Awesome#9547]
A simple list of traffic lights icons.
So having an
- fa-traffic-light-go-man
- fa-traffic-light-stop-man

By naming like this it would give the power for also having in the feature
- fa-traffic-light-go-woman
- fa-traffic-light-stop-woman
- fa-traffic-light-stop-hand
- -girl
- -boy
- -couple-man-woman (maybe a little too long.)
- -Ampelmann ([Wikipedia](https://en.wikipedia.org/wiki/Ampelm%C3%A4nnchen))

**Comment by tagliala** [comment]
Sorry, I will not leave this open

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Attach a single color image or two that represent the idea you're going for.
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
