### ISSUE TITLE
Icon Request: fa:trolley, fa: subway and fa: tramway/ fa: street-car

### ISSUE THREAD

**Issue by rootingrobin** [FortAwesome/Font-Awesome#9548]
Hello,
I love how versatile Font Awesome icons are! I would like to request icons of a trolley, subway sign and street-car to add to the contact page of my website.
Thanks so much for your work!
Best Regards,
Ina

![icon trolley](https://cloud.githubusercontent.com/assets/20397590/16729013/8d39fba0-4772-11e6-9f84-87d11a25fedb.JPG)
![metro icon](https://cloud.githubusercontent.com/assets/20397590/16729014/8d3ac36e-4772-11e6-962c-0a4451207f26.JPG)
![street car icon](https://cloud.githubusercontent.com/assets/20397590/16729037/a68663f0-4772-11e6-9b09-2072fcbe1cdb.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open

Please take another look at our contributing guidelines:

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a 👍 reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).

Subway: http://fontawesome.io/icon/subway/
Subway symbols: #4038

**Comment by rootingrobin** [comment]
Hello,

Sorry for spamming you with the request.

I read the rules beforehand and thought it was fine. Could you please be 
more specific what the issue is so I can try to reopen it without the 
errors?

Thanks!

Best Regards,

Ina

**Comment by tagliala** [comment]
If you want to request three icons, open three individual requests, having care of searching before for existing requests.

A request  for tram should already exist at: #9181
