### ISSUE TITLE
Clickable sort icons

### ISSUE THREAD

**Issue by hormigaz** [FortAwesome/Font-Awesome#9549]
Hello,

I'm trying to stack sort asc and desc icons and make them clickable. But it seems that only the second one is clickable. Can anyone help me, please?

```
<span class="fa-stack fa-lg">
    <a href="#sort-asc"><i class="fa fa-sort-asc fa-stack-1x"></i></a>
    <a href="#sort-desc"><i class="fa fa-sort-desc fa-stack-1x"></i></a>
</span>
```

Thanks!

**Comment by tagliala** [comment]
Hi,

unfortunately this could not be implemented, please consider another solution (pure css is fine)

icons have the same height, so they overlap

https://jsfiddle.net/tagliala/4Lcpvhoo/5/

**Comment by hormigaz** [comment]
Ok, thanks anyway!
