### ISSUE TITLE
Icon Request: fa-chemical

### ISSUE THREAD

**Issue by niyazpoyilan** [FortAwesome/Font-Awesome#9553]
A chemical in a lab tube

**Comment by tagliala** [comment]
Duplicate of #1353 ?

**Comment by JoeKonst** [comment]
![chemical-blue](https://cloud.githubusercontent.com/assets/12752154/16811287/75a8d944-491f-11e6-99ff-8d8494ffe285.png)

What about something like this?

**Comment by tagliala** [comment]
We already have a flask: http://fontawesome.io/icon/flask/

**Comment by JoeKonst** [comment]
Ah yeah, my bad!

Maybe this then:

![testtube](https://cloud.githubusercontent.com/assets/12752154/16815020/3579a2b6-4930-11e6-9041-a619e7f199db.png)

**Comment by tagliala** [comment]
So can I consider this a duplicate of #1353?

**Comment by kanalumaddela** [comment]
yeah^

**Comment by tagliala** [comment]
Duplicate of #1353, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
