### ISSUE TITLE
Icon request: fa-line

### ISSUE THREAD

**Issue by mcpe-yossi1114** [FortAwesome/Font-Awesome#9557]

**Comment by mcpe-yossi1114** [comment]
LINE PNG logo image is here:
http://line.me/en/logo

**Comment by tagliala** [comment]
Duplicate of #2631 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
