### ISSUE TITLE
Icon Request: fa-headstone (gravestone)

### ISSUE THREAD

**Issue by blenki101** [FortAwesome/Font-Awesome#9558]
Hi - I need an icon for a cemetery - please see attached file for idea
![head_stone](https://cloud.githubusercontent.com/assets/14123751/16806334/008ff3d0-490c-11e6-93f4-8797d3455b4d.jpg)

**Comment by JoeKonst** [comment]
![gravestone](https://cloud.githubusercontent.com/assets/12752154/16815958/fea39d1a-4933-11e6-8f1e-a28f2636b4c5.png)

**Comment by casman300** [comment]
+1

**Comment by azerusDE** [comment]
Yes, that'd be great.

**Comment by melizaa** [comment]
webtrees needs also this icon.

Are plans to add it? When?

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/tombstone-blank?s=solid
https://fontawesome.com/icons/tombstone?s=solid
