### ISSUE TITLE
Icon Request: fa-fa nurture

### ISSUE THREAD

**Issue by blenki101** [FortAwesome/Font-Awesome#9559]
Hi - I need a new icon for nurture please - for allotments - please see attached image
![nurture](https://cloud.githubusercontent.com/assets/14123751/16806388/37a8d90e-490c-11e6-9d74-e328211e1bc9.jpg)

**Comment by tagliala** [comment]
this is probably a duplicate or there is a very similar request. I need to search for synonyms

**Comment by aethior** [comment]
Something like https://fontawesome.com/icons/hand-holding-seedling?

Regards.

**Comment by tagliala** [comment]
Considering this fulfilled by hand-holding-seedling, it should convey the message.

If it is not the case, I would ask for a clarification of why current design does not fit this use case (I understand that the soil is missing from the implemented icon, but we should also consider icon complexity and rendering at small sizes)
