### ISSUE TITLE
Redesign odd-height icons to improve vertical centering

### ISSUE THREAD

**Issue by ile** [FortAwesome/Font-Awesome#9563]
There seems to be an alignment problem with these icons
![1](https://cloud.githubusercontent.com/assets/433707/16816835/931299e2-4948-11e6-8dc5-8e575062d6e4.jpg)

Or actually the problem is that they are of different size? This fills the entire area:

![2](https://cloud.githubusercontent.com/assets/433707/16816875/bf5c4764-4948-11e6-987f-bdb2d6f7c586.jpg)

... but this is smaller than the heart:

![3](https://cloud.githubusercontent.com/assets/433707/16816946/14cb5424-4949-11e6-9d41-a59aa18359c4.jpg)

This seems to be aligned to the bottom?

![4](https://cloud.githubusercontent.com/assets/433707/16816967/28c495a8-4949-11e6-816a-5313ccf90e87.jpg)

I will make a better test case in a moment.

**Comment by tagliala** [comment]
There are two different bugs, covered in #1624 and #8628 

About `retweet` icon: it has an odd height, so it cannot be vertically centered.

It should be redesigned, but this is an issue which affects of a lot of icons in the set

Also, some icons could not be redesigned to have an even height, e.g: `minus-square-o`

I would leave this open, but we need to find all even-heighted icons

**Comment by tagliala** [comment]
List of odd height icons:
* align-center
* align-justify
* align-left
* align-right
* angle-double-left
* angle-double-right
* angle-down						
* angle-left						
* angle-right						
* angle-up
* beer
* braille
* camera
* caret-up
* caret-down
* cart-arrow-down
* cart-plus
* chain
* chain-broken
**to be continued**
---

**Comment by davegandy** [comment]
This is absolutely an issue, but is a massive amount of work to address. This will be one of the main drivers of Font Awesome 5.0, which will get a complete visual and code rewrite. Stay tuned.

**Comment by tagliala** [comment]
The issue reported in the first post seems fixed to me https://jsfiddle.net/tagliala/tgzouajm/21/
