### ISSUE TITLE
Icon Request: Cat, Dog, (or generic animal - paw) Icons

### ISSUE THREAD

**Issue by ghost** [FortAwesome/Font-Awesome#957]
This is obviously a "want to have" not a "need to have".  It would be an icon for "animals/pets" category.

**Comment by somethingworks** [comment]
+1

**Comment by ryanknutson** [comment]
@somethingworks Already closed!

**Comment by G-Driver** [comment]
+1

**Comment by yarcowang** [comment]
What about Chinese 12 symbolic animals? 
```
Rat charm,子鼠 
Ox patient,丑牛 
Tiger sensitive,寅虎 
Rabbit articulate,卯兔 
Dragon healthy,辰龙 
Snake deep,巳蛇 
Horse popular,午马 
Goat elegant,未羊 
Monkey clever,申猴 
Rooster deep thinkers,酉鸡 
Dog loyalty,戌狗 
Pig chivalrous.亥猪
```
That would be funny. +12

**Comment by tagliala** [comment]
@yarcowang please open a new request, thanks

**Comment by yarcowang** [comment]
Em, what? The doc said they prefer `+1` on existing issue...

**Comment by tagliala** [comment]
@yarcowang this request (I prefer request instead of issue) is closed --> http://fontawesome.io/icon/paw/

**Comment by juhaelee** [comment]
+1

**Comment by tagliala** [comment]
@juhaelee this icon is already here: http://fontawesome.io/icon/paw/

**Comment by Gynidark** [comment]
+1

**Comment by tagliala** [comment]
Locking:  http://fontawesome.io/icon/paw/
