### ISSUE TITLE
Icon request: icon-jabber + icon-xmpp

### ISSUE THREAD

**Issue by giobeatle1794** [FortAwesome/Font-Awesome#9578]
This icon it's used to, for example, show the content it's related to a Jabber/XMPP acount. The icon is necessary same as the Facebook icon, and I need one for put in my webpage, and there not exist on Font Awesome.

**Comment by tagliala** [comment]
Duplicate of #549 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
