### ISSUE TITLE
Use double-colon CSS3 syntax for pseudo elements

### ISSUE THREAD

**Issue by c-smile** [FortAwesome/Font-Awesome#9582]
standard font-awesome.css has following declarations:

`.fa-camera-retro:before {  content: "\f083"; }`

which technically incorrect as `before`  is [pseudo-element but not pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements). Therefore those declarations all should look like as

`.fa-camera-retro::before {  content: "\f083"; }`

While `:before` form is supported as an exception in most browsers I think for standard conformity that CSS should be changed.

**Comment by andrewhosgood** [comment]
Just as a warning, this will drop support for IE8 https://developer.mozilla.org/en/docs/Web/CSS/Pseudo-elements#Notes

**Comment by tagliala** [comment]
@andrewhosgood thanks for pointing this out

version 5.0.0 will drop support for IE8, so it will not be a problem

**Comment by mrmohtas** [comment]
The decision to drop support for IE8 in v5.0.0 has been changed so this issue should be removed from the 5.0.0 milestone

**Comment by tagliala** [comment]
Released in FA6
