### ISSUE TITLE
[Feature-Request] Icons for linux distributions

### ISSUE THREAD

**Issue by shibumi** [FortAwesome/Font-Awesome#9584]
Hey,
I would do it my self, but I am not very talented in graphic design. It would be nice if Awesome font would have icons for the bigger linux distributions:

* Arch Linux
* Debian
* Ubuntu
* Gentoo
* Opensuse
* Slackware
* Fedora
* CentOS

**Comment by aethior** [comment]
Duplicate of #980 (ubuntu, centos, redhat, fedora, suse) and #1125 (debian).

**Comment by tagliala** [comment]
Closing here, please open individual requests for other missing distros
