### ISSUE TITLE
Icon request: icon-smiley-fill-yellow

### ISSUE THREAD

**Issue by hugomiura** [FortAwesome/Font-Awesome#9587]
Dear Font-Awesome staff, It would be nice to have the original Smiley icon with yellow fill, instead of transparent.

![smiley-163510_960_720](https://cloud.githubusercontent.com/assets/2332179/16918905/eced7048-4cdd-11e6-8a3e-9b8658d47968.jpg)

**Comment by tagliala** [comment]
Hi, this is not possible because webfonts are limited to a single color.

Please use stacking or custom css.

Ref: #5284
