### ISSUE TITLE
Icon request: icon-neos

### ISSUE THREAD

**Issue by jonnitto** [FortAwesome/Font-Awesome#9589]
[Neos](https://neos.io) use Font Awesome in the backend. It would be great to have it in the collection!

Logos can be found here:
https://github.com/neos/brand

[Archiv.zip](https://github.com/FortAwesome/Font-Awesome/files/369383/Archiv.zip)

![Outline Logo](https://raw.githubusercontent.com/neos/brand/master/logos/Avatars/neos_avatar_monochrome.png)

**Comment by RafaelKa** [comment]
@jonnitto maybe we should do that per PR?

**Comment by jonnitto** [comment]
@RafaelKa Nope. They want it that way: http://fontawesome.io/community/#requesting-new-icons

**Comment by tagliala** [comment]
@RafaelKa you can clone the repo, add the icon and share here your work

**Comment by robertlemke** [comment]
Here's an example of the wireframe logo which can be used for the Font Awesome icon:

![neos_n_outline_dark_250](https://cloud.githubusercontent.com/assets/95582/19769448/af4f784e-9c5b-11e6-9444-b19d2246cca2.png)

**Comment by joekolade** [comment]
+1

**Comment by marvinhuebner** [comment]
+1

**Comment by rolandschuetz** [comment]
+1

**Comment by dnepro** [comment]
+1

**Comment by jonnitto** [comment]
Please don't write +1. Use the `add reaction` button

**Comment by beheist** [comment]
Would be very useful to have a Neos icon finally :)

**Comment by iseries** [comment]
This is (Font) awesome! :)

**Comment by wr-lang** [comment]
waiting eagerly for the icon - what stops it?

**Comment by beheist** [comment]
Dunno, we've been waiting quite some time now..

**Comment by jonnitto** [comment]
We finally managed it to include Font Awesome 5 into our React-driven backend UI. Can't wait to have it in the FontAwesome Collection

**Comment by cognifloyd** [comment]
Yes. FontAwesome+Neos=EvenMoreAwesome!

**Comment by aertmann** [comment]
me like +1

**Comment by cognifloyd** [comment]
Direct links to relevant icons:
https://github.com/neos/brand/blob/master/logos/Avatars/neos_avatar_monochrome.eps
https://github.com/neos/brand/blob/master/logos/Avatars/neos_avatar_monochrome.png
https://github.com/neos/brand/blob/master/logos/Avatars/neos_avatar_monochrome.svg
https://github.com/neos/brand/blob/master/logos/Avatars/neos_avatar_monochrome@2x.png.png

**Comment by KPeschke** [comment]
+1

**Comment by tantegerda1** [comment]
would be very cool to have that icon!

+1

**Comment by dimaip** [comment]
Oh yes please, Neos is one of the major CMS on the market, sad not to see it on the list...

**Comment by dimitriadisg** [comment]
+1

**Comment by wr-lang** [comment]
@cognifloyd 
> Any other use cases I didn't think of?
We as a web developer agency would like to include the icon on our portfolio page and also identify the projects with it.

**Comment by KPeschke** [comment]
We have internal applications where we use brand icons to identify the product or technology. With the Neos CMS icon, another icon would have been included in FontAwesome which we could use for that case.

**Comment by dfeyer** [comment]
We (the neos community) push FontAwesome since the beggining in our UI, we recently push the support for version 5, having our logo in the font will be so good !

**Comment by skurfuerst** [comment]
Would be awesome to have our logo included here - as we're a heavy user of Neos!

**Comment by christophengelmayer** [comment]
+1

**Comment by alexandergirod** [comment]
We definitely need the *NEOS* logo. Make it happen!

**Comment by mficzel** [comment]
I cant wait to have the neos icon in font-awesome. I need it every day.

**Comment by beheist** [comment]
woohoo! its coming finally :)
