### ISSUE TITLE
icon fa-whatsapp

### ISSUE THREAD

**Issue by ViviLo** [FortAwesome/Font-Awesome#9593]
HI I added fa fa-whatsapp class into fuse social wordpress plugin, but it seems that doesn't works. Alternatively, instead of that I had to use fa fa-phone.

Could you help me please? I need whatsapp icon on my web.

This is my site: http://pruebas.legalpartner.co/

Thanks a lot!

**Comment by aethior** [comment]
Hi @ViviLo,

Your theme is using Font Awesome v4.0.3 and your sidebar plugin is using v4.1.0. You have to update the version to v4.3 (minimum).

**Comment by tagliala** [comment]
@aethior thanks
