### ISSUE TITLE
Icon Request: travel industry icons

### ISSUE THREAD

**Issue by mahsakr** [FortAwesome/Font-Awesome#9596]
Hi Support,

you will be helpful and thankful if you provided new icons for travel industry. here are examples:
http://www.soaptheme.net/html/travelo/shortcode-icon-boxes.html

they are required by many applications

**Comment by tagliala** [comment]
Sorry, can't leave this open

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> * Please do not request comprehensive sets of icons related to a very specific field.
* Please search to see if your icon request already exists. If a request is found, please add a :+1: reaction to that one.
* Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
* Title your new issue Icon request: icon-name (e.g., Icon request: icon-car).
* Request concrete objects: it's harder to make an icon to represent happiness, it's easier to make a smiley face. ☺
