### ISSUE TITLE
Icon Request: fa-meat

### ISSUE THREAD

**Issue by direcactx1** [FortAwesome/Font-Awesome#9598]
Good evening!
I need a icon to supermarket app!
![plainicon com-39727-256px](https://cloud.githubusercontent.com/assets/20547929/16971663/11e4c526-4dfc-11e6-9665-6158de0a2d3d.png)

Thanks for attention!
Best regards,
Rafael Medeiros

**Comment by aethior** [comment]
Duplicate of #6510. Please :+1: that.
