### ISSUE TITLE
Icon Request: fa-lamp

### ISSUE THREAD

**Issue by gauravkumar2217** [FortAwesome/Font-Awesome#9599]
i am developing a website related to Aroma Lamp. so i need the icon of lamp.

**Comment by tagliala** [comment]
could you please provide a single color example suitable for 14px icon size?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by gauravkumar2217** [comment]
sorry i also do not have pic in this size. i have only my client pics which
are in 500px approx.

**Comment by gauravkumar2217** [comment]
its a sample of lamp

**Comment by tagliala** [comment]
@gauravkumar2217 please do not attach pics, they don't work post them on github

**Comment by tagliala** [comment]
No feedback, closing here
