### ISSUE TITLE
custom build

### ISSUE THREAD

**Issue by weepy** [FortAwesome/Font-Awesome#96]
Is it possible to build a custom font-awesome containing just the icons you want ?

**Comment by bee-keeper** [comment]
Can confirm IcoMoon app works flawlessly for this.  Thanks for the tip!

**Comment by tagliala** [comment]
@bee-keeper take also a look here: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome#the-easy-way

feel free to add any other good service to improve the wiki

**Comment by panzerdp** [comment]
https://icomoon.io is great for creating custom builds! Thanks for mentioning.
