### ISSUE TITLE
Icon request: icon-generate

### ISSUE THREAD

**Issue by RaimisErvit** [FortAwesome/Font-Awesome#9600]
Hi, if i can i want ask new icon, Icon request: icon-generate, need generate invoice i think it can be a animated.
like this https://image-gr.s3.envato.com/files/53046446/invoice-icons-set-prev.jpg

**Comment by tagliala** [comment]
Duplicate of #477 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
