### ISSUE TITLE
Icon request: fa-pencil-ruler (prototype, design)

### ISSUE THREAD

**Issue by rashikaranpuria** [FortAwesome/Font-Awesome#9604]
I am creating a website, and I am not very good at front end design but i want to do all the work myself. I would be very grateful if you could design this one. I am sure it will be very useful for other people in the community as well.
![prototype](https://cloud.githubusercontent.com/assets/10719334/16992449/00381302-4ebd-11e6-948e-359c3c5656af.png)
Something like the pencil scale or any other better ideas you have.

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/pencil-ruler?style=solid
