### ISSUE TITLE
Icon request: fa-periscope fa-radio and fa-pikabu

### ISSUE THREAD

**Issue by mha0-gh** [FortAwesome/Font-Awesome#9610]
fa-periscope for use as a clickable button on a page in the "Periscope", fa-periscope for use as a clickable button on a page with my audiostream, and fa-pikabu for use as a clickable button on page in the "Pikabu" respectively. Who can redraw this icons? :)
![fa-pikabu](https://cloud.githubusercontent.com/assets/20575918/17018006/6bd07308-4f3e-11e6-83f6-63e2671a3c9a.jpg)
![fa-periscope](https://cloud.githubusercontent.com/assets/20575918/17018007/6bd108ae-4f3e-11e6-9d3e-402cf22a3092.jpg)
![fa-radio](https://cloud.githubusercontent.com/assets/20575918/17018005/6bcfa1ee-4f3e-11e6-8866-c11c524a74c2.jpg)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons
