### ISSUE TITLE
Icon request: Moodle

### ISSUE THREAD

**Issue by aine100** [FortAwesome/Font-Awesome#9613]
Hi, 
just looking for an icon for Moodle, the lms that is used by students worldwide. 
![download](https://cloud.githubusercontent.com/assets/2893150/17028878/ed95d38e-4f60-11e6-9f86-47e80cb2d7b5.jpg)

Thanks,
Aine

**Comment by tagliala** [comment]
Duplicate of #2167, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
