### ISSUE TITLE
Icon Request: fa-New

### ISSUE THREAD

**Issue by mgee16** [FortAwesome/Font-Awesome#9615]
An icon to draw attention to a newly posted item would be great.
Several varieties would be great also such as a Star with "New" inside etc.
I LOVE your icons.
Great Work!

**Comment by aethior** [comment]
Hi @mgee16,

Remember that Font Awesome is an international project. The icons with words in any language break this condition.

**Comment by Roumed** [comment]
+1

**Comment by tagliala** [comment]
very same duplicate of #1331.

You can +1 that request, but @aethior is right, new is not an icon and it is not international

**Comment by mgee16** [comment]
How about a placeholder for text inside the icon? Michael Gee18658 N. Rincon Ct.Surprise, Az. 85387

**Comment by aethior** [comment]
Check: http://codepen.io/aethior/pen/XKqAdE

Related: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

**Comment by mgee16** [comment]
Aethior:
This is exactly what I needed.Not sure how to resize the icon to be a little smaller though.Thanks a million!
 Michael Gee

**Comment by aethior** [comment]
I just updated the file for do a little smaller (http://codepen.io/aethior/pen/XKqAdE). You can play with `fa-stack-2x` (3x, 2x, 1x...) and `font-size` attributes for ajust the size.

**Comment by mgee16** [comment]
Wow, that is perfect!Thanks for your help with this. :) Michael Gee
