### ISSUE TITLE
Improper URL formation on #iefix font file call

### ISSUE THREAD

**Issue by Netrilix** [FortAwesome/Font-Awesome#9618]
On [this line](https://github.com/FortAwesome/Font-Awesome/blob/c6e79ae1a1e7bef4e7290e5026b704d24f4fa590/css/font-awesome.css#L10):

`url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular)` is properly formatted according to [RFC 3986.4.2](https://tools.ietf.org/html/rfc3986#section-4.2), with the fragment coming after the query string.

`url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3')` is improperly formatted, with the query string coming *inside* the fragment, where a lot of servers won't properly parse it.

**Comment by tagliala** [comment]
Hi, we are aware of that

please take a look here: https://github.com/FortAwesome/Font-Awesome/issues/6556#issuecomment-105463856
