### ISSUE TITLE
Icons request: icon-shopping-basket

### ISSUE THREAD

**Issue by Spheerys** [FortAwesome/Font-Awesome#962]
Everything is on the title :)

**Comment by nacoleman** [comment]
+1

**Comment by Olegipst** [comment]
+1

**Comment by henleywc** [comment]
+1

**Comment by willwright82** [comment]
+1

**Comment by SalmanPK** [comment]
+1 please!

For inspiration: http://thenounproject.com/search/?q=basket

**Comment by linab** [comment]
+1

**Comment by MikeSys** [comment]
+1

**Comment by skorbut** [comment]
+1

**Comment by jungbunzlav** [comment]
+1

**Comment by jonathan-jaekel** [comment]
+1

**Comment by jannik-hh** [comment]
+1

**Comment by sfroehler** [comment]
+1

**Comment by nikkiroylance** [comment]
+1

**Comment by leoncottell** [comment]
+1

**Comment by gasparfm** [comment]
+1

**Comment by wrick17** [comment]
+1

**Comment by andymb** [comment]
Is this icon really less useful than the fighter jet or cutlery? Does the project take donations?  How much to get this done?

**Comment by samuelg0rd0n** [comment]
+1

**Comment by robertglez** [comment]
From Spain, also a big +1. Small e-commerce sites prefer a basket instead of a cart/trolley as it provides a feeling of (non-corporate) nearness

**Comment by gertruda88** [comment]
+1

**Comment by iammag** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by AllyReid** [comment]
+1

**Comment by r-nicol** [comment]
Will this ever get done!? Can't believe it does not exist

**Comment by tomrichmond** [comment]
+1

**Comment by jamesefl** [comment]
+1 
Shopping Basket
Somethiing like this would be great, maybe lose the knobs on the handles:
![shopping-basket-icon](https://cloud.githubusercontent.com/assets/5039726/7061996/9d08d3a4-de90-11e4-96ea-070a4712bfbf.png)

**Comment by olliewills** [comment]
+1. A basket icon would receive much love from those of us in the UK.

**Comment by rontav** [comment]
+1

**Comment by villeman** [comment]
+1

**Comment by Kyle-J** [comment]
+1

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by JeffCalmRay** [comment]
+1

**Comment by Excolo** [comment]
+1

**Comment by larsbo** [comment]
+1

**Comment by benjamincanac** [comment]
+1

**Comment by affinitycloud** [comment]
+1

**Comment by Bodge-IT** [comment]
+1

**Comment by henrikgregersen** [comment]
+1000000000 ;-)

**Comment by satcreative** [comment]
+1
Come on folks, you know it makes sense... ;-)

**Comment by wmurphy** [comment]
\+1

**Comment by charlesemarsh** [comment]
+1

**Comment by explorer2309** [comment]
+1
A solid basket would be very useful because that will allow adding a number inside it, indicating number of items in basket.

**Comment by Sironfoot** [comment]
+1 for this. We Europeans love our shopping baskets :-)
Some inspiration http://simpleicon.com/sets/basket/

PS: Awesome Font Awesome is awesome, keep up the good work!

**Comment by johnend** [comment]
+1 Might as well, more relevant in the UK :)

**Comment by mintonkendereski** [comment]
+1

**Comment by georgeduartevnda** [comment]
+1

**Comment by anothergemma** [comment]
+1

**Comment by Bodge-IT** [comment]
Could you please add a damn basket instead of all these other weird, totally unnecessary icons you've adding since we started this request.  There's clearly enough support and we're all waiting to get on with our lives!

**Comment by mihai101** [comment]
+1

**Comment by markjcasey** [comment]
How is this still not an icon?!

**Comment by mihai101** [comment]
Dave pls :(

**Comment by clopezcapo** [comment]
+1! It is unbelievable there is still no icon... 
Btw, I was just trying to know when will be the next release, somebody has an idea?

**Comment by jimmellor** [comment]
+1

**Comment by leetskills** [comment]
+1

**Comment by ronklaren** [comment]
+1

**Comment by jamesefl** [comment]
Spock icons but no Shopping Basket WTF:

Hi and welcome to the first Font Awesome email update!

We’re crazy excited to announce Font Awesome 4.4! Here’s what’s new:

66 new icons 
Closed 65 of the most commented issues, including 
Full set of 5 hourglass icons 
Most requested brands, like TripAdvisor, Odnoklassniki, Wikipedia, Contao, 500px, Amazon, and more! 
Plus all new rock, paper, scissors, lizard, spock icons!

**Comment by satcreative** [comment]
Oh, very poor.
Has FA become a wee club that are in it 'for the LOLs'?
Basket please, not basket case.

**Comment by tagliala** [comment]
please be nice. This icon is scheduled for the 5.0.0 release

If you can't wait, please consider a custom build: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

**Comment by clopezcapo** [comment]
Hi Tagliala,

Is there some place where I can see the icons that are scheduled for the 5.0.0 release, and more important for me, when will be?

Thanks.

**Comment by satcreative** [comment]
That's good news, thank you Tagliala :)
How many releases is 5.0.0 away?

**Comment by Bodge-IT** [comment]
@tagliala Why make us wait until 5?  This icon is already long needed and is one of the most commented issues.  You claim to have "resolved" the most commented requests, clearly an innacurate claim.    If you're looking for curtesy, why not show some to 123+ users who have taken the time to suggest a 'useful' improvement to FA?

**Comment by Sherif-Ahmed** [comment]
+1

**Comment by quaertym** [comment]
:+1:

**Comment by danandersonasc** [comment]
+1

**Comment by fmellberg** [comment]
+1

**Comment by edwinkoehoren** [comment]
+1

**Comment by trancegaffer** [comment]
+1 

Appreciate the good work, but ignoring this request and adding "Rock, Paper, Siccors" smacks of geek-in joke over practicality.

**Comment by hunter101** [comment]
+1

**Comment by togis** [comment]
+1

**Comment by Dan-Brantze** [comment]
+1

**Comment by moonshineandy** [comment]
+1

**Comment by Bodge-IT** [comment]
Stop wasting your time. THEY'RE NOT LISTENING TO +1s.

**Comment by hunter101** [comment]
+2?

**Comment by renanCaraujo** [comment]
+54 :(

**Comment by coelhoricardo** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by cynthia-pm** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.4.1-wip branch. Closing.

**Comment by Bodge-IT** [comment]
2 1/2 years after first request, it gets heard!
That's service!

**Comment by Sironfoot** [comment]
@Bodge-IT Do you want a refund for your free open source software :-)

**Comment by Bodge-IT** [comment]
@Sironfoot that's got nothing to do with it.  OS is by its nature community driven!
Without the community it's nothing, when when such a large part of the community are ignored for so long, backs get up!

**Comment by cynthia-pm** [comment]
Thanks @davegandy
