### ISSUE TITLE
Icon request: icon-academia

### ISSUE THREAD

**Issue by sanjeevverma1** [FortAwesome/Font-Awesome#9624]
Website: www.academia.edu

Assets: https://a.academia-assets.com/images/favicons/favicon-production.ico

Preview:
![image](https://cloud.githubusercontent.com/assets/7389628/17075531/d4739482-5063-11e6-8c44-1f779fe46b56.png)

**Comment by tagliala** [comment]
Duplicate of #2751, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
