### ISSUE TITLE
Icon request: icon-for medical/hospital

### ISSUE THREAD

**Issue by endra89** [FortAwesome/Font-Awesome#9630]
im working at medical it as programer, im need icon for medical like : 
1. inpatien care icon
2. outpatien care icon
3. emergency icon
4. medical record icon 
5. pharmachy icon 
6. laboratoy icon 
im looking font awsome but only few in medical icon. thank for your big help.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
