### ISSUE TITLE
Icon Request: fa-object-union, fa-object-intersection, fa-object-inverse, fa-object-inverse-right, fa-object-inverse-left

### ISSUE THREAD

**Issue by mariosandoz** [FortAwesome/Font-Awesome#9631]
Union, Intersection icon, left, right inverse
![intersection](https://cloud.githubusercontent.com/assets/5907945/17094255/50d02bd8-5278-11e6-8e2a-d836176602b5.png)
![union](https://cloud.githubusercontent.com/assets/5907945/17094256/50f41e9e-5278-11e6-8dd1-53b2f156e1d8.png)

**Comment by tagliala** [comment]
Could you please clarify this request?

How many icons are you requesting?

Please fix examples and title accordingly

**Comment by DoktorJ** [comment]
There are already unicode characters for the "union" symbol (∪) and "intersection" symbol (∩). Check the entire mathematical operators block at http://www.fileformat.info/info/unicode/block/mathematical_operators/list.htm

These may not be as graphically-oriented as the symbols you're requesting, but for most people who would be interested in such things, they'll readily understand what the existing unicode symbols mean I think.

**Comment by mankins** [comment]
Perhaps something like the graphics here: http://3.bp.blogspot.com/-PCTQfPW6KSM/UZaeH_Az_FI/AAAAAAAAA_4/ZOXy03syC4M/s1600/Figure+7_1.jpg

**Comment by mariosandoz** [comment]
@tagliala 
I need 5 icons
union, intersection, left inverse, right inverse, outer
example;

![union](https://cloud.githubusercontent.com/assets/5907945/18542267/2f2ce9f8-7b54-11e6-96b9-e28270ef5cdc.png)
![intersection](https://cloud.githubusercontent.com/assets/5907945/18542271/34ed0fda-7b54-11e6-9e54-8ffa63de8eee.png)
![invint](https://cloud.githubusercontent.com/assets/5907945/18542272/38289110-7b54-11e6-89a1-b17b06ac3e6d.png)
![rdif](https://cloud.githubusercontent.com/assets/5907945/18542279/3d48267e-7b54-11e6-8eae-b705dcfcfce0.png)
![ldiff](https://cloud.githubusercontent.com/assets/5907945/18542286/47a15244-7b54-11e6-9782-d81104ab3af0.png)

**Comment by dckeyes** [comment]
+1

**Comment by mariosandoz** [comment]
is this font not ready yet?

**Comment by sarveshgupta89** [comment]
Were these icons added to the library?

**Comment by sensibleworld** [comment]
This is a quick update to let folks know that we’re refining our icon request workflow behind the scenes, and as part of that we’re going through all open requests and filing them into several new buckets to be addressed.

In this case we’re closing this issue because it already exists in Font Awesome Pro! [Take a look at it here.](https://fontawesome.com/search?q=boolean&o=r&s=solid&f=classic)
