### ISSUE TITLE
fa-cc-mastercard update

### ISSUE THREAD

**Issue by mpbzh** [FortAwesome/Font-Awesome#9633]
MasterCard recently updated their logo.

They simplified the circles and removed the type from them.

More details here: http://newsroom.mastercard.com/news-briefs/mastercard-updates-its-iconic-logo-and-brand-identity/

**Comment by tagliala** [comment]
thanks for reporting this

**Comment by davegandy** [comment]
Excellent @tagliala. Great find.

**Comment by davegandy** [comment]
(And, perhaps ironically, that Mastercard page is using Font Awesome.) 👍

**Comment by davegandy** [comment]
Updated in 4.7.0-wip branch. Closing.
