### ISSUE TITLE
Icon Request: fa-export

### ISSUE THREAD

**Issue by MichaelHancock** [FortAwesome/Font-Awesome#9635]
FA already has several share/export icons, but none are quite what i am looking for (this is perhaps the closest http://fontawesome.io/icon/share-square-o/). Below is a screenshot of the sort of icon i mean. It is used a lot across the iOS interface and it would be nice to continue that same look and feel in my own app.

![screen shot 2016-07-25 at 13 35 38](https://cloud.githubusercontent.com/assets/10632072/17101821/7ed1613c-526e-11e6-96b0-68016180ea1e.png)

**Comment by tagliala** [comment]
Duplicate of #1020 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by MichaelHancock** [comment]
Apologies, I did not see this when i looked at open issues. I will 👍  this now.
