### ISSUE TITLE
Certain icon not showing up only on iPhone

### ISSUE THREAD

**Issue by www89ee** [FortAwesome/Font-Awesome#9636]
Im starting to lose my mind here,

all the other icons work, everywhere, except for one icon, and only on iPhone.

Im using the latest icons, i have hosted them locally now, before i used bootstrap CDN but the problem was then and still is now the same.

http://89.ee/projektid/89_uus/en/creating-a-website/

In the middle of the page, there should be 4 icons, but the Shopping basket icon is not displaying on iPhone. What the heck?

.fa-shopping-basket:before {
  content: "\f291";
}

**Comment by tagliala** [comment]
Please note that [shopping basket](http://fontawesome.io/icon/shopping-basket/) was added in version 4.5, but your website is loading 4.4 from the CDN

```html
<link rel="stylesheet" id="ut-fontawesome-css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css?ver=4.5.3" type="text/css" media="all">
```

and 4.5.0 from the website itself

```html
<link rel='stylesheet' id='font-awesome-css'  href='http://89.ee/projektid/89_uus/wp-content/plugins/js_composer/assets/lib/bower/font-awesome/css/font-awesome.min.css?ver=4.11.1' type='text/css' media='all' />
```

You cannot predict which one will be loaded first, it also depends on browser.

Hope it helps.

Closing here
