### ISSUE TITLE
Icon request: fa-measuring-tape

### ISSUE THREAD

**Issue by bclair85** [FortAwesome/Font-Awesome#9640]
I need to see if you have a couch and measuring tape icon.  I have provided both in the attachment as pdf files I created in illustrator.  How can I make these work without bothering you? (File type and code)  Or can we add these to the library or something very similar.  Thanks Brent 

[extra icons.pdf](https://github.com/FortAwesome/Font-Awesome/files/382374/extra.icons.pdf)

**Comment by tagliala** [comment]
Couch is a duplicate of #759 , please :+1: that request

Renaming and leaving this open as `fa-measuring-tape`

**Comment by aethior** [comment]
@tagliala check: #8437

**Comment by tagliala** [comment]
All dups, closing here.

Adding measuring-tape to #8437
