### ISSUE TITLE
Icon Request: programming languages

### ISSUE THREAD

**Issue by josealgardataborges** [FortAwesome/Font-Awesome#9643]
Could it be possible to have font-awesome icons for programming languages? Like: php, C#, C++, Java, Perl, Javascript, Ruby, Pascal, Cobol, Basic, etc...

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
