### ISSUE TITLE
Icon books

### ISSUE THREAD

**Issue by pmerinocobaleda** [FortAwesome/Font-Awesome#9645]
Name: icon-books
![books-01](https://cloud.githubusercontent.com/assets/20659929/17133564/e3018462-5326-11e6-80f1-c25fc84a0545.png)

**Comment by tagliala** [comment]
Duplicate of #5098, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
