### ISSUE TITLE
Icon distance-learning-courses

### ISSUE THREAD

**Issue by pmerinocobaleda** [FortAwesome/Font-Awesome#9647]
I need a icon for distance learning courses.
Name: icon-dist
![books-01](https://cloud.githubusercontent.com/assets/20659929/17134755/4c4fd50e-532c-11e6-93cb-37e381166b4c.png)
ance-learning-courses

**Comment by tagliala** [comment]
Is this a brand?

**Comment by pmerinocobaleda** [comment]
It is a web application icon.

**Comment by tagliala** [comment]
Could you please provide a link to this application and more info about it?
