### ISSUE TITLE
Icon request: fa-breastfeeding

### ISSUE THREAD

**Issue by evapete** [FortAwesome/Font-Awesome#9657]
We are missing the international breastfeeding symbol.

![2000px-breastfeeding-icon-med svg](https://cloud.githubusercontent.com/assets/9268639/17179278/9e8db16e-53e6-11e6-8cce-622607eae5c5.png)

**Comment by PhillUpNorth** [comment]
+1

**Comment by NKjoep** [comment]
why web application tag? isn't this a medical-related icon?

**Comment by DoktorJ** [comment]
I would agree that this fits better as medical than "web application"

**Comment by PhillUpNorth** [comment]
It's a useful icon for facilities available at venues and events. I'd suggest accessibility or facilities related, but I'm happy with web application icons.

**Comment by DoktorJ** [comment]
Yes, facilities or accessibility would be even better than medical, but there don't seem to be tags for either. I think medical is still better than "web application".

**Comment by evapete** [comment]
I would pick Medical over Accessibility. Can the icon be tagged as both?

**Comment by jjwebsol** [comment]
+1 for this. Would definitely be useful as a facilities indicator, but medical seems like a reasonable category too.

**Comment by einavsh** [comment]
:+1:

**Comment by sensibleworld** [comment]
Took way too long, but this icon is now available: https://fontawesome.com/icons/person-breastfeeding?s=solid
