### ISSUE TITLE
Icon Request: more times and foods

### ISSUE THREAD

**Issue by saqwild** [FortAwesome/Font-Awesome#966]
Hello, thank for the great work.
There are very few Clock and Time or food/drink related icons, is this possible to add more?

**Comment by tagliala** [comment]
Sorry but I have to close this request and I have also to update contributing guidelines to deal requests like this.

Font Awesome is more about icons that are broadly applicable to the web to folks developing web applications. Your request contains a lot of icons that are related to a very specific field.

Feel free to contact Dave privately if you need a custom solution

Closing here
