### ISSUE TITLE
Issue with Font Awesome icons rendering in Internet Explorer 11.4xx.xxxxx.x

### ISSUE THREAD

**Issue by ssitadmin** [FortAwesome/Font-Awesome#9661]
Encountered and issue with Internet Explorer 11 on Windows 10 where custom web fonts (specifically Font Awesome - http://fontawesome.io/icons/) are not rendering. We notice that this is isolated to Internet Explorer versions starting with 11.4 (11.420.10586.0, 11.494.10586.0) and these versions only seem to appear in Windows 10.

To replicate issue, use one of these versions/builds of Internet Explorer and navigate to the link provided above for the list of Font Awesome fonts. You will see the text labels for the fonts (icons) that are listed but the actual font (icon) to the left is not rendered.

When inspecting the console displays the following:
CSS3111: @font-face encountered unknown error.
fontawesome-webfont.ttf

The Inspect Element CSS displays a crossed out content attribute.

(please see attachments)
![os_build](https://cloud.githubusercontent.com/assets/20690259/17192034/c8a08b28-541a-11e6-9690-b81188152e74.PNG)
![11 494 10586 0_error](https://cloud.githubusercontent.com/assets/20690259/17192033/c899feb6-541a-11e6-92f6-e9c5fc8d7f3a.PNG)
![css_content](https://cloud.githubusercontent.com/assets/20690259/17192032/c8992c52-541a-11e6-978b-d7a5d8fef6f3.png)

**Comment by wolfy1339** [comment]
Please check this troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#fonts-not-rendering-properly-running-windows-10

**Comment by ssitadmin** [comment]
Thanks a million! It appears the link further down that article .(https://technet.microsoft.com/itpro/windows/keep-secure/block-untrusted-fonts-in-enterprise#Turn_on_and_use_the_Blocking_untrusted_fonts_feature) solved the problem. 

In the registry I changed the specified registry entry (HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel\MitigationOptions) from enabled (1000000000000) to disabled (2000000000000).

Why this is only happening to IE 11 and not Edge or any other browser for that matter is beyond me but appears to be the culprit nonetheless.

Thanks again!
