### ISSUE TITLE
Icon Request: fa-<drawing program tools>

### ISSUE THREAD

**Issue by rgrocha** [FortAwesome/Font-Awesome#9664]
Hi,

Not an specific one, but a set of them for those kind of apps/tools. Like

- line, it could be an stright line between two point
- multiline, a 2 or 3 line segments, like Z or <
- polygon, like a pentagon or hexagon. In fact a serie of geometric forms could be handy too: triangle, pentagon, hexagon, heptagon, etc...
- bezier curve
- color control, like in tv remotes, three overlapping circles with 3 colors or gray shades
- contrast control, like in tv remotes, a circle half white half black
- brightness control, like in tv remotes, a sun-like icon, with half white half black
- color selection, like a palette
- color pickup, like a dropper
- fill, like a paint can pouring

I'll use that for a few apps I'm using: drawing forms on a map, a basic image manipulation app, etc.
I think they will also be useful for others.

Thank you so much for your hard work!

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
