### ISSUE TITLE
Icon Request: fa-swiming-pool

### ISSUE THREAD

**Issue by hmoriot** [FortAwesome/Font-Awesome#9667]
![swiming-pool](https://cloud.githubusercontent.com/assets/15689317/17213051/deab0bce-54d2-11e6-974f-1d5b6dde41ea.png)

**Comment by tagliala** [comment]
Duplicate of #3285 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
