### ISSUE TITLE
Icon Request: fa-collateral-account

### ISSUE THREAD

**Issue by nithin8702** [FortAwesome/Font-Awesome#9680]
Hi,

Could you please upload some more icons related to banking and investment industry.

Examples,
Collateral Account
Legal Entity
Account Group
Trading Account
Custodian Bank
Lending Account

Thanks

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
