### ISSUE TITLE
icon request: fa-jquery, fa-javascript 

### ISSUE THREAD

**Issue by FelixWatilah** [FortAwesome/Font-Awesome#9682]
I would like you to include the following fonts on your next update. I am your great fan, your fonts help me to make great websites, for my assignments.
thanks in advance.

**Comment by tagliala** [comment]
Duplicate of #1665 and #1711 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
