### ISSUE TITLE
Icon Request: fa-messenger

### ISSUE THREAD

**Issue by matrush** [FortAwesome/Font-Awesome#9687]
I think it would be Awesome if you guys could add Messenger (http://m.me) related icons.
Messenger has 1B MAU now so why not?
Thanks

**Comment by tagliala** [comment]
Duplicate of #6912 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
