### ISSUE TITLE
Icon Request: fa-tire

### ISSUE THREAD

**Issue by burgerautomotive** [FortAwesome/Font-Awesome#9688]
I am looking for icons that are auto shop/auto body/auto repair related please. Thank you very much. I appreciate any and all help.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

tire: #4430
