### ISSUE TITLE
Icon Request: fa-map-marker-check

### ISSUE THREAD

**Issue by rahulpandey1** [FortAwesome/Font-Awesome#9691]
i am looking for a icon which will have a tick on the address icon.
currently i am using map-Marker 
http://fontawesome.io/icon/map-marker/

<i class="fa fa-22px fa-map-marker addr-color">
but wanted an icon which denotes address is valid.
i created one below need almost same like this
![addressvalidation](https://cloud.githubusercontent.com/assets/12515078/17360346/c3726bda-5988-11e6-9e11-c8419654b702.jpg)

**Comment by tagliala** [comment]
Refers to #1181
