### ISSUE TITLE
Icon Request: fa-shoe

### ISSUE THREAD

**Issue by keery** [FortAwesome/Font-Awesome#9692]
Hello,
Missing a shoe, example :
[http://www.vector-eps.com/wp-content/gallery/sport-shoes-vector-silhouettes/sport-shoe-vector-silhouette1.jpg](url)
AND
[https://pixabay.com/static/uploads/photo/2014/04/03/10/55/shoe-311736_640.png](url)

That could be used for a shop or maps.

**Comment by tagliala** [comment]
Please +1 the most appropriate one from the following: https://github.com/FortAwesome/Font-Awesome/search?q=shoe&state=open&type=Issues&utf8=%E2%9C%93
