### ISSUE TITLE
Icon Request: fa-t-shirt

### ISSUE THREAD

**Issue by keery** [FortAwesome/Font-Awesome#9693]
Hello,
Missing a T-shirt, example :
[http://images.all-free-download.com/images/graphicthumb/black_t_shirt_clip_art_19010.jpg](url)

That could be used for a shop.

**Comment by tagliala** [comment]
Duplicate of #715 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
