### ISSUE TITLE
Icon Request: fa-glasses

### ISSUE THREAD

**Issue by keery** [FortAwesome/Font-Awesome#9694]
Hello,
Missing a glasses, example :
[http://www.clipartbest.com/cliparts/dc7/eBp/dc7eBpyRi.png](url)

That could be used for opticians.

**Comment by tagliala** [comment]
Duplicate of #1043 , planned for 5.0.0, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
