### ISSUE TITLE
Icon Request: fa-lightbulb

### ISSUE THREAD

**Issue by hgw734** [FortAwesome/Font-Awesome#9695]
Hello, 

perhaps this icon has been reqested already, but if not it would be wonderful if you could make this version of the lightbulb available. I am using lightbulb-o in a navbar and it would be great to have the pairing to show on/off selection. (Analagous to the icon: bookmark, bookmark-o)

Thank you kindly for your consideration,
Holger

**Comment by langschlaefer** [comment]
+1

**Comment by naveed-ahmad** [comment]
+++++1

**Comment by ansien12** [comment]
+1

**Comment by aethior** [comment]
Hi @hgw734,

This issue is solved using [solid version (on)](https://fontawesome.com/icons/lightbulb?s=solid) and [regular version (off)](https://fontawesome.com/icons/lightbulb?s=regular), right?

Regards.

cc/ @tagliala

**Comment by tagliala** [comment]
I would say so.

there is also https://fontawesome.com/icons/lightbulb-on?s=solid in FA Pro
