### ISSUE TITLE
Icon request: fa-soundcloud-square

### ISSUE THREAD

**Issue by idleberg** [FortAwesome/Font-Awesome#9697]
Not sure if there's a trick to stack `fa-soundcloud` onto `fa-square`, but since other social icons have both variants, it would be nice if the SoundCloud icon was available in two flavours.

**Comment by tagliala** [comment]
Duplicate of #5485, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
