### ISSUE TITLE
Adding SVG definition file to fonts folder

### ISSUE THREAD

**Issue by Tklaversma** [FortAwesome/Font-Awesome#9700]
Hi,

I think it would be a nice addition to add a SVG-definition file, so that people who want to use FontAwesome icons as SVG-icons can use them.

IcoMoon is already supporting this, but it would be nice to be able to use `composer` on the original FontAwesome library.

A SVG-definition file (like IcoMoon creates them for example) will look like:

```
<svg style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <symbol id="icon-user" viewBox="0 0 25 32">
            <title>user</title>
            <path class="path1" d="M25.143 25.089q0 2.143-1.304 3.384t-3.464 1.241h-15.607q-2.161 0-3.464-1.241t-1.304-3.384q0-0.946 0.063-1.848t0.25-1.946 0.473-1.938 0.768-1.741 1.107-1.446 1.527-0.955 1.991-0.357q0.161 0 0.75 0.384t1.33 0.857 1.929 0.857 2.384 0.384 2.384-0.384 1.929-0.857 1.33-0.857 0.75-0.384q1.089 0 1.991 0.357t1.527 0.955 1.107 1.446 0.768 1.741 0.473 1.938 0.25 1.946 0.063 1.848zM19.429 9.143q0 2.839-2.009 4.848t-4.848 2.009-4.848-2.009-2.009-4.848 2.009-4.848 4.848-2.009 4.848 2.009 2.009 4.848z"></path>
        </symbol>
        <symbol id="icon-film" viewBox="0 0 34 32">
            <title>film</title>
            <path class="path1" d="M6.857 28.571v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM6.857 21.714v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM6.857 14.857v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM25.143 28.571v-9.143q0-0.464-0.339-0.804t-0.804-0.339h-13.714q-0.464 0-0.804 0.339t-0.339 0.804v9.143q0 0.464 0.339 0.804t0.804 0.339h13.714q0.464 0 0.804-0.339t0.339-0.804zM6.857 8v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM32 28.571v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM25.143 14.857v-9.143q0-0.464-0.339-0.804t-0.804-0.339h-13.714q-0.464 0-0.804 0.339t-0.339 0.804v9.143q0 0.464 0.339 0.804t0.804 0.339h13.714q0.464 0 0.804-0.339t0.339-0.804zM32 21.714v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM32 14.857v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM32 8v-2.286q0-0.464-0.339-0.804t-0.804-0.339h-2.286q-0.464 0-0.804 0.339t-0.339 0.804v2.286q0 0.464 0.339 0.804t0.804 0.339h2.286q0.464 0 0.804-0.339t0.339-0.804zM34.286 5.143v24q0 1.179-0.839 2.018t-2.018 0.839h-28.571q-1.179 0-2.018-0.839t-0.839-2.018v-24q0-1.179 0.839-2.018t2.018-0.839h28.571q1.179 0 2.018 0.839t0.839 2.018z"></path>
        </symbol>

        ...

    </defs>
</svg>
```

and then you are able to use the icons like so:

```
<svg class="icon">
    <use xlink:href="<?php echo $svgFileAbsoluteURL ?>#icon-user"></use>
</svg>
```

some CSS:
```
svg:not(:root) {
    object-fit: contain;
    overflow: hidden;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
}
.icon {
    display: inline-block;
    fill: currentColor;
    height: 1em;
    position: relative;
    stroke: currentColor;
    stroke-width: 0;
    width: 1em;
}
```

and voilà.

Anyway possible such a file could be added to the `fonts` folder of this library, so that we can use the icons as SVG and are able to use composer?

**Comment by tagliala** [comment]
The `.svg` file is automatically created by [Font Squirrel Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator), which does not appear to have this option or it does need other work on the original `.otf` file.

Please take a look at https://github.com/encharm/Font-Awesome-SVG-PNG, which provides an .svg sprite with the `id` attribute

I'm going to close here for the moment

**Comment by Tklaversma** [comment]
Maybe I'm not understanding what you are saying (sorry in advance), but I'm talking about **one** .svg-file that contains all FontAwesome icons as definitions (`<symbol>`) instead of `<glyphs>`.

You now have a file called `fontawesome-webfont.svg` in de `/fonts` folder which contain glyphs. Adding another file with the defintions would be awesome!

> The .svg file is automatically created by Font Squirrel Webfont Generator, which does not appear to have this option...

I understand that this is not possible a the moment, otherwise I would not be asking this question. But adding a svg-definition-file through Grunt for example, is what I'm asking. Would you (or anyone else) look into that, so that we can implement this in the current repo?

> Please take a look at https://github.com/encharm/Font-Awesome-SVG-PNG, which provides an SVG sprite with the id attribute

The repository you are referring me to is not even a fork and therefor does not contain the latest FontAwesome build, which is exactly one of my points.

Again, generating such a file for this repository will allow me and others to use the icons as svg's and use composer.

**Comment by tagliala** [comment]
> The repository you are referring me to is not even a fork and therefor does not contain the latest FontAwesome build, which is exactly one of my points.

An (official) updated version of Font-Awesome-SVG-PNG is what you are asking for? You could open an issue there and ping the authors to see if the repo is still mantained, you could also fork it and update it (there are pull requests). Font awesome is listed as a dev dependency in their [package.json](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/package.json#L24)

**Comment by tagliala** [comment]
btw... duplicate of #3203
