### ISSUE TITLE
Icon Request: fa-jmbans

### ISSUE THREAD

**Issue by oto1ro** [FortAwesome/Font-Awesome#9709]
I'm "Jmbans developer staff".
Please make a jmbans logo for FontAwesome.
So please see https://pbs.twimg.com/profile_images/668486700297916418/ae2Eedyx_400x400.png and 
https://www.g-second.net/file/JMBans.png

**Comment by tagliala** [comment]
could you please clarify what jmbans is?

**Comment by oto1ro** [comment]
for example?

**Comment by oto1ro** [comment]
I'm sorry... I'm japanese. i speak english a little...

**Comment by tagliala** [comment]
is jmbans a programming language? is it a brand?

does jmbans have a website?

**Comment by oto1ro** [comment]
ah,ok.
Jmbans is brand.
Jmbans site is https://www.jmbans.net/

**Comment by tagliala** [comment]
> https://www.jmbans.net/

I'm not able to connect to this website

**Comment by oto1ro** [comment]
oh.sorry. server was downing. just a moment..

**Comment by oto1ro** [comment]
this site language is japanese, so would that be all right?

-About JMBans
JMBans is bans share system for "Minecraft".
it's relatively new system.

**Comment by oto1ro** [comment]
And this site using Basic authentication.
it is authentication information.
Username : fa
Passphrase : nlLjugdpligc35kfmoW

**Comment by oto1ro** [comment]
and this system still unpublished.
please be careful this authentication information.
i will delete this information at August 10.

**Comment by douglasdeodato** [comment]
hello do you have a svg version of this logo?

**Comment by tagliala** [comment]
@oto1ro if jmbans is a personal project of yours, please consider a custom version: https://github.com/FortAwesome/Font-Awesome/wiki/Customize-Font-Awesome

I'm going to close this one, feel free to comment when your website is online

**Comment by oto1ro** [comment]
>hello do you have a svg version of this logo?
yes.
