### ISSUE TITLE
Icon-request: fa-phabricator

### ISSUE THREAD

**Issue by SamanthaNguyen** [FortAwesome/Font-Awesome#9712]
It'd be nice to have an icon of the Phabricator logo as a Font Awesome icon :)

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Phacility_phabricator_logo.svg/1024px-Phacility_phabricator_logo.svg.png)

**Comment by tagliala** [comment]
Hi!

This icon will be included in the upcoming Font Awesome 5 Free. 🎉

I'm going to close this request for management purposes

Regards
