### ISSUE TITLE
fa-pied-piper displaying as fa-pied-piper-pp

### ISSUE THREAD

**Issue by durissan** [FortAwesome/Font-Awesome#9718]
I'm having an issue where when I try to call up fa-pied-piper, it's displaying the icon for fa-pied-piper-pp. Is anyone else having this problem?

**Comment by tagliala** [comment]
could you please provide more details or a fiddle showing the issue? please also check our troubleshooting guide: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by tagliala** [comment]
btw I cannot replicate, closing here but feel free to comment

https://jsfiddle.net/tagliala/4Lcpvhoo/7/
