### ISSUE TITLE
icon-Blog Request: fa-blogger

### ISSUE THREAD

**Issue by Ravikumarvm** [FortAwesome/Font-Awesome#9719]
Kindly add a blog icon for social icons

![image](https://cloud.githubusercontent.com/assets/19763906/17482815/0a715ba6-5da1-11e6-8d2a-524537f6ab25.png)

**Comment by tagliala** [comment]
Duplicate of #1088 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by Ravikumarvm** [comment]
Whats the usE of closing it when not included
