### ISSUE TITLE
Icon Request: fa-4K

### ISSUE THREAD

**Issue by standoski** [FortAwesome/Font-Awesome#9721]
Hello,

I have no idea of how to look.

But i'd like to have an icon for the image/video standard: 4K or UHD.

I will use in www.uhdwallpapers.org

_Thank you!_

**Comment by tagliala** [comment]
Duplicate of #7660 (which also contains an example), please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
