### ISSUE TITLE
Icon Request - Icon-Workout

### ISSUE THREAD

**Issue by asrivasts** [FortAwesome/Font-Awesome#9722]
Hi, would it be possible to get a few workout related icons?
icon-yoga (
![image](https://cloud.githubusercontent.com/assets/20916232/17500910/1718880a-5da8-11e6-95a3-d52c8c3fb255.png))

icon-kettlebell (
![image](https://cloud.githubusercontent.com/assets/20916232/17500906/04ea85f2-5da8-11e6-86d5-62a1a2dbd951.png))

icon-barbell (
![image](https://cloud.githubusercontent.com/assets/20916232/17500925/2d567d48-5da8-11e6-80e7-093b1c666e64.png))

icon-overhead-squat
![font-overhead-squat](https://cloud.githubusercontent.com/assets/20916232/17500899/ef11a896-5da7-11e6-8b3a-74ffad42d23c.png)

icon-biceps (
![image](https://cloud.githubusercontent.com/assets/20916232/17500933/3e7e0dde-5da8-11e6-98a5-2e2335da591f.png))

**Comment by tagliala** [comment]
kettlebell: #3845
barebell: #1500 

Please open new, individual requests having care of searching before for the other icons

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

Closing here
