### ISSUE TITLE
Icon request: fa-software

### ISSUE THREAD

**Issue by deadmantfa** [FortAwesome/Font-Awesome#9725]
An Icon for Software will be cool.

Thank you for creating an Awesome project :)

**Comment by tagliala** [comment]
could you please clarify this request?

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by DoktorJ** [comment]
@deadmantfa does [floppy-o](http://fontawesome.io/icon/floppy-o/) work for this purpose? Otherwise, what did you have in mind?

**Comment by ahsteele** [comment]
@DoktorJ came here looking for a fa-software request and found this discussion.

For my purposes the floppy disk does not work as I would posit that it is too universally recognized as "save." Therefore something like this: https://www.iconfinder.com/icons/193675/box_cd_disc_disk_dvd_software_icon would work.

**Comment by tagliala** [comment]
maybe #702 or #908

**Comment by deadmantfa** [comment]
@ahsteele Yes I would like something like that, Sorry for the delayed reply @tagliala  I just saw all the git notifications.

**Comment by tagliala** [comment]
@deadmantfa if #702 or #908 could do the job, please close this one and +1 the proper request, otherwise we need a better title (something like `dvd-with-box`)

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
