### ISSUE TITLE
Icon request: fa-office

### ISSUE THREAD

**Issue by nmilojevic91** [FortAwesome/Font-Awesome#9726]
Hi,
an at office icon would be great. Something like this:

https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Office_room_icon.svg/1024px-Office_room_icon.svg.png

**Comment by tagliala** [comment]
Duplicate of #9495, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
