### ISSUE TITLE
european payment icons / fa-ideal / fa-sofort / fa-bancontact *alias fa-mister-cash / fa-sepa / fa-belfius / fa-paysafecard

### ISSUE THREAD

**Issue by QualityWorks** [FortAwesome/Font-Awesome#9734]
There have been several single requests for some of the European payment methods.
If these are to be made, it makes sense to do all of them at once...
So for reference I made a list:

Sofort (requested #4342 (and #9487))
iDeal (requested #4330)
Bancontact / Mister Cash (requested #8200)
sepa (not requested yet - [http://www.europeanpaymentscouncil.eu/epc_public/previous_site_images/SepaLogoEN.jpg](url))
Belfius Direct (not requested yet - [https://lh3.ggpht.com/RW3YOO09itlnNFDu72tMM8rfZEwaljzQ32_d40DEG2Jan_TeX4qLsnOiYX9mKAV_AII=w300](url))
Paysafecard (not requested yet - [https://www.paysafecard.com/fileadmin/Website/Images/Downloads/logo-paysafecard-einfaerbig.png](url))

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Unfortunately, I cannot leave this issue open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
