### ISSUE TITLE
Icon Request: fa-office

### ISSUE THREAD

**Issue by hurciuc** [FortAwesome/Font-Awesome#9739]
please make an icon for microsoft office like that  [https://c.s-microsoft.com/en-us/CMSImages/Image_Threshold_390x375.png?version=ec93a7e8-c351-5d53-730b-5485204188f2](url)
thx!

**Comment by tagliala** [comment]
Duplicate of #1333, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
