### ISSUE TITLE
Icon Request: fa-dental

### ISSUE THREAD

**Issue by mad1204** [FortAwesome/Font-Awesome#9740]
FA currently has medical, vision, and hearing icons, but nothing for dental. I was just looking for a tooth icon which would probably represent dental best. Maybe even a toothbrush as well. Those 2 icons would represent the dental field perfectly. Would really appreciate it!

**Comment by mad1204** [comment]
FYI for the toothbrush icon, could go with fa-toothbrush. Thank you.

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

Tooth: #1289 
Tootbrush: #5623
