### ISSUE TITLE
typo in font-awesome.css

### ISSUE THREAD

**Issue by gpintar** [FortAwesome/Font-Awesome#9741]
This cached file http://maxcdn.bootstrapcdn.com/font-awesome/2.0/css/font-awesome.css has typos in it that are causing 403 Forbidden responses from MaxCDN.  The "//" after "/2.0/font" is the problem (see below).  Can correct this file and notify MaxCDN to update their cache?

    src:url(https://maxcdn.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.eot?#iefix) format('eot'),
	url(https://maxcdn.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.woff) format('woff'),
	url(https://maxcdn.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.ttf) format('truetype'),
	url(https://maxcdn.bootstrapcdn.com/font-awesome/2.0/font//fontawesome-webfont.svg#FontAwesome) format('svg');

**Comment by ryankane** [comment]
Even if it does not work, it is legacy and you should avoid it.

Try the latest: https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css

It uses relative paths.

```css
src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'),
     url('../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'),
     url('../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'),
     url('../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'),
     url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular')
```

**Comment by gpintar** [comment]
Thanks ryankane, that worked!
