### ISSUE TITLE
icon request: fa-shower

### ISSUE THREAD

**Issue by DerZolf** [FortAwesome/Font-Awesome#9743]
We need an icon for bathtub to use it on a Real Estate site.

Icons like this:
![shower-64](https://cloud.githubusercontent.com/assets/20977506/17603177/42ebadc6-6010-11e6-85f5-67368acfe919.png)

**Comment by tagliala** [comment]
Duplicate of #708, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by MasterJuan** [comment]
+1
