### ISSUE TITLE
Icon Request: fa-view-all and  fa-select-all

### ISSUE THREAD

**Issue by MichLeo** [FortAwesome/Font-Awesome#9745]
I want to use these in a command bar for a reporting web application.

The view all would mean view all pages,

Select All would mean Select all check boxes.

**Comment by ryankane** [comment]
Couldn't you use `fa-eye` and `fa-eye-slash` for view show/hide?

There already is a `fa-square-o` and `fa-check-square-o`.

You may need to provide a reference image. See: [**Font Awesome:** Contributing - Requesting new icons][1].

  [1]: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

**Comment by tagliala** [comment]
select all (with example): #2063 

I need an example of "view all"

**Comment by tagliala** [comment]
No feedback, closing here
