### ISSUE TITLE
circle-o-notch significantly larger than circle

### ISSUE THREAD

**Issue by crownsedge** [FortAwesome/Font-Awesome#9753]
circle-o-notch is significantly larger than circle and other circle-based icons such as play-circle, meaning that it renders strangely when set in the same space as those icons.

For example, see http://stream.playful.cc/ (note: autoplaying audio). You will see circle-o-notch spinning, and then pause-circle appear, and because of the difference in sizing, the transition is more jarring than need be.

**Comment by tagliala** [comment]
adding this to 5.0.0 milestone, so Dave will eventually take a look

**Comment by tagliala** [comment]
Looks fixed to me
