### ISSUE TITLE
Icon Request: fa-eservice

### ISSUE THREAD

**Issue by pascalkessler** [FortAwesome/Font-Awesome#9758]
for eservices and Email
![eservices_enabled_36x36](https://cloud.githubusercontent.com/assets/21056541/17694925/78f197b6-63a6-11e6-88c5-36af15b6725e.png)
![eservices_enabled_36x36](https://cloud.githubusercontent.com/assets/21056541/17694943/98275422-63a6-11e6-8d7d-f21b658c7f19.png)

**Comment by tagliala** [comment]
is this a brand? could you please clarify this request?

**Comment by sensibleworld** [comment]
Doing some repo clean-up and am closing issues where we've asked for some further follow-up/feedback on icon requests, but haven't received it. If these requests are still valid (and more detail can be added), please let us know! Thanks!
