### ISSUE TITLE
 Font Awesome CDN and ASP.Net

### ISSUE THREAD

**Issue by DaveTTS** [FortAwesome/Font-Awesome#9765]
Hi Guys

Thought you may want to know that using the javascript Font Awesome CDN within any ASP.NET 4 page causes an issue where ASP postbacks fail to work in an update panel.  I am not sure why, but we get a parameter count mismatch javascript error, if we remove the javascript CDN and just the the usual stylesheet then postbacks in update panels work as we'd expect.

Cheers

David

**Comment by tagliala** [comment]
do you have a live example?
