### ISSUE TITLE
Icon request: fa-math

### ISSUE THREAD

**Issue by mkingvhs** [FortAwesome/Font-Awesome#9766]
It would be nice to have a font-awesome icon that would denote a mathematical function such as x square (x^2) (for a simple one).

**Comment by tagliala** [comment]
maybe a duplicate of #2675 ?

**Comment by tagliala** [comment]
Duplicate of #2675, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
