### ISSUE TITLE
Change Request: new fa-vk

### ISSUE THREAD

**Issue by cawa-93** [FortAwesome/Font-Awesome#9767]
The new icon is in accordance with the new social network logo.
![image](https://cloud.githubusercontent.com/assets/1662812/17773059/ffa70e12-6554-11e6-8349-0e7d1009ae1b.png) - Old
![image](https://cloud.githubusercontent.com/assets/1662812/17773063/07646a78-6555-11e6-8435-0dd3a9ca6144.png) - New

**Comment by tagliala** [comment]
Note: at the moment I'm writing, EPS and PSD files available at https://vk.com/about still have the old logo

**Comment by cawa-93** [comment]
Support VK said:
> are no plans to change the logo. The naked eye can not see any difference

**Comment by tagliala** [comment]
> are no plans to change the logo. The naked eye can not see any difference

So my eyes are well dressed, because I can definitely see the difference :\

**Comment by cawa-93** [comment]
New EPS and PSD files available at https://vk.com/about

**Comment by tagliala** [comment]
@cawa-93 good, they've changed their mind. Removing the wontfix label

**Comment by Schepilov** [comment]
Fix the logo and add its square version, please.

**Comment by tagliala** [comment]
Hi,

this change will be available in FA5.

Closing here for tracking purposes
