### ISSUE TITLE
Icon Request: fa-traintracks

### ISSUE THREAD

**Issue by Sigkar** [FortAwesome/Font-Awesome#9774]
Train tracks would be a really cool Icon to see on favicon, not to mention it would probably not be too hard to make. Sorry, not too much of a reason here, it's just weird to see the subway icon and no train tracks.

**Comment by tagliala** [comment]
Is this a duplicate of #5801? If it is, could you please post there an example as requested?

**Comment by tagliala** [comment]
No feedback, considering this a duplicate of #5801
