### ISSUE TITLE
Duplicate src-Attribute -> iOS

### ISSUE THREAD

**Issue by vklein** [FortAwesome/Font-Awesome#9777]
In the main Font-Awesome css file there is ```@font-face``` with two src-Attributes.

This causes a Bug in iOS that the Font does not load alwys. 
In my case it just loads after a second reload of the page.

```
src: url('../fonts/fontawesome-webfont.eot?v=4.6.3');
src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3') format('embedded-opentype'),
     url('../fonts/fontawesome-webfont.woff2?v=4.6.3') format('woff2'),
     url('../fonts/fontawesome-webfont.woff?v=4.6.3') format('woff'),
     url('../fonts/fontawesome-webfont.ttf?v=4.6.3') format('truetype'),
     url('../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular') format('svg');
```

**Comment by tagliala** [comment]
Is this the cause of #7770?

**Comment by leecollings** [comment]
I've never seen this bug appear in iOS, and I use the same method of FA in many websites, that are all mobile responsive.

**Comment by vklein** [comment]
The dublicate src attribute was not the bug. 
This issue is duplicate to #7770
