### ISSUE TITLE
Add cup filter to fa-trophy

### ISSUE THREAD

**Issue by Zhouxing-Su** [FortAwesome/Font-Awesome#9778]
Please add medal or cup which may be used in CV for items of honors and awards.

**Comment by tagliala** [comment]
medal: #1898 

Leaving this open as `fa-cup`

**Comment by tagliala** [comment]
Ref: #4601

**Comment by aethior** [comment]
@tagliala Duplicate of `fa-trophy` (http://fontawesome.io/icon/trophy/) icon?

**Comment by tagliala** [comment]
fff, sure.
