### ISSUE TITLE
Website is broken - JS error and download modal isn't working

### ISSUE THREAD

**Issue by distinctdan** [FortAwesome/Font-Awesome#9779]
Not sure if this is the right place to report this. I tried to download font awesome, but the website is broken. There's a javascript error on the console that says: `$(...).collapse is not a function` - site.js:101

**Comment by tagliala** [comment]
Could you please provide more details?

1. website
2. browser and os
3. font awesome load method (cdn (js/css)/maxcdn/self-hosted)

(I suppose that the loading method is cdn/js)

**Comment by distinctdan** [comment]
Sure thing, we're self hosted, so I was trying to download it through the main website using a web browser (http://fontawesome.io/). Happened in chrome and firefox. However, it's working now so someone must have noticed and fixed it.

**Comment by tagliala** [comment]
> However, it's working now so someone must have noticed and fixed it.

*Latest commit 4d05a68  12 days ago*

Nope, maybe a temporary network error
