### ISSUE TITLE
Icon request: icon-english / icon-greek

### ISSUE THREAD

**Issue by kosmastsk** [FortAwesome/Font-Awesome#9780]
Please make an icon to represent the language in the menu from Greek to English and vice versa.
Simple icons that write on them: "en" and "el", such as [this one](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/En-icon_Wikipedians.svg/104px-En-icon_Wikipedians.svg.png): 
Thank you :)

**Comment by tagliala** [comment]
Sorry, I'm going to close this.

Ref: #7931

Please take a look at this blogpost http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/
