### ISSUE TITLE
Font-Awesome CDN breaks Angular2 RC5 Data-binding

### ISSUE THREAD

**Issue by MoxxNull** [FortAwesome/Font-Awesome#9781]
I am using Fontawesome & Angular 2 RC 5 .
The moment I add 
`<script src="https://use.fontawesome.com/f020000e9.js">`
my angular Data Binding breaks and shows weird behavior  (Sometimes it works, sometimes it doesn't .. every page reload shows another result).

The moment I comment it out, everything works as it should.

**Comment by tagliala** [comment]
could you please provide a fiddle showing the issue to help debugging?

**Comment by AndyMeps** [comment]
Hi, I've just discovered this issue myself - commenting out font awesome CDN resolves the issue; I've been using angular cli - not sure if that is the same with MoxxNull. If I can strip content from my app and upload it to github would that be useful?

**Comment by MoxxNull** [comment]
Sorry I missed your comment tagliala. Unfortunatly with the "official" angular-plunker the issue does not show, I already tested that. 
But with angular-cli one could easily test it.

Mine was not with angular-cli, as it is an "old" sample app I keep updating sind beta 5 or something.
But I  reproduced the error with angular-cli aswell.

**Comment by tagliala** [comment]
a reduced test case on fiddle/codepen/whatever would be better

**Comment by tagliala** [comment]
No feedback, closing here
