### ISSUE TITLE
Icon Request: fa- US Holiday Icons

### ISSUE THREAD

**Issue by rehrman** [FortAwesome/Font-Awesome#9783]
fa-new-years [party hat and/or streamers]
fa-valentines (alias for fa-heart)
fa-st-patricks [4 leaf clover]
fa-easter [decorated egg]
fa-july-fourth [bottle rocket type firework]
fa-halloween [Jack-o-lantern]
fa-thanksgiving [cooked turkey]
fa-hanukkah [menorah]
fa-christmas (alias of fa-tree)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by rehrman** [comment]
Geremia,

Understood. Would you like me resubmit these, or is the concept something you are just not looking for? I submitted them together because I thought they could be grouped together – and I did not supply images because I assumed it was generic enough. With that being said, I would be more than happy to submit each one individually, with images, if the concept is something you approve of.

Thanks for your time.

- r


Robert Ehrman
42 milligrams, LLC
the weight of creativity.

www.42mg.com<http://www.42mg.com/>

248-782-7520 direct
248-782-7556 main

**Comment by tagliala** [comment]
@rehrman please follow contributing guidelines.

Open new individual request with a title that represents the icon (eg: cooked-turkey instead of thanksgiving, which could be added as a filter)

There are also duplicates #4039, #1593

**Comment by GVDmeijde** [comment]
any news on the progress of these icons? (i know this is closed but i want them anyway xD)

**Comment by rehrman** [comment]
Gijs,

No, I got lambasted pretty good for not submitting correctly, so I just let it go.
I may resubmit at a later date, but I had other things to keep me busy so I moved on. ☺

- r


Robert Ehrman
Principal
your daily dose of code.
direct:248-782-7520
office:
248-782-7556
www.42mg.com

**Comment by GVDmeijde** [comment]
Dear,

Shame, thanks for replying!

Best regards,
Gijs van der Meijde


________________________________
Van: rehrman <notifications@github.com>
Verzonden: dinsdag 12 december 2017 14:51
Aan: FortAwesome/Font-Awesome
CC: Meijde, G.J. van der (gijs); Comment
Onderwerp: Re: [FortAwesome/Font-Awesome] Icon Request: fa- US Holiday Icons (#9783)

Gijs,

No, I got lambasted pretty good for not submitting correctly, so I just let it go.
I may resubmit at a later date, but I had other things to keep me busy so I moved on. ☺

- r


Robert Ehrman
Principal
your daily dose of code.
direct:248-782-7520
office:
248-782-7556
www.42mg.com
