### ISSUE TITLE
Icon Request - Google Cardboard

### ISSUE THREAD

**Issue by easaw** [FortAwesome/Font-Awesome#9785]
Available as an SVG and free to use for Google VR Devs, I think this should be incorporated ASAP :)

(rename file to .svg - remove .txt)

[cardboard.svg.txt](https://github.com/FortAwesome/Font-Awesome/files/428922/cardboard.svg.txt)

**Comment by tagliala** [comment]
Ref: #6590

**Comment by ccharlton** [comment]
Close this in favor or #6590?

**Comment by thejameshay** [comment]
👍

**Comment by easaw** [comment]
Closed due to duplicate
