### ISSUE TITLE
Icon Request: Bilibili

### ISSUE THREAD

**Issue by wordlesswind** [FortAwesome/Font-Awesome#9789]
Bilibili (stylized bilibili, simplified Chinese: 哔哩哔哩; traditional Chinese: 嗶哩嗶哩; pinyin: bīlībīlī), also nicknamed B Site (B站 as opposeWikipediad to AcFun) in China, is a Chinese video sharing website based in Shanghai, themed around animation, comic, and games (ACG), where users can submit, view and add overlaid commentary on videos. Bilibili uses Adobe Flash or HTML5 player, to play user submitted videos hosted by either itself or third-party sources, featuring a scrolling commenting system nicknamed "bullet curtain" (弹幕 Chinese: danmu; Japanese: danmaku), referring to the bullet hell subgenere of shoot 'em up video games.
From [Wikipedia](https://en.wikipedia.org/wiki/Bilibili)

https://www.bilibili.com/

**Comment by nn708** [comment]
+1

**Comment by wordlesswind** [comment]
@tagliala 
[bilibili.svg.zip](https://github.com/FortAwesome/Font-Awesome/files/1936693/bilibili.zip)
SVG
![1](https://user-images.githubusercontent.com/9050713/39107515-619773e0-46f5-11e8-9fa9-2859816f1c42.png)

**Comment by MengLuoRJ** [comment]
Icon Request Again.

Icon Request: fa-bilibili

Bilibili is a video sharing website themed around anime, manga, and game fandom based in China, where users can submit, view, and add commentary subtitles on videos.
We need this Icon to use as the icon of social link just like Youtube.

Example image in the file.
![favicon](https://user-images.githubusercontent.com/20344258/50698395-cac04500-107f-11e9-89df-a4b52eff7586.png)

**Comment by tagliala** [comment]
@MengLuoRJ please take a look at https://fontawesome.com/community/leaderboard/brands

**Comment by MengLuoRJ** [comment]
@tagliala  . Thank you for your reply. I just didnot get something useful from this page. But I will keep on waiting. Thank you

**Comment by tagliala** [comment]
@MengLuoRJ there is a list of the top 50 most requested brands and the ones we are working on

**Comment by AMiFans** [comment]
Icon Request: fa-bilibili

Bilibili is a video sharing website themed around anime, manga, and game fandom based in China, where users can submit, view, and add commentary subtitles on videos.
We need this Icon to use as the icon of social link just like Youtube.

Example image in the file.
https://user-images.githubusercontent.com/20344258/50698395-cac04500-107f-11e9-89df-a4b52eff7586.png

**Comment by qqiwei** [comment]
+1 waiting

**Comment by Quanfita** [comment]
Icon Request: fa-bilibili

Bilibili is a video sharing website themed around anime, manga, and game fandom based in China, where users can submit, view, and add commentary subtitles on videos. It is popular in China, and it is also a gathering place for young people. Thanks.

Example：https://www.bilibili.com/favicon.ico

**Comment by sparanoid** [comment]
The “SVG” that @wordlesswind provided is not actually in vector format. it's just a rasterized image wrapped by SVG.

So I just extracted vector logo from the official font icon for symbol and text logos:

![image](https://user-images.githubusercontent.com/96356/69005855-b23cde80-0962-11ea-8381-ca534bca77f0.png)

![image](https://user-images.githubusercontent.com/96356/69005859-b668fc00-0962-11ea-8a3e-d19302984e75.png)

[bilibili-svg.zip](https://github.com/FortAwesome/Font-Awesome/files/3855443/bilibili-svg.zip)

**Comment by Chigogo** [comment]
I really want bilibili in FortAwesome! Thanks!

**Comment by archywillhe** [comment]
hmmmm still 0 response huh

**Comment by AdoreJc** [comment]
Icon Request: fa-bilibili
web link https://www.bilibili.com/
icon link https://www.iconfont.cn/search/index?q=bilibili
![bilibili-fill](https://user-images.githubusercontent.com/45906467/73301322-8d75aa80-41e0-11ea-9b0a-964ddca413cb.png)
We really need it, please add it.

**Comment by Aknightofvoid** [comment]
图标请求：fa-bilibili
网站链接https://www.bilibili.com/
图标链接https://www.iconfont.cn/search/index?q=bilibili 我们确实需要它，请添加它。
胆汁充盈

**Comment by BattleWoLFz99** [comment]
Please add it! Bilibili is now like Youtube in China.

**Comment by loadingfd** [comment]
不行玩意，换阿里的iconfont吧

**Comment by wordlesswind** [comment]
time out

**Comment by tagliala** [comment]
Hi @wordlesswind 

Please consider reopening this request, because it has a lot of support from the community.

Closing it would mean to restart from 0 in the [LeaderBoard](https://fontawesome.com/community/leaderboard/brands). Here it is [how requests work](https://fontawesome.com/community/leaderboard/brands#faq) and it contains information about why some requests are still open after several years

If you are bothered by notifications, you can unsubscribe by using the button on the right sidebar

/cc @robmadole @sensibleworld 

Ref: #17198

**Comment by wordlesswind** [comment]
> Hi @wordlesswind
> 
> Please consider reopening this request, because it has a lot of support from the community.
> 
> Closing it would mean to restart from 0 in the [LeaderBoard](https://fontawesome.com/community/leaderboard/brands). Here it is [how requests work](https://fontawesome.com/community/leaderboard/brands#faq) and it contains information about why some requests are still open after several years
> 
> If you are bothered by notifications, you can unsubscribe by using the button on the right sidebar
> 
> /cc @robmadole @sensibleworld
> 
> Ref: #17198

OK, I have re-opened.

**Comment by ssst0n3** [comment]
why not use https://www.iconfont.cn/search/index?searchType=icon&q=bilibili

**Comment by pai233** [comment]
+1 We need it!

**Comment by MegChai** [comment]
We need it!

**Comment by iliyian** [comment]
We need it!!!

**Comment by SK-415** [comment]
We need it!

**Comment by RivenNero** [comment]
We need it!

**Comment by leyulin** [comment]
we need it! why? NO RESPONSE?

**Comment by hesy41** [comment]
Bilibili is a very popular video platform in China among the younger generation. Please add it to official icon so that web programmer are able to include it

**Comment by rootsongjc** [comment]
+1

**Comment by sensibleworld** [comment]
Just added: https://fontawesome.com/v6.0/icons/bilibili?s=brands
