### ISSUE TITLE
Broken link success page

### ISSUE THREAD

**Issue by ilpatrol** [FortAwesome/Font-Awesome#9793]
"Try Again" link doesn´t work in success page when submit email for CDN

**Comment by tagliala** [comment]
From https://cdn.fontawesome.com/register/success I'm able to click on "Try again" (home page).

I think you should insert your email again. It doesn't seem a bug, let's ask @talbs if this behavior is intended

**Comment by Devinsuit** [comment]
"Try again" button doesn't work  in http://fontawesome.io/cdn/success/

**Comment by tagliala** [comment]
@Devinsuit thanks, got it.

@talbs there are broken links at:
* https://github.com/FortAwesome/Font-Awesome/blob/master/src/cdn/error.html#L38
* https://github.com/FortAwesome/Font-Awesome/blob/master/src/cdn/success.html#L25

Don't know where you want to redirect users, maybe you could hardcode https://cdn.fontawesome.com/

**Comment by talbs** [comment]
Thanks for the heads up, folks. I'm on it and will post a fix shortly.
