### ISSUE TITLE
Icon Request: Find Penguins Logo

### ISSUE THREAD

**Issue by pdohmen91** [FortAwesome/Font-Awesome#9799]
There is a new Traveling Social Network and I would prefer to use the icon via font awesome:
https://findpenguins.com

**Comment by tobias-r** [comment]
Same here!

**Comment by pdohmen91** [comment]
Is there a Guide how to create a new icon? Then I would do this and could use it for myself even if it will not be added for the public.

**Comment by pdohmen91** [comment]
Not needed anymore from my side.
