### ISSUE TITLE
New icons: numbers

### ISSUE THREAD

**Issue by steunix** [FortAwesome/Font-Awesome#9802]
It may be useful to have digits (1-9) as subscript or superscript, in order to be used as fa-stack with others...

**Comment by tagliala** [comment]
I'm going to close this one, please use standard unicode point, if you really need numbers as icons

Take also a look here: http://blog.fontawesome.io/2014/05/19/stacking-text-and-icons/

Ref: #6099 #2158 #5019

**Comment by steunix** [comment]
Thanks, didn't know that!
