### ISSUE TITLE
Icon request: icon-envelope-open

### ISSUE THREAD

**Issue by top8843** [FortAwesome/Font-Awesome#9804]
opened envelope means mail which have been read

**Comment by tagliala** [comment]
Duplicate of #897 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by top8843** [comment]
![999](https://cloud.githubusercontent.com/assets/2032385/17937510/f0079652-6a54-11e6-9608-792e4a6795b1.jpg)
