### ISSUE TITLE
Icon request: Linode logo

### ISSUE THREAD

**Issue by SirCmpwn** [FortAwesome/Font-Awesome#9806]
EPS and SVG files are available here: https://www.linode.com/logos

We'd like to use this in https://github.com/Linode/manager. Thanks!

**Comment by aethior** [comment]
@tagliala It's a `Bran Icon` request.

**Comment by davegandy** [comment]
@SirCmpwn Do you have a specific single color version of the logo you'd like to use? This was my first shot at it: 
<img width="697" alt="screenshot 2016-10-04 14 27 59" src="https://cloud.githubusercontent.com/assets/1076721/19130392/f2598a66-8b18-11e6-9341-9cbf09e5cba1.png">

**Comment by SirCmpwn** [comment]
That LGTM

**Comment by davegandy** [comment]
I'll 🚢 it. Already added to 4.7.0-wip branch, so closing here.
