### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by DouglasLoo** [FortAwesome/Font-Awesome#9807]
SMS Icon
http://www.iconarchive.com/show/windows-8-icons-by-icons8/Mobile-Sms-icon.html

needed for responsive web publish of sms phone number with icon to start sms

**Comment by tagliala** [comment]
Duplicate of #1440 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
