### ISSUE TITLE
Icon request: file-new, file-open, file-saveall, file-close, file-closeall

### ISSUE THREAD

**Issue by tiandian** [FortAwesome/Font-Awesome#9809]
hi,

   I hope Font-Awesome have below file-new, file-saveall, file-close, file-closeall icons, 

![image](https://cloud.githubusercontent.com/assets/5468699/17956906/f7ac2b64-6abf-11e6-8d68-9dedab1a1159.png)

 these icons are copy from notepad++'s toolbar.

thanks!

**Comment by tagliala** [comment]
Related to: #1181 

I'm going to close this one

new file: #4998
save all: #433
(maybe others)

Please [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Please follow [contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons)

Closing here
