### ISSUE TITLE
icon request

### ISSUE THREAD

**Issue by prabhs226** [FortAwesome/Font-Awesome#9810]
icon to be placed on a link, header,etc to designate the term `products.`
like if i want to say that this link will open to list of all products we have then there should be fa icon relevant to this term .
we have fa-user but no icon designate an `admin`. It would be very nice if we have one.
the `fa-save` is a hollow icon like the `icons having fa-icon-o`
. but it should also be in a variant like `fa-plus-square`. means that a filled one.  `(sorry if not explained completely)`

**Comment by tagliala** [comment]
@prabhs226 please fix this request/requests following contributing guidelines

Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
