### ISSUE TITLE
Icon Request: fa-blank

### ISSUE THREAD

**Issue by teamlouish** [FortAwesome/Font-Awesome#9814]
It would be nice to have a blank icon, that is completely transparent. Especially helpful with fa-fw so I can have an icon disappear but the text/content around it doesn't shift.

**Comment by tagliala** [comment]
> Especially helpful with fa-fw so I can have an icon disappear but the text/content around it doesn't shift.

You should use `fa-fw` because fontawesome icons have different width by design choice

Ref: #1606
