### ISSUE TITLE
[BUG] FontAwesome.io is not loading properly.

### ISSUE THREAD

**Issue by brennced** [FortAwesome/Font-Awesome#9818]
When opening fontawesome.io the site loads very long and when it's loaded, it just shows the title `Unicorn! · GitHub`. Also a comment with this content is added to the DOM:

```
Hello future GitHubber! I bet you're here to remove those nasty inline styles,
DRY up these templates and make 'em nice and re-usable, right?

Please, don't. https://github.com/styleguide/templates/2.0
```

**Comment by tagliala** [comment]
maybe a temporary problem with github? I cannot replicate
