### ISSUE TITLE
Icon Request: Icons request: icon-apply, icon-save-and-close, icon-submit, icon-send, icon-restore

### ISSUE THREAD

**Issue by thanhhuy27** [FortAwesome/Font-Awesome#9819]
Hi,
I'm building a website & using fontawesome icons. I've found that no icons (even popular) but missing.
For instance, icon-apply or icon-send.
I have no idea in my mind for the moment how they should look like.
Greate if fontawesome create such new icons.

Thanks,
Huy

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
