### ISSUE TITLE
<i class="fa fa-map-o" aria-hidden="true"></i> is not rendering

### ISSUE THREAD

**Issue by craigboman** [FortAwesome/Font-Awesome#9820]
When we render our page, most font awesome icons are rendered, however the fa-map-o icon is not rendering. I have no idea why only this icon is not rendering, since your font awesome website is rendering this fa-map-o icon. 

![image](https://cloud.githubusercontent.com/assets/17816740/18009037/8eb6805a-6b78-11e6-8750-9763fc03420b.png)

**Comment by tagliala** [comment]
`map-o` was introduced in version 4.4

Please make sure you are using an up to date version of Font Awesome

Ref: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

**Comment by craigboman** [comment]
Awesome. Works great now. Many thanks.
