### ISSUE TITLE
Icon Request: grid with four columns

### ISSUE THREAD

**Issue by Litiano** [FortAwesome/Font-Awesome#9822]
Already we have grid with two three columns.
We need a four columns.
Thank you very much in advance.

**Comment by eduardoborges** [comment]
Me too :smile:

**Comment by aethior** [comment]
Hi @Litiano,

This icon has been added in v6.0.0-BETA1.
Check https://fontawesome.com/icons/grid-4

Regards.

cc/ @tagliala
