### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by swehner2** [FortAwesome/Font-Awesome#9823]
Hello, I apologize but I am brand new to using font awesome,  I embedded the code that I was emailed into my header, and copied the code for all 3 facebook icons into my site but no icon is appearing.  Please advise and thank you.

**Comment by swehner2** [comment]
So actually now I have tried multiple icons and none seem to work.  Please help!

**Comment by tagliala** [comment]
@swehner2 this is not a tracker for support requests. Please provide a link to your website

**Comment by swehner2** [comment]
oh sorry I didn't know.  I actually finally figured it out! Thank you so much!!

**Comment by tagliala** [comment]
glad you solved, closing here
