### ISSUE TITLE
Icon Request: icon-uah (currency of Ukraine)

### ISSUE THREAD

**Issue by rizorko** [FortAwesome/Font-Awesome#9827]
Hello,

I am writing to you from Ukraine. It would be great if UAH currency icon was added to FontAwesome. 

Thank you!

![UAH currency icon](https://cloud.githubusercontent.com/assets/1344107/18036882/fc08faae-6d7e-11e6-834b-64e17461d39b.png)

**Comment by tagliala** [comment]
Duplicate of #1451, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by rizorko** [comment]
Oh, I'm sorry. That's my fault.
