### ISSUE TITLE
Icon Request - fa-hanger-o

### ISSUE THREAD

**Issue by SATaylorUSMC** [FortAwesome/Font-Awesome#9830]
We are developing a web-site in which our programmers want to use your Font-Awesome Symbols.  However we really need a hanger symbol to complete this project.  We would love two different ones to show a item is selected and/or unselected.  This is for a "closet" feature on our site.  If you can do this request, or we can pay to have it done quickly, we would appreciate it.   Thanks

**Comment by tagliala** [comment]
hanger: #1659 

renaming this as fa-hanger-o

**Comment by xavigarcia** [comment]
I like something like this, better than an empty hanger:

<img width="62" alt="screen shot 2016-11-26 at 13 49 40" src="https://cloud.githubusercontent.com/assets/2465208/20640499/97a0b8fc-b3df-11e6-80dc-0dd1971c01d6.png">

**Comment by tagliala** [comment]
I'm going to close this, I cannot see any difference between hanger and hanger-o
