### ISSUE TITLE
Icon request: fa-whistle

### ISSUE THREAD

**Issue by sirNemanjapro** [FortAwesome/Font-Awesome#984]
I love FontAwesome, I am grateful that you took time to complete this and make this project fly. I know it will receive even bigger support once the bigger web development audience is familiar with it. There are a lot of people who would benefit of having FA under their belt.

I would humbly ask for three icons:
- whistle
- ~~chair or/and seat~~
- ~~checkered flag~~

**Comment by mgoldwasser** [comment]
+1 chair

**Comment by patrickmcd** [comment]
+1 for whistle

**Comment by comapedrosa** [comment]
+1 whistle

**Comment by EricBorlandAC** [comment]
+1 for whistle

**Comment by milojennings** [comment]
+1 for whistle

**Comment by bstremel** [comment]
+1 for whistle

**Comment by pctux** [comment]
+1 for whistle

**Comment by samirmember** [comment]
+1 for whistle

**Comment by paneum** [comment]
+1 whistle

**Comment by scottbedard** [comment]
+1 whistle

**Comment by dizzib** [comment]
+1

**Comment by amastaneh** [comment]
+1 whistle

**Comment by Santoshah** [comment]
+1 whistle

**Comment by zuck** [comment]
+1 whistle

**Comment by Szymod** [comment]
+1 whistle

**Comment by fdeleglise** [comment]
+1 whistle !

**Comment by stoiacs** [comment]
+1 whistle

**Comment by AndreNitze** [comment]
+1 whistle

**Comment by gabrielenosso** [comment]
+1 whistle

**Comment by ezeswci** [comment]
+1 for whistle

**Comment by nikkiroylance** [comment]
+1 Whistle

**Comment by joaquinmalo** [comment]
+1 Whistle

**Comment by RicardoCino** [comment]
+1

**Comment by Szymod** [comment]
+1 Whistle

**Comment by linc35** [comment]
+1 whistle

**Comment by davevari** [comment]
+1 whistle

**Comment by iragreen** [comment]
+1

**Comment by designedbytiki** [comment]
+1

**Comment by AlphaMAB** [comment]
+1 whistle

**Comment by weinde** [comment]
+1 whistle... or does it already exist?? O.o

**Comment by eannaboland** [comment]
+1 Whistle

**Comment by mikeAron** [comment]
+1 for whistle

**Comment by abartolo** [comment]
+1

**Comment by JoshuaCaputo** [comment]
+=1 for whistle

**Comment by MrLotU** [comment]
+1 for whistle

**Comment by knut2** [comment]
+1 whistle

**Comment by az264** [comment]
+1 whistle

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/whistle?style=solid
