### ISSUE TITLE
Icon request: icon-ocean-waves

### ISSUE THREAD

**Issue by rogerioalarcao** [FortAwesome/Font-Awesome#9840]
I need an icon of the waves . It will be used in the study areas of the sea , and coastal and ocean engineering.

![images](https://cloud.githubusercontent.com/assets/21351242/18113414/034c8014-6f06-11e6-904c-79f164eb7ccd.jpg)

**Comment by tagliala** [comment]
Duplicate of #7840, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
