### ISSUE TITLE
Icon Request: fa-africa

### ISSUE THREAD

**Issue by MingleAfrica** [FortAwesome/Font-Awesome#9843]
Hello,

I would like to request an icon character for "Africa". I have an image of the logo
below. I plan on using this icon to represent the African continent. So the key word here is Africa. 

This would be so useful for me.

Thank you.

![afrika icon](https://cloud.githubusercontent.com/assets/21360158/18126336/f6c3d66a-6f7a-11e6-95ee-a9565785f549.png)

**Comment by tagliala** [comment]
Sorry, I'm going to close this one.

Flags and country/continent silhouettes are out of scope at the moment

Ref: #3992
