### ISSUE TITLE
icon request: icon-moodle

### ISSUE THREAD

**Issue by ammarmerhbi** [FortAwesome/Font-Awesome#9844]
Hi
I would like to request an icon for Moodle, the most famous open LMS. I was surprised not seeing Moodle among Drupal and Joomla icons. 

Thank you

**Comment by tagliala** [comment]
Duplicate of #2167, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
