### ISSUE TITLE
Icon Request: fa-incloudio

### ISSUE THREAD

**Issue by gritchee** [FortAwesome/Font-Awesome#9846]
Hi Gave,

I would request a new font for my company Incloudio based on our brand icon, a citadel. It could also used as a misc icon for bullet point.

I was inspired by the design of the citadels of Vauban (https://en.wikipedia.org/wiki/S%C3%A9bastien_Le_Prestre_de_Vauban) and you could find an example here : https://www.incloud.io/img/favicon/favicon-192x192.png or a more complex one : https://www.incloud.io/media/NewIcon.png. Inside the citadel can be full and I could also provide the .ai file if needed.

If my request is accepted, I would 2 icons : fa-incloudio (with fa-citadel as an alias) and fa-incloudio-square.

Thanks,
Bertrand.

**Comment by aethior** [comment]
>Fin de l'aventure Incloudio https://incloud.io #Merci à tous les clients, les soutiens et les partenaires ! #ThisIstheEnd ([source](https://twitter.com/incloudio/status/861944199670898693))

`Incloud.io` was closed in 2017.

cc/ @tagliala
