### ISSUE TITLE
fa-clock is misaligned

### ISSUE THREAD

**Issue by vmalloc** [FortAwesome/Font-Awesome#9856]
I'm using FA 4.4.0, and this markup:

```html
      <p>
	<i class="fa fa-clock"></i> ...
      </p>
      <p>
	<i class="fa fa-hourglass-1"></i> ...
      </p>
      <p>
	<i class="fa fa-hourglass-3"></i> ...
      </p>

```

I'm getting this output:

<img width="59" alt="screen shot 2016-09-05 at 09 34 30" src="https://cloud.githubusercontent.com/assets/28710/18239164/000ca5ba-734c-11e6-82ba-d12a4b92e5c2.png">

Am I using something wrong or is it a bug?

**Comment by tagliala** [comment]
Icons have not the same width by design choice. Please use the `fa-fw` class helper for this use case

**Comment by vmalloc** [comment]
with `fa-fw` it's even worse:
```html
<p>
	<i class="fa fa-fw fa-clock"></i> ...
      </p>
      <p>
	<i class="fa fa-fw fa-hourglass-1"></i>...
      </p>
      <p>
	<i class="fa fa-fw fa-hourglass-3"></i> ...
      </p>
```

Now it looks like this:
<img width="73" alt="screen shot 2016-09-05 at 12 03 51" src="https://cloud.githubusercontent.com/assets/28710/18242821/d8ee53ce-7360-11e6-925c-bccccfb5a447.png">

**Comment by tagliala** [comment]
Cannot replicate. Please also note that `fa-clock` is wrong, it should be `fa-clock-o` (therefore the placeholder for a missing icon): https://jsfiddle.net/tagliala/4Lcpvhoo/8/

Please provide a jsfiddle showing the issue. You could also consider the [list feature](http://fontawesome.io/examples/#list)

**Comment by vmalloc** [comment]
My bad. I was using a component that included another icon inside, and the outer icon was indeed wrongfully `fa-clock`. Thanks and sorry for the trouble!

**Comment by tagliala** [comment]
no problem, glad you solved 👍
