### ISSUE TITLE
Icon Request: fa-scoop-it

### ISSUE THREAD

**Issue by chenox** [FortAwesome/Font-Awesome#9858]
![scoop-it](https://cloud.githubusercontent.com/assets/22001352/18242787/fd5789a8-734f-11e6-89c8-6934b303835d.png)

**Comment by aethior** [comment]
Duplicate of #1603. Please :+1: that request.

**Comment by ligne13** [comment]
+1 scoop it

**Comment by tagliala** [comment]
🔒
