### ISSUE TITLE
Icon Request: fa-ideal

### ISSUE THREAD

**Issue by Scarmaster** [FortAwesome/Font-Awesome#9859]
iDeal is a widely used payment method in the Netherlands, and therefore pretty popular. Big sites use it already. I would love to see this icon in the font!

**Comment by tagliala** [comment]
Duplicate of #4330, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
