### ISSUE TITLE
Icon Request: Fa-Angular, Fa-iOS

### ISSUE THREAD

**Issue by cinghaman** [FortAwesome/Font-Awesome#9871]
Request for adding Icons for common developer languages
Like
Angular
React
JS
iOS
PHP
.NET
Ruby/Rails
Thanks

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
