### ISSUE TITLE
Icon Request: fa-sandwich

### ISSUE THREAD

**Issue by sonicctba** [FortAwesome/Font-Awesome#9874]
Is it possible to create a sandwich icon? Thanks =)

**Comment by tagliala** [comment]
Ref: #1895

**Comment by Crissov** [comment]
Will probably become &#x1f96a; [U+1F96A](http://unicode.org/emoji/charts-beta/emoji-candidates.html#1f96a) in Unicode 10.0 #222

**Comment by sensibleworld** [comment]
https://fontawesome.com/icons/sandwich?style=solid
