### ISSUE TITLE
Icon Request: icon-recurring-charge

### ISSUE THREAD

**Issue by voveson** [FortAwesome/Font-Awesome#9876]
It would be great to have an icon to represent recurring charges.  Subscription services are becoming more and more popular as a business model.

Example:
![subscription](https://cloud.githubusercontent.com/assets/6799654/18287005/98dfc146-7432-11e6-88ba-e37239dbda5d.png)

**Comment by tagliala** [comment]
Since this is currency dependent and we have a lot of currencies, please consider the [stacking feature](http://fontawesome.io/examples/#stacked)

https://jsfiddle.net/tagliala/4Lcpvhoo/10/

I'm closing here for the moment
