### ISSUE TITLE
[feature request] Use npm / bower instead of component (deprecated)

### ISSUE THREAD

**Issue by rognoni** [FortAwesome/Font-Awesome#9877]
For my new project I was thinking to include as a `component` but the project is **not maintained** anymore [issue #639](https://github.com/componentjs/component/issues/639)

Can you use:
- `npm` [Publishing npm packages](https://docs.npmjs.com/getting-started/publishing-npm-packages)
- `bower` [Register](https://bower.io/docs/creating-packages/#register)
- or other...

**Comment by tagliala** [comment]
npm (unofficial): https://www.npmjs.com/package/font-awesome
bower: fontawesome

**Comment by tagliala** [comment]
Official NPM packages have been released with Font Awesome 5
