### ISSUE TITLE
Icon request: icon-votocrat

### ISSUE THREAD

**Issue by sambariraghu** [FortAwesome/Font-Awesome#9879]
![votocrat-big](https://cloud.githubusercontent.com/assets/22028639/18306137/19e87fe6-7508-11e6-87c6-f41700cc9189.png)

**Comment by aethior** [comment]
The domain ([link](https://www.votocrat.com/)) is currently down and the [facebook account](https://es-la.facebook.com/votocratpoll/) is inactive since 2017.

cc/ @tagliala
