### ISSUE TITLE
Icon request: money box, fountain pen, paper with pen

### ISSUE THREAD

**Issue by andrii-trush-ssa** [FortAwesome/Font-Awesome#9880]
Icon request: 
1. money box (e.g. a pig with number or currency)
2. fountain pen (e.g. http://free-icon-rainbow.com/i/icon_00079/icon_000790_256.png)
3. paper with lines and pen (e.g. http://f2.s.qip.ru/1q1ISWWt.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
