### ISSUE TITLE
fa-mobile is much smaller than other icons

### ISSUE THREAD

**Issue by xcatliu** [FortAwesome/Font-Awesome#9883]
![image](https://cloud.githubusercontent.com/assets/5453359/18339314/6ebfb31c-75d1-11e6-9da0-afc0ac11a7eb.png)

**Comment by tagliala** [comment]
Duplicate of #928 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
