### ISSUE TITLE
Icon Request: fa-home-o 

### ISSUE THREAD

**Issue by tierrarara** [FortAwesome/Font-Awesome#9888]
will be greate get home icon like 
fa-start, fa-start-o

sorry about the next words, but like IE home icon :P

thanks for your attention

**Comment by tagliala** [comment]
Duplicate of #2210, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
