### ISSUE TITLE
Icon Request: fa-potplant-o

### ISSUE THREAD

**Issue by Francorider** [FortAwesome/Font-Awesome#9889]
Basic icon of a plant inside of a pot.

Client has a landscaping business, would be great to have an icon to signify plant pots.

Found a few already-existing potplant icons, but they are either copyrighted or a mess to integrate.

Find attached an example.
![plant-with-two-leaves-on-a-pot-side-view_318-47257](https://cloud.githubusercontent.com/assets/21241670/18360698/4d970b8a-75ff-11e6-810e-5d64c38fe7c9.jpg)

**Comment by tagliala** [comment]
I'm going to consider this a dupliacate of #3810, please +1 that request

closing here
