### ISSUE TITLE
Icon Request: fa-core

### ISSUE THREAD

**Issue by mcpe-yossi1114** [FortAwesome/Font-Awesome#9893]
Please add CPU core FontAwesome icon.
Thanks!

**Comment by mcpe-yossi1114** [comment]
I want to suggest this:
[https://imgur.com/gallery/DbzMHn6](url)

**Comment by tagliala** [comment]
Duplicate of #1840, planned for 5.0.0, but please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
