### ISSUE TITLE
Icon request: fa-taco

### ISSUE THREAD

**Issue by maskott** [FortAwesome/Font-Awesome#9896]
We would use this in hundreds if not thousands of placements in our taco-themed application.

Perhaps a simplified version of something like these:

![taco_318-109301](https://cloud.githubusercontent.com/assets/4070380/18390816/b8bb3fc4-7679-11e6-975d-d534768a8bb1.jpg)
![68929-200](https://cloud.githubusercontent.com/assets/4070380/18390818/b8bebc08-7679-11e6-85b9-4ca18953dd84.png)
![18755-200](https://cloud.githubusercontent.com/assets/4070380/18390817/b8bbcae8-7679-11e6-9384-b0149a0a4716.png)

**Comment by VolitionDevelopment** [comment]
Only a savage would turn down more tacos. This needs to happen.

**Comment by tagliala** [comment]
🌮

**Comment by rockerest** [comment]
> our taco-themed application

Doin' the Lord's work.

+1, only because Tacos.

**Comment by Crissov** [comment]
* [🌮 U+1F32E Taco](http://emojipedia.org/taco/)

## Related Unicode emoji
* [🌭 U+1F32D Hotdog](http://emojipedia.org/hotdog/)
* [🌯 U+1F32F Burrito](http://emojipedia.org/burrito/) (lahmaçun, tortilla wrap)
* [🍔 U+1F354 Hamburger](http://emojipedia.org/hamburger/) (cheeseburger)
* [🍕 U+1F355 Pizza Slice](http://emojipedia.org/pizza-slice/)
* [🍞 U+1F35E Bread](http://emojipedia.org/bread/)
* [🥐 U+1F950 Croissant](http://emojipedia.org/croissant/)
* [🥖 U+1F956 Baguette Bread](http://emojipedia.org/baguette-bread/)
* [🥙 U+1F959 Stuffed Flatbread](http://emojipedia.org/stuffed-flatbread/) (döner kebab, falafel, gyros pita, shawarma)

**Comment by sensibleworld** [comment]
I'm getting hungry: 
https://fontawesome.com/icons/taco?style=solid
