### ISSUE TITLE
Icon Request: icon-cinema-camera

### ISSUE THREAD

**Issue by evanthorpe** [FortAwesome/Font-Awesome#990]
Hi, I'm loving this font set so far, thanks so much for putting it together! I'd like to make a request for two icons in particular:
1. Traditional video camera: right now you have a digital camera, an old school film camera, a piece of film reel and the "facetime" icon. I'm looking to see if you could make something that represents a traditional film video camera, much like the one seen here: http://openclipart.org/image/250px/svg_to_png/170978/camera_icon_estilizado_nofeet.png

Thanks so much!

**Comment by sensibleworld** [comment]
We have a new movie camera icon in 5.11: https://fontawesome.com/icons/camera-movie?style=solid
