### ISSUE TITLE
How can I disable the font-awesome POST to the stats server?

### ISSUE THREAD

**Issue by erichonkanen** [FortAwesome/Font-Awesome#9902]
Hello,

I recently noticed that font-awesome latest version is frequently POSTing stats from my app and I want to disable this network request. How can I use font-awesome w/o enabling this stats healthcheck behavior?

`POST Request URL:https://cdn.fontawesome.com/api/embed-code-stats`

**Comment by tagliala** [comment]
Maybe Edit Options in your embed code and disable "Icon stats reporting"

**Comment by erichonkanen** [comment]
@tagliala so I have to pay to disable it then? looks like only options are paid accounts

**Comment by tagliala** [comment]
@erichonkanen doesn't look like an option only for premium accounts. I don't have a premium account (afaik) and I can disable it.
