### ISSUE TITLE
Request for a condensed version of FA

### ISSUE THREAD

**Issue by migf** [FortAwesome/Font-Awesome#9910]
For producing web pages to be displayed in 3D TV in stereo mode I need a condensed version of FA. As the symbols are in SGV I think it will be possible to apply a 50% horizontal scale to them but I do not know how to do that. I tried to do this by applying CSS rules but I did not succeed.
An example of a web page that has a 3D TV stereo version can be found here:
http://www.atractor.pt/mat/poliedros/index_mdmo-_en.html
and the stereo version is here:
http://www.atractor.pt/mat/poliedros/index_mdst-_en.html
To see the stereo version in a normal display a 1920x1080 screen and maximized browser window should be used.
Thanks in advance for any help,
Miguel Filgueiras

**Comment by sensibleworld** [comment]
Hi there! Apologies for missing this issue. I'm going to close it because the links are no longer valid. If you still have the need, feel free to reopen it! Thanks.
