### ISSUE TITLE
Icon Request: fa-greet

### ISSUE THREAD

**Issue by veigas** [FortAwesome/Font-Awesome#9915]
Hello Respected

It would be better if we get a fa-icon for greet, as it will help lot for developers to quicker their code.

regards.
![namaste-logo2-890x420](https://cloud.githubusercontent.com/assets/20840557/18517233/4453d968-7ab9-11e6-9367-ca76a7e99f15.png)

**Comment by veigas** [comment]
well for my knowledge i haven't seen a brand, but it is not a emoji .

thank you for reply.

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/hands-praying?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
