### ISSUE TITLE
Icon request: fa-friends

### ISSUE THREAD

**Issue by akashpinnaka** [FortAwesome/Font-Awesome#9916]
Hello

This is to request you for the icon which refers to group of friends. ex: facebook friends button.

Thanks
Akash Pinnaka

**PS: Thanks for**_t_ **awsome icons**

**Comment by tagliala** [comment]
Duplicate of #2883 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here

**Comment by akashpinnaka** [comment]
Thanks for pointing this. :) I added the reaction
