### ISSUE TITLE
Icon Request: fa-rectangle/fa-rectangle-o

### ISSUE THREAD

**Issue by danvick** [FortAwesome/Font-Awesome#9917]
We have other shapes like `circle` and `square`. How about plain ole `rectangle`? 

Would like to show game cards like red cards, yellow cards, green cards etc. I've tried using `square` but it doesn't look nice.

**Comment by tagliala** [comment]
Duplicate of #3639, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
