### ISSUE TITLE
Icon request: fa-cyanogen-mod

### ISSUE THREAD

**Issue by brainscript** [FortAwesome/Font-Awesome#9920]
[CyanogenMod](http://www.cyanogenmod.org/) is one of the most popular Android ROMs and I think it deserves it's own icon.

![](https://upload.wikimedia.org/wikipedia/en/1/10/CyanogenMod_logo.svg)

The icon should only represent the robot's face.

**Comment by auge8472** [comment]
Should this issue stay open, regardless the project is abandoned and has a successor named [LineageOS](https://en.wikipedia.org/wiki/LineageOS) (also with a new logo)?

**Comment by tagliala** [comment]
shutting down this request.

Feel free to open a new one for lineage-os
