### ISSUE TITLE
icon request : fa-skin or fa-clothing

### ISSUE THREAD

**Issue by joybbs** [FortAwesome/Font-Awesome#9922]
![1](https://cloud.githubusercontent.com/assets/7369791/18606446/ebe1af7c-7ce2-11e6-9685-566c13e1a16a.jpg)

**Comment by tagliala** [comment]
Duplicate of #715 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
