### ISSUE TITLE
Bug: "Need IE7 Support?" on the fontawesome site shows same block as "Internet Explorer 8 and @font-face"

### ISSUE THREAD

**Issue by Martinspire** [FortAwesome/Font-Awesome#9923]
So on [this "getting started" page](http://fontawesome.io/get-started/) of the Font Awesome site (at the bottom, under "more information") it shows the same text block on the IE7 as the IE8 part about what you need to do for IE8. So basically help for IE7 support isn't listed.

Just noticed this and while i don't need it personally, i think there was something else there in the past. However i'm not sure what so i can't really say what to link to as an alternative. I see something with `zoom:expression` named on some alternatives ([like this one](https://gist.github.com/dorajistyle/7461853)) but i'm not sure where you are going for.

**Comment by tagliala** [comment]
Thanks for reporting this.

https://github.com/FortAwesome/Font-Awesome/commit/ce194fb6d8961ba9953685557dbf23e810dcfbf7#diff-d1d55fda1867da1b14ead5829f1c2048L167

This commit messed up with that section. I cannot revert it but I can definitely fix it :)

**Comment by tagliala** [comment]
Thanks, it will be live when docs will be rebuild
