### ISSUE TITLE
Icon Request: fa-imac

### ISSUE THREAD

**Issue by zeeshaanrehmat** [FortAwesome/Font-Awesome#9933]
Hi FontAwesome!

My name is Zeeshaan, I need iMac LCD icon for my bootstrap theme demo...
![imac](https://cloud.githubusercontent.com/assets/22295066/18631927/30996748-7e8e-11e6-87a3-d75b9bf20401.png)

**Comment by tagliala** [comment]
Maybe http://fontawesome.io/icon/desktop/ does the job

**Comment by ryankane** [comment]
You can stack icons to produce the following effect:

![imac](https://cloud.githubusercontent.com/assets/1094151/19267940/900aa3de-8f7f-11e6-86da-40cb7fbd4960.png)

```html
<span class="fa-stack fa-1x">
  <i class="fa fa-desktop fa-stack-2x"></i>
  <i class="fa fa-apple fa-stack-1x"></i>
</span>
<span class="fa-stack fa-2x">
  <i class="fa fa-desktop fa-stack-2x"></i>
  <i class="fa fa-apple fa-stack-1x"></i>
</span>
<span class="fa-stack fa-3x">
  <i class="fa fa-desktop fa-stack-2x"></i>
  <i class="fa fa-apple fa-stack-1x"></i>
</span>
<span class="fa-stack fa-4x">
  <i class="fa fa-desktop fa-stack-2x"></i>
  <i class="fa fa-apple fa-stack-1x"></i>
</span>
<span class="fa-stack fa-5x">
  <i class="fa fa-desktop fa-stack-2x"></i>
  <i class="fa fa-apple fa-stack-1x"></i>
</span>
```

```css
.fa-stack {
  margin-right: 0.25em;
}

.fa-apple {
  left: 0.09375em;
  font-size: 0.75em;
  line-height: 1.67em;
}
```

Here is a [link](https://jsfiddle.net/MrPolywhirl/4cthz9sL/) to a working demo.

**Comment by tagliala** [comment]
Hi!

we may have some new icon that fit this use case. You may try to search at https://fontawesome.com/search?s=solid%2Cbrands

https://fontawesome.com/icons/desktop?s=solid
https://fontawesome.com/icons/display?s=solid

I'm closing here for inactivity, but feel free to fix the opening request or fill out a [new icon request template](https://github.com/FortAwesome/Font-Awesome/issues/new?title=Icon%20request:%20icon-name&template=icon-request.md)
