### ISSUE TITLE
Icon Requset - fa-bottle

### ISSUE THREAD

**Issue by zoharyosef** [FortAwesome/Font-Awesome#9935]
Hi Font Awesome, your'e awesome!
I could really use a bottle icon, it can be just standing or pouring...
Thanks!
[Example](http://www.clipartkid.com/images/86/white-wine-bottle-29-99-white-wine-bottle-4-OEXED7-clipart.jpg)

**Comment by tagliala** [comment]
Duplicate of #1762, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
