### ISSUE TITLE
Icon Request: icon-delivery

### ISSUE THREAD

**Issue by muzayun** [FortAwesome/Font-Awesome#9936]
I need a delivery icon to show on a website. Really appreciate the help... Thank you!

**Comment by muzayun** [comment]
Thank you @tagliala for respoding - something like the one attached: 
![image](https://cloud.githubusercontent.com/assets/22321869/18814139/c50a7116-832e-11e6-9639-f65725ba0dfa.png)

**Comment by aethior** [comment]
Related: #6038

**Comment by sensibleworld** [comment]
There are a few options for this in the Logistics category in 5.0.7: https://fontawesome.com/icons?d=gallery&c=logistics
