### ISSUE TITLE
Icon Request: fa-typekit

### ISSUE THREAD

**Issue by adrianlbs** [FortAwesome/Font-Awesome#9939]
Request for an Adobe Typekit Icon.
Example: http://2016.typographics.com/assets/uploads/Adobe_Typekit-logo.svg
Thanks!

**Comment by tagliala** [comment]
Sorry, closing this and labeling as cantfix

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5140-to-5150
