### ISSUE TITLE
Icon request: slideshow

### ISSUE THREAD

**Issue by hejmsdz** [FortAwesome/Font-Awesome#994]
Something similar to:
![slideshow-icon](https://cloud.githubusercontent.com/assets/7750325/3137117/b289497e-e84c-11e3-9a8b-381be8d63a82.png)
![download](https://cloud.githubusercontent.com/assets/7750325/3137124/d53e3a24-e84c-11e3-9cb8-0690250cbc75.jpg)

**Comment by AlexVanDamn** [comment]
+1

**Comment by 3Nex** [comment]
+1 
One more example: http://png-1.findicons.com/files/icons/1598/di_black_folder/256/presentation.png

**Comment by AlexVanDamn** [comment]
![slideshow](https://cloud.githubusercontent.com/assets/2526545/6498928/19fb7cba-c2fb-11e4-9db8-c80124312ef6.png)

**Comment by kranthilakum** [comment]
+1

**Comment by gagetaylor** [comment]
+1

**Comment by thetron** [comment]
+1

**Comment by WispProxy** [comment]
+1

**Comment by doc-cb** [comment]
+1

**Comment by igorlino** [comment]
+1

**Comment by TabeebOsama** [comment]
+1

**Comment by HunterJoe** [comment]
+1

**Comment by bluemanos** [comment]
+1

**Comment by jwegner** [comment]
+1

**Comment by hnmcc** [comment]
+1

**Comment by newgrounds** [comment]
+1

Maybe something like this one:
![137-presentation 2x](https://cloud.githubusercontent.com/assets/667311/9974206/2662fb7e-5e53-11e5-8677-b66415f050a7.png)

**Comment by We-St** [comment]
+1

**Comment by jesselpalmer** [comment]
+1

**Comment by integrasistemas** [comment]
+1

**Comment by jackycute** [comment]
+1

**Comment by Crissov** [comment]
Related standard icon, confusingly named “strobe”, but its description reads “display a succession of still pictures on a screen”:

[![IEC 60417-5318](https://www.iso.org/iobp/graphics/grs/ISO263473_200.png)](https://gnbs.isolutions.iso.org/obp/ui#iec:grs:60417:0:5318)

**Comment by matthiku** [comment]
+

**Comment by ttseng** [comment]
+1

**Comment by madkiss** [comment]
+1

**Comment by isiryder** [comment]
+1

**Comment by git-emil** [comment]
+1

**Comment by chrisma** [comment]
+1

**Comment by sebastian-raubach** [comment]
+1

**Comment by kasparsklavins** [comment]
I like the newgrounds suggestion.

**Comment by balping** [comment]
+1

**Comment by luishmelo** [comment]
+1

**Comment by sliceofbytes** [comment]
+1

**Comment by ErickChacon** [comment]
+1

**Comment by bitstorm** [comment]
+1

**Comment by garretwilson** [comment]
+1

Note that this seems to be a duplicate of #866.

**Comment by sensibleworld** [comment]
<img width="1047" alt="Screen Shot 2020-11-04 at 10 07 00 AM" src="https://user-images.githubusercontent.com/529604/98128115-7d80aa80-1e85-11eb-9dbd-0092160ca24c.png">

We have a "presentation-screen" icon, along with some podium icons. Do these satisfy this request?
