### ISSUE TITLE
Icon Request: files-text-o

### ISSUE THREAD

**Issue by andyrue** [FortAwesome/Font-Awesome#9940]
Since there is a [file-o](http://fontawesome.io/icon/file-o/) and a [files-o](http://fontawesome.io/icon/files-o/) to match, it would be nice if there was a files-text-o to go along with the existing [file-text-o](http://fontawesome.io/icon/file-text-o/) icon.

**Comment by aethior** [comment]
`files-lines` according with the current icon names.

@tagliala `files (category)` label for this request?

**Comment by tagliala** [comment]
I think this request has been fulfilled by https://fontawesome.com/icons/file-lines?s=solid in different styles, introduced in FA5

Closing here, feel free to comment if I'm wrong
