### ISSUE TITLE
universal-access icon not working

### ISSUE THREAD

**Issue by debpea** [FortAwesome/Font-Awesome#9942]
Hey - I'm trying to use this icon on my site - everything else works, but even when I copy and paste the code for this icon, it doesn't appear.
Any ideas for why this could be happening?
Using a qode theme on wordpress, all other icons working fine.
Thanks

**Comment by tagliala** [comment]
Please make sure you are using (only) the latest version of Font Awesome.

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#some-icons-dont-show-up

Pay particular attention to point 5
