### ISSUE TITLE
Icon Request: fa-arduino

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9945]
Arduino needs to be added! :)

https://i.ytimg.com/vi/wDgjdXtrnzM/maxresdefault.jpg

**Comment by tagliala** [comment]
Duplicate of #2530, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
