### ISSUE TITLE
Icon Request: fa-raspberry-pi

### ISSUE THREAD

**Issue by OnlyDrey** [FortAwesome/Font-Awesome#9946]
We need a Raspberry Pi icon as well! :)

https://rasplapse.files.wordpress.com/2012/06/pi_white.jpg

**Comment by tagliala** [comment]
Duplicate of #2944, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
