### ISSUE TITLE
Icon request: icon-crown

### ISSUE THREAD

**Issue by Aloqsin** [FortAwesome/Font-Awesome#9952]
Hello,

It could be useful to have a crown icon available. For example:

![1474594033_crown](https://cloud.githubusercontent.com/assets/13577940/18766275/b74b4c88-8119-11e6-9d16-9c8d3bef63b6.png)

Cheers.

**Comment by tagliala** [comment]
Duplicate of #486 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
