### ISSUE TITLE
Icon Request : BPMN Font / Icons

### ISSUE THREAD

**Issue by hnandarusdy** [FortAwesome/Font-Awesome#9953]
It would be really good if we could have a BPMN font also. 

The icons are available here https://pbs.twimg.com/media/CBhzKt4W8AEkN9N.png.

**Comment by hnandarusdy** [comment]
Let me know if your need further explanation for each icon. I am happy to explain or name it.

**Comment by tagliala** [comment]
How many icons are you requesting?

I think this request doesn't meet our contributing guidelines: https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

> Please do not request comprehensive sets of icons related to a very specific field.
> Please make requests for single icons, unless you are requesting a couple of strictly related icons (e.g., thumbs-up/thumbs-down).
