### ISSUE TITLE
Icon Request: fa-electrical..

### ISSUE THREAD

**Issue by 101da** [FortAwesome/Font-Awesome#9957]
How about some icons for regulations in the electric industry:
https://commons.wikimedia.org/wiki/File:Protective_earthing.svg?uselang=de
https://en.wikipedia.org/wiki/ENEC_Mark
https://www.vde.com/en/Institute/Portfolio/Certification/Pages/VDE_Certification_Marks.aspx

Can you suggest me a rather good and free program for fonts and similar things?
..then I'd build a first sketch..

**Comment by 101da** [comment]
name suggestions:
fa-electrical-pe
fa-electrical-enec or fa-enec
fa-electrical-vde or fa-vde

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by 101da** [comment]
Sorry, my fault too specific ($2).
Thanks anyways for your great work!
