### ISSUE TITLE
Icon Request: icon-Labtests

### ISSUE THREAD

**Issue by galiavni** [FortAwesome/Font-Awesome#9959]
I am writing a web application for medical clinic management.
I need this icon to represent a list of laboratory test , it is usualy represented by the letter Lab.

Thank you 
Gali

**Comment by tagliala** [comment]
Do http://fontawesome.io/icon/flask/ or #6825 fit the use case?

**Comment by sensibleworld** [comment]
How about:

- https://fontawesome.com/icons/vials?style=solid
- https://fontawesome.com/icons/vial?style=solid
