### ISSUE TITLE
Can't use FontAwesome as a select option in Safari, Chrome, Firefox (OSX / Linux / Android)

### ISSUE THREAD

**Issue by djonatanb** [FortAwesome/Font-Awesome#996]
# STOP! ✋ 
## Read this comment: :point_right:  https://github.com/FortAwesome/Font-Awesome/issues/996#issuecomment-322332662  :point_left:

---

I would like to be able to list some icons using a select element.
I tried by adding a <i> inside the option like this:

``` html
<select name='example'> 
  <option value='1'>
    <i class='icon-phone-mobile'> </i>
  </option>
</select>
```

But it doesn't display anything. Is it possible to do and I'm trying the wrong approach or it's not possible?

**Comment by wolfram77** [comment]
the solution worked. i tried:
```html
<select class="fa">
<option value="0" selected> &#xf201; Chart</option>
...
</select>
```
which also worked.

**Comment by bsohlml** [comment]
This does not work for me on the Mac (10.10, Chrome or Safari). The icons in the dropdown <option> list show exactly as in @tagliala screenshot above. Once an item is select, the correct icon does appear in the <select> itself. Has anyone found a solution/workaround for this? Thanks!

**Comment by davidpatters0n** [comment]
any news on the above ^^ ? Thank you

**Comment by Kae2312** [comment]
Has anyone found a solution? Thanks!

**Comment by shaununderwood** [comment]
Seems this is still in error; the error icon shows in the dropdown but thankfully renders correct in the selection box. I'm not in favour to use a 3rd party component to overcome this simple issue.

**Comment by tagliala** [comment]
@shaununderwood this issue does not depend on Font Awesome:

http://jsfiddle.net/tagliala/9qg96Lna/ (no fontawesome here)

Maybe webkit based browsers on OSX have some issues with PUA in `select` and `option` tags. Font Awesome uses PUA by design. You can customize the font and bring glyphs outside of the PUA if you need to address this issue

New browser test on http://jsfiddle.net/NyL7d/:
:white_check_mark: Chrome 46 / Win 10
:white_check_mark: Firefox 42 / Win 10
:white_check_mark: IE 11 / Win 10
:white_check_mark: MS Edge 13 / Win 10
:white_check_mark: Firefox 42 / OSX 10.11.1
:x: Chrome 46 / OSX 10.11.1
:x: Safari 9.0.1 / OSX 10.11.1

**Comment by shaununderwood** [comment]
I've raised the issue here https://code.google.com/p/chromium/issues/detail?id=568116 i hope its the right place to do that. I'm sure we'll find out.

**Comment by shaununderwood** [comment]
I've raised the issue here https://code.google.com/p/chromium/issues/detail?id=568116 i hope its the right place to do that. I'm sure we'll find out.

**Comment by tagliala** [comment]
@shaununderwood thanks!

let's wait for an answer

**Comment by tagliala** [comment]
Answer:

> Popups on OSX and Android don't support WebFonts now.

**Comment by shaununderwood** [comment]
> Ah, not WebFonts.  ... font-family is not supported.

Well isn't that just dandy.

**Comment by joeshelton1020** [comment]
Found a fairly organic workaround. A multi-select will display the font icons properly across all browsers. A little Javascript would allow you to restrict a multi-select to one value, if need be.

**Comment by Jngai** [comment]
@joeshelton1020 can you post that solution?

**Comment by joeshelton1020** [comment]
HTML would be

```
<select multiple name="icon" size="8" style="font-family: FontAwesome, sans-serif;">
<option value="fa-500px">&#xf26e&nbsp;&nbsp;500px</option>
<option value="fa-adjust">&#xf042&nbsp;&nbsp;Adjust</option>
<option value="fa-adn">&#xf170&nbsp;&nbsp;Adn</option>
<option value="fa-align-center">&#xf037&nbsp;&nbsp;Align-center</option>
<option value="fa-align-justify">&#xf039&nbsp;&nbsp;Align-justify</option>
<option value="fa-align-left">&#xf036&nbsp;&nbsp;Align-left</option>
<option value="fa-align-right">&#xf038&nbsp;&nbsp;Align-right</option>
<option value="fa-amazon">&#xf270&nbsp;&nbsp;Amazon</option>
<option value="fa-ambulance">&#xf0f9&nbsp;&nbsp;Ambulance</option>
<option value="fa-anchor">&#xf13d&nbsp;&nbsp;Anchor</option>
<option value="fa-android">&#xf17b&nbsp;&nbsp;Android</option>
<option value="fa-angellist">&#xf209&nbsp;&nbsp;Angellist</option>
...
</select>
```

**Comment by ybrodsky** [comment]
@joeshelton1020 Solution works like a charm

http://plnkr.co/edit/lTAFed3IDZBmzL9xulmT?p=preview

**Comment by joeshelton1020** [comment]
@ybrodsky The code you posted does NOT work in certain browsers. The select needs the "multiple" attribute.

**Comment by ybrodsky** [comment]
Updated

**Comment by Jngai** [comment]
I couldn't use the html version because I was incorporating this into a rails app. I had to do it the rails way.

My select looks like this. I am using select2 with font awesome and on top with rails form_for select/options for select helpers. 
```
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <div>
          <%= f.label :icon %>
          <%= f.select(:icon, options_for_select([["Adjust", "fa fa-adjust", {"data-icon" => "fa-adjust"}],
              ["Camera", "fa fa-camera", {"data-icon" => "fa-camera" }], ["Anchor", "fa fa-anchor", {"data-icon" => "fa-anchor" }], ["Archive", "fa fa-archive", {'data-icon'=> "fa-archive" }], ["Asterisk", "fa fa-asterisk", {'data-icon' => "fa-asterisk" }], ["Adn", "fa fa-adn", {'data-icon' => "fa-adn" }],["Bell", "fa fa-bell", {'data-icon' => "fa-bell" }], ["Bicycle", "fa fa-bicycle", {'data-icon' => "fa-bicycle" }]]), {},
              {:style => "font-family:'FontAwesome', Arial;", :class => 'js-example-basic-single'}) %>
        </div>
      </div>
    </div>
  </div>
```

Here is my coffee script file to set the format of the select2 box

```
format = (icon) ->
  originalOption = icon.element
  '<i class="fa ' + $(originalOption).data('icon') + '"></i> ' + icon.text

$(document).ready ->
  $('.js-example-basic-single').select2
    width: '100%'
    formatResult: format
```

This also made the dropdown box render the icons perfectly.

**Comment by PeterShaggyNoble** [comment]
@joeshelton1020 & @ybrodsky, you're missing the semi-colons to close out the entities; you might encounter problems in some browsers without them.

Also, for people using this method, please bear in mind that it breaks the ability to select an option using your keyboard.

**Comment by dantheman999301** [comment]
In case anyone else is having this issue, we found that if you add some border style it can actually fix the issue.

http://jsfiddle.net/6Lquvcr8/

![image](https://cloud.githubusercontent.com/assets/9741849/15393746/e2394ce4-1dc6-11e6-9715-5b3327ac20e2.png)

When expanded the icons are there.

**Comment by tagliala** [comment]
> When expanded the icons are there.

Not there. OSX 10.11.4, Chrome 50

![image](https://cloud.githubusercontent.com/assets/556268/15393920/2ecc1574-1dd0-11e6-8ad6-2d1ad6bf316b.png)

![screen shot 2016-05-19 at 14 43 13](https://cloud.githubusercontent.com/assets/556268/15393911/2363a76a-1dd0-11e6-85df-24d36949428d.png)

![image](https://cloud.githubusercontent.com/assets/556268/15393928/377fdcbe-1dd0-11e6-8179-421671efd5f6.png)

**Comment by dantheman999301** [comment]
How bizarre. Looks like this on our Mac.

![image](https://cloud.githubusercontent.com/assets/9741849/15395264/e9cc7104-1dce-11e6-962b-e5eea4f60a08.png)

And our OS and browser versions

![image](https://cloud.githubusercontent.com/assets/9741849/15395279/fa27e722-1dce-11e6-9d18-e8ddf762bbd2.png)

![image](https://cloud.githubusercontent.com/assets/9741849/15395289/059a20c0-1dcf-11e6-8cba-435f48e7b492.png)

**Comment by tagliala** [comment]
Maybe this is some retina-stuff involved.

It doesn't work on my non-retina MacbBook Air mid '13

**Comment by petogriac** [comment]
I am struggling with the same issue. As mentioned above Chrome and Safari on Mac doesnt show the dropdown menu with custom icons. The workaround I ended up using at the end is the bootstrap dropdown (like this one: http://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp) and then you are able to add custom icons for the <li> tags.

**Comment by ankitgarg306** [comment]
See this link have the solution:-
http://ankithackingtips.blogspot.in/2017/01/font-awsome-in-dropdown.html

**Comment by tagliala** [comment]
@ankitgarg306 unfortunately that solution is not cross platform. Please take a look at: https://bugs.chromium.org/p/chromium/issues/detail?id=568116

**Comment by Syirrus** [comment]
Yeah, I'm having the same problem with a Cordova app and Chrome on Mac.

**Comment by tagliala** [comment]
https://code.google.com/p/chromium/issues/detail?id=568116

> Popups on OSX and Android don't support WebFonts now.

🔒
