### ISSUE TITLE
Icon request: icon-section

### ISSUE THREAD

**Issue by BlueBockser** [FortAwesome/Font-Awesome#9961]
Please create an icon for the [section sign](https://en.wikipedia.org/wiki/Section_sign). I could not find anything like it and the workaround of actually using "§" is not working too well...
The section icon would be very useful for representing an impressum.

**Comment by tagliala** [comment]
Duplicate of #1706 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
