### ISSUE TITLE
Icon Request:

### ISSUE THREAD

**Issue by rakibulkarim** [FortAwesome/Font-Awesome#9963]
Icon request: icon-property, Icon request: icon-Community, Icon request: icon-job, Icon request: icon-electronic appliances, Icon request: icon-electronic gadgets, Icon request: icon-pets,  Icon request: icon-bike,

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
