### ISSUE TITLE
customer & supplier icons

### ISSUE THREAD

**Issue by maxcuttins** [FortAwesome/Font-Awesome#9966]
I think these are very usefull Icons.

Maybe something like this for customer:
![person_with_shopping_cart-512](https://cloud.githubusercontent.com/assets/13466200/18848446/b4a8e7b6-842e-11e6-8e11-eef7e0179f38.png)

And something like this for supplier:
![supplier](https://cloud.githubusercontent.com/assets/13466200/18848447/b4adc9a2-842e-11e6-89e7-c25fc29a857e.png)

But of course style is up to you

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).

**Comment by ajcastro** [comment]
I like the supplier icon. @maxcuttins, Can you give me please a svg file of that icon? 
Tip: I believe you can create your own font icons online. Try http://fontastic.me/ and http://fontello.com/.
