### ISSUE TITLE
Icon Request: fa-teamspeak3 and fa-discord

### ISSUE THREAD

**Issue by Natedanp** [FortAwesome/Font-Awesome#9967]
Hey, I was looking for the TeamSpeak 3 and Discord icon but was not able to find them, but I did find an icon for applications like Slack and Skype, which are very similar to Discord and TS3. I was just wondering if there was anyway you guys could add these two, these would be useful to many Websites who are trying to advertise ways to join their community. Thanks in advance

Teamspeak:
![ts](https://cloud.githubusercontent.com/assets/5360896/18861842/c8ac1246-844d-11e6-897c-26615330796d.png)

Discord:
![discord](https://cloud.githubusercontent.com/assets/5360896/18861852/d3a39520-844d-11e6-8a76-2b94101b9453.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
