### ISSUE TITLE
Button size issue with bootstrap v4 input-group

### ISSUE THREAD

**Issue by natcohen** [FortAwesome/Font-Awesome#9968]
It seems that the size of the grouped button (with an icon) is too small compared to the input... The following code:

```
<div class="input-group">
  <input type="text" placeholder="Recherche" class="form-control"/>
    <span class="input-group-btn">
      <button type="submit" class="btn btn-outline-success"><i class="fa fa-search fa-fw"></i></button\
    </span>
</div>
```

Gives the following:
![input-group](https://cloud.githubusercontent.com/assets/7813574/18879371/4f08a8c8-84d4-11e6-953e-f1cedb8b15c9.jpg)

PS I've opened a [bootstrap issue](https://github.com/twbs/bootstrap/issues/20750) but was closed (bootstrap doesn't support third party libraries/icons)

**Comment by tagliala** [comment]
Browsers affected? OS?

This fiddle https://jsfiddle.net/tagliala/70stfjq9/2/ works for Chrome 53 / Firefox 49 on Windows 10, but it doesn't work on IE11/Edge

https://jsfiddle.net/tagliala/70stfjq9/4 this one has the same issues, but Font Awesome is not involved

**Comment by tagliala** [comment]
http://v4-alpha.getbootstrap.com/components/input-group/

![image](https://cloud.githubusercontent.com/assets/556268/18906928/d9bcaef2-8569-11e6-8f09-8230fc02ab15.png)

Closing here for the moment
