### ISSUE TITLE
Icon Request: fa-rifle

### ISSUE THREAD

**Issue by rebornclan** [FortAwesome/Font-Awesome#9971]
hello guys,
i have just got a louis theme from wplift.com and i am using your fantastic icons for represent videogames  categories on my site. by the way i am the webmaster of an italian multigaming community. 
i would like you to put some icon which depicts weapons like guns, rifles, sniper, shield. it could be useful for me and other communities which use wordpress and themes on websites.
in the end a simple rifle icon would be enough.

thank you guys, you re doing an amazing work :)
![1](https://cloud.githubusercontent.com/assets/22483833/18892926/dbf97dac-850b-11e6-8a66-22af6908241f.jpg)
![2](https://cloud.githubusercontent.com/assets/22483833/18892925/dbf7c354-850b-11e6-86a6-ad1aa5e0042e.jpg)
![3](https://cloud.githubusercontent.com/assets/22483833/18892924/dbf64448-850b-11e6-8da5-8f670bb5d656.jpg)

**Comment by ryankane** [comment]
I was thinking that a crosshair would be a better choice to represent a FPS game or scoped-rifle&hellip;

![](http://i.imgur.com/FTfJaPd.jpg)

**Comment by rebornclan** [comment]
ok, it's fine, thanks :D how many days will it available on the site? see you

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
