### ISSUE TITLE
Icon Request: icon-imdb

### ISSUE THREAD

**Issue by danlewis** [FortAwesome/Font-Awesome#998]
A request for an IMDB icon.

Would be choice as for actors, directors, and everyone else is in movie/tv land.

Thanks for considering.

**Comment by martimarkov** [comment]
+1

**Comment by resonancedesign** [comment]
+1

**Comment by razor2611** [comment]
+1

**Comment by Cinemeet** [comment]
+1 would be really useful!

**Comment by ramon86** [comment]
+1

**Comment by hallison** [comment]
+1

**Comment by littlestoatie** [comment]
+1 - yes please!

**Comment by jekkilekki** [comment]
+1

**Comment by foomep** [comment]
+1

**Comment by jeroenherczeg** [comment]
+1

**Comment by lepinay** [comment]
+1

**Comment by wot4** [comment]
+1

**Comment by JKetelaar** [comment]
+1

**Comment by G-Driver** [comment]
+1

**Comment by sharonekatz** [comment]
+1

**Comment by AndreiTelteu** [comment]
+1

**Comment by pozharlab** [comment]
+1

**Comment by SergeantJack** [comment]
+1

**Comment by shefik** [comment]
+1

**Comment by NathanKTC** [comment]
+1

**Comment by ruthystapleton** [comment]
+1

**Comment by dickjones00** [comment]
+1

**Comment by kusmayadi** [comment]
+1

**Comment by oraculus** [comment]
+1

**Comment by frbry** [comment]
:+1:

**Comment by djc200** [comment]
:+1:

**Comment by psilentrain1** [comment]
+1

**Comment by msalahz** [comment]
:+1:

**Comment by av3** [comment]
+1

**Comment by NoticeCorp** [comment]
+1

**Comment by bobtiki** [comment]
+1

Thanks for the great icons!

**Comment by cassels** [comment]
+1

**Comment by littlestoatie** [comment]
This is really needed.  This is critical icon for websites of anyone in entertainment: actors, directors, screenwriters, production etc. etc.  Font-awesome has added so many social network icons for sites I couldn't identify if my life depended on it but this often used site still has no icon.  Please add this too!

**Comment by TJohnson93** [comment]
+1

**Comment by neu1886** [comment]
+1

**Comment by Scotttie** [comment]
2 years and still waiting?? 
Awesome suggestion Dan. I'd use it indeed!
+2 from me (once for each year)

**Comment by beacabrera** [comment]
+1 !!!!!!

**Comment by NoticeCorp** [comment]
is this ever gonna happen?

**Comment by jacobkossman** [comment]
+1

**Comment by maahd** [comment]
there are 2 icons for Xing, a social network I have never heard of. 4 icons for YC. Weibo, slideshare, simply built, sellsy, shirtsinbulk and even Yahoo. I have never heard of most of these social networks. I fail to comprehend why we can't have an IMDB icon?

**Comment by RyanThaDude** [comment]
+1 This would be perfect for one of my sites that deals with actors and movies. Figured this would've been a no-brainer, but guess not.

**Comment by feather0148** [comment]
+1

**Comment by bnggge** [comment]
+1

**Comment by JayHoltslander** [comment]
+1

**Comment by bennobo** [comment]
+1

**Comment by kamperez** [comment]
unsubscribe

**Comment by daFish** [comment]
Can you attach a milestone to this issue, @davegandy ?

**Comment by mercitas** [comment]
+1

**Comment by relish27** [comment]
+1

**Comment by kayleesachs** [comment]
+1

**Comment by marse17** [comment]
+1

**Comment by stoi2m1** [comment]
+1

**Comment by moonjo** [comment]
been waiting 2 years! hope to see it added soon

**Comment by Lollipop72** [comment]
This would be great and if you can't do it because you feel it is too close then manipulate it a little and do  IM DB on two lines

**Comment by AaronX** [comment]
+1

**Comment by el-rotny** [comment]
+1

**Comment by chuckdouglas** [comment]
+1

**Comment by hou26** [comment]
+1
![mv5bmtqxnduwmtywof5bml5bcg5nxkftztgwnduzntg0mje _v1_](https://cloud.githubusercontent.com/assets/13068436/11993166/0875b70c-aa69-11e5-8090-71619c4c7ca4.png)

**Comment by Peterdoma** [comment]
+1

**Comment by codynguyen1116** [comment]
+1

**Comment by fieteboerner** [comment]
+1

**Comment by mgrosfeld** [comment]
+1

**Comment by lostdz** [comment]
+1

**Comment by iposton** [comment]
+1

**Comment by pitus** [comment]
+1

**Comment by LattMongoria** [comment]
+1

**Comment by lagunawebdesign** [comment]
+1

**Comment by ThatPascale** [comment]
+1

**Comment by antonmaximus** [comment]
Is there one yet? 

+1

**Comment by josec89** [comment]
+1

**Comment by fredhamm** [comment]
+1

**Comment by thisisjoewells** [comment]
+1 
and thanks for the great library!

**Comment by nancyvannoppen** [comment]
+1

**Comment by avaimedia** [comment]
+1

How has this still not been added? :-/

**Comment by breathelifein** [comment]
So many requests for so many years. Kinda disappointed it still hasn't been done. =/
So,  +1.

**Comment by alexandramisleanu** [comment]
+1

**Comment by alexptbg** [comment]
+1 thks

**Comment by isanchez12** [comment]
This is ridiculous that the IMDB icon is not available and we have been waiting three years. Do we really have to contact Dave Gandy (creator of font awesome) about this? 

+1

**Comment by MDMOSTOFA** [comment]
https://www.iconfinder.com/icons/43153/imdb_icon#size=48

**Comment by Dokioki** [comment]
+1 Have a few movie crew member clients - this would be a useful addition. Thanks

**Comment by lyddy** [comment]
+1

This would be very useful for a website I'm working on for an actor/writer.

It seems like this icon has a lot of long-time interest. I really hope it can get created soon.

Thanks.

**Comment by iamakimmer** [comment]
+1

**Comment by Qoraiche** [comment]
+1 we need it :(

**Comment by xim** [comment]
+1

**Comment by davegandy** [comment]
Added to 4.7.0-wip branch.

**Comment by avery-cm** [comment]
Would love to see one with just the wordmark or with a rectangle (instead of a square) as the current one is barely legible

Made a request here: https://github.com/FortAwesome/Font-Awesome/issues/19114
