### ISSUE TITLE
Icon Request: fa-Laundry

### ISSUE THREAD

**Issue by InsertCart** [FortAwesome/Font-Awesome#9980]
Hi 

I want to request some of new icons
Like:

Laundry
CCTV
Fridge
Air Conditioner 
Housekeeping
Gym
Power - Electricity
elevator
 
![icons](https://cloud.githubusercontent.com/assets/8530386/18955415/049c0256-8675-11e6-927d-d2920a00cc42.png)

**Comment by tagliala** [comment]
Sorry, can't leave this open.

Please take another look at our [Contributing guidelines](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons).
