### ISSUE TITLE
Icon Request: fa-rx

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9982]
Prescription - To be used for Health Data Apps
![rx](https://cloud.githubusercontent.com/assets/539719/18964873/c8b124c8-8648-11e6-8ca9-82cfdf612012.png)

**Comment by tagliala** [comment]
Duplicate of #768 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
