### ISSUE TITLE
Icon Request: fa-disease

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9984]
Disease icon to be used within a healthcare data app
![disease](https://cloud.githubusercontent.com/assets/539719/18966333/cc63f7b6-864e-11e6-81e9-498b051b18f7.png)

**Comment by tagliala** [comment]
Duplicate of #255 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
