### ISSUE TITLE
Icon Request: fa-pill

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9986]
Individual Pill icon to be used within a healthcare data app
![pill](https://cloud.githubusercontent.com/assets/539719/18966375/f4eff25c-864e-11e6-89b0-1ec54a37f8f4.png)

**Comment by tagliala** [comment]
Ref: #1778

**Comment by Crissov** [comment]
💊 [U+1F48A](http://emojipedia.org/pill/) in Unicode #222

**Comment by kimberley-johnston** [comment]
+1

**Comment by sensibleworld** [comment]
There are few options for this in the new Medical category in 5.0.7: https://fontawesome.com/icons?d=gallery&c=medical (Pills, Tablets, Capsules.)
