### ISSUE TITLE
Icon Request: fa-shoe

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9989]
Shoe (i.e. 
![shoe](https://cloud.githubusercontent.com/assets/539719/18966438/2c94357e-864f-11e6-9f3b-a024ef001d4d.png)
diabetic shoe fitting) icon to be used within a healthcare data app

**Comment by tagliala** [comment]
Please do a search for shoe and +1 the proper request

https://github.com/FortAwesome/Font-Awesome/search?q=shoe+label%3A%22new+icon%22&state=open&type=Issues&utf8=%E2%9C%93
