### ISSUE TITLE
Icon Request: fa-support

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9990]
Phone Support icon to be used within a healthcare data app
![support](https://cloud.githubusercontent.com/assets/539719/18966453/37a84360-864f-11e6-9c82-ea07fc055265.png)

**Comment by tagliala** [comment]
Duplicate of ##5586, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
