### ISSUE TITLE
Icon Request: fa-caduceus

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9992]
Medical Caduceus symbol for use within a healthcare data app
![caduceus](https://cloud.githubusercontent.com/assets/539719/18966506/6cfb4f30-864f-11e6-880d-c195871a62e2.png)

**Comment by tagliala** [comment]
Duplicate of #4325 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
