### ISSUE TITLE
Icon Request: fa-patient

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9993]
Patient icon for use within a healthcare data app
![patient](https://cloud.githubusercontent.com/assets/539719/18966511/7a9675ac-864f-11e6-8749-3822fda1b2bc.png)

**Comment by tagliala** [comment]
Duplicate of #3629, please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
