### ISSUE TITLE
Icon Request: fa-infinity

### ISSUE THREAD

**Issue by yesi79** [FortAwesome/Font-Awesome#9998]
Infinite icon for use within a healthcare app
![infinity](https://cloud.githubusercontent.com/assets/539719/18966604/d8b28662-864f-11e6-9093-bf7638e1719e.png)

**Comment by tagliala** [comment]
Duplicate of #1647 , please add a 👍  reaction to that request

Please also [search](https://github.com/FortAwesome/Font-Awesome/search?type=Issues) before opening new requests

Closing here
